### ISSUE TITLE
vcpkg 的 qt5静态连接支持

### ISSUE THREAD

**Issue by nick908** [xmake-io/xmake#1001]
### 你在什么场景下需要该功能？

vcpkg 的 qt5静态连接 
qt5-activeqt:x86-windows-static-md                 5.15.0           Qt5 ActiveQt Module - ActiveX components
qt5-base:x86-windows-static-md                     5.15.0#2         Qt5 Application Framework Base Module. Includes ...
qt5-declarative:x86-windows-static-md              5.15.0           Qt5 Declarative (Quick 2) Module. Includes QtQui...
qt5-imageformats:x86-windows-static-md             5.15.0#1         Qt5 Image Formats Module - Plugins for additiona...
qt5-multimedia:x86-windows-static-md               5.15.0           Qt5 Multimedia Module - Classes and widgets for ...
qt5-networkauth:x86-windows-static-md              5.15.0           Qt5 Network Authorization Module
qt5-quickcontrols2:x86-windows-static-md           5.15.0           Qt5 QuickControls2 Module.
qt5-svg:x86-windows-static-md                      5.15.0           Qt5 SVG Module - provides classes for displaying...
qt5-tools:x86-windows-static-md                    5.15.0           Qt5 Tools Module; Includes deployment tools and ...
qt5:x86-windows-static-md                          5.15.0#2         Qt5 Application Framework
qt5[activeqt]:x86-windows-static-md                                 Windows Only
qt5[declarative]:x86-windows-static-md
qt5[essentials]:x86-windows-static-md                               Build the essential qt modules
qt5[imageformats]:x86-windows-static-md
qt5[multimedia]:x86-windows-static-md
qt5[networkauth]:x86-windows-static-md
qt5[quickcontrols2]:x86-windows-static-md
qt5[svg]:x86-windows-static-md
qt5[tools]:x86-windows-static-md

### cmake
find_package(Qt5 COMPONENTS Widgets REQUIRED)
target_link_libraries(target PRIVATE Qt5::Widgets）

### xmake
add_rules("mode.debug", "mode.release")
add_requires("vcpkg::qt5-activeqt", "vcpkg::qt5-base", "vcpkg::qt5-declarative", {configs = {vs_runtime = "MD"}})
if is_plat("windows") then
    add_cxflags("/MD")
end

target("testqt")
    add_rules("qt.widgetapp_static")
    add_headerfiles("src/*.h")
    add_files("src/*.cpp")
    add_files("src/mainwindow.ui")
    -- add files with Q_OBJECT meta (only for qt.moc)
    add_files("src/mainwindow.h")

PS D:\test\testqt> xmake f -a x86 -m debug
checking for Microsoft Visual Studio (x86) version ... 2019
checking for Qt SDK directory ... no
error: Qt SDK not found!

无法找到Qt SDK

### 描述你认为的候选方案

请尽量清晰精准地描述你能接受的候选解决方案。

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by waruqi** [comment]
vcpkg的qt不支持 暂时也不考虑支持，改动太大，请装qt sdk来编译qt程序

**Comment by nick908** [comment]
> vcpkg的qt不支持 暂时也不考虑支持，改动太大，请装qt sdk来编译qt程序
> 
> 也可以使用 https://github.com/miurahr/aqtinstall 快速安装qt sdk

好的，谢谢
