### ISSUE TITLE
add_links添加的多个库不能解决链接顺序问题

### ISSUE THREAD

**Issue by zwxf** [xmake-io/xmake#1002]
环境：
    实现了一个libcore的核心库，然后实现了多个componet的组件库，组件库是依赖libcore库，组件库有些会引用其他组件库的函数。
问题：
    想问下是否考虑add_links这个接口加上循环查找的flags，目前只能在add_ldflags里面添加flags和库名，如add_ldflags(-Wl,--start-group xxx -Wl,--end-group)。

**Comment by waruqi** [comment]
走add_deps，依赖哪些组件库，都加到add_deps就行了

不行就直接 add_ldflags

**Comment by zwxf** [comment]
主要是这些库函数有交叉调用的，如果不加循环检查的标志，链接会提示找不到函数，所以想问下能否加个属性，如

**Comment by zwxf** [comment]
主要是这些库函数有交叉调用的，如果不加循环检查的标志，链接会提示找不到函数，所以想问下是否有考虑加个属性，如add_links(xxx, xxx, {cycly_search=true})之类的这种功能？

**Comment by waruqi** [comment]
暂时做不了，你可以在 add_ldflags 里面自己处理下

**Comment by zwxf** [comment]
> 
> 
> 暂时做不了，你可以在 add_ldflags 里面自己处理下

**Comment by waruqi** [comment]
初步改进了下，试试 https://github.com/xmake-io/xmake/issues/1452#issuecomment-1741152822
