### ISSUE TITLE
Add more default flags for C++ files with MSVC

### ISSUE THREAD

**Issue by paul-reilly** [xmake-io/xmake#1003]
### /EHsc

`/EHsc` is added as a default flag in CMake-produced ninja and msbuild files :

#### from Ninja output
```
/nologo /TP /DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1 -MDd /showIncludes /FS -c
```

#### from msbuild output
```
/Zi /nologo /W1 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Gd /TP /errorReport:queue
```

I have had errors with vcpkg libraries where I have forgot to specify an exception handling flag with xmake too. I think this is would be a sensible default flag to add.

### /permissive-

I personally think that `/permissive-` would be a good default too since writing non-conformant code is not the usual use case and not having this causes errors with conforming code, eg with `if (x == 1 and b == 2)`, the C++ `and` keyword is not permitted.

**Comment by waruqi** [comment]
Usually xmake will add as few default flags as possible to ensure that users are flexible enough to configure. However, in the new version, users have been able to override the default flags (https://github.com/xmake-io/xmake/issues/978), so adding /EHsc as the default flags is also acceptable.

I have added it in the dev branch, you can update to dev and try it.

However, I still won't add too many default flags. Therefore, I will not add `/permissive-` yet unless it is really necessary.

**Comment by paul-reilly** [comment]
Thanks, that's working!

`/permissive-` isn't really necessary, it's default in VS2017+ but maybe more time needs to pass before it's a good default for everybody.
