### ISSUE TITLE
生成ide工程xmake project 如何指定qt目录

### ISSUE THREAD

**Issue by nick908** [xmake-io/xmake#1005]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

正常： xmake f --qt=c:\Qt
使用ide : xmake project -k vsxmake --qt=c:\Qt
报错

### 期待的结果

xmake f 后的参数   -> 如何在 xmake project 后使用

### 错误信息

error: Invalid option: --qt=c:\Qt
PS D:\test\testqt1>

> 如果是xmake相关编译问题，请加上`-vD`参数运行，并给出详细编译输出信息。

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：
- xmake运行平台：
- xmake目标平台：

### 其他信息

请提供其他附加信息帮助我们诊断问题(比如截图，xmake.lua或者可复现的demo)，以及你遇到的问题的一些背景信息。

**Comment by waruqi** [comment]
所有的配置操作，xmake f 阶段指定，后面的工程生成阶段，会基于之前的配置

```console
xmake f --qt=c:\Qt
xmake project -k vsxmake
```

另外，生成的vsxmake工程，也有专门的xmake工程属性页配置，可以设置一些附加的xmake f 配置选项，里面也可以指定 qt 等路径配置

还有 `xmake g --qt=` 全局配置也可以设置，这要 xmake f 里面就不需要设置了，每次都会自动获取Qt路径，`xmake g` 是会全局设置生效的
