### ISSUE TITLE
Can I export the project environment variables to current shell?

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1010]
### Describe the problem details
例如，当前项目依赖一些库，而这些库包括了可执行文件。有没有办法把当前项目的path环境变量导出到当前shell中，或者把这些库生成的可执行文件都复制到项目的某个文件夹下，这样在当前shell下可以比较方便地执行这些可执行文件？

**Comment by waruqi** [comment]
在仓库中定义的包如果设置了 `package:add("PATH", "bin")` 就会设置上相关环境变量，`add_packages("xxx")` 会自动将xxx包的 所有环境变量自动绑定到指定的 target，这个target的所有 `on_/after_/before_xxx`  脚本内部都可以直接运行xxx包的命令，因为path已经被绑定了

```lua
add_requires("python")
target("test")
    add_packages("python")  --- 绑定path还有其他env环境
    after_build(function (target)
        os.exec("python ...")
    end)
```

也可以用`xrepo env` 命令自动绑定环境加载运行

```console
xrepo env python -- 加载python环境，并运行python
xrepo env -b "python 3.x" python args ... -- 绑定指定包环境，并运行shell
xrepo env -b "python,lua 2.x" bash -- 绑定python, lua 并运行 bash，前提是 xrepo install python lua 已经安装
```
