### ISSUE TITLE
xmake not finding dll files on windows

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1011]
### 描述讨论详情

执行`xmake install <target>`时并没有找到用到的dll文件并复制到可执行文件的同一文件夹下

依赖大概是，test依赖(static)openvdb，后者依赖(shared)openexr等库，能成功编译但xmake run失败，xmake install也没有找到包

手动复制dll文件到安装目录之后程序才能正常运行

main.cpp
```c++
#include <openvdb/openvdb.h>
#include <openvdb/tools/LevelSetSphere.h>
#include <iostream>
int main()
{
    openvdb::initialize();
    openvdb::FloatGrid::Ptr grid = openvdb::tools::createLevelSetSphere<openvdb::FloatGrid>(
        /*radius=*/50.0, /*center=*/openvdb::Vec3f(1.5, 2, 3),
        /*voxel size=*/0.5, /*width=*/4.0);
    std::cout << "done" << std::endl;
}
```

xmake.lua
```lua
add_rules("mode.debug", "mode.release")

add_requires("openvdb")

target("xmake-test")
    set_kind("binary")
    add_packages("openvdb")
    add_files("src/*.cpp")
```

**Comment by waruqi** [comment]
你可以执行 xrepo fetch openvdb 看下 libfiles列表有没有包含进dll

理论上应该都可以，我等有空的时候排查下

**Comment by xq114** [comment]
> 你可以执行 xrepo fetch openvdb 看下 libfiles列表有没有包含进dll
> 
> 理论上应该都可以，我等有空的时候排查下

openvdb是static library，libfiles里面没有dll，它依赖的openexr libfiles里面有dll

**Comment by waruqi** [comment]
那就是 xmake install 逻辑没问题，只是 find_packages 没扫到 openvdb 下的 dll 

你可以看下这块

https://github.com/xmake-io/xmake/blob/b9b7e1f2a07fdf8f54dd1dedb24f744f6c9c3b07/xmake/modules/package/manager/xmake/find_package.lua#L108-L115

应该是已经去找了的，一种可能是你之前测试 openvdb 脚本安装时候，on_install 是老脚本 本机还没copy dll 到bin，可以尝试 

```
xmake require --uninstall openvdb
xmake repo -u
xmake f -c -vD
```

强制重装下 openvdb 试试。

**Comment by xq114** [comment]
> 那就是 xmake install 逻辑没问题，只是 find_packages 没扫到 openvdb 下的 dll
> 
> 你可以看下这块
> 
> https://github.com/xmake-io/xmake/blob/b9b7e1f2a07fdf8f54dd1dedb24f744f6c9c3b07/xmake/modules/package/manager/xmake/find_package.lua#L108-L115
> 
> 应该是已经去找了的，一种可能是你之前测试 openvdb 脚本安装时候，on_install 是老脚本 本机还没copy dll 到bin，可以尝试
> 
> ```
> xmake require --uninstall openvdb
> xmake repo -u
> xmake f -c -vD
> ```
> 
> 强制重装下 openvdb 试试。

没有作用，是不是因为这里没有递归去寻找依赖库的libfiles

**Comment by waruqi** [comment]
跟递归没啥关系，你现在根级就是 openvdb ，你看下 实际 openvdb 安装目录下 bin 目录下 有哪些文件，是否真的存在 dll

**Comment by xq114** [comment]
> 跟递归没啥关系，你现在根级就是 openvdb ，你看下 实际 openvdb 安装目录下 bin 目录下 有哪些文件，是否真的存在 dll

没有。这里应该是把它依赖库的dll都放在这里吗

**Comment by waruqi** [comment]
不是这意思，你不是说openvdb自身的dll没有被加载和安装么，那就确认下openvdb库自身的dll有没有被安装到installdir bin

我看安装脚本有做os.cp

https://github.com/xmake-io/xmake-repo/blob/3f545a0ac473fa47c408adc313af09d64e474b0c/packages/o/openvdb/xmake.lua#L70

至于依赖库的dll，和links绑定，你需要在xmake.lua自己加 add_packages("openvbd", "dep1", "dep2")

自己绑定上，xmake/add_packages不会自动嵌套依赖的自动展开，这样links顺序用户无法随意控制，xmake的处理逻辑也会变复杂

**Comment by xq114** [comment]
> 不是这意思，你不是说openvdb自身的dll没有被加载和安装么，那就确认下openvdb库自身的dll有没有被安装到installdir bin
> 
> 我看安装脚本有做os.cp
> 
> [xmake-io/xmake-repo@`3f545a0`/packages/o/openvdb/xmake.lua#L70](https://github.com/xmake-io/xmake-repo/blob/3f545a0ac473fa47c408adc313af09d64e474b0c/packages/o/openvdb/xmake.lua#L70)
> 
> 至于依赖库的dll，和links绑定，你需要在xmake.lua自己加 add_packages("openvbd", "dep1", "dep2")
> 
> 自己绑定上，xmake/add_packages不会自动嵌套依赖的自动展开，这样links顺序用户无法随意控制，xmake的处理逻辑也会变复杂

啊，那是我表述不当，不好意思，openvdb是静态库链接，本来也没有dll....我说的是它的依赖库dll没有被安装

links顺序不同，但那个只在build的时候有影响，install时把依赖的dll复制过去这个顺序并不影响吧。或者可以加一个选项让用户来判断？比如

```lua
add_packages("openvdb", {install_deps=true})
```

**Comment by waruqi** [comment]
目前 add_packages 还只能 处理当前的包，没有自动追加依赖，所以 xmake install， xmake run 的path绑定，还有 links 集成都只处理被显式 add_packages 绑定的包，因为现在这三者的依赖列表是相同的，单纯改install也会牵扯到links部分

你可以先手动 add_packages 绑定上你需要的依赖包 试试。

如果要在 add_packages 中自动展开关联依赖，牵扯的细节就比较多了，比如：

1. 多个同级的 add_packages 内部都有共同的依赖，那么整体link时候依赖顺序展开 需要xmake自动处理
2. 用户也没法随意控制依赖包之间的link顺序
3. 还要多个包共同依赖的包版本不一致怎么处理，现在手动配置依赖关联，可以自己额外add_requires选择版本
4. shared包，link时候，依赖库又不需要展开，因为自身so已经是link好的

所以你先手动通过 add_packages配置展开好了，这块的改进，我需要花点时间评估下。

**Comment by xq114** [comment]
目前手动加上之后openexr的dll文件可以找到了，但tbb的dll不行，原因未知

**Comment by waruqi** [comment]
openexr的dll? 你不是说 openexr 没dll么。。是依赖库的dll么。。

> 但tbb的dll不行

可以看下 tbb 实际安装的 bin 下有没有 dll，xrepo fetch tbb 是否有 libfiles dll

**Comment by xq114** [comment]
> openexr的dll? 你不是说 openexr 没dll么。。是依赖库的dll么。。

openvdb(static)依赖openexr(dynamic)

> 可以看下 tbb 实际安装的 bin 下有没有 dll，xrepo fetch tbb 是否有 libfiles dll

有的

**Comment by waruqi** [comment]
既然有的，那应该install时候就会去cp了 ，add_package("tbb")后还是不行？

或者xmake f -c 清下工程cache，再去xmake install试试呢？

**Comment by xq114** [comment]
> 既然有的，那应该install时候就会去cp了 ，add_package("tbb")后还是不行？
> 
> 或者xmake f -c 清下工程cache，再去xmake install试试呢？

还是不行。可能是tbb libfile里面既有.lib也有.dll？print(target:installfiles())里面也没有tbb的库。能否指引一下设置target:installfiles()的源码位置，我可以研究一下

xmake.lua
```lua
add_rules("mode.debug", "mode.release")

add_requires("openvdb")
add_requires("tbb", {configs={shared=true}})
add_requires("openexr", {configs={shared=true}})

target("xmake-test")
    set_kind("binary")
    add_packages("openvdb", "tbb", "openexr")
    add_files("src/*.cpp")
```

**Comment by waruqi** [comment]
似乎是有点问题，https://github.com/xmake-io/xmake/issues/1014 这个也是相同的问题。

安装逻辑在这里 https://github.com/xmake-io/xmake/blob/master/xmake/modules/target/action/install/windows.lua

你先看看吧，等晚上有时间，我也会给你们看下。

**Comment by xq114** [comment]
我发现虽然设置了tbb的configs={shared=true}，但在tbb的extrainfo()中没有设置shared，原因未知

**Comment by xq114** [comment]
另外tbb只提供动态链接库（官方表示这个库没法做成静态链接），因此在它的xmake.lua中没有判断是否为shared，是不是这个引起的

**Comment by waruqi** [comment]
> 另外tbb只提供动态链接库（官方表示这个库没法做成静态链接），因此在它的xmake.lua中没有判断是否为shared，是不是这个引起的

**Comment by waruqi** [comment]
> 我发现虽然设置了tbb的configs={shared=true}，但在tbb的extrainfo()中没有设置shared，原因未知

你要是没啥头绪，那就等等吧，这两天等我有时间了给你调下

**Comment by waruqi** [comment]
我改好了，你再更新到dev版本试下。然后重新执行下 `xmake f -c` 清下cache就行了， xmake run/xmake install 应该都可以了

之前不行的原因：

1. add_packages 原本就支持级联依赖，这块我之前搞完已忘记了，不过xmake install之前判断了 add_requires(, "shared=true") d的包才会安装 dll，所以之前你这依赖包 没配置 add_requires 更没设置 shared，所以xmake没去装dll

2. xmake run 不行这块，主要是之前对add_packages的级联依赖只处理了 links/linkdirs/includedirs的依赖展开，而对于 每个包的环境变量并没有合并展开，所以只有 openvbd 一个包的 bin PATH可用

现在我对这两个地方，都做了处理，应该直接add_packages("openvbd")一个包就可以了


另外，我还对 cmake.install 做了改进，默认就会尝试 cp install/bin ，所以以后也不用每个包，都去手动 cp bin 一遍，还有 bin 在 win包下 我也做默认的 PATH 设置，所以，on_install 里面，也不用每次针对 windows平台 设置一遍 bin PATH 

当然，现在xmake-repo 包上，还是可以先保留这些设置，因为这些改动还没发版，等xmake发版后，我会设置 xmake-repo 最小xmake版本提到最新版后，就可以去掉这些 cp bin/ bin PATH的设置了。。

**Comment by waruqi** [comment]
这个可以了么？

**Comment by xq114** [comment]
可以了，不过还有一个问题是多了很多暂时不用的dll，需要在after_install()里面去手动删（例如tbb库在程序中实际链接用到tbb.dll和tbbmalloc.dll，但install的时候所有tbb相关的dll都进去了）。

```lua
target("xmake-test")
    set_kind("binary")
    add_packages("openvdb")
    add_files("src/*.cpp")
    after_install(function(target)
        local dllfiles = {["tbb.dll"] = true,
                          ["tbbmalloc.dll"] = true,
                          ["Half-2_5.dll"] = true}
        for _, file in ipairs(os.files(path.join(os.curdir(), target:installdir(), "bin", "*.dll"))) do
            if dllfiles[path.filename(file)] == nil then
                os.rm(file)
            end
        end
    end)
```

希望能让用户在xmake.lua中声明一个用到的dll列表（可选），如果用户声明了列表，不在这个列表中的dll都不安装，这样相比于手动删没用的dll会省事一些。

**Comment by waruqi** [comment]
这些都是openvdb这个依赖的所有包自身安装的所有dll带进来的，如果真的有些dll 没用，应该package的on_install里面就不要安装进去

Half-2_5.dll这个我这测试是需要的，没有这个demo运行失败

>希望能让用户在xmake.lua中声明一个用到的dll列表（可选），如果用户声明了列表，不在这个列表中的dll都不安装，这样相比于手动删没用的dll会省事一些。

这种太过于定制化需求，我就不搞了，自己after_install自己处理下就好了

**Comment by xq114** [comment]
> 这些都是openvdb这个依赖的所有包自身安装的所有dll带进来的，如果真的有些dll 没用，应该package的on_install里面就不要安装进去
> 
> Half-2_5.dll这个我这测试是需要的，没有这个demo运行失败
> 
> > 希望能让用户在xmake.lua中声明一个用到的dll列表（可选），如果用户声明了列表，不在这个列表中的dll都不安装，这样相比于手动删没用的dll会省事一些。
> 
> 这种太过于定制化需求，我就不搞了，自己after_install自己处理下就好了

这段代码的意思是除了Half-2_5.dll，tbb.dll，tbbmalloc.dll其他的都删掉。或者能否提供一个api，接受一个路径和一个table作为参数，删掉路径下不匹配table的所有文件？这样的api在install的时候也许也会有作用

**Comment by waruqi** [comment]
```lua
    after_install(function(target)
        local dllfiles = import("core.base.hashset").of("tbb.dll", "tbbmalloc.dll", "Half-2_5.dll")
        for _, file in ipairs(os.files(path.join(target:installdir(), "bin", "*.dll"))) do
            if dllfiles:has(path.filename(file) then
                os.rm(file)
            end
        end
    end)
```

即使提供api ，其实跟你自己删，也省不了几行代码，这种还是太过于定制化的需求，暂时不考虑提供。

```lua
    after_install(function(target)
        import("target.action.install")
        local dllfiles = {"tbb.dll", "tbbmalloc.dll", "Half-2_5.dll"}
        install.install(target, {dllfiles = dllfiles})
    end
```

另外我看了下，多余的 dll，这本身应该属于特定package issues，既然install用不到，说明 package/on_install 的时候，就压根不应该 os.cp 安装进去。。

比如 tbb_debug.dll, tbbmalloc_debug.dll，既然 add_requires 用的是 release 包，没指定debug版本，那 package(tbb)/on_install的时候，就不应该安装进去，装了也永远不会用到，add_requires("tbb", {debug=true}) 存储的installdir 也是另外一个位置。

还有 msvcp140.dll, vcruntime140.dll 什么的，如果是为了xp上兼容运行需要，那说明xmake install 的确实也需要，如果开发者觉得不需要安装到 xp 环境，压根不需要这些dll，那就得在特定package定义中，增加 add_configs("withxp") 包配置就好（默认可以不启用），只有 add_requires("xxx", {configs = {withxp = true}}) 时候，才会去安装上这些dll

![Snip20201109_19](https://user-images.githubusercontent.com/151335/98541156-f0e14c80-22c9-11eb-8ac8-bebc29579f07.png)

**Comment by xq114** [comment]
了解了，谢谢。另外tbb中windows上的安装是用的pre-compiled binary

```lua
os.cp("tbb/bin/intel64/vc14/**", package:installdir("bin"))
```

请问有什么办法排除掉*_debug.*吗，还是只能先装再删呢

**Comment by waruqi** [comment]
```lua
os.cp("tbb/bin/intel64/vc14/**|*_debug.dll", package:installdir("bin"))
```

试试，add_files/os.cp 都是走的files 模式配置，支持用多个 |*.dll 去排除子文件的，具体使用可以参考 add_files 接口文档。。

不行的话，也可以直接 用 for os.files 自己遍历后过滤。
