### ISSUE TITLE
Package dll copy doesn't work

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#1014]
### Describe the bug
When installing a target on Windows, dependencies dll don't seem to be copied.

### Expected behavior
Following #961 I expected xmake would copy dependencies dll to the install folder.

### Related Environment

- xmake version: xmake v2.3.8+202010172345
- os: Windows 10 2004
- target platform: Windows 10

### Additional context

xmake.lua:
```lua
-- Add dev repository (because of a compilation bug of libcurl 7.64 on Windows due to tests, see https://github.com/xmake-io/xmake-repo/pull/105 )
add_repositories("xmake-repo-dev https://github.com/xmake-io/xmake-repo.git")

add_rules("mode.debug", "mode.release")

add_requires("libcurl")

target("test_curl")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("libcurl")
```

src/main.cpp:
```cpp
#include <curl/curl.h>

int main()
{
  CURL* curl = curl_easy_init();
  if(curl) {
    curl_easy_cleanup(curl);
  }
  return 0;
}
```

Command-line:
```bash
PS C:\Projets\Tests\xmake-build\test_curl2> xmake.exe
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2019
updating repositories .. ok
[ 50%]: compiling.release src\main.cpp
[ 75%]: linking.release test_curl.exe
[100%]: build ok!
PS C:\Projets\Tests\xmake-build\test_curl2> xmake.exe install -v -o install
installing test_curl ..
installing to install ..
> copy build\windows\x64\release\test_curl.exe to install\bin
install ok!
```
As you can see, libcurl.dll is not copied, and executing test_curl.exe doesn't work because of that.

Side-node: how can I copy dependencies dll after building instead of installing?

**Comment by waruqi** [comment]
The libcurl static library is installed by default, you need to install the libcurl dynamic library.

```
add_requires("libcurl", {configs = {shared = true}})
```

In addition, please update the repo first. I just improved the libcurl package today to distinguish between static libraries and dynamic libraries.  

https://github.com/xmake-io/xmake-repo/blob/3f545a0ac473fa47c408adc313af09d64e474b0c/packages/l/libcurl/xmake.lua#L34

```
xmake repo -u
```

**Comment by SirLynix** [comment]
Alright, but here test_curl.exe is linked to libcurl.dll (the dynamic version).
![image](https://user-images.githubusercontent.com/3002461/98356872-9f646380-2024-11eb-823d-bc9c817fdb10.png)

I tried with the shared config as well, and got the same output, libcurl.dll is not copied to the install folder 😞

**Comment by waruqi** [comment]
ok, I will look at it.

**Comment by waruqi** [comment]
This is because libcurl/on_install did not copy bin/*.dll to the installation directory. Considering that cmake/install usually copies dll to the bin directory, I improved xmake to copy the bin directory to the installation directory by default.

You can update to dev version and reinstall libcurl again.

```console
xmake update -s dev
cd projectdir
xmake require --uninstall --extra="{configs={shared=true}}" libcurl
xmake f -c -vD
xmake -rv
xmake install -o install
```

**Comment by SirLynix** [comment]
Still no libcurl.dll in the install folder 😞, but I think I'm not on the lastest xmake version.

```
PS C:\Users\Lynix> xmake --version
xmake v2.3.8+202010172345, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, xmake.io

    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor
```

The timestamp seems to indicate i'm on a two weeks old version, but I did execute `xmake update -s dev` 🤔

**Comment by waruqi** [comment]
> Still no libcurl.dll in the install folder 😞, but I think I'm not on the lastest xmake version.

It works for me. 

> The timestamp seems to indicate i'm on a two weeks old version, but I did execute xmake update -s dev 🤔

It only is the timestamp of core binary. `xmake update -s dev` only update lua scripts.

You can view this patch line in your xmake program dir: https://github.com/xmake-io/xmake/blob/ba62268d4a1cd7db9e66f52e08a393eb6cc2df90/xmake/modules/package/tools/cmake.lua#L349

**Comment by waruqi** [comment]
Or you can download full install package from ci: https://github.com/xmake-io/xmake/actions/runs/349530111

**Comment by SirLynix** [comment]
I really don't understand, I did it three times already, checked the xmake/modules/package/tools/cmake.lua file (it has the change) and nothing shows up in the install folder.

Here's the log:
```
PS C:\Projets\Tests\xmake-build\test_curl> xmake require --uninstall --extra="{configs={shared=true}}" libcurl
uninstall: libcurl-7.73.0 ok!
PS C:\Projets\Tests\xmake-build\test_curl> xmake f -c
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2019
note: try installing these packages (pass -y to skip confirm)?
in xmake-repo:
  -> libcurl 7.73.0
please input: y (y/n)
y
  => install libcurl 7.73.0 .. ok
PS C:\Projets\Tests\xmake-build\test_curl> xmake -r
[ 50%]: compiling.release src\main.cpp
[ 75%]: linking.release test_curl.exe
[100%]: build ok!
PS C:\Projets\Tests\xmake-build\test_curl> xmake install -v -o install
installing test_curl ..
installing to install ..
> copy build\windows\x64\release\test_curl.exe to install\bin
install ok!
```

Here's the same log but with verbose informations (much longer):
https://hastebin.com/anedugicuz.md

**Comment by SirLynix** [comment]
By cleaning xmake folders before trying again, it works now!

```
PS C:\Projets\Tests\xmake-build\test_curl> xmake install -v -o install
installing test_curl ..
installing to install ..
> copy build\windows\x64\release\test_curl.exe to install\bin
> copy C:\Users\Lynix\AppData\Local\.xmake\packages\l\libcurl\7.73.0\c82b552ecf5d4943b33f0805174bfe1c\bin\libcurl.dll to install\bin
install ok!
```

Thank you sir!

One last thing, is it possible to copy dependencies libraries when building the first time (or everytime)?

**Comment by waruqi** [comment]
you can try

```lua
target("test")
    set_installdir("build/install")
    after_build(fucntion (target)
        import("target.action.install")(target)
    end)
```

**Comment by SirLynix** [comment]
It works, once again thank you! 😄

**Comment by SirLynix** [comment]
It seems it stopped working again.

```lua
add_rules("mode.debug", "mode.release")

add_requires("libcurl")

if (is_plat("windows")) then
	add_cxflags(is_mode("debug") and "/MDd" or "/MD")
end 

target("test_curl")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("libcurl")
```

```
lynix@SirLynixVanDesktop:/mnt/c/Projets/Tests/xmake-build/test_curl3$ xmake.exe
[ 50%]: compiling.release src\main.cpp
[ 75%]: linking.release test_curl.exe
[100%]: build ok!
lynix@SirLynixVanDesktop:/mnt/c/Projets/Tests/xmake-build/test_curl3$ xmake.exe install -vo test_install
installing test_curl ..
installing to test_install ..
> copy build\windows\x64\release\test_curl.exe to test_install\bin
install ok!
```
