### ISSUE TITLE
Patches for local repository don't work

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#1018]
### Describe the bug
While working on https://github.com/xmake-io/xmake-repo/pull/120 I was trying to make a patch for chipmunk2d, and it seems patches don't work for local repositories.

### Expected behavior
That patches worked for local repositories as well

### Error output

```powershell
PS C:\Projets\Burgwar\BurgWar> xmake.exe -vD
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2019
checkinfo: cannot runv(unzip.exe -v), No such file or directory
finding concurrentqueue from xmake ..
finding libcurl from xmake ..
finding nlohmann_json from xmake ..
finding fmt from xmake ..
finding chipmunk2d from xmake ..
finding chipmunk2d from vcpkg ..
finding chipmunk2d from conan ..
finding chipmunk2d from pkg_config ..
finding chipmunk2d from system ..
finding stackwalker from xmake ..
finding stackwalker from vcpkg ..
finding stackwalker from conan ..
finding stackwalker from pkg_config ..
finding stackwalker from system ..
note: try installing these packages (pass -y to skip confirm)?
in test-repo:
  -> chipmunk2d 7.0.3
please input: y (y/n)
y
error: @programdir\actions\require\impl\actions\patch_sources.lua:84: patch(xmake-repo\packages\c\chipmunk2d\patches\7.0.3\android.patch): not found!
```

### Related Environment

Please provide compiling and running environment information:

- xmake version: xmake v2.3.8+202010172345
- os: Windows 10 2004
- target platform: Windows 10

### Additional context

When committing the exact same files I used on my local repository to xmake-repo (see https://github.com/xmake-io/xmake-repo/pull/120/commits/b4fe789776054f4ad13a74462bbcb0ffb1748c48), there was no problem when patching, that's why I think the issue comes from local repositories.

**Comment by waruqi** [comment]
I have fixed this problem. You can update to dev and try it again. `xmake update -s dev`

**Comment by SirLynix** [comment]
I can confirm it's fixed, thank you!
