### ISSUE TITLE
Add detection for `find_vulkan`

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1027]
### 你在什么场景下需要该功能？

使用[vulkan sdk](https://www.lunarg.com/vulkan-sdk/)库，主要用到glslc/glslangValidator/vkconfig等工具、Include的头文件和Lib下的库链接

### 描述可能的解决方案

加一个find_vulkan.lua?

### 其他信息

文档里面没有说怎么提交自己的detect方案到`xmake/modules/detect`，然后好像也没有比较简单的办法建立自己的detect库来测试（类似xmake-repo）以及加入ci的测试。从逻辑上这块应该是和xmake-repo差不多的，或许在3.0版本可以把这个detect的一部分从主程序里分出来单独维护？

**Comment by waruqi** [comment]
> 或许在3.0版本可以把这个detect的一部分从主程序里分出来单独维护？

不考虑单独维护，sdk 原本就不多，没必要，单独维护还要考虑 xmake 版本兼容性，维护工作量只会更大。

> 然后好像也没有比较简单的办法建立自己的detect库来测试（类似xmake-repo）以及加入ci的测试

自己用，就自己的项目里 搞个 find_vulkan.lua ，用 import 导入后不就可以用了么，里面自己想怎么实现都可以，返回什么内容都可以。

>  文档里面没有说怎么提交自己的detect方案到xmake/modules/detect

如果要内置到 xmake 中收录，那就提pr 到 https://github.com/xmake-io/xmake/tree/master/xmake/modules/detect/sdks ，并参考其他的 find_xxx 返回基础的 sdkdir bindir 等等基础信息，返回的结果也没啥规范，主要还是根据不同 SDK 能提供哪些信息而定。。就比如 find_vstudio 返回的就跟 find_qt 的完全不同。。

**Comment by xq114** [comment]
好的，谢谢
