### ISSUE TITLE
a slow build because of a timeout while using "ping" util

### ISSUE THREAD

**Issue by dm1try** [xmake-io/xmake#1029]
It looks like `ping` is used for some url caching, but it fails with a timeout on my end.

### Expected behavior
A fast build.

### Error output
<img width="859" alt="Screen Shot 2020-11-12 at 01 36 02" src="https://user-images.githubusercontent.com/486807/98872921-790d5080-2488-11eb-8279-ce572a2ceac7.png">

### Related Environment

Please provide compiling and running environment information:

- xmake version: v2.3.8+202010181133
- os: Mac OS Big Sur 11.0.1 Beta

### Additional context
The workaround is disabling Stealth mode in Security Preferences:
<img width="625" alt="Screen Shot 2020-11-12 at 01 44 30" src="https://user-images.githubusercontent.com/486807/98873132-da352400-2488-11eb-8cc7-5dcad1dbbe80.png">

**Comment by waruqi** [comment]
Can you let me see your xmake.lua?

**Comment by dm1try** [comment]
@waruqi  sure
```lua
package("libaco")
  set_urls("git@github.com:hnes/libaco.git")
  add_versions("v1.2.4", "v1.2.4")
  on_install("macosx", "linux", function (package)
    os.vrun("cc -c aco.c acosw.S")
    os.vrun("ar -rv libaco.a aco.o acosw.o")
    os.cp("*.h", package:installdir("include"))

  end)
package_end()

add_requires("libpq")
add_requires("readline")
add_requires("luajit")
add_requires("libaco")
add_requires("libuv")

target("console")
  set_kind("binary")
  add_files("src/console.c", "src/pg.c")
  add_packages("libpq", "luajit","readline", "libaco")
  if is_plat("macosx") then
    add_ldflags("-pagezero_size100000")
  end

target("web")
  set_kind("binary")
  add_files("src/main.c", "src/pg.c")
  add_packages("libpq", "luajit","readline", "libaco", "libuv")
  if is_plat("macosx") then
    add_ldflags("-pagezero_size100000")
  end
```

**Comment by waruqi** [comment]
ok, I will improve find_ping.lua and set a short timeout.

**Comment by waruqi** [comment]
I have improved it, you can update to dev branch and try it again.  `xmake update -s dev`

**Comment by dm1try** [comment]
@waruqi nice, thanks!

I confirm, the build is much faster now.
