### ISSUE TITLE
Can I use /**/ in Windows registry string?

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1032]
# 描述讨论详情

目前在Windows下找注册表项只能是用"$(reg PATH;NAME)"的形式，能否在PATH或者NAME中加通配符（"*%.*"，"**|*d*"这样的）？

使用场景：自定义find_package时需要找已安装的软件，然而这个软件在注册表中的形式是"XXX 18.x.x.x"这样的，导致无法使用完整路径匹配。在path中加通配符后发现find_path找不到目录了。

**Comment by waruqi** [comment]
这块是可以改进，但是需要花时间改造现有 https://github.com/xmake-io/xmake/blob/master/core/src/xmake/winos/registry_query.c 的实现，加上 lua 的 模式匹配，我暂时没时间去看这块，即使要支持，也要等 2.3.9 之后的下一个版本了

当前 2.3.9  版本，我快要发版了，目前不考虑加新特性和改进了，只解决稳定性问题

**Comment by waruqi** [comment]
我支持上了，你可以看下这个：https://github.com/xmake-io/xmake/pull/1162

通过 winos.registry_keys 模式匹配获取需要的 key path 列表，如果 keypath 固定，仅仅想模式匹配 value 名，可以用 winos.registry_values 

获取到对应 keypath 和 value name 后，就可以用 winos.registry_query 获取实际的 value 值

```lua
local keypaths = winos.registry_keys("HKEY_LOCAL_MACHINE\\SOFTWARE\\*\\Windows NT\\*\\CurrentVersion\\AeDebug")
for _, keypath in ipairs(keypaths) do
    print(winos.registry_query(keypath .. ";Debugger"))
end

local valuepaths = winos.registry_values("HKEY_LOCAL_MACHINE\\SOFTWARE\\xxx\\Windows NT\\xxx\\CurrentVersion\\AeDebug;Debug*")
for _, valuepath in ipairs(valuepaths) do
    print(winos.registry_query(valuepath))
end
```

**Comment by xq114** [comment]
我发现这个方法可以成功访问到REG_SZ类型和REG_DWORD类型，但对REG_EXPAND_SZ类型无效，报错
```
get registry value failed: HKEY_LOCAL_MACHINE\SOFTWARE\LunarG\VulkanSDK;VK_SDK_PATHs
```

**Comment by waruqi** [comment]
我回头看下

**Comment by waruqi** [comment]
你是指哪个接口？ 我 query/values试了下，都可以的么，没啥问题

![Snip20210106_16](https://user-images.githubusercontent.com/151335/103772656-d4148b80-5064-11eb-8a63-fe74a2915908.png)

**Comment by xq114** [comment]
![image](https://user-images.githubusercontent.com/42310255/103846713-b6353e00-50d9-11eb-9373-771f5cf5f0e1.png)

好像REG_EXPAND_SZ也不一定出错

**Comment by waruqi** [comment]
那就不知道了，看了下，REG_EXPAND_SZ 的值里面带有 %xx% 的，可以正常查到，如果没带 %xx%，纯文本，就会失败，具体为啥我也不清楚 

https://github.com/xmake-io/xmake/blob/master/core/src/xmake/winos/registry_query.c

**Comment by waruqi** [comment]
我改了下 你再试试

**Comment by xq114** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-reggetvaluea

https://github.com/xmake-io/xmake/blob/cf4d9172c96f24ea44ab02e74fbeaf6baa3ffbb2/core/src/xmake/winos/registry_query.c#L106-L112

我觉得这里应该是expand的时候失败了，失败之后再试一次
```
s_RegGetValueA(key, rootdir, valuename, RRF_RT_ANY | RRF_NO_EXPAND, &type, (PVOID)value, &valuesize)
```
可能就好了

**Comment by waruqi** [comment]
> https://docs.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-reggetvaluea
> 
> https://github.com/xmake-io/xmake/blob/cf4d9172c96f24ea44ab02e74fbeaf6baa3ffbb2/core/src/xmake/winos/registry_query.c#L106-L112
> 
> 我觉得这里应该是expand的时候失败了，失败之后再试一次
> 
> ```
> s_RegGetValueA(key, rootdir, valuename, RRF_RT_ANY | RRF_NO_EXPAND, &type, (PVOID)value, &valuesize)
> ```
> 
> 可能就好了

已经改了

**Comment by xq114** [comment]
现在可以了
