### ISSUE TITLE
The sorting of options is not stable in graphical menu configuration

### ISSUE THREAD

**Issue by jonathanpoelen** [xmake-io/xmake#1036]
### Describe the bug

The options are not sorted in the same way between two runs of `xmake f --menu`. It becomes difficult to find an option when it changes places all the time.

### Expected behavior

A stable sort between 2 executions, preferably that of the lua sources.

**Comment by waruqi** [comment]
I have fixed it. You can update to dev version and try it again.

**Comment by jonathanpoelen** [comment]
I confirm it's fixed, thanks.
