### ISSUE TITLE
option on the command line for the build folder

### ISSUE THREAD

**Issue by jonathanpoelen** [xmake-io/xmake#1038]
### Is your feature request related to a problem? Please describe.

I would like to generate my compilations in another folder tree in order to:

- not clutter up my working folder
- compile in a memory folder

Additionally, this allows compilations from a read-only disk.

### Describe the solution you'd like

Command line options to put systematically:

- `-B DIR`, `--build-path=DIR` for `build` directory
- `-C DIR`, `--config-path=DIR` for `.xmake` directory

### Describe alternatives you've considered

Symbolic link, but it doesn't work for a read-only disk.

**Comment by waruqi** [comment]
```console
export XMAKE_CONFIG_DIR=config_path
xmake f -o build_path
xmake
```

**Comment by jonathanpoelen** [comment]
`XMAKE_CONFIG_DIR` seems not to be used

```sh
$  ls -a                         
.  ..  src  xmake.lua

$  export XMAKE_CONFIG_DIR=../b/c
$  xmake f -o ../b/hello
checking for architecture ... x86_64

$  ls -a
.  ..  src  .xmake  xmake.lua
```

Ok for `-o build_path`

```sh
$ xmake
$ ls -a
.  ..  src  .xmake  xmake.lua
$ ls ../b/hello/linux/x86_64/release/
hello
```

**Comment by jonathanpoelen** [comment]
Finally it works with `XMAKE_CONFIGDIR` (without `_`).

**Comment by waruqi** [comment]
> Finally it works with `XMAKE_CONFIGDIR` (without `_`).

oh, my typo. you can also run `xmake show -l envs` to view all supported envs.
