### ISSUE TITLE
target增加运行依赖dll

### ISSUE THREAD

**Issue by nick908** [xmake-io/xmake#1039]
### 描述问题
运行依赖dll目录，
（1） dll 目录 d:\test\testqt\bin
（2） xmake.lua 在d:\test\testqt目录
（3）add_runenvs("PATH", "$(scriptdir)/bin")     （**运行错误**）
       add_runenvs("PATH", "D:/test/testqt/bin")     （**运行正常**）
       add_rpathdirs("D:/test/testqt/bin")               （**运行错误**）

**工程目录**
D:/test/testqt/
│  .gitignore
│  1.txt
│  xmake.lua
│  
├─bin
│      device.dll
│                  
├─inc
│      HCameraLists.h
│      htdevdefs.h
│      IHCamera.h
│      
├─lib
│      device.lib
│      
└─src
        main.cpp
        widget.cpp
        widget.h
        widget.ui

**xmake.lua**
target("testqt")
    add_rules("qt.widgetapp_static")
    add_headerfiles("src/*.h")
    add_files("src/*.cpp")
    add_files("src/*.ui")
    add_defines("WIN32")

    -- add files with Q_OBJECT meta (only for qt.moc)
    add_files("src/widget.h")

    add_linkdirs("lib")
    add_includedirs("inc")
    add_links("device")
    add_runenvs("PATH", "$(scriptdir)/bin")
    --add_runenvs("PATH", "D:/test/testqt/bin") 
    add_rpathdirs("D:/test/testqt/bin") 

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 错误信息

如果可能，请尽量附加程序运行过程中的错误输出信息。

> 如果是xmake相关编译问题，请加上`-vD`参数运行，并给出详细编译输出信息。

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：
- xmake运行平台：windows
- xmake目标平台：

### 其他信息

请提供其他附加信息帮助我们诊断问题(比如截图，xmake.lua或者可复现的demo)，以及你遇到的问题的一些背景信息。

**Comment by waruqi** [comment]
> add_rpathdirs("D:/test/testqt/bin") （运行错误）

rpath 只有 linux/macos才有效，windows上dll不支持这东西，只能走 PATH 路径

> （3）add_runenvs("PATH", "$(scriptdir)/bin") （运行错误）

scriptdir 路径获取错误，我dev上修复了，你再试试

**Comment by nick908** [comment]
> > add_rpathdirs("D:/test/testqt/bin") （运行错误）
> 
> rpath 只有 linux/macos才有效，windows上dll不支持这东西，只能走 PATH 路径
> 
> > （3）add_runenvs("PATH", "$(scriptdir)/bin") （运行错误）
> 
> scriptdir 路径获取错误，我dev上修复了，你再试试

已经正常了，谢谢
