### ISSUE TITLE
"xrepo search *" failing on hpsocket

### ISSUE THREAD

**Issue by paul-reilly** [xmake-io/xmake#1045]
### Describe the bug
Running `xrepo search *` fails on hpsocket package.

### Error output
```
-> xrepo search *
The package names:
error: ...positories\xmake-repo\packages\h\hpsocket\port\xmake.lua:1: attempt to call global 'add_rules' (a nil value)
stack traceback:
    [...positories\xmake-repo\packages\h\hpsocket\port\xmake.lua:1]: in main chunk

error: execv(xmake require --search *) failed(-1)
```
`xrepo search h*` also fails. 

`xrepo search hpsocket` succeeds.

### Related Environment
- xmake version: v2.3.8+202011151103
- os: Win 10
- target platform: n/a

**Comment by waruqi** [comment]
I have fixed it on dev branch.

**Comment by paul-reilly** [comment]
That was quick, good stuff!
