### ISSUE TITLE
Pass local repository on xmake invoking package.tools.xmake

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1046]
### 你在什么场景下需要该功能？

使用非官方repo时在里面加了两个包A和B，B依赖A并且用`io.writefile("xmake.lua", ...);import("package.tools.xmake").install(package)`方式安装，B的xmake.lua里面会有add_requires("A")。然而安装的时候只会到官方repo去找A这个包，所以会直接安装失败，提示找不到A包

### 描述可能的解决方案

在调用import("package.tools.xmake")的时候传入local repository的位置，让被调用的xmake和调用者共用同一个local repository

### 附加信息

https://github.com/xmake-io/xmake-repo/pull/136

**Comment by waruqi** [comment]
回头我改进下，你可以先设置全局local repo，xmake repo --add --global ...

**Comment by waruqi** [comment]
我透传进去了，不过还没测试过，你这帮忙测试下吧，dev分支

**Comment by xq114** [comment]
> 我透传进去了，不过还没测试过，你这帮忙测试下吧，dev分支

可以了
