### ISSUE TITLE
qt5 静态链接， 无法打开输入文件“Qt5PlatformSupport.lib”

### ISSUE THREAD

**Issue by nick908** [xmake-io/xmake#1047]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

qt 5.12.9 静态链接  无法打开输入文件“Qt5PlatformSupport.lib”

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 错误信息

PS D:\test\testqt> xmake f -a x64
checking for Microsoft Visual Studio (x64) version ... 2019
checking for Qt SDK directory ... C:/qt/Qt5.12X64
checking for Qt SDK version ... 5.12.9
PS D:\test\testqt> xmake
[ 25%]: compiling.qt.moc src\widget.h
[ 75%]: compiling.release build\.qt\plugin\testqt\static_import.cpp
[ 87%]: linking.release testqt.exe
error: LINK : fatal error LNK1181: 无法打开输入文件“Qt5PlatformSupport.lib”

warning: target(testqt).add_includedirs("C:\qt\Qt5.12X64\include\QtPlatformSupport") path not found at @programdir\rules\qt\load.lua:211
warning: add -v for getting more warnings ..
PS D:\test\testqt>

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：
- xmake运行平台：vs 2019
- xmake目标平台：windows 10

### 其他信息

请提供其他附加信息帮助我们诊断问题(比如截图，xmake.lua或者可复现的demo)，以及你遇到的问题的一些背景信息。

**Comment by waruqi** [comment]
静态链接 得用支持静态链接的qt sdk，给我看下 你这 Qt5PlatformSupport.lib 所在库路径，确认下库是否，如果你的qt sdk里面没有这个库，那就支持不了了

我记得这个库应该是必须的

**Comment by nick908** [comment]
编译的qt静态库，qtcreator 编译运行没问题。

https://github.com/xmake-io/xmake/issues/619

"Qt5PlatformSupport" has been renamed to “Qt5PlatformCompositorSupport” after Qt 5.9

Starting with QT 5.9+ Qt5PlatformSupport.lib is no longer available and has been split into different libraries. To create a static build under windows one needs to link the following additional libraries:

Qt5FontDatabaseSupport.lib
Qt5EventDispatcherSupport.lib
Qt5ThemeSupport.lib
Qt5PlatformCompositorSupport.lib
Qt5AccessibilitySupport.lib
Qt5WindowsUiAutomationSupport.lib
qwindows.lib
and load the windows plugin statically:

#include <QtPlugin>
Q_IMPORT_PLUGIN (QWindowsIntegrationPlugin);

**Comment by waruqi** [comment]
那就是5.9改名了 我回头改下

**Comment by waruqi** [comment]
你再更新下试试呢

**Comment by nick908** [comment]
参考 ：https://stackoverflow.com/questions/57373791/using-qt-static-what-lib-is-required-for-qwindowsguieventdispatcher-qwindows


**release（MT）需要添加**
   add_links("Version", "Userenv","Netapi32", "Dwmapi", "wtsapi32")
    add_links("Qt5WindowsUiAutomationSupport", "Qt5FontDatabaseSupport", "Qt5ThemeSupport","Qt5EventDispatcherSupport")
**debug（MTd）需要添加**
 _add_cxflags("/MTd")_
qt_add_static_plugins("QSvgPlugin", {linkdirs = "plugins/imageformats", links = {"qsvgd"}})
add_links("Qt5WindowsUiAutomationSupportd", "Qt5FontDatabaseSupportd", "Qt5ThemeSupportd","Qt5EventDispatcherSupportd")

可以正常编译运行，目前使用的是

**xmake.lua**
add_rules("mode.debug", "mode.release")

includes("qt_add_static_plugins.lua")

target("qttt")
    add_rules("qt.widgetapp_static")
    add_headerfiles("src/*.h")
    add_files("src/*.cpp")
    add_files("src/mainwindow.ui")
    --add_cxflags("/MD")

    -- add files with Q_OBJECT meta (only for qt.moc)
    add_files("src/mainwindow.h")
    add_links("Version", "Userenv","Netapi32", "Dwmapi", "wtsapi32")
    if is_mode("debug") then
        add_cxflags("/MTd")
        add_links("Qt5WindowsUiAutomationSupportd", "Qt5FontDatabaseSupportd", "Qt5ThemeSupportd","Qt5EventDispatcherSupportd")
    else 
        add_links("Qt5WindowsUiAutomationSupport", "Qt5FontDatabaseSupport", "Qt5ThemeSupport","Qt5EventDispatcherSupport")
    end

    -- add plugin: QSvgPlugin (optional)
    add_frameworks("QtSvg")
    if is_mode("debug") then
        qt_add_static_plugins("QSvgPlugin", {linkdirs = "plugins/imageformats", links = {"qsvgd"}})
    else 
        qt_add_static_plugins("QSvgPlugin", {linkdirs = "plugins/imageformats", links = {"qsvg"}})
    end

**Comment by nick908** [comment]
> 参考 ：https://stackoverflow.com/questions/57373791/using-qt-static-what-lib-is-required-for-qwindowsguieventdispatcher-qwindows
> 
> **release（MT）需要添加**
> add_links("Version", "Userenv","Netapi32", "Dwmapi", "wtsapi32")
> add_links("Qt5WindowsUiAutomationSupport", "Qt5FontDatabaseSupport", "Qt5ThemeSupport","Qt5EventDispatcherSupport")
> **debug（MTd）需要添加**
> _add_cxflags("/MTd")_
> qt_add_static_plugins("QSvgPlugin", {linkdirs = "plugins/imageformats", links = {"qsvgd"}})
> add_links("Qt5WindowsUiAutomationSupportd", "Qt5FontDatabaseSupportd", "Qt5ThemeSupportd","Qt5EventDispatcherSupportd")
> 
> 可以正常编译运行，目前使用的是
> 
> **xmake.lua**
> add_rules("mode.debug", "mode.release")
> 
> includes("qt_add_static_plugins.lua")
> 
> target("qttt")
> add_rules("qt.widgetapp_static")
> add_headerfiles("src/_.h") add_files("src/_.cpp")
> add_files("src/mainwindow.ui")
> --add_cxflags("/MD")
> 
> ```
> -- add files with Q_OBJECT meta (only for qt.moc)
> add_files("src/mainwindow.h")
> add_links("Version", "Userenv","Netapi32", "Dwmapi", "wtsapi32")
> if is_mode("debug") then
>     add_cxflags("/MTd")
>     add_links("Qt5WindowsUiAutomationSupportd", "Qt5FontDatabaseSupportd", "Qt5ThemeSupportd","Qt5EventDispatcherSupportd")
> else 
>     add_links("Qt5WindowsUiAutomationSupport", "Qt5FontDatabaseSupport", "Qt5ThemeSupport","Qt5EventDispatcherSupport")
> end
> 
> -- add plugin: QSvgPlugin (optional)
> add_frameworks("QtSvg")
> if is_mode("debug") then
>     qt_add_static_plugins("QSvgPlugin", {linkdirs = "plugins/imageformats", links = {"qsvgd"}})
> else 
>     qt_add_static_plugins("QSvgPlugin", {linkdirs = "plugins/imageformats", links = {"qsvg"}})
> end
> ```

https://github.com/xmake-io/xmake/issues/1031
1031的问题是qt5.6.3的，当前问题是qt5.12.9

**Comment by waruqi** [comment]
?? 现在到底还有啥问题呢？你刚反馈的 Qt5PlatformSupport 的问题，到底解了么？

**Comment by nick908** [comment]
> ?? 现在到底还有啥问题呢？你刚反馈的 Qt5PlatformSupport 的问题，到底解了么？

已经解决了，主要是报告给你一下
qt5.12.9 需要添加
add_links("Version", "Userenv","Netapi32", "Dwmapi", "wtsapi32")
add_links("Qt5WindowsUiAutomationSupport", "Qt5FontDatabaseSupport", "Qt5ThemeSupport","Qt5EventDispatcherSupport")

**Comment by waruqi** [comment]
哦 这块我回头会补进去

**Comment by waruqi** [comment]
关于静态库链接和插件这块，我下版本会稍微做些重构，来简化配置，当前2.3.9版本暂时先不动了，我最近会先发个版。

**Comment by nick908** [comment]
> 关于静态库链接和插件这块，我下版本会稍微做些重构，来简化配置，当前2.3.9版本暂时先不动了，我最近会先发个版。

未来版本是否可以考虑识别vcpkg的qt sdk？

**Comment by waruqi** [comment]
> > 关于静态库链接和插件这块，我下版本会稍微做些重构，来简化配置，当前2.3.9版本暂时先不动了，我最近会先发个版。
> 
> 未来版本是否可以考虑识别vcpkg的qt sdk？

这个看情况吧 最近issues排满了，下个版本也不一定有时间搞这个，vcpkg的qt结构完全不同，弄起来很花时间，还得处理3个平台

还是先把常用的qt sdk搞好再说吧

**Comment by nick908** [comment]
好的，已经解决了。谢谢
