### ISSUE TITLE
7z not properly extracting .tgz files

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1048]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

![image](https://user-images.githubusercontent.com/42310255/99213933-e2cf8680-2809-11eb-8c77-290f3d75e611.png)

如图所示，使用7z解压tgz文件只解压到tar这一步就停了，没有继续解压得到完整文件夹

### 期待的结果

解压得到完整文件夹

### 错误信息

<details>
<summary>Details</summary>

checking for 7z ... ok
7z x -y icu4c-68.1.tgz -osource.tmp

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 24722348 bytes (24 MiB)

Extracting archive: icu4c-68.1.tgz
--
Path = icu4c-68.1.tgz
Type = gzip
Headers Size = 10

Everything is Ok

Size:       104192000
Compressed: 24722348
C:\Users\xq114\AppData\Local\.xmake\cache\packages\2011\i\icu4c\68.1\source
{
  "C:\Users\xq114\AppData\Local\.xmake\cache\packages\2011\i\icu4c\68.1\source\icu4c-68.1.tar" 
}
 1
finding icu4c from xmake ..
checking for xmake::icu4c ... icu4c 68.1
{ 
  version = "68.1"
}

</details>

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.3.8
- xmake运行平台：Windows 10
- xmake目标平台：windows

### 其他信息

测试文件：

https://github.com/unicode-org/icu/releases/download/release-68-1/icu4c-68_1-src.tgz

**Comment by waruqi** [comment]
我dev改进过了，应该可以了
