### ISSUE TITLE
Visual Studio cannot open files from error output (vsxmake)

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#1049]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
I'm using the vsxmake project generator, which works great, however there's a little problem with errors.
When an error occurs, the output generated is:
```
1>------ Build started: Project: BurgWar, Configuration: debug x64 ------
1>$xmake config -P . -p windows -m debug -a x64 -o "build"
1>$xmake build -P . -w BurgWar
1>[ 86%]: compiling.debug src\Client\ClientApp.cpp
1>EXEC : error : ClientApp.cpp
1>src\Client\ClientApp.cpp(28): error C3861: 'FilStores': identifier not found
```

Which is fine, however the path is not the same as what Visual Studio excepts, when clicking on the error from VS error list it justs print "the system can not find the file specified", I have to find the file myself to check the error, which is kinda annoying.

![](https://user-images.githubusercontent.com/3002461/99284148-335cd900-2836-11eb-9ebc-4df98cfdfd9d.png)

Here's what happening with VS Project:
```
1>------ Build started: Project: BurgWar, Configuration: debug x64 ------
1>ClientApp.cpp
1>C:\Projets\Burgwar\BurgWar\src\Client\ClientApp.cpp(28,3): error C3861: 'FilStores': identifier not found
1>Done building project "BurgWar.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 4 up-to-date, 0 skipped ==========
```

Here it uses absolute path and thus is able to retrieve the file, an other solution would be to trigger xmake from VS folder and use relatives paths from this folder (../src/Client/ClientApp.cpp for example).

### Expected behavior
Being able to use a project generated by vsxmake more naturally, especially when handling errors.

### Related Environment

Please provide compiling and running environment information:

- xmake version: xmake v2.3.8+202010172345
- os: Windows 10 2004
- target platform: Windows

**Comment by waruqi** [comment]
Ok, I will look at it.

**Comment by waruqi** [comment]
You can add `/FC` flags to show full file path.

```lua
add_cxflags("/FC")
```

https://docs.microsoft.com/en-us/cpp/build/reference/fc-full-path-of-source-code-file-in-diagnostics?view=msvc-160

**Comment by SirLynix** [comment]
Thanks, that does the trick. Shouldn't vsxmake enable it by default then?

**Comment by waruqi** [comment]
> Thanks, that does the trick. Shouldn't vsxmake enable it by default then?

I have added it, please update to dev version and re-generate vsxmake project.

**Comment by SirLynix** [comment]
Thanks!
