### ISSUE TITLE
Use of /external:I in generated compile_commands.json breaks editor auto-complete

### ISSUE THREAD

**Issue by paul-reilly** [xmake-io/xmake#1050]
xmake v2.3.8+202011160626

When xmake generates a `compile_commands.json` file, the MSVC `/experimental:external` flag is used and package include directories are marked with `/external:I`.

Unfortunately it seems that Visual Studio Code and YouCompleteMe in neovim don't handle this flag properly.

### Repro
- In Windows, navigate to xmake project that includes a couple of packages
- `xmake project -k compile_commands`
- Open VS Code or neovim configured to use a compilation db file and see the error squiggles
- edit `compile_commands.json` to remove `external:` from the package include paths:
    - `-external:IC:/packageincludepath` -> `-IC:/packageincludepath`
- Open VS Code or neovim and see no squiggles

I have filed a [bug report](https://github.com/microsoft/vscode-cpptools/issues/6531) with VS Code C++ Tools.

A side issue is that the `/experimental:external` flags are not passed on to generated CMakeListst.txt files.

**Comment by waruqi** [comment]
ok, I will look at it.

**Comment by waruqi** [comment]
> A side issue is that the /experimental:external flags are not passed on to generated CMakeListst.txt files.

This seems to be a cmake issue. I have already added SYSTEM to target_include_directories. If cmake supports system header files, it should add /experimental:external by itself

```
target_include_directories(test7 SYSTEM PRIVATE
    sys
)
```

**Comment by paul-reilly** [comment]
I had to add it manually when I used it in the past. It was just `/experimental:external /external:anglebrackets` though.

**Comment by waruqi** [comment]
> I had to add it manually when I used it in the past. It was just `/experimental:external /external:anglebrackets` though.

I think this should be a cmake problem, it does not support system includedirs very well, I will consider temporarily disabling the external header file feature for cmakelists.

**Comment by waruqi** [comment]
> I had to add it manually when I used it in the past. It was just /experimental:external /external:anglebrackets though.

I have disabled external includes for cmake. you can try it.

> xmake project -k compile_commands

I have translated `/external:I` to `-I` for compile_commands.json on dev branch.

**Comment by paul-reilly** [comment]
That's much better, thanks!
