### ISSUE TITLE
Conflict between /Zi and /ZI

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#1051]
### Describe the bug
When enabling /ZI flag (for edit and continue) and enabling debug symbols, in such a way:
```lua
set_symbols("debug", "hidden")

if (is_plat("windows")) then
	add_cxxflags("/ZI")
end
```

both -Zi and /ZI options are passed to cl.exe, causing a D9025 warning (overriding '/Zi' with '/ZI'), this is a bit annoying.

### Expected behavior
That only /ZI is passed to cl.exe.

### Related Environment

- xmake version: xmake v2.3.8+202010172345
- os: Windows 10 2004
- target platform: Windows

**Comment by waruqi** [comment]
I will look at it.

**Comment by waruqi** [comment]
I have improve `set_symbols` to support `/Zi`, `/Zi` and `/Z7`. You do not need to specify additional `add_cxxflags("/ZI")`

```lua
set_symbols("debug") --> /Zi /Fdxxx.pdb
set_symbols("debug", "edit") --> /ZI /Fdxxx.pdb
set_symbols("debug", "embed") --> /Z7
```

`edit` and `embed` levels only for msvc, gcc/clang will ignore it and only use `debug` level.

So you only need set `set_symbols("debug", "edit", "hidden")`

**Comment by SirLynix** [comment]
Thank you!
