### ISSUE TITLE
安装了xmake不能使用xrepo

### ISSUE THREAD

**Issue by chena1982** [xmake-io/xmake#1052]
用xmake-v2.3.8.win64.exe 安装之后，xrepo使用不了。
我看xrepo的文档里说安装了xmake之后，xrepo就可以使用。
https://xrepo.xmake.io/#/zh-cn/getting_started

**Comment by waruqi** [comment]
xrepo需要2.3.9版本才有，还没发版呢，请请装dev/master版本

xmake update master

**Comment by chena1982** [comment]
哦，知道了，谢谢。
