### ISSUE TITLE
add_cxflags好像不起作用

### ISSUE THREAD

**Issue by chena1982** [xmake-io/xmake#1053]
用xmake project -k vsxmake2017 -m "debug;release"生成工程，然后打开vs工程编译，link报错
 error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in dllmain.cpp.obj

用下面这段代码设置flag

```
if is_plat("windows") then 
    if is_mode("release") then
        add_cxflags("-MT") 
    elseif is_mode("debug") then
        add_cxflags("-MTd") 
    end
end
```

不管设置什么flag，vs里面的flag都是默认的/MD，而且即使在vs里改了flag也不起作用。

xmake有没有什么调试的手段？有时候不知道自己搞错了，还是xmake有bug。

**Comment by waruqi** [comment]
看错误提示么，其实很明显了，dllmain.cpp.obj 你用了 MTd ，但是你程序依赖的链接库用了 MDd

至于你用了哪些库，你没贴出来 我也不可能知道，可以自己检查下，把所有依赖库切到MTd

另外，用了MT，需要禁用msvcrt.lib

```lua
    add_ldflags("-nodefaultlib:msvcrt.lib")
```


或者你全用MD，依赖库，main.cpp都切回MDd，默msvcrt也不用禁用

**Comment by chena1982** [comment]
昨天太晚了，晕了，输错了，我是用的
```
    if is_plat("windows") then 
        if is_mode("release") then
            add_cxflags("-MD") 
        elseif is_mode("debug") then
            add_cxflags("-MDd")
        end
    end
```
而且这里不管改成什么参数，vs工程里都是MD，但是dllmain.cpp.obj是MTd，而且我在vs工程里手动改成MDd，还是报这个错。

**Comment by waruqi** [comment]
打开cmd，直接执行 `xmake -rv` 给我看下完整输出

**Comment by chena1982** [comment]
[  5%]: compiling.debug Src\EFFBase\dllmain.cpp
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\cl.exe" -c -nologo -FS -Zi -FdBin\compile.EFFBase.pdb -Od -IInclude -IInclude\EFFBase -IThirdPartyLib -IThirdPartyLib\eastl_x64-windows\include -IThirdPartyLib\zeromq_x64-windows\include -IThirdPartyLib\jsoncpp_x64-windows\include -IThirdPartyLib\yaml-cpp_x64-windows\include -IThirdPartyLib\boost-type-traits_x64-windows\include -IThirdPartyLib\boost-config_x64-windows\include -IThirdPartyLib\boost-static-assert_x64-windows\include -IThirdPartyLib\boost-typeof_x64-windows\include -IThirdPartyLib\boost-function_x64-windows\include -IThirdPartyLib\boost-preprocessor_x64-windows\include -IThirdPartyLib\boost-throw-exception_x64-windows\include -IThirdPartyLib\boost-assert_x64-windows\include -IThirdPartyLib\boost-integer_x64-windows\include -IThirdPartyLib\boost-type-index_x64-windows\include -IThirdPartyLib\boost-container-hash_x64-windows\include -IThirdPartyLib\boost-core_x64-windows\include -IThirdPartyLib\boost-bind_x64-windows\include -DUNICODE -D_WINDOWS -DDEBUG -D_DEBUG -DEFFBASE_EXPORTS -DYAML_DECLARE_STATIC -YuEFFBasePCH.h -FIEFFBasePCH.h -FpTemp\Obj\EFFBase\windows\x64\debug\Src\EFFBase\EFFBasePCH.h.pch -MDd -FoTemp\Obj\EFFBase\windows\x64\debug\Src\EFFBase\dllmain.cpp.obj Src\EFFBase\dllmain.cpp

**Comment by chena1982** [comment]
这个好像是对的，但是在vs里直接编译不对。

**Comment by chena1982** [comment]
我又在vs里编译了一下，这个问题消失了。
这......

**Comment by waruqi** [comment]
> 我又在vs里编译了一下，这个问题消失了。
> 这......

vsxmake 工程，其实就是vs里面调用xmake命令去编译，跟你cmd执行xmake命令没什么区别。

**Comment by chena1982** [comment]
好吧，这个我也搞不明白了，谢谢了。
