### ISSUE TITLE
How do I pass configurations with character " to the compiler?

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1055]
### 描述讨论详情
如何给编译器（以及构建工具）传入带双引号的参数？

例如，需要传入`-DCMAKE_CXX_FLAGS="-IA -IB"`。

尝试：
```
import("package.tools.cmake").install(package, {"-DCMAKE_CXX_FLAGS=\"-IA -IB\""})
```
展开后变成了
```
-DCMAKE_CXX_FLAGS=\\"-IA -IB\\"
```

尝试
```
import("package.tools.cmake").install(package, {'-DCMAKE_CXX_FLAGS="-IA -IB"'})
```
展开后变成了
```
"-DCMAKE_CXX_FLAGS=\\"-IA -IB\\""
```

**Comment by waruqi** [comment]
只需要这样，不用加双引号，带空格也没关系，因为所有参数都是作为参数列表 argv 是透传给 `os.runv(program, argv)`的，xmake 会自动考虑每个 arg value 的空格问题，在不同平台上如何正确传入子进程。
```lua
import("package.tools.cmake").install(package, {"-DCMAKE_CXX_FLAGS=-IA -IB"})
```

**Comment by xq114** [comment]
> 只需要这样，不用加双引号，带空格也没关系，因为所有参数都是作为参数列表 argv 是透传给 `os.runv(program, argv)`的，xmake 会自动考虑每个 arg value 的空格问题，在不同平台上如何正确传入子进程。
> 
> 这里不涉及shell command的参数转义，所以用户不必加 "" 去额外wrap
> 
> ```lua
> import("package.tools.cmake").install(package, {"-DCMAKE_CXX_FLAGS=-IA -IB"})
> ```

这个对指定includepath确实是有用的，但处理linkpath的时候好像没用，Unix-style的“-Lxxx”和Windows-style的“/LIBPATH:xxx”没有正确处理。

这里能不能在xmake里面做一个处理？因为很多用cmake的库有一个陋习就是源码依赖，必须把依赖库的源码下载到`external/`下面才能编译。目前在xmake里面想添加这些库就要先把cmakelists里面的external去掉，然后手动添加includepath和libpath（作为CMAKE_CXX_FLAGS）。如果可以直接用
```lua
import("package.tools.cmake").install(package, configs, {pkgs = {package:dep("A"):fetch(), ...}})
```
或者
```lua
import("package.tools.cmake").install(package, configs, {deps = {"A", ...}})
```
就好了

**Comment by waruqi** [comment]
cmake.install原本就有自动处理add_deps中的所有依赖包，绑定到当前环境，让cmake自动检测到，至于为什么有些库还是没被检测到，那就要调下了

原本on_install里面就不用自己传递所有deps信息给cmake

你可以先调下这块

https://github.com/xmake-io/xmake/blob/b7aee98613d00f768010cdf95273a9bf129ad906/xmake/modules/package/tools/cmake.lua#L255-L275

**Comment by xq114** [comment]
fetchinfo的sysincludedirs漏了；另外为什么设置了isSys就不用设置LIBRARY和INCLUDE了呢？目标的CMakeLists不一定会用find_package()去CMAKE_PREFIX_PATH里面去找啊（可能源码依赖）

**Comment by waruqi** [comment]
> fetchinfo的sysincludedirs漏了

这个我回头补上

> 另外为什么设置了isSys就不用设置LIBRARY和INCLUDE了呢？

看下上面的代码，目前是isSys才设置了lib和inc

> 目标的CMakeLists不一定会用find_package()去CMAKE_PREFIX_PATH里面去找啊（可能源码依赖）

目前仅仅处理了find_package的情况，源码依赖不属于自动探测的范围，xmake没法通用处理，不同的包情况都不一样，只能在on_install做一些处理，可以在cmake.install的第三个参数中做点简化传递，比如用你刚说的传参方式

```lua
import("package.tools.cmake").install(package, configs, {deps = {"A", ...}})
```

**Comment by waruqi** [comment]
> 因为很多用cmake的库有一个陋习就是源码依赖，必须把依赖库的源码下载到external/下面才能编译。目前在xmake里面想添加这些库就要先把cmakelists里面的external去掉，然后手动添加includepath和libpath

哪些库，给几个case 我好做测试

**Comment by waruqi** [comment]
> fetchinfo的sysincludedirs漏了

这个我加上了

**Comment by xq114** [comment]
> > 因为很多用cmake的库有一个陋习就是源码依赖，必须把依赖库的源码下载到external/下面才能编译。目前在xmake里面想添加这些库就要先把cmakelists里面的external去掉，然后手动添加includepath和libpath
> 
> 哪些库，给几个case 我好做测试

effcee对re2的源码依赖，repo里面已经有了

**Comment by waruqi** [comment]
我dev加了个packagedeps参数来处理这个

```lua
import("package.tools.cmake").install(package, configs, {packagedeps = {"A", ...}})
```

不过我就在effcee上测试过，那个只有includes，没links，所以其他的暂时测试不了

或者可以在提供几个带有links的case，你这也可以帮忙测试下

**Comment by xq114** [comment]
> 我dev加了个packagedeps参数来处理这个
> 
> ```lua
> import("package.tools.cmake").install(package, configs, {packagedeps = {"A", ...}})
> ```
> 
> 不过我就在effcee上测试过，那个只有includes，没links，所以其他的暂时测试不了
> 
> 或者可以在提供几个带有links的case，你这也可以帮忙测试下

https://github.com/xq114/xmake-repo/tree/dev

glslang包依赖spirv-tools(同时有include和link)

**Comment by waruqi** [comment]
遇到个问题，现在通过 packagedeps 传进去，走 `cmake -DCMAKE_EXE_LINKER_FLAGS=xxx` 这种设置进去的，都会添加到 cmake编译链接命令行的开头，而不是最后面，导致依赖的 外部 links  还是会 找不到符号，cmake的链接顺序没法改。。

**Comment by waruqi** [comment]
```console
cd /home/ruki/.xmake/cache/packages/2011/g/glslang/1.2.154+1/source/glslang/build_2890FCD4/StandAlone && /usr/bin/cmake -E cmake_link_script CMakeFiles/glslangValidator.dir/link.txt --verbose=1
/usr/bin/c++   -I/home/ruki/.xmake/packages/s/spirv-tools/2020.5/531f88cff3a64da0aa3fb05ee281ab7d/include -O3 -DNDEBUG  -L/home/ruki/.xmake/packages/s/spirv-tools/2020.5/531f88cff3a64da0aa3fb05ee281ab7d/lib -lSPIRV-Tools -lSPIRV-Tools-link -lSPIRV-Tools-reduce -lSPIRV-Tools-opt CMakeFiles/glslangValidator.dir/StandAlone.cpp.o  -o glslangValidator -rdynamic ../glslang/libglslang.a ../SPIRV/libSPIRV.a libglslang-default-resource-limits.a ../SPIRV/libSPVRemapper.a -lpthread ../glslang/libMachineIndependent.a ../OGLCompilersDLL/libOGLCompiler.a ../glslang/OSDependent/Unix/libOSDependent.a -pthread ../glslang/libGenericCodeGen.a -lSPIRV-Tools-opt 
../SPIRV/libSPIRV.a(SpvTools.cpp.o): In function `glslang::SpirvToolsDisassemble(std::ostream&, std::vector<unsigned int, std::allocator<unsigned int> > const&)':
SpvTools.cpp:(.text+0x434): undefined reference to `spvContextCreate'
SpvTools.cpp:(.text+0x467): undefined reference to `spvBinaryToText'
SpvTools.cpp:(.text+0x476): undefined reference to `spvDiagnosticPrint'
```

`-lSPIRV-Tools-xxx` 在所有.a 的最开头，所以加进去也其实没效果，参数传递不行就只能patch cmakelist.txt 来控制顺序了，这就蛋疼了

**Comment by waruqi** [comment]
> > 我dev加了个packagedeps参数来处理这个
> > ```lua
> > import("package.tools.cmake").install(package, configs, {packagedeps = {"A", ...}})
> > ```
> > 
> > 
> > 不过我就在effcee上测试过，那个只有includes，没links，所以其他的暂时测试不了
> > 或者可以在提供几个带有links的case，你这也可以帮忙测试下
> 
> https://github.com/xq114/xmake-repo/tree/dev
> 
> glslang包依赖spirv-tools(同时有include和link)

这个包我也弄进去了，packagedeps 的方式勉强可用，不过对于传入的 links  顺序，还是受限于 cmake 的支持力度，目前没有更好的办法完美支持，所以 glslang 里面我还是加了点对 cmakelist.txt 的patch，修复了下 links 顺序，才能过掉。

先这么用着吧，如果有更好的版本，可以再改进。

**Comment by xq114** [comment]
好的，谢谢
