### ISSUE TITLE
How do I force package.tools.cmake to use ninja?

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1057]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
C和汇编混合的项目只用cmake+vs会有问题，需要使用ninja来构建，如何指定cmake使用ninja？

**Comment by waruqi** [comment]
add_deps("ninja")
install(package, configs, {cmake_generator = "Ninja"})

**Comment by xq114** [comment]
> add_deps("ninja")
> install(package, configs, {cmake_generator = "Ninja"})

同时装了VS和Mingw的时候用这种方法指定ninja，cmake探测不到VS的compiler了，只探测到mingw的gcc，这个怎么解决呢？

**Comment by waruqi** [comment]
那就不知道了，这个是cmake的探测问题，你得先研究下如何让cmake 在同时这两个环境都存在下，传递哪些参数给cmake，才能让它正常检测到vs

之后，我才能看看tools.cmake 是否能够支持或者改进这种参数的传递来让cmake选择vs环境。

**Comment by xq114** [comment]
> 那就不知道了，这个是cmake的探测问题，你得先研究下如何让cmake 在同时这两个环境都存在下，传递哪些参数给cmake，才能让它正常检测到vs
> 
> 之后，我才能看看tools.cmake 是否能够支持或者改进这种参数的传递来让cmake选择vs环境。

http://cmake.3232098.n2.nabble.com/How-to-use-Ninja-on-Windows-with-MSVC-td7599493.html

使用cmd的时候，先运行`vcvars64.bat`或者`vcvarsall.bat x64`就可以了（已测试可以）

powershell上要用Invoke-BatchFile（未测试）

只设置CMAKE_C_COMPILER或者只在环境变量里面加cl不行

**Comment by waruqi** [comment]
那感觉是cmake的问题吧，因为cmake通常都能自己检测到vs，不需要在 vc cmd环境下，也能自动加载进来，所以tools/cmake里面，我没去自动绑定 vsenv 给 cmake，而是让 cmake 自动探测选择的。。

**Comment by waruqi** [comment]
> 使用cmd的时候，先运行vcvars64.bat或者vcvarsall.bat x64就可以了（已测试可以）

要绑定vsenv，只需要传入msvc的 envs就可以了，参考下面的，关键是为啥cmake没去自动检测到？它的bug?

https://github.com/xmake-io/xmake-repo/blob/f8dc70f9cc741057f278e924f72117c03056eb9c/packages/m/make/xmake.lua#L13-L15

**Comment by waruqi** [comment]
我改了下，对 ninja/windows ，我绑定了msvc环境了，你再试试，dev的

不过我还没测试过，你先试试吧

**Comment by xq114** [comment]
可以了，谢谢
