### ISSUE TITLE
qt5的.qrc文件编译错误

### ISSUE THREAD

**Issue by nick908** [xmake-io/xmake#1058]
### 描述问题
无法编译识别.qrc

 **xmake.lua**

add_rules("mode.debug", "mode.release")

includes("qt_add_static_plugins.lua")

target("PythonScan")
    add_rules("qt.widgetapp_static")
    add_headerfiles("*.h")
    add_files("*.cpp")
    add_files("*.ui")
    add_files("*.rc")
    add_files("resource.qrc")
    add_deps("device", "imageprocess")

    add_packages("vcpkg::opencv3")

    -- add files with Q_OBJECT meta (only for qt.moc)
    add_files("mainwindow.h", "view.h", "assistant.h")
    add_links("Version", "Userenv","Netapi32", "Dwmapi", "wtsapi32")
    if is_plat("windows") then 
        if is_mode("debug") then
            add_cxflags("/MDd")
            add_links("Qt5WindowsUiAutomationSupportd", "Qt5FontDatabaseSupportd", "Qt5ThemeSupportd","Qt5EventDispatcherSupportd")
        else 
            add_cxflags("/MD")
            add_links("Qt5WindowsUiAutomationSupport", "Qt5FontDatabaseSupport", "Qt5ThemeSupport","Qt5EventDispatcherSupport")
        end
        add_defines("WIN32")
    end

    -- add plugin: QSvgPlugin (optional)
    add_frameworks("QtSvg")
    if is_mode("debug") then
        qt_add_static_plugins("QSvgPlugin", {linkdirs = "plugins/imageformats", links = {"qsvgd"}})
    else 
        qt_add_static_plugins("QSvgPlugin", {linkdirs = "plugins/imageformats", links = {"qsvg"}})
    end
### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 错误信息

PS D:\Holdtecs\PythonZ> xmake
checking for Microsoft Visual Studio (x64) version ... 2019
checking for Qt SDK directory ... C:/Qt/5.12.9/msvc2019_64
checking for Qt SDK version ... 5.12.9
error: unknown source file: PythonScan\resource.qrc
PS D:\Holdtecs\PythonZ> xmake -vD
error: @programdir\core\main.lua:284: @programdir\actions\build\main.lua:124: @programdir\core\project\target.lua:1496: unknown source file: PythonScan\resource.qrc
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:789]: in function 'raise'
    [@programdir\core\project\target.lua:1496]: in function 'sourcebatches'
    [@programdir\actions\build\kinds\object.lua:121]: in function 'add_batchjobs_for_object'
    [@programdir\actions\build\kinds\binary.lua:145]:
    [@programdir\actions\build\build.lua:57]: in function '_add_batchjobs_builtin'
    [@programdir\actions\build\build.lua:70]: in function '_add_batchjobs'
    [@programdir\actions\build\build.lua:130]: in function '_add_batchjobs_for_target'
    [@programdir\actions\build\build.lua:170]: in function '_add_batchjobs_for_target_and_deps'
    [@programdir\actions\build\build.lua:210]: in function 'get_batchjobs'
    [@programdir\actions\build\build.lua:219]: in function 'build'
    [@programdir\actions\build\main.lua:116]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\actions\build\main.lua:110]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:520]: in function 'run'
    [@programdir\core\main.lua:282]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:789: in function 'raise'
        @programdir\core\main.lua:284: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>
PS D:\Holdtecs\PythonZ> 
### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：xmake v2.3.8+202011151135, A cross-platform build utility based on Lua
- xmake运行平台：windows 10 , vs 2019
- xmake目标平台：windows 10

### 其他信息

请提供其他附加信息帮助我们诊断问题(比如截图，xmake.lua或者可复现的demo)，以及你遇到的问题的一些背景信息。

**Comment by waruqi** [comment]
你追加下 qt.qrc的规则，目前默认只有qt.quickapp规则，才启用了qt.qrc，widgetapp目前默认没启用

你先自己追加下，回头我内置进去

add_rules("qt.widgetapp_static", "qt.qrc")

**Comment by waruqi** [comment]
我刚dev分支 widgetapp 也加上 qt.qrc 规则了。你可以再试试

**Comment by nick908** [comment]
已经没有问题了
