### ISSUE TITLE
xmake + as + clang set_warnings("all") 有些警告还是导致编译通不过

### ISSUE THREAD

**Issue by dsp2000** [xmake-io/xmake#1059]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
请在这描述你需要讨论的话题详情。

set_languages("c99", "cxx11")
set_warnings("all")
add_includedirs("include")
add_linkdirs("libs/$(arch)")
add_files("native-lib.cpp", "ffmpeg.c", "cmdutils.c", "ffmpeg_opt.c", "ffmpeg_filter.c", "ffmpeg_hw.c")

提示
cmdutils.c:211:18: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]

下面是完整的

Executing tasks: [:app:assembleDebug] in project D:\ktv\TestXmake

> Configure project :
Repository https://jcenter.bintray.com/ replaced by http://maven.aliyun.com/nexus/content/groups/public.
Repository https://jcenter.bintray.com/ replaced by http://maven.aliyun.com/nexus/content/groups/public.

> Configure project :app
[xmake/plugin]: activated for project: app

> Task :app:xmakeConfigureForX86
>> xmake f -y -v -p android -a x86 --ndk=E:\Android\sdk\ndk\21.0.6113669 --buildir=D:\ktv\TestXmake\app\build\xmake 
checking for the shared library linker (sh) ... clang++
checking for the linker (ld) ... clang++
configure
{
    ccache = true
    plat = android
    ndk = E:\Android\sdk\ndk\21.0.6113669
    sh = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    ndk_stdcxx = true
    host = windows
    sdk = E:\Android\sdk
    buildir = ..\..\..\build\xmake
    ndk_toolchains_ver = 4.9
    cxx = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    ndk_sdkver = 21
    arch = x86
    bin = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin
    gcc_toolchain = E:\Android\sdk\ndk\21.0.6113669\toolchains\x86-4.9\prebuilt\windows-x86_64
    mode = release
    cc = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang
    cross = i686-linux-android-
    build_toolver = 28.0.3
    kind = static
    ld = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
    android_sdk = E:\Android\sdk
    ndkver = 21
}

> Task :app:xmakeBuildForX86
>> xmake build -v 
[ 33%]: compiling.release ffmpeg.c
E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang -c -Wall -Oz -std=c99 -Iinclude --sysroot=E:\Android\sdk\ndk\21.0.6113669\sysroot -isystem E:\Android\sdk\ndk\21.0.6113669\sysroot\usr\include\i686-linux-android -Qunused-arguments -target i686-none-linux-android -gcc-toolchain E:\Android\sdk\ndk\21.0.6113669\toolchains\x86-4.9\prebuilt\windows-x86_64 -D__ANDROID_API__=21 -fPIC -o ..\..\..\build\xmake\.objs\native-lib\android\x86\release\ffmpeg.c.o ffmpeg.c
[ 44%]: compiling.release cmdutils.c
E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang -c -Wall -Oz -std=c99 -Iinclude --sysroot=E:\Android\sdk\ndk\21.0.6113669\sysroot -isystem E:\Android\sdk\ndk\21.0.6113669\sysroot\usr\include\i686-linux-android -Qunused-arguments -target i686-none-linux-android -gcc-toolchain E:\Android\sdk\ndk\21.0.6113669\toolchains\x86-4.9\prebuilt\windows-x86_64 -D__ANDROID_API__=21 -fPIC -o ..\..\..\build\xmake\.objs\native-lib\android\x86\release\cmdutils.c.o cmdutils.c
[ 55%]: compiling.release ffmpeg_opt.c
E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang -c -Wall -Oz -std=c99 -Iinclude --sysroot=E:\Android\sdk\ndk\21.0.6113669\sysroot -isystem E:\Android\sdk\ndk\21.0.6113669\sysroot\usr\include\i686-linux-android -Qunused-arguments -target i686-none-linux-android -gcc-toolchain E:\Android\sdk\ndk\21.0.6113669\toolchains\x86-4.9\prebuilt\windows-x86_64 -D__ANDROID_API__=21 -fPIC -o ..\..\..\build\xmake\.objs\native-lib\android\x86\release\ffmpeg_opt.c.o ffmpeg_opt.c
[ 66%]: compiling.release ffmpeg_filter.c
E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang -c -Wall -Oz -std=c99 -Iinclude --sysroot=E:\Android\sdk\ndk\21.0.6113669\sysroot -isystem E:\Android\sdk\ndk\21.0.6113669\sysroot\usr\include\i686-linux-android -Qunused-arguments -target i686-none-linux-android -gcc-toolchain E:\Android\sdk\ndk\21.0.6113669\toolchains\x86-4.9\prebuilt\windows-x86_64 -D__ANDROID_API__=21 -fPIC -o ..\..\..\build\xmake\.objs\native-lib\android\x86\release\ffmpeg_filter.c.o ffmpeg_filter.c
[ 77%]: compiling.release ffmpeg_hw.c
E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang -c -Wall -Oz -std=c99 -Iinclude --sysroot=E:\Android\sdk\ndk\21.0.6113669\sysroot -isystem E:\Android\sdk\ndk\21.0.6113669\sysroot\usr\include\i686-linux-android -Qunused-arguments -target i686-none-linux-android -gcc-toolchain E:\Android\sdk\ndk\21.0.6113669\toolchains\x86-4.9\prebuilt\windows-x86_64 -D__ANDROID_API__=21 -fPIC -o ..\..\..\build\xmake\.objs\native-lib\android\x86\release\ffmpeg_hw.c.o ffmpeg_hw.c
error: cmdutils.c:211:18: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
    while (child = av_opt_child_class_next(class, child))
           ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cmdutils.c:211:18: note: place parentheses around the assignment to silence this warning
    while (child = av_opt_child_class_next(class, child))
                 ^
           (                                            )
cmdutils.c:211:18: note: use '==' to turn this assignment into an equality comparison
    while (child = av_opt_child_class_next(class, child))
                 ^
                 ==
cmdutils.c:475:12: warning: assigning to 'const unsigned char *' from 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
    for (p = a; *p; p++)
           ^ ~
cmdutils.c:484:12: warning: assigning to 'const unsigned char *' from 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
    for (p = a; *p; p++) {
           ^ ~
cmdutils.c:1139:5: warning: implicit declaration of function 'avresample_version' is invalid in C99 [-Wimplicit-function-declaration]
    PRINT_LIB_INFO(avresample, AVRESAMPLE, flags, level);
    ^
cmdutils.c:1107:36: note: expanded from macro 'PRINT_LIB_INFO'
            unsigned int version = libname##_version();                 \
                                   ^
<scratch space>:267:1: note: expanded from here
avresample_version
^
cmdutils.c:1139:5: error: use of undeclared identifier 'LIBAVRESAMPLE_VERSION_MAJOR'
cmdutils.c:1111:20: note: expanded from macro 'PRINT_LIB_INFO'
                   LIB##LIBNAME##_VERSION_MAJOR,                        \
                   ^
<scratch space>:269:1: note: expanded from here
LIBAVRESAMPLE_VERSION_MAJOR
^
cmdutils.c:1139:5: error: use of undeclared identifier 'LIBAVRESAMPLE_VERSION_MINOR'
cmdutils.c:1112:20: note: expanded from macro 'PRINT_LIB_INFO'
                   LIB##LIBNAME##_VERSION_MINOR,                        \
                   ^
<scratch space>:271:1: note: expanded from here
LIBAVRESAMPLE_VERSION_MINOR
^
cmdutils.c:1139:5: error: use of undeclared identifier 'LIBAVRESAMPLE_VERSION_MICRO'
cmdutils.c:1113:20: note: expanded from macro 'PRINT_LIB_INFO'
                   LIB##LIBNAME##_VERSION_MICRO,                        \
                   ^
<scratch space>:273:1: note: expanded from here
LIBAVRESAMPLE_VERSION_MICRO
^
cmdutils.c:1139:5: warning: implicit declaration of function 'avresample_configuration' is invalid in C99 [-Wimplicit-function-declaration]
cmdutils.c:1118:31: note: expanded from macro 'PRINT_LIB_INFO'
            const char *cfg = libname##_configuration();                \
                              ^
<scratch space>:274:1: note: expanded from here
avresample_configuration
^
cmdutils.c:1139:5: warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
    PRINT_LIB_INFO(avresample, AVRESAMPLE, flags, level);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cmdutils.c:1118:25: note: expanded from macro 'PRINT_LIB_INFO'
            const char *cfg = libname##_configuration();                \
                        ^     ~~~~~~~~~~~~~~~~~~~~~~~~~
cmdutils.c:1142:5: warning: implicit declaration of function 'postproc_version' is invalid in C99 [-Wimplicit-function-declaration]
    PRINT_LIB_INFO(postproc,   POSTPROC,   flags, level);
    ^
cmdutils.c:1107:36: note: expanded from macro 'PRINT_LIB_INFO'
            unsigned int version = libname##_version();                 \
                                   ^
<scratch space>:297:1: note: expanded from here
postproc_version
^
cmdutils.c:1142:5: error: use of undeclared identifier 'LIBPOSTPROC_VERSION_MAJOR'
cmdutils.c:1111:20: note: expanded from macro 'PRINT_LIB_INFO'
                   LIB##LIBNAME##_VERSION_MAJOR,                        \
                   ^
<scratch space>:299:1: note: expanded from here
LIBPOSTPROC_VERSION_MAJOR
^
cmdutils.c:1142:5: error: use of undeclared identifier 'LIBPOSTPROC_VERSION_MINOR'
cmdutils.c:1112:20: note: expanded from macro 'PRINT_LIB_INFO'
                   LIB##LIBNAME##_VERSION_MINOR,                        \
                   ^
<scratch space>:301:1: note: expanded from here
LIBPOSTPROC_VERSION_MINOR
^
cmdutils.c:1142:5: error: use of undeclared identifier 'LIBPOSTPROC_VERSION_MICRO'
cmdutils.c:1113:20: note: expanded from macro 'PRINT_LIB_INFO'
                   LIB##LIBNAME##_VERSION_MICRO,                        \
                   ^
<scratch space>:303:1: note: expanded from here
LIBPOSTPROC_VERSION_MICRO
^
cmdutils.c:1142:5: warning: implicit declaration of function 'postproc_configuration' is invalid in C99 [-Wimplicit-function-declaration]
cmdutils.c:1118:31: note: expanded from macro 'PRINT_LIB_INFO'
            const char *cfg = libname##_configuration();                \
                              ^
<scratch space>:304:1: note: expanded from here
postproc_configuration
^
cmdutils.c:1142:5: warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
    PRINT_LIB_INFO(postproc,   POSTPROC,   flags, level);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cmdutils.c:1118:25: note: expanded from macro 'PRINT_LIB_INFO'
            const char *cfg = libname##_configuration();                \
                        ^     ~~~~~~~~~~~~~~~~~~~~~~~~~
cmdutils.c:1741:22: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
    for (i = 0; name = av_get_known_color_name(i, &rgb); i++)
                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cmdutils.c:1741:22: note: place parentheses around the assignment to silence this warning
    for (i = 0; name = av_get_known_color_name(i, &rgb); i++)
                     ^
                (                                      )
cmdutils.c:1741:22: note: use '==' to turn this assignment into an equality comparison
    for (i = 0; name = av_get_known_color_name(i, &rgb); i++)
                     ^
                     ==
cmdutils.c:2119:13: warning: 4 enumeration values not handled in switch: 'AVMEDIA_TYPE_UNKNOWN', 'AVMEDIA_TYPE_DATA', 'AVMEDIA_TYPE_ATTACHMENT'... [-Wswitch]
    switch (st->codecpar->codec_type) {
            ^
cmdutils.c:2134:14: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
    while (t = av_dict_get(opts, "", t, AV_DICT_IGNORE_SUFFIX)) {
           ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cmdutils.c:2134:14: note: place parentheses around the assignment to silence this warning
    while (t = av_dict_get(opts, "", t, AV_DICT_IGNORE_SUFFIX)) {
             ^
           (                                                  )
cmdutils.c:2134:14: note: use '==' to turn this assignment into an equality comparison
    while (t = av_dict_get(opts, "", t, AV_DICT_IGNORE_SUFFIX)) {
             ^
             ==
12 warnings and 6 errors generated.

> Task :app:xmakeBuildForX86 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:xmakeBuildForX86'.
> exec failed( -1)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
2 actionable tasks: 2 executed

**Comment by waruqi** [comment]
> cmdutils.c:1139:5: error: use of undeclared identifier 'LIBAVRESAMPLE_VERSION_MAJOR'
> cmdutils.c:1139:5: error: use of undeclared identifier 'LIBAVRESAMPLE_VERSION_MINOR'

看你贴的错误么，很明显，很多宏定义找不到，跟warning没啥关系，你 gradle 里面 配置了  verbose 显示，会在编译错误的时候，会输出所有 编译器 提供的错误信息，里面也有很多警告，但这不是问题点，要看里面的 error 部分，才是引起编译错误的地方。。

这跟xmake也没啥关系，自己分析下相关错误，自己处理下就好了，如果只想显示error不显示警告信息，那就在 build.gradle 里面 buildLevel 去掉 verbose 设置。
