### ISSUE TITLE
xmake + as + clang +ffmpeg 编译通过 加载so时出错, java完全还没有调用c的函数

### ISSUE THREAD

**Issue by dsp2000** [xmake-io/xmake#1060]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
请在这描述你需要讨论的话题详情。

xmake + as + clang +ffmpeg 编译通过 加载so时出错, java完全还没有调用c的函数

add_rules("mode.debug", "mode.release")
target("native-lib")
set_kind("shared")
set_languages("c99", "cxx11")
set_warnings("all")
add_includedirs("include")
add_linkdirs("libs/$(arch)")
add_files("native-lib.cpp", "ffmpeg.c", "cmdutils.c", "ffmpeg_opt.c", "ffmpeg_filter.c", "ffmpeg_hw.c")

add_links("avcodec");
add_links("avformat");
add_links("swscale");
add_links("swresample");
add_links("avfilter");
add_links("avutil");
add_links("avdevice");
add_syslinks("log", "z")

原则上，编译通过就应该包括所有需要的库了。而且未调用任何函数出错，应该是有些库未加入所致？

java.lang.ExceptionInInitializerError
        at java.lang.Class.newInstanceImpl(Native Method)
        at java.lang.Class.newInstance(Class.java:1319)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2025)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
        at android.app.ActivityThread.access$700(ActivityThread.java:140)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4921)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1307]:  1935 cannot locate 'tcsetattr'...
    
        at java.lang.Runtime.loadLibrary(Runtime.java:370)
        at java.lang.System.loadLibrary(System.java:535)
        at com.example.testxmake.MainActivity.<clinit>(MainActivity.java:12)

**Comment by dsp2000** [comment]
在网上找了一通，怀疑可能需要设置与ffmpeg编译的*.a 相同的平台版本， 编译时 arm64-v8a使用 21 其余使用16，如何在xmake.lua 里面分别指定对应的平台呢？

**Comment by waruqi** [comment]
build.gradle里可以改

```lua
    externalNativeBuild {
        xmake {
            path "jni/xmake.lua"
            sdkver 21
        }
    }
```

> Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1307]: 1935 cannot locate 'tcsetattr'...

看错误不是很明显么，你的库里面用了 termios 里面终端接口，而android上没有提供，load so的时候当然报错了。。

android上肯定不会有这些接口，编译ffmpeg 或者 其他哪里用到，直接去掉这些接口调用就行了，反正android上也不会用。。

这跟xmake也没啥关系，这种问题 自己排查解决吧。。

**Comment by dsp2000** [comment]
我刚才排除掉这些没有用到的函数之后，发现在可能没有包含*.a文件进行编译。
运行时：
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_fft_permute" referenced by "/data/app/com.example.testxmake-9LrKfNcgdaUfzi0jc9E1rA==/lib/arm64/libnative-lib.so"...

提示的函数av_fft_permute在libavcodec.a里面的，用360打开libavcodec.a里面的1.txt显示有
...
avfft.o    av_fft_permute
...

而在xmake.lua里面包含
add_links("avcodec");

现在的问题好像是因为没有加入*.a引起的。

Executing tasks: [clean, :app:assembleDebug] in project D:\ktv\TestXmake


> Configure project :
Repository https://jcenter.bintray.com/ replaced by http://maven.aliyun.com/nexus/content/groups/public.
Repository https://jcenter.bintray.com/ replaced by http://maven.aliyun.com/nexus/content/groups/public.

> Configure project :app
[xmake/plugin]: activated for project: app

> Task :clean UP-TO-DATE

> Task :app:xmakeConfigureForArm64
>> xmake f -y -v -p android -a arm64-v8a --ndk=E:\Android\sdk\ndk\21.0.6113669 --ndk_sdkver=21 --buildir=D:\ktv\TestXmake\app\build\xmake 
checking for the shared library linker (sh) ... clang++
checking for the linker (ld) ... clang++
configure
{
    ccache = true
    ndk = E:\Android\sdk\ndk\21.0.6113669
    plat = android
    sdk = E:\Android\sdk
    ndk_stdcxx = true
    buildir = ..\..\..\build\xmake
    ndk_toolchains_ver = 4.9
    ndk_sdkver = 21
    kind = static
    gcc_toolchain = E:\Android\sdk\ndk\21.0.6113669\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64
    mode = release
    bin = E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin
    build_toolver = 29.0.3
    cross = aarch64-linux-android-
    arch = arm64-v8a
    android_sdk = E:\Android\sdk
    host = windows
    ndkver = 21
}

> Task :app:xmakeCleanForArm64
>> xmake clean -v 

> Task :app:xmakeClean
> Task :app:clean

> Task :app:xmakeBuildForArm64
>> xmake build -v 
[ 22%]: compiling.release native-lib.cpp
E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ -c -Wall -Oz -std=c++11 -Iinclude -Iffmpeg --sysroot=E:\Android\sdk\ndk\21.0.6113669\sysroot -isystem E:\Android\sdk\ndk\21.0.6113669\sysroot\usr\include\aarch64-linux-android -IE:\Android\sdk\ndk\21.0.6113669\sources\cxx-stl\llvm-libc++/include -IE:\Android\sdk\ndk\21.0.6113669\sources\cxx-stl\llvm-libc++/libs/arm64-v8a/include -IE:\Android\sdk\ndk\21.0.6113669\sources\cxx-stl\llvm-libc++abi\include -Qunused-arguments -target aarch64-none-linux-android -gcc-toolchain E:\Android\sdk\ndk\21.0.6113669\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64 -D__ANDROID_API__=21 -fPIC -o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\native-lib.cpp.o native-lib.cpp
[ 33%]: compiling.release ffmpeg.c
E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang -c -Wall -Oz -std=c99 -Iinclude -Iffmpeg --sysroot=E:\Android\sdk\ndk\21.0.6113669\sysroot -isystem E:\Android\sdk\ndk\21.0.6113669\sysroot\usr\include\aarch64-linux-android -Qunused-arguments -target aarch64-none-linux-android -gcc-toolchain E:\Android\sdk\ndk\21.0.6113669\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64 -D__ANDROID_API__=21 -fPIC -o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg.c.o ffmpeg.c
[ 44%]: compiling.release cmdutils.c
E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang -c -Wall -Oz -std=c99 -Iinclude -Iffmpeg --sysroot=E:\Android\sdk\ndk\21.0.6113669\sysroot -isystem E:\Android\sdk\ndk\21.0.6113669\sysroot\usr\include\aarch64-linux-android -Qunused-arguments -target aarch64-none-linux-android -gcc-toolchain E:\Android\sdk\ndk\21.0.6113669\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64 -D__ANDROID_API__=21 -fPIC -o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\cmdutils.c.o cmdutils.c
[ 55%]: compiling.release ffmpeg_opt.c
E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang -c -Wall -Oz -std=c99 -Iinclude -Iffmpeg --sysroot=E:\Android\sdk\ndk\21.0.6113669\sysroot -isystem E:\Android\sdk\ndk\21.0.6113669\sysroot\usr\include\aarch64-linux-android -Qunused-arguments -target aarch64-none-linux-android -gcc-toolchain E:\Android\sdk\ndk\21.0.6113669\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64 -D__ANDROID_API__=21 -fPIC -o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_opt.c.o ffmpeg_opt.c
[ 66%]: compiling.release ffmpeg_filter.c
E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang -c -Wall -Oz -std=c99 -Iinclude -Iffmpeg --sysroot=E:\Android\sdk\ndk\21.0.6113669\sysroot -isystem E:\Android\sdk\ndk\21.0.6113669\sysroot\usr\include\aarch64-linux-android -Qunused-arguments -target aarch64-none-linux-android -gcc-toolchain E:\Android\sdk\ndk\21.0.6113669\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64 -D__ANDROID_API__=21 -fPIC -o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_filter.c.o ffmpeg_filter.c
[ 77%]: compiling.release ffmpeg_hw.c
E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang -c -Wall -Oz -std=c99 -Iinclude -Iffmpeg --sysroot=E:\Android\sdk\ndk\21.0.6113669\sysroot -isystem E:\Android\sdk\ndk\21.0.6113669\sysroot\usr\include\aarch64-linux-android -Qunused-arguments -target aarch64-none-linux-android -gcc-toolchain E:\Android\sdk\ndk\21.0.6113669\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64 -D__ANDROID_API__=21 -fPIC -o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_hw.c.o ffmpeg_hw.c
[ 88%]: linking.release libnative-lib.so
E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ -o ..\..\..\build\xmake\android\arm64-v8a\release\libnative-lib.so ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\native-lib.cpp.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\cmdutils.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_opt.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_filter.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_hw.c.o -Llibs\arm64-v8a -s -lavcodec -lavformat -lswscale -lswresample -lavfilter -lavutil -lavdevice -llog -lz -shared -fPIC -target aarch64-none-linux-android -gcc-toolchain E:\Android\sdk\ndk\21.0.6113669\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64 --sysroot=E:\Android\sdk\ndk\21.0.6113669\platforms\android-21/arch-arm64 -LE:\Android\sdk\ndk\21.0.6113669\sources\cxx-stl\llvm-libc++/libs/arm64-v8a -lc++_static -lc++abi -nostdlib++
[100%]: build ok!
installing native-lib ..
installing to D:\ktv\TestXmake\app\build\xmake\libs\arm64-v8a ..
> copy ..\..\..\build\xmake\android\arm64-v8a\release\libnative-lib.so to D:\ktv\TestXmake\app\build\xmake\libs\arm64-v8a\lib
install ok!

> Task :app:xmakeBuild

> Task :app:xmakeInstall
>> install artifacts to D:\ktv\TestXmake\app\libs
running given lua script file ..\..\..\build\xmake\install_artifacts.lua with args:
  - "D:\ktv\TestXmake\app\build\xmake\libs"
  - "D:\ktv\TestXmake\app\libs"
  - "arm64-v8a"
checking for the shared library linker (sh) ... clang++
checking for the linker (ld) ... clang++
> copy D:\ktv\TestXmake\app\build\xmake\libs\arm64-v8a\lib\libnative-lib.so to D:\ktv\TestXmake\app\libs\arm64-v8a

> Task :app:preBuild
> Task :app:preDebugBuild
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig
> Task :app:mainApkListPersistenceDebug
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:createDebugCompatibleScreenManifests
> Task :app:extractDeepLinksDebug
> Task :app:processDebugManifest
> Task :app:mergeDebugShaders
> Task :app:compileDebugShaders
> Task :app:generateDebugAssets
> Task :app:mergeDebugAssets
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:mergeDebugJavaResource
> Task :app:checkDebugDuplicateClasses
> Task :app:javaPreCompileDebug
> Task :app:mergeDebugJniLibFolders
> Task :app:mergeDebugResources
> Task :app:processDebugResources
> Task :app:compileDebugJavaWithJavac
> Task :app:compileDebugSources
> Task :app:dexBuilderDebug
> Task :app:validateSigningDebug
> Task :app:mergeDebugNativeLibs
> Task :app:stripDebugDebugSymbols
> Task :app:mergeExtDexDebug
> Task :app:mergeDexDebug
> Task :app:packageDebug
> Task :app:assembleDebug

BUILD SUCCESSFUL in 11s
31 actionable tasks: 30 executed, 1 up-to-date

**Comment by dsp2000** [comment]
[Uploading libavcodec.zip…]()

**Comment by dsp2000** [comment]
[Uploading 1.zip…]()

**Comment by dsp2000** [comment]
刚才我试了下，把所有的*.a文件移走，编译也是通过的，说明没有链接*.a

add_rules("mode.debug", "mode.release")
target("native-lib")
set_kind("shared")
set_languages("c99", "cxx11")
set_warnings("all")
add_includedirs("include", "ffmpeg")
add_linkdirs("libs/$(arch)")
add_files("native-lib.cpp", "ffmpeg.c", "cmdutils.c", "ffmpeg_opt.c", "ffmpeg_filter.c", "ffmpeg_hw.c")
add_links("avcodec");
add_links("avformat");
add_links("swscale");
add_links("swresample");
add_links("avfilter");
add_links("avutil");
add_links("avdevice");
add_syslinks("log", "z")



这些应该没有起作用：
 -s -lavcodec -lavformat -lswscale -lswresample -lavfilter -lavutil -lavdevice -llog



[ 88%]: linking.release libnative-lib.so
E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ -o ..\..\..\build\xmake\android\arm64-v8a\release\libnative-lib.so ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\native-lib.cpp.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\cmdutils.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_opt.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_filter.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_hw.c.o -Llibs\arm64-v8a -s -lavcodec -lavformat -lswscale -lswresample -lavfilter -lavutil -lavdevice -llog -lz -shared -fPIC -target aarch64-none-linux-android -gcc-toolchain E:\Android\sdk\ndk\21.0.6113669\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64 --sysroot=E:\Android\sdk\ndk\21.0.6113669\platforms\android-21/arch-arm64 -LE:\Android\sdk\ndk\21.0.6113669\sources\cxx-stl\llvm-libc++/libs/arm64-v8a -lc++_static -lc++abi -nostdlib++
[100%]: build ok!

**Comment by waruqi** [comment]
> 这些应该没有起作用：
> -s -lavcodec -lavformat -lswscale -lswresample -lavfilter -lavutil -lavdevice -llog

如果没起作用，那也跟xmake没啥关系，xmake只保证，用户配置了 links/linkdirs，最终确实传递给了 linker ，那任务就算完成了。。

目前看命令行一切ok，剩下的就是 linker ，还有用户自己配置的 linkdirs 是否ok 这些事情了，只能你自己排查解决，比如 多个目录下存在库，导致 links错了，又或者 代码里面压根没用到 ffmpeg 的接口，又或者确实是 g++/linker 的bug，这些都是用户日常开发中，自己要去解决的。不是所有问题，都需要xmake这边帮忙给你看的。。


如果是 xmake.lua 里面你配置 ffmpeg 的links，但是 实际编译链接，这些links 丢失了，或者某些linkdirs没设置上导致链接不过，我这边才会帮你看下，因为这些属于xmake自身的问题。

**Comment by dsp2000** [comment]
像下面这条链接的命令，我如何确定他一定已经将对应的库链接进去了？clang++应该不会没有找到对应的文件而不提示出错吧？



E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ -o ..\..\..\build\xmake\android\arm64-v8a\release\libnative-lib.so ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\native-lib.cpp.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\cmdutils.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_opt.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_filter.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_hw.c.o -Llibs\arm64-v8a -s -lavcodec -lavformat -lswscale -lswresample -lavfilter -lavutil -lavdevice -llog -lz -shared -fPIC -target aarch64-none-linux-android -gcc-toolchain E:\Android\sdk\ndk\21.0.6113669\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64 --sysroot=E:\Android\sdk\ndk\21.0.6113669\platforms\android-21/arch-arm64 -LE:\Android\sdk\ndk\21.0.6113669\sources\cxx-stl\llvm-libc++/libs/arm64-v8a -lc++_static -lc++abi -nostdlib++

我刚才直接在cmd运行clang++

![Z4G((Y63T~PW3~4 X4WC%N7](https://user-images.githubusercontent.com/54521555/99925214-2ed57a80-2d78-11eb-8648-15051e8552f2.png)

**Comment by waruqi** [comment]
> 像下面这条链接的命令，我如何确定他一定已经将对应的库链接进去了？clang++应该不会没有找到对应的文件而不提示出错吧？

命令里面追加了 links ，代码里面确实用到了 这些符号，只要clang 不报错，那就是link上了，如果还是没有，那你需要到 llvm issues去提了。

> 我刚才直接在cmd运行clang++

看错误么，不是很明显么，没找到.o文件，一看就是 执行clang的当前工作目录不对，.o都是相对路径的，你复制命令，怎么可能随便到一个 temp目录下执行就能通过呢，c:\temp 下  ..\..\..\build 你觉得会存在这个目录么？ = =

**Comment by dsp2000** [comment]
是的，我进入正确的路径编译可以了。
但是，我找不到编译的中间文件，类似 *.lst文件  *.map文件这些

例如我平时编译单片机的程序经常在打开*.map找函数或变量的位置这些，

我希望可以保留这些中间文件用于调试。

编译平台这些不太明白，所以需要多多支持

**Comment by waruqi** [comment]
> 但是，我找不到编译的中间文件，类似 *.lst文件 *.map文件这些

这种是自己根据需要xmake.lua 里面通过  add_cxflags/add_shflags/add_ldflags自己配置的，具体怎么配置，需要自己查看 clang 等相关的编译链接选项

**Comment by dsp2000** [comment]
add_files("native-lib.cpp", "ffmpeg.c", "cmdutils.c", "ffmpeg_opt.c", "ffmpeg_filter.c", "ffmpeg_hw.c")
发现一个问题，调用任何函数只要是接受宣布，就能编译及链接通过的。不管这个函数是不是存在的。
所以链接使用下面的是不是有错误了？链接的方式是xmake指定的吧？

E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ -o ..\..\..\build\xmake\android\arm64-v8a\release\libnative-lib.so ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\native-lib.cpp.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\cmdutils.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_opt.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_filter.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_hw.c.o -Llibs\arm64-v8a -s -lavcodec -lavformat -lswscale -lswresample -lavfilter -lavutil -lavdevice -llog -lz -shared -fPIC -target aarch64-none-linux-android -gcc-toolchain E:\Android\sdk\ndk\21.0.6113669\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64 --sysroot=E:\Android\sdk\ndk\21.0.6113669\platforms\android-21/arch-arm64 -LE:\Android\sdk\ndk\21.0.6113669\sources\cxx-stl\llvm-libc++/libs/arm64-v8a -lc++_static -lc++abi -nostdlib++

**Comment by waruqi** [comment]
> add_files("native-lib.cpp", "ffmpeg.c", "cmdutils.c", "ffmpeg_opt.c", "ffmpeg_filter.c", "ffmpeg_hw.c")
> 发现一个问题，调用任何函数只要是接受宣布，就能编译及链接通过的。不管这个函数是不是存在的。
所以链接使用下面的是不是有错误了？链接的方式是xmake指定的吧？

不是，xmake默认不会去管这些，只保证基础的so生成 ，xmake 默认不会去额外设置链接方式，并且会尽可能少的添加内置ldflags，所以链接flags 都由用户自己通过 add_shflags()/add_ldflags 来控制

func声明了链接不报错，那是linker的行为，linker可以强制指定全部报出来，也可以指定默认不报出来，如何控制这个行为，都是用户来决定的，不是xmake。

默认xmake没有设置额外的ldflags，linker不报这些错误，也是正常行为，说明用户假定这些func在android设备的系统so中已经加载存在，这会导致动态lookup加载设备so上的func，也就是 weak symbols 模式。

你想强制全部报出来，那么自己翻下 clang /lld 等linker的编译选项，通过 add_shflags/add_ldflags 添加对应的链接选项，强制静态链接 爆出所有 undefined func。。比如 `-Wl,--no-undefined`  ，具体需要哪些linker flags，自己google 下吧。

**Comment by dsp2000** [comment]
奇怪啊
add_rules("mode.debug", "mode.release")
target("native-lib")
set_kind("shared")
set_languages("c99", "cxx11")
set_warnings("all")
add_includedirs("include", "ffmpeg")
add_linkdirs("libs/$(arch)")
add_files("native-lib.cpp", "ffmpeg.c", "cmdutils.c", "ffmpeg_opt.c", "ffmpeg_filter.c", "ffmpeg_hw.c")

add_links("avcodec");
add_links("avformat");
add_links("swscale");
add_links("swresample");
add_links("avfilter");
add_links("avutil");
add_links("avdevice");
--add_syslinks("log", "z")
add_ldflags("static");

注意我取消了 --add_syslinks("log", "z")
增加了add_ldflags("static");
重新rebuild Project
链接如下
E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ -o ..\..\..\build\xmake\android\arm64-v8a\release\libnative-lib.so ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\native-lib.cpp.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\cmdutils.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_opt.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_filter.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_hw.c.o -Llibs\arm64-v8a -s -lavcodec -lavformat -lswscale -lswresample -lavfilter -lavutil -lavdevice -shared -fPIC -llog -target aarch64-none-linux-android -gcc-toolchain E:\Android\sdk\ndk\21.0.6113669\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64 --sysroot=E:\Android\sdk\ndk\21.0.6113669\platforms\android-21/arch-arm64 -LE:\Android\sdk\ndk\21.0.6113669\sources\cxx-stl\llvm-libc++/libs/arm64-v8a -lc++_static -lc++abi -nostdlib++

注意 -llog 依然存在，而没有add_ldflags("static");把加入

而且-fPIC 是怎样来的？-lc++_static -lc++abi -nostdlib++ 这些好像都没有指定啊

哪里可以查找到clang链接的说明？找半天都没有找到相关的

**Comment by waruqi** [comment]
大哥，你稍微仔细点哈，我刚也没说是 static ，只提了 `-static`，另外具体是哪个 你得自己研究，我只是随手提的几个flags，不保证一定有效，你不要照搬

> 比如 -static, -Wl,--no-undefined 

另外，你加的不支持的flags，xmake会自动忽略，可以通过 force 强制设置上，`add_shflags("-static", "-Wl,--no-undefined", {force = true})`

add_ldflags是给可执行程序，add_shflags是给动态库link，文档有详细说明，不要用错。

**Comment by waruqi** [comment]
> 而且-fPIC 是怎样来的？-lc++_static -lc++abi -nostdlib++ 这些好像都没有指定啊

这些是生成so必须的，所以xmake会内置，否则so不会link通过，可选的 得用户自己设置，。

**Comment by dsp2000** [comment]
我刚才在命令行加了 -static  出错了，好像是有效的
![(L)V@BLPB{90)}59W 76PHB](https://user-images.githubusercontent.com/54521555/99945514-b8546f00-2daf-11eb-83c9-5e40f6f2461f.png)

**Comment by dsp2000** [comment]
我修改了一下

**Comment by dsp2000** [comment]
E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ -o ..\..\..\build\xmake\android\arm64-v8a\release\libnative-lib.so ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\native-lib.cpp.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\cmdutils.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_opt.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_filter.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_hw.c.o -Llibs\arm64-v8a -s -lavcodec -lavformat -lswscale -lswresample -lavfilter -lavutil -lavdevice -shared -fPIC -target aarch64-none-linux-android -gcc-toolchain E:\Android\sdk\ndk\21.0.6113669\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64 --sysroot=E:\Android\sdk\ndk\21.0.6113669\platforms\android-21/arch-arm64 -LE:\Android\sdk\ndk\21.0.6113669\sources\cxx-stl\llvm-libc++/libs/arm64-v8a -lc++_static -lc++abi -nostdlib++ -static

**Comment by dsp2000** [comment]
![7~AYRN285FAEM8{U1`D7(RW](https://user-images.githubusercontent.com/54521555/99945827-50eaef00-2db0-11eb-99bc-6b68be6aa938.png)
我修改了一下 去掉 -llog

**Comment by dsp2000** [comment]
我修改了一下 去掉 -llog 加上-static 出错如下：  上面的是浏览器自己发出的

我ctrl+Enter就自动发了，在QQ之中必须这样，刚才用错了，好像刷屏了

**Comment by waruqi** [comment]
加上 -static ，不是undefined symbols 正常报出来了么。。剩下的就跟xmake没啥关系了，缺啥符号 自己 调链接库吧。。

**Comment by dsp2000** [comment]
如何加入-static 及如何去掉 -llog ？

**Comment by dsp2000** [comment]
现在在命令行显示不完，因为错太多了

**Comment by dsp2000** [comment]
现在在命令行显示不完，因为错太多了，还有在命令行如何将编译的结果重定向到 a.txt现在
E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ -o ..\..\..\build\xmake\android\arm64-v8a\release\libnative-lib.so ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\native-lib.cpp.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\cmdutils.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_opt.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_filter.c.o ..\..\..\build\xmake\.objs\native-lib\android\arm64-v8a\release\ffmpeg_hw.c.o -Llibs\arm64-v8a -s -lavcodec -lavformat -lswscale -lswresample -lavfilter -lavutil -lavdevice -shared -fPIC -llog -target aarch64-none-linux-android -gcc-toolchain E:\Android\sdk\ndk\21.0.6113669\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64 --sysroot=E:\Android\sdk\ndk\21.0.6113669\platforms\android-21/arch-arm64 -LE:\Android\sdk\ndk\21.0.6113669\sources\cxx-stl\llvm-libc++/libs/arm64-v8a -lc++_static -lc++abi -nostdlib++ > error.txt
用不了

及  如何加入-static 及如何去掉 -llog ？
几个问题

**Comment by waruqi** [comment]
-static 会完整static link，包括所有 系统库，这在 android 上肯定会有问题的，很多系统库 ndk 不一定有，只有 device上才有。。
你去掉了 -llog 也没用，还会有一堆其他错误。

所以 我刚不是提了几个flags么，说了不要照搬用，先去 linker man 上自己研究下 是什么意思，怎么个用法，什么时候该用哪个flags，不要照搬贴了一个-static，就一路用到底，觉得不对，可以换其他Flags么。
 
> 比如 -static, -Wl,--no-undefined

去掉-static 直接用 `add_shflags("-Wl,--no-undefined")`
