### ISSUE TITLE
find_vcpk.lua opt.program is incorrectly set to version.exe

### ISSUE THREAD

**Issue by yecate** [xmake-io/xmake#1063]
### 描述问题

xmake.lua:
`add_rules("mode.debug", "mode.release")`
`add_requires("kcp")`
`target("test_kcp")`
 `   set_kind("binary")`
 `  add_files("src/*.cpp")`
 `  add_packages("kcp")`

>cmd: xmake f -p windows -a x64 -m release -vD

### 错误信息
checking for vswhere.exe ... C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
checking for cl.exe ... G:\IDE\vs2019\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2019
checking for dmd ... no
checking for ldc2 ... no
checking for gdc ... no
checking for unzip ... ok
checking for git ... ok
checking for gzip ... ok
checking for tar ... ok 
checking for ping ... ok
pinging for the host(gitee.com) ... 38 ms
checking for nmap ... no
pinging for the host(gitlab.com) ... 65535 ms
pinging for the host(github.com) ... 290 ms
finding kcp from xmake ..     
checking for xmake::kcp ... no
finding kcp from vcpkg ..     
**checkinfo: cannot runv(version.exe version), No such file or directory**
checking for version ... no
checking for vcpkg ... G:\IDE\vcpkg\vcpkg
finding kcp from conan ..
finding kcp from pkg_config ..
checking for pkg-config ... ok
finding kcp from system ..
checking for kcp ... no
note: try installing these packages (pass -y to skip confirm)?
in xmake-repo:
  -> kcp 1.7
please input: y (y/n)

### 相关环境
- xmake版本：2.3.8 dev
- xmake运行平台：windows
- xmake目标平台：windows

### 其他信息
https://github.com/xmake-io/xmake/blob/5bfd4619b0f54678c765064d892c016edbc2f6e8/xmake/modules/detect/tools/find_vcpkg.lua#L70

**Comment by waruqi** [comment]
这个是我后来重构了一次 find_vcpkg 导致，我刚修复了，你再试试 dev 版本

**Comment by yecate** [comment]
可以了
