### ISSUE TITLE
windows10在QT mingw编译项目报错

### ISSUE THREAD

**Issue by baby7305** [xmake-io/xmake#1064]
![image](https://user-images.githubusercontent.com/25588905/100089335-79e0b200-2e8c-11eb-9158-992a7adf2eb2.png)
C:\xmakeCode\hello>xmake b
[ 28%]: compiling.qt.moc src\mainwindow.h
error: x86_64-w64-mingw32-g++: error: CreateProcess: No such file or directory
warning: add_cxflags("-fPIC") is ignored, please pass `{force = true}` or call `set_policy("check.auto_ignore_flags", false)` if you want to set it.

C:\xmakeCode\hello>

**Comment by waruqi** [comment]
装下 mingw g++

```console
pacman -Sy mingw-w64-x86_64-g++
```

**Comment by baby7305** [comment]
装了msys2，pacman安装mingw-w64，
pacman -Syu mingw-w64-x86_64-gcc ，没有g++？
![image](https://user-images.githubusercontent.com/25588905/100177533-38dcb200-2f0d-11eb-962f-f106018d49ea.png)
![image](https://user-images.githubusercontent.com/25588905/100177763-a557b100-2f0d-11eb-8103-0df3580da7b8.png)

**Comment by baby7305** [comment]
这个是在cmd下面的
![image](https://user-images.githubusercontent.com/25588905/100178601-23688780-2f0f-11eb-9627-d2824ccd671e.png)
![image](https://user-images.githubusercontent.com/25588905/100178638-3c713880-2f0f-11eb-9b70-2ed113c52005.png)
error: @programdir\modules\private\async\runjobs.lua:210: @programdir\rules\qt\moc\xmake.lua:115: @programdir\modules\core\tools\gcc.lua:473: x86_64-w64-mingw32-g++: fatal error: cannot execute 'cc1plus': CreateProcess: No such file or directory
compilation terminated.
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:792]: in function 'raise'
    [@programdir\modules\core\tools\gcc.lua:473]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
    [@programdir\modules\core\tools\gcc.lua:422]:
    [C]: in function 'compile'
    [@programdir\rules\qt\moc\xmake.lua:115]: in function 'script'
    [@programdir\actions\build\kinds\object.lua:53]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:188]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:182]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:792: in function 'raise'
        @programdir\modules\private\async\runjobs.lua:210: in function 'catch'
        @programdir\core\sandbox\modules\try.lua:127: in function 'try'
        @programdir\modules\private\async\runjobs.lua:182: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>
warning: add_cxflags("-fPIC") is ignored, please pass `{force = true}` or call `set_policy("check.auto_ignore_flags", false)` if you want to set it.

**Comment by baby7305** [comment]
pacman -Syu  mingw-w64-x86_64-toolchain，用完这个命令还是一样的显示错误

**Comment by waruqi** [comment]
> pacman -Syu mingw-w64-x86_64-gcc ，没有g++？

是 mingw-w64-x86_64-g++ 不是 g++ ，你单装 mingw-w64-x86_64-gcc 是没有  mingw-w64-x86_64-g++  的。

另外，g++ 跟 mingw-w64-x86_64-g++ 是不同的，一个是 msys环境带的，一个是 mingw 工具链带的，你既然用了 mingw ，那就要使用 mingw-w64-x86_64-g++  而不是 g++

**Comment by waruqi** [comment]
> pacman -Syu mingw-w64-x86_64-toolchain，用完这个命令还是一样的显示错误

pacman -Syu mingw-w64-x86_64-g++ 呢？你先确认 mingw-w64-x86_64-g++ 是否存在

**Comment by waruqi** [comment]
> 再不行，给下完整输出：xmake -rvD

另外，之前说的，也给我下，否则我没法进一步分析

**Comment by baby7305** [comment]
mingw-w64-x86_64-g++，这个包在pacman里面不存在，搜不到。。。

**Comment by baby7305** [comment]
$ pacman -Syu mingw-w64-x86_64-g++
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
error: target not found: mingw-w64-x86_64-g++
![image](https://user-images.githubusercontent.com/25588905/100295940-e90df180-2fc5-11eb-8e8e-5df9b7280727.png)

**Comment by baby7305** [comment]
你第一次要以后，已经给过了，拷贝的那堆就是，我再发一次
$ xmake -rvD
error: @programdir\core\main.lua:284: @programdir\core\sandbox\modules\import\core\base\task.lua:65: @programdir\core\project\project.lua:899: @programdir\core\base\path.lua:84: attempt to concatenate local 'p' (a nil value)
stack traceback:
    [@programdir\core\base\path.lua:84]: in function 'join'
    [@programdir\modules\detect\sdks\find_qt.lua:174]: in function '_find_qt'
    [@programdir\modules\detect\sdks\find_qt.lua:204]: in function 'find_qt'
    [@programdir\rules\qt\env\xmake.lua:33]:
    [C]: in function 'load'
    [@programdir\core\project\target.lua:68]: in function '_load_rule'
    [@programdir\core\project\target.lua:88]: in function '_load_rules'
    [@programdir\core\project\target.lua:100]: in function '_load_all'
    [@programdir\core\project\target.lua:139]: in function '_load'
    [@programdir\core\project\project.lua:458]: in function '_load_targets'
    [@programdir\core\project\project.lua:897]: in function 'targets'
    [@programdir\actions\config\main.lua:127]: in function '_check_target'
    [@programdir\actions\config\main.lua:277]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:520]: in function 'run'
    [@programdir\core\sandbox\modules\import\core\base\task.lua:63]: in function 'run'
    [@programdir\actions\build\main.lua:99]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:520]: in function 'run'
    [@programdir\core\main.lua:282]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:792: in function 'raise'
        @programdir\core\main.lua:284: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>

![image](https://user-images.githubusercontent.com/25588905/100296111-53269680-2fc6-11eb-881a-cfad1852dcfb.png)

**Comment by baby7305** [comment]
换个cmd再发一次
C:\xmakeCode\hello>xmake -rvD
error: @programdir\core\main.lua:284: @programdir\core\sandbox\modules\import\core\base\task.lua:65: @programdir\core\project\project.lua:899: @programdir\core\base\path.lua:84: attempt to concatenate local 'p' (a nil value)
stack traceback:
    [@programdir\core\base\path.lua:84]: in function 'join'
    [@programdir\modules\detect\sdks\find_qt.lua:174]: in function '_find_qt'
    [@programdir\modules\detect\sdks\find_qt.lua:204]: in function 'find_qt'
    [@programdir\rules\qt\env\xmake.lua:33]:
    [C]: in function 'load'
    [@programdir\core\project\target.lua:68]: in function '_load_rule'
    [@programdir\core\project\target.lua:88]: in function '_load_rules'
    [@programdir\core\project\target.lua:100]: in function '_load_all'
    [@programdir\core\project\target.lua:139]: in function '_load'
    [@programdir\core\project\project.lua:458]: in function '_load_targets'
    [@programdir\core\project\project.lua:897]: in function 'targets'
    [@programdir\actions\config\main.lua:127]: in function '_check_target'
    [@programdir\actions\config\main.lua:277]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:520]: in function 'run'
    [@programdir\core\sandbox\modules\import\core\base\task.lua:63]: in function 'run'
    [@programdir\actions\build\main.lua:99]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:520]: in function 'run'
    [@programdir\core\main.lua:282]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:792: in function 'raise'
        @programdir\core\main.lua:284: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>

C:\xmakeCode\hello>
![image](https://user-images.githubusercontent.com/25588905/100296310-d0520b80-2fc6-11eb-8b98-6aa14314ed2b.png)

**Comment by baby7305** [comment]
哎，太麻烦了，直接重装QT，把所有构建套件都堆上来。
跑起来了，反正xmake能识别出来就行了。

**Comment by waruqi** [comment]
看你上面图的错误，应该是mingw-w64-x86_64-g++在了的，只不过执行 mingw-w64-x86_64-g++ 时候，它内部执行 cc1plus.exe 发现找不到 就失败了，也就是说你这的环境，没有 cc1plus.exe ，至于为啥没有，我就不清楚了，理论上应该在的。
