### ISSUE TITLE
Protobuf项目生成的compiler_commands不包含对应的pb.h文件

### ISSUE THREAD

**Issue by songouyang** [xmake-io/xmake#1065]
### 描述问题

使用文档用的protobuf工程例子，然后生成对应的compiler_commands.json文件。由于编译命令中没有指定pb的include目录，IDE使用compiler_commands.json无法做出代码提示。不知道这是否符合预期。

<details>
<summary>compile_commands.json</summary>

```json
[
  {
    "directory": "/Users/name/repos/xmake/hello",
    "arguments": [
      "/usr/local/bin/ccache",
      "/usr/local/opt/llvm/bin/clang++",
      "-c",
      "-Qunused-arguments",
      "-arch",
      "x86_64",
      "-std=c++11",
      "-I/Users/name/.xmake/packages/p/protobuf-cpp/3.12.3/d639b7d6e3244216b403b39df5101abf/include",
      "-I/usr/local/include",
      "-I/usr/include",
      "-o",
      "build/.objs/hello/macosx/x86_64/release/src/main.cpp.o",
      "src/main.cpp"
    ],
    "file": "src/main.cpp"
  }
]
```
</details>

<details>
<summary>xmake.lua</summary>

```lua
add_requires("protobuf-cpp")

target("hello")
    set_kind("binary")
    set_languages("c++11")
    add_packages("protobuf-cpp")
    add_files("src/*.cpp")
    add_files("src/*.proto", {rules = "protobuf.cpp"})
```
</details>

<details>
<summary>src/main.cpp</summary>

```cpp
#include <iostream>
#include <string>
#include "request.pb.h"


using namespace std;

int main(int argc, char** argv)
{
  return 0;
}

```
</details>

<details>
<summary>src/request.proto</summary>

```proto
syntax = "proto3";

message SearchRequest {
  string query = 1;
  int32 page_number = 2;
  int32 result_per_page = 3;
}
```
</details>

### 期待的结果

希望include地址可以把pb生成的代码路径加入

### 错误信息

![image](https://user-images.githubusercontent.com/16632254/100093825-05f5d800-2e93-11eb-933b-68ced0019502.png)

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：xmake v2.3.8+202011150524
- xmake运行平台：MacOS
- xmake目标平台：MacOS

**Comment by waruqi** [comment]
pb.h的自动生成是在 protobuf 规则的 `on_build_file()` 脚本里面直接处理的，而 compile_commands 里面目前不支持导出所有的 on_xxx() 脚本内部的各种命令，因此目前是不支持导出pb.h 路径到 compile_commands 的。

这块后期要支持，理论上也是可以，但是要花点时间，可以先在这备着吧，在之后的版本中，如果有时间我会考虑下的。

**Comment by waruqi** [comment]
我在 generator 分支上改进过了，应该支持了，可以更新下试试

```console
xmake update -s github:xmake-io/xmake#generator
```
