### ISSUE TITLE
能否支持并兼容 #cmakedefine 风格的预处理模板，并支持多patten匹配

### ISSUE THREAD

**Issue by wicast** [xmake-io/xmake#1068]
目前在尝试移植libarchive，这个[模板文件](https://github.com/libarchive/libarchive/blob/master/build/cmake/config.h.in) 里有用大量的 #cmakedefine 模板。
#cmakedefine的行为如下：
假如有模板
```c++
#cmakedefine VAR1 
#cmakedefine VAR2 42
#cmakedefine VAR3 ${VAR3}
```
如果 VAR1~3 都为true条件，VAR3 = 23，则：
```c++
#define VAR1 
#define VAR2 42
#define VAR3 23
```
反之条件是false的话则会直接注释掉：
```c++
/* #undef VAR1 */
/* #undef VAR2 */
/* #undef VAR3 */
```
这套行为似乎用现有的xmake无法轻松实现，而我不想动原始代码，单独拿perl，python处理也很麻烦。

需要多patten匹配是因为这个模板里混用了 `@var@` 和 `${var}`

此外，option check失败的情况有时需要设置一些fallback配置
```lua
option("lzma")
    set_showmenu(true)
    add_cincludes("lzma.h")
    set_configvar("HAVE_LZMA_H", 1)
option_end()
-- fallback
if not has_config("lzma") then 
    set_configvar("HAVE_LZMA_H", 0)
end

target("test")
    add_options("lzma")
    set_kind("binary")
    add_files("main.cpp")

    add_configfiles("config.h.in")
```
这个 `if not has_config` 能否再简化一点

**Comment by waruqi** [comment]
> 这套行为似乎用现有的xmake无法轻松实现，而我不想动原始代码，单独拿perl，python处理也很麻烦。

请仔细看下文档，cmake的这些方式xmake全有类似，而且支持的功能还更多一些，当初就是对标cmake的这块，做了类似的支持和改进

@var@ 和 ${var} 都有支持，define替换也有支持 

https://xmake.io/#/zh-cn/manual/project_target?id=targetadd_configfiles

**Comment by wicast** [comment]
> > 这套行为似乎用现有的xmake无法轻松实现，而我不想动原始代码，单独拿perl，python处理也很麻烦。
> 
> 请仔细看下文档，cmake的这些方式xmake全有类似，而且支持的功能还更多一些，当初就是对标cmake的这块，做了类似的支持和改进
> 
> @var@ 和 ${var} 都有支持，define替换也有支持
> 
> https://xmake.io/#/zh-cn/manual/project_target?id=targetadd_configfiles

Define这个我确实漏看了…我想的就是在这个基础上兼容#cmakedefine可以少改很多东西。
 @var@ 和 ${var}我试了半天也只能让其中一个生效，一直没找到两个都生效的语法

**Comment by waruqi** [comment]
暂时不考虑兼容 cmakedefine，var只能支持一个pattern，另外 before_build 里面 自己用 io.gsub 处理替换下 也就一行代码的事

**Comment by wicast** [comment]
那还是算了，还不太习惯lua的文本匹配，我先用py脚本做了
