### ISSUE TITLE
QT widget项目编译时提示不识别qrc资源文件

### ISSUE THREAD

**Issue by baby7305** [xmake-io/xmake#1069]
![image](https://user-images.githubusercontent.com/25588905/100115064-0d29df80-2ead-11eb-92d4-8d0e90413244.png)
![image](https://user-images.githubusercontent.com/25588905/100115126-1ca92880-2ead-11eb-8ee6-e39ae97162e4.png)

add_frameworks("QtWidgets")
加上这句也不行

**Comment by waruqi** [comment]
见 https://github.com/xmake-io/xmake/issues/1058

**Comment by baby7305** [comment]
ヽ(￣▽￣)و
