### ISSUE TITLE
xmake 2.3.9 预编译头失败

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#1070]
升级至 xmake v2.3.9+202011251054 后，预编译设置总是编译失败。

操作系统：mac

复现过程：
新建示例工程：xmake create -l c -P ./hello
新建pch.h，并修改 main.cpp, 将 #include <stdio.h> 加入到 pch.h
修改xmake.lua, 加入 set_pcxxheader("pch.h")

编译出错：
checking for flags (-O3) ... ok
> xcrun -sdk macosx clang "-O3"
checking for ccache ... no
[ 25%]: compiling.release pch.h
"/usr/bin/xcrun -sdk macosx clang" -c -Qunused-arguments -arch x86_64 -mmacosx-version-min=10.15 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fvisibility=hidden -fvisibility-inlines-hidden -O3 -x c++-header -o build/.objs/hello/macosx/x86_64/release/pch.h.pch pch.h
checking for flags (-MMD -MF) ... ok
> xcrun -sdk macosx clang "-MMD" "-MF" "/dev/null"
checking for flags (-fcolor-diagnostics) ... ok
> xcrun -sdk macosx clang "-fcolor-diagnostics"
error: @programdir/modules/private/async/runjobs.lua:210: @programdir/modules/private/action/build/object.lua:78: @programdir/modules/core/tools/gcc.lua:480: clang: error: no such file or directory: 'pch.h'
clang: error: no input files
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:789]: in function 'raise'
    [@programdir/modules/core/tools/gcc.lua:480]: in function 'catch'
    [@programdir/core/sandbox/modules/try.lua:127]: in function 'try'
    [@programdir/modules/core/tools/gcc.lua:429]:
    [C]: in function 'compile'
    [@programdir/modules/private/action/build/object.lua:78]: in function 'script'
    [@programdir/modules/private/action/build/object.lua:91]: in function '_build_object'
    [@programdir/modules/private/action/build/object.lua:102]: in function 'build'
    [@programdir/modules/private/action/build/pcheader.lua:34]:
    [@programdir/rules/c++/xmake.lua:36]: in function 'before_build'
    [@programdir/actions/build/build.lua:155]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:188]:
    [C]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [@programdir/modules/private/async/runjobs.lua:182]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:317]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:789: in function 'raise'
	@programdir/modules/private/async/runjobs.lua:210: in function 'catch'
	@programdir/core/sandbox/modules/try.lua:127: in function 'try'
	@programdir/modules/private/async/runjobs.lua:182: in function 'cotask'
	@programdir/core/base/scheduler.lua:317: in function <@programdir/core/base/scheduler.lua:315>

**Comment by waruqi** [comment]
我这边测试ok

> clang: error: no such file or directory: 'pch.h'

看你的错误，main.cpp 里面 是 `#include "pch.h"`，而 你 xmake.lua 里面 `set_pcxxheader("pch.h")` 是这个，说明pch.h 在根目录下，

`src/main.cpp` 引用根目录的 pch.h ，你有没有加 `add_includedirs(".")` 呢？ 即使不设置 set_pcxxheader ，我觉得也是找不到 pch.h 的

**Comment by fasiondog** [comment]
add_rules("mode.debug", "mode.release")

target("hello")
    set_kind("binary")

    add_includedirs(".")
    set_pcxxheader("pch.h")

    add_files("src/*.c")

加了，还是一样的错误
