### ISSUE TITLE
Allow to install packages from Visual Studio

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#1078]
### Is your feature request related to a problem? Please describe.
When generating a vsxmake project and building it, xmake will try to install any missing dependency.

However it cannot install them as it requires a confirmation by the user which is a bit frustrating since we have to open a shell and run xmake to do it before returning to Visual Studio.
```
1>------ Début de la génération : Projet : Client, Configuration : debug x64 ------
1>$xmake config -P . -p windows -m debug -a x64 -o "build"
1>checking for Microsoft Visual Studio (x64) version ... 2019
1>note: try installing these packages (pass -y to skip confirm)?
1>in xmake-repo:
1>  -> sfml 2.5.1
1>please input: y (y/n)
1>EXEC : error : packages(sfml): must be installed!
```

### Describe the solution you'd like
I'm thinking of two solutions, the first one being to install packages (debug and release, 32bits and 64bits) when generating a vsxmake project, since at this point we're already in the shell.

The second solution would be to be able to install dependencies from Visual Studio, via a property (I'm thinking something that would be automatically enabled as it would be a bit frustration to have to enable it for each project) passing -y to xmake (or something like --allow-install).

### Describe alternatives you've considered
Well, running xmake in a shell everytime I encounter this error, which is a bit frustrating.

**Comment by waruqi** [comment]
I will attempt to improve it, but you can only add `-y` to solve it in Xmake.Custom.props/XmakeCommonFlags now.

**Comment by waruqi** [comment]
I have added -y to vsxmake plugin.

**Comment by SirLynix** [comment]
Thanks! Will try soon

**Comment by SirLynix** [comment]
Can confirm it works! Thank you!

**Comment by SirLynix** [comment]
```
1>$xmake config -P . -y -p windows -m debug -a x64 -o "build"
1>$xmake build -P . -w update_xmake
1>checking for architecture ... x64
1>checking for Microsoft Visual Studio (x64) version ... 2019
1>note: try installing these packages (pass -y to skip confirm)?
1>in xmake-repo:
1>  -> libcurl 7.73.0
1>please input: y (y/n)
1>EXEC : error : packages(libcurl): must be installed!
```

Shouldn't it be added to build as well?

**Comment by waruqi** [comment]
I have added it, try it again?

**Comment by waruqi** [comment]
Does it work?

**Comment by SirLynix** [comment]
Sorry I forgot to answer back, yes it does work! 😄
