### ISSUE TITLE
When using vsxmake, VS cannot find includes

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#1080]
### Describe the bug
When working with a project generated by vsxmake, intellisense cannot find my dependencies headers, breaking auto-completion.

I'm using SFML this way:
```lua
add_requires("sfml")
add_requires("sfml~network", {configs={audio = false, window = false, graphics = false, network = true, main = true}})

add_rules("mode.debug", "mode.release")

target("Client")
    set_kind("binary")
    add_headerfiles("src/*.hpp")
    add_files("src/*.cpp")
    add_packages("sfml")

target("Server")
    set_kind("binary")
    add_headerfiles("src/*.hpp")
    add_files("src/*.cpp")
    add_packages("sfml~network")
```

All I have for now are very simple source files, containing simple code:
![image](https://user-images.githubusercontent.com/3002461/100449840-de7e5580-30b4-11eb-9f9c-6afc62901f18.png)

I don't know if it's supposed to work and is a bug or if it's a missing feature.

Compilation is fine.

### Expected behavior
That Visual Studio is able to find headers in order to have auto-completion and such.

### Related Environment

Please provide compiling and running environment information:

- xmake version: xmake v2.3.9+202011250023
- os: Windows 10 2004
- target platform: Windows

**Comment by waruqi** [comment]
I guess it may be caused by the external header file path. `/external:I`

The real reason can only be confirmed after I debug it. 

However, you can first set `add_requires("xx", {external = false})` to disable external header files, then clear the configuration cache and regenerate vsproj to test and confirm it.

**Comment by SirLynix** [comment]
I can confirm it's working with `{external = false}`.

I looked at the vcxproj generated and when using `external = true` (default value), XmakeIncludeDirs is empty.
```
    <XmakeIncludeDirs></XmakeIncludeDirs>
```

When using `external = false`, it's not
```
    <XmakeIncludeDirs>C:\Users\Lynix\AppData\Local\.xmake\packages\s\sfml\2.5.1\d44505414d5e44aeb34231fb633c4c42\include</XmakeIncludeDirs>
```

**Comment by waruqi** [comment]
That should be caused by the fact that the vsxmake plugin does not support external header files. I will try to improve it later.

**Comment by waruqi** [comment]
I have made the vsxmake plugin to support sysincludedirs, but because my vs environment has not been repaired, I cannot test whether it works now. 

You can help test and verify it. Thanks!

**Comment by SirLynix** [comment]
I can confirm it works, thank you!
