### ISSUE TITLE
Allow cmake out-of-source build to handle filepath over 260 characters

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1082]
### 你在什么场景下需要该功能？

文件路径超过260个字符，超过系统限制

### 描述可能的解决方案

cmake默认是在类似xmake\cache\...\package\version\source\xxxx-xxx-xxxx\build_xxxxxxx\下面构建，这个路径加上cmake生成文件的路径超长了（超出十几个字符），如果可以允许不在源码的子目录下构建（例如放到xmake\cache\...\package\version\build\）就可以解决这个问题

**Comment by waruqi** [comment]
默认的缓存和源码目录改不了，即使缩短了几个字符，也没法根本性解决问题，总归会遇到更长的内部路径的。

> xmake\cache...\package\version\build\

改成这种去掉了 shasum，如果一个包的多个不同配置同时构建就会出问题。。要么就是 遇到有问题的包，cmake.install/build的时候，最后的参数设置 `{build = os.tmpfile() .. ".dir"}` 搞个临时的随机的 tmpdir ，路径固定长度的，不会太长。

**Comment by xq114** [comment]
> 默认的缓存和源码目录改不了，即使缩短了几个字符，也没法根本性解决问题，总归会遇到更长的内部路径的。
> 
> > xmake\cache...\package\version\build\
> 
> 改成这种去掉了 shasum，如果一个包的多个不同配置同时构建就会出问题。。要么就是 遇到有问题的包，cmake.install/build的时候，最后的参数设置 `{build = os.tmpfile() .. ".dir"}` 搞个临时的随机的 tmpdir ，路径固定长度的，不会太长。

问题在于，如果buildir不在源码下，cmake依然会调用`cmake -Dxx=xx ..`，而这里的`..`已经不是源码目录了

**Comment by waruqi** [comment]
我dev上加了个 sourcedir 。。`cmake.install(package, configs, {sourcedir = ".."})`

**Comment by waruqi** [comment]
等下，我还是 sourcedir 内部改成 绝对路径好了

**Comment by waruqi** [comment]
你再试试，我改进过了，固定源码路径了
