### ISSUE TITLE
quotes stripped in defines containing spaces

### ISSUE THREAD

**Issue by cmeerw** [xmake-io/xmake#1084]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug

xmake.lua

```
add_defines("TEST=\"Hello world\"")
target("test")
    set_kind("binary")
    add_files("test.cpp")
```

### Expected behavior

Command line should contain `"-DTEST=\"Hello world\""` (or something similar)

### Error output

actual command line is:

```
/usr/bin/gcc -c -m64 "-DTEST=Hello world" -o build/.objs/test/linux/x86_64/release/test.cpp.o test.cpp
```

### Related Environment

Please provide compiling and running environment information:

- xmake version: v2.3.9+202011250027
- os: Linux (Ubuntu 20.10)
- target platform: Linux (Ubuntu 20.10)

### Additional context

test.cpp should compile cleanly with above xmake.lua file:

```
#include <iostream>

int main()
{
  std::cout << TEST << std::endl;
}
```

Note that

```
add_defines("TEST=\"Hello_world\"")
```

seems to work fine.

**Comment by waruqi** [comment]
I have fixed it on dev branch

**Comment by waruqi** [comment]
I found that the previous changes will affect many other problems, I revert it now. 

I will fix it later, you may need to wait for some time.

**Comment by waruqi** [comment]
Sorry for keeping you waiting so long, I have been dealing with some other issues. Regarding this issue, I have fixed it on the argv branch. You can download it from https://github.com/xmake-io/xmake/actions/runs/477576244 and update to the argv branch version and try it. If it works, I will merge it in these days. 

related patch: https://github.com/xmake-io/xmake/pull/1188

**Comment by waruqi** [comment]
I have merged into dev branch
