### ISSUE TITLE
Mac上，实验四C/C++ 依赖包的集成和使用，执行报错

### ISSUE THREAD

**Issue by baby7305** [xmake-io/xmake#1085]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

请尽量清晰精准地描述你碰到的问题。
Mac上，实验四C/C++ 依赖包的集成和使用，执行报错
songhaibei@MacBook-Pro crc32_conan % xmake run -P
error: execv(/Users/songhaibei/xmakeProjects/code4/crc32_conan/build/macosx/x86_64/release/crc32) failed(-1)

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 错误信息

如果可能，请尽量附加程序运行过程中的错误输出信息。

> 如果是xmake相关编译问题，请加上`-vD`参数运行，并给出详细编译输出信息。

`xmake run -vDP
error: @programdir/core/main.lua:284: @programdir/core/sandbox/modules/os.lua:387: execv(/Users/songhaibei/xmakeProjects/code4/crc32_conan/build/macosx/x86_64/release/crc32) failed(-1)
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:789]: in function 'raise'
    [@programdir/core/sandbox/modules/os.lua:387]: in function 'execv'
    [@programdir/actions/run/main.lua:62]: in function '_do_run_target'
    [@programdir/actions/run/main.lua:89]: in function 'script'
    [@programdir/actions/run/main.lua:144]: in function '_run'
    [@programdir/actions/run/main.lua:214]:
    [C]: in function 'load'
    [@programdir/core/base/task.lua:520]: in function 'run'
    [@programdir/core/main.lua:282]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:317]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:789: in function 'raise'
	@programdir/core/main.lua:284: in function 'cotask'
	@programdir/core/base/scheduler.lua:317: in function <@programdir/core/base/scheduler.lua:315>`

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.3.9
- xmake运行平台：Mac
- xmake目标平台：Mac

### 其他信息

请提供其他附加信息帮助我们诊断问题(比如截图，xmake.lua或者可复现的demo)，以及你遇到的问题的一些背景信息。

![image](https://user-images.githubusercontent.com/25588905/100532769-80c64680-3237-11eb-87f8-a815e66e6efd.png)

**Comment by waruqi** [comment]
> 接下来，我们尝试执行下面的命令运行下这个程序。
> xmake run crc32 somedata

看下这节开头说的运行方式，这个 crc32 的 测试程序 例子，是需要接收 输入字符串参数，来计算 crc的，如果你执行 `xmake run` 那就是没有任何输出参数，这对于一些不接收输入参数的程序运行没什么问题，但是这个例子中的代码你得稍微看下：

```c
#include <stdio.h>
#include <zlib.h>

int main(int argc, char** argv)
{
    printf("crc32: %x!\n", crc32(0, argv[1], strlen(argv[1])));
    return 0;
}
```

这里 `strlen(argv[1])` 会去获取 `xmake run crc32 somedata` 输入的 "somedata" 字符串长度，如果没有就是传入 null，mac上的 strlen 就会 crash

由于这个example ，没做严格的输入检测，所以会有这个问题。

你可以改成 `xmake run crc32 xxxxxxxxx` 来运行测试，另外，不需要追加 `-P` 这个参数。。

如果遇到此类问题的调试手段，切到 debug 模式加载 lldb 调试运行：

```console
xmake f -m debug
xmake
xmake run -d 
(lldb) target create "/private/tmp/test444/build/macosx/x86_64/debug/crc32"
Current executable set to '/private/tmp/test444/build/macosx/x86_64/debug/crc32' (x86_64).
(lldb) r
Process 3013 launched: '/private/tmp/test444/build/macosx/x86_64/debug/crc32' (x86_64)
Process 3013 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00007fff72c51e52 libsystem_platform.dylib`_platform_strlen + 18
libsystem_platform.dylib`_platform_strlen:
->  0x7fff72c51e52 <+18>: pcmpeqb (%rdi), %xmm0
    0x7fff72c51e56 <+22>: pmovmskb %xmm0, %esi
    0x7fff72c51e5a <+26>: andq   $0xf, %rcx
    0x7fff72c51e5e <+30>: orq    $-0x1, %rax
Target 0: (crc32) stopped.
```

**Comment by baby7305** [comment]
升级到2.3.9，xmake的命令不加-P参数就报错。。。
`
songhaibei@MacBook-Pro crc32_conan % xmake -P
[100%]: build ok!
songhaibei@MacBook-Pro crc32_conan % xmake
checking for Xcode directory ... /Applications/Xcode.app
checking for SDK version of Xcode ... 10.15
checking for Codesign Identity of Xcode ... no
checking for Qt SDK directory ... /Users/songhaibei/Qt5.9.9/5.9.9/clang_64
checking for Qt SDK version ... 5.9.9
[ 66%]: linking.release hello
error: clang: error: no input files

warning: You are working in the project directory(/Users/songhaibei/xmakeProjects) and you can also
force to build in current directory via run `xmake -P .`
warning: add -v for getting more warnings ..
songhaibei@MacBook-Pro crc32_conan % 

`
![image](https://user-images.githubusercontent.com/25588905/100533880-49aa6200-3244-11eb-8099-f544319ad144.png)

**Comment by baby7305** [comment]
找出问题了，为啥我老是得加-P参数，我往上级目录放了一个xmake.lua作为模板方便修改。搞得在现在工程里各种不对劲。
后面按照你的说明跑起来了ヽ(￣▽￣)و

**Comment by waruqi** [comment]
> 找出问题了，为啥我老是得加-P参数，我往上级目录放了一个xmake.lua作为模板方便修改。搞得在现在工程里各种不对劲。

上级目录如果存在 xmake.lua ，那么xmake会假定这是一个完整的大工程，那么你在 里面的任意子工程执行 xmake，其实相当于对上级根目录执行，效果是一样的，这是为了方便在任意子目录下执行编译，类似git的效果。。

如果你的子工程是完全独立的，不建议放置在带有上级 xmake.lua 的子目录下，如果非要放在里面，那就通过 -P 指定，强制作为独立子工程编译。
