### ISSUE TITLE
Add environment management for xrepo

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1087]
### 你在什么场景下需要该功能？

xrepo是一个非常好的工具，我觉得可以仿照python的venv或者anaconda来提供一个环境管理。

### 功能描述：

创建环境
```
> xrepo env create venv -p "windows" -b "python 3.8.x"
> xrepo env scan
venv:
  -> python 3.8.5
> 
```

激活/反激活环境
```
> xrepo activate venv
(venv) > cl /?
...
(venv) > python -c "print(__name__)"
__main__
(venv) > xrepo deactivate
> 
```

环境内包管理
```
(venv) > xrepo scan
python 3.8.5:
  -> ...: windows, x64, unused
    -> {...}
(venv) > xrepo install nasm
...
(venv) > nasm -v
NASM version 2.15.05 compiled on Aug 28 2020
(venv) > xrepo remove nasm
...
(venv) >
```

导出/导入环境
```
> xrepo env export venv -o "venv.json" # (或者别的格式)
> xrepo env create venv2 -i "venv.json"
```

删除环境
```
(venv) > xrepo deactivate
> xrepo env remove venv
```

### 使用场景

1. 与在xmake.lua里面放requires不同，这个功能可以对一些binary的包进行快速的测试。例如在xmake某个target要调用nasm，要验证正确性，要么反复修改运行`xmake <target>`（慢！），要么`xrepo env -b "nasm 15.x" nasm...`，很繁琐，尤其是包的数量一多，这个输入会特别麻烦。而有了env之后只需要一次activate，即可直接多次运行nasm

2. 同时安装多个版本的包，避免在`xrepo env xxx`（引入全部包）的时候环境变量冲突。

3. 方便测试一个包的多个版本。xmake.lua里面写`add_requires("xxx 1.x")`，然后全局运行xmake时用的一个版本，xrepo environments里面又是另一个版本，那么不用修改xmake.lua就可以测试同一个包的多个版本，只需要反复激活环境即可。

4. 在c++与python混合开发的时候anaconda和venv都不行（anaconda的python与c++交互不好，venv基于一个host python），xmake在这个时候将具有无可取代的优势。c++与julia混合开发同理，有点类似HPC里面常用的Environment Modules，但比Environment Modules更加强大

### 其他信息

[Conda Docs](https://docs.conda.io/en/latest/)
[Environment Modules Docs](https://modules.readthedocs.io/en/latest/)

这个功能比较复杂，一时也不急，可以暂时放着，只是作为一个建议

**Comment by waruqi** [comment]
多包的环境管理目前是有的，只是还比较雏形，目前的xrepo 只是初版，现在你只能通过 `xrepo env -b "pkg1,pkg2,pkg3" ..` 来激活绑定多个包的环境来运行程序

之后会考虑改进这块的处理，但具体得看我这边的进度安排，先在这里备着吧。

**Comment by waruqi** [comment]
我改进过了，你可以通过在 xmake.lua 里面配置 add_requires() 来管理包环境

### Case1

直接在带有 add_requires("luajit") 维护的已有工程目录下，执行

```console
$ xrepo env shell
xrepo> luajit --version
```

### Case2

如果不是 xmake 工程，也可以单独在目录下 创建个 xmake.lua 仅仅维护 add_requires，不需要配置任何 targets，也就自动拉取包，最后加载环境

```lua
add_requires("luajit")
add_requires("python 3.x")
...
```

```console
$ xrepo env shell
xrepo> luajit --version
xrepo> python --version
```

### 运行自定义 shell

`xrepo env shell` 是内置的，会自动加载 bash/sh/cmd 绑定环境，修改 prompt。。

当然也可以自己指定 shell

```console
$ xrepo env bash
$ xrepo env zsh
$ xrepo env luajit
$ xrepo env python
```

环境的导入导出维护就没必要了，当前的 xmake.lua 就是一个完整环境，里面的包可以通过 add_requires 做更加灵活定制化配置维护。。导入导出就是 xmake.lua 文件的整体迁移，完全独立，每个 xmake.lua 对应的 xrepo env 都是一个独立的 sandbox ，也方便保存。

**Comment by xq114** [comment]
请问如何退出环境？

**Comment by waruqi** [comment]
就是加载的 shell ，ctrl+c 就退了

**Comment by xq114** [comment]
试用了一下，效果不错，还有一些小建议：

1. 能否自动根据当前shell判断启动哪一种shell？我在powershell中输入xrepo env shell然后打开了bash
2. 能否在打开的shell中加入提示信息？例如`[<projectname>] PS C:\...` 在bash中设置比较简单，改PS1环境变量即可；Cmd也很简单，改PROMPT环境变量即可；powershell比较复杂，需要调用一个powershell函数，参考conda
```
function Add-CondaEnvironmentToPrompt() {
    function global:prompt() {
        if ($Env:CONDA_PROMPT_MODIFIER) {
            $Env:CONDA_PROMPT_MODIFIER | Write-Host -NoNewline
        }
        CondaPromptBackup;
    }
}
```

**Comment by xq114** [comment]
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_prompts

powershell prompt的文档

**Comment by waruqi** [comment]
稍微改进了下探测，以及 prompt 提示，powershell 不太会玩，先就这样吧，或者你可以帮忙改进下  https://github.com/xmake-io/xmake/blob/52d50b181831215fb9dc56448745e8e64895968d/xmake/modules/private/xrepo/action/env.lua#L262

**Comment by xq114** [comment]
> 稍微改进了下探测，以及 prompt 提示，powershell 不太会玩，先就这样吧，或者你可以帮忙改进下

1. 这里os.term()不妥，可以用```(dir 2>&1 *`|echo CMD);&<# rem #>echo ($PSVersionTable).PSEdition```
![image](https://user-images.githubusercontent.com/42310255/114898328-933ac880-9e44-11eb-87f6-c19d50c33fdd.png)
![image](https://user-images.githubusercontent.com/42310255/114898881-165c1e80-9e45-11eb-8539-6cb9963c807c.png)
详见https://stackoverflow.com/questions/34471956/how-to-determine-if-im-in-powershell-or-cmd

2. 有必要区分旧版powershell与新版powershell core，后者的启动命令为pwsh.exe而非powershell.exe
3. powershell提示符设置简版```pwsh -noexit -c 'function prompt { \"project \" + $(Get-Location) + \"> \" }'```
![image](https://user-images.githubusercontent.com/42310255/114899260-65a24f00-9e45-11eb-8075-12ca2f56a1b1.png)

4. cmd提示符设置并没有生效，设置环境变量应为```cmd /k "set PROMPT=project ^>"```
![image](https://user-images.githubusercontent.com/42310255/114900422-6edfeb80-9e46-11eb-9e79-f7b900755ca6.png)

我这边可以试着改一下
