### ISSUE TITLE
QT导入自己生成的静态库报错

### ISSUE THREAD

**Issue by baby7305** [xmake-io/xmake#1088]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

请尽量清晰精准地描述你碰到的问题。
QT导入自己生成的静态库报错，'QDialog' file not found，静态库包含UI文件后报错。
代码来源于《QT5.9C++开发指南》12章静态库调用部分代码。

代码显示格式变了，字体变斜有些*号没有了，最下面图片截图是对的。

`
add_rules("mode.debug", "mode.release")

target("myStaticLib")
    add_rules("qt.static")
    add_headerfiles("myStaticLib/*.h")
    add_files("myStaticLib/*.cpp")
    add_files("myStaticLib/qwdialogpen.ui")
    -- add files with Q_OBJECT meta (only for qt.moc)
    add_files("myStaticLib/qwdialogpen.h")
    add_frameworks("QtNetwork", "QtGui")

target("LibUser")
    add_rules("qt.widgetapp")
    add_headerfiles("LibUser/*.h")
    add_headerfiles("LibUser/include/*.h")
    add_files("LibUser/*.cpp")
    add_files("LibUser/mainwindow.ui")
    -- add files with Q_OBJECT meta (only for qt.moc)
    add_files("LibUser/mainwindow.h")
    add_deps("myStaticLib")`

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 错误信息

如果可能，请尽量附加程序运行过程中的错误输出信息。
`xmake -rvD
[ 23%]: compiling.qt.ui LibUser/mainwindow.ui
/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/bin/uic LibUser/mainwindow.ui -o build/.gens/LibUser/macosx/x86_64/release/rules/qt/ui/ui_mainwindow.h
[ 38%]: compiling.qt.ui myStaticLib/qwdialogpen.ui
/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/bin/uic myStaticLib/qwdialogpen.ui -o build/.gens/myStaticLib/macosx/x86_64/release/rules/qt/ui/ui_qwdialogpen.h
checking for /usr/bin/xcrun -sdk macosx clang ... ok
checking for flags (-fvisibility-inlines-hidden) ... ok
> xcrun -sdk macosx clang "-fvisibility-inlines-hidden"
checking for flags (-O3) ... ok
> xcrun -sdk macosx clang "-O3"
checking for flags (-fPIC) ... ok
> xcrun -sdk macosx clang "-fPIC"
[ 46%]: compiling.qt.moc myStaticLib/qwdialogpen.h
/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/bin/moc -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtNetwork.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtGui.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtCore.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/mkspecs/macx-clang -I/Users/songhaibei/QtProject/Qt5d9CppDevGuide/12d3/build/.gens/myStaticLib/macosx/x86_64/release/rules/qt/ui -F/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib myStaticLib/qwdialogpen.h -o build/.gens/myStaticLib/macosx/x86_64/release/rules/qt/moc/moc_qwdialogpen.cpp
[ 30%]: compiling.qt.moc LibUser/mainwindow.h
/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/bin/moc -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_WIDGETS_LIB -DQT_CORE_LIB -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtGui.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtWidgets.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtCore.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/mkspecs/macx-clang -I/Users/songhaibei/QtProject/Qt5d9CppDevGuide/12d3/build/.gens/LibUser/macosx/x86_64/release/rules/qt/ui -F/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib LibUser/mainwindow.h -o build/.gens/LibUser/macosx/x86_64/release/rules/qt/moc/moc_mainwindow.cpp
checking for ccache ... no
"/usr/bin/xcrun -sdk macosx clang" -c -Qunused-arguments -arch x86_64 -mmacosx-version-min=10.15 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++11 -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtNetwork.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtGui.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtCore.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/mkspecs/macx-clang -I/Users/songhaibei/QtProject/Qt5d9CppDevGuide/12d3/build/.gens/myStaticLib/macosx/x86_64/release/rules/qt/ui -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -F /Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib -framework QtNetwork -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework CoreFoundation -framework CoreGraphics -framework OpenGL -framework Carbon -framework Foundation -framework AppKit -framework Security -framework SystemConfiguration -fPIC -o build/.objs/myStaticLib/macosx/x86_64/release/gens/rules/qt/moc/moc_qwdialogpen.cpp.o build/.gens/myStaticLib/macosx/x86_64/release/rules/qt/moc/moc_qwdialogpen.cpp
"/usr/bin/xcrun -sdk macosx clang" -c -Qunused-arguments -arch x86_64 -mmacosx-version-min=10.15 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++11 -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtGui.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtWidgets.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtCore.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/mkspecs/macx-clang -I/Users/songhaibei/QtProject/Qt5d9CppDevGuide/12d3/build/.gens/LibUser/macosx/x86_64/release/rules/qt/ui -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_WIDGETS_LIB -DQT_CORE_LIB -F /Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib -framework QtNetwork -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework CoreFoundation -framework CoreGraphics -framework OpenGL -framework Carbon -framework Foundation -framework AppKit -framework Security -framework SystemConfiguration -framework QtWidgets -fPIC -o build/.objs/LibUser/macosx/x86_64/release/gens/rules/qt/moc/moc_mainwindow.cpp.o build/.gens/LibUser/macosx/x86_64/release/rules/qt/moc/moc_mainwindow.cpp
checking for flags (-MMD -MF) ... ok
> xcrun -sdk macosx clang "-MMD" "-MF" "/dev/null"
checking for flags (-fcolor-diagnostics) ... ok
> xcrun -sdk macosx clang "-fcolor-diagnostics"
error: @programdir/modules/private/async/runjobs.lua:210: @programdir/rules/qt/moc/xmake.lua:115: @programdir/modules/core/tools/gcc.lua:480: In file included from build/.gens/myStaticLib/macosx/x86_64/release/rules/qt/moc/moc_qwdialogpen.cpp:9:
build/.gens/myStaticLib/macosx/x86_64/release/rules/qt/moc/../../../../../../../../../myStaticLib/qwdialogpen.h:4:13: fatal error: 'QDialog' file not found
#include    <QDialog>
            ^~~~~~~~~
1 error generated.
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:789]: in function 'raise'
    [@programdir/modules/core/tools/gcc.lua:480]: in function 'catch'
    [@programdir/core/sandbox/modules/try.lua:127]: in function 'try'
    [@programdir/modules/core/tools/gcc.lua:429]:
    [C]: in function 'compile'
    [@programdir/rules/qt/moc/xmake.lua:115]: in function 'script'
    [@programdir/actions/build/kinds/object.lua:53]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:188]:
    [C]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [@programdir/modules/private/async/runjobs.lua:182]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:317]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:789: in function 'raise'
	@programdir/modules/private/async/runjobs.lua:210: in function 'catch'
	@programdir/core/sandbox/modules/try.lua:127: in function 'try'
	@programdir/modules/private/async/runjobs.lua:182: in function 'cotask'
	@programdir/core/base/scheduler.lua:317: in function <@programdir/core/base/scheduler.lua:315>
`

> 如果是xmake相关编译问题，请加上`-vD`参数运行，并给出详细编译输出信息。

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：
- xmake运行平台：
- xmake目标平台：

### 其他信息

请提供其他附加信息帮助我们诊断问题(比如截图，xmake.lua或者可复现的demo)，以及你遇到的问题的一些背景信息。
![image](https://user-images.githubusercontent.com/25588905/100535985-854f2700-3258-11eb-9c48-1b7353f584e5.png)

**Comment by waruqi** [comment]
> build/.gens/myStaticLib/macosx/x86_64/release/rules/qt/moc/../../../../../../../../../myStaticLib/qwdialogpen.h:4:13: fatal error: 'QDialog' file not found

看了下 https://doc.qt.io/qt-5/qdialog.html ，QDialog 是在 QtWidget frameworks里面的，但是你的 myStaticLib 里面并没有加上这个 frameworks

```
target("myStaticLib")
add_rules("qt.static")
add_headerfiles("myStaticLib/.h")
add_files("myStaticLib/.cpp")
add_files("myStaticLib/qwdialogpen.ui")
-- add files with Q_OBJECT meta (only for qt.moc)
add_files("myStaticLib/qwdialogpen.h")
add_frameworks("QtNetwork", "QtGui")
```


这种头文件找不到问题，缺什么就到qt官方文档上找对应的库在哪，加上就是了

**Comment by baby7305** [comment]
### 现在改成这样了，
`
target("myStaticLib")
    add_rules("qt.static")
    add_headerfiles("myStaticLib/*.h")
    add_files("myStaticLib/*.cpp")
    add_files("myStaticLib/qwdialogpen.ui")
    -- add files with Q_OBJECT meta (only for qt.moc)
    add_files("myStaticLib/qwdialogpen.h")
    add_frameworks("QtWidgets","QtGui")

target("LibUser")
    add_rules("qt.widgetapp")
    add_headerfiles("LibUser/*.h")
    add_headerfiles("LibUser/include/*.h")
    add_files("LibUser/*.cpp")
    add_files("LibUser/mainwindow.ui")
    -- add files with Q_OBJECT meta (only for qt.moc)
    add_files("LibUser/mainwindow.h")
    add_files("LibUser/include/qwdialogpen.h")
    add_deps("myStaticLib")
`
然后提示，
`
xmake -rvD
[ 21%]: compiling.qt.ui myStaticLib/qwdialogpen.ui
/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/bin/uic myStaticLib/qwdialogpen.ui -o build/.gens/myStaticLib/macosx/x86_64/release/rules/qt/ui/ui_qwdialogpen.h
[ 28%]: compiling.qt.moc myStaticLib/qwdialogpen.h
/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/bin/moc -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtWidgets.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtGui.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtCore.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/mkspecs/macx-clang -I/Users/songhaibei/QtProject/Qt5d9CppDevGuide/12d3/build/.gens/myStaticLib/macosx/x86_64/release/rules/qt/ui -F/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib myStaticLib/qwdialogpen.h -o build/.gens/myStaticLib/macosx/x86_64/release/rules/qt/moc/moc_qwdialogpen.cpp
[ 35%]: compiling.qt.ui LibUser/mainwindow.ui
/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/bin/uic LibUser/mainwindow.ui -o build/.gens/LibUser/macosx/x86_64/release/rules/qt/ui/ui_mainwindow.h
[ 42%]: compiling.qt.moc LibUser/mainwindow.h
/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/bin/moc -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_WIDGETS_LIB -DQT_CORE_LIB -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtGui.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtWidgets.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtCore.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/mkspecs/macx-clang -I/Users/songhaibei/QtProject/Qt5d9CppDevGuide/12d3/build/.gens/LibUser/macosx/x86_64/release/rules/qt/ui -F/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib LibUser/mainwindow.h -o build/.gens/LibUser/macosx/x86_64/release/rules/qt/moc/moc_mainwindow.cpp
[ 50%]: compiling.qt.moc LibUser/include/qwdialogpen.h
/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/bin/moc -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_WIDGETS_LIB -DQT_CORE_LIB -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtGui.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtWidgets.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtCore.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/mkspecs/macx-clang -I/Users/songhaibei/QtProject/Qt5d9CppDevGuide/12d3/build/.gens/LibUser/macosx/x86_64/release/rules/qt/ui -F/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib LibUser/include/qwdialogpen.h -o build/.gens/LibUser/macosx/x86_64/release/rules/qt/moc/moc_qwdialogpen.cpp
"/usr/bin/xcrun -sdk macosx clang" -c -Qunused-arguments -arch x86_64 -mmacosx-version-min=10.15 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++11 -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtWidgets.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtGui.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtCore.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/mkspecs/macx-clang -I/Users/songhaibei/QtProject/Qt5d9CppDevGuide/12d3/build/.gens/myStaticLib/macosx/x86_64/release/rules/qt/ui -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -F /Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework CoreFoundation -framework CoreGraphics -framework OpenGL -framework Carbon -framework Foundation -framework AppKit -framework Security -framework SystemConfiguration -fPIC -o build/.objs/myStaticLib/macosx/x86_64/release/gens/rules/qt/moc/moc_qwdialogpen.cpp.o build/.gens/myStaticLib/macosx/x86_64/release/rules/qt/moc/moc_qwdialogpen.cpp
"/usr/bin/xcrun -sdk macosx clang" -c -Qunused-arguments -arch x86_64 -mmacosx-version-min=10.15 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++11 -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtGui.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtWidgets.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtCore.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/mkspecs/macx-clang -I/Users/songhaibei/QtProject/Qt5d9CppDevGuide/12d3/build/.gens/LibUser/macosx/x86_64/release/rules/qt/ui -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_WIDGETS_LIB -DQT_CORE_LIB -F /Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework CoreFoundation -framework CoreGraphics -framework OpenGL -framework Carbon -framework Foundation -framework AppKit -framework Security -framework SystemConfiguration -fPIC -o build/.objs/LibUser/macosx/x86_64/release/gens/rules/qt/moc/moc_mainwindow.cpp.o build/.gens/LibUser/macosx/x86_64/release/rules/qt/moc/moc_mainwindow.cpp
"/usr/bin/xcrun -sdk macosx clang" -c -Qunused-arguments -arch x86_64 -mmacosx-version-min=10.15 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++11 -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtGui.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtWidgets.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtCore.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/mkspecs/macx-clang -I/Users/songhaibei/QtProject/Qt5d9CppDevGuide/12d3/build/.gens/LibUser/macosx/x86_64/release/rules/qt/ui -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_WIDGETS_LIB -DQT_CORE_LIB -F /Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework CoreFoundation -framework CoreGraphics -framework OpenGL -framework Carbon -framework Foundation -framework AppKit -framework Security -framework SystemConfiguration -fPIC -o build/.objs/LibUser/macosx/x86_64/release/gens/rules/qt/moc/moc_qwdialogpen.cpp.o build/.gens/LibUser/macosx/x86_64/release/rules/qt/moc/moc_qwdialogpen.cpp
[ 57%]: compiling.release myStaticLib/qwdialogpen.cpp
"/usr/bin/xcrun -sdk macosx clang" -c -Qunused-arguments -arch x86_64 -mmacosx-version-min=10.15 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++11 -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtWidgets.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtGui.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtCore.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/mkspecs/macx-clang -I/Users/songhaibei/QtProject/Qt5d9CppDevGuide/12d3/build/.gens/myStaticLib/macosx/x86_64/release/rules/qt/ui -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -F /Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework CoreFoundation -framework CoreGraphics -framework OpenGL -framework Carbon -framework Foundation -framework AppKit -framework Security -framework SystemConfiguration -fPIC -o build/.objs/myStaticLib/macosx/x86_64/release/myStaticLib/qwdialogpen.cpp.o myStaticLib/qwdialogpen.cpp
[ 64%]: compiling.release LibUser/mainwindow.cpp
"/usr/bin/xcrun -sdk macosx clang" -c -Qunused-arguments -arch x86_64 -mmacosx-version-min=10.15 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++11 -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtGui.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtWidgets.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtCore.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/mkspecs/macx-clang -I/Users/songhaibei/QtProject/Qt5d9CppDevGuide/12d3/build/.gens/LibUser/macosx/x86_64/release/rules/qt/ui -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_WIDGETS_LIB -DQT_CORE_LIB -F /Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework CoreFoundation -framework CoreGraphics -framework OpenGL -framework Carbon -framework Foundation -framework AppKit -framework Security -framework SystemConfiguration -fPIC -o build/.objs/LibUser/macosx/x86_64/release/LibUser/mainwindow.cpp.o LibUser/mainwindow.cpp
[ 71%]: compiling.release LibUser/main.cpp
"/usr/bin/xcrun -sdk macosx clang" -c -Qunused-arguments -arch x86_64 -mmacosx-version-min=10.15 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++11 -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtGui.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtWidgets.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib/QtCore.framework/Headers -I/Users/songhaibei/Qt5.9.9/5.9.9/clang_64/mkspecs/macx-clang -I/Users/songhaibei/QtProject/Qt5d9CppDevGuide/12d3/build/.gens/LibUser/macosx/x86_64/release/rules/qt/ui -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_WIDGETS_LIB -DQT_CORE_LIB -F /Users/songhaibei/Qt5.9.9/5.9.9/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework CoreFoundation -framework CoreGraphics -framework OpenGL -framework Carbon -framework Foundation -framework AppKit -framework Security -framework SystemConfiguration -fPIC -o build/.objs/LibUser/macosx/x86_64/release/LibUser/main.cpp.o LibUser/main.cpp
error: @programdir/modules/private/async/runjobs.lua:210: @programdir/modules/private/action/build/object.lua:78: @programdir/modules/core/tools/gcc.lua:480: LibUser/mainwindow.cpp:4:13: fatal error: 'qwdialogpen.h' file not found
#include    "qwdialogpen.h"
            ^~~~~~~~~~~~~~~
1 error generated.
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:789]: in function 'raise'
    [@programdir/modules/core/tools/gcc.lua:480]: in function 'catch'
    [@programdir/core/sandbox/modules/try.lua:127]: in function 'try'
    [@programdir/modules/core/tools/gcc.lua:429]:
    [C]: in function 'compile'
    [@programdir/modules/private/action/build/object.lua:78]: in function 'script'
    [@programdir/modules/private/action/build/object.lua:91]: in function '_build_object'
    [@programdir/modules/private/action/build/object.lua:116]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:188]:
    [C]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [@programdir/modules/private/async/runjobs.lua:182]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:317]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:789: in function 'raise'
	@programdir/modules/private/async/runjobs.lua:210: in function 'catch'
	@programdir/core/sandbox/modules/try.lua:127: in function 'try'
	@programdir/modules/private/async/runjobs.lua:182: in function 'cotask'
	@programdir/core/base/scheduler.lua:317: in function <@programdir/core/base/scheduler.lua:315>
`

### 找不到静态库的头文件
![image](https://user-images.githubusercontent.com/25588905/100539920-c9e8bb80-3274-11eb-8666-ccb26586d13f.png)

**Comment by waruqi** [comment]
你先到 qt sdk 里面找下这个 qwdialogpen.h 头文件在哪，然后确认下大小名字对不对，有些mac系统文件名是大小写敏感的，而这里 include 的大小写不匹配 一样会找不到。。

因为很多从其他地方copy过来的项目，有可能是人家 win上写的，所以没考虑大小写。

如果大小写确认也是对的，那就提供下这个头文件的完整路径名给我看下

**Comment by baby7305** [comment]
### 完整路径名字，
### /Users/songhaibei/QtProject/Qt5d9CppDevGuide/12d3/LibUser/include/qwdialogpen.h
![image](https://user-images.githubusercontent.com/25588905/100541883-d6274580-3281-11eb-8dea-5afd3e1de1d6.png)

**Comment by waruqi** [comment]
> /Users/songhaibei/QtProject/Qt5d9CppDevGuide/12d3/LibUser/include/qwdialogpen.h

?? 自己目录的头文件？ 那你不设置 add_includedirs 怎么可能找的到呢？

**Comment by baby7305** [comment]
改成这样，加上add_includedirs成功了！ƪ(˘⌣˘)┐
`
add_rules("mode.debug", "mode.release")

target("myStaticLib")
add_rules("qt.static")
add_headerfiles("myStaticLib/*.h")
add_files("myStaticLib/*.cpp")
add_files("myStaticLib/qwdialogpen.ui")
-- add files with Q_OBJECT meta (only for qt.moc)
add_files("myStaticLib/qwdialogpen.h")
add_frameworks("QtWidgets","QtGui")

target("LibUser")
add_rules("qt.widgetapp")
add_headerfiles("LibUser/*.h")
add_includedirs("LibUser/include")
add_files("LibUser/*.cpp")
add_files("LibUser/mainwindow.ui")
-- add files with Q_OBJECT meta (only for qt.moc)
add_files("LibUser/mainwindow.h")
add_deps("myStaticLib")
`
