### ISSUE TITLE
"yacc" rule not adding generated directory to include directories

### ISSUE THREAD

**Issue by cmeerw** [xmake-io/xmake#1089]
### Describe the bug

`xmake.lua` as follows:

```
target("test")
    set_kind("binary")

    add_rules("yacc")

    add_files("p.yy")
    add_files("test.cpp")
```

`p.yy`:

```
%code
{
  extern int yylex ();
  extern void yyerror (const char *);
}

%token T_TEST

%%
start: T_TEST
%%
```

and `test.cpp`

```
#include "p.tab.hpp"
```

### Expected behavior

`#include` directive in `test.cpp` finds the generated `p.tab.hpp`
(Note: I don't expect this test case to link cleanly, but it should compile cleanly)

### Error output

```
/usr/bin/gcc -c -m64 -o build/.objs/test/linux/x86_64/release/test.cpp.o test.cpp
error: test.cpp:1:10: fatal error: p.tab.hpp: No such file or directory
    1 | #include "p.tab.hpp"
      |          ^~~~~~~~~~~
```

### Related Environment

Please provide compiling and running environment information:

- xmake version: v2.3.9+202011250027
- os: Linux (Ubuntu 20.10)
- target platform: Linux (Ubuntu 20.10)

**Comment by waruqi** [comment]
I have exported includedirs for yacc on dev branch. you can update to dev and try it. `xmake update -s dev`

**Comment by cmeerw** [comment]
that works, thanks.
