### ISSUE TITLE
incorrect ordering of inherited library dependencies

### ISSUE THREAD

**Issue by cmeerw** [xmake-io/xmake#1091]
### Describe the bug

`xmake.lua`

```
target("test1")
    set_kind("static")
    add_links("z", { public = true })
    add_files("test1.cpp")

target("test")
    set_kind("binary")
    add_deps("test1")
    add_files("test.cpp")
```

`test1.cpp`

```
#include <zlib.h>

void foo()
{
  auto p = inflate;
}
```

`test.cpp`

```
extern void foo();

int main()
{
  foo();
}
```

assuming that `zlib.h` and libz.so are found and provide an `inflate` function.

### Expected behavior

Compiles and links cleanly with the libraries specified as `-ltest1 -lz` (as `test1` clearly depends on `z`)

### Error output

```
[ 87%]: linking.release test
/usr/bin/g++ -o build/linux/x86_64/release/test build/.objs/test/linux/x86_64/release/test.cpp.o -m64 -Lbuild/linux/x86_64/release -lz -ltest1
error: /usr/bin/ld: build/linux/x86_64/release/libtest1.a(test1.cpp.o): in function `foo()':
test1.cpp:(.text+0xb): undefined reference to `inflate'
collect2: error: ld returned 1 exit status
```

### Related Environment

Please provide compiling and running environment information:

- xmake version: v2.3.9+202011250027
- os: Linux (Ubuntu 20.10)
- target platform: Linux (Ubuntu 20.10)

### Additional context

On Linux the order of libraries specified is important, so xmake needs to be careful to not re-order libraries specified. Also need to think about if duplicate entries can be removed (maybe not always safe to do - at least the last occurrence should remain regardless)

**Comment by waruqi** [comment]
I have fixed it on dev branch.

**Comment by waruqi** [comment]
Does it work?

**Comment by structure-charger** [comment]
xxx@devops-5:~/new$ xmake
[ 33%]: compiling.release test1.cpp
[ 58%]: archiving.release libtest1.a
[ 91%]: linking.release test
[100%]: build ok!
xxx@devops-5:~/new$ cd build/
xxx@devops-5:~/new/build$ ls
linux
xxx@devops-5:~/new/build$ cd linux/x86_64/release/
xxx@devops-5:~/new/build/linux/x86_64/release$ ./test 
xxx@devops-5:~/new/build/linux/x86_64/release$ ls
libtest1.a  new  test

ubuntu 20.04 x86_64 build the code which had error above succeed now.

**Comment by cmeerw** [comment]
yes, working for me now. Thanks.
