### ISSUE TITLE
xmake f -p cross --sdk=E:\Android\sdk\ndk\21.0.6113669\toolchains没有成功

### ISSUE THREAD

**Issue by dsp2000** [xmake-io/xmake#1092]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
请在这描述你需要讨论的话题详情。

需要交叉编译安卓的项目

xmake f -p cross --sdk=E:\Android\sdk\ndk\21.0.6113669\
xmake f -p cross --sdk=E:\Android\sdk\ndk\21.0.6113669\toolchains

都返回
checking for the architecture ... none

没有成功
E:\Android\sdk\ndk\21.0.6113669\AdvMedia>xmake --version
xmake v2.3.4+202006071439, A cross-platform build utility based on Lua
Copyright (C) 2015-2020 Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|

                         by ruki, tboox.org

    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor

   ==========================================================================
  | A new version of xmake is available!                                     |
  |                                                                          |
  | To update to the latest version v2.3.9, run "xmake update".              |
   ==========================================================================

**Comment by waruqi** [comment]
android 不是有专门的 android 平台么，不用走通用的交叉编译工具链

```console
xmake f -p android --ndk=E:\Android\sdk\ndk\21.0.6113669
```

看下文档：https://xmake.io/#/zh-cn/guide/configuration?id=android

**Comment by dsp2000** [comment]
如果我想同时编译armeabi-v7a及arm64-v8a 平台的，可以在xmake.lua里面指定吗？

下面只是生成xmake.lua吧？
xmake f -p android --ndk=~/files/android-ndk-r10e/ [-a armeabi-v7a|arm64-v8a]

**Comment by waruqi** [comment]
> 如果我想同时编译armeabi-v7a及arm64-v8a 平台的，可以在xmake.lua里面指定吗？

一次编译只能编一个arch，你只能执行两次编译，或者用 xmake-gradle 插件可以同时编译多个arch

> 下面只是生成xmake.lua吧？
> xmake f -p android --ndk=~/files/android-ndk-r10e/ [-a armeabi-v7a|arm64-v8a]

xmake.lua需要你自己写的，这个只是配置编译平台和工具链

**Comment by dsp2000** [comment]
如何指定 APP_PLATFORM=android-16 这个？

**Comment by waruqi** [comment]
--ndk_sdkver

你可以自己到help下查看

```
$ xmake f --help | grep ndk
        --ndk=NDK                                            The NDK Directory
        --ndk_sdkver=NDK_SDKVER                              The SDK Version for NDK (default:
auto)
        --ndk_stdcxx=[y|n]                                   Use stdc++ library for NDK (defaul
t: y)
        --ndk_cxxstl=NDK_CXXSTL                              The stdc++ stl library for NDK
```
