### ISSUE TITLE
xmake集成指定目录的opencv不成功

### ISSUE THREAD

**Issue by baby7305** [xmake-io/xmake#1093]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

请尽量清晰精准地描述你碰到的问题。
xmake集成指定目录的opencv不成功。

`
add_rules("mode.debug", "mode.release")

add_packagedirs("C:\\opencv4d5d0\\build")

target("xmake-opencv-app")
    add_rules("qt.console")
    add_includedirs("C:\\opencv4d5d0\\build\\include")
    add_files("src/*.cpp")
    add_packages("opencv")
`

`
#include <QCoreApplication>

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    printf("hello xmake\n");
    Mat srcImage = imread("../lianggongchunri_de_youyv-009.jpg");
    if (!srcImage.data) {
        std::cout << "Image not loaded";
        return -1;
    }
    imshow("[img]", srcImage);
    waitKey(0);
    return a.exec();
}

`

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 错误信息

如果可能，请尽量附加程序运行过程中的错误输出信息。

> 如果是xmake相关编译问题，请加上`-vD`参数运行，并给出详细编译输出信息。
`
xmake -rvD
[ 50%]: compiling.release src\main.cpp
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\cl.exe" -c /EHsc -nologo -Ox -fp:fast -IC:\opencv4d5d0\build\include -IC:\Qt\Qt5.14.2\5.14.2\msvc2015_64\include\QtCore -IC:\Qt\Qt5.14.2\5.14.2\msvc2015_64\include -IC:\Qt\Qt5.14.2\5.14.2\msvc2015_64\mkspecs\win32-msvc -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_CORE_LIB -Fobuild\.objs\xmake-opencv-app\windows\x64\release\src\main.cpp.obj src\main.cpp
error: @programdir\modules\private\async\runjobs.lua:210: @programdir\modules\private\action\build\object.lua:78: @programdir\modules\core\tools\cl.lua:453: main.cpp
src\main.cpp(8): error C2065: “Mat”: 未声明的标识符
src\main.cpp(8): error C2146: 语法错误: 缺少“;”(在标识符“srcImage”的前面)
src\main.cpp(8): error C2065: “srcImage”: 未声明的标识符
src\main.cpp(8): error C3861: “imread”: 找不到标识符
src\main.cpp(9): error C2065: “srcImage”: 未声明的标识符
src\main.cpp(10): error C2039: "cout": 不是 "std" 的成员
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\chrono(24): note: 参见“std”的声明
src\main.cpp(10): error C2065: “cout”: 未声明的标识符
src\main.cpp(13): error C2065: “srcImage”: 未声明的标识符
src\main.cpp(13): error C3861: “imshow”: 找不到标识符
src\main.cpp(14): error C3861: “waitKey”: 找不到标识符

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:789]: in function 'raise'
    [@programdir\modules\core\tools\cl.lua:453]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
    [@programdir\modules\core\tools\cl.lua:407]:
    [C]: in function 'compile'
    [@programdir\modules\private\action\build\object.lua:78]: in function 'script'
    [@programdir\modules\private\action\build\object.lua:91]: in function '_build_object'
    [@programdir\modules\private\action\build\object.lua:116]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:188]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:182]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:789: in function 'raise'
        @programdir\modules\private\async\runjobs.lua:210: in function 'catch'
        @programdir\core\sandbox\modules\try.lua:127: in function 'try'
        @programdir\modules\private\async\runjobs.lua:182: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>
warning: add_cxflags("-fPIC") is ignored, please pass `{force = true}` or call `set_policy("check.auto_ignore_flags", false)` if you want to set it.
`

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.3.9
- xmake运行平台：win10
- xmake目标平台：win10

### 其他信息

请提供其他附加信息帮助我们诊断问题(比如截图，xmake.lua或者可复现的demo)，以及你遇到的问题的一些背景信息。

**Comment by waruqi** [comment]
> add_packagedirs("C:\opencv4d5d0\build")

这个走的本地包模式，得自己构造 opencv.pkg 包放到这个目录，你确定用对了，有特定结构的（不过这块文档我没补全），里面内置了 opencv.lib 了？参考：https://xmake.io/#/zh-cn/package/local_package

不过 xxx.pkg 的构建文档还不全，https://tboox.org/cn/2016/08/06/add-package-and-autocheck/ 这篇有点包，仅供参考，有些接口快废弃了，回头有时间我补全下文档。。

还有一种方式，创建个静态库项目，打包生成 xxx.pkg 进去看下大概结构

```console
xmake create -t static test
cd test
xmake 
xmake package  ---> 打包 xxx.pkg
```

**Comment by waruqi** [comment]
另外，https://github.com/xmake-io/xmake/issues/1086 之前这个还是不行么？ 走 `add_requires("opencv")` 应该可以的，windows上还没有收录，回头有时间我也会加进去，这样不同平台都可以使用同一统一的方式接入 opencv 

或者可以先走 vcpkg /conan 的包源，应该也是可以的

**Comment by baby7305** [comment]
### 改成下面这样了
![image](https://user-images.githubusercontent.com/25588905/100711799-c2e4b900-33ec-11eb-8d2b-7ed5caf883ac.png)

`
add_rules("mode.debug", "mode.release")

add_packagedirs("pkg")

target("xmake-opencv-app")
    add_rules("qt.console")
    add_files("src/*.cpp")
    add_packages("opencv4d5d0")
`

`
option("opencv4d5d0")
    set_showmenu(true)
    set_category("package")
    add_links("opencv4d5d0")
    add_linkdirs("C:\\opencv4d5d0\\build/$(arch)/lib/$(mode)")
    add_includedirs("C:\\opencv4d5d0\\build\\include")
    set_languages("cxx11")
`

`
xmake -rvD
[ 50%]: compiling.release src\main.cpp
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\cl.exe" -c /EHsc -nologo -Ox -fp:fast -IC:\Qt\Qt5.14.2\5.14.2\msvc2015_64\include\QtCore -IC:\Qt\Qt5.14.2\5.14.2\msvc2015_64\include -IC:\Qt\Qt5.14.2\5.14.2\msvc2015_64\mkspecs\win32-msvc -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_CORE_LIB -Fobuild\.objs\xmake-opencv-app\windows\x64\release\src\main.cpp.obj src\main.cpp
error: @programdir\modules\private\async\runjobs.lua:210: @programdir\modules\private\action\build\object.lua:78: @programdir\modules\core\tools\cl.lua:453: main.cpp
src\main.cpp(8): error C2065: “Mat”: 未声明的标识符
src\main.cpp(8): error C2146: 语法错误: 缺少“;”(在标识符“srcImage”的前面)
src\main.cpp(8): error C2065: “srcImage”: 未声明的标识符
src\main.cpp(8): error C3861: “imread”: 找不到标识符
src\main.cpp(9): error C2065: “srcImage”: 未声明的标识符
src\main.cpp(10): error C2039: "cout": 不是 "std" 的成员
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\chrono(24): note: 参见“std”的声明
src\main.cpp(10): error C2065: “cout”: 未声明的标识符
src\main.cpp(13): error C2065: “srcImage”: 未声明的标识符
src\main.cpp(13): error C3861: “imshow”: 找不到标识符
src\main.cpp(14): error C3861: “waitKey”: 找不到标识符

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:789]: in function 'raise'
    [@programdir\modules\core\tools\cl.lua:453]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
    [@programdir\modules\core\tools\cl.lua:407]:
    [C]: in function 'compile'
    [@programdir\modules\private\action\build\object.lua:78]: in function 'script'
    [@programdir\modules\private\action\build\object.lua:91]: in function '_build_object'
    [@programdir\modules\private\action\build\object.lua:116]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:188]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:182]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:789: in function 'raise'
        @programdir\modules\private\async\runjobs.lua:210: in function 'catch'
        @programdir\core\sandbox\modules\try.lua:127: in function 'try'
        @programdir\modules\private\async\runjobs.lua:182: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>
warning: add_cxflags("-fPIC") is ignored, please pass `{force = true}` or call `set_policy("check.auto_ignore_flags", false)` if you want to set it.
`

### include目录，lib目录分别是下面几个
![image](https://user-images.githubusercontent.com/25588905/100711637-8913b280-33ec-11eb-82e6-7bb7773e6c88.png)

![image](https://user-images.githubusercontent.com/25588905/100711591-74371f00-33ec-11eb-97af-de6094fc0fcd.png)

**Comment by waruqi** [comment]
执行 `xmake f -c -vD` 清下配置检测缓存，然后重新编译，给我下完整输出。。

**Comment by xq114** [comment]
main.cpp有#include头文件吗？问题里面只有一个空的#include，是不是这块漏了

**Comment by baby7305** [comment]
> 执行 `xmake f -c -vD` 清下配置检测缓存，然后重新编译，给我下完整输出（包括 xmake f 的）。。

### 清缓存
`
xmake f -c -vD
checking for architecture ... x64
checking for vswhere.exe ... C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
checking for cl.exe ... C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2019
checking for dmd ... no
checking for ldc2 ... no
checking for gdc ... no
checking for the c compiler (cc) ... cl.exe
> "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\cl.exe" -c -nologo -IC:\opencv4d5d0\build\include -FoC:\Users\songh\AppData\Local\Temp\.xmake\201201\_6945597EB68A49608D725F332ABCC8A0.o C:\Users\songh\AppData\Local\Temp\.xmake\201201\_F24C0D1CE03B496083FC6DB09FEFE5E0.c
checking for link.exe ... C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\link.exe
checking for the linker (ld) ... link.exe
> "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\link.exe" -nologo -dynamicbase -nxcompat -machine:x64 -libpath:C:\opencv4d5d0\build\x64\lib\release opencv4d5d0.lib -out:C:\Users\songh\AppData\Local\Temp\.xmake\201201\_0F697DA08E3A4960807A5F5EB6F5CCD0.b C:\Users\songh\AppData\Local\Temp\.xmake\201201\_6945597EB68A49608D725F332ABCC8A0.o
> checking for c links(opencv4d5d0)
checkinfo: ...gramdir\core\sandbox\modules\import\core\tool\linker.lua:91: @programdir\modules\core\tools\link.lua:146: LINK : fatal error LNK1181: 无法打开输入文件“opencv4d5d0.lib”

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:789]: in function 'raise'
    [@programdir\modules\core\tools\link.lua:146]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
    [@programdir\modules\core\tools\link.lua:127]:
    [C]: in function 'link'
    [...gramdir\core\sandbox\modules\import\core\tool\linker.lua:89]: in function 'link'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:202]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:192]:
    [C]: in function 'load'
    [@programdir\core\project\option.lua:103]: in function '_on_check'
    [@programdir\core\project\option.lua:168]: in function '_check'
    [@programdir\core\project\option.lua:218]: in function 'check'
    [...dir\core\sandbox\modules\import\core\project\project.lua:108]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:188]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:182]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

checking for opencv4d5d0 ... no
checking for qmake ... C:\Qt\Qt5.14.2\5.14.2\msvc2015_64\bin\qmake
checking for Qt SDK directory ... C:/Qt/Qt5.14.2/5.14.2/msvc2015_64
checking for Qt SDK version ... 5.14.2
configure
{
    opencv4d5d0 = false
    plat = windows
    vs = 2019
    host = windows
    kind = static
    qt = C:/Qt/Qt5.14.2/5.14.2/msvc2015_64
    ccache = true
    mode = release
    ndk_stdcxx = true
    qt_sdkver = 5.14.2
    clean = true
    arch = x64
    buildir = build
}
`
### 重新编译
`
xmake -rvD
checking for the c++ compiler (cxx) ... cl.exe
checking for C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\cl.exe ... ok
checking for flags (-Ox -fp:fast) ... ok
> cl.exe "-Ox" "-fp:fast" "/EHsc"
checking for flags (-std:c++11) ... no
> cl.exe "-std:c++11" "/EHsc"
checking for flags (-fPIC) ... no
> cl.exe "-fPIC" "/EHsc"
checking for ccache ... no
[ 50%]: compiling.release src\main.cpp
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\cl.exe" -c /EHsc -nologo -Ox -fp:fast -IC:\Qt\Qt5.14.2\5.14.2\msvc2015_64\include\QtCore -IC:\Qt\Qt5.14.2\5.14.2\msvc2015_64\include -IC:\Qt\Qt5.14.2\5.14.2\msvc2015_64\mkspecs\win32-msvc -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_CORE_LIB -Fobuild\.objs\xmake-opencv-app\windows\x64\release\src\main.cpp.obj src\main.cpp
checking for flags (cl_sourceDependencies) ... ok
> cl.exe "/sourceDependencies" "C:\Users\songh\AppData\Local\Temp\.xmake\201201\_CC72AA60AD964D3083443C3F2768EF60.json" "/EHsc"
error: @programdir\modules\private\async\runjobs.lua:210: @programdir\modules\private\action\build\object.lua:78: @programdir\modules\core\tools\cl.lua:453: main.cpp
src\main.cpp(8): error C2065: “Mat”: 未声明的标识符
src\main.cpp(8): error C2146: 语法错误: 缺少“;”(在标识符“srcImage”的前面)
src\main.cpp(8): error C2065: “srcImage”: 未声明的标识符
src\main.cpp(8): error C3861: “imread”: 找不到标识符
src\main.cpp(9): error C2065: “srcImage”: 未声明的标识符
src\main.cpp(10): error C2039: "cout": 不是 "std" 的成员
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\chrono(24): note: 参见“std”的声明
src\main.cpp(10): error C2065: “cout”: 未声明的标识符
src\main.cpp(13): error C2065: “srcImage”: 未声明的标识符
src\main.cpp(13): error C3861: “imshow”: 找不到标识符
src\main.cpp(14): error C3861: “waitKey”: 找不到标识符

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:789]: in function 'raise'
    [@programdir\modules\core\tools\cl.lua:453]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
    [@programdir\modules\core\tools\cl.lua:407]:
    [C]: in function 'compile'
    [@programdir\modules\private\action\build\object.lua:78]: in function 'script'
    [@programdir\modules\private\action\build\object.lua:91]: in function '_build_object'
    [@programdir\modules\private\action\build\object.lua:116]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:188]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:182]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:789: in function 'raise'
        @programdir\modules\private\async\runjobs.lua:210: in function 'catch'
        @programdir\core\sandbox\modules\try.lua:127: in function 'try'
        @programdir\modules\private\async\runjobs.lua:182: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>
warning: add_cxflags("-fPIC") is ignored, please pass `{force = true}` or call `set_policy("check.auto_ignore_flags", false)` if you want to set it.

`

**Comment by waruqi** [comment]
> checkinfo: ...gramdir\core\sandbox\modules\import\core\tool\linker.lua:91: @programdir\modules\core\tools\link.lua:146: LINK : fatal error LNK1181: 无法打开输入文件“opencv4d5d0.lib”
> checking for opencv4d5d0 ... no


看错误，很明显啊，opencv4d5d0 包检测失败，opencv4d5d0.lib 库没找到，你的 add_linkdirs 路径配置不对啊。。。

看你的截图 实际 lib 文件路径和名字，不单纯 linkdirs 不对，add_links 的名字也对不上哈。。。

**Comment by baby7305** [comment]
> main.cpp有#include头文件吗？问题里面只有一个空的#include，是不是这块漏了

还真的是没加，现在加上头文件和命名空间。。。

`
#include <QCoreApplication>
#include <iostream>
#include <opencv2/opencv.hpp>

using namespace std;
using namespace cv;

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    printf("hello xmake\n");
    Mat srcImage = imread("../lianggongchunri_de_youyv-009.jpg");
    if (!srcImage.data) {
        std::cout << "Image not loaded";
        return -1;
    }
    imshow("[img]", srcImage);
    waitKey(0);
    return a.exec();
}

`

**Comment by baby7305** [comment]
> > checkinfo: ...gramdir\core\sandbox\modules\import\core\tool\linker.lua:91: @programdir\modules\core\tools\link.lua:146: LINK : fatal error LNK1181: 无法打开输入文件“opencv4d5d0.lib”
> > checking for opencv4d5d0 ... no
> 
> 看错误，很明显啊，opencv4d5d0 包检测失败，opencv4d5d0.lib 库没找到，你的 add_linkdirs 路径配置不对啊。。。
> 
> 看你的截图 实际 lib 文件路径和名字，不单纯 linkdirs 不对，add_links 的名字也对不上哈。。。

### 清理缓存

`
xmake f -c -vD
checking for architecture ... x64
checking for vswhere.exe ... C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
checking for cl.exe ... C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2019
checking for dmd ... no
checking for ldc2 ... no
checking for gdc ... no
checking for the c compiler (cc) ... cl.exe
> "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\cl.exe" -c -nologo -IC:\opencv4d5d0\build\include -FoC:\Users\songh\AppData\Local\Temp\.xmake\201201\_DD12439E29CA49708BAE773D3D2C2380.o C:\Users\songh\AppData\Local\Temp\.xmake\201201\_7AFE7AFEA57B49708C1ADD48CAE797C0.c
checking for link.exe ... C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\link.exe
checking for the linker (ld) ... link.exe
> "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\link.exe" -nologo -dynamicbase -nxcompat -machine:x64 -libpath:C:\opencv4d5d0\build\x64\lib\release opencv4d5d0.lib -out:C:\Users\songh\AppData\Local\Temp\.xmake\201201\_E432D5D9AC1A49708B917DDFD4707EC0.b C:\Users\songh\AppData\Local\Temp\.xmake\201201\_DD12439E29CA49708BAE773D3D2C2380.o
> checking for c links(opencv4d5d0)
checkinfo: ...gramdir\core\sandbox\modules\import\core\tool\linker.lua:91: @programdir\modules\core\tools\link.lua:146: LINK : fatal error LNK1181: 无法打开输入文件“opencv4d5d0.lib”

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:789]: in function 'raise'
    [@programdir\modules\core\tools\link.lua:146]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
    [@programdir\modules\core\tools\link.lua:127]:
    [C]: in function 'link'
    [...gramdir\core\sandbox\modules\import\core\tool\linker.lua:89]: in function 'link'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:202]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:192]:
    [C]: in function 'load'
    [@programdir\core\project\option.lua:103]: in function '_on_check'
    [@programdir\core\project\option.lua:168]: in function '_check'
    [@programdir\core\project\option.lua:218]: in function 'check'
    [...dir\core\sandbox\modules\import\core\project\project.lua:108]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:188]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:182]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

checking for opencv4d5d0 ... no
checking for qmake ... C:\Qt\Qt5.14.2\5.14.2\msvc2015_64\bin\qmake
checking for Qt SDK directory ... C:/Qt/Qt5.14.2/5.14.2/msvc2015_64
checking for Qt SDK version ... 5.14.2
configure
{
    kind = static
    qt = C:/Qt/Qt5.14.2/5.14.2/msvc2015_64
    qt_sdkver = 5.14.2
    mode = release
    clean = true
    buildir = build
    ndk_stdcxx = true
    opencv4d5d0 = false
    arch = x64
    ccache = true
    vs = 2019
    plat = windows
    host = windows
}
`


### 重新编译

`
xmake -rvD
checking for the c++ compiler (cxx) ... cl.exe
checking for C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\cl.exe ... ok
checking for flags (-Ox -fp:fast) ... ok
> cl.exe "-Ox" "-fp:fast" "/EHsc"
checking for flags (-std:c++11) ... no
> cl.exe "-std:c++11" "/EHsc"
checking for flags (-fPIC) ... no
> cl.exe "-fPIC" "/EHsc"
checking for ccache ... no
[ 50%]: compiling.release src\main.cpp
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\cl.exe" -c /EHsc -nologo -Ox -fp:fast -IC:\Qt\Qt5.14.2\5.14.2\msvc2015_64\include\QtCore -IC:\Qt\Qt5.14.2\5.14.2\msvc2015_64\include -IC:\Qt\Qt5.14.2\5.14.2\msvc2015_64\mkspecs\win32-msvc -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_CORE_LIB -Fobuild\.objs\xmake-opencv-app\windows\x64\release\src\main.cpp.obj src\main.cpp
checking for flags (cl_sourceDependencies) ... ok
> cl.exe "/sourceDependencies" "C:\Users\songh\AppData\Local\Temp\.xmake\201201\_3277404CF1464F4089929BBA62321580.json" "/EHsc"
error: @programdir\modules\private\async\runjobs.lua:210: @programdir\modules\private\action\build\object.lua:78: @programdir\modules\core\tools\cl.lua:453: main.cpp
src\main.cpp(3): fatal error C1083: 无法打开包括文件: “opencv2/opencv.hpp”: No such file or directory

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:789]: in function 'raise'
    [@programdir\modules\core\tools\cl.lua:453]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
    [@programdir\modules\core\tools\cl.lua:407]:
    [C]: in function 'compile'
    [@programdir\modules\private\action\build\object.lua:78]: in function 'script'
    [@programdir\modules\private\action\build\object.lua:91]: in function '_build_object'
    [@programdir\modules\private\action\build\object.lua:116]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:188]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:182]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:789: in function 'raise'
        @programdir\modules\private\async\runjobs.lua:210: in function 'catch'
        @programdir\core\sandbox\modules\try.lua:127: in function 'try'
        @programdir\modules\private\async\runjobs.lua:182: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>
warning: add_cxflags("-fPIC") is ignored, please pass `{force = true}` or call `set_policy("check.auto_ignore_flags", false)` if you want to set it.
`

**Comment by baby7305** [comment]
> > checkinfo: ...gramdir\core\sandbox\modules\import\core\tool\linker.lua:91: @programdir\modules\core\tools\link.lua:146: LINK : fatal error LNK1181: 无法打开输入文件“opencv4d5d0.lib”
> > checking for opencv4d5d0 ... no
> 
> 看错误，很明显啊，opencv4d5d0 包检测失败，opencv4d5d0.lib 库没找到，你的 add_linkdirs 路径配置不对啊。。。
> 
> 看你的截图 实际 lib 文件路径和名字，不单纯 linkdirs 不对，add_links 的名字也对不上哈。。。

重新改了下，编译过了。
`
option("opencv4d5d0")
    set_showmenu(true)
    set_category("package")
    add_links("opencv_world450")
    add_linkdirs("C:\\opencv4d5d0\\build\\x64\\vc14\\lib")
    add_includedirs("C:\\opencv4d5d0\\build\\include")
    set_languages("cxx11")
`
最后的dll在哪里配置路径呢？

![image](https://user-images.githubusercontent.com/25588905/100717898-a8fba400-33f5-11eb-88fd-6f226b3966ba.png)

**Comment by waruqi** [comment]
dll 得加 PATH 路径，通过 add_runenvs 加，不过话说 你都打算用本地lib库了，干嘛这么麻烦整 add_packagedirs/add_packages   你直接 add_linkdirs/add_links 到你的项目 xmake.lua 不就完事了么。。

**Comment by baby7305** [comment]
把dll目录加进去执行成功了。

`
option("opencv4d5d0")
    set_showmenu(true)
    set_category("package")
    add_links("opencv_world450")
    add_linkdirs("C:\\opencv4d5d0\\build\\x64\\vc14\\lib")
    add_linkdirs("C:\\opencv4d5d0\\build\\x64\\vc14\\bin")
    add_includedirs("C:\\opencv4d5d0\\build\\include")
    set_languages("cxx11")
`

**Comment by baby7305** [comment]
唉？话说图片可以写相对路径吗？我写了后读不到图片，必须要把图片放到release目录下？

**Comment by waruqi** [comment]
> 唉？话说图片可以写相对路径吗？我写了后读不到图片，必须要把图片放到release目录下？

可以通过 set_rundir 修改 target 的运行目录，也可以 xmake run -w /rundir 直接改

**Comment by baby7305** [comment]
@成功跑起来啦，提交到这里φ(゜▽゜*)♪
git@github.com:baby7305/xmake-opencv-app.git
