### ISSUE TITLE
VS target should not be linked to msys2 libraries on windows

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1094]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

在windows上用vs编译，`require("libpng")`时找到了msys2的库，导致链接失败

### 期待的结果

vs应该忽略msys2的库

### 错误信息

cannot open input file png16.lib

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.3.9
- xmake运行平台：windows
- xmake目标平台：windows

### 其他信息

![image](https://user-images.githubusercontent.com/42310255/100700614-d6862480-33d8-11eb-990f-565543a69ff4.png)

**Comment by waruqi** [comment]
我过滤掉了。你再试试
