### ISSUE TITLE
use version:major() in add_urls()

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1095]
### 你在什么场景下需要该功能？

在add_urls里面需要用`function (version) return version:major()..".x/v" .. version end`

### 其他信息

目前这么写会报错，version似乎传入的只是普通字符串

**Comment by waruqi** [comment]
我改了

**Comment by xq114** [comment]
现在报错attempt to concatenate local 'version' (a table value)

**Comment by xq114** [comment]
cmake也挂了，还是暂时不要改了吧，我在cmake的xmake.lua里面找到解决办法了
```
version = function (version)
    return table.concat(table.slice((version):split('%.'), 1, 2), '.') .. "/cmake-" .. version
end
```

**Comment by waruqi** [comment]
> 现在报错attempt to concatenate local 'version' (a table value)

我刚改了下，应该可以了，只要再重载下 .. 拼接就行了，可以完全兼容

**Comment by waruqi** [comment]
> cmake也挂了，还是暂时不要改了吧，我在cmake的xmake.lua里面找到解决办法了
> 
> ```
> version = function (version)
>     return table.concat(table.slice((version):split('%.'), 1, 2), '.') .. "/cmake-" .. version
> end
> ```

你再还原回去试试

**Comment by waruqi** [comment]
cmake的 string.split 我也兼容了

**Comment by xq114** [comment]
> 你再还原回去试试

还有`version:startswith("v")`

**Comment by waruqi** [comment]
> > 你再还原回去试试
> 
> 还有`version:startswith("v")`

加了

**Comment by waruqi** [comment]
不过cmake的要等appveryor 上跑完才能生效 你等会在测试

**Comment by waruqi** [comment]
这里应该没问题了，我先close了

**Comment by waruqi** [comment]
有少数几个包 用了 commits[version] 这种，我暂时 xmake 无法兼容，不过数量不多，我暂时 包里面直接去兼容了 commits[tostring(version)]

在xmake还没发版前，可以都这么处理下
