### ISSUE TITLE
add package.tools.gn

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1097]
### 你在什么场景下需要该功能？

https://github.com/xq114/xmake-repo/tree/master/packages/s/skia

skia库使用gn构建，
```
gn gen build --args='...'
ninja -C build
```
然而这里需要手动设置环境变量来给ninja检测，（新版gn windows上在args里面设置cc和cxx已经不行了，会报错），传入参数的时候需要判断string、boolean是否加引号等等，这些操作感觉可以抽象出来做一个统一的package.tools.gn框架

**Comment by waruqi** [comment]
可以 不过要等个几天了

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/blob/dev/xmake/modules/package/tools/gn.lua 我加上了，不过还是个初版，新版的gn还没时间研究

还有些case需要进一步研究

- prefix 如何对接 installdir ,  gn 是否支持类似 gn --prefix=...
- 如果不支持指定 prefix, gn生成的 ninja.build 在执行 ninja install 之后是否有固定install结构
- cc/ld/cflags等环境的接入

**Comment by waruqi** [comment]
我稍微修了些小问题，你那个 skia patch 我 macos  上测试可以过掉

**Comment by waruqi** [comment]
这个先这样吧，等之后如果需要继续改进，可以再提
