### ISSUE TITLE
xmake安卓llvm编译--ndk_sdkver=16时出现没有找到 no member named 'log2f' in the global namespace

### ISSUE THREAD

**Issue by dsp2000** [xmake-io/xmake#1099]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
请在这描述你需要讨论的话题详情。

xmake安卓llvm编译--ndk_sdkver=21编译是正常的，但使用一些低版本的手机加载so出错。
当将--ndk_sdkver=16编译时提示出错
**error: E:\Android\sdk\ndk\21.0.6113669\sources\cxx-stl\llvm-libc++/include\math.
h:1373:93: error: no member named 'log2f' in the global namespace
inline _LIBCPP_INLINE_VISIBILITY float       log2(float __lcpp_x) _NOEXCEPT
  {return ::log2f(__lcpp_x);}

在xmake.lua里面链接是这样的：
add_syslinks("log", "z", "m")
add_shflags("-Wl,--no-undefined")

找到一篇文章，想试试加入stl 
Android源码中的c++ STL_田海立@CSDN-CSDN博客
https://blog.csdn.net/thl789/article/details/109864831

但不知怎样加

或者如果stl不行，有什么方法可以处理掉 log2f 这个问题？

**Comment by waruqi** [comment]
stl 通过 --ndk_cxxstl 参数切，具体使用看 help 

> 或者如果stl不行，有什么方法可以处理掉 log2f 这个问题？

这是ndk的问题，低版本ndk如果不支持这个，我也没办法，这个又不是xmake的问题，你可以到 ndk issues 上去问问

**Comment by dsp2000** [comment]
怎样加入 -fPIC ?


E:\Android\sdk\ndk\21.0.6113669\KcCore>xmake
checking for the Android SDK directory ... E:\Android\sdk
checking for the Build Tools Version of Android SDK ... 29.0.3
checking for the NDK directory ... E:\Android\sdk\ndk\21.0.6113669
checking for the SDK version of NDK ... 21
checking for the toolchains version of NDK ... 4.9
[ 90%]: linking.release libKcCore.so
error: E:\Android\sdk\ndk\21.0.6113669\toolchains\arm-linux-androideabi-4.9\preb
uilt\windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-an
droideabi/bin\ld: error: libs\armeabi-v7a/libmp3lame.a(quantize_pvt.o): requires
 unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC

**Comment by dsp2000** [comment]
--ndk_cxxstl 
用xmake --help 好像没有对应的说明
我需要依次选择 
gabl++_static  
stlport_static 
gnustl_static 
c++_static 


是加入 --ndk_cxxstl=上面列表吗？

**Comment by waruqi** [comment]
> droideabi/bin\ld: error: libs\armeabi-v7a/libmp3lame.a(quantize_pvt.o): requires

你这个库 libmp3lame 没加 -fPIC，如果也是 xmake编译的，那就 add_cxflags("-fPIC") ，如果是直接引入的三方库，就得自己搞搞了

**Comment by waruqi** [comment]
> --ndk_cxxstl
> 用xmake --help 好像没有对应的说明
> 我需要依次选择
> gabl++_static
> stlport_static
> gnustl_static
> c++_static
> 
> 是加入 --ndk_cxxstl=上面列表吗？

这还需要啥说明，ndk 不就那么几个 stl 么，你可以去 android ndk 官方文档上看下说明，

> 是加入 --ndk_cxxstl=上面列表吗？

对啊 不然怎么用，就是用来切换Stl的

**Comment by dsp2000** [comment]
./configure \
		--prefix=${PREFIX} \
		--host=${LINUX} \
		--disable-shared \
    --enable-static \
		${FEATURES}


	make clean
	make -j4 install

libmp3lame 我是上面的脚本的，如何加入-fPIC

如果换用xmake 编译，应该怎样做？

**Comment by waruqi** [comment]
autotools的使用 和 cflags的设置 你自己google下吧 我这里只处理 xmake的问题

如果要用xmake重编它，要么自己源码移植到xmake.lua然后加-fPIC

要么走xmake的trybuild模式，但这是trybuild，内部调用autotools做的尝试构建，不保证一定成功，即使失败了也正常

xmake f -p android --ndk=/xxx --trybuild=autotools --cxflags="-fPIC"

**Comment by dsp2000** [comment]
D:\pAndroid\multimedia\app\jni\lame-3.100>xmake f -p android --ndk=E:\Android\sd
k\ndk\21.0.6113669 -a armeabi-v7a --trybuild=autotools --cxflags="-fPIC"
checking for the Android SDK directory ... E:\Android\sdk
checking for the Build Tools Version of Android SDK ... 29.0.3
checking for the NDK directory ... E:\Android\sdk\ndk\21.0.6113669
checking for the SDK version of NDK ... 21
checking for the toolchains version of NDK ... 4.9

D:\pAndroid\multimedia\app\jni\lame-3.100>xmake
note: xmake.lua not found, try generating it (pass -y or --confirm=y/n/d to skip
 confirm)?
please input: n (y/n)
y
xmake.lua not found, scanning files ..
error: project not found!

生成不了xmake.lua就表示是失败了吗？

内部调用autotools，会不会是因为没有安装一系列工具？
1. autoscan
2. aclocal
3. autoconf
4. autoheader
5. automake

**Comment by dsp2000** [comment]
另外，如何在mingw32里面下载及使用xmake ?

**Comment by waruqi** [comment]
> 
> xmake.lua not found, scanning files ..
> error: project not found!
> 
> 生成不了xmake.lua就表示是失败了吗？

这是 trybuild 模式的一个bug 按理应该不走到这个，我刚修复了，更新下dev版本，`xmake update -s dev`

**Comment by waruqi** [comment]
> 另外，如何在mingw32里面下载及使用xmake ?

无关问题请开新issues 安装文档里有说明 https://xmake.io/#/zh-cn/guide/installation?id=msysmingw

**Comment by dsp2000** [comment]
D:\pAndroid\multimedia\app\jni\lame-3.100>xmake update -s dev
update version dev from official source ..
  => downloading https://gitee.com/tboox/xmake.git .. (1/git) (1/git) (1/git) 7
(1/git) (1/git) (1/git) (1/git) (1/git) (1/git) (1/git) (1/git) (1/git) 7⠙8[K
  => download https://gitee.com/tboox/xmake.git .. ok
  => install script to D:\Program Files (x86)\xmake .. ok

D:\pAndroid\multimedia\app\jni\lame-3.100>xmake f -p android --ndk=E:\Android\sd
k\ndk\21.0.6113669 -a armeabi-v7a --trybuild=autotools --cxflags="-fPIC"
checking for Android SDK directory ... E:\Android\sdk
checking for Build Tools Version of Android SDK ... 29.0.3
checking for NDK directory ... E:\Android\sdk\ndk\21.0.6113669
checking for SDK version of NDK ... 21
checking for toolchains version of NDK ... 4.9

D:\pAndroid\multimedia\app\jni\lame-3.100>xmake
note: xmake.lua not found, try generating it (pass -y or --confirm=y/n/d to skip
 confirm)?
please input: n (y/n)
y
xmake.lua not found, scanning files ..
error: project not found!


D:\pAndroid\multimedia\app\jni\lame-3.100>xmake --version
xmake v2.3.4+202006071439, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|

                         by ruki, xmake.io

    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor

   ==========================================================================
  | A new version of xmake is available!                                     |
  |                                                                          |
  | To update to the latest version v2.3.9, run "xmake update".              |
   ==========================================================================


D:\pAndroid\multimedia\app\jni\lame-3.100>

**Comment by waruqi** [comment]
你用的还是2.3.4的 先到ci上下载最新安装包装下 

https://github.com/xmake-io/xmake/actions/runs/395370331

等ci跑完后下载

**Comment by dsp2000** [comment]
![Uploading 1%71E3H40RVP9E)T@~MY]`X.png…]()

**Comment by waruqi** [comment]
看不到图

**Comment by dsp2000** [comment]
D:\pAndroid\multimedia\app\jni\lame-3.100>xmake update -s dev
update version dev from official source ..
  => downloading https://gitee.com/tboox/xmake.git .. (1/git) (1/git) (1/git) 7
(1/git) (1/git) (1/git) (1/git) (1/git) (1/git) (1/git) (1/git) (1/git) 7⠙8[K
  => download https://gitee.com/tboox/xmake.git .. ok
  => install script to D:\Program Files (x86)\xmake .. ok

D:\pAndroid\multimedia\app\jni\lame-3.100>xmake --version
xmake v2.3.9+202012020507, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|

                         by ruki, xmake.io

    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor


D:\pAndroid\multimedia\app\jni\lame-3.100>xmake --version
xmake v2.3.9+202012020507, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|

                         by ruki, xmake.io

    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor


D:\pAndroid\multimedia\app\jni\lame-3.100>xmake f -p android --ndk=E:\Android\sd
k\ndk\21.0.6113669 -a armeabi-v7a --trybuild=autotools --cxflags="-fPIC"
checking for Android SDK directory ... E:\Android\sdk
checking for Build Tools Version of Android SDK ... 29.0.3
checking for NDK directory ... E:\Android\sdk\ndk\21.0.6113669
checking for SDK version of NDK ... 21
checking for toolchains version of NDK ... 4.9

D:\pAndroid\multimedia\app\jni\lame-3.100>xmake
note: xmake.lua not found, try generating it (pass -y or --confirm=y/n/d to skip
 confirm)?
please input: n (y/n)
y
xmake.lua not found, scanning files ..
error: project not found!

D:\pAndroid\multimedia\app\jni\lame-3.100>

**Comment by waruqi** [comment]
xmake f 时候追加下 -c

**Comment by dsp2000** [comment]
D:\pAndroid\multimedia\app\jni\lame-3.100>
D:\pAndroid\multimedia\app\jni\lame-3.100>xmake f -c -p android --ndk=E:\Android
\sdk\ndk\21.0.6113669 -a armeabi-v7a --trybuild=autotools --cxflags="-fPIC"
checking for Android SDK directory ... E:\Android\sdk
checking for Build Tools Version of Android SDK ... 29.0.3
checking for NDK directory ... E:\Android\sdk\ndk\21.0.6113669
checking for SDK version of NDK ... 21
checking for toolchains version of NDK ... 4.9

D:\pAndroid\multimedia\app\jni\lame-3.100>xmake
note: xmake.lua not found, try generating it (pass -y or --confirm=y/n/d to skip
 confirm)?
please input: n (y/n)
y
xmake.lua not found, scanning files ..
error: project not found!

D:\pAndroid\multimedia\app\jni\lame-3.100>

**Comment by waruqi** [comment]
我这里可以，不行的话，那就先别用 xmake 的 trybuild 模式，自己手动研究下 autoconf ，传入 -fPIC 进行编译就行了

```console
$ xmake f -p android --ndk=~/files/android-ndk-r20b/ --trybuild=autotools -c; xmake 
checking for architecture ... armeabi-v7a
checking for Android SDK directory ... ~/Library/Android/sdk
checking for Build Tools Version of Android SDK ... 30.0.2
checking for NDK directory ... /Users/ruki/files/android-ndk-r20b
checking for SDK version of NDK ... 21
checking for toolchains version of NDK ... 4.9
checking build system type... x86_64-apple-darwin19.6.0
checking host system type... arm-unknown-linux-androideabi
checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for arm-linux-androideabi-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for style of include used by make... GNU
checking for arm-linux-androideabi-gcc... /Users/ruki/files/android-ndk-r20b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /Users/ruki/files/android-ndk-r20b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang accepts -g... yes
checking for /Users/ruki/files/android-ndk-r20b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang option to accept ISO C89... none needed
checking whether /Users/ruki/files/android-ndk-r20b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang understands -c and -o together... yes
checking dependency style of /Users/ruki/files/android-ndk-r20b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang... gcc3
checking how to run the C preprocessor... /Users/ruki/files/android-ndk-r20b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -E
checking for grep that handles long lines and -e... /usr/local/bin/ggrep
checking for egrep... /usr/local/bin/ggrep -E
checking for ANSI C header files... no
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
```

**Comment by dsp2000** [comment]
你是在windows的命令行窗口吗？
我的是windows的命令行窗口，在而且没有安装autoscan aclocal autoconf autoheader automake 这些的
有关系的吗？
还是windows只能在MSYS之类的linux环境xmake才可以？

**Comment by waruqi** [comment]
你还是没理解清楚关系，第三方的库编译 liblame 这种，都是有他们自己的构建系统 比如 autoconf cmake。。。

除非你是源码移植到 xmake.lua 直接用 xmake来编译，不依赖 autoconf ，那么什么环境依赖都没有，你可以不用 msys，直接cmd下就可以用 xmake 编译。。

而你现在是在直接用 autoconf 编译 liblame ，这跟 xmake 没有任何关系，是否不依赖msys 还是只能linux，是 autoconf 自身是否支持决定的，至于autoconf如何使用，你应该去 autoconf 的 issues获取 其他地方问，或者自己 google 下 也可以到 stackoverflow上问。

刚刚说的 xmake 的 trybuild 模式（这只是一个辅助特性而已），只是 xmake 为了方便一些不会用 autoconf 的用户，简化编译过程，内部实际还是调用 autoconf 命令，自动传递的参数进去，其是否支持哪些环境，也是 autoconf 自身决定的，跟 xmake 没啥关系，要是trybuild用不了，那就用不了了，这块原本我就是随手支持的。

**Comment by dsp2000** [comment]
我明白上面的关系的，我只是说如果没有安装 autoconf，xmake 的 trybuild 模式 能不能使用？

" xmake 为了方便一些不会用 autoconf 的用户" 这个超级赞啊，如果能用，真的是程序员的大幸啊

现在用 xmake 编译 安卓简直是太好了。太方便了！！

强烈建议完全支持 xmake 的 trybuild 模式！

**Comment by dsp2000** [comment]
升级到xmake后，360 整天说有木马。信任后，原来能编译的项目现在都编译通不过了
build\.objs\KcCore\android\arm64-v8a\release\src\ffmpeg_filter.c.o: In function
`configure_filtergraph':
ffmpeg_filter.c:(.text+0x11e0): undefined reference to `avfilter_graph_alloc'
ffmpeg_filter.c:(.text+0x1268): undefined reference to `av_strdup'
ffmpeg_filter.c:(.text+0x12b4): undefined reference to `av_opt_set'
ffmpeg_filter.c:(.text+0x12dc): undefined reference to `av_dict_get'
ffmpeg_filter.c:(.text+0x1310): undefined reference to `av_dict_get'
ffmpeg_filter.c:(.text+0x133c): undefined reference to `avfilter_graph_parse2'
ffmpeg_filter.c:(.text+0x13b4): undefined reference to `avfilter_pad_get_type'
ffmpeg_filter.c:(.text+0x13cc): undefined reference to `avfilter_get_by_name'
ffmpeg_filter.c:(.text+0x140c): undefined reference to `avfilter_get_by_name'
ffmpeg_filter.c:(.text+0x144c): undefined reference to `av_bprint_init'
ffmpeg_filter.c:(.text+0x1458): undefined reference to `av_get_sample_fmt_name'
ffmpeg_filter.c:(.text+0x1478): undefined reference to `av_bprintf'
ffmpeg_filter.c:(.text+0x1490): undefined reference to `av_bprintf'
ffmpeg_filter.c:(.text+0x14a4): undefined reference to `av_log'
ffmpeg_filter.c:(.text+0x14cc): undefined reference to `av_buffersrc_parameters_
alloc'
ffmpeg_filter.c:(.text+0x1508): undefined reference to `av_log'

好像是库没有找到

add_rules("mode.debug", "mode.release")
target("KcCore")
set_kind("shared")
set_languages("c99", "cxx11")
set_warnings("all")
add_includedirs("include", "ffmpeg", "include/lame")
add_linkdirs("libs/$(arch)")
add_files("src/main.cpp", "src/soundkey.cpp")
add_files("src/ffmpeg.c", "src/cmdutils.c", "src/ffmpeg_opt.c", "src/ffmpeg_filter.c", "src/ffmpeg_hw.c", "src/bridge.c")

add_links("avformat", "swscale", "swresample", "avfilter", "postproc", "avcodec", "avutil");
add_links("mp3lame", "x264", "fdk-aac");
add_syslinks("log", "z")
add_shflags("-Wl,--no-undefined")

**Comment by dsp2000** [comment]
add_linkdirs("libs/$(arch)")
add_links("avformat", "swscale", "swresample", "avfilter", "postproc", "avcodec", "avutil");
add_links("mp3lame", "x264", "fdk-aac");

libs\arm64-v8a\*.a 文件都是存在的

没有更新xmake之前是可以用的

**Comment by dsp2000** [comment]
![Q`_)A{{X_M 8(THLXIYXG57](https://user-images.githubusercontent.com/54521555/100851581-5e932980-34c0-11eb-96f3-4624fa1f85f8.png)
![1%71E3H40RVP9E)T@~MY `X](https://user-images.githubusercontent.com/54521555/100851626-6bb01880-34c0-11eb-8cf7-5c28572e2b2a.png)

**Comment by dsp2000** [comment]
![Q`_)A{{X_M 8(THLXIYXG57](https://user-images.githubusercontent.com/54521555/100851692-7f5b7f00-34c0-11eb-9e08-465c20743cbb.png)

**Comment by dsp2000** [comment]
[Uploading xmake-latest.win64.exe.zip…]()

**Comment by waruqi** [comment]
> 我明白上面的关系的，我只是说如果没有安装 autoconf，xmake 的 trybuild 模式 能不能使用？

我这边测试可以用，至于你这为什么不行，不清楚，得调了才知道

> 升级到xmake后，360 整天说有木马。信任后，原来能编译的项目现在都编译通不过了

贴下完整 link 命令

至于木马那个，我也没辙，得360过白，否则经常被360搞也是正常的事情，这种我无能为力。

**Comment by dsp2000** [comment]
xmake f -p android --ndk=E:\Android\sdk\ndk\21.0.6113669 -a armeabi-v7a --ndk_sdkver=16

add_rules("mode.debug", "mode.release")
target("KcCore")
set_kind("shared")
set_languages("c99", "cxx11")
set_warnings("all")
add_includedirs("include", "ffmpeg", "include/lame")
add_linkdirs("libs/$(arch)")
add_files("src/main.cpp", "src/soundkey.cpp")
add_files("src/ffmpeg.c", "src/cmdutils.c", "src/ffmpeg_opt.c", "src/ffmpeg_filter.c", "src/ffmpeg_hw.c", "src/bridge.c")

add_links("avformat", "swscale", "swresample", "avfilter", "postproc", "avcodec", "avutil");
add_links("mp3lame", "x264", "fdk-aac");
add_syslinks("log", "z")
add_shflags("-Wl,--no-undefined")

所有的*.a都找不到了

**Comment by waruqi** [comment]
> 贴下完整 link 命令

给我下，不然我怎么知道怎么回事，xmake -vD

**Comment by dsp2000** [comment]
我刚才 找到之前的 xmake-v2.3.4.win64.zip 解压可以编译了
请问对应2.3.9的zip 在哪里可以下载？ 找了 https://github.com/xmake-io/xmake/ 好像没有

**Comment by waruqi** [comment]
> 我刚才 找到之前的 xmake-v2.3.4.win64.zip 解压可以编译了
> 请问对应2.3.9的zip 在哪里可以下载？ 找了 https://github.com/xmake-io/xmake/ 好像没有

github releases 或者刚的ci下

**Comment by dsp2000** [comment]
解压的2.3.9完全正常的。360也没有找麻烦。
上面的问题
如果windows没有安装 autoconf，  直接运行   xmake 的 trybuild 模式 能不能使用？例如你直接调用autoconf.exe当然会不正常的。

**Comment by waruqi** [comment]
autotools依赖了一系列工具，automake aclocal bash m4 ... 你没msys/cygwin 根本跑不起来

之前我说了 xmake trybuild 依赖 autotools自身的支持力度，你应该了解下 autotools 哪些环境可以使用，而不是 xmake trybuild

**Comment by dsp2000** [comment]
1、在windows直接用autotools一系列工具应该是不可能的了吧？
2、我安装有的msys的，但下载不了xmake。

继续看看怎样解决之中

**Comment by waruqi** [comment]
> 1、在windows直接用autotools一系列工具应该是不可能的了吧？

你可以在msys里面用，但是工具得装全，估计也得折腾一会了

> 2、我安装有的msys的，但下载不了xmake。
> 
> 继续看看怎样解决之中

你直接用windows安装包装的xmake，msys里面也是可以直接用的 不一定要走 pacman装

而且你现在只是为了用autotools编译 blame 带上fpic，那可以不用xmake trybuild，直接折腾autotools就行了

**Comment by dsp2000** [comment]
我的目的不是针对liblame的， 而是用xmake跨平台编译太爽了，之前想编译一些开源的项目，次次碰到一堆问题。如果xmake可以用，又自动处理掉这些问题，那就太好了。

在windows上面如果直接可以用，就更爽了。

**Comment by waruqi** [comment]
windows上原本就可以用 直接下载release安装包就行了

https://github.com/xmake-io/xmake/releases/download/v2.3.9/xmake-v2.3.9.win64.exe

如果是在msys里面，通过export 添加下对应的path就好

**Comment by dsp2000** [comment]
xmake现在我就是直接用windows的，交叉编译太方便了，现在就除了xmake trybuild 没有可以用而已

**Comment by waruqi** [comment]
> xmake现在我就是直接用windows的，交叉编译太方便了，现在就除了xmake trybuild 没有可以用而已

trybuild 理论上也是可以的，我这边macos测试都 ok，如果是用的 后来 dev 上的最近提交，按理你这应该也可以，如果不行 只能等之后有时间再调试了，我暂时没有 msys 环境

**Comment by waruqi** [comment]
> 升级到xmake后，360 整天说有木马。信任后，原来能编译的项目现在都编译通不过了

这个也许跟后来的改动导致，我回头会看下这个问题，相关问题：https://github.com/xmake-io/xmake/issues/1108

**Comment by dsp2000** [comment]
好的

**Comment by waruqi** [comment]
> > 升级到xmake后，360 整天说有木马。信任后，原来能编译的项目现在都编译通不过了
> 
> 这个也许跟后来的改动导致，我回头会看下这个问题，相关问题：#1108

这个问题 我修复了，等 ci 跑完，可以到上面下载包重装下 https://github.com/xmake-io/xmake/actions/runs/398478942

**Comment by dsp2000** [comment]
下载，测试问题已经修复了，暂时这里就可以了，后面再折腾autotools，多谢了
