### ISSUE TITLE
使用sdcc工具链，加 --Werror编译参数会导致所有编译参数不生效

### ISSUE THREAD

**Issue by knightjun** [xmake-io/xmake#1102]
### 描述问题
当使用这个编译参数时，编译参数正常传递
add_cxflags("--model-large --opt-code-size")
`D:\SDCC\bin\sdcc -c -mmcs51 -I. -DSWITCH_AI1010BT -ID:\SDCC\include --model-large --opt-code-size -DUSE_FLOATS=1 -o build\.objs\ai1010bt\cross\mcs51\release\main.c.rel main.c`
而加上--Werror之后
add_cxflags("--model-large --opt-code-size --Werror")
`D:\SDCC\bin\sdcc -c -mmcs51 -I. -DSWITCH_AI1010BT -ID:\SDCC\include -DUSE_FLOATS=1 -o build\.objs\ai1010bt\cross\mcs51\release\main.c.rel main.c`
整一行的编译参数都没有生效

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：xmake v2.3.8+202010172345,
- xmake运行平台：window7
- xmake目标平台：51单片机

### 其他信息
sdcc工具链

**Comment by waruqi** [comment]
首先有几个地方不对，

1. 每个flags独立分开加，`add_cxflags("--model-large", "--opt-code-size", "--Werror")`

2. xmake 默认开启了自动检测flags机制，会去走尝试编译，如果某个flags不支持就会自动忽略，而你这里 加上 `-Werror` 有可能触发了编译错误，所以给自动忽略了，然后你又是跟其他flags放在一个 string ，那就全部忽略了。（其实是有警告提示你的，不知道为啥你没看到）

解决方案：
   - 添加 force = true，强制通过不检测，`add_cxflags("--model-large", "--opt-code-size", "--Werror", {force = true})`
   - 或者设置 `set_policy("check.auto_ignore_flags", false)` 全局禁用flags自动检测机制，见 https://xmake.io/#/zh-cn/manual/project_target?id=targetset_policy

**Comment by knightjun** [comment]
分开加的话前面两个参数加上去了，也出现了警告
“warning: add_cxflags("--Werror") is ignored, please pass `{force = true}` or call `set_policy("check.auto_ignore_flags", false)` if you want
to set it.”
我这边的问题解决了，不过sdcc是支持--Werror（我用的是4.0，不知道其他版本支不支持），我觉得这个警告应该去掉

**Comment by waruqi** [comment]
> 分开加的话前面两个参数加上去了，也出现了警告
“warning: add_cxflags("--Werror") is ignored, please pass {force = true} or call set_policy("check.auto_ignore_flags", false) if you want
to set it.”

对啊，我刚不是说了么，你这个flags 会检测失败，原本就是会有警告提示你怎么处理，按理你不提issues 也应该知道怎么解决，警告里都给你写明白了怎么做。

> 我这边的问题解决了，不过sdcc是支持--Werror（我用的是4.0，不知道其他版本支不支持），我觉得这个警告应该去掉

你怎么就不明白我刚说的呢。
