### ISSUE TITLE
如何在mingw32里面下载及使用xmake ?

### ISSUE THREAD

**Issue by dsp2000** [xmake-io/xmake#1103]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
请在这描述你需要讨论的话题详情。

如何在mingw32里面下载及使用xmake ?

mingw32
pacman -Sy mingw-w64-i686-xmake

# pacman -Sy mingw-w64-i686-xmake
:: 正在同步软件包数据库...
 mingw32                  740.8 KiB  11.8K/s 01:03 [#####################] 100%
 mingw32.sig              438.0   B  0.00B/s 00:00 [#####################] 100%
错误：mingw32: 密钥 "4A6129F4E4B84AE46ED7F635628F528CF3053E04" 未知
错误：无法远程查找到密钥 "4A6129F4E4B84AE46ED7F635628F528CF3053E04"
错误：无法升级 mingw32 (无效或已损坏的数据库 (PGP 签名))
 mingw64                  742.5 KiB  12.6K/s 00:59 [#####################] 100%
 mingw64.sig              438.0   B  0.00B/s 00:00 [#####################] 100%
错误：mingw64: 密钥 "4A6129F4E4B84AE46ED7F635628F528CF3053E04" 未知
错误：无法远程查找到密钥 "4A6129F4E4B84AE46ED7F635628F528CF3053E04"
错误：无法升级 mingw64 (无效或已损坏的数据库 (PGP 签名))
 msys                     184.5 KiB  17.2K/s 00:11 [#####################] 100%
 msys.sig                 119.0   B  0.00B/s 00:00 [#####################] 100%
错误：同步所有数据库失败

**Comment by waruqi** [comment]
不要遇到什么错误都贴过来哈，这明显是msys/pacman的问题 跟xmake又没啥关系 你得到msys/mingw那边去问

**Comment by waruqi** [comment]
这块你自己研究 mingw/pacman的环境配置，或者可以直接拉取源码编译安装，也可以直接安装 windows 原生版本，只要 msys 里面 设置上 path ，里面也可以直接使用的，没啥区别
