### ISSUE TITLE
How do I specify public packages?

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1104]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情

```lua
add_requires("x")
target("a")
	set_kind("static")
	add_packages("x")
	add_files(...)
target("b")
	set_kind("binary")
	add_deps("a")
	add_files(...)
```

如图，a依赖x，b依赖a（间接依赖x），有没有办法声明x为public这样所有依赖a的库自动依赖x

**Comment by waruqi** [comment]
links 和 linkdirs 现在似乎就是 自动依赖上的，不过这块没具体弄过，支持程度怎样 还是未知，回头有时间可以改进，不过 3.5.1 上不一定有时间弄了， 最近issues排满了，等下个版本吧，我会考虑改进下

**Comment by HeBomou** [comment]
glm不能被自动依赖，这个库只有头文件

问题复现
类库LibA依赖glm，类库LibB依赖LibA，LibA中的某个头文件LibA.h包含了glm的头文件
如果LibB包含LibA.h就会出问题

**Comment by waruqi** [comment]
> glm不能被自动依赖，这个库只有头文件
> 
> 问题复现
> 类库LibA依赖glm，类库LibB依赖LibA，LibA中的某个头文件LibA.h包含了glm的头文件
> 如果LibB包含LibA.h就会出问题

不同的问题，请另外开 issues，同时提供 xmake.lua 以及 xmake -vD 信息，或者可复现 example

**Comment by waruqi** [comment]
我 dev 上已经支持了，默认 add_packages 会自动导出 links/linkdirs，设置上 {public = true} 会导出所有，包括 includedirs

具体用法见：https://github.com/xmake-io/xmake/issues/1254
