### ISSUE TITLE
Language standards not set in vsxmake project settings

### ISSUE THREAD

**Issue by paul-reilly** [xmake-io/xmake#1105]
I noticed Intellisense errors in a vsxmake project I opened.

It turns out that the language standard set with `set_languages()` is not being set in the generated VS project.

Specifically, I set `set_languages("c++17")` and the VS 2019 project still has C++14.

**Comment by waruqi** [comment]
Ok, I will look at it.

**Comment by waruqi** [comment]
I have supported it on dev branch, you can try it again.
