### ISSUE TITLE
How do I add module definition file to a shared library on windows?

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1106]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
Windows上创建dll有两种方法，一种是在每个函数前面加__declspec(dllexport)，另一种是使用.def文件（module definition file） [module definition .def files](https://docs.microsoft.com/en-us/cpp/build/reference/module-definition-dot-def-files?view=msvc-160#:~:text=Module-definition%20%28.def%29%20files%20provide%20the%20linker%20with%20information,file%20is%20most%20useful%20when%20building%20a%20DLL.)。如何在xmake中声明.def文件？

**Comment by waruqi** [comment]
见：https://github.com/xmake-io/xmake/issues/153

**Comment by xq114** [comment]
> 见：#153

谢谢

**Comment by waruqi** [comment]
现在dev上可以直接添加def文件了 `add_files("module.def")`
