### ISSUE TITLE
attempt to index global 'process' (a nil value)

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1107]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

```lua
local proc = process.open("echo hello xmake!", {outpath = "", errpath = ""})
```

执行结果：
![image](https://user-images.githubusercontent.com/42310255/100974221-e2a7e880-3576-11eb-9daf-ddc8401070f5.png)

### 期待的结果

新建一个进程

### 错误信息

error: @programdir\core\project\project.lua:1028: .\xmake.lua:5: attempt to index global 'process' (a nil value)
stack traceback:
    [.\xmake.lua:5]: in main chunk

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:789: in function 'raise'
        @programdir\core\project\project.lua:1028: in function 'tasks'
        @programdir\core\project\project.lua:1017: in function 'task'
        @programdir\core\main.lua:275: in function <@programdir\core\main.lua:219>

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.3.9
- xmake运行平台：windows
- xmake目标平台：windows

### 其他信息

请提供其他附加信息帮助我们诊断问题(比如截图，xmake.lua或者可复现的demo)，以及你遇到的问题的一些背景信息。

**Comment by waruqi** [comment]
这个不常用，所以我现在默认不导出了，你需要 import("core.base.process")，通常只需要 os.exec/os.run 就可以了

**Comment by xq114** [comment]
好的，感觉文档很多地方需要修改了
