### ISSUE TITLE
经验：如何新建Qt的widget程序

### ISSUE THREAD

**Issue by duohappy** [xmake-io/xmake#1112]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
Qt编程中，新建Qt Widgets Application，有3个选择：mainwindow， widget，qdialog。我经常使用的是widget，且不习惯用ui文件

官方关于Qt Widget教程：[点击这里](https://xmake.io/#/zh-cn/guide/project_examples?id=widgets%e5%ba%94%e7%94%a8%e7%a8%8b%e5%ba%8f)

xmake版本：2.3.9
Qt：5.12.6

``` bash
cd ~
xmake create -t qt.widgetapp testQtWidget
```
默认新建的时mainwindow，目录结果如下：
``` html
.
├── src
│   ├── main.cpp
│   ├── mainwindow.cpp
│   ├── mainwindow.h
│   └── mainwindow.ui
└── xmake.lua
```

默认的xmake.lua，和官方教程有一点点差异了，可能是同步更新的问题
``` lua
add_rules("mode.debug", "mode.release")

target("test")
    add_rules("qt.widgetapp")
    add_headerfiles("src/*.h")
    add_files("src/*.cpp")
    add_files("src/mainwindow.ui")
    -- add files with Q_OBJECT meta (only for qt.moc)
    add_files("src/mainwindow.h")
```

### 修改为widget项目

``` bash
rm src/*
cd src
touch widget.h widget.cpp main.cpp
```

main.cpp
``` c++
#include "widget.h"

#include <QApplication>

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    Widget w;
    w.show();
    return a.exec();
}
```

widget.h
``` c++
#ifndef WIDGET_H
#define WIDGET_H

#include <QWidget>

class Widget : public QWidget
{
    Q_OBJECT

public:
    Widget(QWidget *parent = nullptr);
    ~Widget();
};
#endif // WIDGET_H
```

widget.cpp
``` c++
#include "widget.h"

Widget::Widget(QWidget *parent)
    : QWidget(parent)
{
}

Widget::~Widget()
{
}
```

### 修改xmake.lua

``` lua
add_rules("mode.debug", "mode.release")

target("test")
    add_rules("qt.widgetapp")
    add_headerfiles("src/*.h")
    add_files("src/*.cpp")
    -- add files with Q_OBJECT meta (only for qt.moc)
    add_files("src/widget.h")
```

说实话，我当初还不理解为什么要加上注释`-- add files with Q_OBJECT meta (only for qt.moc)`，而且在后面还加上`add_files("src/widget.h")`，因为`add_headerfiles("src/*.h")`不是加上了所有的头文件么。

**其实意思是：如果源文件中有 `Q_OBJECT`，必须用add_files添加它，如`add_files("src/widget.h")`**
因为我不用ui文件，所以把ui那句话给删除了。

感谢xmake，很好用，:)

**Comment by waruqi** [comment]
> 默认的xmake.lua，和官方教程有一点点差异了，可能是同步更新的问题

版本更新多少会有些变动，这没啥关系，你只要根据 xmake create 命令创建就行了，创建的空工程仅供参考，如果不满足自己的项目需求，自己稍微改改就好了。

> 其实意思是：如果源文件中有 Q_OBJECT，必须用add_files添加它，如add_files("src/widget.h")

是的

> 因为我不用ui文件，所以把ui那句话给删除了。

这个你随意
