### ISSUE TITLE
A command line parser problem of xmake

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#1113]
Okay, well I ran into a little bug. If I leave a trailing slash when specifying the mingw directory, the end quote gets captured in the string (path).

```
C:\temp\lua-c-test> xmake --version
xmake v2.3.9+202011302258, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, xmake.io

    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor

C:\temp\lua-c-test> xmake f -a i386 -p mingw
checking for mingw directory ... no
please run:
    - xmake config --mingw=xxx
or  - xmake global --mingw=xxx
C:\temp\lua-c-test> xmake global --mingw="C:\Program Files (x86)\WinLua\WLC\"
configure
{
    theme = default
    mingw = C:\Program Files (x86)\WinLua\WLC"  <----------------------------------------- quote is left in the string.
    network = public
    proxy_pac = pac.lua
}
C:\temp\lua-c-test> xmake f -a i386 -p mingw
checking for mingw directory ... no
please run:
    - xmake config --mingw=xxx
or  - xmake global --mingw=xxx
C:\temp\lua-c-test> xmake f -c -vD -a i386 -p mingw
checking for mingw directory ... no
please run:
    - xmake config --mingw=xxx
or  - xmake global --mingw=xxx
error: @programdir\core\main.lua:284: @programdir\core\tool\toolchain.lua:205: stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:800]: in function 'raise'
    [@programdir\toolchains\mingw\check.lua:37]:
    [C]: in function 'load'
    [@programdir\core\tool\toolchain.lua:201]: in function 'check'
    [@programdir\core\platform\platform.lua:287]: in function 'check'
    [...mdir\core\sandbox\modules\import\core\project\config.lua:120]: in function 'check'
    [@programdir\actions\config\main.lua:274]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:520]: in function 'run'
    [@programdir\core\main.lua:282]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:789: in function 'raise'
        @programdir\core\main.lua:284: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>
C:\temp\lua-c-test>
```

Removing the trailing slash fixed the issue:

```
C:\temp\lua-c-test> xmake global --mingw="C:\Program Files (x86)\WinLua\WLC"
configure
{
    mingw = C:\Program Files (x86)\WinLua\WLC
    theme = default
    network = public
    proxy_pac = pac.lua
}
C:\temp\lua-c-test> xmake f -c -vD -a i386 -p mingw
checking for mingw directory ... C:\Program Files (x86)\WinLua\WLC
configure
{
    clean = true
    kind = static
    ndk_stdcxx = true
    mode = release
    cross = i686-w64-mingw32-
    arch = i386
    proxy_pac = pac.lua
    mingw = C:\Program Files (x86)\WinLua\WLC
    theme = default
    plat = mingw
    ccache = true
    network = public
    buildir = build
    host = windows
    bin = C:\Program Files (x86)\WinLua\WLC\bin
}
```

I was able to build successfully on the master branch after that. The complete output is here: https://pastebin.com/4PsFu51y

Good Night!

_Originally posted by @RussellHaley in https://github.com/tboox/tbox/issues/157#issuecomment-738601753_

**Comment by augustheart** [comment]
我的问题可能也是类似的？
刚刚用xmake，还不熟。
直接从issue和教程中复制（并修改）的shell命令执行异常
add_cxflags("$(shell wx-config --cppflags)")
`target("wxtools")
    -- set kind
    set_kind("binary")
    --add_rules("wx")
    add_cxflags("$(shell wx-config --cppflags)")
    --add_files("sqlite3.c")
    add_files("luafunction.cpp")`
结果就是`$ xmake
checking for architecture ... x86_64
checking for mingw directory ... C:/Work/msys2/mingw64
`
直接就结束了，没有任何下文
更详细的
`$ xmake -b -v -D
checking for architecture ... x86_64
checking for mingw directory ... C:/Work/msys2/mingw64
error: @programdir\core\main.lua:284: @programdir\core\sandbox\modules\import\core\base\task.lua:65: stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:800]: in function 'raise'
    [@programdir\core\project\project.lua:908]: in function 'targets'
    [@programdir\actions\config\main.lua:128]: in function '_check_target'
    [@programdir\actions\config\main.lua:302]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:520]: in function 'run'
    [@programdir\core\sandbox\modules\import\core\base\task.lua:63]: in function 'run'
    [@programdir\actions\build\main.lua:100]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:520]: in function 'run'
    [@programdir\core\main.lua:282]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:789: in function 'raise'
        @programdir\core\main.lua:284: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>

`
环境为最新的msys2，mingw32和mingw64下都是如此

**Comment by waruqi** [comment]
> 我的问题可能也是类似的？

不是同一个问题，请新开issues，另外 code 格式改下，很乱 根本没法看。

**Comment by waruqi** [comment]
> C:\temp\lua-c-test> xmake global --mingw="C:\Program Files (x86)\WinLua\WLC\"
> configure
> {
>     theme = default
>     mingw = C:\Program Files (x86)\WinLua\WLC"  <----------------------------------------- quote is left in the string.
>     network = public
>     proxy_pac = pac.lua
> }

This is invalid input, you should pass `\\` instead of `\` in double quotes. Otherwise, the value of argv[i] taken from `main(, char** argv)` is wrong.

`argv[2]` -> `--mingw=C:\Program Files (x86)\WinLua\WLC\"` <- incorrect.

correct input:

```console
xmake global --mingw="C:\\Program Files (x86)\\WinLua\\WLC\\"
```

@RussellHaley

**Comment by RussellHaley** [comment]
Yes, it's very awkward going from raw strings on the command line to Lua string.  I was wondering what your solution was going to be. 👍

**Comment by waruqi** [comment]
> Yes, it's very awkward going from raw strings on the command line to Lua string. I was wondering what your solution was going to be. 👍

This has nothing to do with Lua. The argv list I get from the main function is incorrect. I cannot make any changes unless the user passes the correct input.

**Comment by RussellHaley** [comment]
>  I cannot make any changes unless the user passes the correct input.

Corect imput? Form me? Impossibl! (he he)

I hadn't noticed before because I typically use forward slash / in Windows. Forward slash is accepted just fine in Powershell (and CMD from what I can tell). I only started using backslash \ because I was writing examples on the LuaForums. I shall stop using backslash in my examples I suppose.

**Comment by waruqi** [comment]
> I only started using backslash \ because I was writing examples on the LuaForums.

If you are using a backslash in double quotes, you need to escape it. for example

```console
$ ./shell "c:\\xxx\\xxx\\"     <- correct
$ ./shell "c:\xxx\xxx\"        <- incorrect, we cannot get correct argv[] list values from `int main(int argc, char** argv)`
$ ./shell c:\xxx\xxx\           <- correct
```

> $ ./shell "c:\xxx\xxx\"        <- incorrect, we cannot get correct argv[] list values from `int main(int argc, char** argv)`

You can write a simple test program to test it.

```c
int main (int argc, char** argv)
{
    printf("argv[1]: %s\n", argv[1]);
    return 0;
}
```
