### ISSUE TITLE
use system python (or user installed python) if a package requires binary python

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1115]
### 你在什么场景下需要该功能？

目前只有find_tool("python")没有find_package("python")，导致安装一些依赖python binary的包的时候会直接忽略系统python（例如Debian-based系统）和用户安装的python去自己安装，拖慢了安装的总时间

### 描述可能的解决方案

1.如果一个包被depend的时候是binary的，那么同时考虑走find_tool和find_package

优点：普适 缺点：需要判断binary名称，例如python版本(python2/python3)，windows上的python launcher等

2.额外弄一个python-lib包，需要引用lib的添加dep到python-lib，然后复制现有find_python到package下支持find_package(python)

优点：不太麻烦 缺点：breaking change，破坏前向兼容性

3.把repo里面对python的依赖都改成find_tool然后失败再加add_deps

优点：肯定可行，并且最灵活 缺点：麻烦，如下

```lua
        import("lib.detect.find_tool")
        local python = find_tool("python")
        if python.program then
            package:addenv("PATH", python.program) -- is it correct?
        else
            package:add("deps", "python 3.x", {kind = "binary"})
        end
```

**Comment by xq114** [comment]
还有一种办法保持兼容性，加一个python3包处理binary情况
```lua
package("python3")

    set_homepage("https://www.python.org/")
    set_description("The python programming language.")

    on_load(function (package)
        import("package.tools.find_tool")
        if is_host("windows") then
            py = find_tool("py")
            if not py.program then
                package:add("deps", "python 3.x", {kind = "binary"})
                return
            end
            package:addenv("PATH", py.program)
        end
        python3 = find_tool("python3")
        if python3.program then
            package:addenv("PATH", python3.program)
            return
        else
            package:add("deps", "python 3.x", {kind = "binary"})
        end
    end)

    on_test(function (package)
        os.vrun()
    end)
```
不过需要xmake的find_tool支持py(python launcher)、python3

**Comment by waruqi** [comment]
> 目前只有find_tool("python")没有find_package("python")，导致安装一些依赖python binary的包的时候会直接忽略系统python（例如Debian-based系统）和用户安装的python去自己安装，拖慢了安装的总时间

只有 find_tool，那应该能找到系统 python --version，为什么还会自己重装呢？有没有复现example?

**Comment by xq114** [comment]
发现linux上是另一个依赖包间接依赖python的时候没写binary导致的。但windows上的python有另外两个问题：

1. windows上find_python.lua好像只写了3.6和3.7？
2. windows上anaconda装的python不带py launcher，这个有没有特别处理

不过之前在windows上走xmake-repo装python也很快，所以之前没特别提这个问题

**Comment by waruqi** [comment]
> 发现linux上是另一个依赖包间接依赖python的时候没写binary导致的。

哪个？我回头看下

> 但windows上的python有另外两个问题：
> 
> 1. windows上find_python.lua好像只写了3.6和3.7？

这个我回头改下

> 2. windows上anaconda装的python不带py launcher，这个有没有特别处理
> 
> 不过之前在windows上走xmake-repo装python也很快，所以之前没特别提这个问题

我觉得pyenv应该独立成一个包比较好

**Comment by waruqi** [comment]
现在有了 add_extsources / on_fetch，以后包的 查找改进不用在 xmake/modules/detect/package/find_xx 里做了，可以在包定义里面改进。

参考：https://github.com/xmake-io/xmake/issues/1239

**Comment by waruqi** [comment]
另外，python的包我改进过了，zlib/libffi 依赖也能正常适配了，不需要依赖系统库。。https://github.com/xmake-io/xmake-repo/pull/307

这里先这样吧，有其他问题，后续再开 issue
