### ISSUE TITLE
How can I specify find_package for host environment?

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1116]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情

Python在Ubuntu20.04上安装会报错，缺少系统包zlib和libffi（并且只能用系统版本，传入LDFLAGS和CFLAGS无效），因此需要check find_package提示用户用apt安装zlib和libffi；然而在plat为android交叉编译的时候find_package会报错找不到包，加{host=true}也不行。

```lua
    -- check system libs
    if is_host("linux") then
        for link, lib in pairs({z = "zlib", ffi = "libffi"}) do
            assert(find_package("system::" .. link, {host = true}), ("%s-dev not found, please use your system package manager to install it."):format(lib))
        end
    end
```

**Comment by waruqi** [comment]
直接传 plat = os.host(), arch = os.arch() 呢

**Comment by xq114** [comment]
可以了
