### ISSUE TITLE
Questions about options

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1119]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
1. 如何查看当前项目所有options的当前配置？
2. 如何在option中设置c++ standard？（option没有set_languages选项）
3. 如何在option中设置可选的第三方包？（option也没有add_packages选项）
4. 匿名option如何直接引入到target中？

**Comment by waruqi** [comment]
> 如何查看当前项目所有options的当前配置？

可以用 xmake f --menu看，或者 xmake f -v

> 如何在option中设置c++ standard？（option没有set_languages选项）

有的


> 如何在option中设置可选的第三方包？（option也没有add_packages选项）

暂时不支持，目前也不打算支持


> 匿名option如何直接引入到target中？

option都是有名字的，直接 add_options加到target就好

**Comment by xq114** [comment]
那么如果要根据选项控制使用哪些package该怎么做呢？

**Comment by waruqi** [comment]
> 那么如果要根据选项控制使用哪些package该怎么做呢？

option + has_config + add_packages 

参考tbox里面的配置

**Comment by xq114** [comment]
> option + has_config + add_packages
> 
> 参考tbox里面的配置

好的，谢谢
