### ISSUE TITLE
CPU microarchitecture detection

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1120]
### 你在什么场景下需要该功能？

https://en.wikipedia.org/wiki/List_of_Intel_CPU_microarchitectures

https://en.wikipedia.org/wiki/List_of_AMD_CPU_microarchitectures

要追求性能情况下往往要根据CPU的内存模型和扩展指令集来优化，同时想要跨平台的话，就需要根据当前cpu信息指定对应的代码，（例如intel haswell之后一套，amd zen之后一套，更老的默认到没有优化）。很多高性能计算库里面也会用到这些信息。实际操作要操作系统提供的相关api，例如linux的/proc/cpuinfo，xmake能否简化这个过程，提供一个获取microarchitecture的api？

同时还有一个比起缓存架构更普遍的SSE（Streaming SIMD Extension）模型，sse4/neon/avx2/avx512等，不同cpu对这些sse模型的支持也不一样

### 描述可能的解决方案

os.cpu_arch()

返回："haswell" "skylake" "willowcove" "zen" "zen2" "unknown"等

os.cpu_simd("avx")

返回：true、false

### 其他信息

暂时不急，可以作为一个建议。提出原因是编译一些高性能计算库时发现原来的库只支持linux用Makefile编译（用了cpu优化），想port到xmake来很麻烦

**Comment by waruqi** [comment]
> 同时还有一个比起缓存架构更普遍的SSE（Streaming SIMD Extension）模型，sse4/neon/avx2/avx512等，不同cpu对这些sse模型的支持也不一样


添加扩展指令集有这个配置可以抽象 add_vectorexts，如果编译器不支持就会忽略，不过这个是针对编译器的，不是针对当前os

 https://xmake.io/#/zh-cn/manual/project_target?id=targetadd_vectorexts

> os.cpu_arch()

当前os的这种获取，暂时不考虑支持，因为它只是探测了当前的host上 cpu arch，这种 直接 os.arch 基本够用了，如果确实还要更细粒度抽象获取，你暂时可以先在自己的项目中 封装lua模块接口来直接使用

如果要加入的xmake的内置支持，我暂时没时间搞，不过如果有比较完善的实现，我也接受pr

**Comment by xq114** [comment]
找到一个cmake的实现，linux用的/proc/cpuinfo，macosx用的sysctl，windows用的注册表

https://github.com/tesseract-ocr/tesseract/blob/master/cmake/OptimizeForArchitecture.cmake

应该用lua翻译一下就好了，不过这个有一点点老，还得查文档加上新cpu的支持

**Comment by waruqi** [comment]
暂定2.5.2好了 到时候看情况 有时间的话可以考虑整下

**Comment by waruqi** [comment]
这个等 2.5.3 吧，2.5.2 issues 排满了。暂时忙不过来。

**Comment by waruqi** [comment]
我加上了，https://github.com/xmake-io/xmake/blob/dev/xmake/core/base/cpu.lua

模块：`core.base.cpu`

现在只是翻译了 https://github.com/tesseract-ocr/tesseract/blob/master/cmake/OptimizeForArchitecture.cmake

新的我暂时找不到，intel manual太大，没时间细找。。如果你知道 也可以帮忙补上。。

**Comment by waruqi** [comment]
也可以通过 os.cpuinfo() 快速获取所有信息，这个先这样的吧，回头有时间再改进

**Comment by xq114** [comment]
https://en.wikichip.org/wiki/intel/cpuid

https://en.wikichip.org/wiki/amd/cpuid

当前的获取方式非常好！model和family还可以进行大小比较，比起用字符串表示更好，也更加通用。可以在文档中加这两个链接，有需要的用户根据这两个表去判断当前cpu是否符合要求

**Comment by waruqi** [comment]
加上了，march 我改进过了，wiki上的都加进去了
