### ISSUE TITLE
.def 文件添加错误

### ISSUE THREAD

**Issue by nick908** [xmake-io/xmake#1122]
### 描述问题
找不到 def 文件
**lua.xmake**
add_packagedirs("../packages")

target("Mlog4cxx")
    set_kind("shared")
    add_files("*.cpp")
    add_headerfiles("*.h")
    add_includedirs(".", { public = true })
    add_packages("log4cxx")
    add_shflags("/DEF:exports.def", {force = true})
![image](https://user-images.githubusercontent.com/975674/101301912-2c454b80-3875-11eb-98e7-93b658a6f36a.png)

### 错误信息

D:\Holdtecs\PythonU> xmake -r -vD -w Mlog4cxx
[ 50%]: compiling.release Mlog4cxx\mlog4cxx.cpp
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\cl.exe" -c /EHsc -nologo -IMlog4cxx -Ipackages\log4cxx.pkg\inc -Fobuild\.objs\Mlog4cxx\windows\x64\release\Mlog4cxx\mlog4cxx.cpp.obj Mlog4cxx\mlog4cxx.cpp
[ 75%]: linking.release Mlog4cxx.dll
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\link.exe" -dll -nologo -machine:x64 -libpath:packages\log4cxx.pkg\lib\windows\x64 log4cxx.lib /DEF:exports.def -out:build\windows\x64\release\Mlog4cxx.dll build\.objs\Mlog4cxx\windows\x64\release\Mlog4cxx\mlog4cxx.cpp.obj
error: @programdir\modules\private\async\runjobs.lua:210: @programdir\actions\build\kinds\shared.lua:88: @programdir\modules\core\tools\link.lua:146: LINK : fatal error LNK1104: 无法打开文件“exports.def”

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:789]: in function 'raise'
    [@programdir\modules\core\tools\link.lua:146]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
    [@programdir\modules\core\tools\link.lua:127]:
    [C]: in function 'link'
    [@programdir\actions\build\kinds\shared.lua:88]: in function 'callback'
    [@programdir\modules\core\project\depend.lua:186]: in function 'on_changed'
    [@programdir\actions\build\kinds\shared.lua:54]: in function '_do_link_target'
    [@programdir\actions\build\kinds\shared.lua:109]:
    [@programdir\actions\build\kinds\shared.lua:130]: in function '_link_target'
    [@programdir\actions\build\kinds\shared.lua:152]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:188]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:182]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:789: in function 'raise'
        @programdir\modules\private\async\runjobs.lua:210: in function 'catch'
        @programdir\core\sandbox\modules\try.lua:127: in function 'try'
        @programdir\modules\private\async\runjobs.lua:182: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：xmake v2.3.9+202012061455, A cross-platform build utility based on Lua
- xmake运行平台： vs 2019
- xmake目标平台：windows 10

### 其他信息

请提供其他附加信息帮助我们诊断问题(比如截图，xmake.lua或者可复现的demo)，以及你遇到的问题的一些背景信息。

**Comment by waruqi** [comment]
> "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\link.exe" -dll -nologo -machine:x64 -libpath:packages\log4cxx.pkg\lib\windows\x64 log4cxx.lib /DEF:exports.def -out:build\windows\x64\release\Mlog4cxx.dll build.objs\Mlog4cxx\windows\x64\release\Mlog4cxx\mlog4cxx.cpp.obj

你看下命令行，这个flags已经正确加进去了，没啥问题，至于 exports.def 找不到，那你得自己处理def相对于当前根工程的路径，在 add_ldflags/add_shflags中的都是原始flags，xmake不会自动给你做各种相对路径的处理，你得自己保证添加的文件 能让 link.exe 找到

**Comment by waruqi** [comment]
这个就是 def 的路径问题，自己改下就好

**Comment by waruqi** [comment]
现在dev上可以直接添加def文件了 `add_files("module.def")`

**Comment by nick908** [comment]
好的，谢谢
