### ISSUE TITLE
Android没办法编译libpng的zlib,但是可以单独编译zlib

### ISSUE THREAD

**Issue by ShikinChen** [xmake-io/xmake#1126]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
Android没办法编译libpng的zlib,但是可以单独编译zli,有办法编译libpng时候引用库编译好的zlib

**Comment by waruqi** [comment]
libpng 包的问题，我修复了，你更新下repo后再试试：`xrepo update-repo`

**Comment by waruqi** [comment]
可以了么
