### ISSUE TITLE
本地包option() 下is_mode is_plat无法支持

### ISSUE THREAD

**Issue by nick908** [xmake-io/xmake#1129]
### 描述问题
显示 is_plat nil

**xmake.lua**
option("libusb")

    -- 设置是否在xmake f -h配置菜单中显示
    -- 如果你想让你的包在工程项目中，可以提示用户手动禁用，那么就启用他吧
    set_showmenu(true)

    -- 在xmake f -h中显示相关描述信息
    set_description("The libusb package")

    -- 如果检测通过，定义宏开关到config.h
    --add_defines_h_if_ok("$(prefix)_PACKAGE_HAVE_CYUSB")

    -- 检测链接
    add_links("libusb-1.0")

    -- 添加检测的链接库目录，这里设置优先检测zlib.pkg/lib/下相关平台是否存在链接库，然后再去检测系统的
    -- 如果这个不去设置，xmake只能检测一些系统目录下的链接库，例如：/usr/lib, /usr/local/lib
    -- 如果常用系统目录下检测不到，但是你又装了这个库，你可以自己设定检测的搜索目录
    if is_plat("windows", "mingw") then
        add_defines_h("$(prefix)_GL_APICALL=__tb_stdcall__")
    else
        add_defines_h("$(prefix)_GL_APICALL=__tb_cdecl__")
    end

    add_linkdirs("lib/$(plat)/$(arch)/$(prefix)/lib")

    -- 检测 #include "zlib/zlib.h" 是否能编译通过
    add_cxxincludes("libusb-1.0/libusb.h")

    -- 添加一些检测的头文件目录，默认会在zlib.pkg/inc进行搜索，当然你也可以指定其他目录
    add_includedirs("include")

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 错误信息

PS D:\Holdtecs\PythonZ> xmake
error: .\packages\libusb.pkg\xmake.lua:20: attempt to call global 'is_plat' (a nil value)
stack traceback:
    [.\packages\libusb.pkg\xmake.lua:20]: in main chunk

checking for Microsoft Visual Studio (x64) version ... 2019
error: .\packages\libusb.pkg\xmake.lua:20: attempt to call global 'is_plat' (a nil value)
stack traceback:
    [.\packages\libusb.pkg\xmake.lua:20]: in main chunk

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：xmake v2.3.9+202012081639, A cross-platform build utility based on Lua
- xmake运行平台：
- xmake目标平台：windows 10

### 其他信息

请提供其他附加信息帮助我们诊断问题(比如截图，xmake.lua或者可复现的demo)，以及你遇到的问题的一些背景信息。

**Comment by waruqi** [comment]
你这代码不会是我很老的文章里面弄来的吧，太老了add_defines_h_if_ok，add_defines_h这些我都废弃好久了

另外不要对option使用is_plat，因为is_plat 的值，读的就是 --plat 配置值，而option又是用来定义--xxx=这种自定义配置的，就成了鸡生蛋问题了。。所以后来新版本我对option禁用is_plat了，你看的文章太老了 都是n年前的了

关于option的用法，可以看下文档 https://xmake.io/#/zh-cn/manual/configuration_option

**Comment by waruqi** [comment]
先参考文档 改下demo试试
