### ISSUE TITLE
面向配置编程

### ISSUE THREAD

**Issue by hsz1273327** [xmake-io/xmake#1130]
如果可以的话希望可以通过类似yaml或者json这样比较标准化的格式来描述工程.这样易用性会更好些,也便于其他工具读取使用.

**Comment by xq114** [comment]
compile_commands.json?

```
xmake project -k compile_commands
```

**Comment by hsz1273327** [comment]
我看文档现在的配置文件是一个lua脚本,不是说不好,只是说可能会发展的和jenkins一样到最后强行要用户学一门脚本语言,然后又觉得太麻烦强行弄出一个别处用不到的配置格式增加用户学习成本也给第三方扩展增加额外的维护成本.如果可以在项目初期就定下一种相对通用的配置格式感觉会少走很多弯路,推荐yaml或者json也是因为成熟通用,几乎人人都会,还可以直接使用json schema描述字段和校验配置,会比较方便.

**Comment by waruqi** [comment]
```lua
target("test")
    set_kind("binary")
    add_files("src/*.c")
```

这不就是是配置化的么，你可以不把当lua，难道这个配置还看不懂么？如果你觉得有括号，像脚本调用，你可以去掉

```lua
target "test"
    set_kind "binary"
    add_files "src/*.c"
```

还不行么，这跟json 啥的有啥本质区别么？

另外基于lua，既可以满足初学者向上面这样傻瓜式配置化，也可以满足高端用户脚本化配置能力。

你搞成json，估计也就只能给初学者用用了，稍微熟悉c/c++的，想要深度维护项目的用户压根不会仅用json，那就是放弃一半用户

另外lua也是现有知名语言中最容易学的，总比你去学cmake那套晦涩的dsl强吧，又不是另起一门语言，只是复用，你大可以google上找各种lua教程，再说玩xmake 基本不用去学lua ，0基础的都会，如果上面的配置还觉得复杂学不会的话，那当我没说

另外，这也不是项目初期了，都已经发展6年多的项目，跟meson都快算是同一时代了，你现在提这种有什么意义呢？让我全部推翻设计重来？然后下一个用户又说json不行，再换种配置语法重来一遍？

issues上是反馈问题的，提需求的地方，这种明知没意义的讨论，可以到新开的 https://github.com/xmake-io/xmake/discussions 上讨论，不过我目前没这打算换配置语法

当年cmake还有一堆人建议让cmake改用lua呢，不照样dsl复杂难用，用的好好的现在
