### ISSUE TITLE
How do I get arguments inside custom `on_run` function?

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1131]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
类似
```
xmake run <target> -f data.json
```
如何在`on_run(function(target) ... end)`中识别这些命令行参数？
```
on_run(function(target)
	...do_something
	os.execv(<program>, args)
end)
```

**Comment by waruqi** [comment]
从 option.get("arguments") 中取。


https://github.com/xmake-io/xmake/blob/7d18274bb0b10b0f89a0762cd98d72650f5d7036/xmake/actions/run/main.lua#L62

如果参数不多，直接 argv 列表自己处理下就好，如果参数很多，可以走 option.parse 解析模块

https://github.com/xmake-io/xmake/blob/7d18274bb0b10b0f89a0762cd98d72650f5d7036/xmake/modules/private/xrepo/main.lua#L133-L151
