### ISSUE TITLE
Probably wrong compilation infos output order

### ISSUE THREAD

**Issue by AntoineJT** [xmake-io/xmake#1133]
### Describe the bug
When compiling, the information lines seems to be written in the wrong order (we go i.e. from 7% to 4% and then to 6%, etc.).

![image](https://user-images.githubusercontent.com/26577763/101795803-8d388200-3b08-11eb-8aab-f8809680b5a1.png)

### Expected behavior
We should only progress from 0% to 100% without going back.

### Error output
N/A

### Related Environment

Please provide compiling and running environment information:

- xmake version: v2.3.9+202011250023
- os: Windows 10 1909
- target platform: Windows

### Additional context
I encountered this behavior once before, and I was able to reproduce it just by recompiling it from scratch (after having deleted the .xmake folder).

Maybe you are using a cache system for the output and the order is not conserved. I don't know, I did not read the code.

**Comment by waruqi** [comment]
This is caused by a large number of parallel tasks, and I knew this problem before. But since this is not a big problem, it is just some display disorder, so I did not modify it before. When I have time, I will try to improve it.

**Comment by waruqi** [comment]
I have improved it on dev branch. you can try it again. `xmake update -s dev`
