### ISSUE TITLE
`target:set` not working correctly for `arch` and `toolchains`

### ISSUE THREAD

**Issue by s5bug** [xmake-io/xmake#1135]
### Describe the bug

Create a ruleset like so:
```lua
-- create a default rule for matching compilation
rule("matching")
    on_load(function (target)
        -- Windows x86
        target:set("plat", "windows")
        target:set("arch", "x86")
    
        -- use MSVC and NASM
        target:set("toolchains", "msvc", "nasm")
        target:add("config", "as=nasm")
        
        -- use VS 2005
        target:add("config", "vs=2005")
        
        -- set Windows Vista as the minimum Windows version
        target:add("defines", "_WIN32_WINNT=0x0600")
        
        -- link necessary system libraries
        target:add("syslinks", "user32", "ole32")
        
        -- statically link the C Runtime
        if is_mode("debug") then
            target:add("cxflags", "/MTd")
        else
            target:add("cxflags", "/MT")
        end
    end)
```

Create a target that uses the ruleset:
```lua
target("foo")
    set_kind("binary")
    
    -- only matching builds for now
    add_rules("matching")
    
    -- include pstdint to make up for VS 2005 not having stdint.h
    add_includedirs(
        "external/pstdint/include"
    )
    
    -- platform-independent source files
    add_files(
        "asm/some_asm.asm",
        "src/main.cpp"
    )
```

### Expected behavior

Running `xmake` from a clean directory should build properly, using NASM to build the assembly and VS 2005 to build the C++.

### Error output

```
> xmake
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2005
checking for Microsoft Visual Studio (x86) version ... 2005
error: toolchain("clang"): not found!
```

Even though `clang` was not a desired toolchain.

### Related Environment

Please provide compiling and running environment information:

- xmake version: `xmake v2.3.9+202012081639`
- os: Windows 10 Home 20H2 Build 19042.662
- target platform: Win32 Vista

### Additional context

Setting `vs`, `arch`, `plat`, and `toolchain` via `xmake f` has the following output:

```
> xmake f -p windows -a x86 --vs=2005 --toolchain=msvc --toolchain=nasm -m releasedbg
checking for Microsoft Visual Studio (x86) version ... 2005
```

Then an `xmake` builds the project successfully. Notice how it doesn't look for the x64 version of VS 2005.

**Comment by waruqi** [comment]
oh, I need improve toolchain and rule. Please wait some time.

**Comment by waruqi** [comment]
You can update to dev version and try it. (download dev installer from https://github.com/xmake-io/xmake/actions/runs/415756225 and need wait ci finished)

```lua
add_rules("mode.debug", "mode.release")
set_config("vs", "2005")

rule("matching")
    before_load(function (target)
        -- Windows x86
        target:set("arch", "x86")
        target:set("toolchains", "nasm", "msvc")

        -- set Windows Vista as the minimum Windows version
        target:add("defines", "_WIN32_WINNT=0x0600")

        -- link necessary system libraries
        target:add("syslinks", "user32", "ole32")

        -- statically link the C Runtime
        if is_mode("debug") then
            target:add("cxflags", "/MTd")
        else
            target:add("cxflags", "/MT")
        end
    end)

target("testvs")
    set_kind("binary")
    add_files("src/*.cpp", "src/*.asm")

    -- only matching builds for now
    add_rules("matching")
```

>         target:set("toolchains", "nasm", "msvc")

We need to add the nasm toolchain to override the as setting in the msvc toolchain.

> set_config("vs", "2005")

Currently, we only support global setting vs version, maybe I will improve it later.

**Comment by sorenbug** [comment]
> Currently, we only support global setting vs version, maybe I will improve it later.

Can this be dynamic with some sort of config option?

**Comment by waruqi** [comment]
> > Currently, we only support global setting vs version, maybe I will improve it later.
> 
> Can this be dynamic with some sort of config option?

?

**Comment by sorenbug** [comment]
For now, can I use some sort of `option()` to set the VS version? It's fine if it's set globally.

**Comment by waruqi** [comment]
> For now, can I use some sort of `option()` to set the VS version? It's fine if it's set globally.

Currently set_config does not support option, I need to improve set_toolchains to support vs version setting.

**Comment by waruqi** [comment]
I am improving the toolchain to better support the configuration vs version.

**Comment by waruqi** [comment]
I have supported to set vs version on toochain branch. You can try it again.

Please update to toolchain branch.

```console
xmake update -s toolchain
```

try this:

```lua
target:set("toolchains", "nasm", "msvc", {vs = 2015})
```

I will merge this patch to dev branch if it works.

**Comment by waruqi** [comment]
I continue to improve toolchain branch. you can try it again.

**Comment by waruqi** [comment]
I have merged into dev branch.

**Comment by s5bug** [comment]
Alright. Sorry for the late response, I've been incredibly busy:

```lua
-- add the default rules for the different compilation modes
add_rules("mode.debug", "mode.release", "mode.releasedbg")

-- create a default rule for matching compilation
rule("matching")
    before_load(function (target)
        -- Windows x86
        target:set("plat", "windows")
        target:set("arch", "x86")
    
        -- use MSVC 2005 and NASM
        target:set("toolchains", "nasm", "msvc", {vs = 2005})
        
        -- set Windows Vista as the minimum Windows version
        target:add("defines", "_WIN32_WINNT=0x0600")
        
        -- link necessary system libraries
        target:add("syslinks", "user32", "ole32")
        
        -- statically link the C Runtime
        if is_mode("debug") then
            target:add("cxflags", "/MTd")
        else
            target:add("cxflags", "/MT")
        end
    end)

target("LEGOStarWarsSaga")
    set_kind("binary")
    
    -- only matching builds for now
    add_rules("matching")
```

This creates the output:

```
> xmake
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2019
checking for Microsoft Visual Studio (x86) version ... 2019
```

So, it doesn't even look for VS2005.

**Comment by waruqi** [comment]
>         target:set("toolchains", "nasm", "msvc", {vs = 2005})

my mistake, try string `{vs = "2005"}`

**Comment by s5bug** [comment]
`target:set("toolchains", "nasm", "msvc", {vs = "2005"})`: wrap the version in quotes and it works perfectly.
