### ISSUE TITLE
zlib-dev and libffi-dev not found

### ISSUE THREAD

**Issue by wangzhankun** [xmake-io/xmake#1138]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
When I first run ```xmake``` to build my software after I just install xmake, I run into such an issue than shows ```libffi-dev not found``` or ```zlib-dev not found```. But I have installed both.

### Error output
```bash
checking for architecture ... arm64-v8a
error: libffi-dev not found, please use your system package manager to install it.
```
```bash
checking for architecture ... arm64-v8a
error: zlib-dev not found, please use your system package manager to install it.
```

```bash
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2ubuntu4).
libffi-dev is already the newest version (3.4~20200819gead65ca871-0ubuntu3).
```

### Related Environment

- xmake version: 2.3.9
- os: ubuntu 20.10 arm64-v8a
- target platform: ubuntu 20.10 arm64-v8a

**Comment by waruqi** [comment]
please use libffi and zlib as package name.

https://github.com/xmake-io/xmake-repo/blob/master/packages/l/libffi/xmake.lua

**Comment by xq114** [comment]
It seems like a issue with python installation.

Try
```bash
echo 'import("lib.detect.find_package");print(find_package("system::z"))' > test.lua && xmake l test.lua
```
and the output should be something like
```
{
  links = {
    "z"
  },
  linkdirs = {
    "/usr/lib/x86_64-linux-gnu"
  }
}

{ }
```

Anyway, it's strange since python3 is already installed on Ubuntu 20.10, and xmake should detect it first. Are you using some packages from the xmake package manager?

**Comment by wangzhankun** [comment]
> please use libffi and zlib as package name.
> 
> https://github.com/xmake-io/xmake-repo/blob/master/packages/l/libffi/xmake.lua

I have no idea about what you're saying, would you like to give me more detail?
This is my ```xmake.lua``` file,
```bash
add_syslinks("pthread","gxiapi","cjson", "yaml-cpp")
add_requires("opencv")

includes("Main")
includes("Share")
includes("Armor")
includes("Buff")

target("CV")
    set_kind("binary")
    set_rules("mode.debug", "mode.release")
    --  set_optimize("fastest")
    add_packages("opencv")

set_languages("cxx11")
```

**Comment by wangzhankun** [comment]
> It seems like a issue with python installation.
> 
> Try
> 
> ```shell
> echo 'import("lib.detect.find_package");print(find_package("system::z"))' > test.lua && xmake l test.lua
> ```
> 
> and the output should be something like
> 
> ```
> {
>   links = {
>     "z"
>   },
>   linkdirs = {
>     "/usr/lib/x86_64-linux-gnu"
>   }
> }
> 
> { }
> ```
> 
> Anyway, it's strange since python3 is already installed on Ubuntu 20.10, and xmake should detect it first. Are you using some packages from the xmake package manager?

I run the command that you afford, and the output is nothing:
```bash
{ }
```

**Comment by waruqi** [comment]
try run `xmake l find_package zlib` in non-xmake project dir.

**Comment by waruqi** [comment]
> checking for architecture ... arm64-v8a
error: libffi-dev not found, please use

Please add -vD and let me see verbose output.

xmake f -c -vD
xmake -vD

**Comment by xq114** [comment]
> > checking for architecture ... arm64-v8a
> > error: libffi-dev not found, please use
> 
> Please add -vD and let me see verbose output.
> 
> xmake f -c -vD
> xmake -vD

I think I know what happens. 

https://github.com/xmake-io/xmake-repo/blob/2793cce5ec9514d8c8a3494b5bb224f7b1683134/packages/o/opencv/xmake.lua#L11-L13

https://github.com/xmake-io/xmake-repo/blob/2793cce5ec9514d8c8a3494b5bb224f7b1683134/packages/p/python/xmake.lua#L60-L65

xmake did not find python3, and tried to install python from the repository; however system::z is not found somehow, and the installation failed.

**Comment by xq114** [comment]
> 
> I run the command that you afford, and the output is nothing:
> 
> ```shell
> { }
> ```

Could you please give us the output of the command as follows?
```shell
find /usr/lib | grep -i libz.a
```

On Ubuntu 20.04 it produces
```
/usr/lib/x86_64-linux-gnu/libz.a
```

**Comment by wangzhankun** [comment]
> > I run the command that you afford, and the output is nothing:
> > ```shell
> > { }
> > ```
> 
> Could you please give us the output of the command as follows?
> 
> ```shell
> find /usr/lib | grep -i libz.a
> find /usr/lib | grep -i libffi.a
> ```
> 
> On Ubuntu 20.04 it produces
> 
> ```
> /usr/lib/x86_64-linux-gnu/libz.a
> ```
> 
> and
> 
> ```
> /usr/lib/x86_64-linux-gnu/libffi.a
> ```
```bash
➜  ComputerVision git:(dev) ✗ find /usr/lib | grep -i libz.a
/usr/lib/aarch64-linux-gnu/libz.a
➜  ComputerVision git:(dev) ✗ find /usr/lib | grep -i libffi.a
/usr/lib/aarch64-linux-gnu/libffi.a
```

**Comment by wangzhankun** [comment]
> > > checking for architecture ... arm64-v8a
> > > error: libffi-dev not found, please use
> > 
> > 
> > Please add -vD and let me see verbose output.
> > xmake f -c -vD
> > xmake -vD
> 
> I think I know what happens.
> 
> https://github.com/xmake-io/xmake-repo/blob/2793cce5ec9514d8c8a3494b5bb224f7b1683134/packages/o/opencv/xmake.lua#L11-L13
> 
> https://github.com/xmake-io/xmake-repo/blob/2793cce5ec9514d8c8a3494b5bb224f7b1683134/packages/p/python/xmake.lua#L60-L65
> 
> xmake did not find python3, and tried to install python from the repository; however system::z is not found somehow, and the installation failed.

```bash
checking for architecture ... arm64-v8a
checking for gcc ... /usr/bin/gcc
checking for dmd ... no
checking for ldc2 ... no
checking for gdc ... no
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
checking for ping ... /usr/bin/ping
pinging for the host(gitee.com) ... 37 ms
pinging for the host(github.com) ... 254 ms
pinging for the host(gitlab.com) ... 246 ms
finding z from system ..
checking for pkg-config ... /usr/bin/pkg-config
checking for system::z ... no
error: @programdir/core/main.lua:284: ...make/repositories/xmake-repo/packages/p/python/xmake.lua:63: zlib-dev not found, please use your system package manager to install it.
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:789]: in function 'raiselevel'
    [@programdir/core/sandbox/modules/utils.lua:181]: in function 'assert'
    [...make/repositories/xmake-repo/packages/p/python/xmake.lua:63]: in function 'on_load'
    [@programdir/actions/require/impl/package.lua:375]: in function '_load_package'
    [@programdir/actions/require/impl/package.lua:400]: in function '_load_packages'
    [@programdir/actions/require/impl/package.lua:428]: in function '_load_packages'
    [@programdir/actions/require/impl/package.lua:746]: in function 'load_packages'
    [@programdir/actions/require/impl/package.lua:764]: in function 'install_packages'
    [@programdir/actions/require/install.lua:191]: in function 'install_requires'
    [@programdir/actions/config/main.lua:297]:
    [C]: in function 'load'
    [@programdir/core/base/task.lua:520]: in function 'run'
    [@programdir/core/main.lua:282]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:317]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:789: in function 'raise'
	@programdir/core/main.lua:284: in function 'cotask'
	@programdir/core/base/scheduler.lua:317: in function <@programdir/core/base/scheduler.lua:315>

```

**Comment by waruqi** [comment]
Ok, `find_package z` not found zlib on your system.

> try run `xmake l find_package zlib` in non-xmake project dir.

Can you try these commands first?

```console
xmake l find_package zlib
xmake l find_package z
pkg-config --cflags --libs zlib
pkg-config --cflags --libs z
```

**Comment by wangzhankun** [comment]
> Ok, `find_package z` not found zlib on your system.
> 
> > try run `xmake l find_package zlib` in non-xmake project dir.
> 
> Can you try these commands first?
> 
> ```
> xmake l find_package zlib
> xmake l find_package z
> pkg-config --cflags --libs zlib
> pkg-config --cflags --libs z
> ```

```bash
➜  ComputerVision git:(dev) ✗ xmake l find_package zlib
{ 
  version = "1.2.11",
  links = { 
    "z" 
  } 
}
➜  ComputerVision git:(dev) ✗ xmake l find_package z
nil
➜  ComputerVision git:(dev) ✗ pkg-config --cflags --libs zlib
-lz
➜  ComputerVision git:(dev) ✗ pkg-config --cflags --libs z
Package z was not found in the pkg-config search path.
Perhaps you should add the directory containing `z.pc'
to the PKG_CONFIG_PATH environment variable
No package 'z' found

```

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-repo/blob/2793cce5ec9514d8c8a3494b5bb224f7b1683134/packages/p/python/xmake.lua#L60-L65

@xq114 we should use system::zlib system::libffi instead of system::z system::ffi

**Comment by waruqi** [comment]
> > Ok, `find_package z` not found zlib on your system.
> > > try run `xmake l find_package zlib` in non-xmake project dir.
> > 
> > 
> > Can you try these commands first?
> > ```
> > xmake l find_package zlib
> > xmake l find_package z
> > pkg-config --cflags --libs zlib
> > pkg-config --cflags --libs z
> > ```
> 
> ```shell
> ➜  ComputerVision git:(dev) ✗ xmake l find_package zlib
> { 
>   version = "1.2.11",
>   links = { 
>     "z" 
>   } 
> }
> ➜  ComputerVision git:(dev) ✗ xmake l find_package z
> nil
> ➜  ComputerVision git:(dev) ✗ pkg-config --cflags --libs zlib
> -lz
> ➜  ComputerVision git:(dev) ✗ pkg-config --cflags --libs z
> Package z was not found in the pkg-config search path.
> Perhaps you should add the directory containing `z.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'z' found
> ```

thanks, can you try `find_package libffi` and `find_package ffi` again?

**Comment by xq114** [comment]
> [xmake-io/xmake-repo@`2793cce`/packages/p/python/xmake.lua#L60-L65](https://github.com/xmake-io/xmake-repo/blob/2793cce5ec9514d8c8a3494b5bb224f7b1683134/packages/p/python/xmake.lua#L60-L65)
> 
> @xq114 we should use system::zlib system::libffi instead of system::z system::ffi

There exists one subtlety that pkg-config use `zlib` and `libffi` as package names, but when I don't have pkg-config it will detect the system package by `z` and `ffi`

**Comment by waruqi** [comment]
> > [xmake-io/xmake-repo@`2793cce`/packages/p/python/xmake.lua#L60-L65](https://github.com/xmake-io/xmake-repo/blob/2793cce5ec9514d8c8a3494b5bb224f7b1683134/packages/p/python/xmake.lua#L60-L65)
> > @xq114 we should use system::zlib system::libffi instead of system::z system::ffi
> 
> There exists one subtlety that pkg-config use `zlib` and `libffi` as package names, but when I don't have pkg-config it will detect the system package by `z` and `ffi`

Try `assert(find_package("pkg_config::zlib") or find_package("system:z"), "zlib not found!")` ?

**Comment by waruqi** [comment]
@wangzhankun I have improved python3 package, can you try it again?

```console
xmake repo -u
xmake f -c -vD
xmake
```

**Comment by wangzhankun** [comment]
> @wangzhankun I have improved python3 package, can you try it again?
> 
> ```
> xmake repo -u
> xmake f -c -vD
> xmake
> ```

I add the command ```assert(find_package("pkg_config::zlib") or find_package("system:z"), "zlib not found!")``` and try to rebuild the program:
```bash
xmake repo -u
xmake f -c -vD
xmake
```
But the output error is:
```bash
  ComputerVision git:(dev) ✗ xmake repo -u
xmake f -c -vD
xmake
error: @programdir/core/project/project.lua:1028: ./xmake.lua:8: attempt to call global 'find_package' (a nil value)
stack traceback:
    [./xmake.lua:8]: in main chunk

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:789: in function 'raise'
        @programdir/core/project/project.lua:1028: in function 'tasks'
        @programdir/core/project/project.lua:1017: in function 'task'
        @programdir/core/main.lua:275: in function <@programdir/core/main.lua:219>
error: ./xmake.lua:8: attempt to call global 'find_package' (a nil value)
stack traceback:
    [./xmake.lua:8]: in main chunk

error: @programdir/core/project/project.lua:1028: ./xmake.lua:8: attempt to call global 'find_package' (a nil value)
stack traceback:
    [./xmake.lua:8]: in main chunk

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:789: in function 'raise'
        @programdir/core/project/project.lua:1028: in function 'tasks'
        @programdir/core/project/project.lua:1017: in function 'task'
        @programdir/core/main.lua:275: in function <@programdir/core/main.lua:219>
error: @programdir/core/project/project.lua:1028: ./xmake.lua:8: attempt to call global 'find_package' (a nil value)
stack traceback:
    [./xmake.lua:8]: in main chunk

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:789: in function 'raise'
        @programdir/core/project/project.lua:1028: in function 'tasks'
        @programdir/core/project/project.lua:1017: in function 'task'
        @programdir/core/main.lua:275: in function <@programdir/core/main.lua:219>
```

**Comment by waruqi** [comment]
> I add the command assert(find_package("pkg_config::zlib") or find_package("system:z"), "zlib not found!") and try to rebuild the program:

I don't mean that, I mean that `find_package("system::z")` in xmake-repo/python3/xmake.lua should be improved.

I have improved it, you only need to execute the `xmake repo -u` command to update xmake-repo, you do not need to modify your xmake.lua

**Comment by wangzhankun** [comment]
> > I add the command assert(find_package("pkg_config::zlib") or find_package("system:z"), "zlib not found!") and try to rebuild the program:
> 
> I don't mean that, I mean that `find_package("system::z")` in xmake-repo/python3/xmake.lua should be improved.
> 
> I have improved it, you only need to execute the `xmake repo -u` command to update xmake-repo, you do not need to modify your xmake.lua

Thanks for your solution and I finally successfully to build my program.
