### ISSUE TITLE
Add a way to ask xmake to try to download dependencies from a certain package manager

### ISSUE THREAD

**Issue by ImperatorS79** [xmake-io/xmake#1140]
### Describe the solution you'd like
Currently, one have to add the prefix `pacman::` in front of required librairies to download them using msys on windows. But what happens if a library is available on msys, on conan or on vcpkg and one wants to let the user choose from which package manager the library will be downloaded?

It could be great to add an option from command-line to tell xmake "try first to download dependencies from this package manager, if it does not work, build them using xmake-repo", so that the user is not forced to modify the xmake.lua to do so.

**Comment by waruqi** [comment]
I think only need to modify the xmake.lua configuration to support it.

```lua
add_requires("pacman::zlib", {group = "zlib"})
add_requires("zlib", {group = "zlib"})
target("xxx")
     if has_package("pacman::zlib") then
         add_packages("pacman::zib")
     else
         add_packages("zlib")
     end
```

**Comment by ImperatorS79** [comment]
The problem is that each project manager has to add those `if else` for each package manager manually. Which means that some project manager won't bother while their program would prefectly compiles using librairies coming from pacman.

It would really easy to juste have something like:
```
xmake -prefPkgMan pacman
```

And inside each `add_package` we would have
```lua
if(prefPkgMan == "pacman")
-- try to use pacman
else if (prefPkgMan == "conan")
-- try to use conan
end

-- if pacman or conan failed, use xmake-repo
```

**Comment by waruqi** [comment]
Because even the same package, the configuration in each package manager may be different, and even the package name may be different

xmake cannot handle them automatically, unless the user uses add_requires to explicitly configure which package manager packages to use.

**Comment by waruqi** [comment]
I will improve and support it in 2.5.2. 

see https://github.com/xmake-io/xmake/issues/1239

**Comment by waruqi** [comment]
I have supported it on this pr: https://github.com/xmake-io/xmake/pull/1429

we need add some extsources in packages.

```lua
package("fmt")
    if is_plat("macosx") then
        add_extsources("brew::fmt")
    end
```

and xmake.lua

```lua
add_requires("fmt")
target("test")
    -- ...
    add_packages("fmt")
```

Then run xmake and input `m` and number list to modify packages to select 3rd packages.

```console
$ xmake
note: install or modify (m) these packages (pass -y to skip confirm)?
in local-repo:
  -> fmt 7.1.3
please input: y (y/n/m)
m
note: select the following 3rd packages
  1. brew::fmt -> fmt 7.1.3
please input number list: n (1,2,..)
1
note: install or modify (m) these packages (pass -y to skip confirm)?
in brew:
  -> brew::fmt latest
please input: y (y/n/m)
y
  => install brew::fmt latest .. ok
[ 25%]: ccache compiling.release src/main.cpp
[ 50%]: linking.release test
[100%]: build ok!
```
