### ISSUE TITLE
add_deps依赖顺序问题

### ISSUE THREAD

**Issue by zt449569708** [xmake-io/xmake#1144]
`target("aa")
    set_kind("static")
    add_files("lib/libaa.c")

target("bb")
    set_kind("static")
    add_files("lib/libbb.c")
	
target("dd")
    set_kind("static")
    add_files("lib/libdd.c")

	
target("hello")
    set_kind("binary")
    add_files("src/*.c")
    add_deps("dd", "bb", "aa")
	--add_deps("aa", "bb", "dd")`
我现在有这么3个库aa、bb、dd ，其中dd调用了bb里面的函数，bb又调用了aa里面的函数，如果按add_deps("dd", "bb", "aa")这个顺序，编译就会出错，如果按add_deps("aa", "bb", "dd")编译又是对的。编译工具是gcc。所以想问下，有没有解决方法？

**Comment by waruqi** [comment]
你这么写，仅仅只是设置了 hello 依赖 dd, bb, aa ，但是 dd, bb, aa 之间压根没设置依赖关系。。

既然你的 dd 依赖 bb， bb 依赖 abb ，那么 dd target 里面你要设置 add_deps("bb")

```lua
target("aa")
set_kind("static")
add_files("lib/libaa.c")

target("bb")
add_deps("aa")
set_kind("static")
add_files("lib/libbb.c")

target("dd")
add_deps("bb")
set_kind("static")
add_files("lib/libdd.c")

target("hello")
set_kind("binary")
add_files("src/*.c")
add_deps("dd")
```

hello -> dd -> bb -> aa

**Comment by zt449569708** [comment]
可能这个例子表达不准确，实际上是在使用过程中遇到这么个问题：别人给我了几个静态库，但是这几个静态库之间有依赖关系，就直接导致使用add_links编译不过，必须要使用add_ldflags("Wl,--start-group … Wl,--end-group")才行。所以想问下，add_links可不可以解决这种链接顺序的问题？


 
---原始邮件---
发件人: "ruki"<notifications@github.com&gt;
发送时间: 2020年12月16日 22:08:58
收件人: "xmake-io/xmake"<xmake@noreply.github.com&gt;;
抄送: "zt449569708"<449569708@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [xmake-io/xmake] add_deps依赖顺序问题 (#1144)




 
你这么写，仅仅只是设置了 hello 依赖 dd, bb, aa ，但是 dd, bb, aa 之间压根没设置依赖关系。。
 
既然你的 dd 依赖 bb， bb 依赖 abb ，那么 dd target 里面你要设置 add_deps("bb")
 target("aa") set_kind("static") add_files("lib/libaa.c") target("bb") add_deps("aa") set_kind("static") add_files("lib/libbb.c") target("dd") add_deps("bb") set_kind("static") add_files("lib/libdd.c") target("hello") set_kind("binary") add_files("src/*.c") add_deps("dd")
 
hello -&gt; dd -&gt; bb -&gt; aa

**Comment by waruqi** [comment]
? 你到底再说 add_deps 还是说 add_links 的问题？如果是 add_deps 就按我刚说的来，如果是 add_links 那就自己调整下链接顺序，如果这几个库有循环依赖，那就只能 `Wl,--start-group ..`

**Comment by zt449569708** [comment]
好的，谢谢。


 
---原始邮件---
发件人: "ruki"<notifications@github.com&gt;
发送时间: 2020年12月16日 22:34:38
收件人: "xmake-io/xmake"<xmake@noreply.github.com&gt;;
抄送: "zt449569708"<449569708@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [xmake-io/xmake] add_deps依赖顺序问题 (#1144)




 
? 你到底再说 add_deps 还是说 add_links 的问题？如果是 add_deps 就按我刚说的来，如果是 add_links 那就自己调整下链接顺序，如果这几个库有循环依赖，那就只能 Wl,--start-group ..

**Comment by waruqi** [comment]
如果 没啥其他问题，这里先close了

**Comment by waruqi** [comment]
初步改进了下，试试 https://github.com/xmake-io/xmake/issues/1452#issuecomment-1741152822
