### ISSUE TITLE
Xmake: "check for Microsoft Visual Studio (x64) version ... no

### ISSUE THREAD

**Issue by Mrlobbies** [xmake-io/xmake#1150]
-Windows 10
-VS 2019
What am I missing here?

**Comment by waruqi** [comment]
Can you try run `xmake l detect.sdks.find_studio` in non-xmake project directory and let me see the output?

**Comment by Mrlobbies** [comment]
error: cannot import module: detect.sdks.find_studio, not found

![Screenshot_1](https://user-images.githubusercontent.com/12189789/102727610-8a057900-42f4-11eb-90f9-1f78c709dc02.png)

**Comment by waruqi** [comment]
sorry, it should be `detect.sdks.find_vstudio`

**Comment by Mrlobbies** [comment]
It just shows {  }

**Comment by waruqi** [comment]
vcvarsall.bat/vswhere not found. xmake need them.

https://github.com/xmake-io/xmake/blob/37d4120c6cfd0454b45d606d2969e41631cc1f42/xmake/modules/detect/sdks/find_vstudio.lua#L220

**Comment by Mrlobbies** [comment]
Resolved, new to this .  Thank you for your help :)
