### ISSUE TITLE
add sysroot support for llvm toolchains

### ISSUE THREAD

**Issue by zxlxz** [xmake-io/xmake#1153]
### MacOS/LLVM

当使用llvm.org的LLVM工具链时，报错“找不到头文件”， “找不到链接库”

### 可能的原因

MacOS的系统c++头文件和库，并不在/usr/include下面，而是类似'/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'这样的目录（可以用xcode-select -p看到）

### 可能的解决办法
给clang/clang++添加-sysroot参数，指向这个目录貌似可以解决。

**Comment by waruqi** [comment]
我回头改进下

**Comment by waruqi** [comment]
我 dev 上支持了
