### ISSUE TITLE
这种情况下增量编译不工作

### ISSUE THREAD

**Issue by qyangdu** [xmake-io/xmake#1154]
### Describe the bug
source files:
```
// ../common/test1.hpp 
#include <iostream>

void f()
{
  std::cout << "f()" << std::endl;
}
```
```

// test1.cpp 
#include "common/test1.hpp"

int main(int argc, char** argv)
{
  f();
  return 0;
}
```

```
-- xmake.lua
-- global
add_rules('mode.debug', 'mode.release')

set_version('0.1.0')

set_kind('binary')
add_includedirs('..')
set_warnings('all')
set_languages('cxx20')
target('test1')
add_files('test1.cpp')
target_end()

```

### Expected behavior
incremental compilation should work on header updated.

### Error output
N/A
> If it is a xmake related compilation problem, please add the `-v -D` parameter and give the detailed compilation output information.

xmake -j2 -v -D
[100%]: build ok!

### Related Environment

Please provide compiling and running environment information:

- xmake version: v2.3.9+202011251408
- os: Linux gamma 5.9.13-arch1-1 #1 SMP PREEMPT Tue, 08 Dec 2020 12:09:55 +0000 x86_64 GNU/Linux
- target platform: Linux gamma 5.9.13-arch1-1 #1 SMP PREEMPT Tue, 08 Dec 2020 12:09:55 +0000 x86_64 GNU/Linux

### Additional context
N/A

**Comment by waruqi** [comment]
用你的 case 测了下，linux/macos上 这个版本 都没有复现你说的问题，一切正常

**Comment by qyangdu** [comment]
编译是通过的，第一次编译完成，然后修改header file，再编译不会触发重新编译.
要保证使用的同样的目录结构

**Comment by waruqi** [comment]
> 编译是通过的，第一次编译完成，然后修改header file，再编译不会触发重新编译.
> 要保证使用的同样的目录结构

我刚测试的就是 增量编译，一切正常，test1.hpp 改动，在我这会触发二次编译，完全一样的 demo ，linux/macos都ok

**Comment by qyangdu** [comment]
![image](https://user-images.githubusercontent.com/10286224/102996290-d0a9dc00-455d-11eb-95a6-8c3c9aca5fb9.png)
你看一下这个截图

**Comment by waruqi** [comment]
应该可以了，你更新到 dev 分支再试试。`xmake update -s dev`

**Comment by qyangdu** [comment]
谢谢，工作了。
