### ISSUE TITLE
vs project generator doesn't link correctly

### ISSUE THREAD

**Issue by yamashi** [xmake-io/xmake#1155]
### Describe the bug
Running xmake project -k vs for the following project https://github.com/yamashi/CyberEngineTweaks generates a solution that fails to link due to a mismatch in runtime.

vsxmake works fine but is unusable at the moment due to Visual Studio/ReSharper not being able to run intellisense and thus making the IDE worthless.

### Expected behavior
The generated project uses the correct runtime.

### Error output
```
2>libcpmt.lib(StlCompareStringA.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in Options.obj
2>libcpmt.lib(winapinls.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in Options.obj
2>libcpmt.lib(StlCompareStringW.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in Options.obj
2>libcpmt.lib(StlLCMapStringW.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in Options.obj
2>libcpmt.lib(StlLCMapStringA.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in Options.obj
2>libcpmt.lib(winapisupp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in Options.obj
```

### Related Environment

Please provide compiling and running environment information:

- xmake version:  v2.3.9+202011250023
- os: Windows 10
- target platform: Windows x64

**Comment by waruqi** [comment]
pass vs_runtime to add_requires and try `cache` branch version.

see https://github.com/xmake-io/xmake/issues/1071

**Comment by yamashi** [comment]
cache branch version doesn't help.

I am not even sure it updates correctly to be honest.

**Comment by waruqi** [comment]
you can download install package from ci.

https://github.com/xmake-io/xmake/actions/runs/440223780

xmake-latest.win64.exe

**Comment by waruqi** [comment]
I found that there are still many problems with vs_runtime, and I will try to better support the setting and configuration synchronization of vs_runtime, please wait some time.

**Comment by waruqi** [comment]
> 2>libcpmt.lib(StlCompareStringA.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in Options.obj

This is because MD is enabled for the VS project generated by default (this needs to be fixed), and the dependent package defaults to MT

xmake build is also MT by default

**Comment by waruqi** [comment]
I have improved vs project plugin and vs_runtime, you can install `cache` branch version from ci. https://github.com/xmake-io/xmake/suites/1720734652/artifacts/32543053

and try this configuraion. I have tested it, it works for me.

```lua
set_languages("cxx20")

add_requires("spdlog", "nlohmann_json", "minhook", "imgui", "sol2", "tiltedcore")

add_rules("mode.debug", "mode.release")

if is_mode("release") then
    add_ldflags("/LTCG", "/OPT:REF")
    add_cxflags("/Ot", "/GL", "/Ob2", "/Oi", "/GS-")

    set_optimize("fastest")
end

target("RED4ext")
    set_kind("static")
    add_files("vendor/RED4ext/src/red4ext.sdk/**.cpp")
    add_headerfiles("vendor/RED4ext/src/red4ext.sdk/**.hpp")
    add_includedirs("vendor/RED4ext/src/red4ext.sdk/", { public = true })

target("cyber_engine_tweaks")
    add_defines("KIERO_USE_MINHOOK=1", "KIERO_INCLUDE_D3D12=1")
    set_kind("shared")
    set_filename("cyber_engine_tweaks.asi")
    add_files("src/**.cpp")
    add_headerfiles("src/**.h")
    add_includedirs("src/")
    add_syslinks("User32", "d3d11", "D3D12")
    add_packages("spdlog", "nlohmann_json", "minhook", "imgui", "sol2", "tiltedcore")
    add_deps("RED4ext")
```

**Comment by waruqi** [comment]
I have merged `cache` branch to dev. you can download package from ci (https://github.com/xmake-io/xmake/actions/runs/442445201) try it again.

**Comment by waruqi** [comment]
Does it work?

**Comment by yamashi** [comment]
Yes that did it! Thanks 👍

**Comment by yamashi** [comment]
Reopening because this patch breaks xmake standalone compilation.

It fails to include standard C++ files like algorithm, cstdint...

**Comment by waruqi** [comment]
> Reopening because this patch breaks xmake standalone compilation.
> 
> It fails to include standard C++ files like algorithm, cstdint...

？vs plugin issues? what errors?

**Comment by yamashi** [comment]
No just running the build from command line:
`xmake`
Buid fails with 
> fatal error C1083: Cannot open include file: 'algorithm': No such file or directory

**Comment by waruqi** [comment]
It works for me. You can run `xmake f -c -vD` and `xmake -vD`, then let me see the output.

![Snip20201225_5](https://user-images.githubusercontent.com/151335/103136120-93c61c80-46f8-11eb-8809-48f08c256d77.png)

**Comment by yamashi** [comment]
I managed to fix it by deleting the .xmake folder, sorry for the trouble!

**Comment by waruqi** [comment]
> I managed to fix it by deleting the .xmake folder, sorry for the trouble!

You need only add `-c` arg to `xmake f -c` to clear config cache, because I rewrote cache modules recently.
