### ISSUE TITLE
is_config使用

### ISSUE THREAD

**Issue by zt449569708** [xmake-io/xmake#1159]
![IMG_20201224_160146](https://user-images.githubusercontent.com/6011216/103072924-8ed27180-4601-11eb-9d38-f045c6b8c647.jpg)
你好，xmake使用过程中发现个问题，想请教一下，就是我看xmake的文档，可以通过is_config来判断自定义的配置，但是我在xmake f --xxx=yyy的时候，就会报错，提示无效的选项。
就比如xmake文档给的例子，xmake  f  --test=hello，就会提示--test=hello为无效选项

**Comment by waruqi** [comment]
首先你得通过 `option("test")` 定义一个扩展选项

**Comment by zt449569708** [comment]
![IMG_20201224_174100](https://user-images.githubusercontent.com/6011216/103079710-58035800-460f-11eb-8e73-8cf26def8a0d.jpg)
我按这个方法还是不行，如图。

**Comment by waruqi** [comment]
得设置 set_showmenu(true)   

https://xmake.io/#/zh-cn/manual/configuration_option?id=optionset_showmenu

**Comment by zt449569708** [comment]
好的，谢谢，解决了。


 
---原始邮件---
发件人: "ruki"<notifications@github.com&gt;
发送时间: 2020年12月24日 18:46:02
收件人: "xmake-io/xmake"<xmake@noreply.github.com&gt;;
抄送: "zt449569708"<449569708@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [xmake-io/xmake] is_config使用 (#1159)




 
得设置 set_showmenu(true)
 
https://xmake.io/#/zh-cn/manual/configuration_option?id=optionset_showmenu

**Comment by zt449569708** [comment]
遇到个新问题，想咨询一下，我在编译一个静态库的时候，通过add_files(src/*.c,lib/*.a)添加源文件和其他库，就出现图中这个错误。
![IMG_20201224_203150](https://user-images.githubusercontent.com/6011216/103088860-1e3e4b80-4627-11eb-87c0-264773be775c.jpg)

**Comment by waruqi** [comment]
添加链接库用 add_links

**Comment by zt449569708** [comment]
我不是想链接库，而是想在新的库里面，把其他库打包在一起，并且前段时间都是可以的，后面更新了脚本，今天再来xmake的时候就不行了，从编译过程来看，就像c文件还没全部编译，就开始insert库了

**Comment by waruqi** [comment]
> 我不是想链接库，而是想在新的库里面，把其他库打包在一起，并且前段时间都是可以的，后面更新了脚本，今天再来xmake的时候就不行了，从编译过程来看，就像c文件还没全部编译，就开始insert库了

如果觉得归并.a有问题，你就另开个issues，详细描述下，最好能提供可复现的demo 还有操作平台

另外可以先追加 -c 到 xmake f -c 清下cache 重新触发下检测
