### ISSUE TITLE
vsxmake: Launch console programs the same way VS does

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#1164]
### Is your feature request related to a problem? Please describe.
When starting the executable from a vsxmake project (instead of a regular vs one), it will be run directly, and will directly close on exit, instead of leaving a console with the program output. This is useful in case of error.

### Describe the solution you'd like
That running a program using a vsxmake project (using F5 or Ctrl+F5) runs it the same way VS does.

### Describe alternatives you've considered
Adding a std::getchar() call to the executable, but that is intrusive and don't work with crashes.

### Additional context
It seems Visual Studio use VsDebugConsole.exe internally.

Here's the process tree of a program launched from a regular VS project:
![image](https://user-images.githubusercontent.com/3002461/103139872-29ee4880-46e1-11eb-8c76-682d97ffc6d9.png)

Here's the process tree of a program launched from a vsxmake project:
![image](https://user-images.githubusercontent.com/3002461/103139876-3a062800-46e1-11eb-8ec0-e6046418aece.png)

This feature seems to be related to `Tools->Options->Debugging->Automatically close the console when debugging stops` (has to be unchecked) in regular VS projects, and requires /subsystem:console.

**Comment by SirLynix** [comment]
Okay so this was not as complicated as I expected.

Setting the subsystem to "Console (/SUBSYSTEM:CONSOLE)" in the Visual Studio project did restore this behavior (this setting belongs to the project -> linker -> system -> subsystem).

This changes introduced an `ItemDefinitionGroup` in the vcxproj which sets this in the vcxproj file:
```
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='debug|x64'">
    <Link>
      <SubSystem>Console</SubSystem>
    </Link>
  </ItemDefinitionGroup>
```

A simple way to fix this would be to do the same as vs project and generates a SubSystem entry which will be set to Console or Windows (even though xmake handles the build, this setting is used by VS to run the project).

**Comment by waruqi** [comment]
Ok, I will look at it.

**Comment by waruqi** [comment]
I have supported it on dev branch.

**Comment by SirLynix** [comment]
I have tested it and it works yell 👍 thank you!
