### ISSUE TITLE
xmake构建项目会区分release和debug模式吗？

### ISSUE THREAD

**Issue by baby7305** [xmake-io/xmake#1166]
### 你在什么场景下需要该功能？

请尽量清晰精准地描述你碰到的问题。

xmake构建项目会区分release和debug模式吗？

### 描述可能的解决方案

请尽量清晰精准地描述你期待我们要做的，描述你想到的实现方案。

`
target("qt_widgetapp")
    add_rules("qt.application")
    add_files("src/*.cpp") 
    add_files("src/mainwindow.ui")
    add_files("src/mainwindow.h")  -- 添加带有 Q_OBJECT 的meta头文件
    add_frameworks("QtWidgets")

`

### 描述你认为的候选方案

请尽量清晰精准地描述你能接受的候选解决方案。

再加一个add_rules规则？

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by waruqi** [comment]
用 xmake create 创建的所有 空工程 都是自带 debug/release 模式的，你可以创建个看看

**Comment by baby7305** [comment]
哦，xmake区分debug、release。
add_rules("mode.debug", "mode.release")
xmake run，release模式直接执行。
xmake run -d，msvc下直接调出visual studio执行，一闪而过。

**Comment by waruqi** [comment]
要切到debug编译，然后内部自己打断点或者加int中断下 不然正常运行退出 当然就直接退了
