### ISSUE TITLE
2.3.9 vsxmake 没有包含package 的include目录

### ISSUE THREAD

**Issue by vkensou** [xmake-io/xmake#1169]
### 描述问题

更新到2.3.9 vsxmake 生成的vs工程 没有包含package 的include目录

### 错误信息
打开vs工程，引用包的头文件，都显示无法找到头文件

### 相关环境

- xmake版本：2.3.9
- xmake运行平台：windows
- xmake目标平台：windows

### 其他信息
退回到2.3.8一切正常

**Comment by waruqi** [comment]
这个问题已修复，见：https://github.com/xmake-io/xmake/issues/1080
