### ISSUE TITLE
vs project cannot load if using precompiled header

### ISSUE THREAD

**Issue by yamashi** [xmake-io/xmake#1171]
### Describe the bug
Using `set_pcxxheader("src/stdafx.h")` will result in the vs project not loading with error:
> error  : Cannot load project with duplicated project items: ..\..\src\stdafx.h is included as 'ClCompile' and as 'ClInclude' item types. 

vsxmake works correctly but Intellisense does not take into account the files included in the precompiled headers.

### Expected behavior
Project loads and can be built.

### Error output

- xmake version: dev
- os: Windows 10
- target platform: Windows x64

**Comment by waruqi** [comment]
vs/vsxmake currently does not support set_pcxxheader, if I have time, I will try to support it on 2.5.1, but it may need to wait until 2.5.2

**Comment by waruqi** [comment]
vs project plugin? oh, it supports pch and works for me. 

```lua
add_rules("mode.debug", "mode.release")

target("testpch")
    set_kind("binary")
    add_files("src/*.cpp")
    set_pcxxheader("src/stdafx.h")
```



![Snip20201227_6](https://user-images.githubusercontent.com/151335/103174075-189c6c00-489a-11eb-8e82-ecd8d34f7f1f.png)

**Comment by waruqi** [comment]
Oh, `set_pcxxheader("src/stdafx.h")` conflicted with `add_headerfiles("src/stdafx.h")`

**Comment by yamashi** [comment]
Ah that makes sense!

**Comment by waruqi** [comment]
> Using set_pcxxheader("src/stdafx.h") will result in the vs project not loading with error:

error : Cannot load project with duplicated project items: ....\src\stdafx.h is included as 'ClCompile' and as 'ClInclude' item types.

I have fixed it on dev branch.

**Comment by waruqi** [comment]
> vsxmake works correctly but Intellisense does not take into account the files included in the precompiled headers.

It works for me, I can't reproduce it

**Comment by yamashi** [comment]
Seems to work when including stdafx.h manually indeed!
