### ISSUE TITLE
MACOSX  LLVM/Clang的sysroot参数

### ISSUE THREAD

**Issue by zxlxz** [xmake-io/xmake#1179]
## 1.1 Clang:
$ touch a.cc
$ clang -c -v a.cc 2>&1|rg sysroot
会输出clang自带的sysroot参数，比如我的机器是这样的：
 `-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk`
需要编程提取里面的信息。

后面的`SDKS/MacOSX.sdk`看起来是固定的，因此找到前面的`/Library/Developer/CommandLineTools`即可。

## 1.2 Clang
$ clang --version
会输出InstalledDir，比如我的机器是`/Library/Developer/CommandLineTools/usr/bin`。

## 2. xcode-select
$ xcode-select -p
会输出类似这样的目录
`/Library/Developer/CommandLineTools`
用`$(xcode-select -p)/SDKS/MacOSX.sdk`可以当做sysroot的参数。

**Comment by waruqi** [comment]
回头我会改进下

**Comment by waruqi** [comment]
我现在没装 /Library/Developer/CommandLineTools， 这个目录下的文件列表能给我看下么，看下还有哪些东西。。

```console
ls -l /Library/Developer/CommandLineTools
```

**Comment by zxlxz** [comment]
$ /bin/ls -l /Library/Developer/CommandLineTools
total 0
drwxr-xr-x  5 root  wheel  160 May 26  2020 Library
drwxr-xr-x  7 root  wheel  224 Dec  7 23:20 SDKs
drwxr-xr-x  7 root  wheel  224 May  3  2020 usr
$ /bin/ls -l /Library/Developer/CommandLineTools/SDKs
total 0
lrwxr-xr-x  1 root  wheel   14 Dec  7 23:19 MacOSX.sdk -> MacOSX11.1.sdk
drwxr-xr-x  7 root  wheel  224 May 26  2020 MacOSX10.14.sdk
drwxr-xr-x  8 root  wheel  256 Dec  7 23:20 MacOSX10.15.sdk
drwxr-xr-x  4 root  wheel  128 Dec  7 23:19 MacOSX11.0.sdk
drwxr-xr-x  7 root  wheel  224 Nov 11 06:23 MacOSX11.1.sdk

**Comment by waruqi** [comment]
我改进过了，你再试试，xmake update dev

**Comment by waruqi** [comment]
应该可以了的，不行再开好了
