### ISSUE TITLE
Fail to build a test program with qt6

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1183]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
用Qt6无法编译测试程序qt.console

### Expected behavior
正常编译

### Error output
```
...
error: main.cpp
C:\Qt\6.0.0\msvc2019_64\include\QtCore/qglobal.h(379): error C7525: inline variables require at least '/std:c++17'
...
```

### Related Environment

Please provide compiling and running environment information:

- xmake version: 2.3.9
- os: Windows 10
- target platform: windows

### Additional context
Qt6使用C++17，因此必须要用C++17的flag编译，而自动生成的测试程序使用的是C++11

**Comment by waruqi** [comment]
qt6我没特别测过，应该需要做些适配调整才行，不过最近2.5.1开始收尾了，除非特别严重的问题或者不会花费太多时间就能解决的小问题

其他的都统一放到2.5.2处理

**Comment by waruqi** [comment]
可以了，dev上
