### ISSUE TITLE
Windows tab-completion installation failed due to GFW

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1186]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
Windows上试图安装tab-completion的时候报错网络异常，原因是raw.githubusercontent.com被墙
https://github.com/xmake-io/xmake/blob/d9fb6826a45caafc94772ba63c87a3d2f023867e/scripts/get.ps1#L155-L157

```
Download failed!
Check your network or... the news of S3 break
```

挂梯子后一切正常。是否可以考虑把register-completions.ps1挂到ci或者xmake.io上？

**Comment by waruqi** [comment]
dev上改了
