### ISSUE TITLE
gcc正常，xmake :  x86_64-w64-mingw32-gcc: error: CreateProcess: No such file or directory

### ISSUE THREAD

**Issue by Rorschach1219** [xmake-io/xmake#1191]
### 描述问题

xmake create -l c -P ./hello  之后  xmake 报错

[ 25%]: compiling.release src\main.c
error: x86_64-w64-mingw32-gcc: error: CreateProcess: No such file or directory
warning: add_cxflags("-DNDEBUG") is ignored, please pass `{force = true}` or call `set_policy("check.auto_ignore_flags", false)` if you want to set it.

gcc -v : gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)

### 期待的结果

正常编译

### 错误信息

![图片](https://user-images.githubusercontent.com/20067002/104208770-d8c5af00-546b-11eb-80fa-8b7669c999d6.png)

![图片](https://user-images.githubusercontent.com/20067002/104208848-f266f680-546b-11eb-96c6-6ceb73611bfb.png)

![图片](https://user-images.githubusercontent.com/20067002/104208867-f7c44100-546b-11eb-8762-c166f6a173b4.png)

![图片](https://user-images.githubusercontent.com/20067002/104208880-fbf05e80-546b-11eb-840c-e8e0ea73354c.png)

### 相关环境

- xmake版本： xmake-dev.win64.exe  -  2.3.9.0
- xmake运行平台：win
- xmake目标平台：win

**Comment by waruqi** [comment]
你先试试 用pacman -Sy mingw-w64-x86_64-xmake
 安装的包行不行

**Comment by waruqi** [comment]
这个感觉像是xmake没取到mingw gcc的path变量

你执行下 xmake l os.getenv PATH

给我看下输出

echo $PATH

这个也给我看下

**Comment by ShelpAm** [comment]
所以最后是什么问题？我这里也遇到了。

而且运行`xmake l os.getenv PATH`是有mingw的bin目录的。
