### ISSUE TITLE
能否提供对 TDM-GCC 的 toolchain 支持？

### ISSUE THREAD

**Issue by TheBadZhang** [xmake-io/xmake#1192]
[TDM-GCC](https://jmeubank.github.io/tdm-gcc/)

因为这个版本的 "GCC" 十分方便安装，而且省去了很多不必要的麻烦。有一些 IDE 中似乎就直接集成了 TDM-GCC ，
我想知道是否能够为 TDM-GCC 提供 toolchain 支持？

最后、感谢大大为我们带来的方便又好用的构建工具
（我真的好喜欢

**Comment by waruqi** [comment]
gcc的话，通常只需要切下 path，或者设置下 xmake f --cc=xx 就能直接切过去，或者走交叉编译，指定下 sdk 目录就行了。。除非是内部工具链和编译器命令都完全变了，通常前面说的方式可以直接支持

**Comment by TheBadZhang** [comment]
> gcc的话，通常只需要切下 path，或者设置下 xmake f --cc=xx 就能直接切过去，或者走交叉编译，指定下 sdk 目录就行了 xmake f -p cross --sdk=xxx。。除非是内部工具链和编译器命名都完全变了，通常前面说的方式可以直接支持

是的，但是，啊，我好像提了一个愚蠢的要求呢

**Comment by waruqi** [comment]
我感觉没啥可以改的 先直接切过去试试吧 应该支持的
