### ISSUE TITLE
提供接口或机制控制一定范围内的编译行为

### ISSUE THREAD

**Issue by knightjun** [xmake-io/xmake#1198]
### 你在什么场景下需要该功能？

我构建的软件有很多模块，其中一些部署到私有的xrepo源里，需要让尽可能多的模块生成PDB文件并集中到某个路径，便于调试或者程序奔溃回溯，但是这些模块都是没有设置set_symbol("debug")的，默认不会生成PDB文件，需要在它们生成过程中增加配置和脚本。

目前使用的方案：
在xmake的代码里面修改C++的rules，插入要在编译前和编译后运行的代码，这种方案能解决，但是通过修改xmake来实现不方便在其他机器上使用和xmake更新。

### 描述可能的解决方案

由xmake来提供接口或者机制，能全局的控制编译行为

### 描述你认为的候选方案

提供类似“xmake plugin insert xxx（脚本插件路径）”的命令，脚本插件内可设置类似于add_to_rule("c++")的域来增加已有rule的行为，xmake plugin insert 默认是本地会话生效（通过环境变量实现），可以应用于这个会话下的xmake编译包括xmake require的行为，也可以设置成全局生效

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by waruqi** [comment]
开启调试配置，引入第三方包：

```lua
add_requires("xxx", {debug = true})
```

如果第三方包是xmake维护的，设置了 `add_rules("mode.debug", "mode.release")`，那么可直接支持

如果第三方包是其他构建系统维护的，只需要在 xmake-repo 或者私有仓库中的包定义里面，判断 package:debug() 开启调试配置

```lua
package("xxx")
    on_install(function (package)
        if package:debug() then
            -- enable debug
        end
    end)
```

另外，xmake-repo官方仓库中，已经有不少包已经支持判断debug，开启调试编译，如果有用到的包还不支持，可以提pr过来，自己私有仓库的包，相同的处理方式，参考：

https://github.com/xmake-io/xmake-repo/blob/ee7110d8cbcb0b0044d0e291efa5292da64fb855/packages/l/libcurl/xmake.lua#L37

https://github.com/xmake-io/xmake-repo/blob/ee7110d8cbcb0b0044d0e291efa5292da64fb855/packages/l/libcurl/xmake.lua#L46-L50

**Comment by knightjun** [comment]
其实我主要是想建议提供一种可以全局修改编译行为的机制，debug_symbol只是一个例子，因为生成debug符号文件后，还要做一些自动操作，比如把这些符号文件归档之类的，就目前的xmake来说，通过调试配置是做不到那么灵活的，而这种属于特定项目需要的操作，加到每个包的脚本里面也不合适，目前是改xmake的代码来解决这个问题。
我觉得除了我这种场景，应该还有其他的工程项目需要用到这种机制，比如编译前对用到的包的代码进行签名埋点，编译后对编译结果文件进行归档或者扫描之类的操作，因此我建议是由xmake提供机制，由使用者根据实际需要编写对应的插件

**Comment by waruqi** [comment]
常规特定包配置，走 `add_requires("xxx", {configs = {shared = true, xxx=true}})`  各种自定义配置控制包编译，原本就支持。

> 我觉得除了我这种场景，应该还有其他的工程项目需要用到这种机制，比如编译前对用到的包的代码进行签名埋点，编译后对编译结果文件进行归档或者扫描之类的操作，因此我建议是由xmake提供机制，由使用者根据实际需要编写对应的插件

复杂的特殊配置，fork 定制下 xmake-repo 仓库中的包，走你你自己的私有仓库，或者直接在你自己工程的 xmake.lua 里面定义 package("")

还是刚说的方式

```lua
add_requires("xxx", {configs = {sign = true}})
```

```lua
package("xxx")
    on_install(function (package)
        if package:config("sign") then
            -- 如果启用签名，先自己遍历当前代码，做签名埋点
        end
        -- do build and install
    end)
```

如果需要对每个包做相同的处理，可以自己独立到一个 lua 模块中去复用。

```lua
package("xxx")
    on_install(function (package)
        if package:config("sign") then
            import("xxxx.sign").sign(package)
        end
        -- do build and install
    end)
```

**Comment by knightjun** [comment]
嗯，那我还是使用lua模块的方式吧
