### ISSUE TITLE
vsxmake autoupdate + cache issue

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#1200]
### Describe the bug
This is a bit weird, I'm having this bug from time to time on my other projects when regenerating a vsxmake project.

What happens is that when generating a vsxmake project, some settings seems to just, I don't know, fail the second time.

It's very strange as it seems to be a bit random, but linked to the regeneration of a vsxmake project.

### Expected behavior
That everything works everytime.

### Error output
[First error output](https://pastebin.com/4Zzv6YBj)
[Second error output](https://pastebin.com/AHM1xhdG)

They seems to be a bit similar, but not identical.
### Related Environment

- xmake version: latest xmake dev (as of this issue, it's 36e9370b50ed50d65f843a4a46afce1ad0ad2fbe )
- os: Windows 10 2004
- target platform: Windows

### Additional context

Project files:

xmake.lua:
```lua
-- pass debug option, and it should be `configs` not `config`
add_requires("fmt", { debug = is_mode("debug"), configs = { header_only = false } })

add_rules("mode.debug", "mode.release")
add_rules("plugin.vsxmake.autoupdate")

set_runtimes(is_mode("debug") and "MDd" or "MD")

target("test_lib")
    set_kind("static")
    add_files("src/lib.cpp")
    add_packages("fmt")

target("test_fmt")
    set_kind("binary")
    add_deps("test_lib")
    add_files("src/main.cpp")
    add_packages("fmt")
```

src/lib.hpp:
```cpp
#pragma once

void printHelloWorld();
```

src/lib.cpp:
```cpp
#include <fmt/core.h>

void printHelloWorld() {
  fmt::print("Hello, world!\n");
}
```

src/main.cpp:
```cpp
#include "lib.hpp"

int main() {
  printHelloWorld();
}
```

Steps to reproduce :

1) Run xmake project -k vsxmake, accept fmt installation.
2) Open vsxmake solution.
3) Right click on test_fmt and build.
The project should build fine and a new vsxmake project be generated (with autoupdate), reload all once the compilation has succeeded.
4) Right click on test_fmt and build.
5) The compilation should fail with this error:
```
1>EXEC : error : @programdir\modules\private\async\runjobs.lua:217: @programdir\actions\build\kinds\binary.lua:73: @programdir\modules\core\tools\link.lua:153: fmt.lib(format.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in test_lib.lib(lib.cpp.obj)
1>fmt.lib(format.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in test_lib.lib(lib.cpp.obj)
```

If you can't reproduce it with theses steps, I suggest trying over and over, and maybe regenerating the vsxmake project, it seems to be related with the config switching.

This bugs happens fairly often on my side, I can fix it by deleting the local .xmake folder and trying again.

**Comment by waruqi** [comment]
This is a cache issue, I have reproduced it. `xmake project -k vsxmake` will cause inconsistencies in the cache and configuration status, affecting normal compilation.

```console
$ xmake f -m debug -c
$ xmake project -k vsxmake
$ xmake -rv
```

And I have fixed it now on dev branch. I also fixed the problem of repeated autoupdate.

**Comment by waruqi** [comment]
I have fixed it
