### ISSUE TITLE
基本的api调用提示错误，如set_runenv, import等

### ISSUE THREAD

**Issue by wzc0066** [xmake-io/xmake#1203]
安装的是最新的xmake环境， 基本的编译是可以的。

测试脚本：
```bash
add_rules("mode.debug", "mode.release")

import("core.project.project")

target("hello")
    set_kind("binary")
    add_files("src/*.c")

    after_build(function (target)
	--add_runenvs("XXX_CC", "gcc")
        --set_runenv("YYY_CC", "gcc")
    end)
```
通过注释逐条测试的错误信息如下：

error: ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:47: attempt to call global 'add_runenvs' (a nil value)

error: ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:47: attempt to call global 'set_runenv' (a nil value)

error: @programdir/core/project/project.lua:1028: ./xmake.lua:3: attempt to call global 'import' (a nil value)

都是文档里面介绍的API函数，是什么原因呢？
环境不完整 ？

**Comment by waruqi** [comment]
看下文档，https://xmake.io/#/zh-cn/guide/syntax_description?id=%e9%85%8d%e7%bd%ae%e5%88%86%e7%a6%bb

add_runenv属于描述域配置接口，只能在描述域使用
import 属于脚本域接口，只能在脚本域使用

至于那些是描述域，那些是脚本域，刚的文档里面有说明

**Comment by wzc0066** [comment]
将set_runevn移到了描述域之后，没有错误了，但是环境变量好像也没设置成功，输出为空。

```bash
add_rules("mode.debug", "mode.release")

target("hello")
    set_kind("binary")
    add_files("src/*.c")
    set_runenv("MY_CC", "gcc")

    after_build(function (target)
        print(os.getenv("MY_CC"))
    end)

```

**Comment by waruqi** [comment]
仔细看下文档，set_runenv 是设置 `xmake run` 时候的 `on_run` 脚本的环境变量的。其他地方不设置。

你想其他地方任意设置，就用 `os.setenv("MY_CC", "gcc")` 直接设置

**Comment by wzc0066** [comment]
1. os.setenv好像只能放到脚本域使用，如果放到描述域，则会报错。

2. 在脚本域里面，os.setenv和os.getenv测试都正常，但是接下来的 os.exec() 执行脚本时并不能访问到前面设置的环境变量， 这个是正常的么 ？(我的理解是通过os.setenv设置的环境变量，作用范围无法传递到shell层面导致的，有没有可以传递到shell层面的设置方法 ？)

3. 如果本身有一个用来设置环境变量的shell脚本，如env.sh, 然后执行：os.exec("source env.sh") 是不支持的。有什么实现类似效果的方法么 ？

**Comment by waruqi** [comment]
> os.setenv好像只能放到脚本域使用，如果放到描述域，则会报错。

描述域仅作为基础配置，只能使用有线的只读接口，复杂接口调用请在脚本域使用，文档有说明

> 在脚本域里面，os.setenv和os.getenv测试都正常，但是接下来的 os.exec() 执行脚本时并不能访问到前面设置的环境变量， 这个是正常的么 ？(我的理解是通过os.setenv设置的环境变量，作用范围无法传递到shell层面导致的，有没有可以传递到shell层面的设置方法 ？)

不可能， 我这都ok
![image](https://user-images.githubusercontent.com/151335/105149366-6d9c6c80-5b3e-11eb-9e65-bb2f32e86145.png)

> 如果本身有一个用来设置环境变量的shell脚本，如env.sh, 然后执行：os.exec("source env.sh") 是不支持的。有什么实现类似效果的方法么 ？

source 当然不支持，这个是 bash/sh 内置的命令，不是独立程序，os.exec 只能运行独立进程，设置环境变量就用 os.setenv 

或者 os.execv("echo", {"xxx"}, {envs = {TEST = "sss"}})

**Comment by wzc0066** [comment]
os.setenv("MY_CC", "mygcc")

-- 可以输出刚设置的$MY_CC
print(os.getenv("MY_CC"))

-- 系统环境变量$PATH也能输出
print(os.getenv("PATH"))


然后在Teminal终端执行：echo $MY_CC 是空的 （ $PATH是系统变量，echo 输出正常）。

是正常的么？ （ 系统ubuntu20.04, 前面说的setenv的作用范围无法传递到shell层面就指的是这个 ）

**Comment by waruqi** [comment]
> 然后在Teminal终端执行：echo $MY_CC 是空的 （ $PATH是系统变量，echo 输出正常）。

这跟终端有什么关系，程序内部的所有 环境变量设置，都是影响不到 外部终端的，只对当前进程有效
