### ISSUE TITLE
xrepo install需要支持解析通过"--toolchain"指定的自定义toolchain文件

### ISSUE THREAD

**Issue by wzc0066** [xmake-io/xmake#1204]
### Describe the bug
创建了一个单独toolchain文件，{proj}/toolchains/rt_toolchain.lua, 
通过在xmake.lua里面引用: includes("toolchains/*.lua")，测试正常。

但是xrepo install 的时候， 通过--toolchain 指定，提示not found.

按照ruki大佬的解释：xrepo 那个是新加的命令，暂时不支持用户自己定义的 toolchain.lua， --toolchain= 只能切换内置的，目前仅 xmake.lua 工程支持 自定义的 toolchain.lua 文件 。

### Expected behavior
希望增加该特性的支持。

### Error output
提示：the toolchain toolchains/rt_toolchain not found!

### Related Environment
- xmake version:  v2.3.9+202101141459
- os: Ubuntu 20.04
- target platform:  arm

**Comment by waruqi** [comment]
我 dev 分支上改进了下，可以更新到 dev 版本试试，加了一个 `--includes=`  参数引入 外部lua配置文件

```console
$ xmake update -s dev
$ xrepo install -p cross --sdk=/xxx --includes=/xxx/toolchains.lua --toolchain=mytool zlib
```
