### ISSUE TITLE
xrepo install的时候toolchain里面定义的Includedirs没有被透传

### ISSUE THREAD

**Issue by wzc0066** [xmake-io/xmake#1205]
### Describe the bug
自定义一个toolchain lua文件，在里面的 on_load(function(toolchain) 中增加includedirs定义，如：
toolchain:add("includedirs", "/home/test/include")

在xmake.lua里面引用自定义的toolchain：includes("toolchains/*.lua"),  编译的log里面可以看到“-I/home/test/include”;

但是在xrepo install 调用自定义的toolchain进行编译过程，看不到对定义的includedirs的引用。

### Expected behavior
当有些包需要额外依赖includeddir 才能编译的时候，就没法指定。

### Related Environment
- xmake version: xmake dev
- os: Ubuntu 20.04
- target platform: arm

据说只有Makefile维护的包才会如此，像autoconf和cmake维护的包就没这问题。但我这边没验证过。
现在编译的zlib确实是通过configure产生Makefile进行编译的。

**Comment by waruqi** [comment]
你再试试，应该可以了。。
