### ISSUE TITLE
7z cannot be used in projects

### ISSUE THREAD

**Issue by yamashi** [xmake-io/xmake#1209]
### Describe the bug
find_7z returns "7z" on windows, resulting in a failure to call os.vrunv("7z") if 7z is not in PATH.

### Expected behavior
os.vrunv("7z") should work if 7z is installed/required by xmake.lua.

### Related Environment

Please provide compiling and running environment information:

- xmake version: 2.5.1
- os: Windows 10
- target platform: Windows x64

**Comment by waruqi** [comment]
you can try this first.

```lua
local 7z = find_tool("7z", {paths = path.join(os.programdir(), "winenv", "bin")})
os.execv(7z.program)
```

And I will improve it.

**Comment by waruqi** [comment]
I have improved it on dev branch.

```lua
import("lib.detect.find_tool")
local 7z = find_tool("7z")
if 7z then
    os.execv(7z.program, {"--help"})
end
```

**Comment by waruqi** [comment]
you can also use `add_requires("7z")/add_packages("7z")` to target.

xmake will use it first if find_tool can find it.
