### ISSUE TITLE
errors of mingw makefiles

### ISSUE THREAD

**Issue by wujilingfeng** [xmake-io/xmake#1210]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
   I ran commands like "xmake create -l c -P ./hello" to create a simple project;
then I ran commands like "xmake f -p mingw; xmake project -k makefile " to create MinGW Makfiles。
All commands above ran in Powershell。
   But when I ran "mingw32-make" in powershell  It throwed a error : " A subdirectory or file -p already exists "。
when I ran "mingw32-make" in git-bash it also throwed a error:"[makefile:26:build\mingw\x86_64\release\hello.ext] Error 1"。
   Because this code is simple,you can try it self.
### Expected behavior
   I want to get a correct MinGW Makfiles.

### Related Environment

- xmake version: 2.5.1
- os: windows
- target platform: mingw

**Comment by waruqi** [comment]
Currently does not support generating mingw makefile, maybe you need to wait for some time.

**Comment by wujilingfeng** [comment]
Will xmake of v2.5.2 support generating mingw makefile?Which will version support this function?

**Comment by waruqi** [comment]
Temporarily arrange it at 2.5.2, depending on my time to decide

Of course, I also welcome to submit pr directly.

**Comment by waruqi** [comment]
You can try 

```console
xmake f --toolchain=mingw -c --mingw=y:\llvm-mingw
xmake project -k make
mingw32-make.exe
```

It works for me. 

```console
C:\Users\ruki\Desktop\test2>xmake f --toolchain=mingw -c --mingw=y:\llvm-mingw
checking for platform ... windows
checking for architecture ... x64
checking for mingw directory ... y:\llvm-mingw

C:\Users\ruki\Desktop\test2>xmake project -k make
create ok!

C:\Users\ruki\Desktop\test2>y:\llvm-mingw\bin\mingw32-make.exe
compiling.release src\main.c
linking.release test2.exe
```
