### ISSUE TITLE
condition compile

### ISSUE THREAD

**Issue by wujilingfeng** [xmake-io/xmake#1211]
> Note: If it is a 'bug report' or 'feature request', please select the corresponding issue template, otherwise this issue will be not replied. 

### Describe the problem details
  I want to control  some targets. 
  For example,the xmake.lua will examine the value of "$(Demo)",if it equal "Enable",xmake will compile some targets,otherwise not.
  Can you  tell me how to accomplish it?

**Comment by waruqi** [comment]
`$(Demo)`? option? 

```lua
if has_config("demo") then
    add_defines("xxx")
end
```

**Comment by wujilingfeng** [comment]
I am not sure,Maybe run command "xmake f --Demo=Enable"

**Comment by wujilingfeng** [comment]
Thank you !
