### ISSUE TITLE
Expand variables ahead of time

### ISSUE THREAD

**Issue by wujilingfeng** [xmake-io/xmake#1212]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
  The code like "io.writefile("set.h","$(buildir)")" didn't run correctly,the content of set.h shows $(build).From the result,xmake didn't seem to expand variable ahead of time.
### Expected behavior
I expect that  content of this file is absolute path of current building directory.

### Related Environment

Please provide compiling and running environment information:

- xmake version:2.5.1
- os:windows
- target platform: mingw

**Comment by waruqi** [comment]
```lua
import("core.project.config")
io.writefile("set.h", config.buildir())
```

**Comment by wujilingfeng** [comment]
it's not absolute path

**Comment by waruqi** [comment]
io.writefile("set.h", path.absolute(config.buildir()))
