### ISSUE TITLE
can't input parameter

### ISSUE THREAD

**Issue by wujilingfeng** [xmake-io/xmake#1214]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
    When I run command:"xmake f --demo=y",there throws a erroe.

### Error output
error:Invalid option: --demo=yes

### Related Environment

- xmake version:2.5.1
- os:windows
- target platform: mingw

**Comment by waruqi** [comment]
see https://xmake.io/#/manual/configuration_option?id=optionset_showmenu
