### ISSUE TITLE
Version check has priority over commands

### ISSUE THREAD

**Issue by AntoineJT** [xmake-io/xmake#1219]
### Describe the bug

The version check has priority over commands passed to xmake.
I wanted to update in a folder where I have a xmake.lua file with
> set_xmakever("2.5.1")

![image](https://user-images.githubusercontent.com/26577763/106355233-f5c90180-62f6-11eb-8f4e-1e1c308f593b.png)

Then, in order to check if the bug is still there in the latest version, I updated and changed this line to
> set_xmakever("2.5.2")

![image](https://user-images.githubusercontent.com/26577763/106355457-4ab94780-62f8-11eb-9ea2-2068e37812c7.png)

The bug is still present.

### Expected behavior

The expected behavior would be to avoid any reading of the `xmake.lua` file while running the command `update`

### Error output

v2.3.9+202011250023
```quote
error: @programdir\core\project\project.lua:1064: xmake v2.3.9 < v2.5.1, please run `$xmake update` to upgrade xmake!
stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:787: in function 'raise'
        @programdir\core\project\project.lua:1064: in function 'tasks'
        @programdir\core\project\project.lua:1054: in function 'task'
        @programdir\core\main.lua:281: in function <@programdir\core\main.lua:219>
```

v2.5.1+202101210158
```quote
error: @programdir\core\project\project.lua:1070: xmake v2.5.1 < v2.5.2, please run `$xmake update` to upgrade xmake!
stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:787: in function 'raise'
        @programdir\core\project\project.lua:1070: in function 'tasks'
        @programdir\core\project\project.lua:1060: in function 'task'
        @programdir\core\main.lua:281: in function <@programdir\core\main.lua:219>
```

### Related Environment

Please provide compiling and running environment information:

- xmake version: v2.3.9+202011250023 + v2.5.1+202101210158
- os: Windows 10
- target platform: x64

### Additional context

This is clearly a tiny bug, which can be avoided by running `xmake update` in a folder containing no `xmake.lua` file, but it's better to know existing bugs even if fixing them is not a priority.

**Comment by SirLynix** [comment]
I second this.
I had this problem with a xmake.lua not supporting one of the new functions of xmake 2.5.1, and couldn't run update in that folder.

**Comment by waruqi** [comment]
I have fixed it.
