### ISSUE TITLE
linux xmake tbox console missing add_syslinks("pthread", "dl", "m", "c")

### ISSUE THREAD

**Issue by kenzanin** [xmake-io/xmake#1220]
### Describe the bug
iam try to create tbox based console app using command

`$ xmake xmake create -l c -t tbox.console tbox01`
and when i try 

```
$ xmake
checking for platform ... linux
checking for architecture ... x86_64
[ 25%]: ccache compiling.release src/main.c
[ 50%]: linking.release tbox02
error: /usr/bin/ld: /usr/local/lib/libtbox.a(mutex.c.o): in function `tb_mutex_entry_try_without_profiler':
mutex.c:(.text+0x5d): undefined reference to `pthread_mutex_trylock'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread.c.o): in function `tb_thread_init':
thread.c:(.text+0xe5): undefined reference to `pthread_attr_setstacksize'
/usr/bin/ld: thread.c:(.text+0x12e): undefined reference to `pthread_create'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread.c.o): in function `tb_thread_exit':
thread.c:(.text+0x1b4): undefined reference to `pthread_detach'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread.c.o): in function `tb_thread_wait':
thread.c:(.text+0x1f1): undefined reference to `pthread_join'
/usr/bin/ld: thread.c:(.text+0x206): undefined reference to `pthread_detach'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread.c.o): in function `tb_thread_setaffinity':
thread.c:(.text+0x2bc): undefined reference to `pthread_setaffinity_np'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread_local.c.o): in function `tb_thread_local_once':
thread_local.c:(.text+0x38): undefined reference to `pthread_key_create'
/usr/bin/ld: thread_local.c:(.text+0x4e): undefined reference to `pthread_key_create'
/usr/bin/ld: thread_local.c:(.text+0x5e): undefined reference to `pthread_key_delete'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread_local.c.o): in function `tb_thread_local_has':
thread_local.c:(.text+0x22a): undefined reference to `pthread_getspecific'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread_local.c.o): in function `tb_thread_local_exit':
thread_local.c:(.text+0x276): undefined reference to `pthread_key_delete'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread_local.c.o): in function `tb_thread_local_set':
thread_local.c:(.text+0x3b9): undefined reference to `pthread_setspecific'
/usr/bin/ld: thread_local.c:(.text+0x3d0): undefined reference to `pthread_setspecific'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread_local.c.o): in function `tb_thread_local_get':
thread_local.c:(.text+0x244): undefined reference to `pthread_getspecific'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread_local.c.o): in function `tb_thread_local_exit':
thread_local.c:(.text+0x281): undefined reference to `pthread_key_delete'
collect2: error: ld returned 1 exit status
```

### Expected behavior
clean build i guess

### Error output
) xmake -v -D
[ 50%]: linking.release tbox02
/usr/local/bin/g++ -o build/linux/x86_64/release/tbox02 build/.objs/tbox02/linux/x86_64/release/src/main.c.o -m64 -s -L/usr/local/lib -ltbox
error: @programdir/modules/private/async/runjobs.lua:217: @programdir/actions/build/kinds/binary.lua:73: @programdir/core/sandbox/modules/os.lua:258: /usr/bin/ld: /usr/local/lib/libtbox.a(mutex.c.o): in function `tb_mutex_entry_try_without_profiler':
mutex.c:(.text+0x5d): undefined reference to `pthread_mutex_trylock'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread.c.o): in function `tb_thread_init':
thread.c:(.text+0xe5): undefined reference to `pthread_attr_setstacksize'
/usr/bin/ld: thread.c:(.text+0x12e): undefined reference to `pthread_create'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread.c.o): in function `tb_thread_exit':
thread.c:(.text+0x1b4): undefined reference to `pthread_detach'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread.c.o): in function `tb_thread_wait':
thread.c:(.text+0x1f1): undefined reference to `pthread_join'
/usr/bin/ld: thread.c:(.text+0x206): undefined reference to `pthread_detach'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread.c.o): in function `tb_thread_setaffinity':
thread.c:(.text+0x2bc): undefined reference to `pthread_setaffinity_np'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread_local.c.o): in function `tb_thread_local_once':
thread_local.c:(.text+0x38): undefined reference to `pthread_key_create'
/usr/bin/ld: thread_local.c:(.text+0x4e): undefined reference to `pthread_key_create'
/usr/bin/ld: thread_local.c:(.text+0x5e): undefined reference to `pthread_key_delete'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread_local.c.o): in function `tb_thread_local_has':
thread_local.c:(.text+0x22a): undefined reference to `pthread_getspecific'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread_local.c.o): in function `tb_thread_local_exit':
thread_local.c:(.text+0x276): undefined reference to `pthread_key_delete'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread_local.c.o): in function `tb_thread_local_set':
thread_local.c:(.text+0x3b9): undefined reference to `pthread_setspecific'
/usr/bin/ld: thread_local.c:(.text+0x3d0): undefined reference to `pthread_setspecific'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread_local.c.o): in function `tb_thread_local_get':
thread_local.c:(.text+0x244): undefined reference to `pthread_getspecific'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread_local.c.o): in function `tb_thread_local_exit':
thread_local.c:(.text+0x281): undefined reference to `pthread_key_delete'
collect2: error: ld returned 1 exit status

stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:787]: in function 'raise'
    [@programdir/core/sandbox/modules/os.lua:258]: in function 'runv'
    [@programdir/modules/core/tools/gcc.lua:356]:
    [C]: in function 'link'
    [@programdir/actions/build/kinds/binary.lua:73]: in function 'callback'
    [@programdir/modules/core/project/depend.lua:186]: in function 'on_changed'
    [@programdir/actions/build/kinds/binary.lua:54]: in function '_do_link_target'
    [@programdir/actions/build/kinds/binary.lua:94]:
    [@programdir/actions/build/kinds/binary.lua:115]: in function '_link_target'
    [@programdir/actions/build/kinds/binary.lua:137]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:193]:
    [C]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [@programdir/modules/private/async/runjobs.lua:186]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:317]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:787: in function 'raise'
	@programdir/modules/private/async/runjobs.lua:217: in function 'catch'
	@programdir/core/sandbox/modules/try.lua:127: in function 'try'
	@programdir/modules/private/async/runjobs.lua:186: in function 'cotask'
	@programdir/core/base/scheduler.lua:317: in function <@programdir/core/base/scheduler.lua:315>
### Related Environment

Please provide compiling and running environment information:

- xmake version: xmake v2.5.1+202101301933, A cross-platform build utility based on Lua
- os: 
NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
LOGO=artixlinux
- target platform: native

### Additional context
it can build when i add 

add_syslinks("pthread", "dl", "m", "c")

into xmake.lua

thanks

**Comment by waruqi** [comment]
You can run `xmake repo -u` and re-install tbox again.

**Comment by kenzanin** [comment]
okey. i will try it

**Comment by kenzanin** [comment]
update tbox (https://github.com/tboox/tbox) + install
1. update my tbox git clone
2. xmake 
3. sudo xmake install
4. ok.

create new xmake tbox project
1. xmake create -l c -t tbox.console tbox03
2. cd tbox03
3. xmake
```checking for platform ... linux
checking for architecture ... x86_64
[ 25%]: ccache compiling.release src/main.c
[ 50%]: linking.release tbox03
error: /usr/bin/ld: /usr/local/lib/libtbox.a(mutex.c.o): in function `tb_mutex_entry_try_without_profiler':
mutex.c:(.text+0x5d): undefined reference to `pthread_mutex_trylock'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread.c.o): in function `tb_thread_init':
thread.c:(.text+0xe5): undefined reference to `pthread_attr_setstacksize'
/usr/bin/ld: thread.c:(.text+0x12e): undefined reference to `pthread_create'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread.c.o): in function `tb_thread_exit':
thread.c:(.text+0x1b4): undefined reference to `pthread_detach'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread.c.o): in function `tb_thread_wait':
thread.c:(.text+0x1f1): undefined reference to `pthread_join'
/usr/bin/ld: thread.c:(.text+0x206): undefined reference to `pthread_detach'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread.c.o): in function `tb_thread_setaffinity':
thread.c:(.text+0x2bc): undefined reference to `pthread_setaffinity_np'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread_local.c.o): in function `tb_thread_local_once':
thread_local.c:(.text+0x38): undefined reference to `pthread_key_create'
/usr/bin/ld: thread_local.c:(.text+0x4e): undefined reference to `pthread_key_create'
/usr/bin/ld: thread_local.c:(.text+0x5e): undefined reference to `pthread_key_delete'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread_local.c.o): in function `tb_thread_local_has':
thread_local.c:(.text+0x22a): undefined reference to `pthread_getspecific'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread_local.c.o): in function `tb_thread_local_exit':
thread_local.c:(.text+0x276): undefined reference to `pthread_key_delete'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread_local.c.o): in function `tb_thread_local_set':
thread_local.c:(.text+0x3b9): undefined reference to `pthread_setspecific'
/usr/bin/ld: thread_local.c:(.text+0x3d0): undefined reference to `pthread_setspecific'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread_local.c.o): in function `tb_thread_local_get':
thread_local.c:(.text+0x244): undefined reference to `pthread_getspecific'
/usr/bin/ld: /usr/local/lib/libtbox.a(thread_local.c.o): in function `tb_thread_local_exit':
thread_local.c:(.text+0x281): undefined reference to `pthread_key_delete'
collect2: error: ld returned 1 exit status```

xmake.lua content
) cat xmake.lua
set_xmakever("2.3.6")
set_warnings("all", "error")
set_languages("c99", "cxx11")
add_cxflags("-Wno-error=deprecated-declarations", "-fno-strict-aliasing")
add_mxflags("-Wno-error=deprecated-declarations", "-fno-strict-aliasing")

add_rules("mode.release", "mode.debug")
add_requires("tbox", {debug = is_mode("debug")})

if is_plat("windows") then
    if is_mode("release") then
        add_cxflags("-MT")
    elseif is_mode("debug") then
        add_cxflags("-MTd")
    end
    add_ldflags("-nodefaultlib:msvcrt.lib")
end

includes("src")

**Comment by waruqi** [comment]
```console
xmake repo -u
xmake require --uninstall tbox
xmake f -c
xmake
```
