### ISSUE TITLE
xmake cannot find a brew package which is not linked to /usr/local

### ISSUE THREAD

**Issue by wuzhiguocarter** [xmake-io/xmake#1221]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
```bash
(venv) ➜  route-ranker-broker git:(dev_workflow) ✗ xmake l find_package brew::openssl
nil
(venv) ➜  route-ranker-broker git:(dev_workflow) ✗ brew --prefix openssl
/usr/local/opt/openssl@1.1
```

### Expected behavior
```
/usr/local/opt/openssl@1.1
```
### Error output
```
nil
```
> If it is a xmake related compilation problem, please add the `-v -D` parameter and give the detailed compilation output information.
```bash
xmake l -vD find_package brew::openssl
running builtin module find_package with args:
dump from _print_vlog @@programdir/plugins/lua/main.lua:55
"brew::openssl"
dump from <anonymous> @@programdir/plugins/lua/main.lua:125
nil
```
### Related Environment

Please provide compiling and running environment information:

- xmake version: v2.3.9+202101171430
- os: Darwin Kernel Version 19.5.0: Thu Apr 30 18:25:59 PDT 2020; root:xnu-6153.121.1~7/RELEASE_X86_64 x86_64 i386 
- target platform: MacBookPro14,2 Darwin

### Additional context
None

**Comment by waruqi** [comment]
I have improved it, you can update to dev version and try it again. `xmake update -s dev`

**Comment by waruqi** [comment]
I have improved it, you can update to dev version and try it again. `xmake update -s dev`
