### ISSUE TITLE
关于xmake f --menu显示的菜单没有刷新的问题

### ISSUE THREAD

**Issue by wzc0066** [xmake-io/xmake#1222]
### Describe the bug
测试menu菜单的时候，经常出现的是之前其他测试工程下的菜单，而不是当前xmake.lua里面定义的option菜单。

复现过程：

1. 创建一个示例工程：xmake create -l c -P hello

增加两条Option选项：TEST1, TEST2

```bash
add_rules("mode.debug", "mode.release")

option("test1")
    set_default(false)
    set_showmenu(true)
    set_description("TEST1")

option("test2")
    set_default(false)
    set_showmenu(true)   			      
    set_description("TEST2")

target("hello")
    set_kind("binary")
    add_files("src/*.c")
```
然后执行：xmake f --menu， 选中两个选项后保存，然后xmake编译。

2. 在hello目录下，嵌套创建一个示例工程： xmake create -l c -P hello2

增加两条Option选项：TEST3, TEST4
```bash
add_rules("mode.debug", "mode.release")

option("test3")
    set_default(false)
    set_showmenu(true)
    set_description("TEST3")

option("test4")
    set_default(false)
    set_showmenu(true) 
    set_description("TEST4")                    

target("hello2")
    set_kind("binary")
    add_files("src/*.c")
```
然后执行：xmake f --menu， 看到的两个选项仍然是TEST1, TEST2，且是被选中的状态（即第一步保存的状态及选项值) ;
然后删除hello下的.xmake, 在hello2下xmake f --menu，看到的是未选中的TEST1, TEST2，相当于只是把保存的状态删除了。

说明：实际测试中遇到的这个问题，并不是在嵌套关系下出现的，只是不太好复现了。

### Related Environment

Please provide compiling and running environment information:

- xmake version: dev
- os: ubuntu20.04
- target platform: arm

**Comment by waruqi** [comment]
这个不是bug，目前就是这么设计的。。所有 子目录下工程，默认假定都是作为顶层 xmake.lua 所在目录的工程的子模块。。工作目录都是基于root 下的xmake.lua 。。类似 git 的方式，你随意在子目录下执行 xmake 行为都是跟 root 目录下一致。。

所以，你实际加载的还是root下的xmake.lua 。。

如果确实是子模块，那就 includes 关联子 xmake.lua ，将子 options 定义包含进来

如果子目录 可能跟 root 目录没有任何关系。。执行 xmake 命令的时候 就需要显式指定  `-P . ` 参数，强制作为独立子工程操作。。

```console
cd subdir
xmake -P .
xmake f -P . --menu
```

你执行的时候，其实有警告提示的。。

> warning: You are working in the project directory(/private/tmp/test7) and you can also
force to build in current directory via run `xmake -P .`
