### ISSUE TITLE
menu里面被依赖的选项即时刷新选中状态

### ISSUE THREAD

**Issue by wzc0066** [xmake-io/xmake#1223]
### Is your feature request related to a problem? Please describe.
option选项里面定义了deps依赖后，在执行xmake f --menu 设置时，无法及时看到被依赖选项的自动选中状态。

### Describe the solution you'd like
期望在某个选项被选中后，其所有依赖的选项也会即时刷新成选中状态。类似kernel的make menuconfig效果

**Comment by waruqi** [comment]
依赖的状态更新暂时支持不了，这块涉及现有架构问题，短期内不行，只能等之后有时间再看看了。。

**Comment by waruqi** [comment]
可以先暂时放置到 v2.5.3 到时候看情况
