### ISSUE TITLE
Fail to get the default value with winos.registry_query

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1227]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

使用`winos.registry_query`无法获取注册表key的default value

### 期待的结果

可以获取到default value

### 错误信息

```
> xmake l winos.registry_query "HKEY_LOCAL_MACHINE\SOFTWARE\NewKey;val"
"value"
> xmake l winos.registry_query "HKEY_LOCAL_MACHINE\SOFTWARE\NewKey"
error: get registry value size failed: HKEY_LOCAL_MACHINE\SOFTWARE\NewKey;(Default)
```
![image](https://user-images.githubusercontent.com/42310255/106575173-bdcff180-6576-11eb-8de4-153cb59864c6.png)

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.1
- xmake运行平台：windows
- xmake目标平台：windows

**Comment by waruqi** [comment]
可以了
