### ISSUE TITLE
使用io模块出现错误：attempt to index global 'io' (a nil value)

### ISSUE THREAD

**Issue by 18252580292** [xmake-io/xmake#1228]
这是我的脚本：
`set_xmakever("2.2.2")
set_project(xmakeexample)

os.dirs("./")
io.printf("hello")
target("xmake_library")
    set_kind("binary")
    add_files("$(projectdir)/*.cpp")
    add_links("pthread")`
大佬求帮助

**Comment by waruqi** [comment]
不要在描述域做复杂逻辑和io模块调用，请到脚本域使用。具体看文档：https://xmake.io/#/zh-cn/guide/syntax_description

**Comment by 18252580292** [comment]
> 不要在描述域做复杂逻辑和io模块调用，请到脚本域使用。具体看文档：https://xmake.io/#/zh-cn/guide/syntax_description

明白了，多谢大佬
