### ISSUE TITLE
stdin redirect & shlex support

### ISSUE THREAD

**Issue by TitanSnow** [xmake-io/xmake#123]
Only stdout & stderr could be redirected. The redirection of stdin of spawned process is also needed

Shlex support wanted

```lua
os.run("prog < infile > outfile")
os.run("prog1 < infile | prog2 > outfile")
os.piperun("gcc -xc -"):write("#include...")
print(os.piperun("cat"):write("awd"):read())

**Comment by waruqi** [comment]
It's a little bit of a hassle to implement it, and I'll implement it after I finished other more important features.

**Comment by waruqi** [comment]
Supports a subset of a shell command. for example:
 
```bash
os.run("./configure; make; make install")
os.run("make && make install")
```

**Comment by waruqi** [comment]
@TitanSnow A temporary approach, but not cross-platform.

```lua
os.run("sh -c 'prog < infile > outfile'")
os.run("sh -c 'prog1 < infile | prog2 > outfile'")
os.exec("sh -c 'echo hello xmake | grep xmake -o'")
```

**Comment by TitanSnow** [comment]
There is [a module](https://github.com/python/cpython/blob/master/Lib/shlex.py) in python to parse shell syntax. You could have a look

**Comment by waruqi** [comment]
Ok, I will look at it. Thanks!
