### ISSUE TITLE
在xmake.lua里面的设置无法传递到 Basic Configuration里面去

### ISSUE THREAD

**Issue by wzc0066** [xmake-io/xmake#1230]
### Describe the bug
Basic Configuration里面的一些设置，如plat, arch, toolchain名称等选项值，对于特定的项目都是固定的。
如果能在xmake.lua里面进行默认值设置，就可以不用在 xmake f --menu时候手动设置了，可极大简化用户操作流程，提升用户体验。

### Related Environment

Please provide compiling and running environment information:

- xmake version: dev
- os: ubuntu20.04
- target platform: arm

**Comment by waruqi** [comment]
这块线下已通过定制任务的方式解决
