### ISSUE TITLE
XMake 在windows 10 下, update 指令无效

### ISSUE THREAD

**Issue by 1-erick-zhang** [xmake-io/xmake#1232]
### 描述问题

windows 10 下 xmake update 无效, xmake 忽略了update 指令.
![xmake_update](https://user-images.githubusercontent.com/62749050/106959092-fad3e980-6718-11eb-8e39-ef70e2a4f927.png)

### 期待的结果

希望能快点修复此bug

### 错误信息

>C:\Users\User>xmake update
>error: file(C:\Users\User\xmake.lua): file not found!

### 相关环境

- xmake版本：2.5.1
- xmake运行平台：Windows 10 专业版 Insider Preview 2004
- xmake目标平台：无

### 其他信息

这个问题不存在于 deepin 20.1 社区版
![xmake_update_in_deepin](https://user-images.githubusercontent.com/62749050/106959564-97968700-6719-11eb-8085-f4839d38aae5.png)

xmake 忽略了 update 指令, 而是直接寻找 xmake.lua 文件.

## 其它情况

如果目录下有 xmake.lua 就会显示下面的信息:
![xmake_other](https://user-images.githubusercontent.com/62749050/106963404-4d180900-671f-11eb-83aa-0db0dcf27472.png)

**Comment by waruqi** [comment]
请到非工程目录下执行update 

这个问题 dwv上已修复，见 https://github.com/xmake-io/xmake/issues/1219

**Comment by 1-erick-zhang** [comment]
windows 下我就在非工程目录

**Comment by 1-erick-zhang** [comment]
C:\Users\User :

![x](https://user-images.githubusercontent.com/62749050/106965686-bbaa9600-6722-11eb-9c11-67c79af4321f.png)

**Comment by waruqi** [comment]
从releases里面下载 xmake-master.exe安装下再试试

**Comment by 1-erick-zhang** [comment]
我已经重装了.
XMake 在 任何目录下都可以卸载.
XMake 在 C:\WINDOWS\system32 可以正常更新.

重装前:
![屏幕截图 2021-02-04 202802](https://user-images.githubusercontent.com/62749050/106968703-214d5100-6728-11eb-92c1-62f78d3255bd.png)

重装后:
![屏幕截图 2021-02-04 202927](https://user-images.githubusercontent.com/62749050/106968641-02e75580-6728-11eb-9bd0-7c29261c9280.png)

**Comment by waruqi** [comment]
我回头看下

**Comment by waruqi** [comment]
我这里正常 无法复现你的问题，你可以执行下 xmake update -vD 给我看下栈信息

**Comment by 1-erick-zhang** [comment]
```
pinging for the host(gitlab.com) ... 131 ms
pinging for the host(github.com) ... 148 ms
pinging for the host(gitee.com) ... 394 ms
error: @programdir\core\main.lua:290: @programdir\core\project\project.lua:1002: file(C:\Users\User\xmake.lua): file not found!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:787]: in function 'raise'
    [@programdir\core\project\project.lua:1002]: in function 'requires_str'
    [@programdir\core\project\project.lua:1020]: in function 'requireconfs_str'
    [@programdir\actions\require\impl\package.lua:372]: in function '_merge_requireinfo'
    [@programdir\actions\require\impl\package.lua:497]: in function '_load_package'
    [@programdir\actions\require\impl\package.lua:597]: in function '_load_packages'
    [@programdir\actions\require\impl\package.lua:934]: in function 'load_packages'
    [@programdir\actions\require\impl\package.lua:951]: in function 'install_packages'
    [@programdir\actions\require\impl\environment.lua:51]: in function 'enter'
    [@programdir\actions\update\main.lua:293]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:519]: in function 'run'
    [@programdir\core\main.lua:288]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:787: in function 'raise'
        @programdir\core\main.lua:290: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>
```

**Comment by waruqi** [comment]
你这跑的还是老版本 master版本没生效 你看下path 是不是装了两个版本 一个32bits的 一个64bits的 分别装到不同目录了 然后path指向的还是老的版本

**Comment by 1-erick-zhang** [comment]
我用 Everything 搜索了, 只有一个 xmake.exe

**Comment by waruqi** [comment]
>     [@programdir\actions\require\impl\package.lua:372]: in function '_merge_requireinfo'

你可以到自己安装目录下看下，对应位置的lua脚本，package:.lua 372 行 应该是个 return ，这里 master 上我已经修复过得，但是你这还是会调用到下面的 project.requireconfs_str() 里面去，明显还是老的脚本。

https://github.com/xmake-io/xmake/blob/a3a58f8dbc6a6cbfc5a2ece6b2b5c56a24408297/xmake/actions/require/impl/package.lua#L368-L373

**Comment by 1-erick-zhang** [comment]
好吧, 明天我起来的时候再重新配置, 我这里晚上了

**Comment by 1-erick-zhang** [comment]
我下了源码, \actions\require\impl\package.lua:372 方法时这样的:
```lua
function _merge_requireinfo(requireinfo, requirepath)

    -- find requireconf from the given requirepath
    local requireconf_result = {}
    local requireconfs, requireconfs_extra = project.requireconfs_str()
    if requireconfs then
        for _, requireconf in ipairs(requireconfs) do
            if _match_requirepath(requirepath, requireconf) then
                local requireconf_extra = requireconfs_extra[requireconf]
                table.insert(requireconf_result, {requireconf = requireconf, requireconf_extra = requireconf_extra})
            end
        end
    end

    -- append requireconf_extra into requireinfo
    -- and the configs of add_requires have a higher priority than add_requireconfs.
    --
    -- e.g.
    -- add_requireconfs("*", {configs = {debug = false}})
    -- add_requires("foo", "bar", {configs = {debug = true}})
    --
    -- foo and bar will be debug mode
    --
    -- we can also override the configs of add_requires
    --
    -- e.g.
    -- add_requires("zlib 1.2.11")
    -- add_requireconfs("zlib", {override = true, version = "1.2.10"})
    --
    -- we override the version of zlib to 1.2.10
    --
    if #requireconf_result == 1 then
        local requireconf_extra = requireconf_result[1].requireconf_extra
        if requireconf_extra then
            -- preprocess requireconf_extra, (debug, override ..)
            local override = requireconf_extra.override
            requireconf_extra.override = nil
            if requireconf_extra.debug then
                requireconf_extra.configs = requireconf_extra.configs or {}
                requireconf_extra.configs.debug = true
                requireconf_extra.debug = nil
            end
            -- append or override configs and extra options
            for k, v in pairs(requireconf_extra.configs) do
                requireinfo.configs = requireinfo.configs or {}
                if override or requireinfo.configs[k] == nil then
                    requireinfo.configs[k] = v
                end
            end
            for k, v in pairs(requireconf_extra) do
                if k ~= "configs" then
                    if override or requireinfo[k] == nil then
                        requireinfo[k] = v
                    end
                end
            end
        end
    elseif #requireconf_result > 1 then
        local confs = {}
        for _, item in ipairs(requireconf_result) do
            table.insert(confs, item.requireconf)
        end
        raise("package(%s) will match multiple add_requireconfs(%s)!", requirepath, table.concat(confs, " "))
    end
end
```

![x](https://user-images.githubusercontent.com/62749050/107016789-1d97e980-677d-11eb-875f-40030d6f6a85.png)
版本 2.5.1

安装步骤:

![x](https://user-images.githubusercontent.com/62749050/107016974-589a1d00-677d-11eb-9a7a-31a68bd551ba.png)

之前使用 xmake-v2.5.1.win64.exe 下载的:

![x](https://user-images.githubusercontent.com/62749050/107017177-91d28d00-677d-11eb-9ebb-7334d349fab8.png)

源码 xmake-2.5.1.zip:

![x](https://user-images.githubusercontent.com/62749050/107017327-bc244a80-677d-11eb-9d33-1477f5475b3c.png)
链接: https://codeload.github.com/xmake-io/xmake/zip/v2.5.1

**Comment by waruqi** [comment]
> 我下了源码, \actions\require\impl\package.lua:372 方法时这样的:

你这个还是老版本哈。。我是让你下载 master 版本测试，也就是 master 分支的最新提交版本（还没发版），不是 2.5.1线上版本。。


> 从releases里面下载 xmake-master.exe安装下再试试

https://github.com/xmake-io/xmake/releases/download/v2.5.1/xmake-master.win64.exe

![image](https://user-images.githubusercontent.com/151335/107018514-7eeea580-67db-11eb-8c02-f1e4183d94a7.png)


dev分支的版本也可以，别弄错了

**Comment by 1-erick-zhang** [comment]
![x](https://user-images.githubusercontent.com/62749050/107018985-e4ad4400-677f-11eb-85bc-9c9b56b200c9.png)
这样对了吧

**Comment by waruqi** [comment]
对了 你在update一边试试呢 git能找到不

**Comment by 1-erick-zhang** [comment]
![x](https://user-images.githubusercontent.com/62749050/107021270-b11fe900-6782-11eb-9301-2220480243a6.png)

**Comment by waruqi** [comment]
那可以了。已经更新了。。git 那个暂时不用管，首次装完git 可能有些case没立即绑定环境，所以后面的执行失败了，下次重新 update 就好了。。回头我可以改进下

**Comment by 1-erick-zhang** [comment]
谢谢了
