### ISSUE TITLE
XMake 在 target 作用域提供 get_xxx 方法

### ISSUE THREAD

**Issue by 1-erick-zhang** [xmake-io/xmake#1233]
### 你在什么场景下需要该功能？

比如在 debug 模式设置库的后缀.
```lua
target("demo"
    set_kind("static")
    
    if is_mode("debug")
    then
        set_basename(get_target_name().."d") -- 或者 target_name() 或者 $(target_name) 或者 target:name()
    end
```

### 描述可能的解决方案

提供 get_xxx 或者 xxx.
比如:
```lua
-- kind
get_kind()
target:kind()
kind()
-- target name
get_target_name()
target:name()
target_name()
```

### 描述你认为的候选方案

提供 get_xxx 或者 xxx 或者 get(name) 或者 $(kind).
比如:
```lua
-- kind
get_kind()
kind()
get("kind")
target:kind()
$(kind)
-- target name
get_target_name()
target_name()
get("target_name")
target:name()
$(target_name)
```

### 其他信息

如果项目的某些核心信息改变了(如 target name)需要改变的地方就会少很多.

**Comment by waruqi** [comment]
暂时不考虑，target("xxx")定义的时候原本就知道没必要还去获取

另外，描述域配置还没执行全，get实际过早，存在鸡生蛋问题，无法实现

请到on_load里面处理 get

**Comment by 1-erick-zhang** [comment]
那么有没有考虑在脚本域添加 target:get_xxx 或者 target:xxx.
比如:
```lua
on_load(
    function (target)
        print(target:kind())
    end
)
```

这样写比 target:get("kind") 方便点

**Comment by waruqi** [comment]
> 
> 这样写比 target:get("kind") 方便点

原本就支持 你试了就知道了

**Comment by 1-erick-zhang** [comment]
![x](https://user-images.githubusercontent.com/62749050/107132082-e0397600-68ba-11eb-8add-acc623bcf5e6.png)
可能是我写错了吧

**Comment by waruqi** [comment]
target:get("kind") 你不是说get么

**Comment by 1-erick-zhang** [comment]
那能考虑添加 target:kind() 等等的方法吗? 这样方便点

**Comment by 1-erick-zhang** [comment]
我找到一种可以达到 target:get("kind") 效果的方法, target:targetkind(), 我在 /XMake/core/project/target.lua 添加了 kind 和 get_kind 方法.

```lua
function _instance:kind()
    return self:targetkind()
end

function _instance:get_kind()
    return self:targetkind()
end
```

这样就支持了

**Comment by waruqi** [comment]
不是说了么 你直接用 target:get("kind") 不就好了，target的所有设置 直接 target:get("xxx") 都能取到 为啥还要这么折腾下呢？

**Comment by 1-erick-zhang** [comment]
我说了 target:kind() 对于我来说方便点而已, 这种代码风格我比较喜欢点, 当然我还是会用 target:get("kind").

**Comment by waruqi** [comment]
> 我说了 target:kind() 对于我来说方便点而已, 这种代码风格我比较喜欢点, 当然我还是会用 target:get("kind").

如果有强迫症，那也没办法，这个随你吧，你可以自己fork后改个定制版。尽管 target:targetkind() 也可以直接用。。

**Comment by 1-erick-zhang** [comment]
好的👌
