### ISSUE TITLE
xmake project -k cmake 生成的 CMakeLists.txt, 不支持 C++ modules

### ISSUE THREAD

**Issue by 1-erick-zhang** [xmake-io/xmake#1234]
### 你在什么场景下需要该功能？

有些场景下需要用 cmake 编译, 可是 xmake project -k cmake 生成的 CMakeLists.txt, 不支持 C++ modules.

![x](https://user-images.githubusercontent.com/62749050/107158444-c48ca900-6968-11eb-97be-532dd58a332e.png)

错误信息显示 并没有编译 hello.mpp

### 描述可能的解决方案

XMake 添加支持 C++ modules 的代码 到 CMakeLists.txt

### 描述你认为的候选方案

可以添加一个导入 C++ modules 的函数.

### 其他信息

```cmake

# 可能的函数
function (add_cxx_modules target files)
...
endfunction ()

# 添加模块
add_cxx_modules(target hello.mpp)

```

**Comment by waruqi** [comment]
cmake支持c++module了？我之前测试这个  从来没成功过

**Comment by 1-erick-zhang** [comment]
也就是说 cmake 暂时没有办法支持 C++ modules?

**Comment by waruqi** [comment]
在我印象中 cmake从来就没支持过 你可以测试下

**Comment by 1-erick-zhang** [comment]
好吧, 原生的 cmake 确实不支持, 但是我记得可以通过给特定编译器某些参数让 cmake 支持 C++ modules.
我找到的一个文章: https://stackoverflow.com/questions/57300495/how-to-use-c20-modules-with-cmake

**Comment by waruqi** [comment]
直接传cflags ldflags直接给编译器 当然可以 makefile也可以 只要编译器支持

关键还有其他逻辑是需要构建工具辅助处理的，比如构建顺序，modules的构建要提前预编译，在所有cpp编译之前，还有modules之间如果有import依赖，还要分析modules里面源码，提取依赖关系构建图来整理整个构建流程，还需考虑并行编译的支持，只不是单纯生成一个cmakelist加上cflags ldflags就能搞定的

当然搞搞简单的c++ modules demo当然没问题，要做到通用，高效率，并行编译支持，只有让cmake原生支持，这也就是为啥cmake现在还不支持的原因，细节处理的东西很多，很复杂

xmake目前也都只是初步支持，还有很多东西需要进一步优化改进，没那么简单

**Comment by 1-erick-zhang** [comment]
抱歉, 我还是想的太简单了
