### ISSUE TITLE
xmake project -k vsxmake 生成的vs项目没有包含 mainwindow.ui

### ISSUE THREAD

**Issue by 1-erick-zhang** [xmake-io/xmake#1237]
### 描述问题

xmake.lua
![屏幕截图 2021-02-09 074235](https://user-images.githubusercontent.com/62749050/107352528-b5ae0f80-6aaa-11eb-8a36-01a5bbe5ebfc.png)

![屏幕截图 2021-02-09 074212](https://user-images.githubusercontent.com/62749050/107352436-97481400-6aaa-11eb-8994-1d4342c36d58.png)
生成结果, 并没有包含 mainwindow.ui

### 期待的结果

自动将 mainwindow.ui 包含到项目

### 错误信息

没包含 mainwindow.ui

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.1
- xmake运行平台：windows 10
- xmake目标平台：无

### 其他信息

xmake create -l c++ -t qt.widgetapp
xmake project -k vsxmake
打开 .sln 文件

**Comment by waruqi** [comment]
回头会加上支持

**Comment by 1-erick-zhang** [comment]
好的👌

**Comment by waruqi** [comment]
我加上了，dev分支
