### ISSUE TITLE
generate IDE project files plugin

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#124]
- [x] Makefile (linux/macosx/mingw/cygwin)
  - `$ xmake project -k makefile`
- [x] Visual Studio IDE Project
  - [x] vs2003 - vs2008  
    - `$ xmake project -k vs2008`
  - [x] vs2010 - vs2019
    - `$ xmake project -k vs2017 -m "debug,release"`
- [x] Visual Studio IDE Project (Wrap xmake command https://github.com/xmake-io/xmake/pull/472)
  - [x] vs2010 - vs2019
    - `$ xmake project -k vsxmake2017 -m "debug;release"`
- [x] Compilation Databases (clang-based tools)
  - `$ xmake project -k compile_commands`
  - `$ xmake project -k compile_flags`
- [ ] Xcode IDE Project
  - `$ xmake project -k xcode`
- [ ] Code::Blocks IDE Project
  - `$ xmake project -k codeblocks`
- [x] Ninja 
  - `$ xmake project -k ninja`
- [x] CMake Project
 - `$ xmake project -k cmakelists`

**Comment by waruqi** [comment]
see [#179](https://github.com/tboox/xmake/issues/179)

**Comment by OpportunityLiu** [comment]
see #472

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/issues/627

**Comment by waruqi** [comment]
这里先close了，反正大部分都支持了，ninja最近也加上了，cmake的最近也稍微完善了下，xcode的工程等以后有时间了再说吧，可以在 #627 上跟进，codeblocks我暂时不打算搞了，如果有人感兴趣，可以帮忙贡献下。
