### ISSUE TITLE
Library ordering with multiple dependencies

### ISSUE THREAD

**Issue by cmeerw** [xmake-io/xmake#1240]
### Describe the bug

somewhat related to issue #1091, but this time having multiple targets depend on a single library

### Expected behavior

consider the following xmake.lua:

```
option("foo")
    add_linkdirs(".")
    add_links("foo")

target("test1")
    set_kind("static")
    add_options("foo")
    add_files("test1.cpp")

target("test2")
    set_kind("static")
    add_options("foo")
    add_files("test2.cpp")

target("test")
    set_kind("binary")

    add_deps("test1")
    add_deps("test2")
    add_files("test.cpp")
```

I would expect the final link line be similar to (`foo` appearing last as both `test1` and `test2` depend on it):

```
/usr/bin/g++ -o build/linux/x86_64/release/test build/.objs/test/linux/x86_64/release/test.cpp.o -m64 -Lbuild/linux/x86_64/release -L. -ltest2 -ltest1 -lfoo
```

but instead it is:

```
/usr/bin/g++ -o build/linux/x86_64/release/test build/.objs/test/linux/x86_64/release/test.cpp.o -m64 -Lbuild/linux/x86_64/release -L. -ltest2 -lfoo -ltest1
```

### Related Environment

xmake 2.5.1 on Ubuntu 20.10

### Additional context

at least with gcc this can result in unresolved symbols as only those symbols from libfoo.a will be included that are used in test2, but not those from test1

**Comment by waruqi** [comment]
ok, I will look at it in the next few days. please wait a while, I am working on other issues.

**Comment by yamashi** [comment]
I am also hitting this issue.

> /usr/bin/g++ -o build/linux/x64/release/FalloutTogetherServer build/.objs/FalloutTogetherServer/linux/x64/release/code/server/Components/ModsComponent.cpp.o build/.objs/FalloutTogetherServer/linux/x64/release/code/server/GameServer.cpp.o build/.objs/FalloutTogetherServer/linux/x64/release/code/server/main.cpp.o build/.objs/FalloutTogetherServer/linux/x64/release/code/server/Scripts/Base.cpp.o build/.objs/FalloutTogetherServer/linux/x64/release/code/server/Scripts/EntityHandle.cpp.o build/.objs/FalloutTogetherServer/linux/x64/release/code/server/Scripts/Npc.cpp.o build/.objs/FalloutTogetherServer/linux/x64/release/code/server/Scripts/Party.cpp.o build/.objs/FalloutTogetherServer/linux/x64/release/code/server/Scripts/Player.cpp.o build/.objs/FalloutTogetherServer/linux/x64/release/code/server/Scripts/Quest.cpp.o build/.objs/FalloutTogetherServer/linux/x64/release/code/server/Services/ActorService.cpp.o build/.objs/FalloutTogetherServer/linux/x64/release/code/server/Services/CharacterService.cpp.o build/.objs/FalloutTogetherServer/linux/x64/release/code/server/Services/EnvironmentService.cpp.o build/.objs/FalloutTogetherServer/linux/x64/release/code/server/Services/PartyService.cpp.o build/.objs/FalloutTogetherServer/linux/x64/release/code/server/Services/PlayerService.cpp.o build/.objs/FalloutTogetherServer/linux/x64/release/code/server/Services/QuestService.cpp.o build/.objs/FalloutTogetherServer/linux/x64/release/code/server/Services/ScriptService.cpp.o build/.objs/FalloutTogetherServer/linux/x64/release/code/server/Services/ServerListService.cpp.o build/.objs/FalloutTogetherServer/linux/x64/release/code/server/stdafx.cpp.o build/.objs/FalloutTogetherServer/linux/x64/release/code/server/World.cpp.o -m64 -Lbuild/linux/x64/release -L/home/yamashi/.xmake/packages/t/tiltedcore/v0.2.1/01bb37aefda949499611fc3dbf88e235/lib -L/home/yamashi/.xmake/packages/m/mimalloc/1.7.0/007561a80bd944ab9959f1b48e1e79e6/lib -L/home/yamashi/.xmake/packages/s/snappy/1.1.8/c4aaa2e149e549bca1dc84d16dbd682a/lib -L/home/yamashi/.xmake/packages/g/gamenetworkingsockets/v1.2.0/01bb37aefda949499611fc3dbf88e235/lib -L/home/yamashi/.xmake/packages/p/protobuf-cpp/3.14.0/01bb37aefda949499611fc3dbf88e235/lib -L/home/yamashi/.xmake/packages/o/openssl/1.1.1h/01bb37aefda949499611fc3dbf88e235/lib -L/home/yamashi/.xmake/packages/s/sqlite3/3.34.0+100/01bb37aefda949499611fc3dbf88e235/lib -L/home/yamashi/.xmake/packages/l/lua/v5.4.2/01bb37aefda949499611fc3dbf88e235/lib -s **-lTiltedConnect -lTiltedCore -lmimalloc -lsnappy -lgamenetworkingsockets -lprotobuf -lssl -lcrypto -lTiltedScript -lsqlite3 -llua -lCommon -lFalloutEncoding -lpthread -ldl -lm**

As can be seen in the last lines -lTiltedCore is linked before -lTiltedScript which depends on it causing linker errors:
> error: build/linux/x64/release/libTiltedScript.a(NetRPCs.cpp.o): In function `NetRPCs::Call::Serialize(TiltedPhoques::Buffer::Writer&) const':
NetRPCs.cpp:(.text+0x24c0): undefined reference to `TiltedPhoques::Serialization::WriteVarInt(TiltedPhoques::Buffer::Writer&, unsigned long)'
NetRPCs.cpp:(.text+0x24e4): undefined reference to `TiltedPhoques::Serialization::WriteVarInt(TiltedPhoques::Buffer::Writer&, unsigned long)'

**Comment by waruqi** [comment]
> -ltest2 -lfoo -ltest1

This is a problem caused by the internal deduplication algorithm, `-ltest2 -lfoo -ltest1 -lfoo` -> `-ltest2 -lfoo -ltest1` (after deduplication)

> -lTiltedConnect -lTiltedCore -lmimalloc -lsnappy -lgamenetworkingsockets -lprotobuf -lssl -lcrypto -lTiltedScript -lsqlite3 -llua -lCommon -lFalloutEncoding -lpthread -ldl -lm

same problem in https://github.com/tiltedphoques/TiltedOnline/blob/f389caac97145f71ab39ed429b9d3211e15c7604/Code/server/xmake.lua

```lua
    add_deps(
        "Common",
        "TiltedScript", --  add_packages("tiltedcore")
        "TiltedConnect")
    add_packages(
        "gamenetworkingsockets",
        "spdlog",
        "hopscotch-map",
        "sqlite3",
        "lua",
        "sol2",
        "glm",
        "entt",
        "tiltedcore")
```

`-lTiltedCore -lTiltedScript -llTiltedCore` -> `-lTiltedCore -lTiltedScript`

Now I adjusted deduplication order in dev branch.

new result is

`-lTiltedCore -lTiltedScript -llTiltedCore` -> `-lTiltedScript -lTiltedCore`
`-ltest2 -lfoo -ltest1 -lfoo` -> `-ltest2 -ltest1 -lfoo`

You can update to dev branch and try it again @yamashi @cmeerw 

In addition, about TiltedOnline issue, I will improve add_packages to support `{public = true}` so that the target directly inherits the packages in the dependent target.

This will better solve this problem, because there will be no duplicate links.

related issue, https://github.com/xmake-io/xmake/issues/1109 

And this is also the last few issues of 2.5.2, I will support it in the next few days,

**Comment by waruqi** [comment]
I have fixed it on dev branch.

**Comment by waruqi** [comment]
Now we can sort links better. https://github.com/xmake-io/xmake/issues/1452#issuecomment-1741152822
