### ISSUE TITLE
Add Support for windows .manifest files through the add_files interface.

### ISSUE THREAD

**Issue by Force67** [xmake-io/xmake#1241]
Windows .manifest files should be supported through the add_files interface, similar to how .rc files are handeled.

**Comment by waruqi** [comment]
I think you can use add_ldflags directly. `add_ldflags("/manifest", "/ManifestFile:\"xxx.manifest\"")`

**Comment by waruqi** [comment]
Can you provide a demo project with manifest file?

**Comment by Force67** [comment]
https://github.com/Force67/TiltedOnline/tree/launcherino/Code/launcher, currently i'm the manifest through https://github.com/Force67/TiltedOnline/blob/launcherino/Code/launcher/launcher.rc#L30

**Comment by waruqi** [comment]
I have supported it. https://github.com/xmake-io/xmake/blob/dev/tests/projects/c++/manifest/xmake.lua

```lua
add_rules("mode.debug", "mode.release")
target("test")
    set_kind("binary")
    add_files("src/*.cpp")
    add_files("src/*.manifest")
```
