### ISSUE TITLE
配置选项 option 使用内置变量$(scriptdir) 无效

### ISSUE THREAD

**Issue by nick908** [xmake-io/xmake#1244]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题
**xmake.lua**
option("quc")
    set_showmenu(true)
    add_links("quc") 
    add_linkdirs("lib/linux")
    add_includedirs("inc") 
    -- add_rpathdirs("$(scriptdir)/lib/linux")
    add_rpathdirs("/home/linaro/UpperSoftware/packages/quc.pkg/lib/linux"

$(scriptdir)无法得到当前option定义的xmake.lua的绝对路径

### 期待的结果

使用option作为本地包，需要设置动态链接库的路径时，需要得到option所在xmake.lua的绝对路径

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：xmake v2.5.1+202102151338, A cross-platform build utility based on Lua
- xmake运行平台：linux
- xmake目标平台：

**Comment by waruqi** [comment]
dev版本我加上了，但是还没时间测试，你先试试

**Comment by nick908** [comment]
> dev版本我加上了，但是还没时间测试，你先试试

已经正常了，谢谢

**Comment by terrywh** [comment]
```
set_showmenu(true)
set_default("$(scriptdir)") 
```
会报错：
```
error: @programdir/core/sandbox/sandbox.lua:326: bad argument #1 to 'getfenv' (invalid level)
stack traceback:
        [C]: in function 'getfenv'
        @programdir/core/sandbox/sandbox.lua:326: in function 'instance'
        @programdir/core/sandbox/modules/os.lua:226: in function 'result'
        @programdir/core/base/task.lua:212: in function 'handler'
        @programdir/core/base/filter.lua:136: in function 'get'
        @programdir/core/base/filter.lua:180: in function <@programdir/core/base/filter.lua:174>
        [C]: in function 'gsub'
        @programdir/core/base/filter.lua:174: in function 'handle'
        @programdir/core/base/task.lua:124: in function '_translate_menu'
        @programdir/core/base/task.lua:483: in function 'taskmenu'
        @programdir/core/base/option.lua:358: in function 'taskmenu'
        @programdir/core/base/option.lua:151: in function 'init'
        @programdir/core/main.lua:243: in function <@programdir/core/main.lua:222>
```
@nick908

**Comment by waruqi** [comment]
> 版本：v2.5.3
> 
> ```
> set_showmenu(true)
> set_default("$(scriptdir)") 
> ```
> 
> 会报错：
> 
> ```
> error: @programdir/core/sandbox/sandbox.lua:326: bad argument #1 to 'getfenv' (invalid level)
> stack traceback:
>         [C]: in function 'getfenv'
>         @programdir/core/sandbox/sandbox.lua:326: in function 'instance'
>         @programdir/core/sandbox/modules/os.lua:226: in function 'result'
>         @programdir/core/base/task.lua:212: in function 'handler'
>         @programdir/core/base/filter.lua:136: in function 'get'
>         @programdir/core/base/filter.lua:180: in function <@programdir/core/base/filter.lua:174>
>         [C]: in function 'gsub'
>         @programdir/core/base/filter.lua:174: in function 'handle'
>         @programdir/core/base/task.lua:124: in function '_translate_menu'
>         @programdir/core/base/task.lua:483: in function 'taskmenu'
>         @programdir/core/base/option.lua:358: in function 'taskmenu'
>         @programdir/core/base/option.lua:151: in function 'init'
>         @programdir/core/main.lua:243: in function <@programdir/core/main.lua:222>
> ```
> 
> @nick908 @waruqi

option/default 里面的内置变量 会过早转义（因为要在 help 中展示），目前没办法支持内置变量，即使我压制错误也只能返回 空值，也是不对的。。。理论上要支持也是可以的，就是改起来很麻烦，暂时我就不动了。。


所以不要在 set_default 里面 使用 内置变量，如果你要传入 scriptdir 作为 default 值，可以这么写

`set_default(os.scriptidr())`
