### ISSUE TITLE
Support startproject for visual studio solutions.

### ISSUE THREAD

**Issue by Force67** [xmake-io/xmake#1249]
Add a way to set the 'startproject' for visual studio based solutions. This allows us to directly debug the startproject without having to set it through solution explorer.

Premake5 implementation as reference:
https://github.com/premake/premake-core/blob/master/modules/vstudio/vs2005_solution.lua#L72

**Comment by waruqi** [comment]
I have supported it. you can set default startproject use `set_default(true)`

```lua
target("test")
    set_default(true)
```

Although the targets without explicitly setting `set_default(true)` are also the default build targets, they will not be set as the startup project.

If default=true is not set, xmake will give priority to using binary kind as the startup project.
