### ISSUE TITLE
Include Path with spaces and backslashes is not found on windows

### ISSUE THREAD

**Issue by PucklaMotzer09** [xmake-io/xmake#1252]
### Describe the bug
I want to use the Kinect SDK and its include files and libraries are inside this folder: ```C:\Program Files\Microsoft SDKs\Kinect\v2.0_1409\inc``` and ```C:\Program Files\Microsoft SDKs\Kinect\v2.0_1409\Lib\x64```. xmake invokes the compiler using this flags: ```"-I\"C:\\\\Program Files\\\\Microsoft SDKs\\\\Kinect\\\\v2.0_1409\\\\inc\""```. This leads to the compiler not finding the path.

### Expected behavior
The compiler should be able to find the path. VS Code is able to find the path using the *compile_commands* and xmake itself doesn't even output a warning for not finding the path. This path worked in an earlier version of xmake.

### Related Environment

Please provide compiling and running environment information:

- xmake version: v2.5.1+202101210158
- os: Windows 10
- target platform: Windows 10

### Additional context
I tried to invoke the compiler manually. And by just changes the include path flag to this: ```"-IC:\\\\Program Files\\\\Microsoft SDKs\\\\Kinect\\\\v2.0_1409\\\\inc"``` it worked fine without any errors or warnings.

**Comment by waruqi** [comment]
Can you try dev/master version? I fixed this issue. see https://github.com/xmake-io/xmake/issues/1235

**Comment by PucklaMotzer09** [comment]
Sorry I didn't check for other issues. I updated xmake and now it runs fine. Good Job!
