### ISSUE TITLE
install libxmake v2.3.3 .. failed  (macOS 10.15.7)

### ISSUE THREAD

**Issue by my4399** [xmake-io/xmake#1256]
![image](https://user-images.githubusercontent.com/30616342/109371771-63aa1e00-78e1-11eb-992f-cee482f0a09f.png)

mingzhi@mingzhideiMac luject % xmake
checking for architecture ... x86_64
checking for Xcode directory ... no
note: try installing these packages (pass -y to skip confirm)?
in xmake-repo:
  -> libxmake v2.3.3 
  -> lief 0.10.1 
please input: y (y/n)
y
  => install libxmake v2.3.3 .. failed            
if you want to get verbose errors, please see:
  -> /Users/mingzhi/.xmake/cache/packages/2102/l/libxmake/v2.3.3/installdir.failed/logs/install.txt
error: install failed!

![image](https://user-images.githubusercontent.com/30616342/109371818-92c08f80-78e1-11eb-94c7-b17ba5e2707e.png)
error: In file included from src/tbox/tbox/src/tbox/platform/file.c:39:
src/tbox/tbox/src/tbox/platform/posix/file.c:203:14: warning: 'stat64' is deprecated: first deprecated in macOS 10.6 [-Wdeprecated-declarations]
        if (!stat64(path, &st))
             ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/stat.h:427:9: note: 'stat64' has been explicitly marked deprecated here
int     stat64(const char *, struct stat64 *) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_5, __MAC_10_6, __IPHONE_NA, __IPHONE_NA);
        ^
In file included from src/tbox/tbox/src/tbox/platform/file.c:39:
src/tbox/tbox/src/tbox/platform/posix/file.c:330:12: error: 'preadv' is only available on macOS 11.0 or newer [-Werror,-Wunguarded-availability-new]
    return preadv(tb_file2fd(file), (struct iovec const*)list, size, offset);
           ^~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/uio.h:103:9: note: 'preadv' has been marked as being introduced in macOS 11.0 here, but the deployment target is macOS 10.15.0
ssize_t preadv(int, const struct iovec *, int, off_t) __DARWIN_NOCANCEL(preadv) __API_AVAILABLE(macos(11.0), ios(14.0), watchos(7.0), tvos(14.0));
        ^
src/tbox/tbox/src/tbox/platform/posix/file.c:330:12: note: enclose 'preadv' in a __builtin_available check to silence this warning
    return preadv(tb_file2fd(file), (struct iovec const*)list, size, offset);
           ^~~~~~
src/tbox/tbox/src/tbox/platform/posix/file.c:364:12: error: 'pwritev' is only available on macOS 11.0 or newer [-Werror,-Wunguarded-availability-new]
    return pwritev(tb_file2fd(file), (struct iovec const*)list, size, offset);
           ^~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/uio.h:104:9: note: 'pwritev' has been marked as being introduced in macOS 11.0 here, but the deployment target is macOS 10.15.0
ssize_t pwritev(int, const struct iovec *, int, off_t) __DARWIN_NOCANCEL(pwritev) __API_AVAILABLE(macos(11.0), ios(14.0), watchos(7.0), tvos(14.0));
        ^
src/tbox/tbox/src/tbox/platform/posix/file.c:364:12: note: enclose 'pwritev' in a __builtin_available check to silence this warning
    return pwritev(tb_file2fd(file), (struct iovec const*)list, size, offset);
           ^~~~~~~
1 warning and 2 errors generated.
warning: ifelse(a, b, c) is deprecated, please uses (a and b or c) instead of it

**Comment by waruqi** [comment]
you can update xmake-repo and try it again

```console
xmake repo -u
xmake f -c
xmake
```
