### ISSUE TITLE
space in the add_includedirs parameters

### ISSUE THREAD

**Issue by whua0727** [xmake-io/xmake#1257]
xmake.lua

```
add_includedirs("C:/Program Files/1.5.6-rc1/msvc2019_64/include")
```

When I use "xmake --verbose" to compile, failed because of  a "No such file or directory" mistake.

I think it's caused by the space in the "Program Files".

Because the include dirs of the makefile like this

```
"-I\"C:\\\\Program Files\\\\1.5.6-rc1\\\\msvc2019_64\\\\include\""
```
There are too many "\\" in the makefile. Bug or not?

xmake v2.5.1+202101210158,

**Comment by waruqi** [comment]
Please update to master/dev version.

see 

https://github.com/xmake-io/xmake/issues/1252
https://github.com/xmake-io/xmake/issues/1235

**Comment by waruqi** [comment]
please try v2.5.2
