### ISSUE TITLE
树莓派无法编译运行

### ISSUE THREAD

**Issue by TimeInDreams** [xmake-io/xmake#1258]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
在树莓派上无法编译程序

### Error output
编译报错

![IMG_20210227_235114](https://user-images.githubusercontent.com/56781415/109392510-5f204c80-7957-11eb-9556-1cb3283cb1f3.jpg)

> If it is a xmake related compilation problem, please add the `-v -D` parameter and give the detailed compilation output information.

### Related Environment

Please provide compiling and running environment information:

- xmake version:2.5.1
- os:Linux
- target platform:ubuntu18.04 arm64

**Comment by waruqi** [comment]
你项目里面xmake.lua内容贴下，只有空文件，才会报这个错

既然要编译项目，至少得放置一个target

**Comment by TimeInDreams** [comment]
> 你项目里面xmake.lua内容贴下，只有空文件，才会报这个错
> 
> 既然要编译项目，至少得放置一个target

[xmake_test.zip](https://github.com/xmake-io/xmake/files/6056149/xmake_test.zip)

**Comment by waruqi** [comment]
? 给这么多 xmake.lua 干嘛，我又没法测试，直接给个完整可复现的 example 。。

**Comment by waruqi** [comment]
吧 xmake_final.lua 改成 xmake.lua 测试没啥问题：

```console
ruki-2:xmake_test ruki$ mv xmake_final.lua xmake.lua
ruki-2:xmake_test ruki$ xmake
checking for platform ... macosx
checking for architecture ... x86_64
checking for Xcode directory ... /Applications/Xcode.app
checking for Codesign Identity of Xcode ... no
checking for SDK version of Xcode for macosx (x86_64) ... 11.0
checking for Minimal target version of Xcode for macosx (x86_64) ... 10.15
note: try installing these packages (pass -y to skip confirm)?
in xmake-repo:
  -> python 3.8.5 [from:opencv]
  -> opencv 4.5.1 
please input: y (y/n)
```

**Comment by TimeInDreams** [comment]
> 吧 xmake_final.lua 改成 xmake.lua 测试没啥问题：
> 
> ```
> ruki-2:xmake_test ruki$ mv xmake_final.lua xmake.lua
> ruki-2:xmake_test ruki$ xmake
> checking for platform ... macosx
> checking for architecture ... x86_64
> checking for Xcode directory ... /Applications/Xcode.app
> checking for Codesign Identity of Xcode ... no
> checking for SDK version of Xcode for macosx (x86_64) ... 11.0
> checking for Minimal target version of Xcode for macosx (x86_64) ... 10.15
> note: try installing these packages (pass -y to skip confirm)?
> in xmake-repo:
>   -> python 3.8.5 [from:opencv]
>   -> opencv 4.5.1 
> please input: y (y/n)
> ```

那可能是架构问题吗，我这边在虚拟机上，ubuntu18.04，x86架构可以编译，树莓派的arm64不能编译

**Comment by waruqi** [comment]
arm64下也可以的么。。要么更新到dev/master再试试

```lua
ruki@a660c52d52af:/mnt/xmake_test$ xmake
checking for platform ... linux
checking for architecture ... arm64-v8a
note: try installing these packages (pass -y to skip confirm)?
in xmake-repo:
  -> openssl 1.1.1h [from:python,opencv]
  -> libffi 3.2.1 [from:python,opencv]
  -> zlib 1.2.11 [from:python,opencv]
  -> python 3.8.5 [from:opencv]
  -> opencv 4.5.1 
please input: y (y/n)

  => downloading openssl, libffi, zlib .. (3/curl) ⠙
```

**Comment by waruqi** [comment]
这里暂时没法复现问题，你可以先自己搞个空工程试下，是否正常编译。。如果可以。。那么就到你的问题工程里面 用排查法 逐步排查，是哪个配置导致的问题。。

等完全可以复现后，可以再开 issue 给我个demo测试下，这里暂时先关了
