### ISSUE TITLE
vsxmake 生成的 VS 项目没有包含 add_cxflags 的编译选项

### ISSUE THREAD

**Issue by MeeSong** [xmake-io/xmake#1259]
### 描述问题

vsxmake 生成的 VS 项目没有包含 add_cxflags 的编译选项

### 期待的结果

把 add_cxflags 设置的编译选项包含到生成的 vs 项目配置中

### 相关环境

- xmake版本：v2.5.1+202101210158
- xmake运行平台：Windows 10 20H2
- xmake目标平台：Windows

### 其他信息

xmake.lua

```lua
add_rules("mode.debug", "mode.release")
add_requires("vcpkg::detours")
set_languages("c11", "cxx17")
set_warnings("allextra", "error")

target("menglong.capture")
    set_kind("shared")
    add_packages("vcpkg::detours")
    add_cxflags("-FI menglong.capture.inl", {force = true})
    add_files("src/dllmain.cpp")
    add_files("src/interface.cpp")
```

生成的 vs 编译选项

```
/ifcOutput "D:\Code\Menglong\build\.vs\menglong.capture\x64\debug\" /GS /W1 /Zc:wchar_t /Zi /Gm- /O2 /Fd"D:\Code\Menglong\build\.vs\menglong.capture\x64\debug\vc142.pdb" /Zc:inline /fp:precise /D "_WINDLL" /D "_MBCS" /errorReport:prompt /WX- /Zc:forScope /Gd /MD /std:c++17 /FC /Fa"D:\Code\Menglong\build\.vs\menglong.capture\x64\debug\" /EHsc /nologo /Fo"D:\Code\Menglong\build\.vs\menglong.capture\x64\debug\" /Fp"D:\Code\Menglong\build\.vs\menglong.capture\x64\debug\menglong.capture.pch" /diagnostics:column 
```

影响：未包含
![image](https://user-images.githubusercontent.com/6848759/109409762-4e5fed00-79d0-11eb-9a86-397981f353ba.png)

**Comment by waruqi** [comment]
用的是 vs 还是 vsxmake 插件？

vs 插件，我测试了下，有的么。

```
      <AdditionalOptions>/EHsc -nologo -FS -FI menglong.capture.inl %(AdditionalOptions)</AdditionalOptions>
```

另外，直接走 add_cxflags, 里面的路径不做自动处理的，回原样传给 cl.exe。只能知己处理保证路径可访问。

**Comment by MeeSong** [comment]
用 `xmake project -k vsxmake` 生成 sln，再用 vs 直接打开 sln

**Comment by MeeSong** [comment]
试了下 vs 插件，确实有。只是 vsxmake 没有

**Comment by MeeSong** [comment]
另一个问题：同一个 target， 我通过 `add_shflags("/DEF:module.def", {force = true})` 引入 def 文件，为什么用 vs 插件生成sln之后，生成的路径是 `/def:..\..\module.def `

这个 target 是个子模块，外面一层通过 `includes("menglong.capture/xmake.lua")` 引入

**Comment by MeeSong** [comment]
`add_shflags("/DEF:menglong.capture/src/module.def", {force = true})` 这样才可以（vs 和 vsxmake），为什么需要指定完整路径，而不是直接使用 target 当前路径？就像 add_files 那样直接使用 target 下的路径

**Comment by waruqi** [comment]
> `add_shflags("/DEF:menglong.capture/src/module.def", {force = true})` 这样才可以（vs 和 vsxmake），为什么需要指定完整路径，而不是直接使用 target 当前路径？就像 add_files 那样直接使用 target 下的路径

之前说过了，add_cxflags里面不会处理识别路径，只能当raw string 传入cl

> 另外，直接走 add_cxflags, 里面的路径不做自动处理的，回原样传给 cl.exe。只能自己处理保证路径可访问。

**Comment by MeeSong** [comment]
> 之前说过了，add_cxflags里面不会处理识别路径，只能当raw string 传入cl，你没法知道flags里面，哪些是路径，除非挨个识别flags来提取，但这完全不通用，不可能适配所有compiler的所有flags

所以按理来说，我传入 `module.def` 应该直接生成  `module.def` ，而不是  `..\..\module.def` 才对。但是事实不是

**Comment by waruqi** [comment]
> > 之前说过了，add_cxflags里面不会处理识别路径，只能当raw string 传入cl，你没法知道flags里面，哪些是路径，除非挨个识别flags来提取，但这完全不通用，不可能适配所有compiler的所有flags
> 
> 所以按理来说，我传入 `module.def` 应该直接生成 `module.def` ，而不是 `..\..\module.def` 才对。但是事实不是

回头我看下，vsxmake那个插件也是人家贡献进来的，不是我写的，我也得花时间调了才知道，你也可以直接看下里面实现

**Comment by MeeSong** [comment]
> > > 之前说过了，add_cxflags里面不会处理识别路径，只能当raw string 传入cl，你没法知道flags里面，哪些是路径，除非挨个识别flags来提取，但这完全不通用，不可能适配所有compiler的所有flags
> > 
> > 
> > 所以按理来说，我传入 `module.def` 应该直接生成 `module.def` ，而不是 `..\..\module.def` 才对。但是事实不是
> 
> 回头我看下，vsxmake那个插件也是人家贡献进来的，不是我写的，我也得花时间调了才知道，你也可以直接看下里面实现

vs 插件也是这样的，会多出来 `..\..\`

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/blob/30afab1009650eab95195eb7abcaa49ab85e311b/xmake/plugins/project/vstudio/impl/vs201x_vcxproj.lua#L120-L127

对 def/libpath/includedir 做了提取处理，因为生成的 vs 工程是在独立的 vs201x 目录下，所以原本源文件路径都要基于 vs201x 里面的路径做相对路径的变换处理，vs才能找到，因为vs的工作根路径是基于 vs201x 目录的，如果还是 ./module.def 。。vs会去找 vs201x/testproj/module.def 而不是原有工程的 projectdir/module.def。。

处理成 ../../module.def后，就是 vs201x/testproj/../../module.def 也就是 projectdir/module.def

**Comment by MeeSong** [comment]
了解了，非常感谢。

不过要是 def 文件变换后的路径能和源文件路径一致就好了。

我也print了一下 `$(projectdir)` 路径，发现它是主 xmake.lua 的目录，而不是子 xmake.lua 的目录。所以目前，只能写完整的 def 路径才可以。也就是把 `module.def` 改成 `menglong.capture/src/module.def`

目录树：
```
│   xmake.lua  ;includes("menglong.capture/xmake.lua")
│  
├───menglong.capture
│   │   xmake.lua
│   │
│   └───src
│           dllmain.cpp
│           interface.cpp
│           interface.h
│           main.cpp
│           menglong.capture.inl
│           module.def
│
└───vs2019
    │   vs2019.sln
    │
    ├───menglong.capture
            menglong.capture.vcxproj
            menglong.capture.vcxproj.filters
            menglong.capture.vcxproj.user
```

**Comment by waruqi** [comment]
> 我也print了一下 $(projectdir) 路径，发现它是主 xmake.lua 的目录，而不是子 xmake.lua 的目录

使用 `$(scriptdir)` 就是基于当前子 xmake.lua 目录

**Comment by MeeSong** [comment]
> > 我也print了一下 $(projectdir) 路径，发现它是主 xmake.lua 的目录，而不是子 xmake.lua 的目录
> 
> 使用 `$(scriptdir)` 就是基于当前子 xmake.lua 目录

`$(scriptdir)`  print 出来是正常的 `D:\Code\Menglong\menglong.capture` （通过 `print(os.scriptdir())` ）

然后 `add_shflags("/DEF:$(scriptdir)/src/module.def", {force = true})`

经过 vs 插件生成的 sln，就变成了 `/def:D:\Code\Menglong\src\module.def `

本应是 `$(scriptdir)` 的路径变成了 `$(projectdir)` 的路径

**Comment by waruqi** [comment]
看了，目前 `$(scriptdir)`以及其他vars 都是在 所有 xmake.lua 加载完成后进行的 转义处理，是滞后的，所以 `$(scriptdir)` 永远都是 根 xmake.lua 所在目录的路径

这块目前还不太好处理，涉及整体加载机制，目前可以通过 

```lua
    add_shflags("/def:" .. path.join(os.scriptdir(), "/module.def"), {force = true})
```

来解决，或者使用 dev 分支的新特性 `add_files("module.def")` 来直接添加 .def 文件，就能自动处理路径 （不过这个我刚提交，还有点不稳，还有部分 ci tests失败，但不影响此处功能的测试）

**Comment by waruqi** [comment]
ci上过了 你再试试

**Comment by waruqi** [comment]
应该可以的，你先试试，回头有问题再开

**Comment by MeeSong** [comment]
def 的问题可以了，很好用。但是延伸出新的问题...

vs 插件，生成的 sln 里面，没有把 def 设置进去。

vsxmake 插件倒是没影响，毕竟编译走的是 xmake.lua，但是用 vsxmake 插件又回到了最初的问题：vsxmake 插件生成的 sln 没有把 add_cxflags 附加的配置设置进去，编译没问题，但是代码提示会不准确。

**Comment by waruqi** [comment]
> vs 插件，生成的 sln 里面，没有把 def 设置进去。

这个我改进过了，dev 已经可以了

> vsxmake 插件倒是没影响，毕竟编译走的是 xmake.lua，但是用 vsxmake 插件又回到了最初的问题：vsxmake 插件生成的 sln 没有把 add_cxflags 附加的配置设置进去，编译没问题，但是代码提示会不准确。

这个暂时还不支持 `-FI xx.h` 这个可以改用 预编译头， set_pcxxheader/set_pcheader 。也会 force include 的。支持 vsxmake 提示

**Comment by MeeSong** [comment]
好的，非常感谢！

**Comment by waruqi** [comment]
> vs 插件，生成的 sln 里面，没有把 def 设置进去。

> 这个我改进过了，dev 已经可以了

这个我暂时 revert 了，改动引出了一些其他的问题，我需要先局部重构下

**Comment by waruqi** [comment]
> > vs 插件，生成的 sln 里面，没有把 def 设置进去。
> 
> > 这个我改进过了，dev 已经可以了
> 
> 这个我暂时 revert 了，改动引出了一些其他的问题，我需要先局部重构下

现在应该可以了

**Comment by MeeSong** [comment]
好的，非常感谢
