### ISSUE TITLE
upgrade the version of builtin curl

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1263]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情

使用xmake安装c++包时若使用代理，几率出现错误curl: (16) Error in the HTTP2 framing layer

https://github.com/curl/curl/issues/3750

更新curl到最新版可能解决此问题（此问题7.64.1仍存在，而xmake内置curl版本为7.54.0）

**Comment by waruqi** [comment]
我更新到最新了，ci上跑完，你再试试：https://github.com/xmake-io/xmake/actions/runs/618062335

**Comment by waruqi** [comment]
ci过了，你可以试试
