### ISSUE TITLE
I am not able to use options

### ISSUE THREAD

**Issue by PucklaMotzer09** [xmake-io/xmake#1264]
### Describe the problem details
I wanted to add options to my xmake project, but the command line interface seems to not exist.
I have implemented the option as follows:
```lua
option("build_tests")
    set_default(false)
    set_description("Wether to build the tests. Only necessery when developing")
```

But when I call ```xmake f --build_tests=y```. I get ```error: Invalid option: --build_tests=y```. When looking at the output from ```xmake --help``` it seems that there doesn't exist such an interface. Is this intentional?

xmake version: v2.5.2+202103011718

**Comment by PucklaMotzer09** [comment]
Here is a simple example project:
```lua
set_project("temp")

option("bye")
    set_default(false)
    add_defines("BYE")

target("temp")
    set_kind("binary")
    add_options("bye")
    add_files("main.cpp")
```

main.cpp:
```cpp
#include <iostream>

int main(int args, char *argv[]) {
#ifdef BYE
  std::cout << "Bye world" << std::endl;
#else
  std::cout << "Hello World" << std::endl;
#endif

  return 0;
}
```

When building the project and executing without setting the option it outputs **Hello World**.
When calling ```xmake f --bye=y``` it outputs ```error: Invalid option: --bye=y```.
And setting ```set_defaults(false)``` to true without setting the option in the command also outputs **Hello World**.

**Comment by waruqi** [comment]
you need call `set_showmenu(true)`

https://xmake.io/#/manual/configuration_option?id=optionset_showmenu

**Comment by PucklaMotzer09** [comment]
Now it works thank you
