### ISSUE TITLE
add find_package nvtx

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1267]
### 你在什么场景下需要该功能？

https://docs.nvidia.com/gameworks/content/gameworkslibrary/nvtx/nvidia_tools_extension_library_nvtx.htm

nvtx是cuda的辅助库，往往和cuda一起安装，而xmake目前只有find_cuda，无法在cuda项目中使用nvtx

### 描述可能的解决方案

添加一个detect/packages/find_nvtx.lua，nvtx的位置windows上可以通过环境变量NVTOOLSEXT_PATH获取。其他系统可能也有类似途径

**Comment by waruqi** [comment]
我现在暂时没nvcc环境，你可以直接提个pr过来。

**Comment by xq114** [comment]
请问在安装时需要copy的dll文件如何在find_package返回值中声明？

**Comment by waruqi** [comment]
libfiles = {} 全路径列表
