### ISSUE TITLE
support installing .cmake and pkgconfig/.pc files for targets

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1268]
### 你在什么场景下需要该功能？

使用xmake编写的库，希望其他原来使用cmake的项目也可以不做太多改动的情况下使用

### 描述可能的解决方案

```
add_rules("utils.export.cmake_import_files")
```
效果为install时在include、lib等文件夹外并列放一个cmake文件夹，文件夹里面放fooConfig.cmake等并通过相对路径标明此target的include/lib/syslink等信息

### 描述你认为的候选方案

```
xmake project -k cmake_import_files
```

缺点是不好指定特定的target，install的时候不能保证相对路径的正确

**Comment by waruqi** [comment]
可以用 rule ，名字改下：

```lua
add_rules("utils.install.cmake_import_files")
```

也可以导出 pkg-config pc files

```lua
add_rules("utils.install.pkgconfig_import_files")
```

**Comment by waruqi** [comment]
cmake 的还没弄，我先把 pkgconfig 的加上了。。只需要添加 `add_rules("utils.install.pkgconfig_files")` 规则。

```lua
target("test")
    set_kind("static")
    add_files("src/*.cpp")
    add_rules("utils.install.pkgconfig_files")
```

```
$ xmake install -o /tmp/install
$ tree /tmp/install/
/tmp/install/├── include
└── lib
    ├── libtest.a
    └── pkgconfig
        └── test.pc
```

test.pc

```
prefix=/tmp/install
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: test
Libs: -L/tmp/install/lib -L${libdir} -ltest
Libs.private:
Cflags: -I/tmp/install/include -I${includedir}
```

我们也可以不用内置的规则，自己通过 after_install 定制化一些安装参数

```lua
target("test")
    set_kind("static")
    add_files("src/*.cpp")
    after_install(function (target, opt))
        import("target.action.install.pkgconfig")(target, {includedirs = {"xxx"}, linkdirs = ..., links ..., filename = "xxxx.pc"})
    end
```

**Comment by waruqi** [comment]
cmake 的我也加上了，不过没有详测过是否完全生效，你可以试试 @xq114 

```lua
target("test")
    set_kind("static")
    add_files("src/*.cpp")
    add_rules("utils.install.cmake_importfiles")
```

对应的包名规则：`find_package("test::test")`  。。。targetname::basename

**Comment by xq114** [comment]
1. 一般来说这个文件是放在share/cmake或者lib/cmake下面而不是lib/cmake/test下面，这样同时有多个库的时候可以方便只设置一个路径；库名不会存在冲突问题
2. cmake文件内可以用${CMAKE_CURRENT_LIST_DIR}声明相对路径，而不是使用绝对路径 https://cmake.org/cmake/help/latest/variable/CMAKE_CURRENT_LIST_DIR.html
或者参考 https://cmake.org/cmake/help/latest/guide/importing-exporting/index.html?highlight=cmake_current_list_dir

**Comment by xq114** [comment]
绝对路径导致的问题
```
CMake Error at C:/Users/xq114/Projects/testc/dist/lib/cmake/lodepng/lodepngTargets.cmake:45 (set):
  Syntax error in cmake code at

    C:/Users/xq114/Projects/testc/dist/lib/cmake/lodepng/lodepngTargets.cmake:45

  when parsing string

    C:\Users\xq114\Projects\testc\dist

  Invalid character escape '\U'.
```

**Comment by waruqi** [comment]
> 一般来说这个文件是放在share/cmake或者lib/cmake下面而不是lib/cmake/test下面
> 是否可提供选项去掉project::前缀，直接用find_package(<target>)？

我是参考了 现有的一些包的安装，ogg, libjpeg 什么的，我看都是 project::xxxx 两级命名，并且都是放在 lib/cmake/xxx 下

> add_library(libjpeg-turbo::turbojpeg-static STATIC IMPORTED)


```
/Users/ruki/.xmake/packages//l/libogg/v1.3.4/05bd3ef519484fab9eed1d9b13064f52/lib/cmake/Ogg/OggTargets-release.cmake
/Users/ruki/.xmake/packages//l/libogg/v1.3.4/05bd3ef519484fab9eed1d9b13064f52/lib/cmake/Ogg/OggConfig.cmake
/Users/ruki/.xmake/packages//l/libogg/v1.3.4/05bd3ef519484fab9eed1d9b13064f52/lib/cmake/Ogg/OggConfigVersion.cmake
/Users/ruki/.xmake/packages//l/libogg/v1.3.4/05bd3ef519484fab9eed1d9b13064f52/lib/cmake/Ogg/OggTargets.cmake
/Users/ruki/.xmake/packages//l/libjpeg-turbo/2.0.90/bbc3030e3d9740ec9ff0a1bd1700dc34/lib/cmake/libjpeg-turbo/libjpeg-turboTargets.cmake
/Users/ruki/.xmake/packages//l/libjpeg-turbo/2.0.90/bbc3030e3d9740ec9ff0a1bd1700dc34/lib/cmake/libjpeg-turbo/libjpeg-turboConfig.cmake
/Users/ruki/.xmake/packages//l/libjpeg-turbo/2.0.90/bbc3030e3d9740ec9ff0a1bd1700dc34/lib/cmake/libjpeg-turbo/libjpeg-turboTargets-release.cmake
/Users/ruki/.xmake/packages//l/libjpeg-turbo/2.0.90/bbc3030e3d9740ec9ff0a1bd1700dc34/lib/cmake/libjpeg-turbo/libjpeg-turboConfigVersion.cmake
/Users/ruki/.xmake/packages//l/libjpeg-turbo/2.0.90/751c846dbd12437b9a6ef45db303fb17/lib/cmake/libjpeg-turbo/libjpeg-turboTargets.cmake
/Users/ruki/.xmake/packages//l/libjpeg-turbo/2.0.90/751c846dbd12437b9a6ef45db303fb17/lib/cmake/libjpeg-turbo/libjpeg-turboConfig.cmake
/Users/ruki/.xmake/packages//l/libjpeg-turbo/2.0.90/751c846dbd12437b9a6ef45db303fb17/lib/cmake/libjpeg-turbo/libjpeg-turboTargets-release.cmake
/Users/ruki/.xmake/packages//l/libjpeg-turbo/2.0.90/751c846dbd12437b9a6ef45db303fb17/lib/cmake/libjpeg-turbo/libjpeg-turboConfigVersion.cmake
/Users/ruki/.xmake/packages//l/libfreenect2/v0.2.0/0a7f97f277c446d3bcbfc7c9d958f184/lib/cmake/freenect2/freenect2Config.cmake
/Users/ruki/.xmake/packages//l/libfreenect2/v0.2.0/14fd476c12ee4531b15b9ad6e918d4d8/lib/cmake/freenect2/freenect2Config.cmake
/Users/ruki/.xmake/packages//l/libfreenect2/v0.2.0/3ecdcb9d50b44110ad83adeb15dc0708/lib/cmake/freenect2/freenect2Config.cmake
/Users/ruki/.xmake/packages//l/libfreenect2/v0.2.0/30439040a22f4fccbdabba3caa4f81d1/lib/cmake/freenect2/freenect2Config.cmake
/Users/ruki/.xmake/packages//l/libfreenect2/v0.2.0/4148585e40a04454ab0dbfad1c6b3053/lib/cmake/freenect2/freenect2Config.cmake
```

**Comment by waruqi** [comment]
> cmake文件内可以用${CMAKE_CURRENT_LIST_DIR}声明相对路径，而不是使用绝对路径 https://cmake.org/cmake/help/latest/variable/CMAKE_CURRENT_LIST_DIR.html

同样，我看现有第三方cmake工程安装的，prefixdir 等都是绝对路径，

> 绝对路径导致的问题

跟绝对路径没关系，是 win 上 cmake 不支持 `\\` , 只能支持 `/` 。。我忘记转了。。即使相对路径也会有问题。。
我刚修复了。dev

**Comment by xq114** [comment]
> > 一般来说这个文件是放在share/cmake或者lib/cmake下面而不是lib/cmake/test下面
> > 是否可提供选项去掉project::前缀，直接用find_package()？
> 
> 我是参考了 现有的一些包的安装，ogg, libjpeg 什么的，我看都是 project::xxxx 两级命名，并且都是放在 lib/cmake/xxx 下
> 
> > add_library(libjpeg-turbo::turbojpeg-static STATIC IMPORTED)
> 
> ```
> /Users/ruki/.xmake/packages//l/libogg/v1.3.4/05bd3ef519484fab9eed1d9b13064f52/lib/cmake/Ogg/OggTargets-release.cmake
> /Users/ruki/.xmake/packages//l/libogg/v1.3.4/05bd3ef519484fab9eed1d9b13064f52/lib/cmake/Ogg/OggConfig.cmake
> /Users/ruki/.xmake/packages//l/libogg/v1.3.4/05bd3ef519484fab9eed1d9b13064f52/lib/cmake/Ogg/OggConfigVersion.cmake
> /Users/ruki/.xmake/packages//l/libogg/v1.3.4/05bd3ef519484fab9eed1d9b13064f52/lib/cmake/Ogg/OggTargets.cmake
> /Users/ruki/.xmake/packages//l/libjpeg-turbo/2.0.90/bbc3030e3d9740ec9ff0a1bd1700dc34/lib/cmake/libjpeg-turbo/libjpeg-turboTargets.cmake
> /Users/ruki/.xmake/packages//l/libjpeg-turbo/2.0.90/bbc3030e3d9740ec9ff0a1bd1700dc34/lib/cmake/libjpeg-turbo/libjpeg-turboConfig.cmake
> /Users/ruki/.xmake/packages//l/libjpeg-turbo/2.0.90/bbc3030e3d9740ec9ff0a1bd1700dc34/lib/cmake/libjpeg-turbo/libjpeg-turboTargets-release.cmake
> /Users/ruki/.xmake/packages//l/libjpeg-turbo/2.0.90/bbc3030e3d9740ec9ff0a1bd1700dc34/lib/cmake/libjpeg-turbo/libjpeg-turboConfigVersion.cmake
> /Users/ruki/.xmake/packages//l/libjpeg-turbo/2.0.90/751c846dbd12437b9a6ef45db303fb17/lib/cmake/libjpeg-turbo/libjpeg-turboTargets.cmake
> /Users/ruki/.xmake/packages//l/libjpeg-turbo/2.0.90/751c846dbd12437b9a6ef45db303fb17/lib/cmake/libjpeg-turbo/libjpeg-turboConfig.cmake
> /Users/ruki/.xmake/packages//l/libjpeg-turbo/2.0.90/751c846dbd12437b9a6ef45db303fb17/lib/cmake/libjpeg-turbo/libjpeg-turboTargets-release.cmake
> /Users/ruki/.xmake/packages//l/libjpeg-turbo/2.0.90/751c846dbd12437b9a6ef45db303fb17/lib/cmake/libjpeg-turbo/libjpeg-turboConfigVersion.cmake
> /Users/ruki/.xmake/packages//l/libfreenect2/v0.2.0/0a7f97f277c446d3bcbfc7c9d958f184/lib/cmake/freenect2/freenect2Config.cmake
> /Users/ruki/.xmake/packages//l/libfreenect2/v0.2.0/14fd476c12ee4531b15b9ad6e918d4d8/lib/cmake/freenect2/freenect2Config.cmake
> /Users/ruki/.xmake/packages//l/libfreenect2/v0.2.0/3ecdcb9d50b44110ad83adeb15dc0708/lib/cmake/freenect2/freenect2Config.cmake
> /Users/ruki/.xmake/packages//l/libfreenect2/v0.2.0/30439040a22f4fccbdabba3caa4f81d1/lib/cmake/freenect2/freenect2Config.cmake
> /Users/ruki/.xmake/packages//l/libfreenect2/v0.2.0/4148585e40a04454ab0dbfad1c6b3053/lib/cmake/freenect2/freenect2Config.cmake
> ```

这个问题确实不大，cmake的项目也是五花八门 opencv的cmake直接放在lib下面
![image](https://user-images.githubusercontent.com/42310255/112089159-0d708800-8bcc-11eb-9307-284d7218bf06.png)
我见过的放lib/cmake的比较多，这也是官方tutorial放置的位置

用相对路径的库还是多的，这样复制粘贴到别的地方还能用，改起来也并不复杂，其实自定义的那个import路径就和CMAKE_CURRENT_LIST_DIR差不多

**Comment by xq114** [comment]
另外想要发布二进制预编译包必须用相对路径

**Comment by xq114** [comment]
![image](https://user-images.githubusercontent.com/42310255/112089839-5ecd4700-8bcd-11eb-92a7-915c89cf4a3d.png)
摘自Eigen3Targets.cmake

**Comment by waruqi** [comment]
> 我见过的放lib/cmake的比较多，这也是官方tutorial放置的位置

我看到的都是分两级的，用来便于管理维护 一个project 包含多个 targets 的情况。。

像 tutorial 这种通常都是简单的基础工程，就一个 target，所以可能简化成 一级了。。

> 另外想要发布二进制预编译包必须用相对路径

路径问题，我刚改进过了

**Comment by xq114** [comment]
现在可以成功编译了

**Comment by xq114** [comment]
另外，是否考虑加一个机制支持安装到系统的xmake包？例如，两个xmake包安装到/usr/local下，在xmake中无法直接定位这两个包。而在/usr/local下面放xmake.lua当package用也不现实，会导致这两个包冲突。lib/cmake/project/xxConfig.cmake的设计思路则避开了这个问题，能去子目录找对应的cmake文件。
![image](https://user-images.githubusercontent.com/42310255/112108506-3d7b5380-8beb-11eb-9554-a84f0fb6f159.png)

**Comment by waruqi** [comment]
理论上是可以搞，但目前需求不强烈，既然走了 xmake 包，并且还是提供给 xmake 项目用，那就直接集成到 xmake-repo 仓库或者自己的仓库，然后走 add_requires集成就好了


搞成类似 lib/cmake 的方式，以后安装一个系统包，并且要兼容其他构建工具，以后就会变成 ，.pc/cmake/xmake 导入文件各一份，装个库，光 import files 就是一坨（如果还有其他构建工具的话），现在已经被很多人喷分裂构建生态了。。

所以，能走 xmake-repo/add_requires 尽量走这个集成，不想过于污染系统库目录，导致充斥各种 lib/xmake 文件。。
