### ISSUE TITLE
sync git submodules after checkout to a certain tag from a remote repository

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1271]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
目前在xmake-repo中，一个带有git submodules的库通过git下载后，在同步完所有submodules之后才checkout到tag上，这会导致最终下载的源码中submodules与打上tag时submodules的commit不匹配。若改成先checkout再同步submodules：
```
git submodule sync && git submodule update --init --recursive
```
则不会有这一问题。

**Comment by waruqi** [comment]
没看明白，能给个有问题，可复现的例子么。

**Comment by xq114** [comment]
> 没看明白，能给个有问题，可复现的例子么。

https://github.com/xq114/xmake-repo/tree/dev

正在测试的libtorch包，在on_install里面加上了这两个命令，不加会报一大堆错
