### ISSUE TITLE
How can I import environment variables via find_package("xxx")?

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1273]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
如果一个包含有可执行文件，需要引进path，如何在detect/packages/find_xxx.lua中声明？

**Comment by waruqi** [comment]
不支持 find_package 目前仅用于库 不支持带二进制的
