### ISSUE TITLE
buildir/dependir should be spelled builddir/dependdir

### ISSUE THREAD

**Issue by cmeerw** [xmake-io/xmake#1276]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
`buildir` and `dependir` don't make sense as it's "build directory" and "dependencies directory", so the spelling should be `builddir` and `dependdir` (maybe keep the alternative spelling)

### Expected behavior
I should be able to use `$(builddir)`, `$(dependdir)` or `target:set_dependdir`

### Error output
N/A

### Related Environment

Please provide compiling and running environment information:

- xmake version: 2.5.2
- os: Ubuntu 20.10
- target platform: amd64

### Additional context
Maybe also consider `build_dir` and `depend_dir`

**Comment by waruqi** [comment]
Yes, this is only due to some historical reasons, but I don't want to modify this yet.

Because this involves more changes. Unless more people request this, I will consider modifying it
