### ISSUE TITLE
Function `get_host_speed` in `get.sh`  can't work correctly on Linux.

### ISSUE THREAD

**Issue by chmodgwh777** [xmake-io/xmake#1278]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
Function `get_host_speed` in `get.sh`  can't work correctly on Linux.

### Expected behavior
Get true speed.

### Error output
Run
```bash
$ bash <(curl -fsSL https://xmake.io/shget.text | sed 's/^bash/bash -x/')
```

Output
```
+ set -o pipefail
++ id -u
+ '[' 0 -ne 1000 ']'
+ sudo --version
+ sudoprefix=sudo
+ '[' -z '' ']'
+ tmpdir=/tmp/.xmake_getter16464
+ '[' -d /tmp/.xmake_getter16464 ']'
+ gmake --version
+ make=gmake
+ branch=__run__
+ '[' x '!=' x ']'
+ '[' x__local__ '!=' x__run__ ']'
++ get_fast_host
+++ get_host_speed gitee.com
++++ uname
+++ '[' Linux == Darwin ']'
+++ egrep -o 'time=\d+'
+++ egrep -o '\d+'
+++ ping -c 1 -W 1 gitee.com
+++ echo 65535
++ speed_gitee=65535
+++ get_host_speed github.com
++++ uname
+++ '[' Linux == Darwin ']'
+++ ping -c 1 -W 1 github.com
+++ egrep -o 'time=\d+'
+++ egrep -o '\d+'
+++ echo 65535
++ speed_github=65535
++ '[' 65535 -le 65535 ']'
++ echo gitee.com
+ fasthost=gitee.com
+ '[' gitee.com == gitee.com ']'
+ gitrepo=https://gitee.com/tboox/xmake.git
+ gitrepo_raw=https://gitee.com/tboox/xmake/raw/master
...
```

### Related Environment

Please provide compiling and running environment information:

- xmake version: v2.5.2+202103101303
- os: Linux gentoo 5.11.2-gentoo
- grep: grep (GNU grep) 3.6

### Additional context
I think we should use `grep -P` instead of `egrep` for PCREs regex `"time=\d+"` on Linux (GNU grep).
Note that egrep (BSD grep) on mac osx can work correcly.

**Comment by waruqi** [comment]
I have fixed it on dev branch. Thanks!
