### ISSUE TITLE
links should not be imported from a dependency of kind "binary"

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1279]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

https://github.com/xmake-io/xmake-repo/pull/317/checks?check_run_id=2072732969

libtorch的link中不正确地引入了binary python的依赖：z, ssl, crypto

### 期待的结果

binary dependency的link等不应该引入到包中

### 错误信息

```
> checking for c++ links(torch, torch_cpu, c10, z, ssl, crypto, openblas, openblas_haswellp-r0.3.13, uv, ffi, pthread, dl)
```

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.2
- xmake运行平台：linux
- xmake目标平台：linux

### 其他信息

![image](https://user-images.githubusercontent.com/42310255/110622169-12016d80-81d6-11eb-959b-3d2814d4faa4.png)

**Comment by waruqi** [comment]
这个只影响到 on_test 里面的检测，没有区分 binary/library deps，我刚 dev 上修复了，你再试试

而 add_packages 的实际链接中，有做区分，不会被影响。
