### ISSUE TITLE
integrate find_foo.lua into xmake-repo as phony targets

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1280]
### 你在什么场景下需要该功能？

一个包由于版权等原因无法由xmake自动安装，需要用户手动安装再由xmake寻找。现有解决方案是使用detect/packages/find_foo.lua或者detect/sdks/find_foo.lua进行寻找，返回一个table。然而这种方法在xmake-repo中无法使用package:add("deps", "foo")来添加，破坏了依赖包的一致性，麻烦

### 描述可能的解决方案

有一个方法是在xmake-repo中设置phony target（`set_kind("phony")`），就是一个不加url和version、也不创建自己的installdir的包，直接返回find_xxx的结果。这样find_xxx也不需要再放在xmake本体里面，可以分离到repo中。

### 描述你认为的候选方案

支持package:add_local_package(<table>)的语法

### 其他信息

https://github.com/xmake-io/xmake-repo/pull/317

**Comment by waruqi** [comment]
目前包的kind类型有： binary/toolchains/library(default)

即使做仅用于find_xxx的包，也应该得同时支持 binary/toolchains/library的查找，单纯通过 set_kind("phony") 定制，无法区分。。

其实只需要判断是否存在 on_install/on_fetch，如果只有 on_fetch 没有 on_install，那就是一个单纯的 find_xxx 包，忽略安装和test过程


```lua
package("xxx")

    set_homepage("https://www.xxx.org")
    set_description("A xxx package.")

    on_fetch(function (package)
        return find_package("xxx")
    end)
```

**Comment by waruqi** [comment]
我支持了，你试试

**Comment by waruqi** [comment]
同样，如果是 fetchonly的包， `add_requires("xxx")` 找不到系统库，会直接提示 xxx not found! 报错

除非设置 `add_requires("xxx", {optional = true})` 标记为可选包，就不会报错，只是单纯的忽略

在 package 的 add_deps 也是， `add_deps("xxx", {optional = true})`

**Comment by xq114** [comment]
> 同样，如果是 fetchonly的包， `add_requires("xxx")` 找不到系统库，会直接提示 xxx not found! 报错
> 
> 除非设置 `add_requires("xxx", {optional = true})` 标记为可选包，就不会报错，只是单纯的忽略
> 
> 在 package 的 add_deps 也是， `add_deps("xxx", {optional = true})`

add_deps("xxx", {optional = true})之后如何判断是否存在xxx包呢？是用package:dep("xxx"):fetch()吗？同理，add_requires("xxx", {optional = true})之后也要判断是否成功，然后要加相关的define等，这个怎么操作

**Comment by waruqi** [comment]
通过 package:dep("xxx"):exists() 就可以判断

**Comment by waruqi** [comment]
> ，然后要加相关的define等，这个怎么操作

判断后，在on_install里面加 target:add defines，

on_load阶段太早，dep fetch还没做

**Comment by xq114** [comment]
> > ，然后要加相关的define等，这个怎么操作
> 
> 判断后，在on_install里面加 target:add defines，
> 
> on_load阶段太早，dep fetch还没做

我指的是在实际项目的xmake.lua里面根据查找结果加define，不是在repo里面

**Comment by waruqi** [comment]
> > > ，然后要加相关的define等，这个怎么操作
> > 
> > 
> > 判断后，在on_install里面加 target:add defines，
> > on_load阶段太早，dep fetch还没做
> 
> 我指的是在实际项目的xmake.lua里面根据查找结果加define，不是在repo里面

同样走 add_requires/add_packages，判断存在，可以用 if has_package()
