### ISSUE TITLE
Use MSVC conventions for generated compile_commands.json

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1284]
### 你在什么场景下需要该功能？

在windows上使用cl作为compiler时，有一些language server（例如ccls https://github.com/MaskRay/ccls ）不能正确识别unix-styled msvc options。例如`set_runtimes("MT")`仅在windows上起作用而compile_commands.json生成的选项却是`-MT`而不是`/MT`

### 描述可能的解决方案

在windows上对msvc-specific options使用msvc-style而非unix-style

### 其他信息

![image](https://user-images.githubusercontent.com/42310255/110894003-062abe00-8332-11eb-9bc1-5dedde08925f.png)
![image](https://user-images.githubusercontent.com/42310255/110894033-13e04380-8332-11eb-8152-229a24bfdaa1.png)

**Comment by xq114** [comment]
手动替换将`-MT`改为`/MT`后ccls正常工作了

**Comment by waruqi** [comment]
我这里可以修改做兼容，不过我觉得你应该提个 issues 给 ccls 。这种按理也应该支持才对。

**Comment by waruqi** [comment]
dev上改过了。
