### ISSUE TITLE
如何设置仅在子项目生效的配置？

### ISSUE THREAD

**Issue by eddylin83** [xmake-io/xmake#1285]
### 你在什么场景下需要该功能？
通过includes添加子项目的时候，如何像add_requires那样传递配置内容(add_requires(... {configs = {...}))？现在我的操作基本都是定义全局变量，但总感觉这样算是污染。哪种写法才比较好？只传递给子项目的话。

**Comment by waruqi** [comment]
一种就是走option配置项，全局的 option() + has_config/is_config

或者 includes 里面，通过定义 function 去获取全局配置，get_myconfigs(), get_config_value() 等 ，名字自己随意 或者直接 set_xxxx_configs() 对某个target设置各种 add_xxx/set_xxx
