### ISSUE TITLE
how to use xmake in termux?

### ISSUE THREAD

**Issue by wujilingfeng** [xmake-io/xmake#1286]
I write a .c file like:
``` c
#include<stdio.h>
int main()
{return 1;}
```
and a xmake.lua file like:
``` lua
target("main")
    set_kind("binary")
    add_files("*.c")
```
It reports "Error: ccache: failed to link /home/.cache/ccache/tmp/tmp.cpp_stdout.zOSL4M to /home/.cach/ccache/tmp/tmp.cpp_stdout.zOSL4M.i : Permission denied"

**Comment by waruqi** [comment]
disable ccache. `xmake f --ccache=n`

**Comment by wujilingfeng** [comment]
Thank you !
