### ISSUE TITLE
Having VS Build tools without VS installed means "xmake config --vs --vs_toolset" only works from within  "Developer Command Prompt for VS 2019"

### ISSUE THREAD

**Issue by GavinRay97** [xmake-io/xmake#1287]
### Related Environment

Please provide compiling and running environment information:

- xmake version: xmake v2.5.2+202103121406,
- os: Windows 10
- target platform: Windows/MSVC

![image](https://user-images.githubusercontent.com/26604994/111005402-bca19980-8358-11eb-8481-7dbc6de19eec.png)

**Comment by waruqi** [comment]
you passed an incorrect toolset. It should be 14.2 
14.1   14.0 ... 

see https://github.com/xmake-io/xmake/issues/229

https://cmake.org/cmake/help/latest/variable/MSVC_TOOLSET_VERSION.html

**Comment by GavinRay97** [comment]
Ah, my mistake then. Thank you!
