### ISSUE TITLE
如何获取版本和编译时间

### ISSUE THREAD

**Issue by zwxf** [xmake-io/xmake#1289]
文档中的下面这个接口可以全局设置版本和编译时间
`set_version("x.x.x", {build = "%Y%m%d%H%M"})`
除了文档`https://xmake.io/#/manual/project_target?id=add-template-configuration-files`中提到通过在config.h.in的方式外，有没办法再xmake.lua中直接获取到呢，我想直接将版本重新定义成宏，给全局使用。

还有，是否有方式强制每次都编译特定的文件，而不检查是否已经编译过了？
我有尝试通过如下代码：
```
    on_load(function (target)
        os.run("touch buildtime.c")
    end)
    add_files("buildtime.c")
```
后来发现检测规则和make有所不同，并不是检测文件时间来判断是否重新编译。
期待回复，谢谢！

**Comment by waruqi** [comment]
> 除了文档https://xmake.io/#/manual/project_target?id=add-template-configuration-files中提到通过在config.h.in的方式外，有没办法再xmake.lua中直接获取到呢，我想直接将版本重新定义成宏，给全局使用。

```lua
    on_load(function (target)
        target:add("defines", "TIME_" .. os.date("%Y%m%d%H%M"))
    end)
```

> 还有，是否有方式强制每次都编译特定的文件，而不检查是否已经编译过了？

`xmake build xxxtarget`

or

```lua
xmake --files=src/main.c
xmake --files='src/*.c' [target]
xmake --files='src/**c|excluded_file.c'
xmake --files='src/main.c:src/test.c'
```

**Comment by zwxf** [comment]
感谢，还有touch是会导致重新编译的，我之前touch错文件位置了。
```
    on_load(function (target)
        os.run("touch buildtime.c")
    end)
    add_files("buildtime.c")
```
