### ISSUE TITLE
无法生成vs

### ISSUE THREAD

**Issue by wujilingfeng** [xmake-io/xmake#1295]
### Describe the bug
在安装xmake-dev2.5.2之后，我运行xmake project -k vs或者xmake project -k vs2017出现错误：error:bad argument #1 to 'is_absolute'。
之后我又重新安装xmake-master2.5.2,仍然出现上述错误 。
这个问题出现在我的[项目](https://github.com/wujilingfeng/cstructures.git)和其他项目。

### Expected behavior
在之前的xmake2.5.2版本好像没问题的。

### Error output
![image](https://user-images.githubusercontent.com/35684738/111604433-4ac1c800-8810-11eb-9c70-5074ce98974b.png)

### Related Environment

Please provide compiling and running environment information:

- xmake version: dev-2.5.2,master2.5.2
- os: win10
- target platform:visual studio

**Comment by waruqi** [comment]
追加 -vD 给我看下栈

**Comment by waruqi** [comment]
我修复了，等 ci 跑完再试试，或者直接 xmake update -s dev

**Comment by wujilingfeng** [comment]
其实我并不着急，还是等xmake下个版本吧。xmake加油!

**Comment by waruqi** [comment]
那现在这个确认没问题了吧，那我先关了。。
