### ISSUE TITLE
automatically add includedirs for the header files of a library

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1296]
### 你在什么场景下需要该功能？

对于某library foo，xmake.lua
```
target("foo")
	set_kind("static")
	add_files("src/*.c")
	add_headerfiles("include/(*.h)")
```
效果是在`xmake install -o dist foo`的时候自动安装头文件。但如果在项目中还有其他target
```
target("bar")
	set_kind("binary")
	add_deps("foo")
	add_files("main.cpp")
```
则必须在`target("foo")`下面加一行`add_includedirs("include", {public=true})`，比较麻烦

### 描述可能的解决方案

在`add_headerfiles`时自动添加`add_includedirs("...", {public=true})`

**Comment by waruqi** [comment]
不考虑，手动添加 也多不了几行配置，而且灵活可控，没有隐式的操作 也能避免用户趟坑，配置也会更加直观可维护。。

自动添加，对于多层级headers，到底要自动添加几层子目录都不可控，每个项目的需求都不同。。
