### ISSUE TITLE
使用远程拉取交叉工具链在 xmake clean 之后失效

### ISSUE THREAD

**Issue by OuYangPaste** [xmake-io/xmake#1304]
### 描述问题

        远程拉取交叉编译链(从自己的私有仓中)，正常使用没有问题。 但是如果改动 xmake.lua(比如只是增加一个空格) 然后再 xmake clean , 此时必定报 cross toolchain not found，然后再 xmake 的时候就不会去调用我的交叉编译链，而是使用我 pc 的gcc 环境，只有重新 xmake f 随便任意设置一下，远程拉取的交叉编译链才能重新生效。

### 错误信息
 看下图，因为增加 -v 编译信息太长，所以截图中我提供的是文件的 file 信息

![image](https://user-images.githubusercontent.com/38561133/112144900-a7f4b980-8c14-11eb-8418-4de46a6df266.png)

### 相关环境
- xmake版本：xmake v2.5.2+202103231521
- xmake运行平台：Linux
- xmake目标平台：

**Comment by waruqi** [comment]
我 dev 上修复了
