### ISSUE TITLE
Add ios as a build platform

### ISSUE THREAD

**Issue by demhademha** [xmake-io/xmake#1305]
### Is your feature request related to a problem? Please describe.
building for ios is not possible due to the fact that xmake lacks a build platt for iOS
### Describe the solution you'd like
a solution would be to add iOS support to the Makefile   
### Describe alternatives you've considered
Perhaps it is possible by forcing **platt** to be linux, and then manually setting **CFLAGS, CXXFLAGS, CC, CXX etc**
### Additional context
perhaps you could implement something like this: 
```makefile
ifeq ($(UNAME),Darwin)
ifeq ($(filter $(shell uname -m | cut -c -4), iPad iPho),)
$(warning Building on MacOS)
else
$(warning Building on iOS)

```

**Comment by waruqi** [comment]
I have supported it on dev branch, but I have not tested it on ios yet.

```console
make PLAT=iphoneos
```
