### ISSUE TITLE
find_python doesn't find python3 when find_python3 finds it

### ISSUE THREAD

**Issue by PucklaMotzer09** [xmake-io/xmake#1306]
### Describe the bug
As I worked on [the scons package](https://github.com/xmake-io/xmake-repo/pull/334) **windows** couldn't find **python3** when I searched for it using ```find_tool("python")```, it always found **python2**. But as I switched to ```find_tool("python3")``` everything worked as expected. There was also an error on **macosx** where I couldn't get the version from python, but as soon as I switched it worked.

### Expected behavior
When using ```find_tool("python")``` and there is a **python3** installed, it should work the same as ```find_tool("python3")```

### Error output
You can look at the **CI/CD** output from the [PR](https://github.com/xmake-io/xmake-repo/pull/334).

**Comment by waruqi** [comment]
Can you run `python --version` and let me the output?

**Comment by PucklaMotzer09** [comment]
I would need to open a PR and wait for the CI/CD to finish, because this completely works on my system. The failing checks were **macosx** and **windows**. On my system I get the following output: 
```
checking for python ... /home/johnny/.xmake/packages/p/python/3.8.5/82d0be448a92494e8f3ae51330414f99/bin/python
checking for python3 ... /home/johnny/.xmake/packages/p/python/3.8.5/82d0be448a92494e8f3ae51330414f99/bin/python3
Python 3.8.5
Python 3.8.5
```

When writing
```lua
local python = assert(find_tool("python"), "python not found!")
local python3 = assert(find_tool("python3"), "python3 not found!")
os.execv(python.program, {"--version"})
os.execv(python3.program, {"--version"})
```

**Comment by waruqi** [comment]
I have improved it on dev branch.
