### ISSUE TITLE
 xmake require --list 报错

### ISSUE THREAD

**Issue by OuYangPaste** [xmake-io/xmake#1309]
### 描述问题

 xmake require --list
报错 : invalid value (boolean) at index 1 in table for 'concat'

### 错误信息
        报错之后我在 ~/.local/share/xmake/modules/private/action/require/list.lua 增加了如下打印
![image](https://user-images.githubusercontent.com/38561133/112713126-7fb7d400-8f0e-11eb-9e28-761f12239f02.png)
        显示如下：
![image](https://user-images.githubusercontent.com/38561133/112713141-a544dd80-8f0e-11eb-9cfb-ac7c40c284c3.png)

### 相关环境

- xmake版本： 2.5.2+202103231521
- xmake运行平台： Linux
- xmake目标平台：

**Comment by waruqi** [comment]
去掉所有打印，追加 -vD 给我看下栈，xmake require --list -vD

**Comment by OuYangPaste** [comment]
![image](https://user-images.githubusercontent.com/38561133/112718608-244a0e00-8f2f-11eb-8bd7-30ef0df4810d.png)

**Comment by waruqi** [comment]
我 dev 上修复了

**Comment by OuYangPaste** [comment]
验证了下没有问题了，响应迅速，十分感谢
