### ISSUE TITLE
版本记录与版本的选项，就像debug这中内置的

### ISSUE THREAD

**Issue by southbear-club** [xmake-io/xmake#1315]
### 你在什么场景下需要该功能？

需要xmake能有一个选项能设置当前的软件版本号，如1.0.0这种，能够用于设置一个全局的宏定义，像有debug这种选项就很人性化。
版本号符合语义化，没输入版本号时能使用上次使用的版本号，并且如果输入的版本号非法(格式不对，比上次的低)能够报错。

### 描述可能的解决方案

记录下输入过的合法版本号，每次执行编译时读出来，如果用户没有输入则使用最新的，如果有输入则进行校验，校验过了就记录下来。

**Comment by xq114** [comment]
https://xmake.io/#/zh-cn/manual/global_interfaces?id=set_project

**Comment by waruqi** [comment]
原本就支持，set_version + add_configfiles 

看下文档里面这两个接口的说明

**Comment by southbear-club** [comment]
好的，谢谢。之前翻了下文档没翻到。
