### ISSUE TITLE
Environment variables from dependent packages are neglected by package.tools.nmake

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1316]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

```
add_deps("nasm")
...
import("package.tools.nmake").build(package)
```

报错找不到nasm

### 期待的结果

nmake build过程使用的环境变量应该加入依赖包设置的环境变量

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.2 master
- xmake运行平台：windows
- xmake目标平台：windows

**Comment by waruqi** [comment]
原本就是支持的，只不过是内部 msvc runenvs 设置后，里面的 path 给覆盖了已有的。。我刚修复了。。
