### ISSUE TITLE
add find_bash for windows

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1318]
### 你在什么场景下需要该功能？

https://github.com/Microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_configure_make.cmake

autoconf本质上基于bash，有一些使用autoconf的包实际上在configure里面支持windows，这样有bash就可以port到windows。vcpkg的解决办法是维护一个内建的msys2，用msys2 bash去执行，用msvc编译。其实用git bash也可以达到同样的效果。（mingw-w64缺少bash也无法使用autoconf）所以需要一个find_bash去找可用的bash（git bash，msys2 bash等），然后执行`bash -c "./configure"`

### 描述可能的解决方案

find_tool("bash")

**Comment by waruqi** [comment]
你可以提个pr 帮忙加到 https://github.com/xmake-io/xmake/tree/master/xmake/modules/detect/tools 里面就好了。。

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/pull/1319
