### ISSUE TITLE
macOS clang `compile_commands.json` doesn't have `-internal-isystem` include directory

### ISSUE THREAD

**Issue by zhylmzr** [xmake-io/xmake#1328]
### Describe the bug
clang's `-internal-isystem` directory isn't in `compile_commands.json`, that cause the `clangd` to report `iostream` header file not find.

![error-tip](https://user-images.githubusercontent.com/15730824/114135934-8990fc80-993c-11eb-9da8-0e074a16f08c.png)

### Expected behavior
`-internal-isystem` and `-internal-externc-isystem` can be added correctly to `compile_commands.json`

### Related Environment
- xmake version:v2.5.2+202102281518
- os:macOS Big Sur 11.0.1
- target platform: macOS

### Additional context
```js
// compile_commands.json
[
{
  "directory": "/Users/zhylmzr/Downloads/env-c",
  "arguments": ["/usr/bin/xcrun -sdk macosx clang", "-c", "-Qunused-arguments", "-arch", "x86_64", "-mmacosx-version-min=11.0", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk", "-fvisibility=hidden", "-fvisibility-inlines-hidden", "-O3", "-DNDEBUG", "-o", "build/.objs/env-c/macosx/x86_64/release/src/main.cpp.o", "src/main.cpp"],
  "file": "src/main.cpp"
}]
```

The `xmake b -v` output:
![xmake b -v](https://user-images.githubusercontent.com/15730824/114136408-38353d00-993d-11eb-8ebf-01cde450cca0.png)

The clang compile option
![clang option](https://user-images.githubusercontent.com/15730824/114136595-8a765e00-993d-11eb-956c-e22f134fec6d.png)

**Comment by waruqi** [comment]
I think this should be a clangd issue https://github.com/clangd/clangd/issues/487, compile_commands should not add internal-isystem

It works for c/c++ plugins of vscode.

and ccls is also the c++/v1 path added globally in the .ccls configuration file
