### ISSUE TITLE
config.h.in存在的必要性。

### ISSUE THREAD

**Issue by zwxf** [xmake-io/xmake#1329]
询问下config.h.in存在的必要性，为什么需要在set_configvar后，还需要在config.h.in填写相应的替换信息，才能在生成config.h文件找到设置的信息，为什么不能set_configvar后就可以生成config.h文件，再在config.h.in填写一遍似乎没什么必要性，设计成这个考虑是什么呢？
期待回复，感谢！

**Comment by waruqi** [comment]
xmake 没有强行规定 set_configvar 仅用于 config.h，一切被 add_configfiles("xxxx") 配置的任意文件都可以走 set_configvar 变量替换后输出目标文件。。

可以使 xxxx.h.in 用于头文件，也可以是 xxx.rc.in 用于其他资源文件。。。也可以没有 .in 后缀，也可以是纯二进制文件，.png/.jpeg，纯走 copy 在编译前输出到指定目录。。

通常用了 config.h.in 只不过是一些用户，一些项目的习惯命名用法而已，xmake 没有硬性规定必须是 config.h ，也不知道用户用来做什么，到底是生成 config.h 还是其他啥文件。。


xmake 仅仅只是提供一种通用机制，add_configfiles/set_configvar/set_configdir 配合，在编译前，预处理一些文件，生成到指定位置，为下一步编译使用做准备。
