### ISSUE TITLE
Provide option to remove CMAKE_INSTALL_LIBDIR setting

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1331]
### 你在什么场景下需要该功能？

```
import("package.tools.cmake").install(package)
```

上面的命令会自动设置CMAKE_INSTALL_LIBDIR为绝对路径。然而CMAKE_INSTALL_LIBDIR并不是一个规范的路径，一些库使用CMAKE_INSTALL_LIBDIR="lib"，另一些使用CMAKE_INSTALL_LIBDIR="${CMAKE_INSTALL_PREFIX}/lib"，官方文档未进行指定。设置此选项将导致使用前者定义的库无法正常编译

### 描述可能的解决方案

提供选项，
```
import("package.tools.cmake").install(package, {}, {libdir = false})
```

### 描述你认为的候选方案

直接去掉这个设置，如果需要再手动加

**Comment by waruqi** [comment]
能给个具体的包case 和错误信息么

**Comment by xq114** [comment]
vtk包 https://github.com/Kitware/VTK/

错误信息
```
CMake Error at CMake/vtkModule.cmake:1829 (message):
  The `ARCHIVE_DESTINATION` must not be an absolute path.  Use
  `CMAKE_INSTALL_PREFIX` to keep everything in a single installation prefix.
Call Stack (most recent call first):
  CMake/vtkModule.cmake:2319 (_vtk_module_check_destinations)
  CMakeLists.txt:332 (vtk_module_build)
```

相关文件
https://github.com/Kitware/VTK/blob/4f21cad8e3726f88c2cef519425c2c0284a212c2/CMake/vtkModule.cmake#L2320-L2322

顺带一提，VTK和cmake来自同一个组织Kitware

**Comment by waruqi** [comment]
我改了下，你可以在外面重写 CMAKE_INSTALL_LIBDIR 试试，比如 `table.insert(configs, "-DCMAKE_INSTALL_LIBDIR=lib")` 会优先用外面设置的
