### ISSUE TITLE
内存太小编译卡死 

### ISSUE THREAD

**Issue by wangzhankun** [xmake-io/xmake#1332]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

在执行`xmake`命令进行编译的时候卡死。但是使用`xmake project -k cmake`之后使用`cmake`和`make`进行编译没有任何问题。如下图所示，上面编译成功，下面`xmake`会卡死在某个过程。
![1](https://user-images.githubusercontent.com/35724924/114261346-a432a680-9a0c-11eb-9b00-9f35daaafac4.jpg)

### 相关环境

- xmake版本：3.5.3
- xmake运行平台：树莓派4b Ubuntu server 18.04 arm 2GB版本

### 其他信息
在所有配置相同但是内存为4GB版本的树莓派上编译运行一切正常。

**Comment by xq114** [comment]
xmake f --ccache=false关闭ccache试试

**Comment by waruqi** [comment]
关了 ccache 或者 并行任务开小点 xmake -j1

**Comment by wangzhankun** [comment]
xmake是默认有多少核心就开多少线程吗？

**Comment by wangzhankun** [comment]
编译成功了，感谢。

**Comment by waruqi** [comment]
> xmake是默认有多少核心就开多少线程吗？

ceil(ncpu * 3 / 2)
