### ISSUE TITLE
Find python from conda first other then registry

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1333]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

Windows上仅安装Anaconda未安装python时，依赖python的库报错
```
get registry value size failed: HKEY_CURRENT_USER\SOFTWARE\Python\PythonCore\3.8\InstallPath;ExecutablePath
```

### 期待的结果

从注册表获取python时应针对anaconda情形加判断

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.3
- xmake运行平台：windows
- xmake目标平台：windows

### 其他信息

![image](https://user-images.githubusercontent.com/42310255/114372014-adaa4300-9bb3-11eb-98df-f7ca84fb7cbb.png)

如图，仅安装anaconda时ExecutablePath并不存在

**Comment by waruqi** [comment]
改了，再试下
