### ISSUE TITLE
package detecting failed when pkg-config is not installed on Linux

### ISSUE THREAD

**Issue by idealvin** [xmake-io/xmake#1334]
### Describe the bug

Using the following commands to detect openssl which is already installed on Linux:
```lua
add_requires("openssl", {optional = true})
if has_package("openssl") then
    add_defines("CO_SSL")
    add_links("ssl", "crypto")
end
```

Xmake did not find the openssl  and no error or a hint was given.

Then I installed pkg-config and run xmake again, it finally detected the openssl.

### Expected behavior

Found the package allready installed, otherwise give a hint to the user.

### Related Environment

- xmake version:  v2.5.2
- os:  ubuntu 20.04
- target platform: linux x64

**Comment by waruqi** [comment]
I have improved this problem, you can try

```console
xmake update -s dev
xmake repo -u
xmake f -c
```

**Comment by idealvin** [comment]
Ok, I'll update xmake when the next version is released.
