### ISSUE TITLE
msys2中使用--trybuild特性编译faad时报错cannot exec(autoreconf --install --symlink)

### ISSUE THREAD

**Issue by augustheart** [xmake-io/xmake#1342]
### 描述问题
环境为msys2，使用的命令为
```Shell
xmake f --trybuild=autotools --tryconfigs="--enable-static --disable-shared"
```
有没有--tryconfigs不影响结果
在xmake的时候报错
```Shell
gbgba@LEI MINGW32 ~/faad2-2_10_0
$ xmake f --trybuild=autotools --tryconfigs="--enable-static --disable-shared"

gbgba@LEI MINGW32 ~/faad2-2_10_0
$ xmake -vD
autoreconf --install --symlink
error: @programdir\core\main.lua:294: @programdir\core\sandbox\modules\os.lua:347: cannot exec(autoreconf --install --symlink), No such file or directory
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:788]: in function 'raise'
    [@programdir\core\sandbox\modules\os.lua:347]: in function 'exec'
    [@programdir\core\sandbox\modules\os.lua:404]: in function 'vexec'
    [@programdir\modules\private\action\trybuild\autotools.lua:226]: in function 'build'
    [@programdir\actions\build\main.lua:77]: in function '_try_build'
    [@programdir\actions\build\main.lua:99]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:519]: in function 'run'
    [@programdir\core\main.lua:292]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:788: in function 'raise'
        @programdir\core\main.lua:294: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>
```
autoreconf在环境中已安装，直接使用相关命令是可行的。
```Shell
gbgba@LEI MINGW32 ~/faad2-2_10_0
$ autoreconf --install --symlink
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
...
...
```
并且在如上手动执行autoreconf后再使用xmake --trybuild并xmake是可以编译成功的。

### 相关环境
- xmake版本：2.5.3
- xmake运行平台：msys2
- xmake目标平台：windows10

**Comment by waruqi** [comment]
你可以尝试执行下 `xmake l os.exec "autoreconf --install --symlink"` 看看能否成功。

然后找下 autoreconf 在 msys 里面的实际路径位置，以及扩展名。。

**Comment by augustheart** [comment]
> 
> 
> 你可以尝试执行下 `xmake l os.exec "autoreconf --install --symlink"` 看看能否成功。
> 
> 然后找下 autoreconf 在 msys 里面的实际路径位置，以及扩展名是什么。。
```Shell
gbgba@LEI MINGW32 ~/faad2-2_10_0
$ xmake l os.exec "autoreconf --install --symlink"
error: cannot exec(autoreconf --install --symlink), No such file or directory

gbgba@LEI MINGW32 ~/faad2-2_10_0
$ where autoreconf
C:\Work\msys2\usr\bin\autoreconf
```

**Comment by waruqi** [comment]
我改进过了 你再试试，autoreconf 在 msys 下需要 sh 才能带起来，你命令行执行，走的是 shell ，所以ok的 ， xmake l os.exec 走的是 CreateProcess 。。所以不行。

**Comment by augustheart** [comment]
顺便问一下，xmake有没有可能或是有没有意向将trybuild特性集成到xmake.lua中？写好配置后直接xmake就可以了，不需要每次trybuild、tryconfig命令行一大堆。
这样的好处可能是不需要专门维护一个包，直接从官方的tar.gz包就能实现编译乃至后续的基于文件的处理。xmake提供了trybuild这么独特的能力，似乎可以利用来统一很多不同的编译系统。使用开源库的话，五花八门的编译系统一直是件很麻烦的事。而各种包系统则是各扫门前雪，导致了大量的重复建设。
当然，我知道大佬你是推荐用包系统的，这个想法有点挖包系统的墙角哈。

**Comment by waruqi** [comment]
xmake-repo 里面的所有包，不都是这么干的么。。https://github.com/xmake-io/xmake-repo/blob/e138bd65fda3ae00ae7bcb333c2b00349b4fed9d/packages/l/libogg/xmake.lua#L16-L22 

> 当然，我知道大佬你是推荐用包系统的，这个想法有点挖包系统的墙角哈。

你直接在自己的 xmake.lua 里面 定义一个 package ，走 add_requires() ，跟你说的方式有区别么？

不就是你所谓的：`直接从官方的tar.gz包就能实现编译乃至后续的基于文件的处理`

```lua
package("libogg")
    set_urls("https://gitlab.xiph.org/xiph/ogg/-/archive/$(version)/ogg-$(version).tar.gz",
             "https://gitlab.xiph.org/xiph/ogg.git")
    add_versions("v1.3.4", "62cc64b9fd3cf57bde3a9033e94534ba34313d2bb9698029f623121a4e47bb9b")
    add_patches("v1.3.4", path.join(os.scriptdir(), "patches", "1.3.4", "macos_fix.patch"), "e12c41ad71206777f399c1048914e5e5a2fe44e18d0d50ebe9bedbfbe0624c35")

    on_install(function (package)
        local configs = {"-DBUILD_TESTING=OFF"}
        table.insert(configs, "-DCMAKE_BUILD_TYPE=" .. (package:debug() and "Debug" or "Release"))
        table.insert(configs, "-DBUILD_SHARED_LIBS=" .. (package:config("shared") and "ON" or "OFF"))
        table.insert(configs, "-DCMAKE_POSITION_INDEPENDENT_CODE=ON")
        import("package.tools.cmake").install(package, configs)
    end)

add_requires("libogg")

target("test")
    set_kind("binary")
    add_files("src/*.c")
    add_packages("libogg")
```

**Comment by augustheart** [comment]
> 
> 
> xmake-repo 里面的所有包，不都是这么干的么。。https://github.com/xmake-io/xmake-repo/blob/e138bd65fda3ae00ae7bcb333c2b00349b4fed9d/packages/l/libogg/xmake.lua#L16-L22
> 
> > 当然，我知道大佬你是推荐用包系统的，这个想法有点挖包系统的墙角哈。
> 
> 你直接在自己的 xmake.lua 里面 定义一个 package ，走 add_requires() ，跟你说的方式有区别么？
> 
> 不就是你所谓的：`直接从官方的tar.gz包就能实现编译乃至后续的基于文件的处理`
> 
> ```lua
> package("libogg")
>     set_urls("https://gitlab.xiph.org/xiph/ogg/-/archive/$(version)/ogg-$(version).tar.gz")
>     add_versions("v1.3.4", "62cc64b9fd3cf57bde3a9033e94534ba34313d2bb9698029f623121a4e47bb9b")
> 
>     on_install(function (package)
>         local configs = {"-DBUILD_TESTING=OFF"}
>         table.insert(configs, "-DCMAKE_BUILD_TYPE=" .. (package:debug() and "Debug" or "Release"))
>         table.insert(configs, "-DBUILD_SHARED_LIBS=" .. (package:config("shared") and "ON" or "OFF"))
>         table.insert(configs, "-DCMAKE_POSITION_INDEPENDENT_CODE=ON")
>         import("package.tools.cmake").install(package, configs)
>     end)
> package_end()
> 
> add_requires("libogg")
> 
> target("test")
>     set_kind("binary")
>     add_files("src/*.c")
>     add_packages("libogg")
> ```
> 
> set_urls 也可以是 local file path，add_version() 你也可以省略
> 
> ```lua
> package("libogg")
>     set_urls("file://xxx/ogg-v1.3.4.tar.gz")
> 
>     on_install(function (package)
>         local configs = {"-DBUILD_TESTING=OFF"}
>         table.insert(configs, "-DCMAKE_BUILD_TYPE=" .. (package:debug() and "Debug" or "Release"))
>         table.insert(configs, "-DBUILD_SHARED_LIBS=" .. (package:config("shared") and "ON" or "OFF"))
>         table.insert(configs, "-DCMAKE_POSITION_INDEPENDENT_CODE=ON")
>         import("package.tools.cmake").install(package, configs)
>     end)
> package_end()
> 
> add_requires("libogg")
> 
> target("test")
>     set_kind("binary")
>     add_files("src/*.c")
>     add_packages("libogg")
> ```

我现在还处在看文档的阶段，文档没说的眼前一抹黑，原来早就有了。惭愧惭愧。

**Comment by waruqi** [comment]
看下文档：https://xmake.io/#/zh-cn/package/remote_package?id=%e4%bd%bf%e7%94%a8%e8%87%aa%e5%bb%ba%e7%a7%81%e6%9c%89%e5%8c%85%e4%bb%93%e5%ba%93

没啥其他问题，我这边先 close 了。
