### ISSUE TITLE
多工程共代码管理的xmake框架书写疑惑

### ISSUE THREAD

**Issue by WPchom** [xmake-io/xmake#1345]
近期在对原有的一个较为大型的工程的构建进行的改造，计划采用xmake，但遇到一些问题。

以下是原有工程的精简目录结构：
```
root
    build       # 默认统一输出目录
        projA_Output    # projectA输出文件夹
            targetA1        # targetA1生成文件
            targetA2        # targetA2生成文件
    src
        common      # 公共代码文件夹(配置疑惑？)
            ...         # 较多不同类别的源码库
            Kconfig     # 相关编译控制
        projects    # 工程文件夹(多工程共管理)
            projA       # projectA文件夹
                src         # projectA独立源码文件夹
                targetA1    # 存放targetA1相关config，使用toolchain1
                targetA2    # 存放targetA2相关config，使用toolchain2
            projOther   # 其他工程文件夹，结构如projA
    tools
        toolchain1  # 交叉编译工具链1
        toolchain2  # 交叉编译工具链2
```
目前使用SCons进行构建，目前计划忘xmake进行改造。在兼容原工程的管理架构，有一下几点疑问：
  1. 在common下的多个不同源码的引入Kconfig是否能用xmake的option选项完全代替？option的写法能否像Kconfig那样嵌套或层级的书写？(scons下引入了python的kconfiglib，实现menuconfig和kconfig的解析, ```scons -C projects/projA targetA1 --menuconfig```可以进行menuconfig配置，在targetA1下生成.config文件)
  2. projA下的不同target会使用不同的toolchain，但会使用同一份公共源码，则在common中是使用库的target描述(如何引入targetA1定义的工具链)比较合适，还是使用package描述好？(package的介绍不多，是否适合源码的分发管理)
  3. 目前使用scons直接在root目录下```scons -C projects/projA targetA1```，在执行目录下创建build文件夹进行中间文件和最终文件的生成，转化成xmake是否能保持这样的文件结构？
  4. xmake.lua文件的引用是否能进行跨文件变量传递(scons中Import/Export的特性)？target描述中设置toolchain时，能否为对应的toolchain传递参数，像函数一样？(这个特性在scons中可以将toolchain的指定封装成带参函数，比如在targetA1的设置toolchain时指定toolchain/bin的路径)
  
疑惑比较多，感谢解答。

**Comment by waruqi** [comment]
> 在common下的多个不同源码的引入Kconfig是否能用xmake的option选项完全代替？option的写法能否像Kconfig那样嵌套或层级的书写？(scons下引入了python的kconfiglib，实现menuconfig和kconfig的解析, scons -C projects/projA targetA1 --menuconfig可以进行menuconfig配置，在targetA1下生成.config文件)

option 本身定义不能嵌套，但是可以通过 `set_category("root/submenu/submenu2")` 来直接对当前 option 分类到 menu 的某个特定层级下，作为子 menu item 展示，可以实现同样的结果。

至于 option 放在哪里定义，随意，只要最后被 includes 进来了就行。。

具体看下文档：https://xmake.io/#/zh-cn/manual/configuration_option?id=optionset_category  这里面详细描述。

> projA下的不同target会使用不同的toolchain，但会使用同一份公共源码，则在common中是使用库的target描述(如何引入targetA1定义的工具链)比较合适，还是使用package描述好？(package的介绍不多，是否适合源码的分发管理)

仅仅只需要 includes 所有 toolchains 定义后，针对不同的 target ，使用 set_toolchains 绑定到对应工具链上去就行了

```
- xmake.lua
    src
        common
            - xmake.lua（定义各种 option）
        projects
            projA
              - xmake.lua
                src
                  - xmake.lua (定义各种 targets，少的话一个就行了，多的话，再细分子目录)
            projOther
               - xmake.lua
    tools
        -- xmake.lua （定义各种 toolchains）
```

从跟目录 xmake.lua 开始，按需通过 includes("src/projects", "tools", "src/common") 一层层 includes，子 xmake.lua 里面也是。

只要根目录 xmake.lua 里面 includes 了所有 toolchains 定义，那么

projects/xmake.lua 下就可以直接使用 set_toolchains 来绑定各种工具链了。

```lua
target("A1")
    set_toolchains("tool1")

target("A12")
    set_toolchains("tool2")
```

> 目前使用scons直接在root目录下scons -C projects/projA targetA1，在执行目录下创建build文件夹进行中间文件和最终文件的生成，转化成xmake是否能保持这样的文件结构？

同样，根目录执行 xmake 就行了，默认编译所有 target，也可以指定编译特定 target `xmake build targetA1`

不管在哪里执行，默认都会在根工程目录 build 下，生成所有文件，里面会根据 target 分子目录，分 objs/deps等各种目录，你可以自己 同 tree 查看，要调整生成的 target 文件目录结构，可以通过 set_targetdir/set_objectdir 自己调整，具体看文档

build 目录也可以通过 xmake f --buildir=xxx 修改。

> xmake.lua文件的引用是否能进行跨文件变量传递(scons中Import/Export的特性)？

按原生 lua 语法，直接根 xmake.lua 定义全局 lua 变量 `a = 1`，子目录下 就能获取到。


> target描述中设置toolchain时，能否为对应的toolchain传递参数，像函数一样？(这个特性在scons中可以将toolchain的指定封装成带参函数，比如在targetA1的设置toolchain时指定toolchain/bin的路径)

可以，比如：

```lua
set_toolchains("msvc", {vs = "2019"})
set_toolchains("ndk", {ndk_sdkver = "19"})
```

然后 toolchain("ndk") 定义里面，通过`toolchain:config("ndk_sdkver")` 取，具体看 xmake 源码里面内置工具链定义和使用。

**Comment by zwxf** [comment]
`在common下的多个不同源码的引入Kconfig是否能用xmake的option选项完全代替？option的写法能否像Kconfig那样嵌套或层级的书写？(scons下引入了python的kconfiglib，实现menuconfig和kconfig的解析, scons -C projects/projA targetA1 --menuconfig可以进行menuconfig配置，在targetA1下生成.config文件)`
对于这个我也有些疑惑，目前使用下来，option的机制还是无法和kconfig的完全替换，比如kconfig下有savedefconfig，可以将生成的.config文件文件保存成defconfig，可以使用这个配置不同的项目，然后通过make xxx_defconfig就可以重新生成相应的配置文件，目前xmake并无相应的功能，当有多个配置项目要求的时候，只能将 `.xmake/linux/x86_64/xmake.conf`下面的配置文件拷贝出来，使用时重新重新拷贝回去，再xmake f重新生成配置信息，很麻烦，是否有考虑加入kconfig的这个机制？

**Comment by waruqi** [comment]
说白了，就是 import/export config 么，可以考虑，但是具体实现排期得看后续安排，这个版本 没时间做，可以先单独提个 feature request 备着

**Comment by WPchom** [comment]
> `在common下的多个不同源码的引入Kconfig是否能用xmake的option选项完全代替？option的写法能否像Kconfig那样嵌套或层级的书写？(scons下引入了python的kconfiglib，实现menuconfig和kconfig的解析, scons -C projects/projA targetA1 --menuconfig可以进行menuconfig配置，在targetA1下生成.config文件)`
> 对于这个我也有些疑惑，目前使用下来，option的机制还是无法和kconfig的完全替换，比如kconfig下有savedefconfig，可以将生成的.config文件文件保存成defconfig，可以使用这个配置不同的项目，然后通过make xxx_defconfig就可以重新生成相应的配置文件，目前xmake并无相应的功能，当有多个配置项目要求的时候，只能将 `.xmake/linux/x86_64/xmake.conf`下面的配置文件拷贝出来，使用时重新重新拷贝回去，再xmake f重新生成配置信息，很麻烦，是否有考虑加入kconfig的这个机制？

确实也有这个困惑，scons和make对于menuconfig生成的.config文件是可以指定保存，可以跟随某个target的文件存储和导入。

**Comment by WPchom** [comment]
> 从跟目录 xmake.lua 开始，按需通过 includes("src/projects", "tools", "src/common") 一层层 includes，子 xmake.lua 里面也是。
> 
> 只要根目录 xmake.lua 里面 includes 了所有 toolchains 定义，那么
> 
> projects/xmake.lua 下就可以直接使用 set_toolchains 来绑定各种工具链了。

这个地方和我之前的表述可能不清楚有关，主要是common的源码是会进行权限管理的，不是所有人员都可以拉取到源码；
对于能拉取到源码的人，使用源码编译成lib（需要由targetA提供编译参数），后由targetA链接该lib生成bin；
对于无权限拉取源码的人，会使用已经在仓中同一目录下存放的已经编译好的lib，直接由targetA链接；

问题就出现在能拉取到源码的人，编译lib，需要新建一个static的target，但这个库的target怎样由主targetA进行add_deps时给它传递一些参数（宏定义，额外includedir，toolchain等）
另外就是生成的lib文件能否指定独立文件夹，和bin文件进行分开存放。

**Comment by waruqi** [comment]
> 问题就出现在能拉取到源码的人，编译lib，需要新建一个static的target，但这个库的target怎样由主targetA进行add_deps时给它传递一些参数（宏定义，额外includedir，toolchain等）

includes("common") 导入 common/xmake.lua 里面的 targets 定义，可以通过 `add_includedirs("xxx", {public = true})` 设置到这个 target，并对 add_deps("") 的子targetA 生效导出，大部分 set_xxx/add_xxx/add_defines... 都支持可见性导出，类似cmake，public/interface/private 三种可见性。


> 另外就是生成的lib文件能否指定独立文件夹，和bin文件进行分开存放。

上面说的，set_targetdir

**Comment by xq114** [comment]
> 说白了，就是 import/export config 么，可以考虑，但是具体实现排期得看后续安排，这个版本 没时间做，可以先单独提个 feature request 备着

这个特性确实很有意义，C++项目一般很多config option，排列组合一下就有2^N种编译配置，即使对option之间依赖关系做了处理，还是大概率有配置出问题。而使用配置模板（或者export config），就只需要维护几种配置选项，大大降低了维护复杂度，同时也不局限于一种默认配置

**Comment by waruqi** [comment]
> > 说白了，就是 import/export config 么，可以考虑，但是具体实现排期得看后续安排，这个版本 没时间做，可以先单独提个 feature request 备着
> 
> 这个特性确实很有意义，C++项目一般很多config option，排列组合一下就有2^N种编译配置，即使对option之间依赖关系做了处理，还是大概率有配置出问题。而使用配置模板（或者export config），就只需要维护几种配置选项，大大降低了维护复杂度，同时也不局限于一种默认配置

可以单独提个feature request 备着，这个issues跟这没啥关系，要是没啥其他问题，我先close了

**Comment by waruqi** [comment]
export/import 的支持我加上了，见：https://github.com/xmake-io/xmake/issues/1351#issuecomment-861129019
