### ISSUE TITLE
同时生成 staitc/shared 库

### ISSUE THREAD

**Issue by fallending** [xmake-io/xmake#1346]
### 你在什么场景下需要该功能？

我是SDK开发者，而SDK使用者那边期望同时提供静态库/动态库，所以 xmake 如何支持配置、同时生成静态库/动态库？

**Comment by waruqi** [comment]
配置两个 target ，一个 static 一个 shared

**Comment by fallending** [comment]
> 配置两个 target ，一个 static 一个 shared

感谢🙏回答。

OK，如果要生成同名静态库/动态库【lib.a lib.dylib】的话，有直接配置支持不？

**Comment by waruqi** [comment]
通过 set_filename 或者  set_basename 修改

**Comment by fallending** [comment]
感谢，看上去也不太麻烦

`
target("http_static")
  set_kind("static")
  set_basename('http')
  set_warnings("all", "error")
  set_languages("c++14")
  
  add_files("http.cpp")

  if is_os("android") then
    add_includedirs("$(projectdir)/src/ifaddrs")
    add_links("ifaddrs")
  end
    
target("http_shared")
  set_kind("shared")
  set_basename('http')
  
  add_files("http.cpp")

  set_warnings("all", "error")
  set_languages("c++14")

  if is_os("android") then
    add_includedirs("$(projectdir)/src/ifaddrs")
    add_links("ifaddrs")
  end
`

**Comment by waruqi** [comment]
通用设置放顶部 root 域，对所有子targets生效，没必要每个target都去设置一遍
