### ISSUE TITLE
Binary packages of different vs_runtime should not be considered distinct

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1347]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
例如，windows上我依赖了binary类型的strawberry-perl，则vs_runtime=MT时安装了一遍，vs_runtime=MD的时候应该直接复用原来安装的而无需重新下载安装

**Comment by waruqi** [comment]
区分还是要做的，xmake-repo 里面 add_deps 包默认就是 MT 的。。

只有走 xmake f --vs_runtime=MD 时候，package 的 默认 vs_runtime 配置被改写成了 MD，没走继承逻辑。。我现在改进过了。。可以再试试。。dev

**Comment by xq114** [comment]
对于library类型的package被依赖的库确实要和依赖的库runtime保持一致，如果runtime是MD那依赖的所有library库也都应该是MD的，只有binary类型由于只调用可执行文件而不参与链接所以无需保持一致

**Comment by xq114** [comment]
现在ci上出问题了 https://github.com/xq114/xmake-repo/runs/2401813875?check_suite_focus=true

**Comment by waruqi** [comment]
没看出什么问题，你先自己研究下好了

**Comment by xq114** [comment]
> 没看出什么问题，你先自己研究下好了

就是这里openvdb是MD，依赖的boost也应该是MD，但这里实际安装的boost是MT
![image](https://user-images.githubusercontent.com/42310255/115734759-88d87b80-a3bc-11eb-8452-ee5f2d4e1f53.png)

**Comment by waruqi** [comment]
稍微改了下，等 dev ci跑完再试试

**Comment by waruqi** [comment]
昨天改的有问题，我更新了下，一会再试试
