### ISSUE TITLE
support private package

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1348]
### 你在什么场景下需要该功能？

承接 https://github.com/xmake-io/xmake/issues/1087

下载下来就不变的包只要同一配置，默认共享给所有项目没问题。但有些包安装后会随项目设置变化（例如python）或者含有config文件，希望一个项目在开发时能独占这个包不共享给其他项目使用

举例，使用pybind11开发C++包的python接口，希望在develop过程中不共享python给其他项目且不使用系统python（方便重装），直到发布给用户安装时才指定安装到哪个python；

另外，xmake中指定使用系统上哪一个包除了预先运行`xmake l find_package xmake::python`提供缓存之外还有更好的方式吗？

### 描述可能的解决方案

```
	add_requires("python 3.8.x", {private = has_config("develop")})
```

**Comment by waruqi** [comment]
这个不就是我之前说的这个么，不是已经支持了么，private

https://github.com/xmake-io/xmake/issues/1313#issuecomment-822454918

**Comment by xq114** [comment]
> 这个不就是我之前说的这个么，不是已经支持了么，private
> 
> [#1313 (comment)](https://github.com/xmake-io/xmake/issues/1313#issuecomment-822454918)

没注意到private已经被用了...这两个是不同的场景，1313说的是用来安装的辅助包，不导出link、env等等，而这里说的是不与其他项目共享，但link、env等都正常导出，换一个名字叫exclusive=true好了

**Comment by waruqi** [comment]
`add_requires("python~tag1")` 走 `~tagname` 就能clone出一个独立的python包，独立的安装目录，单独私用，不影响 `add_requires("python")`

完全独立

**Comment by xq114** [comment]
> `add_requires("python~tag1")` 走 `~tagname` 就能clone出一个独立的python包，独立的安装目录，单独私用，不影响 `add_requires("python")`
> 
> 完全独立

测试：
```
~/
--A/
----xmake.lua: add_requires("python~tag1")
--B/
----xmake.lua: add_requires("python~tag2")
```
在A项目内运行python与B项目内运行python调用的是同一个python，在`xmake f -c`时也没有提示重新安装python

**Comment by waruqi** [comment]
更新到 dev 再试试
