### ISSUE TITLE
[iOS打包] 关于改进点：合并iphoneos和iphonesimulator平台，以及watchos和watchsimulator平台，通过arch来区分，使得打包更加方便，能够支持一次性打包iphoneos的所有arch到一个包中

### ISSUE THREAD

**Issue by fallending** [xmake-io/xmake#1350]
### 【更新日志中 v2.0.1种提到：】合并iphoneos和iphonesimulator平台，以及watchos和watchsimulator平台，通过arch来区分，使得打包更加方便，能够支持一次性打包iphoneos的所有arch到一个包中

请教该改进点的使用示例，比如：

```
xmake f -p iphoneos|iphonesimulator
xmake
```

或者 
```
xmake f -p iphoneos -a 多种arch？
xmake
```

**Comment by waruqi** [comment]
原本就合并了快一两年了，只有 iphoneos 和 watchos 两平台，可以 xmake f --help 看下

现在是 2.5.3 ，你去看2.0.1干啥

**Comment by fallending** [comment]
> 原本就合并了快一两年了，只有 iphoneos 和 watchos 两平台，可以 xmake f --help 看下
> 
> 现在是 2.5.3 ，你去看2.0.1干啥

好的，我看下。
主要是 ```xmake f -p iphoneos```  打包出来只看到有armv7，不确定如何打出多种arch的库

**Comment by waruqi** [comment]
自己切下arch，xmake f -p iphoneos -a arm64

**Comment by fallending** [comment]
> -a arm64

嗯，是我理解错了。。以为可以配置多个arch直接生成。。sorry。。所以对于iOS，多arch的库打包，需要这样对吧：

```
        xmake f -p iphoneos -a armv7
	xmake
	xmake f -p iphoneos -a armv7s
	xmake
	xmake f -p iphoneos -a arm64
	xmake
	xmake f -p iphoneos -a x86_64
	xmake
	rm -rf build/iphoneos/release
	mkdir build/iphoneos/release
	lipo -create build/iphoneos/armv7/release/libhttp.a build/iphoneos/arm64/release/libhttp.a build/iphoneos/armv7s/release/libhttp.a build/iphoneos/x86_64/release/libhttp.a -output build/iphoneos/release/libhttp.a
```

**Comment by waruqi** [comment]
xmake m package -f iphoneos 可以一次性打所有 arch ，见 https://xmake.io/#/zh-cn/plugin/builtin_plugins?id=%e5%86%85%e7%bd%ae%e7%9a%84%e5%ae%8f%e8%84%9a%e6%9c%ac
