### ISSUE TITLE
希望增加config的export/import特性

### ISSUE THREAD

**Issue by WPchom** [xmake-io/xmake#1351]
`在common下的多个不同源码的引入Kconfig是否能用xmake的option选项完全代替？option的写法能否像Kconfig那样嵌套或层级的书写？(scons下引入了python的kconfiglib，实现menuconfig和kconfig的解析, scons -C projects/projA targetA1 --menuconfig可以进行menuconfig配置，在targetA1下生成.config文件)`
对于这个我也有些疑惑，目前使用下来，option的机制还是无法和kconfig的完全替换，比如kconfig下有savedefconfig，可以将生成的.config文件文件保存成defconfig，可以使用这个配置不同的项目，然后通过make xxx_defconfig就可以重新生成相应的配置文件，目前xmake并无相应的功能，当有多个配置项目要求的时候，只能将 `.xmake/linux/x86_64/xmake.conf`下面的配置文件拷贝出来，使用时重新重新拷贝回去，再xmake f重新生成配置信息，很麻烦，是否有考虑加入kconfig的这个机制？

_Originally posted by @zwxf in https://github.com/xmake-io/xmake/issues/1345#issuecomment-822132621_

**Comment by waruqi** [comment]
我加上支持了

### Export configs

```console
$ xmake f --export=/tmp/config.txt
$ xmake f -m debug --xxx=y --export=/tmp/config.txt
```


### Import configs

```console
$ xmake f --import=/tmp/config.txt
$ xmake f -m debug --xxx=y --import=/tmp/config.txt
```

### Export configs with menu

```console
$ xmake f --menu --export=/tmp/config.txt
$ xmake f --menu -m debug --xxx=y --export=/tmp/config.txt
```


### Import configs with menu

```console
$ xmake f --menu --import=/tmp/config.txt
$ xmake f --menu -m debug --xxx=y --import=/tmp/config.txt
```

**Comment by zwxf** [comment]
测试下下，import/export没什么问题，但是xmake f --menu修改后save会没有生效的情况发生，好像有点像之前提过的这个 #1004

**Comment by waruqi** [comment]
我这测试ok 没法复现问题

**Comment by zwxf** [comment]
测试结果如图所示：
![test](https://user-images.githubusercontent.com/15979360/122146658-0b942900-ce8a-11eb-96b5-b7cce71e5485.gif)
看着像是先对config.h.in的文件进行替换生成config.h后才对配置文件进行更新，从而导致每次生成的config.h的变量都是上一次的配置。

**Comment by waruqi** [comment]
你确定是用的最新版或者 dev 么。。我这边测试一切ok 没啥问题

**Comment by zwxf** [comment]
是dev上最新的，我甚至xmake update uninstall后重新安装了xmake，还是这样的现象。
![DJHY}@{4B%M(MSB6J(U3 R7](https://user-images.githubusercontent.com/15979360/122170061-bb7c8d00-ceb0-11eb-92ab-5104593c9c92.png)

我打包了我自己测试最小环境，你可以测试下。
[xmake.zip](https://github.com/xmake-io/xmake/files/6660740/xmake.zip)

**Comment by waruqi** [comment]
```lua
option("Vendor-name")
    set_category("main-page")
    set_description("Setup vendor name, e.g. vendor CRRC")
    set_showmenu(true)

    set_values("Vendor_CRRC", "Vendor_DLNE", "Vendor_FUSE")
    set_default("Vendor_CRRC")

    if get_config("Vendor-name") == "Vendor_CRRC" then
	    set_configvar("CONFIG_VENDOR_CRRC", 1)
    elseif get_config("Vendor-name") == "Vendor_DLNE" then
        set_configvar("CONFIG_VENDOR_DLNE", 1)
    elseif get_config("Vendor-name") == "Vendor_FUSE" then
        set_configvar("CONFIG_VENDOR_FUSE", 1)
    end
```

你写的有问题，`get_config("Vendor-name")` 取值，取得就是 `xmake f --xxx` 设置的值，而 你在 `option("Vendor-name")` 定义阶段就去取值，那不就是 鸡生蛋 问题了么。。当然会慢半拍。。

要么  if + set_configvar 你放到 target 里面去做，不要在 option 的描述域判断。。。要么你放到 option/after_check 里面搞。。

```lua

option("Vendor-name")
    set_category("main-page")
    set_description("Setup vendor name, e.g. vendor CRRC")
    set_showmenu(true)

    set_values("Vendor_CRRC", "Vendor_DLNE", "Vendor_FUSE")
    set_default("Vendor_CRRC")

    --[[
    if get_config("Vendor-name") == "Vendor_CRRC" then
	    set_configvar("CONFIG_VENDOR_CRRC", 1)
    elseif get_config("Vendor-name") == "Vendor_DLNE" then
        set_configvar("CONFIG_VENDOR_DLNE", 1)
    elseif get_config("Vendor-name") == "Vendor_FUSE" then
        set_configvar("CONFIG_VENDOR_FUSE", 1)
    end]]

    after_check(function (option)

        if option:value() == "Vendor_CRRC" then
            option:set("configvar", "CONFIG_VENDOR_CRRC", 1)
        elseif option:value() == "Vendor_DLNE" then
            option:set("configvar", "CONFIG_VENDOR_DLNE", 1)
        elseif option:value() == "Vendor_FUSE" then
            option:set("configvar", "CONFIG_VENDOR_FUSE", 1)
        end
    end)
--option_end()
```

**Comment by zwxf** [comment]
好的，我试下
