### ISSUE TITLE
xmake tries to find link.exe multiple times

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#1353]
### Describe the bug
When managing a lot of targets in the same xmake.lua, it seems xmake tries to find link.exe for every target, slowing down generation.
Also it seems to do something costly (not logged) between checking for linker, as it doesn't take that much time in a small project. Maybe because of packages?

### Expected behavior
That xmakes finds link.exe once

### Error output
```
lynix@SirLynixVanDesktop:/mnt/c/Projets/Tests/xmake-build/test_linkcache$ xmake.exe -vr
checking for platform ... windows
checking for architecture ... x64
checking for vswhere.exe ... C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
checking for cl.exe ... C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2019
checking for dmd ... no
checking for ldc2 ... no
checking for gdc ... no
checking for zig ... no
checking for zig ... no
checking for link.exe ... C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64\link.exe
checking for the shared library linker (sh) ... link.exe
checking for the linker (ld) ... link.exe
checking for the shared library linker (sh) ... link.exe
checking for the linker (ld) ... link.exe
checking for the shared library linker (sh) ... link.exe
checking for the linker (ld) ... link.exe
checking for the shared library linker (sh) ... link.exe
checking for the linker (ld) ... link.exe
checking for the shared library linker (sh) ... link.exe
checking for the linker (ld) ... link.exe
checking for the shared library linker (sh) ... link.exe
checking for the linker (ld) ... link.exe
checking for the shared library linker (sh) ... link.exe
checking for the linker (ld) ... link.exe
checking for the shared library linker (sh) ... link.exe
checking for the linker (ld) ... link.exe
checking for the shared library linker (sh) ... link.exe
checking for the linker (ld) ... link.exe
checking for the shared library linker (sh) ... link.exe
checking for the linker (ld) ... link.exe
checking for the shared library linker (sh) ... link.exe
checking for the linker (ld) ... link.exe
checking for the shared library linker (sh) ... link.exe
checking for the linker (ld) ... link.exe
```

edit: it does the same with cl.exe:
```
checking for the linker (ld) ... link.exe
checking for cl.exe ... C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64\cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for the c++ compiler (cxx) ... cl.exe
```

### Related Environment

Please provide compiling and running environment information:

- xmake version: xmake v2.5.3
- os: Windows 10
- target platform: Windows 10

### Additional context
I managed to reproduce it with a very small part of my project xmake.lua:
```lua
local modules = {
	Audio = {
		Deps = {"NazaraCore"},
		Packages = {"libsndfile"}
	},
	Core = {},
	Graphics = {
		Deps = {"NazaraRenderer"}
	},
	Network = {
		Deps = {"NazaraCore"},
		Custom = function()
			if is_plat("windows") then 
				add_syslinks("ws2_32")
			end
		end
	},
	OpenGLRenderer = {
		Deps = {"NazaraRenderer"},
		Custom = function()
			if is_plat("windows") then
				add_syslinks("gdi32", "user32")
			else
				del_files("src/Nazara/OpenGLRenderer/Wrapper/Win32/**.cpp")
				del_files("src/Nazara/OpenGLRenderer/Wrapper/WGL/**.cpp")
			end

			if not is_plat("linux") then
				del_files("src/Nazara/OpenGLRenderer/Wrapper/Linux/**.cpp")
			end
		end
	},
	Physics2D = {
		Deps = {"NazaraUtility"},
		Packages = {"chipmunk2d"}
	},
	Physics3D = {
		Deps = {"NazaraUtility"}
	},
	Platform = {
		Deps = {"NazaraUtility"},
		Packages = {"libsdl"},
		Custom = function()
			if is_plat("windows") then
				add_defines("SDL_VIDEO_DRIVER_WINDOWS=1")
			elseif is_plat("linux") then
				add_defines("SDL_VIDEO_DRIVER_X11=1")
				add_defines("SDL_VIDEO_DRIVER_WAYLAND=1")
			elseif is_plat("macosx") then
				add_defines("SDL_VIDEO_DRIVER_COCOA=1")
			end
		end
	},
	Renderer = {
		Deps = {"NazaraPlatform", "NazaraShader"}
	},
	Shader = {
		Deps = {"NazaraUtility"}
	},
	Utility = {
		Deps = {"stb_image", "NazaraCore"},
		Packages = {"freetype"}
	},
	VulkanRenderer = {
		Deps = {"NazaraRenderer"},
		Custom = function()
			add_defines("VK_NO_PROTOTYPES")
			if is_plat("windows") then
				add_defines("VK_USE_PLATFORM_WIN32_KHR")
				add_syslinks("user32")
			elseif is_plat("linux") then
				add_defines("VK_USE_PLATFORM_XLIB_KHR")
				add_defines("VK_USE_PLATFORM_WAYLAND_KHR")
			elseif is_plat("macosx") then
				add_defines("VK_USE_PLATFORM_MACOS_MVK")
			end
		end
	}
}

set_project("NazaraEngine")

for name, module in pairs(modules) do
	target("Nazara" .. name)
	set_kind("shared")
	set_group("Modules")

	add_files("src/a.cpp")
end
```
(src/a.cpp is empty)

**Comment by waruqi** [comment]
These log is only displayed repeatedly, and the result is actually cached. But I still improved it on dev.

**Comment by waruqi** [comment]
These log is only displayed repeatedly, and the result is actually cached. But I still improved it on dev.

**Comment by SirLynix** [comment]
Thanks. However in my project I have a small time "about 1s" between the print of 
```
checking for the linker (ld) ... link.exe
checking for the shared library linker (sh) ... link.exe
```

What is xmake doing between those? It takes about 5s everytime before xmake starts building because of that.

**Comment by waruqi** [comment]
> Thanks. However in my project I have a small time "about 1s" between the print of
> 
> ```
> checking for the linker (ld) ... link.exe
> checking for the shared library linker (sh) ... link.exe
> ```
> 
> What is xmake doing between those? It takes about 5s everytime before xmake starts building because of that.

The latest dev version too? can you try `xmake -j1`?

```console
xmake f -cvD
xmake -vD -j1
```

If it is built in parallel, the first detection in each coroutine task will be performed at the same time, and they cannot be cached in time. Because they are still running.

**Comment by waruqi** [comment]
> Thanks. However in my project I have a small time "about 1s" between the print of
> 
> ```
> checking for the linker (ld) ... link.exe
> checking for the shared library linker (sh) ... link.exe
> ```
> 
> What is xmake doing between those? It takes about 5s everytime before xmake starts building because of that.

The latest dev version too? can you try `xmake -j1`?

```console
xmake f -cvD
xmake -vD -j1
```

If it is built in parallel, the first detection in each coroutine task will be performed at the same time, and they cannot be cached in time. Because they are still running.

**Comment by SirLynix** [comment]
I updated xmake to the dev version.
xmake now prints less linker message but the wait time is still the same.

I put the time it waits here:
```
checking for xmake::libsndfile ... libsndfile 1.0.30
finding libsdl from xmake ..
checking for xmake::libsdl ... libsdl 2.0.14
checking for cmake ... C:\Program Files\CMake\bin\cmake
checking for link.exe ... C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64\link.exe
checking for the static library archiver (ar) ... link.exe
checking for link.exe ... C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64\link.exe
checking for the linker (ld) ... link.exe
checking for link.exe ... C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64\link.exe
checking for the shared library linker (sh) ... link.exe

#### About 5 seconds here without printing anything

checking for cl.exe ... C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64\cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64\cl.exe ... ok
checking for flags (-std:c++17) ... ok
> cl.exe "-std:c++17" "/EHsc"
checking for flags (cl_external_includedir) ... ok
> cl.exe "-experimental:external" "-external:W0" "-external:Ithirdparty\include" "/EHsc"
checking for flags (/bigobj) ... ok
> cl.exe "/bigobj" "/EHsc"
checking for flags (/permissive-) ... ok
> cl.exe "/permissive-" "/EHsc"
checking for flags (/Zc:__cplusplus) ... ok
> cl.exe "/Zc:__cplusplus" "/EHsc"
checking for flags (/Zc:referenceBinding) ... ok
> cl.exe "/Zc:referenceBinding" "/EHsc"
checking for flags (/Zc:throwingNew) ... ok
> cl.exe "/Zc:throwingNew" "/EHsc"
checking for flags (/FC) ... ok
> cl.exe "/FC" "/EHsc"
checking for flags (/w44062) ... ok
> cl.exe "/w44062" "/EHsc"
checking for flags (/wd4251) ... ok
> cl.exe "/wd4251" "/EHsc"
```

I got this with `xmake -j1 -vDr NazaraGraphics`.

**Comment by waruqi** [comment]
This is what I said before. In fact, they are only checked once and the results have been cached.

> These log is only displayed repeatedly, and the result is actually cached

It should be caused by other problems, I will continue to look at it tomorrow. You can also print some logs in function os.execv to see which process is running causing it is blocked

**Comment by SirLynix** [comment]
I added a log in os.execv but nothing shows up when it waits :(

**Comment by waruqi** [comment]
It works for me. very fast for your demo.

I added some logs on test branch, you can switch to test version and run `xmake f -cvD`/`xmake -r -vD -j1`.

and let me see the verbose output.

**Comment by SirLynix** [comment]
Yes it's fast for the test project, not for the real one.

Nothing shows up.

Here's a gif:
![xmakenazara](https://user-images.githubusercontent.com/3002461/115676736-2ba6e080-a350-11eb-9be7-af0e60b2995f.gif)

Full log: https://pastebin.com/wTTdLsZH

**Okay I think I found it**

I added a log in `os.match` as this was one of the main differences between the test project and the real one:
```
os.match        C:\Program Files\xmake\languages\*
os.match        src\Nazara\Utility\**.cpp
os.match        src\Nazara\Utility\Posix\**.cpp
os.match        src\Nazara\Utility\Posix\**.cpp
os.match        *\Utility\Linux\**.cpp
os.match        *\Utility\Linux\**.cpp
os.match        src\Nazara\Platform\**.cpp
os.match        src\Nazara\Platform\Posix\**.cpp
os.match        src\Nazara\Platform\Posix\**.cpp
os.match        *\Platform\Linux\**.cpp
os.match        *\Platform\Linux\**.cpp
os.match        src\Nazara\Shader\**.cpp
os.match        src\Nazara\Shader\Posix\**.cpp
os.match        src\Nazara\Shader\Posix\**.cpp
os.match        *\Shader\Linux\**.cpp
os.match        *\Shader\Linux\**.cpp
os.match        src\Nazara\Renderer\**.cpp
os.match        src\Nazara\Renderer\Posix\**.cpp
os.match        src\Nazara\Renderer\Posix\**.cpp
os.match        *\Renderer\Linux\**.cpp
os.match        *\Renderer\Linux\**.cpp
os.match        src\Nazara\Graphics\**.cpp
os.match        src\Nazara\Graphics\Posix\**.cpp
os.match        src\Nazara\Graphics\Posix\**.cpp
os.match        *\Graphics\Linux\**.cpp
os.match        *\Graphics\Linux\**.cpp
```

Theses shows up during the wait, it turns out they are `add_files` and `del_files`. I don't know why xmake tries to find them multiple times.

However it seems xmake is taking a lot of time on that pattern beginning with a * : `"*/" .. name .. "/Linux/**.cpp"`, this was the cause of the slowdown. I replaced it with `del_files("src/Nazara/" .. name .. "/Linux/**.cpp")` and now it's fast as before!

Thanks for your help. Maybe there's something behind the fact it matches the same files multiples times?

**Comment by waruqi** [comment]
> os.match        *\Graphics\Linux\**.cpp
os.match        *\Graphics\Linux\**.cpp

single target? Are there multiple targets containing these same file lists?

**Comment by SirLynix** [comment]
Only one, here's my full xmake.lua (work in progress): https://pastebin.com/3bkyJyd8

**Comment by waruqi** [comment]
> Only one, here's my full xmake.lua (work in progress): https://pastebin.com/3bkyJyd8

not only one, too much targets. The source file of each target will recall os.match to obtain the source file list, but each target will only call os.match once.

```lua
for name, module in pairs(modules) do
    target("Nazara" .. name)
    add_files("src/Nazara/" .. name .. "/**.cpp")
```

**Comment by waruqi** [comment]
> However it seems xmake is taking a lot of time on that pattern beginning with a * : "*/" .. name .. "/Linux/**.cpp", this was the cause of the slowdown. I replaced it with del_files("src/Nazara/" .. name .. "/Linux/**.cpp") and now it's fast as before!

If your source file directory level is too deep, recursively traversing the directory will be very slow.

**Comment by SirLynix** [comment]
> If your source file directory level is too deep, recursively traversing the directory will be very slow.
> Therefore, it is recommended to use xxx/*.cpp instead of **.cpp to avoid deep recursion.
I though del_files was applying a pattern on found files, not performing another file match, wouldn't it be faster?

> not only one, too much targets. The source file of each target will recall os.match to obtain the source file list, but each target will only call os.match once.
Yes but `del_files("*\Graphics\Linux\**.cpp")` was only called once, yet it appeared two times in os.match.

**Comment by waruqi** [comment]
Of course, I will also try to cache the matching results of os.match across targets, but this requires a lot of details to be considered. Because the files on the disk may change at any time

**Comment by waruqi** [comment]
> Yes but `del_files("*\Graphics\Linux\**.cpp")` was only called once, yet it appeared two times in os.match.

If os.files() pattern is not matched, xmake also call os.dirs() to match dirs. so two times.

https://github.com/xmake-io/xmake/blob/e124d5d2cc26aa76a0c295791c2ba18f101de7f8/xmake/core/project/target.lua#L1193-L1198

**Comment by SirLynix** [comment]
Okay, thanks for the explanation.

**Comment by waruqi** [comment]
I have cached the matching results of os.match across targets on dev. It should be possible to reduce some duplicate matches, but two matches of del_files cannot be avoided.

**Comment by SirLynix** [comment]
Wouldn't it be possible to make it so del_files doesn't match files at all? I'm thinking of this:

1) Fetch all files (add_files) with os.match in a list
2) For every del_files, iterate over the file list and remove files matching del_files patterns.

This way, no need for del_files to scan files at all.

**Comment by waruqi** [comment]
This actually has nothing to do with del_files. The root cause is that if a path pattern that does not exist is passed, there will be two matches.

add_files/del_files("pattern")

1. pattern found -> only os.files() -> one match
2. pattern not found -> os.files() -> try os.dirs() -> two matches.

os.files -> os.match(file)
os.dirs -> os.match(dir)

```lua
 local results = os.files(file) 
 if #results == 0 then 
     -- attempt to find source directories if maybe compile it as directory with the custom rules 
     if #self:filerules(file) > 0 then 
         results = os.dirs(file) 
     end 
```

**Comment by SirLynix** [comment]
I understand. What I don't understand is why del_files has to match files at all 😅

**Comment by waruqi** [comment]
In theory, it is possible to filter directly from the existing file list and no longer execute os.match, but this requires a lot of work. Maybe I will improve it later, but I am not sure that it can be supported now.

**Comment by waruqi** [comment]
I have improved del_files(), you can try it again.

**Comment by SirLynix** [comment]
I can confirm it's working, and it's faster than before. Thank you!
And now as a bonus del_files no longer complains when no files matches 😄
