### ISSUE TITLE
I have met ”error“ while using xmake.

### ISSUE THREAD

**Issue by sapling-miao** [xmake-io/xmake#1357]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

在妙算2g刷机重新配置环境后，xmake编译opencv-c++代码时zlib报错依赖冲突
（之前虚拟机上的xmake能编译运行这些代码，排除代码错误，认为是环境配置问题；
刷机重装前妙算2g上面xmake编译代码能用，排除xmake不能在妙算上运行，认为是环境配置问题）

### 期待的结果

期待xmake能够正常编译运行代码，谢谢大佬orz，球球了

### 错误信息

如果可能，请尽量附加程序运行过程中的错误输出信息。

> 如果是xmake相关编译问题，请加上`-vD`参数运行，并给出详细编译输出信息。

xmake -vD输出信息：

checking for platform ... linux
checking for architecture ... arm64-v8a
checking for gcc ... /usr/bin/gcc
checkinfo: runv(dmd --version) failed(127)
checking for dmd ... no
checkinfo: runv(ldc2 --version) failed(127)
checking for ldc2 ... no
checkinfo: runv(gdc --version) failed(127)
checking for gdc ... no
checkinfo: runv(zig version) failed(127)
checking for zig ... no
checkinfo: runv(zig version) failed(127)
checking for zig ... no
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /bin/gzip
checking for tar ... /bin/tar
checking for ping ... /bin/ping
pinging for the host(gitee.com) ... 55 ms
pinging for the host(gitlab.com) ... 226 ms
pinging for the host(github.com) ... 395 ms
error: @programdir/core/main.lua:294: @programdir/core/sandbox/modules/import/core/base/task.lua:65: @programdir/modules/private/action/require/impl/package.lua:577: package(zlib/1.2.11:{}): conflict dependences with package(zlib/1.2.11/linux/arm64-v8a:{})!
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:793]: in function 'raise'
    [@programdir/modules/private/action/require/impl/package.lua:577]: in function '_load_package'
    [@programdir/modules/private/action/require/impl/package.lua:645]: in function '_load_packages'
    [@programdir/modules/private/action/require/impl/package.lua:657]: in function '_load_packages'
    [@programdir/modules/private/action/require/impl/package.lua:779]: in function 'load_packages'
    [...modules/private/action/require/impl/install_packages.lua:369]: in function 'install_packages'
    [@programdir/modules/private/action/require/install.lua:85]: in function 'install_packages'
    [@programdir/actions/config/main.lua:341]:
    [C]: in function 'load'
    [@programdir/core/base/task.lua:519]: in function 'run'
    [@programdir/core/sandbox/modules/import/core/base/task.lua:63]: in function 'run'
    [@programdir/actions/build/main.lua:113]:
    [C]: in function 'load'
    [@programdir/core/base/task.lua:519]: in function 'run'
    [@programdir/core/main.lua:292]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:342]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:793: in function 'raise'
        @programdir/core/main.lua:294: in function 'cotask'
        @programdir/core/base/scheduler.lua:342: in function <@programdir/core/base/scheduler.lua:339>

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.3
- xmake运行平台：妙算2g
- xmake目标平台：妙算2g

### 其他信息

请提供其他附加信息帮助我们诊断问题(比如截图，xmake.lua或者可复现的demo)，以及你遇到的问题的一些背景信息。

错误信息都粘在上面啦

**Comment by waruqi** [comment]
更新下 xmake 到 dev 再试试

**Comment by sapling-miao** [comment]
> 更新下 xmake 到 dev 再试试

请问您的意思是xmake update后在自己代码的dev分支下编译吗？如果是这个意思，我就是这种情况下遇到报错的；如果是其他意思，辛苦您进一步解释，谢谢大佬orz

**Comment by waruqi** [comment]
更新到 xmake dev 版本 xmake update dev

**Comment by sapling-miao** [comment]
> 更新到 xmake dev 版本 xmake update dev
请问一定要github上的这个dev嘛？我的环境默认gitee.com/tboox/xmake.git，xmake update dev后依旧同样报错；从github下载失败
![giteeupdate后依旧同样报错](https://user-images.githubusercontent.com/56779515/115820403-4e5df580-a433-11eb-8606-1d5bbb5d2023.jpg)
![github无法下载报错](https://user-images.githubusercontent.com/56779515/115820443-66357980-a433-11eb-894e-7ec0290f326f.jpg)

**Comment by waruqi** [comment]
执行下 `source ~/.xmake/profile` 试试

**Comment by sapling-miao** [comment]
> 执行下 `source ~/.xmake/profile` 试试

说找不到profile，是我少下了什么东西嘛？~/.xmake下的东西只有如下
![微信图片_20210423130932](https://user-images.githubusercontent.com/56779515/115821330-2c657280-a435-11eb-998c-7bee352c1e35.jpg)

**Comment by waruqi** [comment]
为什么 你这会提示 sudo 。。感觉安装过程中，遇到了 perm 问题，装不进去，然后切到 sudo 去了，然后中断了。。

这个你自己研究下吧，反正没装上了，用的还是老版本。。不行了就自己源码编译安装，或者删了重装，文档有完整安装说明

**Comment by wangzhankun** [comment]
修复问题的步骤：
1. `bash <(curl -fsSL https://xmake.io/shget.text)`执行重新安装
2. 编译我们的软件仍然报错`zlib conflict`
3. 执行`xmake update -s dev`出错
4. 切换到root模式执行`xmake update -s dev`出现`unzip or 7zip not found`的报错
5. 安装unzip
6. root用户执行`xmake update -s dev`仍然提示`unzip or 7zip not found`
7. root用户编译软件`xmake --root`发现`updating from git`更新成功且编译通过
8. 切换回普通用户，删除`.xmake和build`目录，重新执行`xmake`成功编译
是不是`unzip`没有安装导致的问题呢？

**Comment by waruqi** [comment]
> bash <(curl -fsSL https://xmake.io/shget.text)执行重新安装
编译我们的软件仍然报错zlib conflict

这一步可以直接指定从 dev 版本安装，否则默认安装的还是 master 版本，我还没更新到 master，`bash <(curl -fsSL https://xmake.io/shget.text) dev`

>  执行xmake update -s dev出错
切换到root模式执行xmake update -s dev出现unzip or 7zip not found的报错

unzip 必须的，得手动装下

> root用户执行xmake update -s dev仍然提示unzip or 7zip not found
root用户编译软件xmake --root发现updating from git更新成功且编译通过

不要 root 下执行，xmake 默认禁用 root 使用，你混着用，切换非 root 用户，更容易出一堆问题，因为已经root创建了一堆临沭文件无法正常访问

> 是不是unzip没有安装导致的问题呢？如果是的话为啥在编译的时候没有提示呢？同时为什么在普通用户下执行xmake update -s dev也没有提示呢？
> 同时为什么在普通用户下执行xmake update -s dev也没有提示呢？

也许是缓存导致没有重新检测 unzip 而已，root下新环境就去重新检测了下。。xmake update 不需要 unzip ，即使没提示出来，那说明正常往下走了，应该也不影响的。

**Comment by wangzhankun** [comment]
那zlib conflict导致的编译失败原因是什么呢？后续又莫名其妙正常了。

**Comment by waruqi** [comment]
> 那zlib conflict导致的编译失败原因是什么呢？后续又莫名其妙正常了。

你成功更新到 dev 版本了，不就正常了么。。最早就跟你说，我改进过了，让你更新到 dev 试试。。

只是你之前的每次更新，都没成功，一直还是运行的老版本。。

**Comment by wangzhankun** [comment]
没有成功更新呀，更新失败了呀

**Comment by waruqi** [comment]
看下安装后的版本，对应 lua file，有没有 https://github.com/xmake-io/xmake/blob/ef17fec2bc80c6ec4ad537e74748762d18e92606/xmake/modules/private/action/require/impl/package.lua#L694-L705 这个 function ，有的话，就是更新过去了

**Comment by wangzhankun** [comment]
我没明白要怎么看呀？我本地没有xmake的源文件吧？

**Comment by waruqi** [comment]
> 我没明白要怎么看呀？我本地没有xmake的源文件吧？

执行 xmake l os.programdir ，显示的路径下面。。

所有 lua 脚本都在。

**Comment by wangzhankun** [comment]
> 看下安装后的版本，对应 lua file，有没有
> 
> https://github.com/xmake-io/xmake/blob/ef17fec2bc80c6ec4ad537e74748762d18e92606/xmake/modules/private/action/require/impl/package.lua#L694-L705
> 
> 这个 function ，有的话，就是更新过去了

my没有这个函数。
![image](https://user-images.githubusercontent.com/35724924/115841300-3c8a4b80-a44f-11eb-8e94-547a86e87c2b.png)

**Comment by waruqi** [comment]
那说明还是老版本，至于为什么没报错，那我就不知道了

xmake l os.programdir 路径贴我看下

另外可以继续尝试：`bash <(curl -fsSL https://xmake.io/shget.text) dev` 直接更新安装到 dev 版本。

**Comment by sapling-miao** [comment]
> 那说明还是老版本，至于为什么没报错，那我就不知道了
> 
> xmake l os.programdir 路径贴我看下
> 
> 另外可以继续尝试：`bash <(curl -fsSL https://xmake.io/shget.text) dev` 直接更新安装到 dev 版本。

![微信图片_20210423162714](https://user-images.githubusercontent.com/56779515/115842905-def6fe80-a450-11eb-8e7f-91208f67ce3c.jpg)

**Comment by waruqi** [comment]
目录对的，那按理 执行

bash <(curl -fsSL https://xmake.io/shget.text) dev

还是 xmake update -s dev 都是可以更新过去的

除非这个目录的权限不对，导致copy失败了

**Comment by wangzhankun** [comment]
> 目录对的，那按理 执行
> 
> bash <(curl -fsSL https://xmake.io/shget.text) dev
> 
> 还是 xmake update -s dev 都是可以更新过去的
> 
> 除非这个目录的权限不对，导致copy失败了

目录权限是755

**Comment by waruqi** [comment]
> > 看下安装后的版本，对应 lua file，有没有
> > https://github.com/xmake-io/xmake/blob/ef17fec2bc80c6ec4ad537e74748762d18e92606/xmake/modules/private/action/require/impl/package.lua#L694-L705
> > 
> > 这个 function ，有的话，就是更新过去了
> 
> my没有这个函数。
> ![image](https://user-images.githubusercontent.com/35724924/115841300-3c8a4b80-a44f-11eb-8e94-547a86e87c2b.png)

根据你这的反馈，应该还是老版本。。

但是 https://github.com/xmake-io/xmake/issues/1358#issuecomment-825506906 这里你又说是 内容完全相同，那应该是最新版本。。

感觉的怪。。package.lua proxy.lua 这两文件都发到附件 给我看下。。

**Comment by wangzhankun** [comment]
我这是两个环境，这里的issue是在妙算2（tx2）上面，#1358是在wsl上面。

**Comment by wangzhankun** [comment]
这个issue的环境是：
- OS ： ubuntu 16.04 armv8

**Comment by waruqi** [comment]
那就只能你先自己研究下，确保更新到 dev 版本就行了。。

直接 `bash <(curl -fsSL https://xmake.io/shget.text) dev` 重装也可以。

**Comment by wangzhankun** [comment]
先这样吧，不升级了，怕升级之后又出问题。能正常编译运行就行
