### ISSUE TITLE
Allow set_configvar function within option and target scopes

### ISSUE THREAD

**Issue by sumeetchhetri** [xmake-io/xmake#1359]
option("ABC")
--check header or library
--should be able to set config var here
on_check(...
set_configvar('ABC', 1)
end
option_end()

target("ABC")
--check header or library
--should be able to set config var here
on_load(...
set_configvar('ABC', 1)
end
target_end()

Very difficult to currently keep the configuration file small due to this very important feature missing.
@waruqi Can we consider this?

**Comment by waruqi** [comment]
? option/target support set_configvar. https://github.com/tboox/tbox/blob/8c42b2c251793861eb85ffdf7e7c2307b129c7ae/src/xmake.lua#L18

**Comment by sumeetchhetri** [comment]
I forgot to correctly update the description, can we allow support for set_configvar within the on_check on_load function scopes?

**Comment by waruqi** [comment]
target:set("configvar", "xxx").  option:set("configvar", "xxx")

**Comment by sumeetchhetri** [comment]
Thanks for the information, so in the options scope, is the add({includedirs = p}) command allowed like it's allowed in the target scope? At-least it seems to be missing in the documentation.

**Comment by waruqi** [comment]
target:add("includedirs", "xxx")

I haven't had time to write a script domain interface document.

**Comment by sumeetchhetri** [comment]
The option:set("configvar", "xxx") does not work as you mentioned, whenever the target specifies an option dependency, all config_var's set within the option scope should be directly added to the target, this is what I have asked for. Also I just tested with the option:set("configvar", "xxx"), it does not work, both options, option:set("configvar", "xxx") and option:add("includedirs", "xxx") should work as intended by adding the required config to the target scope. I hope the requirement is clear now, these function should be allowed to be set within the on/after/before check functions in the option scope.

**Comment by waruqi** [comment]
It works for me.

```lua

option("test")
    set_default(true)
    after_check(function (option)
        option:set("configvar", "TEST", "hello")
    end)

target("test")
    set_kind("binary")
    add_files("src/*.cpp")
    add_options("test")
    add_configfiles("config.h.in")
```

```console
$ cat ./config.h.in
#define TEST ${TEST}
```

```console
$ xmake f -c -vD
generating config.h.in to build/config.h ..
  > replace TEST -> hello
generating config.h.in ...
```

```console
$ cat ./build/config.h
#define TEST hello
```

**Comment by sumeetchhetri** [comment]
Oops, I tried, option:set("TEST", "hello"), what about the option:add("includedirs", "/usr/some/path/include"), is this also supported?

**Comment by waruqi** [comment]
support

**Comment by sumeetchhetri** [comment]
According to the documentation option does not have an add_includedirs method like the target does, can you please confirm this once more?

**Comment by waruqi** [comment]
see https://xmake.io/#/manual/configuration_option?id=option

in a table, it will go to the target/add_includedirs

![image](https://user-images.githubusercontent.com/151335/115838155-f54e8b80-a44b-11eb-9991-078a0edde6d8.png)

Because there are too many interfaces, I don't have time to write.
