### ISSUE TITLE
Option Dependency issues

### ISSUE THREAD

**Issue by sumeetchhetri** [xmake-io/xmake#1360]
Currently if the options have any dependency hierarchy then xmake does not correctly honour the same.

Consider,

option("ONE")
--some config
--on_check()...
option_end()

option("TWO")
add_deps("ONE")
--some config
--on_check()...
option_end()

option("THREE")
add_deps("TWO")
--some config
--on_check()...
option_end()

The documentation says that "on_check will only be executed when the default value is not set", how do you correctly set the dependency in this case then.

**Comment by waruqi** [comment]
Option dependency only affects the order of detection and does not inherit the value

**Comment by sumeetchhetri** [comment]
Don't you think it should also inherit the value, it will allow more then truly allow configuration/option hierarchies?

**Comment by waruqi** [comment]
No, the dependencies are too complex, and direct inheritance cannot be flexibly configured, such as complex option combinations and non-boolean values. .You can make more flexible judgments and settings in after_check.

https://github.com/tboox/tbox/blob/8c42b2c251793861eb85ffdf7e7c2307b129c7ae/src/xmake.lua#L59-L62

**Comment by sumeetchhetri** [comment]
Noted with thanks, will close the issue in that case.
