### ISSUE TITLE
Fetching remote toolchain for mingw

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1362]
### 你在什么场景下需要该功能？

xmake f -p mingw时若未检测到mingw环境则自动下载mingw-w64作为toolchain

### 描述可能的解决方案

类似llvm

### 其他信息

可以取代tinycc作为windows上新手入门的选择，无需自行下载安装设置环境变量等

**Comment by waruqi** [comment]
既然 mingw-w64 已经被收录到 xmake-repo ，那么 原本就已经支持远程拉取集成了。。

```lua
add_requires("mingw-w64")

target("testmingw")
    set_kind("binary")
    add_files("src/*.cpp")
    set_toolchains("mingw@mingw-w64")
```

配置方式参考 llvm ，可以看下文档。。

```console
$ xmake
```

我试了下，是可以编译过的。。

目前远程拉取必须走 `set_toolchains`，不用特地切到 `xmake f -p mingw`，当然如果配置了 set_toolchains，切到 mingw 一样。。

至于不设置 set_toolchains，走 `xmake f -p mingw` 直接拉取，暂时不支持，也不打算考虑支持。。用户 配置一行 set_toolchains 也不会麻烦多少，而且更直观可读。
