### ISSUE TITLE
触发 .dSYM文件 生成时，Linux 交叉编译 strip时 使用了 pc 的 strip

### ISSUE THREAD

**Issue by OuYangPaste** [xmake-io/xmake#1363]
### 描述问题
    我们的 root 域统一设定了
    if is_mode("release") then
        set_symbols("hidden")  
    end
    想在生成动态库时也能隐藏符号，有个同事某个target 想单独关闭掉这个选项，于是增加了个 set_symbols("debug")，而 release 又自带 set_strip("all"), 这两个选项触发了 .dSYM文件的生成，在 strip 因使用了 pc 环境的 strip 报错

    尝试过 xmake f -p cross 是不会有这个问题的，但我们嵌入式平台本身就是linux，大家都不太想定义多一个 plat name，虽然这个问题没有太大影响，但是有个报错点在这里就很不舒服了

### 期待的结果
     触发生成 .dSYM 文件后使用 strip 前检测和优先选择所设定工具链环境中提供的 strip

### 相关环境
- xmake版本： v2.5.3+202104241641
- xmake运行平台：Linux
- xmake目标平台：嵌入式 Linux

### 其他问题
    在找上面这个问题的时候，曾经把 xmake 降级到 2.5.2，后来无论是 xmake update 还是 xmake update 2.5.3 或者 xmake update dev, 虽然显示安装成功，但是 ~/.local/bin/xmake 修改时间一直还是 降级到 2.5.2 时的时间点， version 显示也是 2.5.2，后来我 xmake update -v 看详细信息的时候又安装成功了，最近比较忙，先提给你看看有没有什么头绪，有空再研究下原因

**Comment by waruqi** [comment]
原本就是会从 toolchain 中取 strip，前提是 你用的是什么工具链，具体 `xmake f -cvD; xmake -rvD` 得先贴下，否则我没法确认什么原因，凡事先贴错误详情和环境工具信息。。。

你使用用的工具链，只有配置了 set_toolset("strip", ... ) 到你对应的工具量 strip ，才能用上。。

**Comment by OuYangPaste** [comment]
惆怅， 现在出差了不在公司了没有环境，用的是远程拉取的交叉编译链

**Comment by waruqi** [comment]
走远程拉取的  可以先尝试下  dev 版本的 xmake ，如果还是不行，那等有环境了 再给我份完整 log

**Comment by OuYangPaste** [comment]
尴尬，这个问题是早上的时候发现的，一直忙，刚才出差在路上才有空上来提issue, 现在手头上没有环境，用的是远程拉取的交叉编译链

**Comment by OuYangPaste** [comment]
dev 版本试过了也是一样，我明天回公司重现一下

**Comment by OuYangPaste** [comment]
刚才验证过，更新到最新的 dev 没有问题了
