### ISSUE TITLE
xmake 在 windows 上构建 C++ 项目遇到的非常奇怪的未知问题

### ISSUE THREAD

**Issue by idealvin** [xmake-io/xmake#1365]
### 描述问题

- 所述 C++ 项目地址 [idealvin/co](https://github.com/idealvin/co)

- 现象 1
  - 1. linux 系统上能正常构建.
  - 2. 一台 windows 机器上构建失败，vs 版本:  vs2015
  - 3. 另一台 windows 机器上构建失败， vs 版本: vs2019
  - 4. 构建报错很奇怪，好像是语法层面不支持，类似下面:
     ```sh
     D:\cc\co\include\co\so\rpc.h(45): error C2653: “tcp”: 不是类或命名空间名称
     D:\cc\co\include\co\so\rpc.h(45): error C2460: “so::rpc::Client::_tcp_cli”: 使用正在定义的“so::rpc::Client”
     D:\cc\co\include\co\so\rpc.h(31): note: 参见“so::rpc::Client”的声明
     ```

- 现象 2
   - 用下述命令生成 vsproject 文件，直接在 vs 中编译，也报错，但报错信息与现象1中不同.
      ```sh
      xmake project -k vs2019 -a "x86,x64" -m "debug,release"
      ```
  用xmake生成的project，直接在vs中编译，报错信息:
  ```sh
  1>Performing Custom Build Tools
  1> Assembling: include
  1>MASM : fatal error A1000: cannot open file : include
  1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: “..\..\..\src\co\context\context_x64.asm”的自定义生成已退出，代码为 1。
  ```
  
  追踪发现现象2的原因是 xmake 生成的汇编命令有误，多了个 `include`: 
  ```sh
  ml64.exe -c -nologo -W3  include -Fo..\..\..\build\.objs\libco\windows\x64\debug\src\co\context\context_x64.asm.obj ..\..\..\src\co\context\context_x64.asm
  ```
  手动去掉 `include` 后汇编文件能正常编译，但现象1中的问题仍然存在.

### 期待的结果

linux 与 windows 上都能正常构建整个 C++ 项目.

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本： 2.5.3
- xmake运行平台： windows x64
- xmake目标平台： windows x64

**Comment by waruqi** [comment]
现象1的问题，跟 xmake 没什么关系，你 xmake -v 获取原始编译命令， 直接打开 vs prompt 下 编译，一样的问题，可以拿 tcp.cc 做测试，去掉 openssl 等包的干扰。。一样的问题

```console
Y:\co-master>cl.exe -c /EHsc -nologo -Zi -FS -W3 -O2 -Iinclude -MD -EHsc -Fobuil
d\\.objs\\libco\\windows\\x64\\release\\src\\so\\tcp.cc.obj src\\so\\tcp.cc
tcp.cc
Y:\co-master\include\co\so\rpc.h(45): error C2653: 'tcp': is not a class or name
space name
Y:\co-master\include\co\so\rpc.h(45): error C2460: 'so::rpc::Client::_tcp_cli':
uses 'so::rpc::Client', which is being defined
Y:\co-master\include\co\so\rpc.h(31): note: see declaration of 'so::rpc::Client'
```

似乎跟某些 include 干扰有关，这属于自身项目的代码编译问题了，你自己看看吧，跟 xmake 没啥关系。

另外一个问题，我后两天看下，今天没啥时间

**Comment by idealvin** [comment]
@waruqi 
嗯，第一个问题确实与 xmake 没有关系，我徒手建的vs项目也编译报错。屏蔽掉 rpc.h 与 rpc.cc 两个文件就能正常编译。然而这两个文件很正常啊，奇了怪了，就 windows 上有这问题...

**Comment by waruqi** [comment]
问题2 我修复了，可以更新到 dev 版本再试试。

**Comment by idealvin** [comment]
> 问题2 我修复了，可以更新到 dev 版本再试试。

@waruqi 
用 dev 版本测试，问题 2 已经解决了
