### ISSUE TITLE
support for apple silicon chip arm64

### ISSUE THREAD

**Issue by JackieMa000** [xmake-io/xmake#1377]
Please support for apple silicon arm64, thanks very much!

xmake
[ 25%]: compiling.release main.c
[ 50%]: linking.release main
error: Undefined symbols for architecture arm64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by waruqi** [comment]
please run `xmake f -vD; xmake -rvD` and let me see the output.

**Comment by JackieMa000** [comment]
I figured out, it was my mistake. It works well on Apple Silicon chip now.
xmake and tbox, they are both awesome tools. Thanks for the great work!
