### ISSUE TITLE
xrepo clean won't clean old caches

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1378]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

.xmake/cache/packages下面有上个月的cache 2104和这个月的2105，执行xrepo clean仅清除了2105文件夹，2104没有被清除

### 期待的结果

xrepo clean应该清空所有缓存

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.3 dev
- xmake运行平台：windows
- xmake目标平台：windows

**Comment by waruqi** [comment]
每次 build 后台进程 都会自动清理上个月的缓存才对，通常不需要手动清理，如果没有，你可以调下这块。

https://github.com/xmake-io/xmake/blob/ba285402bd1f5fed3eedc5a507ec98a232de8c27/xmake/actions/build/cleaner.lua#L87-L92

**Comment by waruqi** [comment]
之前自动清理的 cachedir 有点问题，我修复了。。可以更新下，然后 重启系统 或者等明天再试下，每天都会清理一次上月 cache

**Comment by xq114** [comment]
这个问题还是存在，直接调用`xmake l xxx/cleaner.lua`可以正常执行清理，但是清理不会自动执行

https://github.com/xmake-io/xmake/blob/b00f05dd421c8fd8aab0cc6716ecedf185fe32e4/xmake/actions/build/cleaner.lua#L57

怀疑是这个process.open():close()的原因，设置detached之后process.openv应该立即返回，这时候调用close()会不会导致清理还没结束进程就中止了？

**Comment by waruqi** [comment]
detach 了，进程就完全脱离了，后台运行，close只是释放资源，不会去强杀它。

除非是没走到清理逻辑。目前是每个项目，每天的首次 build 才会清理，之后就不会执行到这了。除非再等明天。

你可以加点 log 调试下这个脚本文件。

**Comment by xq114** [comment]
> detach 了，进程就完全脱离了，后台运行，close只是释放资源，不会去强杀它。
> 
> 除非是没走到清理逻辑。目前是每个项目，每天的首次 build 才会清理，之后就不会执行到这了。除非再等明天。
> 
> 你可以加点 log 调试下这个脚本文件。目前我这运行正常，仅仅只保留了当月的缓存目录，之前的目录确实被清理掉了。

我调试过，清理可以走到这条语句，只是这条语句没发挥作用。cleaner.log会正常建立，但其中内容空白，缓存文件也没有被清理。

**Comment by waruqi** [comment]
> > detach 了，进程就完全脱离了，后台运行，close只是释放资源，不会去强杀它。
> > 除非是没走到清理逻辑。目前是每个项目，每天的首次 build 才会清理，之后就不会执行到这了。除非再等明天。
> > 你可以加点 log 调试下这个脚本文件。目前我这运行正常，仅仅只保留了当月的缓存目录，之前的目录确实被清理掉了。
> 
> 我调试过，清理可以走到这条语句，只是这条语句没发挥作用。cleaner.log会正常建立，但其中内容空白，缓存文件也没有被清理。

win? detach 去掉试试呢？或者改成 os.execv 直接回显看看呢。

**Comment by waruqi** [comment]
刚看了下，win上是没清掉，回头有时间 我再看看吧

**Comment by waruqi** [comment]
刚改了下，更新到 dev 再试试，另外，目前只能清上个月的，再之前一个月的，你就自己删下好了

**Comment by xq114** [comment]
现在可以了
