### ISSUE TITLE
xmake fails to install package from local source

### ISSUE THREAD

**Issue by Glinrens-corner** [xmake-io/xmake#1381]
### Describe the bug
When xmake finds that the package is locally available it fails to install it.

I could trigger this bug in two ways:
 1. by putting the package as a git directory into a pkg_searchdir. (simulating a manually downloaded package).
 2. by specifying a local git directory as url. (Is this officially supported?)

xmake seems to have found the local package but was unable to install it.

### Expected behavior
I expected xmake to be able to install the package after having found it.

### Error output
I have prepared two minimal examples for the two cases. See attached files.
To reproduce go into the unpacked top level directory and run example.sh via bash.
ATTENTION: the first example will change your pkg_searchdirs configuration!!!

[xmake_failed_manual_download.tar.gz](https://github.com/xmake-io/xmake/files/6420779/xmake_failed_manual_download.tar.gz)
[xmake_failed_local_git.tar.gz](https://github.com/xmake-io/xmake/files/6420788/xmake_failed_local_git.tar.gz)

I have included the output of my xmake run in output.txt in the respective directory.

the relevant lines seem to be:
...

> finding mydep from pkgconfig ..
> checking for pkg-config ... /usr/bin/pkg-config
> finding mydep from system ..
> checking for mydep ... no
> /usr/bin/git clean -d -f -x
> 
> error: @programdir/modules/private/async/runjobs.lua:217: @programdir/core/sandbox/modules/os.lua:182: cannot change directory /home/glinren/.xmake/cache/packages/2105/m/mydep/0.0.1/source, not found this directory No such file or directory
> stack traceback:
>     [C]: in function 'error'
>     [@programdir/core/base/os.lua:788]: in function 'raise'
>     [@programdir/core/sandbox/modules/os.lua:182]: in function 'cd'
>     [.../modules/private/action/require/impl/actions/install.lua:121]: in function 'action_install'
>     [...modules/private/action/require/impl/install_packages.lua:261]: in function 'jobfunc'
>     [@programdir/modules/private/async/runjobs.lua:193]:
>     [C]: in function 'trycall'
>     [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
>     [@programdir/modules/private/async/runjobs.lua:186]: in function 'cotask'
>     [@programdir/core/base/scheduler.lua:317]:
> 
> stack traceback:
>         [C]: in function 'error'
>         @programdir/core/base/os.lua:788: in function 'raise'
>         @programdir/modules/private/async/runjobs.lua:217: in function 'catch'
>         @programdir/core/sandbox/modules/try.lua:127: in function 'try'
>         @programdir/modules/private/async/runjobs.lua:186: in function 'cotask'
>         @programdir/core/base/scheduler.lua:317: in function <@programdir/core/base/scheduler.lua:315>
> 
> 

### Related Environment

Please provide compiling and running environment information:

- xmake version: xmake v2.5.3+202104262042
- os: openSUSE Leap 15.1
- target platform: x86

### Additional context
The problem seems to be that package downloading [download.lua](https://github.com/xmake-io/xmake/blob/master/xmake/modules/private/action/require/impl/actions/download.lua)  line:53 
realizes that the package is locally available and does nothing (except cleaning it).

when xmake tries to later install it, [install.lua](https://github.com/xmake-io/xmake/blob/master/xmake/modules/private/action/require/impl/actions/install.lua) it expects the package in the cache subdirectory, which hasn't even been created.

**Comment by waruqi** [comment]
I have fixed it on dev, you can update and try it again.
