### ISSUE TITLE
xrepo-hook.psm1 is still misplacing in windows installer

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1382]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
运行`xmake update dev`之后xrepo-hook.psm1放在了xmake.exe同文件夹下，没有放在scripts/文件夹下，导致xrepo失败

**Comment by waruqi** [comment]
应该可以了，等 https://ci.appveyor.com/project/waruqi/xmake/builds/39017495 上跑完，在执行 update 试试

**Comment by xq114** [comment]
还是不行，https://nsis.sourceforge.io/Reference/File 用
```
File /oname=scripts\xrepo-hook.psm1 "..\scripts\xrepo-hook.psm1"
```
或许可以

**Comment by waruqi** [comment]
我之前验证过 拉下来是可以的，你可以开个pr改下 从action ci上拉下 artifacts试试

**Comment by xq114** [comment]
之前我提取安装包的方式不对，现在没问题了
