### ISSUE TITLE
add option to all targets

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1383]
### 你在什么场景下需要该功能？

一些全局的定义（define、cppflags等）需要加到所有的target上，同时又需要用option控制；目前option只能加到单个target上，希望能全局调用add_options("xxx")默认加到所有的target上。

例如一个项目有20个target，20个option，如果一个一个target去加，每加一个全局option都非常麻烦（找到各个文件夹下所有target一个一个加），每加一个target也非常麻烦（一个target要写20行）

### 描述可能的解决方案

```lua
option("foo")
...
option_end()
add_options("foo") -- add to all targets
```

**Comment by waruqi** [comment]
不是原本就支持么 这样不行？所有 target的 set_xxx add_xxx 接口都能全局设置

**Comment by xq114** [comment]
运行xmake f -c 之后好了
