### ISSUE TITLE
Windows v2.5.3+202104080841 创建空的工程后执行xmake报错：error: table index is nil

### ISSUE THREAD

**Issue by ZoroDM** [xmake-io/xmake#1385]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

1.  xmake create -P . -l c++ testxmake, 创建一个demo工程；
2. 在工程的xmake.lua目录下执行 xmake, 执行后出现以下错误：
H:\Project\test\testxmake>xmake run
checking for platform ... windows
checking for architecture ... x64
error: table index is nil

H:\Project\test\testxmake>
### 期待的结果

可以正常运行，并输出 hello world 打印

### 错误信息

H:\Project\test\testxmake>xmake -vD
checking for platform ... windows
checking for architecture ... x64
error: @programdir\core\main.lua:294: @programdir\core\sandbox\modules\import\core\base\task.lua:65: @programdir\core\tool\toolchain.lua:255: @programdir\modules\detect\sdks\find_vstudio.lua:234: table index is nil
stack traceback:
    [@programdir\modules\detect\sdks\find_vstudio.lua:234]: in function 'find_vstudio'
    [@programdir\toolchains\msvc\check.lua:40]: in function '_check_vsenv'
    [@programdir\toolchains\msvc\check.lua:80]:
    [C]: in function 'load'
    [@programdir\core\tool\toolchain.lua:251]: in function 'check'
    [@programdir\core\platform\platform.lua:247]: in function 'check'
    [@programdir\actions\config\main.lua:320]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:519]: in function 'run'
    [@programdir\core\sandbox\modules\import\core\base\task.lua:63]: in function 'run'
    [@programdir\actions\build\main.lua:113]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:519]: in function 'run'
    [@programdir\core\main.lua:292]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:788: in function 'raise'
        @programdir\core\main.lua:294: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>

H:\Project\test\testxmake>

会和我的本地vs有关吗？我本地有装了 vs2017,也装了vs2019。早起的xmake版本是可以正常的(忘记之前哪个版本了)；
> 如果是xmake相关编译问题，请加上`-vD`参数运行，并给出详细编译输出信息。

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：v2.5.3+202104080841
- xmake运行平台：windows
- xmake目标平台：windows

### 其他信息
![image](https://user-images.githubusercontent.com/38154767/117299422-1d59d800-aeab-11eb-8932-18faf79384f2.png)

请提供其他附加信息帮助我们诊断问题(比如截图，xmake.lua或者可复现的demo)，以及你遇到的问题的一些背景信息。

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/blob/9a1d5dc5e43fe4924c349863ead545e5a17a4155/xmake/modules/detect/sdks/find_vstudio.lua#L234

这里 vsvers[VisualStudioVersion] 取出来是 nil，说明 VisualStudioVersion 可能获取的是空串或者无效值。

而这块的逻辑，仅在 %VCInstallDir% 被设置的情况下，主要是为了处理 vs prompt cmd 环境的探测情况。。

你可以先打开一个干净的 cmd 试试，应该不会有这问题。。

至于这里的遇到的问题，有可能是在非cmd下，也可能不是vs prompt cmd下，但是 %VCInstallDir% 又被设置了，%VisualStudioVersion% 又没设置。。所以就这样了。。

我dev改进了下， 可以再试试 xmake update -s dev

**Comment by ZoroDM** [comment]
好的，最终xmake update -s dev后，再重试可以正常工作了，非常感谢！

过程有一些其他情况，细节如下：
1. 我这边打开一个干净的cmd试了，也是不行，不确定是不是我环境的问题；
2. 通过xmake update -s dev，之后再确认 xmake --version 发现版本号还是我反馈问题时的版本号，不确定是否正常？
3. 再执行xmake update -s dev后，我重新创建一个空的工程，然后xmake 目前已经可以正常工作了；

**Comment by waruqi** [comment]
> 我这边打开一个干净的cmd试了，也是不行，不确定是不是我环境的问题；

你可以执行 xmake l os.getenvs 看下，有没有 VCInstallDir 环境变量被设置，如果设置了，是有可能不行，因为 xmake 以为是在 vs prompt cmd下面

> 通过xmake update -s dev，之后再确认 xmake --version 发现版本号还是我反馈问题时的版本号，不确定是否正常？

正常，xmake 分 binary + lua scripts 两部分，版本号是带在 binary 里面的，但是  xmake update -s 。。加 -s 的 仅仅快速更新 lua scripts，binary core没去更新，所以版本号是不变的。。

> 再执行xmake update -s dev后，我重新创建一个空的工程，然后xmake 目前已经可以正常工作了；

说明更新 lua scripts 后，我加的 fix patch 生效了。。除非是 binary 接口变动，通常不用全量更新，xmake update dev 可以全量更新

**Comment by ZoroDM** [comment]
感谢如此详尽的答复;

这个是我的环境问题，确实是有设置了VCINSTALLDIR, 我最近一段时间因为编译最新的SqlCipher 版本，手动加了该变量导致:

---
>我这边打开一个干净的cmd试了，也是不行，不确定是不是我环境的问题；

你可以执行 xmake l os.getenvs 看下，有没有 VCInstallDir 环境变量被设置，如果设置了，是有可能不行，因为 xmake 以为是在 vs prompt cmd下面
