### ISSUE TITLE
如何解决调用第三方库出现 /LTCG 错误

### ISSUE THREAD

**Issue by llatecomers** [xmake-io/xmake#1386]
工程编译的时候上报，link第三方库的时候，出现 error: tbox.lib(trace.c.obj) : 找到 MSIL .netmodule 或使用 /GL 编译的模块；正在使用 /LTCG 重新启动链接；将 /LTCG 添加到链接命令行以改进链接器性能。脚本要通过什么命令，加上 /LTCG参数？目前试了了好多都不行。望指导一下。

**Comment by waruqi** [comment]
追加 -vD 重跑下编译，给我看下完整输出。

**Comment by waruqi** [comment]
另外这个是 tbox 问题，请迁移到 tbox issues 上反馈.
