### ISSUE TITLE
load toolchain in virtual environment

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1389]
### 你在什么场景下需要该功能？

windows下加载virtual environment时希望能同时加载vs的环境变量；clang等toolchain同理

### 描述可能的解决方案

在加载virtual environment的时候加载toolchain环境变量

### 其他信息

使用时发现环境变量中的路径有重复的，可以在获取环境变量时加一个去重

**Comment by waruqi** [comment]
可以通过 xmake.lua / set_toolchains("msvc") 方式配置上工具链信息，不过我暂时没空整，先放着吧。

**Comment by waruqi** [comment]
我加上支持了，用 set_toolchains("msvc")

其他的 clang 什么的，不需要用 set_toolchains，直接走 add_requires("llvm") 包就行了。

有包的尽量走包，目前仅有 msvc toolchain 才附带了 envs
