### ISSUE TITLE
xrepo-hook.psm1 is removed on updating xmake

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1394]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

https://github.com/xmake-io/xmake/issues/1391

### 期待的结果

xmake update -s dev 应该更新xrepo-hook.psm1而不是删除它

**Comment by xq114** [comment]
xrepo.ps1里面Import-Module的位置也要改下

**Comment by waruqi** [comment]
> xrepo.ps1里面Import-Module的位置也要改下

不用改，还是这个路径 

```lua
Import-Module "$Env:XMAKE_ROOTDIR\scripts\xrepo-hook.psm1";
```

安装目录下的 scripts 原本就对应 xmake/scripts ，而不是外面的 scripts。。我改了 installer.nsi 恢复回去了。。

**Comment by waruqi** [comment]
> 我这里定义的XMAKE_ROOTDIR是最外层xmake.exe的文件夹

对啊，安装完的 就一个 scripts，我说的外层 scripts，是指xmake源码repo 里面的外层。。。

xmake源码里面 

xmake-source
- scripts (外层，不会安装到 programdir 下，仅开发使用)
- xmake
  - scripts（会完整安装到 programdir，跟 xmake.exe 同级）

**Comment by xq114** [comment]
合理
