### ISSUE TITLE
windows app如何导入系统相关头文件

### ISSUE THREAD

**Issue by llatecomers** [xmake-io/xmake#1399]
请问，如何在xmake编译脚本中申明mfc的系统环境，代码中能够调用MFC的CStatic窗口类函数。
目前试了add_rules("win.sdk.application")，会报错误。
尝试以下调用方法，又不符合规范。
  add_includedirs("$(VC_IncludePath)")
  add_includedirs("$(WindowsSDK_IncludePath)")
  add_includedirs("$(WindowsSDK_MetadataPath)")

**Comment by waruqi** [comment]
原本就加了，报错就贴错误

**Comment by waruqi** [comment]
相关错误信息给找呢

**Comment by waruqi** [comment]
没有错误信息么？没有的话 我先 close 了
