### ISSUE TITLE
powershell theme issue

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1400]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

![image](https://user-images.githubusercontent.com/42310255/117666831-da637180-b1d6-11eb-998f-cc0d077b0fdf.png)

如图，powershell里面执行xrepo scan的时候包名颜色和背景重合了

### 期待的结果

能有清晰对比度的颜色

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.3 dev
- xmake运行平台：windows
- xmake目标平台：windows

**Comment by x1244** [comment]
更新到`xmake v2.5.3+202105051505` 可以显示包名称配色了。
可以参见
https://gitter.im/xmake-io/xmake?utm_source=notification&utm_medium=email&utm_campaign=unread-notifications

**Comment by xq114** [comment]
![image](https://user-images.githubusercontent.com/42310255/117672544-865b8b80-b1dc-11eb-8026-a1e061d2bac4.png)
我用的已经是最新版了

**Comment by xq114** [comment]
> 我应该改过了才对。。确定运行的 dev 的脚本？

是的，刚刚又运行了xmake update dev 以及 xmake update -s dev，问题还是存在

**Comment by waruqi** [comment]
我这测试也可以的么，确定qie切到 powershell theme 了？

![image](https://user-images.githubusercontent.com/151335/117676151-dc7dfe00-b1df-11eb-82f5-6db4245764f8.png)

**Comment by waruqi** [comment]
> 然后manual和donate前面的符号也显示不出来，感觉是conhost不支持unicode的问题

powershell 上我禁用了 emoji

**Comment by xq114** [comment]
我一开始用的default theme，没切，刚测了下powershell theme是好的，只是default theme有问题。xmake应该能根据当前环境决定theme的吧？
