### ISSUE TITLE
find_package cannot find package installed by xmake

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1403]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
运行`xmake l find_package zlib`和`xmake l find_package xmake::zlib`都找不到xmake安装的zlib，这个现象正常吗？

**Comment by xq114** [comment]
那如果我想做一个接口的blas库，按系统cpu不同依次查找openblas/mkl/等，找到则返回，应该怎么写？find_package找不到xmake的包，add_deps("openblas", "mkl", {optional=true})则会把两个都链接

**Comment by waruqi** [comment]
设置 private 就能避免自动link，然后 on_fetch里面 通过 package:dep("mkl"):fetch() 去获取包信息

add_deps("openblas", "mkl", {private = true, optional=true})

**Comment by xq114** [comment]
另外我希望在找不到已安装的包的时候，可以让xmake自动安装查找顺序的第一个包，在on_fetch里面做可以实现这一点吗

**Comment by waruqi** [comment]
没明白，on_fetch 里面不安装包。。add_deps 哪个包没装，就会自动装，安装顺序自己根据 add_deps 添加顺序和依赖顺序控制

**Comment by xq114** [comment]
> 没明白，on_fetch 里面不安装包。。add_deps 哪个包没装，就会自动装，安装顺序自己根据 add_deps 添加顺序和依赖顺序控制

就是先找xmake已安装的包里面有没有mkl/openblas，如果没有，再根据cpu判断安装mkl或者openblas

**Comment by waruqi** [comment]
直接在 package("mkl") 里面定义 on_fetch ，如果没找到，on_install 里面根据 cpu 安装 mkl 不就好了

**Comment by xq114** [comment]
> 直接在 package("mkl") 里面定义 on_fetch ，如果没找到，on_install 里面根据 cpu 安装 mkl 不就好了

add_requires("mkl") --直接安装mkl

add_requires("blas") --根据cpu判断安装哪一个包

**Comment by waruqi** [comment]
> > 直接在 package("mkl") 里面定义 on_fetch ，如果没找到，on_install 里面根据 cpu 安装 mkl 不就好了
> 
> add_requires("mkl") --直接安装mkl

如果不想找系统 mkl，那就加 {system = false} 就可以直接装，

> add_requires("blas") --根据cpu判断安装哪一个包

on_load/on_install 里面自己判断下，如果是 url 的变动，那就描述域 走 os.cpuinfo 判断下

**Comment by xq114** [comment]
> > add_requires("blas") --根据cpu判断安装哪一个包
> 
> on_load/on_install 里面自己判断下，如果是 url 的变动，那就描述域 走 os.cpuinfo 判断下

表述有误，是先找有没有，没有再判断安装哪一个包

**Comment by waruqi** [comment]
> > > add_requires("blas") --根据cpu判断安装哪一个包
> > 
> > 
> > on_load/on_install 里面自己判断下，如果是 url 的变动，那就描述域 走 os.cpuinfo 判断下
> 
> 表述有误，是先找有没有，没有再判断安装哪一个包

那不就是再多加个 on_fetch 去查找的事么。。

**Comment by xq114** [comment]
```
package("blas")

    set_homepage("https://www.netlib.org/blas/")
    set_description("Basic Linear Algebra Subprograms")

    add_deps("mkl", "openblas", {private = true, optional = true})
    on_fetch(function (package, opt)
        if opt.system then
            local vendor = import("core.base.cpu").vendor()
            local pref_order = {}
            if vendor == "GenuineIntel" then
                pref_order = {"mkl", "openblas"}
            else
                pref_order = {"openblas", "mkl"}
            end
            for _, lib in ipairs(pref_order) do
                if package:dep(lib):exists() then
                    print("Using blas from %s.", lib)
                    return package:dep(lib):fetch()
                end
            end
        end
    end)

    on_install("windows", "linux", "macosx", function (package)
        local vendor = import("core.base.cpu").vendor()
        if vendor == "GenuineIntel" then
            package:add("deps", "mkl")
        else
            package:add("deps", "openblas")
        end
    end)
```

这样写如果on_fetch没找到就会直接报错fetch blas failed!

**Comment by waruqi** [comment]
贴下完整栈呢 -vD

**Comment by xq114** [comment]
```
error: ...\modules\private\action\require\impl\actions\install.lua:194: fetch blas failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:793]: in function 'raiselevel'
    [@programdir\core\sandbox\modules\utils.lua:181]: in function 'assert'
    [...\modules\private\action\require\impl\actions\install.lua:194]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:137]: in function 'action_install'
    [...modules\private\action\require\impl\install_packages.lua:212]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:193]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:186]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:342]:

  => install blas  .. failed
```

**Comment by waruqi** [comment]
> ```
> error: ...\modules\private\action\require\impl\actions\install.lua:194: fetch blas failed!
> stack traceback:
>     [C]: in function 'error'
>     [@programdir\core\base\os.lua:793]: in function 'raiselevel'
>     [@programdir\core\sandbox\modules\utils.lua:181]: in function 'assert'
>     [...\modules\private\action\require\impl\actions\install.lua:194]:
>     [C]: in function 'trycall'
>     [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
>     [...\modules\private\action\require\impl\actions\install.lua:137]: in function 'action_install'
>     [...modules\private\action\require\impl\install_packages.lua:212]: in function 'jobfunc'
>     [@programdir\modules\private\async\runjobs.lua:193]:
>     [C]: in function 'trycall'
>     [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
>     [@programdir\modules\private\async\runjobs.lua:186]: in function 'cotask'
>     [@programdir\core\base\scheduler.lua:342]:
> 
>   => install blas  .. failed
> ```

这个是已经走到 on_install 完成后的 fetch 了。。装完 xmake 仓库包，但是没找到，肯定报失败。。

1. 安装之前 fetch 系统库，这个找不到，不会报错，然后尝试走 xmake 仓库包安装
2. 走 xmake 仓库安装后，会去自动 fetch 装好的包，这个找不到，就会报错，即使不报出来，后面的 on_test 也过不了

你 on_install 里面，一没有复制 libs 到 lib 下，也没有加 add_links/add_linkdirs ，这个包等于是个空包，xmake 不管怎么fetch 肯定找不到。。

所以，先得确保 installdir/lib 下有东西。。或者有 add_links/add_linkdirs 才行。。

如果啥也没有，那也要 on_fetch 里面 对于 `if not opt.system` 返回包的内容哈。。你这个包啥也没有装，怎么可能不报错

```
    on_fetch(function (package, opt)
        if opt.system then
        else
             return {links = .. linkdirs...}
        end
```

**Comment by xq114** [comment]
在on_fetch里面加上else之后on_install部分就不执行了，也就无法给他加上mkl/openblas的依赖了

**Comment by waruqi** [comment]
> 在on_fetch里面加上else之后on_install部分就不执行了，也就无法给他加上mkl/openblas的依赖了

只有在 on_fetch 成功找到了 xmake 里面安装的 mkl 包(也就是返回非空)，才会不走 on_install

  既然要继续走 on_install ，没安装前 on_fetch应该返回 nil

**Comment by waruqi** [comment]
> 在on_fetch里面加上else之后on_install部分就不执行了，也就无法给他加上mkl/openblas的依赖了

只有在 on_fetch 成功找到了 xmake 里面安装的 mkl 包(也就是返回非空)，才会不走 on_install

  既然要继续走 on_install ，没安装前 on_fetch应该返回 nil

**Comment by xq114** [comment]
现在改成

```lua
package("blas")

    set_homepage("https://www.netlib.org/blas/")
    set_description("Basic Linear Algebra Subprograms")

    add_deps("mkl", "openblas", {private = true, optional = true})
    on_fetch(function (package, opt)
        local vendor = import("core.base.cpu").vendor()
        local pref_order = {}
        if vendor == "GenuineIntel" then
            pref_order = {"mkl", "openblas"}
        else
            pref_order = {"openblas", "mkl"}
        end
        for _, lib in ipairs(pref_order) do
            if package:dep(lib):exists() then
                print("Using blas from %s.", lib)
				package:add("deps", lib)
                return package:dep(lib):fetch()
            end
        end
    end)

    on_install("windows", "linux", "macosx", function (package)
        local vendor = import("core.base.cpu").vendor()
        if vendor == "GenuineIntel" then
            package:add("deps", "mkl")
        else
            package:add("deps", "openblas")
        end
    end)
```

但是在on_fetch里面设置的deps没有生效，mkl对tbb的依赖没有传递到blas

**Comment by waruqi** [comment]
deps设置只能在 on_load阶段设置，因为这是这是在加载包列表阶段完成的，on_fetch太滞后了

**Comment by xq114** [comment]
> deps设置只能在 on_load阶段设置，因为这是这是在加载包列表阶段完成的，on_fetch太滞后了，这个时候包依赖结构已经定型，不能再设置了

on_load里面因为find_package找不到xmake安装的包，没法设置好dep，现在的逻辑是private dep->判断->dep

**Comment by waruqi** [comment]
直接描述域或者 on_load 根据 os.cpuinfo().vender 设置不同的 add_deps mkl 或者 openbias 不行么

这两包内部自己会去找，连private都不需要

或者两都弄成 private 和 optional，然后 on_fetch里面从这两包选取结果就行了

**Comment by xq114** [comment]
> 直接描述域或者 on_load 根据 os.cpuinfo().vender 设置不同的 add_deps mkl 或者 openbias 不行么
> 
> 这两包内部自己会去找，自动附加links 连private都不需要

1. blas提供者不仅仅有mkl和openblas，还有atlas等等，现在没加以后可能会加；2. 能用已经安装过的库就没必要重复安装；3. 用户可以用预先安装的方式决定add_requires("blas")里面的blas包

> 或者两都弄成 private 和 optional，然后 on_fetch里面从这两包选取结果就行了

其他的包依赖blas的情况下，on_fetch找不到blas，ci上就无法测试；能够让xmake在未找到的情况下自动安装也更省事

另外，为什么现在不提供通过`find_package`查找xmake安装的包的功能呢？不提供这个功能，on_fetch就没办法完全替代find_xxx.lua了

**Comment by waruqi** [comment]
> 2. 能用已经安装过的库就没必要重复安装

预先设置 add_deps 一样还是先去找 mkl openbias等已经安装过的库，并没有重复安装，只是借用 add_deps走了 xmake的find_package而已

> 其他的包依赖blas的情况下，on_fetch找不到blas，ci上就无法测试；能够让xmake在未找到的情况下自动安装也更省事

bias on_fetch找不到，同样会去走 on_install 去自动装，只不过是 add_deps里面 fetch + on_install 过一遍了，bias 里面的 on_install 里面只需要 add_linkdirs 设置下 直接切入 dep("mkl") 里面的links 就行了，没什么区别

> 另外，为什么现在不提供通过find_package查找xmake安装的包的功能呢？不提供这个功能，on_fetch就没办法完全替代find_xxx.lua了

原本就有 https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/manager/xmake/find_package.lua

只是要根据不同的包 configs version plat/arch什么的算出 buildhash 才能找到对应的包，所以不建议 xmake l find_package 这么直接调用，因为你不知道对应buildhash值

而借用 add_deps走 fetch/find_package 能够自动匹配当前环境的buildhash确保找对包

而 deps 必须在 on_load 里面加，如果在 on_load 里面调用 xmake/find_package ，但是这个阶段deps包都还没完全load，配置信息不全，也是算不出对应buildhash的，所以即使调用find_package也是找不到的

**Comment by waruqi** [comment]
```lua
package("blas")

    set_homepage("https://www.netlib.org/blas/")
    set_description("Basic Linear Algebra Subprograms")

    add_deps("mkl", "openblas", {private = true, optional = true})
    on_fetch(function (package, opt)
        local vendor = import("core.base.cpu").vendor()
        local pref_order = {}
        if vendor == "GenuineIntel" then
            pref_order = {"mkl", "openblas"}
        else
            pref_order = {"openblas", "mkl"}
        end
        for _, lib in ipairs(pref_order) do
            if package:dep(lib):exists() then
                print("Using blas from %s.", lib)
				package:add("deps", lib)
                return package:dep(lib):fetch()
            end
        end
    end)
```

> 其他的包依赖blas的情况下，on_fetch找不到blas，ci上就无法测试；能够让xmake在未找到的情况下自动安装也更省事

而且我觉的 on_install 都不需要，mkl openbias自己的包 先走系统查找复用，没有走自动安装 

如果bias fetch不到，由于没on_test，ci上也能过，而 mkl openbias自身包有 on_test 也已经测试过了

另外目前一些仅有on_fetch的包，目前肯定是避免不了 ci fails，这种包回头ci test脚本改下，过滤掉test逻辑算了，毕竟ci上这些环境肯定没有的 测不了

**Comment by xq114** [comment]
> 原本就有 [`master`/xmake/modules/package/manager/xmake/find_package.lua](https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/manager/xmake/find_package.lua)
> 
> 只是要根据不同的包 configs version plat/arch什么的算出 buildhash 才能找到对应的包，所以不建议 xmake l find_package 这么直接调用，因为你不知道对应buildhash值
> 
> 而借用 add_deps走 fetch/find_package 能够自动匹配当前环境的buildhash确保找对包
> 
> 而 deps 必须在 on_load 里面加，如果在 on_load 里面调用 xmake/find_package ，但是这个阶段deps包都还没完全load，配置信息不全，也是算不出对应buildhash的，所以即使调用find_package也是找不到的
> 
> 另外on_load阶段，即使find_package可以找到，也是不建议使用的，因为除了包安装，还有uninstall info scan 等各种用到包的地方，都会走on_load加载，去find_package，这显然是不对的

不加参数的find_package仅触发包的on_fetch可以吗，相当于用on_fetch部分取代原来的find_xxx.lua

**Comment by waruqi** [comment]
> 而 deps 必须在 on_load 里面加，如果在 on_load 里面调用 xmake/find_package ，但是这个阶段deps包都还没完全load，配置信息不全，也是算不出对应buildhash的，所以即使调用find_package也是找不到的

find_package  里面调用 on_fetch? 这个支持不了，fetch 自身就是各种 find_package 实现的。

**Comment by xq114** [comment]
这个问题还是在于xmake的包依赖没有一种很好的“或”逻辑的实现方式：

假设c依赖a或b，这个依赖项应该是到编译时才确定；而我没理解错的话目前xmake处理依赖的方式是在on_load里面确定，而不是编译期，那这个“或”的逻辑就无法实现

**Comment by waruqi** [comment]
> 这个问题还是在于xmake的包依赖没有一种很好的“或”逻辑的实现方式：
> 
> 假设c依赖a或b，这个依赖项应该是到编译时才确定；而我没理解错的话目前xmake处理依赖的方式是在on_load里面确定，而不是编译期，那这个“或”的逻辑就无法实现

目前只能在 load 期做，编译安装时期已经过于滞后后了。。涉及影响东西比较多，并行安装，以及非安装action 时候也会去加载依赖链。。目前支持不了安装阶段动态调整deps
