### ISSUE TITLE
support selecting package for use interactively

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1409]
### 你在什么场景下需要该功能？

xmake的集成第三方库功能非常强大，但缺少一个方便的选择机制 https://github.com/xmake-io/xmake/issues/1140

选择机制可以先有命令行接口，将来若有xmake-gui选择机制也是重要的一部分

### 描述可能的解决方案

```
xmake config --interactive
...
checking for requires...
> foo
> bar
> baz
use system::foo (1.1.0)? (y/n) n
use xmake::foo (1.4.0, configs={xxx=false})? (y/n) n
use xmake::foo (1.3.0, configs={xxx=true})? (y/n) y
using xmake::foo.
use xmake::bar (2.2.1)? (y/n) n
use vcpkg::bar? (y/n) n
use conan::bar (from remote)? y
installing bar from conan... ok
using conan::bar.
use vcpkg::baz? (y/n) n
use xmake::baz (1.2, from remote)? y
installing baz from xmake... ok
using xmake::baz.
done.
```

`xmake config --interactive -y`效果就和现有`xmake config`一样。

**Comment by waruqi** [comment]
你这个跟 https://github.com/xmake-io/xmake/issues/1140 重复了，没必要再提一遍。。后面也许会搞，但近期没时间。

**Comment by waruqi** [comment]
等下个版本看看吧，如果有时间就搞下，后续还是在 https://github.com/xmake-io/xmake/issues/1140 上跟进好了

**Comment by waruqi** [comment]
我初步支持了，具体见：https://github.com/xmake-io/xmake/issues/1140#issuecomment-849270854

**Comment by xq114** [comment]
这个功能现在的实现是每次config的时候都会提示modify吗？

**Comment by waruqi** [comment]
> 这个功能现在的实现是每次config的时候都会提示modify吗？

会，但是修改后装完了，下次config就能自动检测到，也就不会提示安装 所以也不用modify了
