### ISSUE TITLE
Android 打包 so 的时候，因为 -lcrypto -lssl 链接选项顺序问题导致的运行时COMP_expand_block符号找不到的问题

### ISSUE THREAD

**Issue by fallending** [xmake-io/xmake#1415]
> 问题跟踪时间比较长，下面简而言之，希望也能进行有效的讨论

### Android下打libxx.so成功后，运行时符号找不到的问题

* xx依赖openssl
* openssl是从vcpkg那边以来过来的 add_requires("vcpkg:openssl")
* xmake 最后打so的命令中顺序是：-lcrypto -lssl
* so在android app中LoadLibrary时报错：
```
java.lang.unsatisfiedlinkerror dlopen failed cannot locate symbol "COMP_expand_block" referenced by ..... libxx.so
```
* COMP_expand_block 是 crypto 中的符号

### 期待的结果

运行时不应该报错

### 测试结果

* xmake打so的时候强制将顺序改为：-lssl -lcrypto 
* Android app 正常运行，正常加载 libxx.so 
* 配置如下：
```
add_shflags("-L/Users/..省略../openssl/lib", "-lssl", "-lcrypto", {force = true})
```

**Comment by waruqi** [comment]
改用 add_requires("openssl") 好了，现在支持 android ，顺序也对

**Comment by fallending** [comment]
> find_package.lua

看了下：

* vcpkg中库文件的排序，即系统文件排序
* vcpkg中lib目录有pkgconfig，其中的libssl.pc中有一段：
```
Name: OpenSSL-libssl
Description: Secure Sockets Layer and cryptography libraries
Version: 1.1.0c
Requires.private: libcrypto
Libs: -L${libdir} -lssl
Libs.private: -L/Users/leenjewel/workspaces/openssl_for_ios_and_android/tools/armeabi-v7a-android-toolchain/sysroot/usr/lib -lz -ldl 
Cflags: -I${includedir}
```

**Comment by fallending** [comment]
> 改用 add_requires("openssl") 好了，现在支持 android ，顺序也对
> 
> vcpkg里面 目前只能获取到lib list，没有顺序，这得依赖vcpkg的支持，你可以研究下 vcpkg/find_package.lua

经过测试，add_requires("openssl") 没有问题，赞👍

**Comment by waruqi** [comment]
> > find_package.lua
> 
> 看了下：
> 
> * vcpkg中库文件的排序，即系统文件排序
> * vcpkg中lib目录有pkgconfig，其中的libssl.pc中有一段：
> 
> ```
> Name: OpenSSL-libssl
> Description: Secure Sockets Layer and cryptography libraries
> Version: 1.1.0c
> Requires.private: libcrypto
> Libs: -L${libdir} -lssl
> Libs.private: -L/Users/leenjewel/workspaces/openssl_for_ios_and_android/tools/armeabi-v7a-android-toolchain/sysroot/usr/lib -lz -ldl 
> Cflags: -I${includedir}
> ```

目前vcpkg 只是走了 lib list，没走里面的 pc pkgconfig 文件，回头可以改进下
