### ISSUE TITLE
add_deps和add_links之间的连接顺序问题。

### ISSUE THREAD

**Issue by zwxf** [xmake-io/xmake#1417]
在xmake版本v2.5.1之后的add_deps和add_links之间添加链接的顺序是以add_deps/add_links添加的先后顺序来觉得的链接顺序，v2.5.1之后的版本发现和位置无关了，而是一定在add_links之后，这导致有依赖关系的库链接失败。目前我遇到的情形如下，
```

add_links("A")
add_links("B")
add_links("C")
add_deps("abc")

target("abc")
    set_kind("binary")

    add_files("abc.c")
target_end()

```
其中abc是这个工程生成的静态库，abc这个库依赖于A/B/C这三个第三方的静态库。在v2.5.1之前，我只需将add_deps("abc")放在add_links("A")之上即可完成编译，而在此之后会出现依赖的错误而找不到链接。
考虑过将add_deps("abc")改成add_links（“abc”），但是这样更改后生成abc这个target的时候，abc库的改动无法被检测到，需要先xmake abc生成这个库再xmak abc这个target，有点繁琐。
以上：
    想问下能否改回之前按照add_deps/add_links添加顺序来决定链接顺序？或者说v2.5.1之为什么会有这个改动的？
谢谢，期待回复！

**Comment by waruqi** [comment]
看下这两：

https://github.com/xmake-io/xmake/issues/1240
https://github.com/xmake-io/xmake/issues/605

目前是: 优先使用当前 target 下的 links ，最后再使用 deps 里面的。。

目前的策略不会再变了，你可以用 add_syslinks 来控制将第三方 links 挪到最后

**Comment by waruqi** [comment]
初步改进了下，试试 https://github.com/xmake-io/xmake/issues/1452#issuecomment-1741152822
