### ISSUE TITLE
wait events in poller failed!

### ISSUE THREAD

**Issue by wyf44321** [xmake-io/xmake#1419]
我在编译项目的时候报这个错误，请问是什么原因？
![image](https://user-images.githubusercontent.com/51105583/118813042-5483ac80-b8e1-11eb-9b31-768fe08e5679.png)

**Comment by waruqi** [comment]
贴下 xmake.lua 然后 在 cmd 下手动执行 `xmake -vD` 编译给我看下错误信息

**Comment by wyf44321** [comment]
![image](https://user-images.githubusercontent.com/51105583/118817523-e392c380-b8e5-11eb-80b6-0d1787ae8eb9.png)

**Comment by waruqi** [comment]
-vD 给我完整 output  不要截这么一点点，我怎么看。

**Comment by waruqi** [comment]
没有更详细的错误么？没有的话 我就先 close了

**Comment by waruqi** [comment]
可以看下这个，https://github.com/xmake-io/xmake/issues/1640 应该解决了
