### ISSUE TITLE
Add prefix and suffix options for target names

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#1421]
### Is your feature request related to a problem? Please describe.
Libraries developers often need to add some suffixes (and prefixes) to the output name (for example "-d" as debug suffixes).

Currently xmake has no way to add suffixes or prefixes, which requires users to use basename, which is a bit confusing for new users as other tools have this.

### Describe the solution you'd like
Two new methods: `target:set_suffix` and `target:set_prefix` which would be used by xmake with the basename (`prefix .. basename .. suffix .. "." .. ext`) if the fullname isn't set.

Also, I think it would nice to handle the `lib` prefix on POSIX with this: on POSIX set the default prefix value to "lib" ("" on windows) so the user can get rid of the lib prefix on Linux easily ([which I had to do for a obs-plugin](https://github.com/SirLynix/obs-kinect/blob/master/xmake.lua#L5)).

### Describe alternatives you've considered
Using rules, however this may become complicated if you have multiple way of setting your basename

```lua
-- Adds -d as a debug suffix
rule("debug_suffix")
	on_load(function (target)
		if is_mode("debug") then
			target:set("basename", target:basename() .. "-d")
		end
	end)
```

**Comment by waruqi** [comment]
I have supported it on dev.

```lua
target("xxx")
    set_prefixname("")
    set_suffixname("-d")
    set_extension(".so")
```

`set_prefixname` will override `lib` prefix on posix.

Priority order

1. set_filename()
2. set_prefixname + set_basename + set_suffixname + set_extension
3. default name with target("name")
