### ISSUE TITLE
Can i use add_includedirs to add directories recursively

### ISSUE THREAD

**Issue by dinghao188** [xmake-io/xmake#1423]
for example, i have following directories:
```
root
|---incl1
|---incl2
|---incl3
```
Can i just use `add_directories("root/*")` to replace `add_directories("incl1", "incl2", "incl3")`

**Comment by waruqi** [comment]
add_includedirs(os.dirs(path.join(os.scriptdir(), "root/*")))

**Comment by dinghao188** [comment]
> add_includedirs(os.dirs(path.join(os.scriptdir(), "root/*")))

it gave an error.
```
error: @programdir/core/base/interpreter.lua:362: add_includedirs(table: 0x7f7b719bf0c8): invalid path value at ./xmake.lua:6
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:800]: in function 'raise'
    [@programdir/core/base/interpreter.lua:362]: in function '_api_translate_paths'
    [@programdir/core/base/interpreter.lua:1360]: in function 'add_includedirs'
    [./xmake.lua:6]: in main chunk
```

**Comment by waruqi** [comment]
I have fixed it on dev branch. `xmake update -s dev`

**Comment by waruqi** [comment]
does it work?

**Comment by dinghao188** [comment]
thanks, it works! And i saw your commits. So i realize that i can use `unpack` to sove this in current release version.

**Comment by waruqi** [comment]
ok
