### ISSUE TITLE
Set "binary" as default kind

### ISSUE THREAD

**Issue by heinthanth** [xmake-io/xmake#1424]
It's really not a problem. But, I would be happy if binary is set as default kind. When I start a project, I need to specify kind as
```lua
target("executable")
    set_kind("binary")
```
If set_kind is not set, it's default to static I think.

### Describe the solution you'd like
I just want Xmake to set "binary" as default kind. To tried to look up the source code and try to modify. But since I don't much familiar with Lua and project structure, I failed.

Please help me with this, or please tell me how to. So that, I can fork and build for myself.
Thanks. But sorry for bad English.

**Comment by waruqi** [comment]
I have supported it on dev.
