### ISSUE TITLE
failed add_requires("brew::librdkafka")

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#1427]
(base) apple@mac srv_audit % xmake f -vD -c
checking for platform ... macosx
checking for architecture ... x86_64
checking for Xcode directory ... /Applications/Xcode.app
checking for Codesign Identity of Xcode ... no
checking for SDK version of Xcode for macosx (x86_64) ... 11.3
checking for Minimal target version of Xcode for macosx (x86_64) ... 11.4
checkinfo: cannot runv(dmd --version), No such file or directory
checking for dmd ... no
checkinfo: cannot runv(ldc2 --version), No such file or directory
checking for ldc2 ... no
checkinfo: cannot runv(gdc --version), No such file or directory
checking for gdc ... no
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
finding fmt from xmake ..
checking for xmake::fmt ... fmt master
finding yhsdk from xmake ..
checking for xmake::yhsdk ... yhsdk feature/component
finding yh_utils from xmake ..
checking for xmake::yh_utils ... yh_utils master
finding nlohmann_json from xmake ..
checking for xmake::nlohmann_json ... nlohmann_json release/3.9.1
finding nng from xmake ..
checking for xmake::nng ... nng release/1.3.2
finding librdkafka from brew ..
checking for cmake ... /Users/apple/.xmake/packages/c/cmake/3.18.4/21a5bb5b770e4c598f52412f3a3a962f/bin/cmake
checking for cmake ... /Users/apple/.xmake/packages/c/cmake/3.15.4/65f2e2469f0749d9a1b4d3e0c912d62a/bin/cmake
checking for brew ... /usr/local/bin/brew
checking for brew::librdkafka ... no
note: try installing these packages (pass -y to skip confirm)?
in brew:
  -> brew::librdkafka latest 
please input: y (y/n)
y
installing librdkafka from brew ..
/usr/local/bin/brew install librdkafka --verbose
==> Downloading https://ghcr.io/v2/homebrew/core/librdkafka/manifests/1.7.0
Already downloaded: /Users/apple/Library/Caches/Homebrew/downloads/b17b285dd310c2a6d241d0ce7d65356ac82030411df9b035fdbca0f30a6ec1b1--librdkafka-1.7.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/librdkafka/blobs/sha256:3ec79e37ef21015419739012106ec51199fa50ec71a5843bf97a9bbcd3dd0fc5
Already downloaded: /Users/apple/Library/Caches/Homebrew/downloads/d82b3263b39f12aa959552383c4711be04a3ff52ef4cbfa0d25cb40bb841be8e--librdkafka--1.7.0.big_sur.bottle.tar.gz
==> Verifying checksum for 'd82b3263b39f12aa959552383c4711be04a3ff52ef4cbfa0d25cb40bb841be8e--librdkafka--1.7.0.big_sur.bottle.tar.gz'
==> Pouring librdkafka--1.7.0.big_sur.bottle.tar.gz
tar --extract --no-same-owner --file /Users/apple/Library/Caches/Homebrew/downloads/d82b3263b39f12aa959552383c4711be04a3ff52ef4cbfa0d25cb40bb841be8e--librdkafka--1.7.0.big_sur.bottle.tar.gz --directory /private/tmp/d20210526-17165-1fhcrj0
cp -pR /private/tmp/d20210526-17165-1fhcrj0/librdkafka/. /usr/local/Cellar/librdkafka
chmod -Rf +w /private/tmp/d20210526-17165-1fhcrj0
==> Finishing up
ln -s ../Cellar/librdkafka/1.7.0/include/librdkafka librdkafka
ln -s ../../Cellar/librdkafka/1.7.0/share/doc/librdkafka librdkafka
ln -s ../Cellar/librdkafka/1.7.0/lib/librdkafka++.1.dylib librdkafka++.1.dylib
ln -s ../Cellar/librdkafka/1.7.0/lib/librdkafka++.a librdkafka++.a
ln -s ../Cellar/librdkafka/1.7.0/lib/librdkafka++.dylib librdkafka++.dylib
ln -s ../Cellar/librdkafka/1.7.0/lib/librdkafka.1.dylib librdkafka.1.dylib
ln -s ../Cellar/librdkafka/1.7.0/lib/librdkafka.a librdkafka.a
ln -s ../Cellar/librdkafka/1.7.0/lib/librdkafka.dylib librdkafka.dylib
ln -s ../../Cellar/librdkafka/1.7.0/lib/pkgconfig/rdkafka++-static.pc rdkafka++-static.pc
ln -s ../../Cellar/librdkafka/1.7.0/lib/pkgconfig/rdkafka++.pc rdkafka++.pc
ln -s ../../Cellar/librdkafka/1.7.0/lib/pkgconfig/rdkafka-static.pc rdkafka-static.pc
ln -s ../../Cellar/librdkafka/1.7.0/lib/pkgconfig/rdkafka.pc rdkafka.pc
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210526-17426-2r928c.sb nice ruby -W1 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/librdkafka.rb
==> Summary
🍺  /usr/local/Cellar/librdkafka/1.7.0: 36 files, 4.8MB
finding librdkafka from brew ..
finding librdkafka from system ..
checking for pkg-config ... /usr/local/bin/pkg-config
checking for brew::librdkafka ... no

error: .../modules/private/action/require/impl/actions/install.lua:194: fetch brew::librdkafka-latest failed!
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:800]: in function 'raiselevel'
    [@programdir/core/sandbox/modules/utils.lua:181]: in function 'assert'
    [.../modules/private/action/require/impl/actions/install.lua:194]:
    [C]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [.../modules/private/action/require/impl/actions/install.lua:137]: in function 'action_install'
    [...modules/private/action/require/impl/install_packages.lua:212]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:193]:
    [C]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [@programdir/modules/private/async/runjobs.lua:186]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:365]:

  => install brew::librdkafka latest .. failed
error: @programdir/modules/private/async/runjobs.lua:217: .../modules/private/action/require/impl/actions/install.lua:253: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:800]: in function 'raise'
    [.../modules/private/action/require/impl/actions/install.lua:253]: in function 'catch'
    [@programdir/core/sandbox/modules/try.lua:127]: in function 'try'
    [.../modules/private/action/require/impl/actions/install.lua:137]: in function 'action_install'
    [...modules/private/action/require/impl/install_packages.lua:212]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:193]:
    [C]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [@programdir/modules/private/async/runjobs.lua:186]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:365]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:800: in function 'raise'
        @programdir/modules/private/async/runjobs.lua:217: in function 'catch'
        @programdir/core/sandbox/modules/try.lua:127: in function 'try'
        @programdir/modules/private/async/runjobs.lua:186: in function 'cotask'
        @programdir/core/base/scheduler.lua:365: in function <@programdir/core/base/scheduler.lua:362>

**Comment by waruqi** [comment]
> ln -s ../../Cellar/librdkafka/1.7.0/lib/pkgconfig/rdkafka++-static.pc rdkafka++-static.pc
ln -s ../../Cellar/librdkafka/1.7.0/lib/pkgconfig/rdkafka++.pc rdkafka++.pc
ln -s ../../Cellar/librdkafka/1.7.0/lib/pkgconfig/rdkafka-static.pc rdkafka-static.pc
ln -s ../../Cellar/librdkafka/1.7.0/lib/pkgconfig/rdkafka.pc rdkafka.pc

有多个 pc 文件，默认的 `brew::librdkafka` 没法知道要选哪个？可以尝试下 `brew::librdkafka/rdkafka-static` 或者 `brew::librdkafka/rdkafka` 进一步细分到 pc

**Comment by fasiondog** [comment]
多谢，按上面的方法可以了
