### ISSUE TITLE
离线机器无法安装包

### ISSUE THREAD

**Issue by x1244** [xmake-io/xmake#1428]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

在一台离线的机器上导入包时不成功，提示信息如下：

```
PS G:\> xrepo import -i g:/xx/packages spdlog
updating repositories .. error: Cloning into 'C:\Users\conlay\AppData\Roaming\.xmake\repositories\xmake-repo'...
fatal: unable to access 'https://github.com/xmake-io/xmake-repo.git/': Could not resolve host: github.com

error: execv(xmake require --import --packagedir=g:/xx/packages --extra={system=false} spdlog) failed(-1)
```
包是由另一台在线机器导出的。

### 期待的结果

希望导出的包能在离线机器上导入，或者可以拷贝后使用。

### 错误信息

见问题描述

### 相关环境

`xrepo version`如下：

```
PS C:\workspace\pkg> xrepo --version
xRepo 2.5.4+202105150825/xmake, A cross-platform C/C++ package manager based on Xmake.
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io

    __  ___ ___  ______ ____  _____
    \ \/ / |  _ \| ____|  _ \/  _  |
     >  <  | |_) |  _| | |_) | |_| |
    /_/\_\_| \___|_____|_|   |____/
                         by ruki, xmake.io

      Manual: https://xmake.io/#/getting_started
      Donate: https://xmake.io/#/sponsor
```

### 其他信息

将导出包拷贝到系统包目录，运行`xrepo scan`可以扫描到这个包

```
PS C:\workspace\pkg> xrepo scan spdlog
scanning packages ..
spdlog-v1.8.5:
  -> 3a6d86bc05784bc69ad7f92fea34de2c: windows, x64
    -> {debug=false,vs_runtime="MT",shared=false,pic=true,header_only=true,noexcept=false,fmt_external=false}
```

但是`xrepo info`信息如下：

```
PS C:\workspace\pkg> xrepo info spdlog
updating repositories .. error: Cloning into 'C:\Users\conlay\AppData\Roaming\.xmake\repositories\xmake-repo'...
fatal: unable to access 'https://github.com/xmake-io/xmake-repo.git/': Could not resolve host: github.com

error: execv(xmake require --info --extra={system=false} spdlog) failed(-1)
```

新建一个工程，简单配置如下：

```
add_requires("spdlog")
target("log")
    set_kind("binary")
	add_files("log.cpp")
	add_packages("spdlog")
```

编译提示如下，说明直接拷贝不可用。

```
PS C:\workspace\pkg> xmake f -c --vs=2019
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2019
updating repositories .. error: Cloning into 'C:\Users\conlay\AppData\Roaming\.xmake\repositories\xmake-repo'...
fatal: unable to access 'https://github.com/xmake-io/xmake-repo.git/': Could not resolve host: github.com
```
PS:上次提问的关于`xrepo`的在`xrepo`不如在这里得到的回复及时，不知提到这里是否合适？

**Comment by waruqi** [comment]
xmake g --network=private 

全局设置为私有离线网络试试

**Comment by x1244** [comment]
设置全局私有离线网络模式，提示找不到包。
```
PS C:\Users\conlay> xmake g --network=private
configure
{
    network = private
    proxy_pac = pac.lua
    theme = powershell
    qt = C:\Qt\Qt5.7.0
}
PS C:\Users\conlay> xrepo import -i c:/users/conlay/packages spdlog
error: package(spdlog) not found!
error: execv(xmake require --import --packagedir=c:/users/conlay/packages --extra={system=false} spdlog) failed(-1)
```
不论是在在线机器，还是离线机器都一样。
有一点需要注意的是在线机器已经安装过包，再删除后，将网线断开，也能离线安装，但是离线机器从未联过网，所以不能安装。
在线机器断网后安装效果如下：
```
PS C:\Users\conlay> xrepo import -i c:/users/conlay/packages spdlog
importing spdlog-v1.8.5 [vs_runtime:MT]
  <- c:/users/conlay/packages\s\spdlog\v1.8.5\3a6d86bc05784bc69ad7f92fea34de2c
```
另外，在我的机器上使用powershell主题时，`xrepo scan`给出的包名字对比度弱，我有点散光识别困难，能否改进一下，截图如下：
![scan](https://user-images.githubusercontent.com/63945717/119648930-99b15c80-be54-11eb-83f4-e0de494cd52d.png)

**Comment by waruqi** [comment]
更新到 dev 再试试

**Comment by waruqi** [comment]
> 另外，在我的机器上使用powershell主题时，xrepo scan给出的包名字对比度弱，我有点散光识别困难，能否改进一下，截图如下：

为啥你这里偏暗，我这里很亮么。

![image](https://user-images.githubusercontent.com/151335/119665591-2402bc00-be67-11eb-892a-19e8bdc30368.png)

**Comment by waruqi** [comment]
如果觉得确实看不清的话，那就切到 plain 主题好了，xmake g --theme=plain

**Comment by x1244** [comment]
测试在线机器上，设置`network=private`时安装仍然提示找不到包。离线机器要明天才能给出结果。
```
PS C:\Users\conlay> ls C:\users\conlay\packages\s\spdlog\v1.8.5\3a6d86bc05784bc69ad7f92fea34de2c\


    目录: C:\users\conlay\packages\s\spdlog\v1.8.5\3a6d86bc05784bc69ad7f92fea34de2c


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2021/5/16     18:11                include
d-----         2021/5/16     18:11                lib
-a----         2021/4/17     20:06            568 manifest.txt
-a----         2021/5/16     18:11            224 references.txt


PS C:\Users\conlay> xmake g
configure
{
    qt = C:\Qt\Qt5.7.0
    network = private
    proxy_pac = pac.lua
    theme = powershell
}
PS C:\Users\conlay> xrepo import -i c:/users/conlay/packages spdlog
error: package(spdlog) not found!
error: execv(xmake require --import --packagedir=c:/users/conlay/packages --extra={system=false} spdlog) failed(-1)
PS C:\Users\conlay> xmake --version
xmake v2.5.4+202105260805, A cross-platform build utility based on Lua
```

**Comment by x1244** [comment]
配色那个看来也只能这样了。也不知道我这里的系统环境是怎么设置的，也可能是显示器的问题。

**Comment by waruqi** [comment]
> 测试在线机器上，设置network=private时安装仍然提示找不到包。离线机器要明天才能给出结果。

在更新下试试 dev


> 配色那个看来也只能这样了。也不知道我这里的系统环境是怎么设置的，也可能是显示器的问题。

可以自己搞个定制 theme 文件放到 `~/.xmake/themes/mytheme/xmake.lua` 里面去，然后用 xmake g --theme=mytheme 切下

定义参考：https://github.com/xmake-io/xmake/blob/master/xmake/themes/powershell/xmake.lua

**Comment by x1244** [comment]
在线机器`--network=private`仍然找不到包
```
PS C:\Users\conlay> xrepo import -i c:/users/conlay/packages spdlog
error: package(spdlog) not found!
error: execv(xmake require --import --packagedir=c:/users/conlay/packages --extra={system=false} spdlog) failed(-1)
```
在线机器`--network=public`可以安装成功

**Comment by waruqi** [comment]
刚 push 失败了，你再试试

**Comment by x1244** [comment]
更新了，还是一样的提示。
```
PS C:\Users\conlay> xrepo import -i c:/users/conlay/packagesx spdlog
error: package(spdlog) not found!
error: execv(xmake require --import --packagedir=c:/users/conlay/packagesx --extra={system=false} spdlog) failed(-1)
```

**Comment by waruqi** [comment]
那不可能，你怎么更新的？

**Comment by x1244** [comment]
上次更新确实可能有问题。
刚才又再试了一下，先设置`--network=public`，然后`xmake update dev`，可以看到xmake确实更新了时间和版本号
```
PS C:\Users\conlay> ls c:/tools/xmake/xmake.exe
    目录: C:\tools\xmake
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         2021/5/26     21:51        1147904 xmake.exe
PS C:\Users\conlay> xmake --version
xmake v2.5.4+202105261349, A cross-platform build utility based on Lua
```
再一次`--network=private`，然后导入包成功
```
PS C:\Users\conlay> xrepo import -i c:/users/conlay/packages spdlog
importing spdlog-v1.8.5 [vs_runtime:MT]
  <- c:/users/conlay/packages\s\spdlog\v1.8.5\3a6d86bc05784bc69ad7f92fea34de2c
PS C:\Users\conlay> xmake g
configure
{
    proxy_pac = pac.lua
    theme = powershell
    qt = C:\Qt\Qt5.7.0
    network = private
}
```
这是在线机器上测试的，离线机器测试结果晚上才能给出。

**Comment by waruqi** [comment]
xmake update dev是全量更新，win上得等ci跑完才会实际更新 否则拉取的还是老版本，可以用 xmake update -s dev 仅仅更新脚本

**Comment by x1244** [comment]
在线机器可以安装了，离线机器还不行。和原来的结果一样。

**Comment by waruqi** [comment]
%localappdata%/.xmake/repositories 下面 ，自己把 xmake-repo 整个放进去，这个是必须的。。既然离线了 不能自动拉取，只能你自己放

**Comment by x1244** [comment]
是%localappdata%目录，还是globaldir目录下.xmake/repositories.
如何查询%localappdata%目录？xmake show只能看到globaldir配置。

**Comment by waruqi** [comment]
win下 globaldir 就是 %localappdata% 目录，直接地址栏敲 %localappdata% 就能进去

**Comment by x1244** [comment]
我机器win10上%localappdata%目录是c:/users/conlay/AppData/Local,globaldir目录是c:/users/conlay/AppData/Roaming/.xmake,两个并不一样。
将globaldir下的repositories复制到离线机器上，并设置--network= private,可以导入包了。也能正常add_requires, add_packages.
还有一个问题，包只能一个一个导入吗？能不能import -i 将整个packages全导入呢？还是要自己写脚本来完成。对一台全新的离线开发机器，支持将packages中的所有包一下全导入会很友好的呢。
非常感谢及时修复!

**Comment by waruqi** [comment]
> 对一台全新的离线开发机器，支持将packages中的所有包一下全导入会很友好的呢。

还不如你直接 把 整个 globaldir copy 过去，不就完事了么。

**Comment by x1244** [comment]
> > 对一台全新的离线开发机器，支持将packages中的所有包一下全导入会很友好的呢。
> 
> 还不如你直接 把 整个 globaldir copy 过去，不就完事了么。

哦，还可以这样干!
那目标机器与源机器是不是要目录结构一致？

**Comment by x1244** [comment]
packages的目录结构中include目录下又用了一个包名称目录，这样在include包头文件时，要将这个目录一起include,比如spdlog包，要如下:
# include < spdlog/ spdlog.h>
与不使用包管理时，add_includedirs("/path/to/some/include")
可直接
# include < spdlog.h>
更直观，也更符合通常用法。
请问就是这样设计，并这样使用的吗？

**Comment by waruqi** [comment]
> > > 对一台全新的离线开发机器，支持将packages中的所有包一下全导入会很友好的呢。
> > 
> > 
> > 还不如你直接 把 整个 globaldir copy 过去，不就完事了么。
> 
> 哦，还可以这样干!
> 那目标机器与源机器是不是要目录结构一致？

走 xrepo import 也就是原样 copy 一遍，其他啥也没干。。



> packages的目录结构中include目录下又用了一个包名称目录，这样在include包头文件时，要将这个目录一起include,比如spdlog包，要如下:
> '# include < spdlog/ spdlog.h>'
> 与不使用包管理时，add_includedirs("/path/to/some/include")
> 可直接
> '# include < spdlog.h>'
> 更直观，也更符合通常用法。
> 请问就是这样设计，并这样使用的吗？

以spdlog官方使用为主，https://github.com/gabime/spdlog/blob/v1.x/example/example.cpp 都是 `spdlog/spdlog`，其他的 homebrew 等包管理器装的包，也都是 spdlog/spdlog 

没事，你干嘛要去掉一层呢。。没有spdlog目录隔离，同时用的包多了，各种同名 include header 冲突，到时候出现各种诡异编译问题，又要找我了。。

反正我是不会改，如果你非要这么用，那就自己 add_includedirs

**Comment by x1244** [comment]
好的，OK。我适应一下，可能有的库也需要适应一下。
