### ISSUE TITLE
`find_program` cache prevents finding previously unfound program

### ISSUE THREAD

**Issue by paul-reilly** [xmake-io/xmake#1430]
### Describe the bug
eg, We start with gdb not installed then:
```bash
> xmake run -d
error: debugger not found!
> pacman -S gdb

- - - - - - -

> xmake run -d
error: debugger not found!
```

### Expected behavior
For xmake to find gdb after installing it.

### Error output
```bash
checking for Cuda SDK directory ... no
checking for Cuda SDK directory ... no
error: @programdir/core/main.lua:279: @programdir/modules/devel/debugger/run.lua:279: debugger not found!
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:800]: in function 'raise'
    [@programdir/modules/devel/debugger/run.lua:279]: in function 'run'
    [@programdir/actions/run/main.lua:59]: in function '_do_run_target'
    [@programdir/actions/run/main.lua:83]: in function 'script'
    [@programdir/actions/run/main.lua:138]: in function '_run'
    [@programdir/actions/run/main.lua:201]:
    [C]: in function 'load'
    [@programdir/core/base/task.lua:519]: in function 'run'
    [@programdir/core/main.lua:277]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:365]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:800: in function 'raise'
	@programdir/core/main.lua:279: in function 'cotask'
	@programdir/core/base/scheduler.lua:365: in function <@programdir/core/base/scheduler.lua:362>
```

### Related Environment

- xmake version:v2.5.4+202105180112
- os: Manjaro
- target platform: Linux

### Additional context

The issue seems to be that the boolean `false` result from the cache is used here from the previous failed attempt at finding the tool:

https://github.com/xmake-io/xmake/blob/239c446b20ecceda838e0de77711be18805fab26/xmake/core/sandbox/modules/import/lib/detect/find_program.lua#L277-L281

... commenting it out fixes the issue. It has happened with doxygen and gdb so far.

**Comment by waruqi** [comment]
Yes, this is not a bug. Usually xmake caches the detection results to avoid repeated detection. Of course, this will also make it impossible to detect changes in the user's environment in time, such as the installation of gdb later.

Therefore, you only need to execute `xmake f -c` after installing gdb / doxygen to clean up the configuration cache, and xmake will try to detect gdb again.

**Comment by paul-reilly** [comment]
Ah, okay thanks. I thought that was for clearing a project config cache. I understand now, although my former self clearly needed a nicer error message. :)
