### ISSUE TITLE
add toolchain management mechanism

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1431]
### 你在什么场景下需要该功能？

目前xmake切换toolchain还是有点麻烦，每次切换都需要设置`--toolchain=... --sdk=... --bin=...`，手动输入很容易出错。

一台机器上的toolchain数量是相对固定的，xmake可以使用全局缓存/用户配置来设置机器上所有toolchain配置，简化toolchain的指定。

在机器上toolchain很多（hpc领域常见）时这个功能有很大帮助。这点spack做的很好 https://spack.readthedocs.io/en/latest/getting_started.html#compiler-configuration

### 描述可能的解决方案

用一个.xmake/toolchain.lua描述
```lua
function get_toolchains() {
	local toolchains = {}
	table.insert(toolchains, {vendor = "gcc", alias = "gcc-10", sdk = "/usr/bin", cc = "gcc-10", cxx = "g++-10"})
	table.insert(toolchains, {vendor = "intel", alias = "icc-15", sdk = "/opt/share/intel/15", cc = "icc", cxx = "icc"})
	for _, i in ipairs({"5", "6", "7", "8"}) do
		table.insert(toolchains, {vendor = "clang", alias = "clang-" .. i, sdk = "/opt/share/clang-" .. i , cc = "clang", cxx = "clang++"})
	end
	return {default = "gcc-10", toolchains = toolchains}
}
```

优点是灵活，缺点是不方便自动生成/修改，必须用户手写，且写起来比较麻烦

### 描述你认为的候选方案

用.xmake/toolchain.json描述
```json
{
	"default": "gcc-10",
	"toolchains": [
		{"vendor": "gcc", "alias": "gcc-10", "sdk": "/usr/bin", "cc": "gcc-10", "cxx": "g++-10"},
		{"vendor": "intel", "alias": "icc-15", "sdk": "/opt/share/intel/15", "cc": "icc", "cxx": "icc"},
		
	]
}
```

这种个人看来更好，因为可以结合xmake的自动搜索来比较方便地生成文件，更容易集成到ide中，更容易和remote toolchain结合（xrepo install xxx时自动更新toolchain.json），在发现toolchain失效的时候也可以自动移除。一般toolchain描述也不太需要复杂的逻辑控制。

### 其他信息

还需要一个命令来显示已有的toolchain、自动探测toolchain，但是`xmake show -l toolchains`已经被占用了，需要一个新的接口

**Comment by waruqi** [comment]
> 目前xmake切换toolchain还是有点麻烦，每次切换都需要设置--toolchain=... --sdk=... --bin=...，手动输入很容易出错。

一台机器上的toolchain数量是相对固定的，xmake可以使用全局缓存/用户配置来设置机器上所有toolchain配置，简化toolchain的指定。


自己搞个 toolchains 目录，放置所有 xxx.lua 的 toolchain() 定义，然后 xmake.lua 里面 includes("xxx/toolchains/*.lua") 全部加载进来

然后自己根据自己的平台，if is_plat + set_toolchains("") 不就完事了么。。也可以搞个rule 自己配置自己的工具链生效规则。。

完全没必要 xmake f --toolchain..
