### ISSUE TITLE
Add a way for xmake packages to override their vs_runtime

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#1437]
### Is your feature request related to a problem? Please describe.
For now, xmake will automatically install every package and report the vs_runtime to them:
```
lynix@OrdinateurElise:/mnt/c/Users/lynix/Documents/GitHub/NazaraEngine$ xmake.exe project -k vsxmake
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2019
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> zlib 1.2.11 [vs_runtime:MD, from:assimp]
  -> assimp 5.0.1 [vs_runtime:MD]
  -> chipmunk2d 7.0.3 [vs_runtime:MD]
  -> dr_wav 0.12.19 [vs_runtime:MD]
  -> freetype 2.10.4 [vs_runtime:MD]
  -> libogg v1.3.4 [vs_runtime:MD, from:libvorbis,libflac]
  -> libflac 1.3.3 [vs_runtime:MD]
  -> libsdl 2.0.14 [vs_runtime:MD]
  -> minimp3 2021.05.29 [vs_runtime:MD]
  -> stb 0.0 [vs_runtime:MD]
  -> libvorbis 1.3.7 [with_vorbisenc:n, vs_runtime:MD]
  -> newtondynamics v3.14d [vs_runtime:MD]
in local-repo:
  -> nodeeditor 2.1.3 [optional, vs_runtime:MD]
please input: y (y/n/m)
```

But some of theses packages don't care about vs_runtime, either because:
- they're C shared libraries and aren't affect by vs_runtime (ex: SDL2 under windows)
- they're header-only libraries (ex: dr_wav, minimp3)

### Describe the solution you'd like
A way for a package to override the vs_runtime it uses (except maybe if the project forces it using configs)

### Describe alternatives you've considered
Setting vs_runtime in my project myself for every package and their dependency, which is a bit annoying.

**Comment by waruqi** [comment]
> they're C shared libraries and aren't affect by vs_runtime (ex: SDL2 under windows)

But it depends on other static libraries. This can also cause problems, If the runtime of the dependent libraries are inconsistent with it. We cannot simply disable vs_runtime directly in the package definition

> they're header-only libraries (ex: dr_wav, minimp3)

At present, I did not think of good interfaces to configure them in the package definition, because in addition to vs_runtime, there are many other builtin configurations that have to be processed. It is also very cumbersome to configure it for each headeronly package.

Therefore, you can first use `add_requireconfs` to rewrite packages that do not require vs_runtime. In your project, there are not many such packages. you need not set vs_runtime separately for each package.

**Comment by SirLynix** [comment]
> But it depends on other static libraries. This can also cause problems, If the runtime of the dependent libraries are inconsistent with it. We cannot simply disable vs_runtime directly in the package definition

With some packages which are simply downloading binaries like SDL does, I don't think this can be a problem.

> At present, I did not think of good interfaces to configure them in the package definition, because in addition to vs_runtime, there are many other builtin configurations that have to be processed. It is also very cumbersome to configure it for each headeronly package.

Yeah it's cumbersome to have to do it in each xmake project as well, which I why I think it could be handled inside the package definition.

On a side note, not really related to this, I've noticed xmake takes vs_runtime into account on Linux, I think it could be forcely set to nil for other platforms than Windows

**Comment by waruqi** [comment]
I improved xmake on dev and mark some libs as headeronly. them will ignore vs_runtime.

```lua
package("dr_flac")
    set_kind("library", {headeronly = true})
```

you can try it again.

**Comment by SirLynix** [comment]
Oh this is great, thank you!
I tested it and it works like a charm.

**Comment by SirLynix** [comment]
Oh I've noticed that headeronly libs are still separated by their arch (x86/x64), debug and shared config flags, wouldn't that be a good idea to ignore these as well for header only libs?

**Comment by waruqi** [comment]
> Oh I've noticed that headeronly libs are still separated by their arch (x86/x64), debug and shared config flags, wouldn't that be a good idea to ignore these as well for header only libs?

Some special packages may depend on the architecture to export specific macro definitions. Therefore, I cannot completely ignore them for the time being.

```lua
package("xxx")
    if is_plat("x86") then
        add_defines("XXX_ARCH_X86")
    end
    on_load(function (package)
        if package:debug() then
             package:add("defines", "XXX_DEBUG")
        end
    end)
```

**Comment by SirLynix** [comment]
I understand.

Here's an idea: wouldn't it be a good idea to add a hook to packages to give them the ability to get and change their configuration?

This would enable package that don't rely on this type of config to discard them (reset them to default/nil), and would also allow to handle some packages such as libsdl on Windows which is always shared for now (which means their shared/debug/vs_runtime configs don't have any effect).

**Comment by SirLynix** [comment]
for example:
```lua
package("libsdl")
    on_config("windows", function (config)
        config.debug = nil
        config.shared = true
        config.vs_runtime = nil
    end)```

**Comment by waruqi** [comment]
> for example:
> 
> ```lua
> package("libsdl")
>     on_config("windows", function (config)
>         config.debug = nil
>         config.shared = true
>         config.vs_runtime = nil
>     end)
> ```

This is too complicated and will make the package definition more complicated. I don't plan to consider it at the moment, just deal with the headeronly packet type.

**Comment by SirLynix** [comment]
I understand it's a bit cumbersome but it would only be required for a few packages (especially the binary ones) as xmake already properly handle all other packages the right way (+ headeronly feature now).

The headeronly feature you added is already great, thanks for that.

**Comment by waruqi** [comment]
debug/shared is nil by default, so this will not cause users to download and install repeatedly unless the user explicitly sets them.

**Comment by SirLynix** [comment]
By default shared is false, which means than doing this:
```lua
add_requires("libsdl", { configs = { shared = true }))
```

will install the package once, no problem so far.
Then he may want to link libsdl statically
```lua
add_requires("libsdl", { configs = { shared = false }))
```

For now, xmake will install libsdl a second time, but it will be identical to the first installation because on Windows libsdl is always downloaded from the precompiled binaries and the user won't understand why libsdl is not statically linked (I've been there).

A `on_config` or `check_config` hook would be a good place to override the configuration (to prevent installing a second time, it's not a big deal for libsdl but it may be for bigger packages as it takes time and disk space).

For example:
```lua
package("libsdl")
    on_config("windows", function (config)
        if config.shared == false then
             warn("libsdl is only supported a shared library on windows for now")
        end
        if config.debug == true then
             warn("libsdl doesn't support debug builds for now")
        end
        config.shared = true
        config.debug = nil
        config.vs_runtime = nil
    end)
```

Also, users can easily set some configurations on some packages that don't support it, for example:
```lua
add_requires("chipmunk2d", "dr_wav", "entt", "freetype", "libflac", "libsdl", "minimp3", "stb", { debug = is_mode("debug") )
```

**Comment by waruqi** [comment]
so we only add `assert` to check it in on_load/on_install, like this

https://github.com/xmake-io/xmake-repo/blob/7e26ab1473213d447f2e6f5f99e55a327bf3c5a5/packages/c/cef/xmake.lua#L37

https://github.com/xmake-io/xmake-repo/blob/7e26ab1473213d447f2e6f5f99e55a327bf3c5a5/packages/s/spdlog/xmake.lua#L43-L45

**Comment by xq114** [comment]
Provide a default value for `shared` could also help.

```lua
add_configs("shared", {description = "Build shared library.", default = is_plat("windows"), type = "boolean"})
```

**Comment by SirLynix** [comment]
> so we only add `assert` to check it in on_load/on_install, like this

Yes, but this doesn't prevent installing the library a second time even if the option does nothing (example: libsdl in static mode), and is a hard error. In my example it's simply a warning that will be emitted everytime the user builds its project until he changes the option, I find it a bit better than a failed assert.

**Comment by waruqi** [comment]
> Provide a default value for `shared` could also help.
> 
> ```lua
> add_configs("shared", {description = "Build shared library.", default = is_plat("windows"), type = "boolean"})
> ```

I have improved it, and add `readonly = true` attribute to avoid user to modify it's value.

```lua
package("libsdl")
    if is_plat("windows", "mingw") then
        add_configs("shared", {description = "Build shared library.", default = true, type = "boolean", readonly = true})
        add_configs("vs_runtime", {description = "Set vs compiler runtime.", default = "MD", readonly = true})
    end
```

**Comment by xq114** [comment]
> ```lua
> package("libsdl")
>     if is_plat("windows", "mingw") then
>         add_configs("shared", {description = "Build shared library.", default = true, type = "boolean", readonly = true})
>         add_configs("vs_runtime", {description = "Set vs compiler runtime.", default = "MD", readonly = true})
>     end
> ```

It's not required to fix the `vs_runtime` config since on windows shared library can be linked to either static runtime or dynamic runtime

**Comment by waruqi** [comment]
> > ```lua
> > package("libsdl")
> >     if is_plat("windows", "mingw") then
> >         add_configs("shared", {description = "Build shared library.", default = true, type = "boolean", readonly = true})
> >         add_configs("vs_runtime", {description = "Set vs compiler runtime.", default = "MD", readonly = true})
> >     end
> > ```
> 
> It's not required to fix the `vs_runtime` config since on windows shared library can be linked to either static runtime or dynamic runtime

Different vs_runtime configurations will generate different buildhash, so every time the user modifies vs_runtime, the libsdl package will be repeatedly installed in different buildhash directories. 

But the binary files of libsdl are the same, it should only need to be installed once. for example:

```lua
set_runtimes("MD")
add_requires("libsdl")
```

```lua
set_runtimes("MDd")
add_requires("libsdl")
```

```lua
add_requires("libsdl", {configs = {vs_runtime = "MT"}})
```

If you do not fix it, then the user modifies the configuration three times, and the package will be installed three times.

**Comment by SirLynix** [comment]
This sure is an improvement, thank you.

Perhaps it would be great to have a warning if a user sets a readonly config on a package with a different value than the default one?

**Comment by waruqi** [comment]
> This sure is an improvement, thank you.
> 
> Perhaps it would be great to have a warning if a user sets a readonly config on a package with a different value than the default one?

If there are too many packages, set_runtimes may trigger a lot of warnings. Each package configuration prompt can basically see some information.

**Comment by SirLynix** [comment]
I understand, maybe trigger a warning except for set_runtimes since it's the only automatic config (I think?).

**Comment by waruqi** [comment]
> I understand, maybe trigger a warning except for set_runtimes since it's the only automatic config (I think?).

It is a bit troublesome to distinguish them, so I won't consider it for now.
