### ISSUE TITLE
Allow resource to be a git repository

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1442]
### 你在什么场景下需要该功能？

resource为git repo，带submodules

### 描述可能的解决方案

add_resources("foo", "https://github.com/foo/bar.git", "<commit>")

### 其他信息

https://bkaradzic.github.io/bgfx/build.html

**Comment by waruqi** [comment]
支持了，dev ，你试试

add_resources("foo", "https://github.com/foo/bar.git", "commit_or_tag")

package:resourcefile(xx) 返回的就是 resource git dir

**Comment by xq114** [comment]
第二次测试的时候报错

```
git clone https://github.com/bkaradzic/bimg.git C:\Users\xq114\AppData\Local\.xmake\cache\packages\2106\b\bgfx\7816\resources\bimg\bimg.git
fatal: destination path 'C:\Users\xq114\AppData\Local\.xmake\cache\packages\2106\b\bgfx\7816\resources\bimg\bimg.git' already exists and 
is not an empty directory.
```

是否可以加一个探测，类似download url那样？

**Comment by waruqi** [comment]
再更新下试试 dev

**Comment by waruqi** [comment]
这个应该可以的，你先试试吧，有问题再开。
