### ISSUE TITLE
一个功能性头文件, 提供更多的print用法

### ISSUE THREAD

**Issue by zhangtianxiao** [xmake-io/xmake#1443]
https://github.com/esneider/debug/blob/master/debug.h
在xmake里可以编译通过, 但执行没有效果
单独用clang编译 正常执行
环境是 win64, amd, xmake v2.5.4+202106041624

**Comment by zhangtianxiao** [comment]
代码附件
https://cowtransfer.com/s/0db80b1329c843
取件码
479888

**Comment by zhangtianxiao** [comment]
似乎错了, 单独编译时, 用的qt带的cl, 
xmake用的是 vs的cl

**Comment by xq114** [comment]
xmake f -m debug 切换到debug mode

xmake默认开启release，debug功能不可用

**Comment by waruqi** [comment]
是的，你用了 debug() 去 print，而 release 下，debug.h 禁用了

```
#ifdef NDEBUG
#define debug(...) ((void)0)
#else
```

xmake 默认 release 模式，会设置 NDEBUG
