### ISSUE TITLE
os.dirs seems to list duplicated content

### ISSUE THREAD

**Issue by yangguany** [xmake-io/xmake#1444]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
when printing the result of os.dirs, its content appears 4 times.

### Expected behavior
os.dirs lists unique content from given directory.

### Error output
xmake.lua:
```lua
print(os.dirs("E:/projects/xmake_test/testFolder"))
for k, dir in ipairs(os.dirs("E:/projects/xmake_test/testFolder/**")) do
    print(k, dir)
end

target("test")
    set_kind("binary")
```

directory structure:
```
E:/projects/xmake_test/testFolder:
└───include
    ├───f1
    │   └───t1
    └───f2
```

results:
```
PS E:\projects\xmake_test> xmake f -p windows -a x64
table: 0x0234b24a8d60
1       E:\projects\xmake_test\testFolder\include
2       E:\projects\xmake_test\testFolder\include\f1
3       E:\projects\xmake_test\testFolder\include\f1\t1
4       E:\projects\xmake_test\testFolder\include\f2
table: 0x0234b24b12b8
1       E:\projects\xmake_test\testFolder\include
2       E:\projects\xmake_test\testFolder\include\f1
3       E:\projects\xmake_test\testFolder\include\f1\t1
4       E:\projects\xmake_test\testFolder\include\f2
table: 0x0234b2658f30
1       E:\projects\xmake_test\testFolder\include
2       E:\projects\xmake_test\testFolder\include\f1
3       E:\projects\xmake_test\testFolder\include\f1\t1
4       E:\projects\xmake_test\testFolder\include\f2
table: 0x0234b265b150
1       E:\projects\xmake_test\testFolder\include
2       E:\projects\xmake_test\testFolder\include\f1
3       E:\projects\xmake_test\testFolder\include\f1\t1
4       E:\projects\xmake_test\testFolder\include\f2
```

### Related Environment
- xmake version: v2.5.4
- os: windows 10
- target platform: windows 10 x64

### Other question
can i define a string variable to save path info and then use it in the later?  see
```lua
HOMEDIR="path/to"
target("test")
    add_inlcudedirs("$(HOMEDIR)/include")  # tried this but did not converted as expected
```

**Comment by waruqi** [comment]
don't call print in the description scope, because it will be executed multiple times, remember: it will be executed multiple times! ! !

If you want to debug some information or write complex scripts, please configure it in the script scope. such as `on_load`, after_build, before_install, on_xxx etc

you can see docs: https://xmake.io/#/guide/syntax_description?id=description-scope

**Comment by yangguany** [comment]
thanks to your reply.
Putting the print code in `debug.lua` and called `on_load`, i got the expected result.

but another question:
can i define a string variable to save path info and then use it in the later? see
```lua
HOMEDIR="path/to"
target("test")
    add_inlcudedirs("$(HOMEDIR)/include")  # tried this but did not converted as expected
    --  print("$(HOMEDIR)/include")    -- this do not replace $(HOMEDIR) with "path/to"
```

**Comment by waruqi** [comment]
use option() or lua string variable 

https://xmake.io/#/manual/configuration_option?id=option
