### ISSUE TITLE
How to disable the built-in objc/arc flags

### ISSUE THREAD

**Issue by xiaoqunSun** [xmake-io/xmake#1446]
我创建了一个简单的C++/Objec-C混编工程。
希望通过 add_mxxflags("-fno-objc-arc") 关闭arc 但是不起作用

通过 xmake project -k compile_commands 调试发现 

```
 "arguments": ["/usr/bin/xcrun -sdk macosx clang", "-c", "-pipe", "-DIBOutlet=__attribute__((iboutlet))", "-DIBOutletCollection(ClassName)=__attribute__((iboutletcollection(ClassName)))", "-DIBAction=void)__attribute__((ibaction)", "-Qunused-arguments", "-mmacosx-version-min=10.15", "-arch", "x86_64", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk", "-fvisibility=hidden", "-O3", "-framework", "Foundation", "-framework", "CoreFoundation", "-fno-objc-arc", "-fobjc-arc", "-o", "build/.objs/testXmake/macosx/x86_64/release/test.mm.o", "test.mm"],
```

=============================
"-fno-objc-arc", "-fobjc-arc" 两个都存在。似乎add_mxxflags("-fno-objc-arc"并未正确生效 还是我的使用方法有问题？

**Comment by waruqi** [comment]
目前 arc 是默认的内置 flags，目前可以通过 `set_values("objc.build.arc", false)` 来显式禁用它。

不过现在不推荐这个搞，我刚 dev 更新了下，支持用户在外面直接通过 `add_mxxflags("-fno-objc-arc")` 来覆盖内部的配置，你只需要更新到 dev 版本再试试就行了。。`xmake update -s dev`

**Comment by xiaoqunSun** [comment]
更新到dev 没问题了
感谢!
