### ISSUE TITLE
Automatically reset references.txt on exporting packages

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1448]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
包内部的references.txt文件仍会保留原机器上各个repo的路径信息，出于使xrepo正常工作以及隐私保护的考虑，应当在导出包的时候清理

**Comment by waruqi** [comment]
不用重置，导出的包里面，我整个删了
