### ISSUE TITLE
linux 链接时未加入-fopenmp参数。

### ISSUE THREAD

**Issue by Huberion** [xmake-io/xmake#1450]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

linux项目用到了openmp，xmake执行的命令中只有cpp文件编译时加了-fopenmp命令，链接时没有加。

### 期待的结果

略

### 错误信息

生成的是动态库，使用dlopen打开时报错 undefined symbol: GOMP_critical_start

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：v2.5.4
- xmake运行平台：linux x86_64
- xmake目标平台：linux x86_64

### 其他信息

使用ldd查看生成的动态库，没有链接到libgomp
当手动把链接命令中加入-fopenmp时ldd可以查看链接到了libgomp

**Comment by waruqi** [comment]
好歹贴下 xmake.lua 么，不然我怎么知道你这什么情况。

**Comment by Huberion** [comment]
```lua
target("MyShared")
    set_kind("shared")
    add_rules("c++.openmp")
    add_files("src/**.cpp")
target_end()
```

源码中用到了
#pragma omp critical
#pragma omp parallel for

对生成的动态库使用ldd命令，未发现链接到libgomp库。
我使用xmake b -v MyShared，链接.o文件生成.so的链接命令没有-fopenmp参数。

**Comment by Huberion** [comment]
我能不能不用这个包，我的开发环境在内网，导入一个东西挺麻烦的。而且我的linux环境中有libgmp.so.1。链接时加入-fopenmp的话，就会链接到这个库。不会默认链接环境中的openmp库吗？

**Comment by waruqi** [comment]
走add_requires包 默认就是优先检测系统库，只有找不到才会走下载

也可以强制仅仅走系统库 add_requires("xxx", {system = true})
