### ISSUE TITLE
Support to download and install precompiled image packages from xmake-mirror

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#1454]
I will try to make a pre-compiled image of the windows package first.

### Build and upload automatically

We will add `autobuild` branch to build package in each package repo. example:

xmake-mirror/openssl (autobuild branch)
- .github/workflow/windows.yml
  - download autobuild.lua from xmake-repo/packages
  - automatically run autobuild.lua to build all artifacts (MT, MD, shared, static ..)  
  - upload artifacts to releases, e.g. xmake-mirror/openssl/releases/1.57/[buildhash].zip` and `xxx.zip.sha256`

we download `package/autobuild.lua` script from `xmake-repo` to maintain automatic pre-compilation build tasks, upload the compiled artifacts to xmake-mirror/package/releases in ci.

### Configure mirror sources

we need not add `on_install()` if we install from the precompiled image sources.

```lua
package("openssl")

    -- source urls
    add_urls("https://www.openssl.org/source/openssl-$(version).tar.gz", {alias = "home", excludes = "*/fuzz/*"})    
    add_versions("home:1.1.1k", "892a0875b9872acd04a9fde79b1f943075d5ea162415de3047c327df33fbaee5")

    -- precompiled image urls
    add_urls("https://github.com/xmake-mirror/openssl/releases/download/$(version)/$(buildhash).zip", {precompiled = true})

    on_load("windows", function (package)
        if not package:is_precompiled() then -- we need not these deps if we install it from precompiled image directly.
             package:add("deps", "strawberry-perl", "nasm")
        end
    end)
```

### Select install package from binary mirror or code source.

```lua
-- dowload precompiled image and install it by default
add_requires("openssl")

-- build source and install it
add_requires("openssl", {precompiled = false})
```

Or 

```console
$ xrepo install --precompiled=n openssl
```

**Comment by xq114** [comment]
Some binary dependencies is only required in the build stage. If the package is downloaded from remote, these dependencies will not be required once more. There should be some marks for the situation.

**Comment by waruqi** [comment]
> Some binary dependencies is only required in the build stage. If the package is downloaded from remote, these dependencies will not be required once more. There should be some marks for the situation.

see 

>         if not package:is_precompiled() then -- we need not these deps if we install it from precompiled image directly.
>              package:add("deps", "strawberry-perl", "nasm")
>         end
>

**Comment by SirLynix** [comment]
This is such a great addition, as some packages can take a lot of time to build.

What packages will be concerned and how will they be added to xmake-mirror?

**Comment by waruqi** [comment]
> This is such a great addition, as some packages can take a lot of time to build.
> 
> What packages will be concerned and how will they be added to xmake-mirror?

Some packages that compile slowly or are more commonly used, such as boost openssl and so on. I will try the windows platform first.

Due to permissions issues, currently I can only manually create the specified package repo in xmake-mirror. Of course, users can also request pre-compiled packages in issues.

For contributors, you can also apply to join the xmake-mirror organization and get permission to create package repo.

**Comment by waruqi** [comment]
https://github.com/xmake-mirror/build-artifacts will be an official xmake package artifacts repository.

## Submit and update package artifacts

We need only edit [build.txt](https://github.com/xmake-mirror/build-artifacts/blob/build/build.txt) to modify package name and versions on `build` branch.

It will trigger ci build jobs to build/upload artifacts to releases/assets and update manifest to `main` branch.

**Comment by waruqi** [comment]
The artifacts repository has been completed.

Trigger building

1. update or add package to xmake-repo on dev branch
2. merge info master branch
3. run deploy jobs on ci and push build info to xmake-mirror/build_artifacts on build branch
4. run build jobs on build_artifacts/ci
5. upload artiacts to releases/assets in build_artifacts repo
6. push manifest file to build_artifacts on main branch
7. run test jobs to test precompiled artifacts on main ci

**Comment by waruqi** [comment]
I have completed the support for installing packages from precompiled artifacts in the `precompiled` branch. You can try it in advance and welcome feedback.

Currently, only the pre-compiled products of the openssl/boost package are included for windows.

```console
$ xmake update -s github:xmake-io/xmake#precompiled
$ xrepo update-repo
$ xrepo install -vD --shallow openssl
```

**Comment by Alex2772** [comment]
Hello, thanks for great project.

> I will try to make a pre-compiled image of the windows package first.

@waruqi  Do you plan to support other platforms as well? Is there a documentation about support of pre-compiled binaries and how to set up your own mirror with binary packages?

**Comment by waruqi** [comment]
We don't plan to support it for the time being, but you can define the package yourself by simply modifying the urls.
https://github.com/xmake-io/xmake-repo/blob/0a19b4f7f9fd14bdb4f7a8613d7c046790d26449/packages/l/llvm/xmake.lua#L75
