### ISSUE TITLE
xmake turbojpeg 安卓armeabi-v7a不正常

### ISSUE THREAD

**Issue by dsp2000** [xmake-io/xmake#1459]
> Note: If it is a 'bug report' or 'feature request', please select the corresponding issue template, otherwise this issue will be not replied. 

### Describe the problem details
Please describe your problem details here.

xmake turbojpeg
编译到x86可以使用，但在 安卓armeabi-v7a不正常，生成的so加载不成功。去掉 add_packages("libjpeg-turbo")后可以的

另外，没有生成turbojpeg的include文件。

这个可以单独生成*.a文件吗？现在是直接回到项目的，也不知*.a及一些临时文件放在哪里。

**Comment by dsp2000** [comment]
xmake turbojpeg
编译到x86可以使用，但在 安卓armeabi-v7a不正常，生成的so加载不成功。去掉 add_packages("libjpeg-turbo")后可以的

另外，没有生成turbojpeg的include文件。

这个可以单独生成*.a文件吗？现在是直接回到项目的，也不知*.a及一些临时文件放在哪里。

**Comment by waruqi** [comment]
走 xrepo export 自己导出

**Comment by dsp2000** [comment]
刚才测试了，x86及arm64-v8a者可以正常运行已加入 [v7a_turbojpeg.zip](https://github.com/xmake-io/xmake/files/6683428/v7a_turbojpeg.zip) 的so的。只有armeabi-v7a不行。

已经确认手机的libKcCore.so是正确的编译文件，md5验证过的。加载的示范代码如下：
void* handle = dlopen( dllPath, RTLD_LAZY );

if( !handle )    {
	dlerror()
	Cannot load library: find_library[1202]:  1935 'libKcCore.so' failed to load previously  
}

说明add_packages("libjpeg-turbo")后，生成的so不能被dlopen所认识了

**Comment by dsp2000** [comment]
刚才测试了，x86及arm64-v8a者可以正常运行已加入turbojpeg 的so的。只有armeabi-v7a不行。

 v7a_turbojpeg.zip是有问题的so

**Comment by dsp2000** [comment]
xmake -r -vD > t.txt
[t.zip](https://github.com/xmake-io/xmake/files/6683756/t.zip)

**Comment by dsp2000** [comment]
E:\Android\sdk\ndk\21.0.6113669\KcCore>xmake f -p android --ndk=E:\Android\sdk\n
dk\21.0.6113669 -a armeabi-v7a --ndk_sdkver=18 --ndk_cxxstl=c++_static -vD -c
checking for Android SDK directory ... E:\Android\sdk
checking for Build Tools Version of Android SDK ... 30.0.3
checking for NDK directory ... E:\Android\sdk\ndk\21.0.6113669
checking for SDK version of NDK ... 18
checking for toolchains version of NDK ... 4.9
checking for unzip ... ok
checking for git ... ok
checkinfo: cannot runv(gzip.exe --version), No such file or directory
checking for gzip ... no
checking for 7z ... D:\Program Files (x86)\xmake\winenv\bin\7z
checking for cmake ... no
checking for vswhere.exe ... C:\Program Files (x86)\Microsoft Visual Studio\Inst
aller\vswhere.exe
checking for Microsoft Visual Studio (armeabi-v7a) version ... no
checking for cmake ... ok
checking for nasm ... no
finding libjpeg-turbo from xmake ..
checking for clang++ ... E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuil
t\windows-x86_64\bin\clang++
checking for the shared library linker (sh) ... clang++
checking for clang++ ... E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebuil
t\windows-x86_64\bin\clang++
checking for the linker (ld) ... clang++
checking for xmake::libjpeg-turbo ... libjpeg-turbo 2.1.0
configure
{
    mode = release
    arch = armeabi-v7a
    plat = android
    ccache = true
    host = windows
    ndkver = 21
    ndk = E:\Android\sdk\ndk\21.0.6113669
    ndk_sdkver = 18
    android_sdk = E:\Android\sdk
    clean = true
    build_toolver = 30.0.3
    ndk_toolchains_ver = 4.9
    buildir = build
    ndk_cxxstl = c++_static
    kind = static
    ndk_stdcxx = true
}

E:\Android\sdk\ndk\21.0.6113669\KcCore>

**Comment by dsp2000** [comment]
add_rules("mode.debug", "mode.release")
add_requires("libjpeg-turbo")
target("KcCore")
set_kind("shared")
set_languages("c99", "cxx11")
set_warnings("all")
add_includedirs("include", "ffmpeg", "include/lame", "include/turbojpeg", "D:/Library/Fwb")		-- 
add_linkdirs("libs/$(arch)")

add_files("src/ffmpeg.c", "src/cmdutils.c", "src/ffmpeg_opt.c", "src/ffmpeg_filter.c", "src/ffmpeg_hw.c", "src/decInfo.c", "D:/Library/Fwb/FwbFifo.c")
add_files("src/decFile.c", "src/decAudio.c", "src/decVideo.c", "src/encFile.c", "src/encData.c", "src/camera.c", "src/yuvUtils.c", "src/jpegFile.c", "src/main.cpp")

add_links("avformat", "swscale", "swresample", "avfilter", "postproc", "avcodec", "avutil");
add_links("mp3lame", "x264", "fdk-aac", "yuv");

add_packages("libjpeg-turbo")

add_syslinks("log", "z", "android", "jnigraphics")
add_shflags("-Wl,--no-undefined")

**Comment by waruqi** [comment]
> 刚才测试了，x86及arm64-v8a者可以正常运行已加入 [v7a_turbojpeg.zip](https://github.com/xmake-io/xmake/files/6683428/v7a_turbojpeg.zip) 的so的。只有armeabi-v7a不行。
> 
> 已经确认手机的libKcCore.so是正确的编译文件，md5验证过的。加载的示范代码如下：
> void* handle = dlopen( dllPath, RTLD_LAZY );
> 
> if( !handle ) {
> dlerror()
> Cannot load library: find_library[1202]: 1935 'libKcCore.so' failed to load previously
> }
> 
> 说明add_packages("libjpeg-turbo")后，生成的so不能被dlopen所认识了

一种可能是 libjpeg 引入了一些高版本 ndk api，导致加载失败。需要自己编译的时候，调高 sdk api version，当然还有可能是其他原因

具体原因，只能你自己排查，比如看 logcat 。。

**Comment by dsp2000** [comment]
调高版本之前已经试过了的。如果用了高版本的ndk api，链接应该是过不了的。没有提示出错说明所有的库都已经包含了。如果是看运行的 logcat ，是没有的，因为还没有运行到so之前就死了。在编译libjpeg-turbo的armeabi-v7a时，配置会不会有什么问题？

**Comment by waruqi** [comment]
看 logcat 里面 load library 的错误提示。。否则我也不知道。

**Comment by dsp2000** [comment]
load library时，就调用dlopen一个函数。logcat 里面 没有错误提示 。 或者把你编译armeabi-v7a的脚本等文件给我这里试试？

**Comment by dsp2000** [comment]
现在用xmake f -p android --ndk=E:\Android\sdk\ndk\21.0.6113669 -a armeabi-v7a --ndk_sdkver=18 --ndk_cxxstl=c++_static -vD -c

我尝试改为
xmake f -p android --ndk=E:\Android\sdk\ndk\21.0.6113669 -a armeabi-v7a --ndk_sdkver=16 --ndk_cxxstl=c++_static -vD -c
checking for Microsoft Visual Studio (armeabi-v7a) version ... no
checking for cmake ... ok
checking for nasm ... no
finding libjpeg-turbo from xmake ..
checking for clang++ ... E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebui
t\windows-x86_64\bin\clang++
checking for the shared library linker (sh) ... clang++
checking for clang++ ... E:\Android\sdk\ndk\21.0.6113669\toolchains\llvm\prebui
t\windows-x86_64\bin\clang++
checking for the linker (ld) ... clang++
checking for xmake::libjpeg-turbo ... libjpeg-turbo 2.1.0
configure
{
    ndk_stdcxx = true
    ndkver = 21
    ccache = true
    buildir = build
    arch = armeabi-v7a
    ndk = E:\Android\sdk\ndk\21.0.6113669
    kind = static
    host = windows
    plat = android
    clean = true
    ndk_sdkver = 16
    ndk_cxxstl = c++_static
    android_sdk = E:\Android\sdk
    ndk_toolchains_ver = 4.9
    build_toolver = 30.0.3
    mode = release
}

xmake -r -vD > t.txt
[t.zip](https://github.com/xmake-io/xmake/files/6690198/t.zip)

**Comment by waruqi** [comment]
> load library时，就调用dlopen一个函数。logcat 里面 没有错误提示 。 或者把你编译armeabi-v7a的脚本等文件给我这里试试？

编译脚本在上面 你可以看下 https://github.com/xmake-io/xmake-repo/blob/master/packages/l/libjpeg-turbo/xmake.lua

**Comment by dsp2000** [comment]
就是这个脚本可以编译出来安卓 armeabi-v7a等等多个版本吗？我之前试编译完全过不了的

**Comment by waruqi** [comment]
嗯

**Comment by dsp2000** [comment]
使用你链接的xmake.lua没有生成对应的文件

D:\pAndroid\multimedia\app\jni\libjpeg-turbo-main>xmake f -p android --ndk=E:\An
droid\sdk\ndk\21.0.6113669 -a armeabi-v7a --ndk_sdkver=18 --ndk_cxxstl=c++_stati
c -vD -c
checking for Android SDK directory ... E:\Android\sdk
checking for Build Tools Version of Android SDK ... 30.0.3
checking for NDK directory ... E:\Android\sdk\ndk\21.0.6113669
checking for SDK version of NDK ... 18
checking for toolchains version of NDK ... 4.9
configure
{
    ndk_sdkver = 18
    mode = release
    android_sdk = E:\Android\sdk
    plat = android
    build_toolver = 30.0.3
    ndk_stdcxx = true
    ndkver = 21
    ndk_cxxstl = c++_static
    kind = static
    host = windows
    arch = armeabi-v7a
    clean = true
    ndk_toolchains_ver = 4.9
    buildir = build
    ndk = E:\Android\sdk\ndk\21.0.6113669
    ccache = true
}

D:\pAndroid\multimedia\app\jni\libjpeg-turbo-main>xmake -r -vD
[100%]: build ok!

D:\pAndroid\multimedia\app\jni\libjpeg-turbo-main>

[xmake.zip](https://github.com/xmake-io/xmake/files/6691841/xmake.zip)

**Comment by waruqi** [comment]
不要瞎用，这个只是包定义。仔细看文档：https://xmake.io/#/zh-cn/package/remote_package?id=%e4%bd%bf%e7%94%a8%e8%87%aa%e5%bb%ba%e7%a7%81%e6%9c%89%e5%8c%85%e4%bb%93%e5%ba%93

**Comment by dsp2000** [comment]
看了，但不明白。那真实的xmake.lua在哪里呢？

**Comment by waruqi** [comment]
> 看了，但不明白。那真实的xmake.lua在哪里呢？

没有 xmake.lua 。。https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/tools/cmake.lua

**Comment by dsp2000** [comment]
看了，实在没有明白，他最终都应该是使用到

**Comment by dsp2000** [comment]
看了，实在没有明白，他最终都应该是使用到实际编译的配置

**Comment by waruqi** [comment]
看不明白，那就自己调用 cmake 去编译 libjpeg 源码，不走 xmake 。。。按理你现在的问题 跟 xmake 已经没啥关系了。。armv7下库加载不了，也是 libjpeg 自身对 android 支持问题。。

xmake 只保证第三方库能够在不同平台编译通过，具体使用上的问题，你得自己研究。。

**Comment by dsp2000** [comment]
我是怀疑有些编译平台的cflag之类，或者针对硬件加速的一些配置

**Comment by waruqi** [comment]
这个你从 install -vD 里面就能看到验证编译 flags，自己可以对比下

**Comment by dsp2000** [comment]
E:\Android\sdk\ndk\21.0.6113669\KcCore>xmake install -vD
installing KcCore ..
install ok!

这里没有呢

**Comment by waruqi** [comment]
xrepo install

**Comment by dsp2000** [comment]
E:\Android\sdk\ndk\21.0.6113669\KcCore>xrepo install -vD
error: @programdir\core\main.lua:279: @programdir\modules\private\xrepo\action\i
nstall.lua:229: please specify the packages to be installed.
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:796]: in function 'raise'
    [@programdir\modules\private\xrepo\action\install.lua:229]: in function 'act
ion'
    [@programdir\modules\private\xrepo\main.lua:196]: in function 'func'
    [@programdir\plugins\lua\main.lua:123]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:519]: in function 'run'
    [@programdir\core\main.lua:277]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:365]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:796: in function 'raise'
        @programdir\core\main.lua:279: in function 'cotask'
        @programdir\core\base\scheduler.lua:365: in function <@programdir\core\b
ase\scheduler.lua:362>
E:\Android\sdk\ndk\21.0.6113669\KcCore>

**Comment by waruqi** [comment]
。。。。。看下文档使用说明 指定下参数，我只是随手敲的 不要照搬  自己好好想想，不传平台和报名， xrepo install 还能自己猜出来？

**Comment by dsp2000** [comment]
感觉很难。现在的情况看来还是需要用cmake。建议xmake做一个功能，将cmake及make的脚本转换到xmkae.lua的。完善这个可能就能让人直接跳过学习 cmake及make等其他方式了。模块是支持不完的，但方法是可以复用的

**Comment by waruqi** [comment]
你可能想的太简单了，从 cmake 转 xmake 的工作量够我大半年了，还不稳定可靠。。我是没时间折腾。。有这点时间，你还不如自己花时间学习下cmake

**Comment by dsp2000** [comment]
我明白这里面的难度的。但如果xmake需要更多使用的用户，可能这个角度会比较好。你想他们做项目使用了xmake, 如果还需要使用cmake或其他。对于暂时小众的xmake可能没有优势

**Comment by waruqi** [comment]
xmake-repo 很多包，原本我就直接 port 到了 xmake.lua 不依赖 cmake，但是自动转原本就不现实，差异太大。。你只能人工 port  

另外 xmake-repo 仓库的包，尽可能复用 cmake /autoconf ，可以做大兼容度支持第三方包，另外对用户来讲  只需要 xrepo install xxx 或者走 add_requires ，完全不需要学 cmake，你可以把它当成不存在，xmake 内部自己会处理 cmake 的一切问题。。

这本身没有冲突，干嘛要 转，转了不稳定，各种不兼容。。你现在的问题跟是否用了 cmake 又没啥本质关系。。。

**Comment by dsp2000** [comment]
但是有问题还是需要回到cmake，这个很痛苦

**Comment by dsp2000** [comment]
如果你本来就已经用 cmake转xmake来编译，那我们只需要分析xmake可能就找到问题了

**Comment by waruqi** [comment]
> 但是有问题还是需要回到cmake，这个很痛苦
> 如果你本来就已经用 cmake转xmake来编译，那我们只需要分析xmake可能就找到问题了

你可以不看 cmake 啊，jpeg 才多少个文件，我搞个 xmake.lua 去 port 下也就 几分钟中时间，就算是新手，自己花点时间 port 也不会折腾多久。。你干嘛要去纠结 cmake 。。有这点时间在这聊，老早用 xmake.lua port 完了。

**Comment by dsp2000** [comment]
jpeg不是全部用c的

**Comment by waruqi** [comment]
asm? add_files("*.S", "*.asm") 有区别么？ 但

**Comment by dsp2000** [comment]
应该有一些指令加速的

**Comment by waruqi** [comment]
这又不影响 port 。

**Comment by waruqi** [comment]
neon 相关 flags 可以参考 https://github.com/xmake-io/xmake-repo/blob/b4cbc0aab630db4933c28ed61ab24745edb6d2d1/packages/f/ffmpeg/xmake.lua#L91-L96

**Comment by dsp2000** [comment]
准备参考这个
https://blog.csdn.net/yuxiatongzhi/article/details/81743249

**Comment by dsp2000** [comment]
这种库，自己处理不了的

**Comment by dsp2000** [comment]
暂时编译不了，过几天找MAC来试。
另外，turbojpeg 编译armeabi-v7a时，会不会你写死了 ndkver的版本？

**Comment by waruqi** [comment]
默认当然会有个版本，不是自己可以 --ndk_sdkver=18 改么。。

**Comment by dsp2000** [comment]
暂时没有时间用mac试编译turbojpeg了。可以先关闭issue 。后面再请教
