### ISSUE TITLE
Fix dependency in manifest.txt

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1460]
### 你在什么场景下需要该功能？

对optional dependency，实际上是否依赖是在编译时就确定的，不应该在require的时候重新从on_load里面找

现在每次走on_load的时候重新确定dependency，会引入实际没有用到的依赖，而且在xrepo clean的时候无法正确判断哪些包是无用的

### 描述可能的解决方案

在manifest.txt里面声明dependency；加载的时候先找manifest.txt确定dependency，找不到再fallback到on_load上

### 目前的解决方案

改用config来控制依赖，但config和optional并不能相互取代，optional具有在编译时确定而非指定的优点。因此这种方案并不好。

**Comment by waruqi** [comment]
> 现在每次走on_load的时候重新确定dependency，会引入实际没有用到的依赖，而且在xrepo clean的时候无法正确判断哪些包是无用的

那是因为 clean 目前没加 --configs 等配置参数，唯一对应上包，像 xrepo info/export --configs/-p/-k 什么的配置都对上来，获取到的依赖原本就是固定的，不会错。。

目前 clean 没加，只是暂时感觉没必要这么精准，大概清理下就行了。。走的模式匹配。。

> 在manifest.txt里面声明dependency；加载的时候先找manifest.txt确定dependency，找不到再fallback到on_load上

没啥意义，获取到对应 buildhash 的 manifest.txt ，其实以及是精准匹配了 configs 才能取到，这个时候跟从 on_load 已经没有本质区别了，结果一样，还增加了复杂性。。

**Comment by xq114** [comment]
> 这个时候跟从 on_load 已经没有本质区别了，结果一样，还增加了复杂性。。

问题就在于on_load获取的依赖是不正确的

考虑package foo对bar是可选依赖
```
package("foo")
add_deps("bar", {optional = true})
```
在一个空机器上先安装foo，再安装bar，此时foo实际上并没有依赖bar，但链接foo的时候会把bar也链接进去；试图移除bar的时候，会提示foo依赖bar而无法移除bar，但实际并没有依赖。这样一来想移除bar就必须重装foo

**Comment by waruqi** [comment]
这种情况是可以再改进下。

**Comment by waruqi** [comment]
> 在一个空机器上先安装foo，再安装bar，此时foo实际上并没有依赖bar，但链接foo的时候会把bar也链接进去；试图移除bar的时候，会提示foo依赖bar而无法移除bar，但实际并没有依赖。这样一来想移除bar就必须重装foo

怎么复现，我尝试这么搞了一遍，bar 还是能够被直接被 `xrepo remove` 移除么，没遇到这个问题。

而且remove的时候，我不记得有加过这个依赖检测机制。贴下提示信息呢。。

另外，这个跟 deps 也没啥关系，是对 optional 的处理问题，即使真的有检测，也应该是改进remove时候对 optional 的处理就行了。。没必要去缓存 deps，这会导致很多其他问题。

**Comment by xq114** [comment]
> 怎么复现，我尝试这么搞了一遍，bar 还是能够被直接被 `xrepo remove` 移除么，没遇到这个问题。
> 
> 而且remove的时候，我不记得有加过这个依赖检测机制。贴下提示信息呢。。
> 
> 另外，这个跟 deps 也没啥关系，是对 optional 的处理问题，即使真的有检测，也应该是改进remove时候对 optional 的处理就行了。。没必要去缓存 deps，这会导致很多其他问题。

那就是我弄错了，那问题就是先安装bar再安装foo，然后卸载bar，这个时候foo依赖bar，卸载bar之后导致找不到bar的符号

总之bar与foo的安装先后顺序很重要，这决定依赖关系是否真实存在，必须在这个点上有所区分

**Comment by waruqi** [comment]
> > 怎么复现，我尝试这么搞了一遍，bar 还是能够被直接被 `xrepo remove` 移除么，没遇到这个问题。
> > 而且remove的时候，我不记得有加过这个依赖检测机制。贴下提示信息呢。。
> > 另外，这个跟 deps 也没啥关系，是对 optional 的处理问题，即使真的有检测，也应该是改进remove时候对 optional 的处理就行了。。没必要去缓存 deps，这会导致很多其他问题。
> 
> 那就是我弄错了，那问题就是先安装bar再安装foo，然后卸载bar，这个时候foo依赖bar，卸载bar之后导致找不到bar的符号
> 
> 总之bar与foo的安装先后顺序很重要，这决定依赖关系是否真实存在，必须在这个点上有所区分

这种情况，即使 manifest 里面缓存了 deps 关系，一样会存在这个问题，bar 装好，再装 foo，这个时候 foo 缓存的 deps 里面是包含 bar 的，再卸载 bar，不管走缓存 deps 还是走 on_load ，deps里面都还是有 bar 的。。但是bar的库已经不在了，同样会有link问题。

另外，optional 只是保证安装失败后，不会中断安装。但是 deps 关系总归会有 bar 的，如果 bar 卸载了，fetch 的时候，bar 的 links 就不会 link 进去，但是 foo 编译的binary还是用了 bar 的符号。。不管怎样都是会出问题的。。改deps是没任何效果的。

**Comment by xq114** [comment]
库已经不在了，依赖不满足的时候xmake应该报错或者重新安装才对，那看起来还需要改更多的逻辑

optional我理解应该是foo的构建系统对bar有自动探测，探测不到的时候就不会链接bar，探测到就链接bar，是否含有bar的符号是在编译时就确定好了的

**Comment by waruqi** [comment]
> 库已经不在了，依赖不满足的时候xmake应该报错或者重新安装才对，那看起来还需要改更多的逻辑

目前编译link就是报错的，目前重新安装只能用户自己控制了，这块自动处理 过于复杂，目前就不动了。

> optional我理解应该是foo的构建系统对bar有自动探测，探测不到的时候就不会链接bar，探测到就链接bar，是否含有bar的符号是在编译时就确定好了的

bar 不存在了，执行 `xmake f -c` 时候，现在就是重新 fetch 重新自动探测，links 里面原本就不会再加 bar 。。但是 foo 的 binary 已经编译好了 带有了 bar 的符号，即使不加 bar link ，最后 link foo 同样会报错。。

除非 bar 存在不存在，走不同的 buildhash ，安装到不同的目录，才能完全区分不干扰，但是 这个 deps 探测已经过于之后了，buildhash 已经固定，这个阶段不能再变了，所以这块不太好弄，短期内 只能用户自己手动卸载 foo 再重装 foo

**Comment by xq114** [comment]
> 除非 bar 存在不存在，走不同的 buildhash ，安装到不同的目录，才能完全区分不干扰，但是 这个 deps 探测已经过于之后了，buildhash 已经固定，这个阶段不能再变了，所以这块不太好弄，短期内 只能用户自己手动卸载 foo 再重装 foo

确实完全自动化不好做。不过现有基础上加一道检查工序还是可以做到的，在fetch foo的时候，检查一下on_load给出的依赖和缓存的依赖是否兼容，不兼容就提前报错，让用户自行解决问题，而不是等到build的时候报符号错误让用户去猜哪个包没装

**Comment by waruqi** [comment]
我改进过了，你可以再试试，foo -> bar (optional) 都安装后，如果卸载 bar ，之后执行 `xmake f -c` 重新检测会自动提示让用户继续安装 bar ，因为之前被安装的 foo 已经包含了 bar。

**Comment by xq114** [comment]
现在是有提示了，但我选n之后还是会正常执行，没有报错信息

**Comment by waruqi** [comment]
再试试呢

**Comment by xq114** [comment]
可以了
