### ISSUE TITLE
Support "Object" target type

### ISSUE THREAD

**Issue by hg-zt** [xmake-io/xmake#1461]
https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#object-libraries

### Describe the solution you'd like

Support Object Target like cmake does.

### Additional context

In most cases, for internal modules, there is actually no need to create static libraries. What we need is just objects and their dependencies.
Static libraries are required only when they need to be published.

More important, static libraries cause problems for C++, since they behave differently from shared libraries for "self registering" code. See examples below:
  - [onqtam/doctest - Why are my tests in a static library not getting registered?](https://github.com/onqtam/doctest/blob/master/doc/markdown/faq.md#why-are-my-tests-in-a-static-library-not-getting-registered)
  - https://github.com/catchorg/Catch2/issues/720
  - https://www.bfilipek.com/2018/02/static-vars-static-lib.html

Workarounds are using compiler-specific flags like `whole-archive` or using Object Targets.

After all, it's not a new idea. We have been using `.o` for Makefile and other old build tools.

See also [Benefits of CMake Object Libraries](https://www.scivision.dev/cmake-object-libraries/)

**Comment by waruqi** [comment]
There is a set_kind("object") type, which was supported a long time ago, but it is rarely used. I'm not sure if it is running now ok

In addition, target("xxx") can be re-entered to add configuration. In most cases, use the object target, and after you re-enter target("xxx") elsewhere, go to add add_files. . There is no essential difference. . Therefore, most needs can be met without object target at all.

**Comment by hg-zt** [comment]
Could you please add it to the document? I thought it's missing because I didn't find it in the doc
https://xmake.io/#/manual/project_target?id=targetset_kind

I tried with a minimal example and it works. Will let you know if I find problems.

**Comment by waruqi** [comment]
> Could you please add it to the document? I thought it's missing because I didn't find it in the doc
> https://xmake.io/#/manual/project_target?id=targetset_kind
> 
> I tried with a minimal example and it works. Will let you know if I find problems.

Because I rarely use it like this, I cannot guarantee that it is stable and reliable, so this type is temporarily not open in my document.
