### ISSUE TITLE
xmake 安装规则不能覆盖

### ISSUE THREAD

**Issue by wujilingfeng** [xmake-io/xmake#1463]
我在xmake.中加入
```lua
rule("markdow")
  on_install (funtion (target)
    os.cp("./temp_libs/libviewer.a", "/usr/lib/") 
  end)
```
然后运行`xmake install --admin` , 仍然运行默认的安装规则。

运行环境:linux xmake-2.5.1,c语言

**Comment by waruqi** [comment]
issue 模板写的提示不看的么。。这种啥也没有  就只有一个 title 的 issues 我是不会处理的。

**Comment by wujilingfeng** [comment]
> issue 模板写的提示不看的么。。这种啥也没有 就只有一个 title 的 issues 我是不会处理的。

对不起，你回复太快了。我已经更新了问题

**Comment by waruqi** [comment]
这只是定义，用 add_rules 对指定  target 生效，具体看文档

**Comment by wujilingfeng** [comment]
> 这只是定义，用 add_rules 对指定 target 生效，具体看文档

我加入
```lua
target("myinstall")
  add_rules("markdown")
```
或者在编译程序的target里加入add_rules("markdown")仍然不起作用

**Comment by waruqi** [comment]
> rule("markdow")
 > add_rules("markdown")

确定你名字 对上了？

**Comment by wujilingfeng** [comment]
> > 这只是定义，用 add_rules 对指定 target 生效，具体看文档
> 
> 感谢。但是当我多次运行xmake install --admin时，xmake会时而运行我的规则，时而运行默认规则

基本上第一次运行我的规则，第二次运行默认规则，3我的规则，4默认规则....

**Comment by waruqi** [comment]
凡事请给详细 log 和复现步骤。我这边测试 ok 没啥问题

**Comment by wujilingfeng** [comment]
> 凡事请给详细 log 和复现步骤或者demo。我这边测试 ok 没啥问题

你测试一下这个项目`git clone https://gitee.com/wujilingfeng/cstructures.git`，很小，无依赖，没有冗余的编译临时文件。

**Comment by waruqi** [comment]
[ 20%]: linking.release myisntall
error: clang: error: no input files

编译都过不了，你搞个空 target 干嘛

```
target("myisntall")
    add_rules("markdown")

```

**Comment by wujilingfeng** [comment]
> [ 20%]: linking.release myisntall
> error: clang: error: no input files
> 
> 编译都过不了，你搞个空 target 干嘛
> 
> ```
> target("myisntall")
>     add_rules("markdown")
> ```

gcc好像可以吧，我不知道在哪里加

**Comment by waruqi** [comment]
给个最精简可复现的demo ，你这个太乱。我懒得看。

**Comment by wujilingfeng** [comment]
> 给个最精简可复现的demo ，你这个太乱。我懒得看。

这个项目能复现我电脑上的问题，它已经足够小了，只编译了一个库和程序

**Comment by waruqi** [comment]
> > 给个最精简可复现的demo ，你这个太乱。我懒得看。
> 
> 这个项目能复现我电脑上的问题，它已经足够小了，只编译了一个库和程序

你只测试 on_install ，又不是测试编译，搞个 main.c 测试下 on_install 不就好了。。on_install 搞个 print 自己验证下

**Comment by wujilingfeng** [comment]
> > > 给个最精简可复现的demo ，你这个太乱。我懒得看。
> > 
> > 
> > 这个项目能复现我电脑上的问题，它已经足够小了，只编译了一个库和程序
> 
> 你只测试 on_install ，又不是测试编译，搞个 main.c 测试下 on_install 不就好了。。on_install 搞个 print 自己验证下

有demo我可以参考么？

**Comment by waruqi** [comment]
> > > > 给个最精简可复现的demo ，你这个太乱。我懒得看。
> > > 
> > > 
> > > 这个项目能复现我电脑上的问题，它已经足够小了，只编译了一个库和程序
> > 
> > 
> > 你只测试 on_install ，又不是测试编译，搞个 main.c 测试下 on_install 不就好了。。on_install 搞个 print 自己验证下
> 
> 有demo我可以参考么？有哪些项目是用xmake构建的，我可以参考一下

xmake create xxx

**Comment by waruqi** [comment]
```lua
rule("xxx")
    on_install(function (target)
        print("xxx")
    end)

target("test")
    set_kind("binary")
    add_files("main.c")
    add_rules("xxx")
```

**Comment by wujilingfeng** [comment]
> > > > > 给个最精简可复现的demo ，你这个太乱。我懒得看。
> > > > 
> > > > 
> > > > 这个项目能复现我电脑上的问题，它已经足够小了，只编译了一个库和程序
> > > 
> > > 
> > > 你只测试 on_install ，又不是测试编译，搞个 main.c 测试下 on_install 不就好了。。on_install 搞个 print 自己验证下
> > 
> > 
> > 有demo我可以参考么？有哪些项目是用xmake构建的，我可以参考一下
> 
> xmake create xxx

运行`xmake create test`,然后把以下代码替换`xmake.lua`
```lua
rule("my")
    on_install(function (target)
        print("zheli")
        os.cp("src/main.cpp","/usr/lib/")
    end)

target("test")
    set_kind("binary")
    add_files("main.c")
    add_rules("my")
```
`xmake install --admin`之后只打印，没有cp(复制)操作，xmake-v2.5.1

**Comment by waruqi** [comment]
？？你都看到打印了，复制不就等于也执行了么

这不都生效了，还有啥问题。。先 确保 复制的文件存在

**Comment by waruqi** [comment]
没进展么？那我先close了。

**Comment by wujilingfeng** [comment]
> ？？你都看到打印了，复制不就等于也执行了么
> 
> 这不都生效了，还有啥问题。。先 确保 复制的文件存在

不好意思，已经解决，是版本问题。
