### ISSUE TITLE
C++ Modules的工具链支持

### ISSUE THREAD

**Issue by SaeruHikari** [xmake-io/xmake#1464]
试用了C++20 Modules，很惊喜可以正常build，但是发现还是有如下一些问题：

- 貌似不能生成module单元的compile_commands
- 生成VS解决方案时不能把.mpp文件添加到工程中

现有状况下，能否为Modules完善这些插件？

**Comment by waruqi** [comment]
见：https://github.com/xmake-io/xmake/issues/1167

目前还没时间改进这块 再等等吧
