### ISSUE TITLE
debug时指定环境变量和工作目录？

### ISSUE THREAD

**Issue by pingsoli** [xmake-io/xmake#1469]
### 描述讨论详情
linux下，xmake r -d target，默认会使用gdb调试target，但是target需要依赖其他库，需要指定指定工作目录。我目前的做法是使用脚本：

```shell
my_out_exe=$PWD/../bin/linux/debug/my_exe_server

cd /home/test/project/server
export LD_LIBRARY_PATH=$PWD/../third_party

my_exe_server "$@"
```

**Comment by waruqi** [comment]
set_rundir
set_runenv
add_runenvs
xmake r -w workdir
...

具体看文档
