### ISSUE TITLE
xmake 安装 spdlog 报failed 

### ISSUE THREAD

**Issue by hucxian** [xmake-io/xmake#1475]
### 描述问题

xmake 安装 spdlog 报failed 

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 错误信息

[hucx@localhost ~]$ xmake f -vD -c
checking for platform ... linux
checking for architecture ... x86_64
checking for gcc ... /opt/rh/devtoolset-7/root/usr/bin/gcc
checkinfo: runv(dmd --version) failed(127)
checking for dmd ... no
checkinfo: runv(ldc2 --version) failed(127)
checking for ldc2 ... no
checkinfo: runv(gdc --version) failed(127)
checking for gdc ... no
checkinfo: runv(zig version) failed(127)
checking for zig ... no
checkinfo: runv(zig version) failed(127)
checking for zig ... no
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
finding fmt from xmake ..
checking for xmake::fmt ... fmt 8.0.0
finding spdlog from xmake ..
checking for xmake::spdlog ... no
note: try installing these packages (pass -y to skip confirm)?
in xmake-repo:
  -> spdlog v1.8.0 [fmt_external:y, header_only:y, vs_runtime:MD]
please input: y (y/n)
y
checking for ping ... /usr/bin/ping
pinging for the host(github.com) ... 65535 ms
/usr/bin/unzip -o v1.8.0.zip -d source.tmp
Archive:  v1.8.0.zip
4a9ccf7e38e257feecce0c579a782741254eaeef
   creating: source.tmp/spdlog-1.8.0/
  inflating: source.tmp/spdlog-1.8.0/.clang-format  
  inflating: source.tmp/spdlog-1.8.0/.clang-tidy  
 extracting: source.tmp/spdlog-1.8.0/.gitattributes  
  inflating: source.tmp/spdlog-1.8.0/.gitignore  
  inflating: source.tmp/spdlog-1.8.0/.travis.yml  
  inflating: source.tmp/spdlog-1.8.0/CMakeLists.txt  
  inflating: source.tmp/spdlog-1.8.0/INSTALL  
  inflating: source.tmp/spdlog-1.8.0/LICENSE  
  inflating: source.tmp/spdlog-1.8.0/README.md  
  inflating: source.tmp/spdlog-1.8.0/appveyor.yml  
   creating: source.tmp/spdlog-1.8.0/bench/
  inflating: source.tmp/spdlog-1.8.0/bench/CMakeLists.txt  
  inflating: source.tmp/spdlog-1.8.0/bench/async_bench.cpp  
  inflating: source.tmp/spdlog-1.8.0/bench/bench.cpp  
  inflating: source.tmp/spdlog-1.8.0/bench/formatter-bench.cpp  
  inflating: source.tmp/spdlog-1.8.0/bench/latency.cpp  
  inflating: source.tmp/spdlog-1.8.0/bench/utils.h  
   creating: source.tmp/spdlog-1.8.0/cmake/
  inflating: source.tmp/spdlog-1.8.0/cmake/ide.cmake  
  inflating: source.tmp/spdlog-1.8.0/cmake/pch.h.in  
  inflating: source.tmp/spdlog-1.8.0/cmake/spdlog.pc.in  
  inflating: source.tmp/spdlog-1.8.0/cmake/spdlogCPack.cmake  
  inflating: source.tmp/spdlog-1.8.0/cmake/spdlogConfig.cmake.in  
  inflating: source.tmp/spdlog-1.8.0/cmake/utils.cmake  
  inflating: source.tmp/spdlog-1.8.0/cmake/version.rc.in  
   creating: source.tmp/spdlog-1.8.0/example/
  inflating: source.tmp/spdlog-1.8.0/example/CMakeLists.txt  
  inflating: source.tmp/spdlog-1.8.0/example/example.cpp  
   creating: source.tmp/spdlog-1.8.0/include/
   creating: source.tmp/spdlog-1.8.0/include/spdlog/
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/async.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/async_logger-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/async_logger.h  
   creating: source.tmp/spdlog-1.8.0/include/spdlog/cfg/
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/cfg/argv.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/cfg/env.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/cfg/helpers-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/cfg/helpers.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/cfg/log_levels.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/common-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/common.h  
   creating: source.tmp/spdlog-1.8.0/include/spdlog/details/
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/backtracer-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/backtracer.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/circular_q.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/console_globals.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/file_helper-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/file_helper.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/fmt_helper.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/log_msg-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/log_msg.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/log_msg_buffer-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/log_msg_buffer.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/mpmc_blocking_q.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/null_mutex.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/os-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/os.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/periodic_worker-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/periodic_worker.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/registry-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/registry.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/synchronous_factory.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/tcp_client-windows.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/tcp_client.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/thread_pool-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/thread_pool.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/details/windows_include.h  
   creating: source.tmp/spdlog-1.8.0/include/spdlog/fmt/
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/fmt/bin_to_hex.h  
   creating: source.tmp/spdlog-1.8.0/include/spdlog/fmt/bundled/
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/fmt/bundled/LICENSE.rst  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/fmt/bundled/chrono.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/fmt/bundled/color.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/fmt/bundled/compile.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/fmt/bundled/core.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/fmt/bundled/format-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/fmt/bundled/format.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/fmt/bundled/locale.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/fmt/bundled/os.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/fmt/bundled/ostream.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/fmt/bundled/posix.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/fmt/bundled/printf.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/fmt/bundled/ranges.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/fmt/chrono.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/fmt/fmt.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/fmt/ostr.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/formatter.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/fwd.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/logger-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/logger.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/pattern_formatter-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/pattern_formatter.h  
   creating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/android_sink.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/ansicolor_sink-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/ansicolor_sink.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/base_sink-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/base_sink.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/basic_file_sink-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/basic_file_sink.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/daily_file_sink.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/dist_sink.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/dup_filter_sink.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/msvc_sink.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/null_sink.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/ostream_sink.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/ringbuffer_sink.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/rotating_file_sink-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/rotating_file_sink.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/sink-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/sink.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/stdout_color_sinks-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/stdout_color_sinks.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/stdout_sinks-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/stdout_sinks.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/syslog_sink.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/systemd_sink.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/tcp_sink.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/win_eventlog_sink.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/wincolor_sink-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/sinks/wincolor_sink.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/spdlog-inl.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/spdlog.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/stopwatch.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/tweakme.h  
  inflating: source.tmp/spdlog-1.8.0/include/spdlog/version.h  
   creating: source.tmp/spdlog-1.8.0/logos/
  inflating: source.tmp/spdlog-1.8.0/logos/jetbrains-variant-4.svg  
   creating: source.tmp/spdlog-1.8.0/scripts/
  inflating: source.tmp/spdlog-1.8.0/scripts/extract_version.py  
  inflating: source.tmp/spdlog-1.8.0/scripts/format.sh  
   creating: source.tmp/spdlog-1.8.0/src/
  inflating: source.tmp/spdlog-1.8.0/src/async.cpp  
  inflating: source.tmp/spdlog-1.8.0/src/cfg.cpp  
  inflating: source.tmp/spdlog-1.8.0/src/color_sinks.cpp  
  inflating: source.tmp/spdlog-1.8.0/src/file_sinks.cpp  
  inflating: source.tmp/spdlog-1.8.0/src/fmt.cpp  
  inflating: source.tmp/spdlog-1.8.0/src/spdlog.cpp  
  inflating: source.tmp/spdlog-1.8.0/src/stdout_sinks.cpp  
   creating: source.tmp/spdlog-1.8.0/tests/
  inflating: source.tmp/spdlog-1.8.0/tests/CMakeLists.txt  
  inflating: source.tmp/spdlog-1.8.0/tests/catch.hpp  
  inflating: source.tmp/spdlog-1.8.0/tests/catch.license  
  inflating: source.tmp/spdlog-1.8.0/tests/includes.h  
 extracting: source.tmp/spdlog-1.8.0/tests/main.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/test_async.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/test_backtrace.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/test_cfg.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/test_create_dir.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/test_daily_logger.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/test_dup_filter.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/test_errors.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/test_eventlog.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/test_file_helper.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/test_file_logging.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/test_fmt_helper.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/test_macros.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/test_misc.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/test_mpmc_q.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/test_pattern_formatter.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/test_registry.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/test_sink.h  
  inflating: source.tmp/spdlog-1.8.0/tests/test_stdout_api.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/test_stopwatch.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/test_systemd.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/test_time_point.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/utils.cpp  
  inflating: source.tmp/spdlog-1.8.0/tests/utils.h  
finding spdlog from xmake ..
checking for xmake::spdlog ... spdlog v1.8.0
{ 
  sysincludedirs = { 
    "/home/hucx/.xmake/packages/s/spdlog/v1.8.0/70ed215d9485427a9718d60235da72a3/include" 
  },
  defines = "SPDLOG_FMT_EXTERNAL" 
}

patching /home/hucx/.xmake/packages/s/spdlog/v1.8.0/70ed215d9485427a9718d60235da72a3/lib/pkgconfig/spdlog.pc ..
checking for gcc ... /opt/rh/devtoolset-7/root/usr/bin/gcc
checking for the c++ compiler (cxx) ... gcc
checkinfo: runv(ccache --version) failed(127)
checking for ccache ... no
> /opt/rh/devtoolset-7/root/usr/bin/gcc -c -m64 -std=c++11 -DSPDLOG_FMT_EXTERNAL -DFMT_HEADER_ONLY=1 -isystem /home/hucx/.xmake/packages/s/spdlog/v1.8.0/70ed215d9485427a9718d60235da72a3/include -isystem /home/hucx/.xmake/packages/f/fmt/8.0.0/a40c937b2fbe4bf8ad2ec84f2c9f19ca/include -o /dev/shm/.xmake1000/210628/_8C388D8336EA4D30854AC4EAFCF70770.o /dev/shm/.xmake1000/210628/_A12ACC4A000B4A008B32A1BD65EF8920.cpp
checking for /opt/rh/devtoolset-7/root/usr/bin/gcc ... ok
checking for flags (-fdiagnostics-color=always) ... ok
> gcc "-fdiagnostics-color=always"
> checking for c++ includes(spdlog/spdlog.h)
> checking for c++ funcs(spdlog::info)
> checking for c++ snippet(has_cxxfuncs)
checkinfo: ...xmake/core/sandbox/modules/import/core/tool/compiler.lua:84: ./.local/share/xmake/modules/core/tools/gcc.lua:481: In file included from /home/hucx/.xmake/packages/s/spdlog/v1.8.0/70ed215d9485427a9718d60235da72a3/include/spdlog/common.h:245:0,
                 from /home/hucx/.xmake/packages/s/spdlog/v1.8.0/70ed215d9485427a9718d60235da72a3/include/spdlog/spdlog.h:12,
                 from /dev/shm/.xmake1000/210628/_A12ACC4A000B4A008B32A1BD65EF8920.cpp:2:
/home/hucx/.xmake/packages/s/spdlog/v1.8.0/70ed215d9485427a9718d60235da72a3/include/spdlog/common-inl.h: In constructor ‘spdlog::spdlog_ex::spdlog_ex(const string&, int)’:
/home/hucx/.xmake/packages/s/spdlog/v1.8.0/70ed215d9485427a9718d60235da72a3/include/spdlog/common-inl.h:57:53: error: cannot convert ‘const string {aka const std::basic_string<char>}’ to ‘const char*’ for argument ‘3’ to ‘void fmt::v7::format_system_error(fmt::v7::detail::buffer<char>&, int, const char*)’
     fmt::format_system_error(outbuf, last_errno, msg);
                                                     ^
stack traceback:
    [C]: in function 'error'
    [./.local/share/xmake/core/base/os.lua:800]: in function 'raise'
    [./.local/share/xmake/modules/core/tools/gcc.lua:481]: in function 'catch'
    [./.local/share/xmake/core/sandbox/modules/try.lua:127]: in function 'try'
    [./.local/share/xmake/modules/core/tools/gcc.lua:430]:
    [C]: in function 'compile'
    [...xmake/core/sandbox/modules/import/core/tool/compiler.lua:82]: in function 'compile'
    [...ocal/share/xmake/modules/lib/detect/check_cxsnippets.lua:198]:
    [C]: in function 'trycall'
    [./.local/share/xmake/core/sandbox/modules/try.lua:121]: in function 'try'
    [...ocal/share/xmake/modules/lib/detect/check_cxsnippets.lua:193]: in function 'has_cxxfuncs'
    [...make/repositories/xmake-repo/packages/s/spdlog/xmake.lua:55]: in function 'script'
    [...ake/modules/private/action/require/impl/utils/filter.lua:125]: in function 'call'
    [...ake/modules/private/action/require/impl/actions/test.lua:41]: in function 'test'
    [.../modules/private/action/require/impl/actions/install.lua:203]:
    [C]: in function 'trycall'
    [./.local/share/xmake/core/sandbox/modules/try.lua:121]: in function 'try'
    [.../modules/private/action/require/impl/actions/install.lua:137]: in function 'action_install'
    [...modules/private/action/require/impl/install_packages.lua:212]: in function 'jobfunc'
    [./.local/share/xmake/modules/private/async/runjobs.lua:193]:
    [C]: in function 'trycall'
    [./.local/share/xmake/core/sandbox/modules/try.lua:121]: in function 'try'
    [./.local/share/xmake/modules/private/async/runjobs.lua:186]: in function 'cotask'
    [./.local/share/xmake/core/base/scheduler.lua:365]:

error: ...make/repositories/xmake-repo/packages/s/spdlog/xmake.lua:55: assertion failed!
stack traceback:
    [C]: in function 'error'
    [./.local/share/xmake/core/base/os.lua:800]: in function 'raiselevel'
    [./.local/share/xmake/core/sandbox/modules/utils.lua:183]: in function 'assert'
    [...make/repositories/xmake-repo/packages/s/spdlog/xmake.lua:55]: in function 'script'
    [...ake/modules/private/action/require/impl/utils/filter.lua:125]: in function 'call'
    [...ake/modules/private/action/require/impl/actions/test.lua:41]: in function 'test'
    [.../modules/private/action/require/impl/actions/install.lua:203]:
    [C]: in function 'trycall'
    [./.local/share/xmake/core/sandbox/modules/try.lua:121]: in function 'try'
    [.../modules/private/action/require/impl/actions/install.lua:137]: in function 'action_install'
    [...modules/private/action/require/impl/install_packages.lua:212]: in function 'jobfunc'
    [./.local/share/xmake/modules/private/async/runjobs.lua:193]:
    [C]: in function 'trycall'
    [./.local/share/xmake/core/sandbox/modules/try.lua:121]: in function 'try'
    [./.local/share/xmake/modules/private/async/runjobs.lua:186]: in function 'cotask'
    [./.local/share/xmake/core/base/scheduler.lua:365]:

  => install spdlog v1.8.0 .. failed
error: ./.local/share/xmake/modules/private/async/runjobs.lua:217: .../modules/private/action/require/impl/actions/install.lua:253: install failed!
stack traceback:
    [C]: in function 'error'
    [./.local/share/xmake/core/base/os.lua:800]: in function 'raise'
    [.../modules/private/action/require/impl/actions/install.lua:253]: in function 'catch'
    [./.local/share/xmake/core/sandbox/modules/try.lua:127]: in function 'try'
    [.../modules/private/action/require/impl/actions/install.lua:137]: in function 'action_install'
    [...modules/private/action/require/impl/install_packages.lua:212]: in function 'jobfunc'
    [./.local/share/xmake/modules/private/async/runjobs.lua:193]:
    [C]: in function 'trycall'
    [./.local/share/xmake/core/sandbox/modules/try.lua:121]: in function 'try'
    [./.local/share/xmake/modules/private/async/runjobs.lua:186]: in function 'cotask'
    [./.local/share/xmake/core/base/scheduler.lua:365]:

stack traceback:
        [C]: in function 'error'
        ./.local/share/xmake/core/base/os.lua:800: in function 'raise'
        ./.local/share/xmake/modules/private/async/runjobs.lua:217: in function 'catch'
        ./.local/share/xmake/core/sandbox/modules/try.lua:127: in function 'try'
        ./.local/share/xmake/modules/private/async/runjobs.lua:186: in function 'cotask'
        ./.local/share/xmake/core/base/scheduler.lua:365: in function <./.local/share/xmake/core/base/scheduler.lua:362>

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.2
- xmake运行平台：centos7
- xmake目标平台：

### 其他信息

[hucx@localhost ~]$ cat xmake.lua 
add_plugindirs("./xmake_plugins")

add_requires("fmt", {system=false, configs = {header_only = true, vs_runtime = "MD"}})
add_requires("spdlog 1.8.0", {system=false, configs = {header_only = true, fmt_external=true, vs_runtime = "MD"}})

**Comment by waruqi** [comment]
> /home/hucx/.xmake/packages/s/spdlog/v1.8.0/70ed215d9485427a9718d60235da72a3/include/spdlog/common-inl.h:57:53: error: cannot convert ‘const string {aka const std::basic_string}’ to ‘const char*’ for argument ‘3’ to ‘void fmt::v7::format_system_error(fmt::v7::detail::buffer&, int, const char*)’
fmt::format_system_error(outbuf, last_errno, msg);

测试 spdlog 包的时候，测试阶段报错了，但是我这边本地测试可以。。是不是编译器版本的问题。你这版本多少，看下 版本是不是过低

**Comment by hucxian** [comment]
[hucx@localhost ~]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-7/root/usr --mandir=/opt/rh/devtoolset-7/root/usr/share/man --infodir=/opt/rh/devtoolset-7/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --with-default-libstdcxx-abi=gcc4-compatible --with-isl=/builddir/build/BUILD/gcc-7.3.1-20180303/obj-x86_64-redhat-linux/isl-install --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)

**Comment by waruqi** [comment]
> /home/hucx/.xmake/packages/s/spdlog/v1.8.0/70ed215d9485427a9718d60235da72a3/include/spdlog/common-inl.h:57:53: error: cannot convert ‘const string {aka const std::basic_string}’ to ‘const char*’ for argument ‘3’ to ‘void fmt::v7::format_system_error(fmt::v7::detail::buffer&, int, const char*)’
fmt::format_system_error(outbuf, last_errno, msg);
^

我这边本地测试，和 ci 都ok，但是你咋安装包测试失败了，像是你这的 fmt 和 spdlog 版本不兼容

**Comment by waruqi** [comment]
你看下这个库的错误信息，对下common-inl.h:57 里面   和你这边的 fmt 库是否兼容，

**Comment by hucxian** [comment]
确实库不兼容
