### ISSUE TITLE
编译动态库时gcc ld不能切换

### ISSUE THREAD

**Issue by as564335sa** [xmake-io/xmake#1477]
如图：
![QQ图片20210630134339](https://user-images.githubusercontent.com/35949162/123907944-47121580-d9a9-11eb-8449-f1fbc3323cdc.png)
在`set_kind("shared")`后，切换ld总是失败，`set_toolset("ld","mipsel-openwrt-linux-gcc")`
链接使用的还是g++

但是这样设置编译binary和static就正常

**Comment by waruqi** [comment]
动态库是 sh 不是 ld ，xmake 里面单独 分开了

**Comment by as564335sa** [comment]
好了，谢谢
