### ISSUE TITLE
建议在编译结束后显示编译耗时

### ISSUE THREAD

**Issue by zwxf** [xmake-io/xmake#1478]
例如rust这种编译后显示编译时间，如下图这种。
![3G9PA7H$ DI (@%S8A%1LK8](https://user-images.githubusercontent.com/15979360/123923911-08398b00-d9bc-11eb-8afc-7e6c496981ca.png)

**Comment by waruqi** [comment]
自己加个 time 不就完事了。。这种特殊需求，没必要内置弄，满足不了所有用户，到时候再来个用户提 issues 说去掉 耗时显示，岂不是很蛋疼。

```console
$ time xmake
[100%]: build ok!

real    0m0.400s
user    0m0.091s
sys     0m0.302s
```
