### ISSUE TITLE
编译模式似乎不起作用

### ISSUE THREAD

**Issue by dicarne** [xmake-io/xmake#1479]
### Describe the bug
根据官方文档，尝试切换到debug模式，但始终编译成release模式。
在`xmake.lua`顶部声明了`add_rules("mode.release", "mode.debug") `，在target内`print(is_mode("debug"))`，尝试看看现在是什么模式，但是输出令人困惑：
![image](https://user-images.githubusercontent.com/10357789/123956474-4eebad00-d9dd-11eb-97dc-8ae65d28a3a0.png)
看起来mode是debug。但实际编译时又不一样了：
![image](https://user-images.githubusercontent.com/10357789/123956619-76427a00-d9dd-11eb-8cad-908e1730bb86.png)
按照输出所述，还是编译出了release的东西。
清理缓存文件等操作并没有帮助。
根据[文档](https://xmake.io/#/zh-cn/manual/custom_rule?id=modedebug)，似乎并没有说还要做什么特殊的操作，是我哪里操作不对吗？

### Expected behavior
使用`xmake f -m debug`和`xmake`后，生成debug模式的文件。

### Related Environment

Please provide compiling and running environment information:

- xmake version: xmake v2.5.4+202106301541
- os: ubuntu 20.04 LS
- target platform: linux/x86_64

**Comment by waruqi** [comment]
> 在target内print(is_mode("debug"))，尝试看看现在是什么模式，但是输出令人困惑：

这个可以先看下文档对描述域的说明，尽量不要在描述域做复杂的脚本和 print，仅仅用于配置，print 什么的都会被执行多次，打印出来的结果没啥意义

https://xmake.io/#/zh-cn/guide/syntax_description

> 根据官方文档，尝试切换到debug模式，但始终编译成release模式。

我这里可以

![image](https://user-images.githubusercontent.com/151335/123964924-8ca10380-d9e6-11eb-9903-63fa31b01a9d.png)

**Comment by dicarne** [comment]
后来我新建了一个project，是可以正常运行的，那么问题是我之前的为啥不能切换呢？
以下是我的两个工程的xmake.lua，感觉除了一些依赖，没什么特别的啊？
![image](https://user-images.githubusercontent.com/10357789/123973787-a6464900-d9ee-11eb-9e65-32195d5b50bb.png)
左边的不能切换，右边的能切换，并且我尝试清空缓存或者.xmake，都没有改善。如果有人能解答，万分感谢

**Comment by waruqi** [comment]
不知道，理论上肯定可以，从来没人遇到过不能切的，执行下 xmake f -m debug -c 试试

**Comment by dicarne** [comment]
确实，我用vscode打开.xmake/xmake.conf，能切换的项目明显在输入命令后重写了这个文件，然而不能切换的项目这个文件根本没变
