### ISSUE TITLE
Compile xmake with system libs?

### ISSUE THREAD

**Issue by Phate6660** [xmake-io/xmake#1482]
### Is your feature request related to a problem? Please describe.
From what I can tell it'll compile things like luajit directly from the source tree.
That's extra time compiling waiting for those things when a
system lib could be used if available instead.
While I understand the way it is currently is a quick and simple process, I
think it would be quite beneficial to at least be able to have it use system
libs, even if it's not some sort of default option.

### Describe the solution you'd like
Some way to specify using system libs while building xmake.

----

Plus it just feels really odd to have a dependency-less ebuild for xmake,
especially knowing that it has dependencies but I can't actually specify them
in the ebuild.

**Comment by waruqi** [comment]
xmake will detect and use system libs.

https://github.com/xmake-io/xmake/blob/c44d6060e82fc332e0f7370398bcbbaed7278543/core/makefile#L284

make LUAJIT_SYSTEM=y

but it is only tested on ubuntu.

**Comment by Phate6660** [comment]
Sorry for the late reply :sweat_smile:

It seems to fail building with system luajit:
```
make[3]: *** [/var/tmp/portage/dev-util/xmake-2.5.5/work/core/suffix.mak:309: demo.b] Error 1
make[2]: *** [/var/tmp/portage/dev-util/xmake-2.5.5/work/core/suffix.mak:309: SUB_PROS_demo_all] Error 2
/usr/lib/gcc/x86_64-gentoo-linux-musl/10.3.0/../../../../x86_64-gentoo-linux-musl/bin/ld: ../lua-cjson/liblua-cjsonr.a(lua_cjson.o): in function `lua_cjson_new':
lua_cjson.c:(.text+0x574): undefined reference to `luaL_setfuncs'
```
I assume it's failing to find the luajit libs?

Though the output of `pkg-config --libs --cflags luajit` is:
`-I/usr/include/luajit-2.0 -lluajit-5.1`

On the same note of system libs, can anything else be built with system libs besides luajit?

Also, what's up with this?
`luajit_JIT :=$(shell if [ -f "/etc/redhat-release" ]; then echo "nojit"; else echo "jit"; fi )`

How does having RedHat's OS info file equate to having luajit?

**Comment by waruqi** [comment]
> luajit_JIT :=$(shell if [ -f "/etc/redhat-release" ]; then echo "nojit"; else echo "jit"; fi )

I remember that rhel/centos only supports luajit with interpreter mode, and jit execution cannot be enabled, otherwise it will fail.
