### ISSUE TITLE
Load environment variable from dependencies besides msvc

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1483]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

https://github.com/xmake-io/xmake-repo/pull/463

这里给cmake加载了msvc，但丢失了nasm等依赖的环境变量，情况类似于package.tools.nmake/package.tools.meson，见https://github.com/xq114/xmake-repo/actions/runs/992556214

更进一步，如果提供一个os.joinenv的接口则更好，可在package内更方便地修改环境变量

**Comment by waruqi** [comment]
加了个 os.joinenvs(envs, oldenvs)  如果 oldenvs 为 nil，默认用  os.getenvs()

另外 tools/gn, cmake, nmake, msbuild, meson 里面的 envs 我都更新过了。。

等 ci 上过了再试试

**Comment by xq114** [comment]
环境变量的问题解决了；另一个问题是走cmake->msbuild路线的时候无法指定是否并行

https://github.com/xmake-io/xmake/blob/60db2397f832af73b7cf72177c11ef57e9f80b6a/xmake/modules/package/tools/cmake.lua#L520-L527

open3d里面不支持ninja只支持msbuild，并且要求cmake后的msbuild必须串行不能并行，能否加一个指令指定是否开启并行（`-m`）？

**Comment by waruqi** [comment]
那你帮忙开个pr直接改下就好了，也就几行代码。我可能要明晚才有时间了
