### ISSUE TITLE
从qmake迁移至xmake，使用includes包含子项目，link出错，error LNK2001: 无法解析的外部符号

### ISSUE THREAD

**Issue by hh-wu** [xmake-io/xmake#1500]
### 描述问题

最近我在迁移一个qmake的项目到xmake上，按照pro文件的格式对照着写了xmake.lua文件。可以编译的几个静态库都没有问题，可惜中间有个target为console的程序link出错。

项目是开源项目，地址为：https://github.com/hh-wu/range_xmake.git

请帮我看看是什么问题，我感觉是moc文件之类的出问题了，但是不知道从何下手。

### 期待的结果

编译成功。

### 错误信息

使用`xmake -rvD > make.log'获得的文件。
[xmake log.zip](https://github.com/xmake-io/xmake/files/6790437/make.zip)

### 相关环境

- xmake版本：xmake v2.5.5+202107060515
- xmake运行平台：Edition	Windows 10 Home
Version	20H2
Installed on	‎2/‎27/‎2021
OS build	19042.1083
Experience	Windows Feature Experience Pack 120.2212.3530.0

- xmake目标平台：Edition	Windows 10 Home
Version	20H2
Installed on	‎2/‎27/‎2021
OS build	19042.1083
Experience	Windows Feature Experience Pack 120.2212.3530.0

### 其他信息

请提供关键的 xmake.lua 配置内容，或者完整 xmake.lua，也可以是其他附加信息帮助我们诊断问题(比如截图，xmake.lua或者可复现的demo)，以及你遇到的问题的一些背景信息。

**Comment by xq114** [comment]
qt必须把头文件也作为源文件：
```
add_files("*.h", "*.cpp")
add_headerfiles("*.h")
```

**Comment by hh-wu** [comment]
> qt必须把头文件也作为源文件：
> 
> ```
> add_files("*.h", "*.cpp")
> add_headerfiles("*.h")
> ```

感谢，LNK2001问题解决

**Comment by waruqi** [comment]
> qt必须把头文件也作为源文件：
> 
> ```
> add_files("*.h", "*.cpp")
> add_headerfiles("*.h")
> ```

仅仅带 moc 的 header 需要
