### ISSUE TITLE
Support nested project

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1505]
### 你在什么场景下需要该功能？

一个项目由三个子项目a b c构成，其中a生成一个可执行文件a.exe，b用到a.exe生成的源文件，c用到可执行文件b生成的源文件

### 描述可能的解决方案

```
target("a")
	...
	after_build(function (target)
		os.vrunv(target:targetfile(), {"-o", val("projectdir")})
	end)

target("b")
	add_deps("a")
	add_files("$(projectdir)/a_generated.cpp", {delayed = true})
	...
```

### 描述你认为的候选方案

更一般地，a/b/c都由多个target组成，可以分开成几个project

```
-- a.lua
set_project("a", {subproject = true})
...

-- b.lua
set_project("b", {subproject = true})
...

-- xmake.lua
set_project("whole")
add_subprojects("a", "b") -- independently run xmake for a first, then for b

```

这样缺点在每个subproject都有自己的cache和build位置，不好统一

### 其他信息

用rule不太好实现这个功能，rule的抽象模型是用第三方编译器把某种文件转化成源文件，但这里的“编译器”本身也是xmake项目的一部分

**Comment by waruqi** [comment]
用 rule 一样可以做，先 add_deps 依赖构建编译生成 target a，然后 target b 依赖 a

再额外搞个 rule 去 运行 a 生成 cpp 然后参与编译

参考 https://github.com/xmake-io/xmake-repo/blob/5f43095bb91fffacbe2e2e36a6cea30a168871af/packages/l/luajit/port/xmake.lua#L199

luajit里面就是，先编译 host buildvm .程序，然后生成 一些文件参与最终编译

**Comment by xq114** [comment]
确实可以，如果能在文档里加入这一部分就更好了
