### ISSUE TITLE
Makefile generation: circular dependency when targetdir is "."

### ISSUE THREAD

**Issue by norech** [xmake-io/xmake#1509]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
The issue happen when a makefile is generated by `xmake project -k make`.

When `set_targetdir(".")` is called, the generated makefile is incorrect and make will warn about a "circular dependency" issue.

### Expected behavior
Make should not show an error.

### Error output
When calling `make`
```
make: Circular sampletarget <- sampletarget dependency dropped.
```

### Related Environment
Please provide compiling and running environment information:

- xmake version: 2.5.5
- os: Fedora Linux
- target platform: -

### Additional context
The faulty `xmake.lua`:

```
target("sampletarget")
    set_kind("binary")
    set_targetdir(".")  -- targetdir is .
    add_files("*.c")
```

**Comment by waruqi** [comment]
Thank you very much for your contribution. 👍
