### ISSUE TITLE
xmake 日志显示异常

### ISSUE THREAD

**Issue by Heafei** [xmake-io/xmake#1511]
### 描述问题
应该是跟我的cmd设置有关系。图中部分log的颜色能正常显示，部分的则是显示色彩控制字符原文。
![image](https://user-images.githubusercontent.com/13373703/125406603-96196b00-e3eb-11eb-91cb-107cc1c6b4c7.png)

### 期待的结果

期待正常的带颜色的log

**Comment by waruqi** [comment]
见：https://github.com/xmake-io/xmake/issues/1501

**Comment by Heafei** [comment]
> 见：#1501
已经修复了。
