### ISSUE TITLE
Improve precompiled binary package compatibility on windows/msvc

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#1513]
### issue1

vs2017

https://github.com/xmake-io/xmake-repo/issues/496

> opencv_core452.lib(parallel.cpp.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4

### issue2

vs2013

https://ci.appveyor.com/project/waruqi/xmake/builds/39973970

> png.lib(pngerror.c.obj) : error LNK2019: unresolved external symbol __imp___acrt_iob_func referenced in function png_warning
png.lib(pngerror.c.obj) : error LNK2019: unresolved external symbol __imp___stdio_common_vfprintf referenced in function _vfprintf_l
C:\Users\appveyor\AppData\Local\Temp\1\.xmake\210713\_E361ED7D2D2D413086531D03EFBCE430.b : fatal error LNK1120: 2 unresolved externals

**Comment by waruqi** [comment]
https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-160

**Comment by xq114** [comment]
so it's just backwards compatible

**Comment by waruqi** [comment]
ok, I only need to use vs2015 to compile all libraries, and only support pre-compiled binaries for compilers above 2015?

**Comment by xq114** [comment]
> ok, I only need to use vs2015 to compile all libraries, and only support pre-compiled binaries for compilers above 2015?

If it's applicable it would be good the precompiled binary from the latest visual studio is provided besides the compatibility version, since better performance could be gained with a more recent compiler

**Comment by waruqi** [comment]
> > ok, I only need to use vs2015 to compile all libraries, and only support pre-compiled binaries for compilers above 2015?
> 
> If it's applicable it would be good the precompiled binary from the latest visual studio is provided besides the compatibility version, since better performance could be gained with a more recent compiler

will do

Will do this, and I think it should be better to identify based on the toolset version instead of the vs version.

**Comment by waruqi** [comment]
In addition, I don’t know if github action has native support for switching msvc toolset, but I saw this

https://github.com/ilammy/msvc-dev-cmd

**Comment by xq114** [comment]
https://github.com/actions/virtual-environments/issues/387

GitHub Actions is not plan to support VS2015 any more. It would be better switch to AppVeyor or some other ci platform.

**Comment by waruqi** [comment]
> [actions/virtual-environments#387](https://github.com/actions/virtual-environments/issues/387)
> 
> GitHub Actions is not plan to support VS2015 any more. It would be better switch to AppVeyor or some other ci platform.

I saw that github ci has vs2015 and vs2019, I will switch to 2015 later

**Comment by waruqi** [comment]
> [actions/virtual-environments#387](https://github.com/actions/virtual-environments/issues/387)
> 
> GitHub Actions is not plan to support VS2015 any more. It would be better switch to AppVeyor or some other ci platform.

The free plan of other ci does not support parallel compilation and will be very slow.

**Comment by waruqi** [comment]
GitHub ci has vs2015 but there is no corresponding msbuild/v140 configuration path. ohmm..

**Comment by waruqi** [comment]
Maybe at present I can only limit to >= vs2019 to support pre-compiled packages

**Comment by waruqi** [comment]
But I see that the toolset version in vs2019 used on the github action is 14.29, which means that as long as the user's compiler toolset >=14.2, it should be compatible.

Maybe some users' VS2017 toolset can also match this requirement.

**Comment by waruqi** [comment]
I have improved xmake dev, and only enable pre-compiled installation for toolset >= 14.29 on ci

The pre-compilation service has also been adjusted, version 2.5.5 can only temporarily disable the new pre-compiled package, and wait for the subsequent xmake release

In addition, dynamic libraries and executable packages are not affected by toolset

**Comment by waruqi** [comment]
Now, I have added v14.16 toolset pre-compiled package support, which can support compilers above vs2017.

- [x] 14.16 (vs2017 on windows-2016)
- [x] 14.29  (vs2019 on windows-latest)

If the user has a higher version compilation, the 14.29 toolset package will be selected first.
