### ISSUE TITLE
Build error on macOS Catalina with tbox

### ISSUE THREAD

**Issue by aacirino** [xmake-io/xmake#1514]
I cloned the repository and have already successfully built earlier versions of xmake in my macOS 10.17.5 Catalina MacBook. I have installed tbox and luajit using brew and am invoking make with the following options:

`make CCACHE=/usr/local/bin/ccache tbox=n luajit=n`

make then shows that the option were valid:
```compiling xmake-core ...

=============================================================================
compile:
    plat:		macosx
    arch:		x86_64
    host:		macosx
    demo:		y
    prof:		n
    debug:		n
    small:		n
    ccache:		/usr/local/bin/ccache
    distcc:
    luajit:		jit

packages:
    tbox:		n
    luajit:		n
    base:		y
```
but tbox and luajit will still be built and tbox build is aborted with these errors:
```
/usr/local/bin/ccache compile.r process/open.c
make[3]: *** [process/open.o] Error 1
make[2]: *** [DEP_PROS_xmake_all] Error 2
process/open.c:203:14: error: no member named 'in' in 'struct __tb_process_attr_t'
        attr.in.path = inpath;
        ~~~~ ^
process/open.c:212:18: error: no member named 'in' in 'struct __tb_process_attr_t'
            attr.in.file = rawfile;
            ~~~~ ^
process/open.c:218:14: error: no member named 'in' in 'struct __tb_process_attr_t'
        attr.in.pipe = inpipe;
        ~~~~ ^
process/open.c:227:14: error: no member named 'out' in 'struct __tb_process_attr_t'
        attr.out.path = outpath;
        ~~~~ ^
process/open.c:236:18: error: no member named 'out' in 'struct __tb_process_attr_t'
            attr.out.file = rawfile;
            ~~~~ ^
process/open.c:242:14: error: no member named 'out' in 'struct __tb_process_attr_t'
        attr.out.pipe = outpipe;
        ~~~~ ^
process/open.c:250:14: error: no member named 'err' in 'struct __tb_process_attr_t'
        attr.err.path = errpath;
        ~~~~ ^
process/open.c:259:18: error: no member named 'err' in 'struct __tb_process_attr_t'
            attr.err.file = rawfile;
            ~~~~ ^
process/open.c:265:14: error: no member named 'err' in 'struct __tb_process_attr_t'
        attr.err.pipe = errpipe;
        ~~~~ ^
9 errors generated.
```

**Comment by waruqi** [comment]
please uninstall system tbox and rebuild xmake souce.

**Comment by aacirino** [comment]
I installed tbox due to the compiling errors. Either using the brew installed or the supplied tbox the compiling errors are the same. I uninstalled tbox and it still does not compile. There is an issue in the makefiles preventing the use of tbox and luajit installed by brew.

**Comment by waruqi** [comment]
The xmake 2.5.5 source code uses the newer tbox header file. Only the tbox master version of process.h has attr.in definition. But looking at the compilation error, it seems that the header file of the lower version tbox library is still used.

The built-in tbox library header file should always be used to compile the xmake source code, so this problem should not exist. This is very strange, you can look at the definition in process.h.

**Comment by aacirino** [comment]
I uninstalled the brew tbox and still cannot build xmake. I modified a little part of the code to be able to use modules with clang, I will open a pull request and hope to incorporate it in the brew installation.

**Comment by waruqi** [comment]
You can try to run `bash <(curl -fsSL https://xmake.io/shget.text)` to install xmake. 

More installation detail: https://xmake.io/#/guide/installation

**Comment by aacirino** [comment]
My problem is that I really want to use modules to build my project and clang now has full support to modules with the '-fmodules' compiler flag instead of '-fmodules-ts' flag. That's the only change I made back in version 2.3.6 that I was able to compile. I merged my fork to keep it up to date with version 2.5.5 and am not able to compile anymore. I cannot install xmake by any other method because it will lack my change and will then break the modules compilation with clang 12.

**Comment by waruqi** [comment]
Currently, xmake only supports module-ts in the early days, at that time gcc did not support module.

Later, I will consider improving xmake to better support modules, but it may take some time because I don’t have much time to pay attention to modules recently.

**Comment by aacirino** [comment]
I created a pull request

**Comment by waruqi** [comment]
Does it work now? about compile tbox

**Comment by aacirino** [comment]
Unfortunately not, still the same errors with tbox.

**Comment by aacirino** [comment]
After a little research (aka Google search) I managed to update the tbox submodule with `git submodule update --recursive`. The problem seems to be that just fetching upstream did not update tbox, only xmake. Now I am able to build and use xmake 2.5.5 with C++ modules support.

**Comment by waruqi** [comment]
I remember that the xmake v2.5.5.tar.gz package downloaded by brew should contain all the submodules.
