### ISSUE TITLE
qt6 openglwidget 找不到

### ISSUE THREAD

**Issue by hh-wu** [xmake-io/xmake#1520]
### 描述问题

qt6 编译失败
代码repo: https://github.com/hh-wu/range_xmake.git

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 错误信息

如果是xmake相关编译问题，请加上`-vD`参数运行，并给出完整编译输出信息以及执行的完整命令，例如：

错误日志-------->[log.txt](https://github.com/xmake-io/xmake/files/6830297/log.txt)

如果日志太多，可以上传附件，但必须完整，否则一率标记为 Invalid。

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.5
- xmake运行平台：win10 x64
- xmake目标平台：win10 x64

### 其他信息

set_config("qt", "C:/Qt/6.0.4/msvc2019_64")

add_frameworks("QtCore","QtGui","QtNetwork","QtPrintSupport","QtOpenGLWidgets")

**Comment by waruqi** [comment]
> 如果是xmake相关编译问题，请加上-vD参数运行，并给出完整编译输出信息以及执行的完整命令，例如：

> error: @programdir\modules\private\async\runjobs.lua:225: @programdir\core\sandbox\modules\os.lua:391: execv(C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX64\x64\cl.exe -c /EHsc -nologo -Zi -FS -Fdbuild\windows\x64\debug\compile.Range.pdb -Od -std:c++17 -ITetGen -IRangeBase\include -IRangeSolverLib\include -IRangeModel\include -IC:\Users\TF\CLionProjects\range3\range\build\.gens\Range\windows\x64\debug\rules\qt\ui -DQT_QML_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -D_WINDOWS -experimental:external -external:W0 -external:IC:\Qt\6.0.4\msvc2019_64\include\QtCore -experimental:external -external:W0 -external:IC:\Qt\6.0.4\msvc2019_64\include\QtCore\6.0.4 -experimental:external -external:W0 -external:IC:\Qt\6.0.4\msvc2019_64\include\QtCore\6.0.4\QtCore -experimental:external -external:W0 -external:IC:\Qt\6.0.4\msvc2019_64\include\QtGui -experimental:external -external:W0 -external:IC:\Qt\6.0.4\msvc2019_64\include\QtGui\6.0.4 -experimental:external -external:W0 -external:IC:\Qt\6.0.4\msvc2019_64\include\QtGui\6.0.4\QtGui -experimental:external -external:W0 -external:IC:\Qt\6.0.4\msvc2019_64\include\QtNetwork -experimental:external -external:W0 -external:IC:\Qt\6.0.4\msvc2019_64\include\QtNetwork\6.0.4 -experimental:external -external:W0 -external:IC:\Qt\6.0.4\msvc2019_64\include\QtNetwork\6.0.4\QtNetwork -experimental:external -external:W0 -external:IC:\Qt\6.0.4\msvc2019_64\include\QtPrintSupport -experimental:external -external:W0 -external:IC:\Qt\6.0.4\msvc2019_64\include\QtPrintSupport\6.0.4 -experimental:external -external:W0 
-external:IC:\Qt\6.0.4\msvc2019_64\include\QtPrintSupport\6.0.4\QtPrintSupport -experimental:external -external:W0 -external:IC:\Qt\6.0.4\msvc2019_64\include\QtWidgets -experimental:external -external:W0 -external:IC:\Qt\6.0.4\msvc2019_64\include\QtWidgets\6.0.4 -experimental:external -external:W0 -external:IC:\Qt\6.0.4\msvc2019_64\include\QtWidgets\6.0.4\QtWidgets -experimental:external -external:W0 -external:IC:\Qt\6.0.4\msvc2019_64\include -experimental:external -external:W0 -external:IC:\Qt\6.0.4\msvc2019_64\mkspecs\win32-msvc -experimental:external -external:W0 -external:IC:\Users\TF\CLionProjects\vcpkg\installed\x64-windows-static\include /openmp -Fobuild\.objs\Range\windows\x64\debug\gens\rules\qt\moc\moc_draw_engine_cylinder.cpp.obj build\.gens\Range\windows\x64\debug\rules\qt\moc\moc_draw_engine_cylinder.cpp) failed(2)
如果日志太多，可以上传附件，但必须完整，否则一率标记为 Invalid。

请根据提示 给出完整 log ，不要就给那么一点，我没 qt6 环境，没时间再去装一个测试，只能看 log

**Comment by waruqi** [comment]
> add_frameworks("QtCore","QtGui","QtNetwork","QtPrintSupport","QtOpenGLWidgets")

你备注里面贴的是 QtOpenGLWidgets

>     add_frameworks("QtCore","QtGui","QtNetwork","QtPrintSupport","OpenGLWidgets")

你实际 xmake.lua 配置里面

**Comment by hh-wu** [comment]
已更新，这两个我其实都试过了，都不行。
其实就是Qt6把opengl分出来了，具体细节在[这里](https://doc.qt.io/qt-6/qtopengl-index.html)。
另外项目黄了，最近有新工作，也就不用搞了。

**Comment by waruqi** [comment]
试了下，我这 mac 上 ok，也就额外 xmake.lua 再多加个 QtOpenGL 就完事了。。win 上没环境，暂时不测了。先就这样吧。

```lua
[ 76%]: ccache compiling.release Range/src/text_edit_widget.cpp
[ 76%]: ccache compiling.release Range/src/material_property_edit_table.cpp
[ 76%]: ccache compiling.release Range/src/model_tree.cpp
[ 76%]: ccache compiling.release Range/src/gl_entity_list.cpp
[ 77%]: ccache compiling.release Range/src/problem_selector_tree.cpp
[ 77%]: ccache compiling.release Range/src/value_scale.cpp
[ 77%]: ccache compiling.release Range/src/rename_model_dialog.cpp
[ 77%]: ccache compiling.release Range/src/model_statistics_dialog.cpp
[ 77%]: ccache compiling.release Range/src/bool_difference_dialog.cpp
[ 77%]: ccache compiling.release Range/src/document_tree.cpp
[ 77%]: ccache compiling.release Range/src/gl_display_properties.cpp
[ 78%]: ccache compiling.release Range/src/variable_value_edit.cpp
[ 78%]: ccache compiling.release Range/src/move_node_dialog.cpp
[ 78%]: ccache compiling.release Range/src/rra_session.cpp
[ 78%]: ccache compiling.release Range/src/gl_element.cpp
[ 99%]: linking.release Range
[ 99%]: linking.release RangeSolver
[ 99%]: generating.qt.app Range.app
[ 99%]: generating.qt.app RangeSolver.app
[100%]: build ok!
```
