### ISSUE TITLE
alilog依赖libcurl - mac - x86_64 - 平台打包库失败

### ISSUE THREAD

**Issue by fallending** [xmake-io/xmake#1521]
### 描述问题

如题

### 期待的结果

打包成功

### 错误信息

如果是xmake相关编译问题，请加上`-vD`参数运行，并给出完整编译输出信息以及执行的完整命令，例如：

```console
$ xmake f -p macosx -a x86_64 --vcpkg=$(VCPKG_HOME) -o _xbuilds -y -vD

看附件
```

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：xmake v2.5.3+202104271704,
- xmake运行平台：mac
- xmake目标平台：mac

### 其他信息

关键报错如下
```
ld: warning: ignoring file ../lib/.libs/libcurl.a, building for iOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )
Undefined symbols for architecture arm64:
  "_curl_easy_cleanup", referenced from:
      _tool_list_engines in curl-tool_help.o
      _post_per_transfer in curl-tool_operate.o
      _create_transfer in curl-tool_operate.o
      _single_transfer in curl-tool_operate.o
      _add_file_name_to_url in curl-tool_operhlp.o
[xmake.build.1.log](https://github.com/xmake-io/xmake/files/6828418/xmake.build.1.log)

```

**Comment by waruqi** [comment]
> ld: warning: ignoring file ../lib/.libs/libcurl.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )

你上面的是 `building for iOS-arm64`  log附件里的为啥是 ios-arm64。。

你 mac 是啥 arch？ 编译生成的 ../lib/.libs/libcurl.a 发上来看下呢，或者自己确认下里面的 arch

**Comment by fallending** [comment]
> > ld: warning: ignoring file ../lib/.libs/libcurl.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )
> 
> 你上面的是 `building for iOS-arm64` log附件里的为啥是 ios-arm64。。
> 
> 你 mac 是啥 arch？ 编译生成的 ../lib/.libs/libcurl.a 发上来看下呢，或者自己确认下里面的 arch

抱歉，iOS-arm64首次打包是遇到这个问题了，但是iOS打包依赖的是`@xmake macro package -p iphoneos -o $(iosdir)` ，为了拿更多的日志，所以切换为`xmake f -p macosx -a x86_64 --vcpkg=$(VCPKG_HOME) -o _xbuilds -y -vD`，两者是同样的报错。。
[libcurl.a.zip](https://github.com/xmake-io/xmake/files/6829223/libcurl.a.zip)

**Comment by waruqi** [comment]
我这里 mac ok，你的 libcurl.a 格式生成的不对，具体我也不知道，要么就是 libtool 的问题，这个应该跟 xmake 没啥关系了，xmake 也是调用 libcurl/configure 编译的。。

你可以手动拉一份 libcurl 代码，执行编译下试试。。要么就是你这 libtool 有问题。

**Comment by fallending** [comment]
哦，好的，老哥方便把下面这块配置信息（你那边打印的）给发一下嘛？

```
configure: Configured to build curl/libcurl:

  Host setup:       x86_64-apple-darwin
  Install prefix:   /tmp/curl-7.77.0-x86_64
  Compiler:         clang
   CFLAGS:          -mmacosx-version-min=10.8 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64 -pipe -Qunused-arguments -Os -Werror=partial-availability
   CPPFLAGS:        
   LDFLAGS:         -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -framework SystemConfiguration -framework CoreFoundation -framework Security
   LIBS:            

  curl version:     7.77.0
  SSL:              enabled (Secure Transport)
  SSH:              no      (--with-{libssh,libssh2})
  zlib:             no      (--with-zlib)
  brotli:           no      (--with-brotli)
  zstd:             no      (--with-zstd)
  GSS-API:          no      (--with-gssapi)
  GSASL:            no      (libgsasl not found)
  TLS-SRP:          no      (--enable-tls-srp)
  resolver:         POSIX threaded
  IPv6:             enabled
  Unix sockets:     enabled
  IDN:              no      (--with-{libidn2,winidn})
  Build libcurl:    Shared=no, Static=yes
  Built-in manual:  enabled
  --libcurl option: enabled (--disable-libcurl-option)
  Verbose errors:   enabled (--disable-verbose)
  Code coverage:    disabled
  SSPI:             no      (--enable-sspi)
  ca cert bundle:   no
  ca cert path:     
  ca fallback:      
  LDAP:             no      (--enable-ldap / --with-ldap-lib / --with-lber-lib)
  LDAPS:            no      (--enable-ldaps)
  RTSP:             enabled
  RTMP:             no      (--with-librtmp)
  Metalink:         no      (--with-libmetalink)
  PSL:              no      (libpsl not found)
  Alt-svc:          enabled (--disable-alt-svc)
  HSTS:             enabled (--disable-hsts)
  HTTP1:            enabled (internal)
  HTTP2:            no      (--with-nghttp2, --with-hyper)
  HTTP3:            no      (--with-ngtcp2, --with-quiche)
  ECH:              no      (--enable-ech)
  Protocols:        DICT FILE FTP FTPS GOPHER GOPHERS HTTP HTTPS IMAP IMAPS MQTT POP3 POP3S RTSP SMB SMBS SMTP SMTPS TELNET TFTP
  Features:         AsynchDNS HSTS IPv6 Largefile NTLM NTLM_WB SSL UnixSockets alt-svc

Making all in lib
```

**Comment by waruqi** [comment]
sh ./configure --disable-silent-rules --disable-dependency-tracking --enable-shared=no --enable-static=yes --with-pic --with-darwinssl --without-libidn2 --without-nghttp2 --without-brotli --without-ca-bundle --without-ca-path --without-librtmp --without-libpsl --disable-ares --disable-ldap --without-zlib --without-zstd --without-openssl --prefix=/Users/ruki/.xmake/packages/l/libcurl/7.73.0/1640ec349dd1433dbd204b3b384682f3

**Comment by fallending** [comment]
【同步】针对官网curl编译，也出现这个问题。原因是我本地工具环境不太干净，将tc配置到env前面就好了

```
export DEVROOT="${XCODE_DEV}/Toolchains/XcodeDefault.xctoolchain"
export PATH="${DEVROOT}/usr/bin/:${PATH}"
```

**Comment by waruqi** [comment]
ok，那我关了

**Comment by fallending** [comment]
> ok，那我关了

问题是，用xmake还是报一样的错误，就只能用curl编好的库了。

**Comment by waruqi** [comment]
那就不知道了，如果还是之前的错误信息，应该还是跟你的环境有关系
