### ISSUE TITLE
Fail when installing vcpkg modules

### ISSUE THREAD

**Issue by mineas312** [xmake-io/xmake#1522]
### Describe the bug
Cannot install vcpkg modules.

### Expected behavior
Success in downloading and installing vcpkg modules.

### Error output
Without `-v -D`:

> PS C:\Users\MineAS\Desktop\TiltedOnline> xmake -y
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2019
  => install vcpkg::magnum latest .. failed
if you want to get verbose errors, please see:
  -> C:\Users\MineAS\AppData\Local\.xmake\cache\packages\2107\v\vcpkg_magnum\latest\installdir.failed\logs\install.txt
error: install failed!

in install.txt:
`Computing installation plan...`
before some reinstalls and commands I got:
`fetch vcpkg::magnum-latest failed!`
but I'm not able to recreate this for now.

With `-v -D`:
[log.txt](https://github.com/xmake-io/xmake/files/6832513/log.txt)

### Related Environment
1. Installed xmake.
2. Installed vcpkg including: adding root folder to `PATH` env, adding root folder to `VCPKG_ROOT` env, running bootstrap_vcpkg.bat, installing vcpkg integrate.
3. Downloaded TiltedOnline and run `xmake -y` in root folder.

- xmake version: 2.5.5
- os: Windows
- target platform: Windows

### Additional context
In this log, what draws my attention is line `error: @programdir\core\sandbox\modules\os.lua:391: execv(E:\vcpkg\vcpkg install magnum:x64-windows-static --debug) failed(-1073741819)` and if i execute this command in command line I get:

> PS C:\Users\MineAS\Desktop\TiltedOnline> E:\vcpkg\vcpkg install magnum:x64-windows-static --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: E:\vcpkg
[DEBUG] Using installed-root: E:\vcpkg\installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: E:\vcpkg\buildtrees
[DEBUG] Using downloads-root: E:\vcpkg\downloads
[DEBUG] Using packages-root: E:\vcpkg\packages
[DEBUG] Using scripts-root: E:\vcpkg\scripts
[DEBUG] Using ports-root: E:\vcpkg\ports
[DEBUG] Using versions-root: E:\vcpkg\versions
[DEBUG] Default binary cache path is: C:\Users\MineAS\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] Found path: E:\CMake\bin\cmake.exe
[DEBUG] CreateProcessW("E:\CMake\bin\cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    46296 us
[DEBUG] CreateProcessW("E:\CMake\bin\cmake.exe" -DVCPKG_ROOT_DIR=E:/vcpkg -DPACKAGES_DIR=E:/vcpkg/packages -DBUILDTREES_DIR=E:/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=E:/vcpkg/installed -DDOWNLOADS=E:/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "E:\vcpkg\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    41456 us

**Comment by mineas312** [comment]
I finally resolved the issue uninstalling CMake from my computer. Caused because vcpkg modules are compiled using CMake. This seems not to be solution for everyone because I found a man without CMake and is not able to compile it. Version of CMake which does not work: 3.20.0 and 3.21.0. Probably versions below 3.20 should be able to compile it properly (but not sure which one).

**Comment by waruqi** [comment]
right, cmake failed

>CreateProcessW("E:\CMake\bin\cmake.exe" -DVCPKG_ROOT_DIR=E:/vcpkg -DPACKAGES_DIR=E:/vcpkg/packages -DBUILDTREES_DIR=E:/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=E:/vcpkg/installed -DDOWNLOADS=E:/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "E:\vcpkg\buildtrees\0.vcpkg_tags.cmake")

**Comment by waruqi** [comment]
I close it now.
