### ISSUE TITLE
utils.install.cmake_importfiles incorrectly set architecture bits

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1524]
### 描述问题

fooConfigVersion.cmake
```
# check that the installed version has the same 32/64bit-ness as the one which is currently searching:
if(NOT CMAKE_SIZEOF_VOID_P STREQUAL "8")
  math(EXPR installedBits "8 * 8")
  set(PACKAGE_VERSION "${PACKAGE_VERSION} (${installedBits}bit)")
  set(PACKAGE_VERSION_UNSUITABLE TRUE)
endif()
```

在arch=x86的时候这里仍然是8*8，显示64bit，不正确

### 期待的结果

utils.install.cmake_importfiles正确处理架构不同位数

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.5 dev
- xmake运行平台：windows x64
- xmake目标平台：windows x86

### 其他信息

https://github.com/xq114/xmake-repo/runs/3097643590?check_suite_focus=true

**Comment by waruqi** [comment]
这种小改动，你直接帮忙改下就好了

https://github.com/xmake-io/xmake/blob/03ffb3cb797b7029653f77309c27722d9be78483/xmake/scripts/cmake_importfiles/xxxConfigVersion.cmake#L44

**Comment by xq114** [comment]
> 这种小改动，你直接帮忙改下就好了
> 
> https://github.com/xmake-io/xmake/blob/03ffb3cb797b7029653f77309c27722d9be78483/xmake/scripts/cmake_importfiles/xxxConfigVersion.cmake#L44

如何在这里面加target arch的判断？这里是8还是4取决于xmake的设置

**Comment by waruqi** [comment]
不懂 cmake，CMAKE_SIZEOF_VOID_P 这玩意的 sizeof(ptr) cmake 自己不会去检测设置么？ 

还有 

> if(NOT CMAKE_SIZEOF_VOID_P STREQUAL "8")

不是 not 8 的意思么，不是 8 bytes 时候，为啥会设置 "8 * 8"？ 之前是从其他已有的 importfiles 搬过来的。。不清楚怎么弄。。单纯 cmake file 里面让 cmake 自己判断不了？

import files 不是 cmake 构建时候导入使用的么，这个时候已经没有 xmake 运行时了，要让 xmake 控制，那就得生成 importfiles 时候，直接写死在里面 8 还是 4。。

**Comment by xq114** [comment]
> 不懂 cmake，CMAKE_SIZEOF_VOID_P 这玩意的 sizeof(ptr) cmake 自己不会去检测设置么？
> 
> 还有
> 
> > if(NOT CMAKE_SIZEOF_VOID_P STREQUAL "8")
> 
> 不是 not 8 的意思么，不是 8 bytes 时候，为啥会设置 "8 * 8"？ 之前是从其他已有的 importfiles 搬过来的。。不清楚怎么弄。。单纯 cmake file 里面让 cmake 自己判断不了？
> 
> import files 不是 cmake 构建时候导入使用的么，这个时候已经没有 xmake 运行时了，要让 xmake 控制，那就得生成 importfiles 时候，直接写死在里面 8 还是 4。。

这段的逻辑是针对64位库的：如果CMAKE_SIZEOF_VOID_P不是8，就说明当前的项目是32位的，这里64位的库不适用，把名字改成64位是为了方便debug。如果是32位库，这里的8就要改成4. 这个的确是生成的时候写死的

**Comment by waruqi** [comment]
可以在这里搞个变量，根据 target:arch() 判断下

https://github.com/xmake-io/xmake/blob/03ffb3cb797b7029653f77309c27722d9be78483/xmake/modules/target/action/install/cmake_importfiles.lua#L25

然后 importfile 模板文件里面根据 `"@varname@"` 取出来
