### ISSUE TITLE
windows平台，当PATH内有mingw工具链时，cuda工程编译失败

### ISSUE THREAD

**Issue by ltmit** [xmake-io/xmake#1526]
### 问题：
在windows平台上，当系统环境变量PATH内包含mingw工具链（gcc.exe，g++.exe等）时，自动检测msvc+CUDA编译环境，生成的脚本编译失败。提示：
`error: nvcc fatal : Host compiler targets unsupported OS.`
经查，是错误的检测到了gcc.exe并将其设置到cuda的ccbin参数，导致了此问题。
### 平台环境：
- Win10 x64（Dev.21502）
- msvc 2017（community）
- CUDAv11.2
- msys2（gcc10.2）

### 期待的结果

希望在PATH内有gcc工具链的情况下，指定platform=windows能够正确的检测msvc+CUDA工具链，并生成正确的编译脚本。

**Comment by waruqi** [comment]
msys2 下默认平台是 mingw 不是 windows/msvc

请手动切到 xmake f -p windows 到 msvc/windows 平台，或者在 cmd/ps 下执行编译

**Comment by ltmit** [comment]
> msys2 下默认平台是 mingw 走的 gcc 工具链 不是 windows/msvc
> 
> 请手动切到 xmake f -p windows 到 msvc/windows 平台，或者在 cmd/ps 下执行编译

没问题。我正式如此操作的。
请看清楚问题描述：当系统环境变量PATH中有gcc.exe时，哪怕 xmake f -p windows，命令行下编译，也会出现cuda编译报错。问题就在于哪怕整体toolchain指定到msvc，但nvcc的ccbin参数仍旧检测为gcc导致失败。

**Comment by waruqi** [comment]
加一下 -vD 贴下完整编译错误

**Comment by waruqi** [comment]
没有 -vD 完整信息提供么？没有的话 我关了。

**Comment by waruqi** [comment]
应该可以了，见 https://github.com/xmake-io/xmake/issues/1556
