### ISSUE TITLE
set_toolchain(msvc, nil) vs set_toolset(msvc, nil)

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1529]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
```set_toolchain("msvc")```

现在报warning warning: set_toolchain(msvc, nil) is deprecated, please uses set_toolset(msvc, nil) instead of it，但换成set_toolset之后，xrepo env shell不能正常加载msvc环境

**Comment by waruqi** [comment]
set_toolchain 是早期的接口，用来单独设置某个 cc/cxx/ld 工具 `set_toolchain("cc", "gcc")`，也就是现在的 set_toolset("cc", "gcc")

后来重构了工具链，单独的工具集设置，走 set_toolset，完整工具链设置用 `set_toolchains("msvc")`

https://xmake.io/#/zh-cn/manual/project_target?id=targetset_toolchains

**Comment by xq114** [comment]
明白了，是我打错了..
