### ISSUE TITLE
hecking for Microsoft Visual Studio (x64) version ... no，为什么会自动检测vs的版本，能否跳过

### ISSUE THREAD

**Issue by weicong790** [xmake-io/xmake#1530]
![image](https://user-images.githubusercontent.com/24372233/126876658-48071afd-acd3-40ab-ab9e-5cc40247f7ef.png)

**Comment by waruqi** [comment]
win上默认平台windows，默认走的msvc编译器，跳过，那用什么编译？你也没说清楚你有什么工具链
