### ISSUE TITLE
编译android arm64-v8a平台报错

### ISSUE THREAD

**Issue by setupsong** [xmake-io/xmake#1535]
错误如下：
/home/coder/.local/share/xmake/core/base/os.lua:715: aarch64-linux-android-gcc: error: aarch64-none-linux-android: No such file or director
aarch64-linux-android-gcc: error: unrecognized command line option '-target'

**Comment by waruqi** [comment]
根据 issues 模板提示，给出完整命令和输出

**Comment by setupsong** [comment]
描述问题

ubuntu18.04 编译 android 平台下 arm64-v8a架构动态库报错

期待的结果

同样的方式编译armv7的动态库没有问题，找到并解决问题。

编译命令：
xmake clean
rm -r .xmake
rm -r build

TARGET_TYPE=.so
BUILD_NDK=/home/coder/vguang/tools/android-ndk-r17/
BUILD_ARCH=arm64-v8a
BUILD_BIN=${BUILD_NDK}/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/
BUILD_PLAT=android
BUILD_CROSS_PREFIX=aarch64-linux-android-
BUILD_TARGET=channel
BUILDMODE=release
TO_DRI=${BUILD_TARGET}_${BUILDMODE}

if [ ! -e ${TO_DRI} ]; then
     mkdir  ${TO_DRI}
fi

xmake f -p ${BUILD_PLAT} --ndk=${BUILD_NDK} -a ${BUILD_ARCH} -m ${BUILDMODE} \
     --cc=${BUILD_CROSS_PREFIX}gcc --cxx=${BUILD_CROSS_PREFIX}g++

错误信息：
checking for the flags (-O3) ... ok
> aarch64-linux-android-gcc -O3
checking for the flags (-pie -fPIE) ... no
> aarch64-linux-android-gcc -pie -fPIE -target aarch64-none-linux-android -gcc-toolchain /home/coder/vguang/tools/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -D__ANDROID_API__=28
checkinfo: /home/coder/.local/share/xmake/core/base/os.lua:715: aarch64-linux-android-gcc: error: aarch64-none-linux-android: No such file or directory
aarch64-linux-android-gcc: error: unrecognized command line option '-target'

stack traceback:
    [C]: in function 'error'
    [/home/coder/.local/share/xmake/core/base/os.lua:715]: in function 'raise'
    [/home/coder/.local/share/xmake/core/sandbox/modules/os.lua:309]: in function 'runv'
    [...local/share/xmake/modules/detect/tools/gcc/has_flags.lua:44]:
    [C]: in function 'trycall'
    [/home/coder/.local/share/xmake/core/sandbox/modules/try.lua:121]: in function 'try'
    [...local/share/xmake/modules/detect/tools/gcc/has_flags.lua:44]: in function 'hasflags'
    [...oder/.local/share/xmake/modules/lib/detect/has_flags.lua:110]: in function 'has_flags'
    [/home/coder/.local/share/xmake/core/tool/builder.lua:70]: in function '_mapflag'
    [/home/coder/.local/share/xmake/core/tool/builder.lua:88]: in function '_mapflags'
    [/home/coder/.local/share/xmake/core/tool/builder.lua:269]: in function '_add_flags_from_flagkind'
    [/home/coder/.local/share/xmake/core/tool/builder.lua:283]: in function '_add_flags_from_option'
    [/home/coder/.local/share/xmake/core/tool/builder.lua:320]: in function '_add_flags_from_target'
    [/home/coder/.local/share/xmake/core/tool/compiler.lua:286]: in function 'compflags'
    [.../coder/.local/share/xmake/actions/build/kinds/object.lua:106]: in function '_do_build_file'
    [.../coder/.local/share/xmake/actions/build/kinds/object.lua:174]: in function '_build_object'
    [.../coder/.local/share/xmake/actions/build/kinds/object.lua:196]:
checking for the flags (-fomit-frame-pointer) ... no
> aarch64-linux-android-gcc -fomit-frame-pointer -target aarch64-none-linux-android -gcc-toolchain /home/coder/vguang/tools/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -D__ANDROID_API__=28
checkinfo: /home/coder/.local/share/xmake/core/base/os.lua:715: aarch64-linux-android-gcc: error: aarch64-none-linux-android: No such file or directory
aarch64-linux-android-gcc: error: unrecognized command line option '-target'



相关环境

    xmake版本：v2.2.7
    xmake运行平台：ubuntu18.04
    xmake目标平台：android arm64-v8a

其他信息

**Comment by waruqi** [comment]
版本太老，先升级 xmake 版本，另外 android 走默认的编译器，切 gcc 我不保证能完全支持。
