### ISSUE TITLE
Add utils.bin2c rule to generate header from binary file

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#1544]
### default format (.bin)

```lua
target("console")
    set_kind("binary")
    add_rules("utils.bin2c")
    add_files("src/*.c")
    add_files("res/*.bin")
```

### specific format (.png)

```lua
target("console")
    set_kind("binary")
    add_files("src/*.c")
    add_files("res/*.png", {rules ="utils.bin2c"})
```

### set line width

```lua
target("console")
    set_kind("binary")
    add_rules("utils.bin2c", {linewidth = 16})
    add_files("src/*.c")
    add_files("res/*.bin")
```

### usage in code

```c
static unsigned char g_png_data[] = {
    #include "image.png.h"
};

int main(int argc, char** argv)
{
    printf("image.png: %s, size: %d\n", g_png_data, sizeof(g_png_data));
    return 0;
}
```

**Comment by SirLynix** [comment]
Why `c++.utils`? This rule probably could be used by C too.

**Comment by waruqi** [comment]
> Why `c++.utils`? This rule probably could be used by C too.

we can add an alias, c.utils.xx c++.utils.xx

**Comment by SirLynix** [comment]
I'm not sure about global either, it may actually prevents to declare the data where we want.

How about
```cpp
static unsigned char g_filename_data[] = {
#include "filename.bin.h"
};```

size could then be obtained using sizeof.
The advantage would be to control how we declare data (some may want to declare it non-const for example).

**Comment by SirLynix** [comment]
Yes but it does prevent someone to declare it otherwise, e.g. without const.

Maybe we could make it configurable wether it generates number sequence or global arrays containing them

**Comment by waruqi** [comment]
> I'm not sure about global either, it may actually prevents to declare the data where we want.
> 
> How about
> 
> ```c++
> static unsigned char g_filename_data[] = {
> #include "filename.bin.h"
> };
> ```

ok, I will consider it.

**Comment by waruqi** [comment]
I have finished this feature. 

example: https://github.com/xmake-io/xmake/blob/dev/tests/projects/other/bin2c/xmake.lua

**Comment by waruqi** [comment]
we can also call private module:

```console
xmake l private.utils.bin2c -i /tmp/b -o /tmp/a -w 16
```

**Comment by waruqi** [comment]
done

**Comment by waruqi** [comment]
now we can custom rule extensions in global

```lua

target("test")
    set_kind("binary")
    add_rules("utils.bin2c", {extensions = {".png", ".bin"}})
    add_files("src/*.c")
    add_files("src/*.bin")
    add_files("src/*.png")
```

see https://github.com/xmake-io/xmake/issues/1555
