### ISSUE TITLE
Custom job sometimes causes .xmake lock file to persist after xmake has closed

### ISSUE THREAD

**Issue by 1bardesign** [xmake-io/xmake#1548]
Custom job from #1539 has been working, but causes some obscure issue where though xmake closes "fine", sometimes it leaves the "only run one xmake at a time" lock file behind, so running xmake again stalls at the terminal forever. Running with `xmake --verbose -D` reports this:
```
$ xmake --verbose -D
the current project is being accessed by other processes, please waiting!
```
so far I'm getting around this with `$ rm -r .xmake` before running again if it stalls.

I noticed if i use `-D` argument for all runs, sometimes I get a stack traceback.

```
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:821]: in function 'raise'
    [@programdir/core/sandbox/modules/os.lua:263]: in function 'runv'
    [./xmake.lua:10]: in function 'script'
    [@programdir/actions/build/kinds/object.lua:57]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:208]:
    [C]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [@programdir/modules/private/async/runjobs.lua:201]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:365]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:821: in function 'raise'
        @programdir/modules/private/async/runjobs.lua:232: in function 'catch'
        @programdir/core/sandbox/modules/try.lua:127: in function 'try'
        @programdir/modules/private/async/runjobs.lua:201: in function 'cotask'
        @programdir/core/base/scheduler.lua:365: in function <@programdir/core/base/scheduler.lua:362>
```

I'm not totally sure where this corresponds to the xmake codebase, and have to stop digging into it for today, but figured the stack trace and the rule definition on the other issue would probably be enough for you to go from it if you had time to look into it.

Might be something strange dotnet core is doing with its process, but I don't think it is intended that an issue with another process can cause xmake to break like this, anyway.

**Comment by waruqi** [comment]
If in the current project directory, the xmake process (in on_xxx script) executes other xmake process, e.g. `xmake build/run`, this problem will occur, because xmake can only allow only one xmake process to access the current project configuration at the same time.

https://github.com/xmake-io/xmake/blob/a959af20d2a34038efb13053c112ef1d55084081/xmake/actions/build/main.lua#L107
https://github.com/xmake-io/xmake/blob/a959af20d2a34038efb13053c112ef1d55084081/xmake/actions/config/main.lua#L277

**Comment by 1bardesign** [comment]
That makes sense, but I don't see where/how I would be running a separate xmake process with the rule here: https://github.com/xmake-io/xmake/issues/1539#issuecomment-889543455 (or with execv changed to runv to suppress output on success).

I am not trying to run it concurrently, as far as I know. I just have one terminal open and I wait for xmake to close and the shell to return before running it again.

**Comment by waruqi** [comment]
Can you let me see your complete xmake.lua?

**Comment by 1bardesign** [comment]
```lua
add_rules("mode.debug", "mode.release")

target("native_library")
	set_kind("shared")
	add_files("src/native/**.cpp")

rule("csharp")
	set_extensions(".csproj")
	on_build_file(function (target, sourcefile)
		os.runv("dotnet", {"build", sourcefile, "-o", target:targetdir()})
	end)
	on_clean(function (target, sourcefile)
		os.runv("dotnet", {"clean", sourcefile, "-o", target:targetdir()})
	end)
	on_link(function () end)
	rule_end()

target("test")
	set_kind("binary")
	add_rules("csharp")
	add_files("src/dotnet/test.csproj")
	add_deps("native_library")
```

**Comment by waruqi** [comment]
I don't see any problems, unless there are other background xmake processes and its child processes that have not exited and access this project at the same time, this problem will occur.

For example, you can confirm whether the dotnet child process has completely exited, and whether its background child process is still running.

**Comment by waruqi** [comment]
I currently cannot reproduce this problem.
