### ISSUE TITLE
使用qt编译时只进行moc，不编译源码，导致链接时找不到符号

### ISSUE THREAD

**Issue by HelloWorld886** [xmake-io/xmake#1549]
rule("cpp")
    set_extensions(".h", ".cpp")

target("OpenGLWindow")
    add_rules("qt.shared", "cpp")
    add_defines("OPENGLWINDOW_LIBRARY")
    add_includedirs("include")

    add_frameworks("QtCore", "QtGui", "QtWidgets", "QtOpenGL")

    on_load(function(target)
        target:add("files", "openglfunctions.cpp", "openglwindow.cpp", "include/openglfunctions.h" , "include/openglwindow.h", "include/export.h")
    end)

![image](https://user-images.githubusercontent.com/15972674/128305257-2b9ee112-ffd1-4674-b1de-7b1fa8f5a986.png)

看build目录里并没有生成添加文件的obj，只有moc的obj

**Comment by waruqi** [comment]
确保 cpp 文件路径，并贴下 -vD 输出

**Comment by HelloWorld886** [comment]
![image](https://user-images.githubusercontent.com/15972674/128308876-981b3c64-90de-413f-bcd0-502928c5bd18.png)

目录结构
![image](https://user-images.githubusercontent.com/15972674/128309178-48867e88-ceba-40d4-80b3-b3deac35a6b3.png)

**Comment by waruqi** [comment]
贴下 -vD 我就是要看完整输出，不是部分

xmake f -c -vD
xmake -r -vD

**Comment by HelloWorld886** [comment]
`PS E:\LearnOpenGL\OpenGLWIndow> xmake -r -vD
[ 16%]: compiling.qt.moc include\openglfunctions.h
D:\Qt\Qt6.1.2\6.1.2\msvc2019_64\bin\moc.exe -DOPENGLWINDOW_LIBRARY -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_CORE_LIB -DQT_GUI_LIB -DQT_WIDGETS_LIB -DQT_OPENGL_LIB -Iinclude -IE:\LearnOpenGL\OpenGLWIndow\build\.gens\OpenGLWindow\windows\x64\release\rules\qt\ui -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtCore -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtCore\6.1.2 -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtCore\6.1.2\QtCore -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtGui -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtGui\6.1.2 -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtGui\6.1.2\QtGui -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtWidgets -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtWidgets\6.1.2 -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtWidgets\6.1.2\QtWidgets -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtOpenGL -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtOpenGL\6.1.2 -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtOpenGL\6.1.2\QtOpenGL -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\mkspecs\win32-msvc include\openglfunctions.h -o build\.gens\OpenGLWindow\windows\x64\release\rules\qt\moc\moc_openglfunctions.cpp
[ 16%]: compiling.qt.moc include\openglwindow.h
D:\Qt\Qt6.1.2\6.1.2\msvc2019_64\bin\moc.exe -DOPENGLWINDOW_LIBRARY -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_CORE_LIB -DQT_GUI_LIB -DQT_WIDGETS_LIB -DQT_OPENGL_LIB -Iinclude -IE:\LearnOpenGL\OpenGLWIndow\build\.gens\OpenGLWindow\windows\x64\release\rules\qt\ui -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtCore -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtCore\6.1.2 -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtCore\6.1.2\QtCore -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtGui -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtGui\6.1.2 -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtGui\6.1.2\QtGui -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtWidgets -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtWidgets\6.1.2 -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtWidgets\6.1.2\QtWidgets -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtOpenGL -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtOpenGL\6.1.2 -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtOpenGL\6.1.2\QtOpenGL -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\mkspecs\win32-msvc include\openglwindow.h -o build\.gens\OpenGLWindow\windows\x64\release\rules\qt\moc\moc_openglwindow.cpp
[ 16%]: compiling.qt.moc include\export.h
D:\Qt\Qt6.1.2\6.1.2\msvc2019_64\bin\moc.exe -DOPENGLWINDOW_LIBRARY -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_CORE_LIB -DQT_GUI_LIB -DQT_WIDGETS_LIB -DQT_OPENGL_LIB -Iinclude -IE:\LearnOpenGL\OpenGLWIndow\build\.gens\OpenGLWindow\windows\x64\release\rules\qt\ui -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtCore -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtCore\6.1.2 -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtCore\6.1.2\QtCore -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtGui -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtGui\6.1.2 -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtGui\6.1.2\QtGui -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtWidgets -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtWidgets\6.1.2 -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtWidgets\6.1.2\QtWidgets -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtOpenGL -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtOpenGL\6.1.2 -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtOpenGL\6.1.2\QtOpenGL -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include -ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\mkspecs\win32-msvc include\export.h -o build\.gens\OpenGLWindow\windows\x64\release\rules\qt\moc\moc_export.cpp
include\export.h(0:1): note: No relevant classes found. No output generated.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30037\bin\HostX64\x64\cl.exe -c /EHsc -nologo -std:c++17 -Iinclude -IE:\LearnOpenGL\OpenGLWIndow\build\.gens\OpenGLWindow\windows\x64\release\rules\qt\ui -DOPENGLWINDOW_LIBRARY -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_CORE_LIB -DQT_GUI_LIB -DQT_WIDGETS_LIB -DQT_OPENGL_LIB -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtCore -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtCore\6.1.2 -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtCore\6.1.2\QtCore -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtGui -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtGui\6.1.2 -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtGui\6.1.2\QtGui -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtWidgets -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtWidgets\6.1.2 -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtWidgets\6.1.2\QtWidgets -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtOpenGL -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtOpenGL\6.1.2 -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtOpenGL\6.1.2\QtOpenGL -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\mkspecs\win32-msvc -Fobuild\.objs\OpenGLWindow\windows\x64\release\gens\rules\qt\moc\moc_export.cpp.obj build\.gens\OpenGLWindow\windows\x64\release\rules\qt\moc\moc_export.cpp
include\openglfunctions.h(0:1): note: No relevant classes found. No output generated.
moc_export.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30037\bin\HostX64\x64\cl.exe -c /EHsc -nologo -std:c++17 -Iinclude -IE:\LearnOpenGL\OpenGLWIndow\build\.gens\OpenGLWindow\windows\x64\release\rules\qt\ui -DOPENGLWINDOW_LIBRARY -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_CORE_LIB -DQT_GUI_LIB -DQT_WIDGETS_LIB -DQT_OPENGL_LIB -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtCore -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtCore\6.1.2 -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtCore\6.1.2\QtCore -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtGui -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtGui\6.1.2 -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtGui\6.1.2\QtGui -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtWidgets -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtWidgets\6.1.2 -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtWidgets\6.1.2\QtWidgets -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtOpenGL -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtOpenGL\6.1.2 -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtOpenGL\6.1.2\QtOpenGL -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\mkspecs\win32-msvc -Fobuild\.objs\OpenGLWindow\windows\x64\release\gens\rules\qt\moc\moc_openglfunctions.cpp.obj build\.gens\OpenGLWindow\windows\x64\release\rules\qt\moc\moc_openglfunctions.cpp
moc_openglfunctions.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30037\bin\HostX64\x64\cl.exe -c /EHsc -nologo -std:c++17 -Iinclude -IE:\LearnOpenGL\OpenGLWIndow\build\.gens\OpenGLWindow\windows\x64\release\rules\qt\ui -DOPENGLWINDOW_LIBRARY -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_CORE_LIB -DQT_GUI_LIB -DQT_WIDGETS_LIB -DQT_OPENGL_LIB -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtCore -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtCore\6.1.2 -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtCore\6.1.2\QtCore -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtGui -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtGui\6.1.2 -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtGui\6.1.2\QtGui -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtWidgets -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtWidgets\6.1.2 -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtWidgets\6.1.2\QtWidgets -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtOpenGL -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtOpenGL\6.1.2 -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include\QtOpenGL\6.1.2\QtOpenGL -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\include -experimental:external -external:W0 -external:ID:\Qt\Qt6.1.2\6.1.2\msvc2019_64\mkspecs\win32-msvc -Fobuild\.objs\OpenGLWindow\windows\x64\release\gens\rules\qt\moc\moc_openglwindow.cpp.obj build\.gens\OpenGLWindow\windows\x64\release\rules\qt\moc\moc_openglwindow.cpp
moc_openglwindow.cpp
[ 66%]: linking.release OpenGLWindow.dll
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX64\\x64\\link.exe" -dll -nologo -machine:x64 -libpath:D:\Qt\Qt6.1.2\6.1.2\msvc2019_64\lib Qt6Core.lib Qt6Gui.lib Qt6Widgets.lib Qt6OpenGL.lib ws2_32.lib gdi32.lib ole32.lib advapi32.lib shell32.lib user32.lib OpenGL32.lib imm32.lib winmm.lib iphlpapi.lib -out:build\windows\x64\release\OpenGLWindow.dll build\.objs\OpenGLWindow\windows\x64\release\gens\rules\qt\moc\moc_openglfunctions.cpp.obj build\.objs\OpenGLWindow\windows\x64\release\gens\rules\qt\moc\moc_openglwindow.cpp.obj build\.objs\OpenGLWindow\windows\x64\release\gens\rules\qt\moc\moc_export.cpp.obj
error: @programdir\modules\private\async\runjobs.lua:232: @programdir\actions\build\kinds\shared.lua:88: @programdir\modules\core\tools\link.lua:159:   正在创建库 build\windows\x64\release\OpenGLWindow.lib 和对象 build\windows\x64\release\OpenGLWindow.exp
moc_openglwindow.cpp.obj : error LNK2019: 无法解析的外部符号 "public: __cdecl OpenGLWindow::OpenGLWindow(class QWindow *)" (??0OpenGLWindow@@QEAA@PEAVQWindow@@@Z)，函数 "public: void __cdecl OpenGLWindow::`default constructor closure'(void)" (??_FOpenGLWindow@@QEAAXXZ) 中引用了该符号
moc_openglwindow.cpp.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl OpenGLWindow::renderNow(void)" (?renderNow@OpenGLWindow@@QEAAXXZ)，函数 "public: virtual int __cdecl OpenGLWindow::qt_metacall(enum QMetaObject::Call,int,void * *)" (?qt_metacall@OpenGLWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z) 中引用了该符号
build\windows\x64\release\OpenGLWindow.dll : fatal error LNK1120: 2 个无法解析的外部命令

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:821]: in function 'raise'
    [@programdir\modules\core\tools\link.lua:159]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
    [@programdir\modules\core\tools\link.lua:140]:
    [C]: in function 'link'
    [@programdir\actions\build\kinds\shared.lua:88]: in function 'callback'
    [@programdir\modules\core\project\depend.lua:186]: in function 'on_changed'
    [@programdir\actions\build\kinds\shared.lua:54]: in function '_do_link_target'
    [@programdir\actions\build\kinds\shared.lua:109]:
    [@programdir\actions\build\kinds\shared.lua:130]: in function '_link_target'
    [@programdir\actions\build\kinds\shared.lua:152]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:208]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:201]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:365]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:821: in function 'raise'
        @programdir\modules\private\async\runjobs.lua:232: in function 'catch'
        @programdir\core\sandbox\modules\try.lua:127: in function 'try'
        @programdir\modules\private\async\runjobs.lua:201: in function 'cotask'
        @programdir\core\base\scheduler.lua:365: in function <@programdir\core\base\scheduler.lua:362>`

**Comment by HelloWorld886** [comment]
直接add_files是没问题的，在on_load里面设置就有问题了

**Comment by waruqi** [comment]
> rule("cpp")
> set_extensions(".h", ".cpp")

你干嘛要重写 c++ 的规则，把内置的 .cpp 构建全部重写掉了，却搞个空规则，啥也没实现。。怎么可能会有 cpp 代码编译进去

**Comment by HelloWorld886** [comment]
去掉自建规则的话，会报这个
![image](https://user-images.githubusercontent.com/15972674/128363981-7a46b6b8-3c6c-4990-819f-483927c47e4f.png)

**Comment by waruqi** [comment]
因为你没添加任何  add_files， 无法检测到任何 c++ 规则，动态加的 自己设置 add_rules("c++") 规则，或者加个任意的  stub.cpp 空文件到 add_files

**Comment by HelloWorld886** [comment]
解决了，感谢回复
