### ISSUE TITLE
在clang14下使用set_symbols("debug")无法产生调试符号

### ISSUE THREAD

**Issue by 2283572185** [xmake-io/xmake#1552]
### 描述问题
在设置clang工具链后，使用set_symbols("debug")无法产生调试符号

### 期待的结果

使用set_symbols("debug")即可产生调试符号，不需要添加额外的链接选项

### 错误信息
在只启用set_symbols("debug")的情况下产生的编译结果。
[ 25%]: compiling.Debug MyIO\src\test.cpp
clang -c -Qunused-arguments -m64 -g -Wall -Wextra -O0 -DWIN32 -DUNICODE -D_UNICODE -D_WIN64 -D_DLL -DDEBUG -D_DEBUG -std=c++2b -fno-cxx-exceptions -fdouble-square-bracket-attributes -ffixed-point -fvectorize -fstandalone-debug -gmodules -fdebug-macro -fdebug-info-for-profiling -o build\.objs\MyIO\windows\x64\Debug\MyIO\src\test.cpp.obj MyIO\src\test.cpp
checking for flags (-MMD -MF) ... ok
checking for flags (-fdiagnostics-color=always) ... ok
[ 50%]: linking.Debug MyIO.exe
clang++ -o build\windows\x64\Debug\MyIO.exe build\.objs\MyIO\windows\x64\Debug\MyIO\src\test.cpp.obj -m64 -LMyIO\lib -lntdll -lnt -lntdllp
[100%]: build ok!
由此可见，set_symbols("debug")仅在编译时添加了-g，并未在链接时添加-g，因此无调试符号

### 相关环境

-编译器：llvm-clang14
-编译器平台：x86_64-pc-windows-msvc
- xmake版本：v2.5.6+202108020442
- xmake运行平台：Windows10-x64
- xmake目标平台：Windows10-x64

### 其他信息
存在问题的版本：
if is_mode("Debug") then
    add_defines("DEBUG", "_DEBUG")
    set_optimize("none")
    set_symbols("debug")
    add_cxflags("-fstandalone-debug", "-gmodules", "-fdebug-macro", "-fdebug-info-for-profiling")
end

可以正常使用的版本：
if is_mode("Debug") then
    add_defines("DEBUG", "_DEBUG")
    set_optimize("none")
    set_symbols("debug")
    add_cxflags("-fstandalone-debug", "-gmodules", "-fdebug-macro", "-fdebug-info-for-profiling")
    add_ldflags("-g", "-fstandalone-debug", "-gmodules", "-fdebug-macro", "-fdebug-info-for-profiling")
end
![只使用set_symbol](https://user-images.githubusercontent.com/63223769/128374790-c6f1f197-698b-4aa7-beab-46b2087821a1.png)
![手动设置链接选项](https://user-images.githubusercontent.com/63223769/128374796-edbceb7c-0aa8-4df3-b281-348a42cd2672.png)

**Comment by waruqi** [comment]
> 由此可见，set_symbols("debug")仅在编译时添加了-g，并未在链接时添加-g，因此无调试符号

-g 原本就是编译器选项，又不是给链接器用的，你硬加进去也没用。 我看编译里面 -g 已经有了，说明 xmake 没啥问题

置于为什么没有调试符号，这个你自己去研究下 clang on windows 上的配置，跟 xmake 没啥关系。

**Comment by waruqi** [comment]
> 由此可见，set_symbols("debug")仅在编译时添加了-g，并未在链接时添加-g，因此无调试符号

-g 原本就是编译器选项，又不是给链接器用的，你硬加进去也没用。 我看编译里面 -g 已经有了，说明 xmake 没啥问题

置于为什么没有调试符号，这个你自己去研究下 clang on windows 上的配置，跟 xmake 没啥关系。

**Comment by 2283572185** [comment]
我在命令行下试过的，linking阶段执行的命令clang++ -o build\windows\x64\Debug\MyIO.exe build.objs\MyIO\windows\x64\Debug\MyIO\src\test.cpp.obj -m64 -LMyIO\lib -lntdll -lnt -lntdllp
如果不加-g在clang14下是不会产生调试符号的，即使编译阶段已经添加了。
我希望可以兼容一下高版本的clang编译器，给clang13和clang14的链接阶段也加上-g，这样set_symbol("debug")在高版本的clang中才有正确的表现。
clang14使用lld-link链接器，该链接器会.pdb文，而且有默认路径。上述的那个缺少调试符号的exe体积都比正常的小，而且无法调试，因此认为缺少调试符号。

**Comment by 2283572185** [comment]
当然，我用的是x86_64-pc-windows-msvc的目标平台，如果改成x86_64-pc-windows-gnu还会不会有这个问题我没有测试过。

**Comment by waruqi** [comment]
> 我在命令行下试过的，linking阶段执行的命令clang++ -o build\windows\x64\Debug\MyIO.exe build.objs\MyIO\windows\x64\Debug\MyIO\src\test.cpp.obj -m64 -LMyIO\lib -lntdll -lnt -lntdllp
> 如果不加-g在clang14下是不会产生调试符号的，即使编译阶段已经添加了。
> 我希望可以兼容一下高版本的clang编译器，给clang13和clang14的链接阶段也加上-g，这样set_symbol("debug")在高版本的clang中才有正确的表现。
> clang14使用lld-link链接器，该链接器会.pdb文，而且有默认路径。上述的那个缺少调试符号的exe体积都比正常的小，而且无法调试，因此认为缺少调试符号。

有相关官方文档么，贴下 link 呢，我只知道 -g 只是编译选项，除非官方文档明确指示哪些 clang 版本的特定 lld linker 必须需要 -g，我才能内置加上，否则你只能外面自己走 add_ldflags 自己配置上

**Comment by waruqi** [comment]
而且我看 https://releases.llvm.org/ 官网目前最新版本也就 llvm clang 12.0.1 。。为啥你能下到 clang 14?  下载link也发个呢

**Comment by 2283572185** [comment]
关于clang14的下载链接没有，只能clone一下master分支然后自行编译

**Comment by waruqi** [comment]
我估计多半仅仅 win clang 下 -g 才需要送入 linker，因为生成 pdb 需要同时传入 ld，而其他平台不需要这么做，-g 仅仅作为编译选项

不过我现在没 win clang 环境，暂时测试不了，你只能先手动外面自己配置下 -g 到 ldflags 了。

**Comment by 2283572185** [comment]
我没有在官方文档中找到关于使用clang进行链接的说明，但在lld-link的编译选项中看到了有关部分。
![未添加-g](https://user-images.githubusercontent.com/63223769/128520860-f985e4a3-eab4-4531-ab9f-51a752a63933.png)
![添加-g](https://user-images.githubusercontent.com/63223769/128521318-10bae247-6057-47f3-9f86-868f6d18c723.png)
由此可见，在链接时，不添加-g选项的话，clang并不会给lld-link传递-debug选项。
而在lld-link的说明中指出：
/debug                  Embed a symbol table in the image（-debug同理，只是使用了gnu like的风格）
所有，如果不向链接时的clang中添加-g就无法产生调试符号

**Comment by waruqi** [comment]
> 由此可见，在链接时，不添加-g选项的话，clang并不会给lld-link传递-debug选项。

能确认下，仅 lld 需要么，还是其他 ld 也是？

**Comment by 2283572185** [comment]
clang默认的链接器一直都是lld，在Windows下lld会调用lld-link来进行链接。就目前我测试的lld-link，msvc的link和gcc的ld，在不添加-g的情况下都不能产生调试符号，还是那个原因，链接器缺少-debug选项

**Comment by waruqi** [comment]
> msvc的link和gcc的ld，在不添加-g的情况下都不能产生调试符号

那只针对 win 程序吧。。我这 linux/mac/android/ios 下 clang/gcc 从来不加 -g 到 ld 。。用的好好的。。

只有win的 pdb 生成需要 link 参与

**Comment by 2283572185** [comment]
Windows下xmake拆散了链接和编译过程，这使得-stdlib和-g这种编译和链接都需要的选项要在add_ldflag和add_cxflag里各写一遍，容易造成误解啊。一般使用clang的话编译和链接是一起的，这种两边都需要的选项写一遍就可以了。如果可以的话，最好在说明文档里告知一下Windows下用clang要多写一遍。

**Comment by waruqi** [comment]
makefile 常规做法都是 ldflags/cflags 分开的。。原本就是自己分开配置。。这是常识，没什么可以说的。。win clang 这种特殊配置，用户自己看 clang 的文档。。

**Comment by waruqi** [comment]
我加上支持了，https://github.com/xmake-io/xmake/commit/671cabb77b5421fae4fabecdfe9d0df4adf0ddb8
