### ISSUE TITLE
reinitialize xmake-repo if repository is broken

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1563]
### 你在什么场景下需要该功能？

在运行`xrepo update-repo`时如果由于网络不稳定等原因中断，xmake-repo文件夹会直接消失，在网络稳定之后重新运行`xrepo update-repo`则会一直失败

### 描述可能的解决方案

在检测到xmake-repo不存在或者其中git文件夹不完整时，自动尝试修复：删除文件夹并重新从xmake-repo clone

**Comment by waruqi** [comment]
话说 git clone 不是应该会保证完整性么

**Comment by xq114** [comment]
> 话说 git clone 不是应该会保证完整性么

中途ctrl+c取消了

**Comment by waruqi** [comment]
> 中途ctrl+c取消了

试了下，没复现出来

> 在检测到xmake-repo不存在或者其中git文件夹不完整时，自动尝试修复

不存在的时候，没啥可修复了，直接重新 clone 就完事了。。git目录不完整的检测 这个我这边很难检测的，只有 git 自身去检测修复，如果 git 被中断后不完整了，应该是 git 的问题，我觉得提到 git issues 上 更合适。

**Comment by xq114** [comment]
我这边也没复现出来，先close吧，之后有再遇到的再open
