### ISSUE TITLE
Adding an existing file to a target does not relink

### ISSUE THREAD

**Issue by jorgenpt** [xmake-io/xmake#1565]
### Describe the bug

1. Create a file named Main.cpp containing `int main() { return 0; }`
2. Create an empty file named Secondary.cpp
3. Create a minimal xmake.lua containing `target("Main"); add_files("Exe.cpp")`
4. `xmake b`
5. Change xmake.lua to say `target("Main"); add_files("Exe.cpp", "Secondary.cpp")`
6. `xmake b`

Note that it is important that you create Secondary.cpp *before* the first `xmake b`. 

The second `xmake b` compiles Secondary.cpp, but does *not* relink Main.exe.

### Expected behavior

Adding a new file to the target should invalidate the target even if the mtime of the source file is older than the output .exe -- it probably needs to consider the mtime of the .o file rather than the .cpp file?

### Related Environment

Please provide compiling and running environment information:

- xmake version: xmake v2.5.6+202107260800
- os: Windows 10
- target platform: Windows 10 x64

**Comment by waruqi** [comment]
I have fixed it, please update to dev version and try it again.

xmake update -s dev

**Comment by jorgenpt** [comment]
This looks good now, thanks!
