### ISSUE TITLE
Removing a file does not relink a target

### ISSUE THREAD

**Issue by jorgenpt** [xmake-io/xmake#1566]
### Describe the bug

1. Create a file named Main.cpp containing `int main() { return 0; }`
2. Create an empty file named Secondary.cpp
3. Create a minimal xmake.lua containing `target("Main"); add_files("Exe.cpp", "Secondary.cpp")`
4. `xmake b`
5. Change xmake.lua to say `target("Main"); add_files("Exe.cpp")`
6. `xmake b`

This second `xmake b` does *nothing*.

### Expected behavior

The second `xmake b` should re-link Main.exe without Secondary.cpp.o

### Related Environment

Please provide compiling and running environment information:

- xmake version: xmake v2.5.6+202107260800
- os: Windows 10
- target platform: Windows 10 x64

**Comment by waruqi** [comment]
I have fixed it, please update to dev version and try it again.

xmake update -s dev

**Comment by jorgenpt** [comment]
Looks good! Thanks!
