### ISSUE TITLE
Custom rule not causing immediate rebuild of dependents

### ISSUE THREAD

**Issue by jorgenpt** [xmake-io/xmake#1570]
### Describe the bug

Defining a custom rule like this does not seem to rebuild the files that include the header that is generated by it:

xmake.lua:
```lua
rule("flatbuf")
	set_extensions(".fbs")
	on_buildcmd_file(function (target, batchcmds, sourcefile, opt)
		local outfile = path.join(path.directory(sourcefile), path.basename(sourcefile) .. "_generated.h")
		batchcmds:show_progress(opt.progress, "${color.build.object}generating.fbs %s", sourcefile)
		batchcmds:vrunv("cp", { sourcefile, outfile })
		batchcmds:add_depfiles(sourcefile)
		batchcmds:set_depmtime(os.mtime(outfile))
    end)

target("LibCommon", { rules = {"flatbuf"}, files = {"Common/**.fbs", "Common/**.cpp"}, includedirs = {"Common"} })
```

Main.cpp:
```cpp
#include "Test_generated.h"
int main() { return 0; }
```

Test.fbs:
```cpp
// Empty comment
```

(note: This relies on gnu coreutils `cp` as a simple no-op transformation tool. It can be retrieved from http://gnuwin32.sourceforge.net/packages/coreutils.htm, or the minimal set of files is included in the attached [xmake-custom-tool-repro.zip](https://github.com/xmake-io/xmake/files/6963947/xmake-custom-tool-repro.zip), which also has the full project.)

Running `xmake b`, then modifying *just* Test.fbs (either by simply running `touch` or by adding a line to it), then running `xmake b` does *not* rebuild Main.cpp. Running `xmake.b` a second time does.

![image](https://user-images.githubusercontent.com/21258/128919710-ec24c863-0971-46fd-a718-9d57037bebef.png)

### Expected behavior

Generating a new file should invalidate the dependencies of Main.cpp and rebuild Main.o.

### Related Environment

Please provide compiling and running environment information:

- xmake version: v2.5.6+202107260800
- os: Windows 10
- target platform: Windows 10 x64

**Comment by jorgenpt** [comment]
I'm seeing the same behavior on my macOS 11.5.1 machine.

**Comment by waruqi** [comment]
you should use before_buildcmd_file instead of on_buildcmd_file to ensure your xxx_generated.h file is generated first.


This is because all source files are compiled in parallel. If main.cpp that depends on _generated.h is compiled first, then xmake will think that _generated.h has not changed. So your rule has been compiled before main.cpp is executed, which will trigger this problem.

And if your rule is executed first, then everything works fine. There are some undefined behaviors.

So, please use before_buildcmd_file to confirm that your rule is executed first.

**Comment by jorgenpt** [comment]
Ah, yes, you're right -- I changed from on_buildcmd_file to before_buildcmd_file at some point in my repro steps, but in the example I posted it *does* make a difference. Here's an example that reproduces even with before_buildcmd_file: 
[xmake-custom-tool-repro-v2.zip](https://github.com/xmake-io/xmake/files/6971500/xmake-custom-tool-repro-v2.zip)

## xmake.lua
```lua
rule("flatbuf")
	set_extensions(".fbs")
	before_buildcmd_file(function (target, batchcmds, sourcefile, opt)
		local outfile = path.join(path.directory(sourcefile), path.basename(sourcefile) .. "_generated.h")
		batchcmds:show_progress(opt.progress, "${color.build.object}generating.fbs %s", sourcefile)
		batchcmds:vrunv("cp", { sourcefile, outfile })
		batchcmds:vrunv(flatc_bin, flatc_args)
		batchcmds:add_depfiles(sourcefile)
		batchcmds:set_depmtime(os.mtime(outfile))
    end)

target("LibLeaf", { kind = "static", rules = {"flatbuf"},files = { "src/**.fbs", "src/Leaf.cpp" }, includedirs = {"src"} })
target("LibRoot", { deps = { "LibLeaf" }, kind = "static", rules = {"flatbuf"}, files = { "src/Root.cpp" }, includedirs = {"src"} })
target("Main", { deps = { "LibRoot" }, files = {"src/Main.cpp"} })
```

## src/Leaf.cpp
```cpp
#include "Test_generated.h"
```

## src/Root.cpp
```cpp
#include "Test_generated.h"
```

## src/Main.cpp
```cpp
int main() { return 0; }
```

## src/Test.fbs
```cpp
// Hello!
```

Here's the result:
![image](https://user-images.githubusercontent.com/21258/129105612-54f20f95-8781-4559-893a-bb105b8dc32e.png)

**Comment by jorgenpt** [comment]
@waruqi Ah, thanks! Is there any chance the API could extend so you could specify which file you're producing, so the cross-product parallel build could use that to sequence the tasks correctly?

**Comment by waruqi** [comment]
No, you just need set_policy("build.across_targets_in_parallel", false)

It only disables parallel compilation between multiple targets, but all source files in each target are still being compiled in parallel.

In addition, you can set this strategy only for the affected part of the target, instead of setting it globally.
