### ISSUE TITLE
Only one target is actually exported via utils.install.cmake_importfiles

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1571]
### 描述问题

当一个project含有多个target的时候应该在PTargets-release.cmake中包含所有target的library而不是只有一个。

xmake.lua
```
add_rules("utils.install.cmake_importfiles")
target(A, {kind="static", files="a.cpp"})
target(B, {kind="static", files="b.cpp"})
```

### 期待的结果

应该在PTargets-release.cmake中包含所有target的library

### 错误信息

```
#----------------------------------------------------------------
# Generated CMake target import file for configuration "Release".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "SuiteSparse::SPQR" for configuration "Release"
set_property(TARGET SuiteSparse::SPQR APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SuiteSparse::SPQR PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "ASM_NASM;C"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/SPQR.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS SuiteSparse::SPQR )
list(APPEND _IMPORT_CHECK_FILES_FOR_SuiteSparse::SPQR "${_IMPORT_PREFIX}/lib/SPQR.dll" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
```
实际上除了SPQR还有若干target没有导出

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.6
- xmake运行平台：windows
- xmake目标平台：windows

**Comment by waruqi** [comment]
更新下试试呢。

**Comment by xq114** [comment]
> 更新下试试呢。

不行，这样改cmake找不到了，find_package(SuiteSparse CONFIG) 只会找SuiteSparseConfig.cmake，现在没有这个文件了

**Comment by waruqi** [comment]
那要等上几天了，或者可以帮忙改下 https://github.com/xmake-io/xmake/blob/dev/xmake/modules/target/action/install/cmake_importfiles.lua

**Comment by xq114** [comment]
另一个问题是windows上动态库的target:targetfile()是dll，但是链接的时候应该链接到对应的implib，写在cmake文件里面的也应该是implib而不是dll，这个implib的信息怎么从target中获取？

**Comment by waruqi** [comment]
> 另一个问题是windows上动态库的target:targetfile()是dll，但是链接的时候应该链接到对应的implib，写在cmake文件里面的也应该是implib而不是dll，这个implib的信息怎么从target中获取？

targetfile 替换下 .dll 后缀
