### ISSUE TITLE
xmake r is slow

### ISSUE THREAD

**Issue by idealvin** [xmake-io/xmake#1572]
### Describe the bug

`xmake r` is slow. It takes several seconds before xmake started the program.

### Expected behavior

`xmake r` may be not necessary to check vs version, find third libraries.

### Related Environment

- xmake version: 2.5.6
- os: win10
- target platform: windows

### Additional context

```sh
$ xmake r -vD flag -x
checking for Microsoft Visual Studio (x64) version ... 2019
finding openssl from xmake ..
finding zlib from xmake ..
finding libcurl from xmake ..
boo: false
x: true
y: false
z: false
n: 0
i32: -32
i64: -64
u32: 32
u64: 64
dbl: 3.14
hello world|11
```

**Comment by waruqi** [comment]
更新到 dev 再试试

**Comment by idealvin** [comment]
> 更新到 dev 再试试

一样的

**Comment by waruqi** [comment]
xmake update -s github:xmake-io/xmake#dev

**Comment by idealvin** [comment]
> xmake update -s github:xmake-io/xmake#dev

这个版本可以，第一次 xmake r 较慢，后面就好了
