### ISSUE TITLE
Registry residuals are not cleaned when executing xmake update

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1576]
### 描述问题

用xmake update升级版本的时候，注册表中老版本存在残留，导致卸载程序界面出现多个xmake程序

### 期待的结果

在升级的时候清理注册表

### 错误信息

![image](https://user-images.githubusercontent.com/42310255/129437347-0d1df175-4a51-4941-890a-1b512324082a.png)

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.6
- xmake运行平台：Windows 10
- xmake目标平台：windows

**Comment by waruqi** [comment]
这个应该是nsis的问题，我也不知道怎么搞，可以看下 https://github.com/xmake-io/xmake/blob/246711d74ea45b554456fdb6ac44a83f5424824a/scripts/installer.nsi#L330

**Comment by xq114** [comment]
我找了下注册表，发现HKLM和HKCU下面都有一个xmake的uninstall项，其中HKLM是2.5.5的，HKCU是2.5.6的，安装位置是同一个位置。感觉卸载的时候应该要把两个地方都清理了才行

**Comment by waruqi** [comment]
我来回试了下，覆盖安装，只会保留一个注册表项，不会有冗余。。

唯一会出现两个的情况，是同时安装了 win32 和 win64 两个安装包。。所以这两的默认安装目录一个在 program files 下，一个在 program files(x86) 下。

所以也会同时存在两个注册表项。。

你可以确认下是否同时安装了它们。至少我这复现的情况来看，只存在这种case

所以，这个也无法改进，因为原本就装了两个版本的 bin 。。

**Comment by waruqi** [comment]
我执行 xmake update，如果都是 x64 的。。更新后还是一个注册表项，不会多出来

当然，早期版本 有过几次注册表混乱的情况，但记不得了，最近 2.5.x 的应该不会有这个问题

**Comment by xq114** [comment]
> 你可以确认下是否同时安装了它们。至少我这复现的情况来看，只存在这种case
> 
> 所以，这个也无法改进，因为原本就装了两个版本的 bin 。。

不是，可以明确确定只有一个bin，显示一个是admin一个是user，和x64无关

**Comment by xq114** [comment]
通过xmake update安装的是user版本，但不确定双击exe安装、从powershell安装、从admin powershell安装xmake是否都会安装user版本。如果是的话，admin版本是用来做什么的呢？

**Comment by waruqi** [comment]
update安装 双击安装 我都试了 同x64的 也ok 没法复现问题

没有分 admin版本，就是uac弹框装，admin下装 就省去弹框了 可以做到静默安装而已

**Comment by xq114** [comment]
> update安装 双击安装 我都试了 同x64的 也ok 没法复现问题
> 
> 没有分 admin版本，就是uac弹框装，admin下装 就省去弹框了 可以做到静默安装而已

但admin和user写注册表的位置是不一样的

https://github.com/xmake-io/xmake/blob/95dea5af25edb9f1eda15ad8412342e26ef39525/scripts/installer.nsi#L205-L210

似乎从powershell安装可以做到静默安装，是不是说明从powershell安装的其实是admin版本？

**Comment by waruqi** [comment]
应该是吧，我也不太清楚，这块脚本也是其他人贡献的。 现在重复项确认是这里导致的？

**Comment by xq114** [comment]
> 应该是吧，我也不太清楚，这块脚本也是其他人贡献的。 现在重复项确认是这里导致的？

我觉得用powershell装一个老版本再运行一下xmake update就能确定了

**Comment by waruqi** [comment]
ps 下来回试了好几遍，脚本装，update 。。还是没法复现，一切ok

**Comment by xq114** [comment]
https://github.com/xmake-io/xmake/blob/master/scripts/get.ps1#L107-L114

从这块看确实是直接以NOADMIN参数安装的，那两行测试命令应该是目标文件夹无法访问的时候才切到admin安装，和静默安装没啥关系，/S参数才是控制静默安装的。目标文件夹如果在用户目录下，基本上都可以直接访问，所以这里也不会切到admin，之前用admin安装的确实有点奇怪

**Comment by xq114** [comment]
> update安装 双击安装 我都试了 同x64的 也ok 没法复现问题
> 
> 没有分 admin版本，就是uac弹框装，admin下装 就省去弹框了 可以做到静默安装而已

我双击安装然后update复现了.
1. 双击安装到用户文件夹：`C:/Users/<user>/xmake`
2. xmake update dev

![image](https://user-images.githubusercontent.com/42310255/143372232-f51553aa-bca6-4848-8762-ca8b877c5346.png)
![image](https://user-images.githubusercontent.com/42310255/143372302-d2efb238-b0c9-48b1-844d-ea3420712418.png)
两个地方都有xmake。win11会自动把两个合成一个，但win10不会，而是直接显示多个应用；win10和win11在这种情况下卸载xmake之后都会留下一个无法删除的项
![image](https://user-images.githubusercontent.com/42310255/143372464-5c3bb401-4408-4eea-a691-bec02fc74974.png)

另外，在没装git的环境下运行xmake update会报错
```
> xmake update dev
error: @programdir\core\base\interpreter.lua:526: the scope root() is empty!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:829]: in function 'raise'
    [@programdir\core\base\interpreter.lua:526]:
    [C]: in function 'xpcall'
    [@programdir\core\base\interpreter.lua:758]: in function 'make'
    [@programdir\core\project\project.lua:255]: in function '_load_scope'
    [@programdir\core\project\project.lua:186]: in function '_load'
    [@programdir\core\project\project.lua:594]: in function '_load_packages'
    [@programdir\core\project\project.lua:1075]: in function 'packages'
    [@programdir\core\package\package.lua:1921]: in function 'load_from_project'
    [...dir\core\sandbox\modules\import\core\package\package.lua:38]: in function '_load_package_from_project'
    [@programdir\modules\private\action\require\impl\package.lua:676]: in function '_load_package'
    [@programdir\modules\private\action\require\impl\package.lua:800]: in function '_load_packages'
    [@programdir\modules\private\action\require\impl\package.lua:998]: in function 'load_packages'
    [...modules\private\action\require\impl\install_packages.lua:524]: in function 'install_packages'
    [...mdir\modules\private\action\require\impl\environment.lua:47]: in function 'enter'
    [@programdir\actions\update\main.lua:293]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:519]: in function 'run'
    [@programdir\core\main.lua:278]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:371]:
```
应该提示需要安装git才对

**Comment by waruqi** [comment]
> 我双击安装然后update复现了.

那就是 uac 弹框装 和 ps 脚本装混用的问题导致，uac 双击装走的 管理员模式，默认安装到 programfiles下，但是如果ps装过一次到 user/目录下，就会默认复用这个目录，虽然这时候，目录不需要管理员了，但是uac 还是会弹，而 ps 安装默认安装到 user/ 目录下，不需要管理员，也没走 uac ，所以会有两个

> 另外，在没装git的环境下运行xmake update会报错

我这里不会，一切 ok，update 不需要 git ，直接拉的 nsis 安装包运行的，不需要git

**Comment by waruqi** [comment]
这个也没啥好的解决方式，要么 双击安装，默认也走 user 目录，并且去掉 uac ，跟 ps 保持一致，但跟老版本混装，一样会有两个，并且如果没权限，还是会安装失败

要么 ps 默认也走 uac 并且装到 programfiles下，不确定是否ok，并且静默不了了。

**Comment by xq114** [comment]
> 我这里不会，一切 ok，update 不需要 git ，直接拉的 nsis 安装包运行的，不需要git

我运行目录下有一个xmake.lua。如果把这个文件删了，就会报错找不到xmake.lua然后终止，直到安装git之后才能正常使用xmake update，虽然使用过程中没用到git

**Comment by xq114** [comment]
> 这个也没啥好的解决方式，要么 双击安装，默认也走 user 目录，并且去掉 uac ，跟 ps 保持一致，但跟老版本混装，一样会有两个，并且如果没权限，还是会安装失败
> 
> 要么 ps 默认也走 uac 并且装到 programfiles下，不确定是否ok，并且静默不了了。

可以参考VS Code的处理方式，用复选框让用户自己选择装到哪里（All users/Just for me）

**Comment by waruqi** [comment]
> > 这个也没啥好的解决方式，要么 双击安装，默认也走 user 目录，并且去掉 uac ，跟 ps 保持一致，但跟老版本混装，一样会有两个，并且如果没权限，还是会安装失败
> > 要么 ps 默认也走 uac 并且装到 programfiles下，不确定是否ok，并且静默不了了。
> 
> 可以参考VS Code的处理方式，用复选框让用户自己选择装到哪里（All users/Just for me）

关键是一开始用户肯定不了解情况，ps 和 双击混用，还是会有这个问题。。如果用户知道这个问题，才能选择规避

**Comment by xq114** [comment]
> 关键是一开始用户肯定不了解情况，ps 和 双击混用，还是会有这个问题。。如果用户知道这个问题，才能选择规避，但都如果这个问题了，直接全 uac 双击就完事了，也不会有这个问题

不是混用的问题，我一般安装软件都是直接双击然后修改路径安装到用户文件夹下，不用默认路径，这个时候就算没用powershell装过照样有问题。要完全解决这个问题得用文件或别的方法记录安装的是admin还是user版本，然后在执行xmake update的时候读取这个信息，在调用安装包的时候根据信息加/NOADMIN参数。

**Comment by waruqi** [comment]
那好麻烦，而且对 nsis 不熟，如果是加 All users/Just for me 选项，你可以提个 pr 改下 installer.nsi

**Comment by xq114** [comment]
> 执行xmake update的时候读取这个信息，在调用安装包的时候根据信息加/NOADMIN参数

这个相对比较简单，改一下 https://github.com/xmake-io/xmake/blob/master/xmake/actions/update/main.lua#L162 就好，检测目录所需权限之前先检测目录下有没有权限说明文件，说明安装的是否为admin版本

**Comment by waruqi** [comment]
稍微改了下，不过还没时间详测，你先试试

https://github.com/xmake-io/xmake/commit/e2e14bba2335d9ea0a1de60a318c21efa4d067ef

**Comment by waruqi** [comment]
再试试 之前改的有bug 现在应该可以的 我测过了

**Comment by waruqi** [comment]
应该可以的，先这样吧
