### ISSUE TITLE
repositories 获取第三方库顺序错误？

### ISSUE THREAD

**Issue by TopXX** [xmake-io/xmake#1578]
### 描述问题

两个项目的xmake.lua分别配置了自己的本地repositories，且两个项目都有各自的add_requires，其中一个项目引用另外一个项目，add_requires却是先从xmake-repo获取包，而不是本地 repositories

### 期待的结果

按引用顺序从repositories获取包。

### 错误信息

使用 xmake repo -l 查看repositories顺序是正确的。

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：v2.5.6
- xmake运行平台：macOS
- xmake目标平台：macOS

### 其他信息

测试例子请查看附件。

[repositories.zip](https://github.com/xmake-io/xmake/files/6987800/repositories.zip)

请打开test2目录，使用xmake命令进行编译，查看获取包的顺序。

**Comment by waruqi** [comment]
看了下，jsoncpp ok，就是从你的 local repo 里面装的

```
in Match3-repo:
  -> jsoncpp 1.9.4
```

而 mysql 没从你的repo 找，是因为你配置的不对。。

目前 `add_repositories("xxx Repos")` 中的 Repos 路径是没有自动路径转换的，写的啥就是啥，并不是相对于当前 xmake.lua 路径，是相对于工程根目录的，你的工程根目录是 test2。那么 test1 里面配置 Repos 路径是找不到的，所以只能从global找 mysql

你要针对当前脚本路径，得写全路径。

```lua
add_repositories("XServer-repo " .. path.join(os.scriptdir(), "Repos"))
```

**Comment by TopXX** [comment]
目前测试下来，发现 os.scriptdir() 返回的路径是带空格的，会提示 updating repositories .. error: fatal: 仓库 '/Volumes/Macintosh' 不存在，我本地路径如下：
/Volumes/Macintosh DATA/Projects

**Comment by waruqi** [comment]
那你加个双引号

**Comment by TopXX** [comment]
我按下面方式加的双引号，报相同的错误。
add_repositories("XServer-repo \"" .. path.join(os.scriptdir(), "Repos\""))

**Comment by waruqi** [comment]
更新到 dev 版本后再试下

```lua
add_repositories("XServer-repo Repos", {rootdir = os.scriptdir()})
```

**Comment by TopXX** [comment]
可以正常使用了，感谢作者辛苦工作！
