### ISSUE TITLE
When installing a target on Linux, includes folders aren't copied

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#1583]
### Describe the bug
When installing a xmake target on Linux, includes are copied to the wrong folders:
```
> copy include/Nazara/Renderer/RenderWindowParameters.hpp to /usr/local/include/RenderWindowParameters.hpp
> copy include/Nazara/Renderer/ShaderBinding.hpp to /usr/local/include/ShaderBinding.hpp
> copy include/Nazara/Renderer/ShaderModule.hpp to /usr/local/include/ShaderModule.hpp
> copy include/Nazara/Renderer/Texture.hpp to /usr/local/include/Texture.hpp
> copy include/Nazara/Renderer/TextureSampler.hpp to /usr/local/include/TextureSampler.hpp
> copy include/Nazara/Renderer/UploadPool.hpp to /usr/local/include/UploadPool.hpp
> copy include/Nazara/Renderer/CommandBuffer.inl to /usr/local/include/CommandBuffer.inl
> copy include/Nazara/Renderer/CommandBufferBuilder.inl to /usr/local/include/CommandBufferBuilder.inl
> copy include/Nazara/Renderer/CommandPool.inl to /usr/local/include/CommandPool.inl
> copy include/Nazara/Renderer/Framebuffer.inl to /usr/local/include/Framebuffer.inl
> copy include/Nazara/Renderer/RenderBuffer.inl to /usr/local/include/RenderBuffer.inl
> copy include/Nazara/Renderer/RenderBufferView.inl to /usr/local/include/RenderBufferView.inl
> copy include/Nazara/Renderer/RenderDevice.inl to /usr/local/include/RenderDevice.inl
> copy include/Nazara/Renderer/Renderer.inl to /usr/local/include/Renderer.inl
> copy include/Nazara/Renderer/RenderFrame.inl to /usr/local/include/RenderFrame.inl
> copy include/Nazara/Renderer/RenderImage.inl to /usr/local/include/RenderImage.inl
> copy include/Nazara/Renderer/RenderPass.inl to /usr/local/include/RenderPass.inl
> copy include/Nazara/Renderer/RenderPipeline.inl to /usr/local/include/RenderPipeline.inl
> copy include/Nazara/Renderer/RenderPipelineLayout.inl to /usr/local/include/RenderPipelineLayout.inl
> copy include/Nazara/Renderer/RenderStates.inl to /usr/local/include/RenderStates.inl
> copy include/Nazara/Renderer/RenderSurface.inl to /usr/local/include/RenderSurface.inl
> copy include/Nazara/Renderer/RenderTarget.inl to /usr/local/include/RenderTarget.inl
> copy include/Nazara/Renderer/RenderWindow.inl to /usr/local/include/RenderWindow.inl
> copy include/Nazara/Renderer/ShaderBinding.inl to /usr/local/include/ShaderBinding.inl
> copy include/Nazara/Renderer/Texture.inl to /usr/local/include/Texture.inl
> copy include/Nazara/Renderer/TextureSampler.inl to /usr/local/include/TextureSampler.inl
> copy include/Nazara/Renderer/UploadPool.inl to /usr/local/include/UploadPool.inl
```

### Expected behavior
That folder are kept:

```
> copy include/Nazara/Renderer/ShaderModule.hpp to /usr/local/include/ShaderModule.hpp
```
=>
```
> copy include/Nazara/Renderer/ShaderModule.hpp to /usr/local/include/Nazara/Renderer/ShaderModule.hpp
```

### Related Environment

- xmake version: xmake v2.5.6+202107301017
- os: Ubuntu 20.04

**Comment by waruqi** [comment]
you need add () to reserve dir structure

add_headerfiles("src/(Nazara/*.h)")


https://xmake.io/#/manual/project_target?id=targetadd_headerfiles

**Comment by SirLynix** [comment]
Works great!

However I have a weird issue:
```
lynix@SirLynixVanDesktop:/mnt/c/Projets/NazaraNext/NazaraEngine$ xmake install --admin -v
installing NazaraCore ..
installing NazaraCore to /usr/local ..
> copy bin/linux_x86_64_release/libNazaraCore.so to /usr/local/lib
install ok!```

When using xmake install --admin, only one file gets installed.

But if I run xmake install from root, then it works:
```
lynix@SirLynixVanDesktop:/mnt/c/Projets/NazaraNext/NazaraEngine$ sudo /home/lynix/.local/bin/xmake install -v
installing NazaraCore ..
installing NazaraCore to /usr/local ..
> copy bin/linux_x86_64_release/libNazaraCore.so to /usr/local/lib
installing NazaraCore ..
installing NazaraCore to /usr/local ..
> copy bin/linux_x86_64_release/libNazaraCore.so to /usr/local/lib
> copy include/Nazara/Math/Algorithm.hpp to /usr/local/include/Algorithm.hpp
> copy include/Nazara/Math/Angle.hpp to /usr/local/include/Angle.hpp
> copy include/Nazara/Math/BoundingVolume.hpp to /usr/local/include/BoundingVolume.hpp
> copy include/Nazara/Math/Box.hpp to /usr/local/include/Box.hpp
> copy include/Nazara/Math/Config.hpp to /usr/local/include/Config.hpp
> copy include/Nazara/Math/Enums.hpp to /usr/local/include/Enums.hpp
> copy include/Nazara/Math/EulerAngles.hpp to /usr/local/include/EulerAngles.hpp
> copy include/Nazara/Math/Frustum.hpp to /usr/local/include/Frustum.hpp
> copy include/Nazara/Math/Matrix4.hpp to /usr/local/include/Matrix4.hpp
> copy include/Nazara/Math/OrientedBox.hpp to /usr/local/include/OrientedBox.hpp
> copy include/Nazara/Math/PidController.hpp to /usr/local/include/PidController.hpp
...
```

**Comment by waruqi** [comment]
It works for me, you can debug https://github.com/xmake-io/xmake/blob/19eee763e481570b2bfd1e1a62ec547892d80097/xmake/actions/install/main.lua#L113

**Comment by SirLynix** [comment]
Ok I found the "issue", in fact it was working but didn't display any log because `sudo.runl` will redirect stdout to a file. Using `sudo.execl` instead of `sudo.runl` fixes this. Do you want me to make a PR?

**Comment by waruqi** [comment]
> Ok I found the "issue", in fact it was working but didn't display any log because `sudo.runl` redirects stdout to a file. Using `sudo.execl` instead of `sudo.runl` fixes this. Do you want me to make a PR?

you can add sudo.vrunl

**Comment by SirLynix** [comment]
I think sudo.execl should be used, because the behavior of xmake install is to print basic info even without -v:
```
lynix@SirLynixVanDesktop:/mnt/c/Projets/NazaraNext/NazaraEngine$ xmake install -o test_verbose
installing NazaraCore ..
installing NazaraCore to test_verbose ..
installing NazaraAudio ..
installing NazaraAudio to test_verbose ..
installing NazaraUtility ..
installing NazaraUtility to test_verbose ..
installing PluginAssimp ..
installing PluginAssimp to test_verbose ..
installing NazaraPlatform ..
installing NazaraPlatform to test_verbose ..
installing NazaraShader ..
installing NazaraShader to test_verbose ..
installing NazaraRenderer ..
installing NazaraRenderer to test_verbose ..
installing RenderTest ..
installing RenderTest to test_verbose ..
installing NazaraPhysics2D ..
installing NazaraPhysics2D to test_verbose ..
installing NazaraVulkanRenderer ..
installing NazaraVulkanRenderer to test_verbose ..
installing NazaraPhysics3D ..
installing NazaraPhysics3D to test_verbose ..
installing NazaraGraphics ..
installing NazaraGraphics to test_verbose ..
installing GraphicsTest ..
installing GraphicsTest to test_verbose ..
installing PlayMusic ..
installing PlayMusic to test_verbose ..
installing NazaraNetwork ..
installing NazaraNetwork to test_verbose ..
installing NazaraUnitTests ..
installing NazaraUnitTests to test_verbose ..
installing NazaraOpenGLRenderer ..
installing NazaraOpenGLRenderer to test_verbose ..
installing Std140Debug ..
installing Std140Debug to test_verbose ..
installing PhysicsDemo ..
installing PhysicsDemo to test_verbose ..
installing NazaraClientUnitTests ..
installing NazaraClientUnitTests to test_verbose ..
installing DeferredShading ..
installing DeferredShading to test_verbose ..
installing DopplerEffect ..
installing DopplerEffect to test_verbose ..
install ok!
```

However, with -v it also displays each copied file:
```
lynix@SirLynixVanDesktop:/mnt/c/Projets/NazaraNext/NazaraEngine$ xmake install -vo test_verbose
installing NazaraCore ..
installing NazaraCore to test_verbose ..
> copy bin/linux_x86_64_debug/libNazaraCore-d.so to test_verbose/lib
> copy include/Nazara/Math/Algorithm.hpp to test_verbose/include/Nazara/Math/Algorithm.hpp
> copy include/Nazara/Math/Angle.hpp to test_verbose/include/Nazara/Math/Angle.hpp
> copy include/Nazara/Math/BoundingVolume.hpp to test_verbose/include/Nazara/Math/BoundingVolume.hpp
> copy include/Nazara/Math/Box.hpp to test_verbose/include/Nazara/Math/Box.hpp
> copy include/Nazara/Math/Config.hpp to test_verbose/include/Nazara/Math/Config.hpp
> copy include/Nazara/Math/Enums.hpp to test_verbose/include/Nazara/Math/Enums.hpp
> copy include/Nazara/Math/EulerAngles.hpp to test_verbose/include/Nazara/Math/EulerAngles.hpp
> copy include/Nazara/Math/Frustum.hpp to test_verbose/include/Nazara/Math/Frustum.hpp
> copy include/Nazara/Math/Matrix4.hpp to test_verbose/include/Nazara/Math/Matrix4.hpp
> copy include/Nazara/Math/OrientedBox.hpp to test_verbose/include/Nazara/Math/OrientedBox.hpp
> copy include/Nazara/Math/PidController.hpp to test_verbose/include/Nazara/Math/PidController.hpp
> copy include/Nazara/Math/Plane.hpp to test_verbose/include/Nazara/Math/Plane.hpp
> copy include/Nazara/Math/Quaternion.hpp to test_verbose/include/Nazara/Math/Quaternion.hpp
> copy include/Nazara/Math/Ray.hpp to test_verbose/include/Nazara/Math/Ray.hpp
...
```

So we should probably use sudo.execl and pass verbose flag to get the correct behavior

**Comment by SirLynix** [comment]
from actions/install/install_admin.lua:
```lua
    print("verbose:", option.get("verbose"))

    -- save the current option and push a new option context
    option.save()

    print("verbose:", option.get("verbose"))

    -- pass installdir to option
    if installdir then
        option.set("installdir", installdir)
    end

    -- pass prefix to option
    if prefix then
        option.set("prefix", prefix)
    end

    -- install target
    install(targetname)

    -- restore the previous option context
    option.restore()
```

The verbose option is lost because of the option.save(), but I don't understand why there's a need to make a new option context since this script is only run for admin installation (and thus only has options passed by the parent xmake script).

Removing this option.save()/option.restore() and using sudo.execl fixes everything.

**Comment by waruqi** [comment]
> I think sudo.execl should be used, because the behavior of xmake install is to print basic info even without -v:
> 
> ```
> lynix@SirLynixVanDesktop:/mnt/c/Projets/NazaraNext/NazaraEngine$ xmake install -o test_verbose
> installing NazaraCore ..
> installing NazaraCore to test_verbose ..
> installing NazaraAudio ..
> installing NazaraAudio to test_verbose ..
> installing NazaraUtility ..
> installing NazaraUtility to test_verbose ..
> installing PluginAssimp ..
> installing PluginAssimp to test_verbose ..
> installing NazaraPlatform ..
> installing NazaraPlatform to test_verbose ..
> installing NazaraShader ..
> installing NazaraShader to test_verbose ..
> installing NazaraRenderer ..
> installing NazaraRenderer to test_verbose ..
> installing RenderTest ..
> installing RenderTest to test_verbose ..
> installing NazaraPhysics2D ..
> installing NazaraPhysics2D to test_verbose ..
> installing NazaraVulkanRenderer ..
> installing NazaraVulkanRenderer to test_verbose ..
> installing NazaraPhysics3D ..
> installing NazaraPhysics3D to test_verbose ..
> installing NazaraGraphics ..
> installing NazaraGraphics to test_verbose ..
> installing GraphicsTest ..
> installing GraphicsTest to test_verbose ..
> installing PlayMusic ..
> installing PlayMusic to test_verbose ..
> installing NazaraNetwork ..
> installing NazaraNetwork to test_verbose ..
> installing NazaraUnitTests ..
> installing NazaraUnitTests to test_verbose ..
> installing NazaraOpenGLRenderer ..
> installing NazaraOpenGLRenderer to test_verbose ..
> installing Std140Debug ..
> installing Std140Debug to test_verbose ..
> installing PhysicsDemo ..
> installing PhysicsDemo to test_verbose ..
> installing NazaraClientUnitTests ..
> installing NazaraClientUnitTests to test_verbose ..
> installing DeferredShading ..
> installing DeferredShading to test_verbose ..
> installing DopplerEffect ..
> installing DopplerEffect to test_verbose ..
> install ok!
> ```
> 
> However, with -v it also displays each copied file:
> 
> ```
> lynix@SirLynixVanDesktop:/mnt/c/Projets/NazaraNext/NazaraEngine$ xmake install -vo test_verbose
> installing NazaraCore ..
> installing NazaraCore to test_verbose ..
> > copy bin/linux_x86_64_debug/libNazaraCore-d.so to test_verbose/lib
> > copy include/Nazara/Math/Algorithm.hpp to test_verbose/include/Nazara/Math/Algorithm.hpp
> > copy include/Nazara/Math/Angle.hpp to test_verbose/include/Nazara/Math/Angle.hpp
> > copy include/Nazara/Math/BoundingVolume.hpp to test_verbose/include/Nazara/Math/BoundingVolume.hpp
> > copy include/Nazara/Math/Box.hpp to test_verbose/include/Nazara/Math/Box.hpp
> > copy include/Nazara/Math/Config.hpp to test_verbose/include/Nazara/Math/Config.hpp
> > copy include/Nazara/Math/Enums.hpp to test_verbose/include/Nazara/Math/Enums.hpp
> > copy include/Nazara/Math/EulerAngles.hpp to test_verbose/include/Nazara/Math/EulerAngles.hpp
> > copy include/Nazara/Math/Frustum.hpp to test_verbose/include/Nazara/Math/Frustum.hpp
> > copy include/Nazara/Math/Matrix4.hpp to test_verbose/include/Nazara/Math/Matrix4.hpp
> > copy include/Nazara/Math/OrientedBox.hpp to test_verbose/include/Nazara/Math/OrientedBox.hpp
> > copy include/Nazara/Math/PidController.hpp to test_verbose/include/Nazara/Math/PidController.hpp
> > copy include/Nazara/Math/Plane.hpp to test_verbose/include/Nazara/Math/Plane.hpp
> > copy include/Nazara/Math/Quaternion.hpp to test_verbose/include/Nazara/Math/Quaternion.hpp
> > copy include/Nazara/Math/Ray.hpp to test_verbose/include/Nazara/Math/Ray.hpp
> ...
> ```
> 
> So we should probably use sudo.execl and pass verbose flag to get the correct behavior

ok, you can try

**Comment by waruqi** [comment]
> ```lua
> option.set("installdir", 
> ```

because it added some extra options, installdir, prefix.I remember that the current options should be read-only and cannot be modified

**Comment by SirLynix** [comment]
I tried to comment out option.save()/option.restore and it works as intended, so I'm not sure if there's a problem removing them in this script?

**Comment by waruqi** [comment]
If you execute task.run("install") in another action or task, there may be problems, because the current options do not have install/prefix parameters.

You can keep option.save, but pass the verbose/diagnosis option additionally.

**Comment by SirLynix** [comment]
Alright, but it's not in the install script, it's in the install_admin script, which exists only for the purpose of being called from another xmake instance, that's what I didn't understand.

However I will use your solution, it feels cleaner.

**Comment by waruqi** [comment]
> Alright, but it's not in the install script, it's in the install_admin script, which exists only for the purpose of being called from another xmake instance, that's what I didn't understand.
> 
> However I will use your solution, it feels cleaner.

task.run can also call all actions without other xmake process instances.
