### ISSUE TITLE
add_files cannot deal with too many files

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1600]
### 描述问题

当文件数过多的时候add_files会挂：
```
target("lib")
    add_files("a/a.cpp",
              "a/b.cpp",
              ... (200~300个文件)
              )
    ...
```
必须分组添加才能正常编译

### 期待的结果

可以让add_files处理数量更多的文件，或者给出更合适的错误提示

### 错误信息

```console
./xmake.lua:4: function or expression too complex near '"Source/OpenEXR/IlmImf/ImfDoubleAttribute.cpp"'
```

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.6
- xmake运行平台：linux
- xmake目标平台：linux

### 其他信息

[xmake.lua.txt](https://github.com/xmake-io/xmake/files/7031012/xmake.lua.txt)

**Comment by waruqi** [comment]
这应该是 lua 的 函数参数限制，似乎最大只能 256 个，不光 luajit，lua 上似乎也是有这个限制：http://lua-users.org/lists/lua-l/2010-07/msg00526.html

尽量不要在一个 `add_files()` 里面加太多文件，可以拆分到不同的 `add_files` 里面去做，我测试过，每次 `add_files` 一个文件，可以添加超过 500 个的列表，而且这样效率更高，因为直接追加到 table 中的。

 > 可以让add_files处理数量更多的文件，或者给出更合适的错误提示

这个提示也是给不了的，因为 xmake.lua 自身加载解析时候，lua 就报错了，只能有 lua 给的错误提示，这个阶段，xmake内部是无法根据这仅有的错误，定位确定是参数过大导致，还是其他地方的语法错误导致。

**Comment by waruqi** [comment]
另外，如果你非要在 一个 add_files 里面加，不想拆分到不同的 add_files，也有个 workaround 方案，那就是加个 `{}` 去 wrap 下所有参数，变成一个 table 参数传入 add_files，也可以绕过限制

```lua
add_files({"file1.c", "file2.c", "file3.c", "...."})
```

**Comment by xq114** [comment]
使用table确实可以
