### ISSUE TITLE
issues on mixing packages built with different toolchain

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1601]
### 你在什么场景下需要该功能？

举例：
- 使用gcc-10编译的库如果带有C++ ABI，则大概率无法和gcc-4.8编译的库相互链接；
- 使用clang toolchain编译并链接到libc++的库无法链接到gcc+libstdc++的项目；
- msvc2019编译的库在msvc2017下可能用不了，等等。

目前xmake对已安装的package仅按plat+arch+config做了区分，没有按编译时使用的toolchain进行区分，这就使得单机多toolchain环境、在不同机器间使用xrepo import/export转移package时出现链接问题。

这个问题在使用C++接口的库里面比较常见，对于C API的库基本没有兼容性问题。

另一个问题是某些package（例如google的filament，intel的open3d）只支持clang不支持gcc（用到libc++的特性），这个无法在package描述文件里面检测，如果能在安装package时存储toolchain信息则也可以把toolchain检测的问题也解决。

### 描述可能的解决方案

[Spack](https://spack.io/)的解决办法是所有的package都按照toolchain分类放好。spack会存储机器上存在的toolchain（由用户指定，提供`spack compiler find`简化指定过程）：
```
$ spack compilers
==> Available compilers
-- gcc ---------------------------------------------------------
    gcc@4.9.0  gcc@4.8.0  gcc@4.7.0  gcc@4.6.2  gcc@4.4.7
-- intel -------------------------------------------------------
    intel@15.0.0  intel@14.0.0  intel@13.0.0  intel@12.1.0  intel@10.0
-- clang -------------------------------------------------------
    clang@3.4  clang@3.3  clang@3.2  clang@3.1
```
在查找package时明确指出编译时使用的plat/arch/toolchain：
```
$ spack find
==> 74 installed packages.
-- linux-debian7-x86_64 / gcc@4.4.7 --------------------------------
ImageMagick@6.8.9-10  libdwarf@20130729  py-dateutil@2.4.0
adept-utils@1.0       libdwarf@20130729  py-ipython@2.3.1
...
-- linux-debian7-x86_64 / gcc@4.9.2 --------------------------------
libelf@0.8.10  mpich@3.0.4
```

### 描述你认为的候选方案

xmake可以不必照搬spack的解决办法。首先并不是所有的toolchain之间都互不相容，其次xmake有tag机制（hdf5~clang10），因此可以让用户来决定使用package时的toolchain。因此只需要在安装package的时候存储编译时的toolchain类型，在当前项目中toolchain可能冲突时提出warning（无法识别的自定义toolchain可以不做此检测）。某些package是直接从网站下载的预编译文件，这类package则在下载时可以设置一个toolchain，此toolchain与本地环境无关。其余冲突检测类似。

另外，如何在xmake.lua中获取使用的toolchain并根据toolchain启用不同的package？

**Comment by waruqi** [comment]
这块比较复杂，xmake每次参与包编译生效的可能不一定只有一个toolchain，也有可能多个组合的结果，尽管大部分case都只需要一个，而且不同工具链的兼容性检测也不太好搞，之前搞一个vs的兼容性就已经很蛋疼了。

暂时我就不搞了，先放着吧，最近也没啥时间，只能用户自己约束下自己在不同设备上的工具链保持兼容。

> 另外，如何在xmake.lua中获取使用的toolchain并根据toolchain启用不同的package？

target:toolchains() 能获取到当前针对target生效的所有工具链，有可能同时生效多个，如果要判断特定 cc/cxx/ld 用了那个，需要根据 target:tool("cxx") 获取。

**Comment by waruqi** [comment]
这块先自己约定下工具链吧，暂时不搞了，过于复杂
