### ISSUE TITLE
xmake cannot  find the boost installed using vcpkg

### ISSUE THREAD

**Issue by qiuwei** [xmake-io/xmake#1605]
### Describe the bug
xmake cannot find boost installed by vcpkg. However,  the installation of boost also fails due to that  Package boost:x64-linux is already installed.

### Expected behavior
The installed boost should be found

### Error output

checking for gcc ... /usr/bin/gcc
checking for dmd ... no
checking for ldc2 ... no
checking for gdc ... no
checking for zig ... no
checking for zig ... no
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
checking for vcpkg::boost ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
in vcpkg:
  -> vcpkg::boost latest
please input: y (y/n/m)
y
checking for vcpkg ... /home/wqiu/Projects/vcpkg/vcpkg
/home/wqiu/Projects/vcpkg/vcpkg install boost:x64-linux
Computing installation plan...
The following packages are already installed:
    boost[core]:x64-linux -> 1.76.0
Package boost:x64-linux is already installed

Total elapsed time: 20.15 us

checking for vcpkg::boost ... no

error: fetch vcpkg::boost-latest failed!
  => install vcpkg::boost latest .. failed
error: install failed!

### Related Environment

- xmake version: v2.5.6+202108241727 
- os: Ubuntu 20.04
- target platform: x64-linux

**Comment by waruqi** [comment]
see https://github.com/xmake-io/xmake/issues/1585#issuecomment-901774386

**Comment by waruqi** [comment]
> checking for vcpkg::boost[core] ... no

vcpkg::boost[core] not found, you can debug https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/manager/vcpkg/find_package.lua

**Comment by qiuwei** [comment]
> > checking for vcpkg::boost[core] ... no
> 
> vcpkg::boost[core] not found, you can debug https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/manager/vcpkg/find_package.lua

Could you explain a bit more about how I could debug this? Do I simply run it as a lua script?

**Comment by waruqi** [comment]
clone xmake source code to xmakesrc dir

switch to local xmake lua scripts

```lua
export XMAKE_PROGRAM_DIR=/your/xmakesrc/xmake
```

create an project with vcpkg packages

then run

xmake f -c -vD


edit vcpkg/find_package.lua and ads print logs to debug it.

**Comment by qiuwei** [comment]
Cool ! saved my day!  many thanks!
