### ISSUE TITLE
The actual downloading url is not printed when '-v -D' flags are not specified

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1608]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
当运行`xmake`时，即使声明了proxy_pac，但显示的还是从github原始地址下载：
```
=> download https://github.com/Kitware/CMake/releases/download/v3.21.0/cmake-3.21.0-linux-x86_64.tar.gz .. ok
```
只有运行`xmake -vD`的时候才显示正确的下载地址：
```
/usr/bin/wget https://hub.fastgit.org/glennrp/libpng/archive/v1.6.37.zip -U "Xmake/2.5.6+202108161610 (Linux;5.10.0-8-amd64) wget/1.21" -O v1.6.37.zip
--2021-08-26 16:27:20--  https://hub.fastgit.org/glennrp/libpng/archive/v1.6.37.zip
Connecting to 127.0.0.1:7890... connected.
Proxy request sent, awaiting response... 301 Moved Permanently
Location: https://endpoint.fastgit.org/https://github.com/glennrp/libpng/archive/v1.6.37.zip [following]
--2021-08-26 16:27:21--  https://endpoint.fastgit.org/https://github.com/glennrp/libpng/archive/v1.6.37.zip
```
这里打印的下载地址应该改成经过proxy_pac处理后的真实下载地址，一来避免误解，二来下载失败的时候也方便用户手动下载。

**Comment by xq114** [comment]
现在下载成功的提示正确了，下载失败的提示还是mirror之前的
```
=> download https://github.com/mosra/magnum/archive/refs/tags/v2020.06.tar.gz .. failed
```

**Comment by xq114** [comment]
失败的错误提示是
```
ERROR: Can not create symbolic link : A required privilege is not held by the client. : source.tmp\magnum-2020.06\.travis.yml
```
windows系统，解压文件为.tar.gz格式。不知道是否与这个有关

**Comment by waruqi** [comment]
可能是，tar.gz 保留了 symlink 。。win上创建 symlink 似乎要 管理员权限才行。

**Comment by xq114** [comment]
> 可能是，tar.gz 保留了 symlink 。。win上创建 symlink 似乎要 管理员权限才行。

windows上默认用的zip是不保留symlink的，xmake在解压tgz的时候也可以在windows上忽略symlink。问题在download fail之后显示的url不是真实用到的url

**Comment by waruqi** [comment]
改了

**Comment by xq114** [comment]
没搜到7z有这个功能，这里先把tarball改成zip了，每次要管理员权限运行太麻烦

https://github.com/xmake-io/xmake-repo/pull/616

**Comment by waruqi** [comment]
也可以试下 excludes 这个功能 https://github.com/xmake-io/xmake-repo/blob/5e74602ba3894e37b96300068862cdfc36e075fa/packages/o/openssl/xmake.lua#L8

解压时直接忽略指定文件
