### ISSUE TITLE
分支名为“xx/yy”时，无法正常获取依赖包

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#1617]
依赖包使用“xx/yy”形式时，xmake 2.5.6 开始无法获取依赖包

复现如下 （下面私有仓里的pybind11已经修改为只有git地址没有版本信息，fork的pybind11已经增加了 release/2.7.0 分支）：
xmake create -P ./hello
修改 xmake.lua 增加私有仓和依赖库：
add_repositories("my-repo https://github.com/fasiondog/xmake-repo.git")
add_requires("pybind11 release/2.7.0", {system = false})
（注：改为 master 分支，可正常安装）

编译错误信息如下（xmake 2.5.6）：
error: @programdir\core\main.lua:279: @programdir\core\sandbox\modules\import\core\base\task.lua:65: @programdir\modules\private\action\require\impl\package.lua:328: package(pybind11): version(release/2.7.0) not found!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:829]: in function 'raise'
    [@programdir\modules\private\action\require\impl\package.lua:328]: in function '_select_package_version'
    [@programdir\modules\private\action\require\impl\package.lua:701]: in function '_load_package'
    [@programdir\modules\private\action\require\impl\package.lua:785]: in function '_load_packages'
    [@programdir\modules\private\action\require\impl\package.lua:983]: in function 'load_packages'
    [...modules\private\action\require\impl\install_packages.lua:524]: in function 'install_packages'
    [@programdir\modules\private\action\require\install.lua:85]: in function 'install_packages'
    [@programdir\actions\config\main.lua:408]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:519]: in function 'run'
    [@programdir\core\sandbox\modules\import\core\base\task.lua:63]: in function 'run'
    [@programdir\actions\build\main.lua:113]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:519]: in function 'run'
    [@programdir\core\main.lua:277]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:365]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:829: in function 'raise'
        @programdir\core\main.lua:279: in function 'cotask'
        @programdir\core\base\scheduler.lua:365: in function <@programdir\core\base\scheduler.lua:362>

=======================================================
完整的xmake.lua如下
add_rules("mode.debug", "mode.release")

add_repositories("my-repo https://github.com/fasiondog/xmake-repo.git")
add_requires("pybind11 release/2.7.0", {system = false})
--add_requires("pybind11 master", {system = false})

target("hello")
    set_kind("binary")
    add_files("src/*.cpp")

    add_packages("pybind11")

**Comment by waruqi** [comment]
再试试

**Comment by waruqi** [comment]
=> install pybind11 release/2.7.0 .. ok

我可以的么，都编过了。

**Comment by fasiondog** [comment]
![图片](https://user-images.githubusercontent.com/1145161/131348684-d739c275-0b18-4cc3-af88-f4b760c5e2e3.png)

**Comment by waruqi** [comment]
这个看版本没用，core binary 不变，版本不会变，我只更新了 lua 脚本。。`xmake update -s dev`

**Comment by fasiondog** [comment]
可以了，多谢
