### ISSUE TITLE
error: wait events in poller failed!

### ISSUE THREAD

**Issue by chenbingkun55** [xmake-io/xmake#1626]
### Describe the bug
在Window 10 i7 环境可以正常编译， 服务器 Amd 3960x-24 编译 protobuf-3.17.3 报错。

### Error output
[  0%]: compiling.release protobuf-3.17.3\google\protobuf\util\internal\json_stream_parser.cc
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\cl.exe" -c /EHsc -nologo -Ox -fp:fast -std:c++17 -Iprotobuf-3.17.3 -INetwork\GenerateProto -I..\BattleSystem\Include -I..\BattleSystem\BattleLogic -DCPPDLL_EXPORTS -DNDEBUG -Fobuild\.objs\BattleSystem\windows\x64\release\protobuf-3.17.3\google\protobuf\util\internal\json_stream_parser.cc.obj protobuf-3.17.3\google\protobuf\util\internal\json_stream_parser.cc
[  0%]: compiling.release protobuf-3.17.3\google\protobuf\util\internal\object_writer.cc
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\cl.exe" -c /EHsc -nologo -Ox -fp:fast -std:c++17 -Iprotobuf-3.17.3 -INetwork\GenerateProto -I..\BattleSystem\Include -I..\BattleSystem\BattleLogic -DCPPDLL_EXPORTS -DNDEBUG -Fobuild\.objs\BattleSystem\windows\x64\release\protobuf-3.17.3\google\protobuf\util\internal\object_writer.cc.obj protobuf-3.17.3\google\protobuf\util\internal\object_writer.cc
[  0%]: compiling.release protobuf-3.17.3\google\protobuf\util\internal\protostream_objectsource.cc
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\cl.exe" -c /EHsc -nologo -Ox -fp:fast -std:c++17 -Iprotobuf-3.17.3 -INetwork\GenerateProto -I..\BattleSystem\Include -I..\BattleSystem\BattleLogic -DCPPDLL_EXPORTS -DNDEBUG -Fobuild\.objs\BattleSystem\windows\x64\release\protobuf-3.17.3\google\protobuf\util\internal\protostream_objectsource.cc.obj protobuf-3.17.3\google\protobuf\util\internal\protostream_objectsource.cc
[  0%]: compiling.release protobuf-3.17.3\google\protobuf\util\internal\protostream_objectwriter.cc
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\cl.exe" -c /EHsc -nologo -Ox -fp:fast -std:c++17 -Iprotobuf-3.17.3 -INetwork\GenerateProto -I..\BattleSystem\Include -I..\BattleSystem\BattleLogic -DCPPDLL_EXPORTS -DNDEBUG -Fobuild\.objs\BattleSystem\windows\x64\release\protobuf-3.17.3\google\protobuf\util\internal\protostream_objectwriter.cc.obj protobuf-3.17.3\google\protobuf\util\internal\protostream_objectwriter.cc
[  0%]: compiling.release protobuf-3.17.3\google\protobuf\util\internal\proto_writer.cc
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\cl.exe" -c /EHsc -nologo -Ox -fp:fast -std:c++17 -Iprotobuf-3.17.3 -INetwork\GenerateProto -I..\BattleSystem\Include -I..\BattleSystem\BattleLogic -DCPPDLL_EXPORTS -DNDEBUG -Fobuild\.objs\BattleSystem\windows\x64\release\protobuf-3.17.3\google\protobuf\util\internal\proto_writer.cc.obj protobuf-3.17.3\google\protobuf\util\internal\proto_writer.cc
**error: wait events in poller failed!**

### Related Environment

Please provide compiling and running environment information:

- xmake version: xmake v2.5.4+202105150825
- os: window
- target platform: window dll

**Comment by waruqi** [comment]
多少 cpu core ，感觉core太多了，默认并行编译数太多导致。要么你限制下 jobs 试试，xmake -j1 或者 xmake -j12 调低点

**Comment by chenbingkun55** [comment]
好的， 24 线直接编过不了， 
用 xmake -j24 可以了，谢谢。

**Comment by waruqi** [comment]
-j24

**Comment by waruqi** [comment]
我会进一步修一下这个问题，具体到 https://github.com/xmake-io/xmake/issues/1640 这里跟进。

**Comment by waruqi** [comment]
你更新到 dev 再试试，我改进过了，可以放开到更多的 jobs 

xmake update dev
