### ISSUE TITLE
Env vars from fetch-only packages are not loaded to virtual environment

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1628]
### 描述问题

使用xmake编译cuda程序，希望在venv里面加载nvcc；

https://github.com/xmake-io/xmake-repo/blob/68f1c58a37dee94ab2c7ad13a3b19c546143fbaa/packages/c/cuda/xmake.lua#L15

这里应该写`add_requires("cuda", {system=true})`就可以加载cuda的环境变量的，但实际运行时报错找不到nvcc

### 期待的结果

`xrepo env shell`可以正常加载cuda环境变量

### 错误信息

```console
$ xrepo env shell
$ nvcc -h
bash: nvcc: command not found
```

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.7
- xmake运行平台：Debian 11
- xmake目标平台：linux x86_64

### 其他信息
![image](https://user-images.githubusercontent.com/42310255/131794327-3376688e-310b-4b7b-a1c7-6a1d60d8a816.png)

**Comment by waruqi** [comment]
on_fetch 里加 path 没用

on_install 里面加 path 可以存储到 manifest 中恢复，on_fetch only 包，不会实际安装，所有取不到的，你只有放到 on_load 里面去加
