### ISSUE TITLE
support finding package from cmake

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1632]
### 你在什么场景下需要该功能？

使用cmake的find_package获取外部依赖。一来有些库默认提供cmake，并且是高度自定义的cmake，较难使用xmake package集成；二来一些cmake script可以直接从之前的库copy，无需重写+测试

这项功能meson已经提供 https://mesonbuild.com/Dependencies.html#cmake ，实现的源代码在 https://github.com/mesonbuild/meson/blob/HEAD/mesonbuild/dependencies/cmake.py ，大致思路是用cmake生成一个临时工程，然后解析CMakeCache里生成的flags。

不过xmake中引入cmake的package还不太方便，因为与系统包不同，cmake有组件系统（find_package同时找寻多个组件，最后链接的implib可能是其中某个组件；同时链接可能是${FOO_LIBRARIES}变量也可能是foo::foo target），并且cmake在find_package前往往需要一些preset variables。xmake直接`add_requires("cmake::foo")`是无法处理这么多因素的，需要设计一下

### 描述可能的解决方案

```
add_requires("cmake::Boost", {configs={
    version="1.75",
    include_directories="${Boost_INCLUDE_DIRS}"
    link_libraries="Boost::filesystem Boost::system",
    presets=format("set(Boost_USE_STATIC_LIBS %s)\nset(Boost_USE_STATIC_RUNTIMES %s)",
                   is_kind("static") and "ON" or "OFF",
                   vsruntime:startswith("MT") and "ON" or "OFF")}})
```
这种方案对内置的cmake package奏效，但在比较复杂的情况下（cmake需要引入一些外部模块），在presets变量中声明外部模块会比较困难。

### 描述你认为的候选方案

```
-- filesystem
cmake/FindABC.cmake
xmake/template.cmake
xmake.lua
```

```
# template.cmake
add_cmake_modules(${CMAKE_CURRENT_LIST_DIR}/../cmake)
...# (set variables or setting up vcpkg or doing some other operations)
find_package(ABC REQUIRED)
add_library(myproj-ABC ${XMAKE_KIND} ${XMAKE_SOURCES})
target_link_libraries(myproj-ABC ABC::ABC1 ABC::ABC3)
```

```
-- xmake.lua
add_requires("cmake::ABC13", {template="xmake/template.cmake", target="myproj-ABC"})
...
add_packages("ABC13")
```

Related issues: https://github.com/xmake-io/xmake/issues/1086#issuecomment-939515425

**Comment by waruqi** [comment]
还是走 package() + on_fetch + add_configs + cmake 辅助脚本就好些。。还可以对现有包直接做 fetch 增强。。对上层 add_requires() 也不需要特殊配置什么，用户使用成本更低

毕竟不同包， cmake 提供的 findxxx.cmake 差异很大，放到 package() 里面更能定制化分别处理

而 add_configs 正好也能支持组件式 find 在 on_fetch 里面。。

只需要搞个 `import("package.tools.cmake").find_package` 的辅助脚本在 on_fetch 里面调用，里面可以做你说的 创建个临时 cmake 工程来提取 包信息，各种定制化参数 和 preset 也可以这里传递。。

毕竟这种定制化传参对用户来说要求和成本过高，而对于包制作者，就无所谓了。

**Comment by waruqi** [comment]
不过这个最近没时间搞，先排着吧

**Comment by waruqi** [comment]
不过现在还有一些问题：

有些包 cmake 获取到的 links 是 Boost::regex Boost::system 这种的，不是真实库名，暂时不支持

这个怎么取到真实 lib 名呢？ 有些 CMakeCache.txt 都没有这些信息

还有 win 上还没测试，仅仅测试了 macOS/linux， win上可以帮忙测试和改进下

https://github.com/xmake-io/xmake/blob/dev/xmake/modules/package/manager/cmake/find_package.lua

**Comment by xq114** [comment]
meson是建立了一个phony target，然后取这个target的link.txt，而不是单一个`find_package`语句，后者会找不到真实库名

**Comment by waruqi** [comment]
> 这个接口可以设置preset吗？

preset 是啥？

**Comment by waruqi** [comment]
> meson是建立了一个phony target，然后取这个target的link.txt，而不是单一个`find_package`语句，后者会找不到真实库名

这种我也想过，主要是想探测快点，搞个 target  cmake 还会去额外探测各种编译器环境啥的额，生成工程文件

**Comment by waruqi** [comment]
> > 我加上了
> > ```lua
> > find_package("cmake::Boost", {components = {"regex", "system"}, presets = {USE_STATIC_LIB = true}})
> > ```
> 
> > 哦，各种提前设置的开关哈，有命名要求么。。Boost_xxx格式? 还是随意的？
> 
> 没有命名要求，是随意的，这里还是用全名好

改了

**Comment by waruqi** [comment]
比如查找 Qt5 的库

```lua
$ xmake l find_package cmake::Qt5Widgets
{ 
  linkdirs = { 
    "/usr/lib/x86_64-linux-gnu" 
  },
  defines = { 
    "QT_CORE_LIB",
    "QT_GUI_LIB",
    "QT_NO_DEBUG",
    "QT_WIDGETS_LIB" 
  },
  links = { 
    "Qt5Widgets",
    "Qt5Gui",
    "Qt5Core" 
  },
  libfiles = { 
    "/usr/lib/x86_64-linux-gnu/libQt5Widgets.so",
    "/usr/lib/x86_64-linux-gnu/libQt5Gui.so",
    "/usr/lib/x86_64-linux-gnu/libQt5Core.so" 
  },
  includedirs = { 
    "/usr/include/x86_64-linux-gnu/qt5",
    "/usr/include/x86_64-linux-gnu/qt5/QtWidgets",
    "/usr/include/x86_64-linux-gnu/qt5/QtGui",
    "/usr/include/x86_64-linux-gnu/qt5/QtCore",
    "/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++" 
  } 
}
```

**Comment by xq114** [comment]
> > 另外还应该支持强制使用config查找，不用内置的FindXXX.cmake，对应语句`find_package(<package> CONFIG REQUIRED)`
> 
> CONFIG 是用来干什么的？ 强制走自己的 modules 里面的 findXXX.cmake ？那如果设置了 moduledirs 参数，我就默认启用 config 呢？

强制走XXXConfig.cmake/XXX-config.cmake，忽略所有FindXXX.cmake，moduledirs自然也就失效了

**Comment by waruqi** [comment]
> 另外还应该支持强制使用config查找，不用内置的FindXXX.cmake，对应语句`find_package(<package> CONFIG REQUIRED)`

自己 presets 里面开启这个优先走 config me？
https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_PACKAGE_PREFER_CONFIG.html#variable:CMAKE_FIND_PACKAGE_PREFER_CONFIG

**Comment by xq114** [comment]
> > 另外还应该支持强制使用config查找，不用内置的FindXXX.cmake，对应语句`find_package(<package> CONFIG REQUIRED)`
> 
> 自己 presets 里面开启这个优先走 config 呢？ [cmake.org/cmake/help/latest/variable/CMAKE_FIND_PACKAGE_PREFER_CONFIG.html#variable:CMAKE_FIND_PACKAGE_PREFER_CONFIG](https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_PACKAGE_PREFER_CONFIG.html#variable:CMAKE_FIND_PACKAGE_PREFER_CONFIG)

这个也行

**Comment by waruqi** [comment]
windows 上也支持了，presets 之前有点问题，也修复了

**Comment by waruqi** [comment]
我改进了下 https://github.com/xmake-io/xmake/pull/1917

直接用 find_package 还是过于底层，对于用户集成包，还是统一走 add_requires 比较好，之前虽然也有直接在 
add_requires 中使用 cmake:: 包，但是无法透传 configs ，现在可以了。

```lua
add_requires("cmake::ZLIB", {alias = "zlib", system = true})
target("test")
    set_kind("binary")
    add_files("src/*.c")
    add_packages("zlib")
```

```lua
add_requires("cmake::Boost", {system = true, configs = {components = {"regex", "system"},
                                         presets = {Boost_USE_STATIC_LIB = true}})}
```

更新后的文档见：https://xmake.io/#/zh-cn/package/local_package?id=%e5%9c%a8%e9%a1%b9%e7%9b%ae%e4%b8%ad%e9%9b%86%e6%88%90%e5%8c%85

**Comment by xixioba** [comment]
@waruqi 
我遇到了Cmake预编译库导入问题，对应`find_package` [search mode](https://cmake.org/cmake/help/latest/command/find_package.html#basic-signature)，具体为移植以下
```
SET(fastcdr_DIR lib/cmake/fastcdr)
SET(fastrtps_DIR share/fastrtps/cmake)

# Find requirements
if(NOT fastcdr_FOUND)
    find_package(fastcdr REQUIRED)
endif()

if(NOT fastrtps_FOUND)
    find_package(fastrtps REQUIRED)
endif()
```
参考并编写xmake如下：
<img width="702" alt="截屏2022-04-22 21 03 34" src="https://user-images.githubusercontent.com/34228625/164720506-e1abe176-01bc-42b0-aeef-c53f56d456b1.png">
目录路径如下：
<img width="437" alt="截屏2022-04-22 20 54 19" src="https://user-images.githubusercontent.com/34228625/164720482-610411c9-4d4b-4f23-b87e-a6b32f7a7599.png">
注释是我参考并做的一些尝试（也测试过绝对路径），均没有生效，编译提示无法找到(已使用`xmake update -s dev`更新)。
对于没有FindXXX.cmake的库，仅有xxx-config.cmake，该怎么导入呢
