### ISSUE TITLE
Dependent target fails to add files from earlier target

### ISSUE THREAD

**Issue by kneeko** [xmake-io/xmake#1634]
### Describe the bug
I am adding some code generation in my project that involves two phases where the output of one phase is supplied to a second phase. When I build the targets one by one in sequence, I get the output I expect (two files, `target_1_output.txt` and `target_2_output.txt`, but when I build them together the second target fails to add the input of the first.

### Expected behavior
The same output as when building the targets together: two output files, `build/target_1_output.txt` and `build/target_2_output.txt`.

### Error output
`warning: cannot match target(target_2).add_files("build/target_1_output.txt") at .\xmake.lua:25`

### Related Environment
Create a file `target_1_input.txt` with any contents, and then build with the following xmake setup:
```set_config("buildir", "build")
set_policy("build.across_targets_in_parallel", false)

rule("target_1_rule")
	set_extensions(".txt")
	before_buildcmd_file(function (target, batchcmds, sourcefile, opt)
		io.writefile("$(buildir)/target_1_output.txt", "")
	end)

rule("target_2_rule")
	set_extensions(".txt")
	before_buildcmd_file(function (target, batchcmds, sourcefile, opt)
		io.writefile("$(buildir)/target_2_output.txt", "")
	end)

target("target_1")
	set_kind("binary")
	add_files("target_1_input.txt", { rule = "target_1_rule" })
	-- override link step since this target doesn't produce object files
	on_link(function(target) end)

target("target_2")
	set_kind("binary")
	add_deps("target_1")
	add_files("$(buildir)/target_1_output.txt", { rule = "target_2_rule", always_added = true})
	-- override with no-op link step since this target doesn't produce object files
	on_link(function(target) end)
```
	
Then run `xmake` to reproduce the issue.

If you delete the build contents and manually build the targets in the correct order both output files will be produced.
```
xmake b target_1
xmake b target_2
```

- xmake version: xmake v2.5.6+202107260800
- os: Version 10.0.19043
- target platform: Windows

### Additional context
Perhaps a separate issue, I am unsure what the appropriate target kind is for running tools like this when there is a dependency chain and it is insufficient to specify them as prebuild steps for some other target. I wound up using `binary` with an overridden link step (otherwise the linker will fail) instead of `objects` (which seemed like it would skip the link step to begin with, but produces the error `error: no suitable linker for object.{}` when generating a visual studio project using `xmake project -k vsxmake`). `phony` seems to not be intended for this either.

**Comment by waruqi** [comment]
I have fixed it on dev. please run `xmake update -s dev` and try it again.

**Comment by kneeko** [comment]
Can confirm this solves the issue. Thank you!
