### ISSUE TITLE
Automatically generated pkg-config files containing incorrect flags

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1635]
### 描述问题

![image](https://user-images.githubusercontent.com/42310255/131955033-f0d408b5-f9ad-4ad6-8606-5693e8c044cc.png)
如图所示，xmake生成的.pc中libs的flag黏在一起了

### 期待的结果

在pkgconfig文件中生成正确的flags

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.7
- xmake运行平台：linux
- xmake目标平台：linux

**Comment by waruqi** [comment]
再试试 dev
