### ISSUE TITLE
Windows: wait events in poller failed

### ISSUE THREAD

**Issue by bionicbeagle** [xmake-io/xmake#1640]
### Describe the bug

I am evaluating xmake for a project and am hitting an issue when compiling on Windows. Basically, it seems like xmake will only handle a certain degree of concurrency due to limitations in polling. This causes an issue when building on a Threadripper 3990x machine with 128 logical processors (xmake will default to 192 maximum parallel jobs)

Issuing `xmake -j 64` fails. It is possible to work around the issue by issuing `xmake -j 63` which avoids the limit which I assume is related to `FD_SETSIZE` which defaults to 64 on Windows. Perhaps xmake needs to be recompiled with a higher `FD_SETSIZE` limit?

### Expected behavior

The build should complete correctly regardless of parallelism

### Error output

The process terminates with the following error:

`error: wait events in poller failed!`

### Related Environment

Please provide compiling and running environment information:

- xmake version: xmake v2.5.7+202108290428
- os: Windows 10 20H2
- target platform: Windows/x64

**Comment by SirLynix** [comment]
If the issue comes from select, WSAPoll/IOCP and poll/epoll/kqueue should be considered instead

**Comment by waruqi** [comment]
I will look at it. related issue: https://github.com/xmake-io/xmake/issues/1626

**Comment by waruqi** [comment]
xmake use WaitForMultipleObjects, it fails

https://github.com/tboox/tbox/blob/379400c529b197be74664acfec99cca42896184e/src/tbox/platform/windows/poller_process.c#L149

**Comment by waruqi** [comment]
https://stackoverflow.com/questions/5136775/increasing-maximum-wait-objects-for-waitformultipleobjects

MAXIMUM_WAIT_OBJECTS is limited <= 64

**Comment by xq114** [comment]
Maybe it's better using threads instead of processes

**Comment by waruqi** [comment]
ninja use iocp + pipe 

https://github.com/ninja-build/ninja/blob/ce700488e01af33bc478bc986e261e306180b993/src/subprocess-win32.cc

**Comment by waruqi** [comment]
I have fixes it on dev. please try it again.

xmake update dev

**Comment by bionicbeagle** [comment]
I just tried it -- I can confirm that it appears to have solved the problem! I see the following in the log where it used to fail:

`[tbox]: [poller]: process: grow loop threads to 2`

Thanks for the quick turnaround!

**Comment by waruqi** [comment]
> [tbox]: [poller]: process: grow loop threads to 2

It only is debug log, I have removed it.

**Comment by waruqi** [comment]
I think this is already working, if there are other questions, please reopen it
