### ISSUE TITLE
Can not debug code  with xmake use VS toolchain but mysql's c++ code can run 

### ISSUE THREAD

**Issue by kkonghao** [xmake-io/xmake#1642]
### Describe the bug
Hello,when I use xmake vs 2019 toolchain and installed mysql server to run c++ code ,my c++ code can run correctly,but when i debug some code,xmake can’t debug. Is my fault and config wrong?

### Expected behavior
xmake can debug c++ mysql code

### Error output
No Error output 

xmake -v -D  info :
![image](https://user-images.githubusercontent.com/57028687/132174801-83b8e75b-cfcf-4b75-bcd0-2dbe4178f38c.png)

### Related Environment

Please provide compiling and running environment information:

- xmake version:xmake v2.5.7
- os: Windows 10
- target platform:Windows 10

### Additional context

xmake.lua 
```xmake
add_rules("mode.debug")

target("ssq")
    set_kind("binary")
    add_files("src/*.cpp")
    add_includedirs("C:\\Program Files\\MySQL\\MySQL Server 8.0\\include")
    add_links("libmysql","mysqlclient")
    add_linkdirs("C:\\Program Files\\MySQL\\MySQL Server 8.0\\lib")
```

main.cpp

```C++
#include <iostream>
#include "mysql.h"

using namespace std;

int main(int argc, char** argv)
{

    MYSQL mysql;

    mysql_init(&mysql);
    const char *host = "127.0.0.1";
    const char *user = "root";
    const char *pwd = "000000";
    const char* db = "world";
    
    if (!mysql_real_connect(&mysql, host, user, pwd, db, 3306, 0, 0))
    {
        cout << "mysql connected failed, " << mysql_error(&mysql) << endl;
    }
    else
    {
        cout << "mysql connected success" << endl;
    }

    MYSQL_RES *res;
    MYSQL_ROW row; 
    const char *sql = "select * from world.city where city.ID<=10";

    mysql_query(&mysql, sql);

    res = mysql_store_result(&mysql);

    while (row = mysql_fetch_row(res))
    {
        cout << row[0] << " ";
        cout << row[1] << endl;
    }

    mysql_free_result(res);
    mysql_close(&mysql);
    return 0;
}
```

Thanks for your consider

**Comment by waruqi** [comment]
run `xmake run -d` to launch vs debugger or run `xmake project -k vsxmake` to generate vs project to debug it.

**Comment by kkonghao** [comment]
> run `xmake run -d` to launch vs debugger or run `xmake project -k vsxmake` to generate vs project to debug it.

yes use    xmake project -k vsxmake      can debug in Visual Studio IDE but Vscode can't

**Comment by SirLynix** [comment]
> yes use xmake project -k vsxmake can debug in Visual Studio IDE but Vscode can't

Is there a reason you're using VSCode instead of VS Studio on Windows?

Have you tried [xmake-vscode](https://marketplace.visualstudio.com/items?itemName=tboox.xmake-vscode) extension?

**Comment by kkonghao** [comment]
> You need to run `xmake f -m debug` before running `xmake` or debug symbols won't be added

thanks for your help,@xq114,actually I have obtain Xmake debug rule 
![image](https://user-images.githubusercontent.com/57028687/132179889-794f925e-7fb8-4131-9773-d86ba929d3fb.png)
change debug mode ->rebuild ->debug and I used your advice there is no result like before

**Comment by kkonghao** [comment]
> > yes use xmake project -k vsxmake can debug in Visual Studio IDE but Vscode can't
> 
> Is there a reason you're using VSCode instead of VS Studio on Windows?
> 
> Have you tried [xmake-vscode](https://marketplace.visualstudio.com/items?itemName=tboox.xmake-vscode) extension?

I have download xmake plugin before writing code.

**Comment by waruqi** [comment]
> > run `xmake run -d` to launch vs debugger or run `xmake project -k vsxmake` to generate vs project to debug it.
> 
> yes use xmake project -k vsxmake can debug in Visual Studio IDE but Vscode can't

you need install c++ plugin or codelldb plugin on macOS in vscode.

**Comment by kkonghao** [comment]
> > > run `xmake run -d` to launch vs debugger or run `xmake project -k vsxmake` to generate vs project to debug it.
> > 
> > 
> > yes use xmake project -k vsxmake can debug in Visual Studio IDE but Vscode can't
> 
> you need install c++ plugin in vscode.
> 
> and install xmake-vscode plugin to click bug icon.

yes i have install c++ plugin,xmake-vscode and obey xmake debug steps but doesn't work , i will push a dynamic graph for you

**Comment by kkonghao** [comment]
> > > > run `xmake run -d` to launch vs debugger or run `xmake project -k vsxmake` to generate vs project to debug it.
> > > 
> > > 
> > > yes use xmake project -k vsxmake can debug in Visual Studio IDE but Vscode can't
> > 
> > 
> > you need install c++ plugin in vscode.
> > and install xmake-vscode plugin to click bug icon.
> 
> yes i have install c++ plugin,xmake-vscode and obey xmake debug steps but doesn't work , i will push a dynamic graph for you

![GIF 2021-9-6 16-26-37](https://user-images.githubusercontent.com/57028687/132185635-912f0aa2-9667-41a2-8bde-136a91307880.gif)

**Comment by waruqi** [comment]
you need add a breakpoint in code.

**Comment by kkonghao** [comment]
> you need add a breakpoint in code first.

actually i did 
![GIF 2021-9-6 18-03-59](https://user-images.githubusercontent.com/57028687/132200176-7eb6bb2f-6f8e-4b0d-a5e9-80418140efee.gif)

**Comment by SirLynix** [comment]
I have the feeling your executable fails to start (code -107...), probably because of a missing dll. Try to copy mysql dll next to your binary.

**Comment by kkonghao** [comment]
> I have the feeling your executable fails to start (code -107...), probably because of a missing dll. Try to copy mysql dll next to your binary.
> 
> This is something xmake handles for you when using packages, see add_requires and add_packages (~there's a mysql package on xmake-repo~ it doesn't support windows actually)

yes you are right when i put libmysql file into debug directory that work, thanks a lot  bro!

**Comment by SirLynix** [comment]
You should change your password by they way 😄

**Comment by waruqi** [comment]
vscode debugger will load executable program, so some dll paths will be missing.
