### ISSUE TITLE
Customize the virtual environment

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1644]
### 你在什么场景下需要该功能？

开发c++&python project时需要设置额外的PYTHONPATH环境变量；
Windows上常常需要设置额外的PATH变量来设置.dll寻找路径；
linux需要设置一些编译器版本相关的环境变量（不同project使用不同版本编译器）；
rules中调用的第三方程序使用环境变量指定运行参数；等等

如果xmake的虚拟环境可以提供添加自定义环境变量的功能，就可以免去在所有平台编写脚本添加环境变量的烦恼了，做到一次设置到处使用。目前xmake的os.setenv并不能影响到shell中的程序。

### 描述可能的解决方案

```
option("develop")
    before_check(function (option)
        option:addenv("PATH", "...")
    end)
```

### 描述你认为的候选方案

```
-- venv.lua
function getenv(opt)
    return {PATH="..."}
end
-- xmake.lua
option("develop", {default=false})
if has_option("develop") then
    set_envfile("venv.lua")
end
```

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by waruqi** [comment]
可以自己定义个 fake `package("myenv")` 在里面的 on_load 里面加自己的各种path env，然后走 add_requries("myenv") 我想应该能生效。

**Comment by xq114** [comment]
> 可以自己定义个 fake `package("myenv")` 在里面的 on_load 里面加自己的各种path env，然后走 add_requries("myenv") 我想应该能生效。

谢谢，确实
