### ISSUE TITLE
Windows平台下无法安装xrepo中使用cmake编译的android 软件包

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#1648]
在 Win10 下安装 xrepo 中使用 cmake 编译的 android 相关软件包，无法成功，但在 linux 下没有问题。
比如：
xmake l .\scripts\test.lua -vD --shallow -p android --ndk=D:\tools\android-ndk-r23 --ndk_sdkver=21 capstone

从 xmake 的输出看，生成的 cmake 命令里带有  -G "Unix Makefiles"，导致 windows 下 cmake 报错

执行输出：
checking for cmake ... C:\Program Files\CMake\bin\cmake
C:\Program Files\CMake\bin\cmake -DCAPSTONE_BUILD_CSTOOL=ON -DCAPSTONE_BUILD_TESTS=OFF -DCAPSTONE_BUILD_STATIC=ON -DCAPSTONE_BUILD_SHARED=OFF -DCMAKE_INSTALL_PREFIX=D:\xmake\.xmake\packages\c\capstone\4.0.2\b95c1a7bd18d4c1b9f5af4cbe88202bf -DCMAKE_INSTALL_LIBDIR=D:\xmake\.xmake\packages\c\capstone\4.0.2\b95c1a7bd18d4c1b9f5af4cbe88202bf\lib -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=D:\tools\android-ndk-r23\build\cmake\android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_NATIVE_API_LEVEL=21 -DCMAKE_POSITION_INDEPENDENT_CODE=ON D:\xmake\.xmake\cache\packages\2109\c\capstone\4.0.2\source\capstone-4.0.2
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "D:/xmake/.xmake/cache/packages/2109/c/capstone/4.0.2/source/capstone-4.0.2/build_AD889E16/CMakeFiles/CMakeOutput.log".
error: @programdir\core\sandbox\modules\os.lua:392: execv(C:\Program Files\CMake\bin\cmake -DCAPSTONE_BUILD_CSTOOL=ON -DCAPSTONE_BUILD_TESTS=OFF -DCAPSTONE_BUILD_STATIC=ON -DCAPSTONE_BUILD_SHARED=OFF -DCMAKE_INSTALL_PREFIX=D:\xmake\.xmake\packages\c\capstone\4.0.2\b95c1a7bd18d4c1b9f5af4cbe88202bf -DCMAKE_INSTALL_LIBDIR=D:\xmake\.xmake\packages\c\capstone\4.0.2\b95c1a7bd18d4c1b9f5af4cbe88202bf\lib -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=D:\tools\android-ndk-r23\build\cmake\android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_NATIVE_API_LEVEL=21 -DCMAKE_POSITION_INDEPENDENT_CODE=ON D:\xmake\.xmake\cache\packages\2109\c\capstone\4.0.2\source\capstone-4.0.2) failed(1)
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:829]: in function 'raise'
    [@programdir\core\sandbox\modules\os.lua:392]: in function 'runv'
    [@programdir\core\sandbox\modules\os.lua:289]: in function 'vrunv'
    [@programdir\modules\package\tools\cmake.lua:717]: in function 'install'
    [D:\workspace\xmake-repo\packages\c\capstone\xmake.lua:18]: in function 'script'
    [...dir\modules\private\action\require\impl\utils\filter.lua:125]: in function 'call'
    [...\modules\private\action\require\impl\actions\install.lua:171]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:137]: in function 'action_install'
    [...modules\private\action\require\impl\install_packages.lua:364]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:208]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:201]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:365]:

  => install capstone 4.0.2 .. failed
error: @programdir\modules\private\async\runjobs.lua:232: ...\modules\private\action\require\impl\actions\install.lua:253: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:829]: in function 'raise'
    [...\modules\private\action\require\impl\actions\install.lua:253]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:137]: in function 'action_install'
    [...modules\private\action\require\impl\install_packages.lua:364]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:208]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:201]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:365]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:829: in function 'raise'
        @programdir\modules\private\async\runjobs.lua:232: in function 'catch'
        @programdir\core\sandbox\modules\try.lua:127: in function 'try'
        @programdir\modules\private\async\runjobs.lua:201: in function 'cotask'
        @programdir\core\base\scheduler.lua:365: in function <@programdir\core\base\scheduler.lua:362>
error: execv(xmake require -f -y --build -v -D --shallow capstone) failed(-1)

**Comment by waruqi** [comment]
更新到  dev 再试下

**Comment by fasiondog** [comment]
可以了，谢谢
