### ISSUE TITLE
Generate linux project for visual studio 2017.

### ISSUE THREAD

**Issue by EnoroF** [xmake-io/xmake#165]
We can use vs2017 to develop and debug Linux application. It is necessary to add an option to generate vs Linux project.

**Comment by EnoroF** [comment]
remote debug also support debug ios and android native application. we can also add an option to generate vs project for them.

**Comment by waruqi** [comment]
Well, I'll think about implementing them, but it may take a while.

**Comment by waruqi** [comment]
这块可以看下 https://github.com/xmake-io/xmake/pull/472  dev提供的新版vsxmake生成插件来生成vcproj。。

内部会去wrap xmake命令来编译运行，并且支持源码跳转和提示，也有单独的xmake属性页配置，用户可以在里面自己配置对应其他平台，只要win上提供了对应的工具链，生成的vs工程就可以去尝试编译linux, android, ios， 通过配置成交叉编译模式。。

```console
xmake project -k vsxmake
```

**Comment by OpportunityLiu** [comment]
这么撸出来的能用VS debug吗？先开着吧，我完了看看VS调试linux工程怎么做

**Comment by waruqi** [comment]
> 这么撸出来的能用VS debug吗？先开着吧，我完了看看VS调试linux工程怎么做

那就暂时先放到2.2.9版本好了，当前版本就不去动了。。

**Comment by tapika** [comment]
Linux projects will probably work for hello world kind of application, but not for larger ones:

https://developercommunity.visualstudio.com/content/problem/669232/linux-projects-incremental-build-does-not-recogniz.html

This item is still open and we had to switch to cmake based solution because of that.

**Comment by waruqi** [comment]
> Linux projects will probably work for hello world kind of application, but not for larger ones:
> 
> https://developercommunity.visualstudio.com/content/problem/669232/linux-projects-incremental-build-does-not-recogniz.html
> 
> This item is still open and we had to switch to cmake based solution because of that.

? xmake and `xmake project -k vsxmake` plugin support incremental build.

**Comment by OpportunityLiu** [comment]
今天调查了一下，感觉有点麻烦。。。

**Comment by waruqi** [comment]
> 今天调查了一下，感觉有点麻烦。。。

是指哪方面？

**Comment by OpportunityLiu** [comment]
他用的完全是远程生成远程调试，要把文件拷贝到远程目录操作，流程比win复杂很多

**Comment by waruqi** [comment]
也就说目前vs上开发linux都是远程的？那些放着吧 等我搞分布式编译的时候，会在xmake里面封装一套socketio 来实现一个xmake server --daemon的代理。

到时候基于xmake实现完全远程的编译运行也就方便了

**Comment by car520120** [comment]
我想使用vs2019调试 xmake 中集成 cmake 编译的工程，cmake 编译的工程需要怎么设置才能调试得到

**Comment by waruqi** [comment]
> 我想使用vs2019调试 xmake 中集成 cmake 编译的工程，cmake 编译的工程需要怎么设置才能调试得到

不要在无关的 issues 里面平台，有 bug 单独开 issues，有疑问，单独开 discusion

**Comment by waruqi** [comment]
初步把 远程编译支持了  https://github.com/xmake-io/xmake/issues/622 不过 windows 上 git/ssh 坑太多，暂时还有一个坑没解。。另外还有一些细节需要完善，不过基本可用了

**Comment by waruqi** [comment]
现在基本可以了，远程编译
