### ISSUE TITLE
第三方库使用的方法求指点

### ISSUE THREAD

**Issue by nomadfighter** [xmake-io/xmake#1652]
由于各种原因，我希望使用远程包，但是又不想弄私有仓库，所以我写的一个包是这样子的

    package("physfs")
        add_urls("https://github.com/icculus/physfs.git")
        add_versions("github", "23690f316d33f04c9f9910f6ff1c9e5cb876db07")
    
        add_deps("cmake")
    
        on_install(function(package)
            import("package.tools.cmake").install(package, 
                {"-DPHYSFS_BUILD_STATIC=ON", "-DPHYSFS_BUILD_SHARED=OFF", "-DPHYSFS_BUILD_TEST=OFF"}
            )
        end)

xmake.lua代码如下

      add_rules("mode.debug", "mode.release")
      
      add_repositories("3rd 3rd")
      
      --这里的困扰特别大，如果不指定main，就会默认master，但是physfs的git仓库又没有master分支，导致各种错误。
      --指定了branch是main，前面package里面指定的commit id似乎无法生效
      --需求是能clone指定commit id版本的代码，而不是main分支的最新代码
      add_requires("physfs main")  
      
      target("foo")
          set_kind("binary")
          add_files("src/*.cpp")
          
          add_packages("physfs")

最后运行xmake build -y
直接link error，应该是未能正确指定链接库，但是include路径似乎ok，所以问题到底是出在哪里？求教。
另外，如何使clone的代码放到本地目录，比如在.xmake目录或者build目录下，而不是跑到AppData/Local/.xmake下面。

总体上写的过程比cmake舒服太多，lua代码很好看，也相对严谨，不像cmake有些地方实在恶心。
但是资料确实有点少，google搜索基本只能搜出来什么xmake vs cmake之类的东西，具体的使用示例
几乎找不到，要不上来就是一个很大的工程。要不就是官方文档那样，给个命令说明但是又没啥上下文，比如
这个package，我的本意是想看看“如何使用第三方package”，但是官方文档上来就让我运行xmake package，

**Comment by waruqi** [comment]
>   add_versions("github", "23690f316d33f04c9f9910f6ff1c9e5cb876db07")

可以指定commiy id，但是前面必须是规范的语义版本号，比如 x.x.x，如果是git commit 你可以用commit date作为版本号比如 2021.9.6 这样才能被自动作为 latest version选择到

> 直接link error，应该是未能正确指定链接库，但是include路径似乎ok，所以问题到底是出在哪里？求教。

所以最好加个 on_test 测试验证下，这样可以在包安装阶段就提前报错，而不是编译项目的时候。

默认 xmake 会自动帮你找所有安装的 links ，但是也有例外，具体看每个包自身的情况，如果没找到 links，自己在包定义里面 add_links 手动配置上

你可以去 https://github.com/xmake-io/xmake-repo
仓库随便找几个包看看，参考下，或者加 -vD 看详情

> 这个package，我的本意是想看看“如何使用第三方package”，但是官方文档上来就让我运行xmake package，

文档有关于包的详细说明，你没找对地方，包括如何做包

https://xmake.io/#/zh-cn/package/remote_package?id=%e6%b7%bb%e5%8a%a0%e5%8c%85%e5%88%b0%e4%bb%93%e5%ba%93
