### ISSUE TITLE
树莓派安装过程报错： [/tmp/.xmake_getter15399/core/suffix.mak:309：demo.b] 错误 1

### ISSUE THREAD

**Issue by Ekkone** [xmake-io/xmake#1662]
在树莓派官方系统上使用 `bash <(curl -fsSL https://xmake.io/shget.text)
`下载，最后都会报错
`make demo
compile.r xmake.c
link demo.b
make[3]: *** [/tmp/.xmake_getter15399/core/suffix.mak:309：demo.b] 错误 1
make[2]: *** [/tmp/.xmake_getter15399/core/suffix.mak:309：SUB_PROS_demo_all] 错误 2
/usr/bin/ld: ../tbox/libtboxr.a(cache_time.o): in function `tb_cache_time_spak':
cache_time.c:(.text+0x9c): undefined reference to `__atomic_store_8'
/usr/bin/ld: ../tbox/libtboxr.a(cache_time.o): in function `tb_cache_time_mclock':
cache_time.c:(.text+0xd4): undefined reference to `__atomic_load_8'
/usr/bin/ld: cache_time.c:(.text+0x18c): undefined reference to `__atomic_store_8'
/usr/bin/ld: ../tbox/libtboxr.a(cache_time.o): in function `tb_cache_time_sclock':
cache_time.c:(.text+0x1c4): undefined reference to `__atomic_load_8'
/usr/bin/ld: cache_time.c:(.text+0x290): undefined reference to `__atomic_store_8'
/usr/bin/ld: ../tbox/libtboxr.a(cache_time.o): in function `tb_cache_time':
cache_time.c:(.text+0x2b8): undefined reference to `__atomic_load_8'
/usr/bin/ld: cache_time.c:(.text+0x384): undefined reference to `__atomic_store_8'
collect2: error: ld returned 1 exit status
installing to /root/.local ...
plat: linux
arch: arm
cp: 无法获取'./core/src/demo/demo.b' 的文件状态(stat): 没有那个文件或目录
make: *** [makefile:116：install] 错误 1
Install Fail`
使用其他下载方式也是一样的

**Comment by waruqi** [comment]
见 https://github.com/xmake-io/xmake/issues/1170

**Comment by Ekkone** [comment]
> 见 https://github.com/xmake-io/xmake/issues/1170

请问是不是只能用源码编译来进行安装呢，而且我昨天试了用源码make build过程中会报一些其他的错误，具体信息晚上我可以放上来

**Comment by waruqi** [comment]
自己拉源码编译之前，确保源码拉取完整，还有 git submodule update --init

**Comment by Ekkone** [comment]
> 自己拉源码编译之前，确保源码拉取完整，还有 git submodule update --init

感谢，已解决
