### ISSUE TITLE
希望支持动态add_deps

### ISSUE THREAD

**Issue by Dozingfiretruck** [xmake-io/xmake#1665]
目前无法动态add_deps

**Comment by xq114** [comment]
if has_option("xxx") then add_deps("bar") end

**Comment by Dozingfiretruck** [comment]
> if has_option("xxx") then add_deps("bar") end

不是命令方式，是从某个.h获得判断，on_load时deps已经改不了了

**Comment by xq114** [comment]
在option:on_check里面io.read("xxx.h")判断option是否启用。不过这种情况更推荐用configuration file：`#define XXX_MACRO ${myoption}`然后让xmake根据option生成需要的头文件，见 https://xmake.io/#/manual/project_target?id=targetadd_configfiles
这种做法在各类开源项目中非常常见

**Comment by Dozingfiretruck** [comment]
> 在option:on_check里面io.read("xxx.h")判断option是否可以使用。不过这种情况更推荐使用配置文件：`#define XXX_MACRO ${myoption}`然后让xmake根据option生成需要的头文件，见[https://xmake.io/ #/manual/project_target?id=targetadd_configfiles](https://xmake.io/#/manual/project_target?id=targetadd_configfiles)
> 这种行为在各类开源项目中非常常见
.h没办法修改是固定的，现在是io.read("xxx.h")判断但是这个是在脚本域，此时deps已经改不了了

**Comment by waruqi** [comment]
可以先试下这个 patch https://github.com/xmake-io/xmake/pull/1672 应该可以了

```lua
xmake update -s github:xmake-io/xmake:load
```

之前这块比较乱，现在稍微整理了下， load 分两阶段，on_load 可以动态添加 deps，跟 package:on_load 行为保持一致。

但是这里面不能调用 target:dep/target:deps ，如果要调用这两需要在 after_load 里面操作，会有提示。。

**Comment by Dozingfiretruck** [comment]
> 可以先试下这个补丁#1672应该可以了
> 
> ```lua
> xmake 更新- s github: xmake - io / xmake:加载
> ```
> 
> 之前这块比较乱，现在稍微整理了下，加载分两阶段，on_load可以动态添加deps，跟package:on_load行为保持一致性。
> 
> 但是这里面不能调用 target:dep/target:deps ，如果要调用这里面需要在 after_load 里面操作，会有提示。。

![image](https://user-images.githubusercontent.com/24759100/133353176-c548d439-7881-41be-851e-a98dbbcfc03d.png)
您好我这升级xmake失败

**Comment by waruqi** [comment]
试下这个 xmake update -s github:xmake-io/xmake#load

**Comment by Dozingfiretruck** [comment]
![image](https://user-images.githubusercontent.com/24759100/133377175-e74f48c4-5963-427d-bb2f-5120d913af40.png)
您好，我尝试了在on_load判断在after_load里deps但是没有成功，编译报错，在描述域直接add_deps编译正常

**Comment by waruqi** [comment]
我觉得说的挺明白了 on_load 里面动态添加 跟after_load没关系

所有脚本域动态配置走 target:add("xxx", ) 而不是 target:add_xxx

**Comment by Dozingfiretruck** [comment]
> 我觉得说的挺明白了 on_load 里面动态添加 跟after_load没关系
> 
> 所有脚本域动态配置走 target:add("xxx", ) 而不是 target:add_xxx

测试可以了，感谢，我看您说 但是这里面不能调用 target:dep/target:deps ，如果要调用这里面需要在 after_load 里面操作 我以为要在after_load做，理解错了，哈哈，请问何时发布下一个正式版？我就可以把改好的工程发布出去了

**Comment by waruqi** [comment]
on_load 你动态添加 deps 这个时候 deps 结构还没构建完成，怎么可能调用 target:deps 。。只能放到 after_load 里面去，你没用到 那就不需要 after_load

> 请问何时发布下一个正式版？我就可以把改好的工程发布出去了

没这么快，等一两月吧。

**Comment by Dozingfiretruck** [comment]
好的，感谢

**Comment by waruqi** [comment]
我先 merge 到 dev 了
