### ISSUE TITLE
`xmake package` 无法得到和文档声称相同的结果

### ISSUE THREAD

**Issue by myuanz** [xmake-io/xmake#1666]
### 描述问题

我创建了一个简单的[项目](https://github.com/myuanz/xmake-package-test), 按照[官方文档](https://xmake.io/#/zh-cn/package/local_package?id=%e9%bb%98%e8%ae%a4%e6%89%93%e5%8c%85%e6%a0%bc%e5%bc%8f)打包. 但是没能得到和文档一样的结果, 缺少.h文件. 

```console
⋊> ~/p/g/xmake-package-test on master ⨯ xmake package                                                                                         16:10:20
[100%]: build ok!
package(xmake-package-test): build/packages/x/xmake-package-test generated
⋊> ~/p/g/xmake-package-test on master ⨯ tree build/packages/                                                                                  16:10:37
build/packages/
└── x
    └── xmake-package-test
        ├── linux
        │   └── x86_64
        │       └── release
        │           └── lib
        │               └── libxmake-package-test.so
        └── xmake.lua

6 directories, 2 files
```

### 期待的结果

和文档所示一样有相同的打出来的.h文件. 

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：xmake v2.5.7+202109072107
- xmake运行平台：Manjaro 21.1.2 Pahvo

**Comment by xq114** [comment]
xmake.lua中没有声明add_headerfiles

**Comment by myuanz** [comment]
> xmake.lua中没有声明add_headerfiles

好了, 谢谢.

我要不开一个关于文档的PR?

**Comment by waruqi** [comment]
> > xmake.lua中没有声明add_headerfiles
> 
> 好了, 谢谢.
> 
> 我要不开一个关于文档的PR?

文档有没说全的 你可以提pr补充
