### ISSUE TITLE
support fetching more information for visual studio

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1673]
### 你在什么场景下需要该功能？

目前`import("core.tool.toolchain").load("msvc")`只保证vs的大版本可以获取，其他部分在测试时非指定不能获取（例如vs_toolset、vs_sdkver等），而一些package（如ghostscript）需要用到toolset的信息。

### 描述可能的解决方案

`import("core.tool.toolchain").load("msvc"):config("vs_toolset")`即使测试时不加--vs_toolset参数也可以自动探测toolset；同样对于vs_sdkver增加自动探测；增加vc版本探测（14=2015，15=2017，16=2019，等等）而不是在包内部用if-else去判断

**Comment by waruqi** [comment]
vs_toolset 和 vs_sdkver 我加上了，另外所有 vs 相关信息字段，原本就可以从  toolchain:config("vcvars") 里面取出来，比如 

vcvars.VCToolsVersion 就是 toolset
