### ISSUE TITLE
mingw shared library suffix .dll.a support

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1674]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情

https://github.com/xmake-io/xmake-repo/pull/640

mingw上动态库的import library默认后缀是libfoo.dll.a，链接时加的flag应为`-lfoo`，与静态库保持一致。在mingw平台使用时，xmake的package自动查找对于动态库应先自动查找.dll.a作为后缀；xmake.lua中添加add_links时应自动识别用户系统上.dll.a后缀的库

**Comment by waruqi** [comment]
这个和 https://github.com/xmake-io/xmake/pull/1589 这个到时候可以一起搞下。。

**Comment by waruqi** [comment]
可以测试下这个 patch https://github.com/xmake-io/xmake/pull/1675

这个改动也许会影响部分 mingw case ，毕竟测试不全，也许会有遗漏，帮忙多测测吧。

**Comment by xq114** [comment]
https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/manager/xmake/find_package.lua

这里自动查找也要改

**Comment by waruqi** [comment]
> https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/manager/xmake/find_package.lua
> 
> 这里自动查找也要改

这里不是已经改了么。。看 mingw 分支

**Comment by waruqi** [comment]
已经合进去了，我这边测试 ok，你可以看下，有问题再开
