### ISSUE TITLE
使用xmake编译cmake工程时出现无规则制作目标"install"错误

### ISSUE THREAD

**Issue by Ekkone** [xmake-io/xmake#1679]
使用xmake编译cmake工程时可以编译成功，但最后会弹出提示：

make: *** 没有规则可制作目标“install”。 停止。
error: execv(make install) failed(2)

cmake编译不会出现上述问题，给cmake工程添加了install目标后xmake正常不报错，现在想可以通过什么样的配置方法可以即使没有install目标也可以正常

**Comment by waruqi** [comment]
做包 还是 trybuild?

**Comment by Ekkone** [comment]
> 做包 还是 trybuild?

应该是trybuild，工程是用cmake的，我使用xmake来调用cmake，编译结果就是xmake需要install目标才能返回成功

**Comment by waruqi** [comment]
trybuild只是尝试编译，有一定的失败率，不可能完全通用，只是作为日常临时编译其他项目的辅助特性

目前默认编译完 会走 make install ，但即使失败了 也没啥问题，其实已经编译晚了

如果想要稳定编译，走包模式，参考 xmake-repo里面带有cmake的包怎么定义的，自己定义后继承进来

**Comment by Ekkone** [comment]
> trybuild只是尝试编译，有一定的失败率，不可能完全通用，只是作为日常临时编译其他项目的辅助特性
> 
> 
> 
> 目前默认编译完 会走 make install ，但即使失败了 也没啥问题，其实已经编译玩了
> 
> 
> 
> 如果想要稳定编译，走包模式，参考 xmake-repo里面带有cmake的包怎么定义的，自己定义后继承进来

好的，我之后试试
