### ISSUE TITLE
Add optional lua5.3 runtime instead of luajit to provide better compatibility

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#1682]
We can support more archs, e.g. riscv, loongarch, ..

**Comment by waruqi** [comment]
We added lua5.3 as an optional lua vm backend, and it basically works now. see https://github.com/xmake-io/xmake/pull/1683 and lua53 branch

@TitanSnow

**Comment by waruqi** [comment]
Currently only core.base.bytes cannot be used because it uses ffi, but this is not a big problem. I will let it support lua in the next few days.
The other 99% of the cases have worked normally.

**Comment by SirLynix** [comment]
I think Lua 5.2 may be a better compatibility choice than Lua 5.3, mostly because Lua has native integer support from >=5.3 and LuaJIT/Lua 5.2 don't, which may lead to weird behavior

**Comment by waruqi** [comment]
> I think Lua 5.2 may be a better compatibility choice than Lua 5.3, mostly because Lua has native integer support from >=5.3 and LuaJIT/Lua 5.2 don't, which may lead to weird behavior

This is not a big problem, it works normally on ci, and xmake will try to support lua5.4 later.

Because the code of xmake is implemented using lua 5.1 syntax, and luajit's restrictions on syntax and features seem to be stricter. So in the process of migrating to 5.3, I did not encounter too many problems.

**Comment by waruqi** [comment]
> because Lua has native integer support from >=5.3

It is also because it supports native integers, so it is more convenient to port the luajit bits module to lua5.3

https://github.com/xmake-io/xmake/blob/dev/xmake/core/base/compat/bit.lua

**Comment by waruqi** [comment]
We continue to switch to lua5.4.3 https://github.com/xmake-io/xmake/pull/1739
