### ISSUE TITLE
package.tools.autoconf should use CPPFLAGS in favor of CFLAGS and CXXFLAGS

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1688]
### 描述问题

- CPPFLAGS: C/C++ preprocessor flags. These are applied both to c and c++ preprocessor. Usually this only includes flags that start with -D and -I.
- CFLAGS / CXXFLAGS / CXX1XFLAGS: Compiler flags for the c/c++/c++11 compiler that are not in the preprocessor. Things like -g -o -pthread. You should rarely set these as R automatically uses the appropriate defaults.

在调用autoconf时应优先使用CPPFLAGS而非CFLAGS/CXXFLAGS。使用后者还会导致问题，即针对preprocessing的测试会失败。 https://www.gnu.org/software/autoconf/manual/autoconf-2.63/html_node/Running-the-Preprocessor.html 使用 AC_PREPROC_IFELSE 测试包头文件时只会采用CPPFLAGS，其余变量将被忽略；这会导致包探测失败，见 https://github.com/xq114/xmake-repo/runs/3647967620?check_suite_focus=true

### 期待的结果

调用autoconf时可以指定cppflags：
```
import("package.tools.autoconf").install(package, configs, {cppflags = {"-I" .. package:dep("openssl"):sysincludedirs()[1]}})
```

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.7
- xmake运行平台：linux
- xmake目标平台：linux

### 其他信息

https://stackoverflow.com/questions/2754966/cflags-vs-cppflags

**Comment by waruqi** [comment]
加上了

**Comment by xq114** [comment]
改动还有问题，cppflags没定义就使用了

**Comment by waruqi** [comment]
再试试
