### ISSUE TITLE
support to define a variable without quotes for configuration files

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1694]
### 你在什么场景下需要该功能？

https://github.com/xmake-io/xmake/discussions/1693

例如在configuration file中定义
```
${define MY_EXPORT}
```
想在target中控制
```
set_configvar("MY_EXPORT", is_kind("shared") and "__declspec(dllexport)" or "")
```
生成的文件会带有引号：
```
#define MY_EXPORT "__declspec(dllexport)"
```
或者
```
#define MY_EXPORT ""
```

### 描述可能的解决方案

去除configfile的引号，需要时手动用flag控制
```
set_configvar("MY_EXPORT", "val", {quote = true})
```

### 描述你认为的候选方案

由用户手动加引号
```
set_configvar("MY_EXPORT", "\"val\"")
```

**Comment by waruqi** [comment]
目前只能禁用 默认去除会破坏向下兼容性

set_configvar("MY_EXPORT", "val", {quote = false})

**Comment by xq114** [comment]
或者用set_policy控制也成

**Comment by waruqi** [comment]
> 或者用set_policy控制也成

可以搞成policy，但目前的默认行为不能改了走policy也是跟 quote=false一样只能禁用

**Comment by waruqi** [comment]
```lua
set_configvar("MY_EXPORT", "val", {quote = true})
```

目前还是加了这种支持，可以再试试

**Comment by xq114** [comment]
```
error: @programdir\core\base\bit.lua:21: module 'base/compat/bit' not found:
        no field package.preload['base/compat/bit']
        failed to load C:\Users\xq114\xmake/core/base/compat/bit.lua : @programdir\core\base\compat\bit.lua:26: 'end' expected (to close 'function' at line 25) near '&'
        no file '.\base/compat/bit.lua'
        no file 'C:\Users\xq114\xmake\lua\base/compat/bit.lua'
        no file 'C:\Users\xq114\xmake\lua\base/compat/bit\init.lua'
        no file '.\base/compat/bit.dll'
        no file 'C:\Users\xq114\xmake\base/compat/bit.dll'
        no file 'C:\Users\xq114\xmake\loadall.dll'
```

发现xmake update -s挂了，应该和runtime改动有关，正在卸载重装；感觉runtime的改动还是挺重要的，是不是等2.6版本再切换默认runtime比较好？这样两者之间不兼容的部分通过minor version就能区分，用到lua5.3特性的也可以直接写`set_xmakever("2.6")`而不用精确到小版本

**Comment by waruqi** [comment]
> 发现xmake update -s挂了，应该和runtime改动有关，正在卸载重装

这个主要是 core 里面加个 xmake._LUAJIT，但是如果从低版本 engine 更新的话，默认就是 nil 走到 lua 上去了，我刚改了下，如果是 nil ，默认就是 luajit = true，兼容下就好了。。

> 感觉runtime的改动还是挺重要的，是不是等2.6版本再切换默认runtime比较好？这样两者之间不兼容的部分通过minor version就能区分，用到lua5.3特性的也可以直接写set_xmakever("2.6")而不用精确到小版本

最近几个版本是不会切的，现在仅仅 dev 阶段 win 上切了下，主要是为了做部分灰度测试，多跑出点问题 好提早修复。。等正式发版前，我会切回来的。。否则永远都测试不出来 lua5.3 上有哪些坑。。

**Comment by xq114** [comment]
quote=false接口可以了
