### ISSUE TITLE
add 0-1 series of configvar_check_xxx functions

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1700]
### 你在什么场景下需要该功能？

cmake/autoconf的configuration都可以指定为def/not def模式和0/1模式，前者若条件不满足就不定义，后者始终定义但根据条件满足与否定义为0或者1. xmake的configvar_check_xxx系列现在只提供前者，不提供后者。

### 描述可能的解决方案

提供`configvar_check_cfuncs01`、`configvar_check_ctypes01`、`configvar_check_csnippets01`等函数，一并封装在check_xxx.lua内。

### 描述你认为的候选方案

在原来函数基础上加一个参数
```
configvar_check_ctypes("USE_MYTYPE_T", "mytype_t", {binary = true})
```

**Comment by waruqi** [comment]
不是原本就支持么。。

https://github.com/xmake-io/xmake/blob/3a8aab03b9e615cd0a40a1ed21e9ab4490f6f1c5/xmake/actions/config/configfiles.lua#L242-L247

```lua
/* #undef HAS_STRING_H */
#define HAS_STRING_AND_STDIO_H 1
/* #undef HAS_WCHAR */
/* #undef HAS_WCHAR_AND_FLOAT */
#define HAS_PTHREAD 1
#define HAS_STATIC_ASSERT 1
#define HAS_SETJMP 1
#define HAS_CONSTEXPR 1
#define HAS_CONSEXPR_AND_STATIC_ASSERT 1
```

**Comment by xq114** [comment]
不是说这里，是说`includes("check_ctypes.lua")`的函数，想要的输出是
```
#define HAS_STRING_H 0
#define HAS_STRING_AND_STDIO_H 1
#define HAS_WCHAR 0
#define HAS_WCHAR_AND_FLOAT 0
#define HAS_PTHREAD 1
#define HAS_STATIC_ASSERT 1
#define HAS_SETJMP 1
#define HAS_CONSTEXPR 1
#define HAS_CONSEXPR_AND_STATIC_ASSERT 1
```

**Comment by waruqi** [comment]
其实 xmake 已经支持了的，而且比 cmake 的 01 更灵活，可以任意指定 x or y 的值，文档里面也有相关介绍，https://xmake.io/#/zh-cn/manual/project_target?id=%e5%ae%8f%e5%ae%9a%e4%b9%89

就是走 `${default HAS_WCHAR 0}` 模式，如果检测通过，它会整个替换成 set_configvar 的支持，比如 string, number 或者 1

如果检测失败，就是 `${default }` 里面指定的默认值，可以是0，也可以是你指定的任意值或者string

你可以改成下面这样就是 01 模式了：

```lua
#define HAS_WCHAR ${default HAS_WCHAR 0}
```

**Comment by xq114** [comment]
> 其实 xmake 已经支持了的，而且比 cmake 的 01 更灵活，可以任意指定 x or y 的值，文档里面也有相关介绍，[xmake.io/#/zh-cn/manual/project_target?id=%e5%ae%8f%e5%ae%9a%e4%b9%89](https://xmake.io/#/zh-cn/manual/project_target?id=%e5%ae%8f%e5%ae%9a%e4%b9%89)
> 
> 就是走 `${default HAS_WCHAR 0}` 模式，如果检测通过，它会整个替换成 set_configvar 的值，比如 string, number 或者 1
> 
> 如果检测失败，就是 `${default }` 里面指定的默认值，可以是0，也可以是你指定的任意值或者string
> 
> 你可以改成下面这样就是 01 模式了：
> 
> ```lua
> #define HAS_WCHAR ${default HAS_WCHAR 0}
> ```

这样的话就得一个一个变量去改.h.in文件了，而且在两种模式之间切换也会变成一件很困难的事情。在port从autoconf移植的包的时候尤其麻烦，有10个.in文件，每个文件20个0-1变量，就得改200遍，整个修改逻辑就没法看了；而有check01系列函数那一切都可以在单个port/xmake.lua里面完成

我现在自定义的是这样
```
function configvar_check_ctypes01(definition, types, opt)
    opt = opt or {}
    local optname = "__" .. (opt.name or definition)
    local defname, defval = unpack(definition:split('='))
    option(optname)
        add_ctypes(types)
        if opt.languages then
            set_languages(opt.languages)
        end
        if opt.cflags then
            add_cflags(opt.cflags)
        end
        if opt.cxflags then
            add_cxflags(opt.cxflags)
        end
        if opt.defines then
            add_defines(opt.defines)
        end
        if opt.includes then
            add_cincludes(opt.includes)
        end
    option_end()
    set_configvar(defname, has_config(optname) and (defval or 1) or 0)
end

function configvar_check_csnippets01(definition, snippets, opt)
    opt = opt or {}
    local optname = "__" .. (opt.name or definition)
    local defname, defval = unpack(definition:split('='))
    option(optname)
        add_csnippets(definition, snippets, {tryrun = opt.tryrun, output = opt.output})
        if opt.includes then
            add_cincludes(opt.includes)
        end
        if opt.cflags then
            add_cflags(opt.cflags)
        end
        if opt.cxflags then
            add_cxflags(opt.cxflags)
        end
        if opt.defines then
            add_defines(opt.defines)
        end
        if opt.output then
            after_check(function (option)
                if option:value() then
                    option:set("configvar", defname, opt.number and tonumber(option:value()) or option:value())
                end
            end)
        end
    option_end()
    set_configvar(defname, has_config(optname) and (defval or 1) or 0)
end
```

其实也可以支持0 or anything的，只是用法上几乎都是
```
#if (@VAR1@ && @VAR2@)
...
#endif
```
这样，所以其实0-1就足够了

**Comment by xq114** [comment]
其实最理想的是xmake可以外带一个文件就完整port整个包，类似 https://github.com/xq114/SuiteSparse-xmake

现在只要带了configuration file就不行，得replace一遍各个.in文件，但.in文件不算太多的时候还好；
```
on_install("windows", function (package)
        io.gsub("config.h.in", "%$", "")
        io.gsub("config.h.in", "# ?undef (.-)\n", "${define %1}\n")
        io.gsub("libcharset/config.h.in", "%$", "")
        io.gsub("libcharset/config.h.in", "# ?undef (.-)\n", "${define %1}\n")
        os.cp(path.join(os.scriptdir(), "port", "xmake.lua"), ".")
        import("package.tools.xmake").install(package, {
            installprefix = package:installdir():gsub("\\", "\\\\"),
            vers = package:version_str()
        })
    end)
```
要是再去针对每个变量改一遍就太麻烦了，这样port的优势就很微弱了

**Comment by waruqi** [comment]
如果非要 xmake.lua 改的话，你这个实现就可以了，直接提个 pr 过来好了。

**Comment by waruqi** [comment]
> 现在只要带了configuration file就不行，得replace一遍各个.in文件，但.in文件不算太多的时候还好；

再多，里面的替换模式就那么几种，搞个 for loop 遍历 .in 替换也要不了几行

**Comment by xq114** [comment]
> 如果非要 xmake.lua 改的话，你这个实现就可以了，直接提个 pr 过来好了。

用01后缀和参数哪个好一点？01后缀更简单，但如果要支持0 or anything的话这种表达又可能有歧义；参数叫binary也有歧义问题，改加一个default就没歧义了
```
configvar_check_ctypes("USE_MYTYPE_T", "mytype_t", {default = 0})
```

**Comment by waruqi** [comment]
> configvar_check_ctypes("USE_MYTYPE_T", "mytype_t", {default = 0})

就这个好了，新加接口，很多重复实现有点冗余了，不好维护，也不方便扩展其他 default 值。
