### ISSUE TITLE
xmake安装lz4的时候, 如果机器上没有7z压缩工具会报下载错误, 而不是合适提示

### ISSUE THREAD

**Issue by myuanz** [xmake-io/xmake#1706]
xmake安装lz4的时候, 如果机器上没有7z会报下载错误, 但是其实不是下载错误, lz4的源代码在`https://www.7-zip.org/a/lzma1900.7z`, 没有7z就无法解压, 报错后丢到最外层只显示一个下载失败. 我加了`-vD`才懂为什么. 

这个提示可能会让新手很迷惑, 新手看到下载错误后第一反应应该是要加梯子, 搜搜xmake怎么加梯子后又会发现好像总是失效, 走投无路来到了github issues这里, 大佬告诉他看看详细信息, 彵这一看才明白是缺7z. 然后这就一上午过去了. 

还是挺打击新手心态的, 所以是不是应该给某些错误提示一个特殊对待, 不要让详细错误信息在向上拋的过程中丢失?

**Comment by waruqi** [comment]
有些错误后面是可以改进完善，但有些错误充斥在其他工具内部，不好提取，不管怎么完善 总归会有覆盖不到的场景。。

目前tar gz zip的包，如果没有相关解压工具，原本就会有 unzip not found提示，只是 7z的包目前不多，并且win自带了7z，很难测试到，一个人搞，所以难免会有部分遗漏的case 体谅下，回头有时间 我会改进下

另外默认不加-vD 失败后也有提示 错误详情在指定文件可以看

**Comment by myuanz** [comment]
作者做得很好啦

**Comment by waruqi** [comment]
错误提示我改进过了，dev 版本
