### ISSUE TITLE
[runtime] invalid option '%l' to 'lua_pushfstring'

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1707]
### 描述问题

安装包时若下载出错则出现这个问题，使用的是lua runtime

https://github.com/lua/lua/blob/9db4bfed6bb9d5828c99c0f24749eedf54d70cc2/lobject.c#L477-L528

https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/host/minilua.c#L672-L713

lua原生是不支持多字节的format的，推测是因为xmake中使用了很多类似`%ld`的修饰符，lua无法识别，就会报错。luajit则实现不同，在这里会自动进行处理，不会报错。

### 期待的结果

能在lua runtime上正常运行；或者扩展lua的功能，或者修改xmake的源码

### 错误信息

```console
error: invalid option '%l' to 'lua_pushfstring'
stack traceback:
    [C]: in function '_openv'
    [@programdir\core\base\process.lua:266]: in function 'openv'
    [@programdir\core\base\os.lua:749]: in function 'execv'
    [@programdir\core\base\os.lua:653]: in function 'runv'
    [@programdir\core\sandbox\modules\os.lua:262]:
    [@programdir\core\sandbox\modules\os.lua:290]: in function 'vrunv'
    [@programdir\modules\devel\git\submodule\update.lua:80]:
    [...modules\private\action\require\impl\actions\download.lua:87]: in function '_checkout'
    [...modules\private\action\require\impl\actions\download.lua:240]:

  => clone pytorch/pytorch.git v1.9.0 .. failed
```

如果日志太多，可以上传附件，但必须完整，否则一率标记为 Invalid。

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：dev
- xmake运行平台：windows
- xmake目标平台：windows

**Comment by waruqi** [comment]
嗯 之前我已经修复掉一些类似的了，这些我回头继续修下

**Comment by waruqi** [comment]
我修了，再试试
