### ISSUE TITLE
Add ability to detect compiler language standards as features

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1715]
### 你在什么场景下需要该功能？

https://github.com/xmake-io/xmake/discussions/1712

cmake的`target_compile_features`支持high level的standard探测和low level的具体feature探测，xmake只支持后者

https://cmake.org/cmake/help/latest/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html

另外cmake还支持cuda的standard探测，这个也可以加上，命名可以为`cuda_cxx_std_14`、`cuda_cxx_std_17`这样

### 描述可能的解决方案

discussion里面说用flag探测，但这个并不行，例如msvc没有`-std:c++11`这个flag（最低就是c++14，默认c++17），但探测是否支持c++11应该返回“是”。可以根据编译器版本判断，也可以借助`__cplusplus`宏来判断。

**Comment by waruqi** [comment]
加上了

https://github.com/xmake-io/xmake/blob/2c906bc87c0140c20509ee2063b64188375225f2/tests/apis/check_xxx/xmake.lua#L26-L34

cuda 的我没环境，并且不同平台根据 ccbin 探测方式不同，懒得弄了，先这样吧。。

或者可以参考 
https://github.com/xmake-io/xmake/tree/dev/xmake/modules/detect/tools/clang
https://github.com/xmake-io/xmake/tree/dev/xmake/modules/detect/tools/cl

提个pr过来，加到 https://github.com/xmake-io/xmake/tree/dev/xmake/modules/detect/tools/nvcc

**Comment by xq114** [comment]
https://github.com/xmake-io/xmake/discussions/1702

这里对option的编译器探测似乎没有好的途径，只能通过
```
check_snippets("gcc", [[#ifndef __GNUC__ // _MSC_VER, __clang__, __EMSCRIPTEN__, etc
#error
#endif]])
```
这种来进行，有点复杂；能否提供一个编译器探测功能？

1. 作为feature提供，`configvar_check_features("GCC", "vendor_gcc")`这样；
2. 类似autoconf，提供一个`check_decls`/`configvar_check_decls`函数检测declarations，实现也很简单，autoconf的实现是
```
-- check_decls("...", "decl")
check_snippets("...", [[
void test() {
#ifndef decl
  void(decl);
#endif
}]])
```
这样定义可以是宏、函数、结构体、全局变量等都行。这样编译器检测可以用
```
configvar_check_decls("GCC", "__GNUC__")
```
也很简单

**Comment by waruqi** [comment]
> 作为feature提供，configvar_check_features("GCC", "vendor_gcc")这样；

是否存在编译器跟 feature 似乎不着边

> 类似autoconf，提供一个check_decls/configvar_check_decls函数检测declarations，实现也很简单，autoconf的实现是

虽然简单通用，但是 decls 去检测 宏，函数 和类型对用户来讲有歧义，明明叫 decls 却去检测 macros，对于初学者压根想不到

还不如一个api 干一件事情，简单明了，而且目前 check_xxx 已经有专门对 types/funcs 等检测了，就没必要都混到这个接口去。。


直接加个 configvar_check_macros() 专门检测宏定义的就行了。。

### 检测宏是否定义

```lua
configvar_check_macros("HAS_GCC", "__GNUC__")
```

### 检测宏没有被定义

```lua
configvar_check_macros("NO_GCC", "__GNUC__", {defined = false})
```

### 检测宏条件

```lua
configvar_check_macros("HAS_CXX20", "__cplusplus >= 202002L", {languages = "c++20"})
```

**Comment by waruqi** [comment]
加上了，再试试：https://github.com/xmake-io/xmake/blob/dev/xmake/includes/check_macros.lua
