### ISSUE TITLE
添加 Linux ARM deb 包

### ISSUE THREAD

**Issue by hmsjy2017** [xmake-io/xmake#1723]
### 你在什么场景下需要该功能？

xmake 没有适用于 ARM 设备的 deb 包，而且树莓派编译 xmake 速度很慢。

### 描述可能的解决方案

提供 armhf 和 arm64 架构的 deb 包。

### 描述你认为的候选方案

无

### 其他信息

无

**Comment by waruqi** [comment]
目前 deb 都是 ci 上构建的，但是 arm/arm64 的 ci 跑在 qemu 下，很慢，跑完测试，还要去重新构建deb 整个过程得超 1h ，影响日常开发效率，即使仅仅发版时候构建，发版过程也很慢

所以目前就不考虑了 ，自己耐心等待编译就好了

**Comment by hmsjy2017** [comment]
Travis-CI 和 Azure Pipelines 都有 arm64 的 runner，可以考虑使用。

**Comment by waruqi** [comment]
不考虑 目前只用action 不想引入第三方ci 。。travis 和 appveyor我好不容易才删干净
