### ISSUE TITLE
Windows非管理员命令行执行xmake update，产生冗余注册表项

### ISSUE THREAD

**Issue by WindyValley** [xmake-io/xmake#1738]
### 问题描述

在Windows平台，直接双击安装包安装时，会默认请求管理员权限，UAC验证通过且安装后，相关注册表项写在**HKEY_LOCAL_MACHINE**；
在非管理员命令行，执行xmake update更新版本时，xmake附带"/NOADMIN"启动安装，相关注册表项写在**HKEY_CURRENT_USER**，而原本写在**HKEY_LOCAL_MACHINE**注册表项并没有被清理；
在上述两次操作后，控制面板软件卸载页会显示两个“XMake build utility”条目

### 期待的结果

能够延续原有的安装方式安装新包，或者安装新包之前清理旧包遗留的注册表

### 相关环境

- xmake版本：由2.5.5更新至2.5.8
- xmake运行平台：Windows

**Comment by xq114** [comment]
https://github.com/xmake-io/xmake/issues/1576

相同的问题

**Comment by WindyValley** [comment]
> #1576
> 
> 相同的问题
