### ISSUE TITLE
qt project can not make vs proj file

### ISSUE THREAD

**Issue by godsay1983** [xmake-io/xmake#174]
rt

**Comment by waruqi** [comment]
Currently not supported, I will later to implement, please wait for some time.

**Comment by godsay1983** [comment]
Is it possible to generate qtcreator proj?

**Comment by waruqi** [comment]
No, I don't have time to support it now. I will consider it if I have free time in the future. of course, I also welcome everyone to contribute it.

**Comment by waruqi** [comment]
We have been able to generate some Qt vcproj projects without moc header files. You can try it.

About other project with moc header files, I'm going to support it in the next version.

**Comment by waruqi** [comment]
#257

**Comment by waruqi** [comment]
I will support it in v2.2.3

**Comment by OpportunityLiu** [comment]
@godsay1983 
可以试下dev分支刚合并的功能
CC @waruqi
