### ISSUE TITLE
Mac m1 更新v2.5.8后启动后被 KILL

### ISSUE THREAD

**Issue by HiSunzhenliang** [xmake-io/xmake#1742]
### 描述问题

Mac m1 使用 `xmake update `更新v2.5.8
执行 `xmake --version`启动后被 KILL

### 期待的结果

显示正确版本号

### 错误信息

```console
 ❯ xmake --version
[1]    65756 killed     xmake --version
❯ xmake 
[1]    65772 killed     xmake
 ❯ xmake -vD          
[1]    65780 killed     xmake -vD
```

### 相关环境

- xmake版本：v2.5.8
- xmake运行平台：
    Darwin 192.168.2.4 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 arm64
- xmake目标平台：
     Darwin 192.168.2.4 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 arm64

### 其他信息

尝试使用官网 `bash <(curl -fsSL https://xmake.io/shget.text)`安装

打印日志结尾为
```
...
installing to /Users/sun/.local ...
plat: macosx
arch: arm64
ok!
/dev/fd/63: line 263: 64342 Killed: 9               xmake --version > /dev/null 2>&1
/Users/sun/.xmake/profile: line 13: compctl: command not found
/dev/fd/63: line 263: 64344 Killed: 9               xmake --version
Reload shell profile by running the following command now!
source ~/.xmake/profile
```
按照提示执行`source ~/.xmake/profile`后报错不变
```
 ❯ which compctl                                                                               
compctl: shell built-in command
```

**Comment by waruqi** [comment]
拉下源码编译 切到luajit试试

```console
git clone --recursive https://github.com/xmake-io/xmake.git -b dev
cd ./xmake
make build RUNTIME=luajit
./scripts/get.sh __local__ __install_only__
source ~/.xmake/profile
xmake --version
```

**Comment by HiSunzhenliang** [comment]
切换make RUNTIME=lua后编译也可以正常编译安装

**Comment by HiSunzhenliang** [comment]
> 那我先关了 回头有问题再开

嗯嗯，我也很纳闷，执行 xmake 现象也比较难
