### ISSUE TITLE
support installing *_importfiles for header-only target

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1747]
### 你在什么场景下需要该功能？

需要为header-only的target导出pkgconfig和cmake的import files

目前会报错error: install failed, pkgconfig_importfiles: only support for library target(testheader)!

### 描述可能的解决方案

在header-only target的import files中忽略library，只提供include。eigen库可以作为参考（这是一个header-only library）

**Comment by waruqi** [comment]
我加了个 headeronly 的 target kind ，专门处理这些，install 那个也从 phony 改成 headeronly 好了。

```lua
add_rules("mode.release", "mode.debug")

target("foo")
    set_kind("headeronly")
    add_headerfiles("src/foo.h")
    add_rules("utils.install.cmake_importfiles")
    add_rules("utils.install.pkgconfig_importfiles")
```

cmake import files 我部署，我加了个空的，可以帮忙提个 pr 改下增加对 headerfiles 的支持，https://github.com/xmake-io/xmake/blob/dev/xmake/scripts/cmake_importfiles/xxxTargets-headeronly.cmake

**Comment by waruqi** [comment]
你先试试，按理 xxxTargets-headeronly.cmake 空的应该也没事，不行到时候再改进下。

**Comment by xq114** [comment]
> 你先试试，按理 xxxTargets-headeronly.cmake 空的应该也没事，不行到时候再改进下。

![image](https://user-images.githubusercontent.com/42310255/137876493-49a037f6-67ae-45b9-a6c1-9e46f0b5edbe.png)
![image](https://user-images.githubusercontent.com/42310255/137876664-a355cf64-dcfc-4d4a-9343-a1e6276f849d.png)
headeronly的library类型应该设为interface而不是static/shared；确实不需要Targets-headeronly.cmake文件，可以直接不要
