### ISSUE TITLE
支持任意后缀的source file

### ISSUE THREAD

**Issue by colorpeach** [xmake-io/xmake#1760]
### 你在什么场景下需要该功能？

目前我的场景是这样的：  
有一个目录下有各种各样的文件，有的有文件后缀，有的甚至没有  
然后我希望对每个文件进行以下操作：
1. 如果是.lua文件，就是用luac5.1进行编译
2. 否则直接拷贝文件到目标目录

由于没法预料这个目录下所有的文件后缀（有些文件没有后缀），所以现在总是会报错：

```
error: unknown source file: xxxx
```

### 描述可能的解决方案

如果set_extensions能够设置所有后缀可能比较好？，比如`set_extensions("*")`这种

### 描述你认为的候选方案

或者新加另一个api来支持不需要关心后缀的情况

### 其他信息

目前我也是刚开始使用xmake，不知道这种情况是不是有其他的处理方式

**Comment by colorpeach** [comment]
@waruqi 感谢回复，我是自定义了rule的，但是如果不写set_extensions，还是会报一样的错误，如果写的话，我没法预料目录之后会放什么文件，最主要还有没有后缀的文件，比如文件名就是：0。

下面是我的代码

```lua
rule("luajit")
    -- set_extensions(".lua", ".json", ".editordata", ".txt", ".xml", ".meta", ".def")
    on_build_file(function (target, sourcefile, opt)
        local targetFile = path.join(target:targetdir(), get_sourcefile_subpath(sourcefile))

        os.mkdir(path.directory(targetFile))

        if (path.extensione(sourcefile) == '.lua')
        then
            os.runv('luajit', { '-bg', sourcefile, targetFile })
        else
            os.cp(sourcefile, targetFile)
        end
    end)


target("compile")
    -- skip link
    set_kind("object")

    add_rules("luajit")
    add_files("scripts/**")
    set_targetdir("../dist")
```

**Comment by waruqi** [comment]
设置上 set_extensions

**Comment by colorpeach** [comment]
@waruqi 嗯，因为没法预料这个目录里会存在其他什么文件。假如我已经设置了：

```lua
set_extensions(".lua", ".json", ".editordata", ".txt", ".xml", ".meta", ".def")
```

文件名为 0 的文件还是会报错。对了，我的xmake是WSL下的`xmake v2.5.8+202110191514`这个版本。

报错是：
```
error: unknown source file: scripts/template/0
```

**Comment by colorpeach** [comment]
@waruqi 我试试这种 add_files("xxx", {rules = "yyy"})

**Comment by colorpeach** [comment]
> @waruqi 我试试这种 add_files("xxx", {rules = "yyy"})

这种写法是可以的，非常感谢。
