### ISSUE TITLE
Cannot install and run on Mac M1

### ISSUE THREAD

**Issue by dannypsnl** [xmake-io/xmake#1768]
### Describe the problem details

After running `bash <(curl -fsSL https://xmake.io/shget.text)`, run `xmake` get
```
[1]    29718 killed     xmake
```

`uname -a`
```
Darwin linzizhuandeMacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 arm64
```

**Comment by waruqi** [comment]
Can you try to download source code and build it?

Because get.sh recently switched to lua runtime instead of luajit by default, I need to confirm whether this change is caused.

You can test and run both runtimes.

```
make RUNTIME=luajit
```
 or 
```
make RUNTIME=lua
```


```console
git clone --recursive https://github.com/xmake-io/xmake.git -b dev
cd ./xmake
make RUNTIME=luajit
./scripts/get.sh __local__ __install_only__
source ~/.xmake/profile
xmake --version
```
