### ISSUE TITLE
respect environment variables when searching for system packages

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1776]
### 你在什么场景下需要该功能？

https://github.com/xmake-io/xmake/issues/1762

```
find_package("system::library")
```
对能够直接在代码里面#include头文件、链接器声明-llibrary的库应该都能找到，这样就需要在编译器默认的系统文件夹外也搜索由环境变量声明的额外文件夹。否则xmake无法找到用户自定义位置的系统包

### 描述可能的解决方案

在寻找系统包的时候也搜索INCLUDE/LIB/CPATH/C_INCLUDE_PATH/CPLUS_INCLUDE_PATH/LIBRARY_PATH等环境变量声明的文件夹

**Comment by waruqi** [comment]
支持了
