### ISSUE TITLE
How to cross-compile using zig toolchain with musl and Makefile build system?

### ISSUE THREAD

**Issue by trenta3** [xmake-io/xmake#1784]
There are a lot of simple examples on the website xmake.io but no clear indication of how the various options that can be passed to the command line to `xmake f` can be set inside of an `xmake.lua`.

In particular I would like to build using `zig cc -target OS-ARCH-musl` and by using Makefile for an already developed project (LuaJIT). Unfortunately the fact that there is no documented way to do this in `xmake.lua` is driving me nuts.

```lua
add_requires("zig 0.7.x")
add_requires("musl")

target("LuaJIT")
    set_kind("binary")
    set_trybuild("make") <---- How to do this?
    set_toolchains("@zig")
    set_toolchains("@musl") <--- How to set musl in zig cross-compilation?
```
Thanks a lot in advance!

**Comment by trenta3** [comment]
I know about those options but I would like to set those options in the xmake.lua file in such a way that it also downloads the zig toolchain all by itself. Is this currently possible?

**Comment by waruqi** [comment]
```lua
add_requires("zig 0.7.x")
set_plat("cross")
set_config("cross", "riscv64-linux-musl")

target("LuaJIT")
    set_kind("binary")
    set_toolchains("@zig")
    add_files("src/main.zig")
```

but I have not tested it. you cn try.

**Comment by waruqi** [comment]
```console
[ 25%]: ccache compiling.release src/main.zig
/Users/ruki/.xmake/packages/z/zig/0.7.1/4aac87cff5df4fc49670476aa67f0ddf/./zig build-obj -target
 riscv64-linux-musl -O ReleaseFast --cache-dir build/.objs/test/cross/x86_64/release/zig-cache -
femit-bin=build/.objs/test/cross/x86_64/release/src/main.zig.o src/main.zig
[ 50%]: linking.release test
/Users/ruki/.xmake/packages/z/zig/0.7.1/4aac87cff5df4fc49670476aa67f0ddf/./zig build-exe -target
 riscv64-linux-musl --strip -femit-bin=build/cross/x86_64/release/test build/.objs/test/cross/x8
6_64/release/src/main.zig.o
[100%]: build ok!
```

I tested it, it works.

or we can also use 

```lua
add_rules("mode.debug", "mode.release")
add_requires("zig 0.7.x")

set_plat("cross")

target("test")
    set_kind("binary")
    add_files("src/*.zig")
    set_toolchains("@zig", {cross = "riscv64-linux-musl"})
```

**Comment by trenta3** [comment]
@waruqi Thanks you very much for the snippets. Unfortunately I would like to build a project that is written in C and using Makefiles using the zig toolchain for cross-compilation.
What I don't see in your examples is how to specify an analogue of the flags `--trybuild=make` inside those scripts.

**Comment by waruqi** [comment]
The trybuild mode simply invokes the make command and pass relevant toolchain information to other build systems. For makefile, xmake will set the compiler to $CC $LD and other environment variables. But this is not guaranteed to be effective, because it depends on a specific makefile.

If you just use make to build it, you don't need xmake.

**Comment by trenta3** [comment]
I understand now. Thank you a lot, I'm now using `os.vrun` with custom arguments to the makefile!
