### ISSUE TITLE
path.envsep() returns ";" instead of ":" in msys2 bash

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1785]
### 描述问题

在windows上msys2中使用xmake时，path.envsep()不能返回正确的值

### 期待的结果

返回":"

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.8
- xmake运行平台：msys2
- xmake目标平台：mingw

### 其他信息

![image](https://user-images.githubusercontent.com/42310255/139521300-943a91c3-f653-442b-9fe2-1309c328fea6.png)

**Comment by waruqi** [comment]
这个改不了，目前 xmake 用的还是原生 win32 api 处理的 envs，类似 mingw的gcc ，而不是像 cygwin gcc 那样走的 posix api 这些 getenv 接口去 port的

如果改了，内部拼env 传给 msvc 工具链，还有解析 vs envs都会出问题

如有特殊需求 ，自己外面处理下

**Comment by waruqi** [comment]
就跟 gcc 一样，msys下可以跑 posix gcc 也有 mingw gcc (win api) 两个不同版本，而目前 xmake 全走的win api

当初也尝试过直接基于 posix gcc编译个版本出来 走 getenv 等posix api，然后各种问题 兼容性非常不好

**Comment by waruqi** [comment]
用 ; 的兼容性会更好些，如果msys下强制用 :，那么msys下运行所有 非 msys的程序 全会出问题，不仅仅msvc

**Comment by xq114** [comment]
这个刚刚遇到了，win32的程序要求用win格式，posix的程序、shell脚本和PATH环境变量则要求用posix格式，没法协调，确实只能自己调整，而且还不一定能完全兼容...这个issue先关了吧
