### ISSUE TITLE
Generate CMakelist.txt file for `xmake project` plugin

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#179]
We can run `$ xmake project -k cmakelists` to generate CMakelists.txt file for supporting cmake.

**Comment by waruqi** [comment]
see [#124](https://github.com/tboox/xmake/issues/124)

**Comment by kwhitestone** [comment]
已经在dev分支上了吗？ 计划什么时候发布？

**Comment by waruqi** [comment]
@kwhitestone 还没，计划中，但还没开始排期开发，具体时间点未定，看后期实际进度再决定。

**Comment by waruqi** [comment]
I am implementing it, the source code is here. https://github.com/xmake-io/xmake/blob/dev/xmake/plugins/project/cmake/cmakelists.lua

**Comment by waruqi** [comment]
I have supported it in dev branch. https://github.com/xmake-io/xmake/releases/download/v2.2.3/xmake-dev.exe
