### ISSUE TITLE
支持自建二进制precompiled仓库，并根据二进制precompiled仓库中的配置与项目中xmake.lua中的add_requires是否匹配来决定是否重新编译package

### ISSUE THREAD

**Issue by liyinbo** [xmake-io/xmake#1790]
### 你在什么场景下需要该功能？

当项目中需要用到多个较大的库时，使用二进制precompiled仓库可大大减小团队中各成员的编译时间。

### 描述可能的解决方案

根据xmake config命令中的设置，及项目中xmake.lua中的add_requires来匹配二进制precompiled仓库中各个precompiled package是否满足要求，如满足则直接下载precompiled package，否则重新编译。

### 描述你认为的候选方案

目前似乎可使用conan中的pacakge来达到该功能，但这样要求团队花较多的时间维护conan server，浪费了xmake易上手及可扩展性强的优秀设计。

**Comment by waruqi** [comment]
不是原本就支持了么，windows 上已经默认走 precompiled 了。。见：https://github.com/xmake-io/xmake/issues/1454

官方的预编译仓库：https://github.com/xmake-mirror/build-artifacts

自建原本就支持的，你 clone 下这个仓库，或者按照 build-artifacts 结构，自己搞得 repo 。。然后走 add_repositories 或者 xmake repo --add ，就行了，跟源码包仓库自建用法一样。

**Comment by waruqi** [comment]
另外，如果只是想要一两个包用预编译，都不需要 build-artifacts 预编译仓库，这个主要是走整套ci+预编译流程用的，

自己一两个包，直接走源码包仓库 或者 自己仓库里面定义 package() 切到二进制安装就行了。。

urls 改成二进制包， on_install copy 下就完事了，

参考：https://github.com/xmake-io/xmake-repo/blob/67314da9aea10c393c5e44be834b6fe6366daa5e/packages/l/libsdl/xmake.lua#L113-L121

**Comment by liyinbo** [comment]
好的，没试过这个方式，以为只支持windows，我按照你说的方法试试看。
