### ISSUE TITLE
Support mixed Rust & C++ target and Cargo dependences

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1799]
### 你在什么场景下需要该功能？

https://cxx.rs/build/other.html

需要在c++中调用rust库/函数

### 描述可能的解决方案

```
target("rustlib")
	set_kind("static")
	add_files("src/*.rs")

target("foo")
	set_kind("binary")
	add_rules("rust.cxxbridge")
	add_files("bind/*.rs") -- generate *.rs.h and *.rs.cc, then compile *.rs.cc into the target
	add_deps("rustlib") -- link to rust library only
	add_files("src/*.cpp")
```
注意必须先生成所有的头文件完毕后再编译.cc文件，否则可能出现头文件缺失。如果使用buildcmd并行实现的话，中间的同步是个问题

### 其他信息

例子见 https://cxx.rs/tutorial.html#calling-a-rust-function-from-c

**Comment by waruqi** [comment]
> buildcmd并行实现的话，中间的同步是个问题

走before_buildcmd_file/before_build_file 不会有这个问题， 会提前执行

**Comment by kassane** [comment]
Perhaps it would be less complicated to adhere to a general version of what would most apply to xmake than to focus on one api only.
For example, try using cbindgen to transform the rust code into c or cpp, depending on how you would specify and then compile the project.

**reference:**
https://sixtyfps.io/blog/expose-rust-library-to-other-languages.html

**Comment by waruqi** [comment]
What is the difference between cxxbridge and cbindgen?

**Comment by waruqi** [comment]
Is there a minimal project example and makefile for rust and c/c++ mixed compilation?

**Comment by kassane** [comment]
Difference:
- cbindgen (translate rust to c/c++)[unsafe]
- bindgen (translate c/c++ to rust) [unsafe]
- cxxbridge is a lower level tool than the bindgens. Just as bindgen and cbindgen are built on top of `extern "C"`, it makes sense to think about higher level tools built on top of CXX [safe] (c++ only)

**Comment by waruqi** [comment]
> Difference:
> 
> * cbindgen (translate rust to c/c++)[unsafe]
> * bindgen (translate c/c++ to rust) [unsafe]
> * cxxbridge is a lower level tool than the bindgens. Just as bindgen and cbindgen are built on top of `extern "C"`, it makes sense to think about higher level tools built on top of CXX [safe] (c++ only)

Thanks, that is to say, if it is only mixed with c++ code, should we use cxxbridge to provide better security as much as possible?

**Comment by kassane** [comment]
Using cxxbridge, you wouldn't have to worry about high-level translation, allowing you to interoperate with C++ ABI.

**Comment by waruqi** [comment]
I tried to use cxxbridge to build an example of calling the rust library from c++, but it didn't work.

rust lib

```
- foo.rs
pub fn add(a: i32, b: i32) -> i32
{
    return a + b;
}
```

c++ binary

```
- bridge.rs
#[cxx::bridge]
mod foo {
    extern "Rust" {
        fn add(a: i32, b: i32) -> i32;
    }
}


- main.cc
#include <stdio.h>
#include "bridge.rs.h"

int main(int argc, char** argv)
{
    printf("add(1, 2) == %d\n", add(1, 2));
    return 0;
}
```

I run `cxxbridge bridge.rs > bridge.rs.cc`

it's content:

```
#include <cstdint>

extern "C" {
::std::int32_t cxxbridge1$add(::std::int32_t a, ::std::int32_t b
} // extern "C"

::std::int32_t add(::std::int32_t a, ::std::int32_t b) noexcept
  return cxxbridge1$add(a, b);
}
```

I try build and link bridge.rs.o and foo rust lib, it will raise errors:

```
error: Undefined symbols for architecture x86_64:
  "_cxxbridge1$add", referenced from:
      add(int, int) in bridge.rs.cc.o
ld: symbol(s) not found for architecture x86_64
```

Where is _cxxbridge1$add defined? Did I write foo.rs incorrectly?

**Comment by xq114** [comment]
> Where is _cxxbridge1$add defined? Did I write foo.rs incorrectly?

From the examples it seems that the implementation of the rust functions must be written along with their declaration in the bridge.rs file, see https://github.com/XiangpengHao/cxx-cmake-example/blob/master/rust_part/src/lib.rs

**Comment by waruqi** [comment]
> https://github.com/XiangpengHao/cxx-cmake-example/blob/master/rust_part/src/lib.rs

Putting it together still does not generate the definition of _cxxbridge1$add

**Comment by waruqi** [comment]
```
#[cxx::bridge]
mod foo {
    extern "Rust" {
        fn add(a: i32, b: i32) -> i32;
    }
}

pub fn add(a: i32, b: i32) -> i32
{
    return a + b;
}
```

Maybe need use rustc to build crate:staticlib, but it need add some deps, e.g. cxx

```
error: error[E0433]: failed to resolve: use of undeclared crate or module `cxx`
 --> src/foo.rs:1:3
  |
1 | #[cxx::bridge]
  |   ^^^ use of undeclared crate or module `cxx`
```

**Comment by waruqi** [comment]
I probably know how to support it, but first I need to let xmake support rust's dependency package integration.

At present, we can only pull the rust dependency library through cargo, but this is equivalent to having executed `cargo build` to build a complete rust project. This does not seem to require xmake to do anything.

**Comment by xq114** [comment]
> I probably know how to support it, but first I need to let xmake support rust's dependency package integration.
> 
> At present, we can only pull the rust dependency library through cargo, but this is equivalent to having executed `cargo build` to build a complete rust project. This does not seem to require xmake to do anything.

All right, the rust part can be built by invoking cargo, but the linkage of the produced library and existing C++ target is still on xmake. BTW, it would be good if rust libraries (for example rav1e https://github.com/xiph/rav1e , which has a set of C API) can be integrated in xmake-repo with something like `import("package.tools.cargo").install(package)`

**Comment by waruqi** [comment]
I have supported it and support add cargo dependences to xmake targets

### Add cargo package dependences

example: https://github.com/xmake-io/xmake/tree/dev/tests/projects/rust/cargo_deps

```lua
add_rules("mode.release", "mode.debug")
add_requires("cargo::base64 0.13.0")
add_requires("cargo::flate2 1.0.17", {configs = {features = "zlib"}})

target("test")
    set_kind("binary")
    add_files("src/main.rs")
    add_packages("cargo::base64", "cargo::flate2")
```

### Use cxxbridge to call rust in c++

example: https://github.com/xmake-io/xmake/tree/dev/tests/projects/rust/cxx_call_rust_library

```lua
add_rules("mode.debug", "mode.release")

add_requires("cargo::cxx 1.0")

target("foo")
    set_kind("static")
    add_files("src/foo.rs")
    set_values("rust.cratetype", "staticlib")
    add_packages("cargo::cxx")

target("test")
    set_kind("binary")
    add_rules("rust.cxxbridge")
    add_deps("foo")
    add_files("src/main.cc")
    add_files("src/bridge.rsx")
```

foo.rs

```rust
#[cxx::bridge]
mod foo {
    extern "Rust" {
        fn add(a: i32, b: i32) -> i32;
    }
}

pub fn add(a: i32, b: i32) -> i32{
    return a + b;
}
```

bridge interface file in c++, bridge.rsx

```rust
#[cxx::bridge]
mod foo {
    extern "Rust" {
        fn add(a: i32, b: i32) -> i32;
    }
}
```

main.cc

```c++
#include <stdio.h>
#include "bridge.rs.h"

int main(int argc, char** argv)
{
    printf("add(1, 2) == %d\n", add(1, 2));
    return 0;
}
```

### Call c++ in rust

example: https://github.com/xmake-io/xmake/tree/dev/tests/projects/rust/rust_call_cxx_library

```lua
add_rules("mode.debug", "mode.release")

target("foo")
    set_kind("static")
    add_files("src/foo.cc")

target("test")
    set_kind("binary")
    add_deps("foo")
    add_files("src/main.rs")
```

main.rs

```rust
extern "C" {
	fn add(a: i32, b: i32) -> i32;
}

fn main() {
    unsafe {
	    println!("add(1, 2) = {}", add(1, 2));
    }
}
```

foo.cc

```c++
extern "C" int add(int a, int b)
{
    return a + b;
}
```
