### ISSUE TITLE
config.get 支持失败默认值或path.joinenv支持遍历nil

### ISSUE THREAD

**Issue by q962** [xmake-io/xmake#1801]
https://github.com/xmake-io/xmake/blob/ded70c3ac78a8df456d743788f37c328bcf7e570/xmake/core/project/config.lua#L33

```lua
function config.get(name, default_val)
    -- ...
   return default_val;
end
```
不填写 default_val 也是返回 nil，结果和预期一致

当想要和 os.setenv 配合工作时，例如想要让自定义路径在最前面 ` os.setenv("PATH", nil, os.getenv("PATH"))` 这会清空 PATH，不会跳过 nil

https://github.com/xmake-io/xmake/blob/ded70c3ac78a8df456d743788f37c328bcf7e570/xmake/core/base/path.lua#L166

才知道 ipairs 不支持遍历 nil，遇到 nil 终止遍历，path.joinenv 改用 pairs ？

**Comment by waruqi** [comment]
不需要 直接 `config.get(name) or "defaultval"` 就行了

> 才知道 ipairs 不支持遍历 nil，遇到 nil 终止遍历，path.joinenv 改用 pairs ？

array 里面不要放 nil，ipairs 用于遍历 array， pairs 用于遍历 keyval table 用途不同。

你array中间放 nil 有兼容性问题，不要这么干，luajit 不支持遍历带nil的

**Comment by q962** [comment]
用 config.get 获取 .config 里的值，它找不到值就返回 nil，需要使用不必要 `or ""` 来避免 nil 的产生。值不是必要的，用来覆盖系统的文件

> 你array中间放 nil 有兼容性问题，不要这么干，luajit 不支持遍历带nil的

是的，我去实验了。不知道对于可变参数 array 使用下标法，处理 nil，是否是好的选择。在调用时不用注意参数是否为 nil。

不过，问题解决了
