### ISSUE TITLE
option中c库函数检测请教

### ISSUE THREAD

**Issue by likun123687** [xmake-io/xmake#1804]
### 你在什么场景下需要该功能？
linux的accept4库函数检测.
想在option中检测accept4函数是否存在,原型如下:
```
#define _GNU_SOURCE             /* See feature_test_macros(7) */
#include <sys/socket.h>
int accept4(int sockfd, struct sockaddr *addr,
                   socklen_t *addrlen, int flags);
```
测试了两种方法都没通过检测:
第一种:
```
option("test")                                                                                      
       set_showmenu(true)                                                                              
       set_description("Enable or disable test")                                                       
       add_defines("TEST")                                                                             
       add_cincludes("sys/socket.h")                                                                   
       add_cfuncs('accept4')
```
第二种:
```
option("test")                                                                                      
       set_showmenu(true)                                                                              
       set_description("Enable or disable test")                                                       
       add_defines("TEST")                                                                             
       add_cincludes("sys/socket.h")                                                                   
       add_csnippets("accept", [[                                                                      
       #define _GNU_SOURCE                                                                             
       #include <sys/socket.h>                                                                         
       void test() {(void *)accept4;}                                                                  
       ]]) 
```

xmake f -c输出:
```
checking for platform ... linux
checking for architecture ... x86_64
checking for test ... no
```

想问下类似这种由宏开关控制的函数应该怎样检测呢?

**Comment by waruqi** [comment]
看下文档，有详细说明：https://xmake.io/#/zh-cn/manual/configuration_option?id=optionadd_cfuncs

检测错误 加 -vD 可以自己看

**Comment by likun123687** [comment]
> > 想问下类似这种由宏开关控制的函数应该怎样检测呢?
> 
> 看下文档，有详细说明：https://xmake.io/#/zh-cn/manual/configuration_option?id=optionadd_cfuncs
> 
> 检测错误 加 -vD 可以自己看

你说的详细说明是这里吗
![image](https://user-images.githubusercontent.com/12448588/140466810-bbe44686-5c05-45ec-a887-1141066ec044.png),没有解决我的问题啊,从文档只能想到
```
add_csnippets("accept", [[                                                                      
       #define _GNU_SOURCE                                                                             
       #include <sys/socket.h>                                                                         
       void test() {(void *)accept4;}                                                                  
       ]]) 
```
这种检测方法

**Comment by xq114** [comment]
```
option("test")                                   
       add_defines("_GNU_SOURCE")                                                                        
       add_cincludes("sys/socket.h")                                                                   
       add_cfuncs('accept4')
```
试试

**Comment by xq114** [comment]
后面用
```
if has_config("test") then
	add_defines("TEST")
	.. do whatever u want
end
```

**Comment by waruqi** [comment]
> -- 如果有些函数是宏定义 wrap 的，可以通过这种方式绕通过检测
sigsetjmp((void*)0, 0)

这不是写的很明显了么。。

```lua
       add_cfuncs("accept4(0,0,0,0)")
```

**Comment by waruqi** [comment]
> -- 也可以指定一个完整函数语句，例如：funcname{codebody}
sigsetjmp{sigsetjmp((void*)0, 0);}

```lua
       add_cfuncs("accept4{accept4(0,0,0,0); 完整片段}")
```

**Comment by likun123687** [comment]
> > -- 如果有些函数是宏定义 wrap 的，可以通过这种方式绕通过检测
> > sigsetjmp((void*)0, 0)
> 
> 这不是写的很明显了么。。
> 
> ```lua
>        add_cfuncs("accept4(0,0,0,0)")
> ```

```
option("test")                                                                                      
       set_showmenu(true)                                                                              
       set_description("Enable or disable test")                                                       
       add_cincludes("sys/socket.h")                                                                   
       add_cfuncs("accept4(0,0,0,0)")  
```
这是可以检测通过.

```
option("test")                                                                                      
       set_showmenu(true)                                                                              
       set_description("Enable or disable test")                                                       
       add_cincludes("sys/socket.h")                                                                   
       add_cfuncs("sdfsdfsdfsdf(0,0,0,0)")  
```
这样也通过检测了.不太清楚这是什么问题

**Comment by likun123687** [comment]
> ```
> option("test")                                   
>        add_defines("_GNU_SOURCE")                                                                        
>        add_cincludes("sys/socket.h")                                                                   
>        add_cfuncs('accept4')
> ```
> 
> 试试
这种方法可以.
add_defines检测函数的时候也会生效的吗?

**Comment by likun123687** [comment]
> ```
> option("test")                                   
>        add_defines("_GNU_SOURCE")                                                                        
>        add_cincludes("sys/socket.h")                                                                   
>        add_cfuncs('accept4')
> ```
> 
> 试试

这种方法可以.
add_defines检测函数的时候也会生效的吗?

**Comment by waruqi** [comment]
> > > -- 如果有些函数是宏定义 wrap 的，可以通过这种方式绕通过检测
> > > sigsetjmp((void*)0, 0)
> > 
> > 
> > 这不是写的很明显了么。。
> > ```lua
> >        add_cfuncs("accept4(0,0,0,0)")
> > ```
> 
> ```
> option("test")                                                                                      
>        set_showmenu(true)                                                                              
>        set_description("Enable or disable test")                                                       
>        add_cincludes("sys/socket.h")                                                                   
>        add_cfuncs("accept4(0,0,0,0)")  
> ```
> 
> 这是可以检测通过.
> 
> ```
> option("test")                                                                                      
>        set_showmenu(true)                                                                              
>        set_description("Enable or disable test")                                                       
>        add_cincludes("sys/socket.h")                                                                   
>        add_cfuncs("sdfsdfsdfsdf(0,0,0,0)")  
> ```
> 
> 这样也通过检测了.不太清楚这是什么问题

我这正常，确保加了 -c ，没用缓存结果

```console
$ xmake f -c -vD
checking for test ... no
> checking for c includes(sys/socket.h)
> checking for c funcs(sdfsdfsdfsdf)
checkinfo: ...amdir/core/sandbox/modules/import/core/tool/compiler.lua:84: @programdir/modules/cor
e/tools/gcc.lua:497: /var/folders/32/w9cz0y_14hs19lkbs6v6_fm80000gn/T/.xmake501/211105/_547C77E3DA
E144308CC997CF3BE7A650.c:8:5: error: implicit declaration of function 'sdfsdfsdfsdf' is invalid in
 C99 [-Werror,-Wimplicit-function-declaration]
    sdfsdfsdfsdf(0,0,0,0);
    ^
1 error generated.
```

**Comment by waruqi** [comment]
> > ```
> > option("test")                                   
> >        add_defines("_GNU_SOURCE")                                                                        
> >        add_cincludes("sys/socket.h")                                                                   
> >        add_cfuncs('accept4')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 试试
> 
> 这种方法可以. add_defines检测函数的时候也会生效的吗?

组合关系，具体看文档说明

**Comment by likun123687** [comment]
> > > > -- 如果有些函数是宏定义 wrap 的，可以通过这种方式绕通过检测
> > > > sigsetjmp((void*)0, 0)
> > > 
> > > 
> > > 这不是写的很明显了么。。
> > > ```lua
> > >        add_cfuncs("accept4(0,0,0,0)")
> > > ```
> > 
> > 
> > ```
> > option("test")                                                                                      
> >        set_showmenu(true)                                                                              
> >        set_description("Enable or disable test")                                                       
> >        add_cincludes("sys/socket.h")                                                                   
> >        add_cfuncs("accept4(0,0,0,0)")  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这是可以检测通过.
> > ```
> > option("test")                                                                                      
> >        set_showmenu(true)                                                                              
> >        set_description("Enable or disable test")                                                       
> >        add_cincludes("sys/socket.h")                                                                   
> >        add_cfuncs("sdfsdfsdfsdf(0,0,0,0)")  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样也通过检测了.不太清楚这是什么问题
> 
> 我这正常，确保加了 -c ，没用缓存结果
> 
> ```
> $ xmake f -c -vD
> checking for test ... no
> > checking for c includes(sys/socket.h)
> > checking for c funcs(sdfsdfsdfsdf)
> checkinfo: ...amdir/core/sandbox/modules/import/core/tool/compiler.lua:84: @programdir/modules/cor
> e/tools/gcc.lua:497: /var/folders/32/w9cz0y_14hs19lkbs6v6_fm80000gn/T/.xmake501/211105/_547C77E3DA
> E144308CC997CF3BE7A650.c:8:5: error: implicit declaration of function 'sdfsdfsdfsdf' is invalid in
>  C99 [-Werror,-Wimplicit-function-declaration]
>     sdfsdfsdfsdf(0,0,0,0);
>     ^
> 1 error generated.
> ```
这是我的xmake.lua
![image](https://user-images.githubusercontent.com/12448588/140471184-c1a8fa46-7934-40be-9cb1-bbde0913ea4a.png)

这是输出
![image](https://user-images.githubusercontent.com/12448588/140471539-72c9dcaa-a6f9-436d-a55f-4e16dac8b649.png)
神奇了..

**Comment by waruqi** [comment]
编译器不同，你这 gcc 编译未定义 func 调用，gcc 都没报错，只是报了一个警告而已，你仔细看下 输出


这跟 xmake 没啥关系，如果不是宏定义的 func，尽量直接 `add_cfuncs("xxx")` ，会作为 变量取址来引用，而不是函数调用。

**Comment by likun123687** [comment]
> 编译器不同，你这 gcc 编译未定义 func 调用，gcc 都没报错，只是报了一个警告而已，你仔细看下 输出
> 
> 这跟 xmake 没啥关系，如果不是宏定义的 func，尽量直接 `add_cfuncs("xxx")` ，会作为 变量取址来引用，而不是函数调用。

accept4不是宏啊,就是一个函数

**Comment by waruqi** [comment]
哦 看错了，那就直接走        `add_defines("_GNU_SOURCE")` 呗

**Comment by xq114** [comment]
这里确实文档有问题，我在文档里没看到option:add_defines接口的说明，这里二义性应该强调的（即通过`add_options`加到target里面/直接被用在check_xxx里面）

**Comment by waruqi** [comment]
> 这里确实文档有问题，我在文档里没看到option:add_defines接口的说明，这里二义性应该强调的（即通过`add_options`加到target里面/直接被用在check_xxx里面）

option 的文档目前是不全的。不过 https://xmake.io/#/zh-cn/manual/configuration_option?id=option 这里有一些 defines 的例子说明。。

**Comment by likun123687** [comment]
> 编译器不同，你这 gcc 编译未定义 func 调用，gcc 都没报错，只是报了一个警告而已，你仔细看下 输出
> 
> 这跟 xmake 没啥关系，如果不是宏定义的 func，尽量直接 `add_cfuncs("xxx")` ，会作为 变量取址来引用，而不是函数调用。

check_xxx把警告当成错误会不会好些

**Comment by waruqi** [comment]
> > 编译器不同，你这 gcc 编译未定义 func 调用，gcc 都没报错，只是报了一个警告而已，你仔细看下 输出
> > 这跟 xmake 没啥关系，如果不是宏定义的 func，尽量直接 `add_cfuncs("xxx")` ，会作为 变量取址来引用，而不是函数调用。
> 
> check_xxx把警告当成错误会不会好些

大部分警告不一定就是错误，如果 func 存在，确实没问题，一个 include 引入 n多无关警告。。一样检测的不对。

**Comment by waruqi** [comment]
如果没啥问题，这里先 close 。。你先用  add_defines 就好了
