### ISSUE TITLE
environment variable VSINSTALLDIR is missing from xrepo virtualenv

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1807]
### 描述问题

![image](https://user-images.githubusercontent.com/42310255/140542623-358b1489-3ca5-4677-87a5-cfbfb4353b3f.png)
![image](https://user-images.githubusercontent.com/42310255/140542730-f1c7083a-2d01-4340-a864-d25b6afd5f88.png)

如图，cl可以识别到说明加载了msvc的环境，但环境里缺少VSINSTALLDIR环境变量

### 期待的结果

xrepo加载的msvc环境可以与vs环境一致

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.9
- xmake运行平台：windows
- xmake目标平台：windows

**Comment by waruqi** [comment]
你可以试试在这里加上 https://github.com/xmake-io/xmake/blob/95dea5af25edb9f1eda15ad8412342e26ef39525/xmake/toolchains/msvc/load.lua#L65

**Comment by xq114** [comment]
https://github.com/xmake-io/xmake/pull/1808
