### ISSUE TITLE
pkgconf related utilities should be available on windows

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1809]
### 描述讨论详情
pkg-config在windows上不可用，但相同功能的pkgconf是可以在windows上使用的；与pkg-config相关的一些功能，如`add_requires`、`utils.install.pkgconfig_importfiles`等也应该在windows上可用，只需要在找pkg-config的时候fallback到pkgconf就可以了

**Comment by waruqi** [comment]
暂时没环境测试，你可以试下，不对的地方可以直接提 pr 到 pkgconf 分支改进。。

https://github.com/xmake-io/xmake/pull/1810

目前 pc 生成都是带的 -L ，如果走 pkgconf 在 windows 上，到底是用 -L 还是需要搞成 -libpath: ？

**Comment by xq114** [comment]
> 目前 pc 生成都是带的 -L ，如果走 pkgconf 在 windows 上，到底是用 -L 还是需要搞成 -libpath: ？

https://github.com/mesonbuild/meson/blob/master/mesonbuild/dependencies/pkgconfig.py#L208-L222

理论上是要-libpath的，但是现在windows上的pkgconf实际上就只有meson在用，用的方法仍是从-L里面自己去找对应的库文件，不支持-libpath。不过meson的这个功能也并不成熟，仍是一个open issue，用的人也并不多，所以xmake只需要做到自洽应该就好了，即自己生成的.pc文件可以用`add_requires`找到就行，其他在windows上写.pc文件可以按照xmake的标准来

https://github.com/mesonbuild/meson/issues/4029

**Comment by waruqi** [comment]
那还是先继续 -L 好了

**Comment by waruqi** [comment]
先这样吧，理论上应该支持了，但是没详测，有问题再开
