### ISSUE TITLE
support manual registration and unregistration of shell-related functions

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1817]
### 你在什么场景下需要该功能？

目前xmake的shell completion和xrepo env shell（在UNIX-like系统上）的feature会修改用户的shell配置。但目前这两项功能只有通过powershell/bash安装xmake时才能实现，对离线安装、从安装包安装、从包管理器安装等途径安装的xmake不起作用。另一个问题是，安装这两项功能后，在卸载xmake时需要用户手动清理，而不能一键取消安装。

### 描述可能的解决方案

提供命令`xmake shell init`和`xmake shell reset`命令（也可以用别的接口）来安装/清除系统上的shell相关功能

### 描述你认为的候选方案

提供几个脚本，需要安装/清除shell功能时由用户手动运行

**Comment by waruqi** [comment]
windows 上看能否搞进 installer.nsi 去安装卸载。

这种，就没必要再去格外加 action了，`xmake update --uninstall` 原本就有卸载支持，你可以在这个里面改进下，多加一些清理逻辑

**Comment by xq114** [comment]
> windows 上看能否搞进 installer.nsi 去安装卸载。
> 
> 这种，就没必要再去格外加 action了，`xmake update --uninstall` 原本就有卸载支持，你可以在这个里面改进下，多加一些清理逻辑

确实可以复用update的action，但是仅仅搞进installer.nsi是不够的，对其他包管理器安装的xmake也应该要支持的。能不能加一个`xmake update --init`来安装当前版本的shell completion，`xmake update -i -s <xmakever>`升级的同时也重新安装shell feature？

**Comment by xq114** [comment]
要自动管理script片段， 还需要有一些标识符，
```
# >>> xmake >>>
# The following section is managed by xmake. Do not edit!
...
# <<< xmake <<<
```
参考 https://github.com/conda/conda/blob/master/conda/core/initialize.py

**Comment by waruqi** [comment]
> > windows 上看能否搞进 installer.nsi 去安装卸载。
> > 这种，就没必要再去格外加 action了，`xmake update --uninstall` 原本就有卸载支持，你可以在这个里面改进下，多加一些清理逻辑
> 
> 确实可以复用update的action，但是仅仅搞进installer.nsi是不够的，对其他包管理器安装的xmake也应该要支持的。能不能加一个`xmake update --init`来安装当前版本的shell completion，`xmake update -i -s <xmakever>`升级的同时也重新安装shell feature？

xmake update 可以加参数扩展
