### ISSUE TITLE
CMakeLists.txt generator do not use precompiled headers feature of CMake

### ISSUE THREAD

**Issue by TNtube** [xmake-io/xmake#1819]
### Describe the bug

I use xmake in CLion, so I use the CMakeLists generator given by xmake to compile my project using CMake on CLion.
But I noticed that when I'm using precompiled headers in my xmake.lua with the line 
`set_pcxxheader("Cardia/include/cdpch.hpp")`, it doesn't translate it in cmake.

### Expected behavior

Find in the CMakeLists.txt generated 
```cmake
target_precompile_headers(Cardia
  PUBLIC
    cdpch.hpp
)
```

### Error output

No error, just an unexpected behavior

### Related Environment

- xmake version: xmake v2.5.9+dev.66c32d141
- os: Windows
- target platform: Windows

**Comment by waruqi** [comment]
I have added it. https://github.com/xmake-io/xmake/commit/dd91627cc9baf3a1376b617c76358f7ce99ba2cd

**Comment by TNtube** [comment]
Thank you very much !
