### ISSUE TITLE
支持编译linux kernel module和windows驱动程序吗？如果目前不支持，预计什么时候支持

### ISSUE THREAD

**Issue by rehuofoods** [xmake-io/xmake#1820]

**Comment by waruqi** [comment]
windows 驱动老早支持了 ，具体看文档：https://xmake.io/#/zh-cn/guide/project_examples?id=wdk%e9%a9%b1%e5%8a%a8%e7%a8%8b%e5%ba%8f

linux 驱动没试过，自己走 xmake.lua + rule 自定义去配置，肯定也能支持的，顶多就是没有原生内置支持配置方便而已。。

如果要内置提供支持，可以这里备着。。但具体支持时间点，不好说，看我个人时间安排。。有可能会等很久。

**Comment by waruqi** [comment]
下个版本会支持上 linux 驱动构建，目前已经初步跑通，具体进度见：https://github.com/xmake-io/xmake/issues/1902
