### ISSUE TITLE
Add feature to show all supported archs

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1829]
### 你在什么场景下需要该功能？

https://xmake.io/#/?id=supported-platforms

xmake支持的arch很多，但关于各系统上arch的命名并不完全统一，文档中supported-platform列出了一些但并不完整（mips/riscv等都没有写出来）。这样在xmake.lua中写is_arch判断时会有 无法确定是否涵盖所有可以支持的arch；对特定的一些arch不清楚它们在xmake中的命名 等问题

### 描述可能的解决方案

加一个`xmake show -l architectures`命令

### 描述你认为的候选方案

在文档中加一个supported architectures板块

**Comment by waruqi** [comment]
xmake f --help 里面有完整 每个plat对应的 arch列表 show里面之后也可以加上

**Comment by waruqi** [comment]
> 加一个xmake show -l architectures命令

我也加上了
