### ISSUE TITLE
函数中漏写参数不报错或者警告

### ISSUE THREAD

**Issue by SmartElec** [xmake-io/xmake#1832]
### 描述问题

编译snprintf(buffer, 64,"%s/%s", str1, str2);
但是当我少写了一个参数64的时候snprintf(buffer,"%s/%s", str1, str2);
编译并没有任何警告或者报错。

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 错误信息

没有任何错误信息

如果日志太多，可以上传附件，但必须完整，否则一率标记为 Invalid。

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.5.9
- xmake运行平台：Ubuntu
- xmake目标平台：arm-linux-gnueabihf-

### 其他信息

请提供关键的 xmake.lua 配置内容，或者完整 xmake.lua，也可以是其他附加信息帮助我们诊断问题(比如截图，xmake.lua或者可复现的demo)，以及你遇到的问题的一些背景信息。

**Comment by waruqi** [comment]
xmake -w 看警告，或者全局配置 xmake g --build_warning=y 启用实时警告输出

**Comment by SmartElec** [comment]
> xmake -w 看警告，或者全局配置 xmake g --build_warning=y 启用实时警告输出

set_warnings不起作用吗，就是希望和gcc的选项类似的，并且可屏蔽某些类型的警告。

**Comment by OuYangPaste** [comment]
起作用，但是如 waruqi 所说要 xmake -w  或者 xmake g --build_warning=y 才能看到 warnning，就如同一些项目的 makefile, 需要手动 增加如 v=1 或者 verbose=1 才能输出详细信息一样，为了更整洁的显示

**Comment by waruqi** [comment]
> > xmake -w 看警告，或者全局配置 xmake g --build_warning=y 启用实时警告输出
> 
> set_warnings不起作用吗，就是希望和gcc的选项类似的，并且可屏蔽某些类型的警告。

set_warnings 只是对编译器生效，让编译器爆出警告，但是 xmake 默认不会让你看到

但是由于大部分情况下，程序警告输出都会狂刷屏，所以 xmake 默认编译是不会让你看到实时的 编译器警告输出的，除非你真的想看，那就加 xmake -w 或者 xmake g --build_warning=y 全局开启 实时警告输出的行为。
