### ISSUE TITLE
xmake 更新问题

### ISSUE THREAD

**Issue by as564335sa** [xmake-io/xmake#1840]
换了台电脑想更新xmake dev，使用新支持的armcc，执行xmake update dev会安装，安装成功了，但是还是没有设置runtime功能，执行xmake update -s dev报错，管理员运行等等都试过了就是不行，这是什么鬼？
![QQ截图20211117222906](https://user-images.githubusercontent.com/35949162/142219896-3a9fa1d7-f326-4f46-9e68-5e2e5c9a3428.png)

**Comment by waruqi** [comment]
> 换了台电脑想更新xmake dev，使用新支持的armcc，执行xmake update dev会安装，安装成功了，但是还是没有设置runtime功能，执行xmake update -s dev报错，管理员运行等等都试过了就是不行，这是什么鬼？

你全量更新的 win 版本，需要等 action ci 上跑完，才能拉取到更新后的版本。。之前让你全量更新的 master 版本，这个跑完了，但是 dev 的 ci 是没跑的。。你看下 action 那一栏，最近一天都是失败的。。。

因为我目前配置的ci策略，dev/master同时提交，只会跑最近一次 commit ，之前的 ci 会自动cancel 节省ci资源和时间。。所以你得更新 xmake update master

除非等到后面那次提交 dev 它 ci 全跑过了。你才能全量更新 dev 版本
