### ISSUE TITLE
Windows下debug模式下依赖的第三方库没有将 compile.xxx.pdb 拷贝至lib目录下

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#1845]
windows下依赖其他库时（可能也是xmake编译的，cmake的没试过）如：

target("AAA")
     add_packages("xxxx")

此时用debug编译AAA，依赖的xxx库编译后，其compile.xxx.pdb没有拷贝至安装目录的lib下，导致最终链接时会报告警，如：
![图片](https://user-images.githubusercontent.com/1145161/142769206-5b49354c-6498-4d11-9c27-efbb6665f66f.png)

**Comment by waruqi** [comment]
请提供完整可复现的 demo

**Comment by fasiondog** [comment]
add_rules("mode.debug", "mode.release")

add_requires("co", {configs={shared=false, debug=true}})

target("hello")
    set_kind("binary")
    add_packages("co")

    add_files("src/*.cpp")

这样没有链接告警，但 .xmake 安装的packages/co lib 下确实没有 compile.co.pdb 文件。cache 下编译出的lib下是存在pdb文件的

**Comment by waruqi** [comment]
目前包安装，还不会安装 库的 pdb 文件 等后续有时间改进吧，最近没啥空。

**Comment by waruqi** [comment]
我改进过了，你更新下 xmake 再试试

**Comment by waruqi** [comment]
应该可以了的，不行再开

**Comment by fasiondog** [comment]
好的，谢谢
