### ISSUE TITLE
错误：在PC ubuntu下安装Armv7版本protobuf-cpp出错

### ISSUE THREAD

**Issue by zhangbowei** [xmake-io/xmake#1853]
问题：请问如何在ubuntu18下交叉编译armv7  ubuntu16下的程序（主要是protobuf-cpp、boost、ompl，先搞定protobuf吧o(╥﹏╥)o）
执行命令：xrepo install -p linux -a armv7 --sdk=/usr/local/toolchain/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf protobuf-cpp
报错：
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> protobuf-cpp 3.17.3 
please input: y (y/n/m)

  => install protobuf-cpp 3.17.3 .. failed

/home/test/.xmake/packages/p/protobuf-cpp/3.17.3/06112fcf1f2e4395b92df6a76b697b30/lib/libprotobuf.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status
if you want to get more verbose errors, please see:
  -> /home/test/.xmake/cache/packages/2111/p/protobuf-cpp/3.17.3/installdir.failed/logs/install.txt
error: install failed!
error: execv(xmake require -j 2 --extra={system=false} protobuf-cpp) failed(255)
图片：
![image](https://user-images.githubusercontent.com/14348480/142976452-e31eaa55-fc2d-47b8-bad3-94707c7a944d.png)

**Comment by zhangbowei** [comment]
And I use xmake，the same error happend
It's my xmake.lua
﻿
add_requires("vcpkg::ompl")
add_requires("protobuf-cpp")
add_requires("vcpkg::eigen3")
--add_packages("boost")

target("console_c++")
    set_kind("binary")
    set_languages("c++11")
    add_includedirs("src") 
    add_packages("protobuf-cpp")
    add_packages("vcpkg::ompl")
    add_packages("boost")
    add_packages("vcpkg::eigen3")
    add_files("src/*.cpp")
    add_files("proto/*.proto", {rules = "protobuf.cpp", proto_rootdir = "proto"})

**Comment by zhangbowei** [comment]
xmake f -p linux -a armv7 --sdk=/usr/local/toolchain/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf

![image](https://user-images.githubusercontent.com/14348480/142977245-efc7a788-5362-4088-a898-189844659aad.png)

但是我直接安装PC上的依赖包protobuf-cpp然后xmake编译是没有问题的，比如xmake f -p linux 然后 xmake.

**Comment by xq114** [comment]
交叉编译应该是-p cross才对吧

**Comment by waruqi** [comment]
目前 protobuf-cpp 包，仓库中，还没加上交叉编译支持，你可以提 pr 到 https://github.com/xmake-io/xmake-repo/blob/master/packages/p/protobuf-cpp/xmake.lua#L47 修改，让其支持 on_install("cross") 交叉编译安装支持，也具体是否能支持，还得看 protobuf 库自身是否能够支持，也需要加patch，具体看每个包的情况而定。。

通常，autoconf/cmake 维护的包，切到cross 编译，xmake 都会自动透传交叉工具链信息，但库代码和编译选项的支持和调整，你得自己看下

**Comment by zhangbowei** [comment]
> 对，先得切到 -p cross 平台，否则依赖包还是 host 编译
> 
> 目前 protobuf-cpp 包，仓库中，还没加上交叉编译支持，你可以提 pr 到 https://github.com/xmake-io/xmake-repo/blob/master/packages/p/protobuf-cpp/xmake.lua#L47 修改，让其支持 on_install("cross") 交叉编译安装支持，也具体是否能支持，还得看 protobuf 库自身是否能够支持，也需要加patch，具体看每个包的情况而定。。
> 
> 通常，autoconf/cmake 维护的包，切到cross 编译，xmake 都会自动透传交叉工具链信息，但库代码和编译选项的支持和调整，你得自己看下

请问假如是一个cmake的包如ompl（运动学包），我需要先自己交叉编译好它，然后make install后，再xmake -p cross --sdk=XXX是吧？

**Comment by waruqi** [comment]
不是，提交 xmake-repo 仓库收录，通常 xmake 会自动对接 交叉编译给 cmake 具体参考现有的一些包 https://github.com/xmake-io/xmake-repo/blob/d6067a470431f659a5830af5c5cd8bae171246f4/packages/l/libomp/xmake.lua#L18
