### ISSUE TITLE
`add_deps` 未按照顺序触发

### ISSUE THREAD

**Issue by lvzixun** [xmake-io/xmake#1856]
### 描述问题

`add_deps`接口在构建时未按照传入的target顺序执行。
如下测试用例:
~~~.lua
target("test_dep")
    set_kind("phony")
    add_deps("test2", "test1")


target("test1")
    set_kind("phony")
    after_build(function ()
        print("test1111111")
    end)


target("test2")
    set_kind("phony")
    after_build(function ()
        print("test2222222")
    end)
~~~

执行的结果如下:
```
test1111111
test2222222
[100%]: build ok!
```
### 期待的结果
期望能够根据传入的`add_deps` 的顺序来依次触发`xxx_build`。
```
test2222222
test1111111
```

### 相关环境

- xmake版本： 2.5.9
- xmake运行平台：windows
- xmake目标平台：windows

**Comment by waruqi** [comment]
那你要在 test2 上加 add_deps("test1") 才行，否则这两是并行的，没有依赖关系，顺序未定义

**Comment by lvzixun** [comment]
> 那你要在 test2 上加 add_deps("test1") 才行，否则这两是并行的，没有依赖关系，顺序未定义

能不能支持下顺序？因为如果期望顺序依赖的话 就只能一个个target 加。还是挺麻烦的

**Comment by waruqi** [comment]
> > 那你要在 test2 上加 add_deps("test1") 才行，否则这两是并行的，没有依赖关系，顺序未定义
> 
> 能不能支持下顺序？因为如果期望顺序依赖的话 就只能一个个target 加。还是挺麻烦的

目前的设计就是这样，根据依赖图控制构建顺序和并行编译

没必要一个个加，test_dep 只需要加 test2，test2 只需要加 test1，你都放在test_deps下 也就这点字符量

而且 如果有很多target都需要加相同，可以直接放root域，也就加一次

这块肯定不会改的

**Comment by lvzixun** [comment]
all顺序依赖test1和test2，但是test2和test1之间没有依赖关系。构建有可能构建all，也有可能独立构建test2。如果在test2里面加上依赖test1，构建test2的时候就必然要构建test1了。

**Comment by waruqi** [comment]
既然没有依赖关系，为什么还要控制 以次触发 build，这个就是依赖

xmake里面构建顺序就是依赖关系，只有完全并行，两者间不依赖构建顺序，才是没有依赖

add_deps就是用来控制构建的依赖顺序用的
