### ISSUE TITLE
期望`addfiles` 接口的`always_added` 配置能够支持模式匹配

### ISSUE THREAD

**Issue by lvzixun** [xmake-io/xmake#1857]
### 你在什么场景下需要该功能？
对于动态生成的文件类型，尽管有`always_added` 配置可以设置，但是不支持模式匹配还是挺不方便的。

### 描述可能的解决方案
 期望在`add_files` 的时候能够支持模式匹配，如：`add_files("gen/*.dsl", {always_added = true})`

**Comment by waruqi** [comment]
暂时支持不了，模式匹配是在 on_load 阶段就完成了，后面build阶段的动态生成时机过于滞后，所以我才加了个 always_added 来忽略早期匹配阶段 file not found的情况。

**Comment by xq114** [comment]
cmake里面有用cmake调用cmake来进行多段生成+编译的解决办法：
```
add_custom_command(${CMAKE_COMMAND} -S ${CURRENT_SOURCE_DIR} -H ${CMAKE_BUILD_DIR}/subcommand)
```
不知道xmake能不能用类似的方法解决？

**Comment by waruqi** [comment]
> cmake里面有用cmake调用cmake来进行多段生成+编译的解决办法：
> 
> ```
> add_custom_command(${CMAKE_COMMAND} -S ${CURRENT_SOURCE_DIR} -H ${CMAKE_BUILD_DIR}/subcommand)
> ```
> 
> 不知道xmake能不能用类似的方法解决？

不了解，给个完整demo? 

另外，走自定义 rule 就可以支持滞后的动态生成和模式匹配
