### ISSUE TITLE
关于生成的.o文件名问题

### ISSUE THREAD

**Issue by Dozingfiretruck** [xmake-io/xmake#1859]
您好，之前我们发现有一个xmake编译的静态库编译无法运行，查询后发现
xmake生成的.o是 原文件名 + .o, 例如 abc.S 生成 abc.S.o
makefile对同一个.S文件生成的是 abc.o , 没有中间的.S

然后原本的ld文件里面是根据 KEEP(*startup.o)(XXXX) 来配置的, 所以 startup.S.o 匹配不上
请问xmake编译生成的.o文件可以自定义名么？或者生成xx.o而不是xx.s.o
谢谢

**Comment by waruqi** [comment]
加 .S 是因为，同目录下，如果有 foo.c, foo.cpp, foo.S ，就能够避免冲突。。

不过特殊项目，可以自己写点脚本固定下，指定文件的obj名。

```lua
    after_load(function (target)
        for _, sourcebatch in pairs(target:sourcebatches()) do
            if sourcebatch.sourcekind == "as" then -- only asm files
                for idx, objectfile in ipairs(sourcebatch.objectfiles) do
                    sourcebatch.objectfiles[idx] = objectfile:gsub("%.S%.o", ".o")
                end
            end
        end
    end)
```

你可以全改，也可以仅仅改 startup.S，自己调整下脚本

**Comment by Dozingfiretruck** [comment]
感谢，可以用了
