### ISSUE TITLE
path.path.relative 返回结果不符合预期

### ISSUE THREAD

**Issue by ethanvc** [xmake-io/xmake#1860]
### 描述问题
考虑如下的目录结构：
--a
  |--b
     |--c.proto
--xmake.lua
xmake.lua内容如下：
```
set_project("test")

add_requires("protobuf-cpp")

target("proto")
    set_kind("binary")
    add_files("a/b/*.cpp")
    add_files("a/b/*.proto", {rules = "protobuf.cpp"})
    add_packages("protobuf-cpp")
```
在rules/protobuf/proto.lua中，做如下调用：
local proto_relative_path = path.relative(sourcefile_proto, "$(projectdir)")
print("xxx " .. proto_relative_path)
### 期待的结果
期待print输出的proto_relative_path的路径为：a/b/c.proto。
实际结果为：../a/b/c.proto

### 其它
path.absolute也有类似的问题，比如path.absolute("$(projectdir") 返回的结果也不正确(c:\test\c:\test)。

**Comment by waruqi** [comment]
path 模块不支持内建变量，如果已经在脚本域，请尽量直接使用 os.projectdir() ，而不是用内建变量，那个主要是给描述域用的，在脚本域，只有少部分 os.cp/os.mv 等接口才支持。
