### ISSUE TITLE
需要使用xmake 在ubuntu18交叉编译代码至armv7

### ISSUE THREAD

**Issue by zhangbowei** [xmake-io/xmake#1861]
问题：需要使用xmake 在ubuntu18交叉编译代码至armv7

1. 使用vcpkg 安装了 ompl:arm-linux  protobuf:arm-linux包 ，还有ompl:x64-linux  protobuf:x64-linux
   然后使用xmake l find_packages vcpkg::ompl可以找到x64-linux但无法找到arm-linux的。
2. 使用 xmake g --vcpkg=/home/test/package/vcpkg/installed/arm-linux依然无法找到
3. 找到包后准备执行xmake f -p linux -a armv7 --sdk=/usr/local/toolchain/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf完成编译

请问命令使用有什么问题吗？(顺带说一下，xmake f -p linux是可以的，因为x64_linux的包能找到）

这是一些补充信息：
xmake.lua

﻿add_requires("vcpkg::protobuf")
add_requires("vcpkg::ompl")
-- add_requires("boost")

target("console_c++")
    set_kind("binary")
    set_languages("c++11")
    add_includedirs("src") 
    add_includedirs("proto") 
    add_packages("vcpkg::protobuf")
    add_packages("vcpkg::ompl")
    -- add_packages("boost")
    add_files("src/*.cpp")
    add_files("src/*.pb.cc"})

vcpkg/installed目录
![image](https://user-images.githubusercontent.com/14348480/143161333-56a266be-58d9-4eef-a493-4768eac41e0e.png)

**Comment by waruqi** [comment]
切到 `xmake f -p linux -a armv7 -cvD` 试下。。

是根据 vcpkg/installed/vcpkg/info 里面的 list 文件找的，如果还不行，你可以自己调下下面的这个文件

https://github.com/xmake-io/xmake/blob/679c463806be46f4c0d3184bcbe56dbd6a4e1598/xmake/modules/package/manager/vcpkg/find_package.lua#L81

**Comment by zhangbowei** [comment]
arm-linux是有的，请问具体怎么设置？
还有命令xmake f -p linux -a armv7 -cvD试过了，还是让我重新下载，我这个xmake f -p linux -a armv7 --sdk=/usr/local/toolchain/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf命令没问题吧？
还有vcpkg的包我是 vcpkg install ompl:arm-linux安装的，成功后弹出
The package protobuf provides CMake targets:

    find_package(protobuf CONFIG REQUIRED)
    target_link_libraries(main PRIVATE protobuf::libprotoc protobuf::libprotobuf protobuf::libprotobuf-lite)

要怎么和xmake结合起来呢？
这是我的src只有一个main函数

```c++
#include <iostream>
// #include "conio.h"
#include "people.pb.h"  
#include <ompl/base/spaces/ReedsSheppStateSpace.h>
#include <ompl/base/spaces/DubinsStateSpace.h>
#include <ompl/base/spaces/SE2StateSpace.h>
#include <ompl/base/State.h>
// #include <boost/heap/binomial_heap.hpp>
#include "test.h"


typedef ompl::base::SE2StateSpace::StateType State;

using namespace std;

int main(int argc, char** argv)
{
    ros::People p;
    string test;  
    p.set_name("Hideto");  
    p.set_id(123);  
    p.set_email("hideto.bj@gmail.com");  
    p.SerializeToString(&test);  
    cout << test << endl;
    cout << "hello world!" << endl;
    return 0;
}

```

![1637731181(1)](https://user-images.githubusercontent.com/14348480/143180245-dbddf62a-8425-454d-991d-f4469d3e83e0.png)

**Comment by waruqi** [comment]
你调下 https://github.com/xmake-io/xmake/blob/679c463806be46f4c0d3184bcbe56dbd6a4e1598/xmake/modules/package/manager/vcpkg/find_package.lua#L81

**Comment by zhangbowei** [comment]
更改后执行命令报错>

test@ubuntu:~/code/test/hello$ xmake f -p linux -a armv7 --sdk=/usr/local/toolchain/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf

error: ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:56: attempt to concatenate local 'p' (a nil value)
stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:829: in function 'raise'
	...mdir/core/sandbox/modules/import/core/base/scheduler.lua:56: in function 'co_start_withopt'
	@programdir/modules/private/async/runjobs.lua:199: in function <@programdir/modules/private/async/runjobs.lua:159>
	[C]: in function 'trycall'
	@programdir/core/base/scheduler.lua:487: in function 'co_group_begin'
	...mdir/core/sandbox/modules/import/core/base/scheduler.lua:94: in function 'co_group_begin'
	@programdir/modules/private/async/runjobs.lua:159: in function 'runjobs'
	...modules/private/action/require/impl/install_packages.lua:535: in function 'install_packages'
	@programdir/modules/private/action/require/install.lua:85: in function 'install_packages'
	@programdir/actions/config/main.lua:408: in function <@programdir/actions/config/main.lua:249>
	[C]: in function 'load'
	@programdir/core/base/task.lua:519: in function 'run'
	@programdir/core/main.lua:278: in function 'cotask'
	@programdir/core/base/scheduler.lua:371: in function <@programdir/core/base/scheduler.lua:368>

![image](https://user-images.githubusercontent.com/14348480/143183573-6a745765-ad30-4e2e-bf2d-139544d29295.png)


![image](https://user-images.githubusercontent.com/14348480/143183259-8c7f82f5-d773-41c3-b515-45e2c3008f59.png)

**Comment by zhangbowei** [comment]
改完后可以找到了，但xmake时报错

另外，在xmake官方文档中是有protobuf项目的使用方式（protobuf-cpp库不支持交叉编译），并且我在xmake目标本机也成功了，但在交叉编译时失败（参考：https://xmake.io/#/zh-cn/guide/project_examples?id=protobuf%e7%a8%8b%e5%ba%8f）

故使用vcpkg的protobuf:arm-linux，将其作为常规包方式调用，但报错google头文件没找到。

请问要怎么配置？

![image](https://user-images.githubusercontent.com/14348480/143184949-bb1b5a31-0813-4812-9029-756c47f11735.png)

**Comment by waruqi** [comment]
> 改完后可以找到了，但xmake时报错

改了啥，报什么错，都没说，我哪知道咋回事

> 
> 另外，在xmake官方文档中是有protobuf项目的使用方式（protobuf-cpp库不支持交叉编译），并且我在xmake目标本机也成功了，但在交叉编译时失败（参考：[https://xmake.io/#/zh-cn/guide/project_examples?id=protobuf%e7%a8%8b%e5%ba%8f）](https://xmake.io/#/zh-cn/guide/project_examples?id=protobuf%e7%a8%8b%e5%ba%8f%EF%BC%89)
> 
> 故使用vcpkg的protobuf:arm-linux，将其作为常规包方式调用，但报错google头文件没找到。
> 
> 请问要怎么配置？
> 
> ![image](https://user-images.githubusercontent.com/14348480/143184949-bb1b5a31-0813-4812-9029-756c47f11735.png)

同样，调下 vcpkg/find_package.lua 看下找到的 includedirs 结果，然后自己对下路径

**Comment by zhangbowei** [comment]
PC ubuntu18

我修改了vcpkg/find_package.lua文件，编译通过（修改的内容如下：
```
 if (plat == "windows" and line:endswith(".lib")) or line:endswith(".a") or line:endswith(".so")  or line:endswith(".so.1.5.1")  or line:endswith(".so.16") then
                if line:find(triplet .. (mode == "debug" and "/debug" or "") .. "/lib/", 1, true) then
```
然后编译通过，但执行时报错.so文件找不到，于是
export LD_LIBRARY_PATH=/home/test/package/vcpkg/installed/x64-linux/lib
后执行成功。

问题：
1. vcpkg install ompl:x64-linux为什么生成了动态库（vcpkg install protobuf:x64-linux是静态的即*.a文件）
2. xmake是不是我用法不对，这种动态库有相应的使用方式？

补充：ompl_1.5.1_x64-linux.list内容（即find_package.lua读入文件）

![image](https://user-images.githubusercontent.com/14348480/143404585-c7530fb9-a84a-4ac8-906f-6f5b3083f036.png)

**Comment by waruqi** [comment]
> vcpkg install ompl:x64-linux为什么生成了动态库（vcpkg install protobuf:x64-linux是静态的即*.a文件）

这个你得到 vcpkg 上去问，目前 win 上我是明确加了 -static 来区分的，linux 是否 vcpkg 也支持区分，我不清楚，你可以研究下

另外，你不是反馈 arm linux的问题么，怎么又变 x64 了。。倒底要调啥？ 多个问题 不要混一起，很乱，我都不知道 你要调哪个问题，不同的问题 开不同的 issues。

> xmake是不是我用法不对，这种动态库有相应的使用方式？

你也没说清楚你想怎么个用法，xmake run? 还是自己运行？还是其他。。。。

xmake run 目前只有 xmake-repo 包才会自动设置 LD_LIBRARY_PATH，或者 你可以自己 xmake.lua 里面设置 runenvs

**Comment by waruqi** [comment]
vcpkg/find_package.lua 的 so 过滤我刚dev加上了
