### ISSUE TITLE
报错unable to rename

### ISSUE THREAD

**Issue by Dozingfiretruck** [xmake-io/xmake#1864]
您好，我添加了一些静态库，走add_deps
![image](https://user-images.githubusercontent.com/24759100/143673757-f58b2ce7-10dd-4623-b434-55e2e8b5b3c1.png)
报错unable to rename
![image](https://user-images.githubusercontent.com/24759100/143673771-3d94d58f-4ce0-4021-9533-aa4d77f63499.png)
![image](https://user-images.githubusercontent.com/24759100/143673777-49dfc910-de8a-4f52-96f7-f6cb86d439b4.png)
走-j1单线程编译无问题，请问有什么办法解决？

**Comment by xq114** [comment]
`xmake -v -D`贴完整log

**Comment by Dozingfiretruck** [comment]
![image](https://user-images.githubusercontent.com/24759100/143681756-a899273b-8dc5-43be-aa74-3ab4220e283d.png)

**Comment by waruqi** [comment]
看不出啥了，感觉像是这个工具链自身的问题

**Comment by Dozingfiretruck** [comment]
> 看不出啥来，觉得这个工具链自身的问题

走xmake的add_deps或者add_links都会这样，现在是在ldflags走命令连接的
target:add("ldflags", flto .. "-Wl,--gc-sections -Wl,-zmax-page-size=1024 -Wl,--whole-archive ./lib/libwmarch.a ./lib/libapp.a ./lib/libgt.a ./lib/libwlan.a ./lib/libdsp.a ./lib/libbtcontroller.a -Wl,--no-whole-archive -mcpu=ck804ef -nostartfiles -mhard-float -lm -Wl,-T./ld/"..TARGET_NAME..".ld -Wl,-ckmap=./build/out/"..TARGET_NAME..".map ",{force = true})
    这样可以正常编译

**Comment by waruqi** [comment]
看错误，有可能是多任务编译问题，可以尝试 xmake -j1 试试，也可能是 这个工具链的 ar 不支持 win 的 `\` 格式路径。

但目前，你给的信息太少，我看不出什么。

可以搞个简单demo 提供下复现例子，上传过来，包括对应的工具链。。

**Comment by Dozingfiretruck** [comment]
> 看错误，有可能是多任务编译问题，可以尝试 xmake -j1 试试，也可能是 这个工具链的 ar 不支持 win 的 `\` 格式路径。
> 
> 但目前，你给的信息太少，我看不出什么。
> 
> 可以搞个简单demo 提供下复现例子，上传过来，包括对应的工具链。。

您好，我前面反馈时候提了一下可能您没看见，单线程编译没问题，只有多线程编译才会出现此问题，目前没搞出来简单的复现例子，貌似只有静态库多了才会出现此问题，但是工程您有时间可以看一下https://gitee.com/openLuat/luatos-soc-air101
工具链：https://occ.t-head.cn/community/download?id=3885366095506644992
中的csky-elfabiv2-tools-mingw-minilibc
xmake.lua使用[xmake.zip](https://github.com/xmake-io/xmake/files/7640071/xmake.zip)

**Comment by waruqi** [comment]
我这里跑了下，没啥问题，不过我这 win vm ，所以只开了 2 jobs 并行，暂时无法复现。。

如果是并行编译导致，那估计也是这个工具链自身的 ar 有点问题，一种可能是 ar 在相同目录并行生成多个 .a ，有抢占一些文件资源，导致 rename 失败，可以每个 .a 的输出目录改下试试

要么尝试全局设置 `set_policy("build.across_targets_in_parallel")` 禁用跨target并行，试试，target内部源文件还是并行的，只是不让它们同时进行 link 了。。

要么文档里指明 xmake -j1 禁用并行编译

**Comment by Dozingfiretruck** [comment]
>

> 我这里跑了下，没啥问题，不过我这 win vm ，所以只开了 2 jobs 并行，暂时无法复现。。
> 
> 如果是并行编译导致，那估计也是这个工具链自身的 ar 有点问题，一种可能是 ar 在相同目录并行生成多个 .a ，有抢占一些文件资源，导致 rename 失败，可以每个 .a 的输出目录改下试试
> 
> 要么尝试全局设置 `set_policy("build.across_targets_in_parallel")` 禁用跨target并行，试试，target内部源文件还是并行的，只是不让它们同时进行 link 了。。
> 
> 要么文档里指明 xmake -j1 禁用并行编译

您好，set_policy("build.across_targets_in_parallel")之后确实解决了，产生一个警告
warning: policy(build.across_targets_in_parallel): invalid value type(table), it shound be 'boolean'!
请问这个需要有什么改动消除此警告么？
![image](https://user-images.githubusercontent.com/24759100/145331239-3896ee3a-244a-4673-83f2-9b8d631ec1e4.png)

**Comment by waruqi** [comment]
set_policy("build.across_targets_in_parallel", true)

**Comment by Dozingfiretruck** [comment]
> set_policy("build.across_targets_in_parallel", true)

设置set_policy("build.across_targets_in_parallel", false)后可以了，非常感谢指导，哈哈
