### ISSUE TITLE
require packages in github repo directly

### ISSUE THREAD

**Issue by qqiangwu** [xmake-io/xmake#1866]
### 你在什么场景下需要该功能？
我有一些用xmake管理的个人项目，开发时会依赖另一些用xmake管理的库，这些库在github上。库也是我写的，但是质量又没有好到可以放到xrepo的官方库上。我期望可以像golang一些，直接引用github上的代码。像这样：

```
add_requires("github::someuser/somelib 1.0.0", {"alias":"mylib"})
```

自己搞个本地包去下载也行，就是不方便复用。添加此特性后，有以下几个好处：

+ 只要某个库支持xmake，就可以直接从github上下载并依赖，方便库的传播
+ 不需要等待xrepo引录，避免写库的额外工作
+ 库的维护与库索引的维护(xrepo)放在一起，简化维护工作

### 描述可能的解决方案
add_requires支持新的源github，格式为"github::<user_name>/<repo_name> <version>"

version支持以下形式：
+ branch
    + master
    + branch/xxxx
+ 版本号
    + tag?

#### 包下载
+ 对于branch，直接clone https://github.com/<user_name>/<repo_name>.git 对应branch
+ 对于版本号，直接clone对应的tag

#### 包构建
repo中包含xmake.lua，可以直接构建。

### 描述你认为的候选方案
无

### 其他信息
无

**Comment by xq114** [comment]
不想用local repo的话，可以在自己的xmake.lua中直接自定义package

```
package("foo")
	add_urls("https://github.com/foo/foo.git")
	on_install(function(package) import("package.tools.xmake").install(package) end)

add_requires("foo")
```

或者
```
package("foo")
	add_urls("https://github.com/foo/foo.git")
	add_versions("v1.0", "<commit>")
	add_deps("cmake")
	on_install(function(package) import("package.tools.cmake").install(package) end)

add_requires("foo 1.0")
```

C++的构建系统太多样化了，并且大部分基于cmake的包很难保证在各平台上都能原样编译通过，需要改config/打patch，不可能像go那么一致的，一些额外的脚本控制是必须的。而且也不麻烦，几行的事情

**Comment by waruqi** [comment]
可以放自己私有仓库管理，也可以像上面那样直接在自己xmake.lua里面定义包

**Comment by qqiangwu** [comment]
好吧

**Comment by qqiangwu** [comment]
> C++的构建系统太多样化了，并且大部分基于cmake的包很难保证在各平台上都能原样编译通过，需要改config/打patch，不可能像go那么一致的，一些额外的脚本控制是必须的。而且也不麻烦，几行的事情

我的目的是，针对已经是用xmake作为构建工具的repo，可以快速被其他人引用，而不需要引用者自己再包一层。

**Comment by waruqi** [comment]
> > C++的构建系统太多样化了，并且大部分基于cmake的包很难保证在各平台上都能原样编译通过，需要改config/打patch，不可能像go那么一致的，一些额外的脚本控制是必须的。而且也不麻烦，几行的事情
> 
> 我的目的是，针对已经是用xmake作为构建工具的repo，可以快速被其他人引用，而不需要引用者自己再包一层。

如果是 xmake 包，你包一下也就2 3 行，不会麻烦多少。。

```lua
package("foo")
	add_urls("https://github.com/foo/foo.git")
	on_install(function(package)
             import("package.tools.xmake").install(package)
        end)
package_end()

add_requires("foo 1.0")
```

而且，为了包的稳定可靠，特定版本对应的 sha256 校验，on_test 的包测试验证，都是必须的，否则都是不可靠的，即使是 xmake.lua 维护的包。。

因为尽管 xmake.lua 维护，但是每个库还依赖库代码自身的可移植性，很多 c/c++ 库代码自身存在各种问题，导致在不同编译器下，出现各种编译问题需要patch代码才能过掉，而且每个库作者写的 xmake.lua 都各有差异，如果有些库对 dll 没导出符号，或者没有配置安装头文件，都会导致用户引入失败

所以不可能完全一键适配所有 c/c++ 库，即使是用 xmake.lua 维护，多少要做一些适配。这是有 c/c++ 自身特性和生态决定。。

不像 go/js/py 这种，天生代码层面全平台兼容，不用各种特殊处理，只要代码+版本对上就 ok 了。。

**Comment by waruqi** [comment]
如果非要强行做 一行引入 xmake 包，是可以做到的，但是会存在各种限制和隐患：

- 没有包完整性校验，用户引入的包随时会被篡改
- 不同github仓库包版本tag 不一致，不完全能够版本语义选择
- 没有 on_test 安装测试验证，即使安装成功了，用户编译集成阶段也可能会报错，导致用户产生各种困惑，不完全可靠
- 不支持的平台，无法提前提示用户不支持，只能尝试安装失败，然后留给用户一堆的库编译错误，体验很差
- 无法对包打 patch 过掉一些库自身小问题导致的代码编译不过
- 无法实现包可选特性的配置
- 无法实现版本语义选择
- 无法支持多源切换，如果设置了 github url 包，那国内用户下载受限，安装成功率不高，但是有 package 适配层，可以设置 gitee/github/gitlab 等各种镜像源，一个 url 下载失败，会自动尝试下载另外一个，优先选最快的源

**Comment by waruqi** [comment]
还有很多其他的各种限制，多了去了 仅仅为了省去那 2 3 行配置，牺牲这么多特性，去用个限制版，我是觉得得不偿失，没必要非得跟 go 看齐，而且 golang 的那种包引入方式，即使对于go自身，我还是不看好，这等于是代码里面写死了 各种  github url

哪天 github 包作者，一换源或者仓库地址，比如切到 gitlab 去维护了，那我代码里面还得各种改，牵一发动全身，导致各种依赖问题，而且也没法支持灵活换源，干嘛非得去抄它的模式。 真心还不如 npm cargo 了。
