### ISSUE TITLE
Escape characters for set_configvar

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1872]
### 你在什么场景下需要该功能？

```
set_configvar("TEST", "$(projectdir)")
```
会展开成
```
#define TEST "C:\...\project"
```
在给字符串自动加引号时对`\`等字符的转义没有处理，而要正确处理转义就必须在on_load里面进行，非常麻烦；或者使用STRINGIFY宏和quote=false选项来进行，也很麻烦

### 描述可能的解决方案

```
set_configvar("TEST", "$(projectdir)", {escape = true})
```
在加引号的同时处理转义问题，默认不处理的行为不动

**Comment by waruqi** [comment]
加了 https://github.com/xmake-io/xmake/commit/7dc1142890a81e5aed622b2832cca5e39b897ce7
