### ISSUE TITLE
xmake能否支持Kotlin语言？

### ISSUE THREAD

**Issue by biij5698** [xmake-io/xmake#1887]
有时候我使用Flutter开发一些Android应用，但有些Android功能单独使用Flutter无法实现，其中一个不错的解决方案是用Kotlin来实现这个功能，然后编译成动态链接库供Flutter调用，但是看到xmake目前还不支持Kotlin语言，所以来提个issue希望能够支持Kotlin语言。顺便提一下，大家都知道现在Android原生开发语言已经是Kotlin优先，Android系统的一等公民，大部分新的Android应用现在也都是用Kotlin开发的。

**Comment by waruqi** [comment]
xmake 目前专注构建 native 系语言，jvm 系的语言 暂时不考虑支持

**Comment by waruqi** [comment]
你是指 kotlin native？如果是这个 后期可以考虑 但暂时还不确定排期，可以先备着

**Comment by biij5698** [comment]
@waruqi 也许我这个issue的提出看似正确但实际上是错误的，站在个人角度来说，也就是我自已的角度来说，我感觉还是用Kotlin为Flutter开发插件较为合适，一开始我想的太美好了，现在想想即便xmake支持了Kotlin又如何，就我自己来说，可能更多还是用Kotlin为Flutter开发插件，如果一定要编译为动态链接库，Kotlin本身也可以的。
今天我想了想，为了实现这个功能去浪费你们的时间可能是个错误，因为不一定有多少人会去用，所以我这条建议你就当没有提出吧。
如果你对xmake支持Kotlin语言有兴趣，我不会有任何意见。我只希望不要因为我的错误建议而浪费你们的时间。

**Comment by waruqi** [comment]
kotlin java 这种 jvm 系的，gradle/maven 此类构建工具都很成熟了，而且跟这边主打 native 系语言构建 架构差异都比较大，目前确实还没有时间精力去处理这块，即使支持了，估计也不会有多少人用，因为相比 gradle/maven 可能没有太多优势。

所以，我们重点还是以 c/c++/asm 构建为主，其他 native 语言混合开发为辅，jvm 系的暂时不考虑。

**Comment by waruqi** [comment]
目前 kotlin 也提供了 kotlin-native 的编译支持，因此也可以用来构建 native 二进制了。所以最近对齐也做了初步支持。

https://github.com/xmake-io/xmake/issues/6154
