### ISSUE TITLE
xmake v2.6.1的Windows安装包会先删除安装目录下的文件

### ISSUE THREAD

**Issue by dongnanyanhai** [xmake-io/xmake#1888]
### 描述问题

xmake v2.6.1的Windows安装包会先删除安装目录下的所有文件，用户不小心选错目录的话，问题有点大！

### 期待的结果

安装程序先检测用户选择的安装目录，如果存在文件或目录，弹出提示告知用户重新选择。

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：v2.6.1
- xmake运行平台：win 10

**Comment by waruqi** [comment]
这个跟2.6.1没啥关系，之前的版本也会有这个问题，回头可以尝试从注册表读取之前的安装目录

**Comment by dongnanyanhai** [comment]
最好在安装程序那里判断一下目录，我今天选错被删了太多文件了。

好在目录下有个软件用了npm，没想到目录里有几万个小文件救了我一命。

**Comment by dongnanyanhai** [comment]
建议尽量不要删除用户目录下的文件，改为提醒用户选择一个空目录，这样比较保险。

**Comment by waruqi** [comment]
> 建议尽量不要删除用户目录下的文件，改为提醒用户选择一个空目录，这样比较保险。

我只能尝试读取之前注册表实际的历史安装目前，直接卸载之前的版本，提示做不了，这个是 nsis 的脚本，我不太熟，不一定它支持这个功能，而且通常默认给的路径安装就是了， C:\program files\xmake 不会存在这个问题，所以建议不要随意切换安装目录。

**Comment by waruqi** [comment]
刚稍微改进了下，如果选择的安装目录下有 xmake.exe ，才会尝试选删除历史文件，如果没有，就直接装

https://github.com/xmake-io/xmake/commit/b062cae6275c91a0c415524353daa49220cbb3f8#diff-8a89c99a899893537a7a7e6df063963d3cd3fbda57c6a4fb5babf345a06b6048

**Comment by waruqi** [comment]
目前的改进基本可以了，https://github.com/xmake-io/xmake/actions/runs/1541406506 到这里可以下载安装包做测试，有问题再开

**Comment by dongnanyanhai** [comment]
好的，辛苦了！
