### ISSUE TITLE
separate user-defined options in exported configuration

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1889]
### 描述讨论详情
由于使用命令行输入的局限性，一些转义字符不方便输入给xmake。现在新版的gn提供了一个用编辑器来进行config的模式，运行gn args会用设置好的编辑器打开一个临时文件，然后各类config可以在临时文件里面修改，再被gn读取。

xmake虽然不支持这种使用编辑器进行config的模式，但xmake支持更强大的config导入/导出。使用`xmake f --export config.txt`、修改config.txt、再运行`xmake f --import config.txt`进行配置，配置文件会保留下来，并且可以读取到默认设置，比gn的解决方法更优。但是目前使用这种方法还有一些问题：

1. `xmake config --export`导出的config.txt是一个乱序的lua table，不方便手动修改。如果能固定顺序，或者把用户设置的option和xmake自带的option分开就好了。现在是这样
```
{
    float = false,
    vs = "2019",
    buildir = "build",
    mode = "release",
    openmp = true,
    theme = "default",
    ndk_stdcxx = true,
    plat = "windows",
    arch = "x64",
    host = "windows",
    clean = true,
    kind = "static",
    network = "public",
    ccache = true
}
```
希望改成这样
```
{
    -- user defined options
    float = false,
    openmp = true,

    -- builtin options
    vs = "2019",
    buildir = "build",
    mode = "release",
    theme = "default",
    ndk_stdcxx = true,
    plat = "windows",
    arch = "x64",
    host = "windows",
    clean = true,
    kind = "static",
    network = "public",
    ccache = true
}
```

2. 一部分builtin option没有出现在导出的config.txt中（cc，cxx，toolchain，ld，cflags等等）这块是如何考虑的？毕竟使用这种方法输入config通常也是需要修改这些toolchain变量的，如果使用import无法修改的话也是一个问题

**Comment by waruqi** [comment]
> xmake config --export导出的config.txt是一个乱序的lua table，不方便手动修改。如果能固定顺序，或者把用户设置的option和xmake自带的option分开就好了。现在是这样

乱序问题好弄，序列化时候排序下keys，但是要分离加注释，没法直接在一个 table 里面分，目前的序列化模块不支持，除非加层 key value ，用 key 区分。

```lua
{
    custom = {},
    builtin = {}
}
```

而且目前导出时候，这些 values 内部已经混一起了，没法再区分了，除非再挨个判断 key name 强行分离，理论上可以做，就是稍微复杂点。

> 一部分builtin option没有出现在导出的config.txt中（cc，cxx，toolchain，ld，cflags等等）这块是如何考虑的？毕竟使用这种方法输入config通常也是需要修改这些toolchain变量的，如果使用import无法修改的话也是一个问题

有默认值的，或者已经设置了值的，会自动导出，没出现的都是 还没设置 当前是 nil 的配置，所以只是忽略了而已，但是你自己加进去导入，也是生效的。

**Comment by waruqi** [comment]
乱序问题，我刚排序过了

**Comment by waruqi** [comment]
这块先这样吧，乱序问题解了，加注释不太好搞，cc 这种 builtin 的你直接自己添加导入就行了，也是支持的，只是导出默认省略了
