### ISSUE TITLE
Intel Fortran Compiler can not be detected on linux

### ISSUE THREAD

**Issue by PucklaMotzer09** [xmake-io/xmake#1893]
### Describe the bug
When I switch to the `ifort` toolchain using `set_toolchains("ifort")`, the compiler is not found. There is a workaround (see Additional Context) though it would be nice if it could be detected automatically. I installed the compiler from the [official Intel website](https://www.intel.com/content/www/us/en/developer/articles/tool/oneapi-standalone-components.html#fortran) using the online installer.

### Expected behavior
The Compiler and all related paths should be detected automatically by xmake.

### Error output
Well, it just says `toolchain("ifort"): not found!`.

### Related Environment

- ifort version: 2021.1.2
- xmake version: 2.5.9
- os: Garuda Linux
- target platform: Linux x86_64

### Additional context
The workaround goes as follows:
1. Add the compiler executable to `PATH`
For me I had to add `~/intel/oneapi/compiler/latest/linux/bin/intel64`. Change `intel64` to `ia32` for x86.
```
export PATH="~/intel/oneapi/compiler/latest/linux/bin/intel64:$PATH"
```
2. Add the library folder to `LD_LIBRARY_PATH`
For me I had to add `~/intel/oneapi/compiler/latest/linux/compiler/lib/intel64`. Change `intel64` to `ia32` for x86.
```
export LD_LIBRARY_PATH="~/intel/oneapi/compiler/latest/linux/compiler/lib/intel64:$LD_LIBRARY_PATH"
```
This should be everything and now you can use ifort with xmake.

**Comment by waruqi** [comment]
I have improved it but I have not environment to test it.  You can try it. If it does not work, you can open a pr later.

**Comment by PucklaMotzer09** [comment]
Now it is able to find `ifort`, but when linking it can not find `libimf.so`. This file is inside the folder added to `LD_LIBRARY_PATH`, but it seems that the environment variable isn't actually accessed.

**Comment by waruqi** [comment]
I have improved it on ifort branch, can you try it again.
```
xmake update -s github:xmake-io/xmake#ifort
```

https://github.com/xmake-io/xmake/pull/1898/files

But I have not tested it. if it dose not work, you can debug this patch and open pr to this branch.

**Comment by waruqi** [comment]
I have improved to detect icc/ifort toolchains again on dev, you can try it. 

xmake update -s dev

**Comment by PucklaMotzer09** [comment]
It's still the same `libimf.so` is not found. xmake does find `ifort` completely fine, but somehow `LD_LIBRARY_PATH` is not getting applied.
