### ISSUE TITLE
运行xmake提示libreadline.so.8没找到的问题

### ISSUE THREAD

**Issue by cngith** [xmake-io/xmake#1894]
Deepin 20.1系统, 下载了deb, 安装
$ sudo dpkg -i xmake-v2.6.1.amd64.deb
...
$ xmake --version
xmake: error while loading shared libraries: libreadline.so.8: cannot open shared object file: No such file or directory

查了一下这个"libreadline.so.8"应该是readline的类库
readline - A library for editing typed command lines
但它不提供deepin的安装版本.
主页(tiswww.case.edu/php/chet/readline/rltop.html)提供的几个源码链接都打不开, 怎么办?
怎么才能把xmake跑起来?

**Comment by waruqi** [comment]
不是readme和官网最顶上就有一键安装脚本么，为啥还要这么搞呢？

**Comment by cngith** [comment]
谢谢您, 解决了.
