### ISSUE TITLE
Changing the default outputdir for vsxmake is not supported by the autoupdate extension

### ISSUE THREAD

**Issue by PierreEVEN** [xmake-io/xmake#1895]
All is in the title

### Describe the bug

When I compile the project from VisualStudio 2019, the autoupdate extension regenerate the files in the **DEFAULT** location instead of the custom outputdir

### How to reproduce : 

1. Create a basic project with the autoupdate vsxmake plugin
```lua
add_rules("mode.debug", "mode.release")
add_rules("plugin.vsxmake.autoupdate")

target("HeadlessEngine")
    set_kind("binary")
    add_files("src/*.cpp")
```

2. Create the vs project files in a **CUSTOM** output dir
```
xmake project -k vsxmake2019 my_custom_output_dir
```

3. Open the vs project, add a new random source file

4. Build from VS (the new file should normally appear after building, but it's not the case here)

**What hapenned** => Instead of updating the current project file, it create new VS project files in the **DEFAULT** folder : *vsxmake2019* (instead of the custom one : *my_custom_output_dir*).

### Related Environment

- xmake version: 2.6.1
- os: windows
- target platform: windows

**Comment by SirLynix** [comment]
Also, installing a new VS version (2022) will make vsxmake.autoupdate to generate a vsxmake2022 folder instead of updating the vsxmake2019 one

**Comment by waruqi** [comment]
I have improved it on dev, you can try

```lua
add_rules("plugin.vsxmake.autoupdate", {outputdir = "xxx"})
```

**Comment by waruqi** [comment]
> Also, installing a new VS version (2022) will make vsxmake.autoupdate to generate a vsxmake2022 folder instead of updating the vsxmake2019 one

This is to avoid VS version conflicts, and users will not frequently upgrade VS, you can reopen vsxmake2022.

**Comment by SirLynix** [comment]
> I have improved it on dev, you can try
> 
> ```lua
> add_rules("plugin.vsxmake.autoupdate", {outputdir = "xxx"})
> ```

This shouldn't be part of xmake.lua I think, every user may change the output dir to whatever they want from the command-line.

Maybe we should store that info in a file (vsxproj?) when called from the command-line and reuse it? Same for vs version.

> > Also, installing a new VS version (2022) will make vsxmake.autoupdate to generate a vsxmake2022 folder instead of updating the vsxmake2019 one
> 
> This is to avoid VS version conflicts, and users will not frequently upgrade VS, you can reopen vsxmake2022.

It's not just an issue when you upgrade since you mah want to work with a lower vs version (like vs2019) while having vs2022 installed

**Comment by waruqi** [comment]
I added local cache to autoupdate and vsxmake plugin. you can try it again.

**Comment by waruqi** [comment]
> It's not just an issue when you upgrade since you mah want to work with a lower vs version (like vs2019) while having vs2022 installed

you can run `xmake project -k vsxmake2019` now. the `--kind=value` will be cached

**Comment by waruqi** [comment]
Does it work now?

**Comment by PierreEVEN** [comment]
Sorry, I didn't had time to test it. I'll try Tomorrow :)

**Comment by PierreEVEN** [comment]
> Does it work now?

Yup, thanks ! 🥳

I haven't tested using an older version of VS (which @SirLynix's was talking about) but the autoupdate now uses the correct directory 👍
