### ISSUE TITLE
unable to parse semver range 'v1.7.0'

### ISSUE THREAD

**Issue by ipyffor** [xmake-io/xmake#1897]
> Note: If it is a 'bug report' or 'feature request', please select the corresponding issue template, otherwise this issue will be not replied. 

### Describe the problem details
Please describe your problem details here.
xmake v2.6.1+202112081732

```lua
-- spdlog
package("spdlog")
    set_urls("https://gitcode.net/mirrors/gabime/spdlog.git")
    on_install(function (package)
        import("package.tools.cmake").install(package)
    end)
package_end()

-- spdlog 1.7.0
add_requires("spdlog v1.7.0", {alias = "spdlog"})
```
之前还可以正常使用，现在出现unable to parse semver range 'v1.7.0'

**Comment by waruqi** [comment]
先改成 1.7.0 试下，回头我会调下

**Comment by ipyffor** [comment]
```shell
xmake -vrv
checking for gcc ... /usr/bin/gcc
checking for dmd ... no
checking for ldc2 ... no
checking for gdc ... no
checking for zig ... no
checking for zig ... no
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /bin/gzip
checking for tar ... /bin/tar
checking for xmake::spdlog ... no
checking for pacman ... no
checking for emerge ... no
checking for brew ... no
checking for pkg-config ... /usr/bin/pkg-config
checking for spdlog ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
  -> spdlog 1.7.0 
please input: y (y/n/m)
y
checking for ping ... /bin/ping
pinging for the host(gitcode.net) ... 45 ms
/usr/bin/git clone https://gitcode.net/mirrors/gabime/spdlog.git source.tmp/spdlog
正克隆到 'source.tmp/spdlog'...
remote: Enumerating objects: 773, done.
remote: Counting objects: 100% (773/773), done.
remote: Compressing objects: 100% (314/314), done.
remote: Total 23610 (delta 469), reused 614 (delta 380), pack-reused 22837
接收对象中: 100% (23610/23610), 40.07 MiB | 4.56 MiB/s, 完成.
处理 delta 中: 100% (15739/15739), 完成.
/usr/bin/git checkout 1.7.0
error: pathspec '1.7.0' did not match any file(s) known to git.
error: execv(/usr/bin/git checkout 1.7.0) failed(1)
  => clone https://gitcode.net/mirrors/gabime/spdlog.git 1.7.0 .. failed

we can also download these packages manually:
  - https://gitcode.net/mirrors/gabime/spdlog.git
to the local search directories: 
  - spdlog.git
and we can run `xmake g --pkg_searchdirs=/xxx` to set the search directories.
error: 
```

**Comment by ipyffor** [comment]
换1.7.0不行

**Comment by ipyffor** [comment]
嗯，这样可以，但这样需要设置两个地方，还是之前可以直接检出到v1.7.0方便，我现在windows上用的v2.5.9+master.3c61b8d29，是可以直接检出的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月8日(星期三) 晚上6:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xmake-io/xmake] unable to parse semver range &#39;v1.7.0&#39; (Issue #1897)





 
这样应该可以
 package("spdlog")     set_urls("https://gitcode.net/mirrors/gabime/spdlog.git")     add_versions("v1.7.0", "616caa5d30172b65cc3a06800894c575d70cb8e6")     on_install(function (package)         import("package.tools.cmake").install(package)     end) package_end() -- spdlog 1.7.0 add_requires("spdlog 1.7.0", {alias = "spdlog"})
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by waruqi** [comment]
> 之前还可以正常使用，现在出现unable to parse semver range 'v1.7.0'

跟 xmake 版本没关系，我 windows 上也是可以的，触发这个问题，是因为你 package 里面没设置 add_versions

所以，xmake 自动内部调用 find_package 找已经安装过得 spdlog 和系统库，如果找到，并且找到了系统库版本，就会跟你指定的 v1.7.0 进行匹配，而在匹配过程中，`add_requires("xxx v1.7.0")` 你指定的 version range 是不规范的格式，所以就报错了

而你之前可以，应该是之前没找到对应系统库，内部没去匹配版本，所以没机会触发这个错误。。

但是本质上，你写的就是不对的，add_versions 等单个版本号 可以带 v 前缀，但是 add_requires 里面的是版本范围。。可能是 >=1.7 什么的，不是单个版本值，目前版本范围不支持带 v 前缀，之前的版本也是

**Comment by waruqi** [comment]
所以就是，add_requires 里面，你不能写 v1.7.0 只能写 1.7.0
