### ISSUE TITLE
os.rm, os.rmdir and os.tryrm can delete the entire project directory 

### ISSUE THREAD

**Issue by Jackie365** [xmake-io/xmake#1899]
### Reproduce the problem
In the project root directory, e.g. `test`, create `xmake.lua` with the following content
```
target("test")
    set_kind("phony")
    on_build(function()
        os.rm("")
    end)
```
and execute `xmake`, the entire project directory will be deleted.
The same is true for `os.rmdir` and `os.tryrm`

### Expected behavior
Not a bug, but I think a build system should be able to protect the project files from being accidentally deleted, not to mention the entire directory containing the root xmake file

### Possible solution
In my opinion, in `xmake/core/base/os.lua`, we can modify the definition of `os.rm` and `os.rmdir` , that is
```
if not filepath or filepath == "" then
    return false, string.format("invalid arguments!")
end
```

**Comment by waruqi** [comment]
I have fixed it, you can try it again.
```
xmake update dev
```
