### ISSUE TITLE
如何使用FLEX&BISON?

### ISSUE THREAD

**Issue by yangjz1125** [xmake-io/xmake#190]
如何在c/c++中使用FLEX&BISON?

**Comment by yangjz1125** [comment]
我指使用xmake构造flex&bison。

**Comment by yangjz1125** [comment]
在xmakec/cpp项目中添加flex&bison文件

**Comment by waruqi** [comment]
暂时还没有原生支持，你可以先自定义两个flex bison规则去支持他们，可以参考 qt的相关规则实现，https://github.com/tboox/xmake/blob/master/xmake/rules/qt/ui/xmake.lua

或者看下文档介绍 [rule规则](https://xmake.io/#/zh/manual?id=构建规则) 

xmake之后也会考虑内置支持，不过具体时间点不定，得看这边具体工作进度来排期，因为还有很多特性正在开发中。

不过之后我也会通过内置rule的方式来支持它们，也欢迎相关代码贡献。

**Comment by waruqi** [comment]
我在dev分支上支持了，你更新到dev分支试试，只需要应用 lex, yacc两个构建规则就行了，里面会自动检测lex/flex, yacc/bison，然后调用编译。

```lua
add_rules("mode.debug", "mode.release")

target("calc")
    set_kind("binary")
    add_rules("lex", "yacc")
    add_files("src/*.l", "src/*.y")
```

example项目见，https://github.com/xmake-io/xmake/tree/dev/tests/projects/lex_yacc
