### ISSUE TITLE
link order: local target and a remote package depend the same package

### ISSUE THREAD

**Issue by qqiangwu** [xmake-io/xmake#1903]
### 描述问题
![image](https://user-images.githubusercontent.com/2892107/145668365-e7482ef4-1b5b-4219-aaf3-ba1d58d81923.png)

![image](https://user-images.githubusercontent.com/2892107/145668394-a0c3cafc-8143-48fc-9821-b871d6a7e93c.png)

编译test相关target时，target依赖了fmt和folly，folly也依赖了fmt，在macos上是正常链接的，但是在ubuntu:20.04上，链接会出问题，[报folly到不到fmt中的符号](https://github.com/qqiangwu/cloudkv/runs/4446893151?check_suite_focus=true)。

链接命令是

```
/usr/bin/g++ -o xxx_test build/.../xxx_test.cpp.o -m64 -L...(省略一堆link目录) -s -lgmock -lgtest -l gtest_main -lcloudkv -lfmt -lfolly_test_util -lfolly -lfollybenchmark -lzstd -llz4 -lglog -lgflags_nothreads -ldouble-conversion -levent_openssl -levent_pthreads -levent -levent_extra -levent_core -l ssdl -lcrypto -l<省略一堆boost> -lz -lbz2 -l pthread -ldl
```

![image](https://user-images.githubusercontent.com/2892107/145668443-01ba2528-4626-48b9-b330-1708bc292549.png)

排查下来的原因是，在link xxx_test里，link的order是先fmt，再folly。经过排查，把fmt移动到folly后面就解决了。
![image](https://user-images.githubusercontent.com/2892107/145668516-fe0b0633-38c5-4da9-86cb-1343aa400994.png)

但是这样改还是有些费劲，需要人工来resolve依赖顺序。

### 期待的结果
链接正常

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：v2.6.1
- xmake运行平台：ubuntu:20.04 
- xmake目标平台：
- g++版本：Ubuntu 9.3.0-17ubuntu1~20.04 9.3.0

### 其他信息
https://github.com/qqiangwu/cloudkv

**Comment by waruqi** [comment]
你更新到 master 然后 重装 folly 试下，2.6.1里面有个link bug，后来 master 上有修复

**Comment by qqiangwu** [comment]
我跑了`xmake update master`和`xmake p -f`，然后结果还是一样

**Comment by waruqi** [comment]
拉了你的代码试了下，编译不过

```
error: In file included from src/db_impl.h:9,
                 from src/db.cpp:2:
src/task/task_manager.h:26:15: error: declaration of 'cloudkv::task* cloudkv::task_manager::task_ctx::task' changes meaning of 'task' [-fpermissive]
   26 |         task* task;
      |               ^~~~
In file included from src/task/task_manager.h:8,
                 from src/db_impl.h:9,
                 from src/db.cpp:2:
src/task/task.h:9:7: note: 'task' declared here as 'class cloudkv::task'
    9 | class task : private boost::noncopyable {
      |       ^~~~
```

**Comment by qqiangwu** [comment]
抱歉，之前提升了编译器warning级别。现在已经修了。https://github.com/qqiangwu/cloudkv/runs/4498583342?check_suite_focus=true

**Comment by waruqi** [comment]
更新到 dev 再试试，xmake update -s dev

**Comment by qqiangwu** [comment]
ok，感谢
