### ISSUE TITLE
`xmake init` and force create project

### ISSUE THREAD

**Issue by Bricklou** [xmake-io/xmake#1907]
### Is your feature request related to a problem? Please describe.
I often work with already created or cloned projects where I want to initialize a xmake project (i.e. fresh created git repo with default README file). But at the moment, xmake doesn't allow creating projects in non-empty directories.

### Describe the solution you'd like
1. Add an `-f` / `--force` to force xmake to create a project
2. Add a `xmake init` command to initialize a project in the current folder. Maybe add a prompt to confirm the action if there are files conflicts or if the directory is not empty.

**Comment by waruqi** [comment]
you can update to dev branch and try it.

```console
xmake create -f -P . test
xmake create --force -P . test
```
