### ISSUE TITLE
Cannot use openmp in msys2

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1911]
### 描述问题

msys2中openmp不能正常工作

### 期待的结果

openmp正常工作，即package:has_tool可以识别mingw的gcc

### 错误信息

```
checking for i686-w64-mingw32-gcc ... D:\a\_temp\msys64\mingw32\bin\i686-w64-mingw32-gcc
checking for the c compiler (cc) ... i686-w64-mingw32-gcc
checkinfo: cannot runv(ccache --version), No such file or directory
checking for ccache ... no
> D:\a\_temp\msys64\mingw32\bin\i686-w64-mingw32-gcc -c -m32 -isystem C:\Users\runneradmin\AppData\Local\.xmake\packages\o\openblas\0.3.18\7bcccb9dbbbd46e8adcbc409ddf50a5a\include -o D:\a\_temp\msys64\tmp\.xmake\211214\_8C69668DDCFA4720885CEB65C3234D20.o D:\a\_temp\msys64\tmp\.xmake\211214\_66C4A1C2F0FA4728BDE347C3FEE7E208.c
checking for i686-w64-mingw32-g++ ... D:\a\_temp\msys64\mingw32\bin\i686-w64-mingw32-g++
checking for the linker (ld) ... i686-w64-mingw32-g++
> D:\a\_temp\msys64\mingw32\bin\i686-w64-mingw32-g++ -o D:\a\_temp\msys64\tmp\.xmake\211214\_F4B187B5FD0B4728B113A65DF5D16418.b D:\a\_temp\msys64\tmp\.xmake\211214\_8C69668DDCFA4720885CEB65C3234D20.o -m32 -LC:\Users\runneradmin\AppData\Local\.xmake\packages\o\openblas\0.3.18\7bcccb9dbbbd46e8adcbc409ddf50a5a\lib -lopenblas -lopenblas_nehalemp-r0.3.18
> checking for c includes(cblas.h)
> checking for c links(openblas, openblas_nehalemp-r0.3.18)
> checking for c snippet(test)
checkinfo: ...gramdir\core\sandbox\modules\import\core\tool\linker.lua:75: @programdir\core\sandbox\modules\os.lua:264: D:/a/_temp/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:\Users\runneradmin\AppData\Local\.xmake\packages\o\openblas\0.3.18\7bcccb9dbbbd46e8adcbc409ddf50a5a\lib/libopenblas.a(cblas_dgemm.obj):gemm.c:(.text+0x3f9): undefined reference to `omp_get_max_threads'
```

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.6.1
- xmake运行平台：msys2
- xmake目标平台：mingw

### 其他信息

https://github.com/xq114/xmake-repo/runs/4519942643?check_suite_focus=true

**Comment by waruqi** [comment]
![Snip20211214_1](https://user-images.githubusercontent.com/151335/146016573-86161691-06a8-4a58-a653-2213cae1fb15.png)

我这本地可以的么

**Comment by xq114** [comment]
> checking for the c compiler (cc) ... i686-w64-mingw32-gcc

应该是这里的问题，xmake找到了i686-w64-mingw32-gcc.exe，匹配gcc就会失败。这个需要安装了mingw-w64-x86_64-gcc，并且在mingw64 bash里面打开才行，在msys bash里面只会找到gcc.exe

**Comment by waruqi** [comment]
? 我这找的不也是这个么。。ci 上我配置的 就是 mingw64/msys2 bash 。。不是纯 msys2 bash 那个原本默认就不是mingw平台

**Comment by waruqi** [comment]
? 我这找的不也是这个么。。ci 上我配置的 就是 mingw64/msys2 bash 。。不是纯 msys2 bash 那个原本默认就不是mingw平台

**Comment by waruqi** [comment]
> checking for the c compiler (cc) ... i686-w64-mingw32-gcc

而且我看这里都检测到了，is_tool 是取的 toolname ，可以 print `local program, toolname = package:tool("cc")`

看下，按理，toolname 就是 gcc

**Comment by xq114** [comment]
发现问题了，ci上面使用test.lua的时候openmp只会安装不会fetch，而openmp的on_install没写mingw，所以没法安装同时没法fetch，就出问题了。ci上和本地行为不一样。我改了下
```
package:add("deps", "openmp", {system = true})
```
本地可以正常找到openmp，ci上直接报错openmp无法安装

**Comment by waruqi** [comment]
没懂，on_install没加 mingw，肯定不会去fetch，加上也不会fetch?

我本地是临时加上后测的

**Comment by waruqi** [comment]
> 而openmp的on_install没写mingw

你可以 openmp 那个包加上 on_install mingw 平台后试试，我这测试 msys 下是可以的。。。不过 mingw on macOS 上 omp.h 会找不到，似乎 mingw 在 macos 上没 libomp 。。不知道应该用哪个。

**Comment by waruqi** [comment]
我 msys on_install 加上openmp了 还是不行么？

**Comment by xq114** [comment]
https://github.com/xq114/xmake-repo/runs/4561104708?check_suite_focus=true

还是不行

**Comment by xq114** [comment]
`package:add("deps", "openmp")`没有生效

**Comment by waruqi** [comment]
> `package:add("deps", "openmp")`没有生效

可以的么，你只是 on_load 里面没加上 mingw 平台，所以 deps 实际没加进去而已

https://github.com/xmake-io/xmake-repo/actions/runs/1595674962

现在我这测试，反而是 macos 下有点问题，刚修复了下

话说有cmakelist 为啥当初调用 make呢，makefile 不同平台配置起来比较琐碎，对 deps 处理也不太好 目前。

另外，with_xx 选项，统一改成 xx 了，统一规范。。

https://github.com/xmake-io/xmake-repo/pull/766

我已经 merge 了，后续有变动，可以继续补 pr
