### ISSUE TITLE
Add WDK toolchain to build non-driver program

### ISSUE THREAD

**Issue by ddkwork** [xmake-io/xmake#1925]
os：win11 latest
操作：
1 安装lua latest
2 xmake goland plugin
3 lua语法识别的插件
4 goland新建xmake工程，加载ewdk iso最新版，此时的环境是：不要安装任何cpp编译器，vs 40多gb每次安装后感觉
够不妙，然后打开goland控制台输入
xmake f --wdk="L:\Program Files\Windows Kits\10" -c
xmake

新建xmake工程为hello word

#include <stdio.h>

int main(int argc, char** argv)
{
printf("hello world!\n");
return 0;
}

问题在这里，如果不该这些，提示找不到头文件和lib，如果是这样改：
add_rules("mode.debug", "mode.release")

target("console")
set_kind("binary")
--add_includedirs("L:/Program Files/Windows Kits/10/Include/10.0.17763.0/km/crt")
add_includedirs("L:/Program Files/Windows Kits/10/Include/10.0.17763.0/ucrt")
--add_linkdirs("L:\Program Files\Windows Kits\10\Lib\10.0.17763.0\um\x64\kernel32.Lib")
add_linkdirs("kernel32.Lib")
add_linkdirs("uuid.Lib")
add_files("src/*.c")
--L:\Program Files\Windows Kits\10\Lib\10.0.17763.0\ucrt\x64
--"L:\Program Files\Windows Kits\10\Lib\10.0.17763.0\um\x64\Uuid.Lib"

就能编译了，从此脱离了vs几十gb噩梦

**Comment by waruqi** [comment]
目前 wdk ，xmake 仅支持用来编译 win 驱动程序，需要设置 `wdk.driver` 等规则，才会自动设置 wdk 里面各种 includedirs, linkdirs

这块具体看 文档 ：https://xmake.io/#/zh-cn/guide/project_examples?id=wdk%e9%a9%b1%e5%8a%a8%e7%a8%8b%e5%ba%8f

如果你不是为了编译驱动，仅仅只是用来编译平常程序，目前还有提供支持，所以你要自己配置各种 add_includedirs add_linkdirs

这块要支持，需要额外加个一个 wdk 的 toolchain 才行。等后面有时间可以给你改进下支持，但具体时间不定，目前你只能先自己手动设置下。

**Comment by waruqi** [comment]
先试试 add_rules("wdk.binary")  用来基于 wdk 编译二进制程序，不一定是驱动。

另外还有 add_rules("wdk.static")  和 wdk.shared 对应动态库，静态库

**Comment by ddkwork** [comment]
> 先试试add_rules("的信息，请参见.二进制")用来基于的信息，请参见编译二进制程序，不一定是驱动。
> 
> 且add_rules("的信息，请参见.静态")和信息，请参见.共享对应动态库，静态库

good👍🏻

**Comment by ddkwork** [comment]
> 先试试add_rules("的信息，请参见.二进制")用来基于的信息，请参见编译二进制程序，不一定是驱动。
> 
> 且add_rules("的信息，请参见.静态")和信息，请参见.共享对应动态库，静态库

等大湿完善后请多多测试 exe dll sys mfc，妙不可言呐，谢谢大湿

**Comment by waruqi** [comment]
用户端程序，其实是支持的，可以看下文档：

https://xmake.io/#/zh-cn/guide/project_examples?id=umdf%e9%a9%b1%e5%8a%a8%e7%a8%8b%e5%ba%8f

```lua
target("app")
    add_rules("wdk.binary", "wdk.env.umdf")
    add_files("exe/*.cpp")
```

**Comment by waruqi** [comment]
之前默认使用的 还是外面安装的 msvc，仅仅用了 wdk 的 headers/libs。。

刚改进下了，如果找不到 vs 。。会继续从 wdk 目录找 msvc 来用。。
