### ISSUE TITLE
在win11上  error: .\core\base\tty.lua:239: attempt to index a boolean value

### ISSUE THREAD

**Issue by cyinen** [xmake-io/xmake#1929]
使用的是最新版本，运行xnake出现以下错误

error: .\core\base\tty.lua:239: attempt to index a boolean value
stack traceback:
        .\core\base\tty.lua:239: in function 'base/tty.has_emoji'
        .\core\base\colors.lua:258: in function 'base/colors.translate'
        .\core\base\utils.lua:185: in function 'base/utils.cprint'
        .\core\base\utils.lua:233: in function 'sandbox/modules/utils.error'
        .\core\main.lua:191: in function 'main._exit'
        (...tail calls...)

**Comment by waruqi** [comment]
你执行了 `xmake l winos.version` 给我看下输出

**Comment by cyinen** [comment]
ruki
这样子的




2021-12-20
| |
陈银
|
|
***@***.***
|
在2021年12月20日 ***@***.***> 写道：

你执行了 xmake l winos.version 给我看下输出

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by waruqi** [comment]
你在本地安装目录的 lua 脚本里面 

https://github.com/xmake-io/xmake/blob/fde9f472906c2b7061afa5afed4128817ffd15c1/xmake/core/base/tty.lua#L242

这个位置之前，加点 print 调下呢 比如 print(winos.version()) 看下输出，贴上来

**Comment by waruqi** [comment]
还是不行么，按上面步骤操作下呢，我这没win11 也没法复现问题

**Comment by waruqi** [comment]
我修复了 dev

xmake update -s dev
