### ISSUE TITLE
target:pkg("name"):get("includedirs") returns an empty string

### ISSUE THREAD

**Issue by Jackie365** [xmake-io/xmake#1932]
### Steps to reproduce
In an empty directory, use the following `xmake.lua` file
```
add_requires("lua")
target("name")
    set_kind("phony")
    add_packages("lua")
    on_build(function(target)
        print(target:pkg("lua"):get("includedirs"))
    end)
```
then execute `xmake`, it prints an empty line.
But it works fine for other fields, such as `linkdirs`, `syslinks` and `libfiles`. I'm not sure if it is a bug, and `target:pkg` is undocumented at the moment.

**Comment by waruqi** [comment]
目前包默认用的是 sysincludedirs 不是 includedirs，所以你得用 sysincludedirs 来取。。或者 `add_requires("lua", {external = false})` 切到 includedirs 上去
