### ISSUE TITLE
Add target.del_headerfiles

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#1939]
### Is your feature request related to a problem? Please describe.
I'm using `add_files` then `del_files` to remove some files which shouldn't be part of it, and now I would like to add headerfiles (and remove some which shouldn't be part of it).

To be clear, here's what I have:
```lua
-- Common config
set_group("Tests")
set_kind("binary")

add_deps("NazaraCore", "NazaraNetwork", "NazaraPhysics2D", "NazaraShader")
add_packages("catch2", "spirv-tools")
add_headerfiles("Engine/**.hpp")
add_files("resources.cpp")
add_files("Engine/**.cpp")

target("NazaraClientUnitTests")
	add_deps("NazaraAudio")

	add_files("main_client.cpp")

target("NazaraUnitTests")
	add_files("main.cpp")

	-- del_headerfiles("Engine/Shader/**") :(
	del_files("Engine/Audio/**")
```

### Describe the solution you'd like
Since `add_files` has `del_files`, it would be logical to have `del_headerfiles` too.

I tried to add it myself to make a PR (it doesn't seem very complicated) but I'm not comfortable enough yet with xmake internals.

### Describe alternatives you've considered
Add every header subfolder myself except those I don't wan't, but since del_files exists it seems del_headerfiles would be a nice addition

**Comment by waruqi** [comment]
you can use `add_headerfiles("**.h|excluded/*.h")`

**Comment by SirLynix** [comment]
It won't work with my code (and when I'll have multiples subfolder I guess), since I add files for both targets but want to remove files for only one

**Comment by waruqi** [comment]
At present, I am not very satisfied with the naming convention of del_files, so I have not added other interfaces.
But I might consider changing to other naming conventions later. For example, remove_files, remove_headerfiles, rm_files, rm_headerfiles ...

**Comment by SirLynix** [comment]
For reference:
[**Premake** uses `removefiles`](https://github.com/premake/premake-core/wiki/Adding-Source-Files)
[**CMake** uses `REMOVE_ITEM`](https://cmake.org/cmake/help/v2.8.10/cmake.html#command:list)
[**Maven** seems to use "delete"](https://stackoverflow.com/questions/18637626/remove-or-delete-resource-files-from-target-directory-using-pom-file)
[**Gradle** seems to use "delete" as well](https://stackoverflow.com/questions/27285885/gradle-delete-files-with-certain-extension)
[**Meson** seems to have a "delete" command](https://mesonbuild.com/Rewriter.html)

So it seems delete and remove are the two common keywords for this, since `delete` may seems ambiguous (since "delete file" may mean deleting it from the filesystem, same for `rm` since it's an unix command), I can suggest using `remove`, `remove_files`, `remove_headerfiles` and such.

**Comment by SirLynix** [comment]
Also thinking about it, a word that I haven't seen in other build tools is, but may be more clear, is "exclude" (`exclude_files`, `exclude_headerfiles`)

**Comment by waruqi** [comment]
Thank you, I think remove_files and remove_headerfiles are better.

**Comment by eli-schwartz** [comment]
meson's "delete" command is for the scriptable tool to edit the build definition files.

I think the concept you are working with here has more to do with inheritance, and specifically partial inheritance? i.e. targets seem to have sub-targets that inherit the list of associated source files, and you can restrict that by later on by removing some of those files from the target node.

This is definitely not something meson has an equivalent to, since meson supports neither globs nor target inheritance. Instead, one would simply create two meson arrays, and add one set of files to one target and both sets of files to the other target.

Also meson's rewriter uses `delete` to delete attributes, and `remove` to remove array elements from an attribute value.

**Comment by waruqi** [comment]
I have added `remove_files` and `remove_headerfiles` on `remove` branch. you can try it. `xmake update -s github:xmake-io/xmake#remove`

**Comment by waruqi** [comment]
It has been merge into dev now.

**Comment by SirLynix** [comment]
I get errors
```lua
error: @programdir\core\main.lua:280: @programdir\core\project\target.lua:1515: bad argument #1 to 'remove' (position out of bounds)
stack traceback:
    [C]: in function 'remove'
    [@programdir\core\project\target.lua:1515]: in function 'pred'
    [@programdir\core\base\table.lua:458]: in function 'remove_if'
    [@programdir\core\project\target.lua:1507]: in function 'headerfiles'
    [@programdir\plugins\project\vstudio\impl\vs201x.lua:572]: in function 'make'
    [@programdir\plugins\project\vstudio\vs.lua:50]: in function '?'
    [@programdir\plugins\project\main.lua:79]: in function '_make'
    [@programdir\plugins\project\main.lua:89]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\base\task.lua:519]: in function 'run'
    [@programdir\core\main.lua:278]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:371]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:827: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:280: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:371: in function <@programdir\core\base\scheduler.lua:368>
```

**Comment by waruqi** [comment]
Try it again.

**Comment by SirLynix** [comment]
It works well, thank you!
