### ISSUE TITLE
xmake f --menu 后选择Exit 会更改设置

### ISSUE THREAD

**Issue by jinhe1314** [xmake-io/xmake#194]
首先执行
xmake f -p linux -a mips -m release --bin=~/buildroot-2018.02/output/host/usr/bin
编译都是正常
后执行
xmake f --menu 后选择Exit 
GCC的设置会变成X86_64的

xmake f -p linux -a mips -m release --bin=~/ingenic/work/buildroot-2018.02/output/host/usr/bin
xmake f  --menu
checking for the architecture ... x86_64

**Comment by waruqi** [comment]
我改下，目前点exit后，还会继续 config 过程，所以后期自动配置检测的时候，就给篡改了。。

我之后修改下，点exit直接退出，不在继续config，点save保存退出，并且开始config过程。

**Comment by waruqi** [comment]
我改好了。你可以重新拉取下master代码，编译安装更新下试试，现在点Exit，会直接退出，不影响之前的config内容了。
