### ISSUE TITLE
Projects with low Build Activity - Survey

### ISSUE THREAD

**Issue by jadsonjs** [xmake-io/xmake#1942]
Dear Developers of project **xmake-io/xmake**,

We are conducting a study on CI metrics and we noticed that in your project, something peculiar happened.

During the period you are using Travis CI, the project passed by a long period of inactivity.
We noticed that the TravisCI configuration file (.travis.yml) was committed to your project on the date of **2016-01-05**.
But there is only a build history in TravisCI for a very short period, between **2020-05-31** and **2020-06-24**, in which were performed suddenly **183** builds.

Please, we would like you to answer this short survey with just 4 questions to help us identify the cause of this behavior.

https://forms.gle/UkkFrxpi7MNscYmV7

**Comment by waruqi** [comment]
It happened a long time ago, and I can't remember it, sorry.

In addition, I have used github action ci instead of travis ci.
