### ISSUE TITLE
使用add_requires("vcpkg::第3方库")时，该库隐式依赖vcpkg中的openssl,生成 -lcrypto -lssl 而不是 -lssl -lcrypto，导致链接错误

### ISSUE THREAD

**Issue by firesxp007** [xmake-io/xmake#1948]
### 你在什么场景下需要该功能？

xmake-repo没有sqlpp11和sqlpp11-connector-mysql，只能使用vcpkg引入，而该库自动依赖vcpkg中的openssl，生成 -lcrypto -lssl 而不是 -lssl -lcrypto，导致链接错误

### 描述可能的解决方案

目前vcpkg 只是走了 lib list，没走里面的 pc pkgconfig 文件，希望可以改进下

**Comment by waruqi** [comment]
改进了
