### ISSUE TITLE
Output "field ‘_term_mode’ "messgae when requesting a repo third-party library

### ISSUE THREAD

**Issue by pioneerAlone** [xmake-io/xmake#1949]
xmake version
xmake v2.6.2+HEAD.90e499cb2, A cross-platform build utility based on Lua

xmake configure:
xmake f -p mingw -a x86 --mingw=C:\llvm-mingw

Execute process:
C:\Users\bakewell.wang\CLionProjects\lua>xmake f -p mingw -a x86 --mingw=C:\llvm-mingw -m debug
checking for mingw directory ... C:\llvm-mingw
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> lua v5.4.2
please input: y (y/n/m)
y
error: field '_term_mode' is not callable (a nil value)

Any idea will be greatly appreciated. Thanks!

**Comment by waruqi** [comment]
try https://github.com/xmake-io/xmake/releases/download/v2.6.2/xmake-dev.win64.exe first

**Comment by pioneerAlone** [comment]
The new version is valid, thanks!
