### ISSUE TITLE
Xmake run does not rebuild after file has changed

### ISSUE THREAD

**Issue by Immortalin** [xmake-io/xmake#1957]
### Describe the bug
`xmake run` runs the old binary instead of rebuilding when the source file has changed. Rebuilding before running if source file has changed is the default behaviour in other build tools such as `cargo` and `go`.

### Expected behavior
If source file has changed, xmake should rebuild.

### Error output
N/A

### Related Environment

Please provide compiling and running environment information:

- xmake version: 2.62
- os: Ubuntu under WSL2
- target platform: x64-Linux

**Comment by waruqi** [comment]
xmake run will not do anything to build, please run `xmake build` or `xmake` to do build first

**Comment by Immortalin** [comment]
Yes but it takes two commands to run program after changing source code. Other software like cargo can compile and run with one command. Is is possible to build and run with one command?

**Comment by waruqi** [comment]
use macro https://xmake.io/#/plugin/builtin_plugins?id=macros-recording-and-playback

or define custom task, https://xmake.io/#/plugin/plugin_development?id=run-plugin
