### ISSUE TITLE
Provide a default description for options

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1969]
### 你在什么场景下需要该功能？

目前如果option下没明确写`set_description(...)`则在`xmake f --menu`的时候此option的描述是空的，无法辨认，体验不太好

![image](https://user-images.githubusercontent.com/42310255/148922937-47a63d6a-8069-4b3a-9547-f02091d7a195.png)

### 描述可能的解决方案

为option提供一个默认的description（即option名）

**Comment by waruqi** [comment]
加上了
