### ISSUE TITLE
删除有合并库的静态库文件后，重新编译会使库失效并会缺少文件

### ISSUE THREAD

**Issue by Smartqiu** [xmake-io/xmake#1973]
### 描述问题

我有一个名为test的项目，我期望将test文件夹中的资源编译为静态库使用。编译的结果放在bulid文件夹中。

![image](https://user-images.githubusercontent.com/65647464/149288854-345b684b-1938-4f98-aa7b-5c6d41f708ec.png)

编译后的文件夹：
![image](https://user-images.githubusercontent.com/65647464/149300894-a40ab5bf-7e6e-411e-8265-afa063deab5d.png)

**xmake.lua：**
```
set_project("test")

add_rules("mode.debug", "mode.release")

if is_plat("android") then
	add_cxxflags("-std=c++11")
end

target("test")
	-- set kind
	set_kind("static")
	-- add files
	add_files("test/*.cpp")
	-- add lib
	add_files("test/*.lib")
```

**windows32位编译使用的bat**
`
xmake f -p windows -a x86 --vs_runtime=MTd -m debug
xmake build
`

**Android32位编译使用的bat**
`
xmake f -p android -a armeabi-v7a -m release --ndk_cxxstl=gnustl_static
xmake build
`

初次编译时生成的库是正常可用的，window编译生成了test.lib、test.pdb，Android编译生成test.a

**当我不删除bulid文件夹，仅删除bulid文件夹中的test.lib、test.pdb和test.a，重新执行bat，此时重新生成的静态库无法使用，静态库的大小发生了变化，应该是在合并库时出现问题，并且test.pdb丢失。**

**而如果删除整个bulid文件夹，重新编译后，生成的静态库是完全正常的。**

### 期待的结果

仅删除文件夹中生成的静态库文件时，重新编译依旧可以正常生成文件。

### 错误信息

这是我删除库文件后重新编译时的提示：
![image](https://user-images.githubusercontent.com/65647464/149291071-c1d93ba9-eafb-41bc-9a2b-1c8e9d718d70.png)
![image](https://user-images.githubusercontent.com/65647464/149291271-f13f2fa4-eefa-493f-8813-31b11c75b03a.png)

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.6.2.0
- xmake运行平台：Windows10
- xmake目标平台：Windows10

### 其他信息

如果我的描述不够清晰，您需要例子请留言

**Comment by waruqi** [comment]
走 utils.archive.merge_staticlib merge

https://github.com/xmake-io/xmake/issues/1638

**Comment by Smartqiu** [comment]
我已经看过了#1638的内容，并且作出了一些列的尝试，但并没有得到想要的结果

这是工程中的xmake.lua如下：
![企业微信截图_16421524933043](https://user-images.githubusercontent.com/65647464/149492185-4620fd70-b579-4f55-8722-a464d43f88ef.png)

工程目录下没有build文件夹时，运行xmake-vs2019-32.bat后
![image](https://user-images.githubusercontent.com/65647464/149488852-946bad60-0d97-48e2-8bb6-815fd6ee037d.png)
![企业微信截图_16421529122494](https://user-images.githubusercontent.com/65647464/149493231-a40aadb0-1d1e-406f-b83d-3bd438ef6c4f.png)
![image](https://user-images.githubusercontent.com/65647464/149493416-649d4e1b-9b6f-4cdc-a654-c53b613be373.png)

**我使用bat编译后生成了上图的静态库，此时是正常可用的**
**我仅删除上图中的静态库文件后，再次使用bat编译，变成了下图**
![image](https://user-images.githubusercontent.com/65647464/149493808-4a42c83c-b6a1-4948-b60e-b05161830488.png)
![image](https://user-images.githubusercontent.com/65647464/149493948-32064fdb-356d-42e7-a60b-9187e2ed7283.png)
修改xmake第18行添加的顺序
![image](https://user-images.githubusercontent.com/65647464/149494283-9d3ab672-bd14-43bc-8297-c5c0547e4edc.png)
![image](https://user-images.githubusercontent.com/65647464/149494385-7c7c1625-a6da-48f9-8606-e94abad62f53.png)
合成出的lib依旧是有问题的，重新生成的静态库大小都小于正常的库，并且缺少了.pdb文件

**Comment by waruqi** [comment]
既然用了 merge_staticlib，为什么还要 add_files 它们，这不是互相冲突覆写么。

另外，目前仅支持 merge 库，不会 merge pdb

**Comment by Smartqiu** [comment]
感谢您快速的回复,我会继续尝试解决问题。

**Comment by Smartqiu** [comment]
我尝试将18行注释掉，print(target:objectfiles())输出的值中反而没有了我需要的库，得到的lib依旧错误

**Comment by waruqi** [comment]
> 我尝试将18行注释掉，print(target:objectfiles())输出的值中反而没有了我需要的库，得到的lib依旧错误

这不是对的么，就是不应该有，走 add_files .lib 才会 hack 下这么搞，最后把所有 obj 打到 target

走 merge_staticlib 接口，你要自己指定输出 lib path ，不会打入当前 target

自己看下参数说明

https://github.com/xmake-io/xmake/blob/edcbcd5127a9f3b7bbe93d34aa1921856db9a8fb/xmake/modules/utils/archive/merge_staticlib.lua#L52

**Comment by OuYangPaste** [comment]
话说，我一直好奇，为什么不改成在 add_files 静态库时默认调用 merge_staticlib 呢

**Comment by waruqi** [comment]
> 话说，我一直好奇，为什么不改成在 add_files 静态库时默认调用 merge_staticlib 呢

懒得改 没时间

**Comment by waruqi** [comment]
改了下，再试试

**Comment by Smartqiu** [comment]
非常感谢您的解释

**Comment by waruqi** [comment]
确认下，刚的更新 可以了没有

**Comment by Smartqiu** [comment]
工程中使用的还是旧版本的,我会尽快使用新版本的进行测试,同时我还发现了一些其他问题,确认后我将一并告诉您

**Comment by waruqi** [comment]
用 dev 版本

**Comment by Smartqiu** [comment]
好的

**Comment by waruqi** [comment]
/temp.a /target.a 你确定这种 / 根路径 你有写权限？xmake 默认 root 下不让用的

**Comment by Smartqiu** [comment]
这个例子我是简化后的，这些.a实际位置在D盘中我的工作目录下

**Comment by waruqi** [comment]
win 我没环境，自己调下下面脚本，比如加上 android 什么的试试 

https://github.com/xmake-io/xmake/blob/c692e42656a2406d8c27f6503d1d7ef60b820abb/xmake/modules/utils/archive/merge_staticlib.lua#L28

**Comment by Smartqiu** [comment]
好的,我会继续尝试

**Comment by waruqi** [comment]
可以了么

**Comment by Smartqiu** [comment]
不好意思让您久等了，我尝试了加上 android 选项,但这样依旧无法运行。目前我的项目编译使用 add_files，这里的问题暂时搁置了 。

**Comment by waruqi** [comment]
> 不好意思让您久等了，我尝试了加上 android 选项,但这样依旧无法运行。目前我的项目编译使用 add_files，这里的问题暂时搁置了 。

我改进了下，你再试试，dev版本

**Comment by Smartqiu** [comment]
以下代码,分别添加多个库可以了，

```
lib = {target:targetfile(), "./libdetour.a",  "./librecast.a"}
merge_staticlib(target, target:targetfile(), lib)
```
不过如果我想添加目录下全部的.a还是会提示找不到库
```
lib = {target:targetfile(), "./*.a"}
merge_staticlib(target, target:targetfile(), lib)
```

**Comment by waruqi** [comment]
这不是shell，自己遍历追加 lib 并确保路径有效.  os.files(path.join(os.projectdir(), "xxx", "*.a"))

**Comment by Smartqiu** [comment]
非常感谢,理解了
