### ISSUE TITLE
add `-rdc=true` as default option for cuda

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1975]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
在Visual Studio中使用cuda时默认会启用 `-rdc=true` （Relocatable Device Code）（效果添加在cuflags里面）
![image](https://user-images.githubusercontent.com/42310255/149371794-3bc8e69f-19a0-445b-b782-f465929b437b.png)
而在xmake中不会默认启用，这就导致一些cuda项目port时编译失败，见 https://blog.csdn.net/groundhappy/article/details/53895105

希望能添加一个cuda.rdc的value，默认设置为true，对应开启rdc；同时可以用`set_values("cuda.rdc", false)`关闭。

**Comment by waruqi** [comment]
加了，再试试。

另外，有空也可以帮忙看看这个问题，https://github.com/xmake-io/xmake/issues/1972 你这有没有遇到，我暂时没有 win cuda 环境

**Comment by xq114** [comment]
我没遇到过，不过我也没win7的环境，测不了。

还有一个问题是xmake对nvcc的报错处理有问题，不开xmake -v的时候只能看到warning看不到error

**Comment by waruqi** [comment]
> 我没遇到过，不过我也没win7的环境，测不了。
> 
> 还有一个问题是xmake对nvcc的报错处理有问题，不开xmake -v的时候只能看到warning看不到error

你可以调下这里 

https://github.com/xmake-io/xmake/blob/edcbcd5127a9f3b7bbe93d34aa1921856db9a8fb/xmake/modules/core/tools/nvcc.lua#L351-L368

**Comment by xq114** [comment]
不加-rdc=true报错的信息是
```
ptxas fatal   : Unresolved extern function '_ZNK6grid2D8ind_cellEiRiS0_'
PoissonLike.cu
```
所以只检测`error:`检测不到，截断下来之后就只剩warning了。这里可以加一个`ptxas fatal   :`的检测，但不确定这个通用性如何

**Comment by waruqi** [comment]
不知道，你可以先改进下试试，回头有问题再改进

**Comment by xq114** [comment]
> 不知道，你可以先改进下试试，回头有问题再改进

而且在使用cl作为host compiler时cuda报的错误信息也是cl的格式（`error C2664:...`），这里直接被忽略了，这也不对。怎么在nvcc.lua里面获取host compiler？

**Comment by waruqi** [comment]
> > 不知道，你可以先改进下试试，回头有问题再改进
> 
> 而且在使用cl作为host compiler时cuda报的错误信息也是cl的格式（`error C2664:...`），这里直接被忽略了，这也不对。怎么在nvcc.lua里面获取host compiler？

从 nvcc 里获取我不太清楚，目前只能根据平台判断，假定默认的 host cc，比如 win 下默认是 cl.exe

然后有个 --cu-ccbin 可以切，走 config.get 来获取判断

**Comment by xq114** [comment]
现在还有一个问题，nvcc报的错误信息有些是stdout有些是stderr，但try-catch(errors)貌似只能获取stderr的信息，从而漏了一些报错信息，表现在结果上就是即使运行`xmake -v`也看不到完整的报错

**Comment by waruqi** [comment]
errors 可以是个 table，可以取到的 stdout，见：

https://github.com/xmake-io/xmake/blob/1c8adbbb12815c9cad0070621928f58dc5d3161e/xmake/modules/core/tools/cl.lua#L456

**Comment by cherichy** [comment]
但rdc默认为true的话，在linux上会有比较大的性能损失，建议可以把默认改成false，或者按平台选择不同的默认值。
