### ISSUE TITLE
CUDA device linking is not enabled on windows when building static libraries

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#1976]
### 描述问题

https://gitlab.kitware.com/cmake/cmake/-/issues/17520

cuda在linux下编译静态库时无需进行device linking，但在windows上无论静态库还是动态库都必须进行device linking。xmake这里犯了和cmake同样的错误，windows上编译静态库时没开device linking，导致报错

### 期待的结果

windows上默认打开device linking；

希望能通过设置`cuda.build.devlink`，手动强制启用device linking

### 错误信息

如果是xmake相关编译问题，请加上`-vD`参数运行，并给出完整编译输出信息以及执行的完整命令，例如：

```console
$ xmake -vD
error LNK2019: unresolved external symbol __cudaRegisterLinkedBinary_...
```

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.6.2
- xmake运行平台：windows
- xmake目标平台：windows

**Comment by waruqi** [comment]
自己改下这里 https://github.com/xmake-io/xmake/blob/edcbcd5127a9f3b7bbe93d34aa1921856db9a8fb/xmake/rules/cuda/devlink/xmake.lua#L46

**Comment by xq114** [comment]
这里还是有问题，之前是我没搞清楚，实际情况是只有当static lib最终进入的executable中没有.cu文件的时候才需要devlink static lib，否则不能devlink static lib，和是不是windows没有关系

**Comment by xq114** [comment]
我觉得这里还是回退原来的设置，然后检测 不带cu的binary依赖一个带cu的static library ，这种情况报 warning: cuda device link is not performed! specify `set("cuda.build.devlink", true)` to enable it. 让用户手动选择

**Comment by waruqi** [comment]
那你直接来个 pr 吧，这块我暂时也没 cuda for linux 环境测试。

另外，现在有 policy 了，`set("cuda.build.devlink", true)` 可以改为 policy 的方式，应该更合适些，也更加容易文档化

**Comment by xq114** [comment]
> 另外，现在有 policy 了，`set("cuda.build.devlink", true)` 可以改为 policy 的方式，应该更合适些，也更加容易文档化

policy和set_values的区别是什么？我理解policy是全局作用的，然而需要修改cuda.build.devlink的情况都是单个target修改，并不需要全局设置

**Comment by waruqi** [comment]
> policy和set_values的区别是什么？我理解policy是全局作用的，然而需要修改cuda.build.devlink的情况都是单个target修改，并不需要全局设置

policy 也是 target 粒度的，全局设置，所有 target 生效。。可以 `target:policy("xxx")` 对特定 target 访问，如果是对构建等等默认行为的控制修改可以用 policy。。

set_values 通常用于对一些 rule 和插件的 扩展参数设置

**Comment by waruqi** [comment]
> 我觉得这里还是回退原来的设置，然后检测 不带cu的binary依赖一个带cu的static library ，这种情况报 warning: cuda device link is not performed! specify `set_values("cuda.build.devlink", true)` to enable it. 让用户手动选择

那 shared 带 static 的情况呢？ 怎么看着跟 fpic 类似。。

**Comment by waruqi** [comment]
> 检测 不带cu的binary依赖一个带cu的static library

另外，这种检测，对大部分非 cuda 的项目，都会跑进去遍历检测。。加多了，targets 多了，多少会影响其他正常项目构建的效率

**Comment by waruqi** [comment]
目前初步加上了，https://github.com/xmake-io/xmake/pull/3397

但现在的实现方式，会去遍历所有 target 和 deps ，还不是很好，后面再看看有啥优化的办法吧

另外，我改成 `set_policy("build.cuda.devlink", true)` 了，走 policy 更正式点，后面会逐步替代掉 value 的设置

**Comment by xq114** [comment]
现在是在 `xmake check` 里面检查吗？这样做的话遍历也没关系了，不会拖慢编译速度，只有编译有问题的时候才会运行xmake check，不知道我理解的对不对？

**Comment by waruqi** [comment]
> 现在是在 `xmake check` 里面检查吗？这样做的话遍历也没关系了，不会拖慢编译速度，只有编译有问题的时候才会运行xmake check，不知道我理解的对不对？

目前是放在 xmake check 里面，但是一些比较快的常规 checker 检测（languages, kind 等检测），我设置了 timely = true，也就是编译时候，及时检测。。可以到 checker.lua 的 list 里面能看到。。

目前对 devlink 我也开启了，如果这个不是必须要在 编译时做检测，我可以默认关掉，仅仅对 xmake check 放开

**Comment by xq114** [comment]
可不可以设置成只有编译出错的时候检测？

**Comment by waruqi** [comment]
可以试下

**Comment by waruqi** [comment]
> 可不可以设置成只有编译出错的时候检测？

由于 coroutine scheduler 实现上的一些问题，在 build 失败后，目前不太好快速捕获和注入一些自定义脚本，不太好搞，要等后面改进完再试试了，我先仅仅对 `xmake check` 放开了 devlink check

https://github.com/xmake-io/xmake/issues/3401

**Comment by waruqi** [comment]
> > 另外，现在有 policy 了，`set("cuda.build.devlink", true)` 可以改为 policy 的方式，应该更合适些，也更加容易文档化
> 
> policy和set_values的区别是什么？我理解policy是全局作用的，然而需要修改cuda.build.devlink的情况都是单个target修改，并不需要全局设置

set_values 是早期设置，那个时候还没 set_policy，所以只要是对 rule 和 插件的扩展配置，都是放在 set_values 里面处理，避免新增太多 API

后来加了 set_policy 后，跟构建行为策略，包安装策略，全局工程等各种行为控制策略相关的，都建议放置到 policy 里面去设置
这个相对更加稳定规范化，devlink 的 policy 配置，我更新到文档里了，并且整个 policy 的文档，我单开了一栏，之后重点描述。。https://xmake.io/#/zh-cn/guide/build_policies?id=buildcudadevlink

而 set_values 还会保留，但主要不是用来配置策略了，而是 rule 和 plugins 里面一些扩展的值配置，可以通过这个设置，比如各种插件和规则的目录，路径，参数值，custom flags 值等等

**Comment by waruqi** [comment]
> 可不可以设置成只有编译出错的时候检测？

暂时用其他方式加上了，可以试下 https://github.com/xmake-io/xmake/pull/3402
