### ISSUE TITLE
armclang ar命令长度达到7175将出现archiving失败

### ISSUE THREAD

**Issue by Zmmfly** [xmake-io/xmake#1978]
### Describe the bug
ar命令长度达到7175将失败，将命令复制出，在cmd中执行却又可以成功。

### Expected behavior
将STM32 G0 HAL驱动库编译成静态库的过程中，编译阶段无任何问题，最后archiving阶段报错。

### Error output
因为build.log过长，与工程同时放进了压缩包
[stm32g0xx_hal_library.zip](https://yun.mxtech.ltd/s/Ynn4x77p5eKDL3X)

```console
error: Product: MDK Professional 5.34
Component: ARM Compiler 6.16
Tool: armar [5dfea700]

Archive creation and maintenance tool

Command format:

armar options archive [ file_list ]

Wildcards '?' and '*' may be used in file_list

Options:-

 -r         Insert files in <file_list>, replace existing members of the same name.
 -d         Delete the members in <file_list>.
 -x         Extract members in <file_list> placing in files of the same name.
 -m         Move files in <file_list>.
 -p         Print files to stdout.
 -a pos     Insert/move files after file named <pos>.
 -b pos     Insert/move files before file named <pos>.
 -u         Update older files only, used with -r.

 -n         Do not add a symbol table to an object archive.
 -s         Force regeneration of archive symbol table.
 -t         Print table of contents of archive.
--zs        Show the symbol table.
--zt        Summarize the archive contents (sizes + entries).
 -c         Suppress warning when a new archive is created.
 -C         Do not overwrite existing files when extracting.
 -T         Truncate file names to system maximum length.
 -v         Give verbose output.
--create    Force creation of a new archive.
--via file  Take additional arguments from via file.
--sizes     List the size of each member and the library total.
--entries   List sections containing ENTRY points.
--vsn       Print the current Armar Version.
--help      Print this message.

Examples:-

        armar -r  mylib.a obj1 obj2 obj3...
        armar -x  mylib.a ?sort*
        armar -d  mylib.a hash.o
        armar -tv ansilib.a
```

> If it is a xmake related compilation problem, please add the `-v -D` parameter and give the detailed compilation output information.

### Related Environment

Please provide compiling and running environment information:

- xmake version: xmake v2.6.2+HEAD.90e499cb2
- os: Win10 LTSC 2021
- target platform: cortex-m0plus

**Comment by waruqi** [comment]
你可以先自己调下这个地方，https://github.com/xmake-io/xmake/blob/909b14dd4774e651d778a575a0e99dcfdd22b41b/xmake/core/base/winos.lua#L158

为了绕过 win path limit，目前超过4096，会走 @link.txt 模式送入 ar 和 link

**Comment by Zmmfly** [comment]
> 你可以先自己调下这个地方，
> 
> https://github.com/xmake-io/xmake/blob/909b14dd4774e651d778a575a0e99dcfdd22b41b/xmake/core/base/winos.lua#L158
> 
> https://github.com/xmake-io/xmake/blob/909b14dd4774e651d778a575a0e99dcfdd22b41b/xmake/modules/core/tools/ar.lua#L46
> 
> 为了绕过 win path limit，目前超过4096，会走 @link.txt 模式送入 ar 和 link

`--via file  Take additional arguments from via file.`

armar 不支持这种 @link.txt 用法，可以通过 --via 参数传递，有什么方法在`function winos.cmdargv(argv, opt)`可以判断编译器？

**Comment by waruqi** [comment]
> > 你可以先自己调下这个地方，
> > https://github.com/xmake-io/xmake/blob/909b14dd4774e651d778a575a0e99dcfdd22b41b/xmake/core/base/winos.lua#L158
> > 
> > https://github.com/xmake-io/xmake/blob/909b14dd4774e651d778a575a0e99dcfdd22b41b/xmake/modules/core/tools/ar.lua#L46
> > 
> > 为了绕过 win path limit，目前超过4096，会走 @link.txt 模式送入 ar 和 link
> 
> `--via file Take additional arguments from via file.`
> 
> armar 不支持这种 @link.txt 用法，可以通过 --via 参数传递，有什么方法在`function winos.cmdargv(argv, opt)`可以判断编译器？

不能，这个是 win 下通用接口，而 --via 是对特定ar的处理，只能在 https://github.com/xmake-io/xmake/blob/909b14dd4774e651d778a575a0e99dcfdd22b41b/xmake/modules/core/tools/armar.lua 里面，参考 ar.lua 重写 linkargv link 这两，单独处理下

**Comment by Zmmfly** [comment]
https://github.com/xmake-io/xmake/pull/1979
