### ISSUE TITLE
xrepo install 是否支持为 CMake 构建的库指定 toolchain?

### ISSUE THREAD

**Issue by cyfdecyf** [xmake-io/xmake#1987]
目前工作中的一些项目需要同时支持 g++-9 和 g++-4.8 (不开启 cxx11 abi)，所以想通过指定 toolchain 来编译和使用两种不同 abi 的 C++ 库。

看到有两个地方可以指定 toolchain，使用 xmake dev 分支的代码，分别进行了如下尝试：

- `xrepo install --toolchain`
  - 尝试执行 `xrepo install --toolchain=gcc-4.8 gflags` 和 `xrepo install --toolchain=gcc-9 gflags`，并未生成两份编译产出
- `xrepo install -f toolchains=gcc-9 gflags`
  - 遇到如下错误信息 `error: cannot deserialize "{toolchains=gcc-9}": (t):1: attempt to perform arithmetic on a nil value (global 'gcc')`

从 #1204 的讨论来看，toolchain 仅支持 xmake.lua 构建的工程，想咨询下是否的确如此？

我也尝试了修改 xrepo 中对应 package 的 xmake.lua 文件，在其中指定 toolchain，并未产生效果。

**Comment by waruqi** [comment]
目前仅交叉编译 走 -p cross 平台，支持工具链切换。。其他 pc 平台，都是固定工具链的，因为要走 ci 严格压测的，随意换工具链，每个包不保证可靠构建。

不过你可以自己设置 CC LD 等环境编译来切

**Comment by cyfdecyf** [comment]
设置环境变量有尝试过，从行为来看 xmake 应该并没有检测 CC, CXX 等环境变量来判断是否可以使用已经安装的包。所以如果之前安装过某个包，直接更改 CC, CXX 环境变量并不会导致重新安装。从库的 manifest.txt 文件来看里面也为包含所使用的编译器信息。

尝试了用如下命令在 Linux 下安装 fmt 库

```
xrepo install -p cross/linux --toolchain=gcc-4.8 fmt
xrepo install -p cross/linux --toolchain=gcc-9 fmt
```

的确可以成功编译出两个版本的 fmt 库。

```
$  xrepo scan fmt
scanning packages ..
fmt-8.1.1:
  -> a4766615dc1647f49a5f0c5c71924c90: cross/linux, x86_64
    -> {shared=false,debug=false,pic=true,header_only=false,toolchains="gcc-9"}
  -> 5bc29dc728224317a69ab77efa35e0ab: cross/linux, x86_64
    -> {shared=false,debug=false,pic=true,toolchains="gcc-4.8",header_only=false}
```

由此有两个问题想咨询：

1. 如果仅是想切换编译器，并非为了交叉编译，使用 `-p cross` 是否会有不希望的副作用
    - 如果可以的话我会在 xrepo-cmake 中添加相关支持并提交 PR
2. xrepo 中如何使得一个 包支持 cross
    - 我对比了下 `libunwind` 的 xmake.lua，没能很快发现跟 `fmt` 的差异


另外可能在 `xrepo fetch` 时可能遇到了一个 bug：

```
$ xrepo fetch -f shared=false,debug=false,pic=true,toolchains="gcc-9",header_only=false fmt
error: cannot deserialize "{shared=false,debug="... : (t):1: attempt to perform arithmetic on a nil value (global 'gcc')
```

如果不是我使用上的问题，我可以提交 bug report。

**Comment by waruqi** [comment]
> 设置环境变量有尝试过，从行为来看 xmake 应该并没有检测 CC, CXX 等环境变量来判断是否可以使用已经安装的包。所以如果之前安装过某个包，直接更改 CC, CXX 环境变量并不会导致重新安装。从库的 manifest.txt 文件来看里面也为包含所使用的编译器信息。

不会，只会在安装包时候生效，各种环境因素太多，还要保证一致性，比较复杂，所以目前常规平台我没切工具链

> xrepo install -p cross/linux --toolchain=gcc-4.8 fmt

只支持 -p cross 。因为包仓库只有 cross 平台才会切，linux 虽然也可以交叉编译，但包暂时不走交叉编译逻辑

cross/linux 最好不要写成这样。

> 如果仅是想切换编译器，并非为了交叉编译，使用 -p cross 是否会有不希望的副作用

唯一的副作用就是，xmake-repo 仓库有些包暂时没加 cross 平台支持，只加了 linux, macosx, windows 等平台，遇到不支持的，你得提 pr 到 xmake-repo 仓库，改进下包，增加支持，其他没啥

> xrepo 中如何使得一个 包支持 cross

如果包定义里面看到以下两种 on_install 的，就是支持 cross 的。

一种：显式带有 cross 平台指定的，例如 openssl 的包，你可以参考下

```lua
package()
    on_install("cross", function(package))
```

另外一种 , 没有显式平台指定的，说明全平台支持的包，cross 甚至 ios android 啥全支持，通常此类 headeronly 和 xmake.lua 维护的多数

```lua
package()
    on_install(function(package))
```

**Comment by cyfdecyf** [comment]
尝试加 print 代码看了下，应该是因为 Linux shell 默认把引号去掉了，导致 `serialize._load` 的输入不是合法的 lua table 而出错。

改成如下调用之后不再报错，但是没有输出

```
$ xrepo fetch -f toolchains=\"gcc-9\" fmt
```

如果在 `xrepo fetch` 时指定 platform 和 arch，则会有如下报错：

```
$ xrepo fetch -p cross -a none -f toolchains=\"gcc-9\" fmt
error: error: target(working): toolchain not found!
```

发了个 PR 允许指定 `--toolchain` 参数给 `xrepo fetch`，现在我可以走通切换编译器的整个流程了。

**Comment by waruqi** [comment]
> 发了个 PR 允许指定 `--toolchain` 参数给 `xrepo fetch`，现在我可以走通切换编译器的整个流程了。

直接这样不行么？

```console
xrepo fetch -p cross -a none fmt
```

> 发了个 PR 允许指定 --toolchain 参数给 xrepo fetch，现在我可以走通切换编译器的整个流程了。

我不记得目前有把 toolchains 加入对 buildhash 的计算，你 fetch 时候加不加 --toolchains 都不会影响 fetch 结果才对

你加了 `-f toolchains=\"gcc-9\" ` 是因为设置到 configs = {} 里面去了，才会参与 buildhash 计算，分成两个不同的包。。

**Comment by cyfdecyf** [comment]
谢谢反馈~

我在 dev 分支最新代码上试过，

```
$ xrepo fetch -p cross -a none -f toolchains=\"gcc-9\" fmt
error: error: target(working): toolchain not found!

$ xrepo fetch -p cross -a none fmt
error: error: target(working): toolchain not found!
```

这个出错我通过加 print 代码来看应该是在执行 `xmake/modules/private/xrepo/action/fetch.lua` 中执行 `xmake f ...` 的时候出现的。

另外执行 `xrepo install -p cross fmt` 也会报上述错误，我贴一个带 `-vD` 的完整输出：

```
$ xrepo install -vD -p cross fmt
xmake f -c -v -D -p cross
checking for architecture ... none
error: @programdir/core/main.lua:280: @programdir/actions/config/main.lua:157: target(working): toolchain not found!
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:827]: in function 'raiselevel'
    [@programdir/core/sandbox/modules/utils.lua:181]: in function 'assert'
    [@programdir/actions/config/main.lua:157]: in function '_check_target_toolchains'
    [@programdir/actions/config/main.lua:427]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/core/base/task.lua:519]: in function 'run'
    [@programdir/core/main.lua:278]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:371]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:827: in function 'os.raiselevel'
        (...tail calls...)
        @programdir/core/main.lua:280: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:371: in function <@programdir/core/base/scheduler.lua:368>
error: @programdir/core/main.lua:280: @programdir/core/sandbox/modules/os.lua:393: execv(xmake f -c -v -D -p cross) failed(255)
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:827]:
    [@programdir/core/sandbox/modules/os.lua:393]:
    [@programdir/core/sandbox/modules/os.lua:290]: in function 'vrunv'
    [@programdir/modules/private/xrepo/action/install.lua:175]: in function '_install_packages'
    [@programdir/modules/private/xrepo/action/install.lua:235]:
    [@programdir/modules/private/xrepo/main.lua:196]:
    [@programdir/plugins/lua/main.lua:123]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/core/base/task.lua:519]: in function 'run'
    [@programdir/core/main.lua:278]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:371]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:827: in function 'os.raiselevel'
        (...tail calls...)
        @programdir/core/main.lua:280: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:371: in function <@programdir/core/base/scheduler.lua:368>
```

**Comment by waruqi** [comment]
哦 走 cross ，需要自己配置 toolchain 或者 --sdk 让它找到工具链才行，跟 buildhash 倒是没关系。。只是找不到你的 gcc-9 而已

那这样的话，你那个 pr 应该没啥问题。我 merge 了
