### ISSUE TITLE
支持asn1c编译

### ISSUE THREAD

**Issue by RickSKy** [xmake-io/xmake#1994]
即将asn文件生成c代码，同时可以直接引用相关头文件和编译生成的c。它需要asn1c工具。过程有点类似flex,bison

**Comment by waruqi** [comment]
你可以参考现有的 yacc lex vala 规则，提个pr过来

https://github.com/xmake-io/xmake/blob/master/xmake/rules/lex_yacc/yacc/xmake.lua

https://github.com/xmake-io/xmake/blob/master/xmake/rules/vala/xmake.lua

**Comment by waruqi** [comment]
可以了
