### ISSUE TITLE
xmake依赖vcpkg::boost时编译失败

### ISSUE THREAD

**Issue by alice7290** [xmake-io/xmake#1998]
### 描述问题

xmake依赖vcpkg::boost时编译失败，而当我将vcpkg::boost改为vcpkg::eigen3且没去掉boost相关代码的情况下却能编译成功

### 错误信息

PS D:\Projects\Mei\VcpkgTest\VcpkgTest> xmake -vD
checking for vswhere.exe ... C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
checking for cl.exe ... D:\VS2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2019
checkinfo: cannot runv(dmd.exe --version), No such file or directory
checking for dmd ... no
checkinfo: cannot runv(ldc2.exe --version), No such file or directory
checking for ldc2 ... no
checkinfo: cannot runv(gdc.exe --version), No such file or directory
checking for gdc ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(unzip.exe -v), No such file or directory
checking for unzip ... no
checking for 7z ... D:\xmake\winenv\bin\7z
checking for git ... ok
checkinfo: cannot runv(gzip.exe --version), No such file or directory
checking for gzip ... no
finding boost from vcpkg ..
checking for vcpkg::boost ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
in vcpkg:
  -> vcpkg::boost latest [vs_runtime:"MT"]
please input: y (y/n/m)
y
installing boost from vcpkg ..
checking for vcpkg ... D:\Projects\vcpkg\vcpkg
D:\Projects\vcpkg\vcpkg install boost:x64-windows-static --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: D:\Projects\vcpkg
[DEBUG] Using installed-root: D:\Projects\vcpkg\installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: D:\Projects\vcpkg\buildtrees
[DEBUG] Using downloads-root: D:\Projects\vcpkg\downloads
[DEBUG] Using packages-root: D:\Projects\vcpkg\packages
[DEBUG] Using scripts-root: D:\Projects\vcpkg\scripts
[DEBUG] Using ports-root: D:\Projects\vcpkg\ports
[DEBUG] Using versions-root: D:\Projects\vcpkg\versions
[DEBUG] Default binary cache path is: C:\Users\72904\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] Found path: D:\cmake\cmake-3.18.3-win64-x64\bin\cmake.exe
[DEBUG] CreateProcessW("D:\Projects\vcpkg\downloads\tools\cmake-3.20.2-windows\cmake-3.20.2-windows-i386\bin\cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    42130 us
[DEBUG] CreateProcessW("D:\Projects\vcpkg\downloads\tools\cmake-3.20.2-windows\cmake-3.20.2-windows-i386\bin\cmake.exe" -DVCPKG_ROOT_DIR=D:/Projects/vcpkg -DPACKAGES_DIR=D:/Projects/vcpkg/packages -DBUILDTREES_DIR=D:/Projects/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=D:/Projects/vcpkg/installed -DDOWNLOADS=D:/Projects/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\Projects\vcpkg\buildtrees\0.vcpkg_dep_info.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    27466 us
The following packages are already installed:
    boost[core]:x64-windows-static -> 1.75.0
Package boost:x64-windows-static is already installed

Total elapsed time: 235.3 us

[DEBUG] C:\A\1\121\s\src\vcpkg\install.cpp(1104)
[DEBUG] Exiting after 225218 us (223332 us)
finding boost from vcpkg ..
checking for vcpkg::boost ... no

error: ...\modules\private\action\require\impl\actions\install.lua:228: fetch vcpkg::boost-latest failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:827]: in function 'raiselevel'
    [@programdir\core\sandbox\modules\utils.lua:181]: in function 'assert'
    [...\modules\private\action\require\impl\actions\install.lua:228]:

  => install vcpkg::boost latest .. failed
error: @programdir\modules\private\async\runjobs.lua:232: ...\modules\private\action\require\impl\actions\install.lua:301: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:827]:
    [...\modules\private\action\require\impl\actions\install.lua:301]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:170]:
    [...modules\private\action\require\impl\install_packages.lua:367]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:208]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:827: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir\modules\private\async\runjobs.lua:232: in field 'catch'
        @programdir\core\sandbox\modules\try.lua:127: in global 'try'
        @programdir\modules\private\async\runjobs.lua:200: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:371: in function <@programdir\core\base\scheduler.lua:368>

将vcpkg::boost改为vcpkg::eigen3后的xmake -vD信息

PS D:\Projects\Mei\VcpkgTest\VcpkgTest> xmake -vD
[ 25%]: compiling.release src\main.cpp
D:\VS2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe -c /EHsc -nologo -Ox -fp:fast -std:c++latest -external:W0 -external:ID:\Projects\vcpkg\installed\x64-windows-static\include -DNDEBUG -Fobuild\.objs\VcpkgTest\windows\x64\release\src\main.cpp.obj src\main.cpp
[ 50%]: linking.release VcpkgTest.exe
D:\VS2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe -nologo -dynamicbase -nxcompat -machine:x64 /opt:ref /opt:icf -out:build\windows\x64\release\VcpkgTest.exe build\.objs\VcpkgTest\windows\x64\release\src\main.cpp.obj
[100%]: build ok!

### 相关环境

- xmake版本：v2.6.3+HEAD.e2bbeb1b0
- xmake运行平台：win10
- xmake目标平台：win10

### 其他信息

add_rules("mode.debug", "mode.release")

set_languages("c17", "c++latest")

add_requires("vcpkg::boost")

target("VcpkgTest")
    set_kind("binary")
    add_packages("vcpkg::boost")
    add_files("src/*.cpp")

**Comment by waruqi** [comment]
vcpkg 里面 没有 boost 这个包，只有 vcpkg::boost[core]  vcpkg::boost-xxx 等一系列子包。。你先仔细看下 vcpkg 里面 boost 包的命名和使用

**Comment by waruqi** [comment]
相关重复 issues:

https://github.com/xmake-io/xmake/issues/1585#issuecomment-901774386
https://github.com/xmake-io/xmake/issues/1605

**Comment by alice7290** [comment]
我修改为"vcpkg::boost-range"后OK了，谢谢
