### ISSUE TITLE
xmake -P run error in xmake 2.6.3

### ISSUE THREAD

**Issue by OuYangPaste** [xmake-io/xmake#2000]
### 描述问题

xmake 更新到 2.6.3 dev 之后 xmake -P 不带路径会直接报错

### 错误信息

```console
➜  test xmake -vDP
error: @programdir/core/main.lua:144: assertion failed!
stack traceback:
        [C]: in function 'assert'
        @programdir/core/main.lua:144: in function 'main._init'
        @programdir/core/main.lua:209: in function 'main.entry'
        (...tail calls...)

```

### 相关环境

- xmake版本： xmake v2.6.3+dev.fbb7163
- xmake运行平台：x86_64 linux

**Comment by waruqi** [comment]
这跟 2.6.3 有啥关系，之前的版本也是一样，这原本就是无效输入参数，总归会报错的，顶多就是目前的错误输出不可读，回头改成 invalid arg 而已，其他也没啥

**Comment by OuYangPaste** [comment]
emmm 我看 help 说生效优先级是 输入目录, $XMAKE_PROJECT_DIR, 本路径，目前 XMAKE_PROJECT_DIR 也没法用，而且我 2.6.2 是没问题的

**Comment by waruqi** [comment]
我切了好几个版本，一样的错误，这块逻辑n年没动过了。。-P 原本就是 key/value 的参数输入，你光设置 key: -P 不设置输入参数 value，原本就是不对的。。改成：`-P .`

只有 --yes/-y 此类才是 keyonly 参数，可以只输入 -y

你的参数输入格式都不对，跟 XMAKE_PROJECT_DIR 没啥关系

**Comment by OuYangPaste** [comment]
😂奇怪了，因为我们有个地方一直用的就是 -P（放在命令最后)，之前版本也没报过这个错

**Comment by waruqi** [comment]
不管有没有报错，反正这么输入就是不对的。自己改下输入

**Comment by OuYangPaste** [comment]
好吧...不过我期望类似的规范和变动能出现在更新日志里🥺

**Comment by waruqi** [comment]
> 好吧...不过我期望类似的规范和变动能出现在更新日志里🥺

没改过哈，哪来的 changelog

**Comment by OuYangPaste** [comment]
emmm, 真奇怪，好奇心上来了，我下午研究下，诡异了

**Comment by OuYangPaste** [comment]
找到变化原因了，以前 key value 放在最后不传入 value, 会拿到空字符串，然后在 @programdir/core/main.lua -> main._init  -> path.absolute(projectdir) 能转换出路径出来，而我更新完之后，可能是由于 tbox 这个[fix commit](https://github.com/tboox/tbox/commit/f301f5eca1e909ffd6bcf688f14646d8226acfd9) 导致我之前使用错误的问题暴露出来

**Comment by waruqi** [comment]
哦哦，那是好事情，说明之前的 fix 有效果了
