### ISSUE TITLE
Question:  How can I use the complete library in custom functions?

### ISSUE THREAD

**Issue by kompasim** [xmake-io/xmake#2001]
I want to do some customization work before building, such as creating a folder or downloading a zip file. but I found that some lua libraries are incomplete in custom functions. How can I use the complete library in my functions?

my example:
```lua
local function test()
    print("TEST1:", os.isdir, os.run)
end
before_build(function()
    test()
    print("TEST2:", os.isdir, os.run)
end)
target("test")
set_kind("binary")
add_files("test.c")
```

output:
```
checking for Microsoft Visual Studio (x64) version ... 2017
TEST1:  function: 00007FF751145828      nil
TEST2: <function: 0000015937396010> <function: 0000015937396DD0>
[100%]: build ok!
```

xmake version: xmake v2.6.3+HEAD.e2bbeb1b0

**Comment by kompasim** [comment]
I can pass the libraries as the argument of the function, but it seems not smart.

**Comment by waruqi** [comment]
Please do not call or access functions and variables describing the scope in the script scope before_build.

It is recommended that you first understand the difference between the description scope and the script scope: https://xmake.io/#/guide/syntax_description

You can import and use your custom modules in the script scope using the import interface: https://xmake.io/#/manual/builtin_modules?id=import
