### ISSUE TITLE
[Question] how to cross-compile xmake for Android

### ISSUE THREAD

**Issue by leleliu008** [xmake-io/xmake#2003]
Hi there, I wanna run xmake on Android, I wanna known how to cross-compile xmake for Andriod using Android NDK? Thank you!

**Comment by waruqi** [comment]
```console
cd core
xmake f -p android --ndk=~/android-ndk-r23b
xmake
```

**Comment by leleliu008** [comment]
![22](https://user-images.githubusercontent.com/3040852/150736858-717e920c-8fc6-4251-8f04-684fc09442be.PNG)

**Comment by waruqi** [comment]
git submodule update --init

**Comment by leleliu008** [comment]
Works like a charm, thank you very much!

**Comment by leleliu008** [comment]
Let me sum up how to cross-compile xmake for Andriod using Android NDK from github source tree:

```
git clone --recursive  https://github.com/xmake-io/xmake
cd xmake/core
xmake f -p android --ndk=~/android-ndk-r23b
xmake
```
![24](https://user-images.githubusercontent.com/3040852/150739644-1a51892c-ec55-4373-b378-a8d22c076111.PNG)
