### ISSUE TITLE
Failed to find cuda devices on windows

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2004]
### 描述问题

```
add_cugencodes("native")
```
windows下报错
```
warning: failed to find cuda devices: nvcc fatal   : Cannot find compiler 'cl.exe' in PATH
```

### 期待的结果

正常探测到cugencodes

### 错误信息

如果是xmake相关编译问题，请加上`-vD`参数运行，并给出完整编译输出信息以及执行的完整命令，例如：

```console
$ xmake f -vD
checking for C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc ... ok
checking for cuda devices
configure
{
    ...
}
warning: failed to find cuda devices: nvcc fatal   : Cannot find compiler 'cl.exe' in PATH
```

如果日志太多，可以上传附件，但必须完整，否则一率标记为 Invalid。

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.6.3
- xmake运行平台：windows
- xmake目标平台：windows

**Comment by waruqi** [comment]
改了下，不过没环境测试 

如果有问题，可以参考这个 patch ，自己再调调改改

https://github.com/xmake-io/xmake/commit/dee5ebd8220b3695a0ebf43d88fee06d910766ee

**Comment by xq114** [comment]
可以了
