### ISSUE TITLE
path.extension returns incorrect result

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2005]
### 描述问题

当文件没有扩展名时path.extension返回值错误
![image](https://user-images.githubusercontent.com/42310255/150740566-84d57be0-8115-4875-9f25-93afd7e77dd9.png)

### 期待的结果

path.extension能正确识别路径分隔符，返回空字符串

### 错误信息

如果是xmake相关编译问题，请加上`-vD`参数运行，并给出完整编译输出信息以及执行的完整命令，例如：

```console
$ xmake l -vD path.extension 1.1\abc
running builtin module path.extension with args:
dump from _print_vlog @.\C:\Users\xq114\xmake\plugins\lua\main.lua:55 
"1.1\abc"
dump from <anonymous> @.\C:\Users\xq114\xmake\plugins\lua\main.lua:125
".1\abc"
```

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.6.3
- xmake运行平台：windows
- xmake目标平台：windows

**Comment by waruqi** [comment]
可以了 再试试
