### ISSUE TITLE
Updating repositories failed when ran xmake.

### ISSUE THREAD

**Issue by lhgzbxhz** [xmake-io/xmake#2007]
I want to add a vcpkg package in my project.
I coded like this:`add_requires("vcpkg::bdwgc")`
When I ran `xmake`:

checking for mingw directory ... F:\MinGW\mingw64
updating repositories .. error: Updating 748a683..a9e031a
ke-mirror/build-artifacts
 * branch            main       -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
        .github/workflows/windows.yml
        packages/b/benchmark/1.5.5/manifest.txt
        packages/b/boost/1.77.0/manifest.txt
        packages/f/fmt/8.0.1/manifest.txt
        packages/f/freetype/2.11.0/manifest.txt
        packages/g/glslang/1.2.189+1/manifest.txt
        packages/h/hdf5/1.12.1/manifest.txt
        packages/i/imgui/v1.83/manifest.txt
        packages/i/imgui/v1.85/manifest.txt
        packages/l/libffi/3.4.2/manifest.txt
        packages/l/libiconv/1.16/manifest.txt
        packages/l/libsdl_image/2.0.5/manifest.txt
        packages/l/libvorbis/1.3.7/manifest.txt
        packages/l/libxml2/2.9.12/manifest.txt
        packages/n/nasm/2.15.05/manifest.txt
        packages/o/openssl/1.1.1l/manifest.txt
        packages/p/pcre/8.45/manifest.txt
        packages/p/python/3.9.6/manifest.txt
        packages/s/suitesparse/v5.10.1/manifest.txt
Please commit your changes or stash them before you merge.
Aborting

notes:
- xmake version: xmake v2.6.3+HEAD.e2bbeb1b0
- os: windows x64
- target platform: mingw-x64

I tried to update the xmake, but It didn't work.

**Comment by waruqi** [comment]
try `rm ~/.xmake/repositories/xmake-repo` or `git reset` it

**Comment by waruqi** [comment]
try `rm ~/.xmake/repositories/xmake-repo` or `git reset` it
