### ISSUE TITLE
有关于mfc的支持介绍么？

### ISSUE THREAD

**Issue by xigalto** [xmake-io/xmake#201]
有个mfc的项目也想移植过来，不过发现不知道用什么方式指定为mfc项目，有没有类似cmake的CMAKE_MFC_FLAG这种东西存在？

**Comment by waruqi** [comment]
暂时还不支持mfc哦。。

**Comment by waruqi** [comment]
可以在 https://github.com/tboox/xmake/tree/master/xmake/rules/winsdk 目录下，新增一个 mfc的目录，参考里面 dotnet的规则定义，扩展支持一个mfc的构建规则。。。

```lua
target("test")
    add_rules("win.sdk.mfc")
    add_files("src/*.c")
```

通过应用win.sdk.mfc规则， 可直接对target进行编译支持，内置一些mfc才有的links,linkdirs以及includedirs设置，可能需要在增加一个`win.sdk.mfc.env`作为依赖规则用于在on_load的时候探测和加载mfc的一些sdk路径和设置。。

对于vcproj的工程生成，可以通过判断 `if target:rule("win.sdk.mfc") then`是否存在，来增加对mfc的支持，不需要额外的values设置。

总结下：

- [ ] win.sdk.mfc 规则定义
  - [ ] win.sdk.mfc.env 依赖规则，优先执行检测加载mfc环境，可参考：https://github.com/tboox/xmake/blob/master/xmake/rules/wdk/env/xmake.lua
- [ ] vcproj工程mfc支持

当然，你也可以预定义一个 win.sdk.mfc的空规则，先把vcproj工程mfc支持的支持，通过判断`if target:rule("win.sdk.mfc") then`的方式先实现掉。。

至于win.sdk.mfc规则的实现本身，之后再实现也可以。

**Comment by xigalto** [comment]
mfc的规则昨晚在家的时候已经写好了，不过没提交，暂时还有点问题。就是目前xmake对rc似乎没怎么处理，编译能通过，但是rc并没有生效（表现就是加载对话框资源会失败，找不到资源）。直接加入vsproject中是可以的，我猜测应该是差了link这一步。
另外rc的后缀应该是.res，obj在vs201x中可以链接，但是vs200x中不行，会报错。

**Comment by waruqi** [comment]
rc目前仅支持直接编译，在生成vcproj里面没怎么处理，因为xmake重点还是在直接构建上，所以对vcproj生成的支持，仅处于基本可用，没做完善的支持
