### ISSUE TITLE
Support to inherit base package

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#2011]
I can use this feature to override the partial configuration of builtin package in xmake-repo.

### Override package configuration

for example: override package urls, ...

```lua
package("myzlib")
    set_base("zlib")
    set_urls("https://github.com/madler/zlib.git")
package_end()

add_requires("myzlib", {system = false, alias = "zlib"})

target("test")
    set_kind("binary")
    add_files("src/*.c")
    add_packages("zlib")
```

### Define alias package in repositories

like this, an alias package(onetbb -> tbb): https://github.com/xmake-io/xmake-repo/blob/master/packages/o/onetbb/xmake.lua

```lua
package("onetbb", {base = "tbb"})
```

or 

```lua
package("onetbb")
    set_base("tbb")
```

xmake.lua

```lua
add_requires("onetbb")
```

Related issues: https://github.com/xmake-io/xmake/pull/2010

**Comment by yamashi** [comment]
Does this mean we can also add versions without making a PR?

**Comment by waruqi** [comment]
> Does this mean we can also add versions without making a PR?

You can do it, but I still hope you can open pr to help update the package versions in the repository.
