### ISSUE TITLE
头文件路径的依赖传递

### ISSUE THREAD

**Issue by stolen-programmer** [xmake-io/xmake#2013]
### 你在什么场景下需要该功能？

关于依赖传递  头文件路径不在传递范围内 我在文档中 没有找到相关内容(如果有 我很抱歉) 

### 描述可能的解决方案

add_includedirs() 可以考虑加一个属性 来确定是否传递路径

### 描述你认为的候选方案

多目标写多个add_includedirs(args) args相同是很愚蠢的  当然 也可以生成CMakeLists.txt 然后手动修改(更蠢)

### 其他信息

没了

**Comment by xq114** [comment]
add_includedirs("inc", {public = true})

**Comment by stolen-programmer** [comment]
好伐 确实没注意
