### ISSUE TITLE
xmake r loading shared libraries failed

### ISSUE THREAD

**Issue by stolen-programmer** [xmake-io/xmake#2014]
### 描述问题

xmake -rv; xmake r  提示找不到库 
![rt](https://user-images.githubusercontent.com/23734345/151118786-27f4f96d-bfc2-4a0b-bb91-102a461e005a.png)

### 错误信息

error while loading shared libraries: libdecor.so: cannot open shared object file: No such file or directory

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：xmake v2.6.3+202201251818
- xmake运行平台：WSL/Ubuntu
- xmake目标平台：WSL/Ubuntu

### 其他信息

![xmake-lua](https://user-images.githubusercontent.com/23734345/151119215-6a10e6fd-1ab0-490f-b80e-0752ac54aacb.png)

**Comment by waruqi** [comment]
看不出什么问题，我这测试也ok，你自己加 -vD 看下编译链接详情，自己分析下 link options 看看哪里有问题。。或者自己复制link command 手动改改执行下 调调

**Comment by stolen-programmer** [comment]
了解

**Comment by stolen-programmer** [comment]
主要是就这一个库有问题  更坑爹的是  用cmake构建也有问题 我换了几个名字 貌似也不行
