### ISSUE TITLE
msvc 编译出错，是两个文件同名的导致的

### ISSUE THREAD

**Issue by car520120** [xmake-io/xmake#2015]
严重性	代码	说明	项目	文件	行	禁止显示状态
警告	C6387	“lib”可能是“0”: 这不符合函数“GetProcAddress”的规范。	lite-xl	D:\Home\Learn\ide\lite-xl\src\main.c	90	
警告	MSB8027	名为 renderer.c 的两个或更多文件将生成到同一位置的输出。这会导致错误的生成结果。   调用的文件是 ..\..\src\renderer.c, ..\..\src\api\renderer.c。	lite-xl	C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets	1088	
警告	LNK4042	对象被多次指定；已忽略多余的指定	lite-xl	D:\Home\Learn\ide\lite-xl\build\.objs\lite-xl\windows\x64\debug\renderer.obj	1	
错误	LNK2001	无法解析的外部符号 luaopen_renderer	lite-xl	D:\Home\Learn\ide\lite-xl\vs2022\lite-xl\api.obj	1	
错误	LNK1120	1 个无法解析的外部命令	lite-xl	D:\Home\Learn\ide\lite-xl\build\windows\x64\debug\lite-xl.exe	1

**Comment by waruqi** [comment]
请按 issues 模板规范反馈问题
