### ISSUE TITLE
Add additional files to vs project generator

### ISSUE THREAD

**Issue by car520120** [xmake-io/xmake#2017]
### 你在什么场景下需要该功能？

生成 vs2022工程
只是需要加入 .lua .hxx  .js 等一些特殊文件
不需要编译也不需要设置环境 vs 类型 ：实用工具
因为 vs有额外的插件可以调试这种文件

### 描述可能的解决方案
xmake project -k   vsxmake 
生成的工程包含这类型文件的集合就可以了，就类似纯头文件工程一样的
因为后续调时会用得上的

### 描述你认为的候选方案

xmake.lua
```
target("lualib")
    set_kind("binary")
    set_default(false)
    add_headerfiles("lualib/*.lua")
    add_headerfiles("lualib/*.js")
    add_files("src/*.c")
```

lualib/main.c
```
#include <stdio.h>
int main()
{
    return 0;
}
```

是可以实现类似的功能，但是多了 main.c 感觉不太好的样子

**Comment by waruqi** [comment]
dev可以设置成 phony 类型
