### ISSUE TITLE
白色背景无法阅读黄色文字

### ISSUE THREAD

**Issue by wangzhankun** [xmake-io/xmake#2018]
### 你在什么场景下需要该功能？
在使用白色主题的terminal时

### 问题如图所示

![image](https://user-images.githubusercontent.com/35724924/151654823-c4d8e468-6488-4d7d-a8cf-e06b44aa40e8.png)

### 描述你认为的候选方案
希望能够增加对白色主题的支持。

**Comment by waruqi** [comment]
你可以参考dark主题 加个 light 主题 提个 pr 过来
https://github.com/xmake-io/xmake/tree/master/xmake/themes

**Comment by wangzhankun** [comment]
请问我应该怎么做测试呀？如果我添加了一个light的文件夹之后，应该修改哪里的配置文件以使其生效呀？

**Comment by waruqi** [comment]
看下 https://xmake.io/#/zh-cn/theme/switch_theme

**Comment by wangzhankun** [comment]
我添加了light的文件夹，把dark目录下的xmake.lua拷贝了进来，执行`xmake g --theme=light`提示找不到light的主题。

**Comment by waruqi** [comment]
theme("light")

**Comment by wangzhankun** [comment]
已提交PR：#2019

**Comment by waruqi** [comment]
merge le

**Comment by waruqi** [comment]
搞错了，其实你应该直接用 dark 主题，针对浅色背景，所以主题配色得 dark 

而 light 主题，应该是针对深色背景。。

我刚改了下，同步了你的改动到 dark theme，light 的我改了下，你应该切到 dark 上去
