### ISSUE TITLE
set_targetdir generates wrong directory under CMake building

### ISSUE THREAD

**Issue by Xertok** [xmake-io/xmake#2026]
### Describe the bug
To reproduce the issue:
In **xmake.lua** we set our target directory to  `set_targetdir("../bins")` and then generate CMake with `xmake project -k cmake -y`
and when we build with CMake, it builds in the wrong directory.

### Expected behavior
In CMake we expect to have a `../../bins` directory, but we get `../bins` in the way defined in **xmake.lua**

### Related Environment

- xmake version: **xmake v2.6.3+HEAD.e2bbeb1b0**
- os: **Windows 10**
- ide: **CLion 2021.2.3**

### Additional context

- We need to be able to customize the CMake directory `set_targetdir ("../bins", {cmake = "../../bins"})`
- If the above is not a good/acceptable idea, then generate an extra parent (`../`)

**Comment by waruqi** [comment]
you can use absolute path, `set_targetdir("$(projectdir)/bin")`

**Comment by Xertok** [comment]
The problem seems to persist after setting `set_targetdir("$(projectdir)/../../bins")`, is still building in the wrong directory

**Comment by waruqi** [comment]
please update to dev and try it again. `xmake update -s dev`

**Comment by Xertok** [comment]
Thanks it works great now
