### ISSUE TITLE
为CUDA项目改善Ampere架构支持

### ISSUE THREAD

**Issue by Shan-Zhou** [xmake-io/xmake#2027]
### 你在什么场景下需要该功能？

目前在Ampere架构显卡上测试xmake自带的cuda项目（xmake create -l cuda test）时发现在设置add_cugencodes("native")时xmake能正确地检测到显卡的架构并编译，但会提示warning: unknown architecture:sm_86（根据显卡型号不同也可能是87）

### 描述可能的解决方案

在xmake/rules/cuda/gencodes/xmake.lua第46和47行（local known_v_archs = ... 和 local known_r_archs = ...）里增加86和87。我不太熟悉xmake的结构不确定其他地方需不需要改，不过在我自己的电脑上试了试似乎只要改这一个地方就行。

### 其他信息

在CUDA 11.6 & VS2022 & Windows 11环境中测试了一下上面的方案似乎可以解决问题。

**Comment by waruqi** [comment]
这块也是人家贡献的，我也没环境测试，你可以先来个pr过来

**Comment by Shan-Zhou** [comment]
https://github.com/xmake-io/xmake/pull/2028

**Comment by waruqi** [comment]
merge le ，谢谢
