### ISSUE TITLE
C++ Toolchain settings seem not taking effect for the building of external dependencies

### ISSUE THREAD

**Issue by saltylin** [xmake-io/xmake#2034]
### Is your feature request related to a problem? Please describe.
We want to use custom C++ toolchains to build all the source files (including external dependencies), but it seems only working for the main project. We also didn't find any related solution in the xmake document.

### Describe the solution you'd like
It would be better if the main C++ project and external dependencies are built with the same custom toolchain.

### Describe alternatives you've considered
We also tried Bazel, which has unified the building toolchains. However, Bazel is too complicated to use.

**Comment by waruqi** [comment]
Currently only toolchains defined in the global ~/.xmake/xmakerc.lua file and cut to the cross platform (`-p cross`) support building external dependencies.

Maybe I will continue to improve it in the future, but currently you can only define the toolchain in the global xmakerc.lua file so that xmake can pass it to the build environment of external dependencies.

**Comment by waruqi** [comment]
都是国人，就直接中文吧

### 关于工具链切换

目前走 add_requires 的外部依赖包，只有 xmake f -p cross 切到交叉编译平台，才支持工具链透传，而 linux, win, mac, ios, android mingw  等平台，是固定工具链的，比如 win 下就是 vs，android 就是 ndk 不能随意修改工具链。

这是因为，所有 xmake-repo 包，在提交入库时候，ci 上会对每个平台做严格压测的，你随意切换自定义工具链，不能保证依赖包构建的可靠性，容易失败。

而对于交叉编译平台，只要这个包支持交叉编译，用户就可以随意切换工具链。。

### 关于工具链透传

另外，即使 cross 平台交叉编译，目前只有 cmake/autoconf/meson 维护的依赖包，支持用户在本地项目中自定义 toolchain 透传进去，因为，xmake 内部会拆解成 cc, ld 逐个透传的。

而如果这个依赖包，是用 xmake.lua port 维护的，目前是走的 --toolchian=xxx 直接透传的 toolchain name，所以，用户定义的 本地 toolchain，对于依赖包的 xmake.lua 内部是不可见的，所以要定义到全局 xmakerc.lua 里面，xmake 才能在构建依赖包时候找到这个自定义工具链的实际定义。

关于这个问题，我回头有空会改进，不过目前 xmake-repo 中 xmake.lua 维护的包还不是很多，倒是问题不大。

**Comment by saltylin** [comment]
赞！我们试试

**Comment by waruqi** [comment]
目前 xmake-repo 不是所有包支持交叉编译构建，如果有的包想切换工具链，但还不支持 cross 平台，可以改进 xmake-repo 仓库的包定义配置，增加上 `on_install("cross")` 平台支持就行了，如果源码自身支持，并且是 cmake/autoconf/meson维护的话，基本没啥问题。
