### ISSUE TITLE
How does Xrepo force using xrepo managed packages?

### ISSUE THREAD

**Issue by cyfdecyf** [xmake-io/xmake#2035]
Guess this discussion may be of interest to other Xrepo users. So posting it here in English.

Looking at the output of `xrepo -vD -f "gflags=true,unwind=true,shared=true,mt=true" glog`:

```
checking for xmake::libunwind ... libunwind v1.5
checking for xmake::gflags ... no
checking for pacman ... no
checking for emerge ... no
checking for brew ... no
checking for pkg-config ... /usr/bin/pkg-config
checking for gflags ... no
checking for xmake::glog ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
in builtin-repo:
......
cmake -DBUILD_TESTING=OFF -DGFLAGS_REGISTER_BUILD_DIR=OFF \
    -DGFLAGS_REGISTER_INSTALL_PREFIX=OFF -DCMAKE_BUILD_TYPE=Release
    -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=OFF -DBUILD_gflags_LIB=ON \
    -DBUILD_gflags_nothreads_LIB=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    -DCMAKE_INSTALL_PREFIX=/home/cyf/.xmake/packages/g/gflags/v2.2.2/f8a8ee721d4f43e1bace22f4400cc9bf \
    -DCMAKE_INSTALL_LIBDIR=/home/cyf/.xmake/packages/g/gflags/v2.2.2/f8a8ee721d4f43e1bace22f4400cc9bf/lib \
    -G "Unix Makefiles" -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    /home/cyf/.xmake/cache/packages/2202/g/gflags/v2.2.2/source/gflags-2.2.2
......
-- Looking for gflags namespace
-- Looking for gflags namespace - gflags
......
-- Found Unwind: /home/cyf/.xmake/packages/l/libunwind/v1.5/f1dc8f75081f4455a49e73f90bdc171a/include (found version "1.5.0")
```

Several questions here:

1. Is there any command line option to avoid the use of system installed libraries for dependencies?
    - I accomplish this by adding `system = false` in `glog` xmake.lua:
        ``` 
        if config == "gflags" then
            package:add("deps", "gflags", {system = false})
        ```
    - A command line option would allow us to control this in `xrepo-cmake`
2. When building `glog`, how does Xrepo make `glog` find the `gflags` and `libunwind` managed by Xrepo?
   - I didn't see any thing related in the cmake configure command
   - I've little experience with Lua, tried adding `print` and `print(debug.traceback())` in source code but failed to locate the key point

**Comment by waruqi** [comment]
> Is there any command line option to avoid the use of system installed libraries for dependencies?

you can use `add_requireconfs("glog.gflags", {system = false})` to override configs of it's deps if you use xmake in xmake.lua

Or use the package inherit feature of xmake/dev version, it will make you can rewrite partial configuration in package()

```lua
package("myglog")
    set_base("glog")
    add_deps("gflags", {system = false})
```

> When building glog, how does Xrepo make glog find the gflags and libunwind managed by Xrepo?

There is currently no parameter that can be set to control this behavior. maybe you can try custom package + set_base

**Comment by cyfdecyf** [comment]
Thanks for the quick reply.
 
> > When building glog, how does Xrepo make glog find the gflags and libunwind managed by Xrepo?
> 
> There is currently no parameter that can be set to control this behavior. maybe you can try custom package + set_base

From the install log, we can be sure that it's the xrepo installed `libunwind` being found:

```
-- Found Unwind: /home/cyf/.xmake/packages/l/libunwind/v1.5/f1dc8f75081f4455a49e73f90bdc171a/include (found version "1.5.0")
```

`$HOME/.xmake/packages` is not in cmake package registry, I confirm this by manually running cmake build process for glog and it can't find `libunwind`. So there must be something that Xrepo sets up for `glog` to find `libunwind`. This is what makes me interested.

**Comment by waruqi** [comment]
CMAKE_PREFIX_PATH env will be set

https://github.com/xmake-io/xmake/blob/c80d0c5638f83d7de838a09554daa48800c71fe3/xmake/modules/package/tools/cmake.lua#L542
