### ISSUE TITLE
QML application isn't rebuilt after changing *.qml files

### ISSUE THREAD

**Issue by xaizek** [xmake-io/xmake#2038]
### Describe the bug

`qt.quickapp` set of rules doesn't recognize `*.qml` files for sources (can't even add them) and thus they don't participate in dependency tracking.

### Expected behavior

Changing a `*.qml` file triggers rebuilding of resources, building them and relinking of the application.

### Related Environment

- xmake version: 2.6.3

### Additional context

Working around it by copying and modifying `qt.quickapp` and `qt.qrc` rules to add:
```lua
        for _, file in ipairs(target:get("qmlfiles")) do
            batchcmds:add_depfiles(file)
        end
```
which also requires copying `load.lua` file (the ugliest part).

I think `add_files()` should accept `*.qml` files and add them as dependencies on `*.qrc` file.

**Comment by SirLynix** [comment]
Did you try the dev branch? https://github.com/xmake-io/xmake/pull/2023 should have fixed this.
`xmake update -s dev`

**Comment by xaizek** [comment]
Should have searched among PRs as well. Thanks, looks like it's already addressed.
