### ISSUE TITLE
Support cuda for cmake generator

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2040]
### 你在什么场景下需要该功能？

将cuda项目导出到cmake

### 描述可能的解决方案

参考
https://developer.nvidia.com/blog/building-cuda-applications-cmake/

相比于目前的cmake生成器改动不大，仅增加一个language、增加一些源文件、对每个target加CUDA_SEPARABLE_COMPILATION 和CUDA_RESOLVE_DEVICE_SYMBOLS（控制devlink）即可

**Comment by waruqi** [comment]
等后面排期 或者直接来个 pr

**Comment by waruqi** [comment]
加上了 https://github.com/xmake-io/xmake/commit/85ae6415a9650fe77325a965e76dc0d5984b9430

但是没环境测试，你试试吧，不行可以来个 pr 改下

**Comment by xq114** [comment]
目前实现有几个问题：

1. 带空格路径未加引号，cmake无法识别
```
target_include_directories(main PRIVATE
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.5/include
)
```
2. project()任何时候都启用cuda，cmake在无cuda机器上直接报错

这里要改的话只能先扫一遍所有target再生成project语句吗？有什么便捷的方法判断项目是否启用cuda吗

**Comment by xq114** [comment]
cmake generator还有个问题：指定的RUNTIME_OUTPUT_DIRECTORY就是target:targetdir()，但cmake中一些generator会在此目录附加额外的目录来区分不同config，见

https://cmake.org/cmake/help/latest/prop_tgt/RUNTIME_OUTPUT_DIRECTORY.html

要让输出放到正确的目录，则需要分别指定RUNTIME_OUTPUT_DIRECTORY_DEBUG、RUNTIME_OUTPUT_DIRECTORY_RELEASE等。xmake中如何获取一个target在debug设置和release设置下分别应该输出到哪个目录？

**Comment by waruqi** [comment]
你可以暂时不分 mode，先按当前 mode 来。。如果要分 mode ，这个改动就大了，要参考 vs/vsxmake 那两 generator ，根据 mode 切两边 config ，重新清 cache ，然后取出对应 targetdir 等所有信息才行，比较折腾。

https://github.com/xmake-io/xmake/blob/8f62958d7fd2c602bd8f0f2d304067d08b3de405/xmake/plugins/project/vsxmake/getinfo.lua#L390-L502

**Comment by xq114** [comment]
先这样吧，RUNTIME_OUTPUT_DIRECTORY不对目前影响不大，之后可以再调
