### ISSUE TITLE
增加对 windows arm arm64编译支持

### ISSUE THREAD

**Issue by ranwei1025** [xmake-io/xmake#2042]
如题

**Comment by waruqi** [comment]
没设备环境，暂时不考虑。谁有环境的 可以来个 pr

**Comment by waruqi** [comment]
我支持了 

https://github.com/xmake-io/xmake/pull/2728

```
xmake g -c
xmake f -a arm64
```

**Comment by fxliang** [comment]
似乎还是没有支持MSVC的ARM架构？

**Comment by star-hengxing** [comment]
> 似乎还是没有支持MSVC的ARM架构？

xmake-repo ci 天天跑着呢，如果有其他问题请单独开 issue

**Comment by fxliang** [comment]
这个issue 是要arm 和amr64的支持，目前仓库release只支持到arm64，本来不应该关闭这个issue。所以我在这个未解的issue上提并没有问题。

至于你说的ci天天跑是什么意思，自行下载最新代码自行构建已实现的意思吗？是的话我可以试试看

**Comment by waruqi** [comment]
> 似乎还是没有支持MSVC的ARM架构？

加上了 https://github.com/xmake-io/xmake/pull/5316
