### ISSUE TITLE
CUDA source files are missing depfiles

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2047]
### 描述问题

CUDA源文件中包含的头文件发生变化时，xmake不能检测到并重新编译。

*.cpp.obj.d文件的结构是这样
```
{
    values = {
        [[C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64\cl.exe]],
        {
           ...
        }
    },
    files = {
        [[abc.cpp]]
    },
    depfiles_cl_json = "{\
    \"Version\": \"1.1\",\
    \"Data\": {\
        \"Source\": \"abc.cpp\",\
        \"ProvidedModule\": \"\",\
        \"Includes\": [\
            ...
        ],\
    }\
}"
}
```

*.cu.obj.d文件的结构是这样
```
{
    files = {
        [[abc.cu]]
    },
    values = {
        [[C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\bin\nvcc]],
        {
            ...
        }
    }
}
```

缺失了类似depfiles_cl_json 的部分，或导致了这一bug的发生

### 期待的结果

xmake能正确track到CUDA源文件中引入的头文件

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.6.3
- xmake运行平台：windows
- xmake目标平台：windows

**Comment by waruqi** [comment]
目前只加了对 ccbin(gcc) 的支持，cl 的还没支持

https://github.com/xmake-io/xmake/blob/c62d50f692935b7369869ac72dfb7b99f6e19941/xmake/modules/core/tools/nvcc.lua#L393-L397

我暂时没有 nvcc for cl 的环境，你可以参考 cl.lua 里对 cl deps 的保存，在上面 nvcc.lua 里面也加上试试

https://github.com/xmake-io/xmake/blob/c62d50f692935b7369869ac72dfb7b99f6e19941/xmake/modules/core/tools/cl.lua#L517-L522

**Comment by xq114** [comment]
![image](https://user-images.githubusercontent.com/42310255/153338520-86a0f992-d737-46de-993b-08f1a3416d76.png)

https://github.com/xmake-io/xmake/blob/c62d50f692935b7369869ac72dfb7b99f6e19941/xmake/modules/core/tools/nvcc.lua#L328-L336

这里为什么-MD不能用？windows上-MM和-MMD都无法生效，只有-M和-MD可用；这里直接排除了-M和-MD

**Comment by waruqi** [comment]
> ![image](https://user-images.githubusercontent.com/42310255/153338520-86a0f992-d737-46de-993b-08f1a3416d76.png)
> 
> https://github.com/xmake-io/xmake/blob/c62d50f692935b7369869ac72dfb7b99f6e19941/xmake/modules/core/tools/nvcc.lua#L328-L336
> 
> 这里为什么-MD不能用？windows上-MM和-MMD都无法生效，只有-M和-MD可用；这里直接排除了-M和-MD

我直接从 gcc.lua 里面搬过来的，gcc 支持 `-MMD` ，避免生成大量 system headers ，这样解析和判断依赖变动会更快，提升编译速度

```
  -MD                     Write a depfile containing user and system headers
  -MMD                    Write a depfile containing user headers
 ```
