### ISSUE TITLE
allow to find a certain version of cuda sdk

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2053]
### 你在什么场景下需要该功能？

同一机器上安装有不同版本的cuda时，希望能选择使用哪一个cuda，类似vs可选择--vs=2019或--vs=2022

### 描述可能的解决方案

xmake f --cuda=11.4 仅选择版本为11.4的cuda sdk，不选中其他，如果找不到则报错

### 描述你认为的候选方案

xmake f "--cuda_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5" 声明完整版的cuda path，不选中其他，如果找不到则报错

**Comment by waruqi** [comment]
> xmake f "--cuda_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5" 声明完整版的cuda path，不选中其他，如果找不到则报错

不是有 `xmake f --cuda=/xxx/sdk` 么

**Comment by xq114** [comment]
> > xmake f "--cuda_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5" 声明完整版的cuda path，不选中其他，如果找不到则报错
> 
> 不是有 `xmake f --cuda=/xxx/sdk` 么

这个不支持简单版的版本声明（11.5这样），而且目前有一些bug，1. cuda的nvcc路径和add_requires("cuda", {...})获取的cuda library目录有时会不一样，导致编译命令中用11.1的nvcc链接11.6的库；2. --cuda=/xxx/sdk声明了之后如果目录不存在，会fallback到其他sdk上，而不会报错

**Comment by waruqi** [comment]
那只需要改进下 find_cuda.lua 就好了，你可以调下 https://github.com/xmake-io/xmake/blob/master/xmake/modules/detect/sdks/find_cuda.lua
