### ISSUE TITLE
add msvc-20xx toolchain

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2054]
### 你在什么场景下需要该功能？

在xrepo env shell时要激活msvc环境目前只能通过
```
set_toolchains("msvc")
```
但这样设置只能激活最新msvc环境（vs2022），无法激活vs2019环境。cuda目前官方还不支持vs2022，调试时需要用到vs2019环境，xmake现无法激活

### 描述可能的解决方案

添加set_toolchains("msvc-2019")，类似clang-12、gcc-11等，以便选择激活环境时的目标

**Comment by waruqi** [comment]
```lua
set_toolchains("msvc", {vs = "2019"})
```

**Comment by xq114** [comment]
> ```lua
> set_toolchains("msvc", {vs = "2019"})
> ```

没用，还是加载的vs2022
```
xrepo env -b base shell
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft Visual Studio (x64) version ... 2022
```

**Comment by xq114** [comment]
这里设置了vs="2019"在没装vs2019的机器上也不报错，而是直接切到vs2022了，这里无法满足要求的附加条件时还是加一个提示吧？
