### ISSUE TITLE
target program not found

### ISSUE THREAD

**Issue by wangzhankun** [xmake-io/xmake#2065]
我在桌面上使用xmake命令创建了一个工程。debug正常运行。开发两天后将工程移动到了其他目录，在vscode下使用debug按钮启动debug时提示，target program not found。我删除了build、.vscode、.xmake目录重新进行编译，也执行了`xmake c`，但是仍然提示错误。

**Comment by wangzhankun** [comment]
我发现了问题所在。当把工程转为vs之后，使用visual studio调试时，会弹出有个dll文件找不到。把dll文件复制到执行文件路径即可。请问xmake执行程序时为啥会看不到类似的提示呢？使用`xmake r`执行时会有如下报错：
`error: execv(E:\aboutme\研究生\科研活动\测绘项目\openssl_gm_client\build\windows\x86\release\openssl_gm_client.exe) failed(-1073741515)`
但是visual studio会有弹窗报错提示dll找不到。请问我该如何设置呢？

**Comment by waruqi** [comment]
> debug时提示，target program not found。

跟 dll 没关系，切到 vscode，需要点底部 build 按钮先编译一次，即使之前命令行编译过

>\openssl_gm_client\build\windows\x86\release\openssl_gm_client.exe) failed(-1073741515)
但是visual studio会有弹窗报错提示dll找不到。请问我该如何设置呢？

不知道，反正命令行该有的错误，vscode的终端输出也都会有，没有本质区别
