### ISSUE TITLE
避免将 gcc 默认 include path 加入编译选项

### ISSUE THREAD

**Issue by cyfdecyf** [xmake-io/xmake#2067]
### 描述问题

在 ArchWsl 上执行 `xrepo install -f unwind=true glog`，`on_test` 执行期遇到错误，如果没有加上 `-f unwind=true` 则不会遇到以上错误。

已经定位到原因：测试代码的编译命令中多了 `-isystem /usr/include`，因为系统上用 pacman 安装了 libunwind (这是 strace 命令的依赖)，因此编译依赖中加入了系统目录。

关键错误信息如下：

```
error: ...ake/repositories/my-xmake-repo/packages/g/glog/xmake.lua:43: ...amdir/core/sandbox/modules/import/core/tool/compiler.lua:84: @programdir/modules/core/tools/gcc.lua:503: In file included from /usr/include/c++/11.2.0/ext/string_conversions.h:41,
                 from /usr/include/c++/11.2.0/bits/basic_string.h:6607,
                 from /usr/include/c++/11.2.0/string:55,
                 from /usr/include/c++/11.2.0/bits/locale_classes.h:40,
                 from /usr/include/c++/11.2.0/bits/ios_base.h:41,
                 from /usr/include/c++/11.2.0/ios:42,
                 from /usr/include/c++/11.2.0/ostream:38,
                 from /home/cyf/.xmake/packages/g/glog/v0.5.0/3958b855fc6d4ea7a2c7b93502baf38a/include/glog/logging.h:44,
                 from /dev/shm/.xmake1000/220218/_AED3C641250846308E67435364DD7930.cpp:2:
/usr/include/c++/11.2.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
   75 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
compilation terminated.
```

### 期待的结果

`xrepo install glog` 增加 `-f unwind=true` 不应该导致出错。

### 错误信息

参考这个 [gcc bug report](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129)，指定 `-isystem /usr/include` 导致的头文件寻找错误是已知问题，且看来不会被修复。

可以用以下命令进行测试：

```
echo "#include<cstdlib>" | g++ -x c++ -isystem /usr/include -
```

以下是我测试过的编译器版本：

- g++-4.8, g++-5.5 不会有头文件查找错误
- g++-7.5, g++-9.4, g++-11.2, clang-13, `-isystem /usr/include` 会导致头文件查找错误。

### 相关环境

- xmake版本：dev 分支最新代码
- xmake运行平台：ArchWsl
- xmake目标平台：x86_64

### 其他信息

目前的 work around，通过 lua 脚本来指定依赖，避免引入系统库。lua 脚本如下：

```
# pkg.lua
add_requires("glog", {system = false, configs = {unwind = true, gflags = true}})
add_requireconfs("glog.libunwind", {system = false})
```

执行 `xrepo install ./pkg.lua` 即可正常安装。

尝试看了下 xmake 的代码，我只能想到在文件 `xmake/core/tool/builder.lua` 函数 `builder:_add_flags_from_language` 中对此类路径进行过滤。但这总是会出问题的 work around，就不发 PR 了。

接下来打算在 xrepo-cmake 中加入对 `xrepo install pkg.lua` 这种用法的支持，所以这个问题并不急着解决。祝周末愉快 @waruqi

**Comment by waruqi** [comment]
我这 arch 上没法复现，能够正常安装，并且没有额外的 /usr/include 。。你执行下面的两个命令看看呢。

```console
[ruki@b386cacd379f xmake-repo]$ xmake l find_package pacman::libunwind
{ 
  linkdirs = { },
  links = { 
    "unwind-coredump",
    "unwind-ptrace",
    "unwind-generic",
    "unwind-setjmp",
    "unwind" 
  },
  includedirs = { } 
}
[ruki@b386cacd379f xmake-repo]$ xmake l find_package libunwind
{ 
  linkdirs = { 
    "/usr/lib" 
  },
  links = { 
    "unwind" 
  } 
}
```

**Comment by cyfdecyf** [comment]
抱歉周末没有 ArchWsl 环境，所以现在才回复。

先提一下我的 xmake 安装方式，确认下安装命令是否有问题：

```bash
make -j
./scripts/get.sh __local__ __install_only__
```

为方便调试，会通过软链使用源码目录下的 xmake 目录替换安装目录下的 xmake：

```bash
cd ~/.local/share
rm -rf xmake
ln -s ${xmake_git_repo_xmake} .
```

以下命令结果是否使用 xmake 目录软链都没有差异。

获取最新代码编译安装后执行以上命令的结果：

```bash
07:35 ~> xmake l find_package pacman::libunwind
{
  linkdirs = {
    "/usr/lib"
  },
  includedirs = {
    "/usr/include"
  },
  links = {
    "unwind-coredump",
    "unwind-generic",
    "unwind-ptrace",
    "unwind-setjmp",
    "unwind-x86_64",
    "unwind"
  }
}

07:35 ~> xmake l find_package libunwind
{
  includedirs = {
    "/usr/include"
  },
  links = {
    "unwind-coredump",
    "unwind-generic",
    "unwind-ptrace",
    "unwind-setjmp",
    "unwind-x86_64",
    "unwind"
  },
  linkdirs = {
    "/usr/lib"
  }
}
```

附带 pacman 查询结果，版本为目前最新版 1.6.2，与 xmake-repo 中不同。（xmake-repo 中的 libunwind 我正在添加新版本，依赖 lzma 和 zlib 作为 configs 还需要做测试）：

```bash
07:37 ~> pacman -Qi libunwind
Name            : libunwind
Version         : 1.6.2-1
Description     : Portable and efficient C programming interface (API) to determine the call-chain of a program
Architecture    : x86_64
URL             : https://www.nongnu.org/libunwind/
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : xz  zlib
Optional Deps   : None
Required By     : strace
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 261.51 KiB
Packager        : Antonio Rojas <arojas@archlinux.org>
Build Date      : Fri 24 Dec 2021 05:57:38 AM CST
Install Date    : Fri 18 Feb 2022 05:42:03 PM CST
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

**Comment by waruqi** [comment]
我没有 archwsl 环境，只有 arch linux 环境，这边测试是可以的。

目前对 pacman 的查找有两步，先走 pacman -Ql libunwind 获取完整 file list ，从里面提取 includedirs ，这个时候是带 /usr/include的，这是肯定的，也没法改。

但是，如果 file list 里面有 .pc 文件，会进一步优先用 pkg-config 去提取 includedirs 进行改进，而 pkg-config 会对 /usr/include 做自动剔除，所以我这是没问题的。

```console
$ pkg-config --cflags --libs libunwind
-lunwind 
```

你可以先确认下 pkg-config 是否安装，如果没有，安装下试试。

这个其实是 gcc 的问题，我这边内部是无法直接硬编码剔除相关路径的，因为 find_package 阶段是不知道用的什么编译器，什么版本，直接从返回结果中剔除，干扰太大，有可能其他非 gcc 编译器就需要 /usr/include 路径。

而后期编译阶段，还要去判断编译器，硬编码修 gcc 的问题，更不太好改。

**Comment by waruqi** [comment]
> 为方便调试，会通过软链使用源码目录下的 xmake 目录替换安装目录下的 xmake：

另外，调试源码脚本只需要，`export XMAKE_PROGRAM_DIR=/xmakesource/xmake` 动态切下就好了，没必要用软连。

另外，还有 `source ./scripts/srcenv.profile` 也可以直接用，bore binary 也会自动切到本地编译版本，方便调试

**Comment by cyfdecyf** [comment]
谢谢快速反馈！

抱歉，的确是因为环境里没有安装 pkgconfig 导致的。

最近刚刚切换到 ArchWsl 2，编译环境 setup 时遗漏了 pkgconfig。
