### ISSUE TITLE
Qt build fail

### ISSUE THREAD

**Issue by soloIife** [xmake-io/xmake#2071]
xmake -w
[ 28%]: compiling.qt.moc src\mainwindow.h
error: moc_mainwindow.cpp
D:\Qt\6.2.2\msvc2019_64\include\QtCore/qglobal.h(94): fatal error C1189: #error:  "Qt requires a C++17 compiler, and a suitable value for __cplusplus. On MSVC, you must pass the /Zc:__cplusplus option to the compiler."

**Comment by SirLynix** [comment]
How about adding the flag? `add_cxflags("/Zc:__cplusplus")`

**Comment by waruqi** [comment]
> How about adding the flag? `add_cxflags("/Zc:__cplusplus")`

@soloIife You can try it first. If it works, we can add it to here.

https://github.com/xmake-io/xmake/blob/6654a889d2403e8cb940d3b6bd9ad54de17bfece/xmake/rules/qt/load.lua#L137-L138

But I'm not sure yet, the qt version range that needs this flag. >= 6.0?

**Comment by soloIife** [comment]
add_cxflags("/Zc:__cplusplus")  
or 
if qt_sdkver:ge("6.0") then 
         target:add("languages", "c++17") 
can fix it.

**Comment by waruqi** [comment]
> `add_cxflags("/Zc:__cplusplus") ` or
> 
> ```
> if qt_sdkver:ge("6.0") then 
>          target:add("languages", "c++17") 
> ```
> 
> can fix it.

why? xmake has added `c++17` for 6.0

**Comment by soloIife** [comment]
I don't know，I was just following  `xmake create -t qt.widgetapp test` to create project. And then that error happened.

**Comment by SirLynix** [comment]
Maybe xmake project templates for Qt sould include 
```lua
set_languages("cxx17")
if is_plat("windows") then
    add_cxflags("/Zc:__cplusplus")
end
```

**Comment by waruqi** [comment]
I added it. https://github.com/xmake-io/xmake/commit/2cecbbcd65702ca2da16b0ddf3785ce9b355c0b6
