### ISSUE TITLE
xmake 生成的vstudio工程，支持 cuda 

### ISSUE THREAD

**Issue by soloist-v** [xmake-io/xmake#2077]
我的项目中使用了cuda 和 Qt
我使用xmake能够正确编译结果，但是我使用命令`xmake project -k vs -m "debug,release"`将项目导出未vs工程后，出现了一些问题
##### auto_strike.vcxproj.filters 文件中：
```
<ClCompile Include="$(XmakeProjectDir)\D:\CppInclude\print\my_print.cpp">
    <Filter>D:\CppInclude\print</Filter>
</ClCompile>
<ClCompile Include="$(XmakeProjectDir)\D:\CppInclude\tensorRT_Pro\src\tensorRT\common\cuda_tools.cpp">
    <Filter>D:\CppInclude\tensorRT_Pro\src\tensorRT\common</Filter>
</ClCompile>
```

**Comment by waruqi** [comment]
赞不支持，用 xmake project -k vsxmake

**Comment by xq114** [comment]
这个可以先作为feature request备着，vs生成器要支持cuda并不一定非要custom command，用安装cuda toolkit同时安装的vs integration（CUDA 11.x.props）也可以做到，只是把`<ClCompile>`换成`<CudaCompile>`而已，vsxmake就是这么实现的 @waruqi 

vsxmake支持绝对路径也是应该的，这里要改 https://github.com/xmake-io/xmake/blob/master/xmake/plugins/project/vsxmake/vsproj/templates/vcxproj.filters/File.c(filec)

**Comment by xq114** [comment]
已修复这些问题，xmake update -s dev再试试

**Comment by soloist-v** [comment]
ok
