### ISSUE TITLE
多线程(/MT)改为多线程 DLL (/MD) 

### ISSUE THREAD

**Issue by wangzhankun** [xmake-io/xmake#2078]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 问题
调试程序遇到一堆error LNK2001与error LNK2019 bug，最后将问题解决，现将解决办法记录下来以便后续查看。
1>libcpmtd.lib(locale.obj) : error LNK2001: 无法解析的外部符号 _CrtDbgReportW
1>libcpmtd.lib(wlocale.obj) : error LNK2001: 无法解析的外部符号 _CrtDbgReportW
1>libcpmtd.lib(xlocale.obj) : error LNK2001: 无法解析的外部符号 _CrtDbgReportW
1>C_Python.obj : error LNK2001: 无法解析的外部符号 _CrtDbgReportW
1>libcpmtd.lib(stdthrow.obj) : error LNK2001: 无法解析的外部符号 _CrtDbgReportW
1>libcpmtd.lib(syserror.obj) : error LNK2001: 无法解析的外部符号 _CrtDbgReportW
1>libcpmtd.lib(cout.obj) : error LNK2001: 无法解析的外部符号 _CrtDbgReportW
1>libcpmtd.lib(_tolower.obj) : error LNK2019: 无法解析的外部符号 _wcsdup_dbg，

我找到的解决办法：项目–>属性–>C/C++ –>代码生成–>运行库 中多线程(/MT)改为多线程 DLL (/MD)。请问我该如何在xmake.lua中进行这种设置呢？

**Comment by xq114** [comment]
set_runtimes("MD")

见 https://xmake.io/#/manual/global_interfaces?id=set-vs-runtime
