### ISSUE TITLE
生成VisualStudio工程 语言版本未设置

### ISSUE THREAD

**Issue by UUZZzga** [xmake-io/xmake#2079]
我一直这样使用`set_languages("c++20")`
生成VisualStudio工程，出现语言版本未设置都是手动设置，
直到我使用`set_languages("cxx20")`，他设置上了

经调查
https://github.com/xmake-io/xmake/blob/a4aa0f5d1a9f16fe86200cea9798417fee4f36e7/xmake/plugins/project/vstudio/impl/vs201x_vcxproj.lua#L581-L595
是这样操作的
https://github.com/xmake-io/xmake/blob/a4aa0f5d1a9f16fe86200cea9798417fee4f36e7/xmake/plugins/project/vstudio/impl/vs201x_vcxproj.lua#L599-L600
并没有像这样处理
https://github.com/xmake-io/xmake/blob/a4aa0f5d1a9f16fe86200cea9798417fee4f36e7/xmake/modules/core/tools/cl.lua#L230-L232

**Comment by waruqi** [comment]
修复了，xmake update dev
