### ISSUE TITLE
xrepo install pkg.lua 等待用户输入时没有输出提示

### ISSUE THREAD

**Issue by cyfdecyf** [xmake-io/xmake#2084]
### 描述问题

pkg.lua 内容如下：

```lua
add_requires("libunwind", {system = false, configs = {minidebuginfo = true, zlibdebuginfo = true}})
add_requireconfs("libunwind.*", {system = false})
```

执行 `xrepo install pkg.lua` 时没有输出，执行 `xrepo install -v pkg.lua` 才能看到 xrepo 在等待用户输入

```
note: install or modify (m) these packages (pass -y to skip confirm)?
in my-xmake-repo:
  -> lzma 19.00 [from:libunwind]
  -> zlib v1.2.11 [from:libunwind]
  -> libunwind v1.6.2 [zlibdebuginfo:y, minidebuginfo:y]
please input: y (y/n/m)
```

### 期待的结果

`xrepo install pkg.lua` 能输出信息提示用户输入。

### 相关环境

- xmake版本：dev branch commit 465fee4cb
- xmake运行平台：ArchWsl2
- xmake目标平台：x86_64

**Comment by waruqi** [comment]
再试试

**Comment by cyfdecyf** [comment]
在 Ubuntu 18.04 下试了下情况一样。

**Comment by waruqi** [comment]
更新到dev 再试

**Comment by cyfdecyf** [comment]
不确定是不是我哪里弄错了，但我提交 issue 时是在 dev 分支的 465fee4cb commit 上，之后的 commit 是我 fix typo 的 PR。

**Comment by waruqi** [comment]
> 不确定是不是我哪里弄错了，但我提交 issue 时是在 dev 分支的 [465fee4](https://github.com/xmake-io/xmake/commit/465fee4cbf4b72419c8a717e05a4879e79ac772e) commit 上，之后的 commit 是我 fix typo 的 PR。

哦，被你那个 commit 后，我这 push 失败了，需要 rebase 下，现在应该可以了，再试试

**Comment by cyfdecyf** [comment]
83b50994a 已经修复这个问题，谢谢~
