### ISSUE TITLE
xrepo install --mode=debug 与 -f debug=true 的差别

### ISSUE THREAD

**Issue by cyfdecyf** [xmake-io/xmake#2108]
### 描述讨论详情

```console
xrepo install --mode=debug gflags
note: install or modify (m) these packages (pass -y to skip confirm)?
in my-xmake-repo:
  -> gflags v2.2.2 [debug:y]
please input: y (y/n/m)
y
  => install gflags v2.2.2 .. ok
```

`xrepo install --mode=debug` 安装包时会带上 `-f debug=true`。

另外在 xmake-repo 中编写 xmake.lua 时，我们仅检查 `package:config("debug")` 来决定 cmake 的 build type。

指定 `--mode=debug` 跟 `-f debug=true` 是否有其他差别？

**Comment by waruqi** [comment]
> 指定 --mode=debug 跟 -f debug=true 是否有其他差别？

没区别，-m debug, -k shared 这种配置切换比较常用 所以加了几个快捷的参数直接切换，内部就是走的 configs

**Comment by cyfdecyf** [comment]
谢谢回答。

我在用 xrepo-cmake 时想到了这个问题。之后 xrepo-cmake 发 PR 的时候我在加个关于 `MODE debug` 跟 `CONFIGS debug=true` 等价的说明。
