### ISSUE TITLE
update compile_commands generation to be compatible with C++20 modules (bug?)

### ISSUE THREAD

**Issue by metasprite** [xmake-io/xmake#2114]
### Is your feature request related to a problem? Please describe.
The `compile_commands.json` generated by xmake doesn't help language servers like `clangd` find C++20 module files. My project with C++20 modules compiles fine, but `clangd` can't find imported modules, so it complains.

### Describe the solution you'd like
Extend `compile_commands.json` generation to tell the compiler where modules can be found.
For `clang` on linux, adding `-fprebuilt-module-path=build/.gens/test/linux/x86_64/release/rules/modules/cache` to the `compile_commands.json` generated by xmake works. `clangd` behaves as expected after doing this.

I see how this is implemented in `build_modules/clang.lua`:
```lua
target:add("cxxflags", "-fimplicit-modules", "-fimplicit-module-maps", "-fprebuilt-module-path=" .. cachedir, {force = true})
```
I'm just not sure how to make the `compile_commands.json` generation code use this...

### Describe alternatives you've considered
I wasn't sure whether this was a bug report or feature request, so I don't see another way to fix this problem.

**Comment by waruqi** [comment]
not supported yet, see https://github.com/xmake-io/xmake/issues/1167

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/issues/1167#issuecomment-1215200148

**Comment by waruqi** [comment]
but vscode and other some ide maybe still not support compile_commands.json with c++modules.

https://github.com/microsoft/vscode-cpptools/issues/6302#issuecomment-1215554637

**Comment by waruqi** [comment]
I have merged it now.
