### ISSUE TITLE
指定CUDA toolkit后，无法正确获取cu编译器(nvcc)

### ISSUE THREAD

**Issue by ltmit** [xmake-io/xmake#2134]
### Xmake 版本

2.6.4

### 操作系统版本和架构

WSL Ubuntu18.04 

### 描述问题

采用xmake f --cuda=/usr/local/cuda-11.3 后，识别CUDA toolkit目录成功。但是编译工程失败，提示找不到cu文件的编译器：
![image](https://user-images.githubusercontent.com/53287548/157171856-76cd03f6-6905-4e5c-b691-fa2b0c0f43b9.png)
经过确认，toolkit目录下有正确的编译器位置$(CUDA_ROOT)/bin/nvcc，且能正常执行。但是未设置环境变量。
--------------------------------------------------------
补充：如果设置了环境变量，让PATH包含对应的nvcc，则可以正确执行编译，但这不是我们想要的。因为系统内可能存在多套CUDA toolkit，如果我需要再切换其他toolkit版本，不能每次都重设环境变量，而应该通过xmake自身管理功能实现。

### 期待的结果

通过 xmake f --cuda=/usr/local/cuda-11.3 指定特定的CUDA toolkit后，xmake应该能够正确获取相关环境参数（包括编译器nvcc，对应的include和lib，等）。能够正确的编译工程。

### 附加信息和错误日志

(base) root@ltmit-TB16P:~/workspace/sape-srv-v2# xmake  -D -v
checking for the cuda compiler (cu: nvcc) ... no
checking for the cuda compiler (cu: clang) ... no
error: @programdir/core/main.lua:280: @programdir/actions/build/main.lua:155: ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:96: ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:56: @programdir/modules/private/async/runjobs.lua:232: ...amdir/core/sandbox/modules/import/core/tool/compiler.lua:37: cannot get program for cu
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:849]:
    [...amdir/core/sandbox/modules/import/core/tool/compiler.lua:37]: in function 'load'
    [@programdir/modules/private/action/build/object.lua:39]: in function 'script'
    [@programdir/modules/private/action/build/object.lua:91]: in function 'build_object'
    [@programdir/modules/private/action/build/object.lua:116]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:208]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:849: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir/modules/private/async/runjobs.lua:232: in field 'catch'
        @programdir/core/sandbox/modules/try.lua:127: in global 'try'
        @programdir/modules/private/async/runjobs.lua:200: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:371: in function <@programdir/core/base/scheduler.lua:368>
stack traceback:
        @programdir/core/base/utils.lua:290: in function <@programdir/core/base/utils.lua:280>
        [C]: in function 'error'
        @programdir/core/base/os.lua:849: in function 'base/os.raiselevel'
        (...tail calls...)
        ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:56: in field 'co_start_withopt'
        @programdir/modules/private/async/runjobs.lua:199: in function <@programdir/modules/private/async/runjobs.lua:159>
        [C]: in function 'xpcall'
        @programdir/core/base/utils.lua:280: in function 'base/utils.trycall'
        @programdir/core/base/scheduler.lua:487: in function 'base/scheduler.co_group_begin'
        ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:94: in field 'co_group_begin'
        @programdir/modules/private/async/runjobs.lua:159: in function <@programdir/modules/private/async/runjobs.lua:54>
        (...tail calls...)
        @programdir/actions/build/build.lua:244: in function <@programdir/actions/build/build.lua:238>
        (...tail calls...)
        @programdir/actions/build/main.lua:101: in global '_do_build'
        @programdir/actions/build/main.lua:143: in function <@programdir/actions/build/main.lua:137>
        [C]: in function 'xpcall'
        @programdir/core/base/utils.lua:280: in function 'base/utils.trycall'
        @programdir/core/sandbox/modules/try.lua:121: in global 'try'
        @programdir/actions/build/main.lua:135: in function <@programdir/actions/build/main.lua:106>
        (...tail calls...)
        [C]: in function 'xpcall'
        @programdir/core/base/utils.lua:280: in function 'base/utils.trycall'
        (...tail calls...)
        @programdir/core/base/task.lua:519: in function 'base/task.run'
        @programdir/core/main.lua:278: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:371: in function <@programdir/core/base/scheduler.lua:368>
stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:849: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir/core/main.lua:280: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:371: in function <@programdir/core/base/scheduler.lua:368>

**Comment by waruqi** [comment]
用 `xmake f --sdk=/usr/local/cuda-11.3` 试试

**Comment by waruqi** [comment]
再更新到 dev 试试呢，xmake update -s dev

**Comment by xq114** [comment]
可以试试`xmake f --cuda=11.3`，效果应该是一样的

**Comment by ltmit** [comment]
dev版本可以了。
试了xmake f --cuda=11.3 效果的确和打全路径一样。但必须是dev版才能正确编译。
