### ISSUE TITLE
A "template" package kind

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#2138]
### Is your feature request related to a problem? Please describe.

I'm trying to improve packages qt5core, qt5gui and qt5widgets by having a common package base (qt5lib) to reduce how many lines are required to add a Qt package, but that common base cannot be used in a project directly (and shouldn't be processed by xmake-package CI or xmake-mirror/build-artifacts)

### Describe the solution you'd like

Now that we have package inheritance (https://github.com/xmake-io/xmake/issues/2011), it would be nice to have a "template" package kind, that can't be directly used in a project but can serve as a base for real packages.

```lua
package("qt5lib")
    set_kind("template")

... -- some generic code

package("qt5core")
    set_base("qt5lib")
    set_kind("library")
... -- customisation of variables in on_load
package_end()

add_requires("qt5lib") -- forbidden, this is a template package
add_requires("qt5core") -- allowed

target("example")
    add_packages("qt5lib") -- forbidden, this is a template package
    add_packages("qt5core") -- allowed
```

### Describe alternatives you've considered

Adding an error in the package on_load if its directly included, however this will make xmake-repo and xmake-mirror CI fail

**Comment by waruqi** [comment]
I have supported it
