### ISSUE TITLE
Windows ARM Support?

### ISSUE THREAD

**Issue by chachako** [xmake-io/xmake#2140]
### Is your feature request related to a problem? Please describe.

我正在编写可能会在 Windows ARM 平台上运行的 Rust & C++ 程序，输入 `xmake f -h` 命令发现 windows 只有 x86 和 x64 的架构支持，我看到 Rust 貌似已经支持了 https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-2-with-host-tools

### Describe the solution you'd like

是否会支持/已经支持?

### Additional context

![image](https://user-images.githubusercontent.com/58068445/157490512-5969126f-1aa9-441b-bc6d-20bc0c90d33d.png)

**Comment by waruqi** [comment]
之前有人提过这个了 https://github.com/xmake-io/xmake/issues/2042

我也很想支持，但是我没 windows arm 环境，用 qemu 捣鼓又太折腾，而且我本机也没磁盘空间去安装其他系统了

谁有环境，可以直接拉代码帮忙加上支持后提个pr过来

**Comment by xiaomi2077** [comment]
linux arm呢，有考虑吗，大佬

**Comment by waruqi** [comment]
> linux arm呢，有考虑吗，大佬

原本就支持，还要考虑什么？

**Comment by xiaomi2077** [comment]
我是aarch64的板子，原来想t通过添加源安装，但是添加源了，没有搜到xmake。以为不支持。不过现在通过脚本安装上了
![截屏-20220609191803-499x306](https://user-images.githubusercontent.com/33375652/172835267-df21b1dd-e1d0-43e7-91a8-d8c0874e4418.png)

**Comment by Winterreisender** [comment]
在x64平台下安装的Visual Studio自带了一个编译到ARM64的编译器,`C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\arm64\cl.exe`

对于简单的程序,直接将cl.exe的路径换一下就可以正常编译,其他的都不需要动,有没有别的方法间接实现arm64支持?比如设置`--sdk`之类的(试过没成功)

**Comment by waruqi** [comment]
理论上直接 xmake f -a arm64 就行了，但是我没arm64环境，暂时测不了，也许要做一些改动才能支持。你们有环境的 可以自己研究下 提个pr过来

**Comment by Winterreisender** [comment]
> 在x64平台下安装的Visual Studio自带了一个编译到ARM64的编译器,`C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\arm64\cl.exe`
> 
> 对于简单的程序,直接将cl.exe的路径换一下就可以正常编译,其他的都不需要动,有没有别的方法间接实现arm64支持?比如设置`--sdk`之类的(试过没成功)


我找到了一种方法间接在x64平台上编译ARM64

```shell
xmake f
  -p windows 
  -a arm64
  --sdk="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\" 
  --cc="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\arm64\cl.exe" 
  --cxx="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\arm64\cl.exe" 
  --includedirs="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include;C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared;C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\winrt" 
  --linkdirs="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\lib\arm64\;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\arm64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\ucrt\arm64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\winrt\arm64" 
  --ld="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\arm64\link.exe" 
  --sh="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\arm64\link.exe" 
  --ar="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\arm64\lib.exe" 
&& xmake
```

**Comment by waruqi** [comment]
只需要 xmake f -a arm64，不需要设置其他任何参数

**Comment by Winterreisender** [comment]
> 只需要 xmake f -a arm64，不需要设置其他任何参数

抱歉,已经改正了

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/pull/2728

我支持了 xmake f -a arm64
