### ISSUE TITLE
Automatically running build task on modified files

### ISSUE THREAD

**Issue by masrur10rahman** [xmake-io/xmake#2141]
### Is your feature request related to a problem? Please describe.

Whenever I modify a file, I usually need to run `xmake` and then `xmake r` to run a target. It gets a bit irritating when you have to type nearly the same command to build and run but twice each time you make a modification.

### Describe the solution you'd like

I would like to have `xmake build` automatically executed before any other task if a file has been modified like `make` does with it's recipes.

For example, if I had modified a file and I execute `xmake r`, it should first build the target and then run it without having to write two separate commands.

**Comment by waruqi** [comment]
you can call `os.exec("xmake build")` in before_run

```lua
target("test")
    before_run(function(target)
        os.exec("xmake build")
    end)
```
