### ISSUE TITLE
unknown source file: xxx.h

### ISSUE THREAD

**Issue by RinOrz** [xmake-io/xmake#2142]
### Xmake 版本

v2.6.4+202203070649

### 操作系统版本和架构

macOS 12.21  x86_64

### 描述问题

出于一些原因我正在移植一个c++库，它貌似需要头文件作为源文件编译：
https://github.com/facebook/redex/blob/main/CMakeLists.txt#L69

一开始，我尝试了在 xmake 配置的 `add_files` 中删除掉这些头文件...但是运行失败。因此我感觉是没有编译头文件的问题（没有发现输出的 `.o` 文件），然后就将头文件包含在 `add_files` 中，但是如标题一样报错了，我应该如何将这些头文件发给 xmake 编译？

### 期待的结果

允许将头文件作为源文件编译

### 工程配置

```lua
add_requires("zlib-ng", "jsoncpp")
-- Add optional boosts libraries,
--   because in android targets we'll use prebuilt replacement for them
add_requires("boost", {
    optional = true,
    configs = {
        regex = true,
        system = true,
        thread = true,
        iostreams = true,
        program_options = true
    }
 })

-- Enable built-in optimizations for different modes
--   https://xmake.io/#/manual/custom_rule?id=built-in-rules
add_rules("mode.debug", "mode.release")

set_kind("static")
set_languages("gnuxx17")
set_targetdir("../prebuilt/redex/$(plat)/$(arch)")

target("redex")
    add_ldflags("-static-libgcc", "-static-libstdc++", {force = true})
    add_packages("boost", "zlib-ng", "jsoncpp")
    add_includedirs(
        "analysis",
        "libredex",
        "liblocator",
        "libresource",
        "opt/regalloc",
        "opt/regalloc-fast",
        "service/regalloc",
        "service/regalloc-fast",
        "service/dataflow",
        "util",
        "shared",
        "sparta/include",
        "wrapper"
    )
    add_files(
        "analysis/max-depth/*.cpp",
        "analysis/ip-reflection-analysis/*.cpp",
        "libredex/*.cpp",
        "libresource/*.cpp",
        "opt/regalloc/*.cpp",
        "opt/regalloc-fast/*.cpp",
        "service/regalloc/*.cpp",
        "service/regalloc-fast/*.cpp",
        "service/dataflow/*.cpp",
        "util/CommandProfiling.cpp",
        "util/JemallocUtil.cpp",
        "util/Sha1.cpp",
        "shared/DexDefs.cpp",
        "shared/DexEncoding.cpp",
        "shared/file-utils.cpp",
        "liblocator/locator.cpp",
        "wrapper/*.cpp"
    )
    if is_plat("android") then
        add_defines("ANDROID_STL=c++_shared")
        -- Setup boost libraries in android targets
        add_links(
            "boost_regex",
            "boost_system",
            "boost_thread",
            "boost_iostreams",
            "boost_filesystem",
            "boost_program_options"
        )
        add_includedirs("../prebuilt/boost-android/include")
        add_linkdirs("../prebuilt/boost-android/$(arch)/lib")
    end
```

### 附加信息和错误日志

> checking for Xcode directory ... /Applications/Xcode.app
> checking for Codesign Identity of Xcode ... no
> checking for SDK version of Xcode for macosx (x86_64) ... 12.1
> checking for Minimal target version of Xcode for macosx (x86_64) ... 12.2
> checkinfo: cannot runv(dmd --version), No such file or directory
> checking for dmd ... no
> checkinfo: cannot runv(ldc2 --version), No such file or directory
> checking for ldc2 ... no
> checking for gdc ... /usr/local/bin/gdc
> checkinfo: cannot runv(zig version), No such file or directory
> checking for zig ... no
> checkinfo: cannot runv(zig version), No such file or directory
> checking for zig ... no
> checking for unzip ... /usr/bin/unzip
> checking for git ... /usr/bin/git
> checking for gzip ... /usr/bin/gzip
> checking for tar ... /usr/bin/tar
> /usr/bin/git rev-parse HEAD
> checking for cmake ... /usr/local/bin/cmake
> checking for cmake ... /usr/local/bin/cmake
> finding zlib-ng from xmake ..
> checking for xmake::zlib-ng ... zlib-ng 2.0.5
> finding jsoncpp from xmake ..
> checking for xmake::jsoncpp ... jsoncpp 1.9.5
> finding boost from xmake ..
> checking for xmake::boost ... no
> finding boost from brew ..
> checking for brew ... /usr/local/bin/brew
> finding boost from system ..
> checking for brew::boost ... boost 
> checking for xcrun -sdk macosx clang ... /usr/bin/xcrun -sdk macosx clang
> checking for the c++ compiler (cxx) ... xcrun -sdk macosx clang
> checking for the c++ compiler (cxx) ... xcrun -sdk macosx clang
> checking for the c++ compiler (cxx) ... xcrun -sdk macosx clang
> checking for the c++ compiler (cxx) ... xcrun -sdk macosx clang
> checking for the c++ compiler (cxx) ... xcrun -sdk macosx clang
> checking for the c++ compiler (cxx) ... xcrun -sdk macosx clang
> checking for the c++ compiler (cxx) ... xcrun -sdk macosx clang
> checking for the c++ compiler (cxx) ... xcrun -sdk macosx clang
> checking for the c++ compiler (cxx) ... xcrun -sdk macosx clang
> checking for the c++ compiler (cxx) ... xcrun -sdk macosx clang
> checking for the c++ compiler (cxx) ... xcrun -sdk macosx clang
> checking for the c++ compiler (cxx) ... xcrun -sdk macosx clang
> checking for the c++ compiler (cxx) ... xcrun -sdk macosx clang
> checking for the c++ compiler (cxx) ... xcrun -sdk macosx clang
> checking for the c++ compiler (cxx) ... xcrun -sdk macosx clang
> checking for the c++ compiler (cxx) ... xcrun -sdk macosx clang
> checking for the c++ compiler (cxx) ... xcrun -sdk macosx clang
> checking for the c++ compiler (cxx) ... xcrun -sdk macosx clang
> checking for /usr/bin/xcrun -sdk macosx clang ... ok
> checking for flags (-fPIC) ... ok
> > xcrun -sdk macosx clang "-fPIC"
> checking for flags (-fvisibility-inlines-hidden) ... ok
> > xcrun -sdk macosx clang "-fvisibility-inlines-hidden"
> checking for flags (-O0) ... ok
> > xcrun -sdk macosx clang "-O0"
> checking for xcrun -sdk macosx ar ... /usr/bin/xcrun -sdk macosx ar
> checking for the static library archiver (ar) ... xcrun -sdk macosx ar
> [100%]: build ok!

**Comment by waruqi** [comment]
头文件不参与编译，cmake 加进去也不会编译他们，编译错误，跟 头文件是否参与编译无关。

> [100%]: build ok!


另外，你贴的错误信息里面，我没看到任何错误，看输出不是 build ok 了么

**Comment by RinOrz** [comment]
> 头文件不参与编译，cmake 加进去也不会编译他们，编译错误，跟 头文件是否参与编译无关。

原来如此...我还以为在头文件中写入源码也会参与编译，因为我看到那个项目里面是这么写的 
https://github.com/facebook/redex/blob/1f78158bda4837c8c14c0d9418e5d5728a43c9f9/CMakeLists.txt#L67-L94

> 另外，你贴的错误信息里面，我没看到任何错误，看输出不是 build ok 了么

是运行错误

---
这个我暂时关闭吧，看起来是其他原因了，我再排查排查

**Comment by RinOrz** [comment]
我发现链接报错中有这两个参数 `"-Wl,-dead_strip" "-nodefaultlibs"`, 这是链接器默认行为还是xmake内置的呢，defaultlibs可以添加到链接中吗

**Comment by waruqi** [comment]
这两 xmake 不会加 你找找自己哪里加进去的

**Comment by RinOrz** [comment]
看起来是 Rust 链接时添加的选项
