### ISSUE TITLE
Validate the pac file on setting

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2148]
### 你在什么场景下需要该功能？

运行`xmake g --proxy_pac=...`的时候希望能检测一下文件是否存在；例如`xmake g --proxy_pac=github_mirror.lua`误写成`xmake g --proxy_pac=github_mirrors.lua`，希望能发出警告github_mirrors.lua不存在

### 描述可能的解决方案

加一个检测和warning

**Comment by waruqi** [comment]
你可以直接这里改下 https://github.com/xmake-io/xmake/blob/205f1d2ae8281955b22b868eb16741a86e44da58/xmake/modules/net/proxy.lua#L68

**Comment by xq114** [comment]
https://github.com/xmake-io/xmake/blob/205f1d2ae8281955b22b868eb16741a86e44da58/xmake/actions/global/main.lua#L52

这里直接设置完就返回了，走不到net/proxy那里

**Comment by waruqi** [comment]
那这个暂时搞不了，只能跑到的时候，检测下，xmake g 设置阶段没法处理
