### ISSUE TITLE
安装vcpkg中的包时triplet判断错误

### ISSUE THREAD

**Issue by woodkatu** [xmake-io/xmake#2149]
### Xmake 版本

2.6.4

### 操作系统版本和架构

windows 10 21H1 x86-64

### 描述问题

命令 add_requires("vcpkg::ffmpeg", {alias = "ffmpeg", configs = {vs_runtime="MD", shared = true}})
会安装 ffmpeg:x64-windows-static

### 期待的结果

安装 ffmpeg:x64-windows

### 附加信息和错误日志

在modules\package\manager\vcpkg\install_package.lua中print后发现shared变量在opt.configs下
`if opt.plat == "windows" and opt.shared ~= true then`中的 opt.shared应该是opt.configs.shared

**Comment by waruqi** [comment]
好了，再试试
