### ISSUE TITLE
第一次执行 xrepo install pkg.lua，若 system=false 不会自动更新 repositoriy

### ISSUE THREAD

**Issue by cyfdecyf** [xmake-io/xmake#2158]
### Xmake 版本

2.6.4

### 操作系统版本和架构

Ubuntu 18.04

### 描述问题

`~/.xmake` 和 `/dev/shm/.xmake<uid>` 目录为空的情况下，执行 `xmake install pkg.lua`。

若 `pkg.lua` 给出的配置中包含 `system=false` 配置则不会自动更新 repository。

使用 xmake 版本为 2.6.4，修改了 `xmake/core/sandbox/modules/import/core/package/repository.lua` 以便替换默认 repo。这个改动应该不太会影响到此处的行为。若无法复现，我再贴出 patch 代码。

### 期待的结果

是否包含 `system=false` 不影响自动更新 repository 的行为。

### 工程配置

pkg.lua 内容

```lua
add_requires("libunwind", {system = false})
```

去掉 `system = false` 则能够成功安装。

### 附加信息和错误日志

出错日志 [log.txt](https://github.com/xmake-io/xmake/files/8239096/log.txt)

**Comment by waruqi** [comment]
应该可以了 再试试

**Comment by cyfdecyf** [comment]
已经解决，谢谢！
