### ISSUE TITLE
Fail to fetch repository if an empty folder is present

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2159]
### Xmake 版本

2.6.4

### 操作系统版本和架构

Windows 10

### 描述问题

在xmake fetching remote repo过程中如果中途ctrl+c打断，会在~/.xmake/repositories文件夹留下一个build-artifacts的空文件夹；存在空文件夹时再执行xmake只会报错fatal: not a git repository，只能靠手动删除空文件夹解决

### 期待的结果

xmake应自动修复此类问题。例如，在更新remote repositories时，先检查目标文件夹是否包含.git，如果不包含则删除目标文件夹重新git clone；或者运行git pull失败，则删除目标文件夹重新clone

### 附加信息和错误日志

```
> xmake -vD
checking for ...
...
updating repositories ..
pulling repository(build-artifacts): https://gitee.com/xmake-mirror/build-artifacts.git to C:\Users\xq114\AppData\Local\.xmake\repositories\build-artifacts ..
git pull origin main
fatal: not a git repository (or any of the parent directories): .git
error: @programdir\core\main.lua:280: @... failed
stack traceback:
...
[@programdir\plugins\repo\main.lua:137]: in function '_update'
[@programdir\plugins\repo\main.lua:233]:
```

**Comment by waruqi** [comment]
可以了，再试试，不过没测过

**Comment by xq114** [comment]
这里光检测空文件夹还不够，中间打断之后不一定是空文件夹，也可能是有一些文件的损坏文件夹

![image](https://user-images.githubusercontent.com/42310255/192570497-716a1501-98c9-40ff-8398-7efe8e2250b9.png)

最好用git来检测，如果pull失败那就删掉整个文件夹再试

**Comment by waruqi** [comment]
删非空还安全点，删非空有点危险哈，要是有个其他的 bug ，删错目录就蛋疼了。

**Comment by xq114** [comment]
![fe366efeb6cc4266ead1cb8373cb07a](https://user-images.githubusercontent.com/42310255/192789383-a6db9b32-ca7b-443f-b472-ee2740538efd.png)
他们目录长这样

**Comment by waruqi** [comment]
> ![fe366efeb6cc4266ead1cb8373cb07a](https://user-images.githubusercontent.com/42310255/192789383-a6db9b32-ca7b-443f-b472-ee2740538efd.png) 他们目录长这样

这个不是有 .git 么，啥问题呢？

**Comment by xq114** [comment]
好像还不是打断的问题，因为这里clone下来的仓库是完整的；可能是并行的问题，出现了数据冲突，报错fatal: not a repository (or any of the parent directories) : .git

**Comment by xq114** [comment]
是不是同时运行多个git命令引起的？

**Comment by waruqi** [comment]
> 是不是同时运行多个git命令引起的？

是的，目前是并行拉的。

https://github.com/xmake-io/xmake/blob/0d2b60e8732d531a1e75e0a298b8235f1b3cc0da/xmake/plugins/repo/main.lua#L121

带 -v 禁用并行为了看 verbose logs

**Comment by waruqi** [comment]
你可以这里改成这样试下，加上 `{isolate = true}` ，对 curdir 和 envs 进行 task 隔离

```lua
        runjobs("update repo", task, {progress = true, isolate = true})
```

**Comment by xq114** [comment]
这个问题也不是人人都有的，随机出现，很可能就是并行的问题，刚刚那个情况build-artifacts是好的，但xmake-repo里面只有一个不完整的.git文件夹

**Comment by xq114** [comment]
我这也不能稳定复现。要么检测一下只有.git的文件夹删掉？

**Comment by waruqi** [comment]
> 我这也不能稳定复现。要么检测一下只有.git的文件夹删掉？

如果有 .git ，就不会提示 not a git repo 的错误了，我 dev 先加了 isolate ，后面先观察一段时间吧，看看还会不会出现

**Comment by xq114** [comment]
问题还是在，能不能加个命令手动清理所有repository？

**Comment by waruqi** [comment]
```console
xrepo rm-repo --all
xrepo update-repo
```

**Comment by waruqi** [comment]
不知道是否跟这个有没有关系，比如并行拉取 repo 时候，互相占用对方 repo 目录，导致拉取失败等等。https://github.com/xmake-io/xmake/issues/2902#issuecomment-1326631095

我 dev 改进了进程启动，收敛了 handles 继承范围，可以尝试更新到 dev，然后再观察一段时间看看。

**Comment by xq114** [comment]
https://github.com/xmake-mirror/build-artifacts/actions/runs/3548938402/jobs/5961867476

这里报handle is invalid，不知道是不是改动的副作用

**Comment by waruqi** [comment]
看着像是，但是很奇怪，xmake-repo 和 xmake 的 ci 上也都在跑 dev ，就没遇到这个问题，我这暂时无法本地复现

**Comment by waruqi** [comment]
修复了 应该可以了

**Comment by waruqi** [comment]
> https://github.com/xmake-mirror/build-artifacts/actions/runs/3548938402/jobs/5961867476
> 
> 这里报handle is invalid，不知道是不是改动的副作用

这个 job 我重新跑过了

**Comment by waruqi** [comment]
最近还有这个问题么，没有的话，可以先关了。。
