### ISSUE TITLE
Find mingw from virtual envs

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2162]
### 你在什么场景下需要该功能？

https://github.com/xmake-io/xmake/blob/bc501387029826a8dbcb6a5b7776fd8f17e37d2f/xmake/modules/detect/sdks/find_mingw.lua#L46-L58

目前执行`xrepo env -b mingw-w64 shell`进入mingw环境后，可以正常使用gcc、g++等工具，但运行xmake f -p mingw仍然报错找不到mingw。find_mingw.lua只识别到路径中mingwxx\bin的形式，xrepo安装的mingw路径`C:\Users\xq114\AppData\Local\.xmake\packages\m\mingw-w64\8.1.0\aad6257977e0449595004d7441358fc5\bin`被忽略了。

### 描述可能的解决方案

在windows上先从PATH找gcc.exe，然后将gcc.exe的目录即设为mingw目录

### 描述你认为的候选方案

同时识别mingwxxx\<version>\<hash>\bin的形式

**Comment by waruqi** [comment]
可以了

**Comment by xq114** [comment]
好像不对啊
```
[base] PS C:\Users\xq114> xmake l detect.sdks.find_mingw
{ 
  bindir = "C:\Users\xq114\AppData\Local\.xmake\packages\p\python\3.9.10\3b40a992d2bf4866addcf5c48dee6441\bin",
  sdkdir = "C:\Users\xq114\AppData\Local\.xmake\packages\p\python\3.9.10\3b40a992d2bf4866addcf5c48dee6441"
}
```

**Comment by waruqi** [comment]
再试试

**Comment by xq114** [comment]
现在可以了
