### ISSUE TITLE
2015版的MBP系统版本macos12.2.1上安装报错

### ISSUE THREAD

**Issue by huye** [xmake-io/xmake#2169]
### Xmake 版本

2.6.4

### 操作系统版本和架构

2015 macOS 12.2.1

### 描述问题

新系统直接命令网络安装报错，错误如下：
`
compile.r tbox/src/tbox/platform/ifaddrs.c
make[3]: *** [tbox/src/tbox/platform/ifaddrs.o] Error 1
make[2]: *** [DEP_PROS_tbox_all] Error 2
tbox/src/tbox/platform/ifaddrs.c:187:17: error: variable 'ipflags' set but not used [-Werror,-Wunused-but-set-variable]
    tb_uint32_t ipflags = 0;
                ^
1 error generated.
installing to /Users/desk/.local ...
plat: macosx
arch: x86_64
cp: ./core/src/demo/demo.b: No such file or directory
make: *** [install] Error 1
Install Fail
`

### 期待的结果

因为以前都是在Linux上用的，第一次在macOS上安装，不知道错误情况原因。

**Comment by waruqi** [comment]
再试试

**Comment by huye** [comment]
我是用的
`bash <(curl -fsSL https://xmake.io/shget.text)`
这个命令安装的，问题还是一样的。现在要怎么测试你的处理？

**Comment by waruqi** [comment]
用这个 
```
bash <(curl -fsSL https://xmake.io/shget.text) dev
```
