### ISSUE TITLE
Different toolchain should not be treated as cross toolchain

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2170]
### Xmake 版本

2.6.4

### 操作系统版本和架构

ubuntu

### 描述问题

https://github.com/xmake-io/xmake-repo/runs/5572755726?check_suite_focus=true

CMAKE_SYSTEM_PROCESSOR变量缺失，原因是cmake中显式设置了CMAKE_SYSTEM_NAME，导致cmake误以为正在交叉编译

### 期待的结果

传toolchain单独处理，不应与cross混为一谈

https://github.com/xmake-io/xmake/blob/64fde43f3f58d86446ed5ea0c7e4a187fd93f898/xmake/modules/package/tools/cmake.lua#L514-L516

### 附加信息和错误日志

https://cmake.org/cmake/help/latest/variable/CMAKE_CROSSCOMPILING.html

**Comment by waruqi** [comment]
再试试

**Comment by xq114** [comment]
还有autoconf也有此问题：

https://github.com/xmake-io/xmake/blob/64fde43f3f58d86446ed5ea0c7e4a187fd93f898/xmake/modules/package/tools/autoconf.lua#L261-L267

为啥ar tool是ar就说明是cross compiling？换toolchain=clang这里也会判断为真

**Comment by xq114** [comment]
而且toolchain=clang情况下autoconf的CXX不能用clang，必须用clang++，因为autoconf会直接使用CXX compiler作为linker，不会使用声明的LD，因此无法使用clang编译并使用clang++链接

**Comment by waruqi** [comment]
> 为啥ar tool是ar就说明是cross compiling？换toolchain=clang这里也会判断为真

没说是 cross compile，这里就是判断 cross complie 或者 toolchian=clang/gcc 两种 case

**Comment by waruqi** [comment]
改了下，再试试
