### ISSUE TITLE
vs project fails to build due to pdb race condition

### ISSUE THREAD

**Issue by yamashi** [xmake-io/xmake#2171]
### Xmake Version

dev

### Operating System Version and Architecture

Windows 11

### Describe Bug

When using the `vs` generator some projects will fail to build with the following errors:
```
2>F:\Dev\TiltedEvolution\Code\tp_process\main.cpp : fatal error C1041: cannot open program database 'F:\Dev\TiltedEvolution\vs2022\TPProcess\build\windows\x64\debug\compile.TPProcess.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
2>F:\Dev\TiltedEvolution\Code\tp_process\ProcessHandler.cpp : fatal error C1041: cannot open program database 'F:\Dev\TiltedEvolution\vs2022\TPProcess\build\windows\x64\debug\compile.TPProcess.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
```

After checking 

### Expected Behavior

It builds.

### Additional Information and Error Logs

VS also spews a few logs before this happens
```
2>cl : command line warning D9025: overriding '/Fd..\..\build\.objs\TPProcess\windows\x64\debug\vc143.pdb' with '/Fdbuild\windows\x64\debug\compile.TPProcess.pdb'
2>cl : command line warning D9025: overriding '/W0' with '/W3'
2>cl : command line warning D9025: overriding '/Fd..\..\build\.objs\TPProcess\windows\x64\debug\vc143.pdb' with '/Fdbuild\windows\x64\debug\compile.TPProcess.pdb'
2>cl : command line warning D9025: overriding '/W0' with '/W3'
2>cl : command line warning D9025: overriding '/Fd..\..\build\.objs\TPProcess\windows\x64\debug\vc143.pdb' with '/Fdbuild\windows\x64\debug\compile.TPProcess.pdb'
2>cl : command line warning D9025: overriding '/W0' with '/W3'
```

My theory at the moment is that overriding this way does not propagate to the sync server for pdb access, so VS instructs the sync server to watch vc143.pdb and then cl.exe syncs vc143.pdb but not the override. Could be a cl.exe bug but I can't find a workaround to prevent xmake from overriding like that.

EDIT: I have confirmed that this happens when the pdb path is passed in the ClCompile for specific files which happens when my project contains a .rc file, if I remove the rc file the ClCompile does not contain any command argument.

I opened a ticket with microsoft regarding this issue but I don't think the pdb path should be set for each individual file, it should be at the project level.

**Comment by waruqi** [comment]
I have fixed it on dev.
