### ISSUE TITLE
指定 --toolchain 无法编译 c-ares

### ISSUE THREAD

**Issue by cyfdecyf** [xmake-io/xmake#2178]
### Xmake 版本

dev 分支 commit 7979010

### 操作系统版本和架构

CI 环境的 Ubuntu

### 描述问题

尝试在 xmake-repo 的 CI 环境中复现，https://github.com/cyfdecyf/xmake-repo/commit/1acc72fcd3b503b993558fa5a24cda0ee69e8ebe

出错[日志](https://github.com/cyfdecyf/xmake-repo/runs/5610485977?check_suite_focus=true#step:5:172)。

我在本地试过

1. 不加 `--toolchain` 选项，可以编译安装
2. 将 xmake 代码 toolchain/gcc.lua 中的 cxx 改为 g++，可以解决问题

估计是 autotools linker 的问题。

CI 环境 ubuntu_clang 没有这个问题，CI [记录](https://github.com/cyfdecyf/xmake-repo/runs/5610486008?check_suite_focus=true)。

### 期待的结果

指定 `--toolchain` 能正常编译。

**Comment by cyfdecyf** [comment]
6675ca4e4 这个修改应该对 g++ 也做同样的处理吧。

**Comment by waruqi** [comment]
再试试 dev

**Comment by cyfdecyf** [comment]
9e37fafc56c2a8bba0f252365840718121c0856a

似乎少了一行 gcc 的处理逻辑？

```lua
name = name:gsub("gcc$", "g++")
```

**Comment by waruqi** [comment]
这个暂时不改，等有问题再说

**Comment by cyfdecyf** [comment]
试了下，不指定 g++ 会出问题。

尝试 trigger CI 的[改动](https://github.com/cyfdecyf/xmake-repo/commit/adc8e4662b2b7bbedffb1613141965f3520833d8)，出错[日志](https://github.com/cyfdecyf/xmake-repo/runs/5617609887?check_suite_focus=true)。

**Comment by waruqi** [comment]
看了下，确实，以前现有的包没问题是因为，之前没透传 toolchain，让 autoconf 自动探测的系统 gcc，所以没问题，如果显式传递 CXX 还是得改下，刚我改了，再试试

**Comment by cyfdecyf** [comment]
谢谢。是不是可以在 xmake-repo 里再可以加一个 CI，指定 `--toolchain=gcc`，这样 clang 和 gcc 都能 cover 到了。

**Comment by waruqi** [comment]
> 谢谢。是不是可以在 xmake-repo 里再可以加一个 CI，指定 `--toolchain=gcc`，这样 clang 和 gcc 都能 cover 到了。

暂时不加了，加一个只是为了基本覆盖下工具链切换，现在 xmake-repo 上 ci jobs 已经过多了，再多影响效率
