### ISSUE TITLE
Linux home 目录存在 xmake.lua 时行为异常

### ISSUE THREAD

**Issue by cyfdecyf** [xmake-io/xmake#2179]
### Xmake 版本

dev 分支 commit 7979010

### 操作系统版本和架构

Ubuntu 18.04

### 描述问题

当存在文件 `~/xmake.lua` 时，xrepo 的各种命令都变得异常。

例如 `xrepo install pkg.lua` 会说找不到 `pkg.lua` 这个包而不是将其理解为 lua 脚本进行处理。

遇到这个问题是因为我在调试 xrepo zstd 的安装，拷贝了生成的 `xmake.lua` 文件到 home 目录进行查看，之后便遇到了各种奇怪的问题。

### 期待的结果

到目前为止还未在文档中留意到过 `~/xmake.lua` 会有什么特别之处，这个行为挺让人意外，看起来像是 bug。

**Comment by waruqi** [comment]
xrepo 其实就是 xmake 的 wrap，而 xmake 执行的当前 work 目录，是基于顶层的 xmake.lua ，类似 .git 的处理，在任意子目录执行，都会把顶层的 xmake.lua 作为主工程目录。。

所以，~/xmake.lua 存在，会使得 xmake 在 ~/xxx/xx 目录下执行，都把 `~` 作为一个完整的 xmake.lua 项目来加载

尽管 xrepo 不执行编译，但是 xrepo 是用 xmake lua 去 wrap 加载的，所以在选项解析阶段，主工程的 xmake.lua 也会加载一次

具体受影响程度，得看 ~/xmake.lua 里面的内容，至少我这如果只是加一个空 xmake.lua ，对 xrepo install pkg.lua 执行影响不大，我这没能复现这个。。

另外，即使复现了，目前也是无解的，所以建议不要在顶层以及任意非工程目录放置 xmake.lua ，除非它真的是一个 xmake 工程。。
