### ISSUE TITLE
当使用--curses=no参数时会出现error: ld: archive has no table of contents file 'build.d/macosx/x86_64/release/liblcurses.a'

### ISSUE THREAD

**Issue by leleliu008** [xmake-io/xmake#2186]
### Xmake 版本

2.6.4

### 操作系统版本和架构

macOS 10.15.7   macOS11  macOS12 都有  x86_64

### 描述问题

![xmake-xcode-ld-error](https://user-images.githubusercontent.com/3040852/159198301-ccde7cc2-615a-45bb-b6d1-35bc6bf45f8a.png)

### 期待的结果

正常编译通过

### 工程配置

```
xmake config --clean -vD --mode=release --plat=macosx --arch=x86_64 --toolchain=xcode --buildir=./build.d --curses=no
xmake
```

### 附加信息和错误日志

https://github.com/leleliu008/test/runs/5620600001?check_suite_focus=true
https://github.com/leleliu008/test/runs/5620600083?check_suite_focus=true

解决办法：
增加`--arflags=-crs`，原因是默认的`ARFLAGS=-cr`

**Comment by waruqi** [comment]
也支持了

**Comment by waruqi** [comment]
@leleliu008 我记得你这之前好像搞了 macos m1 的 ci workflow 在 github 上，你还记得怎么弄的么？

> https://github.com/leleliu008/test/runs/5620600001?check_suite_focus=true

我看这个 link 无效了。

**Comment by leleliu008** [comment]
那个仓库（https://github.com/leleliu008/test](https://github.com/leleliu008/test）是专门用来做临时测试的，所以没用了的workflow就被我删除了。

GitHub Actions目前还不支持主机是arm64的。

你说的是生成的exe文件能运行在macOS-arm64上的吧？

**Comment by waruqi** [comment]
> 那个仓库 https://github.com/leleliu008/test 是专门用来做临时测试的，所以没用了的workflow就被我删除了。
> 
> GitHub Actions目前还不支持主机是arm64的。
> 
> 你说的是生成的exe文件能运行在macOS-arm64上的吧？

哦哦，那就是你之前那个是交叉编译，不是跑的 m1?

**Comment by leleliu008** [comment]
是的

**Comment by waruqi** [comment]
了解了，谢谢

**Comment by leleliu008** [comment]
我说的GitHub Actions目前还不支持主机是arm64的是GitHub-hosted的这种形式
实际上GitHub Actions还支持你自己self-hosted形式的，就是你需要自己弄macOS-arm64的主机

参考： https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners

**Comment by waruqi** [comment]
> 实际上GitHub Actions还支持你自己self-hosted形式的，就是你需要自己弄macOS-arm64的主机

这个我知道，homebrew 就是这么搞的，目前就是身边没 m1 机器，所有想起来之前你这 repo 我好像看到过来着。
