### ISSUE TITLE
build for iphoneos failed due to 'system' system call is not available on ios

### ISSUE THREAD

**Issue by leleliu008** [xmake-io/xmake#2187]
### Xmake 版本

github master

### 操作系统版本和架构

与系统无关

### 描述问题

![xmake-ios-error](https://user-images.githubusercontent.com/3040852/159199306-497ab655-ef26-4af5-9f34-42b0a149e1fe.png)

### 期待的结果

能够编译为iPhoneOS的二进制文件

### 工程配置

```
xmake config --clean -vD --mode=release --plat=iphoneos --arch=arm64 --toolchain=xcode --buildir=./build.d --curses=no --arflags=-crs
xmake
```

### 附加信息和错误日志

解决办法：

```
sed -i .bak 's|system(cmd)|execl("/bin/sh" "sh" "-c", cmd, (char*)NULL)|' src/lua/lua/loslib.c
```

`system` 系统调用因为存在重大安全漏洞而被Apple在移动平台上禁止调用了，我们可以使用其他函数实现。

https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87152177

**Comment by waruqi** [comment]
？ 编译 xmake 自身？还是编译 lua 库？

前者没必要，干嘛要在 ios 上跑 xmake 命令，后者自己改代码，跟 xmake 没啥关系

**Comment by leleliu008** [comment]
是，编译xmake自身，ios上也有terminal的

**Comment by huye** [comment]
有点过份了，之前我都说，作图，写代码这些不适合在手机上搞，一是屏太小，二是没键盘鼠标。你说你编译到手机上有什么用了？

**Comment by leleliu008** [comment]
是使用平板，不是使用手机，这个对经常外出的人很有用的，键盘用外接的折叠式蓝牙键盘

**Comment by leleliu008** [comment]
这个很多人都在用，经常外出的人背个笔记本太重了。不会当住主力开发工作站，就是为了应急用的。

**Comment by leleliu008** [comment]
这个问题没有价值，我关闭了

**Comment by waruqi** [comment]
刚 dev 已经支持了

**Comment by leleliu008** [comment]
OK，谢谢啊~
