### ISSUE TITLE
macOS 编译老是报错，但是修改下配置文件再执行又能正常执行了

### ISSUE THREAD

**Issue by huye** [xmake-io/xmake#2189]
### Xmake 版本

v2.6.4+dev.35fa885

### 操作系统版本和架构

macOS 12.2.1  2015 amd64

### 描述问题

$ xmake -vvv
checking for Xcode directory ... %s
checking for Codesign Identity of Xcode ... no
checking for SDK version of Xcode for macosx (x86_64) ... nil
checking for Minimal target version of Xcode for macosx (x86_64) ... nil
checking for dmd ... no
checking for ldc2 ... no
checking for gdc ... no
checking for zig ... no
checking for zig ... no
error: @programdir/core/base/filter.lua:68: run $(shell pkg-config --libs openssl) failed, errors:
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:849]:
    [@programdir/core/base/filter.lua:68]:
    [@programdir/core/base/filter.lua:183]: in function 'handle'
    [@programdir/core/base/interpreter.lua:452]: in function '_filter'
    [@programdir/core/base/interpreter.lua:483]: in function '_handle'
    [@programdir/core/base/interpreter.lua:523]:
    [C]: in function 'xpcall'
    [@programdir/core/base/interpreter.lua:743]: in function 'make'
    [@programdir/core/project/project.lua:255]: in function '_load_scope'
    [@programdir/core/project/project.lua:192]: in function '_load'
    [@programdir/core/project/project.lua:479]: in function '_load_options'
    [@programdir/core/project/project.lua:972]: in function 'options'
    [...dir/core/sandbox/modules/import/core/project/project.lua:78]: in function 'check'
    [@programdir/actions/config/main.lua:389]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/core/base/task.lua:519]: in function 'run'
    [@programdir/core/sandbox/modules/import/core/base/task.lua:63]: in function 'run'
    [@programdir/actions/build/main.lua:127]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/core/base/task.lua:519]: in function 'run'
    [@programdir/core/main.lua:278]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:371]:

### 期待的结果

xmake clean 也报错，可能跟我写的xmake不规范也有关系，但我注释掉执行一下，再去掉注释再执行又是能正常执行的。所以我觉得这个问题，就算是我没有规范写配置文件，但xmake缓存处理也还是有些问题。
老大看看是不是 在公共部分（第一个target之前）这样写会引起这个问题：
add_shflags("$(shell pkg-config --libs openssl)")

**Comment by huye** [comment]
这个问题很奇怪，我刚才那样操作一下能正常执行，现在改一下又不行了。之前还有没修改也能正常执行的情况。反正就是改来改去，但内容没有变化（目的只是让时间更新一下或者中间临时注释掉那些错误再还原回来），有时能正常执行有时又不行。感觉问题还是在缓存上面的。

**Comment by waruqi** [comment]
有 add_requires("openssl") 包，干嘛不用，也会自动找系统库

**Comment by huye** [comment]
不光是这个包呀，还有些编译安装的包，有的可能pc文件都没有的，要么手动添加链接，要么自己写个pc文件呢？

**Comment by waruqi** [comment]
> 不光是这个包呀，还有些编译安装的包

都自己做成 package() 集成不就好了，没 pc 你走 `$(shell pkg-config` 也会报错，也是没用

另外，add_requires("xxx") 默认会自动查找系统库，用各种方式，内部也会调用 pkgconfig ，跟你现在手动调用没区别。即使没 pc，也会尝试扫 /usr/lib 系统目录找库。。

另外，自己编译安装，最好整个 pc 。。xmake 的 target 可以配置 rule，自动导出 pc。。再不济 直接 add_links add_linkdirs 也比你现在的方式强

**Comment by huye** [comment]
其它我原来就是用的 add_links 加载的 openssl，在Linux好好的，就是在macOS上报找不到库我才改为这个shell的。现在按你说的改为 add_requires 又可以了。不知道是不是add_links 也有兼容问题？

**Comment by waruqi** [comment]
> 不知道是不是add_links 也有兼容问题？

这跟兼容有啥关系，得加 add_linkdirs 。。macos 上 sysroot 又不在 /usr/local/lib 下，在 xcode 里。。不走 pkgconfig，又没 linkdirs 怎么可能找到

**Comment by huye** [comment]
不是xcode里的，我自己用brew安装的，用add_requires能找到。不说这个问题了，不影响使用就行。因为我之前一直使用的 add_links add_linkdirs add_shflags add_ldflags 这些，没用过 add_requires ，只以为是有bug。当然我提的这个bug应该还是算bug，主要就是在我改来改去的过程中，有时能正常编译，有时又会报错。如果老大觉得这个不算是bug，就关掉吧。

**Comment by waruqi** [comment]
> 不是xcode里的，我自己用brew安装的，用add_requires能找到

你没懂我意思，mac下，clang 的 sysroot 是在 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk，你单纯加 openssl links ，不加 linkdirs，clang 会默认找这个目录下的 库，即使你 brew 将库安装到 /usr/local/lib 下。clang 也不会默认去找它们来 link..

这跟 linux下是不同的，linux 下 gcc 默认的 sysroot 在 /usr/lib 下，你即使只加了 links ，不加 linkdirs ，gcc 也是能正常 link 到

所以只有借助 pkg-config 才能找到它们，用add_requires能找到，是因为，xmake 内部用了 pkg-config
