### ISSUE TITLE
"module 'std_config' is defined in both … and …" when importing a module from another library within the same project with clang

### ISSUE THREAD

**Issue by remi6397** [xmake-io/xmake#2194]
### Xmake Version

v2.6.4+202203070649

### Operating System Version and Architecture

macOS 12.2.1

### Describe Bug

"module 'std_config' is defined in both … and …" error appears when importing a module from another library within the same project with Homebrew clang 13.0.1.

### Expected Behavior

Project should build successfully (?)

Works on G++-11 from Homebrew.

(*I'm not very experienced with C++20 modules, so I hope I'm not trying to do the wrong thing here.*)

### Project Configuration

<details>
<summary><code>❯ tree</code></summary>
<pre>
.
├── bar.mpp
├── foo.mpp
└── xmake.lua
</pre>
</details>

<details>
<summary><code>❯ cat xmake.lua</code></summary>
<pre>
set_languages("c++20")

target("foo")
&nbsp;&nbsp;&nbsp;&nbsp;set_kind("static")
&nbsp;&nbsp;&nbsp;&nbsp;add_files("foo.cpp", "foo.mpp")

target("bar")
&nbsp;&nbsp;&nbsp;&nbsp;set_kind("static")
&nbsp;&nbsp;&nbsp;&nbsp;add_files("bar.cpp", "bar.mpp")
&nbsp;&nbsp;&nbsp;&nbsp;add_deps("foo")
</pre>
</details>

<details>
<summary><code>❯ cat foo.mpp</code></summary>
<pre>
export module foo;

import&lt;string&gt;;
</pre>
</details>

<details>
<summary><code>❯ cat bar.mpp</code></summary>
<pre>
export module bar;

import foo;

import&lt;string&gt;;
</pre>
</details>

<details>
<summary><code>❯ /usr/local/opt/llvm/bin/clang++ --version</code></summary>
<pre>
Homebrew clang version 13.0.1
Target: x86_64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
</pre>
</details>

### Steps to reproduce

<ol>
<li>
<details>
<summary><code>❯ xmake f -c -vD --toolchain=llvm --sdk=/usr/local/opt/llvm</code></summary>
<pre>
checking for platform ... macosx
checking for architecture ... x86_64
checking for Xcode directory ... /Applications/Xcode.app
checking for SDK version of Xcode for macosx (x86_64) ... 12.1
checking for clang ... /usr/local/opt/llvm/bin/clang
checking for the c++ compiler (cxx) ... clang
checking for /usr/local/opt/llvm/bin/clang ... ok
checking for flags (-fPIC) ... ok
> clang "-fPIC"
checking for flags (-fmodules) ... ok
> clang "-fmodules"
configure
{
&nbsp;&nbsp;&nbsp;&nbsp;plat = macosx
&nbsp;&nbsp;&nbsp;&nbsp;sdk = /usr/local/opt/llvm
&nbsp;&nbsp;&nbsp;&nbsp;xcode = /Applications/Xcode.app
&nbsp;&nbsp;&nbsp;&nbsp;clean = true
&nbsp;&nbsp;&nbsp;&nbsp;ndk_stdcxx = true
&nbsp;&nbsp;&nbsp;&nbsp;kind = static
&nbsp;&nbsp;&nbsp;&nbsp;ccache = true
&nbsp;&nbsp;&nbsp;&nbsp;mode = release
&nbsp;&nbsp;&nbsp;&nbsp;arch = x86_64
&nbsp;&nbsp;&nbsp;&nbsp;buildir = build
&nbsp;&nbsp;&nbsp;&nbsp;toolchain = llvm
&nbsp;&nbsp;&nbsp;&nbsp;host = macosx
}
</pre>
</details>
</li>
<li>
<details>
<summary><code>❯ xmake -rv</code></summary>
<pre>
generating.moduledeps bar.mpp
checking for the c++ compiler (cxx) ... clang
generating.moduledeps foo.mpp
checking for flags (-std=c++20) ... ok
checking for ccache ... no
[ 12%]: compiling.release foo.mpp
/usr/local/opt/llvm/bin/clang -c -Qunused-arguments -m64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -std=c++20 -fmodules -fimplicit-modules -fimplicit-module-maps -fprebuilt-module-path=build/.gens/foo/macosx/x86_64/release/rules/modules/cache --precompile -x c++-module -fmodules-cache-path=build/.gens/foo/macosx/x86_64/release/rules/modules/cache -o build/.gens/foo/macosx/x86_64/release/rules/modules/cache/foo.pcm foo.mpp
checking for flags (-MMD -MF) ... ok
checking for flags (-fdiagnostics-color=always) ... ok
/usr/local/opt/llvm/bin/clang -c -Qunused-arguments -m64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -std=c++20 -fmodules -fmodules-cache-path=build/.gens/foo/macosx/x86_64/release/rules/modules/cache -fimplicit-modules -fimplicit-module-maps -fprebuilt-module-path=build/.gens/foo/macosx/x86_64/release/rules/modules/cache -o build/.objs/foo/macosx/x86_64/release/foo.mpp.o build/.gens/foo/macosx/x86_64/release/rules/modules/cache/foo.pcm
checking for llvm-ar ... /usr/local/opt/llvm/bin/llvm-ar
checking for the static library archiver (ar) ... llvm-ar
[ 25%]: archiving.release libfoo.a
/usr/local/opt/llvm/bin/llvm-ar cr build/macosx/x86_64/release/libfoo.a build/.objs/foo/macosx/x86_64/release/foo.mpp.o
checking for flags (-fmodules) ... ok
[ 62%]: compiling.release bar.mpp
/usr/local/opt/llvm/bin/clang -c -Qunused-arguments -m64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -std=c++20 -fmodules-cache-path=build/.gens/foo/macosx/x86_64/release/rules/modules/cache -fprebuilt-module-path=build/.gens/foo/macosx/x86_64/release/rules/modules/cache -fmodules -fimplicit-modules -fimplicit-module-maps -fprebuilt-module-path=build/.gens/bar/macosx/x86_64/release/rules/modules/cache --precompile -x c++-module -fmodules-cache-path=build/.gens/bar/macosx/x86_64/release/rules/modules/cache -o build/.gens/bar/macosx/x86_64/release/rules/modules/cache/bar.pcm bar.mpp
error: bar.mpp:5:1: fatal error: module 'std_config' is defined in both '/Users/redacted/Developer/foobar/build/.gens/foo/macosx/x86_64/release/rules/modules/cache/217M0EF2WR0YA/std_config-Z5PCF8GTUA9H.pcm' and '/Users/redacted/Developer/foobar/build/.gens/bar/macosx/x86_64/release/rules/modules/cache/217M0EF2WR0YA/std_config-Z5PCF8GTUA9H.pcm'
import &lt;string&gt;;
^
1 error generated.
warning: cannot match target(foo).add_files("foo.cpp") at ./xmake.lua:5
warning: cannot match target(bar).add_files("bar.cpp") at ./xmake.lua:9
</pre>
</details>
</li>
</ol>

**Comment by remi6397** [comment]
Similar error occurs on Debian Sid with LLVM 14 and latest xmake from git:

> module '**_Builtin_stddef_max_align_t**' is defined in both … and …

----

<details>
<summary><code>$ clang-14 --version</code></summary>

```
Debian clang version 14.0.0-+rc4-1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

</details>

<details>
<summary><code>$ xmake --version</code></summary>

```
xmake v2.6.4+master.fb5f370, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, xmake.io

    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor
```

</details>

----

<ol>
<li>
<details>
<summary><code>$ xmake f -c --toolchain=llvm --sdk=/usr/lib/llvm-14 -vD --cxxflags='-isysroot /usr/lib/llvm-14 --stdlib libc++' --ar=/usr/lib/llvm-14/bin/llvm-ar</code></summary>

```
checking for platform ... linux
checking for architecture ... x86_64
checking for clang ... /usr/lib/llvm-14/bin/clang
checking for the c++ compiler (cxx) ... clang
checking for /usr/lib/llvm-14/bin/clang ... ok
checking for flags (-fPIC) ... ok
> clang "-fPIC"
checking for flags (-fmodules) ... ok
> clang "-fmodules"
configure
{
    sdk = /usr/lib/llvm-14
    ar = /usr/lib/llvm-14/bin/llvm-ar
    arch = x86_64
    kind = static
    host = linux
    mode = release
    toolchain = llvm
    buildir = build
    cxxflags = -isysroot /usr/lib/llvm-14 --stdlib libc++
    ccache = true
    plat = linux
    clean = true
    ndk_stdcxx = true
}
warning: cannot match target(foo).add_files("foo.cpp") at ./xmake.lua:5
```

</details>
</li>
<li>
<details>
<summary><code>$ xmake -rv</code></summary>

```
generating.moduledeps bar.mpp
checking for the c++ compiler (cxx) ... clang
generating.moduledeps foo.mpp
checking for flags (-std=c++20) ... ok
checking for ccache ... no
[ 12%]: compiling.release foo.mpp
/usr/lib/llvm-14/bin/clang -c -Qunused-arguments -m64 -isysroot /usr/lib/llvm-14 --stdlib libc++ -std=c++20 -fmodules -fimplicit-modules -fimplicit-module-maps -fprebuilt-module-path=build/.gens/foo/linux/x86_64/release/rules/modules/cache --precompile -x c++-module -fmodules-cache-path=build/.gens/foo/linux/x86_64/release/rules/modules/cache -o build/.gens/foo/linux/x86_64/release/rules/modules/cache/foo.pcm foo.mpp
checking for flags (-MMD -MF) ... ok
checking for flags (-fdiagnostics-color=always) ... ok
/usr/lib/llvm-14/bin/clang -c -Qunused-arguments -m64 -isysroot /usr/lib/llvm-14 --stdlib libc++ -std=c++20 -fmodules -fmodules-cache-path=build/.gens/foo/linux/x86_64/release/rules/modules/cache -fimplicit-modules -fimplicit-module-maps -fprebuilt-module-path=build/.gens/foo/linux/x86_64/release/rules/modules/cache -o build/.objs/foo/linux/x86_64/release/foo.mpp.o build/.gens/foo/linux/x86_64/release/rules/modules/cache/foo.pcm
[ 25%]: archiving.release libfoo.a
/usr/lib/llvm-14/bin/llvm-ar cr build/linux/x86_64/release/libfoo.a build/.objs/foo/linux/x86_64/release/foo.mpp.o
checking for flags (-fmodules) ... ok
[ 62%]: compiling.release bar.mpp
/usr/lib/llvm-14/bin/clang -c -Qunused-arguments -m64 -isysroot /usr/lib/llvm-14 --stdlib libc++ -std=c++20 -fmodules-cache-path=build/.gens/foo/linux/x86_64/release/rules/modules/cache -fprebuilt-module-path=build/.gens/foo/linux/x86_64/release/rules/modules/cache -fmodules -fimplicit-modules -fimplicit-module-maps -fprebuilt-module-path=build/.gens/bar/linux/x86_64/release/rules/modules/cache --precompile -x c++-module -fmodules-cache-path=build/.gens/bar/linux/x86_64/release/rules/modules/cache -o build/.gens/bar/linux/x86_64/release/rules/modules/cache/bar.pcm bar.mpp
error: bar.mpp:5:1: fatal error: module '_Builtin_stddef_max_align_t' is defined in both '/home/redacted/MacDeveloper/foobar/build/.gens/foo/linux/x86_64/release/rules/modules/cache/3G2ANGD0T06NQ/_Builtin_stddef_max_align_t-1H8I45IT1PNAL.pcm' and '/home/redacted/MacDeveloper/foobar/build/.gens/bar/linux/x86_64/release/rules/modules/cache/3G2ANGD0T06NQ/_Builtin_stddef_max_align_t-1H8I45IT1PNAL.pcm'
import <string>;
^
1 error generated.
warning: cannot match target(foo).add_files("foo.cpp") at ./xmake.lua:5
warning: cannot match target(bar).add_files("bar.cpp") at ./xmake.lua:9

```

</details>
</li>
</ol>

**Comment by waruqi** [comment]
not support yet, please use `#include <string>` first. see

https://github.com/xmake-io/xmake/blob/fb5f37067336a438f5e8adff01652e07bfee86fa/tests/projects/c%2B%2B/modules/hello/src/hello.mpp#L2

**Comment by remi6397** [comment]
> please use `#include <string>` first.

I'm afraid it doesn't work this way either. I'm getting the exact same error.

**Comment by remi6397** [comment]
Everything builds correctly if you disable ``-fmodules-cache-path=`` though:

<details>

```diff
diff --git a/xmake/rules/c++/modules/build_modules/clang.lua b/xmake/rules/c++/modules/build_modules/clang.lua
index 4cde114..89e1963 100644
--- a/xmake/rules/c++/modules/build_modules/clang.lua
+++ b/xmake/rules/c++/modules/build_modules/clang.lua
@@ -43,7 +43,6 @@ function load_parent(target, opt)
         local sourcebatches = dep:sourcebatches()
         if sourcebatches and sourcebatches["c++.build.modules"] then
             local cachedir = path.join(dep:autogendir(), "rules", "modules", "cache")
-            target:add("cxxflags", "-fmodules-cache-path=" .. cachedir, {force = true})
             target:add("cxxflags", "-fimplicit-modules", "-fimplicit-module-maps", "-fprebuilt-module-path=" .. cachedir, {force = true})
         end
     end
@@ -100,7 +99,7 @@ function build_with_batchjobs(target, batchjobs, sourcebatch, opt)
             -- compile module files to *.pcm
             local opt2 = table.join(opt, {configs = {force = {cxxflags = {modulesflag,
                 "-fimplicit-modules", "-fimplicit-module-maps", "-fprebuilt-module-path=" .. cachedir,
-                "--precompile", "-x c++-module", "-fmodules-cache-path=" .. cachedir}}}})
+                "--precompile", "-x c++-module"}}}})
             opt2.progress   = (index * 100) / total
             opt2.objectfile = modulefiles[i]
             opt2.dependfile = target:dependfile(opt2.objectfile)
@@ -108,7 +107,7 @@ function build_with_batchjobs(target, batchjobs, sourcebatch, opt)
             objectbuilder.build_object(target, sourcefile, opt2)

             -- compile *.pcm to object files
-            opt2.configs    = {force = {cxxflags = {modulesflag, "-fmodules-cache-path=" .. cachedir,
+            opt2.configs    = {force = {cxxflags = {modulesflag,
                 "-fimplicit-modules", "-fimplicit-module-maps", "-fprebuilt-module-path=" .. cachedir}}}
             opt2.quiet      = true
             opt2.objectfile = sourcebatch.objectfiles[i]
@@ -118,7 +117,7 @@ function build_with_batchjobs(target, batchjobs, sourcebatch, opt)
             -- add module flags to other c++ files after building all modules
             count = count + 1
             if count == sourcefiles_total then
-                target:add("cxxflags", modulesflag, "-fmodules-cache-path=" .. cachedir, {force = true})
+                target:add("cxxflags", modulesflag, {force = true})
                 -- FIXME It is invalid for the module implementation unit
                 --target:add("cxxflags", "-fimplicit-modules", "-fimplicit-module-maps", "-fprebuilt-module-path=" .. cachedir, {force = true})
                 for _, modulefile in ipairs(modulefiles) do
```

</details>

**Comment by waruqi** [comment]
I have fixed it for clang on dev. `xmake update -s dev`

**Comment by remi6397** [comment]
I can confirm it works correctly now, thank you!
