### ISSUE TITLE
libcurl 指定 --toolchain=gcc -f shared 编译失败

### ISSUE THREAD

**Issue by cyfdecyf** [xmake-io/xmake#2195]
### Xmake 版本

dev 分支 commit fb5f37067

### 操作系统版本和架构

Ubuntu 18.04

### 描述问题

在尝试解决 libcurl 开启 brotli 功能的时候试了下编译成动态库，发现指定 `--toolchain=gcc` 会出错，不指定则正常。https://github.com/xmake-io/xmake-repo/pull/1074

尝试触发的改动 https://github.com/xmake-io/xmake-repo/compare/master...cyfdecyf:libcurl-shared-toolchain

出错[日志](https://github.com/cyfdecyf/xmake-repo/runs/5641751987?check_suite_focus=true#step:5:449)。

### 期待的结果

指定 `--toolchain=clang` 是正常的，期望 gcc 也正常。

**Comment by waruqi** [comment]
再试试

**Comment by cyfdecyf** [comment]
本地试了下，执行 `xrepo install --toolchain=gcc-9 -f shared=true libcurl`  还是相同的错误。

这个我不着急能修复，动态库目前还不会用到。只是编译 libcurl 遇到问题时测试用了一下。

**Comment by waruqi** [comment]
我这里可以

```console
$ xrepo install --shallow --toolchain=gcc-11 -y --force -k shared libcurl 
  => install libcurl 7.82.0 .. ok  
```

**Comment by cyfdecyf** [comment]
在 Ubuntu 18.04 上用 gcc-11 也试了下，还是出错。传个完整的日志 [libcurl.install.log.gz](https://github.com/xmake-io/xmake/files/8325094/libcurl.install.log.gz)

**Comment by waruqi** [comment]
> checking if the linker (/usr/bin/gcc-11) is GNU ld... no

那就怪了，我已经修复了，应该是 ld 才对，我这也测试没问题。。确认下是否已经更新到最新 dev 。。不然我也不知道了

**Comment by cyfdecyf** [comment]
不好意思，我再重新编译安装 xmake 之后正常了。之前有确认过 `xrepo --version`，不知道哪里弄错了。

谢谢快速解决。

**Comment by waruqi** [comment]
更新 lua scripts ，version 不会变，version 只有 core binary 改动才会，如果只是更新脚本，走 xmake update -s dev 就行了
