### ISSUE TITLE
包管理问题

### ISSUE THREAD

**Issue by liuli-neko** [xmake-io/xmake#2202]
### Xmake 版本

2.6.4+202203251935

### 操作系统版本和架构

Ubuntu 20.04.4 LTS

### 描述问题

add_requires("opencv")
在已apt安装了libopencv-dev的情况下，xmake仍然下载并重新安装了一遍opencv。
add_requires("eigen3")
同样在已apt安装了libeigen3-dev的情况下，xmake无法导入或识别eigen。（编译包含eigen的头文件会直接报错）

### 期待的结果

希望能够加入对这两个库的支持，以及能够识别已安装的库

### 工程配置

add_requires("opencv4")
add_requires("libjpeg")
add_requires("libpng")
add_requires("libwebp")
add_requires("eigen3")
add_rules("mode.debug","mode.release")

target("viewer_test")
    add_includedirs("./include/camera")
    add_packages("opencv4")
    add_packages("libjpeg")
    add_packages("libpng")
    add_packages("libwebp")
    add_packages("eigen3")
    add_files("./src/camera/*.cc")
    add_files("./src/opencv_test/viewer_test.cc")
    if is_mode("debug") then 
        add_defines("DEBUG")
    end

**Comment by waruqi** [comment]
可以参考这个包的配置

https://github.com/xmake-io/xmake-repo/blob/d0fca1a8d3d00d2913a31cf9d2df2ffeedbaa21a/packages/f/freetype/xmake.lua#L22

在 opencv 包中，https://github.com/xmake-io/xmake-repo/blob/master/packages/o/opencv/xmake.lua

添加对应的 apt 源，提个 pr 过来。

如果 add_extsources 还是检测不到，就加个 on_fetch 做更完整的自定义 查找，参考

https://github.com/xmake-io/xmake-repo/blob/4b57a224b58bb8a38331ca75be7853c28706e09a/packages/b/brotli/xmake.lua#L27

https://github.com/xmake-io/xmake-repo/blob/52c27bf0940d3ffce261201c39911315854c3686/packages/l/libxnvctrl/xmake.lua#L10
