### ISSUE TITLE
xrepo env 支持指定 --toolchain

### ISSUE THREAD

**Issue by cyfdecyf** [xmake-io/xmake#2205]
### 你在什么场景下需要该功能？

类似 pyarrow 这样的 python package 需要先完成 C++ 包的编译安装，然后才能进行 python 包的构建。

当使用 xrepo 完成 C++ 包安装后，通过 `xrepo env` 进入已经设置好 `CMAKE_PREFIX_PATH` 等各种环境变量的 shell，后续编译 python 包就会很方便。

但若在编译 C++ 包时加上了 `--toolchain` 选项，则无法通过 `xrepo env --toolchain` 进入到合适的编译环境 shell 中。

### 描述可能的解决方案

`xrepo env` 支持 `--toolchain` 选项。

暂不支持的情况下，用户可以自行通过 `xrepo fetch` 获取包路径并自行设置需要的环境变量。例如 [`xrepo-apache-arrow/build.sh`](https://github.com/cyfdecyf/l/blob/main/build.sh#L33) 就是这样处理的。

但若需要添加的包很多，则这种方式处理起来会比较麻烦。除了 `CMAKE_PREFIX_PATH`，可能还需要设置  `PKG_CONFIG_PATH` 等许多 `xrepo env shell` 已经处理的变量。

**Comment by waruqi** [comment]
这个暂时不加了，`--toolchain` 局限太多，xrepo env shell 环境，需求复杂的，都建议通过 xmake.lua 配置来管理

当前目录配置，xmake.lua

```lua
set_toolchains("gcc")
add_requires("python")
```

然后执行 `xrepo env shell`

常用配置，可以通过 `xrepo env --add myenv.lua` 导入后，通过 `xrepo env -b myenv shell` 加载
