### ISSUE TITLE
xmake does not compile on Raspbian OS

### ISSUE THREAD

**Issue by IanBullard** [xmake-io/xmake#2206]
### Xmake Version

2.5.8

### Operating System Version and Architecture

Raspberry Pi OS

### Describe Bug

When trying to install/build xmake, a linking error occurs:

> make demo
> compile.r xmake.c
> link demo.b
> make[3]: *** [/home/ianadmin/github/xmake/core/suffix.mak:309: demo.b] Error 1
> make[2]: *** [/home/ianadmin/github/xmake/core/suffix.mak:309: SUB_PROS_demo_all] Error 2
> /usr/bin/ld: ../tbox/libtboxr.a(cache_time.o): in function `tb_cache_time_spak':
> cache_time.c:(.text+0x9c): undefined reference to `__atomic_store_8'
> /usr/bin/ld: ../tbox/libtboxr.a(cache_time.o): in function `tb_cache_time_mclock':
> cache_time.c:(.text+0xd4): undefined reference to `__atomic_load_8'
> /usr/bin/ld: cache_time.c:(.text+0x184): undefined reference to `__atomic_store_8'
> /usr/bin/ld: ../tbox/libtboxr.a(cache_time.o): in function `tb_cache_time_sclock':
> cache_time.c:(.text+0x1bc): undefined reference to `__atomic_load_8'
> /usr/bin/ld: cache_time.c:(.text+0x284): undefined reference to `__atomic_store_8'
> /usr/bin/ld: ../tbox/libtboxr.a(cache_time.o): in function `tb_cache_time':
> cache_time.c:(.text+0x2cc): undefined reference to `__atomic_load_8'
> /usr/bin/ld: cache_time.c:(.text+0x394): undefined reference to `__atomic_store_8'
> collect2: error: ld returned 1 exit status

This is because, for some reason, Raspbian/Raspberry Pi OS requires the atomic library to be linked to use the atomic types.

I have verified this does NOT happen on Kali Linux on the Pi, and probably others.  I have a fix, but I'm not a makefile expert and a new xmake user so I do not know if this is the proper solution.

I added the following line to core/makefile at line 291:

`base_LIBNAMES 	+= $(shell if { egrep -i \'ID=raspbian\' /etc/os-release -q; }; then echo atomic; fi )`

I can create a pull request if needed.

### Expected Behavior

I expect xmake to compile and install on Raspbian/Pi OS without error.

**Comment by waruqi** [comment]
see https://github.com/xmake-io/xmake/issues/1384#issuecomment-999273141

**Comment by IanBullard** [comment]
Thank you!
