### ISSUE TITLE
build-artifacts: fix path for libtool .la file on install

### ISSUE THREAD

**Issue by cyfdecyf** [xmake-io/xmake#2209]
### Is your feature request related to a problem? Please describe.

We may get file path in libtool .la file.

For example, under xmake package directory:

```console
$ rg nonexistent
l/libunwind/v1.5/cba21689e7cc42a9a1bab055135d6d5c/lib/libunwind-setjmp.la
20:dependency_libs=' /nonexistent/.xmake/packages/l/libunwind/v1.5/cba21689e7cc42a9a1bab055135d6d5c/lib/libunwind-x86_64.la /nonexistent/.xmake/packages/l/libunwind/v1.5/cba21689e7cc42a9a1bab055135d6d5c/lib/libunwind.la -lgcc_s -lc'
41:libdir='/nonexistent/.xmake/packages/l/libunwind/v1.5/cba21689e7cc42a9a1bab055135d6d5c/lib'
```

### Describe the solution you'd like

We can follow the solutions in #2200 which fixes path for pkg-config .pc files.

I'm not sure when is libtool being used. I'll leave it as is for now and try to fix it when it actually causes problem for compilation.

**Comment by waruqi** [comment]
这个目前用不到，暂时不用管它
