### ISSUE TITLE
build-artifacts: fix path for cmake file containing multiple paths on single line

### ISSUE THREAD

**Issue by cyfdecyf** [xmake-io/xmake#2210]
### Is your feature request related to a problem? Please describe.

Example of problemtic cmake file

```console
$ rg nonexistent
c/civetweb/v1.15/76b26eb3e5ce43e486cfdc0d14b1ae2f/lib/cmake/civetweb/civetweb-targets.cmake
52:  INTERFACE_LINK_LIBRARIES "-lpthread;/nonexistent/.xmake/packages/o/openssl/1.1.1m/fc2f462ae44846c1bcb8a958bc1b7a89/lib/libssl.so;/nonexistent/.xmake/packages/o/openssl/1.1.1m/fc2f462ae44846c1bcb8a958bc1b7a89/lib/libcrypto.so;/nonexistent/.xmake/packages/z/zlib/v1.2.11/8dc724df8cab415090b0f31e34c33cea/lib/libz.a"
```

The current fix path code prints a warning about this case instead of fixing the path.

### Describe the solution you'd like

I will add a search pattern `(([^%s;]+))` to cmake files case in https://github.com/xmake-io/xmake/commit/58d882b87f497705211294f156c4a9172f8a1ae5#diff-48079b78bab521d35135de125039d2c7efb2d51b575b51b04a62f2466a88323eR157

This pattern is quite general, but I can't come up with a more restricted pattern for now.

For my usage, I can use the known path prefix (`/nonexistent/.xmake/packages/`) to limit search pattern. But this solution is not general.

To make the solution general, can we we associate path prefix information when adding a build-artifacts repo? With known path prefix, the search pattern can be more simple and precise.

**Comment by waruqi** [comment]
I added it. https://github.com/xmake-io/xmake/commit/b178f763015779488df34e75990667eccb82521a

you can replace `remotedir` to `package:installdir()`.

```lua
local remotedir
local manifest = package:manifest_load()
if manifest and manifest.artifacts then
    remotedir = manifest.artifacts.remotedir
end
```

**Comment by cyfdecyf** [comment]
Thanks for such quick response. I'll have a try.
