### ISSUE TITLE
warning D9002 :忽略未知选项“-std:c++11”

### ISSUE THREAD

**Issue by wangzhankun** [xmake-io/xmake#2214]
### Xmake 版本

2.6.4

### 操作系统版本和架构

windows11, visual studio 2019

### 描述问题

在`xmake.lua`脚本中添加了指示语言的命令：
```lua
set_languages("cxx11")
```
但是提示
error: cl: 命令行 warning D9002 :忽略未知选项“-std:c++11”

### 期待的结果

能够正确使用指定语言版本的条件进行编译

### 工程配置

```lua
set_languages("cxx11")
add_cxxflags("-Wall -pedantic")

includes("src")

target("CodeCraft-2021")
    set_kind("binary")
    set_rules("mode.debug", "mode.release")
    -- add_files("src/*.cpp")
    -- set_optimize("fastest")
    if(is_mode("debug")) then
        add_defines("TEST")
    else
        set_optimize("fastest")
    end

```

### 附加信息和错误日志

error: cl: 命令行 warning D9002 :忽略未知选项“-std:c++11”

**Comment by waruqi** [comment]
这跟 xmake 有啥关系？能提示这个，说明 xmake 已经把 `-std:c++11` 设置进去了，至于编译器报错，那是编译器的问题

**Comment by xq114** [comment]
vs2019只支持c++14和c++17，不支持c++11

**Comment by wangzhankun** [comment]
好的，谢谢。
