### ISSUE TITLE
Cannot install dependencies from xrepo

### ISSUE THREAD

**Issue by michael-brennan2005** [xmake-io/xmake#2218]
### Xmake Version

2.6.4

### Operating System Version and Architecture

Fedora 5.16.14-200.fc35.x86_64

### Describe Bug

I cannot install raylib for an emulator I am writing.

### Expected Behavior

I want to install raylib and be able to use it in a project, instead I get this error:
`
[name@fedora crestone]$ xmake
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> raylib 4.0.0 
please input: y (y/n/m)
y
  => install raylib 4.0.0 .. failed

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/name/.config/.xmake/cache/packages/2203/r/raylib/4.0.0/source/raylib-4.0.0/src/OPENGL_INCLUDE_DIR
   used as include directory in directory /home/name/.config/.xmake/cache/packages/2203/r/raylib/4.0.0/source/raylib-4.0.0/src
CMake Generate step failed.  Build files cannot be regenerated correctly.
eatures - done
-- Performing Test COMPILER_HAS_THOSE_TOGGLES
-- Performing Test COMPILER_HAS_THOSE_TOGGLES - Success
-- Testing if -Werror=pointer-arith can be used -- compiles
-- Testing if -Werror=implicit-function-declaration can be used -- compiles
-- Testing if -fno-strict-aliasing can be used -- compiles
-- Using raylib's GLFW
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
if you want to get more verbose errors, please see:
  -> /home/name/.config/.xmake/cache/packages/2203/r/raylib/4.0.0/installdir.failed/logs/install.txt
error: install failed!
`

### Project Configuration

add_requires("raylib")

target("crestone")
    set_kind("binary")
    add_files("src/*.cpp")
    add_includedirs("src/")
    add_packages("raylib")

**Comment by waruqi** [comment]
run `xmake f -c -vD` and let me see the verbose output.

**Comment by tech0tron** [comment]
Here's a pastebin with the output:
https://pastebin.com/8A5JTj0Y

**Comment by waruqi** [comment]
I don't know, I didn't see any cmake error. It has finished to configure, but the exit code is non-zero.

> -- Configuring done
-- Generating done

**Comment by waruqi** [comment]
I don't know, I didn't see any cmake error. It has finished to configure, but the exit code is non-zero.

> -- Configuring done
-- Generating done

**Comment by tech0tron** [comment]
Raylib has a cmakelists.txt and also a build.zig file that just generates a .a file. Is there any way in xmake I can just add that directly in along with the headers?
