### ISSUE TITLE
protobuf编译依赖分析

### ISSUE THREAD

**Issue by shuax** [xmake-io/xmake#2225]
### 你在什么场景下需要该功能？

当proto文件本身存在依赖关系时，编译proto顺序不一定正确。

```proto
import "base.proto"
```

### 描述可能的解决方案

扫描一下import关系

### 描述你认为的候选方案

或者不要一边编译proto一边编译c，可以等所有proto编译完成以后再编译c。

**Comment by waruqi** [comment]
给个完整复现的例子和编译输出。

**Comment by shuax** [comment]
```python
for x in range(1, 100):
	f = open("proto/{}.proto".format(x), "w")
	f.write('syntax = "proto3";')
	if x==1:
		f.write('import "99.proto";')
```
生成99个proto文件
编译报错
```
[  0%]: compiling.proto proto\1.proto
[  0%]: compiling.proto proto\10.proto
[  0%]: compiling.proto proto\11.proto
[  0%]: compiling.proto proto\12.proto
[  0%]: compiling.proto proto\13.proto
[  0%]: compiling.proto proto\14.proto
[  4%]: compiling.proto proto\15.proto
[  4%]: compiling.proto proto\16.proto
[  4%]: compiling.proto proto\17.proto
[  4%]: compiling.proto proto\18.proto
error: 1.pb.cc
***.gens\test\windows\x64\release\rules\protobuf\proto\1.pb.h(32): fatal error C1083: 无法打开包括文件: “99.pb.h”: No such file or directory
```

**Comment by waruqi** [comment]
上传个完整 demo

**Comment by shuax** [comment]
[test.zip](https://github.com/xmake-io/xmake/files/8386489/test.zip)

**Comment by waruqi** [comment]
试了好几次，没测出啥问题，一切正常

```console
[ 66%]: compiling.proto proto/63.proto
[ 67%]: compiling.proto proto/24.proto
[ 68%]: compiling.proto proto/61.proto
[ 69%]: compiling.proto proto/7.proto
[ 70%]: compiling.proto proto/19.proto
[ 71%]: compiling.proto proto/85.proto
[ 72%]: compiling.proto proto/78.proto
[ 73%]: compiling.proto proto/45.proto
[ 74%]: compiling.proto proto/39.proto
[ 75%]: compiling.proto proto/81.proto
[ 76%]: compiling.proto proto/41.proto
[ 77%]: compiling.proto proto/20.proto
[ 78%]: compiling.proto proto/65.proto
[ 79%]: compiling.proto proto/98.proto
[ 80%]: compiling.proto proto/58.proto
[ 81%]: compiling.proto proto/3.proto
[ 82%]: compiling.proto proto/1.proto
[ 84%]: compiling.proto proto/22.proto
[ 84%]: compiling.proto proto/67.proto
[ 85%]: compiling.proto proto/43.proto
[ 86%]: compiling.proto proto/83.proto
[ 98%]: archiving.release libtest.a
[100%]: build ok!
```

**Comment by shuax** [comment]
能让1.proto最先编译，99.proto最后编译吗

**Comment by waruqi** [comment]
这是并行的控制不了，要想解析 import 做依赖并行编译是可以，不过要做不少改动，暂时没空搞。。你可以参考 

https://github.com/xmake-io/xmake/blob/06b374d6f1eb4b97f81dbcf9f5d528e3767981a1/xmake/rules/c%2B%2B/modules/build_modules/msvc.lua#L119-L149

对 proto 做类似的处理，c++ modules 里面，就是解析了源码 import 构建依赖图 然后进行依赖编译的。

**Comment by shuax** [comment]
我是说复现这个问题，最好用第一个去依赖最后一个proto，并不是真的要控制顺序。

**Comment by waruqi** [comment]
> 我是说复现这个问题，最好用第一个去依赖最后一个proto，并不是真的要控制顺序。

在没做依赖构建支持之前，是控制不了让 1.proto 先去编译的，也就没法复现。。而支持了依赖构建，这个问题就等于解了，也就没必要复现了。。

而且也不用复现，我大体知道什么问题，就是刚说的要支持 import 解析构造 .proto 之间的依赖关系，来处理编译顺序才行。。目前没时间支持。

**Comment by waruqi** [comment]
> 不用`before_buildcmd_file`一个一个处理，而是`before_buildcmd_files`一次性把所有proto处理了，再编译cpp，行得通吗。

现在就是先处理的 proto ，再编译的 cpp，问题是就算换成 before_buildcmd_files，那一批 proto 之间的依赖关系，你还是要处理，避免不了

**Comment by shuax** [comment]
> > 不用`before_buildcmd_file`一个一个处理，而是`before_buildcmd_files`一次性把所有proto处理了，再编译cpp，行得通吗。
> 
> 现在就是先处理的 proto ，再编译的 cpp，问题是就算换成 before_buildcmd_files，那一批 proto 之间的依赖关系，你还是要处理，避免不了

实际上编译proto并不会出错，而是生成的c文件有依赖关系编译才出错的。

**Comment by waruqi** [comment]
> > > 不用`before_buildcmd_file`一个一个处理，而是`before_buildcmd_files`一次性把所有proto处理了，再编译cpp，行得通吗。
> > 
> > 
> > 现在就是先处理的 proto ，再编译的 cpp，问题是就算换成 before_buildcmd_files，那一批 proto 之间的依赖关系，你还是要处理，避免不了
> 
> 实际上编译proto并不会出错，而是生成的c文件有依赖关系编译才出错的。

目前是在 proto rule 生成完 .c 然后直接阻塞编译的，跟 add_files 没啥关系，所以还是依赖 proto 的处理顺序

**Comment by waruqi** [comment]
> 试了下before_buildcmd_files，能用，但是并行不起来，编译特别慢，不好用，

那是因为不走并行了，恰巧顺序处理对了而已。但是 os.files 遍历的 proto file 列表顺序 依赖系统，也是未定义的

**Comment by Ocrosoft** [comment]
确实是个问题，我也遇到了，特别是在机器卡的时候就会找不到依赖头文件。

**Comment by shuax** [comment]
> 确实是个问题，我也遇到了，特别是在机器卡的时候就会找不到依赖头文件。

我现在是手动编译proto，先用着吧。

**Comment by waruqi** [comment]
改进了下， 更新到 dev 再试试，xmake update -s dev

**Comment by shuax** [comment]
可以了，感谢作者。
