### ISSUE TITLE
error: cannot copy file packages... file not found!

### ISSUE THREAD

**Issue by sunzhangchang** [xmake-io/xmake#2229]
### Xmake 版本

2.6.4

### 操作系统版本和架构

win10 1709

### 描述问题

![image](https://user-images.githubusercontent.com/52880063/161047815-57dc4305-ea6b-4b35-9734-64c139dbfb68.png)

### 期待的结果

成功import

**Comment by waruqi** [comment]
搞不懂你的用法，直接执行 `xmake` 不就完事了么。。

**Comment by sunzhangchang** [comment]
。
不会用，xmake以后怎么include

**Comment by waruqi** [comment]
只需要 `xmake` 。如果你配置对了，include 自己会找到。

**Comment by sunzhangchang** [comment]
直接`xmake`可以了
但是`xmake require`是什么

**Comment by waruqi** [comment]
你暂时不用管它，只需要 xmake 编译就行了
