### ISSUE TITLE
显示乱码

### ISSUE THREAD

**Issue by sunzhangchang** [xmake-io/xmake#2230]
### Xmake 版本

2.6.4

### 操作系统版本和架构

win10 1709

### 描述问题

![image](https://user-images.githubusercontent.com/52880063/161056934-5163aa59-6eac-44ec-9523-2bc962053b11.png)

有时候正常显示，有时候乱码

### 期待的结果

正常显示文字

**Comment by waruqi** [comment]
xmake g --theme=plain

**Comment by sunzhangchang** [comment]
![image](https://user-images.githubusercontent.com/52880063/161250811-494a3f9b-6cf0-4043-a2c3-63181aa180e0.png)

设置完以后

![image](https://user-images.githubusercontent.com/52880063/161250724-09312ea8-883e-40dd-9e40-8f1de91a548f.png)

**Comment by waruqi** [comment]
这个不用管它，有些终端是会这样

**Comment by sunzhangchang** [comment]
。没有解决办法吗

**Comment by waruqi** [comment]
没

**Comment by sunzhangchang** [comment]
ok
