### ISSUE TITLE
链接报错不能触发重新编译

### ISSUE THREAD

**Issue by MaxwellGengYF** [xmake-io/xmake#2236]
### Xmake 版本

2.6.4

### 操作系统版本和架构

Windows 10

### 描述问题

开启Unity Build，Link阶段报错，在文件夹中添加新的cpp文件（未超过unity build batch size），重新编译会直接跳转到link阶段并持续报错。

### 期待的结果

检测新文件并重新编译

### 工程配置

add_rules("c.unity_build", {
    batchsize = 8
})
add_rules("c++.unity_build", {
    batchsize = 8
})

**Comment by SirLynix** [comment]
我最近为unity build做了一个修复，你能不能先尝试更新到xmake dev？(`xmake update -s dev`)

**Comment by waruqi** [comment]
我修了下，先更新到 dev 试试，`xmake update -s dev`

测试前，先删下 build 目录，清理掉之前的 deps 缓存。

**Comment by MaxwellGengYF** [comment]
看来可以了，没再出现这个问题。
________________________________
发件人: Jér?me Leclercq ***@***.***>
发送时间: 2022年4月2日 23:04
收件人: xmake-io/xmake ***@***.***>
抄送: Maxwell Geng ***@***.***>; Author ***@***.***>
主题: Re: [xmake-io/xmake] 链接报错不能触发重新编译 (Issue #2236)


我最近为unity build做了一个修复，你能不能先尝试更新到xmake dev？(xmake update -s dev)

―
