### ISSUE TITLE
Use specific commit hash to pin dependencies when using add_requires()

### ISSUE THREAD

**Issue by lasagnaphil** [xmake-io/xmake#2242]
### Is your feature request related to a problem? Please describe.

`add_requires()` lets you specify a Git branch (including releases/tags), but it doesn't support specific commit hashes. This is useful when you are relying on a certain commit while waiting for a new version to be released, or generally when you are using Github repos where people don't make any releases/tags.

### Describe the solution you'd like

For example, I would like to do the following:

```
add_requires("sokol a180313")
```

**Comment by lasagnaphil** [comment]
Thanks for the workaround. So in order to use a specific commit you need to explicitly version it first.

I think there's still some ergonomic issues to solve here. Xmake allows specifying branches in `add_requires` (ex. `add_requires(mypackage master)`), which conflicts with the view that every commit needs to be versioned before it could be used. If xmake allows specifying a branch without modifying the package definition, then it's natural to expect that it allows specifying a commit as well.

**Comment by waruqi** [comment]
The version selection logic for add_requires is now complex enough that I'm not considering adding support for git commits at this time.

Also, although xmake has support for master branches, I don't recommend using it either in xmake.lua.

If you want to use git commit, the solution I provided above is sufficient.

**Comment by waruqi** [comment]
I have supported it, but only support whole commit string.

```lua
add_requires("zlib adafed158c5e805f963028c7eb7c9ca6bba4ba2c")
```
