### ISSUE TITLE
on_load 获取 configvar_check_xxx 值

### ISSUE THREAD

**Issue by car520120** [xmake-io/xmake#2246]
### 你在什么场景下需要该功能？

主要是翻译 cmake 程序时使用到的
target("test")
    add_deps("foo")
    set_kind("binary")
    add_files("main.c")
    add_configfiles("config.h.in")
    configvar_check_csnippets("T_INT_SIZE", 'printf("%d", sizeof(int)); return 0;', {output = true, number = true})
    configvar_check_csnippets("T_LONG_SIZE", 'printf("%d", sizeof(long)); return 0;', {output = true, number = true})
    on_load(function (target)
            local mt = target:get("configvar")
            if 4 == mt["T_INT_SIZE"] then
                add_defines("T1")
            elseif 4 == mt["T_LONG_SIZE"] then
                add_defines("T1")
            end
    end)

### 描述可能的解决方案

configvar_check_xxx 相关的函数能增加个返回值也是可以的
local ok,res = configvar_check_csnippets("T_LONG_SIZE", 'printf("%d", sizeof(long)); return 0;', {output = true, number = true})

### 描述你认为的候选方案

或者是这种会更灵活
local xx = configvar_check_value('printf("%d", sizeof(int)); return 0;', {output = true, number = true})

**Comment by waruqi** [comment]
用 option https://xmake.io/#/zh-cn/manual/configuration_option?id=optionadd_csnippets

**Comment by car520120** [comment]
option("test")
    add_csnippets("OFF_SIZE__TT", 'printf("%d", sizeof(off_t)); return 0;', {output = true, number = true})

//在vs环境下能正常编译，但上面的获取不到off_t 大小

#include <iostream>
#include <cassert>
#include <sys/types.h>

using namespace std;
int main(int argc, char** argv)
{
    off_t ss = 1;
    cout << "hello world!"<< ss << endl;
    return 0;
}

**Comment by waruqi** [comment]
刚给你的文档里面不是写的很明显了么。。仔细看下。。
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/151335/162398022-f61fc8e8-0567-4b91-963b-85490e5dadba.png">

**Comment by car520120** [comment]
local ok,cc = check_cxsnippets({'printf("%d", sizeof(off_t)); return 0;'}, {includes = {"sys/types.h"}, tryrun=true , output = true})
 我描述的问题来的，off_t 是需要自己手动引用一下头文件才可以的，要不就是检测不到的

**Comment by waruqi** [comment]
你不是加了 `includes = {"sys/types.h"}` 么，还有什么问题么。

**Comment by car520120** [comment]
没有问题的了，谢谢的了
