### ISSUE TITLE
after_build中调用函数提示nil value

### ISSUE THREAD

**Issue by as564335sa** [xmake-io/xmake#2259]
### Xmake Version

master

### Operating System Version and Architecture

win

### Describe Bug

请教大神，我在xmake.lua中定义一个function用于生成bin文件，在target中的`after_build(createBin)`这样可以直接正常执行，但是我想不同target添加不同的操作，这样调用就不行了，提示`global 'createBin' is not callable (a nil value)`
```
after_build(function (target)
        createBin(target:targetfile())
        os.cp(target:targetfile() .. ".bin","output/" .. OUT_IQCEN_NAME .. ".bin")
        os.cp(target:targetfile() .. ".hex","output/" .. OUT_IQCEN_NAME .. ".hex") 
    end)
```
请问这是什么原因，这种方式应该怎么操作？看了半天作用域那部分文档也没搞懂

### Expected Behavior

None

**Comment by waruqi** [comment]
不要跨脚本域，描述域调用，两边作用域隔离的，脚本域走 import 导入自己的模块
