### ISSUE TITLE
Linux内核驱动编译出错

### ISSUE THREAD

**Issue by zt449569708** [xmake-io/xmake#2263]
### Xmake 版本

v2.6.4+master.26e6cc713

### 操作系统版本和架构

ubuntu 18.04

### 描述问题

```
add_requires("linux-headers", {configs = {driver_modules = true}})

target("fpga")
    add_rules("platform.linux.driver")
    add_files("*.c")
    add_packages("linux-headers")
    set_license("GPL-2.0")
```
通过上面xmake.lua编译驱动，错误日志和makefile编译日志如下：
[xmakeLog.txt](https://github.com/xmake-io/xmake/files/8474584/xmakeLog.txt)
[makefileLog.txt](https://github.com/xmake-io/xmake/files/8474585/makefileLog.txt)

其中有两个问题：
1、编译问题
2、linux-headers没找对，在日志中可以看到找的是linux-headers-5.4.0-84-generic，但实际使用的是如图：（由于系统更新，本机中存在多个内核版本）
![image](https://user-images.githubusercontent.com/6011216/163002962-889188d2-ad0a-4343-a3fe-ba0ab8701fb3.png)

### 期待的结果

找到正确的内核路径，并编译成功

**Comment by waruqi** [comment]
uname -r 出来的版本，系统里面也不一定存在。。如果非要以 uname -r 的优先，你可以提个 pr 改进下

https://github.com/xmake-io/xmake-repo/blob/6a26b7c083f4cb942a9cf7053660f40f7a1c80bb/packages/l/linux-headers/xmake.lua#L35

但是，还要确保兼容 uname -r 的指定的版本 找不到时候，能个选取到其他的 header

**Comment by zt449569708** [comment]
如果uname -r版本的linux-headers没安装，我觉得没必要再去找其他版本的，直接报错，提示没有找到对应版本的linux-headers即可。因为在实际使用的时候，就是要编译此内核版本的内核模块，如果再去找其他版本内核，编译出来的ko文件可能都运行不了。就比如，通常用makefile编译本机的内核模块都是通过uname -r来的，如果没找到，则手动去安装，如ubuntu下sudo apt-get install linux-headers-$(uname -r)
 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月13日 00:03:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xmake-io/xmake] Linux内核驱动编译出错 (Issue #2263)




 
uname -r 出来的版本，系统里面也不一定存在。。如果非要以 uname -r 的优先，你可以提个 pr 改进下
 
https://github.com/xmake-io/xmake-repo/blob/6a26b7c083f4cb942a9cf7053660f40f7a1c80bb/packages/l/linux-headers/xmake.lua#L35
 
但是，还要确保兼容 uname -r 的指定的版本 找不到时候，能个选取到其他的 header

**Comment by waruqi** [comment]
不能报错，你没这个需求 不代表其他用户没需求，编译出来的模块 又不一定非得给本机用

**Comment by zt449569708** [comment]
如果不是用于本机，那么就应该是人为的指定内核路径。就比如说，交叉编译某个平台的内核模块。


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月13日 08:17:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xmake-io/xmake] Linux内核驱动编译出错 (Issue #2263)




 
不能报错，你没这个需求 不代表其他用户没需求，编译出来的模块 又不一定非得给本机用

**Comment by waruqi** [comment]
所以你也可以人为指定编译 设置下 --sdk= 参数就行了。。。

另外即使不是本机，apt 人为指定特定版本的安装，然后走自动探测选取后直接编译也是有需求的 不一定非要xmake里面指定

**Comment by waruqi** [comment]
如果你也不想指定版本，那就按我刚说的来 提 pr 改进刚那个包，优先选取 uname -r ，然后再选其他版本，既能够保证本机完全匹配，也能完全兼容其他用户的需求，没任何负面影响 

没必要仅仅为了为了适配你这里的问题，而去break其他用户，就比如我的系统 安装的版本 就是很unname不匹配的，但是我经常其他版本做编译测试

**Comment by waruqi** [comment]
```lua
add_values("linux.driver.linux-headers", "/xxx")
```

可以自己指定 linux header 路径的

也可以配置 custom option 传入路径进去，`xmake f --linux-headers=/xxx`

参考：https://github.com/xmake-io/xmake/blob/master/tests/projects/linux/driver/hello_custom/xmake.lua
