### ISSUE TITLE
本地包供能增强和生成cmake驱动工程错误

### ISSUE THREAD

**Issue by ddkwork** [xmake-io/xmake#2268]
### Xmake 版本

2.6.4

### 操作系统版本和架构

win11

### 描述问题

本地包供能增强和生成cmake驱动工程错误

为什么使用本地包？
就像其他语言的工作空间下的预发布模块一样，对新包需要快速的重构和更多的工程引用测试bug，
每个包改一点点都要上载网络很多时候不方便，在预测阶段，再者就是某库的bug导致编译或者使用问题，作者来不及修复。

本地包遇到的困扰：

依赖可能出现的情况：
1 泄露的lib和头文件
2 仅仅是头文件
3 指定目录下的.h文件而非include目录

缺失的功能：

1 xmake package命令对应的配置接口api add_headerfiles 无法保留头文件的层级关系导致引用路径错误，
请为 xmake package 增加复制目录的接口，
猜测是在xmake-master/xmake/actions/package/local/main.lua 中的
    -- copy headers
    local srcheaders, dstheaders = target:headerfiles(headerdir)

各种case的地方增加检测：if includedirs == "include" os.cp ..... 复制完整目录

2 泄露的lib和头文件，增加复制h和lib文件的逻辑并添加到xmake.lua或者 xmake package的附加参数，
  或者能和headerronly关联？因为这种情况是没有源代码的

3 xmack生成cmake工程目前在两个驱动工程包运行时错误，其余的几个工程正常

### 期待的结果

增加打本地包

**Comment by waruqi** [comment]
看了半天，没看懂你要说啥，不同的问题不要混一起，单独开issues 

> 1 xmake package命令对应的配置接口api add_headerfiles 无法保留头文件的层级关系导致引用路径错误，

原本就支持，仔细看文档，里面有说明如何保留层级，这种基础特性怎么可能会不支持

<img width="892" alt="image" src="https://user-images.githubusercontent.com/151335/163372994-fe8752fb-eeb7-4e48-8c84-d0491b0611a6.png">

> 2 泄露的lib和头文件，增加复制h和lib文件的逻辑并添加到xmake.lua或者 xmake package的附加参数，

没看懂，header/lib 不是原本就会复制打包的么，还要干啥。。

> 3 xmack生成cmake工程目前在两个驱动工程包运行时错误，其余的几个工程正常

有错误，又不说啥错误，既不贴 log 也不贴 xmake.lua 。。我还能凭空猜出来？


自己先理下，遇到哪些哪些问题，详细描述错误，然后重开 issues，拆分问题，我没太多时间问答式去一边猜一遍查。
