### ISSUE TITLE
无法识别fortran固定格式 .for

### ISSUE THREAD

**Issue by xiangyi-wang** [xmake-io/xmake#2270]
### Xmake 版本

2.6.4

### 操作系统版本和架构

WSL2

### 描述问题

![image](https://user-images.githubusercontent.com/22881957/163502877-0fe3ae8e-db07-4a1b-a918-554b34737f49.png)
原始fortran项目使用cmake，现在我想迁移到xmake,代码90%以上是固定格式.for后缀，编译显示无法识别，需要如何设置呢，或者说目前仅支持f90以后的版本

### 期待的结果

实现固定格式和自由格式的识别

### 工程配置

```
rule("fortran.build")
target('dsscsm047')
    set_kind('binary')
    add_files('CSM_Main/*for')
    add_files('FlexibleIO/*f90')
    add_files('InputModule/*for','InputModule/*f90')
    add_files('Management/*for')
    add_files('Plant/*for')
    add_files('Soil/*for')
    add_files('SPAM/*for')
    add_files('Utilities/*for')
    add_files('Weather/*for')
```

### 附加信息和错误日志

https://github.com/DSSAT/dssat-csm-os 这是项目链接

**Comment by waruqi** [comment]
add_rules("fortran", {extensions = {".f90", ".for"}})
