### ISSUE TITLE
使用git地址进行包管理能否加入版本参数

### ISSUE THREAD

**Issue by featherfly** [xmake-io/xmake#2272]
### 你在什么场景下需要该功能？

我想自己的库直接放在git上进行版本管理
每次版本发布只需要创建一个tag就行了
需要拉取指定版本， 只要 git clone -b 1.0.0 url 拉取就好了

### 描述可能的解决方案

add_urls("https://gitlab.gnome.org/GNOME/libxml2.git") 
这样一直都是拉取最新的  

比如像下面这样(版本号是举例随便写的) 
add_urls("https://gitlab.gnome.org/GNOME/libxml2.git#1.0.0") 使用 git clone -b 1.0.0 url 拉取 
或者 
add_urls("https://gitlab.gnome.org/GNOME/libxml2.git 2.0.0") 使用 git clone -b 2.0.0 url 拉取 

个人推荐上面那个#号连接的，那个链接还是一个有效的url 

add_versions("1.0.0", "d9d14e88c6fb6d68de9ca0d1f9797477d82fc3aed613558f87ffbdbbc5ceb74a") 
add_versions("2.0.0", "b7711a1800a071674c2bf76898ae8584fc6c9643cfe933cfc1bc54361e3a6e49")

**Comment by waruqi** [comment]
原本就支持，https://github.com/xmake-io/xmake-repo/blob/master/packages/x/x264/xmake.lua
