### ISSUE TITLE
target:set_sourcedir 设置源码目录

### ISSUE THREAD

**Issue by car520120** [xmake-io/xmake#2274]
### work dir 工作目录结构
H:\WORKPRO\LEARN\TBOX\LIBRARY_WITH_CMAKELISTS
│  xmake.lua
│  
├─aa
│  └─bb
│      └─cc
│          └─foo
│              │  CMakeLists.txt
│              │  
│              └─src
│                      foo.c
│                      foo.h
│                      
└─src
        main.c
        
aa 为甲方团队目录提供的是库，当前无权修 aa目录中的任何内容只能引用他的工程或者源码文件

### xmake.lua
add_rules("mode.debug", "mode.release")
local foo_home = path.join(os.scriptdir(),"aa/bb/cc/foo")
target("foo")
    set_sourcedir(foo_home)
    add_files("src/*.c")
    add_includedirs("src",{ public = true })

target("demo")
    set_kind("binary")
    add_deps("foo")
    add_files("src/main.c")

生成vs 工程时
foo 项目源码结构如下 
└─src
          foo.c
          foo.h

去除多余的 aa/bb/cc/foo

### 描述你认为的候选方案

add_files("aa/bb/cc/foo/src/*.c",{ sourcedir = "aa/bb/cc/foo/"  })
生成 vs 工程时如上

### 其他信息

其实就是代替在 foo 目录下写工程文件
aa/bb/cc/foo/xmake.lua
生成的工程是可以达到我想要的效果的，只是每一次 git 提交代码都提示无权限特别麻烦

**Comment by waruqi** [comment]
重复了，跟 https://github.com/xmake-io/xmake/issues/1149 这个类似

暂时没时间搞。

**Comment by waruqi** [comment]
可以了 dev

源码分组我支持了。dev 版本 https://github.com/xmake-io/xmake/issues/2282
