### ISSUE TITLE
不能正常加载win7驱动

### ISSUE THREAD

**Issue by ddkwork** [xmake-io/xmake#2275]
### Xmake Version

2.6.4

### Operating System Version and Architecture

win11

### Describe Bug

手动签名驱动后加载
zwloaddriver 0xc0000024

vs2019新建kmdf工程签名加载成功

### Expected Behavior

成功加载驱动

### Project Configuration

target("sys")
add_rules("wdk.env.kmdf", "wdk.driver")
add_files("*.c")

#include <ntifs.h>

VOID DriverUnload(PDRIVER_OBJECT DriverObject) {
    UNREFERENCED_PARAMETER(DriverObject);
    DbgPrint("DriverUnload");
}

NTSTATUS DriverEntry(PDRIVER_OBJECT DriverObject, PUNICODE_STRING RegistryPath) {
    UNREFERENCED_PARAMETER(RegistryPath);
    UNREFERENCED_PARAMETER(DriverObject);
    DbgPrint("DriverEntry");
    DriverObject->DriverUnload = (PDRIVER_UNLOAD) DriverUnload;
    return STATUS_SUCCESS;
}

winver指定win7

**Comment by waruqi** [comment]
这边已经没有 wdk 环境了，也没 win 真机测试驱动加载，暂时无法调试，你只能自己对下 flags 验证下

**Comment by ddkwork** [comment]
我把全部参数都改了和正常加载的一样了，还是不行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月18日(周一) 凌晨0:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xmake-io/xmake] 不能正常加载win7驱动 (Issue #2275)




 
这边已经没有 wdk 环境了，也没 win 真机测试驱动加载，暂时无法调试，你只能自己对下 flags 验证下

**Comment by ddkwork** [comment]
要不您远程操作我机器吧，我把之前的驱动工程移植到xmake了五六个了，发现编译都挺好，然后在虚拟机签名准备加载，发现一个都加载不了，很不错，xmake管理源代码



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月18日(周一) 凌晨0:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xmake-io/xmake] 不能正常加载win7驱动 (Issue #2275)




 
这边已经没有 wdk 环境了，也没 win 真机测试驱动加载，暂时无法调试，你只能自己对下 flags 验证下

**Comment by waruqi** [comment]
没时间
