### ISSUE TITLE
无法编译静态可执行文件

### ISSUE THREAD

**Issue by junknet** [xmake-io/xmake#2276]
### Xmake Version

v2.6.4+master.8dfd4c9

### Operating System Version and Architecture

ArchLinux

### Describe Bug

[ 25%]: compiling.release src/main.cpp
/home/junknet/Downloads/gcc-arm-10.3-2021.07-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-gcc -c -static -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG -o build/.objs/test/linux/x86_64/release/src/main.cpp.o src/main.cpp
[ 50%]: linking.release test
/home/junknet/Downloads/gcc-arm-10.3-2021.07-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-g++ -o build/linux/x86_64/release/test build/.objs/test/linux/x86_64/release/src/main.cpp.o -s

在连接阶段编译参数 少了 -static
xmake.conf 中也设置了 cxxflags = "-static"

### Expected Behavior

生成单一静态可执行文件

**Comment by waruqi** [comment]
> 在连接阶段编译参数 少了 -static
xmake.conf 中也设置了 cxxflags = "-static"

。。。这不是 链接器 flags 么，你设置到 cxxflags 给编译器怎么可能有效。。

另外，设置到 xmake.conf 是什么鬼，不在 xmake.lua 设置，直接改缓存的 xmake.conf? = =

用 add_ldflags("-static", {force = true}) 在 xmake.lua 设置
