### ISSUE TITLE
patches in git submodules are not cleaned on rebuilding

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2289]
### Xmake Version

2.6.4

### Operating System Version and Architecture

Debian 11.3

### Describe Bug

https://github.com/xmake-io/xmake/discussions/2280

在libtorch这个包安装过程中对submodule的文件打了patch，仅仅运行git reset --hard v1.11.0是无法清除patch的，导致后续apply patch 失败。在清理的过程中应该对submodule也进行清理。

### Expected Behavior

重新构建复用已经clone的源码时先清理submodule

**Comment by waruqi** [comment]
修了，但是还没测试过

**Comment by xq114** [comment]
我这边测试ok
