### ISSUE TITLE
add_filegroups 能同步支持一下头文件吗?

### ISSUE THREAD

**Issue by car520120** [xmake-io/xmake#2290]
### 你在什么场景下需要该功能？

target("librapidxml")
    set_kind("headeronly")
    add_includedirs(lib_inc,{public = true})
    add_filegroups("rapidxml", {rootdir = lib_inc})
    add_headerfiles(path.join(lib_inc,"**.hpp"))

生成vs工程时希望和cpp文件一样

### 描述可能的解决方案

target("librapidxml")
    set_kind("headeronly")
    add_includedirs(lib_inc,{public = true})
    add_filegroups("rapidxml", {rootdir = lib_inc,headerfiles={'src/**.hpp'}})
    -- add_headerfiles(path.join(lib_inc,"**.hpp"))

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/issues/2291 重复
