### ISSUE TITLE
仅头文件工程生成vs工程出错

### ISSUE THREAD

**Issue by car520120** [xmake-io/xmake#2291]
### Xmake 版本

2.6.4

### 操作系统版本和架构

win10

### 描述问题

target("librapidxml")
    set_kind("headeronly")
    add_includedirs(lib_inc,{public = true})
    add_filegroups("librapidxml", {rootdir = lib_inc})
    add_headerfiles(path.join(lib_inc,"**.hpp"))

### 期待的结果

能正常生成vs工程

**Comment by car520120** [comment]
2.6.4 + github 上的脚本才有 add_filegroups 功能

**Comment by waruqi** [comment]
原本就支持，以后凡事先贴 error logs 。。

目前我测试，就 cuda 那块有点干扰，我修了下，其他没遇到什么问题

**Comment by car520120** [comment]
原因是路径的问题来的  绝对路径中含有 \.. 所以出错的了
D:\WorkPro\learn\coro\libcopp\src\libcotask D:\WorkPro\learn\coro\libcopp\xmgr\..\include\libcotask\this_task.h
之所以会这样是因为
target:add("files","..\include\libcotask\this_task.h")
也不能添加 rc 文件
target:add("files","..\include\libcotask\this_task.rc")

**Comment by waruqi** [comment]
.h 去加到 files 干嘛，源文件编译才需要。。走 add_headerfiles 。。

另外，开头的 xmake.lua 跟你现在的有完全不一样。。反馈问题前，请先提供 完整 xmake.lua 和 错误输出


.. 原本就支持

**Comment by car520120** [comment]
PS D:\WorkPro\learn\coro\libcopp> xmake project  -k vs2022 -v
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for dmd ... no
checking for ldc2 ... no
checking for gdc ... no
checking for zig ... no
checking for zig ... no
checking for with_os_tool ... masm
checking for with_os_abi ... ms
checking for with_os_platform ... x86_64
checking for copp_env ... no
checking for with_os_format ... pe
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for link.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\link.exe
checking for the linker (ld) ... link.exe
> checking for c++ includes(Windows.h, cstring, cstdlib, stdio.h)
> checking for c++ snippet(                )
> checking for c++ includes(sys/resource.h, sys/time.h, unistd.h, sys/types.h, fcntl.h, sys/mman.h, stdio.h)
> checking for c++ snippet(printf("%d", 1);)
generating build\config\libcopp\utils\config\libcopp_build_features.h.in to build\config\libcopp\utils\config\libcopp_build_features.h ..
checking for git ... ok
generating build\config\libcopp\utils\config\libcopp_build_features.h.in ... cache
checking for link.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\link.exe
checking for the shared library linker (sh) ... link.exe
configure
{
    ndk_stdcxx = true
    vs = 2022
    vs_sdkver = 10.0.19041.0
    with_std_experimental_coroutine = false
    kind = static
    with_exception_ptr = false
    with_std_coroutine = false
    host = windows
    with_valgrind = false
    copp_env = false
    with_segmented = false
    with_threads = false
    with_os_tool = masm
    with_cleanup_manager = true
    with_fcontext_tsx = true
    ccache = true
    buildir = build
    with_os_platform = x86_64
    mode = release
    with_exception = false
    arch = x64
    with_rtti = false
    with_os_abi = ms
    with_os_format = pe
    plat = windows
}
using project kind vs2022
checking for debug.x86 ...
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX86\x86\cl.exe
checking for Microsoft Visual Studio (x86) version ... 2022
checking for dmd ... no
checking for ldc2 ... no
checking for gdc ... no
checking for zig ... no
checking for zig ... no
checking for with_os_tool ... masm
checking for with_os_abi ... ms
checking for with_os_platform ... i386
checking for copp_env ... no
checking for with_os_format ... pe
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX86\x86\cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for link.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX86\x86\link.exe
checking for the linker (ld) ... link.exe
> checking for c++ includes(Windows.h, cstring, cstdlib, stdio.h)
> checking for c++ snippet(                )
> checking for c++ includes(sys/resource.h, sys/time.h, unistd.h, sys/types.h, fcntl.h, sys/mman.h, stdio.h)
> checking for c++ snippet(printf("%d", 1);)
checking for link.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX86\x86\link.exe
checking for the shared library linker (sh) ... link.exe
generating build\config\libcopp\utils\config\libcopp_build_features.h.in to build\config\libcopp\utils\config\libcopp_build_features.h ..
checking for git ... ok
generating build\config\libcopp\utils\config\libcopp_build_features.h.in ... cache
checking for C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX86\x86\cl.exe ... ok
checking for flags (-FS -Fd) ... ok
checking for flags (-Od) ... ok
checking for debug.x64 ...
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for dmd ... no
checking for ldc2 ... no
checking for gdc ... no
checking for zig ... no
checking for zig ... no
checking for with_os_tool ... masm
checking for with_os_abi ... ms
checking for with_os_platform ... x86_64
checking for copp_env ... no
checking for with_os_format ... pe
> checking for c++ includes(Windows.h, cstring, cstdlib, stdio.h)
> checking for c++ snippet(                )
> checking for c++ includes(sys/resource.h, sys/time.h, unistd.h, sys/types.h, fcntl.h, sys/mman.h, stdio.h)
> checking for c++ snippet(printf("%d", 1);)
checking for link.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\link.exe
checking for the shared library linker (sh) ... link.exe
generating build\config\libcopp\utils\config\libcopp_build_features.h.in to build\config\libcopp\utils\config\libcopp_build_features.h ..
checking for git ... ok
generating build\config\libcopp\utils\config\libcopp_build_features.h.in ... cache
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\cl.exe ... ok
checking for flags (-FS -Fd) ... ok
checking for flags (-Od) ... ok
checking for release.x86 ...
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX86\x86\cl.exe
checking for Microsoft Visual Studio (x86) version ... 2022
checking for dmd ... no
checking for ldc2 ... no
checking for gdc ... no
checking for zig ... no
checking for zig ... no
checking for with_os_tool ... masm
checking for with_os_abi ... ms
checking for with_os_platform ... i386
checking for copp_env ... no
checking for with_os_format ... pe
> checking for c++ includes(Windows.h, cstring, cstdlib, stdio.h)
> checking for c++ snippet(                )
> checking for c++ includes(sys/resource.h, sys/time.h, unistd.h, sys/types.h, fcntl.h, sys/mman.h, stdio.h)
> checking for c++ snippet(printf("%d", 1);)
checking for link.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX86\x86\link.exe
checking for the shared library linker (sh) ... link.exe
generating build\config\libcopp\utils\config\libcopp_build_features.h.in to build\config\libcopp\utils\config\libcopp_build_features.h ..
checking for git ... ok
generating build\config\libcopp\utils\config\libcopp_build_features.h.in ... cache
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX86\x86\cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX86\x86\cl.exe ... ok
checking for flags (-Ox -fp:fast) ... ok
checking for flags (-DNDEBUG) ... ok
checking for release.x64 ...
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for dmd ... no
checking for ldc2 ... no
checking for gdc ... no
checking for zig ... no
checking for zig ... no
checking for with_os_tool ... masm
checking for with_os_abi ... ms
checking for with_os_platform ... x86_64
checking for copp_env ... no
checking for with_os_format ... pe
> checking for c++ includes(Windows.h, cstring, cstdlib, stdio.h)
> checking for c++ snippet(                )
> checking for c++ includes(sys/resource.h, sys/time.h, unistd.h, sys/types.h, fcntl.h, sys/mman.h, stdio.h)
> checking for c++ snippet(printf("%d", 1);)
checking for link.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\link.exe
checking for the shared library linker (sh) ... link.exe
generating build\config\libcopp\utils\config\libcopp_build_features.h.in to build\config\libcopp\utils\config\libcopp_build_features.h ..
checking for git ... ok
generating build\config\libcopp\utils\config\libcopp_build_features.h.in ... cache
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\cl.exe ... ok
checking for flags (-Ox -fp:fast) ... ok
checking for flags (-DNDEBUG) ... ok
create ok!
warning: cannot match target(libcopp).add_files("..\src\libcopp\fcontext\asm\make_x86_64_ms_pe_masm.asm") at .\xmgr\libcopp.lua:256
warning: cannot match target(libcopp).add_files("..\src\libcopp\fcontext\asm\jump_x86_64_ms_pe_masm.asm") at .\xmgr\libcopp.lua:256
warning: cannot match target(libcopp).add_files("..\src\libcopp\fcontext\asm\ontop_x86_64_ms_pe_masm.asm") at .\xmgr\libcopp.lua:256
warning: cannot match target(libcopp).add_files("..\src\libcopp\stack\*.cpp") at .\xmgr\libcopp.lua:260
warning: cannot match target(libcopp).add_files("..\src\libcopp\stack\allocator\stack_allocator_memory.cpp") at .\xmgr\libcopp.lua:261
warning: cannot match target(libcopp).add_files("..\src\libcopp\stack\allocator\stack_allocator_malloc.cpp") at .\xmgr\libcopp.lua:262
warning: cannot match target(libcopp).add_files("..\src\libcopp\stack\**_windows.cpp") at .\xmgr\libcopp.lua:265
warning: please use the new vs project generator, .e.g xmake project -k vsxmake
warning: cannot match target(libcopp).add_files("..\src\libcopp\fcontext\asm\make_i386_ms_pe_masm.asm") at .\xmgr\libcopp.lua:256
warning: cannot match target(libcopp).add_files("..\src\libcopp\fcontext\asm\jump_i386_ms_pe_masm.asm") at .\xmgr\libcopp.lua:256
warning: cannot match target(libcopp).add_files("..\src\libcopp\fcontext\asm\ontop_i386_ms_pe_masm.asm") at .\xmgr\libcopp.lua:256

**Comment by car520120** [comment]
add_rules("mode.debug", "mode.release", "asm")

local PROJECT_LIBCOPP_SYSLIB_LINK_NAMES = false
local LIBCOTASK_ENABLE = true
local CMAKE_USE_PTHREADS_INIT = false

local lib_path = path.join("..")
local lib_src = path.join(lib_path,"src")
local lib_inc = path.join(lib_path,"include")

local copp_inc = path.join(lib_inc,"libcopp")
local copp_src = path.join(lib_src,"libcopp")
local cotask_inc = path.join(lib_inc,"libcotask")
local cotask_src = path.join(lib_src,"libcotask")


local cfg_inc = path.join("$(buildir)","config")
local cfg_copp = path.join(cfg_inc,"libcopp","utils","config")
local cfg_in = path.join(lib_inc,"libcopp","utils","config","libcopp_build_features.h.in")
local cfg_fn = path.join(cfg_copp,"libcopp_build_features.h.in")


option("copp_env")
    before_check(function(op)
        if os.isfile(cfg_fn) then
            return
        end

        if not os.isdir(cfg_copp) then
            os.mkdir(cfg_copp)
        end

        os.cp(path.join(lib_inc,"*"),cfg_inc)

        import("config_c2x", {alias = "cfg"})
       
        cfg.ce2x(cfg_in,cfg_fn)
    end)
option_end()

option("with_std_coroutine")
    set_default(false)
    set_showmenu(true)
    
option("with_std_experimental_coroutine")
    set_default(false)
    set_showmenu(true)

option("with_exception")
    set_default(false)
    set_showmenu(true)

option("with_exception_ptr")
    set_default(false)
    set_showmenu(true)

option("with_rtti")
    set_default(false)
    set_showmenu(true)

option("with_cleanup_manager")
    set_default(true)
    set_showmenu(true)

option("with_threads")
    set_default(false)
    set_showmenu(true)
    add_links("pthread")

option("with_fcontext_tsx")
    set_default(true)
    set_showmenu(true)

option("with_os_platform")
    set_showmenu(true)
    set_values("arm","arm64","i386","x86_64","combined","mips","ppc32","ppc64")
    on_check(function(op)
        if is_arch("x64") then
            if is_plat("windows","linux","macosx") then
                op:set_value("x86_64")
            end
        elseif is_arch("x86","x86_64","i386") then
            if is_plat("windows","linux","macosx") then
                op:set_value("i386")
            end
        elseif is_arch("arm64") then
            op:set_value("arm64")
        elseif is_arch("arm*") then
            op:set_value("arm")
        end
    end)

option("with_os_abi")
    set_showmenu(true)
    set_values("sysv","aapcs","mips","o32","ms")
    on_check(function(op)
        if is_plat("windows") then
            op:set_value("ms")
        elseif  is_plat("linux") then
            op:set_value("sysv")
        elseif  is_plat("macosx") then
            op:set_value("o32")
        end
    end)

option("with_os_format")
    set_showmenu(true)
    set_values("elf","pe","macho","xcoff")
    on_check(function(op)
        if is_plat("windows") then
            op:set_value("pe")
        elseif  is_plat("linux") then
            op:set_value("elf")
        elseif  is_plat("macosx") then
            op:set_value("macho")
        end
    end)


option("with_os_tool")
    set_showmenu(true)
    set_values("gas","armasm","masm")
    on_check(function(op)
        if is_plat("windows") then
            op:set_value("masm")
        elseif  is_plat("linux","macosx") then
            op:set_value("gas")
        else
            op:set_value("armasm")
        end
    end)

option("with_segmented")
    set_default(false)
    set_showmenu(true)

option("with_valgrind")
    set_default(false)
    set_showmenu(true)



option_end()

-- xmake f --menu
-- select with option
local op_maps = {
    with_std_coroutine = "LIBCOPP_MACRO_ENABLE_STD_COROUTINE",
    with_std_experimental_coroutine = "LIBCOPP_MACRO_USE_STD_EXPERIMENTAL_COROUTINE",
    with_exception = "LIBCOPP_MACRO_ENABLE_EXCEPTION",
    with_exception_ptr = "LIBCOPP_MACRO_ENABLE_STD_EXCEPTION_PTR",
    with_rtti = "LIBCOPP_MACRO_ENABLE_RTTI",
    with_cleanup_manager = "LIBCOTASK_MACRO_AUTO_CLEANUP_MANAGER",
    with_threads = "THREAD_TLS_USE_PTHREAD",
    with_fcontext_tsx = "LIBCOPP_FCONTEXT_USE_TSX"
}


local enable_cotask = true

target("libcopp")
    set_kind("shared")
    add_options("copp_env")
    add_filegroups("include", {rootdir = path.relative(copp_inc)})
    add_filegroups("src", {rootdir = path.relative(copp_src)})
    add_files(path.join(copp_src,"coroutine","*.cpp"))
    add_files(path.join(copp_src,"utils","*.cpp"))
    add_headerfiles(path.join(copp_inc,"**.hpp"),{prefixdir = "libcopp"})
    
    add_options("with_os_platform","with_os_abi","with_os_format","with_os_tool","with_segmented","with_valgrind")
    for k,_ in pairs(op_maps) do
        add_options(k)
    end

    add_configfiles(cfg_fn)
    set_configdir(cfg_copp)
    add_includedirs(cfg_inc,{ public = true })
    set_configvar("LIBCOPP_VERSION_MAJOR",1)
    set_configvar("LIBCOPP_VERSION_MINOR",5)
    set_configvar("LIBCOPP_VERSION_PATCH",0)
    set_configvar("LIBCOPP_VERSION","1.5.0")

    add_defines("LIBCOPP_API_COPP_NATIVE=1")
    if enable_cotask then
        set_configvar("LIBCOTASK_MACRO_ENABLED",1)
    end

    on_load(function(target)
        import("lib.detect.check_cxsnippets")
        if "shared" == target:get("kind") then
            target:add("defines","LIBCOPP_API_DLL=1")
        end

        for k,v in pairs(op_maps) do
            if has_config(k) then
                target:set("configvar",v,1)
            end
        end

        if is_plat("windows") then
            local fiber_opt =  { sourcekind = "cxx" ,tryrun =true ,output = true}
            fiber_opt.includes ={
                 "Windows.h",
                 "cstring",
                 "cstdlib"
            }
            fiber_opt.configs = {
                defines = {"WIN32_LEAN_AND_MEAN"}
            }

            local fiber_code = [[
                auto pSwitchToFiber = SwitchToFiber;
                auto pCreateFiber = CreateFiber;
                auto pConvertThreadToFiber = ConvertThreadToFiber;
                printf("%d",1);
                return 0;
            ]]

            local fiber_isok = check_cxsnippets(fiber_code,fiber_opt)
            if fiber_isok then
                target:set("configvar","LIBCOPP_MACRO_ENABLE_WIN_FIBER",1)
            end
            
        end

        if is_config("toolchain", "clang") then

        end

        local concat = function(mt,sep)
            local ss = ""
            if sep then
                local c = #mt
                ss = mt[1]
                for i = 2,c,1 do
                    ss = ss .. sep .. mt[i]
                end
            else
                for _,s in pairs(mt) do
                    ss = ss .. s
                end
            end
            return ss
        end
        -- asm  add files
        local asm_plat = val("with_os_platform")
        local asm_abi = val("with_os_abi")
        local asm_format = val("with_os_format")
        local asm_tool = val("with_os_tool")
        local asm_exname = "gas" == asm_tool and ".S" or ".asm"
        local asm_fn = concat({asm_plat,asm_abi,asm_format,asm_tool},"_")
        local asm_src = path.join(copp_src,"fcontext","asm") 
        local make_fn = path.join(asm_src,concat({"make_",asm_fn,asm_exname}))
        local jump_fn = path.join(asm_src,concat({"jump_",asm_fn,asm_exname}))
        local ontop_fn = path.join(asm_src,concat({"ontop_",asm_fn,asm_exname}))
        target:add("files",make_fn,jump_fn,ontop_fn)

        -- stack add files
        local stack_src = path.join(copp_src,"stack") 
        target:add("files",path.join(stack_src,"*.cpp"))
        target:add("files",path.join(stack_src,"allocator","stack_allocator_memory.cpp"))
        target:add("files",path.join(stack_src,"allocator","stack_allocator_malloc.cpp"))

        if is_plat("windows") then
            target:add("files",path.join(stack_src,"**_windows.cpp"))
            target:set("configvar","LIBCOPP_MACRO_SYS_WIN",1)
        end

        local stack_opt =  { sourcekind = "cxx" ,tryrun =true ,output = true}
        stack_opt.includes = {
            "sys/resource.h",
            "sys/time.h",
            "unistd.h",
            "sys/types.h",
            "fcntl.h",
            "sys/mman.h"
        }

        local posix_isok = check_cxsnippets('printf("%d", 1); return 0;',stack_opt)
        if  posix_isok then
            target:add("files",path.join(stack_src,"**_posix.cpp"))
            target:set("configvar","LIBCOPP_MACRO_SYS_POSIX",1)
        end 

        if is_plat("linux") and is_config("toolchain","gcc") and has_config("with_segmented") then
            target:add("cxxflags","-fsplit-stack")
            target:set("configvar","LIBCOPP_MACRO_USE_SEGMENTED_STACKS",1)
            target:add("files",path.join(stack_src,"allocator","stack_allocator_split_segment.cpp"))
        end
        if has_config("with_valgrind") then
            local valgrind_opt =  { sourcekind = "cxx",tryrun =true ,output = true }
            valgrind_opt.includes = {
                "valgrind/valgrind.h"
            }
            local valgrind_isok = check_cxsnippets('printf("%d", 1); return 0;',valgrind_opt) 
            if valgrind_isok then
                target:set("configvar","LIBCOPP_MACRO_USE_VALGRIND",1)
            end
        end
    end)
    

target("cotask")
    set_default(enable_cotask)
    add_deps("libcopp")
    set_kind("shared")
    add_filegroups("include", {rootdir = path.relative(cotask_inc)})
    add_filegroups("src", {rootdir = path.relative(cotask_src)})
    add_files(path.join(cotask_src,"impl","*.cpp"))
    add_headerfiles(path.join(cotask_inc,"**.h"),{prefixdir = "libcotask"})
    add_defines("LIBCOPP_API_COTASK_NATIVE=1")
    on_load(function(target)
        if "shared" == target:get("kind") then
            target:add("defines","LIBCOPP_API_DLL=1")
        end
    end)

**Comment by car520120** [comment]
local lib_path = path.join(os.scriptdir(),"..")  如果接成这样就可以正常的

**Comment by car520120** [comment]
config_c2x.lua
https://github.com/owent/libcopp
```
local function check_cmakestr_ex(s)
    if "#cmakedefine" == string.sub(s,1,12) then
        local mt = {}
        for w  in s:gmatch("([^%s]+)") do
            table.insert(mt,w)
        end
        
        local ss = nil
        return table.concat({"${define ",mt[2],"}\n"}) 
    else
        local ms,mn = string.gsub(s,"@(.-)@","${%1}")
        if 0 < mn then
            return ms .. "\n"
        end
    end
    return s .. "\n"
end

local function check_cmakestr(s)
    local mt = {}
    local is_cmake = false
    for w  in s:gmatch("([^%s]+)") do
        table.insert(mt,w)
    end
    if "#cmakedefine" == mt[1] then
        local ss = nil
        return table.concat({"${define ",mt[2],"}\n"}) 
    else
        local ms,mn = string.gsub(s,"@(.-)@","${%1}")
        if 0 < mn then
            return ms .. "\n"
        end
    end
    return s .. "\n"
end

local function check_undef(s)
    return string.gsub(s,"^[%s]*#undef (.-)[%s]*[.]*$","${%1}") .. "\n"
end

function src2dst(src,dst,to)
    f = io.open (dst,"w+")
    for s in io.lines(src) do
        local ss =to(s)
        f:write(ss)
    end
    f:close()
end

function ce2x(src,dst)
    src2dst(src,dst,check_cmakestr_ex)
end

function c2x(src,dst)
    src2dst(src,dst,check_cmakestr)
end

function u2x(src,dst)
    src2dst(src,dst,check_undef)
end

function main(src,dst)
    c2x(src,dst)
end
```
