### ISSUE TITLE
导入cmake库找不到头文件

### ISSUE THREAD

**Issue by xixioba** [xmake-io/xmake#2300]
### Xmake 版本

2.6.4+202203070653

### 操作系统版本和架构

macos monterey 12.3.1

### 描述问题

我预先编译了cmake库，这些库只提供xxx-config.cmake，即使用[cmake(find_package config model)](https://cmake.org/cmake/help/latest/command/find_package.html#basic-signature)，
参考xmake教程，似乎全部使用Module mode，于是参考 #1632 和 #2160 编写如下xmake.lua
<img width="715" alt="截屏2022-04-23 13 53 30" src="https://user-images.githubusercontent.com/34228625/164880678-257c103b-50ed-4d43-95a3-328e6e3bec7e.png">
确认fastrtps-config.cmake中include路径正确，且使用cmake编译工程正确，请问xmake导入cmake库还需要补充什么？

另外，是否有输出可以确认xmake.lua中 add_requires的结果是类似`xmake l find_package protobuf`
<img width="449" alt="截屏2022-04-23 14 01 14" src="https://user-images.githubusercontent.com/34228625/164882240-266c564d-bb5a-486c-9ab7-7c4fd1394add.png">

同时遇到另一个问题，如果使用`xmake clean -a`清除缓存后，再次`xmake'会提示找不到库

<img width="536" alt="截屏2022-04-23 14 09 28" src="https://user-images.githubusercontent.com/34228625/164882498-148e9a4d-c5ad-4005-b5ff-9c1c0ff64525.png">

### 期待的结果

生成bin文件

**Comment by waruqi** [comment]
xmake f -c -vD 强制触发下检测，然后自己看下详细输出检查下。。还是不行，自己在 https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/manager/cmake/find_package.lua 加点 print 调下

**Comment by xixioba** [comment]
以下是xmake f -c -vD的最小示例，设置env后可以找到xxx-config.cmake，但是仍然报错
<img width="1063" alt="截屏2022-04-23 23 20 17" src="https://user-images.githubusercontent.com/34228625/164912423-1c02f55c-62c5-4355-99fd-f69d306f7bfa.png">

**Comment by waruqi** [comment]
哦 那来个 pr 过来呢？ executable 的名字可以加个前缀啥的区分下 `test_` .. name

**Comment by xixioba** [comment]
我并不确定有没有完全修好- - )，似乎解决了我的问题，包括依赖的动态库再依赖问题，我稍后提一个pr

**Comment by xixioba** [comment]
#2301

**Comment by waruqi** [comment]
谢谢，我稍微改了下，已经 merge
