### ISSUE TITLE
能否增加一个前置的脚本域

### ISSUE THREAD

**Issue by car520120** [xmake-io/xmake#2302]
### 你在什么场景下需要该功能？

带有配置检查过多的项目
add_configfiles(cfg_fn)
set_configdir(cfg_dir)
每次检查都特别耗时，因些想到前置一个脚本域作为配置的因为有部分 api 只能在脚本域使用 io.cat 等等

### 描述可能的解决方案

```lua
local cfg =  on_start(function(config)
    local config = config or {}
    set_config("xxx")
    get_config("xx")
    io.writefile("xxx")
    os.cp("xxx")
    config.isok = os.isfile("xxxx")
    return config
end)

if cfg.isok then
    option("xxxx")
end


target("libcpr")
    set_kind("shared")
    add_deps("libcurl")
    set_group("lib3rd")
    add_includedirs(lib_src)
    add_includedirs(lib_inc,{public = true})
    add_filegroups("src", {rootdir = path.relative(lib_src)})
    add_headerfiles(path.join(lib_inc,"**.h"))
    add_files(path.join(lib_src,"**.cpp"))
```

**Comment by waruqi** [comment]
option 可以自己 on_check 重写检测规则

**Comment by car520120** [comment]
option 是可以代替部分，但达不到上面的，例如
local lib_inc = "include"
option("tt")
    on_check(function(op)
        import("core.project.config")
        local mm = config.buildir()
        io.writefile(".xmake/build.config",mm)
    end)

io.cat(".xmake/build.config")
print("ggg",get_config("abc.cc"))



print("ccc  ",get_config("buildir"))

target("librapidxml")
    add_options("tt")
    set_kind("headeronly")
    -- set_default(false)
    add_includedirs(lib_inc,{public = true})
    -- add_filegroups("librapidxml", {rootdir = lib_inc})
    add_headerfiles("include/*.hpp")
    if has_config("tt") then
        print("x *** tt")
       add_includedirs(lib_inc,{public = true})
    end

**Comment by waruqi** [comment]
1. 不要在描述调用 io.cat 。。不要做任何复杂的操作，不要调用 print 
2. has_config 可以在描述域用
3. rc 可以在 on_load 脚本域添加
4. 任何跟 has_config 只能在 option 的 on_check 操作，其他方案一概不支持，也不会考虑。。内部实现很复杂，不是所有需求都能实现。
