### ISSUE TITLE
add_filegroups  多组配对时

### ISSUE THREAD

**Issue by car520120** [xmake-io/xmake#2303]
### Xmake 版本

2.6.4 

### 操作系统版本和架构

win10

### 描述问题

d:/abc/456/789/1.cc
d:/def/456/789/2.cc

add_filegroups("src",{rootdir="d:/abc/456"})  
add_filegroups("src",{rootdir="d:/def/456"})  
path.absolute(rootdir, scriptdir) 会产生  ../../789/1.cc
导致出错
```lua
-- make filter
function _make_filter(filepath, target, vcxprojdir)
    local filter
    local filegroups = target.filegroups
    if filegroups then
        -- @see https://github.com/xmake-io/xmake/issues/2282
        filepath = path.absolute(filepath)
        local scriptdir = target.scriptdir
        local filegroups_extraconf = target.filegroups_extraconf or {}
        for _, filegroup in ipairs(filegroups) do
            local extraconf = filegroups_extraconf[filegroup] or {}
            local rootdir = extraconf.rootdir
            assert(rootdir, "please set root directory, e.g. add_filegroups(%s, {rootdir = 'xxx'})", filegroup)
            if not path.is_absolute(rootdir) then
                rootdir = path.absolute(rootdir, scriptdir)
            end
            local fileitem = path.relative(filepath, rootdir)
            local files = extraconf.files or "**"
            local mode = extraconf.mode
            for _, filepattern in ipairs(files) do
                filepattern = path.pattern(path.translate(filepattern))
                if fileitem:match(filepattern) and '.' ~= fileitem:sub(1,1) then
                    if mode == "plain" then
                        filter = path.normalize(filegroup)
                    else
                        -- file tree mode (default)
                        filter = path.normalize(path.join(filegroup, path.directory(fileitem)))
                    end
                    if filter and filter == '.' then
                        filter = nil
                    end
                    break
                end
            end
        end
    end
```

### 期待的结果

改一下判断方式就能达到，主要是不熟识正则
if fileitem:match(filepattern) and '.' ~= fileitem:sub(1,1) then
正则还是原来lua的正则库吗？

**Comment by waruqi** [comment]
> path.absolute(rootdir, scriptdir) 会产生 ../../789/1.cc
导致出错

还是没说出啥错？具体错误截图。。另外这个肯定不可能会产生这个。。path.absolute 只会生成绝对路径。。确定不是下面的 path.relative？

**Comment by waruqi** [comment]
另外，给个完整可复现的 demo 工程

**Comment by car520120** [comment]
local fileitem = path.relative(filepath, rootdir)
local fileitem = path.relative(”d:/def/456/789/2.cc“, "d:/abc/456")
fileitem  =  "../../def/456/789/2.cc"
这步出错的了，你自己写个简单的脚本测试一下就知道的了

**Comment by waruqi** [comment]
> local fileitem = path.relative(”d:/def/456/789/2.cc“, "d:/abc/456")
> fileitem = "../../def/456/789/2.cc"
> 这步出错的了，你自己写个简单的脚本测试一下就知道的了
> 

没感觉有啥问题，这不是很正常么，你源码路径在 `d:/def/456/789/2.cc` 却要指定到另外一个完全无关的 `d:/abc/456` 根目录，当然转出来这样了。。一个是 d:/def 一个是 d:adc ，根目录都不匹配。。


> 
> d:/abc/456/789/1.cc
> d:/def/456/789/2.cc
> 
> add_filegroups("src",{rootdir="d:/abc/456"})
> add_filegroups("src",{rootdir="d:/def/456"})
> path.absolute(rootdir, scriptdir) 会产生 ../../789/1.cc

再看你之前这个设置，1.cc 在 d:/adc 而 2.cc 在 d:def 。。两个文件完全两个不同的根目录，却要设置 到相同的 src 分组，rootdir 又设置到不同的目录，并且也没指定 files 匹配，那么这两个不同的 rootdir ，就是冲突的，等于只覆盖生效了 `add_filegroups("src",{rootdir="d:/def/456"})`

xmake 怎么知道 哪个 rootdir 对 1.cc ，哪个 rootdir 对 2.cc?

不同的源文件组，用 {files = ""} 匹配，文档有说明，否则默认就是 `**` 全量匹配。

**Comment by car520120** [comment]
我以为是截取路径匹配的，所以才会写两个 add_filegroups 不带 files 的误解的了！最后能支持一下 add_filegroups("",{rootdir="d:/def/456"}) 当是空时就是删除  d:/def/456
