### ISSUE TITLE
clang编译cuda编写的cu文件

### ISSUE THREAD

**Issue by zt449569708** [xmake-io/xmake#2305]
### Xmake 版本

v2.6.4

### 操作系统版本和架构

ubuntu

### 描述问题

由于某些原因，需要使用clang编译cuda编写的cu文件，运行`xmake f --toolchain=clang`，执行`xmake -rv`后，提示`error: unknown source file: main.cu`，但是看`xmake/toolchains/cuda`下的xmake.lua文件（如图），应该是支持clang的，所以想问一下，我应该怎么来使用？谢谢。我通过clang命令单独来编译cu文件是没问题的。
![image](https://user-images.githubusercontent.com/6011216/164969661-718b739c-da21-495b-a93b-92eaa36968bd.png)

### 期待的结果

clang能编译cu文件

**Comment by waruqi** [comment]
xmake f --cu-ccbin=clang

**Comment by zt449569708** [comment]
> xmake f --cu-ccbin=clang

这样用也不行。
![image](https://user-images.githubusercontent.com/6011216/164977530-2a6090ba-acac-4e73-93ab-2041a2e61a6c.png)

**Comment by waruqi** [comment]
nvcc 没装？

**Comment by zt449569708** [comment]
> nvcc 没装？

没装，实际上是用的一个国产GPU，兼容cuda，只能使用clang编译（查资料，实际上nvidia gpu的cuda程序也可以只用clang来编译）。或者有没有自定义的方式来编译cuda？

**Comment by waruqi** [comment]
编译器可以用 `xmake f --cu=clang` 切，但是 linker 目前还是依赖 nvcc 的。。我没试过改成 clang 是否可行，

你可以 linker 一起切下试试，`xmake f --cu=clang --culd=clang -c` 试试，不行 那就是不支持

**Comment by zt449569708** [comment]
试了不得行，想问一下，有没有建议怎么修改？主要是用习惯xmake，不想换其他工具。


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月24日 22:23:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xmake-io/xmake] clang编译cuda编写的cu文件 (Issue #2305)




 
编译器可以用 xmake f --cu=clang 切，但是 linker 目前还是依赖 nvcc 的。。我没试过改成 clang 是否可行，
 
你可以 linker 一起切下试试，xmake f --cu=clang --culd=clang -c 试试，不行 那就是不支持

**Comment by zt449569708** [comment]
错误提示，还是unknown source file
 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月24日 22:23:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xmake-io/xmake] clang编译cuda编写的cu文件 (Issue #2305)




 
编译器可以用 xmake f --cu=clang 切，但是 linker 目前还是依赖 nvcc 的。。我没试过改成 clang 是否可行，
 
你可以 linker 一起切下试试，xmake f --cu=clang --culd=clang -c 试试，不行 那就是不支持

**Comment by waruqi** [comment]
-vD 看下，应该还是连 clang 都没检测到，确认下 clang 是否在 path

```console
xmake f --cu=clang --culd=clang -cvD
xmake -rvD
```

**Comment by zt449569708** [comment]
> -vD 看下，应该还是连 clang 都没检测到，确认下 clang 是否在 path
> 
> ```
> xmake f --cu=clang --culd=clang -cvD
> xmake -rvD
> ```
> 
> 另外，不要 root 搞，xmake 不建议 root 用

-vD执行日志：
[rvd.txt](https://github.com/xmake-io/xmake/files/8549962/rvd.txt)

**Comment by waruqi** [comment]
我这里还是能检测到 clang ，应该还是 root 的关系，先切到 非 root 下，换个工程目录试试

```console
ruki@f6cc6a05e480:/mnt/xmake/tests/projects/cuda/console$ xmake -rv
checking for clang ... /usr/bin/clang
checking for flags (-fPIC) ... no
checking for flags (-O3) ... no
checking for flags (-rdc=true) ... no
checking for flags (--cuda-gpu-arch=sm_35) ... no
checking for flags (--cuda-gpu-arch=sm_37) ... no
checking for flags (--cuda-gpu-arch=sm_50) ... no
checking for flags (--cuda-gpu-arch=sm_52) ... no
checking for flags (--cuda-gpu-arch=sm_60) ... no
checking for flags (--cuda-gpu-arch=sm_61) ... no
checking for flags (--cuda-gpu-arch=sm_70) ... no
checking for flags (--cuda-gpu-arch=sm_75) ... no
checking for ccache ... /usr/bin/ccache
[ 25%]: ccache compiling.release src/main.cu
/usr/bin/ccache clang -c -Qunused-arguments -fvisibility=hidden -Iinc -m64 -o build/.objs/cuda_console/linux/x86_64/release/src/main.cu.o src/main.cu
checking for flags (-MMD -MF) ... ok
checking for flags (-fdiagnostics-color=always) ... no
checking for flags (-fcolor-diagnostics) ... ok
error: clang: error: cannot find libdevice for sm_20. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
clang: error: cannot find CUDA installation. Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang: error: cannot find CUDA installation. Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
```

另外即使 clang 检测到，也是用不了的，还是得依赖 cuda 工具链，不光 clang 切到编译器就完事了，还有 linker ，还有对应 cuda 的 sdk 库也需要。

**Comment by zt449569708** [comment]
> 我这里还是能检测到 clang ，应该还是 root 的关系，先切到 非 root 下，换个工程目录试试
> 
> ```
> ruki@f6cc6a05e480:/mnt/xmake/tests/projects/cuda/console$ xmake -rv
> checking for clang ... /usr/bin/clang
> checking for flags (-fPIC) ... no
> checking for flags (-O3) ... no
> checking for flags (-rdc=true) ... no
> checking for flags (--cuda-gpu-arch=sm_35) ... no
> checking for flags (--cuda-gpu-arch=sm_37) ... no
> checking for flags (--cuda-gpu-arch=sm_50) ... no
> checking for flags (--cuda-gpu-arch=sm_52) ... no
> checking for flags (--cuda-gpu-arch=sm_60) ... no
> checking for flags (--cuda-gpu-arch=sm_61) ... no
> checking for flags (--cuda-gpu-arch=sm_70) ... no
> checking for flags (--cuda-gpu-arch=sm_75) ... no
> checking for ccache ... /usr/bin/ccache
> [ 25%]: ccache compiling.release src/main.cu
> /usr/bin/ccache clang -c -Qunused-arguments -fvisibility=hidden -Iinc -m64 -o build/.objs/cuda_console/linux/x86_64/release/src/main.cu.o src/main.cu
> checking for flags (-MMD -MF) ... ok
> checking for flags (-fdiagnostics-color=always) ... no
> checking for flags (-fcolor-diagnostics) ... ok
> error: clang: error: cannot find libdevice for sm_20. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
> clang: error: cannot find CUDA installation. Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
> clang: error: cannot find CUDA installation. Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
> ```
> 
> 另外即使 clang 检测到，也是用不了的，还是得依赖 cuda 工具链，不光 clang 切到编译器就完事了，还有 linker ，还有对应 cuda 的 sdk 库也需要。

我网上查了一下，可以把cu文件后缀改一下，改成c或者cpp，然后编译cflags或者cxxflags里面加上-x cuda就可以了，如图，clang的编译选项。
![image](https://user-images.githubusercontent.com/6011216/165007776-94727e47-3ab2-4e48-82f2-7c1241697133.png)
但是这样，有个新的问题想咨询一下，就是我现在是cuda和C/C++混合编写的，如果我只想将`-x cuda`作用于cuda这个文件，有没有简单的方法可以做到？谢谢。

**Comment by waruqi** [comment]
add_files("*.cu", {cuflags = ""})

**Comment by zt449569708** [comment]
> > 我这里还是能检测到 clang ，应该还是 root 的关系，先切到 非 root 下，换个工程目录试试
> > ```
> > ruki@f6cc6a05e480:/mnt/xmake/tests/projects/cuda/console$ xmake -rv
> > checking for clang ... /usr/bin/clang
> > checking for flags (-fPIC) ... no
> > checking for flags (-O3) ... no
> > checking for flags (-rdc=true) ... no
> > checking for flags (--cuda-gpu-arch=sm_35) ... no
> > checking for flags (--cuda-gpu-arch=sm_37) ... no
> > checking for flags (--cuda-gpu-arch=sm_50) ... no
> > checking for flags (--cuda-gpu-arch=sm_52) ... no
> > checking for flags (--cuda-gpu-arch=sm_60) ... no
> > checking for flags (--cuda-gpu-arch=sm_61) ... no
> > checking for flags (--cuda-gpu-arch=sm_70) ... no
> > checking for flags (--cuda-gpu-arch=sm_75) ... no
> > checking for ccache ... /usr/bin/ccache
> > [ 25%]: ccache compiling.release src/main.cu
> > /usr/bin/ccache clang -c -Qunused-arguments -fvisibility=hidden -Iinc -m64 -o build/.objs/cuda_console/linux/x86_64/release/src/main.cu.o src/main.cu
> > checking for flags (-MMD -MF) ... ok
> > checking for flags (-fdiagnostics-color=always) ... no
> > checking for flags (-fcolor-diagnostics) ... ok
> > error: clang: error: cannot find libdevice for sm_20. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
> > clang: error: cannot find CUDA installation. Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
> > clang: error: cannot find CUDA installation. Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 另外即使 clang 检测到，也是用不了的，还是得依赖 cuda 工具链，不光 clang 切到编译器就完事了，还有 linker ，还有对应 cuda 的 sdk 库也需要。
> 
> 我网上查了一下，可以把cu文件后缀改一下，改成c或者cpp，然后编译cflags或者cxxflags里面加上-x cuda就可以了，如图，clang的编译选项。 ![image](https://user-images.githubusercontent.com/6011216/165007776-94727e47-3ab2-4e48-82f2-7c1241697133.png) 但是这样，有个新的问题想咨询一下，就是我现在是cuda和C/C++混合编写的，如果我只想将`-x cuda`作用于cuda编写的这类文件，有没有简单的方法可以做到？谢谢。

**Comment by zt449569708** [comment]
> add_files("*.cu", {cuflags = ""})

感谢，解决这个问题了。最主要的就是将cu后缀改成c/cpp后缀，然后加上编译选项-x cuda就行了。
