### ISSUE TITLE
建议增加service功能的安全性

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#2309]
### 你在什么场景下需要该功能？

在群里给大佬提过了，如果忙不过来，首先加最简单的安全机制即可， 

在服务端和客户端的配置文件里加上key参数，客户端请求时对比即可，代码可能就几行。这是用很小的代码量拦截了大部分的黑客攻击操作。

参考redis，前车之鉴，大部分只在内网运行，一样被黑客打成筛子，往往还会成为突破口。  
大部分时间运行在内网并不能表示可以忽略安全性。

### 描述可能的解决方案

客户端和服务端都配置key参数，客户端请求时比较key，不正确就拒绝连接，正确才允许继续

**Comment by waruqi** [comment]
稍微搞了下，多用户管理，密码验证， known hosts 检测什么的，基础认证逻辑做了一套，局域网应该基本够用了。。
