### ISSUE TITLE
target:has_tool 加上对 toolname 的探测

### ISSUE THREAD

**Issue by Latias94** [xmake-io/xmake#2315]
### 你在什么场景下需要该功能？

来自 Discussions [How to get the compiler name and linker name which is in use?](https://github.com/xmake-io/xmake/discussions/2314).

下面这种对使用的编译器的判断，对 clang-cl 不生效

```lua
on_config(function(target)
    if target:has_tool("cxx", "cl", "clang_cl") then
    elseif target:has_tool("cxx", "clang") then
    elseif target:has_tool("cxx", "gcc") then
    else
    end
end)
```

除非

```lua
if target:tool("cxx") == "clang-cl" then
```

希望能够方便的获取当前编译器、链接器，也有接口直接获取相关的版本号。
文档里面也加上对应方法。

相关 issue:
[How can I get current toolchain/compiler identifier?](https://github.com/xmake-io/xmake/discussions/1702)
[How do I check whether a package toolset is clang or apple-clang?](https://github.com/xmake-io/xmake/discussions/2190)

### 描述可能的解决方案

封装一下

**Comment by waruqi** [comment]
应该已经修了，你 dev 更新下试试 xmake update -s dev

**Comment by Latias94** [comment]
fixed，有空加下文档吧。
