### ISSUE TITLE
xmake should not set -stdlib=libc++ when using gcc from homebrew

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2317]
### Xmake 版本

2.6.5

### 操作系统版本和架构

macOS Big Sur 11.6 (M1)

### 描述问题

从homebrew安装gcc后，gcc不再是clang的alias，不应该加-stdlib=libc++才对；xmake没有识别，仍添加这一flag导致出错

### 期待的结果

macos上根据gcc -v判断是gcc还是clang并添加对应flag

**Comment by waruqi** [comment]
我这里没看出啥问题，不要走 xmake f --ld=gcc 强切，走 xmake f --toolchain=gcc 切就行了
