### ISSUE TITLE
Add a control option for xmake-repo from the command line

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2318]
### Xmake 版本

2.6.5

### 操作系统版本和架构

macOS Big Sur (M1)

### 描述问题

指定toolchain后add_extsources不再生效：例如`xmake f --toolchain=clang`，`add_requires("openmp")`将忽略系统的brew::libomp而去自己编译安装

### 期待的结果

指定toolchain后仍可以使用系统包，除非显式指定`add_requires("xxx", {system = false})`

### 附加信息和错误日志

最好可以提供一个pkg_mode的命令行参数，可以从外部启用/禁用xmake-repo：
```
xmake f --pkg_mode=auto # default
xmake f --pkg_mode=system # use system packages only
xmake f --pkg_mode=remote # prefer remote packages over system ones
```
这样在xmake项目集成到第三方package manager时可通过pkg_mode=system来禁用xmake-repo，避免混淆；另外切换其他不兼容toolchain时可通过pkg_mode=remote来禁用系统包，确保包的一致性

**Comment by waruqi** [comment]
这跟toolchain没关系吧，我没对 toolchain 特殊处理。。

即使不切 toolchain，我这测试也是找不到 brew:libomp 的。。因为它压根没装 pc 文件，

```
/usr/local/Cellar/libomp
└── 14.0.0
    ├── INSTALL_RECEIPT.json
    ├── include
    │   ├── omp-tools.h
    │   ├── omp.h
    │   └── ompt.h
    └── lib
        ├── libomp.a
        └── libomp.dylib

```

你可以直接用 `xmake l find_package brew::libomp` 测试

目前 brew:: 包的查找，是完全基于 pkg-config 的，如果没有 pc 文件，是找不到的

**Comment by waruqi** [comment]
这种比较特殊的，只能 on_fetch 里面改进下了

**Comment by xq114** [comment]
brew::libomp是另一个问题了，这个issue改成关于xmake-repo的控制好了

meson已经做了这个功能（remote部分是否开启的控制），参见 https://mesonbuild.com/Subprojects.html#commandline-options

**Comment by waruqi** [comment]
为什么要禁用? 不同项目配置的包 差异很大，直接禁用走系统，得看项目，很多项目都不一定能编译过。

而且一个项目里，很多包了，一刀切 system ，感觉编译成功率太低。。真要走 命令参数切。。可以走 option + add_requireconfs 自己设置，这样也便于作者只对里面，可以支持 system 的包进行选择性切换支持。

**Comment by xq114** [comment]
> 为什么要禁用? 不同项目配置的包 差异很大，直接禁用走系统，得看项目，很多项目都不一定能编译过。
> 
> 而且一个项目里，很多包了，一刀切 system ，感觉编译成功率太低。。真要走 命令参数切。。可以走 option + add_requireconfs 自己设置，这样也便于作者只对里面，可以支持 system 的包进行选择性切换支持。

只禁用其中下载安装的部分，on_fetch部分仍然启用。xmake-repo里面处理比如cmake的包的时候，也是禁用其中的下载第三方库部分，让他们去找xmake已经装好的第三方库；同理，反过来，vcpkg/cpm/别的第三方包管理处理xmake的包的时候，应该也有办法禁用xmake-repo，让xmake项目通过on_fetch去找系统上已经装好的包

**Comment by waruqi** [comment]
可以搞得更通用，更可扩展些。

这些东西，其实都适合通过 policy 来配置，我加了两个 policy 来配置。

### 仅仅走 fetch 模式，查找系统包

```lua
set_policy("package.fetch_only", true)
``` 

### 仅仅走安装模式

总是会远程下载安装。

```lua
set_policy("package.install_only", true)
``` 

### 命令行配置

我加了个 `xmake f --policies=` 配置项参数，可以通过配置修改多个 xmake 内部的默认策略，不仅仅用于控制包

默认配置了，就是启用

```console
$ xmake f --policies=package.fetch_only
```

也可以设置 `key:n`, `key:y`, `key:true`, `key:xxxx` 来配置 policy 的值
也可以通过 `,` 分割配置多个 policy

```console
$ xmake f --policies=package.precompiled:n,package.install_only
```
