### ISSUE TITLE
global 'raise' is not callable (a nil value)

### ISSUE THREAD

**Issue by bamlan** [xmake-io/xmake#2325]
### Xmake 版本

2.6.5

### 操作系统版本和架构

ubuntu 21.10

### 描述问题

全局域中使用：
```
if not os.isdir("xxx") then
    raise("fail")
end
```

报错：global 'raise' is not callable (a nil value)

在https://xmake.io/#/zh-cn/manual/builtin_modules?id=raise 文档中有raise的用法描述，是版本更新后修改掉了吗

### 期待的结果

在build过程中抛出异常中断build过程的方法

**Comment by xq114** [comment]
逻辑写在脚本域里面（on_config() etc），不要写在全局描述域里面

**Comment by waruqi** [comment]
不要在描述域调用，具体先了解下 描述域和脚本域的概念：https://xmake.io/#/zh-cn/guide/syntax_description

**Comment by 2283572185** [comment]
xmake version 2.6.9
我即使在脚本域内调动raise也会报global 'raises' is not callable
![2022-08-24](https://user-images.githubusercontent.com/63223769/186451523-d9a4cf55-be7d-41ff-af5c-fb205809612c.png)

**Comment by waruqi** [comment]
> 'raises' is not callable

仔细看，多了一个 s `raise` 不是 `raises`
