### ISSUE TITLE
添加nvidia-hpc-sdk工具链支持

### ISSUE THREAD

**Issue by xiangyi-wang** [xmake-io/xmake#2327]
### Is your feature request related to a problem? Please describe.

添加nvidia-hpc-sdk工具链支持(https://developer.nvidia.cn/nvidia-hpc-sdk-downloads)

### Describe the solution you'd like

可以自动识别nvidia-hpc-sdk工具链

**Comment by waruqi** [comment]
dev 支持了，更新到 `xmake update dev`

```console
$ xmake f --toolchain=cuda -c
$ xmake -rv
[ 25%]: ccache compiling.release src/main.f90
/usr/bin/ccache /opt/nvidia/hpc_sdk/Linux_x86_64/22.3/compilers/bin/nvfortran -c -m64 -O3 -o build/.objs/test/linux/x86_64/release/src/main.f90.o src/main.f90
[ 50%]: linking.release test
/opt/nvidia/hpc_sdk/Linux_x86_64/22.3/compilers/bin/nvfortran -o build/linux/x86_64/release/test build/.objs/test/linux/x86_64/release/src/main.f90.o -m64 -s
[100%]: build ok!
```

```console
$ xmake f --toolchain=cuda -c
$ xmake -rv
[ 25%]: ccache compiling.release src/main.cpp
/usr/bin/ccache /opt/nvidia/hpc_sdk/Linux_x86_64/22.3/compilers/bin/nvc++ -c -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG -o build/.objs/test/linux/x86_64/release/src/main.cpp.o src/main.cpp
[ 50%]: linking.release test
/opt/nvidia/hpc_sdk/Linux_x86_64/22.3/compilers/bin/nvc++ -o build/linux/x86_64/release/test build/.objs/test/linux/x86_64/release/src/main.cpp.o -m64 -s
[100%]: build ok!
```

**Comment by xiangyi-wang** [comment]
感谢这么快就支持了，不过 我更新到dev后还有有点问题，如果不设置fc，直接执行 `xmake f --toolchain=cuda -c`仍然使用的gfortran，设置fc后可以看到识别到nvfortran了,但是不识别fc设置的nvfortran
![image](https://user-images.githubusercontent.com/22881957/166405305-456fa39c-dbff-4349-b998-73c3c7e9b6a0.png)

![image](https://user-images.githubusercontent.com/22881957/166405178-3fe2c42d-349d-46c0-9cd0-632203bff1af.png)

**Comment by waruqi** [comment]
我这里可以，确认更新到最新 dev

**Comment by xiangyi-wang** [comment]
除了执行`xmake update dev`还需要其他操作吗 版本好像还是之前的

![image](https://user-images.githubusercontent.com/22881957/166406113-8eefea33-953f-469d-872f-5abc1d61504c.png)

**Comment by xiangyi-wang** [comment]
刚试了下 从vscode插件切换工具链成功过了
![image](https://user-images.githubusercontent.com/22881957/166406955-d903493a-9aa3-48e3-aed0-768ae0d24bc5.png)

**Comment by waruqi** [comment]
source ~/.xmake/profile

或者重新开下终端

**Comment by xiangyi-wang** [comment]
可以了 谢谢！
