### ISSUE TITLE
console colors breaking in windows

### ISSUE THREAD

**Issue by yamashi** [xmake-io/xmake#2329]
### Xmake Version

v2.6.5+master.9f24c2743

### Operating System Version and Architecture

Windows 11

### Describe Bug

Colors in windows console break after 
```
checking for debug.x64 ...
checking for Microsoft Visual Studio (x64) version ... 2022
updating repositories .. ok
```
when executing
`xmake project -k vs/vsxmake`

### Expected Behavior

Colors keep working

**Comment by waruqi** [comment]
please add -vD and let me see the output

**Comment by yamashi** [comment]
[bug.log](https://github.com/xmake-io/xmake/files/8596989/bug.log)

**Comment by yamashi** [comment]
![image](https://user-images.githubusercontent.com/672982/166107608-3b257c57-9fea-4dbd-befc-11dff805b584.png)

**Comment by waruqi** [comment]
please update to dev branch nad try it again. `xmake update dev`

**Comment by yamashi** [comment]
I can confirm it was fixed in dev!
