### ISSUE TITLE
add_filegroups 

### ISSUE THREAD

**Issue by car520120** [xmake-io/xmake#2335]
### Xmake 版本

2.6.5

### 操作系统版本和架构

win10

### 描述问题

生成 vs工程所有头文件都在  src 目录中

### 期待的结果

include/abc/a.h
include/def/b.h
include/c.h

src/abc/1.h
src/abc/1.c
src/def/2.h
src/def/2.c
src/3.h
src/3.c

### 工程配置

[test_filegroups.zip](https://github.com/xmake-io/xmake/files/8630005/test_filegroups.zip)

**Comment by waruqi** [comment]
凡事仔细点，文件在哪别搞错了。

```diff
- add_filegroups("include",{rootdir=lib_src,files="**.h"})
- add_filegroups("src",{rootdir=lib_inc,files={"**.c","**.h"}})
+ add_filegroups("include",{rootdir=lib_inc,files="**.h"})
+ add_filegroups("src",{rootdir=lib_src,files={"**.c", "**.h"}})

  add_files(path.join(lib_src,"**.c"))
  add_headerfiles(path.join(lib_inc,"**.h"))
+ add_headerfiles(path.join(lib_src,"**.h"))
```

![image](https://user-images.githubusercontent.com/151335/166924174-aca4a628-33af-46e9-aa46-0e57d3ce46eb.png)
