### ISSUE TITLE
Add a way to get batchcmd context

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#2337]
### Is your feature request related to a problem? Please describe.

I'm currently using batchcmd to compile shaders when building my project, like this:
```lua
	before_buildcmd_file(function (target, batchcmds, shaderfile, opt)
		local nzslc = target:dep("NazaraShaderCompiler")

		-- add commands
		batchcmds:show_progress(opt.progress, "${color.build.object}compiling shader %s", shaderfile)
		local argv = {"--compile", "--partial", "--header-file", shaderfile}
		batchcmds:vrunv(nzslc:targetfile(), argv, { curdir = "." })

		local outputFile = path.join(path.directory(shaderfile), path.basename(shaderfile) .. ".nzslb.h")

		-- add deps
		batchcmds:add_depfiles(shaderfile)
		batchcmds:set_depmtime(os.mtime(outputFile))
		batchcmds:set_depcache(target:dependfile(outputFile))
	end)
```

It outputs something like this:

![image](https://user-images.githubusercontent.com/3002461/167117406-5bf2cc2c-267c-496d-9b04-4d260761c389.png)

which is nice.

However, when compiling from VS, I get this:
![image](https://user-images.githubusercontent.com/3002461/167117716-2bf94b1d-b404-4b59-8c88-91c476bb257d.png)
![image](https://user-images.githubusercontent.com/3002461/167117739-0a336907-1beb-4388-a99a-ade3c054fb69.png)

which isn't bad, but we can do better.

I added a `--log-format=vs` option which outputs error in a way VS can parse:
![image](https://user-images.githubusercontent.com/3002461/167118004-c456fe18-d56d-41d6-a63d-1cb1c84dbf2c.png)

which is pretty nice for VS, however it's very less interesting when compiling from xmake
![image](https://user-images.githubusercontent.com/3002461/167118089-f13019cb-ca16-4f65-8e94-65d0beb26f92.png)

I'd like to add the `--log-format=vs` option only for Visual Studio, unfortunately we currently have no way to know if batchcmds are currently used in VS or for another project generator or even xmake.

### Describe the solution you'd like

Maybe a `batchcmds:context()` which could return a string, it could returns "vs-project", "vsxmake-project", "cmake-project", "xmake" and more.

This way, we could do something like that:
```lua
	before_buildcmd_file(function (target, batchcmds, shaderfile, opt)
...
		local argv = {"--compile", "--partial", "--header-file"}
		if batchcmds:context():match("^vs") then
			table.insert(argv, "--log-format=vs")
		end
		table.insert(argv, shaderfile)    
		batchcmds:vrunv(nzslc:targetfile(), argv, { curdir = "." })
...
	end)
```

Please note this isn't a vs-only issue, as other tools such as xcode and more (#1955) may use a specific format, in the future this solution could be expanded for such tools.

### Describe alternatives you've considered

Using a xmake option which could pass log-format to this rule. However this requires me to switch between xmake options all the time since I'm compiling with both VS and xmake (depending on circumstances)

**Comment by waruqi** [comment]
please update to dev and try 

```lua
local kind = target:data("plugin.project.kind")
if kind == "vs" then
    -- ...
end
```

Other project generators I will add support for later, but at the moment I don't have time to deal with them.

**Comment by SirLynix** [comment]
Works like a charm, thank you.

Do you want me to make a PR for other projects generator?

**Comment by waruqi** [comment]
welcome, thanks
