### ISSUE TITLE
qt  moc_ 同名文件会有冲突

### ISSUE THREAD

**Issue by car520120** [xmake-io/xmake#2343]
### Xmake 版本

2.6.5

### 操作系统版本和架构

win10

### 描述问题

error: build\.objs\test\windows\x64\debug\gens\rules\qt\moc\moc_signal.cpp.obj : warning LNK4042: 对象被多次指定；已忽略多余的指定
test.cpp.obj : error LNK2001: 无法解析的外部符号 "public: virtual struct QMetaObject const * __cdecl abc::Signal::metaObject(void)const " (?metaObject@Signal@abc@@UEBAPEBUQMetaObject@@XZ)
test.cpp.obj : error LNK2001: 无法解析的外部符号 "public: virtual void * __cdecl abc::Signal::qt_metacast(char const *)" (?qt_metacast@Signal@abc@@UEAAPEAXPEBD@Z)
test.cpp.obj : error LNK2001: 无法解析的外部符号 "public: virtual int __cdecl abc::Signal::qt_metacall(enum QMetaObject::Call,int,void * *)" (?qt_metacall@Signal@abc@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z)
test.cpp.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl abc::Signal::abc(void)" (?abc@Signal@0@QEAAXXZ)，函数 "public: __cdecl Test::Test(class QWidget *)" (??0Test@@QEAA@PEAVQWidget@@@Z) 中引用了 
该符号
test.cpp.obj : error LNK2001: 无法解析的外部符号 "public: static struct QMetaObject const abc::Signal::staticMetaObject" (?staticMetaObject@Signal@abc@@2UQMetaObject@@B)
build\windows\x64\debug\test.exe : fatal error LNK1120: 5 个无法解析的外部命令

PS D:\WorkPro\learn\qt\test>

### 期待的结果
xmake -j1
能正常编译

### 工程配置

[test.zip](https://github.com/xmake-io/xmake/files/8645186/test.zip)

**Comment by car520120** [comment]
粗略处理了一下
https://github.com/car520120/xmake/blob/master/xmake/rules/qt/moc/xmake.lua
增加了 moc 目录层次
```lua
local moc_rootdirs = target.moc_rootdirs
        if not moc_rootdirs then
            moc_rootdirs = {}
            local filegroups = target:get("filegroups")
            if  filegroups then
                local filegroups_extraconf = target:extraconf("filegroups")
                for _,fg in ipairs(filegroups) do
                    local rootdir = filegroups_extraconf[fg].rootdir
                    if not path.is_absolute(rootdir) then
                        rootdir = path.absolute(rootdir)
                    end
                    table.insert(moc_rootdirs,path.normalize(rootdir))
                end
            end
            table.insert(moc_rootdirs,target:scriptdir())
            table.insert(moc_rootdirs,os.projectdir())
            target.moc_rootdirs = moc_rootdirs
        end
      


        local filter
        local fileitem =  path.is_absolute(sourcefile) and sourcefile or  path.absolute(sourcefile)
        if fileitem then
            fileitem = path.normalize(fileitem)
            for _,rootdir in ipairs(moc_rootdirs) do
                if fileitem:match(rootdir) then
                    filter = path.normalize(path.directory(path.relative(fileitem, rootdir)))
                    if '.' == filter then
                        filter = nil
                    end
                    break
                end
            end
        end
```
如果是存在多层目录会加上相对部分
```lua
        if filter then
            filename_moc = path.join(filter,filename_moc)
        end

```

**Comment by waruqi** [comment]
更新到 dev 再试下
