### ISSUE TITLE
qt 生成vs工程编译不过

### ISSUE THREAD

**Issue by car520120** [xmake-io/xmake#2350]
### Xmake 版本

2.6.5

### 操作系统版本和架构

win10

### 描述问题

提示缺少moc文件

### 期待的结果

能正常编译

### 工程配置

[qt.zip](https://github.com/xmake-io/xmake/files/8660306/qt.zip)

**Comment by waruqi** [comment]
这个你只能自己调下，我没 win qt 环境，磁盘空间不够

**Comment by car520120** [comment]
我已经调试能正常编译的了，但是对项目不熟识！是提个PR给你帮忙看看吗？
[xmake_modify.zip](https://github.com/xmake-io/xmake/files/8704496/xmake_modify.zip)

**Comment by waruqi** [comment]
更新到 dev 再试下

**Comment by car520120** [comment]
error: @programdir\core\main.lua:280: @programdir\actions\build\main.lua:166: ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:96: ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:56: @programdir\modules\private\async\runjobs.lua:256: @programdir\core\base\path.lua:132: method 'str' is not callable (a nil value)
stack traceback:
    [@programdir\core\base\path.lua:132]: in function 'concat'
    [@programdir\modules\core\tools\cl.lua:506]:
    [@programdir\modules\private\utils\batchcmds.lua:242]: in function 'compile'
    [@programdir\rules\qt\moc\xmake.lua:95]: in function 'script'
    [@programdir\actions\build\kinds\object.lua:86]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:232]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:872: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir\modules\private\async\runjobs.lua:256: in field 'catch'
        @programdir\core\sandbox\modules\try.lua:127: in global 'try'
        @programdir\modules\private\async\runjobs.lua:218: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:388: in function <@programdir\core\base\scheduler.lua:385>
stack traceback:
        @programdir\core\base\utils.lua:290: in function <@programdir\core\base\utils.lua:280>
        [C]: in function 'error'
        @programdir\core\base\os.lua:872: in function 'base/os.raiselevel'
        (...tail calls...)
        ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:56: in field 'co_start_withopt'
        @programdir\modules\private\async\runjobs.lua:217: in function <@programdir\modules\private\async\runjobs.lua:162>
        [C]: in function 'xpcall'
        @programdir\core\base\utils.lua:280: in function 'sandbox/modules/utils.trycall'
        @programdir\core\base\scheduler.lua:504: in function 'base/scheduler.co_group_begin'
        ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:94: in field 'co_group_begin'
        @programdir\modules\private\async\runjobs.lua:162: in function <@programdir\modules\private\async\runjobs.lua:56>
        (...tail calls...)
        @programdir\actions\build\build.lua:252: in function <@programdir\actions\build\build.lua:240>
        (...tail calls...)
        @programdir\actions\build\main.lua:103: in global '_do_build'
        @programdir\actions\build\main.lua:150: in function <@programdir\actions\build\main.lua:144>
        [C]: in function 'xpcall'
        @programdir\core\base\utils.lua:280: in function 'sandbox/modules/utils.trycall'
        @programdir\core\sandbox\modules\try.lua:121: in global 'try'
        @programdir\actions\build\main.lua:142: in function <@programdir\actions\build\main.lua:108>
        (...tail calls...)
        [C]: in function 'xpcall'
        @programdir\core\base\utils.lua:280: in function 'sandbox/modules/utils.trycall'
        (...tail calls...)
        @programdir\core\base\task.lua:519: in function 'base/task.run'
        @programdir\core\main.lua:278: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:388: in function <@programdir\core\base\scheduler.lua:385>
stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:872: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:280: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:388: in function <@programdir\core\base\scheduler.lua:385>
warning: You are working in the project directory(E:\WorkPro\sandbox\208_blockmango-client) and you can also
force to build in current directory via run `xmake -P .`
PS E:\WorkPro\sandbox\208_blockmango-client\engine-core>
