### ISSUE TITLE
add_deps 不能调整链接顺序

### ISSUE THREAD

**Issue by huye** [xmake-io/xmake#2351]
### 你在什么场景下需要该功能？

我项目中有多个 target静态使用tbox 库，会产生多个副本，想在一个 target 中链接 tbox 后，其它 target 能优选链接它，但现在的情况是链接的时候 tbox 始终在前面，而我这个 target 的库都在它后面，调整 add_deps 的顺序无效，手动在前面加一个 add_packages 也无效，add_deps 依赖的库都会链接到后面去。现在我是通过关闭了 add_deps 的继承后，手动指定 add_links 和 add_linkdirs

### 描述可能的解决方案

希望能根据 add_deps 的顺序来链接，如果怕这个会有兼容问题，那么希望另外手动指定 add_packages 或 add_links 时保持住链接顺序。

**Comment by huye** [comment]
我之前在 xmake.io 上看到有修复链接顺序，我以为不是本身的问题，但我看了下这个 #1452 ，不知道是不是这个还没修复，如果是的话，那么我这里应该就是同一个问题了，如果以前有修复，那是不是又重新出现这个问题了？

**Comment by waruqi** [comment]
反馈问题，请提交 bug 反馈，而不是 feature request ，另外附带 xmake.lua， logs ，可复现 example

**Comment by waruqi** [comment]
初步改进了下，试试 https://github.com/xmake-io/xmake/issues/1452#issuecomment-1741152822
