### ISSUE TITLE
对于添加了后缀的目标文件vs工程无法执行

### ISSUE THREAD

**Issue by supf1994** [xmake-io/xmake#2362]
### Xmake 版本

2.6.5

### 操作系统版本和架构

windows10

### 描述问题

在工程中指定了生成目标文件后缀
`add_rules("mode.debug", "mode.release")

if is_mode("debug") then 
    set_suffixname("-d")
end

includes("libtest")

includes("main")
`

生成vs2022工程，在vs工程中运行会有如下提示
![image](https://user-images.githubusercontent.com/23397492/168958003-76678728-8f3b-4fc5-8da0-c76e98fa2f06.png)

直接使用xmake run 运行则没有问题

### 期待的结果

vs工程可以直接运行

**Comment by waruqi** [comment]
给完整 demo

**Comment by supf1994** [comment]
[https://raw.githubusercontent.com/supf1994/other/56fd20082d89488c7ec80795ad3932f9a493ed68/xmake_test/test.zip](url)

**Comment by supf1994** [comment]
[https://github.com/supf1994/other/blob/main/xmake_test/test.zip](url)

**Comment by supf1994** [comment]
[https://github.com/supf1994/other/blob/56fd20082d89488c7ec80795ad3932f9a493ed68/xmake_test/test.zip](url)

**Comment by waruqi** [comment]
等ci跑完，全量更新下再试试：https://github.com/xmake-io/xmake/actions/runs/2366749084
