### ISSUE TITLE
生成的 Visual Studio 解决方案的生成事件脚本的默认运行目录不合预期

### ISSUE THREAD

**Issue by afoolsbag** [xmake-io/xmake#2363]
### Xmake 版本

xmake v2.6.5+HEAD.d239205f6

### 操作系统版本和架构

Windows 10 version 21H2

### 描述问题

使用 `xmake project vs` 生成 `.sln` 解决方案，其中各项目的生成事件（生成前事件、链接前事件、生成后事件）的脚本的运行目录，默认为 `.vcxproj` 项目文件所在目录，而非 XMake 项目目录。

这会导致使用相对路径的命令（如 `target:autogendir()`）无法找到对应文件。

### 期待的结果

Visual Studio 可以正确执行生成的生成事件脚本。

### 我的临时解决方案

在每一条脚本命令前，切换当前目录到 XMake 项目目录，将

https://github.com/xmake-io/xmake/blob/567d04c515cb241e8ca0caff53dcb4e31f4688b9/xmake/plugins/project/vstudio/impl/vs201x_vcxproj.lua#L717-L719

修改为

``` lua
    for _, command in ipairs(commands) do
        vcxprojfile:print("cd \"$(projectdir)\"")
        vcxprojfile:print("%s", command)
    end
```

**Comment by waruqi** [comment]
要等 https://github.com/xmake-io/xmake/pull/2341 这个 patch 。。

**Comment by waruqi** [comment]
更新到 dev 再试下
