### ISSUE TITLE
生成的vsxmake工程编译时日志输出乱码

### ISSUE THREAD

**Issue by supf1994** [xmake-io/xmake#2364]
### Xmake 版本

2.6.5

### 操作系统版本和架构

windows10

### 描述问题

生成 vsxmake2022 工程，编译时输出的中文日志为乱码
![image](https://user-images.githubusercontent.com/23397492/169073645-355653db-6bcf-49b5-adfa-d94737d3a5ae.png)

### 期待的结果

正常的输出中文日志

**Comment by waruqi** [comment]
已知问题，暂时没空解，可以来个 pr

**Comment by Domain** [comment]
> 已知问题，暂时没空解，可以来个 pr

把Xmake.targets里面的StdOutEncoding和StdErrEncoding删除就正常了，不知道这样的修改接受吗？

**Comment by waruqi** [comment]
> > 已知问题，暂时没空解，可以来个 pr
> 
> 把Xmake.targets里面的StdOutEncoding和StdErrEncoding删除就正常了，不知道这样的修改接受吗？

先确认下有没有其他的影响，比如编译错误的输出，如果有中文 是否反而会乱码等等。。

**Comment by waruqi** [comment]
我已经merge了
