### ISSUE TITLE
自定义创建工程的模版

### ISSUE THREAD

**Issue by yueneiqi** [xmake-io/xmake#2375]
### 你在什么场景下需要该功能？

使用xmake create生成工程时，想使用自定义的模版工程，请问有什么方法吗？

### 描述可能的解决方案

无

**Comment by waruqi** [comment]
暂不支持自定义

**Comment by OuYangPaste** [comment]
我曾经有过同样的需求，解决方法是自己写个xmake 插件自行生成模板，不使用 xmake create

**Comment by waruqi** [comment]
这种自己搞个task脚本处理下，也就几行代码的事，暂时不考虑支持
