### ISSUE TITLE
Don't use build artifacts

### ISSUE THREAD

**Issue by yamashi** [xmake-io/xmake#2377]
### Is your feature request related to a problem? Please describe.

Yes, using different versions of MSVC can lead to linker failures (see : https://developercommunity.visualstudio.com/t/-imp-std-init-once-complete-unresolved-external-sy/1684365 )

Currently the only way to disable the use of prebuilt artifacts it to add `{ build = true }` to every require which is less than ideal and I would like to be able to disable it entirely to prevent running into linker issues.

### Describe the solution you'd like

Either a config value for xmake to disable/enable build artifacts or a project wise option maybe `set_usecachedartifacts(true/false)`

**Comment by SirLynix** [comment]
Maybe a policy like `set_policy("package.useartifacts", false)`

**Comment by waruqi** [comment]
please update to dev and try `set_policy("package.precompiled", false)` in project or package.

**Comment by Freed-Wu** [comment]
Can we don't use package.precompiled by an command line option? Such as `xmake build --without-package-precomipiled`

Sometimes we build the project without network to download artifact like #2662 . it will avoid error in this situation.

**Comment by SirLynix** [comment]
You can use `xmake config --policies=package.precompiled:n` to disable precompiled with the commandline

**Comment by Freed-Wu** [comment]
Thank to your quick reply! I also find the official document [here](https://xmake.io/#/guide/build_policies)
