### ISSUE TITLE
Allow changing default vsxmake `outputdir` in `xmake.lua`

### ISSUE THREAD

**Issue by Qudix** [xmake-io/xmake#2378]
### Is your feature request related to a problem? Please describe.

I like to have the vs solution files generate under a `build/` directory, and setting it in the command line works just fine
i.e. `xmake project -k vsxmake2022 build` generates `build/vsxmake2022/...`
However, there doesn't appear to be a way to set the default outputdir when it's omitted from the command line?

### Describe the solution you'd like

I'd like to set the default outputdir in `xmake.lua` when it isn't specified in the command line

### Describe alternatives you've considered

I couldn't find anything in the documentation, nor could I surmise something from reading the xmake source.

**Comment by waruqi** [comment]
I wouldn't consider this feature, you can pass the outputdir parameter.

`xmake project -k vsxmake2022 build`
