### ISSUE TITLE
xmake 运行依赖

### ISSUE THREAD

**Issue by dapeng17951** [xmake-io/xmake#2381]
### Xmake 版本

2.6.5

### 操作系统版本和架构

arch linux

### 描述问题

安装成功，运行提示：
xmake: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory

### 期待的结果

项cmake一样，安装后即用！

**Comment by waruqi** [comment]
用脚本装的，还是 aur 包？ 看下 ncurses 在你系统上的位置。

**Comment by dapeng17951** [comment]
yay -S xmake 安装的
which ncurses 未找到ncurses
sudo paman -S ncurses 后 依旧 which 不到

**Comment by waruqi** [comment]
用脚本装下试试

```
bash <(curl -fsSL https://xmake.io/shget.text)
source ~/.xmake/profile
```

**Comment by dapeng17951** [comment]
执行bash <(curl -fsSL https://xmake.io/shget.text)
提示：
curl: (6) Could not resolve host: xmake.io

**Comment by waruqi** [comment]
这就是你的网络环境问题了

**Comment by dapeng17951** [comment]
网络修复了，且raw.githubusercontent.com ping的通，依旧curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 2 ms: Connection refused

**Comment by waruqi** [comment]
这个没办法，之前走的 jsdelivr ，最近被q了，只能回退到 github 。。要是访问不了，直接自己到 releases 下，自己下载 xxx.run 自安装包装，或者自己 clone git 源码安装。。或者fq下

**Comment by dapeng17951** [comment]
谢谢大哥

**Comment by dapeng17951** [comment]
wsl 重装了依此，依此执行如下
1.换源；
2.sudo pacman -S glibc lib32-glibc；
3.sudo pacman -S base-devel ；
4.sudo pacman -Ss yay;
5.yay -S ncurses;
6.yay -S xmake;
然后好了！唉！
