### ISSUE TITLE
add_packages支持-Bstatic和-Bdynamic

### ISSUE THREAD

**Issue by rel1ve** [xmake-io/xmake#2383]
### 你在什么场景下需要该功能？

在使用add_requires和add_packages时，如果动态库和静态库同时存在，c/c++编译器默认会优先链接动态库，需要添加-Wl,-Bstatic -lxxx来指定链接静态库。

### 描述可能的解决方案

希望能增加语法支持指定链接动态库或静态库，如
1. 指定链接静态库：
`add_packages("boost", {links= {{name = "boost_thread", link = static}}})`
2. 指定链接动态库：
`add_packages("boost", {links= {{name = "boost_thread", link = shared}}})`

**Comment by waruqi** [comment]
xmake 的包是 静态库和动态库隔离的，不会同时安装在一个地方。。

通过 `add_requires("boost", {configs = {shared = true}})`

要么只装 so 要么只装 .a ，不需要这个特性

**Comment by rel1ve** [comment]
如果是第三方的包（比如CONAN），也必须是静态库和动态库隔离的，不能是同时包括静态库和动态库。这种要求是否过于严格？

**Comment by waruqi** [comment]
理论上都是要隔离的，但目前还没空搞，只有win static现在做了隔离，具体得看第三方包的支持力度

但 xmake-repo 自身包，肯定要严格控制的

如果用了第三方管理，肯定不会有内置包那么多特性，所以 add_packages这种需求，更不会支持

而且不同包在不同平台下 link name差异巨大，规则复杂，例如boost，自己外面指定，无法跨平台，所以我不会开放这种设置
