### ISSUE TITLE
Add a add_assets to the vs generator

### ISSUE THREAD

**Issue by TNtube** [xmake-io/xmake#2384]
### Is your feature request related to a problem? Please describe.

I faced a problem with the current vs solution generator, I couldn't see my assets folder (contening mainly images and glsl scripts)

### Describe the solution you'd like

A add_assets function (or any name that sound better) to add any non project files in the VS solution hierarchy.

### Describe alternatives you've considered

I'm currently using add_headerfiles, that is working in my case but feel more like a hack than anything.

Thanks you

**Comment by SirLynix** [comment]
Maybe we could reuse `add_installfiles` to include them in VS projects?

**Comment by TNtube** [comment]
That's currently what i'm doing and it works well, but I thought it was more a hack than a solution.

**Comment by Arthapz** [comment]
meson has "extra_files" to list them

**Comment by waruqi** [comment]
meson is just a project generator, so it can provide various special interfaces related to the project generator.

But project generator is only an optional plug-in for xmake, and I don't want to add a special Api just for the features that project generator needs.

**Comment by waruqi** [comment]
May be we can add `add_extrafiles` for extra files. It will be used to support some of the following features.

1. Only show them in vs/vsxmake project generator, but they will be not installed.
2. ...

Only one case I can think of at the moment, but it's not enough to add an new api just for the vs project generator.

**Comment by waruqi** [comment]
I have added it. `add_extrafiles("*.txt")` https://github.com/xmake-io/xmake/pull/4104

```
xmake update -s github:xmake-io/xmake#extrafiles
```

**Comment by SirLynix** [comment]
Awesome, thank you!
