### ISSUE TITLE
cmake依赖包版本号无效 

### ISSUE THREAD

**Issue by YSRForGithub** [xmake-io/xmake#2385]
### Xmake 版本

2.6.6

### 操作系统版本和架构

Linux 5.17.9-arch1-1

### 描述问题

调用add_requires("cmake::xxx 1.2.3")  时，未能正确找到相应版本库。猜测是文件 cmake/find_package.lua 中 opt.required_version 变量名错误，改为 opt.require_version 后就正常了

### 期待的结果

期待能够支持按包版本号查找cmake包

**Comment by waruqi** [comment]
修复了，更新到 dev 版本试下

xmake update -s dev
