### ISSUE TITLE
xmake throws away SSE options on macOS Clang

### ISSUE THREAD

**Issue by Dieken** [xmake-io/xmake#2387]
### Xmake Version

v2.6.4+202203070649

### Operating System Version and Architecture

macOS 12.3.1

### Describe Bug

$ brew install gtk4
$ pkg-config --cflags gtk4
-mfpmath=sse -msse -msse2 -I/usr/local/Cellar/libffi/3.4.2/include -I/usr/local/Cellar/gtk4/4.6.1/include/gtk-4.0 -I/usr/local/Cellar/glib/2.70.4/include/gio-unix-2.0 -I/usr/local/Cellar/libepoxy/1.5.9_1/include -I/usr/local/Cellar/cairo/1.16.0_5/include/cairo -I/usr/local/Cellar/pango/1.50.5/include/pango-1.0 -I/usr/local/Cellar/harfbuzz/4.0.1/include/harfbuzz -I/usr/local/Cellar/pango/1.50.5/include/pango-1.0 -I/usr/local/Cellar/fribidi/1.0.11/include/fribidi -I/usr/local/Cellar/harfbuzz/4.0.1/include/harfbuzz -I/usr/local/Cellar/graphite2/1.3.14/include -I/usr/local/Cellar/gdk-pixbuf/2.42.6/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -I/usr/local/Cellar/libtiff/4.3.0/include -I/usr/local/Cellar/cairo/1.16.0_5/include/cairo -I/usr/local/Cellar/pixman/0.40.0/include/pixman-1 -I/usr/local/Cellar/fontconfig/2.13.1/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -I/usr/local/Cellar/libxcb/1.14_2/include -I/usr/local/Cellar/libxrender/0.9.10/include -I/usr/local/Cellar/libxext/1.3.4/include -I/usr/local/Cellar/libx11/1.7.3.1/include -I/usr/local/Cellar/libxcb/1.14_2/include -I/usr/local/Cellar/libxau/1.0.9/include -I/usr/local/Cellar/libxdmcp/1.1.3/include -I/usr/local/Cellar/graphene/1.10.6/include/graphene-1.0 -I/usr/local/Cellar/graphene/1.10.6/lib/graphene-1.0/include -I/usr/local/Cellar/glib/2.70.4/include -I/usr/local/Cellar/glib/2.70.4/include/glib-2.0 -I/usr/local/Cellar/glib/2.70.4/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.45/include -I/usr/local/Cellar/xorgproto/2021.5/include

$ touch a.c
$ cat > xmake.lua <<EOF
add_requires("gtk4")
add_rules("mode.debug", "mode.release")
set_warnings("everything")

target("a")
    set_kind("shared")
    add_defines("BUILDING_ZIM")
    add_packages("gtk4")
    add_files("a.c")
    set_symbols("hidden")
EOF

$ xmake -v

### Expected Behavior

"-mfpmath=sse -msse -msse2" should be there, but xmake throws away them.

checking for platform ... macosx
checking for architecture ... x86_64
checking for Xcode directory ... /Applications/Xcode.app
checking for Codesign Identity of Xcode ... no
checking for SDK version of Xcode for macosx (x86_64) ... 12.3
checking for Minimal target version of Xcode for macosx (x86_64) ... 12.3
checking for dmd ... no
checking for ldc2 ... no
checking for gdc ... no
checking for zig ... /usr/local/bin/zig
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/local/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
checking for ping ... /sbin/ping
pinging for the host(gitee.com) ... 31 ms
pinging for the host(gitlab.com) ... 232 ms
pinging for the host(github.com) ... 65535 ms
checking for xmake::gtk4 ... no
checking for brew ... /usr/local/bin/brew
checking for pkg-config ... /usr/local/bin/pkg-config
checking for gtk4 ... brew::gtk4 4.6.1
checking for xcrun -sdk macosx clang ... /usr/bin/xcrun -sdk macosx clang
checking for the c compiler (cc) ... xcrun -sdk macosx clang
checking for /usr/bin/xcrun -sdk macosx clang ... ok
checking for flags (-fPIC) ... ok
checking for flags (-O3) ... ok
checking for flags (-DNDEBUG) ... ok
checking for ccache ... no
[ 25%]: compiling.release a.c
"/usr/bin/xcrun -sdk macosx clang" -c -Qunused-arguments -arch x86_64 -mmacosx-version-min=12.3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -fPIC -fvisibility=hidden -Weverything -O3 -DBUILDING_ZIM -isystem /usr/local/Cellar/libffi/3.4.2/include -isystem /usr/local/Cellar/gtk4/4.6.1/include/gtk-4.0 -isystem /usr/local/Cellar/glib/2.70.4/include/gio-unix-2.0 -isystem /usr/local/Cellar/libepoxy/1.5.9_1/include -isystem /usr/local/Cellar/cairo/1.16.0_5/include/cairo -isystem /usr/local/Cellar/pango/1.50.5/include/pango-1.0 -isystem /usr/local/Cellar/harfbuzz/4.0.1/include/harfbuzz -isystem /usr/local/Cellar/fribidi/1.0.11/include/fribidi -isystem /usr/local/Cellar/graphite2/1.3.14/include -isystem /usr/local/Cellar/gdk-pixbuf/2.42.6/include/gdk-pixbuf-2.0 -isystem /usr/local/Cellar/libpng/1.6.37/include/libpng16 -isystem /usr/local/Cellar/libtiff/4.3.0/include -isystem /usr/local/Cellar/pixman/0.40.0/include/pixman-1 -isystem /usr/local/Cellar/fontconfig/2.13.1/include -isystem /usr/local/opt/freetype/include/freetype2 -isystem /usr/local/Cellar/libxcb/1.14_2/include -isystem /usr/local/Cellar/libxrender/0.9.10/include -isystem /usr/local/Cellar/libxext/1.3.4/include -isystem /usr/local/Cellar/libx11/1.7.3.1/include -isystem /usr/local/Cellar/libxau/1.0.9/include -isystem /usr/local/Cellar/libxdmcp/1.1.3/include -isystem /usr/local/Cellar/graphene/1.10.6/include/graphene-1.0 -isystem /usr/local/Cellar/graphene/1.10.6/lib/graphene-1.0/include -isystem /usr/local/Cellar/glib/2.70.4/include -isystem /usr/local/Cellar/glib/2.70.4/include/glib-2.0 -isystem /usr/local/Cellar/glib/2.70.4/lib/glib-2.0/include -isystem /usr/local/opt/gettext/include -isystem /usr/local/Cellar/pcre/8.45/include -isystem /usr/local/Cellar/xorgproto/2021.5/include -DNDEBUG -o build/.objs/a/macosx/x86_64/release/a.c.o a.c
checking for flags (-MMD -MF) ... ok
checking for flags (-fdiagnostics-color=always) ... ok
checking for xcrun -sdk macosx clang++ ... /usr/bin/xcrun -sdk macosx clang++
checking for the shared library linker (sh) ... xcrun -sdk macosx clang++
checking for /usr/bin/xcrun -sdk macosx clang++ ... ok
checking for flags (-fPIC) ... ok
[ 50%]: linking.release liba.dylib
"/usr/bin/xcrun -sdk macosx clang++" -o build/macosx/x86_64/release/liba.dylib build/.objs/a/macosx/x86_64/release/a.c.o -shared -fPIC -arch x86_64 -mmacosx-version-min=12.3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -stdlib=libc++ -L/usr/local/Cellar/gtk4/4.6.1/lib -L/usr/local/Cellar/pango/1.50.5/lib -L/usr/local/Cellar/harfbuzz/4.0.1/lib -L/usr/local/Cellar/gdk-pixbuf/2.42.6/lib -L/usr/local/Cellar/cairo/1.16.0_5/lib -L/usr/local/Cellar/graphene/1.10.6/lib -L/usr/local/Cellar/glib/2.70.4/lib -L/usr/local/opt/gettext/lib -Wl,-x -lgtk-4 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lgraphene-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl -lz -install_name @rpath/liba.dylib
[100%]: build ok!

### Project Configuration

add_requires("gtk4")
add_rules("mode.debug", "mode.release")
set_warnings("everything")

target("a")
    set_kind("shared")
    add_defines("BUILDING_ZIM")
    add_packages("gtk4")
    add_files("a.c")
    set_symbols("hidden")

**Comment by Dieken** [comment]
Latest xmake v2.6.6 has same issue:

```
$ ~/.local/bin/xmake -v
[ 25%]: ccache compiling.release a.c
"/usr/bin/xcrun -sdk macosx clang" -c -Qunused-arguments -arch x86_64 -mmacosx-version-min=12.3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -fPIC -fvisibility=hidden -Weverything -O3 -DBUILDING_ZIM -isystem /usr/local/Cellar/libffi/3.4.2/include -isystem /usr/local/Cellar/gtk4/4.6.1/include/gtk-4.0 -isystem /usr/local/Cellar/glib/2.70.4/include/gio-unix-2.0 -isystem /usr/local/Cellar/libepoxy/1.5.9_1/include -isystem /usr/local/Cellar/cairo/1.16.0_5/include/cairo -isystem /usr/local/Cellar/pango/1.50.5/include/pango-1.0 -isystem /usr/local/Cellar/harfbuzz/4.0.1/include/harfbuzz -isystem /usr/local/Cellar/fribidi/1.0.11/include/fribidi -isystem /usr/local/Cellar/graphite2/1.3.14/include -isystem /usr/local/Cellar/gdk-pixbuf/2.42.6/include/gdk-pixbuf-2.0 -isystem /usr/local/Cellar/libpng/1.6.37/include/libpng16 -isystem /usr/local/Cellar/libtiff/4.3.0/include -isystem /usr/local/Cellar/pixman/0.40.0/include/pixman-1 -isystem /usr/local/Cellar/fontconfig/2.13.1/include -isystem /usr/local/opt/freetype/include/freetype2 -isystem /usr/local/Cellar/libxcb/1.14_2/include -isystem /usr/local/Cellar/libxrender/0.9.10/include -isystem /usr/local/Cellar/libxext/1.3.4/include -isystem /usr/local/Cellar/libx11/1.7.3.1/include -isystem /usr/local/Cellar/libxau/1.0.9/include -isystem /usr/local/Cellar/libxdmcp/1.1.3/include -isystem /usr/local/Cellar/graphene/1.10.6/include/graphene-1.0 -isystem /usr/local/Cellar/graphene/1.10.6/lib/graphene-1.0/include -isystem /usr/local/Cellar/glib/2.70.4/include -isystem /usr/local/Cellar/glib/2.70.4/include/glib-2.0 -isystem /usr/local/Cellar/glib/2.70.4/lib/glib-2.0/include -isystem /usr/local/opt/gettext/include -isystem /usr/local/Cellar/pcre/8.45/include -isystem /usr/local/Cellar/xorgproto/2021.5/include -DNDEBUG -o build/.objs/a/macosx/x86_64/release/a.c.o a.c
[ 50%]: linking.release liba.dylib
"/usr/bin/xcrun -sdk macosx clang++" -o build/macosx/x86_64/release/liba.dylib build/.objs/a/macosx/x86_64/release/a.c.o -shared -fPIC -arch x86_64 -mmacosx-version-min=12.3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -stdlib=libc++ -L/usr/local/Cellar/gtk4/4.6.1/lib -L/usr/local/Cellar/pango/1.50.5/lib -L/usr/local/Cellar/harfbuzz/4.0.1/lib -L/usr/local/Cellar/gdk-pixbuf/2.42.6/lib -L/usr/local/Cellar/cairo/1.16.0_5/lib -L/usr/local/Cellar/graphene/1.10.6/lib -L/usr/local/Cellar/glib/2.70.4/lib -L/usr/local/opt/gettext/lib -Wl,-x -lgtk-4 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lgraphene-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl -lz -install_name @rpath/liba.dylib
[100%]: build ok!
```

**Comment by Dieken** [comment]
https://github.com/xmake-io/xmake/blob/master/xmake/modules/lib/detect/pkgconfig.lua#L153

It processes only -I, -L and -l,  this is wrong, throws away -D and other options.

**Comment by waruqi** [comment]
please update to dev and try it again. `xmake update -s dev`

**Comment by Dieken** [comment]
It fixed the issue although failed on another error.

```
[ 25%]: ccache compiling.release zim.c
"/usr/bin/xcrun -sdk macosx clang" -c -Qunused-arguments -arch x86_64 -mmacosx-version-min=12.3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -fPIC -fvisibility=hidden -Weverything -O3 -DBUILDING_ZIM -isystem /usr/local/Cellar/libffi/3.4.2/include -isystem /usr/local/Cellar/gtk4/4.6.1/include/gtk-4.0 -isystem /usr/local/Cellar/glib/2.70.4/include/gio-unix-2.0 -isystem /usr/local/Cellar/libepoxy/1.5.9_1/include -isystem /usr/local/Cellar/cairo/1.16.0_5/include/cairo -isystem /usr/local/Cellar/pango/1.50.5/include/pango-1.0 -isystem /usr/local/Cellar/harfbuzz/4.0.1/include/harfbuzz -isystem /usr/local/Cellar/fribidi/1.0.11/include/fribidi -isystem /usr/local/Cellar/graphite2/1.3.14/include -isystem /usr/local/Cellar/gdk-pixbuf/2.42.6/include/gdk-pixbuf-2.0 -isystem /usr/local/Cellar/libpng/1.6.37/include/libpng16 -isystem /usr/local/Cellar/libtiff/4.3.0/include -isystem /usr/local/Cellar/pixman/0.40.0/include/pixman-1 -isystem /usr/local/Cellar/fontconfig/2.13.1/include -isystem /usr/local/opt/freetype/include/freetype2 -isystem /usr/local/Cellar/libxcb/1.14_2/include -isystem /usr/local/Cellar/libxrender/0.9.10/include -isystem /usr/local/Cellar/libxext/1.3.4/include -isystem /usr/local/Cellar/libx11/1.7.3.1/include -isystem /usr/local/Cellar/libxau/1.0.9/include -isystem /usr/local/Cellar/libxdmcp/1.1.3/include -isystem /usr/local/Cellar/graphene/1.10.6/include/graphene-1.0 -isystem /usr/local/Cellar/graphene/1.10.6/lib/graphene-1.0/include -isystem /usr/local/Cellar/glib/2.70.4/include -isystem /usr/local/Cellar/glib/2.70.4/include/glib-2.0 -isystem /usr/local/Cellar/glib/2.70.4/lib/glib-2.0/include -isystem /usr/local/opt/gettext/include -isystem /usr/local/Cellar/pcre/8.45/include -isystem /usr/local/Cellar/xorgproto/2021.5/include -mfpmath=sse -msse -msse2 -DNDEBUG -o build/.objs/zim/macosx/x86_64/release/zim.c.o zim.c
checking for flags (-MMD -MF) ... ok
checking for flags (-fdiagnostics-color=always) ... ok
error: field '_xxhash' is not callable (a nil value)
```

**Comment by SirLynix** [comment]
Disable cache (--ccache=n) or update xmake core to dev `xmake update dev`

**Comment by waruqi** [comment]
you need update core binary. or you can run `bash <(curl -fsSL https://xmake.io/shget.text) dev` to reinstall it.

**Comment by Dieken** [comment]
Nice, it works! Thank you very much for quick response!
