### ISSUE TITLE
Parallel running of targets

### ISSUE THREAD

**Issue by WubiCookie** [xmake-io/xmake#2389]
### Is your feature request related to a problem? Please describe.

I would like to be able to run all my targets on parallel.

### Describe the solution you'd like

`xmake r -j2 target1 target2 target3 target4`
`xmake r -aj` or `xmake r -j` to run all targets on all available cores
`xmake r -ad` or `xmake r --all --detach` to run all targets on detached processes so that it doesn't block the current process

**Comment by SirLynix** [comment]
Maybe a `xmake run --detach` parameter which would run tasks in detached processes? (will start them sequentially without waiting for them to stop).

**Comment by waruqi** [comment]
I have supported it.

```console
xmake r -jN
xmake r -jN --all
xmake r --detach
```
