### ISSUE TITLE
Ability to add to `AdditionalIncludeDirectories` in VS?

### ISSUE THREAD

**Issue by Qudix** [xmake-io/xmake#2392]
### Is your feature request related to a problem? Please describe.

I'd like to be able to add include dir's to `AdditionalIncludeDirectories` (Additional Include Directories) in Visual Studio
![image](https://user-images.githubusercontent.com/17361645/170809564-4ac7363f-9111-4687-a8cb-7a2eb3b7d27c.png)

### Describe the solution you'd like

I'm unsure if gcc/clang has an option for this too, but perhaps something like `add_additionalincludedirs` or `add_addincludedirs` (that one seems kind of odd).

Another way would be to add an optional parameter to `add_includedirs` to do the same thing.

### Describe alternatives you've considered

I tried using `add_cxxflags("/I<include_path_example>"), but that doesn't seem to work (or at least I can't get it to work).

**Comment by xq114** [comment]
What's the difference between the function of this option and `add_includedirs`?

**Comment by Qudix** [comment]
`add_includedirs` adds to the variable `XmakeIncludeDirs` which is used here
![image](https://user-images.githubusercontent.com/17361645/170838620-22f1ebf5-ca8a-425c-8fed-e1cf02d642d4.png)

**Comment by SirLynix** [comment]
Ok but what does AdditionalIncludeDirs have than this doesn't?

**Comment by Qudix** [comment]
It allows me to use `#include "path/to/header"` rather than the "system" version `#include <path/to/header"` as the system version also includes all of the system libraries.

**Comment by SirLynix** [comment]
Both are valid with add_includedirs.
You can also use add_sysincludedirs to add system includes

**Comment by Qudix** [comment]
`add_sysincludedirs` adds `/external:I <path/to/include>` and I what I want is the non-external version of that

**Comment by Qudix** [comment]
You can see the documentation for it here:
https://docs.microsoft.com/en-us/cpp/build/reference/i-additional-include-directories?view=msvc-170

**Comment by SirLynix** [comment]
I've been using VS projects generated by xmake for over a year without any issue, regarding VS or Intellisense.

Could you send me a small project reproducing the issue?

**Comment by Qudix** [comment]
[Test.zip](https://github.com/xmake-io/xmake/files/8791790/Test.zip)
using `xmake project -k vsxmake2022 build` in my case

Intellisense doesn't show anything when using quotes
![image](https://user-images.githubusercontent.com/17361645/170841301-4e305900-07a9-4c73-83ea-e8fdf4c86201.png)

**Comment by SirLynix** [comment]
![image](https://user-images.githubusercontent.com/3002461/170884931-6f73b51e-feca-4651-8b96-d623d61ab74f.png)
Without changing anything.

However I think we should move $(XmakeIncludeDirs) to Additional Include Directories, as this is what is done with the vs generator.

**Comment by Qudix** [comment]
Did you try with a vanilla VS, because that has extra stuff (like from extensions?)

**Comment by SirLynix** [comment]
You're right, it was one of my extension (Visual Assist) which fixed that for me, if I disable it I encounter the same issue as you.

I made a PR to fix this.

**Comment by waruqi** [comment]
I have merged this pr.
