### ISSUE TITLE
qmake 可以编译 xmake 编译出错

### ISSUE THREAD

**Issue by iujakchu** [xmake-io/xmake#2393]
### Xmake 版本

xmake v2.6.6+master.1cadcda

### 操作系统版本和架构

Arch(5.17.9-arch1-1)

### 描述问题

xmake报错：
```
main.cpp.cpp:(.text+0x383): undefined reference to `vtable for MpvObject'
```
但是qmake是可以成功编译的
会不会是我的xmake.lua 没写对呢
这是pro文件：
```
QT += qml quick

HEADERS += main.h
SOURCES += main.cpp

QT_CONFIG -= no-pkg-config
CONFIG += link_pkgconfig debug
PKGCONFIG += mpv

RESOURCES += mpvtest.qrc

OTHER_FILES += main.qml
```
这是xmake.lua
```
add_rules("mode.debug", "mode.release")
add_requires("mpv")
target("q5")
add_rules("qt.quickapp")
add_headerfiles("src/*.h")
add_files("src/*.cpp")
add_files("src/mpvtest.qrc")
add_packages("mpv")
```

### 期待的结果

成功编译

### 附加信息和错误日志

[ 20%]: ccache compiling.release src/main.cpp
/usr/bin/gcc -c -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++11 -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_QUICK_LIB -DQT_QML_LIB -DQT_CORE_LIB -DQT_NETWORK_LIB -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtGui/5.15.4 -isystem /usr/include/qt/QtGui/5.15.4/QtGui -isystem /usr/include/qt/QtQuick -isystem /usr/include/qt/QtQuick/5.15.4 -isystem /usr/include/qt/QtQuick/5.15.4/QtQuick -isystem /usr/include/qt/QtQml -isystem /usr/include/qt/QtQml/5.15.4 -isystem /usr/include/qt/QtQml/5.15.4/QtQml -isystem /usr/include/qt/QtCore -isystem /usr/include/qt/QtCore/5.15.4 -isystem /usr/include/qt/QtCore/5.15.4/QtCore -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtNetwork/5.15.4 -isystem /usr/include/qt/QtNetwork/5.15.4/QtNetwork -isystem /usr/include/qt -isystem /usr/lib/qt/mkspecs/linux-g++ -DNDEBUG -fPIC -o build/.objs/q5/linux/x86_64/release/src/main.cpp.o src/main.cpp
[ 20%]: compiling.qt.qrc src/mpvtest.qrc
/usr/bin/rcc -name mpvtest src/mpvtest.qrc -o build/.gens/q5/linux/x86_64/release/rules/qt/qrc/mpvtest.cpp
/usr/bin/gcc -c -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++11 -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_QUICK_LIB -DQT_QML_LIB -DQT_CORE_LIB -DQT_NETWORK_LIB -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtGui/5.15.4 -isystem /usr/include/qt/QtGui/5.15.4/QtGui -isystem /usr/include/qt/QtQuick -isystem /usr/include/qt/QtQuick/5.15.4 -isystem /usr/include/qt/QtQuick/5.15.4/QtQuick -isystem /usr/include/qt/QtQml -isystem /usr/include/qt/QtQml/5.15.4 -isystem /usr/include/qt/QtQml/5.15.4/QtQml -isystem /usr/include/qt/QtCore -isystem /usr/include/qt/QtCore/5.15.4 -isystem /usr/include/qt/QtCore/5.15.4/QtCore -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtNetwork/5.15.4 -isystem /usr/include/qt/QtNetwork/5.15.4/QtNetwork -isystem /usr/include/qt -isystem /usr/lib/qt/mkspecs/linux-g++ -DNDEBUG -fPIC -o build/.objs/q5/linux/x86_64/release/gens/rules/qt/qrc/mpvtest.cpp.o build/.gens/q5/linux/x86_64/release/rules/qt/qrc/mpvtest.cpp
[ 60%]: linking.release q5
/usr/bin/g++ -o build/linux/x86_64/release/q5 build/.objs/q5/linux/x86_64/release/src/main.cpp.o build/.objs/q5/linux/x86_64/release/gens/rules/qt/qrc/mpvtest.cpp.o -m64 -L/usr/lib -Wl,-rpath=/usr/lib -s -lmpv -lQt5Gui -lQt5Quick -lQt5Qml -lQt5Core -lQt5Network
error: @programdir/modules/private/async/runjobs.lua:256: @programdir/actions/build/kinds/binary.lua:74: @programdir/core/sandbox/modules/os.lua:257: /usr/bin/ld: build/.objs/q5/linux/x86_64/release/src/main.cpp.o: in function `MpvObject::~MpvObject()':
main.cpp.cpp:(.text+0x383): undefined reference to `vtable for MpvObject'
/usr/bin/ld: build/.objs/q5/linux/x86_64/release/src/main.cpp.o: in function `MpvObject::~MpvObject()':
main.cpp.cpp:(.text+0x3e3): undefined reference to `vtable for MpvObject'
/usr/bin/ld: build/.objs/q5/linux/x86_64/release/src/main.cpp.o: in function `non-virtual thunk to MpvObject::~MpvObject()':
main.cpp.cpp:(.text+0x443): undefined reference to `vtable for MpvObject'
/usr/bin/ld: build/.objs/q5/linux/x86_64/release/src/main.cpp.o: in function `non-virtual thunk to MpvObject::~MpvObject()':
main.cpp.cpp:(.text+0x4b0): undefined reference to `vtable for MpvObject'
/usr/bin/ld: build/.objs/q5/linux/x86_64/release/src/main.cpp.o: in function `MpvObject::MpvObject(QQuickItem*)':
main.cpp.cpp:(.text+0x1862): undefined reference to `vtable for MpvObject'
/usr/bin/ld: main.cpp.cpp:(.text+0x21a2): undefined reference to `MpvObject::onUpdate()'
/usr/bin/ld: main.cpp.cpp:(.text+0x2209): undefined reference to `MpvObject::staticMetaObject'
/usr/bin/ld: build/.objs/q5/linux/x86_64/release/src/main.cpp.o: in function `MpvObject::on_update(void*)':
main.cpp.cpp:(.text+0x511): undefined reference to `MpvObject::onUpdate()'
/usr/bin/ld: build/.objs/q5/linux/x86_64/release/src/main.cpp.o: in function `(anonymous namespace)::on_mpv_redraw(void*)':
main.cpp.cpp:(.text._ZN12_GLOBAL__N_113on_mpv_redrawEPv[_ZN11MpvRenderer23createFramebufferObjectERK5QSize]+0x1): undefined reference to `MpvObject::onUpdate()'
/usr/bin/ld: build/.objs/q5/linux/x86_64/release/src/main.cpp.o: in function `non-virtual thunk to QQmlPrivate::QQmlElement<MpvObject>::~QQmlElement()':
main.cpp.cpp:(.text._ZN11QQmlPrivate11QQmlElementI9MpvObjectED2Ev[_ZN11QQmlPrivate11QQmlElementI9MpvObjectED5Ev]+0x2c): undefined reference to `vtable for MpvObject'
/usr/bin/ld: build/.objs/q5/linux/x86_64/release/src/main.cpp.o: in function `QQmlPrivate::QQmlElement<MpvObject>::~QQmlElement()':
main.cpp.cpp:(.text._ZN11QQmlPrivate11QQmlElementI9MpvObjectED2Ev[_ZN11QQmlPrivate11QQmlElementI9MpvObjectED5Ev]+0xa0): undefined reference to `vtable for MpvObject'
/usr/bin/ld: build/.objs/q5/linux/x86_64/release/src/main.cpp.o: in function `QQmlPrivate::QQmlElement<MpvObject>::~QQmlElement()':
main.cpp.cpp:(.text._ZN11QQmlPrivate11QQmlElementI9MpvObjectED0Ev[_ZN11QQmlPrivate11QQmlElementI9MpvObjectED5Ev]+0x20): undefined reference to `vtable for MpvObject'
/usr/bin/ld: build/.objs/q5/linux/x86_64/release/src/main.cpp.o: in function `non-virtual thunk to QQmlPrivate::QQmlElement<MpvObject>::~QQmlElement()':
main.cpp.cpp:(.text._ZN11QQmlPrivate11QQmlElementI9MpvObjectED0Ev[_ZN11QQmlPrivate11QQmlElementI9MpvObjectED5Ev]+0xac): undefined reference to `vtable for MpvObject'
/usr/bin/ld: build/.objs/q5/linux/x86_64/release/src/main.cpp.o: in function `main':
main.cpp.cpp:(.text.startup+0x56): undefined reference to `MpvObject::staticMetaObject'
/usr/bin/ld: main.cpp.cpp:(.text.startup+0x182): undefined reference to `MpvObject::staticMetaObject'
/usr/bin/ld: main.cpp.cpp:(.text.startup+0x1aa): undefined reference to `MpvObject::staticMetaObject'
/usr/bin/ld: main.cpp.cpp:(.text.startup+0x360): undefined reference to `MpvObject::staticMetaObject'
/usr/bin/ld: main.cpp.cpp:(.text.startup+0x3ce): undefined reference to `MpvObject::staticMetaObject'
/usr/bin/ld: build/.objs/q5/linux/x86_64/release/src/main.cpp.o:(.data.rel.ro._ZTIN11QQmlPrivate11QQmlElementI9MpvObjectEE[_ZTIN11QQmlPrivate11QQmlElementI9MpvObjectEE]+0x10): undefined reference to `typeinfo for MpvObject'
/usr/bin/ld: build/.objs/q5/linux/x86_64/release/src/main.cpp.o:(.data.rel.ro._ZTVN11QQmlPrivate11QQmlElementI9MpvObjectEE[_ZTVN11QQmlPrivate11QQmlElementI9MpvObjectEE]+0x10): undefined reference to `MpvObject::metaObject() const'
/usr/bin/ld: build/.objs/q5/linux/x86_64/release/src/main.cpp.o:(.data.rel.ro._ZTVN11QQmlPrivate11QQmlElementI9MpvObjectEE[_ZTVN11QQmlPrivate11QQmlElementI9MpvObjectEE]+0x18): undefined reference to `MpvObject::qt_metacast(char const*)'
/usr/bin/ld: build/.objs/q5/linux/x86_64/release/src/main.cpp.o:(.data.rel.ro._ZTVN11QQmlPrivate11QQmlElementI9MpvObjectEE[_ZTVN11QQmlPrivate11QQmlElementI9MpvObjectEE]+0x20): undefined reference to `MpvObject::qt_metacall(QMetaObject::Call, int, void**)'
collect2: error: ld returned 1 exit status

stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:872]:
    [@programdir/core/sandbox/modules/os.lua:257]: in function 'runv'
    [@programdir/modules/core/tools/gcc.lua:363]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/actions/build/kinds/binary.lua:74]: in function 'callback'
    [@programdir/modules/core/project/depend.lua:189]: in function 'on_changed'
    [@programdir/actions/build/kinds/binary.lua:55]: in function '_do_link_target'
    [@programdir/actions/build/kinds/binary.lua:102]:
    [@programdir/actions/build/kinds/binary.lua:129]: in function '_link_target'
    [@programdir/actions/build/kinds/binary.lua:157]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:232]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [@programdir/modules/private/async/runjobs.lua:218]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:388]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:872: in function 'os.raiselevel'
	(...tail calls...)
	@programdir/modules/private/async/runjobs.lua:256: in field 'catch'
	@programdir/core/sandbox/modules/try.lua:127: in global 'try'
	@programdir/modules/private/async/runjobs.lua:218: in upvalue 'cotask'
	@programdir/core/base/scheduler.lua:388: in function <@programdir/core/base/scheduler.lua:385>

**Comment by xq114** [comment]
add_files("src/*.h")

qt头文件也需要进行moc编译，因此需要`add_files`

**Comment by iujakchu** [comment]
> add_files("src/*.h")
> 
> qt头文件也需要进行moc编译，因此需要`add_files`

感谢
