### ISSUE TITLE
xmake模块编译错误

### ISSUE THREAD

**Issue by limuy2022** [xmake-io/xmake#2395]
### Xmake 版本

v2.6.6

### 操作系统版本和架构

windows 11 22000.708

### 描述问题

该版本无法支持c++20模块新特性的编译，但它的上一个版本可以正常工作

### 期待的结果

正常生成可执行文件

### 工程配置

set_languages("c++20")

target("main")
    set_kind("binary")
    add_files("*.cpp","*.ixx")

### 附加信息和错误日志

[ 16%]: ccache compiling.release a.ixx
error: @programdir\core\main.lua:280: @programdir\actions\build\main.lua:166: ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:96: ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:56: @programdir\modules\private\async\runjobs.lua:256: @programdir\core\tool\compiler.lua:282: bad argument #-1 to 'args' (string expected, got nil)
stack traceback:
    [C]: in function 'args'
    [@programdir\core\tool\compiler.lua:282]: in function 'compcmd'
    [@programdir\modules\private\action\build\object.lua:79]: in function 'script'
    [@programdir\modules\private\action\build\object.lua:98]: in function 'build_object'
    [@programdir\rules\c++\modules\build_modules\msvc.lua:136]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:232]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:872: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\modules\private\async\runjobs.lua:256: in field 'catch'
        @programdir\core\sandbox\modules\try.lua:127: in global 'try'
        @programdir\modules\private\async\runjobs.lua:218: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:388: in function <@programdir\core\base\scheduler.lua:385>
stack traceback:
        @programdir\core\base\utils.lua:290: in function <@programdir\core\base\utils.lua:280>
        [C]: in function 'error'
        @programdir\core\base\os.lua:872: in function 'os.raiselevel'
        (...tail calls...)
        ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:56: in field 'co_start_withopt'
        @programdir\modules\private\async\runjobs.lua:217: in function <@programdir\modules\private\async\runjobs.lua:162>
        [C]: in function 'xpcall'
        @programdir\core\base\utils.lua:280: in function 'base/utils.trycall'
        @programdir\core\base\scheduler.lua:504: in function 'base/scheduler.co_group_begin'
        ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:94: in field 'co_group_begin'
        @programdir\modules\private\async\runjobs.lua:162: in function <@programdir\modules\private\async\runjobs.lua:56>
        (...tail calls...)
        @programdir\actions\build\build.lua:252: in function <@programdir\actions\build\build.lua:240>
        (...tail calls...)
        @programdir\actions\build\main.lua:103: in global '_do_build'
        @programdir\actions\build\main.lua:150: in function <@programdir\actions\build\main.lua:144>
        [C]: in function 'xpcall'
        @programdir\core\base\utils.lua:280: in function 'base/utils.trycall'
        @programdir\core\sandbox\modules\try.lua:121: in global 'try'
        @programdir\actions\build\main.lua:142: in function <@programdir\actions\build\main.lua:108>
        (...tail calls...)
        [C]: in function 'xpcall'
        @programdir\core\base\utils.lua:280: in function 'base/utils.trycall'
        (...tail calls...)
        @programdir\core\base\task.lua:519: in function 'base/task.run'
        @programdir\core\main.lua:278: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:388: in function <@programdir\core\base\scheduler.lua:385>
stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:872: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:280: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:388: in function <@programdir\core\base\scheduler.lua:385>

**Comment by waruqi** [comment]
更新到 dev 在试下。。xmake update -s dev

**Comment by limuy2022** [comment]
更新到 dev后，xmake正常工作了
