### ISSUE TITLE
generated cmakelists errors

### ISSUE THREAD

**Issue by arkena00** [xmake-io/xmake#2399]
### Xmake Version

2.6.7

### Operating System Version and Architecture

Windows 11

### Describe Bug

When using Qt, the cmakelists contains paths  with \ instead of / and are not surrounded by quotes.
The -subsystem:windows flag produce a link error

Why not using automoc to avoid having a 5k lines cmakelists ?

### Expected Behavior

Usable cmakelists

### Project Configuration

```
add_rules("mode.debug", "mode.release")

target("tmp")
    add_rules("qt.widgetapp")
    add_headerfiles("src/*.h")
    add_files("src/*.cpp")
    add_files("src/mainwindow.ui")
    -- add files with Q_OBJECT meta (only for qt.moc)
    add_files("src/mainwindow.h")
    add_cxflags("/permissive-")
```

**Comment by waruqi** [comment]
let me see your cmakelist.txt

**Comment by arkena00** [comment]
[CMakeLists.txt](https://github.com/xmake-io/xmake/files/8793800/CMakeLists.txt)

**Comment by waruqi** [comment]
please update to dev and try it again. `xmake update -s dev`

**Comment by arkena00** [comment]
Paths are still incorrect for moc custom commands, the rest seems good.

[CMakeLists.txt](https://github.com/xmake-io/xmake/files/8799319/CMakeLists.txt)

There is a property in cmake to have (or not) a console in GUI programs if you need
`set_target_properties(target PROPERTIES WIN32_EXECUTABLE true)`

**Comment by waruqi** [comment]
try it again.

**Comment by arkena00** [comment]
Same
The problem is with the args of the command, some args are fine like
`-I${CMAKE_SOURCE_DIR}/build/.gens/nxi/windows/x64/release/rules/qt/ui`

But the ones with -external are not `-external:ID:\dev\qts\windows\release\include\QtSvg\6.4.0`

[CMakeLists.txt](https://github.com/xmake-io/xmake/files/8801080/CMakeLists.txt)

Btw why not using automoc and autorcc from cmake ? it just requires the Qt path. I was planning to use it with CLion but it's kinda  slow with a1Mo cmakelists so i made my own tool for that but some people could need a lighter generated cmakelists.

**Comment by waruqi** [comment]
try it again. 

> Btw why not using automoc and autorcc from cmake ? it just requires the Qt path. I was planning to use it with CLion but it's kinda slow with a1Mo cmakelists so i made my own tool for that but some people could need a lighter generated cmakelists.

We need control over all paths as we want to be compatible with qt sdk, the qt package in xmake-repo, the vcpkg qt package, the system qt package (apt, pacman ...).

Not all qt environments, will provide a global qt root sdk path.

**Comment by arkena00** [comment]
Everything is good !

I don't know other usecases but i just let you know that's annoying for CLion users to have such a big cmakelists !
