### ISSUE TITLE
Improve generated cmakelists

### ISSUE THREAD

**Issue by arkena00** [xmake-io/xmake#2410]
### Is your feature request related to a problem? Please describe.

Huge size of generated cmakelists

### Describe the solution you'd like

Reduce the size and the number of targets

### Describe alternatives you've considered

I don't know what's the use case of people generating cmakelists but when using it in an IDE, the size and the number of generated targets can really slow the IDE.

I'm not sure to understand why you can't use automoc, the Qt path is supposed to be handled by xmake so you just need to pass the resolved path to the find_package and then use automoc.

Anyway you can still reduce the size by using 2 variables for cl et moc commands parameters and avoiding generating mocs for files not using q_object macro

### Additional context

![unknown](https://user-images.githubusercontent.com/4370057/171168982-78f7e4fb-6cea-491c-af0c-1d9a81904b41.png)
😢 

Let me know what you prefer and i will try to hide those targets, maybe with EXCLUDE_FROM_ALL

**Comment by arkena00** [comment]
```cmake
set_target_properties(xtest PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/build/windows/x64/release")
```

Add the build type prefix for debug release etc ..

Example : 
```cmake
set_target_properties(xtest PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CMAKE_SOURCE_DIR}/build/windows/x64/release")
set_target_properties(xtest PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG "${CMAKE_SOURCE_DIR}/build/windows/x64/debug")
```

Or remove it and let the user choose the build directory

**Comment by waruqi** [comment]
> Reduce the size and the number of targets

It is because that ADD_CUSTOM_COMMAND and PRE_BUILD did not work as I expected, so we need use add_dependencies and fake target to support it.

see https://gitlab.kitware.com/cmake/cmake/-/issues/17802

https://github.com/xmake-io/xmake/blob/a9cc2ad0f1b0695113782cb6ab9333d7c418f280/xmake/plugins/project/cmake/cmakelists.lua#L693-L708

If you have a better solution to this problem, you can reduce the target by at least half.

**Comment by SirLynix** [comment]
We could use AUTOMOC at least for moc generation, and set [AUTOMOC_EXECUTABLE](https://cmake.org/cmake/help/latest/prop_tgt/AUTOMOC_EXECUTABLE.html) so CMake doesn't have to find Qt by itself.

**Comment by arkena00** [comment]
[AUTOMOC_PATH_PREFIX](https://cmake.org/cmake/help/latest/prop_tgt/AUTOMOC_PATH_PREFIX.html)
[AUTOMOC_MOC_OPTIONS](https://cmake.org/cmake/help/latest/prop_tgt/AUTOMOC_MOC_OPTIONS.html)
Yep you have what you need with that, same for AUTORCC



> ```cmake
> set_target_properties(xtest PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/build/windows/x64/release")
> ```

This breaks the paths in CLion because the output will be the same for all modes. For my use case i can just remove this generated line from the cmakelists, but if you need you can add those properties with the *_mode suffix

**Comment by waruqi** [comment]
> This breaks the paths in CLion because the output will be the same for all modes. For my use case i can just remove this generated line from the cmakelists, but if you need you can add those properties with the *_mode suffix

I know there is a problem, but supporting multiple mode switches at the same time would require a lot of code refactoring and a lot of detail consideration. So for the time being it is not supported.

If you are interested, you can also open a pr and refer to the vs generator to improve it.

https://github.com/xmake-io/xmake/blob/95b9be337bcfd48200e6c8ed938f8205540c8dc4/xmake/plugins/project/vstudio/impl/vs201x.lua#L519-L597

**Comment by arkena00** [comment]
> but supporting multiple mode switches at the same time would require a lot of code refactoring and a lot of detail consideration

What about removing RUNTIME_OUTPUT_DIRECTORY from the cmakelists as a hotfix then ? And let cmake use the default path, that's just two lines to comment.

I don't know what people needs when generating cmakelists but for CLion, there is no problem using the default path, it will use the build dir which can be configured in CLion

**Comment by waruqi** [comment]
> > but supporting multiple mode switches at the same time would require a lot of code refactoring and a lot of detail consideration
> 
> What about removing RUNTIME_OUTPUT_DIRECTORY from the cmakelists as a hotfix then ? And let cmake use the default path, that's just two lines to comment.
> 
> I don't know what people needs when generating cmakelists but for CLion, there is no problem using the default path, it will use the build dir which can be configured in CLion

No, the generated output path must be exactly the same as the default configuration of xmake. All generators are consistent with xmake's output path.

But you can modify output path in your xmake.lua by yourself.

```lua
target("xxx")
    set_targetdir("$(buildir)")
```

**Comment by waruqi** [comment]
I have improved it and reduced much custom command target in cmakelists on cxxmodules branch.

https://github.com/xmake-io/xmake/pull/2641

**Comment by waruqi** [comment]
I have merged it now. It should work.
