### ISSUE TITLE
Compile errors when using ccache

### ISSUE THREAD

**Issue by WubiCookie** [xmake-io/xmake#2413]
### Xmake Version

v2.6.7+HEAD.93b724537

### Operating System Version and Architecture

Windows 10 version 1909

### Describe Bug

The compilation fails when using ccache and antislahes (\\) in the code.

With this xmake.lua
```
target("main")
    set_kind("binary")
    add_files("main.cpp")
```

This fails
```
int main()
{
#pragma omp parallel for \
 num_threads(omp_get_max_threads()) \
 private(cj,imax,imin,joffset,ioffset,bij,jbmax,jbmin,i,jb,ib,b_i)

	for (int j = 0; j < 10; ++j)
		;
}
```

This compiles
```
int main()
{
#pragma omp parallel for num_threads(omp_get_max_threads()) private(cj,imax,imin,joffset,ioffset,bij,jbmax,jbmin,i,jb,ib,b_i)

	for (int j = 0; j < 10; ++j)
		;
}
```

And both compile with `xmake f --policies=build.ccache:n`

### Expected Behavior

It should compile in any cases

### Additional Information and Error Logs

```
> xmake
[ 25%]: ccache compiling.release main.cpp
error: main.cpp.cpp
main.cpp(4): error C2061: syntax error: identifier 'num_threads'
main.cpp(7): error C2065: 'j': undeclared identifier
main.cpp(7): error C2065: 'j': undeclared identifier
main.cpp(7): error C2059: syntax error: ')'

  > in main.cpp
```

**Comment by waruqi** [comment]
> The compilation fails when using ccache and antislahes (\) in the code.

`cl.exe /E` and `cl.exe /P` cannot preprocess `\` and expand them. I don't know if there are other parameter options to allow the preprocessor to expand them automatically.

BTW， I fixed a cache prolicy bug, you can update to dev and try `xmake f --ccache=n` to disable ccache.

**Comment by waruqi** [comment]
I tested and this is only `#pragma omp parallel for \`

In most other cases, `\` in the code works well.

It works too if we use following code.
```
#pragma omp parallel for num_threads(omp_get_max_threads()) \
 private(cj,imax,imin,joffset,ioffset,bij,jbmax,jbmin,i,jb,ib,b_i)
```

or 

```c
#   pragma comment(lib, \
    "Ws2_32.lib")
int main() \
{
#define XXX 1\
444

#pragma omp parallel for num_threads(omp_get_max_threads()) \
 private(cj,imax,imin,joffset,ioffset,bij,jbmax,jbmin,i,jb,ib,b_i)
	for (int j = 0; j < XXX; ++j)
		;
    return 0;
}
```

**Comment by waruqi** [comment]
I don't have a good solution for now, you can change the code or disable the cache.

```
#pragma omp parallel for num_threads(omp_get_max_threads()) \
 private(cj,imax,imin,joffset,ioffset,bij,jbmax,jbmin,i,jb,ib,b_i)
```

**Comment by WubiCookie** [comment]
That's what we did for now, but the faulty code is actually generated. We will probably give it to clang-format to fix this automatically if there's no fix in xmake directly

**Comment by waruqi** [comment]
I have improved it on dev. you can try it again. xmake update -s dev

xmake will fallback to compile original source file automatically if compiling preprocessed file fails.
