### ISSUE TITLE
Target all exists but does nothing

### ISSUE THREAD

**Issue by arkena00** [xmake-io/xmake#2414]
### Xmake Version

xmake v2.6.7+dev.0428cdc48

### Operating System Version and Architecture

Windows 11

### Describe Bug

```
PS D:\tmp\xtest> xmake build all
[100%]: build ok!
PS D:\tmp\xtest> xmake build rng
error: unknown target: rng
PS D:\tmp\xtest> xmake build --all
[ 60%]: linking.release xtest2.exe
[ 60%]: linking.release xtest.exe
[100%]: build ok!
```

The behaviour of the "all" target is not well defined

### Expected Behavior

1) Remove the all target and let the user use this name
2) Use the all target as a special target to build all targets (cmake behaviour)

For 1), the all target should not exists and produce an error message

**Comment by waruqi** [comment]
This is a legacy code.
I have deleted it, you can try again after updating to dev

**Comment by arkena00** [comment]
That's good !
