### ISSUE TITLE
Better logging/error message

### ISSUE THREAD

**Issue by arkena00** [xmake-io/xmake#2421]
### Is your feature request related to a problem? Please describe.

Some of logging / error message are not clear or not accurate.

### Describe the solution you'd like

- Display more information about the compiler version, we only have the VS version atm
`compiler ID : MSVC 19.32.31329.0`
`compiler path : %programs%/.../cl.exe`

- The config options errors are not clear because there is no distinction between user and xmake config
> error: Invalid option: --rng=on
When an option doesn't exists, we are flooded by the config help instead of just having a warning like "option ignored"

So maybe add a distinction between user and xmake configs like
`xmake f -xqt=path -xarch=x64 --user_option=v`
It would break the current version so maybe in another one.

Same for the xmake.lua errors, when you come from cmake, the errors are harder to identify

**Comment by arkena00** [comment]
Some packages can take time to download/install, by default we have no information about the state.
Maybe display a progressbar and/or the last output message on a single line to avoid flooding.

**Comment by waruqi** [comment]
> Some packages can take time to download/install, by default we have no information about the state.
Maybe display a progressbar and/or the last output message on a single line to avoid flooding.

We cannot capture download progress from curl/wget, but you can add `-vD`  to get more verbose information.

**Comment by waruqi** [comment]
I have improved to show msvc info.

```console
checking for Microsoft Visual Studio (x64) version ... 2019
checking for Microsoft C/C++ Compiler (x64) version ... 19.29.30137
```

But cl full path is too long, so you can only show it when enable `-v`

```console
$ xmake f -cv
checking for cl.exe ... C:\Program Files (x86)\Microsoft Visual Studio\2019\Comm
unity\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe
checking for link.exe ... C:\Program Files (x86)\Microsoft Visual Studio\2019\Co
mmunity\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe
```
