### ISSUE TITLE
Custom project templates

### ISSUE THREAD

**Issue by arkena00** [xmake-io/xmake#2423]
### Is your feature request related to a problem? Please describe.

Not really a problem, just a cool thing !

### Describe the solution you'd like

- Create a directory structure with all templates and config files and maybe a .xmake-template.lua to initialize some stuffs like git
Structure : 
```
ark/
  .global/
  - .clang-format
  - mit_license
  cpp/
    testing/
      - .xmake-template.lua
      - xmake.lua
    project/
      - .xmake-template.lua
      - xmake.lua
      - .gitignore
      - .clang-format.xmake-ref // (text file containing the path to the file ex: "$root/.global/.clang-format")
    source/
      - main.cpp
      -  __name__/  //  replaced by the name config value
    include/
      -  __name__/ 
```
- Generate from the template
`xmake create -t ark/cpp/project --name=ark_project --git --mit` (config values passed to .xmake-template.lua)

- .xmake-template.lua (pseudo code)
```
// run custom commands
if has_config("git") run("git init")
if has_config("mit") copy("ark/.global/mit_license", ".")
```

**Comment by arkena00** [comment]
I made a tool for that, so i don't need it anymore and i guess that's not a priority :p

**Comment by scruel** [comment]
Thanks for your work, about this feature, I think is a good idea, so why not? Any chance to reopen it?
