### ISSUE TITLE
Add commit hash when updating

### ISSUE THREAD

**Issue by arkena00** [xmake-io/xmake#2426]
### Is your feature request related to a problem? Please describe.

`xmake update -s`
> xmake v2.6.7 has been installed!
We don't know the exact version of the sources and the --version command is not up to date using this command

### Describe the solution you'd like

`xmake update -s`
> xmake v2.6.7+dev.0428cdc48 has been installed!

Display the full version when updating the sources so we can provide it for issues

**Comment by waruqi** [comment]
you need run `xmake update` or `xmake update dev` without script-only mode `-s`. it will update commit in `xmake --version`

```
$ xmake --version
xmake v2.6.7+HEAD.93b7245, A cross-platform build utility based on Lua
```
