### ISSUE TITLE
ucrt headers not found

### ISSUE THREAD

**Issue by arkena00** [xmake-io/xmake#2427]
### Xmake Version

2.6.7

### Operating System Version and Architecture

Windows 11

### Describe Bug

Using msvc 19.32.31329 | kit 10.0.22000.0
Headers are not found
`add_sysincludedirs("ucrt_path")` fix the errors

### Expected Behavior

Find headers

### Project Configuration

```lua
set_languages("clatest")

target("xtest")
    set_kind("binary")
    add_files("src/main.c")
```

### Additional Information and Error Logs

```c
#include <stdio.h>

int main(int argc, char** argv)
{
    printf("");
}
```

```
PS D:\tmp\xtest> xmake -v
[ 25%]: ccache compiling.release src\main.c
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\cl.exe" -c -nologo -Ox -fp:fast -std:c17 -DNDEBUG -Fobuild\.objs\xtest\windows\x64\release\src\main.c.obj src\main.c
error: main.c
src\main.c(1): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
```

**Comment by arkena00** [comment]
Ok it seems that the `xmake clean` command doesn't check for invalid global cached values so after a VS upgrade, paths are invalid. I would suggest to add a check for invalid paths in the global cache after a clean.

**Comment by waruqi** [comment]
you need run `xmake g -c` after a vs upgrade
