### ISSUE TITLE
Install packages as sources/submodules

### ISSUE THREAD

**Issue by arkena00** [xmake-io/xmake#2428]
### Is your feature request related to a problem? Please describe.

I want to use a packages as submodules and in-project sources

### Describe the solution you'd like

```lua
-- path is specified, sources are copied into the project directory
add_requires("sqlite3", { type = "source", path = "third_party" })
-- path is not specified, use the default packages directory
add_requires("sqlite3", { type = "source" })
```
So we can use amalgamation files or get the sources and edit them easily 

```lua
-- use git add submodule
add_requires("libcustom", { type = "submodule", path="third_party" })
```

### Describe alternatives you've considered

I don't know what syntax to suggest as i don't know very well lua and you api

**Comment by waruqi** [comment]
see https://xmake.io/#/package/local_3rd_source_library

**Comment by waruqi** [comment]
The c++ libraries are not like the go/rust libraries, and most of the time it is not possible to introduce a git url and have it compile completely. If you look at the cmake packages in xmake-repo, many of them require additional configuration and even many patches to get them to compile.

Therefore, it is essential to define packages, and introducing them directly via a git url is very unreliable.

If your cmake is simple, it will compile perfectly well. Then even if you define packages, it's only a few lines of configuration and not very complicated.

```lua
package("sqlite3")
    set_sourcedir(path.join(os.scriptdir(), "sqlite3"))
    on_install(function (package)
        import("package.tools.cmake").install(package)
    end)
package_end()

add_requires("sqlite3")
```

only 8 lines.

But if your cmake package is complex and requires all sorts of extra configuration to ensure that it compiles through. Then you have to define the package and it simply won't work the way you say.

```lua
package("pcre2")
    set_sourcedir(path.join(os.scriptdir(), "pcre2"))
    on_load(function (package)
        local bitwidth = package:config("bitwidth") or "8"
        if package:version():ge("10.39") and package:is_plat("windows") and not package:config("shared") then
            package:add("links", "pcre2-" .. bitwidth .. "-static")
        else
            package:add("links", "pcre2-" .. bitwidth)
        end
        package:add("defines", "PCRE2_CODE_UNIT_WIDTH=" .. bitwidth)
        if not package:config("shared") then
            package:add("defines", "PCRE2_STATIC")
        end
    end)

    on_install(function (package)
        if package:version():lt("10.21") then
            io.replace("CMakeLists.txt", [[SET(CMAKE_C_FLAGS -I${PROJECT_SOURCE_DIR}/src)]], [[SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -I${PROJECT_SOURCE_DIR}/src")]], {plain = true})
        end
        local configs = {"-DPCRE2_BUILD_TESTS=OFF", "-DPCRE2_BUILD_PCRE2GREP=OFF"}
        table.insert(configs, "-DBUILD_SHARED_LIBS=" .. (package:config("shared") and "ON" or "OFF"))
        table.insert(configs, "-DPCRE2_SUPPORT_JIT=" .. (package:config("jit") and "ON" or "OFF"))
        local bitwidth = package:config("bitwidth") or "8"
        if bitwidth ~= "8" then
            table.insert(configs, "-DPCRE2_BUILD_PCRE2_8=OFF")
            table.insert(configs, "-DPCRE2_BUILD_PCRE2_" .. bitwidth .. "=ON")
        end
        if package:debug() then
            table.insert(configs, "-DPCRE2_DEBUG=ON")
        end
        if package:is_plat("windows") then
            table.insert(configs, "-DPCRE2_STATIC_RUNTIME=" .. (package:config("vs_runtime"):startswith("MT") and "ON" or "OFF"))
        end
        import("package.tools.cmake").install(package, configs)
    end)
```

If you have a way to make xmake automatically know if it can build it successfully, and no additional configuration is needed, just set a git url. You can tell me.

**Comment by arkena00** [comment]
I totally agree when those libraries are external libraries (i mean external to the user project and the user has no control on it), the current system is great. And i didn't mean to compile libraries external to the user project with another build system. I will be more specific;

There is somecases where the users wants/needs to modify the sources or use a submodule architecture.
# In-Source
Some libraries are designed to be built directly using the sources providing amalgamation files (or multiples files). So to use them, we just copy the files to our project, add some defines and build.
With sqlite3 for example, the sources could be part of the current sqlite3 package and we could select between static/shared/source library type

**Currently**
```lua
-- goto sqlite website
-- copy the sources
    add_files("third_party/src/sqlite3.c")
    add_headerfiles("third_party/src/sqlite3.h")
-- we have 2 different ways to manage external code (xmake + local third_party)
```

**Could be**
```lua
add_requires("sqlite3-dev") // or w/e the syntax
-- 1 way to manage add_requires("nds")
-- we can modify the source code depending on if we use a local repo or not
```

I don't know if it would requires a lot of change to handle that so i would understand that's not a priority if you need to make a lot of modifications.

# Submodules
For the submodules, i was not talking about handling libraries external to the current project or building with other build systems.
Some projects use this architecture in the same project so the user has control on all those libraries.
I was suggesting supporting submodules for xmake only, all libraries would use xmake to build. If the project user switch to xmake, he just has to add a xmake.lua to his submodules, the transition is really easy.


I think having one interface (add_requires) to handle all cases of external code could be very powerful. Compiled libraries are so easy to use with xmake, would be so cool to handle sources and submodules the same way, even if it's not a priority :)

**Comment by waruqi** [comment]
If you just want to use xmake to maintain submodules, then there must also be an xmake.lua file inside the submodule project to maintain them, as different source files, they also have different compilation options.

Of course, in this case, there is really no need to define packages, but there is even less need to use add_requires.

Wouldn't it be simpler to simply use includes + add_deps to integrate them?

```lua
includes("submodules/*/xmake.lua")

target("test")
     add_deps("sqlite3", ...)
```

use `includes("submodules/*/xmake.lua")`, all subprojects in your submodule directory will be loaded automatically. If the submodule directories do not exist, they do not have any negative impact.
