### ISSUE TITLE
add_files cannot detect the file generated in before_build

### ISSUE THREAD

**Issue by iujakchu** [xmake-io/xmake#2430]
### Xmake 版本

v2.6.7+master.2ae835d

### 操作系统版本和架构

Arch

### 描述问题

add_files [不能检测](https://github.com/iujakchu/cxx-xmake-example/runs/6722999764?check_suite_focus=true)到before_build中生成的文件
我在before build里cp了几个文件到指定目录，
第一次xmake会报错：
```
warning: cannot match target(xm).add_files("after/lib.rs.cc") at ./xmake.lua:21
```
第二次xmake 可以成功编译，类似的add_includedirs没有这个问题

### 期待的结果

add_files 可以识别 before_build中生成的文件

### 工程配置

add_rules("mode.release")

local rust_backend = "back"
target("xm")
before_build(function(target)
	os.cd("back")
	os.exec("cargo build --release --verbose")
	os.cd("..")
	os.mkdir("after", "after/include")
	os.cp("back/target/cxxbridge/back/src/*.h", "after/include/")
	os.cp("back/target/cxxbridge/back/src/*.cc", "after/")
	os.cp("back/target/cxxbridge/rust/*.h", "after/include/")
end)
set_toolchains("clang-13")
set_languages("cxx17")
set_kind("binary")

add_files("src/*.cpp")
add_includedirs("src/include")

add_files("after/lib.rs.cc")
add_includedirs("after/include")

add_links("stdc++")
add_linkdirs(rust_backend .. "/target/release/")
add_links(rust_backend)

add_cxflags("-flto=thin")
add_ldflags("-flto=thin")
add_ldflags("-fuse-ld=mold")

### 附加信息和错误日志

https://github.com/iujakchu/cxx-xmake-example/runs/6722999764?check_suite_focus=true

**Comment by Domain** [comment]
> 设置 always_added 到 add_files
> 
> [#1090 (comment)](https://github.com/xmake-io/xmake/issues/1090#issuecomment-889576769)

always_added可以支持通配符吗？就是**.cpp？因为我并不知道会生成什么文件

**Comment by Domain** [comment]
> 仔细看下 [#1090 (comment)](https://github.com/xmake-io/xmake/issues/1090#issuecomment-889576769)
> 
> 不就还是 add_files 么，该怎么支持就怎么支持

我看到#1540里面说到：
>However, we also need to pay attention to that, since the currently automatically generated source file may not yet exist, we cannot use pattern matching in add_files("src/*.cpp", {always_added = true}), we only can add each source file path explicitly.

好像不支持还不存在而且不知道名字的文件

**Comment by waruqi** [comment]
可以参考下 https://github.com/xmake-io/xmake-repo/blob/master/packages/l/luajit/port/xmake.lua
