### ISSUE TITLE
Can't compile a set_default(false) target with vsxmake2022 project

### ISSUE THREAD

**Issue by WubiCookie** [xmake-io/xmake#2432]
### Xmake Version

2.6.7

### Operating System Version and Architecture

Windows 10 version 1909

### Describe Bug

With this script,
```lua
target("main")
    set_default(false)
    set_kind("binary")
    add_files("main.cpp")
```
the target is never built, even when specifically rebuilding it from Visual Studio.

My use case is a test target for a library. I don't want the tests to automatically be built and/or installed and/or packaged, but I still want to be able to execute them from vs when I'm working on the library.

### Expected Behavior

The target should be built

### Additional Information and Error Logs

Visual Studio output:
```
Rebuild started...
1>------ Rebuild All started: Project: main, Configuration: release x64 ------
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

**Comment by waruqi** [comment]
I have merged this patch https://github.com/xmake-io/xmake/pull/2433
