### ISSUE TITLE
Allow to handle multiples plugin repositories

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#2434]
### Is your feature request related to a problem? Please describe.

Currently, xmake plugins are not very used, in fact only the official xmake repository can be used for plugins (with most plugins included in base repository), which makes plugins basically useless.

xmake plugins can be useful to add and maintains tasks related to multiple projects, for example I have a task that can refactor includes for projects using my coding style. Currently it's on only one of my repository but I'd like to have and share it to use it on multiple repositories without having to duplicate them.

### Describe the solution you'd like

I suggest to have something like xmake repositories:
```
xmake plugin --install <github url>
```

with update using
```
xmake plugin --update
```
which would update all plugins repositories.

**Comment by waruqi** [comment]
I have supported it.

**Comment by SirLynix** [comment]
```
D:\>xmake plugin --install https://github.com/SirLynix/xmake-plugins
installing plugins from https://github.com/SirLynix/xmake-plugins ..
  -> config-update
all plugins have been installed in C:\Users\lynix\AppData\Local\.xmake\plugins!

D:\>xmake plugin --update
updating plugins from https://github.com/SirLynix/xmake-plugins ..
  -> config-update
all plugins have been updated in C:\Users\lynix\AppData\Local\.xmake\plugins!
```

I can confirm it works well! Thanks a lot!
