### ISSUE TITLE
从已经克隆好的本地目录更新xmake的lua脚本。

### ISSUE THREAD

**Issue by coucya** [xmake-io/xmake#2436]
### 你在什么场景下需要该功能？

我的xmake是用包管理器安装的，不是使用源码编译安装的，安装的xmake和克隆的xmake源码是分开的，在修改xmake的lua源码后需要安装测试。

### 描述可能的解决方案

xmake update -s ./

### 描述你认为的候选方案

xmake update -s -d ./
xmake update -s --developer ./

**Comment by waruqi** [comment]
包管理器安装的 默认会装到 /usr/ 下，需要处理权限问题，所以目前不支持自更新

如果要支持自更新，请用 官方推荐的一键脚本安装。

如果要调试源码，可以进到 xmake 源码仓库，编译后，直接加载本地源码环境来测试，不需要安装

```console
cd xmake_source
make
source ./scripts/srcenv.profile
```
