### ISSUE TITLE
STM32 M4编译报错

### ISSUE THREAD

**Issue by robomentor** [xmake-io/xmake#2441]
### Xmake 版本

v2.6.7

### 操作系统版本和架构

Windows Feature Experience Pack 120.2212.4170.0

### 描述问题

基于STM32F427IIH6（cortex-m4）的嵌入式程序，目前尝试从原来的Gcc+make编译方式迁移到xmake，过程中遇到一些问题。

### 期待的结果

能够顺利编译出.elf文件

### 工程配置

`lua
add_rules("mode.debug", "mode.release")

toolchain("arm-none-eabi")
    set_kind("standalone")
    set_sdkdir("F:/ProgramFiles/gcc/arm-none-eabi-windows")
toolchain_end()

-- 编译配置
target("firmware")

    set_kind("binary")

    set_toolchains("arm-none-eabi")

    -- 设置要编译的.c源文件
    add_files(
        "./System/startup_gcc.s",
        "./Source/app/src/*.c",
        "./Source/main/src/*.c",
        "./Source/modular/src/*.c",
        "./Source/robot/base/src/*.c",
        "./Source/utils/src/*.c",
        "./FreeRTOS/*.c",
        "./FreeRTOS/portable/GCC/ARM_CM4F/port.c",
        "./FreeRTOS/portable/MemMang/heap_4.c",
        "./System/core/src/*.c",
        "./System/driver/src/*.c",
        "./System/usb/USB_Driver/src/usb_bsp.c",
        "./System/usb/USB_Driver/src/usb_core.c",
        "./System/usb/USB_Driver/src/usb_dcd.c",
        "./System/usb/USB_Driver/src/usb_dcd_int.c",
        "./System/usb/USB_Library/Core/src/usbd_cdc_vcp.c",
        "./System/usb/USB_Library/Core/src/usbd_core.c",
        "./System/usb/USB_Library/Core/src/usbd_desc.c",
        "./System/usb/USB_Library/Core/src/usbd_ioreq.c",
        "./System/usb/USB_Library/Core/src/usbd_req.c",
        "./System/usb/USB_Library/Core/src/usbd_usr.c",
        "./System/usb/USB_Library/Class/cdc/src/usbd_cdc_core.c"
    )

    -- 设置要排除的.c源文件
    remove_files(
        "./System/driver/src/stm32f4xx_fsmc.c"
    )

    -- 设置要编译的.h头文件目录
    add_includedirs(
        "./Source/app/inc",
        "./Source/main/inc",
        "./Source/modular/inc",
        "./Source/robot/base/inc",
        "./Source/utils/inc",
        "./FreeRTOS/include",
        "./FreeRTOS/portable/GCC/ARM_CM4F",
        "./System/core/inc",
        "./System/driver/inc",
        "./System/usb/USB_Driver/inc",
        "./System/usb/USB_Library/Class/cdc/inc",
        "./System/usb/USB_Library/Core/inc"
    )

    -- 设置宏定义
    add_defines(
        "USE_STDPERIPH_DRIVER",
        "STM32F427_437xx",
        "USE_STM324x9I_EVAL",
        "USE_USB_OTG_FS",
        "USE_ULPI_PHY"
    )

    add_cflags(
        "-O3",
        "-mcpu=cortex-m4",
        "-mfpu=fpv4-sp-d16 -mfloat-abi=hard",
        "-mthumb",
        "-Wall -fdata-sections -ffunction-sections",
        "-g -gdwarf-2",{force = true}
    )

    add_asflags(
        "-O3",
        "-mcpu=cortex-m4",
        "-mfpu=fpv4-sp-d16 -mfloat-abi=hard",
        "-x assembler-with-cpp",
        "-mthumb",
        "-Wall -fdata-sections -ffunction-sections",
        "-g -gdwarf-2",{force = true}
    )

    add_ldflags(
        "-O3",
        "-mcpu=cortex-m4",
        "-mfpu=fpv4-sp-d16 -mfloat-abi=hard",
        "-L./",
        "-TSystem/STM32F437IIHx_FLASH.ld",
        "-Wl,--gc-sections",
        "-lc -lm -lnosys -u _printf_float",{force = true}
    )

    -- 设置编译目录，必须为Build
    set_targetdir("Build")

    -- 设置生成的文件名，必须为firmware.elf
    set_filename("firmware.elf")

    -- 生成HEX、BIN文件
    after_build(function(target)
        print("---------- Complete Build ---------")
        os.exec("arm-none-eabi-objcopy -O ihex ./Build//firmware.elf ./build//firmware.hex")
    end)
`

### 附加信息和错误日志

`sh
PS D:\Geek_Lite_Board\hardware> xmake -vD
checking for arm-none-eabi-gcc ... F:\ProgramFiles\gcc\arm-none-eabi-windows\bin\arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for the c compiler (cc) ... arm-none-eabi-gcc
checking for F:\ProgramFiles\gcc\arm-none-eabi-windows\bin\arm-none-eabi-gcc ... ok
checking for flags (-fPIC) ... ok
> arm-none-eabi-gcc "-fPIC"
checking for flags (-O3) ... ok
> arm-none-eabi-gcc "-O3"
checking for flags (-DNDEBUG) ... ok
> arm-none-eabi-gcc "-DNDEBUG"
[  1%]: ccache compiling.release Source\app\src\app.c
F:\ProgramFiles\gcc\arm-none-eabi-windows\bin\arm-none-eabi-gcc -c -fvisibility=hidden -ISource\app\inc -ISource\main\inc -ISource\modular\inc -ISource\robot\base\inc -ISource\utils\inc -IFreeRTOS\include -IFreeRTOS\portable\GCC\ARM_CM4F -ISystem\core\inc -ISystem\driver\inc -ISystem\usb\USB_Driver\inc -ISystem\usb\USB_Library\Class\cdc\inc -ISystem\usb\USB_Library\Core\inc -DUSE_STDPERIPH_DRIVER -DSTM32F427_437xx -DUSE_STM324x9I_EVAL -DUSE_USB_OTG_FS -DUSE_ULPI_PHY -O3 -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -Wall -fdata-sections -ffunction-sections -g -gdwarf-2 -DNDEBUG -o build\.objs\firmware\cross\cortex-m4\release\Source\app\src\app.c.o Source\app\src\app.c
...........
> arm-none-eabi-gcc "-MMD" "-MF" "C:\Users\MAKERY~1\AppData\Local\Temp\.xmake\220608\_1325CFBD2D484A108C87F3F5B84B3280"
checking for flags (-fdiagnostics-color=always) ... ok
> arm-none-eabi-gcc "-fdiagnostics-color=always"
checking for arm-none-eabi-g++ ... F:\ProgramFiles\gcc\arm-none-eabi-windows\bin\arm-none-eabi-g++
checking for the linker (ld) ... arm-none-eabi-g++
checking for F:\ProgramFiles\gcc\arm-none-eabi-windows\bin\arm-none-eabi-g++ ... ok
checking for flags (-fPIC) ... no
> arm-none-eabi-g++ "-fPIC"
checkinfo: @programdir\core\sandbox\modules\os.lua:257: f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/lib\libc.a(lib_a-exit.o): in function `exit':
exit.c:(.text.exit+0x2c): undefined reference to `_exit'
collect2.exe: error: ld returned 1 exit status

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:872]:
    [@programdir\core\sandbox\modules\os.lua:257]: in function 'runv'
    [@programdir\modules\detect\tools\gcc\has_flags.lua:42]:
[ 97%]: linking.release firmware.elf
F:\ProgramFiles\gcc\arm-none-eabi-windows\bin\arm-none-eabi-g++ -o Build\firmware.elf build\.objs\firmware\cross\cortex-m4\release\System\startup_gcc.s.o build\.objs\firmware\cross\cortex-m4\release\Source\app\src\app.c.o build\.objs\firmware\cross\cortex-m4\release\Source\main\src\main.c.o build\.objs\firmware\cross\cortex-m4\release\Source\main\src\serial_task.c.o build\.objs\firmware\cross\cortex-m4\release\Source\main\src\system_task.c.o build\.objs\firmware\cross\cortex-m4\release\Source\main\src\user_task.c.o build\.objs\firmware\cross\cortex-m4\release\Source\modular\src\adc.c.o build\.objs\firmware\cross\cortex-m4\release\Source\modular\src\buzzer.c.o build\.objs\firmware\cross\cortex-m4\release\Source\modular\src\can.c.o build\.objs\firmware\cross\cortex-m4\release\Source\modular\src\cpu.c.o build\.objs\firmware\cross\cortex-m4\release\Source\modular\src\hmi.c.o build\.objs\firmware\cross\cortex-m4\release\Source\modular\src\io.c.o build\.objs\firmware\cross\cortex-m4\release\Source\modular\src\key.c.o build\.objs\firmware\cross\cortex-m4\release\Source\modular\src\led.c.o build\.objs\firmware\cross\cortex-m4\release\Source\modular\src\modular.c.o build\.objs\firmware\cross\cortex-m4\release\Source\modular\src\mpu.c.o build\.objs\firmware\cross\cortex-m4\release\Source\modular\src\power.c.o build\.objs\firmware\cross\cortex-m4\release\Source\modular\src\pwm.c.o build\.objs\firmware\cross\cortex-m4\release\Source\modular\src\pwm_motor.c.o build\.objs\firmware\cross\cortex-m4\release\Source\modular\src\radar.c.o build\.objs\firmware\cross\cortex-m4\release\Source\modular\src\rocker.c.o build\.objs\firmware\cross\cortex-m4\release\Source\modular\src\servo.c.o build\.objs\firmware\cross\cortex-m4\release\Source\modular\src\usb.c.o build\.objs\firmware\cross\cortex-m4\release\Source\modular\src\wifi.c.o build\.objs\firmware\cross\cortex-m4\release\Source\robot\base\src\robot.c.o build\.objs\firmware\cross\cortex-m4\release\Source\utils\src\cjson.c.o build\.objs\firmware\cross\cortex-m4\release\Source\utils\src\delay.c.o build\.objs\firmware\cross\cortex-m4\release\Source\utils\src\utils.c.o build\.objs\firmware\cross\cortex-m4\release\FreeRTOS\croutine.c.o build\.objs\firmware\cross\cortex-m4\release\FreeRTOS\event_groups.c.o build\.objs\firmware\cross\cortex-m4\release\FreeRTOS\list.c.o build\.objs\firmware\cross\cortex-m4\release\FreeRTOS\queue.c.o build\.objs\firmware\cross\cortex-m4\release\FreeRTOS\tasks.c.o build\.objs\firmware\cross\cortex-m4\release\FreeRTOS\timers.c.o build\.objs\firmware\cross\cortex-m4\release\FreeRTOS\portable\GCC\ARM_CM4F\port.c.o build\.objs\firmware\cross\cortex-m4\release\FreeRTOS\portable\MemMang\heap_4.c.o build\.objs\firmware\cross\cortex-m4\release\System\core\src\stm32f4xx_it.c.o build\.objs\firmware\cross\cortex-m4\release\System\core\src\system_stm32f4xx.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\misc.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_adc.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_can.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_cec.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_crc.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_cryp.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_cryp_aes.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_cryp_des.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_cryp_tdes.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_dac.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_dbgmcu.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_dcmi.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_dfsdm.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_dma.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_dma2d.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_dsi.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_exti.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_flash.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_flash_ramfunc.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_fmc.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_fmpi2c.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_gpio.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_hash.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_hash_md5.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_hash_sha1.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_i2c.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_iwdg.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_lptim.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_ltdc.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_pwr.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_qspi.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_rcc.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_rng.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_rtc.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_sai.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_sdio.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_spdifrx.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_spi.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_syscfg.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_tim.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_usart.c.o build\.objs\firmware\cross\cortex-m4\release\System\driver\src\stm32f4xx_wwdg.c.o build\.objs\firmware\cross\cortex-m4\release\System\usb\USB_Driver\src\usb_bsp.c.o build\.objs\firmware\cross\cortex-m4\release\System\usb\USB_Driver\src\usb_core.c.o build\.objs\firmware\cross\cortex-m4\release\System\usb\USB_Driver\src\usb_dcd.c.o build\.objs\firmware\cross\cortex-m4\release\System\usb\USB_Driver\src\usb_dcd_int.c.o build\.objs\firmware\cross\cortex-m4\release\System\usb\USB_Library\Core\src\usbd_cdc_vcp.c.o build\.objs\firmware\cross\cortex-m4\release\System\usb\USB_Library\Core\src\usbd_core.c.o build\.objs\firmware\cross\cortex-m4\release\System\usb\USB_Library\Core\src\usbd_desc.c.o build\.objs\firmware\cross\cortex-m4\release\System\usb\USB_Library\Core\src\usbd_ioreq.c.o build\.objs\firmware\cross\cortex-m4\release\System\usb\USB_Library\Core\src\usbd_req.c.o build\.objs\firmware\cross\cortex-m4\release\System\usb\USB_Library\Core\src\usbd_usr.c.o build\.objs\firmware\cross\cortex-m4\release\System\usb\USB_Library\Class\cdc\src\usbd_cdc_core.c.o -s -O3 -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -L./ -TSystem/STM32F437IIHx_FLASH.ld -Wl,--gc-sections -lc -lm -lnosys -u _printf_float
error: @programdir\modules\private\async\runjobs.lua:256: @programdir\actions\build\kinds\binary.lua:74: @programdir\core\sandbox\modules\os.lua:257: f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\libc.a(lib_a-sbrkr.o): in function `_sbrk_r':
sbrkr.c:(.text._sbrk_r+0xc): undefined reference to `_sbrk'
f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\libc.a(lib_a-writer.o): in function `_write_r':
writer.c:(.text._write_r+0x14): undefined reference to `_write'
f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\libc.a(lib_a-closer.o): in function `_close_r':
closer.c:(.text._close_r+0xc): undefined reference to `_close'
f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\libc.a(lib_a-lseekr.o): in function `_lseek_r':
lseekr.c:(.text._lseek_r+0x14): undefined reference to `_lseek'
f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\libc.a(lib_a-readr.o): in function `_read_r':
readr.c:(.text._read_r+0x14): undefined reference to `_read'
f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\libc.a(lib_a-abort.o): in function `abort':
abort.c:(.text.abort+0xa): undefined reference to `_exit'
f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\libc.a(lib_a-signalr.o): in function `_kill_r':
signalr.c:(.text._kill_r+0x12): undefined reference to `_kill'
f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\libc.a(lib_a-signalr.o): in function `_getpid_r':
signalr.c:(.text._getpid_r+0x0): undefined reference to `_getpid'
f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\libc.a(lib_a-fstatr.o): in function `_fstat_r':
fstatr.c:(.text._fstat_r+0x12): undefined reference to `_fstat'
f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: f:/programfiles/gcc/arm-none-eabi-windows/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\libc.a(lib_a-isattyr.o): in function `_isatty_r':
isattyr.c:(.text._isatty_r+0xc): undefined reference to `_isatty'
collect2.exe: error: ld returned 1 exit status

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:872]:
    [@programdir\core\sandbox\modules\os.lua:257]: in function 'runv'
    [@programdir\modules\core\project\depend.lua:189]: in function 'on_changed'
    [@programdir\actions\build\kinds\binary.lua:55]: in function '_do_link_target'
    [@programdir\actions\build\kinds\binary.lua:102]:
    [@programdir\actions\build\kinds\binary.lua:129]: in function '_link_target'
    [@programdir\actions\build\kinds\binary.lua:157]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:232]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:218]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:388]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:872: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\modules\private\async\runjobs.lua:256: in field 'catch'
        @programdir\core\sandbox\modules\try.lua:127: in global 'try'
        @programdir\modules\private\async\runjobs.lua:218: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:388: in function <@programdir\core\base\scheduler.lua:385>
`

**Comment by waruqi** [comment]
https://stackoverflow.com/questions/68101413/undefined-reference-to-write-which-is-implemented-in-a-library

可以试试 `--–whole-archive`

**Comment by ririyeye** [comment]
> https://stackoverflow.com/questions/68101413/undefined-reference-to-write-which-is-implemented-in-a-library
> 
> 可以试试 `--–whole-archive`

刚好遇到了这个问题  不加这些的话 里面的irqhandle会被编译器优化掉
那怎么给一个static target设置一个标志让他能自动添加这些前后缀呢
