### ISSUE TITLE
能不能添加对wxWidgets的支持？

### ISSUE THREAD

**Issue by wahello** [xmake-io/xmake#2443]
### Is your feature request related to a problem? Please describe.

在 `xmake create `添加生成 wxWidgets.

### Describe the solution you'd like

类似生成qt项目，
`xmake create -l c++ -t wx.share `
`xmake create -l c++ -t wx.static `
`xmake create -l c++ -t wx.widgetapp `

**Comment by waruqi** [comment]
最近没啥时间，后面看时间安排吧，你也可以直接来个 pr

**Comment by waruqi** [comment]
看下 https://github.com/xmake-examples/wxWidgets-scaffold

**Comment by heheda123123** [comment]
尝试示例失败了，https://github.com/xmake-examples/wxWidgets-scaffold/issues/1
另外这个可以内置到xmake不
