### ISSUE TITLE
aarch64平台安装pcl失败

### ISSUE THREAD

**Issue by xiaomi2077** [xmake-io/xmake#2453]
### Xmake 版本

2.6.7

### 操作系统版本和架构

Linux nx-desktop 4.9.140-tegra #1 SMP PREEMPT Fri Apr 16 01:50:20 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux

### 描述问题

安装pcl库时，有如下报错：
```bash
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> boost 1.78.0 [serialization:y, date_time:y, iostreams:y, filesystem:y, system:y, from pcl)
  -> pcl 1.12.1 [shared:y]
please input: y (y/n/m)
y
  => install boost 1.78.0 .. ok
  => install pcl 1.12.1 .. failed

CMake Error at /home/ubuntu/.xmake/packages/b/boost/1.78.0/124a5e8540714d31b251349b7d7f3fd2/lib/cmake/Boost-1.78.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:
    /home/ubuntu/.xmake/packages/b/boost/1.78.0/124a5e8540714d31b251349b7d7f3fd2/lib/cmake/boost_filesystem-1.78.0/boost_filesystem-config.cmake
  but it set boost_filesystem_FOUND to FALSE so package "boost_filesystem" is
  considered to be NOT FOUND.  Reason given by package:
  No suitable build variant has been found.
  The following variants have been tried and rejected:
  * libboost_filesystem-mt.a (32 bit, need 64)
Call Stack (most recent call first):
  /home/ubuntu/.xmake/packages/b/boost/1.78.0/124a5e8540714d31b251349b7d7f3fd2/lib/cmake/Boost-1.78.0/BoostConfig.cmake:262 (boost_find_component)
  /home/ubuntu/czs/softwares/cmake-3.21.5-linux-aarch64/share/cmake-3.21/Modules/FindBoost.cmake:594 (find_package)
  cmake/pcl_find_boost.cmake:29 (find_package)
  CMakeLists.txt:400 (include)
Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Checking for module 'eigen3'
--   Found eigen3, version 3.4.0
if you want to get more verbose errors, please see:
  -> /home/ubuntu/.xmake/cache/packages/2206/p/pcl/1.12.1/installdir.failed/logs/install.txt
error: install failed!
```
完整日志文件：
[install.txt](https://github.com/xmake-io/xmake/files/8889400/install.txt)

此错误应该是`libboost_filesystem-mt.a`被编译成了32位

### 期待的结果

期望`libboost_filessytem-mt.a`编译成64位，并正确安装pcl库

### 工程配置

```lua
set_languages('cxx17')
add_includedirs('include') --添加本项目头文件搜索目录
add_includedirs('/usr/local/cuda/include') -- 否则会找到不到driver_types.h

add_requires("opencv","yaml-cpp",'fmt',"cxxopts","eigen",{system=false}) -- 不使用系统包

add_requires('pcl',{system=false,config={shared=true}}) -- pcl的包会添加boost部分模块的依赖


target('oilfield_common')
    set_kind('shared')
    add_files('common/*.cpp')
    add_packages("opencv",'yaml-cpp','cxxopts','boost')
```

### 附加信息和错误日志

执行`xmake -vD`
输出太长了，保存到下面的文件里了
[aa.txt](https://github.com/xmake-io/xmake/files/8889456/aa.txt)

**Comment by xiaomi2077** [comment]
![图片](https://user-images.githubusercontent.com/33375652/173316552-a6d8794e-3dfe-4b7e-be34-eca19cc80a32.png)
上图第一个是我通过`xmake require --extra="{config={shared=true},system=false}" boost`安装的boost是动态库，且是64位。如下图
![图片](https://user-images.githubusercontent.com/33375652/173317146-2fd9a78e-7822-4c92-92c8-b4d4472ad0a1.png)

第二个是安装pcl时，xmake它自己又安装一次boost，编译出来的库是静态库。使用`objdump -a libboost_filesystem-mt.a`的输出
![图片](https://user-images.githubusercontent.com/33375652/173317985-ce06f142-9cc1-44b1-ac69-a38e364f39d1.png)

**Comment by xiaomi2077** [comment]
很奇怪啊，我把124文件夹里的静态库复制到5bc文件夹下，并将5bc目录名改为124。改名后的124(原5bc目录)如下图：
![图片](https://user-images.githubusercontent.com/33375652/173319224-0ea93a83-7328-4caf-b950-2b868cdf0804.png)
然后执行`xmake`编译项目，输出如下：
```bash
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> pcl 1.12.1 [shared:y]
please input: y (y/n/m)
y
  => install pcl 1.12.1 .. failed

CMake Error at /home/ubuntu/.xmake/packages/b/boost/1.78.0/124a5e8540714d31b251349b7d7f3fd2/lib/cmake/Boost-1.78.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:
    /home/ubuntu/.xmake/packages/b/boost/1.78.0/124a5e8540714d31b251349b7d7f3fd2/lib/cmake/boost_filesystem-1.78.0/boost_filesystem-config.cmake
  but it set boost_filesystem_FOUND to FALSE so package "boost_filesystem" is
  considered to be NOT FOUND.  Reason given by package:
  No suitable build variant has been found.
  The following variants have been tried and rejected:
  * libboost_filesystem-mt.so.1.78.0 (32 bit, need 64)
Call Stack (most recent call first):
  /home/ubuntu/.xmake/packages/b/boost/1.78.0/124a5e8540714d31b251349b7d7f3fd2/lib/cmake/Boost-1.78.0/BoostConfig.cmake:262 (boost_find_component)
  /home/ubuntu/czs/softwares/cmake-3.21.5-linux-aarch64/share/cmake-3.21/Modules/FindBoost.cmake:594 (find_package)
  cmake/pcl_find_boost.cmake:29 (find_package)
  CMakeLists.txt:400 (include)
ng Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Checking for module 'eigen3'
--   Found eigen3, version 3.4.0
if you want to get more verbose errors, please see:
  -> /home/ubuntu/.xmake/cache/packages/2206/p/pcl/1.12.1/installdir.failed/logs/install.txt
error: install failed!
```
这次找到了`libboost_filesystem-mt.so.1.78.0`动态库，但仍报错`The following variants have been tried and rejected: *libboost_filesystem-mt.so.1.78.0 (32 bit, need 64)`
这是把这个库识别成了32位，可是`libboost_filesystem-mt.so.1.78.0`通过`file`命令查看是64位啊：）

**Comment by waruqi** [comment]
那说明安装的库没问题咯，就是 64 的，是 cmake find 时候，内部调用了啥检测，检测成了 32bit? 那应该是 cmake 的问题吧。。要不你看下 cmake 相关 find package 怎么找的它

**Comment by xiaomi2077** [comment]
@waruqi 找了一个小时。。。，大佬能再提示提示吗？我对cmake不太熟悉。

**Comment by waruqi** [comment]
可以 google 下相关错误，应该有不少类似的参考：

https://stackoverflow.com/questions/61145830/cmake-error-while-using-find-packageboost-in-cmakelists-txt-no-suitable

**Comment by xiaomi2077** [comment]
不知道为什么boost默认编译成32位的库了，解决方法是手动编译下在的boost源码，并安装。`--address-model=64`指定编译成64位。命令如下：
`./bootstrap.sh`
`./b2 install --prefix=/home/ubuntu/.xmake/packages/b/boost/1.78.0/124a5e8540714d31b251349b7d7f3fd2  --with-filesystem --with-date_time --with-iostreams --with-system  --address-model=64 --link=static
`
然后再使用xmake安装pcl就可以了。
但是安装的pcl不全，少了好多库，如下图，左边是xmake安装的，右边是自己安装的
![图片](https://user-images.githubusercontent.com/33375652/173511605-4a5cb379-9396-46f2-af66-eb0b3075f43d.png)

我看仓库里好像只能安装vtk和cuda，不知道在哪里设置才能安装pcl的全部模块。。。

**Comment by waruqi** [comment]
包里有配置 --address-model=64 的，

https://github.com/xmake-io/xmake-repo/blob/a140c62bb87ff301f919b5dcc94f9f6a5c4455d1/packages/b/boost/xmake.lua#L147

而且我看你最早d的截图，里面编译出来也是 64 的。没啥问题 
<img width="864" alt="image" src="https://user-images.githubusercontent.com/151335/173513435-482a2755-8b3a-48ab-8a7e-cb8f6e1082ba.png">

**Comment by xiaomi2077** [comment]
但是它报错是` libboost_filesystem-mt.a (32 bit, need 64)`，意思是这个静态库是32位，需要64位的库。而且我也没改pcl和boost的cmake
我这个是aarch64平台，符合 if package:is_arch("x64", "x86_64") then的判断吗？（我不太懂这些架构归类关系

**Comment by waruqi** [comment]
提个 pr 过来到 dev branch， https://github.com/xmake-io/xmake-repo/blob/a140c62bb87ff301f919b5dcc94f9f6a5c4455d1/packages/b/boost/xmake.lua#L146

这里加个 arm64 的 arch

**Comment by xq114** [comment]
改成`package:is_arch(".+64")`这样更好吧？目前xmake支持的arch里面64位的都是以64结尾的

**Comment by waruqi** [comment]
> 改成`package:is_arch(".+64")`这样更好吧？目前xmake支持的arch里面64位的都是以64结尾的

也可以

**Comment by waruqi** [comment]
boost 包里面，我加上 arm64 了，更新下仓库再试下，xrepo update-repo

**Comment by waruqi** [comment]
你执行 `xmake l os.arch` 给我看下

**Comment by xiaomi2077** [comment]
![图片](https://user-images.githubusercontent.com/33375652/173569440-4b557784-3a82-4c00-b34b-bb9eded614e1.png)

**Comment by waruqi** [comment]
在更新下试试

**Comment by xiaomi2077** [comment]
好了，谢谢。但是为什么只生成这些库？不能全部的模块都生成吗？
![图片](https://user-images.githubusercontent.com/33375652/173573629-b1a9a241-90ab-45d1-9371-af5ba82a8a2b.png)

**Comment by waruqi** [comment]
如果它还可以生成其他库，可以自己提 pr 改进下这个包。。https://github.com/xmake-io/xmake-repo/blob/master/packages/p/pcl/xmake.lua

目前 xmake-repo 仓库的包，都是用户根据自己需求，自己维护的。

**Comment by xiaomi2077** [comment]
> 好了，谢谢。但是为什么只生成这些库？不能全部的模块都生成吗？ ![图片](https://user-images.githubusercontent.com/33375652/173573629-b1a9a241-90ab-45d1-9371-af5ba82a8a2b.png)

原因：我知道为什么只生成这几个库了。pcl好多库都直接或间接依赖于flann。
https://github.com/xmake-io/xmake-repo/blob/6d323eab58f59d2c1142c1bd8bc20b7f9888a39f/packages/p/pcl/xmake.lua#L31 仓库里这一行把原来cmake的`find_package(FLANN 1.9.1 REQUIRED)`改为了`find_package(flann CONFIG REQUIRED)`。可能是CONFIG里没有配置好，不太懂cmake。
解决办法：把仓库里替换FLANN的哪一行注释掉就好了。不过要用xmake提前安装好flann1.9.1

**Comment by waruqi** [comment]
@xq114 这个帮忙看下？

**Comment by xq114** [comment]
> 不过要用xmake提前安装好flann1.9.1

你确定是用xmake安装的flann吗？xmake安装的flann pcl应该找不到才对，这里有cmake的详细log吗

**Comment by xiaomi2077** [comment]
不清楚了。我查了一下，xmake装了flann1.9.1,系统库里也找到了libflann 1.9.1。
> 这里有cmake的详细log吗

cmake日志在哪找？.xmake/cache 和.xmake/packages里都没有

**Comment by xq114** [comment]
那应该是用的系统库的flann。可以提供一下.xmake/packages/f/flann/.../1.9.1/cmake/flannConfig.cmake和.xmake/packages/f/flann/.../1.9.1/cmake/flannTargets-release.cmake的内容吗

**Comment by xiaomi2077** [comment]
flannConfig.cmake
```
####### Expanded from @PACKAGE_INIT@ by configure_package_config_file() #######
####### Any changes to this file will be overwritten by the next CMake run ####
####### The input file was Config.cmake.in                            ########

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

macro(set_and_check _var _file)
  set(${_var} "${_file}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "File or directory ${_file} referenced by variable ${_var} does not exist !")
  endif()
endmacro()

macro(check_required_components _NAME)
  foreach(comp ${${_NAME}_FIND_COMPONENTS})
    if(NOT ${_NAME}_${comp}_FOUND)
      if(${_NAME}_FIND_REQUIRED_${comp})
        set(${_NAME}_FOUND FALSE)
      endif()
    endif()
  endforeach()
endmacro()

include("${CMAKE_CURRENT_LIST_DIR}/flannTargets.cmake")
check_required_components("flann")
```
flannTargets-release.cmake
```
#----------------------------------------------------------------
# Generated CMake target import file for configuration "Release".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "flann::flann" for configuration "Release"
set_property(TARGET flann::flann APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(flann::flann PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "ASM_NASM;C"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libflann_s.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS flann::flann )
list(APPEND _IMPORT_CHECK_FILES_FOR_flann::flann "${_IMPORT_PREFIX}/lib/libflann_s.a" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
```

**Comment by xq114** [comment]
改了，现在应该可以了
