### ISSUE TITLE
emscripten options should be in the compile and link command

### ISSUE THREAD

**Issue by jonathanpoelen** [xmake-io/xmake#2455]
### Xmake Version

v2.6.7+HEAD.93b7245

### Operating System Version and Architecture

Linux

### Describe Bug

For compiler options to be handled properly by emcc/em++, same options must be used at compile and link.

Here, an explanation about the optimization options: https://emscripten.org/docs/compiling/Building-Projects.html?highlight=optimization#building-projects-optimizations

```console
$ xmake
emcc -c -O2 -o build/.objs/test/wasm/wasm32/release/test.cpp.o test.cpp
em++ -o build/wasm/wasm32/release/test.html build/.objs/test/wasm/wasm32/release/test.cpp.o
```

`-O2` is missing on `em++ ...`

### Expected Behavior

```console
$ xmake
emcc -c -O2 -o build/.objs/test/wasm/wasm32/release/test.cpp.o test.cpp
em++ -O2 -o build/wasm/wasm32/release/test.html build/.objs/test/wasm/wasm32/release/test.cpp.o
```

`-O2` on both lines.

### Project Configuration

`test.cpp`
```cpp
#include <cstdio>
int main() { puts("Hello"); }
```

`xmake.lua`
```lua
set_optimize("faster") -- enable -O2

target("test")
    set_kind("binary")
    add_files("test.cpp")
```

**Comment by waruqi** [comment]
try `xmake update -s github:xmake-io/xmake#opti` 

https://github.com/xmake-io/xmake/pull/2461

**Comment by waruqi** [comment]
I have improved it.
