### ISSUE TITLE
`set_optimize"aggressive"` does not enable any optimization with emscripten

### ISSUE THREAD

**Issue by jonathanpoelen** [xmake-io/xmake#2456]
### Xmake Version

v2.6.7+HEAD.93b7245

### Operating System Version and Architecture

Linux

### Describe Bug

`set_optimize"aggressive"` tries `-Ofast` option with emscripten. However, this one does not exist and no optimization is activated.

### Expected Behavior

Enable an optimization such as `-O3`.

### Project Configuration

```lua
set_optimize("aggressive")

target("test")
    set_kind("binary")
    add_files("test.cpp")
```

**Comment by waruqi** [comment]
I have improved it.
