### ISSUE TITLE
xmake重新安装opencv没输出

### ISSUE THREAD

**Issue by xiaomi2077** [xmake-io/xmake#2464]
### Xmake 版本

xmake v2.6.7+HEAD.93b7245

### 操作系统版本和架构

Linux nx-desktop 4.9.140-tegra #1 SMP PREEMPT Fri Apr 16 01:50:20 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux

### 描述问题

通过`xmake require  --extra="{configs={gtk=true}}" opencv`命令安装带gtk的opencv。但是命令没有任何输出，如下图。
![image](https://user-images.githubusercontent.com/33375652/173806980-e0ab537a-0240-4406-b443-54f7e8225f13.png)
查看`~/.xmake/packages/o/opencv/4.5.5/`发现新增有4709...文件夹，但里面是空的。下图中其他三个文件夹是之前编译好的opencv，带gtk和不带gtk。
![image](https://user-images.githubusercontent.com/33375652/173807109-2aba9899-a231-4f97-84af-e5a4317d6acc.png)
执行`xmake f -c`，安装命令还是没输出。
![image](https://user-images.githubusercontent.com/33375652/173808062-f86ce7a3-c011-44fd-b3fd-7a02e630c849.png)

是不是哪里缓存没有清掉？

### 期待的结果

顺利安装带有gtk的opencv

**Comment by xiaomi2077** [comment]
执行`xmake l os.arch`输出：
![image](https://user-images.githubusercontent.com/33375652/173808864-76319d81-12ae-49d7-aae4-98746271abbe.png)

**Comment by waruqi** [comment]
不要去用 xmake requires 。。全走 add_requires/add_packages 在 xmake.lua 里面统一配置，直接编译

**Comment by xiaomi2077** [comment]
![image](https://user-images.githubusercontent.com/33375652/173812619-55c8cf62-0114-46dc-9ad8-280fc9b9159d.png)
执行`xrepo install -f "gtk=true" opencv`没输出，但是执行`xrepo install -f "gtk=true" opencv`有可以正常安装。出现这种问题是不是包的lua脚本写错了？

![image](https://user-images.githubusercontent.com/33375652/173813147-1dacb706-e7a2-45ca-b3e3-287a40bc9025.png)
并且我执行命令`xrepo info opencv`看opencv的编译选项，也有gtk

看输出好像xrepo也是走的xmake require，这两个命令有啥区别吗？

**Comment by waruqi** [comment]
xmake require 目前用于工程内管理有缓存，也会读当前工程 xmake.lua ，通常用户不需要用，走 xmake 编译，内部自动会调用


xrepo 是独立命令，不跟当前工程相关，独立管理包

**Comment by waruqi** [comment]
你先走 add_requires + add_packages 试下，看是否有问题

**Comment by xiaomi2077** [comment]
我的问题基本解决，下面说下的情况

我的`os.arch=arm64-v8`
我的需求：使用opencv显示图片
如何做：使用xmake安装opencv，并指定`gtk=true`
安装时需要注意的是：
1、opencv依赖gtk，仓库中虽然有gtk的包，但是arm64-v6的不支持。要保证电脑上有gtk+-3.0，可以使用`pkg-config gtk+-3.0 --libs --cflags`查看。没有安装就apt安一下。如果安装了，输出如下：
![image](https://user-images.githubusercontent.com/33375652/174230892-a23bb410-7efa-41f8-8668-67040fedaefd.png)
2、xmake.lua中记得加上`libpng`包，引用时写在`opencv`后面，即：`add_packages("opencv","libpng")`

完整的xmake.lua如下：
![image](https://user-images.githubusercontent.com/33375652/174228587-af8efd94-ec6b-45ac-9e8d-51d292490fba.png)

**Comment by xiaomi2077** [comment]
现在问题基本解决了，但是intellisense在第2行画红线，好像找不到这个库，能编译成功。（已在`c_cpp_propertiess.jon`中指定`compileCommand`为`./vscode/compile_commands.json`）
![image](https://user-images.githubusercontent.com/33375652/174208543-6eaab797-fc37-42b9-bd21-e275df3aac20.png)
![image](https://user-images.githubusercontent.com/33375652/174232195-ac0cac3e-627b-4b3c-8f87-06c8d5c99e3f.png)

如何才能去掉这个红线呢？

**Comment by waruqi** [comment]
参考下 https://github.com/xmake-io/xmake-vscode/issues/40 然后确认 compile_commands.json 是否生成。。如果插件激活，每次 xmake.lua 配置改动，都会自动生成。。

如果生成了，就看下，里面有没有带上 opencv 相关includedir 。。确认路径是否 ok

这里我先 close 了，intelligense 问题可以到 xmake-vscode/issues 下反馈
