### ISSUE TITLE
vcpkg manifest 模式下支持自定义 vcpkg-configuration.json

### ISSUE THREAD

**Issue by BenzzzX** [xmake-io/xmake#2469]
### Is your feature request related to a problem? Please describe.

vcpkg [支持外部 registry](https://vcpkg.io/en/docs/users/registries.html)，registry 的配置存放在与 vcpkg.json 同一目录下的 vcpkg-configuration.json 中，目前 xmake 可以生成 vcpkg.json，但没办法自定义 vcpkg-configuration.json。

### Describe the solution you'd like

提供自定义 vcpkg-configuration.json 的方式。比如直接拷贝根目录下的 vcpkg-configuration.json 到编译目录。

**Comment by waruqi** [comment]
能搞个简单的 demo 么。。我这方便测试

**Comment by BenzzzX** [comment]
[tmp.zip](https://github.com/xmake-io/xmake/files/8939410/tmp.zip)
使用 `vcpkg install` 可以找到对应的 package。我改了一下 xmake 增加了
```lua
local configuration = path.join(os.projectdir(), "vcpkg-configuration.json")
if os.exists(configuration) then
    vprint(configuration)
    os.cp(configuration, installdir)
end
```
也可以找到 package

**Comment by waruqi** [comment]
```lua
local registries = {
        {
            kind = "git",
            repository = "https://github.com/SakuraEngine/vcpkg-registry",
            baseline = "e0e1e83ec66e3c9b36066f79d133b01eb68049f7",
            packages = {
                "skrgamenetworkingsockets"
            }
        }
}
add_requires("vcpkg::skrgamenetworkingsockets >=1.4.0+1", {configs = {registries = registries}})
```

试下，dev。。

增加了 registries 和 default_registries 配置，可以把 vcpkg-configuartion.json 里面的原样搬过去，不过要转成 lua table

**Comment by BenzzzX** [comment]
牛逼，成了，不过 modules\package\manager\vcpkg\configurations.lua 少写了一个逗号

**Comment by waruqi** [comment]
再试下

**Comment by waruqi** [comment]
应该可以了对吧，我先关了
