### ISSUE TITLE
qt 生成带ui的界面共享库

### ISSUE THREAD

**Issue by mingtiancai** [xmake-io/xmake#2472]
### Xmake Version

2.6.7

### Operating System Version and Architecture

ubuntu 20.04

### Describe Bug

默认生成的shard库是不带ui的，加上ui编译，编译不过去，总是提示各种错误
[demo.zip](https://github.com/xmake-io/xmake/files/8933170/demo.zip)

### Expected Behavior

编译带ui的库跟正常一样

**Comment by waruqi** [comment]
有错误 就贴错误

**Comment by mingtiancai** [comment]
> 有错误 就贴错误
![Screenshot 2022-06-09 11:00:21](https://user-images.githubusercontent.com/13520801/174430020-c1625f5d-4fc5-45b5-a7d8-1b0f9f0cf70f.png)

**Comment by mingtiancai** [comment]
> 有错误 就贴错误
![Screenshot 2022-06-18 16:40:40](https://user-images.githubusercontent.com/13520801/174430035-4806a8c8-a844-402c-9751-ef02c2cc6a80.png)
各种错误，怎么调都对不上，能否给出一个qt带界面的共享库使用说明，或者代码示例

**Comment by waruqi** [comment]
哪来的附件
