### ISSUE TITLE
编译cortex-m4报cross toolchain not found错误！

### ISSUE THREAD

**Issue by robomentor** [xmake-io/xmake#2477]
### Xmake Version

2.6.7

### Operating System Version and Architecture

Windows10

### Describe Bug

之前在自己电脑测试没问题，可以顺利完成STM32的编译并生成可用的bin文件，今天用同事的电脑进行编译测试时发生错误。

执行脚本：xmake f -p cross -a cortex-m4 --toolchain=armcc -c 后直接报错：cross toolchain not found

问题的电脑进行的一些配置操作：
1、xmake.exe的根目录已经设置到系统环境变量
2、arm-none-eabi的bin目录已经设置到系统环境变量

难道还需要其他的东西？

### Expected Behavior

期望是通过xmake+arm-none-eabi即可正常完成编译。

### Project Configuration

`lua
add_rules("mode.debug", "mode.release")

toolchain("arm-none-eabi")
    set_kind("standalone")
    set_sdkdir("arm-none-eabi的根目录")
    set_toolset("cc", "arm-none-eabi-gcc")
    set_toolset("ld", "arm-none-eabi-gcc")
    set_toolset("ar", "arm-none-eabi-ar")
    set_toolset("as", "arm-none-eabi-gcc")
toolchain_end()

-- 编译配置
target("firmware")

    set_kind("binary")

    set_toolchains("arm-none-eabi")

    -- 设置要编译的.c源文件
    add_files(
        "./System/startup_gcc.s",
        "./FreeRTOS/*.c",
        "./FreeRTOS/portable/GCC/ARM_CM4F/port.c",
        "./FreeRTOS/portable/MemMang/heap_4.c",
        "./System/core/src/*.c",
        "./System/driver/src/*.c",
        "./System/usb/USB_Driver/src/usb_bsp.c",
        "./System/usb/USB_Driver/src/usb_core.c",
        "./System/usb/USB_Driver/src/usb_dcd.c",
        "./System/usb/USB_Driver/src/usb_dcd_int.c",
        "./System/usb/USB_Library/Core/src/usbd_cdc_vcp.c",
        "./System/usb/USB_Library/Core/src/usbd_core.c",
        "./System/usb/USB_Library/Core/src/usbd_desc.c",
        "./System/usb/USB_Library/Core/src/usbd_ioreq.c",
        "./System/usb/USB_Library/Core/src/usbd_req.c",
        "./System/usb/USB_Library/Core/src/usbd_usr.c",
        "./System/usb/USB_Library/Class/cdc/src/usbd_cdc_core.c",
        "./Source/app/src/*.c",
        "./Source/main/src/*.c",
        "./Source/modular/src/*.c",
        "./Source/robot/base/src/*.c",
        "./Source/utils/src/*.c"
    )

    -- 设置要排除的.c源文件
    remove_files(
        "./System/driver/src/stm32f4xx_fsmc.c"
    )

    -- 设置要编译的.h头文件目录
    add_includedirs(
        "./Source/app/inc",
        "./Source/main/inc",
        "./Source/modular/inc",
        "./Source/robot/base/inc",
        "./Source/utils/inc",
        "./FreeRTOS/include",
        "./FreeRTOS/portable/GCC/ARM_CM4F",
        "./System/core/inc",
        "./System/driver/inc",
        "./System/usb/USB_Driver/inc",
        "./System/usb/USB_Library/Class/cdc/inc",
        "./System/usb/USB_Library/Core/inc"
    )

    -- 设置宏定义
    add_defines(
        "USE_STDPERIPH_DRIVER",
        "STM32F427_437xx",
        "USE_STM324x9I_EVAL",
        "USE_USB_OTG_FS",
        "USE_ULPI_PHY"
    )

    add_cxflags(
        "-mcpu=cortex-m4",
        "-mthumb",
        "-mfloat-abi=hard -mfpu=fpv4-sp-d16",
        "-Wall -fdata-sections -ffunction-sections",
        "-O3 -g -gdwarf-2",{force = true}
    )
    add_asflags(
        "-mcpu=cortex-m4",
        "-mthumb",
        "-mfloat-abi=hard -mfpu=fpv4-sp-d16",
        "-Wall -fdata-sections -ffunction-sections",
        "-O3 -g -gdwarf-2",{force = true}
    )
    add_ldflags(
        "-O3",
        "-mcpu=cortex-m4",
        "-mfloat-abi=hard -mfpu=fpv4-sp-d16",
        "-specs=nano.specs",
        "-L./",
        "-TSystem/flash.ld",
        "-Wl,--gc-sections -std=gnu11 -D_MICROLIB",
        "-lc -lm -lnosys -u _printf_float",{force = true}
    )

    -- 设置编译目录，必须为Build
    set_targetdir("Build")

    -- 设置生成的文件名，必须为firmware.elf
    set_filename("firmware.elf")

    -- 生成HEX、BIN文件
    after_build(function(target)
        os.exec("arm-none-eabi-objcopy -O ihex ./Build/firmware.elf ./Build/firmware.hex")
        os.exec("arm-none-eabi-objcopy -O binary ./Build/firmware.elf ./Build/firmware.bin")
        print("---------- Complete Build ---------")
    end)
`

### Additional Information and Error Logs

error：cross toolchain not found！

**Comment by robomentor** [comment]
看了官方的文档好像是这么用的，正确的执行脚本是什么？另外我看了下我的电脑和同事的电脑区别在于我的电脑安装了Microsoft Visual Studio，且执行脚本时的头部内容为：

`
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2019
[  1%]: ccache compiling.release FreeRTOS\croutine.c
[  1%]: ccache compiling.release System\driver\src\stm32f4xx_flash_ramfunc.c
[  1%]: ccache compiling.release System\driver\src\stm32f4xx_dsi.c
[  1%]: ccache compiling.release System\driver\src\stm32f4xx_dfsdm.c
[  1%]: ccache compiling.release System\driver\src\misc.c
........
`

**Comment by waruqi** [comment]
> set_toolchains("arm-none-eabi")

我看你不是用了自己定义的工具链么，那为啥还要指定 --toolchain=armcc ，这个是 keil 的工具链，同时使用两个不同的工具链，不就冲突了么。。而且你这有装 keil/armcc ?

既然用了自定义的 toolchain，那 xmake f  配置就不要再去切其他工具链。

另外，交叉编译工具链，通常不用自定义，直接走 xmake f -p cross --sdk=/xxx 就能自动探测到并使用。

**Comment by robomentor** [comment]
谢谢大神，我这边弄好了，改了一下配置，直接：xmake 就可以运行了，贴出配置，以便其他人参考：

```
add_rules("mode.debug", "mode.release")

set_plat("cross")

set_arch("cortex-m4")

function use_toolchain(sdk_path)
	toolchain("arm-gcc")
		set_kind("cross")
		set_sdkdir(sdk_path)
		set_toolset("cc", "arm-none-eabi-gcc")
		set_toolset("ld", "arm-none-eabi-gcc")
		set_toolset("ar", "arm-none-eabi-ar")
		set_toolset("as", "arm-none-eabi-gcc")
	toolchain_end()
	set_toolchains("arm-gcc")
end

local arm_gcc_installing_path = os.getenv("ARM_GCC_TOOL")
use_toolchain(arm_gcc_installing_path)

-- 编译配置
target("firmware")

    set_kind("binary")

    -- 设置要编译的.c源文件
    add_files(
        "./System/startup_gcc.s",
        "./FreeRTOS/*.c",
        "./FreeRTOS/portable/GCC/ARM_CM4F/port.c",
        "./FreeRTOS/portable/MemMang/heap_4.c",
        "./System/core/src/*.c",
        "./System/driver/src/*.c",
        "./System/usb/USB_Driver/src/usb_bsp.c",
        "./System/usb/USB_Driver/src/usb_core.c",
        "./System/usb/USB_Driver/src/usb_dcd.c",
        "./System/usb/USB_Driver/src/usb_dcd_int.c",
        "./System/usb/USB_Library/Core/src/usbd_cdc_vcp.c",
        "./System/usb/USB_Library/Core/src/usbd_core.c",
        "./System/usb/USB_Library/Core/src/usbd_desc.c",
        "./System/usb/USB_Library/Core/src/usbd_ioreq.c",
        "./System/usb/USB_Library/Core/src/usbd_req.c",
        "./System/usb/USB_Library/Core/src/usbd_usr.c",
        "./System/usb/USB_Library/Class/cdc/src/usbd_cdc_core.c",
        "./Source/app/src/*.c",
        "./Source/main/src/*.c",
        "./Source/modular/src/*.c",
        "./Source/robot/base/src/*.c",
        "./Source/utils/src/*.c"
    )

    -- 设置要排除的.c源文件
    remove_files(
        "./System/driver/src/stm32f4xx_fsmc.c"
    )

    -- 设置要编译的.h头文件目录
    add_includedirs(
        "./Source/app/inc",
        "./Source/main/inc",
        "./Source/modular/inc",
        "./Source/robot/base/inc",
        "./Source/utils/inc",
        "./FreeRTOS/include",
        "./FreeRTOS/portable/GCC/ARM_CM4F",
        "./System/core/inc",
        "./System/driver/inc",
        "./System/usb/USB_Driver/inc",
        "./System/usb/USB_Library/Class/cdc/inc",
        "./System/usb/USB_Library/Core/inc"
    )

    -- 设置宏定义
    add_defines(
        "USE_STDPERIPH_DRIVER",
        "STM32F427_437xx",
        "USE_STM324x9I_EVAL",
        "USE_USB_OTG_FS",
        "USE_ULPI_PHY"
    )

    add_cxflags(
        "-mcpu=cortex-m4",
        "-mthumb",
        "-mfloat-abi=hard -mfpu=fpv4-sp-d16",
        "-Wall -fdata-sections -ffunction-sections",
        "-O3 -g -gdwarf-2",{force = true}
    )
    add_asflags(
        "-mcpu=cortex-m4",
        "-mthumb",
        "-mfloat-abi=hard -mfpu=fpv4-sp-d16",
        "-Wall -fdata-sections -ffunction-sections",
        "-O3 -g -gdwarf-2",{force = true}
    )
    add_ldflags(
        "-O3",
        "-mcpu=cortex-m4",
        "-mfloat-abi=hard -mfpu=fpv4-sp-d16",
        "-specs=nano.specs",
        "-L./",
        "-TSystem/flash.ld",
        "-Wl,--gc-sections -std=gnu11 -D_MICROLIB",
        "-lc -lm -lnosys -u _printf_float",{force = true}
    )

    -- 设置编译目录，必须为Build
    set_targetdir("Build")

    -- 设置生成的文件名，必须为firmware.elf
    set_filename("firmware.elf")

    -- 生成HEX、BIN文件
    after_build(function(target)
        os.exec("arm-none-eabi-objcopy -O ihex ./Build/firmware.elf ./Build/firmware.hex")
        os.exec("arm-none-eabi-objcopy -O binary ./Build/firmware.elf ./Build/firmware.bin")
        print("---------- Complete Build ---------")
    end)
```

改天再测试下MacOS，有问题再请教你。
