### ISSUE TITLE
Pacman包的 include 路径错误

### ISSUE THREAD

**Issue by sunxfancy** [xmake-io/xmake#2482]
### Xmake 版本

xmake v2.6.8+202206221218

### 操作系统版本和架构

5.13.10-1-MANJARO

### 描述问题

在引用Pacman的包LLVM时，include path中会引入大量不必要且可能引发文件名冲突的子目录，如：
-isystem /usr/include/llvm/DebugInfo/GSYM
-isystem /usr/include/llvm/Transforms/Coroutines
...

我不确定其他pacman的包是否有类似问题，但看起来更像是pacman包引入机制的问题。

### 期待的结果

正常情况下，应该仅仅引入 /usr/include/ 即可，用户会在include时指定 "llvm/DebugInfo/GSYM/..."

### 工程配置

add_rules("mode.debug", "mode.release")
set_languages("c17", "c++20")
add_requires("pacman::llvm")

target("Pass")
    set_kind("shared")
    add_files("compiler/*.cpp", "compiler/*.ixx")
    add_packages("pacman::llvm")

### 附加信息和错误日志

xmake b -r -vD                                                                                                                                     

checking for gcc ... /usr/bin/gcc
checkinfo: cannot runv(dmd --version), No such file or directory
checking for dmd ... no
checkinfo: cannot runv(ldc2 --version), No such file or directory
checking for ldc2 ... no
checkinfo: cannot runv(gdc --version), No such file or directory
checking for gdc ... no
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
finding llvm from pacman ..
checking for pacman ... /usr/bin/pacman
checking for pacman::llvm ... llvm 13.0.1
checking for gcc ... /usr/bin/gcc
checking for the c++ compiler (cxx) ... gcc
checking for /usr/bin/gcc ... ok
checking for flags (-fPIC) ... ok
> gcc "-fPIC"
checking for flags (-fmodules-ts) ... ok
> gcc "-fmodules-ts"
generating.moduledeps runtime/map.ixx
checking for flags (-O3) ... ok
> gcc "-O3"
checking for flags (-std=c++20) ... ok
> gcc "-std=c++20"
checking for flags (-fmodules-ts) ... ok
> gcc "-fmodules-ts"
checking for flags (-DNDEBUG) ... ok
> gcc "-DNDEBUG"
[ 22%]: ccache compiling.release compiler/pass.cpp
/usr/bin/gcc -c -m64 -fPIC -O3 -std=c++20 -isystem /usr/include/llvm-c -isystem /usr/include/llvm-c/Transforms -isystem /usr/include/llvm/ADT -isystem /usr/include/llvm/Analysis -isystem /usr/include/llvm/Analysis/Utils -isystem /usr/include/llvm/AsmParser -isystem /usr/include/llvm/BinaryFormat -isystem /usr/include/llvm/Bitcode -isystem /usr/include/llvm/Bitstream -isystem /usr/include/llvm/CodeGen -isystem /usr/include/llvm/CodeGen/GlobalISel -isystem /usr/include/llvm/CodeGen/MIRParser -isystem /usr/include/llvm/CodeGen/PBQP -isystem /usr/include/llvm/Config -isystem /usr/include/llvm/DWARFLinker -isystem /usr/include/llvm/DWP -isystem /usr/include/llvm/DebugInfo/CodeView -isystem /usr/include/llvm/DebugInfo -isystem /usr/include/llvm/DebugInfo/DWARF -isystem /usr/include/llvm/DebugInfo/GSYM -isystem /usr/include/llvm/DebugInfo/MSF -isystem /usr/include/llvm/DebugInfo/PDB -isystem /usr/include/llvm/DebugInfo/PDB/DIA -isystem /usr/include/llvm/DebugInfo/PDB/Native -isystem /usr/include/llvm/DebugInfo/Symbolize -isystem /usr/include/llvm/Demangle -isystem /usr/include/llvm/ExecutionEngine -isystem /usr/include/llvm/ExecutionEngine/JITLink -isystem /usr/include/llvm/ExecutionEngine/Orc -isystem /usr/include/llvm/ExecutionEngine/Orc/Shared -isystem /usr/include/llvm/ExecutionEngine/Orc/TargetProcess -isystem /usr/include/llvm/FileCheck -isystem /usr/include/llvm/Frontend/OpenMP -isystem /usr/include/llvm/FuzzMutate -isystem /usr/include/llvm/IR -isystem /usr/include/llvm/IRReader -isystem /usr/include/llvm -isystem /usr/include/llvm/InterfaceStub -isystem /usr/include/llvm/LTO -isystem /usr/include/llvm/LTO/legacy -isystem /usr/include/llvm/LineEditor -isystem /usr/include/llvm/Linker -isystem /usr/include/llvm/MC -isystem /usr/include/llvm/MC/MCDisassembler -isystem /usr/include/llvm/MC/MCParser -isystem /usr/include/llvm/MCA -isystem /usr/include/llvm/MCA/HardwareUnits -isystem /usr/include/llvm/MCA/Stages -isystem /usr/include/llvm/Object -isystem /usr/include/llvm/ObjectYAML -isystem /usr/include/llvm/Option -isystem /usr/include/llvm/Passes -isystem /usr/include/llvm/ProfileData/Coverage -isystem /usr/include/llvm/ProfileData -isystem /usr/include/llvm/Remarks -isystem /usr/include/llvm/Support -isystem /usr/include/llvm/Support/FileSystem -isystem /usr/include/llvm/Support/Solaris/sys -isystem /usr/include/llvm/Support/Windows -isystem /usr/include/llvm/TableGen -isystem /usr/include/llvm/Target -isystem /usr/include/llvm/Testing/Support -isystem /usr/include/llvm/TextAPI -isystem /usr/include/llvm/ToolDrivers/llvm-dlltool -isystem /usr/include/llvm/ToolDrivers/llvm-lib -isystem /usr/include/llvm/Transforms/AggressiveInstCombine -isystem /usr/include/llvm/Transforms -isystem /usr/include/llvm/Transforms/Coroutines -isystem /usr/include/llvm/Transforms/IPO -isystem /usr/include/llvm/Transforms/InstCombine -isystem /usr/include/llvm/Transforms/Instrumentation -isystem /usr/include/llvm/Transforms/Scalar -isystem /usr/include/llvm/Transforms/Utils -isystem /usr/include/llvm/Transforms/Vectorize -isystem /usr/include/llvm/WindowsManifest -isystem /usr/include/llvm/WindowsResource -isystem /usr/include/llvm/XRay -DNDEBUG -o build/.objs/FCSymPass/linux/x86_64/release/compiler/pass.cpp.o compiler/pass.cpp
[ 22%]: ccache compiling.release runtime/map.ixx
/usr/bin/gcc -c -m64 -fPIC -O3 -std=c++20 -fmodules-ts -DNDEBUG -x c++ -o build/.objs/FCSym/linux/x86_64/release/runtime/map.ixx.o runtime/map.ixx
checking for flags (-MMD -MF) ... ok
> gcc "-MMD" "-MF" "/dev/null"
checking for flags (-fdiagnostics-color=always) ... ok
> gcc "-fdiagnostics-color=always"
checking for g++ ... /usr/bin/g++
checking for the shared library linker (sh) ... g++
checking for /usr/bin/g++ ... ok
checking for flags (-fPIC) ... ok
> g++ "-fPIC" "-shared"
[ 44%]: linking.release libFCSymPass.so
/usr/bin/g++ -o build/linux/x86_64/release/libFCSymPass.so build/.objs/FCSymPass/linux/x86_64/release/compiler/pass.cpp.o -shared -fPIC -m64 -L/usr/lib -s -lLLVMAArch64AsmParser -lLLVMAArch64CodeGen -lLLVMAArch64Desc -lLLVMAArch64Disassembler -lLLVMAArch64Info -lLLVMAArch64Utils -lLLVMAMDGPUAsmParser -lLLVMAMDGPUCodeGen -lLLVMAMDGPUDesc -lLLVMAMDGPUDisassembler -lLLVMAMDGPUInfo -lLLVMAMDGPUUtils -lLLVMARMAsmParser -lLLVMARMCodeGen -lLLVMARMDesc -lLLVMARMDisassembler -lLLVMARMInfo -lLLVMARMUtils -lLLVMAVRAsmParser -lLLVMAVRCodeGen -lLLVMAVRDesc -lLLVMAVRDisassembler -lLLVMAVRInfo -lLLVMAggressiveInstCombine -lLLVMAnalysis -lLLVMAsmParser -lLLVMAsmPrinter -lLLVMBPFAsmParser -lLLVMBPFCodeGen -lLLVMBPFDesc -lLLVMBPFDisassembler -lLLVMBPFInfo -lLLVMBinaryFormat -lLLVMBitReader -lLLVMBitWriter -lLLVMBitstreamReader -lLLVMCFGuard -lLLVMCFIVerify -lLLVMCodeGen -lLLVMCore -lLLVMCoroutines -lLLVMCoverage -lLLVMDWARFLinker -lLLVMDWP -lLLVMDebugInfoCodeView -lLLVMDebugInfoDWARF -lLLVMDebugInfoGSYM -lLLVMDebugInfoMSF -lLLVMDebugInfoPDB -lLLVMDemangle -lLLVMDlltoolDriver -lLLVMExecutionEngine -lLLVMExegesis -lLLVMExegesisAArch64 -lLLVMExegesisMips -lLLVMExegesisPowerPC -lLLVMExegesisX86 -lLLVMExtensions -lLLVMFileCheck -lLLVMFrontendOpenACC -lLLVMFrontendOpenMP -lLLVMFuzzMutate -lLLVMGlobalISel -lLLVMHexagonAsmParser -lLLVMHexagonCodeGen -lLLVMHexagonDesc -lLLVMHexagonDisassembler -lLLVMHexagonInfo -lLLVMIRReader -lLLVMInstCombine -lLLVMInstrumentation -lLLVMInterfaceStub -lLLVMInterpreter -lLLVMJITLink -lLLVMLTO -lLLVMLanaiAsmParser -lLLVMLanaiCodeGen -lLLVMLanaiDesc -lLLVMLanaiDisassembler -lLLVMLanaiInfo -lLLVMLibDriver -lLLVMLineEditor -lLLVMLinker -lLLVMMC -lLLVMMCA -lLLVMMCACustomBehaviourAMDGPU -lLLVMMCDisassembler -lLLVMMCJIT -lLLVMMCParser -lLLVMMIRParser -lLLVMMSP430AsmParser -lLLVMMSP430CodeGen -lLLVMMSP430Desc -lLLVMMSP430Disassembler -lLLVMMSP430Info -lLLVMMipsAsmParser -lLLVMMipsCodeGen -lLLVMMipsDesc -lLLVMMipsDisassembler -lLLVMMipsInfo -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMObjCARCOpts -lLLVMObject -lLLVMObjectYAML -lLLVMOption -lLLVMOrcJIT -lLLVMOrcShared -lLLVMOrcTargetProcess -lLLVMPasses -lLLVMPowerPCAsmParser -lLLVMPowerPCCodeGen -lLLVMPowerPCDesc -lLLVMPowerPCDisassembler -lLLVMPowerPCInfo -lLLVMProfileData -lLLVMRISCVAsmParser -lLLVMRISCVCodeGen -lLLVMRISCVDesc -lLLVMRISCVDisassembler -lLLVMRISCVInfo -lLLVMRemarks -lLLVMRuntimeDyld -lLLVMScalarOpts -lLLVMSelectionDAG -lLLVMSparcAsmParser -lLLVMSparcCodeGen -lLLVMSparcDesc -lLLVMSparcDisassembler -lLLVMSparcInfo -lLLVMSupport -lLLVMSymbolize -lLLVMSystemZAsmParser -lLLVMSystemZCodeGen -lLLVMSystemZDesc -lLLVMSystemZDisassembler -lLLVMSystemZInfo -lLLVMTableGen -lLLVMTableGenGlobalISel -lLLVMTarget -lLLVMTextAPI -lLLVMTransformUtils -lLLVMVectorize -lLLVMWebAssemblyAsmParser -lLLVMWebAssemblyCodeGen -lLLVMWebAssemblyDesc -lLLVMWebAssemblyDisassembler -lLLVMWebAssemblyInfo -lLLVMWebAssemblyUtils -lLLVMWindowsManifest -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMX86Desc -lLLVMX86Disassembler -lLLVMX86Info -lLLVMXCoreCodeGen -lLLVMXCoreDesc -lLLVMXCoreDisassembler -lLLVMXCoreInfo -lLLVMXRay -lLLVMipo
[ 66%]: ccache compiling.release runtime/main.cpp
/usr/bin/gcc -c -m64 -fPIC -O3 -std=c++20 -fmodules-ts -DNDEBUG -o build/.objs/FCSym/linux/x86_64/release/runtime/main.cpp.o runtime/main.cpp
[ 77%]: linking.release libFCSym.so
/usr/bin/g++ -o build/linux/x86_64/release/libFCSym.so build/.objs/FCSym/linux/x86_64/release/runtime/main.cpp.o build/.objs/FCSym/linux/x86_64/release/runtime/map.ixx.o -shared -fPIC -m64 -s

build cache stats:
cache directory: build/.build_cache
cache hit rate: 100%
cache hit: 3
cache miss: 0
new cached files: 0
remote cache hit: 0
remote new cached files: 0
preprocess failed: 0
compile fallback count: 0

[100%]: build ok!

**Comment by sunxfancy** [comment]
Arch package 一般开发包也就直接把header放到/usr/include里了，如果有特殊存放位置的，一般都会提供pc文件。
可以参考arch 打包规范： https://wiki.archlinux.org/title/Arch_package_guidelines#Directories

通过XXXConfig.cmake来获取include path我不清楚是否可行，但至少需要安装cmake，像LLVM的Install Path是如下计算的：
```cmake
# Compute the installation prefix from this LLVMConfig.cmake file location.
get_filename_component(LLVM_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(LLVM_INSTALL_PREFIX "${LLVM_INSTALL_PREFIX}" PATH)
get_filename_component(LLVM_INSTALL_PREFIX "${LLVM_INSTALL_PREFIX}" PATH)
get_filename_component(LLVM_INSTALL_PREFIX "${LLVM_INSTALL_PREFIX}" PATH)
```
既依赖变量CMAKE_CURRENT_LIST_FILE，又用到了函数get_filename_component向上层寻找。这恐怕不容易在没有cmake的情况下解析出来。当然有些简单的XXXConfig.cmake里面有可能提供了绝对路径，可能较为容易实现。

如果简单起见，一种简单的修复策略是如果有pc文件的，先走pkg-config，其次如果header里有/usr/include开头的，那么直接忽略该path，因为这个是编译器默认路径。如果有其他目录的，再引入其他目录。如果可以增加对cmake的调用，可以考虑调用cmake脚本模式去解析一下，然后把XXX_INCLUDE_DIR和XXX_LIBRARY_DIR求出来。这只需要写个小的cmake脚本，把对应include和library路径打印出来由xmake解析。该方案应该对其他提供cmake配置的native包应该也是可行的。

**Comment by waruqi** [comment]
> 其次如果header里有/usr/include开头的，那么直接忽略该path，因为这个是编译器默认路径。如果有其他目录的，再引入其他目录

你可以来个 pr ，直接本地测通过提过来。

**Comment by sunxfancy** [comment]
Ok, PR发过去了，本地测了下，路径在arch linux下应该没问题了，不过最好再测下msys和mingw，但可惜我不用Windows.

**Comment by waruqi** [comment]
msys 下，通常根目录是 /mingw64/include ，不会有冲突

**Comment by waruqi** [comment]
merge了
