### ISSUE TITLE
分布式编译服务器连不上时，应该回滚到本地编译

### ISSUE THREAD

**Issue by Domain** [xmake-io/xmake#2491]
### 你在什么场景下需要该功能？

配置了分布式编译，但是有些时候服务器连不上，这时候会编译失败，提示 server unreachable

### 描述可能的解决方案

编译开始时就尝试连接服务器，如果失败了，回滚到本地编译，而不是编译失败

**Comment by Domain** [comment]
另外，fastbuild分布式编译的时候，本地文件都编译完了之后，会自动编译已经分发出去的文件，哪一个先完成就用哪一个，这在网络环境比较差，或者远程机器比较卡的时候很有用，不知道xmake是否也有类似的功能。

**Comment by Domain** [comment]
同理，远程缓存服务器连不上时，也不应该编译失败，要么不缓存，要么本地缓存

**Comment by Domain** [comment]
同理，远程缓存服务器连不上时，也不应该编译失败，要么不缓存，要么本地缓存

**Comment by waruqi** [comment]
server unreachable 自动 fallback 我搞了下。dev

> 另外，fastbuild分布式编译的时候，本地文件都编译完了之后，会自动编译已经分发出去的文件，哪一个先完成就用哪一个，这在网络环境比较差，或者远程机器比较卡的时候很有用，不知道xmake是否也有类似的功能。

没有，暂时懒得搞。。
