### ISSUE TITLE
Preprocessing files left after compilation failed

### ISSUE THREAD

**Issue by OuYangPaste** [xmake-io/xmake#2510]
### Xmake 版本

v2.6.8+dev.98baab9

### 操作系统版本和架构

Linux: 5.15.24-amd64-desktop

### 描述问题

在编译失败后，由于 ccache 的原因在 build 目录下残留了 .c.c 预处理文件还没被及时删除，而 项目 xmake.lua 内部使用了 add_files("**.c") ，再次进行编译的时候会把这些残留的 .c.c 文件也 add 了 进去，导致再次编译错误

### 期待的结果

我不知道会不会有其他可能的在 build 目录下生成的类 .c 文件的情况(比如 unity_build？) 
这种情况交由用户去处理的话编译出错的时候确实看着信息有点懵

**Comment by waruqi** [comment]
好多 rules 内部都会自动生成 c/cpp， qt, protobuf, lex, ....  

通常不建议全局 `**.c` , 目前这边只能针对性改进 对 .c.c 的删除清理，其他的暂时没法改进

**Comment by OuYangPaste** [comment]
> 通常不建议全局 `**.c` , 目前这边只能针对性改进 对 .c.c 的删除清理，其他的暂时没法改进

只能这样了

一般我不会 全局 add **.c，我有个同事说 xmake 更新到最新发现调代码的时候总是报奇奇怪怪的错，我过去一看发现报错的是 .c.c 文件，对了下 xmake.lua 才发现确实是 add_files("**.c") 导致的，某种程度上也反映了一些用户比较喜欢无脑 add_files("**.c")

是否应该应对 add_files("**...") 这种情况加以警示打印？

**Comment by waruqi** [comment]
> 是否应该应对 add_files("**...") 这种情况加以警示打印？

加不了，如果没出问题，天天报 warning  其他用户又要叫了

**Comment by OuYangPaste** [comment]
> > 是否应该应对 add_files("**...") 这种情况加以警示打印？
> 
> 加不了，如果没出问题，天天报 warning 其他用户又要叫了

哈哈确实

**Comment by waruqi** [comment]
我改进过了，编译失败也会自动删除 cppfile ，可以更新下试试

**Comment by OuYangPaste** [comment]
👌验证过没问题
