### ISSUE TITLE
远程缓存会卡死

### ISSUE THREAD

**Issue by Domain** [xmake-io/xmake#2512]
### Xmake 版本

2.6.8

### 操作系统版本和架构

Windows 11

### 描述问题

服务器开启了远程缓存，客户端找到了缓存，但是没法使用，一直显示pull cache，超过1个多小时都不会超时。服务器有报错：

<pre>
C:\Users\build>xmake service -vD
<remote_build_server>: listening 0.0.0.0:9691 ..
<remote_cache_server>: listening 0.0.0.0:9692 ..
<distcc_build_server>: listening 0.0.0.0:9693 ..
<remote_cache_server>: <socket: tcp4/872.0>: session connected
<remote_cache_server>: <socket: tcp4/908.0>: session connected
<remote_cache_server>: <socket: tcp4/912.0>: session connected
<remote_cache_server>: <socket: tcp4/916.0>: session connected
<remote_cache_server>: <socket: tcp4/920.0>: session connected
<remote_cache_server>: <socket: tcp4/924.0>: session connected
<remote_cache_server>: <socket: tcp4/928.0>: session connected
<remote_cache_server>: <socket: tcp4/932.0>: session connected
<remote_cache_server>: <socket: tcp4/936.0>: session connected
<remote_cache_server>: <socket: tcp4/940.0>: session connected
<remote_cache_server>: <socket: tcp4/944.0>: session connected
<remote_cache_server>: <socket: tcp4/948.0>: session connected
<remote_cache_server>: <socket: tcp4/952.0>: session connected
<remote_cache_server>: <socket: tcp4/956.0>: session connected
<remote_cache_server>: <socket: tcp4/960.0>: session connected
<remote_cache_server>: <socket: tcp4/964.0>: session connected
<remote_cache_server>: <socket: tcp4/968.0>: session connected
<remote_cache_server>: <socket: tcp4/972.0>: session connected
<remote_cache_server>: <socket: tcp4/976.0>: session connected
<remote_cache_server>: <socket: tcp4/980.0>: session connected
<remote_cache_server>: <socket: tcp4/984.0>: session connected
<remote_cache_server>: <socket: tcp4/988.0>: session connected
<remote_cache_server>: <socket: tcp4/992.0>: session connected
<remote_cache_server>: <socket: tcp4/996.0>: session connected
<remote_cache_server>: <socket: tcp4/1000.0>: session connected
<remote_cache_server>: <socket: tcp4/1004.0>: session connected
<remote_cache_server>: <socket: tcp4/1008.0>: session connected
<remote_cache_server>: <socket: tcp4/1012.0>: session connected
<remote_cache_server>: <socket: tcp4/1016.0>: session connected
<remote_cache_server>: <socket: tcp4/1020.0>: session connected
<remote_cache_server>: <socket: tcp4/1028.0>: session connected
<remote_cache_server>: <socket: tcp4/872.0>: <session 73885b64>: on handle message(9)
{
  token = "caa00ef84ecf37b842326e71137db005",
  session_id = "73885b64",
  code = 9,
  filename = "4f505cbcd68cb57263f9407e5243d899"
}

@programdir\modules\private\service\remote_cache\server.lua:88: session has not been connected!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:872]: in function 'raiselevel'
    [@programdir\core\sandbox\modules\utils.lua:181]: in function 'assert'
    [@programdir\modules\private\service\remote_cache\server.lua:88]:

<remote_cache_server>: <socket: tcp4/872.0>: <session 73885b64>: send ok
<remote_cache_server>: <socket: tcp4/908.0>: <session 73885b64>: on handle message(9)
{
  token = "caa00ef84ecf37b842326e71137db005",
  session_id = "73885b64",
  code = 9,
  filename = "5fbf8875ae9048b147b097bf7c22398c"
}

@programdir\modules\private\service\remote_cache\server.lua:88: session has not been connected!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:872]: in function 'raiselevel'
    [@programdir\core\sandbox\modules\utils.lua:181]: in function 'assert'
    [@programdir\modules\private\service\remote_cache\server.lua:88]:

<remote_cache_server>: <socket: tcp4/908.0>: <session 73885b64>: send ok
<remote_cache_server>: <socket: tcp4/912.0>: <session 73885b64>: on handle message(9)
{
  token = "caa00ef84ecf37b842326e71137db005",
  session_id = "73885b64",
  code = 9,
  filename = "e75cc824dba5061ca15dcbc61e7a1142"
}

@programdir\modules\private\service\remote_cache\server.lua:88: session has not been connected!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:872]: in function 'raiselevel'
    [@programdir\core\sandbox\modules\utils.lua:181]: in function 'assert'
    [@programdir\modules\private\service\remote_cache\server.lua:88]:

<remote_cache_server>: <socket: tcp4/912.0>: <session 73885b64>: send ok
<remote_cache_server>: <socket: tcp4/916.0>: <session 73885b64>: on handle message(9)
{
  token = "caa00ef84ecf37b842326e71137db005",
  session_id = "73885b64",
  code = 9,
  filename = "f63a9bda6bcd53499c3bae4fe3320436"
}
</pre>

### 期待的结果

能正常获取缓存，或者快速超时，转本地缓存

**Comment by Domain** [comment]
C:\Users\build&gt;xmake service -vD
&lt;remote_build_server&gt;: listening 0.0.0.0:9691 ..
&lt;remote_cache_server&gt;: listening 0.0.0.0:9692 ..
&lt;distcc_build_server&gt;: listening 0.0.0.0:9693 ..
&lt;remote_cache_server&gt;: &lt;socket: tcp4/872.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/908.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/912.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/916.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/920.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/924.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/928.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/932.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/936.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/940.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/944.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/948.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/952.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/956.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/960.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/964.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/968.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/972.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/976.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/980.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/984.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/988.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/992.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/996.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/1000.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/1004.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/1008.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/1012.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/1016.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/1020.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/1028.0&gt;: session connected
&lt;remote_cache_server&gt;: &lt;socket: tcp4/872.0&gt;: &lt;session 73885b64&gt;: on handle message(9)
{
  token = "caa00ef84ecf37b842326e71137db005",
  session_id = "73885b64",
  code = 9,
  filename = "4f505cbcd68cb57263f9407e5243d899"
}

@programdir\modules\private\service\remote_cache\server.lua:88: session has not been connected!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:872]: in function 'raiselevel'
    [@programdir\core\sandbox\modules\utils.lua:181]: in function 'assert'
    [@programdir\modules\private\service\remote_cache\server.lua:88]:

&lt;remote_cache_server&gt;: &lt;socket: tcp4/872.0&gt;: &lt;session 73885b64&gt;: send ok
&lt;remote_cache_server&gt;: &lt;socket: tcp4/908.0&gt;: &lt;session 73885b64&gt;: on handle message(9)
{
  token = "caa00ef84ecf37b842326e71137db005",
  session_id = "73885b64",
  code = 9,
  filename = "5fbf8875ae9048b147b097bf7c22398c"
}

@programdir\modules\private\service\remote_cache\server.lua:88: session has not been connected!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:872]: in function 'raiselevel'
    [@programdir\core\sandbox\modules\utils.lua:181]: in function 'assert'
    [@programdir\modules\private\service\remote_cache\server.lua:88]:

&lt;remote_cache_server&gt;: &lt;socket: tcp4/908.0&gt;: &lt;session 73885b64&gt;: send ok
&lt;remote_cache_server&gt;: &lt;socket: tcp4/912.0&gt;: &lt;session 73885b64&gt;: on handle message(9)
{
  token = "caa00ef84ecf37b842326e71137db005",
  session_id = "73885b64",
  code = 9,
  filename = "e75cc824dba5061ca15dcbc61e7a1142"
}

@programdir\modules\private\service\remote_cache\server.lua:88: session has not been connected!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:872]: in function 'raiselevel'
    [@programdir\core\sandbox\modules\utils.lua:181]: in function 'assert'
    [@programdir\modules\private\service\remote_cache\server.lua:88]:

&lt;remote_cache_server&gt;: &lt;socket: tcp4/912.0&gt;: &lt;session 73885b64&gt;: send ok
&lt;remote_cache_server&gt;: &lt;socket: tcp4/916.0&gt;: &lt;session 73885b64&gt;: on handle message(9)
{
  token = "caa00ef84ecf37b842326e71137db005",
  session_id = "73885b64",
  code = 9,
  filename = "f63a9bda6bcd53499c3bae4fe3320436"
}

**Comment by waruqi** [comment]
这两天没时间细看，等周末看下

**Comment by Domain** [comment]
几天没跑了，我没有删除.xmake，现在只是重新connect，没问题了。我觉得是不是加一个超时好一点？出问题了自动不用缓存

**Comment by waruqi** [comment]
超时我初步支持了，可以切到 `timeout` 分支试下。。`xmake update -s github:xmake-io/xmake#timeout`

```lua
$ cat ~/.xmake/service/client.conf
{
    send_timeout = 5000,
    recv_timeout = 5000,
    connect_timeout = 5000,
    distcc_build = {}
}
```

默认配置，timeout 都是 -1，你可以可选配置上对应的 send/recv/connect 超时，也可以在 distcc_build/remote_cache 的配置块里面，单独对某个 client 服务配置上。

**Comment by waruqi** [comment]
我merge了 后续有问题 先关了 再开
