### ISSUE TITLE
Better support for LTO 

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#2515]
### Is your feature request related to a problem? Please describe.

- [x] package config
- [x] rules
- [x] gcc/clang/msvc
- [x] policy

### References

- https://clang.llvm.org/docs/ThinLTO.html#controlling-backend-parallelism
- https://stackoverflow.com/questions/31355692/how-do-i-enable-link-time-optimization-lto-with-cmake
- https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html

#### Solution1: Use policy

for global

```lua
set_policy("build.optimization.lto", true)
```

for target

```lua
target("test")
    set_policy("build.optimization.lto", true)
```

for cli option

```console
xmake f --policy=build.optimization.lto
```

for package

```lua
add_requires("zlib", {configs = {lto = true}})
```

cli

```console
xrepo install -f "lto=true" zlib
```

#### Solution2: Improve set_optimize

add new `set_optimizes` api

```lua
set_optimizes("faster", "lto")
```

```lua
set_optimize("faster")
add_optimizes("lto")
```

**Comment by sunxfancy** [comment]
Clang的thin-lto对分布式很友好，如果能和xmake的分布式构建一起使用，那就很棒了
GCC 好像也有个WHOPR的扩展是类似thin-lto的，不过没用过

**Comment by waruqi** [comment]
> Clang的thin-lto对分布式很友好，如果能和xmake的分布式构建一起使用，那就很棒了 GCC 好像也有个WHOPR的扩展是类似thin-lto的，不过没用过

现在分布式原本就支持 lto 的，你配上对应 flags 就行了

这里只是打算提供一些内置规则和配置选项，来简化不同编译器对 lto flags的配置而已。

**Comment by waruqi** [comment]
@SirLynix @xq114 Any ideas for LTO configuration solution?

**Comment by Zmmfly** [comment]
有没有方案3，两种都要，策略默认flase，方案2作为独立开关

**Comment by SirLynix** [comment]
> @SirLynix @xq114 Any ideas for LTO configuration solution?

One benefit of policies would be to allow configuring every project to use LTO without modifying their xmake.lua

I'm wondering, doesn't LTO adds some constraints with static linking?

**Comment by xq114** [comment]
https://docs.microsoft.com/en-us/cpp/build/reference/gl-whole-program-optimization?view=msvc-170

It's better if we can check whether the compiler supports LTO explicitly

**Comment by waruqi** [comment]
> I'm wondering, doesn't LTO adds some constraints with static linking?

what's constraints? need pass `-flto` and some optimization flags to ldflags.

**Comment by sunxfancy** [comment]
I think it's better to use policy solutions since LTO is usually useful while the library is also built using LTO. A global policy for enabling LTO for the whole project will be useful. The second reason, it can pass the configuration to required packages. Then, the root project may control the subproject to enable/disable LTO, which is more flexible.

**Comment by waruqi** [comment]
I have supported the solution1.
