### ISSUE TITLE
Xmake can't build/make/run my project

### ISSUE THREAD

**Issue by PoloNX** [xmake-io/xmake#2525]
### Xmake Version

xmake v2.6.8+master.42262f8

### Operating System Version and Architecture

Linux 5.18.7-arch1-1

### Describe Bug

when I do the command : "xmake project -k makefile" I'm stuck on this screen : (screen in "Additional Information and Error Logs")

when I do the command : "xmake f -cvD" I'm stuck on the step for pinging sourceforge.net, ferzkopp.net and libsdl.org

### Expected Behavior

I created a project on windows with sdl2 sdl2_gfx sdl_image and sdl_ttf. I wanted to continue it on arch linux now so I did "xmake project -k makefile"

### Project Configuration

add_requires("libsdl")
add_requires("libsdl_image")
add_requires("libsdl_ttf")
add_requires("libsdl_gfx")

function main()
  io.read()
end

target("BurgerTruck")
  set_kind("binary")
  set_languages("c++20")
  add_files("src/*.cpp")
  add_headerfiles("src/*.hpp")
  add_packages("libsdl")
  add_packages("libsdl_image")
  add_packages("libsdl_ttf")
  add_packages("libsdl_gfx")

### Additional Information and Error Logs

if i do "xmake project -k makefile" : 
![image](https://user-images.githubusercontent.com/57038157/177047711-972ac098-4d48-48a8-afdc-c087bde14736.png)
if I do "XMAKE_PROFILE=stuck xmake f -cvD" : 
![image](https://user-images.githubusercontent.com/57038157/177047730-f659a729-7aac-4239-a6e5-32ac02c5fa17.png)

**Comment by waruqi** [comment]
I tried to reproduce it on my archlinux, but it works for me.

**Comment by waruqi** [comment]
I added some logs, you can update to test branch and get me full logs

```console
xmake update github:xmake-io/xmake#test
xmake f -cvD -y
```

**Comment by PoloNX** [comment]
> I added some logs, you can update to test branch and give me full logs
> 
> 
> 
> ```console
> 
> xmake update github:xmake-io/xmake#test
> 
> xmake f -cvD -y
> 
> ```

I'll test it in few days I'm not at my home sorry.

**Comment by PoloNX** [comment]
I installed the update with  `xmake update github:xmake-io/xmake#test` without error and get this with 
`xmake f -cvD -y`

`➜  BurgerTruck xmake update github:xmake-io/xmake#test
update version test from https://github.com/xmake-io/xmake.git ..
  => download https://github.com/xmake-io/xmake.git .. ok
  => install to ~/.local/bin .. ok
➜  BurgerTruck xmake f -cvD -y
checking for platform ... linux
checking for architecture ... x86_64
checking for gcc ... /usr/bin/gcc
checkinfo: cannot runv(dmd --version), No such file or directory
checking for dmd ... no
checkinfo: cannot runv(ldc2 --version), No such file or directory
checking for ldc2 ... no
checkinfo: cannot runv(gdc --version), No such file or directory
checking for gdc ... no
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
/usr/bin/git rev-parse HEAD
checking for pkg-config ... /usr/bin/pkg-config
checking for pkg-config ... /usr/bin/pkg-config
finding util-macros from xmake ..
checking for xmake::util-macros ... no
checking for pacman ... /usr/bin/pacman
checkinfo: cannot runv(emerge --version), No such file or directory
checking for emerge ... no
finding util-macros from brew ..
checking for brew ... no
finding util-macros from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding util-macros from conan ..
finding util-macros from pkgconfig ..
checking for pkg-config ... /usr/bin/pkg-config
finding util-macros from pacman ..
finding util-macros from system ..
checking for util-macros ... no
finding xorgproto from xmake ..
checking for xmake::xorgproto ... no
finding x11proto-dev from apt ..
checkinfo: cannot runv(dpkg --version), No such file or directory
checking for dpkg ... no
checking for apt::x11proto-dev ... no
finding xproto from pkgconfig ..
checking for pkgconfig::xproto ... no
finding xorgproto from brew ..
finding xorgproto from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding xorgproto from conan ..
finding xorgproto from pkgconfig ..
finding xorgproto from pacman ..
checking for xorgproto ... pacman::xorgproto 2.1.1
finding xtrans from xmake ..
checking for xmake::xtrans ... no
finding xtrans-dev from apt ..
checking for apt::xtrans-dev ... no
finding xtrans from pacman ..
checking for pacman::xtrans ... no
finding xtrans from brew ..
finding xtrans from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding xtrans from conan ..
finding xtrans from pkgconfig ..
finding xtrans from pacman ..
finding xtrans from system ..
checking for xtrans ... no
finding openssl from xmake ..
checking for xmake::openssl ... no
finding openssl from find_openssl ..
finding openssl from brew ..
finding openssl from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding openssl from conan ..
finding openssl from pkgconfig ..
checking for openssl ... pkgconfig::openssl 1.1.1p
checking for xmake-repo::openssl ... openssl 1.1.1p
finding ca-certificates from xmake ..
checking for xmake::ca-certificates ... no
finding ca-certificates from brew ..
finding ca-certificates from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding ca-certificates from conan ..
finding ca-certificates from pkgconfig ..
finding ca-certificates from pacman ..
checking for ca-certificates ... pacman::ca-certificates 20210603
finding libffi from xmake ..
checking for xmake::libffi ... no
finding libffi-dev from apt ..
checking for apt::libffi-dev ... no
finding libffi from pacman ..
checking for pacman::libffi ... libffi 3.4.2
finding zlib from xmake ..
checking for xmake::zlib ... no
finding zlib from pacman ..
checking for pacman::zlib ... zlib 1.2.12
checking for python ... /usr/bin/python
checking for python3 ... /usr/bin/python3
finding python from xmake ..
checking for xmake::python ... no
finding python from brew ..
finding python from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding python from conan ..
finding python from pkgconfig ..
finding python from pacman ..
checking for python ... pacman::python 3.10
finding xcb-proto from xmake ..
checking for xmake::xcb-proto ... no
finding xcb-proto from brew ..
finding xcb-proto from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding xcb-proto from conan ..
finding xcb-proto from pkgconfig ..
finding xcb-proto from pacman ..
checking for xcb-proto ... pacman::xcb-proto 1.15.2
finding libpthread-stubs from xmake ..
checking for xmake::libpthread-stubs ... no
finding libpthread-stubs from brew ..
finding libpthread-stubs from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding libpthread-stubs from conan ..
finding libpthread-stubs from pkgconfig ..
finding libpthread-stubs from pacman ..
finding libpthread-stubs from system ..
checking for libpthread-stubs ... no
finding libxau from xmake ..
checking for xmake::libxau ... no
finding libxau-dev from apt ..
checking for apt::libxau-dev ... no
finding libxau from pacman ..
checking for pacman::libxau ... libxau 1.0.9
finding libxdmcp from xmake ..
checking for xmake::libxdmcp ... no
finding libxdmcp-dev from apt ..
checking for apt::libxdmcp-dev ... no
finding libxmdcp from pacman ..
checking for pacman::libxmdcp ... no
finding libxdmcp from brew ..
finding libxdmcp from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding libxdmcp from conan ..
finding libxdmcp from pkgconfig ..
checking for libxdmcp ... pkgconfig::libxdmcp 1.1.3
finding libxcb from xmake ..
checking for xmake::libxcb ... no
finding libxcb1-dev from apt ..
checking for apt::libxcb1-dev ... no
finding libxcb from pacman ..
checking for pacman::libxcb ... libxcb 1.15
finding libx11 from xmake ..
checking for xmake::libx11 ... no
finding libx11-dev from apt ..
checking for apt::libx11-dev ... no
finding libx11 from pacman ..
checking for pacman::libx11 ... libx11 1.8.1
finding libxext from xmake ..
checking for xmake::libxext ... no
finding libxext-dev from apt ..
checking for apt::libxext-dev ... no
finding libxext from brew ..
finding libxext from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding libxext from conan ..
finding libxext from pkgconfig ..
checking for libxext ... pkgconfig::libxext 1.3.4
finding libsdl from xmake ..
checking for xmake::libsdl ... no
checking for xmake-repo::libsdl ... libsdl 2.0.22
checking for m4 ... /usr/bin/m4
checking for autoconf ... /usr/bin/autoconf
checking for automake ... /usr/bin/automake
checkinfo: cannot runv(apt::automake --version), No such file or directory
checking for apt::automake ... no
checkinfo: cannot runv(pacman::automake --version), No such file or directory
checking for pacman::automake ... no
checking for automake ... /usr/bin/automake
finding libsdl_image from xmake ..
checking for xmake::libsdl_image ... no
finding sdl2_image from pacman ..
checking for pacman::sdl2_image ... no
finding libsdl2-image-dev from apt ..
checking for apt::libsdl2-image-dev ... no
finding libsdl_image from brew ..
finding libsdl_image from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding libsdl_image from conan ..
finding libsdl_image from pkgconfig ..
finding libsdl_image from pacman ..
finding libsdl_image from system ..
checking for libsdl_image ... no
finding freetype from xmake ..
checking for xmake::freetype ... no
finding freetype2 from pkgconfig ..
checking for pkgconfig::freetype2 ... freetype2 24.3.18
finding libsdl_ttf from xmake ..
checking for xmake::libsdl_ttf ... no
finding sdl2_ttf from pacman ..
checking for pacman::sdl2_ttf ... no
finding libsdl2-ttf-dev from apt ..
checking for apt::libsdl2-ttf-dev ... no
finding libsdl_ttf from brew ..
finding libsdl_ttf from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding libsdl_ttf from conan ..
finding libsdl_ttf from pkgconfig ..
finding libsdl_ttf from pacman ..
finding libsdl_ttf from system ..
checking for libsdl_ttf ... no
finding libsdl_gfx from xmake ..
checking for xmake::libsdl_gfx ... no
finding sdl2_gfx from pacman ..
checking for pacman::sdl2_gfx ... no
finding libsdl2-gfx-dev from apt ..
checking for apt::libsdl2-gfx-dev ... no
finding libsdl_gfx from brew ..
finding libsdl_gfx from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding libsdl_gfx from conan ..
finding libsdl_gfx from pkgconfig ..
finding libsdl_gfx from pacman ..
finding libsdl_gfx from system ..
checking for libsdl_gfx ... no
checking for ping ... /usr/bin/ping
pinging for the host(sourceforge.net) ... 20 ms
pinging for the host(www.ferzkopp.net) ... 129 ms
pinging for the host(www.libsdl.org) ... 171 ms
^C
`

**Comment by PoloNX** [comment]
I can send a screenshot if it's better but I can't send you all the output

**Comment by PoloNX** [comment]
I have one infinite loop with this :
`poller:wait ok  0
packages_pending 3 0 0
poller:wait ..  1.0
[xmake]: [poller_wait]: tb_poller_wait .. 1
[xmake]: [poller_wait]: tb_poller_wait ok, 0`

**Comment by waruqi** [comment]
I added more logs in test branch, please update and try it again. then give me more logs.

**Comment by waruqi** [comment]
I added more logs in test branch, please update and try it again. then give me more logs.

**Comment by waruqi** [comment]
I added more logs, can you try it again and give me logs from `print("_fetch_packages")` to last?

**Comment by PoloNX** [comment]
I have a lot of log and my console can't stock all them. For which pkg you want the log ? (it's the start) 

_fetch_packages ..
_fetch_packages ..
fetch pkg:  pkg-config
ready:  true nil
fetch instance pkg-config
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
checking for pkg-config ... /usr/bin/pkg-config
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
checking for pkg-config ... /usr/bin/pkg-config
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
fetch instance pkg-config exists: true
fetch pkg:  util-macros
  > dep:  pkg-config true
ready:  true nil
fetch instance util-macros
finding util-macros from xmake ..
checking for xmake::util-macros ... no
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
checking for pacman ... /usr/bin/pacman
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
checkinfo: cannot runv(emerge --version), No such file or directory
checking for emerge ... no
finding util-macros from brew ..
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
checking for brew ... no
finding util-macros from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding util-macros from conan ..
finding util-macros from pkgconfig ..
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
checking for pkg-config ... /usr/bin/pkg-config
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
finding util-macros from pacman ..
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
finding util-macros from system ..
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
checking for util-macros ... no
fetch instance util-macros exists: false
fetch pkg:  xorgproto

**Comment by PoloNX** [comment]
for SDL_TTF:
fetch pkg:  libsdl_ttf
  > dep:  pkg-config true
  > dep:  util-macros true
  > dep:  xorgproto true
  > dep:  xtrans true
  > dep:  pkg-config true
  > dep:  openssl true
  > dep:  ca-certificates true
  > dep:  libffi true
  > dep:  zlib true
  > dep:  python true
  > dep:  python true
  > dep:  xcb-proto true
  > dep:  libpthread-stubs true
  > dep:  libxau true
  > dep:  libxdmcp true
  > dep:  libxcb true
  > dep:  libx11 true
  > dep:  libxext true
  > dep:  libsdl true
  > dep:  freetype true
ready:  true nil
fetch instance libsdl_ttf
finding libsdl_ttf from xmake ..
checking for xmake::libsdl_ttf ... no
finding sdl2_ttf from pacman ..
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
checking for pacman::sdl2_ttf ... no
finding libsdl2-ttf-dev from apt ..
checking for apt::libsdl2-ttf-dev ... no
finding libsdl_ttf from brew ..
finding libsdl_ttf from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding libsdl_ttf from conan ..
finding libsdl_ttf from pkgconfig ..
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
finding libsdl_ttf from pacman ..
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
finding libsdl_ttf from system ..
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 0
[xmake]: [poller_wait]: tb_poller_wait .. 1000
[xmake]: [poller_wait]: tb_poller_wait ok, 1
checking for libsdl_ttf ... no
fetch instance libsdl_ttf exists: false

**Comment by PoloNX** [comment]
or the log.txt (thanks Lynix)
[log.txt](https://github.com/xmake-io/xmake/files/9070629/log.txt)

**Comment by PoloNX** [comment]
the full log after pressed y: 
[log.txt](https://github.com/xmake-io/xmake/files/9070876/log.txt)

**Comment by PoloNX** [comment]
New logs : 
[log.txt](https://github.com/xmake-io/xmake/files/9078966/log.txt)

**Comment by waruqi** [comment]
I found some problems, but I need more logs, please update to test and try it again.

**Comment by PoloNX** [comment]
new logs with last update
[log.txt](https://github.com/xmake-io/xmake/files/9079322/log.txt)

**Comment by waruqi** [comment]
I probably know the cause of the problem, but I need some time to fix it.

**Comment by PoloNX** [comment]
Good news :) 
Take your time.

**Comment by PoloNX** [comment]
I close the issue ?

**Comment by waruqi** [comment]
no, please wait for my fix first

**Comment by waruqi** [comment]
I have fixed it, please update to dev and try it again.

xmake update dev

**Comment by PoloNX** [comment]
Thanks it works fine
