### ISSUE TITLE
Compile Commands 生成过程

### ISSUE THREAD

**Issue by SineStriker** [xmake-io/xmake#2535]
### Xmake Version

2.6.8

### Operating System Version and Architecture

Windows 10 家庭中文版 21H2 19044.1766

### Describe Bug

+ xmake.lua
````
target("XMakeQtTest")
    add_rules("qt.widgetapp")
    add_files("*.cpp")
    add_files("*.h")
````
因为CMake里`add_executable`是可以加入头文件的，于是就往里面加了头文件（不知道算不算不规范）。
然后config没有问题，生成`CMakeLists.txt`也没有问题，也能正常build和run，但是生成`commpile_commands.json`就报错了
````
error: method 'find' is not callable (a nil value)
````
试着在源码里找了一下，在`xmake/plugins/project/clang/compile_commands.lua`中的`_translate_arguments`函数中，for循环遍历的键值对中，正常来说`arg`应该是string，看意思应该是在`compile_commands.json`中放到`arguments`块里面的一个参数，如果不存在`add_files("*.h")`那么没有问题，但如果存在，这个函数里遍历到后面，某个`arg`就不是字符串而是table了，所以就触发找不到`find`成员函数中止了，然后我试着输出了一下这个table。
````
build/.gens/XMakeQtTest/windows/x64/release/rules/qt/ui
````
这显然是不正常的。

### Expected Behavior

如果不允许添加头文件的话，那么最好config的时候直接报错。
如果允许的话，那么这应该算是生成`compile_commands`的一个bug。

### Project Configuration

target("XMakeQtTest")
    add_rules("qt.widgetapp")
    add_files("*.cpp")
    add_files("*.h")

### Additional Information and Error Logs

````
# cmds
xmake config
xmake project -k compile_commands -a outputdir ./build

# output
checking for Microsoft Visual Studio (x64) version ... 2019
checking for Qt SDK directory ... C:/Qt/5.15.2/msvc2019_64
checking for Qt SDK version ... 5.15.2
error: method 'find' is not callable (a nil value)
````

**Comment by SineStriker** [comment]
如果可以的话，最好能在执行命令的时候如果报错中止打印trace。

**Comment by waruqi** [comment]
> 如果不存在add_files("*.h")那么没有问题，但如果存在，这个函数里遍历到后面，某个arg就不是字符串而是table了，所以就触发找不到find成员函数中止了，然后我试着输出了一下这个table。

那是因为 qt 的 moc rule 里面有 path instance 作为参数，后来新加的，暂时还没对 compile_commands 做兼容处理，我刚改进了下，更新到 dev 再试试 xmake update -s dev

> 如果不允许添加头文件的话，那么最好config的时候直接报错。

qt 的规则，支持加 .h ，需要处理 moc 。。非 qt 项目，不支持加 .h ，并且原本就会提示错误 not support

> 如果可以的话，最好能在执行命令的时候如果报错中止打印trace。

你没开 -vD 参数

**Comment by SineStriker** [comment]
qt的项目不加.h没法扩展Q_OBJECT运行moc，所以我觉得，要不干脆可以随便加.h文件得了（？
Qt项目也可以完全作为CMake项目，所以其实不必搞特殊化。况且不用xmake自带的qt规则，多写点脚本也能构建一个Qt工程。

**Comment by waruqi** [comment]
> qt的项目不加.h没法扩展Q_OBJECT运行moc，所以我觉得，要不干脆可以随便加.h文件得了（？

所以我不是说了么，现在 qt项目原本支持加 .h 啊

> qt 的规则，支持加 .h ，需要处理 moc 

> Qt项目也可以完全作为CMake项目，所以其实不必搞特殊化。况且不用xmake自带的qt规则，多写点脚本也能构建一个Qt工程。

Qt 项目必须得用 rules，你愿意自己写脚本，不代表其他用户也愿意写一堆 qt sdk 环境探测，moc/qrc 处理等一坨脚本

这不是特殊化，.h 加 add_files 原本就是没任何必要的，xmake 里面 有 add_headerfiles 专门处理头文件安装，只有代码编译才走 add_files。。qt 的 .h 带有 moc ，需要转 cpp 编译，所以才会通过 rule 对 add_files 支持上。

**Comment by SineStriker** [comment]
有道理。希望教程能补上引用其他模块、引入私有类头文件还有自动生成翻译的做法。
