### ISSUE TITLE
使用llvm-mingw以shared方式引用cpr包失败

### ISSUE THREAD

**Issue by wsw0108** [xmake-io/xmake#2539]
### Xmake 版本

2.6.8

### 操作系统版本和架构

Windows 10

### 描述问题

用工具链llvm-mingw以shared方式引用cpr包时，cpr包编译失败。

如果xmake的toolchain文件clang.lua中的cxx顺序改为clang++在前，则可以成功。

不过不清楚这么改有没有什么副作用。

### 期待的结果

以这种方式使用cpr时，cpr能支持编译通过。

### 工程配置

[xmake-mingw-clang-using-cmake-shared-library.zip](https://github.com/xmake-io/xmake/files/9052751/xmake-mingw-clang-using-cmake-shared-library.zip)

### 附加信息和错误日志

[logs.txt](https://github.com/xmake-io/xmake/files/9052795/logs.txt)

**Comment by wsw0108** [comment]
这个mingw-winlibs-llvm有点特殊，又有gcc，又有clang。

支持llvm-mingw指的是https://github.com/mstorsjo/llvm-mingw/releases/download/20220323/llvm-mingw-20220323-ucrt-x86_64.zip么？里面的gcc应该只是个clang的别名。

不过我看toolchain mingw里面，g++也是排在cxx的值的第一个。

**Comment by waruqi** [comment]
> 这个mingw-winlibs-llvm有点特殊，又有gcc，又有clang。

我知道，所以我刚说 目前内部支持 gcc 

> 不过我看toolchain mingw里面，g++也是排在cxx的值的第一个。

你先去掉 `--toolchain=clang` 后，是否还有同样问题，然后再给份完整 logs

**Comment by wsw0108** [comment]
将 https://github.com/xmake-io/xmake/blob/afbbc9a0ed32f096a7e5006edfe042db547807c8/xmake/toolchains/mingw/xmake.lua#L68

和 

https://github.com/xmake-io/xmake/blob/afbbc9a0ed32f096a7e5006edfe042db547807c8/xmake/toolchains/mingw/xmake.lua#L81

的顺序调换后，对于上面的示例，只使用`--sdk=/path/to/mingw`，不加`--toolchain`也会出现链接错误。

就是这个会导致传递给cmake的cxx_compiler为gcc而不是g++，虽然传递给的cmake-linker确实是g++，但是cmake链接时仍然使用的gcc

**Comment by waruqi** [comment]
我知道这个，但是我现在需要 logs 分析问题。

**Comment by wsw0108** [comment]
> 我知道这个，但是我现在需要 logs 分析问题。

不使用`--toolchain=clang`是可以成功的。但是把mingw的toolchain里的两处调换顺序后，就出错了。是需要这个出错的logs么？

**Comment by waruqi** [comment]
目前只有 -p cross 编译，我会对 cmake 修正 gcc, g++ 的处理，mingw 下还不会

https://github.com/xmake-io/xmake/blob/afbbc9a0ed32f096a7e5006edfe042db547807c8/xmake/modules/package/tools/cmake.lua#L454-L461

**Comment by wsw0108** [comment]
了解，先关了。
