### ISSUE TITLE
设置vs工程调试目录

### ISSUE THREAD

**Issue by car520120** [xmake-io/xmake#2545]
### 你在什么场景下需要该功能？

如果工作目录不在build 目录时，生成的vs工程需要设置一下调试目录 LocalDebuggerWorkingDirectory

### 描述可能的解决方案

target:setWorkingDirectory("xxx")
设置工作目录
![image](https://user-images.githubusercontent.com/36702004/177900475-24a93cd5-9cd0-478c-8fee-1bc25a6ffc06.png)

**Comment by Domain** [comment]
应该是target:set_rundir吧
https://xmake.io/#/manual/project_target?id=targetset_rundir

**Comment by waruqi** [comment]
原本就支持，用 set_rundir 

https://github.com/xmake-io/xmake/blob/e8911871580e32e4b782c2bc98ed15248839916f/xmake/plugins/project/vstudio/impl/vs201x_vcxproj.lua#L343

**Comment by car520120** [comment]
![image](https://user-images.githubusercontent.com/36702004/178106923-7319aee8-655e-4ba4-bb1c-e7a8a2a09339.png)
![image](https://user-images.githubusercontent.com/36702004/178106937-3339f710-2420-4877-a559-0aee25a69880.png)
是支持的了，用的是绝对路径来的

**Comment by car520120** [comment]
https://github.com/car520120/xpbr.git

**Comment by waruqi** [comment]
因为你用了  `$(projectdir)` 和 `os.projectdir()`，这个值本身就是绝对路径，目前绝对路径不会自动处理路径变换，原样保留。

你可以直接用当前路径，add_includedirs/set_rundir 路径相关 api ，会自动根据当前 xmake.lua 所在路径自动展开处理，没必要每个地方都用 projectdir


```lua
set_rundir(".")
```
