### ISSUE TITLE
xrepo 依赖bash

### ISSUE THREAD

**Issue by leleliu008** [xmake-io/xmake#2549]
### Xmake Version

2.6.6+202207091354

### Operating System Version and Architecture

AlpineLinux

### Describe Bug

xrepo这个脚本非常简单， 依赖bash完全没有必要，应该考虑它的普适性。bash并不是所有GNU/Linux操作系统的默认安装的shell，比如AplineLinux就默认没有安装bash。

### Expected Behavior

我的建议：
```
#!/usr/bin/sh

BASEDIR="$( cd "$( dirname "$0" )" && pwd )/"

if [ ! -e "${BASEDIR}xmake" ]; then
    unset BASEDIR
fi

exec ${BASEDIR}xmake lua private.xrepo "$@"
```

**Comment by waruqi** [comment]
不依赖怎么搞？

**Comment by leleliu008** [comment]
不好意思，是我唐突了
