### ISSUE TITLE
生成相对路径 vs工程

### ISSUE THREAD

**Issue by car520120** [xmake-io/xmake#2550]
### 你在什么场景下需要该功能？

git clone https://github.com/car520120/xpbr.git
cd xpbr
xmake project -k vs

### 描述可能的解决方案

生成的vs工程使用相对路径

**Comment by car520120** [comment]
![image](https://user-images.githubusercontent.com/36702004/178111514-4c420a7e-7e5e-4748-8ac0-58c10bf66c24.png)
![image](https://user-images.githubusercontent.com/36702004/178111526-77f504e1-7d40-4aec-8fae-97471f4e9252.png)

**Comment by waruqi** [comment]
这个咱叔不处理，不可能完全避免绝对路径，如果 add_packages 引用了依赖库，肯定都是绝对路径，本地编译没问题就行了。。

**Comment by car520120** [comment]
其实整个工程都是使用xmake 构建的，没有使用到cmake 或者其它的工具的，应该支持才对的
