### ISSUE TITLE
clean命令应该只删除指定target的文件

### ISSUE THREAD

**Issue by Domain** [xmake-io/xmake#2552]
### 你在什么场景下需要该功能？

现在clean target时，会把所有依赖的目标文件也删除，是不是应该只删除这个指定的target？或者加个-r参数是否删除其他依赖目标的文件

### 描述可能的解决方案

默认只删除指定target的文件，增加-r参数，删除依赖目标的文件

**Comment by waruqi** [comment]
改了，去掉了 deps 的 clean
