### ISSUE TITLE
Filewatcher 

### ISSUE THREAD

**Issue by Immortalin** [xmake-io/xmake#2555]
### Is your feature request related to a problem? Please describe.

Package managers often have a "watch" feature where code is automatically rebuilt and ran when the source is changed.

Something like https://github.com/watchexec/cargo-watch

### Describe the solution you'd like

`xmake watch` command

### Describe alternatives you've considered

N/A

### Additional context

Each OS has different filewatcher APIs, use `inotify` on Linux, `FSEvents` on Mac, and `ReadDirectoryChangesW` for Windows. (BSD has something called `kqueue` but I am not sure)

**Comment by waruqi** [comment]
xmake does not need to provide the `xmake watch` command, but I will consider providing some api modules related to file watcher. With these api modules and custom tasks, you can easily implement any watch function yourself, including `xmake watch`.

like this

```lua
task("watch")
     on_run(function (target)
         os.watchdir("src", function()
             -- do some thing
             os.exec("xmake build")
         end)
     end)
```

**Comment by OuYangPaste** [comment]
I used to implement similar features based on xmake plugin and [entr](https://github.com/eradman/entr),
for private

**Comment by waruqi** [comment]
I have supported it in https://github.com/xmake-io/xmake/pull/2592 and add new `xmake watch` plugin command.

## `xmake watch` plugin

### Watch project directory and build project

```console
$ xmake watch
watching /private/tmp/test/src/** ..
watching /private/tmp/test/* ..
/private/tmp/test/src/main.cpp modified[ 25%]: ccache compiling.release src/main.cpp
[ 50%]: linking.release test
[100%]: build ok!
```

### Watch the given directories

```console
$ xmake watch -d src
$ xmake watch -d "src;tests/*"
```

### Watch and run given commands

```console
$ xmake watch -c "xmake; xmake run"
```

### Watch and run given lua script file

```console
$ xmake watch -s /tmp/test.lua
```

### Watch and build the given target

```console
$ xmake watch targetname
```

## Watch modules

### basic api

```lua
import("core.base.fwatcher")

function main(watchdir)
    print("watch %s ..", watchdir)
    fwatcher.add(watchdir)
    while true do
        local ok, event = fwatcher.wait(-1)
        if ok > 0 then
            print(event)
        end
    end
end
```

### callback api

```lua
import("core.base.fwatcher")

function main(watchdir)
    print("watch %s ..", watchdir)
    fwatcher.watchdirs(watchdir, function (event)
        local status
        if event.type == fwatcher.ET_CREATE then
            status = "created"
        elseif event.type == fwatcher.ET_MODIFY then
            status = "modified"
        elseif event.type == fwatcher.ET_DELETE then
            status = "deleted"
        end
        print(event.path, status)
    end)
end
```

### specific event callback api

```lua
import("core.base.fwatcher")

function main(watchdir)
    print("watch %s ..", watchdir)
    fwatcher.on_modified(watchdir, function (filepath)
        print(filepath, "modified")
    end)
end
```

```lua
import("core.base.fwatcher")

function main(watchdir)
    print("watch %s ..", watchdir)
    fwatcher.on_created(watchdir, function (filepath)
        print(filepath, "created")
    end)
end
```

```lua
import("core.base.fwatcher")

function main(watchdir)
    print("watch %s ..", watchdir)
    fwatcher.on_deleted(watchdir, function (filepath)
        print(filepath, "deleted")
    end)
end
```

**Comment by waruqi** [comment]
There are still some bugs in the fsevent based implementation on the mac, I will continue to improve it in the next few days.

**Comment by waruqi** [comment]
I have fixed all bugs and It is now fully available.
