### ISSUE TITLE
Send cached object file failed

### ISSUE THREAD

**Issue by Domain** [xmake-io/xmake#2559]
### Xmake 版本

2.6.8

### 操作系统版本和架构

Windows 11

### 描述问题

分布式编译，远程缓存，服务器报错：
<pre>
send cached object file C:\Users\build\AppData\Local\.xmake\service\server\distcc_build\sessons\e152b859\cache\1f\1f51d85c762e4ba009761d8100f8465b.o ..
...\modules\private\service\distcc_build\server_session.lua:162: send C:\Users\build\AppData\Local\.xmake\service\server\distcc_build\sessons\e152b859\cache\1f\1f51d85c762e4ba009761d8100f8465b.o failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:872]:
    [...\modules\private\service\distcc_build\server_session.lua:162]: in function 'compile'
    [@programdir\modules\private\service\distcc_build\server.lua:90]:

<distcc_build_server>: <socket: tcp4/1536.0>: <session e152b859>: send failed
<distcc_build_server>: <socket: tcp4/1536.0>: session end
</pre>

### 期待的结果

忽略错误，继续跑。
虽然现在加上了timeout设置，但是默认是-1，这对用户不够友好，先不说没有文档说明，每个用户安装好之后还要设置，这样就很麻烦。特别是现在远程编译和缓存还不够稳定的情况，很容易卡住流程。应该默认设置上timeout，让用户无感使用。

**Comment by waruqi** [comment]
> 虽然现在加上了timeout设置，但是默认是-1，这对用户不够友好，先不说没有文档说明，每个用户安装好之后还要设置，这样就很麻烦。特别是现在远程编译和缓存还不够稳定的情况，很容易卡住流程。应该默认设置上timeout，让用户无感使用。

无感了，出了问题，用户到最后都不知道 是否 distcc 真的生效了，特别是实现刚初步支持使其，用户尽早反馈问题 更便于改进。

暂时不会默认开启超时，自己配下。

**Comment by Domain** [comment]
又跑了一下，服务器没有重启，这次客户端用了-vD，有很多相同的报错：

<pre>
fallback to the local cache, @programdir\modules\private\service\remote_cache\client.lua:447: &lt;remote_cache_client&gt;: server unreachable!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:872]:
    [@programdir\modules\private\service\remote_cache\client.lua:447]: in function '_sock_open'
    [@programdir\modules\private\service\remote_cache\client.lua:182]: in function 'pull'
    [@programdir\modules\private\cache\build_cache.lua:158]:
</pre>

服务器完全没有任何反应，没有输出，而且CPU占用25%，没有cl进程，像是死循环一样

**Comment by Domain** [comment]
这就是当时所有日志，客户端还有一些正常的本地和distcc的日志，然后不动了，服务器没有任何反应，卡住了。
我试了在服务器用profile运行：
C:\>set XMAKE_PROFILE=stuck
C:\>xmake service -vD
然后直接卡住了，CPU>30%，屏幕没有任何输出，按Ctrl+c，弹出vsjitdebugger调试窗口，没有符号表，当然看不到什么东西，屏幕还是没有任何输出。去掉这个环境变量就可以正常启动

**Comment by waruqi** [comment]
没太多 logs 就不太好查了。



> 这就是当时所有日志，客户端还有一些正常的本地和distcc的日志，然后不动了，服务器没有任何反应，卡住了。 我试了在服务器用profile运行： C:>set XMAKE_PROFILE=stuck C:>xmake service -vD 然后直接卡住了，CPU>30%，屏幕没有任何输出，按Ctrl+c，弹出vsjitdebugger调试窗口，没有符号表，当然看不到什么东西，屏幕还是没有任何输出。去掉这个环境变量就可以正常启动

是看 客户端卡的位置，不是服务端。如果这种方式不行，就只能自己加点 print ，跟下具体卡哪里了。

**Comment by waruqi** [comment]
首次使用初始化配置的时候，目前 connect timeout 默认改成了 10s  另外最近修复了 远程缓存不生效问题 https://github.com/xmake-io/xmake/issues/4592 

以及远程缓存 session id 全局固定 https://github.com/xmake-io/xmake/discussions/4524
