### ISSUE TITLE
More flexible package fetching from cmake

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2576]
### 你在什么场景下需要该功能？

https://cmake.org/cmake/help/latest/guide/using-dependencies/index.html#guide:Using%20Dependencies%20Guide

希望xmake支持：
- Module/Config模式设置 `find_package(ABC CONFIG REQUIRED)` (仅从ABCConfig.cmake查找)
- Components设置 `find_package(Boost 1.79 COMPONENTS date_time)`
- 特定target设置 `target_link_libraries(test PRIVATE ABC::lib1 ABC::lib3)`

这里第3点很重要，因为package提供的cflags、cxxflags、defines、syslinks都是通过这种方式链接才有，只链接`ABC_LIBRARIES`不仅无法控制链接的库和顺序（可能导致冲突），还会丢失信息（可能导致编译不过）。

### 描述可能的解决方案

改进cmake/find_package模块

**Comment by waruqi** [comment]
> Components设置 find_package(Boost 1.79 COMPONENTS date_time)

这个不是原本就支持么

https://github.com/xmake-io/xmake/blob/30ceace35346e91a90381712bec746598658a089/xmake/modules/package/manager/cmake/find_package.lua#L42-L55

**Comment by waruqi** [comment]
> 特定target设置 target_link_libraries(test PRIVATE ABC::lib1 ABC::lib3)

这个怎么搞？要么传自定义 linktargets 进去，`add_requires("cmake::xxx", {configs = {linktargets = {"abc::lib1", "abc::lib2"}}})`

**Comment by xq114** [comment]
> > 特定target设置 target_link_libraries(test PRIVATE ABC::lib1 ABC::lib3)
> 
> 这个怎么搞？要么传自定义 targetlinks 进去，`add_requires("cmake::xxx", {configs = {targetlinks = {"abc::lib1", "abc::lib2"}}})`

targetlinks这个名字不是很贴切，改成link_libraries比较好，因为cmake里面的`target_link_libraries(test PRIVATE ABC::lib1 ABC::lib3)`是把 test 这个 target ”link“ 到 libraries ABC::lib1 和 ABC::lib3。{find_config = true}也不如{search_mode = "config"}好，后者可以设置"both" "config" "module"。见 https://cmake.org/cmake/help/latest/command/find_package.html#id4

**Comment by waruqi** [comment]
好了

```lua
add_requires("cmake::xxx", {configs = {link_libraries = {"abc::lib1", "abc::lib2"}}})
add_requires("cmake::xxx", {configs = {search_mode = "CONFIG"}}) -- MODULE, BOTH
```

**Comment by xq114** [comment]
不好意思我没讲清楚，both就是啥也不加，默认就两个都找，不需要额外声明，需要声明的只有config和module

**Comment by waruqi** [comment]
> 好了
> 
> ```lua
> add_requires("cmake::xxx", {configs = {link_libraries = {"abc::lib1", "abc::lib2"}}})
> add_requires("cmake::xxx", {configs = {search_mode = "config"}}) -- module, both
> ```

那就不设置就行了

```lua
add_requires("cmake::xxx", {configs = {search_mode = "config"}})
add_requires("cmake::xxx", {configs = {search_mode = "module"}})
add_requires("cmake::xxx") -- both

```
