### ISSUE TITLE
Support Ubuntu 22.04 Jammy Jellyfish PPA

### ISSUE THREAD

**Issue by Immortalin** [xmake-io/xmake#2579]
### Xmake Version

2.6.9

### Operating System Version and Architecture

Ubuntu 22.04 Jammy Jellyfish

### Describe Bug

Current provided PPA does not support support Jammy Jellyfish, Ubuntu 22.04 is the latest LTS version.

### Expected Behavior

A PPA for Jammy Jellfish is available

**Comment by waruqi** [comment]
I have supported it.
