### ISSUE TITLE
Set stdout to line buffering

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#2580]
### Is your feature request related to a problem? Please describe.

When running xmake on GitHub actions on Linux and macOS, you have to wait a few minutes to see the log.
![image](https://user-images.githubusercontent.com/3002461/179496334-f8f04f28-d118-405a-b5e6-c3f466dc6b16.png)

This is because on Linux/macOS stdout is fully buffered on Github by default.

### Describe the solution you'd like

XMake could enable line buffering using `setvbuf(stdout, NULL, _IONBF, 0);` to flush on line feed.

### Describe alternatives you've considered

I'm not sure if it can be done outside of xmake.

**Comment by waruqi** [comment]
I think it should be possible to control the stdout buffer size by creating a child process, like `python -u`.

**Comment by waruqi** [comment]
You can try this patch, but I'm not sure if it works. https://github.com/xmake-io/xmake/pull/2605

**Comment by SirLynix** [comment]
Unfortunately it doesn't work, same behavior as before (tested on Linux CI).

Isn't there some code missing there, since it tests for `XMAKE_STDOUT_NBUF` env? Or should I set it myself from CI?

**Comment by waruqi** [comment]
I improved it, try it again.

export XMAKE_STDOUT_NBUF=0

**Comment by SirLynix** [comment]
It seems to work, every line gets printed on Github CI directly.

However, this seems to disable completely stdout buffer, which could be problematic with verbose output. Couldn't we use `_IOLBF` (line buffering) by default? (it's a [standard value](https://en.cppreference.com/w/c/io/setvbuf)).

```c
setvbuf(stdout, tb_null, _IOLBF, BUFSIZ);
```

This is standard and can be used on Windows as well.

On Posix we can get a better value than BUFSIZE using
```c
    struct stat stats;
    int fileno(FILE*);
    if(fstat(fileno(fp), &stats) == -1) { // POSIX only
        perror("fstat"); return EXIT_FAILURE;
    }
 
    printf("BUFSIZ is %d, but optimal block size is %ld\n", BUFSIZ, stats.st_blksize);
    if(setvbuf(fp, NULL, _IOFBF, stats.st_blksize) != 0) {
       perror("setvbuf failed"); // POSIX version sets errno
       return EXIT_FAILURE;
    }
```

**Comment by waruqi** [comment]
>     if(setvbuf(fp, NULL, _IOFBF, stats.st_blksize) != 0) {

? _IOFBF?

**Comment by SirLynix** [comment]
My mistake, I copy-pasted the code from the documentation. Should be _IOLBF for line-feed buffering

**Comment by waruqi** [comment]
try it again. `export XMAKE_STDOUT_LINEFLUSH=y`

**Comment by waruqi** [comment]
> This is standard and can be used on Windows as well.

xmake do not use fwrite(stdout) on windows. It can be a little complicated to process. There is also an encoding conversion before writing to stdout, and a separate stream buffer

**Comment by SirLynix** [comment]
It works great. What would be the issue of enabling this by default?

> > This is standard and can be used on Windows as well.
> 
> xmake do not use fwrite(stdout) on windows. It can be a little complicated to process. There is also an encoding conversion before writing to stdout, and a separate stream buffer

Okay, it's not an issue on Windows CI anyway.

**Comment by waruqi** [comment]
I'm not sure if it has an impact on build performance or if there are any other side effects. For the time being it is better to control it through environment variables.

**Comment by SirLynix** [comment]
This is already the default behavior on most OS, and for instance this is done by Ninja as well:
https://github.com/ninja-build/ninja/blob/master/src/ninja.cc#L1518

**Comment by waruqi** [comment]
ok, I have enabled by default.

**Comment by SirLynix** [comment]
Thanks!
