### ISSUE TITLE
add_files不能添加.a静态库文件

### ISSUE THREAD

**Issue by as564335sa** [xmake-io/xmake#2583]
### Xmake 版本

2.6.4

### 操作系统版本和架构

windows

### 描述问题

大佬，我看教程文档里说`add_files`可以直接添加.a静态库文件，我试了下编译会提示符号未定义`Undefined symbol`错误；需要用`add_links`和`add_linkdirs`添加才行，什么问题？工程是armcc的cortex-m3

### 期待的结果

-

**Comment by waruqi** [comment]
armar 还不支持
