### ISSUE TITLE
已有项目删除.xmake目录后，重新编译时如果无法访问github, 导致项目后续编译失败

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#2584]
### Xmake 版本

2.6.9

### 操作系统版本和架构

Ubuntu20.04

### 描述问题

xmake 编译时，会自动更新 xmake_repo , 但更新失败时，会导致项目无法编译。
比如项目之前已经编译成功（包括其依赖的软件包），这时候手工把项目下的 .xmake 删除，重新进行编译，而刚好无法获取 github，这时项目即使开始编译也往往由于配置不对最终会编译失败。

### 期待的结果

建议此种情况下，应该不影响已有项目的编译

### 工程配置

![图片](https://user-images.githubusercontent.com/1145161/179934696-5a6ace6b-71ed-4ffc-b023-2c3f46fba5b2.png)

**Comment by waruqi** [comment]
不要去删，用 `xmake f -c`

**Comment by fasiondog** [comment]
> 不要去删 .xmake，用 `xmake f -c`

可是有的时候，我需要删除 .xmake，跨平台编译或者内部的repo更新需要立刻试验，这个时候删掉.xmake比较快捷不容易出错

**Comment by waruqi** [comment]
其实 xmake f -c 更不容易出错，效果一样的，另外仓库问题，你可以删 ~/.xmake/repositories 重拉下

**Comment by fasiondog** [comment]
> 你可以删 ~/.xmake/repositories 重拉下

这种情况，主要就是 repositories  重拉不了，导致后续都没法编译了

**Comment by fasiondog** [comment]
还有就是，如果使用内部仓库，但因为github的公共仓库没法重拉更新，也会导致内部项目第一次编译就会失败

**Comment by waruqi** [comment]
可以设置代理，或者 repo 切到 gitee 上去拉

https://xmake.io/#/zh-cn/guide/configuration?id=xmake_main_repo

https://xmake.io/#/zh-cn/guide/configuration?id=xmake_binary_repo

**Comment by fasiondog** [comment]
> 

哦，好的，有学到一点，谢谢
