### ISSUE TITLE
Add the target directory to PATH in virtual environment

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2599]
### 你在什么场景下需要该功能？

用xmake生成二进制与动态库给其他程序用时调试起来很困难，每次启动开发环境都需要手动设置PATH指向该项目生成的二进制与动态库位置（不想污染全局环境变量）。当前虚拟环境内并未加入target目录，设置一个phony package然后加PATH的方法也不太好使，因为target目录是随设置变化的。

### 描述可能的解决方案

希望运行`xrepo env shell`时可以将target directory加入PATH（如果有target的话），内置的那种仅有add_requires的environment不用加

**Comment by waruqi** [comment]
加上了
