### ISSUE TITLE
xmake watch improve

### ISSUE THREAD

**Issue by OuYangPaste** [xmake-io/xmake#2607]
### 你在什么场景下需要该功能？

刚才玩了下 最新 dev 的 watch，默认参数下非常好用
手动指定监听文件 xmake watch -d 在一般情况下也很方便，但是不够灵活，甚至于想复刻默认 xmake watch 的功能，都无法做到（想监听 xmake.lua 但是似乎只能 xmake watch -d . 但是这样会把 .xmake build 都加进去，xmake watch -d '\*|build|.\*' 就无法监听 xmake.lua ）
1. 这种情况下如果有相对应的 watch files 命令，就比较灵活了（可能和 watch dir 有冲突)
2. xmake -s 可以指定执行相对应的 xmake lua 脚本，如果能够传入变动的文件列表到脚本内，就可以做很多其他更方便的操作了，这也是我之前用 [entr](https://github.com/eradman/entr) 一直想做但做不到的事情

### 描述可能的解决方案

1. watch files 命令相较于 watch dir 应该只有 os.dirs 和 os.files 的差异
2. 传入文件列表的话可以类似于我下面的改动：
![image](https://user-images.githubusercontent.com/38561133/181224516-a693c9c7-5177-45fb-864f-8fe397de2bf5.png)
记录相应的 event files 然后级层传递到脚本中（当然可能会有传相对路径还是绝对路径的考量）

**Comment by waruqi** [comment]
> 记录相应的 event files 然后级层传递到脚本中（当然可能会有传相对路径还是绝对路径的考量）

我直接传了 events list 进去，再试试

**Comment by waruqi** [comment]
> 这种情况下如果有相对应的 watch files 命令，就比较灵活了

files 的暂时搞不了，目前有些平台不支持 files 监听，只能监听目录，处理起来比较蛋疼，要对上层目录监听后再去过滤文件，懒得搞了。

我加了个 `-p/--plaindirs` 参数，非递归监听目录，基本可以复刻默认工程监听：

```
xmake watch -d "*|build|.*" -p .
```

**Comment by OuYangPaste** [comment]
> files 的暂时搞不了，目前有些平台不支持 files 监听，只能监听目录，处理起来比较蛋疼，要对上层目录监听后再去过滤文件，懒得搞了。

原来如此

> 我加了个 `-p/--plaindirs` 参数，非递归监听目录，基本可以复刻默认工程监听：

测试过没有问题

> 我直接传了 events list 进去，再试试
不知道为什么 linux 下每按一下 ctrl + s 会有两个一样事件触发
![image](https://user-images.githubusercontent.com/38561133/181405266-548dc280-b2d1-44ba-b481-229339140a10.png)

一直按着 ctrl + s 的时候会有多个一样的事件一直触发并缓存，enents list 传进去会有很多重复事件
![image](https://user-images.githubusercontent.com/38561133/181405570-9e8194dc-ef96-4dd8-87bc-88ef38ce2b14.png)

**Comment by waruqi** [comment]
正常，目前没做去重，依赖平台实现，有的平台会重复触发的，有的平台内部做了延时自动去重过滤，敏感度不同。

自己外面去重过滤下就行了。。

**Comment by OuYangPaste** [comment]
嗯👌

**Comment by waruqi** [comment]
我去重了 dev
