### ISSUE TITLE
xmake使用默认编译出错提示找不到-lstdc++

### ISSUE THREAD

**Issue by guangjieMVP** [xmake-io/xmake#2609]
### Xmake Version

xmake v2.6.5+202204250217

### Operating System Version and Architecture

ubuntu18.04 x86

### Describe Bug

xmake没有过多设置，编译在链接的时候失败，提示找不到-lstdc++。但是直接使用gcc xxx.c -o xxx这样编译是没有错误的

### Expected Behavior

不设置编译工具的时候应该使用系统默认的编译工具来编译吧

### Project Configuration

`add_rules("mode.debug", "mode.release")
target("AutoPID")           -- 设置目标程序名字
    set_kind("binary")   -- 设置编译成二进制程序，不设置默认编译成二进制程序，可选择编译成动静态库等
    --add_includedirs("/usr/local/include")   -- 设置头文件目录
    set_plat("linux")    -- 设置平台
    set_arch("x86")      -- 设置架构
--    set_languages("c99", "c++11")
    add_links("stdc++")
--    add_linkdirs("/usr/lib/", "/usr/lib/gcc/x86_64-linux-gnu/7/")   -- 设置链接库搜索路径
--    add_linkdirs("/usr/local/tslib/lib/")   -- 设置链接库搜索路径

    add_files("./*.c")  -- 设置C文件搜索目录
    -- 设置头文件搜索路径
    -- 设置C编译选项
--    add_cflags("-O3 -g0")`

### Additional Information and Error Logs

[ 25%]: compiling.release constrain.c
[ 50%]: linking.release AutoPID
error: /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.a when searching for -lstdc++
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.a when searching for -lstdc++
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status

**Comment by waruqi** [comment]
> add_links("stdc++")


删了

**Comment by guangjieMVP** [comment]
这是我后来加上，刚开始是没有加的，编译也出错，也是提示找不到这个我才加的，删了之后编译时这样：
[ 60%]: linking.release AutoPID
error: /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.a when searching for -lstdc++
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status

**Comment by waruqi** [comment]
> set_arch("x86") -- 设置架构

删了

**Comment by guangjieMVP** [comment]
ok,蟹蟹
