### ISSUE TITLE
删除build文件夹后出现编译报错:updating repositories .. error: fatal: repository 'build' does not exist

### ISSUE THREAD

**Issue by suihanhbr** [xmake-io/xmake#2621]
### Xmake 版本

2.6.9

### 操作系统版本和架构

macOS 12.3.1

### 描述问题

我删除build文件夹后编译出错，但此前我多次删除build文件夹后都是可以正常编译的，这次是突然不行了，我从废纸桶中恢复build文件夹中的内容后可以继续编译，但是再次删除的话还是会出错；

### 期待的结果

删除build文件夹后，xmake应该能重新生成build文件夹，并正常编译

### 工程配置

```
set_xmakever("2.6.9")
set_warnings("all", "error")
set_languages("c99", "cxx11")
add_cxflags("-Wno-error=deprecated-declarations", "-fno-strict-aliasing")
add_mxflags("-Wno-error=deprecated-declarations", "-fno-strict-aliasing")

add_rules("mode.release", "mode.debug")
add_repositories("local-repo build")
add_requires("tbox")

if is_plat("windows") then
    if is_mode("release") then
        add_cxflags("-MT")
    elseif is_mode("debug") then
        add_cxflags("-MTd")
    end
    add_ldflags("-nodefaultlib:msvcrt.lib")
end

 if is_plat("android") then 
    add_defines("SH_ANDROID")
elseif is_plat("iphoneos") then 
    add_defines("SH_IOS")
elseif is_plat("macosx") then
    add_defines("SH_MAC")
end


includes("src")
includes("sub1")


--
-- If you want to known more usage about xmake, please see https://xmake.io
--
-- ## FAQ
--
-- You can enter the project directory firstly before building project.
--
--   $ cd projectdir
--
-- 1. How to build project?
--
--   $ xmake
--
-- 2. How to configure project?
--
--   $ xmake f -p [macosx|linux|iphoneos ..] -a [x86_64|i386|arm64 ..] -m [debug|release]
--
-- 3. Where is the build output directory?
--
--   The default output directory is `./build` and you can configure the output directory.
--
--   $ xmake f -o outputdir
--   $ xmake
--
-- 4. How to run and debug target after building project?
--
--   $ xmake run [targetname]
--   $ xmake run -d [targetname]
--
-- 5. How to install target to the system directory or other output directory?
--
--   $ xmake install
--   $ xmake install -o installdir
--
-- 6. Add some frequently-used compilation flags in xmake.lua
--
-- @code
--    -- add debug and release modes
--    add_rules("mode.debug", "mode.release")
--
--    -- add macro defination
--    add_defines("NDEBUG", "_GNU_SOURCE=1")
--
--    -- set warning all as error
--    set_warnings("all", "error")
--
--    -- set language: c99, c++11
--    set_languages("c99", "c++11")
--
--    -- set optimization: none, faster, fastest, smallest
--    set_optimize("fastest")
--
--    -- add include search directories
--    add_includedirs("/usr/include", "/usr/local/include")
--
--    -- add link libraries and search directories
--    add_links("tbox")
--    add_linkdirs("/usr/local/lib", "/usr/lib")
--
--    -- add system link libraries
--    add_syslinks("z", "pthread")
--
--    -- add compilation and link flags
--    add_cxflags("-stdnolib", "-fno-strict-aliasing")
--    add_ldflags("-L/usr/local/lib", "-lpthread", {force = true})
--
-- @endcode
--


```

### 附加信息和错误日志

checking for Xcode directory ... /Applications/Xcode.app
checking for Codesign Identity of Xcode ... Apple Distribution: Kaijie Huang (BNQ9VWCZ9F)
checking for SDK version of Xcode for macosx (x86_64) ... 12.3
checking for Minimal target version of Xcode for macosx (x86_64) ... 12.3
checkinfo: cannot runv(dmd --version), No such file or directory
checking for dmd ... no
checkinfo: cannot runv(ldc2 --version), No such file or directory
checking for ldc2 ... no
checkinfo: cannot runv(gdc --version), No such file or directory
checking for gdc ... no
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
/usr/bin/git rev-parse HEAD
finding sub1 from xmake ..
checking for xmake::sub1 ... no
finding sub1 from brew ..
checking for brew ... /usr/local/bin/brew
finding sub1 from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding sub1 from conan ..
finding sub1 from pkgconfig ..
checking for pkg-config ... /usr/local/bin/pkg-config
finding sub1 from system ..
checking for sub1 ... no
finding tbox from xmake ..
checking for xmake::tbox ... tbox v1.6.9
note: the following packages were not found in any repository (check if they are spelled correctly):
  -> sub1
error: @programdir/core/main.lua:280: @programdir/core/sandbox/modules/import/core/base/task.lua:65: stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:883]:
    [...modules/private/action/require/impl/install_packages.lua:739]:
    [@programdir/modules/private/action/require/install.lua:85]:
    [@programdir/actions/config/main.lua:420]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/core/base/task.lua:501]: in function 'run'
    [@programdir/core/sandbox/modules/import/core/base/task.lua:63]: in function 'run'
    [@programdir/actions/build/main.lua:134]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/core/base/task.lua:501]: in function 'run'
    [@programdir/core/main.lua:278]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:388]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:872: in function 'base/os.raiselevel'
	(...tail calls...)
	@programdir/core/main.lua:280: in upvalue 'cotask'
	@programdir/core/base/scheduler.lua:388: in function <@programdir/core/base/scheduler.lua:385>

**Comment by suihanhbr** [comment]
[](http://image.suihanime.com/tboxtest.zip)

这是报错的项目，我尝试过删除.xmake文件夹、重启电脑都无法解决问题；

**Comment by waruqi** [comment]
> add_repositories("local-repo build")

你把 build 目录作为本地仓库，又去把它删了，这是要搞啥，删了当然无法拉取仓库了

**Comment by suihanhbr** [comment]
> > add_repositories("local-repo build")
> 
> 你把 build 目录作为本地仓库，又去把它删了，这是要搞啥，删了当然无法拉取仓库了

 #原来如此，我是xmake的初学者，还在学习中。我之所以要删除build文件夹，是因为tboxtest和sub1里的代码同步有问题，感觉应该和这个issue  #2620有关，不确定是不是bug

**Comment by waruqi** [comment]
你可以看下文档：https://xmake.io/#/zh-cn/manual/global_interfaces?id=add_repositories

后面设置实际的本地仓库路径
