### ISSUE TITLE
package:config("vs_runtime") is nil

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2625]
### Xmake 版本

2.6.9

### 操作系统版本和架构

Windows 10 v1909

### 描述问题

不加设置的时候package:config("vs_runtime")取不到值
```
error: @programdir\modules\package\tools\cmake.lua:300: attempt to concatenate a nil value (local 'vs_runtime')
stack traceback:
    [@programdir\modules\package\tools\cmake.lua:300]: in function '_get_configs_for_windows'
    [@programdir\modules\package\tools\cmake.lua:577]: in function '_get_configs'
    [@programdir\modules\package\tools\cmake.lua:845]: in function 'install'
    [...rs\xq114\Projects\xmake-repo\packages\c\catch2\xmake.lua:37]: in function 'script'
    [...dir\modules\private\action\require\impl\utils\filter.lua:125]: in function 'call'
    [...\modules\private\action\require\impl\actions\install.lua:298]:
```
这导致package.tools.cmake无法设置正常的vs_runtime，见 https://github.com/xmake-io/xmake-repo/runs/7599192739?check_suite_focus=true

### 期待的结果

package:config("vs_runtime")可以取到默认值，或者修改所有使用package:config("vs_runtime")的地方处理nil情形

**Comment by waruqi** [comment]
原本就会默认设置到 MT，如果不设置的话。。除非这是个 headeronly 包

https://github.com/xmake-io/xmake/blob/e45d9400697a256c4873237329c45374c8c869ce/xmake/modules/private/action/require/impl/package.lua#L488-L494

catch2 本来是 headeronly，现在改成库构建了，catch2 要去掉 headeronly

**Comment by xq114** [comment]
明白了，已改
