### ISSUE TITLE
Let find_tool find binaries from `add_requires`

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2629]
### 你在什么场景下需要该功能？

例如如下程序
```
add_requires("python 3.x")
target("example")
    add_rules("python.library", {soabi=true})
    add_files("src/*.cpp")
    add_packages("python 3.x")
```
如果系统上未安装python，则此程序无法通过`xmake f` （rule `python.library` 调用了find_tool去查找python），从xrepo下载的python就没有意义了（即使使用xrepo env shell也无法进入虚拟环境，过不了`xmake f`这一关）

### 描述可能的解决方案

希望xmake在项目内调用find_tool时可以找到项目依赖的xrepo中的文件，例如python、swig等

**Comment by waruqi** [comment]
这个 rule 是在 on_load 里面处理的，目前仅仅 xx_build_xx 系列 scripts 会绑定包环境，我刚改了下 on_config 也支持包环境绑定，切到 on_config 上去了。。

on_load 目前支持不了绑定
