### ISSUE TITLE
执行xmake不执行当前目录下的xmake.lua，而去从当前目录执行拷贝到其他目录的xmake.lua

### ISSUE THREAD

**Issue by guangjieMVP** [xmake-io/xmake#2633]
### Xmake Version

xmake v2.6.5+202204250217

### Operating System Version and Architecture

ubuntu18.04 x86

### Describe Bug

执行xmake不执行当前目录下的xmake.lua，而去从当前目录执行拷贝到其他目录的xmake.lua

当前目录存在xmake
ares@ubuntu:~/work/PrjStellar/lv_port_linux_frame_buffer$ ls
build    lv_conf.h   lv_drv_conf.h  lv_ex_conf.h  main.c    README.md
LICENSE  lv_drivers  lv_examples    lvgl          Makefile  xmake.lua
执行xmake跑去执行了这个目录下的xmake了
ares@ubuntu:~/work$ ls xmake.lua 
xmake.lua
这问题是咋回事？

### Expected Behavior

.

### Project Configuration

`--add_rules("mode.debug", "mode.release")
target("lvgl")           -- 设置目标程序名字
    set_kind("binary")   -- 设置编译成二进制程序，不设置默认编译成二进制程序，可选择编译成动静态库等
--    add_includedirs("/usr/local/include")   -- 设置头文件目录
--    add_linkdirs("/usr/local/lib")
--    add_syslinks("pthread")
--    add_linksset_plat("linux")    -- 设置平台
--    set_arch("imx6ull")  -- 设置架构
--    set_languages("c99", "c++11")
--    add_links("m", "ts")   -- 设置链接库
--    add_linkdirs("/usr/local/tslib/lib/")   -- 设置链接库搜索路径

    add_files("./*.c")  -- 设置C文件搜索目录
    add_files("lvgl/src/lv_core/*.c", "lvgl/src/lv_draw/*.c", "lvgl/src/lv_font/*.c")  -- 设置C文件搜索目录
    add_files("lvgl/src/lv_gpu/*.c", "lvgl/src/lv_hal/*.c", "lvgl/src/lv_misc/*.c")
    add_files("lvgl/src/lv_themes/*.c", "lvgl/src/lv_widgets/*.c")
    add_files("lv_lib_png/*.c")
    add_files("lv_drivers/*.c", "lv_drivers/display/*.c", "lv_drivers/indev/*.c")
    add_files("lv_app/*.c", "lv_app/font/*.c", "lv_app/img/*.c", "lv_app/weather_client/*.c", "lv_app/img/weather_app/*.c")
    add_files("lv_examples/src/lv_demo_widgets/*.c")
    -- 设置头文件搜索路径
    add_includedirs(".", "/usr/local/tslib/include/")  
    add_includedirs("lv_app/weather_client")
    add_includedirs("lvgl", "lvgl/lv_drivers", "lvgl/lv_lib_png", "lvgl/lv_drivers", "lvgl/lv_drivers/indev", "lvgl/lv_drivers/display") 
    add_includedirs('lv_examples/src/lv_demo_widgets/')
    -- 设置C编译选项
    add_cflags("-O3 -g0 -Wall -Wshadow -Wundef -Wmaybe-uninitialized -Wmissing-prototypes -Wno-discarded-qualifiers -Wall -Wextra -Wno-unused-function -Wundef -Wno-error=strict-prototypes -Wpointer-arith -fno-strict-aliasing -Wno-error=cpp -Wuninitialized -Wmaybe-uninitialized -Wno-unused-parameter -Wno-missing-field-initializers -Wtype-limits -Wsizeof-pointer-memaccess -Wno-format-nonliteral -Wno-cast-qual -Wunreachable-code -Wno-switch-default -Wno-switch-enum -Wreturn-type -Wmultichar -Wformat-security -Wno-ignored-qualifiers -Wno-error=pedantic -Wno-sign-compare -Wno-error=missing-prototypes -Wdouble-promotion -Wclobbered -Wdeprecated -Wempty-body -Wtype-limits -Wshift-negative-value -Wstack-usage=1024 -Wno-unused-value -Wno-unused-parameter -Wno-missing-field-initializers -Wuninitialized -Wmaybe-uninitialized -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wtype-limits -Wsizeof-pointer-memaccess -Wno-format-nonliteral -Wpointer-arith -Wno-cast-qual -Wmissing-prototypes -Wunreachable-code -Wno-switch-default -Wswitch-enum -Wreturn-type -Wmultichar -Wno-discarded-qualifiers -Wformat-security -Wno-ignored-qualifiers -Wno-sign-compare")
`

### Additional Information and Error Logs

res@ubuntu:~/work/PrjStellar/lv_port_linux_frame_buffer$ xmake
[ 66%]: linking.release stellar
error: build/.objs/stellar/linux/x86_64/release/fifo_test.c.o: In function `main':
fifo_test.c:(.text.startup+0x0): multiple definition of `main'
build/.objs/stellar/linux/x86_64/release/mplayer_test.c.o:mplayer_test.c:(.text.startup+0x0): first defined here
collect2: error: ld returned 1 exit status

[xmake_log.txt](https://github.com/xmake-io/xmake/files/9231592/xmake_log.txt)

**Comment by waruqi** [comment]
> warning: You are working in the project directory(/home/ares/work) and you can also
force to build in current directory via run `xmake -P .`
warning: add -v for getting more warnings ..


提示不是很明显么，要么 `xmake -P .` 要么删了 `/home/ares/work/xmake.lua`

**Comment by guangjieMVP** [comment]
sorry，看到英文懵逼，没认真看提示
