### ISSUE TITLE
Not being able to use OpenMP

### ISSUE THREAD

**Issue by Daniel-Boll** [xmake-io/xmake#2634]
### Xmake Version

2.6.9

### Operating System Version and Architecture

Linux artix 5.18.14-artix1-1 x86_64 GNU/Linux

### Describe Bug

Testing with the simple example [loop](https://github.com/xmake-io/xmake/tree/dev/tests/projects/openmp/loop) using `gcc` seems to work fine.

```
openmp_test via 🌙 v5.4.4
❯ g++ src/main.cpp -fopenmp; ./a.out
hello(4): i = 6
hello(1): i = 2
hello(1): i = 3
hello(0): i = 0
hello(0): i = 1
hello(7): i = 9
hello(2): i = 4
hello(6): i = 8
hello(3): i = 5
hello(5): i = 7
```

Yet still with xmake the result is not the same.

```
openmp via 🌙 v5.4.4
❯ xmake && xmake run
[100%]: build ok!
hello(0): i = 0
hello(0): i = 1
hello(0): i = 2
hello(0): i = 3
hello(0): i = 4
hello(0): i = 5
hello(0): i = 6
hello(0): i = 7
hello(0): i = 8
hello(0): i = 9
```

### Expected Behavior

To work similarly as the gcc.

### Project Configuration

```lua
add_requires("openmp")
target("loop")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("openmp")
```

### Additional Information and Error Logs

```
openmp via 🌙 v5.4.4
❯ xmake -vD

build cache stats:
cache directory: build/.build_cache
cache hit rate: 0%
cache hit: 0
cache miss: 0
new cached files: 0
remote cache hit: 0
remote new cached files: 0
preprocess failed: 0
compile fallback count: 0

[100%]: build ok!
```

**Comment by waruqi** [comment]
try dev. https://github.com/xmake-io/xmake/issues/2603

xmake update dev

**Comment by Daniel-Boll** [comment]
Thank you, this alongside with 
```lua
set_policy("preprocessor.gcc.directives_only", false)
```

did the job. Once again thank you for the fast replies, and sorry for the duplicate.
