### ISSUE TITLE
add_deps不能传递编译模式

### ISSUE THREAD

**Issue by touseit** [xmake-io/xmake#2635]
### Xmake 版本

2.6.9

### 操作系统版本和架构

Windows 10  17134.1792

### 描述问题

比如，我编译a，b，c三个动态库，其中a依赖b，b依赖c。当我编译一个可执行程序d的时候，我显示指定add_requires("a",{debug=true}),但是此时对b,c依赖确是release版本。
require(c):
      -> description: The c package
      -> version: latest
      -> repo: cbb ...
      -> deps:
      -> requires:
         -> plat: windows
         -> arch: x64
         -> configs:
            -> vs_runtime: MDd
            -> shared: true
            -> pic: true
            -> debug: false
      -> configs:
         -> shared: Build shared library. (default: true)
      -> configs (builtin):
         -> debug: Enable debug symbols. (default: false)
    require(b):
      -> description: The b package
      -> version: latest
      -> repo: cbb ...
      -> deps:
         -> c
      -> requires:
         -> plat: windows
         -> arch: x64
         -> configs:
            -> vs_runtime: MDd
            -> shared: true
            -> pic: true
            -> debug: false
      -> configs:
         -> shared: Build shared library. (default: true)
      -> configs (builtin):
         -> debug: Enable debug symbols. (default: false)
           ...
    require(a):
      -> description: The a package
      -> version: latest
      -> repo: cbb ...
      -> deps:
         -> b
         -> c
      -> requires:
         -> plat: windows
         -> arch: x64
         -> configs:
            -> vs_runtime: MDd
            -> shared: true
            -> pic: true
            -> debug: true
      -> configs:
         -> shared: Build shared library. (default: true)
      -> configs (builtin):
         -> debug: Enable debug symbols. (default: false)

### 期待的结果

我希望顶层a依赖的是什么编译模式，他后续依赖的模块也是对应的编译模式

**Comment by xq114** [comment]
add_requireconfs("a.*", {debug = true})

**Comment by touseit** [comment]
add_requireconfs这个选项也用过，但是不起作用，使用 xmake require --info还是看到配置用的是release版本。另外补充下，a,b,c三者之间的依赖关系用的add_deps，不是用的add_requires。

**Comment by waruqi** [comment]
add_requireconfs  就是用来修改 package 内部 add_deps 里面依赖包的默认配置的，你可以先看下文档

**Comment by waruqi** [comment]
```lua
add_requireconfs("a.*", {configs = {debug = true}})
```

**Comment by waruqi** [comment]
```lua
add_requireconfs("netbase.**", {configs = {debug = true}})
```

递归匹配下试试，不行就提供 -vD 的完整输出。

**Comment by touseit** [comment]
非常感谢大佬，最后可以了。需要补充下，add_requireconfs("netbase.**", {configs = {debug = true}})要和add_requires("netbase", {debug = true})一起使用才可以。否则每个依赖库还是release版本。

**Comment by touseit** [comment]
上面说的有点问题，应该是第一个会是release版本
