### ISSUE TITLE
wasm install doesn't copy all files

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#2645]
### Xmake Version

2.6.9

### Operating System Version and Architecture

Ubuntu 10

### Describe Bug

When running xmake install on a wasm project, only the .html file is copied, however emscripten generates more file:
https://emscripten.org/docs/tools_reference/emcc.html#emcc-o-target

### Expected Behavior

xmake should copy .js, .mjs and .wasm files to the bin folder if they exist.

**Comment by waruqi** [comment]
you can write a `platform.wasm` rule in https://github.com/xmake-io/xmake/tree/master/xmake/rules/platform

and add deps to c++ rules.
