### ISSUE TITLE
Use -gsource-map on wasm targets in debug

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#2646]
### Is your feature request related to a problem? Please describe.

When building wasm with symbols, `-gsource-map` should be added along with `-g` to be able to debug original file easily.

See https://emscripten.org/docs/tools_reference/emcc.html#emcc-gsource-map

### Describe the solution you'd like

Adding `-gsource-map` when `-g` is added and wasm is used.

### Describe alternatives you've considered

Adding it myself

**Comment by waruqi** [comment]
you can open a pr to add `nf_symbol` to handle debug symbols flags in https://github.com/xmake-io/xmake/blob/master/xmake/modules/core/tools/emcc.lua
