### ISSUE TITLE
Linking.Release Skipped When Building Previously Cached Files

### ISSUE THREAD

**Issue by jteppinette** [xmake-io/xmake#2655]
### Version

v2.6.9+202207181016

### Operating System Version and Architecture

macOS 12.4 M1

### Describe Bug

If you run `xmake build` on a file which has already been compiled, then the `linking.release` step is skipped. Therefore, the new binary is not created. This results in the previous binary being used during `xmake run`.

**main.cpp - v1**
```cpp
#include <iostream>

int main() {
  std::cout << 1 << std::endl;
}
```

**xmake.lua**
```lua
target("main")
    set_kind("binary")
    set_languages("cxx17")
    add_files("main.cpp")
```

**build - v1**
```sh
$ xmake; xmake run 
[ 25%]: ccache compiling.release main.cpp
[ 50%]: linking.release main
[100%]: build ok!
1
```

**main.cpp - v2**
```cpp
#include <iostream>

int main() {
  std::cout << 2 << std::endl;
}
```

**build - v2**
```sh
$ xmake; xmake run 
[ 25%]: ccache compiling.release main.cpp
[ 50%]: linking.release main
[100%]: build ok!
2
```

**main.cpp - v1**
```cpp
#include <iostream>

int main() {
  std::cout << 1 << std::endl;
}
```

**build - v1**
```sh
$ xmake; xmake run 
[ 25%]: ccache compiling.release main.cpp
[100%]: build ok!
2
```

Notice, above, the `linking.release` stage was skipped and the resulting binary wrote `2` instead of `1` to the console.

### Temporary Resolution

I was able to remediate this issue by disabling the build cache:

**xmake.lua**
```lua
set_policy("build.ccache", false)

target("main")
    set_kind("binary")
    set_languages("cxx17")
    add_files("main.cpp")
```

**Comment by jteppinette** [comment]
Upon exiting the GUI app forcefully (not with <ctrl-c> via the terminal), the recompilation functionality becomes broken until I delete the `.xmake` and `build` directory.

**Comment by waruqi** [comment]
? I don't understand what you mean.

**Comment by jteppinette** [comment]
@waruqi I have written about the issue in more detail after digging in a little more.

**Comment by waruqi** [comment]
I have fixed it in previous issue. https://github.com/xmake-io/xmake/issues/2620

please update to dev and try it again.

xmke update dev

**Comment by jteppinette** [comment]
Thanks!
