### ISSUE TITLE
feature: EmmyLua annotations 

### ISSUE THREAD

**Issue by xiyaowong** [xmake-io/xmake#2656]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

xmake is based on lua, so we can use lua extension for better completion experience. For more information, please see the below links

https://github.com/sumneko/lua-language-server/wiki/Annotations
https://github.com/sumneko/lua-language-server/wiki/Libraries

**Comment by waruqi** [comment]
?

**Comment by xiyaowong** [comment]
我的想法是，既然xmake是基于lua，所以我们可以提供类似typescript里的types.d.ts文件，然后结合lua插件获得更好的补全体验

**Comment by xiyaowong** [comment]
xmake的VSCode插件的补全仅仅是匹配单词，就只是提供关键词，功能有些薄弱。比如cmake有cmake-language-server，xmake是用lua，可以直接用现成的lua-language-server

**Comment by waruqi** [comment]
没空搞，可以提个 pr 过来。

**Comment by xiyaowong** [comment]
是的。写这玩意儿工作量是不小。但是不是特别熟悉xmake，又写不了。我也只是提供建议，希望有人愿意贡献。:heart:

**Comment by mochaaP** [comment]
我覺得，如果 xmake 在迭代的過城中可以逐步添加 type annotation 的話，不僅能提升用戶的易用性（編輯器內置文檔），也能提供一個良好的開發體驗，吸引更多 contributor。

短時間內會考慮這樣做嗎？:heart:

**Comment by hawkinchina** [comment]
呵， 看看需要做些什么工作？  这个提议非常好。 good pr。
