### ISSUE TITLE
无法访问build-artifacts.git

### ISSUE THREAD

**Issue by wujilingfeng** [xmake-io/xmake#2662]
### Xmake 版本

2.6.4

### 操作系统版本和架构

ubuntu20

### 描述问题

我在xmake添加了add_requires("cmake::PCL",{alias="pcl",system=true})， 
但是编译出现updating repositories .. error: fatal: 无法访问 'https://github.com/xmake-mirror/build-artifacts.git/'：gnutls_handshake() failed: Error in the pull function.

### 期待的结果

我期待能够搜索pcl库，并添加依赖。

**Comment by waruqi** [comment]
git 或者 网络问题
