### ISSUE TITLE
Precompiled header is included more than once despite `pragma once`

### ISSUE THREAD

**Issue by Qudix** [xmake-io/xmake#2667]
### Xmake Version

2.6.9

### Operating System Version and Architecture

Windows 11 (21H2)

### Describe Bug

During a build, the precompiled header file is included more than once. `pragma once` is supposed to prevent this, but under xmake this does not seem to be the case? Using a macro guard alongside `pragma once` I conducted a test:

If the header is only included once, it passes. If it gets included more than once, it will hit the `#error` macro.

One with ccache enabled:
![image](https://user-images.githubusercontent.com/17361645/183820674-725889e0-36ea-4c23-bed0-e2beb560a922.png)

One without ccache (just it case):
![image](https://user-images.githubusercontent.com/17361645/183820928-dd8062ee-0d5d-4f32-aad2-e6b9aa0ea747.png)

And cmake for comparison:
![image](https://user-images.githubusercontent.com/17361645/183820739-cd0e0aad-4338-4492-a776-459bcb55c4e9.png)

The result of this is that I end up with redefinition errors when trying to build in my project. 

### Expected Behavior

The precompiled header file should abide by `pragma once` and not be included more than once.

### Project Configuration

[Test.zip](https://github.com/xmake-io/xmake/files/9296894/Test.zip)

For xmake:
```
xmake
```
For cmake:
```cpp
cmake -S . -B build
cmake --build build
```

**Comment by waruqi** [comment]
try `xmake f --ccache=n; xmake`?

**Comment by Qudix** [comment]
I have a non-ccache run up above

**Comment by waruqi** [comment]
You can compare the difference in compile options with cmake.

**Comment by SirLynix** [comment]
Here's xmake flags:
```
lynix@SirDesktop:/mnt/c/Users/lynix/Downloads/Test (1)/Test$ xmake.exe -v
[  0%]: compiling.release include\PCH.h
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\cl.exe" -c -Yc /EHsc -nologo -Ox -fp:fast -Iinclude -FIPCH.h -DNDEBUG -TP -Fpbuild\.objs\test\windows\x64\release\include\PCH.h.pch -Fobuild\.objs\test\windows\x64\release\include\PCH.h.pch.obj include\PCH.h
error: PCH.h
C:\Users\lynix\Downloads\Test (1)\Test\include\PCH.h(6): fatal error C1189: #error:  "This shouldn't happen. Is `pragma once` being ignored?"
```

and cmake (msbuild) flags:
```
CustomBuild:
  Building Custom Rule C:/Users/lynix/Downloads/Test (1)/Test/CMakeLists.txt
ClCompile:
  C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\CL.exe /c /I"C:\
  Users\lynix\Downloads\Test (1)\Test\include" /Zi /nologo /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _
  WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /st
  d:c++20 /Yc"C:/Users/lynix/Downloads/Test (1)/Test/cmake/CMakeFiles/Test.dir/Debug/cmake_pch.hxx" /Fp"C:/Users/lynix/
  Downloads/Test (1)/Test/cmake/Test.dir/Debug/cmake_pch.pch" /Fo"Test.dir\Debug\\" /Fd"C:\Users\lynix\Downloads\Test (
  1)\Test\cmake\Debug\Test.pdb" /external:W1 /Gd /TP /FI"C:/Users/lynix/Downloads/Test (1)/Test/cmake/CMakeFiles/Test.d
  ir/Debug/cmake_pch.hxx" /errorReport:queue "C:\Users\lynix\Downloads\Test (1)\Test\cmake\CMakeFiles\Test.dir\cmake_pc
  h.cxx"
  cmake_pch.cxx
  C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\CL.exe /c /I"C:\
  Users\lynix\Downloads\Test (1)\Test\include" /Zi /nologo /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _
  WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /st
  d:c++20 /Yu"C:/Users/lynix/Downloads/Test (1)/Test/cmake/CMakeFiles/Test.dir/Debug/cmake_pch.hxx" /Fp"C:/Users/lynix/
  Downloads/Test (1)/Test/cmake/Test.dir/Debug/cmake_pch.pch" /Fo"Test.dir\Debug\\" /Fd"C:\Users\lynix\Downloads\Test (
  1)\Test\cmake\Debug\Test.pdb" /external:W1 /Gd /TP /FI"C:/Users/lynix/Downloads/Test (1)/Test/cmake/CMakeFiles/Test.d
  ir/Debug/cmake_pch.hxx" /errorReport:queue "C:\Users\lynix\Downloads\Test (1)\Test\src\Test.cpp"
  Test.cpp
```

With cmake_pch.hxx being this:
```
/* generated by CMake */

#pragma system_header
#ifdef __cplusplus
#include "C:/Users/lynix/Downloads/Test (1)/Test/include/PCH.h"
#endif // __cplusplus
```

**Comment by waruqi** [comment]
cmake will generate a header wrapper.   `pch_xxx.h`

```c
#pragma system_header
#ifdef __cplusplus
#include "PCH.h"
#endif // __cplusplus
```

You can add this wrapper to build it.

```lua
    set_pcxxheader("include/pch_xxx.h")
```

It works for xmake.

**Comment by Qudix** [comment]
That doesn't solve the root problem and the cmake is just for comparison sake, otherwise I would just use cake rather than xmake.

**Comment by waruqi** [comment]
please run `xmake update -s dev` and try it again

**Comment by Qudix** [comment]
Testing with the test case above and with another project, it seems to work with the dev branch
