### ISSUE TITLE
xmake arm-none-eabi编译出错提示 \AppData\Local\Temp\ccV84OJn.s:619: Error rror: registers may not be the same -- `strexb r0,r0,[r1]'

### ISSUE THREAD

**Issue by guangjieMVP** [xmake-io/xmake#2678]
### Xmake Version

xmake v2.6.9+HEAD.22ecc0156

### Operating System Version and Architecture

win10

### Describe Bug

编译出错如下错误：太奇怪了这个目录下也没这个文件
error: C:\Users\opto\AppData\Local\Temp\ccV84OJn.s: Assembler messages:
C:\Users\opto\AppData\Local\Temp\ccV84OJn.s:619: Error: registers may not be the same -- `strexb r0,r0,[r1]'
C:\Users\opto\AppData\Local\Temp\ccV84OJn.s:650: Error: registers may not be the same -- `strexh r0,r0,[r1]'

### Expected Behavior

.

### Project Configuration

`-- 设置工程名
set_project("stm32-xmake")

-- 设置工程版本
set_version("1.0.0")

add_rules("mode.debug", "mode.release")

-- 自定义工具链
toolchain("arm-none-eabi")
    -- 标记为独立工具链
    set_kind("standalone")
    -- 定义交叉编译工具链地址
    set_sdkdir("C:\\gcc-arm-none-eabi\\10 2021.10")
    --set_bindir("C:\\Program Files (x86)\\GNU Arm Embedded Toolchain\\10 2021.10\\bin")
toolchain_end()

target("LED_DRV.elf")
    -- 编译为二进制程序
    set_kind("binary") 
    -- 设置使用的交叉编译工具链
    set_toolchains("arm-none-eabi")  

    -- 设置平台
    set_plat("cross")
    -- 设置架构
    set_arch("m3")

    --set_filename("LED_DRV.elf")

    add_defines(
        "USE_STDPERIPH_DRIVER",  -- 使用标准库
        "STM32F10X_MD"  --  中容量
    )
    
    -- 添加链接库
    add_links("c", "m", "nosys", "rdimon");  -- 链接选项添加 ：-lc -lm -lnosys -lrdimon 
    
    -- 添加启动文件
    add_files("startup_stm32f10x_md.s");

    add_cflags(
        "-Og",
        "-mcpu=cortex-m3",
        "-mthumb",
        "-Wall",
        "-fdata-sections",
        "-ffunction-sections",
        "-g -gdwarf-2",
        {force = true}
    )

    add_asflags(
        "-Og",
        "-mcpu=cortex-m3",
        "-mthumb",
    --    "-x assembler-with-cpp",
        "-Wall",
        "-fdata-sections", 
        "-ffunction-sections",
        "-g -gdwarf-2",
        {force = true}
    )

    add_ldflags(
        "-Og",
        "-mcpu=cortex-m3",
        "-TSTM32F103C8Tx_FLASH.ld",  -- 不同芯片需要修改链接脚本
        "-Wl,--gc-sections",
        "-u _printf_float",  
        {force = true}
    )
    
    -- 源文件和头文件路径
    local src_path = {
        "USER/",
        "Common/",
        "./MqEvent/",
        "Lib/Fwlib",
        "Lib/Fwlib/src",
        "./Lib/CMSIS/",
        "USER/app/src",
        "USER/bsp/src"
    }
    -- 头文件路径
    local inc_path = {
        "./MqEvent/",
        "./Lib/CMSIS/",
        "Lib/Fwlib/inc",
        "Common/inc",
        "USER/app/inc",
        "USER/bsp/inc"
    }

    -- 排除的文件，不参与编译 模板文件可以直接删除
    remove_files("Common\\src\\meanFilter.c")
    remove_files("USER\\bsp\\src\\VirtualCOM.c")
    
    for _, dir in ipairs(src_path) do  -- 遍历 src_path
            add_files(dir.."/*.c"); 
    end

    -- 添加头文件路径
    for _, inc in ipairs(inc_path) do
        add_includedirs(inc);
    end
   
    if is_mode("debug") then 
        add_cflags("-g", "-gdwarf-2")
    end

    after_build(
        function(target)
        cprint("Compile finished!!!")
        cprint("Next, generate HEX and bin files.")
        os.exec("arm-none-eabi-objcopy -O ihex ./build/cross/m3/release/LED_DRV.elf ./build/LED_DRV.hex")
        os.exec("arm-none-eabi-objcopy -O binary ./build/cross/m3/release/LED_DRV.elf ./build/LED_DRV.bin")
        print("Generate hex and bin files ok!!!")

        print(" ");
        print("********************储存空间占用情况*****************************")
        os.exec("arm-none-eabi-size -Ax ./build/cross/m3/release/LED_DRV.elf")
        os.exec("arm-none-eabi-size -Bx ./build/cross/m3/release/LED_DRV.elf")
        os.exec("arm-none-eabi-size -Bd ./build/cross/m3/release/LED_DRV.elf")
        --print("heap-堆, stack-栈, .data-已初始化的变量全局/静态变量, .bss-未初始化的data, .text-代码和常量")
        --os.run("arm-none-eabi-objdump -D ./build/cross/m3/release/demo.elf > demo.s")
    end)`

### Additional Information and Error Logs

[xmake_log.txt](https://github.com/xmake-io/xmake/files/9349879/xmake_log.txt)

**Comment by waruqi** [comment]
估计是内联汇编报错，这种都是代码导致的编译问题，跟 xmake 没啥关系。自己排查下
