### ISSUE TITLE
Unity Build 和非 Unity 源码混编无法完全源码并行化

### ISSUE THREAD

**Issue by MaxwellGengYF** [xmake-io/xmake#2684]
### Xmake 版本

2.6.9

### 操作系统版本和架构

Windows 10

### 描述问题

无依赖项目编译无故串行化，有依赖的项目生成compile_commands.json中途中断生成，得到不完整的文件。

### 期待的结果

功能恢复到master branch稳定版本状态。

### 工程配置

[xmake_test.zip](https://github.com/xmake-io/xmake/files/9356731/xmake_test.zip)
xmake f -p windows -a x64 -m release

**Comment by waruqi** [comment]
> 有依赖的项目生成compile_commands.json中途中断生成，得到不完整的文件。

这个我刚更新改进了下，再试试呢，`xmake update -s dev`

**Comment by waruqi** [comment]
关于并行编译，你可以这里加个 print 调下看看，是否会进去，其他地方我暂时想不到会影响并行这块。。

https://github.com/xmake-io/xmake/blob/41c70cef65f4f82e718924ae934dd6323d5b60ad/xmake/rules/c%2B%2B/modules/xmake.lua#L37

**Comment by waruqi** [comment]
> > 有依赖的项目生成compile_commands.json中途中断生成，得到不完整的文件。
> 
> 这个我刚更新改进了下，再试试呢，`xmake update -s dev`

这个可以了么？

**Comment by waruqi** [comment]
可以了么 最近要发版了

**Comment by waruqi** [comment]
这里稍微备注下，unity build 和 非 unity 混合编译，部分源码编译会在链接后执行，没有完全源码并行化。

```
target("test")
    set_kind("binary")
    add_includedirs("src")
    add_rules("c++.unity_build", {batchsize = 2, uniqueid = "MY_UNITY_ID"})
    add_files("src/*.c", "src/*.cpp")
    add_files("src/foo/*.cpp", {unity_group = "foo"})
    add_files("src/bar/*.cpp", {unity_group = "bar"})

target("test2")
    set_kind("static")
    add_includedirs("src")
    add_files("src/main.cpp")
    add_defines("MY_UNITY_ID=xx")
```

```console
[ 52%]: ccache compiling.release src/main.cpp
[ 57%]: archiving.release libtest2.a
[ 57%]: ccache compiling.release src/test.c
[ 57%]: ccache compiling.release build/.gens/test/macosx/unity_build/unity_1.cpp
[ 57%]: ccache compiling.release src/main.cpp
[ 57%]: ccache compiling.release build/.gens/test/macosx/unity_build/unity_group_bar.cpp
[ 57%]: ccache compiling.release build/.gens/test/macosx/unity_build/unity_group_foo.cpp
[ 90%]: linking.release test
[100%]: build ok!
```

主要原因是为了改进 c++modules，对 rule 的 before_build 进行了 batch 支持，并且实现级联嵌套依赖，增加了层级依赖，导致叶子节点源码，unity 和 非 unity 不在同一层级上了。

如果全部都是 unity 或者不是 unity 就不会出现这个问题。

**Comment by waruqi** [comment]
我在这里 revert 了相关修改，并且 c++ modules 中相关地方换了一种方案去实现，应该就没这个问题了。。https://github.com/xmake-io/xmake/pull/2726

**Comment by waruqi** [comment]
应该可以了，再试试
