### ISSUE TITLE
Support for incremental compilation and parse header file deps for keil/armcc

### ISSUE THREAD

**Issue by as564335sa** [xmake-io/xmake#2686]
### Xmake 版本

2.6.9

### 操作系统版本和架构

windows

### 描述问题

今天突然发现，armcc编译器在修改了一个头文件后，重新编译，包含这个头文件的.C文件不会被重新编译，之前并没有注意过这种情况，不知道与版本有没有关系，gcc似乎没有这种情况？

### 期待的结果

无

**Comment by waruqi** [comment]
正常，目前就 gcc/clang/msvc 支持头文件依赖解析和增量编译。。冷门编译器暂时没时间搞，你可以提个 pr 过来支持上

**Comment by as564335sa** [comment]
好吧，看了下，看不懂这部分东西

**Comment by waruqi** [comment]
先得确认下 armcc 有没有类似 gcc 里面的 -MM/-MMD flags 可以生成头文件依赖关系的。。

然后参考下这部分代码。

https://github.com/xmake-io/xmake/blob/3c54402ff5d8c8cb2e085a09cd1fc4c10297817e/xmake/modules/core/tools/gcc.lua#L626

**Comment by as564335sa** [comment]
> 先得确认下 armcc 有没有类似 gcc 里面的 -MM/-MMD flags 可以生成头文件依赖关系的。。
> 
> 然后参考下这部分代码。
> 
> https://github.com/xmake-io/xmake/blob/3c54402ff5d8c8cb2e085a09cd1fc4c10297817e/xmake/modules/core/tools/gcc.lua#L626

我看了下，armcc对应的选项是--depend，在keil里能找到类似的选项`--depend *.d`；
我参照gcc.lua添加了一下这个选项，能编译通过，也生成了tmpfile，但是还是没有效果，对xmake的流程不了解，不知道怎么高了；

armclang在keil里的选项是-MD，搜了下资料支持下面这些；
```
-M, -MM         生成适合 make 实用程序使用的 makefile 依赖规则列表。        编译和组装。
-MD, -MMD         编译或汇编源文件并生成适合 make 实用程序使用的 makefile 依赖规则列表。        编译和组装。
-MF         为 -M 和 -MD 选项生成的 makefile 依赖规则指定文件名。        仅编译

**Comment by waruqi** [comment]
armcc.lua/armclang.lua 里面添加 flags 生成 deps 然后 depend.lua 里面去解析它。

https://github.com/xmake-io/xmake/blob/e6c8d8c5c8bed2cae7830dec39e60382d7dd1464/xmake/modules/core/project/depend.lua#L42-L65

**Comment by waruqi** [comment]
armclang 我也支持了
