### ISSUE TITLE
对 headeronly 的包，传递 toolchains 给其依赖

### ISSUE THREAD

**Issue by cyfdecyf** [xmake-io/xmake#2688]
### 你在什么场景下需要该功能？

使用 xmake dev branch commit 365f650e4 验证过目前最新版的行为。

cppzmq 是一个 headeronly library，但其依赖 zeromq 并不是 headeronly 的。
执行如下命令：

```
xrepo install --toolchain=gcc-9 zeromq
xrepo install --toolchain=gcc-9 cppzmq
```

第二条命令，由于 toolchain 选项并未传递给 zeromq，因此还是会重新编译 zeromq。

### 描述可能的解决方案

对于依赖的包，如果不是 headeronly 则传递 toolchain 选项。

### 描述你认为的候选方案

目前我的 workaround 是将 cppzmq 的 headeronly 选项移除，缺点是每个 toolchain 都会单独安装一份 cppzmq。

**Comment by waruqi** [comment]
你试试 dev ，xmake update -s dev

**Comment by cyfdecyf** [comment]
更新后针对 cppzmq 测试已经可以了，赞速度，非常感谢！

**Comment by waruqi** [comment]
之前的改动有点问题，我暂时 revert，会在单独的 pr 里面也压测下。。https://github.com/xmake-io/xmake/pull/2690

现在没空细看，回头可能需要改进下。。

**Comment by waruqi** [comment]
应该可以了，你再试试，`xmake update -s github:xmake-io/xmake#requires`

不过 github ci 失效了，暂时没法测试，所以还不能 merge

**Comment by waruqi** [comment]
合并了，再试下

**Comment by cyfdecyf** [comment]
试了下，似乎不太对，toolchain 参数没有传递下去。

```
$ xrepo --version
xRepo 2.6.9+dev.3c54402ff/xmake, A cross-platform C/C++ package manager based on Xmake.

$ xrepo install --toolchain=gcc-11 cppzmq
note: install or modify (m) these packages (pass -y to skip confirm)?
in my-xmake-repo:
  -> zeromq 4.3.4 [from:cppzmq]
  -> cppzmq v4.8.1
please input: y (y/n/m)
```

**Comment by waruqi** [comment]
再试试

**Comment by cyfdecyf** [comment]
能正常传递 toolchain 了，谢谢！
