### ISSUE TITLE
在windows上使用xmake project生成CMakeLists时不能正确配置toolchain的路径

### ISSUE THREAD

**Issue by Xyfuture** [xmake-io/xmake#2693]
### Xmake 版本

2.6.9

### 操作系统版本和架构

windows11 

### 描述问题

在windows上首先使用`xmake f --toolchain=gcc -c`配置编译器为gcc(mingw)，然后使用`xmake project -k cmake -y`生成CMakeLists.txt。这时CMakeLists里面关于编译器配置结果为
```
# target
set(CMAKE_C_COMPILER "gcc")
set(CMAKE_CXX_COMPILER "./g++")
```
g++前面多了个‘./’,不应该用当前路径。
此外配置为mingw(`xmake f --toolchain=mingw -c`)也有问题，生成的CMakeLists如下
```
# target
set(CMAKE_C_COMPILER "C:/Program Files/JetBrains/CLion 2022.1.3/bin/mingw/bin/gcc")
set(CMAKE_CXX_COMPILER "C:\Program Files\JetBrains\CLion 2022.1.3\bin\mingw\bin\g++")
```
c++的编译器路径应该用‘/’,结果用了‘\’,windows上路径不支持直接写‘\’

感觉应该是一处的问题，看了一下plugins里project的源码，之前没接触过lua，没看出有啥问题来

### 期待的结果

```
CMakeLists.txt应该为
# target
set(CMAKE_C_COMPILER "gcc")
set(CMAKE_CXX_COMPILER "g++")
```

```
# target
set(CMAKE_C_COMPILER "C:/Program Files/JetBrains/CLion 2022.1.3/bin/mingw/bin/gcc")
set(CMAKE_CXX_COMPILER "C:/Program Files/JetBrains/CLion 2022.1.3/bin/mingw/bin/g++")
```

### 工程配置

```
target("main")
    set_kind("binary")
    add_files("main.cpp")
```

**Comment by waruqi** [comment]
更新到 dev 再试试，xmake update -s dev

**Comment by Xyfuture** [comment]
mingw的问题解决了
g++那个还是会多个'./'
`cxx = path.join(dir, name)`
这里的dir是‘./’
这个可能也不算是bug吧，我是想直接运行g++，不具体到绝对路径
‘xmake f --toolchain=gcc --cc=gcc --cxx=g++ -c‘ 这个可以解决我的问题了
多谢！

**Comment by waruqi** [comment]
> g++那个还是会多个'./'

好了，再试试

**Comment by Xyfuture** [comment]
好了，全部解决了
