### ISSUE TITLE
支持发布appimage格式的包

### ISSUE THREAD

**Issue by xaljer** [xmake-io/xmake#2696]
### 你在什么场景下需要该功能？

在没有网络连接和管理员权限的服务器上使用appimage包比较方便，但是不方便安装deb包。

### 描述可能的解决方案

每次release支持appimage的包，在Linux上比较通用。

**Comment by waruqi** [comment]
releases 上有 xxx.run 的自安装包，mac/linux 完全通用，不需要网。。你找找，安装包不想再搞其他的了，太多了维护麻烦

**Comment by xaljer** [comment]
哦哦，谢谢。
