### ISSUE TITLE
修正armasm宏定义选项设置

### ISSUE THREAD

**Issue by as564335sa** [xmake-io/xmake#2705]
### Is your feature request related to a problem? Please describe.

目前armasm的宏定义设置，只有固定的 `--pd "XXXX SETA 1"`这种，在一个新项目上需要定义`XXXX=2`这样的宏定义，armasm上是编译不通过的，它的定义方式是 这样`--pd "XXXX SETA 2“

### Describe the solution you'd like

我修改了下armasm的nf_define()函数内容，修正了一下
```
-- make the define flag
function nf_define(self, macro)
    local s = macro:replace(" ", "")
    local def = s:split("=")
    if def[1] == nil then
        return {"--pd", macro .. " SETA 1"}
    end
    local value = 1
    if def[2] ~= nil and #def[2] > 0 then
        value = def[2]
    end
    return {"--pd", def[1] .. " SETA " .. value}
end

**Comment by waruqi** [comment]
add_defines 怎么的写法也贴下呢，然后nf_defines 里面也加点注释

**Comment by as564335sa** [comment]
> add_defines 怎么的写法也贴下呢，然后nf_defines 里面也加点注释

add_defines写法不变，正常添加就行
