### ISSUE TITLE
qt 调试不设置 set_runtimes("MTd") 或者 set_runtimes("MDd") 退出时会报异常

### ISSUE THREAD

**Issue by car520120** [xmake-io/xmake#2709]
### Xmake 版本

2.6.9

### 操作系统版本和架构

win10

### 描述问题

![image](https://user-images.githubusercontent.com/36702004/185909323-03475b33-1bd9-4639-802e-a0801269f0cc.png)

### 期待的结果

正常退出

**Comment by waruqi** [comment]
这好像跟 xmake 也没啥关系吧，你可以到 Qt 那个去反馈下。。如果 Qt Creator / qmake 带  MT 编译运行正常，那就自己对比下 flags 


我这也没 win qt 环境去调这个。

**Comment by scially** [comment]
我最近在用xmake编译Qt的时候也有这个问题，我如果用MT编译，程序就到这里`QString::toStdString`就会崩溃，如果我设置成MD，系统可以运行，但是明细结果不对
```
add_rules("mode.debug", "mode.release")
set_runtimes("MD")

target("xmakeproject")
    add_rules("qt.console")
    add_files("src/*.cpp")
```

```
#include <QCoreApplication>
#include <QString>

int main(int argc, char *argv[])
{
    QCoreApplication app(argc, argv);

    QString a = "测试Xmake Qt工程";
    std::string b = a.toStdString();
    return app.exec();
}
```

![image](https://user-images.githubusercontent.com/22127608/199227328-7eee3e89-36c2-457e-a990-4d0c2524860c.png)

**Comment by scially** [comment]
> 不知道，你可以自己对下 flags 调下，我暂时没 win qt 环境。

好吧 我试试 xmake怎么查看编译的flags

**Comment by scially** [comment]
> 不知道，你可以自己对下 flags 调下，我暂时没 win qt 环境。

搞不定…… flgs看着好像没差别了 除了/MD，能帮忙看看么。

**Comment by scially** [comment]
> > 不知道，你可以自己对下 flags 调下，我暂时没 win qt 环境。
> > @waruqi
> > 搞不定…… flgs看着好像没差别了 除了/MD，能帮忙看看么。

@waruqi 确实是，如果用的是msvc，qt.console要设置MD 或者 MDd
