### ISSUE TITLE
github ci使用curl安装错误使用了gitee仓库

### ISSUE THREAD

**Issue by SkyTeamWater** [xmake-io/xmake#2718]
### Xmake 版本

2.6.9

### 操作系统版本和架构

ubuntu 20.04应该？

### 描述问题

github ci使用curl安装时小概率用gitee导致pull失败
![-36e20bd829cb2527](https://user-images.githubusercontent.com/51621873/186369134-4e0238e7-2042-4aaa-a937-e8a03161faae.png)

### 期待的结果

使用github repo正常安装

**Comment by waruqi** [comment]
这种就没必要提了吧，你可以重跑下 ci job ，或者给 gitee 提 issues 让他们改进下服务

**Comment by SkyTeamWater** [comment]
ok！
