### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by paulocoutinhox** [xmake-io/xmake#2724]
### Xmake Version

all

### Operating System Version and Architecture

all

### Describe Bug

The code to use vcpkg is wrong because it have only a single ":"

<img width="428" alt="image" src="https://user-images.githubusercontent.com/395096/186934089-45e05ff0-bf1e-4b2c-8e32-b5dba287dc69.png">

### Expected Behavior

Have to "::"

### Project Configuration

-

### Additional Information and Error Logs

-

**Comment by waruqi** [comment]
fixed
