### ISSUE TITLE
Sometimes the package environments are not bound to on_buildcmd_files

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2729]
### Xmake 版本

2.7.1

### 操作系统版本和架构

Windows 10

### 描述问题

在on_buildcmd_files中调用find_program，如果项目中有phony target，则有时会找不到add_requires引入的package，有时能找到

### 期待的结果

希望可以确保on_buildcmd_files环境绑定依赖包环境

### 工程配置

```
add_requires("bgfx")
rule("test")
	set_extensions(".ext")
	on_buildcmd_files(function (target, batchcmds, sourcefile, opt)
		import("lib.detect.find_program")
		assert(find_program("shadercRelease", {paths = "$(env PATH)"}))
	end)
add_rules("test")
target("phony")
	set_kind("phony")
target("main")
	add_files("asset.ext")
	add_files("main.cpp")
```

**Comment by waruqi** [comment]
你这个例子不完整，没有 add_packages 绑定任何包，shadercRelease 也不在 bdfx 包里。。无法测试

**Comment by waruqi** [comment]
shadercRelease 在哪？我没看到 bgfx 里面有这个么，这个包都没设置 bin path

**Comment by xq114** [comment]
> shadercRelease 在哪？我没看到 bgfx 里面有这个么，这个包都没设置 bin path

https://github.com/xmake-io/xmake-repo/blob/master/packages/b/bgfx/xmake.lua#L110

**Comment by waruqi** [comment]
试下这个 patch ，对 dep public package 也整进来了，应该能用了。。不过 envs 隔离问题 不太好搞，可能会影响性能 后面再想办法。

**Comment by xq114** [comment]
这个地方只处理一层够吗？要是有链式依赖的话还得递归处理吧

**Comment by waruqi** [comment]
orderdeps 原本就是所有 deps 展开后的了

**Comment by waruqi** [comment]
这里没问题的话 先这样吧
