### ISSUE TITLE
Can't use vcpkg::tracy as a dependency

### ISSUE THREAD

**Issue by braxtons12** [xmake-io/xmake#2730]
### Xmake Version

v2.7.1+master.6ae8de7

### Operating System Version and Architecture

Arch Linux, 5.19.4-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 25 Aug 2022 17:31:19 +0000 x86_64 GNU/Linux

### Describe Bug

Trying to require `vcpkg::tracy` as a dependency fails.

Relying on xmake to get the latest version via:
```
add_requires("vcpkg::tracy", {
    alias = "tracy",
    system = false,
    configs = {
        languages = cxx20
    }
})
```
results in "fetch vcpkg::tracy-latest failed!" being printed in both the CLI and the install log, with no further information.

Using ether of this:
```
add_requires("vcpkg::tracy 0.8.2", {
    alias = "tracy",
    system = false,
    configs = {
        languages = cxx20
    }
})
```
or this:
```
add_requires("vcpkg::tracy >=0.8.0", {
    alias = "tracy",
    system = false,
    configs = {
        languages = cxx20
    }
})
```

results in "error: the baseline does not contain an entry for port tracy" in both the CLI and install log.

In the first case, vcpkg actually does successfully install tracy, xmake just seems to think it didn't for some reason.
If I run `vcpkg list`, tracy is listed as installed at version 0.8.2.

In the second and third cases, vcpkg does not install tracy, even though running
`vcpkg search tracy` returns:
`tracy                    0.8.2            A real time, nanosecond resolution, remote telemetry, hybrid frame and sam...`
which means there is in fact an entry for tracy at version 0.8.2.

### Expected Behavior

xmake should successfully fetch tracy from vcpkg

**Comment by waruqi** [comment]
> results in "fetch vcpkg::tracy-latest failed!" being printed in both the CLI and the install log, with no further information.

run `xmake f -c -vD` and give me verbose logs

> In the first case, vcpkg actually does successfully install tracy, xmake just seems to think it didn't for some reason.
If I run vcpkg list, tracy is listed as installed at version 0.8.2.

xmake runs `vcpkg install tracy:x64-windows-static ` by default, so it installs the x64-windows-static version.

Even if you have installed it with `vcpkg install tracy`, they are not an exact match and xmake cannot find it.

Unless you switch to the dynamic library version using `configs = {shared = true}`, or install `vcpkg install tracy:x64-windows-static` manually

**Comment by waruqi** [comment]
it works for your configuration on my host.

![image](https://user-images.githubusercontent.com/151335/187116617-b199cf43-63f2-48ef-a894-a01219df4afc.png)

**Comment by braxtons12** [comment]
> run `xmake f -c -vD` and give me verbose logs

This helped solve the problem.
`checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!`

Apparently `$VCPKG_ROOT` wasn't being set correctly in my environment. Fixing that has solved the problem and I've got it working now!

**Comment by waruqi** [comment]
you can also run `vcpkg integrate install` or `xmake f --vcpkg=/vcpkgroot` to let xmake find it.
