### ISSUE TITLE
支持 add_cxxflags("/P")

### ISSUE THREAD

**Issue by car520120** [xmake-io/xmake#2732]
### 你在什么场景下需要该功能？

需要查看预编译文件时需要看到

### 描述可能的解决方案

add_cxxflags("/P") 或者是封装个所有平台都支持的

**Comment by waruqi** [comment]
加 cxxflags 影响编译，你确定要这么干？你直接 add_cxxflags 加进去不就好了

**Comment by car520120** [comment]
旧的是可以，不知道为什么新的我加上去后，就编译出错的了！ 不知道是不是 VS2022 改了规则的
https://docs.microsoft.com/zh-cn/cpp/build/reference/p-preprocess-to-a-file?view=msvc-170

**Comment by waruqi** [comment]
xmake f --ccache=n 禁用 cache 后试试
