### ISSUE TITLE
在 macOS 上 xmake install 会把符号链接文件复制成文件

### ISSUE THREAD

**Issue by CaffreySun** [xmake-io/xmake#2742]
### Xmake 版本

2.7.1

### 操作系统版本和架构

macOS 12.4, Mac mini (M1, 2022)

### 描述问题

首先在macOS上使用`add_rules("xcode.framework")`编译一个framework出来，
使用 `ls -l` 查看framework目录结构如下：
```
Headers -> Versions/Current/Headers
RbtBezier -> Versions/Current/RbtBezier
Resources -> Versions/Current/Resources
Versions
```
能看到Headers、RbtBezier、Resources是符号链接，都指向了Versions目录中。

使用`set_installdir`设置安装目录，执行`xmake install`，
使用 `ls -l` 查看安装的framework：
```
Headers
RbtBezier
Resources
Versions
```

能看到Headers、RbtBezier、Resources已经不是符号链接了。

虽然这样的framework单独使用时也能用，但是使用`xcodebuild -create-xcframework` 命令将framework合并成xcframework时就会有问题。

### 期待的结果

执行`xmake install`能保持符号链接。
我平时复制framework时使用`cp -R -H`命令，这样可以保持符号链接。

**Comment by waruqi** [comment]
完全修复了 xmake update dev
