### ISSUE TITLE
Binary dependency is not correctly handled

### ISSUE THREAD

**Issue by find** [xmake-io/xmake#2747]
### Xmake Version

2.7.1

### Operating System Version and Architecture

Windows 10 Pro 20H2

### Describe Bug

When target `b` depends on `a` where `a` is a binary target, xmake does not build `a` before `b`

### Expected Behavior

Always build `a` before `b` if `b` depends on `a`

### Project Configuration

xmake.lua:
```lua
target('a')
  set_kind('binary')
  add_files('a.c')

rule('rulea')
  on_load(function(t)
    local o=t:autogendir()
    t:add('deps', 'a')
    t:add('includedirs', o)
  end)
  before_buildcmd_file(function(t, b, s)
    import('core.project.project')
    local o=t:autogendir()
    if not os.isdir(o) then os.mkdir(o) end
    local n=s:gsub('%\\','/'):match('([^/]+)%.[^%.]+$')
    b:vrunv(project.target('a'):targetfile(), {
      path.join(o, n..'.h')
    })
  end)

target('b')
  set_kind('binary')
  add_rules('rulea')
  add_deps('a') -- to be or not to be, xmake behaves the same
  add_files('b.c')
  add_files('b.c', {rule='rulea'})
```

a.c:
```c
#include <stdio.h>

int main(int c, char** v)
{
  if (c!=2) return -1;
  FILE* f=fopen(v[1], "wb");
  if (!f) return -1;
  fprintf(f, "enum { HELLO = 1024 };\n");
  fclose(f);
  return 0;
}
```

b.c:
```c
#include "b.h"
#include <stdio.h>

int main()
{
  printf("%d\n", HELLO);
  return 0;
}
```

### Additional Information and Error Logs

you will need manually call `xmake -b a` before `xmake` to build above example

**Comment by waruqi** [comment]
see https://xmake.io/#/manual/project_target?id=buildacross_targets_in_parallel

**Comment by find** [comment]
Thanks, that works!

but I'm fairly sure that depending on a `binary` target semantically implies requiring that binary to be executable (fully linked) - or what else can the dependency statement mean? Please consider making it automatic

**Comment by waruqi** [comment]
By default, all target source files have no dependencies on each other, so even if add_deps is set, they can be compiled in full parallel, which can significantly improve compilation speed. This has nothing to do with whether or not they depend on binary at the moment.

Their final linking dependencies will still be linked according to add_deps, ensuring that no linking errors occur.


But you are artificially creating dependencies between sources by relying on a target in the before_build_file script, breaking the default parallelism policy. So you can only disable cross-target parallelism for a given target according to the set_policy I mentioned.

This is not automatically recognised because xmake has no way of knowing the dependencies between the script configured by the user in the before_build_file script and other targets.

**Comment by find** [comment]
Well, I've digged into the xmake code base a little just now, and IMHO changing [this line](https://github.com/xmake-io/xmake/blob/master/xmake/actions/build/build.lua#L200) in `build.lua` from
```lua
if dep:policy("build.across_targets_in_parallel") == false then
```
into
```lua
if dep:policy("build.across_targets_in_parallel") == false or dep:kind() == 'binary' then
```
is sufficient, and reasonable.

**Comment by waruqi** [comment]
You're still missing my point, even the source files of the binary target and the source files of the other targets can be compiled in full parallel with each other without relying on add_deps, it's just that you're making extra dependencies in the before_build_file that make the source files dependent on target A.

**Comment by waruqi** [comment]
> Well, I've digged into the xmake code base a little just now, and IMHO changing [this line](https://github.com/xmake-io/xmake/blob/master/xmake/actions/build/build.lua#L200) in `build.lua` from
> 
> ```lua
> if dep:policy("build.across_targets_in_parallel") == false then
> ```
> 
> into
> 
> ```lua
> if dep:policy("build.across_targets_in_parallel") == false or dep:kind() == 'binary' then
> ```
> 
> is sufficient, and reasonable.

If you do this, the source files in the binary target will not be compiled in parallel with the source files of other targets, which will affect the compilation speed.

**Comment by find** [comment]
> You're still missing my point, even the source files of the binary target and the source files of the other targets can be compiled in full parallel with each other without relying on add_deps, it's just that you're making extra dependencies in the before_build_file that make the source files dependent on target A.

I got the point, that `add_deps` join depencies at linking stage.

But I think when you depend on an binary, you'd **always** want that binary to be executable **before compiling**, as it just makes no sense at link stage afterall. So the binary being depended on shouldn't be compiled in parallel with other projects anyway.



-------------------

> > Well, I've digged into the xmake code base a little just now, and IMHO changing [this line](https://github.com/xmake-io/xmake/blob/master/xmake/actions/build/build.lua#L200) in `build.lua` from
> > ```lua
> > if dep:policy("build.across_targets_in_parallel") == false then
> > ```
> >   
> > into
> > ```lua
> > if dep:policy("build.across_targets_in_parallel") == false or dep:kind() == 'binary' then
> > ```
> > 
> > is sufficient, and reasonable.
> 
> If you do this, the source files in the binary target will not be compiled in parallel with the source files of other targets, which will affect the compilation speed.

So be it, if not so, I will have to add `set_policy('build.across_targets_in_parallel', false)` in the dependent project manually to make it build, ended up all the same.

**Comment by waruqi** [comment]
It makes sense for compilation speedup, if you have 100 binary targets and only one source file per binart target, then I can compile 100 source files in parallel and then link them one by one. Compile a.c, b.c, c.c in parallel ...

But as you say, the 100 source files can only be compiled one by one. compile a.c, link a, compile b.c, link b ...

It will be very slow.

**Comment by find** [comment]
> But as you say, the 100 source files can only be compiled one by one. compile a.c, link a, compile b.c, link b ...

When `b` depends on `a`, `c` depends on `b`, ... that is the case, and that's what we want, wasn't it?

If `c` doesn't depend on `a` or `b`, nothing stops it from being compiled in parallel

**Comment by waruqi** [comment]
If b depends on a and c depends on b, but I can still compile their source files in parallel, but now I can't.

**Comment by find** [comment]
> If b depends on a and c depends on b, but I can still compile their source files in parallel,

If `a` is a binary, it's definitely not something to link to, in what way would `b` depends on `a` then?

**Comment by find** [comment]
Or let's see if it's clearer if I put it this way: 

What I need is something like `add_deps_thats_ready_to_execute_before_compiling(...)`, and I thought `add_deps(binary)` should imply that, as binary dependencies only make sense before compiling.

**Comment by waruqi** [comment]
> > If b depends on a and c depends on b, but I can still compile their source files in parallel,
> 
> If `a` is a binary, it's definitely not something to link to, in what way would `b` depends on `a` then?

Run other binary programs in scripts like before_link, after_build, etc. As you are doing now, b also depends on a. and run a in b script

**Comment by waruqi** [comment]
> Or let's see if it's clearer if I put it this way:
> 
> What I need is something like `add_deps_thats_ready_to_execute_before_compiling(...)`, and I thought `add_deps(binary)` should imply that, as binary dependencies only make sense before compiling.

so you just need set_policy for this target.

**Comment by find** [comment]
> > > If b depends on a and c depends on b, but I can still compile their source files in parallel,
> > 
> > If `a` is a binary, it's definitely not something to link to, in what way would `b` depends on `a` then?
> 
> Run other binary programs (a) in b scripts like before_link, after_build, etc. As you are doing now, b also depends on a. and run a in b script

Okay.. that makes sense. Still think something like `add_deps(..., {deadline='before_build'})` would be better, but I'm good with the `set_policy` solution
