### ISSUE TITLE
xrepo export 将 so 软链接复制成普通文件

### ISSUE THREAD

**Issue by cyfdecyf** [xmake-io/xmake#2753]
### Xmake 版本

 v2.7.1+dev.56a32c8a1

### 操作系统版本和架构

Arch Linux, Ubuntu 20.04

### 描述问题

执行以下命令：

```
xrepo install -f shared=true gflags
xrepo export -f shared=true --shallow -o gflags-pkg gflags
```

export 后的 lib 目录下所有 .so 软链接变成了普通文件。

确认过 .xmake/package/g/gflags 安装目录下动态库的软链接是正常的。

### 期待的结果

xrepo export 保持动态库的软链接。

**Comment by waruqi** [comment]
更新到 dev 再试试，xmake update dev

要全量更新 包括 binary

**Comment by cyfdecyf** [comment]
测试确认已修复，谢谢！

**Comment by cyfdecyf** [comment]
上午仅测试了 `xrepo export` 是正常的，但 `xrepo install` 从 artifacts 安装时，artifacts tarball 中的软链接在安装后还是变成了普通文件。

看代码 `import_pacakges` 里有相关的变更，但不确定为何没有生效。我直接 reopen 这个 issue 了。

**Comment by waruqi** [comment]
我这边测试导入是正常的，没啥问题，你可以调下 tar 解压这块，是否保留了 symlink

**Comment by cyfdecyf** [comment]
我这里是用 lua 脚本来指定 package 的，尝试执行

`xrepo install -vD pkg/gflags.lua`

执行过程中输出的 `tar -xf xxx.tar.gz -C source.tmp` 命令有手动执行过（进到 `~/.xmake/cache/packages/2209/g/gflags/v2.2.2` 目录下），解压出来的 lib 目录下的确是软链接。

install 命令输出中并没有出现  `importing xxx` 这行消息，是不是以上命令并不是执行 `import_packages.lua` 中的代码？

**Comment by waruqi** [comment]
xrepo install 不走 export/import ，跟 export/import 没啥关系，应该是 artifacts 的 install copy 问题

**Comment by waruqi** [comment]
稍微改了下 再试试 xmake update dev

**Comment by cyfdecyf** [comment]
`xrepo install` 现在也能保留 artifacts 里的软链接了，谢谢！
