### ISSUE TITLE
clatest sets -std=c17

### ISSUE THREAD

**Issue by davidchisnall** [xmake-io/xmake#2772]
### Xmake Version

v2.7.1+dev.e59566a7d

### Operating System Version and Architecture

FreeBSD 14

### Describe Bug

Setting `set_languages("clatest")` adds `-std=c17` to cflags.  This then causes build failures for C2x features.

### Expected Behavior

Setting `set_languages("clatest")` should add `-std=c2x` to cflags.

It is possible to explicitly add `-std=c2x`, but it's quite surprising that you can't opt into this (or into C++2y or C++2z), in spite of the fact that compilers either do, or will, support this during the lifetime of a packaged release of a build system

**Comment by waruqi** [comment]
I have improved it. `xmake update -s dev`
