### ISSUE TITLE
当xmake.lua钟含有add_files("xxx.qrc")的时候，无法正常生成compile_command.json

### ISSUE THREAD

**Issue by hybcloud** [xmake-io/xmake#2776]
### Xmake 版本

xmake v2.7.1+master.5c0e53f91

### 操作系统版本和架构

windows11 21H2 (22000.856)

### 描述问题

通过
```
xmake create -t qt.quickapp test
```
生成的测试项目
xmake.lua内容为：
![image](https://user-images.githubusercontent.com/43987901/188308437-1d3155cb-d5ea-4a70-991b-d3f21bac5bef.png)
执行
```
xmake project -k compile_commands --verbose
```
后，得到报错：
![image](https://user-images.githubusercontent.com/43987901/188308465-8b73075a-6bce-4c1a-9e04-a5e5188669f3.png)
注释掉`add_files("src/qml.qrc")`后
![image](https://user-images.githubusercontent.com/43987901/188308559-75494b67-fa5f-4771-a522-d6478f5e6a8c.png)

，再次执行
```
xmake project -k compile_commands --verbose
```
，则能正常生成compile_command.json：
![image](https://user-images.githubusercontent.com/43987901/188308570-63aa22bc-7f06-40a5-b057-1c2050bcc627.png)

### 期待的结果

当add_files("xxx.qrc")时，仍然额能够正常生成compile_command.json

### 工程配置

```
add_rules("mode.debug", "mode.release")

target("test")
    add_rules("qt.quickapp")
    add_headerfiles("src/*.h")
    add_files("src/*.cpp")
    add_files("src/qml.qrc")
```

**Comment by waruqi** [comment]
> 后，得到报错：

报错信息呢？在哪？

**Comment by hybcloud** [comment]
> > 后，得到报错：
> 
> 报错信息呢？在哪？

![image](https://user-images.githubusercontent.com/43987901/188317104-b3779d97-71f9-4808-a106-902d28874eaf.png)

不好意思，截图截掉了:-(

**Comment by hybcloud** [comment]
另外在存在.h文件的时候也会出现相同的问题

**Comment by waruqi** [comment]
```console
quickapp$ xmake project -k compile_commands
create ok!
```

我 linux 下可以，win 上我暂时没 qt 环境，你可以加点 print log 调下这里，看看为啥输入参数 `os.args(arguments_escape) .. sourcefile` 是 table 不是 string

https://github.com/xmake-io/xmake/blob/6175fa9fc9781b22da3c3f8fca54318eb9bb3101/xmake/plugins/project/clang/compile_commands.lua#L129

**Comment by hybcloud** [comment]
为了处理这个问题现学的相关知识，可能debug的方式有些拙劣，还请大佬指教。
![image](https://user-images.githubusercontent.com/43987901/188542411-46e89973-b009-460d-9eec-817f9a9b642e.png)
![image](https://user-images.githubusercontent.com/43987901/188542597-4cb642bb-672d-4f9e-9e96-553fe4b5c972.png)
![image](https://user-images.githubusercontent.com/43987901/188542935-fffbeaea-3773-4df2-97f0-528bb49ac031.png)
我认为，这个args虽然是table，但是因为未知的原因通过了lua的check_string检查，而且它确实可以转化为字符串
所以一个可能的解决方法是：在hash.uuid()之前将sourcefile强行转换为string
![image](https://user-images.githubusercontent.com/43987901/188549786-779b4c49-7cda-4f5a-9ad2-c5bab46e5d30.png)
此时能够正常运行：
![image](https://user-images.githubusercontent.com/43987901/188550132-b67633e9-dc2d-411e-9ae5-c19bd8060559.png)

但这样做其实掩盖了args为什么是table的问题，所以我觉得还得您再看看再指导一下

**Comment by waruqi** [comment]
我修了，你再试试，这个 table 其实是 path object 

xmake update -s dev

**Comment by hybcloud** [comment]
> 我修了，你再试试，这个 table 其实是 path object
> 
> xmake update -s dev

![image](https://user-images.githubusercontent.com/43987901/188551543-bab04d22-45c1-4d03-a245-dfbb8f9e75a1.png)

![image](https://user-images.githubusercontent.com/43987901/188551601-bd8a5a53-f238-4d3e-967d-0646b66a921e.png)

嗯，已经OK了，谢谢大佬
