### ISSUE TITLE
add target directory to PYTHONPATH if the `python.library` rule is present

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2777]
### 你在什么场景下需要该功能？

https://github.com/xmake-io/xmake/issues/2599

目前调试时仅将target directory加入PATH中，但对python module还需要将目标路径加入PYTHONPATH才能正常调用

### 描述可能的解决方案

对声明python.library的target，将targetdir加入虚拟环境的PYTHONPATH环境变量中

**Comment by waruqi** [comment]
试下这个 patch https://github.com/xmake-io/xmake/pull/2778

target/add_runenvs 也顺带支持了，xrepo env

**Comment by xq114** [comment]
可以了
