### ISSUE TITLE
WDK Rule 对于新版 signtool 工具缺乏 /fd 参数指定

### ISSUE THREAD

**Issue by jianglu** [xmake-io/xmake#2783]
### Xmake 版本

v2.6.9+HEAD.22ecc0156

### 操作系统版本和架构

Windows 11 22000.918

### 描述问题

使用 WDK Rule 编译 Windows 驱动工程，Sign 签名过程发生错误

`
...
[ 20%]: ccache compiling.release common.cpp
[ 20%]: ccache compiling.release disp_filter.cpp
[ 60%]: linking.release DispFilter.sys
[ 80%]: signing.test DispFilter.sys
error: SignTool Error: No file digest algorithm specified. Please specify the digest algorithm with the /fd flag. Using /fd SHA256 is recommended and more secure than SHA1. Calling signtool with /fd sha1 is equivalent to the previous behavior. In order to select the hash algorithm used in the signing certificate's signature, use the /fd certHash option.
...
`

在 Windows Kits 10.0.22000.0 等较新版本中，signtool.exe 工具需要显式指定 /fd 参数

`/fd         Specifies the file digest algorithm to use for creating file
            signatures. If this parameter is not specified, an error will be
            generated.`

### 期待的结果

增加选项指定 /fd

xmake 可以考虑增加 vrun 的 filter/middleware，方便类似类似问题在工程上的临时处理

**Comment by waruqi** [comment]
已合并，谢谢
