### ISSUE TITLE
menuconfig 界面相关

### ISSUE THREAD

**Issue by liukangcc** [xmake-io/xmake#2793]
### Is your feature request related to a problem? Please describe.

1. 子界面配置完成 back 后，菜单选项依然停留在 back 选项
![image](https://user-images.githubusercontent.com/44889940/189018024-2f584e07-fa64-4855-a8dc-54d67cbb13bb.png)

2. Exit 退出时，没有提示用户是否去保存修改

### Describe the solution you'd like

1. back 菜单逻辑：子界面配置完成，选择 back 后，希望选项能停留在父界面的 select 选项：
   
![buildroot_back](https://user-images.githubusercontent.com/44889940/189018990-f33aa841-0f23-4712-8207-c70a6eb5175c.gif)

2. exit 菜单逻辑：当用户有修改并且选择了 exit 选项时，需要提示用户是否保存当前修改，而不是直接强制退出：
   
![buildroot_exit](https://user-images.githubusercontent.com/44889940/189019207-7db3723b-56ca-4c7c-b76b-361952c2106c.gif)

**Comment by waruqi** [comment]
> back 菜单逻辑：子界面配置完成，选择 back 后，希望选项能停留在父界面的 select 选项：

这个我改了，更新到 dev 再试试，`xmake update -s dev`

**Comment by waruqi** [comment]
> exit 菜单逻辑：当用户有修改并且选择了 exit 选项时，需要提示用户是否保存当前修改，而不是直接强制退出：

这个也可以了
