### ISSUE TITLE
add_includedirs添加了头文件路径还是提示找不到

### ISSUE THREAD

**Issue by guangjieMVP** [xmake-io/xmake#2794]
### Xmake Version

xmake v2.6.9+202207171349

### Operating System Version and Architecture

ubuntu18.04 x86

### Describe Bug

[ 28%]: cache compiling.release lvgl/src/draw/sdl/lv_draw_sdl_texture_cache.c
error: lvgl/src/extra/libs/ffmpeg/lv_ffmpeg.c:15:32: fatal error: libavcodec/avcodec.h: No such file or directory
 #include "libavcodec/avcodec.h"
                                ^

lv_ffmpeg.c 头文件是这样添加的：
`#include "libavcodec/avcodec.h"
#include "libavformat/avformat.h"
#include "libavutil/imgutils.h"
#include "libavutil/samplefmt.h"
#include "libavutil/timestamp.h"
#include "libswscale/swscale.h"`

add_includedirs("/home/ares/work/tmp_lib/ffmpeg/include/") 这个就是avcodec.h:头文件所在的目录

https://github.com/xmake-io/xmake/issues/1879 参考这个issues，同这样add_includedirs("/home/ares/work/tmp_lib/ffmpeg/include/") 添加头文件目录不行

就试过修改头文件包含，无论是绝对路径还是相对路径说找不到，确认过那个路径头文件是存在的

### Expected Behavior

*

### Project Configuration

`
-- 设置工程名
set_project("mutilmedia")

-- 设置工程版本
set_version("1.1.0")

-- 自定义工具链
toolchain("arm-linux-gnueabihf")
    -- 标记为独立工具链
    set_kind("standalone")
    -- 定义交叉编译工具链地址
    set_sdkdir("/usr/local/arm_gcc/gcc-linaro-4.9.4-2017.01-i686_arm-linux-gnueabihf")
    add_linkdirs("/usr/local/arm_gcc/gcc-linaro-4.9.4-2017.01-i686_arm-linux-gnueabihf/arm-linux-gnueabihf/libc/usr/lib")
    add_includedirs("/usr/local/arm_gcc/gcc-linaro-4.9.4-2017.01-i686_arm-linux-gnueabihf/arm-linux-gnueabihf/libc/usr/include")   
toolchain_end()

target("lvglv8")
    -- static lib
    set_kind("static")  
     -- 设置使用的交叉编译工具链
    set_toolchains("arm-linux-gnueabihf")  

    set_languages("c99", "c++11")

    local lvgl_src_path = {
        "lvgl/src/",
    --    "lvgl/demos/",
     --   "lv_drivers/"
    }

    for _, index in ipairs(lvgl_src_path) do
        for _, dir in ipairs(os.dirs(index.."/**")) do
            add_files(dir.."/*.c")  
            add_includedirs(dir)
        end
    end

    add_includedirs("lvgl")
target_end()

target("mutlimedia")  -- 设置目标程序名字
    set_kind("binary")   -- 设置编译成二进制程序，不设置默认编译成二进制程序，可选择编译成动静态库等
    
     -- 设置使用的交叉编译工具链
    set_toolchains("arm-linux-gnueabihf")  
   
    -- -- 设置平台
    set_plat("cross")
    -- 设置架构
    set_arch("arm")

    set_languages("c99", "c++11")

    -- 设置链接库搜索路径
    add_linkdirs("/opt/tslib-1.21/lib")  
    add_linkdirs("/home/ares/work/tmp_lib/ffmpeg/lib")   
    add_linkdirs("/home/ares/work/tmp_lib/x264/lib")   
    --add_linkdirs("/usr/local/arm_gcc/gcc-linaro-4.9.4-2017.01-i686_arm-linux-gnueabihf/arm-linux-gnueabihf/libc/usr/lib")
    -- 设置链接的库
    add_links("m", "pthread", "ts")
    add_deps("lvglv8")
    add_links("x264")
    add_links("avformat", "avcodec", "avutil", "swscale", "swresample", "m", "pthread")

    --  add_cflags(
    --     "-O3"
    --  )

    local lvgl_src_path = {
    --    "lvgl/src/",
        "lvgl/demos/",
        "lv_drivers/"
    }

    for _, index in ipairs(lvgl_src_path) do
        for _, dir in ipairs(os.dirs(index.."/**")) do
            add_files(dir.."/*.c") 
            add_includedirs(dir)
        end
    end

    add_includedirs("lvgl")
    add_files("lvgl/examples/libs/ffmpeg/*.c") 
    add_includedirs("lvgl/examples/libs/ffmpeg")

    local usr_src_path = {
        ".",
        "multimedia",
        "multimedia/font",
        "multimedia/img/camera",
        "multimedia/img/desktop",
        "multimedia/img/light",
        "multimedia/img/music",
        "multimedia/img/time", 
        "multimedia/img/video",
        "multimedia/img/weather",
    }

    for _, dir in ipairs(usr_src_path) do
        add_files(dir.."/*.c");  
    end

    remove_files("multimedia/font/myFontDailyWeather.c")
    remove_files("multimedia/font/myFont_Foshan.c")
    remove_files("multimedia/font/myFontNumber.c")

    add_includedirs(".")   
    add_includedirs("/opt/tslib-1.21/include")
    add_includedirs("/home/ares/work/tmp_lib/x264/include")

    -- add_includedirs("th3lib/include/libavcodec") 
    -- add_includedirs("th3lib/include/libavfilter") 
    -- add_includedirs("th3lib/include/libavutil") 
    -- add_includedirs("th3lib/include/libswresample") 
    -- add_includedirs("th3lib/include/libavdevice") 
    -- add_includedirs("th3lib/include/libavformat") 
    -- add_includedirs("th3lib/include/libpostproc") 
    -- add_includedirs("th3lib/include/libswscale") 
    -- add_includedirs("/home/ares/work/tmp_lib/ffmpeg/include/")

    -- add_includedirs("th3lib/include/")
    add_includedirs("/home/ares/work/tmp_lib/ffmpeg/include/")

    -- local ffmpeg_inc = { 
    --     "/home/ares/work/tmp_lib/ffmpeg/include/libavcodec",
    --     "/home/ares/work/tmp_lib/ffmpeg/include/libavfilter",
    --     "/home/ares/work/tmp_lib/ffmpeg/include/libavutil",
    --     "/home/ares/work/tmp_lib/ffmpeg/include/libswresample",
    --     "/home/ares/work/tmp_lib/ffmpeg/include/libavdevice",
    --     "/home/ares/work/tmp_lib/ffmpeg/include/libavformat",
    --     "/home/ares/work/tmp_lib/ffmpeg/include/libpostproc",
    --     "/home/ares/work/tmp_lib/ffmpeg/include/libswscale",
    -- }
    -- for _, ffmpeg in ipairs(ffmpeg_inc) do  
    --     add_includedirs(ffmpeg)
    -- end

    -- -- 递归遍历获取所有子目录
    -- for _, dir in ipairs(os.dirs("lvgl/src/**")) do
    --     add_files(dir.."/*.c");    
    --     add_includedirs(dir);
    -- end

    -- -- 递归遍历获取所有子目录
    -- for _, dir in ipairs(os.dirs("lvgl/demos/**")) do
    --     add_files(dir.."/*.c");   -- 添加目录下所有C文件
    --     add_includedirs(dir);  -- 添加目录作为头文件搜索路径
    -- end

    -- for _, v in ipairs(os.dirs("lv_drivers/**")) do
    --     add_files(v.."/*.c");
    --     add_includedirs(v);
    -- end

    after_build(
        function(target)
        cprint("Compile finished!!!")

        print(" ")
        os.exec("sudo cp build/cross/arm/release/mutlimedia /mnt/nfs/")  
    end)`

**Comment by waruqi** [comment]
这种项目自身编译问题，自己调哈，跟 xmake 又没啥关系，只要你 add_includedirs 配置了, xmake -v 看完整命令行，`-Ixx` flags 确实加进去了，那就是配置生效了。。

至于你配置了什么路径，没找到，那是你自身项目的配置错误问题，不在 xmake 维护范围呢

**Comment by guangjieMVP** [comment]
👌谢谢
