### ISSUE TITLE
`-y` and `--confirm=y` flag not working with `xrepo remove`

### ISSUE THREAD

**Issue by vic1707** [xmake-io/xmake#2805]
### Xmake Version

dev latest & 2.7.1

### Operating System Version and Architecture

Ubuntu 22.04 github CI, MacOS, ubuntu (in docker)

### Describe Bug

When I run `xrepo remove --all fmt` with either validation flag it doesn't automatically remove the package and instead waits for input resulting in action's failure on github CI 

<img width="708" alt="image" src="https://user-images.githubusercontent.com/28602203/189615109-e6eef9b0-e176-45c9-a180-672179e0a161.png">

### Expected Behavior

should not prompt for confirmation

**Comment by waruqi** [comment]
Please move all `--xxx` arguments to the left of the fmt package name.

```
xrepo remove --all -y fmt
```

**Comment by vic1707** [comment]
mybad 😓
