### ISSUE TITLE
看教程执行出错。

### ISSUE THREAD

**Issue by NaonaoCoke** [xmake-io/xmake#2806]
### Xmake Version

2.7.1

### Operating System Version and Architecture

windows10 

### Describe Bug

[mingw-w64] F:\vscode\111\helloworld>xmake
checking for mingw directory ... D:\program\Anaconda3\Library\mingw-w64
error: ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:56: cannot get program for cxx
stack traceback:
        @programdir\core\base\utils.lua:290: in function <@programdir\core\base\utils.lua:280>
        [C]: in function 'error'
        @programdir\core\base\os.lua:882: in function 'os.raiselevel'
        (...tail calls...)
        ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:56: in field 'co_start_withopt'
        @programdir\modules\private\async\runjobs.lua:217: in function <@programdir\modules\private\async\runjobs.lua:162>
        [C]: in function 'xpcall'
        @programdir\core\base\utils.lua:280: in function 'sandbox/modules/utils.trycall'
        @programdir\core\base\scheduler.lua:504: in function 'base/scheduler.co_group_begin'
        ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:94: in field 'co_group_begin'
        @programdir\modules\private\async\runjobs.lua:162: in function <@programdir\modules\private\async\runjobs.lua:56>
        (...tail calls...)
        @programdir\actions\build\build.lua:246: in function <@programdir\actions\build\build.lua:234>
        (...tail calls...)
        @programdir\actions\build\main.lua:103: in global '_do_build'
        @programdir\actions\build\main.lua:150: in function <@programdir\actions\build\main.lua:144>
        [C]: in function 'xpcall'
        @programdir\core\base\utils.lua:280: in function 'sandbox/modules/utils.trycall'
        @programdir\core\sandbox\modules\try.lua:121: in global 'try'
        @programdir\actions\build\main.lua:142: in function <@programdir\actions\build\main.lua:108>
        (...tail calls...)
        [C]: in function 'xpcall'
        @programdir\core\base\utils.lua:280: in function 'sandbox/modules/utils.trycall'
        (...tail calls...)
        @programdir\core\base\task.lua:501: in function 'base/task.run'
        @programdir\core\main.lua:278: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:388: in function <@programdir\core\base\scheduler.lua:385>

下面的是日志
[mingw-w64] F:\vscode\111\helloworld>xmake f -vD
checking for mingw directory ... D:\program\Anaconda3\Library\mingw-w64
checkinfo: cannot runv(unzip.exe -v), No such file or directory
checking for unzip ... no
checking for 7z ... D:\tool\xmake\winenv\bin\7z
checking for git ... ok
checkinfo: cannot runv(gzip.exe --version), No such file or directory
checking for gzip ... no
finding Mingw from xmake ..
checking for xmake::Mingw ... no
finding Mingw from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding Mingw from conan ..
checking for Mingw ... no
note: the following packages were not found in any repository (check if they are spelled correctly):
  -> Mingw
error: @programdir\core\main.lua:280: stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:893]:
    [...modules\private\action\require\impl\install_packages.lua:739]:
    [@programdir\modules\private\action\require\install.lua:85]:
    [@programdir\actions\config\main.lua:424]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\base\task.lua:501]: in function 'run'
    [@programdir\core\main.lua:278]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:388]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:882: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:280: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:388: in function <@programdir\core\base\scheduler.lua:385>

[mingw-w64] F:\vscode\111\helloworld>xmake -vD
checking for mingw directory ... D:\program\Anaconda3\Library\mingw-w64
checkinfo: cannot runv(unzip.exe -v), No such file or directory
checking for unzip ... no
checking for 7z ... D:\tool\xmake\winenv\bin\7z
checking for git ... ok
checkinfo: cannot runv(gzip.exe --version), No such file or directory
checking for gzip ... no
finding Mingw from xmake ..
checking for xmake::Mingw ... no
finding Mingw from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding Mingw from conan ..
checking for Mingw ... no
note: the following packages were not found in any repository (check if they are spelled correctly):
  -> Mingw
error: @programdir\core\main.lua:280: @programdir\core\sandbox\modules\import\core\base\task.lua:65: stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:893]:
    [...modules\private\action\require\impl\install_packages.lua:739]:
    [@programdir\modules\private\action\require\install.lua:85]:
    [@programdir\actions\config\main.lua:424]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\base\task.lua:501]: in function 'run'
    [@programdir\core\sandbox\modules\import\core\base\task.lua:63]: in function 'run'
    [@programdir\actions\build\main.lua:134]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\base\task.lua:501]: in function 'run'
    [@programdir\core\main.lua:278]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:388]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:882: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:280: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:388: in function <@programdir\core\base\scheduler.lua:385>

### Expected Behavior

希望得到拉取远程工具链跟交叉编译的详细示例

**Comment by waruqi** [comment]
贴下 xmake.lua
