### ISSUE TITLE
对于cl.exe，-O2应比-Ox更快

### ISSUE THREAD

**Issue by lone-wolf-akela** [xmake-io/xmake#2809]
### Xmake 版本

xmake v2.7.1+master.5c0e53f91

### 操作系统版本和架构

windows 11

### 描述问题

根据代码：
https://github.com/xmake-io/xmake/blob/1bf418b749afd4abaeaf36574569e6ac4fc4b8d9/xmake/modules/core/tools/cl.lua#L164
https://github.com/xmake-io/xmake/blob/1bf418b749afd4abaeaf36574569e6ac4fc4b8d9/xmake/modules/core/tools/cl.lua#L165
xmake 将 cl.exe 在最大优化模式下设置为-Ox而非-O2。
根据微软文档 https://docs.microsoft.com/en-us/cpp/build/reference/ox-full-optimization?view=msvc-170 ：

> the /Ox compiler option enables only a subset of the speed optimization options enabled by /O2.

因此，这里faster和fastest的优化参数是否应该交换一下？

### 期待的结果

如上描述。

**Comment by waruqi** [comment]
似乎是，你可以来个 pr 过来

**Comment by waruqi** [comment]
改了
