### ISSUE TITLE
Qt: always compile .ui before running moc.

### ISSUE THREAD

**Issue by paul-reilly** [xmake-io/xmake#2814]
### Is your feature request related to a problem? Please describe.

As discussed on Discord, when doing a clean build of a Qt project with .ui form files, sometimes the build fails because `rule(qt.ui).before_buildcmd_file` and `rule(qt.moc). before_buildcmd_file` are run in parallel and ui_ files are not generated when needed.

### Describe the solution you'd like

For the ui_ files always to be generated when needed.

_(originally posted in xmake-repo, I closed that one)_

**Comment by waruqi** [comment]
try `xmake update -s github:xmake-io/xmake#rule`

**Comment by paul-reilly** [comment]
Wow, that was quick, thanks!

It's working with a clean build here on Manjaro and in CI on Ubuntu: https://github.com/paul-reilly/gideros/actions/runs/3059134920
