### ISSUE TITLE
当vcpkg里面的社区 triplet 名字不标准时无法安装包

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#2816]
### Xmake 版本

2.7.1

### 操作系统版本和架构

windows 11

### 描述问题

```
add_requires("vcpkg::pugixml")
```
配置平台为mingw
```
xmake f -p mingw
```
安装时会报错，这是因为，vcpkg里面社区版叫下面的名字
```
  x64-mingw-dynamic
  x64-mingw-static
```
而xmake默认安装的是 x64-mingw，这种可能得需要加个参数，能指定triplet

### 期待的结果

安装指定的包

**Comment by waruqi** [comment]
可以直接来个pr过来 https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/manager/vcpkg/install_package.lua

**Comment by waruqi** [comment]
我加上了 xmake update -s dev
