### ISSUE TITLE
错误的 compile_commands arguments \\\" 转义

### ISSUE THREAD

**Issue by q962** [xmake-io/xmake#2821]
### Xmake 版本

2.7.1

### 操作系统版本和架构

Linux demo-PC 5.10.50-amd64-desktop #0304 SMP Mon Jul 19 17:10:50 CST 2021 x86_64 GNU/Linux

### 描述问题

https://github.com/xmake-io/xmake/issues/1506 的修复我认为这是错误的。

我遇到了这个错误。

根据 https://clang.llvm.org/docs/JSONCompilationDatabase.html 

arguments 的值是传递给 execvp 的
command 的值是传递给 shell 的

json 自身需要一层转义。所以 
- `"-DKEY=\"VALUE\""` 被读取后传递给 execvp 就会变成 正确的字符串 `-DKEY="VALUE"`
- `"gcc -DKEY=\"VALUE\""` 被读取后传递给 shell 就会变成字符串 `gcc -DKEY="VALUE"` 到达预处理器就会变成 `VALUE` ，不是字符串
- `"gcc -DKEY=\\\"VALUE\\\""` 被读取后传递给 shell 就会变成字符串 `gcc -DKEY=\"VALUE\"` 到达预处理器就会变成 `"VALUE"` ，是字符串

```bash
$ echo -D="b"
-D=b
```

所以 arguments 只需要一层转义，而 command 需要二层转义。

### 期待的结果

```json
{
    "arguments" : ["gcc", "-DV=\"S\""]
}
```
or
```json
{
    "command" : ["gcc -DV=\\\"S\\\""]
}
```

**Comment by waruqi** [comment]
@Nats-ji any idea?

**Comment by Nats-ji** [comment]
he is right. issue in https://github.com/xmake-io/xmake/issues/1506 should be a bug from vscode side. Should revert the changes in https://github.com/xmake-io/xmake/pull/1508

**Comment by waruqi** [comment]
@q962 @Nats-ji Can you open a pr?
