### ISSUE TITLE
`xmake --version` specifies `dev`

### ISSUE THREAD

**Issue by vic1707** [xmake-io/xmake#2822]
### Is your feature request related to a problem? Please describe.

ATM it's impossible to know if I'm on dev branch or the last release from a `xmake --version`

on dev
```
xmake v2.7.1+202209131345, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, xmake.io
    
    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor
```

on 2.7.1
```
xmake v2.7.1+202209131345, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, xmake.io
    
    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor
```

### Describe the solution you'd like

instead of showing `xmake v2.7.1+202209131345` for the dev branch maybe show `xmake dev-<commit hash>` or something like that?

**Comment by waruqi** [comment]
it works for me, did you use `xmake update dev` to update dev version?

```console
$ xmake update dev
$ xmake --version
xmake v2.7.1+dev.46e28a1, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
```

**Comment by vic1707** [comment]
no, I used `xmake update -s dev ` which is the command you gave me on github 😅

**Comment by waruqi** [comment]
> no, I used `xmake update -s dev ` which is the command you gave me on github 😅

It only update lua scripts without git commit. It will be faster.

if you want to get dev commit, you can try `xmake update dev` to update all, the core binary will be also updated.

**Comment by vic1707** [comment]
Works great on linux but on my MacOS system it doesn't seem to be working, I think it's because it's downloading the new version to `~/.local/xmake` instead of `/opt/homebrew/bin/xmake` (I installed xmake with brew)
<img width="530" alt="image" src="https://user-images.githubusercontent.com/28602203/190367334-3ff1f151-01f1-4175-b87c-38a80262aa11.png">

**Comment by waruqi** [comment]
please do not use brew to install it. you should use onel-line script to install it. `bash <(curl -fsSL https://xmake.io/shget.text)
`

xmake/brew does not support `xmake update` to update self.

**Comment by vic1707** [comment]
with the source command the path to the executable is updated 👍 
maybe disable the usage of `xmake update` if it detect being a brew install to avoid this issue ?
