### ISSUE TITLE
Create a MacOS bundle in Swift

### ISSUE THREAD

**Issue by glcraft** [xmake-io/xmake#2835]
### Xmake Version

xmake v2.6.9+HEAD.22ecc01

### Operating System Version and Architecture

MacOS Monterey 12.6 (21G115)

### Describe Bug

Using the rule `xcode.bundle` in a swift project include the flag `-bundle` to ldflags, which does not exists in swiftc command line arguments

### Expected Behavior

Generate a bundle over a Swift source project.

### Project Configuration

add_rules("mode.debug", "mode.release")

target("screensaver-test")
    add_rules("xcode.bundle")
    set_languages("swift")
    add_files("src/*.swift")
    add_files("src/Info.plist")

### Additional Information and Error Logs

❯ xmake b -vD
checking for Xcode directory ... /Applications/Xcode.app
checking for Codesign Identity of Xcode ... Developer ID Application: EIG (6DB2STFQWW)
checking for SDK version of Xcode for macosx (arm64) ... 12.3
checking for Minimal target version of Xcode for macosx (arm64) ... 12.6
checkinfo: cannot runv(dmd --version), No such file or directory
checking for dmd ... no
checkinfo: cannot runv(ldc2 --version), No such file or directory
checking for ldc2 ... no
checkinfo: cannot runv(gdc --version), No such file or directory
checking for gdc ... no
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checking for xcrun -sdk macosx swiftc ... /usr/bin/xcrun -sdk macosx swiftc
checking for the swift compiler (sc) ... xcrun -sdk macosx swiftc
checking for /usr/bin/xcrun -sdk macosx swiftc ... ok
checking for flags (-O) ... ok
> xcrun -sdk macosx swiftc "-O" "-target" "arm64-apple-macos12.6" "-sdk" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk"
checking for xcrun -sdk macosx swiftc ... /usr/bin/xcrun -sdk macosx swiftc
checking for the swift linker (scld) ... xcrun -sdk macosx swiftc
[ 60%]: linking.release screensaver-test
"/usr/bin/xcrun -sdk macosx swiftc" -o build/macosx/arm64/release/screensaver-test build/.objs/screensaver-test/macosx/arm64/release/src/screensaver.swift.o -target arm64-apple-macos12.6 -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -Xlinker -s -lz -bundle
error: @programdir/modules/private/async/runjobs.lua:256: @programdir/actions/build/kinds/binary.lua:74: @programdir/core/sandbox/modules/os.lua:267: error: unknown argument: '-bundle'

stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:890]:
    [@programdir/core/sandbox/modules/os.lua:267]: in function 'runv'
    [@programdir/modules/core/tools/swiftc.lua:186]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/actions/build/kinds/binary.lua:74]: in function 'callback'
    [@programdir/modules/core/project/depend.lua:193]: in function 'on_changed'
    [@programdir/actions/build/kinds/binary.lua:55]: in function '_do_link_target'
    [@programdir/actions/build/kinds/binary.lua:102]:
    [@programdir/actions/build/kinds/binary.lua:129]: in function '_link_target'
    [@programdir/actions/build/kinds/binary.lua:157]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:232]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:117]: in function 'try'
    [@programdir/modules/private/async/runjobs.lua:218]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:388]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:890: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir/modules/private/async/runjobs.lua:256: in field 'catch'
        @programdir/core/sandbox/modules/try.lua:123: in global 'try'
        @programdir/modules/private/async/runjobs.lua:218: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:388: in function <@programdir/core/base/scheduler.lua:385>

**Comment by glcraft** [comment]
After some researchs, it seems that swift bundle does not work like C++ and objc use to do. 
In swift, you have to create a Package.swift source file which acts like a manifest file

https://www.swift.org/package-manager/#packages
https://www.fabrizioduroni.it/2020/10/19/swift-package-manager-resources/
https://www.swiftbysundell.com/articles/building-a-command-line-tool-using-the-swift-package-manager/

**Comment by glcraft** [comment]
There is something interesting : the Swift Package Manager can [init a package](https://www.swift.org/getting-started/#using-the-package-manager) like xmake does. 

It could be interesting to relate SPM initializer to xmake with `xmake create -l swift`

**Comment by waruqi** [comment]
I have supported it, just change `-bundle` to `-Xlinker -bundle` for swiftc.

xmake update -s dev

**Comment by glcraft** [comment]
The correction works fine 👍
