### ISSUE TITLE
Xmake uses the wrong compiler version when using MSVC 2022

### ISSUE THREAD

**Issue by p3rl** [xmake-io/xmake#2842]
### Xmake Version

2.7.1

### Operating System Version and Architecture

Windows 10

### Describe Bug

We have a project using windows specific header files, i.e. atlfile.h. This file is located under:
```
Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\atlmfc\include\atlfile.h
```
Configuring the project outputs:
```
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.32.31335
```

The project fails to compile with an error message about missing include `atlfile.h`. This works fine using Xmake version `2.6.4`

### Expected Behavior

Xmake should be able to choose the latest compiler version after clearing any xmake cache(s).

**Comment by waruqi** [comment]
can you try 

```
xmake g -c
xmake f -c
```

if it still do not work, you can run `xmake l detect.sdks.find_vstudio` and let me see the output

**Comment by waruqi** [comment]
can you try 

```
xmake g -c
xmake f -c
```

if it still do not work, you can run `xmake l detect.sdks.find_vstudio` and let me see the output

**Comment by waruqi** [comment]
can you update to dev and try it again?

```console
xmake update dev
xmake g -c
xmake f -c
```
