### ISSUE TITLE
注册表读取出现问题

### ISSUE THREAD

**Issue by SaeruHikari** [xmake-io/xmake#2860]
### Xmake 版本

2.7.1

### 操作系统版本和架构

Windows 11 21H2

### 描述问题

find_qt 中读取注册表项分析 SDK 路径时获取值失败：

![@589(}WVP}NV6SZ6~`90DLB](https://user-images.githubusercontent.com/39457738/191907513-91f95042-4ee5-4752-860e-035b992ca9a9.png)

![VLZO{~AKCHH`Y_PK2{{UE2L](https://user-images.githubusercontent.com/39457738/191907520-2e4d97b9-03ec-4507-878a-93b75a392d5d.png)

使用内建脚本 winos.registry_query 时显示 error：

![O~LS94Z38N8Q8M(72D UQMO](https://user-images.githubusercontent.com/39457738/191907633-d3c03ee2-bcf6-4a7b-8715-31ec7c40a872.png)

### 期待的结果

可以正确查询注册表值并找到 Qt SDK 安装路径

**Comment by waruqi** [comment]
全量更新下 再试试 xmake update dev
