### ISSUE TITLE
生成compile_commands.json缺少add_includedirs的依赖

### ISSUE THREAD

**Issue by featherfly** [xmake-io/xmake#2867]
### Xmake 版本

2.7.1

### 操作系统版本和架构

windows11 x64

### 描述问题

生成compile_commands.json缺少add_includedirs的依赖，导致vscode的clangd插件语法提示出不来
能够使用xmake正常编译和运行，但是在vscode中clangd的语法提示不能找到使用add_includedirs的第三方库
查看了compile_commands.json，发现没有add_includedirs加入的路径

### 期待的结果

生成的compile_commands.json能够包含add_includedirs加入的依赖

### 工程配置

add_rules("mode.debug", "mode.release")

add_links("$(env OPENCV_LINK_PATHS)")
add_linkdirs("$(env OPENCV_LINK_LIBS)\\lib")
add_includedirs("$(env OPENCV_INCLUDE_PATHS)")
// add_includedirs("Y:\\soft\\programe\\runtime\\opencv\\4.6.0\\build\\include")

target("rectangle")
    set_kind("binary")
    add_files("src/rectangle/*.cpp")

**Comment by waruqi** [comment]
这边测试可以，没发复现问题

```console
$ OPENCV_INCLUDE_PATHS=/tmp/opencv xmake project -k compile_commands
create ok!
ruki-2:test6 ruki$ cat ./compile_commands.json
[
{
  "directory": "/private/tmp/test6",
  "arguments": ["/usr/bin/xcrun -sdk macosx clang", "-c", "-Qunused-arguments", "-target", "x86_
64-apple-macos11.4", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.p
latform/Developer/SDKs/MacOSX11.3.sdk", "-fvisibility=hidden", "-fvisibility-inlines-hidden", "-
O3", "-I/tmp/opencv", "-DNDEBUG", "-o", "build/.objs/test6/macosx/x86_64/release/src/main.cpp.o"
, "src/main.cpp"],
  "file": "src/main.cpp"
}]
```

**Comment by featherfly** [comment]
文件中找到了，没有语法提示应该是其他的问题
