### ISSUE TITLE
spdlog still install install fmt dependencies internally.

### ISSUE THREAD

**Issue by fonqL** [xmake-io/xmake#2869]
### Xmake 版本

2.7.1

### 操作系统版本和架构

Ubuntu 22.04 on Win10 WSL

### 描述问题

 [传递额外的编译信息到包](https://xmake.io/#/zh-cn/package/remote_package?id=%e4%bc%a0%e9%80%92%e9%a2%9d%e5%a4%96%e7%9a%84%e7%bc%96%e8%af%91%e4%bf%a1%e6%81%af%e5%88%b0%e5%8c%85)

> 这个时候，我们可以通过在外层项目xmake.lua提前通过add_requires添加fmt包（这个时候你可以设置各种自己的配置）， 确保spdlog在在安装之前，fmt已经通过add_requires的配置完成了安装，那么在安装spdlog的时候，就会自动检测到，并直接使用，不会在内部继续安装fmt依赖。

但是我输入命令后发现内部还是会安装依赖，似乎是因为依赖的fmt的header_only的配置和fmt默认配置不一样

```lua
add_rules("mode.debug", "mode.release")
set_toolchains("clang")
set_languages("c++17")
set_warnings("all")

add_requires("fmt")
add_requires("spdlog",{configs = {fmt_external = true}})

target("demo")
    set_kind("binary")
    add_files("src/main.cpp")

```

```bash
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> fmt#1 9.1.0 [toolchains:"clang", header_only:y, from:spdlog]
  -> spdlog v1.10.0 [toolchains:"clang", fmt_external:y]
please input: y (y/n/m)
```

### 期待的结果

与文档一致

**Comment by waruqi** [comment]
> 这个时候，我们可以通过在外层项目xmake.lua提前通过add_requires添加fmt包（这个时候你可以设置各种自己的配置）， 确保spdlog在在安装之前，fmt已经通过add_requires的配置完成了安装，那么在安装spdlog的时候，就会自动检测到，并直接使用，不会在内部继续安装fmt依赖。

> 但是我输入命令后发现内部还是会安装依赖，似乎是因为依赖的fmt的header_only的配置和fmt默认配置不一样

这个描述是很早期的文档，后来忘记更新了，现在外层的 fmt 和内部的 fmt 如果配置不同 是互不影响的两个不同的包，没有任何关联关系。。就是要装两遍的。。

如果想复用，除非两个 fmt 配置完全相同。。

几种做法：
1. 直接删了外面的 fmt ，反正 spdlog 也会引入 fmt ，没必要外面再去配一遍
2. 将外面的 fmt 配置成内部 fmt 相同配置，`add_requires("fmt", {configs = {header_only = true}})`
3. 将内部的 fmt 配置成跟外面的 fmt 相同的配置，`add_requireconfs("spdlog.fmt", {configs = {header_only = false}})`

**Comment by fonqL** [comment]
ok。
改内部配置是不是还要加个override？
`add_requireconfs("spdlog.fmt",{override=true,configs={header_only=false}})`
我是先这样解决了，不然修改不了内部的配置
