### ISSUE TITLE
add_requires 改变configs参数后第一次重编译要求重新install产生的系列行为异常

### ISSUE THREAD

**Issue by fy0** [xmake-io/xmake#287]
这里其实有三个问题

例如，一开始config里面是a=1，编译通过。
改成 a = 2 后，再次编译。
```
add_requires('libuv', {config = {a = 2}})
```

这时要求重新下载 libuv 1.24.0（实际上要求重新下载存在的源码本身就是一个问题，这是**问题一**）
```cmd
>xmake
checking for the Microsoft Visual Studio (x64) version ... 2017
note: try installing these packages (pass -y to skip confirm)?
  -> libuv v1.24.0
please input: y (y/n)
```

来看接下来，在输入y之后，进行了重新编译。这个结果是正确的。

如果输入非y，那么存在以下两个问题：

**问题二**：重编译阶段被跳过，使用上一次的config配置

**问题三**：再次运行xmake命令，此时xmake会认为config已经应用，而不会再次要求用户进行重新下载源码和重编译。

**Comment by waruqi** [comment]
> 这时要求重新下载 libuv 1.24.0（实际上要求重新下载存在的源码本身就是一个问题，这是问题一）

除非version变动，单纯configs变动仅会rebuild and reinstall包 不会重新下载的

那个提示信息仅仅提示用户要重装下，但是下载文件有缓存的

之后如果看到下载进度条信息，这个是显示上有点误导，其实只是重新unzip了一下，所以下载进度会很快过掉。(这个提示信息可以之后改进下)

关于 问题二，三的用户取消install的情况 我暂时还没处理，之后改进下

**Comment by waruqi** [comment]
问题一已改进（dev）：下载提示误导我改进了下，如果走缓存没去实际下载的话，download ... ok 那行提示信息我就不显示了，避免误导用户。

**Comment by waruqi** [comment]
问题2， 问题3 我也已经改进过了。。
