### ISSUE TITLE
add_requires的on_install触发时机有问题

### ISSUE THREAD

**Issue by fy0** [xmake-io/xmake#288]
如果add_requires()的第二个参数中没有config或者为{}，那么除了第一次之外，不会经过on_install。
而在这之后的缓存好像也存在问题。
以这个文件为例，on_install中存在默认行为。

https://github.com/tboox/xmake-repo/blob/a2a415a45d5877c785ef74f79acee1430b662f9d/packages/l/libuv/xmake.lua

缓存问题是基于repo本身的xmake文件被修改的基础上发生的：
已知存在一个缓存机制，对config相同的编译结果进行二进制缓存。
但可以明显看出，xmakefile本身的改变并不影响缓存结果……也就是说如果默认的编译选项发生变更，那么缓存不会更新。

另外就是每一种不同的config都会视为不同的编译进行缓存，即使输入的选项压根毫无意义。我认为应该让xmake-repo中的项目自我声明有效的选项和可选值。避免这样的浪费发生。

**Comment by waruqi** [comment]
> 如果add_requires()的第二个参数中没有config或者为{}，那么除了第一次之外，不会经过on_install。

这个正常逻辑，之前configs为空装过一次了，第二次还是空，就没必要重复install了

> 但可以明显看出，xmakefile本身的改变并不影响缓存结果……

这块之前就考虑到了，只是一直没时间处理，所以要是还不支持根据repo的xmake.lua变动进行缓存更新，这块请耐心等待


> 另外就是每一种不同的config都会视为不同的编译进行缓存，即使输入的选项压根毫无意义。我认为应该让xmake-repo中的项目自我声明有效的选项和可选值。避免这样的浪费发生。

这个配置选项的描述和约束，之后是会做的，描述用于提示用户有哪些可用配置，约束限制无效配置，输入无效配置就直接提示错误了，让用户修改，所以本身跟缓存策略没啥关系，只是因为当前还没做约束而已

之后会跟xmake --help有个包配置参数说明提示和约束检测的

但是由于目前时间不多，所以进度上会慢些，可能要等上一段时间才能实现掉

**Comment by waruqi** [comment]
> 但可以明显看出，xmakefile本身的改变并不影响缓存结果……

repo里面的xmake.lua变动，我暂时不打算做自动更新cache支持

1. 因为repo里面某个包如果已经安装成功，即使之后的xmake.lua有所改进，也是没必要再去更新重装这个包的，用户如果有需要可以自行卸载和重装指定包。
2. 像homebrew/vcpkg/conan目前我也没看到，由于某个包的描述规则更新，会自动去重装的。。
3. 只有repo的维护者才会需要不断的更新xmake.lua去尝试重装包，那么对于这些少数维护者，自己手动重装下就行了，并没有多少工作量。

> 另外就是每一种不同的config都会视为不同的编译进行缓存，即使输入的选项压根毫无意义。我认为应该让xmake-repo中的项目自我声明有效的选项和可选值。避免这样的浪费发生。

这块，我dev分支已经彻底改进过了，对包的配置，加上了参数配置，以及强约束规则，并且对安装的hash目录做了彻底改进，不会动不动就产生一个新目录。。见 #284

**Comment by waruqi** [comment]
如果要测试的话，暂时需要添加dev分支的xmake-repo版本，`xmake repo --add local-repo https://github.com/xmake-io/xmake-repo.git dev`
