### ISSUE TITLE
compile_flags.txt 缺少 add_packages 目标的 -I

### ISSUE THREAD

**Issue by q962** [xmake-io/xmake#2883]
### Xmake 版本

2.7.1

### 操作系统版本和架构

Linux demo-PC 5.10.50-amd64-desktop #0304 SMP Mon Jul 19 17:10:50 CST 2021 x86_64 GNU/Linux

### 描述问题

compile_flags.txt 缺少 add_packages 依赖项的 `-I` 目录
输出结果只有 `add_includedirs` 的值

生成的 compile_commands.json 包含add_packages 依赖项的结果

### 期待的结果

正确包含 add_packages  依赖项的头文件目录

**Comment by waruqi** [comment]
更新到 dev 试试，xmake update -s dev

**Comment by q962** [comment]
ok

**Comment by q962** [comment]
有一个新问题，似乎不允许存在空格分隔符。
提示找不到文件，删除空格就可以。

**Comment by waruqi** [comment]
再试试

**Comment by q962** [comment]
空格去了，应该没问题了
