### ISSUE TITLE
Build fails because generated `.pch` file can't be found

### ISSUE THREAD

**Issue by Qudix** [xmake-io/xmake#2885]
### Xmake Version

2.7.1+dev.d4b5d6244

### Operating System Version and Architecture

Windows 11

### Describe Bug

Often in a bigger project, the build fails because `.cpp` files cannot open the precompiled header:
![image](https://user-images.githubusercontent.com/17361645/193044323-3ddecd20-adf2-47ba-a91a-6a1fd6f925b7.png)

The mentioned file does not "exist" because the generated `.pch` doesn't seem to get renamed:
![image](https://user-images.githubusercontent.com/17361645/193044941-814fc5d5-1f1c-429c-bff9-ca930e7ddf52.png)

And it's not because my precompiled header is called `pch.h`, I already tried various other names to no avail.

### Expected Behavior

The generated `.pch` should be renamed accordingly so `.cpp` files can find it.

### Project Configuration

Reproducible test: [pch-test.zip](https://github.com/xmake-io/xmake/files/9675107/pch-test.zip)

### Additional Information and Error Logs

I've run this test on the latest dev commit, but this problem has been occurring long before intermittently.

**Comment by waruqi** [comment]
I have fixed it, you can try it again. `xmake update -s dev`

It is caused by cache.

**Comment by Qudix** [comment]
It works.
