### ISSUE TITLE
`add_repositories` should try the `main` branch if `master` doesn't exist

### ISSUE THREAD

**Issue by Qudix** [xmake-io/xmake#2886]
### Xmake Version

2.7.1

### Operating System Version and Architecture

Windows 11

### Describe Bug

A while back Github changed the default branch from `master` to `main` for reasons I won't get into. Because of this, many new repos only have `main` or have switched to it. `add_repositories` allows you to set the branch yourself, but ideally it should handle this specific situation automatically.

### Expected Behavior

`add_repositories` should consider the `main` alongside the `master` branch automatically. Consequently, I'd imagine this would affect `git` operations in general?

**Comment by waruqi** [comment]
you can try dev branch. https://github.com/xmake-io/xmake/issues/2844

xmake update -s dev

**Comment by Qudix** [comment]
Oh, it was fixed in dev. Sorry.
