### ISSUE TITLE
binary package should ignore the toolchain setting

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2889]
### Xmake 版本

2.7.1

### 操作系统版本和架构

Windows 10

### 描述问题

如图所示，binary的python也区分了不同toolchain；但实际上toolchain设置不会对python解释器的使用有任何影响，这会导致不必要的重复下载。
![image](https://user-images.githubusercontent.com/42310255/193257646-0d78be76-720e-4cf9-8cb7-461ab634d62c.png)

### 期待的结果

对binary package忽略toolchain不同；类似headeronly package

**Comment by waruqi** [comment]
交叉编译，android 平台等，也有可能需要切 toolchain 编译对应的 binary 丢给设备上跑，只有 host binary 才不需要

**Comment by waruqi** [comment]
再试试
