### ISSUE TITLE
mingw使用boost包安装失败，需要msvc

### ISSUE THREAD

**Issue by 233lol** [xmake-io/xmake#2896]
### Xmake 版本

2.7.1

### 操作系统版本和架构

Windows 10

### 描述问题

xmake f -p mingw -m release
checking for mingw directory ... C:/Users/user/scoop/apps/gcc-llvm-ucrt/current
checking for Microsoft Visual Studio (x86_64) version ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> boost 1.80.0
please input: y (y/n/m)

  => install boost 1.80.0 .. failed

'"cl"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
找不到文件
 not find "vswhere"
Call_If_Exists "..\bin\VCVARS32.BAT"

Using 'msvc' toolset.

### 期待的结果

解决windows下mingw64安装boost问题
解决使用mingw还是检查Microsoft Visual Studio

### 工程配置

xmake f -p mingw -m release

add_rules("mode.debug", "mode.release")
add_requires("fmt","vcpkg::fftw3","boost")
target("hello")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("fmt","vcpkg::fftw3","boost")

{
    __toolchains_mingw_x86_64 = {
        "envs",
        "mingw",
        "yasm",
        "nasm",
        "fasm",
        "go"
    },
    arch = "x86_64",
    buildir = "build",
    ccache = true,
    host = "windows",
    kind = "static",
    mingw = "C:/Users/user/scoop/apps/gcc-llvm-ucrt/current",
    mode = "release",
    ndk_stdcxx = true,
    network = "public",
    plat = "mingw",
    proxy = "http://127.0.0.1:8889",
    proxy_pac = "pac.lua",
    theme = "default"
}

**Comment by 233lol** [comment]
> xmake f -p mingw -m release

xmake f -p mingw -m releas -vD
checking for architecture ... x86_64
checking for mingw directory ... C:/Users/user/scoop/apps/mingw-winlibs-llvm-ucrt/current
checking for unzip ... ok
checking for git ... ok
checking for gzip ... ok
checking for tar ... ok
git rev-parse HEAD
checking for cmake ... no
checkinfo: cannot runv(vswhere.exe -?), No such file or directory
checking for vswhere.exe ... no
checkinfo: cannot runv(vswhere.exe -?), No such file or directory
checking for vswhere ... no
checking for Microsoft Visual Studio (x86_64) version ... no
checking for cmake ... ok
finding fmt from xmake ..
checking for xmake::fmt ... fmt 9.1.0
finding fftw3 from vcpkg ..
checking for pkg-config ... ok
checking for vcpkg::fftw3 ... fftw3 3.3.10
finding boost from xmake ..
checking for xmake::boost ... no
finding boost from vcpkg ..
finding boost from conan ..
checking for boost ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> boost 1.80.0
please input: y (y/n/m)
y
checking for ping ... ok
pinging for the host(github.com) ... 65535 ms
pinging for the host(boostorg.jfrog.io) ... 65535 ms
checking for 7z ... C:\Users\user\scoop\apps\xmake\current\winenv\bin\7z
C:\Users\user\scoop\apps\xmake\current\winenv\bin\7z x -y boost_1_80_0.tar.bz2 -oC:\Users\user\AppData\Local\Temp\.xmake\221008\_D252D17D3E2F41308D30B56FE0A2BE40.tar

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 115869904 bytes (111 MiB)

Extracting archive: boost_1_80_0.tar.bz2
--
Path = boost_1_80_0.tar.bz2
Type = bzip2

Everything is Ok

Size:       771205120
Compressed: 115869904
C:\Users\user\scoop\apps\xmake\current\winenv\bin\7z x -y C:\Users\user\AppData\Local\Temp\.xmake\221008\_D252D17D3E2F41308D30B56FE0A2BE40.tar\boost_1_80_0.tar -osource.tmp

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 771205120 bytes (736 MiB)

Extracting archive: C:\Users\user\AppData\Local\Temp\.xmake\221008\_D252D17D3E2F41308D30B56FE0A2BE40.tar\boost_1_80_0.tar
--
Path = C:\Users\user\AppData\Local\Temp\.xmake\221008\_D252D17D3E2F41308D30B56FE0A2BE40.tar\boost_1_80_0.tar
Type = tar
Physical Size = 771205120
Headers Size = 42336256
Code Page = UTF-8

Everything is Ok

Folders: 6752
Files: 72069
Size:       710164332
Compressed: 771205120
checking for x86_64-w64-mingw32-g++ ... C:\Users\user\scoop\apps\mingw-winlibs-llvm-ucrt\current\bin\x86_64-w64-mingw32-g++
checking for the c++ compiler (cxx) ... x86_64-w64-mingw32-g++
bootstrap.bat --prefix=C:\Users\user\AppData\Local\.xmake\packages\b\boost\1.80.0\63db9d185548414b9234b43ce3362547 --libdir=C:\Users\user\AppData\Local\.xmake\packages\b\boost\1.80.0\63db9d185548414b9234b43ce3362547\lib --without-icu
Building Boost.Build engine
LOCALAPPDATA=C:\Users\user\AppData\Local
could not find "vswhere"
Call_If_Exists "..\bin\VCVARS32.BAT"
###
### Using 'msvc' toolset.
###

C:\Users\user\AppData\Local\.xmake\cache\packages\2210\b\boost\1.80.0\source\tools\build\src\engine>"cl" /nologo /MP /MT /TP /Feb2 /wd4996 /O2 /GL /EHsc   -DNDEBUG  builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp execnt.cpp execunix.cpp filent.cpp filesys.cpp fileunix.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathnt.cpp pathsys.cpp pathunix.cpp regexp.cpp rules.cpp scan.cpp search.cpp jam_strings.cpp startup.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp /link kernel32.lib advapi32.lib user32.lib
'"cl"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\user\AppData\Local\.xmake\cache\packages\2210\b\boost\1.80.0\source\tools\build\src\engine>dir *.exe
 驱动器 C 中的卷是 系统
 卷的序列号是 5F98-7F6F

 C:\Users\user\AppData\Local\.xmake\cache\packages\2210\b\boost\1.80.0\source\tools\build\src\engine 的目录

找不到文件

Failed to build Boost.Build engine.

error: @programdir\core\sandbox\modules\os.lua:372: execv(bootstrap.bat --prefix=C:\Users\user\AppData\Local\.xmake\packages\b\boost\1.80.0\63db9d185548414b9234b43ce3362547 --libdir=C:\Users\user\AppData\Local\.xmake\packages\b\boost\1.80.0\63db9d185548414b9234b43ce3362547\lib --without-icu) failed(1)
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:890]:
    [@programdir\core\sandbox\modules\os.lua:372]:
    [@programdir\core\sandbox\modules\os.lua:285]: in function 'vrunv'
    [...xmake\repositories\xmake-repo\packages\b\boost\xmake.lua:147]: in function 'script'
    [...dir\modules\private\action\require\impl\utils\filter.lua:125]: in function 'call'
    [...\modules\private\action\require\impl\actions\install.lua:299]:

  => install boost 1.80.0 .. failed
error: @programdir\modules\private\async\runjobs.lua:256: ...\modules\private\action\require\impl\actions\install.lua:399: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:890]:
    [...\modules\private\action\require\impl\actions\install.lua:399]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:263]:
    [...modules\private\action\require\impl\install_packages.lua:479]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:232]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:890: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\modules\private\async\runjobs.lua:256: in field 'catch'
        @programdir\core\sandbox\modules\try.lua:123: in global 'try'
        @programdir\modules\private\async\runjobs.lua:218: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:388: in function <@programdir\core\base\scheduler.lua:385>

**Comment by waruqi** [comment]
有点怪，我这里并不会去检测 vs

你先搞个没有包的简单工程试试呢，贴下 logs

```console
xmake create test
xmake f -p mingw -c -vD
xmake -rvD
```

![image](https://user-images.githubusercontent.com/151335/194706572-90671388-578e-471d-bb9d-9c91c0219626.png)

**Comment by 233lol** [comment]
> 

 xmake f -p mingw -c -vD
checking for architecture ... x86_64
checking for mingw directory ... C:/Users/user/scoop/apps/mingw-winlibs-llvm-ucrt/current
configure
{
    ccache = true
    clean = true
    kind = static
    theme = default
    proxy_pac = pac.lua
    plat = mingw
    buildir = build
    arch = x86_64
    mingw = C:/Users/user/scoop/apps/mingw-winlibs-llvm-ucrt/current
    proxy = http://127.0.0.1:8889
    ndk_stdcxx = true
    host = windows
    network = public
    mode = release
}
xmake -rvD
checking for x86_64-w64-mingw32-g++ ... C:\Users\user\scoop\apps\mingw-winlibs-llvm-ucrt\current\bin\x86_64-w64-mingw32-g++
checking for the c++ compiler (cxx) ... x86_64-w64-mingw32-g++
checking for C:\Users\user\scoop\apps\mingw-winlibs-llvm-ucrt\current\bin\x86_64-w64-mingw32-g++ ... ok
checking for flags (-fvisibility-inlines-hidden) ... ok
> x86_64-w64-mingw32-g++ "-fvisibility-inlines-hidden"
checking for flags (-O3) ... ok
> x86_64-w64-mingw32-g++ "-O3"
checking for flags (-DNDEBUG) ... ok
> x86_64-w64-mingw32-g++ "-DNDEBUG"
[ 25%]: cache compiling.release src\main.cpp
C:\Users\user\scoop\apps\mingw-winlibs-llvm-ucrt\current\bin\x86_64-w64-mingw32-g++ -c -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG -o build\.objs\test\mingw\x86_64\release\src\main.cpp.obj src\main.cpp
checking for flags (-MMD -MF) ... ok
> x86_64-w64-mingw32-g++ "-MMD" "-MF" "C:\Users\user\AppData\Local\Temp\.xmake\221009\_CDAF68EFB4924F4084525266F10F3950"
checking for flags (-fdiagnostics-color=always) ... ok
> x86_64-w64-mingw32-g++ "-fdiagnostics-color=always"
checking for x86_64-w64-mingw32-g++ ... C:\Users\user\scoop\apps\mingw-winlibs-llvm-ucrt\current\bin\x86_64-w64-mingw32-g++
checking for the linker (ld) ... x86_64-w64-mingw32-g++
[ 50%]: linking.release test.exe
C:\Users\user\scoop\apps\mingw-winlibs-llvm-ucrt\current\bin\x86_64-w64-mingw32-g++ -o build\mingw\x86_64\release\test.exe build\.objs\test\mingw\x86_64\release\src\main.cpp.obj -m64 -s

build cache stats:
cache directory: build\.build_cache
cache hit rate: 0%
cache hit: 0
cache miss: 1
new cached files: 1
remote cache hit: 0
remote new cached files: 0
preprocess failed: 0
compile fallback count: 0

[100%]: build ok!

**Comment by 233lol** [comment]
我是用winlibs的mingw而不是msys2下的

**Comment by waruqi** [comment]
> > 
> 
> xmake f -p mingw -c -vD checking for architecture ... x86_64 checking for mingw directory ... C:/Users/user/scoop/apps/mingw-winlibs-llvm-ucrt/current configure { ccache = true clean = true kind = static theme = default proxy_pac = pac.lua plat = mingw buildir = build arch = x86_64 mingw = C:/Users/user/scoop/apps/mingw-winlibs-llvm-ucrt/current proxy = http://127.0.0.1:8889 ndk_stdcxx = true host = windows network = public mode = release } xmake -rvD checking for x86_64-w64-mingw32-g++ ... C:\Users\user\scoop\apps\mingw-winlibs-llvm-ucrt\current\bin\x86_64-w64-mingw32-g++ checking for the c++ compiler (cxx) ... x86_64-w64-mingw32-g++ checking for C:\Users\user\scoop\apps\mingw-winlibs-llvm-ucrt\current\bin\x86_64-w64-mingw32-g++ ... ok checking for flags (-fvisibility-inlines-hidden) ... ok
> 
> > x86_64-w64-mingw32-g++ "-fvisibility-inlines-hidden"
> > checking for flags (-O3) ... ok
> > x86_64-w64-mingw32-g++ "-O3"
> > checking for flags (-DNDEBUG) ... ok
> > x86_64-w64-mingw32-g++ "-DNDEBUG"
> > [ 25%]: cache compiling.release src\main.cpp
> > C:\Users\user\scoop\apps\mingw-winlibs-llvm-ucrt\current\bin\x86_64-w64-mingw32-g++ -c -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG -o build.objs\test\mingw\x86_64\release\src\main.cpp.obj src\main.cpp
> > checking for flags (-MMD -MF) ... ok
> > x86_64-w64-mingw32-g++ "-MMD" "-MF" "C:\Users\user\AppData\Local\Temp.xmake\221009_CDAF68EFB4924F4084525266F10F3950"
> > checking for flags (-fdiagnostics-color=always) ... ok
> > x86_64-w64-mingw32-g++ "-fdiagnostics-color=always"
> > checking for x86_64-w64-mingw32-g++ ... C:\Users\user\scoop\apps\mingw-winlibs-llvm-ucrt\current\bin\x86_64-w64-mingw32-g++
> > checking for the linker (ld) ... x86_64-w64-mingw32-g++
> > [ 50%]: linking.release test.exe
> > C:\Users\user\scoop\apps\mingw-winlibs-llvm-ucrt\current\bin\x86_64-w64-mingw32-g++ -o build\mingw\x86_64\release\test.exe build.objs\test\mingw\x86_64\release\src\main.cpp.obj -m64 -s
> 
> build cache stats: cache directory: build.build_cache cache hit rate: 0% cache hit: 0 cache miss: 1 new cached files: 1 remote cache hit: 0 remote new cached files: 0 preprocess failed: 0 compile fallback count: 0
> 
> [100%]: build ok!

我看这个不是挺正常的么，也没检测 vs 啥的。

为啥你上面的 logs 不一样，你 xmake.lua 里面加了 set_toolchains ?

**Comment by 233lol** [comment]
> > > 
> > 
> > 
> > xmake f -p mingw -c -vD checking for architecture ... x86_64 checking for mingw directory ... C:/Users/user/scoop/apps/mingw-winlibs-llvm-ucrt/current configure { ccache = true clean = true kind = static theme = default proxy_pac = pac.lua plat = mingw buildir = build arch = x86_64 mingw = C:/Users/user/scoop/apps/mingw-winlibs-llvm-ucrt/current proxy = http://127.0.0.1:8889 ndk_stdcxx = true host = windows network = public mode = release } xmake -rvD checking for x86_64-w64-mingw32-g++ ... C:\Users\user\scoop\apps\mingw-winlibs-llvm-ucrt\current\bin\x86_64-w64-mingw32-g++ checking for the c++ compiler (cxx) ... x86_64-w64-mingw32-g++ checking for C:\Users\user\scoop\apps\mingw-winlibs-llvm-ucrt\current\bin\x86_64-w64-mingw32-g++ ... ok checking for flags (-fvisibility-inlines-hidden) ... ok
> > > x86_64-w64-mingw32-g++ "-fvisibility-inlines-hidden"
> > > checking for flags (-O3) ... ok
> > > x86_64-w64-mingw32-g++ "-O3"
> > > checking for flags (-DNDEBUG) ... ok
> > > x86_64-w64-mingw32-g++ "-DNDEBUG"
> > > [ 25%]: cache compiling.release src\main.cpp
> > > C:\Users\user\scoop\apps\mingw-winlibs-llvm-ucrt\current\bin\x86_64-w64-mingw32-g++ -c -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG -o build.objs\test\mingw\x86_64\release\src\main.cpp.obj src\main.cpp
> > > checking for flags (-MMD -MF) ... ok
> > > x86_64-w64-mingw32-g++ "-MMD" "-MF" "C:\Users\user\AppData\Local\Temp.xmake\221009_CDAF68EFB4924F4084525266F10F3950"
> > > checking for flags (-fdiagnostics-color=always) ... ok
> > > x86_64-w64-mingw32-g++ "-fdiagnostics-color=always"
> > > checking for x86_64-w64-mingw32-g++ ... C:\Users\user\scoop\apps\mingw-winlibs-llvm-ucrt\current\bin\x86_64-w64-mingw32-g++
> > > checking for the linker (ld) ... x86_64-w64-mingw32-g++
> > > [ 50%]: linking.release test.exe
> > > C:\Users\user\scoop\apps\mingw-winlibs-llvm-ucrt\current\bin\x86_64-w64-mingw32-g++ -o build\mingw\x86_64\release\test.exe build.objs\test\mingw\x86_64\release\src\main.cpp.obj -m64 -s
> > 
> > 
> > build cache stats: cache directory: build.build_cache cache hit rate: 0% cache hit: 0 cache miss: 1 new cached files: 1 remote cache hit: 0 remote new cached files: 0 preprocess failed: 0 compile fallback count: 0
> > [100%]: build ok!
> 
> 我看这个不是挺正常的么，也没检测 vs 啥的。
> 
> 为啥你上面的 logs 不一样，你 xmake.lua 里面加了 set_toolchains ?

添加boost之后就回之前的样子了

**Comment by waruqi** [comment]
试了下，这边可以装也没啥问题，但是 boost 编译其实还是用的 msvc 

按理应该切到 mingw gcc 了，https://github.com/xmake-io/xmake-repo/blob/5db54f8c833697bc11efe961ec460f5afaa035b6/packages/b/boost/xmake.lua#L133

但是没生效，这个要调 boost 包，暂时没空搞，你可以先自己研究下 boost 为啥一直使用 msvc ，没用 mingw

**Comment by 233lol** [comment]
> 

if is_host("windows") then
            import("core.tool.toolchain")
            local runenvs = toolchain.load("msvc"):runenvs()
            os.vrunv("bootstrap.bat", bootstrap_argv, {envs = runenvs})
144行，host是windows，直接就msvc了

**Comment by waruqi** [comment]
可以来个 pr 过来

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-repo/pull/1809
