### ISSUE TITLE
Remove empty folder in directory tree after unistalling a shared library

### ISSUE THREAD

**Issue by gffrnl** [xmake-io/xmake#2901]
Hello friends, I have the following simple xmake.lua:

````
add_rules("mode.debug", "mode.release")

target("pide")
    set_languages("cxx20")
    set_kind("shared")
    add_includedirs("include", {public = true})

    add_headerfiles("include/pide/*.h", {prefixdir = "pide"})
    add_files("src/*.cpp")

target("pide_demo")
    set_languages("cxx20")
    set_kind("binary")
    add_deps("pide")
    add_files("pide_demo/main.cpp")
````

**I'm on linux**. After uninstalling the shared library the prefix folder `pide` created inside `/usr/local/include/` is not removed (uninstalling leave `pide` an empty folder), despite that the header files and the shared library are properly removed. I would like this folder to be removed on uninstall so it doesn't contaminate my directory tree.

A friend from xmake's discord suggested substitute `add_headerfiles("include/pide/*.h", {prefixdir = "pide"})` by `add_headerfiles("include/(pide/*.h)")`, but it did not work too. So a conclusion at the conversation at discord was that this looks like a missing feature.

### Describe the solution you'd like

If it's a missing feature, I'd like folders created to contain header files within the include directory to be removed on uninstall of libraries created with xmake so these empty folders does not contaminate the directory tree.

**Comment by waruqi** [comment]
try dev version, `xmake update -s dev`

**Comment by gffrnl** [comment]
> try dev version, `xmake update -s dev`

Thank you! But did not work. Do I need to pass some additional flag to `sudo xmake uninstall pide`?

**Comment by waruqi** [comment]
try

```console
xmake update dev
source ~/.xmake/profile
```

it should work.

**Comment by gffrnl** [comment]
> try
> 
> ```
> xmake update dev
> source ~/.xmake/profile
> ```
> 
> it should work.

Thank you! It works. The binary of the development version is installed in my machine at `~/.local/bin/xmake` so I need use `sudo ~/.local/bin/xmake uninstall pide` instead. 

Will this modification be included in next xmake release???

**Comment by gffrnl** [comment]
Oh, one more thing. I should mention that if `/usr/local/include` contains only the empty folder that xmake removes, then the script now will remove the directory `/usr/local/include` also, not only `/usr/local/include/pide`.
