### ISSUE TITLE
using coost library from xrepo raises  undefined reference errors

### ISSUE THREAD

**Issue by raceychan** [xmake-io/xmake#2912]
### Xmake Version

2.6.8

### Operating System Version and Architecture

ubuntu 20.0

### Describe Bug

using coost library installed by xrepo install raises multiple undefined reference errors;

error: /usr/bin/ld: /home/race/.xmake/packages/c/coost/v3.0.0/e7a64508b634445f93e6b7f099ab5e52/lib/libco.a(log.cc.o): in function `___::log::xx::Logger::start()':
log.cc:(.text+0x1d8f): undefined reference to `pthread_create'
/usr/bin/ld: /home/race/.xmake/packages/c/coost/v3.0.0/e7a64508b634445f93e6b7f099ab5e52/lib/libco.a(log.cc.o): in function `___::log::xx::Logger::stop(bool)':
log.cc:(.text+0x47da): undefined reference to `pthread_join'
/usr/bin/ld: /home/race/.xmake/packages/c/coost/v3.0.0/e7a64508b634445f93e6b7f099ab5e52/lib/libco.a(stack_trace.cc.o): in function `___::log::StackTraceImpl::dump_stack(void*, int)':
stack_trace.cc:(.text+0xb8): undefined reference to `backtrace_create_state'
/usr/bin/ld: stack_trace.cc:(.text+0xcf): undefined reference to `backtrace_full'
/usr/bin/ld: /home/race/.xmake/packages/c/coost/v3.0.0/e7a64508b634445f93e6b7f099ab5e52/lib/libco.a(hook.cc.o): in function `read':
hook.cc:(.text+0x3d7): undefined reference to `dlsym'
/usr/bin/ld: /home/race/.xmake/packages/c/coost/v3.0.0/e7a64508b634445f93e6b7f099ab5e52/lib/libco.a(hook.cc.o): in function `recv':
hook.cc:(.text+0x9c7): undefined reference to `dlsym'
/usr/bin/ld: /home/race/.xmake/packages/c/coost/v3.0.0/e7a64508b634445f93e6b7f099ab5e52/lib/libco.a(hook.cc.o): in function `recvfrom':
hook.cc:(.text+0xfdf): undefined reference to `dlsym'
/usr/bin/ld: /home/race/.xmake/packages/c/coost/v3.0.0/e7a64508b634445f93e6b7f099ab5e52/lib/libco.a(hook.cc.o): in function `socket':
hook.cc:(.text+0x14e3): undefined reference to `dlsym'
/usr/bin/ld: /home/race/.xmake/packages/c/coost/v3.0.0/e7a64508b634445f93e6b7f099ab5e52/lib/libco.a(hook.cc.o): in function `socketpair':
hook.cc:(.text+0x199b): undefined reference to `dlsym'
/usr/bin/ld: /home/race/.xmake/packages/c/coost/v3.0.0/e7a64508b634445f93e6b7f099ab5e52/lib/libco.a(hook.cc.o):hook.cc:(.text+0x218f): more undefined references to `dlsym' follow
/usr/bin/ld: /home/race/.xmake/packages/c/coost/v3.0.0/e7a64508b634445f93e6b7f099ab5e52/lib/libco.a(scheduler.cc.o): in function `co::SchedulerManager::SchedulerManager()':
scheduler.cc:(.text+0x2b6a): undefined reference to `pthread_create'
/usr/bin/ld: scheduler.cc:(.text+0x2b7f): undefined reference to `pthread_detach'
/usr/bin/ld: scheduler.cc:(.text+0x2bab): undefined reference to `pthread_join'
/usr/bin/ld: /home/race/.xmake/packages/c/coost/v3.0.0/e7a64508b634445f93e6b7f099ab5e52/lib/libco.a(thread.cc.o): in function `co::xx::cond_init(pthread_cond_t*)':
thread.cc:(.text+0x34): undefined reference to `pthread_condattr_setclock'
collect2: error: ld returned 1 exit status

### Expected Behavior

would be able to compile and run coost offical example
```cpp
#include "co/all.h"

DEF_string(s, "nice", "");

int main(int argc, char **argv) {
  flag::init(argc, argv);
  LOG << FLG_s;
  return 0;
}
```

### Project Configuration

Here is my xmake.lua

```lua
add_rules("mode.debug", "mode.release")
add_requires("coost 3.0.0")


set_languages("c++20")
set_optimize("fastest")

target("main")
    set_toolchains("gcc-11")
    set_kind("binary")
    add_files("src/main.cpp")
    add_packages("coost")
```

### Additional Information and Error Logs
possible way to reproduce this bug:

step1. xrepo install coost
step2. copy paste my xmake.lua
step3. creating main.cpp using coost offcial example I post above.
step4. xmake build

**Comment by waruqi** [comment]
try

```console
xrepo update-repo
xrepo remove --all -y coost
xmake f -c
xmake
```

**Comment by waruqi** [comment]
try

```console
xrepo update-repo
xrepo remove --all -y coost
xmake f -c
xmake
```
