### ISSUE TITLE
includes接口添加不存在的目录或文件不会又警告或者报错

### ISSUE THREAD

**Issue by Dozingfiretruck** [xmake-io/xmake#2918]
### Xmake 版本

2.7.2

### 操作系统版本和架构

win10

### 描述问题

使用includes接口添加不存在的目录或文件不会又警告或者报错
例如： includes("abc")或 includes("abc/xmake.lua")，但是abc并不存在，此时不会有任何警告或报错

### 期待的结果

希望有报错或警告，另外有个需求：includes接口有返回，可以是bool型，通过返回判断是否成功

**Comment by waruqi** [comment]
> 希望有报错或警告，另外有个需求：includes接口有返回，可以是bool型，通过返回判断是否成功

警告可以加，返回值不搞，自己 if os.isfile 判断下也没几行代码

**Comment by Dozingfiretruck** [comment]
> > 希望有报错或警告，另外有个需求：includes接口有返回，可以是bool型，通过返回判断是否成功
> 
> 警告可以加，返回值不搞，自己 if os.isfile 判断下也没几行代码

好的，另外请问是否支持在target里includes，我这有测试可以，不知道会不会是bug，怕这么用了以后修复

**Comment by waruqi** [comment]
includes 是全局接口，跟 target 无关，你即使放在 target下面 includes，也跟 target 没任何关系

**Comment by Dozingfiretruck** [comment]
> includes 是全局接口，跟 target 无关，你即使放在 target下面 includes，也跟 target 没任何关系

懂了，非常感谢

**Comment by waruqi** [comment]
警告我加了

**Comment by Dozingfiretruck** [comment]
> 警告我加了

收到
