### ISSUE TITLE
xrepo install `--mode=debug` 对 lua 脚本指定 package 选项不生效

### ISSUE THREAD

**Issue by cyfdecyf** [xmake-io/xmake#2921]
### Xmake 版本

2.7.2+dev.455d51688

### 操作系统版本和架构

Arch Linux, Ubuntu 20.04

### 描述问题

以这个 [lua 脚本](https://github.com/xmake-io/xrepo-cmake/blob/main/example/packages/gflags.lua)为例，以下命令

```
$ xrepo install --mode=debug glog.lua
note: install or modify (m) these packages (pass -y to skip confirm)?
in my-xmake-repo:
  -> glog v0.5.0 [shared:y, gflags:y]
please input: y (y/n/m)
```

这里 config 中并没有出现 `debug:y`。

### 期待的结果

可能更合理的行为是 `--mode=debug` 会修改默认的 debug 配置属性，若 package config 中若没有 debug 则用默认值设置。

目前这个行为对使用上影响不大，需要 debug build 可以通过 configs 来指定。而且我们使用 lua 脚本指定很多包的配置时本身就有类似的逻辑（全局默认 static lib，特定 package 用 shared）。

**Comment by cyfdecyf** [comment]
debug xrepo-cmake 的过程中有个想法：如果使用 lua 脚本指定包，就尽量让所有 config 都在 lua 脚本中指定，否则多个包互相之间的 config 容易发生不一致。

**Comment by waruqi** [comment]
走 lua 脚本，就完全有 lua 里面每个包的 add_requires 的 configs 完全托管了，原本外面 xrepo install 的那些 -m/-k/--configs 就是不会影响里面的，那个是给 命令行装包配置用的

如果 lua 配置，还要混用外面的 -m/-k/--configs 那就太蛋疼了，而且处理不好，反而会导致混乱，用户更搞不清。

**Comment by cyfdecyf** [comment]
> 如果 lua 配置，还要混用外面的 -m/-k/--configs 那就太蛋疼了，而且处理不好，反而会导致混乱，用户更搞不清。
> 
> 建议用了 lua 配，外面就不要配了

的确，命令行指定和 lua 脚本混合的确不好。我 close 这个 issue。
