### ISSUE TITLE
cppcoro: unmatched checksum

### ISSUE THREAD

**Issue by backfirehzy** [xmake-io/xmake#2923]
### Xmake 版本

xmake v2.7.2+dev.343db2cf1

### 操作系统版本和架构

Windows 11 企业版 22621.521

### 描述问题

无法下载cppcoro, 出现checksum不匹配的错误

### 期待的结果

成功安装cppcoro

### 工程配置

add_requires("cpr")
add_requires("cppcoro")

target("untitled1")
    set_kind("binary")
    set_languages("c++20")
    add_files("src/*.cpp")
    add_packages("cpr")
    add_packages("cppcoro")

### 附加信息和错误日志

checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checkinfo: cannot runv(dmd.exe --version), No such file or directory
checking for dmd ... no
checkinfo: cannot runv(ldc2.exe --version), No such file or directory
checking for ldc2 ... no
checkinfo: cannot runv(gdc.exe --version), No such file or directory
checking for gdc ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(unzip.exe -v), No such file or directory
checking for unzip ... no
checking for 7z ... C:\Program Files\xmake\winenv\bin\7z
checking for git ... ok
checkinfo: cannot runv(gzip.exe --version), No such file or directory
checking for gzip ... no
git rev-parse HEAD
checking for cmake ... C:\Program Files\CMake\bin\cmake
finding libcurl from xmake ..
checking for xmake::libcurl ... libcurl 7.84.0
finding cpr from xmake ..
checking for xmake::cpr ... cpr 1.8.3
finding cppcoro from xmake ..
checking for xmake::cppcoro ... no
finding cppcoro from vcpkg ..
checkinfo: vcpkg root directory not found, maybe you need set $VCPKG_ROOT!
finding cppcoro from conan ..
finding cppcoro from pkgconfig ..
checkinfo: cannot runv(pkg-config.exe --version), No such file or directory
checking for pkg-config ... no
checkinfo: cannot runv(pkgconf.exe --version), No such file or directory
checking for pkgconf ... no
finding cppcoro from system ..
checking for cppcoro ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> cppcoro 2020.10.13 [vs_runtime:"MT"]
please input: y (y/n/m)
y
checking for ping ... ok
pinging for the host(github.com) ... 223 ms
checking for curl ... C:\Program Files\xmake\winenv\bin\curl
C:\Program Files\xmake\winenv\bin\curl -SL -A "Xmake/2.7.2+dev.343db2cf1 (Windows;) curl/7.85.0" https://github.com/xmake-mirror/build-artifacts/releases/download/cppcoro-2020.10.13/windows-x64-vc142-35eebf12b19f4336b38b6f3ee5f9ad33.7z -o windows-x64-vc142-35eebf12b19f4336b38b6f3ee5f9ad33.7z
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  222k  100  222k    0     0  56766      0  0:00:04  0:00:04 --:--:--  103k
error: ...modules\private\action\require\impl\actions\download.lua:157: unmatched checksum!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:897]:
    [...modules\private\action\require\impl\actions\download.lua:157]: in function '_download'
    [...modules\private\action\require\impl\actions\download.lua:277]:

  => download https://github.com/xmake-mirror/build-artifacts/releases/download/cppcoro-2020.10.13/windows-x64-vc142-35eebf12b19f4336b38b6f3ee5f9ad33.7z .. failed

we can also download these packages manually:
  - https://github.com/xmake-mirror/build-artifacts/releases/download/cppcoro-2020.10.13/windows-x64-vc142-35eebf12b19f4336b38b6f3ee5f9ad33.7z
to the local search directories: c:/
  - windows-x64-vc142-35eebf12b19f4336b38b6f3ee5f9ad33.7z
and we can run `xmake g --pkg_searchdirs=/xxx` to set the search directories.
error: @programdir\modules\private\async\runjobs.lua:256: ...modules\private\action\require\impl\actions\download.lua:318:
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:897]:
    [...modules\private\action\require\impl\actions\download.lua:318]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [...modules\private\action\require\impl\actions\download.lua:257]:
    [...modules\private\action\require\impl\install_packages.lua:472]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:232]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:897: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir\modules\private\async\runjobs.lua:256: in field 'catch'
        @programdir\core\sandbox\modules\try.lua:123: in global 'try'
        @programdir\modules\private\async\runjobs.lua:218: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:388: in function <@programdir\core\base\scheduler.lua:385>

**Comment by waruqi** [comment]
先更新repo再试下，xrepo update-repo

还不行，就是下载不完整，失败了

**Comment by backfirehzy** [comment]
repo更新过, 重新下载了好几次, 每次都只是这一个包出问题. 浏览器下载时也没有文件完整性问题, 会不会是checksum值标错了?

**Comment by waruqi** [comment]
再更新 repo 试试，我 rebuild 了下

xrepo update-repo
xmake f -c
xmake

**Comment by backfirehzy** [comment]
更新之后报错解决了, 谢谢
