### ISSUE TITLE
Implicit binary packages should not be distinct from explicit ones

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2924]
### Xmake 版本

2.7.2

### 操作系统版本和架构

Windows 10

### 描述问题

![image](https://user-images.githubusercontent.com/42310255/195986644-19bc5944-1022-4d0d-baa8-7b09836b96f9.png)

这里cmake被装了两遍，但它们都是binary类型，没有任何差异，不应该重复安装才对

### 期待的结果

显式声明的binary与隐式声明的binary应该视为相同，只安装一遍

**Comment by waruqi** [comment]
给下 xmake.lua

**Comment by waruqi** [comment]
看了下，不太好搞，`{kind = "binary"}` 在加载包前，就是参与 package key 的去重计算

目前只能改 glad 包，对 cmake 去掉显式的  `{kind = "binary"}`，原本就是没必要的设置。

**Comment by waruqi** [comment]
这个暂时改不了，repo 里面 glad 我改了，应该可以了，更新下试试 xrepo update-repo
