### ISSUE TITLE
Doxygen plugin improvement

### ISSUE THREAD

**Issue by A2va** [xmake-io/xmake#2925]
### Is your feature request related to a problem? Please describe.

Now doxygen must be installed separately to get working with doxygen plugin. 

### Describe the solution you'd like

But doxygen is already on xrepo, so it's neat if the doxygen plugin can get the binary from the xmake package directory

**Comment by waruqi** [comment]
I have improved it. `xmake update -s dev`

**Comment by A2va** [comment]
Thank you very much!
