### ISSUE TITLE
xmake can not find visual studio

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2927]
### Xmake 版本

2.7.2

### 操作系统版本和架构

Windows 10

### 描述问题

xmake 找不到非默认位置的Visual Studio安装
<img width="464" alt="69dfe601ac2040948f9ef63c4ddf70a" src="https://user-images.githubusercontent.com/42310255/196025564-a772a150-fabe-453a-aaa6-90ca2ab72e6c.png">

<img width="532" alt="35e0758664af1f553d17615ad33319d" src="https://user-images.githubusercontent.com/42310255/196025570-906d91d8-fb5d-4a9e-af4f-7364306ba68c.png">

### 期待的结果

可以正常找到D分区的visual studio

**Comment by waruqi** [comment]
如果 vsallvars.bat 已经找到了，后面就只是加载这个 bat 获取相关的 envs ，其他不做什么了，
https://github.com/xmake-io/xmake/blob/554ab8a3cdb805efc83870d22d01790df4e55782/xmake/modules/detect/sdks/find_vstudio.lua#L321

感觉像是 vsallvars.bat 本身有点问题，可以自己调下上面这个脚本

**Comment by xq114** [comment]
找到原因了，卸载Anaconda的时候没卸干净，anaconda安装在cmd的autorun hook就会报错，这样调用cmd运行各类脚本都会直接失败，包括winos.version等等。建议xmake运行时检查一下当前的cmd是否能正常运行，如果不能的话提前报错，方便定位问题

**Comment by waruqi** [comment]
可以来个 patch 在这个位置，加上 catch errors 的处理，加个 wprint 显示 errors ，当 -D 被启用的时候

**Comment by xq114** [comment]
这里不光是find_vstudio，其他地方也会出问题，cmd检测应该放在全局检测里（比如os.iorun里，每次bat运行失败后检测cmd是否正常）；加error print也不解决问题，光看输出是正常输出，但用cmd运行bat就会失败

**Comment by waruqi** [comment]
> cmd检测应该放在全局检测里（比如os.iorun里，每次bat运行失败后检测cmd是否正常

这种暂时不搞，原本就是极小概率事件，没必要特地为判断个 cmd 搞这么折腾。

> 加error print也不解决问题，光看输出是正常输出，但用cmd运行bat就会失败

os.run 不会失败？失败，就会有 errors

**Comment by xq114** [comment]
https://github.com/xmake-io/xmake/blob/master/xmake/core/base/winos.lua#L120 这里也用了，确实目前就这两个地方

**Comment by waruqi** [comment]
就这两，也就没啥必要了，顶多先 find_vstudio 里面先处理下，加个 warning
