### ISSUE TITLE
在gcc-12中使用了错误的命令行参数

### ISSUE THREAD

**Issue by SuperCodeHero** [xmake-io/xmake#2928]
### Xmake 版本

2.7.2

### 操作系统版本和架构

macOS Monterey 12.6

### 描述问题

在xmake源码的 tests/projects/c++/modules/stl_headerunit 下, 设置编译器为gcc-12, 执行xmake将会出错, 以下是执行的完整命令

> xmake f --cc=gcc-12 --cxx=g++-12
> xmake -v

以下是结果:
`
[  0%]: generating.cxx.module.deps src/main.cpp
[  0%]: generating.cxx.module.deps src/hello.mpp
[ 16%]: generating.cxx.headerunit.bmi iostream
g++-12 -target arm64-apple-macos12.3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=c++20 -fmodules-ts -fmodule-mapper=/var/folders/l8/8z93h2q11gq5md1gp355k9hc0000gn/T/.xmake501/221016/_EDC283CEC04147308F5C192632CE3D40 -D_GLIBCXX_USE_CXX11_ABI=0 -c -x c++-system-header iostream
g++-12: error: unrecognized command-line option '-target'
error: execv(g++-12 -target arm64-apple-macos12.3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -std=c++20 -fmodules-ts -fmodule-mapper=/var/folders/l8/8z93h2q11gq5md1gp355k9hc0000gn/T/.xmake501/221016/_EDC283CEC04147308F5C192632CE3D40 -D_GLIBCXX_USE_CXX11_ABI=0 -c -x c++-system-header iostream) failed(1)
`

### 期待的结果

执行xmake后可以正确的完成编译

**Comment by waruqi** [comment]
xmake f --toolchain=gcc-12 -c
xmake

**Comment by SuperCodeHero** [comment]
谢谢
