### ISSUE TITLE
xmake 无法通过指定 分支名 来下载 安装 spdlog

### ISSUE THREAD

**Issue by yflin1** [xmake-io/xmake#2939]
### Xmake 版本

2.6.9

### 操作系统版本和架构

Ubuntu 20.04

### 描述问题

xmake.lua 里, add_requires("spdlog v2.x") 出错(无法为 spdlog 指定分支名)
spdlog 的 v2.x 分支是存在的, 可以通过 git clone 来下载到:
<pre>
git clone --single-branch --branch=v2.x https://github.com/gabime/spdlog
</pre>

试了其它几个第三方开源库也是这样情况 , 唯独 tbox 正常(`add_requires("tbox test")`)

### 期待的结果

可以通过  `xmake f` 正常下载并编译 spdlog v2.x 分支

### 工程配置

<pre>
add_requires("tbox test")
add_requires("spdlog v2.x")

target("test")
    set_kind("binary")
    add_files("src/**.cpp")
    add_packages("spdlog")
</pre>

### 附加信息和错误日志

<pre>
error: @programdir/core/main.lua:280: ...make/repositories/xmake-repo/packages/s/spdlog/xmake.lua:35: attempt to index a nil value
stack traceback:
    [...make/repositories/xmake-repo/packages/s/spdlog/xmake.lua:35]: in function 'on_load'
    [@programdir/modules/private/action/require/impl/package.lua:837]: in function '_load_package'
    [@programdir/modules/private/action/require/impl/package.lua:864]: in function '_load_packages'
    [@programdir/modules/private/action/require/impl/package.lua:1067]: in function 'load_packages'
    [...modules/private/action/require/impl/install_packages.lua:654]:
    [@programdir/modules/private/action/require/install.lua:85]:
    [@programdir/actions/config/main.lua:420]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/core/base/task.lua:501]: in function 'run'
    [@programdir/core/main.lua:278]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:388]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:872: in function 'os.raiselevel'
	(...tail calls...)
	@programdir/core/main.lua:280: in upvalue 'cotask'
	@programdir/core/base/scheduler.lua:388: in function <@programdir/core/base/scheduler.lua:385>

</pre>

**Comment by waruqi** [comment]
仅仅只是 spdlog 包配置的问题，跟其他无关。。更新下 repo 再试下

```console
xrepo update-repo
xmake f -c
xmake
```

**Comment by yflin1** [comment]
好的, 问题解决了, 谢谢
