### ISSUE TITLE
ldflags静态链接到路径中包含空格的目标.a文件失败

### ISSUE THREAD

**Issue by wsw0108** [xmake-io/xmake#2941]
### Xmake 版本

2.7.1

### 操作系统版本和架构

macOS

### 描述问题

第三方SDK在同一个目录下同时存在`libfoo.a`与`libfoo.dylib`，且SDK目录中包含空格。

在静态链接时，为了避免链接器优先使用动态库，使用了`add_ldflags("/path with space/to/libfoo.a")`，xmake在最终链接时，就出现问题了。

### 期待的结果

能够正常的使用ldflags链接到路径包含空格的静态库。

### 工程配置

https://github.com/wsw0108/xmake-bug-ldflags-space

`xmake -v main`失败
`xmake -v main2`成功

**Comment by wsw0108** [comment]
问题同时也在linux下存在。

**Comment by waruqi** [comment]
目前只有 add_includedirs add_defines 这种支持空格，add_ldflags 因为要支持 add_ldflags("-I xxx") 这种组合类 flags，内部会做 split ，所以要支持空格，得人为设置成 `{xxx}` 并标记为 {expand = false} 不对齐展开才行。

试下

```lua
    add_ldflags({path.translate("~/tmpdir/with space/libhello.a")}, {expand = false, force = true})
```
