### ISSUE TITLE
vsxmake 生成的 Visual Studio 工程中 set_group 层级错误

### ISSUE THREAD

**Issue by SaeruHikari** [xmake-io/xmake#2949]
### Xmake Version

2.7.2

### Operating System Version and Architecture

Windows 11 version 22H2

### Describe Bug

以下脚本：

``` cpp

add_rules("mode.debug", "mode.release")

target("xmake_group")
    set_group("00.group")
    set_kind("binary")
    add_files("src/*.cpp")

target("xmake_group2")
    set_group("00.group/cgpu")
    set_kind("binary")
    add_files("src2/*.cpp")

```

生成的 VS 工程层级如下：

![image](https://user-images.githubusercontent.com/39457738/196923415-b6e735a7-dbbe-4636-87c9-555fe04d51e9.png)

### Expected Behavior

正确地生成如下的目录结构：

![image](https://user-images.githubusercontent.com/39457738/196923523-868759c7-c706-41d6-b062-f2891340c4ea.png)

**Comment by waruqi** [comment]
再试下 应该可以了 xmake update -s dev

**Comment by SaeruHikari** [comment]
好了
