### ISSUE TITLE
cannot get program for ar for llvm-14

### ISSUE THREAD

**Issue by bamlan** [xmake-io/xmake#2955]
### Xmake 版本

2.7.2

### 操作系统版本和架构

armbian 4.4.213

### 描述问题

升级到xmake 2.7.2后，升级llvm-13到llvm-14，编译时报错(xmake 2.6+llvm-13时编译正常)

### 期待的结果

是否是因为升级llvm版本的原因？

### 工程配置

xmake f --toolchain=llvm --mode=release -vD 日志：
configure
{
    host = linux
    PIC = true
    ccache = true
    CHECK_JSVALUE = false
    plat = linux
    JS_STRICT_NAN_BOXING = true
    ndk_stdcxx = true
    JSX = true
    buildir = build
    BIGNUM = true
    toolchain = llvm
    PROFILE = false
    QJSX = true
    LTO = true
    mode = release
    kind = static
    arch = arm64-v8a
    WERROR = true
    ENABLE_LTO = true
    STORAGE = true
}

### 附加信息和错误日志

xmake -rvD日志：
...
checkinfo: OVERVIEW: LLVM Archiver

USAGE: llvm-ar [options] [-]<operation>[modifiers] [relpos] [count] <archive> [files]
       llvm-ar -M [<mri-script]

OPTIONS:
  --format              - archive format to create
    =default            -   default
    =gnu                -   gnu
    =darwin             -   darwin
    =bsd                -   bsd
  --plugin=<string>     - ignored for compatibility
  -h --help             - display this help and exit
  --rsp-quoting         - quoting style for response files
    =posix              -   posix
    =windows            -   windows
  --thin                - create a thin archive
  --version             - print the version and exit
  @<file>               - read options from <file>

OPERATIONS:
  d - delete [files] from the archive
  m - move [files] in the archive
  p - print contents of [files] found in the archive
  q - quick append [files] to the archive
  r - replace or insert [files] into the archive
  s - act as ranlib
  t - display list of files in archive
  x - extract [files] from the archive

MODIFIERS:
  [a] - put [files] after [relpos]
  [b] - put [files] before [relpos] (same as [i])
  [c] - do not warn if archive had to be created
  [D] - use zero for timestamps and uids/gids (default)
  [h] - display this help and exit
  [i] - put [files] before [relpos] (same as [b])
  [l] - ignored for compatibility
  [L] - add archive's contents
  [N] - use instance [count] of name
  [o] - preserve original dates
  [O] - display member offsets
  [P] - use full names when matching (implied for thin archives)
  [s] - create an archive index (cf. ranlib)
  [S] - do not build a symbol table
  [T] - deprecated, use --thin instead
  [u] - update only [files] newer than archive contents
  [U] - use actual timestamps and uids/gids
  [v] - be verbose about actions taken
  [V] - display the version and exit

checkinfo: OVERVIEW: LLVM Archiver

USAGE: llvm-ar [options] [-]<operation>[modifiers] [relpos] [count] <archive> [files]
       llvm-ar -M [<mri-script]

OPTIONS:
  --format              - archive format to create
    =default            -   default
    =gnu                -   gnu
    =darwin             -   darwin
    =bsd                -   bsd
  --plugin=<string>     - ignored for compatibility
  -h --help             - display this help and exit
  --rsp-quoting         - quoting style for response files
    =posix              -   posix
    =windows            -   windows
  --thin                - create a thin archive
  --version             - print the version and exit
  @<file>               - read options from <file>

OPERATIONS:
  d - delete [files] from the archive
  m - move [files] in the archive
  p - print contents of [files] found in the archive
  q - quick append [files] to the archive
  r - replace or insert [files] into the archive
  s - act as ranlib
  t - display list of files in archive
  x - extract [files] from the archive

MODIFIERS:
  [a] - put [files] after [relpos]
  [b] - put [files] before [relpos] (same as [i])
  [c] - do not warn if archive had to be created
  [D] - use zero for timestamps and uids/gids (default)
  [h] - display this help and exit
  [i] - put [files] before [relpos] (same as [b])
  [l] - ignored for compatibility
  [L] - add archive's contents
  [N] - use instance [count] of name
  [o] - preserve original dates
  [O] - display member offsets
  [P] - use full names when matching (implied for thin archives)
  [s] - create an archive index (cf. ranlib)
  [S] - do not build a symbol table
  [T] - deprecated, use --thin instead
  [u] - update only [files] newer than archive contents
  [U] - use actual timestamps and uids/gids
  [v] - be verbose about actions taken
  [V] - display the version and exit

checkinfo: OVERVIEW: LLVM Archiver

USAGE: llvm-ar [options] [-]<operation>[modifiers] [relpos] [count] <archive> [files]
       llvm-ar -M [<mri-script]

OPTIONS:
  --format              - archive format to create
    =default            -   default
    =gnu                -   gnu
    =darwin             -   darwin
    =bsd                -   bsd
  --plugin=<string>     - ignored for compatibility
  -h --help             - display this help and exit
  --rsp-quoting         - quoting style for response files
    =posix              -   posix
    =windows            -   windows
  --thin                - create a thin archive
  --version             - print the version and exit
  @<file>               - read options from <file>

OPERATIONS:
  d - delete [files] from the archive
  m - move [files] in the archive
  p - print contents of [files] found in the archive
  q - quick append [files] to the archive
  r - replace or insert [files] into the archive
  s - act as ranlib
  t - display list of files in archive
  x - extract [files] from the archive

MODIFIERS:
  [a] - put [files] after [relpos]
  [b] - put [files] before [relpos] (same as [i])
  [c] - do not warn if archive had to be created
  [D] - use zero for timestamps and uids/gids (default)
  [h] - display this help and exit
  [i] - put [files] before [relpos] (same as [b])
  [l] - ignored for compatibility
  [L] - add archive's contents
  [N] - use instance [count] of name
  [o] - preserve original dates
  [O] - display member offsets
  [P] - use full names when matching (implied for thin archives)
  [s] - create an archive index (cf. ranlib)
  [S] - do not build a symbol table
  [T] - deprecated, use --thin instead
  [u] - update only [files] newer than archive contents
  [U] - use actual timestamps and uids/gids
  [v] - be verbose about actions taken
  [V] - display the version and exit

checkinfo: OVERVIEW: LLVM Archiver

USAGE: llvm-ar [options] [-]<operation>[modifiers] [relpos] [count] <archive> [files]
       llvm-ar -M [<mri-script]

OPTIONS:
  --format              - archive format to create
    =default            -   default
    =gnu                -   gnu
    =darwin             -   darwin
    =bsd                -   bsd
  --plugin=<string>     - ignored for compatibility
  -h --help             - display this help and exit
  --rsp-quoting         - quoting style for response files
    =posix              -   posix
    =windows            -   windows
  --thin                - create a thin archive
  --version             - print the version and exit
  @<file>               - read options from <file>

OPERATIONS:
  d - delete [files] from the archive
  m - move [files] in the archive
  p - print contents of [files] found in the archive
  q - quick append [files] to the archive
  r - replace or insert [files] into the archive
  s - act as ranlib
  t - display list of files in archive
  x - extract [files] from the archive

MODIFIERS:
  [a] - put [files] after [relpos]
  [b] - put [files] before [relpos] (same as [i])
  [c] - do not warn if archive had to be created
  [D] - use zero for timestamps and uids/gids (default)
  [h] - display this help and exit
  [i] - put [files] before [relpos] (same as [b])
  [l] - ignored for compatibility
  [L] - add archive's contents
  [N] - use instance [count] of name
  [o] - preserve original dates
  [O] - display member offsets
  [P] - use full names when matching (implied for thin archives)
  [s] - create an archive index (cf. ranlib)
  [S] - do not build a symbol table
  [T] - deprecated, use --thin instead
  [u] - update only [files] newer than archive contents
  [U] - use actual timestamps and uids/gids
  [v] - be verbose about actions taken
  [V] - display the version and exit

checking for llvm-ar ... no
checking for the static library archiver (ar: llvm-ar) ... no
checking for the static library archiver (ar: llvm-ar) ... no
error: @programdir/modules/private/async/runjobs.lua:256: ...gramdir/core/sandbox/modules/import/core/tool/linker.lua:33: cannot get program for ar
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:897]:
    [...gramdir/core/sandbox/modules/import/core/tool/linker.lua:33]: in function 'load'
    [@programdir/actions/build/kinds/static.lua:35]: in function '_do_link_target'
    [@programdir/actions/build/kinds/static.lua:117]:
    [@programdir/actions/build/kinds/static.lua:144]: in function '_link_target'
    [@programdir/actions/build/kinds/static.lua:172]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:232]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:897: in function 'os.raiselevel'
        (...tail calls...)
        @programdir/modules/private/async/runjobs.lua:256: in field 'catch'
        @programdir/core/sandbox/modules/try.lua:123: in global 'try'
        @programdir/modules/private/async/runjobs.lua:218: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:388: in function <@programdir/core/base/scheduler.lua:385>

执行 llvm-ar --version 输出：
Ubuntu LLVM version 14.0.6

  Optimized build.
  Default target: aarch64-unknown-linux-gnu
  Host CPU: cortex-a72

**Comment by waruqi** [comment]
不要省略，给完整 logs

**Comment by waruqi** [comment]
llvm 的问题，之前通过 `llvm-ar -version` 检测的，参数格式变了

我改了下，改成 llvm-ar -h 和 llvm-ar --version 检测了，应该可以了，但是否还兼容 llvm-13 你再测下，我这里暂时没 低版本 llvm

**Comment by bamlan** [comment]
经过测试，修改后llvm-14版本下该问题解决；llvm-13版本我只有x86_64 linux环境，在x86_64环境下llvm-13测试通过。

`xmake f --toolchain=llvm `时，使用clang++-14链接出错：

`
/usr/bin/clang++ -o build/linux/arm64-v8a/release/qjsxc build/.objs/qjsxc/linux/arm64-v8a/release/qjsc.c.o -Lbuild/linux/arm64-v8a/release -s -lqjsxlto -lm -ldl -lpthread -flto -fPIC -rdynamic
/usr/bin/ld: 当搜索用于 build/linux/arm64-v8a/release/libqjsxlto.a 时跳过不兼容的 -lqjsxlto
/usr/bin/ld: 找不到 -lqjsxlto
`


跟踪了下：

`
 "/usr/bin/ld" -pie -export-dynamic -s -EL -z relro --hash-style=gnu --build-id --eh-frame-hdr -m aarch64linux -export-dynamic -dynamic-linker /lib/ld-linux-aarch64.so.1 -o build/linux/arm64-v8a/release/qjsxc /usr/lib/aarch64-linux-gnu/Scrt1.o /usr/lib/aarch64-linux-gnu/crti.o /usr/bin/../lib/gcc/aarch64-linux-gnu/11/crtbeginS.o -Lbuild/linux/arm64-v8a/release -L/usr/bin/../lib/gcc/aarch64-linux-gnu/11 -L/lib/aarch64-linux-gnu -L/usr/lib/aarch64-linux-gnu -L/lib -L/usr/lib -plugin /usr/lib/llvm-14/bin/../lib/LLVMgold.so -plugin-opt=mcpu=generic build/.objs/qjsxc/linux/arm64-v8a/release/qjsc.c.o -lqjsxlto -lm -ldl -lpthread -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/bin/../lib/gcc/aarch64-linux-gnu/11/crtendS.o /usr/lib/aarch64-linux-gnu/crtn.o
`


`-lqjsxlto` 改为xmake生成的文件路径 `build/linux/arm64-v8a/release/libqjsxlto.a ` 链接通过：

`
 "/usr/bin/ld" -pie -export-dynamic -s -EL -z relro --hash-style=gnu --build-id --eh-frame-hdr -m aarch64linux -export-dynamic -dynamic-linker /lib/ld-linux-aarch64.so.1 -o build/linux/arm64-v8a/release/qjsxc /usr/lib/aarch64-linux-gnu/Scrt1.o /usr/lib/aarch64-linux-gnu/crti.o /usr/bin/../lib/gcc/aarch64-linux-gnu/11/crtbeginS.o -Lbuild/linux/arm64-v8a/release -L/usr/bin/../lib/gcc/aarch64-linux-gnu/11 -L/lib/aarch64-linux-gnu -L/usr/lib/aarch64-linux-gnu -L/lib -L/usr/lib -plugin /usr/lib/llvm-14/bin/../lib/LLVMgold.so -plugin-opt=mcpu=generic build/.objs/qjsxc/linux/arm64-v8a/release/qjsc.c.o build/linux/arm64-v8a/release/libqjsxlto.a -lm -ldl -lpthread -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/bin/../lib/gcc/aarch64-linux-gnu/11/crtendS.o /usr/lib/aarch64-linux-gnu/crtn.o
`

上面的问题可能也是版本更新导致的吧。这个我找时间再另外提个详细的issues。

**Comment by waruqi** [comment]
链接问题，跟这个没啥关系，你也可以直接提 pr 过来改进下

**Comment by terrywh** [comment]
升级到 xmake 2.7.2 后也出现类似问题，未使用 LLVM ：
```
[root@terryhaowu1651740613579-0 cpp-xbond]# xmake build --project=. -v -D
checking for the static library archiver (ar: ar) ... no
error: @programdir/core/main.lua:280: @programdir/actions/build/main.lua:171: ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:96: ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:56: @programdir/modules/private/async/runjobs.lua:256: ...gramdir/core/sandbox/modules/import/core/tool/linker.lua:33: cannot get program for ar
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:897]:
    [...gramdir/core/sandbox/modules/import/core/tool/linker.lua:33]: in function 'load'
    [@programdir/actions/build/kinds/static.lua:35]: in function '_do_link_target'
    [@programdir/actions/build/kinds/static.lua:117]:
    [@programdir/actions/build/kinds/static.lua:144]: in function '_link_target'
    [@programdir/actions/build/kinds/static.lua:172]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:232]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:897: in function 'os.raiselevel'
        (...tail calls...)
        @programdir/modules/private/async/runjobs.lua:256: in field 'catch'
        @programdir/core/sandbox/modules/try.lua:123: in global 'try'
        @programdir/modules/private/async/runjobs.lua:218: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:388: in function <@programdir/core/base/scheduler.lua:385>
stack traceback:
        @programdir/core/base/utils.lua:290: in function <@programdir/core/base/utils.lua:280>
        [C]: in function 'error'
        @programdir/core/base/os.lua:897: in function 'os.raiselevel'
        (...tail calls...)
        ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:56: in field 'co_start_withopt'
        @programdir/modules/private/async/runjobs.lua:217: in function <@programdir/modules/private/async/runjobs.lua:162>
        [C]: in function 'xpcall'
        @programdir/core/base/utils.lua:280: in function 'sandbox/modules/utils.trycall'
        @programdir/core/base/scheduler.lua:504: in function 'base/scheduler.co_group_begin'
        ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:94: in field 'co_group_begin'
        @programdir/modules/private/async/runjobs.lua:162: in function <@programdir/modules/private/async/runjobs.lua:56>
        (...tail calls...)
        @programdir/actions/build/build.lua:257: in function <@programdir/actions/build/build.lua:245>
        (...tail calls...)
        @programdir/actions/build/main.lua:108: in global '_do_build'
        @programdir/actions/build/main.lua:155: in function <@programdir/actions/build/main.lua:149>
        [C]: in function 'xpcall'
        @programdir/core/base/utils.lua:280: in function 'sandbox/modules/utils.trycall'
        @programdir/core/sandbox/modules/try.lua:117: in global 'try'
        @programdir/actions/build/main.lua:147: in function <@programdir/actions/build/main.lua:113>
        (...tail calls...)
        [C]: in function 'xpcall'
        @programdir/core/base/utils.lua:280: in function 'sandbox/modules/utils.trycall'
        (...tail calls...)
        @programdir/core/base/task.lua:501: in function 'base/task.run'
        @programdir/core/main.lua:278: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:388: in function <@programdir/core/base/scheduler.lua:385>
stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:897: in function 'os.raiselevel'
        (...tail calls...)
        @programdir/core/main.lua:280: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:388: in function <@programdir/core/base/scheduler.lua:385>
```

**Comment by waruqi** [comment]
> 升级到 xmake 2.7.2 后也出现类似问题，未使用 LLVM ：
> 
> ```
> # xmake build --project=. -v -D
> checking for the static library archiver (ar: ar) ... no
> error: @programdir/core/main.lua:280: @programdir/actions/build/main.lua:171: ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:96: ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:56: @programdir/modules/private/async/runjobs.lua:256: ...gramdir/core/sandbox/modules/import/core/tool/linker.lua:33: cannot get program for ar
> stack traceback:
>     [C]: in function 'error'
>     [@programdir/core/base/os.lua:897]:
>     [...gramdir/core/sandbox/modules/import/core/tool/linker.lua:33]: in function 'load'
>     [@programdir/actions/build/kinds/static.lua:35]: in function '_do_link_target'
>     [@programdir/actions/build/kinds/static.lua:117]:
>     [@programdir/actions/build/kinds/static.lua:144]: in function '_link_target'
>     [@programdir/actions/build/kinds/static.lua:172]: in function 'jobfunc'
>     [@programdir/modules/private/async/runjobs.lua:232]:
> 
> stack traceback:
>         [C]: in function 'error'
>         @programdir/core/base/os.lua:897: in function 'os.raiselevel'
>         (...tail calls...)
>         @programdir/modules/private/async/runjobs.lua:256: in field 'catch'
>         @programdir/core/sandbox/modules/try.lua:123: in global 'try'
>         @programdir/modules/private/async/runjobs.lua:218: in upvalue 'cotask'
>         @programdir/core/base/scheduler.lua:388: in function <@programdir/core/base/scheduler.lua:385>
> stack traceback:
>         @programdir/core/base/utils.lua:290: in function <@programdir/core/base/utils.lua:280>
>         [C]: in function 'error'
>         @programdir/core/base/os.lua:897: in function 'os.raiselevel'
>         (...tail calls...)
>         ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:56: in field 'co_start_withopt'
>         @programdir/modules/private/async/runjobs.lua:217: in function <@programdir/modules/private/async/runjobs.lua:162>
>         [C]: in function 'xpcall'
>         @programdir/core/base/utils.lua:280: in function 'sandbox/modules/utils.trycall'
>         @programdir/core/base/scheduler.lua:504: in function 'base/scheduler.co_group_begin'
>         ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:94: in field 'co_group_begin'
>         @programdir/modules/private/async/runjobs.lua:162: in function <@programdir/modules/private/async/runjobs.lua:56>
>         (...tail calls...)
>         @programdir/actions/build/build.lua:257: in function <@programdir/actions/build/build.lua:245>
>         (...tail calls...)
>         @programdir/actions/build/main.lua:108: in global '_do_build'
>         @programdir/actions/build/main.lua:155: in function <@programdir/actions/build/main.lua:149>
>         [C]: in function 'xpcall'
>         @programdir/core/base/utils.lua:280: in function 'sandbox/modules/utils.trycall'
>         @programdir/core/sandbox/modules/try.lua:117: in global 'try'
>         @programdir/actions/build/main.lua:147: in function <@programdir/actions/build/main.lua:113>
>         (...tail calls...)
>         [C]: in function 'xpcall'
>         @programdir/core/base/utils.lua:280: in function 'sandbox/modules/utils.trycall'
>         (...tail calls...)
>         @programdir/core/base/task.lua:501: in function 'base/task.run'
>         @programdir/core/main.lua:278: in upvalue 'cotask'
>         @programdir/core/base/scheduler.lua:388: in function <@programdir/core/base/scheduler.lua:385>
> stack traceback:
>         [C]: in function 'error'
>         @programdir/core/base/os.lua:897: in function 'os.raiselevel'
>         (...tail calls...)
>         @programdir/core/main.lua:280: in upvalue 'cotask'
>         @programdir/core/base/scheduler.lua:388: in function <@programdir/core/base/scheduler.lua:385>
> ```
> 
> 系统对应的 AR：
> 
> ```shell
> # ar --version
> GNU ar version 2.27-44.base.tl2.1
> Copyright (C) 2016 Free Software Foundation, Inc.
> This program is free software; you may redistribute it under the terms of
> the GNU General Public License version 3 or (at your option) any later version.
> This program has absolutely no warranty.

不同的问题，单独开 issue，并提供完整 -vD logs

**Comment by MaxwellGengYF** [comment]
Windows11 Clang16.0.1 xmake 2.7.8，使用--toolchain=clang也遇到了这个问题，--cc=clang --cxx=clang是没问题的。

**Comment by waruqi** [comment]
要用 `--toolchain=llvm`，才会使用 `llvm-ar`

`--toolchain=clang` 用的还是 ar，主要用于 linux/mac 下 /usr 系统路径，或者 PATH 下， gcc / clang 工具链切换

**Comment by MaxwellGengYF** [comment]
似乎win11即使用msvc toolchain也会有这个问题。
