### ISSUE TITLE
The autogenerated makefile for gnu-rm/c is not compatible with GNU make on Windows.

### ISSUE THREAD

**Issue by JacobPeng** [xmake-io/xmake#2957]
### Xmake Version

v2.7.2

### Operating System Version and Architecture

Windows 10 21H2

### Describe Bug

make is GNU Make 4.2.1 on Windows.
This is the original generated makefile.
```
clean_foo: 
	@del /F /Q build\cross\armv7\debug\libfoo.a > NUL 2>&1 || rmdir /S /Q build\cross\armv7\debug\libfoo.a > NUL 2>&1
```
The following is the error information.
```
PS C:\XXX\xmake\tests\projects\embed\gnu-rm\hello> make clean
make: *** [makefile:68: clean_foo] Error 1
```
I modified the makefile to check the error again.
```
clean_foo: 
	@del /F /Q build\cross\armv7\debug\libfoo.a
```
The error information is
```
PS C:\XXX\xmake\tests\projects\embed\gnu-rm\hello> make clean
make: del: Command not found
```
I checked the xmake/plugins/project/make/makefile.lua, the commands are correct. However, they are not compatible with GNU make. You can check the same issue [[Calling Windows commands (e.g. del) from a GNU makefile](https://stackoverflow.com/questions/2463037/calling-windows-commands-e-g-del-from-a-gnu-makefile)] on stackoverflow.
```
-- try to remove the given file or directory
function _tryrm(makefile, filedir)
    if is_subhost("windows") then
        -- we attempt to delete it as file first, we remove it as directory if failed
        makefile:print("\t@del /F /Q %s > NUL 2>&1 || rmdir /S /Q %s > NUL 2>&1", filedir, filedir)
    else
        makefile:print("\t@rm -rf %s", filedir)
    end
end
```

### Expected Behavior

Do you have any recommended make version on Windows which is compatible with the current implementation? 
Or I can modify the current implementation refers to the solution of the issue [[Calling Windows commands (e.g. del) from a GNU makefile](https://stackoverflow.com/questions/2463037/calling-windows-commands-e-g-del-from-a-gnu-makefile)] on stackoverflow.

**Comment by waruqi** [comment]
you should use nmake, xmake just generate makefile for nmake on windows.
