### ISSUE TITLE
xrepo install failed to find manually cloned git folder

### ISSUE THREAD

**Issue by RnMss** [xmake-io/xmake#2958]
### Xmake Version

2.7.2

### Operating System Version and Architecture

Ubuntu 22.04

### Describe Bug

Try to install a package named `libtorch` with poor network.
which need to be cloned from `https://github.com/pytorch/pytorch.git`.

it fails with log:

```
we can also download these packages manually:
  - https://github.com/pytorch/pytorch.git
to the local search directories: /my_xmake_pkgs
  - pytorch.git
```

Clone it manually into `/my_xmake_pkgs/pytorch.git` and try again.
Xrepo ignores my clone and try to clone into `xxx/source.tmp` again.

rename `/my_xmake_pkgs/pytorch.git` to `/my_xmake_pkgs/libtorch` will work.

### Expected Behavior

it should either search in `/my_xmake_pkgs/pytorch.git`,
or print the correct directory `/my_xmake_pkgs/libtorch`.

### Additional Information and Error Logs

 I don't know lua well, but I guess either
https://github.com/xmake-io/xmake/blob/master/xmake/modules/private/action/require/impl/actions/download.lua#L58
or
https://github.com/xmake-io/xmake/blob/master/xmake/modules/private/action/require/impl/actions/download.lua#L314
is wrong.

**Comment by waruqi** [comment]
you can add print to debug it.

**Comment by waruqi** [comment]
try it again, `xmake update -s dev`
