### ISSUE TITLE
Compiling Modules Inconsistant

### ISSUE THREAD

**Issue by cgbsu** [xmake-io/xmake#2961]
### Xmake Version

2.7.2

### Operating System Version and Architecture

Ubuntu (Container, Podman, amd x64)

### Describe Bug

Having some trouble using C++ modules with xmake, it seems inconsistent

If I compile a header into a module (Header.hpp + Header.mpp) it works... once, but does not propagate changes made to headers included by Header.hpp into the Header module (though I can, say, still call a new function that I add to an include of Header.hpp), then I have to delete .xmake and build

If I just use Header.mpp with Partition0.mpp Partition1.mpp etc.. it also works... once, but then doesn't seem to import anything from the module (in particular after an xmake clean) and it only works if I have a parallel set of headers Partition1.hpp Partition0.hpp that I have already put into a module as described above (even if I have removed them), though changes from PartitionX.mpp will be propagated and recompiled at this point.

Deleting .xmake and build will NOT work at this point, if I build again, it wont import anything from the modules, thought it appears to compile the modules themselves.

Its all really confusing

I have to use a gcc snapshot because gcc 12.1 or 12.2 crashes when compiling modules
gcc-13.0.0 seems to work OK (but not when including some headers, see the comment I put [here](https://gcc.gnu.org/bugzilla//show_bug.cgi?id=99241#c5)

You can see what I did hear 
["Master Header" version](https://github.com/cgbsu/WarpBootstrapCompiler2/commit/ae62c4db6b0e9b103c0c1ab9bfb88f8d044fb67f) (where Utilities.hpp includes several files and is imported by Utilities.mpp)
[Module Partition Version](https://github.com/cgbsu/WarpBootstrapCompiler2/commit/9e186e1060e1cff4871f1721cdf962273ca7a5a7)

These 3 commits may be of use: 
a3412b1bd2b4d902db102f3f39165bf0754b3ce1
ae62c4db6b0e9b103c0c1ab9bfb88f8d044fb67f
9e186e1060e1cff4871f1721cdf962273ca7a5a7

For the sake for being forthcoming I should mention that I am running as root with `XMAKE_ROOT=y` in a container

### Expected Behavior

~: xmake // Works
// Change file here 
~: xmake // Works, if the code itself does not have a problem, changes propagated to module files/caches in both cases ("Master Header" vs "Partitioned")
~: xmake clean
~: xmake  // Works, if the code itself does not have a problem, changes propagated to module files/caches in both cases ("Master Header" vs "Partitioned")

### Project Configuration

-- See changes
-- ["Master Header" version](https://github.com/cgbsu/WarpBootstrapCompiler2/commit/ae62c4db6b0e9b103c0c1ab9bfb88f8d044fb67f)
-- [Module Partition Version](https://github.com/cgbsu/WarpBootstrapCompiler2/commit/9e186e1060e1cff4871f1721cdf962273ca7a5a7)

set_languages("c++23")

add_requires("conan::ctpg/1.3.7", {alias = "ctpg"})
add_requires("conan::crc_cpp/1.1.0", {alias = "crc_cpp"})
add_requires("conan::catch2/3.0.1", {alias = "catch2"})

--target("Warp.Common")
--	set_kind("static")
--	add_files("Source/Common.mpp")
--	set_policy("build.c++.modules", true)
--target_end()

--target("Warp.Utilities")
--	set_kind("static")
--	add_files("Source/Utilities/*.mpp", "Source/Utilities.mpp")
--	add_includedirs("Include/")
--	add_includedirs("Include/ThirdParty/constexpr-random/include")
--	add_deps("Warp.Common");
--	add_packages("ctpg", "crc_cpp")
--	set_policy("build.c++.modules", true)
--target_end()

-- Check this out later! https://xmake.io/#/features/unity_build
-- add_rules("c.unity_build")
-- add_rules("c++.unity_build")

target("test")
	set_kind("binary")
	add_mflags("-freport-bug", "-E")
	add_files(
			"Source/Utilities/*.mpp", 
			"Source/*.mpp", 
			--"Source/Common.mpp", 
			"Test/*.cpp"
	)
	add_packages("ctpg", "catch2", "crc_cpp")
	--add_deps("Warp.Common");
	add_includedirs("Include")
	add_includedirs("Include/ThirdParty/constexpr-random/include")
	set_policy("build.c++.modules", true)
target_end()

### Additional Information and Error Logs

# Partitioned Case

Error in partition case when not importing: 

```
[ 72%]: cache compiling.release Test/Main.cpp
error: Test/Main.cpp:12:28: error: ‘treeSortMakeTree’ was not declared in this scope
   12 |         using X = decltype(treeSortMakeTree<minimum, ConstantBinaryTreeRootType>(
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Test/Main.cpp:12:28: error: ‘treeSortMakeTree’ was not declared in this scope
Test/Main.cpp:15:22: error: ‘X’ has not been declared
   15 |         std::cout << X::toString() << "\n";
      |                      ^
Test/Main.cpp:16:33: error: ‘treeSort’ was not declared in this scope
   16 |         constexpr auto result = treeSort<minimum>(
      |                                 ^~~~~~~~~~~~~~~~~
  > in Test/Main.cpp
```

This comes after this log, it requires me to build twice

```
error: In module imported at Include/ThirdParty/constexpr-random/include/crand/distributions/uniform_int_distribution.hpp:30:1:
./Include/ThirdParty/constexpr-random/include/crand/distributions/distribution_limits.hpp: error: failed to read compiled module: No such file or directory
./Include/ThirdParty/constexpr-random/include/crand/distributions/distribution_limits.hpp: note: compiled module file is ‘/root/workdir/build/.gens/test/linux/x86_64/release/rules/modules/cache/Include/ThirdParty/constexpr-random/include/crand/distributions/distribution_limits.hpp.gcm’
./Include/ThirdParty/constexpr-random/include/crand/distributions/distribution_limits.hpp: note: imports must be built before being imported
./Include/ThirdParty/constexpr-random/include/crand/distributions/distribution_limits.hpp: fatal error: returning to the gate for a mechanical issue
compilation terminated.
```

# "Master Header" Case
after making a change to a header included by Utilities.hpp it builds successfully but does not update the module,
`[100%]: build ok!`

I can confirm the module is not changing with `sha256sum` then I run `xmake clean` and `xmake` again and I get: 
`
error: In module imported at Source/Utilities.mpp:3:8:
./Include/Warp/Utilities.hpp: error: failed to read compiled module: Bad file data
./Include/Warp/Utilities.hpp: note: compiled module file is ‘/root/workdir/build/.gens/test/linux/x86_64/release/rules/modules/cache/Include/Warp/Utilities.hpp.gcm’
./Include/Warp/Utilities.hpp: fatal error: returning to the gate for a mechanical issue
compilation terminated.
`

This is the result of changing Main, no real suprise,
`
root@fe9917e74f33:~/workdir# xmake
[  0%]: generating.cxx.module.deps Test/Main.cpp
[ 44%]: cache compiling.release Test/Main.cpp
[ 77%]: linking.release test
[100%]: build ok!
`

I can confirm the presence of a module in the gcm.cache folder

Also I did try this with C++20 set in xmake.lua to see what would happen -- no obvious difference

# Update
 Just by the PartitionX.mpp files still being there, in the "Master Header" version it can call functions from the modules... go figure
 
 It did not do this before, but it seems to not take changes from the headers anymore... I can declare a function in the header and it wont find it... but I think it did this before... I was just trying to reproduce what I saw with C++23 (and changing the module did that, instead of the header this time) :dizzy_face:

**Comment by waruqi** [comment]
I don't know what you are talking about, please describe the problem as simply and directly as possible, reproducible steps, execution commands with the -vD parameter and a full log.

And provide a fully reproducible example project.

If you encounter multiple issues, split them into separate issues.

**Comment by cgbsu** [comment]
I may try to run with -Vd later but I linked the commits which show my xmake.lua and noted mysteps
```
xmake
xmake clean
xmake
rm -rf .xmake
rm -rf build
xmake
```

In two different context's (one where I try to create one large header unit, another where I try to use module/module partitions

The example is the one linked to in the commits which I linked

**Comment by waruqi** [comment]
I don't speak English well enough to understand what you are saying. Please describe your problem as simply as possible, or provide reproducible commands, logs and engineering examples.

**Comment by xq114** [comment]
I think he is talking about:
1. Modifying headers doesn't trigger recompiling;
2. Module partition (1 .hpp -> 2 .mpp) is not supported.

**Comment by waruqi** [comment]
> I think he is talking about:
> 
> 1. Modifying headers doesn't trigger recompiling;
> 2. Module partition (1 .hpp -> 2 .mpp) is not supported.

ok, I think it should be split into two separate issues. @cgbsu

**Comment by waruqi** [comment]
> Modifying headers doesn't trigger recompiling;

We need parse include deps with modules. https://github.com/xmake-io/xmake/issues/3000#issuecomment-1296446603

**Comment by waruqi** [comment]
> Modifying headers doesn't trigger recompiling;

I have improved it, you can run `xmake update -s github:xmake-io/xmake#modules` to update and try it again. @cgbsu

**Comment by waruqi** [comment]
> Module partition (1 .hpp -> 2 .mpp) is not supported.

About this, I'm still not sure what the problem is, can you provide a reproducible example project? @cgbsu
