### ISSUE TITLE
在vsxmake生成的vs solution中，phony target没有被放入正确的group中

### ISSUE THREAD

**Issue by AirGuanZ** [xmake-io/xmake#2963]
### Xmake 版本

xmake v2.7.2+master.a6eb410b9

### 操作系统版本和架构

Windows 11 22000.1098, 12th Gen Intel(R) Core(TM) i9-12950HX

### 描述问题

当某个target被设置为phony类型时，它仍然会出现在vsxmake生成的vs项目中，但不会被放入`set_group`所设置的group中。

### 期待的结果

`set_group`对phony target生效。

### 工程配置

[reprod.zip](https://github.com/xmake-io/xmake/files/9845952/reprod.zip)

其中的xmake.lua内容如下：

```lua
target("lib_phony")
	set_kind("phony")
	set_group("TestGroup")
	
target("lib_static")
	set_kind("static")
	set_group("TestGroup")
	add_files("lib.cpp")
	
target("main")
	set_kind("binary")
	add_files("main.cpp")
	add_deps("lib_phony", "lib_static")
```

运行命令：

```
xmake project -k vsxmake
```

可以看到生成的vs解决方案中，`lib_static`被放入了正确的group里，而`lib_phony`没有。

![未命名](https://user-images.githubusercontent.com/19588296/197380535-8f4c351d-a20b-4c01-ba09-74e6e0551819.png)

注：我使用的vs版本是

```
Visual Studio Community 2022 (64 位) - 17.3.1
```

**Comment by waruqi** [comment]
再试试，xmake update -s dev

**Comment by AirGuanZ** [comment]
已可以正常工作，感谢作者的贡献！
