### ISSUE TITLE
linux下build目录占用越来越大

### ISSUE THREAD

**Issue by gooker** [xmake-io/xmake#2966]
### Xmake 版本

2.7.1

### 操作系统版本和架构

centos7.8

### 描述问题

build目录下占用太大,刚开始几百M,用了一段时间一看8个多g了,虽然删了解决问题.

### 期待的结果

希望能提示或者自动清理

**Comment by waruqi** [comment]
禁用 cache

```console
xmake f --ccache=n
```

**Comment by gooker** [comment]
> ```
> xmake f --ccache=n
> ```

多谢,不知道是不是错觉.编译也快了..

**Comment by gooker** [comment]
> ```
> xmake f --ccache=n
> ```

多谢,不知道是不是错觉.编译也快了..
