### ISSUE TITLE
Proposal for generating `ptx` files

### ISSUE THREAD

**Issue by chenzhekl** [xmake-io/xmake#297]
Currently, `*.cu` files are by default compiled and linked as an executable host application. But for uses with things like `OptiX`, generating a standalone `ptx` with `--ptx` is necessary. There seems to be no workaround to avoid `evlink` for now, and the documentation for custom languages are missing. Thus I have a proposal for directly generating `ptx` files.

**Comment by waruqi** [comment]
I haven't had time to support it in the near future. Maybe I will consider supporting it in the v2.2.5 version. Please wait some time.

If you need this feature urgently, you can help contribute the relevant code. 

Thanks!

**Comment by chenzhekl** [comment]
@waruqi Thanks for the quick response. I'll see if I can help.

**Comment by chenzhekl** [comment]
Thanks! The above code snippet solved my problem.
