### ISSUE TITLE
Cross-compilation on windows

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#2983]
### Xmake 版本

2.7.2

### 操作系统版本和架构

Windows 10

### 描述问题

https://github.com/xmake-io/xmake-repo/actions/runs/3330911335/jobs/5510018408

ci上测试使用的windows-arm64用的交叉编译测试，环境仍是amd64的环境；但安装的包（package.tools.cmake）却没有做交叉编译的处理，导致CMAKE_SYSTEM_PROCESSOR 仍是x86_64而不是arm64

### 期待的结果

cmake中应该使用CMAKE_TOOLCHAIN_FILE来指定交叉编译工具链

https://github.com/libjpeg-turbo/libjpeg-turbo/issues/572

https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html

**Comment by waruqi** [comment]
> https://github.com/libjpeg-turbo/libjpeg-turbo/issues/572

这里面用的是 gnumake generator

目前 tools.cmake 里面走的 vs generator 切 arm64 不行么？我看目前跑下来很多包，ci 上 win arm64 都能过掉，没啥问题么，干嘛一定要走 gnumake。。

https://github.com/xmake-io/xmake/blob/57674e8882d2c3d002a8212623bab76e42b4aaf7/xmake/modules/package/tools/cmake.lua#L328-L331

**Comment by waruqi** [comment]
> https://github.com/xmake-io/xmake-repo/actions/runs/3330911335/jobs/5510018408
>          C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\bin\HostX64\arm64\Lib.exe /OUT:"C:\Users\runneradmin\AppData\Local\.xmake\cache\packages\2210\l\libjpeg-turbo\2.1.4\source\build_ab87bdd8\Release\jpeg-static.lib" /NOLOGO /MACHINE:ARM64  /machine:ARM64 "jpeg-static.dir\Release\jcapimin.obj"

看里面 flags ，也都用了 arm64 的了

**Comment by waruqi** [comment]
感觉应该还是这个 jpeg 库本身的编译配置问题。asm 相关代码还是作为了 x64 编译，用的也都是 sse/avx 啥的。。跟 cmake.install 里面关系不大

**Comment by xq114** [comment]
这个不是特定包的问题，交叉编译的CMAKE_SYSTEM_PROCESSOR设置应该是普适的。我先试试特殊判断一下吧

**Comment by waruqi** [comment]
> 这个不是特定包的问题，交叉编译的CMAKE_SYSTEM_PROCESSOR设置应该是普适的。我先试试特殊判断一下吧

目前不打算硬编码写死在里面，很多包 cmakelists.txt 自己也会判断这个，谁知道是不是按正常的 arch 值判断，目前也没几个包真的依赖这个。。

有需要的包，在外面配置下就好了。

**Comment by xq114** [comment]
https://github.com/xmake-io/xmake-repo/actions/runs/3343066995/jobs/5535914135

CMAKE_SYSTEM_PROCESSOR不能通过命令行设置，只能在toolchain里面指定

**Comment by waruqi** [comment]
> https://github.com/xmake-io/xmake-repo/actions/runs/3343066995/jobs/5535914135
> 
> CMAKE_SYSTEM_PROCESSOR不能通过命令行设置，只能在toolchain里面指定

也许只是值不对，试下 aarch64 或者小写 arm

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/d0e7c4548a908166b6c4daba549ee86cabe3efba/CMakeLists.txt#L81
