### ISSUE TITLE
C++ exception enabled/disabled switch method

### ISSUE THREAD

**Issue by MaxwellGengYF** [xmake-io/xmake#2988]
### Is your feature request related to a problem? Please describe.

Currently, different platforms can only enable/disable c++ exception by using compiler's flag, such as "/EHsc" on MSVC or "-fno-exceptions" on Clang. 

### Describe the solution you'd like

This inconvenient could be avoided if a built-in method such as "set_exception" provided.

**Comment by SaeruHikari** [comment]
我尝试了并正在使用这样的做法：

``` lua
rule("c++.exception")
    on_config(function (target)
        if (target:has_tool("cxx", "cl")) then
            target:add("cxflags", "/EHsc", {force = true})
            target:add("cxxflags", "/EHsc", {force = true})
            target:add("defines", "_HAS_EXCEPTIONS=1", {force = true})
        elseif(target:has_tool("cxx", "cl") or target:has_tool("cxx", "clang-cl")) then
            target:add("cxflags", "-fexceptions", {force = true})
            target:add("cxflags", "-fcxx-exceptions", {force = true})
        end
    end)

rule("c++.noexception")
    on_config(function (target)
        if (target:has_tool("cxx", "cl")) then
            target:add("cxflags", "/EHs-c-", {force = true})
            target:add("cxflags", "/D_HAS_EXCEPTIONS=0", {force = true})
            target:add("defines", "_HAS_EXCEPTIONS=0", {force = true})
        elseif(target:has_tool("cxx", "cl") or target:has_tool("cxx", "clang-cl")) then
            target:add("cxflags", "-fno-exceptions", {force = true})
            target:add("cxflags", "-fno-cxx-exceptions", {force = true})
        end
    end)
```

脚本本身功能上可以运作但是 CL 会抛出大量的警告：

![image](https://user-images.githubusercontent.com/39457738/199898590-b5dee2f9-5af4-4f5d-a243-c7e1b427e147.png)

D9025 属于无法屏蔽的警告，可能还是需要在 cxx 的内部规则提供专门用于设置异常开关的接口。

**Comment by waruqi** [comment]
加上了，试下 `xmake update -s github:xmake-io/xmake#exception`

https://github.com/xmake-io/xmake/pull/3025

```lua
set_exceptions("cxx")
set_exceptions("objc")
set_exceptions("no-cxx")
set_exceptions("no-objc")
set_exceptions("cxx", "objc")
```

windows 如果没设置，默认启用 cxx exception，但用户可以通过 `set_exceptions("no-cxx")` 覆盖设置

**Comment by shuax** [comment]
这里说的是windows没设置，默认会启用，实际上好像并没有启用呢，一定要自己写一个`set_exceptions("cxx")`，不然就提示`warning C4530: 使用了 C++ 异常处理程序，但未启用展开语义。请指定 /EHsc`

**Comment by SaeruHikari** [comment]
> 这里说的是windows没设置，默认会启用，实际上好像并没有启用呢，一定要自己写一个`set_exceptions("cxx")`，不然就提示`warning C4530: 使用了 C++ 异常处理程序，但未启用展开语义。请指定 /EHsc`

这个 issue 比较老了，最近的新版本改了默认是关掉的。

**Comment by shuax** [comment]
> 不，默认一直是开着的，没变。。#4838
> 
> 只不过 2.8.8 版本有个 bug ，默认开着 但实际没生效，2.8.9 应该修复了才对。。请确认下版本。

😂刚好是2.8.8，马上升级
