### ISSUE TITLE
Incremental compilation support for modules

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#3000]
### Xmake Version

2.7.2

### Operating System Version and Architecture

ubuntu

### Describe Bug

Modifying headers doesn't trigger recompiling; https://github.com/xmake-io/xmake/issues/2961

we can test it in user_headerunits test.

- [x] xxx.mpp cannot generate deps with header
  - [x] gcc
  - [x] clang
  - [x] msvc 
- [x] we need improve to parse header file from xxx.gcm.d and xxx.cpp.o.d if it contains modules
  - [x] gcc
  - [x] clang
  - [x] msvc 
- [x] ccache will also affect incremental compilation (disabled)
  - [x] object 
  - [x] fix dependfile 

### Expected Behavior

..

**Comment by waruqi** [comment]
we need improve to parse include deps with modules for gcc.

hello.gcm.d

```
build/.objs/user_headerunit/linux/x86_64/release/src/hello.mpp.o  /mnt/xmake/tests/projects/c++/modules/user_headerunit/build/.gens/user_headerunit/linux/x86_64/release/rules/modules/cache/hello.gcm:  src/hello.mpp\
build/.objs/user_headerunit/linux/x86_64/release/src/hello.mpp.o  /mnt/xmake/tests/projects/c++/modules/user_headerunit/build/.gens/user_headerunit/linux/x86_64/release/rules/modules/cache/hello.gcm:  ./src/header.hpp.c++m\
hello.c++m:  /mnt/xmake/tests/projects/c++/modules/user_headerunit/build/.gens/user_headerunit/linux/x86_64/release/rules/modules/cache/hello.gcm\
.PHONY: hello.c++m\
/mnt/xmake/tests/projects/c++/modules/user_headerunit/build/.gens/user_headerunit/linux/x86_64/release/rules/modules/cache/hello.gcm:|  build/.objs/user_headerunit/linux/x86_64/release/src/hello.mpp.o\
CXX_IMPORTS += ./src/header.hpp.c++m
```

**Comment by barcharcraz** [comment]
> we need improve to parse include deps with modules.
> ### gcc
> 
> hello.gcm.d
> 
> ```
> build/.objs/src/hello.mpp.o  /modules/cache/hello.gcm:  src/hello.mpp\
> build/.objs/src/hello.mpp.o  /modules/cache/hello.gcm:  ./src/header.hpp.c++m\
> hello.c++m:  /modules/cache/hello.gcm\
> .PHONY: hello.c++m\
> /modules/cache/hello.gcm:|  build/.objs/src/hello.mpp.o\
> CXX_IMPORTS += ./src/header.hpp.c++m
> ```
> 
> I really don't understand this include dependency format of gcc. what's `:|`? neutral_face

That's an [order only dependency](https://www.gnu.org/software/make/manual/make.html#Prerequisite-Types), it just means hello.gcm must be built after hello.mpp.o, but need not be rebuilt if it's older than hello.mpp.o.

**Comment by waruqi** [comment]
> > we need improve to parse include deps with modules.
> > ### gcc
> > hello.gcm.d
> > ```
> > build/.objs/src/hello.mpp.o  /modules/cache/hello.gcm:  src/hello.mpp\
> > build/.objs/src/hello.mpp.o  /modules/cache/hello.gcm:  ./src/header.hpp.c++m\
> > hello.c++m:  /modules/cache/hello.gcm\
> > .PHONY: hello.c++m\
> > /modules/cache/hello.gcm:|  build/.objs/src/hello.mpp.o\
> > CXX_IMPORTS += ./src/header.hpp.c++m
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I really don't understand this include dependency format of gcc. what's `:|`? neutral_face
> 
> That's an [order only dependency](https://www.gnu.org/software/make/manual/make.html#Prerequisite-Types), it just means hello.gcm must be built after hello.mpp.o, but need not be rebuilt if it's older than hello.mpp.o.

Got it, thanks!
