### ISSUE TITLE
Two mutually exclusive clang flags for C++20 modules compilation are included

### ISSUE THREAD

**Issue by aacirino** [xmake-io/xmake#3009]
### Xmake Version

2.7.1

### Operating System Version and Architecture

Fedora 36, clang 15

### Describe Bug

Since some time I've had problems building C++20 projects with modules. I had to resort to adding some compile flags but got tired of it and noticed that the compiler flags generation is including two mutually exclusive flags. In `xmake/rules/c++/modules/modules_support/clang.lua` we have

`local implicitmodulesflag = get_implicitmodulesflag(target)`
`local noimplicitmodulemapsflag = get_noimplicitmodulemapsflag(target)`

and then

`target:add("cxxflags", implicitmodulesflag, {force = true})`
`target:add("cxxflags", noimplicitmodulemapsflag, {force = true})`

Xmake should include only the implicit modules flag, allowing us to use clang's module maps transparently. Unfortunately xmake will not build in my environment due to an error something like `No rule to build the target 'lua/lapi.c'` (my system is in Brazilian Portuguese so I have to guess this is how it is phrased in English). I would change the modules flag generation myself and submit a pull request if I could build xmake.
In the meantime I have to keep adding the following flags to xmake.lua:

`"-fimplicit-module-maps",`
`"-fmodule-map-file=$(shell brew --prefix)/include/c++/v1/module.modulemap",`

### Expected Behavior

xmake should include only the `-fimplicit-modules` flag.

### Project Configuration

[trouble.zip](https://github.com/xmake-io/xmake/files/9914119/trouble.zip)

### Additional Information and Error Logs

[~/git/trouble]$ xmake -bv
[  0%]: generating.cxx.module.deps src/my_module.cpp
[ 23%]: generating.cxx.module.bmi my_module
/home/linuxbrew/.linuxbrew/opt/llvm/bin/clang -Qunused-arguments -m64 -fPIC -O3 -std=c++20 -fmodules -fbuiltin-module-map -fimplicit-modules -fno-implicit-module-maps -DNDEBUG -fmodules-cache-path=build/.gens/trouble/linux/x86_64/release/rules/modules/cache -c -x c++-module --precompile src/my_module.mpp -o build/.gens/trouble/linux/x86_64/release/rules/modules/cache/my_module.pcm
src/my_module.mpp:3:8: fatal error: module 'std' not found
import std;
~~~~~~~^~~
1 error generated.

**Comment by waruqi** [comment]
> xmake should include only the -fimplicit-modules flag.
> "-fmodule-map-file=$(shell brew --prefix)/include/c++/v1/module.modulemap",

Even when I add these flags, it still doesn't seem to work.


```console
/usr/bin/clang -c -x c++-module --precompile -Qunused-arguments -m64 -fPIC -O3 -std=c++20 -fmodules -fbuiltin-module-map -fimplicit-modules -fimplicit-module-maps -fmodule-map-file=/usr/lib/llvm-15/lib/clang/15.0.2/include/module.modulemap -DNDEBUG -fmodules-cache-path=build/.gens/trouble/linux/x86_64/release/rules/modules/cache -o build/.gens/trouble/linux/x86_64/release/rules/modules/cache/my_module.pcm src/my_module.mpp
/usr/bin/clang -c -Qunused-arguments -m64 -fPIC -O3 -std=c++20 -fmodules -fbuiltin-module-map -fimplicit-modules -fimplicit-module-maps -fmodule-map-file=/usr/lib/llvm-15/lib/clang/15.0.2/include/module.modulemap -DNDEBUG -fmodules-cache-path=build/.gens/trouble/linux/x86_64/release/rules/modules/cache -o build/.objs/trouble/linux/x86_64/release/src/my_module.mpp.o build/.gens/trouble/linux/x86_64/release/rules/modules/cache/my_module.pcm
checking for flags (-MMD -MF) ... ok
checking for flags (-fdiagnostics-color=always) ... ok
error: src/my_module.mpp:3:8: fatal error: module 'std' not found
import std;
~~~~~~~^~~
1 error generated.
```

**Comment by waruqi** [comment]
I have not linuxbrew and mold. I modified llvm path, but it does not work for me.

```console
/usr/bin/clang -c -x c++-module --precompile -Qunused-arguments -m64 -fPIC -O3 -std=c++20 -I/usr/local/include -I/usr/lib/llvm-15/include -I/usr/lib/llvm-15/lib/clang/15.0.2/include/c++/v1 -fmodules -fcxx-modules -fmodule-maps -fimplicit-module-maps -fbuiltin-module-map -fmodule-map-file=/usr/lib/llvm-15/lib/clang/15.0.2/include/module.modulemap -fvisibility=default -fimplicit-modules -fno-implicit-module-maps -DNDEBUG -fmodules-cache-path=build/.gens/trouble/linux/x86_64/release/rules/modules/cache -o build/.gens/trouble/linux/x86_64/release/rules/modules/cache/my_module.pcm src/my_module.mpp
/usr/bin/clang -c -Qunused-arguments -m64 -fPIC -O3 -std=c++20 -I/usr/local/include -I/usr/lib/llvm-15/include -I/usr/lib/llvm-15/lib/clang/15.0.2/include/c++/v1 -fmodules -fcxx-modules -fmodule-maps -fimplicit-module-maps -fbuiltin-module-map -fmodule-map-file=/usr/lib/llvm-15/lib/clang/15.0.2/include/module.modulemap -fvisibility=default -fimplicit-modules -fno-implicit-module-maps -DNDEBUG -fmodules-cache-path=build/.gens/trouble/linux/x86_64/release/rules/modules/cache -o build/.objs/trouble/linux/x86_64/release/src/my_module.mpp.o build/.gens/trouble/linux/x86_64/release/rules/modules/cache/my_module.pcm
error: src/my_module.mpp:3:8: fatal error: module 'std' not found
import std;
~~~~~~~^~~
1 error generated.
```

**Comment by aacirino** [comment]
By commenting out `target:add("cxxflags", noimplicitmodulemapsflag, {force = true})` in `xmake/rules/c++/modules/modules_support/clang.lua` this is the smallest `xmake.lua` build scrit that works for me:
```set_config("toolchain", "clang")
add_rules("mode.debug", "mode.release")
set_languages("c++20")

target()
add_includedirs(
	"$(shell brew --prefix)/include/",
	"$(shell brew --prefix)/opt/llvm/include/c++/v1"
)
add_cxxflags(
	"-fvisibility=default",
	{ force = true }
)
add_ldflags("-nostdlib++", "-stdlib=libc++", "-lc++")
target_end()

target("trouble")
    set_kind("shared")
    add_files("src/*.cpp", "src/*.mpp")

target("test")
    set_kind("binary")
    add_files("test/*.cpp")
    add_deps("trouble")
```

**Comment by waruqi** [comment]
I cannot run this script, because I have not brew on my ubuntu.

**Comment by aacirino** [comment]
@waruqi the problem is that your compiler flags include the undesired `-fno-implicit-module-maps` flag. This flag excludes clang's `module.modulemap` files from the compilation. I managed to comment-out the generation of this flag in xmake and built it again.

**Comment by aacirino** [comment]
Is xmake able to get clang's installation dir?

**Comment by waruqi** [comment]
> Is xmake able to get clang's installation dir?

/usr/lib/llvm-15/lib
/usr/bin/clang

**Comment by waruqi** [comment]
> Use this build script
> 
> ```
> set_config("toolchain", "clang")
> add_rules("mode.debug", "mode.release")
> set_languages("c++20")
> 
> target()
> add_includedirs(
> 	"/usr/local/include",
> 	"/usr/lib/llvm-15/lib/clang/15.0.2/include/c++/v1"
> )
> add_cxxflags(
> 	"-fvisibility=default",
> 	{ force = true }
> )
> add_ldflags("-nostdlib++", "-stdlib=libc++", "-lc++")
> target_end()
> 
> target("trouble")
>     set_kind("shared")
>     add_files("src/*.cpp", "src/*.mpp")
> 
> target("test")
>     set_kind("binary")
>     add_files("test/*.cpp")
>     add_deps("trouble")
> ```

```console
/usr/bin/clang -c -x c++-module --precompile -Qunused-arguments -m64 -fPIC -O3 -std=c++20 -I/usr/local/include -I/usr/lib/llvm-15/lib/clang/15.0.2/include/c++/v1 -fvisibility=default -fmodules -fbuiltin-module-map -fimplicit-modules -fno-implicit-module-maps -DNDEBUG -fmodules-cache-path=build/.gens/trouble/linux/x86_64/release/rules/modules/cache -o build/.gens/trouble/linux/x86_64/release/rules/modules/cache/my_module.pcm src/my_module.mpp
/usr/bin/clang -c -Qunused-arguments -m64 -fPIC -O3 -std=c++20 -I/usr/local/include -I/usr/lib/llvm-15/lib/clang/15.0.2/include/c++/v1 -fvisibility=default -fmodules -fbuiltin-module-map -fimplicit-modules -fno-implicit-module-maps -DNDEBUG -fmodules-cache-path=build/.gens/trouble/linux/x86_64/release/rules/modules/cache -o build/.objs/trouble/linux/x86_64/release/src/my_module.mpp.o build/.gens/trouble/linux/x86_64/release/rules/modules/cache/my_module.pcm
checking for flags (-MMD -MF) ... ok
checking for flags (-fdiagnostics-color=always) ... ok
error: src/my_module.mpp:3:8: fatal error: module 'std' not found
import std;
~~~~~~~^~~
1 error generated.
```

it does not work.

**Comment by waruqi** [comment]
If it works on your machine, you can open a pr first.

**Comment by aacirino** [comment]
PR created

**Comment by waruqi** [comment]
see https://github.com/xmake-io/xmake/pull/3016

But I still need to solve the compatibility problem between libc++ and libstdc++.

**Comment by waruqi** [comment]
try it again. `xmake update -s dev`

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/blob/7c5bd94cde348e8d656a0cb577bef83c7e20a070/tests/projects/c%2B%2B/modules/stdmodules/xmake.lua#L1-L33

**Comment by waruqi** [comment]
It should work now.
