### ISSUE TITLE
Xmake in Windows failed to compile projects stored inside WSL2 

### ISSUE THREAD

**Issue by itdevwu** [xmake-io/xmake#3013]
### Xmake Version

2.7.2

### Operating System Version and Architecture

Host: Windows 11 version 21H2; WSL2: Ubuntu 22.04 5.10.102.1-microsoft-standard-WSL2

### Describe Bug

In Windows 11, Microsoft PowerShell has supported access files and paths inside WSL2. User can directly copy a path of WSL2 from Windows' file explorer and use `cd` command in PowerShell to change their working path to somewhere inside the WSL2 VM.

Theoretically, this should have allowd xmake installed on Windows directly compile source code stored in WSL2 without copying them back to host. Since MSVC has the widest support of C++20 (much more than gcc/clang), such feature is supposed to be useful.

However, current version of xmake failed to parse such sort of path, who behaved as follows:
```powershell
PS Microsoft.PowerShell.Core\FileSystem::\\wsl.localhost\Ubuntu-22.04\home\user> xmake
error: cannot change directory \wsl.localhost\Ubuntu-22.04\home\user\wsl.localhost\Ubuntu-22.04\home\user, not found this directory Unknown
PS Microsoft.PowerShell.Core\FileSystem::\\wsl.localhost\Ubuntu-22.04\home\user>
```

The path used in the example above is: `\\wsl.localhost\Ubuntu-22.04\home\user` .

### Expected Behavior

For xmake installed inside WSL2, things are fine just like they are in normal Linux:

```bash
(base) user@Apple:~$ xmake
[ 18%]: cache compiling.release code/dp.cpp
[ 18%]: cache compiling.release code/divide_conque.cpp
[ 18%]: cache compiling.release code/datagen.cpp
[ 63%]: linking.release ma
[ 63%]: linking.release datagen
[100%]: build ok!
(base) user@Apple:~$
```

**Comment by waruqi** [comment]
> PowerShell has supported access files and paths inside WSL2.

powershell support it, but xmake maybe does not support it. xmake use the native Win32 API to access windows path. It seems not support it.

I don't have a windows wsl2 environment at the moment to test and improve it further. You can open a pr to improve it.

**Comment by SirLynix** [comment]
Isn't it because xmake processes paths and deduplicate (back)slashes? (turning //wsl.localhost into \wsl.localhost)

**Comment by waruqi** [comment]
I have improved it, you can try it again. `xmake update dev`

**Comment by waruqi** [comment]
It should work.
