### ISSUE TITLE
unxpected `-I` in compile_command.json

### ISSUE THREAD

**Issue by garfieldkwong** [xmake-io/xmake#3020]
### Xmake Version

v2.7.2+202210241457

### Operating System Version and Architecture

Ubuntu 22.04

### Describe Bug

xmake use the flag `-isystem` for the package include path. But when generating the compile_command.json, it is `-I`

```
/usr/bin/clang-15 -c -Qunused-arguments -m64 -g -Wall -Wextra -Werror -O0 -std=c++2b -isystem <boost-path>/include -o build/.objs/y/linux/x86_64/debug/src/main.cpp.o src/main.cpp
```

compile_command.json:
```
{
  "directory": "<home-path>",
  "arguments": ["/usr/bin/clang-15", "-c", "-Qunused-arguments", "-m64", "-g", "-Wall", "-Wextra", "-Werror", "-O0", "-std=c++2b", "-I", "<boost-path>/include", "-o", "build/.objs/y/linux/x86_64/debug/src/main.cpp.o", "src/main.cpp"],
  "file": "src/main.cpp"
},
```

### Expected Behavior

should generate the following in compile_command.json
```
{
  "directory": "<home-path>",
  "arguments": ["/usr/bin/clang-15", "-c", "-Qunused-arguments", "-m64", "-g", "-Wall", "-Wextra", "-Werror", "-O0", "-std=c++2b", "-isystem", "<boost-path>/include", "-o", "build/.objs/y/linux/x86_64/debug/src/main.cpp.o", "src/main.cpp"],
  "file": "src/main.cpp"
},
```

**Comment by waruqi** [comment]
I remember previous feedback from users that cpptools or clangd did not yet support parsing headers from `-isystem`, so xmake uses `-I` to provide better compatibility.

**Comment by garfieldkwong** [comment]
> I remember previous feedback from users that cpptools or clangd did not yet support parsing headers from `-isystem`, so xmake uses `-I` to provide better compatibility.
> 
> Also, `"-I", "/xx"` are valid arguments and the LSP should support it. If they don't support it, you should go to clangd or cpptools and give feedback on the problem.

So could we have an argument to adjust it?

**Comment by garfieldkwong** [comment]
And according to https://clangd.llvm.org/guides/system-headers#search-directories-mentioned-with-compile-flags, clangd does support "-isystem"

and by my testings, when I replace all "-I" with "-isystem" in compile_commands.json, both clangd and clang-tidy respect the "-isystem" in compile_commands.json

**Comment by waruqi** [comment]
Not only clangd, but also many LSPs, cpptools/ccls ... There is no guarantee that all LSPs will support -isystem, but -I is certainly the most compatible.

**Comment by garfieldkwong** [comment]
So could we have an argument to adjust it? Since -isystem will ignore the warning and tidy error but -I will still have it.

**Comment by waruqi** [comment]
no arguments now.

**Comment by waruqi** [comment]
I added a `--lsp=clangd` argument to improve it for clangd.

```
xmake project -k compile_commands --lsp=clangd
```
