### ISSUE TITLE
Add flags for specific compilers and linkers 

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#3022]
### Is your feature request related to a problem? Please describe.

Usually, we need to add specific flags in the script scope in order to determine the compiler name.

```lua
target("test")
    on_config(function (target)
         if target:has_tool("cxx", "clang") then
             target:add("cxxflags", "-stdlib=libc++")
         end
    end)
```

### Better solution1

For the same flags, we can also easily append them to different.

However, it can only be used for compilation tools and cannot be extended to other types.

```lua
add_cxxflags("clang::-stdlib=libc++")
add_cxxflags("gcc::-stdlib=libc++")
```

and if there are a lot of flags, it will be `add_cxxflags("clang::-stdlib=libc++", "clang::xxx", "clang::yyy", "clang::zz")`

### Better solution2

```lua
add_cxxflags("-stdlib=libc++", {tools = "clang"})
add_cxxflags("-stdlib=libc++", {tools = "gcc"})
```

it will override tools, always is gcc

### Other solutions

...

It will override tools, it always is gcc.

**Comment by waruqi** [comment]
I have supported both solutions.

**Comment by Jeangowhy** [comment]
it doesn't work in Windows 10 MinGW GCC. Much more, flags can't cover the default value:
```
    add_cxxflags("-fmodules-ts", { tools = "gcc" })
    add_cxxflags("-o module-ixx", { tools = "gcc" })

C:\mingw-w64\x86_64-12.2.0-release-win32-seh-ucrt-rt_v10-rev2\bin\x86_64-w64-mingw32-g++ -c -m64 -g -O0 -std=c++20 module-ixx/hello.ixx module-ixx/world.ixx -o build\.objs\module-ixx\mingw\x86_64\debug\modules_ixx\app.cpp.obj modules_ixx\app.cpp
```

**Comment by adamdusty** [comment]
> it doesn't work in Windows 10 MinGW GCC. Much more, flags can't cover the default value:
> 
> ```
>     add_cxxflags("-fmodules-ts", { tools = "gcc" })
>     add_cxxflags("-o module-ixx", { tools = "gcc" })
> 
> C:\mingw-w64\x86_64-12.2.0-release-win32-seh-ucrt-rt_v10-rev2\bin\x86_64-w64-mingw32-g++ -c -m64 -g -O0 -std=c++20 module-ixx/hello.ixx module-ixx/world.ixx -o build\.objs\module-ixx\mingw\x86_64\debug\modules_ixx\app.cpp.obj modules_ixx\app.cpp
> ```

I'm having the same issue, and haven't found a resolution. I'm curious if it has anything to do with mingw being treated as cross compilation.

**Comment by waruqi** [comment]
tools = "gxx"
