### ISSUE TITLE
clang编译器参数“-fcxx-exceptions”被意外添加到gcc编译器导致无法编译

### ISSUE THREAD

**Issue by sharedwonder** [xmake-io/xmake#3027]
### Xmake 版本

2.7.2 (dev/master)

### 操作系统版本和架构

Windows 11 version 22H2 build 22621.674

### 描述问题

使用工具链：gcc/mingw编译报错如下：
```
x86_64-w64-mingw32-gcc: error: unrecognized command-line option '-fcxx-exceptions'; did you mean '-fno-exceptions'?
```
- msvc和clang正常

经过查找资料，发现“-fcxx-exceptions”是clang的参数，gcc下无效

在使用最新版本（[xmake-master.win64.exe](https://github.com/xmake-io/xmake/releases/download/v2.7.2/xmake-master.win64.exe)和[xmake-dev.win64.exe](https://github.com/xmake-io/xmake/releases/download/v2.7.2/xmake-dev.win64.exe)）会出现此问题

我再尝试了以前的版本（[xmake-v2.7.2.win64.exe](https://github.com/xmake-io/xmake/releases/download/v2.7.2/xmake-v2.7.2.win64.exe)），它正常完成了编译

### 期待的结果

在使用gcc编译时不应该出现“-fcxx-exceptions”参数

**Comment by waruqi** [comment]
再试试，xmake update -s dev

**Comment by waruqi** [comment]
再试试，xmake update -s dev

**Comment by ass-killer67** [comment]
> 再试试，xmake update -s dev

我在clion使用xmake插件的时候也出现了 '-fcxx-exceptions，同时我在将其改为-fno-exceptions后build出现了skipping incompatible，也即链接器找不到对应的库，在cmake中还发现了$<$<COMPILE_LANGUAGE:CXX>:-m32>其使用了32位架构，而我的机器是64位架构的

**Comment by supf1994** [comment]
这个问题在v2.8.5的版本上依然存在

**Comment by waruqi** [comment]
dev 版本，最近修复过这个问题  https://github.com/xmake-io/xmake/pull/4387/files
