### ISSUE TITLE
toolchain not found!

### ISSUE THREAD

**Issue by StarBeat** [xmake-io/xmake#3030]
### Xmake 版本

xmake v2.7.2+HEAD.d88193698,

### 操作系统版本和架构

window 10 21H2 19044.2130

### 描述问题

vs 2019 编译会报编译器内部错误(另一台机器 vs2022 正常编译),遂安装 vs 2022 然而xmake还是选择 2019 作为编译收选项,卸载 vs2019后出现无法找到工具链。
powershell 执行 cl.exe 如下:
···
PS C:\Users\xinyt> cl
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.34.31933 版
版权所有(C) Microsoft Corporation。保留所有权利。

用法: cl [ 选项... ] 文件名... [ /link 链接选项... ]
···

### 期待的结果

正常识别vs 2022 

### 附加信息和错误日志

checkinfo: @programdir\core\sandbox\modules\os.lua:267: cannot runv(cl.exe ), No such file or directory
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:897]:
    [@programdir\core\sandbox\modules\os.lua:267]: in function 'runv'
    [@programdir\modules\detect\tools\find_cl.lua:41]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [...\core\sandbox\modules\import\lib\detect\find_program.lua:65]: in function '_do_check'
    [...\core\sandbox\modules\import\lib\detect\find_program.lua:88]: in function '_check'
    [...\core\sandbox\modules\import\lib\detect\find_program.lua:237]: in function '_find'
    [...\core\sandbox\modules\import\lib\detect\find_program.lua:304]:
    [@programdir\modules\detect\tools\find_cl.lua:44]:
    [@programdir\modules\lib\detect\find_tool.lua:33]: in function '_find_from_modules'
    [@programdir\modules\lib\detect\find_tool.lua:48]: in function '_find_tool'
    [@programdir\modules\lib\detect\find_tool.lua:100]:
    [@programdir\toolchains\msvc\check.lua:72]: in function '_check_vsenv'
    [@programdir\toolchains\msvc\check.lua:86]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\tool\toolchain.lua:259]: in function 'check'
    [@programdir\core\platform\platform.lua:247]: in function 'check'
    [@programdir\actions\config\main.lua:439]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\base\task.lua:501]: in function 'run'
    [@programdir\core\sandbox\modules\import\core\base\task.lua:63]: in function 'run'
    [@programdir\actions\build\main.lua:139]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\base\task.lua:501]: in function 'run'
    [@programdir\core\main.lua:278]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:404]:

checking for cl.exe ... no
checkinfo: @programdir\core\sandbox\modules\os.lua:267: cannot runv(cl.exe ), No such file or directory
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:897]:
    [@programdir\core\sandbox\modules\os.lua:267]: in function 'runv'
    [@programdir\modules\detect\tools\find_cl.lua:41]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [...\core\sandbox\modules\import\lib\detect\find_program.lua:65]: in function '_do_check'
    [...\core\sandbox\modules\import\lib\detect\find_program.lua:88]: in function '_check'
    [...\core\sandbox\modules\import\lib\detect\find_program.lua:237]: in function '_find'
    [...\core\sandbox\modules\import\lib\detect\find_program.lua:304]:
    [@programdir\modules\lib\detect\find_tool.lua:58]: in function '_find_tool'
    [@programdir\modules\lib\detect\find_tool.lua:100]:
    [@programdir\toolchains\msvc\check.lua:72]: in function '_check_vsenv'
    [@programdir\toolchains\msvc\check.lua:86]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\tool\toolchain.lua:259]: in function 'check'
    [@programdir\core\platform\platform.lua:247]: in function 'check'
    [@programdir\actions\config\main.lua:439]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\base\task.lua:501]: in function 'run'
    [@programdir\core\sandbox\modules\import\core\base\task.lua:63]: in function 'run'
    [@programdir\actions\build\main.lua:139]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\base\task.lua:501]: in function 'run'
    [@programdir\core\main.lua:278]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:404]:

checking for cl.exe ... no
checking for Microsoft Visual Studio (x64) version ... no
checkinfo: cannot runv(clang.exe --version), No such file or directory
checking for clang ... no
checkinfo: cannot runv(dmd.exe --version), No such file or directory
checking for dmd ... no
checkinfo: cannot runv(ldc2.exe --version), No such file or directory
checking for ldc2 ... no
checkinfo: cannot runv(gdc.exe --version), No such file or directory
checking for gdc ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(unzip.exe -v), No such file or directory
checking for unzip ... no
checking for 7z ... C:\Program Files\xmake\winenv\bin\7z
checking for git ... ok
checkinfo: cannot runv(gzip.exe --version), No such file or directory
checking for gzip ... no
git rev-parse HEAD
finding lua from xmake ..
checking for xmake::lua ... lua v5.4.4
finding taskflow from xmake ..
checking for xmake::taskflow ... taskflow v3.4.0
checking for cmake ... C:\Program Files\CMake\bin\cmake
checking for cmake ... C:\Program Files\CMake\bin\cmake
finding mimalloc from xmake ..
checking for xmake::mimalloc ... mimalloc 2.0.6

**Comment by waruqi** [comment]
```console
xmake g -c
xmake f -c
xmake
```

试下

**Comment by StarBeat** [comment]
这么及时，问题已解决，看来要好好学学这些参数
