### ISSUE TITLE
XMake stucked with C++20 modules

### ISSUE THREAD

**Issue by Arthapz** [xmake-io/xmake#3031]
### Xmake Version

v2.7.2+HEAD.d88193698,

### Operating System Version and Architecture

Windows 11 Version 22H2 22623.875

### Describe Bug

When building a large project with C++20 modules, XMake stuck indefinitly as you can see on this vcperf

![image](https://user-images.githubusercontent.com/27437334/200179843-0090ccd6-9d90-46e7-a77a-efe4a0ac6982.png)
[vcperf.txt](https://github.com/xmake-io/xmake/files/9946395/b.txt)
(you need to rename to .json and use a chrome trace viewer like ui.perfetto.dev)

i got the callstack and XMake seems to stuck on 

```
xmake b -j1
<subprocess: cmd>: cmd /c ver
<subprocess: git>: git rev-parse --abbrev-ref HEAD
<subprocess: git>: git rev-parse --verify HEAD
[xmake]: [engine]: stack traceback:
        @programdir\core\base\hashset.lua: in for iterator 'for iterator'
        @programdir\modules\private\async\jobpool.lua:189: in method '_genleafjobs'
        @programdir\modules\private\async\jobpool.lua:189: in method '_genleafjobs'
        @programdir\modules\private\async\jobpool.lua:185: in for iterator 'for iterator'
        @programdir\modules\private\async\jobpool.lua:189: in method '_genleafjobs'
        @programdir\modules\private\async\jobpool.lua:189: in method '_genleafjobs'
        @programdir\modules\private\async\jobpool.lua:189: in method '_genleafjobs'
        @programdir\modules\private\async\runjobs.lua:183: in function <@programdir\modules\private\async\runjobs.lua:162>
        @programdir\core\base\scheduler.lua:520: in function 'base/scheduler.co_group_begin'
        @programdir\modules\private\async\runjobs.lua:183: in function <@programdir\modules\private\async\runjobs.lua:162>
        ...     (skipping 2 levels)
        @programdir\actions\build\main.lua:108: in global '_do_build'
        [C]: in function 'xpcall'
        @programdir\core\base\utils.lua:280: in function 'base/utils.trycall'
        @programdir\actions\build\build.lua:257: in function <@programdir\actions\build\build.lua:245>
        (...tail calls...)
        @programdir\core\sandbox\modules\try.lua:117: in global 'try'
        @programdir\actions\build\main.lua:147: in function <@programdir\actions\build\main.lua:113>
        (...tail calls...)
        [C]: in function 'xpcall'
        @programdir\actions\build\main.lua:147: in function <@programdir\actions\build\main.lua:113>
        (...tail calls...)
        @programdir\core\sandbox\modules\try.lua:117: in global 'try'
        [C]: in function 'xpcall'
        @programdir\actions\build\main.lua:155: in function <@programdir\actions\build\main.lua:149>
        [C]: in function 'xpcall'
```

so maybe here there is a infinite loop (maybe something is wrong with my project, but XMake should not be stuck)

### Expected Behavior

XMake build or fail, but not stucked

### Project Configuration

you can try with my projet 

```
> git clone https://github.com/TapzCrew/StormKit.git --depth 1 -b modulify
> cd StormKit
> xmake f "--kind=static" "--mode=release" "--plat=windows" "--arch=x64" "--enable_wsi_x11=no" "--enable_applications=no" "--enable_wsi_wayland=no" "--enable_engine=no" "--enable_entities=yes" "--enable_log=yes" "--enable_examples=no" "--unity_build=no" "--enable_wsi=yes" "--enable_image=yes" "--enable_gpu=yes"

> xmake b
```

**Comment by Arthapz** [comment]
oh i think it's because i have a circular dependency in my project

**Comment by waruqi** [comment]
> > xmake f "--kind=static" "--mode=release" "--plat=windows" "--arch=x64" "--enable_wsi_x11=no" "--enable_applications=no" "--enable_wsi_wayland=no" "--enable_engine=no" "--enable_entities=yes" "--enable_log=yes" "--enable_examples=no" "--unity_build=no" "--enable_wsi=yes" "--enable_image=yes" "--enable_gpu=yes"

invalid options for `--enable_applications=no`, `--enable_engine=no`, ...

main branch?

**Comment by waruqi** [comment]
I checkout modulify branch. It does not stuk, but it has other errors.

![image](https://user-images.githubusercontent.com/151335/200213953-cd097ead-125a-46de-afbe-e112e2df7c9d.png)

**Comment by waruqi** [comment]
I checkout modulify branch, it does not stuk for me, but it has some other errors.

![image](https://user-images.githubusercontent.com/151335/200214537-4e474afc-acbf-44b5-98d4-98fa17681776.png)

**Comment by Arthapz** [comment]
> I checkout modulify branch, it does not stuk for me, but it has some other errors.
> 
> msvc has only std.core, not std.
> 
> ![image](https://user-images.githubusercontent.com/151335/200214537-4e474afc-acbf-44b5-98d4-98fa17681776.png)

i know, std module is mine not msvc one so it should work as it work on my machine 🤔 (https://asciinema.org/a/CVvpPlLRijP3GPYnqmGBWQ9bR)

**Comment by Arthapz** [comment]
ah maybe it's because i'm using VS 17.4 preview 6, i'll try with latests not preview msvc

**Comment by waruqi** [comment]
> https://asciinema.org/a/CVvpPlLRijP3GPYnqmGBWQ9bR)

Have you fixed the stuck problem? I saw it work in your video.

**Comment by Arthapz** [comment]
> > https://asciinema.org/a/CVvpPlLRijP3GPYnqmGBWQ9bR)
> 
> Have you fixed the stuck problem? I saw it work in your video.

at the end, xmake is stuck in an infinite loop (with the  print table)


i made a small example [simple_test.zip](https://github.com/xmake-io/xmake/files/9951341/simple_test.zip)

**Comment by waruqi** [comment]
OK, I'll improve it by providing more friendly error messages, and you can modifying the module code to avoid circular dependencies first.

**Comment by waruqi** [comment]
try this `xmake update -s github:xmake-io/xmake#moduledeps`

please remove `build` first.

```console
$ rm -rf build/;xmake
[  0%]: generating.cxx.module.deps Foo.mpp
[  0%]: generating.cxx.module.deps Foo2.mpp
[  0%]: generating.cxx.module.deps Foo3.mpp
[  0%]: generating.cxx.module.deps main.cpp
error: circular modules dependency(Foo2, Foo, Foo3, Foo2) detected!
  -> module(Foo2) in Foo2.mpp
  -> module(Foo) in Foo.mpp
  -> module(Foo3) in Foo3.mpp
  -> module(Foo2) in Foo2.mpp
```

**Comment by Arthapz** [comment]
it work fine !
