### ISSUE TITLE
Provide a way to clean the caches while preserving the options

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#3046]
### 你在什么场景下需要该功能？

目前的`xmake f -c`在清除缓存时会同时也清除已设置的option。然而很多时候只是有些工具发生变化需要重新查找，运行`xmake f -c`之后还要再设置一遍原来的option非常麻烦，也容易出错

### 描述可能的解决方案

提供一个`xmake f --reconfig`或者`xmake f --clean-cache`命令，只清理cache，保留已设置的各option

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/pull/3099

加了，可以先试下：`xmake f --check` 强制重新探测所有，但是不清先前的用户配置。

**Comment by SirLynix** [comment]
如果`xmake g -c'也有同样的可能性就好了，它可以清除全局配置。

**Comment by waruqi** [comment]
> 如果`xmake g -c'也有同样的可能性就好了，它可以清除全局配置。

添加了
