### ISSUE TITLE
xmake failed to install package with a git branch

### ISSUE THREAD

**Issue by XimingCheng** [xmake-io/xmake#3047]
### Xmake Version

v2.7.3+HEAD.b35ff3118

### Operating System Version and Architecture

Windows10

### Describe Bug

with xmake.lua
add_requires("imgui docking")

xmake f -c -vD
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> imgui docking [vs_runtime:"MT"]
please input: y (y/n/m)
y
checking for ping ... ok
pinging for the host(github.com) ... 65535 ms
git -c core.fsmonitor=false clean -d -f -x
git -c core.fsmonitor=false reset --hard
HEAD is now at d7aca16 Backends: SDL: Fixed drag'n drop crossing a viewport border losing mouse coordinates. (#5710, #5012)
error: ...xmake\repositories\xmake-repo\packages\i\imgui\xmake.lua:70: attempt to index a nil value
stack traceback:
    [...xmake\repositories\xmake-repo\packages\i\imgui\xmake.lua:70]: in function 'script'
    [...dir\modules\private\action\require\impl\utils\filter.lua:125]: in function 'call'
    [...\modules\private\action\require\impl\actions\install.lua:304]:

  => install imgui docking .. failed
error: @programdir\modules\private\async\runjobs.lua:256: ...\modules\private\action\require\impl\actions\install.lua:410: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:897]:
    [...\modules\private\action\require\impl\actions\install.lua:410]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:268]:
    [...modules\private\action\require\impl\install_packages.lua:479]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:232]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:897: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir\modules\private\async\runjobs.lua:256: in field 'catch'
        @programdir\core\sandbox\modules\try.lua:123: in global 'try'
        @programdir\modules\private\async\runjobs.lua:218: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>

### Expected Behavior

install ok

**Comment by XimingCheng** [comment]
`package:version()` in imgui xmake.lua is nil when using `add_requires("imgui docking")`

**Comment by waruqi** [comment]
xrepo update-repo

**Comment by XimingCheng** [comment]
Thanks! It is ok now.
