### ISSUE TITLE
targets in loops are not ended correctly

### ISSUE THREAD

**Issue by 6ziv** [xmake-io/xmake#3048]
### Xmake Version

v2.7.3+dev.b3bec1b2f

### Operating System Version and Architecture

Windows 11 version 22H2 (22621.819)

### Describe Bug

targets in loops does not work correctly.

Just take what is provided in https://github.com/xmake-io/xmake/issues/1577 as an example:

    for _, arch in ipairs({"x86", "x64"}) do
        add_requires("libcurl~" .. arch, {arch = arch})
        target("getHTTPdata" .. arch)
            set_arch(arch)
            set_kind("binary")
            add_files("getHTTPdata.cpp")
            add_packages("libcurl~" .. arch)
    end
`

### Expected Behavior

The add_reference statement should be equivant to 

    add_requires("libcurl~x86", {arch = "x86"})
    add_requires("libcurl~x64", {arch = "x64"})
`

### Project Configuration

Attachment:  [a.zip](https://github.com/xmake-io/xmake/files/9991316/a.zip), which contains the xmake.lua as mentioned, and a minimal compilable cpp file

### Additional Information and Error Logs

-vD output is stored in [error.log](https://github.com/xmake-io/xmake/files/9991330/error.log)
In a word, xmake complains about  requires() called in target(), which does not happen in this configuration.

Adding "target_end()" at the end of the loop seems to fix. It seems that targets are not automatically ended as loop iterates. 

Maybe document should be updated to recommend manually calling "target_end()" more often? Or, can "target()" be made a function-like macro, which initializes a scope-guard as well? (I have never used Lua before, so I'm not sure if it can be done.)

**Comment by SirLynix** [comment]
> Maybe document should be updated to recommend manually calling "target_end()" more often? Or, can "target()" be made a function-like macro, which initializes a scope-guard as well? (I have never used Lua before, so I'm not sure if it can be done.)

XMake 2.7.3 added support for this syntax which automatically calls target_end()
```lua
for _, arch in ipairs({"x86", "x64"}) do
    add_requires("libcurl~" .. arch, {arch = arch})
    target("getHTTPdata" .. arch, function ()
        set_arch(arch)
        set_kind("binary")
        add_files("getHTTPdata.cpp")
        add_packages("libcurl~" .. arch)
    end)
end
```
