### ISSUE TITLE
add_installfiles可以重命名文件

### ISSUE THREAD

**Issue by jingkaimori** [xmake-io/xmake#3058]
### 你在什么场景下需要该功能？

cmake提供了`install( RENAME`接口，通过该接口定义的安装文件，安装时会改变文件名

### 描述可能的解决方案

```lua
add_installfile("oldname.txt",{filename="newname.txt"})
```

**Comment by waruqi** [comment]
add_installfiles 是批量安装接口，还要支持 `*` 模式匹配，无法单独对一个文件配置重命名

暂时我不考虑加新接口，这种特殊需求，自己 after_install 里面搞搞，也就一两行配置的事情

```lua
after_install(function (target)
    os.cp("xxx/oldname", path.join(target:installdir(), "newname"))
end)
```
