### ISSUE TITLE
Xmake cannot find package glut 

### ISSUE THREAD

**Issue by drcxd** [xmake-io/xmake#3063]
### Xmake Version

2.7.3

### Operating System Version and Architecture

Windows 10 20H2

### Describe Bug

1. Create a new project with `xmake create -l c++ -P xtest`
2. Add opengl, glu, glut packages and build.
3. Get error message
```
error: The packages(glut) not found, please run `xmake repo -u` first!
```

### Expected Behavior

glut should be found, since its in the repo.

### Project Configuration

```
add_rules("mode.debug", "mode.release")

add_requires("opengl", "glu", "glut")
-- add_requires("opengl", "glu")

target("gltest")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("opengl", "glu", "glut")
    -- add_packages("opengl", "glu")
    set_toolchains("clang")
```

**Comment by waruqi** [comment]
glut is fetchonly package, it will not be installed if not found. you can use `freeglut` package for windows.

**Comment by drcxd** [comment]
I don't understand what is a fetch-only package? Is this issue exclusive on Windows?

**Comment by waruqi** [comment]
> I don't understand what is a fetch-only package? Is this issue exclusive on Windows?

there is only on_fetch in package(). it just can find libraries on your system and will not install them. like glut, opengl,... 

https://github.com/xmake-io/xmake-repo/blob/9c5059214aabe8aaac38e77b200af63150517b94/packages/g/glut/xmake.lua#L10

**Comment by waruqi** [comment]
Why are they fetchonly packages?

1. For copyright reasons, Xmake cannot distribute them, so users have to install them themselves.
2. There are a lot of dependencies or writing package installation scripts requires a lot of work and the developer does not have enough time to write them at the moment, and can only temporarily provide fetch scripts to find them from the system.  like glut, gtk+3 .. Users are of course welcome to submit pr to include these packages.

**Comment by drcxd** [comment]
Thanks for the detailed explanation.
