### ISSUE TITLE
Documentation correction

### ISSUE THREAD

**Issue by matty0ung** [xmake-io/xmake#3077]
At https://xmake.io/#/guide/syntax_description?id=configuration-separation, it says "Xmake.lua uses the 28th principle" and then goes on to discuss the 80:20 split between simple and complex configuration needs.  It's possible that I'm misunderstanding, but I never heard of this described in English as the "28th principle".  Wouldn't it be more idiomatic to say "the Pareto principle" (see https://en.wikipedia.org/wiki/Pareto_principle).

**Comment by waruqi** [comment]
Sorry, my English is not good, I used google translate for the English document, you can open a pr to help fix it.
