### ISSUE TITLE
cxxlatest生成的compile_commands.json无法被正确识别

### ISSUE THREAD

**Issue by MaxwellGengYF** [xmake-io/xmake#3081]
### Xmake 版本

2.7.3

### 操作系统版本和架构

Windows 10

### 描述问题

toolchain为clang-cl/msvc，使用set_languages("cxxlatest")时，在compile_commands.json中会生成"-std:c++latest"，这无法被clangd正确识别。

### 期待的结果

根据编译器版本生成可以被识别的版本号，如"-std:c++20"

**Comment by waruqi** [comment]
这个目前没办法，生成 compile_commands 时候，xmake 是没法知道用于 clangd 还是其他 ，只能根据当前 clang/cl 自身编译的支持力度 来映射 flags的，所以目前只能用户自己 set_languages 改成 c++20 来调整

我感觉这个给 clangd 去反馈更好些

**Comment by inclyc** [comment]
clang-cl 是否可以传入 -std:c++latest ？

**Comment by inclyc** [comment]
Link: https://github.com/clangd/clangd/issues/1383
