### ISSUE TITLE
Add MSVC support for `import std` when VS 2022 17.5 releases

### ISSUE THREAD

**Issue by Qudix** [xmake-io/xmake#3084]
### Xmake Version

v2.7.3+HEAD.b35ff3118

### Operating System Version and Architecture

Windows 11

### Describe Bug

https://github.com/microsoft/STL/wiki/Changelog#vs-2022-175-preview-1
https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview

As of the VS 2022 17.5 Preview, the standard library modules now take on the more universal naming scheme `std` and `std.compat` and can be located in the following folder:
```bat
"C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32019\modules"
Length | Name
14241    std.compat.ixx
3194     std.ixx
```

They are not precompiled anymore to support a wide variety of configurations and must be compiled before use.

At the moment when compiling modules xmake uses the previous experimental location and naming scheme for the modules and will need to be updated to consider the official ones as well. You can also consider dropping the old location as that's pretty much dead now.

### Expected Behavior

`import std` must compile on MSVC

**Comment by waruqi** [comment]
But I have not VS 2022 17.5 Preview now.

**Comment by Qudix** [comment]
I suppose it would be best to wait for 17.5 to leave preview and enter release

**Comment by waruqi** [comment]
It has been merged. https://github.com/xmake-io/xmake/pull/3168
