### ISSUE TITLE
xmake无法在带有@字符的交叉编译工具链路径下正常工作

### ISSUE THREAD

**Issue by bmsleft** [xmake-io/xmake#3102]
### Xmake Version

 v2.7.1+202208261018

### Operating System Version and Architecture

Ubuntu 1804

### Describe Bug

xmake无法在带有@字符的路径下正常工作， 报如下err:
/home/bsw-boyan/boyan_cicd/workspace/auto-boyan/boyan_arm64_prebuild@2/arm_build_dir/out/build//logger out of source build
build all
logger build script....
error: ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:56: cannot find known tool script for /home/bsw-boyan/boyan_cicd/workspace/auto-boyan/boyan_arm64_prebuild
stack traceback:
        @programdir/core/base/utils.lua:290: in function <@programdir/core/base/utils.lua:280>
        [C]: in function 'error'
        @programdir/core/base/os.lua:882: in function 'os.raiselevel'
        (...tail calls...)
        ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:56: in field 'co_start_withopt'
        @programdir/modules/private/async/runjobs.lua:217: in function <@programdir/modules/private/async/runjobs.lua:162>
        [C]: in function 'xpcall'
        @programdir/core/base/utils.lua:280: in function 'sandbox/modules/utils.trycall'
        @programdir/core/base/scheduler.lua:504: in function 'base/scheduler.co_group_begin'
        ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:94: in field 'co_group_begin'
        @programdir/modules/private/async/runjobs.lua:162: in function <@programdir/modules/private/async/runjobs.lua:56>
        (...tail calls...)
        @programdir/actions/build/build.lua:246: in function <@programdir/actions/build/build.lua:234>
        (...tail calls...)
        @programdir/actions/build/main.lua:103: in global '_do_build'
        @programdir/actions/build/main.lua:150: in function <@programdir/actions/build/main.lua:144>
        [C]: in function 'xpcall'
        @programdir/core/base/utils.lua:280: in function 'sandbox/modules/utils.trycall'
        @programdir/core/sandbox/modules/try.lua:121: in global 'try'
        @programdir/actions/build/main.lua:142: in function <@programdir/actions/build/main.lua:108>
        (...tail calls...)
        [C]: in function 'xpcall'
        @programdir/core/base/utils.lua:280: in function 'sandbox/modules/utils.trycall'
        (...tail calls...)
        @programdir/core/base/task.lua:501: in function 'base/task.run'
        @programdir/core/main.lua:278: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:388: in function <@programdir/core/base/scheduler.lua:385>

### Expected Behavior

正常编译

**Comment by waruqi** [comment]
贴完整执行命令，logs，xmake.lua 配置

**Comment by bmsleft** [comment]
root@bsw-boyan:/home/bsw-boyan/boyan_cicd/workspace/auto-boyan/boyan_arm64_prebuild@2/arm_build_dir/logger# xmake f -p cross -a $ARCH -m $TARGET_MODE --sdk=${SRC_HOST_DIR}/${TOOLCHAIN_NAME} --enable_boyan_sdk=$ENABLE_BOYAN_SDK -o ${BUILD_OUTPUT_PATH}/build
root@bsw-boyan:/home/bsw-boyan/boyan_cicd/workspace/auto-boyan/boyan_arm64_prebuild@2/arm_build_dir/logger# xmake
error: cannot find known tool script for /home/bsw-boyan/boyan_cicd/workspace/auto-boyan/boyan_arm64_prebuild
root@bsw-boyan:/home/bsw-boyan/boyan_cicd/workspace/auto-boyan/boyan_arm64_prebuild@2/arm_build_dir/logger# xmake -v
error: ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:56: cannot find known tool script for /home/bsw-boyan/boyan_cicd/workspace/auto-boyan/boyan_arm64_prebuild
stack traceback:
        @programdir/core/base/utils.lua:290: in function <@programdir/core/base/utils.lua:280>
        [C]: in function 'error'
        @programdir/core/base/os.lua:882: in function 'os.raiselevel'
        (...tail calls...)
        ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:56: in field 'co_start_withopt'
        @programdir/modules/private/async/runjobs.lua:217: in function <@programdir/modules/private/async/runjobs.lua:162>
        [C]: in function 'xpcall'
        @programdir/core/base/utils.lua:280: in function 'base/utils.trycall'
        @programdir/core/base/scheduler.lua:504: in function 'base/scheduler.co_group_begin'
        ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:94: in field 'co_group_begin'
        @programdir/modules/private/async/runjobs.lua:162: in function <@programdir/modules/private/async/runjobs.lua:56>
        (...tail calls...)
        @programdir/actions/build/build.lua:246: in function <@programdir/actions/build/build.lua:234>
        (...tail calls...)
        @programdir/actions/build/main.lua:103: in global '_do_build'
        @programdir/actions/build/main.lua:150: in function <@programdir/actions/build/main.lua:144>
        [C]: in function 'xpcall'
        @programdir/core/base/utils.lua:280: in function 'base/utils.trycall'
        @programdir/core/sandbox/modules/try.lua:121: in global 'try'
        @programdir/actions/build/main.lua:142: in function <@programdir/actions/build/main.lua:108>
        (...tail calls...)
        [C]: in function 'xpcall'
        @programdir/core/base/utils.lua:280: in function 'base/utils.trycall'
        (...tail calls...)
        @programdir/core/base/task.lua:501: in function 'base/task.run'
        @programdir/core/main.lua:278: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:388: in function <@programdir/core/base/scheduler.lua:385>
root@bsw-boyan:/home/bsw-boyan/boyan_cicd/workspace/auto-boyan/boyan_arm64_prebuild@2/arm_build_dir/logger#

**Comment by bmsleft** [comment]
看起来是交叉编译工具链路径带了@之后不行的。

**Comment by waruqi** [comment]
> 看起来是交叉编译工具链路径带了@之后不行的。

@ 有特殊用途，`--cxx=gcc@/xxxx/xxxx/arm-cc` 强制作为 gcc 编译器。 所以你传入 `--sdk=` 的路径，避免带 `@` 自己改下
