### ISSUE TITLE
在vscode的xmake插件创建qt.widgetapp_static项目中xmake的build会报错

### ISSUE THREAD

**Issue by QQ-CN** [xmake-io/xmake#3103]
### Xmake 版本

2.7.3

### 操作系统版本和架构

Windows11 版本21H2

### 描述问题

编译的工具链为clang-cl
以下是xmake 执行 xmake f --qt=~/qt6/qt6.4.1输出的信息
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Qt SDK directory ... D:/Qt6/6.4.1/msvc2019_64
checking for Qt SDK version ... 6.4.1
执行xmake build 命令
在链接时报错：error: LINK : fatal error LNK1181: 无法打开输入文件“qsvg.lib”
后面把工具链换成msvc，也是同样的报错

### 期待的结果

能够编译成功

### 工程配置

这个配置就是 xmake创建的基础工程

### 附加信息和错误日志

[ 12%]: compiling.qt.ui src\mainwindow.ui
D:\Qt6\6.4.1\msvc2019_64\bin\uic.exe src\mainwindow.ui -o build\.gens\chinese_chess\windows\x64\release\rules\qt\ui\ui_mainwindow.h
[ 25%]: compiling.qt.moc src\mainwindow.h
D:\Qt6\6.4.1\msvc2019_64\bin\moc.exe -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_SVG_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_PRINTSUPPORT_LIB -DQT_PLATFORMCOMPOSITORSUPPORT_LIB -DQT_WIDGETS_LIB -D_WINDOWS -ID:/VSC_Qt/chinese_chess/build/.gens/chinese_chess/windows/x64/release/rules/qt/ui -ID:/Qt6/6.4.1/msvc2019_64/include/QtSvg -ID:/Qt6/6.4.1/msvc2019_64/include/QtSvg/6.4.1 -ID:/Qt6/6.4.1/msvc2019_64/include/QtSvg/6.4.1/QtSvg -ID:/Qt6/6.4.1/msvc2019_64/include/QtGui -ID:/Qt6/6.4.1/msvc2019_64/include/QtGui/6.4.1 -ID:/Qt6/6.4.1/msvc2019_64/include/QtGui/6.4.1/QtGui -ID:/Qt6/6.4.1/msvc2019_64/include/QtCore -ID:/Qt6/6.4.1/msvc2019_64/include/QtCore/6.4.1 -ID:/Qt6/6.4.1/msvc2019_64/include/QtCore/6.4.1/QtCore -ID:/Qt6/6.4.1/msvc2019_64/include/QtPrintSupport -ID:/Qt6/6.4.1/msvc2019_64/include/QtPrintSupport/6.4.1 -ID:/Qt6/6.4.1/msvc2019_64/include/QtPrintSupport/6.4.1/QtPrintSupport -ID:/Qt6/6.4.1/msvc2019_64/include/QtWidgets -ID:/Qt6/6.4.1/msvc2019_64/include/QtWidgets/6.4.1 -ID:/Qt6/6.4.1/msvc2019_64/include/QtWidgets/6.4.1/QtWidgets -ID:/Qt6/6.4.1/msvc2019_64/include -ID:/Qt6/6.4.1/msvc2019_64/mkspecs/win32-msvc src\mainwindow.h -o build\.gens\chinese_chess\windows\x64\release\src\moc_mainwindow.cpp
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\cl.exe -c -nologo -O2 -fp:fast -std:c++17 -ID:\VSC_Qt\chinese_chess\build\.gens\chinese_chess\windows\x64\release\rules\qt\ui -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_SVG_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_PRINTSUPPORT_LIB -DQT_PLATFORMCOMPOSITORSUPPORT_LIB -DQT_WIDGETS_LIB -D_WINDOWS /EHsc -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtSvg -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtSvg\6.4.1 -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtSvg\6.4.1\QtSvg -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtGui -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtGui\6.4.1 -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtGui\6.4.1\QtGui -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtCore -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtCore\6.4.1 -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtCore\6.4.1\QtCore -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtPrintSupport -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtPrintSupport\6.4.1 -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtPrintSupport\6.4.1\QtPrintSupport -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtWidgets -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtWidgets\6.4.1 -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtWidgets\6.4.1\QtWidgets -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\mkspecs\win32-msvc /Zc:__cplusplus /permissive- -DNDEBUG -Fobuild\.objs\chinese_chess\windows\x64\release\gens\src\moc_mainwindow.cpp.obj build\.gens\chinese_chess\windows\x64\release\src\moc_mainwindow.cpp
moc_mainwindow.cpp
[ 37%]: cache compiling.release src\main.cpp
"D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\cl.exe" -c -nologo -O2 -fp:fast -std:c++17 -ID:\VSC_Qt\chinese_chess\build\.gens\chinese_chess\windows\x64\release\rules\qt\ui -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_SVG_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_PRINTSUPPORT_LIB -DQT_PLATFORMCOMPOSITORSUPPORT_LIB -DQT_WIDGETS_LIB -D_WINDOWS /EHsc -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtSvg -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtSvg\6.4.1 -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtSvg\6.4.1\QtSvg -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtGui -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtGui\6.4.1 -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtGui\6.4.1\QtGui -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtCore -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtCore\6.4.1 -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtCore\6.4.1\QtCore -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtPrintSupport -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtPrintSupport\6.4.1 -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtPrintSupport\6.4.1\QtPrintSupport -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtWidgets -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtWidgets\6.4.1 -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtWidgets\6.4.1\QtWidgets -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\mkspecs\win32-msvc /Zc:__cplusplus /permissive- -DNDEBUG -Fobuild\.objs\chinese_chess\windows\x64\release\src\main.cpp.obj src\main.cpp
[ 37%]: cache compiling.release src\mainwindow.cpp
"D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\cl.exe" -c -nologo -O2 -fp:fast -std:c++17 -ID:\VSC_Qt\chinese_chess\build\.gens\chinese_chess\windows\x64\release\rules\qt\ui -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_SVG_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_PRINTSUPPORT_LIB -DQT_PLATFORMCOMPOSITORSUPPORT_LIB -DQT_WIDGETS_LIB -D_WINDOWS /EHsc -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtSvg -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtSvg\6.4.1 -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtSvg\6.4.1\QtSvg -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtGui -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtGui\6.4.1 -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtGui\6.4.1\QtGui -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtCore -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtCore\6.4.1 -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtCore\6.4.1\QtCore -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtPrintSupport -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtPrintSupport\6.4.1 -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtPrintSupport\6.4.1\QtPrintSupport -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtWidgets -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtWidgets\6.4.1 -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtWidgets\6.4.1\QtWidgets -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\mkspecs\win32-msvc /Zc:__cplusplus /permissive- -DNDEBUG -Fobuild\.objs\chinese_chess\windows\x64\release\src\mainwindow.cpp.obj src\mainwindow.cpp
[ 37%]: cache compiling.release build\.qt\plugin\chinese_chess\static_import.cpp
"D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\cl.exe" -c -nologo -O2 -fp:fast -std:c++17 -ID:\VSC_Qt\chinese_chess\build\.gens\chinese_chess\windows\x64\release\rules\qt\ui -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_SVG_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_PRINTSUPPORT_LIB -DQT_PLATFORMCOMPOSITORSUPPORT_LIB -DQT_WIDGETS_LIB -D_WINDOWS /EHsc -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtSvg -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtSvg\6.4.1 -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtSvg\6.4.1\QtSvg -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtGui -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtGui\6.4.1 -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtGui\6.4.1\QtGui -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtCore -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtCore\6.4.1 -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtCore\6.4.1\QtCore -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtPrintSupport -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtPrintSupport\6.4.1 -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtPrintSupport\6.4.1\QtPrintSupport -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtWidgets -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtWidgets\6.4.1 -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include\QtWidgets\6.4.1\QtWidgets -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\include -external:W0 -external:ID:\Qt6\6.4.1\msvc2019_64\mkspecs\win32-msvc /Zc:__cplusplus /permissive- -DNDEBUG -Fobuild\.objs\chinese_chess\windows\x64\release\build\.qt\plugin\chinese_chess\static_import.cpp.obj build\.qt\plugin\chinese_chess\static_import.cpp
[ 75%]: linking.release chinese_chess.exe
"D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe" -nologo -dynamicbase -nxcompat -machine:x64 -libpath:D:\Qt6\6.4.1\msvc2019_64\plugins\imageformats -libpath:D:\Qt6\6.4.1\msvc2019_64\plugins\platforms -libpath:D:\Qt6\6.4.1\msvc2019_64\lib /opt:ref /opt:icf qsvg.lib qwindows.lib Qt6Svg.lib Qt6Gui.lib Qt6Core.lib Qt6PrintSupport.lib Qt6PlatformCompositorSupport.lib Qt6Widgets.lib ws2_32.lib gdi32.lib ole32.lib advapi32.lib shell32.lib user32.lib opengl32.lib imm32.lib winmm.lib iphlpapi.lib -subsystem:windows -entry:mainCRTStartup -out:build\windows\x64\release\chinese_chess.exe build\.objs\chinese_chess\windows\x64\release\src\main.cpp.obj build\.objs\chinese_chess\windows\x64\release\src\mainwindow.cpp.obj build\.objs\chinese_chess\windows\x64\release\build\.qt\plugin\chinese_chess\static_import.cpp.obj build\.objs\chinese_chess\windows\x64\release\gens\src\moc_mainwindow.cpp.obj
error: @programdir\modules\private\async\runjobs.lua:256: @programdir\actions\build\kinds\binary.lua:74: @programdir\modules\core\tools\link.lua:159: LINK : fatal error LNK1181: 无法打开输入文件“qsvg.lib”

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:897]:
    [@programdir\modules\core\tools\link.lua:159]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [@programdir\modules\core\tools\link.lua:139]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\actions\build\kinds\binary.lua:74]: in function 'callback'
    [@programdir\modules\core\project\depend.lua:193]: in function 'on_changed'
    [@programdir\actions\build\kinds\binary.lua:55]: in function '_do_link_target'
    [@programdir\actions\build\kinds\binary.lua:102]:
    [@programdir\actions\build\kinds\binary.lua:129]: in function '_link_target'
    [@programdir\actions\build\kinds\binary.lua:157]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:232]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:218]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:404]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:897: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\modules\private\async\runjobs.lua:256: in field 'catch'
        @programdir\core\sandbox\modules\try.lua:123: in global 'try'
        @programdir\modules\private\async\runjobs.lua:218: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>

**Comment by waruqi** [comment]
你找找 qt sdk 里面有没有这个 qsvg.lib 库，路径在哪，贴下

**Comment by QQ-CN** [comment]
sdk下没有这个库qsvg.lib
xmake.lua(这个就是xmake创建的工程，就是说创建工程后我直接build）

add_rules("mode.debug", "mode.release")

includes("qt_add_static_plugins.lua")

target("chinese_chess")
    add_rules("qt.widgetapp_static")
    add_headerfiles("src/*.h")
    add_files("src/*.cpp")
    add_files("src/mainwindow.ui")

    -- add files with Q_OBJECT meta (only for qt.moc)
    add_files("src/mainwindow.h")

    -- add plugin: QSvgPlugin (optional)
    add_frameworks("QtSvg")
    qt_add_static_plugins("QSvgPlugin", {linkdirs = "plugins/imageformats", links = {"qsvg"}})

--
-- If you want to known more usage about xmake, please see https://xmake.io
--
-- ## FAQ
--
-- You can enter the project directory firstly before building project.
--
--   $ cd projectdir
--
-- 1. How to build project?
--
--   $ xmake
--
-- 2. How to configure project?
--
--   $ xmake f -p [macosx|linux|iphoneos ..] -a [x86_64|i386|arm64 ..] -m [debug|release]
--
-- 3. Where is the build output directory?
--
--   The default output directory is `./build` and you can configure the output directory.
--
--   $ xmake f -o outputdir
--   $ xmake
--
-- 4. How to run and debug target after building project?
--
--   $ xmake run [targetname]
--   $ xmake run -d [targetname]
--
-- 5. How to install target to the system directory or other output directory?
--
--   $ xmake install
--   $ xmake install -o installdir
--
-- 6. Add some frequently-used compilation flags in xmake.lua
--
-- @code
--    -- add debug and release modes
--    add_rules("mode.debug", "mode.release")
--
--    -- add macro defination
--    add_defines("NDEBUG", "_GNU_SOURCE=1")
--
--    -- set warning all as error
--    set_warnings("all", "error")
--
--    -- set language: c99, c++11
--    set_languages("c99", "c++11")
--
--    -- set optimization: none, faster, fastest, smallest
--    set_optimize("fastest")
--
--    -- add include search directories
--    add_includedirs("/usr/include", "/usr/local/include")
--
--    -- add link libraries and search directories
--    add_links("tbox")
--    add_linkdirs("/usr/local/lib", "/usr/lib")
--
--    -- add system link libraries
--    add_syslinks("z", "pthread")
--
--    -- add compilation and link flags
--    add_cxflags("-stdnolib", "-fno-strict-aliasing")
--    add_ldflags("-L/usr/local/lib", "-lpthread", {force = true})
--
-- @endcode
--

**Comment by waruqi** [comment]
那只是 demo ，没 qsvg 那就把下面两行删了

> add_frameworks("QtSvg")
qt_add_static_plugins("QSvgPlugin", {linkdirs = "plugins/imageformats", links = {"qsvg"}})

**Comment by QQ-CN** [comment]
去掉上面说的两行后build报错
error: @programdir\modules\private\async\runjobs.lua:256: @programdir\actions\build\kinds\binary.lua:74: @programdir\modules\core\tools\link.lua:159: LINK : fatal error LNK1104: 无法打开文件“qwindowsd.lib”

qt sdk里面没有找到qwindowsd.lib

xmake.lua如下
add_rules("mode.debug", "mode.release")

includes("qt_add_static_plugins.lua")

target("chinese_chess")
    add_rules("qt.widgetapp_static")
    add_headerfiles("src/*.h")
    add_files("src/*.cpp")
    add_files("src/mainwindow.ui")

    -- add files with Q_OBJECT meta (only for qt.moc)
    add_files("src/mainwindow.h")

    -- add plugin: QSvgPlugin (optional)

**Comment by waruqi** [comment]
贴完整执行命令和 logs

**Comment by waruqi** [comment]
另外，确定你安装的是 qt static 版本 sdk? 只有static 版本 qt sdk 才能用 qt.widgetapp_static ，默认安装的都是动态库版本 qt sdk ，得用 `qt.widgetapp` 不要搞错了

**Comment by QQ-CN** [comment]
嗯嗯，感谢

**Comment by Leart-Loen** [comment]
```
PS > xmake create -t qt.widgetapp_static -P ./xmake_test
create xmake_test ...
  [+]: src\main.cpp
  [+]: src\mainwindow.cpp
  [+]: src\mainwindow.h
  [+]: src\mainwindow.ui
  [+]: xmake.lua
  [+]: .gitignore
create ok!
PS > cd ./xmake_test
PS > xmake f --qt=Path\To\Qt\6.4.1\static
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Qt SDK directory ... Path/To/Qt/6.4.1/static
checking for Qt SDK version ... 6.4.1
PS > xmake build
[ 12%]: compiling.qt.ui src\mainwindow.ui
[ 25%]: compiling.qt.moc src\mainwindow.h
[ 37%]: cache compiling.release src\main.cpp
[ 37%]: cache compiling.release src\mainwindow.cpp
[ 37%]: cache compiling.release build\.qt\plugin\xmake_test\static_import.cpp
[ 75%]: linking.release xmake_test.exe
error: LINK : fatal error LNK1181: 无法打开输入文件“Qt6PlatformCompositorSupport.lib”
```
看了看`Path\To\Qt\6.4.1\static` `Path\To\Qt\6.4.1\msvc2019_64` 以及 `Path\To\Qt\6.4.1\Src` 里面，似乎都没有类似于 `Qt6PlatformCompositorSupport` 的文件。

**Comment by Leart-Loen** [comment]
> ```
> PS > xmake create -t qt.widgetapp_static -P ./xmake_test
> create xmake_test ...
>   [+]: src\main.cpp
>   [+]: src\mainwindow.cpp
>   [+]: src\mainwindow.h
>   [+]: src\mainwindow.ui
>   [+]: xmake.lua
>   [+]: .gitignore
> create ok!
> PS > cd ./xmake_test
> PS > xmake f --qt=Path\To\Qt\6.4.1\static
> checking for platform ... windows
> checking for architecture ... x64
> checking for Microsoft Visual Studio (x64) version ... 2022
> checking for Qt SDK directory ... Path/To/Qt/6.4.1/static
> checking for Qt SDK version ... 6.4.1
> PS > xmake build
> [ 12%]: compiling.qt.ui src\mainwindow.ui
> [ 25%]: compiling.qt.moc src\mainwindow.h
> [ 37%]: cache compiling.release src\main.cpp
> [ 37%]: cache compiling.release src\mainwindow.cpp
> [ 37%]: cache compiling.release build\.qt\plugin\xmake_test\static_import.cpp
> [ 75%]: linking.release xmake_test.exe
> error: LINK : fatal error LNK1181: 无法打开输入文件“Qt6PlatformCompositorSupport.lib”
> ```
> 
> 看了看`Path\To\Qt\6.4.1\static` `Path\To\Qt\6.4.1\msvc2019_64` 以及 `Path\To\Qt\6.4.1\Src` 里面，似乎都没有类似于 `Qt6PlatformCompositorSupport` 的文件。

不好意思，我遇到的问题应该是[#2791 ]

**Comment by shuax** [comment]
qt菜鸟，也有相同问题，只不过我是用的vcpkg install的qt static，不知道要怎么用。

**Comment by waruqi** [comment]
不支持 vcpkg qt 。。用官方 qt sdk
