### ISSUE TITLE
在一些环境上 x64 target 配置构建时不能找到正确的 clang-cl 版本

### ISSUE THREAD

**Issue by SaeruHikari** [xmake-io/xmake#3123]
### Xmake Version

2.7.3

### Operating System Version and Architecture

Windows 11 version 22H2

### Describe Bug

正常的 x64 机器上，clang-cl 的目标总是 x64：
![image](https://user-images.githubusercontent.com/39457738/204959683-ee3b704a-7a81-49b5-92de-c51edd979359.png)

但是在一些 VS 版本的安装中，clang-cl 在 x86 prompt 下的目标不是 x86_64 而是 i386（具体原因不明）：
![Cache_-4938cc6d75308c3f](https://user-images.githubusercontent.com/39457738/204959576-09adf56b-5608-415f-91db-a78c19d6753a.jpg)

这种环境下，xmake 在 x64 配置下构建依然会找到 i386 目标的 clang-cl，os.arch() 也会返回 i386。

### Expected Behavior

正确调用 clang-cl，在 x64 目标下不再错误调用 i386 的 clang-cl。

**Comment by SaeruHikari** [comment]
评论之后看到 clang 版本有些许不同，也可能是 xmake 没有识别 i686 arch ？

**Comment by waruqi** [comment]
>这种环境下，xmake 在 x64 配置下构建依然会找到 i386 目标的 clang-cl，os.arch() 也会返回 i386。

你是不是环境变量设置了 MSYSTEM_CARCH=i686 ，xmake 检测到后以为是 msys2 环境了，默认切到 msys2 的 i386 arch 了。。如果不是在 msys2 的终端下，就不要设置这个。。

默认 cmd 环境，不会连 os.arch 都检测为 i386，只会是 x86/x64

**Comment by SaeruHikari** [comment]
> 

打开 prompt 就是这样，不过这些 PC 确实可能有 MSYS 环境。。。我在我干净的环境下升级下 clang-cl 验证下

**Comment by waruqi** [comment]
你 `echo %MSYSTEM_CARCH%` 看下，或者执行 `xmake l os.getenvs` dump下所有环境变量

**Comment by Ricardo2001ZG** [comment]
> 你 `echo %MSYSTEM_CARCH%` 看下，或者执行 `xmake l os.getenvs` dump下所有环境变量

在 Developer PowerShell for VS 2022 这个 VS2022 安装自带的 shell 的环境下，执行相关命令的 log 已提供
[log_2022-12-01_13-09.txt](https://github.com/xmake-io/xmake/files/10129391/log_2022-12-01_13-09.txt)

**Comment by waruqi** [comment]
> PS C:\Users\miao\Projects\SakuraEngine> xmake l os_arch.lua
x64
> 这种环境下，xmake 在 x64 配置下构建依然会找到 i386 目标的 clang-cl，os.arch() 也会返回 i386。

看你们的 logs ，跟你们的描述不一样哈，这不正常返回的 x64 么？ 是执行的 os.arch 么？哪返回 i386 了？

从这个 log 我没看出哪里不正常了，不要进入 prompt ，直接打开 cmd ，然后执行下面的命令，完整给我一份 logs

```console
xmake f -cvD --toolchain=clang-cl
xmake -rvD
```

> **********************************************************************
> ** Visual Studio 2022 Developer PowerShell v17.4.1
> ** Copyright (c) 2022 Microsoft Corporation
> **********************************************************************
> PS C:\Users\miao\source\repos> cd C:\Users\miao\Projects\SakuraEngine
> PS C:\Users\miao\Projects\SakuraEngine> clang-cl -v
> clang version 15.0.1
> Target: i686-pc-windows-msvc
> Thread model: posix
> 

另外，这个是你们打开 x64 prompt 执行的？clang-cl 返回 i686 那跟 xmake 有啥关系？

**Comment by SaeruHikari** [comment]
>  i386 

嗯，确认了下 os.arch() 确实是 x64，问题在这
![image](https://user-images.githubusercontent.com/39457738/204976248-f2319918-c55a-4825-85c3-36f327ecdaa4.png)

调试了一下似乎 option 本身都没有正确执行,  所以这行逻辑落到了 i386：

``` lua
option("pointer-size")
    add_cxxsnippets("VOID_P_SIZE", 'return sizeof(void*);', {number = true})
option_end()
if (get_config("pointer-size")) then
    print("pointer size: " .. get_config("pointer-size"))
else
    print("pointer size failed")
end
```

上面 option 输出：

![IZEE6%VA55V_ C ZN(2QU6N](https://user-images.githubusercontent.com/39457738/204979577-7e7ed345-c143-402e-9380-745c8d86de23.png)

> 另外，这个是你们打开 x64 prompt 执行的？clang-cl 返回 i686 那跟 xmake 有啥关系？

其实主要问题还是 xmake 明明找到了 toolchain，但是 test option 都没通过，直接汇报了 MSVC-no 和 clang-no。

上图执行环境就是普通的 WindowsPowerShell，native x64 prompt 下面是正常的。

**Comment by waruqi** [comment]
执行下面命令，给我一份 logs 

```console
xmake f -cvD
xmake -rvD
```

**Comment by Ricardo2001ZG** [comment]
> 执行下面命令，给我一份 logs
> 
> ```
> xmake f -cvD
> xmake -rvD
> ```

[log_(x64 Native Tools Command Prompt for VS 2022)_2022-12-01_15-00.txt](https://github.com/xmake-io/xmake/files/10130078/log_.x64.Native.Tools.Command.Prompt.for.VS.2022._2022-12-01_15-00.txt)

[log_(Windows PowerShell)_2022-12-01_14-55.txt](https://github.com/xmake-io/xmake/files/10130080/log_.Windows.PowerShell._2022-12-01_14-55.txt)

[log_(Developer PowerShell for VS 2022)_2022-12-01_14-59.txt](https://github.com/xmake-io/xmake/files/10130082/log_.Developer.PowerShell.for.VS.2022._2022-12-01_14-59.txt)

**Comment by SaeruHikari** [comment]
[log_(Developer PowerShell for VS 2022)_2022-12-01_14-59.txt](https://github.com/xmake-io/xmake/files/10130092/log_.Developer.PowerShell.for.VS.2022._2022-12-01_14-59.txt)

环境中有 clang-cl 但是 test option 失败

**Comment by waruqi** [comment]
没看出哪里不对，这几份logs 行为都正常。。

> [log_(x64 Native Tools Command Prompt for VS 2022)_2022-12-01_15-00.txt](https://github.com/xmake-io/xmake/files/10130078/log_.x64.Native.Tools.Command.Prompt.for.VS.2022._2022-12-01_15-00.txt)

x64 prompt + xmake (x64) ，当然正常

> [log_(Windows PowerShell)_2022-12-01_14-55.txt](https://github.com/xmake-io/xmake/files/10130080/log_.Windows.PowerShell._2022-12-01_14-55.txt)

非 vs prompt + xmake (x64) ，没 clang-cl path，你们强行指定  `xmake f --cxx=clang-cl` 当然会失败。

我群里说了，用 clang-cl 走 `xmake f --toolchain=clang-cl` ,有专门的工具链，xmake 会自动加载安装在 vs 里面的 clang-cl ，保证跟 vs link.exe 环境和 arch 一致，干嘛不用

https://github.com/xmake-io/xmake/files/10130082/log_.Developer.PowerShell.for.VS.2022._2022-12-01_14-59.txt

vs prompt (x86) + xmake (x64) 当然冲突了，很正常。。

默认执行 xmake 都是 x64的，你得自己切 arch，`xmake f -a x86`

另外，没必要再 vs prompt 下执行，xmake 会加载一切 vs 环境。。

**Comment by SaeruHikari** [comment]
https://github.com/xmake-io/xmake/files/10130092/log_.Developer.PowerShell.for.VS.2022._2022-12-01_14-59.txt

他发的比较多，我觉得显然有问题的只有这个。。。这个环境不是 prompt，就是本机的 powershell，这个显然是 x64 环境啊，i686，找到的 linker 都是 /x64 下的：

checking for clang-cl ... ok
checking for c++ snippet(VOID_P_SIZE)
checkinfo: ...gramdir\core\sandbox\modules\import\core\tool\linker.lua:75: @programdir\modules\core\tools\link.lua:159: C:\Users\miao\AppData\Local\Temp\.xmake\221201\_F6241A21C9F94B608FC0B6B171BB94A0.o : fatal error LNK1112: 模块计算机类型“x86”与目标计算机类型“x64”冲突

但是目标类型就是 x86，这个很奇怪，我反复折腾也是疑惑这一点，为什么 x64 的 powershell 上 -arch x64 找到的 x64 linker 会指向 x86 的目标冲突。。。如果确认不是 bug 的话，我很好奇这个到底是为什么。。。

另外感觉 test 可以抛出更明确一点的错误信息，这个 arch 对不上的错误感觉比较严重，非 -cvD 下我觉得也可以抛。至少早点看到这个 log 的话，用户这边也能大致知道是 target arch 冲了。

**Comment by SaeruHikari** [comment]
关于 --toolchain=clang-cl 这点，主要是考虑那个用的 LLVM 的连接器，真的太慢了。。。

这两个错误出现的环境也都多少有问题，绝大部分环境下直接给 cc 都能正常过编译

**Comment by waruqi** [comment]
> https://github.com/xmake-io/xmake/files/10130092/log_.Developer.PowerShell.for.VS.2022._2022-12-01_14-59.txt

他发的比较多，我觉得显然有问题的只有这个。。。这个环境不是 prompt，就是本机的 powershell，这个显然是 x64 环境啊，i686，找到的 linker 都是 /x64 下的：

正常啊，非 prompt 下，xmake 默认也是 x64  环境编译啊，你在 path 里面加了 x86 的 clang-cl 给 xmake 用，当然冲突了。。

好歹给个 clang-cl x64 到 path 里面去哈。。要么就是我刚说的，手动将 xmake 切到 x86 下编译，`xmake f -a x86 --cxx=clang-cl`

没啥问题，感觉还是你们的使用问题。



> 关于 --toolchain=clang-cl 这点，主要是考虑那个用的 LLVM 的连接器，真的太慢了。。。
> 

你没试过怎么知道用了 llvm 的 linker，，`--toolchain=clang-cl` 只切了编译器，link 还是 msvc 的，sdk库也是 vs 环境的。

**Comment by SaeruHikari** [comment]
> 没啥问题，感觉还是你们的使用问题。

其实正常安装的 VS 也没这事，这两个 case 都是环境变动引起的，就两例，感觉可能和缓存相关，所以才当 bug 报过来。

> --toolchain=clang-cl 只切了编译器，link 还是 msvc 的，sdk库也是 vs 环境的。

之前一直以为是直接走的和 VS 相同的配置，学到了。。。

> 在 path 里面加了 x86 的 clang-cl 给 xmake 用，当然冲突了

这个行为不是显式的，并且运行了 xmake g -c 和 f -c 都是稳定重现的。configure 也是一路过，没有任何警告或报错，不然也不会纠结那么久为什么了。。。所以我觉得 option test 的输出可以增强一下，不然用户直接 fatal 是很难去分析具体环境问题在哪里的。

CMake 是会编译一个测试程序，但是冷启动起来感觉会拖慢速度。比较理想的是在 fatal 抛出一个 -cvD/-rvD 的命令行提示，让用户自己再运行一下，bug report 也会清晰很多。

**Comment by waruqi** [comment]
> 其实正常安装的 VS 也没这事，这两个 case 都是环境变动引起的，就两例，感觉可能和缓存相关，所以才当 bug 报过来。

跟缓存没关系，看 logs 就是你系统 path 里是 clang-cl x86 但是 xmake 默认始终走的 x64 导致的 link 冲突。跟 xmake 应该也无关，你修复下 path，在非 vs prompt 里面，clang-cl 也切到 x64 就行了。。或者干脆走 xmake f --toolchain=clang-cl，跟 xmake 加载 vs arch 环境是自动保持一致的

> 这个行为不是显式的，工具都是 VS 自己安装的，并且运行了 xmake g -c 和 f -c 都是稳定重现的。configure 也是一路过，没有任何警告或报错，不然也不会纠结那么久为什么了。。。所以我觉得 option test 的输出可以增强一下，不然用户直接 fatal 是很难去分析具体环境问题在哪里的。

一种可能 vs 安装时候，改了 path，默认走到 clang-cl x86 了。。

> 所以我觉得 option test 的输出可以增强一下，不然用户直接 fatal 是很难去分析具体环境问题在哪里的。
> CMake 是会编译一个测试程序，但是冷启动起来感觉会拖慢速度。比较理想的是在 fatal 抛出一个 -cvD/-rvD 的命令行提示，让用户自己再运行一下，bug report 也会清晰很多。

关键是没啥问题，要报什么错? 只是给错了 clang-cl 而已，即使是 clang-cl x86 一样可以通过检测，只是跟 target x64 链接arch 不一致而已。。但也有可能其他 target 会用到 x86 的（如果其他 target 强行内部配置了 set_arch("x86") 就一样可用）。。

**Comment by SaeruHikari** [comment]
OK，了解了，感谢解答👌

我这边直接加个 64bit 断言好了，然后切到内置的 clang-cl toolchain 去。
