### ISSUE TITLE
安装基于 cmake 的 package 时 cmake 无法找到编译器

### ISSUE THREAD

**Issue by BenzzzX** [xmake-io/xmake#3124]
### Xmake 版本

2.7.3

### 操作系统版本和架构

Windows 10 21H2

### 描述问题

安装 package efsw 的时候，cmake 出现无法找到编译器的错误。手动运行 log 中的 cmake 命令可以正确执行。cmake version 3.25.1。

### 期待的结果

成功运行 cmake

### 工程配置

add_requires("efsw")

target("test")
    set_kind("shared")
    add_files("src/*.cpp")
    add_packages("efsw")

### 附加信息和错误日志

PS H:\新建文件夹> xmake f -v
checking for platform ... windows
checking for architecture ... x64
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for dmd ... no
checking for ldc2 ... no
checking for gdc ... no
checking for zig ... no
checking for zig ... no
checking for unzip ... no
checking for 7z ... C:\Users\Dev1\xmake\winenv\bin\7z
checking for git ... ok
checking for gzip ... no
git rev-parse HEAD
checking for cmake ... C:\Program Files\CMake\bin\cmake
checking for cmake ... C:\Program Files\CMake\bin\cmake
checking for xmake::efsw ... no
checking for pkg-config ... no
checking for pkgconf ... no
checking for efsw ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> efsw 1.1.0 [vs_runtime:"MT"]
please input: y (y/n/m)
y
checking for ping ... ok
pinging for the host(github.com) ... 65535 ms
C:\Users\Dev1\xmake\winenv\bin\7z x -y 1.1.0.tar.gz -oC:\Users\Dev1\AppData\Local\Temp\.xmake\221201\_7478BB1993A04D7086C7A7E9762599F0.tar

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 66455 bytes (65 KiB)

Extracting archive: 1.1.0.tar.gz
--
Path = 1.1.0.tar.gz
Type = gzip
Headers Size = 10

Everything is Ok

Size:       481280
Compressed: 66455
C:\Users\Dev1\xmake\winenv\bin\7z x -y C:\Users\Dev1\AppData\Local\Temp\.xmake\221201\_7478BB1993A04D7086C7A7E9762599F0.tar\1.1.0.tar -osource.tmp

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 481280 bytes (470 KiB)

Extracting archive: C:\Users\Dev1\AppData\Local\Temp\.xmake\221201\_7478BB1993A04D7086C7A7E9762599F0.tar\1.1.0.tar
--
Path = C:\Users\Dev1\AppData\Local\Temp\.xmake\221201\_7478BB1993A04D7086C7A7E9762599F0.tar\1.1.0.tar
Type = tar
Physical Size = 481280
Headers Size = 67072
Code Page = UTF-8

Everything is Ok

Folders: 15
Files: 102
Size:       384886
Compressed: 481280
checking for cmake ... C:\Program Files\CMake\bin\cmake
C:\Program Files\CMake\bin\cmake -DBUILD_TEST_APP=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\Users\Dev1\AppData\Local\.xmake\packages\e\efsw\1.1.0\ac3cf3af549e415b8d094873a61ca496 -DCMAKE_INSTALL_LIBDIR:PATH=lib -G "Visual Studio 17 2022" -A x64 -DCMAKE_GENERATOR_TOOLSET=v143 -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded "-DCMAKE_CXX_FLAGS_DEBUG=/MT /Zi /Ob0 /Od /RTC1" "-DCMAKE_CXX_FLAGS_RELEASE=/MT /O2 /Ob2 /DNDEBUG" "-DCMAKE_C_FLAGS_DEBUG=/MT /Zi /Ob0 /Od /RTC1" "-DCMAKE_C_FLAGS_RELEASE=/MT /O2 /Ob2 /DNDEBUG" -DCMAKE_COMPILE_PDB_OUTPUT_DIRECTORY=pdb -DCMAKE_POSITION_INDEPENDENT_CODE=ON C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!
See also "C:/Users/Dev1/AppData/Local/.xmake/cache/packages/2212/e/efsw/1.1.0/source/build_ac3cf3af/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Dev1/AppData/Local/.xmake/cache/packages/2212/e/efsw/1.1.0/source/build_ac3cf3af/CMakeFiles/CMakeError.log".
error: execv(C:\Program Files\CMake\bin\cmake -DBUILD_TEST_APP=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\Users\Dev1\AppData\Local\.xmake\packages\e\efsw\1.1.0\ac3cf3af549e415b8d094873a61ca496 -DCMAKE_INSTALL_LIBDIR:PATH=lib -G "Visual Studio 17 2022" -A x64 -DCMAKE_GENERATOR_TOOLSET=v143 -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded "-DCMAKE_CXX_FLAGS_DEBUG=/MT /Zi /Ob0 /Od /RTC1" "-DCMAKE_CXX_FLAGS_RELEASE=/MT /O2 /Ob2 /DNDEBUG" "-DCMAKE_C_FLAGS_DEBUG=/MT /Zi /Ob0 /Od /RTC1" "-DCMAKE_C_FLAGS_RELEASE=/MT /O2 /Ob2 /DNDEBUG" -DCMAKE_COMPILE_PDB_OUTPUT_DIRECTORY=pdb -DCMAKE_POSITION_INDEPENDENT_CODE=ON C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source) failed(1)
  => install efsw 1.1.0 .. failed
error: install failed!

**Comment by waruqi** [comment]
进到 %localappdata%/.xmake/cache 目录下对应包源码编译目录下，贴下 cmake 的检测log，看下CMAKE_C_COMPILER 为啥会检测失败。

**Comment by BenzzzX** [comment]
[build_ac3cf3af.zip](https://github.com/xmake-io/xmake/files/10129316/build_ac3cf3af.zip)

**Comment by BenzzzX** [comment]
“CL.exe”的命令行开关无效。System.ArgumentException: 已添加项。字典中的关键字:“WINDOWSSDKDIR”所添加的关键字:“WindowsSdkDir”
这是什么环境变量吗，看起来是这里的问题。
完整的：

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler:  
Build flags: 
Id flags:  

The output was:
1
MSBuild version 17.4.0+18d5aef85 for .NET Framework
生成启动时间为 2022/12/1 12:50:33。
节点 1 上的项目“C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source\build_ac3cf3af\CMakeFiles\3.22.3\CompilerIdC\CompilerIdC.vcxproj”(默认目标)。
PrepareForBuild:
  正在创建目录“Debug\”。
  正在创建目录“Debug\CompilerIdC.tlog\”。
InitializeBuildStatus:
  正在创建“Debug\CompilerIdC.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
ClCompile:
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001: “CL.exe”的命令行开关无效。System.ArgumentException: 已添加项。字典中的关键字:“WINDOWSSDKDIR”所添加的关键字:“WindowsSdkDir” [C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source\build_ac3cf3af\CMakeFiles\3.22.3\CompilerIdC\CompilerIdC.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    在 System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add) [C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source\build_ac3cf3af\CMakeFiles\3.22.3\CompilerIdC\CompilerIdC.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    在 System.Diagnostics.ProcessStartInfo.get_EnvironmentVariables() [C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source\build_ac3cf3af\CMakeFiles\3.22.3\CompilerIdC\CompilerIdC.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    在 Microsoft.Build.Utilities.ToolTask.GetProcessStartInfo(String pathToTool, String commandLineCommands, String responseFileSwitch) [C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source\build_ac3cf3af\CMakeFiles\3.22.3\CompilerIdC\CompilerIdC.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    在 Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source\build_ac3cf3af\CMakeFiles\3.22.3\CompilerIdC\CompilerIdC.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    在 Microsoft.Build.CPPTasks.TrackedVCToolTask.TrackerExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source\build_ac3cf3af\CMakeFiles\3.22.3\CompilerIdC\CompilerIdC.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    在 Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source\build_ac3cf3af\CMakeFiles\3.22.3\CompilerIdC\CompilerIdC.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    在 Microsoft.Build.Utilities.ToolTask.Execute() [C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source\build_ac3cf3af\CMakeFiles\3.22.3\CompilerIdC\CompilerIdC.vcxproj]
已完成生成项目“C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source\build_ac3cf3af\CMakeFiles\3.22.3\CompilerIdC\CompilerIdC.vcxproj”(默认目标)的操作 - 失败。

生成失败。

“C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source\build_ac3cf3af\CMakeFiles\3.22.3\CompilerIdC\CompilerIdC.vcxproj”(默认目标) (1) ->
(ClCompile 目标) -> 
  C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001: “CL.exe”的命令行开关无效。System.ArgumentException: 已添加项。字典中的关键字:“WINDOWSSDKDIR”所添加的关键字:“WindowsSdkDir” [C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source\build_ac3cf3af\CMakeFiles\3.22.3\CompilerIdC\CompilerIdC.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    在 System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add) [C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source\build_ac3cf3af\CMakeFiles\3.22.3\CompilerIdC\CompilerIdC.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    在 System.Diagnostics.ProcessStartInfo.get_EnvironmentVariables() [C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source\build_ac3cf3af\CMakeFiles\3.22.3\CompilerIdC\CompilerIdC.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    在 Microsoft.Build.Utilities.ToolTask.GetProcessStartInfo(String pathToTool, String commandLineCommands, String responseFileSwitch) [C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source\build_ac3cf3af\CMakeFiles\3.22.3\CompilerIdC\CompilerIdC.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    在 Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source\build_ac3cf3af\CMakeFiles\3.22.3\CompilerIdC\CompilerIdC.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    在 Microsoft.Build.CPPTasks.TrackedVCToolTask.TrackerExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source\build_ac3cf3af\CMakeFiles\3.22.3\CompilerIdC\CompilerIdC.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    在 Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source\build_ac3cf3af\CMakeFiles\3.22.3\CompilerIdC\CompilerIdC.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6001:    在 Microsoft.Build.Utilities.ToolTask.Execute() [C:\Users\Dev1\AppData\Local\.xmake\cache\packages\2212\e\efsw\1.1.0\source\build_ac3cf3af\CMakeFiles\3.22.3\CompilerIdC\CompilerIdC.vcxproj]

    0 个警告
    1 个错误

已用时间 00:00:00.30

**Comment by waruqi** [comment]
>  “CL.exe”的命令行开关无效。System.ArgumentException: 已添加项。字典中的关键字:“WINDOWSSDKDIR”所添加的关键字:“WindowsSdkDir"

你打开了 vs prompt? xmake 明明可以直接找 vs 环境用的，去进入 vs prompt 。干嘛呢？

进到干净的 cmd 里面再试下，如果还是不行  系统环境变量里面找下 WindowsSdkDir，删了再试试

**Comment by BenzzzX** [comment]
就是用的 cmd，我试试删环境变量

**Comment by BenzzzX** [comment]
环境变量删了就可以了。。。奇怪的问题

**Comment by waruqi** [comment]
重复的环境变量 大小写冲突导致，你系统设置了一份，xmake 加载 vs 设置了一份，大小写还不同，所以才会有这个问题。。只要不去随意乱加 vs prompt 里面的各种 vs sdk 环境变量到系统就行了。。
