### ISSUE TITLE
在 clang-cl 下提供相对安全的 -O2 optimize 配置

### ISSUE THREAD

**Issue by SaeruHikari** [xmake-io/xmake#3130]
### Xmake Version

v2.7.3

### Operating System Version and Architecture

Windows 11 22H2

### Describe Bug

很多 SSE 库有比较激进的浮点值寄存器优化，开 -fp:fast 在 CL 下测试还好，但是 clang-cl 貌似不是很行。在 DXMath 仓库里面有几个已知是此问题的 issue，那几个 issue 讨论下来除了关闭 -fp:fast 没啥好办法：

[The clang/LLVM returns bad results for specific code optimizations](https://github.com/microsoft/DirectXMath/issues/127)

[unexpected results with clang-cl /fp:fast in release mode](https://github.com/microsoft/DirectXMath/issues/152)

这个 SIMD 库是游戏开发里非常常见非常普遍的一个库，这个 issue 看上去也是几年都没人在 clang 里解决的样子。我看了下现在 xmake 预置的 clang-cl 配置是这样的：

``` lua
-- make the optimize flag
function nf_optimize(self, level)
    local maps =
    {
        none        = "-Od"
    ,   faster      = "-Ox"
    ,   fastest     = "-O2 -fp:fast"
    ,   smallest    = "-O1"
    ,   aggressive  = "-O2 -fp:fast"
    }
    return maps[level]
end
```

没有能保持 -O2 质量的同时关闭这个激进浮点优化的选项，试了下 set_fpmodels 也没法覆盖。我**同时也试了其他几个 SIMD 库**，包括 RTM，GLM， SonyMath 这些 SSE 库都有这个问题（毕竟问题出在一个非常普遍的 SinCos 实现里面）。

本地测试了一下：

``` lua
 fastest     = "-O2"
```

之后这些库就都没有问题了。

### Expected Behavior

有可以关闭 -fp:fast 的选项，最好默认在 clang-cl 下面关闭这个。安全为大，这个完全脱离 IEEE-754 标准，NaN 都是未定义行为，很容易踩到难以调试出来的暗坑。

**Comment by waruqi** [comment]
好了，再试试

**Comment by SaeruHikari** [comment]
ok
