### ISSUE TITLE
ubuntu vcpkg::zlib depedence failure

### ISSUE THREAD

**Issue by edidada** [xmake-io/xmake#3140]
### Xmake Version

2.6.4

### Operating System Version and Architecture

ubuntu

### Describe Bug

ubuntu 20
xmake v2.6.4
xmake.lua

add_requires("vcpkg::zlib", "vcpkg::pcre2")

xmake -y
 => install vcpkg::zlib latest .. 
failed fetch vcpkg::zlib-latest failed! if you want to get more verbose errors, please see: -> /home/wdidada/CLionProjects/rest_description_xmake/build/.packages/v/vcpkg_zlib/latest/cache/installdir.failed/logs/install.txt error: install failed!

### Expected Behavior

build success

**Comment by waruqi** [comment]
xmake f -c -vD 贴下详细 logs

**Comment by edidada** [comment]
I set VCPKG_ROOT=~/vcpkg and get it
