### ISSUE TITLE
Link order

### ISSUE THREAD

**Issue by Arthapz** [xmake-io/xmake#3144]
### Xmake Version

2.7.3-dev

### Operating System Version and Architecture

Archlinux

### Describe Bug

```lua
set_xmakever("2.7.3")
set_project("foo")

target("a")
    set_kind("static")
    add_files("src/a.cpp")

target("b")
    set_kind("static")
    add_files("src/b.cpp")

target("foo")
    set_kind("binary")
    add_files("src/main.cpp")
    add_deps("a", "b")
```

```cmake
cmake_minimum_required(VERSION 3.7...3.25)
project(Foo LANGUAGES CXX)

add_library(a STATIC src/a.cpp)
add_library(b STATIC src/b.cpp)

add_executable(foo src/main.cpp)
target_link_libraries(foo a b)
```

```cpp
// main.cpp
#include <iostream>
extern int b;
int main() {
    std::cout << b << std::endl;
    return b;
}

// a.cpp
int b = 1;

// b.cpp
int b = 0;
```

produce different link behavior

**xmake**: `/usr/sbin/g++ -o build/linux/x64/release/foo build/.objs/foo/linux/x64/release/src/main.cpp.o -m64 -Lbuild/linux/x64/release -lb -la`
**cmake**: `/usr/sbin/c++   CMakeFiles/foo.dir/src/main.cpp.o -o foo  liba.a  libb.a`

![image](https://user-images.githubusercontent.com/27437334/206308128-474f7916-2793-4414-ba92-c86df8f86770.png)

### Expected Behavior

Both same link behavior

### Additional Information and Error Logs

tested on gcc and msvc

this also affect GCC module support as the link order doesn't match the import order (this doesn't affect msvc through, i don't know for clang)

**Comment by waruqi** [comment]
try it again on dev

**Comment by Arthapz** [comment]
it works fine now !

**Comment by waruqi** [comment]
The previous fix was wrong, please continue to test the latest dev version.
