### ISSUE TITLE
doxygen plugin should use doxyfile in project root

### ISSUE THREAD

**Issue by paul-reilly** [xmake-io/xmake#3147]
### Is your feature request related to a problem? Please describe.

At the moment there is a temporary doxyfile created which xmake populates with the project name and version. This means it can't be used where custom options are required.

Also because doxygen is using a temp doxyfile in another location, any doxyfile in the root project dir is renamed with a `.bak` extension.

### Describe the solution you'd like

**xmake doxygen plugin should:**
- use an existing doxyfile in the project root if one exists
- create one in the project root if it doesn't

**Note:**
I think using a placeholder for the version string in the actual file to avoid committing autogenerated changes would be  good idea.

**Comment by waruqi** [comment]
try it again.

**Comment by paul-reilly** [comment]
Thanks, that was quick! The remaining issue is how to deal with the doxyfile project versioning since it's either:
- autogenerated and should not be committed with every change
- new behaviour: somewhere information has to be duplicated (between xmake `set_version` and doxyfile)

I think having something like:

```
PROJECT_NUMBER = $(VERSION)     # replace $(VERSION) to stop using set_version from xmake.lua 
```

... would, I think, cover all bases: empty, autogen and manual version.

**Comment by waruqi** [comment]
you can open a pr to improve it.

**Comment by paul-reilly** [comment]
Okdk, will do!
