### ISSUE TITLE
请加入grpc cpp编译规则支持

### ISSUE THREAD

**Issue by gooker** [xmake-io/xmake#3148]
### 你在什么场景下需要该功能？

希望 xmake支持 grpc.cpp编译规则

grpc 用protoc除了生成protobuf的2个文件,还会生成另外两个文件.grpc.pb.h和.grpc.pb.cc 
下面是目前我加在before_build(function (target)

os.execv("protoc --grpc_out=$(projectdir)/ --plugin=protoc-gen-grpc=/usr/local/bin/grpc_cpp_plugin -I $(projectdir)/proto/ xxx.proto")

### 描述可能的解决方案

类似protobuf 一样支持生成xxx.grpc.pb.h和xx.grpc.pb.cc

**Comment by ivanallen** [comment]
我也有这个问题，不知道作者是否会支持，还是说只能继续采取你这个临时方案

**Comment by waruqi** [comment]
最近没啥时间，你们也可以直接 写 rule 提 pr 过来

**Comment by waruqi** [comment]
可以了，patch 已经 merge ，`xmake update -s dev` 试下

**Comment by waruqi** [comment]
例子工程见：https://github.com/xmake-io/xmake/tree/dev/tests/projects/c%2B%2B/protobuf_grpc_cpp_plugin
