### ISSUE TITLE
使用vcpkg的requires报错

### ISSUE THREAD

**Issue by chriscp-cat** [xmake-io/xmake#3158]
### Xmake 版本

2.7.3

### 操作系统版本和架构

windows 11 latest

### 描述问题

安装requires时报错

### 期待的结果

安装requires时报错

### 工程配置

xmake create创建的空白项目
```lua
add_rules("mode.debug", "mode.release")

add_requires("vcpkg::boost[core]")

target("protest")
    set_kind("binary")
    add_files("src/*.cpp")
```

### 附加信息和错误日志

[output.txt](https://github.com/xmake-io/xmake/files/10198508/output.txt)

**Comment by waruqi** [comment]
装完没找到 boost，可以自己调下 vcpkg/find_package.lua 

或者改用 add_request("boost")
