### ISSUE TITLE
Add default components for packages

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#3164]
### Is your feature request related to a problem? Please describe.

Hi.

Now that package components and rules are implemented, I plan to make new packages for Qt5 and Qt6, which would be based on them.

I plan to make two packages for Qt, `qt5` and `qt6` which would make use of components to allow to enable other Qt library. Components are perfect for the Qt library as the Qt installer (aqtinstaller) installs all Qt libraries.

This way, it would be easy to use Qt6:
```lua
add_requires("qt6")

target("MyWidgetApp")
    add_files("src/*.cpp")
    add_rules("@qt6/widgetapp")
    add_packages("qt6", { components = "widgets" }) -- widgets deps on gui and core
```

however most people will probably write this:
```lua
add_requires("qt6")

target("MyWidgetApp")
    add_files("src/*.cpp")
    add_rules("@qt6/widgetapp")
    add_packages("qt6") -- ??
```

with xmake 2.7.3, this will enable all qt6 components and libs, and there are dozens of them. it makes it too easy to enable too many libs.

### Describe the solution you'd like

I was thinking we could easily add a way to specify default components
```lua
package("qt6")
    add_components("core", "gui", "widgets", "network", ...)
    set_defaultcomponents("core", "gui", "widgets")
```

or maybe
```lua
    on_component("core", function (package, component)
        -- ...
        component:set_default(true)
    end)
```

these components would be the selected components if none if specified.

### Describe alternatives you've considered

adding an "error" component which would try to trigger a compilation error telling the user to select which components it wants to use.

**Comment by waruqi** [comment]
It has been supported. you can use `add_configs()` to set default components.

```lua
package("test")
    add_configs("widgets",       {description = "", default = true, type = "boolean"})
    on_load(function (package)
        if package:config("widgets") then
            package:add("components", "main")
        end
    end)
```

**Comment by waruqi** [comment]
try it https://github.com/xmake-io/xmake/pull/3167

```lua
add_components("graphics", {default = true})
```

or 

```lua
on_component(function (package, component))
    component:set("default", true)
end)
```
