### ISSUE TITLE
before_build_file executed twice

### ISSUE THREAD

**Issue by PAN-jingcheng** [xmake-io/xmake#3171]
### Xmake Version

2.7.3

### Operating System Version and Architecture

Ubuntu 20.04.5

### Describe Bug

before_build_file executed twice
![image](https://user-images.githubusercontent.com/120500799/207407175-58146212-793c-4362-926c-4a1882034001.png)

### Expected Behavior

before_build_file should only execute once

### Project Configuration

```
xmake.lua: 
  target("iotest")
      set_kind("binary")
      add_files("src/*.cpp")
      before_build_file(function (target, sourcefile)
          print("\n--- before_build_file ---\n")
          local data = io.readfile(sourcefile)
          if data then
              print("readfile", data)
              data = data:gsub("world", "xmake")
              io.writefile(sourcefile, data)
              print("writefile", data)
          end
      end)
```

**Comment by waruqi** [comment]
I have fixed it, please update to dev and try it again. `xmake update -s dev`
