### ISSUE TITLE
compile_commands and precompiled headers

### ISSUE THREAD

**Issue by c0nd3v** [xmake-io/xmake#3173]
### Xmake Version

2.7.3

### Operating System Version and Architecture

All

### Describe Bug

![image](https://user-images.githubusercontent.com/32241825/207790978-db200877-ad69-42e3-875e-1b0bac0d1149.png)

I noticed these two lines in "plugins/project/clang/compile_commands.lua".

After removing these lines, vscode intellisense is working again for precompiled headers.

Is there any reason that precompiled headers are disabled for compile_commands? 

### Expected Behavior

working vscode intellisense

**Comment by c0nd3v** [comment]
After commenting these two lines, intellisense works in all source files, but intellisense still has problems in the pch file. 

![image](https://user-images.githubusercontent.com/32241825/207796599-134011fc-99ab-4429-a70e-b515ab2d26d6.png)

If I manually add the pch file to the compile_commands.json like this, intellisense in the pch file works correctly.

**Comment by waruqi** [comment]
I disabled it for now because I didn't have time before to test if it worked on all compilers and LSPs.

I think even with pch disabled, it should fallback to using the -I method to find headers if you include pre-compiled headers in the source. It should also work.

**Comment by c0nd3v** [comment]
Okay thanks… I’ll do that!
