### ISSUE TITLE
安装v8失败

### ISSUE THREAD

**Issue by over-shine** [xmake-io/xmake#3178]
### Xmake 版本

2.7.3

### 操作系统版本和架构

win11

### 描述问题

在安装v8依赖depot_tools时，报错：系统找不到文件 D:\xmake\.xmake\packages\d\depot_tools\2022.2.1\4924624413ef40f4a456604ecc109209\python3_bin_reldir.txt
![Uploading image.png…]()

### 期待的结果

可以正常安装v8

### 附加信息和错误日志

install.txt文件内容如下：

系统找不到文件 D:\xmake\.xmake\packages\d\depot_tools\2022.2.1\4924624413ef40f4a456604ecc109209\python3_bin_reldir.txt。
系统找不到指定的路径。

**Comment by waruqi** [comment]
请提供完整-vD logs

**Comment by over-shine** [comment]
> 请提供完整-vD logs

(base) PS D:\xmake\.xmake\cache\packages\2212\d\depot_tools\2022.2.1> xrepo install -vD v8
xmake f -c --require=n -vD
checking for platform ... windows
checking for architecture ... x64
checking for cl.exe ... C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2019
checkinfo: cannot runv(dmd.exe --version), No such file or directory
checking for dmd ... no
checkinfo: cannot runv(ldc2.exe --version), No such file or directory
checking for ldc2 ... no
checkinfo: cannot runv(gdc.exe --version), No such file or directory
checking for gdc ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checking for link.exe ... C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe
checking for the linker (ld) ... link.exe
configure
{
    buildir = build
    clean = true
    vs = 2019
    ccache = true
    arch = x64
    plat = windows
    ndk_stdcxx = true
    kind = static
    mode = release
    host = windows
}
xmake require -v -D -j 14 --extra={system=false} v8
checkinfo: cannot runv(unzip.exe -v), No such file or directory
checking for unzip ... no
checking for 7z ... D:\xmake\winenv\bin\7z
checking for git ... ok
checkinfo: cannot runv(gzip.exe --version), No such file or directory
checking for gzip ... no
git rev-parse HEAD
checking for depot_tools ... no
checkinfo: cannot runv(depot_tools.exe --version), No such file or directory
checking for depot_tools ... no
finding v8 from xmake ..
checking for xmake::v8 ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> depot_tools 2022.2.1 [from:v8]
  -> v8 10.0.58
please input: y (y/n/m)

checkinfo: @programdir\core\sandbox\modules\os.lua:258:
正在 Ping 127.0.0.1 具有 32 字节的数据:
请求超时。

127.0.0.1 的 Ping 统计信息:
    数据包: 已发送 = 1，已接收 = 0，丢失 = 1 (100% 丢失)，

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:897]:
    [@programdir\core\sandbox\modules\os.lua:258]: in function 'run'
    [@programdir\modules\detect\tools\find_ping.lua:37]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [...\core\sandbox\modules\import\lib\detect\find_program.lua:65]: in function '_do_check'
    [...\core\sandbox\modules\import\lib\detect\find_program.lua:88]: in function '_check'
    [...\core\sandbox\modules\import\lib\detect\find_program.lua:237]: in function '_find'
    [...\core\sandbox\modules\import\lib\detect\find_program.lua:304]:
    [@programdir\modules\net\ping.lua:39]:
    [@programdir\modules\net\fasturl.lua:68]: in function 'sort'
    [...modules\private\action\require\impl\install_packages.lua:46]: in function '_sort_packages_urls'
    [...modules\private\action\require\impl\install_packages.lua:774]:
    [@programdir\modules\private\action\require\install.lua:85]:
    [@programdir\actions\require\main.lua:123]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\base\task.lua:501]: in function 'run'
    [@programdir\core\main.lua:278]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:404]:

checking for ping ... no
git -c core.fsmonitor=false clean -d -f -x
git -c core.fsmonitor=false reset --hard
HEAD is now at 8a6d00f1 Roll recipe dependencies (trivial).
gclient.bat --verbose
Your depot_tools checkout is configured to fetch from an obsolete URL
Would you like to update it? [y/N]: N
fatal: unable to access 'https://github.com/xmake-mirror/depot_tools.git/': OpenSSL SSL_read: Connection was reset, errno 10054
Downloading CIPD client for windows-amd64 from https://chrome-infra-packages.appspot.com/client?platform=windows-amd64&version=git_revision:8e9b0c80860d00dfe951f7ea37d74e210d376c13...
[P3512 09:54:45.075 client.go:306 W] RPC failed transiently. Will retry in 1s    {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 157.240.13.8:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"1s"}
[P3512 09:55:07.109 client.go:306 W] RPC failed transiently. Will retry in 2s    {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 157.240.13.8:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"2s"}
[P3512 09:55:30.164 client.go:306 W] RPC failed transiently. Will retry in 4s    {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 157.240.13.8:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"4s"}
[P3512 09:55:55.209 client.go:306 W] RPC failed transiently. Will retry in 8s    {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 157.240.13.8:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"8s"}
[P3512 09:56:24.262 client.go:306 W] RPC failed transiently. Will retry in 16s   {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 157.240.13.8:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"16s"}
[P3512 09:57:01.316 client.go:306 W] RPC failed transiently. Will retry in 32s   {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 157.240.13.8:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"32s"}
[P3512 09:57:54.375 client.go:306 W] RPC failed transiently. Will retry in 1m4s  {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 157.240.13.8:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"1m4s"}
[P3512 09:59:19.416 client.go:306 W] RPC failed transiently. Will retry in 2m8s  {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 157.240.13.8:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"2m8s"}
[P3512 10:01:48.433 client.go:306 W] RPC failed transiently. Will retry in 4m16s {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 157.240.13.8:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"4m16s"}
[P3512 10:06:25.491 client.go:306 W] RPC failed transiently. Will retry in 8m32s {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 157.240.13.8:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"8m32s"}
[P3512 10:15:18.550 client.go:350 W] RPC failed permanently: rpc error: code = Internal desc = prpc: when sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 157.240.13.8:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 157.240.13.8:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository"}
Error: prpc: when sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 157.240.13.8:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..
Failed to bootstrap or update CIPD client
CIPD client self-update failed, trying to bootstrap it from scratch...
Downloading CIPD client for windows-amd64 from https://chrome-infra-packages.appspot.com/client?platform=windows-amd64&version=git_revision:8e9b0c80860d00dfe951f7ea37d74e210d376c13...
[P9472 10:37:00.266 client.go:306 W] RPC failed transiently. Will retry in 1s    {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 128.242.245.244:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"1s"}
[P9472 10:37:22.310 client.go:306 W] RPC failed transiently. Will retry in 2s    {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 128.242.245.244:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"2s"}
[P9472 10:37:45.362 client.go:306 W] RPC failed transiently. Will retry in 4s    {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 128.242.245.244:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"4s"}
[P9472 10:38:10.407 client.go:306 W] RPC failed transiently. Will retry in 8s    {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 128.242.245.244:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"8s"}
[P9472 10:38:39.450 client.go:306 W] RPC failed transiently. Will retry in 16s   {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 128.242.245.244:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"16s"}
[P9472 10:39:16.488 client.go:306 W] RPC failed transiently. Will retry in 32s   {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 128.242.245.244:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"32s"}
[P9472 10:40:09.533 client.go:306 W] RPC failed transiently. Will retry in 1m4s  {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 128.242.245.244:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"1m4s"}
[P9472 10:41:34.605 client.go:306 W] RPC failed transiently. Will retry in 2m8s  {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 128.242.245.244:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"2m8s"}
[P9472 10:44:03.652 client.go:306 W] RPC failed transiently. Will retry in 4m16s {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 128.242.245.244:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"4m16s"}
[P9472 10:48:40.701 client.go:306 W] RPC failed transiently. Will retry in 8m32s {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 128.242.245.244:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"8m32s"}
[P9472 10:57:33.761 client.go:350 W] RPC failed permanently: rpc error: code = Internal desc = prpc: when sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 162.125.32.5:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion\": dial tcp 162.125.32.5:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository"}
Error: prpc: when sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 162.125.32.5:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..
Failed to bootstrap or update CIPD client
checking for depot_tools ... no
{
  configs = {
    debug = false,
    shared = false
  },
  name = "depot_tools",
  artifacts = {
    installdir = "D:\xmake\.xmake\packages\d\depot_tools\2022.2.1\4924624413ef40f4a456604ecc109209"
  },
  repo = {
    url = "https://github.com/xmake-io/xmake-repo.git",
    commit = "49cd34c23fc612ea781cd8e7cd9590d8342f8801",
    branch = "master",
    name = "xmake-repo"
  },
  mode = "release",
  kind = "binary",
  plat = "windows",
  version = "2022.2.1",
  envs = {
    PATH = {
      "bin",
      ".",
      "python-bin"
    },
    DEPOT_TOOLS_UPDATE = {
      "0"
    },
    DEPOT_TOOLS_METRICS = {
      "0"
    },
    DEPOT_TOOLS_WIN_TOOLCHAIN = {
      "0"
    }
  },
  arch = "x64",
  description = "Tools for working with Chromium development"
}

python3 --version
Python 3.9.12
ninja --version
1.8.2
gclient.bat --version
系统找不到文件 D:\xmake\.xmake\packages\d\depot_tools\2022.2.1\4924624413ef40f4a456604ecc109209\python3_bin_reldir.txt。

**Comment by waruqi** [comment]
下载失败，安装 depot_tools 以及后期使用 depot_tools 同步拉 v8 源码都是需要 fq 的。。自己备好梯子。
