### ISSUE TITLE
xmake使用msvc模块化标准库时出现问题，cmake却没有问题

### ISSUE THREAD

**Issue by C-pops** [xmake-io/xmake#3186]
### Xmake 版本

 v2.7.3+dev.30fbe9007

### 操作系统版本和架构

windows11 22h2

### 描述问题

![image](https://user-images.githubusercontent.com/102885957/208636761-9fb83be6-fbab-4709-9224-3ed0e6930a7c.png)
![image](https://user-images.githubusercontent.com/102885957/208637295-ac77ffbc-6eab-480d-8288-55dd8b1a485a.png)

### 期待的结果

应当编译成功

### 工程配置

![image](https://user-images.githubusercontent.com/102885957/208636312-628a9c2c-d08d-4c73-9ab1-60e0026c1a93.png)
![image](https://user-images.githubusercontent.com/102885957/208636408-464349bb-7767-489c-be85-89f64db5ca4e.png)
![image](https://user-images.githubusercontent.com/102885957/208636447-24bf3825-9101-4ece-9225-f5cd4c29db2e.png)
![image](https://user-images.githubusercontent.com/102885957/208637352-8d6d4f6b-58f2-44ee-9846-8c4b64cb11f1.png)

**Comment by C-pops** [comment]
![image](https://user-images.githubusercontent.com/102885957/208662219-8ad676be-f540-4d11-9f80-acf977f653af.png)
但是xmake生成的cmakelists也能构建成功

**Comment by waruqi** [comment]
std.core 属于 msvc 特有的 std ifc 模块，早期实验性产物，最新预览版中都快要废弃了。。

由于它即将被废弃，并且不跟 gcc/clang 兼容，所以 dev 版本中，xmake 已经彻底移除了对它的支持，具体看下 https://github.com/xmake-io/xmake/pull/3168
https://github.com/xmake-io/xmake/issues/3084

后面新版本 msvc，VS 2022 17.5 预览版之后，都将支持跟 c++23 标准std 模块，跟 gcc/clang 一样，统一使用 import std 。。

所以，目前我不打算再去支持 ifc std 了（前几个版本是有支持的），不仅不方便维护，写的模块代码，也不跨编译器。

**Comment by waruqi** [comment]
想用 std 模块，就等到 VS 2022 17.5 预览版发布，或者改用 gcc/clang

**Comment by waruqi** [comment]
另外，你配置也写的不对，不要自己设置各种 flags ，参考 https://github.com/xmake-io/xmake/tree/master/tests/projects/c%2B%2B/modules/stdmodules

已有的各种 examples，文档里也有完整 example ，不要乱写

**Comment by waruqi** [comment]
如果非得要用即将废弃的 std.core ，那就回退到 2.7.3 版本，然后配置参考上面的 example 改对

**Comment by C-pops** [comment]
> std.core 属于 msvc 特有的 std IFC 模块，早期实验性产物，最新预览版中都快要废弃了。。
> 
> 由于它即将被废弃，并且不跟 gcc/clang 兼容，所以 dev 版本中，xmake 已经彻底移除了对它的支持，具体看下 #[3168](https://github.com/xmake-io/xmake/pull/3168) #3084
> 
> 后面新版本 msvc，VS 2022 17.5 预览版之后，都将支持 c++23 标准std 模块，跟 gcc/clang 一样，统一使用 import std 。。
> 
> 所以，目前我不打算再去支持 IFC std 了（前几个版本是有支持的），不仅不方便维护，写的模块代码，也不跨编译器。

gcc和clang支持import std吗

**Comment by waruqi** [comment]
> > std.core 属于 msvc 特有的 std IFC 模块，早期实验性产物，最新预览版中都快要废弃了。。
> > 由于它即将被废弃，并且不跟 gcc/clang 兼容，所以 dev 版本中，xmake 已经彻底移除了对它的支持，具体看下 #[3168](https://github.com/xmake-io/xmake/pull/3168) #3084
> > 后面新版本 msvc，VS 2022 17.5 预览版之后，都将支持 c++23 标准std 模块，跟 gcc/clang 一样，统一使用 import std 。。
> > 所以，目前我不打算再去支持 IFC std 了（前几个版本是有支持的），不仅不方便维护，写的模块代码，也不跨编译器。
> 
> gcc和clang支持import std吗

后期按标准都是要支持的，但目前我测下来，高版本 clang 可以支持，gcc 还不行，不过我这里只有 gcc11 再高版本不清楚，你可以试试，我估计悬。

而且clang下，你还得额外安装 libc++ libc++-abi 才行，默认 ubuntu 自带的 libstdc++ 下，也是不行的。。

所以现阶段，想用 std 还过早。。你想尝鲜可以试试。

**Comment by C-pops** [comment]
> 如果非得要用即将废弃的 std.core ，那就回退到 2.7.3 版本，然后配置参考上面的 example 改对

xmake v2.7.3+HEAD.b35ff3118使用std.core需要什么命令

**Comment by waruqi** [comment]
> > 如果非得要用即将废弃的 std.core ，那就回退到 2.7.3 版本，然后配置参考上面的 example 改对
> 
> xmake v2.7.3+HEAD.b35ff3118使用std.core需要什么命令

参考这个 https://github.com/xmake-io/xmake/blob/v2.7.3/tests/projects/c%2B%2B/modules/stdmodules/xmake.lua 

example，然后直接 xmake 就行了，如果没有任何 .mpp 文件，需要额外配置 `set_policy("build.c++.modules", true)`

**Comment by C-pops** [comment]
> > > 如果非得要用即将废弃的 std.core ，那就回退到 2.7.3 版本，然后配置参考上面的 example 改对
> > 
> > 
> > xmake v2.7.3+HEAD.b35ff3118使用std.core需要什么命令
> 
> 参考这个 https://github.com/xmake-io/xmake/blob/v2.7.3/tests/projects/c%2B%2B/modules/stdmodules/xmake.lua
> 
> example，然后直接 xmake 就行了，如果没有任何 .mpp 文件，需要额外配置 `set_policy("build.c++.modules", true)`

谢谢了
