### ISSUE TITLE
Unable to set target_minver on Windows for remote build in macOS

### ISSUE THREAD

**Issue by c0nd3v** [xmake-io/xmake#3187]
This line of code makes it so I cannot set xcode configurations on Windows for remote build in macOS.

https://github.com/xmake-io/xmake/blob/30fbe9007008e20e709af947272719ea31e43a67/xmake/core/platform/menu.lua#L54

**Comment by waruqi** [comment]
I have improved it, try it again. `xmake update -s dev`
