### ISSUE TITLE
xmake create 项目 出现报错 scheduler.lua:56: cannot get program for cxx 

### ISSUE THREAD

**Issue by shenxin-karl** [xmake-io/xmake#3189]
### Xmake 版本

xmake v2.6.9+HEAD.22ecc0156, A cross-platform build utility based on Lua

### 操作系统版本和架构

win10 version 21H2

### 描述问题

第一次安装 xmake. 电脑上有编译环境是 vs2022, 且 cmake 环境能够编译 c++. 

出现方式 在一个新目录下
xmake create xmake_test 
cd xmake_test
xmake 
就有了如下报错
路径无中文

### 期待的结果

无报错能正常使用

### 附加信息和错误日志

checking for the c++ compiler (cxx: x86_64-w64-mingw32-g++) ... no
checking for the c++ compiler (cxx: x86_64-w64-mingw32-gcc) ... no
checking for the c++ compiler (cxx: E:\Git\mingw64\bin\g++) ... no
checking for the c++ compiler (cxx: E:\Git\mingw64\bin\gcc) ... no
error: @programdir\core\main.lua:280: @programdir\actions\build\main.lua:166: ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:96: ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:56: @programdir\modules\private\async\runjobs.lua:256: ...amdir\core\sandbox\modules\import\core\tool\compiler.lua:37: cannot get program for cxx
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:872]:
    [...amdir\core\sandbox\modules\import\core\tool\compiler.lua:37]: in function 'load'
    [@programdir\modules\private\action\build\object.lua:40]: in function 'script'
    [@programdir\modules\private\action\build\object.lua:103]: in function 'build_object'
    [@programdir\modules\private\action\build\object.lua:128]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:232]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:872: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\modules\private\async\runjobs.lua:256: in field 'catch'
        @programdir\core\sandbox\modules\try.lua:127: in global 'try'
        @programdir\modules\private\async\runjobs.lua:218: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:388: in function <@programdir\core\base\scheduler.lua:385>
stack traceback:
        @programdir\core\base\utils.lua:290: in function <@programdir\core\base\utils.lua:280>
        [C]: in function 'error'
        @programdir\core\base\os.lua:872: in function 'os.raiselevel'
        (...tail calls...)
        ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:56: in field 'co_start_withopt'
        @programdir\modules\private\async\runjobs.lua:217: in function <@programdir\modules\private\async\runjobs.lua:162>
        [C]: in function 'xpcall'
        @programdir\core\base\utils.lua:280: in function 'base/utils.trycall'
        @programdir\core\base\scheduler.lua:504: in function 'base/scheduler.co_group_begin'
        ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:94: in field 'co_group_begin'
        @programdir\modules\private\async\runjobs.lua:162: in function <@programdir\modules\private\async\runjobs.lua:56>
        (...tail calls...)
        @programdir\actions\build\build.lua:256: in function <@programdir\actions\build\build.lua:244>
        (...tail calls...)
        @programdir\actions\build\main.lua:103: in global '_do_build'
        @programdir\actions\build\main.lua:150: in function <@programdir\actions\build\main.lua:144>
        [C]: in function 'xpcall'
        @programdir\core\base\utils.lua:280: in function 'base/utils.trycall'
        @programdir\core\sandbox\modules\try.lua:121: in global 'try'
        @programdir\actions\build\main.lua:142: in function <@programdir\actions\build\main.lua:108>
        (...tail calls...)
        [C]: in function 'xpcall'
        @programdir\core\base\utils.lua:280: in function 'base/utils.trycall'
        (...tail calls...)
        @programdir\core\base\task.lua:501: in function 'base/task.run'
        @programdir\core\main.lua:278: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:388: in function <@programdir\core\base\scheduler.lua:385>
stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:872: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:280: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:388: in function <@programdir\core\base\scheduler.lua:385>

**Comment by waruqi** [comment]
不要在 msys2 的终端下运行，这里面默认会用 mingw 工具链，不是 vs

直接打开 cmd 执行编译就行了

**Comment by shenxin-karl** [comment]
谢谢, 确实是可以了

**Comment by shenxin-karl** [comment]
![image](https://user-images.githubusercontent.com/59679661/209157141-c9373358-21d6-4c6a-8328-acff61ca6a60.png)
不可以, 我重新安装了也不可以

**Comment by waruqi** [comment]
加 -c 重新检测，否则有 cache

```
 xmake f -c -vD 
```

**Comment by shenxin-karl** [comment]
解决了. 确实是缓存的问题. 非常感激

**Comment by isbdnt** [comment]
> 不要在 msys2 的终端下运行，这里面默认会用 mingw 工具链，不是 vs
> 
> 直接打开 cmd 执行编译就行了

能不能在msys2下指定用vs？

**Comment by isbdnt** [comment]
msys2的终端下指定vs
xmake f -c -vD -p windows
