### ISSUE TITLE
JSON output for auto complete 

### ISSUE THREAD

**Issue by glcraft** [xmake-io/xmake#3192]
### Is your feature request related to a problem? Please describe.

The auto completion support for xmake can be improved/extended for other shells like [Nu shell](https://www.nushell.sh/) or Powershell by outputting result in JSON.

### Describe the solution you'd like

Add on option for `xmake lua private.utils.complete` to output in JSON.

### Additional context

*Hold on for my PR in a bit :)*

**Comment by waruqi** [comment]
Thanks, I have merged it.
