### ISSUE TITLE
不能在另外一台机器上import 

### ISSUE THREAD

**Issue by jkawnkwh85** [xmake-io/xmake#3196]
### Xmake Version

v2.7.3+202211291633

### Operating System Version and Architecture

ubuntu 20.04

### Describe Bug

两台机器的系统以及xmake版本完全一致

但是在机器1上导出的包不能在机器上成功导入, 导入导出时使用的config完全一致。

导出命令
```
xrepo import -f"shared=true,max_quote_size=256" -i /nas_remote/xrepo_export "cts 1.2.4"
```
导入命令
```
xrepo import -f"shared=true,max_quote_size=256" -i /nas_remote/xrepo_export "cts 1.2.4"
```

报错信息
```
error: cannot copy file /nas_remote/xrepo_export/c/cts/1.2.4/0b6dae404095416b9c0927bd52389bfa, file not found!
error: execv(xmake require --import --packagedir=/nas_remote/xrepo_export --extra={system=false,configs={max_quote_size=256,shared=true}} "cts 1.2.4") failed(255)
```
导出的目录是
```
/nas_remote/xrepo_export/c/cts/1.2.4/c891d39094bb4945aed794cd8772954e
```

不知道为什么两边计算的hash不一样

### Expected Behavior

能够顺利的导入包

**Comment by waruqi** [comment]
> 导出命令
> xrepo import -f"shared=true,max_quote_size=256" -i /nas_remote/xrepo_export "cts 1.2.4"

import? 导出不应该是 export 么？

可以先试下本机导入导出

**Comment by jkawnkwh85** [comment]
> 

对，是export，写错了。

本机没有问题。

已经定位出来了，是因为max_quote_size的默认值带了引号， 在export 和import的时候对这种带有引号的值处理上似乎有不一致。目前把引号去掉就正常了。
