### ISSUE TITLE
Source release configuration directory handling completely broken

### ISSUE THREAD

**Issue by alerque** [xmake-io/xmake#3202]
### Xmake Version

2.7.4

### Operating System Version and Architecture

Source tarball, extracted on Linux

### Describe Bug

There are several issues with the source tarball and included configure script shipped in v2.7.4. This *seems* like a GNU Autotools style configure script, but it doesn't actually work in any of the standard ways. As a downstream packager I would appreciate if it was fixed so the expected functions work as in autotools. If you need help doing this right I may be able to help setup the tooling.

Here are some of the issues:

1. The sources don't extract with a top level directory. This makes a huge mess because the tar has no root directory. Sources build with `make dist` will always have the version number in the name and extract to a matching top level directory.

2. The configure script does not accept `./configure --prefix=...`. This is standard usage for distro packagers that don't use the usual /usr/local defaults and want to set /usr or similar instead.

3. The `make install DESTDIR="..."` does not function to accept a base director. This is also standard usage. This and no 2 only work if bundled together as `make install PREFIX="/base/prefix"`, but this is broken non-standard usage.

There may be more, I gave up trying to use it at all when I discovered the prefix and destination handling was cross wired.

### Expected Behavior

A top level directory in the source tarball, a `--prefix` configure flag that works, a DESTDIR install target that works.

**Comment by waruqi** [comment]
> The configure script does not accept ./configure --prefix=.... This is standard usage for distro packagers that don't use the usual /usr/local defaults and want to set /usr or similar instead.

It is supported and you can test it.

```console
./configure --prefix=/xxx
make
make install
```

About 1 and 3, I will improve it in the next two days

**Comment by waruqi** [comment]
> The make install DESTDIR="..." does not function to accept a base director. This is also standard usage. This and no 2 only work if bundled together as make install PREFIX="/base/prefix", but this is broken non-standard usage.

I have supported it now.

> The sources don't extract with a top level directory. This makes a huge mess because the tar has no root directory. Sources build with make dist will always have the version number in the name and extract to a matching top level directory.

I have modified it, you can try this tar bar.

[xmake.tar.gz](https://github.com/xmake-io/xmake/files/10299341/xmake.tar.gz)

**Comment by alerque** [comment]
Looking forward to the fixes in the next release, I'll update packaging when a stable version is tagged.

**Comment by alerque** [comment]
BTW the tar file you attached above has a top level directory, but it is not versioned. It is quite typical to distribute software with versioned files that extract to versioned directories because this avoids all sorts of possible headaches and confusion. The filename should be something like `xmake-X.Y.Z.tar.gz` and extract to a directory called `xmake-X.Y.Z` (Using a `v` prefix is optional, conventions vary widely on whether to include it in the filename and/or directory. In fact it's pretty common to find it used in the tar file name but not the extraction directory, which I think is weird but whatever. The important thing on this topic is to stay consistent between releases.).

**Comment by waruqi** [comment]
I have modified it. 

[xmake-v2.7.4.tar.gz](https://github.com/xmake-io/xmake/files/10303468/xmake-v2.7.4.tar.gz)

**Comment by alerque** [comment]
There is an extra `/./` in the tar file paths now. This will work for some situations and make a mess of others. Typically the paths would just be `xmake-X.Y.Z/<files>` not `./xmake-X.Y.Z/<files>`. You can pretty easily compare this with auto generated archives from e.g. GitHub. For example look at the this:

```console
$ wget https://github.com/xmake-io/xmake/archive/refs/tags/v2.7.4/xmake-2.7.4.tar.gz
$ tar xvfl xmake-2.7.4.tar.gz
```

...vs. the output of `tar xvfs` for the bundle you attached here. Again some tooling will deal with this, but others will not. In particular the depth extraction arguments to many tar related tools will be off by one and give unexpected results.

**Comment by waruqi** [comment]
I have improved it.

[xmake-v2.7.4.tar.gz](https://github.com/xmake-io/xmake/files/10305150/xmake-v2.7.4.tar.gz)

**Comment by waruqi** [comment]
I released new version. https://github.com/xmake-io/xmake/releases/download/v2.7.5/xmake-v2.7.5.tar.gz

**Comment by xaizek** [comment]
Oh, no.  You've removed old (working!) build system without a warning and giving a chance to try out `xmake.sh`.  Please don't make surprises like that, warn in a changelog beforehand and remove previous build only if there are no issues with the new one for a whole release or 3-4 month (whichever comes *last*).

`xmake.sh` seems to check presence of functions by compilation only which makes it think lua5.4/luajit is there, based on the headers from another version.  And specifying `--runtime=lua` doesn't change anything, I'd expect it to have higher priority than whatever is found automatically.

**Comment by waruqi** [comment]
> Oh, no. You've removed old (working!) build system without a warning and giving a chance to try out `xmake.sh`. Please don't make surprises like that, warn in a changelog beforehand and remove previous build only if there are no issues with the new one for a whole release or 3-4 month (whichever comes _last_).
> 
> `xmake.sh` seems to check presence of functions by compilation only which makes it think lua5.4/luajit is there, based on the headers from another version. And specifying `--runtime=lua` doesn't change anything, I'd expect it to have higher priority than whatever is found automatically.

If you encounter a problem, you can open a separate issue and provide verbose logs and I will fix it.

**Comment by xaizek** [comment]
It's basically one more bullet to this issue, build from source using `./configure` fails the same on v2.7.4 and v2.7.5 if you have installation of Lua from a different version.

**Comment by waruqi** [comment]
> It's basically one more bullet to this issue, build from source using `./configure` fails the same on v2.7.4 and v2.7.5 if you have installation of Lua from a different version.

please open a new issue and provide error.
