### ISSUE TITLE
The first argument is splitted in compile_commands.json when using Visual Studio

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#3203]
### Xmake 版本

2.7.4

### 操作系统版本和架构

Windows 10

### 描述问题

![image](https://user-images.githubusercontent.com/42310255/209461726-af02b137-8494-420d-82e8-6def6605aa54.png)
如图所示，第一个参数应该是cl.exe编译器，然而这里被拆开了，导致vscode不能正确识别

### 期待的结果

compile_commands.json的第一个参数应该是编译器

**Comment by waruqi** [comment]
再试试，xmake update -s dev

**Comment by xq114** [comment]
可以了
