### ISSUE TITLE
Build error when more than one target tries to use c++23 standard modules

### ISSUE THREAD

**Issue by Qudix** [xmake-io/xmake#3205]
### Xmake Version

v2.7.4+HEAD.8340827ed

### Operating System Version and Architecture

Windows 11

### Describe Bug

Whenever you have more than one target consume the standard c++23 modules with `import std` the build fails with:
![image](https://user-images.githubusercontent.com/17361645/209481976-b87e1eb0-bfc7-4098-9b61-b0487fb6c9db.png)

From a glance it appears that every target causes an individual `compiling.module.release std` build step which seem to conflict with each other due to the stl build output regenerating while the previous target is trying to use it. But that's just a guess.

### Expected Behavior

Multiple targets should be able to consume standard c++23 modules.

### Project Configuration

[test.zip](https://github.com/xmake-io/xmake/files/10300630/test.zip)

**Comment by Arthapz** [comment]
i can confirm the issue

![image](https://user-images.githubusercontent.com/27437334/209560861-d3e260ae-3936-4983-adc5-3a10b9cf4fc4.png)

**Comment by Arthapz** [comment]
@waruqi Is it possible to generate a std specific target from the `modules_support.load` function and add it as dependency to all other targets to avoid std compilation duplication ?

**Comment by Arthapz** [comment]
as a workaround @Qudix  you can create a "std-modules" target with a dummy module "stl" that export import std and import it instead of std for now (and `s/stl/std/g` when the bug is fixed)

**Comment by waruqi** [comment]
I have merged this patch, you can try it again.

**Comment by Qudix** [comment]
Has the CI successfully built the `dev` branch yet?

**Comment by Qudix** [comment]
Ok it does
