### ISSUE TITLE
无法检测Intel Fortran Compiler 2022 on Windows

### ISSUE THREAD

**Issue by indesperate** [xmake-io/xmake#3206]
### Xmake 版本

 2.7.4

### 操作系统版本和架构

Win11 22H2

### 描述问题

xmake 使用环境变量来检测Intel fortran toolkit，之前在Intel fortran 2021有过这样的问题，#1892，但是现在fortran22 使用IFORT_COMPLIER22环境变量，导致无法检测，我自己设置了一个环境变量IFOR_COMPILER21指向2022的版本可以正常检测。

### 期待的结果

使用一个通用的环境变量来检测Intel fortran，不然每次使用新版本都得更新，或者可以指定Intel fortran compiler version
个人建议使用$ONEAPI_ROOT，检测$ONEAPI_ROOT/compliler，（不过个人不确定这个变量是否所有版本的fortran安装一定会有），修改find_ifortenv.lua文件中的
```
paths = {"$(env IFORT_COMPILER21)"}
        ifortvars_bat = find_file("../../../setvars.bat", paths)
```
为
```
paths = {"$(env ONEAPI_ROOT)"}
        ifortvars_bat = find_file("setvars.bat", paths)
```
不过这样好像有个问题就是无法确定fortran compiler是否一定存在，其他intel套件感觉也有这个问题。

**Comment by waruqi** [comment]
> 使用一个通用的环境变量来检测Intel fortran，不然每次使用新版本都得更新，或者可以指定Intel fortran compiler version

关键是这东西不是 xmake 约定的，是 ifortran 工具链装完，它自己设置的环境变量

xmake 只会去尝试性探测各种已有的东西，如果它设置了 IFORT_COMPLIER21，就尝试读取它去改进探测而已

xmake 不会自己去定义这些，也不会新增一些自己的环境变量定义，没意义。

**Comment by waruqi** [comment]
所以如果它提供了 IFORT_COMPLIER22，就提个pr过来，继续改进读取，支持上22就行了

**Comment by indesperate** [comment]
我的意思是Intel现在好像把自己的套件都整合为OneAPI，然后现在有了ONEAPI_ROOT这样一个ifortran工具链装完也有的环境变量，是否考虑探测这样一个环境变量来进行检测所有的Intel api 套件，而且Intel在自己的compiler，debugger目录下都创建了一个lastest文件软链接指向最新的版本来保证最新的套件路径不变，但是我不确定是否是最近才有ONEAPI_ROOT这样一个环境变量。不过最简单的方法就是加一个 IFORT_COMPLIER22。

**Comment by waruqi** [comment]
如果它提供了 ONEAPI_ROOT 就可以利用它来改进查找，IFORT_COMPLIER22 也还是可以继续利用起来，你可以提个pr过来改进下

**Comment by indesperate** [comment]
我是研究核物理的工科生，整天和上古的fortran代码战斗😂，xmake真的比cmake语法友好太多了，我非常喜欢lua这个语言👍，我都准备在我们组宣传一下了，不过我没这方面的经验，pr我尽力试一下，我先测试一下不同版本的intel套件是否都会设置这样一个变量。

**Comment by waruqi** [comment]
多谢支持，已 merge 。
