### ISSUE TITLE
xmake使用keil8051编译8051项目出现链接问题

### ISSUE THREAD

**Issue by lanjackg2003** [xmake-io/xmake#3211]
### Xmake 版本

v2.7.4+HEAD.8340827ed

### 操作系统版本和架构

Windows 11 专业版 22H2

### 描述问题

- xmake脚本
```lua
add_rules("mode.debug", "mode.release")
set_defaultplat("cross")
target("Test")
    set_kind("binary")
    add_rules("c51.binary")
    set_toolchains("c51")
    add_files("main.c")
```
- `main.c`代码
```c
#pragma NOAREGS
void main()
{

	while (1)
	{
		/* code */
	}
	
}
```
- `xmake -rv`编译输出错误信息
```
[ 25%]: cache compiling.release main.c
C:\Keil_v5\C51\bin\c51 main.c -DNDEBUG
C51 COMPILER V9.60.0.0 - SN: K1DZC-HAZGGC
COPYRIGHT Copyright (C) 2012 - 2019 ARM Ltd and ARM Germany GmbH. All rights reserved.
C51 COMPILATION COMPLETE.  0 WARNING(S),  0 ERROR(S)
[ 50%]: linking.release Test
C:\Keil_v5\C51\bin\bl51 build\.objs\Test\cross\8051\release\main.c.o TO build\cross\8051\release\Test
error: 
BL51 BANKED LINKER/LOCATER V6.22.2.0 - SN: K1DZC-HAZGGC
COPYRIGHT ARM Germany GmbH 1987 - 2017

*** FATAL ERROR L218: NOT AN OBJECT FILE
    FILE: BUILD\.OBJS\TEST\CROSS\8051\RELEASE\MAIN.C.O
```
从编译输出的临时文件看,用于链接成二进制文件的应该是`.obj`后缀的文件,而非`.o`文件
![图片](https://user-images.githubusercontent.com/20794381/209546422-7f01eb09-abed-4e5e-aa66-04e48c752ba2.png)

可以手动将原`mai.c.o`文件删除,并将`main.c.OBJ`重名为`mai.c.o`,再执行`xmake -bv`,此时会编译成功
···
$ xmake -bv
[ 50%]: linking.release Test
C:\Keil_v5\C51\bin\bl51 build\.objs\Test\cross\8051\release\main.c.o TO build\cross\8051\release\Test
checking for bl51.exe ... no
checking for C:\Keil_v5\C51\bin\bl51.exe ... ok
checking for oh51.exe ... no
checking for C:\Keil_v5\C51\bin\oh51.exe ... ok
[ 50%]: generating.release build\cross\8051\release\Test.hex
[100%]: build ok!
···
![图片](https://user-images.githubusercontent.com/20794381/209546715-44a6f0fe-0a08-435e-b219-427e486b6a88.png)

keil8051编译器生成的文件不是.o结尾,而是.OBJ结尾
但是xmake在链接过程使用的是`.o`文件,因而导致编译失败

### 期待的结果

xmake可以扩展一个接口给用户来指定编译器生成的中间文件的后缀
这样更加灵活会更加灵活解决编译器中间文件不一致导致编译问题

### 工程配置

add_rules("mode.debug", "mode.release")
set_defaultplat("cross")
target("Test")
    set_kind("binary")
    add_rules("c51.binary")
    set_toolchains("c51")
    add_files("main.c")

### 附加信息和错误日志

[ 25%]: cache compiling.release main.c
C:\Keil_v5\C51\bin\c51 main.c -DNDEBUG
C51 COMPILER V9.60.0.0 - SN: K1DZC-HAZGGC
COPYRIGHT Copyright (C) 2012 - 2019 ARM Ltd and ARM Germany GmbH. All rights reserved.
C51 COMPILATION COMPLETE.  0 WARNING(S),  0 ERROR(S)
[ 50%]: linking.release Test
C:\Keil_v5\C51\bin\bl51 build\.objs\Test\cross\8051\release\main.c.o TO build\cross\8051\release\Test
error: 
BL51 BANKED LINKER/LOCATER V6.22.2.0 - SN: K1DZC-HAZGGC
COPYRIGHT ARM Germany GmbH 1987 - 2017

*** FATAL ERROR L218: NOT AN OBJECT FILE
    FILE: BUILD\.OBJS\TEST\CROSS\8051\RELEASE\MAIN.C.O

**Comment by waruqi** [comment]
那是因为你设置了 set_defaultplat("cross")

examples和文档里可没说要设置这个

**Comment by lanjackg2003** [comment]
> 那是因为你设置了 set_defaultplat("cross")
> 
> examples和文档里可没说要设置这个

确实是去掉这个编译平台配置就ok了
- https://xmake.io/#/zh-cn/guide/project_examples?id=keilc51-%e5%b5%8c%e5%85%a5%e5%bc%8f%e7%a8%8b%e5%ba%8f

是我不理解`-p`参数中传`cross`的意义,
我认为`cross`表示生成的编译目标将运行在嵌入式设备上

我应该在什么场景下才使用到`cross`呢
我看人家的文章使用SDCC时候传了`cross`参数
`xmake f -p cross --toolchain=sdcc -a mcs51 --sdk="c:\program files\sdcc"`

- https://blog.csdn.net/m0_37685403/article/details/127734704?spm=1001.2101.3001.6650.9&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromBaidu%7ERate-9-127734704-blog-120377718.pc_relevant_multi_platform_whitelistv3&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromBaidu%7ERate-9-127734704-blog-120377718.pc_relevant_multi_platform_whitelistv3&utm_relevant_index=18

**Comment by waruqi** [comment]
具体得看工具链，通常只有交叉编译工具链才需要，c51 目前不需要，主要是因为 c51 的编译无法修改 obj 路径和后缀，有些限制，当然后期要支持 cross 也是可以的，得改进对 obj file 的处理才行。
