### ISSUE TITLE
依赖编译时没有使用add_requireconfs() 里指定的版本

### ISSUE THREAD

**Issue by jkawnkwh85** [xmake-io/xmake#3219]
### Xmake 版本

v2.7.3+202211291633

### 操作系统版本和架构

Ubuntu 20.04

### 描述问题

```
add_rules("mode.debug", "mode.release")

add_requires("cas_passthrough")
add_requireconfs("*.cts", {override = true, version = "1.1.6", configs = {shared = true}})

target("test_diamond")
    set_kind("binary")
    add_packages("cas_passthrough")
    add_files("src/*.cpp")
```

用以上的xmake.lua 构建项目，其中cas_passthrough 依赖cts，使用add_requireconfs强制指定cts版本为1.1.6.
在build时，xmake还是会下载安装1.1.6版本以及最新的cts 1.2.4版本。
并且在编译时会使用1.2.4版本cts的头文件, 
<img width="1488" alt="image" src="https://user-images.githubusercontent.com/117454019/209665613-3c0b4bd0-2599-45cc-97ec-c131277e6e43.png">

但是build好的cas_passthrough包的manifest.txt里的deps确实是1.1.6版本的cts
<img width="567" alt="image" src="https://user-images.githubusercontent.com/117454019/209665501-213ad864-0995-401f-bd0d-fe379ead3128.png">

cas_passthrough的项目构建xmake.lua
```
add_rules("mode.debug", "mode.release", "mode.asan", "mode.tsan", "mode.lsan", "mode.ubsan")
set_project("cts_passthrough")
set_version("0.1.7")
set_languages("c++17")
add_requires("cts", "quill")
add_includedirs("$(projectdir)/include")
add_syslinks("pthread", "rt", "z")
target("cas_passthrough")
    set_kind("$(kind)")
    add_headerfiles("include/*.h")
    add_packages( "cts", "quill")
    add_files("src/**.cpp")
```

远程包文件
```
package("cas_passthrough")
    set_description("The cas_passthrough package")

    add_urls("git://dummy_url")

    add_versions("0.1.7", "b5e441bbb978ecd0b150fcb41ba959b63e0cece9")

    add_deps("cts")

    on_install(function (package)
        local configs = {}
        if package:config("shared") then
            configs.kind = "shared"
        end
        import("package.tools.xmake").install(package, configs)
    end)

    on_test(function (package)
        -- TODO check includes and interfaces
        -- assert(package:has_cfuncs("foo", {includes = "foo.h"})
    end)
```

### 期待的结果

在build cas_passthrough 时使用add_requireconfs指定的cts版本

**Comment by waruqi** [comment]
add_requireconfs 只会改包里的配置，也就是 add_deps 里面的，你 cas_passthrough 里面自身项目用 xmake.lua 维护的, 是独立的，里面的 add_requires("cts") 还是默认的，你得自己根据 package:dep("cts"):version_str() 传入你的 xmake.lua 

参考：https://github.com/xmake-io/xmake-repo/blob/17ac997fc055dc81f20a12ec775a51fc3fe9b558/packages/i/imguizmo/xmake.lua#L30

> cas_passthrough的项目构建xmake.lua

> add_rules("mode.debug", "mode.release", "mode.asan", "mode.tsan", "mode.lsan", "mode.ubsan")
> set_project("cts_passthrough")
> set_version("0.1.7")
> set_languages("c++17")
> add_requires("cts", "quill") <---

**Comment by jkawnkwh85** [comment]
好的，感谢！

**Comment by jkawnkwh85** [comment]
> add_requireconfs 只会改包里的配置，也就是 add_deps 里面的，你 cas_passthrough 里面自身项目用 xmake.lua 维护的, 是独立的项目，包配置影响不到它，里面的 add_requires("cts") 还是默认的，你得自己根据 package:dep("cts"):version_str() 传入你的 xmake.lua
> 
> 参考：https://github.com/xmake-io/xmake-repo/blob/17ac997fc055dc81f20a12ec775a51fc3fe9b558/packages/i/imguizmo/xmake.lua#L30
> 
> > cas_passthrough的项目构建xmake.lua
> 
> > add_rules("mode.debug", "mode.release", "mode.asan", "mode.tsan", "mode.lsan", "mode.ubsan")
> > set_project("cts_passthrough")
> > set_version("0.1.7")
> > set_languages("c++17")
> > add_requires("cts", "quill") <---

还有个问题请教下，对于本身也是用xmake.lua维护的项目，是否可以用包的add_configs 之类的选项把依赖的版本透传过去？我参考了您提供的imgui的例子，这个相当于要把项目的xmake.lua 在包配置里拷贝一份？

**Comment by waruqi** [comment]
> 我参考了您提供的imgui的例子，这个相当于要把项目的xmake.lua 在包配置里拷贝一份？

不是 这个包本身没 xmake.lua，只是 port 了下

**Comment by jkawnkwh85** [comment]
好的，感谢！
