### ISSUE TITLE
生成的 compile_commands 中带空格路径被切分

### ISSUE THREAD

**Issue by MasterBalll** [xmake-io/xmake#3242]
### Xmake 版本

2.7.4

### 操作系统版本和架构

Windows 10 version 22H2

### 描述问题

更新到 2.7.4 后，出现如下现象。
![image](https://user-images.githubusercontent.com/122007764/210744796-d1b4ba1b-1ead-4a85-9d33-6c2f3866efe0.png)

### 期待的结果

正确处理路径空格。

**Comment by waruqi** [comment]
看下这个。https://github.com/xmake-io/xmake/issues/3217
