### ISSUE TITLE
msvc standard modules fail

### ISSUE THREAD

**Issue by andylizf** [xmake-io/xmake#3243]
### Xmake Version

v2.7.4+HEAD.8340827ed

### Operating System Version and Architecture

Windows 11 version 21H2

### Describe Bug

With Visual Studio 17.5 preview 2, I cloned [stdmodules example](https://github.com/xmake-io/xmake/tree/master/tests/projects/c%2B%2B/modules/stdmodules) and ran `xmake` but it did not work at all, reporting:
> [  7%]: compiling.module.release my_module
> error: my_module.mpp
> src\my_module.mpp(3): error C2230: could not find module 'std'

seems that #3168 does not work.

### Expected Behavior

It compiles.

**Comment by waruqi** [comment]
@Arthapz any idea? Do the std modules need to be installed separately?

**Comment by Arthapz** [comment]
mmmh it should work 
![image](https://user-images.githubusercontent.com/27437334/210800854-80327397-7c17-4ca4-8b70-5b8f106c431f.png)


and std modules doesn't need to be installed separately, plz check you have std.ixx / std.compat.ixx in
<PATH_OF_VISUALSTUDIO>\VC\Tools\MSVC\14.35.32124\modules

and can you submit the entire log with -vD of your build ?

**Comment by andylizf** [comment]
Yes, they are there, while `xmake -vD` reported:
<details>
  <summary>content</summary>

  > checking for platform ... windows
  > checking for architecture ... x64
  > checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32124\bin\HostX64\x64\cl.exe
  > checking for Microsoft Visual Studio (x64) version ... 2022
  > checking for Microsoft C/C++ Compiler (x64) version ... 19.35.32124
  > checkinfo: cannot runv(dmd.exe --version), No such file or directory
  > checking for dmd ... no
  > checkinfo: cannot runv(ldc2.exe --version), No such file or directory
  > checking for ldc2 ... no
  > checkinfo: cannot runv(gdc.exe --version), No such file or directory
  > checking for gdc ... no
  > checkinfo: cannot runv(zig.exe version), No such file or directory
  > checking for zig ... no
  > checkinfo: cannot runv(zig.exe version), No such file or directory
  > checking for zig ... no
  > checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32124\bin\HostX64\x64\cl.exe
  > checking for the c++ compiler (cxx) ... cl.exe
  > checking for C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32124\bin\HostX64\x64\cl.exe ... ok
  > checking for flags (cl_experimental_module) ... ok
  > cl.exe "-experimental:module"
  > checking for link.exe ... C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32124\bin\HostX64\x64\link.exe
  > checking for the linker (ld) ... link.exe
  > checking for flags (cl_scan_dependencies) ... ok
  > cl.exe "-scanDependencies" "C:\Users\andyl\AppData\Local\Temp\.xmake\230106\_7D5BF3A2C2734B208EFB40B5DF3B2730.json"
  > [  0%]: generating.module.deps test\test.cpp
  > checking for flags (-O2 -fp:fast) ... ok
  > cl.exe "-O2" "-fp:fast"
  > checking for flags (-experimental:module) ... ok
  > cl.exe "-experimental:module"
  > checking for flags (-DNDEBUG) ... ok
  > cl.exe "-DNDEBUG"
  > C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32124\bin\HostX64\x64\cl.exe -nologo -O2 -fp:fast -std:c++latest /EHsc -experimental:module -DNDEBUG -TP -scanDependencies build\.gens\test\windows\x64\release\rules\modules\cache\test\test.cpp.json test\test.cpp -Fobuild\.objs\test\windows\x64\release\test\test.cpp.obj
  > test.cpp
  > checking for flags (cl_ifc_output) ... ok
  > cl.exe "-ifcOutput"
  > checking for flags (cl_interface) ... ok
  > cl.exe "-interface"
  > checking for flags (cl_reference) ... ok
  > cl.exe "-reference"
  > checking for flags (cl_internal_partition) ... ok
  > cl.exe "-internalPartition"
  > [  0%]: generating.module.deps src\my_module.cpp
  > C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32124\bin\HostX64\x64\cl.exe -nologo -O2 -fp:fast -std:c++latest /EHsc -experimental:module -DNDEBUG -TP -scanDependencies build\.gens\mod\windows\x64\release\rules\modules\cache\src\my_module.cpp.json src\my_module.cpp -Fobuild\.objs\mod\windows\x64\release\src\my_module.cpp.obj
  > my_module.cpp
  > [  0%]: generating.module.deps src\my_module.mpp
  > C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32124\bin\HostX64\x64\cl.exe -nologo -O2 -fp:fast -std:c++latest /EHsc -experimental:module -DNDEBUG -TP -scanDependencies build\.gens\mod\windows\x64\release\rules\modules\cache\src\my_module.mpp.json src\my_module.mpp -Fobuild\.objs\mod\windows\x64\release\src\my_module.mpp.obj
  > my_module.mpp
  > [  7%]: compiling.module.release my_module
  > "C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\VC\\Tools\\MSVC\\14.35.32124\\bin\\HostX64\\x64\\cl.exe" -c -TP -nologo -O2 -fp:fast -std:c++latest /EHsc -experimental:module -DNDEBUG -TP -ifcOutput build\.gens\mod\windows\x64\release\rules\modules\cache\my_module.ifc -interface -Fobuild\.objs\mod\windows\x64\release\src\my_module.mpp.obj src\my_module.mpp
  > checking for flags (cl_sourceDependencies) ... ok
  > cl.exe "/sourceDependencies" "C:\Users\andyl\AppData\Local\Temp\.xmake\230106\_D4338D18197B4B0085FD51387A62E940.json"
  > error: @programdir\modules\private\async\runjobs.lua:256: @programdir\rules\c++\modules\modules_support\msvc.lua:123: @programdir\modules\core\tools\cl.lua:648: my_module.mpp
  > src\my_module.mpp(3): error C2230: could not find module 'std'
  > 
  > stack traceback:
  >     [C]: in function 'error'
  >     [@programdir\core\base\os.lua:897]:
  >     [@programdir\modules\core\tools\cl.lua:648]: in function 'catch'
  >     [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
  >     [@programdir\modules\core\tools\cl.lua:587]:
  >     [C]: in function 'xpcall'
  >     [@programdir\core\base\utils.lua:280]:
  >     [@programdir\rules\c++\modules\modules_support\msvc.lua:123]: in function '_build_modulefile'
  >     [@programdir\rules\c++\modules\modules_support\msvc.lua:503]: in function 'jobfunc'
  >     [@programdir\modules\private\async\runjobs.lua:232]:
  >     [C]: in function 'xpcall'
  >     [@programdir\core\base\utils.lua:280]: in function 'trycall'
  >     [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
  >     [@programdir\modules\private\async\runjobs.lua:218]: in function 'cotask'
  >     [@programdir\core\base\scheduler.lua:404]:
  > 
  > stack traceback:
  >         [C]: in function 'error'
  >         @programdir\core\base\os.lua:897: in function 'base/os.raiselevel'
  >         (...tail calls...)
  >         @programdir\modules\private\async\runjobs.lua:256: in field 'catch'
  >         @programdir\core\sandbox\modules\try.lua:123: in global 'try'
  >         @programdir\modules\private\async\runjobs.lua:218: in upvalue 'cotask'
  >         @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>
</details>

**Comment by andylizf** [comment]
An interesting fact: changing language standard from c++latest to c++23 in xmake.lua config file solves this issue.
Maybe this is because c++latest flag is ignored evaluating `isatleastcpp23` variable in [msvc.lua](https://github.com/xmake-io/xmake/pull/3168/files#diff-612af26a753191155382645dc74ddd52b5438699fbb45c072d068a1e002f700d)

**Comment by Arthapz** [comment]
can you test with dev branch ? `xmake update -s dev`

it's an issue that i already fixed in dev i think

**Comment by andylizf** [comment]
Yes, you are right. I just edited msvc.lua a few minutes ago and found that a supplementary check for `language:endswith("latest")` fixed it.
