### ISSUE TITLE
add_urls/set_urls should try the main branch if master doesn't exist

### ISSUE THREAD

**Issue by Arthapz** [xmake-io/xmake#3248]
### Xmake Version

2.7.4

### Operating System Version and Architecture

Windows 11

### Describe Bug

A while back Github changed the default branch from master to main for reasons I won't get into. add_urls/set_urls allows you to set the branch yourself via add_versions but when it is omited xmake try to clone master branch which could not exist anymore, but ideally it should handle this specific situation automatically.

### Expected Behavior

Like #2886 

add_urls/set_urls should consider the main alongside the master branch automatically when submitting a git repo.

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/pull/3250

But I don't recommend that users remove set_versions, it should always be set.

**Comment by Arthapz** [comment]
it's working now !

>But I don't recommend that users remove set_versions, it should always be set.
You're right, but it should work "in case of"
