### ISSUE TITLE
Detection of libraries by their functions is broken in configure 

### ISSUE THREAD

**Issue by xaizek** [xmake-io/xmake#3263]
### Xmake Version

2.7.4, 2.7.5, probably all other with configure script.

### Operating System Version and Architecture

Slackware 15.0

### Describe Bug

It checks presence of functions in a library by compilation only which makes it think lua5.4/luajit is there because headers from another version of Lua are present.

### Expected Behavior

lua5.4/luajit isn't detected as present when they aren't installed.

### Additional Information and Error Logs

[configure-diagnosis.log](https://github.com/xmake-io/xmake/files/10368574/configure-diagnosis.log)
[make-verbose.log](https://github.com/xmake-io/xmake/files/10368575/make-verbose.log)

**Comment by waruqi** [comment]
please checkout dev branch and run `./configure --lua=y --luajit=n; make` to disable system lua/luajit library first.

and I will fix detect lua/luajit libs without links later.

**Comment by xaizek** [comment]
Thanks, but configuring with `./configure --lua=y --luajit=n` or `./configure --lua=n --luajit=n` makes no difference. This will do for now:
```
sed -i '/^option "lua"/,/^option_end/d' core/xmake.sh
sed -i '/^option "luajit"/,/^option_end/d' core/xmake.sh
```

**Comment by waruqi** [comment]
mymistake, it should be `./configure --lua=n --luajit=n`

**Comment by waruqi** [comment]
I have improve it on dev branch. you can try `./configure; make` again.

**Comment by xaizek** [comment]
Fixed on `master`, thanks.
