### ISSUE TITLE
install failed, "nil\bin\Demo.exe" does not exist.

### ISSUE THREAD

**Issue by freestriker** [xmake-io/xmake#3266]
### Xmake 版本

2.7.4

### 操作系统版本和架构

Windows 10 专业版22H2 19045.2364

### 描述问题

在根目录使用xmake，可以正常build，但使用xmake install，会出现install failed, "nil\bin\Demo.exe" does not exist.的错误，似乎是内部路径为null。删除.xmake文件夹后重新 install依然不行。

PS E:\Projects\AirEngine> xmake
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Qt SDK directory ... C:/Software/QT/6.4.1/msvc2019_64
checking for Qt SDK version ... 6.4.1
[ 18%]: cache compiling.release Runtime\Core\Context.cpp
[ 18%]: cache compiling.release Runtime\Core\Manager\GraphicDeviceManager.cpp
[ 18%]: cache compiling.release Runtime\Core\Manager\ManagerInitializer.cpp
[ 18%]: cache compiling.release Demo\main.cpp
[ 18%]: cache compiling.release Runtime\Core\Manager\ManagerBase.cpp
[ 63%]: linking.release Runtime.dll
[ 81%]: linking.release Demo.exe
[100%]: build ok!
PS E:\Projects\AirEngine> xmake install
installing Runtime ..
installing Demo ..
error: install failed, "nil\bin\Demo.exe" does not exist.

### 期待的结果

存在某种方式重新设置根路径或重新检查项目设置

### 工程配置

AirEngine
--xmake.lua
--Runtime
----xmake.lua
--Demo
----xmake.lua

AirEngine下lua：
set_project("AirEngine")

add_rules("mode.debug", "mode.release")

add_requires("boost", {configs = {all = true}})

add_packages("boost")

set_languages("cxx17")
add_cxxflags("cl::/Zc:__cplusplus /permissive-")
add_defines("NOMINMAX")

includes("Runtime", "Demo")

Runtime下lua：
target("Runtime")
    add_rules("qt.shared")
    add_files("**.cpp")
    add_headerfiles(("**.hpp"))
    add_defines("DLL_EXPORTS")

Demo下lua：
target("Demo")
    add_rules("qt.widgetapp")
    add_files("**.cpp")
    add_headerfiles(("**.hpp"))
    add_deps("Runtime")

### 附加信息和错误日志

PS E:\Projects\AirEngine> xmake install -vD
installing Runtime ..
installing Demo ..
C:\Software\QT\6.4.1\msvc2019_64\bin\windeployqt.exe --force --verbose=2 --release nil\bin\Demo.exe
"nil\bin\Demo.exe" does not exist.

error: @programdir\core\main.lua:280: @programdir\actions\install\main.lua:124: install failed, @programdir\core\sandbox\modules\os.lua:372: execv(C:\Software\QT\6.4.1\msvc2019_64\bin\windeployqt.exe --force --verbose=2 --release nil\bin\Demo.exe) failed(1)
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:897]:
    [@programdir\core\sandbox\modules\os.lua:372]:
    [@programdir\core\sandbox\modules\os.lua:285]: in function 'vrunv'
    [@programdir\rules\qt\install\windows.lua:94]:
    [@programdir\actions\install\install.lua:79]: in function 'script'
    [@programdir\actions\install\install.lua:90]: in function '_install_target'
    [@programdir\actions\install\install.lua:121]:
    [@programdir\actions\install\main.lua:85]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:897: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:280: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>

**Comment by waruqi** [comment]
win下你暂定 xmake install -o xxx 指定安装目录，否则不知道装哪
