### ISSUE TITLE
不能加载vulkansdk

### ISSUE THREAD

**Issue by freestriker** [xmake-io/xmake#3268]
### Xmake 版本

2.7.5

### 操作系统版本和架构

Windows 10 专业版22H2 19045.2364

### 描述问题

在项目目录使用xmake l find_package vulkansdk可以找到本机安装的VulkanSDK，但在xmake.lua中添加包后，使用 xmake project -k vsxmake -vD后提示The packages(vulkansdk) not found, please run `xmake repo -u` first!使用xmake repo -u后报错依旧，将xmake.lua中的替换为add_requires("vulkansdk", {system = true})后，报错note: the following packages were not found on your system, try again after installing them:-> vulkansdk latest。但缓存目录的packages/v中确实存在vulkansdk但内部只有一个空latest文件夹。
尝试删除项目中.xmake文件夹重试后无效。

### 期待的结果

设置vulkansdk路径或add_requires中用更多可选参数

### 工程配置

AirEngine
--xmake.lua
--Runtime
----xmake.lua
--Demo
----xmake.lua

AirEngine下lua：
set_project("AirEngine")

add_rules("mode.debug", "mode.release")

add_requires("boost", {configs = {all = true}})

add_packages("boost")

set_languages("cxx17")
add_cxxflags("cl::/Zc:__cplusplus /permissive-")
add_defines("NOMINMAX")

includes("Runtime", "Demo")

Runtime下lua：
add_requires("vulkansdk", {system = true})
add_requires("vk-bootstrap")

target("Runtime")
    add_rules("qt.shared")
    add_files("**.cpp")
    add_headerfiles(("**.hpp"))
    add_packages("vulkansdk")
    add_packages("vk-bootstrap")
    add_defines("DLL_EXPORTS")

Demo下lua：
target("Demo")
add_rules("qt.widgetapp")
add_files(".cpp")
add_headerfiles((".hpp"))
add_deps("Runtime")

### 附加信息和错误日志

PS E:\Projects\AirEngine> xmake l find_package vulkansdk
{
  links = {
    "vulkan-1"
  },
  apiversion = "1.3.224",
  includedirs = {
    "E:\Software\VulkanSDK\1.3.211.0\include"
  },
  linkdirs = {
    "E:\Software\VulkanSDK\1.3.211.0\lib"
  },
  bindir = "E:\Software\VulkanSDK\1.3.211.0\bin",
  sdkdir = "E:\Software\VulkanSDK\1.3.211.0"
}
PS E:\Projects\AirEngine> xmake project -k vsxmake -vD
checking for qmake ... C:\Software\QT\6.4.1\msvc2019_64\bin\qmake
checking for Qt SDK directory ... C:/Software/QT/6.4.1/msvc2019_64
checking for Qt SDK version ... 6.4.1
checkinfo: cannot runv(link.exe -lib -out:E:\Data\XMake\temp\.xmake\230109\_9F49F2F167134A70897C05B50408B2C0.exe E:\Data\XMake\temp\.xmake\230109\_64FFDE8E6E6644108714D3DD5700B330.obj), No such file or directory
checking for link.exe ... no
checking for the shared library linker (sh: link.exe) ... no
checking for Cuda SDK directory ... C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
checkinfo: cannot runv(C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvc++.exe --version), No such file or directory
checking for C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvc++ ... no
checkinfo: cannot runv(nvc++.exe --version), No such file or directory
checking for nvc++ ... no
checking for the shared library linker (sh: nvc++) ... no
checkinfo: cannot runv(C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvc.exe --version), No such file or directory
checking for C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvc ... no
checkinfo: cannot runv(nvc.exe --version), No such file or directory
checking for nvc ... no
checking for the shared library linker (sh: nvc) ... no
checkinfo: cannot runv(link.exe -lib -out:E:\Data\XMake\temp\.xmake\230109\_B0C9E04DEE5449008C81E3F9A8E53080.exe E:\Data\XMake\temp\.xmake\230109\_533ED4CD6EE94D508AD21B19C31A9BB0.obj), No such file or directory
checking for link.exe ... no
checking for the linker (ld: link.exe) ... no
checkinfo: cannot runv(C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvc++.exe --version), No such file or directory
checking for C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvc++ ... no
checkinfo: cannot runv(nvc++.exe --version), No such file or directory
checking for nvc++ ... no
checking for the linker (ld: nvc++) ... no
checkinfo: cannot runv(C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvc.exe --version), No such file or directory
checking for C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvc ... no
checkinfo: cannot runv(nvc.exe --version), No such file or directory
checking for nvc ... no
checking for the linker (ld: nvc) ... no
configure
{
    cuda = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
    plat = windows
    vs = 2022
    qt_sdkver = 6.4.1
    ccache = true
    ndk_stdcxx = true
    qt = C:/Software/QT/6.4.1/msvc2019_64
    buildir = build
    arch = x64
    host = windows
    mode = release
    kind = static
}
using project kind vs2022
checking for debug.x86 ...
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\bin\HostX86\x86\cl.exe
checking for Microsoft Visual Studio (x86) version ... 2022
checkinfo: cannot runv(dmd.exe --version), No such file or directory
checking for dmd ... no
checkinfo: cannot runv(ldc2.exe --version), No such file or directory
checking for ldc2 ... no
checkinfo: cannot runv(gdc.exe --version), No such file or directory
checking for gdc ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(unzip.exe -v), No such file or directory
checking for unzip ... no
checking for 7z ... E:\Software\xmake\winenv\bin\7z
checking for git ... ok
checkinfo: cannot runv(gzip.exe --version), No such file or directory
checking for gzip ... no
git rev-parse HEAD
finding vulkansdk from xmake ..
checking for xmake::vulkansdk ... no
checking for cmake ... E:\Software\CMake\bin\cmake
checking for cmake ... E:\Software\CMake\bin\cmake
finding vulkan-headers from xmake ..
checking for xmake::vulkan-headers ... vulkan-headers 1.3.231+1
finding vk-bootstrap from xmake ..
checking for xmake::vk-bootstrap ... vk-bootstrap v0.5
finding boost from xmake ..
checking for xmake::boost ... boost 1.81.0
note: the following packages were not found on your system, try again after installing them:
  -> vulkansdk latest
error: @programdir\core\main.lua:280: stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:909]:
    [...modules\private\action\require\impl\install_packages.lua:739]:
    [@programdir\modules\private\action\require\install.lua:85]:
    [@programdir\plugins\project\vsxmake\getinfo.lua:494]:
    [@programdir\plugins\project\vsxmake\vsxmake.lua:224]: in function '?'
    [@programdir\plugins\project\main.lua:79]: in function '_make'
    [@programdir\plugins\project\main.lua:92]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\base\task.lua:501]: in function 'run'
    [@programdir\core\main.lua:278]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:404]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:898: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:280: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>
PS E:\Projects\AirEngine> xmake repo -u
updating repositories .. ok
PS E:\Projects\AirEngine> xmake project -k vsxmake -vD
checking for qmake ... C:\Software\QT\6.4.1\msvc2019_64\bin\qmake
checking for Qt SDK directory ... C:/Software/QT/6.4.1/msvc2019_64
checking for Qt SDK version ... 6.4.1
checkinfo: cannot runv(link.exe -lib -out:E:\Data\XMake\temp\.xmake\230109\_25DAD73E3D6B4350808F58A2732FAFB0.exe E:\Data\XMake\temp\.xmake\230109\_F7339399E34A46708473477F090D11E0.obj), No such file or directory
checking for link.exe ... no
checking for the shared library linker (sh: link.exe) ... no
checking for Cuda SDK directory ... C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
checkinfo: cannot runv(C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvc++.exe --version), No such file or directory
checking for C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvc++ ... no
checkinfo: cannot runv(nvc++.exe --version), No such file or directory
checking for nvc++ ... no
checking for the shared library linker (sh: nvc++) ... no
checkinfo: cannot runv(C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvc.exe --version), No such file or directory
checking for C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvc ... no
checkinfo: cannot runv(nvc.exe --version), No such file or directory
checking for nvc ... no
checking for the shared library linker (sh: nvc) ... no
checkinfo: cannot runv(link.exe -lib -out:E:\Data\XMake\temp\.xmake\230109\_8A9068D6F19E47708B08A111D37B0AC0.exe E:\Data\XMake\temp\.xmake\230109\_05181A2D64F942308D06C00C43ECF290.obj), No such file or directory
checking for link.exe ... no
checking for the linker (ld: link.exe) ... no
checkinfo: cannot runv(C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvc++.exe --version), No such file or directory
checking for C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvc++ ... no
checkinfo: cannot runv(nvc++.exe --version), No such file or directory
checking for nvc++ ... no
checking for the linker (ld: nvc++) ... no
checkinfo: cannot runv(C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvc.exe --version), No such file or directory
checking for C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvc ... no
checkinfo: cannot runv(nvc.exe --version), No such file or directory
checking for nvc ... no
checking for the linker (ld: nvc) ... no
configure
{
    vs = 2022
    ccache = true
    qt = C:/Software/QT/6.4.1/msvc2019_64
    host = windows
    buildir = build
    arch = x64
    cuda = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
    mode = release
    kind = static
    ndk_stdcxx = true
    plat = windows
    qt_sdkver = 6.4.1
}
using project kind vs2022
checking for debug.x86 ...
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\bin\HostX86\x86\cl.exe
checking for Microsoft Visual Studio (x86) version ... 2022
checkinfo: cannot runv(dmd.exe --version), No such file or directory
checking for dmd ... no
checkinfo: cannot runv(ldc2.exe --version), No such file or directory
checking for ldc2 ... no
checkinfo: cannot runv(gdc.exe --version), No such file or directory
checking for gdc ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(unzip.exe -v), No such file or directory
checking for unzip ... no
checking for 7z ... E:\Software\xmake\winenv\bin\7z
checking for git ... ok
checkinfo: cannot runv(gzip.exe --version), No such file or directory
checking for gzip ... no
git rev-parse HEAD
finding vulkansdk from xmake ..
checking for xmake::vulkansdk ... no
checking for cmake ... E:\Software\CMake\bin\cmake
checking for cmake ... E:\Software\CMake\bin\cmake
finding vulkan-headers from xmake ..
checking for xmake::vulkan-headers ... vulkan-headers 1.3.231+1
finding vk-bootstrap from xmake ..
checking for xmake::vk-bootstrap ... vk-bootstrap v0.5
finding boost from xmake ..
checking for xmake::boost ... boost 1.81.0
note: the following packages were not found on your system, try again after installing them:
  -> vulkansdk latest
error: @programdir\core\main.lua:280: stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:909]:
    [...modules\private\action\require\impl\install_packages.lua:739]:
    [@programdir\modules\private\action\require\install.lua:85]:
    [@programdir\plugins\project\vsxmake\getinfo.lua:494]:
    [@programdir\plugins\project\vsxmake\vsxmake.lua:224]: in function '?'
    [@programdir\plugins\project\main.lua:79]: in function '_make'
    [@programdir\plugins\project\main.lua:92]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\base\task.lua:501]: in function 'run'
    [@programdir\core\main.lua:278]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:404]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:898: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:280: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>

**Comment by waruqi** [comment]
直接 build 呢

```console
xmake f -c -vD
xmake -rvD
```

**Comment by waruqi** [comment]
> xmake f -c -vD找不到qt路径，xmake -f设置后依然无效

不要照搬，既然用了 qt，就追加指定下 --qt，然后再给份 logs

**Comment by xq114** [comment]
生成x86工程失败了，project -k vsxmake -a x64 就行

**Comment by waruqi** [comment]
> 但在使用add_requires("vulkansdk", {system = false})：xmake project -k vsxmake -vD -a x64时依然会失败，好像依然找不到xmake repo上vulkansdk的包：

vulkansdk 目前只是 find only 包，xmake-repo 里面没有安装脚本，只能找系统上用户安装的。。不要指定 system = false，直接 `add_requires("vulkansdk")` 或者 system = true 就行。

**Comment by waruqi** [comment]
另外，我改进了下，默认只生成当前 arch，可以减少一些失败率和包安装
