### ISSUE TITLE
add_defines("CCL_NAMESPACE_BEGIN=\"namespace ccl {\"") 和预期不符合

### ISSUE THREAD

**Issue by breakerrorchen** [xmake-io/xmake#3271]
### Xmake Version

xmake v2.7.2+HEAD.d881936

### Operating System Version and Architecture

mac

### Describe Bug

add_defines("CCL_NAMESPACE_BEGIN=\"namespace ccl {\"")
展开成了
#define CCL_NAMESPACE_BEGIN "namespace ccl {"

### Expected Behavior

add_defines("CCL_NAMESPACE_BEGIN=\"namespace ccl {\"")
展开成了
#define CCL_NAMESPACE_BEGIN namespace ccl {

**Comment by waruqi** [comment]
更新到 dev 再试试, xmake update -s dev

```lua
add_defines("CCL_NAMESPACE_BEGIN=namespace ccl {")
```
