### ISSUE TITLE
使用 compile_commands.json 时报错 Unknown argument: '-sdk'

### ISSUE THREAD

**Issue by Parallel-Paradox** [xmake-io/xmake#3286]
### Xmake 版本

xmake v2.7.5

### 操作系统版本和架构

macOS Ventura 13.1

### 描述问题

在 vscode 中使用 clangd 插件作为跳转环境, 使用 `xmake project -k compile_commands` 生成 compile_commands.json 文件后, 虽然不影响 build 和 run, 但 clangd 会在头文件开始处报错 Unknown argument: '-sdk'.

观察生成的 compile_commands.json 文件中部分表项:

```
{
  "directory": "...",
  "arguments": ["/usr/bin/xcrun", “-sdk”, "macosx" , "clang", "-c", ...],
  "file": "..."
},
```

将 arguments 中的 `"-sdk", "macosx"` 删除后报错提示消失.

### 期待的结果

生成 arguments 时是否不应有 “-sdk” 参数?

### 工程配置

[mvp.zip](https://github.com/xmake-io/xmake/files/10408487/mvp.zip)

### 附加信息和错误日志

![image](https://user-images.githubusercontent.com/81791934/212245453-7b2f9497-bee5-4141-b872-c5edd93c0943.png)

**Comment by waruqi** [comment]
maybe you should open an issue to clangd

**Comment by Parallel-Paradox** [comment]
I try to revert the arguments combination change in #3159 and this error disappear.

```
"arguments": ["/usr/bin/xcrun -sdk macosx clang",
```

Looks like there is a conflict between CLion and clangd.

**Comment by waruqi** [comment]
我改进了下，转成全路径了，再试试，xmake update -s dev
