### ISSUE TITLE
Multiple xmakes are installed, after updating 

### ISSUE THREAD

**Issue by yssource** [xmake-io/xmake#329]
1. `yaourt xmake`  2 xmakes installed

``` zsh
/usr/bin/xmake --version
xmake v2.2.3.201901122330, A cross-platform build utility based on Lua
```

``` zsh
/usr/share/xmake/xmake --version
xmake v2.2.3.201901122330, A cross-platform build utility based on Lua
```

2. `xmake update dev`   3 xmake are installed

``` zsh
/usr/bin/xmake --version
xmake v2.2.3.201901122330, A cross-platform build utility based on Lua
```

``` zsh
/usr/share/xmake/xmake --version
xmake v2.2.3.201901122330, A cross-platform build utility based on Lua
```

``` zsh
/usr/local/bin/xmake --version
xmake v2.2.3.201901122334, A cross-platform build utility based on Lua
```

3. `xmake update dev` re-running this command again, 4 xmake are installed
  
``` zsh
/usr/bin/xmake --version
xmake v2.2.3.201901122330, A cross-platform build utility based on Lua
```

``` zsh
/usr/share/xmake/xmake --version
xmake v2.2.3.201901122330, A cross-platform build utility based on Lua
```

``` zsh
/usr/local/bin/xmake --version
xmake v2.2.3.201901122334, A cross-platform build utility based on Lua
```

``` zsh
~/.local/bin/xmake --version
xmake v2.2.3.201901122339, A cross-platform build utility based on Lua # here v2.2.3.201901122339
```
-----
- I think it would be better that only one to be installed, no matter installing or upgrading, isn't it?

**Comment by waruqi** [comment]
> yaourt xmake 2 xmakes installed

Only one xmake is installed.  `/usr/bin/xmake` wrapper script -> `/usr/share/xmake/xmake` binary

> xmake update dev 3 xmake are installed

Maybe you used the old version of xmake before, run `xmake update dev` will install to `/usr/local/bin`

> xmake update dev re-running this command again, 4 xmake are installed

After updating xmake, run `xmake update dev` will install to ~/.local/bin/xmake.

So after the new version is released, there will only be two paths.

Arch linux:

`yaourt xmake` -> /usr/bin/xmake
`xmake update` -> run `./xmakesrc/script/get.sh __local__` -> ~/.local/bin/xmake

If we use a script to compile and install, it will be installed to ~/.local/bin/xmake, this is also the recommended way, does not require root privileges.

But some package management has its own specified installation directory restrictions, like homebrew, aur package,  so there will be different installation directory locations.

We can detect the existing installation directory and execute the script to install to the previous location.

However, if the processing is not good, it is easy to destroy the directory structure of other package management tools, so you need to carefully cover the xmake directory installed by other package management tools.

**Comment by waruqi** [comment]
This probloem will be resolved after the new version is released.
