### ISSUE TITLE
使用源码构建 cmake 包时, xmake install 不会拷贝 动态库文件

### ISSUE THREAD

**Issue by shenxin-karl** [xmake-io/xmake#3290]
### Xmake 版本

xmake v2.6.9+HEAD.22ecc0156, A cross-platform build utility based on Lua

### 操作系统版本和架构

版本	Windows 10 专业版 版本号	21H2 安装日期	‎2022/‎7/‎10 操作系统内部版本	19044.2130 体验	Windows Feature Experience Pack 120.2212.4180.0

### 描述问题

修改了 https://github.com/xmake-io/xmake/tree/master/tests/projects/c/library_with_cmakelists test 内的代码. 使其 cmake 生成动态库文件. 随后使用 xmake install -o res 的 bin 目录内只有一个 exe

cmakelists 修改为 share 格式
![image](https://user-images.githubusercontent.com/59679661/212488538-ac8bab52-94b8-4808-9e6c-d13647e39cb8.png)

foo.h foo.c main.c 中加入了 dll 导出的处理

![image](https://user-images.githubusercontent.com/59679661/212488570-8f1b23a1-b5d9-4daa-8fae-776c1c72075d.png)
![image](https://user-images.githubusercontent.com/59679661/212488582-c8f06fe2-653a-4281-81b2-5d45a19f1796.png)

### 期待的结果

能够正确的拷贝 dll

### 工程配置

[xmake_test.zip](https://github.com/xmake-io/xmake/files/10418509/xmake_test.zip)

**Comment by shenxin-karl** [comment]
我在 build/.packages 子目录内有找到 foo.dll 文件

**Comment by waruqi** [comment]
> 我在 build/.packages 子目录内有找到 foo.dll 文件

那就让它装上，这是 cmakelist.txt 的 install 脚本问题，你可以 google 研究下怎么在 cmake 里安装 dll
