### ISSUE TITLE
xmake run 加TAB补全不起作用

### ISSUE THREAD

**Issue by zt449569708** [xmake-io/xmake#3295]
### Xmake 版本

2.7.5

### 操作系统版本和架构

ubuntu 18.04

### 描述问题

![Image_20230116095034](https://user-images.githubusercontent.com/6011216/212582062-6ebcb7c6-052d-46fd-8a55-34b654b7dcda.png)
xmake脚本如上，当前有两个目标分别是aaaa和bbbb，当编译完成，打算运行aaaa的时候，通过xmake run aa加tab键去补全，发现无法完成补全，如下图：
![Image_20230116095344](https://user-images.githubusercontent.com/6011216/212582324-d6e254eb-0604-4cc3-be2b-ab7340102882.png)
只要通过tab去补全，就会把所有的目标列出来，无法完成补全功能。但是tab补全功能在2.7.5之前的版本是可以。

### 期待的结果

xmake run支持tab补全

**Comment by waruqi** [comment]
@glcraft any idea? it works for 2.7.4.  Maybe 2.7.5 broke something.

**Comment by waruqi** [comment]
I have fixed it on dev. `xmake update -s dev`

**Comment by zt449569708** [comment]
> I have fixed it on dev. `xmake update -s dev`

谢谢，验证OK

**Comment by glcraft** [comment]
Sorry I wasn't available yesterday. 

What was the problem ?
