### ISSUE TITLE
set_group bug in vsxmake

### ISSUE THREAD

**Issue by Extra-Creativity** [xmake-io/xmake#3303]
### Xmake Version

2.7.5

### Operating System Version and Architecture

Win10 22H2, x86_64

### Describe Bug

The minimal project that causes this bug has been uploaded to [my temporary repository](https://github.com/Extra-Creativity/TestCode).

In this project, `set_group` [here](https://github.com/Extra-Creativity/TestCode/blob/0fdf0e3374fa044be1fe32dae5e4e68585d8a77e/xmake.lua#L16) will:
+ cause incorrect groups in vscode.
+ trigger unexpected dump in project-generating command(i.e. `xmake project -a "x64" -k vsxmake -m "debug;release"`).

In the second problem, running with `-D` will prompt error information as :
```
checking for Microsoft Visual Studio (x64) version ... 2019
error: @programdir\core\main.lua:280: @programdir\plugins\project\vsxmake\getinfo.lua:294: attempt to index a nil value 
(field '?')
stack traceback:
    [@programdir\plugins\project\vsxmake\getinfo.lua:294]: in function '_make_vsinfo_groups'
    [@programdir\plugins\project\vsxmake\getinfo.lua:442]:  
    [@programdir\plugins\project\vsxmake\vsxmake.lua:224]: in function '?'
    [@programdir\plugins\project\main.lua:79]: in function '_make'
    [@programdir\plugins\project\main.lua:92]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\base\task.lua:501]: in function 'run' 
    [@programdir\core\main.lua:278]: in function 'cotask'   
    [@programdir\core\base\scheduler.lua:404]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:898: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:280: in upvalue 'cotask'  
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>
```

### Expected Behavior

+ VSCode will make `Test2` a subgroup of `Test`.
+ Visual Studio can be generated correctly.

**Comment by waruqi** [comment]
These are two questions, please refer to the vscode question, separately to https://github.com/xmake-io/xmake-vscode/issues

> cause incorrect groups in vscode.

**Comment by waruqi** [comment]
>     local relativeDir = string.sub(scriptDir, #projectDir + 2)

try

```lua
local relativeDir = path.relative(scriptDir, projectDir)
```

https://github.com/Extra-Creativity/TestCode/blob/0fdf0e3374fa044be1fe32dae5e4e68585d8a77e/xmake.lua#L12

**Comment by Extra-Creativity** [comment]
This change seems not to help?

**Comment by Extra-Creativity** [comment]
Two questions:
1. Why will this work but the other will not?
2. It seems that the groups are still incorrect, like this:
![image](https://user-images.githubusercontent.com/72960952/213065872-59e6ae45-bed2-42e9-a977-07b5173274b8.png)

**Comment by waruqi** [comment]
> Why will this work but the other will not?

> string.sub(scriptDir, #projectDir + 2)

If projectDir is the same as scriptDir (GlobalTest target), it will return the empty string.

I've improved it on the dev branch, but it's still an invalid group name and xmake/dev will still ignore the group, but at least it won't throw an exception error

> path.relative(scriptDir, projectDir)

it will return "."

**Comment by waruqi** [comment]
> It seems that the groups are still incorrect, like this:

It works for me.

![image](https://user-images.githubusercontent.com/151335/213070384-97f6c704-ed49-4264-a4d7-adf76f829709.png)

**Comment by Extra-Creativity** [comment]
Okay, works for me now when I omit the root directory, apologize for my carelessness.
