### ISSUE TITLE
无法正确链接catch2

### ISSUE THREAD

**Issue by dingjr27** [xmake-io/xmake#3312]
### Xmake 版本

2.7.5

### 操作系统版本和架构

5.13.0-52-generic #59~20.04.1-Ubuntu

### 描述问题

Catch2 需要链接两个库，一个是catch2本体，一个是catch2预先定义的main函数。如果需要自定义main函数，则不需要链接Catch2Main。
`package:add("links", "Catch2Main", "Catch2")`
然而xmake-repo中预先定义的就是全部链接，找不到只链接Catch2的方法。

### 期待的结果

提供只链接Catch2的方法。

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-repo/pull/1754
