### ISSUE TITLE
Xrepo remove package that are defined in xmake.lua

### ISSUE THREAD

**Issue by A2va** [xmake-io/xmake#3313]
### Is your feature request related to a problem? Please describe.

I have created a [sample package](https://github.com/A2va/libsample) and I use it in this project:

```lua
package("libsample")
	set_description("Sample library")
	set_homepage("https://github.com/A2va/libsample")
    add_urls("https://github.com/A2va/libsample.git")
    add_versions("v0.1", "b9a9f87ede22330b5b81bc6cec99babc27cdd307")

    on_install(function (package)
        import("package.tools.xmake").install(package, {})
    end)
package_end()

add_requires("libsample")
target("sample")
    add_files("main.cpp")
    add_packages("libsample")
```

```cpp
#include <iostream>

#include "lib.h"

int main() {
    std::cout << "Hello " << getWorld();    
}
```

If I want to remove this package with `xmake remove libsample` it will fail and display this message:
```
error: package(libsample) not found!
error: execv(xmake require --info --extra={system=false} libsample) failed(-1)
```

### Describe the solution you'd like

Uninstalling a package like this is not very convenient because I have to remove it manually. It could be nice to add this ability as well displaying information about the package.

`xrepo remove libsample` would remove the `libsample` package
`xrepo info libsample` would display information about the `libsample` package

**Comment by waruqi** [comment]
try `xmake require --uninstall libsample` or `xrepo remove --all libsample`

**Comment by A2va** [comment]
Ok, the two of them works, but I find it strange because `xrepo remove libsample` try to run `xmake require --uninstall ...` and this one worked when I run it myself.

So, I investigate a little more.

https://github.com/xmake-io/xmake/blob/535529d5e08cf8fc0f2d624508c4ef145bce12c3/xmake/modules/private/xrepo/action/remove.lua#L187

I changed this line to: `os.vrunv("xmake", require_argv, {curdir = os.projectdir()})`.

With this change, it works to remove libsample (and unlike `xrepo remove --all` the folder containing the version is not removed), but strangely there is no yes/no prompt before.

**Comment by waruqi** [comment]
xrepo remove is a standalone package management command that is not tied to the current project configuration.

So you can only use `xrepo remove --all` to remove all configured libsample packages. You can't get xrepo to remove it unless you can configure them exactly, `xrepo remove -p linux -m release -k shared/static -f "other configs ..." `

And `xmake require --uninstall` will go and load the current project's cached configuration to remove the libsample package under the current project configuration.

Translated with www.DeepL.com/Translator (free version)

**Comment by A2va** [comment]
Thank you, I didn't know this difference existed.
