### ISSUE TITLE
Creating xmake "Build Helper" for Conan - FYI

### ISSUE THREAD

**Issue by solvingj** [xmake-io/xmake#332]
I haven't started work yet, but I wanted to mention that there is one more conan-related project for XMake I want to do which is called a "Build Helper". 

https://docs.conan.io/en/latest/reference/build_helpers.html

The documentation for the CMake helper provides the justification here: 

https://docs.conan.io/en/latest/reference/build_helpers/cmake.html

In summary, helpers make the Conan recipe's cleaner (easier to write, easier to follow, less error-prone string formatting, concatenation, and manipulation).  

Another great part is that a new `xmake_build_helper` can be created, shared as a package, and tested easily now before being submitting to Conan to be included as a built-in feature request.

**Comment by waruqi** [comment]
Well, after the integration is complete, I will take some time to write the help documentation, but since my English is not very good, when I have finished writing, I hope you can help to improve the grammar together

**Comment by solvingj** [comment]
Sure thing!

**Comment by waruqi** [comment]
https://github.com/conan-io/docs/pull/1851

**Comment by waruqi** [comment]
Now the help documentation for xmake has been added to the conan documentation.

https://docs.conan.io/en/latest/integrations/build_system/xmake.html
