### ISSUE TITLE
Add `xmake check` to diagnose some errors in xmake.lua

### ISSUE THREAD

**Issue by star-hengxing** [xmake-io/xmake#3320]
### 你在什么场景下需要该功能？

用户有小概率在`add_packages`的时候，把包名写错，然后编译失败，找了很久 bug 都不知道在哪。应该提供一个检查的功能

### 描述可能的解决方案

自己实现了一段简单的代码，不知道应该塞在 xmake 哪个功能里，插件/策略/规则？
```lua
import("core.project.project")

function main()
    local requires = table.wrap(project.get("requires"))
    for targetname, target in pairs(project.targets()) do
        local packages = table.wrap(target:get("packages"))
        for _, package in pairs(packages) do
            if not table.contains(requires, package) then
                wprint("Unknown package: " .. package)
            end
        end
    end
end
```

**Comment by waruqi** [comment]
暂时不考虑，没 add_requires 仅仅加 add_packages ，目前也是常规操作，用于简化对 option 条件处理

只需要 has_config 条件判断处理 add_requires 就能开启一些 package ，否则每个 target 的 add_packages 都得重复来遍 if has_config

现在只需要这样，就可以条件控制包的开启：

```lua
if has_config("with_zlib") then
    add_requires("zlib")
end

if has_config("with_libpng") then
    add_requires("libpng")
end

target("test")
   -- ...
   add_packages("zlib", "libpng")

target("test2")
   -- ...
   add_packages("zlib")

```

否则就得变成这样：


```lua
if has_config("with_zlib") then
    add_requires("zlib")
end

if has_config("with_libpng") then
    add_requires("libpng")
end

target("test")
   -- ...
   if has_config("with_zlib") then
       add_packages("zlib")
   end
   if has_config("with_libpng") then
       add_packages("libpng")
   end

target("test2")
   -- ...
   if has_config("with_zlib") then
       add_packages("zlib")
   end
```

包越多越繁琐，如果不理 warning ，每次编译 warning 也得刷屏。

**Comment by star-hengxing** [comment]
`xmake check`插件应该是 best practice 了，我先随便写个看看

**Comment by waruqi** [comment]
这样可以把各种复杂的检测逻辑，抽离到单独的 xmake check 里面维护，不影响正常逻辑的代码实现，也方便维护。

而且可以将各种诊断分类，定义检测级别，类似 warning level 

1. 默认开启一些常规检测 `xmake check`
2. 也可以强制全开所有检测 `xmake check --all`
3. 也可以指定检测某组特性，比如跟包有关的特性错误， `xmake check package.*`
4. 指定检测单个 API 传值错误等等，`xmake check api.add_packages`, `xmake check api.set_languages`

**Comment by waruqi** [comment]
clang tidy 这个，回头我也会一并整进去

https://github.com/xmake-io/xmake/issues/1367

```
xmake check --clang-tidy
```

**Comment by waruqi** [comment]
具体看下这里，目前实现了 set_languages/add_packages 检测

https://github.com/xmake-io/xmake/issues/3326

**Comment by waruqi** [comment]
这里先关了，回头有问题到 #3326 上跟进。
