### ISSUE TITLE
临时文件路径和日期相关导致每天必然会重新编译

### ISSUE THREAD

**Issue by q962** [xmake-io/xmake#3321]
### Xmake 版本

2.7.6

### 操作系统版本和架构

Linux fedora 6.1.6-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jan 14 16:55:06 UTC 2023 x86_64 GNU/Linux

### 描述问题

```
$ cat /home/demo/project/demo/xmake_build_test/a/.xmake/linux/x86_64/tmp/230206/_E2BB99FB47614
29EB2F157B92513DE30                                                                           
{                                                                                             
    files = {                                                                                 
        "src/config.h.in"                                                                     
    }                                                                                         
}%                                                                                            
```
记录了依赖文件，但是修改时间后（过了一天）
```
dependfile: /home/demo/project/demo/xmake_build_test/a/.xmake/linux/x86_64/tmp/230207/_E2BB99F
B4761429EB2F157B92513DE30                                                                     
dependinfo { }                                                                                
```
可见，将要读取的临时文件并不存在，因为路径拼接根据时间而发生了变化。

https://github.com/xmake-io/xmake/blob/f3b7dad8768679df499b36d635532f81f3c5063a/xmake/core/project/project.lua#L1159
https://github.com/xmake-io/xmake/blob/f3b7dad8768679df499b36d635532f81f3c5063a/xmake/core/project/project.lua#L1183

dependinfo 会被传递到这里

https://github.com/xmake-io/xmake/blob/f3b7dad8768679df499b36d635532f81f3c5063a/xmake/modules/core/project/depend.lua#L188-L193
https://github.com/xmake-io/xmake/blob/f3b7dad8768679df499b36d635532f81f3c5063a/xmake/modules/core/project/depend.lua#L85-L90

### 期待的结果

移除日期？

**Comment by waruqi** [comment]
日期是不能移的，tmpdir 设置按天分离，便于定期清理，每天首次运行 后台进程会清理一次前天的临时文件，避免磁盘空间越占越多。。

根本问题是 depend.on_changed 在 configfiles 生成里面，我没加 dependfile 设置，所以默认用了 tmpfile 作为 dependfile 

https://github.com/xmake-io/xmake/blob/c7b76a4dcc9f1938cef673b5a69a368adb7f8905/xmake/modules/core/project/depend.lua#L179

只要外面设置上固定 dependfile 路径，避免走到 tmpfile 就行了。。

我改进了下，再试试，`xmake update -s dev`

**Comment by q962** [comment]
使用修改时间的方式验证，已经没有重新编译的问题了。
