### ISSUE TITLE
set_toolchains 在 xmake.lua 中不生效 （或者请帮我理解 xmake.lua 和 xmake f 的关系）

### ISSUE THREAD

**Issue by drcxd** [xmake-io/xmake#3325]
### Xmake 版本

2.7.6

### 操作系统版本和架构

Win10 20H2 19042.2364

### 描述问题

```
xmake create xmake-test
```
修改 xmake.lua 为以下内容：
```
add_rules("mode.debug", "mode.release")

target("xmake_test")
    set_kind("binary")
    add_files("src/*.cpp")
    set_toolchains("gcc")
    add_rules("mode.debug")
```
运行
```
xmake f -c
xmake
```
输出
```
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.31.31105
```
程序是使用 msvc 编译的 release 版本，我理解成 xmake.lua 中对该目标的配置未生效？

如果在命令行使用命令：

```
xmake f -c
xmake f --toolchains=gcc --mode=debug
xmake
```

则程序是使用 gcc 编译的 debug 版本

我读过官方文档，但并没有找到相关的解释。

### 期待的结果

如果上面的表现是正常的，希望能说明清楚：
1. xmake.lua 和 `xmake f` 对工程配置的影响分别是什么？
2. 哪些内容应该在 xmake.lua 中配置，哪些内容该用 `xmake f` 配置？如果二者有冲突，谁的优先级更高？
3. 每次执行 `xmake f`, 是否使用 xmake.lua 的内容？

**Comment by star-hengxing** [comment]
- 从命令行输入的 config 优先级应该是最高的
- 如果可以用多个工具链编译，我认为不应该在项目里使用 set_toolchains，这有点像是 hardcode

**Comment by waruqi** [comment]
> checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.31.31105

不要看到这个输出，就以为没生效，这个是全局工具链检测，跟 set_toolchains 没关系。。

你通过 set_toolchains 对 n 个 targets 设置不同的 toolchains，全局检测的工具链还是 msvc ，因为你没切平台，当前平台还是 windows，这个默认走的 msvc

但这并不影响你用 set_toolchains 对特定 targets 切到其他工具链，你设置了 gcc toolchains ，当前这个 targets 自然就用了  gcc 

不要去管上面那个输出，那个全局的平台工具链，就不会被用到了。。

你要看 `xmake -rv` 实际编译命令，来确认是不是真用了 gcc。。

你可以贴下 `xmake -rv` 的 logs 看下

**Comment by drcxd** [comment]
> 你要看 `xmake -rv` 实际编译命令，来确认是不是真用了 gcc。。

确实是使用了 gcc

还有个小问题：有没有办法在 xmake.lua 中对 target 指定编译的模式 (debug or realease)?

**Comment by waruqi** [comment]
> > 你要看 `xmake -rv` 实际编译命令，来确认是不是真用了 gcc。。
> 
> 确实是使用了 gcc
> 
> 还有个小问题：有没有办法在 xmake.lua 中对 target 指定编译的模式 (debug or realease)?

https://xmake.io/#/manual/global_interfaces?id=set_defaultmode

**Comment by drcxd** [comment]
这个只能全局，不能按 target 指定。

**Comment by waruqi** [comment]
mode 只能全局一个值，但你可以针对的不同 target ，自己 配置各种设置，不走 mode
