### ISSUE TITLE
Can't compile module units to static library

### ISSUE THREAD

**Issue by ChuanqiXu9** [xmake-io/xmake#3328]
### Xmake Version

master

### Operating System Version and Architecture

linux

### Describe Bug

For the project:

```
//--- Hello.cppm
export module X;
export int foo() { return 43; }

//--- xmake.lua
add_rules("mode.debug", "mode.release")

target("hello")
	set_kind("static")
	add_files("Hello.cppm")
	set_languages("c++20")
```

And I run `xmake`, it tells me:

```
$xmake
error: unknown source file: Hello.cppm
```

It works fine if I add a file ended with `.cpp` in `add_files`

### Expected Behavior

Compile it to static library

**Comment by Qudix** [comment]
You must have one `.cpp` file as well.

**Comment by ChuanqiXu9** [comment]
This is incorrect since a module unit a compilation unit too.

**Comment by waruqi** [comment]
If there is no cpp file, xmake will not recognise the current target as a c++ project. You can add an empty c++ file, or you can configure `add_rules("c++")` to let xmake know that it is a c++ target.

```lua
add_rules("mode.debug", "mode.release")

target("hello")
	set_kind("static")
        add_rules("c++")
	add_files("Hello.cppm")
	set_languages("c++20")
```

**Comment by ChuanqiXu9** [comment]
> 

Thanks. Or this may be a feature request. It makes a lot of sense to recognize .cppm, .ixx, .mpp (and anything else) as c++ sources.

**Comment by waruqi** [comment]
> > 
> 
> Thanks. Or this may be a feature request. It makes a lot of sense to recognize .cppm, .ixx, .mpp (and anything else) as c++ sources.

I will improve it later.

**Comment by waruqi** [comment]
I have improved it. https://github.com/xmake-io/xmake/pull/3330

you can update to dev version and try it again.

```console
xmake update -s dev
```
