### ISSUE TITLE
error: package(nvtx) not found!

### ISSUE THREAD

**Issue by xiaomi2077** [xmake-io/xmake#3329]
### Xmake 版本

xmake v2.7.6+HEAD.f00d2ed,

### 操作系统版本和架构

Linux  5.15.0-58-generic #64~20.04.1-Ubuntu SMP Fri Jan 6 16:42:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

安装libtorch，让支持cuda=true。
`add_requires("libtorch",{configs={cuda=true}})`，编译报错`error: package(nvtx) not found!`  
如下截图：
![图片](https://user-images.githubusercontent.com/33375652/216609024-530fa331-2ce7-4497-bcb4-174d9e70d67b.png)

xmake.lua如下截图：
![图片](https://user-images.githubusercontent.com/33375652/216609221-1a4e1410-db66-4b0e-8a59-8d673438cfa8.png)

https://github.com/xmake-io/xmake/issues/1267 这个issue也有相同的问题，但是是for windows的。
在 `find_nvtx.lua`文件里下面这部分代码是在linux平台找nvtx   https://github.com/xmake-io/xmake/blob/c2387f757d6ad0b4cfc42841920a4b38ba1cc1e0/xmake/modules/detect/packages/find_nvtx.lua#L63-L79

不知道是不是这部分的问题

### 期待的结果

找到package nvtx，正常编译libtorch，且支持cuda

### 工程配置

```
set_project("RobotArmSys")
set_languages("cxx17")
add_rules("mode.debug","mode.release")


add_requires("opencv","fmt")
add_requires("libtorch",{configs={cuda=true}})
add_requires("apt::librealsense2-dev")

target("test_load_model")
    set_kind("binary")
    add_files("tmp/test_load_model.cpp")
    add_packages("libtorch")
```

### 附加信息和错误日志

```
checking for gcc ... /usr/bin/gcc
checking for dmd ... no
checking for ldc2 ... no
checking for gdc ... no
checking for zig ... no
checking for zig ... no
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
/usr/bin/git rev-parse HEAD
checking for gcc ... /usr/bin/gcc
checking for the c compiler (cc) ... gcc
checking for gcc ... /usr/bin/gcc
checking for the c++ compiler (cxx) ... gcc
checking for Cuda SDK directory ... /usr/local/cuda
error: package(nvtx) not found!
```

**Comment by waruqi** [comment]
目前 nvtx 这个没收录到包仓库里，需要自己装，可以确认下装了没有。。

@xq114 这个是不是也可以放进包里？https://github.com/NVIDIA/NVTX

**Comment by xiaomi2077** [comment]
nvtx仓库说cuda toolkit默认带
![图片](https://user-images.githubusercontent.com/33375652/216627132-97155127-91d0-40c9-bf8b-aa71c3539d94.png)

而且也在我电脑上找到了`nvToolsExt.h`头文件。应该是装了nvtx
![图片](https://user-images.githubusercontent.com/33375652/216627204-0e95a6ed-3d10-4511-87b8-b6b01bee51e5.png)

**Comment by waruqi** [comment]
有库文件么？

https://github.com/xmake-io/xmake/blob/c2387f757d6ad0b4cfc42841920a4b38ba1cc1e0/xmake/modules/detect/packages/find_nvtx.lua#L69

这里是去找了库的，至少得有个 .a/.so 库才行，仅仅头文件也会找不到。。

**Comment by xiaomi2077** [comment]
![图片](https://user-images.githubusercontent.com/33375652/216628955-d9af2b7b-6f54-4299-bf85-da739e881edd.png)
有，路径是`/usr/local/cuda/lib64/libnvToolsExt.so`

**Comment by waruqi** [comment]
你可以加点 print 调下这里 https://github.com/xmake-io/xmake/blob/c2387f757d6ad0b4cfc42841920a4b38ba1cc1e0/xmake/modules/detect/packages/find_nvtx.lua#L69

比如看下 cuda.linkdirs 的路径是不是 /usr/local/cuda/lib64/

看下 find_library 为什么没找到

**Comment by xiaomi2077** [comment]
在`xmake/modules/detect/sdks/find_cuda.lua`中调试输出cacheinfo，
调试代码如下（高亮部分）：
![图片](https://user-images.githubusercontent.com/33375652/216639441-5bca57b2-0ead-4bc4-99f4-70945f609eee.png)

调试输出如下：
![图片](https://user-images.githubusercontent.com/33375652/216639267-c8beb7dd-5ad3-427a-b500-d0ce92584e4b.png)
从结果来看是，cuda.linkdirs有路径/usr/local/cuda/lib64。

***但是find_cuda.lua好像没有调用find_nvtx.lua***。在find_nvtx.lua的开始处添加进入调试，没有调用`find_nvtx.lua`的输出
调试代码如下：（高亮部分）
![图片](https://user-images.githubusercontent.com/33375652/216639933-86f24e0a-b32b-4363-beb5-c46f126477dc.png)

**Comment by waruqi** [comment]
得 `xmake f -c` 强制清下缓存，触发查找试试

另外，我把 nvtx 挪到 xmake-repo 里面去了。 https://github.com/xmake-io/xmake-repo/pull/1781

你更新下仓库，然后调下本地仓库的 https://github.com/xmake-io/xmake-repo/blob/master/packages/n/nvtx/fetch.lua 脚本，在 `~/.xmake/repositories/xmake-repo` 里面

```console
xrepo update-repo
xmake f -c
xmake
```

**Comment by xiaomi2077** [comment]
可以了。找到nvtx 了。谢谢
