### ISSUE TITLE
`package:dep("python"):version()` returns incorrect version when fetching from system

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#3333]
### Xmake 版本

2.7.6

### 操作系统版本和架构

Ubuntu 22.04

### 描述问题

在编写包描述文件时，`package:dep("python"):version()` 无法正确返回从系统fetch得到的python版本，而是返回仓库里python的最新版本，要获取系统python版本则需要 `package:dep("python"):fetch().version`，而且获取的还是字符串必须parse一遍才成为semver变量，这就造成了系统包和仓库包的不一致。

### 期待的结果

`package:dep("python"):version()` 可以返回正确的系统python版本（即  `package:dep("python"):fetch().version`）

### 附加信息和错误日志

https://github.com/xmake-io/xmake-repo/pull/1784

**Comment by waruqi** [comment]
这个改不了，package:version() 目前就是包定义里面选择的版本，加载时候就决定好的，那个时候 package fetch 都还没执行。。

要用系统版本，只能走 fetch() 里面返回的 version 值，这个是一致的，即使找的是仓库包，也是一样可以用 fetch.version

**Comment by xq114** [comment]
但fetch.version是普通字符串，要处理还需要手动parse，写起来比较容易出错。能否提供一个类似`package:fetch_version()`的api，自动调用 package:fetch() ？

**Comment by waruqi** [comment]
改过了，如果 fetch 到的系统库，会自动更新下 package:version()
