### ISSUE TITLE
无法使用apr静态库

### ISSUE THREAD

**Issue by CKCat** [xmake-io/xmake#3339]
### Xmake 版本

2.7.6

### 操作系统版本和架构

Window 10

### 描述问题

编译成功，但是运行出错，提示缺少apr动态库。
![image](https://user-images.githubusercontent.com/18586344/217154099-76c69942-2b30-456c-9ca8-5908c6071782.png)

### 期待的结果

使用静态库编译。

### 工程配置

测试代码：
```c++
#include <iostream>
#include <apr_general.h>
using namespace std;

int main(int argc, char** argv)
{
    // Initialization
    ::apr_initialize();

    cout << "hello world!" << endl;
    ::apr_terminate();
    return 0;
}
```

xmake.lua 
```
add_rules("mode.debug", "mode.release")

add_requires("apr 1.7.0")

target("testapr")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("apr")
```

### 附加信息和错误日志

$ xmake -rvD                                
[ 25%]: cache compiling.release src\main.cpp
"E:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" -c -nologo -O2 -fp:fast /EHsc -external:W0 -external:IC:\Users\CKCat\AppData\Local\.xmake\packages\a\apr\1.7.0\144e7934b80e43c2aa506368d758520a\include -DNDEBUG -Fobuild\.objs\testapr\windows\x64\release\src\main.cpp.obj src\main.cpp
[ 50%]: linking.release testapr.exe
"E:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe"
-nologo -dynamicbase -nxcompat -machine:x64 -libpath:C:\Users\CKCat\AppData\Local\.xmake\packages\a\apr\1.7.0\144e7934b80e43c2aa506368d758520a\lib /opt:ref /opt:icf apr-1.lib aprapp-1.lib libapr-1.lib libaprapp-1.lib -out:build\windows\x64\release\testapr.exe
build\.objs\testapr\windows\x64\release\src\main.cpp.obj

build cache stats:
cache directory: build\.build_cache
cache hit rate: 0%
cache hit: 0
cache miss: 1
new cached files: 1
remote cache hit: 0
remote new cached files: 0
preprocess failed: 0
compile fallback count: 0

**Comment by waruqi** [comment]
双击运行的，还是 `xmake run` 运行的？

**Comment by CKCat** [comment]
> 

xmake run 运行出现错误：
 $ xmake run
error: execv(E:\Study\testapr\build\windows\x64\release\testapr.exe ) failed(-1073741515)

**Comment by waruqi** [comment]
C:\Users\CKCat\AppData\Local.xmake\packages\a\apr\1.7.0\144e7934b80e43c2aa506368d758520a\bin 看下这个目录下 有哪些dll文件，列下。

**Comment by CKCat** [comment]
> 
这个文件夹下是空的。
![image](https://user-images.githubusercontent.com/18586344/217156502-6a161769-6a23-402e-b36e-71a586c61278.png)

**Comment by waruqi** [comment]
等下这个 patch https://github.com/xmake-io/xmake-repo/pull/1795

**Comment by waruqi** [comment]
再试下。需要更新仓库，重装下 apr 包

```
xrepo update-repo
xrepo remove --all apr
xmake f -c
xmake
```

**Comment by CKCat** [comment]
> 
按你的步骤试了一下，还是同样的错误。
![image](https://user-images.githubusercontent.com/18586344/217176756-593a63c5-f736-4d28-8c95-f5586c4ca785.png)

看了一下cache,也是最新的。
![image](https://user-images.githubusercontent.com/18586344/217178417-e0e0c493-c21d-4cbb-a8d0-b5740e206219.png)

**Comment by waruqi** [comment]
现在应该是纯静态库，应该不会的，删下 build 目录，然后 `xmake -r` rebuild 试试，或者自己先自己分析下这个包。。确认下产物是不是纯 static 库了。

**Comment by waruqi** [comment]
> 再试下。需要更新仓库，重装下 apr 包
> 
> ```
> xrepo update-repo
> xrepo remove --all apr
> xmake f -c
> xmake
> ```

刚又更新了下，重新按上面的步骤，重装下库后 试试。

**Comment by waruqi** [comment]
可以了么

**Comment by CKCat** [comment]
> 可以了么
编译报错，符号错误，我怀疑是C++名称粉碎的原因，暂时没有时间去分析，主要是学习用这个库，所以先用动态库代替了，后续有时间了再看看什么原因。
$ xmake
[ 50%]: linking.release testapr.exe
error: main.cpp.obj : error LNK2019: 无法解析的外部符号 __imp__apr_initialize@0，函数 _main 中引用了该符号
main.cpp.obj : error LNK2019: 无法解析的外部符号 __imp__apr_terminate，函数 _main 中引用了该符号
build\windows\x86\release\testapr.exe : fatal error LNK1120: 2 个无法解析的外部命令

**Comment by CKCat** [comment]
> 可以 xmake -v 看下 links flags
> 
> 之前是因为安装的包，static/shared 两个类型的库都装进去了，导致实际link的 dll 版本的，但是由于 static ，所以 dll 被删了导致。。
> 
> 现在完全走 static 了，link 应该对了，缺符号可以排查下 link

我把文件改为.c就可以编译成功了，因该是库的问题，没有对C++做处理

**Comment by CKCat** [comment]
把xmake 文件添加了一个宏就可以编译通过了。
add_requires("apr 1.7.0")
add_defines("__cplusplus")
target("testapr")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("apr")

**Comment by waruqi** [comment]
__cplusplus 是 c++ 编译器的内置宏，你不加，编译 cpp 文件，也是自动定义的。

**Comment by CKCat** [comment]
> __cplusplus 是 c++ 编译器的内置宏，你不加，编译 cpp 文件，也是自动定义的。跟这个应该没关系

嗯，xmake f -c xmake 编译了一下，还是同样的错误，估计是缓存导致编译成功了，文件改为.c就可以，.cpp就会出现下面的错误
$ xmake
[ 25%]: cache compiling.release src\main.cpp
[ 50%]: linking.release testapr.exe
error: main.cpp.obj : error LNK2019: 无法解析的外部符号 __imp_apr_initialize，函数 main 中引用了该符号
main.cpp.obj : error LNK2019: 无法解析的外部符号 __imp_apr_terminate，函数 main 中引用了该符号
build\windows\x64\release\testapr.exe : fatal error LNK1120: 2 个无法解析的外部命令

现在先使用动态库学习一下吧，后续再看看到底怎么回事。

**Comment by waruqi** [comment]
你再更新下试试 应该可以了，我修复了

**Comment by CKCat** [comment]
> 你再更新下试试 应该可以了，我修复了

OK，编译运行都没有问题了。

**Comment by waruqi** [comment]
> > 你再更新下试试 应该可以了，我修复了
> 
> OK，Windows下编译运行（xmake run 和 直接运行）都没有问题了。linux下 xmake run 可以运行，直接应用则缺少动态库： error while loading shared libraries: libapr-1.so.0: cannot open shared object file: No such file or directory

xmake run 会自动绑定环境，自己运行，你得自己设置 LD_LIBRARY_PATH 或者 xmake install -o xxx 走安装，导出依赖的so
