### ISSUE TITLE
Improve to configure working and build directories

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#3342]
xmake will support two ways of configuring working directory.

#### Working directory

The current working directory where xmake is running, and it is also the directory where the project cache configuration .xmake is stored.

```
- workdir
  - .xmake
  - build
```

#### Build directory (-o/--buildir)

Build the output directory of the build artifacts.

```
build
└── macosx
    └── x86_64
        └── release
            ├── demo
```

#### Project directory (-P/--project)

The root directory of the project's source code, which is also the directory containing the root xmake.lua file.

```
- projectdir
  - xmake.lua
```

### Internal working directory mode (default)

This is the behaviour of the existing version, which has never changed.

#### The working directory is the project root directory by default.

```
- projectdir (workdir)
  - build (generated)
  - .xmake (generated)
  - src
  - xmake.lua
```

```console
$ cd projectdir
$ xmake
```

#### Set the other build directory outside the working directory

we can set the given build directory, but the working directory is still the project root directory.

```
- projectdir (workdir)
  - .xmake (generated)
  - src
  - xmake.lua
- build
```

```console
$ cd projectdir
$ xmake f -o ../build
```

### External working directory mode (new)

We can use `-P projectdir` to set the given project directory and it will enable external working directory mode.

Lock the current directory as the working directory, and xmake will cache the specified project directory.

#### The working directory is the current directory by default.

```
- workdir
  - build (generated)
  - .xmake (generated)
- projectdir
  - src 
  - xmake.lua
```

```console
$ cd workdir
$ xmake f -P ../projectdir
$ xmake
```

#### Set the other build directory outside the working directory

```
- build (generated)
- workdir
  - .xmake (generated)
- projectdir
  - src 
  - xmake.lua
```

```console
$ cd workdir
$ xmake f -o ../build
```

**Comment by waruqi** [comment]
```
$ xmake update -s github:xmake-io/xmake#config
$ cd workdir
$ xmake f -P ../projectdir
$ xmake
$ xmake run
...
```

**Comment by waruqi** [comment]
@davidchisnall you can try it, I have merged into dev branch.

**Comment by davidxiaozhi** [comment]
帮忙测试验证
 xmake.lua 存在且能执行 xmake 构建
![image](https://user-images.githubusercontent.com/6194818/217593541-128d5cae-73ee-4e89-849f-c11a9741784f.png)

更新 xmake 之后执行 xmake f -P ../projectdir 提示重新生成 xmake.lua
![image](https://user-images.githubusercontent.com/6194818/217593351-a0929717-b6de-417d-93b8-de31be15d3d1.png)
