### ISSUE TITLE
winegcc wineg++ 不支持？

### ISSUE THREAD

**Issue by dapeng17951** [xmake-io/xmake#3343]
### Xmake Version

2.7.6

### Operating System Version and Architecture

manjaro-cinnamon-22.0-230104-linux61

### Describe Bug

自定义的编译器，使用winegcc，wineg++
```lua
add_rules("mode.debug", "mode.release")
toolchain("myclang")
    set_kind("standalone")
    set_bindir("/usr/bin")
    set_toolset("cxx", "winegcc", "wineg++")
toolchain_end()

target("hellocpp")
    set_kind("binary")
    add_files("src/*.cpp")
    set_toolchains("myclang")
````
提示：
error: cannot find known tool script for /usr/bin/winegcc

系统：
manjaro，已安装wine，/usr/bin已具备winegcc wineg++

main.cpp内容

```c++
#include <iostream>

using namespace std;

int main(int argc, char** argv)
{
    cout << "hello world!" << endl;
    return 0;
}
```

### Expected Behavior

自定义工具链，指定winegcc wineg++ 编译器，在linux上编译适用与wine的windows应用。

### Project Configuration

```lua
add_rules("mode.debug", "mode.release")
toolchain("myclang")
    set_kind("standalone")
    set_bindir("/usr/bin")
    set_toolset("cxx", "winegcc", "wineg++")
toolchain_end()

target("hellocpp")
    set_kind("binary")
    add_files("src/*.cpp")
    set_toolchains("myclang")
```

### Additional Information and Error Logs

[xkp@xkp-aspiree1471g hellocpp]$ xmake
checking for platform ... linux
checking for architecture ... x86_64
error: cannot find known tool script for /usr/bin/winegcc

**Comment by waruqi** [comment]
改成 "gcc@winegcc" "gxx@wineg++" 试下，强制作为 gcc 来使用

**Comment by dapeng17951** [comment]
在xmake中做了修改
```lua
add_rules("mode.debug", "mode.release")
toolchain("myclang")
    set_kind("standalone")
    set_bindir("/usr/bin")
    set_toolset("cxx", "gcc@winegcc", "g++@wineg++")
toolchain_end()

target("hellocpp")
    set_kind("binary")
    add_files("src/*.cpp")
    set_toolchains("myclang")
```
可以正常编译，但编译结果不是想要的。
xmake编译结果为<mark>hellocpp</mark>，并非想要的。

使用wineg++编译
```cmd
wineg++ -o a ./src/main.cpp
```
编译结果：
> a.exe
> a.exe.so
![image](https://user-images.githubusercontent.com/39858062/217552613-d67789ac-50f7-4551-af6e-6a28204decc7.png)

**Comment by waruqi** [comment]
> 在xmake中做了修改
> 
> ```lua
> add_rules("mode.debug", "mode.release")
> toolchain("myclang")
>     set_kind("standalone")
>     set_bindir("/usr/bin")
>     set_toolset("cxx", "gcc@winegcc", "g++@wineg++")
> toolchain_end()
> 
> target("hellocpp")
>     set_kind("binary")
>     add_files("src/*.cpp")
>     set_toolchains("myclang")
> ```
> 
> 可以正常编译，但编译结果不是想要的。 xmake编译结果为hellocpp，并非想要的。
> 
> 使用wineg++编译
> 
> ```batchfile
> wineg++ -o a ./src/main.cpp
> ```
> 
> 编译结果：
> 
> > a.exe
> > a.exe.so
> > ![image](https://user-images.githubusercontent.com/39858062/217552613-d67789ac-50f7-4551-af6e-6a28204decc7.png)

你在 linux 上，默认走的是 linux 平台，当然扩展按 linux binary 走。你没告诉 xmake 要生成 window binary ，xmake 不可能猜出来。。

自己 set_extension(".exe") 改下

**Comment by dapeng17951** [comment]
非常感谢！完美解决！
