### ISSUE TITLE
Redirecting the output of batchcmds::vrunv works only with -v

### ISSUE THREAD

**Issue by davidchisnall** [xmake-io/xmake#3353]
### Xmake Version

v2.7.6+dev.c34ac1c69

### Operating System Version and Architecture

FreeBSD and Ubuntu, x86-64, multiple versions.

### Describe Bug

Annoyingly, `llvm-objdump` always outputs to stdout and so we have to redirect the output to a file.  We do this with [the following line](https://github.com/microsoft/cheriot-rtos/blob/069456aa90b828208f2c7c973a6280e950c39cd7/sdk/xmake.lua#L457):

```lua
		batchcmds:vrunv(target:tool("objdump"), {"-glxsdrS", target:targetfile()}, table.join(opt, {stdout = target:targetfile() .. ".dump"}))
```

Running `xmake` does not generate the `.dump` file, though it does report that it is running the tool.  Running `xmake -v` does.

### Expected Behavior

The command output would be redirected in both verbose and non-verbose builds.

### Project Configuration

Building in a clone of this directory will show the behaviour:

https://github.com/microsoft/cheriot-rtos/tree/main/tests

**Comment by waruqi** [comment]
if you want to redirect output, you should use `batchcmds:vexecv`

**Comment by davidchisnall** [comment]
That does appear to fix it.  Neither command is documented so I don't understand when to use either.  I am also apparently doing something wrong because the outputs are not tracked and so if I delete either the firmware image or the .dump file and rerun `xmake` neither is recreated.

**Comment by waruqi** [comment]
Yes, the documentation is incomplete at the moment as I have very little free time and some interfaces have not had time to be added to the documentation, I will take the time to continue to improve the documentation later.

Also here is some documentation for os.execv and os.runv, although it is not complete, it can be consulted.

https://xmake.io/#/manual/builtin_modules?id=osexecv
