### ISSUE TITLE
Failed to compile module units to dynamic library

### ISSUE THREAD

**Issue by ChuanqiXu9** [xmake-io/xmake#3357]
### Xmake Version

xmake v2.7.6+master.7f8eefb8a

### Operating System Version and Architecture

linux

### Describe Bug

For,

``` 
// Hello.cppm
export module X;
export int foo() { return 43; }

// xmake.lua
add_rules("mode.debug", "mode.release")

target("hello")
	set_kind("dynamic")
	add_files("Hello.cppm")
	set_languages("c++20")
```

I got the following message after I run `xmake`:

```
$xmake
[100%]: build ok!
```

Nothing got compiled.

### Expected Behavior

Hello.cppm should be compiled.

**Comment by waruqi** [comment]
> 	set_kind("dynamic")

set_kind("shared")

**Comment by ChuanqiXu9** [comment]
Thanks
