### ISSUE TITLE
xmake在windows下生成makefile、ninjia等构建配置存在路径问题

### ISSUE THREAD

**Issue by 233lol** [xmake-io/xmake#3359]
### Xmake 版本

 v2.7.6

### 操作系统版本和架构

Windows 10

### 描述问题

xmake在windows下生成makefile、ninjia等构建配置存在路径问题 
比如\ / 以及盘符C: 这些导致makefile和ninja出现问题，以及采用绝对路径导致移动文件夹时会出现问题

### 期待的结果

修复以上问题然后增加选项可以使用相对路径。

**Comment by waruqi** [comment]
目前就 vcproj/vsxmake/cmakelists 默认就是相对路径处理，makefile/ninja 之前一直没时间搞，所以暂时没弄。

等后面有空，可以改进下。

**Comment by waruqi** [comment]
这个放到下个版本搞，这个版本暂时不动了。

**Comment by senkuIgM** [comment]
同样路径问题，不能用Clion进行debug

**Comment by waruqi** [comment]
> 同样路径问题，不能用Clion进行debug

这跟 clion 没关系，生成cmakelists 支持路径转换，其他问题，请单独开 issues

**Comment by waruqi** [comment]
ninja的处理了。https://github.com/xmake-io/xmake/pull/3491

**Comment by waruqi** [comment]
makefile 也可以了 https://github.com/xmake-io/xmake/pull/3494
