### ISSUE TITLE
基于 conda 的多版本虚拟环境配置 编译运行官方的生成的工程

### ISSUE THREAD

**Issue by davidxiaozhi** [xmake-io/xmake#3383]
### 你在什么场景下需要该功能？

需要开发针对不同cuda tookit 的 GPU 算子,例如 cuckoo hash,需要测试多 cuda tookit 是否能够正常运行

### 描述可能的解决方案

--cuda 是配置整个 cuda 的目录,例如/usr/local/cuda 需要支持基于 conda 虚拟环境安装的 cuda tookit 进行配置
例如
add_cuda_includedirs("/App/conda/envs/conda_xmake/include")
add_cuda_linkdirs("/App/conda/envs/conda_xmake/lib")

**Comment by davidxiaozhi** [comment]
@waruqi  当前解决方案为安装系统层次 cuda,后续其他的解决方案可以通过系统软连切换来进行, 但可能需要基于 torch 和 tf 整体测试,这些一般基于虚拟环安装依赖

**Comment by waruqi** [comment]
> add_cuda_includedirs("/App/conda/envs/conda_xmake/include")
add_cuda_linkdirs("/App/conda/envs/conda_xmake/lib")

如果是这个结构，这样呢

```
xmake f --cuda=/App/conda/envs/conda_xmake
```

如果不是，具体贴下路径结构

**Comment by davidxiaozhi** [comment]
可以的  xmake f --cuda=/App/conda/envs/conda_xmake ,之前不可以是因为 conda 里面的安装,需要安装cudatoolkit-dev 才可以,否则是不能直接使用的

这个是安装 dev 后 lib 里的 cuda 动态库
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/6194818/219737664-6b32f0d0-9620-4817-9960-2d5961cf7623.png">
bin 目录
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/6194818/219738020-5ee1e4b7-3347-4c56-b82a-0b3cd2c3bc82.png">
include
![Uploading image.png…]()

**Comment by waruqi** [comment]
那现在还有什么问题么，指定 `--cuda=` 不是已经可以了？那我关了？

**Comment by davidxiaozhi** [comment]
@waruqi 好的,另外请教一下,如果底层芯片类 cuda 编程,但是不是 cuda, 我应该基于 xmake 怎么做完成同样的功能,有没有资料可以参考

**Comment by waruqi** [comment]
自定义 rule ，文档里自己看下

**Comment by davidxiaozhi** [comment]
@waruqi  好的学习一下
