### ISSUE TITLE
Multiple environment variable value in vcxproj when package:setenv api used

### ISSUE THREAD

**Issue by exalight87** [xmake-io/xmake#3391]
### Xmake Version

v2.7.6+HEAD.f00d2ed0a

### Operating System Version and Architecture

Windows 10 version 21H2

### Describe Bug

Sub package set specific environment variable via setenv api and when the solution is created with vsxmake the environment variable contains multiple time the value.

### Expected Behavior

Package setenv api should set a unique value to the specified environment variable

### Project Configuration

xmake.lua
```lua
package("a")
    set_kind("library")

    on_install(function(package)
    end)

    on_load(function(package)
        package:setenv("TEST", "value")
    end)
package_end()

package("b")
    set_kind("library")
    add_deps("a")

    on_install(function(package)
    end)
package_end()

add_requires("a", "b")

target("x")
    set_kind("static")
    add_packages("a", "b", {public= true})

target("y")
    set_kind("static")
    add_deps("x")
```

If you run `xmake project -k vsxmake` on this xmake.lua you should see in `vsxmake2022/y/y.vcxproj` that the field containing the environment variable `XmakeRunEnvs` contains `TEST=value;value;value;value;$([System.Environment]::GetEnvironmentVariable('TEST'))` instead of the expected `TEST=value;` as we configured the package to only set the value and not add it.

**Comment by waruqi** [comment]
please update to dev and try it again.  `xmake update -s dev`

**Comment by exalight87** [comment]
It's way better now, thanks!

`TEST=value;$([System.Environment]::GetEnvironmentVariable('TEST'))`

However, I still see `$([System.Environment]::GetEnvironmentVariable('TEST'))` is it wanted? Isn't the purpose of setenv api to overwrite the environment variable?

**Comment by exalight87** [comment]
Fair enough :) 

Thank you for the fix!
