### ISSUE TITLE
Windows下使用qt编译console_qt项目出错

### ISSUE THREAD

**Issue by jiagushuai** [xmake-io/xmake#340]
+ 用xmake的模板工程创建console成功
![image](https://user-images.githubusercontent.com/29997741/52040517-a1a5ae00-2572-11e9-97a4-c6218384744a.png)
##  但是编译失败,共57个error
![image](https://user-images.githubusercontent.com/29997741/52040537-b3875100-2572-11e9-9e2f-318bb0ea5a9c.png)
+ 加入链接库
```
    add_links("ws2_32")
    add_links("GDI32")
    add_links("ole32")
    add_links("ADVAPI32")
    add_links("SHELL32")
    add_links("USER32")

```
之后还有11个error

![image](https://user-images.githubusercontent.com/29997741/52044381-0534d900-257d-11e9-9256-160e0884b227.png)

**Comment by jiagushuai** [comment]
我用D盘的qt生成的程序可以独立在xp正常运行
![image](https://user-images.githubusercontent.com/29997741/52040868-b171c200-2573-11e9-946c-cf801890df6b.png)

**Comment by jiagushuai** [comment]
+ 我是用默认创建xmake的console_qt工程，没有改动。至于为什么用到这个不清楚。
![image](https://user-images.githubusercontent.com/29997741/52045426-770e2200-257f-11e9-89b5-9ce82a4e9a1d.png)

+我全局搜索了一下pcre关键字但是在没有找到qt目录下面有相关的lib

**Comment by waruqi** [comment]
可能还是跟你这的这个 msvc2015static 的 qt sdk 有关系。。里面的 Qt5Core 等库，默认内部使用了 pcre2等依赖库。。而之前我测试用的官方版本 sdk ，并没有这问题。。你这个 sdk 哪里弄来的？ 

看着像是你这个版本sdk里面的 库，默认所有lib都是静态依赖一些其他第三方库

虽然奇怪，不管怎样，根据错误提示，缺什么库 就加什么库被。既然缺pcre库，就加上pcre2库的link呗。先去sdk下面找找有没有，没有的话，就去下个pcre2.lib加进去。。
