### ISSUE TITLE
在链接合并的库时，又把子库链接了一遍

### ISSUE THREAD

**Issue by wond12** [xmake-io/xmake#3404]
### Xmake 版本

2.7.6

### 操作系统版本和架构

Windows 10 21H2, CentOS 7

### 描述问题

当在xmake.lua中使用合并静态库的功能时，最后使用这个合并后的静态库的地方，都会再把其子库链接一遍；既然已经合并了，是否可以不用链接其子库了。示例：
-- target里面省略了add_files，真实测试的时候，每个target都需要加上add_files
target("test_binary")
    set_kind("binary")
    add_deps("merge_static")

target("merge_static")
    set_kind("static")
    add_deps("test1_static", "test2_static")
    set_policy("build.merge_archive", true)

target("test1_static")
    set_kind("static")

target("test2_static")
    set_kind("static")

-- 最后生成的链接语句中，会出现 -lmerge_static -ltest1_static -ltest2_static，按理说，只需要-lmerge_static就可以了

### 期待的结果

生成-lmerge_static
而不是-lmerge_static -ltest1_static -ltest2_static

### 工程配置

[tmp.zip](https://github.com/xmake-io/xmake/files/10799288/tmp.zip)

**Comment by waruqi** [comment]
你可以先 `add_deps("test1_static", "test2_static", {inherit = false})` 禁用掉

**Comment by wond12** [comment]
> 你可以先 `add_deps("test1_static", "test2_static", {inherit = false})` 禁用掉

大佬，还是不行

**Comment by waruqi** [comment]
更新到 dev 再试试，`xmake update -s dev`
