### ISSUE TITLE
支持vcpkg的--x-install-root功能，指定包的安装目录

### ISSUE THREAD

**Issue by wond12** [xmake-io/xmake#3405]
### 你在什么场景下需要该功能？

默认的vcpkg安装目录在每个人的电脑上的路径都不一样，对于一些需要配置include目录以实现代码提示功能的IDE，如vscode，不是很友好，不方便把配置上传到版本控制仓库中（因为每个人需要配置的include目录不一样）。

### 描述可能的解决方案

在add_requires的configs里面增加字段x-install-root

**Comment by waruqi** [comment]
xmake 会生成 add_packages 包的 compile_commands.json 。。不需要自己硬编码配置任何东西。。

https://xmake.io/#/zh-cn/plugin/more_plugins?id=%e9%85%8d%e7%bd%ae-intellsence
