### ISSUE TITLE
xrepo fetch 的时候不支持指定vs版本

### ISSUE THREAD

**Issue by xiaozhu1337** [xmake-io/xmake#3407]
### 你在什么场景下需要该功能？

```
xrepo install -v -y -f "vs_runtime='MTd'" -m debug -k static -a x86 --vs=2019 boost
```
xrepo install 的时候支持指定vs版本，但是 xrepo fetch 的时候只能下面这样，不能指定vs版本，如果分别有2019和2022编译的相同库，没法区分
```
xrepo fetch --cflags --ldflags -f "vs_runtime='MTd'" -m debug -k static -a x86 boost
```

### 描述可能的解决方案

xrepo fetch 增加一个 --vs 的参数

**Comment by waruqi** [comment]
vs 根据 toolset 版本是向下兼容的，这种需求量太少，改动量和影响面较广，目前不考虑支持

**Comment by xiaozhu1337** [comment]
> vs 根据 toolset 版本是向下兼容的，这种需求量太少，改动量太大（buildhash 什么的都得变）和影响面较广，目前不考虑支持

这个向下兼容的意思是，2019编译出来的2022能用，还是2022编译出来的2019能用呀？

**Comment by waruqi** [comment]
2019 编译的 ，2022 能用

**Comment by xiaozhu1337** [comment]
刚刚搜了下，怪不得从2015开始，工具集都以14开头了，貌似都二进制互相兼容
https://learn.microsoft.com/zh-cn/cpp/porting/binary-compat-2015-2017?view=msvc-170
> 假设你具有 Visual Studio 2015 生成的第三方库。 你仍可在 Visual Studio 2017、2019 或 2022 生成的应用程序中使用它们。 无需使用匹配工具集重新编译。
