### ISSUE TITLE
在docker环境下运行, /dev/shm的默认大小是64m, 编译中大型项目时,存放临时文件报空间不足

### ISSUE THREAD

**Issue by wendal** [xmake-io/xmake#3408]
### Xmake 版本

2.7.3

### 操作系统版本和架构

Ubuntu 18.04, 在windows 10 + docker, 或者阿里云函数计算

### 描述问题

1. 需要是docker环境, 例如 windows 10 + docker, 阿里云函数计算
2. 构建镜像, ubuntu 系列均可
3. 使用docker启动镜像, 执行xmake -v, 如果项目足够大, 会出现以下报错

```
[ 97%]: cache compiling.debug thirdparty/littlefs/port/lfs_port_task.c

[ 99%]: archiving.debug libluatos.a

[ 99%]: merging.debug libluatos.a


FC Invoke End RequestId: 63c6db98-3ce5-4cb0-949e-1a4af0373aa0
error: cannot copy file build/.gens/luatos/cross/arm/debug/9627355F8FB44C098FF9D92C532D922A.a to /dev/shm/.xmake0/230223/_63B1A6D4E6D5441083BDF3779DFBB840.a, No space left on device
```

[相关问题的描述: ](https://lulaoshi.info/blog/dev-shm-docker/#docker)

翻阅源码找到环境变量配置项 XMAKE_RAMDIR, 临时解决之

### 期待的结果

若使用/dev/shm作为临时目录, 建议先探测其大小, 若过小应该放弃, 恢复使用系统默认的os.tmpdir

**Comment by waruqi** [comment]
其实这块加速也不是很明显，我 dev 默认禁用了，用户可以自己配置 `XMAKE_RAMDIR=/dev/shm` 来开启
