### ISSUE TITLE
msvc x64 -fp:fast 导致 nan 判断与 debug 不同

### ISSUE THREAD

**Issue by zeromake** [xmake-io/xmake#3411]
### Xmake 版本

xmake v2.7.6+HEAD.f00d2ed0a

### 操作系统版本和架构

Windows_NT 10.0 22621 x86_64 MS/Windows(windows11)

### 描述问题

https://github.com/facebook/yoga/issues/1232
release 默认带的 `-fp:fast` 选项导致 yoga 库在 release 和 debug 效果不同，查吐了，因为 release 编译不能调试。

### 期待的结果

是否考虑 msvc release 模式去掉 `-fp:fast` 选项，不过应该有一把库都在用这个编译选项了，是否可以先选择给与开关来关闭 `-fp:fast`

**Comment by zeromake** [comment]
顺便一提 x86 下正常，x64 才会出现

**Comment by waruqi** [comment]
自己 xmake.lua 里走 set_optimize("faster") 覆盖下设置就行了

```lua
if is_mode("release") then
    set_optimize("faster")
end
```

内部改的话，也可以，它现在跟 aggressive 是一样的配置，是可以调下的

https://github.com/xmake-io/xmake/blob/eda07a2a7382e7f43c42489b4402e34a41555f1c/xmake/modules/core/tools/cl.lua#L165

不过，现在也确实已经有不少项目在用了，所以直接改风险还是有的，你可以先按上面我说的方式自己改下。

如果后续有至少5到10人以上支持，并且自身项目测试正常，我可以考虑内部改下，fastest -> -O2
