### ISSUE TITLE
丰富输出日志

### ISSUE THREAD

**Issue by wond12** [xmake-io/xmake#3413]
### 你在什么场景下需要该功能？

由于target里面的源文件没有变化时，target不会被重新编译，所以在输出日志中看不到这个target的任何信息。
但有的时候我还是希望知道有哪些target被编译了（包括那些源文件没有变化的），比如我在make -v -g xxx时，对xxx组进行编译，如果组里面的target里面的源文件都没有变化，我只能看到一条build ok的消息，我不知道编译了哪些target，在排查一些错误的时候没有日志可循，所以希望能打印出来。
另外，还希望打印出整个编译过程的耗时。
以上需求均非必要需求，xmake确实做的很棒，点个星。

### 描述可能的解决方案

在加了-v选项后，把上述信息打印出来

**Comment by waruqi** [comment]
构建时间输出我加上了

```
[ 96%]: cache compiling.release src/demo/math/fixed.c
[ 96%]: cache compiling.release src/demo/libm/float.c
[ 96%]: cache compiling.release src/demo/libm/double.c
[ 98%]: archiving.release libtbox.a
[ 99%]: linking.release demo
[100%]: build ok, spent 5.132s
```
