### ISSUE TITLE
国产操作系统uos linux arm64 编译报错

### ISSUE THREAD

**Issue by sinnren** [xmake-io/xmake#3416]
### Xmake 版本

2.7.7

### 操作系统版本和架构

uos 4.19.0-arm64-desktop, aarch64 gnu/linux

### 描述问题

note: the following packages are unsupported on linux/arm64-v8a:
  -> cmake 3.24.2

无法继续编译。

### 期待的结果

能正常编译。

### 工程配置

add_rules("mode.debug", "mode.release")

add_requires("boost", "libarchive", "openssl", "jsoncpp", "libiconv", "lzma")

target("testx")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("boost", "libarchive", "openssl", "jsoncpp", "libiconv", "lzma")

### 附加信息和错误日志

fenlog@fenlogUOS-PC:~/work/testx$ xmake -vD
checking for platform ... linux
checking for architecture ... arm64-v8a
checking for gcc ... /usr/bin/gcc
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
/usr/bin/git rev-parse HEAD
finding bzip2 from xmake ..
checking for xmake::bzip2 ... no
finding bzip2 from pacman ..
checkinfo: cannot runv(pacman --version), No such file or directory
checking for pacman ... no
checking for pacman::bzip2 ... no
finding libbz2-dev from apt ..
checking for dpkg ... /usr/bin/dpkg
checking for apt::libbz2-dev ... no
checkinfo: cannot runv(emerge --version), No such file or directory
checking for emerge ... no
finding bzip2 from brew ..
checking for brew ... no
finding bzip2 from vcpkg ..
finding bzip2 from conan ..
finding bzip2 from pkgconfig ..
checking for pkg-config ... /usr/bin/pkg-config
finding bzip2 from system ..
checking for bzip2 ... no
finding zlib from xmake ..
checking for xmake::zlib ... no
finding zlib from pacman ..
checking for pacman::zlib ... no
finding zlib1g-dev from apt ..
checking for apt::zlib1g-dev ... no
finding zlib from find_zlib ..
finding zlib from brew ..
finding zlib from vcpkg ..
finding zlib from conan ..
finding zlib from pkgconfig ..
finding zlib from system ..
finding z from system ..
checking for zlib ... no
finding boost from xmake ..
checking for xmake::boost ... no
finding boost from pacman ..
checking for pacman::boost ... no
finding libboost-all-dev from apt ..
checking for apt::libboost-all-dev ... no
finding boost from brew ..
finding boost from vcpkg ..
finding boost from conan ..
finding boost from pkgconfig ..
finding boost from system ..
checking for boost ... no
checking for cmake ... no
checkinfo: cannot runv(cmake --version), No such file or directory
checking for cmake ... no
checkinfo: cannot runv(pacman::cmake --version), No such file or directory
checking for pacman::cmake ... no
checkinfo: cannot runv(apt::cmake --version), No such file or directory
checking for apt::cmake ... no
finding lz4 from xmake ..
checking for xmake::lz4 ... no
finding lz4 from pacman ..
checking for pacman::lz4 ... no
finding lz4 from brew ..
finding lz4 from vcpkg ..
finding lz4 from conan ..
finding lz4 from pkgconfig ..
finding lz4 from system ..
checking for lz4 ... no
finding zstd from xmake ..
checking for xmake::zstd ... no
finding zstd from brew ..
finding zstd from vcpkg ..
finding zstd from conan ..
finding zstd from pkgconfig ..
finding zstd from system ..
checking for zstd ... no
finding libarchive from xmake ..
checking for xmake::libarchive ... no
finding libarchive from brew ..
finding libarchive from vcpkg ..
finding libarchive from conan ..
finding libarchive from pkgconfig ..
finding libarchive from system ..
checking for libarchive ... no
finding openssl from xmake ..
checking for xmake::openssl ... no
finding openssl from find_openssl ..
finding openssl from brew ..
finding openssl from vcpkg ..
finding openssl from conan ..
finding openssl from pkgconfig ..
checking for openssl ... pkgconfig::openssl 1.1.1d
checking for xmake-repo::openssl ... openssl 1.1.1d
finding jsoncpp from xmake ..
checking for xmake::jsoncpp ... no
finding jsoncpp from brew ..
finding jsoncpp from vcpkg ..
finding jsoncpp from conan ..
finding jsoncpp from pkgconfig ..
finding jsoncpp from system ..
checking for jsoncpp ... no
finding libiconv from xmake ..
checking for xmake::libiconv ... no
checking for xmake-repo::libiconv ... libiconv 
finding lzma from xmake ..
checking for xmake::lzma ... no
finding lzma from brew ..
finding lzma from vcpkg ..
finding lzma from conan ..
finding lzma from pkgconfig ..
finding lzma from system ..
checking for lzma ... no
note: the following packages are unsupported on linux/arm64-v8a:
  -> cmake 3.24.2
error: @programdir/core/main.lua:302: @programdir/core/sandbox/modules/import/core/base/task.lua:65: stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:923]:
    [...modules/private/action/require/impl/install_packages.lua:739]:
    [@programdir/modules/private/action/require/install.lua:85]:
    [@programdir/actions/config/main.lua:453]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/core/base/task.lua:501]: in function 'run'
    [@programdir/core/sandbox/modules/import/core/base/task.lua:63]: in function 'run'
    [@programdir/actions/build/main.lua:159]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/core/base/task.lua:501]: in function 'run'
    [@programdir/core/main.lua:300]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:404]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:912: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir/core/main.lua:302: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>

**Comment by waruqi** [comment]
目前 cmake 这包，在 linux 上，我只加了 x86_64 的源，没放开 arm64

你可以提个 pr 过来，加上 arm64 的 url 源和 sha256 

https://github.com/xmake-io/xmake-repo/blob/1e2e3b3106139b9f24f8e99833fbc5fa0e457642/packages/c/cmake/xmake.lua#L21

然后这里去掉 x86_64 的限制就行了。。

https://github.com/xmake-io/xmake-repo/blob/1e2e3b3106139b9f24f8e99833fbc5fa0e457642/packages/c/cmake/xmake.lua#L87

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-repo/pull/1860

再试下

```
xrepo update-repo
```

**Comment by sinnren** [comment]
awesome.
