### ISSUE TITLE
`add_vectorexts` 缺少 fma 指令集

### ISSUE THREAD

**Issue by ryblust** [xmake-io/xmake#3418]
### Xmake 版本

v2.7.7+HEAD.da4fa3574

### 操作系统版本和架构

Windows11 version 22621.1265

### 描述问题

```c++
#include <immintrin.h>

int main() {
    __m128 a{};
    _mm_fmadd_ps(a, a, a);
}
```
通过 gcc/clang 编译时，`add_vectorexts("fma")` 在 `2.7.7` 上没有添加 `-mfma` 这个 flag，之前版本可以

### 期待的结果

添加 `add_vectorexts` 对 fma 指令集的支持

### 工程配置

```lua
target("test")
    add_vectorexts("fma")
    add_files("main.cpp")
```

### 附加信息和错误日志

error: @programdir\modules\private\async\runjobs.lua:256: @programdir\modules\private\action\build\object.lua:91: @programdir\modules\core\tools\gcc.lua:713: In file included from c:\dev\mingw64\lib\gcc\x86_64-w64-mingw32\12.2.0\include\immintrin.h:105,
                 from main.cpp:1:
c:\dev\mingw64\lib\gcc\x86_64-w64-mingw32\12.2.0\include\fmaintrin.h: In function 'int main()':
c:\dev\mingw64\lib\gcc\x86_64-w64-mingw32\12.2.0\include\fmaintrin.h:55:1: error: inlining failed in call to 'always_inline' '__m128 _mm_fmadd_ps(__m128, __m128, __m128)': target specific option mismatch
   55 | _mm_fmadd_ps (__m128 __A, __m128 __B, __m128 __C)
      | ^~~~~~~~~~~~
main.cpp:5:17: note: called from here
    5 |     _mm_fmadd_ps(a, a, a);
      |     ~~~~~~~~~~~~^~~~~~~~~
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:912]:
    [@programdir\modules\core\tools\gcc.lua:713]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [@programdir\modules\core\tools\gcc.lua:654]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\modules\private\action\build\object.lua:91]: in function 'script'
    [@programdir\modules\private\action\build\object.lua:104]: in function 'build_object'
    [@programdir\modules\private\action\build\object.lua:129]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:232]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:218]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:404]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:912: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\modules\private\async\runjobs.lua:256: in field 'catch'
        @programdir\core\sandbox\modules\try.lua:123: in global 'try'
        @programdir\modules\private\async\runjobs.lua:218: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>
warning: .\xmake.lua:2: unknown vectorext value 'fma', it may be 'sse'

**Comment by waruqi** [comment]
> 之前版本可以

从来没支持过

**Comment by ryblust** [comment]
> > 之前版本可以
> 
> 从来没支持过

那就奇怪了 我之前编译的时候他确实添加了 `-mfma` 这个 flag 我用的 mingw 和 clang-cl

**Comment by waruqi** [comment]
> > > 之前版本可以
> > 
> > 
> > 从来没支持过
> 
> 那就奇怪了 我之前编译的时候他确实添加了 `-mfma` 这个 flag 我用的 mingw 和 clang-cl

肯定不是 xmake 内部加的，从来没支持过这个。连这个 flags 我都是头一次听说

**Comment by waruqi** [comment]
要么是你之前引入了什么依赖包，里面带进来的。。xmake-repo 仓库有几个包，我看有这个 flag，你可以搜下

**Comment by ryblust** [comment]
> 要么是你之前引入了什么依赖包，里面带进来的。。xmake-repo 仓库有几个包，我看有这个 flag，你可以搜下

我自己写的数学库只用到了标准库和 `immintrin.h`，没有其他依赖
那既然这样不如把 fma 的支持加到 `add_vectorexts` 里面。如果不合适的话，我自己添加 `add_cxxflags` 也可以

**Comment by waruqi** [comment]
帮忙 review 下 flags  https://github.com/xmake-io/xmake/pull/3421
