### ISSUE TITLE
xmake remote build hang

### ISSUE THREAD

**Issue by shaqtsui** [xmake-io/xmake#3422]
### Xmake Version

2.7.6

### Operating System Version and Architecture

Ubuntu 20.04

### Describe Bug

remote build via command `echo xmake | bash` will hang(never return). While the same project config can successfuly executed via `bash -c xmake`.
I have tried some projects. 
Seems:
  this happen on all projects, nothing to do with xmake config.
  local build can be executed via `echo xmake | bash`

### Expected Behavior

remote build with `echo xmake | bash` successfully return. 

### Project Configuration

```
target "mailioexample"
set_version "0.1.0"
add_files "src/*.cpp"
```

### Additional Information and Error Logs

Stop on below log:
```
root@mibp:~/Projects/mailioexample# xmake service --connect
<remote_build_client>: connect 127.0.0.1:9691 ..
<remote_build_client>: connected!
<remote_build_client>: sync files in 127.0.0.1:9691 ..
Scanning files ..
Comparing 2 files ..
0 files has been changed!
<remote_build_client>: sync files ok!
root@mibp:~/Projects/mailioexample# echo xmake | bash
<remote_build_client>: run xmake in 127.0.0.1:9691 ..

```

seems that remote build stdout is blocked.

**Comment by waruqi** [comment]
when running `echo xmake | bash`, `io.readable` always return true. But right now I don't know how to fix it.

https://github.com/xmake-io/xmake/blob/d960f672350aa0a446c3a0f403c156cc207232b0/xmake/modules/private/service/remote_build/client.lua#L558

https://github.com/tboox/tbox/blob/5a19b3ec9c527305f9f2bb75feb50d0a6ff5c90a/src/tbox/platform/stdfile.c#L142

**Comment by waruqi** [comment]
please update to dev and try it again.

```
xmake update -s dev
```

**Comment by shaqtsui** [comment]
Amazing quick fix (supprise face).
Checked ok in my local. 
Great thanks.
