### ISSUE TITLE
Allow custom option name on checking flags/macros/...

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#3424]
### 你在什么场景下需要该功能？

https://github.com/xmake-io/xmake/blob/8e5e0c6038239eae863341bcf060f6d0ae4e7348/xmake/includes/check_macros.lua#L31

目前通过check_xxx.lua引入的option都以双下划线开头，但实际上这些option之后还需要通过get_option来引用（option内部不能加add_requires等语句），以双下划线开头并不方便。

### 描述可能的解决方案

希望通过opt.name可以修改全名，而不要再加双下划线，同时在文档里写清楚这一接口
```lua
local optname = opt.name or "__" .. definition
```

**Comment by waruqi** [comment]
因为之前这些没打算开放给 get_config/has_config 使用，算是内部私有 option ，所以没文档化

而且对外用户也不知道这是用 option 实现的，也许以后改用其他方式实现都有可能。

如果想要走 has_config/get_config 可以直接自己定义 option 来实现。

**Comment by waruqi** [comment]
如果要开放出来，以后实现上就不太好大改了，我还没想好，所以之前暂时没公开文档化

等后面我再想想吧，先可以暂时自己走 option 封装下，自己 function wrap 下也没几行配置

**Comment by waruqi** [comment]
改了，文档等后续版本在更新，或者也可以帮忙来个 pr
