### ISSUE TITLE
Module files are not added(.ixx) when generating a visual studio 2022 project

### ISSUE THREAD

**Issue by Vantus555** [xmake-io/xmake#3426]
### Xmake Version

2.7.7

### Operating System Version and Architecture

windows 10 - 11

### Describe Bug

When generating a project for vs2022, module files are not added to the project. Only .cpp are added. If you generate a vsxmake project, then everything works. But there is also a mistake. All constructions are underlined in red, as if there is no connection of libraries, but if you start the project, it will start without errors.

### Expected Behavior

Adding modules (.ixx) and the correct operation of IntelliSense

### Project Configuration

set_project("Engine2023")

add_rules("mode.debug", "mode.release")
set_defaultmode("debug")
set_defaultarchs("windows|x64")
set_allowedarchs("windows|x64")
set_languages("c++20")

target("Engine")
    set_kind("static")
    add_files(
        "src/Engine/**.cpp",
        "src/Engine/**.ixx",
        "src/Dependencies/**.ixx"
    )
    add_includedirs("src/Engine/", "src/Dependencies/")

target("Game")
    set_default(true)
    set_kind("binary")
    add_files("src/Game/**.cpp")
    add_deps("Engine")
    add_includedirs("src/Engine/")
    before_build(function (target)
        local out = target:targetdir()
        os.cp("$(scriptdir)/content", out)
    end)

### Additional Information and Error Logs

![image](https://user-images.githubusercontent.com/55625210/221403697-8ee319de-e848-432d-b7e0-f7b43447101f.png)

**Comment by waruqi** [comment]
> When generating a project for vs2022, module files are not added to the project.

 It is not yet supported.

>  All constructions are underlined in red, as if there is no connection of libraries, but if you start the project, it will start without errors.

Intelligense is also not yet supported.

**Comment by waruqi** [comment]
I have supported it. https://github.com/xmake-io/xmake/pull/4748

```
xmake update -s dev
```
