### ISSUE TITLE
cannot open file: \detect, Unknown

### ISSUE THREAD

**Issue by Cyrisub** [xmake-io/xmake#3427]
### Xmake Version

2.7.4

### Operating System Version and Architecture

Windows 11 22H2

### Describe Bug

I'm using xmake + msvc in windows recently, but it reports `cannot open file: \detect, Unknown` as if it cannot find msvc.

debug output below (run in fresh-new project created by `xmake create`):
> ❯ xmake f -cvD --toolchain=msvc
> checking for platform ... windows
> checking for architecture ... x64
> checking for vswhere.exe ... C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
> error: @programdir\core\main.lua:280: @programdir\core\tool\toolchain.lua:263: @programdir\core\cache\globalcache.lua:63: cannot open file: \detect, Unknown
> stack traceback:
>     [C]: in function 'error'
>     [@programdir\core\base\os.lua:897]:
>     [@programdir\core\cache\globalcache.lua:63]: in function 'save'
>     [@programdir\modules\detect\sdks\find_vstudio.lua:391]:
>     [@programdir\toolchains\msvc\check.lua:43]: in function '_check_vsenv'
>     [@programdir\toolchains\msvc\check.lua:86]:
>     [C]: in function 'xpcall'
>     [@programdir\core\base\utils.lua:280]:
>     [@programdir\core\tool\toolchain.lua:259]: in function 'check'
>     [@programdir\core\platform\platform.lua:247]: in function 'check'
>     [@programdir\actions\config\main.lua:444]:
>     [C]: in function 'xpcall'
>     [@programdir\core\base\utils.lua:280]:
>     [@programdir\core\base\task.lua:501]: in function 'run'
>     [@programdir\core\main.lua:278]: in function 'cotask'
>     [@programdir\core\base\scheduler.lua:404]:
> 
> stack traceback:
>         [C]: in function 'error'
>         @programdir\core\base\os.lua:897: in function 'os.raiselevel'
>         (...tail calls...)
>         @programdir\core\main.lua:280: in upvalue 'cotask'
>         @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>

I use VS2022 MSVC v143 build tools + Windows 10 SDK 10.0.19041.0, seems xmake chage the usage of vswhere causing some compatibility issue, because 2.7.4 is the oldest version has that issue, 2.7.3 works fine, and it still exist in 2.7.7.

### Expected Behavior

xmake should find msvc and build normally.

**Comment by waruqi** [comment]
try run 

```
xmake g -c
xmake f -c
```

**Comment by Cyrisub** [comment]
it works! Looks like xmake not longer rely on the detect file. Thanks a lot!
