### ISSUE TITLE
在依赖包版本锁定中检测自定义选项

### ISSUE THREAD

**Issue by MasterBalll** [xmake-io/xmake#3430]
### 你在什么场景下需要该功能？

关联讨论 https://github.com/xmake-io/xmake/discussions/3415#discussioncomment-5098598
如讨论所说，嵌入式开发中，可能采用选项来指定不同的处理器核心配置以及其他配置，进而对应到不同的依赖包。
如此一来，单纯用 plat|arch 来锁定一组依赖包就会有歧义，因为不同的选项组合会对应不同的依赖包。

### 描述可能的解决方案

是否可以在 xmake-requires.lock 中加入对自定义选项值的记录，从而可以针对不同的 plat|arch 以及选项的组合来锁定依赖包。

**Comment by waruqi** [comment]
原本就会根据传给 add_requires("xxx", {configs = {option1 = "", option2 = ""}}) 中的 `configs = {}` 所有配置，生成包唯一 hash 

不同配置的包，互不冲突，存储路径都是不同的。。跟时候锁定没关系。。即使不锁定，也是不冲突的。。

你外面自己定义的 option ，跟 add_requires 和 包本身没任何关联，你想依赖外面自己定义的。 option。。

就自己根据 get_config/has_config 判断你的 option ，传入 add_requires 中的 configs ，来对包针对性配置。

另外，前提是 package 本身定义里面已经通过add_configs 定义了这些配置。

**Comment by MasterBalll** [comment]
我明白问题在哪了，问题里这么写，似乎产生了歧义，作者跟我理解成了不同的意思。
我重新表述一下。

就是对于把自定义 option 通过 `xmake f --opt1=xxx --opt2=xxx` 映射到包的 configs 定义上，从而对应不同的 hash 版本，这一点我是理解的，也是这么做的。

需求不在于这里，而是在于当我配置成不同的选项组合时，比如 `xmake f --opt1=a --opt2=a` 与
`xmake f --opt1=b --opt2=b` ，它们其实是可以对应不同的依赖包组合的，而不仅仅是 hash 版本。

目前的包版本锁定，只是针对 plat|arch 来保存锁定的包版本信息。
比如，现在的 xmake-requires.lock 是这样的
```txt
{
    __meta__ = {
        version = "1.0"
    },
    ["cross|xtensa"] = {
        ["HiFi2_NatureDSP_Signal 0.2.0#019dd64e"] = {
            repo = {
                commit = "xxx",
                url = "xxx"
            },
            version = "0.2.0"
        },
        ["hifi_common 0.2.0#019dd64e"] = {
            repo = {
                commit = "xxx",
                url = "xxx"
            },
            version = "0.2.0"
        }
    }
}
```
这是假设了不同配置组合下包都是一样的，只是 configs 不同，但实际上包也有可能不同。
所以希望加入对选项值的记录，意思是说，或许可以改成类似这样
```txt
{
    __meta__ = {
        version = "1.0"
    },
    ["cross|xtensa,opt1=a,opt2=a"] = {
        ["HiFi2_NatureDSP_Signal 0.2.0#019dd64e"] = {
            repo = {
                commit = "xxx",
                url = "xxx"
            },
            version = "0.2.0"
        },
        ["hifi_common 0.2.0#019dd64e"] = {
            repo = {
                commit = "xxx",
                url = "xxx"
            },
            version = "0.2.0"
        }
    },
    ["cross|xtensa,opt1=b,opt2=b"] = {
        ["HiFi3_NatureDSP_Signal 0.2.0#019dd64e"] = { # 【注意到这个包和上面是不同的】
            repo = {
                commit = "xxx",
                url = "xxx"
            },
            version = "0.2.0"
        },
        ["hifi_common 0.2.0#019dd64e"] = {
            repo = {
                commit = "xxx",
                url = "xxx"
            },
            version = "0.2.0"
        }
    }
}
}
```

**Comment by MasterBalll** [comment]
@waruqi 有空的话麻烦再看下这个。

**Comment by waruqi** [comment]
> 这是假设了不同配置组合下包都是一样的，只是 configs 不同，但实际上包也有可能不同。
> 所以希望加入对选项值的记录，意思是说，或许可以改成类似这样

不考虑，目前只能支持到 plat/arch 。。就算支持了 options，还有各种其他乱七八糟的用户条件判断，都可能干扰包组合，比如 系统版本，编译器版本，编译器名，编译器特性，。。。组合和干扰因素多了去了，永远不可能全部存下来。。

**Comment by MasterBalll** [comment]
好吧，那只好先不锁定版本了。
