### ISSUE TITLE
MSYS2 QT支持

### ISSUE THREAD

**Issue by zyppe** [xmake-io/xmake#3433]
### 你在什么场景下需要该功能？

MSYS2是一个非常常见的在Windows下用类似于Linux的操作模式开发的方案，内置有QT5/6与qtcreator，但似乎xmake并不支持MSYS2内置的QT。

### 描述可能的解决方案

按照类似于Linux的方式检测QT的SDK

### 其他信息

![image](https://user-images.githubusercontent.com/10075036/221558195-591bae1d-8795-4cbb-b333-0a1e30edb60e.png)

**Comment by waruqi** [comment]
我看可以的么，你得打开 mingw64 的终端，或者手动切到 mingw 平台，`xmake f -p mingw -c`

你现在打开的 msys2 终端，非 mingw 环境，默认不是 mingw 平台，不会去找 mingw qt

![image](https://user-images.githubusercontent.com/151335/221740060-4eee01eb-b941-4123-9411-b665ab0982ec.png)

**Comment by waruqi** [comment]
mingw/msys2 原本就支持的，另外，我 dev 修复一些新版本 mingw toolchain 导致 stdlib.h 找不到的问题。其他也没啥了

```
xmake update -s dev
```

![image](https://user-images.githubusercontent.com/151335/221744616-400dc935-ed50-46f1-850a-3df0c603c2df.png)

**Comment by zyppe** [comment]
我是用MSYS2里面的clang64平台的，估计UCRT64平台也会有这个问题

**Comment by zyppe** [comment]
![image](https://user-images.githubusercontent.com/10075036/222152738-b518079a-7cd2-499c-9437-38b1321560e7.png)
![image](https://user-images.githubusercontent.com/10075036/222153021-e32ec830-953c-4e6a-8fab-fd4f3b019972.png)
给您提供两张参考图

**Comment by zyppe** [comment]
另外，我给我的qtcreator安装的xmake插件也是没有任何动作预计和这个有很大关系

**Comment by waruqi** [comment]
> 手动切到 mingw 平台，`xmake f -p mingw -c`

手动切到 mingw 平台，xmake f -p mingw -c

**Comment by waruqi** [comment]
> 另外，我给我的qtcreator安装的xmake插件也是没有任何动作预计和这个有很大关系

这个是第三方插件，不是我搞的，你得找对应的 issues 上去问了。

**Comment by zyppe** [comment]
可不可以顺带着把clang64和ucrt64也添加支持了
