### ISSUE TITLE
menuconfig 界面中的 toolchain name 无法指定

### ISSUE THREAD

**Issue by iamlook** [xmake-io/xmake#3436]
### Xmake 版本

v2.7.7+HEAD.da4fa3574

### 操作系统版本和架构

Windows 10 Professional 21H1

### 描述问题

无法通过menuconfig界面配置toolchain name;

通过 `xmake f --menu` 进入menuconfig界面, 
```
Basic Configuration -> 
    Corss Complation Configuration ->
        Set Toolchain name ()  ----
```
如上顺序进入交叉编译菜单里, Set Toolchain name 这个选项不会返回任何系统支持或自定义的 toolchain 供选择.

查看代码 `actions\config\xmake.lua` 里面 , toolchain 对应的 `values = _toolchain_values` , 这里的values都带了 complete 和 opt 参数, 但我不确定是否是因为我系统的原因, 在windows下各种bash都不能自动补全, complete 参数也永远都是 false .  但是对比其他配置项的 values 函数, 似乎只有 `_toolchain_values` 是只在 complete 的情况才返回值的.  感觉是不是没有必要? 或者我应该做什么配置或操作来达到complete的状态?

### 期待的结果

menuconfig 界面应该也可以像 `xmake show -l toolchains`  命令一样可以展示出所有支持和自定义的toolchain name供用户选择使用, 选定后效果和 `xmake f --toolchain=XXXX` 相同.

**Comment by waruqi** [comment]
> 在windows下各种bash都不能自动补全, complete 参数也永远都是 false，或者我应该做什么配置或操作来达到complete的状态?

只有走脚本安装，才会有。走安装包安装，目前不会装 complete 。。或者执行 `xmake update --integrate` 手动装下

> 似乎只有 _toolchain_values 是只在 complete 的情况才返回值的. 感觉是不是没有必要?

因为 toolchains list 太长了，`xmake f --help` 显示会刷屏，所以我暂时禁用了，仅仅对 complete 生效

**Comment by waruqi** [comment]
刚改进了下，再试试 `xmake update -s dev`

**Comment by iamlook** [comment]
我确实是安装包安装的, 之前直接在msys里安装记得好像menu会有问题, 所以后来都用安装包或者zip来安装升级了.
试了下  `xmake update --integrate` 显示  `error: failed to get profile location from powershell!` , 还没有研究是哪里有问题.
看了新的代码, 这样应该是没问题了.  

主要是我们的用户要求要有menuconfig来配置. 所以能支持最方便了.

Thanks!

**Comment by waruqi** [comment]
win 上目前只有走 ps 的脚本安装，才会去装 complete。。

如果没啥问题了，这里我先关了

**Comment by xq114** [comment]
> 我确实是安装包安装的, 之前直接在msys里安装记得好像menu会有问题, 所以后来都用安装包或者zip来安装升级了. 试了下 `xmake update --integrate` 显示 `error: failed to get profile location from powershell!` , 还没有研究是哪里有问题. 看了新的代码, 这样应该是没问题了.

xmake内是通过
```
Write-Output $PROFILE.CurrentUserAllHosts
```
来定位ps文件的安装位置的，可以试试powershell里这条命令能不能正常输出
