### ISSUE TITLE
自建包仓库使用本地 url 时总会自动切到特定版本

### ISSUE THREAD

**Issue by MasterBalll** [xmake-io/xmake#3437]
### Xmake 版本

2.7.7

### 操作系统版本和架构

Windows 10 version 22H2

### 描述问题

自建包仓库，使用本地 url 。
在安装包时，

![image](https://user-images.githubusercontent.com/122007764/222051418-93132755-b727-4583-a467-c6261b11bb5a.png)

会触发包仓库切换至最新版本（如图就是 v0.2.1）

![image](https://user-images.githubusercontent.com/122007764/222051491-9d336ef8-9747-413e-81fe-f060cb527f56.png)

即便指定了分支，`xrepo add-repo xxx <本地url> dev` ，也是如此。

### 期待的结果

自建包仓库使用本地 url 时，如果不指定分支，能应用最新改动。

**Comment by MasterBalll** [comment]
我把自建包仓库又复制了一份，换成这个新目录是正常的，不知道是啥原因，是不是哪里的缓存需要清一下？

**Comment by waruqi** [comment]
> 即便指定了分支，xrepo add-repo xxx <本地url> dev ，也是如此。

包版本，跟仓库分支有啥关系？包版本只跟 add_versions 指定的版本列表，和 add_requires 和指定的版本有关。。

 add_requires 不指定版本，默认拉取的就是 add_versions 的最新版本，如果要固定版本，就 add_requires("zlib 1.2.11") 指定版本约束。或者走版本锁定 https://xmake.io/#/zh-cn/package/remote_package?id=%e4%be%9d%e8%b5%96%e5%8c%85%e7%9a%84%e9%94%81%e5%ae%9a%e5%92%8c%e5%8d%87%e7%ba%a7

跟你切哪个 包仓库分支 没任何关系

**Comment by MasterBalll** [comment]
不是不是，包版本没有问题，是自建包仓库的相关设置上可能有问题。

> 在安装包时，
> 会触发包仓库切换至最新版本（如图就是 v0.2.1）

就是今天不知道咋回事，本来包仓库是在 dev 的，但是 `xmake f xxx` 一配置，它就自动切到 v0.2.1，很是奇怪。

**Comment by waruqi** [comment]
> xrepo add-repo xxx <本地url> dev

这个是加的全局仓库，不受缓存影响。。

> xmake repo --add local-repo 

这个是加的本地工程仓库，存在当前工程目录下

另外，还可以通过 add_repositories 去设置仓库地址和分支。。

但是同时可以加多个仓库，优先用本地仓库，然后再用全局仓库。。

你自己通过 `xmake repo -l` 看下当前 仓库 list ，和它的查找顺序
