### ISSUE TITLE
Rust package handling is broken for packages containing "-"

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#3452]
### Xmake Version

2.7.7

### Operating System Version and Architecture

Windows 11

### Describe Bug

This [change](https://github.com/xmake-io/xmake/commit/081dd1de9439e2bf71ab1a1afffac3cb9a1049e1) introduced a bug, as by default Rust libraries containing a - (for example future-util) will produce .rlib file such as `libfuture_util-<hash>.rlib`.

With this commit, xmake now searches for a `libfuture-<hash>.rlib` file which is wrong.

This causes xmake to not link some libs (and rustc to not find some libraries).

I know this change was caused by this discussion: https://www.reddit.com/r/xmake/comments/zq9k9c/xmake_not_installing_all_cargo_dependencies and I checked why obj-rs didn't produce a `libobj_rs-<hash>.rlib` file and it's because this lib [renames its output file](https://github.com/simnalamburt/obj-rs/blob/main/obj-rs/Cargo.toml#L20).

I don't know if we can detect this when cargo builds the crate rlib file, but for now we should revert the commit as it breaks more libraries than it fixes.

### Expected Behavior

That it works with all Rust crates.

### Project Configuration

I tested this with:

src/main.rs:
```rs
use obj::*;
use futures_util::*;

fn main() {
    println!("Hello, world!");
}
```

Cargo.toml:
```rs
[package]
name = "test_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3"
obj-rs = "0.7.0"
```

xmake.lua:
```
add_requires("cargo::test", {configs={cargo_toml=path.join(os.scriptdir(), "Cargo.toml"),version="*"}})

target("test")
	set_kind("binary")
	add_files("src/main.rs")
	add_packages("cargo::test")
```

with the current xmake version, this project will break on `future-util`:
```
lynix@SirDesktop:/mnt/c/Projets/Perso/Tests/test_rust$ xmake.exe
checking for Microsoft Visual Studio (x64) version ... 2022
[ 33%]: linking.release test.exe
error: error[E0432]: unresolved import `futures_util`
 --> src\main.rs:3:5
  |
3 | use futures_util::*;
  |     ^^^^^^^^^^^^ use of undeclared crate or module `futures_util`
```

with https://github.com/xmake-io/xmake/commit/081dd1de9439e2bf71ab1a1afffac3cb9a1049e1 reverted, `obj-rs` breaks:
```
lynix@SirDesktop:/mnt/c/Projets/Perso/Tests/test_rust$ xmake.exe
[ 33%]: linking.release test.exe
error: error[E0432]: unresolved import `obj`
 --> src\main.rs:2:5
  |
2 | use obj::*;
  |     ^^^ use of undeclared crate or module `obj`
```

however I think it should be reverted for now until we have a better solution, because most Rust libraries don't rename their library file.

**Comment by waruqi** [comment]
you can open a pr.

**Comment by waruqi** [comment]
I tried extracting the libname from cargo.toml and it seems to work for me, despite some hacking.

I don't have a better way to deal with it at the moment.

https://github.com/xmake-io/xmake/commit/8c1523adbcc37c3e020433faada44e8825bf99b6

**Comment by SirLynix** [comment]
It works great with #3462 applied, thanks.
