### ISSUE TITLE
Dlang incremental build support

### ISSUE THREAD

**Issue by Mergull** [xmake-io/xmake#3455]
### Is your feature request related to a problem? Please describe.

I've tried to compile one of my projects with xmake. Project setup is really nice and easy. Problem is that xmake doesn't support dependencies for incremental building for Dlang. This leads to requirement for full rebuild everytime something changed (what is really bad for big projects).

### Describe the solution you'd like

Only changed files and files which depend on them should be recompiled. 
Both DMD and LDC has "-makedeps" option which produce makefile compatible dependency information (so it can be used to get that kind of information).

**Comment by waruqi** [comment]
Can you provide an example project?

**Comment by Mergull** [comment]
Link to repository branch: [(https://gitlab.com/Mergul/bubel-ecs/-/tree/xmake)]
There is simple xmake.lua build file on **xmake** branch

**Comment by waruqi** [comment]
try this patch. https://github.com/xmake-io/xmake/pull/3487

```
xmake update github:xmake-io/xmake#dlang
```

**Comment by Mergull** [comment]
That's was quick! From brief testing it looks that incremental building is working now. Thanks!
