### ISSUE TITLE
原本的 project.name() 和 project.version() 都消失了，請問有替代方法嗎?

### ISSUE THREAD

**Issue by orzuk-lmj** [xmake-io/xmake#346]
- 目前已知 project.set_version() 被移動到 target 中，對應的取得version() 方法也是。
- 使用 name 和 version 方法是為了取得字串，設置一些專案資料夾路徑，用來安裝東西用。
- 原本打算用 set_config("project_version",  ".....")  這種方法來達到目的，但發現on_install 的時候 config.get("project_version") 取得的是 nil

- 更新前：
    ``` lua
    import("core.project.project")
    project.name()  -- 可以取得 set_project("xxx")
    project.version()    -- 可以取得 set_version("1.2.3")
    ```
- 重要的是必須讓 on_install 的時候可以拿到正確資料

**Comment by waruqi** [comment]
> 目前已知 project.set_version() 被移動到 target 中，對應的取得version() 方法也是。

考虑到之前通过 set_version全局设置工程版本，如果某个set_version设置了版本的工程 被 includes 作为了子工程模块， 那么project version就会被 子xmake.lua里面的set_version所影响，独立工程 和 子模块工程间 无法无缝切换了。。

所以master上我把set_version作为target的设置，缩小影响范围，提供更多的可控性，每个target可以有 不同的版本号，尤其是 生成 config.h 里面的 version定义，也可以每个target对应 不同的版本，不会被全局干扰

虽然设置到了Target, 但是如果set_version在全局root域设置，还是会影响所有Target, 相当于全局project versiob设置的效果

> 原本的 project.name() 和 project.version() 都消失了

这两个接口，并没有消失，会长期有效，并且也能够正常处理，`project.version()`会通过遍历target获取到全局project version，如果set_version在root域设置的话

当然也可以单独对指定target获取version，`target:get("version")`

如果你这`project.version()`返回空，按理应该不会的，如果真为nil，那就是bug，可能我没处理好，等晚上我抽空看下。。

理论上现在这两种版本获取方式都是可以


```lua
set_version("1.0")

target("test1")
    on_install(function (target)
         import("core.project.project")
         print(project.version()) -- version: 1.0
    end)

target("test2")
    set_version("1.1")
    on_install(function (target)
         print(target:get("version"))  -- version: 1.1
    end)
```

不过我更建议使用 `target:get("version")` 来直接获取

目前project.version我会一直保留兼容下去，不过现在处理的不是很好，后面我会想办法更好的获取到Root version，而不是遍历targets来获取。

**Comment by orzuk-lmj** [comment]
> 前project.version我会一直保留兼容下去，不过现在处理的不是很好

- 使用 target:get("version") 取得正確
- 使用 project.version() 失敗
    ``` lua
    attempt to call field 'version' (a nil value)
    error: installation failed, may permission denied!
    checking for the sudo ... no
    ```

**Comment by waruqi** [comment]
哦，我想起了，可能当初我改完随手删了，我晚上恢复下。。

**Comment by waruqi** [comment]
project.version我恢复了，并且做了改进

```lua
set_version("1.0.1")

target("test")
    set_kind("binary")
    add_files("src/*.c") 

    set_version("1.0.3")
```

project.version() 将会获取到root下全局version 1.0.1， target:version() 将会获取到 1.0.3

**Comment by orzuk-lmj** [comment]
感謝
