### ISSUE TITLE
使用std模块时构建失败

### ISSUE THREAD

**Issue by hackermdch** [xmake-io/xmake#3463]
### Xmake 版本

v2.7.7+dev.8c1523adb

### 操作系统版本和架构

Windows 11 21H2 + VS2022 17.5.1

### 描述问题

使用debug或release配置进行首次构建可以成功，但之后切换到release或debug再次构建出现链接错误

### 期待的结果

正常构建

### 工程配置

[simple.zip](https://github.com/xmake-io/xmake/files/10895843/simple.zip)
运行build.bat可重现错误

### 附加信息和错误日志

<pre>
[  0%]: generating.module.deps test\test.cpp
[  0%]: generating.module.deps src\mod.ixx
[  0%]: generating.module.deps src\mod.cpp
[  5%]: compiling.module.debug std
[ 11%]: compiling.module.debug std.compat
[ 11%]: compiling.module.debug mod
[ 35%]: compiling.debug src\mod.cpp
[ 41%]: archiving.debug lib.lib
[ 82%]: compiling.debug test\test.cpp
[ 88%]: linking.debug bin.exe
error: std.ixx.ifc.obj : error LNK2005: "char * __cdecl std::ctime(__int64 const * const)" (?ctime@std@@YAPEADQEB_J@Z::<!std>) 已经在 std.ixx.ifc.obj 中定义
std.ixx.ifc.obj : error LNK2005: "double __cdecl std::difftime(__int64,__int64)" (?difftime@std@@YAN_J0@Z::<!std>) 已经在 std.ixx.ifc.obj 中定义
std.ixx.ifc.obj : error LNK2005: "struct tm * __cdecl std::gmtime(__int64 const * const)" (?gmtime@std@@YAPEAUtm@@QEB_J@Z::<!std>) 已经在 std.ixx.ifc.obj 中定 义
std.ixx.ifc.obj : error LNK2005: "struct tm * __cdecl std::localtime(__int64 const * const)" (?localtime@std@@YAPEAUtm@@QEB_J@Z::<!std>) 已经在 std.ixx.ifc.obj 中定义
std.ixx.ifc.obj : error LNK2005: "__int64 __cdecl std::mktime(struct tm * const)" (?mktime@std@@YA_JQEAUtm@@@Z::<!std>) 已经在 std.ixx.ifc.obj 中定义
std.ixx.ifc.obj : error LNK2005: "__int64 __cdecl std::time(__int64 * const)" (?time@std@@YA_JQEA_J@Z::<!std>) 已经在 std.ixx.ifc.obj 中定义
std.ixx.ifc.obj : error LNK2005: "int __cdecl std::timespec_get(struct timespec * const,int)" (?timespec_get@std@@YAHQEAUtimespec@@H@Z::<!std>) 已经在 std.ixx.ifc.obj 中定义
build\windows\x64\debug\bin.exe : fatal error LNK1169: 找到一个或多个多重定义的符号"
</pre>

**Comment by waruqi** [comment]
再试试 

```
xmake update -s dev
```

记得先清下缓存

**Comment by hackermdch** [comment]
好，没问题了
