### ISSUE TITLE
add_defines()路径的分隔符在Windows环境下有转义字符冲突

### ISSUE THREAD

**Issue by GustafXTT** [xmake-io/xmake#3464]
### Xmake 版本

2.7.7

### 操作系统版本和架构

Win 11 22621.1344

### 描述问题

在xmake.lua中使用`add_defines("PROJECTDIR=\"$(projectdir)\"")`
相当于：`#define PROJECTDIR "C:\Users\someone\codeFolder\testProject"`
在上面的字符串中：\U、\s、\c、\t均会被认为是转义字符

### 期待的结果

add_define()在Windows下使用双反斜杠分隔路径
期望结果：`#define PROJECTDIR "C:\\Users\\someone\\codeFolder\\testProject"`

**Comment by waruqi** [comment]
`$(projectdir)` 返回的就是常规路径字符串，它又不知道你外面还去自己搞了个 `""` ，当然没法自动转义，你既然外面额外加了 ""，就需要去自己处理转义，那就不能用 `$(projectdir)`。。自己取下 os.projectdir() 然后，自己走 lua string gsub 自己处理下转义，改成 `\\` 。。或者改成 `/`

**Comment by GustafXTT** [comment]
请问像是`ofstream.open(PROJECTDIR "text.txt)`这种传一个路径字符串进去的只能用os.projectdir()自己改吗
我看cmake的add_definitions()可以在里面用""符号扩起来直接返回一串字符串用在代码里

**Comment by waruqi** [comment]
自己转下不就好了么，一句话的事情，又不复杂。。

```
add_defines("PROJECTDIR=\"" .. (os.projectdir():gsub("\\", "\\\\")) .. "\"")
```

```
add_defines("PROJECTDIR=\"" .. (os.projectdir():gsub("\\", "/")) .. "\"")
```
