### ISSUE TITLE
更新後，在 xmake install 的時候，自定義參數的傳入，失敗了。

### ISSUE THREAD

**Issue by orzuk-lmj** [xmake-io/xmake#347]
- 為了隱藏一些私有開發過程中的除錯訊息，會自定義 option 且希望能在 on_install 的時候使用它
    ``` lua
    option("detail")
        set_default(false)
        set_showmenu(true)
        set_description("show detail messages")
    option_end()
    ```

- 更新後出錯： 
    ``` bash
    xmake install --verbose --detail=true --all -o "%INSTALL_DIR%"
    ```
- 錯誤訊息為：
    ```
    error: invalid option: --detail=true
    ```

**Comment by waruqi** [comment]
这块我晚上看看，最近更新改动了不少，可能受影响了，不过问题不大，等我之后修下就好

另外对于获取详细的错误信息，xmake有提供原生选项`-D`/`--diagnosis`，没必要自己单独加个

目前xmake控制输出，有三个level的，你可以自由选择通过那个option来处理，通过`option.get("xxx")`都是可以直接获取到的

- `-q`/`--quiet`:  静默输出，不输出任何东西
- `-v`/`--verbose`: 详细输出，输出结果对用户友好，仅提供一些用户需要的详细信息，比如：详细编译选项，详细检测信息等
- `-D`/`--diagnosis`:  诊断输出，输出结果信息最大化，但是显示上不保证对用户友好，因为不是给用户使用的，仅对xmake开发者、xmake.lua的编写者开放、如果用户需要调试自定义脚本，也可以在里面自己加入一些对自己可读的调试信息

例如：

```lua
on_install(function (target)
    import("core.base.option")
    if option.get("diagnosis") then
        print("debug info")
    end
end)
```

```console
$ xmake install -D
```

或者直接用dprint接口（而vprint对应verbose），更加简单：


```lua
on_install(function (target)
    dprint("debug info")
end)
```

**Comment by orzuk-lmj** [comment]
> 另外对于获取详细的错误信息，xmake有提供原生选项`-D`/`--diagnosis`，没必要自己单独加个
> 
> 目前xmake控制输出，有三个level的，你可以自由选择通过那个option来处理，通过`option.get("xxx")`都是可以直接获取到的

- xmake假若稱為第一方，它作為軟件的底層機制，管控編譯流程；我們這些研發庫給其他人使用的先簡單稱為第二方；那麼使用我們發佈出去的庫的其他人稱為第三方好了。
- 三方各自所需要專注看到的焦點不一樣。
- 作為第二方的我們，需要知道在使用xmake時候，自己到底哪邊寫錯了，又或是定位出BUG回報給第一方。
  * 這時候會需要看到一些自己寫出的除錯訊息，自己在寫code過程也希望能看到 call stack ，所以開啟了 -v -D 。
  * 但是像 add_cincludes 這類檢查失敗，在開啟了-D的時候會打印出大量的雜訊干擾，這種時候大量的檢查失敗應該要有辦法被過濾掉，因為這種對我們來說不能稱為真正的錯誤，這是現階段使用上的麻煩。
  * 有些訊息又不希望讓第三方預設看到，可是自己在研發過程卻又需要看到，所以添加了 option("detail") 開關，預設開著。
- 作為第三方的同事們，為了讓他們盡可能的簡單使用，不需要把大量精力放在編譯環境的建置，他們僅需要在出錯的時候，把打印出來足夠清楚的訊息回報給我們；所以解決方案會盡可能的先做更完善的前置檢查還有防呆機制。
  * 預設不需要看到 call stack ，且不需要看到第二方的研發中除錯訊息。所以會關閉 -D，僅保留 -v，方便獲得相對完整的 xmake 訊息。

**Comment by waruqi** [comment]
目前对第三方使用-v就可以了，对第一方使用-v -D，这也是当初的设计，而对于第二方，当初考虑到也是开发者，我就假定能够自己过滤-D中自己所需的信息，所以目前没有特定level log提供，可以直接使用-v -D

如果觉得输出的冗余信息太多，可以通过 -v + 自定义detail选项来打印，也就是你现在用的方式。。

不过 你确定，之前老版本，`xmake install --verbose --detail=true --all -o "%INSTALL_DIR%"`
这样是ok的？

自定义option选项，是给配置命令使用的，`xmake f --xxx=xx`， 对于其他action，例如install/uninstall/run什么的，没法直接后面追加自定义选项的，以前的版本也不支持

你只能这样操作：

```console
$ xmake f --detail=y
$ xmake install -v --all -o "%INSTALL_DIR%"
```

**Comment by waruqi** [comment]
不过对于-v的输出，我可以改进下，如果是编译错误，仅显示编译错误详细信息，也就是目前的行为

对于脚本错误，仅显示最关键的完整栈，忽略检测信息中的栈信息

这样的话，一般情况下，对于第一方，第二方只需要开启-v就行了，-D仅给第一方使用

其他第二方自定义的调试输出，还是可以用你现在的方式，自定义一个选项来控制或者用环境变量控制

**Comment by orzuk-lmj** [comment]
> 不过 你确定，之前老版本，`xmake install --verbose --detail=true --all -o "%INSTALL_DIR%"`
> 这样是ok的？

抱歉，回頭仔細看了一下後發現是自己記錯，這個問題我先關閉好了。
