### ISSUE TITLE
linux ppa install的不是最新版本的xmake

### ISSUE THREAD

**Issue by Dozingfiretruck** [xmake-io/xmake#3472]
### Xmake 版本

2.7.6

### 操作系统版本和架构

ubuntu

### 描述问题

linux ppa install的不是最新版本的xmake

### 期待的结果

linux ppa install的为最新版本的xmake

**Comment by waruqi** [comment]
建议走官网一键脚本安装，也是推荐方式，ppa 目前 ci 自动上传失效了，暂时没时间看

而且 ppa 安装，不支持 xmake update 以及 command complete

**Comment by Dozingfiretruck** [comment]
> 建议走官网一键脚本安装，也是推荐方式，ppa 目前 ci 自动上传失效了，暂时没时间看
> 
> 而且 ppa 安装，不支持 xmake update 以及 command complete

你好，脚本方式我测试会报
![image](https://user-images.githubusercontent.com/24759100/223309415-df05bc75-af9e-4509-9f50-afdc052b83ec.png)
请问是什么原因？

**Comment by Dozingfiretruck** [comment]
> 

使用的 Ubuntu22.04.2 LTS测试

**Comment by waruqi** [comment]
你参考下源码编译：https://xmake.io/#/zh-cn/guide/installation?id=%e6%ba%90%e7%a0%81%e7%bc%96%e8%af%91%e5%ae%89%e8%a3%85

然后自己排查下生成的 makefile ，看哪里带 -e 命令导致。。

我这边 ubuntu 22.10 测试可以

**Comment by Dozingfiretruck** [comment]
> 

![image](https://user-images.githubusercontent.com/24759100/223316533-0052c5db-428a-438b-bb00-c976b6f5bc74.png)
你好，自己尝试编译报这个

**Comment by Dozingfiretruck** [comment]
> 你参考下源码编译：https://xmake.io/#/zh-cn/guide/installation?id=%e6%ba%90%e7%a0%81%e7%bc%96%e8%af%91%e5%ae%89%e8%a3%85
> 
> 然后自己排查下生成的 makefile ，看哪里带 -e 命令导致。。
> 
> 我这边 ubuntu 22.10 测试可以

自己编译一切正常，这就奇怪了

**Comment by waruqi** [comment]
切到 2.7.7的 tag 呢

**Comment by Dozingfiretruck** [comment]
> 切到 2.7.7的 tag 呢

我的环境不晓得出了什么问题，重装ubuntu虚拟机之后正常了

**Comment by waruqi** [comment]
ppa 我更新修复了，是因为 tar 打包格式后来调整过，导致 ppa 打包失败了。。
