### ISSUE TITLE
Can not install vcpkg::xxx

### ISSUE THREAD

**Issue by shaqtsui** [xmake-io/xmake#3474]
### Xmake Version

2.7.6

### Operating System Version and Architecture

Windows 11 with WSL1

### Describe Bug

Install `vcpkg::spdlog` raise error:  `cannot runv(D:\shaq\Projects\vcpkg\vcpkg install spdlog:x64-windows-static), Unknown`
I looked inside the code seems that it's due to that:
There are 2 executables in side `VCPKG_ROOT` : vcpkg & vcpkg.exe.
if invoke vcpkg, it will be execute it inside wsl(in this case, there will be no result returned to invoker). 
if invoke vcpkg.exe, it will be executed inside windows. 
`find_program()` returns vcpkg instead of vcpkg.exe in windows.  

### Expected Behavior

Success install vcpkg::xxx in windows with wsl1

**Comment by waruqi** [comment]
Shouldn't the system running in WSL1 be linux? Why would it install windows libraries?

**Comment by shaqtsui** [comment]
Sorry for inaccurate description. 
I am working in windows, but this windows have wsl installed. 
I am not working in wsl.

**Comment by waruqi** [comment]
try this patch https://github.com/xmake-io/xmake/pull/3476

**Comment by shaqtsui** [comment]
Tested OK in my local.
