### ISSUE TITLE
package linkdir missing

### ISSUE THREAD

**Issue by shaqtsui** [xmake-io/xmake#3478]
### Xmake Version

2.7.6

### Operating System Version and Architecture

Ubuntu 20.04

### Describe Bug

When package config with `add_linkdirs` & `add_links` to avoid default detection.
Some linkdirs missed when no corresponding lib specified via `add_links`.
Which means, If I didn't specify any lib via `add_links`, the corresponding linkdir got removed.

I think this havior is incorrest as:
windows may declare link in source via `#pragma comment(lib, "XXX.lib")`, which reply on `add_linkdirs` config. 

### Expected Behavior

`add_linkdirs` avialable even no corresponding lib specified via `add_link`

### Project Configuration

```
package("windows_kit")
    set_description("The windows kit package")

    add_urls("http://test/sdk/windows_kit_10.0.20348.tar.gz")
    add_versions("10.0.20348", "51be7513996d5eecc4b450697347abdbbc468e2f193cf69acb4da63ab6c606da")

    add_includedirs("Include/10.0.20348.0/shared", "Include/10.0.20348.0/ucrt", "Include/10.0.20348.0/um")
    add_linkdirs("Lib/10.0.20348.0/ucrt/x64", "Lib/10.0.20348.0/um/x64")
    -- avoid defaut link
    add_links("")

    on_install(function (package)
          os.mv("*", package:installdir())
    end)
    ```

**Comment by waruqi** [comment]
If you make it a package, do not use `#pragma comment`, you should always use add_linkdirs/add_links to specify the library links.

You can disable `#pragma comment` with add_patches

**Comment by shaqtsui** [comment]
It's 3rd part library, I hope to keep source untouched. 
Can I know the reason, that `#pragma comment` MUST be repaced by explicit `add_link`?

**Comment by waruqi** [comment]
This is the xmake package specification, and using `pragram comment` breaks a lot of things. Cannot export libraries. Cannot distinguish static libraries from dynamic libraries. Other packages that depend on it don't automatically get the link information, etc.

xmake will not consider supporting it.

**Comment by shaqtsui** [comment]
Got it, thanks. 
Any tools/api in xmake can help on this replacement?

**Comment by waruqi** [comment]
> Got it, thanks. Any tools/api in xmake can help on this replacement?

add_patches or io.replace

you can refer some packages in xmake-repo

**Comment by shaqtsui** [comment]
Thx.
