### ISSUE TITLE
package test failed when call has_cxxfuncs()

### ISSUE THREAD

**Issue by shaqtsui** [xmake-io/xmake#3488]
### Xmake Version

2.7.7

### Operating System Version and Architecture

Ubuntu 20.04

### Describe Bug

A lot of packages use `has_cxxfuncs()` to test packages. 
The impl of `has_cxxfuncs` invoke `sandbox_core_tool_compiler.load(sourcekind, opt):compile(sourcefiles, objectfile, opt)`.
But that compiler cannot find sdk headers(e.g. #include <atomic>) when I perform cross compilation via llvm.

### Expected Behavior

has_cxxfuncs run successfully

### Project Configuration

```
-- contains msvc windows kit
add_repositories "myrepo https://test/cpp-repo.git"

if os.host() == "linux" then
  ------------ sdk ------------
  set_config("sdk", "/usr/local")

  -- sdk toolchain
  set_toolchains "llvm"
  set_defaultplat "windows"
  add_requires("msvc", "windows_kit")
  add_packages("msvc", "windows_kit")
  ------------ sdk end ------------
end

add_requires "spdlog"

target "test"
set_languages "c++20"
add_defines("_UNICODE", "UNICODE")
add_defines("_WIN32", "_AFXDLL", "_WINDOWS")
add_defines("SPDLOG_USE_STD_FORMAT")
add_files "src/*.cpp"
```

### Additional Information and Error Logs

```
/home/shaq/.xmake/packages/s/spdlog/v1.11.0/4b75562d880f41e796ba90ae99029422/include/spdlog/details/null_mutex.h:6:10: fatal error: 'atomic' file not found
#include <atomic>
         ^~~~~~~~
1 error generated.
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:913]:
    [@programdir/modules/core/tools/gcc.lua:718]: in function 'catch'
    [@programdir/core/sandbox/modules/try.lua:123]: in function 'try'
    [@programdir/modules/core/tools/gcc.lua:659]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [...amdir/core/sandbox/modules/import/core/tool/compiler.lua:82]: in function 'compile'
    [@programdir/modules/lib/detect/check_cxsnippets.lua:218]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:117]: in function 'try'
    [@programdir/modules/lib/detect/check_cxsnippets.lua:212]:
    [...make/repositories/xmake-repo/packages/s/spdlog/xmake.lua:68]: in function 'script'
    [...dir/modules/private/action/require/impl/utils/filter.lua:125]: in function 'call'
    [...dir/modules/private/action/require/impl/actions/test.lua:41]:
    [.../modules/private/action/require/impl/actions/install.lua:366]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:117]: in function 'try'
    [.../modules/private/action/require/impl/actions/install.lua:287]:
    [...modules/private/action/require/impl/install_packages.lua:479]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:232]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:117]: in function 'try'
    [@programdir/modules/private/async/runjobs.lua:218]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:404]:
```

**Comment by waruqi** [comment]
If you want to compile packages for the windows platform, you can only use the default msvc toolchain on windows.

If you want to cross-compile or switch toolchains to compile packages, you have to switch to the cross platform. And make sure that the required packages support the cross platform.

Or you can use the mingw platform and toolchain to compile them.

**Comment by shaqtsui** [comment]
I am compiling windows application in my linux env. And I am using llvm toolchain + msvc abi/std libraries.

Base on:
```
  set_config("sdk", "/usr/local")
  set_toolchains "llvm"
  set_defaultplat "windows"
```
I tink I have configed cross compile toolchain via llvm(I don't use mingw to avoid multiple installation for different target platform)

The thing is that these corss compile works pretty well when I am depends on all packages which have no `has_cxxfuncs()` invocation.

**Comment by waruqi** [comment]
> set_defaultplat "windows"

it is only for msvc on windows. you should use `cross` platform.

**Comment by shaqtsui** [comment]
I have check the llvm toolchain related source code:
As I know `-target x86_64-pc-windows-msvc` is the flag for cross compile windows target. 
It requires `toolchain:is_plat("windows")`. Thats why I put `set_defaultplat "windows"` instead of `set_defaultplat "cross"`.
![image](https://user-images.githubusercontent.com/4743082/224203383-3417df93-0087-4545-a3ef-9391d5cb24aa.png)

**Comment by waruqi** [comment]
Not just this one place, windows and msvc are deeply bound so that good optimisations can be made for windows packages, such as pre-compiled package support, and rigorous testing of various configuration permutations such as vs_runtime/static/shared on the ci. Various patches are also added to each package to support msvc.

As a result, xmake does not allow switching between toolchains on the windows platform, which adds more uncertainty to all the windows packages on xmake-repo than I have to maintain, and makes the package configuration script more complex, as it has to do various specific patches on the windows platform for different toolchains.

Also, xmake currently only passes toolchain information to the internal build scripts for the cross platform.

So, please don't switch toolchains on windows. If you have to do so, I will not do anything to support it.

**Comment by shaqtsui** [comment]
So the toolchain config (e.g. `xmake f --syslinks`) will not pass to 3rd part package(added via `add_requires`) build.
3rd part package build is completely encapsulated in it's own package script. 
Package user can only do limited config which exposed by package mantainer.
Am I right?

**Comment by waruqi** [comment]
???

only pass `--toolchains`/`set_toolchains` to packages for `cross` platform (`-p cross`).

`--syslinks` is always not passed to packages, whether cross-compiled or not. Package builds are completely independent from the current project build.

**Comment by shaqtsui** [comment]
Toolchain, which can be specified by `--toolchains`, is used by both project targets & deps package build.
While project level config, e.g. `--syslinks` is only used by project targets.
So if I need to switch `compiler runtime library`, `cpp runtime library`, `cpp std library`, I need to config them individually for project targets & deps package.

**Comment by shaqtsui** [comment]
I sorry for the misleading. 
I  take configuration of `compiler runtime library`, `cpp runtime library`, `cpp std library` as sdk level config. 
sdk = toolchain + `compiler runtime library`, `cpp runtime library`, `cpp std library` 
Something, I mix phrasing sdk & toolchain.

**Comment by waruqi** [comment]
? No matter how you do it, you must use the `-p cross` platform whenever you use the cross-compilation toolchain.

**Comment by shaqtsui** [comment]
Ok, got it.
