### ISSUE TITLE
設置 yasm 的時候，錯誤訊息難以識別

### ISSUE THREAD

**Issue by orzuk-lmj** [xmake-io/xmake#349]
彙編錯誤的時候看起來長得像是：
```
error: Tools\xmake\bin/core/base/os.lua:705: Tools\xmake\bin/core/base/os.lua:705: 
Tools\xmake\bin/core/base/os.lua:705: Tools\xmake\bin/core/base/os.lua:705: 
runv(yasm -Ilib -D__platform_mingw__ -D__config_i386__ -D__config_debug__ -DDEBUG -D_DEBUG -I../inc -m32 -o ..\_build\.objs\vpx\mingw\i386\debug\lib\vp8\common\x86\idctllm_sse2.asm.obj lib\vp8\common\x86\idctllm_sse2.asm) failed(-1)!
```
- 訊息只有很簡單的  failed(-1) 實在難以識別到底哪裡出錯了
- 另外疑惑的是在 mingw 的時候，貌似會連同 -m32 也傳給 yasm 當參數，這樣正確嗎?

**Comment by waruqi** [comment]
> 另外疑惑的是在 mingw 的時候，貌似會連同 -m32 也傳給 yasm 當參數，這樣正確嗎?

这个我刚修复了，dev分支上

> 訊息只有很簡單的  failed(-1) 實在難以識別到底哪裡出錯了

yasm的编译错误输出，我暂时压制了，之前支持的时候，没时间细弄，忘记开放输出了，明天我改进下就好，今天太晚了。。

**Comment by waruqi** [comment]
> 訊息只有很簡單的 failed(-1) 實在難以識別到底哪裡出錯了

我看了下，编译输出之前也是已经有的，只是warnings信息被压制了，这个我dev刚加上了，可以通过 -w/-D 显示出来

而你这的failed问题，应该是 运行yasm 没找到这个程序，所以连错误信息都没有，因为根本没运行起来。。

你先确认下，path环境是否能够正常运行到yasm，或者可以先 手动配置下 绝对路径试试。。`xmake f --as=c:\yasm.exe`

**Comment by orzuk-lmj** [comment]
- yasm.exe 目錄路徑已經設置在 PATH 中，開啟cmd 使用 yasm --version 確認可執行。
- 直接設置 as = 絕對路徑之後就可以了，但這樣貌似有些麻煩

**Comment by waruqi** [comment]
> 直接設置 as = 絕對路徑之後就可以了，但這樣貌似有些麻煩，若PATH能直接找的到，能否只設置 `set_tools({as = "yasm"})`

我这边测试path存在后，`xmake f --as=yasm` 和 `set_tools({as = "yasm"})` 都是能够正常处理的，并没问题。

**Comment by orzuk-lmj** [comment]
我的環境是這樣：
```
Microsoft Windows [版本 10.0.17134.523]
(c) 2018 Microsoft Corporation. 著作權所有，並保留一切權利。

C:\Users\localuser>yasm --version
yasm 1.3.0
Compiled on Aug 17 2014.
Copyright (c) 2001-2014 Peter Johnson and other Yasm developers.
Run yasm --license for licensing overview and summary.

C:\Users\localuser>
```
- 我只是簡單把 yasm.exe 先隨便塞到一個 PATH 內已存在的路徑內

**Comment by waruqi** [comment]
那我也不清楚了，我这边都ok，你可以单独执行os.run或者os.exec试试

```console
$ xmake l
$ os.exec("yasm --version")
```

或者单独编译那个文件试试

```console
$ os.exec("yasm flags xxx.asm")
```

**Comment by orzuk-lmj** [comment]
> 
> 
> 那我也不清楚了，我这边都ok，你可以单独执行os.run或者os.exec试试
> 
> ```
> $ xmake l
> $ os.exec("yasm --version")
> ```
> 
> 或者单独编译那个文件试试
> 
> ```
> $ os.exec("yasm flags xxx.asm")
> ```

定位出問題了，xmake 運行時多少有些不同於 windows 提供的 cmd 取環境變數的方式吧，所以我之前每次用cmd檢查PATH和yam都很正常，估計cmd每次啟動都會刷新環境變數。但是對於XMAKE來說，貌似我在win10底下需要`重啟電腦`後才能讀取到正確值。

**Comment by waruqi** [comment]
你可以执行 xmake l os.getenv PATH 来查看当前path，xmake用的也是win api获取的env path

我这边之前测试，也是直接 cmd set PATH直接改的，可以立马生效，系统path修改。

我在win10下也测过，改完系统path后， 重新打开个 cmd 再获取path，xmake也能立马获取到

**Comment by orzuk-lmj** [comment]
非常感謝，現在 yasm 和錯誤訊息都可以正常了，至於改PATH 沒辦法即使可用，我也不確定為什麼，但重開機就可以解決，也算是簡單的方法，先關閉好了，有新消息我再回報。
