### ISSUE TITLE
add an optional internal project name for cmake find_package

### ISSUE THREAD

**Issue by RichardYCJ** [xmake-io/xmake#3492]
### Is your feature request related to a problem? Please describe.

I'm using xmake to find an external third-party with cmake suppot. The library is called `deal.II` but within the `deal.IIConfig.cmake`  file, all variable names start with `DEAL_II` like:

```cmake
SET(DEAL_II_PACKAGE_NAME "deal.II")
SET(DEAL_II_INCLUDE_DIRS ...)
```

However the offered `find_package` module could not detect the actual link and include path
https://github.com/xmake-io/xmake/blob/43908d7c753b6502cf1f2f589cbc52b508738347/xmake/modules/package/manager/cmake/find_package.lua#L84-L93

### Describe the solution you'd like

If possible, please consider to add an extra optional `config_name` to `add_requires`  interface. And the `_find_package` function should be:

```lua
local config_name = opt.config_name or name
cmakefile:print("   target_include_directories(%s PRIVATE ${%s_INCLUDE_DIR} ${%s_INCLUDE_DIRS})", 
    testname, config_name, config_name) 
cmakefile:print("   target_include_directories(%s PRIVATE ${%s_INCLUDE_DIR} ${%s_INCLUDE_DIRS})", 
    testname, config_name:upper(), config_name:upper())
```

And the use of the interface should look like:

```lua
-- library that use an extra config name
add_requires("cmake::deal.II", {configs = {system = true, config_name = "DEAL_II"}})
-- library that work as before
add_requires("cmake::ZLIB")
```

### Describe alternatives you've considered

My current workaround is to create a `deal_II` directory and copy all `deal.IIConfig...` files, rename them as `deal_IIConfig...`. While using xmake, use `deal_II` as the library name:

```
add_requires("cmake::deal_II")
```

**Comment by RichardYCJ** [comment]
BTW, is there a preferred way to **distinguish an external cmake library between debug and release mode** (if built in `ReleaseDebug` mode)? or just use different `CMAKE_BUILD_TYPE` like:

```lua
if is_mode("debug") then
    add_requires("cmake::deal.II", {configs = {envs = {CMAKE_BUILD_TYPE = "Debug"}}})
elseif is_mode("release") then
    add_requires("cmake::deal.II", {configs = {envs = {CMAKE_BUILD_TYPE = "Release"}}})
end
```

**Comment by waruqi** [comment]
> If possible, please consider to add an extra optional config_name to add_requires interface. And the _find_package function should be:

you can open a pr.

**Comment by waruqi** [comment]
> BTW, is there a preferred way to **distinguish an external cmake library between debug and release mode** (if built in `ReleaseDebug` mode)? or just use different `CMAKE_BUILD_TYPE` like:
> 
> ```lua
> if is_mode("debug") then
>     add_requires("cmake::deal.II", {configs = {envs = {CMAKE_BUILD_TYPE = "Debug"}}})
> elseif is_mode("release") then
>     add_requires("cmake::deal.II", {configs = {envs = {CMAKE_BUILD_TYPE = "Release"}}})
> end
> ```

```
add_requires("cmake::deal.II", {configs = {debug = is_mode("debug")})
```

**Comment by RichardYCJ** [comment]
> > If possible, please consider to add an extra optional config_name to add_requires interface. And the _find_package function should be:
> 
> you can open a pr.

Sure, do you think `config_name` is ok or you have a better name?

As to the second debug/release problem. I'm not sure if `is_mode` can be used in script domain and should the default value to be the actaul mode in xmake or just `false` by default? Please give some more detailed discussion on it.

I will open a PR in draft and see if I could work it out.

**Comment by waruqi** [comment]
> Sure, do you think config_name is ok or you have a better name?

I can't think of a better name, but you can start with config_name. 

you can add it in https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/manager/cmake/configurations.lua

@xq114 @SirLynix any idea?

> As to the second debug/release problem. I'm not sure if is_mode can be used in script domain and should the default value to be the actaul mode in xmake or just false by default? Please give some more detailed discussion on it.

debug is builtin configuration, you can get it from `opt` argument.

```lua
add_requires("cmake::deal.II", {configs = {debug = is_mode("debug")})
function _find_package(cmake, name, opt)
    if opt.mode == "debug" then
    end
```

**Comment by SirLynix** [comment]
I'd say `build_type` would be a better name, as it's how it's called in cmake doc: https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html

**Comment by waruqi** [comment]
> https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html

We're not talking about build mode, but about parsing `${config_name}_INCLUDE_DIRS` prefixes from configuration results.

**Comment by waruqi** [comment]
ok, maybe `find_name` will be better.

**Comment by xq114** [comment]
I think we can make it more flexible, without limit to the form of `${config_name}_INCLUDE_DIRS`. Currently the user can specify custom link libraries by setting `{link_libraries = "package::target"}`, but it can be used here in this scenario as well: `{link_libraries = "${DEAL_II_LIBRARIES}"}`. Similarly for include directories, we just need to add an interface `{include_directories = "${DEAL_II_INCLUDE_DIRS}"}`.

cmake didn't have a standard what variable should be provided in the config file xxxConfig.cmake. For xmake, I think we should support more kinds of variable besides the current form `${config_name}_INCLUDE_DIRS`

**Comment by xq114** [comment]
For CMAKE_BUILD_TYPE, it should not be specified here since it's a variable on the **build** stage instead of **find** stage. `add_requires("cmake::xxx")` only finds the package **as is**, not building the package from source (in that case you should create a xmake package). If you want to link the debug version, build the package with -DCMAKE_BUILD_TYPE=Debug and make sure the correct version is on your environment variable CMAKE_PREFIX_PATH.

**Comment by RichardYCJ** [comment]
Hi @xq114, some packages would build **both Release and Debug version sharing with the same config file** and cmake generates the link flags according to the variable `CMAKE_BUILD_TYPE`. According to this [cmake official ref](https://cmake.org/cmake/help/latest/command/target_link_libraries.html#overview), in the final point of overview, this kind of behavior is also supported.

Besides, **build type**, IMO, should also be one of the specifiers of the **installed libraries**, just like what you said:
> If you want to link the debug version, build the package with -DCMAKE_BUILD_TYPE=Debug and make sure the correct version is on your environment variable CMAKE_PREFIX_PATH.

Isn't use different `CMAKE_PREFIX_PATH` to link libraries equivalent to use different `CMAKE_BUILD_TYPE`?

**Comment by RichardYCJ** [comment]
> Currently the user can specify custom link libraries by setting `{link_libraries = "package::target"}`

This true, for libraries who provides different targets, we could use `link_libraries` to separate the flags but some libraries may not. I'm not sure whether cmake has such policy to ensure the target generation?

> Similarly for include directories, we just need to add an interface `{include_directories = "${DEAL_II_INCLUDE_DIRS}"}`.

That's a clever idea! We just need to pass raw string like `"${DEAL_II_INCLUDE_DIRS}"` to generate the same code. Though it's a little hard for people not familiar with cmake. What do you guys think? @waruqi @SirLynix

**Comment by waruqi** [comment]
> That's a clever idea! We just need to pass raw string like to generate the same code. Though it's a little hard for people not familiar with cmake. What do you guys think? @waruqi @SirLynix"${DEAL_II_INCLUDE_DIRS}"

I think it's a good idea, it's more flexible. it may be better than `${find_name}_INCLUDE_DIRS`
