### ISSUE TITLE
support xmake run command on non binary target if on_run exists

### ISSUE THREAD

**Issue by iAndyHD3** [xmake-io/xmake#3495]
### Is your feature request related to a problem? Please describe.

if there is no binary target and the default target is of kind shared, there is currently no way to invoke the `on_run` function by using `xmake run`, of course this can easily be fixed by running the specific target like this `xmake run [target name]`, however I find this kind of annoying and less attractive, especially because the target name is the end file name (`.dll`...)

### Describe the solution you'd like

When running `xmake run`, if a binary target does not exist, xmake could look for `on_run` functions in other targets. additionally it could start looking at targets which were set default with [target:set_default](https://xmake.io/#/manual/project_target?id=targetset_default)

### Describe alternatives you've considered

making a placeholder binary target with the on_run function, which is obviously a pretty bad solution

### Additional context

I'm making a modding template, of course the default target being a windows shared library (`.dll` file). I added options and wrote a custom `on_run` function that automatically copies the dll and starts the executable

**Comment by waruqi** [comment]
see https://github.com/xmake-io/xmake/pull/3496

```
xmake update -s github:xmake-io/xmake#run
```

```
target("test")
    set_kind("shared")
    on_run(function (target)
        print("run")
    end)
```
