### ISSUE TITLE
`xmake check clang.tidy` not work when pch configed

### ISSUE THREAD

**Issue by shaqtsui** [xmake-io/xmake#3499]
### Xmake Version

2.7.7

### Operating System Version and Architecture

Ubuntu 20.04

### Describe Bug

`xmake check clang.tidy` not work when pch configed via `set_pcxxheader "src/pch.h"`
I did a basic explore, maybe root cause is that:
`pch.h` is implicitly included in source, but corresponding `pch.h.pch` need a build to generate. 
`xmake check clang.tidy` doesn't build `pch.h.pch` before delegate to clang-tidy

### Expected Behavior

`xmake check clang.tidy`  work when pch configed via `set_pcxxheader "src/pch.h"`

### Project Configuration

```
target "ccexample"
set_pcxxheader "src/pch.h"
add_files "src/*.cpp"
```

**Comment by waruqi** [comment]
you need also include it explicitly.

https://github.com/xmake-io/xmake/blob/7ce8680f4288e3c1fa7c51c4a23ca78d6a4853f6/tests/projects/c%2B%2B/precompiled_header/src/test.cpp#L3

**Comment by waruqi** [comment]
> I know this would resolve this issue. But not sure this is reasonable solution.

With set_pcxxheader, xmake always assumes that the user has explicitly included it himself, independent of clang-tidy.

**Comment by shaqtsui** [comment]
Got it.
