### ISSUE TITLE
在on_build 裡面有條件的添加移除原始碼

### ISSUE THREAD

**Issue by orzuk-lmj** [xmake-io/xmake#350]
- 目前已知 on_build 裡面使用 target:add("files", "src/xxx.c") 這種使用方式
- 若打算添加 "src/*.c" 這類的呢，現在貌似會有底下這種錯誤，該如何解決?
    ```
    warning: cannot match target(vpx).add_files("vp8/common/x86/*.c") at :-1
    warning: cannot match target(vpx).add_files("vp8/common/x86/*.asm") at :-1 
    ```
- 若打算在 on_build 內先判斷 arch == xxx 之後移除某些檔案，功能近似於 del_files 但需要有先判斷條件，該怎麼辦?  查了一下好像不存在 target:del(......) 這種接口。

**Comment by waruqi** [comment]
> 目前已知 on_build 裡面使用 target:add("files", "src/xxx.c") 這種使用方式

自定义on_build相当于重写内置的 build 逻辑了，这个时候改files后，也不会执行内置buil，除非你自己调用了opt.origin()脚本

另外建议动态改flags, files此类放在target.on_load阶段做。。

> 若打算添加 "src/*.c" 這類的呢，現在貌似會有底下這種錯誤，該如何解決?

脚本内部通过target:add()添加，比较原始，不会自动处理路径变换，你需要自己通过os.files去模式匹配文件，通过path.join去获取实际的文件绝对路径

```lua
target:add("files", os.files(path.join(os.projectdir(), "src/*.c")))
```

> 若打算在 on_build 內先判斷 arch == xxx 之後移除某些檔案，功能近似於 del_files 但需要有先判斷條件，該怎麼辦?  查了一下好像不存在 target:del(......) 這種接口。

 target:del还没实现，也不建议通过target:add去动态修改文件列表，尽量在xmake.lua的描述域直接添加

**Comment by orzuk-lmj** [comment]
回頭仔細看過了一次正在用的代碼，的確是on_load ，是我在這篇問題內寫錯了，目前使用 os.files 這種方法，但越到些小問題：
``` lua
target:add("files", os.files(path.join(os.projectdir(), "vp8/common/x86/*.c")))

error: xmake\bin/core/base/os.lua:705: xmake\bin/core/project/target.lua:1018: 
attempt to index local 'file' (a number value)
```

轉而使用稍微麻煩一些的語法才成功：
``` lua
for _, filepath in ipairs(os.files("$(scriptdir)/vp8/common/x86/*.c")) do
    target:add("files", filepath)
end
```

**Comment by waruqi** [comment]
`target:add("files", (os.files(path.join(os.projectdir(), "vp8/common/x86/*.c"))))` 试试， os.files外面在包个括号，因为os.files返回的是 filelists, filecount，后面有个count

**Comment by orzuk-lmj** [comment]
有機會的話，若可以用條件來控制源碼是否要被編譯，對於一些複雜的專案移植來說會比較方便，例如 libvpx / ffmpeg 在 windows 上的移植就是一個例子。。

**Comment by waruqi** [comment]
直接外面 if + add_files 控制不行吗？target:add 这块 我后面有时间改进下

**Comment by waruqi** [comment]
删除这块，可以到 https://github.com/xmake-io/xmake/issues/353 跟进

**Comment by waruqi** [comment]
这块我改进过了，见 https://github.com/xmake-io/xmake/issues/352#issuecomment-464559109
