### ISSUE TITLE
在 Windows 平台下对 Qt 项目使用 xmake install -o 报错

### ISSUE THREAD

**Issue by AngryAccelerated** [xmake-io/xmake#3505]
### Xmake 版本

2.7.7

### 操作系统版本和架构

Windows 11 22H2

### 描述问题

![-466bea8d6b9b9d8a](https://user-images.githubusercontent.com/13927622/225064209-04f9344d-3d71-44f3-a40f-3c306652a20c.jpg)
![21a12ea256df97c](https://user-images.githubusercontent.com/13927622/225064353-9ad75d6c-5efd-4121-a075-4e535d4c8835.jpg)
对 Qt 项目使用 xmake install -o 后出现报错，提示 [windows.lua](https://github.com/xmake-io/xmake/blob/master/xmake/rules/qt/install/windows.lua) 44 行处报错 attempt to index a nil value (local 'qt')
Qt 版本: 5.15.2 msvc2019

### 期待的结果

能够完成 windeployqt.exe 对二进制文件拷贝对应的 dll 文件

**Comment by waruqi** [comment]
更新到 dev 再试试，xmake update -s dev

**Comment by AngryAccelerated** [comment]
![Snipaste_2023-03-15_12-03-38](https://user-images.githubusercontent.com/13927622/225203542-f573bdd3-4202-409c-bd79-164985ff67c1.png)
![Snipaste_2023-03-15_12-04-39](https://user-images.githubusercontent.com/13927622/225203547-9c7f30fa-0964-4a34-ac6b-18c38ac0995b.png)
ok，问题解决了
