### ISSUE TITLE
xmake编译cmake工程，无法切换工具链

### ISSUE THREAD

**Issue by zt449569708** [xmake-io/xmake#3508]
### Xmake 版本

xmake v2.7.7+HEAD.da4fa35

### 操作系统版本和架构

aarch64 kylin V10 

### 描述问题

现在电脑上装了多个工具链，如自带的gcc、clang，还有其他厂商的clang工具，现在用其他厂商提供的clang去编译opencv4.6的时候，工具链切换不过去（不是交叉编译，就是在本机上运行的程序），如下：
![image](https://user-images.githubusercontent.com/6011216/225209116-4e77c0af-85aa-4db7-869b-20a8a2acdf0a.png)

### 期待的结果

能够切换工具链

**Comment by waruqi** [comment]
更新到 dev 再试试

xmake update -s dev

**Comment by zt449569708** [comment]
> 更新到 dev 再试试
> 
> xmake update -s dev

可以了，谢谢
