### ISSUE TITLE
xmake查找本地cmake包，无法找到头文件路径

### ISSUE THREAD

**Issue by zt449569708** [xmake-io/xmake#3514]
### Xmake 版本

xmake v2.7.7+HEAD.da4fa35

### 操作系统版本和架构

ubuntu20.04  x86_64

### 描述问题

应用场景：现在需要编译一个opencv写的代码，因此先编译了一个opencv的源码包，然后利用add_requires去添加这个opencv的cmake包进来，xmake.lua如下：
```
add_requires("cmake::OpenCV", {alias = "opencv", system = true,  
    configs = {envs = {CMAKE_PREFIX_PATH = "/root/workspace/test/opencv/build/artifacts"}}})

--add_includedirs("/root/workspace/test/opencv/build/artifacts/include/opencv4")

target("test")
    set_kind("binary")
    add_files("test.cpp")
    add_packages("opencv")
```
然后运行xmake -rwv，错误如下图：
![image](https://user-images.githubusercontent.com/6011216/225519673-31f8a1c8-316e-4284-a5e3-21f2da1af790.png)
从图片可以看出，是头文件的路径没找到。然后利用add_includedirs添加头文件路径，是可以编译成功的。所以就不清楚是没用对的问题，还是xmake解析xxx.cmake文件的问题。

### 期待的结果

能够编译成功

**Comment by waruqi** [comment]
你调下 https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/manager/cmake/find_package.lua

**Comment by zt449569708** [comment]
> 你调下 https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/manager/cmake/find_package.lua

调用后，找的是系统的自带的opencv包，如下：
![image](https://user-images.githubusercontent.com/6011216/225789165-3f01b574-5210-4b47-b28c-31fa431c5abf.png)
然后通过 xmake l find_package cmake::OpenCV {configs ={envs={CMAKE_PREFIX_PATH=xxxx}}} 这种方式去传参数没反应，无任何打印输出，所以应该是我传递参数的方式不对，因为对lua传参不是很熟悉，所以不知道怎么来调用。

**Comment by waruqi** [comment]
用 add_requires 写到 xmake.lua ，然后走 `xmake f -cvD` 来调试

**Comment by zt449569708** [comment]
> 用 add_requires 写到 xmake.lua ，然后走 `xmake f -cvD` 来调试

运行xmake f -cvD 输出如下：
[log.txt](https://github.com/xmake-io/xmake/files/10997529/log.txt)

**Comment by waruqi** [comment]
你自己加点 print 调下 https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/manager/cmake/find_package.lua ，看下为什么没解析到

**Comment by xq114** [comment]
很可能cmake安装opencv那一步就出错了，你可以贴一下opencvconfig.cmake文件，看看为什么会有//include/opencv4这种路径出现。

**Comment by zt449569708** [comment]
> 很可能cmake安装opencv那一步就出错了，你可以贴一下opencvconfig.cmake文件，看看为什么会有//include/opencv4这种路径出现。

是的，就是opencvconfig.cmake文件里面的OpenCV_INSTALL_PATH变量指向的路径不对导致的

**Comment by waruqi** [comment]
> 所以应该是xmake编译opencv自动添加的"-DCMAKE_INSTALL_LIBDIR="导致的问题。

我改了下，改成了 
> -DCMAKE_INSTALL_LIBDIR:PATH=lib

再试试

xmake update -s dev

**Comment by waruqi** [comment]
另外，你走 trybuild 模式编译，原本就是不可靠的。一些细节配置 不可能自动化处理，只能编译个大概。。

要想完全适配，得走 xmake-repo 仓库的 opencv 编译。。如果嫌下载慢。。可以不下载。。

你都拉到源码了，直接

```
cd opencv
xrepo install -d . opencv
```

指定当前 opencv 源码目录，编译安装包就行了。。

或者直接 opencv 源码目录执行 xmake

```
cd opencv
xmake
```

xmake 也会自动探测到 是 opencv 包，用 xmake-repo 仓库的 opencv 编译脚本去编译安装，比 trybuild 更可靠。

**Comment by zt449569708** [comment]
> 另外，你走 trybuild 模式编译，原本就是不可靠的。一些细节配置 不可能自动化处理，只能编译个大概。。
> 
> 要想完全适配，得走 xmake-repo 仓库的 opencv 编译。。如果嫌下载慢。。可以不下载。。
> 
> 你都拉到源码了，直接
> 
> ```
> cd opencv
> xrepo install -d . opencv
> ```
> 
> 指定当前 opencv 源码目录，编译安装包就行了。。
> 
> 或者直接 opencv 源码目录执行 xmake
> 
> ```
> cd opencv
> xmake
> ```
> 
> xmake 也会自动探测到 是 opencv 包，用 xmake-repo 仓库的 opencv 编译脚本去编译安装，比 trybuild 更可靠。

好的，以后就这样用，主要是开始不知道xrepo 可以指定本地路径，谢谢啊。

**Comment by zt449569708** [comment]
> > 所以应该是xmake编译opencv自动添加的"-DCMAKE_INSTALL_LIBDIR="导致的问题。
> 
> 我改了下，改成了
> 
> > -DCMAKE_INSTALL_LIBDIR:PATH=lib
> 
> 再试试
> 
> xmake update -s dev

可以了，谢谢。
