### ISSUE TITLE
請問如何在 option: 和 target: 中使用 set_configvar 

### ISSUE THREAD

**Issue by orzuk-lmj** [xmake-io/xmake#352]
- 打算用在 before_check / after_check / on_load 腳本中，原因是條件判斷複雜，貌似只好寫在這些地方。
- set_configvar 該如何轉化為 target:set("configvar", ....................)  這類的寫法?

**Comment by waruqi** [comment]
set_configvar 这种属于 key/value设置。。暂时target:set/option:set 还不支持，这块暂时还不完善，后面我会统一理下，包括对target:remove的支持。

你先等等吧。

**Comment by waruqi** [comment]
这块，我dev上也重构过了，对target/option内置的各种settings，会自动匹配器设置模式，完全跟外层的add_xxx 传参行为保持一致。。

例如：`target:add("files", "src/*.c")` 等价于 `add_files("src/*.c")`

并且我新增了`target:del("files", "src/*.c")`去删除指定文件，等价于 `del_files("src/*.c")`

而文件的排除模式，以及附带参数都跟add_files完全一致，`target:add("files", "src/*.c|test/*.c", {defines = "xxx"})`

**Comment by waruqi** [comment]
详细进展见：#353  这块是完全兼容之前的设置模式的，但由于这块我改动较大，如有其他附带问题，可反馈上来，我处理下。。
