### ISSUE TITLE
使用Windows Mingw gcc编译add_defines()传入的带双引号路径报错

### ISSUE THREAD

**Issue by GustafXTT** [xmake-io/xmake#3520]
### Xmake 版本

2.7.7

### 操作系统版本和架构

Win 11 22621.1413 gcc 11.3.0

### 描述问题

使用`add_defines("PROJECTDIR=\"" .. (os.projectdir():gsub("\\", "\\\\")) .. "\"")`后
在Windows平台使用mingw gcc编译的时候有找不到输入文件的报错
`xmake -v`后查看编译细节
```
gcc -c -m64 -g -O0 -std=c++17 -Iinclude -DPROJECTDIR=\"C:\\Users\\username\\codeFolder\\testProject\" -fexceptions -o build\.objs\testProject\windows\x64\debug\src\main.cpp.obj src\main.cpp
```
报错：`error: gcc: fatal: no input file`

删除`add_defines()`相关的`-DPROJECTDIR=\"C:\\Users\\username\\codeFolder\\testProject\"`路径字符串两边的转义字符`\"`变成`-DPROJECTDIR=C:\\Users\\username\\codeFolder\\testProject`后编译成功，但传入的内容不是双引号包裹的路径。
MSVC和clang与linux平台的gcc均无问题

### 期待的结果

顺利使用Windows Mingw gcc编译add_defines()，使其传入一个用双引号包裹的路径

### 工程配置

```
add_rules("mode.debug", "mode.release")

target("testProject")
    set_kind("binary")
    add_files("src/*.cpp")
    add_includedirs("/include")
    add_languages("c++17")
    set_optimize("none")
    add_toolchains("gcc")

    add_defines("PROJECTDIR=\"" .. (os.projectdir():gsub("\\", "\\\\")) .. "\"")
```

**Comment by waruqi** [comment]
不要用 gcc ，用 mingw gcc ,`set_toolchains` 删了，切 `xmake f -p mingw`

我这 ok

![image](https://user-images.githubusercontent.com/151335/225836654-6cc9920c-aa32-4130-b531-90b92a39d8e8.png)

**Comment by GustafXTT** [comment]
刚试了一下`/`路径，也是编译失败
更新msys2后mingw-w64-x86_64-gcc的版本从11.3.0升级到12.2.0，编译成功，并且也支持`\\`路径，怀疑是gcc在高版本中修复了这个问题

感谢指点
