### ISSUE TITLE
依赖安装结束后输出显示异常

### ISSUE THREAD

**Issue by RimuruChan** [xmake-io/xmake#3535]
### Xmake 版本

2.7.7

### 操作系统版本和架构

Windows 11 22H2

### 描述问题

![image](https://user-images.githubusercontent.com/42002296/226217713-8833a34d-b822-4f27-a579-4c3834e2a5f2.png)

如图，少了一个换行

### 期待的结果

正常换行

**Comment by waruqi** [comment]
这个是偶现的，我这边也遇到过，我稍微改进了下，你再试试

xmake update -s dev

**Comment by RimuruChan** [comment]
![image](https://user-images.githubusercontent.com/42002296/226230935-de9c60df-d9f7-4a8a-82be-02535d9a34d8.png)
测试后发现正常了
