### ISSUE TITLE
Add support for clang-tidy fixes

### ISSUE THREAD

**Issue by baepli-jhcs** [xmake-io/xmake#3537]
### Is your feature request related to a problem? Please describe.

It would be nice if we could get an option to use the clang-tidy --fix option when using xmake check clang.tidy. 

### Describe the solution you'd like

An option in xmake check clang.tidy to fix the source files.

### Describe alternatives you've considered

Perhaps having an optional list of arguments that we pass could work better.

**Comment by waruqi** [comment]
you can open a pr. https://github.com/xmake-io/xmake/blob/master/xmake/modules/private/check/checkers/clang/tidy.lua

**Comment by waruqi** [comment]
done. `xmake update -s dev`

```
xmake check clang.tidy --fix
xmake check clang.tidy --fix_errors
xmake check clang.tidy --fix_notes
```
