### ISSUE TITLE
卸载包后构建不会自动重新安装包

### ISSUE THREAD

**Issue by RimuruChan** [xmake-io/xmake#3542]
### Xmake 版本

2.7.7

### 操作系统版本和架构

Windows 11

### 描述问题

卸载包后重新构建应当重新要求用户安装包，而不是继续编译

### 期待的结果

先要求安装包，然后再编译

### 附加信息和错误日志

![image](https://user-images.githubusercontent.com/42002296/226598680-7f160057-a534-4206-96df-c2a73420e0be.png)

**Comment by RimuruChan** [comment]
卸载某个库后就会出现异常，除非重新configure

**Comment by RimuruChan** [comment]
![image](https://user-images.githubusercontent.com/42002296/226600850-9c06ad8d-5c13-4a02-a76f-7e0f9a13737d.png)
![image](https://user-images.githubusercontent.com/42002296/226600961-ea7f2de2-da3f-4775-82f8-6f744395ce18.png)
如图，卸载后info中依然存在，没有自动更新

**Comment by RimuruChan** [comment]
貌似可以通过 xmake f --check 来解决这个问题

**Comment by waruqi** [comment]
config 追加 -c
