### ISSUE TITLE
Can not set the default value of an option according to current platform

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#3543]
### Xmake 版本

2.7.7

### 操作系统版本和架构

windows 10

### 描述问题

无法根据platform设置option默认值

示例xmake.lua：
```lua
option("test")
    set_default(is_plat("windows"))
option_end()
print(has_config("test"))
target("testcpp")
    set_kind("binary")
    add_files("src/*.cpp")
```

输出结果：
```
> xmake f -c
nil
nil
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.35.32215
nil
nil
nil
nil
```

### 期待的结果

当前platform为windows时，option默认值正确被设置为true

**Comment by waruqi** [comment]
不支持，不要这么做。is_plat 取的 `xmake f -p xxx` 配置，option 定义的也是 `xmake f -xx` 配置，会有鸡生蛋问题。。

**Comment by xq114** [comment]
那怎么样实现根据平台选取默认值呢

**Comment by waruqi** [comment]
> 那怎么样实现根据平台选取默认值呢

不能，只能直接根据 get_config/is_plat 去判断配置 target，不能设置到 option/default

```lua
local is_test = get_config("test") or is_plat("windows")
if is_test then
end
```

**Comment by waruqi** [comment]
或者你可以在 option/on_check 里面判断，脚本域可以用 is_plat

```lua
option("test")
    before_check(function (opt)
        if is_plat("windows") then
            opt:enable(true)
        end
    end)
```

**Comment by xq114** [comment]
> 或者你可以在 option/on_check 里面判断，脚本域可以用 is_plat
> 
> ```lua
> option("test")
>     before_check(function (option)
>         if is_plat("windows") then
>             option:enable(true)
>         end
>     end)
> ```

这个方法可行
