### ISSUE TITLE
`xmake lua` action will execute `xmake.lua` once in the current directory

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#3544]
### Xmake 版本

2.7.7

### 操作系统版本和架构

windows 10

### 描述问题

当前运行`xmake lua xxx`指令的时候，会将当前目录的xmake.lua执行一遍，但不报错。这个行为是特意设计的吗？

目前xrepo env 虚拟环境依赖于xmake lua 命令来运行，但如果用户在当前目录的xmake.lua加入了全局print等不正确的语句，xrepo env 会直接报错且无法正常使用，尽管激活的是全局环境（python等）。

### 期待的结果

`xmake lua xxx`指令应该与当前目录有无xmake.lua、其内容如何完全无关。

**Comment by waruqi** [comment]
主要是 main 里面初始解析 menu option 时候，里面有一些脚本，也会去尝试加载 project xmake.lua 。。

比如解析 task 列表（project 里面定义的），tab 补全，等等，这些 menu 中的脚本执行过于早期。。不是在 xmake lua 里面的。。甚至连 当前执行的是哪个 task name 都还不确定。。没法去掉。。

**Comment by xq114** [comment]
那有没有办法抑制解析过程的输出呢？这样即使用户在xmake.lua里加了print，也不会破坏虚拟环境功能。现在的--quiet对xmake.lua里的print不生效

**Comment by waruqi** [comment]
--quiet 已经滞后了，解析时候 option 参数列表都还没提取出来

**Comment by waruqi** [comment]
> 那有没有办法抑制解析过程的输出呢？这样即使用户在xmake.lua里加了print，也不会破坏虚拟环境功能。现在的--quiet对xmake.lua里的print不生效

原本就不应该加 print ，除非自己在调试 api。。暂时没法抑制

**Comment by xq114** [comment]
那有没有办法检查xmake.lua是否会在解析时产生多余输出？例如xmake lua <phony script>，这样可以更精准地产生报错信息

**Comment by waruqi** [comment]
没有，那个阶段加载过早。。就算执行 `xmake --help` 也是会加载 xmake.lua 的。。

**Comment by xq114** [comment]
> 没有，那个阶段加载过早。。就算执行 `xmake --help` 也是会加载 xmake.lua 的。。

不是，我意思是xmake内部有没有不产生任何输出的命令或者lua模块？这样我在xrepo的script里面运行一下这个命令，检查输出是否为空就可以判断了。如果没有的话，只能生成一个空的lua文件来判断了

**Comment by waruqi** [comment]
> > 没有，那个阶段加载过早。。就算执行 `xmake --help` 也是会加载 xmake.lua 的。。
> 
> 不是，我意思是xmake内部有没有不产生任何输出的命令或者lua模块？这样我在xrepo的script里面运行一下这个命令，检查输出是否为空就可以判断了。如果没有的话，只能生成一个空的lua文件来判断了

api ？ 还是 命令参数？命令参数没有，`--quiet` 还没解析出来，就已经报错了。。

你再 xrepo 哪个 脚本里运行? 为啥要判空？是处理什么问题？

**Comment by xq114** [comment]
https://github.com/xmake-io/xmake/blob/fce2659ef7e3be32a19d474ea254c9407880cdbe/xmake/scripts/xrepo-hook.psm1#L27-L32

这里，如果项目里有print，获取prompt就会有问题。

> api ？ 还是 命令参数？命令参数没有，--quiet 还没解析出来，就已经报错了。。

就是一个命令，它本身不产生任何输出，可以是api或者命令参数，只有当用户xmake.lua写了print才会导致它有输出

**Comment by xq114** [comment]
我试了下，`xmake lua --quiet core.tool.toolchain`就可以，但不知道有没有更适合的语句

**Comment by waruqi** [comment]
> 这里，如果项目里有print，获取prompt就会有问题。

那就用 `--quiet` 呗
