### ISSUE TITLE
Windows Clang toolchain尚未支持set_runtime

### ISSUE THREAD

**Issue by MaxwellGengYF** [xmake-io/xmake#3546]
### 你在什么场景下需要该功能？

Windows平台使用--toolchain=clang

### 描述可能的解决方案

set_runtime在Windows Clang应该得到支持，具体目前替代方案是
MT:
add_cxflags("-fms-runtime-lib=static", {tools = "clang"})
MTd:
add_cxflags("-fms-runtime-lib=static_dbg", {tools = "clang"})
动态库需要额外手动链接msvcrt, msvcrtd，目前Clang对此完全支持且运行正常
MD:
add_cxflags("-fms-runtime-lib=dll", {tools = "clang"})
add_syslinks("msvcrt")
MDd:
add_cxflags("-fms-runtime-lib=dll_dbg", {tools = "clang"})
add_syslinks("msvcrtd")

### 其他信息

https://clang.llvm.org/docs/ClangCommandLineReference.html

-fms-runtime-lib=<arg>
Specify Visual Studio C runtime library. “static” and “static_dbg” correspond to the cl flags /MT and /MTd which use the multithread, static version. “dll” and “dll_dbg” correspond to the cl flags /MD and /MDd which use the multithread, dll version. <arg> must be ‘static’, ‘static_dbg’, ‘dll’ or ‘dll_dbg’.

**Comment by waruqi** [comment]
试下这个 https://github.com/xmake-io/xmake/pull/3548 我没测过

xmake update -s github:xmake-io/xmake#runtime

**Comment by MaxwellGengYF** [comment]
目前Windows 10 Clang 16.0.0没问题。

**Comment by waruqi** [comment]
merge 了
