### ISSUE TITLE
package:add_deps and on_fetch

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#3547]
### 你在什么场景下需要该功能？

关于从系统fetch到的包，其dependency有两种情况：

1. 构建时用到的dependency，例如调用python生成一些中间文件。这种情况对于已经编译好的包，不再需要依赖了；
2. 运行时用到的dependency，例如运行过程中调用python，或者静态链接到python的库。这种仍然需要加上依赖。

目前xmake-repo中没有对二者进行区分，我想问问对于系统fetch的包，它的dependency是如何处理的？

### 描述可能的解决方案

目前已经有一个package:is_built()接口用于windows上判断是否是precompiled。实际上它的逻辑和从系统fetch是一致的，可以复用这个接口，放开到全平台，区分是否是系统上已经编译好的包。

### 描述你认为的候选方案

增加一个新的接口？

**Comment by waruqi** [comment]
> 构建时用到的dependency，例如调用python生成一些中间文件。这种情况对于已经编译好的包，不再需要依赖了；
> 关于从系统fetch到的包

都从系统 fetch 到了，这个不都是 apt/brew 等安装的么，他们用到的构建依赖，xmake 不是原本就取不到么。也不处理。

不清楚，你这到底要判断什么。。

> package:is_built()

这个命名有歧义，不好理解，已经快废弃了，内部直接走的 `not package:is_precompiled()`

外面尽量用 package:is_precompiled()

**Comment by CyaNinix** [comment]
我以为这已经在工作了？
```lua
package("lib")
    add_deps("runtimedep")
    add_deps("buildonly", { private = true })
```

**Comment by xq114** [comment]
> 我以为这已经在工作了？
> 
> ```lua
> package("lib")
>     add_deps("runtimedep")
>     add_deps("buildonly", { private = true })
> ```

If there is an `on_fetch` snippet, which dependencies will be required? From my side `{private = true}` indicates that the includes/links/flags do not propagate along the dependency chain, but does it mean this dependency is not required if we fetch the package from the `on_fetch` snippet?

**Comment by CyaNinix** [comment]
As far as I understood, a private package dependency is not used past build

**Comment by waruqi** [comment]
> > 都从系统 fetch 到了，这个不都是 apt/brew 等安装的么，他们用到的构建依赖，xmake 不是原本就取不到么。也不处理。
> 
> 走on_fetch找到的包，不走系统包管理器，如何声明其依赖呢？

跟是否走系统没关系，不管是否用 on_fetch 都是 `add_deps("xxx")`，如果不想导出给用户用，就 `add_deps("buildonly", { private = true })`

**Comment by xq114** [comment]
> 跟是否走系统没关系，不管是否用 on_fetch 都是 `add_deps("xxx")`，如果不想导出给用户用，就 `add_deps("buildonly", { private = true })`

我总结一下现在的处理：
```lua
package("lib")
    add_deps("runtimedep")
    add_deps("buildonly", { private = true })
```

- 如果从apt/brew找到lib，则xmake会从apt/brew查找依赖，runtimedep和buildonly都被无视；
- 如果从on_fetch找到lib，则xmake会继续查找runtimedep，同时无视buildonly；
- 如果系统上没有找到lib，则从xmake-repo安装，并继续查找runtimedep和buildonly。

我理解对吗？

**Comment by waruqi** [comment]
> > 跟是否走系统没关系，不管是否用 on_fetch 都是 `add_deps("xxx")`，如果不想导出给用户用，就 `add_deps("buildonly", { private = true })`
> 
> 我总结一下现在的处理：
> 
> ```lua
> package("lib")
>     add_deps("runtimedep")
>     add_deps("buildonly", { private = true })
> ```
> 
> * 如果从apt/brew找到lib，则xmake会从apt/brew查找依赖，runtimedep和buildonly都被无视；

不完全是，buildonly 仅用于内部 on_install 构建依赖，如果找到 apt/brew 没有构建过程，那么会忽略它
runtimedep 是对用户导出的 link 依赖。。是否从 apt 找到，都不会影响到 runtimedep，还是会使用，最终到用户那边的 link 就是，`apt::lib` -> `runtimedep` 并没有什么区别。

> xmake会从apt/brew查找依赖

xmake不会从 apt/brew 查找依赖，除非 runtimedep 自身查找时候，也正好从 apt 里面找到了包。。

> * 如果从on_fetch找到lib，则xmake会继续查找runtimedep，同时无视buildonly；
> * 如果系统上没有找到lib，则从xmake-repo安装，并继续查找runtimedep和buildonly。

同上，不管是否从 on_fetch 找到，还是 on_install 里去，都会去找 runtimedep

**Comment by xq114** [comment]
> 不完全是，buildonly 仅用于内部 on_install 构建依赖，如果找到 apt/brew 没有构建过程，那么会忽略它

原来如此，我一直以为private=true仅仅是不继承相关flag。那这样就没有问题了
