### ISSUE TITLE
error while using import std with msvc

### ISSUE THREAD

**Issue by veritas-Qiu** [xmake-io/xmake#3554]
### Xmake Version

xmake v2.7.7+master.bfe26c7c5

### Operating System Version and Architecture

Windows 11 version 22H2

### Describe Bug

try to use the example source file in msvc's tutorial [Tutorial: Import the C++ standard library using modules from the command line](https://learn.microsoft.com/en-us/cpp/cpp/tutorial-import-stl-named-module?view=msvc-170)
```
// requires /std:c++latest

import std;

int main()
{
    std::cout << "Import the STL library for best performance\n";
    std::vector<int> v{5, 5, 5};
    for (const auto& e : v)
    {
        std::cout << e;
    }
}
```

while xmake reports error C2230: could not find module 'std'
msvc version 14.35.32215, with std.ixx and std.compat.ixx in \VC\Tools\MSVC\14.35.32215\modules

### Expected Behavior

build ok

### Project Configuration

```
target("x") 
    set_kind("binary")
    add_files("x.cpp")
    set_languages("cxxlatest")
    set_toolchains("msvc")
```

**Comment by waruqi** [comment]
please remove `set_toolchains("msvc")`

and any idea? @Arthapz

**Comment by waruqi** [comment]
check your msvc version. >= 17.5 preview 

https://github.com/xmake-io/xmake/issues/3084

**Comment by Arthapz** [comment]
i got to reproduce this issue, i'm trying to figure out why it doesn't work
![image](https://user-images.githubusercontent.com/27437334/227166102-bf888414-caac-49d2-9021-4fd4acd119ae.png)

**Comment by Arthapz** [comment]
as a workaround you can add  set_policy("build.c++.modules", true) to you target it will force the module dependency scanner to run

**Comment by Arthapz** [comment]
ok, so because no modules files (.ixx / .mpp / .cppm) is used by the target, module support fail to detect the usage of modules

**Comment by veritas-Qiu** [comment]
Solved, thanks a lot to @Arthapz @waruqi
