### ISSUE TITLE
本地编译源码包msgpack提示找不到boost

### ISSUE THREAD

**Issue by lgmcode** [xmake-io/xmake#3558]
### Xmake 版本

v2.7.7+master.c1789f73d

### 操作系统版本和架构

Windows11 x64

### 描述问题

我在本地下载了 msgpack-c 的源码，checkout 到 cpp_master 分支，在 xmake.lua 中通过`package`引入：
```lua
set_xmakever("2.7.7")
set_project("xmake_msgpack_issue")
set_languages("cxx17")

package("msgpack-cpp")
    set_sourcedir(path.join(os.scriptdir(), "msgpack-c"))
    on_install(function (package)
        local configs = {"-DMSGPACK_CXX17=ON", "-DMSGPACK_USE_BOOST=OFF", "-DMSGPACK_BUILD_DOCS=OFF"}
        table.insert(configs, "-DCMAKE_BUILD_TYPE=" .. (package:debug() and "Debug" or "Release"))
        table.insert(configs, "-DYAML_BUILD_SHARED_LIBS=" .. (package:config("shared") and "ON" or "OFF"))
        import("package.tools.cmake").install(package, configs)
    end)
package_end()

add_requires("msgpack-cpp")
add_rules("plugin.compile_commands.autoupdate", {outputdir = "$(buildir)"})

target("app")
    set_kind("binary")
    add_packages("msgpack-cpp")
    add_files("main.cpp")
target_end()
```
在上面的编译脚本中指定了不使用boost，`-DMSGPACK_USE_BOOST=OFF`，但是编译的时候提示找不到`boost/predef/other/endian.h`
```bash
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2022
note: install or modify (m) these packages (pass -y to skip confirm)?
  -> msgpack-cpp latest [vs_runtime:"MT"]
please input: y (y/n/m)

  => install msgpack-cpp latest .. ok
[ 25%]: cache compiling.release main.cpp
error: main.cpp
C:\Users\xxx\xmake_msgpack_issue\build\.packages\m\msgpack-cpp\latest\8574311f4b544fa89a3d8c3ee79d1929\include\msgpack/sysdep.hpp(102): fatal error C1083: 无法打开包括文件: “boost/predef/other/endian.h”: No such file or directory

  > in main.cpp

```
看了一下在`build\.packages`中安装的msgpack包中的`msgpack-cxx-targets.cmake`文件，里面有一个宏定义`MSGPACK_NO_BOOST`
```cmake
# Create imported target msgpack-cxx
add_library(msgpack-cxx INTERFACE IMPORTED)

set_target_properties(msgpack-cxx PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "MSGPACK_NO_BOOST;MSGPACK_DEFAULT_API_VERSION=3"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include"
)
```
手动补上这个宏定义后是可以正常编译通过并且代码工作正常的（`add_defines("MSGPACK_NO_BOOST")`），所以猜测是这个宏定义没有传递到xmake的target中

### 期待的结果

希望通过`package`引入的本地源码包（源码包通过cmake构建）可以把宏定义传递到编译的目标中

### 工程配置

set_xmakever("2.7.7")
set_project("xmake_msgpack_issue")
set_languages("cxx17")

package("msgpack-cpp")
    set_sourcedir(path.join(os.scriptdir(), "msgpack-c"))
    on_install(function (package)
        local configs = {"-DMSGPACK_CXX17=ON", "-DMSGPACK_USE_BOOST=OFF", "-DMSGPACK_BUILD_DOCS=OFF"}
        table.insert(configs, "-DCMAKE_BUILD_TYPE=" .. (package:debug() and "Debug" or "Release"))
        table.insert(configs, "-DYAML_BUILD_SHARED_LIBS=" .. (package:config("shared") and "ON" or "OFF"))
        import("package.tools.cmake").install(package, configs)
    end)
package_end()

add_requires("msgpack-cpp")
add_rules("plugin.compile_commands.autoupdate", {outputdir = "$(buildir)"})

target("app")
    set_kind("binary")
    add_packages("msgpack-cpp")
    -- add_defines("MSGPACK_NO_BOOST")
    add_files("main.cpp")
target_end()

**Comment by waruqi** [comment]
> 手动补上这个宏定义后是可以正常编译通过并且代码工作正常的（add_defines("MSGPACK_NO_BOOST")），所以猜测是这个宏定义没有传递到xmake的target中

自己 package() 配置里加上这个就好了

**Comment by lgmcode** [comment]
> 自己 package() 配置里加上这个就好了, add_defines("MSGPACK_NO_BOOST")

可以自动把这些宏定义加到依赖的target里面去吗，毕竟如果每一个库都要去手动找到这些宏定义还是挺麻烦的，而且如果库的版本更新了，某些宏定义变了，可能会忘记更新自己脚本里的这些宏定义

**Comment by waruqi** [comment]
可以，你试了不就知道了。。记得先重装下包

**Comment by lgmcode** [comment]
> 可以，你试了不就知道了。。记得先重装下包

嗯，试了，是可以的。
其实，我的意思是，能不能连在`package()`里面加`add_defines("MSGPACK_NO_BOOST")`这一步也省掉

**Comment by lgmcode** [comment]
> > > 可以，你试了不就知道了。。记得先重装下包
> > 
> > 
> > 嗯，试了，是可以的。 其实，我的意思是，能不能连在`package()`里面加`add_defines("MSGPACK_NO_BOOST")`这一步也省掉
> 
> 不能，xmake 不解析 cmakelists.txt 。。各种三方库，cmakelist,configure,scons 随意用，我不可能还去挨个解析一边，自动分析里面到底用了哪些 macros ，哪些是内部的，哪些需要对外导出的。。没这么智能。。也不可靠。。我也没这么多时间去折腾这种

咦，xmake添加cmake构建的第三方包后不是可以得到头文件目录，库目录，库文件吗，不可以顺便也拿到宏定义吗

**Comment by waruqi** [comment]
> > > > 可以，你试了不就知道了。。记得先重装下包
> > > 
> > > 
> > > 嗯，试了，是可以的。 其实，我的意思是，能不能连在`package()`里面加`add_defines("MSGPACK_NO_BOOST")`这一步也省掉
> > 
> > 
> > 不能，xmake 不解析 cmakelists.txt 。。各种三方库，cmakelist,configure,scons 随意用，我不可能还去挨个解析一边，自动分析里面到底用了哪些 macros ，哪些是内部的，哪些需要对外导出的。。没这么智能。。也不可靠。。我也没这么多时间去折腾这种
> 
> 咦，xmake添加cmake构建的第三方包后不是可以得到头文件目录，库目录，库文件吗，不可以顺便也拿到宏定义吗

不完全能，不是所有 cmake库写的 cmakelists.txt 都是完善的，都会去安装 xxx.cmake 导入文件，很多库是没有这个的。。而且这个也依赖 cmake 解析

另外即使有这个，解析出来也是不可靠的。。经常遇到漏了各种 includedirs。。

xmake 不会去依赖这种完全不可靠的东西，头文件，库文件，宏定义，都是通过 add_includedirs/add_links/add_defines 自己配置的，也会按照 xmake 约定的 lib/include 固定安装结构，提取 库名，includedirs 信息。。

另外，还有很多库还不是 cmake 的。。是 autoconf/scons/meson 的，也大量缺少这种信息，不是所有都有 .pc文件，也不是所有 .pc 文件正确导出了 defines 。。win 更不好搞。。

让 xmake 依赖这种乱七八糟的东西去对用户导出 includedirs/links/defines 。。那就有的蛋疼了，到时候天天出现找不到各种头文件，defines 给我反馈 issues 。。我可没时间处理

至少现在 xmake-repo 官方仓库维护的包，很少会出现这种问题，只要 ci 通过。。那么 includes/defines/links 等信息肯定都是可靠的。。

**Comment by lgmcode** [comment]
感谢解释，没想到需要考虑这么多。用了 xmake 一段时间，写代码都愉快了很多。以前了解一些lua，xmake.lua 写起来非常流畅，希望 xmake 能早日成为主流构建工具，减轻我们的负担
