### ISSUE TITLE
windows由源码构建xmake后测试可在任意路径下运行srcenv.bat

### ISSUE THREAD

**Issue by Cliear** [xmake-io/xmake#3561]
### 你在什么场景下需要该功能？

如果从其它路径运行此脚本会找不到XMAKE_PROGRAM_DIR，必须进入script目录运行，并且如果是在命令行下运行的话，它会污染我的环境变量。

### 描述可能的解决方案

bat文件定位使用%~dp0，并且使用setlocal以保证不污染环境变量

**Comment by waruqi** [comment]
通常只需要双击打开就行了
