### ISSUE TITLE
PDB文件输出问题

### ISSUE THREAD

**Issue by RimuruChan** [xmake-io/xmake#3567]
### Xmake 版本

2.7.7

### 操作系统版本和架构

Windows 11

### 描述问题

![image](https://user-images.githubusercontent.com/42002296/227865396-eb2db3e8-f2ce-49ed-b1e0-e8305fd2e03e.png)
我猜测xmake会在编译后把compile.target.pdb复制为target.pdb，但是没有删除原来的临时pdb文件。
另外我觉得最好就直接输出到target.pdb，方便程序调试的时候调试器可以直接自动找到pdb文件

### 期待的结果

只留下一个pdb文件

**Comment by waruqi** [comment]
最早就是直接写 target pdb 的，后来躺了坑，有问题，才通过这种方式解决的。。

相关背景：

https://github.com/xmake-io/xmake/pull/495
https://github.com/xmake-io/xmake/issues/658

如果你有更好的方案，既能解决之前的问题，又能直接写 target pdb ，也可以提 pr 过来。

**Comment by RimuruChan** [comment]
看了一下最后连接出来好像也没毛病，倒也问题不大
