### ISSUE TITLE
Xmake can't recognize bundled library of qt when building wasm application

### ISSUE THREAD

**Issue by jingkaimori** [xmake-io/xmake#3572]
### Xmake Version

v2.7.4+202212240813

### Operating System Version and Architecture

18.04.1-Ubuntu

### Describe Bug

When building binary file for wasm with qt, xmake files on linking stage, complaining not found symbol of bundled library such as pcre.

### Expected Behavior

Xmake recognize QtBundled*.so and add them to system include, e.g. `-isystem QtBundledPcre.so`

### Additional Information and Error Logs

Qt is installed by aqt via following command:
```
aqt install-qt linux desktop 6.4.3 wasm_32
aqt install-qt linux desktop 6.4.3 gcc_64
```

Associated error log here:
https://github.com/XmacsLabs/mogan/actions/runs/4542217632/jobs/8005354108?pr=547

**Comment by waruqi** [comment]
libpcre not found for wasm, maybe need improve here to support for wasm.

https://github.com/xmake-io/xmake/blob/884ec302caa4751a18a5a85de04e64a42ac8b210/xmake/rules/qt/load.lua#L59

**Comment by waruqi** [comment]
done
