### ISSUE TITLE
指定的winsdk版本在生成compile_commands的时候没有起作用

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#3574]
### Xmake 版本

2.7.7

### 操作系统版本和架构

windows 11

### 描述问题

指定使用的 winsdk 版本
```
xmake f --vs_sdkver=10.0.19041.685
```
生成compile_commands.json
```
xmake project -k compile_commands --lsp=clangd
```
然后可以看到是引用的 22000
![image](https://user-images.githubusercontent.com/97490782/228420152-1dcb73ba-187a-4024-a50e-5a218f47679a.png)
compile_commands.json 里面指不指定sdkver都没区别

### 期待的结果

能根据配置中不同的sdk版本生成不同的compile_commands

**Comment by waruqi** [comment]
不支持，这种都是从 msvc 的 %INCLUDE% 环境变量中直接加载的，编译时候也不会显式设置 `-I` 

转成 commands json，msvc 环境变量里面设置的值 目前不会显式带进去。

**Comment by heheda123123** [comment]
我生成compile_commands是让clangd用，那想让clangd使用指定的sdk版本有办法吗

**Comment by waruqi** [comment]
除非 clangd 本身支持选择 msvc sdk ，这你要问 clangd 那边了

**Comment by heheda123123** [comment]
设置不同的windows sdk或者vs版本其实就是想用不同的头文件和lib，根据xmake config的设置直接把头文件路径加到前面可行吗
![image](https://user-images.githubusercontent.com/97490782/232288058-579e3097-e0ae-4a7c-b5ce-94e169738b3f.png)

![image](https://user-images.githubusercontent.com/97490782/232288146-6a93c1b6-24a1-4640-b031-b29406f632e1.png)
![image](https://user-images.githubusercontent.com/97490782/232288174-3616e0a7-b412-4260-8d47-a100aa7672fd.png)

**Comment by waruqi** [comment]
你可以试试

**Comment by heheda123123** [comment]
> 你可以试试

网上看了下，windows sdk的版本可以传给compile_commands ，参考下面这个链接
https://github.com/Nemirtingas/clang-msvc-sdk
主要是下面的几段代码，
```
set(WINSDK_INCLUDE "${WINSDK_BASE}/Include/${WINSDK_VER}")
set(WINSDK_LIB "${WINSDK_BASE}/Lib/${WINSDK_VER}")
```
```
set(COMPILE_FLAGS
    -D_CRT_SECURE_NO_WARNINGS
    --target=${TRIPLE_ARCH}-windows-msvc
    -fms-compatibility-version=19.11
    -imsvc "${ATLMFC_INCLUDE}"
    -imsvc "${MSVC_INCLUDE}"
    -imsvc "${WINSDK_INCLUDE}/ucrt"
    -imsvc "${WINSDK_INCLUDE}/shared"
    -imsvc "${WINSDK_INCLUDE}/um"
    -imsvc "${WINSDK_INCLUDE}/winrt")
```
```
set(LINK_FLAGS
    # Prevent CMake from attempting to invoke mt.exe. It only recognizes the slashed form and not the dashed form.
    /manifest:no

    -libpath:"${ATLMFC_LIB}/${WINSDK_ARCH}"
    -libpath:"${MSVC_LIB}/${WINSDK_ARCH}"
    -libpath:"${WINSDK_LIB}/ucrt/${WINSDK_ARCH}"
    -libpath:"${WINSDK_LIB}/um/${WINSDK_ARCH}")
```

**Comment by star-hengxing** [comment]
这里没问题可以关了

**Comment by xq114** [comment]
我这里clangd 报错 error: unknown argument: '-imsvc'。

https://reviews.llvm.org/D95472 根据这个链接可以用/winsdkdir和/winsdkversion指定sdk版本，我试了使用 `"/winsdkdir", "C:\\Program Files (x86)\\Windows Kits\\10", "/winsdkversion", "10.0.22000.0"` 可以，clangd不会报错。
