### ISSUE TITLE
xrepo install 报错

### ISSUE THREAD

**Issue by yousogood** [xmake-io/xmake#3577]
### Xmake 版本

2.7.7

### 操作系统版本和架构

windows 10

### 描述问题

xmake install 7z
xmake install llvm
updating repositories .. error: fatal: not a git repository (or any of the parent directories): .git
error: execv(xmake require -j 10 --extra={system=false} llvm) failed(-1)

起因，我猜它使用git下载，因此打开代理下载，但太慢了，而且没有进度提示，仿佛卡住了，便ctrl-c了，然后重新再install就跑不起来了。我猜可能是临时存放git的目录需要清空一下，但我找半天也不知道它到底下载到哪个目录。

### 期待的结果

xrepo在windows上默认安装到哪个目录下

**Comment by waruqi** [comment]
删下 %localappdata%/.xmake/repositoires 目录后再试试

**Comment by yousogood** [comment]
有用

**Comment by Sorrow-Scarlet** [comment]
>updating repositories .. error: fatal: not a git repository (or any of the parent directories): .git

`xrepo install` 和 `xmake install` 如被打断，在最新的`v3.0.6+HEAD.9fdcf69f6` 也会出现一致错误

可行的修复：

1. 提供一个`xmake reset`之类的命令
2. 给报错添加更多信息
```txt
updating repositories .. error: fatal: not a git repository (or any of the parent directories): .git
Try clean this dir: %localappdata%\.xmake\repositoires
```
3. 添加一个校验，没下完的git写入锁或者其他，然后下次xmake时检测发现问题，优先解决（

**Comment by Sorrow-Scarlet** [comment]
补充一点，执行`xmake install`的克隆，能否改成浅克隆，而不是完整克隆...在没有代理的环境太慢了。

`git clone --depth 1 <url>`

**Comment by star-hengxing** [comment]
> 补充一点，执行`xmake install`的克隆，能否改成浅克隆，而不是完整克隆...在没有代理的环境太慢了。
> 
> `git clone --depth 1 <url>`

传递 `-v` 可以看到，现在都是 depth 1 或者 treeless clone。

**Comment by Sorrow-Scarlet** [comment]
> 传递 `-v` 可以看到，现在都是 depth 1 或者 treeless clone。

@star-hengxing 是我表达问题，位于`%localappdata%\.xmake\repositories` ，这个位置的repo没做浅克隆:

```txt
// Console output
commit 48a754f1d132af651327f04da6149d2bd9f1f1e1 (HEAD -> master, origin/master, origin/dev, origin/HEAD)
Author: ruki <waruqi@gmail.com>
Date:   Mon Jan 26 11:07:40 2026 +0800

    Update pyincpp to v2.7.1 (#9189)

commit daf2b81c2369aa5c75a211ee5d6341c183e3d83e
Author: ruki <waruqi@gmail.com>
Date:   Mon Jan 26 11:07:37 2026 +0800

    Update freerdp to 3.21.0 (#9190)

commit 5caec311598029a91027de0d670ef486f21449cd
:
```

图片：

<img width="294" height="420" alt="Image" src="https://github.com/user-attachments/assets/b02df6e8-99f7-4daf-a210-9fe4393c06b9" />

无论是`build-artifacts` 还是`xmake-repo` 都是这样

**Comment by waruqi** [comment]
> > 传递 `-v` 可以看到，现在都是 depth 1 或者 treeless clone。
> 
> [@star-hengxing](https://github.com/star-hengxing) 是我表达问题，位于`%localappdata%\.xmake\repositories` ，这个位置的repo没做浅克隆:

没必要，这个随时都可能要 git pull 去更新仓库的，又不是一次拉取用完就没事了。
