### ISSUE TITLE
add_linkdirs and add_rpathdirs not finding DLL when debugging with VS

### ISSUE THREAD

**Issue by maximegmd** [xmake-io/xmake#3578]
### Xmake Version

2.7.7

### Operating System Version and Architecture

Windows

### Describe Bug

When using `add_linkdirs` or `add_rpathdirs` the vs project generator will add relatives paths to the PATH environment for debugging. But the relative dirs are relative to the xmake.lua file, not the working directory of the debug environment. This causes the path to be invalid and dlls cannot be loaded.

### Expected Behavior

The paths added to PATH are either relative to the working directory of the binary during the debug or absolute paths to prevent any kind of issue.

**Comment by waruqi** [comment]
add_linkdirs is for linkers only, add_rpathdirs is for non-windows programs only.

The windows dll loading can only be controlled by adding the PATH environment variable, you should use add_runenvs or set_runenv to set it.

Refer to the documentation at https://xmake.io/#/manual/project_target?id=targetadd_runenvs

**Comment by yamashi** [comment]
https://xmake.io/#/manual/project_target?id=targetadd_rpathdirs

> After [add_linkdirs](https://xmake.io/#/manual/project_target?id=targetadd_linkdirs) sets the link search directory of the dynamic library, the program is normally linked, but in the Linux platform, if you want to run the compiled program normally, it will report that the dynamic library fails to be loaded.

It appears add_linkdirs is already supposed to do that.

**Comment by waruqi** [comment]
> https://xmake.io/#/manual/project_target?id=targetadd_rpathdirs
> 
> > After [add_linkdirs](https://xmake.io/#/manual/project_target?id=targetadd_linkdirs) sets the link search directory of the dynamic library, the program is normally linked, but in the Linux platform, if you want to run the compiled program normally, it will report that the dynamic library fails to be loaded.
> 
> It appears add_linkdirs is already supposed to do that.

When the linker is linking the import library file foo.lib corresponding to the foo.dll dynamic library, it will search for the linked library from linkdirs. But this is a matter for the linker and has nothing to do with loading foo.dll at runtime.

**Comment by SirLynix** [comment]
It works well for me with `xmake run` and `vs` / `vsxmake` generator, can you give an example of your VS setup with the xmake.lua?

**Comment by waruqi** [comment]
Although the msvc runtime does not rely on linkdirs, xmake will try to add the path to linkdirs to the PATH as well, since it is possible that foo.dll exists in the linkdirs directory. So xmake will try to add some paths that may exist, but this is not entirely reliable and does not currently convert linkdirs paths.

**Comment by waruqi** [comment]
It works for me.

```lua
target("testdll")
    set_kind("binary")
    add_files("src/*.cpp")
    add_linkdirs("dll")
```

```
    <XmakeRunEnvs>PATH=$(XmakeProjectDir)\dll;$([System.Environment]::GetEnvironmentVariable('PATH'))</XmakeRunEnvs>
```

`$(XmakeProjectDir)\dll` is correct path.

**Comment by youngday** [comment]
for linux,linkdirs,comment below,

```lua
target("test")
    add_links("testso")   
    add_linkdirs("$(buildir)/lib") --just for shared lib link path
    add_rpathdirs("$(buildir)/lib") --just for shared lib link path when running on linux,but not worked
    add_rpathdirs("@loader_path/lib") --just for shared lib link path when running on linux,worked well
```
如何优化一下呢？linux 下编译不容易发现少rpathdirs,和link加一样的路径又不工作，终于在文档找到loader_path路径，终于debug正常了。

**Comment by waruqi** [comment]
> for linux,linkdirs,comment below,
> 
> ```lua
> target("test")
>     add_links("testso")   
>     add_linkdirs("$(buildir)/lib") --just for shared lib link path
>     add_rpathdirs("$(buildir)/lib") --just for shared lib link path when running on linux,but not worked
>     add_rpathdirs("@loader_path/lib") --just for shared lib link path when running on linux,worked well
> ```
> 
> 如何优化一下呢？linux 下编译不容易发现少rpathdirs,和link加一样的路径又不工作，终于在文档找到loader_path路径，终于debug正常了。

与这个 issue 无关，请单独开 issue
