### ISSUE TITLE
add_links 添加动态库，能够成功编译，最终通过ldd查看，发现没有编译时链接的动态库

### ISSUE THREAD

**Issue by yangyagami** [xmake-io/xmake#3579]
### Xmake 版本

2.7.7

### 操作系统版本和架构

ubuntu 20.04 lts

### 描述问题

add_links 添加动态库，能够成功编译，最终通过ldd查看，发现没有编译时链接的动态库，使用的工具链是aarch64-linux-gnu-gcc 9.4.0。

### 期待的结果

可执行程序中通过readelf能够查看所连接的库。

**Comment by Qizhi697** [comment]
我也遇到这个问题，请问是什么原因呢？

**Comment by yangyagami** [comment]
> 我也遇到这个问题，请问是什么原因呢？

添加“-Wl,--no-as-needed"链接选项。
