### ISSUE TITLE
最新版Clion（）里xmake-idea没用

### ISSUE THREAD

**Issue by putao520** [xmake-io/xmake#358]
win10x64下最新版Clion（）里xmake-idea没用
1：安装了xmake-idea插件
2：安装了xmake，并且在环境变量PATH设置了XMAKE安装目录
3：在ide里使用xmake菜单下任何命令无效
但是还是用不了，求大神解决!谢谢。

**Comment by aadog** [comment]
+1 最新版搜索不到xmake插件
