### ISSUE TITLE
wrong compiler arg for xrepo install conan

### ISSUE THREAD

**Issue by MrScriptX** [xmake-io/xmake#3583]
### Xmake Version

2.7.7

### Operating System Version and Architecture

Windows 11

### Describe Bug

When trying to install boost from the conan repo using xrepo using the following
`$ xrepo install conan::boost/1.81.0`

The following command is invoke
`$ conan install . --build=missing -s os=Windows -s arch=x86_64 -s build_type=Debug -s "compiler=Visual Studio" -s compiler.version=17 -s compiler.runtime=MT`

Which throws the following error : 
`ERROR: Invalid setting 'Visual Studio' is not a valid 'settings.compiler' value.
Possible values are ['sun-cc', 'gcc', 'msvc', 'clang', 'apple-clang', 'intel-cc', 'qcc', 'mcst-lcc']`

### Expected Behavior

The invoke command should have the compiler option set to "msvc", not "Visual Studio". Which give in full :
`$ conan install . --build=missing -s os=Windows -s arch=x86_64 -s build_type=Debug -s "compiler=msvc" -s compiler.version=17 -s compiler.runtime=MT`

### Project Configuration

conan default profile

[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=20
compiler.runtime=static
compiler.version=193
os=Windows

**Comment by waruqi** [comment]
try it again. `xmake update -s dev`
