### ISSUE TITLE
mac下用xmake设置类似qt中注释掉pro文件的 CONFIG += console

### ISSUE THREAD

**Issue by jiagushuai** [xmake-io/xmake#359]
+ qt创建Qt Console APPlication 项目，隐藏掉界面通过注释掉pro文件的`CONFIG += console`
![image](https://user-images.githubusercontent.com/29997741/53392556-b4c26700-39d4-11e9-9997-dbd986ccc0de.png)
## 在xmake中设置什么可以达到相同效果呢

**Comment by waruqi** [comment]
终端程序可以看下demo https://github.com/xmake-io/xmake/tree/master/tests/projects/qt/console

我记得xmake create 里面应该也有模板工程可以直接创建 你可以敲help看下

**Comment by jiagushuai** [comment]
使用xmake创建运行成功的，是如何设置隐藏界面？
qt中是通过注释掉qt的pro文件的一条语句，xmake要达到相同效果要如何设置呢

**Comment by waruqi** [comment]
？ console 工程 不是原本就没界面的么。。？

**Comment by jiagushuai** [comment]
默认运行的时候会弹出终端窗口。我想把那个隐藏掉做成类似后台进程的效果

**Comment by waruqi** [comment]
? 还是没明白。。我用qt creator按照你的方式 创建的console工程，编译运行 不也是默认弹出终端窗口的么。。

![image](https://user-images.githubusercontent.com/151335/53684847-a7e3a180-3d4d-11e9-9999-25d5cc13591d.png)

![image](https://user-images.githubusercontent.com/151335/53684850-b5009080-3d4d-11e9-956c-7b0ff55b7537.png)

跟xmake创建的没什么本质区别。。

如果你要做成 daemon进程，是需要写代码控制的，这跟qt CONFIG += console 没啥必然关系，qt creator创建的工程，默认也做不到这个效果。。

你要么google下 如何敲代码控制以daemon方式启动，要么根据linux/macos等不同平台，配置daemon的配置文件，让系统把你的程序作为daemon方式加载起来，这块如何配置，你也可以google下。。

但是这跟xmake还是qt都没啥关系。。

**Comment by jiagushuai** [comment]
qt点击run的console程序为什么没有弹出界面呢，我直接双击生成是像你说的一样有界面。

**Comment by waruqi** [comment]
你说的是什么界面。。console工程不可能有界面的。。所谓的界面。。不会是 终端吧？ 我那个截图就是 qt 点run。。qt自己打开终端显示出来的

如果你这qt run后，没看到终端界面，那就不清楚了。。可以切到后台窗口看下 有没有，或者看下程序是否已经快速退出了，所以没看到。。

反正这跟 后台进程没有任何关系，跟qt还是xmake也没有任何关系。。

![image](https://user-images.githubusercontent.com/151335/53708421-5c74e480-3e6e-11e9-9a1c-9a9bf4a64540.png)

**Comment by jiagushuai** [comment]
界面确实是 指终端
我加了`getchar()`编译运行后还是run没有界面出来。
去掉`CONFIG += console`之后run才有界面出来
![image](https://user-images.githubusercontent.com/29997741/53713927-82f34980-3e87-11e9-9647-6d760ee14cd8.png)

**Comment by jiagushuai** [comment]
+ 创建项目的时候使用Qt Console APPlication ，然后在pro文件注释掉这一句
![image](https://user-images.githubusercontent.com/29997741/53714489-91426500-3e89-11e9-9b92-55a951981be0.png)

**Comment by waruqi** [comment]
这是qt creator的run的加载问题，跟xmake没啥关系。。你去掉 += console 用Qt编译 直接在终端下运行 生成的程序。效果还是一样的，只不过你加上 += console，点run，qt帮你额外打开了终端去运行它而已。。不加的话，qt直接运行编译生成的程序了，没给你额外打开终端

![image](https://user-images.githubusercontent.com/151335/53715189-06af3500-3e8c-11e9-8752-2eac059c6834.png)

**Comment by jiagushuai** [comment]
这样子 👌
