### ISSUE TITLE
"xmake check" gives false warnings for compiler-specific flags

### ISSUE THREAD

**Issue by AidanSun05** [xmake-io/xmake#3594]
### Xmake Version

v2.7.7+dev.f95a957

### Operating System Version and Architecture

macOS Ventura 13.3

### Describe Bug

When compiler specific flags are specified in `xmake.lua`, such as `add_cxxflags("cl::/Zc:preprocessor")`, `xmake check` does not recognize them and outputs false warnings.

Output of `xmake check` with the specified project configuration (Clang 16 is used):

```shell
$ xmake check
./xmake.lua:6: warning: clang: unknown c++ compiler flag 'cl::/Zc:preprocessor'
./xmake.lua:9: warning: clang: unknown c++ compiler flag '/utf-8'
./xmake.lua:12: warning: clang: unknown c++ compiler flag 'clang::-finput-charset=UTF-8'
./xmake.lua:12: warning: clang: unknown c++ compiler flag 'clang::-fexec-charset=UTF-8'
0 notes, 4 warnings, 0 errors
```

### Expected Behavior

In strings like `"cl::/Zc:preprocessor"`, `xmake check` should recognize the compiler as `cl` and the flag as `/Zc:preprocessor`. It should ignore compiler flags that do not apply to the compiler that is being used.

With the given project configuration, `xmake check` should output 0 warnings.

### Project Configuration

```lua
target("compiler-flag-test")
    set_kind("binary")
    add_files("src/*.cpp")

    -- This is identified as an unknown flag
    add_cxxflags("cl::/Zc:preprocessor")

    -- Specifying flags this way also fails
    add_cxxflags("/utf-8", { tools = "cl" })

    -- Compiler flags specific to Clang
    add_cxxflags("clang::-finput-charset=UTF-8", "clang::-fexec-charset=UTF-8")
```

**Comment by waruqi** [comment]
try `xmake update -s github:xmake-io/xmake#check`

https://github.com/xmake-io/xmake/pull/3595

**Comment by AidanSun05** [comment]
Thanks, this fixes the bug.
