### ISSUE TITLE
add_filegroups with empty group name

### ISSUE THREAD

**Issue by WubiCookie** [xmake-io/xmake#3598]
### Xmake Version

2.7.7

### Operating System Version and Architecture

Windows 10 version 1909

### Describe Bug

Creating a filegroup with no name have an inconsistant behaviour with a named group. (also note the empty filter and the '.' filter)

![devenv_4O9DWVTAhH](https://user-images.githubusercontent.com/17192695/230082936-5b7a8902-9502-4862-99de-55f7b1ae1f59.png)

### Expected Behavior

The filtered files should be at the project's root.

![devenv_hlHtEadjJ9](https://user-images.githubusercontent.com/17192695/230083089-f1a17be1-34ab-4d14-8ac4-700301f381b8.png)

### Project Configuration

Folders structure:
```
\---project
    |   xmake.lua
    |
    \---src
        |   main.cpp
        |
        \---folder1
                source1.cpp
```

xmake.lua:
```lua
target("named_group_default_mode")
	add_files("src/**.cpp")
	add_filegroups("group", {rootdir = "src", files = "**.cpp"})

target("unnamed_group_default_mode")
	add_files("src/**.cpp")
	add_filegroups("", {rootdir = "src", files = "**.cpp"})

target("named_group_plain_mode")
	add_files("src/**.cpp")
	add_filegroups("group", {rootdir = "src", files = "**.cpp", mode = "plain"})

target("unnamed_group_plain_mode")
	add_files("src/**.cpp")
	add_filegroups("", {rootdir = "src", files = "**.cpp", mode = "plain"})
```

[project.zip](https://github.com/xmake-io/xmake/files/11158845/project.zip)

**Comment by waruqi** [comment]
Try it again, `xmake update -s dev`

BTW, why do you want to use empty string as filegroup. It's invalid group name for xmake.

**Comment by waruqi** [comment]
ok, so does it work now?

**Comment by WubiCookie** [comment]
No it doesn't on dev
![image](https://user-images.githubusercontent.com/17192695/230331486-649f0f37-0b3e-48a8-8816-4d441929cb85.png)

**Comment by waruqi** [comment]
? dot group has been removed

<img width="207" alt="image" src="https://user-images.githubusercontent.com/151335/230332546-4f3ce558-29a3-4c2f-a827-b38fa5eb03f3.png">

**Comment by waruqi** [comment]
try it again.

**Comment by waruqi** [comment]
Does it work now?
