### ISSUE TITLE
add_filegroups with same group names

### ISSUE THREAD

**Issue by WubiCookie** [xmake-io/xmake#3599]
### Xmake Version

2.7.7

### Operating System Version and Architecture

Windows 10 version 1909

### Describe Bug

When calling `add_filegroups` several times with the same group name, only the last call is used.

![image](https://user-images.githubusercontent.com/17192695/230086513-819bf806-fd6a-43e0-9081-f0d31af8d70a.png)

### Expected Behavior

The files should be added to the group.

![image](https://user-images.githubusercontent.com/17192695/230086739-a1b16bb1-e0bf-44b8-ba18-413f6f63b3c8.png)

### Project Configuration

Folders structure:
```
\---project
    |   xmake.lua
    |
    +---include
    |   |   main.hpp
    |   |
    |   \---folder1
    |           source1.hpp
    |
    \---src
        |   main.cpp
        |
        \---folder1
                source1.cpp
```

xmake.lua:
```lua
target("main")
	add_files("src/**.cpp")
	add_headerfiles("include/**.hpp")
	add_filegroups("group", {rootdir = "src", files = "**.cpp"})
	add_filegroups("group", {rootdir = "include", files = "**.hpp"})
```

[project.zip](https://github.com/xmake-io/xmake/files/11158992/project.zip)

**Comment by waruqi** [comment]
We cannot use same name group. We can only use 

```
	add_filegroups("group", {rootdir = ".", files = {"**.cpp", "**.hpp"}})
```

for only one group.

**Comment by WubiCookie** [comment]
How can I have the same filters as I shown in Expected Behavior without changing my folders structure?

**Comment by waruqi** [comment]
> How can I have the same filters as I shown in Expected Behavior without changing my folders structure?

It does not support.

**Comment by WubiCookie** [comment]
Can I turn this bug report into a feature request?

**Comment by waruqi** [comment]
> Can I turn this bug report into a feature request?

No, and will not be supported in the future, all add_xxx and set_xxx descriptive scope interfaces, will de-duplicate the values. This is a feature that cannot be supported and I would not consider it.

You can only change to a different group name

**Comment by WubiCookie** [comment]
Ok, thank you
