### ISSUE TITLE
c++20 module 在clang15.0.4上还是有问题，没法编译

### ISSUE THREAD

**Issue by malizhao** [xmake-io/xmake#3601]
### Xmake 版本

2.7.7

### 操作系统版本和架构

redhat 9

### 描述问题

两个很简单的文件：

$ cat src/hello.mpp
export module hello;
//#include <cstdio>
export namespace hello {
    void say(const char* str) {
        //printf("%s\n", str);
    }
}

$ cat src/main.cpp
import hello;
int main() {
    hello::say("hello module!");
    return 0;
}

编译时报错：
$ xmake -v
[  0%]: generating.module.deps src/main.cpp
/opt/clang-15.0.4/bin/clang -Qunused-arguments -m64 -E -x c++ src/main.cpp -o build/.gens/hello/linux/x86_64/release/rules/modules/cache/2d9b7c0b/main.cpp.i
[  0%]: generating.module.deps src/hello.mpp
/opt/clang-15.0.4/bin/clang -Qunused-arguments -m64 -E -x c++ src/hello.mpp -o build/.gens/hello/linux/x86_64/release/rules/modules/cache/2d9b7c0b/hello.mpp.i
[ 14%]: compiling.module.release hello
/opt/clang-15.0.4/bin/clang -c -x c++-module --precompile -Qunused-arguments -m64 -std=c++20 -fmodules-ts -fmodules-cache-path=build/.gens/hello/linux/x86_64/release/rules/modules/cache -o build/.gens/hello/linux/x86_64/release/rules/modules/cache/2d9b7c0b/hello.pcm src/hello.mpp
/opt/clang-15.0.4/bin/clang -c -Qunused-arguments -m64 -std=c++20 -fmodules-ts -fmodules-cache-path=build/.gens/hello/linux/x86_64/release/rules/modules/cache -o build/.objs/hello/linux/x86_64/release/src/hello.mpp.o build/.gens/hello/linux/x86_64/release/rules/modules/cache/2d9b7c0b/hello.pcm
[ 57%]: compiling.release src/main.cpp
/opt/clang-15.0.4/bin/clang -c -Qunused-arguments -m64 -std=c++20 -fmodules-ts -fmodule-file=build/.gens/hello/linux/x86_64/release/rules/modules/cache/2d9b7c0b/hello.gcm -o build/.objs/hello/linux/x86_64/release/src/main.cpp.o src/main.cpp
error: fatal error: module file 'build/.gens/hello/linux/x86_64/release/rules/modules/cache/2d9b7c0b/hello.gcm' not found: module file not found
1 error generated.

应该是混用了gcm，pcm吧，这里产生的结果是pcm

### 期待的结果

pass

**Comment by waruqi** [comment]
> 应该是混用了gcm，pcm吧，这里产生的结果是pcm

按理不可能会混用的，要么你之前用 gcc 编译过，后来切到 clang 了。。build 下 mapper 里面还保留了 gcc 的 gcm mapfile

可以清空下 build 和 .xmake  后再试下

```
rm -rf build
rm -rf .xmake
xmake -rvD
```

**Comment by malizhao** [comment]
我确实用gcc编译过，但是我用xmake clean命令clean了啊。

**Comment by malizhao** [comment]
用了你的cmd确实是可以了，但是我觉得xmake clean应该能解决这个情况

**Comment by waruqi** [comment]
> 用了你的cmd确实是可以了，但是我觉得xmake clean应该解决这个情况

试下  `xmake clean --all`
