### ISSUE TITLE
树莓派等 aarch 系统上 os.arch 不能正确收敛为 arm64, 导致 xmake repo 安装 cmake 失败

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#3604]
### 你在什么场景下需要该功能？

树莓派等 aarch 系统上 os.arch 不能正确收敛为 arm64, 导致 xmake repo 安装 cmake 失败

### 描述可能的解决方案

os.arch 改进，将 arm64-v8a 收敛至 arm64

**Comment by waruqi** [comment]
我改进过了，走收敛的话，也许会丢失不少 arch 信息，有可能其他地方得用到。

而且即使 arm64 收敛了，还有 armv7, armv6 等等
想了想，还是得通过 `os.is_arch` 来处理。。

可以通过下面的方式来判断 arm64/arm32

```
if os.is_arch("arm64.*") then
    -- arm64
elseif os.is_arch("arm.*") then
    -- arm32
end
