### ISSUE TITLE
Package preload files for wasm

### ISSUE THREAD

**Issue by jingkaimori** [xmake-io/xmake#3613]
### Is your feature request related to a problem? Please describe.

Some wasm program needs local asset files when starting. Emscripten provides a 'preload' mechanism to package these file into a `.data` package. XMake should make this kind of package from the list of install file.

### Describe the solution you'd like

```lua
target("wasmapp") do
    set_kind("binary")
    add_installfiles("assets/as_1.md")
    add_installfiles("assets/as_2.md", {prefixdir = "doc"})
    add_installfiles("assets/(nest/as_3.md)", {prefixdir = "doc"})
end
```

```
emcc wasmapp.cpp -o wasmapp.html --preload-file assets/as_1.md --preload-file assets/as_2@doc/as_2.md--preload-file assets/nest/as_3@doc/nest/as_3.md
```

### Additional context

Usage of package arg of emcc is documented [here](https://emscripten.org/docs/porting/files/packaging_files.html#packaging-using-emcc).

**Comment by waruqi** [comment]
We should not use `add_installfiles`, it only for installation. `xmake install`

but `--preload-file ` is only for building stage.

you can use 

```
target("wasmapp") do
    set_kind("binary")
    add_ldflags({"--preload-file", "src/xxx.md"}, {expand = false, force = true})
    add_ldflags({"--preload-file", "src/xxx2.md"}, {expand = false, force = true})
end
```

**Comment by waruqi** [comment]
or waiting for https://github.com/xmake-io/xmake/issues/2384

**Comment by waruqi** [comment]
or you can try this on dev branch `xmake update -s dev`

```lua
target("test5")
    set_kind("binary")
    add_files("src/*.cpp")
    add_values("wasm.preloadfiles", "src/xxx.md")
    add_values("wasm.preloadfiles", "src/xxx2.md")
```
