### ISSUE TITLE
在非root下,不能通过xmake创建项目.

### ISSUE THREAD

**Issue by GitHubProgarm** [xmake-io/xmake#362]
在非root用户下下载并编译安装后,仍然不能编译例子下的项目和不能创建目录.希望作者找一下,是否有此问题存在

**Comment by GitHubProgarm** [comment]
create hello ...
error: cannot copy file project/.gitignore to /data/lua_project/hello, error: File exists

**Comment by waruqi** [comment]
看提示 你已经创建过了 hello工程在lua_project下，可以删了hello目录重新创建下。或者换个 工程名

```console
xmake create test
```

/data目录也确认下权限, 非root下 是否能创建。。

/data/project/xmake-master目录，也确认下，是否在root下去clone创建的，非root下是否有写入权限

**Comment by GitHubProgarm** [comment]
可以了,谢谢
