### ISSUE TITLE
When installing a package inside of project generation, unity build is disabled

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#3624]
### Xmake Version

2.7.8

### Operating System Version and Architecture

Windows 11

### Describe Bug

When you generate a project (like VS project) and have xmake install a package, `XMAKE_IN_PROJECT_GENERATOR` is set which prevents the package to use unity build with xmake because of [this check](https://github.com/xmake-io/xmake/blob/master/xmake/rules/c%2B%2B/unity_build/unity_build.lua#L77).

This failed compilation of one of my package as it enables some defines when using unitybuild that must not be defined when unitybuild is disabled.

### Expected Behavior

That disabling unitybuild for a target doesn't disable unitybuild for its packages.

**Comment by waruqi** [comment]
try reset it in `https://github.com/xmake-io/xmake/blob/b4dd67800fe1efa0107875011ac9d6f9d864fd87/xmake/modules/package/tools/xmake.lua#L240`
