### ISSUE TITLE
add_files 添加 .rc 文件后，生成 CMakeLists.txt 错误

### ISSUE THREAD

**Issue by xzzh999** [xmake-io/xmake#3626]
### Xmake 版本

2.7.8

### 操作系统版本和架构

win10

### 描述问题

win下，编写好xmake.lua后，使用 add_files("../../test.rc")添加 .rc 文件，然后执行 xmake project -k cmakelists，CMakeLists.txt 出现错误的生成代码，而没有将 rc 文件添加到工程中：

target_link_libraries(test PRIVATE
    ${CMAKE_SOURCE_DIR}/build/.objs/test/windows/x86/release/__/__/test.rc.obj
)

### 期待的结果

正确加入 .rc 文件到工程中

### 工程配置

add_files("../../test.rc")

**Comment by waruqi** [comment]
更新到 dev 试试

```
xmake update -s dev
```
