### ISSUE TITLE
获取openssl失败

### ISSUE THREAD

**Issue by Tomtest001** [xmake-io/xmake#3629]
### Xmake 版本

v2.6.2+HEAD.90e499c

### 操作系统版本和架构

Mac i7 12.6

### 描述问题

 使用 
add_requires("openssl 1.1.1-t", {system = false}) 

获取 openssl 1.1.1-t 失败
checking for Android SDK directory ... ~/Library/Android/sdk
checking for Build Tools Version of Android SDK ... 32.0.0
checking for NDK directory ... /Users/sdkClient/Library/Android/sdk/ndk/21.1.6352462
checking for SDK version of NDK ... 21
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/local/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
/usr/local/bin/git rev-parse HEAD
error: @programdir/core/main.lua:302: @programdir/modules/private/action/require/impl/package.lua:388: package(openssl): version(1.1.1-t) not found!
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:913]:
    [@programdir/modules/private/action/require/impl/package.lua:388]: in function '_select_package_version'
    [@programdir/modules/private/action/require/impl/package.lua:805]: in function '_load_package'
    [@programdir/modules/private/action/require/impl/package.lua:894]: in function '_load_packages'
    [@programdir/modules/private/action/require/impl/package.lua:1195]: in function 'load_packages'
    [...modules/private/action/require/impl/install_packages.lua:659]:
    [@programdir/modules/private/action/require/install.lua:85]:
    [@programdir/actions/config/main.lua:387]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/core/base/task.lua:501]: in function 'run'
    [@programdir/core/main.lua:300]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:404]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:913: in function 'os.raiselevel'
	(...tail calls...)
	@programdir/core/main.lua:302: in upvalue 'cotask'
	@programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>
make: *** [x-deploy-android] Error 255

### 期待的结果

获取到openssl 1.1.1t 版本并编译 Android

### 附加信息和错误日志

xrepo search openssl

The package names:
openssl:
-> openssl-1.1.1n: A robust, commercial-grade, and full-featured toolkit for TLS and SSL. (in xmake-repo)

_No response_

**Comment by waruqi** [comment]
更新下仓库试试

```
xrepo update-repo
xmake f -c -p android --ndk=...
```

不行就再更新下 xmake 版本，有点老了。
