### ISSUE TITLE
請問如何在 xmake 中添加 .def 檔案，用來明確定義 dll 導出資訊?

### ISSUE THREAD

**Issue by orzuk-lmj** [xmake-io/xmake#363]
目前我用底下這種方式寫，但用-v查看的時候，發現/DEF 沒有被正確的添加到命令列中
``` lua
on_load(function (target)
        -- check for shared library definitions
        local targetkind = target:targetkind()
        if targetkind == "shared" then
            if is_plat("windows") then
                local defpath = path.absolute(path.join(os.projectdir(), "src/ogg.def"))
                local deflg = "/DEF:" .. defpath
                print("***** " .. deflg)
                target:add("ldflags", deflg)
            end
        end
end)
```
- 打印出來的 defpath 指向絕對位置，並且確認存在這個檔案
- deflg 的內容是 `/DEF:"D:\External\libogg-1.3.3\sources\src\ogg.def"`
- 手動直接複製 deflg 內容貼到 VC additional command 中，則可以正確連結輸出DLL

- 附註: 後來找到一個暫時解決的方式，就是不檢查直接強制傳入，就可以link成功了
    ``` lua
    target:add("shflags", deflg, {force = true})
    ```

**Comment by orzuk-lmj** [comment]
目前使用 shflags 傳入參數的時候遇到兩個麻煩，不確定有沒有更好的解決方法：
- 打算置入雙引號 `/DEF:"......."` ，但是發現整理好的字串deflg傳到command之後雙引號錢多了一個斜線 `\"`
- 目前使用絕對路徑最方便，相對路徑的話會造成 VC plugin 和 command 兩種編譯時候其中一方找不到檔案。

**Comment by waruqi** [comment]
> 目前我用底下這種方式寫，但用-v查看的時候，發現/DEF 沒有被正確的添加到命令列中
> 
> ```lua
> on_load(function (target)
>         -- check for shared library definitions
>         local targetkind = target:targetkind()
>         if targetkind == "shared" then
>             if is_plat("windows") then
>                 local defpath = path.absolute(path.join(os.projectdir(), "src/ogg.def"))
>                 local deflg = "/DEF:" .. defpath
>                 print("***** " .. deflg)
>                 target:add("ldflags", deflg)
>             end
>         end
> end)
> ```
> 
> * 打印出來的 defpath 指向絕對位置，並且確認存在這個檔案
> * deflg 的內容是 `/DEF:"D:\External\libogg-1.3.3\sources\src\ogg.def"`
> * 手動直接複製 deflg 內容貼到 VC additional command 中，則可以正確連結輸出DLL
> * 附註: 後來找到一個暫時解決的方式，就是不檢查直接強制傳入，就可以link成功了
>   ```lua
>   target:add("shflags", deflg, {force = true})
>   ```

`/DEF:`的flags检测，是有做处理的，不过之前大写方式没考虑到，所以检测失败，需要设置force=true强制写入，我刚dev改进了下，对大写做了处理，你可以去掉force后再试试

**Comment by waruqi** [comment]
> 目前使用 shflags 傳入參數的時候遇到兩個麻煩，不確定有沒有更好的解決方法：
> 
> * 打算置入雙引號 `/DEF:"......."` ，但是發現整理好的字串deflg傳到command之後雙引號前面多了一個斜線 `\"`

为什么要加双引号，就算写绝对路径，不加双引号也是可以的 `/def:f:\\cc\ss\ss.def`，如果路径中有空格， 你加个单引号试试

> * 目前使用絕對路徑最方便，相對路徑的話會造成 VC plugin 和 command 兩種編譯時候其中一方找不到檔案。

由于vs的工程默认生成在 project/vs201x下，项目根路径变动了，里面的源文件已经搜索相对路径 跟 命令行编译下，是有差异的。。

所以所有vs编译用到的 /I  /libpath的路径都是需要修正的。。目前对def的路径没去修正，我刚改进了下 你可以试试，dev分支。。

**Comment by orzuk-lmj** [comment]
> 为什么要加双引号，就算写绝对路径，不加双引号也是可以的 `/def:f:\\cc\ss\ss.def`，如果路径中有空格， 你加个单引号试试

使用單引號的話，檢查的時候有通過，但link指令實際執行的時候出錯。另外注意到了就算給了-v之後，link 的詳細參數出錯後就看不到，而且打印出來的 C28219D87C16E1C601975AFA63E23825.args.txt 也在執行後刪除了，目前無法得知實際執行的參數是什麼。
```
checking for the flags (/DEF:'D:\Externals Test\libvorbis-1.3.6\sources\lib\src\vorbis.def') ... ok

[ 20%]: linking.debug vorbis.dll
"link.exe -dll" @C:\\Users\\LOCALU~1\\AppData\\Local\\Temp\\.xmake\\190311\\_C28219D87C16E1C601975AFA63E23825.args.txt
error: LINK : fatal error LNK1104: cannot open file ''D:\\Externals Test\\rebuild_libraries\\libvorbis-1.3.6\\sources\\lib\\src\\vorbis.def''
```

**Comment by orzuk-lmj** [comment]
目前暫時的解法是：
- 避免使用絕對路徑
- 不要把專案放在有空白的路徑中

但是難保證使用者的路徑中不存在空白，win10有太多常用路徑都有，這是稍微麻煩的地方

**Comment by waruqi** [comment]
双引号转义，是因为命令行编译的时候需要处理，vs里面，如果双引号转义不支持，你可以看看 https://github.com/xmake-io/xmake/blob/0153b21317a804fc38737bc5e6b47bb52b2c6324/xmake/plugins/project/vstudio/impl/vs201x_vcxproj.lua#L155-L161 这块，做一些改进修正。。我最近暂时没时间处理这块。。

**Comment by waruqi** [comment]
我测了下，def中加入空格，没什么问题，命令行编译和vsproj编译，都能正常导出lib库。。

```lua

target("test11")
    set_kind("shared")
    add_files("src/interface.c") 
    add_shflags("-def:\"f:\\s s\\xxx.def\"")

target("test11_demo")
    set_kind("binary")
    add_deps("test11")
    add_files("src/test.c") 
```

**Comment by orzuk-lmj** [comment]
感謝!!  仔細測了下，發現是我忽略了路徑中需要有 `\\` 的問題。
