### ISSUE TITLE
引入vcpkg的包不会自动处理依赖

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#3634]
### Xmake 版本

2.7.8

### 操作系统版本和架构

windows 11

### 描述问题

本来打算用xmake自己的包，但是自带的mysql包不支持windows，于是像下面这样用vcpkg的包，但是不能自动处理依赖，在vcpkg的ports文件里面可以看到libmysql依赖多个其他包，全部递归手动添加依赖不是很可行。

main.cpp
```
#include <iostream>
#include "mysql/mysql.h"

using namespace std;

int main(int argc, char** argv)
{
    MYSQL ms;
    mysql_init(&ms);
    return 0;
}
```
xmake.lua
```
add_rules("mode.debug", "mode.release")
add_requires("vcpkg::libmysql")

target("testwin")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("vcpkg::libmysql")
```

### 期待的结果

1 能根据vcpkg ports里面的描述自动把依赖加上？
2 或者xmake自带的mysql能支持windows

**Comment by waruqi** [comment]
目前不支持，vcpkg 对外提供的信息太少，不太好处理。。目前只有 xmake 包才支持级联依赖。
