### ISSUE TITLE
像 cpm.cmake 包管理器那样可以直接指定 github 仓库或者 url

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#3643]
### 你在什么场景下需要该功能？

https://github.com/cpm-cmake/CPM.cmake
```
CPMAddPackage("gh:catchorg/Catch2@2.5.0")
```
```
CPMAddPackage(
  NAME Boost
  VERSION 1.81.0
  GITHUB_REPOSITORY "boostorg/boost"
  GIT_TAG "boost-1.81.0"
)
```

### 描述可能的解决方案

可以直接指定 github 仓库或者 url

**Comment by waruqi** [comment]
不考虑。它这个似乎也只是用 [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) 去拉源码到主工程而已。

xmake 的包安装时候就要编译的，c/c++ 包的碎片化和复杂性，不用脚本去处理，基本没法用。
