### ISSUE TITLE
带module相关 生成cmakelist错误，无法读取

### ISSUE THREAD

**Issue by RI-ss** [xmake-io/xmake#3645]
### Xmake 版本

xmake v2.7.8+master.fce193249,

### 操作系统版本和架构

Windows 11 专业版22H2  22621.1555 

### 描述问题

当xmake.lua中含有dd_files("src/*.ixx")或set_policy("build.c++.modules", true)时，生成的cmakelist，clion无法读取并报错
![image](https://user-images.githubusercontent.com/71321125/232714057-9847a6c8-642a-4e8a-a34b-737c26264b13.png)
![image](https://user-images.githubusercontent.com/71321125/232713793-741727a3-f61d-4f46-8188-8784c87787dd.png)
![image](https://user-images.githubusercontent.com/71321125/232714280-d0c902a6-acb4-4d03-af17-c2bd70b31d4d.png)
当删掉上述语句时，生成cmakelist可正常读取

### 期待的结果

生成正确的cmakelist，clion可正常读取

### 工程配置

[example1.zip](https://github.com/xmake-io/xmake/files/11260077/example1.zip)

### 附加信息和错误日志

完整报错
"D:\Program Files\apps\CLion\ch-0\231.8109.222\bin\cmake\win\x64\bin\cmake.exe" -DCMAKE_BUILD_TYPE=Debug "-DCMAKE_MAKE_PROGRAM=D:/Program Files/apps/CLion/ch-0/231.8109.222/bin/ninja/win/x64/ninja.exe" -G Ninja -S D:\c++\example1 -B D:\c++\example1\cmake-build-debug
CMake Error at CMakeLists.txt:14 (add_custom_command):
  Syntax error in cmake code at

    D:/c++/example1/CMakeLists.txt:16

  when parsing string

    -Fdbuild\windows\x64\debug\compile.example1.pdb

  Invalid character escape '\w'.

CMake Error at CMakeLists.txt:14 (add_custom_command):
  Syntax error in cmake code at

    D:/c++/example1/CMakeLists.txt:18

  when parsing string

    -Fdbuild\windows\x64\debug\compile.example1.pdb

  Invalid character escape '\w'.

CMake Error at CMakeLists.txt:14 (add_custom_command):
  Syntax error in cmake code at

    D:/c++/example1/CMakeLists.txt:20

  when parsing string

    -Fdbuild\windows\x64\debug\compile.example1.pdb

  Invalid character escape '\w'.

CMake Error at CMakeLists.txt:14 (add_custom_command):
  Syntax error in cmake code at

    D:/c++/example1/CMakeLists.txt:22

  when parsing string

    -Fdbuild\windows\x64\debug\compile.example1.pdb

  Invalid character escape '\w'.

CMake Error at CMakeLists.txt:14 (add_custom_command):
  Syntax error in cmake code at

    D:/c++/example1/CMakeLists.txt:23

  when parsing string

    src\unit.ixx

  Invalid character escape '\u'.

CMake Error at CMakeLists.txt:14 (add_custom_command):
  Syntax error in cmake code at

    D:/c++/example1/CMakeLists.txt:25

  when parsing string

    -Fdbuild\windows\x64\debug\compile.example1.pdb

  Invalid character escape '\w'.

CMake Error at CMakeLists.txt:14 (add_custom_command):
  Syntax error in cmake code at

    D:/c++/example1/CMakeLists.txt:28

  when parsing string

    -Fdbuild\windows\x64\debug\compile.example1.pdb

  Invalid character escape '\w'.

CMake Error at CMakeLists.txt:14 (add_custom_command):
  Syntax error in cmake code at

    D:/c++/example1/CMakeLists.txt:31

  when parsing string

    -Fdbuild\windows\x64\debug\compile.example1.pdb

  Invalid character escape '\w'.

-- Configuring incomplete, errors occurred!
See also "D:/c++/example1/cmake-build-debug/CMakeFiles/CMakeOutput.log".

[Failed to reload]

**Comment by waruqi** [comment]
project generator 目前还不能很好的支持 c++ modules
