### ISSUE TITLE
xmake 2.7.8 wont run Qt based applications

### ISSUE THREAD

**Issue by danieleTrimarchi** [xmake-io/xmake#3655]
### Xmake Version

2.7.8

### Operating System Version and Architecture

Windows 10

### Describe Bug

Please find the attached example: [Qt_xmake_run.zip](https://github.com/xmake-io/xmake/files/11275459/Qt_xmake_run.zip)

Compile and execute with xmake 2.7.7 : suceess

```
>xmake update 2.7.7  
>xmake
>xmake run
```

Compile and execute with xmake 2.7.8 : failure

```
>xmake update 2.7.8 
>xmake
>xmake run
```

In the second case, the application wont run as the Qt dlls are not found - see screen shot below : 

![image](https://user-images.githubusercontent.com/24756418/233142570-3058e8b0-2a7b-4c14-927f-474012ed4037.png)

 

### Expected Behavior

xmake run should be functional despite the version of xmake

**Comment by waruqi** [comment]
Can you try dev version? It should have been fixed.

xmake update -s dev

**Comment by danieleTrimarchi** [comment]
Thanks @waruqi ! 

I have tried with both  `v2.7.8+dev.025fbe955` and  `v2.7.8+HEAD.87dff1ef4`. 

I confirm that there is no problem with these versions.
