### ISSUE TITLE
add_packages 在target是静态对象时 应该启用include包含 

### ISSUE THREAD

**Issue by ranwei1025** [xmake-io/xmake#366]
如下：
target("test")
    set_kind("static")
    add_packages ("xx")
test 静态库 需要xx包的头文件包含，应该把头文件包含进 test
现在没有包含 出现错误

**Comment by waruqi** [comment]
请先详细描述的你的 xx 包情况，并提供详细xmake.lua设置 以及 xmake -v编译的完整编译参数信息。。

**Comment by ranwei1025** [comment]
比如 xx 包 xmake.lua 如下：
option("xx")
add_includedirs("inc/$(plat)", "inc")
现在 test静态库 需要xx包的头文件包含目录 不然就会编译不过 add_packages ("xx") 后头文件包含目录没有添加到test target里 导致找不到文件

**Comment by ranwei1025** [comment]
测试版本 xmake v2.2.3.201902041856

**Comment by waruqi** [comment]
如果option没设置links，是不会做检测的，由于没设置set_default(true)，所以你这包应该是被禁用了

你可以通过set_default启用下你的包

```lua
option("xx") 
    set_default(true)
    add_includedirs("inc/$(plat)", "inc")``

**Comment by ranwei1025** [comment]
加了 set_default(true) 还是不行

**Comment by ranwei1025** [comment]
不是纯 includedirs 包含了连接库 和 文件编译

**Comment by waruqi** [comment]
你发个完整的xmake.lua给我看下，或者发个精简版可复现的demo空工程给我 我分析下
