### ISSUE TITLE
unknown tool /home/leleliu008/.ppkg/core/bin/proxy-cc

### ISSUE THREAD

**Issue by leleliu008** [xmake-io/xmake#3668]
### Xmake 版本

2.7.8

### 操作系统版本和架构

Ubuntu22.04

### 描述问题

编译 https://github.com/xmake-io/xmake/releases/download/v2.7.8/xmake-v2.7.8.tar.gz 的时候报告我： `unknown tool /home/leleliu008/.ppkg/core/bin/proxy-cc`,  大致看了一下，发现 https://github.com/xmake-io/xmake/blob/master/configure#L425 这一行报告的错误

### 期待的结果

能自动判断出编译器类型

**Comment by waruqi** [comment]
proxy-cc 这什么编译器？这种就算了，老老实实用 gcc/clang 编译，或者你 soft link 到 gcc 上去
