### ISSUE TITLE
add_cxflags broken during CMakeLists generate

### ISSUE THREAD

**Issue by MaxwellGengYF** [xmake-io/xmake#3669]
### Xmake Version

2.7.8

### Operating System Version and Architecture

Any platform

### Describe Bug

in on_load():

target:add("cxflags", "/Zc:preprocessor", {
    tools = "cl"
});

"/Zc:preprocessor" will still be added to CMakeLists.txt even when target is using llvm-toolchain.

### Expected Behavior

Such flags should not be added.

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/pull/3665 这个 patch 里，我支持上了，顺带正好帮我测下其他的改动是否会影响现有工程。。

```
xmake update -s github:xmake-io/xmake#cmakelists
```
