### ISSUE TITLE
add_files,add_headers层级结构问题

### ISSUE THREAD

**Issue by Ultraman95** [xmake-io/xmake#367]
比如add_files("../../../../source/platform/*.cpp")，在生成的vs2017工程目录结构会有很多层，能不能只有一层

**Comment by waruqi** [comment]
不能 目前就是多级分层

**Comment by Ultraman95** [comment]
可以做到不分层吗？

**Comment by Ultraman95** [comment]
还有就是vs2017工程的解决方案名称可以自己定义吗？目前都叫vs2017

**Comment by waruqi** [comment]
不能 目前没这个打算 xmake重点在直接构建，生成vsproj只是附带的一个插件功能而已，不会太花精力在这上面，只要生成的vcproj能够正常编译就行了

而且分层有助于管理源码，我特地做成分层的 不会改的

**Comment by Ultraman95** [comment]
我们用xmake，除了直接构建之外，有时候使用vs2017调试也是很必须的，vs2017工程的解决方案名称可以自己定义吗？

**Comment by waruqi** [comment]
不能，名字和分层 不影响编译调试

**Comment by Ultraman95** [comment]
os.addenv 这个接口怎么文档里面没有呢？

**Comment by waruqi** [comment]
文档里主要还是描述上层的设置接口

对于脚本域的模块接口，由于较多，而且更新频繁，暂时没精力写全，难免有遗漏 

之后有时间会补充进去，用户也可以自己帮忙提个pr完善下文档。

如果有些接口文档中没找到，可以提issues咨询
