### ISSUE TITLE
xrepo支持通过hash去获取包使用信息

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#3670]
### 你在什么场景下需要该功能？

有时候想在vs里面用xrepo安装的包，需要获取包使用信息
主要有两个问题

1 xrepo无法获取本地测试包的使用信息
如果自己编写了包，`xmake l test/script.lua` 测试之后会在本地生成包的缓存，执行xrepo scan可以查看到包，比如下面的mysql mingw版本
![image](https://user-images.githubusercontent.com/97490782/233826922-960f413d-fc90-4e21-b609-6a76dacb3128.png)
但是无法获取到包的使用信息
![image](https://user-images.githubusercontent.com/97490782/233826962-f7aa7236-8bb8-4bf1-b47a-aa826d6ce03e.png)

2 在配置比较复杂的时候每次都要用-f指定很多参数比较繁琐
比如下面这样安装了coost库
```
xrepo install -v -y -f "vs_runtime='MTd',libcurl=true" -m debug -k static -a x86 -v coost
```
想获取包使用信息得这么写
```
xrepo fetch --cflags --ldflags -f "vs_runtime='MTd'" -m debug -k static -a x86 coost
```

### 描述可能的解决方案

支持通过hash获取包的使用信息，比如执行xrepo scan之后获得如下信息
![image](https://user-images.githubusercontent.com/97490782/233827040-c8ac6e02-939b-4b1a-a13d-1e2c11d8ac27.png)
直接输入
```
xrepo fetch 343f9fc228ff491fa7c84b590528c1c1
```
就能获得包的使用信息
![image](https://user-images.githubusercontent.com/97490782/233827065-1f2c8bad-f37e-4cb1-811c-52a3d687e705.png)

**Comment by waruqi** [comment]
不考虑。都跑到 xmake-repo 走脚本临时测试了，直接 包 xmake.lua 里面改改 config 默认值，调调就完事了。。hash 是内部实现机制用到的，不对外开放，否则后续如果不打算用 hash 方案了，改也不好改。。
