### ISSUE TITLE
xmake build 后，会在项目根目录下生成一个.ifc文件

### ISSUE THREAD

**Issue by yillis** [xmake-io/xmake#3671]
### Xmake 版本

2.7.8

### 操作系统版本和架构

windows11 22621.1555

### 描述问题

在运行xmake build TARGET后，会在根目录出现一个_2A70BC855C6B47118314FA08E23BEC9B.cpp.ifc文件

build前
![image](https://user-images.githubusercontent.com/43308441/233829016-840b07fd-d2d3-4d31-9691-b5c165e1947e.png)
build后
![image](https://user-images.githubusercontent.com/43308441/233829041-43bc6b8e-67e2-4288-9922-7423fef1ac4a.png)

### 期待的结果

可能是采用了module的原因，之前没用module一直好好的
这个问题目前似乎没别的影响，就是看着有点碍眼

**Comment by waruqi** [comment]
这里用测试 demo 没法复现问题，你可以直接调下 https://github.com/xmake-io/xmake/blob/master/xmake/rules/c%2B%2B/modules/modules_support/msvc.lua 这里，看看哪里写入了这个文件。

**Comment by yillis** [comment]
> 这里用测试 demo 没法复现问题，你可以直接调下 https://github.com/xmake-io/xmake/blob/master/xmake/rules/c%2B%2B/modules/modules_support/msvc.lua 这里，看看哪里写入了这个文件。

不好意思，请问这个具体怎么操作呢，没太理解到

**Comment by waruqi** [comment]
或者可以给个可复现的工程demo 并且提供下复现流程

**Comment by yillis** [comment]
好的，我建了个小的复现demo
https://github.com/yillis/xmake_ifc_issue
运行xmake build test_module就会出现那个ifc文件

**Comment by yillis** [comment]
> 或者可以给个可复现的工程demo 并且提供下复现流程

好的，我建了个小的复现demo
https://github.com/yillis/xmake_ifc_issue
运行xmake build test_module就会出现那个ifc文件
运行环境是win11+msvc

**Comment by waruqi** [comment]
应该可以了，再试试，`xmake update -s dev`

**Comment by yillis** [comment]
> 应该可以了，再试试，`xmake update -s dev`

可以了，辛苦！
