### ISSUE TITLE
xmake关于vs运行时链接的库是不是弄错了

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#3677]
### Xmake 版本

2.7.8

### 操作系统版本和架构

windows 11

### 描述问题

xmake文档是这样描述的
```
这个接口传入 MT/MTd 参数配置，xmake 会自动配置上 /MT /nodefaultlib:msvcrt.lib 参数
```
![image](https://user-images.githubusercontent.com/97490782/233847049-0c51f027-73f2-428f-bbcd-991dbf2eab02.png)
但是查看msdn的文档,MT的时候应该链接LIBCMT.lib呀
```
定义 _MT 并使编译器将库名称 LIBCMT.lib 
```
![image](https://user-images.githubusercontent.com/97490782/233847091-f7212713-5082-4f10-81dd-32a51af757bc.png)

### 期待的结果

是我理解错了吗？

**Comment by waruqi** [comment]
msvc 默认 link 的 msvcrt.lib ，你加了 /MT 就会报跟 libcmt.lib 冲突，所以还得额外去掉 msvcrt.lib

你仔细看，是 no default lib。。。/nodefaultlib:msvcrt.lib

跟你说的 libcmt.lib .并不冲突，就是为了用 libcmt
