### ISSUE TITLE
protobuf.cpp规则导出.h文件

### ISSUE THREAD

**Issue by leaf-potato** [xmake-io/xmake#3678]
### Is your feature request related to a problem? Please describe.

场景：proto文件编译成静态库作为依赖给其他库使用，期望能够output编译后的.pb.h文件

```lua
target("proto")
    set_kind("static")
    add_rules("c++")
    add_files("proto/*.proto", { proto_public = true })
```
使用`add_headerfiles()`可以添加需要发布的.h文件，但编译后.pb.h的目录不太好确定。

### Describe the solution you'd like

add_rules(protobuf.cpp) 新增配置项，在执行`xmake install`时可以将生产的.pb.h文件发布到output目录中

**Comment by waruqi** [comment]
我加了个 proto_autogendir，你可以指定 proto 自动生成的文件的根目录，然后从你指定的目录下，获取对应路径，设置到 add_headerfiles

```
target("proto")
    set_kind("static")
    add_rules("c++")
    add_files("proto/*.proto", { proto_autogendir = path.join(os.projectdir(), "build", "proto") })
    add_headerfiles("$(buildir)/proto/xxxx.h") --- 这里路径自己根据实际情况，自己调整下
```

**Comment by leaf-potato** [comment]
验证没问题 感谢~

**Comment by itfanr** [comment]
经测试发现， 无法支持 proto 的 import 语法。

```
|-- basic_msgs
|   |-- geometry.proto
|   |-- header.proto
|   `-- service.proto
|-- clean.sh
|-- common.cmake
|-- config_msgs
|   |-- README.md
|   |-- agv_config.proto
```

比如 agv_config.proto 里面，import basic_msgs/header.proto，那么 agv_config.proto 无法编译通过。报错是`basic_msgs/header.proto: File not found.`

**Comment by waruqi** [comment]
不相关的问题，请单独开 issues ，支持 import https://github.com/xmake-io/xmake/blob/1bae1746ea64f19e0fe7e24ec2b0bbf22e78dee4/tests/projects/c%2B%2B/protobuf/src/test.proto#L2

**Comment by itfanr** [comment]
> 不相关的问题，请单独开 issues ，支持 import
> 
> https://github.com/xmake-io/xmake/blob/1bae1746ea64f19e0fe7e24ec2b0bbf22e78dee4/tests/projects/c%2B%2B/protobuf/src/test.proto#L2

貌似你这个是引用父目录，而我的需求是子目录内的proto 文件引用平级的子目录中的proto 文件。
