### ISSUE TITLE
Support `private, public, interface` to improve dependency inheritance like cmake

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#368]
Inherit all compiler and linker settings, e.g. `add_cflags`, `add_defines`, `add_includedirs` ..

Roadmap

- [x] `add_xxx("", {public = true})`
  - [x] private = true (default)
  - [x] public = true (private + public)
  - [x] interface = true (only public)
- [x] `add_deps("", {inherit = false})`
  - [x] inherit = true (default)
- [x] `target:get("defines", {interface = true})`
- [x] `target:add("defines", "xxx", {public = true})`
- [x] `target:set("defines", "xxx", {private = true})`

References

https://github.com/xmake-io/xmake/issues/291

Examples

```lua
target("test")
    set_kind("static")
    add_files("src/*.c")
    add_includedirs("inc", {public = true})

-- inherit includedirs and link libtest.a
target("demo")
    set_kind("binary")
    add_deps("test") 

-- only affect the compilation order 
target("demo2")
    set_kind("binary")
    add_deps("test", {inherit = false})
```

**Comment by orzuk-lmj** [comment]
可以也實作 `target:add("xxx", "yyy", {public = true, inherit = true})` 這種語法嗎?

**Comment by waruqi** [comment]
> 可以也實作這種語法嗎?
> 
> ```
> target:add("xxx", "yyy", {public = true})
> ```

yes

**Comment by waruqi** [comment]
I have implemented this feature in dev branch.
