### ISSUE TITLE
While building `xmake`: `PROCESSOR_ARCHITECTURE_ARM64` not defined.

### ISSUE THREAD

**Issue by metakosmo** [xmake-io/xmake#3680]
### Xmake Version

a4a1414b6d81985e4e880c4960ca56016038bee6

### Operating System Version and Architecture

Windows 10

### Describe Bug

Using Microsoft Visual Studio 14.0, I got this error when trying to build `xmake` from source:

    src\xmake\engine.c(938): error C2065: 'PROCESSOR_ARCHITECTURE_ARM64': undeclared identifier

I had to apply this change to compile:

~~~
diff --git a/core/src/xmake/engine.c b/core/src/xmake/engine.c
index 8baac18c6..a68de8c12 100644
--- a/core/src/xmake/engine.c
+++ b/core/src/xmake/engine.c
@@ -935,9 +935,11 @@ static tb_void_t xm_engine_init_arch(xm_engine_t* engine)
     case PROCESSOR_ARCHITECTURE_AMD64:
         sysarch = "x64";
         break;
+#if defined(PROCESSOR_ARCHITECTURE_ARM64)
     case PROCESSOR_ARCHITECTURE_ARM64:
         sysarch = "arm64";
         break;
+#endif
     case PROCESSOR_ARCHITECTURE_ARM:
         sysarch = "arm";
         break;
~~~

### Expected Behavior

Compile without errors without having to modify the source code.

**Comment by waruqi** [comment]
you can open a pr.
