### ISSUE TITLE
让写package的时候能指定github的某个commit

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#3682]
### 你在什么场景下需要该功能？

现在添加包的时候可以写github的url
![image](https://user-images.githubusercontent.com/97490782/233968369-26100d2f-54bf-475e-871d-47c7c1615dc2.png)
但是没法指定用哪个commit
比如对于libgo这个库，https://github.com/yyzybb537/libgo
他的master分支在更新，只是没有tag和release。这种貌似现在没法指定

### 描述可能的解决方案

是不是在写package的时候允许这样写好一些
```
add_urls("https://github.com/yyzybb537/libgo.git")
add_versions("2023_04_24", "commit:17d915bc81d943d482bc3e63dd7a5a8fad2918fe")
```
类似这样的写法

**Comment by star-hengxing** [comment]
这种包很少见，没必要特别照顾吧，参考一下这个
https://github.com/xmake-io/xmake-repo/pull/1759#discussion_r1089691251

**Comment by heheda123123** [comment]
我去，从文档中package的部分没找到，看了下大佬你给的链接，在add_requires的地方找到了，已经支持指定commit了
![image](https://user-images.githubusercontent.com/97490782/233971477-29db2c38-a45a-4295-a4aa-8b9595e58029.png)
