### ISSUE TITLE
仓库中的包指定依赖时很多都没有指定版本，以后可能存在兼容性隐患

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#3684]
### 你在什么场景下需要该功能？

最近给xmake-repo仓库提了几个pr，写的时候发现个问题，已有的大部分包，添加依赖时都是下面这样只指定了依赖的名字
![image](https://user-images.githubusercontent.com/97490782/234249500-63a6e597-32fc-4fad-8a91-d17cce09bd9f.png)
很明显，如果依赖更新了版本，存在不兼容的地方，那这个包肯定就构建不了。但是大家写的时候往往也比较随意并没太关注版本号。

### 描述可能的解决方案

要么是本地 xmake l scripts/test.lua 通过的时候自动把版本回填到测试的脚本中。（或者起码在最后给个提示，当前包用的依赖的版本号是哪些，叫开发者补充到xmake.lua中）

或者就是合并一个包的pr时自动填上依赖的版本。
或者起码自动加个注释，不然过个几年，存在不兼容的问题都不知道该回退用哪个包

对于现在已有的包，合并pr前都跑了一遍check，可以考虑写脚本，自动把相关的版本号提取出来，至少放个注释在构建脚本里面

**Comment by waruqi** [comment]
自己配置下，开启版本锁定。。https://xmake.io/#/zh-cn/package/remote_package?id=%E4%BE%9D%E8%B5%96%E5%8C%85%E7%9A%84%E9%94%81%E5%AE%9A%E5%92%8C%E5%8D%87%E7%BA%A7

**Comment by heheda123123** [comment]
> 自己配置下，开启版本锁定。。https://xmake.io/#/zh-cn/package/remote_package?id=%E4%BE%9D%E8%B5%96%E5%8C%85%E7%9A%84%E9%94%81%E5%AE%9A%E5%92%8C%E5%8D%87%E7%BA%A7

这个是使用者锁定版本吧。我的意思是针对仓库里的包而言。
比如仓库里有个包a，她依赖了包b，万一哪天有人在xmake-reop提了个pr升级了包b，这个升级还是不兼容的。
这时候如果有人使用了包a，包a里添加依赖b的时候又没指定版本，最后包a就编译不成功。

**Comment by waruqi** [comment]
> > 自己配置下，开启版本锁定。。https://xmake.io/#/zh-cn/package/remote_package?id=%E4%BE%9D%E8%B5%96%E5%8C%85%E7%9A%84%E9%94%81%E5%AE%9A%E5%92%8C%E5%8D%87%E7%BA%A7
> 
> 这个是使用者锁定版本吧。我的意思是针对仓库里的包而言。 比如仓库里有个包a，她依赖了包b，万一哪天有人在xmake-reop提了个pr升级了包b，这个升级还是不兼容的。 这时候如果有人使用了包a，包a里指定依赖b的时候又没指定版本，最后包a就编译不成功。
> 
> 应该在当初添加包a的时候就把当时a说依赖的b的版本给指定清楚。

不会，package.requires_lock 不仅锁定用户当前时刻依赖的包版本，还锁定那个时间点，xmake-repo 仓库的 commit 

即使你后续提 pr 更新 xmake-repo ，对于用户还是用的锁定的 xmake-repo 历史 commit 中的包配置定义，依赖包版本，甚至包的 on_install 脚本也是一起锁定的
