### ISSUE TITLE
生成cmakelist 出现了一个不能被识别的命令行选项-fcxx-exceptions

### ISSUE THREAD

**Issue by RI-ss** [xmake-io/xmake#3692]
### Xmake 版本

xmake v2.7.8+master.fce193249,

### 操作系统版本和架构

版本	Windows 11 专业版 版本	22H2 

### 描述问题

这是一个C++编译错误提示，主要信息为：

x86_64-w64-mingw32-g++: error: unrecognized command-line option '-fcxx-exceptions'; did you mean '-fno-exceptions'?

意思是在使用x86_64-w64-mingw32-g++编译器时，出现了一个不能被识别的命令行选项-fcxx-exceptions

### 期待的结果

正常生成 cmakelist

### 工程配置

add_rules("mode.debug", "mode.release")

set_languages("c17", "c++20")

target("test2")
    set_kind("binary")
    set_toolchains("mingw")
    add_files("src/*.cpp")

生成的cmakelist
# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

# project
cmake_minimum_required(VERSION 3.15.0)
cmake_policy(SET CMP0091 NEW)
project(test2 LANGUAGES CXX C)

# target
set(CMAKE_C_COMPILER "C:/msys64/mingw64/bin/x86_64-w64-mingw32-gcc")
set(CMAKE_CXX_COMPILER "C:/msys64/mingw64/bin/x86_64-w64-mingw32-g++")
add_executable(test2 "")
set_target_properties(test2 PROPERTIES OUTPUT_NAME "test2")
set_target_properties(test2 PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/build/windows/x64/debug")
if(CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
    target_compile_options(test2 PRIVATE /EHsc)
else()
    target_compile_options(test2 PRIVATE -fcxx-exceptions)
endif()
set_target_properties(test2 PROPERTIES CXX_EXTENSIONS OFF)
target_compile_features(test2 PRIVATE cxx_std_20)
if(MSVC)
    target_compile_options(test2 PRIVATE $<$<CONFIG:Debug>:-Od>)
else()
    target_compile_options(test2 PRIVATE -O0)
endif()
if(MSVC)
    target_compile_options(test2 PRIVATE -Zi)
else()
    target_compile_options(test2 PRIVATE -g)
endif()
if(MSVC)
    set_property(TARGET test2 PROPERTY
        MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
endif()
target_sources(test2 PRIVATE
    src/main.cpp
)

### 附加信息和错误日志

"D:\Program Files\apps\CLion\ch-0\231.8109.222\bin\cmake\win\x64\bin\cmake.exe" -DCMAKE_BUILD_TYPE=Debug "-DCMAKE_MAKE_PROGRAM=D:/Program Files/apps/CLion/ch-0/231.8109.222/bin/ninja/win/x64/ninja.exe" -DCMAKE_C_COMPILER=C:/msys64/mingw64/bin/gcc.exe -DCMAKE_CXX_COMPILER=C:/msys64/mingw64/bin/g++.exe -G Ninja -S D:\c++\test2 -B D:\c++\test2\cmake-build-debug
-- Configuring done
-- Generating done
-- Build files have been written to: D:/c++/test2/cmake-build-debug

Problems were encountered while collecting compiler information:
	x86_64-w64-mingw32-g++.exe: error: unrecognized command-line option '-fcxx-exceptions'; did you mean '-fno-exceptions'?

[Finished]

====================[ Build | test2 | Debug ]===================================
"D:\Program Files\apps\CLion\ch-0\231.8109.222\bin\cmake\win\x64\bin\cmake.exe" --build D:\c++\test2\cmake-build-debug --target test2 -j 10
[1/2] Building CXX object CMakeFiles/test2.dir/src/main.cpp.obj
FAILED: CMakeFiles/test2.dir/src/main.cpp.obj 
C:\msys64\mingw64\bin\x86_64-w64-mingw32-g++   -g -fdiagnostics-color=always -fcxx-exceptions -O0 -g -std=c++20 -MD -MT CMakeFiles/test2.dir/src/main.cpp.obj -MF CMakeFiles\test2.dir\src\main.cpp.obj.d -o CMakeFiles/test2.dir/src/main.cpp.obj -c D:/c++/test2/src/main.cpp
x86_64-w64-mingw32-g++: error: unrecognized command-line option '-fcxx-exceptions'; did you mean '-fno-exceptions'?
ninja: build stopped: subcommand failed.

**Comment by waruqi** [comment]
用 mingw 得切到 `-p mingw` 平台
