### ISSUE TITLE
Incorrect cmake metal compilation command generated

### ISSUE THREAD

**Issue by Su5eD** [xmake-io/xmake#3694]
### Xmake Version

v2.7.8+dev.63e4d08

### Operating System Version and Architecture

macOS Ventura 13.1 x64

### Describe Bug

When generating a CMakeLists file for an Xmake project that includes `.metal` files, the resulting CMake configuration contains an invalid command.
```cmake
add_custom_command(OUTPUT output_HelloTriangle_14DA4EA0
    COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_SOURCE_DIR}/build/.objs/HelloTriangle/macosx/x86_64/release/Renderer
    COMMAND "/usr/bin/xcrun -sdk macosx  metal" -c -ffast-math -gline-tables-only -target air64-apple-macos13.1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -o ${CMAKE_SOURCE_DIR}/build/.objs/HelloTriangle/macosx/x86_64/release/Renderer/AAPLShaders.metal.o.air ${CMAKE_SOURCE_DIR}/Renderer/AAPLShaders.metal
    VERBATIM
)
```
Here, the 2nd `COMMAND` tries to run a program with the metal sdk arguments included in the path, which leads to an error when building the project using CMake.  
```
/bin/sh: /usr/bin/xcrun -sdk macosx  metal: No such file or directory
```

Wrong: `COMMAND "/usr/bin/xcrun -sdk macosx  metal" -c -ffast-math ...` (rest of the command omitted)
Correct: `COMMAND "/usr/bin/xcrun" -sdk macosx  metal -c -ffast-math ...`

### Steps to reproduce
1. Clone the xmake repository
`git clone https://github.com/xmake-io/xmake`
2. Navigate to the metal_app test project directory
`cd xmake/tests/projects/objc/metal_app`
3. Generate the `CMakeLists.txt` file
`xmake project -k cmakelists`
4. OPTIONAL: If necessary, set the project language in the generated CMakeLists.txt file
`project(HelloTriangle LANGUAGES CXX)`
5. Configure CMake. I have used the Makefiles generator here for simplicity but the choice doesn't generally matter.
`cmake -G "Unix Makefiles" -B_build`
6. Try building the CMake project
`cmake --build _build`
7. Get an error
`/bin/sh: /usr/bin/xcrun -sdk macosx  metal: No such file or directory`

### Expected Behavior

The generated CMake configuration should not contain arguments inside the command as demonstrated above.  
Wrong: `COMMAND "/usr/bin/xcrun -sdk macosx  metal" -c -ffast-math ...` (rest of the command omitted)
Correct: `COMMAND "/usr/bin/xcrun" -sdk macosx  metal -c -ffast-math ...`

### Project Configuration

I am using the xmake [`metal_app`](https://github.com/xmake-io/xmake/tree/5519c957c6fb9e4eb9098dcafba17aa483993267/tests/projects/objc/metal_app) test project available inside this repository.

### Additional Information and Error Logs

- Generated [CMakeLists.txt](https://pastebin.com/bh53Vvx9) using the `xmake project -k cmakelists` command
- [CMake build output](https://pastebin.com/vG0fxtQ8)

**Comment by waruqi** [comment]
I have fixed it, try it again. `xmake update -s dev`

**Comment by Su5eD** [comment]
It works now, thanks
