### ISSUE TITLE
每次在项目目录下构建必须要求使用xmake -P .而非xmake

### ISSUE THREAD

**Issue by OHNope** [xmake-io/xmake#3695]
### Xmake 版本

xmake v2.7.8+20230406

### 操作系统版本和架构

MacOS Ventura 13.1 (22C65)

### 描述问题

无法在工作目录下正常如教程或演示中的操作使用xmake

### 期待的结果

给出解决方案，原因或指出我错误

### 工程配置

xmake create projectname默认生成的目录下的make.lua

### 附加信息和错误日志

# xby @ XBYdeMacBook-Pro in ~/hello [22:20:19] 
$ xmake create hello
create hello ...
  [+]: xmake.lua
  [+]: src/main.cpp
  [+]: .gitignore
create ok!

# xby @ XBYdeMacBook-Pro in ~/hello [22:21:09] 
$ cd hello

# xby @ XBYdeMacBook-Pro in ~/hello/hello [22:21:14] C:127
$ xmake             
[ 25%]: cache compiling.release example.cpp
[ 25%]: cache compiling.release gc.cpp
[ 25%]: cache compiling.release test.cpp
error: gc.cpp:1:10: fatal error: 'include/ds.h' file not found
#include "include/ds.h"
         ^~~~~~~~~~~~~~
1 error generated.
  > in gc.cpp
warning: You are working in the project directory(/Users/xby) and you can also
force to build in current directory via run `xmake -P .`

# xby @ XBYdeMacBook-Pro in ~/hello/hello [22:21:16] C:255
$ xmake -P .
checking for platform ... macosx
checking for architecture ... x86_64
checking for Xcode directory ... /Applications/Xcode.app
checking for Codesign Identity of Xcode ... gdb_codesign
checking for SDK version of Xcode for macosx (x86_64) ... 13.1
checking for Minimal target version of Xcode for macosx (x86_64) ... 13.1
[ 25%]: cache compiling.release src/main.cpp
[ 50%]: linking.release hello
[100%]: build ok, spent 1.247s

# xby @ XBYdeMacBook-Pro in ~/hello/hello [22:21:31] 
$

**Comment by waruqi** [comment]
> warning: You are working in the project directory(/Users/xby) and you can also

根据提示，把 `/Users/xby/xmake.lua` 删了，如果 xby 不是工程目录的话。

**Comment by OHNope** [comment]
谢谢！是我弄错了
