### ISSUE TITLE
xmake doesn't use changed default generator when building CMake project

### ISSUE THREAD

**Issue by paul-reilly** [xmake-io/xmake#3697]
### Xmake Version

v2.7.8+dev.5075fc8

### Operating System Version and Architecture

Linux 6.1.25-1-MANJARO #1 SMP PREEMPT_DYNAMIC  x86_64 GNU/Linux

### Describe Bug

When I run `xmake` in a project root, xmake will detect whether the project uses xmake, make, CMake or others and execute the correct commands. This is good.

However: 

- The CMake default generator on Linux is Makefiles. 
- I have the default generator set to Ninja.

xmake expects Makefiles so after running `xmake`, I get the error:

>error: execv(make -j18 VERBOSE=1) failed(2)

### Expected Behavior

In order of personal preference:

1st - xmake should ideally be able to detect what the default cmake generator is and execute the correct build command
2nd - prefer Ninja if available and pass the generator to cmake.
3rd - pass whatever the default is for the platform to override any changed default

**Comment by waruqi** [comment]
> I have the default generator set to Ninja.

How did you change the default generator for cmake? envs?

> error: execv(make -j18 VERBOSE=1) failed(2)

You don't have make installed?

**Comment by SirLynix** [comment]
> You don't have make installed?

It probably failed not because make was not installed but because no Makefile was generated by CMake (because it generated Ninja files)

**Comment by waruqi** [comment]
trybuild/cmake just support cmake/makefile generator now. It also does not support modification and automatic generator detection now. This may require a lot of changes.

**Comment by waruqi** [comment]
try it again. `xmake update -s github/xmake-io:xmake#cmake`

**Comment by paul-reilly** [comment]
That's it working, thanks for getting it sorted so quickly!
