### ISSUE TITLE
xmake的远程库，是否是分版本的呢

### ISSUE THREAD

**Issue by Ultraman95** [xmake-io/xmake#370]

**Comment by Ultraman95** [comment]
比如我使用openssl库，有1.1的版本，又有1.0的版本，如果有分版本的，如何使用

**Comment by Ultraman95** [comment]
conan好像xmake也支持的，conan好像可以和jfrog组合着用，如果大神知道，能写一篇文章吗？

**Comment by waruqi** [comment]
> 比如我使用openssl库，有1.1的版本，又有1.0的版本，如果有分版本的，如何使用

支持语义版本

`add_requires("openssl 1.x")`
`add_requires("openssl 1.0")`

**Comment by waruqi** [comment]
> conan好像xmake也支持的，conan好像可以和jfrog组合着用，如果大神知道，能写一篇文章吗？

conan这块，xmake只是初步支持，generator还没集成到conan官方库里面去，还需要等待一段时间

详细进展见：https://github.com/xmake-io/xmake/issues/339

现在你要使用，需要自己安装dev版本xmake，并且需要自己导出conan-xmake-genrator，并且设置 build_requires才能使用

建议等我新版本发布之后再用

**Comment by Ultraman95** [comment]
谢谢，好期待呀。vcpkg支持分版本吗？比如不同版本的openssl

**Comment by Ultraman95** [comment]
谢谢，好期待呀。vcpkg支持分版本吗？比如不同版本的openssl

**Comment by waruqi** [comment]
> 谢谢，好期待呀。vcpkg支持分版本吗？比如不同版本的openssl

忘记了，我记得可以，语义版本不支持，指定固定版本号应该可以，你可以试试

**Comment by Ultraman95** [comment]
下个版本支持吗？

**Comment by waruqi** [comment]
还不确定，如果有时间我会看下vcpkg这块，这个依赖vcpkg自身的支持力度，xmake只是透传而已

**Comment by waruqi** [comment]
> conan好像xmake也支持的，conan好像可以和jfrog组合着用，如果大神知道，能写一篇文章吗？

conan支持我最近改进过了，你可以试试，首先需要装下 conan 和 xmake 

然后在你的项目xmake.lua里面，参考下面的example编写依赖库：

```lua
add_requires("CONAN::zlib/1.2.11@conan/stable", {alias = "zlib", debug = true})
add_requires("CONAN::OpenSSL/1.0.2n@conan/stable", {alias = "openssl", configs = {options = "OpenSSL:shared=True"}})

target("test")
    set_kind("binary")
    add_files("src/*.c") 
    add_packages("openssl", "zlib")
```

然后执行 xmake 编译即可。
