### ISSUE TITLE
改进vsxmake生成的Visual Studio工程对c11/c17标准的支持

### ISSUE THREAD

**Issue by zhangyingfan** [xmake-io/xmake#3707]
### 你在什么场景下需要该功能？

vsxmake生成的工程即使设置了c语言标准（`set_languages("c17")`），生成的工程文件在Visual Stdio中打开后也会显示没有启用相应的配置，而c++的设置是正确的：
![project](https://user-images.githubusercontent.com/49017591/236176589-a4670c09-b226-4237-b939-9e4f5bd23c0b.png)
这种情况下，如果写c代码时使用新语法会提示语法错误，不过最终编译可以通过

原因是vsxmake所使用的vs模板Xmake.props里只有对c++标准的配置（类似`<LanguageStandard Condition="...">stdcpp11</LanguageStandard>`），没有c语言的配置

### 描述可能的解决方案

在plugins/project/vsxmake/vsproj/Xmake.props文件中加入以下内容可以增加相应C语言标准支持：
`<LanguageStandard_C Condition="'%(LanguageStandard_C)' == '' And $(XmakeLanguages.Contains('c11'))">stdc11</LanguageStandard_C>`
`<LanguageStandard_C Condition="'%(LanguageStandard_C)' == '' And $(XmakeLanguages.Contains('c17'))">stdc17</LanguageStandard_C>`
目前vs支持stdc11和stdc17两种配置

**Comment by waruqi** [comment]
xmake update -s dev
