### ISSUE TITLE
detect and generate architecture information in package.tools.msbuild package

### ISSUE THREAD

**Issue by jingkaimori** [xmake-io/xmake#3708]
### Is your feature request related to a problem? Please describe.

`package.tools.msbuild` simply apply command arguments and execute build comment. But this package does not check architecture of package, so caller must detect architecture of package manually, like this:
```lua
        table.insert(configs, "/p:Platform=" .. (package:is_arch("x64") and "x64" or "Win32"))
```
It is inconvenient to detect arm64, x86 or x64 with this style of detection, thus many ci in xmake-repo fails on winarm because of incorrect platform setting.

### Describe the solution you'd like

Remove manual detection of architecture and mode.
```diff
         local configs = {path.join("source", "allinone", "allinone.sln"), "/p:SkipUWP=True", "/p:_IsNativeEnvironment=true"}
-        table.insert(configs, "/p:Configuration=" .. (package:debug() and "Debug" or "Release"))
-        table.insert(configs, "/p:Platform=" .. (package:is_arch("x64") and "x64" or "Win32"))
         import("package.tools.msbuild").build(package, configs)
```
and insert such codes in package.tools.msbuild:
```lua
        if(package:is_arch("x86")) then
            table.insert(configs, "/p:Platform=Win32")
        elseif(package:is_arch("x64")) then
            table.insert(configs, "/p:Platform=x64")
        elseif(package:is_arch("arm64")) then
            table.insert(configs, "/p:Platform=arm64")
        end
```

**Comment by waruqi** [comment]
you can open a pr.
