### ISSUE TITLE
  CUDA target doesn't respect `add_defines`

### ISSUE THREAD

**Issue by OpportunityLiu** [xmake-io/xmake#371]
in the example https://github.com/tboox/xmake/tree/master/tests/projects/cuda/console, I added `add_defines("DEBUG")` at line 2 of `xmake.lua`.
The compile command is 
```
/usr/bin/ccache /usr/local/cuda/bin/nvcc -c -Iinc -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_70,code=compute_70 -m64 -Xcompiler -m64 -I/usr/local/cuda/include -o build/.objs/cuda_console/linux/x86_64/release/src/main.cu.o src/main.cu
```
no `-DDEBUG` flags

**Comment by waruqi** [comment]
I have fixed it, you can update xmake and try it again from dev branch. `$ xmake update dev`

**Comment by OpportunityLiu** [comment]
I've updated to dev  branch, there's still no `-D` flags?

BTW, `set_languages` should also be suppored.

**Comment by waruqi** [comment]
You can try it again after updating.
