### ISSUE TITLE
set_runtimes is useless

### ISSUE THREAD

**Issue by freestriker** [xmake-io/xmake#3710]
### Xmake Version

2.7.8

### Operating System Version and Architecture

windows11 22h2

### Describe Bug

1. use "xmake create -l c++ -t console XmakeRuntimesTest" to create a project
2. use "xmake project -k vsxmake -vD" to create vs2022 solution
3. Property->C/C++->CodeGeneration->RuntimeLibrary is all MD
4. change xmake.lua, add "set_runtimes("MT")"
5. use "xmake project -k vsxmake -vD" to recreate vs2022 solution
6. Property->C/C++->CodeGeneration->RuntimeLibrary is all MD too, nothing changed.
7. delete vsxmake folder, use "xmake project -k vsxmake -vD" to recreate vs2022 solution
8. Property->C/C++->CodeGeneration->RuntimeLibrary is all MD too, nothing changed.

### Expected Behavior

the RuntimeLibrary should change

### Project Configuration

add_rules("mode.debug", "mode.release")

target("XmakeRuntimesTest")
    set_kind("binary")
    add_files("src/*.cpp")
    set_runtimes("MT")

### Additional Information and Error Logs

PS D:\Project\XmakeRuntimesTest> xmake project -k vsxmake -vD
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.35.32217.1
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checking for link.exe ... C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX64\x64\link.exe
checking for the linker (ld) ... link.exe
configure
{
    plat = windows
    ccache = true
    arch = x64
    kind = static
    vs = 2022
    buildir = build
    mode = release
    host = windows
    ndk_stdcxx = true
}
using project kind vs2022
checking for debug.x64 ...
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.35.32217.1
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checking for link.exe ... C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX64\x64\link.exe
checking for the linker (ld) ... link.exe
checking for release.x64 ...
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.35.32217.1
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checking for link.exe ... C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX64\x64\link.exe
checking for the linker (ld) ... link.exe
skipped file vsxmake2022\XmakeRuntimesTest.sln since the file has the same content
skipped file vsxmake2022\Xmake.Custom.props since the file already exists
skipped file vsxmake2022\Xmake.Custom.targets since the file already exists
skipped file vsxmake2022\XmakeRuntimesTest\XmakeRuntimesTest.vcxproj since the file has the same content
skipped file vsxmake2022\XmakeRuntimesTest\XmakeRuntimesTest.vcxproj.filters since the file has the same content
skipped file vsxmake2022\XmakeRuntimesTest\Xmake.Custom.props since the file already exists
skipped file vsxmake2022\XmakeRuntimesTest\Xmake.Custom.targets since the file already exists
skipped file vsxmake2022\XmakeRuntimesTest\Xmake.Custom.items since the file already exists
skipped file vsxmake2022\XmakeRuntimesTest\Xmake.Custom.items.filters since the file already exists
create ok!

**Comment by SirLynix** [comment]
vsxmake generator doesn't use msbuild to compile but xmake directly, and thus VS RuntimeLibrary is not used, if you check the compilation flags used you'll see `vs_runtime` is passed to `cl.exe`.

(Regular) VS generator doesn't have this issue.

However I think this could be fixed for now, until a better way of generating vsxmake projects arrive
