### ISSUE TITLE
Dead urls in install script + minor redirect problems

### ISSUE THREAD

**Issue by vic1707** [xmake-io/xmake#3714]
### Xmake Version

v2.7.8 but not important (I think)

### Operating System Version and Architecture

macOS 13.1 (22C65)

### Describe Bug

Hello,

I'm having fun making installation scripts and realised that some URLs seem to be dead in the install script of xmake
I'm running:
```bash
echo "Installing xmake..."
curl -fsSL https://xmake.io/shget.text | bash 1>/dev/null
echo "Installed xmake"
```
And it gives the following output
```
Installing xmake...

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

debconf: delaying package configuration, since apt-utils is not installed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1812k  100 1812k    0     0  6956k      0 --:--:-- --:--:-- --:--:-- 6943k
Creating directory /tmp/.xmake_getter3844
  100%   SHA256 checksums are OK.  100%   MD5 checksums are OK.  100%  core/src/lua-cjson/lua-cjson/dtoa.c: In function 'dtoa':
core/src/lua-cjson/lua-cjson/dtoa.c:3974:56: warning: 'j1' may be used uninitialized in this function [-Wmaybe-uninitialized]
 3974 |                                 dval(&eps1) *= tens[j1 & 0xf];
      |                                                     ~~~^~~~~
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    47    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 404
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    47    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404
Installed xmake
```

### Expected Behavior

The two `curl` calls shouldn't fail or should probably be removed from the install script (or at least could they be called quietly?).
From what I could find it looks like those calls are the culprits as I can't find those files at these locations on the repo.
```
# get.sh l260
        remote_get_content "$gitrepo_raw/scripts/register-completions.sh" >> ~/.xmake/profile
# get.sh l266
        remote_get_content "$gitrepo_raw/scripts/register-virtualenvs.sh" >> ~/.xmake/profile

```
Running the install script while redirecting `stdout` to `/dev/null` should only leave errors and/or warnings in the console.
So the 
 - `apt` warning
 - `debconf` warning
 - failed `curl` (which should be fixed)
 - warning from `dtoa.c`
are to be expected, I don't think the rest should be present.

**Comment by waruqi** [comment]
I removed old profile scripts, you can try it again.

https://github.com/xmake-io/xmake/commit/45829dab6f83494b1101fd5da3771cdca2400aad

**Comment by vic1707** [comment]
yup, looks better 
```

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

debconf: delaying package configuration, since apt-utils is not installed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1812k  100 1812k    0     0  5636k      0 --:--:-- --:--:-- --:--:-- 5627k
Creating directory /tmp/.xmake_getter3753
  100%   SHA256 checksums are OK.  100%   MD5 checksums are OK.  100%  core/src/lua-cjson/lua-cjson/dtoa.c: In function 'dtoa':
core/src/lua-cjson/lua-cjson/dtoa.c:3974:56: warning: 'j1' may be used uninitialized in this function [-Wmaybe-uninitialized]
 3974 |                                 dval(&eps1) *= tens[j1 & 0xf];
      |                                                     ~~~^~~~~

**Comment by vic1707** [comment]
I think other lines should be `stdout`  
- the curl call download infos
- the `Creating directory ...`
- `100%   SHA256 checksums are OK.  100%   MD5 checksums are OK.  100%`
- What do you think ?

**Comment by waruqi** [comment]
maybe runfile? xxx.run

**Comment by vic1707** [comment]
Yep that's where it is

**Comment by vic1707** [comment]
the script called line 207

**Comment by vic1707** [comment]
looks like it line 630 in the `.run` file: `echo "Creating directory $targetdir" >&2`

**Comment by vic1707** [comment]
since that script seems to be generated I think the best solution would be to take advantage of its built-in `--quiet` option but it would require adding one the the xmake install script

**Comment by waruqi** [comment]
> the curl call can be silenced from the remote_get_content() function

I can't remove it, the progress info is always needed.

Also, for the install script, it doesn't matter if there is some redundant output on stderr, except that the dead urls problem needs to be fixed.

I will not remove the download progress because of this output problem.

> the Creating directory and checksum messages are from a generated script, can probably only be safely silenced by using its --quiet option

I added it.

**Comment by vic1707** [comment]
> I can't remove it, the progress info is always needed.

Okay 👌 I probably misunderstood something. 
I always thought that `curl`/`wget` would output to `stderr` if anything bad happens  so, to me, that progress info was useless 🤷.

> Also, for the install script, it doesn't matter if there is some redundant output on stderr

Depending on what you mean by "redundant output" I don't really agree with that one as `stderr` should be reserved to errors/warnings.

Anyways thank you for the fixes and explanations ^^ !
