### ISSUE TITLE
add_files能不能添加远程的源码文件?实现按需编译,而不需要整体编译大型库?

### ISSUE THREAD

**Issue by masx200** [xmake-io/xmake#3717]
### 你在什么场景下需要该功能？

就像go/deno那样直接添加远程的源码文件,就可以按需编译了,而不需要编译整个大型项目

### 描述可能的解决方案

```lua
add_files("https://gitee.com/masx200/leetcode-treenode-cpp/raw/1.1.6/TreeNode.ixx")

add_files("https://raw.githubusercontent.com/google/googletest/main/googletest/src/gtest-all.cc")

```

### 描述你认为的候选方案
这就相当于把源码直接下载下来到本地,添加本地文件编译一样

### 其他信息

之前的添加远程包的方式就像用nodejs或者vcpkg的包一样,下载下来一大堆文件,结果只需要使用里面一个函数而已,比如说npm上的lodash,又比如说vcpkg上的boost

**Comment by masx200** [comment]
又或者说对于modules可以使用类似于import_map.json的描述文件来描述模块名和文件的关系
```json
{
    "imports": {
        "leetcode_treenode_cpp.TreeNode": "https://gitee.com/masx200/leetcode-treenode-cpp/raw/1.1.6/TreeNode.ixx"
       
    },
    "scopes": {}
}
```

**Comment by masx200** [comment]
拿gtest举个例子
```
{
    "imports": {
        "gtest/": "https://github.com/google/googletest/raw/main/googletest/include/gtest/",
       "src/":"https://raw.githubusercontent.com/google/googletest/main/googletest/src/"
    },
    "scopes": {}
}
```

**Comment by waruqi** [comment]
c++ 跟其他语言不一样，目前只考虑走库集成

**Comment by xq114** [comment]
为什么不直接用git submodule呢

**Comment by masx200** [comment]
[添加 clib 的依赖包](https://xmake.io/#/zh-cn/package/remote_package?id=%e6%b7%bb%e5%8a%a0-clib-%e7%9a%84%e4%be%9d%e8%b5%96%e5%8c%85)
clib是一款基于源码的依赖包管理器，拉取的依赖包是直接下载对应的库源码，集成到项目中编译，而不是二进制库依赖。

其在xmake中集成也很方便，唯一需要注意的是，还需要自己添加上对应库的源码到xmake.lua，例如：
