### ISSUE TITLE
openssl的动态库可以被用，静态库无法使用

### ISSUE THREAD

**Issue by Ultraman95** [xmake-io/xmake#372]
add_links("libssl32MDd")
add_links("libcrypto32MDd")
如果这两个是动态库，编译通过，如果换成静态库，编译无法通过。这个是为什么，难道引用三方静态库不能使用add_links方法吗？

**Comment by waruqi** [comment]
都支持 这是最基础特性，add_links("crypto32MDd")

**Comment by Ultraman95** [comment]
还是链接出错
xmake.lua

set_project("FasexSuperApi")

-- add modes: debug and release 
add_rules("mode.debug", "mode.release")

add_defines("WINDOWS")
add_defines("MSVC")
add_defines("ISLIB")
add_defines("DEBUG_NOT_LOG")
add_defines("FASEX_SUPERAPI_IS_LIB")
add_defines("LIB_FASEX_SUPER_API_EXPORT")
add_defines("SAFE_API_FTD")
add_defines("WIN32")
add_defines("SUPERAPI")


-- add target
target("FasexSuperApi")

    -- set kind
    set_kind("shared")
	
    -- add .h files
    add_includedirs("../../source/platform/")
    add_includedirs("../../source/base/")
    add_includedirs("../../source/utility/")
	add_includedirs("../../source/probelogger/")
	add_includedirs("../../source/datastruct/")
	add_includedirs("../../source/event/")
	add_includedirs("../../source/version/")
	add_includedirs("../../../baserun/include/openssl/")
    add_includedirs("../../source/network/")
    add_includedirs("../../source/tcpnetwork/")
	add_includedirs("../../source/sslnetwork/")
    add_includedirs("../../source/udpnetwork/")
	add_includedirs("../../source/multinetwork/")
    add_includedirs("../../source/protocol/")
    add_includedirs("../../source/channelprotocol/")
	add_includedirs("../../source/ftdprotocol/")
	add_includedirs("../../source/compressprotocol/")
    add_includedirs("../../source/nsprotocol/")
    add_includedirs("../../source/xmpprotocol/")
	add_includedirs("../../source/multiprotocol/")
	add_includedirs("../../source/ftdfield/")
    add_includedirs("../../source/customDataType/")
	add_includedirs("../../source/crypt/")
	add_includedirs("../../source/UFCopy/")
	add_includedirs("../src/superapi/")

	-- add .h files
    add_headers("../../source/platform/*.h")
    add_headers("../../source/base/*.h")
    add_headers("../../source/utility/*.h")
	add_headers("../../source/probelogger/*.h")
	add_headers("../../source/datastruct/*.h")
	add_headers("../../source/version/*.h")
    add_headers("../../../baserun/include/openssl/*.h")
	add_headers("../../source/event/*.h")
    add_headers("../../source/network/*.h")
    add_headers("../../source/tcpnetwork/*.h")
	add_headers("../../source/sslnetwork/*.h")
    add_headers("../../source/udpnetwork/*.h")
	add_headers("../../source/multinetwork/*.h")
    add_headers("../../source/protocol/*.h")
    add_headers("../../source/channelprotocol/*.h")
	add_headers("../../source/ftdprotocol/*.h")
	add_headers("../../source/compressprotocol/*.h")
    add_headers("../../source/nsprotocol/*.h")
    add_headers("../../source/xmpprotocol/*.h")
	add_headers("../../source/multiprotocol/*.h")
	add_headers("../../source/ftdfield/*.h")
    add_headers("../../source/customDataType/*.h")
	add_headers("../../source/crypt/*.h")
	add_headers("../../source/UFCopy/*.h")
	add_headers("../src/superapi/*.h")


    -- add .cpp files
    add_files("../../source/platform/*.cpp")
    add_files("../../source/base/*.cpp")
    add_files("../../source/utility/*.cpp")
	add_files("../../source/probelogger/*.cpp")
	add_files("../../source/datastruct/*.cpp")
    add_files("../../source/version/*.cpp")
	add_files("../../source/event/*.cpp")
    add_files("../../source/network/*.cpp")
    add_files("../../source/tcpnetwork/*.cpp")
	add_files("../../source/sslnetwork/*.cpp")
    add_files("../../source/udpnetwork/*.cpp")
	add_files("../../source/multinetwork/*.cpp")
    add_files("../../source/protocol/*.cpp")
    add_files("../../source/channelprotocol/*.cpp")
	add_files("../../source/ftdprotocol/*.cpp")
	add_files("../../source/compressprotocol/*.cpp")
    add_files("../../source/nsprotocol/*.cpp")
    add_files("../../source/xmpprotocol/*.cpp")
	add_files("../../source/multiprotocol/*.cpp")
	add_files("../../source/ftdfield/*.cpp")
	add_files("../../source/crypt/*.cpp")
	add_files("../src/superapi/*.cpp")

	add_linkdirs("../../../baserun/lib/")
	
	add_links("wsock32")
	add_links("ssl")
	add_links("crypto")
	add_links("ws2_32")
	add_links("Crypt32")
	


    


**这个还是会出错，出错信息：**

crypto.lib(cryptlib.obj) : error LNK2019: 无法解析的外部符号 __imp__DeregisterEventSource@4，该符号在函数 _OPENSSL
_showfatal 中被引用
crypto.lib(cryptlib.obj) : error LNK2019: 无法解析的外部符号 __imp__RegisterEventSourceW@8，该符号在函数 _OPENSSL_
showfatal 中被引用
crypto.lib(cryptlib.obj) : error LNK2019: 无法解析的外部符号 __imp__ReportEventW@36，该符号在函数 _OPENSSL_showfat
al 中被引用
crypto.lib(cryptlib.obj) : error LNK2019: 无法解析的外部符号 __imp__GetProcessWindowStation@0，该符号在函数 _OPENS
SL_isservice 中被引用
crypto.lib(cryptlib.obj) : error LNK2019: 无法解析的外部符号 __imp__GetUserObjectInformationW@20，该符号在函数 _OP
ENSSL_isservice 中被引用
crypto.lib(cryptlib.obj) : error LNK2019: 无法解析的外部符号 __imp__MessageBoxW@16，该符号在函数 _OPENSSL_showfata
l 中被引用
crypto.lib(e_capi.obj) : error LNK2019: 无法解析的外部符号 __imp__CryptAcquireContextW@20，该符号在函数 _capi_ctx_
set_provname 中被引用
	
    
**首先已经排除静态库不对的情况，用公司自己的工具生成的makefile是可以正常编译的，xmake不行**

**Comment by Ultraman95** [comment]
是不是使用静态库，不能用add_links，还是有其他注意点

**Comment by Ultraman95** [comment]
支持的源文件类型 | 描述
-- | --
.c/.cpp/.cc/.cxx | c++文件
.s/.S/.asm | 汇编文件
.m/.mm | objc文件
.swift | swift文件
.go | golang文件
.o/.obj | 对象文件
.a/.lib | 静态库文件，会自动合并库到目标程序
.rc | msvc的资源文件

这个是add_files的接口描述，**静态库文件，会自动合并库到目标程序**，这个我也试过了，不行

**Comment by waruqi** [comment]
请仔细看下 add_links文档说明，文档里面已经说得很清楚了，这个就是用来添加链接库的（包括动态库，静态库），https://xmake.io/#/zh/manual?id=targetadd_links

add_files仅用于添加源文件，以及.a/.lib库的合并。。

> 这个还是会出错，出错信息：
> 
> crypto.lib(cryptlib.obj) : error LNK2019: 无法解析的外部符号 __imp__DeregisterEventSource@4，该符号在函数 _OPENSSL
> _showfatal 中被引用

缺什么符号，就加什么库，你提供的错误信息中缺失的符号所在的库，我没看到你哪里通过add_links添加进来了。。

__imp__DeregisterEventSource -> Advapi32
GetProcessWindowStation -> User32
CryptAcquireContextA -> Advapi32

Advapi32, User32 这些你有通过add_links添加进来了么？

xmake默认不会帮你追加任何库的，用户需要哪些库，依赖了哪些系统库，得自己根据需要自己加进来。。


至于错误信息中缺失的符号，请百度找下对应的库名。。

**Comment by bstaint** [comment]
我也遇到同样问题，测试https://github.com/TsudaKageyu/minhook
xmake.lua:
```
-- add rules: debug/release
add_rules("mode.debug", "mode.release")

-- define target
target("libMinHook")
    -- set kind
    set_kind("static")
    
    add_defines("WIN32","NDEBUG","_LIB","STRICT")
    
    add_includedirs("include/")

    -- add files
    add_files("src/buffer.c")
    
    if is_arch("x86") then
        add_files("src/HDE/hde32.c")
    elseif is_arch("x86_64") then
        add_files("src/HDE/hde64.c")
    end

    add_files("src/hook.c")
    add_files("src/trampoline.c")
    
    
target("MinHook")
    
    set_kind("shared")
    
    add_deps("libMinHook")
    add_links("libMinHook")
    
    add_defines("_WINDOWS", "_USRDLL", "MINHOOK_EXPORTS")
    
    -- add_files("dll_resources/MinHook.rc")
    add_shflags("/DEF:dll_resources/MinHook.def", {force = true})
```

注释这行`-- add_files("dll_resources/MinHook.rc")`之后用xmake -v输出就会有：
 > "link.exe -dll" -libpath:build_obj\\\\windows\\\\x86\\\\debug -debug -pdb:build_obj\\windows\\x86\\debug\\MinHook.pdb libMinHook.lib /DEF:dll_resources/MinHook.def -nologo -machine:x86 -out:build_obj\\windows\\x86\\debug\\MinHook.dll

取消注释：
 > "link.exe -dll" /DEF:dll_resources/MinHook.def -nologo -machine:x86 -out:build_obj\\windows\\x86\\debug\\MinHook.dll build_obj\\.objs\\MinHook\\windows\\x86\\debug\\dll_resources\\MinHook.rc.obj
error: MinHook.def : error LNK2001: 无法解析的外部符号 MH_ApplyQueued
MinHook.def : error LNK2001: 无法解析的外部符号 MH_CreateHook
MinHook.def : error LNK2001: 无法解析的外部符号 MH_CreateHookApi
MinHook.def : error LNK2001: 无法解析的外部符号 MH_CreateHookApiEx
MinHook.def : error LNK2001: 无法解析的外部符号 MH_DisableHook
MinHook.def : error LNK2001: 无法解析的外部符号 MH_EnableHook
MinHook.def : error LNK2001: 无法解析的外部符号 MH_Initialize
MinHook.def : error LNK2001: 无法解析的外部符号 MH_QueueDisableHook
MinHook.def : error LNK2001: 无法解析的外部符号 MH_QueueEnableHook
MinHook.def : error LNK2001: 无法解析的外部符号 MH_RemoveHook
MinHook.def : error LNK2001: 无法解析的外部符号 MH_StatusToString
MinHook.def : error LNK2001: 无法解析的外部符号 MH_Uninitialize
build_obj\windows\x86\debug\MinHook.lib : fatal error LNK1120: 12 个无法解析的外部命令

**Comment by waruqi** [comment]
@bstaint 有问题 请新开issues。。#411

**Comment by 525293680** [comment]
Windows：
#pragma comment(lib, "user32.lib")
#pragma comment(lib, "gdi32.lib")
#pragma comment(lib, "advapi32.lib")

**Comment by 525293680** [comment]
Windows：
#pragma comment(lib, "user32.lib")
#pragma comment(lib, "gdi32.lib")
#pragma comment(lib, "advapi32.lib")
