### ISSUE TITLE
当没有project.rootfile()时，XMAKE_RCFILES 环境变量不会生效

### ISSUE THREAD

**Issue by xqyjlj** [xmake-io/xmake#3728]
### Xmake 版本

xmake v2.7.8+dev.4fe1c80f5

### 操作系统版本和架构

Linux 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

我手写了几个额外的tasks放置在XMAKE_RCFILES 中，用于创建自定义的xmake工程模版，这个场景类似于xmake create，但是当前路径却没有xmake.lua (因为这些tasks就是为了创建这个xmake.lua)

现在已经知道问题在哪了，
位于路径的`core/project/project.lua`的函数：
```lua
function project._load_tasks()

    -- the project file is not found?
    if not os.isfile(project.rootfile()) then
        return {}, nil
    end
.....
```

### 期待的结果

当没有project.rootfile()时，也能加载XMAKE_RCFILES 指定的tasks

**Comment by waruqi** [comment]
支持不了。。XMAKE_RCFILES 就是为了给 工程用的，得先有工程，也就是得先存在 xmake.lua ，才能继续所有后续事情，包括对 XMAKE_RCFILES 的设置使用。。

**Comment by waruqi** [comment]
如果你要搞自定义的 task ，就是自定义插件，得走插件扩展模式，而不是用 XMAKE_RCFILES 。。走插件安装 xmake plugin --help 自己看下参数。。装到全局插件目录。。

**Comment by xqyjlj** [comment]
有空我帮xmake补补文档吧，感觉和已经脱节了，这东西文档没有的

**Comment by waruqi** [comment]
这块确实还没时间去更新，欢迎 pr
