### ISSUE TITLE
something error with link a shared target

### ISSUE THREAD

**Issue by yillis** [xmake-io/xmake#3729]
### Xmake 版本

xmake v2.7.8+HEAD.87dff1ef4

### 操作系统版本和架构

windows11 22621.1555

### 描述问题

有这样两个target
```lua
-- in core/xmake.lua
target("core")
    set_kind("shared")
    add_files("**.cpp")
    add_headerfiles("**.hpp")
    add_packages("spdlog")
```

```lua
-- in src/xmake.lua
target("test_log")
    set_kind("binary")
    add_files("**.cpp")
    add_deps("core")
    add_includedirs("$(projectdir)")
```
运行`xmake build test_log`报错

```
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2022
[ 25%]: compiling.release src\main.cpp
[ 25%]: compiling.release core\log\log.cpp
[ 50%]: linking.release core.dll
[ 75%]: linking.release test_log.exe
error: LINK : fatal error LNK1181: 无法打开输入文件“core.lib”
```

这时，当我将target core的kind改为 static，接着再次运行`xmake build test_log`，能成功
紧接着我又改回shared，再次运行`xmake build test_log`，就能成功链接dll了

不知道是我用错了还是怎么回事。
复现仓库：https://github.com/yillis/xmake_issue

### 期待的结果

能正常link core的dll

**Comment by waruqi** [comment]
你的 动态库，没有导出符号，所以不会生成 dll 对应的 lib 导入库，可以到 msvc 或者 google 上自己查下，怎么导出动态库符号。 可以代码里面导出，也可以 .def 导出

至于你后来可以，只不过是后来生成了静态库 lib 到相同目录下，后来改回 动态库后，对应 .lib 你没删，所以之后就一直 link 这个静态库了。。不管 dll是否存在导入库，都被你之前生成的静态库干扰的 link search

**Comment by yillis** [comment]
> 你的 动态库，没有导出符号，所以不会生成 dll 对应的 lib 导入库，可以到 msdn 或者 google 上自己查下，怎么导出动态库符号。 可以代码里面导出，也可以 .def 导出
> 
> 至于你后来可以，只不过是后来生成了静态库 lib 到相同目录下，后来改回 动态库后，对应 .lib 你没删，所以之后就一直 link 这个静态库了。。不管 dll是否存在导入库，都被你之前生成的静态库干扰的 link search
> 
> 这个跟 xmake 没啥关系，建议先科普下 win 动态库链接相关的一些东西

噢噢谢谢，疏忽这个了，刚刚主要是试出来觉得有点奇怪！
