### ISSUE TITLE
vulkansdk can not find in ubuntu

### ISSUE THREAD

**Issue by rain-io** [xmake-io/xmake#3734]
### Xmake Version

xmake v2.7.8+20230406

### Operating System Version and Architecture

ubuntu 22.04

### Describe Bug

After I installed vulkansdk to /usr, I add `add_requires("vulkansdk 1.3.243", {system = true})` in my xmake .lua.

When I execute `xmake`, it log:

```
checking for platform ... linux
checking for architecture ... x86_64
note: the following packages were not found on your system, try again after installing them:
  -> vulkansdk 1.3.243
```

### Expected Behavior

I want to know how to make sure to find vulkansdk in xmake.

**Comment by waruqi** [comment]
you can debug here. https://github.com/xmake-io/xmake/blob/643719b7e52a0a2bf458853d2b0381e416bdf433/xmake/modules/detect/sdks/find_vulkansdk.lua#L45

https://github.com/xmake-io/xmake-repo/blob/2f6b80ca04b15a0e4b9be35ed3be5740da50ad05/packages/v/vulkansdk/xmake.lua#L22

**Comment by xq114** [comment]
Currently vulkansdk do not support find by version; please use `add_requires("vulkansdk", {system = true})` and change environment variable `VK_SDK_PATH` to select right version

**Comment by xq114** [comment]
Currently vulkansdk do not support find by version; please use `add_requires("vulkansdk", {system = true})` and change environment variable `VK_SDK_PATH` to select right version

**Comment by rain-io** [comment]
This has nothing to do with xmake, I had some problems when installing vulkansdk, now it is solved. Sorry to bother you.
