### ISSUE TITLE
Build fails with custom compiler

### ISSUE THREAD

**Issue by mtribiere** [xmake-io/xmake#3736]
Here is my `xmake.lua`:
``` lua
toolchain("myToolchain")

    set_kind("standalone")
    set_toolset("cc", "gcc@ccppc")
    set_toolset("cxx", "gcc@ccppc")

toolchain_end()


target("TEST")
    set_kind("static")
    add_files("src/command.c")
    
```

Here is the error I'm getting:
```
C:\Tools\DEV\TEST_PARTITION>..\xmake\xmake.exe -v
checking for ccppc ... ok
checking for the c compiler (cc) ... ccppc
[ 25%]: cache compiling.release src\command.c
ccppc -c -fexceptions -o build\.objs\TEST\windows\x64\release\src\command.c.obj src\command.c
checking for ccppc ... ok
checking for flags (-MMD -MF) ... no
checking for flags (-fdiagnostics-color=always) ... no
checking for flags (-fcolor-diagnostics) ... no
error: ccppc tried to spawn C:\Tools\AH-Applications\WindRiver\gnu\3.3.2-vxworks653\x86-win32\bin\..\lib\gcc-lib\powerpc-wrs-vxworksae\3.3.2\get_feature.exe but failed: Invalid descriptor

C:\Tools\DEV\TEST_PARTITION>
```

_Originally posted by @mtribiere in https://github.com/xmake-io/xmake/discussions/3727#discussioncomment-5858635_

**Comment by waruqi** [comment]
please add `-vD` and provide verbose logs.

**Comment by mtribiere** [comment]
@waruqi partially solved it by using a custom rule. How could I add the compilation and linking flags?
```
rule("cFiles")
    set_extensions(".c", ".cc")
    on_build_file(function (target, sourcefile, opt)
        import("core.project.depend")
        import("core.tool.compiler")
        import("utils.progress") -- it only for v2.5.9, we need use print to show progress below v2.5.8
        
        -- Get all informations about the build
        local toolname,_ = target:tool("cc")

        -- make sure build directory exists
        os.mkdir(target:targetdir())

        -- replace .c with .o
        local targetfile = path.join(target:targetdir(), path.basename(sourcefile) .. ".o")

        -- only rebuild the file if its changed since last run
        depend.on_changed(function ()

            os.vrunv(toolname, {"-c", "-o", targetfile, sourcefile})
            progress.show(opt.progress, "${color.build.object}markdown %s", sourcefile)
        end, {files = sourcefile})
    end)


target("TEST")
    add_rules("cFiles")
    set_kind("static")

    add_files("src/command.c")
```

**Comment by mtribiere** [comment]
It's not quite the same issue I believe, one has to do with `-v`  inconsistent behavior (that should just add more output) and the other one is a command line spawning problem

**Comment by waruqi** [comment]
> @waruqi partially solved it by using a custom rule. How could I add the compilation and linking flags?
> 
> ```
> rule("cFiles")
>     set_extensions(".c", ".cc")
>     on_build_file(function (target, sourcefile, opt)
>         import("core.project.depend")
>         import("core.tool.compiler")
>         import("utils.progress") -- it only for v2.5.9, we need use print to show progress below v2.5.8
>         
>         -- Get all informations about the build
>         local toolname,_ = target:tool("cc")
> 
>         -- make sure build directory exists
>         os.mkdir(target:targetdir())
> 
>         -- replace .c with .o
>         local targetfile = path.join(target:targetdir(), path.basename(sourcefile) .. ".o")
> 
>         -- only rebuild the file if its changed since last run
>         depend.on_changed(function ()
> 
>             os.vrunv(toolname, {"-c", "-o", targetfile, sourcefile})
>             progress.show(opt.progress, "${color.build.object}markdown %s", sourcefile)
>         end, {files = sourcefile})
>     end)
> 
> 
> target("TEST")
>     add_rules("cFiles")
>     set_kind("static")
> 
>     add_files("src/command.c")
> ```

You should not do it. It doesn't solve this problem.

> C:\Tools\AH-Applications\WindRiver\gnu\3.3.2-vxworks653\x86-win32\bin\..\lib\gcc-lib\powerpc-wrs-vxworksae\3.3.2\get_feature.exe but failed: Invalid descriptor

This should be the same issue.

**Comment by waruqi** [comment]
> It's not quite the same issue I believe, one has to do with inconsistent behavior (that should just add more output) and the other one is a command line spawning problem`-v`

This also has to do with flags and possibly the configuration of the CreateProcess parameter inside os.execv. But I think it's just a same problem that causes it. Even if you use custom rules, at some point this may still trigger this problem.

**Comment by waruqi** [comment]
It could also be due to some internal bug in the compiler when it opens multiple subprocesses for compilation at the same time.

**Comment by waruqi** [comment]
You can try manually running `ccppc -c -fexceptions -o build\.objs\TEST\windows\x64\release\src\command.c.obj src\command.c` or make a bat script to start some processes to compile at the same time to check if parallel compilation is causing it.

**Comment by mtribiere** [comment]
It does work by running manually:
```
ccppc -c -fexceptions -o build\.objs\TEST\windows\x64\release\src\command.c.obj src\command.c
```

**Comment by mtribiere** [comment]
It does work when executed in parallel and have also worked with other build tools in the past. I believe it is the way XMake spawn parallels processes but I can't be sure

**Comment by waruqi** [comment]
Can you provide your compiler or download link? I will test it.
