### ISSUE TITLE
我在编译uwebsockets库的时候，出现unknown source file: libwshandshake.hpp，是不是不支持hpp

### ISSUE THREAD

**Issue by Ultraman95** [xmake-io/xmake#375]

**Comment by Ultraman95** [comment]
要是你的远程库支持最新版的uwebsockets就好了，这个库太难编译了

**Comment by waruqi** [comment]
你可以提个feature request到xmake-repo/issues，之后有时间我会考虑加上。。

**Comment by waruqi** [comment]
提issues，请将问题详细在issues内容里面描述，不要放在title上面，内容反而是空的，这种issues我以后就不回复了

> 出现unknown source file: libwshandshake.hpp，是不是不支持hpp

想详细看下add_files官方文档，这个是用来加源码编译的, hpp是头文件，不会生成.o对象文件，没必要放置在add_files里面，代码里面include下就行，这个你可以看下 c++相关教程。。

**Comment by Ultraman95** [comment]
知道了
