### ISSUE TITLE
Error in generator 'XmakeGenerator': '_Component' object has no attribute 'copy'

### ISSUE THREAD

**Issue by BenjaminDbb** [xmake-io/xmake#3760]
### Xmake 版本

2.7.9

### 操作系统版本和架构

macOS Ventura

### 描述问题

无法使用 xmake 安装 conan 的 package

### 期待的结果

正常安装使用

### 工程配置

add_requires("conan::eigen/3.4.0", {alias = "eigen3"})

### 附加信息和错误日志

======== Finalizing install (deploy, generators) ========
conanfile.txt: Writing generators to /Users/admin/Desktop/main/build/.conan/eigen/3.4.0
conanfile.txt: Generator 'XmakeGenerator' calling 'generate()'
conanfile.txt: ERROR: Traceback (most recent call last):
  File "/usr/local/Cellar/conan/2.0.5/libexec/lib/python3.11/site-packages/conans/client/generators/__init__.py", line 92, in write_generators
    generator.generate()
  File "/Users/admin/.conan2/extensions/generators/xmake_generator.py", line 34, in generate
    dep_cppinfo = dep.cpp_info.copy()
                  ^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/conan/2.0.5/libexec/lib/python3.11/site-packages/conans/model/build_info.py", line 408, in __getattr__
    return getattr(self._package, attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_Component' object has no attribute 'copy'

ERROR: Error in generator 'XmakeGenerator': '_Component' object has no attribute 'copy'

**Comment by waruqi** [comment]
可以了，再试下 xmake update -s dev

conan 在 2.0.5 发版前，又改了东西，给 break 了。

**Comment by wuzhiguocarter** [comment]
conan2 似乎又有一些破坏性更新，导致XmakeGenerator不work了。

(base) ➜  carpool-project xmake --version
xmake v2.9.3+20240624, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, xmake.io

    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor

(base) ➜  carpool-project conan --version
WARN: Downgrading cache from Conan 2.14.0 to 2.4.1
Conan version 2.4.1

 (base) ➜  xrepo install -vy conan::thrift/0.13.0
/usr/local/bin/xmake f -c --require=n
checking for platform ... macosx
checking for architecture ... x86_64
checking for Xcode directory ... /Applications/Xcode.app
checking for Codesign Identity of Xcode ... no
checking for SDK version of Xcode for macosx (x86_64) ... 14.5
checking for Minimal target version of Xcode for macosx (x86_64) ... 14.2
/usr/local/bin/xmake require -y -v -j 10 --extra={system=false} conan::thrift/0.13.0
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/local/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
checking for conan::thrift/0.13.0 ... no
checking for conan ... /usr/local/Caskroom/miniconda/base/bin/conan
 /usr/local/Caskroom/miniconda/base/bin/conan config install /usr/local/Cellar/xmake/2.9.3/share/xmake/scripts/conan
Copying file xmake_generator.py to /Users/wuzhiguocarter/.conan2/extensions/generators
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang ... ok
checking for the c compiler (cc) ... clang
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang ... ok
^R
/usr/local/Caskroom/miniconda/base/bin/conan install . -g XmakeGenerator --profile:build=profile_build.txt --profile:host=profile_host.txt --build=missing

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=15
os=Macos

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=15
os=Macos

....

-------- Installing package bzip2/1.0.8 (2 of 12) --------
bzip2/1.0.8: Building from source
bzip2/1.0.8: Package bzip2/1.0.8:b9379226640322e9052b1b25fee2ef331fcfb99b
bzip2/1.0.8: Copying sources to build folder
bzip2/1.0.8: Building your package in /Users/wuzhiguocarter/.conan2/p/b/bzip2419e43496cc27/b
ERROR: Unable to load conanfile in /Users/wuzhiguocarter/.conan2/extensions/generators/xmake_generator.py
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/wuzhiguocarter/.conan2/extensions/generators/xmake_generator.py", line 9, in <module>
    from conans.model.build_info import CppInfo
ModuleNotFoundError: No module named 'conans.model.build_info'

error: execv(/usr/local/Caskroom/miniconda/base/bin/conan install . -g XmakeGenerator --profile:build=profile_build.txt --profile:host=profile_host.txt --build=missing) failed(1)
  => install conan::thrift/0.13.0 latest .. failed
error: install failed!
error: execv(/usr/local/bin/xmake require -y -v -j 10 --extra={system=false} conan::thrift/0.13.0) failed(255)

**Comment by waruqi** [comment]
> conan2 似乎又有一些破坏性更新，导致XmakeGenerator不work了。
> 
> (base) ➜ carpool-project xmake --version xmake v2.9.3+20240624, A cross-platform build utility based on Lua Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io _ __ ___ __ __ __ _| | ______ \ / / | / |/ _ | |/ / __ > < | __/ | /_| | < ___/ /_/__|_| |_|__ |_|_____| by ruki, xmake.io
> 
> ```
> 👉  Manual: https://xmake.io/#/getting_started
> 🙏  Donate: https://xmake.io/#/sponsor
> ```
> 
> (base) ➜ carpool-project conan --version WARN: Downgrading cache from Conan 2.14.0 to 2.4.1 Conan version 2.4.1
> 
> (base) ➜ xrepo install -vy conan::thrift/0.13.0 /usr/local/bin/xmake f -c --require=n checking for platform ... macosx checking for architecture ... x86_64 checking for Xcode directory ... /Applications/Xcode.app checking for Codesign Identity of Xcode ... no checking for SDK version of Xcode for macosx (x86_64) ... 14.5 checking for Minimal target version of Xcode for macosx (x86_64) ... 14.2 /usr/local/bin/xmake require -y -v -j 10 --extra={system=false} conan::thrift/0.13.0 checking for unzip ... /usr/bin/unzip checking for git ... /usr/local/bin/git checking for gzip ... /usr/bin/gzip checking for tar ... /usr/bin/tar checking for conan::thrift/0.13.0 ... no checking for conan ... /usr/local/Caskroom/miniconda/base/bin/conan /usr/local/Caskroom/miniconda/base/bin/conan config install /usr/local/Cellar/xmake/2.9.3/share/xmake/scripts/conan Copying file xmake_generator.py to /Users/wuzhiguocarter/.conan2/extensions/generators checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang ... ok checking for the c compiler (cc) ... clang checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang ... ok ^R /usr/local/Caskroom/miniconda/base/bin/conan install . -g XmakeGenerator --profile:build=profile_build.txt --profile:host=profile_host.txt --build=missing
> 
> ======== Input profiles ======== Profile host: [settings] arch=x86_64 build_type=Release compiler=clang compiler.cppstd=gnu17 compiler.libcxx=libc++ compiler.version=15 os=Macos
> 
> Profile build: [settings] arch=x86_64 build_type=Release compiler=clang compiler.cppstd=gnu17 compiler.libcxx=libc++ compiler.version=15 os=Macos
> 
> ....
> 
> -------- Installing package bzip2/1.0.8 (2 of 12) -------- bzip2/1.0.8: Building from source bzip2/1.0.8: Package bzip2/1.0.8:b9379226640322e9052b1b25fee2ef331fcfb99b bzip2/1.0.8: Copying sources to build folder bzip2/1.0.8: Building your package in /Users/wuzhiguocarter/.conan2/p/b/bzip2419e43496cc27/b ERROR: Unable to load conanfile in /Users/wuzhiguocarter/.conan2/extensions/generators/xmake_generator.py File "", line 999, in exec_module File "", line 488, in _call_with_frames_removed File "/Users/wuzhiguocarter/.conan2/extensions/generators/xmake_generator.py", line 9, in from conans.model.build_info import CppInfo ModuleNotFoundError: No module named 'conans.model.build_info'
> 
> error: execv(/usr/local/Caskroom/miniconda/base/bin/conan install . -g XmakeGenerator --profile:build=profile_build.txt --profile:host=profile_host.txt --build=missing) failed(1) => install conan::thrift/0.13.0 latest .. failed error: install failed! error: execv(/usr/local/bin/xmake require -y -v -j 10 --extra={system=false} conan::thrift/0.13.0) failed(255)

单独开个issue
