### ISSUE TITLE
add translation for English

### ISSUE THREAD

**Issue by infdahai** [xmake-io/xmake#3763]
### Is your feature request related to a problem? Please describe.

I see someone isn't familiar with Chinese and they also want to participate in this project.
And we can use English in github's communication or translate words to English.
 

### Describe the solution you'd like

We can provide an action to translate Chinese to English in issues by [`this action`](https://github.com/dromara/issues-translate-action).

The result looks like https://github.com/seata/seata-go/pull/560#issuecomment-1547466798.

**Comment by waruqi** [comment]
我已经添加它，现在测试下。

**Comment by waruqi** [comment]
我已经添加它。。
