### ISSUE TITLE
xmake在Ubuntu上无法找到VulkanSDK

### ISSUE THREAD

**Issue by HuajiKojima** [xmake-io/xmake#3767]
### Xmake 版本

2.7.9

### 操作系统版本和架构

Ubuntu 22.04.1

### 描述问题

在Ubuntu 22.04.1安装VulkanSDK并配置好环境变量之后，运行项目中的xmake.lua出现```The packages(vulkansdk) not found, please run "xmake repo -u" first!```，但输入```xmake l find_package vulkansdk```却是如下结果：
![屏幕截图 2023-05-22 191155](https://github.com/xmake-io/xmake/assets/44185970/37dac976-dd76-4d30-a729-95a4602f5bdc)
不过在windows平台上生成VS项目或者是直接生成exe均没有问题。
与#3268的问题相似，但是这里是纯C++项目，不包含qt的任何东西。同时，在xmake.lua里面加上system = true依旧不起作用。

### 期待的结果

在相似情况下可以设置vulkansdk的路径。

### 工程配置

```lua
set_project("ShadowPlay2")
set_arch("x64")
set_warnings("all")
add_rules("mode.debug", "mode.release")

add_requires("vulkansdk", "glfw", "glm")

target("ShadowPlay2")
    set_kind("shared")
    set_targetdir("ShadowPlay2")
    add_files("ShadowPlay2/Core/RHI/*.cpp")
    add_files("ShadowPlay2/Core/Memory/*.cpp")
    add_files("ShadowPlay2/*.cpp")
    add_headerfiles("ShadowPlay2/Core/RHI/*.h")
    add_headerfiles("ShadowPlay2/Core/Memory/*.h")
    add_headerfiles("ShadowPlay2/*.h")
    add_includedirs("ShadowPlay2")
    add_packages("vulkansdk", "glfw", "glm")

    set_pcxxheader("ShadowPlay2/ShadowPreCompileHeader.h")

    add_defines("SHADOWPLAY_CORE_EXPORT")
    add_defines("SHADOWPLAY_ACC_AVX")
    add_defines("SHADOWPLAY_API_VK")
    if is_plat("windows") then
        add_defines("SHADOWPLAY_PLAT_WIN")
    end
    if is_plat("linux") then
        add_defines("SHADOWPLAY_PLAT_LINUX")
    end
    if is_mode("debug") then
        add_defines("SHADOWPLAY_DEBUG")
    end

    set_symbols("debug")
    set_strip("all")

    set_basename("ShadowPlay2_$(mode)_$(arch)")
    set_targetdir("bin/$(arch)/$(mode)")
    set_objectdir("bin-int/$(arch)/$(mode)")
target_end()
```

**Comment by waruqi** [comment]
```
xrepo update-repo
xrepo fetch -vD vulkansdk
xmake f -cvD
```

执行下，看看能找到么

**Comment by HuajiKojima** [comment]
> ```
> xrepo update-repo
> xrepo fetch -vD vulkansdk
> xmake f -cvD
> ```
> 
> 执行下，看看能找到么

感谢解答，但是还是无法找到，以下是xmake返回的结果：
![屏幕截图 2023-05-22 224427](https://github.com/xmake-io/xmake/assets/44185970/4abbcd78-9244-42b1-8fd2-0d76f49e52bd)
![屏幕截图 2023-05-22 224650](https://github.com/xmake-io/xmake/assets/44185970/576a6bbc-dbc9-46a3-80ef-55fc290c97f7)
![屏幕截图 2023-05-22 224714](https://github.com/xmake-io/xmake/assets/44185970/7bc0c0a4-513d-4462-8a25-0c8923206303)

**Comment by waruqi** [comment]
你可以在 xmake-repo 里调下 https://github.com/xmake-io/xmake-repo/blob/6f6bcf4c91736b579d7b5ee16094cca13f4dfd82/packages/v/vulkansdk/xmake.lua#L22 这块代码，看看找的到么，进去了么。。

你可以把 xmake-repo clone 后，走 `xmake repo --add local /xxx/xmake-repo` 关联后调试。。

```console
git clone  ....xmake-repo
xmake repo --add local /xxx/xmake-repo
xmake f -cvD
```

**Comment by HuajiKojima** [comment]
> 你可以在 xmake-repo 里调下 https://github.com/xmake-io/xmake-repo/blob/6f6bcf4c91736b579d7b5ee16094cca13f4dfd82/packages/v/vulkansdk/xmake.lua#L22 这块代码，看看找的到么，进去了么。。
> 
> 你可以把 xmake-repo clone 后，走 `xmake repo --add local /xxx/xmake-repo` 关联后调试。。
> 
> ```
> git clone  ....xmake-repo
> xmake repo --add local /xxx/xmake-repo
> xmake f -cvD
> ```

尝试clone下来，使用您给的方案试了一下，目前的结果是这样：还是无法生成
![屏幕截图 2023-05-23 103143](https://github.com/xmake-io/xmake/assets/44185970/f2fabc0e-d0cb-41a0-b7cf-f415bb357854)
![屏幕截图 2023-05-23 103114](https://github.com/xmake-io/xmake/assets/44185970/d4313fd8-5352-4fc1-8d4b-69e699a74e50)

**Comment by waruqi** [comment]
我是说按我说的 自己调试下包

**Comment by waruqi** [comment]
我这里可以，没啥问题。。

```console
ruki@66d64831d5e9:/tmp/test$ xmake f -cvD
checking for platform ... linux
checking for architecture ... x86_64
checking for gcc ... /usr/bin/gcc
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
/usr/bin/git rev-parse HEAD
finding vulkansdk from xmake ..
checking for xmake::vulkansdk ... no
checking for xmake-repo::vulkansdk ... vulkansdk 
configure
{
    clean = true
    buildir = build
    ndk_stdcxx = true
    ccache = true
    arch = x86_64
    mode = release
    host = linux
    kind = static
    plat = linux
}
ruki@66d64831d5e9:/tmp/test$ xmake -rv
checking for gcc ... /usr/bin/gcc
checking for the c++ compiler (cxx) ... gcc
checking for /usr/bin/gcc ... ok
checking for flags (-fPIC) ... ok
checking for flags (-fvisibility-inlines-hidden) ... ok
checking for flags (-O3) ... ok
checking for flags (-DNDEBUG) ... ok
[ 25%]: cache compiling.release src/main.cpp
/usr/bin/gcc -c -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -isystem /mnt/1.3.243.0/x86_64/include -DNDEBUG -o build/.objs/test/linux/x86_64/release/src/main.cpp.o src/main.cpp
checking for flags (-MMD -MF) ... ok
checking for flags (-fdiagnostics-color=always) ... ok
checking for g++ ... /usr/bin/g++
checking for the linker (ld) ... g++
checking for /usr/bin/g++ ... ok
checking for flags (-fPIC) ... ok
[ 50%]: linking.release test
/usr/bin/g++ -o build/linux/x86_64/release/test build/.objs/test/linux/x86_64/release/src/main.cpp.o -m64 -L/mnt/1.3.243.0/x86_64/lib -s -lvulkan
[100%]: build ok, spent 4.324s
```

**Comment by HuajiKojima** [comment]
感谢解答，我尝试了一下使用cmake::Vulkan的方式试了一下可以找到，貌似是环境变量的问题，重新配置并应用过后已经可以正常使用了。
