### ISSUE TITLE
Ability to define custom platform

### ISSUE THREAD

**Issue by Arthapz** [xmake-io/xmake#3768]
### Is your feature request related to a problem? Please describe.

It would be handy to be able to define platform, it would simplify compilation to xmake unknown platform, in my case, the nintendo switch

### Describe the solution you'd like

```lua
toolchain("switch-llvm")
    add_cxflags(...)
    ...

platform("switch")
    set_os("nxos")

    set_hosts("macos", "linux", "windows")

    set_archs("arm64-v8a")

    set_formats("static", "$(name).a.nro")
    set_formats("object", "$(name).o")
    set_formats("shared", "$(name).nso")
    set_formats("symbol", "$(name).sym")

    set_toolchains("envs", "switch-llvm")
 ```
 
 ```
 xmake f -p switch
 ```
 
 the xmake command line get consistent with compiling to iOS / android / other platformes

**Comment by waruqi** [comment]
The platform interface is not yet designed to be stable and is not available to the public at this time. You can customise the platform in the following way.

```lua
if is_plat("myplat") then
    add_defines("xxx")
    set_toolchains("xxx")
end
```

```console
xmake f -p myplat
xmake
```

or you can add a custom rule to set them.

**Comment by Arthapz** [comment]
Oh thx, i didn't know this was working
