### ISSUE TITLE
need variable $(targetname)

### ISSUE THREAD

**Issue by superzmy** [xmake-io/xmake#377]
set_basename(targetName .. "_$(mode)_$(arch)")
There is not an $(targetname) variable.
Or anyone can tell me how to make a binary file which is named "targetname_debug_x64.out" ?

**Comment by waruqi** [comment]
This variable is not necessary.

```lua
target("test")
    set_kind("binary")
    set_basename("test_$(mode)$(arch).out")
    add_files("src/*.c")
```

**Comment by superzmy** [comment]
According to your opinion, it's not need for VS to give us variable $(ProjectName). Because we can write the ProjectName everywhere.

**Comment by waruqi** [comment]
xmake is not vs, at least not necessary for xmake. Or you can use lua variables

```lua
for _, name in ipairs({"test1", "test2", "test3"}) do
    target(name)
        set_kind("binary")
        set_filename(name .. "_$(mode)$(arch).out")
        add_files("src/*.c")
end
```

Or 

```lua
function add_target(name)
    target(name)
        set_kind("binary")
        set_filename(name .. "_$(mode)$(arch).out")
        add_files("src/*.c")
    target_end()
end
```
