### ISSUE TITLE
Dummy slow when system has no Visual Studio Version registered

### ISSUE THREAD

**Issue by ZiXuanVickyLu** [xmake-io/xmake#3770]
### Xmake Version

2.7.9

### Operating System Version and Architecture

Windows 11

### Describe Bug

xmake 源码的 xmake/modules/detect/sdks/find_vstudio.lua 中的line 262 的for循环中，前面的逻辑似乎是，如果系统没有注册VCInstallDir 或者VisualStudioVersion，那么枚举所有版本号在指定路径下搜索。

实际效果是（e.g. 系统只存在一个版号，例如VS2022的），对后面的版号的vswhere查询均会返回空字符串。
line295-321的文件系统遍历会消耗3min之久（并且实际上什么也搜不出来）。对14个版号的遍历会消耗40+min，但是实际上只有第一次对VS2022版号的搜索是有效的（并且实际上并没有执行line295-321的遍历）。
Dummy slowly.
![image](https://github.com/xmake-io/xmake/assets/53465084/d0d056cc-6c6f-41a5-bd90-c36beefc7b46)
这段有没有好办法规避呢…

### Expected Behavior

希望xmake f -c能在几分钟内跑出个结果？

**Comment by waruqi** [comment]
按理不应该这么慢，如果某个版本没装，不存在这个路径，根目录判断不存在，就不会继续遍历下去

你可以编辑下 paths，一点点删掉一些路径，看下那个路径影响最大。。

另外这个探测是有全局缓存的，不会每次 `xmake f -cvD` 都会去检测。。只有 vs 环境变动 才重新检测一次

**Comment by birepeople** [comment]
> 按理不应该这么慢，如果某个版本没装，不存在这个路径，根目录判断不存在，就不会继续遍历下去
> 
> 你可以编辑下 paths，一点点删掉一些路径，看下那个路径影响最大。。
> 
> 另外这个探测是有全局缓存的，不会每次 `xmake f -cvD` 都会去检测。。只有 vs 环境变动 才重新检测一次

想想，确实最近变动了vs，%path%东西也确实比较多……我再查一下，谢谢您

**Comment by waruqi** [comment]
我这边试了下，即使遍历磁盘也很快，瞬间就遍历完了。。你可以看下具体哪个目录遍历慢
