### ISSUE TITLE
wasm platform failed to install the third-party library fmt

### ISSUE THREAD

**Issue by Waitforomething2023** [xmake-io/xmake#3771]
### Xmake 版本

xmake v2.7.9+master.992cc3c22

### 操作系统版本和架构

windows 10 21H2

### 描述问题

先切换到wasm平台
xmake f -p wasm  
然后执行
xmake
提示
···
 *  正在执行任务: xmake -v 

checking for emsdk directory ... no
checking for emcc.bat ... ok
checking for unzip ... no
checking for 7z ... C:\Users\luciouskami\xmake\winenv\bin\7z
checking for git ... ok
checking for gzip ... no
git rev-parse HEAD      
checking for cmake ... no
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for cmake ... no
checking for cmake ... no
checking for cmake ... C:\Program Files\CMake\bin\cmake
checking for xmake::fmt ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> fmt 10.0.0 [vs_runtime:"MT", toolchains:"emcc"]
please input: y (y/n/m)
y
checking for ping ... ok
pinging for the host(github.com) ... 1 ms
C:\Users\luciouskami\xmake\winenv\bin\7z x -y fmt-10.0.0.zip -osource.tmp

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 1279571 bytes (1250 KiB)

Extracting archive: fmt-10.0.0.zip
--
Path = fmt-10.0.0.zip
Type = zip
Physical Size = 1279571

Everything is Ok

Folders: 29
Files: 232
Size:       4599553
Compressed: 1279571
checking for emsdk directory ... no
error: emscripten not found!
  => install fmt 10.0.0 .. failed
error: install failed!

···

我确认已经将emasdk的目录加入到环境变量中

### 期待的结果

正确安装fmt库

### 工程配置

set_runtimes("MT")
add_requires("fmt")

set_languages("cxx20")
target("test")
    set_kind("binary")
    add_files("src/*.cpp")

    set_optimize("fastest")

### 附加信息和错误日志

G:\MapProject\MapFrameWork\test>xmake -vD
checking for emsdk directory ... no
checking for emcc.bat ... ok
checkinfo: cannot runv(unzip.exe -v), No such file or directory
checking for unzip ... no
checking for 7z ... C:\Users\luciouskami\xmake\winenv\bin\7z
checking for git ... ok
checkinfo: cannot runv(gzip.exe --version), No such file or directory
checking for gzip ... no
git rev-parse HEAD
checking for cmake ... no
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for cmake ... no
checking for cmake ... no
checking for cmake ... C:\Program Files\CMake\bin\cmake
finding fmt from xmake ..
checking for xmake::fmt ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> fmt 10.0.0 [vs_runtime:"MT", toolchains:"emcc"]
please input: y (y/n/m)
y
checking for ping ... ok
pinging for the host(github.com) ... 1 ms
C:\Users\luciouskami\xmake\winenv\bin\7z x -y fmt-10.0.0.zip -osource.tmp

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 1279571 bytes (1250 KiB)

Extracting archive: fmt-10.0.0.zip
--
Path = fmt-10.0.0.zip
Type = zip
Physical Size = 1279571

Everything is Ok

Folders: 29
Files: 232
Size:       4599553
Compressed: 1279571
checking for emsdk directory ... no
error: @programdir\modules\package\tools\cmake.lua:481: emscripten not found!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:913]: in function 'raiselevel'
    [@programdir\core\sandbox\modules\utils.lua:149]: in function 'assert'
    [@programdir\modules\package\tools\cmake.lua:481]: in function '_get_configs_for_wasm'
    [@programdir\modules\package\tools\cmake.lua:691]: in function '_get_configs'
    [@programdir\modules\package\tools\cmake.lua:972]: in function 'install'
    [...\.xmake\repositories\xmake-repo\packages\f\fmt\xmake.lua:53]: in function 'script'
    [...dir\modules\private\action\require\impl\utils\filter.lua:125]: in function 'call'
    [...\modules\private\action\require\impl\actions\install.lua:364]:

  => install fmt 10.0.0 .. failed
error: @programdir\modules\private\async\runjobs.lua:256: ...\modules\private\action\require\impl\actions\install.lua:469: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:913]:
    [...\modules\private\action\require\impl\actions\install.lua:469]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:328]:
    [...modules\private\action\require\impl\install_packages.lua:479]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:232]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:913: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\modules\private\async\runjobs.lua:256: in field 'catch'
        @programdir\core\sandbox\modules\try.lua:123: in global 'try'
        @programdir\modules\private\async\runjobs.lua:218: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>

**Comment by waruqi** [comment]
执行 `xmake l detect.sdks.find_emsdk` 给我看下输出，注：在非工程目录下执行，避免工程缓存干扰。。

**Comment by Waitforomething2023** [comment]
C:\Users\luciouskami\Desktop>xmake l detect.sdks.find_emsdk
{ }

**Comment by Waitforomething2023** [comment]
> 你调下
> 
> https://github.com/xmake-io/xmake/blob/992cc3c22e49a7a7f8a47d6b10d34af0128c58af/xmake/modules/detect/sdks/find_emsdk.lua#L35
> 
> 这里，看下为什么没找到。。
> 检查下 EMSDK 环境变量。。

我好像明白了，我并没有添加EMSDK这个环境变量，我是直接把他们加到了path里，我先按照官方那个env.bat配置一下

**Comment by waruqi** [comment]
> > 你调下
> > https://github.com/xmake-io/xmake/blob/992cc3c22e49a7a7f8a47d6b10d34af0128c58af/xmake/modules/detect/sdks/find_emsdk.lua#L35
> > 
> > 这里，看下为什么没找到。。
> > 检查下 EMSDK 环境变量。。
> 
> 我好像明白了，我并没有添加EMSDK这个环境变量，我是直接把他们加到了path里，我先按照官方那个env.bat配置一下

你用法不对，emsdk 得走官方的方式加载环境，不是单纯自己加 PATH，还有很多其他变量了。。

**Comment by Waitforomething2023** [comment]
> xmake l detect.sdks.find_emsdk

按照官方的例子配好了以后emsdk找到了，不过他又报了找不到mingw
Microsoft Windows [版本 10.0.19044.2006]
(c) Microsoft Corporation。保留所有权利。

G:\MapProject\MapFrameWork\test>xmake
checking for Microsoft Visual Studio (x64) version ... 2022
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> fmt 10.0.0
please input: y (y/n/m)
y
  => install fmt 10.0.0 .. failed

mingw not found!
if you want to get more verbose errors, please see:
  -> C:\Users\luciouskami\AppData\Local\.xmake\cache\packages\2305\f\fmt\10.0.0\installdir.failed\logs\install.txt
error: install failed!

**Comment by waruqi** [comment]
xmake f -p wasm 切下平台

**Comment by Waitforomething2023** [comment]
G:\MapProject\MapFrameWork\test>xmake f -p wasm
checking for Microsoft Visual Studio (x64) version ... 2022
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> fmt 10.0.0        
please input: y (y/n/m)
y
  => install fmt 10.0.0 .. failed

mingw not found!
if you want to get more verbose errors, please see:
  -> C:\Users\luciouskami\AppData\Local\.xmake\cache\packages\2305\f\fmt\10.0.0\installdir.failed\logs\install.txt
error: install failed!


切平台的时候提示要安装fmt，然后又提示找不到mingw，如果选择不安装
G:\MapProject\MapFrameWork\test>xmake f -p wasm
checking for Microsoft Visual Studio (x64) version ... 2022
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> fmt 10.0.0        
please input: y (y/n/m)
n
error: packages(fmt): must be installed!

**Comment by Waitforomething2023** [comment]
> > xmake f -p wasm 切下平台
> 
> 然后我单独使用emcc编译了一下 emcmake cmake .. ninja
> 
> 能编译通过

临时的解决方案是直接添加fmt的头文件和源文件到项目里，能编译过，不过大项目的话就麻烦了

**Comment by waruqi** [comment]
这是因为 wasm 下用 cmake 编译的包，默认 cmake 内部都会去检测使用 make 走 makefile 编译，而 windows 默认没 make 的。。所以 xmake 需要检测 mingw 环境，设置它里面的 make 给 cmake 用的。。

没检测到 mingw ，就没法让 cmake 走 make 编译。。

这里可以改进下，尝试检测 ninja ，如果存在，走 ninja 去编译

**Comment by waruqi** [comment]
不过前提是用户也装了 ninja ，你这是正好系统上装了，否则即使改了包 还是会报错的。。

**Comment by waruqi** [comment]
我 dev 改进下了。会尝试用 ninja ，可以再试试。。xmake update -s dev

**Comment by Waitforomething2023** [comment]
> xmake update -s dev

搜索ninja确实是一个解，用emcake ninja应该就行了，话说现在做开发的基本上都会装ninja吧

**Comment by waruqi** [comment]
> > xmake update -s dev
> 
> 搜索ninja确实是一个解，用emcmake ninja应该就行了，话说现在做开发的基本上都会装ninja吧

不会，我就从来不用 ninja 。。

如果现在没问题了，我就关了。

**Comment by Waitforomething2023** [comment]
> > > xmake update -s dev
> > 
> > 
> > 搜索ninja确实是一个解，用emcmake ninja应该就行了，话说现在做开发的基本上都会装ninja吧
> 
> 不会，我就从来不用 ninja 。。
> 
> 如果现在没问题了，我就关了。

有问题，用ninja以后
checking for clang ... ok
checking for unzip ... no
checking for 7z ... C:\Users\luciouskami\xmake\winenv\bin\7z
checking for git ... ok
checking for gzip ... no
git rev-parse HEAD
checking for cmake ... no
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for cmake ... no
checking for cmake ... no
checking for cmake ... C:\Program Files\CMake\bin\cmake
checking for xmake::fmt ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> fmt 10.0.0 [toolchains:"wasi"]
please input: y (y/n/m)
y
checking for ping ... ok
pinging for the host(github.com) ... 1 ms
C:\Users\luciouskami\xmake\winenv\bin\7z x -y fmt-10.0.0.zip -osource.tmp

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 1279571 bytes (1250 KiB)

Extracting archive: fmt-10.0.0.zip
--
Path = fmt-10.0.0.zip
Type = zip
Physical Size = 1279571

Everything is Ok

Folders: 29
Files: 232
Size:       4599553
Compressed: 1279571
checking for ninja ... ok
checking for emsdk directory ... G:\LearnSomething\GitRepo\emsdk
checking for cmake ... C:\Program Files\CMake\bin\cmake
C:\Program Files\CMake\bin\cmake -DFMT_TEST=OFF -DFMT_DOC=OFF -DFMT_FUZZ=OFF -DCMAKE_CXX_VISIBILITY_PRESET=default -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\Users\luciouskami\AppData\Local\.xmake\packages\f\fmt\10.0.0\61ae54a034a142ab940218b042edc06e -DCMAKE_INSTALL_LIBDIR:PATH=lib -G Ninja -DCMAKE_TOOLCHAIN_FILE=G:\LearnSomething\GitRepo\emsdk\upstream\emscripten\cmake\Modules\Platform\Emscripten.cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON C:\Users\luciouskami\AppData\Local\.xmake\cache\packages\2305\f\fmt\10.0.0\source
-- CMake version: 3.26.4
-- Version: 10.0.0
-- Build type: Release
-- Performing Test HAS_NULLPTR_WARNING
-- Performing Test HAS_NULLPTR_WARNING - Success
-- Configuring done (1.8s)
-- Generating done (0.0s)
-- Build files have been written to: C:/Users/luciouskami/AppData/Local/.xmake/cache/packages/2305/f/fmt/10.0.0/source/build_61ae54a0
ninja install -C C:\Users\luciouskami\AppData\Local\.xmake\cache\packages\2305\f\fmt\10.0.0\source\build_61ae54a0 -v -j 26
ninja: Entering directory `C:\Users\luciouskami\AppData\Local\.xmake\cache\packages\2305\f\fmt\10.0.0\source\build_61ae54a0'
[1/4] G:\LearnSomething\GitRepo\emsdk\upstream\emscripten\em++.bat  -IC:/Users/luciouskami/AppData/Local/.xmake/cache/packages/2305/f/fmt/10.0.0/source/include -O3 -DNDEBUG -std=gnu++11 -fPIC -fvisibility=default -fvisibility-inlines-hidden -MD -MT CMakeFiles/fmt.dir/src/os.cc.o -MF CMakeFiles\fmt.dir\src\os.cc.o.d -o CMakeFiles/fmt.dir/src/os.cc.o -c C:/Users/luciouskami/AppData/Local/.xmake/cache/packages/2305/f/fmt/10.0.0/source/src/os.cc
[2/4] G:\LearnSomething\GitRepo\emsdk\upstream\emscripten\em++.bat  -IC:/Users/luciouskami/AppData/Local/.xmake/cache/packages/2305/f/fmt/10.0.0/source/include -O3 -DNDEBUG -std=gnu++11 -fPIC -fvisibility=default -fvisibility-inlines-hidden -MD -MT CMakeFiles/fmt.dir/src/format.cc.o -MF CMakeFiles\fmt.dir\src\format.cc.o.d -o CMakeFiles/fmt.dir/src/format.cc.o -c C:/Users/luciouskami/AppData/Local/.xmake/cache/packages/2305/f/fmt/10.0.0/source/src/f-- Install configuration: "Release"
-- Installing: C:/Users/luciouskami/AppData/Local/.xmake/packages/f/fmt/10.0.0/61ae54a034a142ab940218b042edc06e/lib/libfmt.a
-- Installing: C:/Users/luciouskami/AppData/Local/.xmake/packages/f/fmt/10.0.0/61ae54a034a142ab940218b042edc06e/include/fmt/args.h
-- Installing: C:/Users/luciouskami/AppData/Local/.xmake/packages/f/fmt/10.0.0/61ae54a034a142ab940218b042edc06e/include/fmt/chrono.h
-- Installing: C:/Users/luciouskami/AppData/Local/.xmake/packages/f/fmt/10.0.0/61ae54a034a142ab940218b042edc06e/include/fmt/color.h
-- Installing: C:/Users/luciouskami/AppData/Local/.xmake/packages/f/fmt/10.0.0/61ae54a034a142ab940218b042edc06e/include/fmt/compile.h
-- Installing: C:/Users/luciouskami/AppData/Local/.xmake/packages/f/fmt/10.0.0/61ae54a034a142ab940218b042edc06e/include/fmt/core.h
-- Installing: C:/Users/luciouskami/AppData/Local/.xmake/packages/f/fmt/10.0.0/61ae54a034a142ab940218b042edc06e/include/fmt/format.h
-- Installing: C:/Users/luciouskami/AppData/Local/.xmake/packages/f/fmt/10.0.0/61ae54a034a142ab940218b042edc06e/include/fmt/format-inl.h
-- Installing: C:/Users/luciouskami/AppData/Local/.xmake/packages/f/fmt/10.0.0/61ae54a034a142ab940218b042edc06e/include/fmt/os.h
-- Installing: C:/Users/luciouskami/AppData/Local/.xmake/packages/f/fmt/10.0.0/61ae54a034a142ab940218b042edc06e/include/fmt/ostream.h
-- Installing: C:/Users/luciouskami/AppData/Local/.xmake/packages/f/fmt/10.0.0/61ae54a034a142ab940218b042edc06e/include/fmt/printf.h
-- Installing: C:/Users/luciouskami/AppData/Local/.xmake/packages/f/fmt/10.0.0/61ae54a034a142ab940218b042edc06e/include/fmt/ranges.h
-- Installing: C:/Users/luciouskami/AppData/Local/.xmake/packages/f/fmt/10.0.0/61ae54a034a142ab940218b042edc06e/include/fmt/std.h
-- Installing: C:/Users/luciouskami/AppData/Local/.xmake/packages/f/fmt/10.0.0/61ae54a034a142ab940218b042edc06e/include/fmt/xchar.h
-- Installing: C:/Users/luciouskami/AppData/Local/.xmake/packages/f/fmt/10.0.0/61ae54a034a142ab940218b042edc06e/lib/cmake/fmt/fmt-config.cmake
-- Installing: C:/Users/luciouskami/AppData/Local/.xmake/packages/f/fmt/10.0.0/61ae54a034a142ab940218b042edc06e/lib/cmake/fmt/fmt-config-version.cmake
-- Installing: C:/Users/luciouskami/AppData/Local/.xmake/packages/f/fmt/10.0.0/61ae54a034a142ab940218b042edc06e/lib/cmake/fmt/fmt-targets.cmake
-- Installing: C:/Users/luciouskami/AppData/Local/.xmake/packages/f/fmt/10.0.0/61ae54a034a142ab940218b042edc06e/lib/cmake/fmt/fmt-targets-release.cmake
-- Installing: C:/Users/luciouskami/AppData/Local/.xmake/packages/f/fmt/10.0.0/61ae54a034a142ab940218b042edc06e/lib/pkgconfig/fmt.pc
ormat.cc
[3/4] cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E rm -f libfmt.a && G:\LearnSomething\GitRepo\emsdk\upstream\emscripten\emar.bat qc libfmt.a  CMakeFiles/fmt.dir/src/format.cc.o CMakeFiles/fmt.dir/src/os.cc.o && G:\LearnSomething\GitRepo\emsdk\upstream\emscripten\emranlib.bat libfmt.a && cd ."
[3/4] cmd.exe /C "cd /D C:\Users\luciouskami\AppData\Local\.xmake\cache\packages\2305\f\fmt\10.0.0\source\build_61ae54a0 && "C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake"
checking for xmake::fmt ... fmt 10.0.0
{
  links = {
    "fmt"
  },
  linkdirs = {
    "C:\Users\luciouskami\AppData\Local\.xmake\packages\f\fmt\10.0.0\61ae54a034a142ab940218b042edc06e\lib"
  },
  sysincludedirs = {
    "C:\Users\luciouskami\AppData\Local\.xmake\packages\f\fmt\10.0.0\61ae54a034a142ab940218b042edc06e\include"
  },
  version = "10.0.0",
  static = true,
  libfiles = {
    "C:\Users\luciouskami\AppData\Local\.xmake\packages\f\fmt\10.0.0\61ae54a034a142ab940218b042edc06e\lib\libfmt.a"
  }
}

checking for clang ... ok
checking for the c++ compiler (cxx) ... clang
checking for flags (-fPIC) ... no
checking for flags (-fdiagnostics-color=always) ... ok
checking for clang++ ... ok
checking for the linker (ld) ... clang++
checking for clang++ ... ok
checking for flags (-fPIC) ... no
LINK : fatal error LNK1181: 无法打开输入文件“fmt.lib”
clang++: error: linker command failed with exit code 1181 (use -v to see invocation)
> checking for c++ includes(fmt/format.h)
> checking for c++ links(fmt)
> checking for c++ snippet(test)
error: execv(clang++ -o C:\Users\LUCIOU~1\AppData\Local\Temp\.xmake\230524\_810C84E4D05D43708B03500186B8F770.b C:\Users\LUCIOU~1\AppData\Local\Temp\.xmake\230524\_810C84E4D05D43708B03500186B8F770.o --sysroot=nil\share\wasi-sysroot -LC:\Users\luciouskami\AppData\Local\.xmake\packages\f\fmt\10.0.0\61ae54a034a142ab940218b042edc06e\lib -lfmt) failed(1181)
  => install fmt 10.0.0 .. failed
error: install failed!

 *  终端进程“C:\Windows\System32\cmd.exe /d /c xmake -v”已终止，退出代码: 4294967295。 
 *  终端将被任务重用，按任意键关闭。 
 
是不是得用emcmake ninja

**Comment by Waitforomething2023** [comment]
-> fmt 10.0.0 [toolchains:"wasi"]
please input: y (y/n/m)

这里工具链应该是emcc吧

**Comment by Waitforomething2023** [comment]
> 

如果工具链设置为wasi，则在编译fmt时，与标志“-fPIC”不兼容，设置为emcc的情况下，加上标志“-s STANDALONE_WASM”，可以生成独立字节码而不需要gluejs

**Comment by waruqi** [comment]
>     set_toolchains("emcc")

不要用 set_toolchains，你这样只是对 target 切了 emcc 。。但是整个编译平台还是 windows ，对于包 默认用的还是 msvc 。。

得走 `xmake f -p wasm` 切整个平台，然后删了 set_toolchains

**Comment by Waitforomething2023** [comment]
> > ```
> > set_toolchains("emcc")
> > ```
> 
> 不要用 set_toolchains，你这样只是对 target 切了 emcc 。。但是整个编译平台还是 windows ，对于包 默认用的还是 msvc 。。
> 
> 得走 `xmake f -p wasm` 切整个平台，然后删了 set_toolchains
已经用 xmake f -p wasm 切了平台了，然后不设置toochains的话他默认是wasi，得手动选emcc才是emcc

**Comment by Waitforomething2023** [comment]
checking for clang ... ok
checking for the c++ compiler (cxx) ... clang
checking for flags (-fPIC) ... no
checking for flags (-O3) ... ok
checking for flags (-std=c++20) ... ok
[ 25%]: cache compiling.release src\test.cpp
clang -c -Qunused-arguments --sysroot=nil\share\wasi-sysroot -O3 -std=c++20 -o build\.objs\test\wasm\wasm32\release\src\test.cpp.o src\test.cpp
checking for flags (-MMD -MF) ... ok
checking for flags (-fdiagnostics-color=always) ... ok
checking for clang++ ... ok
checking for the linker (ld) ... clang++
checking for clang++ ... ok
checking for flags (-fPIC) ... no
checking for flags (-s WASM=1) ... no
checking for flags (-s STANDALONE_WASM) ... no
checking for flags (-s EXPORTED_FUNCTIONS=['_main']) ... no
checking for flags (-s NODEJS_CATCH_EXIT=0) ... no
checking for flags (-s NODEJS_CATCH_REJECTION=0) ... no
[ 50%]: linking.release test.html
clang++ -o build\wasm\wasm32\release\test.html build\.objs\test\wasm\wasm32\release\src\test.cpp.o --sysroot=nil\share\wasi-sysroot
[100%]: build ok, spent 1.594s
warning: add_ldflags(""-s WASM=1"") is ignored, please pass `{force = true}` or call `set_policy("check.auto_ignore_flags", false)` if you want to set it.
warning: add_ldflags(""-s STANDALONE_WASM"") is ignored, please pass `{force = true}` or call `set_policy("check.auto_ignore_flags", false)` if you want to set it.
warning: add_ldflags(""-s EXPORTED_FUNCTIONS=['_main']"") is ignored, please pass `{force = true}` or call `set_policy("check.auto_ignore_flags", false)` if you want to set it.
warning: add_ldflags(""-s NODEJS_CATCH_EXIT=0"") is ignored, please pass `{force = true}` or call `set_policy("check.auto_ignore_flags", false)` if you want to set it.
warning: add_ldflags(""-s NODEJS_CATCH_REJECTION=0"") is ignored, please pass `{force = true}` or call `set_policy("check.auto_ignore_flags", false)` if you want to set it.

**Comment by waruqi** [comment]
这不是好了么，build 过了。。

**Comment by waruqi** [comment]
这不是 fmt 安装好了么，那个是编译 link 错误，没有 fmt 包的 links ，你 add_packages("fmt") 加了么。。

**Comment by Waitforomething2023** [comment]
> 这不是 fmt 安装好了么，那个是编译 link 错误，没有 fmt 包的 links ，你 add_packages("fmt") 加了么。。

确实是因为我没加add_packages("fmt") 导致的，已经好了，测试也通过了。
另外还有个问题，生成独立的字节码的时候应该不需要生成html和js，emcc和wasi工具链都是

**Comment by waruqi** [comment]
> > 这不是 fmt 安装好了么，那个是编译 link 错误，没有 fmt 包的 links ，你 add_packages("fmt") 加了么。。
> 
> 确实是因为我没加add_packages("fmt") 导致的，已经好了，测试也通过了。 另外还有个问题，生成独立的字节码的时候应该不需要生成html和js，emcc和wasi工具链都是

有些用户需要 html ，不可能满足所有用户需求，反正生成了 html 。。也会自动生成 wasm 。。你想用哪个就哪个。。不想用 html，直接无视就行了，或者自己 after_build 里，自己删下。
