### ISSUE TITLE
xmake run 时 库搜索路径错了

### ISSUE THREAD

**Issue by yflin1** [xmake-io/xmake#3773]
### Xmake 版本

v2.7.8+HEAD.87dff1e

### 操作系统版本和架构

Ubuntu 22.04

### 描述问题

设置了本地仓库，引入 paddle，编译正常，但运行时 paddle 库的搜索路径错了，设置的库路径是 /opt/paddle/paddle/lib，但 LD_LIBRARY_PATH 里设置的库搜索路径却是 /opt/paddle/lib

### 期待的结果

运行时，LD_LIBRARY_PATH 里设置的是 /opt/paddle/paddle/lib

### 工程配置

本地仓库 第三方库 local_repo/packages/p/paddle/xmake.lua 脚本如下：
`package("paddle")
    set_homepage("https://www.paddlepaddle.org.cn")
    set_description("Paddle Inference: 是飞桨的原生推理库，提供服务器端的高性能推理能力")

    add_deps("cuda", "nccl", "tensorrt")

    on_load(function (package)
        if is_plat("linux") and is_arch("x86_64") then 
            package:set("installdir", "/opt/paddle")
        end 
    end)

    on_fetch(function (package)
        local result = {}
        result.links = {
            "paddle_inference"
        }
        result.linkdirs = {
            package:installdir("paddle/lib")
        }
        result.includedirs = {
            package:installdir("paddle/include")
        }
        result.rpathdirs = {
            package:installdir("third_party/install/mkldnn/lib"),
            package:installdir("third_party/install/mklml/lib")
        }
        return result
    end)`

target 的 before_run() 打印 LD_LIBRARY_PATH:
`target("sample")
    set_kind("binary")
   ...
    before_run(function (target)
        print("==> $(env LD_LIBRARY_PATH)")
    end)
`

**Comment by waruqi** [comment]
package:installdir 是给 安装包用的，都走 on_fetch 找系统库了，直接 linkdirs = "/opt/xxxx" 不要去设置 installdir

**Comment by yflin1** [comment]
> package:installdir 是给 安装包用的，都走 on_fetch 找系统库了，直接 linkdirs = "/opt/xxxx" 不要去设置 installdir

理解，谢谢
