### ISSUE TITLE
Centos安装xmake出错？

### ISSUE THREAD

**Issue by Ultraman95** [xmake-io/xmake#378]
![360截图-15968203](https://user-images.githubusercontent.com/1725360/55135998-29212f00-5168-11e9-8e39-3d36e2fb0551.jpg)
这个是因为 网络原因吗？

**Comment by waruqi** [comment]
恩 网络

**Comment by Ultraman95** [comment]
是被墙了吗？

**Comment by Ultraman95** [comment]
能提供rpm的安装包吗？

**Comment by yangjz1125** [comment]
应该不是吧，github没有被墙

**Comment by Ultraman95** [comment]
是因为我用的是云吗？

**Comment by waruqi** [comment]
你可以下载源码编译安装，https://xmake.io/#/zh/?id=编译安装

rpm包现在不提供了，每次发版打包好麻烦。
