### ISSUE TITLE
os.capture

### ISSUE THREAD

**Issue by LWarrens** [xmake-io/xmake#3784]
### Is your feature request related to a problem? Please describe.

I'm porting over a CMake file for a Node Addon.
In CMake I can reliably get the include directory using `require("node-addon-api").include` which is the suggested method.
I'm not sure if I can do this in xmake

### Describe the solution you'd like

Could this be solved by adding os.capture to the description scope?

**Comment by waruqi** [comment]
please get it in script scode. 

```lua
target("xxx")
    on_load(function (target)
         local includedirs = target:get("includedirs")
    end)
```


```lua
add_requires("zlib")
target("xxx")
    add_packages("zlib")
    on_load(function (target)
         local includedirs = target:pkg("zlib"):get("includedirs")
    end)
```

**Comment by LWarrens** [comment]
I'm trying to get it programatically (as node-gyp and cmake-js do e.g. [here](https://nodejs.github.io/node-addon-examples/build-tools/cmake-js/#node-addon-api), since the project is dependent on node.js
I have `node` and the `node-addon-api` npm package  in my path, 

in my xmake.lua, I can call and get output fine when I run this on windows:
```lua
on_load(function(target)
    os.execv('node', { "-p", '[...require("node-addon-api").include].filter(ch => ![10,13,34].includes(ch.charCodeAt())).join("")' })
end)
```
using the same call that[ the standard tool for Node C++ Addons](https://github.com/nodejs/node-gyp) uses to find the include dir

it will output the location of the npm package the node instance is using: `PROJECT_DIR\node_modules\node-addon-api`
which contains the headers I need.

 ```lua
 on_load(function(target)
  local node_install_dir = os.capture('node', { "-p", '[...require("node-addon-api").include].filter(ch => ![10,13,34].includes(ch.charCodeAt())).join("")' })
  print(node_install_dir)
 --- include somehow
end)
```

**Comment by SirLynix** [comment]
I think you're looking for `os.iorunv`.

example with git:
```lua
	before_build(function (target)
		local branch = "unknown-branch"
		local commitHash = "unknown-commit"
		try
		{
			function ()
				import("detect.tools.find_git")
				local git = find_git()
				if (git) then
					branch = os.iorunv(git, {"rev-parse", "--abbrev-ref", "HEAD"}):trim()
					commitHash = os.iorunv(git, {"describe", "--tags", "--long"}):trim()
				else
					error("git not found")
				end
			end,

			catch
			{
				function (err)
					print(string.format("Failed to retrieve git data: %s", err))
				end
			}
		}
-- ...
```

**Comment by waruqi** [comment]
You can use `os.iorunv` instead of `os.execv` . https://xmake.io/#/manual/builtin_modules?id=osiorunv

**Comment by LWarrens** [comment]
That works @SirLynix @waruqi!
```lua

**Comment by SirLynix** [comment]
> Now I just need to add to includedirs in the script scope

You can use `target:add("includedirs", include_dir)`
