### ISSUE TITLE
CUDA工程下编译动态链接库时出现 `-fPIC` 错误。

### ISSUE THREAD

**Issue by ivechan** [xmake-io/xmake#379]
#### 环境：
```configure
{
    arch = x86_64
    ccache = true
    host = linux
    cu-ld = /usr/local/cuda-9.2/bin/nvcc
    mode = release
    cu = /usr/local/cuda-9.2/bin/nvcc
    cc = /usr/bin/gcc
    cu-sh = /usr/local/cuda-9.2/bin/nvcc
    kind = static
    buildir = build
    cuda = /usr/local/cuda-9.2
    plat = linux
}
```

####  复现步骤：

1.

```
xmake create -P test -l cuda
cd ./test
touch src/main.c
```

2.
在 `xmake.lua `中
-  将`add_files("src/*.cu")` 更改为 `add_files("src/*.cu", "src/*.c")`
- target 类型 更改`binary` 为 `shared`

3.
`xmake build -r -v`

#### 结果：

```
/usr/local/cuda-9.2/bin/nvcc -o build/linux/x86_64/release/libtest.so build/.objs/test/linux/x86_64/release/src/main.c.o build/.objs/test/linux/x86_64/release/src/main.cu.o -shared -fPIC -Xcompiler -fPIC -m64 -Xcompiler -m64 -L/usr/local/cuda-9.2/lib
error: nvcc fatal   : Unknown option 'fPIC'
```
即在 `-shared` 后面多了 `-fPIC`。

上面输出是我将 https://github.com/xmake-io/xmake/blob/d71a01615883fffa53fbd28e578db14353628a52/xmake/modules/core/tools/nvcc.lua#L36-L38 
修改为 
```
 if not is_plat("windows") then 
     self:set("shflags", "-shared", "-Xcompiler -fPIC") 
     self:set("shared.cuflags", "-Xcompiler -fPIC"
```
后的结果，在链接阶段才出现错误。
若不更改，直接使用最新的 `master` 版本，则在编译 `main.cu` 阶段即会出现 `-fPIC` 错误。

**Comment by waruqi** [comment]
我dev分支尝试改了下，这边macosx下测试ok，你先试试 xmake update dev更新下

另外，`xmake build -r -v` 构建是默认行为，只需要敲 `xmake -r -v` 或者 `xmake` 就行了，

**Comment by ivechan** [comment]
我复现步骤写得不够严谨，我应该提醒你删掉 `main` 函数的。
dev 分支的问题是最后链接的时候把 `-shared` 丢了，而测试用例里刚好有 `main` 函数，所以你测试正常。

**Comment by waruqi** [comment]
你又改了下，你再试试，dev分支

**Comment by ivechan** [comment]
我这边测试一切正常，非常感谢，辛苦了！

**Comment by waruqi** [comment]
你再更新下dev分支试试，昨天的修改不是很完善，这块我今天稍微小重构了下，你试试是否也ok

**Comment by ivechan** [comment]
我这边没有问题。

**Comment by waruqi** [comment]
ok
