### ISSUE TITLE
Add option to set inheritance expose for all rules in target

### ISSUE THREAD

**Issue by AidanSun05** [xmake-io/xmake#3796]
### Is your feature request related to a problem? Please describe.

I have a configuration which shares common files and compiler flags with an `object` target. Currently, it needs `{ public = true }` in each option so they can be applied to inherited targets, but this makes the configuration repetitive.

```lua
target("core")
    add_packages("imgui", { public = true })
    set_kind("object")

    add_defines("UNICODE", "_UNICODE", "NOMINMAX", { public = true })

    add_cxxflags("cl::/Zc:preprocessor", { public = true })

    add_includedirs("src", { public = true })
    add_files("src/*.cpp")

target("test1")
    add_deps("core")
    add_files("main.cpp")

target("test2")
    add_deps("core")
    add_files("other/main.cpp")
```

### Describe the solution you'd like

An option like `set_expose` could set `public = true` for every option in the target:

```lua
target("core")
    set_expose("public") -- or set_expose("interface")
    set_kind("object")

    -- All options below have { public = true } implicitly set (if applicable)
    add_packages("imgui")

    add_defines("UNICODE", "_UNICODE", "NOMINMAX")

    add_cxxflags("cl::/Zc:preprocessor")

    add_includedirs("src")
    add_files("src/*.cpp")
```

**Comment by SirLynix** [comment]
Note that you can also place them outside of a target to make them local to the file / included files.

```lua
add_packages("imgui")
add_defines("UNICODE", "_UNICODE", "NOMINMAX")
add_cxxflags("cl::/Zc:preprocessor")
add_includedirs("src")

target("core")
    set_kind("object")
    add_files("src/*.cpp")

target("test1")
    add_deps("core")
    add_files("main.cpp")

target("test2")
    add_deps("core")
    add_files("other/main.cpp")
```

**Comment by AidanSun05** [comment]
Thanks for the answer @SirLynix, your solution works for my project setup.

What's the best way to proceed with this issue? I can potentially see this feature being useful in larger/more complex build scripts as it can allow more control than global options. However, if there are already existing ways to handle these situations, then I can agree on closing this.

**Comment by waruqi** [comment]
> Thanks for the answer @SirLynix, your solution works for my project setup.
> 
> What's the best way to proceed with this issue? I can potentially see this feature being useful in larger/more complex build scripts as it can allow more control than global options. However, if there are already existing ways to handle these situations, then I can agree on closing this.

What @SirLynix mentions is the recommended practice.

**Comment by SirLynix** [comment]
@AidanSun05 I have a rather complex build script which uses this, these not really "global" options as they are scoped to the file.

For example:
xmake.lua:
```lua
-- this is local to the targets defined in xmake.lua and subsequently included files
add_includedirs("include")
set_languages("c89", "cxx17")

-- [..]

includes("tests/xmake.lua")
```

tests/xmake.lua:
```lua
option("tests", { description = "Build unit tests", default = false })

if has_config("tests") then
	if is_mode("asan") then
		add_defines("CATCH_CONFIG_NO_WINDOWS_SEH")
		add_defines("CATCH_CONFIG_NO_POSIX_SIGNALS")
	end

	add_requires("catch2 3", "spirv-tools", "tiny-process-library")
	add_requires("glslang", { configs = { rtti = is_mode("ubsan") } }) -- ubsan requires rtti

	add_includedirs("src") -- this is local to the target defined in xmake/tests.lua and subsequently included files

	-- [..]
end
```

**Comment by AidanSun05** [comment]
@SirLynix I appreciate the clarification and example. I wasn't sure about the specifics of the feature, so I'll definitely look into it more.

@star-hengxing Thanks for your answer. It's close to what I was looking for (define some options together, then apply them to specific targets).

I'll consider both solutions and see which works better with my project.
