### ISSUE TITLE
Request add option for disable the zero append of utils.bin2c

### ISSUE THREAD

**Issue by Zmmfly** [xmake-io/xmake#3798]
### Is your feature request related to a problem? Please describe.

Yes, https://github.com/xmake-io/xmake/issues/1544
In this issue it describes a way to add binaries to the project.

I'm trying to use this, but I find that a zero is appended at the end.

### Describe the solution you'd like

Add binary file with option
look like:
```lua
target("test")
    add_rules("utils.bin2c", {linewidth=16, extensions={".bin"}})
    add_files("cert/*.bin", {nozeroend=true})
```

### Additional context

https://github.com/xmake-io/xmake/issues/1544
It's already have argument to disable zero append:
https://github.com/xmake-io/xmake/blob/853d25d9192c4e2c936b2dbd267342ad5a6766ae/xmake/modules/private/utils/bin2c.lua#L25-L30
But no argument can be seen in the call:
https://github.com/xmake-io/xmake/blob/853d25d9192c4e2c936b2dbd267342ad5a6766ae/xmake/rules/utils/bin2c/xmake.lua#L40-L46
https://github.com/xmake-io/xmake/blob/853d25d9192c4e2c936b2dbd267342ad5a6766ae/xmake/modules/private/utils/bin2c.lua#L87-L93

**Comment by waruqi** [comment]
try it again on dev. `xmake update -s dev`

```
target("test")
    add_rules("utils.bin2c", {linewidth=16, extensions={".bin"}, nozeroend = true})
```

**Comment by Zmmfly** [comment]
>```
>target("test")
>    add_rules("utils.bin2c", {linewidth=16, extensions={".bin"}, nozeroend = true})
>``` 
Yes, it works.
