### ISSUE TITLE
VisualStudio项目没有设置AdditionalOptions

### ISSUE THREAD

**Issue by VirFunc** [xmake-io/xmake#3807]
### Xmake 版本

v2.7.9

### 操作系统版本和架构

Windows 10 22H2

### 描述问题

使用 vsxmake 生成 VS 2022 的项目时，通过 `add_cxflags` 添加的一些 flag （如 `/Zc:__cpluscplus` ）没有写入 AdditionalOptions 属性中，这导致 VS 的智能提示错误。

在设置了 cxx17 并添加了 [/Zc:__cplusplus](https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170) 后， 用 VS 2022 打开 xmake 生成的项目时 `__cpluscplus` 仍然被智能提示识别为 `199711L`，虽然智能提示无法正确识别，但是构建是没有问题的。同样的代码，使用 CMake 生成项目则不会出现这种问题，通过对比两边生成的项目属性可以发现，CMake 向 `AditionalOptions` 写入了这个 flag（左侧为 CMake 生成的项目，右侧为 xmake 生成的项目）。经过验证，在 xmake 生成的项目属性手动设置 AditionalOptions 之后 VS 的智能提示正常工作。
![image](https://github.com/xmake-io/xmake/assets/28671722/e803e770-b5a4-4170-ba66-5b93ab9b673f)

### 期待的结果

根据 [CL Task 文档](https://learn.microsoft.com/en-us/visualstudio/msbuild/cl-task?view=vs-2022) 和 [/Zc:__cplusplus的文档](https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170)，xmake 应该将这种 flag 写到 `AditionalOptions` 属性中。

### 工程配置

项目结构
```
src
 |-main.cpp
xmake.lua
CMakeLists.txt
```
xmake.lua
```lua
set_xmakever("2.7.9")
set_project("cpp_pg")
set_languages("cxx17")

add_cxflags("/utf-8")
add_cxflags("/Zc:__cplusplus")

target("app")
    set_kind("binary")
    add_includedirs("src")
    add_files("src/**.cpp")
```
CMakeLists.txt
```
cmake_minimum_required(VERSION 3.14)
set(CMAKE_CXX_STANDARD 17)

project(cpp_pg)

add_executable(app src/main.cpp)
target_compile_options(app PRIVATE "/Zc:__cplusplus")
```

main.cpp
```c++
#include <iostream>
#include <fstream>

namespace fs = std::filesystem;

#if !(__cplusplus >= 201703L)
#error "Need C++ 17"
#endif

#if !(_MSVC_LANG >= 201703L)
#error "Need C++ 17"
#endif

int main() {
    std::ifstream fs("src/main.cpp");
    return 0;
}
```

**Comment by waruqi** [comment]
试下 https://github.com/xmake-io/xmake/pull/3811

```
xmake update -s github:xmake-io/xmake#vsxmake
```

**Comment by waruqi** [comment]
可以了么？

**Comment by VirFunc** [comment]
貌似还有问题，Additional Options 这一栏还是空的

**Comment by VirFunc** [comment]
会不会是字符串拼接有问题，官网文档给出的示例是空格分隔的命令行参数
![image](https://github.com/xmake-io/xmake/assets/28671722/9c683d9b-4dc2-4dd1-a64f-25b753dac6c8)
我用CMake生成了一个VS的工程，他这里是用空格分隔了
![image](https://github.com/xmake-io/xmake/assets/28671722/edf6ec5b-0ee4-4586-a729-bb7e47e7c38d)
我手动修改本地文件测试一下

**Comment by waruqi** [comment]
> 经过测试，我发现你这里的 `AdditionalOptions` 少打了一个 `d`。然后就是确实需要空格分隔，分号分隔不生效

我从这里直接 copy 的。

> xmake 应该将这种 flag 写到 AditionalOptions 属性中。

我更新了下，再试试，还是上面的分支

**Comment by waruqi** [comment]
可以了么

**Comment by VirFunc** [comment]
这里的`XmakeCXFlags`里的flags是用分号分隔的，vs识别不了，我尝试修改了一下`geninfo.lua`，改为空格分隔后可以正常识别。
![image](https://github.com/xmake-io/xmake/assets/28671722/808afb40-2984-47a8-9f6d-cec2b66e5c31)

**Comment by waruqi** [comment]
再试试，改过了

**Comment by VirFunc** [comment]
已经可以了，现在VS能够正确识别了，感谢

**Comment by waruqi** [comment]
我合到 dev 了
