### ISSUE TITLE
生成的 makefile 中 INSTALLDIR 在 DESTDIR 为空的情况下无法正确定义

### ISSUE THREAD

**Issue by mochaaP** [xmake-io/xmake#3808]
### Xmake 版本

2.7.9-39-g068a8296f (master)

### 操作系统版本和架构

Fedora Linux 39 (rawhide)

### 描述问题

1. `git clone https://github.com/xmake-io/xmake --recursive`
2. `./configure --generator=gmake`
3. `export PREFIX=/usr/bin`
4. `make` && `make install DESTDIR=[...]`
5. ```sh
	+ /usr/bin/make install DESTDIR=/builddir/build/BUILDROOT/xmake-2.7.9-1.fc39.x86_64
	installing build/xmake to /usr/bin
	cp: cannot create regular file '/usr/bin/xmake': Permission denied
	make: *** [makefile:2387: install] Error 1
	```

### 期待的结果

正常构建并安装，Makefile 中应为：

```makefile
# this is the build file for this project
# it is autogenerated by the xmake.sh build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

INSTALLDIR:=
ifneq ($(DESTDIR),)
INSTALLDIR:=$(DESTDIR) # <- `:=` 应改为 `=`，因为上面定义过了
endif
```

**Comment by mochaaP** [comment]
附加：这里应该用的是 `install` 而非 `cp`。
<https://man.archlinux.org/man/install.1>

**Comment by waruqi** [comment]
```
bash-5.2$ make install DESTDIR=/tmp 
installing build/xmake to /tmp/usr/bin/bin
```

我这可以的么。。

**Comment by waruqi** [comment]
> 附加：这里应该用的是 `install` 而非 `cp`。 https://man.archlinux.org/man/install.1

这跟 cp 区别在哪呢。什么时候应该用 install ？另外，这个通用么，mac, bsd, linux 上都能用 并且参数行为一致么。。?

**Comment by mochaaP** [comment]
可以參考一下 <https://unix.stackexchange.com/questions/104982/why-use-install-rather-than-cp-and-mkdir> 這裡的回答。

**Comment by waruqi** [comment]
> 附加：这里应该用的是 `install` 而非 `cp`。 https://man.archlinux.org/man/install.1

这个似乎不是很通用，macos 上参数格式不同，不通用的话，还得分平台处理 比较蛋疼，还是 cp / mkdir 更通用些。。

```
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
```

**Comment by waruqi** [comment]
INSTALLDIR 这个我 dev 上改进过了

**Comment by mochaaP** [comment]
tbox 上也有這個問題

**Comment by waruqi** [comment]
INSTALLDIR 我应该已经改进过了
