### ISSUE TITLE
vcpkg的triplet获取有误

### ISSUE THREAD

**Issue by ChrisCatCP** [xmake-io/xmake#3810]
### Xmake 版本

2.7.9

### 操作系统版本和架构

windows 11 latest

### 描述问题

项目配置为vsxmake  编译时命令行为xmake config -y  -P . -p windows -m debug -a x86 -o "build"
这里已经配置为debug了
modules\package\manager\vcpkg\find_package.lua, line 78
```
    local mode = opt.mode --这里的mode还是release
```

### 期待的结果

能正确获取到triplet

**Comment by ChrisCatCP** [comment]
补充一下  上面说法有误  获取错误的是mode而不是triplet  这会导致linkdirs会获取到release的目录

**Comment by waruqi** [comment]
这不是 bug，目前就是这么设计的，任何包，不管是 vcpkg 包，还是 xmake-repo 仓库包。。它的 configs, mode, vs_runtime 等都是需要 add_requires 里面配置的，不跟 `xmake f -m debug` 同步的。。

你得自己 `add_requires("vcpkg::zlib", {debug = true})` 切到 debug 包。

如果要跟 `xmake f -m debug` 保持同步，也得自己配置。。

```
add_requires("vcpkg::zlib", {debug = is_mode("debug")})
```

因为如果没特殊需求，即使 debug 编译，大都是也是使用 release 包，debug 包带大量符号，如果默认同步开，对于一些打包，非常占用磁盘空间，编译影响编译安装速度。

仅仅有调试需要，你自己 add_requires 里面针对性开 debug 。。如果还是想全部保持同步，就按我上面说的，走 is_mode 自己同步下。。灵活性更好

**Comment by ChrisCatCP** [comment]
行吧  之所以会产生这个问题 是因为运行库不一致会没法编译的  vc是有运行库匹配的

**Comment by waruqi** [comment]
vs runtime 和 debug mode ，都得自己切。

全局 set_runtime 可以对所有包全局切

**Comment by ChrisCatCP** [comment]
问题就是 vcpkg不受vcruntime的影响 release就是mt  debug就是mtd  默认就是relelease  所以会不匹配

**Comment by ChrisCatCP** [comment]
问题就是 vcpkg不受vcruntime的影响 release就是mt  debug就是mtd  默认就是relelease  所以会不匹配

**Comment by waruqi** [comment]
> 问题就是 vcpkg不受vcruntime的影响 release就是mt debug就是mtd 默认就是relelease 所以会不匹配

我的意思是说，这些都需要自己切，哪个不匹配，你自己 add_requires 里切哪个，都提供足够灵活性了，怎么组合 随你搞。。没说一定要设置 vs runtime 

如果 `xmake f -m debug --vs_runtime` 这种同步切，要是不匹配，你改也没机会改。。

**Comment by ChrisCatCP** [comment]
我的意思是 默认应该同步配置吧...   否则编译都编译不了  并不是说不让修改了

**Comment by ChrisCatCP** [comment]
在vcpkg中不同于xrepo   release默认值会导致运行库不一致 影响编译 虽然能自己配置debug  但是导入包的默认行为至少是应该能编译的吧

**Comment by waruqi** [comment]
> 我的意思是 默认应该同步配置吧... 否则编译都编译不了 并不是说不让修改了

不能，连 mode.release 也都是可选的配置，内置的 release/debug rule 只是辅助规则，没有硬性标准规定，debug release应该怎样，用户可以完全不用，自己配置 release debug的规则，你只能根据项目，自己配

**Comment by ChrisCatCP** [comment]
行吧  虽然是这么说 但是vcpkg会读取debug配置  来添加debug前缀

**Comment by waruqi** [comment]
> 在vcpkg中不同于xrepo release默认值会导致运行库不一致 影响编译 虽然能自己配置debug 但是导入包的默认行为至少是应该能编译的吧

xrepo本身没release默认值一说。只有附带提供的 mode.release rule，但这是可选的，可以不设置，用户也可以用 minsizerel, asan 等其他 mode

**Comment by ChrisCatCP** [comment]
好吧  那看来只能加debug  opt了
