### ISSUE TITLE
Add support for .tar.Z archives

### ISSUE THREAD

**Issue by 0x2Adr1** [xmake-io/xmake#3816]
### Is your feature request related to a problem? Please describe.

I'm trying to add [CSPICE](https://naif.jpl.nasa.gov/naif/toolkit_C_MacM1_OSX_clang_64bit.html) to `xmake-repo`. The CSPICE source code is distributed in a `.tar.Z` archive.

It looks like xmake is unable to extract the archive:

```
warning: ./xmake.lua:17: cannot match add_files("**.c") in target(cspice)
```

I think the above warning is because xmake was unable to extract the archive and therefore the C source files cannot be found.

### Describe the solution you'd like

Add support to exrtract .tar.Z archives.

**Comment by waruqi** [comment]
Thanks!
