### ISSUE TITLE
我在cmake工程下执行xmake命令报错

### ISSUE THREAD

**Issue by RunningShrimp** [xmake-io/xmake#3820]
### Xmake 版本

v2.7.9

### 操作系统版本和架构

macOS 13.4 (22F66)

### 描述问题

我的工程是cmake管理的QT demo。尝试使用xmake管理出现下面的问题
xmake f -c --require=n -p macosx -a arm64 -m release -k static --xcode=/Applications/Xcode.app
checking for Xcode directory ... /Applications/Xcode.app
checking for Codesign Identity of Xcode ... duguanjia-local.internal.baidu.com
checking for SDK version of Xcode for macosx (arm64) ... 13.3
checking for Minimal target version of Xcode for macosx (arm64) ... 13.3
xmake require -y -v -j 12 --debugdir=/Users/wangbiao/CLionProjects/As --force --shallow --build --extra={configs={shared=false},system=false} "robin-hood-hashing 3.11.5"
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
/usr/bin/git rev-parse HEAD
checking for cmake ... /Users/wangbiao/.xmake/packages/c/cmake/3.24.2/6b2b7880d90e44f69311d5a446c0fc96/bin/cmake
checking for ping ... /sbin/ping
pinging for the host(github.com) ... 94 ms
checking for cmake ... /Users/wangbiao/.xmake/packages/c/cmake/3.24.2/6b2b7880d90e44f69311d5a446c0fc96/bin/cmake
/Users/wangbiao/.xmake/packages/c/cmake/3.24.2/6b2b7880d90e44f69311d5a446c0fc96/bin/cmake -DRH_STANDALONE_PROJECT=OFF -DCMAKE_INSTALL_PREFIX=/Users/wangbiao/.xmake/packages/r/robin-hood-hashing/3.11.5/de46fe6ffef047a692b147222be6a258 -DCMAKE_INSTALL_LIBDIR:PATH=lib -G "Unix Makefiles" -DCMAKE_POSITION_INDEPENDENT_CODE=ON /Users/wangbiao/CLionProjects/As
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/wangbiao/CLionProjects/As/build_de46fe6f
make -j12
[ 25%] Automatic MOC and UIC for target ASPlayer
[ 25%] Built target ASPlayer_autogen
Consolidate compiler generated dependencies of target ASPlayer
[100%] Built target ASPlayer
make install
checking for xmake::robin-hood-hashing ... robin-hood-hashing 3.11.5
{ 
  version = "3.11.5",
  license = "MIT" 
}

patching /Users/wangbiao/.xmake/packages/r/robin-hood-hashing/3.11.5/de46fe6ffef047a692b147222be6a258/lib/pkgconfig/robin-hood-hashing.pc ..
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang ... ok
checking for the c++ compiler (cxx) ... clang
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang ... ok
checking for flags (-fPIC) ... ok
checking for flags (-fdiagnostics-color=always) ... ok
> checking for c++ includes(robin_hood.h)
> checking for c++ snippet(test)
error: /var/folders/ff/1788jj7x1ds7qd0sdt09rrm80000gn/T/.xmake501/230606/_C95CCC79A9E0406CA9E6D3F5ECF75D77.cpp:2:10: fatal error: 'robin_hood.h' file not found
#include <robin_hood.h>
         ^~~~~~~~~~~~~~
1 error generated.
  => install robin-hood-hashing 3.11.5 .. failed
error: install failed!
warning: Package deprecated, author reason:
Unfortunately I do not have time to continue development for this hashmap. I have a worthy successor though, please head over to: ankerl::unordered_dense::{map, set}
error: execv(xmake require -y -v -j 12 --debugdir=/Users/wangbiao/CLionProjects/As --force --shallow --build --extra={configs={shared=false},system=false} "robin-hood-hashing 3.11.5") failed(255)
error: execv(/Users/wangbiao/.local/bin/xrepo install -y --shallow -v -p macosx -a arm64 -m release -k static -j 12 --xcode=/Applications/Xcode.app -d . "robin-hood-hashing 3.11.5") failed(255)

### 期待的结果

能够正常生成文件xmake.lua

### 工程配置

[As.zip](https://github.com/xmake-io/xmake/files/11665010/As.zip)

### 附加信息和错误日志

checking for xrepo ... /Users/wangbiao/.local/bin/xrepo
checking for ping ... /sbin/ping
pinging for the host(gitlab.com) ... 95 ms
pinging for the host(github.com) ... 95 ms
pinging for the host(gitee.com) ... 29 ms
note: robin-hood-hashing 3.11.5 in xmake-repo found, try building it or you can run `xmake f --trybuild=` to set buildsystem (pass -y or --confirm=y/n/d to skip confirm)?
please input: y (y/n)
y
checking for platform ... macosx
checking for architecture ... arm64
checking for Xcode directory ... /Applications/Xcode.app
checking for Codesign Identity of Xcode ... duguanjia-local.internal.baidu.com
checking for SDK version of Xcode for macosx (arm64) ... 13.3
checking for Minimal target version of Xcode for macosx (arm64) ... 13.3
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
configure
{
    xcode = /Applications/Xcode.app
    plat = macosx
    kind = static
    xcode_codesign_identity = duguanjia-local.internal.baidu.com
    arch = arm64
    trybuild = xrepo
    ndk_stdcxx = true
    buildir = build
    host = macosx
    ccache = true
    mode = release
}
checking for xrepo ... /Users/wangbiao/.local/bin/xrepo
/Users/wangbiao/.local/bin/xrepo install -y --shallow -v -D -p macosx -a arm64 -m release -k static -j 12 --xcode=/Applications/Xcode.app -d . "robin-hood-hashing 3.11.5"
xmake f -c --require=n -vD -p macosx -a arm64 -m release -k static --xcode=/Applications/Xcode.app
checking for Xcode directory ... /Applications/Xcode.app
checking for Codesign Identity of Xcode ... duguanjia-local.internal.baidu.com
checking for SDK version of Xcode for macosx (arm64) ... 13.3
checking for Minimal target version of Xcode for macosx (arm64) ... 13.3
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
configure
{
    xcode_codesign_identity = duguanjia-local.internal.baidu.com
    plat = macosx
    mode = release
    clean = true
    ndk_stdcxx = true
    kind = static
    host = macosx
    xcode = /Applications/Xcode.app
    ccache = true
    buildir = build
    arch = arm64
}
xmake require -y -v -D -j 12 --debugdir=/Users/wangbiao/CLionProjects/As --force --shallow --build --extra={system=false,configs={shared=false}} "robin-hood-hashing 3.11.5"
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
/usr/bin/git rev-parse HEAD
checking for cmake ... /Users/wangbiao/.xmake/packages/c/cmake/3.24.2/6b2b7880d90e44f69311d5a446c0fc96/bin/cmake
checking for ping ... /sbin/ping
pinging for the host(github.com) ... 98 ms
checking for cmake ... /Users/wangbiao/.xmake/packages/c/cmake/3.24.2/6b2b7880d90e44f69311d5a446c0fc96/bin/cmake
/Users/wangbiao/.xmake/packages/c/cmake/3.24.2/6b2b7880d90e44f69311d5a446c0fc96/bin/cmake -DRH_STANDALONE_PROJECT=OFF -DCMAKE_INSTALL_PREFIX=/Users/wangbiao/.xmake/packages/r/robin-hood-hashing/3.11.5/de46fe6ffef047a692b147222be6a258 -DCMAKE_INSTALL_LIBDIR:PATH=lib -G "Unix Makefiles" -DCMAKE_POSITION_INDEPENDENT_CODE=ON /Users/wangbiao/CLionProjects/As
-- The C compiler identification is AppleClang 14.0.3.14030022
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE  
-- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/System/Library/Frameworks/OpenGL.framework   
-- Found WrapOpenGL: TRUE  
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_INSTALL_LIBDIR
    RH_STANDALONE_PROJECT

-- Build files have been written to: /Users/wangbiao/CLionProjects/As/build_de46fe6f
make -j12 VERBOSE=1
/Users/wangbiao/.xmake/packages/c/cmake/3.24.2/6b2b7880d90e44f69311d5a446c0fc96/bin/cmake -S/Users/wangbiao/CLionProjects/As -B/Users/wangbiao/CLionProjects/As/build_de46fe6f --check-build-system CMakeFiles/Makefile.cmake 0
/Users/wangbiao/.xmake/packages/c/cmake/3.24.2/6b2b7880d90e44f69311d5a446c0fc96/bin/cmake -E cmake_progress_start /Users/wangbiao/CLionProjects/As/build_de46fe6f/CMakeFiles /Users/wangbiao/CLionProjects/As/build_de46fe6f//CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/ASPlayer_autogen.dir/build.make CMakeFiles/ASPlayer_autogen.dir/depend
cd /Users/wangbiao/CLionProjects/As/build_de46fe6f && /Users/wangbiao/.xmake/packages/c/cmake/3.24.2/6b2b7880d90e44f69311d5a446c0fc96/bin/cmake -E cmake_depends "Unix Makefiles" /Users/wangbiao/CLionProjects/As /Users/wangbiao/CLionProjects/As /Users/wangbiao/CLionProjects/As/build_de46fe6f /Users/wangbiao/CLionProjects/As/build_de46fe6f /Users/wangbiao/CLionProjects/As/build_de46fe6f/CMakeFiles/ASPlayer_autogen.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/ASPlayer_autogen.dir/build.make CMakeFiles/ASPlayer_autogen.dir/build
[ 25%] Automatic MOC and UIC for target ASPlayer
/Users/wangbiao/.xmake/packages/c/cmake/3.24.2/6b2b7880d90e44f69311d5a446c0fc96/bin/cmake -E cmake_autogen /Users/wangbiao/CLionProjects/As/build_de46fe6f/CMakeFiles/ASPlayer_autogen.dir/AutogenInfo.json ""
AutoGen: Refreshing parse cache because it doesn't exist.
AutoMoc: Generating "SRC:/build_de46fe6f/ASPlayer_autogen/moc_predefs.h", because it doesn't exist.
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -dM -E -c /Users/wangbiao/.xmake/packages/c/cmake/3.24.2/6b2b7880d90e44f69311d5a446c0fc96/share/cmake-3.24/Modules/CMakeCXXCompilerABI.cpp -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I/Users/wangbiao/Qt/6.2.4/macos/lib/QtCore.framework -I/Users/wangbiao/Qt/6.2.4/macos/lib/QtCore.framework/Headers -I/Users/wangbiao/Qt/6.2.4/macos/mkspecs/macx-clang -I/Users/wangbiao/Qt/6.2.4/macos/include -I/Users/wangbiao/Qt/6.2.4/macos/lib/QtGui.framework -I/Users/wangbiao/Qt/6.2.4/macos/lib/QtGui.framework/Headers -I/Users/wangbiao/Qt/6.2.4/macos/lib/QtWidgets.framework -I/Users/wangbiao/Qt/6.2.4/macos/lib/QtWidgets.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.3/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F /Users/wangbiao/Qt/6.2.4/macos/lib
AutoGen: Parsing "SRC:/main.cpp"
AutoMoc: Generating MOC compilation "SRC:/build_de46fe6f/ASPlayer_autogen/mocs_compilation.cpp"
AutoGen: Writing the parse cache file "SRC:/build_de46fe6f/CMakeFiles/ASPlayer_autogen.dir/ParseCache.txt"
AutoGen: Writing the settings file "SRC:/build_de46fe6f/CMakeFiles/ASPlayer_autogen.dir/AutogenUsed.txt"
[ 25%] Built target ASPlayer_autogen
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/ASPlayer.dir/build.make CMakeFiles/ASPlayer.dir/depend
cd /Users/wangbiao/CLionProjects/As/build_de46fe6f && /Users/wangbiao/.xmake/packages/c/cmake/3.24.2/6b2b7880d90e44f69311d5a446c0fc96/bin/cmake -E cmake_depends "Unix Makefiles" /Users/wangbiao/CLionProjects/As /Users/wangbiao/CLionProjects/As /Users/wangbiao/CLionProjects/As/build_de46fe6f /Users/wangbiao/CLionProjects/As/build_de46fe6f /Users/wangbiao/CLionProjects/As/build_de46fe6f/CMakeFiles/ASPlayer.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/ASPlayer.dir/build.make CMakeFiles/ASPlayer.dir/build
[ 75%] Building CXX object CMakeFiles/ASPlayer.dir/ASPlayer_autogen/mocs_compilation.cpp.o
[ 75%] Building CXX object CMakeFiles/ASPlayer.dir/main.cpp.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I/Users/wangbiao/CLionProjects/As/build_de46fe6f/ASPlayer_autogen/include -iframework /Users/wangbiao/Qt/6.2.4/macos/lib -isystem /Users/wangbiao/Qt/6.2.4/macos/lib/QtCore.framework/Headers -isystem /Users/wangbiao/Qt/6.2.4/macos/mkspecs/macx-clang -isystem /Users/wangbiao/Qt/6.2.4/macos/include -isystem /Users/wangbiao/Qt/6.2.4/macos/lib/QtGui.framework/Headers -isystem /Users/wangbiao/Qt/6.2.4/macos/lib/QtWidgets.framework/Headers -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -fPIE -std=gnu++2b -MD -MT CMakeFiles/ASPlayer.dir/ASPlayer_autogen/mocs_compilation.cpp.o -MF CMakeFiles/ASPlayer.dir/ASPlayer_autogen/mocs_compilation.cpp.o.d -o CMakeFiles/ASPlayer.dir/ASPlayer_autogen/mocs_compilation.cpp.o -c /Users/wangbiao/CLionProjects/As/build_de46fe6f/ASPlayer_autogen/mocs_compilation.cpp
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I/Users/wangbiao/CLionProjects/As/build_de46fe6f/ASPlayer_autogen/include -iframework /Users/wangbiao/Qt/6.2.4/macos/lib -isystem /Users/wangbiao/Qt/6.2.4/macos/lib/QtCore.framework/Headers -isystem /Users/wangbiao/Qt/6.2.4/macos/mkspecs/macx-clang -isystem /Users/wangbiao/Qt/6.2.4/macos/include -isystem /Users/wangbiao/Qt/6.2.4/macos/lib/QtGui.framework/Headers -isystem /Users/wangbiao/Qt/6.2.4/macos/lib/QtWidgets.framework/Headers -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -fPIE -std=gnu++2b -MD -MT CMakeFiles/ASPlayer.dir/main.cpp.o -MF CMakeFiles/ASPlayer.dir/main.cpp.o.d -o CMakeFiles/ASPlayer.dir/main.cpp.o -c /Users/wangbiao/CLionProjects/As/main.cpp
[100%] Linking CXX executable ASPlayer
/Users/wangbiao/.xmake/packages/c/cmake/3.24.2/6b2b7880d90e44f69311d5a446c0fc96/bin/cmake -E cmake_link_script CMakeFiles/ASPlayer.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -L/opt/homebrew/opt/llvm/lib CMakeFiles/ASPlayer.dir/ASPlayer_autogen/mocs_compilation.cpp.o CMakeFiles/ASPlayer.dir/main.cpp.o -o ASPlayer -F/Users/wangbiao/Qt/6.2.4/macos/lib  -Wl,-rpath,/Users/wangbiao/Qt/6.2.4/macos/lib /Users/wangbiao/Qt/6.2.4/macos/lib/QtWidgets.framework/Versions/A/QtWidgets /Users/wangbiao/Qt/6.2.4/macos/lib/QtGui.framework/Versions/A/QtGui /Users/wangbiao/Qt/6.2.4/macos/lib/QtCore.framework/Versions/A/QtCore -framework DiskArbitration -framework IOKit -Xlinker -framework -Xlinker OpenGL -Xlinker -framework -Xlinker AGL -framework AppKit -framework ImageIO -framework Metal 
[100%] Built target ASPlayer
/Users/wangbiao/.xmake/packages/c/cmake/3.24.2/6b2b7880d90e44f69311d5a446c0fc96/bin/cmake -E cmake_progress_start /Users/wangbiao/CLionProjects/As/build_de46fe6f/CMakeFiles 0
make install
finding robin-hood-hashing from xmake ..
checking for xmake::robin-hood-hashing ... robin-hood-hashing 3.11.5
{ 
  version = "3.11.5",
  license = "MIT" 
}

patching /Users/wangbiao/.xmake/packages/r/robin-hood-hashing/3.11.5/de46fe6ffef047a692b147222be6a258/lib/pkgconfig/robin-hood-hashing.pc ..
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang ... ok
checking for the c++ compiler (cxx) ... clang
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang ... ok
checking for flags (-fPIC) ... ok
> clang "-fPIC" "-Qunused-arguments" "-target" "arm64-apple-macos13.3" "-isysroot" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk"
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -c -Qunused-arguments -target arm64-apple-macos13.3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -std=c++14 -o /var/folders/ff/1788jj7x1ds7qd0sdt09rrm80000gn/T/.xmake501/230606/_1E7EDDE8A52F462081181C7C09E0D060.o /var/folders/ff/1788jj7x1ds7qd0sdt09rrm80000gn/T/.xmake501/230606/_C95CCC79A9E0406CA9E6D3F5ECF75D77.cpp
checking for flags (-fdiagnostics-color=always) ... ok
> clang "-fdiagnostics-color=always" "-Qunused-arguments" "-target" "arm64-apple-macos13.3" "-isysroot" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk"
> checking for c++ includes(robin_hood.h)
> checking for c++ snippet(test)
checkinfo: ...amdir/core/sandbox/modules/import/core/tool/compiler.lua:84: @programdir/modules/core/tools/gcc.lua:721: /var/folders/ff/1788jj7x1ds7qd0sdt09rrm80000gn/T/.xmake501/230606/_C95CCC79A9E0406CA9E6D3F5ECF75D77.cpp:2:10: fatal error: 'robin_hood.h' file not found
#include <robin_hood.h>
         ^~~~~~~~~~~~~~
1 error generated.
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:913]:
    [@programdir/modules/core/tools/gcc.lua:721]: in function 'catch'
    [@programdir/core/sandbox/modules/try.lua:123]: in function 'try'
    [@programdir/modules/core/tools/gcc.lua:662]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/core/tool/compiler.lua:278]: in function 'compile'
    [...amdir/core/sandbox/modules/import/core/tool/compiler.lua:82]: in function 'compile'
    [@programdir/modules/lib/detect/check_cxsnippets.lua:246]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:117]: in function 'try'
    [@programdir/modules/lib/detect/check_cxsnippets.lua:240]:
    [...ories/xmake-repo/packages/r/robin-hood-hashing/xmake.lua:23]: in function 'script'
    [...dir/modules/private/action/require/impl/utils/filter.lua:125]: in function 'call'
    [...dir/modules/private/action/require/impl/actions/test.lua:41]:
    [.../modules/private/action/require/impl/actions/install.lua:407]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:117]: in function 'try'
    [.../modules/private/action/require/impl/actions/install.lua:328]:
    [...modules/private/action/require/impl/install_packages.lua:479]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:232]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:117]: in function 'try'
    [@programdir/modules/private/async/runjobs.lua:218]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:404]:

error: ...ories/xmake-repo/packages/r/robin-hood-hashing/xmake.lua:23: ...amdir/core/sandbox/modules/import/core/tool/compiler.lua:84: @programdir/modules/core/tools/gcc.lua:721: /var/folders/ff/1788jj7x1ds7qd0sdt09rrm80000gn/T/.xmake501/230606/_C95CCC79A9E0406CA9E6D3F5ECF75D77.cpp:2:10: fatal error: 'robin_hood.h' file not found
#include <robin_hood.h>
         ^~~~~~~~~~~~~~
1 error generated.
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:913]:
    [@programdir/modules/core/tools/gcc.lua:721]: in function 'catch'
    [@programdir/core/sandbox/modules/try.lua:123]: in function 'try'
    [@programdir/modules/core/tools/gcc.lua:662]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/core/tool/compiler.lua:278]: in function 'compile'
    [...amdir/core/sandbox/modules/import/core/tool/compiler.lua:82]: in function 'compile'
    [@programdir/modules/lib/detect/check_cxsnippets.lua:246]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:117]: in function 'try'
    [@programdir/modules/lib/detect/check_cxsnippets.lua:240]:
    [...ories/xmake-repo/packages/r/robin-hood-hashing/xmake.lua:23]: in function 'script'
    [...dir/modules/private/action/require/impl/utils/filter.lua:125]: in function 'call'
    [...dir/modules/private/action/require/impl/actions/test.lua:41]:
    [.../modules/private/action/require/impl/actions/install.lua:407]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:117]: in function 'try'
    [.../modules/private/action/require/impl/actions/install.lua:328]:
    [...modules/private/action/require/impl/install_packages.lua:479]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:232]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:117]: in function 'try'
    [@programdir/modules/private/async/runjobs.lua:218]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:404]:

  => install robin-hood-hashing 3.11.5 .. failed
error: @programdir/modules/private/async/runjobs.lua:256: .../modules/private/action/require/impl/actions/install.lua:469: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:913]:
    [.../modules/private/action/require/impl/actions/install.lua:469]: in function 'catch'
    [@programdir/core/sandbox/modules/try.lua:123]: in function 'try'
    [.../modules/private/action/require/impl/actions/install.lua:328]:
    [...modules/private/action/require/impl/install_packages.lua:479]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:232]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:913: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir/modules/private/async/runjobs.lua:256: in field 'catch'
        @programdir/core/sandbox/modules/try.lua:123: in global 'try'
        @programdir/modules/private/async/runjobs.lua:218: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>
warning: Package deprecated, author reason:
Unfortunately I do not have time to continue development for this hashmap. I have a worthy successor though, please head over to: ankerl::unordered_dense::{map, set}
error: @programdir/core/main.lua:300: @programdir/core/sandbox/modules/os.lua:378: execv(xmake require -y -v -D -j 12 --debugdir=/Users/wangbiao/CLionProjects/As --force --shallow --build --extra={system=false,configs={shared=false}} "robin-hood-hashing 3.11.5") failed(255)
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:913]:
    [@programdir/core/sandbox/modules/os.lua:378]:
    [@programdir/modules/private/xrepo/action/install.lua:300]: in function '_install_packages'
    [@programdir/modules/private/xrepo/action/install.lua:307]:
    [@programdir/modules/private/xrepo/main.lua:196]:
    [@programdir/plugins/lua/main.lua:123]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/core/base/task.lua:501]: in function 'run'
    [@programdir/core/main.lua:298]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:404]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:913: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir/core/main.lua:300: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>
error: @programdir/core/main.lua:300: @programdir/core/sandbox/modules/os.lua:378: execv(/Users/wangbiao/.local/bin/xrepo install -y --shallow -v -D -p macosx -a arm64 -m release -k static -j 12 --xcode=/Applications/Xcode.app -d . "robin-hood-hashing 3.11.5") failed(255)
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:913]:
    [@programdir/core/sandbox/modules/os.lua:378]:
    [@programdir/modules/private/action/trybuild/xrepo.lua:216]: in function 'build'
    [@programdir/actions/build/main.lua:46]: in function '_do_try_build'
    [@programdir/actions/build/main.lua:82]: in function '_try_build'
    [@programdir/actions/build/main.lua:136]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/core/base/task.lua:501]: in function 'run'
    [@programdir/core/main.lua:298]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:404]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:913: in function 'os.raiselevel'
        (...tail calls...)
        @programdir/core/main.lua:300: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>

**Comment by waruqi** [comment]
> 能够正常生成文件xmake.lua

首先，xmake 不能将 cmake 工程自动转成 xmake.lua ，它只提供了 trybuild 模式，也就是探测到 cmakelists.txt 工程，自动调用 cmake ，帮你执行 cmake 配置编译，简化你对 cmake 的使用而已，但这不完全可靠的，你可以自己执行 cmake 编译，没有本质区别。。

> note: robin-hood-hashing 3.11.5 in xmake-repo found, try building it or you can run xmake f --trybuild= to set buildsystem (pass -y or --confirm=y/n/d to skip confirm)?
please input: y (y/n)
y

其次，xmake 会自动对第三方项目，匹配 xmake-repo 中仓库的包，尝试更可靠的编译，但是不一定完全匹配对，这里错误把你的项目匹配成了 robin-hood-hashing，然后执行了 robin-hood-hashing 的构建脚本。。

所以，看到这个提示，如果不是 robin-hood-hashing ，就不要敲 y ，应该敲 n，仔细看上面的提示

> note: CMakeLists.txt found, try building it or you can run `xmake f --trybuild=` to set buildsystem (pass -y or --confirm=y/n/d to skip confirm)?
please input: y (y/n)

如果提示这个，才敲 y ，尝试性执行 cmake 进行编译，但不完全可靠

总结：

1. 如果这是你自己的 cmake 项目，建议直接 cmake 运行编译。。
2. 如果是知名的第三方 cmake 库项目，可以执行 xmake 尝试性编译，准确匹配到 xmake-repo 包，编译通常能过，匹配不到，尝试性编译，成功率 50%
3. 如果想转 xmake.lua ，自己手动转，目前没自动转的功能，只有 xmake 转 cmake 倒是可以的。

**Comment by RunningShrimp** [comment]
好些谢谢
