### ISSUE TITLE
xmake pause too long time

### ISSUE THREAD

**Issue by csrlsm** [xmake-io/xmake#3826]
### Xmake 版本

v2.7.3

### 操作系统版本和架构

windows server 2019 1809 17763.3650

### 描述问题

when i run xmake -y -v after xmake f -m release -v -y, it take long time (at least 1min) to begin run the process.

### 期待的结果

i want to know what happen (or why)  when i enter "xmake -v -y" before it start the process

### 附加信息和错误日志

![image](https://github.com/xmake-io/xmake/assets/18453523/6127c343-0469-4a41-84b3-8b8ace83bf30)

**Comment by waruqi** [comment]
Can you try https://github.com/xmake-io/xmake/issues/2033?
