### ISSUE TITLE
使用包时修改了readonly的配置应该中断执行

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#3829]
### 你在什么场景下需要该功能？

比如对于tbb这个包，xrepo info tbb看到有shared这个config
![image](https://github.com/xmake-io/xmake/assets/97490782/711929b0-627a-4026-a81e-a43528d99a7b)
于是自己改配置为false，但是最后生成的还是用的动态库
去xmake-repo仓库看才发现这个配置是readonly的。
![image](https://github.com/xmake-io/xmake/assets/97490782/3e4b11f7-3471-4ced-b3eb-6c0d0f81d279)
在修改这个config的时候应该进行提示吧。
不然用户得去翻脚本才知道改了不生效的原因。

### 描述可能的解决方案

在使用包时，如果在config中修改了readonly的配置应该中断xmake执行并进行提示

**Comment by waruqi** [comment]
中断不行，这会 break 很多现成的工程，顶多加个 check warning

**Comment by heheda123123** [comment]
> 中断不行，这会 break 很多现成的工程，顶多加个 check warning

不过这也意味着现在很多工程有无效的config。

可以的，加个 check warning 也行

**Comment by waruqi** [comment]
加了
