### ISSUE TITLE
centos上root问题

### ISSUE THREAD

**Issue by Ultraman95** [xmake-io/xmake#383]
已经是root用户，使用xmake命令依然需要什么root

error: Running xmake as root is extremely dangerous and no longer supported.
As xmake does not drop privileges on installation you would be giving all
build scripts full access to your system. 
Or you can add `--root` option or XMAKE_ROOT=y to allow run as root temporarily.

该如何处理？
还有个问题就是使用bash <(curl -fsSL https://raw.githubusercontent.com/tboox/xmake/master/scripts/get.sh)这个命令，在root用户下依然无法安装，在CentOS下

**Comment by waruqi** [comment]
为了安全性，xmake默认不建议在root下使用，所以会有这提示，如果用户非要在root下使用，可以通过 每次执行命令的时候，追加--root参数，比如xmake --root，或者设置 XMAKE_ROOT=y 环境变量，来启用root下使用

**Comment by Ultraman95** [comment]
使用bash <(curl -fsSL https://raw.githubusercontent.com/tboox/xmake/master/scripts/get.sh)这个命令，在root用户下依然无法安装，这个也受限制吗？

**Comment by waruqi** [comment]
脚本里面安装完 会执行下 xmake --version 你执行安装脚本后提示这个信息，说明xmake已经root下装好了，只是在最后执行xmake --version时候检测到了root，提示了下

你可以重新开个新终端，或者执行source ~/.xmake/profile 加载下xmake 的path 就好了，新开的终端不用执行，会自动生效，因为xmake通过脚本默认并没有装在/usr/bin下
