### ISSUE TITLE
Warn user when `xmake run` if related files were updated but not rebuilt

### ISSUE THREAD

**Issue by Sssssaltyfish** [xmake-io/xmake#3836]
### Is your feature request related to a problem? Please describe.

Sometimes it is annoying to find `xmake run` is actually running an outdated version of binary, and xmake just lets it happen without letting the user acknowledge it. I think it might be better if there's an option to enable this kind of warning.

### Describe the solution you'd like

Add an option that:

Assume a binary target `A`, of which some related files were updated after the last time the user built it, warn the user "running an outdated version of binary of `A`, consider rebuilding it" after or before `xmake run` output.

### Describe alternatives you've considered

Rebuild the target automatically before executing `xmake run`, if related files were updated after the last build.

I know this snippet would be likely to get this job done:

```lua
before_run(function(target)
    os.execv("xmake", {"build", target:name()}
end)
```

but I think an explicit option would make it clearer.

**Comment by waruqi** [comment]
This requires detecting if the file code has been changed and I would not consider it. But you can use `xmake watch` to be able to support it.

https://xmake.io/#/plugin/builtin_plugins?id=watching-for-file-updates
