### ISSUE TITLE
测试包时对add_resources下载的内容也进行缓存

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#3840]
### 你在什么场景下需要该功能？

比如测试包的时候执行命令
```
xmake l scripts/test.lua -v -D --shallow  wxwidgets
```
使用了`--shallow`参数会对`add_urls`下载的内容进行缓存，但是不会缓存如图这些用`add_resources`指定的文件
测试的时候就会反复下载影响效率
![image](https://github.com/xmake-io/xmake/assets/97490782/b88e3a05-09b7-4ee5-bf84-622c8abe8cf8)

### 描述可能的解决方案

用`--shallow`参数的时候也缓存add_resources下载的内容

**Comment by waruqi** [comment]
你可以调下这里，按理 resources 目前也是做了缓存的

https://github.com/xmake-io/xmake/blob/a0dfaf3aec07cf0c14e3eb81ffe00f69864d90da/xmake/modules/private/action/require/impl/actions/download_resources.lua#L103

**Comment by heheda123123** [comment]
> 你可以调下这里，按理 resources 目前也是做了缓存的
> 
> https://github.com/xmake-io/xmake/blob/a0dfaf3aec07cf0c14e3eb81ffe00f69864d90da/xmake/modules/private/action/require/impl/actions/download_resources.lua#L103

我这样改源码想把中间变量输出出来有什么问题吗？报错了
![image](https://github.com/xmake-io/xmake/assets/97490782/358486c5-8d33-4c55-b145-68bc8d5788b5)
![image](https://github.com/xmake-io/xmake/assets/97490782/daa28c48-74ee-49b2-b68f-63bbe1426d9f)

**Comment by heheda123123** [comment]
好像破案了，`option.get("force")`被设置成了true
我这样改了下源码，用了`--shallow`但是force还是true
![image](https://github.com/xmake-io/xmake/assets/97490782/06c0085c-7e9e-446b-854c-b7f05f5b09a2)
![image](https://github.com/xmake-io/xmake/assets/97490782/cf24c08b-f8a8-4341-a8c1-05ab1ab2c980)
![image](https://github.com/xmake-io/xmake/assets/97490782/1eb4800d-2ab7-4b1d-9ceb-fa0fb985ff1e)

（另外：因为不知道怎么编译win版的xmake，所以这里在linux下加了add_resources，不过应该不影响这里）

**Comment by waruqi** [comment]
test.lua 对 测试包加了 --force，这个是必须的。否则没法每次执行 重复测试包

**Comment by waruqi** [comment]
我暂时去掉这个 force 判断了，先试试吧

**Comment by heheda123123** [comment]
> 我暂时去掉这个 force 判断了，先试试吧

测了下，去掉开头这个force判断就可以了
