### ISSUE TITLE
`xmake` rebuilds static/shared cuda target everytime if `set_pcxxheader` is called inside this target

### ISSUE THREAD

**Issue by Sssssaltyfish** [xmake-io/xmake#3843]
### Xmake Version

2.7.9

### Operating System Version and Architecture

Windows 11 version 25375.1 with Windows Feature Experience Pack 1000.25350.1000.0, x86-64

### Describe Bug

`xmake` rebuilds cuda target every time if `set_pcxxheader` is called inside it.

A minimal reproducible example is:

```shell
❯ tree
.
├── src
│   ├── main.cpp
│   ├── main.cu
│   └── test.h
└── xmake.lua

1 directory, 4 files
```

`main.cu` and `test.h` are empty files and `main.cpp` has an empty `int main()`. `xmake.lua` is as below.

Tested on Windows 11 and WSL2 Ubuntu-22.04.

On Windows:

<img width="296" alt="image" src="https://github.com/xmake-io/xmake/assets/47731209/03a44014-3fdb-47ac-9040-8aa1ad8048fd">

On WSL2:

<img width="273" alt="image" src="https://github.com/xmake-io/xmake/assets/47731209/432763ad-63c0-4c03-b58d-057614bc5f3c">

### Expected Behavior

No target shall be rebuilt as long as no file is updated, just as the behavior when the `set_pcxxheader` line is commented out.

<img width="320" alt="image" src="https://github.com/xmake-io/xmake/assets/47731209/a8456b14-ffbe-4267-afe2-6f9dabb1d787">

Or if cuda target does not support `set_pcxxheader`, the user should at least get a warning.

### Project Configuration

```lua
target("lib", function()
    set_kind("static")
    add_files("src/*.cu")
    set_policy("build.cuda.devlink", true)
    set_pcxxheader("src/test.h")
end)

target("main", function()
    set_kind("binary")
    add_deps("lib")
    add_files("src/*.cpp")
end)
```

**Comment by waruqi** [comment]
try this patch. https://github.com/xmake-io/xmake/pull/3850

```console
xmake update -s github:xmake-io/xmake#pch
```
