### ISSUE TITLE
文档没有提到windows下怎么编译xmake

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#3844]
### 你在什么场景下需要该功能？

提了另一个issue，https://github.com/xmake-io/xmake/issues/3840

想改xmake源码，把中间变量的值输出出来看，但是翻了下xmake的文档，是下面这样写的
configure是个sh脚本，windows上没法用，其他地方翻了下也没看到windows怎么编译

![image](https://github.com/xmake-io/xmake/assets/97490782/32be7214-ea46-46c5-bf65-c507aad29298)

### 描述可能的解决方案

文档中补充windows下是怎么编译xmake的

**Comment by star-hengxing** [comment]
windows 用 xmake 自举（

**Comment by heheda123123** [comment]
> windows 用 xmake 自举（

没看懂。我在源码目录下直接执行xmake也不行，另外也没看到哪里有xmake.lua呀

**Comment by star-hengxing** [comment]
在 core 目录下。。

**Comment by heheda123123** [comment]
> 在 core 目录下。。

![image](https://github.com/xmake-io/xmake/assets/97490782/a5c9fe0e-7067-4db0-af2e-443a895e9b8e)

**Comment by star-hengxing** [comment]
你确定你 git 子模块也拉取了？

**Comment by heheda123123** [comment]
额，可以了，忘了这个仓库是之前拉的没recursive，我的锅，刚刚已经在linux上编译了一个，问题解决了
https://github.com/xmake-io/xmake/issues/3840

**Comment by heheda123123** [comment]
不过文档还是可以补充下

**Comment by waruqi** [comment]
文档可以提 pr 过来补充下

**Comment by heheda123123** [comment]
> 文档可以提 pr 过来补充下

https://github.com/xmake-io/xmake-docs/pull/127

**Comment by heheda123123** [comment]
提这个pr的时候发现文档写得还是有问题，编译能通过，但是编译出来的程序运行不了
https://github.com/xmake-io/xmake/pull/3863
