### ISSUE TITLE
Centos上编译，错误信息不足

### ISSUE THREAD

**Issue by Ultraman95** [xmake-io/xmake#385]
error:      Json::Reader jsonReader(Json::Features::strictMode());
                                                         ^
                 args.push_back(jsonRoot["args"][i].asString());
                                                ^
In file included from ../../sourcebase/json/json/json.h:10:0,
                 from ../../sourceapp/wsfront/wsbusiness/wsBusinessSession.h:15,
                 from ../../sourceapp/wsfront/wsbusiness/wsBusinessSession.cpp:9:
   Value& operator[](ArrayIndex index);
          ^
   Value& operator[](int index);
          ^
   const Value& operator[](ArrayIndex index) const;
                ^
   const Value& operator[](int index) const;
                ^
   Value& operator[](const char* key);
          ^
   const Value& operator[](const char* key) const;
                ^
   Value& operator[](const JSONCPP_STRING& key);
          ^
   const Value& operator[](const JSONCPP_STRING& key) const;
                ^
         sprintf(szNowStr, "%lld", now);
                                      ^
     Json::Reader jsonReader(Json::Features::strictMode());
                                                         ^

类似这种错误信息，感觉不太明确

**Comment by waruqi** [comment]
执行 xmake -v 可获取完整编译错误信息，如果这样还是不明确 就只能给编译器提issues了 你先试试吧 加-v

**Comment by Ultraman95** [comment]
JsonCpp库，jsonRoot["args"][i]这种用法是可以的，在linux下就是编译不过，windows下没有问题

**Comment by Ultraman95** [comment]
我加了-v,基本没有太多提示

**Comment by Ultraman95** [comment]
会不会有这种情况，在linux下手写makefile可以编译通过，用xmake就不行

**Comment by waruqi** [comment]
这边只处理xmake相关使用问题，不对源码上的编译错误提供技术支持，这块你可以google下 相关c++语法 和编译器的支持力度，自行检查源码写法是否正确，以及不同编译器下 默认启用的c++标准

你可以尝试通过set_languages设置调整c++ std标准编译

**Comment by waruqi** [comment]
> 会不会有这种情况，在linux下手写makefile可以编译通过，用xmake就不行

除非编译的flags不同，这个你可以自行对比，如果flags相同，行为是一致的

编译错误跟构建工具无关

**Comment by Ultraman95** [comment]
目前发现xmake build -v产生的错误信息不足
我现在一般这么办，先通过xmake project -k makefile,然后make一下，此时.build.log这个文件的错误信息比较充足
为什么xmake build -v要删除必要的错误信息呢？

**Comment by waruqi** [comment]
-v不会过滤处理错误信息，都是原样输出的，如果你觉得有输出信息丢失了 可以吧make的输出 都贴下 对比下

**Comment by waruqi** [comment]
-v不会过滤处理错误信息，都是原样输出的，如果你觉得有输出信息丢失了 可以吧make的输出 都贴下 对比下

**Comment by waruqi** [comment]
要么就是 在过滤 头文件依赖的 时候，错误过滤掉了部分信息，你可以调下这块。

https://github.com/xmake-io/xmake/blob/85cb688e30f996c5ac1036ec99b6c7c1a45cb035/xmake/modules/core/tools/gcc.lua#L344-L357

**Comment by Ultraman95** [comment]
line:startswith(".") 这句话有点问题
我的错误信息是这样“../../sourceapp/qmarket/qmarket.cpp:36:5: error: ‘pid’ was not declared in this scope”
这句话就被过滤了

**Comment by Ultraman95** [comment]
编译器的错误信息，尽量不要过滤

**Comment by waruqi** [comment]
> line:startswith(".") 这句话有点问题
> 我的错误信息是这样“../../sourceapp/qmarket/qmarket.cpp:36:5: error: ‘pid’ was not declared in this scope”
> 这句话就被过滤了

回头我兼容下

**Comment by waruqi** [comment]
> 编译器的错误信息，尽量不要过滤

必须要过滤的，除非不想支持头文件依赖编译，这个是必须的功能

但是要支持这个，必须在编译的同时，加上 -H 参数，生成对应的依赖头文件列表，然后xmake提取解析后，用于头文件依赖检测。。

但是gcc -H生成的头文件列表信息跟编译信息都是混在stdout里面的，没法独立区分，所以要启用-H编译，最后的编译输出会有大量  include xxx file的信息，xmake是必须要过滤掉的，否则编译错误根本没法看，会大量刷屏。

之前试过 使用-MM来获取依赖头文件信息，这个确实不会跟编译错误混在一起，但是需要额外多一次的预编译过程，严重影响编译效率，并且低版本gcc也不支持。

windows/msvc下，也是同样的问题，需要加`-showIncludes`同时获取和解析include依赖，以及输出过滤。

目前没有更好的解决办法，除非彻底禁用头文件依赖编译，这样每次改代码，你只能rebuild整个项目代码了。。

如果你能解决不加-H，也不用-MM也能获取到依赖头文件信息，或者有更好版本区分编译错误信息和include list信息，那我很乐意不去过滤它。

现在这样已经算是比较好的方式，毕竟比起彻底禁用头文件依赖编译导致用户每次重编的麻烦程度，现在只有极少情况，才会出现一次过滤错误信息丢失问题，还是可以接受的。

更何况过滤算法，我会不断改进优化。

**Comment by Ultraman95** [comment]
听你的意思是，你使用了gcc -H这个命令，但是这个命令生成的头文件列表信息跟编译信息是混在一起的，然后你过滤了大量 include xxx file的信息，是吗？

**Comment by Ultraman95** [comment]
我理解是这样的，支持头文件依赖编译这个功能是必须要有的，所以就必须使用GCC -H编译，但是使用这个命令编译，会使得头文件列表信息跟编译信息是混在一起的，如何过滤这个混在一起的信息比较困难，最理性的当然是能将混在一起的信息中的编译错误能抽取出来，是吗？

**Comment by waruqi** [comment]
> 我理解是这样的，支持头文件依赖编译这个功能是必须要有的，所以就必须使用GCC -H编译，但是使用这个命令编译，会使得头文件列表信息跟编译信息是混在一起的，如何过滤这个混在一起的信息比较困难，最理性的当然是能将混在一起的信息中的编译错误能抽取出来，是吗？

我目前就是这么做的，你现在遇到的错误信息丢失问题，就是抽取过程中，部分lines没成功抽出来，所以丢失了一些

这块目前只能想想办法，根据你遇到的抽取失败case，对抽取算法做些改进

**Comment by waruqi** [comment]
这块我最近研究了下，应该可以通过 -MM -MF depfile.d 来将头文件依赖信息独立输出到单独的文件中去，来解决这个问题，如果低版本gcc不支持这些flags 那么会自动退化到现有的处理方式。。

后两天我会尝试改进下看看。

**Comment by waruqi** [comment]
我dev分支上改进过了，采用`-MMD -MF depfile.d `的方式来隔离编译输出和头文件依赖输出，现在不会过滤错误信息了，你再试试
