### ISSUE TITLE
在openSUSE上识别不到系统Qt5框架

### ISSUE THREAD

**Issue by iphelf** [xmake-io/xmake#3851]
### Xmake 版本

2.7.9

### 操作系统版本和架构

openSUSE Tumbleweed

### 描述问题

目前，在openSUSE上用`xmake`编译Qt5程序时会报错，提示找不到本地安装的Qt5框架。

```
checking for Qt SDK directory ... no
error: Qt SDK not found!
```

原因在于，openSUSE发行版上Qt5框架的qmake可执行程序其实叫做`qmake-qt5`（本来的`qmake`已经被Qt4版的占用了），而`xmake`似乎并没有实现相关的逻辑支持查找这样不太寻常命名的qmake。

### 期待的结果

简单粗暴的方法是，在`xmake`的默认行为中加入候选逻辑，当`qmake`没找到时，尝试找`qmake-qt5`。
我自己已经实现了这个方法，参见这个[commit](https://github.com/iphelf/xmake/commit/0be5f096df3d2f6e3ef8a6799015e7624598816b)，经自测可用。

要是上述这种方法OK，那么我就来发PR。要是不合适，请告诉我正确的方法。

**Comment by waruqi** [comment]
可以提个 pr 过来
