### ISSUE TITLE
Unable to compile example headerunits_person 

### ISSUE THREAD

**Issue by brano543** [xmake-io/xmake#3853]
### Xmake Version

2.7.9

### Operating System Version and Architecture

Ubuntu 22.04.2 LTS

### Describe Bug

While trying to compile example https://github.com/xmake-io/xmake/tree/master/tests/projects/c%2B%2B/modules/headerunits_person by running commands I receive error "error: fatal error: module header file 'string' not found". I am using Nix as dependency manager.

xmake clean --all
xmake f -p linux --toolchain=clang -c
xmake -vD

```
[0%]: generating.module.deps src/main.cpp
checkinfo: cannot runv(/nix/store/j72jba4hij4kv46pnf7rw76jal2rj283-clang-wrapper-16.0.1/bin/clang-scan-deps --version), No such file or directory
checking for /nix/store/j72jba4hij4kv46pnf7rw76jal2rj283-clang-wrapper-16.0.1/bin/clang-scan-deps ... no
checking for flags (-fvisibility-inlines-hidden) ... ok
> clang "-fvisibility-inlines-hidden" "-Qunused-arguments" "-m64"
checking for flags (-O3) ... ok
> clang "-O3" "-Qunused-arguments" "-m64"
checking for flags (-std=c++20) ... ok
> clang "-std=c++20" "-Qunused-arguments" "-m64"
checking for flags (-DNDEBUG) ... ok
> clang "-DNDEBUG" "-Qunused-arguments" "-m64"
/nix/store/j72jba4hij4kv46pnf7rw76jal2rj283-clang-wrapper-16.0.1/bin/clang -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG -E -x c++ src/main.cpp -o build/.gens/headerunits_person/linux/x86_64/release/rules/modules/cache/0d20b8c9/main.cpp.i
[  0%]: generating.module.deps src/Person.mpp
/nix/store/j72jba4hij4kv46pnf7rw76jal2rj283-clang-wrapper-16.0.1/bin/clang -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG -E -x c++ src/Person.mpp -o build/.gens/headerunits_person/linux/x86_64/release/rules/modules/cache/0d20b8c9/Person.mpp.i
checking for flags (clang_modules_cache_path) ... ok
> clang "-fmodules-cache-path=/tmp/.xmake1000/230616" "-Qunused-arguments" "-m64"
checking for flags (clang_user_header_unit_support) ... ok
> clang "-std=c++20" "-x" "c++-user-header" "-Qunused-arguments" "-m64"
checking for flags (clang_system_header_unit_support) ... ok
> clang "-std=c++20" "-x" "c++-system-header" "-Qunused-arguments" "-m64"
[ 10%]: compiling.headerunit.release iostream
/nix/store/j72jba4hij4kv46pnf7rw76jal2rj283-clang-wrapper-16.0.1/bin/clang -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++20 -DNDEBUG -fmodules-cache-path=build/stlmodules/cache/release -c -Wno-everything -o build/stlmodules/cache/release/iostream.pcm -x c++-system-header iostream
[ 10%]: compiling.headerunit.release string
/nix/store/j72jba4hij4kv46pnf7rw76jal2rj283-clang-wrapper-16.0.1/bin/clang -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++20 -DNDEBUG -fmodules-cache-path=build/stlmodules/cache/release -c -Wno-everything -o build/stlmodules/cache/release/string.pcm -x c++-system-header string
fatal error: fatal error: module header file 'iostream' not foundmodule header file 'string' not found

1 error1 generated error.
 generated.
error: @programdir/modules/private/async/runjobs.lua:256: @programdir/core/sandbox/modules/os.lua:378: execv(/nix/store/j72jba4hij4kv46pnf7rw76jal2rj283-clang-wrapper-16.0.1/bin/clang -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++20 -DNDEBUG -fmodules-cache-path=build/stlmodules/cache/release -c -Wno-everything -o build/stlmodules/cache/release/iostream.pcm -x c++-system-header iostream) failed(1)
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:913]:
    [@programdir/core/sandbox/modules/os.lua:378]:
    [@programdir/core/sandbox/modules/os.lua:291]: in function 'vrunv'
    [@programdir/rules/c++/modules/modules_support/clang.lua:409]: in function 'callback'
    [@programdir/modules/core/project/depend.lua:193]: in function 'on_changed'
    [@programdir/rules/c++/modules/modules_support/clang.lua:403]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:232]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:913: in function 'os.raiselevel'
        (...tail calls...)
        @programdir/modules/private/async/runjobs.lua:256: in field 'catch'
        @programdir/core/sandbox/modules/try.lua:123: in global 'try'
        @programdir/modules/private/async/runjobs.lua:218: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>
```

### Expected Behavior

Example should compile.

**Comment by waruqi** [comment]
@Arthapz Any idea?

**Comment by waruqi** [comment]
> /nix/store/j72jba4hij4kv46pnf7rw76jal2rj283-clang-wrapper-16.0.1/bin/clang-scan-deps no

Perhaps clang-scan-deps is missing to get the exact dependency map for iostream string, which causes iostream string to be compiled in the wrong order. iostream is compiled before string, so the string headerunit is not found.

You can try rebuild llvm and enable clang-scan-deps

**Comment by Arthapz** [comment]
> > /nix/store/j72jba4hij4kv46pnf7rw76jal2rj283-clang-wrapper-16.0.1/bin/clang-scan-deps no
> 
> 
> 
> Perhaps clang-scan-deps is missing to get the exact dependency graph for headerunits (iostream string), which causes iostream and string to be compiled in the wrong order. iostream is compiled before string, so the string headerunit is not found.
> 
> 
> 
> You can try rebuild llvm and enable clang-scan-deps

Yes clang-scan-deps does not support header units atm

**Comment by brano543** [comment]
So the problem is that even if it could find clang-scan-deps, it wouldn't have compiled?

Could you please provide an example on how we might use the c++ modules as of today? For gcc I was missing some special flag, it wouldn't compile.

**Comment by waruqi** [comment]
You can try other some examples without headerunit if you use clang.

https://github.com/xmake-io/xmake/tree/master/tests/projects/c%2B%2B/modules

**Comment by Arthapz** [comment]
> So the problem is that even if it could find clang-scan-deps, it wouldn't have compiled?
> 
> 
> 
> Could you please provide an example on how we might use the c++ modules as of today? For gcc I was missing some special flag, it wouldn't compile.
> 
> 

It would build with one or two stl include imported, but more Will lead to ICE (Internal Compiler Error) or just bugged error

**Comment by brano543** [comment]
Hello, after some tweaking in Nix, I was able to build one example. I believe this way would work in general assuming all standard library headers are included.

I am now facing issue with generating compile_commands.json. Whenever I generate it, it only shows output for main.cpp and not for foo.mpp.

Could you please advise?

main.cpp
```
#include <iostream>
import foo;

int main()
{
	int i = 5 + 8;
	std::cout << "Test " << i << std::endl;
	foo f;
	f.helloworld();
	return 0;
}
```
foo.mpp
```
module;
#include <iostream>

export module foo;

export class foo
{
  public:
	foo();
	~foo();
	void helloworld();
};

foo::foo() = default;
foo::~foo() = default;
void foo::helloworld()
{ //
	std::cout << "hello world\n";
}

```
xmake.lua
```
add_rules("mode.release", "mode.debug")
set_languages("c++20")

add_requires("pkgconfig::fmt", {system = true})

target("hello")
    set_kind("binary")
    add_files("src/main.cpp", "src/foo.mpp")
```
Build output
```
xmake clean --all
pandora@pandora-MS-7B17:/app/cpp_training_flakes$ xmake f -p linux --toolchain=clang --includedirs=/nix/store/i29k9pvl90385mpsavifqvm4rag684dn-glibc-2.37-8-dev/include:/nix/store/2vwipws2crqcjxfzjyq9rjpk61iqf7pf-gcc-12.3.0/include/c++/12.3.0:/nix/store/2vwipws2crqcjxfzjyq9rjpk61iqf7pf-gcc-12.3.0/include/c++/12.3.0/x86_64-unknown-linux-gnu:/nix/store/1pv5xljgx41ldwrczibw3v0gz7w095jv-clang-wrapper-16.0.1/resource-root/include -c
checking for architecture ... x86_64
pandora@pandora-MS-7B17:/app/cpp_training_flakes$ xmake
[  0%]: generating.module.deps src/main.cpp
[  0%]: generating.module.deps src/foo.mpp
[ 14%]: compiling.module.release foo
[ 57%]: compiling.release src/main.cpp
[ 71%]: linking.release hello
[100%]: build ok, spent 1,59s
```
Resulting compile_commands.json
```
[
{
  "directory": "/app/cpp_training_flakes",
  "arguments": ["/nix/store/70d4by83v5r5z7sphrngjwwd1xz7ypkj-devenv/bin/clang", "-c", "-Qunused-arguments", "-m64", "-I/nix/store/i29k9pvl90385mpsavifqvm4rag684dn-glibc-2.37-8-dev/include", "-I/nix/store/2vwipws2crqcjxfzjyq9rjpk61iqf7pf-gcc-12.3.0/include/c++/12.3.0", "-I/nix/store/2vwipws2crqcjxfzjyq9rjpk61iqf7pf-gcc-12.3.0/include/c++/12.3.0/x86_64-unknown-linux-gnu", "-I/nix/store/1pv5xljgx41ldwrczibw3v0gz7w095jv-clang-wrapper-16.0.1/resource-root/include", "-fvisibility=hidden", "-fvisibility-inlines-hidden", "-O3", "-std=c++20", "-DNDEBUG", "-fmodule-file=foo=build/.gens/hello/linux/x86_64/release/rules/modules/cache/c83caa2b/foo.pcm", "-o", "build/.objs/hello/linux/x86_64/release/src/main.cpp.o", "src/main.cpp"],
  "file": "src/main.cpp"
}]

```

**Comment by waruqi** [comment]
> Hello, after some tweaking in Nix, I was able to build one example. I believe this way would work in general assuming all standard library headers are included.
> 
> I am now facing issue with generating compile_commands.json. Whenever I generate it, it only shows output for main.cpp and not for foo.mpp.
> 
> Could you please advise?
> 
> main.cpp
> 
> ```
> #include <iostream>
> import foo;
> 
> int main()
> {
> 	int i = 5 + 8;
> 	std::cout << "Test " << i << std::endl;
> 	foo f;
> 	f.helloworld();
> 	return 0;
> }
> ```
> 
> foo.mpp
> 
> ```
> module;
> #include <iostream>
> 
> export module foo;
> 
> export class foo
> {
>   public:
> 	foo();
> 	~foo();
> 	void helloworld();
> };
> 
> foo::foo() = default;
> foo::~foo() = default;
> void foo::helloworld()
> { //
> 	std::cout << "hello world\n";
> }
> ```
> 
> xmake.lua
> 
> ```
> add_rules("mode.release", "mode.debug")
> set_languages("c++20")
> 
> add_requires("pkgconfig::fmt", {system = true})
> 
> target("hello")
>     set_kind("binary")
>     add_files("src/main.cpp", "src/foo.mpp")
> ```
> 
> Build output
> 
> ```
> xmake clean --all
> pandora@pandora-MS-7B17:/app/cpp_training_flakes$ xmake f -p linux --toolchain=clang --includedirs=/nix/store/i29k9pvl90385mpsavifqvm4rag684dn-glibc-2.37-8-dev/include:/nix/store/2vwipws2crqcjxfzjyq9rjpk61iqf7pf-gcc-12.3.0/include/c++/12.3.0:/nix/store/2vwipws2crqcjxfzjyq9rjpk61iqf7pf-gcc-12.3.0/include/c++/12.3.0/x86_64-unknown-linux-gnu:/nix/store/1pv5xljgx41ldwrczibw3v0gz7w095jv-clang-wrapper-16.0.1/resource-root/include -c
> checking for architecture ... x86_64
> pandora@pandora-MS-7B17:/app/cpp_training_flakes$ xmake
> [  0%]: generating.module.deps src/main.cpp
> [  0%]: generating.module.deps src/foo.mpp
> [ 14%]: compiling.module.release foo
> [ 57%]: compiling.release src/main.cpp
> [ 71%]: linking.release hello
> [100%]: build ok, spent 1,59s
> ```
> 
> Resulting compile_commands.json
> 
> ```
> [
> {
>   "directory": "/app/cpp_training_flakes",
>   "arguments": ["/nix/store/70d4by83v5r5z7sphrngjwwd1xz7ypkj-devenv/bin/clang", "-c", "-Qunused-arguments", "-m64", "-I/nix/store/i29k9pvl90385mpsavifqvm4rag684dn-glibc-2.37-8-dev/include", "-I/nix/store/2vwipws2crqcjxfzjyq9rjpk61iqf7pf-gcc-12.3.0/include/c++/12.3.0", "-I/nix/store/2vwipws2crqcjxfzjyq9rjpk61iqf7pf-gcc-12.3.0/include/c++/12.3.0/x86_64-unknown-linux-gnu", "-I/nix/store/1pv5xljgx41ldwrczibw3v0gz7w095jv-clang-wrapper-16.0.1/resource-root/include", "-fvisibility=hidden", "-fvisibility-inlines-hidden", "-O3", "-std=c++20", "-DNDEBUG", "-fmodule-file=foo=build/.gens/hello/linux/x86_64/release/rules/modules/cache/c83caa2b/foo.pcm", "-o", "build/.objs/hello/linux/x86_64/release/src/main.cpp.o", "src/main.cpp"],
>   "file": "src/main.cpp"
> }]
> ```

It's another issue, you should open a new issue.

mpp will not be added into compile_commands.json, only `-fmodule-file=xxx.pcm` will be added into main.cpp.

https://github.com/xmake-io/xmake/issues/3857
