### ISSUE TITLE
C++ modules support

### ISSUE THREAD

**Issue by mathstuf** [xmake-io/xmake#386]
Hi there, I'm a CMake developer and am working on C++20 modules support in build systems across the board. I was wondering how you were planning on supporting it. I have [a repository](https://github.com/mathstuf/cxx-modules-sandbox/) which contains "interesting" corner cases for build systems. I'd welcome adding `xmake` support to it when modules are supported. Resources:

  - [Overview of CMake's strategy](https://mathstuf.fedorapeople.org/fortran-modules/fortran-modules.html)
  - Dependency output format for use with build tools: [start of thread](http://www.open-std.org/pipermail/tooling/2019-March/000609.html), [continued](http://www.open-std.org/pipermail/tooling/2019-April/000622.html), and [continued](http://www.open-std.org/pipermail/tooling/2019-April/000629.html)
  - [Docker image](https://hub.docker.com/r/benboeckel/cxx-modules-sandbox) with a setup for using modules

If you have any questions, feel free to ask.

**Comment by waruqi** [comment]
Hello, thank you very much for your information, I will plan to support c++20 modules in the new version later.
When I start to implement it, I will discuss the specific implementation with you.

**Comment by waruqi** [comment]
@mathstuf 

I have implemented c++modules support for clang and msvc. Because there is no gcc toolchains with c++modules yet, it has not been implemented yet.

@see https://github.com/xmake-io/xmake/pull/569
