### ISSUE TITLE
xrepo info xxx的时候可以标注readonly的配置

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#3861]
### 你在什么场景下需要该功能？

之前提过一个类似的issue，在修改readonly配置的时候会提示 
https://github.com/xmake-io/xmake/issues/3829

但是在xrepo info查看包详情的时候就能够看到哪些配置是只读的更好
比如下面这个包，只看输出是看不出哪些config是只读，不方便
必须去看包的脚本源码
![image](https://github.com/xmake-io/xmake/assets/97490782/21728d67-8e36-40cc-a84c-e7ab6b10f57c)

### 描述可能的解决方案

在 xrepo info xxx 的输出中标注哪些config是readonly的，可以加在default的那个括号里面

**Comment by waruqi** [comment]
这种小改动，可以直接提个 pr 过来
