### ISSUE TITLE
vsmake生成vs工程项目的时候丢失了PlatformToolset

### ISSUE THREAD

**Issue by Waitforomething2023** [xmake-io/xmake#3867]
### Xmake 版本

xmake v2.7.9+master.2082781e0

### 操作系统版本和架构

windows 10 21H2

### 描述问题

如题，生成vs工程的时候丢失了<PlatformToolset>这个属性，我在vs201x_vcxproj.lua中看到似乎有生成这个属性值的方法，但是最终生成的工程中缺少了这个属性

### 期待的结果

在vs工程中正确生成PlatformToolset属性

### 工程配置

add_rules("plugin.vsxmake.autoupdate")
add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})

add_rules("mode.debug", "mode.release")

set_languages("c11","cxx20")
set_defaultplat("clang-cl")

target("test")
    set_kind("binary")
    add_files("src/*.cpp")
    set_plat("windows")
    set_toolchains("clang-cl")

### 附加信息和错误日志

```log

G:\MapProject\Repo2\test>xmake project -k vsxmake2022 -m "debug,release" -vD
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for zig ... ok
checking for clang-cl.exe ... C:\Program Files\LLVM\bin\clang-cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for LLVM Clang C/C++ Compiler (x64) version ... 16.0.1
checking for link.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\link.exe
checking for the linker (ld) ... link.exe
configure
{
    vs = 2022
    mode = release
    host = windows
    arch = x64
    ccache = true
    buildir = build
    ndk_stdcxx = true
    kind = static
    plat = windows
}
using project kind vs2022
checking for debug.x64 ...
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for zig ... ok
checkinfo: cannot runv(link.exe -lib -out:C:\Users\LUCIOU~1\AppData\Local\Temp\.xmake\230620\_D025B9FE166943708C588FD88B7902B0.exe C:\Users\LUCIOU~1\AppData\Local\Temp\.xmake\230620\_DFA62369F5B44F70882168742C451390.obj), No such file or directory
checking for link.exe ... no
checking for the linker (ld: link.exe) ... no
checking for link.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\link.exe
checking for the linker (ld) ... link.exe
checking for release.x64 ...
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for zig ... ok
checkinfo: cannot runv(link.exe -lib -out:C:\Users\LUCIOU~1\AppData\Local\Temp\.xmake\230620\_003C8C6A55E946008D640007785EEC50.exe C:\Users\LUCIOU~1\AppData\Local\Temp\.xmake\230620\_4B6135E395DF4C708BD8573B568124F0.obj), No such file or directory
checking for link.exe ... no
checking for the linker (ld: link.exe) ... no
skipped file vsxmake2022\test.sln since the file has the same content
skipped file vsxmake2022\Xmake.Custom.props since the file already exists
skipped file vsxmake2022\Xmake.Custom.targets since the file already exists
skipped file vsxmake2022\test\test.vcxproj since the file has the same content
skipped file vsxmake2022\test\test.vcxproj.filters since the file has the same content
skipped file vsxmake2022\test\Xmake.Custom.props since the file already exists
skipped file vsxmake2022\test\Xmake.Custom.targets since the file already exists
skipped file vsxmake2022\test\Xmake.Custom.items since the file already exists
skipped file vsxmake2022\test\Xmake.Custom.items.filters since the file already exists
create ok!
```

**Comment by Waitforomething2023** [comment]
补张截图
![bug](https://github.com/xmake-io/xmake/assets/10268785/6d176f6c-4ef9-4c8d-b503-0fe84b641859)

**Comment by waruqi** [comment]
> 如题，生成vs工程的时候丢失了这个属性，我在vs201x_vcxproj.lua中看到似乎有生成这个属性值的方法，但是最终生成的工程中缺少了这个属性

那是 vs 生成器，`xmake project -k vs` ，而你用的是 vsxmake 生成器，不一样。。

vsxmake 生成的 vs 工程只是个壳，实际编译还是走的 xmake 命令，所以 vs 内部大部分参数都是不用设置的，不影响编译。。部分影响 intellisense 的，比如 defines, cflags includedirs 都已经设置进去了。。

**Comment by Waitforomething2023** [comment]
> > 如题，生成vs工程的时候丢失了这个属性，我在vs201x_vcxproj.lua中看到似乎有生成这个属性值的方法，但是最终生成的工程中缺少了这个属性
> 
> 那是 vs 生成器，`xmake project -k vs` ，而你用的是 vsxmake 生成器，不一样。。
> 
> vsxmake 生成的 vs 工程只是个壳，实际编译还是走的 xmake 命令，所以 vs 内部大部分参数都是不用设置的，不影响编译。。部分影响 intellisense 的，比如 defines, cflags includedirs 都已经设置进去了。。

PlatformToolset是影响intellisense的，至少对于clang-cl来说，如果不显式设置平台工具集为clang-cl，那么clang的语法就不被vs的intellisense识别，比如：
![clang-1](https://github.com/xmake-io/xmake/assets/10268785/1a980f15-17ba-42e1-bf40-692b5630bb04)
第二张图是设置了clang-cl的：
![clang2](https://github.com/xmake-io/xmake/assets/10268785/e66c7378-cbe6-4c9a-8e17-ff8cdf5d6a4e)

**Comment by waruqi** [comment]
vsxmake 的生成器，也有设置这个，全局设置了。。

https://github.com/xmake-io/xmake/blob/b1412a18df8f507db138bbe8bfb1ec44d3b5c62c/xmake/plugins/project/vsxmake/vsproj/Xmake.props#L54

**Comment by Waitforomething2023** [comment]
> vsxmake 的生成器，也有设置这个，全局设置了。。
> 
> https://github.com/xmake-io/xmake/blob/b1412a18df8f507db138bbe8bfb1ec44d3b5c62c/xmake/plugins/project/vsxmake/vsproj/Xmake.props#L54

好像没起效，我搜了props里面没有这个属性

**Comment by Waitforomething2023** [comment]
看了一下这个文件，clang-cl的工具集名称叫"ClangCL"，应该是没加进去

**Comment by waruqi** [comment]
> > vsxmake 的生成器，也有设置这个，全局设置了。。
> > https://github.com/xmake-io/xmake/blob/b1412a18df8f507db138bbe8bfb1ec44d3b5c62c/xmake/plugins/project/vsxmake/vsproj/Xmake.props#L54
> 
> 好像没起效，我搜了props里面没有这个属性

全局的，在 xmake 安装目录里面，生成的本地工程会 include 这个进来，不在自己工程里，但是所有工程都会全局生效的 应该

**Comment by waruqi** [comment]
不过 有可能 getinfo 里面没设置进去，所以值没取到

**Comment by Waitforomething2023** [comment]
> 不过 有可能 getinfo 里面没设置进去，所以值没取到
这里
···xml
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '10.0'">v100</PlatformToolset>
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '11.0'">v110</PlatformToolset>
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '12.0'">v120</PlatformToolset>
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '14.0'">v140</PlatformToolset>
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '15.0'">v141</PlatformToolset>
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '16.0'">v142</PlatformToolset>
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '17.0'">v143</PlatformToolset>
```
在使用clang-cl的时候应该是没法通过只通过$(VisualStudioVersion)来判断是否开启clang-cl的还有一个叫$(UseClangCl)的宏，为true的时候就设置PlatformToolset 为ClangCL

**Comment by waruqi** [comment]
这个就是我之前说的了，vsxmake 仅用于 msvc ，clang 系从没支持过，你可以提 pr 过来。

**Comment by Waitforomething2023** [comment]
> 这个就是我之前说的了，vsxmake 仅用于 msvc ，clang 系从没支持过，你可以提 pr 过来。

好，这部分我改一下，包括wasm那个也这么设置应该能跑起来了

**Comment by Waitforomething2023** [comment]
> 这个就是我之前说的了，vsxmake 仅用于 msvc ，clang 系从没支持过，你可以提 pr 过来。

我改过能跑了，但是写法非常不优雅，不知道能不能pr过来

**Comment by waruqi** [comment]
可以弄得稍微优雅点，再提过来。

**Comment by Waitforomething2023** [comment]
> 可以弄得稍微优雅点，再提过来。

需要大佬的建议，我对xmake的代码完全不了解，就是看着硬改的，您看看。我觉得应该有比较优雅的写法。

**Comment by waruqi** [comment]
确实很 hack ，要么你试试自己配置下 Xmake.Custom.props (生成在你的工程里的），自己直接加上

```
    <PlatformToolset>ClangCL</PlatformToolset>
```

https://github.com/xmake-io/xmake/blob/master/xmake/plugins/project/vsxmake/vsproj/templates/Xmake.Custom.props

也就啥也不用改了，目前的 patch 肯定没法 merge 进来的。

**Comment by Waitforomething2023** [comment]
> 确实很 hack ，要么你试试自己配置下 Xmake.Custom.props (生成在你的工程里的），自己直接加上
> 
> 
> 
> ```
> 
>     <PlatformToolset>ClangCL</PlatformToolset>
> 
> ```
> 
> 
> 
> https://github.com/xmake-io/xmake/blob/master/xmake/plugins/project/vsxmake/vsproj/templates/Xmake.Custom.props
> 
> 
> 
> 也就啥也不用改了，目前的 patch 肯定没法 merge 进来的。

主要是只加这个是没有用的，因为vs不支持wasm平台也没有wasm32这个架构，必须要给他一个合法的名字才能骗它给出正常的配置选项，否则即使加了这个选项也会报找不到工具集。目前也没有什么比较优雅的方法，伤脑筋。

**Comment by waruqi** [comment]
> > 确实很 hack ，要么你试试自己配置下 Xmake.Custom.props (生成在你的工程里的），自己直接加上
> > ```
> > 
> >     <PlatformToolset>ClangCL</PlatformToolset>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://github.com/xmake-io/xmake/blob/master/xmake/plugins/project/vsxmake/vsproj/templates/Xmake.Custom.props
> > 也就啥也不用改了，目前的 patch 肯定没法 merge 进来的。
> 
> 主要是只加这个是没有用的，因为vs不支持wasm平台也没有wasm32这个架构，必须要给他一个合法的名字才能骗它给出正常的配置选项，否则即使加了这个选项也会报找不到工具集。目前也没有什么比较优雅的方法，伤脑筋。

我是说 不切 wasm ，直接正常 windows平台生成后，改我说的那里，你的 patch 我看不也只有这些改动么

**Comment by Waitforomething2023** [comment]
> > > 确实很 hack ，要么你试试自己配置下 Xmake.Custom.props (生成在你的工程里的），自己直接加上
> > > ```
> > > 
> > >     <PlatformToolset>ClangCL</PlatformToolset>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > https://github.com/xmake-io/xmake/blob/master/xmake/plugins/project/vsxmake/vsproj/templates/Xmake.Custom.props
> > > 也就啥也不用改了，目前的 patch 肯定没法 merge 进来的。
> > 
> > 
> > 主要是只加这个是没有用的，因为vs不支持wasm平台也没有wasm32这个架构，必须要给他一个合法的名字才能骗它给出正常的配置选项，否则即使加了这个选项也会报找不到工具集。目前也没有什么比较优雅的方法，伤脑筋。
> 
> 我是说 不切 wasm ，直接正常 windows平台生成后，改我说的那里，你的 patch 我看不也只有这些改动么
> 
> wasm 平台编译，在 custom.targets 里面也能追加 -p wasm 在生成后切的

明白了

**Comment by waruqi** [comment]
而且，生成的 vsxmake 工程，你可以打开属性设置，有个专门的 xmake 属性页，应该也能配置 -p wasm

**Comment by waruqi** [comment]
![image](https://github.com/xmake-io/xmake/assets/151335/304534f4-2bf5-4802-a0b8-f0d737002249)

![image](https://github.com/xmake-io/xmake/assets/151335/8ddc53a8-248b-4f26-9ea6-5105ff8fc304)

这里

**Comment by Waitforomething2023** [comment]
> ![image](https://user-images.githubusercontent.com/151335/247367553-304534f4-2bf5-4802-a0b8-f0d737002249.png)
> 
> ![image](https://user-images.githubusercontent.com/151335/247367640-8ddc53a8-248b-4f26-9ea6-5105ff8fc304.png)
> 
> 这里
我试一下，如果每次自动更新vs项目不覆盖Xmake.Custom.props的话，这个做法应该是最好的

**Comment by waruqi** [comment]
> 我试一下，如果每次自动更新vs项目不覆盖Xmake.Custom.props的话，这个做法应该是最好的

不会覆盖，原本就是用于给用户自定义配置的，覆盖了，不就等于没法保存配置了么

**Comment by waruqi** [comment]
如果没啥问题了，这里我关了
