### ISSUE TITLE
--build 和 --host 无法正确解析携有 vendor 或 env 信息的 triplet

### ISSUE THREAD

**Issue by mochaaP** [xmake-io/xmake#3869]
### Xmake 版本

2.7.9

### 操作系统版本和架构

Fedora Linux 39 (rawhide)

### 描述问题

Linux 下對於非 debian 形式（`<arch>-<os>-<env>`）或帶有額外信息的 triplet 的解析有問題：

完整的 triplet 形式實際上是 `<arch><subarch>-<vendor>-<os>-<env>`，
但是就[解析的結果](https://github.com/xmake-io/xmake/blob/master/configure?plain=1#L2761) 來看解析出來的參數有誤，導致在 Redhat 系發行版上 rpm `%configure` 之後會把 `os` 辨識成 `x86_64`（。。？）

具體必要的數據結構可以參考 <https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/TargetParser/Triple.h>。

### 期待的结果

參考 LLVM 的行為：
- <https://github.com/llvm/llvm-project/blob/main/llvm/lib/TargetParser/Triple.cpp>
- <https://github.com/llvm/llvm-project/tree/main/clang/lib/Driver/ToolChains>

### 附加信息和错误日志

完整格式 (clang -dumpmachine):
- `i686-redhat-linux-gnu` (RHEL, x86)
- `aarch64-alpine-linux-musl` (Alpine, arm64)
- `x86_64-pc-linux-gnu` (Debian, x64)
- `aarch64-unknown-linux-android24` (Termux on Android 13, arm64)

對應的 `gcc -dumpmachine` 輸出：
- `i686-redhat-linux`
- `aarch64-alpine-linux-musl` (非常奇怪的用了完整的格式)
- `x86_64-linux-gnu`
- ~~無 GCC Toolchain~~

**Comment by waruqi** [comment]
改进过了，再试试

**Comment by mochaaP** [comment]
行了，同步一下更改到 tbox 吧

**Comment by waruqi** [comment]
> 行了，同步一下更改到 tbox 吧

刚就是同步改的。

**Comment by mochaaP** [comment]
那 v2.8.1 的時候 xmake.spec 記得改一下 `scripts/rpmbuild/xmake.spec`

```diff
diff --git a/scripts/rpmbuild/xmake.spec b/scripts/rpmbuild/xmake.spec
index dd4f3b1af..607657767 100644
--- a/scripts/rpmbuild/xmake.spec
+++ b/scripts/rpmbuild/xmake.spec
@@ -52,12 +52,7 @@ system to help users solve the integrated use of C/C++ dependent libraries.
 rm -rf core/src/{lua,luajit,lua-cjson,lz4,pdcurses}/*/
 
 %build
-%set_build_flags
-./configure --external=yes \
-  --prefix=%{_prefix} \
-  --bindir=%{_bindir} \
-  --libdir=%{_libdir} \
-  --includedir=%{_includedir} \
+%configure --external=yes \
 %if %{use_luajit}
   --runtime=luajit
 %else
```

**Comment by waruqi** [comment]
我可能会忘，到时候你提个 pr 过来就好了，或者现在提前提 pr 改好
