### ISSUE TITLE
ChatGpt support

### ISSUE THREAD

**Issue by xzzh999** [xmake-io/xmake#3872]
### Is your feature request related to a problem? Please describe.

fisrt, thanks to u guys doing the greate work!

i suggest: 
xmake have so many parameters for developers to remeber or research,  is there any plans for chatgpt integrated ?

### Describe the solution you'd like

with chatgpt sdk, i can just write normal words to generate or build the project

**Comment by waruqi** [comment]
I wouldn't consider it for now
