### ISSUE TITLE
cmake不应使用系统默认的工具链

### ISSUE THREAD

**Issue by 24bit-xjkp** [xmake-io/xmake#3878]
### Xmake 版本

v2.7.9+dev.8b9228762

### 操作系统版本和架构

Windows11 21H2

### 描述问题

在构建包时，xmake已经将工具链设置成了gcc
```
in xmake-repo:
  -> benchmark 1.8.0 [toolchains:"gcc", vs_runtime:"MT", shared:n]
```
但编译的时候用的是msvc
```
-- Check for working CXX compiler: D:/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe
```
那编译出来的库肯定用不了，会产生链接错误。

### 期待的结果

使用设置的工具链去编译依赖库，而不是用平台默认的。
建议将ninja设置为默认，因为ninja支持多个平台并且轻量而快速。相较于Windows下的msbuild，ninja的效果会更好。

### 附加信息和错误日志

```
> g++ -o C:\Users\22835\AppData\Local\Temp\.xmake\230622\_2C71A5DB5AD14F2081A38BC034C61A90.b C:\Users\22835\AppData\Local\Temp\.xmake\230622\_2C71A5DB5AD14F2081A38BC034C61A90.o -m64 -LC:\Users\22835\AppData\Local\.xmake\packages\b\benchmark\1.8.0\15d21182b5c34f69adcf4c498c0aaf92\lib -lbenchmark_main -lbenchmark -lshlwapi
D:/gcc/bin/../lib/gcc/x86_64-w64-mingw32/13.1.1/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\22835\AppData\Local\Temp\.xmake\230622\_2C71A5DB5AD14F2081A38BC034C61A90.o:_CD0CDFD16296488DBA3A516F729ED0EC.cpp:(.text+0x61): undefined reference to `benchmark::State::StartKeepRunning()'
D:/gcc/bin/../lib/gcc/x86_64-w64-mingw32/13.1.1/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\22835\AppData\Local\Temp\.xmake\230622\_2C71A5DB5AD14F2081A38BC034C61A90.o:_CD0CDFD16296488DBA3A516F729ED0EC.cpp:(.text+0x11d): undefined reference to `benchmark::State::FinishKeepRunning()'
D:/gcc/bin/../lib/gcc/x86_64-w64-mingw32/13.1.1/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\22835\AppData\Local\Temp\.xmake\230622\_2C71A5DB5AD14F2081A38BC034C61A90.o:_CD0CDFD16296488DBA3A516F729ED0EC.cpp:(.text+0x169): undefined reference to `benchmark::internal::InitializeStreams()'
D:/gcc/bin/../lib/gcc/x86_64-w64-mingw32/13.1.1/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\22835\AppData\Local\Temp\.xmake\230622\_2C71A5DB5AD14F2081A38BC034C61A90.o:_CD0CDFD16296488DBA3A516F729ED0EC.cpp:(.text+0x1c8): undefined reference to `benchmark::internal::RegisterBenchmarkInternal(benchmark::internal::Benchmark*)'
D:/gcc/bin/../lib/gcc/x86_64-w64-mingw32/13.1.1/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\22835\AppData\Local\Temp\.xmake\230622\_2C71A5DB5AD14F2081A38BC034C61A90.o:_CD0CDFD16296488DBA3A516F729ED0EC.cpp:(.text+0x241): undefined reference to `benchmark::internal::RegisterBenchmarkInternal(benchmark::internal::Benchmark*)'
D:/gcc/bin/../lib/gcc/x86_64-w64-mingw32/13.1.1/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\22835\AppData\Local\Temp\.xmake\230622\_2C71A5DB5AD14F2081A38BC034C61A90.o:_CD0CDFD16296488DBA3A516F729ED0EC.cpp:(.text+0x249): undefined reference to `benchmark::internal::Benchmark::ThreadPerCpu()'
D:/gcc/bin/../lib/gcc/x86_64-w64-mingw32/13.1.1/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\22835\AppData\Local\Temp\.xmake\230622\_2C71A5DB5AD14F2081A38BC034C61A90.o:_CD0CDFD16296488DBA3A516F729ED0EC.cpp:(.text$_ZN9benchmark8internal17FunctionBenchmarkC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPFvRNS_5StateEE[_ZN9benchmark8internal17FunctionBenchmarkC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPFvRNS_5StateEE]+0x20): undefined reference to `benchmark::internal::Benchmark::Benchmark(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
D:/gcc/bin/../lib/gcc/x86_64-w64-mingw32/13.1.1/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\22835\AppData\Local\Temp\.xmake\230622\_2C71A5DB5AD14F2081A38BC034C61A90.o:_CD0CDFD16296488DBA3A516F729ED0EC.cpp:(.rdata$.refptr._ZTVN9benchmark8internal17FunctionBenchmarkE[.refptr._ZTVN9benchmark8internal17FunctionBenchmarkE]+0x0): undefined reference to `vtable for benchmark::internal::FunctionBenchmark'
collect2.exe: error: ld returned 1 exit status
```
可以看到链接错误了。

**Comment by waruqi** [comment]
? 你怎么设置平台的？如果是默认的 -p windows 平台，对于包，目前原本就是绑定 msvc toolchain ，不支持切换其他 toolchain 。。不管是否 cmake 。。其他 meson scons 等维护的包也不支持切换。。

因为包要在 ci 上做压测，一个 msvc 就已经 shared/static/MT/MTd/MD/MDd/x64/x86 等全排列压测，并且 on_install 脚本要做各种适配，再去支持任意 toolchain 切，维护不过来， 工作量和组合数是数量级增长。。

要想对包切 toolchains ，走交叉编译，`-p cross` ，目前只有交叉编译的包 才支持任意 toolchain 切换。。`-p linux` 平台支持 gcc/clang 等 host toolchain 切换。。windows 平台，目前只有 xmake 维护的包，能支持 gcc/clang 切换，其他 cmake 维护的暂时不支持。

**Comment by 2283572185** [comment]
>  你怎么设置平台的？

就是-p windows
> 目前原本就是绑定 msvc toolchain ，不支持切换其他 toolchain。

但msvc的abi以及name mangling和gcc/clang不一样，就导致mingw用不了msvc编译的库。Linux至少都是gnu的，不会链接错误。
> 要想对包切 toolchains ，走交叉编译，-p cross ，目前只有交叉编译的包 才支持任意 toolchain 切换。

但不换平台只换工具链还是有意义的嘛，这个gcc/clang的优化也比msvc更好。而且benchmark这种不应该因为交叉编译有问题，
就不让mingw用了嘛。而且有一个小问题，windows下开-p cross会去找Unix Makefiles，这还是改用ninja好一点吧。
> 支持云端预编译，对 windows 包支持加速安装

那就toolchain是msvc的时候走预编译，其他时候还是编译安装。

**Comment by 2283572185** [comment]
> 因为包要在 ci 上做压测，一个 msvc 就已经 shared/static/MT/MTd/MD/MDd/x64/x86 等全排列压测，并且 on_install 脚本要做各种适配

把Windows下的gcc/clang作为可选支持如何？不再做额外测试。能构建则构建，不能那是写库的人的问题。就只保证msvc能正常用。

**Comment by waruqi** [comment]
> > 你怎么设置平台的？
> 
> 就是-p windows
> 
> > 目前原本就是绑定 msvc toolchain ，不支持切换其他 toolchain。
> 
> 但msvc的abi以及name mangling和gcc/clang不一样，就导致mingw用不了msvc编译的库。Linux至少都是gnu的，不会链接错误。

mingw 有专门的 `-p mingw` 平台，以及对 mingw 支持的包，如果你要走 mingw ，应该直接切到 mingw 平台，而不是 window 平台下切工具链 

> 
> > 要想对包切 toolchains ，走交叉编译，-p cross ，目前只有交叉编译的包 才支持任意 toolchain 切换。
> 
> 但不换平台只换工具链还是有意义的嘛，这个gcc/clang的优化也比msvc更好。而且benchmark这种不应该因为交叉编译有问题

如果不用包，工具链随意切，用了包，对工具链切换肯定有限制的，不能让你随意切，

> 就不让mingw用了嘛。

mingw 有专门的 mingw 平

> 而且有一个小问题，windows下开-p cross会去找Unix Makefiles，这还是改用ninja好一点吧。

看包用的构建工具，cmake 的。包里面可以选择性切到 ninja 去编译，可以自己改。。

> 
> > 支持云端预编译，对 windows 包支持加速安装
> 
> 那就toolchain是msvc的时候走预编译，其他时候还是编译安装。

支持不了，每个 target 编译，不单纯仅有一个 toolchain，有可能 msvc ,yasm, dlang 等多个 toolchain 同时生效来混编，单纯从 Toolchain 层面处理预编译，不好搞，而且 linux macos 等平台还得收到 平台的 系统版本，runtime lib 等影响。。。单靠 toolchain 不行。。。只有 平台强绑定 才能更可靠的处理，实现起来相对也比较简单 好维护。

**Comment by waruqi** [comment]
> > 因为包要在 ci 上做压测，一个 msvc 就已经 shared/static/MT/MTd/MD/MDd/x64/x86 等全排列压测，并且 on_install 脚本要做各种适配
> 
> 把Windows下的gcc/clang作为可选支持如何？不再做额外测试。能构建则构建，不能那是写库的人的问题。就只保证msvc能正常用。

目前仅 xmake 维护的包支持，其他 cmake autoconf meson 包暂时不支持

**Comment by waruqi** [comment]
另外，windows 随意切 toolchain 。。还会导致 xmake-repo 里面每个 包的 配置脚本，on_install 脚本，额外增加脚本复杂度，降低可维护性，也会导致贡献者更难维护和改进包脚本。。

原本 windows 的包，我只需要简单假定作为 msvc 编译的来处理，安装脚本会很简单，维护性很好，现在额外多出 gcc/clang 等 N 中可能性， on_install 脚本里得额外判断 当前处于哪个 toolchian ，加特殊的安装逻辑，patch 逻辑，配置逻辑。。会很蛋疼。

**Comment by 2283572185** [comment]
> 原本 windows 的包，我只需要简单假定作为 msvc 编译的来处理，安装脚本会很简单，维护性很好，现在额外多出 gcc/clang 等 N 中可能性， on_install 脚本里得额外判断 当前处于哪个 toolchian ，加特殊的安装逻辑，patch 逻辑，配置逻辑。。会很蛋疼。

我认为可以放宽对本地的包的约束。xmake-repo的包依然严格和msvc绑定，而由用户创建的本地包则允许任意工具链，由用户去维护，这样就能比较好得解决这个问题了。毕竟用户可以知道他到底需要哪些组合而不用一一测试。

**Comment by waruqi** [comment]
> > 原本 windows 的包，我只需要简单假定作为 msvc 编译的来处理，安装脚本会很简单，维护性很好，现在额外多出 gcc/clang 等 N 中可能性， on_install 脚本里得额外判断 当前处于哪个 toolchian ，加特殊的安装逻辑，patch 逻辑，配置逻辑。。会很蛋疼。
> 
> 我认为可以放宽对本地的包的约束。xmake-repo的包依然严格和msvc绑定，而由用户创建的本地包则允许任意工具链，由用户去维护，这样就能比较好得解决这个问题了。毕竟用户可以知道他到底需要哪些组合而不用一一测试。

不是限制问题，是支持复杂度问题，目前还没人力实现，就算本地要支持，也得对 cmake/meson 透传 toolchain 环境，预编译对 toolchain加各种逻辑 过滤掉 gcc/clang 等非 msvc 。。各种地方都要改。。没那么简单。。都要花大量时间人力，才能支持上的。。。不是单纯一句像放开 就能放开的。。

**Comment by someview** [comment]
> 尽管理论上，随意切换 toolchain 肯定能实现，但是要考虑到现在，我单人的维护成本，时间，实现复杂度 等各方面综合考虑。。也许将来可能会支持，但短期你只能强绑定 windows 平台走 msvc 的包，mingw 平台走 mingw 包，cross 平台，走任意 toolchain 包。

哥们，你这不容易啊，单人维护这么多年
