### ISSUE TITLE
Suggestion: Pascal Language Support

### ISSUE THREAD

**Issue by kassane** [xmake-io/xmake#388]
It would be interesting to add in this project support for the pascal language adhering to compatibility with FreePascal and/or Delphi.

**Comment by waruqi** [comment]
As long as it is a native binary compatible compiled language, I will consider support it in xmake, but currently xmake is mainly focused on c/c++.

So I can't guarantee which version and time point to support it.

**Comment by waruqi** [comment]
If more than 5 people request this feature, I will consider supporting it.

**Comment by tazdij** [comment]
I would like to voice my request for this feature. Especially considering the simplicity and flexibility of the fpc compilation process. While freepascal is nice and simple to compile for, all of the other tasks related to but not directly part of the building of the binary.

It would be nice to have the ability to conditionally select shared library file to copy into the bin folder, and other similar tasks. Anyway, I just found xmake in a recent project, and think it is really nice, and would like to be able to use it for many of my freepascal projects :)

**Comment by waruqi** [comment]
ok, I will consider it in version 2.5.6

**Comment by waruqi** [comment]
some references:

* https://www.freepascal.org/download.html
* https://www.lazarus-ide.org/

**Comment by waruqi** [comment]
Maybe I need some example projects and makefiles to start working, such as hello world and static/shared program for free pascal.

**Comment by kassane** [comment]
Cross-platform tutorial/tips:
https://wiki.freepascal.org/Cross_compiling

**Comment by kassane** [comment]
Shared libraries:

```pascal
library SimpleLib;

function MySucc(AVal : Int64) : Int64; stdcall;
begin
  Result := System.Succ(AVal);
end;

function MyPred(AVal : Int64) : Int64; stdcall;
begin
  Result := System.Pred(AVal);
end;

exports
  MySucc,
  MyPred;

end.
```
Command:
```bash
fpc -Sd SimpleLib.pas
```

Source: [freepascal-wiki](https://wiki.freepascal.org/Using_Pascal_Libraries_with_.NET_and_Mono)

**Comment by waruqi** [comment]
done, examples: https://github.com/xmake-io/xmake/tree/dev/tests/projects/pascal

```lua
add_rules("mode.debug", "mode.release")
target("test")
    set_kind("binary")
    add_files("src/*.pas")
```

we need install fpc compiler.

**Comment by kassane** [comment]
Nice. I will try to test soon.

For static lib flag add:

```
-Xt (-static lib)
```

[More Info](https://www.freepascal.org/docs-html/3.0.2/user/userap1.html)

**Comment by kassane** [comment]
Fpc library to C app (ffi)

[Doc info](https://www.freepascal.org/docs-html/ref/refsu73.html#x190-21200014.10.3)

**Comment by waruqi** [comment]
> Nice. I will try to test soon.
> 
> For static lib flag add:
> 
> ```
> -Xt (-static lib)
> ```
> 
> [More Info](https://www.freepascal.org/docs-html/3.0.2/user/userap1.html)

done

**Comment by waruqi** [comment]
> Fpc library to C app (ffi)
> 
> [Doc info](https://www.freepascal.org/docs-html/ref/refsu73.html#x190-21200014.10.3)

? Does this require xmake to do something extra?

**Comment by kassane** [comment]
> > Fpc library to C app (ffi)
> > 
> > [Doc info](https://www.freepascal.org/docs-html/ref/refsu73.html#x190-21200014.10.3)
> 
> ? Does this require xmake to do something extra?

Before closing, it would be to have an ffi tests.

Examples [c++, rust, freepascal]:

[Lib](https://gist.github.com/kassane/5a7f35736b384fa0555cf82210c39086)
[App](https://gist.github.com/kassane/8b71ed122e235d7413976d08c3c5513a

**Comment by kassane** [comment]
Ok. I wiil test now.
But first problem: Missing pascal template in shared and static libs.

**Comment by waruqi** [comment]
> Ok. I wiil test now.
> But first problem: Missing pascal template in shared and static libs.

Because I am not familiar with pascal, there is no example of dynamic library and static library similar to hello world.

**Comment by kassane** [comment]
## Works

C library:

```c
#include <stdint.h>

extern int64_t fib(int64_t n)
{
    return n > 1 ? fib(n - 1) + fib(n - 2) : 1;
}
```
Pascal app:
```pascal
program hello;

function fib(n: Int64): Int64;
  cdecl; external 'bar';

var
  Value: Integer;
begin
  Value := 5;
  WriteLn(fib(Value));
end.
```

XMake build:

```lua
add_rules("mode.debug", "mode.release")

target("bar")
     set_kind("static") -- works
     -- set_kind("shared") -- works
     add_files("src/bar.c")

target("hello")
    set_kind("binary")
    add_deps("bar")
    add_files("src/hello.pas")
```
---

## Fail

Pascal library [shared / static]:
```pascal
library libbar;

{$mode objfpc}{$H+}

function fib(n : Int64) : Int64; cdecl;
begin
  if n > 1 then
  begin
      Result := fib(n - 1) + fib(n - 2);
  end
  else
        Result := 1;
end;

exports
{$IFDEF DARWIN}  {OS X entry points}
 fib name '_fib',
{$ENDIF}
 fib;
end.
```
XMake build:

```lua
add_rules("mode.debug", "mode.release")

target("bar")
     set_kind("static") -- don't works
     -- set_kind("shared") -- don't works
     add_files("src/bar.pas")

target("hello")
    set_kind("binary")
    add_deps("bar")
    add_files("src/hello.pas")
```

hello-app w/ static-lib output:
```bash
# build
[ 33%]: linking.release libbar.a
/usr/bin/fpc -O3 -Xt -obuild/linux/x86_64/release/libbar.a src/bar.pas
[ 66%]: linking.release hello
/usr/bin/fpc -O3 -Sd -k-Lbuild/linux/x86_64/release -Xs -k-lbar -obuild/linux/x86_64/release/hello src/hello.pas
[100%]: build ok!
# run
/build/linux/x86_64/release/hello: error while loading shared libraries: libbar.a: cannot open shared object file: No such file or directory
```
**hello-app w/ shared-lib output:**
```bash
# build
[ 33%]: linking.release libbar.so
/usr/bin/fpc -O3 -Sd -Xs -obuild/linux/x86_64/release/libbar.so src/bar.pas
[ 66%]: linking.release hello
checking for flags (-k-rpath=@loader_path) ... ok
/usr/bin/fpc -O3 -Sd -k-Lbuild/linux/x86_64/release -k-rpath=$ORIGIN -Xs -k-lbar -obuild/linux/x86_64/release/hello src/hello.pas
[100%]: build ok!
➜  hello ./build/linux/x86_64/release/hello
# run
./build/linux/x86_64/release/hello: symbol lookup error: ./build/linux/x86_64/release/hello: undefined symbol: calloc, version GLIBC_2.2.5
``

**Comment by kassane** [comment]
## New test - Works

Pascal - Shared lib

Pascal app:
```pascal
program Hello;

uses sysutils, dynlibs;

procedure UseLib;
type
  TMyFunc=function (n:Integer):Integer; stdcall;
var
  MyLib: TLibHandle = dynlibs.NilHandle;
  MyFunc: TMyFunc;
  FuncResult: integer;
begin
  MyLib := LoadLibrary('libbar.' + SharedSuffix);
  if MyLib = dynlibs.NilHandle then Exit;  //Lib was not loaded successfully
  MyFunc:= TMyFunc(GetProcedureAddress(MyLib, 'fib'));
  FuncResult:= MyFunc (5);  //Executes the function
  if MyLib <>  DynLibs.NilHandle then if FreeLibrary(MyLib) then MyLib:= DynLibs.NilHandle;  //Unload the lib, if already loaded
  writeln('Result fibonacci (Lib): '+InttoStr(FuncResult));
end;

procedure Main;
begin
	UseLib;
end;

begin
  Main;
end.
```

Pascal lib:
```pascal
library bar;

{$mode delphi} // delphi mode: fpc -Sd
// {$mode objfpc}{$H+} // fp mode: fpc -S2

function fib(n : Int64) : Int64; stdcall;
begin
  if n > 1 then
  begin
      Result := fib(n - 1) + fib(n - 2);
  end
  else
        Result := 1;
end;

exports
{$IFDEF DARWIN}  {OS X entry points}
 fib name '_fib',
{$ENDIF}
 fib;
end.
```


XMake build
```lua
add_rules("mode.debug", "mode.release")

target("bar")
     set_kind("static") -- don't works
     -- set_kind("shared") -- don't works
     add_files("src/bar.pas")

target("hello")
    set_kind("binary")
    add_deps("bar")
    add_files("src/hello.pas")
```

**Comment by kassane** [comment]
Ref.: [Modern Pascal - Introduction](https://castle-engine.io/modern_pascal_introduction.html)

**Comment by waruqi** [comment]
> /build/linux/x86_64/release/hello: error while loading shared libraries: libbar.a: cannot open shared object file: No such file or directory

-Xt (-static lib) cannot generate static library. libbar.a is still dynamic library.

>       -Xt        Link with static libraries (-static is passed to linker)

**Comment by waruqi** [comment]
> ./build/linux/x86_64/release/hello: symbol lookup error: ./build/linux/x86_64/release/hello: undefined symbol: calloc, version GLIBC_2.2.5

I fixed it, and added shared project tempalte.

**Comment by tazdij** [comment]
Thank you, I will also run some tests with my projects, this weekend. I will try to convert a couple of them to utilize xmake, instead of FPCs built in build system.

I have been away for about 3 weeks, recovering from a nasty virus. Otherwise I would have jumped on this issue :)

**Comment by kassane** [comment]
I would like you to add more extensions referring to pascal like:

```
*.dfu, *.lpr, *.dpr, *.ic
```
Unit files: `fpc -Fu`

Add flag `fPIC` or `-Cg` to shared library and XMake function to chance pascal syntax mode:

e.g.: `pascal_mode()`

Delphi mode: ` fpc -Sd` or `fpc -Mdelphi` or `fpc -Mdelphiunicode`
ObjPascal: `fpc -S2` or ` fpc -Mobjfpc`
Pascal (default): `fpc -Mfpc`

**Comment by waruqi** [comment]
> I would like you to add more extensions referring to pascal like:
> 
> ```
> *.ppu, *.lpr, *.inc
> ```
> 
> Unit files: `fpc -Fu`
> 
> Add flag `-fPIC` or `-Cg` to shared library and XMake function to chance pascal syntax mode:

done

> 
> e.g.: `pascal_mode()`
> 
> Delphi mode: ` fpc -Sd` or `fpc -Mdelphi` or `fpc -Mdelphiunicode`
> ObjPascal: `fpc -S2` or ` fpc -Mobjfpc`
> Pascal: `fpc -Mfpc`

you can use `add_pcflags()`

**Comment by waruqi** [comment]
I removed the static library example, because I tried some methods and it does not support generating static library well. In addition, I saw that the official fpc did not provide support for it.

https://gitlab.com/freepascal.org/fpc/documentation/-/issues/22272

**Comment by kassane** [comment]
> I removed the static library example, because I tried some methods and it does not support generating static library well. In addition, I saw that the official fpc did not provide support for it.
> 
> https://gitlab.com/freepascal.org/fpc/documentation/-/issues/22272

Wow! I understand.

I think it's unfortunate that you don't have static-lib support.
Then I can close this issue. Any more problems, another issue can be made for correction.

Thanks again @waruqi! Good work, XMake +1 support.

**Comment by tazdij** [comment]
I want to leave a comment here, expressing my gratitude. I can now use xmake for over 75% of my projects, and it is so much better than make and cmake. Thank you bunches :smiley:
