### ISSUE TITLE
There is an error in the CMakeLists.txt generated by xmake.

### ISSUE THREAD

**Issue by Redbeanw44602** [xmake-io/xmake#3880]
### Xmake Version

2.7.9

### Operating System Version and Architecture

Windows10 22H2

### Describe Bug

xmake-generated CMakeLists contains code related to enabling C++ exceptions that uses an incorrect method to determine the type of toolchain, resulting in a "unknown argument" warning for cl.

The specific problem code is as follows:
```
if(CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC") # bug
    target_compile_options(CubeTerritory PRIVATE /EHsc)
else()
    target_compile_options(CubeTerritory PRIVATE -fcxx-exceptions) # Added this parameter. But in reality, the MSVC toolchain is being used.
endif()
```

### Expected Behavior

Correctly identify the toolchain type and enable C++ exceptions. I noticed that the correct approach was used elsewhere.

The code for the above-mentioned problem should be modified as follows:
```
if(MSVC) # Tested and no bug found again.
    target_compile_options(CubeTerritory PRIVATE /EHsc)
else()
    target_compile_options(CubeTerritory PRIVATE -fcxx-exceptions)
endif()
```

Possible code location:
https://github.com/xmake-io/xmake/blob/17e6a90526fdb0ea059f26741e559e83ed241bb1/xmake/plugins/project/cmake/cmakelists.lua#L681

### Project Configuration

Not Important.

### Additional Information and Error Logs

```
[1/22] Building CXX object CMakeFiles\CubeTerritory.dir\src\Helper.cpp.obj
cl: 命令行 warning D9002 :忽略未知选项“-fcxx-exceptions”
...
```

**Comment by waruqi** [comment]
try it again. `xmake update -s dev`
