### ISSUE TITLE
proto文件独立成一个静态库导致链接报 undefined

### ISSUE THREAD

**Issue by ivanallen** [xmake-io/xmake#3881]
### Xmake 版本

xmake v2.7.9+20230619

### 操作系统版本和架构

Linux 10-16-43-32 5.14.0-70.13.1.el9_0.x86_64 #1 SMP PREEMPT Wed May 25 21:01:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

![image](https://github.com/xmake-io/xmake/assets/12481610/73d965c4-c63b-4095-a8fa-df3512a16264)

![image](https://github.com/xmake-io/xmake/assets/12481610/d48386e5-cca4-4350-9483-2aa87bee1d7f)

### 期待的结果

尝试在 src 中添加了一个 demo.cc 文件，如果也添加到 pp 库中，就可以正常链接。当pp 中只有 proto 文件时，会导致hello 这个 target link 不上 libpp.a

实际工程中，可能会有一个 proto 文件夹，里面只有 proto 文件，这个 proto 文件夹单独以库的形式被多个模块复用。

**Comment by waruqi** [comment]
给个完整 demo 工程

**Comment by ivanallen** [comment]
目录结构：

![image](https://github.com/xmake-io/xmake/assets/12481610/72725a48-e4a8-43bb-80b2-fb4113a8c2c9)

代码：

```lua
add_rules("mode.debug", "mode.release")
add_requires("protobuf-cpp")

target("hello")
    set_kind("binary")
    set_languages("c++11")
    add_files("src/*.cc")
    add_deps("pp")

target("pp")
    set_kind("static")
    add_packages("protobuf-cpp", {public = true})
    add_rules("protobuf.cpp")
    add_files("src/*.proto", {proto_public = true})
```


```c++
// main.cc
#include <stdio.h>
#include <demo.pb.h>

int main(int argc, char** argv)
{
    DemoRequest req;
    req.set_id(100);
    printf("hello world!\n");
    return 0;
}
```

```proto
// demo.proto
syntax = "proto3";

message DemoRequest {
    int32 id = 1;
}
```

```c++
// demo.cc
// 该文件只是测试用，并未添加到 xmake.lua
#include <demo.pb.h>
```

**Comment by waruqi** [comment]
再试试，`xmake update -s dev`

**Comment by ivanallen** [comment]
> 再试试，`xmake update -s dev`

可以了。我看你添加了 `add_deps("c++")`，这一行是什么意思呢？为什么加了它就可以正确 link 了

**Comment by waruqi** [comment]
> > 再试试，`xmake update -s dev`
> 
> 可以了。我看你添加了 `add_deps("c++")`，这一行是什么意思呢？为什么加了它就可以正确 link 了

因为你的 proto lib target 里 add_files 没有加任何 .cpp 文件，无法检测到 c++ 程序，默认也就不去 link 了。。可以加一个 空的 xxx.cpp 文件，也能绕过，或者强制设置 c++ rule ，作为 c++ 的 target 来 link
