### ISSUE TITLE
依赖的 proto 未编译完，主程序提前进行了编译，导致找不到 pb.h 文件

### ISSUE THREAD

**Issue by ivanallen** [xmake-io/xmake#3882]
### Xmake Version

v2.7.9+20230619

### Operating System Version and Architecture

Linux 10-16-43-32 5.14.0-70.13.1.el9_0.x86_64 #1 SMP PREEMPT Wed May 25 21:01:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Describe Bug

![image](https://github.com/xmake-io/xmake/assets/12481610/fa8d0f2a-4e4c-49b1-ae10-0ad66c8ccd87)

看起来是 demo.proto 依赖了 common.proto 导致的

### Expected Behavior

必须等到依赖 proto 全部编译完，再编译主程序

### Project Configuration

![image](https://github.com/xmake-io/xmake/assets/12481610/c744e5e3-14b7-45c5-b2fc-b15e56ca554a)

参考代码：https://gitee.com/ivan_allen/xmake_report

**Comment by waruqi** [comment]
同样给个完整的测试工程，打包发过来，github issues 可以上传附件

**Comment by ivanallen** [comment]
> https://gitee.com/ivan_allen/xmake_report

工程放在这里了，可以直接拉下来  https://gitee.com/ivan_allen/xmake_report

**Comment by waruqi** [comment]
因为你拆成了多个 target，目前 proto 的依赖分析，仅限于 proto 之间构造依赖图，然后proto 所在的 target 的其他 .cc 文件会确保在 proto 之后编译。。

但是跨了 target，目前的跨并行编译解决不了这个问题，你只能通过 `set_policy("build.across_targets_in_parallel", false)` 去对 target a 和 b 禁用跨 target 并行。。将并行编译限制在当前 target 内部文件之间。

**Comment by ivanallen** [comment]
> 因为你拆成了多个 target，目前 proto 的依赖分析，仅限于 proto 之间构造依赖图，然后proto 所在的 target 的其他 .cc 文件会确保在 proto 之后编译。。
> 
> 但是跨了 target，目前的跨并行编译解决不了这个问题，你只能通过 `set_policy("build.across_targets_in_parallel", false)` 去对 target a 和 b 禁用跨 target 并行。。将并行编译限制在当前 target 内部文件之间。

分成2步可行吗，第一步，先编译所有的 proto 文件，生成 pb.h pb.cc，第二步，处理编译的问题

如果不行，就只能牺牲编译速度了。不过我们这边项目挺大，编译速度也挺重要

**Comment by waruqi** [comment]
> > 因为你拆成了多个 target，目前 proto 的依赖分析，仅限于 proto 之间构造依赖图，然后proto 所在的 target 的其他 .cc 文件会确保在 proto 之后编译。。
> > 但是跨了 target，目前的跨并行编译解决不了这个问题，你只能通过 `set_policy("build.across_targets_in_parallel", false)` 去对 target a 和 b 禁用跨 target 并行。。将并行编译限制在当前 target 内部文件之间。
> 
> 分成2步可行吗，第一步，先编译所有的 proto 文件，生成 pb.h pb.cc，第二步，处理编译的问题

原本就是分2步的，但是只能在 target 内部分，不能跨 target 分。。

> 
> 如果不行，就只能牺牲编译速度了。不过我们这边项目挺大，编译速度也挺重要

target 内部还是并行编译的，对速度其实影响不大

**Comment by ivanallen** [comment]
> > > 因为你拆成了多个 target，目前 proto 的依赖分析，仅限于 proto 之间构造依赖图，然后proto 所在的 target 的其他 .cc 文件会确保在 proto 之后编译。。
> > > 但是跨了 target，目前的跨并行编译解决不了这个问题，你只能通过 `set_policy("build.across_targets_in_parallel", false)` 去对 target a 和 b 禁用跨 target 并行。。将并行编译限制在当前 target 内部文件之间。
> > 
> > 
> > 分成2步可行吗，第一步，先编译所有的 proto 文件，生成 pb.h pb.cc，第二步，处理编译的问题
> 
> 原本就是分2步的，但是只能在 target 内部分，不能跨 target 分。。
> 
> > 如果不行，就只能牺牲编译速度了。不过我们这边项目挺大，编译速度也挺重要
> 
> target 内部还是并行编译的，对速度其实影响不大

好的，看起来只能先这样了
