### ISSUE TITLE
无法识别 WIN32 宏定义

### ISSUE THREAD

**Issue by LJJ931026** [xmake-io/xmake#3884]
### Xmake 版本

2.7.9

### 操作系统版本和架构

Windows10

### 描述

在 Windows10 上使用 xmake2.7.9 版本编译时遇到无法找到 unistd.h 头文件，可以通过下面源码看到应该进入到 WIN32 分支下找头文件，但是却进入了 else 分支。

```txt
error: log4z.cpp
log4z\log4z.cpp(61): fatal error C1083: 无法打开包括文件: “unistd.h”: No such file or directory

  > in log4z\log4z.cpp
```

### 源码

```cpp
#ifdef WIN32
#include <io.h>
#include <shlwapi.h>
#include <process.h>
#pragma comment(lib, "shlwapi")
#pragma comment(lib, "User32.lib")
#pragma warning(disable:4996)

#else
#include <unistd.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sys/types.h>
#include <sys/socket.h>
#include<pthread.h>
#include <sys/time.h>
#include <sys/stat.h>
#include <dirent.h>
#include <fcntl.h>
#include <semaphore.h>
#include <sys/syscall.h>
#endif
```

### 期望结果

这是一个开源日志代码，我使用了 qmake 和 cmake 编译都是没有问题，理论上 xmake 也应该编译通过。

### xmake 配置

```sh
target("log")
    set_kind("binary")
    add_includedirs("log4z")
    add_files("log4z/log4z.cpp")
    add_files("main.cpp")
```

### 目录结构

```txt
src
├──main.cpp
└──log4z
    ├──log4z.h
    └──log4z.cpp
```

**Comment by SirLynix** [comment]
the right Windows define is `_WIN32` (see https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170), either change it or add `add_defines("WIN32")` on Windows.

--

正确的Windows定义是`_WIN32`（见https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170），要么改变它，要么在Windows上添加`add_defines("WIN32")`。

**Comment by LJJ931026** [comment]
### 解决方法

@SirLynix 按照你说的将 WIN32 替换为 _WIN32 后可以编译通过，非常感谢。
