### ISSUE TITLE
支持 link 完整路径的库文件

### ISSUE THREAD

**Issue by ivanallen** [xmake-io/xmake#3889]
### 你在什么场景下需要该功能？

当系统中存在相同的库时，使用 -L -l 方式可能产生 link 错误。

例如下面的 lflags 会导致  link 错误，本意是想 link /usr/lib64/librdmacm.a /path/to/fmt/lib/libfmt.a，但是实际会导致 link 成 /usr/lib64/libfmt.a

```
-L/usr/lib64 -L/path/to/fmt/lib -lrdmacm -lfmt
```

### 描述可能的解决方案

如果 xmake link 的时候，直接指定 /path/to/fmt/lib/libfmt.a 就不会有这个问题。

**Comment by waruqi** [comment]
自己走 add_ldflags 就行了

**Comment by waruqi** [comment]
可以了，`xmake update -s dev`

**Comment by ivanallen** [comment]
在我的环境上看起来没有生效

![image](https://github.com/xmake-io/xmake/assets/12481610/8fecfca8-b134-41f9-b938-c1e6e20b919d)


```bash
xmake update -s dev
xmake clean -a
xmake f -cv
xmake -v
```

**Comment by waruqi** [comment]
```lua

target("test")
    set_kind("binary")
    add_files("src/*.cpp")
    add_links("/usr/local/libtest.a")
```

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o
 build/macosx/x86_64/release/test build/.objs/test/macosx/x86_64/release/src/main.cpp.o -target x
86_64-apple-macos12.6 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platf
orm/Developer/SDKs/MacOSX13.0.sdk -stdlib=libc++ -Wl,-x -Wl,-dead_strip /usr/local/libtest.a -lz
```

**Comment by ivanallen** [comment]
> ```lua
> target("test")
>     set_kind("binary")
>     add_files("src/*.cpp")
>     add_links("/usr/local/libtest.a")
> ```
> 
> ```
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o
>  build/macosx/x86_64/release/test build/.objs/test/macosx/x86_64/release/src/main.cpp.o -target x
> 86_64-apple-macos12.6 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platf
> orm/Developer/SDKs/MacOSX13.0.sdk -stdlib=libc++ -Wl,-x -Wl,-dead_strip /usr/local/libtest.a -lz
> ```
> 
> 不是有的么

你是显式的 add_links 的呀。其实我是想自动 add_deps 的库，也能 link 全路径

**Comment by ivanallen** [comment]
这个需求是我 add_packages 了第三方的库，可能非常多的库，我没有办法一个一个手动去 link 全路径，因为实在是太多了。。。

**Comment by ivanallen** [comment]
然后每个人的机器环境可能都不一样，有的人在本地安装了系统库，就导致各种问题

**Comment by waruqi** [comment]
> > ```lua
> > target("test")
> >     set_kind("binary")
> >     add_files("src/*.cpp")
> >     add_links("/usr/local/libtest.a")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o
> >  build/macosx/x86_64/release/test build/.objs/test/macosx/x86_64/release/src/main.cpp.o -target x
> > 86_64-apple-macos12.6 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platf
> > orm/Developer/SDKs/MacOSX13.0.sdk -stdlib=libc++ -Wl,-x -Wl,-dead_strip /usr/local/libtest.a -lz
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 不是有的么
> 
> 你是显式的 add_links 的呀。其实我是想自动 add_deps add_packages 的库，也能 link 全路径

这个不考虑

**Comment by ivanallen** [comment]
> > > ```lua
> > > target("test")
> > >     set_kind("binary")
> > >     add_files("src/*.cpp")
> > >     add_links("/usr/local/libtest.a")
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o
> > >  build/macosx/x86_64/release/test build/.objs/test/macosx/x86_64/release/src/main.cpp.o -target x
> > > 86_64-apple-macos12.6 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platf
> > > orm/Developer/SDKs/MacOSX13.0.sdk -stdlib=libc++ -Wl,-x -Wl,-dead_strip /usr/local/libtest.a -lz
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 不是有的么
> > 
> > 
> > 你是显式的 add_links 的呀。其实我是想自动 add_deps add_packages 的库，也能 link 全路径
> 
> 这个不考虑

为什么呢，我看 cmake 也都是 link 全路径的，这种方式，能避免依赖冲突的问题。-L -l 这种在大型项目中非常不好用

**Comment by ivanallen** [comment]
如果开发的话难度大不大，我可以自己尝试一下

**Comment by waruqi** [comment]
试下这个。https://github.com/xmake-io/xmake/issues/5066#issuecomment-2108007718
