### ISSUE TITLE
error: unknown source file:

### ISSUE THREAD

**Issue by XinranSix** [xmake-io/xmake#3896]
### Xmake 版本

v2.7.9

### 操作系统版本和架构

Windown 10 22H2

### 描述问题

![image](https://github.com/xmake-io/xmake/assets/62458905/c3e3e20c-e725-4e46-8a6c-35b90f5c53aa)
如上图所示，src 目录下有 Application.cpp 文件，但在 build 的时候出现了如下错误：
![image](https://github.com/xmake-io/xmake/assets/62458905/3636382c-e967-4860-b240-a82c5f638b8d)

### 期待的结果

不出现前面描述的错误。

### 工程配置

![image](https://github.com/xmake-io/xmake/assets/62458905/4583d4f1-a1a7-455e-9f45-e45e3ebc8151)

**Comment by waruqi** [comment]
`*cpp` 改成 `*.cpp`
