### ISSUE TITLE
Unable to use "clang-cl" as toolchain due to weird precompiled header error

### ISSUE THREAD

**Issue by WSSDude** [xmake-io/xmake#3905]
### Xmake Version

v2.7.9+master.a361c0684

### Operating System Version and Architecture

Windows 11 Pro 22H2 (x64)

### Describe Bug

When I add `set_toolchains("clang-cl")`, compilation dies during precompiled header step because it appears it can't find the header for whatever reason. Default VS2022 toolchain works as expected.

### Expected Behavior

I would expect clang-cl to work the same way as VS2022 toolchain does in this regard (meaning it is able to find and compile the header, if there are other errors in my code, so be it... but there doesn't seem to be anything obviously wrong which would prevent header from being found)

### Project Configuration

Don't have minimal example, can try to make some when required. Whole project can be checked out here, xmake.lua is in the root. Problem is on all commits, so latest in master should suffice for reference.

Code: https://github.com/WSSDude/HitmanAudioTool
xmake.lua: https://github.com/WSSDude/HitmanAudioTool/blob/main/xmake.lua

### Additional Information and Error Logs

Used debug build (release errors on warnings in my code and there are some unfixed, though I would not suspect them to matter)

[clang-cl_precompiled_header.log](https://github.com/xmake-io/xmake/files/11906610/clang-cl_precompiled_header.log)

**Comment by WSSDude** [comment]
Added log created by running `xmake -r -y -VD`.
Note that debug configuration was used as mentioned in the OP.

**Comment by WSSDude** [comment]
Just last note, need to leave for a bit then - file is definitely present at the right location I can see in the log.

![image](https://github.com/xmake-io/xmake/assets/41929176/0cabab83-eaa5-411e-8647-c0067b968bbb)

**Comment by waruqi** [comment]
try it again. `xmake update -s dev`

**Comment by WSSDude** [comment]
Seems like this did the trick 👍 Thank you🙇 
Closing the issue.
