### ISSUE TITLE
linux下编译的动态库无法被使用

### ISSUE THREAD

**Issue by Ultraman95** [xmake-io/xmake#391]
我编译生成了libssl.so.1.1的库，我在lua脚本中使用了add_links("ssl"),好像无法找到这个库
但是如果我使用ln -s libssl.so.1.1 libssl.so这样就能找到这个库
请问还有其他办法吗？

**Comment by waruqi** [comment]
没有

**Comment by Ultraman95** [comment]
add_links不支持版本号吗

**Comment by waruqi** [comment]
add_links 只做 xxx  ->  -lxxx.so/.a   xxx.lib 的翻译。不处理版本。。

**Comment by Ultraman95** [comment]
还有就是在linux下使用add_linksdirs()这个命令，在xmake build的时候如何优先去这个路径下找，而不是去系统路径下找

**Comment by waruqi** [comment]
？通过这个设置的 都会优先于默认的系统路径
