### ISSUE TITLE
Apple Clang 下 OBJCXX 混合目标打开 PCH 出现冲突

### ISSUE THREAD

**Issue by SaeruHikari** [xmake-io/xmake#3912]
### Xmake Version

2.7.9

### Operating System Version and Architecture

macOS latest

### Describe Bug

![image](https://github.com/xmake-io/xmake/assets/39457738/d183d737-1016-49d6-a1aa-842024b15696)

CMake 有个叫 SKIP_PRECOMPILE_HEADERS 的 prop，可以在编译文件时跳过 pch。

### Expected Behavior

编译 objc 文件时跳过 pch

**Comment by waruqi** [comment]
我看 objc 支持 pch 的，能编译过，为啥要单独禁用？你这加了什么配置禁用 objc 预编译了 为啥?

**Comment by SaeruHikari** [comment]
具体原因不太清楚，输出也不太详细，只能找到很多类似这样的参考：

https://discourse.cmake.org/t/target-precompile-headers-with-macos-and-objective-c-mm-files/3205

看这些描述貌似 objc 不使用 -include-pch，xmake 看源码直接继承了 pcxxheader 规则，这里 cmake 做了单独支持，可能有单独的 flags？

**Comment by waruqi** [comment]
```console
[  7%]: cache compiling.release src/test5.mm
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -c
-pipe -DIBOutlet=__attribute__((iboutlet)) -DIBOutletCollection(ClassName)=__attribute__((iboutl
etcollection(ClassName))) -DIBAction=void)__attribute__((ibaction) -Qunused-arguments -target x8
6_64-apple-macos12.6 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platf
orm/Developer/SDKs/MacOSX13.0.sdk -fobjc-arc -fvisibility=hidden -O3 -std=c++11 -framework Found
ation -framework CoreFoundation -include src/header.h -include-pch build/.objs/main/macosx/x86_6
4/release/src/header.h.pch -o build/.objs/main/macosx/x86_64/release/src/test5.mm.o src/test5.mm
checking for flags (-MMD -MF) ... ok
checking for flags (-fdiagnostics-color=always) ... ok
checking for flags (-fdiagnostics-color=always) ... ok
[ 14%]: cache compiling.release test3.cpp
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -c
-Qunused-arguments -target x86_64-apple-macos12.6 -isysroot /Applications/Xcode.app/Contents/Dev
eloper/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk -fvisibility=hidden -fvisibility-
inlines-hidden -O3 -std=c++11 -framework Foundation -framework CoreFoundation -include src/heade
r.h -include-pch build/.objs/main/macosx/x86_64/release/src/header.h.pch -DNDEBUG -o build/.objs
/main/macosx/x86_64/release/test3.cpp.o test3.cpp
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/
bin/clang++ ... ok
checking for the linker (ld) ... clang++
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/
bin/clang++ ... ok
checking for flags (-fPIC) ... ok
[ 85%]: linking.release main
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -
o build/macosx/x86_64/release/main build/.objs/main/macosx/x86_64/release/src/test.cpp.o build/.
objs/main/macosx/x86_64/release/src/test8.cpp.o build/.objs/main/macosx/x86_64/release/src/test4
.cpp.o build/.objs/main/macosx/x86_64/release/src/test5.cpp.o build/.objs/main/macosx/x86_64/rel
ease/src/test7.cpp.o build/.objs/main/macosx/x86_64/release/src/test6.cpp.o build/.objs/main/mac
osx/x86_64/release/src/test2.cpp.o build/.objs/main/macosx/x86_64/release/src/main.cpp.o build/.
objs/main/macosx/x86_64/release/test3.cpp.o build/.objs/main/macosx/x86_64/release/src/test.c.o
build/.objs/main/macosx/x86_64/release/src/test5.mm.o -target x86_64-apple-macos12.6 -isysroot /
Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sd
k -stdlib=libc++ -Wl,-x -Wl,-dead_strip -framework Foundation -framework CoreFoundation -lz
[100%]: build ok, spent 4.798s
```

>  -include src/header.h -include-pch build/.objs/main/macosx/x86_6
4/release/src/header.h.pch -o build/.objs/main/macosx/x86_64/release/src/test5.mm.o src/test5.mm

我这里加了个 objc 和 pch 编译都正常么，没啥问题。

**Comment by SaeruHikari** [comment]
看字面意思是 pch 没有打开 objc，我找到一个类似问题，是pch 开了 cxx14 但是文件没开：
https://root-forum.cern.ch/t/c-14-was-enabled-in-pch-file-but-is-currently-disabled/19566/2

看了看我的 CI 输出的 log 感觉原理近似：
https://github.com/SakuraEngine/SakuraEngine/actions/runs/5443570225/jobs/9900254004#step:11:145

可能需要在构建 objc 用的 pch 时添加参数？

**Comment by SaeruHikari** [comment]
可能我的 pch 里面产生了什么 c++ 独有的东西，xmake 的测试例里面没有，所以覆盖不到。我稍候调整下 pch 里的内容再试试。

**Comment by SaeruHikari** [comment]
按照 cmake 那边的情况，objc 的 pch 确实是要作为一个独立语言处理的，类似的报错蛮多的。这个报错 cmake 有两个修补方案：

- 用我上面说的那个 prop 跳过这个文件的 pch flag；
- 在语言集里 explicit 加入 objcxx，这样 objcxx 会从 cxx 分离，走一个专门的 toolchain，cmake 在这个 toolchain 里面有独立的 pch 逻辑。

xmake 的 objcxx pch rule 我看是直接继承了 cpp pch rule。

不过我定位不到具体原因，这个输出太模糊了，clang 的文档里也没提及。

**Comment by waruqi** [comment]
> 看字面意思是 pch 没有打开 objc，我找到一个类似问题，是pch 开了 cxx14 但是文件没开： https://root-forum.cern.ch/t/c-14-was-enabled-in-pch-file-but-is-currently-disabled/19566/2

估计是编译 pch 时候，没开 objc ，编译器默认作为 c++ 编译生成的 pch ，不包含 objc 相关信息。。

然后编译 .mm ，编译器默认开了 objc ，然后输入的 pch 的是 c++ 格式的，所以报了那个错误。。

一种就是可以尝试生成兼容 objc 的 pch，一种就是你说的pch 忽略 objc，不过具体怎么弄还有待分析，等后面几天吧，最近暂时也没太多时间

**Comment by SaeruHikari** [comment]
嗯嗯，我 mac 平台先关闭就好，问题不大

**Comment by waruqi** [comment]
切到 dev 分支再试试。https://github.com/xmake-io/xmake/pull/3922

默认禁用 objc pch ，如果要开启 objc pch ，额外设置下，set_pcxxheader 之后仅用于 c++

```lua
set_pmxxheader("header.h")
```

**Comment by SaeruHikari** [comment]
OK 了
