### ISSUE TITLE
交叉时cmake的c++编译器路径错误

### ISSUE THREAD

**Issue by 2283572185** [xmake-io/xmake#3913]
### Xmake 版本

v2.7.9+dev.8b9228762

### 操作系统版本和架构

Windows 11 22H2

### 描述问题

运行`xmake f --toolchain=gcc -p cross -m Debug -a x64 --target_os=Windows`
在编译cmake包时出现错误
```
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:4 (project):
  The CMAKE_CXX_COMPILER:

    ./gcc.exe

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
```
这是cmake的选项
```
cmake -DBENCHMARK_ENABLE_TESTING=OFF -DBENCHMARK_INSTALL_DOCS=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=C:\Users\22835\AppData\Local\.xmake\packages\b\benchmark\1.8.0\da4ba6115e2b4d7c964c6b695dbd0e68 -DCMAKE_INSTALL_LIBDIR:PATH=lib -G Ninja -DCMAKE_CXX_FLAGS=-m64 -DCMAKE_FIND_USE_INSTALL_PREFIX=0 -DCMAKE_C_FLAGS=-m64 -DCMAKE_EXE_LINKER_FLAGS=-m64 -DCMAKE_STATIC_LINKER_FLAGS= -DCMAKE_AR=ar.exe -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=BOTH -DCMAKE_FIND_USE_CMAKE_SYSTEM_PATH=0 -DCMAKE_C_COMPILER=gcc.exe -DHAVE_FLAG_SEARCH_PATHS_FIRST=0 -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=BOTH -DCMAKE_SHARED_LINKER_FLAGS=-m64 -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_ASM_FLAGS=-m64 -DCMAKE_OSX_SYSROOT= -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_CXX_COMPILER=./gcc.exe -DCMAKE_ASM_COMPILER=gcc.exe "-DCMAKE_CXX_LINK_EXECUTABLE=g++.exe <FLAGS> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>" C:\Users\22835\AppData\Local\.xmake\cache\packages\2307\b\benchmark\1.8.0\source
```
除了c++编译器错误地设置成了./g++.exe，其他的工具都正确。
换用clang同样也会错误地把c++编译器设置成./clang.exe。
不过如果加上`--cxx=D:\Tools\gcc\bin\g++.exe`也就是设置g++的绝对路径就可以解决这个问题。

### 期待的结果

和c编译器等工具一样设置成g++.exe或者使用绝对路径。

**Comment by waruqi** [comment]
再试试

```
xmake update -s dev
```

**Comment by 2283572185** [comment]
看起来不太行`xmake f --toolchain=clang -a x64 -m Debug -p cross -v --target_os=Windows -c`
但输出还是
```
CMake Error at CMakeLists.txt:4 (project):
  The CMAKE_CXX_COMPILER:

    ./clang.exe

  is not a full path and was not found in the PATH.
```

**Comment by waruqi** [comment]
再试试

**Comment by 2283572185** [comment]
现在路径对了

**Comment by 2283572185** [comment]
> 现在路径对了

为何CMAKE_CXX_COMPILER变成了gcc.exe/clang.exe而不是g++.exe/clang++.exe？这导致cmake的一些测试不能通过，因为编译器没有去寻找c++头文件和链接库。

**Comment by waruqi** [comment]
> > 现在路径对了
> 
> 为何CMAKE_CXX_COMPILER变成了gcc.exe/clang.exe而不是g++.exe/clang++.exe？这导致cmake的一些测试不能通过，因为编译器没有去寻找c++头文件和链接库。

你调下这个位置。。https://github.com/xmake-io/xmake/blob/087be99d586ed93ac76cf52d56e31b14ea7f6b55/xmake/modules/package/tools/cmake.lua#L488

理论上内部已经替换成 clang++ 了。。这个问题 很久就修复了。。

**Comment by 2283572185** [comment]
> > > 现在路径对了
> > 
> > 
> > 为何CMAKE_CXX_COMPILER变成了gcc.exe/clang.exe而不是g++.exe/clang++.exe？这导致cmake的一些测试不能通过，因为编译器没有去寻找c++头文件和链接库。
> 
> 你调下这个位置。。
> 
> https://github.com/xmake-io/xmake/blob/087be99d586ed93ac76cf52d56e31b14ea7f6b55/xmake/modules/package/tools/cmake.lua#L488
> 
> 理论上内部已经替换成 clang++ 了。。这个问题 很久就修复了。。

看起来它并没有工作
```lua
print(name)
name = name:gsub("clang$", "clang++")
name = name:gsub("clang%-", "clang++-")
name = name:gsub("gcc$", "g++")
name = name:gsub("gcc%-", "g++-")
print(name)
```
输出是
```
clang.exe
clang.exe
```

**Comment by waruqi** [comment]
> 你调下这个位置。。

位置在哪已经给你指出来了，自己调下。我这没法复现

**Comment by waruqi** [comment]
你把 .exe 去了试试

**Comment by waruqi** [comment]
再试下 xmake update -s dev

**Comment by 2283572185** [comment]
可以了
