### ISSUE TITLE
`bash` completions error: `compctl: command not found`

### ISSUE THREAD

**Issue by vic1707** [xmake-io/xmake#3915]
### Xmake Version

xmake v2.7.9+HEAD.c879226

### Operating System Version and Architecture

macOS 13.4 (22F66)

### Describe Bug

Running `bash` from an OS whose default shell is `zsh` causes completions to fail to load.
<img width="598" alt="image" src="https://github.com/xmake-io/xmake/assets/28602203/0f7edda0-7d4f-4f78-8178-ee251a1ed692">

### Expected Behavior

I think completions should load based on the currently running shell, not the global default one.

[Xmake chooses completions based on `$SHELL`](https://github.com/xmake-io/xmake/blob/master/xmake/scripts/profile-unix.sh#L22) which returns the default shell, not the currently running one.

<img width="476" alt="image" src="https://github.com/xmake-io/xmake/assets/28602203/ceb258f7-5ce6-4011-98cc-4a21ab115092">

The fix could involve replacing `$SHELL` in `profile-unix.sh`. I tried `$0` since it fixes the `bash` issue, but breaks `zsh` completions.

**Comment by waruqi** [comment]
> The fix could involve replacing in . I tried since it fixes the issue, but breaks completions.$SHELLprofile-unix.sh$0bashzsh

But it does not work in script file.

test.sh
```
echo $0
```

```
bash ./test.sh
./test.sh
```

Now I don't have a better way to improve it, you can modify $SHELL to fix it.

**Comment by vic1707** [comment]
I'll test with variables only available in those shells

**Comment by vic1707** [comment]
the use of `$ZSH_VERSION` and `$BASH_VERSION` does the trick, created #3919 if that looks good to you.
