### ISSUE TITLE
swift多文件编译未合并在同一个module中造成编译失败

### ISSUE THREAD

**Issue by zjyhjqs** [xmake-io/xmake#3916]
### Xmake 版本

2.7.9+20230515

### 操作系统版本和架构

macOS 13.4.1 (22F82)

### 描述问题

在swift的语法中, 允许通过一次性将多个文件输入`swiftc`中, 作为一个module进行编译:

例: 
```
// A.swift
func test() {}

// B.swift
test()
```

`swiftc -o Test A.swift B.swift` // success

然而在`xmake`的处理中, 每个文件被分开进行编译, 这就使得例中的`B.swift`因找不到符号导致编译失败.

### 期待的结果

正常通过编译

**Comment by waruqi** [comment]
合并成一条命令编译，类似 rust 这种，尽管可以，改动太大，并且有很多局限性，比如无法细粒度设置单独每个 swift 文件的 flags 。。也没法做并行编译优化。。所以能不搞一起 尽量不搞一起。。

可以先先研究下拆分 obj 编译时候的 module 支持方案，我记得应该是可以的，比如用 modulemap 什么的，但是具体怎么弄，要花时间分析，这块先放着吧，最近也没太多时间。。或者你可以先自己研究下 如何单独编译某个 swift 时候，支持引入其他 module 符号

**Comment by waruqi** [comment]
你先提供个可复现的完整 example project 过来

**Comment by zjyhjqs** [comment]
> 你先提供个可复现的完整 example project 过来

[test.zip](https://github.com/xmake-io/xmake/files/11995387/test.zip)

**Comment by waruqi** [comment]
再试试，`xmake update -s dev`

**Comment by zjyhjqs** [comment]
> 再试试，`xmake update -s dev`

我手头上的工程没问题了👌
