### ISSUE TITLE
qt windeployqt自动调用的问题

### ISSUE THREAD

**Issue by zhuizhubf** [xmake-io/xmake#3918]
### Is your feature request related to a problem? Please describe.

在一些场景下 不需要调用windeployqt自动包含依赖 
但是 尝试后发现都不能覆盖 install 查看源码发现是 after_install 实现的 

### Describe the solution you'd like

单独封装成一个 rule 自己引用 或者又更好的方案

### Describe alternatives you've considered

目前是直接注释掉 os.vrunv(windeployqt, argv, {envs = envs})

**Comment by waruqi** [comment]
这种，自己重写 on_install  或者自己做个自己的 rule 就好了，内置的就不改了，不可能满足所有用户的需求。。

**Comment by zhuizhubf** [comment]
自己写 rule 
```
rule("executable")
    on_load(function (target)
        target:set("targetdir", "$(buildir)/$(mode)/bin")
    end)
    on_install(function (target)
        os.mkdir(path.join(target:installdir(), "bin"))
        os.cp(target:targetfile(), path.join(target:installdir(), "bin"))
    end)
```
在 目标程序调用 
```
target("processlauncher")
    add_rules("qt.console")
    add_rules("executable")

   ...
```
 在  xmake i -o build/out1  时候 它依然会 调用 windeployqt 的命令 

但是 在 target 本身 写 
```
target("processlauncher")
    add_rules("qt.console")
   ...
    on_install(function (target)
        os.mkdir(path.join(target:installdir(), "bin"))
        os.cp(target:targetfile(), path.join(target:installdir(), "bin"))
    end)
target_end()
```
不会触发 windeployqt

**Comment by waruqi** [comment]
对，目前 rules 是追加 on_install ，只有 target 的是覆盖
