### ISSUE TITLE
如何在包中引用绝对路径的第三方库呢

### ISSUE THREAD

**Issue by ChrisCatCP** [xmake-io/xmake#3920]
### 你在什么场景下需要该功能？

在包中使用相对路径很容易和第三方包管理器的库冲突    
我尝试过add("links")无法引用绝对路径的库  也没法add("files")    

### 描述可能的解决方案

无

**Comment by waruqi** [comment]
没懂什么意思，包定义中，只能走 add_deps 引入其他包依赖，会自动优先查找系统库。

**Comment by ChrisCatCP** [comment]
是这么个情况  我在安装官方的包(hpsocket)的时候他自带了libssl  安装的时候会把自带的libssl引入  这样做正常情况是没问题。。但是我引入了vcpkg的一个包   所以lib搜索目录有vcpkg的目录  然后他会默认引用vcpkg目录的libssl  就没法正常编译。。  所以我想把这里的libssl改成绝对路径    不知道有没有更好的解决办法

**Comment by waruqi** [comment]
> 是这么个情况 我在安装官方的包(hpsocket)的时候他自带了libssl 安装的时候会把自带的libssl引入 这样做正常情况是没问题。。但是我引入了vcpkg的一个包 所以lib搜索目录有vcpkg的目录 然后他会默认引用vcpkg目录的libssl 就没法正常编译。。 所以我想把这里的libssl改成绝对路径 不知道有没有更好的解决办法

这个包原本当初人家塞进来的时候，就没完全做好，应该改进 hpsocket 包，禁用自带的 llbssl，全部走 `add_deps("openssl")` 引入 xmake-repo 的 ssl包。

**Comment by ChrisCatCP** [comment]
其实感觉deps也会有相同的问题   搜索顺序问题还是得解决一下。。

**Comment by waruqi** [comment]
> 其实感觉deps也会有相同的问题 搜索顺序问题还是得解决一下。。

不会，add_deps 优先搜系统，系统没有使用 xmake-repo 的包。。你也可以 `add_requireconfs("hpsocket.openssl", {system = false})` 对依赖禁用系统库搜索，直接走 xmake-repo 里面的包。。也可以 `add_deps("vcpkg::openssl")` 显式依赖其他仓库的包。。想这么搞都行。。

**Comment by ChrisCatCP** [comment]
系统没有ssl    项目又引入了vcpkg  我看着是vcpkg的目录是在前面   除非我卸载掉vcpkg的ssl 因为是静态库。。如果是动态库就没问题  因为包里没有引用vcpkg  所以没有vcpkg的搜索目录

**Comment by ChrisCatCP** [comment]
除非我把所有vcpkg的包都挪到xrepo的包的后面。。  不然还是会有这个问题。。

**Comment by ChrisCatCP** [comment]
所以如果能绝对路径的话  就最好了。。。  我不知道还有没别的解决方法

**Comment by waruqi** [comment]
> 系统没有ssl 项目又引入了vcpkg 我看着是vcpkg的目录是在前面 除非我卸载掉vcpkg的ssl 因为是静态库。。如果是动态库就没问题 因为包里没有引用vcpkg 所以没有vcpkg的搜索目录

那是因为 vcpkg 的库存储结构导致的，都在一个地方，不建议 混用 xmake-repo 和 vcpkg 的包。要么全走 vcpkg 。。要么全走 xmake-repo

**Comment by ChrisCatCP** [comment]
> > 系统没有ssl 项目又引入了vcpkg 我看着是vcpkg的目录是在前面 除非我卸载掉vcpkg的ssl 因为是静态库。。如果是动态库就没问题 因为包里没有引用vcpkg 所以没有vcpkg的搜索目录
> 
> 那是因为 vcpkg 的库存储结构导致的，都在一个地方，不建议 混用 xmake-repo 和 vcpkg 的包。要么全走 vcpkg 。。要么全走 xmake-repo

是这样的  看来混用确实是个不好的选择   其实我就用了一个包dxsdk。。xrepo里没有   我尝试加到xrepo里吧   不用vcpkg了
