### ISSUE TITLE
making generator recognize rule batchcmds:runv ln execv commands

### ISSUE THREAD

**Issue by DanielKui** [xmake-io/xmake#3921]
### Is your feature request related to a problem? Please describe.

This request was related to https://github.com/orgs/xmake-io/discussions/3914 

when I use “xmake project -k makefile  --file=xmake.lua”, try to generate makefile,  generator will ignore batchcmds:runv, batchcmds:ln commands. so then makefile will not have those commands.

### Describe the solution you'd like

“xmake project -k makefile  --file=xmake.lua” should generate the corresponding commands in makefile and CMakeLists.txt

**Comment by waruqi** [comment]
batchcmds:ln 我加了 。。https://github.com/xmake-io/xmake/pull/3924

```
xmake update github:xmake-io/xmake#makefile
```

**Comment by waruqi** [comment]
xmake update -s dev
