### ISSUE TITLE
CentOS下面Curl库没有按名称寻找

### ISSUE THREAD

**Issue by Ultraman95** [xmake-io/xmake#393]
使用addlinks("curl")，没有去寻找libcurl.so库，而是寻找libcurl.so..4这个库，这个是什么原因

**Comment by Ultraman95** [comment]
我是怎么知道这个事情的呢，我用ldd命令查看（通过xmake build生成）程序，发现依赖libcurl.so.4这个库，但是我在lua脚本里面明明写的是addlinks("curl")

**Comment by waruqi** [comment]
你装的libcurl.so 是软连接 -> libcurl.so.4

**Comment by Ultraman95** [comment]
我的软连接是这样的
libcurl.so -> libcurl.so.4.5.0
libcurl.so.4 -> libcurl.so.4.5.0
libcurl.so.4.5.0

**Comment by Ultraman95** [comment]
![1555047924(1)](https://user-images.githubusercontent.com/1725360/56014796-4984e800-5d29-11e9-9be2-77b22635c0b6.png)
![1555048000(1)](https://user-images.githubusercontent.com/1725360/56014837-6faa8800-5d29-11e9-98ae-53ad73103575.png)
![1555048046(1)](https://user-images.githubusercontent.com/1725360/56014863-8a7cfc80-5d29-11e9-9d99-4e460ea50910.png)

**Comment by Ultraman95** [comment]
libz.so也是同样的问题，我的lua文件就是add_links("curl") , add_links("z")
按道理：
libcurl.so.4 -> libcurl.so.4.5.0
libz.so.1 -> libz.so.1.2.11
这两个软连接可以不要
--------------------------------------

如果去掉，重新xmake build，结果是这样：
![1555048340(1)](https://user-images.githubusercontent.com/1725360/56015084-53f3b180-5d2a-11e9-85b1-a8c93b7899b4.png)
直接找系统的了，没有在我的环境下找

**Comment by Ultraman95** [comment]
所以，我感觉libcurl和libz这两个库，虽然lua脚本里面写的是
add_links("curl") , add_links("z")
，但是寻找的依然是libcurl.so.4,libz.so.1

**Comment by waruqi** [comment]
可加 xmake -v 参数 查看实际的 链接参数，如果链接的库 没满足自己实际的 搜索目录，可自行通过 add_linkdirs 添加控制

默认追加的搜索目录 -L/usr/local/lib -L/usr/lib 其他xmake不会做额外的处理。。

**Comment by Ultraman95** [comment]
我用了add_linkdirs的

**Comment by Ultraman95** [comment]
xmake project -k makefile

里面有一行：
qmarket_LD=-L../../library/lib/linux -s -fvisibility=hidden -lssl -lcrypto -lrdkafka++ -lrdkafka -luv -lz -lcurl -lpthread -m64 -L/usr/local/lib -L/usr/lib

**Comment by Ultraman95** [comment]
qmarket_LD=-L../../library/lib/linux
这个就是add_linkdirs产生的效果

**Comment by waruqi** [comment]
你可以自己敲 xmake -v -r 编译，获取详细的链接命令，然后复制出来，手动执行 ，不断调整参数来调试验证。。

这边只负责处理 xmake.lua相关使用上的问题，像这种都是开发者自己配置的事情，你自己调试下吧。。

手动敲gcc完整链接命令调通后，再调整下相关xmake.lua就好了。
