### ISSUE TITLE
qt moc 生成 不会 包含 add_deps 里面 的 includedirs 

### ISSUE THREAD

**Issue by zhuizhubf** [xmake-io/xmake#3930]
### Xmake 版本

xmake v2.7.9+HEAD.c87922676

### 操作系统版本和架构

Window10

### 描述问题

qt moc 生成 不会 包含 add_deps 里面 的 public  includedirs 

在 工程目录手动依赖就可以使用了
```
add_includedirs("$(projectdir)/src/libs/sdk")
```
但是这个在 sdk 里面 使用  
```
add_includedirs("sdk", {public = true})
```
导出了

### 期待的结果

不加入 
```
add_includedirs("$(projectdir)/src/libs/sdk")
```
可以 正常生成

### 工程配置

```
add_deps("libsdk")
```

### 附加信息和错误日志

缺失 include 导致的

**Comment by waruqi** [comment]
再试试 https://github.com/xmake-io/xmake/pull/3933

```
xmake update -s github:xmake-io/xmake#moc
```

**Comment by zhuizhubf** [comment]
测试没问题了
