### ISSUE TITLE
Repositories being used even when package is marked as system

### ISSUE THREAD

**Issue by brano543** [xmake-io/xmake#3938]
### Xmake Version

2.7.9

### Operating System Version and Architecture

Ubuntu 22.04.2 LTS

### Describe Bug

Hello,

I am trying to use Nix and xmake command to build my project. Everything works well as long as I don't specify a dependency. Once a dependency is specified, xmake is trying to clone remote github repositories. Since Nix is expecting all dependencies to be built by Nix, it won't allow call to git clone command.

Is it possible to disable this feature completely?

updating repositories .. error: Cloning into 'HOME/.config/.xmake/repositories/build-artifacts'...
       > fatal: unable to access 'https://github.com/xmake-mirror/build-artifacts.git/': Could not resolve host: github.com

### Expected Behavior

Once dependency is defined as
add_requires("pkgconfig::fmt", {system = true})

no update of repositories should happen as I am marking the dependency as system one.

### Project Configuration

add_rules("mode.release", "mode.debug")
set_languages("c++20")

add_requires("pkgconfig::fmt", {system = true})

target("cpp_training")
    set_kind("binary")
    add_files("src/main.cpp", "src/foo.cppm")

### Additional Information and Error Logs

```
cpp-examples> unpacking sources
cpp-examples> unpacking source archive /nix/store/2lfxyk14ryxcjihxgzz3a0a3hd6imqjh-nfqx35my58f9yyyn0y46p16dmqj9cr60-source
cpp-examples> source root is nfqx35my58f9yyyn0y46p16dmqj9cr60-source
cpp-examples> patching sources
cpp-examples> configuring
cpp-examples> checking for architecture ... x86_64
cpp-examples> updating repositories .. error: Cloning into 'HOME/.config/.xmake/repositories/build-artifacts'...
cpp-examples> fatal: unable to access 'https://github.com/xmake-mirror/build-artifacts.git/': Could not resolve host: github.com
cpp-examples> 
error: builder for '/nix/store/98fpghvpbjdkkim9lay5ngg1rwndkxpb-cpp-examples-0.1.0.drv' failed with exit code 255;
       last 9 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/2lfxyk14ryxcjihxgzz3a0a3hd6imqjh-nfqx35my58f9yyyn0y46p16dmqj9cr60-source
       > source root is nfqx35my58f9yyyn0y46p16dmqj9cr60-source
       > patching sources
       > configuring
       > checking for architecture ... x86_64
       > updating repositories .. error: Cloning into 'HOME/.config/.xmake/repositories/build-artifacts'...
       > fatal: unable to access 'https://github.com/xmake-mirror/build-artifacts.git/': Could not resolve host: github.com
       > 
       For full logs, run 'nix log /nix/store/98fpghvpbjdkkim9lay5ngg1rwndkxpb-cpp-examples-0.1.0.drv'.
```

**Comment by waruqi** [comment]
xmake g --network=private
