### ISSUE TITLE
Allow os.execv() to return non zero with option.

### ISSUE THREAD

**Issue by DIG-** [xmake-io/xmake#3943]
### Is your feature request related to a problem? Please describe.

I've trying to use xmake macro to run and report tests in CI.
The biggest issue is that if `os.execv()` fails, the macro entirely stops.
Basically I want something like a shell script but one cross-platform.

### Describe the solution you'd like

Lets assume macro `ci-test`:
`xmake macro ci-test --target test-xxx`
```lua
local target = option.get("target")
local ret = os.exec("xmake b " .. target)
if ret ~= 0 then
    -- notify test build failed
    return
end
ret = os.exec("xmake r " .. target)
if ret ~= 0 then
    -- notify test runtime error
   return
end
-- notify test passed
```

**Comment by waruqi** [comment]
```lua
local ok = try { function () os.exec("xmake b " .. target); return true end }
if not ok then
    -- ...
end
```

**Comment by DIG-** [comment]
Wow! I've searched for try-catch in lua, but it seems that is handled with `pcall()`. I tryied `pcall()` but
```error: global 'pcall' is not callable (a nil value)```

Maybe it will be good to mention the existence of this try block in documentation.
Thank you!

**Comment by waruqi** [comment]
> Maybe it will be good to mention the existence of this try block in documentation.

https://xmake.io/#/manual/builtin_modules?id=try-catch-finally
