### ISSUE TITLE
无法彻底卸载

### ISSUE THREAD

**Issue by Bit0r** [xmake-io/xmake#3948]
### Xmake 版本

v2.7.9+20230711

### 操作系统版本和架构

Ubuntu 22.04

### shell环境

fish

### 描述问题

操作步骤如下

1. 使用`curl -fsSL https://xmake.io/shget.text | bash`命令全新安装`xmake`
2. 不更改任何配置文件
3. 使用`xmake update --uninstall`卸载`xmake`
4. 终端打印`uninstall ok!`，卸载已经完成
5. `~/.local/bin/`目录下依旧有`xmake`和`xrepo`两个文件
6. 使用`apt`包管理方式安装`xmake`
7. `xmake`命令仍然使用`~/.local/bin/xmake`，因为用户目录的优先级更高

### 期待的结果

卸载命令应该删除`~/.local/bin/`目录下的`xmake`和`xrepo`两个文件

### 工程配置

从全新状态安装

### 附加信息和错误日志

没有其它错误

**Comment by waruqi** [comment]
```console
ruki-2:xmake ruki$ ls ~/.local/share/xmake/
actions         modules         rules           toolchains
core            platforms       scripts
includes        plugins         templates
languages       repository      themes
ruki-2:xmake ruki$ ls ~/.local/bin/xmake
/Users/ruki/.local/bin/xmake
ruki-2:xmake ruki$ xmake update --uninstall
uninstall ok!
ruki-2:xmake ruki$ ls ~/.local/bin/xmake
ls: /Users/ruki/.local/bin/xmake: No such file or directory
ruki-2:xmake ruki$ ls ~/.local/share/xmake/
ls: /Users/ruki/.local/share/xmake/: No such file or directory
ruki-2:xmake ruki$
```

可以的么

**Comment by waruqi** [comment]
> 使用curl -fsSL https://xmake.io/shget.text | bash命令全新安装xmake
不更改任何配置文件

没有执行 `source ~/.xmake/profile`？ 那应该还是用的 apt 安装的。。先执行下，切到脚本安装版本再试试

**Comment by Bit0r** [comment]
Linux平台下一般会把`~/.local/bin`加入PATH，本地的优先级会更高

**Comment by waruqi** [comment]
> Linux平台下一般会把`~/.local/bin`加入PATH，本地的优先级会更高

你执行 `xmake l os.programdir` 和 `xmake l os.programfile` 看下输出

**Comment by Bit0r** [comment]
fish下运行：
- `xmake l os.programdir`: 返回255错误码，没有任何输出
- `xmake l os.programfile`: 返回255错误码，没有任何输出
- `which xmake`: `/home/bit0r/.local/bin/xmake`

bash下运行：
- `xmake l os.programdir`: 没有任何输出
- `xmake l os.programfile`: 没有任何输出
- `which xmake`: `/home/bit0r/.local/bin/xmake`

手动删除`~/.local/bin/xmake`和`~/.local/bin/xrepo`之后：
- `xmake l os.programdir`: `"/usr/share/xmake"`
- `xmake l os.programfile`: `"/usr/bin/xmake"`
- `which xmake`: `/usr/bin/xmake`

**Comment by Bit0r** [comment]
`~/.local/share/xmake/`不存在，应该已经被删除了。卸载程序应该就只留下了`~/.local/bin/xmake`和`~/.local/bin/xrepo`这两个二进制文件。

**Comment by waruqi** [comment]
> `~/.local/share/xmake/`不存在，应该已经被删除了。卸载程序应该就只留下了`~/.local/bin/xmake`和`~/.local/bin/xrepo`这两个二进制文件。

~/.local/share/xmake/ 没这个目录,xmake 跑不起来的，也就没法继续卸载其他的东西。。

**Comment by Bit0r** [comment]
这个目录是卸载程序自动删除的，不是我手动删除的。
代码里面可以直接加入shell命令`rm ~/.local/bin/{xmake,xrepo}`来删除文件吗？

**Comment by waruqi** [comment]
> 这个目录是卸载程序自动删除的，不是我手动删除的。 代码里面可以直接加入shell命令`rm ~/.local/bin/{xmake,xrepo}`来删除文件吗？

原本就会删，并且我这正常，没问题。。

先脚本重装 恢复所有文件。。确认脚本正常，重新删一遍。。定位问题原因。。

或者自己调下脚本

https://github.com/xmake-io/xmake/blob/7939d750e9dcd51b5bac3e4f4a7ead5a81b2bed0/xmake/actions/update/main.lua#L161

**Comment by Bit0r** [comment]
应该和系统有关，你应该不是Linux系统？

**Comment by waruqi** [comment]
```
ruki@26ffdcdd0127:/tmp/test$ xmake update --uninstall
uninstall ok!
ruki@26ffdcdd0127:/tmp/test$ ls ~/.local/bin/xmake
ls: cannot access '/home/ruki/.local/bin/xmake': No such file or directory
ruki@26ffdcdd0127:/tmp/test$ ls ~/.local/share/xmake
ls: cannot access '/home/ruki/.local/share/xmake': No such file or directory
```

linux 也正常

**Comment by waruqi** [comment]
暂时无法复现。
