### ISSUE TITLE
Better integration of xmake dependencies for xmake packages

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#3952]
### Is your feature request related to a problem? Please describe.

Libraries using xmake are not very well integrated within xrepo, and this can lead to issues.

For example, let's consider a library using fmt:
```lua
add_requires("fmt")

target("nzsl")
  add_packages("fmt")
  ...
```

and turn it into a package:
```lua
package("nzsl")
  add_deps("fmt")

  on_install(function (package)
    import("package.tools.xmake").install(package)
  end)
```

the package can be used with
```lua
add_requires("nzsl")
```

this poses no problem.

However, if a user wants to change fmt settings (make it header_only for example)
```lua
add_requireconfs("nzsl.fmt", { configs = { header_only = true } })
```

This will make the package install fmt header_only, but when it will run `on_install` it will trigger `xmake config` on the library script which contains only `add_requires("fmt")`, installing regular fmt.

This causes link error and has happened to a user of my library earlier.

### Describe the solution you'd like

I think xmake should pass libraries config or even install dir to the installation script, for example:
```lua
package("nzsl")
  add_deps("fmt")

  on_install(function (package)
    import("package.tools.xmake").install(package)
  end)
```

would install fmt and then run `xmake config --installdir_fmt=~/.xmake/packages/f/fmt/v10.0.0/738a1e07d397408bbb6fc6518b3f8757`, making the internal script use this installdir over its own config.

**Comment by waruqi** [comment]
When I have time, I'll consider improving it.

**Comment by waruqi** [comment]
try it again .https://github.com/xmake-io/xmake/pull/4088

**Comment by waruqi** [comment]
If the same dependency has add_requireconfs internally, it should take precedence over the internal one.

**Comment by SirLynix** [comment]
But if I use 
`add_requireconfs("*", { configs = { is_mode("debug") }})` in my library xmake.lua, and that PR adds `add_requireconfs("fmt", { ... })`, won't that trigger a "package(fmt) will match multiple add_requireconfs" error?

**Comment by waruqi** [comment]
No, add_requireconfs can be called multiple times to duplicate configuration for the same dependency, or it can be called each time to append some configuration.

**Comment by SirLynix** [comment]
When I write
```lua
add_rules("mode.debug", "mode.release")

add_requires("fmt")

add_requireconfs("*", { debug = false })
add_requireconfs("fmt", { debug = true })

target("pkgtest")
    set_kind("binary")
    add_files("src/main.cpp")
```

I get
```
C:\Projets\Perso\Tests\test_pkg2>xmake f
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2022
error: package(fmt) will match multiple add_requireconfs(* fmt)!
```

Here's the same happening with packages on dev branch:
```
C:\Projets\Perso\Tests\test_pkg2>xmake f -c
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2022
note: install or modify (m) these packages (pass -y to skip confirm)?
  -> pkg_test latest [vs_runtime:"MT"]
please input: y (y/n/m)
y
  => install pkg_test latest .. failed

checking for Microsoft Visual Studio (x64) version ... 2022
error: package(fmt) will match multiple add_requireconfs(fmt *)!
if you want to get more verbose errors, please see:
  -> C:\Users\lynix\AppData\Local\.xmake\cache\packages\2308\p\pkg_test\latest\installdir.failed\logs\install.txt
error: install failed!
```

Also, I think this line is wrong
```lua
        if requireinfo and (requireinfo.override or (requireinfo.configs and #requireinfo.configs > 0)) then
```
(in package.tools.xmake.lua:399)
because requireinfo.configs is not an array, it should be checked using `not table.empty(requireinfos.configs)`

```lua
        if requireinfo and (requireinfo.override or not table.empty(requireinfos.configs)) then
```

**Comment by SirLynix** [comment]
Here's my test script:
```lua
package("pkg_test")
    add_deps("fmt")

    on_install(function (package)
        io.writefile("test.h", [[
            #pragma once
            void Print();
        ]])
        io.writefile("test.cpp", [[
            #include <fmt/format.h>
            void Print()
            {
                fmt::println("Hello xmake");
            }
        ]])
        io.writefile("xmake.lua", [[
            add_rules("mode.debug", "mode.release")

            add_requires("fmt")
            add_requireconfs("*", { debug = is_mode("debug") })

            target("pkg_test")
                set_kind("static")
                add_headerfiles("test.h")
                add_files("test.cpp")
                add_packages("fmt")
        ]])
        import("package.tools.xmake").install(package)
    end)
package_end()

add_rules("mode.debug", "mode.release")

add_requires("pkg_test")

add_requireconfs("pkg_test.fmt", { override = true, configs = { debug = false } }) --override shouldn't be required here?

target("radio")
    set_kind("binary")
    add_files("src/main.cpp")
```

**Comment by waruqi** [comment]
> because requireinfo.configs is not an array, it should be checked using not table.empty(requireinfos.configs)

I have fixed it.

>  add_requireconfs("fmt", { ... }), won't that trigger a "package(fmt) will match multiple add_requireconfs" error?

I will improve it, maybe we can merge these configs.

**Comment by waruqi** [comment]
I have improved it. https://github.com/xmake-io/xmake/pull/4092

If the same dependency is matched to multiple configurations, the configurations are merged by default, and if override is set, then it rewrites the previous configurations.

And I added `package.xmake.pass_depconfs` policy, we can also disable pass depconfs.

**Comment by waruqi** [comment]
Does it work now?

**Comment by SirLynix** [comment]
Yes thank you, I tested it with my script and it does work!

**Comment by waruqi** [comment]
This feature seems to have stopped working.; it cannot synchronize dependency versions. You can try this patch.

https://github.com/xmake-io/xmake/pull/7041
