### ISSUE TITLE
2.8.1 版本 windows 上 efsw cmake 包安装失败

### ISSUE THREAD

**Issue by SaeruHikari** [xmake-io/xmake#3953]
### Xmake Version

v2.8.1

### Operating System Version and Architecture

Windows 11 22H2

### Describe Bug

https://github.com/SakuraEngine/SakuraEngine/actions/runs/5517897034/jobs/10061141350#step:11:3302
更新 v2.8.1 后 windows 上安装 efsw 包出现 cmake compiler 内置失败，回退 v2.7.9 后成功。

### Expected Behavior

能正常安装 efsw 包

### Project Configuration

``` lua
add_rules("mode.debug", "mode.release")
add_requires("efsw")

target("xmake-test")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("efsw")
```

### Additional Information and Error Logs

https://github.com/SakuraEngine/SakuraEngine/actions/runs/5517897034/jobs/10061141350#step:11:3302

**Comment by waruqi** [comment]
这块好像没怎么改过。。而且它这个错误也有点怪。。像是路径乱了

>  "C:/Program Files/CMake/bin/cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles/cmTC_c0243.dir/testCCompiler.c.obj.d --working-dir=D:/a/SakuraEngine/xmake-global/.xmake/cache/packages/2307/e/efsw/1.3.1/source/build_ff652845/CMakeFiles/CMakeScratch/TryCompile-vfqnob --filter-prefix="Note: including file: " -- "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.35.32215/bin/HostX64/x64/cl.exe"  /nologo   /DWIN32 /D_WINDOWS  /Zi /Ob0 /Od /RTC1 -MDd /showIncludes /FoCMakeFiles/cmTC_c0243.dir/testCCompiler.c.obj /FdCMakeFiles/cmTC_c0243.dir/ /FS -c D:/a/SakuraEngine/xmake-global/.xmake/cache/packages/2307/e/efsw/1.3.1/source/build_ff652845/CMakeFiles/CMakeScratch/TryCompile-vfqnob/testCCompiler.c
    Microsoft (R) C/C++ Optimizing Compiler Version 19.35.32217.1 for x64
    Copyright (C) Microsoft Corporation.  All rights reserved.
    
>    cl : Command line warning D9024 : unrecognized source file type 'C:/Program Files/Git/nologo', object file assumed
    cl : Command line warning D9027 : source file 'C:/Program Files/Git/nologo' ignored

**Comment by SaeruHikari** [comment]
对，看上去没有找到文件的路径，只传进去了一堆 flag

**Comment by waruqi** [comment]
而且，https://github.com/xmake-io/xmake/issues/3912 里你用的 dev 版本，跟现在 2.8.1 也没差几天，期间没改过 cmake 这块。。之前 dev 不是好好的么

**Comment by waruqi** [comment]
你开下 -vD 对比下 2.7.9 和 2.8.1 的安装输出呢，看下有啥区别

**Comment by SaeruHikari** [comment]
#3912 那会确实没问题，而且我印象里也没走包缓存，但是在一个已经删了的分支上做的， CI 记录有点远，找不到了。

**Comment by SaeruHikari** [comment]
> 你开下 -vD 对比下 2.7.9 和 2.8.1 的安装输出呢，看下有啥区别

稍等我合并个 PR，过后新开两个分支对比下。

**Comment by SaeruHikari** [comment]
`2.8.1`
https://github.com/SakuraEngine/SakuraEngine/actions/runs/5518255218/jobs/10061958843#step:11:3687

`2.7.9`
https://github.com/SakuraEngine/SakuraEngine/actions/runs/5518248901/jobs/10061944342#step:11:3719

**Comment by waruqi** [comment]
是有次 commit 不小心带入了一个测试 patch ，我 revert 了。。等 ci 过了，你再切到 dev 试试，如果 ok，我明天再发个版本。

https://github.com/xmake-io/xmake/commit/b7a82a2e449133752cca5cee2349180371999373

**Comment by waruqi** [comment]
可以了么

**Comment by SaeruHikari** [comment]
稍等，我试一下

**Comment by SaeruHikari** [comment]
ok 了

**Comment by waruqi** [comment]
由于只影响 windows ，新版本就不用发，我直接更新了 releases 上的 windows 安装包，应该也能直接修复这个问题

不过安装包如果走的 jsdelivery 下在，有 cdn 缓存，完全生效得等到明天
