### ISSUE TITLE
EntryPointNotFoundException: luaLS_loadbuffer

### ISSUE THREAD

**Issue by libyyu** [xmake-io/xmake#396]
NDK编译so，链接静态库的时候，如何导出所有符号啊。

**Comment by waruqi** [comment]
默认mode.release模式会禁止导出所有符号

因为里面设置了 set_symbols("hidden")

你可以显式导出指定符号

https://github.com/xmake-io/xmake/blob/85cb688e30f996c5ac1036ec99b6c7c1a45cb035/tests/projects/c/shared_library/src/interface.h#L8

或者你在xmake.lua里面重新设置

set_symbols("none")

复写下
