### ISSUE TITLE
不支持生成vs2008的工程

### ISSUE THREAD

**Issue by setoutsoft** [xmake-io/xmake#3972]
### Xmake 版本

2.8.1

### 操作系统版本和架构

win10

### 描述问题

使用xmake生成vs2008的工程，生成的工程不能用。

### 期待的结果

希望可以兼容vs2008

### 工程配置

最简单的demo都不行。

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
```
xmake project -k vs2008
```

原本就是支持，如果不行，详细提供错误信息和截图。。光说不能用，我哪知道怎么回事。。

另外我这没 2008 ，建议自己调试下，对比 vs2008 自己生成的工程，排查原因，可以提 pr 过来

**Comment by setoutsoft** [comment]
找一个空目录。执行下面几条指令：
xmake create -l c++ -t console myproject
cd myproject
xmake project -k vs2008
然后用vs2008打开工程。
在source files下会有两个main.cpp文件
编译提示：
1>------ 已启动生成: 项目: myproject, 配置: release Win32 ------
1>正在编译...
1>main.cpp
1>正在编译资源清单...
1>Microsoft (R) Windows (R) Resource Compiler Version 6.1.6723.1
1>Copyright (C) Microsoft Corporation.  All rights reserved.
1>正在链接...
1>LINK : warning LNK4075: 忽略“/INCREMENTAL”(由于“/OPT:ICF”规范)
1>..\..\build\.objs\myproject\windows\x64\release\src\main.cpp.obj : fatal error LNK1112: 模块计算机类型“X86”与目标计算机类型“x64”冲突
打开生成的vcproj文件，发现files节点是这样的：
`<Files>
		<Filter Name="Source Files">
			<File
				RelativePath="..\..\src\main.cpp"
				>
				<FileConfiguration
					Name="release|Win32"
					>
					<Tool
						Name="VCCLCompilerTool"
						AdditionalOptions="-nologo -O2 -fp:fast /EHsc -DNDEBUG"
						ObjectFile="..\..\build\.objs\myproject\windows\x64\release\src\main.cpp.obj"
					/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="..\..\src\main.cpp"
				>
				<FileConfiguration
					Name="release|Win32"
					>
					<Tool
						Name="VCCLCompilerTool"
						AdditionalOptions="-nologo -O2 -fp:fast /EHsc -DNDEBUG"
						ObjectFile="..\..\build\.objs\myproject\windows\x64\release\src\main.cpp.obj"
					/>
				</FileConfiguration>
			</File>
		</Filter>
		<Filter Name="Resource Files">
		</Filter>
	</Files>`

**Comment by waruqi** [comment]
vs200x 的 project generator 基本不怎么维护了，仅支持生成 x86 的工程，强行切到 x86 试下。。

```console
xmake f -a x86 -c
xmake project -a x86 -k vs2008
```

**Comment by setoutsoft** [comment]
> vs200x 的 project generator 基本不怎么维护了，仅支持生成 x86 的工程，强行切到 x86 试下。。
> 
> ```
> xmake f -a x86 -c
> xmake project -a x86 -k vs2008
> ```

测试过了，结果一样。
可能很多人不用vs2008了，不过在我看来vs2008有很多vs2010+没有的优点：
1、安装包体积小。
2、编译生成的包体积小。
3、编译速度很快。
4、编辑器占用内存小。
5、配合VA，代码导航很方便。（新版本VS的VA不好用）
6、还有离线msdn
除了不支持c11, 我个人看到的都是优点。
希望作者可以完善vs2008的支持。

**Comment by waruqi** [comment]
> > vs200x 的 project generator 基本不怎么维护了，仅支持生成 x86 的工程，强行切到 x86 试下。。
> > ```
> > xmake f -a x86 -c
> > xmake project -a x86 -k vs2008
> > ```
> 
> 测试过了，结果一样。 可能很多人不用vs2008了，不过在我看来vs2008有很多vs2010+没有的优点： 1、安装包体积小。 2、编译生成的包体积小。 3、编译速度很快。 4、编辑器占用内存小。 5、配合VA，代码导航很方便。（新版本VS的VA不好用） 6、还有离线msdn 除了不支持c11, 我个人看到的都是优点。 希望作者可以完善vs2008的支持。

我现在的自己都已经装不上2008了。。没法测试，你可以提 pr 过来改进

**Comment by setoutsoft** [comment]
看了一下xmake的lua脚本，我只能表示无能为力。
