### ISSUE TITLE
CUDA debug flags in mode.debug

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#3978]
### 你在什么场景下需要该功能？

https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-altering-compiler-linker-behavior-device-debug

CUDA也有控制调试符号生成的选项，如 `--device-debug(-G)` 等，但xmake中mode.debug并未为cuda的符号提供支持

### 描述可能的解决方案

在各mode中也添加对应的cuda flag

### 描述你认为的候选方案

参考set_symbol("debug")，提供接口set_symbol("cuda.debug")

**Comment by waruqi** [comment]
直接 nvcc.lua 里面 debug -> -g -G 不就好了。可以提个 pr 过来
