### ISSUE TITLE
make install fails in msys2/mingw-w64 environment

### ISSUE THREAD

**Issue by Biswa96** [xmake-io/xmake#3982]
### Xmake Version

2.8.1

### Operating System Version and Architecture

Microsoft Windows Version 10.0.19045

### Describe Bug

`make install PREFIX="${pkgdir}${MINGW_PREFIX}"` command fails with the following error.

```
make: Entering directory '/f/test/MINGW-packages/mingw-w64-xmake/src/xmake-2.8.1'
installing build/xmake.exe to /f/test/MINGW-packages/mingw-w64-xmake/pkg/mingw-w64-ucrt-x86_64-xmake/ucrt64/bin
cp: cannot stat 'scripts/msys/xmake.sh': No such file or directory
make: *** [makefile:6194: install] Error 1
make: Leaving directory '/f/test/MINGW-packages/mingw-w64-xmake/src/xmake-2.8.1'
```

### Expected Behavior

Install files without any error.

### Project Configuration

¯\ (ツ)/¯

### Additional Information and Error Logs

¯\ (ツ)/¯

**Comment by waruqi** [comment]
I fixed it in the next version.

https://github.com/xmake-io/xmake/commit/56bc58325b10e39b8278e81e1852997334716efb

**Comment by Biswa96** [comment]
Thank you for working on this issue.

Another thing I saw with new release. There is a duplicate $MINGW_PREFIX/share/xmake/xmake.exe file. Is that required or an known issue? I can provide CI log and further information.

**Comment by waruqi** [comment]
> $MINGW_PREFIX/share/xmake/xmake.exe

we need this file.

@see https://github.com/xmake-io/xmake/issues/3628

**Comment by waruqi** [comment]
> Thank you for working on this issue.
> 
> Another thing I saw with new release. There is a duplicate $MINGW_PREFIX/share/xmake/xmake.exe file. Is that required or an known issue? I can provide CI log and further information.

There is indeed something wrong here and I will try to fix it.

```console
cp build/xmake.exe /mingw64/bin/xmake.exe
cp scripts/msys/xmake.sh /mingw64/bin/xmake    ----> it will override /mingw64/bin/xmake.exe
cp build/xmake.exe /mingw64/share/xmake/xmake.exe
```

=> 

```console
cp scripts/msys/xmake.sh /mingw64/bin/xmake
cp build/xmake.exe /mingw64/share/xmake/xmake.exe
```

**Comment by Biswa96** [comment]
Thank you for working on it. Recently, a bin -> share directory relocation was fixed with scrcpy package in msys2, here https://github.com/msys2/MINGW-packages/commit/5f6f03465e5d931e489ab83a5cea7d75d8d6994c. I hope it may help here also.

**Comment by waruqi** [comment]
> Thank you for working on it. Recently, a bin -> share directory relocation was fixed with scrcpy package in msys2, here [msys2/MINGW-packages@5f6f034](https://github.com/msys2/MINGW-packages/commit/5f6f03465e5d931e489ab83a5cea7d75d8d6994c). I hope it may help here also.

Thanks, but It's not the same problem as us. I need to fix the CreateProcess implicit search path issue. https://github.com/xmake-io/xmake/issues/3628
