### ISSUE TITLE
在target的after_build中，调用os.exec出现Permission Denined

### ISSUE THREAD

**Issue by rocketman123456** [xmake-io/xmake#3984]
### Xmake 版本

xmake v2.8.1+dev.732d60063

### 操作系统版本和架构

Win11

### 描述问题

c++ 项目中在编译完成后的after_build步骤中，需要调用编译生成的exe文件进行后续处理，在使用os.exec调用指令后，返回Permission Denined错误，无法继续运行。单独将命令拿出来可以在命令行执行，切换到D盘E盘无法执行。

### 期待的结果

可以正常调用exec

### 工程配置

[ArchViz-xmake](https://github.com/rocketman123456/ArchViz-xmake)

```
target("meta_parser", function ()
    set_kind("binary")
    add_headerfiles("parser/**.h")
    add_files("parser/**.cpp")
    add_includedirs("$(projectdir)/engine/3rd_party/mustache")
    add_includedirs("$(projectdir)/engine/3rd_party/llvm_lib/include")
    add_includedirs("$(projectdir)/engine/src/meta_parser/parser")
    if is_plat("windows") then 
        add_linkdirs("$(projectdir)/engine/3rd_party/llvm_lib/lib/windows")
        add_links("libclang")
    elseif is_plat("macos") then 
        add_linkdirs("$(projectdir)/engine/3rd_party/llvm_lib/lib/macos")
        add_links("libclang")
    elseif is_plat("linux") then 
        add_linkdirs("$(projectdir)/engine/3rd_party/llvm_lib/lib/linux")
        add_links("libclang")
    end
    on_load(function (target)
        if is_plat("linux", "macosx") then
            target:add("links", "pthread", "m", "dl")
        end
    end)
    after_build(function (target)
        import("core.project.config")
        local targetfile = target:targetfile()
        os.mkdir("$(projectdir)/bin/tool")
        os.cp(targetfile, path.join("$(projectdir)/bin/tool", path.filename(targetfile)))
        print("build %s", targetfile)

        print("*************************************************************")
        print("**** [Precompile] Begin ")
        print("*************************************************************")
        print("")

        local params = "\"$(projectdir)/engine/src/runtime\""
        local ipnut = "\"$(projectdir)/build/parser_header.h\""
        local source_dir = "\"$(projectdir)/engine/src\""
        local include_dir = "*"
        if is_plat("linux") then
            include_dir = "/usr/include/c++/9/"
        elseif is_plat("macosx") then
            include_dir = os.getenv("osx_sdk_platform_path_test").."/../../Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1"
        end
        local namespace = "ArchViz"
        local opt = 0

        -- project_input_src include_file_path include_path include_sys module_name is_show_errors
        local cmd= ". $(projectdir)/bin/tool/meta_parser.exe " .. params .. " " .. ipnut .. " " .. source_dir .. " " .. include_dir .. " " .. namespace .." 0"
        print(cmd)
        -- os.exec(cmd);

        print("*************************************************************")
        print("**** [Precompile] Finish ")
        print("*************************************************************")
        print("")
    end)
end)
```

### 附加信息和错误日志

error: ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:56: cannot exec(. C:\Users\RoccketSky\Desktop\Engine\ArchViz-xmake/bin/tool/meta_parser.exe "C:\Users\RoccketSky\Desktop\Engine\ArchViz-xmake/engine/src/runtime" "C:\Users\RoccketSky\Desktop\Engine\ArchViz-xmake/build/parser_header.h" "C:\Users\RoccketSky\Desktop\Engine\ArchViz-xmake/engine/src" "*" "ArchViz" 0), Permission denied
stack traceback:
        @programdir\core\base\utils.lua:290: in function <@programdir\core\base\utils.lua:280>
        [C]: in function 'error'
        @programdir\core\base\os.lua:913: in function 'os.raiselevel'
        (...tail calls...)
        ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:56: in field 'co_start_withopt'
        @programdir\modules\private\async\runjobs.lua:217: in function <@programdir\modules\private\async\runjobs.lua:162>
        [C]: in function 'xpcall'
        @programdir\core\base\utils.lua:280: in function 'sandbox/modules/utils.trycall'
        @programdir\core\base\scheduler.lua:520: in function 'base/scheduler.co_group_begin'
        ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:94: in field 'co_group_begin'
        @programdir\modules\private\async\runjobs.lua:162: in function <@programdir\modules\private\async\runjobs.lua:56>
        (...tail calls...)
        @programdir\actions\build\build.lua:259: in function <@programdir\actions\build\build.lua:247>
        (...tail calls...)
        @programdir\actions\build\main.lua:109: in global '_do_build'
        @programdir\actions\build\main.lua:180: in function <@programdir\actions\build\main.lua:173>
        [C]: in function 'xpcall'
        @programdir\core\base\utils.lua:280: in function 'sandbox/modules/utils.trycall'
        @programdir\core\sandbox\modules\try.lua:117: in global 'try'
        @programdir\actions\build\main.lua:171: in function <@programdir\actions\build\main.lua:133>
        (...tail calls...)
        [C]: in function 'xpcall'
        @programdir\core\base\utils.lua:280: in function 'sandbox/modules/utils.trycall'
        (...tail calls...)
        @programdir\core\base\task.lua:501: in function 'base/task.run'
        @programdir\core\main.lua:298: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>

**Comment by waruqi** [comment]
> local cmd= ". $(proje
> cannot exec(.

你加个 `.` 干嘛，这个能执行成功就怪了。

**Comment by rocketman123456** [comment]
> > local cmd= ". $(proje
> > cannot exec(.
> 
> 你加个 `.` 干嘛，这个能执行成功就怪了。

谢谢，在windows测试可以正常运行了。因为在命令行执行指令有这个也可以运行，我就以为在lua中也是这样。我调整一下配置在linux中也测试一下
