### ISSUE TITLE
改动 PCH 内的头会错误地连续触发两次不完整的增量构建

### ISSUE THREAD

**Issue by SaeruHikari** [xmake-io/xmake#3988]
### Xmake 版本

2.8.1

### 操作系统版本和架构

Windows11 22H2

### 描述问题

改动 PCH 包含的头时（例如 pch.hpp 包含了 A.hpp，我改动了 A.hpp），会在接下来的两次构建中都触发增量：
- 第一次会触发 PCH 本身的构建（不一定会触发包含 PCH 的源文件的构建）；
- 第二次会触发 PCH 相关的所有源文件的构建。

![image](https://github.com/xmake-io/xmake/assets/39457738/30ceb037-ebb0-43c7-9632-e4a09e2c476b)

### 期待的结果

改动 PCH 包含的头时，在下一次构建时，先触发 PCH 本身的构建，之后构建源文件。

### 工程配置

最小工程：[xmake-test.zip](https://github.com/xmake-io/xmake/files/12130014/xmake-test.zip)

### 附加信息和错误日志

两次构建的日志：

PS D:\xmake-test> xmake -j22 -vD
[ 11%]: compiling.debug build\.gens\xmake-test\windows\x64\debug\src\pch.hpp
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\cl.exe" -c -Yc -nologo -Zi -FS -Fdbuild\windows\x64\debug\compile.xmake-test.pdb -Od -IA /EHsc -FIpch.hpp -TP -Fpbuild\.objs\xmake-test\windows\x64\debug\gens\src\cxx\pch.hpp.pch -Fobuild\.objs\xmake-test\windows\x64\debug\gens\src\cxx\pch.hpp.pch.obj build\.gens\xmake-test\windows\x64\debug\src\pch.hpp
[ 77%]: linking.debug xmake-test.exe
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\link.exe" -nologo -dynamicbase -nxcompat -machine:x64 -libpath:build\windows\x64\debug -debug -pdb:build\windows\x64\debug\xmake-test.pdb xmake-testA.lib -out:build\windows\x64\debug\xmake-test.exe build\.objs\xmake-test\windows\x64\debug\src\main.cpp.obj build\.objs\xmake-test\windows\x64\debug\src\td.cpp.obj build\.objs\xmake-test\windows\x64\debug\gens\src\cxx\pch.hpp.pch.obj

build cache stats:
cache directory: build\.build_cache
cache hit rate: 0%
cache hit: 0
cache miss: 0
new cached files: 0
remote cache hit: 0
remote new cached files: 0
preprocess failed: 0
compile fallback count: 0

[100%]: build ok, spent 0.766s
PS D:\xmake-test> xmake -j22 -vD
[ 22%]: compiling.debug src\main.cpp
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\cl.exe" -c -nologo -Zi -FS -Fdbuild\windows\x64\debug\compile.xmake-test.pdb -Od -IA /EHsc -Yupch.hpp -FIpch.hpp -Fpbuild\.objs\xmake-test\windows\x64\debug\gens\src\cxx\pch.hpp.pch -Fobuild\.objs\xmake-test\windows\x64\debug\src\main.cpp.obj src\main.cpp
[ 22%]: compiling.debug src\td.cpp
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\cl.exe" -c -nologo -Zi -FS -Fdbuild\windows\x64\debug\compile.xmake-test.pdb -Od -IA /EHsc -Yupch.hpp -FIpch.hpp -Fpbuild\.objs\xmake-test\windows\x64\debug\gens\src\cxx\pch.hpp.pch -Fobuild\.objs\xmake-test\windows\x64\debug\src\td.cpp.obj src\td.cpp
[ 77%]: linking.debug xmake-test.exe
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\link.exe" -nologo -dynamicbase -nxcompat -machine:x64 -libpath:build\windows\x64\debug -debug -pdb:build\windows\x64\debug\xmake-test.pdb xmake-testA.lib -out:build\windows\x64\debug\xmake-test.exe build\.objs\xmake-test\windows\x64\debug\src\main.cpp.obj build\.objs\xmake-test\windows\x64\debug\src\td.cpp.obj build\.objs\xmake-test\windows\x64\debug\gens\src\cxx\pch.hpp.pch.obj

build cache stats:
cache directory: build\.build_cache
cache hit rate: 0%
cache hit: 0
cache miss: 0
new cached files: 0
remote cache hit: 0
remote new cached files: 0
preprocess failed: 0
compile fallback count: 0

[100%]: build ok, spent 0.484s

**Comment by waruqi** [comment]
更新到 dev 再试试 xmake update -s dev

另外，测试前，先删下  build 目录，再测

**Comment by SaeruHikari** [comment]
OK 了
