### ISSUE TITLE
Pass build environment to support iphoneos/android/mingw package

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#399]
Pass build environment to the following build system
- [x] xmake
- [x] autotools (iphoneos, android, linux, macosx, mingw)
- [x] cmake
- [ ] scons
- [ ] meson 

References

https://github.com/xmake-io/xmake-repo/issues/12 Support for packages for iphoneos and android

**Comment by mwik** [comment]
Great! Just a question, how should we handle packages with custom build systems? Take for example openssl on iphoneos? Should the package on_install(...) detect iphone sdk and pass that on to the build script or is that information available somewhere within xmake so on_install() function can merely pass it on? I looked into the openssl case this weekend, but I could not find any detected SDK or toolchain paths within xmake itself, rather xcrun seems to be used directly. Have I understood correctly or am I missing something?

**Comment by waruqi** [comment]
> Great! Just a question, how should we handle packages with custom build systems? Take for example openssl on iphoneos? Should the package on_install(...) detect iphone sdk and pass that on to the build script or is that information available somewhere within xmake so on_install() function can merely pass it on? I looked into the openssl case this weekend, but I could not find any detected SDK or toolchain paths within xmake itself, rather xcrun seems to be used directly. Have I understood correctly or am I missing something?

We can call `get_config("xxx")` and `platform.get("xxx")` to get all build tools and flags from configuration and platform.

```lua
import("core.platform.platform")
local cc = get_config("cc")
local ld = get_config("ld")
local cflags = get_configs("cflags")
local ldflags = platform.get("cflags")
```

You can see

https://github.com/xmake-io/xmake/blob/85cb688e30f996c5ac1036ec99b6c7c1a45cb035/xmake/modules/package/tools/xmake.lua#L58-L60

And I will improve https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/tools/autoconf.lua to pass all build environment to autoconf.

```lua
    on_install("iphoneos", function (package)
        local configs = {"--enable-debug=yes"}
        import("package.tools.autoconf").install(package, configs)
    end)
```

**Comment by waruqi** [comment]
I have supported cross-compile libuv for iphoneos, android, you can see

https://github.com/xmake-io/xmake-repo/blob/134af635b7d385b335c10a038964e6817a0afb40/packages/l/libuv/xmake.lua#L36-L38

```lua
 on_install("macosx", "linux", "iphoneos", "android@linux,macosx", function (package)
        import("package.tools.autoconf").install(package, {"--enable-shared=no"})
 end)
```

https://github.com/xmake-io/xmake-repo/blob/134af635b7d385b335c10a038964e6817a0afb40/packages/z/zlib/xmake.lua#L23-L29

```lua
on_install("iphoneos", "android@linux,macosx", "mingw@linux,macosx", function (package)
        import("package.tools.autoconf").configure(package, {host = "", "--static"})
        io.gsub("Makefile", "\nAR=.-\n",      "\nAR=" .. (package:build_getenv("ar") or "") .. "\n")
        io.gsub("Makefile", "\nARFLAGS=.-\n", "\nARFLAGS=cr\n")
        io.gsub("Makefile", "\nRANLIB=.-\n",  "\nRANLIB=\n")
        os.vrun("make install -j4")
    end)
```

I improved https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/tools/autoconf.lua to pass all build environment to autoconf.

https://github.com/xmake-io/xmake/blob/43749aaefcce37ac729cfc995786612d124d2a3b/xmake/modules/package/tools/autoconf.lua#L25-L112

**Comment by waruqi** [comment]
Then I will support passing the build environment to other build systems, such as: cmake, meson, etc.
https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/tools/cmake.lua

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-repo/blob/master/PKGLIST.md

![image](https://user-images.githubusercontent.com/151335/56865128-63028100-6a05-11e9-8f12-8b1a201b8ede.png)

**Comment by waruqi** [comment]
We can pass mingw/iphoneos/android envs to autotools/cmake/xmake. It is enough now.
