### ISSUE TITLE
set_exceptions 设置为 none 的时候 cmake 无法正常工作

### ISSUE THREAD

**Issue by RimuruChan** [xmake-io/xmake#3993]
### Xmake 版本

v2.8.1+dev.732d60063

### 操作系统版本和架构

Windows 11

### 描述问题

原因是四个月前pr的这段代码没有处理none的情况，导致生成cmake代码中出现了错误片段，无法成功配置
![image](https://github.com/xmake-io/xmake/assets/42002296/79ed50bb-b99f-4b89-9575-0d72068c2bfb)
![image](https://github.com/xmake-io/xmake/assets/42002296/5d4bfc59-6c07-4c82-9444-1118c6db604c)

### 期待的结果

正常配置cmake

### 工程配置

add_rules("mode.debug", "mode.release")

target("proj")
    set_kind("binary")
    add_files("src/*.cpp")
    add_cxxflags("/UTF-8")
    set_languages("cxx20")
    set_exceptions("none")

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
merge 了
