### ISSUE TITLE
find_program函数找不到从xmake-repo的包里安装的程序

### ISSUE THREAD

**Issue by jingkaimori** [xmake-io/xmake#3997]
### Xmake 版本

2.8.1

### 操作系统版本和架构

Windows 10 22H2

### 描述问题

xmake-repo 的包可以安装可执行文件，`os.run`可以运行这些文件，但是`find_program`识别不到这些文件

### 期待的结果

`find_program`针对这些文件，返回对应的文件名

### 工程配置

```lua
add_requires("qtifw")
target("test")
    add_package("qtifw")
    on_install(function (target)
        find_program("binarycreator", {check=" --help"}) // returns nil
        os.run("binarycreator --help") // runs successfully
    end)
```

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
用 lib.detect.find_tool 不要直接用 find_program。。另外可以 print(os.getenv("PATH")) 看下当前的 PATH 有没有带上里面的bin path

**Comment by jingkaimori** [comment]
`find_tool`可以找到相应的程序
