### ISSUE TITLE
Qt Header not detect

### ISSUE THREAD

**Issue by kassane** [xmake-io/xmake#400]
I tested example of your project using widgets_qt, however when I tried to use it in my project to test it this error occurred:
**My project test:** [here](https://github.com/kassane/Movable-and-Resizeable-QWidgets)

**output:**
> error: sources\mainwindow.cpp:9:10: fatal error: headers/tcontainer.hpp: No such file or directory
>  #include "headers/tcontainer.hpp"
>           ^~~~~~~~~~~~~~~~~~~~~~~~

**script:**
```lua
-- add modes: debug and release 
add_rules("mode.debug", "mode.release")

set_languages("c99", "cxx17")

-- add target
target("qt_demo")

    -- add rules
    add_rules("qt.application")

    -- add headers
    --set_headerdir("$(pwd)/headers")
	add_headerfiles("headers/*.hpp")

    -- add files
    add_files("*.cpp", "sources/*.cpp") 

    -- add files with Q_OBJECT meta (only for qt.moc)
    add_files("headers/mainwindow.h") 

    -- add frameworks
    add_frameworks("QtWidgets")
```
I tried to see more information about the command ```add_headerfiles``` but content is in Chinese and I do not understand.
In fact, the ```set_language``` command does not change __cxx11__ to __cxx17__ or later.

**Comment by waruqi** [comment]
> In fact, the set_language command does not change cxx11 to cxx17 or later.

I have fixed this problem.

You can update dev branch version and try it again.

```lua
add_rules("mode.debug", "mode.release")

set_languages("c99", "cxx17")

-- add target
target("qt_demo")

    -- add rules
    add_rules("qt.application")

    -- add header files for `$xmake install`
    add_headerfiles("headers/*.hpp")

    -- add include search directories
    add_includedirs(".")

    -- add files
    add_files("*.cpp", "sources/*.cpp") 

    -- add files with Q_OBJECT meta (only for qt.moc)
    add_files("headers/mainwindow.h") 
    add_files("headers/tcontainer.hpp") 

    -- add frameworks
    add_frameworks("QtWidgets")
```
