### ISSUE TITLE
最新的 dev 版本在 VSCode 插件调试时没有反应

### ISSUE THREAD

**Issue by SaeruHikari** [xmake-io/xmake#4001]
### Xmake Version

v2.8.1 dev

### Operating System Version and Architecture

Windows 11 22H2

### Describe Bug

2023/7/24 下午一点下的 `dev` 还是好的 (那时候在调 pch 的 bug), 晚上回来八点多钟拉的 `dev` 版本出现此问题。

Extensions 上显示有 `Uncaught Error`, 定位在 `WorkspaceContainsXmake`。将 `xmake` 回退到 `release` 版本该问题不再复现。

### Expected Behavior

可以正常地在 VSCode 插件中选择目标并调试。

### Project Configuration

任意小工程即可复现。

### Additional Information and Error Logs

Extensions 上显示有 `Uncaught Error`, 定位在 `WorkspaceContainsXmake`。

**Comment by waruqi** [comment]
是这个 https://github.com/xmake-io/xmake/pull/3989 patch 改了一些 vscode 插件用到的模块导致，我插件里面兼容了。。更新下插件再试试

**Comment by SaeruHikari** [comment]
OK 了
