### ISSUE TITLE
xmake转为cmakelists时存在转换错误

### ISSUE THREAD

**Issue by limuy2022** [xmake-io/xmake#4006]
### Xmake 版本

v2.8.1+20230711

### 操作系统版本和架构

Archlinux

### 描述问题

我正在使用xmake的c++ module功能时，发现转换后的cmakelists包含一句没有输入文件的clang编译命令
```cmake
COMMAND /usr/local/bin/clang -Qunused-arguments -m64 -fPIC -g -Wall -Werror -O0 -std=c++23 -I${CMAKE_SOURCE_DIR}/src/include -DBUILD_language_DLL
```
这导致clang报错
```
clang: error: no input file
```

### 期待的结果

正常生成可编译的cmakelists

### 工程配置

target("Trc")
    set_kind("binary")
    add_files("src/**.cpp", "src/**.cppm", "language/**.cppm")
    add_subdirs("language")
    add_deps("language")

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
see https://github.com/xmake-io/xmake/issues/3642

**Comment by limuy2022** [comment]
好的，我明白了，看来还是要等cmake官方支持c++ module了，xmake才好做
