### ISSUE TITLE
Compiling c++ in termux

### ISSUE THREAD

**Issue by ghost** [xmake-io/xmake#4018]
### Xmake Version

2.8.1

### Operating System Version and Architecture

android version 9

### Describe Bug

When I try to compile a C/C++ project in termux I get the error: segmentation fault

### Expected Behavior

What is expected is to generate the executable

### Project Configuration

The project is the template generated by the command: xmake create <project>

### Additional Information and Error Logs

[ 25%]: cache compiling.release src/main.cpp
gcc -c -Qunused-arguments -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG -o build/.objs/test/linux/armv7a/release/src/main.cpp.o src/main.cpp
Segmentation fault

**Comment by waruqi** [comment]
it works for me.

![Screenshot_20230728_102046_com termux](https://github.com/xmake-io/xmake/assets/151335/fd8587ad-3e0b-49d7-9e1f-e1741db27708)

**Comment by LucasAlves015** [comment]
> it works for me.
> 
> ![Screenshot_20230728_102046_com termux](https://github.com/xmake-io/xmake/assets/151335/fd8587ad-3e0b-49d7-9e1f-e1741db27708)
>  
![Screenshot_20230727-234005.png](https://github.com/xmake-io/xmake/assets/122476524/7fd97253-d629-4560-99ac-30158b8f2b87)

**Comment by LucasAlves015** [comment]
> it works for me.
> 
> ![Screenshot_20230728_102046_com termux](https://github.com/xmake-io/xmake/assets/151335/fd8587ad-3e0b-49d7-9e1f-e1741db27708)
>  

![Screenshot_20230727-234005.png](https://github.com/xmake-io/xmake/assets/122476524/673b1385-4d73-44b6-8e4f-0bc0c9776063)

**Comment by paul-reilly** [comment]
Just for more information, I can confirm that it works here:

- Android 12
- arm64-v8a

**Comment by waruqi** [comment]
I have fixed it on dev. https://github.com/xmake-io/xmake/issues/5029
