### ISSUE TITLE
下载场景可以选择使用wget代替curl

### ISSUE THREAD

**Issue by veritas-Qiu** [xmake-io/xmake#4026]
### 你在什么场景下需要该功能？

当前版本下，使用xrepo下载依赖/xmake update等需要下载的命令时，如果宿主环境中同时有curl和wget，会使用curl进行下载
但我的使用环境配置了ipguard，curl将下载内容保存为文本后再改名，文本会触发ipguard的加密功能，导致下载下来的内容被加密，xmake后续的操作被中断，而且给ipguard增加了不必要的审计压力。使用wget没有这个问题

### 描述可能的解决方案

在.xmake中增加一个配置，允许用户指定curl或wget作为默认下载器

### 描述你认为的候选方案

目前通过修改modules/net/http/download.lua强制屏蔽curl（

**Comment by waruqi** [comment]
目前没其他办法，你把 curl 卸载了就行了。
