### ISSUE TITLE
xmake llvm 工具链自动识别问题

### ISSUE THREAD

**Issue by breaking153** [xmake-io/xmake#4027]
### Xmake Version

v2.8.1+dev.732d60063

### Operating System Version and Architecture

win11

### Describe Bug

llvm在path中但无法被自动切换识别

### Expected Behavior

path中的llvm工具被自动识别

### Project Configuration

.....
set_toolchain("llvm")
.....

### Additional Information and Error Logs

D:\C-C++Project\PjMine>xmake f -cvD  --toolchain=llvm  
checking for platform ... windows
checking for architecture ... x64
error: @programdir\core\main.lua:300: @programdir\core\tool\toolchain.lua:273: @programdir\toolchains\llvm\check.lua:90: llvm toolchain not found!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:913]:
    [@programdir\toolchains\llvm\check.lua:90]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\tool\toolchain.lua:269]: in function 'check'
    [@programdir\core\platform\platform.lua:247]: in function 'check'
    [@programdir\actions\config\main.lua:363]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\base\task.lua:501]: in function 'run'
    [@programdir\core\main.lua:298]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:404]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:913: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:300: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>

**Comment by waruqi** [comment]
默认 windows 平台，仅仅支持 msvc 。是强绑定的，https://github.com/xmake-io/xmake/issues/3878
