### ISSUE TITLE
Windows路径下，install的目标路径中似乎不能带有空格

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#403]
![图片](https://user-images.githubusercontent.com/1145161/56290517-e7c3e400-6155-11e9-8e42-5f99758d7849.png)
（注：已经是使用管理员的CMD）

**Comment by waruqi** [comment]
你是自定义的on_install 还是直接内置的install？

请提供下你的完整执行命令，如果有on_install也请提供下

可以加-v -D参数执行后，提供下详细输出信息

**Comment by fasiondog** [comment]
![图片](https://user-images.githubusercontent.com/1145161/56294925-7ccadb00-615e-11e9-887a-50c359514f9f.png)

on_install:
![图片](https://user-images.githubusercontent.com/1145161/56294965-92d89b80-615e-11e9-9d96-057145b37b58.png)

**Comment by waruqi** [comment]
你这是最新版本xmake? 追加-v -D应该可以看到错误信息的，你更新下xmake试试

```console
Z:\hikyuu>xmake i -o "C:\Program Files\test" -v -D
configure
{
    with-demo = false
    arch = x86
    ccache = true
    with-unit-test = false
    cxx = cl.exe
    theme = default
    clean = true
    plat = windows
    boost-python-suffix = 3X
    host = windows
    kind = static
    buildir = build
    vs = 2008
    mode = release
}
无效的参数数量
C:\Program Files\xmake/core/base/os.lua:700: exec(xcopy /S /Q /Y /I hikyuu C:\Pr
ogram Files\test) failed(4)!
```

看错误，是你的before_install里面写的有问题。

https://github.com/fasiondog/hikyuu/blob/ab05a6804005249f74f7d6202d8a64cbbb9c6da7/scripts/before_install.lua#L16-L18

问题一：

为什么不直接用`os.cp`呢，内置跨平台copy文件

问题二：

全字符串命令传入`os.exec`，如果路径带空格，你需要用os.args转义处理下的：

```lua
        os.exec("xcopy /S /Q /Y /I hikyuu %s", os.args(installdir))
```

或者用os.execv版本，通过argv参数数组传递:

```lua
        os.execv("xcopy", {"/S", "/Q", "/Y", "/I", "hikyuu", installdir})
```

**Comment by fasiondog** [comment]
3Q:)  
不用系统的cp好像是因为当时cp会在目标目录下建个子目录（现在不知道了)
