### ISSUE TITLE
xmake qt 继承自qt基类的自定义库编译显示链接不上

### ISSUE THREAD

**Issue by mingtiancai** [xmake-io/xmake#4031]
### Xmake Version

2.8.1

### Operating System Version and Architecture

Windows11

### Describe Bug

![image](https://github.com/xmake-io/xmake/assets/13520801/82433511-452f-4340-8532-8a96d150496a)
![image](https://github.com/xmake-io/xmake/assets/13520801/99b88be2-9c3a-4343-93b1-6c235c4508e3)

首先使用xmake 创建widgetapp模板项目可以运行，然后加个类文件，里面自定义继承自qt基类的自定义类，编译就编译不过去，但是在cmake qt下代码可以运行

### Expected Behavior

编译通过

### Project Configuration

xmake qt widgetapp模板生成

### Additional Information and Error Logs

![image](https://github.com/xmake-io/xmake/assets/13520801/82433511-452f-4340-8532-8a96d150496a)
![image](https://github.com/xmake-io/xmake/assets/13520801/99b88be2-9c3a-4343-93b1-6c235c4508e3)

**Comment by waruqi** [comment]
带 meta 的 .h 要加到 add_files

**Comment by mingtiancai** [comment]
> 解决了，谢谢
