### ISSUE TITLE
headeronly 类型的 target 设置 set_group 后，导致 protoc 找不到

### ISSUE THREAD

**Issue by ivanallen** [xmake-io/xmake#4033]
### Xmake 版本

xmake v2.8.1+20230728

### 操作系统版本和架构

Linux 10-16-43-32 5.14.0-70.13.1.el9_0.x86_64 #1 SMP PREEMPT Wed May 25 21:01:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

headeronly 类型的 target 设置 set_group 后，导致 protoc 找不到

### 期待的结果

设置 set_group 也能正常找到 protoc

### 工程配置

```lua
set_project("test")
set_languages("c++20")

set_version("1.0.0", {build = "%Y%m%d"})

add_requires("protobuf-cpp", {system = false})

target("demo")
    set_kind("binary")
    set_group("bar-group")
    add_files("src/main.cc")
    add_files("src/demo.proto")
    add_rules("protobuf.cpp")
    add_packages("protobuf-cpp")
    add_packages("grpc")

    before_build_file(function (target, sourcefile, opt)
        print("before ====>", sourcefile, opt)
    end)

    after_build_file(function (target, sourcefile, opt)
        print("after ---->", sourcefile, opt)
    end)

target("foo")
    set_kind("headeronly")
    set_group("bar-group") -- 去掉这行可正常编译
    add_headerfiles("src/add.h")
```

### 附加信息和错误日志

![image](https://github.com/xmake-io/xmake/assets/12481610/ffc7dd82-fe1d-48c8-8b74-1fd242c8a9af)

**Comment by waruqi** [comment]
大概知道问题在哪 但需要一些时间 跟 set_group 没啥关系。。内部 PATH envs 处理的问题

**Comment by ivanallen** [comment]
好的，我尝试了一下，确实是和 set_group 没关系，感觉只是 set_group 增加了复现的概率。。。

**Comment by waruqi** [comment]
再试试，xmake update -s dev

**Comment by waruqi** [comment]
没啥问题 我就先关了

**Comment by ivanallen** [comment]
> 没啥问题 我就先关了

谢谢，现在测试 OK
