### ISSUE TITLE
xmake安装ffmpeg库失败

### ISSUE THREAD

**Issue by 1821746019** [xmake-io/xmake#4038]
### Xmake 版本

xmake v2.8.1+dev.0ffb589fb

### 操作系统版本和架构

win10 x64 22H2 

### 描述问题

xmake安装ffmpeg库失败

### 期待的结果

安装成功

### 工程配置

add_rules("mode.debug", "mode.release")

add_rules("plugin.vsxmake.autoupdate")
add_rules("plugin.compile_commands.autoupdate")
set_languages("cxx20")
set_runtimes("MD")
add_requires("xmake::ffmpeg", {
    config = {
        shared = true
    }
})
-- 试过安装cpr没问题
-- add_requires("xmake::cpr", {
--     config = {
--         shared = true
--     }
-- })
target("qml_player")
    add_rules("qt.quickapp")
    add_headerfiles("src/*.h")
    add_files("src/*.cpp")
    add_files("src/qml.qrc")

### 附加信息和错误日志

checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.36.32537
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> ffmpeg 5.1.2 [vs_runtime:"MD", shared:y]
please input: y (y/n/m)
n
error: packages(ffmpeg): must be installed!
warning: add_requires("xmake::ffmpeg") has unknown option: {config=table: 0000025820C61F80}!
PS F:\Users\Administrator\Desktop\myCode\###xmake\utils\qml_player> xmake -vD
checking for cl.exe ... D:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.36.32537
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(unzip.exe -v), No such file or directory
checking for unzip ... no
checking for 7z ... D:\Program Files\xmake\winenv\bin\7z
checking for git ... ok
checkinfo: cannot runv(gzip.exe --version), No such file or directory
checking for gzip ... no
git rev-parse HEAD
finding ffmpeg from xmake ..
checking for xmake::ffmpeg ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> ffmpeg 5.1.2 [vs_runtime:"MD", shared:y]
please input: y (y/n/m)
y
checking for ping ... ok
pinging the host(www.gyan.dev) ... 1 ms
D:\Program Files\xmake\winenv\bin\7z x -y ffmpeg-5.1.2-full_build-shared.7z -osource.tmp
7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 39593966 bytes (38 MiB)

Extracting archive: ffmpeg-5.1.2-full_build-shared.7z
--
Path = ffmpeg-5.1.2-full_build-shared.7z
Type = 7z
Physical Size = 39593966
Headers Size = 3432
Method = LZMA2:192m LZMA:20 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Folders: 14
Files: 212
Size:       150670240
Compressed: 39593966
error: @programdir\core\sandbox\modules\os.lua:111: cannot move bin to D:\Program Files\xmake\XMAKE_PKG_INSTALLDIR\f\ffmpeg\5.1.2\af1c2f1e3fb04e67b6ccd800f82e81ea\bin Unknown  
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:913]:
    [@programdir\core\sandbox\modules\os.lua:111]: in function 'mv'
    [...make\repositories\xmake-repo\packages\f\ffmpeg\xmake.lua:107]: in function 'script'
    [...dir\modules\private\action\require\impl\utils\filter.lua:125]: in function 'call'
    [...\modules\private\action\require\impl\actions\install.lua:364]:

  => install ffmpeg 5.1.2 .. failed
error: @programdir\modules\private\async\runjobs.lua:256: ...\modules\private\action\require\impl\actions\install.lua:469: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:913]:
    [...\modules\private\action\require\impl\actions\install.lua:469]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:328]:
    [...modules\private\action\require\impl\install_packages.lua:479]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:232]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:913: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir\modules\private\async\runjobs.lua:256: in field 'catch'
        @programdir\core\sandbox\modules\try.lua:123: in global 'try'
        @programdir\modules\private\async\runjobs.lua:218: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>
warning: add_requires("xmake::ffmpeg") has unknown option: {config=table: 000002568F9D00D0}!

**Comment by 1821746019** [comment]
另外,这是安装cpr的日志
```powershell
 *  正在执行任务: xmake -v 

checking for cl.exe ... D:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.36.32537
checking for zig ... no
checking for zig ... no
checking for unzip ... no
checking for 7z ... D:\Program Files\xmake\winenv\bin\7z
checking for git ... ok
checking for gzip ... no
git rev-parse HEAD
checking for cmake ... no
checking for cmake ... no
checking for cmake ... no
checking for cmake ... ok
checking for xmake::libcurl ... no
checking for pkg-config ... no
checking for pkgconf ... no
checking for libcurl ... no
checking for xmake::cpr ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> libcurl 8.0.1 [vs_runtime:"MD", from:cpr]
  -> cpr 1.10.3 [vs_runtime:"MD", shared:y]
please input: y (y/n/m)
y
checking for ping ... ok
pinging the host(github.com) ... 1 ms
checking for curl ... D:\Program Files\xmake\winenv\bin\curl
D:\Program Files\xmake\winenv\bin\curl -SL -A "Xmake/2.8.1+dev.732d60063 (Windows;) curl/7.85.0" https://github.com/xmake-mirror/build-artifacts/releases/download/libcurl-8.0.1/windows-x64-vc142-459ca8e5d8464aaeaab4f24186417257.7z -o windows-x64-vc142-459ca8e5d8464aaeaab4f24186417257.7z
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100  760k  100  760k    0     0   167k      0  0:00:04  0:00:04 --:--:--  403k
D:\Program Files\xmake\winenv\bin\7z x -y windows-x64-vc142-459ca8e5d8464aaeaab4f24186417257.7z -osource.tmp

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 778511 bytes (761 KiB)

Extracting archive: windows-x64-vc142-459ca8e5d8464aaeaab4f24186417257.7z
--
Path = windows-x64-vc142-459ca8e5d8464aaeaab4f24186417257.7z
Type = 7z
Physical Size = 778511
Headers Size = 692
Method = LZMA2:3m BCJ
Solid = +
Blocks = 2

Everything is Ok

Folders: 11
Files: 21
Size:       2905897
Compressed: 778511
  => download https://github.com/xmake-mirror/build-artifacts/releases/download/libcurl-8.0.1/windows-x64-vc142-459ca8e5d8464aaeaab4f24186417257.7z .. ok
checking for xmake::libcurl ... libcurl 8.0.1
{
  license = "MIT",
  linkdirs = {
    "D:\Program Files\xmake\XMAKE_PKG_INSTALLDIR\l\libcurl\8.0.1\459ca8e5d8464aaeaab4f24186417257\lib" 
  },
  libfiles = {
    "D:\Program Files\xmake\XMAKE_PKG_INSTALLDIR\l\libcurl\8.0.1\459ca8e5d8464aaeaab4f24186417257\lib\libcurl.lib" 
  },
  static = true,
  links = {
    "libcurl"
  },
  defines = "CURL_STATICLIB",
  sysincludedirs = {
    "D:\Program Files\xmake\XMAKE_PKG_INSTALLDIR\l\libcurl\8.0.1\459ca8e5d8464aaeaab4f24186417257\include" 
  },
  syslinks = {
    "advapi32",
    "crypt32",
    "wldap32",
    "winmm",
    "ws2_32",
    "user32"
  },
  version = "8.0.1"
}

checking for link.exe ... D:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\link.exe
checking for the linker (ld) ... link.exe
checking for cl.exe ... D:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\cl.exe
checking for the c compiler (cc) ... cl.exe
checking for D:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\cl.exe ... ok
checking for flags (/MD) ... ok
checking for flags (cl_external_includedir) ... ok
checking for cl.exe ... D:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\cl.exe
checking for the c++ compiler (cxx) ... cl.exe
> checking for c includes(curl/curl.h)
> checking for c funcs(curl_version)
> checking for c links(libcurl, advapi32, crypt32, wldap32, winmm, ws2_32, user32)      
> checking for c snippet(has_cfuncs)
  => install libcurl 8.0.1 .. ok
D:\Program Files\xmake\winenv\bin\curl -SL -A "Xmake/2.8.1+dev.732d60063 (Windows;) curl/7.85.0" https://github.com/xmake-mirror/build-artifacts/releases/download/cpr-1.10.3/windows-x64-vc143-199e70e466df485288df30290f10a057.7z -o windows-x64-vc143-199e70e466df485288df30290f10a057.7z
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  300k  100  300k    0     0   109k      0  0:00:02  0:00:02 --:--:--  297k
D:\Program Files\xmake\winenv\bin\7z x -y windows-x64-vc143-199e70e466df485288df30290f10a057.7z -osource.tmp

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 307528 bytes (301 KiB)

Extracting archive: windows-x64-vc143-199e70e466df485288df30290f10a057.7z
--
Path = windows-x64-vc143-199e70e466df485288df30290f10a057.7z
Type = 7z
Physical Size = 307528
Headers Size = 1159
Method = LZMA2:1536k BCJ
Solid = +
Blocks = 2

Everything is Ok

Folders: 11
Files: 58
Size:       1194181
Compressed: 307528
  => download https://github.com/xmake-mirror/build-artifacts/releases/download/cpr-1.10.3/windows-x64-vc143-199e70e466df485288df30290f10a057.7z .. ok
checking for xmake::cpr ... cpr 1.10.3
{ 
  license = "MIT",
  linkdirs = {
    "D:\Program Files\xmake\XMAKE_PKG_INSTALLDIR\c\cpr\1.10.3\199e70e466df485288df30290f10a057\lib" 
  },
  shared = true,
  libfiles = {
    "D:\Program Files\xmake\XMAKE_PKG_INSTALLDIR\c\cpr\1.10.3\199e70e466df485288df30290f10a057\lib\cpr.lib",
    "D:\Program Files\xmake\XMAKE_PKG_INSTALLDIR\c\cpr\1.10.3\199e70e466df485288df30290f10a057\bin\cpr.dll" 
  },
  static = true,
  links = {
    "cpr"
  },
  sysincludedirs = {
    "D:\Program Files\xmake\XMAKE_PKG_INSTALLDIR\c\cpr\1.10.3\199e70e466df485288df30290f10a057\include" 
  },
  version = "1.10.3"
}

checking for flags (/MD) ... ok
checking for flags (cl_external_includedir) ... ok
> checking for c++ links(cpr, libcurl, advapi32, crypt32, wldap32, winmm, ws2_32, user32)
> checking for c++ snippet(test)
  => install cpr 1.10.3 .. ok
checking for Qt SDK directory ... D:/Qt/Qt5/Qt5.15.10-Windows-x86_64-VS2022-17.6.2
checking for Qt SDK version ... 5.15.10
checking for flags (-O2 -fp:fast) ... ok
checking for flags (-std:c++20) ... ok
checking for flags (-DNDEBUG) ... ok
create ok!
compile_commands.json updated!
[100%]: build ok, spent 0.047s
warning: add_requires("xmake::cpr") has unknown option: {config=table: 00000190B2187F70}!
```

**Comment by waruqi** [comment]
再试试

xrepo update-repo
xmake f -c

**Comment by 1821746019** [comment]
好了,nice!
```powershell
F:\Users\Administrator\Desktop\myCode\###xmake\utils\qml_player>xrepo update-repo
updating repositories .. ok
F:\Users\Administrator\Desktop\myCode\###xmake\utils\qml_player>xmake f -c
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.36.32537
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> ffmpeg 5.1.2 [shared:y, vs_runtime:"MD"]
please input: y (y/n/m)
y
  => install ffmpeg 5.1.2 .. ok       
checking for Qt SDK directory ... D:/Qt/Qt5/Qt5.15.10-Windows-x86_64-VS2022-17.6.2
checking for Qt SDK version ... 5.15.10
warning: add_requires("xmake::ffmpeg") has unknown option: {config=table: 0000022A39CF85A0}!
```

**Comment by star-hengxing** [comment]
```
warning: add_requires("xmake::ffmpeg") has unknown option: {config=table: 0000022A39CF85A0}!
```

config -> configs

**Comment by 1821746019** [comment]
> ```
> warning: add_requires("xmake::ffmpeg") has unknown option: {config=table: 0000022A39CF85A0}!
> ```
> 
> * config -> configs
> * `xmake::ffmpeg` -> `ffmpeg`

Thank you for your reminder, I will correct it now.

**Comment by waruqi** [comment]
根本原因是，os.mv 跨驱动器 rename 失败了。你改了包的存储路径到 D 盘导致。

之前是 ffmpeg 包改成了 os.cp 规避掉。现在我改进了下 xmake 的 os.mv 实现，应该可以从根本上解决这个问题。。`xmake update dev`
