### ISSUE TITLE
find_package 可以找到本地库，但是 link 的时候缺失

### ISSUE THREAD

**Issue by ivanallen** [xmake-io/xmake#4045]
### Xmake 版本

xmake v2.8.1+20230728

### 操作系统版本和架构

Linux 10-16-43-32 5.14.0-70.13.1.el9_0.x86_64 #1 SMP PREEMPT Wed May 25 21:01:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

![image](https://github.com/xmake-io/xmake/assets/12481610/e25254b3-d77d-4c34-b2ca-fe40db53ffd8)

如上，可以找到本地库，但是 link 的时候，不链接 systemd

### 期待的结果

能正常链接 systemd

### 工程配置

```lua
add_rules("mode.debug", "mode.release")

add_requires("systemd", {system = true})
add_requires("numa", {system = true})

target("bar")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("systemd")
    add_packages("numa")
```

### 附加信息和错误日志

![image](https://github.com/xmake-io/xmake/assets/12481610/c319d923-61b8-4de2-8274-f24fa684984c)

![image](https://github.com/xmake-io/xmake/assets/12481610/c9a62800-69c0-4ed6-bd17-7050cb0f13f0)

find_package 可以正常找到：

![image](https://github.com/xmake-io/xmake/assets/12481610/dff38148-a96d-44ab-9ea8-d5e1de2d6d46)

**Comment by waruqi** [comment]
你手动测试找的 `system::xxx` 是在 pkg-config 也找不到的情况下，退化到最后的查找策略，直接搜索 /usr/lib 等库目录。。

而 `{system = true}` ，默认优先从 pkg-config 找系统库，找不到，才去走 system::xxx，你工程里面已经从 pkg-config 找到了库，没走 system::xxx

<img width="249" alt="image" src="https://github.com/xmake-io/xmake/assets/151335/c5c750eb-654f-463a-a7eb-3b20aaf928ef">

所以你要排查 pkg-config 的返回结果。。

```
pkgconfig --cflags --libs systemd
xmake l find_package pkgconfig::systemd
```

如果它没返回 links，那就跟 xmake 没啥关系了。pkg-config 的问题

**Comment by ivanallen** [comment]
> 你手动测试找的 `system::xxx` 是在 pkg-config 也找不到的情况下，退化到最后的查找策略，直接搜索 /usr/lib 等系统库目录。。
> 
> 而 `{system = true}` ，默认优先从 pkg-config 找系统库，找不到，才去走 system::xxx，你工程里面已经从 pkg-config 找到了库，没走 system::xxx
> 
> <img alt="image" width="249" src="https://user-images.githubusercontent.com/151335/258649122-c5c750eb-654f-463a-a7eb-3b20aaf928ef.png">
> 所以你要排查 pkg-config 的返回结果。。
> 
> ```
> pkgconfig --cflags --libs systemd
> xmake l find_package pkgconfig::systemd
> ```
> 
> 如果它没返回 links，那就跟 xmake 没啥关系了。pkg-config 的问题

确实系统中存在着一个 systemd.pc，什么也不返回。
还有一个 libsystemd.pc，这个可以正常返回，修改为 add_packages("libsystemd", {system = true}) 就好了。
