### ISSUE TITLE
Merge dependent package to my target library

### ISSUE THREAD

**Issue by zlargon** [xmake-io/xmake#405]
Hi,

Does xmake provides a way to merge dependent packages to my target `static` or `shared` library?

For example, my "hello" library use a third-party package `libuv`. I would like to merge `libuv.a` into `libhello.a` because the function of `libuv.a` would not expose to the end user. Instead, the user just need to import one static library `libhello.a` for his/her app.

Thank you.

```lua
add_requires("libuv")
add_includedirs("src")

target("hello")
    set_kind("$(kind)")
    add_files("src/*.c")
    add_packages("libuv")
```

```
build
└── macosx
    └── x86_64
        └── release
            ├── libhello.a
            └── libhello.dylib
```

**Comment by waruqi** [comment]
There is currently no built-in support, but you can try the following code.

```lua

add_requires("libuv", "zlib")

target("test")
    set_kind("static")
    add_files("src/*.c") 
    on_load(function (target)
        import("lib.detect.find_library")
        for _, name in ipairs({"libuv", "zlib"}) do
            local package = target:pkg(name)
            if package then
                for _, link in ipairs(package:get("links")) do
                    local libinfo = find_library(link, package:get("linkdirs"), {kind = "static"})
                    if libinfo then
                        local libfile = path.join(libinfo.linkdir, libinfo.filename)
                        target:add("files", libfile)
                    end
                end
            end
        end
    end)
    add_packages("libuv", "zlib")
```

Because `add_files("libxxx.a")` and `target:add("files", "libxxx.a")` supports merging library files.

However, merging library will have object file name conflicts, because it will lose the directory hierarchy when extracting obj files via `ar -x libxxx.a` If there is a duplicate object file name.

Therefore, I do not recommend this.

**Comment by zlargon** [comment]
It works for me. I also take your recommendation and let the library separate.
Thank you!

**Comment by waruqi** [comment]
I added pkg:get("libpathes") to get all library files path. You can simply traverse this list to install the dll library files you need

see 
https://github.com/xmake-io/xmake/issues/961#issuecomment-698091698
