### ISSUE TITLE
一个target设置--coverage后，导致另外一个target的-g选项丢失

### ISSUE THREAD

**Issue by xumaofeng-jn** [xmake-io/xmake#4053]
### Xmake 版本

2.8.1

### 操作系统版本和架构

Linux  5.15.90.1-microsoft-standard-WSL2

### 描述问题

我在一个project中创建了两个target，设置set_defaultmode("debug")。
当我未设置 --coverage 时，这两个target编译时都有 -g 选项。
我设置 target A 的 cxflags 增加 --coverage 选项 ： add_cxflags("--coverage")
target B 不增加 --coverage 
此时编译，target A 和 B 的编译选项的 -g 参数都丢失了，使用变量 mode 测试仍是 debug 模式，为什么 -g 选项丢失了？

### 期待的结果

1、一个 project 多个 target 时，是否可以针对不同 target 设置不同的 mode ？
2、本用例描述的场景是否是一个 bug？

### 工程配置

编译参数大致如下：
"-c", "-m64", "-fvisibility=hidden", "-fvisibility-inlines-hidden", "-O0", "-std=c++11", "-pthread", "-Warray-bounds", "-Wno-address", "-fstack-protector", "-fsigned-char", "-Wno-invalid-offsetof", "-Wno-switch", "-Wno-narrowing", "-Wno-invalid-source-encoding", "-Wno-deprecated-declarations", "-Wno-attributes", "-Wno-deprecated", "-Wno-return-type-c-linkage", "-Wno-logical-op-parentheses", "-Wno-enum-constexpr-conversion", "-fPIE", "-fstack-protector-all"

### 附加信息和错误日志

没有错误信息，编译选项丢失 -g 参数。

**Comment by waruqi** [comment]
```lua
add_rules("mode.debug", "mode.release")

set_defaultmode("debug")

target("A")
    set_kind("binary")
    add_files("src/*.cpp")
    add_cxflags("--coverage")

target("B")
    set_kind("binary")
    add_files("src/*.cpp")
```

```
$ xmake -v
[ 25%]: cache compiling.debug src/main.cpp
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -c -Qunused-arguments -target x86_64-apple-macos12.6 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk -g -O0 -o build/.objs/B/macosx/x86_64/debug/src/main.cpp.o src/main.cpp
checking for flags (-MMD -MF) ... ok
checking for flags (-fdiagnostics-color=always) ... ok
checking for flags (--coverage) ... ok
[ 25%]: cache compiling.debug src/main.cpp
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -c -Qunused-arguments -target x86_64-apple-macos12.6 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk -g -O0 --coverage -o build/.objs/A/macosx/x86_64/debug/src/main.cpp.o src/main.cpp
[ 50%]: linking.debug B
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o build/macosx/x86_64/debug/B build/.objs/B/macosx/x86_64/debug/src/main.cpp.o -target x86_64-apple-macos12.6 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk -stdlib=libc++ -lz
[ 50%]: linking.debug A
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o build/macosx/x86_64/debug/A build/.objs/A/macosx/x86_64/debug/src/main.cpp.o -target x86_64-apple-macos12.6 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk -stdlib=libc++ -lz
```

> -g -O0 -o build/.objs/B/macosx/x86_64/debug/src/main.cpp.o src/main.cpp
> -g -O0 --coverage -o build/.objs/A/macosx/x86_64/debug/src/main.cpp.o src/main.cpp

不是好好的么

**Comment by waruqi** [comment]
> 发现是 set_symbols("hidden") 导致的。

set_ 会重置覆盖 symbols ，不是追加。。你只设置了 hidden 。。没设置 debug 。。当然了。。得用 `set_symbols("debug", "hidden")`

**Comment by xumaofeng-jn** [comment]
@waruqi 
好的懂了，感谢大神答疑解惑！
