### ISSUE TITLE
xmake lua 没法执行相对路径的lua脚本

### ISSUE THREAD

**Issue by Wzshun** [xmake-io/xmake#4057]
### Xmake 版本

2.8.1

### 操作系统版本和架构

windows10

### 描述问题

相对路径的foo.lua，没法被执行，报cannot import module:
这是一个feature还是bug？不清楚。

还有xmake.lua中，import 相对路径的自定义lua应该怎么描述？

### 期待的结果

支持相对路径

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
好歹给个 xmake.lua 和 logs 么。。啥也没有，让我猜么。。按照 issue 模板，重新提个过来。。
