### ISSUE TITLE
使用xrepo下载zlib失败

### ISSUE THREAD

**Issue by Utu81** [xmake-io/xmake#4059]
### Xmake 版本

2.7.8

### 操作系统版本和架构

Windows10  19045

### 描述问题

在msys环境下使用xmake创建一个c++项目并执行xrepo install zlib后报错:

updating repositories .. error: 致命错误：不是 git 仓库（或者直至挂载点 / 的任何父目录）
停止在文件系统边界（未设置 GIT_DISCOVERY_ACROSS_FILESYSTEM）。

error: execv(xmake require -j 10 --extra={system=false} libhv) failed(-1)

### 期待的结果

希望能尽快解决

### 工程配置

默认c++项目模板

### 附加信息和错误日志

No Thing

**Comment by waruqi** [comment]
xrepo rm-repo --all 

试试

**Comment by Utu81** [comment]
谢谢，已解决
