### ISSUE TITLE
因文件名而不支持模块分区

### ISSUE THREAD

**Issue by 2283572185** [xmake-io/xmake#4063]
### Xmake 版本

xmake v2.8.1+HEAD.12fe4e0c5

### 操作系统版本和架构

Windows 11 23H2

### 描述问题

有一个使用了模块分区的源文件
``` c++
// a.ixx
export module a:core;
```
然后在Windows下构建：`xmake f --toolchain=clang --policies=build.c++.clang.fallbackscanner"
xmake给出的文件名是"a:core.pcm"，但Windows的文件名中不能含有':'字符
于是产生了这么一个错误：`error: unable to rename temporary 'build\.gens\MyDetail\windows\x64\Debug\rules\modules\cache\c6251745\a:core-64f241f0.pcm.tmp' to output file 'build\.gens\MyDetail\windows\x64\Debug\rules\modules\cache\c6251745\a:core.pcm': 'Invalid argument'`

### 期待的结果

应该重新设置模块分区的输出文件名，至少不应该包含':'
虽然说是fallback途径，但鉴于clang-scan-deps对header uints的支持一直不行，还是有必要修一下的

### 工程配置

[test.zip](https://github.com/xmake-io/xmake/files/12321138/test.zip)

### 附加信息和错误日志

<img width="1280" alt="image" src="https://github.com/xmake-io/xmake/assets/63223769/53c284c5-f44c-46b5-a602-dc6e71584265">

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/pull/4066 试下

**Comment by waruqi** [comment]
我先 merge 了。。如果有问题及时反馈
