### ISSUE TITLE
Keil C51 工具链无法生成 .LST 文件

### ISSUE THREAD

**Issue by Noveren** [xmake-io/xmake#4067]
### Xmake 版本

xmake v2.8.1+dev.732d60063

### 操作系统版本和架构

Windows 11 22H2 x86

### 描述问题

Keil C51 在编译时会输出 .LST 文件，包含源文件编译的相关信息；该文件的生成由 PRINT directive 进行控制，即
`C51 example.c PRINT(./exampe.lst) OBJECT(./exmample.obj)`；但是目前其只生成了文件扩展名为 `.c.o` 的二进制文件，且文本覆盖现象，使用 VSCODE 强制打开如图
![image](https://github.com/xmake-io/xmake/assets/54400786/2f55b9bb-2e82-46bd-8967-4174d572242f)

### 期待的结果

生成 `.LST` 文件

### 工程配置

[example.zip](https://github.com/xmake-io/xmake/files/12327501/example.zip)

### 附加信息和错误日志

经尝试发现，该错误产生的原因是由于扩展名替换失败
文件 `\modules\core\tools\c51.lua` 的第 67 行的 `"PRINT(" .. (objectfile:gsub("%.c%.obj", ".lst"))`
由于 `objectfile` 文件的扩展展名实际是 `.c.o`，因此 `gsub` 方法替换失败，导致编译时 `PRINT` 的参数的扩展名仍为 `.c.o`，先生成 lst 文本文件，而后同名的二进制目标文件又对其进行覆盖
经测试，将其改为 `objectfile:gsub("%.c%.o", "lst")` 可以解决该问题

**Comment by waruqi** [comment]
你是不是切到 cross 平台了？不切试试呢 https://github.com/xmake-io/xmake/issues/3211 跟这个类似的问题

**Comment by waruqi** [comment]
不过我改进过了，兼容了 .o 和 .obj

xmake update -s dev

**Comment by Noveren** [comment]
> 你是不是切到 cross 平台了？不切试试呢 #3211 跟这个类似的问题

确实，我在 xmake.lua 文件中添加了如下两行
```lua
set_defaultplat("mcs51")
set_defaultarchs("mcs51")
```
生成的目标文件的扩展名是 `.c.o`，移除了之后生成的是 `.c.obj`；之前没有细看 #3211


> 不过我改进过了，兼容了 .o 和 .obj
> 
> xmake update -s dev

现在已经可以正常生成 .lst 了，兼容了  .o 和 .obj

非常感谢您，xmake 很棒
