### ISSUE TITLE
指定子依赖的版本，依旧不生效

### ISSUE THREAD

**Issue by ivanallen** [xmake-io/xmake#4078]
### Xmake 版本

xmake v2.8.1+20230728

### 操作系统版本和架构

Linux 10-16-43-32 5.14.0-70.13.1.el9_0.x86_64 #1 SMP PREEMPT Wed May 25 21:01:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

目前在 protobuf 版本控制上出现了冲突，为了理解问题，简化了一下：

foo 库是 A 团队开发的项目。
xsub 对应 protobuf 这个库。
xmul 是 B 团队开发的项目。

假设目前模块依赖如下：

foo->xsub
foo->xmul->xsub

其中 xmul 依赖 xsub 1.0.0，这个版本在 B 团队的代码库里是写死的。

现在 foo 项目，A 团队强行使用 add_requireconfs("xmul.xsub", {override = true, version = "1.0.1"})

但是在实际编译的时候，xmul 依然使用 xsub 1.0.0 进行编译。如果  xsub 是 protobuf 的话，就会出现生成的 pb.cc 文件不兼容。

使用 xmake f -m debug 配置的时候有提示，这个提示并没有提示也要安装 xsub 1.0.0，因为我们强制指定了所有地方都是 1.0.1
![image](https://github.com/xmake-io/xmake/assets/12481610/8e5374b5-6b9e-4b8d-95e8-30a674591197)

但是在实际 install 的时候，依旧使用了 1.0.0 版本：
![image](https://github.com/xmake-io/xmake/assets/12481610/5d419d09-efe3-430f-b574-53156ef8a900)
       
 

### 期待的结果

强制指定依赖库的依赖，应该也使用对应的版本去编译

### 工程配置

```lua
add_rules("mode.debug", "mode.release")
add_requires("xsub 1.0.1")

add_requires("xmul")
add_requireconfs("xmul.xsub", {override = true, version = "1.0.1"})

add_requires("xdiv")

target("foo")
    set_kind("binary")
    add_files("src/*.cc")
    add_packages("xsub")
    add_packages("xmul")
    add_packages("xdiv")
```

**Comment by ivanallen** [comment]
> #3952

是的，我没有办法去控制 xmul 的 xmake.lua，因为不是一个团队。

我看你写的 
> When I have time, I'll consider improving it.

是有计划改善吗？

现在项目挺大的了，我们在自建仓库里引入了新版本的 protobuf 后，ci 编译全挂了。。

**Comment by waruqi** [comment]
> > #3952
> 
> 是的，我没有办法去控制 xmul 的 xmake.lua，因为不是一个团队。
> 
> 我看你写的
> 
> > When I have time, I'll consider improving it.
> 
> 是有计划改善吗？

之前已经说过了，有时间的时候会考虑，看我个人时间安排

> 
> 现在项目挺大的了，我们在自建仓库里引入了新版本的 protobuf 后，ci 编译全挂了。。

workaround 方案: 可以在 on_install 里根据 package:dep("xxx") 的实际版本，用 io.replace 对 xmake.lua 打 patch 修改同步版本

**Comment by waruqi** [comment]
再试试 https://github.com/xmake-io/xmake/pull/4088

```
xmake update -s github:xmake-io/xmake#package
```

**Comment by ivanallen** [comment]
> 再试试 #4088
> 
> ```
> xmake update -s github:xmake-io/xmake#package
> ```

太给力了，我试下

**Comment by ivanallen** [comment]
> 再试试 #4088
> 
> ```
> xmake update -s github:xmake-io/xmake#package
> ```

看起来没有生效。确认本地代码是更新的了：
![image](https://github.com/xmake-io/xmake/assets/12481610/bffdfd98-4b77-41e6-b9f8-343c9133694d)

**Comment by waruqi** [comment]
buildenvs 上面怎么没这段？你删了？

<img width="536" alt="image" src="https://github.com/xmake-io/xmake/assets/151335/f25320be-4038-4bd8-85e3-daa5db4b8935">

不行就提供个完整的可复现 demo project 给我

**Comment by ivanallen** [comment]
> buildenvs 上面怎么没这段？你删了？
> 
> <img alt="image" width="536" src="https://user-images.githubusercontent.com/151335/261202140-f25320be-4038-4bd8-85e3-daa5db4b8935.png">
> 不行就提供个完整的可复现 demo project 给我

我来打个包。没删除，grep 的输出限制了行数，没显示出来

**Comment by ivanallen** [comment]
[test_foo.tar.gz](https://github.com/xmake-io/xmake/files/12365963/test_foo.tar.gz)

主项目是 foo

**Comment by waruqi** [comment]
```
cloning repository(liufeng-repo): git@github.xsky.com:liu-feng/xmake-repo.git to /Users/ruki/Downloads/test_foo/foo/.xmake/macosx/x86_64/repositories/liufeng-repo ..
/usr/bin/git clone git@github.xsky.com:liu-feng/xmake-repo.git -c core.fsmonitor=false /Users/ruki/Downloads/test_foo/foo/.xmake/macosx/x86_64/repositories/liufeng-repo
Cloning into '/Users/ruki/Downloads/test_foo/foo/.xmake/macosx/x86_64/repositories/liufeng-repo'...
ssh: connect to host github.xsky.com port 22: Operation timed out
fatal: Could not read from remote repository.


```

下载不了

**Comment by ivanallen** [comment]
> ```
> cloning repository(liufeng-repo): git@github.xsky.com:liu-feng/xmake-repo.git to /Users/ruki/Downloads/test_foo/foo/.xmake/macosx/x86_64/repositories/liufeng-repo ..
> /usr/bin/git clone git@github.xsky.com:liu-feng/xmake-repo.git -c core.fsmonitor=false /Users/ruki/Downloads/test_foo/foo/.xmake/macosx/x86_64/repositories/liufeng-repo
> Cloning into '/Users/ruki/Downloads/test_foo/foo/.xmake/macosx/x86_64/repositories/liufeng-repo'...
> ssh: connect to host github.xsky.com port 22: Operation timed out
> fatal: Could not read from remote repository.
> ```
> 
> 下载不了

xmake-reop 我一起打包给你了，我改一下配置，让本地也能用吧

**Comment by ivanallen** [comment]
[test_foo.tar.gz](https://github.com/xmake-io/xmake/files/12366668/test_foo.tar.gz)
之前的带了很多内网的地址，这次全部改成 local 了
你需要提前 xrepo add-repo 那个 xmake-repo 文件夹

**Comment by waruqi** [comment]
有两个问题导致。。

1. xmul 包里面你 xsub 没加到 deps 里面去，我手动改了下

```lua
    on_load(function (package)
        for _, dep in ipairs({"xadd", "xsub"}) do
            package:add("deps", dep)
        end
        --[[
        package:add("deps", "xadd ^1.0.0")
        for _,dep in pairs(package:deps()) do
            print('---->' + dep:name())
        end]]
    end)
```

2. 你 foo 的根配置里面也有个 `add_requires("xsub 1.0.1")`

由于配置跟 xmul.xsub 完全相同，我内部缓存共享了，优先取了这个的，但是 override 标识没有了，所以内部没同步配置过去。

我刚改进了下，更新后再试试

**Comment by ivanallen** [comment]
> 有两个问题导致。。
> 
> 1. xmul 包里面你 xsub 没加到 deps 里面去，我手动改了下
> 
> ```lua
>     on_load(function (package)
>         for _, dep in ipairs({"xadd", "xsub"}) do
>             package:add("deps", dep)
>         end
>         --[[
>         package:add("deps", "xadd ^1.0.0")
>         for _,dep in pairs(package:deps()) do
>             print('---->' + dep:name())
>         end]]
>     end)
> ```
> 
> 2. 你 foo 的根配置里面也有个 `add_requires("xsub 1.0.1")`
> 
> 由于配置跟 xmul.xsub 完全相同，我内部缓存共享了，优先取了这个的，但是 override 标识没有了，所以内部没同步配置过去。
> 
> 我刚改进了下，更新后再试试

感谢，现在可以了!
