### ISSUE TITLE
extra option for `add_requires` to automatically `add_packages(pkgs added in `add_requires`)` for all targets.

### ISSUE THREAD

**Issue by 1821746019** [xmake-io/xmake#4085]
### Is your feature request related to a problem? Please describe.

Adding the same package for each target individually is too cumbersome. 

### Describe the solution you'd like

Provide an option to let the pkgs added in `add_requires` automatically added to all targets.

**Comment by SirLynix** [comment]
If your targets depend on each other, you can make their package public so they are inherited.

```lua
add_requires("fmt")

target("myLib")
    add_packages("fmt", { public = true })
    -- ...

target("myApp")
    add_deps("myLib") -- inherit fmt package
```

if not, you can add them in the file scope:
```lua
add_requires("fmt")
add_packages("fmt") -- all targets defined in this files (and subsequently included files) will have package fmt

target("foo")
   -- ...
target("bar")
   -- ...
target("baz")
   -- ...

-- foo, bar and baz all have the fmt package
```

**Comment by 1821746019** [comment]
Oh, I had tried `add_packages` in the global scope before proposing this request but encountered a compile error: `cannot find header file`. Now, I will try it again.
```lua
pkgs={"microsoft-detours 4.0.1", "fltk", "nlohmann_json", "toml++ 3.3.*", "cxxopts 3.1.*"}
add_requires(unpack(pkgs))
add_packages(unpack(pkgs))
--using these are the same, having the same error.
-- add_requires("microsoft-detours 4.0.1", "fltk", "nlohmann_json", "toml++ 3.3.*", "cxxopts 3.1.*")
-- add_packages("microsoft-detours 4.0.1", "fltk", "nlohmann_json", "toml++ 3.3.*", "cxxopts 3.1.*")
```
## Only a part of the packages are added to the target. Is it a bug? The project files were regenerated, and the build failed, so it should not be a problem with VS and MSVC.
![uTools_1692235633980](https://github.com/xmake-io/xmake/assets/107804044/80358efb-5b1c-43b8-8404-fa249723b071)

**Comment by 1821746019** [comment]
Thank you . Now I know how to define a function for the feature I want.
