### ISSUE TITLE
感觉文档不怎么易用

### ISSUE THREAD

**Issue by huanshifeichen** [xmake-io/xmake#409]
对c/c++不算怎么熟悉，但对写Makefile很厌烦，所以想用这个试试。使用过程遇到一些问题

- 没搞清楚  `.xmake` 目录下的配置和 `xmake.lua`的配置的区别是什么? 
  本来是用来配一个简单的 c++项目,按照首页配了后,在vscode里始终不能debug,手动 gdb xxx 发现是没有 符号表, 以为是加 add_cxflags("-g"),但用了也不行,又试了targetr下各种发给发，后来才找到是通过`xmake f -m debug`设置到 debug 模式,找到生成的配置在 `.xmake`目录下`xmake.conf`里。 这个命令没有在 首页文档里出现，要在 xmake usage 的视频里才有, 而且也没说为什么 配置要分到2个地方。
-  文档里的教程太简单,不知道怎么适应到其他项目结构
  对c/c++不算怎么熟悉，打算先用它应用到其他的开源项目。这些开源项目的目录结构一般都比较复杂，不知道怎么应用。 我觉得应该提供一个教程，以一个开源项目为例，使用 xmake 时,怎样适配，这样才能了解在使用过程中还需要配些什么

**Comment by waruqi** [comment]
> 对c/c++不算怎么熟悉，但对写Makefile很厌烦，所以想用这个试试。使用过程遇到一些问题
> 
> * 没搞清楚  `.xmake` 目录下的配置和 `xmake.lua`的配置的区别是什么?

用户只需要配置维护xmake.lua，相当于makefile，但是比makefile更可读，配置编写也更加简单，易上手

`.xmake`是编译过程中临时生成的cache目录，用户不需要去关注这个文件（所以我默认设置为隐藏了），你gitignore里面设置为忽略就行了，删了也没事，相当于vscode下的.vscode目录类似。

>   本来是用来配一个简单的 c++项目,按照首页配了后,在vscode里始终不能debug,手动 gdb xxx 发现是没有 符号表, 以为是加 add_cxflags("-g"),但用了也不行,又试了targetr下各种发给发，后来才找到是通过`xmake f -m debug`设置到 debug 模式,找到生成的配置在 `.xmake`目录下`xmake.conf`里。 这个命令没有在 首页文档里出现，要在 xmake usage 的视频里才有, 而且也没说为什么 配置要分到2个地方。

这个命令，readme里就有 https://github.com/xmake-io/xmake#configure-platform
这里debug模式切换相关说明：https://xmake.io/#/zh/manual?id=is_mode
`.xmake`目录你不要去管它
另外所有命令，你都可以敲--help查看说明：

```console
$ xmake --help
$ xmake f --help
```

> * 文档里的教程太简单,不知道怎么适应到其他项目结构

可通过`xmake create`命令创建各种类型的空工程，直接使用，里面的结构，你也可以直接参考，可以看下文档：https://xmake.io/#/zh/?id=%E5%88%9B%E5%BB%BA%E5%B7%A5%E7%A8%8B

或者你进入源码目录，直接执行`xmake`, 一路回车自动扫描当前源码结构，生成个xmake.lua，然后自己在修修改改下。

>   对c/c++不算怎么熟悉，打算先用它应用到其他的开源项目。这些开源项目的目录结构一般都比较复杂，不知道怎么应用。 我觉得应该提供一个教程，以一个开源项目为例，使用 xmake 时,怎样适配，这样才能了解在使用过程中还需要配些什么

我博客网站上有很多教程和使用介绍的文章和例子，你可以去看看：https://tboox.org/cn/category/#xmake

比如以下入门文章：

https://tboox.org/cn/2018/03/26/build-project-so-simply/
https://tboox.org/cn/2018/06/08/simplify-xmake-description/
https://tboox.org/cn/2017/04/05/project-desciption-examples/
https://tboox.org/cn/2016/10/26/api-scope/

**Comment by huanshifeichen** [comment]
好，谢谢,我再看下博客里的文章。
