### ISSUE TITLE
使用llvm编译sdl报错

### ISSUE THREAD

**Issue by Dozingfiretruck** [xmake-io/xmake#4093]
### Xmake Version

2.8.1

### Operating System Version and Architecture

windows 10

### Describe Bug

使用llvm编译sdl报错

### Expected Behavior

正常编译（以前是正常的）

### Project Configuration

![image](https://github.com/xmake-io/xmake/assets/24759100/3618cb20-6d2f-445b-b088-6c3aa6656ebf)
使用的 llvm:15.07 sdl:2.28.2

### Additional Information and Error Logs

![image](https://github.com/xmake-io/xmake/assets/24759100/ee277db7-e335-4d0e-9a24-dbf6329acdc9)

**Comment by Dozingfiretruck** [comment]
cmake:3.27.1

**Comment by waruqi** [comment]
更新下再试试，xmake update -s dev

**Comment by Dozingfiretruck** [comment]
> 更新下再试试，xmake update -s dev

可以了
