### ISSUE TITLE
需要在Xcode .app文件生成之后执行脚本的命令

### ISSUE THREAD

**Issue by JerryMu** [xmake-io/xmake#4095]
### Is your feature request related to a problem? Please describe.

after_buid，after_link等命令都会在生成.app文件生成前执行，缺少在.app文件生成后执行的脚本。很多时候，需要在生成.app文件后导入资源文件。

### Describe the solution you'd like

添加新的在.app文件生成后执行的脚本。

### Describe alternatives you've considered

或者将生成.app文件移动到after_build之前，因为一般认为after_build会在所有指令执行后运行。

**Comment by waruqi** [comment]
因为生成 .app 也是在 xcode.application rule 的 after_build 里面处理的。你得搞个 rule 依赖它才行。。


```lua
rule("test")
    add_deps("xcode.application")
    after_build(function ()
        print("xxx")
    end)

target("test")
    add_rules("xcode.application")
    add_files("src/*.m", "src/**.storyboard", "src/*.xcassets")
    add_files("src/Info.plist")
    add_rules("test")
```

**Comment by JerryMu** [comment]
了解了，谢谢。
