### ISSUE TITLE
Add support for `-mfmt=num` in `utils.glsl2spv`

### ISSUE THREAD

**Issue by jube** [xmake-io/xmake#4099]
### Is your feature request related to a problem? Please describe.

glslc provides a `-mfmt=num` option that generates a text file containing 32 bit hex numbers (in the endianness of the host) instead of bytes. When using the `utils.glslspv`, the `bin2c` option generates a text file containing bytes, that requires the user to cast (`reinterpret_cast` in C++) to an array of `uint32_t` for the vulkan library.

For example, the start of a file generated with `-mfmt=num` option:
```
0x07230203,
```

And the same file generated with `bin2c`:
```
0x03, 0x02, 0x23, 0x07,
```

### Describe the solution you'd like

I see two possible solutions:

- add support for `-mfmt=num` directly in `utils.glsl2spv`, as suggested in the title of this issue
- add support for generating 32 bit hex numbers in `bin2c`, which would be a more general solution as it could be used for other purposes

**Comment by waruqi** [comment]
You can only cast to uint32_t from byte. 

```c
#include <stdio.h>
#include <inttypes.h>

unsigned char d[] = {0x03, 0x02, 0x23, 0x07};

int main(int argc, char** argv)
{
    printf("0x%x\n", *((uint32_t*)d));
    return 0;
}
```

> 0x7230203
