### ISSUE TITLE
添加 qrc 文件到VS工程文件

### ISSUE THREAD

**Issue by zhin2929** [xmake-io/xmake#4100]
### 你在什么场景下需要该功能？

创建qt项目时，通过add_files("src/res/res.qrc")添加 qrc 文件，生成 VS 工程文件后，能显示在VS IDE的文件夹里。
如图那个res.qrc文件，现在是不会添加到项目里的。
![image](https://github.com/xmake-io/xmake/assets/15818471/dfa7582a-71d0-4245-b238-f3d762e6af58)

### 描述可能的解决方案

对待qrc文件就和ui文件一样处理应该可以。

### 其他信息

```lua
add_frameworks("QtNetwork")
target("qtTest")
    add_rules("qt.widgetapp", "qt.qrc")
    add_headerfiles("src/**.h")
    add_files("src/*.cpp")
    add_files("src/**.h")
    add_files("src/ui/*.ui")
    add_files("src/res/res.qrc")
```

**Comment by waruqi** [comment]
用 add_headerfiles 加一下 qrc 就能显示了

**Comment by zhin2929** [comment]
> 用 add_headerfiles 加一下 qrc 就能显示了

OK，那没问题了。

**Comment by waruqi** [comment]
extrafiles 分支，我加了个接口，也可以试试 `add_extrafiles` https://github.com/xmake-io/xmake/issues/2384#issuecomment-1685917912
