### ISSUE TITLE
支持强制包含

### ISSUE THREAD

**Issue by jingkaimori** [xmake-io/xmake#4101]
### 你在什么场景下需要该功能？

墨干项目通过强制包含来引入配置文件，gcc 和 msvc 都支持强制包含选项，而且vscode的C++插件提供了强制包含的配置项。

* gcc: [`-include`](https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html#index-include)
* clang: [`-include`](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-include-file)
* msvc: [`/FI`](https://learn.microsoft.com/en-us/cpp/build/reference/fi-name-forced-include-file?view=msvc-170#:~:text=To%20set%20this%20compiler%20option%20in%20the%20Visual,File%20property.%20To%20set%20this%20compiler%20option%20programmatically)
* armcc: `--preinclude`, [ARM® Compiler armcc User Guide, §8.154](https://documentation-service.arm.com/static/5eb946b50f1c1e0dae6ee21e)
* sdcc: `-include`, same as gcc, but needing further confirmation.
* tcc: not supported.

xmake 需要引入新的配置项，并且改进 msvc 插件，从而生成对应的强制包含信息

### 描述可能的解决方案

- [x] 定义域下为 target 添加`set_forceinclude`接口：
- [ ] vscode 插件根据上述接口修改`c_cpp_properties.json`文件

```lua
target("test")
    set_forceinclude({"src/config.h", "src/config_after.h"})
```

### 描述你认为的候选方案

目前的解决方案：

```lua
if is_plat("windows") then
    add_cxxflags("-FI " .. path.absolute("$(buildir)\\L1\\config.h"))
else
    add_cxxflags("-include $(buildir)/L1/config.h")
end
```

**Comment by waruqi** [comment]
改了下，再试试

```lua
add_forceincludes("config.h")
add_includedirs("$(buildir)/L1")
```

默认 add_forceincludes 匹配 c/c++/objc。如果仅仅只想匹配 c++ 可以

```lua
add_forceincludes("config.h", {sourcekinds = "cxx"})
```

如果想同时匹配多个源文件类型，可以


```lua
add_forceincludes("config.h", {sourcekinds = {"cxx", "mxx"}})
```

**Comment by jingkaimori** [comment]
现在能跑通了，`add_forceincludes`添加的各个文件出现在命令行的顺序能控制吗？
