### ISSUE TITLE
Compile minhook failed

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#411]
我也遇到同样问题，测试https://github.com/TsudaKageyu/minhook
xmake.lua:
```
-- add rules: debug/release
add_rules("mode.debug", "mode.release")

-- define target
target("libMinHook")
    -- set kind
    set_kind("static")
    
    add_defines("WIN32","NDEBUG","_LIB","STRICT")
    
    add_includedirs("include/")

    -- add files
    add_files("src/buffer.c")
    
    if is_arch("x86") then
        add_files("src/HDE/hde32.c")
    elseif is_arch("x86_64") then
        add_files("src/HDE/hde64.c")
    end

    add_files("src/hook.c")
    add_files("src/trampoline.c")
    
    
target("MinHook")
    
    set_kind("shared")
    
    add_deps("libMinHook")
    add_links("libMinHook")
    
    add_defines("_WINDOWS", "_USRDLL", "MINHOOK_EXPORTS")
    
    -- add_files("dll_resources/MinHook.rc")
    add_shflags("/DEF:dll_resources/MinHook.def", {force = true})
```

注释这行`-- add_files("dll_resources/MinHook.rc")`之后用xmake -v输出就会有：
 > "link.exe -dll" -libpath:build_obj\\\\windows\\\\x86\\\\debug -debug -pdb:build_obj\\windows\\x86\\debug\\MinHook.pdb libMinHook.lib /DEF:dll_resources/MinHook.def -nologo -machine:x86 -out:build_obj\\windows\\x86\\debug\\MinHook.dll

取消注释：
 > "link.exe -dll" /DEF:dll_resources/MinHook.def -nologo -machine:x86 -out:build_obj\\windows\\x86\\debug\\MinHook.dll build_obj\\.objs\\MinHook\\windows\\x86\\debug\\dll_resources\\MinHook.rc.obj
error: MinHook.def : error LNK2001: 无法解析的外部符号 MH_ApplyQueued
MinHook.def : error LNK2001: 无法解析的外部符号 MH_CreateHook
MinHook.def : error LNK2001: 无法解析的外部符号 MH_CreateHookApi
MinHook.def : error LNK2001: 无法解析的外部符号 MH_CreateHookApiEx
MinHook.def : error LNK2001: 无法解析的外部符号 MH_DisableHook
MinHook.def : error LNK2001: 无法解析的外部符号 MH_EnableHook
MinHook.def : error LNK2001: 无法解析的外部符号 MH_Initialize
MinHook.def : error LNK2001: 无法解析的外部符号 MH_QueueDisableHook
MinHook.def : error LNK2001: 无法解析的外部符号 MH_QueueEnableHook
MinHook.def : error LNK2001: 无法解析的外部符号 MH_RemoveHook
MinHook.def : error LNK2001: 无法解析的外部符号 MH_StatusToString
MinHook.def : error LNK2001: 无法解析的外部符号 MH_Uninitialize
build_obj\windows\x86\debug\MinHook.lib : fatal error LNK1120: 12 个无法解析的外部命令

_Originally posted by @bstaint in https://github.com/xmake-io/xmake/issues/372#issuecomment-487578168_

**Comment by waruqi** [comment]
```lua
target("MinHook")
    set_kind("shared")
```
你的这个minhook shared target，没有添加任何.c/cpp源文件，也没有调用libminhook中的任何接口，属于空target，无法生成dll。。

另外
```lua
    add_deps("libMinHook")
    add_links("libMinHook") -- 此处没有必要，add_deps会自动link对应依赖的static库。
```

请直接添加源文件生成dll

```lua
-- add rules: debug/release
add_rules("mode.debug", "mode.release")

-- define target
target("MinHook")
    set_kind("shared")
    add_defines("WIN32","NDEBUG","_LIB","STRICT")
    add_includedirs("include/")
    add_files("src/buffer.c")
    
    if is_arch("x86") then
        add_files("src/HDE/hde32.c")
    elseif is_arch("x86_64") then
        add_files("src/HDE/hde64.c")
    end

    add_files("src/hook.c")
    add_files("src/trampoline.c")
   
    add_defines("_WINDOWS", "_USRDLL", "MINHOOK_EXPORTS")
    
    add_files("dll_resources/MinHook.rc")
    add_shflags("/DEF:dll_resources/MinHook.def")
```

**Comment by bstaint** [comment]
哦 感谢
