### ISSUE TITLE
add_extrafiles 不能模糊匹配

### ISSUE THREAD

**Issue by zhin2929** [xmake-io/xmake#4110]
### Xmake 版本

xmake v2.8.2+HEAD.57212c681

### 操作系统版本和架构

windows 10 21H2

### 描述问题

只能匹配文件名，不能模糊匹配多个文件。
![}W8Q7EBPY 4%)$QV}F2Y`TW](https://github.com/xmake-io/xmake/assets/15818471/8497df24-9e04-41ac-8d69-d35394095843)

### 期待的结果

`add_extrafiles("src/res/**.qrc")` 能匹配该目录下，包括子目录的多个qrc文件。

### 工程配置

add_extrafiles("src/res/**.qrc")

### 附加信息和错误日志

![}W8Q7EBPY 4%)$QV}F2Y`TW](https://github.com/xmake-io/xmake/assets/15818471/8497df24-9e04-41ac-8d69-d35394095843)

**Comment by waruqi** [comment]
再试试，xmake update -s dev

**Comment by zhin2929** [comment]
> 再试试，xmake update -s dev

可以了
