### ISSUE TITLE
使用emscripten作为wasm的toolchain无法检测对应的Python和emscripten

### ISSUE THREAD

**Issue by darcy-shen** [xmake-io/xmake#4119]
### Xmake 版本

2.8.2

### 操作系统版本和架构

Windows 11

### 描述问题

无法检测     add_requires("emscripten") 之后安装 Python 和 emscripten

### 期待的结果

能够自动检测Python和emscripten，不需要手动设置PATH

### 工程配置

See https://github.com/XmacsLabs/xmake-hello-world/blob/main/xmake.lua

### 附加信息和错误日志

```
$ xmake config -p wasm
checking for architecture ... wasm32
Exception: xmake exited with 4294967295
[tty 490]:1:1: xmake config -p wasm
~\git\hello> xmake config -p wasm -vD
checking for architecture ... wasm32
checking for emsdk directory ... no
checkinfo: cannot runv(emcc.bat --version), No such file or directory
checking for emcc.bat ... no
checkinfo: cannot runv(emcc.exe --version), No such file or directory
checking for emcc ... no
checkinfo: cannot runv(unzip.exe -v), No such file or directory
checking for unzip ... no
checking for 7z ... C:\Users\darcy\scoop\apps\xmake\current\winenv\bin\7z
checking for git ... ok
checkinfo: cannot runv(gzip.exe --version), No such file or directory
checking for gzip ... no
git rev-parse HEAD
checking for python ... no
checking for python3 ... no
checking for python ... no
checking for python2 ... no
checking for python ... no
checking for emscripten ... no
error: @programdir\core\main.lua:300: stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:932]:
    [@programdir\actions\config\main.lua:133]: in function '_check_target_toolchains'
    [@programdir\actions\config\main.lua:400]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\base\task.lua:501]: in function 'run'
    [@programdir\core\main.lua:298]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:404]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:921: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:300: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>
Exception: xmake exited with 4294967295
[tty 491]:1:1: xmake config -p wasm -vD                       
```

**Comment by waruqi** [comment]
不是所有工具链都支持绑定包，要改工具链配置。。目前 emcc toolchain 还没加上 package 绑定支持。。

要改 emcc 的 on_check 加上 package 检测支持才行。。https://github.com/xmake-io/xmake/blob/8bc2fe44da59c56aaf453daff542db8565d2197c/xmake/toolchains/cross/check.lua#L40

**Comment by darcy-shen** [comment]
在Windows上面还没有搞定，在Linux现在只要设置 `EMSDK` 这个环境变量就可以了：
``` elvish
#!/usr/bin/env elvish
var pkg_info = (xrepo fetch --json emscripten | from-json)
var emsdk_path = $pkg_info[0][artifacts][installdir]
set-env EMSDK $emsdk_path

xmake config -p wasm -vD
```
https://github.com/XmacsLabs/xmake-hello-world/blob/main/bin/config_wasm

**Comment by waruqi** [comment]
再试试 https://github.com/xmake-io/xmake/pull/4123

```console
xmake update -s dev
xrepo update-repo
xmake f -p wasm -cvD
xmake
```

**Comment by darcy-shen** [comment]
dev这个不行，感觉应该是emcc：
```
- xmake update -s dev
+ xmake update -s emcc
```

**Comment by waruqi** [comment]
嗯 说错了，还没 merge 到 dev

```
xmake update -s github:xmake-io/xmake#emcc
```

**Comment by darcy-shen** [comment]
在Windows上面的WSL Ubuntu 22.04 里面验证了，emcc这个分支已经解决了这个问题。

**Comment by darcy-shen** [comment]
第一次执行 `xmake f -p wasm -cvD` ，会有 `emcc` 的版本显示：
```
checking for emscripten ... no
{
  artifacts = {
    installdir = "C:\Users\darcy\AppData\Local\.xmake\packages\e\emscripten\3.1.42\4ecd018e3b6b4e549c8c83e93d2e9944"
  },
  arch = "x64",
  kind = "toolchain",
  description = "Emscripten: An LLVM-to-WebAssembly Compiler.",
  version = "3.1.42",
  deps = {
    python = {
      version = "3.11.3",
      buildhash = "81b03999b7844cbe8874e267043e9594"
    }
  },
  mode = "release",
  librarydeps = { },
  plat = "windows",
  repo = {
    name = "xmake-repo",
    branch = "master",
    url = "https://gitee.com/tboox/xmake-repo.git",
    commit = "be832f2cace05fd467886c91313ca5e7e5598dce"
  },
  configs = {
    shared = false,
    debug = false
  },
  envs = {
    JAVA_HOME = {
      "C:\Users\darcy\AppData\Local\.xmake\packages\e\emscripten\3.1.42\4ecd018e3b6b4e549c8c83e93d2e9944\java\8.152_64bit"
    },
    EMSDK = {
      "C:\Users\darcy\AppData\Local\.xmake\packages\e\emscripten\3.1.42\4ecd018e3b6b4e549c8c83e93d2e9944"
    },
    EMSDK_NODE = {
      "C:\Users\darcy\AppData\Local\.xmake\packages\e\emscripten\3.1.42\4ecd018e3b6b4e549c8c83e93d2e9944\node\16.20.0_64bit\bin\node.exe"
    },
    EMSDK_PYTHON = {
      "C:\Users\darcy\AppData\Local\.xmake\packages\e\emscripten\3.1.42\4ecd018e3b6b4e549c8c83e93d2e9944\python\3.9.2-nuget_64bit\python.exe"
    },
    PATH = {
      "bin",
      "C:\Users\darcy\AppData\Local\.xmake\packages\e\emscripten\3.1.42\4ecd018e3b6b4e549c8c83e93d2e9944\upstream\emscripten",
      "C:\Users\darcy\AppData\Local\.xmake\packages\e\emscripten\3.1.42\4ecd018e3b6b4e549c8c83e93d2e9944",
      "C:\Users\darcy\AppData\Local\.xmake\packages\e\emscripten\3.1.42\4ecd018e3b6b4e549c8c83e93d2e9944\node\16.20.0_64bit\bin"
    }
  },
  license = "MIT",
  name = "emscripten"
}

emcc.bat --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.42 (6ede0b8fc1c979bb206148804bfb48b472ccc3da)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by darcy-shen** [comment]
我在Windows上面，需要设置 EMSDK 和 EMSDK_PYTHON 这两个环境变量才能够work

```
set-env EMSDK_PYTHON C:\Users\darcy\AppData\Local\.xmake\packages\e\emscripten\3.1.42\4ecd018e3b6b4e549c8c83e93d2e9944\python\3.9.2-nuget_64bit\python.exe
set-env EMSDK C:\Users\darcy\AppData\Local\.xmake\packages\e\emscripten\3.1.42\4ecd018e3b6b4e549c8c83e93d2e9944
```

**Comment by darcy-shen** [comment]
如果要让单元测试能够work，应该还需要 EMSDK_NODE 里面指定版本的 node


```
        on_run(function (target)
            cmd = "node $(buildir)/wasm/wasm32/$(mode)/hello.js"
            print("> " .. cmd)
            os.exec(cmd)
        end)
```
在我的hello world项目里面，我的on_run是这样写的，如果有 EMSDK_NODE的话，我直接把直接调用node，改为环境变量，这样测试也搞定了。

**Comment by waruqi** [comment]
> 第一次执行 `xmake f -p wasm -cvD` ，会有 `emcc` 的版本显示：
> 
> ```
> checking for emscripten ... no
> {
>   artifacts = {
>     installdir = "C:\Users\darcy\AppData\Local\.xmake\packages\e\emscripten\3.1.42\4ecd018e3b6b4e549c8c83e93d2e9944"
>   },
>   arch = "x64",
>   kind = "toolchain",
>   description = "Emscripten: An LLVM-to-WebAssembly Compiler.",
>   version = "3.1.42",
>   deps = {
>     python = {
>       version = "3.11.3",
>       buildhash = "81b03999b7844cbe8874e267043e9594"
>     }
>   },
>   mode = "release",
>   librarydeps = { },
>   plat = "windows",
>   repo = {
>     name = "xmake-repo",
>     branch = "master",
>     url = "https://gitee.com/tboox/xmake-repo.git",
>     commit = "be832f2cace05fd467886c91313ca5e7e5598dce"
>   },
>   configs = {
>     shared = false,
>     debug = false
>   },
>   envs = {
>     JAVA_HOME = {
>       "C:\Users\darcy\AppData\Local\.xmake\packages\e\emscripten\3.1.42\4ecd018e3b6b4e549c8c83e93d2e9944\java\8.152_64bit"
>     },
>     EMSDK = {
>       "C:\Users\darcy\AppData\Local\.xmake\packages\e\emscripten\3.1.42\4ecd018e3b6b4e549c8c83e93d2e9944"
>     },
>     EMSDK_NODE = {
>       "C:\Users\darcy\AppData\Local\.xmake\packages\e\emscripten\3.1.42\4ecd018e3b6b4e549c8c83e93d2e9944\node\16.20.0_64bit\bin\node.exe"
>     },
>     EMSDK_PYTHON = {
>       "C:\Users\darcy\AppData\Local\.xmake\packages\e\emscripten\3.1.42\4ecd018e3b6b4e549c8c83e93d2e9944\python\3.9.2-nuget_64bit\python.exe"
>     },
>     PATH = {
>       "bin",
>       "C:\Users\darcy\AppData\Local\.xmake\packages\e\emscripten\3.1.42\4ecd018e3b6b4e549c8c83e93d2e9944\upstream\emscripten",
>       "C:\Users\darcy\AppData\Local\.xmake\packages\e\emscripten\3.1.42\4ecd018e3b6b4e549c8c83e93d2e9944",
>       "C:\Users\darcy\AppData\Local\.xmake\packages\e\emscripten\3.1.42\4ecd018e3b6b4e549c8c83e93d2e9944\node\16.20.0_64bit\bin"
>     }
>   },
>   license = "MIT",
>   name = "emscripten"
> }
> 
> emcc.bat --version
> emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.42 (6ede0b8fc1c979bb206148804bfb48b472ccc3da)
> Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
> This is free and open source software under the MIT license.
> There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> ```

这个不用管它，安装那个包 -vD 下会显示信息

**Comment by waruqi** [comment]
> 我在Windows上面，需要设置 EMSDK 和 EMSDK_PYTHON 这两个环境变量才能够work
> 
> 下面这个是elvish的语法
> 
> ```
> set-env EMSDK_PYTHON C:\Users\darcy\AppData\Local\.xmake\packages\e\emscripten\3.1.42\4ecd018e3b6b4e549c8c83e93d2e9944\python\3.9.2-nuget_64bit\python.exe
> set-env EMSDK C:\Users\darcy\AppData\Local\.xmake\packages\e\emscripten\3.1.42\4ecd018e3b6b4e549c8c83e93d2e9944
> ```

这些 envs 我刚 emcc 分支自动加上了，再试试。

```
xmake f -p wasm -c
```

**Comment by waruqi** [comment]
> 经过这个issue的讨论，然后基于 xmake 2.8.2 ，我可以结合 Elvish 脚本设置环境变量，基本搞定了 Ubuntu 和 Windows 上面使用 wasm 的开发的流程。
> 
> 希望 xmake 2.8.3 能有更好的支持！

envs 是可以 toolchains 里自动加的，我刚 emcc 分支改进过了，理论上用户不需要设置任何东西。

**Comment by darcy-shen** [comment]
再测试了一下，Windows上面也已经可以了

**Comment by darcy-shen** [comment]
现在还有一个问题是 toolchain 里面 EMSDK_NODE 这个环境变量如何在 on_run 里面使用，因为 `EMSDK_NODE/..` 这个目录并没有自动加到 PATH 里面

**Comment by waruqi** [comment]
> 现在还有一个问题是 toolchain 里面 EMSDK_NODE 这个环境变量如何在 on_run 里面使用，因为 `EMSDK_NODE/..` 这个目录并没有自动加到 PATH 里面

add_packages 会自动绑定 envs 到 on_run ，但是要设置到 PATH，你得 toolchain package 那个包配置里，把它加入 PATH env

**Comment by darcy-shen** [comment]
> 你得 toolchain package 那个包配置里，把它加入 PATH env

所以只要在 xrepo 里面做如上改动就可以了，是吧？

**Comment by waruqi** [comment]
嗯 改进下对应的包，然后本地重装下

**Comment by darcy-shen** [comment]
在ci里面试了一下，还是有一些问题：https://github.com/XmacsLabs/lolly/actions/runs/5978209028/job/16219827146?pr=85

我感觉需要先 `xrepo install emscripten`，然后再 `xmake config -p wasm`。

lolly这个比xmake-hello-world要稍稍复杂一些

**Comment by darcy-shen** [comment]
有依赖的情况还不行，见：https://github.com/XmacsLabs/lolly/pull/85
```
> xmake config -p wasm
checking for architecture ... wasm32
checking for HAVE_GETTIMEOFDAY ... no
checking for HAVE_STDLIB_H ... no
checking for HAVE_TIME_T ... no
checking for HAVE_INTPTR_T ... no
checking for HAVE_INTTYPES_H ... no
checking for CONFIG_LARGE_POINTER ... no
checking for posix_thread ... no
checking for HAVE_STDINT_H ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> doctest 2.4.11
please input: y (y/n/m)
y
  => install doctest 2.4.11 .. failed

cannot get program for cxx
if you want to get more verbose errors, please see:
  -> C:\Users\darcy\AppData\Local\.xmake\cache\packages\2308\d\doctest\2.4.11\installdir.failed\logs\install.txt
error: install failed!
Exception: xmake exited with 4294967295
[tty 91]:1:1: xmake config -p wasm
```

**Comment by darcy-shen** [comment]
有依赖的情况，通过脚本设置 EMSDK 的环境变量是可以的：
https://github.com/XmacsLabs/lolly/blob/main/bin/config_wasm

**Comment by darcy-shen** [comment]
另外的问题我新建issue吧，这个问题可以认为是已经解决了
