### ISSUE TITLE
Support for cppfront

### ISSUE THREAD

**Issue by paul-reilly** [xmake-io/xmake#4132]
### Xmake Version

v2.8.1+dev.bdb28e5

### Operating System Version and Architecture

Linux 6.1.44-1-MANJARO x86_64 GNU/Linux

### Describe Bug

When running this xmake.lua file to generate a single .cpp file, the build fails on first run even though the .cpp file is generated.

```lua
rule("cppfront")
    set_extensions(".cpp2")
    on_load(function(target)
        local rule = target:rule("c++.build"):clone()
        rule:add("deps", "cppfront", { order = true })
        target:rule_add(rule)
    end)

    on_build_file(function(target, sourcefile, opt)
        cprint('${cyan}cppfront compiling: ${bright green}%s', sourcefile)
        local dir = path.directory(sourcefile)
        local outdata, errdata = os.iorunv("cppfront", { sourcefile })
        cprint("res: '%s'  :  '%s'", outdata, errdata)
    end)


target("app")
    set_kind("binary")
    add_rules("cppfront")
    add_files("src/*.cpp2")
    add_files("src/*.cpp")
    add_packages("fmt")
```

### Expected Behavior

The generated main.cpp is compiled.

### Project Configuration

Test cpp2 file:
```cpp2
main: () -> int = 
    println("Hello world!\n");

println: (msg: _) -> int = {
    std::cout << "msg: " << msg;
    return 0;
}
```

### Additional Information and Error Logs

Message with failed compilation:
```bash
>xmake -rv                                  ✔ 
cppfront compiling: src/main.cpp2
res: 'src/main.cpp2... ok (all Cpp2, passes safety checks)

'  :  ''
[ 50%]: linking.release app
/usr/bin/g++ -o build/linux/x86_64/release/app -m64 -L/home/dev/.xmake/packages/f/fmt/10.0.0/cf4a2efd8ed34f738dfde8eaa4fb9660/lib -lfmt
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/Scrt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'
collect2: error: ld returned 1 exit status
error: execv(/usr/bin/g++ -o build/linux/x86_64/release/app -m64 -L/home/dev/.xmake/packages/f/fmt/10.0.0/cf4a2efd8ed34f738dfde8eaa4fb9660/lib -lfmt) failed(1)
warning: ./xmake.lua:26: cannot match add_files("src/*.cpp") in target(app)
```

**Comment by waruqi** [comment]
I will attempt to add a builtin cppfront rule.

**Comment by paul-reilly** [comment]
Official cppfront support would be a good addition to xmake. 

However this issue is general to files generated at build time for compilation with that pattern, which is used in the xmake documentation. I have seen it when adding a rule for files generated by `drogon_ctl`, for example.

**Comment by waruqi** [comment]
see https://github.com/xmake-io/xmake/tree/master/tests/projects/other/autogen_codedep

**Comment by paul-reilly** [comment]
Thanks, the docs imply that the rule in the first post here would work:

https://xmake.io/#/manual/custom_rule?id=ruleadd_deps

I don't think a description of the autogen_codedep pattern is in the docs yet.

**Comment by waruqi** [comment]
> https://xmake.io/#/manual/custom_rule?id=ruleadd_deps


This is just to say the dynamic creation and injection of rules, not the automatic generation of code.

It's just that I happened to put in a small example of dynamic injection about cppfront.

**Comment by waruqi** [comment]
I added it. cppfront https://github.com/xmake-io/xmake/pull/4140

**Comment by cassepipe** [comment]
Thanks waruqi !

**Comment by hros** [comment]
It is great to see the `xmake` has support for `cppfront`
How do I use this?
I created a cpp project and inserted the `hello.cpp2` file from the `cppfront` [documentation](https://hsutter.github.io/cppfront/welcome/hello-world/) in the `src` directory and commented out the code in the generated `main.cpp`, however the `xmake build` does not try to build the `hello.cpp2` file
What do I have to do differently to setup a project for `cppfront`?

**Comment by waruqi** [comment]
see https://github.com/xmake-io/xmake/tree/dev/tests/projects/cppfront/console

**Comment by hros** [comment]
thanks @waruqi  !!
modifying `xmake.lua` according to your example works perfectly

when I came across cppfront, I thought it would be great if it could be an `xmake` target
your project "prevented" me from learning to create an xmake package ;)

since I'm new to `xmake` and `cppfront`, I have a few questions:
1. is it possible to `xmake create` a `cpp2` project, or do I have to manually edit the `xmake.lua` file?
2. if I understand correctly your solution installs a prebuilt `cppfront` in the `.xmake` directory. How can I update the `cppfront` - currently using v0.7.4 to the latest version = v0.8.0? (either updating your package, or pointing to my installed version of `cppfront`)
3. how can I see the compilation commands in the `cppfront` rules?

**Comment by waruqi** [comment]
> is it possible to xmake create a cpp2 project, or do I have to manually edit the xmake.lua file?

right, no template now.

> if I understand correctly your solution installs a prebuilt cppfront in the .xmake directory. How can I update the cppfront - currently using v0.7.4 to the latest version = v0.8.0? (either updating your package, or pointing to my installed version of cppfront)

you can open a pr to update it.
https://github.com/xmake-io/xmake-repo/blob/dev/packages/c/cppfront/xmake.lua

> how can I see the compilation commands in the cppfront rules?

```console
xmake -rv
```

**Comment by hros** [comment]
> > If I understand correctly, your solution installs a prebuilt cppfront in the .xmake directory. How can I update the cppfront - currently using v0.7.4 to the latest version = v0.8.0? (either updating your package or pointing to my installed version of cppfront)
> 
> You can open a pr to update it. https://github.com/xmake-io/xmake-repo/blob/dev/packages/c/cppfront/xmake.lua
> 

I'll add a pr.
Do I need to add another line `add_versions("v0.8.0", "<sha256>")`?
It is not clear to me from the [docs](https://[xmake](https://xmake.io/mirror/manual/package_dependencies.html#add_urls).io/mirror/manual/package_dependencies.html#add_urls) how to get the sha256 value of a release tag in the github project

by the way, looking at your [cppfront package](https://github.com/xmake-io/xmake-repo/blob/dev/packages/c/cppfront/xmake.lua), where do you actually build `cppfront` and create the `bin` and `include` directories in the `.xmake/packages` tree?

**Comment by qudix** [comment]
`add_versions("v0.8.0", "7fb573599960bc0a46a71ed103ff97adbf938d4a0df754dc952a44fdcacfc571")`

The first url goes for a tag `v0.8.0` that ends with `.tar.gz`. I just used 7z's included hash checker to get the sha256 of the `.tar.gz` archive, but you can use whatever tool you'd like.

Of course, this is assuming there haven't been breaking changes in in this newer version of cppfront that would require further modifications to the package to build properly.

**Comment by hros** [comment]
Thanks @qudix 
I submitted a PR, which (hopefully) will be merged and work
The ability to specify the version tag in the `add_requires` command is great. A nice addition (if it is not implemented, somehow, already) would be to add project version specifiers ('*', '^') and a "latest" option

Out of curiosity, wanting to learn how `xmake` packages are developed and deployed; where are the commands used to build and install the `cppfront` package?

**Comment by hros** [comment]
I tried to install the `cppfront` package on a mac and received the error (actually a warning, but it prevents installation):
> the following packages are unsupported on macosx/arm64

Where can I see the *code* of the package, rather than the [project template](https://github.com/xmake-io/xmake/tree/dev/tests/projects/cppfront/console), so that I can add mac support?

**Comment by qudix** [comment]
@hros 
https://github.com/xmake-io/xmake-repo/blob/master/packages/c/cppfront/xmake.lua#L32

If cppfront does support macos for arm64, then simply removing `|x86_64` specifier from `macosx` should suffice
