### ISSUE TITLE
make build problem in ubuntu

### ISSUE THREAD

**Issue by sanwenyun88** [xmake-io/xmake#414]
problem:

$ make build
compiling xmake-core ...

=============================================================================
compile:
    plat:               linux
    arch:               arm
    host:               linux
    demo:               y
    prof:               n
    debug:              n
    small:              n
    ccache:
    distcc:

packages:
    tbox:               y
    luajit:             y
    base:               y

directories:
    install:
    package:

toolchains:
    bin:
    pre:
    sdk:

flags:
    cflag:
    ccflag:
    cxflag:
    mflag:
    mmflag:
    mxflag:
    ldflag:
    asflag:
    arflag:
    shflag:

clean xmake
clean lcurses
clean sv
clean luajit
clean tbox
clean xmake
clean demo
make xmake
make lcurses
compile.r lcurses.c
link liblcursesr.a
make sv
compile.r src/comp.c
compile.r src/id.c
compile.r src/num.c
compile.r src/range.c
compile.r src/semvers.c
compile.r src/utils.c
compile.r src/version.c
link libsvr.a
make luajit
compile.r src/lib_aux.c
compile.r src/lib_base.c
compile.r src/lib_bit.c
compile.r src/lib_debug.c
compile.r src/lib_ffi.c
compile.r src/lib_init.c
compile.r src/lib_io.c
compile.r src/lib_jit.c
compile.r src/lib_math.c
compile.r src/lib_os.c
compile.r src/lib_package.c
compile.r src/lib_string.c
compile.r src/lib_table.c
compile.r src/lj_alloc.c
compile.r src/lj_api.c
compile.r src/lj_asm.c
compile.r src/lj_bc.c
compile.r src/lj_bcread.c
compile.r src/lj_bcwrite.c
compile.r src/lj_buf.c
compile.r src/lj_carith.c
compile.r src/lj_ccall.c
compile.r src/lj_ccallback.c
compile.r src/lj_cconv.c
compile.r src/lj_cdata.c
compile.r src/lj_char.c
compile.r src/lj_clib.c
compile.r src/lj_cparse.c
compile.r src/lj_crecord.c
compile.r src/lj_ctype.c
compile.r src/lj_debug.c
compile.r src/lj_dispatch.c
compile.r src/lj_err.c
compile.r src/lj_ffrecord.c
compile.r src/lj_func.c
compile.r src/lj_gc.c
compile.r src/lj_gdbjit.c
compile.r src/lj_ir.c
compile.r src/lj_lex.c
compile.r src/lj_lib.c
compile.r src/lj_load.c
compile.r src/lj_mcode.c
compile.r src/lj_meta.c
compile.r src/lj_obj.c
compile.r src/lj_opt_dce.c
compile.r src/lj_opt_fold.c
compile.r src/lj_opt_loop.c
compile.r src/lj_opt_mem.c
compile.r src/lj_opt_narrow.c
compile.r src/lj_opt_sink.c
compile.r src/lj_opt_split.c
compile.r src/lj_parse.c
compile.r src/lj_profile.c
compile.r src/lj_record.c
compile.r src/lj_snap.c
compile.r src/lj_state.c
compile.r src/lj_str.c
compile.r src/lj_strfmt.c
compile.r src/lj_strfmt_num.c
compile.r src/lj_strscan.c
compile.r src/lj_tab.c
compile.r src/lj_trace.c
compile.r src/lj_udata.c
compile.r src/lj_vmevent.c
compile.r src/lj_vmmath.c
compile.r src/autogen/linux/jit/arm/lj_vm.S
make[3]: *** [src/autogen/linux/jit/arm/lj_vm.o] Error 1
make[2]: *** [DEP_PROS_luajit_all] Error 2
buildvm_arm.dasc: Assembler messages:
buildvm_arm.dasc:11: Error: unknown pseudo-op: `.fnstart'
buildvm_arm.dasc:12: Error: unknown pseudo-op: `.save'
buildvm_arm.dasc:13: Error: unknown pseudo-op: `.vsave'
buildvm_arm.dasc:14: Error: unknown pseudo-op: `.save'
buildvm_arm.dasc:15: Error: unknown pseudo-op: `.pad'
buildvm_arm.dasc:276: Error: no such instruction: `bl lj_tab_len'
buildvm_arm.dasc:488: Error: no such instruction: `bl pow'
buildvm_arm.dasc:499: Error: no such instruction: `bl lj_meta_cat'
buildvm_arm.dasc:581: Error: no such instruction: `blne lj_gc_barrieruv'
buildvm_arm.dasc:595: Error: no such instruction: `blne lj_gc_barrieruv'
buildvm_arm.dasc:625: Error: no such instruction: `bl lj_func_closeuv'
buildvm_arm.dasc:636: Error: no such instruction: `bl lj_func_newL_gc'
buildvm_arm.dasc:650: Error: no such instruction: `bl lj_tab_new'
buildvm_arm.dasc:654: Error: no such instruction: `bl lj_gc_step_fixtop'
buildvm_arm.dasc:665: Error: no such instruction: `bl lj_tab_dup'
buildvm_arm.dasc:669: Error: no such instruction: `bl lj_gc_step_fixtop'
buildvm_arm.dasc:781: Error: no such instruction: `bl lj_tab_newkey'
buildvm_arm.dasc:815: Error: no such instruction: `bl lj_tab_reasize'
buildvm_arm.dasc:920: Error: no such instruction: `bl lj_state_growstack'
buildvm_arm.dasc:1242: Error: no such instruction: `bl lj_state_growstack'
buildvm_arm.dasc:1283: Error: no such instruction: `bl _Unwind_Complete'
buildvm_arm.dasc:1285: Error: no such instruction: `bl _Unwind_DeleteException'
buildvm_arm.dasc:1302: Error: no such instruction: `bl lj_state_growstack'
buildvm_arm.dasc:1422: Error: no such instruction: `bl lj_meta_tget'
buildvm_arm.dasc:1434: Error: no such instruction: `bl lj_tab_getinth'
buildvm_arm.dasc:1468: Error: no such instruction: `bl lj_meta_tset'
buildvm_arm.dasc:1481: Error: no such instruction: `bl lj_tab_setinth'
buildvm_arm.dasc:1491: Error: no such instruction: `bl lj_meta_comp'
buildvm_arm.dasc:1531: Error: no such instruction: `bl lj_meta_equal'
buildvm_arm.dasc:1541: Error: no such instruction: `bl lj_meta_equal_cd'
buildvm_arm.dasc:1551: Error: no such instruction: `bl lj_meta_istype'
buildvm_arm.dasc:1586: Error: no such instruction: `bl lj_meta_arith'
buildvm_arm.dasc:1603: Error: no such instruction: `bl lj_meta_len'
buildvm_arm.dasc:1613: Error: no such instruction: `bl lj_meta_call'
buildvm_arm.dasc:1625: Error: no such instruction: `bl lj_meta_call'
buildvm_arm.dasc:1634: Error: no such instruction: `bl lj_meta_for'
buildvm_arm.dasc:1691: Error: no such instruction: `bl lj_tab_get'
buildvm_arm.dasc:1712: Error: no such instruction: `bl lj_strfmt_number'
buildvm_arm.dasc:1724: Error: no such instruction: `bl lj_tab_next'
buildvm_arm.dasc:1750: Error: no such instruction: `bl lj_tab_getinth'
buildvm_arm.dasc:1806: Error: no such instruction: `bl lj_state_growstack'
buildvm_arm.dasc:1829: Error: no such instruction: `bl lj_ffh_coroutine_wrap_err'
buildvm_arm.dasc:1831: Error: no such instruction: `bl lj_state_growstack'
buildvm_arm.dasc:1933: Error: no such instruction: `bl log'
buildvm_arm.dasc:1943: Error: no such instruction: `bl log10'
buildvm_arm.dasc:1953: Error: no such instruction: `bl exp'
buildvm_arm.dasc:1963: Error: no such instruction: `bl sin'
buildvm_arm.dasc:1973: Error: no such instruction: `bl cos'
buildvm_arm.dasc:1983: Error: no such instruction: `bl tan'
buildvm_arm.dasc:1993: Error: no such instruction: `bl asin'
buildvm_arm.dasc:2003: Error: no such instruction: `bl acos'
buildvm_arm.dasc:2013: Error: no such instruction: `bl atan'
buildvm_arm.dasc:2023: Error: no such instruction: `bl sinh'
buildvm_arm.dasc:2033: Error: no such instruction: `bl cosh'
buildvm_arm.dasc:2043: Error: no such instruction: `bl tanh'
buildvm_arm.dasc:2054: Error: no such instruction: `bl pow'
buildvm_arm.dasc:2065: Error: no such instruction: `bl atan2'
buildvm_arm.dasc:2076: Error: no such instruction: `bl fmod'
buildvm_arm.dasc:2087: Error: no such instruction: `bl ldexp'
buildvm_arm.dasc:2097: Error: no such instruction: `bl frexp'
buildvm_arm.dasc:2108: Error: no such instruction: `bl modf'
buildvm_arm.dasc:2169: Error: no such instruction: `bl lj_str_new'
buildvm_arm.dasc:2209: Error: no such instruction: `bl lj_buf_putstr_reverse'
buildvm_arm.dasc:2210: Error: no such instruction: `bl lj_buf_tostr'
buildvm_arm.dasc:2222: Error: no such instruction: `bl lj_buf_putstr_lower'
buildvm_arm.dasc:2223: Error: no such instruction: `bl lj_buf_tostr'
buildvm_arm.dasc:2235: Error: no such instruction: `bl lj_buf_putstr_upper'
buildvm_arm.dasc:2236: Error: no such instruction: `bl lj_buf_tostr'
buildvm_arm.dasc:2380: Error: no such instruction: `bl lj_state_growstack'
buildvm_arm.dasc:2390: Error: no such instruction: `bl lj_gc_step'
buildvm_arm.dasc:2419: Error: no such instruction: `bl lj_dispatch_ins'
buildvm_arm.dasc:2438: Error: no such instruction: `bl lj_trace_hot'
buildvm_arm.dasc:2455: Error: no such instruction: `bl lj_dispatch_call'
buildvm_arm.dasc:2473: Error: no such instruction: `bl lj_dispatch_stitch'
buildvm_arm.dasc:2483: Error: no such instruction: `bl lj_dispatch_profile'
buildvm_arm.dasc:2498: Error: no such instruction: `bl lj_trace_exit'
buildvm_arm.dasc:2517: Error: no such instruction: `bl lj_err_throw'
buildvm_arm.dasc:2645: Error: no such instruction: `bl lj_ccallback_enter'
buildvm_arm.dasc:2658: Error: no such instruction: `bl lj_ccallback_leave'
buildvm_arm.dasc:2661: Error: unknown pseudo-op: `.personality'
buildvm_arm.dasc:2662: Error: unknown pseudo-op: `.fnend'
buildvm_arm.dasc:2663: Error: unknown pseudo-op: `.fnstart'
buildvm_arm.dasc:2664: Error: unknown pseudo-op: `.save'
buildvm_arm.dasc:2665: Error: unknown pseudo-op: `.setfp'
buildvm_arm.dasc:2678: Error: unknown pseudo-op: `.fnend'

Development Environment:
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04 LTS
Release:        12.04
Codename:       precise

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)

**Comment by waruqi** [comment]
你这gcc版本太老了，可以升级下gcc到5.x以上版本或者装下clang再试试
