### ISSUE TITLE
Builtin `hlsl2spv` rule like `glsl2spv`

### ISSUE THREAD

**Issue by Latias94** [xmake-io/xmake#4147]
### Is your feature request related to a problem? Please describe.

I want my program support both hlsl and glsl.

### Describe the solution you'd like

Use `glsl2spv` as a template. like https://github.com/Locietta/learn-vulkan/blob/main/xmake/hlsl2spv.lua

It is better to get `dxc` under `VULKAN_SDK\Bin` folder.
On my pc, it seems the `dxc` under `C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64\dxc.exe` is a bit outdated which cannot convert hlsl to spv.

### Describe alternatives you've considered

Compile shader using `shaderc` or `naga`?

**Comment by waruqi** [comment]
> Use glsl2spv as a template. like https://github.com/Locietta/learn-vulkan/blob/main/xmake/hlsl2spv.lua

you can open a pr.

> It is better to get dxc under VULKAN_SDK\Bin folder.
On my pc, it seems the dxc under C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64\dxc.exe is a bit outdated which cannot convert hlsl to spv.

you can add `find_dxc.lua` to improve it in https://github.com/xmake-io/xmake/tree/master/xmake/modules/detect/tools
