### ISSUE TITLE
当使用package.tools.make的install调用时, 能否加入一个向make install 添加预定义变量的接口?

### ISSUE THREAD

**Issue by RiversJin** [xmake-io/xmake#4148]
### Is your feature request related to a problem? Please describe.

按照当前的实现, package.tools.make  build函数签名为 
build(package, configs, opt)
其中, configs 只会在 make 构建时加入到make 预定义中, 而make install 不受影响

但是, 存在一些不太"规范"的 makefile, 其安装路径是通过
make DESTDIR=xxx install 来实现的, 比如https://github.com/bji/libs3/blob/master/GNUmakefile#L93

### Describe the solution you'd like

所以, 我想如果能在 build 函数上额外添加一个 install_configs 参数就更好了.
如果这个修改不会与现在的实现, 接口冲突的话, 我想我可以提一个 PR?

**Comment by waruqi** [comment]
可以用 make()

```lua
import("package.tools.make").build(package)
import("package.tools.make").make(package, {"DESTDIR=" .. package:installdir(), "install"})
```

就行了，单独先走 build，然后用 make 直接传，可以随意搞，也就一行配置

**Comment by RiversJin** [comment]
> 可以用 make()
> 
> ```lua
> import("package.tools.make").build(package)
> import("package.tools.make").make(package, {"DESTDIR=" .. package:installdir(), "install"})
> ```
> 
> 就行了，单独先走 build，然后用 make 直接传，可以随意搞，也就一行配置

哈哈, 好吧, 是我思路窄了
