### ISSUE TITLE
improve shallow clones support

### ISSUE THREAD

**Issue by fonqL** [xmake-io/xmake#4151]
### 你在什么场景下需要该功能？

起因是发现`add_requires("lua-format")`使用git clone拉取LuaFormatter的代码，但没带上--depth 1选项，以及之后的拉取子模块也没带上此选项。改为`add_requires("lua-format master")`或`add_requires("lua-format 1.3.6")`才用上--depth 1，但拉取子模块还是没带上此选项。

而且不能写成`add_requires("lua-format 1.3.5")`，否则不带--depth 1，因为xrepo里收录了1.3.5版本。其中[add_versions](https://github.com/xmake-io/xmake-repo/blob/fa5743043276743eb1af54da42f60eb903017a45/packages/l/lua-format/xmake.lua#L6)第二个参数是git commit号。我理解不能对指定commit进行git clone，只能下载全部历史再checkout。但是发现把第二个参数改为git tag名(`add_versions("1.3.5", "1.3.5")`)或者branch名(`add_versions("1.3.5", "master")`)还是走的下载全部历史再checkout。

lua-format的子模块历史记录很大，下载会因网络问题而失败。

另外其实我并不清楚add_versions第二参数是否有意设计为只支持commit号和sha256以确保稳定性，api参考里没写，而且在[生成远程包](https://xmake.io/#/zh-cn/package/local_package?id=%e7%94%9f%e6%88%90%e8%bf%9c%e7%a8%8b%e5%8c%85)里的示例里add_versions只有sha256和commIt号可选，但在<https://github.com/xmake-io/xmake/issues/833#issuecomment-641400521>得知大概还是支持tag和branch名的。

所以请求总结如下：
1. 对`add_requires("pkg branch/tag")`支持子模块的shallow clone。
2. 如果add_versions第二参数支持branch/tag名，则判断如果是commit号，则行为依旧是下载全部历史再checkout（其实可以更进一步，子模块可以是shallow clone）；如果是branch/tag名，则行为是shallow clone。
3. 如果add_versions第二参数不支持branch/tag名，希望支持。

### 描述可能的解决方案

主要修改[download.lua](https://github.com/xmake-io/xmake/blob/219c5dcbc69dddda3ca9637c9de3b6affc5dcf8b/xmake/modules/private/action/require/impl/actions/download.lua)

对于第一点，给git.clone加上 `shallow_submodules = true`即可
<https://github.com/xmake-io/xmake/blob/219c5dcbc69dddda3ca9637c9de3b6affc5dcf8b/xmake/modules/private/action/require/impl/actions/download.lua#L99>

对于第二点，可以先做一点小改进，增加对子模块的shallow clone支持，给git.submodule.update加上`depth = 1`即可。
<https://github.com/xmake-io/xmake/blob/219c5dcbc69dddda3ca9637c9de3b6affc5dcf8b/xmake/modules/private/action/require/impl/actions/download.lua#L113>
在调试时发现devel.git模块下的submodule/update.lua里没有支持depth=1，需要添加支持：
```lua
    if opt.depth then
        table.insert(argv, "--depth")
        table.insert(argv, type(opt.depth) == "number" and tostring(opt.depth) or opt.depth)
    end
```

第二点的完整解决方案大概也是在_checkout(和上面一样的函数)里对package:version_str()判断是commit号还是branch/tag名。（根据字符串长度是否等于40判断）（进入_checkout说明是要用git下载了而不是用curl下载了？）。但是我不确定这样判断是否可靠。

全局搜索发现[download_resources.lua](https://github.com/xmake-io/xmake/blob/219c5dcbc69dddda3ca9637c9de3b6affc5dcf8b/xmake/modules/private/action/require/impl/actions/download_resources.lua)也有git.clone和git.submodules.update的调用，但在我的场景下发现里面的函数没有执行，所以不清楚这个文件的具体作用，可以暂时搁置。

**Comment by waruqi** [comment]
> 对add_requires("pkg branch/tag")支持子模块的shallow clone。

原本就是 shallow clone ，仅仅只是 submodule 没处理而已，这个可以改进。。

> 如果add_versions第二参数支持branch/tag名，则判断如果是commit号，则行为依旧是下载全部历史再checkout（其实可以更进一步，子模块可以是shallow clone）；如果是branch/tag名，则行为是shallow clone。

支持 branch/tag/commit，但是目前区分不了是否为 branch，只能统一走 checkout。。

**Comment by fonqL** [comment]
把commit和branch/tag区分开应该还是可以的吧。至于区分branch和tag的话我觉得没什么必要，clone行为都是一样的吧

**Comment by waruqi** [comment]
> 把commit和branch/tag区分开应该还是可以的吧。至于区分branch和tag的话我觉得没什么必要，clone行为都是一样的吧

这个区分开也没啥用，关键是 tag 和 branch 区别不开。。tag 还是要 checkout ，git clone --depth 1 无法指定 tag 去 clone

**Comment by waruqi** [comment]
> 对于第一点，给git.clone加上 shallow_submodules = true即可

这个我加上了

**Comment by waruqi** [comment]
> git clone -b tag_name --depth 1试验过是可以的，也见git clone --help，其中最后一句：
> 
> ```
>        -b <name>, --branch <name>
>            Instead of pointing the newly created HEAD to the branch pointed to by the cloned
>            repository’s HEAD, point to <name> branch instead. In a non-bare repository, this is
>            the branch that will be checked out.  --branch can also take tags and detaches the
>            HEAD at that commit in the resulting repository.
> ```
> 
> 哦这git 1.8才支持，不知道会不会破坏兼容性。

我记得之前是不支持的，如果只是高版本支持，就不太好搞，除非判断下版本，但要确定是否真的 1.8 开始

**Comment by fonqL** [comment]
我是从[这](https://stackoverflow.com/questions/35291833/how-to-clone-a-tag-of-a-git-branch)知道的，具体版本号确实不清楚。

**Comment by fonqL** [comment]
我是从[这](https://stackoverflow.com/questions/35291833/how-to-clone-a-tag-of-a-git-branch)知道的，具体版本号确实不清楚。

**Comment by waruqi** [comment]
最好确认验证下，如果确实是，我可以加个版本判断。

**Comment by fonqL** [comment]
确定是1.7.10版本的支持。可以查看[1.7.10的RelNotes](https://github.com/git/git/blob/e8dde3e5f9ddb7cf95a6ff3cea6cf07c3a2db80d/Documentation/RelNotes/1.7.10.txt#L84-L87)、[1.7.10的git-clone.txt](https://github.com/git/git/blob/e8dde3e5f9ddb7cf95a6ff3cea6cf07c3a2db80d/Documentation/git-clone.txt#L150-L152)、[1.7.9.7的git-clone.txt](https://github.com/git/git/blob/d0f1ea6003d97e63110fa7d50bb07f546a909b6e/Documentation/git-clone.txt#L146-L150)来确认。

**Comment by fonqL** [comment]
git submodule update --depth 1在[1.8.4](https://github.com/git/git/blob/e230c568c4b9a991e3175e5f65171a566fd8e39c/Documentation/RelNotes/1.8.4.txt#L129-L130)才支持

**Comment by waruqi** [comment]
好了，再试试，`xmake update -s dev`

**Comment by fonqL** [comment]
大概就这些参数？
--shallow-submodules所需版本可能太高了，可以分解为git clone --depth + git submodule  update --init --recursive --depth 1 ？

**Comment by waruqi** [comment]
没必要，不想搞太复杂，现在的逻辑已经很复杂了。。随着 git 版本迭代，尽可能简化现有逻辑，而不是复杂化。

过低的 git 版本，直接 fallback 到现有深度 clone 也无所谓。

**Comment by waruqi** [comment]
没啥问题，我关了。应该可以了

**Comment by fonqL** [comment]
突然意识到其实branch/tag和commit号其实也不能很好的区分，建议尽量兼容旧行为，能绝对确定是个branch/tag才采用shallow clone吧。然而[这个判断](https://github.com/xmake-io/xmake/blob/56c0b2a45c2c31d14a07dc684e2193447cd2e2e7/xmake/modules/private/action/require/impl/actions/download.lua#L109) 我的理解是尽量判定为branch/tag，这就不太合理。我的建议是改为`if revision and (#revision > 40 or not revision:match("^%x+$"))`。
因为，比如具体来说，如果有人以前写了add_version(“1.0", "0e3946")这样的不足40位的commit号，在以前版本是可以走checkout正常运作，而新版本会被判定为这是个tag而用git clone -b 0e3946而找不到对应branch/tag而报错。`not revision:match("^%x+$")`则是若字符串出现非十六进制字符，则绝对确定是branch/tag而不是commit号。

**Comment by fonqL** [comment]
其他就没什么问题了

**Comment by waruqi** [comment]
> 在区分branch/tag和commit号上，建议尽量兼容旧行为，能绝对确定是个branch/tag才采用shallow clone吧。然而[这个判断](https://github.com/xmake-io/xmake/blob/56c0b2a45c2c31d14a07dc684e2193447cd2e2e7/xmake/modules/private/action/require/impl/actions/download.lua#L109) 我的理解是尽量判定为branch/tag，这就不太合理。我的建议是改为`if revision and (#revision > 40 or not revision:match("^%x+$")) then`。 因为，比如具体来说，如果有人以前写了add_version(“1.0", "0e3946")这样的不足40位的commit号，在以前版本是可以走checkout正常运作，而新版本会被判定为这是个tag而用git clone -b 0e3946而找不到对应branch/tag而报错。`not revision:match("^%x+$")`则是若字符串出现非十六进制字符，则绝对确定是branch/tag而不是commit号。

目前包里面 add_versions 如果走 commit ，原本就仅支持 40位 full commit 号，不支持缩写，其他地方也是，即使这里兼容了 也没用。。反正不是 full commit 的，一律都是 tag / branch。。之前就是这个行为。

**Comment by fonqL** [comment]
那就更新一下文档好了，文档中确实没有写这个规定。
