### ISSUE TITLE
rebuild一个target，总会引起他依赖的target也rebuild

### ISSUE THREAD

**Issue by Wzshun** [xmake-io/xmake#4154]
### Xmake 版本

2.8.1

### 操作系统版本和架构

windows10

### 描述问题

重新构建一个target，他依赖的target也会触发重新编译。这在某些大的顶层target，不可忍受重新编译的时长。

### 期待的结果

只重建我指定的target，在依赖项的target没被改动过的前提下。

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
目前只能全局 rebuild，要做成 target 粒度 rebuild 需要做部分重构，可能得费点时间

**Comment by waruqi** [comment]
改了下，再试试

```
xmake update -s github:xmake-io/xmake#rebuild
```

**Comment by waruqi** [comment]
默认行为不变，还是会自动重建所有依赖

```console
xmake -r target
```

如果仅仅 rebuild 当前指定的 target，加 `--shallow` 参数

```console
xmake -r --shallow target
```

**Comment by waruqi** [comment]
我已经 merge 到 dev 了。
