### ISSUE TITLE
Protoc not being found with project -k vs

### ISSUE THREAD

**Issue by maximegmd** [xmake-io/xmake#4162]
### Xmake Version

v2.8.2+HEAD.57212c681

### Operating System Version and Architecture

Windows 11

### Describe Bug

protoc is not found when using the protobuf-cpp package and running `xmake project -k vs`

### Expected Behavior

protoc is located and the vs solution generator works.

### Project Configuration

add_requires("protobuf-cpp")

target("test")
     set_kind("binary")
     set_languages("c++11")
     add_packages("protobuf-cpp")
     add_rules("protobuf.cpp")
     add_files("*.cpp")
     add_files("*.proto")

### Additional Information and Error Logs

checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.36.32537
checking for release.x64 ...
error: protoc not found!

**Comment by waruqi** [comment]
Can you try `xmake project -k vsxmake`?

**Comment by maximegmd** [comment]
It works fine with vsxmake but not with vs

**Comment by waruqi** [comment]
Try it again. `xmake update -s dev`
