### ISSUE TITLE
xmake doxygen 的-o参数无效

### ISSUE THREAD

**Issue by Charonxin** [xmake-io/xmake#4163]
### Xmake 版本

xmake v2.8.2

### 操作系统版本和架构

Ubuntu22.04

### 描述问题

```
xmake doxygen -o doc
```

没有生成指定的doc文件夹
新建doc文件夹后还是无法输出文件到指定的文件夹

### 期待的结果

`xmake doxygen -o doc`会将生成的文件存入doc文件夹，如果没有应该新建

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
我这里可以，没啥问题，仅仅只是 log 显示有点小 bug ，输出正常。

```
ruki-2:tbox ruki$ xmake doxygen -o doc
generating ..
result: doc/html/index.html
doxygen ok!
drwxr-xr-x  1953 ruki  staff  62496  9  4 11:08 html
drwxr-xr-x  1534 ruki  staff  49088  9  4 11:08 latex
```

**Comment by Charonxin** [comment]
另外，如果项目中含有 `Doxyfile.in` 文件，在执行 `xmake doxygen` 时将会重新生成一份 `doxyfile` 文件，我认为应该直接使用现有的文件比较好。。

请问 xmake 能否提供doxygen的`doxygen <config-file>`选项呢？

**Comment by waruqi** [comment]
如果有 doxyfile 文件会直接使用。

**Comment by Charonxin** [comment]
如果有doxyfile，有没有办法在doxyfile中使用宏，然后xmake的
```
add_configfiles(
    "Doxyfile.in", {
        filename = "doxyfile",
        pattern = "@(.-)@",
        variables = {
            DOXYGEN_DIR = get_config("buildir"),
        }
    }
)
```
进行替换？

**Comment by waruqi** [comment]
> 如果有doxyfile，有没有办法在doxyfile中使用宏，然后用xmake的
> 
> ```
> add_configfiles(
>     "Doxyfile.in", {
>         filename = "doxyfile",
>         pattern = "@(.-)@",
>         variables = {
>             DOXYGEN_DIR = get_config("buildir"),
>         }
>     }
> )
> ```
> 
> 进行替换？

add_configfiles 主要是构建前的 config 阶段执行的。。你想要走这个 替换，可以执行 `xmake doxygen` 之前，先执行下 `xmake config -c` 就行了

**Comment by Charonxin** [comment]
谢谢！
