### ISSUE TITLE
使用mingw toolchain无法检测 HAVE_INTPTR_T

### ISSUE THREAD

**Issue by darcy-shen** [xmake-io/xmake#4173]
### Xmake 版本

dev and 2.8.2

### 操作系统版本和架构

Windows 11

### 描述问题

```
xmake config -p mingw
```
无法检测
```
configvar_check_cxxtypes("HAVE_INTPTR_T", "intptr_t", {includes = {"memory"}})
```
在手动将mingw相关路径加入之后，可以检测到 HAVE_INTPTR_T，比如 https://github.com/XmacsLabs/lolly/blob/main/bin/config_mingw

### 期待的结果

HAVE_INTPTR_T能够被检测到

### 工程配置

+ https://github.com/XmacsLabs/lolly/blob/v1.2.2/xmake.lua#L17
+ https://github.com/XmacsLabs/lolly/blob/v1.2.2/System/config_l1.h.xmake#L8

### 附加信息和错误日志

xmake config的关键信息
```
checking for HAVE_INTTYPES_H ... no
checking for HAVE_INTPTR_T ... no
```

出错信息（和lolly仓库有关）
```
error: C:/Users/darcy/AppData/Local/.xmake/packages/m/mingw-w64/8.1.0/56aa6e64d5e4436e887c6df8f2e26e92/x86_64-w64-mingw32/include/crtdefs.h:62:35: error: conflicting declaration 'typedef long long int intptr_t'
 __MINGW_EXTENSION typedef __int64 intptr_t;
                                   ^~~~~~~~
In file included from <command-line>:
./build/L1/config.h:16:14: note: previous declaration as 'typedef long int intptr_t'
 typedef long intptr_t;
              ^~~~~~~~
  > in tests\Kernel\Types\tree_test.cpp
```

**Comment by waruqi** [comment]
> 出错信息（和lolly仓库有关）

这只是你的编译错误，要看 xmake f -vD; xmake -vD 的 check error info 。。贴下

**Comment by darcy-shen** [comment]
感谢，已成功配置：https://github.com/XmacsLabs/lolly/pull/137/

**Comment by jingkaimori** [comment]
在target进行的检测可以缓存吗？`on_config`事件每次编译前都会触发，导致重复检测

**Comment by waruqi** [comment]
> 在target进行的检测可以缓存吗？`on_config`事件每次编译前都会触发，导致重复检测

没有， on_config 每次配置都会被执行，不过 dev 我刚加了个 recheck 状态，你可以根据这个来判断是否需要检测

```lua
on_config(target, opt)
     if opt.recheck and target:has_cfuncs(...) then
    end
 end
```

**Comment by waruqi** [comment]
参考这个 patch， https://github.com/tboox/tbox/pull/235
