### ISSUE TITLE
ASAN missing DLL on Visual Studio 17.7.X

### ISSUE THREAD

**Issue by samayala22** [xmake-io/xmake#4176]
### Xmake Version

2.8.2

### Operating System Version and Architecture

Windows 11 22H2

### Describe Bug

The ASAN linking model in visual studio changed on [version 17.7](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#other-c-updates-1 ). As a consequence, when trying to run a project compiled with `mode.asan` we get a missing dll error window popup saying:

> The code execution cannot proceed because clang_rt.asan_dynamic-x86_64.dll was not found. Reinstalling the program may fix this problem. 

This dll can be found at `C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64` if you install VS at default location. 

I tried with both runtimes (`MT` and `MD`) and got the same error message. In the meantime I can manually put the dll in the same directory as the executable and it will work.

I tried on another machine running VS 17.6.4 and it worked fine, and with VS 17.7.3 we get missing dll error.

I have provided a minimal reproducible example below.

### Expected Behavior

Expected the program to run correctly when compiled in asan mode.

### Project Configuration

On a windows machine with VS 17.7 & Asan debugging installed:

```
xmake f -m asan && xmake && xmake run
```

Program should run and asan should catch the heap-buffer-overflow.

[asan_missing_dll_repro.zip](https://github.com/xmake-io/xmake/files/12553714/asan_missing_dll_repro.zip)

### Additional Information and Error Logs

Runtime error so no compilation logs .

**Comment by star-hengxing** [comment]
My solution
https://github.com/star-hengxing/clipboard-url-clear/blob/main/xmake/rule/debug.lua

**Comment by waruqi** [comment]
> My solution https://github.com/star-hengxing/clipboard-url-clear/blob/main/xmake/rule/debug.lua

you can open a pr to improve it.

**Comment by waruqi** [comment]
Fixed. `xmake update -s dev`

**Comment by waruqi** [comment]
I have improved asan and provide asan policy to support it and packages.

https://github.com/xmake-io/xmake/issues/4226
