### ISSUE TITLE
Visual Studio project (not vsxmake) can't be compiled due to Build Scripts

### ISSUE THREAD

**Issue by Raildex** [xmake-io/xmake#4177]
### Xmake Version

2.8.2

### Operating System Version and Architecture

Windows 10, Visual Studio 2022

### Describe Bug

I have a target that converts hlsl files to C arrays by first compiling them and then converting them to C Arrays with a custom tool.
When generating a Visual Studio Solution, this conversion is done in a Pre Build Event.

However, this Pre Build Event doesn't seem to work:

![grafik](https://github.com/xmake-io/xmake/assets/14938934/c2b7352d-273e-47eb-94ad-42d7f9f36728)

I don't know what exactly fails.

### Expected Behavior

The Pre Build Event should work without errors, just like the pure xmake build

### Project Configuration

[xmake test.zip](https://github.com/xmake-io/xmake/files/12558479/xmake.test.zip)

### Additional Information and Error Logs

execute `xmake project -k vs` to generate the Visual Studio solution. Within Visual Studio, try to compile the target "Test", it will fail due to the Pre Build Event.

Visual Studio needs to be installed and the fxc shader compiler tool needs to be in PATH.
[fxc.zip](https://github.com/xmake-io/xmake/files/12558494/fxc.zip)

**Comment by waruqi** [comment]
> local compileargs = {"/T",profile ,"/E" ,entry ,"/WX" ,"/Zi" ,"/Zss" ,"/Ges" ,"/Gis" ,"/Od","/nologo","/Fo" ,bytecodefile , sourcefile_bin}
> batchcmds:vrunv("fxc", compileargs)

You need use `path(bytecodefile)` to wrap all paths in batchcmds. They will be translated to real path in vsproject.

like this

```lua
> local compileargs = {"/T",profile ,"/E" ,entry ,"/WX" ,"/Zi" ,"/Zss" ,"/Ges" ,"/Gis" ,"/Od","/nologo","/Fo" , path(bytecodefile), (sourcefile_bin)}
```

> fxc.exe /T vs_5_0 /E main /WX /Zi /Zss /Ges /Gis /Od /nologo /Fo build\.gens\Test\windows\x64\release\include\shaders\d3d11\blit.vertex.dxbc blit.vertex.hlsl
:xmEnd

will be translated to

> fxc.exe /T vs_5_0 /E main /WX /Zi /Zss /Ges /Gis /Od /nologo /Fo "..\..\build\.gens\Test\windows\x64\release\include\shaders\d3d11\blit.vertex.dxbc" ..\..\blit.vertex.hlsl
:xmEnd

and other some file paths in other batchcmds.

**Comment by waruqi** [comment]
you need wrap all paths.

It works for me 

```lua
            local compileargs = {"/T",profile ,"/E" ,entry ,"/WX" ,"/Zi" ,"/Zss" ,"/Ges" ,"/Gis" ,"/Od","/nologo","/Fo" , path(bytecodefile) , path(sourcefile_bin)}
            batchcmds:vrunv("fxc", compileargs)

            batchcmds:show_progress(opt.progress, "${color.build.object}generating.f2c variable name %s", varname)
            batchcmds:show_progress(opt.progress, "${color.build.object}generating.f2c filepathbase name %s", filepathbase)
            local f2cpkg = target:pkg("f2c")
            local f2c = path.join(f2cpkg:installdir(), "bin", "f2c.exe")
            local f2cargs = {"-cpp", path(bytecodefile), varname, path(filepathbase), "raid::shaders::d3d11"}
```

![image](https://github.com/xmake-io/xmake/assets/151335/f16004e7-6678-48ae-8f91-59ae6f829969)

**Comment by Raildex** [comment]
It works on the test project, but it does not on my real project.
I have copy&paste'd the pre-build event and put it into a bat file.
The output of it is this:

![grafik](https://github.com/xmake-io/xmake/assets/14938934/01d9048e-17fc-4312-a55c-8a50033567a1)

what I noticed is that it uses relative path `../../`
if `vs2022` is the directory in which this gets executed, then it goes one directory up too much.
