### ISSUE TITLE
Unable to develop xmake on macOS (apple silicon)

### ISSUE THREAD

**Issue by silvanshade** [xmake-io/xmake#4180]
### Xmake Version

2.8.2

### Operating System Version and Architecture

macos 13.5.1

### Describe Bug

I am trying to develop `xmake` on `macOS` in order to debug a problem I encountered #4179 but am encountering errors after trying to run `xmake` after building it.

The process I followed:

1. `git clone --recursive https://github.com/xmake-io/xmake`
2. `cd xmake`
3. `./configure` # I also tried with `export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)` but it makes no difference
4. `make`
5. `export XMAKE_PROGRAM_DIR=$(pwd)/xmake`
6. `xmake install brew::llvm`

This gives me an error:

```
error: file(${HOME}/Development/xmake/xmake.lua): file not found!
```

However, when I follow the exact same procedure on Linux, I do not get this error.

### Expected Behavior

Running `xmake` from the local development repository with `XMAKE_PROGRAM_DIR` set should work.

### Project Configuration

N/A

### Additional Information and Error Logs

```
error: ./xmake/core/main.lua:309: ./xmake/core/project/project.lua:952: file(${HOME}/Development/xmake/xmake.lua): file not found!
stack traceback:
    [C]: in function 'error'
    [./xmake/core/base/os.lua:921]:
    [./xmake/core/project/project.lua:952]: in function 'requires_str'
    [./xmake/core/project/project.lua:483]: in function '_load_requires'
    [./xmake/core/project/project.lua:934]: in function 'required_packages'
    [./xmake/core/project/project.lua:328]: in function '_load_targets'
    [./xmake/core/project/project.lua:874]: in function 'targets'
    [./xmake/core/project/project.lua:899]: in function 'ordertargets'
    [...ake/core/sandbox/modules/import/core/project/project.lua:182]: in function '_load_package_rules_for_targets'
    [...ake/core/sandbox/modules/import/core/project/project.lua:193]: in function 'load_targets'
    [./xmake/actions/install/main.lua:71]:
    [C]: in function 'xpcall'
    [./xmake/core/base/utils.lua:280]:
    [./xmake/core/base/task.lua:501]: in function 'run'
    [./xmake/core/main.lua:307]: in function 'cotask'
    [./xmake/core/base/scheduler.lua:404]:

stack traceback:
	[C]: in function 'error'
	./xmake/core/base/os.lua:921: in function 'base/os.raiselevel'
	(...tail calls...)
	./xmake/core/main.lua:309: in upvalue 'cotask'
	./xmake/core/base/scheduler.lua:404: in function <./xmake/core/base/scheduler.lua:397>
```

**Comment by waruqi** [comment]
run `source ./scripts/srcenv.profile`

see https://xmake.io/#/guide/faq?id=loading-a-local-debugging-environment-on-other-platforms
