### ISSUE TITLE
Android工程不能正确查找到系统包

### ISSUE THREAD

**Issue by zjyhjqs** [xmake-io/xmake#4184]
### Xmake 版本

2.8.2

### 操作系统版本和架构

WSL2 Arch Linux x86_64

### 描述问题

NDK在 API 3 与 API 28 分别加入了[`zlib`](https://developer.android.com/ndk/guides/stable_apis#zlib_compression)与[`libiconv`](https://android-review.googlesource.com/c/platform/bionic/+/464455)的接口.

但在构建Android项目时, 对`zlib`与`libiconv`执行`add_requires(*, {system = true})`, 返回了无法找到系统包的错误.

而当我手动`xrepo install`后, 这些通过`xrepo`安装的包却被视为了系统包而通过了检测.

### 期待的结果

`ndk_sdkver >= 28`:
- ✅`add_requires("zlib", {system=true})`
- ✅`add_requires("libiconv", {system=true})`

`ndk_sdkver < 28`:
- ✅`add_requires("zlib", {system=true})`
- ❌`add_requires("libiconv", {system=true})`

### 工程配置

```lua
add_requires("zlib", {system = true})
add_requires("libiconv", {system = true})
```

### 附加信息和错误日志

看了下[实现部分](https://github.com/xmake-io/xmake/blob/master/xmake/core/package/package.lua#L1759~L1762), 似乎现在交叉编译暂时还不支持系统包的检测?

**Comment by waruqi** [comment]
目前系统库查找不支持交叉编译，你可以直接 `add_syslinks("z", "iconv")`

**Comment by zjyhjqs** [comment]
> 目前系统库查找不支持交叉编译，你可以直接 `add_syslinks("z", "iconv")`

将三方库视为系统库的缺陷仍然存在, 我提了个#4193
