### ISSUE TITLE
nvcc 支持 set_warnings 问题

### ISSUE THREAD

**Issue by OpportunityLiu** [xmake-io/xmake#419]
https://github.com/xmake-io/xmake/blob/b1fd47f59027fc780e9ae6ffbc36d289859452cf/xmake/modules/core/tools/nvcc.lua#L69-L83

nvcc 除了 `-w` `-Werror` 就剩下个 `-Wreorder`，剩下的需要通过`-Xcompiler` 和 `-Xlinker` 给host编译器和链接器处理
https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#generic-tool-options-Wreorder

另外，希望能够增加extra和everything级别

|   | gcc | clang | msvc |
| --- | --- | --- | --- |
| extra | -Wextra |  -Wextra | -W4 |
| everything | "-Wall -Wextra -Weffc++" |  -Weverything | -Wall |

**Comment by waruqi** [comment]
哦 这块我只测试了-w -Werror 其他的都是直接复用了gcc的，你可以提个pr帮忙改下 加个-Xcompiler

**Comment by OpportunityLiu** [comment]
在nvcc的nf_warings里该怎么检测 cu-cxx 和调用其他编译器的nf_warings呢？

**Comment by waruqi** [comment]
```lua
local cu_cxx = config.get("cu-cxx")
if is_plat("windows") then
elseif cu_cxx and cu_cxx:find("gcc", 1, true) then
end
```

**Comment by OpportunityLiu** [comment]
所以怎么找到对应的实例呢？
```
    local cu_cxx = config.get("cu-cxx")
    local cu_cxx_tool = nil 
    if is_plat("windows") or not cu_cxx then
        cu_cxx_tool = tool.load("cxx") -- ???
    elseif cu_cxx then
        cu_cxx_tool = tool.load("cxx", cu_cxx)
    end

    local cu_cxx_tool_warning = cu_cxx_tool.nf_warning(level)
```

**Comment by waruqi** [comment]
不要用tool.load，可以用has_flags 参考下 

https://github.com/xmake-io/xmake/blob/85cb688e30f996c5ac1036ec99b6c7c1a45cb035/xmake/modules/core/tools/nvcc.lua#L160

**Comment by waruqi** [comment]
nvcc/nf_warning这块，我已经改好了，你试试
https://github.com/xmake-io/xmake/commit/7ed7da5e9b333930081b50ff3781ea0a07417a1b

**Comment by OpportunityLiu** [comment]
结果需要抄过来吗。。。那我还是会的

**Comment by waruqi** [comment]
> 结果需要抄过来吗。。。那我还是会的

? nvcc/nf_warning里面那块我改掉了，你那个pr里面把nvcc这块的commit revert下，其他gcc/cl/clang的 warnings处理，我merge下就好了。。
