### ISSUE TITLE
Target type that has no source files, but acts as "headeronly" to generate headers through rules

### ISSUE THREAD

**Issue by Raildex** [xmake-io/xmake#4192]
### Is your feature request related to a problem? Please describe.

I have a target that is supposed to act as a "headeronly" target.
This target does not have any regular program source files. instead, it contains schema files which are later converted to header files.
The target itself acts on these files through rules.

There is currently no way to tell xmake that it is "headeronly" and apply rules to files. Rules are simply not executed.

### Describe the solution you'd like

I would like to have the option to enforce the application of rules - we explicitly say
`set_extensions(...)` within the rule and it should act on them, regardless of the target type.

### Describe alternatives you've considered

I have tried the "phony" target, but it does not trigger rules either.
Using "object" demands a linker. Since my target does not contain object files, i receive 
`error: no suitable linker for object.{}`

### Additional context

```lua
add_requires("flatbuffers")


rule("utils.flatc")
    set_extensions(".fbs")
    on_load(function (target)
        local headerdir = path.join(target:autogendir(), "include")
        if not os.isdir(headerdir) then
            os.mkdir(headerdir)
        end
        target:add("includedirs", headerdir,{public = true})
    end)
    before_buildcmd_file(function (target, batchcmds, sourcefile_bin, opt)

        -- get header file
        local headerdir = path.join(target:autogendir(), "include")
        local schemadir = path.join(headerdir,"schema")
        local headerfile = path.join(schemadir, path.filename(sourcefile_bin):gsub("%.fbs","") .. "_serialization.h")
        batchcmds:show_progress(opt.progress,"Schema %s will be generated to %s",sourcefile_bin, headerfile)
        -- add commands
        batchcmds:show_progress(opt.progress, "${color.build.object}generating.flatc %s", sourcefile_bin)
        batchcmds:mkdir(schemadir)
        local argv = {"--csharp", "--cpp", "--gen-object-api", "--cs-gen-json-serializer", "--gen-onefile","--scoped-enums", "-o",schemadir,"--cpp-std" ,"c++17", "--filename-suffix", "_serialization","--object-suffix", "_t", "--force-empty", sourcefile_bin}
        batchcmds:vrunv("flatc", argv)

        -- add deps
        batchcmds:add_depfiles(sourcefile_bin)
        batchcmds:set_depmtime(os.mtime(headerfile))
        batchcmds:set_depcache(target:dependfile(headerfile))
    end)

target("Common Schema")
    set_kind("headeronly") -- its headeronly, but rules should apply nonetheless
    add_rules("utils.flatc")
    add_packages("flatbuffers")
    add_files("common.fbs")
target_end()
```

**Comment by waruqi** [comment]
try `set_kind("object")`?

**Comment by Raildex** [comment]
as in the description : does not work.

Using "object" demands a linker. Since my target does not contain object files, i receive
- [error: no suitable linker for object.{}]

**Comment by waruqi** [comment]
no link, it works for me.

```
ruki-2:test3 ruki$ xmake -r
src/test.man
[100%]: build ok, spent 0.005s
```

```lua
add_rules("mode.debug", "mode.release")

rule("man")
    set_extensions(".man")
    on_build_file(function (target, sourcefile)
        print(sourcefile)
    end)

target("test3")
    set_kind("object")
    add_files("src/*.man")
    add_rules("man")
```

**Comment by Raildex** [comment]
To me it look slike `batchcmds` does not get executed.
How do I execute tools (in my case `flatc`) within `on_build_file`?
