### ISSUE TITLE
xmake run 在程序出错后，stderr 信息未输出到屏幕

### ISSUE THREAD

**Issue by ivanallen** [xmake-io/xmake#4194]
### Xmake 版本

xmake v2.8.1+20230728

### 操作系统版本和架构

Linux 10-16-43-32 5.14.0-70.13.1.el9_0.x86_64 #1 SMP PREEMPT Wed May 25 21:01:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

ci 上跑 xmake run -g test，程序发生段错误，信息不输出屏幕

### 期待的结果

对 stderr 也能正常打印

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
`xmake run` 是不捕获 stdio 的，所有 stdout/stderr 输出，原本就会默认回显。。如果没看到，就是段错误崩溃时候，你程序本身就没任何输出，或者还在 buffer 里没刷出来。

**Comment by ivanallen** [comment]
> `xmake run` 是不捕获 stdio 的，所有 stdout/stderr 输出，原本就会默认回显。。如果没看到，就是段错误崩溃时候，你程序本身就没任何输出，或者还在 buffer 里没刷出来。

好吧，os 打的段错误它也没有显示出来，比如下图中，手动运行会提示段错误，但是这里什么也没提示就报错了。。

![image](https://github.com/xmake-io/xmake/assets/12481610/351e6f7c-431a-41bb-85a7-d66eabf4e458)

**Comment by waruqi** [comment]
那个是 xmake 的lua 栈，又不是你 target 程序的段错误，描述清楚啊。。。

xmake 的错误栈，得加 -D 才能显示

**Comment by ivanallen** [comment]
> 那个是 xmake 的lua 栈，又不是你 target 程序的段错误，描述清楚啊。。。
> 
> xmake 的错误栈，得加 -D 才能显示

上面是加了 xmake run -vD 运行的。实际上 target 程序发生了段错误的，只是没有提示

**Comment by waruqi** [comment]
那就不知道了，target 本身的错误，原本就是回显的，除非它就是没输出。。xmake 没做任何捕获
