### ISSUE TITLE
Multiple add_ldflags("-u symbol") won't compile when translated to CMake scripts

### ISSUE THREAD

**Issue by JX-Master** [xmake-io/xmake#4196]
### Xmake Version

2.8.2

### Operating System Version and Architecture

macOS Ventura 13.4

### Describe Bug

The current version of xmake uses CMake to generate XCode projects. When translating multiple `add_ldflags("-u symbol")` of the same project, the result CMake scripts contains `target_link_options` similar to this:

```
target_link_options(Project PRIVATE
    -target
    arm64-apple-macos13.3
    -isysroot
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk
    -stdlib=libc++
    -lz
    -u symbol1
    -u symbol2
    -u symbol3
)
```

Note that there are multiple `-u` options on the command. As noted by [CMake docs](https://cmake.org/cmake/help/latest/command/target_link_options.html), *Option De-duplication* is performed on multiple options with the same option identifier (the `-u` here) since CMake 3.12. So that the result command line will be `-u symbol1 symbol2 symbol3`, which causes `ld` to throw errors: `No such file or directory: 'symbol2'` `No such file or directory: 'symbol3'`.

### Expected Behavior

According to CMake docs, the correct output of `target_link_options` shall be:

```
target_link_options(Project PRIVATE
    -target
    arm64-apple-macos13.3
    -isysroot
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk
    -stdlib=libc++
    -lz
    "SHELL:-u symbol1"
    "SHELL:-u symbol2"
    "SHELL:-u symbol3"
)
```

I think the xmake's CMake generator shall be modified to fix this bug.

### Project Configuration

This bug can happen when build projects from XCode with CMake scripts generated from xmake projects with multiple `-u` ld flags. The linker used here is `Ld`.

### Additional Information and Error Logs

Error message from XCode:

Build target Asset
Run script build phase 'CMake PostBuild Rules' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked.

Ld /Users/jxmaster/Desktop/LunaSDK/build/macosx/arm64/release/Debug/libLunaAsset.dylib normal (in target 'Asset' from project 'Luna')
    cd /Users/jxmaster/Desktop/LunaSDK/Solution
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -Xlinker -reproducible -target arm64-apple-macos13.3 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -L/Users/jxmaster/Desktop/LunaSDK/build/EagerLinkingTBDs/Debug -L/Users/jxmaster/Desktop/LunaSDK/build/macosx/arm64/release/Debug -L/Users/jxmaster/Desktop/LunaSDK/Solution/../build/macosx/arm64/release/Debug -L/Users/jxmaster/Desktop/LunaSDK/Solution/../build/macosx/arm64/release -F/Users/jxmaster/Desktop/LunaSDK/build/EagerLinkingTBDs/Debug -F/Users/jxmaster/Desktop/LunaSDK/build/macosx/arm64/release/Debug -filelist /Users/jxmaster/Desktop/LunaSDK/build/Asset.build/Debug/Objects-normal/arm64/LunaAsset.LinkFileList -install_name @rpath/libLunaAsset.dylib -Xlinker -rpath -Xlinker /Users/jxmaster/Desktop/LunaSDK/Solution/../build/macosx/arm64/release -Xlinker -object_path_lto -Xlinker /Users/jxmaster/Desktop/LunaSDK/build/Asset.build/Debug/Objects-normal/arm64/LunaAsset_lto.o -target arm64-apple-macos13.3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -stdlib\=libc++ -u _luna_static_register_module_VariantUtils _luna_static_register_module_VFS _luna_static_register_module_JobSystem -dynamiclib -Wl,-headerpad_max_install_names -lLunaVariantUtils -lLunaVFS -lLunaJobSystem -lLunaRuntime -lz -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/jxmaster/Desktop/LunaSDK/build/Asset.build/Debug/Objects-normal/arm64/LunaAsset_dependency_info.dat -o /Users/jxmaster/Desktop/LunaSDK/build/macosx/arm64/release/Debug/libLunaAsset.dylib

clang: error: no such file or directory: '_luna_static_register_module_VFS'
clang: error: no such file or directory: '_luna_static_register_module_JobSystem'

No such file or directory: '_luna_static_register_module_VFS'

No such file or directory: '_luna_static_register_module_JobSystem'

Activity Log Complete    2023/9/12, 22:54    0.4 seconds

**Comment by waruqi** [comment]
Try it again. `xmake update -s dev`

**Comment by JX-Master** [comment]
That problem still exists. I think quotes ("") should be added to prevent CMake from recognizing `-u` and `symbol` as separate identifiers:
```
"SHELL:-u symbol1"
"SHELL:-u symbol2"
"SHELL:-u symbol3"
```
instead of:
```
SHELL:-u symbol1
SHELL:-u symbol2
SHELL:-u symbol3
```

**Comment by waruqi** [comment]
try it again.
