### ISSUE TITLE
在emsdk工具链下，使用emconfigure运行configure脚本

### ISSUE THREAD

**Issue by jingkaimori** [xmake-io/xmake#4197]
### 你在什么场景下需要该功能？

emsdk提供了emconfigure工具来执行配置脚本，从而构建ICU4C等依赖`configure`的项目

### 描述可能的解决方案

xmake的`package.tools.autoconf`适配这一工具

### 其他信息

https://emscripten.org/docs/compiling/Building-Projects.html#integrating-with-a-build-system

**Comment by waruqi** [comment]
有什么区别呢，现在 wasm 的包不是也构建的好好的。。

> emconfigure ./configure

看用法，应该就是自动导出绑定了 emcc 的 CC LD CFLAGS 等环境给 ./configure 。。

但是 `package.tools.autoconf` 在执行 ./configure 的时候，xmake 已经自动将 emcc toolchain 的环境绑定输出给 ./configure 了，做了 emconfigure 类似的事情，而且还能跟 xmake 内部编译 target 用的环境完全保持一致。。

而 emconfigure 外置的，它反而不清楚 xmake 对 target 等加载的 toolchain envs 状态，会有稍许差异。

**Comment by jingkaimori** [comment]
原来这个只是简单地调用configure脚本，没有为Windows准备shell环境。。。。关了这个issue。
