### ISSUE TITLE
Add C++ module for `xmake project`

### ISSUE THREAD

**Issue by glcraft** [xmake-io/xmake#4198]
### Is your feature request related to a problem? Please describe.

`xmake build` build my project fine. But using `xmake project` to generate a `compile_commands.json` won't work properly because C++ modules are not present in the json.

### Describe the solution you'd like

Add modules in the built source among others (listed in the function `_sourcebatch_is_built` of the file `/plugins/project/clang/compile_commands.lua` for example)

### Describe alternatives you've considered

For now, I'm using `xmake b -vD` to get xmake module build command that I copy/paste into the compile_command.json

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/pull/4199
