### ISSUE TITLE
xmake package, deps未考虑target的add_packages

### ISSUE THREAD

**Issue by Wzshun** [xmake-io/xmake#4202]
### Xmake 版本

2.8.1

### 操作系统版本和架构

windows10

### 描述问题

```
add_requires("C")
target("B")

target("A")
  add_deps("B")
  add_packages("C", {public=true})
```
打包A，不会把C纳入add_deps
```
xmake package A
```
生成xmake.lua
```
package("a")
  add_deps("b")
```

### 期待的结果

希望生成的xmake.lua为
```
package("a")
  add_deps("b", "c")
```
但这里可能需要考虑其他包管理器的package。。比方说 add_requires("conan::C")。。这就复杂了。。

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
再试试，支持 conan `xmake update -s dev`
