### ISSUE TITLE
Do not remove directories created by the user in the xmake install directory when updating xmake.

### ISSUE THREAD

**Issue by 1821746019** [xmake-io/xmake#4206]
### Is your feature request related to a problem? Please describe.

I created a folder named XMAKE_PKG_INSTALLDIR in the xmake install directory, where packages will be installed.
However, today I updated xmake and found that all the packages were removed. 
![uTools_1694864185150](https://github.com/xmake-io/xmake/assets/107804044/7b5366ea-9103-4122-b11d-607ad099aac4)

### Describe the solution you'd like

Overwrite the files instead of removing the entire directories when installing a new version.

**Comment by waruqi** [comment]
Do not add any user storage directories to the xmake installation directory.
