### ISSUE TITLE
Add Wpedantic option to set_warnings

### ISSUE THREAD

**Issue by FederAndInk** [xmake-io/xmake#4209]
### Is your feature request related to a problem? Please describe.

Simple QoL feature request :)

### Describe the solution you'd like

It would be great to be able to set [pedantic](https://clang.llvm.org/docs/DiagnosticsReference.html#wpedantic) with `set_warnings` like so(or similar):

```
set_warnings("all", "pedantic")
```

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/pull/4211

```
xmake update -s github:xmake-io/xmake#warn
```
