### ISSUE TITLE
Make packages inherit rules when they have a base

### ISSUE THREAD

**Issue by Qudix** [xmake-io/xmake#4210]
### Is your feature request related to a problem? Please describe.

At the moment if you have this scenario:

In xrepo:
```lua
package("foo")
    set_urls(...)
    ...
```
...while also containing `rules`.

And in your local script you define another package that uses it as a base:
```lua
package("bar")
    set_base("foo")
```

The rules from `foo` aren't available when `bar` is used.

### Describe the solution you'd like

Make packages inherit rules when they have a base.

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/pull/4212

try

```
xmake update -s github:xmake-io/xmake#base
```

**Comment by Qudix** [comment]
It works, thanks.
