### ISSUE TITLE
xmake build 总是重新编译全部模块, 即时没有修改任何源码, 如何解决?

### ISSUE THREAD

**Issue by sxstd001** [xmake-io/xmake#4215]
xmake build 每次都重新编译所有代码, 即时没有修改任何源码, 如何解决?

远程LINUX编译: XMAKE + GCC

XMAKE最新版本, 简单的写几个模块用于测试,  什么都不改, 连续三次执行 xmake --root, 结果如下: 

https://github.com/sxstd001/xmake_test/

[root@archlinux xmake_test]# xmake --root
[  9%]: compiling.module.debug type
[  9%]: compiling.module.debug timer
[ 27%]: compiling.module.debug fmt
[ 27%]: compiling.module.debug tc
[ 45%]: compiling.module.debug rand
[ 54%]: compiling.module.debug base
[ 72%]: compiling.debug main.cpp
[ 81%]: linking.debug hello
[100%]: build ok, spent 5.67s
[root@archlinux xmake_test]# xmake --root
[  9%]: compiling.module.debug type
[  9%]: compiling.module.debug timer
[ 27%]: compiling.module.debug fmt
[ 27%]: compiling.module.debug tc
[ 45%]: compiling.module.debug rand
[ 54%]: compiling.module.debug base
[ 72%]: compiling.debug main.cpp
[ 81%]: linking.debug hello
[100%]: build ok, spent 3.627s
[root@archlinux xmake_test]# xmake --root
[  9%]: compiling.module.debug type
[  9%]: compiling.module.debug timer
[ 27%]: compiling.module.debug tc
[ 27%]: compiling.module.debug fmt
[ 45%]: compiling.module.debug rand
[ 54%]: compiling.module.debug base
[ 72%]: compiling.debug main.cpp
[ 81%]: linking.debug hello
[100%]: build ok, spent 2.922s

目测没有复用已编译好的模块.

**Comment by waruqi** [comment]
提供完整可复现的最小 example project.

**Comment by sxstd001** [comment]
https://github.com/sxstd001/xmake_test/       vmware-archlinux gcc13  xmake2.8.2

**Comment by sxstd001** [comment]
> 提供完整可复现的最小 example project.
> 
> 另外，你没按 issues bug 模版提供对应信息。。

https://github.com/sxstd001/xmake_test/  xmake2.8.2  archlinux  gcc13

**Comment by waruqi** [comment]
再试试 https://github.com/xmake-io/xmake/pull/4237

```
xmake update -s github:xmake-io/xmake#parsedeps
```
