### ISSUE TITLE
Windows下Cargo build正常而xmake无法编译

### ISSUE THREAD

**Issue by xixioba** [xmake-io/xmake#4216]
### Xmake 版本

2.8.2+20230822

### 操作系统版本和架构

Win11 22621.2283

### 描述问题

参考[官方教程](https://xmake.io/#/guide/project_examples?id=integrating-cargotoml-dependency-packages)在**windows**下构建了binary程序，`Cargo build`可以正常编译，但xmake编译提示
` fatal error LNK1181: 无法打开输入文件“windows.0.48.5.lib”`
xmake相比于官方教程仅仅添加了一些第三方库
Windows下使用了MSVC编译器，`rustup default`返回
`stable-x86_64-pc-windows-msvc (default)`

### 期待的结果

应该Windows/Macos/Linux下得到一致的执行文件

### 工程配置

[compare_test.zip](https://github.com/xmake-io/xmake/files/12660357/compare_test.zip)

### 附加信息和错误日志

```
[ 33%]: linking.release test.exe
rustc -C opt-level=3 --edition 2021 -L dependency=C:\compare_test\build\.packages\c\cargo_test_deps\latest\abcb927c8565450fa520f946fd3e0342\lib --extern chrono=C:\compare_test\build\.packages\c\cargo_test_deps\latest\abcb927c8565450fa520f946fd3e0342\lib\libchrono-90a3a9d5be5e1b32.rlib --extern clap=C:\compare_test\build\.packages\c\cargo_test_deps\latest\abcb927c8565450fa520f946fd3e0342\lib\libclap-f00337b08293c3d6.rlib --extern env_logger=C:\compare_test\build\.packages\c\cargo_test_deps\latest\abcb927c8565450fa520f946fd3e0342\lib\libenv_logger-8e05b27c5bd657e7.rlib --extern log=C:\compare_test\build\.packages\c\cargo_test_deps\latest\abcb927c8565450fa520f946fd3e0342\lib\liblog-b12108de843d5a68.rlib --crate-type=bin -o build\windows\x64\release\test.exe src\main.rs
error: @programdir\modules\private\async\runjobs.lua:256: @programdir\rules\rust\build\target.lua:67: @programdir\core\sandbox\modules\os.lua:273: error: linking with `link.exe` failed: exit code: 1181
***
***
***
 note: LINK : fatal error LNK1181: 无法打开输入文件“windows.0.48.5.lib”
```

**Comment by xixioba** [comment]
经过对比`cargo build`，发现缺少了`rustup\.cargolregistry\srclindex.crates.io`里面的系统库链接
![{C79082B3-B1E5-96AB-5FBF-1389D8F19DC8}](https://github.com/xmake-io/xmake/assets/34228625/ff92df38-9432-47f7-b3f5-b5988e5e4da9)

**Comment by waruqi** [comment]
> 经过对比`cargo build`，发现缺少了`rustup\.cargo\registry\srclindex.crates.io`里面的系统库链接 ![{C79082B3-B1E5-96AB-5FBF-1389D8F19DC8}](https://user-images.githubusercontent.com/34228625/269174057-ff92df38-9432-47f7-b3f5-b5988e5e4da9.png)

关键是我还不清楚，这个路径怎么可靠的取出来

**Comment by xixioba** [comment]
似乎已经能抓到这个依赖，但是传递给`rustc`的时候没了

![WX20230921-150555@2x](https://github.com/xmake-io/xmake/assets/34228625/e66bfd1d-c55b-4072-8d1e-e1321fc29411)

顺便，我们可以只用`xmake`提取编译产物，`cargo build`取完成原生的工程编译么，因为发现xmake对cargo.toml的支持比较少，迁移到`xmake.lua`需要再写一遍，不是很优雅

**Comment by waruqi** [comment]
> 似乎已经能抓到这个依赖，但是传递给`rustc`的时候没了
> 
> ![WX20230921-150555@2x](https://user-images.githubusercontent.com/34228625/269521422-e66bfd1d-c55b-4072-8d1e-e1321fc29411.png)
> 
> 顺便，我们可以只用`xmake`提取编译产物，`cargo build`取完成原生的工程编译么，因为发现xmake对cargo.toml的支持比较少，迁移到`xmake.lua`需要再写一遍，不是很优雅

那你直接 on_build 通过 os.exec 执行下 cargo build，在 after_build 里面去下产物就行，其实用不用 xmake 也无所谓了。

xmake 里面支持 rust ，主要目的是为了跟 c++ 混编需要，纯粹的 rust 项目，直接走 cargo build ，完全没必要用 xmake

**Comment by xixioba** [comment]
那是后话了，现在的确是c++和rust混编的需求，macos/linux都搭完了，就剩windows下这个奇怪的问题了

**Comment by waruqi** [comment]
> 那是后话了，现在的确是c++和rust混编的需求，macos/linux都搭完了，就剩windows下这个奇怪的问题了

暂时没时间细研究，得看下这个路径怎么可靠的取出来，只要能取到 这边加上对应 -L flags 就行了，你可以先分析下看看

**Comment by xixioba** [comment]
关联 #4552 ，使用cargo build来编译纯rust项目
