### ISSUE TITLE
add_requires("libbacktrace")时xmake -a执行出错

### ISSUE THREAD

**Issue by GitHubUserC** [xmake-io/xmake#4218]
### Xmake 版本

2.8.2

### 操作系统版本和架构

Windows 10 专业版  22H2 19045.2965

### 描述问题

执行xmake -a -y -vD报错，即使手动创建C:\Users\Administrator\AppData\Local\.xmake\packages\l\libbacktrace\v1.0\78ebca0c18184ee29df2a2ea135e9a0f也会被自动删除然后报错

### 期待的结果

xmake -a执行成功

### 工程配置

set_config("plat", "linux")
set_project("cpp-util")
set_xmakever("2.7.5")

set_languages("c++17")
set_warnings("all")
add_rules("mode.debug", "mode.release")
set_optimize("faster")   -- faster: -O2  fastest: -O3  none: -O0
--add_cxflags("-Wno-narrowing", "-Wno-sign-compare", "-Wno-strict-aliasing")

add_cxflags("-fPIC")
add_requires("libbacktrace")

-- logger --
add_includedirs(".", "thirdparty/cpptoml/include")
add_installfiles("logger/*.h", {prefixdir = "include/cpputil/logger"})
add_installfiles("(util/**/*.h)", "(util/*.h)", {prefixdir = "include/cpputil"})
add_installfiles("logger/README.md", {prefixdir = "include/cpputil/logger"})

-- json_helper --
add_includedirs("thirdparty/boost/include")
add_installfiles("json_helper/*.h", {prefixdir = "include/cpputil/json_helper"})
add_installfiles("thirdparty/boost/include/boost/preprocessor.hpp", {prefixdir = "include/cpputil/boost"})
add_installfiles("thirdparty/boost/include/boost/preprocessor(/**/*.hpp)", {prefixdir = "include/cpputil/boost/preprocessor"})
add_installfiles("thirdparty/boost/include/boost/preprocessor/*.hpp)", {prefixdir = "include/cpputil/boost/preprocessor"})
add_installfiles("json_helper/README.md", {prefixdir = "include/cpputil/json_helper"})

target("cpputil")
    set_kind("static")
    -- logger --
    add_files("logger/*.cc|*_test.cc")  -- 添加 logger 下所有的 *.cc 文件, 但不包括 logger 下的 *_test.cc 文件
    -- add_files("thirdparty/backtrace/lib/libbacktrace.a", "thirdparty/uuid/lib/libuuid.a")
    add_packages("libbacktrace", { public = true })

### 附加信息和错误日志

checking for architecture ... x64
checking for gcc ... ok
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(unzip.exe -v), No such file or directory
checking for unzip ... no
checking for 7z ... C:\Program Files\xmake\winenv\bin\7z
checking for git ... ok
checkinfo: cannot runv(gzip.exe --version), No such file or directory
checking for gzip ... no
git rev-parse HEAD
finding libbacktrace from xmake ..
checking for xmake::libbacktrace ... no
checking for ping ... ok
pinging the host(github.com) ... 77 ms
git -c core.fsmonitor=false clean -d -f -x
git -c core.fsmonitor=false reset --hard
HEAD is now at d0f5e95 config/override.m4: don't require exactly autoconf 2.69
checking for gcc ... ok
checking for the c compiler (cc) ... gcc
checking for flags (-fPIC) ... ok
> gcc "-fPIC" "-m64"
checking for gcc ... ok
checking for the assember (as) ... gcc
checking for flags (-fPIC) ... ok
> gcc "-fPIC" "-m64"
checking for gcc ... ok
checking for the c++ compiler (cxx) ... gcc
checking for flags (-fPIC) ... ok
> gcc "-fPIC" "-m64"
checking for g++ ... ok
checking for the linker (ld) ... g++
checking for g++ ... ok
checking for flags (-fPIC) ... ok
> g++ "-fPIC" "-m64" "-m64"
checking for g++ ... ok
checking for the shared library linker (sh) ... g++
checking for flags (-fPIC) ... ok
> g++ "-fPIC" "-shared" "-m64" "-m64"
checking for ar ... ok
checking for the static library archiver (ar) ... ar
./configure --enable-shared=no --enable-static=yes --prefix=C:\Users\Administrator\AppData\Local\.xmake\packages\l\libbacktrace\v1.0\78ebca0c18184ee29df2a2ea135e9a0f
error: @programdir\core\sandbox\modules\os.lua:378: cannot execv(./configure --enable-shared=no --enable-static=yes --prefix=C:\Users\Administrator\AppData\Local\.xmake\packages\l\libbacktrace\v1.0\78ebca0c18184ee29df2a2ea135e9a0f), No such file or directory
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:921]:
    [@programdir\core\sandbox\modules\os.lua:378]:
    [@programdir\core\sandbox\modules\os.lua:291]: in function 'vrunv'
    [@programdir\modules\package\tools\autoconf.lua:449]: in function 'configure'
    [@programdir\modules\package\tools\autoconf.lua:473]: in function 'build'
    [@programdir\modules\package\tools\autoconf.lua:502]: in function 'install'
    [...epositories\xmake-repo\packages\l\libbacktrace\xmake.lua:17]: in function 'script'
    [...dir\modules\private\action\require\impl\utils\filter.lua:125]: in function 'call'
    [...\modules\private\action\require\impl\actions\install.lua:364]:

  => install libbacktrace v1.0 .. failed
error: @programdir\modules\async\runjobs.lua:256: ...\modules\private\action\require\impl\actions\install.lua:469: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:921]:
    [...\modules\private\action\require\impl\actions\install.lua:469]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:328]:
    [...modules\private\action\require\impl\install_packages.lua:479]: in function 'jobfunc'
    [@programdir\modules\async\runjobs.lua:232]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:921: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\modules\async\runjobs.lua:256: in field 'catch'
        @programdir\core\sandbox\modules\try.lua:123: in global 'try'
        @programdir\modules\async\runjobs.lua:218: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>

**Comment by waruqi** [comment]
./configure 执行不了，这个包仅支持 linux, macosx，你 windows 上当然不行了，为啥还强行切到 plat=linux。。不要乱搞。。

**Comment by GitHubUserC** [comment]
原来如此，谢谢大佬，BTW，Win开发者好惨
