### ISSUE TITLE
xmake，在sdk指定为clang时，对于set_kind("shared")，生成的shflags默认带-fPIC，而ld.lld不支持

### ISSUE THREAD

**Issue by fxv2** [xmake-io/xmake#4220]
### Xmake 版本

v2.7.9+20230515

### 操作系统版本和架构

Ubuntu 18.04 x86_64 kernel4.15

### 描述问题

xmake，linux64架构交叉编译arm64 linux，--sdk为clang
报错：
/ld.lld -o libsqlite.sosqlite3.c.o -fPIC -shared
error: ld.lld: error: unknown argument '-fPIC'

### 期待的结果

如何unset掉shflags中的-fPIC参数？
通过xmake生成Makefile，手动删除sh链接命令中的 -fPIC参数后，编译成功。但是有一堆程序都用xmake，这样改起来太麻烦。

### 工程配置

    xmake f -p cross -a arm64 -m debug --sdk=${CLANG_PATH} -o $BUILD_OUTPUT_PATH/sqlite3/build 
add_includedirs("inc")

target("sqlite")
  set_kind("shared")
  add_files("src/sqlite3.c")
  on_install(function(target)
    os.cp(target:targetfile(), "$(env INSTALL_DIR)")
  end)

### 附加信息和错误日志

/ld.lld -o libsqlite.sosqlite3.c.o -fPIC -shared
error: @programdir/modules/private/async/runjobs.lua:256: @programdir/actions/build/kinds/shared.lua:89: @programdir/core/sandbox/modules/os.lua:273: ld.lld: error: unknown argument '-fPIC'

stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:913]:
    [@programdir/core/sandbox/modules/os.lua:273]: in function 'runv'
    [@programdir/modules/core/tools/ld.lua:81]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/core/tool/linker.lua:224]: in function 'link'
    [@programdir/actions/build/kinds/shared.lua:89]: in function 'callback'
    [@programdir/modules/core/project/depend.lua:193]: in function 'on_changed'
    [@programdir/actions/build/kinds/shared.lua:55]: in function '_do_link_target'
    [@programdir/actions/build/kinds/shared.lua:117]:
    [@programdir/actions/build/kinds/shared.lua:144]: in function '_link_target'
    [@programdir/actions/build/kinds/shared.lua:172]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:232]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:117]: in function 'try'
    [@programdir/modules/private/async/runjobs.lua:218]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:404]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:913: in function 'os.raiselevel'
        (...tail calls...)
        @programdir/modules/private/async/runjobs.lua:256: in field 'catch'
        @programdir/core/sandbox/modules/try.lua:123: in global 'try'
        @programdir/modules/private/async/runjobs.lua:218: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>

**Comment by waruqi** [comment]
为啥要直接用 ld.lld 不用 `clang++` 和 `-fuse-ld`

即使交叉编译，默认的 linker 应该也是 clang++/g++

**Comment by fxv2** [comment]
非常感谢您的解答。
通过xmake命令行手动指定sh为clang++，添加了shflags和cflags后，不再报错。
起初命令行只指定了--sdk选项，然后linker和shlinker被默认为ld.lld。
在这个链接里找到了您的文档中关于编译套件linker设定的说明，[Set the c/c++ linker](https://xmake.io/#/guide/configuration?id=set-the-cc-linker)
可以解释一下将linker指定为clang++的原理吗？顺祝时祺。

**Comment by fxv2** [comment]
对于比较大型的项目，ld.lld相较clang++链接速度要快很多，也支持LTO等优化。所以未来版本考不考虑一下，支持诸如shflags等参数的覆盖而非添加？

**Comment by waruqi** [comment]
> 对于比较大型的项目，ld.lld相较clang++链接速度要快很多，也支持LTO等优化。所以未来版本考不考虑一下，支持诸如shflags等参数的覆盖而非添加？

原本就支持，前面说了切 ld 走 `-fuse-ld=ld.lld` ，不要直接切 clang++

```lua
add_shflags("-fuse-ld=ld.lld")
add_ldflags("-fuse-ld=ld.lld")
```
