### ISSUE TITLE
无法通过 Cargo.toml 指定本地包

### ISSUE THREAD

**Issue by oxc-v** [xmake-io/xmake#4222]
### Xmake 版本

2.8.2

### 操作系统版本和架构

Linux 5.14.0-70.13.1.el9_0.x86_64

### 描述问题

xmake 使用 Cargo.toml 加载依赖时，如果里面是本地包，xmake 无法正确构建：

# Cargo.toml:
[package]
name = "test-add"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
add-rs = { path = "../add-rs" }

# 输出：
![image](https://github.com/xmake-io/xmake/assets/59563828/4dcdcb25-5265-4e0f-be27-4d8595b9ad5f)

# 初步分析：
xmake 会将当前 Cargo.toml 复制到 build 相关目录下，并执行 cargo 命令，导致里面的路径失效，从而找不到本地包

### 期待的结果

无

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
看下这个

**Comment by oxc-v** [comment]
> 看下这个 #4214

还是不行
![image](https://github.com/xmake-io/xmake/assets/59563828/118c9b9e-35e9-42aa-bc14-ad8bba3b0d2b)

**Comment by waruqi** [comment]
给下完整可复现 project

**Comment by oxc-v** [comment]
[xmake_demon.tar.gz](https://github.com/xmake-io/xmake/files/12671063/xmake_demon.tar.gz)

**Comment by waruqi** [comment]
再试试，`xmake update -s dev`
