### ISSUE TITLE
无法通过 add_requires(“cargo::async-trait 0.1.73”) 安装依赖

### ISSUE THREAD

**Issue by oxc-v** [xmake-io/xmake#4228]
### Xmake 版本

2.8.2

### 操作系统版本和架构

Linux 10-16-43-57 5.14.0-70.13.1.el9_0.x86_64

### 描述问题

无法下载 cargo  async-trait 依赖

### 期待的结果

正常下载

### 工程配置

[demon.zip](https://github.com/xmake-io/xmake/files/12679770/demon.zip)

### 附加信息和错误日志

<img width="1117" alt="image" src="https://github.com/xmake-io/xmake/assets/59563828/e6491560-b828-4894-81e6-8ccdb151e073">

**Comment by waruqi** [comment]
这个包安装后，deps 都是 rlib，而 async-trait 不是 rlib，而是 dylib (至少在macos上是)

我暂时对 macos 上改进支持了，但不确定是否完全可用，linux 下是否为 .so 还是啥，我暂时没环境测试。。

你可以参看这个 patch ，提个 pr 过来加上 linux 的支持

https://github.com/xmake-io/xmake/commit/18fe125530192566779c797d0e7006aa5c78c550

**Comment by oxc-v** [comment]
> 这个包安装后，deps 都是 rlib，而 async-trait 不是 rlib，而是 dylib (至少在macos上是)
> 
> 我暂时对 macos 上改进支持了，但不确定是否完全可用，linux 下是否为 .so 还是啥，我暂时没环境测试。。
> 
> 你可以参看这个 patch ，提个 pr 过来加上 linux 的支持
> 
> [18fe125](https://github.com/xmake-io/xmake/commit/18fe125530192566779c797d0e7006aa5c78c550)

目前测试 macOS 可行，但是 linux 不行，linux 我看是 .so

**Comment by waruqi** [comment]
再试试呢

**Comment by oxc-v** [comment]
> 再试试呢

可以了
