### ISSUE TITLE
vcpkg集成问题

### ISSUE THREAD

**Issue by ccliuyang** [xmake-io/xmake#423]
我现在在vcpkg中进行开源动态库的编译，然后采用vckpg导出功能，导出包含指定开源包的一个文件夹，我怎样在xmake脚本中集成这个导出的目录

**Comment by waruqi** [comment]
不用导出 直接集成使用就行,xmake会自动给你装vcpkg的包的 看下 https://tboox.org/cn/2019/04/01/xmake-v2.2.5-new-features/

**Comment by ccliuyang** [comment]
嗯，本地安装的vcpkg是可以的，不过我导出来的就不行了，指定那个目录也不行，看来是不支持这样了

**Comment by waruqi** [comment]
嗯，不支持导出

**Comment by waruqi** [comment]
不过你可以通过在项目中扩展find_package来自定义找库，`find_packages("vcpkg::xxx")`

你可以看下 https://xmake.io/#/zh/manual?id=detect-find_package 

> 查找一个名为openssl的包，可以编写一个find_openssl.lua的脚本放置在工程目录：
> 
> projectdir
>  - xmake
>    - modules
>      - detect/package/find_openssl.lua
> 然后在工程的xmake.lua文件的开头指定下这个modules的目录：
> 

add_moduledirs("$(projectdir)/xmake/modules")

另外扩展后，add_requires里面也会同时生效，内部其实也是调用了find_packages，如果能找到，就不会自动去下载安装了，直接集成使用
