### ISSUE TITLE
使用 add_requires 安装 cargo 依赖时指定 features 导致安装失败

### ISSUE THREAD

**Issue by oxc-v** [xmake-io/xmake#4231]
### Xmake 版本

2.8.2

### 操作系统版本和架构

macOS ventura

### 描述问题

使用 add_requires 安装 cargo 依赖时指定 features 导致安装失败

### 期待的结果

正确安装

### 工程配置

[demon.zip](https://github.com/xmake-io/xmake/files/12682540/demon.zip)

### 附加信息和错误日志

<img width="709" alt="image" src="https://github.com/xmake-io/xmake/assets/59563828/77fc9a65-19bf-4697-a2ab-8f759fd93f6f">

**Comment by waruqi** [comment]
再试试，应该可以了，不过这个包现在好像没这个 feature 了，`xmake update -s dev`

> does not have the feature `zlib`

**Comment by oxc-v** [comment]
> 再试试，应该可以了，不过这个包现在好像没这个 feature 了，`xmake update -s dev`
> 
> > does not have the feature `zlib`

![image](https://github.com/xmake-io/xmake/assets/59563828/de7669d3-6378-45f1-9322-e24e3242f3f2)
![image](https://github.com/xmake-io/xmake/assets/59563828/2fde4b41-1510-4e84-b8e4-f154031b6502)

xmake 还是不行，cargo build 没问题，固定的版本 feature 不会消失的

**Comment by waruqi** [comment]
是指哪里不行，之前的 error 应该已经修复，新 error ，那就贴下

**Comment by oxc-v** [comment]
> 是指哪里不行，之前的 error 应该已经修复，新 error ，那就贴下

![image](https://github.com/xmake-io/xmake/assets/59563828/a95f1e54-f9db-4a0a-a4ca-002414429d84)
![image](https://github.com/xmake-io/xmake/assets/59563828/b2aa7897-59a4-4df6-bedf-a3723351a1f9)
cargo 能够正确识别这些版本的 feature

**Comment by waruqi** [comment]
xmake 里面安装也没问题，是 build 完，会去执行 ` cargo metadata --format-version 1 --manifest-path ./Cargo.toml --color never --features zlib` dump 依赖信息，这个时候报错了

**Comment by waruqi** [comment]
改了下，再试试  `xmake update -s dev`
