### ISSUE TITLE
关于库的 group和whole 以及顺序问题

### ISSUE THREAD

**Issue by Dozingfiretruck** [xmake-io/xmake#4234]
### 你在什么场景下需要该功能？

使用到的嵌入式项目有许多需要使用 group和whole 是否可以直接在add_links和add_deps中添加控制参数比如add_links("test",{group=true,whole =true})类似这种控制方式，我们的几个项目中使用的越来越多的这种，现在使用中体验越来越不友好，如果完全走on_link会更麻烦一些，并且我们是做成sdk开放出去，这里用on_link用户并加很多库和代码之后客户也不能很好地控制

### 描述可能的解决方案

add_links和add_deps中添加控制参数比如add_links("test",{group=true}),add_deps("test",{whole =true})

**Comment by waruqi** [comment]
这个其实是老问题，具体见：https://github.com/xmake-io/xmake/issues/1452

这块涉及到部分重构，以及新的 API 设计，要尽可能不失灵活性，可扩展性的同时，保证改动量最小，降低实现复杂度。

这个之后肯定会改进，但至少需要连续的空闲时间，我才能思考的周全些，但目前有限的碎片化时间，不太好搞。

目前的一种 workaround 的方式，就是 `add_deps("xxx", {inherit = false})` 禁用 link 继承，然后走 add_ldflags 全盘控制，自己加 group/whole 处理。

**Comment by Dozingfiretruck** [comment]
> 这个其实是老问题，具体见：#1452
> 
> 这块涉及到部分重构，以及新的 API 设计，要尽可能不失灵活性，可扩展性的同时，保证改动量最小，降低实现复杂度。
> 
> 这个之后肯定会改进，但至少需要连续的空闲时间，我才能思考的周全些，但目前有限的碎片化时间，不太好搞。
> 
> 目前的一种 workaround 的方式，就是 `add_deps("xxx", {inherit = false})` 禁用 link 继承，然后走 add_ldflags 全盘控制，自己加 group/whole 处理。
> 
> 你也可以把自己想到的设计方案和建议，提到 #1452 里面去。

看到了，期待，这个问题还是很常见的
另外我现在就是`add_deps("xxx", {inherit = false})` 禁用 link 继承，然后走 add_ldflags的，但是我自己的项目自己可以控制，像公司的sdk就没法知道用户连接了多少库，能否有一个方便的方式知道项目一个deps了多少个静态库，还有静态库目录都在哪
比如 用户在taget A里deps了一个taget B，并且add_linkdirs了静态库目录，我如何在最终执行link的taget比较方便的遍历出项目一共deps了多少静态库，和add_linkdirs了多少，我尝试看taget:get()，但是只能得到当前taget的一些信息，deps的获取不到

**Comment by waruqi** [comment]
> > 这个其实是老问题，具体见：#1452
> > 这块涉及到部分重构，以及新的 API 设计，要尽可能不失灵活性，可扩展性的同时，保证改动量最小，降低实现复杂度。
> > 这个之后肯定会改进，但至少需要连续的空闲时间，我才能思考的周全些，但目前有限的碎片化时间，不太好搞。
> > 目前的一种 workaround 的方式，就是 `add_deps("xxx", {inherit = false})` 禁用 link 继承，然后走 add_ldflags 全盘控制，自己加 group/whole 处理。
> > 你也可以把自己想到的设计方案和建议，提到 #1452 里面去。
> 
> 看到了，期待，这个问题还是很常见的 另外我现在就是`add_deps("xxx", {inherit = false})` 禁用 link 继承，然后走 add_ldflags的，但是我自己的项目自己可以控制，像公司的sdk就没法知道用户连接了多少库，能否有一个方便的方式知道项目一个deps了多少个静态库，还有静态库目录都在哪 比如 用户在taget A里deps了一个taget B，并且add_linkdirs了静态库目录，我如何在最终执行link的taget比较方便的遍历出项目一共deps了多少静态库，和add_linkdirs了多少，我尝试看taget:get()，但是只能得到当前taget的一些信息，deps的获取不到

```lua
for _, dep in ipairs(target:orderdeps()) do
    local linkdir = dep:targetdir()
end

**Comment by Dozingfiretruck** [comment]
> > > 这个其实是老问题，具体见：#1452
> > > 这块涉及到部分重构，以及新的 API 设计，要尽可能不失灵活性，可扩展性的同时，保证改动量最小，降低实现复杂度。
> > > 这个之后肯定会改进，但至少需要连续的空闲时间，我才能思考的周全些，但目前有限的碎片化时间，不太好搞。
> > > 目前的一种 workaround 的方式，就是 `add_deps("xxx", {inherit = false})` 禁用 link 继承，然后走 add_ldflags 全盘控制，自己加 group/whole 处理。
> > > 你也可以把自己想到的设计方案和建议，提到 #1452 里面去。
> > 
> > 
> > 看到了，期待，这个问题还是很常见的 另外我现在就是`add_deps("xxx", {inherit = false})` 禁用 link 继承，然后走 add_ldflags的，但是我自己的项目自己可以控制，像公司的sdk就没法知道用户连接了多少库，能否有一个方便的方式知道项目一个deps了多少个静态库，还有静态库目录都在哪 比如 用户在taget A里deps了一个taget B，并且add_linkdirs了静态库目录，我如何在最终执行link的taget比较方便的遍历出项目一共deps了多少静态库，和add_linkdirs了多少，我尝试看taget:get()，但是只能得到当前taget的一些信息，deps的获取不到
> 
> ```lua
> for _, dep in ipairs(target:orderdeps()) do
>     local linkdir = dep:targetdir()
> end
> ```

好的，感谢，另外像 target:orderdeps() 这种文档是否考虑完善一下呢？之前比如 target:toolchains()[1]:bindir() 之类的都是自己打印或者翻源码看的，文档如果有更详细的说明会更方便

**Comment by waruqi** [comment]
暂时没太多时间完善文档，后面有空改进

**Comment by ivanallen** [comment]
whole-archive 这个太迫切了，好多底层库都使用了 __attribute__((constructor)) 修饰，这种库基本都需要 whole-archive

**Comment by waruqi** [comment]
初步改进了下，试试 https://github.com/xmake-io/xmake/issues/1452#issuecomment-1741152822

**Comment by waruqi** [comment]
支持了。`xmake update -s dev`
