### ISSUE TITLE
os.touch 在windows平台不更新mtime

### ISSUE THREAD

**Issue by RimuruChan** [xmake-io/xmake#4239]
### Xmake 版本

v2.8.2+HEAD.57212c681

### 操作系统版本和架构

Windows 11 22621.2283

### 描述问题

os.touch没有更新目标文件的修改时间

### 期待的结果

更新目标文件的修改时间到当前时间

### 工程配置

略

### 附加信息和错误日志

略

**Comment by waruqi** [comment]
用法不对，不是 `os.touch(file)` ，得设置修改 mtime 才行，默认不带 mtime 设置，仅仅只是创建空文件。

```lua
os.touch(objectfile, {mtime = os.time()})
```
