### ISSUE TITLE
set_symbols("debug")在release模式下存在问题

### ISSUE THREAD

**Issue by ranwei1025** [xmake-io/xmake#425]
vs 的release模式下 会自动产生pdb文件
xmake设置为 set_symbols("debug") 在release模式下 也会产生pdb文件

但产生的文件 要比不设置  set_symbols("debug")  大一半左右
而vs的release模式 不管配置产生pdb 还是不产生pdb 生成的文件大小时一样的

**Comment by waruqi** [comment]
首先 xmake跟vs的release/debug模式没有可比性，毕竟两者参数肯定会有差异，xmake默认的mode rule不会可以去跟vs完全保持一致，除非用户自己配置release/mode，不用内置的mode.release规则

其次 xmake内置的mode.release规则，设置的是set_symbols("hidden")，也就是隐藏所有符号，也不会带调试符号信息，此时的pdb当然会很小，因为没有生成调试符号信息在里面

而你在mode.release下，通过set_symbols("debug")强行设置启用调试符号信息，那么pdb当然变大了，并没觉得哪里有问题

vs下release/debug下pdb大小一样，是因为不管是否release，它可能默认都启用了symbols debug，也就是-g

如果你说的是跟xmake project -k vs201x生成的vs工程，release模式有差异，那就是生成vs工程插件处理上存在一些问题，你这是自建vcproj，还是用xmake生成的？

**Comment by ranwei1025** [comment]
生成的文件大小时一样的 不是pdb文件 而是目标文件 
所以认为 xmake的  set_symbols("debug")  在release模式下 产生的文件 不是最优的 在大小和优化指令上 
对比vs 自己产生的工程 release模式 产不产生pdb文件 都是最优的

**Comment by waruqi** [comment]
这跟release没啥关系，是`set_symbols("debug")`的问题，还会在linker的时候追加`/debug`选项，这个会增加exe文件的大小

mode.release: 没设置`set_symbols("debug")`，所以没有/debug选项，exe非常小
mode.release + symbols/debug:  除了启用pdb，还会加上/debug，但是exe会稍微大点
mode.debug: 内置symbols/debug，所以exe也会大，但是大小跟`mode.release + symbols/debug`生成的一样大

而vs下，编译pdb，链接pdb（/debug）是分别设置的，如果只是禁用编译pdb，没禁用/debug，那么exe大小，两者也是相同。。

你可以自己对比下编译参数，我不觉得现在有什么问题，如果你觉得 内置的 `set_symbols("debug")` 不满足需求，可以直接通过 add_cxflags add_ldflags的放置，定制化设置。

**Comment by ranwei1025** [comment]
目前问题不大 只是对比vs产生的release和pdb条件下的文件 要大一些
应该还有改进的空间

**Comment by waruqi** [comment]
这个暂时先这样吧，等以后有强需求了，我再改进下。你可以自己通过 add_cxflags add_ldflags 来进一步优化
