### ISSUE TITLE
add_files should read files in hidden directory |需要拓展add_files的功能到支持隐藏目录

### ISSUE THREAD

**Issue by bruce-the-terrible** [xmake-io/xmake#4254]
### 你在什么场景下需要该功能？

```
#!/bin/zsh
filename="xmake.lua"
projectname="fake_xmake"
rm -rf $filename
rm -rf compile_command.json
touch $filename
touch .git
#echo "set_project(\"$1\")" >> $filename
echo "set_project(\"$projectname\")" >> $filename
echo "set_xmakever(\"2.7.9\")" >> $filename
echo "set_version(\"1.0.0\")" >> $filename
#echo "  target(\"$1\")" >> $filename
echo "  target(\"$projectname\")" >> $filename
echo "      set_kind(\"binary\")" >> $filename
echo "      set_targetdir(\"./build\")" >> $filename
echo "      add_files(\"./**.c\")" >> $filename
echo "      add_files(\"./**.s\")" >> $filename
#echo "      add_files(\"./**.cpp\")" >> $filename
#echo "      add_files(\"./**.cxx\")" >> $filename
find . -iname "*.h" -o -iname "*.hpp" -o -iname "*.hxx" |\
    xargs -o dirname |sort|uniq|\
    while read dir_name ;do 
        echo "      add_includedirs(\"$dir_name\")";
    done >> $filename
xmake project -k compile_commands
```
I write a script above . Run this script at source code directory ,  a fake compile_commands.json will be created .
Compile_commands.json is used to make neovim happy , so I can read any c/c++ project source code without compile it really .
But , here comes a problem : c/c++ files in hidden directory will not be read . 
-----------------------
我写了一个上述脚本，只要在任何c/c++项目的根目录下运行这个脚本，就可以得到一个compile_commands.json，但是目前这个功能受限，因为add_files不能读隐藏目录下的代码。可能还存在其他类似的限制，所以无法用一个简单的脚本处理所有的情况

### 描述可能的解决方案

1、The best plane is : xmake team provide and maintain a script to generate fake compile_commands.json
2、or expand function of add_files and add_includedirs  , make it easy
--------------------------------
xmake官方维护一个产生“虚假compile_commands.json”的脚本，则善莫大焉
否则，请扩展一下add_files和add_includedirs的功能，让我写这个脚本更容易一点

### 其他信息

Programmers may often encounter "I need to read this bunch of code  , which cannot be compiled and is messy", therefore, a simple script is urgently needed at this moment .  It can be run directly to create compil_commands.json for this bunch of code without any modification.  Makes tools like neovim to do the following job .

由于程序员经常可能接接触到“我要读这一坨无法编译、乱七八糟”的代码，所以，这时候就急需一个简单的脚本，不需要经过任何修改，直接运行就能为这一堆代码建立compil_commands.json，进而让neovim这样的工具能工作起来。

**Comment by waruqi** [comment]
? it works for me.

```lua
target("test")
    set_kind("binary")
    add_files("src/*.cpp")
    add_files("**.c")
```

```console
ruki-2:test ruki$ touch .deps/test.c
ruki-2:test ruki$ xmake -r
[ 20%]: cache compiling.release .deps/test.c
[ 20%]: cache compiling.release src/main.cpp
[ 60%]: linking.release test
[100%]: build ok, spent 1.524s
ruki-2:test ruki$ xmake project -k compile_commands
create ok!
ruki-2:test ruki$ cat ./compile_commands.json | grep .deps
  "arguments": ["/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bi
n/clang", "-c", "-Qunused-arguments", "-target", "x86_64-apple-macos12.6", "-isysroot", "/Applications
/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk", "-fvisibility=
hidden", "-O3", "-DNDEBUG", "-o", "build/.objs/test/macosx/x86_64/release/.deps/test.c.o", ".deps/test
.c"],
  "file": ".deps/test.c"
```
