### ISSUE TITLE
Xrepo update-repo  --root can not work

### ISSUE THREAD

**Issue by Oyyko** [xmake-io/xmake#4255]
### Xmake Version

xmake v2.8.3+HEAD.2b61611, A cross-platform build utility based on Lua

### Operating System Version and Architecture

Archlinux newest

### Describe Bug

Xrepo update-repo can not run on root mode even if I added `--root` or `XMAKE_ROOT=y`.

### Expected Behavior

It should runs on root mode when you add `--root`.

### Project Configuration

https://github.com/XmacsLabs/mogan/blob/branch-1.2/xmake.lua

### Additional Information and Error Logs

I found the problem when I run `xrepo update-repo`.

No problem with `xmake`.

So obviously it is an XREPO ISSUE.

**Comment by waruqi** [comment]
use `XMAKE_ROOT=y`, it works for me.

```
XMAKE_ROOT=y xrepo update-repo
```

**Comment by darcy-shen** [comment]
Here is a neat solution in xrepo:
https://github.com/xmake-io/xmake-repo/blob/dev/.github/workflows/archlinux.yml#L37-L38

I guess it is because you are running the wrong bash command line.

**Comment by waruqi** [comment]
> Here is a neat solution in xrepo: https://github.com/xmake-io/xmake-repo/blob/dev/.github/workflows/archlinux.yml#L37-L38
> 
> I guess it is because you are running the wrong bash command line.

You can run it on ci, and XMAKE_ROOT works.
