### ISSUE TITLE
`has_cxxfuncs` may not work correctly.

### ISSUE THREAD

**Issue by ChenPi11** [xmake-io/xmake#4257]
### Xmake Version

v2.8.3+master.4ea057304

### Operating System Version and Architecture

Microsoft Windows 11 amd64 22H2

### Describe Bug

In C++, functions may have a lots of overload, that makes `has_cxxfuncs` not work correctly, like this

Definition of package header
```cpp
iconv_t iconv_open(const char* , const char*);
iconv_t iconv_open(int, int);
```
`has_cxxfuncs` will generate this code.
```cpp
#include <xxx.hpp>

int main(int argc, char** argv)
{
    volatile void* piconv_open = (void*)&iconv_open; if (piconv_open) {};
    return 0;
}
```
But the compiler does not know which overload are you referring to.

Another bug is that C++ function may have namespace, like this
```cpp
namespace a
{
    void function(void);
}
```
`has_cxxfuncs` will generate this code
```cpp
#include <xxx.hpp>

int main()
{
    volatile void* pa::function = (void*)&a::function; if (pa::function) {};
    return 0;
}
```
This will cause a terrible compilation failure.

======================================

C++中，函数可能有多个重载，这使`has_cxxfuncs`不能正常工作，比如这个

软件包头文件的定义
```cpp
iconv_t iconv_open(const char* , const char*);
iconv_t iconv_open(int, int);
```
`has_cxxfuncs` 会生成如下代码
```cpp
#include <xxx.hpp>

int main(int argc, char** argv)
{
    volatile void* piconv_open = (void*)&iconv_open; if (piconv_open) {};
    return 0;
}
```
但编译器无法知道`iconv_open`指的是那个重载。

另一个bug是因为 C++ 函数可能有命名空间，像这样
```cpp
namespace a
{
    void function(void);
}
```
`has_cxxfuncs` 会生成如下代码
```cpp
#include <xxx.hpp>

int main()
{
    volatile void* pa::function = (void*)&a::function; if (pa::function) {};
    return 0;
}
```
这会导致致命的编译错误

**Comment by waruqi** [comment]
try pass arguments.

```lua
has_cxxfuncs("iconv_open(0,0)")
has_cxxfuncs("pa::function()")
```

<img width="625" alt="image" src="https://github.com/xmake-io/xmake/assets/151335/b37d5ea8-c66f-4f3a-a924-330f93d120dd">

https://xmake.io/#/manual/extension_modules?id=detecthas_cxxfuncs

or use `check_cxxsnippets`
