### ISSUE TITLE
AArch64 packages in the Ubuntu repository?

### ISSUE THREAD

**Issue by davidchisnall** [xmake-io/xmake#4258]
### Is your feature request related to a problem? Please describe.

We're building a devcontainer on Ubuntu and installing xmake from the PPA.  Unfortunately, this contains only x86 packages

### Describe the solution you'd like

Packages for AArch64 as well.

### Describe alternatives you've considered

Building xmake ourselves, but that means that `apt upgrade` won't let users pull a new version.

**Comment by waruqi** [comment]
But I don't know how to upload arm64 packages in ppa repository.

only x86_64/amd64 now

<img width="405" alt="image" src="https://github.com/xmake-io/xmake/assets/151335/61d66c8c-ebea-46bd-999a-cc7dbdb2cd8b">

**Comment by davidchisnall** [comment]
Is the problem building or uploading?  Uploading should be the same as for i386 and amd64?

**Comment by waruqi** [comment]
It is built on the ppa cloud, we just call the script on the ci to upload the source package and debian packaging script, and I have configured the debian script as any cpu.

We don't build binaries locally and then go and upload them.

I don't know why the arm64 binary package is not automatically built on the ppa server

https://github.com/xmake-io/xmake/blob/master/scripts/makeppa

https://github.com/xmake-io/xmake/blob/4ea0573047db301f1569c9d6b0d117f92433db49/.github/workflows/linux.yml#L50

https://github.com/xmake-io/xmake/blob/4ea0573047db301f1569c9d6b0d117f92433db49/scripts/debian/control#L12

**Comment by davidchisnall** [comment]
Looking at [the docs](https://help.launchpad.net/Packaging/PPA) it appears that you need to explicitly request other architectures by going to the 'Change details' page for the PPA.  It also warns:

> Changing the set of architectures for which a PPA builds does not create new builds for source packages that are already published in that PPA; it only affects which builds will be created for new uploads. If you need to create builds for newly-enabled architectures without reuploading, go to "View package details" and then "Copy packages", select all the packages for which you want to create builds, select "This PPA", "The same series", and "Copy existing binaries", and submit the form using the "Copy Packages" button.

**Comment by waruqi** [comment]
Thanks, I have enabled all architectures. you can try it again.

<img width="477" alt="image" src="https://github.com/xmake-io/xmake/assets/151335/502d344c-8df0-40ea-b521-cfb1be118979">

**Comment by waruqi** [comment]
xmake is in the debian repository now. https://packages.debian.org/sid/xmake
