### ISSUE TITLE
xmake 建议-n --no 参数 默认跳过安装

### ISSUE THREAD

**Issue by ranwei1025** [xmake-io/xmake#426]
类似于 
-y, --yes            Input yes by default if need user confirm.
在脚本调用下 有时不需要安装这些包 需要自动跳过

**Comment by waruqi** [comment]
既然要调过安装，那为什么还要执行`xmake install`呢，直接调过执行此命令不就好了。

**Comment by ranwei1025** [comment]
比如下面这个命令 会要求输入 
xmake f  -p linux -a aarch64 --sdk=/home/bl/aarch64 --cross=aarch64-linux-
。。。。。。。
note: try installing these packages (pass -y to skip confirm)?
in xmake-repo:
  -> sqlite3 3.24.0 (optional)
  -> openssl 1.1.1 (optional)
  -> mysql 5.7.23 (optional)
  -> mbedtls 2.13.0 (optional)
  -> pcre2 10.31 (optional)
     or pcre 8.41 (optional)
please input: y (y/n)
上面如果输入 y 会安装相关的包裹 但我这边用不到 还会花很长时间

**Comment by waruqi** [comment]
哦，这个可以考虑加个，我之后处理下。

**Comment by waruqi** [comment]
我支持了，你更新下dev分支版本试试：

```console
    -y, --yes                              Input yes by default if need user confirm.
        --confirm=CONFIRM                  Input the given result if need user confirm.
                                               - y|yes
                                               - n|no
                                               - d|def
```

新增一个`--confirm=y` 参数选项，可以指定调过用户确认时，传递的值：y/yes通过，n/no不通过，d/def按照默认值行为处理

**Comment by ranwei1025** [comment]
xmake f --confirm=n -p linux -a aarch64 --sdk=/home/bl/aarch64 --cross=aarch64-linux-
cc ar 不对了 cc=/urs/bin/gcc 

更新最新版本之前 下面的命令工作正常
xmake f -p linux -a aarch64 --sdk=/home//bl/aarch64 --cross=aarch64-linux-
