### ISSUE TITLE
ArchLinux 下面通过 pacman 安装的 xmake 无法使用

### ISSUE THREAD

**Issue by luozhiya** [xmake-io/xmake#4263]
### Xmake 版本

NO

### 操作系统版本和架构

Linux R9-7950X-CODE 6.5.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 23 Sep 2023 22:55:13 +0000 x86_64 GNU/Linux

### 描述问题

1. 编译安装master版本，然后卸载
```
git clone --recursive https://github.com/xmake-io/xmake.git
cd ./xmake
./configure
make
./scripts/get.sh __local__ __install_only__
source ~/.xmake/profile

xmake update --uninstall
```

2. 再安装pacman版本
```
sudo pacman -Sy xmake

whereis xmake
xmake: /usr/bin/xmake /usr/share/xmake

xmake --version
not found main script: ~/.local/share/xmake/core/_xmake_main.lua
```

### 期待的结果

`xmake --version` 可以正常打印版本

### 工程配置

NO

### 附加信息和错误日志

NO

**Comment by waruqi** [comment]
不要混着装

> 编译安装master版本，然后卸载

走源码安装，或者一键脚本安装，默认安装在 `~/.local/bin` 下面，需要通过 `source ~/.xmake/profile` 切换绑定 xmake 的脚本路径，里面设置了 `XMAKE_PROGRAM_DIR` 的 env

推荐一键安装方式，因为支持完整 tab 补全，xmake update 自更新等功能

> pacman 安装

走这个安装，就是直接安装到系统 /usr/bin 下，自更新等功能没法用，因为权限问题，如果你走自动更新，也需要 `source ~/.xmake/profile` 切过去

你从 pacman 切到 源码安装也可以

但是从 源码安装切回 pacman 安装，你得 `unset XMAKE_PROGRAM_DIR` 等 bash 中设置的环境变量，并且删除 `~/.xmake/profile` 文件才行。。否则 lua 脚本还指向你源码安装的 `~/.local/share/xmake` 路径，但是已经被你删了

**Comment by luozhiya** [comment]
@waruqi  :+1: 

原来如此，还会依赖环境变量，`XMAKE_PROGRAM_DIR` 和 `XMAKE_EXE`
```shell
printenv | grep xmake

XMAKE_PROGRAM_DIR=/home/yanchcore/.local/share/xmake
XMAKE_EXE=/home/yanchcore/.local/bin/xmake
```
`unset` 这两个环境变量之后，pacman 安装的 xmake 可以正常运行了
