### ISSUE TITLE
Have a way to signal test failure to CI or other tools

### ISSUE THREAD

**Issue by Arthapz** [xmake-io/xmake#4265]
### Is your feature request related to a problem? Please describe.

I implemented xmake test in my project, and i need to signal to the CI that a test is a failure to make the CI action fail

### Describe the solution you'd like

Maybe we could have xmake test return -1 when a test fail (or other value, i don't mind)

**Comment by waruqi** [comment]
I have supported it. https://github.com/xmake-io/xmake/issues/3381#issuecomment-1752237776
