### ISSUE TITLE
Inactive compiler flags are generated in vsxmake projects

### ISSUE THREAD

**Issue by AidanSun05** [xmake-io/xmake#4268]
### Xmake Version

xmake v2.8.3+master.870bb0fc0

### Operating System Version and Architecture

Windows 11 22H2

### Describe Bug

Compile flags specified with the `tools = { ... }` and `tool::flag` syntax are all included in the `vcxproj` C++ flags, even if they do not correspond to the selected toolchain. With the given configuration, the `vcxproj` file has the following flags:

```xml
<XmakeCXXFlags>-Wno-missing-field-initializers -pthread cl::/Zc:preprocessor</XmakeCXXFlags>
```

The compile flags for both Clang and MSVC, and the `cl::` prefix, are all present, even though some should be excluded depending on the toolchain.

### Expected Behavior

Xmake should recognize the active toolchain before generating vsxmake project files. For example, with MSVC, `<XmakeCXXFlags>` should be:

```xml
<XmakeCXXFlags>/Zc:preprocessor</XmakeCXXFlags>
```

### Project Configuration

```lua
add_rules("mode.debug", "mode.release")

target("vsxmake-test")
    set_kind("binary")
    add_files("src/*.cpp")
    add_cxxflags("-Wno-missing-field-initializers", "-pthread", { tools = { "clang", "clangxx" } })
    add_cxxflags("cl::/Zc:preprocessor", { force = true })
```

### Additional Information and Error Logs

The incorrect flags can interfere with Visual Studio's IntelliSense and make it behave unexpectedly.

Visual C++ log:

```text
<28316> [IntelliSense] CBuildTask::Build() -> stderr output:
...
	cl  ... -Wno-missing-field-initializers -pthread cl::/Zc:preprocessor ...
	cl : Command line error D8021 : invalid numeric argument '/Wno-missing-field-initializers'
...
```

**Comment by waruqi** [comment]
try it again. `xmake update -s dev`
