### ISSUE TITLE
xmake --cross= 工作不正常

### ISSUE THREAD

**Issue by ranwei1025** [xmake-io/xmake#427]
xmake f --confirm=n -p linux -a aarch64 --sdk=/home/bl/aarch64 --cross=aarch64-linux-
cc ar 不对了 cc=/urs/bin/gcc 

更新最新版本之前 下面的命令工作正常
xmake f -p linux -a aarch64 --sdk=/home//bl/aarch64 --cross=aarch64-linux-

**Comment by waruqi** [comment]
我这边测试了下，没啥问题，除非/home/bl/aarch64/bin/aarch64-linux-gcc没有检测到，提供的sdk里面没检测到任何编译器，才会选择使用默认的/usr/bin/gcc，并不是检测不对，是没检测到交叉工具链下的gcc

你贴下，tree /home/bl/aarch64 里面的目录结构， 并且加 -v 执行下 ，给我看下详细的输出信息：

```console
xmake f --confirm=n -p linux -a aarch64 --sdk=/home/bl/aarch64 --cross=aarch64-linux- -v -c
xmake -r -v
```
我看下为什么没检测到。

另外，交叉编译，一般情况下都不需要配置 `-a aarch64`

**Comment by ranwei1025** [comment]
ls -l aarch64 输出如下：
drwxr-xr-x  6 ran ran  4096 May 29  2018 aarch64-buildroot-linux-musl
drwxr-xr-x  2 ran ran 12288 May 29  2018 bin
drwxr-xr-x  2 ran ran  4096 May 29  2018 etc
drwxr-xr-x 13 ran ran  4096 May 29  2018 include
drwxr-xr-x  7 ran ran  4096 May 29  2018 lib
lrwxrwxrwx  1 ran ran     3 May 29  2018 lib64 -> lib
drwxr-xr-x  3 ran ran  4096 May 29  2018 libexec
drwxr-xr-x  2 ran ran  4096 May 29  2018 sbin
drwxr-xr-x 19 ran ran  4096 May 29  2018 share
lrwxrwxrwx  1 ran ran     1 May 29  2018 usr -> .

 ls -l bin | grep  aarch64-linux-输出如下：
lrwxrwxrwx 1 ran ran      38 May 29  2018 aarch64-linux-addr2line -> aarch64-buildroot-linux-musl-addr2line
lrwxrwxrwx 1 ran ran      31 May 29  2018 aarch64-linux-ar -> aarch64-buildroot-linux-musl-ar
lrwxrwxrwx 1 ran ran      31 May 29  2018 aarch64-linux-as -> aarch64-buildroot-linux-musl-as
lrwxrwxrwx 1 ran ran      36 May 29  2018 aarch64-linux-c++filt -> aarch64-buildroot-linux-musl-c++filt
lrwxrwxrwx 1 ran ran      17 May 29  2018 aarch64-linux-cc -> toolchain-wrapper
lrwxrwxrwx 1 ran ran      39 May 29  2018 aarch64-linux-cc.br_real -> aarch64-buildroot-linux-musl-cc.br_real
lrwxrwxrwx 1 ran ran      17 May 29  2018 aarch64-linux-cpp -> toolchain-wrapper
lrwxrwxrwx 1 ran ran      40 May 29  2018 aarch64-linux-cpp.br_real -> aarch64-buildroot-linux-musl-cpp.br_real
lrwxrwxrwx 1 ran ran      36 May 29  2018 aarch64-linux-elfedit -> aarch64-buildroot-linux-musl-elfedit
lrwxrwxrwx 1 ran ran      17 May 29  2018 aarch64-linux-gcc -> toolchain-wrapper
lrwxrwxrwx 1 ran ran      17 May 29  2018 aarch64-linux-gcc-6.4.0 -> toolchain-wrapper
lrwxrwxrwx 1 ran ran      46 May 29  2018 aarch64-linux-gcc-6.4.0.br_real -> aarch64-buildroot-linux-musl-gcc-6.4.0.br_real
lrwxrwxrwx 1 ran ran      35 May 29  2018 aarch64-linux-gcc-ar -> aarch64-buildroot-linux-musl-gcc-ar
lrwxrwxrwx 1 ran ran      35 May 29  2018 aarch64-linux-gcc-nm -> aarch64-buildroot-linux-musl-gcc-nm
lrwxrwxrwx 1 ran ran      39 May 29  2018 aarch64-linux-gcc-ranlib -> aarch64-buildroot-linux-musl-gcc-ranlib
lrwxrwxrwx 1 ran ran      40 May 29  2018 aarch64-linux-gcc.br_real -> aarch64-buildroot-linux-musl-gcc.br_real
lrwxrwxrwx 1 ran ran      33 May 29  2018 aarch64-linux-gcov -> aarch64-buildroot-linux-musl-gcov
lrwxrwxrwx 1 ran ran      38 May 29  2018 aarch64-linux-gcov-dump -> aarch64-buildroot-linux-musl-gcov-dump
lrwxrwxrwx 1 ran ran      38 May 29  2018 aarch64-linux-gcov-tool -> aarch64-buildroot-linux-musl-gcov-tool
lrwxrwxrwx 1 ran ran      34 May 29  2018 aarch64-linux-gprof -> aarch64-buildroot-linux-musl-gprof
lrwxrwxrwx 1 ran ran      31 May 29  2018 aarch64-linux-ld -> aarch64-buildroot-linux-musl-ld
lrwxrwxrwx 1 ran ran      35 May 29  2018 aarch64-linux-ld.bfd -> aarch64-buildroot-linux-musl-ld.bfd
lrwxrwxrwx 1 ran ran      31 May 29  2018 aarch64-linux-nm -> aarch64-buildroot-linux-musl-nm
lrwxrwxrwx 1 ran ran      36 May 29  2018 aarch64-linux-objcopy -> aarch64-buildroot-linux-musl-objcopy
lrwxrwxrwx 1 ran ran      36 May 29  2018 aarch64-linux-objdump -> aarch64-buildroot-linux-musl-objdump
lrwxrwxrwx 1 ran ran      35 May 29  2018 aarch64-linux-ranlib -> aarch64-buildroot-linux-musl-ranlib
lrwxrwxrwx 1 ran ran      36 May 29  2018 aarch64-linux-readelf -> aarch64-buildroot-linux-musl-readelf
lrwxrwxrwx 1 ran ran      33 May 29  2018 aarch64-linux-size -> aarch64-buildroot-linux-musl-size
lrwxrwxrwx 1 ran ran      36 May 29  2018 aarch64-linux-strings -> aarch64-buildroot-linux-musl-strings
lrwxrwxrwx 1 ran ran      34 May 29  2018 aarch64-linux-strip -> aarch64-buildroot-linux-musl-strip

**Comment by ranwei1025** [comment]
checking for the gcc ... /usr/bin/gcc
checking for the c compiler (cc) ... gcc
checking for the c compiler (cc) ... gcc
checking for the c compiler (cc) ... gcc
checking for the c compiler (cc) ... gcc
checking for the ccache ... /usr/bin/ccache
> checking for the c includes(sys/poll.h, sys/socket.h)
> checking for the c funcs(poll)
checking for the posix_poll ... ok
> checking for the c includes(locale.h)
> checking for the c funcs(setlocale)
checking for the libc_setlocale ... ok
> checking for the c includes(sys/socket.h, fcntl.h)
> checking for the c funcs(socket)
checking for the posix_socket ... ok
> checking for the c includes(sys/uio.h)
> checking for the c funcs(pwritev)
checking for the posix_pwritev ... ok
> checking for the c includes(unistd.h)
> checking for the c funcs(getpagesize)
checking for the posix_getpagesize ... ok
> checking for the c includes(signal.h, setjmp.h)
> checking for the c funcs(kill)
checking for the libc_kill ... ok
> checking for the c includes(sys/resource.h)
> checking for the c funcs(getrlimit)
checking for the posix_getrlimit ... ok
> checking for the c includes(unistd.h)
> checking for the c funcs(execvp)
checking for the posix_execvp ... ok
> checking for the c includes(unistd.h)
> checking for the c funcs(fork)
checking for the posix_fork ... ok
> checking for the c includes(ifaddrs.h)
> checking for the c funcs(getifaddrs)
checking for the posix_getifaddrs ... ok
> checking for the c includes(wchar.h, stdlib.h)
> checking for the c funcs(wcsstr)
checking for the libc_wcsstr ... ok
> checking for the c includes(wchar.h, stdlib.h)
> checking for the c funcs(wcsncat)
checking for the libc_wcsncat ... ok
> checking for the c includes(string.h, stdlib.h)
> checking for the c funcs(strcat)
checking for the libc_strcat ... ok
> checking for the c includes(math.h)
> checking for the c funcs(sqrtf)
checking for the libm_sqrtf ... ok
> checking for the c includes(math.h)
> checking for the c funcs(sincos)
checking for the libm_sincos ... no
> checking for the c includes(string.h, stdlib.h)
> checking for the c funcs(memcpy)
checking for the libc_memcpy ... ok
> checking for the c includes(wchar.h, stdlib.h)
> checking for the c funcs(wcsnlen)
checking for the libc_wcsnlen ... ok
> checking for the c includes(stdlib.h)
> checking for the c funcs(random)
checking for the libc_random ... ok
> checking for the c includes(string.h, stdlib.h)
> checking for the c funcs(memmem)
checking for the libc_memmem ... no
> checking for the c includes(math.h)
> checking for the c funcs(acosf)
checking for the libm_acosf ... ok
> checking for the c includes(string.h, stdlib.h)
> checking for the c funcs(strnlen)
checking for the libc_strnlen ... ok
> checking for the c includes(sys/sem.h, sys/ipc.h)
> checking for the c funcs(semtimedop)
checking for the systemv_semtimedop ... no
> checking for the c includes(sys/sendfile.h)
> checking for the c funcs(sendfile)
checking for the posix_sendfile ... ok
> checking for the c includes(wchar.h, stdlib.h)
> checking for the c funcs(wcsncpy)
checking for the libc_wcsncpy ... ok
> checking for the c includes(string.h, stdlib.h)
> checking for the c funcs(strncmp)
checking for the libc_strncmp ... ok
> checking for the c includes(netdb.h)
> checking for the c funcs(gethostbyaddr)
checking for the posix_gethostbyaddr ... ok
> checking for the c includes(sys/uio.h)
> checking for the c funcs(preadv)
checking for the posix_preadv ... ok
> checking for the c includes(string.h, stdlib.h)
> checking for the c funcs(strncasecmp)
checking for the libc_strncasecmp ... ok
> checking for the c includes(string.h, stdlib.h)
> checking for the c funcs(strlcpy)
checking for the libc_strlcpy ... no
> checking for the c includes(wchar.h, stdlib.h)
> checking for the c funcs(wcscpy)
checking for the libc_wcscpy ... ok
> checking for the c includes(sys/wait.h)
> checking for the c funcs(waitpid)
checking for the posix_waitpid ... ok
> checking for the c includes(time.h)
> checking for the c funcs(localtime)
checking for the libc_localtime ... ok
> checking for the c includes(unistd.h)
> checking for the c funcs(sysconf)
checking for the posix_sysconf ... ok
> checking for the c includes(string.h, stdlib.h)
> checking for the c funcs(strncpy)
checking for the libc_strncpy ... ok
> checking for the c includes(math.h)
> checking for the c funcs(tanf)
checking for the libm_tanf ... ok
> checking for the c includes(string.h, stdlib.h)
> checking for the c funcs(strstr)
checking for the libc_strstr ... ok
> checking for the c includes(signal.h, setjmp.h)
> checking for the c funcs(signal)
checking for the libc_signal ... ok
> checking for the c includes(math.h)
> checking for the c funcs(log2f)
checking for the libm_log2f ... ok
> checking for the c includes(pthread.h)
> checking for the c funcs(pthread_mutex_init)
checking for the posix_pthread_mutex_init ... ok
> checking for the c includes(wchar.h, stdlib.h)
> checking for the c funcs(wcstombs)
checking for the libc_wcstombs ... ok
> checking for the c includes(math.h)
> checking for the c funcs(fmodf)
checking for the libm_fmodf ... ok
> checking for the c types(wchar_t)
checking for the wchar ... no
> checking for the c includes(math.h)
> checking for the c funcs(fmod)
checking for the libm_fmod ... ok
> checking for the c includes(math.h)
> checking for the c funcs(exp)
checking for the libm_exp ... ok
> checking for the c includes(pthread.h)
> checking for the c funcs(pthread_create)
checking for the posix_pthread_create ... ok
> checking for the c includes(signal.h, setjmp.h)
> checking for the c funcs(setjmp)
checking for the libc_setjmp ... ok
> checking for the c includes(spawn.h)
> checking for the c funcs(posix_spawnp)
checking for the posix_posix_spawnp ... ok
> checking for the c includes(string.h, stdlib.h)
> checking for the c funcs(strcasestr)
checking for the libc_strcasestr ... no
> checking for the c includes(time.h)
> checking for the c funcs(mktime)
checking for the libc_mktime ... ok
> checking for the c includes(execinfo.h)
> checking for the c funcs(backtrace)
checking for the libc_backtrace ... ok
> checking for the c includes(sched.h)
> checking for the c funcs(sched_yield)
checking for the posix_sched_yield ... ok
> checking for the c includes(math.h)
> checking for the c funcs(acos)
checking for the libm_acos ... ok
> checking for the c includes(math.h)
> checking for the c funcs(sincosf)
checking for the libm_sincosf ... no
> checking for the c includes(math.h)
> checking for the c funcs(asinf)
checking for the libm_asinf ... ok
> checking for the c includes(dlfcn.h)
> checking for the c funcs(dlopen)
checking for the posix_dlopen ... ok
> checking for the c includes(unistd.h)
> checking for the c funcs(fdatasync)
checking for the posix_fdatasync ... ok
> checking for the c includes(regex.h)
> checking for the c funcs(regexec)
checking for the posix_regexec ... ok
> checking for the c includes(unistd.h)
> checking for the c funcs(vfork)
checking for the posix_vfork ... ok
> checking for the c includes(sys/select.h)
> checking for the c funcs(select)
checking for the posix_select ... ok
> checking for the c includes(sys/uio.h)
> checking for the c funcs(writev)
checking for the posix_writev ... ok
> checking for the c includes(wchar.h, stdlib.h)
> checking for the c funcs(wcscat)
checking for the libc_wcscat ... ok
> checking for the c includes(sys/sem.h, sys/ipc.h)
> checking for the c funcs(semget)
checking for the systemv_semget ... ok
> checking for the c includes(sys/stat.h, fcntl.h)
> checking for the c funcs(open)
checking for the posix_open ... ok
> checking for the c includes(pthread.h)
> checking for the c funcs(pthread_key_delete)
checking for the posix_pthread_key_delete ... ok
> checking for the c includes(time.h)
> checking for the c funcs(gmtime)
checking for the libc_gmtime ... ok
> checking for the c includes(pthread.h)
> checking for the c funcs(pthread_key_create)
checking for the posix_pthread_key_create ... ok
> checking for the c includes(math.h)
> checking for the c funcs(tan)
checking for the libm_tan ... ok
> checking for the c includes(wchar.h, stdlib.h)
> checking for the c funcs(wcscasecmp)
checking for the libc_wcscasecmp ... ok
> checking for the c includes(string.h, stdlib.h)
> checking for the c funcs(memmove)
checking for the libc_memmove ... ok
> checking for the c includes(math.h)
> checking for the c funcs(atan)
checking for the libm_atan ... ok
> checking for the c includes(wchar.h, stdlib.h)
> checking for the c funcs(wcscmp)
checking for the libc_wcscmp ... ok
> checking for the c includes(wchar.h, stdlib.h)
> checking for the c funcs(wcslen)
checking for the libc_wcslen ... ok
> checking for the c includes(string.h, stdlib.h)
> checking for the c funcs(strcmp)
checking for the libc_strcmp ... ok
> checking for the c includes(string.h, stdlib.h)
> checking for the c funcs(strcasecmp)
checking for the libc_strcasecmp ... ok
> checking for the c includes(pthread.h)
> checking for the c funcs(pthread_getspecific)
checking for the posix_pthread_getspecific ... ok
> checking for the c includes(math.h)
> checking for the c funcs(pow)
checking for the libm_pow ... ok
> checking for the c includes(string.h, stdlib.h)
> checking for the c funcs(memset)
checking for the libc_memset ... ok
> checking for the c includes(stdio.h)
> checking for the c funcs(fputs)
checking for the libc_fputs ... ok
> checking for the c includes(unistd.h)
> checking for the c funcs(execvpe)
checking for the posix_execvpe ... no
> checking for the c includes(unistd.h)
> checking for the c funcs(pread64)
checking for the posix_pread64 ... no
> checking for the c includes(math.h)
> checking for the c funcs(atanf)
checking for the libm_atanf ... ok
> checking for the c includes(unistd.h)
> checking for the c funcs(getdtablesize)
checking for the posix_getdtablesize ... ok
> checking for the c includes(sys/epoll.h)
> checking for the c funcs(epoll_create)
checking for the posix_epoll_create ... ok
> checking for the c includes(wchar.h, stdlib.h)
> checking for the c funcs(wcsncasecmp)
checking for the libc_wcsncasecmp ... ok
> checking for the c includes(string.h, stdlib.h)
> checking for the c funcs(strcpy)
checking for the libc_strcpy ... ok
> checking for the c includes(wchar.h, stdlib.h)
> checking for the c funcs(wcslcpy)
checking for the libc_wcslcpy ... no
> checking for the c includes(math.h)
> checking for the c funcs(sinf)
checking for the libm_sinf ... ok
> checking for the c includes(sys/time.h)
> checking for the c funcs(gettimeofday)
checking for the libc_gettimeofday ... ok
> checking for the c includes(math.h)
> checking for the c funcs(atan2f)
checking for the libm_atan2f ... ok
> checking for the c includes(sys/epoll.h)
> checking for the c funcs(epoll_wait)
checking for the posix_epoll_wait ... ok
> checking for the c includes(dirent.h)
> checking for the c funcs(opendir)
checking for the posix_opendir ... ok
> checking for the c includes(wchar.h, stdlib.h)
> checking for the c funcs(wcscasestr)
checking for the libc_wcscasestr ... no
> checking for the c includes(netdb.h)
> checking for the c funcs(getnameinfo)
checking for the posix_getnameinfo ... ok
> checking for the c includes(wchar.h, stdlib.h)
> checking for the c funcs(wcsncmp)
checking for the libc_wcsncmp ... ok
> checking for the c includes(sys/uio.h)
> checking for the c funcs(readv)
checking for the posix_readv ... ok
> checking for the c includes(regex.h)
> checking for the c funcs(regcomp)
checking for the posix_regcomp ... ok
> checking for the c includes(math.h)
> checking for the c funcs(log2)
checking for the libm_log2 ... ok
> checking for the c includes(math.h)
> checking for the c funcs(cosf)
checking for the libm_cosf ... ok
> checking for the c includes(string.h, stdlib.h)
> checking for the c funcs(memcmp)
checking for the libc_memcmp ... ok
> checking for the c includes(valgrind/valgrind.h)
> checking for the c funcs(VALGRIND_STACK_REGISTER)
checking for the valgrind_VALGRIND_STACK_REGISTER ... ok
> checking for the c includes(signal.h, setjmp.h)
> checking for the c funcs(sigsetjmp)
checking for the libc_sigsetjmp ... ok
> checking for the c includes(wchar.h, stdlib.h)
> checking for the c funcs(mbstowcs)
checking for the libc_mbstowcs ... ok
> checking for the c includes(math.h)
> checking for the c funcs(cos)
checking for the libm_cos ... ok
> checking for the c includes(unistd.h)
> checking for the c funcs(gethostname)
checking for the posix_gethostname ... ok
> checking for the c includes(string.h, stdlib.h)
> checking for the c funcs(strncat)
checking for the libc_strncat ... ok
> checking for the c includes(pthread.h)
> checking for the c funcs(pthread_setspecific)
checking for the posix_pthread_setspecific ... ok
> checking for the c includes(math.h)
> checking for the c funcs(powf)
checking for the libm_powf ... ok
> checking for the c includes(math.h)
> checking for the c funcs(expf)
checking for the libm_expf ... ok
> checking for the c includes(math.h)
> checking for the c funcs(asin)
checking for the libm_asin ... ok
> checking for the c includes(unistd.h)
> checking for the c funcs(pwrite64)
checking for the posix_pwrite64 ... no
> checking for the c includes(semaphore.h)
> checking for the c funcs(sem_init)
checking for the posix_sem_init ... ok
> checking for the c includes(math.h)
> checking for the c funcs(sin)
checking for the libm_sin ... ok
> checking for the c includes(netdb.h)
> checking for the c funcs(getaddrinfo)
checking for the posix_getaddrinfo ... ok
> checking for the c includes(sys/stat.h, fcntl.h)
> checking for the c funcs(stat64)
checking for the posix_stat64 ... no
> checking for the c includes(netdb.h)
> checking for the c funcs(gethostbyname)
checking for the posix_gethostbyname ... ok
> checking for the c includes(copyfile.h)
> checking for the c funcs(copyfile)
checking for the posix_copyfile ... no
> checking for the c includes(math.h)
> checking for the c funcs(sqrt)
checking for the libm_sqrt ... ok
> checking for the c includes(stdlib.h)
> checking for the c funcs(srandom)
checking for the libc_srandom ... ok
> checking for the c includes(string.h, stdlib.h)
> checking for the c funcs(strlen)
checking for the libc_strlen ... ok
> checking for the c includes(math.h)
> checking for the c funcs(atan2)
checking for the libm_atan2 ... ok
checking for the unzip ... /usr/bin/unzip
checking for the git ... /usr/bin/git
checking for the gzip ... /bin/gzip
checking for the tar ... /bin/tar
checking for the ping ... /bin/ping
pinging for the host(gitlab.com) ... 298 ms
checking for the nmap ... no
pinging for the host(github.com) ... 65535 ms
pinging for the host(gitee.com) ... 59 ms
checking for the xmake::zlib ... 1.2.11
checking for the xmake::sqlite3 ... no
checking for the xmake::openssl ... no
checking for the xmake::mysql ... no
checking for the xmake::mbedtls ... no
checking for the xmake::polarssl ... no
checking for the xmake::pcre2 ... no
checking for the xmake::pcre ... no
checking for the brew ... no
checking for the vcpkg directory ... no
checking for the sqlite3 ... no
checking for the mysql ... no
checking for the mbedtls ... no
checking for the polarssl ... no
checking for the pcre2 ... no
checking for the pcre ... no
checking for the brew ... no
checking for the openssl ... no
checking for the cmake ... /usr/bin/cmake
note: try installing these packages (pass -y to skip confirm)?
in xmake-repo:
  -> sqlite3 3.24.0 (optional)
  -> openssl 1.1.1 (optional)
  -> mysql 5.7.23 (optional)
  -> mbedtls 2.13.0 (optional)
  -> pcre2 10.31 (optional)
     or pcre 8.41 (optional)
please input: y (y/n)
n
configure
{
    deprecated = false
    clean = true
    polarssl = true
    small = false
    object = true
    arch = aarch64
    sqlite3 = true
    info = true
    cc = /usr/bin/gcc
    cross = aarch64-linux-
    plat = linux
    sdk = /home/bl/aarch64
    wchar = false
    float = true
    ndk_stdcxx = true
    host = linux
    charset = true
    xml = true
    exception = false
    openssl = true
    zlib = true
    regex = true
    coroutine = true
    database = true
    buildir = build
    mysql = true
    demo = false
    ccache = true
    pcre2 = true
    pcre = true
    mbedtls = true
    hash = true
    zip = true
    micro = false
    mode = release
    kind = static
}

**Comment by waruqi** [comment]
你有没有设置 CC CXX等环境变量，目前默认优先会从 $CC 环境变量中检测。。

你可以 看下：echo $CC，如果有的话可以清下在xmake f -c 配置试试（记得加-c清下配置缓存）

**Comment by ranwei1025** [comment]
CC变量没有设置 xmake f -c试了的 还是一样

**Comment by waruqi** [comment]
你把工具链发我下，我试试

**Comment by ranwei1025** [comment]
好的 qq传你

**Comment by waruqi** [comment]
测了下你给的toolchain，没啥问题啊，一切ok

```console
[ruki@1d76a4d7f520 test]$ xmake f -p linux --sdk=/mnt/aarch64/ --cross=aarch64-linux- --confirm=n -c -v
checking for the architecture ... none
configure
{
    arch = none
    ccache = true
    clean = true
    ndk_stdcxx = true
    plat = linux
    sdk = /mnt/aarch64/
    kind = static
    buildir = build
    host = linux
    cross = aarch64-linux-
    mode = release
}
[ruki@1d76a4d7f520 test]$ xmake -r -v
checking for the aarch64-linux-g++ ... no
checking for the linker (ld: g++) ... no
checking for the aarch64-linux-gcc ... /mnt/aarch64/bin/aarch64-linux-gcc
checking for the linker (ld) ... aarch64-linux-gcc
checking for the c compiler (cc) ... aarch64-linux-gcc
checking for the ccache ... /usr/sbin/ccache
checking for the /mnt/aarch64/bin/aarch64-linux-gcc ... ok
checking for the flags (-O3) ... ok
[  0%]: ccache compiling.release src/main.c
/usr/sbin/ccache /mnt/aarch64/bin/aarch64-linux-gcc -c -fvisibility=hidden -O3 -I/mnt/aarch64/include -o build/.objs/test/linux/none/release/src/main.c.o src/main.c
checking for the flags (-MMD -MF /dev/null) ... ok
[100%]: linking.release test
/mnt/aarch64/bin/aarch64-linux-gcc -o build/linux/none/release/test build/.objs/test/linux/none/release/src/main.c.o -s -fvisibility=hidden -L/mnt/aarch64/lib
build ok!
```

**Comment by waruqi** [comment]
最近几次提交引入的问题，吧 —sdk=xxx 传入的 path 给处理成小写了，导致你这 sdk dir 内部访问 not found了，现已修复
