### ISSUE TITLE
基于 gcc 的自定义工具链增量构建失效

### ISSUE THREAD

**Issue by MasterBalll** [xmake-io/xmake#4273]
### Xmake 版本

2.8.3

### 操作系统版本和架构

Windows 10 version 22H2

### 描述问题

排查发现这里的改动会造成基于 gcc 的自定义工具链增量构建失效。
https://github.com/xmake-io/xmake/blob/025c5e8415b456bf5f24e37322731615bd5ddea1/xmake/modules/private/tools/gcc/parse_deps.lua#L32
注释掉就能够正常进行增量构建。

### 期待的结果

能够正常进行增量构建。

### 工程配置

大概与工程配置关系不大。

### 附加信息和错误日志

就是执行 xmake 会从头开始构建，没有什么特别现象 。

**Comment by waruqi** [comment]
提供下完整可复现的工程

**Comment by waruqi** [comment]
再试试，应该可以了，`xmake update -s dev`
