### ISSUE TITLE
为 package 支持 link_group 功能

### ISSUE THREAD

**Issue by ivanallen** [xmake-io/xmake#4274]
### Is your feature request related to a problem? Please describe.

目前只在 target 场景支持了 link_group，但是实际使用的时候，package 可能更加需要此功能。

导出的很多底层 c 库，在 link 的时候可能都需要 -Wl,whole-archive 包一下，但是目前只能使用 add_ldflags 处理。

### Describe the solution you'd like

https://github.com/xmake-io/xmake/issues/1452

**Comment by waruqi** [comment]
支持了，https://github.com/xmake-io/xmake/issues/1452#issuecomment-1782438553

不过改动比较大，建议多做一些测试，并且看下是否会 break 已有的东西。。

```
xmake update -s github:xmake-io/xmake#package
```

**Comment by ivanallen** [comment]
> 支持了，[#1452 (comment)](https://github.com/xmake-io/xmake/issues/1452#issuecomment-1782438553)
> 
> 不过改动比较大，建议多做一些测试，并且看下是否会 break 已有的东西。。
> 
> ```
> xmake update -s github:xmake-io/xmake#package
> ```

给力，我先试用一下看看

**Comment by waruqi** [comment]
我 merge 到 dev 了。。`xmake update -s dev`

**Comment by ivanallen** [comment]
目前在我们项目中测试正常。
