### ISSUE TITLE
xmake gcc增量编译失效

### ISSUE THREAD

**Issue by cnjhb** [xmake-io/xmake#4279]
### Xmake 版本

2.8.3

### 操作系统版本和架构

MINGW64_NT-10.0-22621 dsxw-001 3.4.9.x86_64 2023-09-15 12:15 UTC x86_64 Msys

### 描述问题

当我使用gcc编译我的c项目时，增量编译是失效的。clang则不会出现这种问题。

### 期待的结果

gcc的增量编译正常工作

### 工程配置

~

### 附加信息和错误日志

~

**Comment by cnjhb** [comment]
2.8.2版工作正常，刚刚退回去了

**Comment by waruqi** [comment]
再试试，应该可以了，`xmake update -s dev`
