### ISSUE TITLE
Android 无法编译 armeabi-v7a、x86架构

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#428]
可以编译arm64-v8a，但 armeabi-v7a、x86 不行。输出如下：

![图片](https://user-images.githubusercontent.com/1145161/58551401-7b52ff00-8242-11e9-8361-25c2023b2807.png)

**Comment by fasiondog** [comment]
xmake 版本： 2.2.5

**Comment by waruqi** [comment]
x86需要 2.2.6版本才支持，arch名不对，是i386 x86_64 你可以xmake f --help 看下里面对应平台的arch支持列表

**Comment by Zliu404** [comment]
> x86需要 2.2.6版本才支持，arch名不对，是i386 x86_64 你可以xmake f --help 看下里面对应平台的arch支持列表
> 
> 另外x86 xmake仅支持高版本ndk 你可以更新到r16以上的ndk版本

是否考虑修改Android的arch命名，跟Android官方的ABI一致？

**Comment by waruqi** [comment]
不考虑
