### ISSUE TITLE
Issue with conan2 recipes which require compiler.cppstd > 14

### ISSUE THREAD

**Issue by Alex-PLACET** [xmake-io/xmake#4281]
### Xmake Version

2.8.3

### Operating System Version and Architecture

Windows 11 Professionnal Version	22H2

### Describe Bug

When you add a dependency from conan which requires cppstd > 14, like:
``add_requires("conan::exiv2/0.28.0")``
it leads to
[install.txt](https://github.com/xmake-io/xmake/files/12886879/install.txt)

The guilty: https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/manager/conan/v2/install_package.lua#L183

### Expected Behavior

The compiler.cppstd setting provided to conan should be the same as the one configured in xmake.
set_languages("c++11") => compiler.cppstd=11
set_languages("c++14") => compiler.cppstd=14
set_languages("c++20") => compiler.cppstd=20
etc ...

### Project Configuration

```
set_languages("c++20")
add_rules("mode.debug", "mode.release")
add_requires("conan::exiv2/0.28.0")
```

### Additional Information and Error Logs

NA

**Comment by waruqi** [comment]
> The compiler.cppstd setting provided to conan should be the same as the one configured in xmake.

set_languages is only used to set the target, the target needs c ++ 11 does not mean that the source code compilation of the conan package also needs c++11, there is no necessary relationship between them, especially the conan library only provides the c export interfaces.

**Comment by Alex-PLACET** [comment]
I agree there is no direct relationship but it's a convenient way to set the cppstd of the conan library.
About the exiv2 conan recipe: https://github.com/conan-io/conan-center-index/blob/master/recipes/exiv2/all/conanfile.py#L91
Is there another way to set the cppstd of a require ?
BTW, why we use C++14 on Windows and Gnu17 on Linux ? https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/manager/conan/v2/install_package.lua#L231

**Comment by waruqi** [comment]
> I agree there is no direct relationship but it's a convenient way to set the cppstd of the conan library. About the exiv2 conan recipe: https://github.com/conan-io/conan-center-index/blob/master/recipes/exiv2/all/conanfile.py#L91 Is there another way to set the cppstd of a require ? 

no way now, I don't know the details of conan2, but for each package, shouldn't the language standard be specified by each package's own package configuration? At least that's what the xmake-repo package does. xmake doesn't know the details of each conan2 package, it would be very unfriendly if each package asked the user to specify the language.

> BTW, why we use C++14 on Windows and Gnu17 on Linux ? https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/manager/conan/v2/install_package.lua#L231

no reason, only for fix some previous errors. https://github.com/conan-io/conan/issues/12387

maybe it need be improved.

**Comment by Alex-PLACET** [comment]
> it would be very unfriendly if each package asked the user to specify the language.
That's why I propose to use, by default, the version set in the `set_languages`, and maybe have a way to change the conan settings

**Comment by waruqi** [comment]
try pass custom settings? like this

```lua
add_requires("conan::zlib 1.2.11", {alias = "zlib", debug = true,
    configs = {settings = "compiler.cppstd=14"}})
```
