### ISSUE TITLE
GCC编译cpp模块出现BUG

### ISSUE THREAD

**Issue by sxstd001** [xmake-io/xmake#4282]
### Xmake 版本

2.8.3

### 操作系统版本和架构

linux

### 描述问题

https://github.com/sxstd001/xmake_test

编译后错误代码: 139;
错误与import iostream有关,  base.mxx 和main.cpp 都import iostream则编译后, 程序直接退出, 报139错误;  

### 期待的结果

https://github.com/sxstd001/xmake_test

### 工程配置

GCC最新,  XMAKE最新;

### 附加信息和错误日志

进程已结束，退出代码为 139

**Comment by waruqi** [comment]
等下周吧 最近太忙 暂时没空看

**Comment by waruqi** [comment]
工程代码 404 了。
