### ISSUE TITLE
编译android动态库时不会检测符号是否存在

### ISSUE THREAD

**Issue by woodkatu** [xmake-io/xmake#4290]
### Xmake 版本

2.8.3

### 操作系统版本和架构

os: Windows 11 22H2, cpu: x86_64

### 描述问题

如下代码可以编译并生成动态库
```cpp
int __add(int a, int b);

__attribute__ ((visibility ("default"))) int add(int a, int b)
{
    return __add(a, b);
}
```

### 期待的结果

编译失败，并提示 undefined symbol: __add(int, int)

### 工程配置

-- cmd --
```
xmake f -p android -a arm64-v8a -m release
xmake
```

-- xmake.lua --
```
add_rules("mode.debug", "mode.release")

target("foo")
    set_kind("shared")
    add_files("src/foo.cpp")
```

### 附加信息和错误日志

ndk版本 25.2.9519653

**Comment by waruqi** [comment]
这跟 xmake 无关，你得自己配置 ldflags 去控制 linker 的行为，比如 -static 或者其他一些 flags ，你可以翻下 gcc 的手册，xmake 默认不会内置去加各种 flags 的。

**Comment by woodkatu** [comment]
了解了，问题已解决。个人认为默认加上启用符号检测的flag更好，不过不加flag也是合理的。
