### ISSUE TITLE
arm64-linux 下使用 vcpkg::libuv 库时生成的链接参数错误

### ISSUE THREAD

**Issue by bamlan** [xmake-io/xmake#4292]
### Xmake 版本

2.8.3

### 操作系统版本和架构

arm64-linux

### 描述问题

在arm64-linux下链接 libuv.a 生成的参数是：":libuv.a"， 缺少 -l 前缀，参照x64-linux下生成的参数应该是："-l:libuv.a"

### 期待的结果

同样的配置，在 x64-linux 平台下测试是正确的：
[ 59%]: linking.debug ffijs.so
/usr/bin/g++ -o build/linux/x86_64/debug/qjs_ffi/ffijs.so build/.objs/ffijs/linux/x86_64/debug/qjs_ffi/ffijs.c.o -shared -m64 -L/codes/cpp/vcpkg/installed/x64-linux/debug/lib/pkgconfig/../../lib -Lbuild/linux/x86_64/debug -lcrypto -lssl -l:libuv.a -lrt -lffi -lqjsx -lm -ldl -lpthread -fPIC

### 工程配置

add_requires("vcpkg::libuv", {debug=is_mode("debug"), configs = {shared = true}})
add_requires("vcpkg::libffi", {debug=is_mode("debug"), configs = {shared = false}})

target("ffijs")
    set_kind("shared")
    ...
    add_packages("vcpkg::libuv", "vcpkg::libffi")
    ...
target_end()

### 附加信息和错误日志

[ 66%]: linking.release ffijs.so
/usr/bin/g++ -o build/linux/arm64-v8a/release/qjs_ffi/ffijs.so build/.objs/ffijs/linux/arm64-v8a/release/qjs_ffi/ffijs.c.o -shared -L/codes/cpp/vcpkg/installed/arm64-linux/lib/pkgconfig/../../lib -Lbuild/linux/arm64-v8a/release -s -lcrypto -lssl :libuv.a -lrt -lffi -lqjsx -lm -ldl -lpthread -fPIC
/usr/bin/ld: 找不到 :libuv.a: 没有那个文件或目录
collect2: error: ld returned 1 exit status
error: execv(/usr/bin/g++ -o build/linux/arm64-v8a/release/qjs_ffi/ffijs.so build/.objs/ffijs/linux/arm64-v8a/release/qjs_ffi/ffijs.c.o -shared -L/codes/cpp/vcpkg/installed/arm64-linux/lib/pkgconfig/../../lib -Lbuild/linux/arm64-v8a/release -s -lcrypto -lssl :libuv.a -lrt -lffi -lqjsx -lm -ldl -lpthread -fPIC) failed(1)

**Comment by waruqi** [comment]
暂时没有 arm64 linux 的设备，你可以直接加 print 调下这里 https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/manager/vcpkg/find_package.lua

然后提个 pr 过来

**Comment by bamlan** [comment]
我打印了一下vcpkg/find_package.lua的信息，arm64-linux与x64-linux下的返回值是一样的：
````
call _find_package => name: libuv, opt：
{
  configs = {
    debug = false,
    pic = true,
    shared = true,
    default_features = true
  },
  installdir = "/codes/js/quickjs/qjsx/build/.packages/v/vcpkg_libuv/latest/de2b35fd790d49508e02044d43153bea",
  arch = "arm64-v8a",
  version = true,
  cachekey = "fetch_package_system",
  mode = "release",
  buildhash = "de2b35fd790d49508e02044d43153bea",
  plat = "linux",
  external = true,
  system = true,
  require_version = "latest",
  components_extsources = { },
  components = { }
}

_find_package result:
{
  version = "1.46.0",
  links = {
    ":libuv.a",
    "pthread",
    "dl",
    "rt"
  },
  includedirs = {
    "/codes/cpp/vcpkg/installed/arm64-linux/lib/pkgconfig/../../include"
  },
  linkdirs = {
    "/codes/cpp/vcpkg/installed/arm64-linux/lib/pkgconfig/../../lib"
  }
}
````
问题应该不是出在这个文件，生成命令行：
`
/usr/bin/g++ -o build/linux/x86_64/debug/qjs_ffi/ffijs.so build/.objs/ffijs/linux/x86_64/debug/qjs_ffi/ffijs.c.o -shared -m64 -L/codes/cpp/vcpkg/installed/x64-linux/debug/lib/pkgconfig/../../lib -Lbuild/linux/x86_64/debug -lcrypto -lssl -l:libuv.a -lrt -lffi -lqjsx -lm -ldl -lpthread -fPIC
`
这段的lua文件是哪个？我找时间再跟一下。

**Comment by bamlan** [comment]
> > links = {
> > ":libuv.a",
> 
> 这个返回的不对，应该是 `uv` ，不知道为啥 vcpkg.find_package 会提取出来这个，你可以调调

我查看了libuv-static.pc文件，vcpkg的pkgconfig就是这样定义的：
```
prefix=${pcfiledir}/../..
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include

Name: libuv-static
Version: 1.46.0
Description: multi-platform support library with a focus on asynchronous I/O.
URL: http://libuv.org/


Libs: "-L${libdir}" -l:libuv.a -lpthread -ldl -lrt
Cflags: "-I${includedir}"
```

**Comment by bamlan** [comment]
我在 x64-linux 下，删除了 .xmake 目录与 build 目录，重新编译，也出现了 arm64-linux 下同样的问题，链接参数变成了 ":libuv.a"，原来查看到链接参数是 -luv，因为x64-linux下的文件存在比较久了，可能是缓存，具体原因未知。查看了两个系统下的vcpkg的pkgconfig/libuv-static.pc, 内容都一样的，这个库在linux下直接用系统的库，应该是vcpkg的问题。

**Comment by waruqi** [comment]
> Libs: "-L${libdir}" -l:libuv.a -lpthread -ldl -lrt

目前从 vcpkg 找包链接是通过 pkgconfig 返回的结果解析的，它返回 `-l:libuv.a` 那么，find_package 会解析到 `:libuv.a` 作为 links。而带有 `.a`，在 xmake 的 links 处理中，默认会假定为 xxx.a 静态库全名链接，所以不会去加 `-l` ，导致了  ldflags 里面会变成 `:libuv.a`

`-l:libuv.a` 这种格式确实也是合法格式，但这么用的不多，之前解析上 没考虑到这种情况，可以改进 find_package 中对 pkgconfig 的 links 解析提取算法，将 `-l:libuv.a` 解析成 `libuv.a` 作为 links 应该就能解，回头可以改进下这块

**Comment by waruqi** [comment]
可以试下这个 patch https://github.com/xmake-io/xmake/pull/4298

```console
xmake update -s github:xmake-io/xmake#pkgconfig
```

**Comment by waruqi** [comment]
这个 patch 可以了么

**Comment by bamlan** [comment]
> 这个 patch 可以了么

[ 62%]: linking.release ffijs.so
/usr/bin/g++ -o build/linux/arm64-v8a/release/qjs_ffi/ffijs.so build/.objs/ffijs/linux/arm64-v8a/release/qjs_ffi/ffijs.c.o -shared -L/codes/cpp/vcpkg/installed/arm64-linux/lib/pkgconfig/../../lib -Lbuild/linux/arm64-v8a/release -s -lcrypto -lssl libuv.a -lrt -lffi -lqjsx.lto -lm -ldl -lpthread -flto=auto -fPIC
checking for flags (-fPIC) ... ok
/usr/bin/ld: 找不到 libuv.a: 没有那个文件或目录
collect2: error: ld returned 1 exit status

libuv.a 名称对了，但还是会提示找不到文件，我手动使用 -l:libuv.a 是可以正常执行的。

**Comment by bamlan** [comment]
> > 这个 patch 可以了么
> 
> [ 62%]: linking.release ffijs.so /usr/bin/g++ -o build/linux/arm64-v8a/release/qjs_ffi/ffijs.so build/.objs/ffijs/linux/arm64-v8a/release/qjs_ffi/ffijs.c.o -shared -L/codes/cpp/vcpkg/installed/arm64-linux/lib/pkgconfig/../../lib -Lbuild/linux/arm64-v8a/release -s -lcrypto -lssl libuv.a -lrt -lffi -lqjsx.lto -lm -ldl -lpthread -flto=auto -fPIC checking for flags (-fPIC) ... ok /usr/bin/ld: 找不到 libuv.a: 没有那个文件或目录 collect2: error: ld returned 1 exit status
> 
> libuv.a 名称对了，但还是会提示找不到文件，我手动使用 -l:libuv.a 是可以正常执行的。

而且在 -L/codes/cpp/vcpkg/installed/arm64-linux/lib/pkgconfig/../../lib 这个路径下是存在 libuv.a这个文件的，如果是类似 -l:xxx.a 的参数直接引用到 xmake 链接参数上不知道可不可行？

**Comment by waruqi** [comment]
再试下：xmake update -s dev

**Comment by bamlan** [comment]
我在 讨论组 里提了个问题， #4294 
同时引用 vcpkg 的静态库和动态库，不使用完整路径的话，会导致引用库出错，有时间帮忙看看有没有办法解决。
我现在只能在 vcpkg 中把静态库或者动态库删除一个来编译。
