### ISSUE TITLE
链接静态库，能否增加 *.a 的方式增加目录下所有静态库

### ISSUE THREAD

**Issue by jacob1024** [xmake-io/xmake#4296]
### 你在什么场景下需要该功能？

我的xmake 版本：xmake v2.8.3+master.23f5f45fd
linux 下：当我的程序需要链接较多的第三方静态库的时候。

### 描述可能的解决方案

例如：当我想要链接 lib/hisi/hi3559av100/ 目录下的所有静态库，如果使用下面的方式，无法成功。
add_links("lib/hisi/hi3559av100/*.a")
错误：
error: lib/hisi/hi3559av100/*.a: No such file or directory

如果我一个一个的增加静态库，是可以的，如下：
add_links("lib/hisi/hi3559av100/libmpi.a", "lib/hisi/hi3559av100/libaacdec.a", "lib/hisi/hi3559av100/libaacenc.a", "lib/hisi/hi3559av100/libdetail_ap.a", "lib/hisi/hi3559av100/libdnvqe.a", 
             "lib/hisi/hi3559av100/libdpu_match.a", "lib/hisi/hi3559av100/libdpu_rect.a", "lib/hisi/hi3559av100/libdsp.a", "lib/hisi/hi3559av100/libhdmi.a", "lib/hisi/hi3559av100/libhdr_ap.a", 
             "lib/hisi/hi3559av100/lib_hiae.a", "lib/hisi/hi3559av100/libhiavslut.a", "lib/hisi/hi3559av100/lib_hiawb.a", "lib/hisi/hi3559av100/lib_hiawb_natura.a", "lib/hisi/hi3559av100/lib_hicalcflicker.a", 
             "lib/hisi/hi3559av100/libhi_cipher.a", "lib/hisi/hi3559av100/lib_hidehaze.a", "lib/hisi/hi3559av100/lib_hidrc.a", "lib/hisi/hi3559av100/libhifisheyecalibrate.a", 
             "lib/hisi/hi3559av100/lib_hiir_auto.a", "lib/hisi/hi3559av100/lib_hildci.a", "lib/hisi/hi3559av100/libisp.a", "lib/hisi/hi3559av100/libive.a", "lib/hisi/hi3559av100/libmd.a", "lib/hisi/hi3559av100/libmfnr_ap.a", "lib/hisi/hi3559av100/libmpi_photo.a", "lib/hisi/hi3559av100/libnnie.a", 
             "lib/hisi/hi3559av100/libpciv.a", "lib/hisi/hi3559av100/libpos_query.a", "lib/hisi/hi3559av100/libsecurec.a", "lib/hisi/hi3559av100/libsfnr_ap.a", "lib/hisi/hi3559av100/libsns_imx277_slvs.a", 
             "lib/hisi/hi3559av100/libsns_imx290.a", "lib/hisi/hi3559av100/libsns_imx334.a", "lib/hisi/hi3559av100/libsns_imx334_slave.a", "lib/hisi/hi3559av100/libsns_imx477.a", "lib/hisi/hi3559av100/libsns_osun_imx322.a", "lib/hisi/hi3559av100/libsns_sharp8k.a", 
             "lib/hisi/hi3559av100/libsvpruntime.a", "lib/hisi/hi3559av100/libtde.a", "lib/hisi/hi3559av100/libupvqe.a", "lib/hisi/hi3559av100/libVoiceEngine.a", "lib/hisi/hi3559av100/libxml_ap.a")

### 描述你认为的候选方案

是否可以增加这样的方案？
 add_links("lib/hisi/hi3559av100/*.a")
多谢！

**Comment by waruqi** [comment]
不考虑，link 对链接顺序敏感，而不同系统的 文件遍历顺序都是未定义的，如果正好扫到的顺序不符合 库之间的依赖顺序，就跪了

即使你本机没事，其他用户换个系统，说不定就要躺坑。

**Comment by jacob1024** [comment]
好的。那么只能耐心一个一个的写静态库了。也确实遇到过链接顺序反了导致链接失败的问题！
