### ISSUE TITLE
设置了QT的路径，在install时依旧从conda路径中找QT5XXX.dll

### ISSUE THREAD

**Issue by Xiaobin-Jiang** [xmake-io/xmake#4297]
### Xmake 版本

2.8.2

### 操作系统版本和架构

Windows10 19041.746

### 描述问题

已经设置过qt的路径：xmake f   --qt=D:\QT\Qt5.14.2\5.14.2\msvc2017_64
运行的时候是正常的，但是在install的时候是从conda里面找对应的dll，而不是从设置的QT路径中查到对应的dll，导致install失败。
直接运行找到的依赖库是正常的。

error: install failed, Unable to find dependent libraries of C:\ProgramData\anaconda3\Library\bin\Qt5Gui.dll :Cannot open 'C:/ProgramData/anaconda3/Library/bin/Qt5Gui.dll':

### 期待的结果

在已经设置qt路径的情况下，install不会链接到conda环境上，找的依赖库的dll应该和设置的时候一致。

### 工程配置

[QTTest.zip](https://github.com/xmake-io/xmake/files/12927241/QTTest.zip)

### 附加信息和错误日志

(base) PS E:\XXX\QTTest> xmake install -o install -vD
installing QTTest ..
installing QTTest to install ..
> copy build\windows\x64\release\QTTest.exe to install\bin
D:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\windeployqt.exe --force --verbose=2 --release install\bin\QTTest.exe
Qt binaries in C:\ProgramData\anaconda3\Library\bin
readPeExecutable: E:\XXX\QTTest\install\bin\QTTest.exe 64 bit, dependent libraries: 4, debug
Unable to find dependent libraries of C:\ProgramData\anaconda3\Library\bin\Qt5Gui.dll :Cannot open 'C:/ProgramData/anaconda3/Library/bin/Qt5Gui.dll': error: @programdir\core\main.lua:309: @programdir\actions\install\main.lua:129: install failed, @programdir\core\sandbox\modules\os.lua:378: execv(D:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\windeployqt.exe --force --verbose=2 --release install\bin\QTTest.exe) failed(1)
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:921]:
    [@programdir\core\sandbox\modules\os.lua:378]:
    [@programdir\core\sandbox\modules\os.lua:291]: in function 'vrunv'
    [@programdir\rules\qt\install\windows.lua:102]:
    [@programdir\actions\install\install.lua:79]: in function 'script'
    [@programdir\actions\install\install.lua:90]: in function '_install_target'
    [@programdir\actions\install\install.lua:121]:
    [@programdir\actions\install\main.lua:87]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:921: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:309: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>

**Comment by waruqi** [comment]
这是因为目前 windeployqt 执行目前没绑定 qt 环境，所以走的还是外面的 envs，回头可以改下

**Comment by waruqi** [comment]
试下这个 patch https://github.com/xmake-io/xmake/pull/4299

```console
xmake update -s github:xmake-io/xmake#qt
```

**Comment by Xiaobin-Jiang** [comment]
xmake install -o install  -vD
installing QTTest ..
installing QTTest to install ..
> copy build\windows\x64\release\QTTest.exe to install\bin
error: @programdir\core\main.lua:309: @programdir\actions\install\main.lua:129: install failed, @programdir\rules\qt\install\windows.lua:81: attempt to index a nil value (global 'env')
stack traceback:
    [@programdir\rules\qt\install\windows.lua:81]:
    [@programdir\actions\install\install.lua:79]: in function 'script'
    [@programdir\actions\install\install.lua:90]: in function '_install_target'
    [@programdir\actions\install\install.lua:121]:
    [@programdir\actions\install\main.lua:87]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:923: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:309: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>

是需要再额外配置一下env吗？

**Comment by waruqi** [comment]
再试试

```
xmake update -s github:xmake-io/xmake#qt
```

**Comment by Xiaobin-Jiang** [comment]
可以正常install了，谢谢
