### ISSUE TITLE
add_linkgroups 中 whole 和 group顺序调整

### ISSUE THREAD

**Issue by Dozingfiretruck** [xmake-io/xmake#4308]
### Xmake 版本

 v2.8.3+dev.654050350

### 操作系统版本和架构

win10

### 描述问题

当使用add_linkgroups("a","b","c", {whole = true,group = true})时候会得到 -Wl,--start-group -la -lb -lc -Wl,--end-group -Wl,--whole-archive -la -lb -lc -Wl,--no-whole-archive 先group的话whole 会导致连接报错，应该先 whole 后 group 即 -Wl,--whole-archive -la -lb -lc -Wl,--no-whole-archive -Wl,--start-group -la -lb -lc -Wl,--end-group 或者 -Wl,--whole-archive -Wl,--start-group -la -lb -lc -Wl,--end-group -Wl,--no-whole-archive 
推荐：
add_linkgroups("a", {whole = true}) 得到 -Wl,--whole-archive -la -Wl,--no-whole-archive
add_linkgroups("a", {group = true}) 得到 -Wl,--start-group -la -Wl,--end-group
add_linkgroups("a", {whole = true,group = true}) 得到  -Wl,--whole-archive -Wl,--start-group -la -Wl,--end-group -Wl,--no-whole-archive 

### 期待的结果

得到正常连接顺序

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
再试试，`xmake update -s dev`

**Comment by Dozingfiretruck** [comment]
可以了
