### ISSUE TITLE
使用xmake进行编译时，数学库函数找不到

### ISSUE THREAD

**Issue by moji-tao** [xmake-io/xmake#4309]
### Xmake 版本

2.8.3

### 操作系统版本和架构

Win11

### 描述问题

我在一个VS工程中，拿出了部分封装好的数学库代码，是可以正常编译通过的，这部分代码使用xmake编译时，总是提示某些数学函数找不到，不知道是什么原因。 
![image](https://github.com/xmake-io/xmake/assets/61088187/49bb86b2-e427-4822-811d-ac1f6d1699b4)
![image](https://github.com/xmake-io/xmake/assets/61088187/013d9bf9-784a-4610-b3dd-092d4146cdd3)
都是一些很正常的代码

### 期待的结果

正常编译通过

### 工程配置

target("Math")
    set_kind("shared")
    set_pcxxheader("include/pch.h")

    add_files("src/*.cpp")
    add_headerfiles("include/*.h")
    add_includedirs("include/")

### 附加信息和错误日志

checking for Microsoft Visual Studio (x64) version ... 2022
hello: Math
[  0%]: compiling.debug build\.gens\Math\windows\x64\debug\Math\include\pch.h
error: pch.h
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cstdlib(24): error C2039: "fabs": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cstdlib(24): error C3861: “fabs”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cstdlib(28): error C2039: "fabsf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cstdlib(28): error C3861: “fabsf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cstdlib(32): error C2039: "fabsl": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cstdlib(32): error C3861: “fabsl”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(38): error C2039: "acosf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(38): error C3861: “acosf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(42): error C2039: "acoshf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(42): error C3861: “acoshf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(46): error C2039: "asinf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(46): error C3861: “asinf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(50): error C2039: "asinhf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(50): error C3861: “asinhf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(54): error C2039: "atanf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(54): error C3861: “atanf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(58): error C2039: "atanhf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(58): error C3861: “atanhf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(62): error C2039: "atan2f": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(62): error C3861: “atan2f”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(66): error C2039: "cbrtf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(66): error C3861: “cbrtf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(90): error C2039: "cosf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(90): error C3861: “cosf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(94): error C2039: "coshf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(94): error C3861: “coshf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(98): error C2039: "erff": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(98): error C3861: “erff”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(102): error C2039: "erfcf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(102): error C3861: “erfcf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(106): error C2039: "expf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(106): error C3861: “expf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(110): error C2039: "exp2f": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(110): error C3861: “exp2f”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(114): error C2039: "expm1f": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(114): error C3861: “expm1f”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(118): error C2039: "fabsf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(118): error C3861: “fabsf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(122): error C2039: "fdimf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(122): error C3861: “fdimf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(136): error C2039: "fmaf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(136): error C3861: “fmaf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(140): error C2039: "fmaxf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(140): error C3861: “fmaxf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(144): error C2039: "fminf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(144): error C3861: “fminf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(148): error C2039: "fmodf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(148): error C3861: “fmodf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(152): error C2039: "frexpf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(152): error C3861: “frexpf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(156): error C2039: "hypotf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(156): error C3861: “hypotf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(160): error C2039: "ilogbf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(160): error C3861: “ilogbf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(164): error C2039: "ldexpf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(164): error C3861: “ldexpf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(168): error C2039: "lgammaf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(168): error C3861: “lgammaf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(172): error C2039: "llrintf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(172): error C3861: “llrintf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(176): error C2039: "llroundf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(176): error C3861: “llroundf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(180): error C2039: "logf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(180): error C3861: “logf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(184): error C2039: "log10f": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(184): error C3861: “log10f”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(188): error C2039: "log1pf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(188): error C3861: “log1pf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(192): error C2039: "log2f": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(192): error C3861: “log2f”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(196): error C2039: "logbf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(196): error C3861: “logbf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(200): error C2039: "lrintf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(200): error C3861: “lrintf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(204): error C2039: "lroundf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(204): error C3861: “lroundf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(208): error C2039: "modff": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(208): error C3861: “modff”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(212): error C2039: "nearbyintf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(212): error C3861: “nearbyintf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(216): error C2039: "nextafterf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(216): error C3861: “nextafterf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(220): error C2039: "nexttowardf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(220): error C3861: “nexttowardf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(224): error C2039: "powf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(224): error C3861: “powf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(228): error C2039: "remainderf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(228): error C3861: “remainderf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(232): error C2039: "remquof": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(232): error C3861: “remquof”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(236): error C2039: "rintf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(236): error C3861: “rintf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(250): error C2039: "scalblnf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(250): error C3861: “scalblnf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(254): error C2039: "scalbnf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(254): error C3861: “scalbnf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(258): error C2039: "sinf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(258): error C3861: “sinf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(262): error C2039: "sinhf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(262): error C3861: “sinhf”: 找不到标识符
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(266): error C2039: "sqrtf": 不是 "`global namespace'" 的成员
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cmath(266): fatal error C1003: 错误计数超过 100；正在停止编译

**Comment by qycyfjy** [comment]
问题出在Math.h上, windows上文件名不区分大小写, 你add_headerfiles("include/*.h"), 所以会找到你的Math.h而不是bundle的math.h, 然后就完蛋了.

解决方案: 把Math.h改成其他名

**Comment by waruqi** [comment]
提供下完整可复现的工程 ，然后自己也可以尝试先禁用 pch ，或者切下 win sdk version 试试

**Comment by waruqi** [comment]
> 问题出在Math.h上, windows上文件名不区分大小写, 你add_headerfiles("include/*.h"), 所以会找到你的Math.h而不是bundle的math.h, 然后就完蛋了.
> 
> 解决方案: 把Math.h改成其他名

add_headerfiles 仅用于安装，不用于 search paths ，没影响

**Comment by qycyfjy** [comment]
> > 问题出在Math.h上, windows上文件名不区分大小写, 你add_headerfiles("include/*.h"), 所以会找到你的Math.h而不是bundle的math.h, 然后就完蛋了.
> > 解决方案: 把Math.h改成其他名
> 
> add_headerfiles 仅用于安装，不用于 search paths ，没影响

是add_includedirs("include/")
试试这个, 把Math1改成Math, 用不用pch都会错误
[demo.zip](https://github.com/xmake-io/xmake/files/13062788/demo.zip)
[demo_nopch.zip](https://github.com/xmake-io/xmake/files/13062801/demo_nopch.zip)

**Comment by waruqi** [comment]
本地有 math.h 就会优先找到，导致冲突，去了那个 add_includedirs 就行了，这个是工程自己的问题
