### ISSUE TITLE
Target Testing

### ISSUE THREAD

**Issue by Raildex** [xmake-io/xmake#4325]
### Is your feature request related to a problem? Please describe.

I would like to have a (uniform across testing frameworks like gtest) testing facility integrated into xmake.

Currently, I need to duplicate my target (if I do not want to pollute my code with `#ifndef TESTING` or similar ), add the testing framework and keep dependencies in sync between main target and test target

### Describe the solution you'd like

```lua
target(MyPrimaryTarget)
set_kind("binary")
add_files("src/module/myFile.cpp")
add_test_suite("My first test suite", "gtest", "src/module1.cpp", "src/module/myFile.cpp", "src/test/test1.cpp")

on_compile_test_suite_file(function (testsuite, testsuite_name, framework, file) -- allow customizing file compilation when generating a test suite runner
  file:add_defines("TESTING_DEFINED")
end)

on_discover_tests(function (testsuite, testsuite_name, framework, file) -- called for each file in "add_test_suite"
  if(framework == "gtest") then
    testsuite:add_test(gtest_discover_tests(file)) -- specific test discover function for a particular framework
  end
end)


target_end()
```

The resulting xmake.lua should generate the following targets:
`MyPrimaryTarget` which contains NO tests
`My first test suite` which contains Tests described in "module1.cpp","test1.cpp" and "myFile.cpp" with a single `main()` generated automatically and with  `TESTING_DEFINED` defined.

**Comment by waruqi** [comment]
you can try dev version. `xmake update -s dev`

see https://github.com/xmake-io/xmake/issues/3381#issuecomment-1751623805

**Comment by waruqi** [comment]
see https://github.com/xmake-io/xmake/issues/3381#issuecomment-1788328387
