### ISSUE TITLE
Windows 版本检测失效

### ISSUE THREAD

**Issue by OpportunityLiu** [xmake-io/xmake#434]
https://github.com/xmake-io/xmake/blob/eb60a76b7454975d151f2d8b5d9e19b26d561c2d/xmake/core/base/winos.lua#L103-L105

```powershell
PS C:\Users\lzy\Documents\Source\xmake-io\xmake> cmd /c ver

Microsoft Windows [Version 10.0.18362.116]
```

会得到版本 `0.18362.116`

可以考虑改成 `"%[.-([%d%.]+)]"`

**Comment by waruqi** [comment]
> 可以考虑改成 "%[.-([%d%.]+)]"

会匹配到完整 `10.0.18362.116` ，但是目前 内部的 semver 语义版本解析不支持 这种带四个点的格式解析，只能处理 x.x.x 和 x.x.x+buildversion 或者 x.x.x-prerelease 格式

可以改成 "%[.-(%d+%.%d+%.%d+)" ，仅提取前三个点版本号，major.minor.patch
