### ISSUE TITLE
包中只包含 share/pkgconfig/*.pc 时，xmake 自动生成的 lib/pkgconfig/*.pc 会优先生效

### ISSUE THREAD

**Issue by SuperSodaSea** [xmake-io/xmake#4340]
### Xmake 版本

xmake v2.8.3+20231026

### 操作系统版本和架构

Linux 5.15.90.1-microsoft-standard-WSL2

### 描述问题

例如 [wayland-protocols](https://github.com/xmake-io/xmake-repo/tree/dev/packages/w/wayland-protocols) 这个包只会生成 `share/pkgconfig/wayland-protocols.pc`，但 xmake 在安装时会自动为其生成 `lib/pkgconfig/wayland-protocols.pc`，且 xmake 在为 meson 生成 `PKG_CONFIG_PATH` 环境变量时 `lib/pkgconfig` 是在 `share/pkgconfig` 之前的，这就导致 xmake 自动生成的 `lib/pkgconfig/*.pc` 会优先于 `share/pkgconfig/*.pc` 被找到。

### 期待的结果

当检测到 `share/pkgconfig/*.pc` 存在时不自动生成 `lib/pkgconfig/*.pc`。

### 工程配置

**xmake.lua**:
```lua
add_requires("wayland-protocols", { system = false })

target("test-pkgconfig")
    add_packages("wayland-protocols")
    on_load(function (target)
        local pkg = target:pkg("wayland-protocols")
        local envs = {
            PKG_CONFIG_PATH = path.join(pkg:installdir(), "lib", "pkgconfig") .. ":" .. path.join(pkg:installdir(), "share", "pkgconfig"),
        }
        local variables, _ = os.iorunv("pkg-config", {"wayland-protocols", "--print-variables"}, {envs = envs})
        print(variables)
    end)
```

实际输出（首先匹配到了 xmake 生成的 `lib/pkgconfig/wayland-protocols.pc`）:
```
exec_prefix
includedir
libdir
pcfiledir
prefix
```

期望输出（不自动生成 `lib/pkgconfig/wayland-protocols.pc`，匹配到库自带的 `share/pkgconfig/wayland-protocols.pc`）:
```
datarootdir
pcfiledir
pkgdatadir
prefix
```

### 附加信息和错误日志

相关的 xmake 代码：
https://github.com/xmake-io/xmake/blob/461b9331e67fe88062057ecdee53eb4cabc09e3c/xmake/modules/private/action/require/impl/actions/install.lua#L33-L49
https://github.com/xmake-io/xmake/blob/461b9331e67fe88062057ecdee53eb4cabc09e3c/xmake/modules/package/tools/meson.lua#L403-L413

**Comment by waruqi** [comment]
可以来个 pr 过来改进下
