### ISSUE TITLE
支持屏蔽远程包的依赖项

### ISSUE THREAD

**Issue by KanonMemphis** [xmake-io/xmake#4344]
### 你在什么场景下需要该功能？

当我在使用一个远程的cpp包时，它拥有一个依赖项，xmake会自动隐式的添加这个远程依赖包，但是我不想使用远程的依赖项，而是使用本地自定义的替代，需要支持屏蔽指定依赖包

### 描述可能的解决方案

add_require的时候增加参数，忽略依赖

**Comment by waruqi** [comment]
```lua
add_requireconfs("libpng.zlib", {override = true, system = true})
```

改写指定依赖，强制走系统查找
