### ISSUE TITLE
原本可以正常build的项目，更换路径后无法build了

### ISSUE THREAD

**Issue by wjy2249** [xmake-io/xmake#4346]
### Xmake 版本

2.7.8

### 操作系统版本和架构

linux

### 描述问题

updating repositories .. error: Cloning into '/home/dmal_gradstudent_wjy/xstudio/XStudioPlugins/source/PlanarBooleanPlugin/XPlanarBool/.xmake/linux/x86_64/repositories/XStudioPackage'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

warning: You are working in the project directory(/home/dmal_gradstudent_wjy/xstudio/XStudioPlugins) and you can also
force to build in current directory via run `xmake -P .`
dmal_gradstudent_wjy@linuxcadserver:~/xstudio/XStudioPlugins/source/PlanarBooleanPlugin/XPlanarBool$ xmake -P
error: @programdir/core/main.lua:168: assertion failed!
stack traceback:
        [C]: in function 'assert'
        @programdir/core/main.lua:168: in function 'main._init'
        @programdir/core/main.lua:236: in function 'main.entry'
        (...tail calls...)
放到这个目录后报错了

### 期待的结果

![image](https://github.com/xmake-io/xmake/assets/60702050/2014184e-4faf-415d-be88-f5fc502a77cf)
在这个目录下我正常运行

### 工程配置

set_project("XPlanarBool")
add_rules("mode.debug", "mode.releasedbg", "mode.release")
set_allowedmodes("debug", "releasedbg", "release")
set_defaultmode("debug")

option("unitybuild", { description = "Build the engine using unity build", default = false })

-- This will cause crash
-- if not is_mode("release") then
-- 	set_symbols("debug", "hidden")
-- end

if is_mode("debug") then
	set_suffixname("-d")
end

set_languages("c++11")

modules = {
    "IO",
    "BoolAlgo",
    "DataStructure",
    "TopAlgos",
    "GeoAlgos"
}
target("STATIC")
    set_basename("XStudioBrepModeler")
    set_kind("static")
    add_cflags("-fPIC")
    add_cxxflags("-fPIC")

    add_defines("XStudio_BrepModeler_EXPORTS")
    add_defines("OCCT_NO_PLUGINS")

    if has_config("unitybuild") then
        add_rules("c++.unity_build",{batchsize = 12,uniqueid = "XStudio_UNITY_ID"})
    end
    if is_plat("windows") then
        add_syslinks("advapi32","user32" )
    end
    for _, module in ipairs(modules) do
        add_headerfiles("source/" .. module .."/**.h",
                        "source/" .. module .."/**.hxx",
                        "source/" .. module .."/**.hpp",
                        "source/" .. module .."/**.lxx",
                        "source/" .. module .."/**.gxx",
                        "source/" .. module .."/**.pxx",
                        "source/" .. module .."/**.mm")

        add_files("source/" .. module .."/**.c",
                  "source/" .. module .."/**.cxx",
                  "source/" .. module .."/**.cpp")

        add_includedirs(os.dirs(path.join(os.projectdir(), "/source/".. module .."/**")))
    end

    set_targetdir("package/lib")
    on_package(function(target) end)

target("Test")
    set_kind("binary")
    add_deps("STATIC")

    for _, module in ipairs(modules) do
        add_headerfiles("source/" .. module .."/**.h",
                        "source/" .. module .."/**.hxx",
                        "source/" .. module .."/**.hpp",
                        "source/" .. module .."/**.lxx",
                        "source/" .. module .."/**.gxx",
                        "source/" .. module .."/**.pxx",
                        "source/" .. module .."/**.mm")

        add_includedirs(os.dirs(path.join(os.projectdir(), "/source/".. module .."/**")))
    end

    add_includedirs("TestTools/**.h")
    add_cxxflags("-pg")
    add_files("main.cpp")

### 附加信息和错误日志

stack traceback:
        [C]: in function 'assert'
        @programdir/core/main.lua:168: in function 'main._init'
        @programdir/core/main.lua:236: in function 'main.entry'
        (...tail calls...)

**Comment by waruqi** [comment]
> warning: You are working in the project directory(/home/dmal_gradstudent_wjy/xstudio/XStudioPlugins) and you can also
force to build in current directory via run xmake -P .

你父目录 /home/dmal_gradstudent_wjy/xstudio/XStudioPlugins 有 xmake.lua ，或作为工程主目录，不要将独立的工程放到里面的子目录。。

**Comment by wjy2249** [comment]
> > warning: You are working in the project directory(/home/dmal_gradstudent_wjy/xstudio/XStudioPlugins) and you can also
> > force to build in current directory via run xmake -P .
> 
> 你父目录 /home/dmal_gradstudent_wjy/xstudio/XStudioPlugins 有 xmake.lua ，或作为工程主目录，不要将独立的工程放到里面的子目录。。
> 
> 要么你把父目录的 xmake.lua 删了，要么子工程移到外面，要么父工程 includes 子工程

请问下父工程要怎么includes子工程qaq

**Comment by wjy2249** [comment]
> > warning: You are working in the project directory(/home/dmal_gradstudent_wjy/xstudio/XStudioPlugins) and you can also
> > force to build in current directory via run xmake -P .
> 
> 你父目录 /home/dmal_gradstudent_wjy/xstudio/XStudioPlugins 有 xmake.lua ，或作为工程主目录，不要将独立的工程放到里面的子目录。。
> 
> 要么你把父目录的 xmake.lua 删了，要么子工程移到外面，要么父工程 includes 子工程

我父工程includes了子工程还是不行，这是为什么qaq（我是A includes了B,B inlcudes了C，C includes了D，B在A的子目录下，C在B的子目录下，D在C的子目录下）

**Comment by waruqi** [comment]
> > > warning: You are working in the project directory(/home/dmal_gradstudent_wjy/xstudio/XStudioPlugins) and you can also
> > > force to build in current directory via run xmake -P .
> > 
> > 
> > 你父目录 /home/dmal_gradstudent_wjy/xstudio/XStudioPlugins 有 xmake.lua ，或作为工程主目录，不要将独立的工程放到里面的子目录。。
> > 要么你把父目录的 xmake.lua 删了，要么子工程移到外面，要么父工程 includes 子工程
> 
> 我父工程includes了子工程还是不行，这是为什么qaq（我是A includes了B,B inlcudes了C，C includes了D，B在A的子目录下，C在B的子目录下，D在C的子目录下）

改了东西 就重新贴 logs， xmake.lua ，光说不行 我哪知道咋回事

**Comment by wjy2249** [comment]
> > > > warning: You are working in the project directory(/home/dmal_gradstudent_wjy/xstudio/XStudioPlugins) and you can also
> > > > force to build in current directory via run xmake -P .
> > > 
> > > 
> > > 你父目录 /home/dmal_gradstudent_wjy/xstudio/XStudioPlugins 有 xmake.lua ，或作为工程主目录，不要将独立的工程放到里面的子目录。。
> > > 要么你把父目录的 xmake.lua 删了，要么子工程移到外面，要么父工程 includes 子工程
> > 
> > 
> > 我父工程includes了子工程还是不行，这是为什么qaq（我是A includes了B,B inlcudes了C，C includes了D，B在A的子目录下，C在B的子目录下，D在C的子目录下）
> 
> 改了东西 就重新贴 logs， xmake.lua ，光说不行 我哪知道咋回事

sry我还是个新手，刚才改了下发现可以了，谢谢答主~

**Comment by waruqi** [comment]
可以了，那我关了。
