### ISSUE TITLE
当 package 是压缩包时，add_patches 未生效

### ISSUE THREAD

**Issue by ivanallen** [xmake-io/xmake#4356]
### Xmake 版本

xmake v2.8.2+dev.2e99338

### 操作系统版本和架构

Linux 10-16-43-32 5.14.0-70.13.1.el9_0.x86_64 #1 SMP PREEMPT Wed May 25 21:01:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

ci 系统上，突然出现 grpc 包（看起来只有源码压缩包会有这个问题）拉下来时编译报错：
![image](https://github.com/xmake-io/xmake/assets/12481610/331c8651-fb58-423c-b071-3c1a2844ef9d)

经过定位发现，是 add_patches 失效，导致 grpc cmake 去下载外网工具。

https://github.com/xmake-io/xmake-repo/blob/dev/packages/g/grpc/xmake.lua#L10C4-L10C4

检查了一下，这个 patch 确实是没有成功，理论上这个 function 被 patch 后会直接 return 出去，不执行任何语句。

![image](https://github.com/xmake-io/xmake/assets/12481610/4e001e77-f5ae-4ddd-8809-8110fe80d425)

### 期待的结果

对源码包可以正常 patch

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
那就调下，提个 pr 过来

**Comment by ivanallen** [comment]
问题定位出来了，但是挺不好修的。
原因：
因为下载的压缩包解压后，没有 .git，它就会默认认为当前是在 xmake-repo 这个 repo 中，导致会 skip 这个 patch.
变通的方案：
- 制作压缩包的时候，把 .git 文件也一起压缩进去，这样没问题
- 不使用 git apply，使用 patch 命令

**Comment by ivanallen** [comment]
![image](https://github.com/xmake-io/xmake/assets/12481610/ecd3c9f3-b9ef-41a0-bd59-178881df0663)
尝试添加各种参数都不太行
只要移除到非 git repo 目录下，就能正常 work。。。

**Comment by ivanallen** [comment]
> > 问题定位出来了，但是挺不好修的。 原因： 因为下载的压缩包解压后，没有 .git，它就会默认认为当前是在 xmake-repo 这个 repo 中，导致会 skip 这个 patch. 变通的方案：
> > 
> > * 制作压缩包的时候，把 .git 文件也一起压缩进去，这样没问题
> > * 不使用 git apply，使用 patch 命令
> 
> ? 现在仓库很多 tar.gz 包的 patch ，都是走的 git apply ，也没 .git ，也从没见有啥问题，git apply 都用了几年了，也没见有啥问题
> 
> > 只要移除到非 git repo 目录下，就能正常 work。。。
> 
> 刚说要加 .git ，这里又说非 .git 的才 work ? 看不懂

加 .git ，是指加这个源码的对应的那个 .git 索引树。如果没有.git 索引树，那把源码解压出来 ，是不能放在其它的 git repo 下的。

比如 xmake-repo ，这是一个 git-repo，grpc 解压出来放在这个目录下，使用 git apply 会失败。如果我把 grpc 解压出来 的目录放在 xmake-repo 之外，非 git repo 环境，则可以 git apply 成功。

如果 grpc 解压出来，已经自带了 .git 索引树，放在 xmake-repo 下也是没关系的，可以正确 patch

**Comment by ivanallen** [comment]
和我的用法也有点关系，使用 xmake 默认的路径应该是没问题的。我修改了 XMAKE_GLOBALDIR，放在了自己项目路径下，导致受了影响。

**Comment by waruqi** [comment]
那就加 --git-dir https://github.com/xmake-io/xmake/pull/4358#issuecomment-1792372392

我这边测过可以

**Comment by waruqi** [comment]
> 和我的用法也有点关系，使用 xmake 默认的路径应该是没问题的。我修改了 XMAKE_GLOBALDIR，放在了自己项目路径下，导致受了影响。

你应该仅仅配置 XMAKE_PKG_INSTALLDIR  https://xmake.io/#/zh-cn/guide/configuration?id=xmake_pkg_installdir 

XMAKE_GLOBALDIR 会把缓存目录也配置到你的项目中去，这就会导致你这个问题，即使通过 git-dir 改了 git apply 过了，也是有问题的，不仅仅是之前遇到的 break 问题，如果是从 git url 下载的包，还会去做 git reset ，对非 git url 的包，缓存下载，你还得加到 gitignore 。。

所以这个问题，没必要去修 git apply ，正常使用，不可能会存在这个问题，缓存路径不要设置到当前工程目录下就行了

**Comment by ivanallen** [comment]
> > 和我的用法也有点关系，使用 xmake 默认的路径应该是没问题的。我修改了 XMAKE_GLOBALDIR，放在了自己项目路径下，导致受了影响。
> 
> 你应该仅仅配置 XMAKE_PKG_INSTALLDIR https://xmake.io/#/zh-cn/guide/configuration?id=xmake_pkg_installdir
> 
> XMAKE_GLOBALDIR 会把缓存目录也配置到你的项目中去，这就会导致你这个问题，即使通过 git-dir 改了 git apply 过了，也是有问题的，不仅仅是之前遇到的 break 问题，如果是从 git url 下载的包，还会去做 git reset ，对非 git url 的包，缓存下载，你还得加到 gitignore 。。
> 
> 所以这个问题，没必要去修 git apply ，正常使用，不可能会存在这个问题，缓存路径不要设置到当前工程目录下就行了
> 
> 另外，缓存目录 [XMAKE_PKG_CACHEDIR](https://xmake.io/#/zh-cn/guide/configuration?id=xmake_pkg_cachedir) 也是可以单独修改的，改到一个 临时目录，其他非 git 目录下，就行了，如果你非要改它

感谢解答，我们目前主要在 docker 中使用 xmake，然后跑在 cicd 机器上，屏蔽一些环境差异。之所以配置 XMAKE_GLOBALDIR 在项目路径下，是因为怕 cicd 上的不同容器互相造成影响。。。
我得想想怎么改造一下比较合适。
