### ISSUE TITLE
Support explict git source for xmake update

### ISSUE THREAD

**Issue by OpportunityLiu** [xmake-io/xmake#437]
Support `xmake update gitrepo#branch` to install form give repo and branch.

eg. `xmake update https://github.com/OpportunityLiu/xmake#cu-deps`

It is very helpful for contibuters to test their PRs before merge

**Comment by OpportunityLiu** [comment]
不过就目前win上的机制是没法实现的。。。

**Comment by waruqi** [comment]
嗯，现在主要是win上处理起来 有点问题，需要花时间去支持

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/issues/264

**Comment by OpportunityLiu** [comment]
需要支持到哪个版本，感觉xp要搞就很麻烦，win7还行，反正可以装PowerShell5

**Comment by waruqi** [comment]
xp也要支持的。我现在主要就是在xp下跑 偶尔测测win10/win7

**Comment by OpportunityLiu** [comment]
那就只能vbs了

**Comment by waruqi** [comment]
对于uac的命令运行，里面有个脚本就是vbs处理的，可以参考下：

https://github.com/xmake-io/xmake/blob/3633407fdd3f55288c602238957f9e9fa16fc063/xmake/actions/update/main.lua#L94-L98

**Comment by OpportunityLiu** [comment]
这脚本有啥坑吗？为啥sudo.has()还是要返回false而不是直接用这个实现？

**Comment by waruqi** [comment]
sudo.lua 那个模块，当初支持了 linux/macos ，对于win 还没有封装进去，虽然后来加了个 sudo.vbs，但还是半成品，封装仅sudo.lua ，也许还需要做很多细节处理。

比如环境变量的传递等，当前执行权限的检测等，想要完美模拟 linux 下的sudo 还有点距离。
