### ISSUE TITLE
protobuf-cpp: Cannot compile when there are alot of proto files in separate directories

### ISSUE THREAD

**Issue by Chi-EEE** [xmake-io/xmake#4372]
### Xmake Version

2.8.5

### Operating System Version and Architecture

Windows 10 22H2

### Describe Bug

Xmake only compiles 3/5 directories containing proto files using protobuf-cpp.

### Expected Behavior

All the proto files in the directories should get compiled

### Project Configuration

The repository which I'm working on is https://github.com/cartographer-project/cartographer
```lua
add_rules("mode.debug", "mode.release")

add_requires("boost", {configs = {iostreams = true}})
add_requires("ceres-solver", {configs = {suitesparse = true}})
add_requires("abseil", "cairo", "eigen", "glog", "lua", "protobuf-cpp")

target("cartographer")
    set_kind("$(kind)")
    set_languages("cxx17")

    add_packages(
        "abseil",
        "boost", 
        "ceres-solver", 
        "cairo", 
        "eigen",
        "glog",
        "lua"
    )
    
    add_packages("protobuf-cpp", {public = true})
    add_rules("protobuf.cpp")

    add_files("cartographer/**.proto", {proto_rootdir = "cartographer", proto_autogendir = path.join(os.projectdir(), "build", "proto") , proto_public = true})
    add_headerfiles("$(buildir)/proto/**.h")
    add_includedirs("$(buildir)/proto")

    remove_files("cartographer/**_service.proto")

    add_headerfiles("(cartographer/**.h)")
    add_files("cartographer/**.cc")

    remove_files("cartographer/io/serialization_format_migration.cc")
    remove_headerfiles("cartographer/io/serialization_format_migration.h")

    remove_headerfiles("**/fake_*.h", "**/*test_helpers*.h", "**/mock*.h")
    remove_files("**/fake_*.cc", "**/*test_helpers*.cc", "**/mock*.cc", "**/*_main.cc", "**/*_test.cc")

    -- BUILD_GRPC is not enabled
    remove_headerfiles("cartographer/cloud/**.h")
    remove_files("cartographer/cloud/**.cc")
    remove_files("cartographer/cloud/proto/**.proto")

    add_includedirs(".")

```

### Additional Information and Error Logs

Error Log: https://pastebin.com/6DWxE6n7

**Comment by Chi-EEE** [comment]
When I debugged Xmake, I saw that 10/44 proto files managed to run the function inside of this call: https://github.com/xmake-io/xmake/blob/master/xmake/rules/protobuf/proto.lua#L195

**Comment by waruqi** [comment]
xmake tries to resolve the dependencies between proto files and then generates a dependency graph, compiling as much as possible in parallel.

However, xmake currently parses the dependencies from the source code itself, and if it does not generate them correctly, the parallel compilation may fail.

https://github.com/xmake-io/xmake/blob/8eefa03ee2cadf0d89126e18173c1e179bebc3c5/xmake/rules/protobuf/proto.lua#L186

So you can try debugging this implementation of dependency resolution. Or try serial compilation. `xmake -j1`

**Comment by Chi-EEE** [comment]
Fixed the issue by doing the following:

- Setting the proto_rootdir to the directory where the proto files were: `cartographer`
- Doing: https://github.com/xmake-io/xmake/issues/3678
- Set proto_public to true
- set add_includedirs to the proto_autogendir
- And changed the import inside of the proto files. Example: `import "cartographer/..."` to `import "..."`

**Comment by Chi-EEE** [comment]
I did the above changes and it was only fixed on linux
