### ISSUE TITLE
生成CmakeLists.txt的时候，加了g++不支持的标志，默认链接windows的库

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#4375]
### Xmake 版本

2.8.3

### 操作系统版本和架构

Windows 11

### 描述问题

原有makefile 如下
```
all: demo1 

demo1:demo1.cpp
	g++ -g -o demo1 demo1.cpp ../_public.cpp 

clean:
	rm -f demo1
```
执行命令 `xmake project -k cmake`
生成的CmakeLists.txt中demo1部分如下
```
# target
add_executable(demo1 "")
set_target_properties(demo1 PROPERTIES OUTPUT_NAME "demo1")
set_target_properties(demo1 PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/build/windows/x64/release")
if(MSVC)
    target_compile_options(demo1 PRIVATE /EHsc)
else()
    target_compile_options(demo1 PRIVATE -fcxx-exceptions)
endif()
if(MSVC)
    set_property(TARGET demo1 PROPERTY
        MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
endif()
target_link_libraries(demo1 PRIVATE
    kernel32
    ntdll
)
target_sources(demo1 PRIVATE
    demo1.cpp
)
```
其中`target_compile_options(demo1 PRIVATE -fcxx-exceptions)`
这个 -fcxx-exceptions 是clang才有的吧。用g++编译的时候就报错了
```
FAILED: CMakeFiles/demo1.dir/demo1.cpp.o 
/usr/bin/x86_64-pc-linux-gnu-g++   -g -fcxx-exceptions -MD -MT CMakeFiles/demo1.dir/demo1.cpp.o -MF CMakeFiles/demo1.dir/demo1.cpp.o.d -o CMakeFiles/demo1.dir/demo1.cpp.o -c /home/cat/.edx/c/sources/wcz_c++/project_20230727/project/public/demo/demo1.cpp
x86_64-pc-linux-gnu-g++: error: unrecognized command-line option '-fcxx-exceptions'; did you mean '-fno-exceptions'?
ninja: build stopped: subcommand failed.
```
这里不是MSVC就都加了这个标志，导致出错，是不是还要判断下是否是g++工具链

另外还有下面没有判断，就链接了kernel32 和 ntdll，也需要加一下工具链判断

### 期待的结果

能够正确处理g++和clang++的情况

### 工程配置

rt

### 附加信息和错误日志

rt

**Comment by waruqi** [comment]
暂时还没时间看，你可以直接来个 pr 改进下，https://github.com/xmake-io/xmake/blob/f205de61c97bad8457838272b33c37d876063851/xmake/plugins/project/cmake/cmakelists.lua#L621

加个 gcc/clang 的判断，调整下 flags 就行了

**Comment by heheda123123** [comment]
issue开头就提到了哈，可能大佬没注意看。
有一些小项目只提供了makefile，我一直都是用xmake把他转为CmakeLists.txt
然后偶然在知乎看到这个问题，写了这个回答 https://www.zhihu.com/question/36294947/answer/3282509835

一般转换后需要简单调整下，一个是异常的参数，一个就是额外链接了几个库。

**Comment by waruqi** [comment]
改了下，再试试 xmake update -s dev

**Comment by heheda123123** [comment]
问题解决了。
不过貌似我理解有点错误，我以为xmake是去解析了makefile的内容。但是好像只是扫描了文件生成xmake.lua，再生成CMakeLists.txt

**Comment by waruqi** [comment]
> 问题解决了。 不过貌似我理解有点错误，我以为xmake是去解析了makefile的内容。 但是好像只是扫描了当前目录下的文件生成xmake.lua，再生成CMakeLists.txt

不会解析，其实根本没用到那个 makefile。。没有 xmake.lua ，那么 xmake 会自动扫描源码 自动生成一个 xmake.lua   但这是不可靠的，仅仅用于一些非常简单的文件结构

https://tboox.org/cn/2017/01/07/build-without-makefile/
