### ISSUE TITLE
"智能化构建第三方库"没有识别到libhv

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#4379]
### Xmake 版本

2.8.5

### 操作系统版本和架构

windows 11

### 描述问题

之前看大佬的文章有提到 https://tboox.org/cn/2022/10/09/xmake-update-v2.7.2/
更加智能化构建第三方库
如果监测到会有如下的提示
```
ruki-2:libjpeg-turbo-2.1.4 ruki$ xmake
note: libjpeg-turbo 2.1.4 in xmake-repo found, try building it or you can run `xmake f --trybuild=` to set buildsystem (pass -y or --confirm=y/n/d to skip confirm)?
please input: y (y/n)
```
但是我拿libhv的源码试了下，只是提示识别到cmakelists和makefile
![image](https://github.com/xmake-io/xmake/assets/97490782/63912212-8bfe-4ca6-aaa0-8e7b272ebab3)
源码包是直接从 https://github.com/xmake-io/xmake-repo/blob/dev/packages/l/libhv/xmake.lua 这里得到的
`https://github.com/ithewei/libhv/archive/v1.3.2.zip`
不知道其他源码是否有这个问题

### 期待的结果

应该也提示识别到libhv在xmake-repo里面

### 工程配置

rt

### 附加信息和错误日志

rt

**Comment by waruqi** [comment]
```console
ruki-2:libhv-1.3.2 ruki$ xmake
note: libhv 1.3.2 in xmake-repo found, try building it or you can run `xmake f --trybuild=` to set buildsystem (pass -y or --confirm=y/n/d to skip confirm)?
please input: y (y/n)
```

我这里可以，你可以看下仓库是否没更新，还没收录 libhv 最新版本。。`xrepo update-repo`

**Comment by heheda123123** [comment]
噢，可以了。因为我先xmake update的，下意识以为仓库也更新到最新了
