### ISSUE TITLE
Android 平台下 add_includedirs 不生效

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#439]
编译 android 平台时，add_includedirs 添加主目录之外的目录不生效，总是报找不到文件。编译windows平台又没问题。
比如：
+3rdparty
     |-dlib
+mycode
    add_includedirs("../3rdparty")

**Comment by waruqi** [comment]
你贴下加-v的详细编译输出，以及错误信息

**Comment by fasiondog** [comment]
明天加吧，公司里用的

**Comment by waruqi** [comment]
嗯 还有你对应的xmake.lua 也贴我看下

**Comment by fasiondog** [comment]
公司用的，就补贴了。大致是因为看见 add_includedirs 有 public 参数，于是把 3rdparty 下的第三方库里加了 add_includedirs("dlib", {public=true}) , 在 主项目里 add_deps ，但因为不在一个目录层次，add_includedirs 里应该是相对目录可能加不进来。

**Comment by waruqi** [comment]
这个你调整下相对目录，或者设置为绝对路径也是可以的，`add_includedirs("$(projectdir)/xxx")` 相对于项目跟目录就行了。。

当然你这种处理方式也是可以的。。
