### ISSUE TITLE
package:find_package can not find libiconv.tbd in MacOSX sdk

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#4399]
### Xmake 版本

2.8.5

### 操作系统版本和架构

macOS

### 描述问题

https://github.com/xmake-io/xmake-repo/pull/2822

这里有/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/lib/libiconv.tbd文件，但package:find_package("system::iconv", {includes="iconv.h"})找不到

### 期待的结果

可以正常找到libiconv.tbd

### 工程配置

https://github.com/xmake-io/xmake-repo/blob/dev/packages/l/libiconv/xmake.lua

### 附加信息和错误日志

https://github.com/xmake-io/xmake-repo/actions/runs/6846983394/job/18614444481?pr=2822

**Comment by waruqi** [comment]
我记得 .tbd 是有支持的，你可以调下这里 https://github.com/xmake-io/xmake/blob/8a593a2d3ad47e57064516643fd8cb8442cbb52d/xmake/modules/package/manager/system/find_package.lua#L155

**Comment by xq114** [comment]
我没有macos的环境

**Comment by xq114** [comment]
出现了奇怪的事情：
```
xmake l ./scripts/test.lua -vD --fetch libiconv
```
可以正常找到libiconv.tbd；但是
```
add_deps("libiconv", {system = true})
```
显示找不到libiconv。是不是fetch的时候没有传递参数？或者是对system=true的包也限制了版本？如果是，怎么去掉这个版本的限制？

**Comment by xq114** [comment]
![image](https://github.com/xmake-io/xmake/assets/42310255/a33a92af-bbcf-4385-84d3-ad7bc08fedc2)
![image](https://github.com/xmake-io/xmake/assets/42310255/3b7601e0-141f-4245-92c7-bf3101da5123)

**Comment by waruqi** [comment]
应该修复了，再试试

**Comment by xq114** [comment]
可以了
