### ISSUE TITLE
Unity编译导致连接时出现undefined reference错误

### ISSUE THREAD

**Issue by Domain** [xmake-io/xmake#4402]
### Xmake 版本

2.8.5

### 操作系统版本和架构

Windows 11

### 描述问题

我有一个静态库，里面部分代码依赖于libcurl，然后一个exe工程用到了这个库，但是没有用到libcurl相关的功能，正常编译一切正常，但是我把这个静态库加上Unity编译：
add_rules("c++.unity_build")
在编译这个exe时，就会提示链接找不到libcurl，把这句删除就又正常了。

### 期待的结果

使不使用Unity编译都应该得到相同的结果

### 工程配置

没什么特殊的，就是有没有add_rules("c++.unity_build")这句的区别

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
给个可复现的工程 example

**Comment by Domain** [comment]
[unity_bug.zip](https://github.com/xmake-io/xmake/files/13500276/unity_bug.zip)
根目录的xmake.lua，打开add_rules("c++.unity_build")链接就提示找不到lua_newstate，注释掉就没问题

**Comment by waruqi** [comment]
> [unity_bug.zip](https://github.com/xmake-io/xmake/files/13500276/unity_bug.zip) 根目录的xmake.lua，打开add_rules("c++.unity_build")链接就提示找不到lua_newstate，注释掉就没问题

首先是 lua_newstate 符号原本就没被定义，也没 lua link ，通常肯定会 undefined 的。

这应该跟 msvc 的链接优化有关，unitybuild 仅仅只是把 bar.cpp 和 foo.cpp 合并到一个 cpp 编译，并没有其他处理。

正常编译，分成两个独立 .obj 链接， 其中一个 bar.obj 里面引用了这个 undefined 的 lua_newstate，链接器看到 bar.obj 完全没用到，就整个优化掉了。。

而作为 unitybuild 编译，合并一个独立的 obj 包含了 undefined lua_newstate, 而 app 也引用了里面的 add() ，似乎链接器没有无视那个 lua_newstate，直接报错了。

也许有 link flags 可以让 msvc link 更好的处理它，你可以找找。但这个不是 xmake 的问题，是 unity build 本身的机制影响了链接行为，除非你禁用 unity build ，或者配置一些优化 flags 到 linker 去更好的处理它。

另外，macosx 上 Clang 编译，开启 unitybuild 也能通过，这个还是不同链接器的行为差异导致

**Comment by Domain** [comment]
[unresolved external symbol referenced in function removed by /OPT:REF](https://developercommunity.visualstudio.com/t/unresolved-external-symbol-referenced-in-function/1016851)
根据微软的回答，这个应该无解

**Comment by Domain** [comment]
发现还是有办法的：[/FORCE:UNRESOLVED](https://learn.microsoft.com/en-us/cpp/build/reference/force-force-file-output?view=msvc-170)

**Comment by waruqi** [comment]
那你自己加上就行了
