### ISSUE TITLE
希望 target:add_linkgroups能得到继承

### ISSUE THREAD

**Issue by Dozingfiretruck** [xmake-io/xmake#4403]
### 你在什么场景下需要该功能？

希望 target:add_linkgroups能得到继承，比如
target("a")
set_kind("static")
add_linkdirs("abc",{public = true})
add_linkgroups("abc", {whole = true,public = true})
target_end()
target("b")
set_kind("binary")
add_deps("a")
target_end()
当生成binary时候自动连接abc静态库

### 描述可能的解决方案

target:add_linkgroups能得到继承

**Comment by Dozingfiretruck** [comment]
@waruqi

**Comment by waruqi** [comment]
再试试 dev

**Comment by Dozingfiretruck** [comment]
可以了，感谢大佬
