### ISSUE TITLE
package.tools.meson generates problematic ldflags

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#4407]
### Xmake 版本

2.8.5

### 操作系统版本和架构

Windows 11

### 描述问题

Windows上package.tools.meson在生成ldflags时生成的是 `-libpath:xxx/lib` 的格式；但由于meson会自动将 `-l` 开头的ldflags识别成链接库，导致上述flag会被替换成 `ibpath:xxx/lib.lib` ，导致链接出错。

### 期待的结果

修改方式一：在package.tools.meson中添加ldflags时将`-libpath`替换成`/libpath`
https://github.com/xmake-io/xmake/blob/v2.8.5/xmake/modules/package/tools/meson.lua#L45-L48

修改方式二：在windows上生成ldflags时就直接生成`/libpath`，不用`-libpath`了

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
改了，再试试

这个应该算是 meson 的问题，这边只能在 tools.meson 里面做兼容，但建议到 meson 那个提 issues 去改进支持

**Comment by xq114** [comment]
可以了
