### ISSUE TITLE
produce a warning instead of error when it fails to extract a .tar on windows

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#4412]
### 你在什么场景下需要该功能？

很多时候.tar包是给unix系打包的，里面README/LICENSE等是用软链接放的，但在windows上解压的时候就会报错权限不够。实际上这个时候7z仍然会解压剩余的部分，并去掉这些软链接，实际上并不影响编译。因此希望xmake在windows上发生解压错误的时候可以报一个warning提示报错的内容而不是error，继续执行安装。

### 描述可能的解决方案

windows上解压.tar文件的时候如果发生错误，报一个warning然后继续，不影响正常使用

**Comment by waruqi** [comment]
没啥必要，做包阶段报错，直接修了就好，add_urls 里面 通过 excludes 排除这部分 soft link 文件就行了，如果它不影响编译。。

如果影响编译，报错也是正常行为，变成警告了 查起问题来返回不方便。。

而且这个也不好改，有点硬改的味道，解压模块也不一定都用在安装包阶段，直接解压模块内部改这种行为，对于其他一些 case 是否适用 也好说。
