### ISSUE TITLE
target:add_cxxflags不生效

### ISSUE THREAD

**Issue by WSFcloud** [xmake-io/xmake#4419]
### Xmake 版本

v2.8.5+master.401d67ca9

### 操作系统版本和架构

Windows 10 22H2 19045.3693

### 描述问题

在xmake.lua中添加add_cxxflags("mingw::-fexec-charset=GBK")，build后-fexec-charset=GBK未生效，而add_cxxflags(-fexec-charset=GBK")可以生效。将mingw换成gcc，g++均未生效。
![QQ截图20231123190818](https://github.com/xmake-io/xmake/assets/20496842/cbe5c6a3-b7cb-4b2e-ab09-eb8bffa9c52d)

### 期待的结果

![截图2023](https://github.com/xmake-io/xmake/assets/20496842/8b482d72-cf8c-44b8-8c8f-8805cfa49b6b)

### 工程配置

xmake.lua:
```lua
add_rules("mode.debug", "mode.release")

target("test")
    set_kind("binary")
    set_languages("c++17")
    add_files("src/*.cpp")
    add_toolchains("mingw")
    add_cxxflags("-fexec-charset=GBK")
    add_cxxflags("-Wall")
```
\src\main.cpp::
```cpp
#include <iostream>
using namespace std;

int main()
{
	cout << "测试" << endl;
	return 0;
}
```

### 附加信息和错误日志

gcc version:
Using built-in specs.
COLLECT_GCC=C:\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/12.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-12.2.0/configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/mingw64 --with-sysroot=/c/buildroot/x86_64-1220-posix-seh-rt_v10-rev1/mingw64 --enable-host-shared --disable-multilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --enable-libstdcxx-filesystem-ts=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=nocona --with-tune=core2 --with-libiconv --with-system-zlib --with-gmp=/c/buildroot/prerequisites/x86_64-w64-mingw32-static --with-mpfr=/c/buildroot/prerequisites/x86_64-w64-mingw32-static --with-mpc=/c/buildroot/prerequisites/x86_64-w64-mingw32-static --with-isl=/c/buildroot/prerequisites/x86_64-w64-mingw32-static --with-pkgversion='x86_64-posix-seh-rev1, Built by MinGW-W64 project' --with-bugurl=https://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe -fno-ident -I/c/buildroot/x86_64-1220-posix-seh-rt_v10-rev1/mingw64/opt/include -I/c/buildroot/prerequisites/x86_64-zlib-static/include -I/c/buildroot/prerequisites/x86_64-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -fno-ident -I/c/buildroot/x86_64-1220-posix-seh-rt_v10-rev1/mingw64/opt/include -I/c/buildroot/prerequisites/x86_64-zlib-static/include -I/c/buildroot/prerequisites/x86_64-w64-mingw32-static/include' CPPFLAGS=' -I/c/buildroot/x86_64-1220-posix-seh-rt_v10-rev1/mingw64/opt/include -I/c/buildroot/prerequisites/x86_64-zlib-static/include -I/c/buildroot/prerequisites/x86_64-w64-mingw32-static/include' LDFLAGS='-pipe -fno-ident -L/c/buildroot/x86_64-1220-posix-seh-rt_v10-rev1/mingw64/opt/lib -L/c/buildroot/prerequisites/x86_64-zlib-static/lib -L/c/buildroot/prerequisites/x86_64-w64-mingw32-static/lib ' LD_FOR_TARGET=/c/buildroot/x86_64-1220-posix-seh-rt_v10-rev1/mingw64/bin/ld.exe --with-boot-ldflags=' -Wl,--disable-dynamicbase -static-libstdc++ -static-libgcc'
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 12.2.0 (x86_64-posix-seh-rev1, Built by MinGW-W64 project)

**Comment by waruqi** [comment]
> 将mingw换成gcc，g++均未生效。

g++ 对应 gxx, `add_cxxflags("gxx::-fexec-charset=GBK")`
