### ISSUE TITLE
Improve test library

### ISSUE THREAD

**Issue by OpportunityLiu** [xmake-io/xmake#442]
测试库也可以改进下，用assert报错都看不出来有啥问题

_Originally posted by @OpportunityLiu in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMTc3NzA5OTc0OnYy/pull_request_review_threads/discussion_

**Comment by OpportunityLiu** [comment]
- [ ] 补充测试用的帮助方法
- [ ] 优化测试输出结果
- [ ] 补充测试内容

**Comment by waruqi** [comment]
? 加上assert message不就好了，而且加 -v -D 执行就看到完整栈信息 xmake l -v -D ./tests/test.lua ，定位到对应哪个assert出了问题，很方便啊，个人觉得定位问题够用了

```lua
assert(false, "assert message: %s", "xxx")
```

**Comment by OpportunityLiu** [comment]
起码能提示下expact和actual，一条一条写提示信息得累死

**Comment by OpportunityLiu** [comment]
就现在这个写测试的复杂度，我也很能理解为啥ut会缺这么多。

一个人写没有这些无所谓，多人参与以后没有足够的ut控制代码质量会很快下降的。
这块我可以重构下，起码加几个are_equal are_identity啥的

**Comment by waruqi** [comment]
恩，你可以改进下，封装的通用测试接口暂时还是先放置在tests/目录下吧

tests不全，是因为一个人确实没这么多精力整，现在空闲时间也少。

**Comment by OpportunityLiu** [comment]
最好还是能根据注释自动生成，不过这又是个天坑了

**Comment by waruqi** [comment]
> 最好还是能根据注释自动生成，不过这又是个天坑了

这个坑我暂时不打算躺了，等以后有时间吧。。
