### ISSUE TITLE
完全回显链接器的输出

### ISSUE THREAD

**Issue by PR2403** [xmake-io/xmake#4420]
### 你在什么场景下需要该功能？

单片机非常看重文件的大小，所以在链接后需要显示编译的文件大小，xmake没有回显链接器的输出导致没法查看编译的文件大小

### 描述可能的解决方案

希望xmake可以添加一个参数允许完全回显链接器的输出

**Comment by PR2403** [comment]
#4410

**Comment by PR2403** [comment]
只是链接器armlink没有回显，armclang和armcc除了c编译器名字不一样，其他的都是一样的
![image](https://github.com/xmake-io/xmake/assets/64511917/e16eae6d-205a-4d14-8a21-8c9fc751c98f)
![image](https://github.com/xmake-io/xmake/assets/64511917/f7469b55-3066-4c6a-9b5c-532db56676a5)
可能我们对链接器的理解有偏差，armclang和armcc的链接器都叫armlink.exe，armclang.exe和armcc.exe只是c的编译器不是链接器。
我没接触过lua，还是您来改进吧

**Comment by waruqi** [comment]
先更新到这个版本试下，`xmake update -s github:xmake-io/xmake#armlink`

https://github.com/xmake-io/xmake/pull/4441

**Comment by waruqi** [comment]
可以了么

**Comment by PR2403** [comment]
还是不行
![image](https://github.com/xmake-io/xmake/assets/64511917/8d257a1a-ddb1-4612-9d40-ee115fa5b917)

**Comment by waruqi** [comment]
你自己调下这个 patch 我暂时没环境 https://github.com/xmake-io/xmake/pull/4441

**Comment by waruqi** [comment]
再试试

**Comment by PR2403** [comment]
可以了，感谢
