### ISSUE TITLE
gcc工具链下，xmake对于cpp文件使用gcc构建而不是g++。

### ISSUE THREAD

**Issue by yangyagami** [xmake-io/xmake#4422]
### Xmake 版本

xmake v2.8.3+20230926

### 操作系统版本和架构

Linux Raiden 6.1.54-1-lts #1 SMP PREEMPT_DYNAMIC Tue, 19 Sep 2023 10:52:23 +0000 x86_64 GNU/Linux

### 描述问题

gcc工具链下，xmake对于cpp文件使用gcc构建而不是g++。
![image](https://github.com/xmake-io/xmake/assets/45322657/337c72f7-1f20-4497-823b-10b42ef92af3)
![image](https://github.com/xmake-io/xmake/assets/45322657/7143dcda-f616-4162-ae49-f1fd176eee77)

### 期待的结果

对于cpp文件使用g++来构建。

### 工程配置

```lua
add_requires("glfw", "spdlog", "glm", "sol2")

add_rules("mode.debug", "mode.release")
add_cxflags("-Wall", "-Werror")

target("ThorTest")
        set_kind("binary")
        add_includedirs("engine", "engine/core", "engine/renderer", "engine/editor", "engine/scene", "engine/components", "engine/input", "engine/objects", "platform/linux/GLFWwindow", "platform/linux/OpenglRenderer", "3rdparty/glad/include", "3rdparty/stb_image/include", "3rdparty/imgui/include")
        add_files("test/*.cpp", "engine/*.cpp", "engine/core/*.cpp", "engine/renderer/*.cpp", "engine/editor/*.cpp", "engine/scene/*.cpp", "engine/input/*.cpp", "engine/objects/*.cpp", "platform/linux/GLFWwindow/*.cpp", "platform/linux/OpenglRenderer/*.cpp", "3rdparty/glad/src/*.c", "3rdparty/imgui/src/*.cpp")

        add_packages("spdlog", "glfw", "glm", "sol2")
```

### 附加信息和错误日志

![image](https://github.com/xmake-io/xmake/assets/45322657/337c72f7-1f20-4497-823b-10b42ef92af3)
![image](https://github.com/xmake-io/xmake/assets/45322657/7143dcda-f616-4162-ae49-f1fd176eee77)

**Comment by waruqi** [comment]
正常，有什么问题？有编译错误？

**Comment by yangyagami** [comment]
> 正常，有什么问题？有编译错误？

没有，以为是bug。
