### ISSUE TITLE
target:add不支持linkgroups

### ISSUE THREAD

**Issue by Dozingfiretruck** [xmake-io/xmake#4428]
### Xmake 版本

xmake v2.8.5+HEAD.debbd3ac3

### 操作系统版本和架构

win10

### 描述问题

target:add不支持linkgroups

### 期待的结果

target:add支持linkgroups

### 工程配置

target:add("linkgroups","aisound50_8K", {whole = true,public = true})

### 附加信息和错误日志

error: invalid value (table) at index 2 in table for 'concat'

**Comment by waruqi** [comment]
我这里可以

```console
[ 50%]: linking.release test
/usr/bin/g++ -o build/linux/x86_64/release/test build/.objs/test/linux/x86_64/release/src/main.cpp.o -m64 -s -Wl,--start-group -lpthread -Wl,--end-group
[100%]: build ok, spent 0.639s
```

```lua
add_rules("mode.debug", "mode.release")

target("test")
    set_kind("binary")
    add_files("src/*.cpp")
    on_load(function (target)
	target:add("linkgroups", "pthread", {group = true})
    end)
```

**Comment by Dozingfiretruck** [comment]
这就奇怪了。。。我这里不行，大佬看下我这个工程 https://gitee.com/openLuat/luatos-soc-2023
https://gitee.com/openLuat/luatos-soc-2023/blob/master/project/luatos/xmake.lua 里的 
![image](https://github.com/xmake-io/xmake/assets/24759100/3c42c9e2-d85c-4e3e-afa4-b0476b99c3b3)
我现在用的add_files处理的，使用target:add("linkgroups"就报错

**Comment by waruqi** [comment]
给个最小可复现的 example 工程

**Comment by Dozingfiretruck** [comment]
> 给个最小可复现的 example 工程

我测试过最基础的小工程没问题，只有上面那个工程有问题，大佬用上面的工程测试吧，运行 .\build.bat luatos 编译luatos工程

**Comment by wendal** [comment]
啊啊啊, 急需这个功能呢

**Comment by waruqi** [comment]
> luatos



> > 给个最小可复现的 example 工程
> 
> 我测试过最基础的小工程没问题，只有上面那个工程有问题，大佬用上面的工程测试吧，运行 .\build.bat luatos 编译luatos工程

```
D:\projects\personal\luatos-soc-2023>.\build.bat luatos
"=============================="
"AirM2M https://openluat.com"
"=============================="
PROJECT   : luatos
CHIP_TARGET : ec718p
LSPD_MODE : enable
"=============================="
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2022
updating repositories .. ok
note: install or modify (m) these packages (pass -y to skip confirm)?
  -> gnu_rm ec7xx
please input: y (y/n/m)

  => download http://cdndownload.openluat.com/xmake/toolchains/gcc-arm/gcc-arm-none-eabi-10-2020-q4-major-win32.zip .. ok
  => install gnu_rm ec7xx .. ok
[  3%]: cache compiling.debug project\luatos\src\luat_hmeta_ec7xx.c
[  3%]: cache compiling.debug project\luatos\src\luat_wlan_ec7xx.c
[  3%]: cache compiling.debug project\luatos\src\luat_main_ec7xx.c
[  3%]: cache compiling.debug project\luatos\src\luat_malloc_ec7xx.c
[  3%]: cache compiling.debug project\luatos\src\luat_sfd_onchip_ec7xx.c
[  3%]: cache compiling.debug project\luatos\src\luat_shell_ec7xx.c
error: project\luatos\src\luat_hmeta_ec7xx.c:1:10: fatal error: luat_base.h: No such file or directory
    1 | #include "luat_base.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
  > in project\luatos\src\luat_hmeta_ec7xx.c
warning: .\project\luatos\xmake.lua:49: cannot match add_files("D:\projects\personal\luatos-soc-2023/../LuatOS/lua/src/*.c") in target(luatos)
warning: add -v for getting more warnings ..
end
```

编译不过

**Comment by Dozingfiretruck** [comment]
> > luatos
> 
> 
> 
> > > 给个最小可复现的 example 工程
> > 
> > 我测试过最基础的小工程没问题，只有上面那个工程有问题，大佬用上面的工程测试吧，运行 .\build.bat luatos 编译luatos工程
> 
> ```
> D:\projects\personal\luatos-soc-2023>.\build.bat luatos
> "=============================="
> "AirM2M https://openluat.com"
> "=============================="
> PROJECT   : luatos
> CHIP_TARGET : ec718p
> LSPD_MODE : enable
> "=============================="
> checking for platform ... windows
> checking for architecture ... x64
> checking for Microsoft Visual Studio (x64) version ... 2022
> updating repositories .. ok
> note: install or modify (m) these packages (pass -y to skip confirm)?
>   -> gnu_rm ec7xx
> please input: y (y/n/m)
> 
>   => download http://cdndownload.openluat.com/xmake/toolchains/gcc-arm/gcc-arm-none-eabi-10-2020-q4-major-win32.zip .. ok
>   => install gnu_rm ec7xx .. ok
> [  3%]: cache compiling.debug project\luatos\src\luat_hmeta_ec7xx.c
> [  3%]: cache compiling.debug project\luatos\src\luat_wlan_ec7xx.c
> [  3%]: cache compiling.debug project\luatos\src\luat_main_ec7xx.c
> [  3%]: cache compiling.debug project\luatos\src\luat_malloc_ec7xx.c
> [  3%]: cache compiling.debug project\luatos\src\luat_sfd_onchip_ec7xx.c
> [  3%]: cache compiling.debug project\luatos\src\luat_shell_ec7xx.c
> error: project\luatos\src\luat_hmeta_ec7xx.c:1:10: fatal error: luat_base.h: No such file or directory
>     1 | #include "luat_base.h"
>       |          ^~~~~~~~~~~~~
> compilation terminated.
>   > in project\luatos\src\luat_hmeta_ec7xx.c
> warning: .\project\luatos\xmake.lua:49: cannot match add_files("D:\projects\personal\luatos-soc-2023/../LuatOS/lua/src/*.c") in target(luatos)
> warning: add -v for getting more warnings ..
> end
> ```
> 
> 编译不过

大佬没克隆luatos仓库，看一下readme，luatos仓库要克隆到2023仓库同级目录下

**Comment by Dozingfiretruck** [comment]
> > error: invalid value (table) at index 2 in table for 'concat'
> 
> 这个报错我修了，不过还有其他 link error ，你自己调下。。xmake update -s dev

可以了，链接报错是因为之前add_files把静态库合并了，重新编译就报错了，感谢
