### ISSUE TITLE
卡死

### ISSUE THREAD

**Issue by Domain** [xmake-io/xmake#4429]
### Xmake 版本

2.8.5

### 操作系统版本和架构

ubuntu 20.04

### 描述问题

有些时候直接运行xmake会卡死
builder@188:/export/project$ XMAKE_PROFILE=stuck xmake -vD
<subprocess: cat>: cat /proc/cpuinfo
<subprocess: which>: which gcc-10
<subprocess: gcc-10>: /usr/bin/gcc-10 --version
^C[xmake]: [engine]: stack traceback:
        @programdir/core/base/scheduler.lua:608: in function 'base/scheduler.co_running'
        @programdir/core/base/scheduler.lua:447: in function 'base/scheduler.co_suspend'
        @programdir/core/base/scheduler.lua:498: in function 'base/scheduler.co_sleep'
        (...tail calls...)
        ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:73: in function 'sandbox/modules/import/core/base/scheduler.co_yield'
        .../core/sandbox/modules/import/lib/detect/find_program.lua:280: in function <.../core/sandbox/modules/import/lib/detect/find_program.lua:274>
        (...tail calls...)
        @programdir/modules/detect/tools/find_gcc.lua:40: in function <@programdir/modules/detect/tools/find_gcc.lua:38>
        (...tail calls...)
        @programdir/modules/lib/detect/find_tool.lua:31: in global '_find_from_modules'
        @programdir/modules/lib/detect/find_tool.lua:42: in global '_find_tool'
        @programdir/modules/lib/detect/find_tool.lua:88: in function <@programdir/modules/lib/detect/find_tool.lua:83>
        (...tail calls...)
        @programdir/core/tool/toolchain.lua:470: in method '_checktool'
        ...     (skipping 2 levels)
        @programdir/core/tool/compiler.lua:118: in function 'tool/compiler.load'
        ...amdir/core/sandbox/modules/import/core/tool/compiler.lua:35: in field 'load'
        @programdir/modules/private/action/build/object.lua:40: in local 'script'
        @programdir/modules/private/action/build/object.lua:122: in global 'build_object'
        @programdir/modules/private/action/build/object.lua:148: in upvalue 'jobfunc'
        @programdir/modules/async/runjobs.lua:237: in function <@programdir/modules/async/runjobs.lua:222>
        [C]: in function 'xpcall'
        @programdir/core/base/utils.lua:280: in function 'base/utils.trycall'
        @programdir/core/sandbox/modules/try.lua:117: in global 'try'
        @programdir/modules/async/runjobs.lua:220: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>
Trace/breakpoint trap (core dumped)

之前正常，改了一次配置出现，每次堆栈不一定一样，还出现：
<subprocess: cat>: cat /proc/cpuinfo
<subprocess: which>: which gcc-10
<subprocess: gcc-10>: /usr/bin/gcc-10 --version
^C[xmake]: [engine]: 10
stack traceback:
        @programdir/core/base/heap.lua:119: in upvalue 'swap'
        @programdir/core/base/heap.lua:39: in upvalue 'movedown'
        @programdir/core/base/heap.lua:54: in upvalue 'pop'
        @programdir/core/base/heap.lua:137: in method 'pop'
        @programdir/core/base/timer.lua:82: in function 'base/timer.next'
        @programdir/core/base/scheduler.lua:993: in function 'base/scheduler.runloop'
        @programdir/core/main.lua:313: in function 'main.entry'
        (...tail calls...)
Trace/breakpoint trap (core dumped)

### 期待的结果

无

### 工程配置

无

### 附加信息和错误日志

无

**Comment by Domain** [comment]
<subprocess: cat>: cat /proc/cpuinfo
<subprocess: which>: which gcc-10
<subprocess: gcc-10>: /usr/bin/gcc-10 --version
^C[xmake]: [engine]: stack traceback:
        @programdir/core/base/timer.lua:47: in function 'base/timer.post_at'
        (...tail calls...)
        @programdir/core/base/scheduler.lua:490: in function 'base/scheduler.co_sleep'
        (...tail calls...)
        ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:73: in function 'sandbox/modules/import/core/base/scheduler.co_yield'
        .../core/sandbox/modules/import/lib/detect/find_program.lua:280: in function <.../core/sandbox/modules/import/lib/detect/find_program.lua:274>
        (...tail calls...)
        @programdir/modules/detect/tools/find_gcc.lua:40: in function <@programdir/modules/detect/tools/find_gcc.lua:38>
        (...tail calls...)
        @programdir/modules/lib/detect/find_tool.lua:31: in global '_find_from_modules'
        @programdir/modules/lib/detect/find_tool.lua:42: in global '_find_tool'
        @programdir/modules/lib/detect/find_tool.lua:88: in function <@programdir/modules/lib/detect/find_tool.lua:83>
        (...tail calls...)
        @programdir/core/tool/toolchain.lua:470: in method '_checktool'
        @programdir/core/tool/toolchain.lua:210: in method 'tool'
        ...     (skipping 1 levels)
        @programdir/core/tool/compiler.lua:118: in function 'tool/compiler.load'
        ...amdir/core/sandbox/modules/import/core/tool/compiler.lua:35: in field 'load'
        @programdir/modules/private/action/build/object.lua:40: in local 'script'
        @programdir/modules/private/action/build/object.lua:122: in global 'build_object'
        @programdir/modules/private/action/build/object.lua:148: in upvalue 'jobfunc'
        @programdir/modules/async/runjobs.lua:237: in function <@programdir/modules/async/runjobs.lua:222>
        [C]: in function 'xpcall'
        @programdir/core/base/utils.lua:280: in function 'base/utils.trycall'
        @programdir/core/sandbox/modules/try.lua:117: in global 'try'
        @programdir/modules/async/runjobs.lua:220: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>
Trace/breakpoint trap (core dumped)

恢复不了了

**Comment by Domain** [comment]
好像也不一定，不用分布式编译也会出现，堆栈多种多样，还有些时候提示工程被其他进程锁住了

**Comment by waruqi** [comment]
这个应该是并行的问题，你现在cpu多少 core

**Comment by Domain** [comment]
> 这个应该是并行的问题，你现在cpu多少 core，另外，可以先改成 xmake -j1 单任务看看看 还有这个问题么

24核，加了-j1参数，还是卡死，还是卡在/usr/bin/gcc-10 --version

**Comment by Domain** [comment]
另外问一句，就算不卡死的时候，我还会看见
/usr/bin/gcc-10 --version
这句输出非常多，可能有上百次，这是正常的吗

**Comment by Domain** [comment]
更多的输出
builder@188:/export/project$ XMAKE_PROFILE=stuck xmake -vD -j1
<subprocess: cat>: cat /proc/cpuinfo
<subprocess: which>: which gcc-10
<subprocess: gcc-10>: /usr/bin/gcc-10 --version
^C[xmake]: [engine]: 1
stack traceback:
        @programdir/core/base/heap.lua:127: in function <@programdir/core/base/heap.lua:126>
        (...tail calls...)
        @programdir/core/base/timer.lua:78: in function 'base/timer.next'
        @programdir/core/base/scheduler.lua:993: in function 'base/scheduler.runloop'
        @programdir/core/main.lua:313: in function 'main.entry'
        (...tail calls...)
Trace/breakpoint trap (core dumped)





builder@188:/export/project$ XMAKE_PROFILE=stuck xmake -vD -j1
<subprocess: cat>: cat /proc/cpuinfo
<subprocess: which>: which gcc-10
<subprocess: gcc-10>: /usr/bin/gcc-10 --version
^C[xmake]: [engine]: stack traceback:
        @programdir/core/base/table.lua:420: in function 'table.pack'
        @programdir/core/base/scheduler.lua:444: in function 'base/scheduler.co_suspend'
        @programdir/core/base/scheduler.lua:498: in function 'base/scheduler.co_sleep'
        (...tail calls...)
        ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:73: in function 'sandbox/modules/import/core/base/scheduler.co_yield'
        .../core/sandbox/modules/import/lib/detect/find_program.lua:280: in function <.../core/sandbox/modules/import/lib/detect/find_program.lua:274>
        (...tail calls...)
        @programdir/modules/detect/tools/find_gcc.lua:40: in function <@programdir/modules/detect/tools/find_gcc.lua:38>
        (...tail calls...)
        @programdir/modules/lib/detect/find_tool.lua:31: in global '_find_from_modules'
        @programdir/modules/lib/detect/find_tool.lua:42: in global '_find_tool'
        @programdir/modules/lib/detect/find_tool.lua:88: in function <@programdir/modules/lib/detect/find_tool.lua:83>
        (...tail calls...)
        @programdir/core/tool/toolchain.lua:470: in method '_checktool'
        ...     (skipping 2 levels)
        @programdir/core/tool/compiler.lua:118: in function 'tool/compiler.load'
        ...amdir/core/sandbox/modules/import/core/tool/compiler.lua:35: in field 'load'
        @programdir/modules/private/action/build/object.lua:40: in local 'script'
        @programdir/modules/private/action/build/object.lua:122: in global 'build_object'
        @programdir/modules/private/action/build/object.lua:148: in upvalue 'jobfunc'
        @programdir/modules/async/runjobs.lua:237: in function <@programdir/modules/async/runjobs.lua:222>
        [C]: in function 'xpcall'
        @programdir/core/base/utils.lua:280: in function 'sandbox/modules/utils.trycall'
        @programdir/core/sandbox/modules/try.lua:117: in global 'try'
        @programdir/modules/async/runjobs.lua:220: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>
Trace/breakpoint trap (core dumped)




builder@188:/export/project$ XMAKE_PROFILE=stuck xmake -vD -j1
<subprocess: cat>: cat /proc/cpuinfo
<subprocess: which>: which gcc-10
<subprocess: gcc-10>: /usr/bin/gcc-10 --version
^C[xmake]: [engine]: 23
stack traceback:
        @programdir/core/base/heap.lua:122: in upvalue 'cmp'
        @programdir/core/base/heap.lua:35: in upvalue 'movedown'
        @programdir/core/base/heap.lua:54: in upvalue 'pop'
        @programdir/core/base/heap.lua:137: in method 'pop'
        @programdir/core/base/timer.lua:82: in function 'base/timer.next'
        @programdir/core/base/scheduler.lua:993: in function 'base/scheduler.runloop'
        @programdir/core/main.lua:313: in function 'main.entry'
        (...tail calls...)
Trace/breakpoint trap (core dumped)

**Comment by waruqi** [comment]
> 另外问一句，就算不卡死的时候，我还会看见 /usr/bin/gcc-10 --version 这句输出非常多，可能有上百次，这是正常的吗

这个我修复了，先试试，`xmake update -s dev`

**Comment by waruqi** [comment]
这个还卡么？gcc --version 的问题 我处理了

**Comment by Domain** [comment]
我还没更新，现在暂时不卡，等重现了，再更新试试

**Comment by Domain** [comment]
还是会卡死，你这个修复和卡死没关系吧？只是不再多次执行/usr/bin/gcc-10 --version？我按照你的提交修改了本地文件，还是卡死。

**Comment by Domain** [comment]
据我调试，应该卡死在这一行：
[        local ok, program_path = os.iorunv("which", {name})](https://github.com/xmake-io/xmake/blob/f37de48cc3c015c429453c2ffdfd0d527c58cc87/xmake/core/sandbox/modules/import/lib/detect/find_program.lua#L213)

**Comment by waruqi** [comment]
> 还是会卡死，你这个修复和卡死没关系吧？只是不再多次执行/usr/bin/gcc-10 --version？我按照你的提交修改了本地文件，还是卡死。

是跟卡死无关，你不说看到多次 gcc --version 么，先解决了这个而已

**Comment by waruqi** [comment]
> 据我调试，应该卡死在这一行： [ local ok, program_path = os.iorunv("which", {name})](https://github.com/xmake-io/xmake/blob/f37de48cc3c015c429453c2ffdfd0d527c58cc87/xmake/core/sandbox/modules/import/lib/detect/find_program.lua#L213)

单独执行呢？会卡么。。

**Comment by waruqi** [comment]
好像跟这个 https://github.com/xmake-io/xmake/issues/4391 同一个问题

>   .../core/sandbox/modules/import/lib/detect/find_program.lua:213: in field '_find' 

也是 which 的位置

**Comment by waruqi** [comment]
可以继续调试下这两个位置，看看卡那一行了。

https://github.com/xmake-io/xmake/blob/master/core/src/xmake/process/openv.c
https://github.com/tboox/tbox/blob/master/src/tbox/platform/posix/process.c

编译调试 c 源码，参考文档：https://xmake.io/#/zh-cn/guide/faq?id=%e7%bc%96%e8%af%91%e6%ba%90%e7%a0%81

**Comment by Domain** [comment]
确实是卡在wait了：
https://github.com/xmake-io/xmake/blob/f37de48cc3c015c429453c2ffdfd0d527c58cc87/xmake/core/base/os.lua#L874
具体后面再看看怎么调试

**Comment by Domain** [comment]
根据调试，不是卡死在tbox底层，而是coroutine出不来了：
https://github.com/xmake-io/xmake/blob/f37de48cc3c015c429453c2ffdfd0d527c58cc87/xmake/core/base/scheduler.lua#L441
一直在这个函数转

**Comment by waruqi** [comment]
> 根据调试，不是卡死在tbox底层，而是coroutine出不来了：
> 
> https://github.com/xmake-io/xmake/blob/f37de48cc3c015c429453c2ffdfd0d527c58cc87/xmake/core/base/scheduler.lua#L441
> 
> 
> 一直在这个函数转

这种一般是 os.exec 执行的进程一直没退出，比如 which gcc-10 一直不退出导致 协程等待不到结果，只能一直等

**Comment by Domain** [comment]
我编译了一个debug版本的xmake，但是启动的时候，只显示两行：
[xmake]: init: ..
[xmake]: version: xmake_v2_8_5.........
就退出了，没法使用。
我就是./configure --mode=debug && make编译的

**Comment by waruqi** [comment]
> 我编译了一个debug版本的xmake，但是启动的时候，只显示两行： [xmake]: init: .. [xmake]: version: xmake_v2_8_5......... 就退出了，没法使用。 我就是./configure --mode=debug && make编译的

```
source ./scripts/srcenv.profile
xmake --version
```

进下源码调试环境

**Comment by Domain** [comment]
> > 我编译了一个debug版本的xmake，但是启动的时候，只显示两行： [xmake]: init: .. [xmake]: version: xmake_v2_8_5......... 就退出了，没法使用。 我就是./configure --mode=debug && make编译的
> 
> ```
> source ./scripts/srcenv.profile
> xmake --version
> ```
> 
> 进下源码调试环境

通过https://github.com/xmake-io/xmake/releases/download/v2.8.5/xmake-v2.8.5.tar.gz
下载的包里面没这个文件……

**Comment by waruqi** [comment]
> > > 我编译了一个debug版本的xmake，但是启动的时候，只显示两行： [xmake]: init: .. [xmake]: version: xmake_v2_8_5......... 就退出了，没法使用。 我就是./configure --mode=debug && make编译的
> > 
> > 
> > ```
> > source ./scripts/srcenv.profile
> > xmake --version
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 进下源码调试环境
> 
> 通过https://github.com/xmake-io/xmake/releases/download/v2.8.5/xmake-v2.8.5.tar.gz 下载的包里面没这个文件……

git clone 下载

**Comment by Domain** [comment]
最终发现卡死在这里：
https://github.com/tboox/tbox/blob/4e5d720f813c34dc4f2f21c6955f641932be60d7/src/tbox/platform/systemv/semaphore.c#L134

**Comment by Domain** [comment]
顺便说一下，这一行我这里编译不过，类型不对
https://github.com/tboox/tbox/blob/4e5d720f813c34dc4f2f21c6955f641932be60d7/src/tbox/platform/systemv/semaphore.c#L120
应该是timespec类型才行

**Comment by Domain** [comment]
虽然是有点奇怪，可能是clone和下载的哪里混着乱了，后面我再重新弄一下，不过我手动改成posix的semphore ，一样卡在那里

**Comment by Domain** [comment]
我又试了一下，用git clone下来的无法编译，下载的tar.gz包可以，而且在core里面执行xmake f --mode=debug && xmake，用的就是systemv的semphore

**Comment by Domain** [comment]
clone下来的会提示src/demo/xmake.lua的before_installcmd函数不存在，我把它注释掉，编译，同样用的是systemv的semphore

**Comment by waruqi** [comment]
> 我又试了一下，用git clone下来的无法编译，下载的tar.gz包可以，而且在core里面执行xmake f --mode=debug && xmake，用的就是systemv的semphore

你得用 `./configure; make` 编译，走 xmake 编译 core ， 是因为 tbox 的 xmake.lua 配置有点问题，漏掉了  posix semaphore 的检测，正好今天有其他用户报障，我刚修了 https://github.com/tboox/tbox/commit/1ec4e9222b0bdad8f58c90ce471d08b7cb03751f

你可以拉取 dev 分支 xmake 源码编译，就不会编译到 systemv 那个了。。

> 用git clone下来的无法编译

submodule 拉了么。。`git submodule update --init`

另外如果之前正常走脚本安装，还是不应该跑到 systemv 这里，现在卡的这个位置，只有你刚的源码编译才会进去

**Comment by Domain** [comment]
一样的，我重新下载了最新的dev，重新编译，然后还是卡死在类似的地方：
https://github.com/tboox/tbox/blob/059f19ed8f18cfcd59c1ca2f2aff3143157a0df4/src/tbox/platform/posix/semaphore.c#L117C28-L117C28

**Comment by waruqi** [comment]
> 一样的，我重新下载了最新的dev，重新编译，然后还是卡死在类似的地方： https://github.com/tboox/tbox/blob/059f19ed8f18cfcd59c1ca2f2aff3143157a0df4/src/tbox/platform/posix/semaphore.c#L117C28-L117C28

这个我知道，dev 只是解决不进入 systemv semphore的问题，它应该是卡在 poller_process  里了。。

可以看下是否这里的位置

https://github.com/tboox/tbox/blob/059f19ed8f18cfcd59c1ca2f2aff3143157a0df4/src/tbox/platform/posix/poller_process.c#L124

不过这个是子线程 wait，估计实现上 一些边缘 case 没考虑到，导致一直没法等到 process exit

回头有空我细看下

**Comment by Domain** [comment]
是的，就是这个位置

**Comment by waruqi** [comment]
按理 wait 之前会去 post 个 semaphore 信号，除非当前没有任何等待进程

https://github.com/tboox/tbox/blob/059f19ed8f18cfcd59c1ca2f2aff3143157a0df4/src/tbox/platform/posix/poller_process.c#L393

https://github.com/tboox/tbox/blob/059f19ed8f18cfcd59c1ca2f2aff3143157a0df4/src/tbox/platform/poller.c#L325

还有你看看这里会不会卡 

https://github.com/tboox/tbox/blob/059f19ed8f18cfcd59c1ca2f2aff3143157a0df4/src/tbox/platform/poller.c#L341

**Comment by waruqi** [comment]
能给个 tbox debug 下的。。完整 logs 么。

**Comment by Domain** [comment]
[xmake]: init: ..
[xmake]: version: xmake_v2_8_5_20231205_x86_64_sse2_elf by gnu c/c++ 9.4
[tbox]: init: ..
[tbox]: version: tbox_v1_7_5_20231205_x86_64_sse2_elf by gnu c/c++ 9.4
[tbox]: init: ok
[xmake]: init: ok
[xmake]: [engine]: project: /export/opm/trunk/opm_server
[xmake]: [engine]: programfile: /home/builder/xmake/core/build/xmake
[xmake]: [engine]: programdir: /home/builder/.local/share/xmake
[xmake]: [engine]: main: /home/builder/.local/share/xmake/core/_xmake_main.lua
[tbox]: [platform_socket]: pair: 0x5 0x6
[tbox]: [poller]: process: insert pid: 914077 with priv: 0x0
[tbox]: [poller]: process: waitpid ..
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:102
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:117
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:120
[tbox]: [poller]: process: finished: 914077, status: 0
[tbox]: [poller]: process: finished: -1, status: -1
[tbox]: [platform_socket]: send: 0x5 1 => 1, errno: 10
[tbox]: [poller]: process: waitpid ..
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:102
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:117
[tbox]: [poller]: process: prepare 1
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:120
[tbox]: [poller]: process: finished: -1, status: -1
[tbox]: [poller]: process: waitpid ..
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:102
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:117
[tbox]: [platform_socket]: recv: 0x6 1 => 1, errno: 2
[tbox]: [poller]: process: poll 1
[tbox]: [poller]: process: pid: 914077
[tbox]: [poller]: process: poll wait 1
[tbox]: [poller]: process: remove pid: 914077
[tbox]: [poller]: process: insert pid: 914079 with priv: 0x0
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:120
[tbox]: [poller]: process: finished: 914079, status: 0
[tbox]: [poller]: process: finished: -1, status: -1
[tbox]: [platform_socket]: send: 0x5 1 => 1, errno: 10
[tbox]: [poller]: process: waitpid ..
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:102
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:117

行号是我加的日志，看到socket，是不是还是也distcc有关？

**Comment by waruqi** [comment]
看 logs 跟 semphore 没啥关系，那个地方就是一个子线程，没进程事件的时候，始终会 wait semphore 的，不会卡主进程，不用管它。

> ^C[xmake]: [engine]: stack traceback:
@programdir/core/base/table.lua:420: in function 'table.pack'
@programdir/core/base/scheduler.lua:444: in function 'base/scheduler.co_suspend'
@programdir/core/base/scheduler.lua:498: in function 'base/scheduler.co_sleep'
(...tail calls...)
...mdir/core/sandbox/modules/import/core/base/scheduler.lua:73: in function 'sandbox/modules/import/core/base/scheduler.co_yield'
.../core/sandbox/modules/import/lib/detect/find_program.lua:280: in function <.../core/sandbox/modules/import/lib/detect/find_program.lua:274>

看你之前的栈，大都卡在这。。按理这个应该就是  多任务并行 find gcc --version 时候，才会执行到，如果卡这里倒是有可能的，但是你又说 -j1 也卡 就是怪了

**Comment by waruqi** [comment]
或者你试着吧这段代码先删了，yield 那段

https://github.com/xmake-io/xmake/blob/ba071b3d6a6b41d2fa49126988fa9ef826e7a909/xmake/core/sandbox/modules/import/lib/detect/find_program.lua#L280

删了后看看还卡不。。

**Comment by Domain** [comment]
去掉整个while之后，好了一次，之后再跑，又卡住了，然后恢复while，也卡在同一个地方，应该是检测flags的时候：

[xmake]: init: ..
[xmake]: version: xmake_v2_8_5_20231207_x86_64_sse2_elf by gnu c/c++ 9.4
[tbox]: init: ..
[tbox]: version: tbox_v1_7_5_20231207_x86_64_sse2_elf by gnu c/c++ 9.4
[tbox]: init: ok
[xmake]: init: ok
[xmake]: [engine]: project: /export/opm/trunk/opm_server
[xmake]: [engine]: programfile: /home/builder/xmake/core/build/xmake
[xmake]: [engine]: programdir: /home/builder/.local/share/xmake
[xmake]: [engine]: main: /home/builder/.local/share/xmake/core/_xmake_main.lua
<subprocess: cat>: cat /proc/cpuinfo
[tbox]: [platform_socket]: pair: 0x5 0x6
<subprocess: gcc-10>: /usr/bin/gcc-10 -Wno-stringop-truncation -m64 -S -o /tmp/.xmake1001/231207/_A748B5ABD9564200849AD801AD1C6310 /tmp/.xmake1001/231207/_F3443E45635A466AA3BEAE9DE99B4339.cpp
[tbox]: [poller]: process: insert pid: 928268 with priv: 0x0
[tbox]: [poller]: process: waitpid ..
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:102
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:117
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:120
[tbox]: [poller]: process: finished: 928268, status: 0
[tbox]: [poller]: process: finished: -1, status: -1
[tbox]: [platform_socket]: send: 0x5 1 => 1, errno: 10
[tbox]: [poller]: process: waitpid ..
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:102
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:117
[tbox]: [poller]: process: prepare 1
[tbox]: [platform_socket]: recv: 0x6 1 => 1, errno: 2
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:120
[tbox]: [poller]: process: poll 1
[tbox]: [poller]: process: pid: 928268
[tbox]: [poller]: process: finished: -1, status: -1
[tbox]: [poller]: process: waitpid ..
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:102
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:117
[tbox]: [poller]: process: poll wait 1
[tbox]: [poller]: process: remove pid: 928268
checking for flags (-Wno-stringop-truncation) ... ok
> gcc-10 "-Wno-stringop-truncation" "-m64"
<subprocess: gcc-10>: /usr/bin/gcc-10 -Wno-stringop-overflow -m64 -S -o /tmp/.xmake1001/231207/_2684626038F4433089E738F0DA579A40 /tmp/.xmake1001/231207/_F3443E45635A466AA3BEAE9DE99B4339.cpp
[tbox]: [poller]: process: insert pid: 928271 with priv: 0x0
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:120
[tbox]: [poller]: process: finished: 928271, status: 0
[tbox]: [poller]: process: finished: -1, status: -1
[tbox]: [platform_socket]: send: 0x5 1 => 1, errno: 10
[tbox]: [poller]: process: waitpid ..
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:102
[tbox]: src/tbox/tbox/src/tbox/platform/posix/semaphore.c:117
^C[xmake]: [engine]: stack traceback:
        @programdir/core/base/heap.lua:131: in method 'push'
        @programdir/core/base/timer.lua:50: in function 'base/timer.post_at'
        (...tail calls...)
        @programdir/core/base/scheduler.lua:490: in function 'base/scheduler.co_sleep'
        (...tail calls...)
        ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:73: in field 'co_yield'
        @programdir/modules/lib/detect/has_flags.lua:87: in function <@programdir/modules/lib/detect/has_flags.lua:44>
        (...tail calls...)
        @programdir/core/tool/builder.lua:74: in function 'tool/builder._mapflag_impl'
        (...tail calls...)
        @programdir/core/tool/builder.lua:198: in function 'tool/builder._add_flags_from_flagkind'
        @programdir/core/tool/builder.lua:274: in function 'tool/builder._add_flags_from_target'
        @programdir/core/tool/compiler.lua:343: in function 'tool/compiler.compflags'
        @programdir/modules/private/action/build/object.lua:43: in local 'script'
        @programdir/modules/private/action/build/object.lua:122: in global 'build_object'
        @programdir/modules/private/action/build/object.lua:148: in upvalue 'jobfunc'
        @programdir/modules/async/runjobs.lua:237: in function <@programdir/modules/async/runjobs.lua:222>
        [C]: in function 'xpcall'
        @programdir/core/base/utils.lua:280: in function 'base/utils.trycall'
        @programdir/core/sandbox/modules/try.lua:117: in global 'try'
        @programdir/modules/async/runjobs.lua:220: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>
[xmake]: [engine]: [error]: abort at xm_engine_signal_handler(): 865, src/xmake/engine.c

**Comment by waruqi** [comment]
因为检测 flags 那里也有这个 yeild 处理，你也可以去掉试试

https://github.com/xmake-io/xmake/blob/ba071b3d6a6b41d2fa49126988fa9ef826e7a909/xmake/modules/lib/detect/has_flags.lua#L87

**Comment by Domain** [comment]
两个都去掉后，现在确实不卡了，后续再观察一下

**Comment by waruqi** [comment]
> 现在偶尔会卡住没反应，但是ctrl+c中断后，再运行就好了

后面遇到卡住，可以再给下 `XMAKE_PROFILE=stuck` 的栈。。目前这个问题暂时还不清楚具体原因。。另外如果不开 distcc 也会卡么。。

如果能够给个完全可以复现的 example 和操作步骤，我这边调试会更方便点。

**Comment by waruqi** [comment]
这边也遇到过几次卡住，是 socket connect 超时 -1 ，服务器 ip 没起服务导致，不知道是否跟你这类似。。可以试试禁用远程服务，看看还会不会卡

XMAKE_PROFILE=stuck 也加了 socket connect 的 log

**Comment by waruqi** [comment]
这里的卡死问题应该解决了，https://github.com/xmake-io/xmake/issues/4645

不过安装包内部 make install 还有点问题，但应该跟现在这个无关了。
