### ISSUE TITLE
disconnect远程服务器不应该失败

### ISSUE THREAD

**Issue by Domain** [xmake-io/xmake#4443]
### Xmake 版本

2.8.5

### 操作系统版本和架构

Windows 11

### 描述问题

分布式编译的时候，远程机器有问题，导致编译卡死，我想换成本地编译，执行：
xmake service --disconnect --distcc
一直报错，说recv超时，导致没法断开，没法切换成本地编译

### 期待的结果

--disconnect直接删除session，甚至都不需要等待返回

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
好了，试试，`xmake update -s github:xmake-io/xmake#service`

https://github.com/xmake-io/xmake/pull/4449
