### ISSUE TITLE
xmake install failed on mingw

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#4447]
### Xmake 版本

dev

### 操作系统版本和架构

windows

### 描述问题

https://github.com/xmake-io/xmake-repo/actions/runs/7028529827/job/19124632048?pr=2880

报错
/bin/sh: -c: line 1: syntax error near unexpected token `('
/bin/sh: -c: line 1: `cp -p xmake/scripts/vsxmake/vsproj/templates/sln/ProjConfig(target,mode,arch) /mingw64/share/xmake/scripts/vsxmake/vsproj/templates/sln/ProjConfig(target,mode,arch)'
make: *** [makefile:5691: install] Error 2

### 期待的结果

mingw上可以正常安装

### 工程配置

无

### 附加信息和错误日志

https://github.com/xmake-io/xmake-repo/actions/runs/7028529827/job/19124632048?pr=2880

**Comment by waruqi** [comment]
这个我修了。
