### ISSUE TITLE
使用 xmake project -k vsxmake -m "debug" 生成 vs 项目文件，在 vs 中每次启动调试运行都会触发全量编译

### ISSUE THREAD

**Issue by vrecluse** [xmake-io/xmake#4453]
### Xmake 版本

2.8.5

### 操作系统版本和架构

Windows 10

### 描述问题

使用 xmake project -k vsxmake -m "debug" 生成 vs 项目文件，在 vs 中每次启动调试运行都会触发全量编译

### 期待的结果

如果没有文件改动，连续启动调试运行不会触发编译

### 工程配置

无

### 附加信息和错误日志

无

**Comment by vrecluse** [comment]
toolchains: clang-cl

**Comment by waruqi** [comment]
先确认下，手动执行 xmake 命令是否也有这个问题？vsxmake project 最终也是调用的 xmake 命令。。

**Comment by waruqi** [comment]
如果仅仅 vs 中出现，提供个最小可复现工程 和 详细复现步骤

**Comment by vrecluse** [comment]
@waruqi  是 xmake 的原因。
排除法确认，应该是 `set_warnings("all", "error") `
的问题。
加了这个选项，则 windows clang-cl toolset 多次连续运行 xmake，会有概率重新全部编译。
xmake 配置命令：
```
xmake f --vs=2022 --plat=windows --mode=debug --toolchain=clang-cl --vs_runtime=MDd -v
```
简单复现示例：
xmake.lua:
```lua
set_languages("c++20")
set_warnings("all", "error")
target("hello")
    set_kind("binary")
    add_files("*.cpp")

```

test.cpp:
```cpp
#include <iostream>
constexpr long fibonacci(int N) {
    long long a = 0;
    long long b = 1;
    for (long i = 0; i < N; ++i) {
        long long temp = a;
        a = b;
        b = temp + b;
    }
    return a;
}

int main() {
    constexpr long long x = fibonacci(48);
    std::cout << x << std::endl;
    return 0;
}
```
[test.zip](https://github.com/xmake-io/xmake/files/13522802/test.zip)

**Comment by waruqi** [comment]
> 加了这个选项，则 windows clang-cl toolset 多次连续运行 xmake，会有概率重新全部编译。
xmake 配置命令：

> xmake f --vs=2022 --plat=windows --mode=debug --toolchain=clang-cl --vs_runtime=MDd -v
> xmake

那你可以脱离 vs 。。先 cmd 下执行这个命令，多执行几次。。看看是否也会复现重新编译问题
