### ISSUE TITLE
test dlang/console_with_pkgs fails possibly new dub dependency algorithm

### ISSUE THREAD

**Issue by Allam76** [xmake-io/xmake#4455]
### Xmake 版本

xmake v2.8.5+master.67b89a225

### 操作系统版本和架构

Ubuntu 23.10

### 描述问题

When running test xmake/tests/projects/dlang/console_with_pkgs manually the build fails with `install dub::emsi_containers latest .. failed`

error file show the same output as above and nothing else useful.

Dub cannot find nested dependencies.

Note that dub changed the package determination with breaking changes as result. Meson also have an outstanding issue for this.

### 期待的结果

build should succed.

### 工程配置

add_rules("mode.debug", "mode.release")

add_requires("dub::log 0.4.3", {alias = "log"})
add_requires("dub::dateparser", {alias = "dateparser"})
add_requires("dub::emsi_containers", {alias = "emsi_containers"})
add_requires("dub::stdx-allocator", {alias = "stdx-allocator"})
add_requires("dub::mir-core", {alias = "mir-core"})

target("test")
    set_kind("binary")
    add_files("src/*.d")
    add_packages("log", "dateparser", "emsi_containers", "stdx-allocator", "mir-core")

### 附加信息和错误日志

error log: fetch dub::emsi_containers-latest failed!
dub: DUB version 1.34.0, built on Aug 18 2023

**Comment by waruqi** [comment]
try it again. `xmake update -s dev`

**Comment by Clouud9** [comment]
> Dose it work now?

I've had this same issue just now, it's still a problem for me.

**Comment by Clouud9** [comment]
> Dose it work now?

I've had this problem just now, so it's still an issue.
