### ISSUE TITLE
How to set arch

### ISSUE THREAD

**Issue by woubuc** [xmake-io/xmake#446]
How can I set the architecture (x86, x64) of a target? I want to build for x64 but xmake defaults to x86.

I see there is a `is_arch()` check, but there's no `set_arch()` function for a target.

**Comment by waruqi** [comment]
```console
xmake f -a x64
xmake
```

or

xmake.lua

`set_config("arch", "x64")

**Comment by n8v8R** [comment]
@waruqi how to set the arch in rule? Tried different syntax but none worked

```
rule("arm")
   on_load(function (toolchain)
    toolchain:set_config("arch", "arm")
  end)
rule_end()
```

alternating with
* `toolchain:set("config", "arch", "arm")`
* `toolchain:set("config", {"arch", "arm"})` 
* `toolchain:set("config", {arch = arm})` 
* `toolchain:set(config, "{arch", "arm}")`
* `toolchain:{set_config}("arch", "armv7")`

**Comment by waruqi** [comment]
```
rule("arm")
   on_load(function (target)  -- target, not toolchain
    target:set_arch("arm")
  end)
rule_end()
```

**Comment by n8v8R** [comment]
Thank you but unfortunately that produces

>error: @programdir/core/main.lua:284: @programdir/core/project/project.lua:882: ./xmake.lua:39: attempt to call method 'set_arch' (a nil value)

**Comment by waruqi** [comment]
> : ./xmake.lua:39: attempt to call method 'set_arch' (a nil value)

?? I did not write set_arch.

**Comment by n8v8R** [comment]
Pardon, tripped on the keyboard :hot_face:
