### ISSUE TITLE
首次config时，checking失败会生成debug文件而不是文件夹

### ISSUE THREAD

**Issue by Wzshun** [xmake-io/xmake#4461]
### Xmake 版本

2.8.5

### 操作系统版本和架构

windows10

### 描述问题

在项目第一次config时，如果checking失败了，会生成`build/plat/arch/debug`文件，而不是`debug`文件夹。

后续`xmake f`的checkging成功后，执行`xmake build`，会报错，如：
```
error: cannot create directory: build\windows\x64\debug\plugins, Unknown Error (3)
```

### 期待的结果

这个估计是os.mkdir时出错了。

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
给个可复现的最小工程，和复现步骤

**Comment by Wzshun** [comment]
今天写了个小demo，发现复现不了。。然后排查了下相关包，是我自己的问题，一个本地包的on_fetch写错了
```
        local selfDir = os.scriptdir()        
        local targetdir = path.join(config.buildir(), config.plat(), config.arch(), config.mode())
        os.cp(path.join(selfDir, "msvc2017_64bit", mode, "*.dll"), targetdir)
```

这里的targetdir应该是
```
        local targetdir = path.join(config.buildir(), config.plat(), config.arch(), config.mode(), "/")
```

关闭问题了。。
