### ISSUE TITLE
关于 Ubuntu 22.04 下，一个用户安装之后，其他用户安装报错 "not found main script"

### ISSUE THREAD

**Issue by HypoxanthineOvO** [xmake-io/xmake#4476]
### Xmake Version

latest

### Operating System Version and Architecture

Ubuntu 22.04

### Describe Bug

我在某个用户下安装了 XMake 之后（通过脚本安装），在同机器下的其他用户安装 XMake 时，在最后一步会出现：
```
not found main script: /home/{之前安装的那个用户}/.local/share/xmake/core/_xmake_main.lua
```
我尝试过脚本安装、apt 换源安装和源码安装，都会遇到同样的报错。

是否是之前用户安装的时候出现了操作问题？我该如何修复？我试过删掉我能找到的所有 XMake相关文件，但没有用

### Expected Behavior

让其他用户都能使用这个 XMake。

### Project Configuration

是安装时候遇到的问题

### Additional Information and Error Logs

x

**Comment by HypoxanthineOvO** [comment]
其他的用户的 `~/.xmake/profile` 里的 `XMAKE_PROGRAM_DIR` 都是之前用户的路径而非自己的路径。
```
export XMAKE_ROOTDIR="/home/{其他用户}/.local/bin"
export XMAKE_PROGRAM_DIR="/home/先前用户{}/.local/share/xmake"
export PATH="$XMAKE_ROOTDIR:$PATH"
test $FISH_VERSION && test -f "$XMAKE_PROGRAM_DIR/scripts/profile-unix.fish" && source "$XMAKE_PROGRAM_DIR/scripts/profile-unix.fish" && exit 0
test -f "$XMAKE_PROGRAM_DIR/scripts/profile-unix.sh" && source "$XMAKE_PROGRAM_DIR/scripts/profile-unix.sh"

```

**Comment by HypoxanthineOvO** [comment]
在通过调整访问权限强行安装好之后，我似乎可以通过把 PROGRAM_DIR 修改回当前用户来修复问题。问题似乎出现在安装的时候，某种设置错误导致了其他用户安装时都会将 Program 设置为最早安装的用户。

**Comment by HypoxanthineOvO** [comment]
感谢您刚才的提醒，我发现问题了，是因为我使用Mobaxterm ssh终端直接切换用户的时候，环境变量的传播问题，原本用户的环境变量传播到了我切换的其他用户中。感谢！

**Comment by Meha555** [comment]
> 感谢您刚才的提醒，我发现问题了，是因为我使用Mobaxterm ssh终端直接切换用户的时候，环境变量的传播问题，原本用户的环境变量传播到了我切换的其他用户中。感谢！

我也遇到过这个问题，其实出问题后不止 xmake 用不了，其他一些命令也出问题了。我是发现我设置的一些 alias 用不了才意识到可能是环境变量的问题，于是采用重开一个 Mobaxterm 的 ssh 会话来解决。

您能详细说下为啥其他用户的环境变量会传递过来吗？我挺好奇的。
