### ISSUE TITLE
xmake生成compile_comamnds的时候加入了不匹配的头文件路径

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#4479]
### Xmake 版本

2.8.3

### 操作系统版本和架构

windows 11

### 描述问题

详见 edx 的这个 issue https://gitee.com/scu319hy/edx/issues/I8MU2Q#note_23382408_link
概述:
使用如下命令生成compile_commands的时候
```
C:\Users\Administrator\xmake\xmake.exe f  -y -P "C:\Users\Administrator\temp\edx\testtt123" --buildir="C:\Users\Administrator\temp\edx\testtt123\.edx\xmake\vs2022-x64\Debug" -p windows --toolchain=msvc --cc="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" --cxx="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" --includedirs="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include;C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt;C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um;C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared;C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\winrt;C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\cppwinrt" --linkdirs="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\lib\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64" --cflags="/diagnostics:column" --cxxflags="/diagnostics:column" --mrc="C:\Program Files (x86)\Windows Kits\10\Bin\10.0.22621.0\x64\rc.exe" --arch=x64 --mode=debug

C:\Users\Administrator\xmake\xmake.exe project -y -P "C:\Users\Administrator\temp\edx\testtt123" -k compile_commands --lsp=clangd --archs="x64" --modes="debug" "C:\Users\Administrator\temp\edx\testtt123\.edx\xmake\vs2022-x64\Debug"
```
尽管在f配置的时候指定了工具链是msvc，但是因为在PATH里面加了msys的bin目录 `c:\msys64\ucrt64\bin`，
生成的compile_commands仍然会把msys的头文件目录加到项目的头文件路径里面去。

导致两个错误
1 xmake认为系统中有zlib这个包，没有去下载xmake自身的 msvc zlib包（zlib包跨msvc和mingw能混用，但是换个c++的包这样就不行了）
2 尽管当前项目指定了msvc工具链，但是会去使用msys的头文件，头文件混用，产生了错误的提示。

### 期待的结果

如果工具链指定了是msvc，即便PATH里有msys的bin目录，也不要把后者的头文件目录加到项目里

### 工程配置

应该不用

### 附加信息和错误日志

应该不用

**Comment by waruqi** [comment]
提供下  -vD 的 logs ，感觉像是默认检测到 msys/mingw 环境，自动切到 mingw 平台了

另外，可以通过 `-p windows` 显式指定 windows 平台，默认用的就是 msvc ，而不是切 --toolchian=msvc，这会导致平台和 toolchain 不一致。

**Comment by waruqi** [comment]
> 1 xmake认为系统中有zlib这个包，没有去下载xmake自身的 msvc zlib包（zlib包跨msvc和mingw能混用，但是换个c++的包这样就不行了）

xmake 默认会先找系统库，这没问题，如果你不想用系统库，可以显式禁用 `add_requires("zlib", {system = false})`

而这里被检测到系统库，是因为你 path 里面加了 pkg-config ，xmake 的系统库查找就是用的 pkg-config 去找的。

而 pkg-config/pkgconf 本身也是可以支持 windows 库的，但 xmake 无法通过 pkg-config 去判断返回的库是 gnulib 还是 mslib 格式，只能假定都可使用。

如果你想确保兼容性问题，那就不要全局加 pkg-config 到 path，尤其是 msvc 环境。。想用 pkg-config 可以在 msys/mingw 环境用。

> checking for pkg-config ... ok
checking for zlib ... pkgconfig::zlib 1.3

**Comment by waruqi** [comment]
> 尽管当前项目指定了msvc工具链，但是会去使用msys的头文件，头文件混用，产生了错误的提示。

这个我猜也有可能是 pkg-config 找到 mingw 系统的 zlib 引入的。

另外，看下你的环境变量。是不是还设置了 %MSYSTEM% 到 msys/mingw crt，这也会导致 xmake 检测当前环境为 mingw

**Comment by heheda123123** [comment]
> > C:\Users\Administrator\xmake\xmake.exe f  -y -P "C:\Users\Administrator\temp\edx\testtt123" --buildir="C:\Users\Administrator\temp\edx\testtt123.edx\xmake\vs2022-x64\Debug" -p windows --toolchain=msvc --
> > cc="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" --cxx="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe" --
> > includedirs="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include;C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt;C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um;C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared;C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\winrt;C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\cppwinrt" --linkdirs="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\lib\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64" --cflags="/diagnostics:column" --cxxflags="/diagnostics:column" --mrc="C:\Program Files (x86)\Windows Kits\10\Bin\10.0.22621.0\x64\rc.exe" --arch=x64 --mode=debug
> 
> 另外，我是不建议 cc/ld/includes/flags 挨个打散设置 msvc 的。。这并不能保证内部安装包的 msvc 版本一致性，而且可能会趟各种坑，尤其是大量使用包的项目。。
> 
> 如果要用 msvc ，就简单的设置 `xmake f -p windows` 就行了，如果要切 win sdk, toolset 和 vs 版本, vs runtime，都是有参数，可以直接切的，所有包都会自动同步 msvc 版本和环境
> 
> ```
> xmake f --vs=2022 --vs_toolset=14.0 --vs_sdkver=10.0.15063.0 -c
> ```
> 
> ```
>                 ,   {nil, "vs",         "kv", "auto", "The Microsoft Visual Studio"
>                                                     , "  e.g. --vs=2017"                            }
>                 ,   {nil, "vs_toolset", "kv", nil,    "The Microsoft Visual Studio Toolset Version"
>                                                     , "  e.g. --vs_toolset=14.0"                    }
>                 ,   {nil, "vs_sdkver",  "kv", nil,    "The Windows SDK Version of Visual Studio"
>                                                     , "  e.g. --vs_sdkver=10.0.15063.0"             }
>                 ,   {nil, "vs_runtime", "kv", nil,    "The Runtime library of Visual Studio"
>                                                     , values = {"MT", "MTd", "MD", "MDd"}           }
> ```

ok，我跟edx作者也说下

**Comment by heheda123123** [comment]
> > 1 xmake认为系统中有zlib这个包，没有去下载xmake自身的 msvc zlib包（zlib包跨msvc和mingw能混用，但是换个c++的包这样就不行了）
> 
> xmake 默认会先找系统库，这没问题，如果你不想用系统库，可以显式禁用 `add_requires("zlib", {system = false})`
> 
> 而这里被检测到系统库，是因为你 path 里面加了 pkg-config ，xmake 的系统库查找就是用的 pkg-config 去找的。
> 
> 而 pkg-config/pkgconf 本身也是可以支持 windows 库的，但 xmake 无法通过 pkg-config 去判断返回的库是 gnulib 还是 mslib 格式，只能假定都可使用。
> 
> 如果你想确保兼容性问题，那就不要全局加 pkg-config 到 path，尤其是 msvc 环境。。想用 pkg-config 可以在 msys/mingw 环境用。
> 
> > checking for pkg-config ... ok
> > checking for zlib ... pkgconfig::zlib 1.3

嗯，我是把msys的bin加到PATH里了，之前想到了可能会遇到问题，只是一直没遇到 （：
