### ISSUE TITLE
调用元方法时参数顺序倒序

### ISSUE THREAD

**Issue by ChrisCatCP** [xmake-io/xmake#4482]
### Xmake 版本

2.8.5

### 操作系统版本和架构

windows 11 latest

### 描述问题

core/base/semver.lua:165
```
function _instance:__le(version)
    print(self,version)
    return self:le(version)
end
```
输出结果为 1.8.4  v1.8.2
代码为
`package:version() >= "1.8.4"`
很明显这里  self与version反过来了

### 期待的结果

调用参数能正确

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
可以了，再试试

**Comment by ChrisCatCP** [comment]
> 可以了，再试试

这样可以倒是可以，但是他这参数反了的问题还是没解决。。

**Comment by ChrisCatCP** [comment]
> 可以了，再试试

好吧，很少用这个元方法，原来这里就是这样的，我还以为参数反了

**Comment by waruqi** [comment]
> > 可以了，再试试
> 
> 这样可以倒是可以，但是他这参数反了的问题还是没解决。。

没反，就是这样的。。你用的是 ` >= ` 它内部就是调用 `__le` + 反参，等价于 `__ge` + 正参，但是 lua 没有 `__ge` ，只能用 __le 处理。。没问题，lua 的设计如此，不是 bug

另外 不建议用 `>=`  ，建议用 `:ge`, `:le` 会有更好的兼容性。。如果我切到 luajit runtime 版本的 xmake ，你这么写目前不支持，尽管现在默认用的 lua 5.4。
