### ISSUE TITLE
error when build libcello project

### ISSUE THREAD

**Issue by lvrongjian** [xmake-io/xmake#4488]
### Xmake Version

v2.8.5+dev.b8530e7

### Operating System Version and Architecture

Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux Ubuntu 20.04.6 LTS

### Describe Bug

when i build a pure C code with a external libcello, some errors happen.
the problem maybe happen in the second stage, use g++ to compile *.o file.

### Expected Behavior

[https://www.libcello.org/learn/cello-world](url)
i use the compile command `gcc -std=gnu99 cello_world.c -lCello -lm -lpthread -o cello_world`  , all was fine.

### Project Configuration

xmake.lua

`add_rules("mode.debug", "mode.release")

target("cello")
    set_kind("binary")
    add_files("src/*.c")
    set_languages("gnu99")
    add_cxflags("-lCello", "-lm", "-lpthread")`

only one src file main.c

`#include <Cello.h>

int main(int argc, char** argv)
{
    println("hello world!\n");
    return 0;
}`

### Additional Information and Error Logs

xmake -rv
[ 25%]: compiling.release src/main.c
/usr/bin/gcc -c -m64 -fvisibility=hidden -O3 -std=gnu99 -lCello -lm -lpthread -DNDEBUG -o build/.objs/cello/linux/x86_64/release/src/main.c.o src/main.c
[ 50%]: linking.release cello
/usr/bin/g++ -o build/linux/x86_64/release/cello build/.objs/cello/linux/x86_64/release/src/main.c.o -m64 -s
/usr/bin/ld: build/.objs/cello/linux/x86_64/release/src/main.c.o: in function `Cello_Main':
main.c:(.text+0xb): undefined reference to `Tuple'
/usr/bin/ld: main.c:(.text+0x2b): undefined reference to `Terminal'
/usr/bin/ld: main.c:(.text+0x44): undefined reference to `header_init'
/usr/bin/ld: main.c:(.text+0x5b): undefined reference to `println_with'
/usr/bin/ld: build/.objs/cello/linux/x86_64/release/src/main.c.o: in function `main':
main.c:(.text.startup+0x1c): undefined reference to `Ref'
/usr/bin/ld: main.c:(.text.startup+0x49): undefined reference to `header_init'
/usr/bin/ld: main.c:(.text.startup+0x61): undefined reference to `Tuple'
/usr/bin/ld: main.c:(.text.startup+0x72): undefined reference to `Terminal'
/usr/bin/ld: main.c:(.text.startup+0x86): undefined reference to `header_init'
/usr/bin/ld: main.c:(.text.startup+0x98): undefined reference to `GC'
/usr/bin/ld: main.c:(.text.startup+0x9d): undefined reference to `new_raw_with'
/usr/bin/ld: main.c:(.text.startup+0xa4): undefined reference to `Cello_Exit'
collect2: error: ld returned 1 exit status
error: execv(/usr/bin/g++ -o build/linux/x86_64/release/cello build/.objs/cello/linux/x86_64/release/src/main.c.o -m64 -s) failed(1)

**Comment by star-hengxing** [comment]
Please use [add_links](https://xmake.io/#/manual/project_target?id=targetadd_links)

**Comment by lvrongjian** [comment]
Solved by change 
`add_cxflags("-lCello", "-lm", "-lpthread")`
into
`add_syslinks("Cello", "m", "pthread")`
