### ISSUE TITLE
在Visual Studio 2022中可否远程到linux下编译、运行和断点调试

### ISSUE THREAD

**Issue by supf1994** [xmake-io/xmake#4490]
### Is your feature request related to a problem? Please describe.

在Visual Studio 2022中可否远程到linux下编译、运行和断点调试

### Describe the solution you'd like

类似vs自带的远程linux创建功能，能否支持远程到linux上进行编译和断点调试，或者在windows进行交叉编译，远程到linux下进行断点调试

**Comment by waruqi** [comment]
编译可以走 vsxmake project generator + xmake 的远程编译特性。。vs 断点远程调试不支持。。
