### ISSUE TITLE
自动生成样例qt.quickapp缺少头文件

### ISSUE THREAD

**Issue by sunzz96** [xmake-io/xmake#4499]
### Xmake 版本

2.8.5

### 操作系统版本和架构

macOS Sonoma 14.1.2, aarch64

### 描述问题

通过`xmake create -t qt.quickapp test`创建样例程序

编译错误提示：
> **error**: /Users/UserName/Qt/6.6.0/macos/lib/QtQml.framework/Headers/qqmlregistration.h:8:10: 
**fatal error**: 'QtQmlIntegration/qqmlintegration.h' file not found
#include <QtQmlIntegration/qqmlintegration.h>

xmake.lua中添加`add_includedirs("/Users/UserName/Qt/6.6.0/macos/include")`后正常编译

如有更正确的操作，麻烦告知，多谢

### 期待的结果

按模板创建样例程序后可以直接跑通

### 工程配置

```lua
add_rules("mode.debug", "mode.release")

target("test")
    add_rules("qt.quickapp")
    add_includedirs("/Users/UserName/Qt/6.6.0/macos/include")    -- 手动添加
    add_headerfiles("src/*.h")
    add_files("src/*.cpp")
    add_files("src/qml.qrc")
```

### 附加信息和错误日志

NULL

**Comment by waruqi** [comment]
再试试 xmake update -s dev

**Comment by sunzz96** [comment]
> 再试试 xmake update -s dev

已解决，非常感谢！
