### ISSUE TITLE
XMAKE_BINARY_REPO 环境变量失效

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#4500]
### Xmake 版本

xmake v2.8.5

### 操作系统版本和架构

Ubuntu 2204

### 描述问题

即使配置了 XMAKE_BINARY_REPO 环境变量，在 xmake 编译的时候还是会去拉 github 的 build-artifacts.git 库。
![image](https://github.com/xmake-io/xmake/assets/47598093/3afcab82-022c-491a-9c92-1523d76b775d)
打印出来对应的环境变量已经设置上，但是没生效：
![image](https://github.com/xmake-io/xmake/assets/47598093/b8d93f3a-f002-4ee6-961f-48255a81442c)

### 期待的结果

可以使用 gitee 库地址，解决国内网络问题。

![image](https://github.com/xmake-io/xmake/assets/47598093/f79b346d-5bfc-4da9-98e8-3cba151b84d6)

### 工程配置

xmake_tar.sh

```bash
xmake package
```

### 附加信息和错误日志

![image](https://github.com/xmake-io/xmake/assets/47598093/d064f1ad-3dd3-442a-b7ce-3549381f3ad9)

**Comment by waruqi** [comment]
没啥问题，我这里ok，无法复现

```bash
ruki-2:tmp ruki$ XMAKE_BINARY_REPO=https://gitee.com/xmake-mirror/build-artifacts.git xrepo updat
e-repo -vD
xmake create -P .
create working ...
  [+]: xmake.lua
  [+]: src/main.cpp
  [+]: .gitignore
create ok!
xmake repo --update -v -D
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
updating repositories ..
checking for ping ... /sbin/ping
pinging the host(gitlab.com) ... 38 ms
pinging the host(gitee.com) ... 23 ms
pinging the host(github.com) ... 72 ms
pulling repository(build-artifacts): https://gitee.com/xmake-mirror/build-artifacts.git to /Users
/ruki/.xmake/repositories/build-artifacts ..
/usr/bin/git -c core.fsmonitor=false pull origin main
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 7 (delta 4), reused 7 (delta 4), pack-reused 0
Unpacking objects: 100% (7/7), 1.59 KiB | 232.00 KiB/s, done.
From https://github.com/xmake-mirror/build-artifacts
 * branch            main       -> FETCH_HEAD
   9c99f71..0559a97  main       -> origin/main
Updating 9c99f71..0559a97
```

```bash
ruki-2:test ruki$ XMAKE_BINARY_REPO=https://gitee.com/xmake-mirror/build-artifacts.git xmake f -c
vD
checking for platform ... macosx
checking for architecture ... x86_64
checking for Xcode directory ... /Applications/Xcode.app
checking for Codesign Identity of Xcode ... Apple Development: waruqi@gmail.com (T3NA4MRVPU)
checking for SDK version of Xcode for macosx (x86_64) ... 14.0
checking for Minimal target version of Xcode for macosx (x86_64) ... 14.0
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
updating repositories ..
cloning repository(build-artifacts): https://gitee.com/xmake-mirror/build-artifacts.git to /Users
/ruki/.xmake/repositories/build-artifacts ..
/usr/bin/git clone https://gitee.com/xmake-mirror/build-artifacts.git -b main -c core.fsmonitor=f
alse /Users/ruki/.xmake/repositories/build-artifacts
Cloning into '/Users/ruki/.xmake/repositories/build-artifacts'...
remote: Enumerating objects: 10088, done.
remote: Counting objects: 100% (7557/7557), done.
remote: Compressing objects: 100% (5979/5979), done.
````

**Comment by waruqi** [comment]
你确定你这样是设置了环境变量，我怎么看着你只是设置了 shell 变量。。环境变量还是没变

**Comment by waruqi** [comment]
<img width="408" alt="image" src="https://github.com/xmake-io/xmake/assets/151335/f9453f79-3daa-4e4b-b20b-5cb7f8fad2fd">

我看上面 dump 环境变量不是用的 `${env.XXX}` 么，为啥下面不是。。建议你先调下环境变量生效问题。。我这边测试没啥问题

**Comment by TOMO-CAT** [comment]
> <img alt="image" width="408" src="https://private-user-images.githubusercontent.com/151335/290716077-f9453f79-3daa-4e4b-b20b-5cb7f8fad2fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzYwMjAsIm5iZiI6MTcwMjYzNTcyMCwicGF0aCI6Ii8xNTEzMzUvMjkwNzE2MDc3LWY5NDUzZjc5LTNkYWEtNGU0Yi1iMjBiLTVjYjdmOGZhZDJmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQxMDIyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWZjNWVkMTFhZTUzNGFkNjRmOTZlODdjOWZhNjdmNTNhYmExNjU1ZjIwMTAxNjNhNWQ4MWRmM2NhYjIyYTRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eRwcSlIIiSAr1UYHqeOviu9IaFEsBGXJttCZ0VTmOPw">
> 我看上面 dump 环境变量不是用的 `${env.NODE_NAME}` 么，为啥下面不是 `env.XXX`。。建议你先调下环境变量生效问题。。我这边测试没啥问题

删除 ~/.xmake 后重新编译就可以了，感觉不是环境变量没设置上的问题。${env.XMAKE_BINARY_REPO} 是 jenkins 流水线脚本的 groovy 写法，确实传进去了。

**Comment by TOMO-CAT** [comment]
只要 `~/.xmake/repositories/build-artifacts` 存在这个环境变量就不会生效，需要删掉这个目录才会去下载对应的 repo。
