### ISSUE TITLE
About the snapshot mechanism of xmake package: Associate the version number that has passed the test with the commit that merges the PR

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#4504]
### 你在什么场景下需要该功能？

主要涉及两个问题
1 xmake包更新的时候不一定能保证旧版本仍然能通过测试
比如发现一个xmake包有新版本，于是修改版本号，提交pr，虽然会经过测试，但是只是测试最新版本号，并没有确保旧版本仍然能通过测试。特别是对于复杂一点的包，做一些比较大的修改很正常，万一有错误人眼没注意到，旧版本就break了。

2 xmake包更新的时候需要保证满足旧版本的平台支持，但是新版本源码存在一些问题测试无法通过，导致包一直是旧版本
之前给一个朋友推荐xmake，他看了之后说xmake的包版本都太老了。
下面的链接也是个例子，新版本不知道为什么android和arm都无法通过，我也不熟悉这个平台，尝试了下并没有解决。只能关闭PR
https://github.com/xmake-io/xmake-repo/pull/2923#discussion_r1427608854

我提到的snapshot机制的含义
1 在包被合并的时候记录下此时的commit和这个版本号，如果版本号已有对应的commit，则替换之前的commit。始终保证合并进去PR里的包版本号和某个commit对应
2 当用户使用某个包的时候不是去拿xmake-repo仓库最新commit里的描述，而是通过版本号去找之前记录的commit，这样无论后面包怎么改，可以保证旧版本不会break
3 另一个好处就是可以保证包的快速更新，发现某个包有新版本，做简单处理就可以提交pr，测试后可以把通过的平台和架构记录下来，而不用等到所有测试都通过。这样旧版本仍然支持那些平台，新版本可以等有空慢慢完善。不然照现在这样的标准，当前包描述写得越完善，支持的平台架构越多。以后更新版本越难，很容易新版本就通不过了，又要去打patch，但是很多平台自己用不到，没时间去看

我觉得第三点非常重要，我也提了不少PR了，很多时候都是网上看到某个包，于是会先在xmake-repo看看有没有，版本旧了就顺手更新一下，我自己只需要在linux和windows上用，如果其他平台有问题，我也不是很想花时间去解决

### 描述可能的解决方案

1

**Comment by heheda123123** [comment]
之前我还有更激进的想法。
如果能实现我上面说的这种机制，xmake其实完全可以全自动更新包，
可以写个脚本定时自动去各个包的仓库检查是否有新版本，如果有就自动提PR测试。
没问题的就自动合并，
有问题的人工处理，或者自动合并（合并的时候把通过测试的平台和架构加在on_install处）

**Comment by waruqi** [comment]
不考虑，过于复杂，并且 xmake-repo 目前是 github 维护，是无法持久化状态的，还得 merge 完，再去 commit push 去更新保持 merge commit 信息。。

而且这严重依赖 ci 脚本和 bot ，这对于其他用户自建仓库的，都没法支持，也就是这个特性只能用于官方仓库


搞这个，还不如默认开启用户端 require-lock 了。。

**Comment by waruqi** [comment]
> 之前我还有更激进的想法。 如果能实现我上面说的这种机制，xmake其实完全可以全自动更新包， 可以写个脚本定时自动去各个包的仓库检查是否有新版本，如果有就自动提PR测试。 没问题的就自动合并， 有问题的人工处理，或者自动合并（合并的时候把通过测试的平台和架构加在on_install处）

自动更新后面会搞，但这个考虑的东西比较多，还要设计一些 API，暂时没空弄

老外有做过一个自动更新脚本，目前他自用，自己本地跑脚本更新提交版本。。目前看效果也还可以
