### ISSUE TITLE
当指定使用依赖的master版本时，获取版本为空

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#4511]
### Xmake 版本

2.8.5

### 操作系统版本和架构

windows 11

### 描述问题

比如在某个包指定用了依赖的master版本
```
package:add("deps", "abseil master")
```
在依赖中如下获取版本的写法会抛异常
![image](https://github.com/xmake-io/xmake/assets/97490782/5364fd76-0e06-4924-9142-f240563f544d)
![image](https://github.com/xmake-io/xmake/assets/97490782/0ad55b15-d85b-45a3-984e-071249335964)

### 期待的结果

应该判定不符合这个版本，而不是"ttempt to index a nil value"

### 工程配置

1

### 附加信息和错误日志

1

**Comment by waruqi** [comment]
参考其他包，通过 package:gitref() 处理下。走 git branch 原本就是没 version 的

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-repo/pull/2970
