### ISSUE TITLE
`find_package` 无法找到 xrepo 安装的包

### ISSUE THREAD

**Issue by myuanz** [xmake-io/xmake#4519]
### Xmake 版本

v2.8.5+20231107

### 操作系统版本和架构

Manjaro Linux 23.1.0

### 描述问题

由于这个上下文 https://github.com/xmake-io/xmake/discussions/4514 我需要查找包安装的位置，动态注入到环境变量里。但是我注意到`find_package`只能找到系统的包，无法找到 xrepo 安装的包。比如我安装一个 zlib 后：

```bash
xmake> find_package('zlib')
< { 
    links = { 
      "z" 
    },
    linkdirs = { 
      "/usr/lib" 
    } 
  }

xmake> find_package('xmake::zlib') 
< nil

xmake> find_package('xrepo::zlib')
...mdir/core/sandbox/modules/import/core/sandbox/module.lua:428: cannot import module: package.manager.xrepo.find_package, not found!
stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:923: in function 'base/os.raiselevel'
        (...tail calls...)
        ...mdir/core/sandbox/modules/import/core/sandbox/module.lua:428: in function 'sandbox/modules/import/core/sandbox/module.import'
        @programdir/modules/package/manager/find_package.lua:109: in global '_find_package'
        @programdir/modules/package/manager/find_package.lua:193: in function <@programdir/modules/package/manager/find_package.lua:169>
        (...tail calls...)
        @programdir/modules/lib/detect/find_package.lua:109: in function <@programdir/modules/lib/detect/find_package.lua:74>
        (...tail calls...)
        [C]: in function 'sandbox/sandbox.interactive'
        ...dir/core/sandbox/modules/import/core/sandbox/sandbox.lua:102: in field 'interactive'
        @programdir/plugins/lua/main.lua:180: in function <@programdir/plugins/lua/main.lua:161>
        (...tail calls...)
        [C]: in function 'xpcall'
        @programdir/core/base/utils.lua:280: in function 'base/utils.trycall'
        (...tail calls...)
        @programdir/core/base/task.lua:501: in function 'base/task.run'
        @programdir/core/main.lua:307: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>

```

但是此时我已经通过 xrepo 安装了 zlib 

```bash
> xrepo fetch zlib
{ 
  { 
    links = { 
      "z" 
    },
    includedirs = { 
      "/home/myuan/.xmake/packages/z/zlib/v1.3/45ea3fb9069b468faf0ef6782964c796/include" 
    },
    version = "v1.3",
    libfiles = { 
      "/home/myuan/.xmake/packages/z/zlib/v1.3/45ea3fb9069b468faf0ef6782964c796/lib/libz.a" 
    },
    static = true,
    linkdirs = { 
      "/home/myuan/.xmake/packages/z/zlib/v1.3/45ea3fb9069b468faf0ef6782964c796/lib" 
    } 
  } 
}
```

另外我已经注意到`find_package`在文档里提到不再推荐使用，那我应该用什么呢？

### 期待的结果

`find_package`能找到 xrepo 安装的包

### 工程配置

通过 `xmake lua` 操作，没有配置

### 附加信息和错误日志

见问题描述

**Comment by waruqi** [comment]
> 由于这个上下文 https://github.com/xmake-io/xmake/discussions/4514 我需要查找包安装的位置，动态注入到环境变量里。但是我注意到find_package只能找到系统的包，无法找到 xrepo 安装的包。比如我安装一个 zlib 后：

不要用 find_package 。。每个 package ，根据 add_deps 依赖关系，会自动找 deps 里面的，也会自动设置所有 deps 包到  CMAKE_PREFIX_PATH , PKG_CONFIG_PATH 给当前的包 on_install 里面用，让 cmake/pkg-config 找到。。

你外面自己调用 find_package 是找不到的，每个包的 configs 不同，路径不同，只能根据当前包和对应的 deps 关系，还有当前的 configs ，去匹配包，内部会调用 find_package 找，但内部会自动透传各种 configs 计算精准包路径。

一个 zlib ，不同的配置 MT/MD, static/shared, 各种配置，都是不同的独立安装路径，你外面 find_package("zlib") 都不知道配置信息，怎么找？

另外，package 里面，尽管关联了 deps，告诉了 cmake CMAKE_PREFIX_PATH/PKG_CONFIG_PATH 信息，但是 on_install 里面 cmake 的 find_package 查找成功率也只有 50% ，不可能 100% ，这依赖 cmake 特定 findXXX.cmake 的实现，找不到的，on_install 就得加 patch 强行透传信息让它找到，或者走 packagedeps 强行打入 tools.cmake.install 废弃 cmake findXXX

如果你还要外面找，不在包的 on_install 里找，更不可能。。

**Comment by waruqi** [comment]
总结一句，不要自己用 find_package 。。一切皆用 add_requires ，它内部也会调用 find_package ，效果一样，并且完整知道包信息。。

**Comment by waruqi** [comment]
>xmake> find_package('xmake::zlib') 
> xmake> find_package('xrepo::zlib')

不要瞎用，看文档，从没支持这种 xmake:: 域

**Comment by waruqi** [comment]
> 1. 那么看起来要处理 matio 这种包的话，看起来最好的方案就是强改掉 matio 自己的 CMakeFiles 吗？
> 2. CMake 不认 XMake 添加的依赖，根据上文应该是由于 XRepo 里包装的 hdf5 包的问题？所以只是没有看到 hdf5 这个包。如果是这样的话我可以再把 hdf5 包改得完整一些。

打 patch ，或者走 packagedeps 强行打入 deps 的 includedirs/links ，不走 cmake/find_package

或者研究 cmake FindXXX.cmake 实现，看需要哪些特殊设置才能找到，on_install 额外传入

https://github.com/xmake-io/xmake-repo/blob/593c17be90034c5b9cb7611558363f90294acca7/packages/r/rpm/xmake.lua#L37

> 3. 很感谢您告诉我`add_deps`后相关信息会自动添加到 CMake 环境中，但是在开这个 Issue 之前，我已经通读里文档，没有找到在什么地方写了这回事。那么我也只能沿着朴素的道路手动查找包放置到环境变量里。这一部分我并不熟悉，如果您愿意的话请告诉我文档中哪里描述了这件事。

文档里没有，API 太多，不可能写完整，目前包配置相关文档有限，多看看其他包的 on_install，就知道了。

> 4. `xmake::`作用域确实在文档里写了，https://github.com/xmake-io/xmake/blob/b5e571f970716e31c24e7c98112e16ac55ead624/xmake/modules/package/manager/find_package.lua#L150

这也是后来才支持的，没有 xrepo:: ，并且你手动 find_package xmake::xx 是没有绑定项目 configs 上下文的，找到的也不是你 add_requires 所对应配置的。

> 5. 在此之前，我已经尝试过在 on_install 里查找 hdf5 和 zlib，都找不到 xrepo 包，所以我给出样例的时候，就直接在外面调用了，其结果跟我写在 on_install 里一致。文档里只留了一句不推荐使用 `find_package`，但是脏活总是存在的，对吧？那么当前来说这种获取安装路径的脏活最佳处理手段是什么？

打 patch 或者 on_install 额外传入 它需要的特殊配置

**Comment by myuanz** [comment]
谢谢，我接下来就试一试改掉 matio 的构建文件。

**Comment by myuanz** [comment]
后来者请参考: https://xmake.io/#/zh-cn/manual/package_instance?id=packageinstalldir
