### ISSUE TITLE
How to copy headers under build dir to intalldir() ?

### ISSUE THREAD

**Issue by lushengguo** [xmake-io/xmake#4520]
For example, mailio contains a cmake file wihch exports two hpp files to build dir, those two header files only contain some macros,  I can only copy headers that I know relative path to the root of project folder;
I want to  know how to describe copy files under build dir in xmake.lua
![image](https://github.com/xmake-io/xmake/assets/53362727/4e9ae5fe-916e-483c-9e53-afb36ebb4209)

**Comment by waruqi** [comment]
for package or target?

target:  `add_headerfiles("$(buildir)/*.h")`

package/on_install:  use os.cp

**Comment by waruqi** [comment]
> [xmake-io/xmake-repo#2968](https://github.com/xmake-io/xmake-repo/pull/2968)

merged
