### ISSUE TITLE
package:deps 的返回值会受到 add_requires 的干扰

### ISSUE THREAD

**Issue by oxc-v** [xmake-io/xmake#4522]
### Xmake 版本

2.8.3

### 操作系统版本和架构

ubuntu 22.04

### 描述问题

![IMG_0725](https://github.com/xmake-io/xmake/assets/59563828/f8cbf86c-c28a-400a-8229-2052609b0d14)

为什么 bb 和 cc 的 add_requires 顺序，会导致 cc 的 package:deps() 的结果不一样

### 期待的结果

package:deps 不受 add_requires 影响

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
具体有啥不一样？你也没说清楚啊。。每次结果不对？顺序不对？还是啥？ 啥也没说 我哪知道是什么问题？

**Comment by oxc-v** [comment]
> 具体有啥不一样？你也没说清楚啊。。每次结果不对？顺序不对？还是啥？ 啥也没说 我哪知道是什么问题？

没说清楚，这里的不一样是指，package:deps() 的返回值不是固定的，如果 add_requires(cc) 在 add_requires(bb) 的前面，那么 cc 的 package:deps() 会返回 4 个依赖项；如果 add_requires(bb) 在 add_requires(cc) 的前面，那么 cc 的 package:deps() 会返回 0 个依赖项

**Comment by waruqi** [comment]
给个完整可复现的 example ，然后提供对应 logs

**Comment by oxc-v** [comment]
> 给个完整可复现的 example ，然后提供对应 logs

[Uploading xmake-demon.zip…]()

**Comment by oxc-v** [comment]
> 给个完整可复现的 example ，然后提供对应 logs

[xmake-demon.zip](https://github.com/xmake-io/xmake/files/13726019/xmake-demon.zip)

**Comment by oxc-v** [comment]
### add_requires("aa") 在 add_requires("bb") 的前面
checking for platform ... macosx
checking for architecture ... arm64
checking for Xcode directory ... %s
checking for Codesign Identity of Xcode ... no
checking for zig ... no
checking for zig ... no
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
checking for ping ... /sbin/ping
pinging the host(gitee.com) ... 38 ms
pinging the host(gitlab.com) ... 159 ms
pinging the host(github.com) ... 65535 ms
/usr/bin/git rev-parse HEAD
checking for cmake ... no
checking for xmake::fmt ... fmt 10.1.1
checking for xmake::aa ... no
checking for brew ... /opt/homebrew/bin/brew
checking for pkg-config ... no
checking for pkgconf ... no
checking for aa ... no
checking for xmake::bb ... no
checking for bb ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
  -> aa latest [from:bb]
  -> bb latest 
please input: y (y/n/m)
y
checking for xmake::aa ... aa latest
{ 
  version = "latest" 
}

patching /Users/oxc/.xmake/packages/a/aa/latest/a5b4e345986a4740863d88955955c4b5/lib/pkgconfig/aa.pc ..
  => install aa latest .. ok
/Users/oxc/.xmake/packages/a/aa/latest/a5b4e345986a4740863d88955955c4b5/lib/*.a
libfiles  1
checking for xmake::bb ... bb latest
{ 
  version = "latest" 
}

patching /Users/oxc/.xmake/packages/b/bb/latest/a5b4e345986a4740863d88955955c4b5/lib/pkgconfig/bb.pc ..
  => install bb latest .. ok
configure
{
    plat = macosx
    kind = static
    arch = arm64
    buildir = build
    ccache = true
    mode = debug
    clean = true
    ndk_stdcxx = true
    host = macosx
}
checking for /Library/Developer/CommandLineTools/usr/bin/clang ... ok
checking for the c++ compiler (cxx) ... clang
checking for /Library/Developer/CommandLineTools/usr/bin/clang ... ok
checking for flags (-fPIC) ... ok
checking for flags (-fvisibility-inlines-hidden) ... ok
checking for flags (-O0) ... ok
[ 25%]: cache compiling.debug src/main.cpp
/Library/Developer/CommandLineTools/usr/bin/clang -c -Qunused-arguments -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -g -O0 -o build/.objs/xmake-demon/macosx/arm64/debug/src/main.cpp.o src/main.cpp
checking for flags (-MMD -MF) ... ok
checking for flags (-fdiagnostics-color=always) ... ok
checking for /Library/Developer/CommandLineTools/usr/bin/clang++ ... ok
checking for the linker (ld) ... clang++
checking for /Library/Developer/CommandLineTools/usr/bin/clang++ ... ok
checking for flags (-fPIC) ... ok
[ 50%]: linking.debug xmake-demon
/Library/Developer/CommandLineTools/usr/bin/clang++ -o build/macosx/arm64/debug/xmake-demon build/.objs/xmake-demon/macosx/arm64/debug/src/main.cpp.o -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -stdlib=libc++ -lz
[100%]: build ok, spent 0.551s
oxc@OXC-MacBook-Pro xmake-demon % xrepo remove --all aa                           
note: remove aa-latest/a5b4e345986a4740863d88955955c4b5
  -> [debug:n, pic:y, shared:n] (used) (pass -y or --confirm=y/n/d to skip confirm)?
please input: y (y/n)
y  
oxc@OXC-MacBook-Pro xmake-demon % xrepo remove --all bb                           
note: remove bb-latest/a5b4e345986a4740863d88955955c4b5
  -> [shared:n, pic:y, debug:n] (used) (pass -y or --confirm=y/n/d to skip confirm)?
please input: y (y/n)
y
oxc@OXC-MacBook-Pro xmake-demon % rm -rf build && xmake f -m debug -cv && xmake -vD
checking for platform ... macosx
checking for architecture ... arm64
checking for Xcode directory ... %s
checking for Codesign Identity of Xcode ... no
checking for zig ... no
checking for zig ... no
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
/usr/bin/git rev-parse HEAD
checking for cmake ... no
checking for xmake::fmt ... fmt 10.1.1
checking for xmake::aa ... no
checking for brew ... /opt/homebrew/bin/brew
checking for pkg-config ... no
checking for pkgconf ... no
checking for aa ... no
checking for xmake::bb ... no
checking for bb ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
  -> aa latest [from:bb]
  -> bb latest 
please input: y (y/n/m)
y
checking for xmake::aa ... aa latest
{ 
  version = "latest" 
}

patching /Users/oxc/.xmake/packages/a/aa/latest/a5b4e345986a4740863d88955955c4b5/lib/pkgconfig/aa.pc ..
  => install aa latest .. ok
/Users/oxc/.xmake/packages/a/aa/latest/a5b4e345986a4740863d88955955c4b5/lib/*.a
libfiles  1
checking for xmake::bb ... bb latest
{ 
  version = "latest" 
}

patching /Users/oxc/.xmake/packages/b/bb/latest/a5b4e345986a4740863d88955955c4b5/lib/pkgconfig/bb.pc ..
  => install bb latest .. ok
configure
{
    kind = static
    clean = true
    mode = debug
    buildir = build
    ccache = true
    host = macosx
    ndk_stdcxx = true
    plat = macosx
    arch = arm64
}
checking for /Library/Developer/CommandLineTools/usr/bin/clang ... ok
checking for the c++ compiler (cxx) ... clang
checking for /Library/Developer/CommandLineTools/usr/bin/clang ... ok
checking for flags (-fPIC) ... ok
> clang "-fPIC" "-Qunused-arguments" "-isysroot" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
checking for flags (-fvisibility-inlines-hidden) ... ok
> clang "-fvisibility-inlines-hidden" "-Qunused-arguments" "-isysroot" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
checking for flags (-O0) ... ok
> clang "-O0" "-Qunused-arguments" "-isysroot" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
[ 25%]: cache compiling.debug src/main.cpp
/Library/Developer/CommandLineTools/usr/bin/clang -c -Qunused-arguments -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -g -O0 -o build/.objs/xmake-demon/macosx/arm64/debug/src/main.cpp.o src/main.cpp
checking for flags (-MMD -MF) ... ok
> clang "-MMD" "-MF" "/dev/null" "-Qunused-arguments" "-isysroot" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
checking for flags (-fdiagnostics-color=always) ... ok
> clang "-fdiagnostics-color=always" "-Qunused-arguments" "-isysroot" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
checking for /Library/Developer/CommandLineTools/usr/bin/clang++ ... ok
checking for the linker (ld) ... clang++
checking for /Library/Developer/CommandLineTools/usr/bin/clang++ ... ok
checking for flags (-fPIC) ... ok
> clang++ "-fPIC" "-isysroot" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" "-stdlib=libc++" "-lz" "-isysroot" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" "-stdlib=libc++" "-lz"
[ 50%]: linking.debug xmake-demon
/Library/Developer/CommandLineTools/usr/bin/clang++ -o build/macosx/arm64/debug/xmake-demon build/.objs/xmake-demon/macosx/arm64/debug/src/main.cpp.o -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -stdlib=libc++ -lz

build cache stats:
cache directory: build/.build_cache
cache hit rate: 0%
cache hit: 0
cache miss: 1
new cached files: 1
remote cache hit: 0
remote new cached files: 0
preprocess failed: 0
compile fallback count: 0

[100%]: build ok, spent 0.491s

## add_requires("aa") 在 add_requires("bb") 的后面
checking for platform ... macosx
checking for architecture ... arm64
checking for Xcode directory ... %s
checking for Codesign Identity of Xcode ... no
checking for zig ... no
checking for zig ... no
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
/usr/bin/git rev-parse HEAD
checking for cmake ... no
checking for xmake::fmt ... fmt 10.1.1
checking for xmake::aa ... no
checking for brew ... /opt/homebrew/bin/brew
checking for pkg-config ... no
checking for pkgconf ... no
checking for aa ... no
checking for xmake::bb ... no
checking for bb ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
  -> aa latest [from:bb]
  -> bb latest 
please input: y (y/n/m)
y
checking for xmake::aa ... aa latest
{ 
  version = "latest" 
}

patching /Users/oxc/.xmake/packages/a/aa/latest/a5b4e345986a4740863d88955955c4b5/lib/pkgconfig/aa.pc ..
  => install aa latest .. ok
/Users/oxc/.xmake/packages/f/fmt/10.1.1/5023714ee31c498784e8f31e5250733d/lib/*.a
/Users/oxc/.xmake/packages/c/cmake/3.26.4/dfa14878089746a482b5bba1f685022f/lib/*.a
/Users/oxc/.xmake/packages/a/aa/latest/a5b4e345986a4740863d88955955c4b5/lib/*.a
libfiles  3
checking for xmake::bb ... bb latest
{ 
  version = "latest" 
}

patching /Users/oxc/.xmake/packages/b/bb/latest/a5b4e345986a4740863d88955955c4b5/lib/pkgconfig/bb.pc ..
  => install bb latest .. ok
configure
{
    clean = true
    plat = macosx
    arch = arm64
    ndk_stdcxx = true
    mode = debug
    host = macosx
    ccache = true
    kind = static
    buildir = build
}
checking for /Library/Developer/CommandLineTools/usr/bin/clang ... ok
checking for the c++ compiler (cxx) ... clang
checking for /Library/Developer/CommandLineTools/usr/bin/clang ... ok
checking for flags (-fPIC) ... ok
> clang "-fPIC" "-Qunused-arguments" "-isysroot" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
checking for flags (-fvisibility-inlines-hidden) ... ok
> clang "-fvisibility-inlines-hidden" "-Qunused-arguments" "-isysroot" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
checking for flags (-O0) ... ok
> clang "-O0" "-Qunused-arguments" "-isysroot" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
[ 25%]: cache compiling.debug src/main.cpp
/Library/Developer/CommandLineTools/usr/bin/clang -c -Qunused-arguments -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -g -O0 -o build/.objs/xmake-demon/macosx/arm64/debug/src/main.cpp.o src/main.cpp
checking for flags (-MMD -MF) ... ok
> clang "-MMD" "-MF" "/dev/null" "-Qunused-arguments" "-isysroot" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
checking for flags (-fdiagnostics-color=always) ... ok
> clang "-fdiagnostics-color=always" "-Qunused-arguments" "-isysroot" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
checking for /Library/Developer/CommandLineTools/usr/bin/clang++ ... ok
checking for the linker (ld) ... clang++
checking for /Library/Developer/CommandLineTools/usr/bin/clang++ ... ok
checking for flags (-fPIC) ... ok
> clang++ "-fPIC" "-isysroot" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" "-stdlib=libc++" "-lz" "-isysroot" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" "-stdlib=libc++" "-lz"
[ 50%]: linking.debug xmake-demon
/Library/Developer/CommandLineTools/usr/bin/clang++ -o build/macosx/arm64/debug/xmake-demon build/.objs/xmake-demon/macosx/arm64/debug/src/main.cpp.o -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -stdlib=libc++ -lz

build cache stats:
cache directory: build/.build_cache
cache hit rate: 0%
cache hit: 0
cache miss: 1
new cached files: 1
remote cache hit: 0
remote new cached files: 0
preprocess failed: 0
compile fallback count: 0

[100%]: build ok, spent 0.51s

**Comment by oxc-v** [comment]
> 再试试 #4562
> 
> ```
> xmake update -s github:xmake-io/xmake#packagedeps
> ```

解决了
