### ISSUE TITLE
qt.quickapp工程生成vs工程时，在vs中看不到qml和qrc文件

### ISSUE THREAD

**Issue by supf1994** [xmake-io/xmake#4525]
### 你在什么场景下需要该功能？

qt.quickapp工程使用  xmake project -k vsxmake  命令生成vs工程时，qml和qrc文件无法被添加到工程目录中，而ui文件可以

项目目录文件如下
![image](https://github.com/xmake-io/xmake/assets/23397492/87cd963a-af83-4a83-8138-cbd89862473c)

生成后的VS工程
![image](https://github.com/xmake-io/xmake/assets/23397492/2bd80ddf-f113-4054-8843-4918fb1e87e7)

使用的软件版本为  2.8.5

### 描述可能的解决方案

希望能将这些文件都添加进vs中，方便开发过程中对qt文件进行编辑调试

**Comment by waruqi** [comment]
自己用 add_extrafiles 加一下
