### ISSUE TITLE
生成CMake工程时，MSVC命令中出现 \ 导致cmake解析失败

### ISSUE THREAD

**Issue by supf1994** [xmake-io/xmake#4526]
### Xmake 版本

2.8.5

### 操作系统版本和架构

windows10 

### 描述问题

生成的cmake工程中有如下指令
`add_custom_command(OUTPUT output_LL-Sow-ConfigTools_2BB40C49
    COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_SOURCE_DIR}/../LL-Device-Software/build/.gens/LL-Sow-ConfigTools/windows/x64/debug/rules/qt/qrc
    COMMAND D:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/bin/rcc.exe -name qml ${CMAKE_SOURCE_DIR}/../LL-Device-Software/LL-Sow-ConfigTools/qml/qml.qrc -o ${CMAKE_SOURCE_DIR}/../LL-Device-Software/build/.gens/LL-Sow-ConfigTools/windows/x64/debug/rules/qt/qrc/qml.cpp
    COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_SOURCE_DIR}/../LL-Device-Software/build/.objs/LL-Sow-ConfigTools/windows/x64/debug/gens/rules/qt/qrc
    COMMAND D:/Develop/Tools/vs2022/Visual Studio/VC/Tools/MSVC/14.38.33130/bin/HostX64/x64/cl.exe -c -nologo -Zi -FS -Fdbuild\windows\x64\debug\compile.LL-Sow-ConfigTools.pdb -Od -std:c++latest -MDd -ID:/Develop/Lib/Vld/include -ID:/Develop/Lib/Boost/boost_1_83_0_build/include -I${CMAKE_SOURCE_DIR}/../LL-Device-Software/LL-Sow-ConfigTools -I${CMAKE_SOURCE_DIR}/../LL-Device-Software -I${CMAKE_SOURCE_DIR}/../LL-Device-Software/build/.gens/LL-Sow-ConfigTools/windows/x64/debug/rules/qt/ui -D_DEBUG -D_HAS_STD_BYTE=0 -DQT_QML_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_QUICK_LIB -DQT_QML_LIB -DQT_CORE_LIB -DQT_NETWORK_LIB -D_WINDOWS /EHsc -Yucommon_header.h -FIcommon_header.h -Fpbuild\.objs\LL-Sow-ConfigTools\windows\x64\debug\gens\LL-Sow-ConfigTools\entry\cxx\common_header.h.pch -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtGui -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtGui/5.15.2 -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtGui/5.15.2/QtGui -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtQuick -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtQuick/5.15.2 -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtQuick/5.15.2/QtQuick -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtQml -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtQml/5.15.2 -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtQml/5.15.2/QtQml -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtCore -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtCore/5.15.2 -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtCore/5.15.2/QtCore -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtNetwork -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtNetwork/5.15.2 -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtNetwork/5.15.2/QtNetwork -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/mkspecs/win32-msvc -external:W0 -external:IC:/Users/supf1/AppData/Local/.xmake/packages/o/openssl/1.1.1-w/38dc29f4427749098963c9d51f6b4577/include /bigobj /utf-8 /we4858 -Fo${CMAKE_SOURCE_DIR}/../LL-Device-Software/build/.objs/LL-Sow-ConfigTools/windows/x64/debug/gens/rules/qt/qrc/qml.cpp.obj ${CMAKE_SOURCE_DIR}/../LL-Device-Software/build/.gens/LL-Sow-ConfigTools/windows/x64/debug/rules/qt/qrc/qml.cpp
    VERBATIM
)`

指令中
COMMAND D:/Develop/Tools/vs2022/Visual Studio/VC/Tools/MSVC/14.38.33130/bin/HostX64/x64/cl.exe -c -nologo -Zi -FS -Fdbuild\windows\x64\debug\compile.LL-Sow-ConfigTools.pdb -Od -std:c++latest -MDd -ID:/Develop/Lib/Vld/include -ID:/Develop/Lib/Boost/boost_1_83_0_build/include -I${CMAKE_SOURCE_DIR}/../LL-Device-Software/LL-Sow-ConfigTools -I${CMAKE_SOURCE_DIR}/../LL-Device-Software -I${CMAKE_SOURCE_DIR}/../LL-Device-Software/build/.gens/LL-Sow-ConfigTools/windows/x64/debug/rules/qt/ui -D_DEBUG -D_HAS_STD_BYTE=0 -DQT_QML_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_QUICK_LIB -DQT_QML_LIB -DQT_CORE_LIB -DQT_NETWORK_LIB -D_WINDOWS /EHsc -Yucommon_header.h -FIcommon_header.h -Fpbuild\.objs\LL-Sow-ConfigTools\windows\x64\debug\gens\LL-Sow-ConfigTools\entry\cxx\common_header.h.pch -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtGui -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtGui/5.15.2 -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtGui/5.15.2/QtGui -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtQuick -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtQuick/5.15.2 -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtQuick/5.15.2/QtQuick -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtQml -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtQml/5.15.2 -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtQml/5.15.2/QtQml -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtCore -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtCore/5.15.2 -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtCore/5.15.2/QtCore -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtNetwork -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtNetwork/5.15.2 -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include/QtNetwork/5.15.2/QtNetwork -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/include -external:W0 -external:ID:/Develop/Lib/Qt/Qt5.15.2/5.15.2/msvc2019_64/mkspecs/win32-msvc -external:W0 -external:IC:/Users/supf1/AppData/Local/.xmake/packages/o/openssl/1.1.1-w/38dc29f4427749098963c9d51f6b4577/include /bigobj /utf-8 /we4858 -Fo${CMAKE_SOURCE_DIR}/../LL-Device-Software/build/.objs/LL-Sow-ConfigTools/windows/x64/debug/gens/rules/qt/qrc/qml.cpp.obj ${CMAKE_SOURCE_DIR}/../LL-Device-Software/build/.gens/LL-Sow-ConfigTools/windows/x64/debug/rules/qt/qrc/qml.cpp

的部分命令参数携带路径时使用\，导致cmake解析失败，例如：
Fpbuild\.objs\LL-Sow-ConfigTools\windows\x64\debug\gens\LL-Sow-ConfigTools\entry\cxx\common_header.h.pch

通过文本编辑器将文件中的 \ 替换成 / 便可以成功编译

### 期待的结果

生的cmake工程时将命令参数中路径的分隔符替换为/

### 工程配置

..

### 附加信息和错误日志

..

**Comment by waruqi** [comment]
按理 pch 我应该也已经处理了路径转换才对。。https://github.com/xmake-io/xmake/blob/b5e571f970716e31c24e7c98112e16ac55ead624/xmake/plugins/project/cmake/cmakelists.lua#L420

你可以加 print 调下这个位置的代码，以及生成的 cmakelists.txt

**Comment by waruqi** [comment]
> -Yucommon_header.h -FIcommon_header.h -Fpbuild\.objs\LL-Sow-ConfigTools\windows\x64\debug\gens\LL-Sow-ConfigTools\entry\cxx\common_header.h.pch

这个哪来的？走 set_pcxxheader 设置的 pch 不会生成这个，只会生成 

```
target_precompile_headers(main PRIVATE
  $<$<COMPILE_LANGUAGE:CXX>:${CMAKE_CURRENT_SOURCE_DIR}/build/.gens/main/windows/x64/release/src/header.h>
)
```

我这里测试没问题。。

**Comment by waruqi** [comment]
贴下你的 xmake.lua

**Comment by supf1994** [comment]
我对  project 插件中cmakelist.lua文件的_translate_flag函数做下修改就可以了，增加了对-F参数的处理
-- translate flag
function _translate_flag(flag, outputdir)
    if flag then
        if path.instance_of(flag) then
            flag = flag:clone():set(_get_relative_unix_path_to_cmake(flag:rawstr(), outputdir)):str()
        elseif path.is_absolute(flag) then
            flag = _get_relative_unix_path_to_cmake(flag, outputdir)
        elseif flag:startswith("-fmodule-file=") then
            flag = "-fmodule-file=" .. _get_relative_unix_path_to_cmake(flag:sub(15), outputdir)
        elseif flag:startswith("-fmodule-mapper=") then
            flag = "-fmodule-mapper=" .. _get_relative_unix_path_to_cmake(flag:sub(17), outputdir)
        elseif flag:startswith("-F") then
            flag = "-F" .. _get_relative_unix_path_to_cmake(flag:sub(3), outputdir)
        elseif flag:match("(.+)=(.+)") then
            local k, v = flag:match("(.+)=(.+)")
            if v and (v:endswith(".ifc") or v:endswith(".map")) then -- e.g. hello=xxx/hello.ifc
                flag = k .. "=" .. _get_relative_unix_path_to_cmake(v, outputdir)
            end
        end
    end
    return flag
end

**Comment by waruqi** [comment]
我知道这样是可以，但这是最后的办法，没办法时候 才需要这么搞。。

先要定位你这个 pch 的源头从哪里引入的，我需要看了 你的 xmake.lua 配置才知道。。按理 pch 走 set_pcxheader 不会是在 cmakelists 中生成这些 flags 的

**Comment by supf1994** [comment]
> 我知道这样是可以，但这是最后的办法，没办法时候 才需要这么搞。。
> 
> 先要定位你这个 pch 的源头从哪里引入的，我需要看了 你的 xmake.lua 配置才知道。。按理 pch 走 set_pcxheader 不会是在 cmakelists 中生成这些 flags 的
> 
> 应该直接修源头 才是最合理的

我这边统一使用的都是  set_pcxxheader，目前我将函数改成
-- translate flag
function _translate_flag(flag, outputdir)
    if flag then
        if path.instance_of(flag) then
            flag = flag:clone():set(_get_relative_unix_path_to_cmake(flag:rawstr(), outputdir)):str()
        elseif path.is_absolute(flag) then
            flag = _get_relative_unix_path_to_cmake(flag, outputdir)
        elseif flag:startswith("-fmodule-file=") then
            flag = '-fmodule-file=' .. _get_relative_unix_path_to_cmake(flag:sub(15), outputdir)
        elseif flag:startswith("-fmodule-mapper=") then
            flag = '-fmodule-mapper=' .. _get_relative_unix_path_to_cmake(flag:sub(17), outputdir)
        elseif flag:startswith("-F") then
            if flag:startswith("-Fd") then
                flag = '-Fd' .. _get_relative_unix_path_to_cmake(flag:sub(4), outputdir)
            elseif flag:startswith("-Fe") then
                flag = '-Fe' .. _get_relative_unix_path_to_cmake(flag:sub(4), outputdir)
            elseif flag:startswith("-Fi") then
                flag = '-Fi' .. _get_relative_unix_path_to_cmake(flag:sub(4), outputdir)
            elseif flag:startswith("-Fo") then
                flag = '-Fo' .. _get_relative_unix_path_to_cmake(flag:sub(4), outputdir)
            elseif flag:startswith("-Fp") then
                flag = '-Fp' .. _get_relative_unix_path_to_cmake(flag:sub(4), outputdir)
            elseif flag:startswith("-FR") then
                flag = '-FR' .. _get_relative_unix_path_to_cmake(flag:sub(4), outputdir)
            elseif flag:startswith("-Fr") then
                flag = '-Fr' .. _get_relative_unix_path_to_cmake(flag:sub(4), outputdir)
            elseif string.len(flag) > 5 then
                flag = '-F' .. _get_relative_unix_path_to_cmake(flag:sub(3), outputdir)
            end
        elseif flag:match("(.+)=(.+)") then
            local k, v = flag:match("(.+)=(.+)")
            if v and (v:endswith(".ifc") or v:endswith(".map")) then -- e.g. hello=xxx/hello.ifc
                flag = k .. '=' .. _get_relative_unix_path_to_cmake(v, outputdir)
            end
        end
    end
    return flag
end

在我的项目中可以正常工作，现在项目的目录比较多，我晚点导出一下xmake

**Comment by waruqi** [comment]
如果你用的 set_pcxxheader 不应该会生成 -Fx 这些 flags 到 cmakelists 才对。。

你可以直接调下代码：
https://github.com/xmake-io/xmake/blob/b5e571f970716e31c24e7c98112e16ac55ead624/xmake/plugins/project/cmake/cmakelists.lua#L417

目前的实现，这块是会直接生成 target_precompile_headers 配置到 cmakelists.txt

**Comment by waruqi** [comment]
> 在我的项目中可以正常工作，现在项目的目录比较多，我晚点导出一下xmake

太多了，我也调不了。。你搞个最小可复现的工程 example 方便我调试

**Comment by supf1994** [comment]
> cmakelists:print("target_precompile_headers(%s PRIVATE", target:name())

目前我这边调试下去，出问题的工程是QT工程，同时开启了预编译头文件，问题出现在生成的cmake编译前执行的指令集中，我使用的是vs，生成的cl编译指令中携带了 -Fx 这些参数，导致该问题

另外当vs安装目录中有空格时，生成的cmake文件使用vs打开编译，指令运行在windows cmd中，碰到路径有空格会导致执行错误，在   function _get_command_string(cmd, outputdir) 函数中将  cmd.program 添加到 os.args(argv) 的agv列表中，然后一起生成指令字符串可以解决该问题
`-- get command string
function _get_command_string(cmd, outputdir)
    local kind = cmd.kind
    local opt = cmd.opt
    if cmd.program then
        -- @see https://github.com/xmake-io/xmake/discussions/2156
        local argv = {_escape_path(cmd.program)}
        for _, v in ipairs(cmd.argv) do
            table.insert(argv, _translate_flag(v, outputdir))
        end

        local command = os.args(argv)
        if opt and opt.curdir then
            command = "${CMAKE_COMMAND} -E chdir " .. _get_relative_unix_path_to_cmake(opt.curdir, outputdir) .. " " .. command
        end
        return command
    elseif kind == "cp" then
        if os.isdir(cmd.srcpath) then
            return string.format("${CMAKE_COMMAND} -E copy_directory %s %s",
                _get_relative_unix_path_to_cmake(cmd.srcpath, outputdir), _get_relative_unix_path_to_cmake(cmd.dstpath, outputdir))
        else
            return string.format("${CMAKE_COMMAND} -E copy %s %s",
                _get_relative_unix_path_to_cmake(cmd.srcpath, outputdir), _get_relative_unix_path_to_cmake(cmd.dstpath, outputdir))
        end
    elseif kind == "rm" then
        return string.format("${CMAKE_COMMAND} -E rm -rf %s", _get_relative_unix_path_to_cmake(cmd.filepath, outputdir))
    elseif kind == "mv" then
        return string.format("${CMAKE_COMMAND} -E rename %s %s",
            _get_relative_unix_path_to_cmake(cmd.srcpath, outputdir), _get_relative_unix_path_to_cmake(cmd.dstpath, outputdir))
    elseif kind == "cd" then
        return string.format("cd %s", _get_relative_unix_path_to_cmake(cmd.dir, outputdir))
    elseif kind == "mkdir" then
        return string.format("${CMAKE_COMMAND} -E make_directory %s", _get_relative_unix_path_to_cmake(cmd.dir, outputdir))
    elseif kind == "show" then
        return string.format("echo %s", colors.ignore(cmd.showtext))
    end
end`

**Comment by waruqi** [comment]
那就是 moc 里面 可能带进去了

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/pull/4780

应该可以了，`xmake update -s github:xmake-io/xmake#gen`

**Comment by waruqi** [comment]
xmake update -s dev
