### ISSUE TITLE
`add_resources` 使用本地资源时出错

### ISSUE THREAD

**Issue by ririyeye** [xmake-io/xmake#4528]
### Xmake 版本

v2.8.5+master

### 操作系统版本和架构

ubuntu22 gcc-linaro-5.4.1-2017.05-x86_64_arm-linux-gnueabihf

### 描述问题

```
package("local_libusb")
    set_urls(path.join(os.scriptdir(), "libusb-1.0.26.tar.bz2"))
    add_versions("1.0.26", "12ce7a61fc9854d1d2a1ffe095f7b5fac19ddba095c259e6067a46500381b5a5")
    add_resources("1.0.26", "libusb-cmake", path.join(os.scriptdir(), "libusb-cmake.tar"), "86696181e290301f9937ec31e147746599eea97855d283f615d47a429fb55365")
```
如果使用`add_resources("v1.0.26", "libusb-cmake", "https://github.com/libusb/libusb-cmake.git", "84fb1bba4dde4c266944e7c7aa641a8a15d18f31")` github上的没有问题
文件没有问题
```
wangyang@wangyang:~/wine$ sha256sum /home/wangyang/wine/libusb-cmake.tar
86696181e290301f9937ec31e147746599eea97855d283f615d47a429fb55365  /home/wangyang/wine/libusb-cmake.tar
```

### 期待的结果

可以正常编译

### 工程配置

[wine.zip](https://github.com/xmake-io/xmake/files/13737283/wine.zip)

### 附加信息和错误日志

  => install local_json 3.11 .. ok
/usr/bin/tar -xf libusb-1.0.26.tar.bz2 -C source.tmp
  => download /home/wangyang/ppp/third_package/libusb/libusb-1.0.26.tar.bz2 .. ok
downloading resource(libusb-cmake: /home/wangyang/ppp/third_package/libusb/libusb-cmake.tar) to local_libusb-1.0.26 ..
error: ...ivate/action/require/impl/actions/download_resources.lua:121: invalid resource url(/home/wangyang/ppp/third_package/libusb/libusb-cmake.tar)
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:949]:
    [...ivate/action/require/impl/actions/download_resources.lua:121]: in function '_download'
    [...ivate/action/require/impl/actions/download_resources.lua:169]:
    [.../modules/private/action/require/impl/actions/install.lua:354]:

  => install local_libusb 1.0.26 .. failed
error: @programdir/core/main.lua:314: @programdir/modules/async/runjobs.lua:320: .../modules/private/action/require/impl/actions/install.lua:474: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:949]:
    [.../modules/private/action/require/impl/actions/install.lua:474]: in function 'catch'
    [@programdir/core/sandbox/modules/try.lua:123]: in function 'try'
    [.../modules/private/action/require/impl/actions/install.lua:333]:
    [...modules/private/action/require/impl/install_packages.lua:479]: in function 'jobfunc'
    [@programdir/modules/async/runjobs.lua:237]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:949: in function 'os.raiselevel'
        (...tail calls...)
        @programdir/core/main.lua:314: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>

**Comment by ririyeye** [comment]
```
  => download /home/wangyang/wine/libusb-1.0.26.tar.bz2 .. ok
downloading resource(libusb-cmake: /home/wangyang/wine/libusb-cmake.tar) to local_libusb-v1.0.26 ..
error: ...ivate/action/require/impl/actions/download_resources.lua:121: invalid resource url(/home/wangyang/wine/libusb-cmake.tar)
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:949]:
    [...ivate/action/require/impl/actions/download_resources.lua:121]: in function '_download'
    [...ivate/action/require/impl/actions/download_resources.lua:169]:
    [.../modules/private/action/require/impl/actions/install.lua:354]:

  => install local_libusb v1.0.26 .. failed
error: @programdir/core/main.lua:314: @programdir/modules/async/runjobs.lua:320: .../modules/private/action/require/impl/actions/install.lua:474: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:949]:
    [.../modules/private/action/require/impl/actions/install.lua:474]: in function 'catch'
    [@programdir/core/sandbox/modules/try.lua:123]: in function 'try'
    [.../modules/private/action/require/impl/actions/install.lua:333]:
    [...modules/private/action/require/impl/install_packages.lua:479]: in function 'jobfunc'
    [@programdir/modules/async/runjobs.lua:237]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:949: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir/core/main.lua:314: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>
```
更新错误日志

**Comment by waruqi** [comment]
不要用 .tar 后缀。改成常规的压缩格式   .zip   .tar.gz  。。。

**Comment by ririyeye** [comment]
.zip .tar.gz 都试了下 还是一样的报错

**Comment by waruqi** [comment]
> /home/wangyang/ppp/third_package/libusb/libusb-cmake.tar

资源文件 目前仅仅支持 http ，还不支持本地文件

**Comment by waruqi** [comment]
你都放本地仓库了，还走啥 add_resources ，直接 on_install 里直接 os.cp 或者直接访问使用不就好了么。。走 add_resources 不是多此一举么

**Comment by waruqi** [comment]
支持了，`xmake update -s dev`
