### ISSUE TITLE
VisualStudio下编译生成C++项目，在不做任何修改的前提下编译常常碰到先失败几次然后重复点生成又能生成成功的情况。

### ISSUE THREAD

**Issue by MinamotoShin** [xmake-io/xmake#4530]
### Xmake 版本

2.8.5

### 操作系统版本和架构

windows 10

### 描述问题

出现的报错不止一种，我截了两种，附有“stddef”相关的报错出现频率最高。也会出现一次编译成功的情况，但是经常会先失败几次然后继续一直点生成，连续尝试几次就突然能成功了，在编译成功后可以先清空，在release和debug之间来回切换编译，有概率继续复现这个问题。

### 期待的结果

按理说是每次都一次过。

### 工程配置

add_rules("mode.debug", "mode.release")

set_encodings("utf-8")
set_languages("c++20")

add_requires("vcpkg::fmt")
add_requires("vcpkg::sdl2" , "vcpkg::ms-gsl")

target("newxmake")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("vcpkg::fmt")
    add_packages("vcpkg::sdl2" , "vcpkg::ms-gsl")

### 附加信息和错误日志

![_20231221202255](https://github.com/xmake-io/xmake/assets/49475787/156607b3-33df-4f7f-ab9d-a4be829dec61)
![_20231221202111](https://github.com/xmake-io/xmake/assets/49475787/ef62b5e9-4263-4603-91a8-cc1267a37e21)
![_20231221202143](https://github.com/xmake-io/xmake/assets/49475787/d9e7bad1-e42f-4483-ab08-c2dc4ec8417b)

**Comment by waruqi** [comment]
直接命令行编译呢，每次也会失败？

**Comment by waruqi** [comment]
```console
xmake f -cvD
xmake -rvD
```

给下完整 logs

**Comment by waruqi** [comment]
感觉像是你的 vs 环境问题，winsdk 没装，或者没装完整，也可能是没装到默认路径导致。。

可以先自己系统目录下，找下 libcpmt.lib 所在目录

然后执行下面的命令，从 LIB 的路径中找下有没有这个路径。

```console
xmake l detect.sdks.find_vstudio
```

**Comment by waruqi** [comment]
这个库通常是在： 
`Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\onecore\<arch>`

但是你的 LIBPATH 里面，根本没这个路径。。


LIBPATH 是 vs 的 vcvarsall.bat 里面提供的，所以这个还是你的 vs 环境问题，跟 xmake 没啥关系。。

**Comment by waruqi** [comment]
不清楚，你可以对下你同事输出的 LIBPATH 的路径，看看是否相同。

或者打开 vsprompt cmd，输出下 %LIBPATH% 看看

**Comment by waruqi** [comment]
重装完

xmake g -c
xmake f -c

执行了么

**Comment by waruqi** [comment]
装 vs时候，c++ 开发套件勾选了么

**Comment by waruqi** [comment]
你没装 windows 11 sdk

**Comment by waruqi** [comment]
再执行 xmake l detect.sdks.find_vstudio 看下

libcmpt.lib 和 iostream 所在的完整路径也贴下

**Comment by waruqi** [comment]
这回看着没啥问题

xmake f -cvD
xmake -rvD

再给下完整logs呢

**Comment by waruqi** [comment]
有点怪，你创建个空工程试试呢

```bash
xmake create test
xmake -vD
```

**Comment by waruqi** [comment]
你 xmake 什么版本？

这个估计要调源码了。。可以 print 看下这个位置 

https://github.com/xmake-io/xmake/blob/728f688974dd7fc9afec6311a9db862b426a9291/xmake/modules/core/tools/link.lua#L160

里面的 `print(self:runenvs())` ，看看失败的时候，它的值

**Comment by waruqi** [comment]
连接失败，打那个位置，现在编译失败打这里

https://github.com/xmake-io/xmake/blob/728f688974dd7fc9afec6311a9db862b426a9291/xmake/modules/core/tools/cl.lua#L602

**Comment by waruqi** [comment]
> INCLUDE = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\ATLMFC\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include;D:\Windows Kits\10\include\10.0.20348.0\ucrt;D:\Windows Kits\10\include\10.0.20348.0\um;D:\Windows Kits\10\include\10.0.20348.0\shared;D:\Windows Kits\10\include\10.0.20348.0\winrt;D:\Windows Kits\10\include\10.0.20348.0\cppwinrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um;D:\masm32\include;D:\Windows Kits\10\include\10.0.22000.0\ucrt",

> C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include

在里面，iostream 所在路径，应该能找到才对。。那我也不知道为啥了。。
