### ISSUE TITLE
分支名被当作版本号解析，解析错误

### ISSUE THREAD

**Issue by zhin2929** [xmake-io/xmake#4532]
### Xmake Version

2.8.5

### Operating System Version and Architecture

win10

### Describe Bug

分支名被当作版本号解析，spdlog的分支名就叫做 "v1.x"，这么写时：add_requires("spdlog v1.x")，会出现错误：error: unable to parse semver range 'v1.x'

### Expected Behavior

正确解析分支

### Project Configuration

add_requires("spdlog v1.x")

### Additional Information and Error Logs

error: unable to parse semver range 'v1.x'

**Comment by waruqi** [comment]
可以的么

```bash
ruki-2:test ruki$ xmake f -cvD
checking for platform ... macosx
checking for architecture ... x86_64
checking for Xcode directory ... /Applications/Xcode.app
checking for Codesign Identity of Xcode ... iPhone Developer: runqing wang (A3BN6B59KQ)
checking for SDK version of Xcode for macosx (x86_64) ... 14.0
checking for Minimal target version of Xcode for macosx (x86_64) ... 14.0
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
/usr/bin/git rev-parse HEAD
finding spdlog from xmake ..
checking for xmake::spdlog ... no
finding spdlog from brew ..
checking for brew ... /usr/local/bin/brew
finding spdlog from vcpkg ..
finding spdlog from conan ..
finding spdlog from pkgconfig ..
checking for pkg-config ... /usr/local/bin/pkg-config
finding spdlog from system ..
checking for spdlog ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> spdlog v1.x
please input: y (y/n/m)

checking for ping ... /sbin/ping
pinging the host(github.com) ... 121 ms
/usr/bin/git clone https://github.com/gabime/spdlog.git -b v1.x --depth 1 --recursive --shallow
-submodules -c core.fsmonitor=false source.tmp/spdlog
Cloning into 'source.tmp/spdlog'...
remote: Enumerating objects: 189, done.
remote: Counting objects: 100% (189/189), done.
remote: Compressing objects: 100% (178/178), done.
remote: Total 189 (delta 25), reused 40 (delta 7), pack-reused 0
Receiving objects: 100% (189/189), 304.11 KiB | 823.00 KiB/s, done.
Resolving deltas: 100% (25/25), done.
  => clone https://github.com/gabime/spdlog.git v1.x .. ok
finding spdlog from xmake ..
checking for xmake::spdlog ... spdlog v1.x
{
  sysincludedirs = {
    "/Users/ruki/.xmake/packages/s/spdlog/v1.x/7c9ef39d07474d92b782b6f82483ad30/include"
  },
  version = "v1.x"
}

patching /Users/ruki/.xmake/packages/s/spdlog/v1.x/7c9ef39d07474d92b782b6f82483ad30/lib/pkgconf
ig/spdlog.pc ..
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr
/bin/clang ... ok
checking for the c++ compiler (cxx) ... clang
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr
/bin/clang ... ok
checking for flags (-fPIC) ... ok
> clang "-fPIC" "-Qunused-arguments" "-target" "x86_64-apple-macos14.0" "-isysroot" "/Applicati
ons/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk"
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-c -Qunused-arguments -target x86_64-apple-macos14.0 -isysroot /Applications/Xcode.app/Contents
/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -std=c++14 -isystem /Users/r
uki/.xmake/packages/s/spdlog/v1.x/7c9ef39d07474d92b782b6f82483ad30/include -o /var/folders/32/w
9cz0y_14hs19lkbs6v6_fm80000gn/T/.xmake501/231223/_7BF3F9243CE645308A8863D644FE3550.o /var/folde
rs/32/w9cz0y_14hs19lkbs6v6_fm80000gn/T/.xmake501/231223/_011629B690204E21A4BFE3FF7DBEFDA4.cpp
checking for flags (-fdiagnostics-color=always) ... ok
> clang "-fdiagnostics-color=always" "-Qunused-arguments" "-target" "x86_64-apple-macos14.0" "-
isysroot" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
MacOSX14.0.sdk"
> checking for c++ includes(spdlog/spdlog.h)
> checking for c++ funcs(spdlog::info)
> checking for c++ snippet(has_cxxfuncs)
  => install spdlog v1.x .. ok
```

**Comment by zhin2929** [comment]
> 可以的么
> 
> ```shell
> ruki-2:test ruki$ xmake f -cvD
> checking for platform ... macosx
> checking for architecture ... x86_64
> checking for Xcode directory ... /Applications/Xcode.app
> checking for Codesign Identity of Xcode ... iPhone Developer: runqing wang (A3BN6B59KQ)
> checking for SDK version of Xcode for macosx (x86_64) ... 14.0
> checking for Minimal target version of Xcode for macosx (x86_64) ... 14.0
> checkinfo: cannot runv(zig version), No such file or directory
> checking for zig ... no
> checkinfo: cannot runv(zig version), No such file or directory
> checking for zig ... no
> checking for unzip ... /usr/bin/unzip
> checking for git ... /usr/bin/git
> checking for gzip ... /usr/bin/gzip
> checking for tar ... /usr/bin/tar
> /usr/bin/git rev-parse HEAD
> finding spdlog from xmake ..
> checking for xmake::spdlog ... no
> finding spdlog from brew ..
> checking for brew ... /usr/local/bin/brew
> finding spdlog from vcpkg ..
> finding spdlog from conan ..
> finding spdlog from pkgconfig ..
> checking for pkg-config ... /usr/local/bin/pkg-config
> finding spdlog from system ..
> checking for spdlog ... no
> note: install or modify (m) these packages (pass -y to skip confirm)?
> in xmake-repo:
>   -> spdlog v1.x
> please input: y (y/n/m)
> 
> checking for ping ... /sbin/ping
> pinging the host(github.com) ... 121 ms
> /usr/bin/git clone https://github.com/gabime/spdlog.git -b v1.x --depth 1 --recursive --shallow
> -submodules -c core.fsmonitor=false source.tmp/spdlog
> Cloning into 'source.tmp/spdlog'...
> remote: Enumerating objects: 189, done.
> remote: Counting objects: 100% (189/189), done.
> remote: Compressing objects: 100% (178/178), done.
> remote: Total 189 (delta 25), reused 40 (delta 7), pack-reused 0
> Receiving objects: 100% (189/189), 304.11 KiB | 823.00 KiB/s, done.
> Resolving deltas: 100% (25/25), done.
>   => clone https://github.com/gabime/spdlog.git v1.x .. ok
> finding spdlog from xmake ..
> checking for xmake::spdlog ... spdlog v1.x
> {
>   sysincludedirs = {
>     "/Users/ruki/.xmake/packages/s/spdlog/v1.x/7c9ef39d07474d92b782b6f82483ad30/include"
>   },
>   version = "v1.x"
> }
> 
> patching /Users/ruki/.xmake/packages/s/spdlog/v1.x/7c9ef39d07474d92b782b6f82483ad30/lib/pkgconf
> ig/spdlog.pc ..
> checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr
> /bin/clang ... ok
> checking for the c++ compiler (cxx) ... clang
> checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr
> /bin/clang ... ok
> checking for flags (-fPIC) ... ok
> > clang "-fPIC" "-Qunused-arguments" "-target" "x86_64-apple-macos14.0" "-isysroot" "/Applicati
> ons/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk"
> > /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
> -c -Qunused-arguments -target x86_64-apple-macos14.0 -isysroot /Applications/Xcode.app/Contents
> /Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -std=c++14 -isystem /Users/r
> uki/.xmake/packages/s/spdlog/v1.x/7c9ef39d07474d92b782b6f82483ad30/include -o /var/folders/32/w
> 9cz0y_14hs19lkbs6v6_fm80000gn/T/.xmake501/231223/_7BF3F9243CE645308A8863D644FE3550.o /var/folde
> rs/32/w9cz0y_14hs19lkbs6v6_fm80000gn/T/.xmake501/231223/_011629B690204E21A4BFE3FF7DBEFDA4.cpp
> checking for flags (-fdiagnostics-color=always) ... ok
> > clang "-fdiagnostics-color=always" "-Qunused-arguments" "-target" "x86_64-apple-macos14.0" "-
> isysroot" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
> MacOSX14.0.sdk"
> > checking for c++ includes(spdlog/spdlog.h)
> > checking for c++ funcs(spdlog::info)
> > checking for c++ snippet(has_cxxfuncs)
>   => install spdlog v1.x .. ok
> ```

我windows平台不行，会出现错误：error: @programdir\core\main.lua:314: @programdir\modules\async\runjobs.lua:320: ...gramdir\core\sandbox\modules\import\core\base\semver.lua:82: unable to parse semver range 'v1.x'        要更新xmake?我还是2.8.5的

**Comment by waruqi** [comment]
我 windows 也可以，没啥问题。要么你试试 dev 版本 xmake update -s dev


```
xmake f -cvD
checking for platform ... windows
checking for architecture ... x64
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.38.33129\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(unzip.exe -v), No such file or directory
checking for unzip ... no
checking for 7z ... D:\projects\personal\xmake\scripts\..\xmake\winenv\bin\7z
checking for git ... ok
checkinfo: cannot runv(gzip.exe --version), No such file or directory
checking for gzip ... no
checking for ping ... ok
pinging the host(gitee.com) ... 17 ms
pinging the host(github.com) ... 96 ms
pinging the host(gitlab.com) ... 62 ms
git rev-parse HEAD
finding spdlog from xmake ..
checking for xmake::spdlog ... no
finding spdlog from vcpkg ..
finding spdlog from conan ..
finding spdlog from pkgconfig ..
checkinfo: cannot runv(pkg-config.exe --version), No such file or directory
checking for pkg-config ... no
checkinfo: cannot runv(pkgconf.exe --version), No such file or directory
checking for pkgconf ... no
finding spdlog from system ..
checking for spdlog ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> spdlog v1.x [vs_runtime:"MT"]
please input: y (y/n/m)

git clone https://github.com/gabime/spdlog.git -b v1.x --depth 1 --recursive --shallow-submodules -c core.fsmonitor=false source.tmp\spdlog
Cloning into 'source.tmp\spdlog'...
remote: Enumerating objects: 189, done.
remote: Counting objects: 100% (189/189), done.
remote: Compressing objects: 100% (178/178), done.
remote: Total 189 (delta 26), reused 34 (delta 7), pack-reused 0Receiving objects:  93% (176/189)
Receiving objects: 100% (189/189), 307.05 KiB | 1014.00 KiB/s, done.
Resolving deltas: 100% (26/26), done.
  => clone https://github.com/gabime/spdlog.git v1.x .. ok
finding spdlog from xmake ..
checking for xmake::spdlog ... spdlog v1.x
{
  version = "v1.x",
  sysincludedirs = {
    "C:\Users\wangrunqing\AppData\Local\.xmake\packages\s\spdlog\v1.x\e07ce06651a240dd8811e61e2843b3e0\include"
  }
}

patching C:\Users\wangrunqing\AppData\Local\.xmake\packages\s\spdlog\v1.x\e07ce06651a240dd8811e61e2843b3e0\lib\pkgconfig\spdlog.pc ..
checking for link.exe ... C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.38.33129\bin\HostX64\x64\link.exe
checking for the linker (ld) ... link.exe
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.38.33129\bin\HostX64\x64\cl.exe
checking for the c++ compiler (cxx) ... cl.exe
checking for C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.38.33129\bin\HostX64\x64\cl.exe ... ok
checking for flags (/MT) ... ok
> cl.exe "/MT" "-nologo"
checking for flags (cl_external_includedir) ... ok
> cl.exe "-external:W0" "-external:IC:\Users\wangrunqing\AppData\Local\.xmake\packages\s\spdlog\v1.x\e07ce06651a240dd8811e61e2843b3e0\include" "-nologo"
> "C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\VC\\Tools\\MSVC\\14.38.33129\\bin\\HostX64\\x64\\cl.exe" -c -nologo /MT -std:c++14 /EHsc -external:W0 -external:IC:\Users\wangrunqing\AppData\Local\.xmake\packages\s\spdlog\v1.x\e07ce06651a240dd8811e61e2843b3e0\include -FoC:\Users\WANGRU~1\AppData\Local\Temp\.xmake\231225\_4A17920B9C05464080C7EC6F2844ADB0.o C:\Users\WANGRU~1\AppData\Local\Temp\.xmake\231225\_011629B690204E21A4BFE3FF7DBEFDA4.cpp
> checking for c++ includes(spdlog/spdlog.h)
> checking for c++ funcs(spdlog::info)
> checking for c++ snippet(has_cxxfuncs)
  => install spdlog v1.x .. ok
configure
{
    theme = default
    mode = release
    clean = true
    arch = x64
    proxy_pac = pac.lua
    kind = static
    buildir = build
    ndk_stdcxx = true
    network = public
    host = windows
    plat = windows
    vs = 2022
    ccache = true
}
```
