### ISSUE TITLE
cross toolchain: winegcc, wineg++ not recognized

### ISSUE THREAD

**Issue by shaqtsui** [xmake-io/xmake#4533]
### Xmake Version

2.8.5

### Operating System Version and Architecture

linux(guix 1.4)

### Describe Bug

winegcc, wineg++ are compiler tools provided by wine. 
When I specify them via `xmake f --sdk=/path/to/dir/of/winegcc --cross=wine`, I got error: `ore/sandbox/modules/import/core/tool/compiler.lua:37: cannot find known tool script for /path/to/dir/of/winegcc/winegcc`

### Expected Behavior

cross compile success with winegcc, wineg++

### Project Configuration

```
target "mtexample"
set_languages "c++20"
add_files "src/*.cpp"
```

### Additional Information and Error Logs

modules/lib/detect/find_toolname.lua:main() can not correctly parse tool name.

**Comment by waruqi** [comment]
强制作为 gcc 使用，否则是未知编译器

```
xmake f --cxx=gcc@/xxx/xxx/winegcc --cc=gcc@/xxx/xxx/xxwinegcc --ld=...
```

https://xmake.io/#/zh-cn/guide/configuration?id=%e8%ae%be%e7%bd%aecc%e7%bc%96%e8%af%91%e5%99%a8

**Comment by shaqtsui** [comment]
thx a lot
