### ISSUE TITLE
导出 ninja 工程时 toolchain 设置错误

### ISSUE THREAD

**Issue by feather179** [xmake-io/xmake#4536]
### Xmake 版本

v2.8.5+HEAD.debbd3ac3

### 操作系统版本和架构

Windows 10 version 1809

### 描述问题

同时安装有 MSVC 和 mingw 编译器
xmake.lua 中设置 set_toolchains("mingw")  ，但是导出 ninja 工程时(xmake project -k ninja)，build.ninja 中设定的是 MSVC 相关的编译器和链接器
如果设置 set_toolchains("msvc")，导出的 build.ninja 中也是 MSVC 相关的编译器和链接器

### 期待的结果

set_toolchains("mingw") 时，build.ninja 中使用 Mingw 相关的编译器 (gcc， g++)

### 工程配置

add_rules("mode.debug", "mode.release")
 
target("test")
    set_kind("binary")
    set_toolchains("mingw")
    set_languages("c++20")
    add_files("main.cpp")

### 附加信息和错误日志

生成的 build.ninja 文件

ninja_required_version = 1.5.1

rule gen
 command = xmake project -P . -k ninja
 description = regenerating ninja files

# rules for compiler
msvc_deps_prefix = Note: including file:
rule as
 command = D:\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64\ml64.exe -c $ARGS -Fo$out $in
 deps = msvc
 description = compiling.debug $in

rule cc
 command = D:\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64\cl.exe -showIncludes -c $ARGS $in -Fo$out
 deps = msvc
 description = compiling.debug $in

rule cxx
 command = D:\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64\cl.exe -showIncludes -c $ARGS $in -Fo$out
 deps = msvc
 description = compiling.debug $in

**Comment by waruqi** [comment]
默认是 windows 平台，走的 msvc 。。你要切 mingw 。。得切到 mingw 平台

```
xmake f -p mingw
xmake
```

不要单独切 toolchain

**Comment by feather179** [comment]
哇  可以了，感谢大大~
