### ISSUE TITLE
是否考虑打包成单一文件

### ISSUE THREAD

**Issue by Domain** [xmake-io/xmake#4542]
### 你在什么场景下需要该功能？

premake，fbuild都是单一文件，使用方便，直接放在仓库里，所有人都可以直接获取，升级一次，所有人自动更新，不用每个人自己重新安装，这在多人开发的时候非常方便

### 描述可能的解决方案

参考premake，把所有lua脚本生成到c文件里面

**Comment by waruqi** [comment]
不考虑

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/pull/5491
