### ISSUE TITLE
target() 如果参数为 nil 应该报错

### ISSUE THREAD

**Issue by tisyang** [xmake-io/xmake#4547]
### 你在什么场景下需要该功能？

如果在 `xmake.lua` 中错误的将 `target("xxx")` 写成了 `target(xxx)`，那么构建将会忽略这个目标且不会报错，此时 xxx 作为变量引用大概率默认为 `nil`。

其次，如果在大工程中使用变量来组建多 `target`，那么如果意外传入值为 `nil` 的时候，也无法提示错误，因为这时候传入 `nil` 事实上应该是一个隐藏的构建问题。

### 描述可能的解决方案

建议 `target` 应该检查参数，检查参数是否为 `nil` ，如果是，则应该提示错误。
如果要区分空参数（无参数）和 `nil` 参数，则可以参考 https://stackoverflow.com/questions/12622912/detecting-single-nil-argument-in-lua 

### 描述你认为的候选方案

如果为了保持某些兼容性，可以考虑使用输出警告提示信息代替错误。

**Comment by waruqi** [comment]
target() 如果没有参数，就是重新进入 root 域，等于全局设置，这是原本的设计，目前也不太好改，尽管这种写法用的不多

```lua
target()
    add_defines("TEST")

target("test")
    set_kind("binary")
    add_files("src/*.cpp")
```

**Comment by tisyang** [comment]
> target() 如果没有参数，就是重新进入 root 域，等于全局设置，这是原本的设计，目前也不太好改，尽管这种写法用的不多
> 
> ```lua
> target()
>     add_defines("TEST")
> 
> target("test")
>     set_kind("binary")
>     add_files("src/*.cpp")
> ```

我觉得 没参数 和（意外）传入 `nil` 参数的情况应该进行区分，前者有意进入全局配置，后者多数可能是意料之外的情况，后者应该进行警告。
如果 `target` 是 lua 脚本实现的话，可以参考[代码](https://stackoverflow.com/questions/12622912/detecting-single-nil-argument-in-lua)进行区分：
```lua
function myFunc(...)
  if select('#', ...) == 0 then
    print "Called without argument"
  elseif select('#', ...) == 1 and select(1, ...) == nil then
    print "Called with a nil argument"
  end
end
```

**Comment by waruqi** [comment]
加上了，再试试  xmake update -s dev

```
error: ./xmake.lua:3: target(nil): invalid target name
```

**Comment by tisyang** [comment]
> 加上了，再试试 xmake update -s dev
> 
> ```
> error: ./xmake.lua:3: target(nil): invalid target name
> ```
测试 OK.

升级 dev 前：
```bash
$ xmake
[100%]: build ok, spent 0.002s
```
升级 dev 后：
```bash
$ xmake 
error: ./xmake.lua:1: target(nil): invalid target name
error: ./xmake.lua:1: target(nil): invalid target name
```
不知为何 会 `error` 两次

修改参数正常后 正常输出：
```bash
$ xmake
[ 25%]: cache compiling.release xxx.c
[ 50%]: archiving.release xxx.a
[100%]: build ok, spent 0.189s
```
