### ISSUE TITLE
2.8.6 protobuf编译错误,提示没有头文件

### ISSUE THREAD

**Issue by gooker** [xmake-io/xmake#4549]
### Xmake 版本

2.8.6

### 操作系统版本和架构

centos7.8

### 描述问题

xmake.lua类似如下,之前版本都好用,现在会提示
error: xxxxx.h:7:10: fatal error: xxx.pb.h: 没有那个文件或目录
    7 | #include "xxx.pb.h"

### 期待的结果

可以正常编译protobuf

### 工程配置

add_rules("mode.debug", "mode.release")
set_languages("c99", "c++20")

target("xxx")
    set_kind("binary")
    add_files("*.cpp","*/*.cpp","*/*.cc","*/*.c")
    add_files("proto/wcs_com.proto","proto/bat_manage_com.proto","proto/mon_tools.proto",{rules = "protobuf.cpp"})
    add_links("protobuf","grpc++","grpc","address_sorting","re2","upb","cares","z","gpr","absl_statusor","absl_raw_hash_set","absl_hash","absl_hashtablez_sampler","absl_city","absl_low_level_hash","absl_random_distributions","absl_random_seed_sequences","absl_random_internal_pool_urbg","absl_random_internal_randen","absl_random_seed_gen_exception","absl_random_internal_randen_hwaes","absl_random_internal_randen_slow","absl_random_internal_randen_hwaes_impl","absl_random_internal_platform","absl_random_internal_seed_material","absl_status","absl_cord","absl_strerror","absl_cordz_info","absl_cord_internal","absl_cordz_functions","absl_cordz_handle","absl_exponential_biased","absl_synchronization","absl_bad_optional_access","absl_str_format_internal","absl_graphcycles_internal","absl_stacktrace","absl_symbolize","absl_time","absl_debugging_internal","absl_demangle_internal","absl_malloc_internal","absl_civil_time","absl_strings","absl_time_zone","absl_strings_internal","absl_int128","absl_throw_delegate","rt","absl_base","absl_spinlock_wait","absl_bad_variant_access","absl_raw_logging_internal","absl_log_severity")
    add_syslinks("pthread")

### 附加信息和错误日志

error: xxxxx.h:7:10: fatal error: xxx.pb.h: 没有那个文件或目录
    7 | #include "xxx.pb.h"

**Comment by waruqi** [comment]
写法不对，仔细看文档：https://xmake.io/#/zh-cn/guide/project_examples?id=%e4%bd%bf%e7%94%a8c%e5%ba%93-1

**Comment by gooker** [comment]
> 写法不对，仔细看文档：https://xmake.io/#/zh-cn/guide/project_examples?id=%e4%bd%bf%e7%94%a8c%e5%ba%93-1

用了挺久的之前一直正常, 新版配置protobuf有改变?

**Comment by waruqi** [comment]
rules 不要放 add_files 里
