### ISSUE TITLE
windows下内置变量中的目录用于add_defines的时候\\会丢失

### ISSUE THREAD

**Issue by supf1994** [xmake-io/xmake#4550]
### Xmake 版本

2.8.5

### 操作系统版本和架构

windows10 

### 描述问题

使用如下代码添加一个宏定义 add_defines("QML_SOURCE_DIR=\"$(scriptdir)\"")， 在C++代码中将  QML_SOURCE_DIR 打印出来得到的结果是  
![image](https://github.com/xmake-io/xmake/assets/23397492/23fc8981-1f95-4d24-b06d-740800bd5505)

反斜杠被转义掉了，有什么办法能解决吗

### 期待的结果

有没有什么函数可以先将内置变量转为字符串，再自己手动处理

### 工程配置

...

### 附加信息和错误日志

...

**Comment by waruqi** [comment]
os.scriptdir()
