### ISSUE TITLE
after_build doesn't work as expected in vs proj while vsxmake proj works fine

### ISSUE THREAD

**Issue by Kethers** [xmake-io/xmake#4553]
### Xmake Version

v2.8.6+dev.da3b723be

### Operating System Version and Architecture

Windows11 22H2 22621.2861

### Describe Bug

It's usual to copy some third-party binary libs to targetdir for linking. We usually do it in after_build via os.cp("dir/xxx.lib", target:targetdir()). 
When generating vs2022 project via below cmd, build the solution and run, only to find that the third-party binaries are not copied. This only happens for vs project generator, vsxmake works fine.
`xmake project -k vs2022`

### Expected Behavior

[CppTest.zip](https://github.com/xmake-io/xmake/files/13793022/CppTest.zip)

vs2022 without something.txt after build:
![image](https://github.com/xmake-io/xmake/assets/49612587/6834f0db-a1bb-4f39-b56c-81430bffa60b)

vsxmake with something.txt after build:
![image](https://github.com/xmake-io/xmake/assets/49612587/51aea2f6-a296-4837-ba41-f4ffbc393cfe)

### Project Configuration

```Lua
set_project("CppTest")

add_rules("mode.debug", "mode.release")

set_allowedarchs("x64")
set_allowedplats("windows")
set_allowedmodes("debug", "release")

target("MyLib")
	set_kind("static")
	add_files("MyLib/**.cpp")

target("MyBin")
	add_deps("MyLib")
	set_kind("binary")
	add_includedirs("MyLib")
	add_files("MyBin/**.cpp")
	after_build(function (target)
		os.cp("SomeAfterBuildFiles/something.txt", target:targetdir())
	end)
```

### Additional Information and Error Logs

None.

**Comment by waruqi** [comment]
vs proj generator cannot support after_build. you can use after_buildcmd instead of it.
