### ISSUE TITLE
构建android  so 出错

### ISSUE THREAD

**Issue by liuritian** [xmake-io/xmake#456]
### 描述问题详情
请在这描述你的问题详情。
[root@localhost hello]# xmake --verbose --root
configure
{
    ndk_sdkver = 28
    arch = armv7-a
    sh = arm-linux-androideabi-g++
    bin = /usr/workspace/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin
    ndk = /usr/workspace/android-ndk-r17c/
    mode = release
    ndk_stdcxx = true
    plat = android
    cross = arm-linux-androideabi-
    ccache = true
    kind = static
    buildir = build
    ndk_toolchains_ver = 4.9
    gcc_toolchain = /usr/workspace/android-ndk-r17c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64
    host = linux
}
[ 50%]: linking.release liblibrary.so
arm-linux-androideabi-g++ -o build/android/armv7-a/release/liblibrary.so -shared -fPIC -llog -mthumb -target armv7-none-linux-androideabi -gcc-toolchain /usr/workspace/android-ndk-r17c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot=/usr/workspace/android-ndk-r17c/platforms/android-28/arch-arm -L/usr/workspace/android-ndk-r17c/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -lc++_static -lc++abi
error: runv(arm-linux-androideabi-g++ -o build/android/armv7-a/release/liblibrary.so -shared -fPIC -llog -mthumb -target armv7-none-linux-androideabi -gcc-toolchain /usr/workspace/android-ndk-r17c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot=/usr/workspace/android-ndk-r17c/platforms/android-28/arch-arm -L/usr/workspace/android-ndk-r17c/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -lc++_static -lc++abi) failed(127)!
构建动态库  xmake 执行之后报错   该如何解决

**Comment by waruqi** [comment]
请提供xmake版本信息

**Comment by liuritian** [comment]
[root@localhost hello]# xmake update --root
xmake v2.2.6 has been installed!

**Comment by liuritian** [comment]
[root@localhost hello]# xmake f -p android --ndk=/usr/workspace/android-ndk-r17c/ --sh=arm-linux-androideabi-g++ --root
 我得xmake 设置

**Comment by liuritian** [comment]
[root@localhost hello]# xmake f -p android --ndk=/usr/workspace/android-ndk-r17c/ --sh=arm-linux-androideabi-g++ --root



xmake .lua内容

-- add modes: debug and release 
add_rules("mode.debug", "mode.release")


target("library")
    set_kind("shared")
-- add target
target("hello")

    -- set kind
    set_kind("binary")

    -- add files
    add_files("src/*.c")

    add_deps("library")

**Comment by waruqi** [comment]
为什么要手动指定 --sh=arm-linux-androideabi-g++？ 默认的sh不行么？ 你要指定 也得指定 全路径

**Comment by liuritian** [comment]
,,, 我是个新手,,我是照着官网教程操作得 不好意思,,,我这就去尝试一下

**Comment by liuritian** [comment]
默认得sh 不行,,告诉我找不到sh参数

**Comment by liuritian** [comment]
[root@localhost hello]# xmake f -p android --ndk=/usr/workspace/android-ndk-r17c/ -a arm64-v8a --bin=/usr/workspace/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/ --sh=/usr/workspace/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-g++ --cc=/usr/workspace/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc --root
[root@localhost hello]# xmake --verbose --root
configure
{
    ndk_sdkver = 28
    arch = arm64-v8a
    sh = /usr/workspace/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-g++
    plat = android
    cc = /usr/workspace/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc
    ndk = /usr/workspace/android-ndk-r17c/
    mode = release
    ndk_stdcxx = true
    host = linux
    cross = aarch64-linux-android-
    bin = /usr/workspace/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/
    kind = static
    buildir = build
    ndk_toolchains_ver = 4.9
    gcc_toolchain = /usr/workspace/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64
    ccache = true
}
[ 50%]: compiling.release src/main.c
/usr/workspace/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc -c -fvisibility=hidden -O3 -fPIE -pie --sysroot=/usr/workspace/android-ndk-r17c/sysroot -isystem /usr/workspace/android-ndk-r17c/sysroot/usr/include/aarch64-linux-android -march=arm64-v8a -D__ANDROID_API__=28 -o build/.objs/hello/android/arm64-v8a/release/src/main.c.o src/main.c
error: src/main.c:1:0: error: unknown value 'arm64-v8a' for -march
 int add(int,int);
 ^
找不到这个arm64-v8a ,,,,,

**Comment by liuritian** [comment]
尝试了半天 一直没有成功也没有什么头绪.

**Comment by waruqi** [comment]
不需要设置什么，一切默认就行了，我这可以：

```console
ruki:test6 ruki$ xmake f -p android --ndk=~/Downloads/android-ndk-r17c
checking for the architecture ... armv7-a
checking for the NDK directory ... /Users/ruki/Downloads/android-ndk-r17c
checking for the SDK version of NDK ... 28
checking for the toolchains version of NDK ... 4.9
checking for the Android SDK directory ... ~/Library/Android/sdk
checking for the Build Tools Version of Android SDK ... 28.0.3
ruki:test6 ruki$ xmake -r -v
configure
{
    sh = /Users/ruki/Downloads/android-ndk-r17c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
    ndk = ~/Downloads/android-ndk-r17c
    ndk_stdcxx = true
    host = macosx
    sdk = ~/Library/Android/sdk
    buildir = build
    ndk_toolchains_ver = 4.9
    ndk_sdkver = 28
    arch = armv7-a
    build_toolver = 28.0.3
    mode = release
    ccache = true
    bin = /Users/ruki/Downloads/android-ndk-r17c/toolchains/llvm/prebuilt/darwin-x86_64/bin
    ld = /Users/ruki/Downloads/android-ndk-r17c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
    kind = static
    cross = arm-linux-androideabi-
    android_sdk = ~/Library/Android/sdk
    plat = android
    gcc_toolchain = /Users/ruki/Downloads/android-ndk-r17c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64
}
checking for the c compiler (cc: gcc) ... no
checking for the c compiler (cc) ... clang
checking for the ccache ... /usr/local/bin/ccache
checking for the /Users/ruki/Downloads/android-ndk-r17c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang ... ok
checking for the flags (-O3) ... ok
[  0%]: ccache compiling.release src/interface.c
/usr/local/bin/ccache /Users/ruki/Downloads/android-ndk-r17c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -c -O3 --sysroot=/Users/ruki/Downloads/android-ndk-r17c/sysroot -isystem /Users/ruki/Downloads/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -Qunused-arguments -mthumb -target armv7-none-linux-androideabi -gcc-toolchain /Users/ruki/Downloads/android-ndk-r17c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 -D__ANDROID_API__=28 -fPIC -o build/.objs/test6/android/armv7-a/release/src/interface.c.o src/interface.c
checking for the flags (-MMD -MF /dev/null) ... ok
[ 50%]: linking.release libtest6.so
/Users/ruki/Downloads/android-ndk-r17c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -o build/android/armv7-a/release/libtest6.so build/.objs/test6/android/armv7-a/release/src/interface.c.o -s -shared -fPIC -llog -mthumb -target armv7-none-linux-androideabi -gcc-toolchain /Users/ruki/Downloads/android-ndk-r17c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/ruki/Downloads/android-ndk-r17c/platforms/android-28/arch-arm -L/Users/ruki/Downloads/android-ndk-r17c/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -lc++_static -lc++abi
[ 50%]: ccache compiling.release src/test.c
/usr/local/bin/ccache /Users/ruki/Downloads/android-ndk-r17c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -c -fvisibility=hidden -O3 -fPIE -pie --sysroot=/Users/ruki/Downloads/android-ndk-r17c/sysroot -isystem /Users/ruki/Downloads/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -Qunused-arguments -mthumb -target armv7-none-linux-androideabi -gcc-toolchain /Users/ruki/Downloads/android-ndk-r17c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 -D__ANDROID_API__=28 -o build/.objs/test6_demo/android/armv7-a/release/src/test.c.o src/test.c
checking for the flags (-Wl,-rpath=@loader_path) ... ok
[100%]: linking.release test6_demo
/Users/ruki/Downloads/android-ndk-r17c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -o build/android/armv7-a/release/test6_demo build/.objs/test6_demo/android/armv7-a/release/src/test.c.o -Lbuild/android/armv7-a/release -Wl,-rpath=$ORIGIN -s -fvisibility=hidden -ltest6 -llog -mthumb -target armv7-none-linux-androideabi -gcc-toolchain /Users/ruki/Downloads/android-ndk-r17c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/ruki/Downloads/android-ndk-r17c/platforms/android-28/arch-arm -fPIE -pie -L/Users/ruki/Downloads/android-ndk-r17c/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -lc++_static -lc++abi
build ok!👌
```

你追加-c清掉老的cache配置再试下：

```console
xmake f -p android --ndk=~/Downloads/android-ndk-r17c -c
```

而且你这个xmake.lua写的也不对，target library下面 都没有添加源码。。

```lua
-- add modes: debug and release
add_rules("mode.debug", "mode.release")

target("library")
set_kind("shared")    ------- 空target，没有需要编译的源文件
-- add target
target("hello")

-- set kind
set_kind("binary")

-- add files
add_files("src/*.c")

add_deps("library")
```

**Comment by waruqi** [comment]
你可以创建个空工程试下：

```console
xmake create -t shared test
cd test
xmake f -p android --ndk=~/Downloads/android-ndk-r17c -c
xmake
```

**Comment by liuritian** [comment]
root@localhost workspace]# xmake -r -v --root
configure
{
    ld = /usr/workspace/toolchain/bin/arm-linux-androideabi-gcc
    ndk = /usr/workspace/android-ndk-r17c/
    ndk_stdcxx = true
    plat = android
    buildir = build
    ndk_toolchains_ver = 4.9
    ndk_sdkver = 28
    arch = armv7-a
    gcc_toolchain = /usr/workspace/android-ndk-r17c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64
    mode = release
    host = linux
    cross = arm-linux-androideabi-
    bin = /usr/workspace/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin
    kind = static
    ccache = true
    sh = /usr/workspace/toolchain/bin/arm-linux-androideabi-gcc
    clean = true
}
checking for the c compiler (cc) ... arm-linux-androideabi-gcc
checking for the ccache ... no
checking for the /usr/workspace/toolchain/bin/arm-linux-androideabi-gcc ... ok
checking for the flags (-O3) ... ok
[  0%]: compiling.release src/interface.c
/usr/workspace/toolchain/bin/arm-linux-androideabi-gcc -c -O3 --sysroot=/usr/workspace/android-ndk-r17c/sysroot -isystem /usr/workspace/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -mthumb -target armv7-none-linux-androideabi -gcc-toolchain /usr/workspace/android-ndk-r17c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -D__ANDROID_API__=28 -fPIC -o build/.objs/workspace/android/armv7-a/release/src/interface.c.o src/interface.c
checking for the flags (-MMD -MF /dev/null) ... no
error: arm-linux-androideabi-gcc: error: armv7-none-linux-androideabi: No such file or directory
arm-linux-androideabi-gcc: error: unrecognized command line option '-target'

可能是因为ndk 坏境得问题,,,照着你得步骤 创建还是这样   
其实我想创建一个so库 供android 使用, 这样的话我得源文件可能就没有main函数了

**Comment by liuritian** [comment]
这个android 得sdk路径是必须要配置得吗

**Comment by liuritian** [comment]
你得ndk 设置了什么吗 ,我只是简单得设置了一些环境变量
    export PATH=$PATH:`pwd`/my-toolchain/bin
    target_host=aarch64-linux-android
    export AR=$target_host-ar
    export AS=$target_host-clang
    export CC=$target_host-clang
    export CXX=$target_host-clang++
    export LD=$target_host-ld
    export STRIP=$target_host-strip
    export CFLAGS="-fPIE -fPIC"
    export LDFLAGS="-pie"

**Comment by waruqi** [comment]
> 其实我想创建一个so库 供android 使用, 这样的话我得源文件可能就没有main函数了

android so原本就没main函数的。。为啥要main?

**Comment by waruqi** [comment]
> 这个android 得sdk路径是必须要配置得吗

sdk不需要，只要ndk

**Comment by waruqi** [comment]
> 你得ndk 设置了什么吗 ,我只是简单得设置了一些环境变量
> export PATH=$PATH:`pwd`/my-toolchain/bin
> target_host=aarch64-linux-android
> export AR=$target_host-ar
> export AS=$target_host-clang
> export CC=$target_host-clang
> export CXX=$target_host-clang++
> export LD=$target_host-ld
> export STRIP=$target_host-strip
> export CFLAGS="-fPIE -fPIC"
> export LDFLAGS="-pie"

不需要任何设置，从官方下载的ndk，解压直接使用就行了

**Comment by waruqi** [comment]
> 你得ndk 设置了什么吗 ,我只是简单得设置了一些环境变量
> export PATH=$PATH:`pwd`/my-toolchain/bin
> target_host=aarch64-linux-android
> export AR=$target_host-ar
> export AS=$target_host-clang
> export CC=$target_host-clang
> export CXX=$target_host-clang++
> export LD=$target_host-ld
> export STRIP=$target_host-strip
> export CFLAGS="-fPIE -fPIC"
> export LDFLAGS="-pie"

这些env都不要设置，设置的不好反而会有干扰。

**Comment by liuritian** [comment]
我也是这样得 官方下载 直接unzip 解压,    是得,,我想编译一个so  给我自己android 程序使用,  
但是 出现错误了, 暂时不知道哪里有问题

**Comment by liuritian** [comment]
> 
> 
> > 你得ndk 设置了什么吗 ,我只是简单得设置了一些环境变量
> > export PATH=$PATH:`pwd`/my-toolchain/bin
> > target_host=aarch64-linux-android
> > export AR=$target_host-ar
> > export AS=$target_host-clang
> > export CC=$target_host-clang
> > export CXX=$target_host-clang++
> > export LD=$target_host-ld
> > export STRIP=$target_host-strip
> > export CFLAGS="-fPIE -fPIC"
> > export LDFLAGS="-pie"
> 
> 这些env都不要设置，设置的不好反而会有干扰。

好的 我先去掉再来一下

**Comment by waruqi** [comment]
> error: arm-linux-androideabi-gcc: error: armv7-none-linux-androideabi: No such file or directory
> arm-linux-androideabi-gcc: error: unrecognized command line option '-target'

-target 参数不支持，你确定是r17c？ 你重新从官方源下载个r17c 试试呢。。或者下载更高版本 ndk试试。。。

记住，env的环境设置都先清掉，包括 $CC $LD这些

**Comment by liuritian** [comment]
> 
> 
> > error: arm-linux-androideabi-gcc: error: armv7-none-linux-androideabi: No such file or directory
> > arm-linux-androideabi-gcc: error: unrecognized command line option '-target'
> 
> -target 参数不支持，你确定是r17c？ 你重新从官方源下载个r17c 试试呢。。或者下载更高版本 ndk试试。。。
> 
> 记住，env的环境设置都先清掉，包括 $CC $LD这些

确定  我这里有更高版本得ndk 我先去去掉尝试一下 高版本

**Comment by liuritian** [comment]
> 
> 
> 这个也不要设置，export PATH=$PATH:pwd/my-toolchain/bin
> 
> xmake f -p android --ndk=/usr/workspace/android-ndk-r17c 就行了，我看了你的配置，多半就是被你设置的env干扰了
> 
> ```
> ld = /usr/workspace/toolchain/bin/arm-linux-androideabi-gcc
> ndk = /usr/workspace/android-ndk-r17c/
> bin = /usr/workspace/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin
> sh = /usr/workspace/toolchain/bin/arm-linux-androideabi-gcc
> ```
> 
> 这是你用xmake刚检测到配置，bin在 `/usr/workspace/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin`
> 
> 用的却是 `/usr/workspace/toolchain/bin` 跟本就没用你的 ndk r17c啊，全部用的 /usr/workspace/toolchain 你这个目录下 的 bin 当然会有问题了
更换高版本可以成功编译了,, 目前看来确实是 因为环境变量设置得问题,,非常感谢,,
