### ISSUE TITLE
xmake 多实例 debug 时端口占用

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#4560]
### Xmake 版本

xmake v2.8.5

### 操作系统版本和架构

Linux 720ce3a659a2 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

在 xmake 源码调试时，如果启动了额外的 xmake 实例会报错，因为它们都会 bind 9966 端口。

### 期待的结果

新起实例的时候绑定其他的端口，避免端口冲突。

### 工程配置

无

### 附加信息和错误日志

![image](https://github.com/xmake-io/xmake/assets/47598093/c0f71c43-506b-4a7a-be0b-dbb068001fbc)

**Comment by waruqi** [comment]
这个没办法，调试用的第三方 lua 插件，只能访问 9966 端口，除非你提 issues 给这个插件，让它支持多端口配置。

**Comment by TOMO-CAT** [comment]
> 这个没办法，调试用的第三方 lua 插件，只能访问 9966 端口，除非你提 issues 给这个插件，让它支持多端口配置。

好的暂时通过取巧的方式解决了，多谢
