### ISSUE TITLE
windows平台下使用llvm工具链安装nlohmann_json出现不支持c++14扩展的报错

### ISSUE THREAD

**Issue by Arama-Vanarana** [xmake-io/xmake#4566]
### Xmake 版本

2.8.6+HEAD.211710b67

### 操作系统版本和架构

版本	Windows 11 专业版 版本	23H2 安装日期	‎2024/‎1/‎3 操作系统版本	22631.2861 体验	Windows Feature Experience Pack 1000.22681.1000.0

### 描述问题

使用MSVC时不会出现此问题, 一旦切换至LLVM工具链就出现了:(

### 期待的结果

能够正常安装

### 工程配置

add_rules("mode.debug", "mode.releasedbg", "mode.release", "mode.minsizerel")
add_languages("cxx17", "c17")

add_requires(
    "libcurl",
    "openssl3",
    "nlohmann_json"
)

add_packages("nlohmann_json")

target("lib")
    set_kind("$(kind)")
    add_headerfiles("lib/*.hpp")
    add_files("lib/**.cpp")
    add_packages("libcurl")
    add_packages("openssl3")
    on_load(
        function (target)
            if is_mode("debug", "releasedbg") then
                target:set("kind", "shared")
                if is_plat("windows") then
                    import("core.project.rule")
                    local rule = rule.rule("utils.symbols.export_all")
                    target:rule_add(rule)
                    target:extraconf_set("rules", "utils.symbols.export_all", {export_classes = true})
                end
            elseif is_mode("release") then
                target:set("kind", "static")
            else
                assert(false, "Unknown build kind")
            end
        end
    )
target_end()

if is_mode("debug", "releasedbg") then 
    target("test")
        set_kind("binary")
        add_files("test.cpp")
        add_deps("lib")
    target_end()
    add_defines("DEBUG")
end

target("main")
    set_kind("binary")
    add_deps("lib")
    add_files("main.cpp")
target_end()

### 附加信息和错误日志

PS D:\MyC++> xmake f -p windows -a x64 -m debug -y -vD --sdk=D:\Scoop\apps\llvm\current --toolchain=llvm 
checkinfo: cannot runv(unzip.exe -v), No such file or directory
checking for unzip ... no
checking for 7z ... D:\Scoop\apps\xmake\current\winenv\bin\7z
checking for git ... ok
checkinfo: cannot runv(gzip.exe --version), No such file or directory
checking for gzip ... no
git rev-parse HEAD
checking for cmake ... no
checking for cl.exe ... D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for cmake ... no
checking for cmake ... no
finding libcurl from xmake ..
checking for xmake::libcurl ... libcurl 8.5.0
checking for nasm ... no
checking for perl ... no
checking for strawberry-perl ... no
finding openssl3 from xmake ..
checking for xmake::openssl3 ... openssl3 3.0.7
finding nlohmann_json from xmake ..
checking for xmake::nlohmann_json ... no
finding nlohmann_json from vcpkg ..
finding nlohmann_json from conan ..
finding nlohmann_json from pkgconfig ..
checkinfo: cannot runv(pkg-config.exe --version), No such file or directory
checking for pkg-config ... no
checkinfo: cannot runv(pkgconf.exe --version), No such file or directory
checking for pkgconf ... no
finding nlohmann_json from system ..
checking for nlohmann_json ... no
checking for ping ... ok
pinging the host(github.com) ... 1 ms
D:\Scoop\apps\xmake\current\winenv\bin\7z x -y v3.11.3.tar.gz -oC:\Users\Arama\AppData\Local\Temp\.xmake\240104\_2EBD4DD656FD432089C350C71E621050.tar

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 8053705 bytes (7865 KiB)

Extracting archive: v3.11.3.tar.gz
--
Path = v3.11.3.tar.gz
Type = gzip
Headers Size = 10

Everything is Ok  

Size:       14899200
Compressed: 8053705
D:\Scoop\apps\xmake\current\winenv\bin\7z x -y C:\Users\Arama\AppData\Local\Temp\.xmake\240104\_2EBD4DD656FD432089C350C71E621050.tar\v3.11.3.tar -osource.tmp

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 14899200 bytes (15 MiB)

Extracting archive: C:\Users\Arama\AppData\Local\Temp\.xmake\240104\_2EBD4DD656FD432089C350C71E621050.tar\v3.11.3.tar
--
Path = C:\Users\Arama\AppData\Local\Temp\.xmake\240104\_2EBD4DD656FD432089C350C71E621050.tar\v3.11.3.tar
Type = tar
Physical Size = 14899200
Headers Size = 613888
Code Page = UTF-8

Everything is Ok

Folders: 93
Files: 1091
Size:       13968176
Compressed: 14899200
finding nlohmann_json from xmake ..
checking for xmake::nlohmann_json ... nlohmann_json v3.11.3
{
  sysincludedirs = {
    "C:\Users\Arama\AppData\Local\.xmake\packages\n\nlohmann_json\v3.11.3\763ee9118896452a949037ba6c7b8b6f\include"
  },
  license = "MIT",
  version = "v3.11.3"
}

patching C:\Users\Arama\AppData\Local\.xmake\packages\n\nlohmann_json\v3.11.3\763ee9118896452a949037ba6c7b8b6f\lib\pkgconfig\nlohmann_json.pc ..
checking for clang++ ... D:\Scoop\apps\llvm\current\bin\clang++
checking for the linker (ld) ... clang++
checking for clang ... D:\Scoop\apps\llvm\current\bin\clang
checking for the c++ compiler (cxx) ... clang
> D:\Scoop\apps\llvm\current\bin\clang -c -Qunused-arguments -m64 -std=c++11 -isystem C:\Users\Arama\AppData\Local\.xmake\packages\n\nlohmann_json\v3.11.3\763ee9118896452a949037ba6c7b8b6f\include -o C:\Users\Arama\AppData\Local\Temp\.xmake\240104\_692F9AAE0FCF417083BEF8E0B09FF5A0.o C:\Users\Arama\AppData\Local\Temp\.xmake\240104\_28C57B3B5C4C4E77B26DA862EF4957F4.cpp
checking for D:\Scoop\apps\llvm\current\bin\clang ... ok
checking for flags (-fdiagnostics-color=always) ... ok
> clang "-fdiagnostics-color=always" "-Qunused-arguments" "-m64"
> checking for c++ includes(nlohmann/json.hpp)
> checking for c++ snippet(test)
checkinfo: ...amdir\core\sandbox\modules\import\core\tool\compiler.lua:84: @programdir\modules\core\tools\gcc.lua:841: In file included from C:\Users\Arama\AppData\Local\Temp\.xmake\240104\_28C57B3B5C4C4E77B26DA862EF4957F4.cpp:2:
In file included from C:\Users\Arama\AppData\Local\.xmake\packages\n\nlohmann_json\v3.11.3\763ee9118896452a949037ba6c7b8b6f\include\nlohmann/json.hpp:21:
In file included from D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\algorithm:10:
In file included from D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xmemory:15:
In file included from D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:11:
In file included from D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\__msvc_iter_core.hpp:10:
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\utility:162:22: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
  162 | _NODISCARD constexpr auto&& _Tuple_get(tuple<_Types...>&& _Tuple) noexcept;
      |                      ^
In file included from C:\Users\Arama\AppData\Local\Temp\.xmake\240104\_28C57B3B5C4C4E77B26DA862EF4957F4.cpp:2:
In file included from C:\Users\Arama\AppData\Local\.xmake\packages\n\nlohmann_json\v3.11.3\763ee9118896452a949037ba6c7b8b6f\include\nlohmann/json.hpp:21:
In file included from D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\algorithm:10:
In file included from D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xmemory:15:
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:544:15: error: deduced return types are a C++14 extension
  544 |     constexpr decltype(auto) operator()(_Args&&... _Vals) { // forward function call operator
      |               ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:556:22: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
  556 | _NODISCARD constexpr auto _Pass_fn(_Fn& _Func) noexcept {
      |                      ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:1152:16: error: constexpr function's return type 'void' is not a literal type
 1152 | constexpr void _Adl_verify_range(const _Iter& _First, const _Sentinel& _Last) {
      |                ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:1174:22: error: deduced return types are a C++14 extension
 1174 | _NODISCARD constexpr decltype(auto) _Get_unwrapped(_Iter&& _It) noexcept(
      |                      ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:1202:22: error: deduced return types are a C++14 extension
 1202 | _NODISCARD constexpr decltype(auto) _Get_unwrapped_unverified(_Iter&& _It) {
      |                      ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:1241:22: error: deduced return types are a C++14 extension
 1241 | _NODISCARD constexpr decltype(auto) _Get_unwrapped_n(_Iter&& _It, const _Diff _Off) {
      |                      ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:1275:16: error: constexpr function's return type 'void' is not a literal type
 1275 | constexpr void _Seek_wrapped(_Iter& _It, _UIter&& _UIt) {
      |                ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:1336:22: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
 1336 | _NODISCARD constexpr auto _Idl_distance(const _Iter& _First, const _Iter& _Last) {
      |                      ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:1341:16: error: no viable conversion from returned value of type '_Distance_unknown' to function return type 'int'  
 1341 |         return _Distance_unknown{};
      |                ^~~~~~~~~~~~~~~~~~~
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:1637:27: error: constexpr function's return type 'void' is not a literal type
 1637 |     friend constexpr void _Verify_range(
      |                           ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:1643:20: error: constexpr function's return type 'void' is not a literal type
 1643 |     constexpr void _Verify_offset(const difference_type _Off) const noexcept {
      |                    ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:1662:20: error: constexpr function's return type 'void' is not a literal type
 1662 |     constexpr void _Seek_to(const reverse_iterator<_Src>& _It) noexcept(noexcept(current._Seek_to(_It.current))) {
      |                    ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:4094:18: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
 4094 |     _CONSTEXPR17 auto operator++(int) noexcept(
      |                  ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:4198:27: error: constexpr function's return type 'void' is not a literal type
 4198 |     friend constexpr void _Verify_range(const move_iterator& _First, const move_iterator<_Iter2>& _Last) noexcept {
      |                           ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:4211:20: error: constexpr function's return type 'void' is not a literal type
 4211 |     constexpr void _Verify_offset(const difference_type _Off) const noexcept {
      |                    ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:4229:20: error: constexpr function's return type 'void' is not a literal type
 4229 |     constexpr void _Seek_to(const move_iterator<_Src>& _It) noexcept(noexcept(_Current._Seek_to(_It._Get_current()))) {
      |                    ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:4233:20: error: constexpr function's return type 'void' is not a literal type
 4233 |     constexpr void _Seek_to(move_iterator<_Src>&& _It) noexcept(
      |                    ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:4391:22: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
 4391 | _NODISCARD constexpr auto _To_address(const _Iter& _Val) noexcept {
      |                      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:949]:
    [@programdir\modules\core\tools\gcc.lua:841]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [@programdir\modules\core\tools\gcc.lua:782]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\tool\compiler.lua:278]: in function 'compile'
    [...amdir\core\sandbox\modules\import\core\tool\compiler.lua:82]: in function 'compile'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:242]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:236]:
    [...positories\xmake-repo\packages\n\nlohmann_json\xmake.lua:45]: in function 'script'
    [...dir\modules\private\action\require\impl\utils\filter.lua:114]: in function 'call'
    [...dir\modules\private\action\require\impl\actions\test.lua:41]:
    [...\modules\private\action\require\impl\actions\install.lua:412]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:333]:
    [...modules\private\action\require\impl\install_packages.lua:479]: in function 'jobfunc'
    [@programdir\modules\async\runjobs.lua:237]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [@programdir\modules\async\runjobs.lua:220]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:404]:

error: ...positories\xmake-repo\packages\n\nlohmann_json\xmake.lua:45: ...amdir\core\sandbox\modules\import\core\tool\compiler.lua:84: @programdir\modules\core\tools\gcc.lua:841: In file included from C:\Users\Arama\AppData\Local\Temp\.xmake\240104\_28C57B3B5C4C4E77B26DA862EF4957F4.cpp:2:
In file included from C:\Users\Arama\AppData\Local\.xmake\packages\n\nlohmann_json\v3.11.3\763ee9118896452a949037ba6c7b8b6f\include\nlohmann/json.hpp:21:
In file included from D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\algorithm:10:
In file included from D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xmemory:15:
In file included from D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:11:
In file included from D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\__msvc_iter_core.hpp:10:
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\utility:162:22: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
  162 | _NODISCARD constexpr auto&& _Tuple_get(tuple<_Types...>&& _Tuple) noexcept;
      |                      ^
In file included from C:\Users\Arama\AppData\Local\Temp\.xmake\240104\_28C57B3B5C4C4E77B26DA862EF4957F4.cpp:2:
In file included from C:\Users\Arama\AppData\Local\.xmake\packages\n\nlohmann_json\v3.11.3\763ee9118896452a949037ba6c7b8b6f\include\nlohmann/json.hpp:21:
In file included from D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\algorithm:10:
In file included from D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xmemory:15:
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:544:15: error: deduced return types are a C++14 extension
  544 |     constexpr decltype(auto) operator()(_Args&&... _Vals) { // forward function call operator
      |               ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:556:22: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
  556 | _NODISCARD constexpr auto _Pass_fn(_Fn& _Func) noexcept {
      |                      ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:1152:16: error: constexpr function's return type 'void' is not a literal type
 1152 | constexpr void _Adl_verify_range(const _Iter& _First, const _Sentinel& _Last) {
      |                ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:1174:22: error: deduced return types are a C++14 extension
 1174 | _NODISCARD constexpr decltype(auto) _Get_unwrapped(_Iter&& _It) noexcept(
      |                      ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:1202:22: error: deduced return types are a C++14 extension
 1202 | _NODISCARD constexpr decltype(auto) _Get_unwrapped_unverified(_Iter&& _It) {
      |                      ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:1241:22: error: deduced return types are a C++14 extension
 1241 | _NODISCARD constexpr decltype(auto) _Get_unwrapped_n(_Iter&& _It, const _Diff _Off) {
      |                      ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:1275:16: error: constexpr function's return type 'void' is not a literal type
 1275 | constexpr void _Seek_wrapped(_Iter& _It, _UIter&& _UIt) {
      |                ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:1336:22: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
 1336 | _NODISCARD constexpr auto _Idl_distance(const _Iter& _First, const _Iter& _Last) {
      |                      ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:1341:16: error: no viable conversion from returned value of type '_Distance_unknown' to function return type 'int'  
 1341 |         return _Distance_unknown{};
      |                ^~~~~~~~~~~~~~~~~~~
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:1637:27: error: constexpr function's return type 'void' is not a literal type
 1637 |     friend constexpr void _Verify_range(
      |                           ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:1643:20: error: constexpr function's return type 'void' is not a literal type
 1643 |     constexpr void _Verify_offset(const difference_type _Off) const noexcept {
      |                    ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:1662:20: error: constexpr function's return type 'void' is not a literal type
 1662 |     constexpr void _Seek_to(const reverse_iterator<_Src>& _It) noexcept(noexcept(current._Seek_to(_It.current))) {
      |                    ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:4094:18: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
 4094 |     _CONSTEXPR17 auto operator++(int) noexcept(
      |                  ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:4198:27: error: constexpr function's return type 'void' is not a literal type
 4198 |     friend constexpr void _Verify_range(const move_iterator& _First, const move_iterator<_Iter2>& _Last) noexcept {
      |                           ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:4211:20: error: constexpr function's return type 'void' is not a literal type
 4211 |     constexpr void _Verify_offset(const difference_type _Off) const noexcept {
      |                    ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:4229:20: error: constexpr function's return type 'void' is not a literal type
 4229 |     constexpr void _Seek_to(const move_iterator<_Src>& _It) noexcept(noexcept(_Current._Seek_to(_It._Get_current()))) {
      |                    ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:4233:20: error: constexpr function's return type 'void' is not a literal type
 4233 |     constexpr void _Seek_to(move_iterator<_Src>&& _It) noexcept(
      |                    ^
D:\Microsoft Visual Studio\BuildTools\VC\Tools\MSVC\14.38.33130\include\xutility:4391:22: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
 4391 | _NODISCARD constexpr auto _To_address(const _Iter& _Val) noexcept {
      |                      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:949]:
    [@programdir\modules\core\tools\gcc.lua:841]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [@programdir\modules\core\tools\gcc.lua:782]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\tool\compiler.lua:278]: in function 'compile'
    [...amdir\core\sandbox\modules\import\core\tool\compiler.lua:82]: in function 'compile'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:242]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:236]:
    [...positories\xmake-repo\packages\n\nlohmann_json\xmake.lua:45]: in function 'script'
    [...dir\modules\private\action\require\impl\utils\filter.lua:114]: in function 'call'
    [...dir\modules\private\action\require\impl\actions\test.lua:41]:
    [...\modules\private\action\require\impl\actions\install.lua:412]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:333]:
    [...modules\private\action\require\impl\install_packages.lua:479]: in function 'jobfunc'
    [@programdir\modules\async\runjobs.lua:237]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [@programdir\modules\async\runjobs.lua:220]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:404]:

  => install nlohmann_json v3.11.3 .. failed
error: @programdir\core\main.lua:314: @programdir\modules\async\runjobs.lua:320: ...\modules\private\action\require\impl\actions\install.lua:474: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:949]:
    [...\modules\private\action\require\impl\actions\install.lua:474]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:333]:
    [...modules\private\action\require\impl\install_packages.lua:479]: in function 'jobfunc'
    [@programdir\modules\async\runjobs.lua:237]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:949: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:314: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>

**Comment by Arama-Vanarana** [comment]
豪德明白了

**Comment by Arama-Vanarana** [comment]
PS D:\MyC++> xmake f -p cross -a x86_64 -m debug -y -v --sdk=D:\Scoop\apps\llvm\current --toolchain=llvm 
checking for unzip ... no
checking for 7z ... D:\Scoop\apps\xmake\current\winenv\bin\7z
checking for git ... ok
checking for gzip ... no
git rev-parse HEAD
checking for xmake::openssl ... no
checking for xmake::libcurl ... no
checking for xmake::openssl3 ... no
checking for xmake::nlohmann_json ... no
checking for ping ... ok
pinging the host(github.com) ... 1 ms
pinging the host(curl.haxx.se) ... 166 ms
pinging the host(curl.mirror.anstey.ca) ... 65535 ms
D:\Scoop\apps\xmake\current\winenv\bin\7z x -y OpenSSL_1_1_1w.zip -osource.tmp -xr@C:\Users\Arama\AppData\Local\Temp\.xmake\240104\_4ED8F0B266EB4D108E7D6CBF9C44B160

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 11885135 bytes (12 MiB)

Extracting archive: OpenSSL_1_1_1w.zip
--
Path = OpenSSL_1_1_1w.zip
Type = zip
Physical Size = 11885135
Comment = e04bd3433fd84e1861bf258ea37928d9845e6a86

Everything is Ok

Folders: 160
Files: 3084
Size:       41454421
Compressed: 11885135
checking for clang ... D:\Scoop\apps\llvm\current\bin\clang
checking for the c compiler (cc) ... clang
checking for D:\Scoop\apps\llvm\current\bin\clang ... ok
checking for flags (-fPIC) ... no
checking for clang ... D:\Scoop\apps\llvm\current\bin\clang
checking for the assember (as) ... clang
checking for flags (-fPIC) ... ok
checking for clang ... D:\Scoop\apps\llvm\current\bin\clang
checking for the c++ compiler (cxx) ... clang
checking for flags (-fPIC) ... no
checking for clang++ ... D:\Scoop\apps\llvm\current\bin\clang++
checking for the linker (ld) ... clang++
checking for D:\Scoop\apps\llvm\current\bin\clang++ ... ok
checking for flags (-fPIC) ... no
checking for clang++ ... D:\Scoop\apps\llvm\current\bin\clang++
checking for the shared library linker (sh) ... clang++
checking for flags (-fPIC) ... no
checking for llvm-ar ... D:\Scoop\apps\llvm\current\bin\llvm-ar
checking for the static library archiver (ar) ... llvm-ar
checking for clang -E ... D:\Scoop\apps\llvm\current\bin\clang -E
checking for the c/c++ preprocessor (cpp) ... clang -E
checking for llvm-ranlib ... D:\Scoop\apps\llvm\current\bin\llvm-ranlib
checking for unknown toolkind ranlib (ranlib) ... llvm-ranlib
./Configure linux-x86_64 -DOPENSSL_NO_HEARTBEATS no-shared no-threads --openssldir=C:\Users\Arama\AppData\Local\.xmake\packages\o\openssl\1.1.1-w\8ec33025d6534b90a98c264fad010921 --prefix=C:\Users\Arama\AppData\Local\.xmake\packages\o\openssl\1.1.1-w\8ec33025d6534b90a98c264fad010921
error: cannot execv(./Configure linux-x86_64 -DOPENSSL_NO_HEARTBEATS no-shared no-threads --openssldir=C:\Users\Arama\AppData\Local\.xmake\packages\o\openssl\1.1.1-w\8ec33025d6534b90a98c264fad010921 --prefix=C:\Users\Arama\AppData\Local\.xmake\packages\o\openssl\1.1.1-w\8ec33025d6534b90a98c264fad010921), Unknown Error (193)
  => install openssl 1.1.1-w .. failed
error: install failed!

**Comment by waruqi** [comment]
大部分包用了 Configure 和 autoconf 此类 shell 脚本来构建，你只能在 msys shell 环境下执行，纯 cmd/ps 环境是跑不起来的

**Comment by Arama-Vanarana** [comment]
好的
