### ISSUE TITLE
xmake更新 template 失效

### ISSUE THREAD

**Issue by 0329-at** [xmake-io/xmake#4570]
### Xmake 版本

xmake v2.8.6

### 操作系统版本和架构

ubuntu 22.04 LTS

### 描述问题

我尝试修改了usr/share/xmake/templates/c++/console/project/ 默认的模版配置
但是更新xmake 以后就不行了。

### 期待的结果

期待修复。

### 工程配置

add_rules("mode.debug", "mode.release")
set_warnings("everything")
set_optimize("aggressive")`
set_languages("clatest", "c++23")

add_requires("fast_io", "openmp","libomp", "semi-static-conditions", "sonic-cpp", "luajit", "boost", "fmtlog", "folly")

target("demo3")
    set_kind("binary")
    set_policy("build.c++.modules", true)
    add_shflags("/home/lan/wsl/mimalloc/build/libmimalloc.so.2.1")
    add_packages("fast_io", "folly")
    add_files("src/*.cpp")

### 附加信息和错误日志

更新以后生成的：

add_rules("mode.debug", "mode.release")

target("demo1")
    set_kind("binary")
    add_files("src/*.cpp")

**Comment by waruqi** [comment]
？？？这些安装文件原本就是不让改，你去硬改，更新后，当然会被覆盖了。。这又不是啥 bug
