### ISSUE TITLE
为set_pcheader添加选项，取消对强制包含的默认添加

### ISSUE THREAD

**Issue by RimuruChan** [xmake-io/xmake#4579]
### 你在什么场景下需要该功能？

当我们使用pch却不希望被强制包含造成作用域污染的时候，或者有时候可能忘记导入某些头文件，但作为库被下游使用的时候因为没有导入头文件而报错

### 描述可能的解决方案

添加一个配置选项来关闭强制包含

**Comment by waruqi** [comment]
win 上 msvc 去不掉，要使用 pch，就要加 `/Yuxxx.h` 这会导致源码中 `#include "xxx.h"` 被忽略，必须再显示加上 `/FIxxx.h` 去 force include 才能让预编译真正生效。。

而 gcc/clang 尽管可以去，但是这样不同编译器的预编译处理行为不一致了。 要么全一起去，要么全不去。。如果 msvc 无法去掉。 gcc/clang 下就不能去
