### ISSUE TITLE
xmake test 前一个测试失败导致后续测试都被标记为失败

### ISSUE THREAD

**Issue by x1244** [xmake-io/xmake#4582]
### Xmake 版本

2.8.5

### 操作系统版本和架构

Windows10 22H2 19045.2604

### 描述问题

运行xmake test，添加多个tests，当目标只包含main.cpp时没有问题，当目标包含main.cpp以外的cpp时，对于一系列测试用例，当某个测试用例失败后，导致后续的测试用例无论是否成功都被标记为失败。
工程里只包含了一个空的cpp文件，实际上包含非空的cpp也会导致一样的结果。

### 期待的结果

只对失败的测试用例标记失败，并正确统计失败的用例数量。

### 工程配置

add_rules("mode.debug", "mode.release")
add_requires("doctest")
target("runtest")
    set_kind("binary")
    add_files("src/main.cpp", "src/empty.cpp")
    add_tests("unit1", {
        packages = "doctest",
        remove_files = "src/main.cpp",
        defines = "DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN",
        files = "src/unit_1.cpp"
    })
    add_tests("unit2", {
        packages = "doctest",
        remove_files = "src/main.cpp",
        defines = "DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN",
        files = "src/unit_2.cpp"
    })
    add_tests("unit3", {
        packages = "doctest",
        remove_files = "src/main.cpp",
        defines = "DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN",
        files = "src/unit_3.cpp"
    })

### 附加信息和错误日志

测试用例统计
![001](https://github.com/xmake-io/xmake/assets/63945717/84eeca72-196e-4f29-b3c2-546bdd721ec6)
测试用例详细输出
```
PS D:\laboratory\runtest> xmake test -v
running tests ...
[ 33%]: runtest/unit1 .................................... passed 0.000s
[doctest] doctest version is "2.4.11"
[doctest] run with "--help" for options
===============================================================================
[doctest] test cases: 1 | 1 passed | 0 failed | 0 skipped
[doctest] assertions: 1 | 1 passed | 0 failed |
[doctest] Status: SUCCESS!

[ 66%]: runtest/unit2 .................................... failed 0.015s
[doctest] doctest version is "2.4.11"
[doctest] run with "--help" for options
===============================================================================
src\unit_2.cpp(3):
TEST CASE:  unit 2

src\unit_2.cpp(5): ERROR: CHECK( false ) is NOT correct!
  values: CHECK( false )

===============================================================================
[doctest] test cases: 2 | 1 passed | 1 failed | 0 skipped
[doctest] assertions: 2 | 1 passed | 1 failed |
[doctest] Status: FAILURE!

run failed, exit code: 1
[100%]: runtest/unit3 .................................... failed 0.000s
[doctest] doctest version is "2.4.11"
[doctest] run with "--help" for options
===============================================================================
src\unit_2.cpp(3):
TEST CASE:  unit 2

src\unit_2.cpp(5): ERROR: CHECK( false ) is NOT correct!
  values: CHECK( false )

===============================================================================
[doctest] test cases: 3 | 2 passed | 1 failed | 0 skipped
[doctest] assertions: 3 | 2 passed | 1 failed |
[doctest] Status: FAILURE!

run failed, exit code: 1

33% tests passed, 2 tests failed out of 3, spent 0.031s
```
从中可以看出测试用例2失败了，其实测试用例3是成功的，但输出被替换成了测试用例2的。
看最后doctest的统计结果是3个测试用例，过了2个，卡了一个，但xmake给出的结果是2个失败。

**Comment by waruqi** [comment]
给下完整测试工程

**Comment by x1244** [comment]
可复现工程在这里。
[runtest.zip](https://github.com/xmake-io/xmake/files/13872703/runtest.zip)

默认情况下编译，一切正常，只有unit2标识为failed
> xmake f -c 
> xmake test --rebuild

结果
running tests ...
[ 25%]: runtest/unit1 .................................... passed 0.016s
[ 50%]: runtest/unit2 .................................... failed 0.000s
[ 75%]: runtest/unit3 .................................... passed 0.015s
[100%]: runtest/unit4 .................................... passed 0.016s

添加一个空的cpp，结果不正常，unit2以后的用例都被标识为failed
> xmake f -c --withempty=y
> xmake test --rebuild

结果
running tests ...
[ 25%]: runtest/unit1 .................................... passed 0.015s
[ 50%]: runtest/unit2 .................................... failed 0.016s
[ 75%]: runtest/unit3 .................................... failed 0.016s
[100%]: runtest/unit4 .................................... failed 0.000s

去掉空的cpp，结果正常，只有unit2标识为failed
> xmake f -c --withempty=n
> xmake test --rebuild

添加一个简单的cpp，结果不正常，unit2以后的用例都被标识为failed
> xmake f -c --withsimple=y
> xmake test --rebuild

结果
running tests ...
[ 25%]: runtest/unit1 .................................... passed 0.015s
[ 50%]: runtest/unit2 .................................... failed 0.016s
[ 75%]: runtest/unit3 .................................... failed 0.016s
[100%]: runtest/unit4 .................................... failed 0.000s

去掉main.cpp以外的cpp，结果正常，只有unit2标识为failed
> xmake f -c --withsimple=n
> xmake test --rebuild

**Comment by waruqi** [comment]
再试试   xmake update -s dev

**Comment by x1244** [comment]
OK!
