### ISSUE TITLE
xmake is installed without the exe extension

### ISSUE THREAD

**Issue by Biswa96** [xmake-io/xmake#4585]
### Xmake Version

2.8.6

### Operating System Version and Architecture

Microsoft Windows Version 10.0.19045

### Describe Bug

`make install PREFIX="${pkgdir}${MINGW_PREFIX}"` command installs xmake without the exe extension. Here is the diff between list of files.

```diff
--- old.txt
+++ new.txt
@@ -1,6 +1,6 @@
 ucrt64/
 ucrt64/bin/
-ucrt64/bin/xmake.exe
+ucrt64/bin/xmake
 ucrt64/bin/xrepo
 ucrt64/share/
 ucrt64/share/licenses/
@@ -419,6 +419,8 @@
 ucrt64/share/xmake/includes/qt/
 ucrt64/share/xmake/includes/qt/qt_add_static_plugins.lua
 ucrt64/share/xmake/includes/qt/xmake.lua
+ucrt64/share/xmake/includes/xpack/
+ucrt64/share/xmake/includes/xpack/xmake.lua
 ucrt64/share/xmake/languages/
 ucrt64/share/xmake/languages/asm/
 ucrt64/share/xmake/languages/asm/load.lua
```

### Expected Behavior

xmake executable should be installed as xmake.exe.

### Project Configuration

The build procedure can be found here https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-xmake/PKGBUILD 

### Additional Information and Error Logs

N/A

**Comment by waruqi** [comment]
It's a shell file. see https://github.com/xmake-io/xmake/issues/3982

**Comment by Biswa96** [comment]
Oh, my apology, did not noticed it.
