### ISSUE TITLE
libsdl_ttf/freetype 无法正确安装

### ISSUE THREAD

**Issue by Caikera** [xmake-io/xmake#4586]
### Xmake 版本

2.8.6

### 操作系统版本和架构

Window 11 22H2

### 描述问题

其它sdl相关库似乎没有问题，安装 `libsdl2` 的依赖 `freetype` 时，无法正确编译。我选择的环境是 `msvc`，但是安装过程貌似引用了 `msys2` 中的头文件。

### 期待的结果

`libsdl2` 正确安装

### 工程配置

```
add_rules("mode.debug", "mode.release")
-- add_requires("libsdl_ttf")
add_requires("libsdl", "libsdl_image", "libsdl_ttf", "libsdl_mixer")

target("sdl_test_xmake")
    set_kind("binary")
    add_files("src/*.cpp", "src/sdl_bindings/*.cpp")
    add_includedirs("src/sdl_bindings")
    add_packages("libsdl", "libsdl_image", "libsdl_ttf", "libsdl_mixer")
    set_languages("c++23")
```

### 附加信息和错误日志

[install.txt](https://github.com/xmake-io/xmake/files/13863546/install.txt)

**Comment by waruqi** [comment]
既然用了 msvc ，就不要在 msys2 下执行，也不要将 msys2 相关的 path 设置到全局，并确认切到了 windows 平台编译，而不是 mingw/msys2

**Comment by Caikera** [comment]
谢谢，我确实是切到windows平台编译的。这个问题好像是因为MSYS2 UCRT在环境变量中导致的，删掉重启就正常了。
