### ISSUE TITLE
xmake-requires.lock使用变量指代main xrepo

### ISSUE THREAD

**Issue by darcy-shen** [xmake-io/xmake#4589]
### 你在什么场景下需要该功能？

在中国做开发，会使用gitee，然后生成的lock是gitee的。但是在github上面运行ci，从gitee clone仓库并不稳定。

+ https://gitee.com/tboox/xmake-repo.git
+ https://github.com/xmake-io/xmake-repo.git

然后手动替换也容易犯错，比如两者的组织名不一样，容易漏掉

### 描述可能的解决方案

使用变量指代这个默认仓库

**Comment by waruqi** [comment]
可以通过变量改 https://xmake.io/#/guide/configuration?id=xmake_main_repo
https://xmake.io/#/guide/configuration?id=xmake_binary_repo

**Comment by darcy-shen** [comment]
但是在lock里面是写死了某一个具体的git仓库吧，所以我的建议在lock里面使用环境变量，而不是具体的某一个仓库

**Comment by waruqi** [comment]
> 但是在lock里面是写死了某一个具体的git仓库吧，所以我的建议在lock里面使用环境变量，而不是具体的某一个仓库

这个不考虑，lock 的目的就是锁死，什么都是固定的，包括仓库地址，而不是根据环境变量可变的。。
