### ISSUE TITLE
xmake-requires.lock 的 meta 区位置不固定

### ISSUE THREAD

**Issue by darcy-shen** [xmake-io/xmake#4590]
### Xmake 版本

2.8.5

### 操作系统版本和架构

Windows 11

### 描述问题

一会儿在文件头部，一会儿在文件中间

![image](https://github.com/xmake-io/xmake/assets/1267865/f18009ee-42e4-4372-bab9-30b0152cee3d)

这个应该是在linux平台使用之后出现问题。macOS和windows的顺序是符合期待的

### 期待的结果

始终在文件头部

### 工程配置

工程配置见： http://github.com/XmacsLabs/mogan

这个应该和具体哪个工程关系不大。

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
我记得 key 已经是排序过的才对

**Comment by darcy-shen** [comment]
就是在Linux上面不一样，应该是linux上面的排序规则问题

**Comment by waruqi** [comment]
我试了下 linux 下也没这个问题么。。__meta__ 一直被排序在最开头

**Comment by darcy-shen** [comment]
我在debian和两台不同架构（x64/loongarch）的uos上面都有这个问题。debian上面是软件源里面的2.8.6，uos上面的是我自己用源代码编译的，应该用的还是2.8.5。

**Comment by darcy-shen** [comment]
这个不重要了，最近在实践中，发现在linux上面使用lockfile并不合适，尤其是在同时支持ArchLinux和Ubuntu的情况下。目前在macOS和windows下开启，比较合适。
