### ISSUE TITLE
xmake-requires.lock 在Windows上面使用CRLF

### ISSUE THREAD

**Issue by darcy-shen** [xmake-io/xmake#4591]
### Xmake 版本

2.8.5

### 操作系统版本和架构

Windows 11

### 描述问题

这个问题导致跨平台使用的时候，每次切换到windows开发都会出现差异

### 期待的结果

默认使用LF

### 工程配置

https://github.com/XmacsLabs/mogan

应该和工程无关，可能任意一个跨平台的项目都可以复现

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
再试试  xmake update -s dev

**Comment by darcy-shen** [comment]
已验证，已经不是crlf了
