### ISSUE TITLE
使用远程缓存编译速度没有提升

### ISSUE THREAD

**Issue by ZYC97104** [xmake-io/xmake#4592]
### Xmake 版本

v2.8.6

### 操作系统版本和架构

本地编译机centos6 x86 远程缓存机器centos7 x86

### 描述问题

 使用远程缓存编译后 清理掉本地缓存 重新编译100%命中远程缓存 但是比没有缓存全量编译还慢
![image](https://github.com/xmake-io/xmake/assets/54052023/87de6ef1-7c3b-4b5f-93e6-73c7522de8b9)
编译机和远程缓存机器全部在南京 使用工具测试网络通信速度500Mbps 磁盘是挂载云盘 io 50M/s
代码全量编译390s左右
没有本地缓存的情况下使用远程缓存编译需要450s

.build_cache大小为506M

### 期待的结果

没有本地缓存的情况下 能够使用远程缓存加快编译速度

### 工程配置

client.conf
{
     remote_cache = {
         connect = "xxxxx:9692",
         token = "8eb7fcb09da4d96d74bc5c8f3c71f2a3"
     },
     send_timeout = 15000,
     recv_timeout = 15000,
     connect_timeout = 15000
}

server.conf
{
    distcc_build = {
        listen = "0.0.0.0:9693",
        toolchains = {
            ndk = { }
        },
        workdir = "/data/.xmake/service/server/distcc_build"
    },
    known_hosts = { },
    logfile = "/data/.xmake/service/server/logs.txt",
    recv_timeout = -1,
    remote_build = {
        listen = "0.0.0.0:9691",
        workdir = "/data/.xmake/service/server/remote_build"
    },
    remote_cache = {
        listen = "0.0.0.0:9692",
        workdir = "/root/.xmake/service/server/remote_cache"
    },
    send_timeout = -1,
    tokens = {
        "8eb7fcb09da4d96d74bc5c8f3c71f2a3"
    }
}

### 附加信息和错误日志

build cache stats:
cache directory: build/.build_cache
cache hit rate: 100%
cache hit: 303
cache miss: 0
new cached files: 303
remote cache hit: 303
remote new cached files: 0
preprocess failed: 1
compile fallback count: 0

**Comment by waruqi** [comment]
编译的 c++ 还是 c?

估计还是 平均每个 obj 的下载拉取耗时超过了 本地编译耗时导致。。后面看看怎么再优化下

**Comment by ZYC97104** [comment]
> 编译的 c++ 还是 c?
> 
> 估计还是 平均每个 obj 的下载拉取耗时超过了 本地编译耗时导致。。后面看看怎么再优化下

c++

**Comment by waruqi** [comment]
之前确实有点问题，我修复了，再试试

xmake update -s dev

**Comment by ZYC97104** [comment]
> 之前确实有点问题，我修复了，再试试
> 
> xmake update -s dev

![image](https://github.com/xmake-io/xmake/assets/54052023/62ce614d-b8ef-428f-8ec1-e1c52d24aa3b)
问题已经解决了 大佬太强了 辛苦给一下赞赏链接 请大佬喝杯咖啡

**Comment by ZYC97104** [comment]
> 之前确实有点问题，我修复了，再试试
> 
> xmake update -s dev

![image](https://github.com/xmake-io/xmake/assets/54052023/0062bc5f-41dc-4df8-9c68-af63e80c20fa)
问题已经解决了 辛苦大佬提供一下赞赏链接 请大佬喝杯咖啡

**Comment by waruqi** [comment]
> > 之前确实有点问题，我修复了，再试试
> > xmake update -s dev
> 
> ![image](https://private-user-images.githubusercontent.com/54052023/295855151-0062bc5f-41dc-4df8-9c68-af63e80c20fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjUxODQsIm5iZiI6MTcwNDk2NDg4NCwicGF0aCI6Ii81NDA1MjAyMy8yOTU4NTUxNTEtMDA2MmJjNWYtNDFkYy00ZGY4LTljNjgtYWY2M2U4MGMyMGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA5MjEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0M2U2MTY5OGRjYjQwMTQwODA4MjhhNzcxYWQ3NzU4M2UwYTYzMjg0OTYyYWU5OTdjMDk2NWUxNTc1M2ZmN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9wN8mROH6Rf1mK-WKdZL6VA2x4an7GjOoEROWFY5mMc) 问题已经解决了 辛苦大佬提供一下赞赏链接 请大佬喝杯咖啡

https://xmake.io/#/zh-cn/about/sponsor

**Comment by ZYC97104** [comment]
> 之前确实有点问题，我修复了，再试试
> 
> xmake update -s dev

大佬 这里我后面又测试了一下 更新一些代码 速度又慢下来了 排查发现之前速度快是没有清理ccache的缓存 全部清理后对比更新之前速度没有太大的提升 这里麻烦看看还有没有优化的空间呀

**Comment by waruqi** [comment]
```console
rm -rf ./build
xmake -rvD
```

重新给下完整 logs，尤其是最后的 build cache 统计数据

**Comment by ZYC97104** [comment]
> ```
> rm -rf ./build
> xmake -rvD
> ```
> 
> 重新给下完整 logs，尤其是最后的 build cache 统计数据

[2024-01-11 23:54:21]
[2024-01-11 23:54:21]build cache stats:
[2024-01-11 23:54:21]cache directory: build/.build_cache
[2024-01-11 23:54:21]cache hit rate: 16%
[2024-01-11 23:54:21]cache hit: 50
[2024-01-11 23:54:21]cache hit total time: 5.268s
[2024-01-11 23:54:21]cache miss: 253
[2024-01-11 23:54:21]cache miss total time: 52.178s
[2024-01-11 23:54:21]new cached files: 253
[2024-01-11 23:54:21]remote cache hit: 50
[2024-01-11 23:54:21]remote new cached files: 253
[2024-01-11 23:54:21]preprocess failed: 0
[2024-01-11 23:54:21]compile fallback count: 0
[2024-01-11 23:54:21]compile total time: 5579.029s
[2024-01-11 23:54:21]
[2024-01-11 23:54:21][100%]: build ok, spent 392.86s

大概破案了 因为是在流水线中使用每次流水线启动后下发一个docker容器会新建一个工作空间 导致每次代码的目录都不一样 虽然代码一样但是缓存命中率非常低
在本地中rm -rf build后测试拉取远程缓存非常快，但是将build文件夹删掉后 把代码拷贝到别的目录重新编译 缓存命中率就会非常低
目前缓存是使用外置缓存ccache 辛苦大佬看看是不是bug 如果是本地的缓存是不会因为目录问题导致缓存无法命中的

**Comment by waruqi** [comment]
参考这个试下 https://github.com/xmake-io/xmake/discussions/4524#discussioncomment-7924722

**Comment by ZYC97104** [comment]
> 参考这个试下 [#4524 (comment)](https://github.com/xmake-io/xmake/discussions/4524#discussioncomment-7924722)

![image](https://github.com/xmake-io/xmake/assets/54052023/8619fa54-6717-44a1-acfe-1bf7472ed167)
![image](https://github.com/xmake-io/xmake/assets/54052023/976e038f-1582-4609-b653-0ed52b3f7687)

目前就是使用这种方式 指定了session 远程缓存只有一个目录 但是每次更换了代码编译的目录还是会导致缓存命中率变低

**Comment by waruqi** [comment]
命中缓存就是通过      session id + hash(预处理后的源码)，只要这两不变，就不会命中不到。。既然 session id 固定了，那就是你的源码变了，或者某些 flags/macro 导致源码预处理展开后的内容变了。。比如用了 __FILE__ 这种，不同机器下，路径不同，展开后的结果也会导致 hash 变化。

**Comment by ZYC97104** [comment]
> 命中缓存就是通过 session id + hash(预处理后的源码)，只要这两不变，就不会命中不到。。既然 session id 固定了，那就是你的源码变了，或者某些 flags/macro 导致源码预处理展开后的内容变了。。比如用了`__FILE__` 这种，不同机器下，路径不同，展开后的结果也会导致 hash 变化。

thx 确实打印日志到处都是__FILE__ 没有打印日志就可以命中缓存
