### ISSUE TITLE
`xmake run` does not set CWD correctly

### ISSUE THREAD

**Issue by rongcuid** [xmake-io/xmake#4595]
### Xmake Version

2.8.6

### Operating System Version and Architecture

Ubuntu 22.04

### Describe Bug

When using `xmake run` to execute a program, the working directory is not where `xmake run` is executed from, but where the binary is located.

用`xmake run`执行程序时，工作目录并非命令行所对应的目录而是可执行文件所处的目录。

### Expected Behavior

```
$ pwd
/tmp/test
$ ./build/linux/x86_64/release/test
CWD: /tmp/test
$ xmake run
CWD: /tmp/test/build/linux/x86_64/release
```

### Project Configuration

```lua
add_rules("mode.debug", "mode.release")

target("test")
    set_kind("binary")
    add_files("src/*.c")
```

```c
#include <stdio.h>
#include <unistd.h>

int main(int argc, char** argv)
{
    char buf[256];
    printf("CWD: %s\n", getcwd(buf, 256));
    return 0;
}
```

### Additional Information and Error Logs

N/A

**Comment by waruqi** [comment]
你可以 set_rundir 或者 `xmake run -w workdir` 自己调整

**Comment by rongcuid** [comment]
不过一般来说cwd默认应该是当前目录吗？xmake的默认目录感觉有点意料之外

**Comment by star-hengxing** [comment]
大部分构建系统也没有类似 `xmake run` 这种功能，感觉哪个目录无所谓吧
我平时给 binary target 用 `set_rundir(os.projectdir())`

**Comment by rongcuid** [comment]
C/C++确实一般没有，但如果看go、Rust等语言的话， `go run`/`carto run`等一般都是等于直接输入可执行文件的命令的。

`cargo run === ./target/debug/exec-file`

**Comment by waruqi** [comment]
如果target会在workdir创建文件，放在 当前目录，就会污染工程目录，甚至可能误删工程文件，这种默认路径，不同用户需求都不同，没必要纠结，自己 set_rundir改下就行了，没啥可意外的
