### ISSUE TITLE
希望支持Visual Studio 生成工具2022

### ISSUE THREAD

**Issue by v-dao** [xmake-io/xmake#4609]
### 你在什么场景下需要该功能？

当我不想Visual Stduio IDE时，又需要用到cl编译器时，我只通过Vsiual Studio Installer安装了Visual Studio 生成工具2022，并且安装了开发用的组件。
![屏幕截图 2024-01-14 154421](https://github.com/xmake-io/xmake/assets/47357234/66f64910-0539-4c46-8ddb-775620ee97db)
![屏幕截图 2024-01-14 154531](https://github.com/xmake-io/xmake/assets/47357234/104f65e0-b0c5-4353-9fb0-2af3cb3112a0)
我用xmake不能设置msvc工具集，cmake就可以使用。

### 描述可能的解决方案

可以添加一个工具集msvc-dev这样的， 或者大佬能有更好的办法。

### 其他信息

这个Visual Stduio生成工具2022启动bat在C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools目录下。
![屏幕截图 2024-01-14 155242](https://github.com/xmake-io/xmake/assets/47357234/d44b22d1-7937-4a15-b9c2-d2156346d22e)

**Comment by xq114** [comment]
有 vcvarsall.bat/vcvars64.bat 这样的文件可以看环境变量吗？看看 C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build 文件夹，有就好办

**Comment by v-dao** [comment]
> 有 vcvarsall.bat/vcvars64.bat 这样的文件可以看环境变量吗？看看 C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build 文件夹，有就好办

很可惜，并没有vcvars64.bat。
![image](https://github.com/xmake-io/xmake/assets/47357234/bf739129-8e81-463f-b43a-46f02c78fbcc)

**Comment by waruqi** [comment]
这边得需要 vcvarsall.bat 才能使用

> 我用xmake不能设置msvc工具集，cmake就可以使用。

本质上 cmake 只是个生成器，最后走的是 msbuild 。。但是 xmake 是直接编译，机制不同，如果没 vcvarsall.bat 单纯只有 vs 的 msbuild 支持不了。

**Comment by v-dao** [comment]
> 这边得需要 vcvarsall.bat 才能使用
> 
> > 我用xmake不能设置msvc工具集，cmake就可以使用。
> 
> 本质上 cmake 只是个生成器，最后走的是 msbuild 。。但是 xmake 是直接编译，机制不同，如果没 vcvarsall.bat 单纯只有 vs 的 msbuild 支持不了。

虽然没有vcvarall.bat但是有第二个图的LaunchDevCmd.bat，两个bat应该是等价的。使用这个bat打开的控制台，我用cmake使用ninja生成器，没有用msbuild，默认使用的编译器是cl。但是xmake只能找到vcvarall.bat才能用cl。

**Comment by waruqi** [comment]
如果 LaunchDevCmd 也能获取到环境，也可以尝试支持下，不过目前粗看下来，并不一定跟 vcvarall.bat 等价，toolset winsdkver arch 也似乎没参数可以切

具体绑定的环境是否完全一致，还有 INCLUDE LIB 等环境变量，都还得细看下

**Comment by waruqi** [comment]
刚改进了下，应该支持  arch 了

**Comment by waruqi** [comment]
可以了么？

**Comment by v-dao** [comment]
> 可以了么？

昨天忘记用一用了，今晚我会记得

**Comment by v-dao** [comment]
可以用了，谢谢支持。
