### ISSUE TITLE
android-ndk-26b文件目录变动导致编译结果有误

### ISSUE THREAD

**Issue by WooZoo86** [xmake-io/xmake#4614]
### Xmake 版本

2.8.6

### 操作系统版本和架构

win11 x64

### 描述问题

set_config("ndk_cxxstl","c++_static")该设置编译结果还是要依赖libc++_shared.so，xmake -vD输出没有-lc++_static
和-static-libstdc++编译项。
对ndk的stdC++编译设置无效，应该是脚本判断ndk的\sources\cxx-stl文件夹失效，该文件夹在android-ndk-26b有变动，libc++更新。

### 期待的结果

期待静态链接libc++，实际是动态链接。

### 工程配置

set_config("ndk_cxxstl","c++_static")
set_config("ndk_sdkver","22")

### 附加信息和错误日志

PS E:\Work\CVFramework> xmake f -p android -a armeabi-v7a -m release --ndk=D:\SDK\android-ndk-r22 --ndk_cxxstl=c++_static 
checking for Android SDK directory ... no
checking for NDK directory ... D:\SDK\android-ndk-r22
checking for SDK version of NDK ... 22
PS E:\Work\CVFramework>  xmake -vD
checking for the shared library linker (sh) ... clang++
checking for the linker (ld) ... clang++
checking for clang++ ... D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++
checking for the c++ compiler (cxx) ... clang++
checking for the c++ compiler (cxx) ... clang++
checking for the c++ compiler (cxx) ... clang++
checking for the c++ compiler (cxx) ... clang++
checking for the c++ compiler (cxx) ... clang++
checking for D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ ... ok
checking for flags (-fPIC) ... ok
> clang++ "-fPIC" "--sysroot=D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot" "-isystem" "D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\arm-linux-androideabi" "-nostdinc++" "-Qunused-arguments" "-target" "armv7-none-linux-androideabi22" "-gcc-toolchain" "D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" "-mthumb"
checking for flags (-fvisibility-inlines-hidden) ... ok
> clang++ "-fvisibility-inlines-hidden" "--sysroot=D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot" "-isystem" "D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\arm-linux-androideabi" "-nostdinc++" "-Qunused-arguments" "-target" "armv7-none-linux-androideabi22" "-gcc-toolchain" "D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" "-mthumb"   
checking for flags (-Oz) ... ok
> clang++ "-Oz" "--sysroot=D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot" "-isystem" "D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\arm-linux-androideabi" "-nostdinc++" "-Qunused-arguments" "-target" "armv7-none-linux-androideabi22" "-gcc-toolchain" "D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" "-mthumb"
checking for flags (-Oz) ... ok
> clang++ "-Oz" "--sysroot=D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot" "-isystem" "D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\arm-linux-androideabi" "-nostdinc++" "-Qunused-arguments" "-target" "armv7-none-linux-androideabi22" "-gcc-toolchain" "D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" "-mthumb"
checking for flags (-std=c++20) ... ok
> clang++ "-std=c++20" "--sysroot=D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot" "-isystem" "D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\arm-linux-androideabi" "-nostdinc++" "-Qunused-arguments" "-target" "armv7-none-linux-androideabi22" "-gcc-toolchain" "D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" "-mthumb"
checking for flags (-std=c++20) ... ok
> clang++ "-std=c++20" "--sysroot=D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot" "-isystem" "D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\arm-linux-androideabi" "-nostdinc++" "-Qunused-arguments" "-target" "armv7-none-linux-androideabi22" "-gcc-toolchain" "D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" "-mthumb"
checking for flags (-fvisibility=hidden) ... ok
> clang++ "-fvisibility=hidden" "--sysroot=D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot" "-isystem" "D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\arm-linux-androideabi" "-nostdinc++" "-Qunused-arguments" "-target" "armv7-none-linux-androideabi22" "-gcc-toolchain" "D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" "-mthumb"
checking for flags (-DNDEBUG) ... ok
> clang++ "-DNDEBUG" "--sysroot=D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot" "-isystem" "D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\arm-linux-androideabi" "-nostdinc++" "-Qunused-arguments" "-target" "armv7-none-linux-androideabi22" "-gcc-toolchain" "D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" "-mthumb"
[ 21%]: cache compiling.release src\Application\src\Application.cpp
D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ -c --sysroot=D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot -isystem D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\arm-linux-androideabi -nostdinc++ -Qunused-arguments -target armv7-none-linux-androideabi22 -gcc-toolchain D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64 -mthumb -fPIC -Wall -Werror -Oz -std=c++20 -IE:\Work\CVFramework -DCV_COMPILED_LIB -DCV_SHARED_LIB -DLOG_ON -isystem D:\SDK\android-ndk-r22\sources\cxx-stl\llvm-libc++\include -isystem D:\SDK\android-ndk-r22\sources\cxx-stl\llvm-libc++\libs\armeabi-v7a\include -isystem D:\SDK\android-ndk-r22\sources\cxx-stl\llvm-libc++abi\include -fvisibility=hidden -DNDEBUG -o build\.objs\Application\android\armeabi-v7a\release\src\Application\src\Application.cpp.o src\Application\src\Application.cpp
checking for flags (-MMD -MF) ... ok
> clang++ "-MMD" "-MF" "C:\Users\castw\AppData\Local\Temp\.xmake\240115\_F1768BB4A47542108C9252CF7F6DB820" "--sysroot=D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot" "-isystem" "D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\arm-linux-androideabi" "-nostdinc++" "-Qunused-arguments" "-target" "armv7-none-linux-androideabi22" "-gcc-toolchain" "D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" "-mthumb"
[ 21%]: cache compiling.release test\src\AppTest.cpp
D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ -c --sysroot=D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot -isystem D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\arm-linux-androideabi -nostdinc++ -Qunused-arguments -target armv7-none-linux-androideabi22 -gcc-toolchain D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64 -mthumb -fPIE -pie -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Oz -std=c++20 -IE:\Work\CVFramework -DCV_COMPILED_LIB -DCV_SHARED_LIB -DLOG_ON -isystem C:\Users\castw\AppData\Local\.xmake\packages\g\gtest\v1.14.0\7484f84bfb1043c199a1c192fdde8434\include -isystem D:\SDK\android-ndk-r22\sources\cxx-stl\llvm-libc++\include -isystem D:\SDK\android-ndk-r22\sources\cxx-stl\llvm-libc++\libs\armeabi-v7a\include -isystem D:\SDK\android-ndk-r22\sources\cxx-stl\llvm-libc++abi\include -fvisibility=hidden -DNDEBUG -o build\.objs\Test\android\armeabi-v7a\release\test\src\AppTest.cpp.o test\src\AppTest.cpp
[ 21%]: cache compiling.release src\Log\src\Log.cpp
D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ -c --sysroot=D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot -isystem D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\arm-linux-androideabi -nostdinc++ -Qunused-arguments -target armv7-none-linux-androideabi22 -gcc-toolchain D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64 -mthumb -fPIC -Wall -Werror -Oz -std=c++20 -IE:\Work\CVFramework -DCV_COMPILED_LIB -DCV_SHARED_LIB -DLOG_ON -DANDROID -isystem C:\Users\castw\AppData\Local\.xmake\packages\s\spdlog\v1.12.0\d35f06e46ef042c0aa73ff35c9bfbeaa\include -isystem D:\SDK\android-ndk-r22\sources\cxx-stl\llvm-libc++\include -isystem D:\SDK\android-ndk-r22\sources\cxx-stl\llvm-libc++\libs\armeabi-v7a\include -isystem D:\SDK\android-ndk-r22\sources\cxx-stl\llvm-libc++abi\include -fvisibility=hidden -DNDEBUG -o build\.objs\CVLog\android\armeabi-v7a\release\src\Log\src\Log.cpp.o src\Log\src\Log.cpp
[ 21%]: cache compiling.release test\src\LogTest.cpp
D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ -c --sysroot=D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot -isystem D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\arm-linux-androideabi -nostdinc++ -Qunused-arguments -target armv7-none-linux-androideabi22 -gcc-toolchain D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64 -mthumb -fPIE -pie -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Oz -std=c++20 -IE:\Work\CVFramework -DCV_COMPILED_LIB -DCV_SHARED_LIB -DLOG_ON -isystem C:\Users\castw\AppData\Local\.xmake\packages\g\gtest\v1.14.0\7484f84bfb1043c199a1c192fdde8434\include -isystem D:\SDK\android-ndk-r22\sources\cxx-stl\llvm-libc++\include -isystem D:\SDK\android-ndk-r22\sources\cxx-stl\llvm-libc++\libs\armeabi-v7a\include -isystem D:\SDK\android-ndk-r22\sources\cxx-stl\llvm-libc++abi\include -fvisibility=hidden -DNDEBUG -o build\.objs\Test\android\armeabi-v7a\release\test\src\LogTest.cpp.o test\src\LogTest.cpp
checking for flags (-fvisibility=hidden) ... ok
> clang++ "-fvisibility=hidden" "--sysroot=D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot" "-isystem" "D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\arm-linux-androideabi" "-nostdinc++" "-Qunused-arguments" "-target" "armv7-none-linux-androideabi22" "-gcc-toolchain" "D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" "-mthumb"
[ 21%]: cache compiling.release test\src\main.cpp
D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ -c --sysroot=D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot -isystem D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\arm-linux-androideabi -nostdinc++ -Qunused-arguments -target armv7-none-linux-androideabi22 -gcc-toolchain D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64 -mthumb -fPIE -pie -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Oz -std=c++20 -IE:\Work\CVFramework -DCV_COMPILED_LIB -DCV_SHARED_LIB -DLOG_ON -isystem C:\Users\castw\AppData\Local\.xmake\packages\g\gtest\v1.14.0\7484f84bfb1043c199a1c192fdde8434\include -isystem D:\SDK\android-ndk-r22\sources\cxx-stl\llvm-libc++\include -isystem D:\SDK\android-ndk-r22\sources\cxx-stl\llvm-libc++\libs\armeabi-v7a\include -isystem D:\SDK\android-ndk-r22\sources\cxx-stl\llvm-libc++abi\include -fvisibility=hidden -DNDEBUG -o build\.objs\Test\android\armeabi-v7a\release\test\src\main.cpp.o test\src\main.cpp
checking for flags (-fdiagnostics-color=always) ... ok
> clang++ "-fdiagnostics-color=always" "--sysroot=D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot" "-isystem" "D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\arm-linux-androideabi" "-nostdinc++" "-Qunused-arguments" "-target" "armv7-none-linux-androideabi22" "-gcc-toolchain" "D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" "-mthumb"    
checking for flags (-fdiagnostics-color=always) ... ok
> clang++ "-fdiagnostics-color=always" "--sysroot=D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot" "-isystem" "D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\arm-linux-androideabi" "-nostdinc++" "-Qunused-arguments" "-target" "armv7-none-linux-androideabi22" "-gcc-toolchain" "D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" "-mthumb"    
checking for flags (-fPIC) ... ok
> clang++ "-fPIC" "-shared" "-llog" "-target" "armv7-none-linux-androideabi22" "-gcc-toolchain" "D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" "-nostdlib++" "-mthumb" "-llog" "-target" "armv7-none-linux-androideabi22" "-gcc-toolchain" "D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" "-nostdlib++" "-mthumb"
[ 57%]: linking.release libCVLog.so
D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ -o build\android\armeabi-v7a\release\libCVLog.so build\.objs\CVLog\android\armeabi-v7a\release\src\Log\src\Log.cpp.o -shared -target armv7-none-linux-androideabi22 -gcc-toolchain D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64 -nostdlib++ -mthumb -fPIC -s -LD:\SDK\android-ndk-r22\sources\cxx-stl\llvm-libc++\libs\armeabi-v7a -llog -lc++_static -lc++abi -lunwind -latomic
[ 71%]: linking.release libApplication.so
D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ -o build\android\armeabi-v7a\release\libApplication.so build\.objs\Application\android\armeabi-v7a\release\src\Application\src\Application.cpp.o -shared -target armv7-none-linux-androideabi22 -gcc-toolchain D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64 -nostdlib++ -mthumb -fPIC -Lbuild\android\armeabi-v7a\release -s -LD:\SDK\android-ndk-r22\sources\cxx-stl\llvm-libc++\libs\armeabi-v7a -lCVLog -llog -lc++_static -lc++abi -lunwind -latomic
checking for flags (-fPIC) ... ok
> clang++ "-fPIC" "-llog" "-target" "armv7-none-linux-androideabi22" "-gcc-toolchain" "D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" "-fPIE" "-pie" "-nostdlib++" "-mthumb" "-llog" "-target" "armv7-none-linux-androideabi22" "-gcc-toolchain" "D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" "-fPIE" "-pie" "-nostdlib++" "-mthumb"
checking for flags (-Wl,-rpath=@loader_path) ... ok
> clang++ "-Wl,-rpath=@loader_path" "-llog" "-target" "armv7-none-linux-androideabi22" "-gcc-toolchain" "D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" "-fPIE" "-pie" "-nostdlib++" "-mthumb" "-llog" "-target" "armv7-none-linux-androideabi22" "-gcc-toolchain" "D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" "-fPIE" "-pie" "-nostdlib++" "-mthumb"
checking for flags (-static-libstdc++) ... ok
> clang++ "-static-libstdc++" "-llog" "-target" "armv7-none-linux-androideabi22" "-gcc-toolchain" "D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" "-fPIE" "-pie" "-nostdlib++" "-mthumb" "-llog" "-target" "armv7-none-linux-androideabi22" "-gcc-toolchain" "D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64" "-fPIE" "-pie" "-nostdlib++" "-mthumb"
[ 85%]: linking.release Test
D:\SDK\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ -o build\android\armeabi-v7a\release\Test build\.objs\Test\android\armeabi-v7a\release\test\src\AppTest.cpp.o build\.objs\Test\android\armeabi-v7a\release\test\src\LogTest.cpp.o build\.objs\Test\android\armeabi-v7a\release\test\src\main.cpp.o -target armv7-none-linux-androideabi22 -gcc-toolchain D:\SDK\android-ndk-r22\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64 -fPIE -pie -nostdlib++ -mthumb -LC:\Users\castw\AppData\Local\.xmake\packages\g\gtest\v1.14.0\7484f84bfb1043c199a1c192fdde8434\lib -Lbuild\android\armeabi-v7a\release -Wl,-rpath=$ORIGIN -s -LD:\SDK\android-ndk-r22\sources\cxx-stl\llvm-libc++\libs\armeabi-v7a -lgmock -lgtest -lApplication -lCVLog -llog -lc++_static -lc++abi -lunwind -latomic -static-libstdc++
clang++: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]

build cache stats:
cache directory: build\.build_cache
cache hit rate: 0%
cache hit: 0
cache miss: 5
new cached files: 5
remote cache hit: 0
remote new cached files: 0
preprocess failed: 0
compile fallback count: 0

[100%]: build ok, spent 10.437s

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/pull/4616

试试，`xmake update -s github:xmake-io/xmake#ndk`

**Comment by waruqi** [comment]
贴下详细命令  和  -vD logs

**Comment by waruqi** [comment]
> -lgmock -lgtest -lApplication -lCVLog -llog -lc++_static -lunwind -latomic

不是加进去了么。。看着没啥问题

**Comment by jococi** [comment]
可以了吗？我怎么还不行

**Comment by waruqi** [comment]
这边可以

```
ruki-2:test ruki$ xmake f -p android --ndk=~/files/android-ndk-r26b/ -c -a arm64-v8a ; xmake -rv
checking for Android SDK directory ... ~/Library/Android/sdk
checking for Build Tools Version of Android SDK ... 33.0.1
checking for NDK directory ... /Users/ruki/files/android-ndk-r26b
checking for SDK version of NDK ... 21
checking for the shared library linker (sh) ... clang++
checking for the linker (ld) ... clang++
checking for clang++ ... /Users/ruki/files/android-ndk-r26b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
checking for the c++ compiler (cxx) ... clang++
checking for /Users/ruki/files/android-ndk-r26b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ ... ok
checking for flags (-fPIC) ... ok
checking for flags (-fvisibility-inlines-hidden) ... ok
checking for flags (-Oz) ... ok
checking for flags (-DNDEBUG) ... ok
[ 25%]: cache compiling.release src/main.cpp
/Users/ruki/files/android-ndk-r26b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -c --sysroot=/Users/ruki/files/android-ndk-r26b/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -isystem /Users/ruki/files/android-ndk-r26b/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/aarch64-linux-android -Qunused-arguments -target aarch64-none-linux-android21 -fPIE -pie -fvisibility=hidden -fvisibility-inlines-hidden -Oz -DNDEBUG -o build/.objs/test/android/arm64-v8a/release/src/main.cpp.o src/main.cpp
checking for flags (-MMD -MF) ... ok
checking for flags (-fdiagnostics-color=always) ... ok
checking for flags (-fPIC) ... ok
[ 50%]: linking.release test
/Users/ruki/files/android-ndk-r26b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -o build/android/arm64-v8a/release/test build/.objs/test/android/arm64-v8a/release/src/main.cpp.o -llog -target aarch64-none-linux-android21 -fPIE -pie -static-libstdc++ -s
[100%]: build ok, spent 0.796s
ruki-2:test ruki$ adb push build/android/arm64-v8a/release/test /data/local/tmp/test; adb shell /data/local/tmp/test
build/android/arm64-v8a/release/test: 1 file pushed, 0 skipped. 104.8 MB/s (791848 bytes in 0.007s)
hello world!
```

**Comment by jococi** [comment]
你是的对的，是我另外一个动态库引起的

**Comment by ifarbod** [comment]
I ran into this issue, I had to use `add_links("c++_static")` in my project, maybe you should give this another look @waruqi ?

Should I open a new issue?

**Comment by waruqi** [comment]
Did you try dev version?

**Comment by ifarbod** [comment]
Yeah, I also tried `xmake update -s dev` but I always get c++_shared.so linked in my final .so.

**Comment by waruqi** [comment]
> Yeah, I also tried `xmake update -s dev` but I always get c++_shared.so linked in my final .so.

you need pass `--ndk_cxxstl=c++_static` to `xmake config`, itis not default config.

**Comment by ifarbod** [comment]
Can I use `set_runtimes()` in my xmake.lua to get the same effect?

**Comment by ifarbod** [comment]
I have created a small repo to demonstrate the bug. https://github.com/ifarbod/example-xmake-android-project

**Comment by waruqi** [comment]
> Can I use `set_runtimes()` in my xmake.lua to get the same effect?

dev version support it.

**Comment by ifarbod** [comment]
@waruqi Will this change land in v2.8.7?

**Comment by waruqi** [comment]
2.8.7 will support it, or you can use set_config  https://github.com/xmake-io/xmake/issues/4614#issuecomment-1893099710
