### ISSUE TITLE
tinycc library extension should be named libxxx.a, not xxx.lib

### ISSUE THREAD

**Issue by badiku** [xmake-io/xmake#4621]
### Xmake Version

2.8.6

### Operating System Version and Architecture

win10 x64

### Describe Bug

when compile Lua , error is "error: tcc: error: library 'src' not found"

when check with xmake -v, I found that generated command is:

```
xmake f --toolchain=tinycc

tcc -ar cr src.lib ...
tcc -o lua.exe ...  -lsrc

```

while in gcc it is ok to use -lsrc to load src.lib,   in tinycc, it should be libsrc.a

quote from https://www.bellard.org/tcc/tcc-doc.html:

> -lxxx
>      Link your program with dynamic library libxxx.so or static library libxxx.a. 

### Expected Behavior

tinycc library extension should be named libxxx.a, not xxx.lib

I manually changed the resulted file src.lib to libsrc.a, and run xmake again, then it is OK 

### Project Configuration

--

### Additional Information and Error Logs

--

**Comment by badiku** [comment]
solution:

tinycc in windows, still need name like libxxx.a,  and object file is *.obj,
so need to change config file 
`xmake\toolchains\tinycc\xmake.lua`
like this:
```
-- define toolchain
toolchain("tinycc")
    set_formats("static", "lib$(name).a")
    set_formats("object", "$(name).obj")
    set_formats("shared", "lib$(name).dll")
    set_formats("binary", "$(name).exe")
```

now, problem solved
    

I only use windows. so not thinking about linux. maybe should take care of windows or linux platform.

**Comment by waruqi** [comment]
试试这个 patch 呢 https://github.com/xmake-io/xmake/pull/4626

```
xmake update -s github:xmake-io/xmake#tcc
```
