### ISSUE TITLE
Improve c++ modules support

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#4629]
- [x] Refactor modules support
  - https://github.com/xmake-io/xmake/pull/4673
- [x] Support clang libc++/modules
  -  https://github.com/llvm/llvm-project/pull/75741
- [x] Improve cmake generator
  - https://github.com/xmake-io/xmake/pull/4625
  - https://github.com/xmake-io/xmake/issues/4087
  - https://github.com/xmake-io/xmake/issues/3642
  - https://github.com/xmake-io/xmake/pull/4746
- [x] Improve compile_commands generator
  - https://github.com/xmake-io/xmake/issues/4330 
- [x] Improve vs/vsxmake generator
  - https://github.com/xmake-io/xmake/issues/3426
- [x] Improve to install c++ modules for packages
- [x] Switch libc++/libstdc++/ runtimes
  -  https://github.com/xmake-io/xmake/issues/4477 
- [ ] Solve c++ modules rules and other rules conflict (protobuf rule, ..)
  - https://github.com/xmake-io/xmake/issues/3420

**Comment by Arthapz** [comment]
i got some times now, so i'll resume the work on https://github.com/xmake-io/xmake/pull/4321
and refactor the commits first to separate tests and refactoring as suggested
and next i'll look on https://github.com/llvm/llvm-project/pull/75741  and https://github.com/xmake-io/xmake/issues/4477

**Comment by waruqi** [comment]
Thanks, I am working at https://github.com/xmake-io/xmake/issues/4477 now.
