### ISSUE TITLE
Should we update CI script to keep zip file structure?

### ISSUE THREAD

**Issue by OpportunityLiu** [xmake-io/xmake#463]
https://github.com/ScoopInstaller/Main/issues/159

**Comment by OpportunityLiu** [comment]
change
https://github.com/xmake-io/xmake/blob/72bd93de8dd64cc5de8986860819a5873ce08fe5/.appveyor.yml#L67
to
```
 - ps: Compress-Archive -Path .\xmake -DestinationPath .\archive.zip -CompressionLevel Optimal
```

**Comment by waruqi** [comment]
之前手动做zip包 是保留xmake目录的。ci上也保留下xmake根目录吧。。

**Comment by waruqi** [comment]
scoop上的 我晚上先手动重传修复下好了

**Comment by niheaven** [comment]
所以传好之后 Ping 我一下咯，我重新改 Scoop 的 Manifest。另外，考虑下在 Release 页面放 SHA256 如何？

**Comment by OpportunityLiu** [comment]
其实也可以直接从CI上拉，现在的安装脚本就是这么搞的
```powershell
"https://ci.appveyor.com/api/projects/waruqi/xmake/artifacts/xmake-installer.exe?tag=v$version&pr=false&job=Image%3A+Visual+Studio+2017%3B+Platform%3A+$arch" 
```

**Comment by waruqi** [comment]
恩 可以搞成直接设置ci url到scoop manifest上去，不过2.2.7目前的zip没根xmake，也没打sha文件。只能等下个版本时，再更新下scoop，直接指向ci的zip/sha url了。。

**Comment by waruqi** [comment]
@niheaven 我重传了，sha也放上去了。https://github.com/xmake-io/xmake/releases/tag/v2.2.7  根目录 xmake 也恢复了。。

**Comment by niheaven** [comment]
搞定，已经改过来并且直接从 release 读 hash 了。

**Comment by waruqi** [comment]
@niheaven 谢谢
