### ISSUE TITLE
Allow different specifiers for fields in declaratively styled xmake.lua sections

### ISSUE THREAD

**Issue by paul-reilly** [xmake-io/xmake#4634]
### Is your feature request related to a problem? Please describe.

(As we know) xmake allows declarative styling:

```lua
target("foo", {
    kind = "shared",
    files = "src/**.cpp",
    includedirs = { "include", "internal" }
})
```

However I don't think it's possible at the moment to have different access specifiers like this:
```lua
target("foo")
    set_kind("shared")
    add_files("src/**.cpp")
    add_includedirs("include", { public = true })
    add_includedirs("internal")
```

### Describe the solution you'd like

A way of being able to do that. Something similar to:

```lua
target("foo", {
    kind = "shared",
    files = "src/**.cpp",
    includedirs = { { "include", { public = true } }, "internal" }
})
```

**Comment by waruqi** [comment]
I tried to implement it, but it seems a bit complicated and its configuration syntax is a bit complex. If you want to configure it, use `add_includedirs("include", { public = true })`

**Comment by paul-reilly** [comment]
No problem, thanks for trying. I did not know that the target function could take more arguments like that either. It's very flexible. To be explicit for any future readers:

```lua

target("foo", {
    kind = "shared",
    files = "src/**.cpp",
    includedirs = "internal",
    packages = {
        "nlohmann_json",
        "tl_optional"
    }},
    add_includedirs("include",  { public = true })
)
```
