### ISSUE TITLE
调用过config --menu后生成的vs工程无法编译

### ISSUE THREAD

**Issue by vkensou** [xmake-io/xmake#4638]
### Xmake 版本

v2.8.6+HEAD.211710b67

### 操作系统版本和架构

Windows 10

### 描述问题

如果一个项目先用xmake config --menu设置过，再用xmake project -k vsxmake生成vs工程，那这个工程就无法编译了，会报错：error : Invalid option: --menu=true

### 期待的结果

正常编译

### 工程配置

用xmake模板即可重现：
1. xmake create -t console
2. xmake config --menu   点击save退出
3. xmake project -k vsxmake
4. 打开vs工程并编译即可重现问题

### 附加信息和错误日志

EXEC : error : Invalid option: --menu=true

**Comment by waruqi** [comment]
修复了 `xmake update -s dev`
