### ISSUE TITLE
$PATH got changed in build

### ISSUE THREAD

**Issue by yangrq1018** [xmake-io/xmake#4654]
### Xmake Version

v2.8.6+20231226

### Operating System Version and Architecture

Arch Linux, x86

### Describe Bug

The `PATH` environment variable is different in xmake build scripts from what I got in the terminal.

### Expected Behavior

The `PATH` should variable should be the same unless explicitly altered.

### Project Configuration

xmake.lua
```
target("main")
  set_kind("binary")
  add_files("**.cpp")
  on_load("windows", "linux", "macosx", function(target)
    print(os.getenv('PATH'))
  end)
target_end()
```
main.cpp
```
int main() {
    return 0;
}
```

Run `xmake build` gives
```
❯ xmake b main
/usr/bin:/home/martin/anaconda3/bin:/home/martin/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/bin/site_perl:/usr/bin/vendor_perl
:/usr/bin/core_perl:/home/martin/go/bin
[ 25%]: cache compiling.release main.cpp
[ 50%]: linking.release main
[100%]: build ok, spent 0.124s
```

While run `echo $PATH` in the same terminal gives
```
❯ echo $PATH
/home/martin/anaconda3/bin:/home/martin/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl
:/usr/bin/core_perl:/home/martin/go/bin:/home/martin/go/bin:/home/martin/go/bin
```

### Additional Information and Error Logs

None

**Comment by yangrq1018** [comment]
I can reproduce this on another WSL Ubuntu, it seems xmake put where it is installed at the very first of $PATH

**Comment by yangrq1018** [comment]
看了一下应该是这里
```
 -- add the directory of the program file (xmake) to $PATH environment
    local programfile = os.programfile()
    if programfile and os.isfile(programfile) then
        os.addenv("PATH", path.directory(programfile))
    else
        os.addenv("PATH", os.programdir())
    end
```
这是处于什么考虑？我的$PATH上有pacman依赖安装的python, conda base python和一个conda env里的python,
xmake把自己所在的路径加到最前面，导致我根本没办法在build过程里判断目前激活的是哪个python环境，这对pybind11是很重要的，有时候需要给特定的python版本编译动态库。

**Comment by waruqi** [comment]
忘记了，这块很久之前加的了，还是7年前的事情了。https://github.com/xmake-io/xmake/commit/7ef69739513b4b4431f6f683fe2a9d297658be02

**Comment by waruqi** [comment]
我估计当初是为了 xmake 内部调用 xmake 自身命令时候用的，内部目前都是直接执行了 xmake 

```lua
os.vrunv("xmake", {"create", "-P", "."})
````

如果这是这个原因，理论上可以去掉，走全路径执行，但是目前类似这种的直接调用地方太多，要全部改，估计也要费点时间，还得详细测试下

**Comment by yangrq1018** [comment]
或者加在path最后面都好很多，至少不影响python环境的判断

**Comment by waruqi** [comment]
加选项不太可能，这个阶段处于启动阶段，选项都还没开始解析呢。。加后面也不太行，启动阶段就是追加再最后的，后面的 path 都还没开始设置呢，后面的其他 path 设置了，它就处于最开头位置了。。

只有想办法去掉，没其他办法。

**Comment by yangrq1018** [comment]
好吧，那我先用CONDA_PREFIX判断吧，不过普通python环境或者venv就没办法了。。最好还是去掉，这么改path感觉容易出一些其他很难溯源的问题

**Comment by waruqi** [comment]
可以试下这个 patch https://github.com/xmake-io/xmake/pull/4658

**Comment by yangrq1018** [comment]
Tested with conda base and conda env. OK.

FYI: I built xmake with this AUR package with branch modified: https://aur.archlinux.org/packages/xmake-git.

**Comment by waruqi** [comment]
我 merge 了

**Comment by waruqi** [comment]
> Tested with conda base and conda env. OK.
> 
> FYI: I built xmake with this AUR package with branch modified: https://aur.archlinux.org/packages/xmake-git.

xmake 已经在 arch 官方源里面的，aur 里面之前也有 xmake，后来移到 arch 仓库后，自动归档了。

**Comment by yangrq1018** [comment]
pacman那个库是release才会更新的吧，你merge了之后我如果要用这个版本还是得用AUR吧
