### ISSUE TITLE
Improve the script pattern

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#4657]
### 你在什么场景下需要该功能？

在写package的时候目前声明支持的平台只能声明plat|arch：
```
on_install("windows|x64", "macosx|x86_64", ...
```
然而很多时候是编译脚本不支持交叉编译（可能中间需要运行一些编译生成的工具），并不是平台不受支持。例如windows+arm64和macosx+arm64其实很多包是支持的，但是ci上跑的是交叉编译，所以才ci不过。但目前没有办法声明一个包仅支持本地编译，所以为了ci通过只好禁用arm64.

### 描述可能的解决方案

交叉编译需要显式声明：
```
on_install("windows", "windows|cross", ...
```
而不声明则默认禁用交叉编译；

### 描述你认为的候选方案

在arch处允许取反运算`!...`
```
on_install("windows|!cross", ...
on_install("windows|cross", ...
```
这样取反也能扩展到其他architecture的声明，更加灵活。这里vcpkg也是支持这么做的。

如果不引入取反，也可以arch写一个native：
```
on_install("windows|native", ...
```

**Comment by SirLynix** [comment]
Also, it would be great to be able to just disallow a platform:
```lua
on_install("!wasm", ...) -- every platform except web
```
instead of writing
```lua
on_install("windows", "linux", "macos", "bsd", "iphoneos", "android", "cross", ...)
```

**Comment by waruqi** [comment]
> Also, it would be great to be able to just disallow a platform:
> 
> ```lua
> on_install("!wasm", ...) -- every platform except web
> ```
> 
> instead of writing
> 
> ```lua
> on_install("windows", "linux", "macos", "bsd", "iphoneos", "android", "cross", ...)
> ```

I have supported it.

matched pattern:
 `plat|arch@subhost|subarch`

e.g.

`@linux`
`@linux|x86_64`
`@macosx,linux`
`android@macosx,linux`
`android|armeabi-v7a@macosx,linux`
`android|armeabi-v7a,iphoneos@macosx,linux|x86_64`
`android|armeabi-v7a@linux|x86_64`
`linux|*`

excluded pattern:
 `!plat|!arch@!subhost|!subarch`

e.g.

`@!linux`
`@!linux|x86_64`
`@!macosx,!linux`
`!android@macosx,!linux`
`android|!armeabi-v7a@macosx,!linux`
`android|armeabi-v7a,!iphoneos@macosx,!linux|x86_64`
`!android|armeabi-v7a@!linux|!x86_64`
`!linux|*`

**Comment by waruqi** [comment]
@xq114 native/cross 暂时不太好支持，这两个概念，以及约定包含的 arch,plat集比较模糊，用户想要知道当前哪些是属于 native 和 cross ，需要翻文档研究半天才能确定，太繁琐，容易产生困扰，暂时可以通过取反来处理

**Comment by waruqi** [comment]
> > @xq114 native/cross 暂时不太好支持，这两个概念，以及约定包含的 arch,plat集比较模糊，用户想要知道当前哪些是属于 native 和 cross ，需要翻文档研究半天才能确定，太繁琐，容易产生困扰，暂时可以通过取反匹配来处理
> 
> 现在已经有了package:is_cross()的api， #4715 还提到了需要全局的is_cross，只要语义保持一致就好；实际上只有ci上win/mac交叉编译出错才会加这个，用户不了解其实也没关系

`|native` 支持了，cross 那个就没必要了，直接 `|!native` 取反就行了

**Comment by waruqi** [comment]
现在支持 `and`, `or`, `(a and b)` 等简单的逻辑表达，来描述平台的组合匹配模式了
https://github.com/xmake-io/xmake/issues/4973
