### ISSUE TITLE
v2.2.7无法生成config.h

### ISSUE THREAD

**Issue by setupsong** [xmake-io/xmake#466]
target("vbar")
    set_configvar("prefix", "VBAR_CONFIG")
    set_configdir("include/vbar/")
    add_configfiles("include/vbar/config.h.in")
这么配置后，没有生成config.h

**Comment by waruqi** [comment]
我这测试可以的么：

```console
ruki:testf ruki$ xmake f -c
checking for the architecture ... x86_64
checking for the Xcode directory ... /Applications/Xcode.app
checking for the SDK version of Xcode ... 10.14
checking for the Cuda SDK directory ... /Developer/NVIDIA/CUDA-10.1
generating include/vbar/config.h.in ... cache
ruki:testf ruki$ tree ./
./
├── include
│   └── vbar
│       ├── config.h
│       └── config.h.in
├── src
│   └── main.c
└── xmake.lua
```

你先确认下有没有 include/vbar/config.h.in 在对应路径下，可以尝试加-c 执行 `xmake f -c` 强制清空cache配置，重新生成 configfiles试试

**Comment by setupsong** [comment]
请问config.h.in是自动生成的吗？还是说我要先配置好config.h.in，根据config.h.in自动生成config.h？

**Comment by waruqi** [comment]
需要内置一个模板文件 xxx.in 具体看下文档

https://xmake.io/#/zh-cn/manual/project_target?id=targetadd_configfiles
