### ISSUE TITLE
find_tool cache problem

### ISSUE THREAD

**Issue by yangrq1018** [xmake-io/xmake#4663]
### Xmake Version

xmake v2.8.6+master.445e43b40, A cross-platform build utility based on Lua

### Operating System Version and Architecture

Arch Linux, x86

### Describe Bug

```
        local python = assert(find_tool("python", {paths = {}, version = true}), "python not found, please install it first! note: python version must > 3.0")
        print(python.version)

```
Run these twice, give me different result
```
$ xmake clean core
3.9.18
$ xmake clean core
3.11.5
```

### Expected Behavior

Versions should be the same

### Project Configuration

I have conda env activated

### Additional Information and Error Logs

None

**Comment by yangrq1018** [comment]
If I hard code like this, the result is correct
```
        local python = assert(find_tool("python", {paths = {'/home/martin/anaconda3/envs/hikyuu/bin'}, version = true}), "python not found, please install it first! note: python version must > 3.0")
```

**Comment by yangrq1018** [comment]
```
-- save result
    detectcache:set2(cachekey, program, result and result or false)
    detectcache:save()
    return result
```
Could this be the reason?

Anyway for now I might just do `python -c "import sys; print(sys.version_info)"` and parse it by myself...

**Comment by waruqi** [comment]
did you call `print(python)` and let me see your python path output.

**Comment by yangrq1018** [comment]
Calls find_tools with `find_tool("python", {version = true})`, print(python) shows
```
{ 
  program = "/home/martin/anaconda3/bin/python",
  version = "3.11.5",
  name = "python" 
}
```

```
$ echo $PATH
/home/martin/anaconda3/envs/hikyuu/bin:/home/martin/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin
/vendor_perl:/usr/bin/core_perl:/home/martin/go/bin:/home/martin/go/bin:/home/martin/go/bin
```

This is fine, I can understand that xmake probably throws away current $PATH variable and starts a new session to find python.

But this is weird:
```
        local p1 = '/home/martin/anaconda3/envs/hikyuu/bin'
        local p2 = os.getenv('CONDA_PREFIX') .. "/bin"
        print(p1)
        print(p2)
        local python = assert(find_tool("python", {paths={p2}, version = true}), "python not found, please install it first! note: python version must > 3.0")
        print(python)
```
If I set paths to `p1`, I always get the right python (the conda env one). If I set paths to `p2`, I got the conda env python for the first run, after that I always got the base one. The first run takes significantly more than to execute than later, it looks like something is cached here.

**Comment by waruqi** [comment]
? please show logs. I don't understand your means.

**Comment by yangrq1018** [comment]
MVP xmake.lua:
```lua
target("foo")
  set_kind("binary")
  add_files("main.cpp")
  on_load("windows", "linux", "macosx", function(target)
    import("lib.detect.find_tool")
    local py_path = os.getenv("CONDA_PREFIX") .. "/bin"
    print(py_path)
    local python = find_tool("python", {paths = {py_path}, version = true})
    print(python)
  end)
target_end()
```



```
$ xmake b main
/home/martin/anaconda3/bin
{
  program = "/home/martin/anaconda3/bin/python",
  version = "3.11.5",
  name = "python"
}

[100%]: build ok, spent 0.003s
$ conda activate hikyuu
$ xmake b main
/home/martin/anaconda3/envs/hikyuu/bin
{
  version = "3.11.5",
  program = "/home/martin/anaconda3/bin/python",
  name = "python"
}
```
I can't consistently get these outputs, the output is random, but this run is buggy obviously.
[100%]: build ok, spent 0.002s
```

**Comment by waruqi** [comment]
> Sorry for my example, they are a bit project specific.
> 
> Minimal Reproducible Example `xmake.lua`:
> 
> ```lua
> target("foo")
>   set_kind("binary")
>   add_files("main.cpp")
>   on_load("windows", "linux", "macosx", function(target)
>     import("lib.detect.find_tool")
>     local py_path = os.getenv("CONDA_PREFIX") .. "/bin"
>     print(py_path)
>     local python = find_tool("python", {paths = {py_path}, version = true})
>     print(python)
>   end)
> target_end()
> ```
> 
> ```
> $ xmake b main
> /home/martin/anaconda3/bin
> {
>   program = "/home/martin/anaconda3/bin/python",
>   version = "3.11.5",
>   name = "python"
> }
> 
> [100%]: build ok, spent 0.003s
> $ conda activate hikyuu
> $ xmake b main
> /home/martin/anaconda3/envs/hikyuu/bin
> {
>   version = "3.11.5",
>   program = "/home/martin/anaconda3/bin/python",
>   name = "python"
> }
> 
> [100%]: build ok, spent 0.002s
> ```
> 
> I can't consistently get these outputs, the output is random, but this run is buggy obviously.

I don't see any problems, looking at the logs it runs fine.

find_tool has detect cache, if you want to force to re-find it. please pass `{force = true}` in find_tool

**Comment by yangrq1018** [comment]
So the cache is based on variable name rather than value?

**Comment by yangrq1018** [comment]
You are right, pass `{force = true}` does give me expected behavior. I guess this is a feature not bug then. Perhaps the documentation should elaborate a bit more about this.
