### ISSUE TITLE
 C++ Modules包

### ISSUE THREAD

**Issue by dayu521** [xmake-io/xmake#4669]
### Xmake 版本

2.8.6

### 操作系统版本和架构

archlinux

### 描述问题

当在一个xmake工程中引用c++20模块包时,首次运行xmake命令可以成功编译.

如果修改了工程文件,再次使用xmake,则报错找不到模块,除非把工程整个清理,重新配置编译

xmake c -va 

xmake

这样才可以

### 期待的结果

修改xmake工程文件,不应该影响模块依赖的查找

### 工程配置

使用xmake源码下的测试例子.第一次运行 xmake

添加了add_defines("AA")

再次运行 xmake 失败

### 附加信息和错误日志

error: src/main.cpp:1:1: error: unknown Compiled Module Interface: no such module
    1 | import foo;
      | ^~~~~~
src/main.cpp:2:1: error: unknown Compiled Module Interface: no such module
    2 | import bar;
      | ^~~~~~
In module imported at src/main.cpp:1:1:
foo: error: failed to read compiled module: Unknown CMI mapping
foo: note: imports must be built before being imported
foo: fatal error: returning to the gate for a mechanical issue

**Comment by waruqi** [comment]
试下这个 patch 呢，最近在重构。。https://github.com/xmake-io/xmake/pull/4321

或者等这个 patch 搞完，你再试试

**Comment by dayu521** [comment]
> 试下这个 patch 呢，最近在重构。。#4321
> 
> 或者等这个 patch 搞完，你再试试

好的谢谢.期待下个版本发布时可以重构好
