### ISSUE TITLE
无法使用内置扩展将object类型的目标导出为vs工程

### ISSUE THREAD

**Issue by veritas-Qiu** [xmake-io/xmake#4671]
### Xmake 版本

v2.8.6+HEAD.211710b67

### 操作系统版本和架构

Windows 11 23H2

### 描述问题

提示找不到合适的链接器，生成失败

### 期待的结果

正确生成vs工程

### 工程配置

    target("test")
        set_kind("object")
        add_files("test.cpp")

### 附加信息和错误日志

    ❯ xmake project -k vsxmake
    checking for Microsoft Visual Studio (x64) version ... 2022
    checking for debug.x64 ...
    checking for Microsoft Visual Studio (x64) version ... 2022
    error: no suitable linker for object.{cxx cc}

**Comment by waruqi** [comment]
不支持
