### ISSUE TITLE
cuda 编程报错 Cuda Runtime (CUDA driver is a stub library)

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#4686]
### Xmake 版本

2.8.5+20231124

### 操作系统版本和架构

Linux 720ce3a659a2 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

cuda 代码编译正常，但是运行时报错 [Cuda Runtime (CUDA driver is a stub library)](https://forums.developer.nvidia.com/t/checkmacros-cpp-272-error-code-1-cuda-runtime-cuda-driver-is-a-stub-library/202911)

![image](https://github.com/xmake-io/xmake/assets/47598093/9ce5f398-ea8b-4705-a3ef-7b5496bffae1)

看日志是 LD_LIBRARY_PATH 引用到了 /usr/local/cuda/lib64/stubs，
![image](https://github.com/xmake-io/xmake/assets/47598093/90d52fbc-1f7e-4a57-96a9-a20fe22e0102)
![image](https://github.com/xmake-io/xmake/assets/47598093/103a1813-a422-43dd-b74a-1655169617ef)

是出于什么考虑呢，我手动改成 其他路径是可以正常运行的。

### 期待的结果

能正确链接 cuda 动态库

### 工程配置

```bash
add_cuflags("--use_fast_math", {force = true})
add_cuflags("-Xcompiler -fPIC", {force = true})
add_cuflags("--expt-relaxed-constexpr", {force = true})

add_cugencodes("compute_70", "compute_70")
```

### 附加信息和错误日志

```bash
$xmake run map/geometric_map/polyline_width_kernel_test
Running main() from gtest_main.cc
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from PolylineWidthKernelTest
[ RUN      ] PolylineWidthKernelTest.MakeHashTableTest
CUDA API Error at line 28: CUDA driver is a stub library
```

**Comment by waruqi** [comment]
忘记了，你可以提个 pr 过来

**Comment by TOMO-CAT** [comment]
> 忘记了，你可以提个 pr 过来

#4688 
提了一个 MR，因为涉及到 cuda 版本的问题没有一个绝对的 linkdir，不过一般都配在用户的 LD_LIBRARY_PATH 里。再不济也可以用户手动指定。
