### ISSUE TITLE
add_deps 的 {inherit = false} 未生效

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#4689]
### Xmake 版本

xmake v2.8.5

### 操作系统版本和架构

Linux 720ce3a659a2 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

target `basic_test` 需要依赖 target `zumm_server_main` 编译完成的二进制，但是通过 add_deps("zumm_server_main") 方式会引入额外的链接参数（zumm_server_main 依赖 zumm_server）。

### 期待的结果

有两个解决思路
* add_deps 是不是可以提供类似 add_deps("xxx", {links = {}}) 的功能。
* 显示指定 targetB 需要在 targetA 编译完成后才能运行，类似于 set_run_deps

### 工程配置

![image](https://github.com/xmake-io/xmake/assets/47598093/4a7a1ce5-d1c5-4d8c-89a9-0966076d95d7)

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
等这个 patch https://github.com/xmake-io/xmake/pull/4698 你也可以先试下

**Comment by waruqi** [comment]
再试试 xmake update -s dev
