### ISSUE TITLE
`set_kind("shared")` but is_kind("static").

### ISSUE THREAD

**Issue by traversebitree** [xmake-io/xmake#4690]
### Xmake Version

2.8.6

### Operating System Version and Architecture

windows-latest, ubuntu-latest, macOS-latest

### Describe Bug

I have set `set_kind("shared")` in target, but `is_kind("static")`. 
虽然我给库目标设置了`set_kind("shared")`，但是通过`print`测试结果是`is_kind("static")`。

This issue exists on every operating system.
在每个操作系统上都有这个问题。

Details in below:
详见一个测试示例库和action结果:
- repo: [https://github.com/traversebitree/test_xmake_dll_bug](https://github.com/traversebitree/test_xmake_dll_bug)
- action repots: [https://github.com/traversebitree/test_xmake_dll_bug/actions/runs/7772914272](https://github.com/traversebitree/test_xmake_dll_bug/actions/runs/7772914272)

![image](https://github.com/xmake-io/xmake/assets/30373236/90ddfdf3-638d-46cb-8a08-0a13308c1005)

### Expected Behavior

Set `set_kind("shared")` in target, and `is_kind("shared")`.
设置为`set_kind("shared")`，那么一定要`is_kind("shared")`。

### Project Configuration

只有一个`xmake.lua`
Only one `xmake.lua` at root
```lua
add_rules("mode.debug", "mode.release")

target("shared_lib")
    set_kind("shared")
    add_files("src/shared_lib/libabc_shared.cpp")
    -- Debug info
    if is_kind("shared") then
       print("[Debug Print] is shared.") 
    end
    if is_kind("static") then
       print("[Debug Print] is static") 
    end
    -- End Debug info
    if is_plat("windows") and is_kind("shared") then
        add_rules("utils.symbols.export_all", {export_classes = true})
    end

target("main")
    set_kind("binary")
    add_files("src/main/main.cpp")
    add_deps("shared_lib")
```

### Additional Information and Error Logs

```sh
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.37.32826.1
[Debug Print] is static
[Debug Print] is static
[Debug Print] is static
[Debug Print] is static
[ 2[5](https://github.com/traversebitree/test_xmake_dll_bug/actions/runs/7772914272/job/21195950310#step:5:6)%]: compiling.release src\shared_lib\libabc_shared.cpp
[ 25%]: compiling.release src\main\main.cpp
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.3[7](https://github.com/traversebitree/test_xmake_dll_bug/actions/runs/7772914272/job/21195950310#step:5:8).32[8](https://github.com/traversebitree/test_xmake_dll_bug/actions/runs/7772914272/job/21195950310#step:5:9)22\include\ostream(780): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\include\ostream(2[9](https://github.com/traversebitree/test_xmake_dll_bug/actions/runs/7772914272/job/21195950310#step:5:10)3): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
[ 50%]: linking.release shared_lib.dll
[ 75%]: linking.release main.exe
error: LINK : fatal error LNK[11](https://github.com/traversebitree/test_xmake_dll_bug/actions/runs/7772914272/job/21195950310#step:5:12)81: cannot open input file 'shared_lib.lib'

Error: Process completed with exit code 1.
```

**Comment by SirLynix** [comment]
is_kind doesn't test the target kind, but the kind config.

You have to use a callback to get a target kind using `if target:kind() == "static" then`

**Comment by traversebitree** [comment]
> is_kind doesn't test the target kind, but the kind config.
> 
> You have to use a callback to get a target kind using `if target:kind() == "static" then`

Thank you for your reply. Does that mean I need to define a function in `on_load()` and then put `if target:kind() == "static" then` in this function??

**Comment by waruqi** [comment]
is_kind 仅用于判断 `xmake f -k static` 传入的 kind 配置。。

**Comment by traversebitree** [comment]
Thank you very much for @waruqi and @SirLynix . With your help, I finally managed to solve the problem. Here is the code, some refer to [使用 Xmake 生成静态和动态库](https://zhuanlan.zhihu.com/p/596605872#:~:text=%E4%B8%8A%E9%9D%A2%E5%8F%AA%E6%98%AF%E4%B8%B4%E6%97%B6%E7%94%A8%E6%B3%95%EF%BC%8C%E5%AE%9E%E9%99%85%E5%9C%A8%E5%B7%A5%E7%A8%8B%E4%B8%AD%EF%BC%8C%E6%88%91%E6%8E%A8%E8%8D%90%E4%BD%BF%E7%94%A8%E8%A7%84%E5%88%99%E3%80%82%E4%B8%8B%E9%9D%A2%E4%BB%A3%E7%A0%81%E5%92%8C%E4%B8%8A%E9%9D%A2%E6%95%88%E6%9E%9C%E6%98%AF%E4%B8%80%E6%A0%B7%E7%9A%84%E3%80%82).

```lua
add_rules("mode.debug", "mode.release")
add_rules("set_export_all_symbols")

rule("set_export_all_symbols")
do 
    on_load(function (target)
        if target:kind()=="static" then
            target:set("kind","static")
        elseif target:kind()=="shared" then
            target:set("kind","shared")
            if is_plat("windows") then 
                import("core.project.rule")
                local rule = rule.rule("utils.symbols.export_all")
                target:rule_add(rule)
                target:extraconf_set("rules", "utils.symbols.export_all", {export_classes = true})
            end
        end
    end)
end 

target("shared_lib")
do
    set_kind("shared")    
    add_files("src/shared_lib/libabc_shared.cpp")
end

target("main")
do
    set_kind("binary")
    add_files("src/main/main.cpp")
    add_deps("shared_lib")
end
```

**Comment by SirLynix** [comment]
I don't understand why you need to test target kind, 'cause you always set it to shared.
```lua
target("shared_lib", function ()
    set_kind("$(kind)") -- set kind from config (xmake f --kind=shared or xmake f --kind=static)
    if is_kind("shared") then -- kind can be tested from config
        add_rules("utils.symbols.export_all", {export_classes = true})
    end 
    add_files("src/shared_lib/libabc_shared.cpp")
end)

target("main", function ()
    set_kind("binary")
    add_files("src/main/main.cpp")
    add_deps("shared_lib")
end)
```

**Comment by traversebitree** [comment]
> I don't understand why you need to test target kind, 'cause you always set it to shared.
> 
> ```lua
> target("shared_lib", function ()
>     set_kind("$(kind)") -- set kind from config (xmake f --kind=shared or xmake f --kind=static)
>     if is_kind("shared") then -- kind can be tested from config
>         add_rules("utils.symbols.export_all", {export_classes = true})
>     end 
>     add_files("src/shared_lib/libabc_shared.cpp")
> end)
> 
> target("main", function ()
>     set_kind("binary")
>     add_files("src/main/main.cpp")
>     add_deps("shared_lib")
> end)
> ```

@SirLynix  Because I'm used to developing code in VSCode, VSCode's xmake extension has a direct **build** button (equivalent to `xmake --all`), and I'm used to clicking that button directly instead of typing `xmake f --kind=shared/static` on the command line, so I'll be developing with `static` or `shared` hardcoded during development. 😆 

![image](https://github.com/xmake-io/xmake/assets/30373236/0e4ab706-693c-4ff8-a6a1-3fec21765989)
