### ISSUE TITLE
vs有多个版本切换失败

### ISSUE THREAD

**Issue by rooong** [xmake-io/xmake#4703]
### Xmake 版本

2.8.6

### 操作系统版本和架构

windows 10/windows7

### 描述问题

问题1：
（1）在windows10中，同时安装vs2013、vs2022，使用命令xmake默认使用vs2022构建，在代码中打印_MSC_VER可输出1938（vs2022的），使用xmake f --vs=2013后，重新编译，运行代码_MSC_VER还是输出1938；
（2）使用xmake project -k vsxmake2013 -m "debug,release"，看输出用的还是vs2022的
![image](https://github.com/xmake-io/xmake/assets/38597332/38827fe8-0a1e-42f1-893f-797d2a432145)

问题2：
在windows7中，同时安装vs2013、vs2019，在代码中打印_MSC_VER值，报错_MSC_VER未定义

### 期待的结果

可正常切换vs版本，在低版本vs可正常构建工程

### 工程配置

[hello.zip](https://github.com/xmake-io/xmake/files/14161931/hello.zip)

### 附加信息和错误日志

![image](https://github.com/xmake-io/xmake/assets/38597332/a4eea955-e4e4-45bb-931e-4c7eee96ac2e)

**Comment by waruqi** [comment]
```console
xmake f --vs=2013 -cvD
xmake -rvD
xmake f --vs=2022 -cvD
xmake -rvD
```

给下完整 logs 输出

**Comment by rooong** [comment]
[log.txt](https://github.com/xmake-io/xmake/files/14174425/log.txt)
不知道为啥，今天vs2013和vs2022可以正常切换了。。。我机器都没重启的，很莫名

[log-win7.txt](https://github.com/xmake-io/xmake/files/14174459/log-win7.txt)
问题2，windows7的还在

**Comment by waruqi** [comment]
> E:\M_Server\xmake_test\hello>xmake f --vs=vs2013 -cvD
checking for platform ... windows
checking for architecture ... x64
checking for cl.exe ... C:\Program Files (x86)\Microsoft Visual Studio\2019\Ente
rprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2019

仔细点，应该是 `--vs=2013` 不是 `--vs=vs2013` 。。vs 版本还是 2019 都没切成功。。你切 2019 敲对了，2013 没对

**Comment by rooong** [comment]
> > E:\M_Server\xmake_test\hello>xmake f --vs=vs2013 -cvD
> > checking for platform ... windows
> > checking for architecture ... x64
> > checking for cl.exe ... C:\Program Files (x86)\Microsoft Visual Studio\2019\Ente
> > rprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe
> > checking for Microsoft Visual Studio (x64) version ... 2019
> 
> 仔细点，应该是 `--vs=2013` 不是 `--vs=vs2013` 。。vs 版本还是 2019 都没切成功。。你切 2019 敲对了，2013 没对

刚刚这个在windows7上是打错了，但是我现在重新试了下，还是一样，问题2仍旧

**Comment by waruqi** [comment]
那就重新给 logs

**Comment by rooong** [comment]
[log-win7.txt](https://github.com/xmake-io/xmake/files/14174516/log-win7.txt)

**Comment by waruqi** [comment]
> [log-win7.txt](https://github.com/xmake-io/xmake/files/14174516/log-win7.txt)

不是正常了么，2013/2019 都切成功了，编译也没问题。。编译器也用对了。。没啥问题

**Comment by rooong** [comment]
这个是说，构建的时候，都不能正常识别vs的版本宏_MSC_VER，有用到跨平台编译的代码，就有问题了

**Comment by waruqi** [comment]
> 这个是说，构建的时候，都不能正常识别vs的版本宏_MSC_VER，有用到跨平台编译的代码，就有问题了

这是编译器的问题，跟 xmake 无关，xmake 只保证能正常检测和使用到对应版本的 vs ，现在它确实已经切到到了正确的 vs 版本，用的 cl.exe 也是对的，如果里面宏不对，你得问 微软了。
