### ISSUE TITLE
A is_cross() function in the description scope

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#4715]
### Is your feature request related to a problem? Please describe.

I need to know when my project is cross-compiling because it needs to requires a host package to use its binary (shader compiler).

I took `package:is_cross()` code as a reference:
https://github.com/xmake-io/xmake/blob/6d635f24fda7ce5e31c5350cf67415e26ff1452f/xmake/core/package/package.lua#L685-L707 to implement my own:

```lua
if has_config("renderer") then
	add_requires("nzsl >=2023.12.31", { debug = is_mode("debug"), configs = { symbols = not is_mode("release"), shared = not is_plat("wasm", "android") and not has_config("static") } })

	local function is_cross_compiling()
		if os.host() == "windows" then
			local host_arch = os.arch()
			if is_plat("windows") then
				-- maybe cross-compilation for arm64 on x86/x64
				if (host_arch == "x86" or host_arch == "x64") and is_arch("arm64") then
					return true
				-- maybe cross-compilation for x86/64 on arm64
				elseif host_arch == "arm64" and not is_arch("arm64") then
					return true
				end
				return false
			elseif is_plat("mingw") then
				return false
			end
		end
		if not is_plat(os.host()) and not is_plat(os.subhost()) then
			return true
		end
		if not is_arch(os.arch()) and not is_arch(os.subarch()) then
			return true
		end
		return false
	end

	-- When cross-compiling, compile shaders using host shader compiler
	if has_config("compile_shaders") and is_cross_compiling() then
		add_requires("nzsl~host", { kind = "binary", host = true })
	end
end
```

### Describe the solution you'd like

I think knowing if we're cross-compiling is a common need and a `is_cross` function may be useful to many.

### Describe alternatives you've considered

Implementing it myself, but it's a lot of lines for something xmake already does

**Comment by ifarbod** [comment]
Unrelated, but, can you cross-compile for Android, on Windows, _without_ WSL? I couldn't find anything related to this in Xmake docs.

**Comment by SirLynix** [comment]
> Unrelated, but, can you cross-compile for Android, on Windows, _without_ WSL? I couldn't find anything related to this in Xmake docs.

Yes it's possible, use NDK Windows binaries.  
But please don't use feature requests/issues to ask unrelated questions, create a [discussion](https://github.com/xmake-io/xmake/discussions) or ask on [Discord](https://discord.gg/xmake)

**Comment by waruqi** [comment]
I added it. https://github.com/xmake-io/xmake/pull/4739

**Comment by SirLynix** [comment]
Thanks! but is it available in the description scope ?

I tried to use it by switching to the branch `xmake update -s cross`
```shell
xmake f --check
checking for Microsoft Visual Studio (x64) version ... 2022
error: .\xmake.lua:358: global 'is_cross' is not callable (a nil value)
stack traceback:
    [.\xmake.lua:358]: in main chunk
```

**Comment by waruqi** [comment]
try it again. on dev

**Comment by SirLynix** [comment]
works great, thanks!
