### ISSUE TITLE
xmake generates a wrong cpp compiler path in cuda project

### ISSUE THREAD

**Issue by HiiroAyane** [xmake-io/xmake#4716]
### Xmake Version

2.8.6

### Operating System Version and Architecture

windows10

### Describe Bug

the compile_commands.json generated by xmake is like this:
[
{
  "directory": "d:\\Cuda\\CCuda",
  "arguments": ["C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.3\\bin\\nvcc.exe", "-c", "-ccbin=\"C:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2019\\\\Community\\\\VC\\\\Tools\\\\MSVC\\\\14.29.30133\\\\bin\\\\Hostx64\\\\x64\\\\cl.exe\"", "-O3", "-I\"C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.3\\include\"", "-m64", "-rdc=true", "-gencode", "arch=compute_75,code=sm_75", "-gencode", "arch=compute_50,code=compute_50", "-o", "build\\.objs\\CCuda\\windows\\x64\\release\\src\\main.cu.obj", "src\\main.cu", "-imsvc", "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\cppwinrt", "-imsvc", "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\shared", "-imsvc", "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\ucrt", "-imsvc", "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\um", "-imsvc", "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\winrt", "-imsvc", "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\include"],
  "file": "src\\main.cu"
}]
path of cl.exe has \\\\ instead of  \\. and when xmake build main.cu nvcc report a error like:
error: Failed to run "C:////Program Files (x86)////Microsoft Visual Studio////2019////Community////VC////Tools////MSVC////14.29.30133////bin////Hostx64////x64/cl.exe" (拒绝访问。
).
nvcc fatal   : Failed to preprocess host compiler properties.

### Expected Behavior

maybe cl.exe 's path like C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe could be correct.

### Project Configuration

default project generated by cmd: xmake create -P CCuda -l cuda

### Additional Information and Error Logs

no more error logs

**Comment by waruqi** [comment]
你是不是手动指定了 `xmake f --cu-ccbin=` 或者当前环境变量存在 `%CC%`, `%CXX%` 指向了 cl.exe 路径，去了试试呢，按理默认不会传 ccbin 才对

**Comment by waruqi** [comment]
try this patch https://github.com/xmake-io/xmake/pull/4718

**Comment by waruqi** [comment]
可以了么

**Comment by HiiroAyane** [comment]
> 你是不是手动指定了 `xmake f --cu-ccbin=` 或者当前环境变量存在 `%CC%`, `%CXX%` 指向了 cl.exe 路径，去了试试呢，按理默认不会传 ccbin 才对

是的，有CXX指向cl.exe

**Comment by HiiroAyane** [comment]
> > 你是不是手动指定了 `xmake f --cu-ccbin=` 或者当前环境变量存在 `%CC%`, `%CXX%` 指向了 cl.exe 路径，去了试试呢，按理默认不会传 ccbin 才对
> 
> 是的，有CXX指向cl.exe

但我删掉CXX环境变量，使用xmake build也会这样报错，会有4个\\\\路径分隔符

**Comment by HiiroAyane** [comment]
> try this patch #4718

从ccbin分支源码编译安装xmake出错，提示如下：
error: file(D:\Github\xmake\core\src\sv\sv\xmake.lua): file not found!
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2019
error: file(D:\Github\xmake\core\src\sv\sv\xmake.lua): file not found!

**Comment by waruqi** [comment]
> > try this patch #4718
> 
> xmake update -s github:xmake-io/xmake#ccbin 安装了patch后，确实xmake build成功了，考虑后续加入主分支吗？

已经 merge 了
