### ISSUE TITLE
add_requires 顺序导致 package 无法引入

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#4717]
### Xmake 版本

2.8.5+20231124

### 操作系统版本和架构

Ubuntu 20.04.5 LTS

### 描述问题

如果我调转 add_requires() 的顺序，target:add_packages 就会找不到依赖。
![1875504d82a6ded43cec3c72d2e551d7](https://github.com/xmake-io/xmake/assets/47598093/e7f96124-de9b-4d4a-bed6-0f8848c497a4)
![7e7eddc39d7e21c961c61637d006bd68](https://github.com/xmake-io/xmake/assets/47598093/c5736fd2-f629-4fb5-acf4-39242a47382b)

因为 zgpu 本身依赖了 zproto，我怀疑是我的依赖（zgpu）已经引用了（zproto），所以当前项目就没必要再引用间接依赖了，能强制设置成直接依赖吗，因为我需要它的 proto 文件编译代码

### 期待的结果

因为我依赖成品库的一些 conf 和 proto 文件，所以必须要拿到 target:pkg("zproto") 的属性。

### 工程配置

无

### 附加信息和错误日志

src-zproto：
![image](https://github.com/xmake-io/xmake/assets/47598093/71f958de-67cb-4dec-a048-204def28fd36)
src-zgpu：
![image](https://github.com/xmake-io/xmake/assets/47598093/e68e3103-2733-41ef-95d3-37ffe92db572)

**Comment by waruqi** [comment]
给个完整可复现的 example
