### ISSUE TITLE
Pass windows path by add_defines().

### ISSUE THREAD

**Issue by traversebitree** [xmake-io/xmake#4731]
### Xmake Version

2.8.6

### Operating System Version and Architecture

Windows 11

### Describe Bug

在Windows下，通过`add_defines`传递路径，内置变量如`$(projectdir)`会传递进反斜线`\`，C++无法完美解析这样的宏，这些宏会被反斜线转义。即使使用 `path.cygwin_path`也如此。

> 示例repo: https://github.com/traversebitree/test_xmake_add_defines_windows_path
> 示例action结果: https://github.com/traversebitree/test_xmake_add_defines_windows_path/actions/runs/7869170614/job/21467723954

![image](https://github.com/xmake-io/xmake/assets/30373236/0b9e3d9c-887f-4522-b0aa-2bdcaa38595c)

### Expected Behavior

在Windows下，通过`add_defines`传递路径时，内置变量如`$(projectdir)`使用正斜线`/`而不是反斜线`\`。

### Project Configuration

```lua
add_rules("mode.debug", "mode.release")
add_rules("plugin.compile_commands.autoupdate", {outputdir = "."})

target("test_xmake_add_defines_windows_path")
    set_kind("binary")
    add_files("src/*.cpp")
    add_defines("TEST_PATH_1=\"$(projectdir)\"")
    
    local model_path="$(projectdir)"
    add_defines("TEST_PATH_2=\"" .. path.cygwin_path(model_path) .. "\"")
```

```cpp
#include <iostream>

using namespace std;

int main(int argc, char **argv) {
  cout << "hello world!" << endl;
  cout << TEST_PATH_1 << endl;
  cout << TEST_PATH_2 << endl;
  return 0;
}
```

### Additional Information and Error Logs

NA

**Comment by traversebitree** [comment]
在VS Code下，可以看到扩展后的字符串如图，路径被反斜线转义了

![image](https://github.com/xmake-io/xmake/assets/30373236/57e3cd7b-ec51-46f1-87a9-c920a6a2b6e1)

**Comment by xq114** [comment]
https://github.com/xmake-io/xmake/issues/1872 应该给add_defines也加上类似接口

目前可以先手动转：`model_path:gsub("\\", "\\\\")` 没有path.cygwin_path

**Comment by traversebitree** [comment]
> #1872 应该给add_defines也加上类似接口
> 
> 目前可以先手动转：`model_path:gsub("\\", "\\\\")` 没有path.cygwin_path

谢谢回复，我临时改成 `model_path:gsub("\\", "\\\\")` 但结果是一样的。
```lua
    local model_path= "$(projectdir)"
    add_defines("TEST_PATH_2=\"" .. model_path:gsub("\\", "\\\\") .. "\"")
```

> https://github.com/traversebitree/test_xmake_add_defines_windows_path/actions/runs/7869534539/job/21468833664

![image](https://github.com/xmake-io/xmake/assets/30373236/47d05e09-3e1f-4ea2-b93f-c9381acf96b7)

**Comment by traversebitree** [comment]
@xq114 如果不用内置变量（如`$(projectdir)`）就可以使用 `:gsub("\\", "\\\\")`

```lua
add_defines("TEST_PATH_3=\"" .. path.absolute("./"):gsub("\\", "\\\\") .. "\"")
```

**Comment by waruqi** [comment]
用 os.projectdir()

**Comment by traversebitree** [comment]
@waruqi 谢谢！确实可以，希望可以增加一个 `path.to_posix()` 内置函数，让所有平台路径统一输出（预解析了`$(projectdir)`等内置变量的路径），例如:
```lua
path.absolute("tests/model/model.onnx",$(projectdir)).to_posix()
```

**Comment by waruqi** [comment]
> @waruqi 谢谢！确实可以，希望可以增加一个 `path.to_posix()` 内置函数，让所有平台路径统一输出（预解析了`$(projectdir)`等内置变量的路径），例如:
> 
> ```lua
> path.absolute("tests/model/model.onnx",$(projectdir)).to_posix()
> ```

加了个 path.unix，但是你还是得用 os.progectdir
