### ISSUE TITLE
语法错误

### ISSUE THREAD

**Issue by Prince213** [xmake-io/xmake#474]
### 描述问题

`xmake repo -l` 输出在只找到一个仓库时使用了`repository`的复数形式`repositories`。

### 期待的结果

使用单数形式(`repository`)。

### 其他信息

文件为`/xmake/plugins/repo/main.lua`

**Comment by waruqi** [comment]
这就不用这么计较了吧，这种问题，你直接提个pr到dev分支不就好了。。github web上都可以直接改掉。。说不定还比提issues快了。。

**Comment by OpportunityLiu** [comment]
比起那个，buildir已经成creat级的错误了

**Comment by waruqi** [comment]
> 比起那个，buildir已经成creat级的错误了

我只是简写了下，两个dd看着别扭。。= =

**Comment by OpportunityLiu** [comment]
。。搞出refer来的人不会也是这么想的
