### ISSUE TITLE
compile_commands.json doesn't update when config changed

### ISSUE THREAD

**Issue by yhsb2k** [xmake-io/xmake#4740]
### Xmake Version

2.8.6

### Operating System Version and Architecture

Windows 11 Pro 23H2 22631.3155

### Describe Bug

```bash
xmake f -m release
xmake
```
See that `compile_commands.json` has `"-DNDEBUG"` and remember its **last changed timestamp**.

```bash
xmake clean
xmake f -m debug
xmake
```
See that `compile_commands.json` still contain `"-DNDEBUG"` and its **last changed timestamp** still the same.

### Expected Behavior

`compile_commands.json` should be updated on the next build when xmake configuration was changed to reflect current built config.

### Project Configuration

```lua
add_rules("mode.debug", "mode.release")
set_languages("c++20")

add_rules("plugin.compile_commands.autoupdate")

add_requires("gtest")
add_packages("gtest")

target("googletest-example")
    set_kind("binary")
    add_files("main.cpp")

```

### Additional Information and Error Logs
<details>
<summary>rebuild log</summary>

```
build cache stats:
cache directory: build\.build_cache
cache hit rate: 0%
cache hit: 0
cache hit total time: 0.000s
cache miss: 0
cache miss total time: 0.000s
new cached files: 0
remote cache hit: 0
remote new cached files: 0
preprocess failed: 0
compile fallback count: 0
compile total time: 0.000s

[100%]: build ok, spent 0.016s
```

</details>

**Comment by waruqi** [comment]
try it again. `xmake update -s dev`

**Comment by yhsb2k** [comment]
Great! Just wonderful!
