### ISSUE TITLE
xmake package 打包远程包时无法指定version选项（全局选项和局部选项冲突）

### ISSUE THREAD

**Issue by RimuruChan** [xmake-io/xmake#4741]
### Xmake 版本

2.8.6

### 操作系统版本和架构

Windows 11

### 描述问题

指定version选项报错

xmake package -f remote --version=1 --shasum=1
error: Invalid option: --version=123

但是如果去掉=1，变成
xmake package -f remote --version --shasum=1
那么竟然可以正常运行，并滑稽的生成一个
add_versions("true", "1")

### 期待的结果

正常生成add_versions("123", "1")

### 工程配置
```lua
add_rules("mode.debug", "mode.release")

target("test")
    add_files("src/**.cpp")
    add_includedirs("src")
    set_kind("shared")
    set_languages("cxx20")
    set_symbols("debug")
```

### 附加信息和错误日志

error: Invalid option: --version=123

**Comment by RimuruChan** [comment]
初步检查是Common options和Package options冲突了。。。导致后者匹配不到

**Comment by waruqi** [comment]
再试试

**Comment by RimuruChan** [comment]
正常了
