### ISSUE TITLE
Allow different versions of specific packages to use separate xmake.lua

### ISSUE THREAD

**Issue by RimuruChan** [xmake-io/xmake#4743]
### Is your feature request related to a problem? Please describe.

Currently, different versions of packages must be written in the same xmake.lua file, which makes it difficult to manage dependencies and automatically update package versions and other content.

### Describe the solution you'd like

For example,  if we have the original package `packages/c/ctre/xmake.lua`, we can simply specific a version by adding a folder `packages/c/ctre/${version}/xmake.lua`.

**Comment by waruqi** [comment]
没必要，你自己的包，自己 includes 下，就能实现任何组织方式，但是官方仓库的包，要尽可能的精简，统一的 xmake.lua 反而更容易维护。。


每个版本都搞一个 xmake.lua 反而不好维护。。而且会把仓库搞得很臃肿，拉取变慢。。想要改个配置，原本只需要改一行，现在变成每个 version 子目录下的 xmake.lua 的都得批量同步改一遍。。

如果你非要这么搞。自己 `includes(path.join(os.scriptdir(), "<version>/xmake.lua"))` 下就行了
