### ISSUE TITLE
支持写脚本函数来 set_config 以支持复杂项目配置

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#4755]
### 你在什么场景下需要该功能？

当前在描述域不支持调用自定义脚本，只能调用 xmake 提供的 [is_arch](https://xmake.io/#/zh-cn/manual/conditions?id=is_arch) 等 API，在我的场景中获取系统 arch 逻辑需要通过自定义脚本实现。然后需要根据不同的 arch 来配置 cuda 的 -ccbin 参数。

我当前的写法如下：

```lua
-- 通过脚本获取当前系统 arch
option("zelos_arch", function()
    on_check(function(option)
        local architecture = ""
        local uname = string.trim(os.iorun("uname -m"))

        if uname == "i386" or uname == "i686" then
            architecture = "386"
        elseif uname == "x86_64" then
            architecture = "amd64"
        elseif uname == "arm" then
            local dpkg_output = os.iorun("dpkg --print-architecture")
            if string.find(dpkg_output, "arm64") then
                architecture = "arm64"
            else
                architecture = "arm"
            end
        elseif uname == "aarch64" then
            architecture = "aarch64"
        end

        if architecture == "aarch64" then
            local temp_version = string.trim(os.iorun(
                                                 "cat /etc/nv_tegra_release 2>/dev/null|awk '{print $2}'"))
            if temp_version == "R32" then
                architecture = "jetpack4"
            elseif temp_version == "R35" then
                architecture = "jetpack5"
            end
        end

        if architecture == "amd64" then
            local nvcc11 = string.trim(os.iorun(
                                           [[nvcc -V | grep 11.4 || echo ""]]))
            if nvcc11 ~= "" then architecture = "amd64_jetpack5" end
        end

        cprint("${bright green}[configure] uname:${clear} [" .. uname .. "]")
        cprint("${bright green}[configure] architecture:${clear} [" ..
                   architecture .. "]")

        if architecture == "" or architecture == "386" then
            raise("unsupported architecture: [" .. architecture .."]")
        end

        option:set_value(architecture)
    end)
end)
```

根据系统 arch 来选择不同的 cuda 参数：

```lua
local architecture = get_config("zelos_arch")
if architecture == "jetpack4" then
    add_cflags("-D_JETPACK4=1")
    add_cuflags("copts=-D_JETPACK4=1", {force = true})
elseif architecture == "jetpack5" then
    set_config("cu-ccbin", "gcc")
    add_cugencodes("compute_80", "compute_80,sm_80,sm_86,sm_87")
elseif architecture == "amd64_jetpack5" then
    set_config("cu-ccbin", "gcc")
    add_cugencodes("compute_80", "compute_80,sm_80,sm_86,sm_87")
end
```

但是现状这种写法没法生效，原因可能是在配置 config 的时候还没有执行 option 对应的脚本，所以 local architecture = get_config("zelos_arch") 返回值可能是 nil。

### 描述可能的解决方案

希望可以提供用户自定义脚本来配置 config。

**Comment by TOMO-CAT** [comment]
如果是直接写函数的话，无法调用模块函数比如 os.iorun 等
![b450c565e4bb71d4abbaaa4404ad8f12](https://github.com/xmake-io/xmake/assets/47598093/7c662474-337e-4062-9c3f-178058ca8ae0)

**Comment by waruqi** [comment]
描述域不要处理复杂脚本，都到脚本域配置。。

```lua
target("test")
    on_config(function (target)
        local arch = os.arch()
        if arch == "xxx" then
            target:add("cuflags", "-ccbin=gcc", {force = true})
            target:add("culdflags", "-ccbin=gcc", {force = true})
        end
    end)
```

**Comment by TOMO-CAT** [comment]
> 描述域不要处理复杂脚本，都到脚本域配置。。
> 
> ```lua
> target("test")
>     on_config(function (target)
>         local arch = os.arch()
>         if arch == "xxx" then
>             target:add("cuflags", "-ccbin=gcc", {force = true})
>             target:add("culdflags", "-ccbin=gcc", {force = true})
>         end
>     end)
> ```

问题是我需要调用 set_config 或者其他的描述域全局 api 函数，在 target 里脚本域做不到吧，比如我问题描述中的场景。

**Comment by waruqi** [comment]
除了 set_config/includes 等少数全局api ，其他所有描述域接口，例如 add_defines/add_cflags/add_xxx/set_xxx 。。都可以在脚本域中通过 `target:add()/target:set()` 等价设置

**Comment by TOMO-CAT** [comment]
> 除了 set_config/includes 等少数全局api ，其他所有描述域接口，例如 add_defines/add_cflags/add_xxx/set_xxx 。。都可以在脚本域中通过 `target:add()/target:set()` 等价设置
> 
> > 比如我问题描述中的场景
> 
> 我不都给你贴实现代码了么。。

这个我试过了，在 devlink 的时候会有两个 -ccbin，而且后面那个依然是 -ccbin=clang++，最好还是直接替换掉原始的 -ccbin

**Comment by waruqi** [comment]
试下这个 patch，然后用  `target:set("toolset", "cu-ccbin", "xxx")` 改。

https://github.com/xmake-io/xmake/pull/4757

```
xmake update -s github:xmake-io/xmake#ccbin
```

**Comment by TOMO-CAT** [comment]
> 试下这个 patch，然后用 `target:set("toolset", "cu-ccbin", "xxx")` 改。
> 
> #4757
> 
> ```
> xmake update -s github:xmake-io/xmake#ccbin
> ```

cuda 的 ccbin 应该是个全局 project 的配置吧，每个 target 单独设置是不是不太有必要

**Comment by waruqi** [comment]
> cuda 的 ccbin 应该是个全局 project 的配置吧，每个 target 单独设置是不是不太有必要。

不提供，建议走 set_toolset/set_toolchains 等 target 粒度接口，放在全局根域，就是全局配置，放在 target 里面配置，就是 target 粒度配置，也可以做成 rule ，全局根域配置对所有 target 生效。。

ccbin 那个都是历史遗留的配置，所以现有版本只支持全局 set_config 配。。set_config 的这个接口通常是不建议使用的，限制太多。。能尽量用 target 接口，尽量用。。全局还是各种target粒度都能灵活配。。

**Comment by TOMO-CAT** [comment]
> > cuda 的 ccbin 应该是个全局 project 的配置吧，每个 target 单独设置是不是不太有必要。
> 
> 不提供，建议走 set_toolset/set_toolchains 等 target 粒度接口，放在全局根域，就是全局配置，放在 target 里面配置，就是 target 粒度配置，也可以做成 rule ，全局根域配置对所有 target 生效。。
> 
> ccbin 那个都是历史遗留的配置，所以现有版本只支持全局 set_config 配。。set_config 的这个接口通常是不建议使用的，限制太多。。能尽量用 target 接口，尽量用。。全局还是各种target粒度都能灵活配。。
> 
> 昨天那个 patch 已经把 ccbin 也改成 target set_toolset 配置了，尽量用这个，如果测试 ok 我就 merge 。。。其他方式概不考虑

可以的，在全局域 set_toolset("cu-ccbin", "gcc")
