### ISSUE TITLE
分布式构建报错

### ISSUE THREAD

**Issue by rooong** [xmake-io/xmake#4760]
### Xmake 版本

2.8.6

### 操作系统版本和架构

windows 7/windows server 2012

### 描述问题

本地windows 7，分布式服务器windows server 2012，构建工程报错
vs2013

### 期待的结果

正常构建

### 工程配置

client.conf配置：
{
    connect_timeout = 10000,
    distcc_build = {
        hosts = {
			{
                connect = "127.0.0.1:9693",
                token = "aee4d7a8875e4cfb2a421219cfb737bc"
            },
			{
                connect = "10.0.0.57:9693",
                token = "fef62d3bb81d39e08f38fbad770e9076"
            }
        }
    },
    recv_timeout = -1,
    remote_build = {
        connect = "127.0.0.1:9691",
        token = "aee4d7a8875e4cfb2a421219cfb737bc"
    },
    remote_cache = {
        connect = "127.0.0.1:9692",
        token = "aee4d7a8875e4cfb2a421219cfb737bc"
    },
    send_timeout = -1
}

### 附加信息和错误日志

[分布式构建异常log.txt](https://github.com/xmake-io/xmake/files/14373458/log.txt)

**Comment by waruqi** [comment]
服务端也是相同版本么，按理 njob 不应该为 nil，你可以调下下面的位置

https://github.com/xmake-io/xmake/blob/67412d490d1e88a17b4e873de75ae19c284cb7bc/xmake/modules/private/service/distcc_build/client.lua#L557

https://github.com/xmake-io/xmake/blob/67412d490d1e88a17b4e873de75ae19c284cb7bc/xmake/modules/private/service/distcc_build/client.lua#L178

**Comment by rooong** [comment]
> 服务端也是相同版本么，按理 njob 不应该为 nil，你可以调下下面的位置
> 
> https://github.com/xmake-io/xmake/blob/67412d490d1e88a17b4e873de75ae19c284cb7bc/xmake/modules/private/service/distcc_build/client.lua#L557
> 
> https://github.com/xmake-io/xmake/blob/67412d490d1e88a17b4e873de75ae19c284cb7bc/xmake/modules/private/service/distcc_build/client.lua#L178

版本一样的，同个安装包。
出现一次后，后面再试没再报错。但是连接上后，有时候分布式服务器有在一起编译构建，有时候没有。。。这个不知道什么情况（这期间分布式连接有开关操作）

**Comment by waruqi** [comment]
> > 服务端也是相同版本么，按理 njob 不应该为 nil，你可以调下下面的位置
> > https://github.com/xmake-io/xmake/blob/67412d490d1e88a17b4e873de75ae19c284cb7bc/xmake/modules/private/service/distcc_build/client.lua#L557
> > 
> > https://github.com/xmake-io/xmake/blob/67412d490d1e88a17b4e873de75ae19c284cb7bc/xmake/modules/private/service/distcc_build/client.lua#L178
> 
> 版本一样的，同个安装包。 出现一次后，后面再试没再报错。但是连接上后，有时候分布式服务器有在一起编译构建，有时候没有。。。这个不知道什么情况（这期间分布式连接有开关操作）

除非有必现的问题，并且提供复现步骤和完整 logs ，不然我也没法看，你可以自己翻源码 调下。

**Comment by rooong** [comment]
![分布式构建异常log2](https://github.com/xmake-io/xmake/assets/38597332/ec72fba5-cf9b-41f5-8f47-966a16075437)
![分布式构建异常log2](https://github.com/xmake-io/xmake/assets/38597332/256a8c97-d3e4-4854-8325-264be97ed3fd)
连接时，有njob值，后面host.njob访问的时候，有一台机器没值

**Comment by waruqi** [comment]
连接完有值，应该会序列化存到本地，加载时候应该也有值才对。。

https://github.com/xmake-io/xmake/blob/ff4b2b09ea46e80c110ac327c4909032669d809e/xmake/modules/private/service/distcc_build/client.lua#L366

https://github.com/xmake-io/xmake/blob/ff4b2b09ea46e80c110ac327c4909032669d809e/xmake/modules/private/service/distcc_build/client.lua#L578

你可以继续调下。然后提个 pr 过来

**Comment by rooong** [comment]
看了工程目录下.xmake/.../status.txt内容，将原有的远程服务器信息删了，重新连接，就可以了
PS：忘了保存原有的服务器信息了，不确定有什么区别

另外，可以复现的一个问题是，在分布式编译过程中，打断编译，然后关闭连接再分布式编译，很容易出现连不上远程服务问题，且远程服务器上分布式编译进程还在，且占用一定的CPU

**Comment by waruqi** [comment]
> PS：忘了保存原有的服务器信息了，不确定有什么区别

等下次复现的时候，贴下 这个文件内容

**Comment by waruqi** [comment]
应该可以了，`xmake update -s dev`
