### ISSUE TITLE
xmake更新之后原有工程编译不了

### ISSUE THREAD

**Issue by Dozingfiretruck** [xmake-io/xmake#4769]
### Xmake 版本

2.8.7

### 操作系统版本和架构

win10

### 描述问题

貌似把warning当做错误了，只要出现这个warning，后面不管编译什么都当做错误停止
![bb9cc9a4029d7620dbcb2b4c985678ae](https://github.com/xmake-io/xmake/assets/24759100/d3db097f-f621-40a0-9011-8d0935f5f6f5)

### 期待的结果

正常编译

### 工程配置

仓库地址 ： https://gitee.com/openLuat/luatos-soc-air101

### 附加信息和错误日志

error: gcc: warning: '-mcpu=' is deprecated; use '-mtune=' or '-march=' instead
..\LuatOS\components\luatfonts\luat_lib_fonts.c:1:0: error: bad value (ck804ef) for -mtune= switch
 /*
 ^

**Comment by waruqi** [comment]
xmake 不会处理 warning 只会判断 gcc 的 exit code ，非 0 就退出。

即使有错，也是 Gcc 报错导致，可以对比前后 flags 的差异

**Comment by Dozingfiretruck** [comment]
> xmake 不会处理 warning 只会判断 gcc 的 exit code ，非 0 就退出。
> 
> 即使有错，也是 Gcc 报错导致，可以对比前后 flags 的差异

没有差异，工程不变，只更新xmake，2.8.6一切正常

**Comment by waruqi** [comment]
再试下。。`xmake update -s dev; xmake f -c`

**Comment by Dozingfiretruck** [comment]
> 再试下。。`xmake update -s dev; xmake f -c`

可以了，这个影响应该比较大，下个版本是不是会提前发布

**Comment by waruqi** [comment]
看情况。

**Comment by waruqi** [comment]
更新了。
