### ISSUE TITLE
启用soname时程序无法正确加载动态库

### ISSUE THREAD

**Issue by xu-h** [xmake-io/xmake#4776]
### Xmake 版本

v2.8.7+HEAD.da27927

### 操作系统版本和架构

Ubuntu 22.04, Windows 11 WSL2

### 描述问题

测试用例 [shared_library_with_soname](https://github.com/xmake-io/xmake/tree/76af94c04ba55dfe7a5087ce76dfeba4a709ba46/tests/projects/c%2B%2B/shared_library_with_soname) 编译正常

执行时提示 `error while loading shared libraries: @rpath/libfoo.so.1: cannot open shared object file: No such file or directory`

在 `linker.soname` 中 `target:add("shflags", "-Wl,-soname,@rpath/" .. soname, {force = true})` 是否应删除 `@rpath`前缀？

### 期待的结果

程序能够正常执行。

### 工程配置

[shared_library_with_soname](https://github.com/xmake-io/xmake/tree/76af94c04ba55dfe7a5087ce76dfeba4a709ba46/tests/projects/c%2B%2B/shared_library_with_soname)

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
再试试，`xmake update -s dev`
