### ISSUE TITLE
{force = true}未生效

### ISSUE THREAD

**Issue by Dozingfiretruck** [xmake-io/xmake#4777]
### Xmake 版本

2.8.7

### 操作系统版本和架构

win10

### 描述问题

![image](https://github.com/xmake-io/xmake/assets/24759100/3e54c5dc-40a7-49c3-8040-0298457d2027)
![image](https://github.com/xmake-io/xmake/assets/24759100/29148454-fa1f-47f8-8e01-e4be46c2c75b)

### 期待的结果

正常识别

### 工程配置

![image](https://github.com/xmake-io/xmake/assets/24759100/fb261574-1c8f-4137-9f5b-47874b6058a6)

### 附加信息和错误日志

![image](https://github.com/xmake-io/xmake/assets/24759100/e5ef07dd-d84a-4624-a401-29f9a918b7fe)

**Comment by waruqi** [comment]
如果 force 失效，应该所有的 add_ldflags force 都失效，而不是就这个一个。。另外我这一直 ok 没法复现这个问题。。

你可以看下，是不是有其他地方单独加了这个 flags 没设置 force 。。

或者提供一个可复现的 example

**Comment by Dozingfiretruck** [comment]
> 如果 force 失效，应该所有的 add_ldflags force 都失效，而不是就这个一个。。另外我这一直 ok 没法复现这个问题。。
> 
> 你可以看下，是不是有其他地方单独加了这个 flags 没设置 force 。。
> 
> 或者提供一个可复现的 example

我很确定都添加了force，
![image](https://github.com/xmake-io/xmake/assets/24759100/a5482e67-d998-41af-8873-fbb70ba1b4d6)
![image](https://github.com/xmake-io/xmake/assets/24759100/59ba54f3-d4b7-4c0c-a5ef-6268c0c9c6f1)
![image](https://github.com/xmake-io/xmake/assets/24759100/2a4b3b67-16be-4238-80c6-7eb7bb2764d7)
工程仓库：https://gitee.com/openLuat/luatos-soc-2023

**Comment by waruqi** [comment]
再试试，应该可以了，`xmake update -s dev`
