### ISSUE TITLE
Windows Applications aren't configured correctly using set_kind("binary")

### ISSUE THREAD

**Issue by Lyuu17** [xmake-io/xmake#4785]
### Xmake Version

2.8.7

### Operating System Version and Architecture

Windows 11

### Describe Bug

set_kind doesn't have any configuration property like [CMake does](https://cmake.org/cmake/help/latest/prop_tgt/WIN32_EXECUTABLE.html#prop_tgt:WIN32_EXECUTABLE) so attempting to run the .exe, it just doesn't work.

### Expected Behavior

A fully working Windows application

### Project Configuration

```lua
target("ServerBrowserApplicationWX")
    set_kind("binary")
    add_files(sources)
    add_deps("LauncherLibrary", "CoreLibrary")
    add_packages("tinyxml2", "fmt", "eventpp", "libcurl", "wxwidgets", "nlohmann_json")
    add_includedirs("include")
    set_pcxxheader("src/pch.hpp")
    add_defines("_UNICODE")
```

### Additional Information and Error Logs

Trying to run it with xmake run gives:

![image](https://github.com/xmake-io/xmake/assets/14199521/cd919e2f-9838-4b84-9cd5-2dcf66d39fdd)

**Comment by Lyuu17** [comment]
I researched a bit, it would be this [/SUBSYSTEM linker flag](https://learn.microsoft.com/en-us/cpp/build/reference/subsystem-specify-subsystem?view=msvc-170) and "Console" is the current one used by "binary".

**Comment by SirLynix** [comment]
This is not a bug, xmake doesn't set the /subsystem flag, /subsystem:console is just the default value from cl.exe.

You can use `add_ldflags("/subsystem:windows")` in this case

**Comment by Lyuu17** [comment]
> You can use `add_ldflags("/subsystem:windows")` in this case

Still builds like a console instead of windows, and vscode seems to not recognize it either

![image](https://github.com/xmake-io/xmake/assets/14199521/1560e55c-411e-4a21-99de-51b56e7d9e87)

**Comment by star-hengxing** [comment]
```lua
add_ldflags("/subsystem:windows", {force = true})
```

**Comment by waruqi** [comment]
`binary` kind will not add any flags. if you want to build windows app. you should use `"win.sdk.application"` rule, it will set binary kind and windows subsystem.

https://xmake.io/#/guide/project_examples?id=winsdk-application-program

https://github.com/xmake-io/xmake/blob/9b8384ff002380fce4ba8ca4cd3f6e0e354fb9dc/tests/projects/windows/winsdk/windemo/xmake.lua#L4

**Comment by Lyuu17** [comment]
> ```lua
> add_ldflags("/subsystem:windows", {force = true})
> ```

Still compiles as "console"

> `binary` kind will not add any flags. if you want to build windows app. you should use `"win.sdk.application"` rule, it will set binary kind and windows subsystem.
> 
> https://xmake.io/#/guide/project_examples?id=winsdk-application-program
> 
> https://github.com/xmake-io/xmake/blob/9b8384ff002380fce4ba8ca4cd3f6e0e354fb9dc/tests/projects/windows/winsdk/windemo/xmake.lua#L4

Thanks, docs are a bit confusing, but still, same as ldflags, compiles as console (I think so, I'm comparing with Visual Studio generating the cmakelists and then .sln)

```
[ 92%]: linking.release ServerBrowserApplicationWX.exe
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x86\\link.exe" -nologo -dynamicbase -nxcompat -machine:x86 -libpath:C:\Users\lucx\AppData\Local\.xmake\packages\l\libcurl\8.5.0\9298462f501e4bdfb979fcd6fbb97d01\lib -libpath:C:\Users\lucx\AppData\Local\.xmake\packages\w\wxwidgets\master\af705bc0e66f4f108a3a47c7ee859189\lib -libpath:build\windows\x86\release -libpath:C:\Users\lucx\AppData\Local\.xmake\packages\t\tinyxml2\10.0.0\f114b247ea1e417493c76700ae5c1c5f\lib -libpath:C:\Users\lucx\AppData\Local\.xmake\packages\f\fmt\10.2.1\0897ead68a554e21b2546cd5fd4492a6\lib /opt:ref /opt:icf libcurl.lib wxbase33u.lib wxbase33u_net.lib wxbase33u_xml.lib wxexpat.lib wxjpeg.lib wxlexilla.lib wxmsw33u_adv.lib wxmsw33u_aui.lib wxmsw33u_core.lib wxmsw33u_gl.lib wxmsw33u_html.lib wxmsw33u_media.lib wxmsw33u_propgrid.lib wxmsw33u_qa.lib wxmsw33u_ribbon.lib wxmsw33u_richtext.lib wxmsw33u_stc.lib wxmsw33u_webview.lib wxmsw33u_xrc.lib wxpng.lib wxregexu.lib wxscintilla.lib wxtiff.lib wxzlib.lib LauncherLibrary.lib CoreLibrary.lib tinyxml2.lib fmt.lib kernel32.lib gdi32.lib winspool.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib comctl32.lib comdlg32.lib setupapi.lib shlwapi.lib strsafe.lib crypt32.lib wldap32.lib winmm.lib ws2_32.lib user32.lib advapi32.lib ole32.lib shell32.lib -subsystem:windows /manifestinput:applications\ServerBrowserApplicationWX\ServerBrowserApplicationWX.manifest /manifestuac:no /manifest:embed -out:build\windows\x86\release\ServerBrowserApplicationWX.exe build\.objs\ServerBrowserApplicationWX\windows\x86\release\applications\ServerBrowserApplicationWX\src\dialogs\AboutDialog.cpp.obj build\.objs\ServerBrowserApplicationWX\windows\x86\release\applications\ServerBrowserApplicationWX\src\dialogs\AddServerDialog.cpp.obj build\.objs\ServerBrowserApplicationWX\windows\x86\release\applications\ServerBrowserApplicationWX\src\dialogs\SettingsDialog.cpp.obj build\.objs\ServerBrowserApplicationWX\windows\x86\release\applications\ServerBrowserApplicationWX\src\Browser.cpp.obj build\.objs\ServerBrowserApplicationWX\windows\x86\release\applications\ServerBrowserApplicationWX\src\main.cpp.obj build\.objs\ServerBrowserApplicationWX\windows\x86\release\applications\ServerBrowserApplicationWX\src\MyApp.cpp.obj build\.objs\ServerBrowserApplicationWX\windows\x86\release\applications\ServerBrowserApplicationWX\src\MyFrame.cpp.obj build\.objs\ServerBrowserApplicationWX\windows\x86\release\applications\ServerBrowserApplicationWX\ServerBrowserApplicationWX.rc.obj build\.objs\ServerBrowserApplicationWX\windows\x86\release\gens\applications\ServerBrowserApplicationWX\src\cxx\pch.hpp.pch.obj
```

![image](https://github.com/xmake-io/xmake/assets/14199521/f356b77e-fbfe-4e56-ad73-6512783bbb30)

[msbuild build.log](https://github.com/xmake-io/xmake/files/14459835/build.log)

**Comment by SirLynix** [comment]
![image](https://github.com/xmake-io/xmake/assets/3002461/b5c561cb-4e6a-46c9-a1eb-900aaa2ec7b2)
No, it does compile with /subsystem:windows.

Why are you generating a cmakelists then a .sln? You can generate a Visual Studio project using either vs or vsxmake project generator.

**Comment by Lyuu17** [comment]
> No, it does compile with /subsystem:windows.

It compiles, it links, but it doesn't run. Once I changed manually in the project settings generated by xmake (and cmake) to Subsystem: Windows I assumed it's was a linking issue

> Why are you generating a cmakelists then a .sln? You can generate a Visual Studio project using either vs or vsxmake project generator.

My bad, sorry. Generating through vsxmake setups correctly the Subsystem:

![image](https://github.com/xmake-io/xmake/assets/14199521/0036732b-5dba-4e28-916e-5a5369540260)

Trying to run it:

![image](https://github.com/xmake-io/xmake/assets/14199521/e0f7ea4f-cc77-40f0-ae0d-46b24ca1c0d1)

Somehow vsxmake is different than doing xmake > cmake > sln?

**Comment by waruqi** [comment]
If possible, use xmake to build the project directly.

**Comment by Lyuu17** [comment]
> If possible, use xmake to build the project directly.

Visual Studio used xmake in the background

**Comment by waruqi** [comment]
yeah, vsxmake will use it. please use vsxmake or use xmake directly.

**Comment by Lyuu17** [comment]
> yeah, vsxmake will use it. please use vsxmake or use xmake directly.

Ok, but program doesn't work using xmake anyway, and I don't know why. It used to work in the cmake, and if I generate the cmakefiles it does indeed work if Subsystem is changed manually

**Comment by waruqi** [comment]
> Ok, but program doesn't work using xmake anyway

please show me your xmake.lua and all logs.

```console
xmake f -cvD
xmake -rvD
```

**Comment by Lyuu17** [comment]
xmake.lua
![image](https://github.com/xmake-io/xmake/assets/14199521/d0667118-aeb1-4138-aae8-0b02c115b340)

xmake f -cvD
[first.log](https://github.com/xmake-io/xmake/files/14481712/first.log)

xmake -rvD
[second.log](https://github.com/xmake-io/xmake/files/14481713/second.log)

**Comment by waruqi** [comment]
> -subsystem:windows /manifestinput:applications\ServerBrowserApplicationWX\ServerBrowserApplicationWX.manifest /manifestuac:no /manifest:embed -out:build\windows\x86\release\ServerBrowserApplicationWX.exe 

`-subsystem:windows` has been added.

**Comment by Lyuu17** [comment]
> > -subsystem:windows /manifestinput:applications\ServerBrowserApplicationWX\ServerBrowserApplicationWX.manifest /manifestuac:no /manifest:embed -out:build\windows\x86\release\ServerBrowserApplicationWX.exe
> 
> `-subsystem:windows` has been added.

yes, and trying to run it:
![image](https://github.com/xmake-io/xmake/assets/14199521/64b5ad1d-e454-4f9c-988a-3bcf0e304c47)

**Comment by waruqi** [comment]
you can debug it, maybe .dll PATH issues, maybe your code has bug, or ...

**Comment by Lyuu17** [comment]
> you can debug it, maybe .dll PATH issues, maybe your code has bug, or ...

works fine in cmake, no code changed and linking against the wxwidgets lib generated by xmake

**Comment by waruqi** [comment]
Or you can provide a complete reproducible project and I'll take a look at it.

**Comment by Lyuu17** [comment]
Found the issue, adding this flag fixes it.
![image](https://github.com/xmake-io/xmake/assets/14199521/c7924067-425d-4a58-81a7-024b333d98ba)

**Comment by SirLynix** [comment]
This flag is enabled by default (see https://learn.microsoft.com/en-us/cpp/build/reference/incremental-link-incrementally), I doubt it changes anything.

**Comment by waruqi** [comment]
> This flag is enabled by default (see https://learn.microsoft.com/en-us/cpp/build/reference/incremental-link-incrementally), I doubt it changes anything.

maybe  `/opt:ref /opt:icf` disable it? `set_strip(true)` or release mode will add them.


> Most programs can be linked incrementally. However, some changes are too great, and some options are incompatible with incremental linking. LINK performs a full link if any of the following options are specified:

> Link Incrementally isn't selected (/INCREMENTAL:NO)
> /OPT:REF is selected
> /OPT:ICF is selected

**Comment by waruqi** [comment]
> Found the issue, adding this flag fixes it. ![image](https://private-user-images.githubusercontent.com/14199521/312238239-c7924067-425d-4a58-81a7-024b333d98ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMDI4MzMsIm5iZiI6MTcxMDMwMjUzMywicGF0aCI6Ii8xNDE5OTUyMS8zMTIyMzgyMzktYzc5MjQwNjctNDI1ZC00YTU4LTgxYTctMDI0YjMzM2Q5OGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA0MDIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2NTQxODdkOWE3OTk5YmU4MTQ5ZWU1ZWZmMzRmNWQyMGQ1ZGE5MWNhYjhlMDFkZTlkZTAxN2NhYTcxMTNlNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pc0QgDXawuY_g8k24b_1bAIX5GfpW0_CKOXJX04TATs)

you can try debug mode. `xmake f -m debug; xmake ; xmake run`

**Comment by Lyuu17** [comment]
> > Found the issue, adding this flag fixes it. ![image](https://private-user-images.githubusercontent.com/14199521/312238239-c7924067-425d-4a58-81a7-024b333d98ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMDI4MzMsIm5iZiI6MTcxMDMwMjUzMywicGF0aCI6Ii8xNDE5OTUyMS8zMTIyMzgyMzktYzc5MjQwNjctNDI1ZC00YTU4LTgxYTctMDI0YjMzM2Q5OGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA0MDIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2NTQxODdkOWE3OTk5YmU4MTQ5ZWU1ZWZmMzRmNWQyMGQ1ZGE5MWNhYjhlMDFkZTlkZTAxN2NhYTcxMTNlNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pc0QgDXawuY_g8k24b_1bAIX5GfpW0_CKOXJX04TATs)
> 
> you can try debug mode. `xmake f -m debug; xmake ; xmake run`

I'm having some issues building with debug mode, they're building with MT instead of MTd runtime in debug mode

**Comment by Lyuu17** [comment]
> Try `set_runtimes(is_mode("debug") and "MDd" or "MD")`

thanks, it works

now i have made a a clean build and seems like /incremental doesn't fix anything, probably it's a wxwidgets linking issue (i rewrote the script to build as static)
