### ISSUE TITLE
工程多模块构建失败

### ISSUE THREAD

**Issue by rooong** [xmake-io/xmake#4786]
### Xmake 版本

2.8.6

### 操作系统版本和架构

windows 7

### 描述问题

vs2013,工程多模块构建失败，单个模块独立构建是正常的。报错如下：
![image](https://github.com/xmake-io/xmake/assets/38597332/81ac40ba-75e8-4f3e-a8fe-6a46d5e05fa2)
详细log看附件

### 期待的结果

正常构建

### 工程配置

工程多模块构建
在xmake.lua中includes多个模块

### 附加信息和错误日志

[log.txt](https://github.com/xmake-io/xmake/files/14455736/log.txt)

**Comment by waruqi** [comment]
XBLog.dll 你没导出任何符号，所以没有自动生成 XBLog.lib ，not found了。。跟 xmake 没啥关系。。你自己导出下符号

**Comment by rooong** [comment]
首先有导出符号，其次，单独构建模块时：xmake -r XBLog，是可以正常构建的，也有自动生成XBLog.lib

**Comment by rooong** [comment]
单独构建XBLog日志
[log2.txt](https://github.com/xmake-io/xmake/files/14455940/log2.txt)

**Comment by waruqi** [comment]
> 首先有导出符号，其次，单独构建模块时：xmake -r XBLog，是可以正常构建的，也有自动生成XBLog.lib

多模块下，XBLog 也构建成功的，跟是否单独没关系，目前看日志，多模块下，就是没有找到 XBLog.lib 

你可以看下就没有生成，如果生成了 XBLog.dll 但是没生成 XBLog.lib 。。那就是没有导出符号。。

**Comment by rooong** [comment]
> > 首先有导出符号，其次，单独构建模块时：xmake -r XBLog，是可以正常构建的，也有自动生成XBLog.lib
> 
> 多模块下，XBLog 也构建成功的，跟是否单独没关系，目前看日志，多模块下，就是没有找到 XBLog.lib
> 
> 你可以看下就没有生成，如果生成了 XBLog.dll 但是没生成 XBLog.lib 。。那就是没有导出符号。。

多模块下，XBLog.lib有生成，XBLog.dll也有文件，但未成功，PS：XBLog.dll不是成功编译好的文件大小

**Comment by waruqi** [comment]
贴下 xmake.lua 或者给下完整可复现的 example

**Comment by rooong** [comment]
找到问题了，是另外一个模块xb_breakpad依赖XBLog，需要引用，脚本中没写依赖，导致编译失败。
但是目前给的log，很难明了的知道问题点啊。而且遇到了这种问题，.xmake需要删掉重新编译，不然链接时会报另外一个错误：
linker.lua:33: cannot get program for ar
也非常不友好，搞不明白实际的问题点

**Comment by rooong** [comment]
希望报错可以更精准些，哪个模块出的问题，可以清晰描述出来，这样更容易找问题

**Comment by waruqi** [comment]
其实我已经猜到是这个问题，所以刚问你要 xmake.lua 只是想确认下。。用户没有添加依赖关系，xmake 也不可能猜出来他们之间需要有依赖（xmake 是无法预判用户需求的），给出准确的依赖错误。。这种只能自己根据 xmake.lua 和链接器报错，自己分析。。
