### ISSUE TITLE
 in mingw cannot find the satic library

### ISSUE THREAD

**Issue by qiu-hao** [xmake-io/xmake#479]
Hello , I used the "add_links()" to add the static library and used the "add_linkdirs() to add the static library dir, 
`
    add_links("libnanogui")
    add_linkdirs("lib")
`
but when I xmake build , terminal show that: 

error: C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -llibnanogui collect2.exe: error: ld returned 1 exit status

I had put  libnanogui.a in the lib dir, but it cannot find the static library.

**Comment by OpportunityLiu** [comment]
```
add_links("nanogui")
```

no `lib`,no`.a`

**Comment by qiu-hao** [comment]
Yes , no `lib` no `.a`,  the `lib` is the static library path

**Comment by waruqi** [comment]
> Hello , I used the "add_links()" to add the static library and used the "add_linkdirs() to add the static library dir,

>add_links("libnanogui") 

Are you sure? no lib? `add_links("libnanogui")` ? `add_links("nanogui")`?

**Comment by qiu-hao** [comment]
@waruqi  Yes,  I use the cmake build the NanoGUI static library with mingw in window 10. and I get the libnanogui.a. My path is 
`-.xmake
-build
-include
-lib
    -libnanogui.a
-src
    -main.cpp
-.gitignore
-xmake.lua
`
and use `add_links("libnanogui")  add_linkdirs("lib") `,
but when I xmake build , terminal show that:

error: C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -llibnanogui collect2.exe: error: ld returned 1 exit status.

But I used the dynamic library, it work well.

**Comment by waruqi** [comment]
> and use add_links("libnanogui") add_linkdirs("lib") ,
> but when I xmake build , terminal show that:

@qiu-hao   Please use  `add_links("nanogui")`, not `add_links("libnanogui")`   

NOTE: **no lib** prefix

**Comment by qiu-hao** [comment]
@waruqi Thanks , it work well
