### ISSUE TITLE
optimize wasi detect

### ISSUE THREAD

**Issue by vkensou** [xmake-io/xmake#4798]
### Is your feature request related to a problem? Please describe.

现在只有一种办法检测wasi-sdk。即调用命令`xmake f -p wasm -a wasm32 --toolchain=wasi --sdk=C:\\xxx`。如果一个项目中有多个target使用不同的platform和toolchain就没办法设置了（可能是我不会）。

### Describe the solution you'd like

希望可以通过环境变量 WASI_SDK_PATH 或者xmake全局设置来告诉xmake wasi-sdk在哪。

**Comment by waruqi** [comment]
> 有多个target使用不同的platform和toolchain就没办法设置了

使用 set_toolchain/set_plat 单独对特定 target 设置就行了，并不影响

**Comment by waruqi** [comment]
> 每个人的wasi-sdk的路径都不一样。这样别人就不能方便的构建了。
我这个pr参考对emsdk的处理，实现了三种方法设置：

走 set_toolchain ，你还是可以传递 `--sdk` ，不同用户不同的设置。。另外也可以自定义 toolchain 去 改 set_sdkdir + option

另外，也可以 `set_toolchain("wasi", {sdkdir = get_config("mysdk")})` + custom option 去传 sdk ，绑定不同的 target

> xmake全局配置xmake g --wasi_sdk=C:\\xxx

额外加 wasi_sdk，只会导致 config options 越来越多，不受敛，同样也没法对不同 target 处理

**Comment by waruqi** [comment]
另外，更推荐的做法是把 wasi sdk 提交到 xmake-repo ，作为包，然后走 add_requires/set_toolchains 直接远程拉取，自动集成，连 --sdk 都不需要指定，目前 emsdk 就已经支持。。。

只需要 xmake 一键编译，还能支持 wasi sdk 的版本选择

**Comment by vkensou** [comment]
那我把config里的删掉好了，有环境变量也足够了。自己在项目里加config、toolchain啥的比较麻烦，每个项目都得做一遍，不太方便，还是xmake能自动检测最好了。
package的话我再后面研究一下~

**Comment by waruqi** [comment]
> 还是xmake能自动检测最好了。

自动检测也可以在包里做，不需要放到 xmake 里面

**Comment by waruqi** [comment]
参考 https://github.com/xmake-io/xmake-repo/blob/dev/packages/l/llvm/fetch.lua
https://github.com/xmake-io/xmake-repo/blob/fb41abe4f98dc2f3ef6342d8ef3d998a0da32b8f/packages/l/llvm/xmake.lua#L100

**Comment by vkensou** [comment]
我又重新提交了，log没有中文了
