### ISSUE TITLE
plugin.compile_commands.autoupdate不会携带预编译header信息

### ISSUE THREAD

**Issue by MaxwellGengYF** [xmake-io/xmake#4802]
### Xmake Version

2.8.7

### Operating System Version and Architecture

Any OS

### Describe Bug

项目中使用
add_rules("plugin.compile_commands.autoupdate", { outputdir = ".vscode" })
编译后生成的compile_commands.json不会正确打印预编译header信息。

### Expected Behavior

应在arguments中正确输出 "-Yupch.h", "-FIpch.h"等

### Project Configuration

set_xmakever("2.8.7")
add_rules("plugin.compile_commands.autoupdate", { outputdir = ".vscode" })

### Additional Information and Error Logs

compile_commands.json updated!

**Comment by MaxwellGengYF** [comment]
目前发现vscode插件直接调用compile_commands.lua时行为正常，而独立启动进程行为不正常。

**Comment by MaxwellGengYF** [comment]
Seems like if I use

**Comment by MaxwellGengYF** [comment]
经过逆向，看起来是 XMAKE_GENERATOR_COMPDB_LSP 这个环境变量的问题，模仿vscode插件内写法：
os.setenv("XMAKE_GENERATOR_COMPDB_LSP", "clangd")
config.load()
_config_targets()
compile_commands.make(compileCommandsDirectory or ".vscode")
就会正确输出pch结果

**Comment by waruqi** [comment]
配置下 lsp 到 clangd 就行了，因为目前已知的，就 clangd 支持 pch，其他的暂时没测试验证过，所以暂时禁用了 pch

```lua
add_rules("plugin.compile_commands.autoupdate", { lsp = "clangd", outputdir = ".vscode" })
```
