### ISSUE TITLE
添加 target:gb2312 以满足中文兼容性

### ISSUE THREAD

**Issue by ruiyuanlu** [xmake-io/xmake#4813]
### Is your feature request related to a problem? Please describe.

当前的 xmake api 检查 set_encodings 时仅支持 utf-8 对于 gb2312 xmake 做 api 检查时会给出 warning
```cmd
warning: .\xmake.lua:51: unknown encoding value 'target:gb2312', it may be 'target:utf-8'
```
出于跨平台兼容性需要，希望代码本身用 utf-8 存储, 在 Linux 上使用 utf-8, 但是在 win 上需要避免中文乱码,  gb2312 对应 CodePage 936 所以需要增加 target:gb2312 支持

CodePage 和编码名称的对应关系参考的是：https://learn.microsoft.com/zh-cn/windows/win32/Intl/code-page-identifiers

### Describe the solution you'd like

# API 检查
在 [encodings.lua](https://github.com/xmake-io/xmake/blob/master/xmake/modules/private/check/checkers/api/target/encodings.lua#L27) 添加对 target:gb2312 检查

```lua
-- imports
import(".api_checker")

function main(opt)
    opt = opt or {}
    api_checker.check_targets("encodings", table.join(opt, {values = {
        "none", "utf-8", "source:utf-8", "target:utf-8", "target:gb2312"}}))
end
```

# 添加 nf_encodings 处理
在 [cl.lua](https://github.com/xmake-io/xmake/blob/master/xmake/modules/core/tools/cl.lua#L366) 和 [gcc.lua](https://github.com/xmake-io/xmake/blob/master/xmake/modules/core/tools/gcc.lua#L403) 中添加对 gb2312 的处理
```lua
local charsets = {
        ["utf-8"] = "utf-8",
        utf8 = "utf-8",
        gb2312 = "gb2312"
    }
```

### Describe alternatives you've considered

NO

### Additional context

NO

**Comment by waruqi** [comment]
再试试，`xmake update -s dev`

**Comment by ruiyuanlu** [comment]
OK，没什么问题，thx
