### ISSUE TITLE
创建 cmakelist 异常

### ISSUE THREAD

**Issue by zhuizhubf** [xmake-io/xmake#4816]
### Xmake 版本

v2.8.8+HEAD.d8e248255

### 操作系统版本和架构

Window10

### 描述问题

在使用 xmake project -k cmakelists
出现 error: @programdir\core\main.lua:306: @programdir\plugins\project\cmake\cmakelists.lua:200: bad argument #1 to 'is_absolute' (string expected, got table)

调试发现 是 set_policy("windows.manifest.uac", "admin") 导致的 
项目加入 set_policy("windows.manifest.uac", "admin") 后就会导致 flag 是一个 table {
  "/manifestuac:level='requireAdministrator' uiAccess='false'",
  __wrap_locked__ = true
} 导致出现问题

### 期待的结果

正常的构建

### 工程配置

add_rules("mode.debug", "mode.release")
add_rules("plugin.compile_commands.autoupdate")
add_rules("plugin.vsxmake.autoupdate")

set_encodings("source:utf-8", "target:utf-8")

add_defines("_UNICODE", "UNICODE")

set_policy("windows.manifest.uac", "admin")

其他是正常的项目配置

### 附加信息和错误日志

error: @programdir\core\main.lua:306: @programdir\plugins\project\cmake\cmakelists.lua:200: bad argument #1 to 'is_absolute' (string expected, got table)
    [C]: in function 'is_absolute'
    [@programdir\plugins\project\cmake\cmakelists.lua:200]: in function '_translate_flag'
    [@programdir\plugins\project\cmake\cmakelists.lua:930]: in function '_add_target_link_options'
    [@programdir\plugins\project\cmake\cmakelists.lua:1136]: in function '_add_target'
    [@programdir\plugins\project\cmake\cmakelists.lua:1156]: in function '_generate_cmakelists'
    [@programdir\plugins\project\cmake\cmakelists.lua:1170]: in function '?'
    [@programdir\plugins\project\main.lua:75]: in function '_make'
    [@programdir\plugins\project\main.lua:95]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\base\task.lua:491]: in function 'run'
    [@programdir\core\main.lua:304]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:404]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:957: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:306: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>

**Comment by waruqi** [comment]
再试试 `xmake update -s dev`

**Comment by zhuizhubf** [comment]
ok 了
