### ISSUE TITLE
Support range based glob pattern

### ISSUE THREAD

**Issue by A2va** [xmake-io/xmake#4817]
### Is your feature request related to a problem? Please describe.

The glob pattern syntax for xmake suports wildcards with `[xyz]` but not `[x-z]`
For example if a file named `abc6` is present in a directory, this script will output:

```lua
print(os.files("abc[0123456789]") -- print {"abc6"}
print(os.files("abc[0-9]") -- print {}
```

### Describe the solution you'd like

It's possible to get around this by using a full selection of what you want to include, but it's a bit annoying with the alphabet, for example.

**Comment by waruqi** [comment]
The file path matching pattern of os.files cannot support it. `+`, `-` is plain character for file path. you can only use `[0123456789]`

**Comment by A2va** [comment]
I didn't quite understand that: `+`, `-` is just a simple file path character. Because `[` or `]` can also be used in a file path, but they have a special meaning for glob.

**Comment by waruqi** [comment]
This is because [] is almost rarely found in paths, whereas +- is often found in paths. We need to simplify path pattern matching in most cases as much as possible to avoid the problems most users have caused by adding +- paths. For example add_files("foo-xx.c")

**Comment by A2va** [comment]
If so, wouldn't it be possible to treat `-` as a special character once it is inside `[]`?

**Comment by waruqi** [comment]
> If so, wouldn't it be possible to treat as a special character once it is inside ?`-``[]`

To simplify the path pattern of add_files, it is not a standard lua pattern; it mainly supports `*`, `**` and some lua patterns, but `+/-` cannot be used as a special character. we can use `*` instead of `+/-`
