### ISSUE TITLE
add_requireconfs 固定依赖版本后丢失依赖信息

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#4818]
### Xmake 版本

v2.8.8+master.67dce6e82 最新 master 版本

### 操作系统版本和架构

Linux 720ce3a659a2 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

当前项目需要依赖 A 库（zcore）和 B 库（zproto），其中 A 库也依赖 B 库。这两个库都定义在本地 xmake-repo 中。
其中 A 库在 xmake-repo 中没有指定 B 库的版本：
![image](https://github.com/xmake-io/xmake/assets/47598093/a672a97e-9fd6-4f14-8da9-1877431f4551)
![image](https://github.com/xmake-io/xmake/assets/47598093/5b998a14-229e-4dc9-aa6b-a226460a72e2)

我希望在整个当前项目中**固定 A 和 B 库的版本**，因此使用 add_requiresonfs：
![image](https://github.com/xmake-io/xmake/assets/47598093/c56d0968-4270-4fa2-8d87-52abd637fe33)

xmake f -c 后可以看到符合要求，这里显示 A 库依赖的 B 库版本已经被覆盖了：
![image](https://github.com/xmake-io/xmake/assets/47598093/f7407bc5-94df-44b8-9e79-78e0245807ce)

但是编译的时候 A库 没有引用 B 库的头文件路径和库路径从而报错找不到 B 库的头文件：
![image](https://github.com/xmake-io/xmake/assets/47598093/30095146-9dae-4efe-ba8a-64abba155080)

### 期待的结果

可以覆盖使用指定库的 version。

### 工程配置

无

### 附加信息和错误日志

无。

**Comment by TOMO-CAT** [comment]
和我使用 alias 有关系吗？还是我 add_requireconfs 的写法有问题？

**Comment by TOMO-CAT** [comment]
报错之前的信息可以看到 A 库是能找到 B 库的，但是为啥没带上 -I 和 -L 呢？
![image](https://github.com/xmake-io/xmake/assets/47598093/042005bb-4d70-4d52-a077-68010cb7f06e)

**Comment by TOMO-CAT** [comment]
改成下面这种方式就可以正常带上依赖库头文件和库文件路径了。

```lua
add_requires("src-zproto 8cb73b36098da141b0d264ec326f85ad2d559562")
add_requires("src-zcore babfcb53115d0b7462e9e30cf85efa150c928cbd")

add_requireconfs("**.src-zproto", {override = true, version = "8cb73b36098da141b0d264ec326f85ad2d559562"})
```
一旦加上 alias 就识别不到：

```lua
add_requires("src-zproto 8cb73b36098da141b0d264ec326f85ad2d559562", {alias = "zproto"})
add_requires("src-zcore babfcb53115d0b7462e9e30cf85efa150c928cbd", {alias = "zcore"})

add_requireconfs("**.src-zproto", {override = true, version = "8cb73b36098da141b0d264ec326f85ad2d559562"})
```

那我应该如何在哪里指定 alias 呢？

**Comment by waruqi** [comment]
没法复现问题，我这看可以, 里面的 libpng 也是 xmake port 引入的 add_requires zlib，跟你结构类似，都没啥问题

```lua
add_rules("mode.debug", "mode.release")

add_requires("libpng", {system = false, alias = "png"})
add_requireconfs("libpng.zlib", {system = false, override = true, version = "1.2.12"})

target("test")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("png")
```

```console
[ 50%]: linking.release test
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o build/macosx/x
86_64/release/test build/.objs/test/macosx/x86_64/release/src/main.cpp.o -target x86_64-apple-macos14.0 -isysroo
t /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -L/Users/ru
ki/.xmake/packages/l/libpng/v1.6.43/5a5a5dee9945466a9da0ecd33dacd4ac/lib -L/Users/ruki/.xmake/packages/z/zlib/v1
.2.12/fabe348668de46d3b23dd12453978e3e/lib -Wl,-x -Wl,-dead_strip -lpng -lz
```

**Comment by TOMO-CAT** [comment]
> 没法复现问题，我这看可以, 里面的 libpng 也是 xmake port 引入的 add_requires zlib，跟你结构类似，都没啥问题
> 
> ```lua
> add_rules("mode.debug", "mode.release")
> 
> add_requires("libpng", {system = false, alias = "png"})
> add_requireconfs("libpng.zlib", {system = false, override = true, version = "1.2.12"})
> 
> target("test")
>     set_kind("binary")
>     add_files("src/*.cpp")
>     add_packages("png")
> ```
> 
> ```
> [ 50%]: linking.release test
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o build/macosx/x
> 86_64/release/test build/.objs/test/macosx/x86_64/release/src/main.cpp.o -target x86_64-apple-macos14.0 -isysroo
> t /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -L/Users/ru
> ki/.xmake/packages/l/libpng/v1.6.43/5a5a5dee9945466a9da0ecd33dacd4ac/lib -L/Users/ruki/.xmake/packages/z/zlib/v1
> .2.12/fabe348668de46d3b23dd12453978e3e/lib -Wl,-x -Wl,-dead_strip -lpng -lz
> ```

没法复现是因为你这里设置的 alias 是 libpng 的（libpng -> png），我设置的是 zlib （例如 zlib -> my-zlib），然后在 libpng 的 xmake.lua 脚本中写：

```lua
target("libpng ")
    set_kind("binary")
    ...
    add_packages("my-zlib")  -- 找不到依赖
   add_packages("zlib") -- 正常
```

btw，当前 xmake 添加不存在的 add_packages 好像不会报错，希望可以类似 add_files 不存在的时候在底部加一个黄色的 warning。

**Comment by waruqi** [comment]
> 没法复现是因为你这里设置的 alias 是 libpng 的（libpng -> png），我设置的是 zlib （例如 zlib -> my-zlib），然后在 libpng 的 xmake.lua 脚本中写：

zlib 不是用户层配置的顶层包，只是内部子依赖，不支持设置 alias 

如果你用户层面额外配置了 add_requires("zlib") ，它跟 libpng.zlib 是完全独立的，即使你改了 alias ，也跟 libpng.zlib 没任何关系。。你通过 add_requireconfs("libpng.*") 还是只能改 libpng 里面依赖的那个 zlib，不会影响到用户端自己配置的 add_requires zlib ..

所以，已经 add_requires("libpng") 了，而且 libpng 依赖了 zlib， 那外面没必要再去 add_requires zlib，加了，反而会导致两个 zlib link 冲突。。你这情况也类似。。

> btw，当前 xmake 添加不存在的 add_packages 好像不会报错，希望可以类似 add_files 不存在的时候在底部加一个黄色的 warning。

就是这么设计的，这是特性，不会加警告，用于简化配置，尤其是针对条件控制包启用的情况。。

```lua
if has_config("foo") then
   add_requires("foo")
end
if has_config("bar") then
   add_requires("bar")
end
if has_config("zoo") then
   add_requires("zoo")
end
target("test")
    add_packages("foo", "bar", "zoo")
```

原本只需要这样，仅仅条件控制 add_requires ，对包的是否引入进行控制。。如果 add_packages 还得检测。。

那只能变成。。


```lua
if has_config("foo") then
   add_requires("foo")
end
if has_config("bar") then
   add_requires("bar")
end
if has_config("zoo") then
   add_requires("zoo")
end
target("test")
    if has_package("foo") then
        add_packages("foo")
    end
    if has_package("bar") then
        add_packages("bar")
    end
    if has_package("zoo") then
        add_packages("zoo")
    end
```

不觉得繁琐么。。

**Comment by TOMO-CAT** [comment]
> > 没法复现是因为你这里设置的 alias 是 libpng 的（libpng -> png），我设置的是 zlib （例如 zlib -> my-zlib），然后在 libpng 的 xmake.lua 脚本中写：
> 
> zlib 不是用户层配置的顶层包，只是内部子依赖，不支持设置 alias
> 
> 如果你用户层面额外配置了 add_requires("zlib") ，它跟 libpng.zlib 是完全独立的，即使你改了 alias ，也跟 libpng.zlib 没任何关系。。你通过 add_requireconfs("libpng.*") 还是只能改 libpng 里面依赖的那个 zlib，不会影响到用户端自己配置的 add_requires zlib ..
> 
> 所以，已经 add_requires("libpng") 了，而且 libpng 依赖了 zlib， 那外面没必要再去 add_requires zlib，加了，反而会导致两个 zlib link 冲突。。你这情况也类似。。
> 
> > btw，当前 xmake 添加不存在的 add_packages 好像不会报错，希望可以类似 add_files 不存在的时候在底部加一个黄色的 warning。
> 
> 就是这么设计的，这是特性，不会加警告，用于简化配置，尤其是针对条件控制包启用的情况。。
> 
> ```lua
> if has_config("foo") then
>    add_requires("foo")
> end
> if has_config("bar") then
>    add_requires("bar")
> end
> if has_config("zoo") then
>    add_requires("zoo")
> end
> target("test")
>     add_packages("foo", "bar", "zoo")
> ```
> 
> 原本只需要这样，仅仅条件控制 add_requires ，对包的是否引入进行控制。。如果 add_packages 还得检测。。
> 
> 那只能变成。。
> 
> ```lua
> if has_config("foo") then
>    add_requires("foo")
> end
> if has_config("bar") then
>    add_requires("bar")
> end
> if has_config("zoo") then
>    add_requires("zoo")
> end
> target("test")
>     if has_package("foo") then
>         add_packages("foo")
>     end
>     if has_package("bar") then
>         add_packages("bar")
>     end
>     if has_package("zoo") then
>         add_packages("zoo")
>     end
> ```
> 
> 不觉得繁琐么。。

主要还是遇到好几次 add_packages 不存在的 bug 了不好排查，条件控制 add_requires 还没用过

**Comment by waruqi** [comment]
> 主要还是遇到好几次 add_packages 不存在的 bug 了不好排查，条件控制 add_requires 还没用过

不存在，xmake -rv 看下就知道了。。相比起这种，我更倾向于对配置的简化。。否则配置复杂化，一样不好调试，看都看不懂。。

**Comment by waruqi** [comment]
> 另外可以通过检测判断理论上应该引用的包但是实际没引入才报 warning 的吧。

怎么判断？不同平台是否应该引入哪些包，都在 if + add_requires + options 里面，xmake 怎么提前知道？都是事后 用户 xmake f --enable_xxx =y 了，才知道，而且即使知道又能怎样， target 的 add_packages 里，还是得 if + add_packages 去处理

**Comment by TOMO-CAT** [comment]
> zlib 不是用户层配置的顶层包，只是内部子依赖，不支持设置 alias

内部子依赖却可以覆盖修改 config 和 version，但是不支持设置 alias，是这样吗

**Comment by waruqi** [comment]
> > zlib 不是用户层配置的顶层包，只是内部子依赖，不支持设置 alias
> 
> 内部子依赖却可以覆盖修改 config 和 version，但是不支持设置 alias，是这样吗

alias 只能给 top 的 add_requires。用于用户端 add_packages 时候用的，简化一些名字，跟子依赖没任何关系
