### ISSUE TITLE
flex应该能正常单独使用

### ISSUE THREAD

**Issue by onnathe** [xmake-io/xmake#4820]
### Xmake 版本

2.8.8

### 操作系统版本和架构

Windows 10 Version 22H2

### 描述问题

xmake内置的规则`lex`下添加了`add_deps("yacc", {order = true})`语句。这使得当单独使用lex时会产生一个警告：
> warning: @programdir/rules/lex_yacc/yacc/xmake.lua:27: includedir 'build/.gens/test-no-yacc/linux/x86_64/release/rules/yacc_yacc' not found

### 期待的结果

希望能消除这个警告。

### 工程配置

```lua
-- xmake.lua
target("no-yacc")
    set_kind("binary")
    add_rules("lex")
    add_files("src/test.l", "src/*.c")
```
```c
// src/main.c
#include <stdio.h>

int yylex(void);

int main(int argc, char *argv[])
{
    yylex();
    return 0;
}
```
```lex
%{
// src/test.l
#if defined _MSC_BUILD
#include <io.h>
#endif
#include <stdio.h>
%}

%option noyywrap
%option nounistd

%%
[0-9]*      { printf("NUMBER "); }
[a-zA-Z]*   { printf("CHAR "); }
.           { printf("OTHER "); }
%%
```

### 附加信息和错误日志

![image](https://github.com/xmake-io/xmake/assets/128711997/b4fa7d56-e63e-4702-b6ed-1994c5bf1255)

**Comment by waruqi** [comment]
再试试 `xmake update -s dev`
