### ISSUE TITLE
ubuntu下调用xmake f --menu报错error: field 'isdone' is not callable (a nil value)

### ISSUE THREAD

**Issue by liangzc1** [xmake-io/xmake#4827]
### Xmake 版本

2.8.8+20240302

### 操作系统版本和架构

Linux ubuntu 5.4.0-150-generic #167~18.04.1-Ubuntu SMP Wed May 24 00:51:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

ubuntu下调用xmake f --menu报错error: field 'isdone' is not callable (a nil value)

使用新建的空xmake工程和使用已经在xmake.lua中设置了option的都会报错

### 期待的结果

ubuntu下调用xmake f --menu能正常

### 工程配置

用xmake create -l c -P ./hello新建的项目

### 附加信息和错误日志

liang@ubuntu:~/WORK/xmake_test/hhh$ xmake f --menu -vD
error: @programdir/core/main.lua:306: @programdir/core/ui/application.lua:120: field 'isdone' is not callable (a nil value)
stack traceback:
    [@programdir/core/ui/application.lua:120]: in function 'run'
    [@programdir/actions/config/menuconf.lua:405]:
    [@programdir/actions/config/main.lua:253]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/core/base/task.lua:491]: in function 'run'
    [@programdir/core/main.lua:304]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:404]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:957: in function 'os.raiselevel'
	(...tail calls...)
	@programdir/core/main.lua:306: in upvalue 'cotask'
	@programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>

**Comment by waruqi** [comment]
建议走官网一键脚本安装。。https://xmake.io/#/guide/installation

ppa 包目前没加 ncurses 依赖，你系统如果没装，编译的 xmake 是不带 ncurses 的。。

**Comment by liangzc1** [comment]
走的ubuntu的安装命令
sudo add-apt-repository ppa:xmake-io/xmake
sudo apt update
sudo apt install xmake
现在也跑了apt install libncurses5-dev装了ncurses的依赖，报错还是一样的，还有额外的依赖吗，有没有列表或者安装脚本

**Comment by waruqi** [comment]
刚不是说了么，不要走 ppa 安装，走官网的一键安装脚本，链接都发你了。。仔细看下么。。

**Comment by liangzc1** [comment]
走xmake-x.x.x.gz.run自安装包的方式可以了，感谢大佬
