### ISSUE TITLE
package:add_linkdirs() 未导出

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#4835]
### Xmake 版本

xmake v2.8.5

### 操作系统版本和架构

Linux 720ce3a659a2 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

package add_links 添加了一些依赖，这些 links 需要导出 linkdirs。

看样子使用到这个 package 的 target 没自动 -L 对应路径。

![image](https://github.com/xmake-io/xmake/assets/47598093/fd20509a-e68a-41aa-b5d3-4da7bcd8314a)

引用这个 package：
![image](https://github.com/xmake-io/xmake/assets/47598093/44e40d2e-e656-4cb4-b511-a16b53e2aa9f)

编译 target 时找不到链接库：
![image](https://github.com/xmake-io/xmake/assets/47598093/b4389d1b-301a-456c-aefa-eb073b2dc170)

### 期待的结果

可以导出 package 的 linkdirs ，现在需要在每个用到的 target 里 add_linkdirs，比较麻烦

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
用法不对，package 的 add_linkdirs 仅用于导出 package 安装目录下的 库路径，使用的是相对路径，对应安装的库文件。。`add_linkdirs("lib")`, `add_linkdirs("lib/xxx")`

不要设置系统路径。

**Comment by TOMO-CAT** [comment]
> 用法不对，package 的 add_linkdirs 仅用于导出 package 安装目录下的 库路径，使用的是相对路径，对应安装的库文件。。`add_linkdirs("lib")`, `add_linkdirs("lib/xxx")`
> 
> 不要设置系统路径。

这样会导致虽然是这个库的 linkdir，所有用到它的都要加，对于一些公司内的项目显得很麻烦，bazel 是可以做到导出的。

**Comment by waruqi** [comment]
不支持，add_linkdirs 仅用于自身 package 的内部 lib 路径的导出，不用于系统路径。。

如果这个包走的是安装库，add_linkdirs 总是指向安装路径。。。如果这个包走的是 fetch 系统库，原本就会通过 pkg-config 返回系统路径，或者 on_fetch 里面自己返回系统路径。。

如果所有包依赖一些系统库和系统路径，你可以单独搞个 systemlib 包，走 on_fetch 去返回系统路径，让这些包全部 add_deps 依赖上。而不是每个包里面去 add_linkdirs 一遍这么多系统路径。。这不也很冗余繁琐么。。

**Comment by TOMO-CAT** [comment]
只有依赖这个包的才需要引入这个系统路径，就是不想繁琐才希望 package 的 add_linkdirs 可以被使用到的 target 继承。毕竟也有 local package 的写法而非全部都是 xmake-repo 这样的 package，和之前的功能也不冲突。
