### ISSUE TITLE
Dependencies are built after precompiled headers

### ISSUE THREAD

**Issue by richionizor** [xmake-io/xmake#4842]
### Xmake Version

v2.8.7+master.b3881c943

### Operating System Version and Architecture

Windows 10 (x64)

### Describe Bug

When a target includes a precompiled header (``set_pcxxheader``), this header is compiled BEFORE any package dependencies are processed/built.

### Expected Behavior

xmake should check/build the deps of the target before building the precompiled headers.

### Project Configuration

```
target("dependency")
	set_kind("static")
	add_files("dependency.cpp")

target("my_program")
	set_kind("binary")
        add_deps("dependency")
	add_files("my_program.cpp")
	set_pcxxheader("dependency_PCH.h")
```

### Additional Information and Error Logs

n.a.

**Comment by waruqi** [comment]
```console
add_rules("mode.debug", "mode.release")

target("foo")
    set_kind("static")
    add_files("src/foo.cpp")
    set_policy("build.across_targets_in_parallel", false)

target("test3")
    set_kind("binary")
    add_deps("foo")
    add_files("src/main.cpp")
    set_pcxxheader("src/test.h")
```

```console
ruki-2:test3 ruki$ xmake
[ 12%]: cache compiling.release src/foo.cpp
[ 25%]: archiving.release libfoo.a
[ 50%]: cache compiling.release src/test.h
[ 62%]: cache compiling.release src/main.cpp
[ 75%]: linking.release test3
[100%]: build ok, spent 0.912s
```

**Comment by waruqi** [comment]
Disable cross-target parallel compilation for target foo, so that other targets can be compiled in parallel only after all of foo's source files have been compiled.
