### ISSUE TITLE
Endianness/Byte-order detection on build machine

### ISSUE THREAD

**Issue by Hyiker** [xmake-io/xmake#4843]
### Is your feature request related to a problem? Please describe.

I'm trying to put some byte-order related functionality in my cpp code, it works like(from UE5 source code):

```c++
struct {
#if PLATFORM_LITTLE_ENDIAN
			uint32	Mantissa : 23;
			uint32	Exponent : 8;
			uint32	Sign : 1;			
#else
			uint32	Sign : 1;
			uint32	Exponent : 8;
			uint32	Mantissa : 23;			
#endif
}
```

c/cpp lacks standard macros for this, I noticed there was once an issue mentioned this: #514 .However, `__BYTE_ORDER__` is not a portable way to do this, for some compilers such as MSVC doesn't have such definition.

CMake provides `TestBigEndian` snippet(supserseded by `CMAKE_<LANG>_BYTE_ORDER` since 3.20), supporting c/c++/cuda/objc/objcxx. Providing resembling API greatly empowers languages such as cpp lack the ability of compile-time byte order determination.

### Describe the solution you'd like

CMake uses [TestEndianess.c.in](https://github.com/Kitware/CMake/blob/master/Modules/TestEndianess.c.in) for this functionality, and we can refer to [TestEndianess.c.in](https://github.com/Kitware/CMake/blob/master/Modules/TestBigEndian.cmake) to do such test.
I suggest run this test in configuration stage( `xmake f` ), and provide an variable `var.$(byteorder)` describing the endianness. To reduce complexity, the value should be either `big_endian` or `little_endian`, ignoring other conditions.

**Comment by waruqi** [comment]
you can refer this patch. https://github.com/xmake-io/xmake/pull/4349

then open a pr to add `check_bigendian`

**Comment by waruqi** [comment]
Thanks!
