### ISSUE TITLE
xmake test 并发测试用例时输出进度乱序, 希望排序后输出

### ISSUE THREAD

**Issue by ruiyuanlu** [xmake-io/xmake#4846]
### Xmake 版本

2.8.8

### 操作系统版本和架构

Win10

### 描述问题

如图所示，100%进度跑到中间去了，并发测试用例时输出进度乱序了, 如果使用 xmake test -j1 没有乱序，但是测试速度降低了
![image](https://github.com/xmake-io/xmake/assets/16774189/73ffc4d9-0c1c-49e2-8720-c74fd49e5e49)

### 期待的结果

并发时也能够按顺序给出进度指示: [33%]->[66%]->[100%]

### 工程配置

NO

### 附加信息和错误日志

NO

**Comment by ruiyuanlu** [comment]
补充一下，目前的进度百分比好像是和测试用例 target 的创建顺序绑定的，非并发的时候，这个逻辑OK，但是并发的时候，如果先创建的测试用例执行时间长，后创建的执行用例执行时间短，就能100%复现这个问题

**Comment by waruqi** [comment]
try this patch. https://github.com/xmake-io/xmake/pull/4849

```console
xmake update -s github:xmake-io/xmake#progress
```
