### ISSUE TITLE
Keep packages required with a branch up to date

### ISSUE THREAD

**Issue by charlesseizilles** [xmake-io/xmake#4853]
### Is your feature request related to a problem? Please describe.

I have a project that depends on a package like so
```lua
add_requires("mypkg dev")
```
But once the package is compiled, it doesn't change even though new commits have been pushed on the branch, forcing the use of `xrepo remove --all mypkg` or equivalent.

### Describe the solution you'd like

I would like for xmake to automatically detect if new commits have been pushed and ask me if I want to update the package, when a branch is used.

**Comment by waruqi** [comment]
Detecting branch updates is time-consuming, we need to additionally pull commit logs ahead of time for each package, and it can introduce changes that break compatibility. This should not be the recommended default behaviour. We will not consider supporting it at this time.

you can pass commit to ensure to install package each time.

`add_requires("mypkg 0e7a8622bf84008c706473d54c3c699c183ff6fc")`

or use package version

**Comment by charlesseizilles** [comment]
I understand, thank you
