### ISSUE TITLE
xmake f -c -P . 清除配置报错 

### ISSUE THREAD

**Issue by Dozingfiretruck** [xmake-io/xmake#4857]
### Xmake 版本

2.8.8

### 操作系统版本和架构

win10

### 描述问题

工程能正常编译，但是xmake f -c -P . 清除配置报错 

### 期待的结果

正常清除

### 工程配置

xmake.lua :
```lua
project_dir = os.scriptdir()
csdk_root = "../../"
includes(csdk_root)
```

csdk_root下xmake.lua:
```lua
-- 各种通用配置
includes("bootloader")
includes("project")
```

bootloader下 xmake.lua
```lua
target("driver",function()
    set_kind("static")
    set_targetdir(project_dir.."/build/bootloader_libdriver")
    --  各种通用配置
end)
```

其中 ‘set_targetdir(project_dir.."/build/bootloader_libdriver")’ 中的 project_dir就会报错，全局变量描述域应该正常使用的，而且编译是正常的，只有  xmake f -c -P . 报错

### 附加信息和错误日志

 ![image](https://github.com/xmake-io/xmake/assets/24759100/a805181e-9729-44ee-94cc-c073fd581ca0)

**Comment by waruqi** [comment]
给下完整工程，好歹 code 贴贴好么，这么乱 怎么看

**Comment by Dozingfiretruck** [comment]
> 给下完整工程，好歹 code 贴贴好么，这么乱 怎么看

已修改

**Comment by waruqi** [comment]
无法复现

```lua
add_rules("mode.debug", "mode.release")

foo=os.scriptdir()
target("foo")
    set_kind("static")
    add_files("src/foo.cpp")

includes("src")
```

```lua
includes("bar")
```

```lua
target("test8", function ()
    set_kind("binary")
    add_deps("foo")
    add_files("src/main.cpp")
    print(foo)
end)
```

```console
ruki-2:test8 ruki$ xmake
/private/tmp/test8
/private/tmp/test8
```

**Comment by waruqi** [comment]
给个完整可复现的最小 example

**Comment by Dozingfiretruck** [comment]
> 给个完整可复现的最小 example

仓库： https://gitee.com/openLuat/luatos-soc-2024

在 luatos-soc-2024\project\test 目录下执行 xmake -P . 可正常编译
执行 xmake f -c -P . 清除会报错

**Comment by waruqi** [comment]
再试试，`xmake update -s dev`

**Comment by Dozingfiretruck** [comment]
> > 给个完整可复现的最小 example
> 
> 仓库： https://gitee.com/openLuat/luatos-soc-2024
> 
> 在 luatos-soc-2024\project\test 目录下执行 xmake -P . 可正常编译 执行 xmake f -c -P . 清除会报错



> xmake update -s dev

可以了
