### ISSUE TITLE
add_cflags 编译标志覆盖问题

### ISSUE THREAD

**Issue by junknet** [xmake-io/xmake#4868]
### Xmake Version

xmake v2.8.8+20240303

### Operating System Version and Architecture

6.6.19-1-MANJARO

### Describe Bug

add_cflags("-g", "-O2", {force = true}) 和自动检测标志-Oz冲突。

### Expected Behavior

编译标志-Oz被覆盖 期望是编译命令中仅有 -O2

### Project Configuration

android ndk 项目编译 使用如下命令配置工程 ` xmake f -p android --ndk=/opt/android-ndk -a arm64-v8a`
xmake.lua 中 添加 add_cflags("-g", "-O2", {force = true})

### Additional Information and Error Logs

[  3%]: cache compiling.release src/test_func.c
/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -c --sysroot=/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot -isystem /opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/aarch64-linux-android -Qunused-arguments -target aarch64-none-linux-android21 -fPIE -pie -fvisibility=hidden -Oz -std=c99 -D__LIBELF64=1 -D__libelf_u64_t=uint64_t -D__libelf_i64_t=int64_t -isystem /home/junknet/.xmake/packages/l/libelf/0.8.13/124d2cfe16ab4133b33f109cc6e70515/include -isystem /home/junknet/.xmake/packages/l/libelf/0.8.13/124d2cfe16ab4133b33f109cc6e70515/include/libelf -isystem /opt/android-ndk/sources/cxx-stl/llvm-libc++/include -isystem /opt/android-ndk/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/include -isystem /opt/android-ndk/sources/cxx-stl/llvm-libc++abi/include -w -g -O2 -DNDEBUG -o build/.objs/mambo_master/android/arm64-v8a/release/src/test_func.c.o src/test_func.c

**Comment by waruqi** [comment]
支持不了，也没必要，flags 原本就是后面的覆盖前面的。。`-Oz -O2` 即使全部设置了，实际也是仅 `-O2` 生效。。

另外，应该尽可能使用 `set_optimize("faster")` 去处理优化选项。。而不是直接用 flag，不仅跨编译器，也能覆盖内部设置

同理 -g 也是
