### ISSUE TITLE
Support to build the selected files for the given target

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#487]
### Is your feature request related to a problem? Please describe.

see https://github.com/xmake-io/xmake/issues/257#issuecomment-511777701

### Describe the solution you'd like

```console
xmake build --files=src/main.c <target>
xmake build --files='src/*.c' <target>
xmake build -f 'src/**.c|excluded_file.c;xxx/file1.c;yyy/file2.c' <target>
```

**Comment by OpportunityLiu** [comment]
这样可以吗？
```
$xmake build -v -P . -w --selected-file="\src\源.c;\src\main.c" test
```

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/61293731-ed899e00-a806-11e9-869a-90fbb91222c6.png)
这还是之前那个搞出来的bug？

**Comment by OpportunityLiu** [comment]
另外，数组分隔符是用 `;` 还是 `,` ，最好尽早统一一下吧，或者另选一个更安全的字符

**Comment by waruqi** [comment]
> 这样可以吗？
> 
> ```
> $xmake build -v -P . -w --selected-file="\src\源.c;\src\main.c" test
> ```

可以通过path.translate做些兼容处理 不过对根 \ 的处理 如果单为了支持vs 处理成相对路径，那在cygwin下就有歧义了

**Comment by waruqi** [comment]
> 另外，数组分隔符是用 `;` 还是 `,` ，最好尽早统一一下吧，或者另选一个更安全的字符

目前像--includedirs里面，现在是通过path.sepenv来分割的 win上传 ; unix上传 :

**Comment by waruqi** [comment]
> ![图片](https://user-images.githubusercontent.com/13471233/61293731-ed899e00-a806-11e9-869a-90fbb91222c6.png)
> 这还是之前那个搞出来的bug？

什么问题？

**Comment by OpportunityLiu** [comment]
> 什么问题？

默认值为nil的帮助就显示不出来了

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/61296320-7951f900-a80c-11e9-92c6-91dcec78fbca.png)

**Comment by OpportunityLiu** [comment]
按照xmake的命名惯例是不是应该写成 <code>--selectedfile<b>s</b></code> ?

**Comment by waruqi** [comment]
> 按照xmake的命名惯例是不是应该写成 `--selectedfiles` ?

可以

**Comment by waruqi** [comment]
> > 什么问题？
> 
> 默认值为nil的帮助就显示不出来了

这个我等会看下

**Comment by OpportunityLiu** [comment]
那就files

**Comment by OpportunityLiu** [comment]
build的默认菜单出现了两次
![图片](https://user-images.githubusercontent.com/13471233/61297906-d1d6c580-a80f-11e9-9cfc-598ad9cf7db4.png)

**Comment by waruqi** [comment]
@OpportunityLiu 我初步整完了 测试了下 跟vsxmake配合ok，你这试试

**Comment by OpportunityLiu** [comment]
合并了吗？在哪个分支试？

**Comment by waruqi** [comment]
恩，我直接rebase到dev了

**Comment by OpportunityLiu** [comment]
挺好的，我这里没啥问题，cuda的文件也可以

**Comment by OpportunityLiu** [comment]
有必要把`-f`就这么分出去吗？这功能应该不是常用功能吧

**Comment by waruqi** [comment]
> 有必要把`-f`就这么分出去吗？这功能应该不是常用功能吧

是不怎么常用。。去了也可以。
