### ISSUE TITLE
vscode中使用 XMake:CreatProject 命令解析目录字符串异常

### ISSUE THREAD

**Issue by yxyh357** [xmake-io/xmake#4883]
### Xmake 版本

xmake v2.8.9+dev.bcc939b30

### 操作系统版本和架构

Windows 10 专业版  22H2

### 描述问题

我创建了一个名为`"a tour of c++"`的目录,并在vscode中以`XMake:CreateProject->c++->console`的方式创建项目失败,返回异常`error: invalid argument: of`,当我直接使用终端输入` xmake create -t console -l c++ -P "d:\project\vscode\cpp\a tour of c++" `时正常创建,但当我使用vscode使用的命令`C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command xmake create -t console -l c++ -P "d:\project\vscode\cpp\a tour of c++"`时复现上述异常

### 期待的结果

可以正常的使用`XMake:CreateProject->c++->console`的方式创建我的在"a tour of c++"目录下的c++项目

### 工程配置

None

### 附加信息和错误日志

xmake v2.8.9+dev.bcc939b30, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, xmake.io
    
    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor

Usage: $xmake create [options] [target]

Create a new project.

Common options:
    -q, --quiet                         Quiet operation.
    -y, --yes                           Input yes by default if need user confirm.
        --confirm=CONFIRM               Input the given result if need user confirm.
                                            - yes
                                            - no
                                            - def
    -v, --verbose                       Print lots of verbose information for users.
        --root                          Allow to run xmake as root.
    -D, --diagnosis                     Print lots of diagnosis information (backtrace, check info ..) only for developers.
                                        And we can append -v to get more whole information.
                                            e.g. $ xmake -vD
    -h, --help                          Print this help message and exit.

    -F FILE, --file=FILE                Read a given xmake.lua file.
    -P PROJECT, --project=PROJECT       Change to the given project directory.
                                        Search priority:
                                            1. The Given Command Argument
                                            2. The Envirnoment Variable: XMAKE_PROJECT_DIR
                                            3. The Current Directory

Command options (create):
    -f, --force                         Force to create project in a non-empty directory.
    -l LANGUAGE, --language=LANGUAGE    The project language (default: c++)
                                            - c
                                            - c++
                                            - cuda
                                            - dlang
                                            - fortran
                                            - go
                                            - nim
                                            - objc
                                            - objc++
                                            - pascal
                                            - rust
                                            - swift
                                            - vala
                                            - zig
    -t TEMPLATE, --template=TEMPLATE    Select the project template id or name of the given language. (default: console)
                                            - console: c, c++, cuda, dlang, fortran, go, nim, objc, objc++, pascal, rust, swift, vala, zig
                                            - qt.console: c++
                                            - qt.quickapp: c++
                                            - qt.quickapp_static: c++
                                            - qt.shared: c++
                                            - qt.static: c++
                                            - qt.widgetapp: c++
                                            - qt.widgetapp_static: c++
                                            - shared: c, c++, cuda, dlang, fortran, nim, pascal, vala, zig
                                            - static: c, c++, cuda, dlang, fortran, go, nim, rust, vala, zig
                                            - tbox.console: c, c++
                                            - tbox.shared: c, c++
                                            - tbox.static: c, c++
                                            - wxwidgets: c++
                                            - xcode.bundle: objc, objc++
                                            - xcode.framework: objc, objc++
                                            - xcode.iosapp: objc
                                            - xcode.iosapp_with_framework: objc
                                            - xcode.macapp: objc
                                            - xcode.macapp_with_framework: objc
                                            - xmake.cli: c, c++

          target                        Create the given target.
                                        Uses the project name as target if not exists.
error: invalid argument: of

**Comment by waruqi** [comment]
应该可以了，更新下试试

**Comment by yxyh357** [comment]
正常了
