### ISSUE TITLE
Qt工程添加预编译头文件后，生成CMake工程moc文件编译报错

### ISSUE THREAD

**Issue by supf1994** [xmake-io/xmake#4886]
### Xmake 版本

2.8.9

### 操作系统版本和架构

windows10 

### 描述问题

Qt工程添加预编译头文件后，使用xmake project_test -k cmake 生成CMake工程moc文件编译报错
project_test 插件修复了 #4884 问题
生成cmake文件后，使用QtCreator打开，编译时报如下错误
![image](https://github.com/xmake-io/xmake/assets/23397492/59d1c525-2cd8-4133-8bb3-a36d71834735)

似乎是预编译头文件还未生成时就先生成moc文件并编译，导致该错误

测试工程
[qt_test.zip](https://github.com/xmake-io/xmake/files/14769886/qt_test.zip)

### 期待的结果

...

### 工程配置

...

### 附加信息和错误日志

...

**Comment by supf1994** [comment]
> 试下这个 patch #4888
> 
> ```
> xmake update -s dev
> ```

可以解决这个问题，不过正式的工程中，依然有部分带路径的cl参数里出现了 \

**Comment by waruqi** [comment]
既然这里解决，我就关了，有其他问题，再开 issues
