### ISSUE TITLE
当一个 object target 添加另一个 object target 作为依赖时无法继承 .o 文件

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#4887]
### 你在什么场景下需要该功能？

![image](https://github.com/xmake-io/xmake/assets/47598093/4db24f73-a037-44db-b80d-25745d1da04b)
按照文档描述 object target 是编译完的目标文件集合，当前项目中有多个 object target 而且存在依赖关系，例如：
```lua
target("zlog", function()
    set_kind("object")
    add_files("zlog/*.cc|*_test.cc")
    add_syslinks("PocoFoundation", "pthread", "dl")
end)

target("convert", function()
    set_kind("object")
    add_files("zutil/convert/*.cc|*_test.cc")
    add_syslinks("pthread")
    add_deps("zlog")
end)

target("coord_convert_test", function()
    set_kind("binary")
    set_default(false)
    add_files("zutil/convert/coord_convert_test.cc")
    add_syslinks("pthread")
    add_packages("gtest")
    add_deps("convert")
end)
```

在这种写法下 coord_convert_test 编译会丢失 zlog 的 .o 文件，虽然可以通过在 target coord_convert_test 中 add_deps("zlog", "convert") 解决，但是一旦项目中 object target 较多就会很麻烦。

### 描述可能的解决方案

希望一个 object target 可以继承它所有通过 add_deps() 引入的 object target 的 .o 文件。比如可以加一个 {public = true } 配置：

target("convert", function()
    set_kind("object")
    add_files("zutil/convert/*.cc|*_test.cc")
    add_syslinks("pthread")
    add_deps("zlog", {public = true})  -- 导出 zlog 的目标文件
end)

**Comment by waruqi** [comment]
再试试 xmake update -s dev

**Comment by TOMO-CAT** [comment]
> 再试试 xmake update -s dev

报错了，不知道是不是和我环境没清理干净相关：

```bash
Already up to date.
ok
/usr/bin/git rev-parse HEAD
/usr/bin/git rev-parse HEAD
checking for cmake ... no
checking for cmake ... /usr/bin/cmake
error: @programdir/core/main.lua:329: @programdir/core/sandbox/modules/import/core/base/task.lua:65: @programdir/modules/async/runjobs.lua:338: ....xmake/repositories/xmake-repo/packages/z/zlib/xmake.lua:26: attempt to index a nil value
stack traceback:
    [....xmake/repositories/xmake-repo/packages/z/zlib/xmake.lua:26]: in function 'on_fetch'
    [@programdir/core/package/package.lua:1733]: in function '_fetch_library'
    [@programdir/core/package/package.lua:1943]: in function 'fetch'
    [...modules/private/action/require/impl/install_packages.lua:333]: in function 'jobfunc'
    [@programdir/modules/async/runjobs.lua:256]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:961: in function 'os.raiselevel'
        (...tail calls...)
        @programdir/core/main.lua:329: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:406: in function <@programdir/core/base/scheduler.lua:399>
```

![image](https://github.com/xmake-io/xmake/assets/47598093/daf08379-8288-40f0-a2f6-1ecb4252c627)

**Comment by TOMO-CAT** [comment]
我用的是 gitee 的源：
![image](https://github.com/xmake-io/xmake/assets/47598093/cbf934d2-c6f2-439c-97e2-2ca535d71da6)

**Comment by waruqi** [comment]
执行 xmake l xmake.version 看下，不行就全量重装下

**Comment by TOMO-CAT** [comment]
> 执行 xmake l xmake.version 看下，不行就全量重装下

继承 .o 的可以了，还有个问题请教下，object target 里的 add_syslinks 不能被导出到 binary 里去。

```lua
target("zutil.thunder", function()
    set_kind("object")
    add_files("*.cc")
    remove_files("*_test.cc")
    add_syslinks("curl")  -- 未导出
    add_deps("zlog")
end)

target("zutil.thunder.http_url_test", function()
    set_kind("binary")
    add_files("http_url_test.cc")
    add_deps("zutil.thunder")
    add_packages("gtest")
end)
```

编译时报错：

![image](https://github.com/xmake-io/xmake/assets/47598093/a1791e0c-45c8-4c3e-a28e-f45d61ed7b28)

虽然加一个 {public = true} 可以解决，但是我理解这种链接时参数应该是无条件导出的，毕竟生成 .o 时也用不上，还是有啥其他考虑呢？

**Comment by waruqi** [comment]
再试试，xmake update -s dev

**Comment by TOMO-CAT** [comment]
> 再试试，xmake update -s dev

可以了，能正常导出 syslinks
