### ISSUE TITLE
Use C implementation for *trim

### ISSUE THREAD

**Issue by OpportunityLiu** [xmake-io/xmake#489]
还有，`*trim` 还是赶紧换C实现吧，太慢了。。 我本来还想把每个输入trim一下，结果一测满了100多倍。。。

_Originally posted by @OpportunityLiu in https://github.com/xmake-io/xmake/pull/488#issuecomment-511832478_

**Comment by waruqi** [comment]
我用c重新实现了。。你测测，虽然没做什么特殊优化。。应该会比之前的快不少。。

**Comment by OpportunityLiu** [comment]
Related: #492
