### ISSUE TITLE
xmake 执行时报错

### ISSUE THREAD

**Issue by KarryCharon** [xmake-io/xmake#4892]
### Xmake Version

2.8.9

### Operating System Version and Architecture

macOS 14.3.1 (23D60)

### Describe Bug

执行xmake时报错:
error: @programdir/core/main.lua:329: attempt to compare string with table
stack traceback:
    [C]: in function 'sort'
    [@programdir/rules/plugin/compile_commands/xmake.lua:61]: in function 'buildscript'
    [@programdir/actions/build/main.lua:97]: in function '_do_project_rules'
    [@programdir/actions/build/main.lua:144]: in function 'catch'
    [@programdir/core/sandbox/modules/try.lua:123]: in function 'try'
    [@programdir/actions/build/main.lua:118]: in function 'build_targets'
    [@programdir/actions/build/main.lua:201]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:275]:
    [@programdir/core/base/task.lua:491]: in function 'run'
    [@programdir/core/main.lua:327]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:406]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:957: in function 'os.raiselevel'
        (...tail calls...)
        @programdir/core/main.lua:329: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:406: in function <@programdir/core/base/scheduler.lua:399>

### Expected Behavior

-

### Project Configuration

-

### Additional Information and Error Logs

-

**Comment by star-hengxing** [comment]
估计是某次修改引入，先试试 `xmake update -s dev`，如果还不行参考这个
https://github.com/Ajatt-Tools/gd-tools/commit/94f46ebd000fdffef0578dbddd4edc88a35e3259

**Comment by waruqi** [comment]
贴完整 `-vD` logs  和 xmake.lua

**Comment by KarryCharon** [comment]
> 贴完整 `-vD` logs 和 xmake.lua

大概知道了 是由 add_headerfiles("src/*.h", {prefixdir = "xxx"}) 导致的, 只要 不传prefixdir 就行,
内部处理的时候有一个 table.sort 这时候 table里理应全是字符串, 但混入了 {prefixdir = "xxx"} 因此导致了 attempt to compare string with table 异常.

**Comment by waruqi** [comment]
compile_commands 这个 sort 我记得 dev 上已经修了才对。。可以更新到 dev 后试下。。

```
xmake update -s dev
```

**Comment by KarryCharon** [comment]
> compile_commands 这个 sort 我记得 dev 上已经修了才对。。可以更新到 dev 后试下。。
> 
> ```
> xmake update -s dev
> ```

确实没问题了 谢谢
