### ISSUE TITLE
使用 add_files 添加的 .def 文件有修改时没有触发重新链接

### ISSUE THREAD

**Issue by SuperSodaSea** [xmake-io/xmake#4898]
### Xmake 版本

xmake v2.8.9+HEAD.cb1b65054

### 操作系统版本和架构

Windows 10 专业版 2004

### 描述问题

使用 add_files 添加 .def 文件后，如果 .def 文件有修改，并不会触发重新链接。

### 期待的结果

xmake 应当将 .def 文件作为链接时的依赖项，.def 文件有更改时触发重新链接。

### 工程配置

**xmake.lua**
```lua
target("DefBug")
    set_kind("shared")
    add_files("Main.cpp", "Module.def")
```

**Main.cpp**
```cpp
int Valid() { return 123; }
```

**Module.def**（修改前）
```
EXPORTS
    Valid
```

**Module.def**（修改后）
```
EXPORTS
    Invalid
```

只修改 **Module.def** 并不会触发重新链接（构建成功完成），xmake clean 之后再重新构建才会报错。

### 附加信息和错误日志

N/A（应该不需要）

**Comment by waruqi** [comment]
再试试，`xmake update -s dev`

**Comment by SuperSodaSea** [comment]
确认已修复，感谢！
