### ISSUE TITLE
package.tools.cmake预设了一个额外的arg导致交叉工具链构建package无法进行

### ISSUE THREAD

**Issue by CyanCloverFern** [xmake-io/xmake#4899]
### Xmake 版本

xmake v2.8.3+HEAD.2b61611fb

### 操作系统版本和架构

win10

### 描述问题

package.tools.cmake添加了-DCMAKE_MAKE_PROGRAM=C:\usr_tool\gcc13\all\x86_64-w64-mingw32\bin\mingw32-make.exe选项，交叉工具链一般不够造这个东西（mingw32-make不包含在binutils、gcc、libc（mingw32或者ucrt中））

### 期待的结果

可以自行控制是否需要添加这一选项，将之挪用到options中

### 工程配置

使用xmake/tests/project/c/library_with_cmakelists进行的排查实验
set_languages("c++20")

add_rules("mode.debug", "mode.release")

add_includedirs("deps", "includes")

add_options("test_links")
  add_links("glu32", "gdi32", "comdlg32", "advapi32", "uuid", "oleaut32", "shell32", "kernel32", "user32", "winspool")
option_end()

package("foo")
    add_deps("cmake")
    set_sourcedir(path.join(os.scriptdir(), "foo"))
    set_policy("package.install_always", true)
    on_install(function (package)
        local configs = {}
        table.insert(configs, "-DCMAKE_BUILD_TYPE=" .. (package:debug() and "Debug" or "Release"))
        table.insert(configs, "-DBUILD_SHARED_LIBS=" .. (package:config("shared") and "ON" or "OFF"))
        import("package.tools.cmake").install(package, configs)
    end)
    on_test(function (package)
        assert(package:has_cfuncs("add", {includes = "foo.h"}))
    end)
package_end()

includes("src/*/*")
includes("deps")
includes("test/*")
includes("programming_windows/*")

### 附加信息和错误日志

PS C:\Users\Cyan\Desktop\test\learn> xmake b --verbose  programming_windows.volume04.system1 
checking for mingw directory ... C:\usr_tool\gcc13\all\x86_64-w64-mingw32
checking for unzip ... ok
checking for git ... ok
checking for gzip ... ok
checking for tar ... ok
git rev-parse HEAD
checking for cmake ... no
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for cmake ... no
checking for cmake ... no
checking for cmake ... ok
checking for xmake::glm_l ... no
checking for glm_l ... no
note: install or modify (m) these packages (pass -y to skip confirm)?
  -> glm_l latest
please input: y (y/n/m)

checking for x86_64-w64-mingw32-gcc ... C:\usr_tool\gcc13\all\x86_64-w64-mingw32\bin\x86_64-w64-mingw32-gcc
checking for the c compiler (cc) ... x86_64-w64-mingw32-gcc
checking for x86_64-w64-mingw32-g++ ... C:\usr_tool\gcc13\all\x86_64-w64-mingw32\bin\x86_64-w64-mingw32-g++
checking for the c++ compiler (cxx) ... x86_64-w64-mingw32-g++
checking for x86_64-w64-mingw32-gcc ... C:\usr_tool\gcc13\all\x86_64-w64-mingw32\bin\x86_64-w64-mingw32-gcc
checking for the assember (as) ... x86_64-w64-mingw32-gcc
checking for C:\usr_tool\gcc13\all\x86_64-w64-mingw32\bin\ar ... ok
checking for the static library archiver (ar) ... ar
checking for C:\usr_tool\gcc13\all\x86_64-w64-mingw32\bin\ranlib ... ok
checking for the archive index generator (ranlib) ... ranlib
checking for x86_64-w64-mingw32-windres ... no
checking for the windows resource compiler (mrc: x86_64-w64-mingw32-windres) ... no
checking for C:\usr_tool\gcc13\all\x86_64-w64-mingw32\bin\windres ... ok
checking for the windows resource compiler (mrc) ... windres
checking for x86_64-w64-mingw32-g++ ... C:\usr_tool\gcc13\all\x86_64-w64-mingw32\bin\x86_64-w64-mingw32-g++
checking for the linker (ld) ... x86_64-w64-mingw32-g++
checking for x86_64-w64-mingw32-g++ ... C:\usr_tool\gcc13\all\x86_64-w64-mingw32\bin\x86_64-w64-mingw32-g++
checking for the shared library linker (sh) ... x86_64-w64-mingw32-g++
checking for cmake ... ok
checking for pkgconf ... no
cmake -DCMAKE_INSTALL_PREFIX=C:\Users\Cyan\Desktop\test\learn\build\.packages\g\glm_l\latest\dbf654cbf0394970a33564d98b8d4ac1 -DCMAKE_INSTALL_LIBDIR:PATH=lib -G "Unix Makefiles" -DCMAKE_AR=C:/usr_tool/gcc13/all/x86_64-w64-mingw32/bin/ar.exe -DCMAKE_OSX_SYSROOT= -DHAVE_FLAG_SEARCH_PATHS_FIRST=0 -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_ASM_COMPILER=C:/usr_tool/gcc13/all/x86_64-w64-mingw32/bin/x86_64-w64-mingw32-gcc.exe -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=BOTH -DCMAKE_ASM_FLAGS=-m64 -DCMAKE_C_COMPILER=C:/usr_tool/gcc13/all/x86_64-w64-mingw32/bin/x86_64-w64-mingw32-gcc.exe -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=BOTH -DCMAKE_SHARED_LINKER_FLAGS=-m64 -DCMAKE_EXE_LINKER_FLAGS=-m64 -DCMAKE_STATIC_LINKER_FLAGS= -DCMAKE_MAKE_PROGRAM=C:\usr_tool\gcc13\all\x86_64-w64-mingw32\bin\mingw32-make.exe -DCMAKE_CXX_COMPILER=C:/usr_tool/gcc13/all/x86_64-w64-mingw32/bin/x86_64-w64-mingw32-g++.exe -DCMAKE_RC_COMPILER=C:/usr_tool/gcc13/all/x86_64-w64-mingw32/bin/windres.exe -DCMAKE_CXX_FLAGS=-m64 -DCMAKE_C_FLAGS=-m64 -DCMAKE_RANLIB=C:/usr_tool/gcc13/all/x86_64-w64-mingw32/bin/ranlib.exe -DCMAKE_FIND_ROOT_PATH=C:\usr_tool\gcc13\all\x86_64-w64-mingw32 C:\Users\Cyan\Desktop\test\learn\includes\glm
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/usr_tool/gcc13/all/x86_64-w64-mingw32/bin/x86_64-w64-mingw32-gcc.exe
-- Check for working C compiler: C:/usr_tool/gcc13/all/x86_64-w64-mingw32/bin/x86_64-w64-mingw32-gcc.exe - broken
CMake Error at C:/Users/Cyan/scoop/apps/cmake/3.26.4/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "C:/usr_tool/gcc13/all/x86_64-w64-mingw32/bin/x86_64-w64-mingw32-gcc.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/Cyan/Desktop/test/learn/build/.packages/g/glm_l/latest/cache/build_dbf654cb/CMakeFiles/CMakeScratch/TryCompile-bw4jws

    Run Build Command(s):C:/Users/Cyan/scoop/apps/cmake/3.26.4/bin/cmake.exe -E env VERBOSE=1 C:\usr_tool\gcc13\all\x86_64-w64-mingw32\bin\mingw32-make.exe -f Makefile cmTC_aea8d/fast && 绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆?

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.26)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
error: execv(cmake -DCMAKE_INSTALL_PREFIX=C:\Users\Cyan\Desktop\test\learn\build\.packages\g\glm_l\latest\dbf654cbf0394970a33564d98b8d4ac1 -DCMAKE_INSTALL_LIBDIR:PATH=lib -G "Unix Makefiles" -DCMAKE_AR=C:/usr_tool/gcc13/all/x86_64-w64-mingw32/bin/ar.exe -DCMAKE_OSX_SYSROOT= -DHAVE_FLAG_SEARCH_PATHS_FIRST=0 -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_ASM_COMPILER=C:/usr_tool/gcc13/all/x86_64-w64-mingw32/bin/x86_64-w64-mingw32-gcc.exe -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=BOTH -DCMAKE_ASM_FLAGS=-m64 -DCMAKE_C_COMPILER=C:/usr_tool/gcc13/all/x86_64-w64-mingw32/bin/x86_64-w64-mingw32-gcc.exe -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=BOTH -DCMAKE_SHARED_LINKER_FLAGS=-m64 -DCMAKE_EXE_LINKER_FLAGS=-m64 -DCMAKE_STATIC_LINKER_FLAGS= -DCMAKE_MAKE_PROGRAM=C:\usr_tool\gcc13\all\x86_64-w64-mingw32\bin\mingw32-make.exe -DCMAKE_CXX_COMPILER=C:/usr_tool/gcc13/all/x86_64-w64-mingw32/bin/x86_64-w64-mingw32-g++.exe -DCMAKE_RC_COMPILER=C:/usr_tool/gcc13/all/x86_64-w64-mingw32/bin/windres.exe -DCMAKE_CXX_FLAGS=-m64 -DCMAKE_C_FLAGS=-m64 -DCMAKE_RANLIB=C:/usr_tool/gcc13/all/x86_64-w64-mingw32/bin/ranlib.exe -DCMAKE_FIND_ROOT_PATH=C:\usr_tool\gcc13\all\x86_64-w64-mingw32 C:\Users\Cyan\Desktop\test\learn\includes\glm) failed(1)
  => install glm_l latest .. failed
error: install failed!

**Comment by waruqi** [comment]
跟 mingw32-make.exe 没啥关系，没指定这个，反而一堆 包得跪。。应该是 `\\` 没转成 `/` 导致

更新到 dev 再试试。`xmake update -s dev`

**Comment by CyanCloverFern** [comment]
> 跟 mingw32-make.exe 没啥关系，没指定这个，反而一堆 包得跪。。应该是 `\\` 没转成 `/` 导致
> 
> 更新到 dev 再试试。`xmake update -s dev`

oh，我已经切换到了dev分支，还是这个问题。
我在powershell里二分检索出的这个选项有问题。
并copy了一个mingw32-make到工具链的路径里，使用xmake完成了构建。

**Comment by waruqi** [comment]
> > 跟 mingw32-make.exe 没啥关系，没指定这个，反而一堆 包得跪。。应该是 `\\` 没转成 `/` 导致
> > 更新到 dev 再试试。`xmake update -s dev`
> 
> oh，我已经切换到了dev分支，还是这个问题。 我在powershell里二分检索出的这个选项有问题。 并copy了一个mingw32-make到工具链的路径里，使用xmake完成了构建。

mingw 平台，cmake 走 GNU makefiles 构建， mingw32-make.exe 是必须的，所以必须得传这个，否则无法构建。。

而不管是 mingw-w64, llvm-mingw 工具链，还是 msys2/mingw64 里，默认都是自带 mingw32-make.exe 的，不会没有。

除非你用的不是官方的 mingw ，是阉割修改版本的。从 `C:/usr_tool/gcc13/all/x86_64-w64-mingw32` 你的这个路径，就不像是用的官方 mingw。。。

建议切到上述的 mingw 工具链，否则你只能自己 copy mingw32-make.exe 过去。没其他办法。
