### ISSUE TITLE
Wrong/duplicate of help menu

### ISSUE THREAD

**Issue by OpportunityLiu** [xmake-io/xmake#490]
### Describe the bug
See https://github.com/xmake-io/xmake/issues/487#issuecomment-511791906, https://github.com/xmake-io/xmake/issues/487#issuecomment-511813449

**Comment by waruqi** [comment]
description丢失问题，是之前那次改动带来的问题，已经修复。。重复help问题，在还没启用utf8之前就已经存在，应该是另外一个问题。我还得再看下。。

**Comment by waruqi** [comment]
重复help的问题也修复了

**Comment by OpportunityLiu** [comment]
:+1:
