### ISSUE TITLE
能不能提供一个standalone版本

### ISSUE THREAD

**Issue by RPG3D** [xmake-io/xmake#4907]
### 你在什么场景下需要该功能？

把xmake嵌入到其他工程，比如ue4引擎，用来编译第三方代码，当前运行xmake需要安装exe或解压zip生成多个文件，有点重度，最好只有一个免安装的exe文件

### 描述可能的解决方案

把xmake程序本体和数据（lua）打包到一个exe中

### 描述你认为的候选方案

把数据部分使用zip封装（不需要压缩），exe运行时直接从zip内读取lua
这样只有2个文件，exe和数据包

**Comment by waruqi** [comment]
不考虑，没时间搞，如果非要嵌入，你可以直接 lua scripts 全部嵌入进去，用 XMAKE_RPOGRAM_DIR 切过去就行了。。参考 https://github.com/xmake-io/xmake/blob/master/scripts/srcenv.bat
