### ISSUE TITLE
xmake-repo 支持发布不附属于 package 的 rules

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#4911]
### 你在什么场景下需要该功能？

背景是在公司内维护了一个类似 xmake-repo 的包仓库：
![image](https://github.com/xmake-io/xmake/assets/47598093/8786d83e-d7a8-4203-9d75-b600236a25ca)

需要发布一些类似于 `mode.debug` 这种与 package 无关的 rule 给所有公司内部的仓库使用，目前的做法只能修改本地的 xmake 仓库，在这个目录新增规则：
![image](https://github.com/xmake-io/xmake/assets/47598093/723fcaa1-2474-4637-bbb8-6e3ccc4edecc)

这种做法每次发布 rule 都需要发布新的 xmake 版本，比较麻烦。

### 描述可能的解决方案

希望可以在 xmake-repo 中发布与 package 无关的 rules，例如：
![image](https://github.com/xmake-io/xmake/assets/47598093/226b0e4b-5995-4621-afe4-f08d4fdb1e89)

### 描述你认为的候选方案

或者可以发布空的 package，跳过 add_urls on_download 和 install 的步骤。

**Comment by waruqi** [comment]
既然 xmake 支持发布 package rules，那你直接搞个 fake packages 专门用于发布 rules 不就好了么。。也没啥工作量

myrules 包里 on_install 可以置空，on_test 可以不加就行了，target 里面 add_packages 也可以不加，不会做任何 link 

```
packages/m/myrules
   - rules/foo.lua
   - rules/bar.lua
   - ...
```

```lua
add_requires("myrules")

target("test")
    add_rules("@myrules/foo")
```

没必要为了这个，单独再去搞个 rules 目录，这跟上面这种，加个特定的 m/myrules 目录，根本没啥区别

**Comment by TOMO-CAT** [comment]
> myrules 包里 on_install 可以置空，on_test 可以不加就行了，target 里面 add_packages 也可以不加，不会做任何 link

你这种方案可以接受，是 issue 里提到的候选方案。

但按照你的说法配置了，但是好像没有生效：
![image](https://github.com/xmake-io/xmake/assets/47598093/bb0e7d74-b82b-4b8e-9779-23739e4c9d31)

对应的 package 写法如下：

![image](https://github.com/xmake-io/xmake/assets/47598093/20c69493-f24b-4096-8087-b647d4040787)

看样子安装成功了：

![image](https://github.com/xmake-io/xmake/assets/47598093/ffa14154-8da1-400c-a26d-3cc600c057ce)

用法如下：

```lua
add_requires("zelos")


target("zutil.time.time_test", function()
    set_kind("binary")
    add_files("time_test.cc")

    add_rules("@zelos/zelos.check_test_target")
end)
```

但是 rule 没生效，哪怕我在 rule 的 on_config 里加上 raise 语句都没任何效果。

**Comment by TOMO-CAT** [comment]
我直接在全局作用域写一个 rule 是可以生效的：
![image](https://github.com/xmake-io/xmake/assets/47598093/a49aa2b5-8703-454a-b144-6188c56e197f)

![image](https://github.com/xmake-io/xmake/assets/47598093/972e89a8-bbb1-4051-854f-9f91fc0591c9)

**Comment by waruqi** [comment]
我随手敲的，具体参考下 https://github.com/xmake-io/xmake/tree/master/tests/projects/package/package_rule

**Comment by TOMO-CAT** [comment]
> 我随手敲的，具体参考下 https://github.com/xmake-io/xmake/tree/master/tests/projects/package/package_rule

可以了，需要用 on_config，另外每次调试的时候需要重新安装 package，只修改脚本不生效。
