### ISSUE TITLE
binary target 无法 add_deps 一个 static / shared target

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#4923]
### Xmake 版本

xmake v2.8.9+dev.50dbca648

### 操作系统版本和架构

Linux 720ce3a659a2 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

当我基于多个 object target 组成一个 static / shared target：
![image](https://github.com/xmake-io/xmake/assets/47598093/827da992-388a-4b88-a6e1-9937672e3bc0)
在尝试 add_deps 这个 static / shard target 时会发现不会自动 -lxxxx：
![image](https://github.com/xmake-io/xmake/assets/47598093/7fcbab1a-d2fb-4ca8-afa4-8e215d64c73f)

手动补上对应的链接参数可以正常编译运行：
![image](https://github.com/xmake-io/xmake/assets/47598093/7f71df53-274a-4744-979c-2d1354320ee3)

### 期待的结果

我猜是因为我这个 static target 只是聚合多个 object targets，没有自己的 cc 文件触发的 bug？希望可以 add_deps 引用 static target。

### 工程配置

可以复现的最小 demo：

https://github.com/TOMO-CAT/xmake-template/blob/main/missed_static_deps/xmake.lua

### 附加信息和错误日志

```bash
$ xmake --version
xmake v2.8.9+dev.50dbca648, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, xmake.io
    
    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor
```

**Comment by star-hengxing** [comment]
给 util 加上 `add_rules("c++")`。因为该 target 没有 add_files，所以没去应用这个 rule。
我认为这不是 xmake 的 bug，因为 obj 文件也可以来自其他 native 语言，而 target 不应该知道自己会给谁调用

**Comment by waruqi** [comment]
嗯，没任何 cpp 文件，是无法自动识别当前 target 是 c++ 项目，也就没法走  c++ 的静态库继承逻辑，只能显式通过 `add_rules("c++")` 配置下

**Comment by TOMO-CAT** [comment]
> 嗯，没任何 cpp 文件，是无法自动识别当前 target 是 c++ 项目，也就没法走 c++ 的静态库继承逻辑，只能显式通过 `add_rules("c++")` 配置下，或者加个空的 cpp 文件

好的，加上后 ok 了。
