### ISSUE TITLE
Build and link can run parallel?

### ISSUE THREAD

**Issue by MaxwellGengYF** [xmake-io/xmake#4928]
### Is your feature request related to a problem? Please describe.

目前compile与link阶段，似乎有一层全局同步，即使数个target互相无依赖也会有这样的情况。在单个compile目标足够大，以及单个link耗时长的情况下，会有严重的气泡，降低性能。

### Describe the solution you'd like

无依赖的target可以并行执行link和compile。

**Comment by waruqi** [comment]
内部没有全局同步，相互无依赖就会并行构建。你可以提供下可以复现的 project example.

**Comment by MaxwellGengYF** [comment]
https://github.com/MaxwellGengYF/XMake-parallel-test.git

**Comment by waruqi** [comment]
看了下，大概知道了原因，是 runjobs 里面调度策略有问题，不过需要点时间来改进

**Comment by waruqi** [comment]
应该可以了，再试试 https://github.com/xmake-io/xmake/pull/4947

```console
xmake update -s github:xmake-io/xmake#runjobs
```
