### ISSUE TITLE
Failed to read large file with ansi encoding

### ISSUE THREAD

**Issue by OpportunityLiu** [xmake-io/xmake#493]
### Describe the bug
For large ansi file, `io.readfile()` and `file:read("a")` returns `""`
[l.zip](https://github.com/xmake-io/xmake/files/3400266/l.zip)

**Comment by waruqi** [comment]
这个我刚这边也复现了，回头我调下。。

**Comment by waruqi** [comment]
是这边封装 MultiByteToWideChar/WideCharToMultiByte 实现ansi流式转码的时候，遇到的坑导致。。

这边要实现转码流式化封装到stream，是对output size做了约束的，只在有限output size里面实现有效字符数转码，返回实际处理完毕的input 字符数。

而 MultiByteToWideChar/WideCharToMultiByte限制完output size后，如果一次送入的input 数据过多，导致output buffer不够，就会自己报错，而不是返回实际能处理的input字符数。

目前通过CharNextExA来提取每个字符的有效bytes，来按每个char bytes进行流式转码，来解决。。

不过CharNextExA又有坑，不支持utf8/utf16系列编码，蛋疼，只能对其自己解析处理了。。

反正不管怎样，目前应该没啥问题了。。先看看效果吧。。

**Comment by OpportunityLiu** [comment]
所以应该两遍调用MultiByteToWideChar确定要多少buffer啊，第一次传null返回的就是需要的buffer量

**Comment by waruqi** [comment]
> 所以应该两遍调用MultiByteToWideChar确定要多少buffer啊，第一次传null返回的就是需要的buffer量

没用，在stream里面，每次spank操作，我会限制每次转码的output bytes大小，即使确认送来的input data需要的实际output buffer量，你还是没法精准切割input data，使得送入的input data大小经过转码刚好满足，约束的output size。。

**Comment by OpportunityLiu** [comment]
我这里测试没啥问题了
