### ISSUE TITLE
xmake qt android 链接报错

### ISSUE THREAD

**Issue by HiiroAyane** [xmake-io/xmake#4930]
### Xmake 版本

2.8.8

### 操作系统版本和架构

Windows 10 22H2

### 描述问题

编译完成后，无法连接到qt的lib
error: D:\Libs\Android\SDK\ndk\21.3.6528147\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot find -lQt5Network
D:\Libs\Android\SDK\ndk\21.3.6528147\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot find -lQt5WebSockets
D:\Libs\Android\SDK\ndk\21.3.6528147\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot find -lQt5Concurrent
D:\Libs\Android\SDK\ndk\21.3.6528147\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot find -lQt5OpenGL
D:\Libs\Android\SDK\ndk\21.3.6528147\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot find -lQt5OpenGLExtensions
D:\Libs\Android\SDK\ndk\21.3.6528147\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot find -lQt5Gui
D:\Libs\Android\SDK\ndk\21.3.6528147\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot find -lQt5Widgets
D:\Libs\Android\SDK\ndk\21.3.6528147\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot find -lQt5Core
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

### 期待的结果

能正确链接。

### 工程配置

```
add_rules("mode.debug", "mode.release")
set_encodings("utf-8")
set_languages("c++17")
add_defines("TOP_CMAKE")

add_includedirs("./", "../", "../Shared/ThirdParty/rapidjson/include")
add_includedirs("E:/gstreamer/1.0/armv7/lib/glib-2.0/include")
add_includedirs("E:/gstreamer/1.0/armv7/include", "E:/gstreamer/1.0/armv7/include/glib-2.0", "E:/gstreamer/1.0/armv7/include/gstreamer-1.0")
-- add_links("E:/gstreamer/1.0/armv7/lib/**.a")
-- add_includedirs("D:/Libs/Android/android_openssl-master/ssl_1.1/include")
-- add_links("D:/Libs/Android/android_openssl-master/ssl_1.1/armeabi-v7a/*.a")

target("TopTerminal")
    add_rules("qt.widgetapp")
    add_frameworks("QtNetwork", "QtWebSockets", "QtConcurrent", "QtOpenGL", "QtOpenGLExtensions")

    add_files("Core/**.cpp")
    add_files("Core/**.h")
    add_files("Include/**.h")
    add_files("Model/**.h")
    -- add_files("Model/**.cpp")
    add_files("View/**.h")
    add_files("View/**.cpp")
    add_files("Widget/**.h")
    add_files("Widget/**.cpp")
    add_files("TopTerminal.h")
    add_files("TopTerminal.cpp")
    add_files("main.cpp")

    add_files("TopTerminal.qrc")
    add_files("Core/Theme/QStyleTheme.qrc");

    add_files(
        "../Core/Utils/AIGCJson.hpp",
        "../Shared/ThirdParty/rapidjson/include/**.h",
        "../Core/core_global.h",
        "../Core/Utils/ColorHelper.h",
        "../Core/Utils/ColorHelper.cpp",
        "../Core/Utils/QtTypeHelper.h",
        "../Core/Utils/QtTypeHelper.cpp",
        "../Core/Utils/AIGCJson.hpp",
        "../Core/Utils/QtUtils.h",
        "../Core/Utils/QtHelper.h",
        "../Core/Utils/QtHelper.cpp",   
        "../Core/TextFileIO/TextFileIO.h",
        "../Core/TextFileIO/TextFileIO.cpp",
        "../Core/HttpClient/httpclient.h",
        "../Core/HttpClient/httpclient.cpp",
        "../Core/Updater/VersionInfo.h",
        "../Core/Updater/UpdateManager.h",
        "../Core/Updater/UpdateManager.cpp"
    )
```

### 附加信息和错误日志

新建一个简单Qt项目，仍然无法链接。Qt版本是5.15.2 Android armeabi-v7a

**Comment by HiiroAyane** [comment]
![IMG_1451(20240403-150828)](https://github.com/xmake-io/xmake/assets/59410757/efc2cca3-1c1d-4614-bdbb-d179f27f165d)
QT的安卓lib里面是这样的

**Comment by star-hengxing** [comment]
add links 不能这么用
你得用 os.files 把列出文件，然后一个个添加

**Comment by HiiroAyane** [comment]
> add links 不能这么用 你得用 os.files 把列出文件，然后一个个添加

注释了的，现在的问题是 QT本身的库连接失败了。

**Comment by star-hengxing** [comment]
编辑一下排版，不然看不清。。
这里说找不到库，很明显缺了 linkdirs

**Comment by HiiroAyane** [comment]
> 编辑一下排版，不然看不清。。 这里说找不到库，很明显缺了 linkdirs

根据官网教程，QT的库是会自动连接的

**Comment by HiiroAyane** [comment]
系统环境变量设成了msvc的Qt库的bin，改成android的就可以了

**Comment by HiiroAyane** [comment]
已解决
