### ISSUE TITLE
xrepo env should output json

### ISSUE THREAD

**Issue by mentalonigiri** [xmake-io/xmake#4933]
### Is your feature request related to a problem? Please describe.

I use dark magic to build android project without gradle using xmake. Here's what I have to use now:
```
# this magic copies .so files from all add_require() dependencies.
# ... Probably from all dependencies.

xrepo env bash <<'EOF'
        # Set the output directory
        OUT="build/apk/lib/$ARCH"

        # Split the LIBRARY_PATH into an array using ":" as the delimiter
        IFS=":" read -ra PATHS <<< "$LIBRARY_PATH"

        # Iterate over each path in the PATHS array
        for path in "${PATHS[@]}"; do
        # Check if the path exists and is a directory
        if [ -d "$path" ]; then
            # Copy all .so files from the path to the output directory
            cp "$path"/*.so "$OUT"
            echo "Copied .so files from $path to $OUT"
        else
            echo "Path $path does not exist or is not a directory"
        fi
        done
EOF
done
```

with json output, I think I can just use output of `xrepo env` command to determine .so files to process, which will lead to simpler and nicer code of my build script.  You can try this thing 

### Describe the solution you'd like

I want someone to open https://github.com/xmake-io/xmake/blob/master/xmake/modules/private/xrepo/action/env.lua#L457 , and instead of using `print` function on lua dictionary, process that dictionary using json module https://github.com/xmake-io/xmake/blob/master/xmake/core/base/json.lua . Or add --json output flag, which will make it a little harder to code.

### Describe alternatives you've considered

You can see my current workaround in the beginning of this issue.

### Additional context

There's no additional context to provide. My project using described code that would benefit from xrepo being able to output json instead of just printing lua dictionary is here https://github.com/mentalonigiri/minimaldroid3

**Comment by waruqi** [comment]
What information do you want to get with xrepo env?

**Comment by mentalonigiri** [comment]
> What information do you want to get with xrepo env?

I use LIBRARY_PATH to copy .so files for all packages, including ones installed as add_requires() from other packages

**Comment by waruqi** [comment]
Why not use lua to copy them?

```lua
add_requires("zlib")
target("test")
    -- ...
    add_packages("zlib")
    after_build(function (target)
        for _, pkg in ipairs(target:orderpkgs()) do
            os.cp(path.join(pkg:installdir(), "lib", "*.so"), ...)
        end
    end)

**Comment by mentalonigiri** [comment]
very nice idea, but not all libraries install themselves to $prefix/lib, and sometimes its dll

**Comment by mentalonigiri** [comment]
Closing the issue as your method is definitely better than trying to do magic with xrepo env. I've built sdl2 + imgui app thanks to your method, here's xmake part of it:
```
add_requires("libsdl", {configs = {shared = true}})
add_requires("imgui", {configs = {
    sdl2 = true,
    opengl3 = true
}})

add_rules("mode.release", "mode.debug")

target("glue")
set_kind("static")
add_includedirs("$(env ANDROID_NDK_ROOT)/sources/android/native_app_glue", {public = true})
add_files("$(env ANDROID_NDK_ROOT)/sources/android/native_app_glue/android_native_app_glue.c")

target("jni-main")
set_default(true)
add_files("main.cpp")
add_packages("libsdl")
add_packages("imgui")
if is_plat("android") then
  set_kind("shared")
--   add_deps("glue")
  after_build(function (target)
        for _, pkg in ipairs(target:orderpkgs()) do
          print(pkg)
            os.cp(path.join(pkg:installdir(), "lib", "*.so"), target:targetdir())
        end
    end)
  add_syslinks("android",
    "EGL",
    "GLESv1_CM",
    "log")
  add_shflags("-u ANativeActivity_onCreate")
end
```
