### ISSUE TITLE
使用 set_pcxxheader 的時候編譯失敗，疑似pdb路徑指向錯誤

### ISSUE THREAD

**Issue by orzuk-lmj** [xmake-io/xmake#494]
- 我使用pch時候的語法大致上都是底下這種：
    ```
    set_pcxxheader("private/PrecompiledHeader.h")
    set_pcxxheader("PrecompiledHeader.h")
    ```
- 使用Release 2.2.7 還有更早之前的版本 2.2.3 ，在win10+vs2015環境下，都可以正常編譯。
- 抓了較新的dev分支 d6be8e7effeca32a035ce89f1d02c28501b6a839 手動編譯後，運行pch測試會報錯。
- 抓了最新的dev執行檔 [xmake-dev.exe](https://github.com/xmake-io/xmake/releases/download/v2.2.7/xmake-dev.exe) ，運行pch測試一樣會報錯。
- 以上兩者出現的錯誤訊息相同，如下列：
    ```
    error C2858: command-line option 'program database name (/FdXXXXX.cpp.obj.pdb)' 
    inconsistent with precompiled header, which used '/FdYYYYY.h.pch.pdb'

    YYYYY.cpp.obj.pdb is not the pdb file that was used when this precompiled header was created, recreate the precompiled header.
    ```

- /Fd指令指向的路徑貌似是錯誤的 (路徑有點長，且確認不一樣所以用X和Y代替)

**Comment by OpportunityLiu** [comment]
之前分离debug信息的时候引进来的bug

**Comment by orzuk-lmj** [comment]
順帶一提，Release v2.2.7版本，使用了 set_pcxxheader 之後，接著`xmake project -k vs2015`生成的 `.vcxproj ` 無法用IDE載入，會顯示 load failed 錯誤。移除  set_pcxxheader  後就正常了。

**Comment by waruqi** [comment]
> 嘗試把 `add_headerfiles("**.h")` 變更為 `add_headerfiles("public/**.h")` 之後，**主動排除 PCH 檔案**，貌似就可以避免這個問題了。

也可以通过 `add_headerfiles("**.h|xxx/PrecompiledHeader.h")` 来排除pch 试试。

这个fix我merge了，一会你再试试：https://github.com/xmake-io/xmake/pull/495

**Comment by orzuk-lmj** [comment]
感謝!  可以正常使用了。
