### ISSUE TITLE
os.dirs在MacOS 14.4.1上无法正常运行

### ISSUE THREAD

**Issue by zuguorui** [xmake-io/xmake#4945]
### Xmake 版本

2.8.9

### 操作系统版本和架构

MacOS 14.4.1 Apple silicon M1

### 描述问题

os.dirs返回的结果仅有当前目录"."。
以下是使用xmake lua命令进行测试：
```lua
xmake> os.dirs(".")
< { 
    "." 
  }
xmake> os.dirs("~/")
< { 
    "/Users/zu" 
  }
```
同样，os.files也无法返回任何结果。

### 期待的结果

希望该函数能正常返回当前文件夹下的所有子文件夹

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
仔细看文档，匹配子目录，要加 `*` 模式匹配，递归模式匹配，`**`
