### ISSUE TITLE
是否可以控制包构建的并行度，防止在配置较差的机器上被 oom killer 干掉

### ISSUE THREAD

**Issue by ivanallen** [xmake-io/xmake#4946]
### 你在什么场景下需要该功能？

默认情况下使用 `xmake f -c` 会触发包下载和构建，此时包会一起进行构建，在机器配置不太好的情况下，编译任务被系统 oom kill 掉。

查了下文档，没找到相关的配置。

### 描述可能的解决方案

可以控制第三主包同时构建的并行度。

**Comment by waruqi** [comment]
加 -vD 就会强制 挨个包单独构建

**Comment by ivanallen** [comment]
> 加 -vD 就会强制 挨个包单独构建

我也发现这样可以串行，但是这样又感觉太慢，希望可以像 build 那样，稍微控制下同时构建包的最大数量，这样既可以保证不被 kill 掉，又能加快构建速度。

这个问题是在 cicd 机器上发现的，有时候发现任务会有一定机率被 kill 掉

**Comment by waruqi** [comment]
`xmake f -c` 控制不了，要么你删了 `.xmake` 走 `xmake -jN` 去控制

```console
rm -rf .xmake
xmake -jN
```

这样可以控制每个包内部构建系统的并行度，但是包之间的并行度是控制不了的，目前写死了最大 4 个包同时处理，原本就不会太多。
