### ISSUE TITLE
自定义包中自定义目标文件名的问题

### ISSUE THREAD

**Issue by huye** [xmake-io/xmake#4951]
### Xmake 版本

v2.8.9+HEAD.cb1b650

### 操作系统版本和架构

macOS Sonoma 14.2.1 (23C71)

### 描述问题

我在包项目的 xmake.lua 中使用了如下代码区别各个模式版本的文件名
`
if not is_mode("release") then
    set_suffixname("-$(mode)")
end
`
现在的问题就是使用 xmake package 后，生成的 packages/x/xxx/xmake.lua 文件中 result.links = "xxx-debug" 是最后一次的，在别的项目中引入时不同模式都成了这个，不会随变化了。

### 期待的结果

希望老大看看是不是能改进技术这个情况，最好是文件名能一一对应。如果不行的话，那就在 package 打包后把这个文件名统一掉。

### 工程配置

if not is_mode("release") then
    set_suffixname("-$(mode)")
end

### 附加信息和错误日志

希望能
release 时
result.links = "xxx"
debug 时
result.links = "xxx-debug"
不行的话，希望
packages/x/xxx/macosx/x86_64/debug/lib/libxxx-debug.dylib
统一成
packages/x/xxx/macosx/x86_64/debug/lib/libxxx.dylib
这样之类的，保证依赖没有问题

**Comment by waruqi** [comment]
packages/x/xxx/macosx/x86_64/debug 前面这个位置，不都已经根据 mode 自动区分了么。。你还改来干嘛。。直接 `add_requires("foo", {debug = is_mode("debug")})` 不就能自动区分了么

```console
$ xmake f -m release
$ xmake package
$ xmake f -m debug
$ xmake package
$ tree build/packages/
build/packages/
├── f
│   └── foo
│       ├── macosx
│       │   └── x86_64
│       │       ├── debug
│       │       │   └── lib
│       │       │       └── libfoo.a
│       │       └── release
│       │           └── lib
│       │               └── libfoo.a
│       └── xmake.lua
```

```
$ cat build/packages/f/foo/xmake.lua 
package("foo")
    set_description("The foo package")


    add_configs("shared", {description = "Build shared library.", default = false, type = "boolean", readonly = true})

    on_load(function (package)
        package:set("installdir", path.join(os.scriptdir(), package:plat(), package:arch(), package:mode()))
    end)

    on_fetch(function (package)
        local result = {}
        local libfiledir = (package:config("shared") and package:is_plat("windows", "mingw")) and "bin" or "lib"
        result.links = "foo"
        result.linkdirs = package:installdir("lib")
        result.includedirs = package:installdir("include")
        result.libfiles = path.join(package:installdir(libfiledir), "libfoo.a")
        return result
    end)
```

>         package:set("installdir", path.join(os.scriptdir(), package:plat(), package:arch(), package:mode()))


这里原本就是根据 package:mode() 会自动切，不要做多余的事情

**Comment by huye** [comment]
我知道路径上已经有了区分，但这就只能把文件放到不同的路径中。我希望能支持把各个模式的文件放在同一个目录中。

**Comment by waruqi** [comment]
> 我知道路径上已经有了区分，但这就只能把文件放到不同的路径中。我希望能支持把各个模式的文件放在同一个目录中。

目前只能支持内部约定的打包格式，如果你要按自己的结构从，只能写个 rule ，然后重写 `on_package` 脚本去完全自己处理库结构。

**Comment by huye** [comment]
好的，那我只能先使用多目录结构的形式吧，lua 不熟而且自己改的话也不通用。
