### ISSUE TITLE
解压扩展包 utils.archive ，win/linux下正常解压，mac下没有解压也没有报错

### ISSUE THREAD

**Issue by wulei1988** [xmake-io/xmake#4954]
### Xmake 版本

2

### 操作系统版本和架构

macOS Ventura 13.6.6

### 描述问题

解压扩展包 utils.archive ，win/linux下正常解压，mac下没有解压也没有报错

### 期待的结果

utils.archive 可以在Mac系统下进行解压

### 工程配置

project_dir = os.scriptdir()
project_name = project_dir:match(".+[/\\]([%w_]+)")

csdk_root = "/Users/wulei/Documents/work/sdks/luatos-soc-2024/" --csdk根目录,可自行修改
includes(csdk_root.."csdk.lua")
description_common()

target(project_name,function()
    set_kind("static")
    set_targetdir("$(buildir)/".. project_name .. "/")
    description_csdk()
    set_warnings("error")

    -- mbedtls
    add_defines("LUAT_USE_TLS",{public = true})

    --加入代码和头文件
    add_includedirs("./inc",{public = true})
    add_files("./src/*.c",{public = true})

    add_includedirs("./components/iot_button/inc",{public = true})
    add_files("./components/iot_button/src/*.c",{public = true})
    add_includedirs("./components/led_indicator/inc",{public = true})
    add_files("./components/led_indicator/src/*.c",{public = true})

    add_defines("AP_FLASH_LOAD_SIZE=0x1b7000",{public = true})
    add_defines("AP_PKGIMG_LIMIT_SIZE=0x1b7000",{public = true})
    add_defines("FULL_OTA_SAVE_ADDR=0x235000",{public = true})

    --ymodem
    add_includedirs(luatos_root .. "/components/ymodem")
    add_files(luatos_root .. "/components/ymodem/luat_ymodem.c")

    --mqtt
    add_includedirs(luatos_root.."/components/network/libemqtt", {public = true})
    add_files(luatos_root.."/components/network/libemqtt/*.c")
    remove_files(luatos_root.."/components/network/libemqtt/luat_lib_mqtt.c")

    --http
    add_includedirs(luatos_root.."/components/network/libhttp", {public = true})
    add_includedirs(luatos_root.."/components/network/http_parser", {public = true})
    add_files(luatos_root.."/components/network/libhttp/*.c")
    remove_files(luatos_root.."/components/network/libhttp/luat_lib_http.c")
    add_files(luatos_root.."/components/network/http_parser/*.c")

    add_includedirs(luatos_root.."/components/fskv", {public = true})
    add_files(luatos_root.."/components/fskv/*.c")
    remove_files(luatos_root.."/components/fskv/luat_lib_fskv.c")

    add_files(luatos_root.."/components/cjson/*.c")
end)

### 附加信息和错误日志

[  7%]: cache compiling.debug ../../../../../sdks/luatos-soc-2024/PLAT/os/freertos/src/list.c
[  7%]: cache compiling.debug ../../../../../sdks/luatos-soc-2024/PLAT/os/freertos/src/heap_4.c
[  7%]: cache compiling.debug ../../../../../sdks/luatos-soc-2024/PLAT/os/freertos/src/queue.c
[  7%]: cache compiling.debug ../../../../../sdks/luatos-soc-2024/PLAT/os/freertos/src/heap_6_psram.c
[  7%]: cache compiling.debug ../../../../../sdks/luatos-soc-2024/PLAT/os/freertos/src/tasks.c
[  7%]: cache compiling.debug ../../../../../sdks/luatos-soc-2024/PLAT/os/freertos/src/timers.c
[  7%]: cache compiling.debug ../../../../../sdks/luatos-soc-2024/PLAT/os/freertos/portable/gcc/port.c
[  7%]: cache compiling.debug ../../../../../sdks/luatos-soc-2024/PLAT/os/freertos/portable/mem/tlsf/tlsf.c
[  7%]: cache compiling.debug ../../../../../sdks/luatos-soc-2024/PLAT/os/freertos/src/event_groups.c
[  7%]: cache compiling.debug ../../../../../sdks/luatos-soc-2024/PLAT/os/freertos/src/heap_6.c
[  7%]: cache compiling.debug ../../../../../sdks/luatos-soc-2024/PLAT/os/freertos/CMSIS/ap/src/cmsis_os2.c
[  7%]: cache compiling.debug ../../../../../sdks/luatos-soc-2024/PLAT/os/freertos/CMSIS/ap/src/os_systick.c
[  7%]: cache compiling.debug ../../../../../sdks/luatos-soc-2024/PLAT/os/freertos/CMSIS/ap/src/os_callback_hook.c
[  7%]: cache compiling.debug ../../../../../sdks/luatos-soc-2024/PLAT/os/freertos/CMSIS/common/src/mm_debug.c
error: ../../../../../sdks/luatos-soc-2024/PLAT/os/freertos/src/list.c:30:10: fatal error: sctdef.h: No such file or directory
   30 | #include "sctdef.h"
      |          ^~~~~~~~~~
compilation terminated.
  > in ../../../../../sdks/luatos-soc-2024/PLAT/os/freertos/src/list.c
wulei@wlmac RK209 %

**Comment by waruqi** [comment]
贴的 xmake.lua 和 build logs 跟 utils.archive 有啥关系？没看出来

**Comment by wulei1988** [comment]
![WechatIMG744](https://github.com/xmake-io/xmake/assets/3634495/42124fa8-794f-49a4-8db7-8317366232f9)
![WechatIMG451](https://github.com/xmake-io/xmake/assets/3634495/9c4e0b68-ca5a-4edd-8549-50c516472c5b)

xmake.lua编译前会进行判断是否存在相关目录，不存在就会解压，实际上并未解压，目录下只有压缩包，没有解压出来源码目录所以编译也就失败了

**Comment by waruqi** [comment]
不要用 7z 。。xmake 的 utils.archive 仅仅只是探测系统已有的 tar/gz/unzip/7z 等压缩工具解压的。。windows 上 xmake 安装包内置了 7z ，所以可以解压， linux 下如果你装了 7z 就能解压，没装就解压不了。。mac 上默认是没装 7z 的。。除非你自己装上

所以 7z 格式不太好跨平台，像 xmake-repo 仓库的包，通常都是 tar.gz 或者 zip 的。。所以全平台基本都能解压。。我都不会去用 .7z 压缩。。

**Comment by waruqi** [comment]
提示加了 https://github.com/xmake-io/xmake/pull/4956

试下

**Comment by wulei1988** [comment]
macOS 解压.7z 需要安装什么工具？ 我安装了p7zip还是不行
7-Zip [64] 17.05 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.05 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,12 CPUs x64)

**Comment by waruqi** [comment]
确认 7z 执行是否存在，然后 `xmake f -c` 清下当前缓存

还不行，就是试下这个 patch https://github.com/xmake-io/xmake/pull/4956

看下报错
