### ISSUE TITLE
Windows 下加密磁盘环境，gcc/build cache 预编译报错

### ISSUE THREAD

**Issue by Dozingfiretruck** [xmake-io/xmake#4958]
### Xmake 版本

2.8.9

### 操作系统版本和架构

win10

### 描述问题

终端(powershell/cmd)编译正常，vscode插件编译报错  unkown errors

### 期待的结果

正常编译

### 工程配置

https://gitee.com/openLuat/luatos-soc-2024

### 附加信息和错误日志

![bb632a7a-b546-464a-af17-1ec1329e9d3d](https://github.com/xmake-io/xmake/assets/24759100/7428e99d-5b04-48b5-8f8c-d3089985001e)

**Comment by waruqi** [comment]
插件就是调用 xmake 命令，先确认终端下 直接执行 xmake 命令是否ok，然后给份 -vD logs

**Comment by Dozingfiretruck** [comment]
> 插件就是调用 xmake 命令，先确认终端下 直接执行 xmake 命令是否ok，然后给份 -vD logs



> 插件就是调用 xmake 命令，先确认终端下 直接执行 xmake 命令是否ok，然后给份 -vD logs

终端上也出现了，看来不是vscode的问题，但是报错是统一的，都是 cannot make xxhash128 for xxx

![image](https://github.com/xmake-io/xmake/assets/24759100/91af3703-6f3d-46f3-988e-ec8bf4bde126)

**Comment by waruqi** [comment]
> > 插件就是调用 xmake 命令，先确认终端下 直接执行 xmake 命令是否ok，然后给份 -vD logs
> 
> > 插件就是调用 xmake 命令，先确认终端下 直接执行 xmake 命令是否ok，然后给份 -vD logs
> 
> 终端上也出现了，看来不是vscode的问题，但是报错是统一的，都是 cannot make xxhash128 for xxx
> 
> ![image](https://private-user-images.githubusercontent.com/24759100/321069223-91af3703-6f3d-46f3-988e-ec8bf4bde126.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTgxMDksIm5iZiI6MTcxMjcxNzgwOSwicGF0aCI6Ii8yNDc1OTEwMC8zMjEwNjkyMjMtOTFhZjM3MDMtNmYzZC00NmYzLTk4OGUtZWM4YmY0YmRlMTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAyNTY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjOGRiYzYxODU5YmRlMDY2MTVlMzdlMmNhYmY2M2U3OWIwMzVmOWJkODVmM2YyZjdkNmM5M2MzYTc1MDNlNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sRxQlUEmUcA-SFvabsGl50LAvUw3bQ8BDak-kRluTXc)

截图不是编译过了么。。刚说了，如果出错，给 -vD logs

**Comment by Dozingfiretruck** [comment]
> > > 插件就是调用 xmake 命令，先确认终端下 直接执行 xmake 命令是否ok，然后给份 -vD logs
> > 
> > 
> > > 插件就是调用 xmake 命令，先确认终端下 直接执行 xmake 命令是否ok，然后给份 -vD logs
> > 
> > 
> > 终端上也出现了，看来不是vscode的问题，但是报错是统一的，都是 cannot make xxhash128 for xxx
> > ![image](https://private-user-images.githubusercontent.com/24759100/321069223-91af3703-6f3d-46f3-988e-ec8bf4bde126.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTgxMDksIm5iZiI6MTcxMjcxNzgwOSwicGF0aCI6Ii8yNDc1OTEwMC8zMjEwNjkyMjMtOTFhZjM3MDMtNmYzZC00NmYzLTk4OGUtZWM4YmY0YmRlMTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAyNTY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjOGRiYzYxODU5YmRlMDY2MTVlMzdlMmNhYmY2M2U3OWIwMzVmOWJkODVmM2YyZjdkNmM5M2MzYTc1MDNlNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sRxQlUEmUcA-SFvabsGl50LAvUw3bQ8BDak-kRluTXc)
> 
> 截图不是编译过了么。。刚说了，如果出错，给 -vD logs

没有成功 
![fdb62f23-bfe1-407c-aad0-21a5e3277b54](https://github.com/xmake-io/xmake/assets/24759100/5d109f22-2337-4feb-a7bf-0256c9adc9ee)

**Comment by waruqi** [comment]
> > > > 插件就是调用 xmake 命令，先确认终端下 直接执行 xmake 命令是否ok，然后给份 -vD logs
> > > 
> > > 
> > > > 插件就是调用 xmake 命令，先确认终端下 直接执行 xmake 命令是否ok，然后给份 -vD logs
> > > 
> > > 
> > > 终端上也出现了，看来不是vscode的问题，但是报错是统一的，都是 cannot make xxhash128 for xxx
> > > ![image](https://private-user-images.githubusercontent.com/24759100/321069223-91af3703-6f3d-46f3-988e-ec8bf4bde126.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTgxMDksIm5iZiI6MTcxMjcxNzgwOSwicGF0aCI6Ii8yNDc1OTEwMC8zMjEwNjkyMjMtOTFhZjM3MDMtNmYzZC00NmYzLTk4OGUtZWM4YmY0YmRlMTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAyNTY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjOGRiYzYxODU5YmRlMDY2MTVlMzdlMmNhYmY2M2U3OWIwMzVmOWJkODVmM2YyZjdkNmM5M2MzYTc1MDNlNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sRxQlUEmUcA-SFvabsGl50LAvUw3bQ8BDak-kRluTXc)
> > 
> > 
> > 截图不是编译过了么。。刚说了，如果出错，给 -vD logs
> 
> 没有成功 ![fdb62f23-bfe1-407c-aad0-21a5e3277b54](https://private-user-images.githubusercontent.com/24759100/321073196-5d109f22-2337-4feb-a7bf-0256c9adc9ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTg4NDEsIm5iZiI6MTcxMjcxODU0MSwicGF0aCI6Ii8yNDc1OTEwMC8zMjEwNzMxOTYtNWQxMDlmMjItMjMzNy00ZmViLWE3YmYtMDI1NmM5YWRjOWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAzMDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMjkwMzExMjJkNWUxMTg3N2QyMmIxYWViN2QwZTYxODhlMmQ0NDdhMjA5MGJkNTgzNDYyODk1NGQyMDU0MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vca8rl9qLzxEZIIVGmb_vbTylv19Dt5eqMXeggFUegs)

我要看出错时候的 -vD error logs 。。你给的 error 还是 `xmake` 没带 -vD 的。。要个 error logs 也太难嘞。哎。

**Comment by Dozingfiretruck** [comment]
> > > > > 插件就是调用 xmake 命令，先确认终端下 直接执行 xmake 命令是否ok，然后给份 -vD logs
> > > > 
> > > > 
> > > > > 插件就是调用 xmake 命令，先确认终端下 直接执行 xmake 命令是否ok，然后给份 -vD logs
> > > > 
> > > > 
> > > > 终端上也出现了，看来不是vscode的问题，但是报错是统一的，都是 cannot make xxhash128 for xxx
> > > > ![image](https://private-user-images.githubusercontent.com/24759100/321069223-91af3703-6f3d-46f3-988e-ec8bf4bde126.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTgxMDksIm5iZiI6MTcxMjcxNzgwOSwicGF0aCI6Ii8yNDc1OTEwMC8zMjEwNjkyMjMtOTFhZjM3MDMtNmYzZC00NmYzLTk4OGUtZWM4YmY0YmRlMTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAyNTY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjOGRiYzYxODU5YmRlMDY2MTVlMzdlMmNhYmY2M2U3OWIwMzVmOWJkODVmM2YyZjdkNmM5M2MzYTc1MDNlNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sRxQlUEmUcA-SFvabsGl50LAvUw3bQ8BDak-kRluTXc)
> > > 
> > > 
> > > 截图不是编译过了么。。刚说了，如果出错，给 -vD logs
> > 
> > 
> > 没有成功 ![fdb62f23-bfe1-407c-aad0-21a5e3277b54](https://private-user-images.githubusercontent.com/24759100/321073196-5d109f22-2337-4feb-a7bf-0256c9adc9ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTg4NDEsIm5iZiI6MTcxMjcxODU0MSwicGF0aCI6Ii8yNDc1OTEwMC8zMjEwNzMxOTYtNWQxMDlmMjItMjMzNy00ZmViLWE3YmYtMDI1NmM5YWRjOWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAzMDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMjkwMzExMjJkNWUxMTg3N2QyMmIxYWViN2QwZTYxODhlMmQ0NDdhMjA5MGJkNTgzNDYyODk1NGQyMDU0MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vca8rl9qLzxEZIIVGmb_vbTylv19Dt5eqMXeggFUegs)
> 
> 我要看出错时候的 -vD error logs 。。你给的 error 还是 `xmake` 没带 -vD 的。。要个 error logs 也太难嘞。哎。

以为要执行 xmake -vD logs了。。。。
![c0ad74ee-d26f-4d7c-b85b-06c91708b51e](https://github.com/xmake-io/xmake/assets/24759100/77fa637b-64eb-4bb2-8f41-77daf44161f2)

**Comment by waruqi** [comment]
> 以为要执行 xmake -vD logs了。。。。

没 error 的 logs 我要来干嘛，又不能凭空猜出问题

<img width="838" alt="image" src="https://github.com/xmake-io/xmake/assets/151335/51263791-8277-46a8-8df0-149609737b00">

确认下这个文件是否存在，能否正常读写访问。。是否存在长路径问题

然后直接测试下

```
xmake l hash.xxhash128 filepath
xmake l os.isfile filepath
```

**Comment by Dozingfiretruck** [comment]
> > 以为要执行 xmake -vD logs了。。。。
> 
> 没 error 的 logs 我要来干嘛，又不能凭空猜出问题
> 
> <img alt="image" width="838" src="https://private-user-images.githubusercontent.com/151335/321075457-51263791-8277-46a8-8df0-149609737b00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTk2NjAsIm5iZiI6MTcxMjcxOTM2MCwicGF0aCI6Ii8xNTEzMzUvMzIxMDc1NDU3LTUxMjYzNzkxLTgyNzctNDZhOC04ZGYwLTE0OTYwOTczN2IwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwMzIyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTRmYjdjMzk2ZTE4M2VjMDYzN2MyYzBhN2MxZDIxZTA3ZDRkZTcxNDQ0OTgwN2JhMmU0MjRhNTEyNGIyMjBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aPElrpQxlD7ZC77xSsY1h2VJJJyt1yJgpJwYNSv9n-k">
> 确认下这个文件是否存在，能否正常读写访问。。是否存在长路径问题
> 
> 然后直接测试下
> 
> ```
> xmake l hash.xxhash128 filepath
> xmake l os.isfile filepath
> ```

看了下.objs下的文件不存在，源码文件是正常的，可以正常读写访问

**Comment by waruqi** [comment]
给个完整可复现的工程

**Comment by Dozingfiretruck** [comment]
> 给个完整可复现的工程

客户的工程，环境加密，给不了，我这别的工程也都复现不了，还在沟通

**Comment by waruqi** [comment]
那就把 ccache 关了，`set_policy("build.ccache", false)` 或者 `xmake f ccache=n`

**Comment by Dozingfiretruck** [comment]
> 那就把 ccache 关了，`set_policy("build.ccache", false)` 或者 `xmake f ccache=n`

关掉他那边可以正常编译了

**Comment by waruqi** [comment]
> > 给个完整可复现的工程
> 
> 客户的工程，环境加密，给不了我们，我这别的工程也都复现不了，还在沟通

这种也可能是磁盘加密 导致某些情况下 预处理器没正常生成文件导致，但具体什么原因，除非有环境能复现，不然也不好定位。。

**Comment by Dozingfiretruck** [comment]
> > > 给个完整可复现的工程
> > 
> > 
> > 客户的工程，环境加密，给不了我们，我这别的工程也都复现不了，还在沟通
> 
> 这种也可能是磁盘加密 导致某些情况下 预处理器没正常生成文件导致，但具体什么原因，除非有环境能复现，不然也不好定位。。

这环境不大好搞，现在只能避开，我先关闭了
