### ISSUE TITLE
本地编译成功，但 GitHub action 失败

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#4965]
### Xmake 版本

2.8.9+master.22889863c

### 操作系统版本和架构

windows-2019, windows-2022

### 描述问题

原项目近期在未修改代码和编译配置的情况下，github action 中 windows 平台突然编译失败。但本地 windows 编译正常，请差两者的build版本不一样
github action 版本及报错：
<img width="625" alt="8DBA3E8FBA33D4734D8E7186F17EA1FC" src="https://github.com/xmake-io/xmake/assets/1145161/7de832a0-b989-4b4d-935f-acc2dca57f37">
<img width="679" alt="B7FDD2A9288802C41224447A638F47C2" src="https://github.com/xmake-io/xmake/assets/1145161/3b8c2075-7d42-49a1-a602-d2c709f1fc54">

本地 xmake 版本：
<img width="499" alt="F09824ADC76DBC2F80D313190C1AFE57" src="https://github.com/xmake-io/xmake/assets/1145161/6b74e7e6-89b5-43df-805e-f70af00fed85">

### 期待的结果

github action 上编译恢复正常

### 工程配置

项目地址：https://github.com/fasiondog/hikyuu

### 附加信息和错误日志

<img width="679" alt="B7FDD2A9288802C41224447A638F47C2" src="https://github.com/xmake-io/xmake/assets/1145161/7ff6bd28-c36a-4f4a-a640-7fb173bee715">

**Comment by fasiondog** [comment]
https://github.com/fasiondog/hikyuu/actions/runs/8641770356

**Comment by fasiondog** [comment]
windows-2019 失败，windows-2022 直接在 config 阶段就被自行终止了

**Comment by waruqi** [comment]
是 ci 上 openssl3 fetch到了 ci 环境的 openssl 库，获取到了 version，但是返回了 table 而不是 string 导致。。https://github.com/xmake-io/xmake-repo/pull/3762

**Comment by waruqi** [comment]
更新下 repo 再试下

xrepo update-repo

**Comment by fasiondog** [comment]
目前会卡在一些依赖于 openssl 的包上，cmake 找不到 openssl
https://github.com/fasiondog/hikyuu/actions/runs/8651839923/job/23741336295#step:4:3904

**Comment by star-hengxing** [comment]
这个问题根本原因是，上游更新了 cpp-httplib 版本：https://github.com/xmake-io/xmake-repo/pull/3739

openssl3 是 cpp-httplib 的依赖，但 Windows ci 预装了 openssl 1.1.1w

两个解决方案：

1. 让 cmake 找到 xrepo openssl3
2. cpp-httplib 回退到 0.15 之前的版本

**Comment by fasiondog** [comment]
OK，多谢

**Comment by star-hengxing** [comment]
这个问题应该已经解决了，依赖 openssl 的库指定 `OPENSSL_ROOT_DIR` 就行
