### ISSUE TITLE
C++20 模块MSVC编译规则少一个逗号

### ISSUE THREAD

**Issue by HaroldCC** [xmake-io/xmake#4968]
### Xmake 版本

xmake v2.8.9+HEAD.cb1b65054

### 操作系统版本和架构

Windows10 19045.3803

### 描述问题

https://github.com/xmake-io/xmake/blob/22889863c89f94fd931fc8519b1ad93506d07498/xmake/rules/c%2B%2B/modules/modules_support/msvc/builder.lua#L382

provide 少一个逗号

### 期待的结果

添加逗号

### 工程配置

none 

### 附加信息和错误日志

none

**Comment by waruqi** [comment]
修了，这种直接提个 pr 过来就行了。
