### ISSUE TITLE
设置环境变量XMAKE_LOG, 在after_build中调用自定义命令, 命令的输出应该也导入到日志文件

### ISSUE THREAD

**Issue by wendal** [xmake-io/xmake#4970]
### Is your feature request related to a problem? Please describe.

1. 设置环境变量XMAKE_LOG=build.log
2. 执行常规xmake编译
3. 执行完毕后, build.log存在, 但自定义命令(os.exec)的输出内容, 没有出现在build.log里

### Describe the solution you'd like

支持自定义命令的输出内容也写入到日志文件

**Comment by waruqi** [comment]
支持不了，只能存 lua 层 log ，获取了 os.execv输出，只能走内部重定向，但是重定向了，终端就不回显了，而且也不建议这么搞，这个 log 通常也不是给用户用的，是这边开发和vscode插件等内部特殊用途使用的。。对于用户不会考虑做各种对这个  log file的支持

**Comment by wendal** [comment]
ok
