### ISSUE TITLE
Windows 上无法使用 QT 开发。

### ISSUE THREAD

**Issue by chenglong-xie** [xmake-io/xmake#4978]
### Xmake 版本

2.8.9

### 操作系统版本和架构

Windows 11 version 22621.3447

### 描述问题

无法开发 QT 程序。编译时提示：

```text
error: main.cpp.obj : error LNK2001: 无法解析的外部符号 "public: virtual struct QMetaObject const * __cdecl Test::metaObject(void)const " (?metaObject@Test@@UEBAPEBUQMetaObject@@XZ)
main.cpp.obj : error LNK2001: 无法解析的外部符号 "public: virtual void * __cdecl Test::qt_metacast(char const *)" (?qt_metacast@Test@@UEAAPEAXPEBD@Z)
main.cpp.obj : error LNK2001: 无法解析的外部符号 "public: virtual int __cdecl Test::qt_metacall(enum QMetaObject::Call,int,void * *)" (?qt_metacall@Test@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z)    
build\windows\x64\release\QtConsole.exe : fatal error LNK1120: 3 个无法解析的外部命令
```

### 期待的结果

正确编译运行

### 工程配置

```shell
 xmake create -P . -t qt.console --yes
xmake f --qt=C:\Qt\Qt5.14.2\5.14.2\msvc2017_64
xmake
```

代码文件：

Test.h

```cpp
#include <QObject>

class Test : public QObject
{
    Q_OBJECT

public:
    Test() = default;
    ~Test() = default;
};
```

main.cpp

```cpp
#include <QCoreApplication>
#include "Test.h"

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    Test test;

    printf("hello xmake\n");
    return a.exec();
}
```

### 附加信息和错误日志

[ 75%]: linking.release QtConsole.exe
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\VC\\Tools\\MSVC\\14.40.33721\\bin\\HostX64\\x64\\link.exe" -nologo -dynamicbase -nxcompat -machine:x64 -libpath:C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\lib /opt:ref /opt:icf Qt5Core.lib qtfreetype.lib qtlibpng.lib qtmain.lib ws2_32.lib gdi32.lib ole32.lib advapi32.lib shell32.lib user32.lib opengl32.lib imm32.lib winmm.lib iphlpapi.lib -out:build\windows\x64\release\QtConsole.exe build\.objs\QtConsole\windows\x64\release\src\main.cpp.obj
error: @programdir\core\main.lua:329: @programdir\actions\build\main.lua:148: @programdir\modules\async\runjobs.lua:338: @programdir\actions\build\kinds\binary.lua:74: @programdir\modules\core\tools\link.lua:175: main.cpp.obj : error LNK2001: 无法解析的外部符号 "public: virtual struct QMetaObject const * __cdecl Test::metaObject(void)const " (?metaObject@Test@@UEBAPEBUQMetaObject@@XZ) 
main.cpp.obj : error LNK2001: 无法解析的外部符号 "public: virtual void * __cdecl Test::qt_metacast(char const *)" (?qt_metacast@Test@@UEAAPEAXPEBD@Z)
main.cpp.obj : error LNK2001: 无法解析的外部符号 "public: virtual int __cdecl Test::qt_metacall(enum QMetaObject::Call,int,void * *)" (?qt_metacall@Test@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z)    
build\windows\x64\release\QtConsole.exe : fatal error LNK1120: 3 个无法解析的外部命令

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:957]:
    [@programdir\modules\core\tools\link.lua:175]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [@programdir\modules\core\tools\link.lua:150]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:275]:
    [@programdir\core\tool\linker.lua:221]: in function 'link'
    [@programdir\actions\build\kinds\binary.lua:74]: in function 'callback'
    [@programdir\modules\core\project\depend.lua:217]: in function 'on_changed'
    [@programdir\actions\build\kinds\binary.lua:55]: in function '_do_link_target'
    [@programdir\actions\build\kinds\binary.lua:105]:
    [@programdir\actions\build\kinds\binary.lua:132]: in function '_link_target'
    [@programdir\actions\build\kinds\binary.lua:160]: in function 'jobfunc'
    [@programdir\modules\async\runjobs.lua:256]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:275]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [@programdir\modules\async\runjobs.lua:238]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:406]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:957: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:329: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:406: in function <@programdir\core\base\scheduler.lua:399>

**Comment by star-hengxing** [comment]
add_files("*.h")
