### ISSUE TITLE
`xmake run`/`xmake test` failing to execute targets in github actions (CI)

### ISSUE THREAD

**Issue by SFGrenade** [xmake-io/xmake#4980]
### Xmake Version

2.8.9

### Operating System Version and Architecture

Windows Server 2022 10.0.20348

### Describe Bug

When running a test target in github ci, it fails to execute but doesn't show any meaningful error.

### Expected Behavior

It runs fine

### Project Configuration

https://github.com/SFGrenade/MinXmakeProtobufExample/actions/runs/8694739231/job/23844283776#step:16:10

### Additional Information and Error Logs

logs: https://github.com/SFGrenade/MinXmakeProtobufExample/actions/runs/8694739231/job/23844283776#step:16:10 and other

**Comment by waruqi** [comment]
> execv(D:\a\MinXmakeProtobufExample\MinXmakeProtobufExample\build\windows\x64\release\MinExample.exe ) failed(-1073741511)

exit code: -1073741511

maybe some dll are missing when running MinExample.exe 

xmake cannot get more error info.

**Comment by SFGrenade** [comment]
> > execv(D:\a\MinXmakeProtobufExample\MinXmakeProtobufExample\build\windows\x64\release\MinExample.exe ) failed(-1073741511)
> 
> exit code: -1073741511
> 
> maybe some dll are missing or other some errors when running MinExample.exe 
> 
> xmake cannot get more error info.

possibly, but that would meant thaz directly executing the program also would crash, which it doesnt.

**Comment by waruqi** [comment]
> > exit code: -1073741511
> > maybe some dll are missing or other some errors when running MinExample.exe
> > xmake cannot get more error info.
> 
> possibly, but that would meant that directly executing the program also would crash, which it doesnt, as seen in the linked workflow.

MinExample has crashed.

**Comment by SFGrenade** [comment]
> > > exit code: -1073741511
> > > maybe some dll are missing or other some errors when running MinExample.exe
> > > xmake cannot get more error info.
> > 
> > possibly, but that would meant that directly executing the program also would crash, which it doesnt, as seen in the linked workflow.
> 
> MinExample has crashed.

only through xmake run.
![Screenshot_20240416-161338-349.png](https://github.com/xmake-io/xmake/assets/25555417/974da77c-b5b0-429d-8182-c9c4a38a1679)

**Comment by waruqi** [comment]
> run: 'cd dest/bin/ && MinExample.exe'

try running MinExample.exe in build directory directly. do not use `xmake install`

maybe some package bin path envs are missing when call `xmake run`

**Comment by SFGrenade** [comment]
https://github.com/SFGrenade/MinXmakeProtobufExample/actions/runs/8708152914/
of course directly in the build directly, in this case, `libprotobuf.dll` is missing there (for the shared kind windows workflows). oddly enough, only the static release mode windows workflows complete the steps and not the other static mode windows workflows.

**Comment by SFGrenade** [comment]
so while testing i just saw that locally xmake adds: `C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\Performance Tools` to path, which i don't see in the CI list of path, though idk what important DLLs there are there

**Comment by waruqi** [comment]
maybe PATH has been override when call `os.execv()`

try this patch.

https://github.com/xmake-io/xmake/pull/4986

**Comment by SFGrenade** [comment]
gets 404 error on install

**Comment by SFGrenade** [comment]
looking at the install action, it doesn't support branches other than dev & master for windows runners

**Comment by waruqi** [comment]
> looking at the install action, it doesn't support branches other than dev & master for windows runners

see https://github.com/waruqi/MinXmakeProtobufExample/blob/34248bde0b54eb68fbf5a368a228d59e5d1609dc/.github/workflows/build.yaml#L65

It works now.

https://github.com/waruqi/MinXmakeProtobufExample/actions/runs/8724519005/job/23935286436

**Comment by SFGrenade** [comment]
https://github.com/SFGrenade/MinXmakeProtobufExample/actions/runs/8724763810/job/23936103174#step:14:10
i see that while the lib folders are there, the bin folders (with the DLLs) are missing

**Comment by waruqi** [comment]
Does it work now?

**Comment by SFGrenade** [comment]
> Does it work now?

it does work with also with zmqpb, yes!
many thanks!
