### ISSUE TITLE
xmake run不能执行目标程序

### ISSUE THREAD

**Issue by dijunkun** [xmake-io/xmake#4993]
### Xmake 版本

2.8.9

### 操作系统版本和架构

Windows 10 专业版 22H2

### 描述问题

使用xmake run以及xmake run -d运行目标可执行程序时无任何打印及窗口输出，并立即执行结束。通过xmake VSCode插件debug按钮可以正常进行debug。可执行程序可以手动打开，并正常运行。

### 期待的结果

xmake run正确运行目标程序。

### 工程配置

target("remote_desk")
    set_kind("binary")
    add_deps("log", "common", "screen_capturer", "device_controller", "projectx")
    add_files("src/gui/main.cpp")

### 附加信息和错误日志

xmake r -vD remote_desk无输出。

**Comment by waruqi** [comment]
提供可复现的最小 example

**Comment by dijunkun** [comment]
> 提供可复现的最小 example

工程有些大，不太好提供最小可复现用例。目前定位到的现象是一旦在add_deps中添加“projectx”模块xmake run就会失效。

**Comment by waruqi** [comment]
没法复现，这边也不好调试。。你可以自己调下源码 https://github.com/xmake-io/xmake/blob/master/xmake/actions/run/main.lua

**Comment by waruqi** [comment]
一般是你的 target 程序执行跪了，一种可能是依赖的某个 dll 没加载到
