### ISSUE TITLE
MSVC版本号缓存导致无法识别最新安装的MSVC工具链

### ISSUE THREAD

**Issue by Xiaohedantou** [xmake-io/xmake#4995]
### Xmake 版本

v2.8.9+master.0ec4f8b72

### 操作系统版本和架构

windows

### 描述问题

文件xmake\modules\detect\sdks\find_vstudio.lua的451行开始的代码，会获取MSVC工具链的历史版本号，但是，如果安装了新的MSVC工具链版本而把旧版本删除了（通过Visual Studio Installer），那么使用这个缓存，在查找MSVC的时候，还是会找旧版本，结果就是toolchain not found

### 期待的结果

可以考虑一下用户频繁更新MSVC版本的需求？因为需要更新以尝试新的语法特性

### 工程配置

与工程无关

### 附加信息和错误日志

tool chain not found

**Comment by star-hengxing** [comment]
需要手动清除缓存

```lua
xmake g -c
xmake f -c
```
