### ISSUE TITLE
交叉编译链接选项报警告

### ISSUE THREAD

**Issue by ccc0818** [xmake-io/xmake#5000]
### Xmake Version

2.8.9

### Operating System Version and Architecture

mac OS 14 sonoma

### Describe Bug

![image](https://github.com/xmake-io/xmake/assets/56196628/e79a72df-4567-4cdb-b061-375ea1aaac64)

### Expected Behavior

不要显示警告

### Project Configuration

    add_ldflags(
        "-mcpu=cortex-m3 -mthumb",
        "-specs=nosys.specs",
        "-specs=nano.specs",
        "-T./src/STM32F103VETx_FLASH.ld",
        "-lc -lm -lnosys",
        "-Wl,--gc-sections",
        "-Wl,--no-warn-rwx-segments",
        -- "-Wl,-Map=./output.map",
        {force = true}
    )

The information of project: 
    plat: cross
    arch: cortex-m3
    mode: debug
    buildir: build
    configdir: /Users/cc/work/projects/lmds/.xmake/macosx/arm64
    projectdir: /Users/cc/work/projects/lmds
    projectfile: /Users/cc/work/projects/lmds/xmake.lua

### Additional Information and Error Logs

![image](https://github.com/xmake-io/xmake/assets/56196628/b5319333-0d67-4591-85b2-d3555a723e34)

**Comment by waruqi** [comment]
再试下，应该可以了，`xmake update dev`

**Comment by ccc0818** [comment]
￼

it seems to be working normally now， thx
