### ISSUE TITLE
policy("package.install_always") does not install always with `xmake f -c`

### ISSUE THREAD

**Issue by bitonality** [xmake-io/xmake#5008]
### Xmake Version

2.8.9

### Operating System Version and Architecture

Ubuntu 22.04

### Describe Bug

My understanding is that package installation logic will run whenever the config is cleaned via `xmake f -c` when a package has the `package.install_always` policy set to `true`.

However, I think this logic check is missing something like `or (package:policy("package.install_always") == true`.
https://github.com/xmake-io/xmake/blob/c1037f5b93be15765bceb88e23e0241f13ae0e33/xmake/modules/private/action/require/impl/actions/install.lua#L383-L388

### Expected Behavior

When `xmake f -c` is run, package installation logic will run when the package has the `package.install_always` policy set as true.

### Project Configuration

```lua
add_requires("my_test_package")

target("test")
    add_packages("my_test_package")

package("my_test_package")
    set_policy("package.install_always", true)
    on_install(function(target)
        print("My installation logic is running")
    end)
```

### Additional Information and Error Logs

# First Run (package not installed)
```bash
bitonality@DESKTOP-STUDIO:~/xmake_test$ xmake f -c
checking for platform ... linux
checking for architecture ... x86_64
note: install or modify (m) these packages (pass -y to skip confirm)?
  -> my_test_package latest
please input: y (y/n/m)
y
My installation logic is running
  => install my_test_package latest .. ok
```

# Second Run
```bash
bitonality@DESKTOP-STUDIO:~/xmake_test$ xmake f -c
checking for platform ... linux
checking for architecture ... x86_64
note: install or modify (m) these packages (pass -y to skip confirm)?
  -> my_test_package latest
please input: y (y/n/m)
y
  => install my_test_package latest .. ok
```

**Comment by waruqi** [comment]
try it again. `xmake update -s dev`
