### ISSUE TITLE
set_fpmodel()无法覆盖set_optimize()中关于浮点模型的设置

### ISSUE THREAD

**Issue by huarkiou** [xmake-io/xmake#5012]
### Xmake 版本

v2.9.1

### 操作系统版本和架构

Windows 11 23H2 x64

### 描述问题

当使用以下内容时，在MSVC上编译传给cl.exe的命令同时包含```-fp:precise -O2 -fp:fast```，导致优化级别中关于fpmodels的设定覆盖了set_fpmodels的设定。
```lua
set_optimize("fastest")
set_fpmodels("precise")
```

如下图
![image](https://github.com/xmake-io/xmake/assets/46279300/44bf4e43-d3f0-456c-adf0-c1b398669c34)

### 期待的结果

理论上应该是```-O2 -fp:precise ```

Microsoft的文档上有关于这个设定导致浮点计算的不一致的说明
https://learn.microsoft.com/zh-cn/cpp/build/reference/fp-specify-floating-point-behavior?view=msvc-170
![image](https://github.com/xmake-io/xmake/assets/46279300/163e65d7-939b-41fe-9b85-aa6691a9a7a5)

### 工程配置

```
set_optimize("fastest")
set_fpmodels("precise")
```

### 附加信息和错误日志

$ xmake -vD
[ 67%]: compiling.release tools\StreamlineTraceNozzle\src\main.cpp
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\cl.exe" -c -nologo -W3 -fp:precise -O2 -fp:fast -std:c++20 -Ihndp\src /EHsc /utf-8 -external:W0 -external:IC:\Users\huarkiou\AppData\Local\.xmake\packages\a\argparse\3.0\476a413f0a1d44349a761bfe5eb294dd\include -external:W0 -external:IC:\Users\huarkiou\AppData\Local\.xmake\packages\t\toml++\v3.4.0\50f990c95ad947fbaa66face51e43264\include -GL -DNDEBUG -Fobuild\.objs\StreamlineTraceNozzle\windows\x64\release\tools\StreamlineTraceNozzle\src\main.cpp.obj tools\StreamlineTraceNozzle\src\main.cpp
[ 71%]: compiling.release tools\StreamlineTraceNozzle\src\streamline_trace.cpp
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\cl.exe" -c -nologo -W3 -fp:precise -O2 -fp:fast -std:c++20 -Ihndp\src /EHsc /utf-8 -external:W0 -external:IC:\Users\huarkiou\AppData\Local\.xmake\packages\a\argparse\3.0\476a413f0a1d44349a761bfe5eb294dd\include -external:W0 -external:IC:\Users\huarkiou\AppData\Local\.xmake\packages\t\toml++\v3.4.0\50f990c95ad947fbaa66face51e43264\include -GL -DNDEBUG -Fobuild\.objs\StreamlineTraceNozzle\windows\x64\release\tools\StreamlineTraceNozzle\src\streamline_trace.cpp.obj tools\StreamlineTraceNozzle\src\streamline_trace.cpp
cl: 命令行 warning D9025 :正在重写“/fp:precise”(用“/fp:fast”)
cl: 命令行 warning D9025 :正在重写“/fp:precise”(用“/fp:fast”)
[ 96%]: linking.release StreamlineTraceNozzle.exe
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\link.exe" -nologo -dynamicbase -nxcompat -machine:x64 -libpath:build\windows\x64\release -libpath:D:\apps\sdk\vcpkg\installed\x64-windows-static\lib /opt:ref /opt:icf hndp.lib gsl.lib gslcblas.lib -LTCG -out:build\windows\x64\release\StreamlineTraceNozzle.exe build\.objs\StreamlineTraceNozzle\windows\x64\release\tools\StreamlineTraceNozzle\src\main.cpp.obj build\.objs\StreamlineTraceNozzle\windows\x64\release\tools\StreamlineTraceNozzle\src\streamline_trace.cpp.obj

build cache stats:
cache directory: build\.build_cache
cache hit rate: 0%
cache hit: 0
cache hit total time: 0.000s
cache miss: 0
cache miss total time: 0.000s
new cached files: 0
remote cache hit: 0
remote new cached files: 0
preprocess failed: 0
compile fallback count: 0
compile total time: 0.000s

[100%]: build ok, spent 3.969s

**Comment by waruqi** [comment]
再试试，`xmake update -s dev`

**Comment by huarkiou** [comment]
正常了，感谢💕
