### ISSUE TITLE
Can not cross build with conan package 

### ISSUE THREAD

**Issue by 19317362** [xmake-io/xmake#5013]
### Xmake 版本

2.9.1

### 操作系统版本和架构

Windows

### 描述问题

I'm test cross build using xmake + conan packages.
It's a simple test project with just hello world.
When none-cross building, everything is ok.

But when cross, conan package failed.

### 期待的结果

Can build as none-cross.

### 工程配置

`
add_rules("mode.debug", "mode.release")
add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})
add_requires("zlib")

-- VCPKG package test
-- add_requires("vcpkg::fmt")

-- conan package test
add_requires("conan::asio/1.27.0", {configs ={ build = "all"}})

target("hi-cross")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("zlib")
    -- add_packages("vcpkg::fmt")
    add_packages("conan::asio/1.27.0")
`

### 附加信息和错误日志

build error
`
xmake f -y -p cross --sdk=c:\APP\arm-none-linux-gnueabihf\
checking for architecture ... arm
  => install conan::asio/1.27.0 latest .. failed

cannot install package(asio/1.27.0) for arch(arm)!
if you want to get more verbose errors, please see:
  -> D:\work\xmake\hi-cross\build\.packages\c\conan_asio\1.27.0\latest\cache\installdir.failed\logs\install.txt
error: install failed!
`

install.txt
`
cannot install package(asio/1.27.0) for arch(arm)!
`

main.cpp
`
#include <iostream>
#include <zlib.h>
#include <asio.hpp>
using namespace std;

int main(int argc, char** argv)
{

    cout << "hello xmake cross "<< __DATE__ << __TIME__ << "!" << endl;
    
    //cout << "tbox"<< endl;
    ::asio::io_context io;
    ::asio::steady_timer timer(io, ::asio::chrono::seconds(5));
    timer.async_wait([](const ::asio::error_code& ec) {
        if (!ec) {
            cout << "Hello, asio!" << endl;
        }
    });
    io.run();
    cout << "zlib"<< zlibVersion() << endl;
    return 0;
}

`

**Comment by waruqi** [comment]
please add `-vD` and provide full logs.

**Comment by 19317362** [comment]
xmake f -y -vD -p cross --sdk=c:\APP\arm-none-linux-gnueabihf\
`
D:\work\xmake\hi-cross>xmake f -y -vD -p cross --sdk=c:\APP\arm-none-linux-gnueabihf\
checking for architecture ... arm
checking for unzip ... ok
checking for git ... ok
checkinfo: cannot runv(gzip.exe --version), No such file or directory
checking for gzip ... no
checking for 7z ... C:\Program Files\xmake\winenv\bin\7z
git rev-parse HEAD
finding zlib from xmake ..
checking for xmake::zlib ... zlib v1.3.1
finding asio/1.27.0 from conan ..
checking for conan::asio/1.27.0 ... no
installing asio/1.27.0 from conan ..
checking for conan ... ok
generate D:\work\xmake\hi-cross\build\.conan\asio\1.27.0\conanfile.txt ..
error: ...dir\modules\package\manager\conan\v1\install_package.lua:187: cannot install package(asio/1.27.0) for arch(arm)!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:973]:
    [...dir\modules\package\manager\conan\v1\install_package.lua:187]:
    [...ramdir\modules\package\manager\conan\install_package.lua:43]:
    [@programdir\modules\package\manager\install_package.lua:111]:
    [@programdir\core\package\package.lua:2762]: in function 'script'
    [...dir\modules\private\action\require\impl\utils\filter.lua:114]: in function 'call'
    [...\modules\private\action\require\impl\actions\install.lua:379]:

  => install conan::asio/1.27.0 latest .. failed

...dir\modules\package\manager\conan\v1\install_package.lua:187: cannot install package(asio/1.27.0) for arch(arm)!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:973]:
    [...dir\modules\package\manager\conan\v1\install_package.lua:187]:
    [...ramdir\modules\package\manager\conan\install_package.lua:43]:
    [@programdir\modules\package\manager\install_package.lua:111]:
    [@programdir\core\package\package.lua:2762]: in function 'script'
    [...dir\modules\private\action\require\impl\utils\filter.lua:114]: in function 'call'
    [...\modules\private\action\require\impl\actions\install.lua:379]:
if you want to get more verbose errors, please see:
  -> D:\work\xmake\hi-cross\build\.packages\c\conan_asio\1.27.0\latest\cache\installdir.failed\logs\install.txt
error: @programdir\core\main.lua:329: @programdir\modules\async\runjobs.lua:322: ...\modules\private\action\require\impl\actions\install.lua:506: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:973]:
    [...\modules\private\action\require\impl\actions\install.lua:506]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:370]:
    [...modules\private\action\require\impl\install_packages.lua:487]: in function 'jobfunc'
    [@programdir\modules\async\runjobs.lua:238]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:973: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:329: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:406: in function <@programdir\core\base\scheduler.lua:399>

`

**Comment by 19317362** [comment]
D:\work\xmake\hi-cross\build\.packages\c\conan_asio\1.27.0\latest\cache\installdir.failed\logs\install.txt
```
cannot install package(asio/1.27.0) for arch(arm)!
```

**Comment by waruqi** [comment]
xmake does not currently support allowing conan to use cross-toolchain.

only support for android/ios/macos/windows/linux.

https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/manager/conan/v2/install_package.lua

we need to pass cross-toolchain info to conan.

**Comment by 19317362** [comment]
why do not use add_requires("asio")?     

I use asio just for an example to reproduce the problem, not the real case.

I've some old private module (about 10+) of embeded linux  using conan v1.x.  
Now, conan v2 is not compatable with v1.x.  So I want migerate my system from conan v1.x to xmake.

Conan V2 dose not compatable with V1 in conanfile.py of each module.  I think it's very BAD. So, I don't want to mig my modules from conanV1 to conanV2.

**Comment by waruqi** [comment]
Right, conan2 is incompatible with conan1, and xmake has only just supported conan2, and hasn't had time to add support for cross-compilation yet. If you're interested, weclome to open a pr to help me add cross-compilation support for conan2.

**Comment by 19317362** [comment]
> Right, conan2 is incompatible with conan1, and xmake has only just supported conan2, and hasn't had time to add support for cross-compilation yet. If you're interested, weclome to open a pr to help me add cross-compilation support for conan2.
> 
> https://github.com/xmake-io/xmake/blob/61498e2197e74a0d77bfad7472eefcc6ea565e45/xmake/modules/package/manager/conan/v2/install_package.lua#L226

OK, I'll have a try

**Comment by 19317362** [comment]
I decide to migrate all my packages from conan v1 to xmake.  Give up conan.

I've done 2 basic package with most my casese. 
xmake is wonderful to replace cmake + conan!
