### ISSUE TITLE
无法在ProgramFiles目录下运行

### ISSUE THREAD

**Issue by OpportunityLiu** [xmake-io/xmake#502]
https://github.com/xmake-io/xmake/blob/dev/core/src/xmake/io/open.c#L183

这里使用RW打开导致无法打开只读的脚本。

**Comment by OpportunityLiu** [comment]
但是要改tboox，直接改这里有问题

**Comment by OpportunityLiu** [comment]
https://github.com/tboox/tbox/blob/006e9743f3703dcda26000f15f7a36ff48e4dfba/src/tbox/platform/windows/file.c#L86-L89

**Comment by waruqi** [comment]
那 tbox/file里面 不管是否ro打开，share mode 都设置成 FILE_SHARE_READ | FILE_SHARE_WRITE 呢？

然后 xmake file里面，针对 'r' 设置 ro 访问？

**Comment by OpportunityLiu** [comment]
是这个意思，我之前也说过

**Comment by waruqi** [comment]
好了。。你再看看呢

**Comment by OpportunityLiu** [comment]
https://github.com/xmake-io/xmake/blob/06b91f200e5c2f918624002a8989ddda61389930/core/src/xmake/io/open.c#L183
应该 这里初始化成RO，底下 case 'a' 和 'w' 再 |= RW

**Comment by OpportunityLiu** [comment]
我来改吧

**Comment by waruqi** [comment]
那你改下吧

**Comment by OpportunityLiu** [comment]
顺便，CRT这么写的
![图片](https://user-images.githubusercontent.com/13471233/61605736-75453180-ac79-11e9-9fe3-ed678e5082f8.png)
`fopen` 用的 `_SH_DENYNO`
`fopen_s` 用的 `_SH_SECURE`

**Comment by OpportunityLiu** [comment]
行了
