### ISSUE TITLE
spirv-cross library installation failed on xmake v2.9.1 with clang-cl on Windows x64.

### ISSUE THREAD

**Issue by JX-Master** [xmake-io/xmake#5020]
### Xmake Version

2.9.1

### Operating System Version and Architecture

Windows 10, x64, clang-cl

### Describe Bug

I have created a minimum github repository that can reproduce this error: 
https://github.com/JX-Master/spirv-corss-exception-error
It seems that on xmake v2.9.1, the xmake compilation on spirv-cross, triggered by `add_requires("spirv-cross")`, will fail due to C++ exceptions being disabled by default. This error does not occur on xmake v 2.8.9 with the same xmake script and github action script.

The github action that failed with v2.9.1:

https://github.com/JX-Master/spirv-corss-exception-error/actions/runs/8857162948/job/24324307327

The same github action that succeeded with v 2.8.9:

https://github.com/JX-Master/spirv-corss-exception-error/actions/runs/8857194203/job/24324381343

This error happens only on Windows, x64 with clang-cl toolchain, it does not happen on Windows with msvc and macOS.

### Expected Behavior

The spirv-cross library should be compiled and installed correctly as before.

### Project Configuration

The minimum reproducable project only includes on simple xmake script that requires spirv-cross library, as so:
```
add_requires("spirv-cross")

target("TestSPIRVCorss")
    set_kind("binary")
    add_files("main.cpp")
    add_packages("spirv-cross")
target_end()
```
The configure process will fail due to spirv-cross not correctly installed.

### Additional Information and Error Logs

Check detailed error logs on: https://github.com/JX-Master/spirv-corss-exception-error/actions/runs/8857162948/job/24324307327

**Comment by star-hengxing** [comment]
2.8.9: cmake + msbuild + cl will automatically add `/EHsc`
https://github.com/xmake-io/xmake/commit/77a1eb757584e42371a0ace7ab8741620fb35665
2.9.1: ninja + clang-cl

spirv-cross package has option `SPIRV_CROSS_EXCEPTIONS_TO_ASSERTIONS`, so we need to improve the package
https://github.com/xmake-io/xmake-repo/pull/3885

**Comment by JX-Master** [comment]
Failed with another error (unresolved symbols):
https://github.com/JX-Master/spirv-corss-exception-error/actions/runs/8860997559/job/24332391072

also failed on LunaSDK with the same reason, so it should not be the project script that caused this problem.
https://github.com/JX-Master/LunaSDK/actions/runs/8861057453/job/24332524406

**Comment by waruqi** [comment]
> "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\link.exe" -nologo -dynamicbase -nxcompat -machine:x64 -out:build\windows\x64\debug\TestSPIRVCorss.exe 

no any spirv-cross links

> { 
  static = true,
  version = "1.3.268+0",
  sysincludedirs = { 
    "D:\a\spirv-corss-exception-error\xmake-global\.xmake\packages\s\spirv-cross\1.3.268+0\7ffdf1289dfb499681d6e89c9e9a52cc\include", 
  },
  license = "Apache-2.0", 
}

Perhaps this is because the package is being compiled in debug mode, resulting in library filenames with a `d` suffix, xmake cannot find them.


> cross/1.3.268+0/7ffdf1289dfb499681d6e89c9e9a52cc/lib/spirv-cross-utild.lib
cross/1.3.268+0/7ffdf1289dfb499681d6e89c9e9a52cc/lib/spirv-cross-cd.lib

this package only add release lib links here.

https://github.com/xmake-io/xmake-repo/blob/dd8e7ebb3fbf9dfa60c1c8f63df3bd9fc7a0dcc7/packages/s/spirv-cross/xmake.lua#L16

We can improve these links to support debug mode.

But now the other question is, why is this package compiled as Debug mode, even though you configured `xmake f -m debug`, the configuration of this package, should still be release 

```console
cmake -DSPIRV_CROSS_ENABLE_TESTS=OFF -DSPIRV_CROSS_EXCEPTIONS_TO_ASSERTIONS=OFF -DSPIRV_CROSS_SHARED=OFF -DCMAKE_INSTALL_PREFIX=D:\a\spirv-corss-exception-error\xmake-global\.xmake\packages\s\spirv-cross\1.3.268+0\7ffdf1289dfb499681d6e89c9e9a52cc -DCMAKE_INSTALL_LIBDIR:PATH=lib -G Ninja "-DCMAKE_C_COMPILER=C:/Program Files/LLVM/bin/clang-cl.exe" "-DCMAKE_CXX_COMPILER=C:/Program Files/LLVM/bin/clang-cl.exe" -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded "-DCMAKE_CXX_FLAGS_DEBUG=/MT /Zi /Ob0 /Od /RTC1" "-DCMAKE_CXX_FLAGS_RELEASE=/MT /O2 /Ob2 /DNDEBUG" "-DCMAKE_C_FLAGS_DEBUG=/MT /Zi /Ob0 /Od /RTC1" "-DCMAKE_C_FLAGS_RELEASE=/MT /O2 /Ob2 /DNDEBUG" -DCMAKE_COMPILE_PDB_OUTPUT_DIRECTORY=pdb -DCMAKE_C_FLAGS=/EHsc "-DCMAKE_CXX_FLAGS=-MT /EHsc" -DCMAKE_EXE_LINKER_FLAGS=-nodefaultlib:msvcrt.lib -DCMAKE_SHARED_LINKER_FLAGS=-nodefaultlib:msvcrt.lib -DCMAKE_POSITION_INDEPENDENT_CODE=ON C:\Users\RUNNER~1\AppData\Local\Temp\.xmake\240427.dir
```

no CMAKE_BUILD_TYPE configuration to enable debug.

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-repo/pull/3891

**Comment by JX-Master** [comment]
Succeeded by adding support for linking debug version of spirv-cross: https://github.com/JX-Master/spirv-corss-exception-error/actions/runs/8860997559/job/24345523183

The reason that causes spirv-cross to compile a debug version is still unknown.
