### ISSUE TITLE
vcpkg 在 dynamic triplet 下工作

### ISSUE THREAD

**Issue by SHIINASAMA** [xmake-io/xmake#5021]
### 你在什么场景下需要该功能？

我的项目需要在 linux 下工作，它本身基于来自我们私有的 vcpkg registry 中的包，并且只能被动态链接。

而 xmake 在 linux 向 vcpkg 传参时，默认忽略 shared = true 配置，而不能动态链接。

### 描述可能的解决方案

1. vcpkg 的 configurations.lua 中 triplet 中增加对应的 case。
2. target.linkname 支持解析 *.so 以及 *.dylib 等拓展名的链接名称。
3. env.lua 添加运行用环境变量 LD_LIBRARY_PATH 等，这需要从 vcpkg 相关中配置中获取，例如 /vcpkg_installed/x64-linux-dynamic/lib/。

### 其他信息

我尝试实现了解决方案的前两点，它能正常工作。但最后一点由于我对暂时没想到好的方法进行判断。
或者可以打印用户提醒手动设置 LD_LIBRARY_PATH？（不是一个好主意，但 xmake run 能工作。）
我是否可以就当前的代码向项目提起 [pr](https://github.com/shiinasama/xmake)？

**Comment by waruqi** [comment]
可以
