### ISSUE TITLE
Link failed with both shared and static lib on windows

### ISSUE THREAD

**Issue by 19317362** [xmake-io/xmake#5026]
### Xmake Version

2.9.1

### Operating System Version and Architecture

Windows

### Describe Bug

I'm evaluate xmake start with a basic hello project:  one exe + one shared lib + one static lib.
When build under linux with gcc, it works fine.
But when build under windows with VS2022, it can not link

I've inspect the build log. The root error is
1. build as expected: s1.lib and d1.dll is there
2. link cmd error:  link to s1.lib  d1.lib  => should be s1.lib d1.dll

### Expected Behavior

Can be build under windows with VS2022: link with s1.lib and d1.dll

### Project Configuration

```
target("s1")
    set_kind("static")
    add_files("src/s1/*.cpp")

target("d1")
    set_kind("shared")
    add_files("src/d1/*.cpp")

target("hi-cross")
    set_kind("binary")
    add_files("src/*.cpp")
    add_deps("s1")
    add_deps("d1")
```

### Additional Information and Error Logs

```
checking for the static library archiver (ar) ... link.exe
[ 58%]: archiving.release s1.lib
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\link.exe" -lib -nologo -machine:x64 /opt:ref /opt:icf -out:build\windows\x64\release\s1.lib build\.objs\s1\windows\x64\release\src\s1\s1.cpp.obj
[ 66%]: compiling.release src\d1\d1.cpp
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\cl.exe" -c -nologo -O2 -fp:fast /EHsc -DNDEBUG -Fobuild\.objs\d1\windows\x64\release\src\d1\d1.cpp.obj src\d1\d1.cpp
checking for flags (cl_external_includedir) ... ok
> cl.exe "-external:W0" "-external:IC:\Users\wps88\AppData\Local\.xmake\packages\z\zlib\v1.3.1\d676b73b676c41cdae37b37fbf6c9cbd\include" "-nologo"
[ 66%]: compiling.release src\main.cpp
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\cl.exe" -c -nologo -O2 -fp:fast /EHsc -external:W0  -Fobuild\.objs\hi-cross\windows\x64\release\src\main.cpp.obj src\main.cpp
[ 75%]: linking.release d1.dll
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\link.exe" -dll -nologo -machine:x64 /opt:ref /opt:icf -out:build\windows\x64\release\d1.dll build\.objs\d1\windows\x64\release\src\d1\d1.cpp.obj
[ 91%]: linking.release hi-cross.exe
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\link.exe" -nologo -dynamicbase -nxcompat -machine:x64  -libpath:build\windows\x64\release /opt:ref /opt:icf zlib.lib s1.lib d1.lib -out:build\windows\x64\release\hi-cross.exe build\.objs\hi-cross\windows\x64\release\src\main.cpp.obj
create ok!
compile_commands.json updated!
error: @programdir\core\main.lua:329: @programdir\actions\build\main.lua:148: @programdir\modules\async\runjobs.lua:322: @programdir\actions\build\kinds\binary.lua:53: @programdir\modules\core\tools\link.lua:175: LINK : fatal error LNK1181: cannot open input file 'd1.lib'

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:973]:
    [@programdir\modules\core\tools\link.lua:175]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [@programdir\modules\core\tools\link.lua:150]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:275]:
    [@programdir\core\tool\linker.lua:221]: in function 'link'
    [@programdir\actions\build\kinds\binary.lua:53]: in function 'callback'
    [@programdir\modules\core\project\depend.lua:217]: in function 'on_changed'
    [@programdir\actions\build\kinds\binary.lua:41]: in function '_do_link_target'
    [@programdir\actions\build\kinds\binary.lua:83]:
    [@programdir\actions\build\kinds\binary.lua:110]: in function '_link_target'
    [@programdir\actions\build\kinds\binary.lua:138]: in function 'jobfunc'
    [@programdir\modules\async\runjobs.lua:238]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:275]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [@programdir\modules\async\runjobs.lua:220]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:406]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:973: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:329: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:406: in function <@programdir\core\base\scheduler.lua:39
```

**Comment by 19317362** [comment]
I've try to find the bug in source code of xmake,  inspected the link.lua, but have no idea to fix it. I can not understand the LUA code.

**Comment by SirLynix** [comment]
This is not a bug of xmake, on Windows you need to export the symbols yourself using `__declspec(dllexport)` and `__declspec(dllimport)`

However xmake supports a rule to automatically export all symbols, check the docs for "export"

**Comment by 19317362** [comment]
> /opt:ref /opt:icf zlib.lib s1.lib d1.lib

look this log. It's not symbol-export related. The Link command is error. It' should be "s1.lib d1.dll"

**Comment by SirLynix** [comment]
MSVC linker doesn't take DLL as input, only lib file (unlike on Linux). Normally when you produce a DLL file, you also produce a .lib file that will serve as your import library. However it's not produced if MSVC find no exported symbol.

See https://stackoverflow.com/questions/7845886/linking-dll-in-visual-studio

As I said, you need to either mark your exported functions and classes with `__declspec(dllexport)` or use something as the [utils.symbols.export_all](https://xmake.io/#/manual/custom_rule?id=utilssymbolsexport_all) rule.

**Comment by waruqi** [comment]
You need to export symbols in dll. use `__declspec(dllexport)` in your code, or use [utils.symbols.export_all](https://xmake.io/#/manual/custom_rule?id=utilssymbolsexport_all) rule in xmake.lua or add `add_files("xxx.def")` export file.

If symbols are exported, msvc will generate a `.lib` file for it's dll, then xmake will call link.exe to link this `.lib` file instead of `.dll`.

.dll files cannot be linked.

**Comment by 19317362** [comment]
> You need to export symbols in dll. use `__declspec(dllexport)` in your code, or use [utils.symbols.export_all](https://xmake.io/#/manual/custom_rule?id=utilssymbolsexport_all) rule in xmake.lua or add `add_files("xxx.def")` export file.
> 
> It's not xmake bug.
> 
> If symbols are exported, msvc will generate a `.lib` file for it's dll automatically, then xmake will call link.exe to link this `.lib` file instead of `.dll`.
> 
> .dll files cannot be linked.

Thanks a lot.  
With utils.symbols.export_all, it works as expected.
