### ISSUE TITLE
centos7.4上xmake编译ltui失败

### ISSUE THREAD

**Issue by vgfree** [xmake-io/xmake#504]
### 两个问题：
1.编译ltui失败了。
2.lua 5.3.5系统已安装，xmake执行时重复安装。

### 相关信息：
root方式运行
lua 5.3.5为下载源码包，手动编译安装
xmake 版本信息：commit d50969c226d4385109b355298e93502bce25e791

### 错误信息：
[root@localhost lua-5.3.5]# make install
cd src && mkdir -p /usr/local/bin /usr/local/include /usr/local/lib /usr/local/man/man1 /usr/local/share/lua/5.3 /usr/local/lib/lua/5.3
cd src && install -p -m 0755 lua luac /usr/local/bin
cd src && install -p -m 0644 lua.h luaconf.h lualib.h lauxlib.h lua.hpp /usr/local/include
cd src && install -p -m 0644 liblua.a /usr/local/lib
cd doc && install -p -m 0644 lua.1 luac.1 /usr/local/man/man1

[root@localhost ltui]# lua -v
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
[root@localhost ltui]# xmake --root -y -v -D
checking for the architecture ... x86_64
checking for the unzip ... /usr/bin/unzip
checking for the git ... /usr/bin/git
checking for the gzip ... /usr/bin/gzip
checking for the tar ... /usr/bin/tar
checking for the ping ... /usr/bin/ping
pinging for the host(gitee.com) ... 17 ms
pinging for the host(gitlab.com) ... 210 ms
checking for the nmap ... /usr/bin/nmap
pinging for the host(github.com) ... 140 ms
finding lua from xmake ..
checking for the xmake::lua ... no
finding lua from brew ..
finding ncurses from xmake ..
checking for the xmake::ncurses ... no
finding ncurses from brew ..
checking for the brew ... no
finding lua from vcpkg ..
checking for the vcpkg directory ... no
finding lua from conan ..
finding lua from pkg_config ..
finding ncurses from vcpkg ..
finding ncurses from conan ..
finding ncurses from pkg_config ..
checking for the pkg-config ... /usr/bin/pkg-config
finding lua from system ..
finding ncurses from system ..
checking for the lua ... no
checking for the ncurses ... no
pinging for the host(www.lua.org) ... 231 ms
pinging for the host(invisible-mirror.net) ... 164 ms
pinging for the host(ftp.gnu.org) ... 276 ms
pinging for the host(ftp.invisible-island.net) ... 370 ms
/usr/bin/tar -xvf lua-5.3.5.tar.gz -C source.tmp
lua-5.3.5/
lua-5.3.5/Makefile
lua-5.3.5/doc/
lua-5.3.5/doc/luac.1
lua-5.3.5/doc/manual.html
lua-5.3.5/doc/manual.css
lua-5.3.5/doc/contents.html
lua-5.3.5/doc/lua.css
lua-5.3.5/doc/osi-certified-72x60.png
lua-5.3.5/doc/logo.gif
lua-5.3.5/doc/lua.1
lua-5.3.5/doc/index.css
lua-5.3.5/doc/readme.html
lua-5.3.5/src/
lua-5.3.5/src/ldblib.c
lua-5.3.5/src/lmathlib.c
lua-5.3.5/src/loslib.c
lua-5.3.5/src/lvm.c
lua-5.3.5/src/ldo.h
lua-5.3.5/src/lua.h
lua-5.3.5/src/lgc.h
lua-5.3.5/src/ltm.h
lua-5.3.5/src/loadlib.c
lua-5.3.5/src/lmem.c
lua-5.3.5/src/lstate.h
lua-5.3.5/src/Makefile
lua-5.3.5/src/lzio.h
lua-5.3.5/src/luaconf.h
lua-5.3.5/src/lopcodes.c
lua-5.3.5/src/lua.c
lua-5.3.5/src/lundump.h
lua-5.3.5/src/lbaselib.c
lua-5.3.5/src/ltable.c
lua-5.3.5/src/ldump.c
lua-5.3.5/src/liolib.c
lua-5.3.5/src/llimits.h
lua-5.3.5/src/lfunc.h
lua-5.3.5/src/lualib.h
lua-5.3.5/src/lzio.c
lua-5.3.5/src/lctype.c
lua-5.3.5/src/lmem.h
lua-5.3.5/src/llex.h
lua-5.3.5/src/ltable.h
lua-5.3.5/src/lstring.c
lua-5.3.5/src/ldebug.h
lua-5.3.5/src/lbitlib.c
lua-5.3.5/src/lprefix.h
lua-5.3.5/src/llex.c
lua-5.3.5/src/linit.c
lua-5.3.5/src/lobject.h
lua-5.3.5/src/lapi.h
lua-5.3.5/src/ldebug.c
lua-5.3.5/src/ldo.c
lua-5.3.5/src/lvm.h
lua-5.3.5/src/lauxlib.c
lua-5.3.5/src/luac.c
lua-5.3.5/src/lctype.h
lua-5.3.5/src/lstring.h
lua-5.3.5/src/lcorolib.c
lua-5.3.5/src/lutf8lib.c
lua-5.3.5/src/lgc.c
lua-5.3.5/src/lstate.c
lua-5.3.5/src/lundump.c
lua-5.3.5/src/ltablib.c
lua-5.3.5/src/lauxlib.h
lua-5.3.5/src/ltm.c
lua-5.3.5/src/lparser.c
lua-5.3.5/src/lcode.h
lua-5.3.5/src/lobject.c
lua-5.3.5/src/lcode.c
lua-5.3.5/src/lopcodes.h
lua-5.3.5/src/lfunc.c
lua-5.3.5/src/lapi.c
lua-5.3.5/src/lparser.h
lua-5.3.5/src/lua.hpp
lua-5.3.5/src/lstrlib.c
lua-5.3.5/README
xmake f -y -c --plat=linux --arch=x86_64 --mode=release -v --diagnosis                                                           
error: open /usr/local/share/xmake/themes/default/xmake.lua failed!
error: /usr/local/share/xmake/core/base/os.lua:719: execv(xmake f -y -c --plat=linux --arch=x86_64 --mode=release -v --diagnosis) failed(255)!
stack traceback:
    [C]: in function 'error'
    [/usr/local/share/xmake/core/base/os.lua:719]: in function 'raise'
    [/usr/local/share/xmake/core/sandbox/modules/os.lua:414]:
    [/usr/local/share/xmake/core/sandbox/modules/os.lua:334]: in function 'vrunv'
    [/usr/local/share/xmake/modules/package/tools/xmake.lua:83]: in function 'install'
    [.../.xmake/repositories/xmake-repo/packages/l/lua/xmake.lua:46]: in function 'script'
    [...gramdir)/actions/require/impl/action/../utils/filter.lua:119]: in function 'call'
    [/usr/local/share/xmake/actions/require/impl/action/install.lua:177]:
    [C]: in function 'trycall'
    [/usr/local/share/xmake/core/sandbox/modules/try.lua:121]: in function 'try'
    [/usr/local/share/xmake/actions/require/impl/action/install.lua:139]: in function 'install'
    [/usr/local/share/xmake/actions/require/impl/package.lua:594]:

  => install lua 5.3.5 .. failed                                                                                                 
error: /usr/local/share/xmake/core/base/os.lua:719: /usr/local/share/xmake/core/base/os.lua:719: /usr/local/share/xmake/core/base/os.lua:719: install failed!
stack traceback:
	[C]: in function 'error'
	/usr/local/share/xmake/core/base/os.lua:719: in function 'raise'
	$(programdir)/actions/require/impl/action/install.lua:259: in function 'catch'
	$(programdir)/core/sandbox/modules/try.lua:127: in function 'try'
	$(programdir)/actions/require/impl/action/install.lua:139: in function 'install'
	$(programdir)/actions/require/impl/package.lua:594: in function <$(programdir)/actions/require/impl/package.lua:519>
[root@localhost ltui]# ls -l /usr/local/share/xmake/themes/default/xmake.lua
-rw-r--r-- 1 root root 2086 7月  22 02:02 /usr/local/share/xmake/themes/default/xmake.lua
[root@localhost ltui]#

**Comment by waruqi** [comment]
root下，内部运行xmake命令，访问open /usr/local/share/xmake/themes/default/xmake.lua 时候失败了，回头我看下。

**Comment by waruqi** [comment]
我修复了，是因为内部调用xmake没有透传`--root`导致，你可以更新到dev分支代码 再试试。

**Comment by vgfree** [comment]
测试可以啦
