### ISSUE TITLE
`xmake f` overwrite the previous config

### ISSUE THREAD

**Issue by rogtino** [xmake-io/xmake#5041]
### Xmake 版本

xmake v2.9.1+20240422

### 操作系统版本和架构

Linux art 6.8.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 28 Apr 2024 15:59:47 +0000 x86_64 GNU/Linux

### 描述问题

`xmake f -m debug` 会覆盖之前的`xmake f --debugger=gdb`
`xmake f -m debug --debugger=gdb`没有这个问题

### 期待的结果

xmake f 可以分别设置对应的config

### 工程配置

add_rules("mode.debug", "mode.release")

target("one")
set_kind("binary")
add_files("src/*.cpp")

### 附加信息和错误日志

不太确定这是不是bug

**Comment by star-hengxing** [comment]
https://github.com/xmake-io/xmake/issues/2401

**Comment by waruqi** [comment]
每次配置都是全量配置，不支持增量配置

**Comment by SirLynix** [comment]
I supported incremental configuration as a xmake plugin, for those who want it:
```shell
xmake plugin --install github:SirLynix/xmake-plugins
```
which adds a `xmake config-update` (or `xmake cu`) command:
```shell
xmake f --a=b
xmake config-update --c=d # --a=b --c=d
xmake cu --e=f # --a=b --c=d --e=f
```
