### ISSUE TITLE
Cannot install package `tobiaslocker_base64`

### ISSUE THREAD

**Issue by Chi-EEE** [xmake-io/xmake#5048]
### Xmake Version

v2.9.1

### Operating System Version and Architecture

Linux arm64-v8a

### Describe Bug

Cannot install package `tobiaslocker_base64`.

The select script is not working correctly, using "windows|!arm64" also excludes "linux|arm64-v8a".

https://github.com/xmake-io/xmake-repo/blob/dev/packages/t/tobiaslocker_base64/xmake.lua

### Expected Behavior

Installs `tobiaslocker_base64`

### Project Configuration

`xrepo install tobiaslocker_base64`

### Additional Information and Error Logs

```bash
note: the following packages are unsupported on linux/arm64-v8a:
  -> tobiaslocker_base64 2024.02.26
```

**Comment by waruqi** [comment]
It's not bug. `windows|!arm64` only will match `windows/x64` and `windows/x86`. you should add linux platform

```lua
on_install("windows|!arm64", "linux")
```

**Comment by Chi-EEE** [comment]
Using `!windows|arm64` excludes `windows|x64` and `windows|x86` which I don't think should happen since the [cello](https://github.com/xmake-io/xmake-repo/pull/3864) package succeeds with windows x64 & x86 but for the final checks in the PR, it does not check them.

**Comment by waruqi** [comment]
> Using `!windows|arm64` excludes `windows|x64` and `windows|x86` which I don't think should happen

`!windows|arm64` means  `(not windows) and arm64`, so it will excludes windows platform.
