### ISSUE TITLE
win11下编译异常

### ISSUE THREAD

**Issue by Dozingfiretruck** [xmake-io/xmake#5051]
### Xmake 版本

2.9.1

### 操作系统版本和架构

win11

### 描述问题

win10下编译正常，win11下报 ar.exe: invalid option -- @

### 期待的结果

正常编译

### 工程配置

仓库地址 ： https://gitee.com/openLuat/luatos-soc-2024

### 附加信息和错误日志

[xmake -vD记录.txt](https://github.com/xmake-io/xmake/files/15206414/xmake.-vD.txt)

**Comment by waruqi** [comment]
编译不过

```console
error: @programdir\core\main.lua:329: @programdir\actions\build\main.lua:148: @programdir\modules\async\runjobs.lua:322: @programdir\modules\private\action\build\object.lua:91: @programdir\modules\core\tools\gcc.lua:886: ..\..\interface\src\luat_mobile_ec7xx.c: In function 'luat_mobile_set_apn_auth_inf':
..\..\interface\src\luat_mobile_ec7xx.c:367:9: warning: implicit declaration of function 'psSetCGAUTH'; did you mean 'psGetCGAUTH'? [-Wimplicit-function-declaration]
  367 |  return psSetCGAUTH(PS_DIAL_REQ_HANDLER, &req);
      |         ^~~~~~~~~~~
      |         psGetCGAUTH
..\..\interface\src\luat_mobile_ec7xx.c: In function 'luat_mobile_config':
..\..\interface\src\luat_mobile_ec7xx.c:944:7: error: 'MOBILE_CONF_RESET_TO_FACTORY' undeclared (first use in this function)
  944 |  case MOBILE_CONF_RESET_TO_FACTORY:
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
..\..\interface\src\luat_mobile_ec7xx.c:944:7: note: each undeclared identifier is reported only once for each function it appears in
stack traceback:
```

**Comment by Dozingfiretruck** [comment]
> ```
> MOBILE_CONF_RESET_TO_FACTORY
> ```

luatos仓库没pull最新的

**Comment by waruqi** [comment]
还是不行

```console
error: @programdir\core\main.lua:329: @programdir\actions\build\main.lua:148: @programdir\modules\async\runjobs.lua:322: @programdir\modules\private\action\build\object.lua:91: @programdir\modules\core\tools\gcc.lua:886: ..\..\..\LuatOS\components\multimedia\luat_multimedia_audio.c: In function 'luat_audio_init':
..\..\..\LuatOS\components\multimedia\luat_multimedia_audio.c:251:39: warning: implicit declaration of function 'luat_mcu_tick64_ms' [-Wimplicit-function-declaration]
  251 |     audio_conf->last_wakeup_time_ms = luat_mcu_tick64_ms();
      |                                       ^~~~~~~~~~~~~~~~~~
..\..\..\LuatOS\components\multimedia\luat_multimedia_audio.c: In function 'luat_audio_play_get_last_error':
..\..\..\LuatOS\components\multimedia\luat_multimedia_audio.c:46:1: error: control reaches end of non-void function [-Werror=return-type]
   46 | }
```

**Comment by waruqi** [comment]
有点怪，它的 help 里面说了 支持 `@file` 但还是没去处理。这里用 `ar.exe @args.txt` 是为了绕过 win 上命令行长度的限制，你这 obj files 太多了，命令行过长。

```console
c376454\bin\../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ar.exe: invalid option -- @

  @<file>      - read options from <file>
```

**Comment by Dozingfiretruck** [comment]
> 有点怪，它的 help 里面说了 支持 `@file` 但还是没去处理。这里用 `ar.exe @args.txt` 是为了绕过 win 上命令行长度的限制，你这 obj files 太多了，命令行过长。
> 
> ```console
> c376454\bin\../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ar.exe: invalid option -- @
> 
>   @<file>      - read options from <file>
> ```

有点值得注意的是只有win11下会这样，win10下没问题

**Comment by waruqi** [comment]
那就不知道了，你可以先本地测下 为啥 win11 上 ar.exe @file 不支持

**Comment by Dozingfiretruck** [comment]
> 那就不知道了，你可以先本地测下 为啥 win11 上 ar.exe @file 不支持

看来不是win11的问题，可能是环境问题，今天有一个客户win10系统也出现了这个问题，大部分电脑都是没问题的，我这里也无法复现，但是有几个客户的环境会出现这个问题，系统是最新版本win10/win11,

**Comment by Dozingfiretruck** [comment]
> > 那就不知道了，你可以先本地测下 为啥 win11 上 ar.exe @file 不支持
> 
> 看来不是win11的问题，可能是环境问题，今天有一个客户win10系统也出现了这个问题，大部分电脑都是没问题的，我这里也无法复现，但是有几个客户的环境会出现这个问题，系统是最新版本win10/win11,没看出来环境异常

**Comment by waruqi** [comment]
是这个 patch 改出来的问题，https://github.com/xmake-io/xmake/issues/5015

gcc-ar.exe 不支持 `@file` ，但是 `ar.exe` 支持，但是之前改成了优先走 gcc-ar 了，为了支持 lto

**Comment by waruqi** [comment]
稍微改了下，应该可以了，不过目前不是完美方案，只能针对 gcc-ar 禁用 @file ，但是如果命令行过长，可能会有问题。

如果要同时兼容支持 `gcc-ar/lto` 和 `ar @file` ，不太好搞。

先试试吧。`xmake update -s dev`

**Comment by Dozingfiretruck** [comment]
> 稍微改了下，应该可以了，不过目前不是完美方案，只能针对 gcc-ar 禁用 @file ，但是如果命令行过长，可能会有问题。
> 
> 如果要同时兼容支持 `gcc-ar/lto` 和 `ar @file` ，不太好搞。
> 
> 先试试吧。`xmake update -s dev`

客户反馈可以了

**Comment by Dozingfiretruck** [comment]
还是不行，之前可以编译的项目反而无法编译了。。。

**Comment by waruqi** [comment]
> arm-none-eabi-gcc-ar 是支持 https://github.com/file 的，大部分环境下编译没有问题，我这里没有复现过

我这里是必现的，gcc-ar 似乎就是处理不了 `@file`

**Comment by Dozingfiretruck** [comment]
> > arm-none-eabi-gcc-ar 是支持 https://github.com/file 的，大部分环境下编译没有问题，我这里没有复现过
> 
> 我这里是必现的，gcc-ar 似乎就是处理不了 `@file`

你那里应该和客户的情况一样，但是大部分用户没有报这个问题，我这里也编译正常，相关工程以前也一直这么用的已经有两年了

**Comment by waruqi** [comment]
那就没办法了，目前没有更好的办法，同时兼容  `@file` 和 `lto`

1. ar 支持 `@file`, 比较稳定，但是不支持 lto
2. gcc-ar 部分机器不支持 `@file` 
3. gcc-ar 去掉 `@file` ，命令过长会失败

你可以自己想下有没有兼容办法，反正目前我这想不到更好的办法同时支持这三种 case 。。除非有办法让 `gcc-ar` 稳定支持 `@file`

**Comment by Dozingfiretruck** [comment]
ar 支持 @file, 比较稳定，但是不支持 lto？我这里一直在用lto并没有问题呀

**Comment by Dozingfiretruck** [comment]
我这里重装了2.9.1，用之前有dev编译的工程直接编译也会出现提示不支持@ 删除掉 build缓存和.xmake之后在编译就正常了，应该还是有bug的

**Comment by waruqi** [comment]
> ar 支持 @file, 比较稳定，但是不支持 lto？我这里一直在用lto并没有问题呀

看 https://github.com/xmake-io/xmake/issues/5015

或者你有办法在使用 ar 时候，也能兼容处理掉这个问题，那也可以

**Comment by Dozingfiretruck** [comment]
我可以提供我的环境给你，我们这边也有ci，都是可以编译的 https://github.com/openLuat/luatos-soc-2024/actions/runs/8905334030/job/24455883537

**Comment by waruqi** [comment]
> 我这里重装了2.9.1，用之前有dev编译的工程直接编译也会出现提示不支持@ 删除掉 build缓存和.xmake之后在编译就正常了，应该还是有bug的

不同版本间，你要清 cache ，不保证 cache 兼容的。

**Comment by waruqi** [comment]
> 我可以提供我的环境给你，我们这边也有ci，都是可以编译的 https://github.com/openLuat/luatos-soc-2024/actions/runs/8905334030/job/24455883537

你这环境可以，不代表其他人的环境也可以，而且人家用的工具链也跟你不同，但是这边只能统一处理，不可能分这么细

**Comment by Dozingfiretruck** [comment]
> > ar 支持 @file, 比较稳定，但是不支持 lto？我这里一直在用lto并没有问题呀
> 
> 看 #5015
> 
> 或者你有办法在使用 ar 时候，也能兼容处理掉这个问题，那也可以

我们用的 gcc-arm-none-eabi 10，应该和linux的交叉编译工具链还有些不同的

**Comment by Dozingfiretruck** [comment]
> > 我可以提供我的环境给你，我们这边也有ci，都是可以编译的 https://github.com/openLuat/luatos-soc-2024/actions/runs/8905334030/job/24455883537
> 
> 你这环境可以，不代表其他人的环境也可以，而且人家用的工具链也跟你不同，但是这边只能统一处理，不可能分这么细

不是啊，都是我们的sdk，工程一样 工具链一样，大部分也都能编译，这算bug吧，并没有工具链不一样

**Comment by waruqi** [comment]
> 不是啊，都是我们的sdk，工程一样 工具链一样，大部分也都能编译，这算bug吧，并没有工具链不一样

我不知道你现在说的 bug 是哪个，同一个 issues 不要混一起。


> 那就没办法了，目前没有更好的办法，同时兼容 `@file` 和 `lto`
> 
> 1. ar 支持 `@file`, 比较稳定，但是不支持 lto
> 2. gcc-ar 部分机器不支持 `@file`
> 3. gcc-ar 去掉 `@file` ，命令过长会失败
> 
> 你可以自己想下有没有兼容办法，反正目前我这想不到更好的办法同时支持这三种 case 。。除非有办法让 `gcc-ar` 稳定支持 `@file`

如果你说的是这个问题，我刚上面说的已经比较清楚了，我暂时没好的办法全部兼容。。



> > 我这里重装了2.9.1，用之前有dev编译的工程直接编译也会出现提示不支持@ 删除掉 build缓存和.xmake之后在编译就正常了，应该还是有bug的
> 
> 不同版本间，你要清 cache ，不保证 cache 兼容的。

如果你说的是这个问题，我刚也说了，这个你只要清 cache 就行了。。

> ar 支持 @file, 比较稳定，但是不支持 lto？我这里一直在用lto并没有问题呀

如果你说的是这个，我刚也说了，人家的 gcc toolchain 遇到了 lto 问题，后来才改的 gcc-ar 。。

**Comment by Dozingfiretruck** [comment]
问题现在就是小部分用户无法编译相同的sdk，报的就是@问题，但是大部分人是可以编译的，gcc-ar 部分机器不支持 @file 这句话我没理解，这是工具链的支持为什么会是机器不支持？而且我的机器环境两个都复现了，不可能是我环境来回变

另外关于lto问题，gcc工具链不是只有一个，linux 应用平台和裸机平台工具链不是一个，不能因为linux应用的工具链问题就gcc得全部相同，裸机的一般用于单片机，linux应用的一般用于A核编译linux内核和应用，本就是不同的，不应该绑定一定一样的处理，linux工具链不支持也不代表none的也不支持

**Comment by waruqi** [comment]
> 问题现在就是小部分用户无法编译相同的sdk，报的就是@问题，但是大部分人是可以编译的，gcc-ar 部分机器不支持 @file 这句话我没理解，这是工具链的支持为什么会是机器不支持？而且我的机器环境两个都复现了，不可能是我环境来回变

不是你说的，你客户那有这个问题，你这没问题么，具体为什么有时候不支持，这个要问 gcc-ar 了，反正目前我这必现 gcc-ar 处理不了 `@file`，暂时也找不到原因和解决办法。

> > > arm-none-eabi-gcc-ar 是支持 https://github.com/file 的，大部分环境下编译没有问题，我这里没有复现过
> > 
> > 
> > 我这里是必现的，gcc-ar 似乎就是处理不了 `@file`
> 
> 你那里应该和客户的情况一样，但是大部分用户没有报这个问题，我这里也编译正常，相关工程以前也一直这么用的已经有两年了



> 
> 另外关于lto问题，gcc工具链不是只有一个，linux 应用平台和裸机平台工具链不是一个，不能因为linux应用的工具链问题就gcc得全部相同，裸机的一般用于单片机，linux应用的一般用于A核编译linux内核和应用，本就是不同的，不应该绑定一定一样的处理，linux工具链不支持也不代表none的也不支持

所以，我刚说了，你那工具链 lto 可以，不代表其他用户那的 toolchain 里面 lto 也可以，但是 xmake 里面不可能分这么细，还去 none, linux 啥各种 gcc cross toolchain  版本，挨个分类兼容，只能统一处理，要么用 ar.exe 要么 用 gcc-ar.exe 。。

但不管用哪种，要么你这有问题，要么其他用户那有问题。。我也说了，目前我也没好的办法，全部兼容每个用户 toolchain 的各种case 。。

就算我现在改回去 重新用了 ar.exe ，回头之前那个用户又 issues 过来了。。

**Comment by waruqi** [comment]
> 本就是不同的，不应该绑定一定一样的处理，linux工具链不支持也不代表none的也不支持

市面上，这么多 linux toolchain 版本了，xmake 内部是不可能全部挨个处理的，只能统一一种 能够覆盖到 90% case 处理方式来处理。。使得影响面保持最小。。

如果要更细粒度处理 每个特定 linux cross toolchain，只有用户自定义 toolchain，而不是让 xmake 内部去各种改，适配其中某种 toolchain 。。。


1. ar 支持 @file, 比较稳定，但是部分用户的 toolchain ar 不支持 lto
2. gcc-ar 部分机用户环境不支持 @file
3. gcc-ar 去掉 @file ，命令过长会失败

反正目前的情况，就是这三种，我这边没法全部兼容，也没法对每个不同版本的 gcc cross toolchain 挨个处理。。

目前的解决办法就两种，

1. 上面三种情况，评估最容易遇到的 case ，我改过去，至少能保证 90% 的用户不会 break，然后剩下 10% 的 case ，你们自定 toolchain 来解决
2. 帮忙一起分析下原因，直接解决 gcc-ar.exe 对 `@file` 的处理，以及 `ar.exe` 对 lto 的处理问题，直接能兼容解决当然是最好的。

**Comment by waruqi** [comment]
目前能想到的一种完全兼容方案，https://github.com/xmake-io/xmake/issues/5015#issuecomment-2105524165 但具体是否可靠，我暂时不确定，即使可以这么搞，估计也得废几天时间。。

**Comment by Dozingfiretruck** [comment]
> > 本就是不同的，不应该绑定一定一样的处理，linux工具链不支持也不代表none的也不支持
> 
> 市面上，这么多 linux toolchain 版本了，xmake 内部是不可能全部挨个处理的，只能统一一种 能够覆盖到 90% case 处理方式来处理。。使得影响面保持最小。。要么用 gcc-ar 要么用 ar `@file`
> 
> 如果要更细粒度处理 每个特定 linux cross toolchain，只有用户自定义 toolchain，而不是让 xmake 内部去各种改，适配其中某种 toolchain 。。。
> 
> 1. ar 支持 @file, 比较稳定，但是部分用户的 toolchain ar 不支持 lto
> 2. gcc-ar 部分机用户环境不支持 @file
> 3. gcc-ar 去掉 @file ，命令过长会失败
> 
> 反正目前的情况，就是这三种，我这边没法全部兼容，也没法对每个不同版本的 gcc cross toolchain 挨个处理。。
> 
> 目前的解决办法就两种，
> 
> 1. 上面三种情况，评估最容易遇到的 case ，我改过去，至少能保证 90% 的用户不会 break，然后剩下 10% 的 case ，你们自定义 toolchain 来解决
> 2. 帮忙一起分析下原因，直接解决 gcc-ar.exe 对 `@file` 的处理，以及 `ar.exe` 对 lto 的处理问题，直接能兼容解决当然是最好的。

1，嵌入式使用的是裸机工具链，和linux完全分开的没有关系，不管是ARM还是其他厂家发布GCC时候都是分开的版本，完全独立的，因为完全是两个方向
2，好的，我这里没法复现，我和客户沟通下看能不能提供环境我测试下，我这里，我们公司其他同事，还有ci上都没法复现，目前只有两个客户和你哪里能稳定出现此问题

**Comment by Dozingfiretruck** [comment]
问题基本了解为啥了，客户下载的不是发行版，所以引入了这个问题，如果回退 ar 就没问题，lto问题只存在于老版本的linux编译工具，我们使用的10以上的裸机编译工具没有此问题

所以lto问题算是老版本工具链bug，如果要支持的话是否可以根据linux gcc版本进行兼容处理？
另外大佬上面说的完全兼容方案也行，不过应该比较费劲吧

**Comment by waruqi** [comment]
> 问题基本了解为啥了，客户下载的不是发行版，所以引入了这个问题，如果回退 ar 就没问题，lto问题只存在于老版本的linux编译工具，我们使用的10以上的裸机编译工具没有此问题
> 
> 所以lto问题算是老版本工具链bug，如果要支持的话是否可以根据linux gcc版本进行兼容处理？ 另外大佬上面说的完全兼容方案也行，不过应该比较费劲吧

根据版本也可以，关键是得先确定是哪个版本以下不支持 lto

**Comment by waruqi** [comment]
而且即使根据版本切，低版本 gcc 下用 gcc-ar 。。不还是会遇到你这的问题。。低版本下还是没法完全兼容。。。仅仅只是不影响高版本了，限制了影响范围。。

应该是根据版本判断，高版本还是用 ar 不用任何处理，。低版本走 ar --plugin lto_plugin.so 去传参兼容。。

**Comment by Dozingfiretruck** [comment]
> 稍微改了下，应该可以了，不过目前不是完美方案，只能针对 gcc-ar 禁用 @file ，但是如果命令行过长，可能会有问题。
> 
> 如果要同时兼容支持 `gcc-ar/lto` 和 `ar @file` ，不太好搞。
> 
> 先试试吧。`xmake update -s dev`

好的，和客户说了，等客户测试一下，这个只有部分客户电脑会出现问题，

> 而且即使根据版本切，低版本 gcc 下用 gcc-ar 。。不还是会遇到你这的问题。。低版本下还是没法完全兼容。。。仅仅只是不影响高版本了，限制了影响范围。。
> 
> 应该是根据版本判断，高版本还是用 ar 不用任何处理，。低版本走 ar --plugin lto_plugin.so 去传参兼容。。

是的，这个方法可以

**Comment by waruqi** [comment]
现在这个 patch 应该差不多了 https://github.com/xmake-io/xmake/pull/5087

**Comment by Dozingfiretruck** [comment]
> 现在这个 patch 应该差不多了 #5087

我这里测试可以正常编译，如果有客户反馈有问题我再继续反馈，先关掉了
