### ISSUE TITLE
includes("**/xmake.lua") 卡死

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#5052]
### Xmake 版本

xmake v2.8.9+dev.50dbca648

### 操作系统版本和架构

Ubuntu 2204

### 描述问题

一旦使用 includes("**/xmake.lua") 就会导致卡死，但是逐个逐个使用就没有问题。
![image](https://github.com/xmake-io/xmake/assets/47598093/a2c2c57a-70ff-4a78-b719-7e57a7eb4743)
我一开始怀疑是有 xmake.lua 文件也用了 includes("**/xmake.lua")  导致循环解析，所以将当前文件夹下所有的 xmake.lua 挨个添加排查：

![image](https://github.com/xmake-io/xmake/assets/47598093/63047f63-8efa-4efb-9ad7-d783636f2126)

因为另一台电脑也是用的这个 xmake commit-id 的版本，所以也排除是 xmake 版本的问题。如果可以调试的话应该是很容易发现问题的，但是 emmylua 插件也是在 xmake 进程内运行的，还没走到调试阶段就卡住了：
![VFS$_DHS{2YY83P}S60TCBS](https://github.com/xmake-io/xmake/assets/47598093/42ce0b47-f15a-4f29-914e-e2bafa4ba289)

### 期待的结果

想知道卡死的原因，怀疑和本地项目有关系，但是项目太大不方便构造一个最小 demo。或者有没有其他的调试方法。

### 工程配置

暂无

### 附加信息和错误日志

无。

**Comment by waruqi** [comment]
估计是 includes 匹配的里面，又匹配到了带有 `includes("**/xmake.lua")` 的 xmake.lua 导致死循环了。不过我这没法复现，你只能自己调下。

https://github.com/xmake-io/xmake/blob/57a6b50a9ff4b87360b0147fab067ee806ebf587/xmake/core/base/interpreter.lua#L1688

**Comment by TOMO-CAT** [comment]
> api_builtin_includes

ok，我打日志看看

**Comment by waruqi** [comment]
解决了么

**Comment by TOMO-CAT** [comment]
> 解决了么

还没解决，卡在这一行：
![image](https://github.com/xmake-io/xmake/assets/47598093/f5a3f95c-6862-4e7a-8f64-608a70dc3880)

日志如下：
![image](https://github.com/xmake-io/xmake/assets/47598093/433904eb-302f-450d-84e6-9bfc629aec61)

**Comment by TOMO-CAT** [comment]
> 解决了么

到这为止就没法继续往下调试了：

rootdir “.”
pattern ".*/xmake%.lua"
recursion -1
mode 0
excludes nil
callback nil

![image](https://github.com/xmake-io/xmake/assets/47598093/459d6fb3-cd72-4f64-8d19-c50666317d12)

**Comment by TOMO-CAT** [comment]
如果到此为止参数都是正确的，那我就重装 xmake 吧，如果参数有问题，那我就接着调试看一下哪一行出的问题

**Comment by waruqi** [comment]
那你这个估计是走 `**/` 递归匹配，扫到太多文件了，所以遍历太慢。。你这项目底下多少文件？

你可以设置 callback 看下具体遍历到了哪里。。

```lua
local file = os.match("**/xmake.lua", true, function (filepath, isdir)
    print(filepath)
    return true
end)
```

也可能是你 .git 目录下子文件太多

**Comment by TOMO-CAT** [comment]
> ```lua
> local file = os.match("**/xmake.lua", true, function (filepath, isdir)
>     print(filepath)
>     return true
> end)
> ```

![image](https://github.com/xmake-io/xmake/assets/47598093/18d83498-0d6a-4f2c-8f18-b4c855ffa1e6)

还是直接卡住了没打印什么东西，这个项目确实很大，但是 find . -name xmake.lua 很快就返回了。
![image](https://github.com/xmake-io/xmake/assets/47598093/39ed8f5a-d4a8-4358-b9cf-764978ff041c)

**Comment by waruqi** [comment]
那你只能继续调下 c 里面的遍历了。。https://github.com/xmake-io/xmake/blob/f66ae558c39dfa1411c1e1e2653b8bd4249f477d/core/src/xmake/os/find.c#L36

拉下 xmake 源码，然后上面地方 通过 printf 或者 tb_trace_i 去 打印下 内部执行，看看遍历到哪了

```console
./configure
make
source ~/scripts/srcenv.profile
xmake build
```

再不行，就只能调下 tbox 里面的遍历接口了。。https://github.com/tboox/tbox/blob/c6b0a56076941b8263e162c7fe7b0870ea44e09c/src/tbox/platform/posix/directory.c#L270

**Comment by TOMO-CAT** [comment]
> 那你只能继续调下 c 里面的遍历了。。
> 
> https://github.com/xmake-io/xmake/blob/f66ae558c39dfa1411c1e1e2653b8bd4249f477d/core/src/xmake/os/find.c#L36
> 
> 拉下 xmake 源码，然后上面地方 通过 printf 或者 tb_trace_i 去 打印下 内部执行，看看遍历到哪了
> 
> ```
> ./configure
> make
> source ~/scripts/srcenv.profile
> xmake build
> ```
> 
> 再不行，就只能调下 tbox 里面的遍历接口了。。https://github.com/tboox/tbox/blob/c6b0a56076941b8263e162c7fe7b0870ea44e09c/src/tbox/platform/posix/directory.c#L270

好的，我再试试，另外这个能通过 includes("**/xmake.lua|.git/**/xmake.lua") 来跳过 .git 下面的遍历吗

**Comment by TOMO-CAT** [comment]
> 也可能是你 .git 目录下子文件太多

**Comment by waruqi** [comment]
`includes("**/xmake.lua|.git/**")`

**Comment by waruqi** [comment]
> xmake 4w 个文件的遍历能抗住吗

没压测过，但也许会很慢，通常我不会 includes 里面这么干。。

**Comment by waruqi** [comment]
你可以自己 `xmake l os.files "**"` 测下。。

**Comment by TOMO-CAT** [comment]
卡住了至少得一分钟还没返回。。。
![image](https://github.com/xmake-io/xmake/assets/47598093/8ad73b1b-14df-4614-8d8e-d4c22ae24d23)


这能优化一下性能吗，至少 find 是立马返回了。虽然这个项目是比较大一点，但是 git 项目 5000 个文件以上还是很普遍的

**Comment by TOMO-CAT** [comment]
> > xmake 4w 个文件的遍历能抗住吗
> 
> 没压测过，但也许会很慢，通常我不会 includes 里面这么干。。

但是这是官方文档的写法，对于大型项目多目录里面都有 xmake.lua 的话挺好用的。
![image](https://github.com/xmake-io/xmake/assets/47598093/6232e599-3e37-40b7-a76c-da2b7b2c7e41)

**Comment by waruqi** [comment]
> 卡住了至少得一分钟还没返回。。。 ![image](https://private-user-images.githubusercontent.com/47598093/329429374-8ad73b1b-14df-4614-8d8e-d4c22ae24d23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMDUzMTMsIm5iZiI6MTcxNTMwNTAxMywicGF0aCI6Ii80NzU5ODA5My8zMjk0MjkzNzQtOGFkNzNiMWItMTRkZi00NjE0LThkOGUtZDRjMjJhZTI0ZDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDAxMzY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2NGZiNzFkZGRkY2FjOTZjYTNkZmY0ZjQ3MzU2ZWZiZGNjZDM1ZTViZDNjMWM4NzQ1M2E1ZGI5ZDcwYTkzNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sLMCX2NxbCOTDmiCEAX0_WO_7B4jGUWt1eTsau1NM18)
> 
> 这能优化一下性能吗，至少 find 是立马返回了。虽然这个项目是比较大一点，但是 git 项目 5000 个文件以上还是很普遍的

find 是纯c的，xmake 里每个遍历，内部都要调度 lua 接口交互，还得每次做 lua pattern 模式匹配，多少会影响性能，但避免不了，而且遍历结果还得塞进 lua table 受限于 lua 的资源管理

**Comment by waruqi** [comment]
但应该也不会太慢，顶多比 find 慢一点点而已，这边 llvm 12w 的文件，find 遍历 2s 。 xmake 里面遍历，算上 lua 模式匹配 + print 回显一些耗时，总共也就 10s 。。你这才 4w，按理顶多 4s 的时间。。。卡住肯定是其他问题，这个就只能你自己调
下 c 层代码了。。

```console
llvm ruki$ time find ./ -type f | wc -l
  126189

real	0m1.946s
user	0m0.145s
sys	0m1.629s
```

```console
llvm ruki$ time xmake l os.files "**" > /tmp/a

real	0m10.200s
user	0m4.564s
sys	0m5.304s
```

**Comment by TOMO-CAT** [comment]
> 但应该也不会太慢，顶多比 find 慢一点点而已，这边 llvm 12w 的文件，find 遍历 2s 。 xmake 里面遍历，算上 lua 模式匹配 + print 回显一些耗时，总共也就 10s 。。你这才 4w，按理顶多 4s 的时间。。。卡住肯定是其他问题，这个就只能你自己调 下 c 层代码了。。
> 
> ```
> llvm ruki$ time find ./ -type f | wc -l
>   126189
> 
> real	0m1.946s
> user	0m0.145s
> sys	0m1.629s
> ```
> 
> ```
> llvm ruki$ time xmake l os.files "**" > /tmp/a
> 
> real	0m10.200s
> user	0m4.564s
> sys	0m5.304s
> ```

我感觉也是哪里卡死了，打日志调试一下下面的 C 代码看看

**Comment by waruqi** [comment]
而且按你目前的 xmake.lua 结构，可以改成 `includes("*/xmake.lua", "*/*/xmake.lua")`，限制到单层，双层遍历，应该效率会高不少。。能不递归遍历全部 就不要这么做，尤其是工程很大的情况下。

**Comment by TOMO-CAT** [comment]
> 而且按你目前的 xmake.lua 结构，可以改成 `includes("*/xmake.lua", "*/*/xmake.lua")`，限制到单层，双层遍历，应该效率会高不少。。能不递归遍历全部 就不要这么做，尤其是工程很大的情况下。

挨个试了一下，删掉 blade-bin 文件夹就可以了，暂时这么写绕过去，但是还是不懂为什么挂在 C++ 函数里：

```lua
includes("**/xmake.lua|blade-bin/**/xmake.lua")
```

**Comment by waruqi** [comment]
这个只有你这调下 c 层代码才行

**Comment by Yangff** [comment]
我猜你的这个

> 删掉 blade-bin 文件夹就可以了

文件夹里面有到上层的软链。

![image](https://github.com/xmake-io/xmake/assets/1381921/76014b72-cf26-46b4-991a-c52e8ebe4067)
![image](https://github.com/xmake-io/xmake/assets/1381921/ce39e884-7f67-44a2-964d-33e6929b7841)
这样就能卡了

**Comment by TOMO-CAT** [comment]
> > 删掉 blade-bin 文件夹就可以了

确实，bazel 和 blade 都会生成软链。

**Comment by TOMO-CAT** [comment]
话说这个有软链（即使软链里面没有 xmake.lua 文件）会卡死的问题算 bug 吗

**Comment by waruqi** [comment]
> 话说这个有软链（即使软链里面没有 xmake.lua 文件）会卡死的问题算 bug 吗

估计是软链到上层导致递归死循环遍历了

**Comment by TOMO-CAT** [comment]
> > 话说这个有软链（即使软链里面没有 xmake.lua 文件）会卡死的问题算 bug 吗
> 
> 估计是软链到上层导致递归死循环遍历了，这种目前也区分不了

好的，我看看 bazel 都生成了些啥玩意

**Comment by TOMO-CAT** [comment]
> > 话说这个有软链（即使软链里面没有 xmake.lua 文件）会卡死的问题算 bug 吗
> 
> 估计是软链到上层导致递归死循环遍历了，这种目前也区分不了

不过这里检测到循环抛出来一个 warning 或者异常是不是更友好一点，之前我个人的体验是直接卡死了，没有调试经验的话完全不知道发生了什么

**Comment by waruqi** [comment]
> > > 话说这个有软链（即使软链里面没有 xmake.lua 文件）会卡死的问题算 bug 吗
> > 
> > 
> > 估计是软链到上层导致递归死循环遍历了，这种目前也区分不了
> 
> 不过这里检测到循环抛出来一个 warning 或者异常是不是更友好一点，之前我个人的体验是直接卡死了，没有调试经验的话完全不知道发生了什么

检测这种就需要通过 map 维护已经遍历过的路径状态，影响遍历性能，尤其是遍历大规模文件时候，还影响内存。。而且这种case 出现概率太低。。为了检测这种，去做更复杂的处理，没必要

**Comment by TOMO-CAT** [comment]
> 检测这种就需要通过 map 维护已经遍历过的路径状态，影响遍历性能，尤其是遍历大规模文件时候，还影响内存。。而且这种case 出现概率太低。。为了检测这种，去做更复杂的处理，没必要

okok，那先维持现状吧
