### ISSUE TITLE
The buildenvs function of autoconf.lua has uninitialized table

### ISSUE THREAD

**Issue by lanytcc** [xmake-io/xmake#5053]
### Xmake 版本

xmake v2.9.1+HEAD.0c79f6162

### 操作系统版本和架构

Windows 11 24H2

### 描述问题

error: @programdir\core\base\table.lua:113: bad argument # 1 to 'insert' (table expected, got nil)
![image](https://github.com/xmake-io/xmake/assets/96584640/c2f3b42b-c9e0-423b-9c56-e4ab9c620d62)

安装ffmpeg时报错
xmake-repo ffmpeg/xmake.lua 204行这句
```lua
local envs = autoconf.buildenvs(package, {packagedeps = "libiconv"})
```
然后对应autoconf.lua在315行
```lua
table.join2(shflags, _map_linkflags(fake_target, "shared", {"cxx"}, "runtime", runtimes))
```

注释掉315行那个就没问题了

### 期待的结果

正确安装

### 工程配置

xmake-repo中的ffmpeg/xmake.lua

### 附加信息和错误日志

默认配置安装就会遇到

**Comment by waruqi** [comment]
我记得这个问题上周 dev 已经修复了，更新下就行了
