### ISSUE TITLE
cudaErrorNoDevice 卡较长时间

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#5058]
### Xmake 版本

xmake v2.8.9+dev.50dbca648

### 操作系统版本和架构

Ubuntu 2204

### 描述问题

背景是开发机上安装了 cuda、cudann 等相关库，但是没有英伟达显卡，xmake -b 或者 xmake r 时会卡在 `checking for cuda devices` 较长时间。
![image](https://github.com/xmake-io/xmake/assets/47598093/4bd827cf-d069-4235-a1cb-58c99798dd6d)

### 期待的结果

希望可以通过设置关掉这个检测。

### 工程配置

无

### 附加信息和错误日志

无

- [ ]

**Comment by waruqi** [comment]
只有 add_cugencodes 里面配置了 native，才会走到这个 find 逻辑，如果自动探测，就不要 传 native
