### ISSUE TITLE
add_deps有性能问题

### ISSUE THREAD

**Issue by wagcheg** [xmake-io/xmake#5059]
### Xmake 版本

2.9.1

### 操作系统版本和架构

ArchLinux 6.7.9-lqx1-1-lqx  x86_64 GNU/Linux

### 描述问题

config有依赖的项目花费的时间随着项目数量增加快速增长

### 期待的结果

config时间降低

### 工程配置

set_kind("phony")
local num = 100
for i=1,num do
    target("t" .. i)
    for j=i+1,num do
        add_deps("t" .. j)
    end
    target_end()
end
i=num + 1
target("t" .. i)
target_end()

### 附加信息和错误日志

[many_targets]$ xmake f -vD
checking for gcc ... /usr/bin/gcc
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(nim --version), No such file or directory
checking for nim ... no
checkinfo: cannot runv(nim --version), No such file or directory
checking for nim ... no

后面就卡住了 一个cpu核被占满

**Comment by waruqi** [comment]
再试试，应该可以了，https://github.com/xmake-io/xmake/pull/5061

xmake update -s dev
