### ISSUE TITLE
Support absolute library path of the package when link

### ISSUE THREAD

**Issue by star-hengxing** [xmake-io/xmake#5066]
### Is your feature request related to a problem? Please describe.

https://github.com/xmake-io/xmake-repo/issues/3962
https://github.com/xmake-io/xmake/issues/4964
https://github.com/xmake-io/xmake/issues/3889

### Describe the solution you'd like

```lua
add_packages("xxx", {absolute_lib = true})
```

### Additional context

Will it conflict with `add_linkorders`?

**Comment by waruqi** [comment]
try https://github.com/xmake-io/xmake/pull/5099

```lua
add_packages("xxx", {linkpath = true})
```

**Comment by TOMO-CAT** [comment]
试了最新的 dev 分支还是 -l 的，是我要手动 cherry-pick 改动吗

**Comment by waruqi** [comment]
patch 还没merge `xmake update -s github:xmake-io/xmake#linkpath`

**Comment by Latias94** [comment]
vulkansdk 支持不

**Comment by waruqi** [comment]
> vulkansdk 支持不

系统库不支持，需要能找到完整库路径。目前只是 fetch only 包 https://github.com/xmake-io/xmake-repo/blob/dev/packages/v/vulkansdk/xmake.lua

除非你改进这个包 增加 on_install ，或者让 on_fetch 检测到库路径，返回 libfiles

**Comment by waruqi** [comment]
> 试了最新的 dev 分支还是 -l 的，是我要手动 cherry-pick 改动吗

merge 了，再试下 dev

**Comment by TOMO-CAT** [comment]
> > 试了最新的 dev 分支还是 -l 的，是我要手动 cherry-pick 改动吗
> 
> merge 了，再试下 dev

可以了，不过我更期待是 policy 这种写法，感觉是一种使用动态库的风格。

至少应该是 `add_requires("xxx")` 的级别，不然的话代码里每次使用 add_packages 都要加一行这个。

**Comment by waruqi** [comment]
> > > 试了最新的 dev 分支还是 -l 的，是我要手动 cherry-pick 改动吗
> > 
> > 
> > merge 了，再试下 dev
> 
> 可以了，不过我更期待是 policy 这种写法，感觉是一种使用三方库的风格。
> 
> 至少应该是 `add_requires("xxx")` 的级别，不然的话代码里每次使用 add_packages 都要加一行这个。

放进 add_requires 里，每次切 linkpath 和 -l 都需要重新安装一遍，并且云端预编译的包也用不了。。走 add_packages ，你想切的时候，几秒就能切过去，默认还是走 -l ，只有需要 linkpath 的加一下就好了。。

而且也不是所有包都能找到完整库路径。。系统库，brew 等一些三方包管理 目前是不支持的
