### ISSUE TITLE
armclang汇编警告

### ISSUE THREAD

**Issue by PeakRacing** [xmake-io/xmake#5071]
### Xmake 版本

2.9.1

### 操作系统版本和架构

win10

### 描述问题

![image](https://github.com/xmake-io/xmake/assets/24759100/a02ab3d2-654d-4bbc-b715-ea9b78414a05)
有 Warning: A3912W: Option 't' is deprecated. 警告，但是并未设置 t 参数

### 期待的结果

无警告

### 工程配置

armclang编译

### 附加信息和错误日志

Warning: A3912W: Option 't' is deprecated.

**Comment by waruqi** [comment]
这个好像跟 xmake 没啥关系吧，你可以自己调下 flags ，看下为啥 armclang 会显示这个警告。。xmake 没有加其他 flags

**Comment by Dozingfiretruck** [comment]
> 这个好像跟 xmake 没啥关系吧，你可以自己调下 flags ，看下为啥 armclang 会显示这个警告。。xmake 没有加其他 flags

重新捋了一遍确实不应该和xmake有关系，不是xmake加的，但是却报这个，ide里显示的汇编命令有
```
-mcpu=cortex-m3 -masm=auto  -Wa,armasm,--diag_suppress=A1950W -c
-gdwarf-4 -Wa,armasm,--pd,"__MICROLIB SETA 1"
 -Wa,armasm, -Wa,armasm,--pd,"AIR32F10X_MD SETA 1"
```
但是自己写这些命令其中
```
 -mcpu=cortex-m3 -masm=auto  -Wa,armasm,--diag_suppress=A1950W -c -gdwarf-4 -Wa,armasm,
```
都会报不识别
，命令中好像会把-后面的一个字母吞掉一样，没弄明白怎么回事

比如 -mcpu=cortex-m3 
![image](https://github.com/xmake-io/xmake/assets/24759100/464b3f7f-338b-433e-9e85-bf4ac45ca926)
编译会报
![image](https://github.com/xmake-io/xmake/assets/24759100/ee822cc9-ca63-4bcb-abbf-0ac4e9e28c43)
会把-后面的一个字母吞掉，变成了 -cpu cortex-m3

**Comment by CofeCofe** [comment]
这个应该是使用的armasm编译器导致的，armasm编译器只支持-cpu -float。armclang也能作为汇编代码的编译器，对应到armclang下就是-mcpu -mfloat。不知道xmake中能不能**显式指定汇编的编译器** @waruqi ，类似cmake中的
`set(CMAKE_ASM_COMPILER armclang.exe)`
这样应该能解决这个问题

**Comment by CofeCofe** [comment]
我也遇到相似的问题，将/xmake/安装/路径/toolchains/armclang/xmake.lua更改了
* 第32行`set_toolset("as", "armasm")`更改为`set_toolset("as", "armclang")`
* 第62行`toolchain:add("asflags", "-cpu="   .. arch_cpu)`更改为`toolchain:add("asflags", "-mcpu="   .. arch_cpu)`
这样就将默认的汇编编译器切换为armclang了，重新运行xmake之后解决了。
Arm Compiler **6.14**之后才支持armasm语法，原有的xmake.lua可能需要增加一个对armclang版本的判断。

**Comment by waruqi** [comment]
> 第32行set_toolset("as", "armasm")更改为set_toolset("as", "armclang")

target 里面也有 set_toolset 接口的，或者直接 `xmake f --as=` ，或者自定义 toolchain

**Comment by Dozingfiretruck** [comment]
> 我也遇到相似的问题，将/xmake/安装/路径/toolchains/armclang/xmake.lua更改了
> 
> * 第32行`set_toolset("as", "armasm")`更改为`set_toolset("as", "armclang")`
> * 第62行`toolchain:add("asflags", "-cpu="   .. arch_cpu)`更改为`toolchain:add("asflags", "-mcpu="   .. arch_cpu)`
>   这样就将默认的汇编编译器切换为armclang了，重新运行xmake之后解决了。
>   Arm Compiler **6.14**之后才支持armasm语法，原有的xmake.lua可能需要增加一个对armclang版本的判断。

@waruqi 对armclang版本进行判断比较靠谱，跟随keil的行为

**Comment by waruqi** [comment]
可以直接来个 pr 过来，我暂时没这个 toolchain
