### ISSUE TITLE
cannot import module: lib.luajit.bcsave

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#5092]
### Xmake 版本

xmake v2.9.1+master.7bb2f2bd6

### 操作系统版本和架构

Ubuntu 2204

### 描述问题

更新了最新 master 版本后报错，怀疑是之前我重写了 protobuf 的 rule，调用了 private.utils，是现在不让调用了吗？
![image](https://github.com/xmake-io/xmake/assets/47598093/49a91706-fcee-4bd3-9e99-12099170a9b8)
之所以要重写是因为现在 protobuf.cpp 的规则不支持引用第三方路径的 proto 文件，比如 triton-backend 需要引用到它的 proto，这样在 protoc 生成 xx.pb.h 文件的时候就需要传入 `-I${triton_root_path} -I${my_proto_path}`，所以重写了一下支持传入各种自定义参数。

### 期待的结果

解决新版本 xmake 无法运行的问题。

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
模块名都说了是 private ，意思就是私有模块，我随时都会改，用户不能用，乱用用出问题，这边概不负责。。

你整个 utils 加载，里面很多模块都会被带进来，还有一些 luajit 才会用到的模块也被加载了，当然会跪

**Comment by waruqi** [comment]
如果非要用 private 自己翻下源码分析下，utils是目录 不是单个模块 

https://github.com/xmake-io/xmake/tree/master/xmake/modules/private/utils

**Comment by TOMO-CAT** [comment]
> 如果非要用 private 自己翻下源码分析下，utils是目录 不是单个模块
> 
> https://github.com/xmake-io/xmake/tree/master/xmake/modules/private/utils

好的，我研究下

**Comment by waruqi** [comment]
要么改成 `import("private.utils.batchcmds")` ，至少当前错误应该能过掉，但不保证后面这个私有模块 会有其他改动

**Comment by TOMO-CAT** [comment]
> 要么改成 `import("private.utils.batchcmds")` ，至少当前错误应该能过掉，但不保证后面这个私有模块 会有其他改动

好的解决了。
