### ISSUE TITLE
Xpack支持deb包

### ISSUE THREAD

**Issue by SmartSmallBoy** [xmake-io/xmake#5107]
### 你在什么场景下需要该功能？

写个debian服务，编译+打包

### 描述可能的解决方案

Xpack支持 set_formats("deb")

**Comment by waruqi** [comment]
暂时没空搞，有兴趣的话，可以来个 pr 

参考 ：https://github.com/xmake-io/xmake/tree/master/xmake/plugins/pack/rpm
https://github.com/xmake-io/xmake/pull/4788

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/pull/5210
