### ISSUE TITLE
mfc UNICODE下连接错误的问题

### ISSUE THREAD

**Issue by ranwei1025** [xmake-io/xmake#511]
> 注：如果是`问题报障`或者`特性请求`，请选择对应issues模板，否则一律不回复。

### 描述问题详情
vs2015的mfc对话框例子工程，在UNICODE并静态连接mfc库下出现下面的错误

error: libcmt.lib(exe_winmain.obj) : error LNK2019: 无法解析的外部符号 WinMain，
该符号在函数 "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh
@@YAHXZ) 中被引用

例子工程见附件，谢谢

[t1.zip](https://github.com/xmake-io/xmake/files/3435485/t1.zip)

**Comment by waruqi** [comment]
mfc程序需要设置`win.sdk.mfc`规则，会自动设置一些相关的链接库，以及win main入口也会设置上。

```lua
target("test")
    add_rules("win.sdk.mfc")
    add_files("src/*.c")
```

更多详情可以参考：[#201](https://github.com/xmake-io/xmake/issues/201)

然后升级到 dev 版本 https://github.com/xmake-io/xmake/releases/download/v2.2.7/xmake-dev.exe

试下新的vs工程生成插件，支持的更加完善，也对rules做了支持

```console
xmake project -k vsxmake2015
```

**Comment by ranwei1025** [comment]
add_rules("win.sdk.mfc") 试了 不加add_defines("_UNICODE", "UNICODE") 没问题 加了还是报最开始的错误

**Comment by waruqi** [comment]
你代码里面 WinMain 入口加了么，把main替换成这个。。

```lua
int WINAPI
WinMain (
         _In_ HINSTANCE hInstance,
         _In_opt_ HINSTANCE hPrevInstance,
         _In_ LPSTR lpszCmdLine,
         _In_ int nCmdShow
         )
{
}
```

**Comment by waruqi** [comment]
你命令行执行xmake编译试试，能通过么，不行的话，加-v提供下详细的编译输出：

```console
$ xmake -v
```

**Comment by ranwei1025** [comment]
configure
{
    ccache = true
    ndk_stdcxx = true
    plat = windows
    buildir = build
    wdk = d:\\cc\\wdk10\\Program Files\\Windows Kits\\10\
    arch = x64
    mode = release
    mrc = C:\Program Files (x86)\Windows Kits\8.1\bin\x64\rc.exe
    cxx = cl.exe
    host = windows
    kind = static
    vs = 2015
    debugger = D:\cc\wdk10\Program Files\Windows Kits\10\Debuggers\x64\windbg.exe
    ld = link.exe
}
[100%]: linking.release q1.exe
link.exe /SUBSYSTEM:WINDOWS -nologo -dynamicbase -nxcompat -machine:x64 -out:build\\windows\\x64\\release\\q1.exe build\\.objs\\q1\\windows\\x64\\release\\.\\t1.rc.obj build\\.objs\\q1\\windows\\x64\\release\\.\\t1.cpp.obj build\\.objs\\q1\\windows\\x64\\release\\.\\stdafx.cpp.obj build\\.objs\\q1\\windows\\x64\\release\\.\\t1Dlg.cpp.obj
error: libcmt.lib(exe_winmain.obj) : error LNK2019: 无法解析的外部符号 WinMain，该符号在函数 "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ) 中被引用
build\windows\x64\release\q1.exe : fatal error LNK1120: 1 个无法解析的外部命令

**Comment by waruqi** [comment]
错了，mfc的规则我提供错了。。你改成 `win.sdk.mfc.shared_app` 或者 `win.sdk.mfc.static_app` 试试

**Comment by ranwei1025** [comment]
现在可以了

**Comment by waruqi** [comment]
这块，我更新了下文档 可以看下：https://xmake.io/#/zh-cn/guide/project_examples?id=mfc%e7%a8%8b%e5%ba%8f
