### ISSUE TITLE
Can't link statically with clang on Windows

### ISSUE THREAD

**Issue by tetsuhaut** [xmake-io/xmake#5110]
### Xmake Version

2.9.1

### Operating System Version and Architecture

Windows 10

### Describe Bug

Using the following xmake.lua file:

```
set_languages("c++23")
add_rules("mode.debug")
set_policy("build.warning", true)
set_warnings("all", "extra")
set_toolchain("clang")
target("mybinary")
    set_kind("binary")
    add_files("src/**.cpp")
    add_cxxflags("-static", {tools = "clang"})
```
and running the command
`xmake -v`
produces the (edited) output:
```
clang++ -o build\windows\x64\release\mybinary.exe build\.objs\mybinary\windows\x64\release\src\main.cpp.obj -m64
```
The `mybinary.exe` executable then fails to load some clang dll files (libc++.dll and libunwind.dll).

### Expected Behavior

The produced output should be
```
clang++ -o build\windows\x64\release\mybinary.exe build\.objs\mybinary\windows\x64\release\src\main.cpp.obj -m64 -static
```

### Project Configuration
```
set_languages("c++23")
add_rules("mode.debug")
set_policy("build.warning", true)
set_warnings("all", "extra")
set_toolchain("clang")
target("mybinary")
    set_kind("binary")
    add_files("src/**.cpp")
    add_cxxflags("-static", {tools = "clang"})
```
### Additional Information and Error Logs

I tried
`add_cxxflags("-static", {tools = "clang"})`
`add_cxflags("-static", {tools = "clang"})`
`add_ldflags("-static", {tools = "clang"})`
`add_cxxflags("clang::-static")`
`add_cxflags("clang::-static")`
`add_ldflags("clang::-static")`
with no success :(

**Comment by waruqi** [comment]
`-static` is linker flags. try `add_ldflags("-static", {force = true})`

**Comment by tetsuhaut** [comment]
It works, thank you [waruqi](https://github.com/waruqi)!
So after a few tests: 
- `add_ldflags("-static")` works,
- `add_ldflags("clang::-static")` doesn't work,
- `add_ldflags("-static", {toto = "clang"})` doesn't work.

Is the version `add_ldflags("-static")` portable?

**Comment by waruqi** [comment]
> It works, thank you [waruqi](https://github.com/waruqi)! So after a few tests:
> 
> * `add_ldflags("-static")` works,
> * `add_ldflags("clang::-static")` doesn't work,
> * `add_ldflags("-static", {tools = "clang"})` doesn't work.

you need add `force = true`

> 
> Is the version `add_ldflags("-static")` portable?

gcc/clang support it

**Comment by tetsuhaut** [comment]
I tried without the force = true and it worked, so maybe it is not always required?
Anyway thank you for the help!

**Comment by star-hengxing** [comment]
You can use [set_runtimes](https://xmake.io/#/manual/project_target?id=targetset_runtimes)

**Comment by tetsuhaut** [comment]
thanks for the hint @star-hengxing. I would love to have a portable xmake.lua, so I am trying to set clang options only if the clang compiler is in use

**Comment by star-hengxing** [comment]
> thanks for the hint @star-hengxing. I would love to have a portable xmake.lua, so I am trying to set clang options only if the clang compiler is in use

```lua
on_config(function (target)
    if target:has_tool("cxx", "clang") then
        target:set("runtimes", "c++_static")
    end
end)
```

**Comment by tetsuhaut** [comment]
👍
