### ISSUE TITLE
对cpp使用qtmoc的增量编译问题

### ISSUE THREAD

**Issue by Elite-stay** [xmake-io/xmake#5124]
### Xmake 版本

~~2.9.1~~ 2.8.8

### 操作系统版本和架构

Ubuntu 20.04

### 描述问题

对cpp使用qt.moc规则会导致每次构建都会重新编译cpp

### 期待的结果

不要每次都重新编译

### 工程配置

[test.zip](https://github.com/xmake-io/xmake/files/15397070/test.zip)

### 附加信息和错误日志

[ 20%]: compiling.qt.moc src/main.cpp
[100%]: build ok, spent 0.041s

**Comment by Elite-stay** [comment]
#5121

**Comment by waruqi** [comment]
再试试 应该可以了 xmake update -s dev

**Comment by Elite-stay** [comment]
> 再试试 应该可以了 xmake update -s dev

ok了
