### ISSUE TITLE
Windows 下找不到llvm toolchain

### ISSUE THREAD

**Issue by MaxwellGengYF** [xmake-io/xmake#5128]
### Xmake 版本

2.9.1 dev

### 操作系统版本和架构

Windows

### 描述问题

llvm toolchain not found.

### 期待的结果

使用where或遍历PATH

### 工程配置

xmake f --toolchain=llvm -c

### 附加信息和错误日志

error: llvm toolchain not found!

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/pull/5129

**Comment by waruqi** [comment]
merge 了，再试试
