### ISSUE TITLE
希望增加支持termux

### ISSUE THREAD

**Issue by Domain** [xmake-io/xmake#513]
android的termux是一个很好的手机开发环境，我尝试过编译xmake，修改了一些配置之后，可以编译通过，但是最后使用还是有问题。很多是路径问题，例如/tmp在termux是不可用的，必须改为$PREFIX/tmp

**Comment by waruqi** [comment]
可以 回头我看下

**Comment by OpportunityLiu** [comment]
Android系统就没有/tmp

**Comment by waruqi** [comment]
@Domain 你可以先设置 `XMAKE_TMPDIR=xxxx`, XMAKE_GLOBALDIR这两环境变量到 android 上对应自己指定目录 试试。。xmake的几个全局目录访问 都是可以通过 环境变量，来配置切换的。。

你可以设置到bash的profile里面去，每次进入终端后，都先切换下

**Comment by waruqi** [comment]
关于编译这块，我回头处理下，对android下也提供编译支持

**Comment by waruqi** [comment]
dev下，android对应的luajit autogen我加上了。。可以通过xmake来编译android版本xmake core

```console
cd core
xmake f -p android --ndk=xxx -a [armv7-a|arm64-v8a]
xmake
```

**Comment by Domain** [comment]
@waruqi 设置环境变量确实可以运行，不过编译出来的helloworld都会崩

**Comment by waruqi** [comment]
这个得看你这termux里面的gcc编译工具链 生成的target是什么arch的 是否也是对应android arm的 

你可以加上-v参数，给我看下验证的编译命令 xmake -v

另外你也可以自己确认下生成的可执行文件对应的 arch

**Comment by Domain** [comment]
我用file看了一下生成的文件：
ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, with debug_info, not stripped
感觉应该是对的，直接用gcc编译出来也是这个

**Comment by waruqi** [comment]
我这边测试编译和运行ok，不过我是直接在 termux上直接编译的 xmake

编译和运行过程确实还比较繁琐，回头我看看能否简化下。

我这边的操作：

```console
pkg install git getconf vim 
mkdir ./tmp
mkdir ./usr
git clone https://github.com/xmake-io/xmake.git --recursive
cd xmake
# 将这三个宏注释禁用掉TB_CONFIG_POSIX_HAVE_POSIX_SPAWNP TB_CONFIG_POSIX_HAVE_PTHREAD_SETAFFINITY_NP TB_CONFIG_LIBC_HAVE_BACKTRACE
vim core/src/tbox/inc/linux/tbox.config.h 
make build TMP_DIR=`pwd`/../tmp
make install prefix=`pwd`/../usr TMP_DIR=`pwd`/../tmp
cd ..
export PATH=`pwd`/usr/bin:$PATH
export XMAKE_TMPDIR=`pwd`/tmp
xmake create test
cd test
xmake
xmake run
```

![WechatIMG259](https://user-images.githubusercontent.com/151335/62007118-5fa1a180-b17c-11e9-821c-9a6d8d00a23b.jpeg)

**Comment by waruqi** [comment]
刚稍微改进了下，编译和xmake内部可以通过获取 $TMPDIR $PREFIX等termux内置环境变量，来处理

简化为：

```console
pkg install git getconf vim 
git clone https://github.com/xmake-io/xmake.git -b dev --recursive
cd xmake
# 将这三个宏注释禁用掉TB_CONFIG_POSIX_HAVE_POSIX_SPAWNP TB_CONFIG_POSIX_HAVE_PTHREAD_SETAFFINITY_NP TB_CONFIG_LIBC_HAVE_BACKTRACE
vim core/src/tbox/inc/linux/tbox.config.h 
make build 
make install 
cd ..
xmake create test
cd test
xmake
xmake run
```

关于tbox.config.h 的编辑，我回头在改进下，目前有些配置启用后，在termux上编译，缺一些头文件和符号，所以暂时禁用了。。

**Comment by waruqi** [comment]
现在可以了，@Domain 你更新下 dev 再试试

```console
pkg install git getconf clang
git clone https://github.com/xmake-io/xmake.git -b dev --recursive
cd xmake
make build 
make install 
cd ..
xmake create test
cd test
xmake
xmake run
```

**Comment by waruqi** [comment]
现在直接通过官网提供的一键安装脚本get.sh，也可以直接装了，可以试试

```console
bash <(curl -fsSL https://raw.githubusercontent.com/xmake-io/xmake/master/scripts/get.sh)
```

**Comment by Domain** [comment]
我自己编译会报错：
link demo.b
make[3]: *** [/data/data/com.termux/files/home/git/xmake/core/suffix.mak:304: demo.b] Error 1
make[2]: *** [/data/data/com.termux/files/home/git/xmake/core/suffix.mak:304: SUB_PROS_demo_all] Error 2
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: ../xmake/libxmaker.a(tmpdir.o): in function `xm_os_tmpdir':
tmpdir.c:(.text+0x1c): undefined reference to `tb_directory_temporary'
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: ../tbox/libtboxr.a(path.o): in function `tb_path_translate':
path.c:(.text+0x4c): undefined reference to `tb_directory_home'
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: ../tbox/libtboxr.a(print.o): in function `tb_print':
print.c:(.text+0x2c): undefined reference to `__android_log_print'
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: ../tbox/libtboxr.a(print.o): in function `tb_printl':
print.c:(.text+0x7c): undefined reference to `__android_log_print'
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: ../tbox/libtboxr.a(platform.o): in function `tb_platform_init_env':
platform.c:(.text+0x4): undefined reference to `tb_android_init_env'
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: ../tbox/libtboxr.a(platform.o): in function `tb_platform_exit_env':
platform.c:(.text+0x44): undefined reference to `tb_android_exit_env'
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Domain** [comment]
安装脚本也报错：

/proc/self/fd/11: line 82: sudo: command not found
Dependencies Installation Fail
The getter currently only support these package managers
        * apt
        * yum
        * zypper
        * pacman
Please install following dependencies manually:
        * git
        * build essential like `make`, `gcc`, etc
        * libreadline-dev (readline-devel)
        * ccache (optional)

**Comment by waruqi** [comment]
> 我自己编译会报错：

你确定拉取的是最新的commit吗？可以重新pull后再试试，昨天有个改动导致了这个问题，后来我修复了 应该。。

**Comment by waruqi** [comment]
> 安装脚本也报错：
> 
> /proc/self/fd/11: line 82: sudo: command not found
> Dependencies Installation Fail
> The getter currently only support these package managers
> * apt
> * yum
> * zypper
> * pacman
> Please install following dependencies manually:
> * git
> * build essential like `make`, `gcc`, etc
> * libreadline-dev (readline-devel)
> * ccache (optional)

看错误，还是用的老的脚本，最新master的get.sh 应该没这问题了。。我昨天测试过

**Comment by Domain** [comment]
我把本地的删除了，重新clone，确实可以了，不过我发现C语言没问题，C++会崩，就是简单的std::cout输出hello都不行

**Comment by waruqi** [comment]
> 我把本地的删除了，重新clone，确实可以了，不过我发现C语言没问题，C++会崩，就是简单的std::cout输出hello都不行

我这边测试 运行也没问题么。。你加上-v 编译，给我看下详细的编译错误，以及运行崩溃信息

**Comment by Domain** [comment]
$> xmake -v
configure
{
    arch = arm64-v8a
    ccache = true
    mode = release
    ndk_stdcxx = true
    host = linux
    ld = g++
    kind = static
    buildir = build
    cxx = gcc
    plat = linux
}
[  0%]: compiling.release src/main.cpp
gcc -c -fvisibility=hidden -O3 -o build/.objs/hello/linux/arm64-v8a/release/src/main.cpp.o src/main.cpp
[100%]: linking.release hello
g++ -o build/linux/arm64-v8a/release/hello build/.objs/hello/linux/arm64-v8a/release/src/main.cpp.o -s -fvisibility=hidden

 $> xmake run
error: execv(/data/data/com.termux/files/home/git/cpp/hello/build/linux/arm64-v8a/release/hello) failed(-1)!

$> ./build/linux/arm64-v8a/release/hello
[1]                   23310 segmentation fault   ./build/linux/arm64-v8a/release/hello

**Comment by waruqi** [comment]
这就不清楚了，我这边可以，对比下，也就是跟你这的gcc/g++路径上有区别。。

要么就是你这的gcc有问题，这跟xmake没啥关系了，你可以看下自己这边的编译链接选项，并没有什么特别的。。

你可以自己复制下对应的编译命令，手动执行gcc编译试试。

或者切到debug编译，然后安装下gdb，调试下看看

![WechatIMG262](https://user-images.githubusercontent.com/151335/62096891-caa3c300-b2b7-11e9-952f-d46b0bd7a24c.jpeg)

**Comment by Domain** [comment]
解决了，termux问题：
https://github.com/termux/termux-packages/issues/3990
