### ISSUE TITLE
xmake create -lc -Phello will not replace FAQ and TARGETNAME

### ISSUE THREAD

**Issue by Freed-Wu** [xmake-io/xmake#5138]
### Xmake Version

v2.9.1+20240422,

### Operating System Version and Architecture

Linux 6.9.1

### Describe Bug

```sh
$ xmake create -lc -Phello
create Desktop ...
error: cannot open file: xmake.lua, Not access because it is busy
$ cat hello/xmake.lua
add_rules("mode.debug", "mode.release")

target("${TARGETNAME}")
    set_kind("binary")
    add_files("src/*.c")

${FAQ}
```

### Expected Behavior

```sh
$ xmake create -lc -Phello
create Desktop ...
$ cat hello/xmake.lua
add_rules("mode.debug", "mode.release")

target("hello")
    set_kind("binary")
    add_files("src/*.c")
```

### Project Configuration

/

### Additional Information and Error Logs

And xmake.lua generated by `xmake create` has permission `r--r--r--`. Why not use umask?

**Comment by waruqi** [comment]
```console
ruki:dddd ruki$ xmake create -lc -Phello
create dddd ...
  [+]: xmake.lua
  [+]: src/main.c
  [+]: .gitignore
create ok!
ruki:dddd ruki$ cat ./hello/xmake.lua
add_rules("mode.debug", "mode.release")

target("dddd")
    set_kind("binary")
    add_files("src/*.c")

```

it works for me.

**Comment by Freed-Wu** [comment]
I have tested in other OSs and it can work. I think it is the bug about NixOS.

**Comment by Freed-Wu** [comment]
We should have `os.chmod()`, then run `os.chmod('file', '+x')` after `os.cp()`.

**Comment by waruqi** [comment]
why?

**Comment by Freed-Wu** [comment]
See https://github.com/NixOS/nixpkgs/issues/314313

**Comment by waruqi** [comment]
`os.cp(srcfile, dstfile)` 

it will add `+w` to open and create dstfile.
https://github.com/tboox/tbox/blob/553c32406a09e3e0a0a8e8dfed741b4888ba07ca/src/tbox/platform/posix/file.c#L80

and srcfile is only for readonly.

**Comment by Freed-Wu** [comment]
No. It doesn't happened. If I `chmod -w` in other OS, the same error will be throw.

**Comment by waruqi** [comment]
Does it work now?

**Comment by Freed-Wu** [comment]
Yes, thanks!

**Comment by Freed-Wu** [comment]
https://github.com/NixOS/nixpkgs/issues/314313#issuecomment-2134239967

`unset LD` cannot work. Is it a bug?

**Comment by Freed-Wu** [comment]
Oh, I must `rm .xmake -rf`.

**Comment by Freed-Wu** [comment]
Can we allow use `ld` as `$LD`? I think it is nature.
