### ISSUE TITLE
Check Endianness / get csnippet output

### ISSUE THREAD

**Issue by FenixFyreX** [xmake-io/xmake#514]
### Is your feature request related to a problem? Please describe.
I am trying to detect the endianness of the platform I am compiling on. I do not know how to get the output of a program with `configvar_check_csnippets` or `lib.detect.check_cxxsnippets`. Is there a way to find out the endianness, or, get the output of the above commands?

### Describe the solution you'd like
1) `if(is_endian("little") or is_endian("big"))`
1) `configvar_check_endianness("MY_CONFIG_ENDIANNESS")`
2) `lib.detect.get_csnippet_output('int x = 1; printf("%d",*(char*)&x == 1);')`

**Comment by waruqi** [comment]
You only need detect it in c/c++ code. for example:

```c
// words endian
#ifdef __BYTE_ORDER__
#   if __BYTE_ORDER__ != __ORDER_LITTLE_ENDIAN__
#       define TB_WORDS_BIGENDIAN
#   endif
#endif
#if defined(MIPSEB) || defined(_MIPSEB) || defined(__MIPSEB__)
#   define TB_WORDS_BIGENDIAN
#endif

// float endian
#ifdef __FLOAT_WORD_ORDER__
#   if __FLOAT_WORD_ORDER__ != __ORDER_LITTLE_ENDIAN__
#       define TB_FLOAT_BIGENDIAN
#   endif
#endif
```
configvar_check_csnippets only try to compile and link the snippet code, but do not run it. so it  can only do some compile-time testing.
