### ISSUE TITLE
Getting types for `plugins.show.lists.apis`

### ISSUE THREAD

**Issue by Frityet** [xmake-io/xmake#5143]
### Is your feature request related to a problem? Please describe.

I would like to be able to automatically generate LuaLanguageServer meta files for xmake, and to do this, type annotations for the APIs would be cruicial

### Describe the solution you'd like

The `apis.apis()` call to return a table which has the name, alongside the types, i.e

```lua
path = {
      join = {
          return_type = "string",
          arguments = {
              { "path1", "string" },
              { varadict = true, "string" }
          },
          method = false
      }
}
```

### Describe alternatives you've considered

Parsing the documentation as [the previously existing project does](https://github.com/LelouchHe/xmake-luals-addon/blob/main/crawl.py)

**Comment by charlesseizilles** [comment]
We are currently working on the xmake-gendoc project that will contain the information you are looking for https://github.com/xmake-io/xmake-gendoc/blob/main/doc/en-us/api/script/builtin_modules/os/joinenvs.md?plain=1#L4C1-L4C50 although it is nowhere near finished...

**Comment by Frityet** [comment]
Awesome! thank you so much
