### ISSUE TITLE
[BUG] xmake运行结果不一致

### ISSUE THREAD

**Issue by KarryCharon** [xmake-io/xmake#5144]
### Xmake Version

2.8.9

### Operating System Version and Architecture

macOS 14.3.1 (23D60)

### Describe Bug

当使用 vscode的xmake插件提供的build 按钮构建项目时, xmake内置工具 os.iorunv 运行结果与外部终端运行结果有差异
图1(外部终端运行):
![image](https://github.com/xmake-io/xmake/assets/49889381/c75ee0e0-3e2d-4b70-b152-69f310358adc)

图2(vscode插件运行):
![image](https://github.com/xmake-io/xmake/assets/49889381/b2f0ee84-4dc4-4b5d-9262-c2ffc020e7d8)

- 不止是运行 python3 指令结果不同, 诸如 which program 等内置程序用于查找程序路径的运行结果也不一致
图3(外部终端运行):
![image](https://github.com/xmake-io/xmake/assets/49889381/a510fe93-df6c-4177-bc40-95cbcf183bc5)

图4(vscode插件运行):
![image](https://github.com/xmake-io/xmake/assets/49889381/947138e0-f6ac-4044-8c0e-1ba655141f14)

### Expected Behavior

-

### Project Configuration

-

### Additional Information and Error Logs

-

**Comment by waruqi** [comment]
可以对比两边的 envs

```console
xmake l os.getenvs
print(os.getenvs())
```

**Comment by KarryCharon** [comment]
这里对比了两个运行情况下的 envs, 目前发现有差异的是这几条(PATH相关的变量包含的条目均相互等价但顺序不同):
![image](https://github.com/xmake-io/xmake/assets/49889381/4aa0824e-1703-479b-951c-92ae044bbb9c)

以下是envs打印的原始文件:
[env_terminal.txt](https://github.com/xmake-io/xmake/files/15444015/env_terminal.txt)
[env_vscode.txt](https://github.com/xmake-io/xmake/files/15444016/env_vscode.txt)

**Comment by waruqi** [comment]
是 PATH 不同，导致优先找到的 python3 不同。。具体为什么会有这些路径，这就不清楚了，你可以自己调下 vscode 的 envs 。。

**Comment by KarryCharon** [comment]
> 是 PATH 不同，导致优先找到的 python3 不同。。具体为什么会有这些路径，这就不清楚了，你可以自己调下 vscode 的 envs 。。

断点看了vscode的 xmake 插件, ShellExecution 没传env 进去, 即使传递了 自定义的 env 结果仍然不正确

**Comment by waruqi** [comment]
估计 vscode 下，PATH 有差异，导致内部的 xmake 进程获取到的 PATH 也有区别，所以找的位置不对。。

你可以 vscode terminal 下看看 PATH 是否跟 外面的 terminal 不同。。

**Comment by KarryCharon** [comment]
> 估计 vscode 下，PATH 有差异，导致内部的 xmake 进程获取到的 PATH 也有区别，所以找的位置不对。。
> 
> 你可以 vscode terminal 下看看 PATH 是否跟 外面的 terminal 不同。。

<img width="1663" alt="image" src="https://github.com/xmake-io/xmake/assets/49889381/53af7c93-73ff-475f-a71d-37d94414c6e4">
<img width="2056" alt="image" src="https://github.com/xmake-io/xmake/assets/49889381/4c72c04b-98b4-4966-bbc1-bb7dcdcf9aae">

**Comment by waruqi** [comment]
那就是了么，就是你这 vscode terminal 的 PATH 不同给干扰了，这个这边也没办法，你只能自己调下 这个里面的 path 。。

**Comment by KarryCharon** [comment]
> 那就是了么，就是你这 vscode terminal 的 PATH 不同给干扰了，这个这边也没办法，你只能自己调下 这个里面的 path 。。

不是, 上面那个图里的3 个PATH 都是正确的, 但build 运行的lua脚本里的不对啊

**Comment by KarryCharon** [comment]
> > 那就是了么，就是你这 vscode terminal 的 PATH 不同给干扰了，这个这边也没办法，你只能自己调下 这个里面的 path 。。
> 
> 不是, 上面那个图里的3 个PATH 都是正确的, 但build 运行的lua脚本里的不对啊

上面三个PATH虽然有区别 但 我自己的pyenv( /Users/karrycharon/.pyenv/shims )都靠前, 当 build 运行时 却拿的 /Library/Frameworks/Python.framework/Versions/3.10/bin 作为python路径

**Comment by KarryCharon** [comment]
> 那就是了么，就是你这 vscode terminal 的 PATH 不同给干扰了，这个这边也没办法，你只能自己调下 这个里面的 path 。。

而且 最关键的是 在xmake插件里调整env的 PATH是不起作用的, 好像跟没传一样

**Comment by waruqi** [comment]
> > 那就是了么，就是你这 vscode terminal 的 PATH 不同给干扰了，这个这边也没办法，你只能自己调下 这个里面的 path 。。
> 
> 而且 最关键的是 在xmake插件里调整env的 PATH是不起作用的, 好像跟没传一样

这个，你可以自己调下 插件看下 为啥没生效。。然后 插件里面执行 `xmake l os.getenvs` 看下 PATH 的结果。。以及实际 find——package 那个地方的 PATH 结果 

也可以手动执行 xmake 命令编译时候，在那个位置看下 PATH 的结果

**Comment by KarryCharon** [comment]
> > > 那就是了么，就是你这 vscode terminal 的 PATH 不同给干扰了，这个这边也没办法，你只能自己调下 这个里面的 path 。。
> > 
> > 
> > 而且 最关键的是 在xmake插件里调整env的 PATH是不起作用的, 好像跟没传一样
> 
> 这个，你可以自己调下 插件看下 为啥没生效。。然后 插件里面执行 `xmake l os.getenvs` 看下 PATH 的结果。。以及实际 find——package 那个地方的 PATH 结果
> 
> 也可以手动执行 xmake 命令编译时候，在那个位置看下 PATH 的结果

xmake插件里执行 `xmake l os.getenvs` 和 实际find_package的env完全一样, 都是错的.
这是我在xmake插件里写的命令行运行方法:
<img width="1004" alt="image" src="https://github.com/xmake-io/xmake/assets/49889381/568ba84e-1105-4fe8-a737-0619aec012bf">
这是命令运行结果:
![image](https://github.com/xmake-io/xmake/assets/49889381/14bfdf46-51fc-4605-8cdb-ce6a3f764189)

**Comment by waruqi** [comment]
那就还是 插件执行  xmake 给的 PATH 不一致，跟 xmake 本身没啥关系了。。你可以调下插件，然后来个 pr

**Comment by KarryCharon** [comment]
> 那就还是 插件执行 xmake 给的 PATH 不一致，跟 xmake 本身没啥关系了。。你可以调下插件，然后来个 pr

我试了下, 非常奇怪, 我重写了PATH, 但 vscode运行Shell 会默认前面自动加一堆PATH
<img width="1376" alt="image" src="https://github.com/xmake-io/xmake/assets/49889381/a6574125-f606-4d16-906f-6947332484d2">
![image](https://github.com/xmake-io/xmake/assets/49889381/e9b0941c-3d70-4f25-9638-26f7a69a458d)
