### ISSUE TITLE
windows安装远程包SuiteSparse失败

### ISSUE THREAD

**Issue by Xiaobin-Jiang** [xmake-io/xmake#5145]
### Xmake 版本

2.9.1

### 操作系统版本和架构

Windows11 23H2 22631.3593

### 描述问题

xmake 安装远程包suitesparse失败。

xmake require "suitesparse 7.7.0"

msbuild的时候出现
无法打开包括文件: “stdalign.h”: No such file or directory 

在suitesparse issue中有人提过这个问题，https://github.com/DrTimothyAldenDavis/SuiteSparse/issues/315  
不知道该怎么修复

### 期待的结果

在windows上可以成功安装suitesparse包

### 工程配置

xmake require "suitesparse 7.7.0"

### 附加信息和错误日志

       “E:\xmake\.xmake\cache\packages\2405\s\suitesparse\v7.7.0\source\build_b6a9876e\SuiteSparse.sln”(Rebuild 目标) (1) ->
       “E:\xmake\.xmake\cache\packages\2405\s\suitesparse\v7.7.0\source\build_b6a9876e\ALL_BUILD.vcxproj.metaproj”(Rebuild 目标) (2) ->
       “E:\xmake\.xmake\cache\packages\2405\s\suitesparse\v7.7.0\source\build_b6a9876e\LAGraph\experimental\benchmark\AllKCore_demo.vcxproj.metaproj”(Rebuild 目标) (5) ->
       “E:\xmake\.xmake\cache\packages\2405\s\suitesparse\v7.7.0\source\build_b6a9876e\GraphBLAS\GraphBLAS_static.vcxproj.metaproj”(Rebuild 目标) (6) ->
       “E:\xmake\.xmake\cache\packages\2405\s\suitesparse\v7.7.0\source\build_b6a9876e\GraphBLAS\GraphBLAS_static.vcxproj”(Rebuild 目标) (127) ->
       (ClCompile 目标) -> 
         E:\xmake\.xmake\cache\packages\2405\s\suitesparse\v7.7.0\source\GraphBLAS\xxHash\xxhash.h(1193,1): fatal error C1083: 无法打开包括文件: “stdalign.h”: No such file or directory [E:\xmake\.xmake\cache\packages\2405\s\suitesparse\v7.7.0\source\build_b6a9876e\GraphBLAS\GraphBLAS_static.vcxproj]

    3250 个警告
    1 个错误

已用时间 00:20:19.62

**Comment by star-hengxing** [comment]
Windows sdk 和 msvc 版本是多少

我在本地试过用高版本 sdk + v141-143 工具链都没问题，大概率升级 sdk 版本就好了

**Comment by Xiaobin-Jiang** [comment]
MSVC：14.39.33519 
Windows11 SDK 10.0.22621.0

xmake uninstall 后，重新安装了2.9.1版本， 其他环境和之前一样，今天安装正常。
前几天我也尝试过重新安装，但似乎每次都存在上面的问题。

当前xmake repo的是master commit: 2f6415728fb0b2aba779b08b37d0c96d5e466ecf
前几天是在某个dev的commit上。

当我继续往下编译的时候，在vs中链接ceres.lib时出现无法解析的外部符号。
看起来都是和cuda相关的函数。

http://ceres-solver.org/installation.html#dependencies   似乎是需要加一个USE_CUDA的flag

出错的log:
1>ceres.lib(context_impl.obj) : error LNK2019: 无法解析的外部符号 cublasCreate_v2，函数 "public: bool __cdecl ceres::internal::ContextImpl::InitCuda(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?InitCuda@ContextImpl@internal@ceres@@QEAA_NPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中引用了该符号
1>ceres.lib(context_impl.obj) : error LNK2019: 无法解析的外部符号 cublasDestroy_v2，函数 "public: void __cdecl ceres::internal::ContextImpl::TearDown(void)" (?TearDown@ContextImpl@internal@ceres@@QEAAXXZ) 中引用了该符号
1>ceres.lib(context_impl.obj) : error LNK2019: 无法解析的外部符号 cublasSetStream_v2，函数 "public: bool __cdecl ceres::internal::ContextImpl::InitCuda(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?InitCuda@ContextImpl@internal@ceres@@QEAA_NPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中引用了该符号
1>ceres.lib(context_impl.obj) : error LNK2019: 无法解析的外部符号 cusolverDnCreate，函数 "public: bool __cdecl ceres::internal::ContextImpl::InitCuda(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?InitCuda@ContextImpl@internal@ceres@@QEAA_NPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中引用了该符号
1>ceres.lib(context_impl.obj) : error LNK2019: 无法解析的外部符号 cusolverDnDestroy，函数 "public: void __cdecl ceres::internal::ContextImpl::TearDown(void)" (?TearDown@ContextImpl@internal@ceres@@QEAAXXZ) 中引用了该符号
1>ceres.lib(context_impl.obj) : error LNK2019: 无法解析的外部符号 cusolverDnSetStream，函数 "public: bool __cdecl ceres::internal::ContextImpl::InitCuda(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?InitCuda@ContextImpl@internal@ceres@@QEAA_NPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中引用了该符号
1>ceres.lib(context_impl.obj) : error LNK2019: 无法解析的外部符号 cusparseCreate，函数 "public: bool __cdecl ceres::internal::ContextImpl::InitCuda(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?InitCuda@ContextImpl@internal@ceres@@QEAA_NPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中引用了该符号
1>ceres.lib(context_impl.obj) : error LNK2019: 无法解析的外部符号 cusparseDestroy，函数 "public: void __cdecl ceres::internal::ContextImpl::TearDown(void)" (?TearDown@ContextImpl@internal@ceres@@QEAAXXZ) 中引用了该符号
1>ceres.lib(context_impl.obj) : error LNK2019: 无法解析的外部符号 cusparseSetStream，函数 "public: bool __cdecl ceres::internal::ContextImpl::InitCuda(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?InitCuda@ContextImpl@internal@ceres@@QEAA_NPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中引用了该符号
1>ceres.lib(cuda_vector.obj) : error LNK2019: 无法解析的外部符号 cublasDnrm2_v2，函数 "public: double __cdecl ceres::internal::CudaVector::Norm(void)const " (?Norm@CudaVector@internal@ceres@@QEBANXZ) 中引用了该符号
1>ceres.lib(cuda_vector.obj) : error LNK2019: 无法解析的外部符号 cublasDdot_v2，函数 "public: double __cdecl ceres::internal::CudaVector::Dot(class ceres::internal::CudaVector const &)const " (?Dot@CudaVector@internal@ceres@@QEBANAEBV123@@Z) 中引用了该符号
1>ceres.lib(cuda_vector.obj) : error LNK2019: 无法解析的外部符号 cublasDscal_v2，函数 "public: void __cdecl ceres::internal::CudaVector::Axpby(double,class ceres::internal::CudaVector const &,double)" (?Axpby@CudaVector@internal@ceres@@QEAAXNAEBV123@N@Z) 中引用了该符号
1>ceres.lib(cuda_vector.obj) : error LNK2019: 无法解析的外部符号 cublasDaxpy_v2，函数 "public: void __cdecl ceres::internal::CudaVector::Axpby(double,class ceres::internal::CudaVector const &,double)" (?Axpby@CudaVector@internal@ceres@@QEAAXNAEBV123@N@Z) 中引用了该符号
1>ceres.lib(cuda_vector.obj) : error LNK2019: 无法解析的外部符号 cusparseCreateDnVec，函数 "public: void __cdecl ceres::internal::CudaVector::Resize(int)" (?Resize@CudaVector@internal@ceres@@QEAAXH@Z) 中引用了该符号
1>ceres.lib(cuda_sparse_matrix.obj) : error LNK2001: 无法解析的外部符号 cusparseCreateDnVec
1>ceres.lib(cuda_vector.obj) : error LNK2019: 无法解析的外部符号 cusparseDestroyDnVec，函数 "private: void __cdecl ceres::internal::CudaVector::DestroyDescriptor(void)" (?DestroyDescriptor@CudaVector@internal@ceres@@AEAAXXZ) 中引用了该符号
1>ceres.lib(cuda_sparse_matrix.obj) : error LNK2001: 无法解析的外部符号 cusparseDestroyDnVec
1>ceres.lib(cuda_sparse_matrix.obj) : error LNK2019: 无法解析的外部符号 cusparseDestroySpMat，函数 "public: __cdecl ceres::internal::CudaSparseMatrix::~CudaSparseMatrix(void)" (??1CudaSparseMatrix@internal@ceres@@QEAA@XZ) 中引用了该符号
1>ceres.lib(cuda_sparse_matrix.obj) : error LNK2019: 无法解析的外部符号 cusparseCreateCsr，函数 "private: void __cdecl ceres::internal::CudaSparseMatrix::Initialize(void)" (?Initialize@CudaSparseMatrix@internal@ceres@@AEAAXXZ) 中引用了该符号
1>ceres.lib(cuda_sparse_matrix.obj) : error LNK2019: 无法解析的外部符号 cusparseSpMV，函数 "private: void __cdecl ceres::internal::CudaSparseMatrix::SpMv(enum cusparseOperation_t,struct cusparseDnVecDescr * const &,struct cusparseDnVecDescr * const &)const " (?SpMv@CudaSparseMatrix@internal@ceres@@AEBAXW4cusparseOperation_t@@AEBQEAUcusparseDnVecDescr@@1@Z) 中引用了该符号
1>ceres.lib(cuda_sparse_matrix.obj) : error LNK2019: 无法解析的外部符号 cusparseSpMV_bufferSize，函数 "unsigned __int64 __cdecl ceres::internal::`anonymous namespace'::GetTempBufferSizeForOp(struct cusparseContext * const &,enum cusparseOperation_t,struct cusparseDnVecDescr * const &,struct cusparseDnVecDescr * const &,struct cusparseSpMatDescr * const &)" (?GetTempBufferSizeForOp@?A0x48a253b6@internal@ceres@@YA_KAEBQEAUcusparseContext@@W4cusparseOperation_t@@AEBQEAUcusparseDnVecDescr@@2AEBQEAUcusparseSpMatDescr@@@Z) 中引用了该符号
1>ceres.lib(dense_cholesky.obj) : error LNK2019: 无法解析的外部符号 cublasDsymv_v2，函数 "public: virtual enum ceres::internal::LinearSolverTerminationType __cdecl ceres::internal::CUDADenseCholeskyMixedPrecision::Solve(double const *,double *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?Solve@CUDADenseCholeskyMixedPrecision@internal@ceres@@UEAA?AW4LinearSolverTerminationType@23@PEBNPEANPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中引用了该符号
1>ceres.lib(dense_cholesky.obj) : error LNK2019: 无法解析的外部符号 cusolverDnSpotrf_bufferSize，函数 "private: enum ceres::internal::LinearSolverTerminationType __cdecl ceres::internal::CUDADenseCholeskyMixedPrecision::CudaCholeskyFactorize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?CudaCholeskyFactorize@CUDADenseCholeskyMixedPrecision@internal@ceres@@AEAA?AW4LinearSolverTerminationType@23@PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中引用了该符号
1>ceres.lib(dense_cholesky.obj) : error LNK2019: 无法解析的外部符号 cusolverDnDpotrf_bufferSize，函数 "public: virtual enum ceres::internal::LinearSolverTerminationType __cdecl ceres::internal::CUDADenseCholesky::Factorize(int,double *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?Factorize@CUDADenseCholesky@internal@ceres@@UEAA?AW4LinearSolverTerminationType@23@HPEANPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中引用了该符号
1>ceres.lib(dense_cholesky.obj) : error LNK2019: 无法解析的外部符号 cusolverDnSpotrf，函数 "private: enum ceres::internal::LinearSolverTerminationType __cdecl ceres::internal::CUDADenseCholeskyMixedPrecision::CudaCholeskyFactorize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?CudaCholeskyFactorize@CUDADenseCholeskyMixedPrecision@internal@ceres@@AEAA?AW4LinearSolverTerminationType@23@PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中引用了该符号
1>ceres.lib(dense_cholesky.obj) : error LNK2019: 无法解析的外部符号 cusolverDnDpotrf，函数 "public: virtual enum ceres::internal::LinearSolverTerminationType __cdecl ceres::internal::CUDADenseCholesky::Factorize(int,double *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?Factorize@CUDADenseCholesky@internal@ceres@@UEAA?AW4LinearSolverTerminationType@23@HPEANPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中引用了该符号
1>ceres.lib(dense_cholesky.obj) : error LNK2019: 无法解析的外部符号 cusolverDnSpotrs，函数 "private: enum ceres::internal::LinearSolverTerminationType __cdecl ceres::internal::CUDADenseCholeskyMixedPrecision::CudaCholeskySolve(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?CudaCholeskySolve@CUDADenseCholeskyMixedPrecision@internal@ceres@@AEAA?AW4LinearSolverTerminationType@23@PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中引用了该符号
1>ceres.lib(dense_cholesky.obj) : error LNK2019: 无法解析的外部符号 cusolverDnDpotrs，函数 "public: virtual enum ceres::internal::LinearSolverTerminationType __cdecl ceres::internal::CUDADenseCholesky::Solve(double const *,double *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?Solve@CUDADenseCholesky@internal@ceres@@UEAA?AW4LinearSolverTerminationType@23@PEBNPEANPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中引用了该符号
1>ceres.lib(dense_qr.obj) : error LNK2019: 无法解析的外部符号 cublasDtrsv_v2，函数 "public: virtual enum ceres::internal::LinearSolverTerminationType __cdecl ceres::internal::CUDADenseQR::Solve(double const *,double *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?Solve@CUDADenseQR@internal@ceres@@UEAA?AW4LinearSolverTerminationType@23@PEBNPEANPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中引用了该符号
1>ceres.lib(dense_qr.obj) : error LNK2019: 无法解析的外部符号 cusolverDnDgeqrf_bufferSize，函数 "public: virtual enum ceres::internal::LinearSolverTerminationType __cdecl ceres::internal::CUDADenseQR::Factorize(int,int,double *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?Factorize@CUDADenseQR@internal@ceres@@UEAA?AW4LinearSolverTerminationType@23@HHPEANPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中引用了该符号
1>ceres.lib(dense_qr.obj) : error LNK2019: 无法解析的外部符号 cusolverDnDgeqrf，函数 "public: virtual enum ceres::internal::LinearSolverTerminationType __cdecl ceres::internal::CUDADenseQR::Factorize(int,int,double *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?Factorize@CUDADenseQR@internal@ceres@@UEAA?AW4LinearSolverTerminationType@23@HHPEANPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中引用了该符号
1>ceres.lib(dense_qr.obj) : error LNK2019: 无法解析的外部符号 cusolverDnDormqr_bufferSize，函数 "public: virtual enum ceres::internal::LinearSolverTerminationType __cdecl ceres::internal::CUDADenseQR::Solve(double const *,double *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?Solve@CUDADenseQR@internal@ceres@@UEAA?AW4LinearSolverTerminationType@23@PEBNPEANPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中引用了该符号
1>ceres.lib(dense_qr.obj) : error LNK2019: 无法解析的外部符号 cusolverDnDormqr，函数 "public: virtual enum ceres::internal::LinearSolverTerminationType __cdecl ceres::internal::CUDADenseQR::Solve(double const *,double *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?Solve@CUDADenseQR@internal@ceres@@UEAA?AW4LinearSolverTerminationType@23@PEBNPEANPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中引用了该符号

**Comment by star-hengxing** [comment]
> http://ceres-solver.org/installation.html#dependencies 似乎是需要加一个USE_CUDA的flag

已经加上了，再试试

**Comment by Xiaobin-Jiang** [comment]
可以了，谢谢！
