### ISSUE TITLE
--help 不应该检查xmake.lua文件

### ISSUE THREAD

**Issue by Domain** [xmake-io/xmake#515]
如果当前目录下有xmake.lua文件，并且文件有错，那么xmake --help不会显示帮助，而是显示错误，包括所有子命令都这样，例如xmake create --help。
我觉得--help参数就不要读取xmake.lua了吧

**Comment by waruqi** [comment]
要读的 因为 你项目当前xmake.lua 里面  如果通过task定义了自己的任务或者插件， xmake --help 里面会一并显示出来

如果定义了option等自定义选项 也会在xmake config --help 里面显示出来 作为用户设置的可配置参数

**Comment by Domain** [comment]
嗯，虽然有道理，但是感觉对初次使用的人还是不够友好，想看看命令怎么用，还要把配置文件写对了才行。其实更大的问题是，现在的出错信息基本没法看

**Comment by waruqi** [comment]
错误显示这块我之后可以改进下 确保help能正常显示出来

不过xmake.lua还是要去读的

**Comment by waruqi** [comment]
我改进过了。help阶段加载xmake.lua出错，help菜单还是会正常显示
