### ISSUE TITLE
error: failed to open file: /root/.local/share/xmake/themes/default/xmake.lua

### ISSUE THREAD

**Issue by neptune87140104** [xmake-io/xmake#516]
### Describe the bug
After ./scripts/get.sh __local__ done and error occur
error: failed to open file: /root/.local/share/xmake/themes/default/xmake.lua

### Expected behavior
No any error

### Error output
compile.r string/endswith.c
compile.r string/startswith.c
compile.r string/trim.c
compile.r xmake.c
link libxmaker.a
make demo
compile.r xmake.c
link demo.b
installing to /root/.local ...
plat: linux
arch: x86_64
ok!
error: failed to open file: /root/.local/share/xmake/themes/default/xmake.lua
Reload shell profile by running the following command now!
source ~/.xmake/profile
root@siw-virtual-machine:/home/siw/hikyuu/xmake# xmake
xmake
root@siw-virtual-machine:/home/siw/hikyuu/xmake# xmake --help
error: failed to open file: /root/.local/share/xmake/themes/default/xmake.lua
root@siw-virtual-machine:/home/siw/hikyuu/xmake# source ~/.xmake/profile
root@siw-virtual-machine:/home/siw/hikyuu/xmake# xmake --help
error: failed to open file: /root/.local/share/xmake/themes/default/xmake.lua
root@siw-virtual-machine:/home/siw/hikyuu/xmake# vi /root/.local/share/xmake/themes/default/xmake.lua 
root@siw-virtual-machine:/home/siw/hikyuu/xmake# 

### Related Environment
$ git clone https://github.com/xmake-io/xmake.git
$ cd ./xmake
$ ./scripts/get.sh __local__

Linux version 4.15.0-55-generic (buildd@lgw01-amd64-038) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) #60~16.04.2-Ubuntu SMP Thu Jul 4 09:03:09 UTC 2019

### Additional context
No

**Comment by waruqi** [comment]
Please do not use xmake under root. If you must use it under root, please add --root parameter to any command. or set XMAKE_ROOT environment var.

```console
xmake --root --help
xmake --root
```

**Comment by neptune87140104** [comment]
> Please do not use xmake under root. If you must use it under root, please add --root parameter to any command. or set XMAKE_ROOT environment var.
> 
> ```
> xmake --root --help
> xmake --root
> ```

so you suggest to complile xmake and use it under normal user, right?

**Comment by waruqi** [comment]
Yes, usually we recommend  to use xmake in normal user mode, this will be more secure.

**Comment by neptune87140104** [comment]
ok, got it, thank you very much!

**Comment by neptune87140104** [comment]
if i don't change to root mode and compile xmake.
seems error will be occur

compile.r luajit/src/lj_trace.c
compile.r luajit/src/lj_udata.c
compile.r luajit/src/lj_vmevent.c
compile.r luajit/src/lj_vmmath.c
compile.r autogen/linux/jit/x86_64/lj_vm.S
link libluajitr.a
make tbox
make[3]: *** No rule to make target 'tbox/src/tbox/algorithm/binary_find.c', needed by 'tbox/src/tbox/algorithm/binary_find.o'.  Stop.
/home/siw/hikyuu/tboox/xmake/core/suffix.mak:304: recipe for target 'DEP_PROS_tbox_all' failed
make[2]: *** [DEP_PROS_tbox_all] Error 2
installing to /home/siw/.local ...
plat: linux
arch: x86_64
cp: cannot stat './core/src/demo/demo.b': No such file or directory
makefile:83: recipe for target 'install' failed
make: *** [install] Error 1
Install Fail
siw@siw-virtual-machine:~/hikyuu/tboox/xmake$

**Comment by waruqi** [comment]
You can try to use a clean directory to perform the installation.

```console
cd /tmp/test
git clone https://github.com/xmake-io/xmake.git
cd xmake
./scripts/get.sh __local__
```

or only run script

```console
bash <(curl -fsSL https://raw.githubusercontent.com/xmake-io/xmake/master/scripts/get.sh)
```
