### ISSUE TITLE
编译了过时的代码，但xmake clean && xmake清除后再构建则符合预期

### ISSUE THREAD

**Issue by liuhaocsucczu** [xmake-io/xmake#5161]
### Xmake 版本

2.8.9

### 操作系统版本和架构

Ubuntu20.04

### 描述问题

打印了一条过时的调试信息。
![1716889048455](https://github.com/xmake-io/xmake/assets/27711856/e4f7a420-fbf1-48bc-a74a-6f9da3f0819c)
此调试打印信息源代码中已删除。
![企业微信截图_17168891277349](https://github.com/xmake-io/xmake/assets/27711856/70fbe612-7f4f-4bb2-85e0-bb2ecf45ff63)
如果清除后再编译xmake clean&& xmake，则符合预期
![企业微信截图_17168892102087](https://github.com/xmake-io/xmake/assets/27711856/8c8b1dbf-27a2-496d-a07e-0b0d86b661e6)

### 期待的结果

不打印过时的调试信息

### 工程配置

工作环境是Ubuntu20.04虚拟机，通过vscode远程开发。
![企业微信截图_17168893454310](https://github.com/xmake-io/xmake/assets/27711856/8c285c7e-6d3f-44b6-94e8-c6e410aaecba)
xmake工程配置如下图
![企业微信截图_17168892823334](https://github.com/xmake-io/xmake/assets/27711856/b7629fc6-280f-4617-9fd7-5a1f2502fc01)

### 附加信息和错误日志

无。

**Comment by waruqi** [comment]
改下对应文件，看下 log ，是否会触发编译

```console
touch dtn_arq.c
xmake
```

**Comment by liuhaocsucczu** [comment]
> 改下对应文件，看下 log ，是否会触发编译
> 
> ```
> touch src/dtn_arq.c
> xmake
> ```

可以触发编译
![企业微信截图_17174862568446](https://github.com/xmake-io/xmake/assets/27711856/17af9180-f650-4523-92b7-5d9f8533099f)

**Comment by waruqi** [comment]
那增量编译没啥问题，或者可以禁用 `xmake f --ccache=n` 试下

**Comment by liuhaocsucczu** [comment]
> 那增量编译没啥问题，或者可以禁用 `xmake f --ccache=n` 试下
禁用 `xmake f --ccache=n`没有效果。
编译。
![企业微信截图_17180751323708](https://github.com/xmake-io/xmake/assets/27711856/e1adeb59-34ce-4440-bd5e-3f1609bd6a25)
![企业微信截图_17180751749088](https://github.com/xmake-io/xmake/assets/27711856/45923611-1630-4564-8168-4242b40a1a08)
过时的打印内容
![企业微信截图_1718075232603](https://github.com/xmake-io/xmake/assets/27711856/000558a8-ca8f-4ec1-a06b-1e39700570db)
源码中已删除
![企业微信截图_17180752794677](https://github.com/xmake-io/xmake/assets/27711856/a959507e-cb88-45f8-9da6-9cd77f6a353f)

**Comment by waruqi** [comment]
ccache 都禁了，那就跟 xmake 没啥关系了，你可以自己  xmake -vD 对比看下实际 link 的 obj ，看下 obj 是否最新 ，或者反编译看下。。

**Comment by liuhaocsucczu** [comment]
此问题是我自己的原因，可以关闭了，我的xmake脚本里面从别的目录拷贝了过时的动态库到目标目录。


> ccache 都禁了，那就跟 xmake 没啥关系了，你可以自己 xmake -vD 对比看下实际 link 的 obj ，看下 obj 是否最新 ，或者反编译看下。。
