### ISSUE TITLE
更好的第三方插件集成

### ISSUE THREAD

**Issue by yao-weijie** [xmake-io/xmake#5175]
### 你在什么场景下需要该功能？

最近有意做一个neovim的xmake插件，需要xmake导出更多信息
我看了下现有的相关插件，比如[xmake.nvim](https://github.com/Mythos-404/xmake.nvim)，[cmp-xmake](https://github.com/RunThem/cmp-xmake)，[xmake.vim](https://github.com/luzhlon/xmake.vim)，[xmake-sublime](https://github.com/xmake-io/xmake-sublime)，[xmake-vscode](https://github.com/xmake-io/xmake-vscode)，基本都是用xmake命令行进行交互的。本身neovim现在用lua配置，而xmake也是用lua配置，如果可以提供接口的话，集成应该是最方便的，如果没有导出可以直接调用的api的话，命令行交互应该是目前的唯一解了？

1. 从xmake端获取信息，现在xmake show 导出的信息还是针对终端查看的，有很多彩色字符需要额外处理，格式方面很多命令没有对`--json`字段生效
2. neovim中执行xmake命令进行build，run等任务时，可以运行在内置终端中，或者用内置的函数执行，然后从stdout获取输出结果，这时可能需要额外的处理，例如处理颜色控制字符
3. 内置api，最近的2.9.2中增加了--list=apis，初步可以获取所有可用的api了，但还有很多细节需要讨论，主要是类型标注和作用域划分两个
  - 类型标注，可以手动标注，但是可能不准？xmake后续有可能导出参数信息吗？
  - 作用域，在neovim中应该可以用treesitter进行分析，xmake可以辅助分析吗？
 
4. 创建option/target等的多种写法
一种是简单写法
```lua
option("test1", {default = true, showmenu = true, description = "test1 option"})
option("test2", {default = true, showmenu = true})
option("test3", {default = "hello"})
```
另一种配置项用函数调用
```
option("test1", function()
    set_default(true)
    set_showmenu(true)
end)
```
可以简写成table的key都是怎么确定的，都是以set_为前缀的吗，因为我看到在获取api的接口这里，还有add_和before_ after_开头的，像target的字段更多，哪些是简写支持的字段
https://github.com/xmake-io/xmake/blob/fac0b793999fea4bb820fbb4e573ca1a516601a1/xmake/core/project/option.lua#L545C17-L545C21

### 描述可能的解决方案

1. 让更多的输出信息支持`--json`选项，包括xmake 信息，项目信息等
2. 希望提供一个临时开关使得输出为plain，比如一个环境变量或者命令参数，只在当前命令生效，但是不影响全局主题设置
3. xmake是否能提供类型标注和作用域等信息？
4. 求解答

**Comment by waruqi** [comment]
> 让更多的输出信息支持--json选项，包括xmake 信息，项目信息等

这种应该参考 xmake-vscode 的做法，自己需要什么信息，自己搞个 getxxx.lua 的脚本针对性输出，想输出什么格式完全可以自己决定，然后执行 `xmake l getxxx.lua` 就能获取到，里面你想取啥信息，就取啥，更加灵活。。

xmake show 的输出不可能满足所有第三方IDE插件的需求，而且还得依赖 xmake 迭代，这边内部加这种开放式接口，每加一个，或者输出一种新的信息，都需要开 issues 评估，然后排期做，而且有些需求也不一定能通过。另外，xmake 不同版本的输出内容也会变，如果一变，很可能就 break 现有插件支持。。

> 希望提供一个临时开关使得输出为plain，比如一个环境变量或者命令参数，只在当前命令生效，但是不影响全局主题设置

你遇到的这种问题，其他插件基本上都会遇到，同样多参考下现有插件，都有处理。。

https://github.com/xmake-io/xmake-vscode/blob/2b6d88598326cfa27c2ede33b8aded9ac3dc3231/src/xmake.ts#L124

> xmake是否能提供类型标注和作用域等信息？

不能，支持不了

类型信息，目前只有在新的文档框架里面，会对每个 API 标注，可以提取。。但是前提是 先得把所有 API 的文档都标注进去。。

目前没有这个人力做这些事情，如果你感兴趣，可以帮忙来 pr 把新文档框架的 API 类型标注全部补全，然后就可以拉取扫描，提取里面的类型标注，作为数据库进行复用。

https://github.com/xmake-io/xmake-gendoc/blob/03733036923df06ed7b8782a83af7453bbf76a9c/doc/en-us/api/script/builtin_modules/os/is_host.md?plain=1#L4

**Comment by yao-weijie** [comment]
![图片](https://github.com/xmake-io/xmake/assets/36393630/03539473-4757-4af2-936b-bbedcdca4c61)
关于第四点，
可以简写成option('test1', { default=true })
或者写成
```lua
option('test1', function()
  set_default(true)
  on_check(...)
end)
```
这些接口形式有set_ add_ remove_ 还有 on_ after_ before_，哪些是简写支持的呢，只有set_xxx和add_xxx对应的key吗

**Comment by waruqi** [comment]
只支持 set_/add_xxx
