### ISSUE TITLE
v2.9.2 单测运行失败问题

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#5184]
### Xmake 版本

v2.9.2

### 操作系统版本和架构

Linux 720ce3a659a2 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

xmake test 或者 xmake run 运行单测都失败：
![b98e02734edc0ddf99114996c6a6f3ce](https://github.com/xmake-io/xmake/assets/47598093/c3bf4491-53a1-45fc-a5d3-715f7263fe4a)

但是手动执行单测可以成功：
![38165cfbcf6171c7d9cd3b69fb8d178f](https://github.com/xmake-io/xmake/assets/47598093/f041eeea-9000-436b-93e2-4fa1da27909d)

调试时发现运行时的环境变量有 1200+，怀疑是不是这里导致的单测失败？
![255dcda04634617884a38905a445e53d](https://github.com/xmake-io/xmake/assets/47598093/9d896a46-c10c-4661-b8ca-9fdfe99c1da4)

### 期待的结果

能正常运行单测

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
给个可复现的 demo

**Comment by TOMO-CAT** [comment]
> 给个可复现的 demo

https://github.com/TOMO-CAT/xmake-template/tree/main/endless_run_envs

这有一个 demo，在 v2.9.2 版本仅仅 10个 object 文件就已经有大量重复的环境变量了，我们的项目更多中间 target，可能正好越界。

**Comment by waruqi** [comment]
再试试，`xmake update -s dev`

**Comment by TOMO-CAT** [comment]
> 再试试，`xmake update -s dev`
可以了。
