### ISSUE TITLE
add_files("*.c*") wildcard does not work anymore

### ISSUE THREAD

**Issue by charlesseizilles** [xmake-io/xmake#5185]
### Xmake Version

v2.9.1+dev.b127a7d00

### Operating System Version and Architecture

Windows 10.0.19045

### Describe Bug

With this xmake.lua file:
```lua
target("main")
    add_files("*.c*")
```
I get an error.

It works fine when I use `add_files("*.c")`, without the wildcard at the end.

### Expected Behavior

`main.c` should be recognized

### Project Configuration

[xmake.zip](https://github.com/user-attachments/files/15534364/xmake.zip)

### Additional Information and Error Logs

```
> xmake -vD
error: @programdir\core\main.lua:329: @programdir\core\project\target.lua:2204: unknown source file: main.c
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:973]:
    [@programdir\core\project\target.lua:2204]: in function 'sourcebatches'
    [@programdir\modules\private\check\checkers\cuda\devlink.lua:28]: in function '_check_target'
    [@programdir\modules\private\check\checkers\cuda\devlink.lua:47]:
    [@programdir\actions\build\check.lua:73]:
    [@programdir\actions\build\main.lua:141]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [@programdir\actions\build\main.lua:118]: in function 'build_targets'
    [@programdir\actions\build\main.lua:201]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:275]:
    [@programdir\core\base\task.lua:491]: in function 'run'
    [@programdir\core\main.lua:327]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:406]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:973: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:329: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:406: in function <@programdir\core\base\scheduler.lua:399>
```

**Comment by waruqi** [comment]
This is because xmake needs to detect if it is currently a c++ project based on the source file extension. For performance reasons, this is done before matching the list of source files.

Therefore, please make sure that at least one complete c++ source file suffix exists.

**Comment by charlesseizilles** [comment]
I tried to add a `main.cpp` file, and with `set_languages`
```lua
target("main")
    set_languages("cxx11", "c11")
    add_files("main.c*")
```
but I still have the same error. With `set_languages`, xmake shouldn't have to detect if it is a c++ project or not, right?

The only way I could compile is by explicitely adding the files, so I can't use the wildcard.
```lua
target("main")
    set_languages("cxx11", "c11") -- optional
    add_files("main.c")
    add_files("main.cpp")
```

**Comment by charlesseizilles** [comment]
```lua
target("main")
    add_files("main.cpp")
    add_files("main.c*")
```
still returned the error `unknown source file: main.c`

**Comment by SirLynix** [comment]
set_languages doesn't help xmake with language detection, it just steps language version.
You can try `add_rules("c")`

**Comment by charlesseizilles** [comment]
it works if I add both: `add_rules("c++", "c")`
But I'm pretty sure it worked without it at some point before

**Comment by waruqi** [comment]
> ```lua
> target("main")
>     add_files("main.cpp")
>     add_files("main.c*")
> ```
> 
> still returned the error `unknown source file: main.c`

`main.c*` will match `{main.c, main.cpp}` files, but c language kind is not detected. so `main.c` is unknown.

because:

> This is because xmake needs to detect if it is currently a c++ project based on the source file extension. For performance reasons, this is done before matching the list of source files.
> 
> Therefore, please make sure that at least one complete c++ source file suffix exists.

you added main.cpp, but it's only c++ source file, no any c source file.

you should write

```lua
target("main")
    add_files("stub.c", "stub.cpp")
    add_files("main.c*")
```

or 

```lua
target("main")
    add_rules("c", "c++")
    add_files("main.c*")
```

**Comment by charlesseizilles** [comment]
Alright, I have a fix for my problem, then.
Still, don't you think having this to work from the get-go would make using xmake easier?

**Comment by SirLynix** [comment]
Or `add_files("src/*.c", "src/*.cpp")`, fixes the issue and is less error-prone

**Comment by charlesseizilles** [comment]
Indeed, but the error I got with `*.c*` wasn't really self-explainatory, althougth the syntax is correct

**Comment by waruqi** [comment]
> Alright, I have a fix for my problem, then. Still, don't you think having this to work from the get-go would make using xmake easier?

I don't see this as a problem, almost no user would write `.c*` that way. As far as I know, you're still the first.

Also, as I said before, I need to consider the complexity and performance of the implementation as well. It's not necessary to greatly increase complexity and performance loss in order to support a problem that only very few users will encounter.

**Comment by charlesseizilles** [comment]
I understand, thank you for your time!
