### ISSUE TITLE
生成vs工程时把xmake.lua也加进去

### ISSUE THREAD

**Issue by Domain** [xmake-io/xmake#519]
方便编辑，另外，头文件也没有包含在工程里面，编辑起来不方便

**Comment by OpportunityLiu** [comment]
> 头文件也没有包含在工程里面

```lua
add_headerfiles("inc/**/*.hpp")
```

建议更新到 dev 版本，使用 `xmake project -k vsxmake` 生成工程文件

**Comment by Domain** [comment]
> > 头文件也没有包含在工程里面
> 
> ```lua
> add_headerfiles("inc/**/*.hpp")
> ```
> 
> 建议更新到 dev 版本，使用 `xmake project -k vsxmake` 生成工程文件，你说的这些都有了

话说在windows下面怎么编译？我用vs的nmake无法执行

**Comment by OpportunityLiu** [comment]
> 话说在windows下面怎么编译？

用xmake自举编译

**Comment by waruqi** [comment]
> 话说在windows下面怎么编译？我用vs的nmake无法执行

如果只是更新，可以执行xmake update dev来更新到dev版本，或者到releases下载xmake-dev.exe安装

编译xmake自身源码，进入core目录执行xmake来编译就可以

```console
cd core
xmake
```

**Comment by Domain** [comment]
> > 话说在windows下面怎么编译？我用vs的nmake无法执行
> 
> 如果只是更新，可以执行xmake update dev来更新到dev版本，或者到releases下载xmake-dev.exe安装
> 
> 编译xmake自身源码，进入core目录执行xmake来编译就可以
> 
> ```
> cd core
> xmake
> ```

C:\git\xmake\core>xmake
[ 14%]: inserting.release src\luajit\autogen\windows\jit\x64\lj_vm.obj
error: bad argument #1 to 'insert' (table expected, got nil)

**Comment by waruqi** [comment]
什么版本的xmake源码? 以及xmake.exe版本多少？你先更新下dev下源码 以及xmake-dev.exe去编译下试试

**Comment by Domain** [comment]
源码就是最新的，xmake版本是v2.2.7+201906201435

**Comment by waruqi** [comment]
> 源码就是最新的，xmake版本是v2.2.7+201906201435

你找到releases下下载 xmake-dev.exe安装更新下xmake

**Comment by Domain** [comment]
用xmake-dev安装的也报错：
[ 85%]: archiving.release xmake.lib
[ 85%]: compiling.release src\demo\xmake.rc
error: Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
Copyright (C) Microsoft Corporation.  All rights reserved.

src\demo\xmake.rc(27) : error RC2104 : undefined keyword or key name: XM_CONFIG_VERSION

**Comment by waruqi** [comment]
估计 你这也是同一份源码，linux win下同时在编译，你删下 core/xmake.config.h文件，这个是linux/macos下生成的 路径跟win上的不一样 目前会干扰win下编译include xmake.config.h的搜索

**Comment by Domain** [comment]
确实可以了，然后执行xmake install会安装到哪里？

**Comment by waruqi** [comment]
win下我没配置xmake install 。。需要通过nsis加载scripts/installer.nsi做出安装包来安装

**Comment by waruqi** [comment]
你也可以直接双击运行scripts/srcenv.bat来启用本地调试环境 里面可以直接走运行刚编译的xmake.exe以及加载本地lua脚本

**Comment by Domain** [comment]
好的
