### ISSUE TITLE
以分支形式 add_package 时希望更新分支最新 commit

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#5199]
### 你在什么场景下需要该功能？

对于线上场景而言需要 follow 一个依赖库的固定分支，例如 add_requires("libxx master") 以分支的方式引用一个三方库，那么希望 master 分支更新能触发 git update 并重新安装。

试了一下 set_policy("package.install_always", true) 不行，
![946217e0f447a4e58ebf6b295401ba27](https://github.com/xmake-io/xmake/assets/47598093/4b574029-709a-4b93-9a44-7c779b47fae4)
这里如果检测到 source 目录有了就不会再下载了。

### 描述可能的解决方案

当前我是在 on_load 里将 package source 目录直接删了强制触发重新拉取代码，理想情况下最好还是 xmake 提供一个 policy 例如 set_policy("package.download_always", true) 强制检查代码是否更新。这样也不会影响之前的代码库。

### 描述你认为的候选方案

无

### 其他信息

无

**Comment by waruqi** [comment]
不好搞，这种太过于特殊化的需求，`set_policy("package.download_always", true)` 还会导致 tar 包每次也去无意义的重复下载拉取。

如果单独对 git url 的 branch 。。你当前拉取编译通过，如果每次都去更新，很容易导致被 break，我是不建议的，所以暂时不考虑加这种特殊需求。

如果你非要这么搞，就自己在 on_install 里面执行 `os.exec("git pull origin master")` ，每次拉取最新，也就一行代码的事情，跟加 set_policy 也没啥区别，也没必要删 source

**Comment by TOMO-CAT** [comment]
> 不好搞，这种太过于特殊化的需求，`set_policy("package.download_always", true)` 还会导致 tar 包每次也去无意义的重复下载拉取。
> 
> 如果单独对 git url 的 branch 。。你当前拉取编译通过，如果每次都去更新，很容易导致被 break，我是不建议的，所以暂时不考虑加这种特殊需求。
> 
> 如果你非要这么搞，就自己在 on_install 里面执行 `os.exec("git pull origin master")` ，每次拉取最新，也就一行代码的事情，跟加 set_policy 也没啥区别，也没必要删 source

好的，这样应该也可以。
