### ISSUE TITLE
生成的vsxmake工程有警告 

### ISSUE THREAD

**Issue by Domain** [xmake-io/xmake#520]
默认c++的hello，world工程，生成的vsxmake编译有警告：
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include\ostream(707): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc

**Comment by waruqi** [comment]
能正常编译通过么？vs的完整输出 截图给我看下呢？

**Comment by Domain** [comment]
不要Werror当然可以编译通过，输出就这一句话，看起来就是没设置/EHsc参数。
应该和vsxmake工程没什么关系，直接编译也一样：
C:\git\z>xmake build -P . -w zero
[  0%]: compiling.release src\zero\src\zero\version.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include\ostream(257): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
[100%]: archiving.release zero.lib

**Comment by waruqi** [comment]
你version.cpp有用到c++异常了么？如果用到了 以及通过 add_cxflags加一下 /EHsc flag就好了，xmake默认是不会去加的 这里有警告是因为了 开启了-w 来显示编译警告信息

**Comment by Domain** [comment]
确是用到了stl，建议windows下面c++默认加上/EHsc

**Comment by waruqi** [comment]
xmake默认尽量避免添加各种内置flags，提供给用户最大的灵活度，也避免了不必要的flags设置冲突

而且每个用户的需求都是不一样的，如果有些项目就是用了stl 但是不想启用c++异常，默认却启用了，用户想禁用也不方便

你可以自己启用下 或者配置自己常用的rule 来默认启用ehsc

**Comment by Domain** [comment]
我反而觉得默认应该尽量和相关编译器默认配置一致，我用vc编译，那么默认就应该和vc新建工程配置一样，该有的参数都有，不想要默认参数的，提供覆盖的选项

**Comment by waruqi** [comment]
> 我反而觉得默认应该尽量和相关编译器默认配置一致，我用vc编译，那么默认就应该和vc新建工程配置一样，该有的参数都有，不想要默认参数的，提供覆盖的选项

每个用户的需求都不一样，之前还有用户反馈就不该默认加这些flags的呢。

vc只是个ide环境，这些flags是vc默认加的，不是cl.exe编译器加的，xmake跟vc是完全独立，并不相关，不会去对齐vc。。

在xmake.lua里面，提供的binary/static/shared等基础工程的语义下，仅提供最原始基础的必须flags，不会根据某个ide默认加了哪些flags，就去适配。。

这块是xmake里面rule该做的事情，比如 `add_rules("win.sdk.application")`就会默认附带上 win sdk程序所需的默认flags以及links，而`add_rules("win.sdk.mfc.static_app")`则会附带上mfc项目所需的默认flags和links。。

**Comment by Domain** [comment]
好吧，也行
