### ISSUE TITLE
安装支持 xmake 第三方库时无法自动解析 packages、syslinks 等

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#5200]
### Xmake 版本

xmake v2.8.5

### 操作系统版本和架构

Linux 720ce3a659a2 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

```lua
 on_install(function(package)
        import("package.tools.xmake").install(package)
    end)
```
在 package 定义中通过这种方式安装第三方库时，还需要手动在 package 描述域写 add_deps、add_syslinks 等，对于更新频繁的库很不友好

### 期待的结果

希望 xmake 可以在安装的时候自动解析 syslinks 并写入。

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
不考虑，实现复杂度过高，且不可靠。。即使 xmake.lua 维护的项目，内部 packages deps, targets deps, links 随着平台，configs 编译条件 都是可变的，有些甚至还依赖编译器版本，特性支持等，可变性太高。。即使 xmake 自身，也只能在编译时候，才能完全确定下来，提前解析是不准的，而且非常影响性能。

想要包可靠，只能外面的包配置里面，自己根据 configs 还有项目自身 deps 需求，提前确定。。

这个就不要想了，肯定不会支持的。
