### ISSUE TITLE
add_requires自定义路径不能使用内置变量

### ISSUE THREAD

**Issue by zt449569708** [xmake-io/xmake#5207]
### Xmake 版本

v2.9.2+HEAD.6b6557c

### 操作系统版本和架构

Ubuntu 18.04.6 LTS

### 描述问题

自己编译了一个opencv，放到工程目录下，在使用的时候利用add_requires自定义opencv路径，xmake.lua片段如下：
```
add_requires("cmake::OpenCV", {alias = "opencv", system = true,
    configs = {envs = {CMAKE_PREFIX_PATH = "$(projectdir)/opencv-4.6.0/lib64/cmake"}}})
```
如上，在指定路径的时候用到了内置变量$(projectdir)，但是在编译的时候没有生效，导致编译失败。如果不用内置变量，直接使用绝对路径就没有问题，但直接使用绝对路径，每次移动都要去改xmake脚本，比较繁琐。

### 期待的结果

add_requires自定义cmake路径，可以支持使用内置变量

### 工程配置

```
add_requires("cmake::OpenCV", {alias = "opencv", system = true,
    configs = {envs = {CMAKE_PREFIX_PATH = "$(projectdir)/opencv-4.6.0/lib64/cmake"}}})
```

### 附加信息和错误日志

编译日志如下，xmake并没有去我指定的路径查找opencv，而是查找的系统默认安装的opencv。
![1718097792375](https://github.com/xmake-io/xmake/assets/6011216/6a6ab574-253c-4751-9ce8-54e926632078)

**Comment by star-hengxing** [comment]
```
path.join(os.projectdir(), "opencv-4.6.0/lib64/cmake")
```

**Comment by waruqi** [comment]
这里面不支持内置变量，用 os.projectdir()

**Comment by zt449569708** [comment]
> ```
> path.join(os.projectdir(), "opencv-4.6.0/lib64/cmake")
> ```

谢谢

**Comment by zt449569708** [comment]
> 这里面不支持内置变量，用 os.projectdir()


> 这里面不支持内置变量，用 os.projectdir()

谢谢
