### ISSUE TITLE
windows默认powershell颜色下，看不见帮助信息

### ISSUE THREAD

**Issue by Domain** [xmake-io/xmake#521]
如图，actions和plugins看不见了
![image](https://user-images.githubusercontent.com/903197/62819793-cd8e9580-bb8c-11e9-8975-5ea44528efeb.png)

**Comment by waruqi** [comment]
额 刚装的xmake-dev.exe版本？我晚上看看

**Comment by Domain** [comment]
release版本也一样

**Comment by OpportunityLiu** [comment]
teminal的坑点之一，根本没有安全色，建议直接API设置背景色了事

**Comment by waruqi** [comment]
可以通过xmake g --theme切主题配色来改进 这块可以多增加几种内置theme 来对应不同终端的默认背景 我晚上稍微改进下

**Comment by Domain** [comment]
其实我觉得这个帮助信息没必要彩色，很少有帮助信息彩色的

**Comment by waruqi** [comment]
> 其实我觉得这个帮助信息没必要彩色，很少有帮助信息彩色的

每个用户的需求都是不同，就比如我，就喜欢有颜色的。。所以只需要用户自己配置下theme就行了，比如 xmake g --theme=plain  就可以切到非彩色的显示。。回头我对menu的色彩控制 也放置到theme中可配置就行了。。

对于theme是可以自己定制的，用户也是可以自己定制属于自己的各种颜色和显示的。。

**Comment by waruqi** [comment]
我dev上改进了theme，对menu里面的colors也做成了theme配置，你可以执行 xmake update -s dev更新下dev下脚本。。

然后执行 xmake g --theme=plain 启用非色彩主题输出后，你再看下是否可以显示了。。

你也可以放置一个 mytheme/xmake.lua 的自定义 theme 文件到~/.xmake/themes目录下，就可以通过 xmake g --theme=mytheme 切到自己的theme配色。。

**Comment by waruqi** [comment]
@Domain 这个可以了么？

**Comment by Domain** [comment]
xmake --help确实可以了，不过我刚才打错了，打成了xmake help，输出就有点奇怪了：
![image](https://user-images.githubusercontent.com/903197/62836755-17fd3880-bc99-11e9-99b6-d8f2bd23edd8.png)

**Comment by waruqi** [comment]
好了，你再更新下dev试试

**Comment by Domain** [comment]
好了
