### ISSUE TITLE
报错日志文件路径没打全，难以定位问题

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#5214]
### Xmake 版本

v2.9.2

### 操作系统版本和架构

Linux 720ce3a659a2 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

报错信息看着像是文件反序列化失败，但是路径没打全无法定位问题：
![369b71a6686dc4be48495eb855047d83](https://github.com/xmake-io/xmake/assets/47598093/e15aebae-4bcb-437b-bc0b-7284914224db)

### 期待的结果

希望 fatal 日志可以打印出更详尽的信息。

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/blob/33f3078f4dc7f1f804c91a3d0e30f61bd5f75d02/xmake/modules/package/manager/xmake/find_package.lua#L240

这里 print 下文件看下，估计是毁了，然后把这个包删了重装再试试

**Comment by waruqi** [comment]
暂时不清楚，这边没复现过，按理不会写坏，这个就要你这帮忙直接调下源码了。

**Comment by TOMO-CAT** [comment]
> 暂时不清楚，这边没复现过，按理不会写坏，这个就要你这帮忙直接调下源码了。

ok，现场被我删了已经，等复现的时候再看看文件被写成啥样了。

**Comment by TOMO-CAT** [comment]
> 暂时不清楚，这边没复现过，按理不会写坏，这个就要你这帮忙直接调下源码了。

今天发现两起一样的问题：
![image](https://github.com/xmake-io/xmake/assets/47598093/5403cd91-8b31-4893-94cd-8d095f389efb)
我把文件下载下来了，发现最后多了一个右花括号？ 能在每次 dump 的时候做一次全量覆盖吗，而且在我们机器上这个目录会一直增加，因为每次 jenkins 流水线都会创建一个 workspace，能禁用 reference.txt 这个功能吗？

**Comment by TOMO-CAT** [comment]
![image](https://github.com/xmake-io/xmake/assets/47598093/f0ef5cb2-ec46-4a21-9cd1-2bdce3a4cf0a)

**Comment by waruqi** [comment]
按理是覆盖的，这边正常，暂时复现不了。。这个没法禁用，只有找到根本原因修掉。

**Comment by TOMO-CAT** [comment]
就算有复现问题的环境，也没法还原当时为啥写花了，这只能从代码层面上分析了

**Comment by waruqi** [comment]
可能是你这里 jenkins 同时开了多个工程，并发安装一个包，导致多个 xmake 子进程同时去写一个包的配置，互相覆盖了。

**Comment by TOMO-CAT** [comment]
> 可能是你这里 jenkins 同时开了多个工程，并发安装一个包，导致多个 xmake 子进程同时去写一个包的配置，互相覆盖了。
> 
> 我看到 refernces.txt 里，就是有 N 个工程引用到了。

jenkins 每个流水线都会创建一个独立的文件夹，编译完就删了，所以这个目录会一直增加，不能给这里加个并发保护吗？

**Comment by waruqi** [comment]
目前包下载和安装会锁，但是这个是在 fetch 阶段去读写的，这块暂时没锁

**Comment by TOMO-CAT** [comment]
> 目前包下载和安装会锁，但是这个是在 fetch 阶段去读写的，这块暂时没锁

我感觉是我们的编译任务数比较高，所以这个问题基本上必现，有考虑处理一下 io.save 的并发问题吗

**Comment by waruqi** [comment]
跟 io.save 无关，是包的并发读写问题。。我这里可以加锁规避部分。。但是我还是不建议你们这么搞。。即使不会出错，同时并发安装一个包，也会导致等锁，反而更慢。

**Comment by TOMO-CAT** [comment]
> 跟 io.save 无关，是包的并发读写问题。。我这里可以加锁规避部分。。但是我还是不建议你们这么搞。。即使不会出错，同时并发安装一个包，也会导致等锁，反而更慢。

包的并发读写在我们这还是比较正常的，jenkins 这种编译物理机不可能只跑一个编译任务的，多个编译任务可能需要安装同一个包。不过之前看源码 package install 的时候本来就是加锁的吧？那我可以通过重写 on_fetch 绕过这个 references.txt 的读写吗？

**Comment by waruqi** [comment]
> > 跟 io.save 无关，是包的并发读写问题。。我这里可以加锁规避部分。。但是我还是不建议你们这么搞。。即使不会出错，同时并发安装一个包，也会导致等锁，反而更慢。
> 
> 包的并发读写在我们这还是比较正常的，jenkins 这种编译物理机不可能只跑一个编译任务的，多个编译任务可能需要安装同一个包。不过之前看源码 package install 的时候本来就是加锁的吧？

我刚不是说了么，install 有锁，fetch 没锁，fetch 时候也会读写包文件

> 那我可以通过重写 on_fetch 绕过这个 references.txt 的读写吗？

内部 fetch ，绕不过，而且即使你绕过了，也没用，刚说了治标不治本，又不止读写这一个文件，有并发冲突，各种包文件都有可能毁，你光绕过这一个有啥用。。



我刚 fetch 也把锁加上了，按理应该不会再同时访问到一个包，但是多个进程并发安装包，遇到冲突，避免不了卡着等其他进程安装完包。反正我是不建议你们这么玩。编译任务可以并发，但是包安装，没必要并发装

**Comment by TOMO-CAT** [comment]
> 编译任务可以并发，但是包安装，没必要并发装

单个编译任务就是直接 xmake -bvD，不同 jenkins 任务之间的隔离不太好做，我们研究下怎么避免 package 的并发安装吧。

**Comment by TOMO-CAT** [comment]
> 我刚 fetch 也把锁加上了，按理应该不会再同时访问到一个包，但是多个进程并发安装包，遇到冲突，避免不了卡着等其他进程安装完包。反正我是不建议你们这么玩。编译任务可以并发，但是包安装，没必要并发装

刚才想了一下，这里应该不是并发安装同一个包的问题，而是多个编译任务同时引用了同一个 package，在编译开始阶段 find package 需要修改该 package 的 references.txt。不知道你这里的改动能否修复这个问题。

**Comment by waruqi** [comment]
> > 我刚 fetch 也把锁加上了，按理应该不会再同时访问到一个包，但是多个进程并发安装包，遇到冲突，避免不了卡着等其他进程安装完包。反正我是不建议你们这么玩。编译任务可以并发，但是包安装，没必要并发装
> 
> 刚才想了一下，这里应该不是并发安装同一个包的问题，而是多个编译任务同时引用了同一个 package，在编译开始阶段 find package 需要修改该 package 的 references.txt。不知道你这里的改动能否修复这个问题。

fetch == find

**Comment by TOMO-CAT** [comment]
> fetch == find

那我这边更新完再观察下

**Comment by waruqi** [comment]
还有问题么
