### ISSUE TITLE
关于 xmake project -k vsxmake  先前生成vs工程文件不会自动更新

### ISSUE THREAD

**Issue by iKunCai** [xmake-io/xmake#5216]
### 你在什么场景下需要该功能？

当我在lua里面 举个例子 add_requires("glog") add_packages("glog")
如果我不重复执行  xmake project -k vsxmake  
导致找不到头文件。
但是当我运行 xmake project -k vsxmake  重新生成工程文件后 就可以了。这个是技术原因 还是使用不对..

![图片_20240614142845](https://github.com/xmake-io/xmake/assets/22653841/15cda1b1-8411-444e-9fa6-ea128749a99a)

### 描述可能的解决方案

可否跟vcpkg一样集成在msbuild 自动刷新包含目录

**Comment by star-hengxing** [comment]
https://xmake.io/#/manual/custom_rule?id=pluginvsxmakeautoupdate

**Comment by iKunCai** [comment]
> https://xmake.io/#/manual/custom_rule?id=pluginvsxmakeautoupdate

谢谢。。。抱歉没看到这个。
