### ISSUE TITLE
写在includes包含文件里面的设置不起作用

### ISSUE THREAD

**Issue by Domain** [xmake-io/xmake#522]
我不知道是不是设计就是这样，我想把配置文件分成几个：
主xmake.lua:
`includes("cfg/platform.lua")`
然后platform.lua:
`if is_plat("windows") then
    includes("windows.lua")
end`
最后windows.lua:
`add_cxxflags("/EHsc")`
可是最后这个设置不起作用，直接写在xmake.lua里面没问题。
不知道要实现这样的功能应该怎么写。

**Comment by waruqi** [comment]
目前includes的设计是tree继承，include的子lua里面的子target，可以继承parent里面的所有root域设置，但是反向include lua里面的所有设置导入到parent是不支持的

说白了，目前include是没法导入子lua里面的root域设置，因为子lua里面root域下的所有设置，只对子target可见，目前的设计就是这样的

不过target定义是可以重入的，你可以在windows.lua里面重新进去target去附加特定设置

比如

```lua
target("test")
    add_files("xxx.c")

includes("windows.lua") 
```

windows.lua:

```lua
target("test") -- 重新进入
     add_cxxflags("/EHsc")
```

还有一种方式就是在子lua里面用function wrap下所有特定设置，include虽然不能导入子target的root设置，但是可以导入全局function

```lua
includes("windows.lua") 
target("test")
    add_files("xxx.c")
    add_flags() -- 调用子lua里面的func接口来设置特定flags
```

windows.lua

```lua
function add_flags()
     add_cxxflags("/EHsc")
end
```

**Comment by waruqi** [comment]
关于这块 后面我会完善下文档，详细说明下includes的使用和继承导入关系

**Comment by Domain** [comment]
嗯，理解，或者能有办法让require起作用吗？

**Comment by waruqi** [comment]
> 嗯，理解，或者能有办法让require起作用吗？

add_requires是全局接口，不是特定针对target的。你在子lua里面同样可以通过func 去wrap下，在parent里面使用

```lua
includes("requires.lua")

add_common_requires() 

target("test")
    add_files("xxx.c")
    add_packages("xxxx")
```

requires.lua

```lua
function add_common_requires()
    add_requires("xxxx")
    add_requires("xxxx")
    add_requires("xxxx")
end
```

**Comment by waruqi** [comment]
不过我一般建议直接在根lua里面处理通用设置，包括相关不同platform的处理，而在子lua里面，描述target，去继承根域的设置。。

根 xmake.lua

```lua
if is_plat("windows") then
    add_cxxflags("xxxx")
elif is_plat("linux") then
    add_cxxflags("xxxx")
end

add_requires("xxx")
add_requires("xxx")
add_requires("xxx")

-- add common flags
add_cflags("xxx")

-- 实际target的定义都放置到子lua里面去继承根lua的设置
includes("src/xxx")
```

**Comment by Domain** [comment]
> > 嗯，理解，或者能有办法让require起作用吗？
> 
> add_requires是全局接口，不是特定针对target的。你在子lua里面同样可以通过func 去wrap下，在parent里面使用
> 
> ```lua
> includes("requires.lua")
> 
> add_common_requires() 
> 
> target("test")
>     add_files("xxx.c")
>     add_packages("xxxx")
> ```
> 
> requires.lua
> 
> ```lua
> function add_common_requires()
>     add_requires("xxxx")
>     add_requires("xxxx")
>     add_requires("xxxx")
> end
> ```

我意思是说lua自带的require，现在require("windoes")会报错

**Comment by waruqi** [comment]
自带的require我禁用了 xmake.lua外层属于描述域，限制做个各种复杂的操作，仅仅用于做些配置相关的操作，所以为了简化，也避免滥用，我是禁用的

在脚本域 你可以用import来代替require

**Comment by Domain** [comment]
理解你的担心，不过我觉得，用lua作为配置文件，一个很大的优势就是可以用lua本身的功能，比其他Makefile之类的强大很多，如果做了过多限制，感觉得不偿失

**Comment by waruqi** [comment]
限制是必须的，xmake.lua分上层描述域 以及脚本域，描述域仅仅做简单的配置描述，简化工程配置，用于满足80%的简单配置场景，即使对于不会lua的人，也可以很快上手，并且保证可读性极强。。

虽然描述域做了很多限制，仅仅是为了简化一些新手的使用，对于高端用户，xmake提供了脚本域，比如on_load/after_build里面进行更加复杂的脚本配置处理，用户可以在里面实现lua能够提供的所有功能 虽然没有require但有更强大的import接口，更加方便模块化导入

通过描述域 和 脚本域的 分离，简化了80%常用场景

**Comment by waruqi** [comment]
说白了 描述域  只是被设计为基于lua的 常规配置，你可以把它当成 不是lua的配置文件，所以小白用户也能快速上手

```lua
target("test")
    set_kind("binary")
    add_files("src/*.c")
```

对于一般的用户，就把这个当成普通的非lua配置文件就可以了，甚至可以 

```lua
target "test"
    set_kind "binary" 
    add_files "src/*.c"
```

xmake再次基础上，提供lua的一些常用 if for 等分支，循环语法支持，使得这些配置起来更加具有灵活度。。

```lua
target("test")
    set_kind("binary")
    add_files("src/*.c")
    if is_mode("debug") then
        -- 
    end
```

但需要注意，描述域不是纯粹的lua脚本，内部做了限制，这个限制刚说了，目的是为了简化工程描述

你如果要写复杂的需求，描述域满足不了，可以在脚本域配置，这是对于一些已经对xmake上手的中高端用户提供的功能，可以做各种更灵活的定制化需求

```lua
target("test")
    set_kind("binary")
    add_files("src/*.c")
    on_load(function (target)
        import("net.http")  -- 导入xmake提供的各种内置模块来使用
        import("xxx")  -- 导入当前xmake.lua所在目录的 用户lua脚本模块，来使用
        if is_plat("windows") then
             target:add("cxflags", "xxx")
        end
    end)
```

**Comment by waruqi** [comment]
甚至更复杂点，如果on_load的实现超级复杂，可以直接独立到单独的lua文件中去维护

```lua
target("test")
    set_kind("binary")
    add_files("src/*.c")
    on_load("xxxx.load")  -- 导入当前xmake.lua所在目录xxxx/load.lua脚本，调用里面main入口，进行更灵活的lua配置
```

**Comment by Domain** [comment]
好的，我再看看怎么用

**Comment by Domain** [comment]
呃，还有问题，好像includes包含的文件只有第一层的函数能够看到，就是以下关系：
windows.lua --> platform.lua --> xmake.lua
只有定义在platform.lua的函数可以用，定义在windows.lua的函数找不到，这也是设计就这样吗？有没有global includes之类的操作？

**Comment by waruqi** [comment]
恩 目前就是这样的 每层子lua都有做域隔离 避免嵌套太深 作用域污染 变量冲突 导致最后很难排查问题

**Comment by Domain** [comment]
加一个includes("platform.lua", {global=true})，允许嵌套，会灵活很多

**Comment by waruqi** [comment]
includes后期可以考虑改进，通过参数来调整includes行为，不过这个版本就不考虑了，我处理掉一些残留问题，近期会发个版

等下个版本我有时间再扩展下

**Comment by waruqi** [comment]
想了下，暂时不考虑做子域merge，都之后如果需求量大  再重新评估。
