### ISSUE TITLE
MSVC, CMake packages with clang toolchain do not build

### ISSUE THREAD

**Issue by Raildex** [xmake-io/xmake#5222]
### Xmake Version

v2.9.2+dev.417313e29

### Operating System Version and Architecture

Windows 11, Visual Studio 2022

### Describe Bug

switch to clang-cl on msvc with `xmake f --toolchain=clang` results in compilation errors of CMake packages.

### Expected Behavior

.

### Project Configuration

.

### Additional Information and Error Logs

[xmake.log](https://github.com/user-attachments/files/15862712/xmake.log)
[xmaketest.zip](https://github.com/user-attachments/files/15864437/xmaketest.zip)

**Comment by waruqi** [comment]
please provide your project example

**Comment by Raildex** [comment]
> please provide your project example

[xmaketest.zip](https://github.com/user-attachments/files/15864423/xmaketest.zip)

running `xmake f --toolchain=clang` will yield in errors on windows

**Comment by waruqi** [comment]
wait this patch https://github.com/xmake-io/xmake-repo/pull/4386

**Comment by waruqi** [comment]
try it again.

```console
xrepo update-repo
```
