### ISSUE TITLE
add_linkorders 循环依赖报错信息不够

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#5228]
### Xmake 版本

v2.9.2

### 操作系统版本和架构

Linux 720ce3a659a2 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

add_linkorders 报 warning 提示存在循环依赖，但是从报错信息上没看出来任何信息
![c0c9eff04a5711212fae2683bf4b727e](https://github.com/xmake-io/xmake/assets/47598093/add93a08-bfd8-4422-ae07-bbb373075ef3)

### 期待的结果

提示具体的循环依赖内容

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
这不提示的很明显了么。。根据 add_links/add_packages 全局搜下对应的配置地方么。。`xmake -v` 或者 `xmake show target` 等稍微看看 不就能定位了么。

**Comment by TOMO-CAT** [comment]
> ### Xmake 版本
> v2.9.2
> 
> ### 操作系统版本和架构
> Linux 720ce3a659a2 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
> 
> ### 描述问题
> add_linkorders 报 warning 提示存在循环依赖，但是从报错信息上没看出来任何信息 ![c0c9eff04a5711212fae2683bf4b727e](https://private-user-images.githubusercontent.com/47598093/340625490-add93a08-bfd8-4422-ae07-bbb373075ef3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTYyNjgsIm5iZiI6MTcxODcxNTk2OCwicGF0aCI6Ii80NzU5ODA5My8zNDA2MjU0OTAtYWRkOTNhMDgtYmZkOC00NDIyLWFlMDctYmJiMzczMDc1ZWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDEzMDYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzOGE5YzgwMTMwZDFkYWJiZTFiNGJmMjUxNjg2NzA1ODE4OWEyODRiODBmNTNhOTExNWEwNjFhZGZlMThiYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1oWn127Aw__8cfcaN7uB_5Ddx9Fosc0F4q4LzNdJDk8)
> 
> ### 期待的结果
> 提示具体的循环依赖内容
> 
> ### 工程配置
> 无
> 
> ### 附加信息和错误日志
> 无



> 这不提示的很明显了么。。根据 add_links/add_packages 全局搜下对应的配置地方么。。`xmake -v` 或者 `xmake show target` 等稍微看看 不就能定位了么。

这是我自己配置的 add_linkorders，从报错只能看出来是个子集，哪看出来的循环依赖？
![image](https://github.com/xmake-io/xmake/assets/47598093/abb2fe67-ed08-47c4-b72d-f84f779aad26)

**Comment by waruqi** [comment]
还要结合 add_links , target deps 和 packages links 里面的初始顺序来看。。循环依赖不单单只是分析 add_linkorders 。。是分析根据 add_linkorders + add_links/add_packages 一起调整后的顺序
