### ISSUE TITLE
客户环境使用xmake会卡住

### ISSUE THREAD

**Issue by Dozingfiretruck** [xmake-io/xmake#5237]
### Xmake 版本

2.9.2

### 操作系统版本和架构

win10

### 描述问题

客户环境使用xmake会卡在打印检测vs版本之后，不会进行下去，环境是win10家庭版 版本号 22H2 操作系统内部版本19045.4529
不知道如何排查

### 期待的结果

正常执行

### 工程配置

https://gitee.com/openLuat/luatos-soc-2024

### 附加信息和错误日志

<img width="744" alt="企业微信截图_17188545269673" src="https://github.com/xmake-io/xmake/assets/24759100/9a0d1449-c43b-4752-b2a1-a7e00eb78644">

**Comment by Dozingfiretruck** [comment]
客户可以提供远程环境进行调试

**Comment by waruqi** [comment]
按这个操作下，看看 logs 和栈 https://github.com/xmake-io/xmake/issues/2033

**Comment by Dozingfiretruck** [comment]
> 按这个操作下，看看 logs 和栈 #2033

![image](https://github.com/xmake-io/xmake/assets/24759100/cd69a4a0-41fa-427f-9177-352f2da3f604)
也卡主

**Comment by Dozingfiretruck** [comment]
> > 按这个操作下，看看 logs 和栈 #2033
> 
> ![image](https://private-user-images.githubusercontent.com/24759100/341347170-cd69a4a0-41fa-427f-9177-352f2da3f604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzQ1NDUsIm5iZiI6MTcxODg3NDI0NSwicGF0aCI6Ii8yNDc1OTEwMC8zNDEzNDcxNzAtY2Q2OWE0YTAtNDFmYS00MjdmLTkxNzctMzUyZjJkYTNmNjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA5MDQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYjZiZDM5OTNmYTg1NTIwZjM3MjZlZjU1MGFhZWI1ZDMzYTVhMGI0ZDdkODQ2MzAzZmE5YmUyY2RhYjc3ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C91T6B2UUr328f_9X61WayJOVIqhPeGciRIxH8aMnp8) 也卡主

过段时间出现 
![image](https://github.com/xmake-io/xmake/assets/24759100/d10b6494-8161-4444-bf13-47ee31a16b16)
keneng 可能是这个问题？

**Comment by waruqi** [comment]
> 按这个操作下，看看 logs 和栈 #2033

按这个操作，给栈

**Comment by waruqi** [comment]
> > Bot detected the issue body's language is not English, translate it automatically.
> 
> > > 按这个操作下，看看 logs 和栈 #2033
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/24759100/341347170-cd69a4a0-41fa-427f-9177-352f2da3f604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ey Jpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSISImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzQ1NDUsIm5iZiI6MTcxODg3NDI0NSwicGF0aCI6Ii8yNDc1 OTEwMC8zNDEzNDcxNzAtY2Q2OWE0YTAtNDFmYS00MjdmLTkxNzctMzUyZjJkYTNmNjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09 EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA5MDQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbm F0dXJlPWNjYjZiZDM5OTNmYTg1NTIwZjM3MjZlZjU1MGFhZWI1ZDMzYTVhMGI0ZDdkODQ2MzAzZmE5YmUyY2RhYjc3ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lk PTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C91T6B2UUr328f_9X61WayJOVIqhPeGciRIxH8aMnp8) 也卡主
> 
> 过段时间出现 ![image](https://private-user-images.githubusercontent.com/24759100/341355593-d10b6494-8161-4444-bf13-47ee31a16b16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzYwMDksIm5iZiI6MTcxODg3NTcwOSwicGF0aCI6Ii8yNDc1OTEwMC8zNDEzNTU1OTMtZDEwYjY0OTQtODE2MS00NDQ0LWJmMTMtNDdlZTMxYTE2YjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA5MjgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMTY2NzBhNWM5MzU2ZDM1ZTE0MDA0NjZjZDE4MTVlYzJkYThkMzQwMmIxYjU2OTFjZTE0YzA3MjdiZDc4ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pxODXy-tUWrmMJd_sA2T6dhiZIo0sAH8GesgBpNFR7Y) keneng 可能是这个问题？

不知道，你可以自己确认下，删了 gzip.exe 验证下 不就好了，或者去掉 gzip 对应的嗯path

**Comment by Dozingfiretruck** [comment]
> > > Bot detected the issue body's language is not English, translate it automatically.
> > 
> > 
> > > > 按这个操作下，看看 logs 和栈 #2033
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/24759100/341347170-cd69a4a0-41fa-427f-9177-352f2da3f604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ey Jpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSISImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzQ1NDUsIm5iZiI6MTcxODg3NDI0NSwicGF0aCI6Ii8yNDc1 OTEwMC8zNDEzNDcxNzAtY2Q2OWE0YTAtNDFmYS00MjdmLTkxNzctMzUyZjJkYTNmNjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09 EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA5MDQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbm F0dXJlPWNjYjZiZDM5OTNmYTg1NTIwZjM3MjZlZjU1MGFhZWI1ZDMzYTVhMGI0ZDdkODQ2MzAzZmE5YmUyY2RhYjc3ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lk PTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C91T6B2UUr328f_9X61WayJOVIqhPeGciRIxH8aMnp8) 也卡主
> > 
> > 
> > 过段时间出现 ![image](https://private-user-images.githubusercontent.com/24759100/341355593-d10b6494-8161-4444-bf13-47ee31a16b16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzYwMDksIm5iZiI6MTcxODg3NTcwOSwicGF0aCI6Ii8yNDc1OTEwMC8zNDEzNTU1OTMtZDEwYjY0OTQtODE2MS00NDQ0LWJmMTMtNDdlZTMxYTE2YjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA5MjgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMTY2NzBhNWM5MzU2ZDM1ZTE0MDA0NjZjZDE4MTVlYzJkYThkMzQwMmIxYjU2OTFjZTE0YzA3MjdiZDc4ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pxODXy-tUWrmMJd_sA2T6dhiZIo0sAH8GesgBpNFR7Y) keneng 可能是这个问题？
> 
> 不知道，你可以自己确认下，删了 gzip.exe 验证下 不就好了，或者去掉 gzip 对应的嗯path

目前看是因为gzip导致的卡住
