### ISSUE TITLE
is_os和is_plat判断termux为linux而不是android

### ISSUE THREAD

**Issue by Domain** [xmake-io/xmake#524]
应该算是android吧

**Comment by waruqi** [comment]
目前`is_plat("android")` 仅用于判断 基于常规ndk构建环境下android平台，而termux下直接通过clang在手机host上编译，只能算是linux环境

如果吧这个也算成`is_plat("android")`，xmake在termux上编译的时候会去调用android ndk相关工具链编译，反而会出问题。。

如果你非要判断termux平台作为android，你可以自己配下自定义平台，只需要：

```console
xmake f -p termux
xmake
```

xmake.lua

```lua
if is_plat("termux", "android") then
    -- 里面作为android来配置相关参数
end
```

**Comment by waruqi** [comment]
或者你可以在on_load里面，自己调用完整 uname -a 去探测android，来设置相关配置

```lua
target("test")
    on_load(function (target)
        local info = (try { function () return os.iorun("uname -a") end} or ""):trim()
        if info:find("Android", 1, true) then
             target:add("cxflags", "xxxxxx")
        end
    end)
```

**Comment by Domain** [comment]
嗯，是可以，不过每个项目都要这样比较麻烦，是否可以考虑增加一个变量$(distr)，标识linux的发行版，termux就标识为termux

**Comment by waruqi** [comment]
暂时不考虑，`xmake f -p termux` + `is_plat("termux", "android")` 我也没觉有多麻烦。。

**Comment by Domain** [comment]
主要是希望别人代码拉下来执行xmake就可以了，而不需要还要记住在不同平台还要用不同的命令，这样用跨平台的构建工具意义就变弱了

**Comment by waruqi** [comment]
那就自己配置个distr的选项就行了，没必要什么都放置到xmake内置变量里面去，每个用户的需求都不同，如果都往xmake内置里面提供，那就太臃肿了，也不好维护

```lua
option("distr")
    set_default("$(host)")
    set_showmenu(true)
    before_check(function (option)
        local info = (try { function () return os.iorun("uname -a") end} or ""):trim()
        if not info:find("Android", 1, true) then
            option:set_value("termux")
        end
    end)

if is_config("distr", "termux", "android") then
    -- host is android
    add_cxflags("xxx")
end
```

默认 distr 选项 采用 os.host()里面的值，针对termux，会做进一步探测，默认自动探测只需要执行xmake就行了

如果探测不对，用户也有机会强制切distr, `xmake f --distr=termux`

这样也没怎么麻烦，像distr等通用的选项，你可以放置到你includes的platform.lua里面去，每个项目复用就行了。。

**Comment by Domain** [comment]
好的，谢谢你的建议
