### ISSUE TITLE
无法链接qt库

### ISSUE THREAD

**Issue by aiyolo** [xmake-io/xmake#5241]
### Xmake 版本

2，9，2

### 操作系统版本和架构

Windows 11

### 描述问题

链接qt库时，PrintSupport库和network库链接不上

### 期待的结果

如何正确链接除widget,core,gui之外的库？

### 工程配置

add_rules("mode.debug", "mode.release")

target("myproject")
    add_rules("qt.widgetapp")
    add_headerfiles("src/*.h")
    add_files("src/*.cpp")
    add_files("src/mainwindow.ui")
    -- add files with Q_OBJECT meta (only for qt.moc)
    add_files("src/mainwindow.h")

### 附加信息和错误日志

提示network的库链接不上

**Comment by star-hengxing** [comment]
https://xmake.io/#/guide/project_examples?id=static-library

`add_frameworks("QtNetwork")`

**Comment by aiyolo** [comment]
> https://xmake.io/#/guide/project_examples?id=static-library
> 
> `add_frameworks("QtNetwork")`

请问怎么能查看add_framework 支持的所有参数？

**Comment by star-hengxing** [comment]
> > https://xmake.io/#/guide/project_examples?id=static-library
> > `add_frameworks("QtNetwork")`
> 
> 请问怎么能查看add_framework 支持的所有参数？

自己查 qt 文档有哪些库

**Comment by aiyolo** [comment]
> > > https://xmake.io/#/guide/project_examples?id=static-library
> > > `add_frameworks("QtNetwork")`
> > 
> > 
> > 请问怎么能查看add_framework 支持的所有参数？
> 
> 自己查 qt 文档有哪些库

明白了，谢谢，比如我想链接PrintSupport库的话，只需要使用`add_frameworks("QtPrintSupport")`
