### ISSUE TITLE
PowerShell installation script will fail when the TMP path contains fields in 8.3 format

### ISSUE THREAD

**Issue by Patrick-Ze** [xmake-io/xmake#5255]
### Xmake 版本

n.a.

### 操作系统版本和架构

Version 22H2 (OS Build 19045.4529)

### 描述问题

https://xmake.io/#/guide/installation 提供的一键安装脚本
`Invoke-Expression (Invoke-Webrequest 'https://xmake.io/psget.text' -UseBasicParsing).Content`

当`TMP`路径中包含8.3格式的字段时（例如用户名较长）
`C:\Users\USER~1.NAM`
通过环境变量获取的临时文件夹路径会导致安装失败，原因是`Remove-Item`和`Set-Location`不支持这样的路径(见 https://github.com/PowerShell/PowerShell/issues/7760#issue-359155177 )。
安装脚本会在`Remove-Item $outfile`这句失败
```
            Write-Output $pid | Out-File -FilePath $outfile
            Remove-Item $outfile
```

### 期待的结果

xmake.io的一键安装脚本应当能正常完成安装

### 工程配置

无需配置即可复现

### 附加信息和错误日志

```log
> Invoke-Expression (Invoke-Webrequest 'https://xmake.io/psget.text' -UseBasicParsing).Content
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____| getter


Cannot write to temp path
Please set environment var "TMP" to another path
Remove-Item:
Line |
  78 |              Remove-Item $outfile
     |              ~~~~~~~~~~~~~~~~~~~~
     | An object at the specified path C:\Users\USER~1.NAM does not exist.
```

**Comment by waruqi** [comment]
这种直接提个 pr 过来修下就好

**Comment by Patrick-Ze** [comment]
> 这种直接提个 pr 过来修下就好

是已经在提PR了，发现guideline需要先提issue才提了这个

**Comment by waruqi** [comment]
merged, thanks
