### ISSUE TITLE
xrepo 命令一直无响应

### ISSUE THREAD

**Issue by L-Super** [xmake-io/xmake#5258]
### Xmake 版本

v2.9.3+20240624

### 操作系统版本和架构

macOS 14.4.1 

### 描述问题

使用brew安装的xmake，使用`xrepo`命令时，无响应：
```bash
xrepo info miniz
xmake require --search miniz
```
查询了仓库:https://xrepo.xmake.io/#/packages/macosx?id=miniz-macosx，是存在miniz库的，不知道是网络问题，还是我的自身问题。

### 期待的结果

xrepo运行正常，并能下载依赖包

### 工程配置

```
add_rules("mode.debug", "mode.release")

target("xmake-demo")
    set_kind("binary")
    add_files("src/*.cpp")
```

### 附加信息和错误日志

均无输出
```
xrepo install miniz -vD
xmake require --search miniz -vD
```

**Comment by L-Super** [comment]
> 可以参考这个 看下栈。。 #2033

输出如下：
```
xmake require --search zlib
<subprocess: sysctl>: /usr/sbin/sysctl -n machdep.cpu.vendor machdep.cpu.model machdep.cpu.family machdep.cpu.features machdep.cpu.brand_string
<subprocess: which>: which ping
<subprocess: ping>: /Applications/Yunshu.app/Contents/Public/ping -c 1 -t 1 127.0.0.1
^C[xmake]: [engine]: 1000
stack traceback:
	[C]: in function 'base/io.poller_wait'
	@programdir/core/base/poller.lua:115: in function 'base/poller.wait'
	@programdir/core/base/scheduler.lua:1063: in function 'base/scheduler.runloop'
	@programdir/core/main.lua:333: in function 'main.entry'
	(...tail calls...)
[1]    7243 segmentation fault  xmake require --search zlib
```

**Comment by waruqi** [comment]
看下 `/Applications/Yunshu.app/Contents/Public/ping -c 1 -t 1 127.0.0.1` 会不会卡

**Comment by L-Super** [comment]
> 看下 `/Applications/Yunshu.app/Contents/Public/ping -c 1 -t 1 127.0.0.1` 会不会卡

所以是这个软件影响了？奇怪的是，这个软件并没有运行
```
/Applications/Yunshu.app/Contents/Public/ping -c 1 -t 1 127.0.0.1
failed to lookup address information: nodename nor servname provided, or not known
PING 127.0.0.1 (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=1 ms

--- 127.0.0.1 ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.053/0.053/0.053/0.000 ms
^C%                                                                                                                       
```

**Comment by waruqi** [comment]
会去从 `which ping` 返回的结果找 ping 。。它返回了这个，就用了这个。。。反正是这个 ping 有问题。。

**Comment by L-Super** [comment]
> 会去从 `which ping` 返回的结果找 ping 。。它返回了这个，就用了这个。。。反正是这个 ping 有问题。。

用`whereis`会不会更好一些

**Comment by waruqi** [comment]
> > 会去从 `which ping` 返回的结果找 ping 。。它返回了这个，就用了这个。。。反正是这个 ping 有问题。。
> 
> 用`whereis`会不会更好一些

跟用哪个没关系，即使 whereis 更好，也不会弃用 which ，只会增加一种查找方式 去辅助改进结果。。
但是不管用哪种，都不能保证它返回的 ping 路径一定是对的，一定没问题，即使你这通过 whereis 绕过了，说不定其他用户也还会遇到类似的。

这种用户自身环境问题，只有你这自己处理下。。

**Comment by L-Super** [comment]
> > > 会去从 `which ping` 返回的结果找 ping 。。它返回了这个，就用了这个。。。反正是这个 ping 有问题。。
> > 
> > 
> > 用`whereis`会不会更好一些
> 
> 跟用哪个没关系，即使 whereis 更好，也不会弃用 which ，只会增加一种查找方式 去辅助改进结果。。 但是不管用哪种，都不能保证它返回的 ping 路径一定是对的，一定没问题，即使你这通过 whereis 绕过了，说不定其他用户也还会遇到类似的。
> 
> 这种用户自身环境问题，只有你这自己处理下。。

是否可以加一个超时，不然会无意义的无限等待

**Comment by waruqi** [comment]
> > > > 会去从 `which ping` 返回的结果找 ping 。。它返回了这个，就用了这个。。。反正是这个 ping 有问题。。
> > > 
> > > 
> > > 用`whereis`会不会更好一些
> > 
> > 
> > 跟用哪个没关系，即使 whereis 更好，也不会弃用 which ，只会增加一种查找方式 去辅助改进结果。。 但是不管用哪种，都不能保证它返回的 ping 路径一定是对的，一定没问题，即使你这通过 whereis 绕过了，说不定其他用户也还会遇到类似的。
> > 这种用户自身环境问题，只有你这自己处理下。。
> 
> 是否可以加一个超时，不然会无意义的无限等待

参数本身 `-t 1` 就是设置了超时 最多等 1s ，但是这个特殊的 ping 老卡着，我也没办法。。

```
ping -c 1 -t 1 127.0.0.1
```

**Comment by waruqi** [comment]
这种你自己处理下，让 which 找对 ping 就行了。。用户环境问题
