### ISSUE TITLE
bash命令行下的多目标补全失败 & 输入错误目标名不报错

### ISSUE THREAD

**Issue by JackLin00** [xmake-io/xmake#5259]
### Xmake 版本

2.9.3

### 操作系统版本和架构

Ubuntu 20.04

### 描述问题

1.[bash命令行]当仓库上存在多个目标的时候，xmake build 无法根据首字母进行补全，当前只会提示所有目标
2.当输入 xmake build [一个不存在目标名]，不会报错
上面两个问题在旧版本 2.6,7 上是不存在的

### 期待的结果

1.[bash命令行]能够正确地进行补全
2.输入不存在的目标名的时候，能够报错

### 工程配置

如附件
[test_xmake_2.zip](https://github.com/user-attachments/files/15986806/test_xmake_2.zip)

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
暂时没空看这个，可以直接来个 pr 过来

**Comment by JackLin00** [comment]
补全问题我周末提一个 pr 过来，但是在查看输入错误目标名不报错的问题的时候，发现里面的逻辑链很深，不知道怎么解决，而且在查看的过程中发现里面有 xmake build -g [组名] 这个功能也是不行，建议重新梳理一下 build 的流程，我感觉里面会有不少的 bug

**Comment by JackLin00** [comment]
个人感觉一些基础的功能是大多数用户最常接触到，对项目的口碑影响相对于那些复杂的功能更大，如果存在多个这些问题，会很劝退新手，希望 xmake 越来越好
