### ISSUE TITLE
Path with xxx-include not included in pch

### ISSUE THREAD

**Issue by MaxwellGengYF** [xmake-io/xmake#5270]
### Xmake 版本

xmake v2.9.3+dev.7f0f823bc

### 操作系统版本和架构

Windows 11

### 描述问题

当add_includedirs 路径为 xxx-include，如 modules/my-include 时，set_pcxxheader 定义的pch编译不会正确 include

### 期待的结果

正常接受 include

### 工程配置

add_includedirs("test/my-include");
set_pcxxheader("pch.h");

### 附加信息和错误日志

fatal error: 'xx.h' file not found

**Comment by waruqi** [comment]
给个完整 project example

**Comment by MaxwellGengYF** [comment]
https://github.com/MaxwellGengYF/test_xmake

**Comment by waruqi** [comment]
再试试，https://github.com/xmake-io/xmake/pull/5284

**Comment by MaxwellGengYF** [comment]
没问题了。
