### ISSUE TITLE
如何方便去掉一些内置的编译参数

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#5274]
### 你在什么场景下需要该功能？

举个例子，在 coverage 或者 debug 模式下，xmake 会自带很多编译参数，比如 nvcc 中会带上`{"-G", "-g", "-lineinfo"}` ， 但是出于某些特殊需求，比如我们去掉里面的 -G 参数，在根目录的xmake.lua 全局作用域中写：
```bash
if is_mode("coverage") then
  remove_cuflags("-G")
end
```
这样是最便捷的，但是实际上无法生效。

即使我想在 after_load 中删掉 cuflags 也无法生效，因为打印 target:get("cuflags") 时 -G 并不在其中。

### 描述可能的解决方案

提供一种解决方法去掉 xmake 内部自带的编译参数。

**Comment by xq114** [comment]
不写add_rules("mode.debug")，自己判断is_mode("debug")加相关flag试试？

**Comment by TOMO-CAT** [comment]
> 不写add_rules("mode.debug")，自己判断is_mode("debug")加相关flag试试？

那相当于整个 mode.coverage 都得自己重新写，可以试试，但感觉比较麻烦，为了去掉一个参数将内置的一些 rule 整个重写了，还有一些 rule 更复杂比如 protobuf.cpp，不太好重写

**Comment by waruqi** [comment]
set_symbols("none") 或者自定义 debug mode

**Comment by TOMO-CAT** [comment]
> "

好的
