### ISSUE TITLE
Allow custom intermediate directory layout in dependir/objectir/targetdir

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#5278]
### 你在什么场景下需要该功能？

目前xmake生成的中间目录结构统一为plat/arch/mode形式，例如.deps/<target>/windows/x64/release/...。目录结构的用途是区分config不让不同config的文件混在一起，然而实际上固定的目录结构并不能达成这一目标（很多时候plat/arch/mode都是定死的，产生区别的是其他config），需要灵活指定中间目录结构。

### 描述可能的解决方案

增加一个api设置中间目录结构；最好可以在on_config脚本域指定，这样可以实现一些复杂一点的操作，例如根据所有config计算一个hash作为中间目录

**Comment by waruqi** [comment]
加了个 `build.intermediate_directory` policy，可以禁用生成中间目录。`set_policy("build.intermediate_directory", false)`

https://github.com/xmake-io/xmake/pull/5283

然后，你直接 `set_targetdir/set_objectdir/set_dependir` 设置就行了。。但只能在 on_load 里面改，on_config 不行，太滞后
