### ISSUE TITLE
Please add missing C++20 Modules file extension

### ISSUE THREAD

**Issue by yamader** [xmake-io/xmake#5280]
### Is your feature request related to a problem? Please describe.

xmake does not recognize some file extensions used in C++ Modules.
Those extensions are supported by common compilers and should be supported by xmake as well.
Currently missing support is for `.ccm`, `.cxxm`, and `.c++m`.

cf. clang and gcc code
https://github.com/llvm/llvm-project/blob/dc410f94/clang/lib/Driver/Types.cpp#L364-L366
https://github.com/gcc-mirror/gcc/blob/ff41abd/gcc/cp/lang-specs.h#L43-L47

### Describe the solution you'd like

Simply add the extensions (`ccm`・`cxxm`・`c++m`) here and it will work.

- https://github.com/xmake-io/xmake/blob/master/xmake/languages/c%2B%2B/xmake.lua#L23
- https://github.com/xmake-io/xmake/blob/master/xmake/rules/c%2B%2B/modules/xmake.lua#L25

**Comment by waruqi** [comment]
you can open a pr to add them
