### ISSUE TITLE
Ubuntu PPA is missing packages for 24.04

### ISSUE THREAD

**Issue by davidchisnall** [xmake-io/xmake#5286]
### Xmake Version

N/A

### Operating System Version and Architecture

Ubuntu

### Describe Bug

The Ubuntu PPA is missing a package for xmake on 24.04.  This version of Ubuntu does have the Debian package, but unfortunately this version imported during the narrow window when the Debian xmake package was not linked against the json library and falls back to the internal implementation, which is not able to parse hex numbers in JSON.

### Expected Behavior

`add-apt-repository ppa:xmake-io/xmake` on Ubuntu 24.04 should add a package repository that can install xmake

### Project Configuration

N/A

### Additional Information and Error Logs

N/A

**Comment by waruqi** [comment]
done, try it again.

**Comment by waruqi** [comment]
>  falls back to the internal implementation, which is not able to parse hex numbers in JSON.

I have improve pure lua json parser to support hex numbers.

https://github.com/xmake-io/xmake/pull/5293
