### ISSUE TITLE
怎么在用 iorunv + try-catch 功能的时候, 即能获取错误又能获取已经打印的标准输出

### ISSUE THREAD

**Issue by Sunrisepeak** [xmake-io/xmake#5292]
### Xmake 版本

xmake v2.9.1+20240517

### 操作系统版本和架构

Ubuntu22.04

### 描述问题

在尝试用xmake开发扩展插件[dslings](https://github.com/Sunrisepeak/d2ds/blob/xmake_test_case/xmake.lua)中, 尝试捕获本地构建目标C++程序运行的输出和错误信息。但是当程序crash的时候, 只能获取error信息已输出的信息无法获取

**直接运行**

![image](https://github.com/xmake-io/xmake/assets/38786181/6d3dd604-1565-48e7-9859-786bc2964bd2)

**在xmake中运行**

![image](https://github.com/xmake-io/xmake/assets/38786181/81294f90-9906-414f-9ba6-9be2276baabc)

**xmake运行的实现**

https://github.com/Sunrisepeak/d2ds/blob/eaf0eb645697db8738d4ea69521607f5f70b29db/common/dslings.lua#L127-L145

```lua
function run_with_error_handling(target)
    local output, err
    local run_success = true

    try {
        function ()
            output, err = os.iorunv("xmake", {"r", target}, {timeout = 2000})
        end,
        catch
        {
            function (e)
                output = e
                run_success = false
            end
        }
    }

    return output, run_success
end
```

### 期待的结果

在xmake中运行本地程序能获取crash前的标准输出 和 直接运行保持控制台输出一致

```bash
Output:
====================
[D2DS LOGI]: - Hello D2DS!
error: execv(/home/speak/workspace/github/d2ds/build/linux/x86_64/release/0.dslings-0 ) failed(-1)
====================
```

### 工程配置

**测试case**
```bash
git clone --recursive git@github.com:Sunrisepeak/d2ds.git -b xmake_test_case
cd d2ds
xmake r 0.dslings-0
xmake dslings
```

### 附加信息和错误日志

```bash
🌏Progress: [>-------------------------------------------------] 0/49

[Target: 0.dslings-0]

❌ Error: Compilation/Running failed for dslings/tests/dslings.0.cpp:

 The code exist some error!

Output:
====================
error: execv(/home/speak/tmp/project_tmp/d2ds/build/linux/x86_64/release/0.dslings-0 ) failed(-1)


====================

Homepage: https://github.com/Sunrisepeak/d2ds-courses
^C
speak@speak-pc:~/tmp/project_tmp/d2ds$ xmake r 0.dslings-0
[D2DS LOGI]: - Hello D2DS!
error: execv(/home/speak/tmp/project_tmp/d2ds/build/linux/x86_64/release/0.dslings-0 ) failed(-1)
speak@speak-pc:~/tmp/project_tmp/d2ds$
```

**Comment by waruqi** [comment]
catch 和 finally 里面都能取。。catch 的 errors 实际上是个 table 。。errors.stdout

```lua
    try
    {
        function ()
              os.iorunv(...)
        end,
        catch
        {
            function (errors)
                 print(errors.stderr)
                 print(errors.stdout) <-----------------
                 print(errors.errors)
                 print(tostring(errors))
            end
        },
        finally
        {
            function (ok, outdata, errdata)
            end
        }
    }
```

**Comment by Sunrisepeak** [comment]
> catch 和 finally 里面都能取。。catch 的 errors 实际上是个 table 。。errors.stdout
> 
> ```lua
>     try
>     {
>         function ()
>               os.iorunv(...)
>         end,
>         catch
>         {
>             function (errors)
>                  print(errors.stderr)
>                  print(errors.stdout) <-----------------
>                  print(errors.errors)
>                  print(tostring(errors))
>             end
>         },
>         finally
>         {
>             function (ok, outdata, errdata)
>             end
>         }
>     }
> ```

![image](https://github.com/xmake-io/xmake/assets/38786181/d0e65336-4aac-4c50-8141-d8d81127b162)

e.stderr 和 e.stdout 好像有一个是空的

**Comment by Sunrisepeak** [comment]
@waruqi 

https://github.com/xmake-io/xmake/blob/59327827e900ee5b61abba74e85d6081933d2a5a/xmake/core/base/utils.lua#L274-L287

这里的 decode 里好像没有显示处理 stdout / stderr

**Comment by Sunrisepeak** [comment]
> > @waruqi
> 
> > 
> 
> > https://github.com/xmake-io/xmake/blob/59327827e900ee5b61abba74e85d6081933d2a5a/xmake/core/base/utils.lua#L274-L287
> 
> > 
> 
> > 这里的 decode 里好像没有显示处理 stdout / stderr
> 
> 
> 
> 跟这里没关系。。https://github.com/xmake-io/xmake/blob/59327827e900ee5b61abba74e85d6081933d2a5a/xmake/core/sandbox/modules/os.lua#L322
> 
> 
> 
> > e.stderr 和 e.stdout 好像有一个是空的
> 
> 
> 
> 正常，又不是所以程序 都同时输出 stderr/stdout
> 
> 
> 
> 另外，你去里面调用 xmake 进程当然没 stderr 了。。xmake 内部没有任何一行输出是走的 stderr 。。怎么可能捕获到呢，我压根没输出，全部走的 stdout

从这个os模块看，发生异常后控制台的输出好像并不会获取。对于这种情况 发生crash的时候 xmake里有获取控制台输出内容的模块 或 有可以研究的方向吗

**Comment by waruqi** [comment]
不懂你在说啥。。

```lua
function main()
    try
    {
        function ()
            os.iorun("/private/tmp/test2/build/macosx/x86_64/release/test2")
        end,
        catch
        {
            function (errors)
                print("errors", errors)
                print("stdout:", errors.stdout)
                print("stderr:", errors.stderr)
            end
        }
    }
end
```

```c
#include <iostream>

int main(int argc, char** argv) {
    std::cout << "output" << std::endl;
    std::cerr << "error" << std::endl;
    return -1;
}
```

```console
$ xmake l test.lua
errors error


stdout: output

stderr: error
```

不是可以的么。。

**Comment by Sunrisepeak** [comment]
> 不懂你在说啥。。
> 
> ```lua
> function main()
>     try
>     {
>         function ()
>             os.iorun("/private/tmp/test2/build/macosx/x86_64/release/test2")
>         end,
>         catch
>         {
>             function (errors)
>                 print("errors", errors)
>                 print("stdout:", errors.stdout)
>                 print("stderr:", errors.stderr)
>             end
>         }
>     }
> end
> ```
> 
> ```c
> #include <iostream>
> 
> int main(int argc, char** argv) {
>     std::cout << "output" << std::endl;
>     std::cerr << "error" << std::endl;
>     return -1;
> }
> ```
> 
> ```
> $ xmake l test.lua
> errors error
> 
> 
> stdout: output
> 
> stderr: error
> ```
> 
> 不是可以的么。。

感谢这个示例, 大概原因找到了。 应该是我的程序crash之前 没有刷新 缓冲区导致的没有输出
