### ISSUE TITLE
Qt DLLs not found with vsxmake2022

### ISSUE THREAD

**Issue by charlesseizilles** [xmake-io/xmake#5295]
### Xmake Version

2.9.3+dev

### Operating System Version and Architecture

Windows 10 Pro version 22H2

### Describe Bug

When trying to run a Qt application from visual studio with a solution generated by the vsxmake2022 kind, I get the following error: 
![image](https://github.com/xmake-io/xmake/assets/61986161/08236ee7-479c-4c20-9441-b3da93c4a1bc)

It works fine from the command line `xmake r` or with the vs2022 kind.

### Expected Behavior

DLLs should be found.

### Project Configuration

[xmake.zip](https://github.com/user-attachments/files/16068290/xmake.zip)

### Additional Information and Error Logs

.

**Comment by SirLynix** [comment]
it works fine for me, did you regenerate your vsxmake project recently?

**Comment by charlesseizilles** [comment]
It seems my installation was corrupted. It works.
