### ISSUE TITLE
xpack nsis format build time error

### ISSUE THREAD

**Issue by Wzshun** [xmake-io/xmake#5306]
### Xmake 版本

2.9.3

### 操作系统版本和架构

windows11

### 描述问题

在使用xpack 的nsis格式时，如果构建时间格式为 "%Y-%m-%d %H:%M"，会报错（应该是空格问题）。
```
error: WriteRegStr expects 4 parameters, got 5.
Usage: WriteRegStr rootkey subkey entry_name new_value_string
    root_key=(HKCR[32|64]|HKLM[32|64]|HKCU[32|64]|HKU|HKCC|HKDD|HKPD|SHCTX)
Error in macro AddReg on macroline 16
```

把构建时间格式改为"%Y-%m-%d-%H:%M"，则顺利生成。

### 期待的结果

支持build格式为"%Y-%m-%d %H:%M"

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
给个可复现的例子

**Comment by Wzshun** [comment]
add_rules("mode.debug", "mode.release")

includes("@builtin/xpack")

target("packIssue")
    set_kind("binary")
    add_files("src/*.cpp")
    set_version("1.0.0", {build = "%Y-%m-%d %H:%M"})

xpack("packTest")
    set_formats("nsis")
    add_targets("packIssue")

**Comment by waruqi** [comment]
再试试，``xmake update -s dev

**Comment by Wzshun** [comment]
可以了
