### ISSUE TITLE
xpack 打包应用改进？

### ISSUE THREAD

**Issue by Wzshun** [xmake-io/xmake#5308]
### 你在什么场景下需要该功能？

```
target("App")
  set_kind("binary")
  add_files("src/*.cpp")
  add_deps("foo")

target("foo")
  set_kind("shared")
  add_files("src/*.cpp")

includes("@builtin/xpack")

xpack("test")
  add_targets("App")
  set_formats("zip")
```

几个问题：
1. 这样写法，xpack并不会去打包App的依赖项foo
2. 给xpack额外添加targets，如`add_targets("App", "foo")`，能够打包foo，但是我不希望走xmake install类似的方式（在安装位置加入了 include、lib等内容），只需要一个动态库文件即可。
3. 控制 target在install的目录应该怎么操作呢？比方说 我想把foo库，安装到安装目录的`/plugins`目录？

### 描述可能的解决方案

无

### 描述你认为的候选方案

无

### 其他信息

无

**Comment by Wzshun** [comment]
尝试了下确实会打包动态库。
但好像有另外一个问题。
```
add_rules("mode.debug", "mode.release")

includes("@builtin/xpack")

target("packIssue")
    set_kind("binary")
    add_files("src/*.cpp")
    add_deps("foo")
    set_version("1.0.0", {build = "%Y-%m-%d %H:%M"})

target("foo")
    set_kind("shared")
    add_files("src/foo/*.cpp")
    add_installfiles("src/foo/Readme.md", {prefixdir="doc"})
    --set_bindir("plugins")

xpack("packTest")
    set_formats("zip")
    add_targets("packIssue")
```
这里的target("foo")的add_installfiles，并没有触发。
得必须xpack里加上`add_targets("packIssue", "foo")`，才会安装。

此外似乎如果target是一个静态库，也不会安装。（可能我之前以为 add_installfiles，没被触发就认为xpack不会级联依赖安装）。

#使用 set_libdir()，set_bindir()
这个只能控制xpack本身，但如果我想要每个库，自行定位安装位置怎么做到呢？比方说这里的`foo`，我希望安装到plugins目录，其他库还是正常安装？

**Comment by waruqi** [comment]
> 此外似乎如果target是一个静态库，也不会安装。（可能我之前以为 add_installfiles，没被触发就认为xpack不会级联依赖安装）。

其实这块按理就不应该默认被安装。。

1. binary 依赖静态库：那么仅仅只需要安装 binary 自身的东西，就能保证运行了，静态库都被 link 进去了，还安装来干嘛。
2. binary 依赖动态库：那么安装 binary + 动态库自身，就能确保运行了，而动态库里面的 headerfiles 按理也不应该被安装了

所以按理不应该无脑级联安装所有，不过目前的默认安装策略确实有点乱，且不够灵活，应该默认走上面的策略，然后单独搞个策略， 针对性开启某些 target 的依赖级联。

这个要后面捋下才行。

**Comment by waruqi** [comment]
我重构设计了下默认安装策略，可以看下，后面会基于这个，同步 `xmake pack` 和 `xmake install` 的安装策略。 https://github.com/xmake-io/xmake/issues/5325
