### ISSUE TITLE
需要支持arm64ec

### ISSUE THREAD

**Issue by Ritchie1108** [xmake-io/xmake#5313]
### 你在什么场景下需要该功能？

本机已安装win11sdk, vs2022, 用xmake创建arm64ec项目的时候报错

### 描述可能的解决方案

麻烦支持

### 其他信息

xmake f -c -vD -m release -a arm64ec
checking for platform ... windows
checking for Microsoft Visual Studio (arm64ec) version ... no
checkinfo: cannot runv(clang.exe --version), No such file or directory
checking for clang ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(nim.exe --version), No such file or directory
checking for nim ... no
checkinfo: cannot runv(nim.exe --version), No such file or directory
checking for nim ... no
error: @programdir\core\main.lua:329: @programdir\actions\config\main.lua:157: target(detours): toolchain not found!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:973]: in function 'raiselevel'
    [@programdir\core\sandbox\modules\utils.lua:143]: in function 'assert'
    [@programdir\actions\config\main.lua:157]: in function '_check_target_toolchains'
    [@programdir\actions\config\main.lua:403]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:275]:
    [@programdir\core\base\task.lua:491]: in function 'run'
    [@programdir\core\main.lua:327]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:406]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:973: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:329: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:406: in function <@programdir\core\base\scheduler.lua:399>

**Comment by star-hengxing** [comment]
https://devblogs.microsoft.com/cppblog/arm64ec-support-in-visual-studio
看起来找 msvc 工具链需要加新的参数，然后编译链接再加个新参数就可以用了，感觉需要定义为一个 plat 而不是 arch？

**Comment by waruqi** [comment]
支持了，https://github.com/xmake-io/xmake/pull/5316

> https://devblogs.microsoft.com/cppblog/arm64ec-support-in-visual-studio 看起来找 msvc 工具链需要加新的参数，然后编译链接再加个新参数就可以用了，感觉需要定义为一个 plat 而不是 arch？

arch 足够，没必要搞这么复杂

**Comment by waruqi** [comment]
再试试，`xmake update -s dev`
