### ISSUE TITLE
汇编文件每次都会编译而不是增量编译

### ISSUE THREAD

**Issue by huhutm** [xmake-io/xmake#5327]
### Xmake 版本

2.9.2

### 操作系统版本和架构

windows 11

### 描述问题

我的工程中有c文件和汇编文件，编译的时候c文件可以正常增量编译，但是汇编文件每次都会编译，无论是否有修改。

### 期待的结果

汇编文件也可以支持增量编译，避免重复编译

### 工程配置

编译器为自定义，如下：
toolchain("mw")
    set_kind("standalone")
    set_sdkdir("C:/ARC/MetaWare/arc")
    set_toolset("cc", "gcc@ccac")
    set_toolset("as", "gcc@ccac")
    set_toolset("cxx", "gcc@ccac")
    set_toolset("ld", "gcc@ccac")
    set_toolset("ar", "ar@arac")

target("elf")
    set_kind("binary")
    set_policy("check.auto_ignore_flags", false)
    add_files("a.c")
    add_files("b.s")

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
```console
ruki-2:gas ruki$ xmake
[ 50%]: compiling.release src/main.S
[ 75%]: linking.release test
[100%]: build ok, spent 0.204s
ruki-2:gas ruki$ xmake
[100%]: build ok, spent 0.016s
```

这边测试正常。

**Comment by huhutm** [comment]
> ```
> ruki-2:gas ruki$ xmake
> [ 50%]: compiling.release src/main.S
> [ 75%]: linking.release test
> [100%]: build ok, spent 0.204s
> ruki-2:gas ruki$ xmake
> [100%]: build ok, spent 0.016s
> ```
> 
> 这边测试正常。

这里我的编译：
PS D:\test> .\xmake_build_rtos.bat clean
PS D:\test> .\xmake_build_rtos.bat flash 
[ 13%]: compiling.release ..\boot\flash\alps\arc_startup.S
[ 20%]: cache compiling.release ..\boot\flash\source\clock.c
[ 26%]: cache compiling.release ..\boot\flash\source\flash.c
[ 33%]: cache compiling.release ..\boot\flash\source\flash_qspi.c
[ 40%]: cache compiling.release ..\boot\flash\source\flash_sfdp.c
[ 46%]: cache compiling.release ..\boot\flash\source\os_port.c
[ 53%]: cache compiling.release ..\boot\flash\source\qspi_driver.c
[ 60%]: cache compiling.release ..\boot\flash\source\string.c
[ 66%]: cache compiling.release ..\boot\flash\source\time.c
[ 73%]: cache compiling.release ..\boot\flash\source\uart.c
[ 80%]: cache compiling.release ..\boot\flash\source\xprintf.c
[ 86%]: cache compiling.release ..\boot\flash\alps\init.c
[ 93%]: linking.release flash_access.elf
[100%]: build ok, spent 0.594s
PS D:\test> .\xmake_build_rtos.bat flash
[ 13%]: compiling.release ..\boot\flash\alps\arc_startup.S
[ 93%]: linking.release flash_access.elf
[100%]: build ok, spent 0.265s
PS D:\test>

**Comment by waruqi** [comment]
这边没法复现，你可以自己调下代码：https://github.com/xmake-io/xmake/blob/c90b483177dd45fb6e7a546b73fcd17c32bbaf23/xmake/modules/core/project/depend.lua#L96

**Comment by huhutm** [comment]
> 这边没法复现，你可以自己调下代码，然后提个 pr 过来：
> 
> https://github.com/xmake-io/xmake/blob/c90b483177dd45fb6e7a546b73fcd17c32bbaf23/xmake/modules/core/project/depend.lua#L96

目前发现 .S 文件对应的 .o 文件的 files_mtime[file] or os.mtime(file) 这两个值都是0，所以会重编译。

**Comment by huhutm** [comment]
补充一点：depend文件中的depend部分是这样的：
files = {
        [[..\boot\flash\alps\arc_startup.S]]
    },
    depfiles_gcc = "..\\build\\.objs\\elf\\cross\\none\\release\\__\\boot\\flash\\alps\\arc_startup.S.o:\9  ..\\boot\\flash\\alps\\arc_startup.S\

但是is_changed打印出的文件是这样的：
0 0 1720667757 D:\work\project\CTMRR180Pro\ctmrr180pro\build\.objs\elf\cross\none\release\__\boot\flash\alps\arc_startup.S.o:
不知道是否与目录名不一致有关系

**Comment by waruqi** [comment]
> > 这边没法复现，你可以自己调下代码，然后提个 pr 过来：
> > https://github.com/xmake-io/xmake/blob/c90b483177dd45fb6e7a546b73fcd17c32bbaf23/xmake/modules/core/project/depend.lua#L96
> 
> 目前发现 .S 文件对应的 .o 文件的 files_mtime[file] or os.mtime(file) 这两个值都是0，所以会重编译。

那就是没有对应的 .o 文件，要么就是 as 没有编译成功，.o 文件没有被生成。。要么就是没权限读

**Comment by huhutm** [comment]
> > > 这边没法复现，你可以自己调下代码，然后提个 pr 过来：
> > > https://github.com/xmake-io/xmake/blob/c90b483177dd45fb6e7a546b73fcd17c32bbaf23/xmake/modules/core/project/depend.lua#L96
> > 
> > 
> > 目前发现 .S 文件对应的 .o 文件的 files_mtime[file] or os.mtime(file) 这两个值都是0，所以会重编译。
> 
> 那就是没有对应的 .o 文件，要么就是 as 没有编译成功，.o 文件没有被生成。。要么就是没权限读

相应的目录下有对应的文件，如果是权限问题，其他.c的文件生成的.o都是正常的，只有.s生成的才有问题？

**Comment by star-hengxing** [comment]
看起来像是开发电脑上有加密软件，然后白名单没加上导致的

**Comment by waruqi** [comment]
你可以自己 -vD 看下完整的 编译命令和链接命令。找下对应 .o 是否存在，如果不存在就是没生成。。

也可以自己手动复制编译命令，执行确认是否能够正常生成 .o

**Comment by huhutm** [comment]
> 你可以自己 -vD 看下完整的 编译命令和链接命令。找下对应 .o 是否存在，如果不存在就是没生成。。
> 
> 也可以自己手动复制编译命令，执行确认是否能够正常生成 .o
<img width="226" alt="企业微信截图_17211126511380" src="https://github.com/user-attachments/assets/4e74e453-16af-4514-9509-9868c7032efc">
<img width="941" alt="企业微信截图_17211126353443" src="https://github.com/user-attachments/assets/c2c4e517-4371-43aa-b4b3-9e4418d598f2">
编译命令和生成的文件见截图，都生成了

**Comment by waruqi** [comment]
> 补充一点：depend文件中的depend部分是这样的： files = { [[..\boot\flash\alps\arc_startup.S]] }, depfiles_gcc = "..\build\.objs\elf\cross\none\release\__\boot\flash\alps\arc_startup.S.o:\9 ..\boot\flash\alps\arc_startup.S\
> 
> 但是is_changed打印出的文件是这样的： 0 0 1720667757 D:\work\project\CTMRR180Pro\ctmrr180pro\build.objs\elf\cross\none\release__\boot\flash\alps\arc_startup.S.o: 不知道是否与目录名不一致有关系

给下完整 depfiles_gcc 的内容。。

> 但是is_changed打印出的文件是这样的：
0 0 1720667757

你之前没说清楚，到底是哪个文件的 mtime 是 0 。。也贴下文件路径。。

另外一种可能是它生成的 deps info 格式问题，导致没解析到正确的路径

**Comment by huhutm** [comment]
```

> > 补充一点：depend文件中的depend部分是这样的： files = { [[..\boot\flash\alps\arc_startup.S]] }, depfiles_gcc = "..\build.objs\elf\cross\none\release__\boot\flash\alps\arc_startup.S.o:\9 ..\boot\flash\alps\arc_startup.S\
> > 但是is_changed打印出的文件是这样的： 0 0 1720667757 D:\work\project\CTMRR180Pro\ctmrr180pro\build.objs\elf\cross\none\release__\boot\flash\alps\arc_startup.S.o: 不知道是否与目录名不一致有关系
> 
> 给下完整 depfiles_gcc 的内容。。
> 
> > 但是is_changed打印出的文件是这样的：
> > 0 0 1720667757
> 
> 你之前没说清楚，到底是哪个文件的 mtime 是 0 。。也贴下文件路径。。
> 
> 另外一种可能是它生成的 deps info 格式问题，导致没解析到正确的路径

```
{
    values = {
        [[C:\ARC\MetaWare\arc\bin\ccac]],
        {
            "-Hasopt=-g",
            "-Hasmcpp",
            "-arcv2em",
            "-core4",
        }
    },
    depfiles_gcc = "..\\build\\.objs\\elf\\cross\\none\\release\\__\\boot\\flash\\alps\\arc_startup.S.o:\9 C:/ARC/MetaWare/arc/bin/arcdsp.s C:/ARC/MetaWare/arc/bin/arcexlib.s ..\\boot\\flash\\alps\\arc_startup.S\
\
",
    files = {
        [[..\boot\flash\alps\arc_startup.S]]
    }
}
```
上面就是deps文件的内容，mtime为0的文件目录：D:\work\project\pro\pro\build\.objs\elf\cross\none\release__\boot\flash\alps\arc_startup.S.o

**Comment by waruqi** [comment]
> 上面就是deps文件的内容，mtime为0的文件目录：D:\work\project\pro\pro\build\.objs\elf\cross\none\release__\boot\flash\alps\arc_startup.S.o

那你看下这个文件是否存在。。

```console
xmake l os.mtime D:\work\project\pro\pro\build\.objs\elf\cross\none\release__\boot\flash\alps\arc_startup.S.o
```

执行下，看看返回值是否也是 0

**Comment by huhutm** [comment]
> > 上面就是deps文件的内容，mtime为0的文件目录：D:\work\project\pro\pro\build.objs\elf\cross\none\release__\boot\flash\alps\arc_startup.S.o
> 
> 那你看下这个文件是否存在。。
> 
> ```
> xmake l os.mtime D:\work\project\pro\pro\build\.objs\elf\cross\none\release__\boot\flash\alps\arc_startup.S.o
> ```
> 
> 执行下，看看返回值是否也是 0

发现问题了，mtime为0的文件是 D:\work\project\pro\pro\build\.objs\elf\cross\none\release__\boot\flash\alps\arc_startup.S.o**：**
注意这个冒号，目录带了冒号，所以实际是不存在这个文件的，感觉是解析depend出现问题了

**Comment by waruqi** [comment]
> ..\\build\\.objs\\elf\\cross\\none\\release\\__\\boot\\flash\\alps\\arc_startup.S.o:\9

这种其实就是工具链自身乱七八糟的bug导致，莫名搞个 `\9` 干嘛。。却要这边来填坑。。这个也不太好兼容，处理起来平白增加解析负担 导致正常情况下依赖解析的性能下降，影响编译效率， 真是不划算。

**Comment by huhutm** [comment]
> > ..\build\.objs\elf\cross\none\release\__\boot\flash\alps\arc_startup.S.o:\9
> 
> 这种其实就是工具链自身乱七八糟的bug导致，莫名搞个 `\9` 干嘛。。却要这边来填坑。。这个也不太好兼容，处理起来平白增加解析负担 导致正常情况下依赖解析的性能下降，影响编译效率， 真是不划算。

好的，如果不改那我就自己加点判断处理掉了，谢谢！
