### ISSUE TITLE
vsxmake工程相对路径不正确

### ISSUE THREAD

**Issue by Domain** [xmake-io/xmake#533]
项目结构如下：
![image](https://user-images.githubusercontent.com/903197/63214763-0d3a1c00-c14f-11e9-997c-6cdcdbbac8db.png)
根目录有一个inc目录放头文件，src目录包含多个子工程，每个子工程都需要包含inc目录，用`add_headerfiles("$(projectdir)/inc/zero/**.h")`把头文件包含进来，vsxmake插件生成的工程结果如下：
![image](https://user-images.githubusercontent.com/903197/63208760-b3176780-c10a-11e9-9e27-e6e92ccaf7e5.png)
双击这些头文件回提示无法打开，打开vcxproj文件看到：
<pre>&lt;ClInclude Include="$(XmakeProjectDir)\C:\git\z\inc\zero\plugins\dependency.h" /&gt;</pre>
路径显然是错的

用老的vs插件生成的是这样的：
![image](https://user-images.githubusercontent.com/903197/63214782-483c4f80-c14f-11e9-9e80-0188cb9a6a5d.png)
虽然看起来很奇怪，不过路径是对的，也可以打开。
如果能够把两级`..`去掉就完美了

**Comment by OpportunityLiu** [comment]
为什么要把不属于工程的外部头用add headerfiles加进来。。。

**Comment by Domain** [comment]
属于工程的，只是这些头文件是库的头文件，需要被其他子项目用到，所以放在公共的地方

**Comment by OpportunityLiu** [comment]
那你的xmake.lua也应该属于整个工程啊

**Comment by OpportunityLiu** [comment]
`add_headerfiles("$(projectdir)/inc/zero/**.h")` 这句话写在哪了？怎么就没有``../..``
那你应该在这一级目录底下创建vs工程

**Comment by waruqi** [comment]
> `add_headerfiles("$(projectdir)/inc/zero/**.h")` 这句话写在哪了？怎么就没有`../..`
> 那你应该在这一级目录底下创建vs工程

估计是他这边 吧xmake.lua通过 includes，隔离到其他不在projectdir的外部目录去了。。这种情况我记得老的vs插件也是做过兼容处理的。。

```lua
    local filter = path.relative(path.absolute(path.directory(filepath)), target.scriptdir or vcxprojdir)
```

**Comment by OpportunityLiu** [comment]
为什么不用上级include下级，反而要反过来呢？

完全不想支持这种。。。

**Comment by waruqi** [comment]
> 为什么不用上级include下级，反而要反过来呢？
> 
> 完全不想支持这种。。。

可以看下他之前的issues https://github.com/xmake-io/xmake/issues/522

xmake的推荐做法都是按tree状继承式includes来维护，也就是上级include子目录下xmake.lua来维护不同子模块

但是确实有部分用户把includes反过来在用，虽然不推荐，不过我这基本上都是做了支持的。

**Comment by Domain** [comment]
根目录的xmake.lua定义了所以公共选项，然后包含src下面所以子目录，每个子目录都是独立的项目，其中有一个是静态库，它的头文件需要被其他子项目使用，所以我把所以公共的头文件都放在根目录的inc里面，静态库就用add_headerfiles把头文件包含进来。

**Comment by OpportunityLiu** [comment]
请你正确使用xmake。。。

我会做的修复就是忽略项目外的文件。。。

**Comment by Domain** [comment]
这么使用哪里不正确吗？

**Comment by OpportunityLiu** [comment]
> 只是这些头文件是库的头文件，需要被其他子项目用到，所以放在公共的地方

这就显然不是推荐的方式，请用 `add_includedirs("...", { public = true})` 来公开接口



可以看看xmake自己的xmake.lua是怎么写的，同样的子工程、静态库、依赖

**Comment by Domain** [comment]
我看了一下xmake的写法，就是所以头文件都是在自己工程目录下面，但是我这边基本上公共头文件都是放在统一的地方，我是希望只要把这个目录和对应的lib发布出去就行，不想到处找头文件

**Comment by OpportunityLiu** [comment]
为什么会需要“到处找头文件”。。

如果又依赖，头文件会继承；如果没有，为什么要添加这些头文件？

**Comment by OpportunityLiu** [comment]
你需要发布请用xmake package，相应的文件会自动整理出来

**Comment by Domain** [comment]
我意思是说，如果别人要用我这个框架，只需要把inc和lib目录给他就行了，如果头文件放在每个工程自己的目录里面，我就需要把 src/lib1/inc，src/lib2/inc，……，等等，全部拿出来

**Comment by OpportunityLiu** [comment]
你应该用xmake package，然后把target.pkg给他。。。

**Comment by waruqi** [comment]
> 我意思是说，如果别人要用我这个框架，只需要把inc和lib目录给他就行了，如果头文件放在每个工程自己的目录里面，我就需要把 src/lib1/inc，src/lib2/inc，……，等等，全部拿出来

xmake package 和 xmake install 都能干这事，add_headerfiles只需要添加当前子目录下的inc files就行，哪怕是inc比较分散也没关系。。

xmake package会吧当前plat/arch下的lib库以及inc全部整理出来，打包到 xxx.pkg里面去，方便分发给其他人用，里面自动帮你整理好了。。而且其他人也可以通过 add_packagedirs/add_packages 吧这个xxx.pkg自动导入到对方的xmake.lua里面，直接集成使用

xmake install也会吧对应lib/inc自动整理出来，不过是安装到系统目录，不过也可以install指定目录

建议你可以试试 xmake package，至于如何去整体零散的headers到指定目录接口，add_headerfiles 里面可以加扩展参数来控制，你可以看下 add_headerfiles 的文档藐视

**Comment by Domain** [comment]
package我试了一下，为什么头文件的目录结构不见了，全部直接放在include里面。

xmake目前只是我个人试用，用来快速开发原型。在没有分布式编译之前，暂时不会给别人使用，因为我真正的工程单机编译要超过一小时。正式使用还是fastbuild，只是他的配置文件麻烦点

**Comment by Domain** [comment]
inc/zero
├── plugins
│   ├── dependency.h
│   ├── iplugin.h
│   └── metadata.h
├── type_traits.h
└── version.h

build/zero.pkg/linux/arm64-v8a/include
├── dependency.h
├── iplugin.h
├── metadata.h
├── type_traits.h
└── version.h

**Comment by OpportunityLiu** [comment]
@waruqi 就这么直接摊平是不太对啊

**Comment by waruqi** [comment]
可以设置成根据子目录结构copy的，加个括号提取里面的子目录结构就行了

```lua
target("test")
    add_headerfiles("src/(tbox/*.h)", {prefixdir = "include"})
```

你可以看下文档，add_headerfiles 和add_installfiles的用法格式一样的

https://xmake.io/#/zh-cn/manual/project_target?id=targetadd_installfiles

或者看下tbox项目里面的例子

https://github.com/tboox/tbox/blob/0cdb41ee2f944466e4d69219922f2feb5b761514/src/tbox/xmake.lua#L19

**Comment by waruqi** [comment]
分布式编译还需要等一段时间，我需要先改进下tbox里面的协程和socket io处理后，才会集成到xmake里面去封装socket io实现

之后会加上分布式编译支持，不过还需要再等等

**Comment by OpportunityLiu** [comment]
这个应该已经修好了

**Comment by waruqi** [comment]
@Domain 你再试试

**Comment by Domain** [comment]
不好意思，回复晚了，确实好了

**Comment by waruqi** [comment]
> package我试了一下，为什么头文件的目录结构不见了，全部直接放在include里面。
> 
> xmake目前只是我个人试用，用来快速开发原型。在没有分布式编译之前，暂时不会给别人使用，因为我真正的工程单机编译要超过一小时。正式使用还是fastbuild，只是他的配置文件麻烦点

dev分支 分布式编译我支持了，支持 gcc/clang/msvc 全平台支持，https://github.com/xmake-io/xmake/issues/274

另外我还增加了 内置的本地 cache 支持，替代 ccache，也支持 msvc，后面还会增加 remote cache 支持

还有上个版本新增的 远程编译支持
