### ISSUE TITLE
只获取 target:deps 自身的 syslinks，不要递归获取 target:pkgs 的 syslinks

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#5331]
### 你在什么场景下需要该功能？

我在写一个打包的 phony target，希望将当前项目里所有的 dep 的 syslinks 和 deps 导出，但是这里的 syslinks 会把 add_packages("xx") 的 syslinks 都带上，有办法可以跳过吗，只拿 target 里面 add_syslinks 的部分。
![d14d47d8cc76c1551f5f6d072545ed37](https://github.com/xmake-io/xmake/assets/47598093/977007fc-e5d9-4dd6-86be-57f95ea8ede1)

背景是现在项目接完了，想把一些之前定制化的脚本都抽到 rule 里，需要封装一下

### 描述可能的解决方案

无

### 描述你认为的候选方案

目前没啥好的解法

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/blob/c90b483177dd45fb6e7a546b73fcd17c32bbaf23/xmake/core/project/target.lua#L656-L696

**Comment by TOMO-CAT** [comment]
> https://github.com/xmake-io/xmake/blob/c90b483177dd45fb6e7a546b73fcd17c32bbaf23/xmake/core/project/target.lua#L656-L696

怎么跳过 dep 的 packages 呢？
![image](https://github.com/xmake-io/xmake/assets/47598093/f4e2107d-3808-4a72-abb0-bc55fd17670a)

**Comment by TOMO-CAT** [comment]
好像可以通过对 source 做过滤，出现 package:: 就跳过，但不是太优雅

**Comment by waruqi** [comment]
```lua
dep:get_from("links", "self") 
```

**Comment by TOMO-CAT** [comment]
> ```lua
> dep:get_from("links", "self") 
> ```

这种写法还是递归获取了 target:dep 对应的所有 packages 导入的 syslinks：
![image](https://github.com/xmake-io/xmake/assets/47598093/c4e226a6-37ce-42c9-a60d-b8648913058b)

有办法只获取 target 里面的 syslinks 吗： `"ceres", "pcl_common", "pcl_filters", "pcl_segmentation"` 只需要这四个

**Comment by TOMO-CAT** [comment]
试了一下，过滤 `dep::*` 中带 package:: 的也不行，它已经递归拿到了 package 的 syslinks 了
```lua
        local values, sources = target:get_from("syslinks", "dep::localization.initialization_localization.reflector_detection")
        for idx, value in ipairs(values) do
            local source = sources[idx]
            print(source)
            print(value)
        end
```

**Comment by waruqi** [comment]
不知道你说啥，反正我这可以，没法复现

```lua
add_requires("libuv")

target("foo")
    set_kind("static")
    add_packages("libuv")
    add_syslinks("z")

target("test")
    set_kind("binary")
    add_deps("foo")
    add_files("src/*.cpp")
    on_config(function (target)
	print("1111", target:dep("foo"):get("syslinks"))
	print("2222", (target:get_from("syslinks", "dep::*")))
    end)
```

```console
1111 z
2222 { 
  "z",
  { 
    "pthread",
    "dl" 
  } 
}
```

target:get("syslinks") 原本就只会仅仅 get target 里面的 syslinks ，不会从 packages 里面取。除非你把这些设置到了 target

**Comment by TOMO-CAT** [comment]
> 不知道你说啥，反正我这可以，没法复现

是我本地 xmake 版本的问题吗？这有一个最小复现的 demo：
https://github.com/TOMO-CAT/xmake-template/blob/main/unexpected_deps_syslinks/README.md

我希望能不把依赖库 gtest 的 syslinks 引进来

**Comment by TOMO-CAT** [comment]
> 代码里，也压根没有从 pkgs 取值的实现，只要 get_from 才有可能取到 package

试验了几次，你给的这个例子确实就没问题，主要出在 c++ rule 这，加上这一行就不行：

![image](https://github.com/xmake-io/xmake/assets/47598093/6317204e-a759-43ab-aee2-2fe1aff122e6)

**Comment by waruqi** [comment]
更新到这个  patch 再试试 https://github.com/xmake-io/xmake/pull/5334

**Comment by TOMO-CAT** [comment]
> 更新到这个 patch 再试试 #5334

可以的，测试过了。
