### ISSUE TITLE
The behavior of `set_optimize` is inconsistent on MSVC-related platforms.

### ISSUE THREAD

**Issue by ObeliskGate** [xmake-io/xmake#5332]
### Xmake 版本

2.9.3

### 操作系统版本和架构

Windows 11 22H2

### 描述问题

根据[ MSVC 文档](https://learn.microsoft.com/zh-cn/cpp/build/reference/o-options-optimize-code?view=msvc-170), `/Ox`是弱于`/O2`的选项, 也就是在 xmake 中应该`/Ox`对应`faster`而`/O2`对应`fastest`及`aggressive`等.

[`cl`](https://github.com/xmake-io/xmake/blob/c90b483177dd45fb6e7a546b73fcd17c32bbaf23/xmake/modules/core/tools/cl.lua#L181)和[`clang-cl`](https://github.com/xmake-io/xmake/blob/c90b483177dd45fb6e7a546b73fcd17c32bbaf23/xmake/modules/core/tools/clang_cl.lua#L101)的代码实现也与上述描述相同.

但在[文档](https://github.com/xmake-io/xmake-docs/blob/3edc28e0c7cc3a0605090b9b4a7b2f01e4615c9c/manual/project_target.md?plain=1#L470)以及[ CMake 相关实现](https://github.com/xmake-io/xmake/blob/c90b483177dd45fb6e7a546b73fcd17c32bbaf23/xmake/plugins/project/cmake/cmakelists.lua#L793)中, 实现为`/O2`对应`faster`而`/Ox`对应`fastest`并且混入了浮点数相关选项, 互相不相符.

而在[`cl`的编译命令`mapflags`](https://github.com/xmake-io/xmake/blob/c90b483177dd45fb6e7a546b73fcd17c32bbaf23/xmake/modules/core/tools/cl.lua#L46)中也有类似的问题: `-O3`和`-Ofast`都被对应到`-Ox`而非`-O2`上并且同样出现了浮点数选项.

我不太清楚会不会导致冲突, 但在浮点数已经有[`target:set_fpmodels`](https://xmake.io/#/manual/project_target?id=targetset_fpmodels)控制的情况下, 这样的映射很可能是不必要的.

这种混乱看上去是由一次不彻底的重构导致的, 期待后续修复.

### 期待的结果

MSVC 相关平台优化选项表现一致.

### 工程配置

N/A

### 附加信息和错误日志

N/A

**Comment by waruqi** [comment]
> 根据[ MSVC 文档](https://learn.microsoft.com/zh-cn/cpp/build/reference/o-options-optimize-code?view=msvc-170), /Ox是弱于/O2的选项, 也就是在 xmake 中应该/Ox对应faster而/O2对应fastest及aggressive等.

现在不就是么，只是文档没更新而已。

https://github.com/xmake-io/xmake/blob/c90b483177dd45fb6e7a546b73fcd17c32bbaf23/xmake/modules/core/tools/cl.lua#L185-L186

> 但在[文档](https://github.com/xmake-io/xmake-docs/blob/3edc28e0c7cc3a0605090b9b4a7b2f01e4615c9c/manual/project_target.md?plain=1#L470)以及[ CMake 相关实现](https://github.com/xmake-io/xmake/blob/c90b483177dd45fb6e7a546b73fcd17c32bbaf23/xmake/plugins/project/cmake/cmakelists.lua#L793)中, 实现为/O2对应faster而/Ox对应fastest并且混入了浮点数相关选项, 互相不相符.

后来更新没同步过去而已，刚改了。

**Comment by ObeliskGate** [comment]
> 后来更新没同步过去而已，刚改了。
改了我就 close 了.
