### ISSUE TITLE
Windows下shared目标缺少定义_WINDLL宏

### ISSUE THREAD

**Issue by Elite-stay** [xmake-io/xmake#5333]
### Xmake 版本

2.9.3

### 操作系统版本和架构

Windows

### 描述问题

通过vs新建的动态库工程会自动包含名为Windows Dynamic Link Library，实则为Microsoft.Cpp.WinDLL.props的属性表，这个属性表会增加定义_WINDLL宏，但目前set_kind(“shared")中并没有

### 期待的结果

设置set_kind(“shared")后，如果是使用vs进行编译，则增加_WINDLL宏

### 工程配置

.

### 附加信息和错误日志

.

**Comment by waruqi** [comment]
xmake 默认不会加任何内置定义的， 也不会保证必须跟 vs 的配置保持同步，你可以自己配置上。
