### ISSUE TITLE
links not found when add_deps("openmp")

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#5345]
### Xmake 版本

2.9.3

### 操作系统版本和架构

Fedora

### 描述问题

https://github.com/xmake-io/xmake-repo/actions/runs/9920625780/job/27407697804?pr=4611

error: @programdir/core/package/package.lua:2406: package(openmp): links not found!

openmp本来就没有link

### 期待的结果

正常安装package

### 工程配置

-

### 附加信息和错误日志

-

**Comment by waruqi** [comment]
再试试

**Comment by xq114** [comment]
还是不行，应该是#ldflags > 0才对吧；还有就是https://github.com/xmake-io/xmake/blob/dev/xmake/core/package/package.lua#L2021-L2029 这里没考虑 fetchinfo 为boolean的情况，直接判断fetchinfo.version会出问题，是不是参考https://github.com/xmake-io/xmake/blob/dev/xmake/core/package/package.lua#L1739-L1749 处理下？

**Comment by waruqi** [comment]
> 还是不行，应该是#ldflags > 0才对吧；

好了，再试试

> 还有就是https://github.com/xmake-io/xmake/blob/dev/xmake/core/package/package.lua#L2021-L2029 这里没考虑 fetchinfo 为boolean的情况，直接判断fetchinfo.version会出问题，是不是参考https://github.com/xmake-io/xmake/blob/dev/xmake/core/package/package.lua#L1739-L1749 处理下？

返回 boolean 原本就是不对的，当初早期可能有几个不规范的，改下包就好了。。现在统一只能返回 table

**Comment by xq114** [comment]
还是不行

**Comment by waruqi** [comment]
> 还是不行

我这里正常，links not found 的问题没了。。

```console
> checking for c links(omp)
> checking for c snippet(test)
  => install openmp latest .. ok
```

反而是 openmp 这个包自从加了 fortran 后，ldflags 没设置对，导致 macos 下 test 测试不过，多了 `-fopenmp` 的 ldflags。。我改了下。。

https://github.com/xmake-io/xmake-repo/pull/4663

**Comment by waruqi** [comment]
应该可以了 https://github.com/xmake-io/xmake-repo/pull/4663
