### ISSUE TITLE
How to set llvm-rc's options on msys2/clangarm64?

### ISSUE THREAD

**Issue by rel1ve** [xmake-io/xmake#5349]
### 你在什么场景下需要该功能？

on msys2/clangarm64, I need compile *.rc file. If rc file contains chinese string, llvm-rc failed.
> error: llvm-rc: Error in VERSIONINFO statement (ID 1):
Non-ASCII 8-bit codepoint () can't be interpreted in the current codepage

So, I need call "llvm-rc -C65001 xxx.rc". How to do this in xmake?

### 描述可能的解决方案

N/A

**Comment by waruqi** [comment]
```
add_mrcflags("-C65001", {force = true})
```
