### ISSUE TITLE
set_project 这个命令在文档中没有描述，是已经舍弃了吗

### ISSUE THREAD

**Issue by Ultraman95** [xmake-io/xmake#535]
> 注：如果是`问题报障`或者`特性请求`，请选择对应issues模板，否则一律不回复。

### 描述问题详情
请在这描述你的问题详情。

**Comment by waruqi** [comment]
https://xmake.io/#/zh-cn/manual/global_interfaces?id=set_project 这不是在的么？

**Comment by Ultraman95** [comment]
cmakelists的支持，文档里没有说明，-h命令描述也没有说明

**Comment by waruqi** [comment]
> cmakelists的支持，文档里没有说明，-h命令描述也没有说明
> 只能去你以前写的文章里去找
> 还比如，文档里写了支持vs2019,但是-h命令描述里没有说明
> 总体感觉不统一

vs2019不是有么。。

![image](https://user-images.githubusercontent.com/151335/63322529-3bd61380-c356-11e9-8b5d-d4e8109ee81f.png)

cmakelists是没有，我之后有时间补下。

一个人维护代码和文档，人力和精力有限，难免会有遗漏，多体谅下。。如果有发现遗漏的地方，你可以帮忙提个pr更新同步下文档或者help

**Comment by Ultraman95** [comment]
你是哪个版本啊，我是xmake v2.2.7+201906192321

**Comment by waruqi** [comment]
dev最新commit

**Comment by Ultraman95** [comment]
我们用户该用哪个版本呢

**Comment by Ultraman95** [comment]
还有就是，web文档现在为什么要分页了，我都没办法全局搜索

**Comment by waruqi** [comment]
没特殊需求 用 正式release版本。。如果要跟进新特性 可以尝试dev。dev每天都会更新，也会有些不稳定。。

release页面有提供 xmake-dev.exe下载。

**Comment by Ultraman95** [comment]
可以用命令更新吗？

**Comment by waruqi** [comment]
> 可以用命令更新吗？

可以 xmake update dev ，不过最近源码repo我改成 git submodule维护了。。现在老版本的 xmake update 不一定支持。。所以还是需要先从release下载安装一次。。之后就可以一直 xmake update dev更新了

**Comment by waruqi** [comment]
> 还有就是，web文档现在为什么要分页了，我都没办法全局搜索

这不是能支持跨页搜索么？ 之前单页面文档 一个md 越来越大，都快上M了。  不好维护哈。。改点文档 找半天 而且还卡编辑器，打个字都卡

![image](https://user-images.githubusercontent.com/151335/63323186-c0756180-c357-11e9-9d04-18cf748ff072.png)

**Comment by OpportunityLiu** [comment]
你说的这个搜索框，我只有刷新一次页面才能看到，从Getting Started那里点进来永远看不见

**Comment by waruqi** [comment]
> 你说的这个搜索框，我只有刷新一次页面才能看到，从Getting Started那里点进来永远看不见

这个我也没辙哈。。用的docsify框架，要么给 docsify提个issues反馈下。。也不知道是否我没用对。我这里也是有这个问题。。目前只能强制先刷新下了。。

**Comment by waruqi** [comment]
> 你说的这个搜索框，我只有刷新一次页面才能看到，从Getting Started那里点进来永远看不见

我文档改进过了，搜索有时候显示不出来的问题，应该解决了。。你可以再试试

是docsify的onlyCover:true导致，似乎启用后，搜索框加载会有问题，我现在只能默认关掉了。。
