### ISSUE TITLE
Improve copy pdb when using ninja on Windows

### ISSUE THREAD

**Issue by star-hengxing** [xmake-io/xmake#5353]
### Xmake Version

dev

### Operating System Version and Architecture

N/A

### Describe Bug

使用 ninja 构建一些 debug 包的时候会遇到

```
if multiple CL.EXE write to the same .PDB file, please use /FS
```

workaround 方法

```lua
if package:is_plat("windows") then
    table.insert(configs, "-DCMAKE_COMPILE_PDB_OUTPUT_DIRECTORY=''")
end
```

这样解决后，xmake 不会把 pdb 拷贝出来。

### Expected Behavior

可能的解决方法：

```lua
if package:is_plat("windows") then
    local dir = os.isdir("pdb") and "pdb/" or ""
    if package:config("shared") or not package:is_library() then
        os.vcp(dir .. "**.pdb", package:installdir("bin"))
    else
        os.vcp(dir .. "**.pdb", package:installdir("lib"))
    end
end
```

### Project Configuration

N/A

### Additional Information and Error Logs

N/A

**Comment by waruqi** [comment]
patch /FS 呢

https://github.com/xmake-io/xmake-repo/blob/2989c39b82d4ca991ec8327b8042029be2d8a91e/packages/s/snmalloc/xmake.lua#L24

**Comment by star-hengxing** [comment]
cmake + debug + ninja 会设置 /FS，但依然报错。
而且我发现只是 jobs 为 1，也是一样的报错

**Comment by waruqi** [comment]
> cmake + debug + ninja 会设置 /FS，但依然报错。 而且我发现只是 jobs 为 1，也是一样的报错

你说的是 backward-cpp 包么，`/Fdpdb\ /FS` 这个包的 flags 不对，`/Fd` 后面应该跟一个可写的 pdb file，例如 `/Fdxxx.pdb`

而不是 `pdb/` 目录。。如果 `/Fd` 后面不是跟的不是可写的 pdb 文件，写入失败，就会报这个错，即使设置了 `/FS`

所以，其实这个还是 这个包的 cmake 配置，或者 cmake 本身有问题

> cl.exe  /nologo /TP -DBACKWARD_HAS_BACKTRACE=0 -DBACKWARD_HAS_BACKTRACE_SYMBOL=0 -DBACKWARD_HAS_BFD=0 -DBACKWARD_HAS_DW=0 -DBACKWARD_HAS_DWARF=0 -DBACKWARD_HAS_LIBUNWIND=0 -DBACKWARD_HAS_UNWIND=0 -IC:\Users\wangrunqing\AppData\Local\.xmake\cache\packages\2407\b\backward-cpp\v1.6\source /DWIN32 /D_WINDOWS /W3 /GR /EHsc /DWIN32 /D_WINDOWS /W3 /GR /EHsc  /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\backward_object.dir\backward.cpp.obj /Fdpdb\ /FS -c C:\Users\wangrunqing\AppData\Local\.xmake\cache\packages\2407\b\backward-cpp\v1.6\source\backward.cpp

**Comment by star-hengxing** [comment]
嗯，不过目前仓库里有 11 个包需要这样 workaround，那感觉 xmake 这边优化下拷贝 pdb 的逻辑可能更好

**Comment by waruqi** [comment]
> 嗯，不过目前仓库里有 11 个包需要这样 workaround，那感觉 xmake 这边优化下拷贝 pdb 的逻辑可能更好

主要还是 cmake 生成的 build.ninja 不会自动创建 `build/pdb` 目录，导致 `/Fdpdb/` 会让 cl.exe 生成 `pdb/v140.pdb` 写入失败。。

另外一种办法就是提前帮它创建好 build/pdb 目录，就行了

**Comment by waruqi** [comment]
可以试下 这个 patch https://github.com/xmake-io/xmake/pull/5365

**Comment by durongze** [comment]
if multiple CL.EXE write to the same .PDB file, please use /FS

**Comment by waruqi** [comment]
> if multiple CL.EXE write to the same .PDB file, please use /FS

/FS has been set.
