### ISSUE TITLE
解决rc文件不会重新编译的问题

### ISSUE THREAD

**Issue by ChrisCatCP** [xmake-io/xmake#5355]
### Is your feature request related to a problem? Please describe.

rc包含资源文件时不会检查资源文件更新  这样很不方便

### Describe the solution you'd like

我觉得可以在add_file中加一个功能    对源文件添加一个depfiles列表  在任意一个depfiles的mtime更新的时候  重新编译这个源文件

**Comment by waruqi** [comment]
常年老问题，重复了 https://github.com/xmake-io/xmake/issues/4342#issuecomment-1788259826

**Comment by ChrisCatCP** [comment]
额  但是这是个feature request

**Comment by star-hengxing** [comment]
msbuild 是开源的，我觉得可以去那边提个 issue 问问是怎么实现的，然后 xmake 这边才好支持

**Comment by ChrisCatCP** [comment]
> msbuild 是开源的，我觉得可以去那边提个 issue 问问是怎么实现的，然后 xmake 这边才好支持

所以才想弄个曲线救国的法子

**Comment by star-hengxing** [comment]
> before_build 里面自己判断 Depfiles mtime 后，去 os.touch 下对应的 rc file 触发编译

那可以基于这个改善一下 rc 的 rule :)
