### ISSUE TITLE
文档不一致，wiki和网页文档不一致，-h命令注释和文档也不一致

### ISSUE THREAD

**Issue by Ultraman95** [xmake-io/xmake#536]
> 注：如果是`问题报障`或者`特性请求`，请选择对应issues模板，否则一律不回复。

### 描述问题详情
请在这描述你的问题详情。

能不能有一份统一的文档

**Comment by waruqi** [comment]
https://xmake.io上就是官方统一的文档啊。。

wiki上的老早废弃了，不是有说明么：

![image](https://user-images.githubusercontent.com/151335/63322340-c4a07f80-c355-11e9-849c-f1d802c07a41.png)

-h只是简单的help菜单描述哈，又不是文档

**Comment by OpportunityLiu** [comment]
文档很难用是事实，多在群里问吧。。。

**Comment by waruqi** [comment]
> 文档很难用是事实，多在群里问吧。。。

还难用哈。已经改版过一次了。。= =
