### ISSUE TITLE
希望有机会设置目标的扩展名

### ISSUE THREAD

**Issue by shrinktofit** [xmake-io/xmake#539]
### Is your feature request related to a problem? Please describe.
有些情况下，输出的目标文件需要有特定的后缀。

### Describe the solution you'd like
注意到目前相关的 API 有 `set_basename()` 和 `set_filename()`。希望提供一个 `set_extname()` 类似的 API。

### Describe alternatives you've considered
`set_filename()` 里面如果能获取到原本的 `basename` 那也可以。

**Comment by waruqi** [comment]
用set_filename就行了 没设置set_basename，那么target("xxx")里面的名字就是默认的basename，所以你不管是否通过set_basename设置，basename原本就是已知的，那么直接使用set_filename不就行了

如果非要获取basename，可以在脚本域获取

```lua
target("xxx")
    on_load(function (target) 
        target:set("filename", taget:basename() .. ".ext")
    end)
