### ISSUE TITLE
mingw方式编译qt.quickapp工程失败

### ISSUE THREAD

**Issue by zkqgxlbjx** [xmake-io/xmake#5393]
### Xmake 版本

2.9.3

### 操作系统版本和架构

Windows 10 LTSC 1809

### 描述问题

创建qt.quickapp示例工程后，使用mingw方式编译没有编译成功且没有报错
使用的命令 xmake f -p mingw -m debug --qt=C:\Qt\6.6.3 --qt_sdkver=6.6.3 -vD

### 期待的结果

能成功编译并运行

### 工程配置

xmake create -t qt.quickapp quickapp 创建的qt.quickapp示例工程

### 附加信息和错误日志

checking for architecture ... x86_64
checking for mingw directory ... C:\Qt\Tools\mingw1120_64
checking for Qt SDK directory ... C:/Qt/6.6.3/mingw_64
checking for Qt SDK version ... 6.6.3
configure
{
    host = windows
    kind = static
    buildir = build
    qt_sdkver = 6.6.3
    mode = debug
    ccache = true
    arch = x86_64
    ndk_stdcxx = true
    plat = mingw
    mingw = C:\Qt\Tools\mingw1120_64
    qt = C:/Qt/6.6.3/mingw_64
}

**Comment by waruqi** [comment]
? 好歹给全下 logs 了。啥也没有。。我哪知道怎么个失败法。

**Comment by zkqgxlbjx** [comment]
后面没有，只输出了这些了

**Comment by zkqgxlbjx** [comment]
> ? 好歹给全下 logs 了。啥也没有。。我哪知道怎么个失败法。

![0c6b1b44-56be-4434-987b-7ceef123d30a](https://github.com/user-attachments/assets/bd6b15ef-c7c3-4c1b-8c0d-edd4c2e0ffbc)

**Comment by waruqi** [comment]
你都没去编译，哪来的后续？ `xmake f/config` 仅仅是配置命令。

**Comment by zkqgxlbjx** [comment]
> 你都没去编译，哪来的后续？ `xmake f/config` 仅仅是配置命令。

没问题了，谢谢
