### ISSUE TITLE
安装 xmake 之后，xmake 没有被添加到环境变量中

### ISSUE THREAD

**Issue by shrinktofit** [xmake-io/xmake#540]
### 描述问题

按照文档，用 Powershell 命令：
```
Invoke-Expression (Invoke-Webrequest 'https://raw.githubusercontent.com/xmake-io/xmake/master/scripts/get.ps1' -UseBasicParsing).Content
```

安装 xmake，完成之后直接运行 xmake 提示不存在相应的可执行文件。

安装过程中分别试过选项 M 和 A，都一样。

### 期待的结果

安装完之后能直接运行 xmake。

### 相关环境

Windows 10，64位，简体中文语言包

**Comment by waruqi** [comment]
你从releases里面下载xmake.exe安装包直接装试试

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/63346926-a011cb00-c388-11e9-9db7-84e0736dfbeb.png)
复现不了。。。

**Comment by waruqi** [comment]
@shrinktofit 这个应该可以了，你再试试 相关pr见：https://github.com/xmake-io/xmake/pull/543
