### ISSUE TITLE
升级VS后导致PCH报错

### ISSUE THREAD

**Issue by MaxwellGengYF** [xmake-io/xmake#5413]
### Xmake 版本

2.9.3

### 操作系统版本和架构

Windows

### 描述问题

更新VS后，出现报错：
error: Microsoft Visual C/C++ Version differs in PCH file vs. current file
执行 xmake c -a 后仍然报错，需要手动删除 .xmake .build 文件夹

### 期待的结果

检测到MSVC版本更新后，重新编译PCH

### 工程配置

set_pcxxheader("pch.h")

### 附加信息和错误日志

error: Microsoft Visual C/C++ Version differs in PCH file vs. current file

**Comment by waruqi** [comment]
再试试，`xmake update -s github:xmake-io/xmake#pch`
