### ISSUE TITLE
xmake qt.widgetapp规则无法配置将日志输出到终端

### ISSUE THREAD

**Issue by aiyolo** [xmake-io/xmake#5430]
### Xmake Version

v2.9.2+HEAD.6b6557c54

### Operating System Version and Architecture

windows11

### Describe Bug

1. 创建工程
```
xmake create -t qt.widgetapp test
```
2. 运行，日志没有输出到终端

### Expected Behavior

应该支持是否输出日志到终端。

### Project Configuration

```
target("test")
    add_rules("qt.widgetapp")
    add_headerfiles("src/*.h")
    add_files("src/*.cpp")
    add_files("src/mainwindow.ui")
```

### Additional Information and Error Logs

nothing

**Comment by star-hengxing** [comment]
`add_ldflags("/subsystem:console")`

**Comment by waruqi** [comment]
默认 gui 程序 windows subsystem 当然不会回显到 console，这个你要自己按上面方式配，或者自己代码里另开 console 绑定 stdout

 这个跟 xmake 又没啥关系，自己 google 下 win gui程序如果终端输出？

**Comment by aiyolo** [comment]
Thank you!
