### ISSUE TITLE
没有检测到 vcpkg 中的包

### ISSUE THREAD

**Issue by shrinktofit** [xmake-io/xmake#544]
`xmake.lua`：
```lua
target("3dsMax-glTF-plugin")
    set_kind("binary")
    add_files("src/*.cpp")
    add_requires("vcpkg::nlohmann_json")
```

构建命令：
```ps1
> xmake f -p windows -a x64 -m debug -o "x:\Repos\xmake-test/build"
```

输出：
```
checking for the Microsoft Visual Studio (x64) version ... 2019
note: try installing these packages (pass -y to skip confirm)?
in vcpkg:
  -> vcpkg::nlohmann_json  
please input: y (y/n)
y
  => install vcpkg::nlohmann_json  .. failed                                                                                                                                                                     
if you want to get verbose errors, please see:
```

但是实际上我的 vcpkg 里安装了 `nlohmann_json`：
![image](https://user-images.githubusercontent.com/28807867/63400373-23bdcd00-c406-11e9-86c7-60162e22ef20.png)

**Comment by waruqi** [comment]
可能是vcpkg里面纯头文件的检测失败，导致重新安装，vcpkg给报错了。。你可以加上 -c -v -D贴下详细输出，我分析下

```console
xmake f -p windows -a x64 -m debug -o "x:\Repos\xmake-test/build" -c -v -D
```

另外，nlohmann_json 这个包，xmake的官方仓库原生就有，不用从vcpkg里面安装使用

```lua
add_requires("nlohmann_json")
```

直接引用就行了，从xmake-repo官方仓库中来下载安装。

**Comment by shrinktofit** [comment]
```
PS X:\Repos\xmake-test> xmake f -p windows -a x64 -m debug -o "x:\Repos\xmake-test/build" -c -v -D
checking for the vswhere.exe ... C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
checking for the cl.exe ... ok
checking for the Microsoft Visual Studio (x64) version ... 2019
checking for the unzip ... ok
checking for the git ... ok
checking for the gzip ... ok
checking for the tar ... ok
checking for the ping ... ok
pinging for the host(gitee.com) ... 18 ms
pinging for the host(gitlab.com) ... 254 ms
checking for the nmap ... no
pinging for the host(github.com) ... 65535 ms
finding nlohmann_json from vcpkg ..
checking for the vcpkg directory ... X:\Repos\vcpkg
checking for the vcpkg::nlohmann_json ... no
note: try installing these packages (pass -y to skip confirm)?
in vcpkg:
  -> vcpkg::nlohmann_json
please input: y (y/n)
```

**Comment by waruqi** [comment]
另外，add_requires 属于全局根配置接口，不需要任何target，你用的也不对，请仔细看下文档描述，readme里面也有examples，也不是这么用的，你仔细看下

```lua
add_requires("nlohmann_json")
target("3dsMax-glTF-plugin")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("nlohmann_json")
```

**Comment by shrinktofit** [comment]
> 另外，add_requires 属于全局根配置接口，不属于任何target，你用的也不对，请仔细看下文档描述，readme里面也有examples，也不是这么用的，你仔细看下
> 
> ```lua
> add_requires("nlohmann_json")
> target("3dsMax-glTF-plugin")
>     set_kind("binary")
>     add_files("src/*.cpp")
>     add_packages("nlohmann_json")
> ```

收到

**Comment by waruqi** [comment]
> Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Failed at [X:\Repos\vcpkg\toolsrc\src\vcpkg\packagespec.cpp(82)] with message:
Contains invalid characters. Only alphanumeric lowercase ASCII characters and dashes are allowed

vcpkg自己报错了，你可以手动命令行敲vcpkg安装 测下，是否也会报错

**Comment by shrinktofit** [comment]
> > Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
> > Failed at [X:\Repos\vcpkg\toolsrc\src\vcpkg\packagespec.cpp(82)] with message:
> > Contains invalid characters. Only alphanumeric lowercase ASCII characters and dashes are allowed
> 
> vcpkg自己报错了，你可以手动命令行敲vcpkg安装 测下，是否也会报错

好的
