### ISSUE TITLE
windows 环境下，生成 CMakeLists.txt 文件，使用 cmake + Ninja + tcc 编译时报错 

### ISSUE THREAD

**Issue by ZCB1208** [xmake-io/xmake#5448]
### Is your feature request related to a problem? Please describe.

1. 生成 cmakelist 文件
`xmake project -k cmakelists` 
可以正常生成 CMakeList.txt 文件

1. 然后创建 cmake_build 文件夹，并进入 cmake_build 文件夹： 
`cd cmake_build`

1. 使用命令调用 cmake 编译 cmakelist 文件
`cmake .. -G Ninja`

1. 此时报错信息如下：
` The C compiler identification is unknown
CMake Error at CMakeLists.txt:11 (project):
  No CMAKE_C_COMPILER could be found.

The C compiler identification is unknown
CMake Error at CMakeLists.txt:11 (project):
  No CMAKE_C_COMPILER could be found.

Configuring incomplete, errors occurred!`

无法进行正常编译生成 ninja 文件

### Describe the solution you'd like

将 `set(CMAKE_C_COMPILER "tcc")` 这一行，移动至 CMakeLists.txt 最上面，即可解决问题

临时解决，让cmake 通过编译可以采用这种方式

### Describe alternatives you've considered

此种解决方案，在下一次生成 cmakelists 文件后又会无法解决，故而需要对 生成 cmakelist 文件的脚本进行修改

在文件 xmake\plugins\project\cmake\cmakelists.lua 文件中增加如下函数

```
function _add_CMAKE_C_COMPILER_first(cmakelists, target)
	cmakelists:print("# tmp fix tcc use xmake create cmakelists bug ")
	if config.get("toolchain") or target:get("toolchains") then
        local cc = target:tool("cc")
        if cc then
            cc = path.unix(cc)
            cmakelists:print("set(CMAKE_C_COMPILER \"%s\")", cc)
        end
	end
	cmakelists:print("")
end
```

再在函数` _generate_cmakelists` 中增加调用

```
-- _add CMAKE_C_COMPILER first 
	for _, target in table.orderpairs(project.targets()) do
		_add_CMAKE_C_COMPILER_first(cmakelists, target)
    end
```

原则上需要对下面生成的`set(CMAKE_C_COMPILER "tcc")` 内容注释掉，但是实际测试，不注释也没有问题，
暂时用这样不修改原有生成脚本的基础上可以解决问题

### Additional context

![image](https://github.com/user-attachments/assets/474628da-a12d-43d9-879b-736bd9fc8ceb)

![image](https://github.com/user-attachments/assets/29293961-84d4-4408-ad5b-24873ad9dc22)

![image](https://github.com/user-attachments/assets/ad7d55df-d7b4-4600-9256-0823b9aea386)

**Comment by waruqi** [comment]
xmake 可以直接编译干嘛不用？ xmake 可以直接生成 build ninja 干嘛不用？要这么饶两层？

另外，为啥移动至 CMakeLists.txt 最上面就可以，这不应该是 cmake 的 issues 么，为啥要改 xmake。。

**Comment by ZCB1208** [comment]
是的，确实是绕了两层，非常无奈公司要求就是必须要用使用 cmake + ninja ，原因在于国外的团队开发组用了这个组合，所以要求我们也要切换至这样。

虽然极力推荐 使用 xmake ，并阐述了个人的几个看法，无奈人微言轻，只能被迫这样的兼容设计，自己在开发与测试的时候，都是直接使用 xmake 进行的，方便很多。 目前在本地开发以及 cicd 测试的时候，我尽量都是使用 xmake 二 cmake 只是作为一个补充，只是为了符合公司要求而已。

虽然这确实是 cmake 的问题，但是目前我只能这样选择去做兼容，最终选择做出这样的提交，希望能为与我一样处境的开发者提供一些便利，确实找这个问题也是花费了一些时间，并不许想后续如我类似的开发者在遇到这样的问题就放弃l 这么好的工具，希望未来 xmake 能成为开发者的首选。看看我们国人做的多么优秀的工具，对洋人，洋工具能祛魅。

**Comment by waruqi** [comment]
这可能是由于 `project( C)` 里面有 language 设置，cmake 解析到这直接开始探测编译器了。所以 set compilers 得放到 project 之前才行。

可以试下这个 patch https://github.com/xmake-io/xmake/pull/5449

不过你这种搞法，之后会碰到很多问题的，有些特性问题 就没那么好规避了，毕竟多绕一层，就会损失一些 xmake 原有的特性，导致差异，还饶了两层。

尤其是一些 rules 目前还无法很好适配 project generator ，不光只是 cmakelists generator.

**Comment by waruqi** [comment]
既然你这公司硬性规避不让用，个人又想要用 xmake，其实个人建议，你通过 xmake 生成初始 cmakelists.txt 后，自己改改，然后同时维护，cmakelists.txt 和 xmake.lua 。。自己平常用 xmake.lua ，对外提供 cmakelists.txt 互不冲突，也不用每次去生成，后期也就是加加 files flags啥的 。

我自己也是这么搞得。

**Comment by waruqi** [comment]
我 merge 了，xmake update -s dev

**Comment by ZCB1208** [comment]
> 既然你这公司硬性规避不让用，个人又想要用 xmake，其实个人建议，你通过 xmake 生成初始 cmakelists.txt 后，自己改改，然后同时维护，cmakelists.txt 和 xmake.lua 。。自己平常用 xmake.lua ，对外提供 cmakelists.txt 互不冲突，也不用每次去生成，后期也就是加加 files flags啥的 。
> 
> 我自己也是这么搞得。

嗯呢，很好的建议，感谢，我也还是维护两份好了
