### ISSUE TITLE
设置本地编译器`gnu-rm`实际变成`gcc`

### ISSUE THREAD

**Issue by USTHzhanglu** [xmake-io/xmake#5453]
### Xmake 版本

2.9.3

### 操作系统版本和架构

win10 22H2

### 描述问题

xmake f -p cross --toolchain=gnu-rm -c -vD
实际上调用了本地的gcc
在cache/detect上
```lua
    ["find_program_gnu-rm_arch_cortex_m33_plat_cross_checktoolcxx"] = {
        gcc = "gcc"
    },
```

### 期待的结果

指向正常的交叉编译器

### 工程配置

```lua
set_arch("cortex_m33")
set_plat("cross")
set_toolchains("gnu-rm")
```

### 附加信息和错误日志

使用add_requires("gnu-rm"):
```lua
    ["find_program_gnu-rm_arch_cortex_m33_packages_gnu-rm_plat_cross_checktoolas"] = {
        ["arm-none-eabi-gcc"] = [[C:\Users\lu.zhang02\AppData\Local\.xmake\packages\g\gnu-rm\2021.10\266dbd53269e4e4e8702faacd7f5944d\bin\arm-none-eabi-gcc]]
    },
```

**Comment by waruqi** [comment]
走 --toolchain 指定交叉编译，得设置，--sdk 不然 xmake 不知道它在哪。

走 add_requires + set_toolchains 远程拉工具链，就不要再指定 --toolchain

另外，你配的也不对，package 和 toolchain 都没绑定

看下例子 https://github.com/xmake-io/xmake/blob/dev/tests/projects/package/toolchain_gnu_rm/xmake.lua

**Comment by USTHzhanglu** [comment]
> 走 --toolchain 指定交叉编译，得设置，--sdk 不然 xmake 不知道它在哪。
> 
> 走 add_requires + set_toolchains 远程拉工具链，就不要再指定 --toolchain
> 
> 另外，你配的也不对，package 和 toolchain 都没绑定
> 
> 看下例子 https://github.com/xmake-io/xmake/blob/dev/tests/projects/package/toolchain_gnu_rm/xmake.lua

 --toolchain 这个是用vscode插件时的指令,这么说的话插件是否应该增加个用户指定sdk的接口?

**Comment by waruqi** [comment]
插件里可以在 `additionalConfigArguments` 里自己配置各种附加参数
