### ISSUE TITLE
Failed to deserialize error message with -v -D flags

### ISSUE THREAD

**Issue by OpportunityLiu** [xmake-io/xmake#546]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
Serialize error displayed when `-v -D` is given for build process.

### Expected behavior
Same error output for build w/ or w/o any of verbose flags.

### Error output
If applicable, please add verbose the errors output to help us analyze your problem.

> If it is a xmake related compilation problem, please add the `-v -D` parameter and give the detailed compilation output information.
```
$xmake create -l cuda -P x
$cd x
$xmake f -p linux
$xmake
[  0%]: compiling.release src\main.cu
error: nvcc fatal   : Cannot find compiler 'cl.exe' in PATH
$xmake -D -v
checking for cuda devices
warning: failed to find cuda devices: nvcc fatal   : Cannot find compiler 'cl.exe' in PATH

configure
{
    clean = true
    arch = x64
    ccache = true
    vs = 2019
    theme = default
    cu = nvcc
    mode = release
    ndk_stdcxx = true
    host = windows
    cu-ccbin = clang
    kind = static
    buildir = build
    plat = linux
}
[  0%]: compiling.release src\main.cu
nvcc -c "-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\include" -gencode arch=compute_30,code=compute_30 -m64 -ccbin=clang -o build\\.objs\\x\\linux\\x64\\release\\src\\main.cu.o src\\main.cu
error: .\..\xmake\actions\build\main.lua:75: cannot deserialize "{stdout=\"nvcc fatal "... : (deserializing data):4: '<eof>' expected near 'stack'
stack traceback:
    [C]: in function 'error'
    [.\..\xmake\core\base\os.lua:762]: in function 'raise'
    [.\..\xmake\actions\build\main.lua:75]: in function 'catch'
    [.\..\xmake\core\sandbox\modules\try.lua:127]: in function 'try'
    [.\..\xmake\actions\build\main.lua:61]:
    [C]: in function 'load'
    [.\..\xmake\core\base\task.lua:508]: in function 'run'
    [.\..\xmake\core\main.lua:236]:
```
### Related Environment
Please provide the compilation or runtime environment information, for example: xmake version, operating system, etc.

**Comment by waruqi** [comment]
os.iorunv的时候 会抛  raise({errors=, stdout=,stderror=}) 然后 os.raiselevel里面去serialize 它，在utils.trycall 里面获取到errors后，再deseriablize 成 table 传递给 catch (errors)

**Comment by OpportunityLiu** [comment]
但是得到的error明显是
```
{errors=, stdout=,stderror=}stack:
...
...
```
这样的，看报错信息也看得出来（`'<eof>' expected near 'stack'`）。

**Comment by waruqi** [comment]
我dev上尝试修了下，你再试试，这边暂时没环境复现

**Comment by waruqi** [comment]
为什么会得到 `{errors=, stdout=,stderror=}stack:` 是因为 在 try/catch里面 

如果加了 -D 获取错误，try捕获到errors后会对errors追加stack信息，由于这个是有 errors已经被serialize 成了string，后面追加stack ，然后trycall返回后尝试deserialize就失败了，errors其实已经不是table了。。是"{xx}stack“字串了。。

https://github.com/xmake-io/xmake/blob/3e3541b38ed974217159037c2410ba701c0fcaf6/xmake/core/sandbox/modules/try.lua#L50-L55

这块还得再改进下，对启用-D的情况。。

**Comment by waruqi** [comment]
刚说的不对，其实即使在-D的时候，在追加stack之前，我已经处理掉 deseriablize 了。也不会有这问题。。怪了。。我这边暂时还没发复现问题。。你先试试dev的修复 看看可以了么。。

**Comment by OpportunityLiu** [comment]
好了，应该就是那里的问题

**Comment by waruqi** [comment]
之前在nvcc里整，确实能修复，不过只是压制了 raise({})的传递，所以并没解决根本原因，其根本原因是：process.runjobs里面 coroutine.resume 获取到traceback，会追加到errors上去，导致utils.trycall里面获取到的errors，附带了traceback，使得deserialize失败了。。

目前的解决办法是，在utils.trycall里面进一步作处理，对追加的traceback进行strip，将其封进errors obj内部。

不过nvcc里面我还是继续压制，不对外传递raise {}了。。你可以更新到dev后，revert nvcc.lua 再试试，应该也ok了。。

话说，lua 里面 error 没法原生支持抛 table 给 xpcall，目前的做法 确实比较麻烦些
