### ISSUE TITLE
mktemp usage messages during configure

### ISSUE THREAD

**Issue by ryandesign** [xmake-io/xmake#5464]
### Xmake Version

2.9.4

### Operating System Version and Architecture

Mac OS X 10.6 PowerPC

### Describe Bug

The following appears several times when running configure on old versions of macOS:

```
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
```

You appear to be calling `mktemp` with no arguments, which is not supported on old versions of macOS:

https://github.com/xmake-io/xmake/blob/216192e56b4fcfa664a7efe59c5b873a2f78adbb/configure#L206

You must supply a template or a prefix, for example:

`mktemp "${TMPDIR-/tmp}/tmp.XXXXXXXX"`

### Expected Behavior

no error messages during configure

### Project Configuration

?

### Additional Information and Error Logs

?

**Comment by waruqi** [comment]
try it again. `xmake update -s dev`

**Comment by ryandesign** [comment]
Thanks, 07b0d45634a870ee905776557d0a27436001276c looks good to me. Should the same change be made in core/src/tbox/tbox/configure?
