### ISSUE TITLE
wrong include flag when using system llvm

### ISSUE THREAD

**Issue by ilobilo** [xmake-io/xmake#5468]
### Xmake Version

2.9.3

### Operating System Version and Architecture

Fedora 40

### Describe Bug

when using ``add_requires("llvm")`` and `` add_packages("llvm")`` in a target, during C++ module dependency scanning, xmake adds ``-isystem /usr/include`` to compiler flags (because llvm headers are located there), that causes the compilation to fail on both libstdcxx and libcxx.
Example:
![image](https://github.com/user-attachments/assets/e987df21-35fb-4e32-82be-9be3ea96bfaf)
![image](https://github.com/user-attachments/assets/81009f85-1e44-4b40-8d0f-285aab697762)

### Expected Behavior

do not add ``-isystem /usr/include``

### Project Configuration

```lua
-- ...
add_requires("llvm", { system = true, kind = "library" })
-- ...
target("...")
-- ...
    add_packages("llvm")
-- ...
```

### Additional Information and Error Logs

screenshots provided above

**Comment by waruqi** [comment]
you can set `system = false` to disable system library. or set `external = false` to use `-I/usr/include` instead of `-isystem`

**Comment by ilobilo** [comment]
``external = false`` did the trick, thanks!
