### ISSUE TITLE
cmakelists 生成不支持编译器 flags

### ISSUE THREAD

**Issue by PolarLinda6** [xmake-io/xmake#5471]
### Xmake 版本

2.9.4

### 操作系统版本和架构

Windows 11 version 23H2

### 描述问题

xmake project -k cmakelists 生成 cmakelists
  1. 不支持编译器flags
  2. 特定编译参数丢失

### 期待的结果

```cmake
if(Clang)
    target_compile_options(Main PRIVATE -Wno-gnu-line-marker)
    target_compile_options(Main PRIVATE -fexperimental-library)  # 生成的 cmakelists 中我并没有找到这个参数
    target_link_options(Main PRIVATE -lc++)
elseif(Gcc)
    target_compile_options(Main PRIVATE -Wno-non-template-friend)
    target_compile_options(Main PRIVATE -fanalyzer)
    target_link_options(Main PRIVATE -lstdc++)
    target_link_options(Main PRIVATE -lbenchmark)
)
endif()
```

### 工程配置

```lua
add_cxxflags("clang::-Wno-gnu-line-marker", "gcc::-Wno-non-template-friend")
add_cxxflags("clang::-stdlib=libc++", "clang::-fexperimental-library", "gcc::-fanalyzer")
add_ldflags("clangxx::-lc++", "gxx::-lstdc++", "gxx::-lbenchmark")
```

### 附加信息和错误日志

![IMG_20240816_225343](https://github.com/user-attachments/assets/eb5be32e-f0a0-4c39-ac53-22a41f8b1f94)

**Comment by waruqi** [comment]
试下这个 patch https://github.com/xmake-io/xmake/pull/5487

```console
xmake update -s github:xmake-io/xmake#cmake
```

**Comment by PolarLinda6** [comment]
> 试下这个 patch #5487
> 
> ```
> xmake update -s github:xmake-io/xmake#cmake
> ```

我已经更新到了新的分支, 我遇到了一个问题:

`set(CMAKE_C_COMPILER "/usr/sbin/gcc") set(CMAKE_CXX_COMPILER "/usr/sbin/g++")` 会重复生成( 与 target 数目相同 )

<img width="556" alt="image" src="https://github.com/user-attachments/assets/7c75851e-8e6f-42dd-a838-3becde5eeff3">

**Comment by waruqi** [comment]
可以了么

**Comment by PolarLinda6** [comment]
> 可以了么

我遇到了新的问题:
set_runtimes 出现了错误, gcc clang 配置消失, msvc 配置错误

```lua
if "clang" == get_config("toolchain") then
  set_runtimes("c++_shared")
elseif "gcc" == get_config("toolchain") then
  set_runtimes("stdc++_static")
end
```

![image](https://github.com/user-attachments/assets/16952455-1565-46f0-8b3e-4e598a265651)

[CMakeLists.txt](https://github.com/user-attachments/files/16685070/CMakeLists.txt)
[xmake.lua.txt](https://github.com/user-attachments/files/16685078/xmake.lua.txt)

**Comment by waruqi** [comment]
不同的问题不要混一起，这个跟当前的 issues 无关。如果当前的 issues 确认已经修复，我就 close 了。。

其他的问题 单独开 issues

**Comment by PolarLinda6** [comment]
> 不同的问题不要混一起，这个跟当前的 issues 无关。如果当前的 issues 确认已经修复，我就 close 了。。
> 
> 其他的问题 单独开 issues

好的, 谢谢作者了
