### ISSUE TITLE
Add os.timestamp api

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#5472]
### 你在什么场景下需要该功能？

希望将构建时的Unix时间戳编码到程序中，为此需要获取当前系统时间，但xmake中只提供了文件修改时间os.mtime，没有直接获取时间的api；目前要编码时间只能分平台写script获取，非常麻烦（windows `Get-Date -UFormat %s`，unix `date +%s`）

### 描述可能的解决方案

增加os.timestamp或者os.systime api获取系统时间

**Comment by waruqi** [comment]
不是有 os.date 和 os.time 么

https://github.com/xmake-io/xmake/blob/c8e8e04d832288a0a7f4d5a90a89061f7951b0e0/xmake/actions/build/cleaner.lua#L68

**Comment by xq114** [comment]
文档里没搜到，看来是文档问题

**Comment by waruqi** [comment]
这两是 lua 原生接口，文档暂时没写，可以来 pr 补下
