### ISSUE TITLE
CSharp with mono

### ISSUE THREAD

**Issue by lualvsil** [xmake-io/xmake#5477]
### Is your feature request related to a problem? Please describe.

.

### Describe the solution you'd like

Adding support for C# projects using mono

**Comment by waruqi** [comment]
Currently I don't have time to support it, so if you're interested you can just open a pr to support it.

Also, csharp with mono and vs csharp use very different build tools, but we need to define a csharp language to unify the two toolchains.

It can take quite a bit of work.

I'm not sure how to use mono to build csharp programs at the moment. It would be nice to have a clear makefile or full build command and parameters. It would probably help a lot with support later on.
