### ISSUE TITLE
find_packages return nil for pkg-config packages

### ISSUE THREAD

**Issue by changephilip** [xmake-io/xmake#548]
### Describe the bug
trying to use system package in my project through following code.
For example inserting following code(from documentation) into hello project's xmake.lua:
`
option("zlib")
    set_showmenu(true)
    before_check(function (option)
        option:add(find_packages("pkg-config:zlib"))
    end)`

then "xmake".

### Error output
undefined  reference to zlib's functions

> /usr/bin/ld: main.c:(.text.startup+0x9c): undefined reference to `compress'
/usr/bin/ld: main.c:(.text.startup+0xb8): undefined reference to `uncompress'
collect2: error: ld returned 1 exit status

### Related Environment
xmake is installed through wget get.sh.
system is debian buster under WSL.
I have installed zlib-dev and zlib by apt and also checked that zlib.h\zconf.h\libz.so existed under default directories(/usr/include,/usr/libs/x86_64-linux-gnu/libz.so)

### Additional context
"pkg-config --list-all |grep zlib " output is also correct.
while I tried "xmake l" and then input with following:
`local abc=find_packages("zlib")`
 or
`local abc=find_packages("pkg-config:zlib")`
the return value both is nil.

**Comment by OpportunityLiu** [comment]
> local abc=find_packages("pkg-config:zlib")

in `xmake l` repl, each command runs in its own environment, so `local` is useless here

try `xmake l find_packages "pkg-config:zlib"`

**Comment by changephilip** [comment]
> 
> 
> > local abc=find_packages("pkg-config:zlib")
> 
> in `xmake l` repl, each command runs in its own environment, so `local` is useless here
> 
> try `xmake l find_packages "pkg-config:zlib"`
try `xmake l find_packages "pkg-config:zlib"` or `xmake l find_packages "zlib"`
now the shell only print：
`{}`

**Comment by waruqi** [comment]
You can try `pkg-config::zlib` and please enter to a non-project directory to run the following command. Because find_packages will cache the previous result in project.

xmake l find_packages pkg-config:zlib

or

```console
xmake l
> find_packages("pkg-config:zlib")
```

or 


```console
xmake l
> a = find_packages("pkg-config:zlib")
```

**Comment by waruqi** [comment]
Maybe ` pkg-config --libs --cflags zlib` only return `-lz` , so xmake cannot find include path.

You can try `xmake l find_packages system::zlib` again.

**Comment by changephilip** [comment]
@waruqi 
Thank you! Problem solved by `xmake l find_packages system::zlib`!

**Comment by waruqi** [comment]
I have improved it, you can update dev/master and try ut again.

xmake l find_packages zlib
