### ISSUE TITLE
checking for mingw directory ... no

### ISSUE THREAD

**Issue by yybbwc** [xmake-io/xmake#5496]
### Xmake Version

2.9.4

### Operating System Version and Architecture

win10 ltsc21

### Describe Bug

好像没找到mingw目录

### Expected Behavior

切换到mingw

### Project Configuration

一大堆

### Additional Information and Error Logs

checking for architecture ... x86_64
checking for mingw directory ... no
error: @programdir\core\main.lua:329: @programdir\actions\config\main.lua:157: target(scite): toolchain not found!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:973]: in function 'raiselevel'
    [@programdir\core\sandbox\modules\utils.lua:143]: in function 'assert'
    [@programdir\actions\config\main.lua:157]: in function '_check_target_toolchains'
    [@programdir\actions\config\main.lua:403]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:275]:
    [@programdir\core\base\task.lua:491]: in function 'run'
    [@programdir\core\main.lua:327]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:406]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:973: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:329: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:406: in function <@programdir\core\base\scheduler.lua:399>

**Comment by yybbwc** [comment]
我用的是草莓perl中附带的mingw

**Comment by yybbwc** [comment]
https://strawberryperl.com/ 这是草莓perl的官网

**Comment by star-hengxing** [comment]
用 scoop 装一个正常的 mingw，或者用 scoop 装 msys 再装 mingw 也行。。

**Comment by yybbwc** [comment]
我搞定了

**Comment by yybbwc** [comment]
在find_mingw.lua的大概59行加这个条件 or p:find(string.ipattern("strawberry%-perl[^\\/]*[\\/]c[\\/]bin$"))

**Comment by yybbwc** [comment]
~~~
        if not sdkdir then
            local pathenv = os.getenv("PATH")
            if pathenv then
                local buildhash_pattern = string.rep('%x', 32)
                local match_pattern = "[\\/]packages[\\/]%w[\\/].*mingw.*[\\/][^\\/]+[\\/]" .. buildhash_pattern .. "[\\/]bin"
                for _, p in ipairs(path.splitenv(pathenv)) do
                    print(p)
                    if (p:find(match_pattern) or p:find(string.ipattern("mingw[%w%-%_%+]*[\\/]bin")) or p:find(string.ipattern("strawberry%-perl[^\\/]*[\\/]c[\\/]bin$")))
                    and path.filename(p) == "bin" 
                    and os.isdir(p) then
                        sdkdir = path.directory(p)
                        break
                    end
                end
            end
        end
~~~

**Comment by waruqi** [comment]
指定下 `--mingw=/xxxx/mingw` 就行了，自动找，智能找常规位置。不保证一定能找到
