### ISSUE TITLE
live status and progress visualisation - build graph

### ISSUE THREAD

**Issue by marcotrosi** [xmake-io/xmake#5500]
### Is your feature request related to a problem? Please describe.

not related to a problem

### Describe the solution you'd like

I don't want to formulate it as a feature request, but more as a question to ask for your opinion.

Imagine xmake could be started as a build-daemon, and it would always know the current state, means which files have changed or are missing and therefore which build paths/dependencies have to be built. Imagine we could open a local website or GUI and see the dependency graph visualised as e.g. a tree, for example something like this https://codepen.io/ericdrowell/pen/qLYrEm or this https://marvl.infotech.monash.edu/webcola/examples/unconstrainedsmallworld.html
For example in the beginning the nodes would be grey, xmake could check the first level of existing files (e.g. a list of C and Header files) and color them green if they exist, or red if they are missing, or orange if there is no read access. All nodes created from these source files would be grey at first, as they don't exist yet. Then if you start building the graph would colorise the strands and show which files is currently created and the tree would slowly get greener and greener from bottom to top until the final binary/library has been created. When you change a file the graph colors immediately get adapted to the new situation and you would immediately see which files get built again. It could also start building in the background with low priority.

so that's the idea, a live status and progress graph, maybe a bit interactive. maybe you click on the nodes and directly trigger only certain paths. And it helps to visually check if the xmake configuration is correct.

maybe instead xmake could only provide the data so that anyone can write such graphical interface/visualisation.

what excites the most is that I have not seen such thing from any build tool, and I would love to see xmake being the first build tool with such feature.

what's your opinion?

**Comment by waruqi** [comment]
It seemed like a good idea, but I didn't have time to develop it. Also, the current architecture would make it difficult to implement it, and would probably require a lot of refactoring work.

**Comment by marcotrosi** [comment]
> It seemed like a good idea, but I didn't have time to develop it. Also, the current architecture would make it difficult to implement it, and would probably require a lot of refactoring work.

thanks for your reply :-)
then of course it doesn't make sense to work on that.
I will close the ticket.
have a great day, keep it up.
