### ISSUE TITLE
error: cannot get program for mrc

### ISSUE THREAD

**Issue by yybbwc** [xmake-io/xmake#5513]
### Xmake 版本

2.8.6

### 操作系统版本和架构

win10 21h1

### 描述问题

error: cannot get program for mrc

### 期待的结果

能编译rc文件

### 工程配置

target("gframe")
  set_kind("binary")
  
--~   add_defines("NO_IRR_COMPILE_WITH_DIRECT3D_9_")
--~   add_defines("NO_IRR_COMPILE_WITH_DIRECTINPUT_JOYSTICK_")
  add_defines("_IRR_STATIC_LIB_")
  add_defines("UNICODE")
  add_defines("YGOPRO_USE_IRRKLANG")
  add_defines("_IRR_WCHAR_FILESYSTEM")
  
  add_deps("event")
  add_deps("freetype")
  add_deps("irrlicht")
  add_deps("lua")
  add_deps("lzma")
  add_deps("ocgcore")
  add_deps("spmemvfs")
  add_deps("sqlite3")
  
  add_includedirs("../event/include")
  add_includedirs("../freetype/include")
  add_includedirs("../irrklang/include")
  add_includedirs("../irrlicht/include")
  add_includedirs("../ocgcore")
  add_includedirs("../sqlite3")
  
  add_ldflags("-mwindows")
  
  add_linkdirs("../irrklang/lib/Win32-gcc")
  
  add_links("irrklang")
  
  add_syslinks("gdi32")
  add_syslinks("imm32")
  add_syslinks("kernel32")
  add_syslinks("opengl32")
  add_syslinks("user32")
  add_syslinks("winmm")
  add_syslinks("ws2_32")
  
  add_files("*.cpp")
  add_files("../rc/*.rc")

### 附加信息和错误日志

error: @programdir\core\main.lua:314: @programdir\actions\build\main.lua:148:
 @programdir\modules\async\runjobs.lua:320: ...amdir\core\sandbox\modules\imp
ort\core\tool\compiler.lua:37: cannot get program for mrc
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:949]:
    [...amdir\core\sandbox\modules\import\core\tool\compiler.lua:37]: in func
tion 'load'
    [@programdir\modules\private\action\build\object.lua:40]: in function 'sc
ript'
    [@programdir\modules\private\action\build\object.lua:122]: in function 'b
uild_object'
    [@programdir\modules\private\action\build\object.lua:147]: in function 'j
obfunc'
    [@programdir\modules\async\runjobs.lua:237]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:949: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:314: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\cor
e\base\scheduler.lua:397>

**Comment by yybbwc** [comment]
我解决了

~~~
xmake f -p mingw -c
~~~

**Comment by waruqi** [comment]
那我就关了
