### ISSUE TITLE
xmake.lua脚本中，特定写法配置不生效的问题

### ISSUE THREAD

**Issue by zhouqingyi123** [xmake-io/xmake#5517]
### Xmake 版本

2.9.4

### 操作系统版本和架构

Windows 11 x64

### 描述问题

**问题1**：如下图所示，在is_plat("windows")的条件块中，通过set_config("vs", “2017”)设置vs的版本时不生效（我的电脑同时安装了2017和2022）,还是使用的2022进行编译，但是写在条件块外面，是可以生效的（如上面注释部分）。

![image](https://github.com/user-attachments/assets/d39a650e-5165-4abb-9d8a-c3f6096baf4e)

**问题2**：如下图所示，当我通过在on_load脚本域中写target:add("includedirs", xxx, {interface = true})来设置头文件目录时，依赖它的子target无法搜索到这个头文件目录，看上去add并没生效。但是我在描述域写add_inculdedirs时是可以生效的。

![image](https://github.com/user-attachments/assets/e9b17edf-fd9b-4f3f-b281-9da2ca32d3c7)

下面的demo1中包含了这两个问题。

[demo1.zip](https://github.com/user-attachments/files/16763559/demo1.zip)

### 期待的结果

希望上图的两个场景，每个场景对应的出问题的写法能正常生效，当然，如果是因为用法不对导致的，请教一下正确的用法。

### 工程配置

```lua
set_project("demo1")
set_version("1.0.0")

add_rules("mode.debug", "mode.release")

-- 设置编译器
-- set_config("toolchain", "msvc")
-- set_config("vs", "2017")
if is_plat("windows") then
    set_config("toolchain", "msvc")
    set_config("vs", "2017")
    if is_mode("debug") then
        set_runtimes("MDd")
    else
        set_runtimes("MD")
    end
elseif is_plat("linux") then
    set_config("toolchain", "gcc")
end

target("version")
    add_rules("c++")
    set_kind("phony")
    add_configfiles("src/config.h.in")

    -- 有效
    -- add_includedirs("./$(buildir)/config", {interface = true})

    on_load(function (target)
        local configDir = "./$(buildir)/config"
        target:set("configdir", configDir)
        target:add("includedirs", configDir, {interface = true}) -- 无效
    end)

target("demo1")
    add_deps("version")
    set_kind("binary")
    add_files("src/*.cpp")

```

### 附加信息和错误日志

提交的demo1应该可以复现

**Comment by waruqi** [comment]
1. see https://github.com/xmake-io/xmake/issues/5454#issuecomment-2282806877
2. 脚本域不会自动处理相对路径，自己走 `path.join(os.scriptdir(), "xxx")`，或者 `os.projectdir()` 拼下

**Comment by zhouqingyi123** [comment]
@waruqi 感谢回复，第1个问题明白了，这种时候就只能用os.host()来获取当前主机的平台。但是第二个问题还是存在，麻烦看看我改的是否正确呢？通过打印这个绝对路径，我确认路径是没错的。

![image](https://github.com/user-attachments/assets/9ac7c593-98ea-486b-a80c-ca8227e1a8db)

**Comment by waruqi** [comment]
不要用 `$(buildir)`

**Comment by zhouqingyi123** [comment]
@waruqi 好的，改成用模块提供的函数来获取build路径进行设置确实名为有问题了。这里再请教一下，这是什么原因呢？脚本域里使用$(builder)得到的字符串通过print打印出来看也是正确的，感觉也能解析到这个内置变量，但就如上一个回复的图中那样，用它拼接而成的绝对路径就有问题。

**Comment by waruqi** [comment]
内置变量主要是给描述域的，脚本域上百个模块，上千个 api ，不可能每个接口，都给支持处理一遍

**Comment by zhouqingyi123** [comment]
@waruqi 好的，感谢解惑
