### ISSUE TITLE
在qt环境下编译debug版本程序，可执行文件无法正常运行

### ISSUE THREAD

**Issue by buaayhq** [xmake-io/xmake#553]
### 描述问题

xmake 2.2.8在windows环境下编译qt程序，release版能正常运行，而debug版本无法运行。

### 期待的结果

release版本和debug版本都能正常运行

### 错误信息

运行debug版本的exe程序，无反应或者直接退出。

*xmake 编译提示：*
>  link.exe -libpath:build\\\\windows\\\\x64\\\\debug -libpath:F:\\\\Qt\\\\Qt5.9.6\\\\5.9.6\\\\msvc2017_64\\\\lib -debug -pdb:build\\windows\\x64\\debug\\ThumbNailer.pdb threadweaver.lib Qt5Cored.lib Qt53DAnim 
ation.lib Qt53DAnimationd.lib Qt53DCore.lib Qt53DCored.lib Qt53DExtras.lib Qt53DExtrasd.lib Qt53DInput.lib Qt53DInputd.lib Qt53DLogic.lib Qt53DLogicd.lib Qt53DQuick.lib Qt53DQuickAnimation.lib Qt53DQuickAnimationd.lib Qt53DQuickd.lib Qt53DQuickExtras.lib Qt53DQuickExtrasd.lib Qt53DQuickInput.lib Qt53DQuickInputd.lib Qt53DQuickRender.lib Qt53DQuickRenderd.lib Qt53DQuickScene2D.lib Qt53DQuickScene2Dd.lib Qt53DRender.lib Qt53DRenderd.lib Qt5AccessibilitySupport.lib Qt5AccessibilitySupportd.lib Qt5AxBase.lib Qt5AxBased.lib Qt5AxContainer.lib Qt5AxContainerd.lib Qt5AxServer.lib Qt5AxServerd.lib Qt5Bluetooth.lib Qt5Bluetoothd.lib Qt5Bootstrap.lib Qt5Charts.lib Qt5Chartsd.lib Qt5Concurrent.lib Qt5Concurrentd.lib Qt5Core.lib Qt5DataVisualization.lib Qt5DataVisualizationd.lib Qt5DBus.lib Qt5DBusd.lib Qt5Designer.lib

### 相关环境

xmake版本：2.2.8
操作系统：windows 10, visual studio 2017

### 其他信息
如前面的编译输出信息，debug版本的库在链接的时候同时也链接了release版本的库，debug和release版本库同时存在
经过我的测试，在xmake 2.2.6版本中把
rules->qt->load.lua文件中的_find_static_links函数的第
45行
if (is_mode("debug") and basename:endswith(debug_suffix)) or ( not basename:endswith(debug_suffix)) 修改为
if (is_mode("debug") and basename:endswith(debug_suffix)) or (not is_mode("debug") and not basename:endswith(debug_suffix)) then
该问题不再出现。

**Comment by waruqi** [comment]
@buaayhq 赞！如果找到问题原因了，这种小改动直接帮忙提个pr上来就好了，可以在github上相关lua文件页面点edit就行了。。

**Comment by waruqi** [comment]
dev上我修复了，你更新下试试，`xmake update -s dev`

**Comment by buaayhq** [comment]
@waruqi 可以了，我这边测试没有问题，谢谢。
