### ISSUE TITLE
xmake无法将交叉链参数正确传向使用autoconf的依赖包

### ISSUE THREAD

**Issue by Redbeanw44602** [xmake-io/xmake#5530]
### Xmake 版本

v2.9.4+20240729

### 操作系统版本和架构

Manjaro Linux

### 描述问题

我正在 x86_64 主机上编译到 aarch64，从 `-v` 的输出结果看，没有向 `./configure` 传递交叉链信息和 `--host` 参数等（已在错误日志中标出）

configure 完成后，依赖包使用错误的工具链编译并链接，之后又使用正确的工具链进行 test，test 失败。

### 期待的结果

> package.tools.autoconf 和 package.tools.cmake 模块都是可以支持 mingw/cross/iphoneos/android 等交叉编译平台和工具链的，xmake 会自动传递对应的工具链进去，用户不需要做任何其他事情。

摘自[文档](https://xmake.io/#/zh-cn/package/local_3rd_source_library?id=%e9%9b%86%e6%88%90-autoconf-%e4%bb%a3%e7%a0%81%e5%ba%93)

因此这应该是一个Bug，希望作者能及时修复 :)

### 工程配置

```
add_requires('lame 3.100')

target("test")
    add_packages("lame")
    set_kind("binary")
    add_files("test.cpp")
```

### 附加信息和错误日志

输入：
```
xmake f -p linux -a arm64-v8a -m debug --cross="aarch64-linux-gnu-" -v
```

输出：
```
...
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> lame 3.100 
please input: y (y/n/m)

checking for ping ... /usr/bin/ping
pinging the host(downloads.sourceforge.net) ... 65535 ms
/usr/bin/tar -xf lame-3.100.tar.gz -C source.tmp
./configure --enable-nasm --enable-shared=no --with-pic --prefix=/home/username/.xmake/packages/l/lame/3.100/0bccc3af89224cd588fed2fa2505d91d --with-pic ###BUG
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu ###BUG
...
/usr/lib/gcc/aarch64-linux-gnu/6.5.0/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible /home/username/.xmake/packages/l/lame/3.100/0bccc3af89224cd588fed2fa2505d91d/lib/libmp3lame.a when searching for -lmp3lame
/usr/lib/gcc/aarch64-linux-gnu/6.5.0/../../../../aarch64-linux-gnu/bin/ld: cannot find -lmp3lame
collect2: error: ld returned 1 exit status
> checking for c includes(lame/lame.h)
> checking for c funcs(lame_encode_buffer)
> checking for c links(mp3lame)
> checking for c snippet(has_cfuncs)
error: execv(/usr/bin/aarch64-linux-gnu-g++ -o /tmp/.xmake1000/240828/_C8BC95B7C77948208374AC0B68BE1760.b /tmp/.xmake1000/240828/_C8BC95B7C77948208374AC0B68BE1760.o -L/home/username/.xmake/packages/l/lame/3.100/0bccc3af89224cd588fed2fa2505d91d/lib -lmp3lame) failed(1)
  => install lame 3.100 .. failed
error: install failed!
```

**Comment by waruqi** [comment]
目前只有 `xmake f -p cross` 切到 cross 平台才会作为交叉编译透传工具链

**Comment by Redbeanw44602** [comment]
目前 xrepo 对 cross 平台支持似乎不是特别好，我看了一下（用到的依赖包里）`on_install` 如果带有平台参数（`linux`/`windows`/`mingw`）几乎没有一个是考虑了 `cross` 平台的。

或许一个叫 `cross` 的平台本身让人有些费解？cmake 中使用交叉编译一般要传工具链、目标平台的系统类型和处理器架构，按理说 `-p linux -a arm64-v8a --cross="aarch64-linux-gnu-"` 已将需要使用的东西都表达了。（本人理解，如果有不对恳请指正）

另外在尝试安装使用 cmake 的依赖包时（`-p linux`）是传递了完整的交叉链信息的，如 `yaml-cpp`：
```
...
  => download https://github.com/jbeder/yaml-cpp/archive/refs/tags/0.8.0.tar.gz .. ok
checking for aarch64-linux-gnu-gcc ... /usr/bin/aarch64-linux-gnu-gcc
checking for the c compiler (cc) ... aarch64-linux-gnu-gcc
checking for aarch64-linux-gnu-gcc ... /usr/bin/aarch64-linux-gnu-gcc
checking for the c++ compiler (cxx) ... aarch64-linux-gnu-gcc
checking for aarch64-linux-gnu-gcc ... /usr/bin/aarch64-linux-gnu-gcc
checking for the assember (as) ... aarch64-linux-gnu-gcc
checking for aarch64-linux-gnu-gcc-ar ... /usr/bin/aarch64-linux-gnu-gcc-ar
checking for the static library archiver (ar) ... aarch64-linux-gnu-gcc-ar
checking for aarch64-linux-gnu-g++ ... /usr/bin/aarch64-linux-gnu-g++
checking for the linker (ld) ... aarch64-linux-gnu-g++
checking for aarch64-linux-gnu-gcc-ranlib ... /usr/bin/aarch64-linux-gnu-gcc-ranlib
checking for the archive index generator (ranlib) ... aarch64-linux-gnu-gcc-ranlib
checking for /usr/bin/aarch64-linux-gnu-gcc ... ok
checking for flags (-fPIC) ... ok
checking for flags (-fPIC) ... ok
checking for flags (-fPIC) ... ok
checking for /usr/bin/aarch64-linux-gnu-g++ ... ok
checking for flags (-fPIC) ... ok
checking for aarch64-linux-gnu-g++ ... /usr/bin/aarch64-linux-gnu-g++
checking for the shared library linker (sh) ... aarch64-linux-gnu-g++
checking for flags (-fPIC) ... ok
checking for cmake ... /usr/bin/cmake
/usr/bin/cmake -DYAML_CPP_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DYAML_BUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/home/username/.xmake/packages/y/yaml-cpp/0.8.0/5cee0c2bc67a480fba56397b7957ccd9 -DCMAKE_INSTALL_LIBDIR:PATH=lib -G "Unix Makefiles" -DCMAKE_FIND_USE_INSTALL_PREFIX=0 "-DCMAKE_CXX_LINK_EXECUTABLE=/usr/bin/aarch64-linux-gnu-g++ <FLAGS> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>" -DCMAKE_FIND_USE_CMAKE_SYSTEM_PATH=0 -DHAVE_FLAG_SEARCH_PATHS_FIRST=0 -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=BOTH -DCMAKE_C_COMPILER=/usr/bin/aarch64-linux-gnu-gcc -DCMAKE_OSX_SYSROOT= -DCMAKE_STATIC_LINKER_FLAGS= -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=BOTH -DCMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g++ -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=BOTH -DCMAKE_AR=/usr/bin/aarch64-linux-gnu-gcc-ar -DCMAKE_RANLIB=/usr/bin/aarch64-linux-gnu-gcc-ranlib -DCMAKE_ASM_COMPILER=/usr/bin/aarch64-linux-gnu-gcc -DCMAKE_SYSTEM_NAME=Linux "-DCMAKE_CXX_FLAGS_RELEASE= -O3 -DNDEBUG" -DCMAKE_STATIC_LINKER_FLAGS_RELEASE= -DCMAKE_SHARED_LINK
...
```

**Comment by waruqi** [comment]
> 目前 xrepo 对 cross 平台支持似乎不是特别好，我看了一下（用到的依赖包里）on_install 如果带有平台参数（linux/windows/mingw）几乎没有一个是考虑了 cross 平台的。

这话说的，支持 cross 的包，没有一千，几百个还是有的，可以到 https://xrepo.xmake.io/#/packages/cross 上面看，全是支持 cross 的。

不能光看 on_install 的参数。。`on_install(function (package))` 这种没平台限制，全平台支持的包也都多了去了，都全平台了，cross 当然也支持。

> 或许一个叫 cross 的平台本身让人有些费解？cmake 中使用交叉编译一般要传工具链、目标平台的系统类型和处理器架构，按理说 -p linux -a arm64-v8a --cross="aarch64-linux-gnu-" 已将需要使用的东西都表达了。（本人理解，如果有不对恳请指正）

本身这么搞没问题，xmake 对 target 编译这样也支持交叉编译。。但是对包的处理，这会复杂化 on_install 。。

像 windows 这种在包构建中，都是平台跟 msvc 绑定的，才能最大化简化包的构建配置，并且 ci 的测试资源有限，runtimes/compiler/mode 各种组合下，一个平台的 ci 压测，都已经十几个 job 了。。再去切 toolchain ，就是多一个数量级，不光是包配置会更复杂难维护，ci 资源也不够。。

所以交叉编译，只能独立到 cross 平台，单独压测。单独维护 。 linux 目前算好的了，至少能让你传完整 toolchain, (--toolchain=, set_toolchain) 。。但是散装的 `--cross=xx` 肯定支持不了。

**Comment by star-hengxing** [comment]
xmake 定义的 cross 平台，语义上确实有点含糊，但 `is_cross` 还是明确区分了 host 和 arch。
https://github.com/xmake-io/xmake/blob/0cfd96928e1f56c4f9dd9a82662ec67313da58e2/xmake/core/base/private/is_cross.lua#L25-L51

**Comment by Redbeanw44602** [comment]
> 不能光看 on_install 的参数。。on_install(function (package)) 这种没平台限制，全平台支持的包也都多了去了，都全平台了，cross 当然也支持。

当然，所以我限定了“带有平台参数”。问题是这样的带有平台参数的包很多，大多数又不考虑 `cross` ， `-p linux` 又可以编译😂...

我觉得测试交叉平台的包意义不是很大，交叉链也太多了，测试不完的... 还有的厂商定制交叉链...

如果说为了节约资源弄一个 cross 平台个人认为还是欠考虑了，github ci并行有限制，但是作业可以排队的。

---

还有就是目前的问题是 cmake 的依赖包会传递交叉链参数（散装的toolchain），但 autoconf 的依赖包不会传相应参数给 configure...

**Comment by waruqi** [comment]
> 当然，所以我限定了“带有平台参数”。问题是这样的带有平台参数的包很多，大多数又不考虑 cross ， -p linux 又可以编译😂...

所以，这种提个 pr 过来改进下包不就完事了么

> 我觉得测试交叉平台的包意义不是很大，交叉链也太多了，测试不完的... 还有的厂商定制交叉链...

ci 过一遍，只能能提前规避 90% 以上的问题，否则 issues 还不得打爆，我哪有时间天天处理这种问题。

> 如果说为了节约资源弄一个 cross 平台个人认为还是欠考虑了，github ci并行有限制，但是作业可以排队的。

不光是 ci 资源，还有人力资源。ci 跪了，还不是得维护者去修，就一个 cross 平台，我们都修的累死累活了。。特么要 linux 各种平台全开 ci job 跑。。那提交一个包。我们不得修的累死。

你看下现在的 pr 上的 ci ，一个 pr 都已经几十个 job 了，linux 下，还单独开了两， linux + gcc，linux + clang 

有时候一个 job 跪，都要修一个礼拜才能解决。。这些都是需要时间人力的支撑的，不是你说多开个 ci 排队跑跑就完事了的。。跑出来要有人修啊。。

如果你有兴趣维护，专门处理新开的 ci job 上的所有 error 修复，那我不介意多开几个 cross 平台 ci 去测试。

**Comment by waruqi** [comment]
> 还有就是目前的问题是 cmake 的依赖包会传递交叉链参数（散装的toolchain），但 autoconf 的依赖包不会传相应参数给 configure...

包安装，散装参数一概不支持，请走 `--toolchain` 和 set_toolchain 切工具链。

**Comment by Redbeanw44602** [comment]
最后确认一下，意思是 cmake 支持 --cross 提供的“散装参数”是bug，autoconf 不支持是正常的？

**Comment by Redbeanw44602** [comment]
如果是对 autoconf 支持有问题而您比较忙的话，有兴趣提一个 pr 来帮忙修。

**Comment by waruqi** [comment]
> 最后确认一下，意思是 cmake 支持 --cross 提供的“散装参数”是bug，autoconf 不支持是正常的？

目前对包的安装，不管是 cmake,meson/autoconf ，我都没对散装 cross 进行支持，只支持 toolchain ，这里面考虑的东西太多了。

- 不光要处理 `--cross`, 还有 `--ld/--cxx/--cc/--ldflags` 等一堆散装参数
- 还要处理 package buildhash ，确保没有兼容性冲突，走 toolchain 就不会有这个问题
- 还得处理包的 package:tool() package:toolchains() ，确保获取没问题
- 还要处理包依赖工具链传递，处理交叉编译下的 host 包工具链分离
- 还要处理散装下包 on_test 检测时候的 工具链一致性
- 处理 tools.cmake/meson/autoconf 散装下透传
- 还得处理判断 linux 当前是否处于交叉编译，还是本机 gcc/clang 编译，也就是要改进 is_cross 精准性
- 还有很多细节处理。。

没那么简单

**Comment by Redbeanw44602** [comment]
> 目前对包的安装，不管是 cmake,meson/autoconf ，我都没对散装 cross 进行支持，只支持 toolchain ，这里面考虑的东西太多了。

额... 看[这里](https://github.com/xmake-io/xmake/issues/5530#issuecomment-2316569399)，cmake 是支持的。

**Comment by waruqi** [comment]
> > 目前对包的安装，不管是 cmake,meson/autoconf ，我都没对散装 cross 进行支持，只支持 toolchain ，这里面考虑的东西太多了。
> 
> 额... 看[这里](https://github.com/xmake-io/xmake/issues/5530#issuecomment-2316569399)，cmake 是支持的。

那是因为你指定了 -a arm64 ，正好触发到了 cross 平台，https://github.com/xmake-io/xmake/blob/87630c8cf33105cc8c000e73cb7b67a2decfe02d/xmake/modules/package/tools/cmake.lua#L906

但这并不是特意支持，只是碰巧切进去了而已。。如果你没设置 arch ，仅仅设置 --cross=, -ld 散装设置参数，照样不行。。
