### ISSUE TITLE
交叉工具链中check报错

### ISSUE THREAD

**Issue by MaxwellGengYF** [xmake-io/xmake#5541]
### Xmake Version

v2.9.4+dev.c64cb5aa8,

### Operating System Version and Architecture

Windows

### Describe Bug

内部使用 set_toolchains(llvm) 且该target没有使用包管理的情况下出现报错：
error: we cannot get tool(cxx) in toolchain(llvm) with windows/x64, because it has been not checked yet!

### Expected Behavior

允许内部使用不同工具链

### Project Configuration

target("xx")
set_toolchains("llvm")

> xmake f --toolchain=msvc -c

### Additional Information and Error Logs

error: error: we cannot get tool(cxx) in toolchain(llvm) with windows/x64, because it has been not checked yet!

**Comment by waruqi** [comment]
我改成 warning 了，不过我还是建议加上 check ，否则某些状态可能是不对的。
