### ISSUE TITLE
add_cxxflags()不起作用

### ISSUE THREAD

**Issue by Ultraman95** [xmake-io/xmake#555]
vs2019编译工程出错：
libeay32.lib(x_x509.obj) : error LNK2026: 模块对于 SAFESEH 映像是不安全的。
所以要加add_cxxflags("-SAFESEH:NO")，但是加了之后，生成工程依然编译不行

**Comment by Ultraman95** [comment]
链接器--->命令行--->其他选项要加入/SAFESEH:NO
这个在xmake.lua脚本中该如何加

**Comment by Ultraman95** [comment]
还有就是C/C++-->常规--->多处理器编译，该怎么在xmake.lua脚本中设置

**Comment by waruqi** [comment]
请描述清楚你的上下文，是 xmake命令行编译，还是生成的 vs工程编译，还是用的vsxmake生成的工程编译。。

如果是命令行编译，请加上-v 贴下完整的编译输出信息，`xmake -v`

如果是用的老的生成的vs工程生成，那么可以先尝试命令行编译确认是否ok，或者切到新版vsxmake生成工程

如果是 `-SAFESEH:NO`没被设置到cl.exe，那么加上force，强制设置下，`add_cxxflags("-SAFESEH:NO", {force = true})`

如果设置生效了，还是报错，

**Comment by OpportunityLiu** [comment]
是给link的参数，跟cxxflags没啥关系吧

**Comment by waruqi** [comment]
> 是给link的参数，跟cxxflags没啥关系吧

确实，这个是link error，得放置到 add_ldflags里面去

**Comment by Ultraman95** [comment]
现在的情况是这样的，主要是引用了openssl库引起的

以下是我的xmake.lua
set_project("mdkernel")

-- add modes: debug and release 
add_rules("mode.debug", "mode.release")

add_defines("WINDOWS")
add_defines("MSVC")
add_defines("DEBUG")
add_defines("DEBUG_LOG")

set_warnings("less")
--set_languages("c98")

-- add target
target("mdkernel")

    -- set kind
    set_kind("binary")

	
    -- add .h files
    add_includedirs("../../source/platform/")
    add_includedirs("../../source/base/")
    add_includedirs("../../source/utility/")
	add_includedirs("../../source/datastruct/")
	add_includedirs("../../source/event/")
    add_includedirs("../../source/network/")
    add_includedirs("../../source/tcpnetwork/")
    add_includedirs("../../source/udpnetwork/")
	add_includedirs("../../source/multinetwork/")
	add_includedirs("../../source/sslnetwork/")
	add_includedirs("../../source/openssl/")
	add_includedirs("../../source/protocol/")
    add_includedirs("../../source/channelprotocol/")
    add_includedirs("../../source/scpprotocol/")
    add_includedirs("../../source/xmpprotocol/")
    add_includedirs("../../source/xtpprotocol/")
	add_includedirs("../../source/compressprotocol/")
	add_includedirs("../../source/ftdprotocol/")
	add_includedirs("../../source/multiprotocol/")
    add_includedirs("../../source/fib/")
	add_includedirs("../../source/xtpfield/")
	add_includedirs("../../source/ftdfield/")
	add_includedirs("../../source/error/")
	add_includedirs("../../source/baseengine/")
	add_includedirs("../../source/engine/")
	add_includedirs("../../source/engine/md/")
	add_includedirs("../../source/memorydatabase/")
	add_includedirs("../../source/tradingtools/")
    add_includedirs("../../source/UFCopy/")
	add_includedirs("../../source/xml/")
	add_includedirs("../../source/deployconfig/")
	add_includedirs("../../source/probelogger/")
	add_includedirs("../../source/version/")
	add_includedirs("../../source/crypt/")
	add_includedirs("../../source/precheck/")
	add_includedirs("../../source/customDataType/")
	add_includedirs("../../source/serviceInterface/")
	add_includedirs("../../source/serviceInterface/init/")
	add_includedirs("../../source/serviceInterface/dbmt/")
	add_includedirs("../../source/serviceInterface/trade/")
	add_includedirs("../../source/serviceInterface/login/")
	add_includedirs("../../source/serviceInterface/MD/")
	add_includedirs("../../source/serviceInterface/bulletin/")
	add_includedirs("../../source/serviceXTPLink/")
	add_includedirs("../../source/serviceXTPLink/init/")
	add_includedirs("../../source/serviceXTPLink/trade/")
	add_includedirs("../../source/serviceXTPLink/login/")
	add_includedirs("../../source/serviceXTPLink/dbmt/")
	add_includedirs("../../source/serviceXTPLink/bulletin/")
	add_includedirs("../../source/serviceImpl/init/")
	add_includedirs("../../source/serviceImpl/dbmt/")
	add_includedirs("../../source/serviceImpl/login/")
	add_includedirs("../../source/serviceImpl/MD/")
	add_includedirs("../../source/serviceImpl/trade/")
	add_includedirs("../../source/serviceImpl/trade/ruleConfig/")
	add_includedirs("../../source/serviceImpl/trade/ruleRepository/")
	add_includedirs("../../source/serviceImpl/bulletin/")
	add_includedirs("../../source/mdkernel/")

	-- add .h files
		add_headerfiles("../../source/platform/*.h")
    add_headerfiles("../../source/base/*.h")
    add_headerfiles("../../source/utility/*.h")
	add_headerfiles("../../source/datastruct/*.h")
	add_headerfiles("../../source/event/*.h")
    add_headerfiles("../../source/network/*.h")
    add_headerfiles("../../source/tcpnetwork/*.h")
    add_headerfiles("../../source/udpnetwork/*.h")
	add_headerfiles("../../source/multinetwork/*.h")
	add_headerfiles("../../source/sslnetwork/*.h")
	add_headerfiles("../../source/protocol/*.h")
    add_headerfiles("../../source/channelprotocol/*.h")
    add_headerfiles("../../source/scpprotocol/*.h")
    add_headerfiles("../../source/xmpprotocol/*.h")
    add_headerfiles("../../source/xtpprotocol/*.h")
	add_headerfiles("../../source/compressprotocol/*.h")
	add_headerfiles("../../source/ftdprotocol/*.h")
	add_headerfiles("../../source/multiprotocol/*.h")
    add_headerfiles("../../source/fib/*.h")
	add_headerfiles("../../source/xtpfield/*.h")
	add_headerfiles("../../source/ftdfield/*.h")
	add_headerfiles("../../source/error/*.h")
	add_headerfiles("../../source/baseengine/*.h")
	add_headerfiles("../../source/engine/*.h")
	add_headerfiles("../../source/engine/md/*.h")
	add_headerfiles("../../source/memorydatabase/*.h")
	add_headerfiles("../../source/tradingtools/*.h")
    add_headerfiles("../../source/UFCopy/*.h")
	add_headerfiles("../../source/xml/*.h")
	add_headerfiles("../../source/deployconfig/*.h")
	add_headerfiles("../../source/probelogger/*.h")
	add_headerfiles("../../source/version/*.h")
	add_headerfiles("../../source/crypt/*.h")
	add_headerfiles("../../source/precheck/*.h")
	add_headerfiles("../../source/customDataType/*.h")
	add_headerfiles("../../source/serviceInterface/*.h")
	add_headerfiles("../../source/serviceInterface/init/*.h")
	add_headerfiles("../../source/serviceInterface/dbmt/*.h")
	add_headerfiles("../../source/serviceInterface/trade/*.h")
	add_headerfiles("../../source/serviceInterface/login/*.h")
	add_headerfiles("../../source/serviceInterface/MD/*.h")
	add_headerfiles("../../source/serviceInterface/bulletin/*.h")
	add_headerfiles("../../source/serviceXTPLink/*.h")
	add_headerfiles("../../source/serviceXTPLink/init/*.h")
	add_headerfiles("../../source/serviceXTPLink/trade/*.h")
	add_headerfiles("../../source/serviceXTPLink/login/*.h")
	add_headerfiles("../../source/serviceXTPLink/dbmt/*.h")
	add_headerfiles("../../source/serviceXTPLink/bulletin/*.h")
	add_headerfiles("../../source/serviceImpl/init/*.h")
	add_headerfiles("../../source/serviceImpl/dbmt/*.h")
	add_headerfiles("../../source/serviceImpl/login/*.h")
	add_headerfiles("../../source/serviceImpl/MD/*.h")
	add_headerfiles("../../source/serviceImpl/trade/*.h")
	add_headerfiles("../../source/serviceImpl/trade/ruleConfig/*.h")
	add_headerfiles("../../source/serviceImpl/trade/ruleRepository/*.h")
	add_headerfiles("../../source/serviceImpl/bulletin/*.h")
	add_headerfiles("../../source/mdkernel/*.h")



    -- add .cpp files
	add_files("../../source/platform/*.cpp")
    add_files("../../source/base/*.cpp")
    add_files("../../source/utility/*.cpp")
	add_files("../../source/datastruct/*.cpp")
	add_files("../../source/event/*.cpp")
    add_files("../../source/network/*.cpp")
    add_files("../../source/tcpnetwork/*.cpp")
    add_files("../../source/udpnetwork/*.cpp")
	add_files("../../source/multinetwork/*.cpp")
	add_files("../../source/sslnetwork/*.cpp")
	add_files("../../source/protocol/*.cpp")
    add_files("../../source/channelprotocol/*.cpp")
    add_files("../../source/scpprotocol/*.cpp")
    add_files("../../source/xmpprotocol/*.cpp")
    add_files("../../source/xtpprotocol/*.cpp")
	add_files("../../source/compressprotocol/*.cpp")
	add_files("../../source/ftdprotocol/*.cpp")
	add_files("../../source/multiprotocol/*.cpp")
    add_files("../../source/fib/*.cpp")
	add_files("../../source/xtpfield/*.cpp")
	add_files("../../source/ftdfield/*.cpp")
	add_files("../../source/error/*.cpp")
	add_files("../../source/baseengine/*.cpp")
	add_files("../../source/engine/*.cpp")
	add_files("../../source/engine/md/*.cpp")
	add_files("../../source/memorydatabase/*.cpp")
	add_files("../../source/tradingtools/*.cpp")
	add_files("../../source/xml/*.cpp")
	add_files("../../source/deployconfig/*.cpp")
	add_files("../../source/probelogger/*.cpp")
	add_files("../../source/version/*.cpp")
	add_files("../../source/crypt/*.cpp")
	add_files("../../source/precheck/*.cpp")
	add_files("../../source/serviceXTPLink/*.cpp")
	add_files("../../source/serviceXTPLink/init/*.cpp")
	add_files("../../source/serviceXTPLink/trade/*.cpp")
	add_files("../../source/serviceXTPLink/login/*.cpp")
	add_files("../../source/serviceXTPLink/dbmt/*.cpp")
	add_files("../../source/serviceXTPLink/bulletin/*.cpp")
	add_files("../../source/serviceImpl/init/*.cpp")
	add_files("../../source/serviceImpl/dbmt/*.cpp")
	add_files("../../source/serviceImpl/login/*.cpp")
	add_files("../../source/serviceImpl/MD/*.cpp")
	add_files("../../source/serviceImpl/trade/*.cpp")
	add_files("../../source/serviceImpl/trade/ruleConfig/*.cpp")
	add_files("../../source/serviceImpl/trade/ruleRepository/*.cpp")
	add_files("../../source/serviceImpl/bulletin/*.cpp")
	add_files("../../source/mdkernel/*.cpp")
	
	add_linkdirs("../../source/openssl/")
	add_links("wsock32")
	--openssl依赖的lib
	add_links("gdi32")
	add_links("libeay32")
	add_links("libssleay32")
	
1.如果使用xmake f -m debug -x 86 ,然后xmake build ，可以编译正常
2.如果使用xmake project -k vs2019 -m debug -a x86 生成vs工程，然后在编译就会出错
  错误信息：
1>LINK : warning LNK4098: 默认库“LIBCMT”与其他库的使用冲突；请使用 /NODEFAULTLIB:library
1>libeay32.lib(v3_conf.obj) : error LNK2019: 无法解析的外部符号 __pctype，该符号在函数 _v3_generic_extension 中被引用
1>libeay32.lib(bn_print.obj) : error LNK2001: 无法解析的外部符号 __pctype
1>libeay32.lib(x509_cmp.obj) : error LNK2001: 无法解析的外部符号 __pctype
1>libeay32.lib(obj_dat.obj) : error LNK2001: 无法解析的外部符号 __pctype
1>libeay32.lib(b_print.obj) : error LNK2001: 无法解析的外部符号 __pctype
1>libeay32.lib(v3_utl.obj) : error LNK2001: 无法解析的外部符号 __pctype
1>libeay32.lib(v3_conf.obj) : error LNK2019: 无法解析的外部符号 ___mb_cur_max，该符号在函数 _v3_generic_extension 中被引用
1>libeay32.lib(bn_print.obj) : error LNK2001: 无法解析的外部符号 ___mb_cur_max
1>libeay32.lib(x509_cmp.obj) : error LNK2001: 无法解析的外部符号 ___mb_cur_max
1>libeay32.lib(obj_dat.obj) : error LNK2001: 无法解析的外部符号 ___mb_cur_max
1>libeay32.lib(b_print.obj) : error LNK2001: 无法解析的外部符号 ___mb_cur_max
1>libeay32.lib(v3_utl.obj) : error LNK2001: 无法解析的外部符号 ___mb_cur_max
1>libeay32.lib(cryptlib.obj) : error LNK2019: 无法解析的外部符号 __iob，该符号在函数 _CRYPTO_lock 中被引用
1>libeay32.lib(rsa_sign.obj) : error LNK2001: 无法解析的外部符号 __iob
1>libeay32.lib(pem_lib.obj) : error LNK2001: 无法解析的外部符号 __iob
1>libeay32.lib(ui_openssl.obj) : error LNK2001: 无法解析的外部符号 __iob

**Comment by OpportunityLiu** [comment]
2.2.8以后建议用 `xmake project -k vsxmake`

**Comment by Ultraman95** [comment]
使用xmake project -k vsxmake 果然不一样啊，现在用Vs2019编译贼快，你是不是给vs2019加了一个自定义的编译属性啊？

**Comment by waruqi** [comment]
libeay32.lib编译 和当前target编译，用的vs runtime设置不同导致，请先确保一致。

估计libeay32.lib里面默认用了 MSVCRT （-MD）编译。。

你xmake.lua里面没有显式设置，所以命令行编译默认也是用的 MSVCRT，所以link没问题

而生成的vs工程，由于xmake.lua里面没设置，所以使用了vs工程里面的设置-MT，导致冲突了。。

一种方式，就是采用 `xmake project -k vsxmake`来生成vs工程，两端参数设置都是完全同步的。。

一种就是在你的xmake.lua显式设置`-MD` flags。。

```lua
if is_plat("windows") then 
    if is_mode("release") then
        add_cxflags("-MD") 
    elseif is_mode("debug") then
        add_cxflags("-MDd") 
    end
end
```

**Comment by waruqi** [comment]
> 使用xmake project -k vsxmake 果然不一样啊，现在用Vs2019编译贼快，你是不是给vs2019加了一个自定义的编译属性啊？

vsxmake是直接wrap调用xmake命令来编译，编译速度应该跟xmake命令行编译是差不多的。。默认都是开启多任务编译。。

**Comment by waruqi** [comment]
@Ultraman95 可以了么？
