### ISSUE TITLE
无法指定libc++的target

### ISSUE THREAD

**Issue by not3** [xmake-io/xmake#5556]
### Xmake 版本

2.9.4

### 操作系统版本和架构

Windows 11

### 描述问题

已将 D:\Home\Coding\msys64\ucrt64\bin; 加入到Path中。

> xmake
> [ 50%]: cache compiling.release src\main.cpp
> error: src\main.cpp:1:10: fatal error: 'iostream' file not found
>     1 | #include <iostream>
>     |          ^~~~~~~~~~
> 1 error generated.

使用llvm自带的，可以编译。
> clang++ -target x86_64-pc-windows-gnu .\main.cpp -o main.exe

### 期待的结果

怎么配置编译target为x86_64-pc-windows-gnu

### 工程配置

> add_rules("mode.debug", "mode.release")
> 
> target("hello")
>     set_kind("binary")
>     add_files("src/*.cpp")

### 附加信息和错误日志

```error: src\main.cpp:1:10: fatal error: 'iostream' file not found
    1 | #include <iostream>
      |          ^~~~~~~~~~
1 error generated.
  > in src\main.cpp```

**Comment by not3** [comment]
>  xmake f -p mingw --mingw=D:\Home\Coding\msys64 --toolchain=llvm --toolchain=llvm --sdk=D:\Home\Coding\LLVM

然后执行xmake

还是报同样的错。

用的LLVM版本是https://github.com/llvm/llvm-project/releases/tag/llvmorg-19.1.0-rc2页面的， LLVM-19.1.0-rc2-Windows-X64.tar.xz

**Comment by not3** [comment]
生成的xmake.conf文件
```
{
    __toolchains_mingw_x86_64 = {
        "llvm"
    },
    arch = "x86_64",
    buildir = "build",
    ccache = true,
    host = "windows",
    kind = "static",
    mingw = [[D:\Home\Coding\msys64]],
    mode = "release",
    ndk_stdcxx = true,
    network = "public",
    plat = "mingw",
    sdk = [[D:\Home\Coding\LLVM]],
    theme = "default",
    toolchain = "llvm"
}
```

若把main.cpp中的代码改为
```
int main(int argc, char** argv) {
    return 0;
}
```
则报错为

> [ 50%]: cache compiling.release src\main.cpp
> [ 75%]: linking.release hello.exe
> error: clang++: warning: unable to find a Visual Studio installation; try running Clang from a developer command prompt [-Wmsvc-not-found]
> clang++: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
> clang++: error: unable to execute command: program not executable
> clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by not3** [comment]
./msys2_shell.cmd -defterm -here -no-start
进入msys环境后，也报错

> not3@PC UCRT64 /e/Workspace/c++/hello
> $ /d/Home/Coding/xmake/xmake.exe  f -p mingw --toolchain=llvm --toolchain=llvm --sdk=/d/Home/Coding/LLVM
> checking for architecture ... x86_64
> 
> not3@PC UCRT64 /e/Workspace/c++/hello
> $ /d/Home/Coding/xmake/xmake.exe
> [ 75%]: linking.release hello.exe
> error: clang++: warning: unable to find a Visual Studio installation; try running Clang from a developer command prompt [-Wmsvc-not-found]
> clang++: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
> clang++: error: unable to execute command: program not executable
> clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by star-hengxing** [comment]
> 用的LLVM版本是[https://github.com/llvm/llvm-project/releases/tag/llvmorg-19.1.0-rc2页面的，](https://github.com/llvm/llvm-project/releases/tag/llvmorg-19.1.0-rc2%E9%A1%B5%E9%9D%A2%E7%9A%84%EF%BC%8C) LLVM-19.1.0-rc2-Windows-X64.tar.xz

其实你可以用 `clang -v` 看看官方 release，target 是 msvc 的。所以你需要用 pacman 单独装一个或者自己编译

**Comment by waruqi** [comment]
`-p mingw` 主要绑定针对 mingw-w64 和 llvm-mingw 这两工具链的支持，并不是随意给个 clang 都支持适配的。。你这两都不用，就不要切 mingw 平台。

自己 `xmake f --toolchain=llvm --sdk=/xxx` 直接指定 llvm 工具链，然后自己通过 `add_cxflags`, `add_ldflags` 设置上 `-target x86_64-pc-windows-gnu` 就行了。。

或者你自定义个 toolchain ，配置上这个 target。

**Comment by not3** [comment]
xmake.lua
```
add_rules("mode.debug", "mode.release")
add_cxxflags ("-target x86_64-pc-windows-gnu", {force = true})
add_ldflags ("-target x86_64-pc-windows-gnu", {force = true})

target("hello")
    set_kind("binary")
    add_files("src/*.cpp")
```
若main.cpp中有iostream
```
#include <iostream>

int main(int argc, char** argv) {
    std::cout << "hello world!" << std::endl;
    return 0;
}
```
执行xmake -v，则报错
> checking for clang ... D:\Home\Coding\LLVM\bin\clang
> checking for the c++ compiler (cxx) ... clang
> checking for D:\Home\Coding\LLVM\bin\clang ... ok
> checking for flags (-fPIC) ... no
> checking for flags (-fvisibility-inlines-hidden) ... ok
> checking for flags (-O3) ... ok
> checking for flags (-DNDEBUG) ... ok
> [ 50%]: cache compiling.release src\main.cpp
> D:\Home\Coding\LLVM\bin\clang -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -target x86_64-pc-windows-gnu -DNDEBUG -o build\.objs\hello\msys\x64\release\src\main.cpp.o src\main.cpp
> checking for flags (-MMD -MF) ... ok
> checking for flags (-fdiagnostics-color=always) ... ok
> checking for flags (-fansi-escape-codes) ... ok
> error: src\main.cpp:1:10: fatal error: 'iostream' file not found
>     1 | #include <iostream>
>       |          ^~~~~~~~~~
> 1 error generated.

若独立执行
> D:\Home\Coding\LLVM\bin\clang -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -target x86_64-pc-windows-gnu -DNDEBUG -o build\.objs\hello\msys\x64\release\src\main.cpp.o src\main.cpp

不报错

若main.cpp无iostream
```
int main(int argc, char** argv) {
    return 0;
}
```
执行xmake -v，则报错
```
checking for clang ... D:\Home\Coding\LLVM\bin\clang
checking for the c++ compiler (cxx) ... clang
checking for D:\Home\Coding\LLVM\bin\clang ... ok
checking for flags (-fPIC) ... no
checking for flags (-fvisibility-inlines-hidden) ... ok
checking for flags (-O3) ... ok
checking for flags (-DNDEBUG) ... ok
checking for clang++ ... D:\Home\Coding\LLVM\bin\clang++
checking for the linker (ld) ... clang++
checking for D:\Home\Coding\LLVM\bin\clang++ ... ok
checking for flags (-fPIC) ... no
[ 75%]: linking.release hello.exe
D:\Home\Coding\LLVM\bin\clang++ -o build\msys\x64\release\hello.exe build\.objs\hello\msys\x64\release\src\main.cpp.o -m64 -s -target x86_64-pc-windows-gnu
clang++: error: unable to execute command: program not executable
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
error: execv(D:\Home\Coding\LLVM\bin\clang++ -o build\msys\x64\release\hello.exe build\.objs\hello\msys\x64\release\src\main.cpp.o -m64 -s -target x86_64-pc-windows-gnu) failed(1)
```
若依次执行

> D:\Home\Coding\LLVM\bin\clang -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -target x86_64-pc-windows-gnu -DNDEBUG -o build.objs\hello\msys\x64\release\src\main.cpp.o src\main.cpp
> D:\Home\Coding\LLVM\bin\clang++ -o build\msys\x64\release\hello.exe build.objs\hello\msys\x64\release\src\main.cpp.o -m64 -s -target x86_64-pc-windows-gnu

不报错

若main.cpp中有iostream
```
#include <iostream>

int main(int argc, char** argv) {
    std::cout << "hello world!" << std::endl;
    return 0;
}
```
依次执行
> D:\Home\Coding\LLVM\bin\clang -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -target x86_64-pc-windows-gnu -DNDEBUG -o build\.objs\hello\msys\x64\release\src\main.cpp.o src\main.cpp
> D:\Home\Coding\LLVM\bin\clang++ -o build\msys\x64\release\hello.exe build\.objs\hello\msys\x64\release\src\main.cpp.o -m64 -s -target x86_64-pc-windows-gnu
> xmake run

控制台会正确打印
> hello world!

**Comment by 24bit-xjkp** [comment]
这不是xmake的问题，使用clang请自行准备一个sysroot。事实上clang会尝试探测系统中已经存在的gcc并使用libstdc++、libgcc和ld，如果环境变量中找不到可执行的gcc或者要使用libc++就必须要指定一个sysroot。关于如何准备sysroot请参考[构建llvm工具链](https://github.com/24bit-xjkp/toolchains/blob/main/build_llvm.md)。如果不希望准备sysroot，就让clang可以通过PATH找到gcc，这样会自动用gcc的库和工具。

**Comment by waruqi** [comment]
`add_cxxflags ("-target x86_64-pc-windows-gnu", {force = true})` 不要加空格，拆成两个 flags。。

```lua
add_cxxflags ("-target", "x86_64-pc-windows-gnu", {force = true})
```

**Comment by not3** [comment]
用了llvm-mingw工具链搞定了。

> xmake f --toolchain=llvm --sdk=D:\Home\Coding\llvm-mingw

并要将D:\Home\Coding\llvm-mingw\bin，加入path中，才能xmake run正常执行编译好的程序。

官方的llvm，还是配合msvc，才行。

**Comment by rc-power** [comment]
补充一下，set_runtimes("c++_static")，不然还是会找不到头文件
-------------------------------------------------------------------------
如果使用官方的LLVM没法调试，不论codelldb还是msvc。
