### ISSUE TITLE
on_load 脚本域在构建的时候又执行了一遍

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#5564]
### Xmake 版本

v2.9.4+dev.0d2bd1503

### 操作系统版本和架构

windows 11

### 描述问题

如下的脚本
```
add_rules("mode.debug", "mode.release")
set_languages("c99", "c++17")


option("hello")
    set_default("111")

target("testcpp")
    set_kind("binary")
    add_files("src/*.cpp")
    add_options("hello")


    on_load(function(target)
        import("core.base.option")
        aa = option.get("hello")
        if aa == "aa" then
            print("aa")
        elseif aa == "bb" then
            print("bb")
        else
            print("other")
        end
    end)
        

```
执行如下的命令，可以看到，配置的时候执行了一遍，获取到了命令行传入的hello=aa
但是构建的时候又执行了一遍，关键是这一遍还没获取到hello的值
```
PS C:\Users\Administrator\temp\testcpp> xmake f --hello=aa
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.41.34120
aa
PS C:\Users\Administrator\temp\testcpp> xmake
other
[100%]: build ok, spent 0.156s
PS C:\Users\Administrator\temp\testcpp>
```

### 期待的结果

1 on_load应该只在配置的时候执行一遍
2 即便执行多次（比如构建的时候默认配置一遍），但是应该每一次配置都能获取到命令行传入的数据

### 工程配置

已提供

### 附加信息和错误日志

已提供

**Comment by waruqi** [comment]
1. 正常，on_load 只要 target 被加载就会被调用， 你 config 和  build 分两次执行，独立进程，target 需要重新加载到内存，每次加载都会执行 on_load 

很正常，如果你直接执行 xmake 编译，首次自动配置，也只会 load 一次。是你没理解对。

2. 你还是没理解对，option.get 的作用仅用于获取 当前命令的参数选项，不是 `xmake f ` 的配置参数

你执行 `xmake build --xxx --yy` 命令，就是获取 build 的参数，你执行 `xmake run --xxx` 运行命令，就是获取 run 的参数，跟配置没有半毛钱关系，只不过是你执行 `xmake config --xxx` 正好获取了 config 的参数而已，当然不会有缓存。

要获取配置。直接用 `get_config`, `has_config`, `is_config` 接口，或者 `core.project.config` 模块，文档有说明

**Comment by heheda123123** [comment]
ok，问题解决了，不过这还是回归到上次在roadmap3里面提到的问题。
文档确实存在很大的问题。

我的需求很简单，就是想根据命令行传入的参数进行判断，加宏定义。
这个需求我先自己翻了文档（没有挨个看api），我看下来唯一和我需求相关的就是option（不是我一个人这么误解，群里很多热心回复我的群友也都是提到这个），文档里option的描述示例就是和我的需求一样，定义了option，再加到target里面，就可以命令行传入了。结果我照着option里面的说明写了也解决不了问题。里面也没说这里定义的是和命令相关。

另外照你前面说的，option是获取命令的参数，但是我给target加了option之后，`xmake b --hello=a`一样提示不存在`error: Invalid option: --hello=aa`

最后你提到的get_config这几个api，首先从名字来看，是肯定看不出来可以从命令行传入？
我又搜了下，和其他文档也没有任何关联，这谁能找到呢？除非挨个去看api。
我在群里问了，有不少热心群友回复，只有starheng是提到了has_config。去搜了这个地方才看到有从命令行传入参数的示例。

之前也多次提过文档的事情，但是大佬都回复是没时间。但我是觉得文档对于目前的xmake是比其他新功能，bug都要重要的东西。

**Comment by waruqi** [comment]
> ok，问题解决了，不过这还是回归到上次在roadmap3里面提到的问题。 文档确实存在很大的问题。
> 
> 我的需求很简单，就是想根据命令行传入的参数进行判断，加宏定义。 这个需求我先自己翻了文档（没有挨个看api），我看下来唯一和我需求相关的就是option（不是我一个人这么误解，群里很多热心回复我的群友也都是提到这个），文档里option的描述示例就是和我的需求一样，定义了option，再加到target里面，就可以命令行传入了。结果我照着option里面的说明写了也解决不了问题。里面也没说这里定义的是和命令相关。
> 
> 另外照你前面说的，option是获取命令的参数，但是我给target加了option之后，`xmake b --hello=a`一样提示不存在`error: Invalid option: --hello=aa`
> 
> 最后你提到的get_config这几个api，首先从名字来看，是肯定看不出来可以从命令行传入？ 我又搜了下，和其他文档也没有任何关联，这谁能找到呢？除非挨个去看api。 我在群里问了，有不少热心群友回复，只有starheng是提到了has_config。去搜了这个地方才看到有从命令行传入参数的示例。
> 
> 之前也多次提过文档的事情，但是大佬都回复是没时间。但我是觉得文档对于目前的xmake是比其他新功能，bug都要重要的东西。

但我还是没时间，我现在都没搞新特性，光处理 issues 都搞不过来，哪来时间搞文档。

每天一堆新 issues，这边很多 issue 都要花一两周甚至个把月才能解决，白天还得工作。如果觉得文档不行，完全可以提 pr 过来一起完善，都是开源的。

而且这几个接口文档都有。https://xmake.io/#/manual/global_interfaces?id=get-the-configuration-value

如果觉得搜索不给力，那是 docsify 的问题，这边也没办法。

新文档框架也搭了，https://docs.xmake.io/en-us/index.html 单靠我一个人也搞不动，之前推了半天，也没一个人帮忙迁移文档过去，一边嫌弃文档不给力，但是帮忙迁移下么，却没一个人搭理。

**Comment by heheda123123** [comment]
> > ok，问题解决了，不过这还是回归到上次在roadmap3里面提到的问题。 文档确实存在很大的问题。
> > 我的需求很简单，就是想根据命令行传入的参数进行判断，加宏定义。 这个需求我先自己翻了文档（没有挨个看api），我看下来唯一和我需求相关的就是option（不是我一个人这么误解，群里很多热心回复我的群友也都是提到这个），文档里option的描述示例就是和我的需求一样，定义了option，再加到target里面，就可以命令行传入了。结果我照着option里面的说明写了也解决不了问题。里面也没说这里定义的是和命令相关。
> > 另外照你前面说的，option是获取命令的参数，但是我给target加了option之后，`xmake b --hello=a`一样提示不存在`error: Invalid option: --hello=aa`
> > 最后你提到的get_config这几个api，首先从名字来看，是肯定看不出来可以从命令行传入？ 我又搜了下，和其他文档也没有任何关联，这谁能找到呢？除非挨个去看api。 我在群里问了，有不少热心群友回复，只有starheng是提到了has_config。去搜了这个地方才看到有从命令行传入参数的示例。
> > 之前也多次提过文档的事情，但是大佬都回复是没时间。但我是觉得文档对于目前的xmake是比其他新功能，bug都要重要的东西。
> 
> 但我还是没时间，我现在都没搞新特性，光处理 issues 都搞不过来，哪来时间搞文档。
> 
> 每天一堆新 issues，这边很多 issue 都要花一两周甚至个把月才能解决，白天还得工作。如果觉得文档不行，完全可以提 pr 过来一起完善，都是开源的。
> 
> 而且这几个接口文档都有。https://xmake.io/#/manual/global_interfaces?id=get-the-configuration-value
> 
> 如果觉得搜索不给力，那是 docsify 的问题，这边也没办法。
> 
> 新文档框架也搭了，https://docs.xmake.io/en-us/index.html 单靠我一个人也搞不动，之前推了半天，也没一个人帮忙迁移文档过去，一边嫌弃文档不给力，但是帮忙迁移下么，却没一个人搭理。

我觉得不能简单的搞文档迁移，迁移要怎么迁呢，一条一条解释api用法吗？就算这样迁移过去还是存在上面提到的问题，当一个人不知道这个api用法的时候他是很难找到这个api的。
更好的还是starheng的那种教程，包括你之前写的很多文章。我觉得官方可以在征求作者意见之后对这些文章做整合。这个我也可以帮忙弄。
另外说到没人帮忙的事情，不是大家都不参与（作为对比，xmake-repo一直有人pr）。很大程度上是别人自己都对这些api不熟悉，我自己都不擅长咋来做这个事情呢

**Comment by waruqi** [comment]
> 我觉得不能简单的搞文档迁移，迁移要怎么迁呢，一条一条解释api用法吗？就算这样迁移过去还是存在上面提到的问题，当一个人不知道这个api用法的时候他是很难找到这个api的。

迁移只是第一步，先已有内容全部迁移过去，切到新框架，不然我同时维护两个文档框架，不是更没时间。。

迁移过去后，然后新文档框架，还要改进搜索，文档组织等，很多的事情呢。。现在新文档没人 care，还有哪来的积极性去改进搜索，连之前贡献这个框架的老外，最近都不搞了。

当然，如果你提 pr 直接能改进掉现有 docsify 这个文档的搜索，让它变得好用，那也可以，就继续一直使用现有框架。

> 另外说到没人帮忙的事情，不是大家都不参与（作为对比，xmake-repo一直有人pr）。很大程度上是别人自己都对这些api不熟悉，我自己都不擅长咋来做这个事情呢

不熟悉，提 issues 趟完坑后 不就知道怎么用了么，然后顺带补上自己已经熟悉的部分。。就跟你现在知道了 还有 get_config 可以用，那就可以把自己对 get_config 的使用经验和理解去完善补全文档。。每个用户要是都这么弄，还愁文档不完善么。
