### ISSUE TITLE
Fix cmake find_package on wasm

### ISSUE THREAD

**Issue by star-hengxing** [xmake-io/xmake#5577]
### Xmake Version

dev

### Operating System Version and Architecture

Windows

### Describe Bug

https://github.com/xmake-io/xmake-repo/actions/runs/10735615401/job/29773289808

### Expected Behavior

Use `CMAKE_FIND_ROOT_PATH` pass package deps installdir.
ref: https://github.com/emscripten-core/emscripten/issues/13310

### Project Configuration

N/A

### Additional Information and Error Logs

N/A

**Comment by waruqi** [comment]
应该传什么值呢？跟

https://github.com/xmake-io/xmake/blob/79e282463c92e3ecd9229a647d8072eb3b5fdc05/xmake/modules/package/tools/cmake.lua#L659-L663

一样配置在 tools.cmake ？还是特定包作为参数外面设置？

**Comment by star-hengxing** [comment]
试了一下，命令行 `-DCMAKE_FIND_ROOT_PATH=xxx` 和环境变量都行

```lua
    local envs = {}
    local installdir = {}
    for _, dep in ipairs(package:librarydeps({private = true})) do
        if not dep:is_system() then
            table.insert(installdir, dep:installdir())
        end
    end
    envs.CMAKE_FIND_ROOT_PATH      = path.joinenv(installdir)
    _get_configs_for_generic(package, configs, opt)
    _insert_configs_from_envs(configs, envs, opt)
```

**Comment by star-hengxing** [comment]
emscripten cmake 脚本设置了这些，xmake 应该不用管

```cmake
# To find programs to execute during CMake run time with find_program(), e.g.
# 'git' or so, we allow looking into system paths.
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# Since Emscripten is a cross-compiler, we should never look at the
# system-provided directories like /usr/include and so on. Therefore only
# CMAKE_FIND_ROOT_PATH should be used as a find directory. See
# http://www.cmake.org/cmake/help/v3.0/variable/CMAKE_FIND_ROOT_PATH_MODE_INCLUDE.html
if (NOT CMAKE_FIND_ROOT_PATH_MODE_LIBRARY)
  set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
endif()
if (NOT CMAKE_FIND_ROOT_PATH_MODE_INCLUDE)
  set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
endif()
if (NOT CMAKE_FIND_ROOT_PATH_MODE_PACKAGE)
  set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
endif()
```

**Comment by star-hengxing** [comment]
linux wasm ci https://github.com/xmake-io/xmake-repo/pull/4692 还有点问题，还需要再分析一下。
目前 Windows 本地测试这些包都没问题。

**Comment by xq114** [comment]
CMAKE_FIND_ROOT_PATH是用来对交叉工具链指定类似/usr这样含大量包的目录的，而且我记得把这个目录当系统目录会有额外影响，建议慎用；既然xmake中把依赖已经处理好了，直接设置 CMAKE_FIND_ROOT_PATH_MODE_PACKAGE 为BOTH更好，https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_ROOT_PATH_MODE_PACKAGE.html 这样原来的CMAKE_PREFIX_PATH Package_DIR 都能继续生效，优先找的都是xmake设置的依赖

**Comment by waruqi** [comment]
那就搞成跟 mingw/android/cross 一样的配置试试么。。

https://github.com/xmake-io/xmake/blob/9e70298e25cde32fdde0cae65f4977a096eabfa7/xmake/modules/package/tools/cmake.lua#L504-L509

**Comment by star-hengxing** [comment]
> 那就搞成跟 mingw/android/cross 一样的配置试试么。。
> 
> https://github.com/xmake-io/xmake/blob/9e70298e25cde32fdde0cae65f4977a096eabfa7/xmake/modules/package/tools/cmake.lua#L504-L509

```lua
local envs = {}
-- https://github.com/emscripten-core/emscripten/issues/13310
envs.CMAKE_FIND_ROOT_PATH_MODE_PACKAGE = "BOTH"
envs.CMAKE_FIND_ROOT_PATH_MODE_LIBRARY = "BOTH"
envs.CMAKE_FIND_ROOT_PATH_MODE_INCLUDE = "BOTH"
envs.CMAKE_FIND_ROOT_PATH_MODE_PROGRAM = "NEVER"
_get_configs_for_generic(package, configs, opt)
_insert_configs_from_envs(configs, envs, opt)
```

在 windows 本地试了一下没问题，可以改一下看看 linux ci 那边效果如何

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/pull/5598

**Comment by star-hengxing** [comment]
> #5598

本地 ubuntu 用 `reflect-cpp` 测试没问题
