### ISSUE TITLE
在新的目录使用xmake报错

### ISSUE THREAD

**Issue by hkunbin** [xmake-io/xmake#558]
xmake在之前的目录是可以正常用的，现在想在另外一个目录使用，报下面的错误，请问怎么支持多个不同的项目目录

error: /home/kirito/.local/share/xmake/core/base/os.lua:705: open /home/kirito/root_home/document/svn/ZhuHai/svn_root/Trunks/BLELock/ARM/BLELock_source_easy/source/.xmake/cache/history failed!
stack traceback:
	[C]: in function 'error'
	/home/kirito/.local/share/xmake/core/base/os.lua:705: in function 'raise'
	/home/kirito/.local/share/xmake/core/project/cache.lua:128: in function 'flush'
	/home/kirito/.local/share/xmake/core/project/history.lua:87: in function 'save'
	/home/kirito/.local/share/xmake/core/main.lua:234: in function </home/kirito/.local/share/xmake/core/main.lua:176>

**Comment by waruqi** [comment]
xmake是支持 多项目的，你是不是之前切到过root用户去编译BLELock_source_easy？导致这个项目的某些cache文件是在root下生成的。。。你现在又切到kirito用户去执行xmake，所以open file之前root下生成的cache文件  没权限失败了。。

你尝试先手动 清掉  `BLELock_source_easy/source/.xmake`后再执行下试试。。另外建议以后 尽量不要在root下执行xmake，这不安全，毕竟xmake会去运行各种lua脚本，如果在xmake.lua里面用户写了一些自定义的lua脚本去清理文件，比如调用了os.rm等，如果没清理路径写对，root下就很容易误删重要文件。

**Comment by hkunbin** [comment]
可以了，不要用root和其他用户来回切换使用就行了。谢谢！
