### ISSUE TITLE
Simplifying adding runenvs in virtual environment

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#5580]
### Is your feature request related to a problem? Please describe.

目前在虚拟环境中加环境变量是比较麻烦的：必须先定义一个package，再在on_load里加环境变量，还要加上on_fetch让xmake不报错：
```lua
package("__phony")
on_load(function (package)
    package:addenv("PYTHONPATH", path.join(os.scriptdir(), "bin"))
end)
on_fetch(function (package, opt) return {} end)
package_end()
add_requires("__phony")
```
这种写法繁琐、非常容易出错。然而加环境变量的需求在多语言项目中普遍存在，例如C++/Python混合项目里，编译出的.pyd要在python里测试，就要把python module加入环境变量PYTHONPATH才行

### Describe the solution you'd like

目前定义一个`add_runenvs()`函数就行：
```lua
function add_runenvs(envs)
package("__phony")
on_load(function (package)
    package:addenv("TESTFILE", io.readfile("testfile"))
    for name, value in pairs(envs) do
        package:addenv(name, value)
    end
end)
on_fetch(function (package, opt) return {} end)
package_end()
add_requires("__phony")
end
```
测试：
```lua
add_runenvs({TESTENV = path.join(os.scriptdir(), "bin"), TESTENV2 = "", TESTENV3 = winos.version()})
```
可以正确生成结果。要加入xmake内置函数的话，加一些处理应该就行：
```lua
function add_runenvs(envs)
envs = envs or {}
local envnames = table.orderkeys(envs)
if #envnames == 0 then return end -- check input
package("__" .. envnames[1] .. #envnames) -- deduplicate name
on_load(function (package)
    for name, value in pairs(envs) do
        package:addenv(name, value)
    end
end)
on_fetch(function (package, opt) return {} end)
package_end()
add_requires("__" .. envnames[1] .. #envnames)
end
```

这样多次调用add_runenvs也没有问题了。剩下两个问题：

1. 这种方式的add_runenvs只能定义description scope可用的值。例如需要读取文件，定义 `TESTFILE = io.readfile("testfile")` ，就只能手写繁琐的package定义了。
2. 这种方式定义的package尽管是fetchonly的空package，仍然会在.xmake/packages产生多余的空文件夹。有没有可能对fetchonly的package不要生成package hash文件夹？

### Describe alternatives you've considered

```lua
function add_metapackage(load)
package("__phony")
on_load(load)
on_fetch(function (package, opt) return {} end)
package_end()
add_requires("__phony")
end
```
仍保留package定义的部分给用户，但传入一个on_load函数：
```lua
add_metapackage(function (package)
    package:addenv("TESTENV", io.readfile("testfile"))
end)
```
这样可以解决上面的问题1，只是需要多写一点代码。并且这种形式不仅限于加环境变量，也可以用来做别的事情。（这里去重的话只能用load函数的地址了；我不太清楚怎么做）

**Comment by waruqi** [comment]
试下这个 patch, https://github.com/xmake-io/xmake/pull/5582

脚本，table 描述域设置都可以

```lua
includes("@builtin/xrepo")

xrepo_addenvs(function (package)
    package:addenv("FOO", "FOO")
end)

xrepo_addenvs({BAR = "BAR"})
```

**Comment by waruqi** [comment]
另外加了一个可以快速设置单个 envs 的 

```lua
xrepo_addenv("ZOO", "ZOO")
```

**Comment by xq114** [comment]
> 这种方式定义的package尽管是fetchonly的空package，仍然会在.xmake/packages产生多余的空文件夹。有没有可能对fetchonly的package不要生成package hash文件夹？

这块好像还没解决

**Comment by waruqi** [comment]
> > 这种方式定义的package尽管是fetchonly的空package，仍然会在.xmake/packages产生多余的空文件夹。有没有可能对fetchonly的package不要生成package hash文件夹？
> 
> 这块好像还没解决

再试试

**Comment by xq114** [comment]
这里实现还是有问题，当加的变量比较复杂（比如路径）
```
xrepo_addenv("CMAKE_PREFIX_PATH", "C:\\Users\\xq114\\Downloads\\libtorch")
```
会报错
```
error: @programdir\core\main.lua:329: @programdir\modules\async\runjobs.lua:325: @programdir\core\package\package.lua:718: cannot create filelock for package(__xrepo_addenv_CMAKE_PREFIX_PATHC:\Users\xq114\Downloads\libtorch)!
```
去重的时候简单拼接还是不行，会有非法字符，包括xrepo_addenvs使用的table也不行，含有":"字符。理想方式是使用hash，但description scope用不了hash.md5
