### ISSUE TITLE
`xmake check clang.tidy` doesn't follow non-default path to the compile_commands.json

### ISSUE THREAD

**Issue by yh-sb** [xmake-io/xmake#5583]
### Xmake Version

2.9.4

### Operating System Version and Architecture

Windows 11 23H2 22631.4037

### Describe Bug

Whet custom location to compile_commands.json is set (`build/compile_commands.json`), `xmake check clang.tidy` can't find it and creates new compile_commands.json each time:

```
clang-tidy -p C:\Users\Y\AppData\Local\Temp\.xmake\240907\_B4E95247014C4A708F2AA4B170AA47A0.dir\compile_commands.json ....
```

### Expected Behavior

`xmake check clang.tidy` should use compile_commands.json created by xmake during the config or build steps.

### Project Configuration

```lua
add_rules("mode.debug", "mode.release", "plugin.compile_commands.autoupdate", {outputdir = "build"})
set_targetdir("$(buildir)")

target("app")
    add_files(
        "main.cpp"
    )

```

### Additional Information and Error Logs

Here is xmake lua code that checks compile_commands.json by hardcoded path:
https://github.com/xmake-io/xmake/blob/3ab8306f221bb7c5cee789044eeafff419b1e15c/xmake/modules/private/check/checkers/clang/tidy.lua#L116

**Comment by waruqi** [comment]
try this patch. https://github.com/xmake-io/xmake/pull/5586

we need pass `--compdb=build/compile_commands.json` to clang tidy

**Comment by yh-sb** [comment]
Is it possible to somehow grab the compile_commands.json path from project setting in **tidy.lua**?

`add_rules("plugin.compile_commands.autoupdate", {outputdir = "build"})`

**Comment by yh-sb** [comment]
It works fine, `xmake check clang.tidy` is using compile_commands.json even with custom path `, {outputdir = "CUSTOM_PATH"}`.
Thank you.
