### ISSUE TITLE
`xmake check clang.tidy` passes non-C++ files by default

### ISSUE THREAD

**Issue by yh-sb** [xmake-io/xmake#5584]
### Xmake Version

2.9.4

### Operating System Version and Architecture

Windows 11 23H2 22631.4037

### Describe Bug

When non C++ files are present in sources, for example Windows icon file `icon.rc`
```lua
    if is_host("windows") then
        add_files("icon.rc")
    end
```
Then it passed to clang-tidy and check is broken since .rc is not a C++ file:
```bash
> xmake check clang.tidy

2 warnings and 2 errors generated.
Error while processing D:\dev\cpp\opengl-app\icon.rc.
D:\dev\cpp\opengl-app\icon.rc:1:1: error: unknown type name 'IDI_ICON1' [clang-diagnostic-error]
    1 | IDI_ICON1 ICON DISCARDABLE "icon.ico"
      | ^
D:\dev\cpp\opengl-app\icon.rc:1:11: error: variable 'ICON' is non-const and globally accessible, consider making it const [cppcoreguidelines-avoid-non-const-global-variables,-warnings-as-errors]
    1 | IDI_ICON1 ICON DISCARDABLE "icon.ico"
      |           ^
D:\dev\cpp\opengl-app\icon.rc:1:11: error: variable 'ICON' can be made static or moved into an anonymous namespace to enforce internal linkage [misc-use-internal-linkage,-warnings-as-errors]
D:\dev\cpp\opengl-app\icon.rc:1:15: error: expected ';' after top level declarator [clang-diagnostic-error]
    1 | IDI_ICON1 ICON DISCARDABLE "icon.ico"
      |               ^
      |               ;
2 warnings treated as errors
error: execv(clang-tidy -p C:\Users\Y\AppData\Local\Temp\.xmake\240908\_295E351DD70344108584FA1227B2FF10.dir\compile_commands.json D:\dev\cpp\opengl-app\icon.rc) failed(1)
```

I know about `-f *.cpp` option, but it's slightly inconvenient to pass it each time.

### Expected Behavior

By default need to ignore such non C++ files when passing files to clang-tidy.

Maybe need to have regex pattern to ignored filenames or something like this?

### Project Configuration

```lua
add_rules("mode.debug", "mode.release")

target("app")
    add_files(
        "main.cpp"
    )
    
    if is_host("windows") then
        add_files("icon.rc")
    end

```

### Additional Information and Error Logs

There is code which handles adding files to the sourcelist which passed to clang-tidy:
https://github.com/xmake-io/xmake/blob/dbf5b7617da2ee5cdf03e7d325aee5c995fa2080/xmake/modules/private/check/checkers/clang/tidy.lua#L138

And then:
https://github.com/xmake-io/xmake/blob/dbf5b7617da2ee5cdf03e7d325aee5c995fa2080/xmake/modules/private/check/checkers/clang/tidy.lua#L72

**Comment by SirLynix** [comment]
You shouldn't use is_host but is_plat to test platforms, even though I don't think it fixes this issue

**Comment by yh-sb** [comment]
Why I shouldn't use `is_host` since icon.rc is handled by all toolchains (MSVC, MinGW and Clang) ?

**Comment by SirLynix** [comment]
`is_host` tests the operating system xmake is running on, `is_plat` tests the target platform the executable is built for.

`is_host("windows")` would return false on Linux compiling for Windows using Clang/MinGW for example.

In your case you should use `is_plat("windows", "mingw")`

**Comment by yh-sb** [comment]
How to deal with Clang in Windows this way?

**Comment by SirLynix** [comment]
Clang is a toolchain, not a platform, when you're using Clang you're still targeting the windows platform. (`windows` platform doesn't mean MSVC, it means MSVC-compatible, which includes Clang). If you're using MinGW Clang, you're on the mingw platform as well. (the only difference between windows and mingw platforms is their ABI, and since they're not compatible xmake differentiate them)

**Comment by yh-sb** [comment]
Meanwhile I am adding new option to clang.tidy check:
```bash
    -i,   ignore                   Set files ignore pattern
                                   e.g.
                                       - xmake check clang.tidy -i '*.rc;*.proto'
                                   By default it's *.rc
```

**Comment by SirLynix** [comment]
Maybe we should reverse it and make it as "supported extensions only". Source files can include anything using rules (even binary files, e.g. utils.bin2c).

**Comment by waruqi** [comment]
try this patch. https://github.com/xmake-io/xmake/pull/5586

**Comment by yh-sb** [comment]
Now `sourcefiles` is completly empty and clang-tidy is not called at all.

**Comment by waruqi** [comment]
try it again. `xmake update -s dev`

**Comment by yh-sb** [comment]
Now it works fine!

By the way, I noticed that clang-tidy called multiple times (once per each c++ file). Have you considered that all c++ files can be passed to call clang-tidy once?
`clang-tidy [options] <source0> [... <sourceN>]`

**Comment by waruqi** [comment]
try it again. https://github.com/xmake-io/xmake/pull/5592

**Comment by yh-sb** [comment]
I tested it and it works fine.

**Regarding cli option string length limit:**
We can pass files to clang-tidy by relative paths instead of absolute path. It saves the space in cli options string. I tested it manually by passing relative paths (from the project root directory where top xmake.lua is located) and it works fine as well.

**Comment by yh-sb** [comment]
Also worth to mention this PR in clang project: [#103499 avoid limits on number of sources by accepting a params file](https://github.com/llvm/llvm-project/issues/103499)

**Comment by waruqi** [comment]
> I tested it and it works fine. All C++ project files are passed in the one row (one clang-tidy call).
> 
> **Regarding cli option string length limit:** We can pass files to clang-tidy by relative paths instead of absolute path. It saves the space in cli options string. I tested it manually by passing relative paths (from the project root directory where top xmake.lua is located) and it works fine as well.

It doesn't solve the problem. The length limit still exists, provided enough source files are encountered.

**Comment by waruqi** [comment]
> Also worth to mention this PR in clang project: [#103499 avoid limits on number of sources by accepting a params file](https://github.com/llvm/llvm-project/issues/103499)

But it's not supported right now.
