### ISSUE TITLE
platform为windows的情况下默认禁用mingw的库文件

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#5595]
### 你在什么场景下需要该功能？

相关讨论的链接
https://github.com/xmake-io/xmake/issues/5527#issuecomment-2339906801
https://github.com/xmake-io/xmake/issues/4479
https://github.com/xmake-io/xmake/issues/5527#issuecomment-2340004518

之前遇到了这个问题，但是其实是没有解决的，只是自己把PATH里面的mingw/bin去掉了

改进总结：平台指定为windows之后，即便PATH里面有pkg-config，也会默认禁用mingw的库

### 描述可能的解决方案

感谢 @xq114  提到的 https://github.com/xmake-io/xmake/issues/5527#issuecomment-2340004518

**Comment by star-hengxing** [comment]
> 主要问题应该是“path 里面加了 pkg-config”，xmake会使用这个msys下的pkg-config

话说为啥 xmake 会去找 pkg-config，不应该和 cmake/meson 一样么。
参考 https://github.com/xmake-io/xmake/issues/5474 ，windows 平台应该只找 pkgconf。

**Comment by xq114** [comment]
> 话说为啥 xmake 会去找 pkg-config，不应该和 cmake/meson 一样么。 参考 #5474 ，windows 平台应该只找 pkgconf。

pkg-config能找到的pkgconf也会找到，这不是关键问题，关键是找到之后判定后缀是.a还是.lib

**Comment by xq114** [comment]
msys2的pkg-config好像内置了PKG_CONFIG_PATH，不过msys2也能装pkgconf，不用msys2也能装pkg-config，这两的区别不是决定性的

**Comment by waruqi** [comment]
> > 话说为啥 xmake 会去找 pkg-config，不应该和 cmake/meson 一样么。 参考 #5474 ，windows 平台应该只找 pkgconf。
> 
> pkg-config能找到的pkgconf也会找到，这不是关键问题，关键是找到之后判定后缀是.a还是.lib

目前找到后，返回的都是 links ，并不是完整的 filename，而且他设置了 -p windows ，用的 msvc ，那么即使 pkg-config 返回了 `-lz -lfoo`，xmake 解析成 links (z, foo) ，然后丢给 msvc，xmake 会自动加 `z.lib`, `foo.lib` 。。msvc 的 link.exe 是不会找到 mingw 里面的 `.a` 库的。。

https://github.com/xmake-io/xmake/blob/9bb96d5156c7e1766d761589f927eb30d5229f84/xmake/modules/core/tools/link.lua#L106

而之前 #4479 里面反应的 msys/mingw库混用问题，不是库文件混用，是 pkg-config 返回的  includedirs 导致的混用冲突，这里面还是有区别的。

下面是 #4479 之前的错误描述：

> 尽管当前项目指定了msvc工具链，但是会去使用msys的头文件，头文件混用，产生了错误的提示。

**Comment by xq114** [comment]
> 目前一种方式，就是对 windows 平台，完全禁用 pkgconfig 自动找库 ..
> 
> https://github.com/xmake-io/xmake/blob/6aa2fa8a103ab33412cef65ce2afdff99e71f06b/xmake/modules/package/manager/find_package.lua#L67

这也不合适吧，pkgconfig还是有用的，检测到.a就排除也可以避免头文件混用，而且现在本来就要提取libfiles，其中顺便做个检测不好吗

**Comment by xq114** [comment]
不过考虑到有headeronly的library，完全禁用也可以

**Comment by waruqi** [comment]
> > 目前一种方式，就是对 windows 平台，完全禁用 pkgconfig 自动找库 ..
> > https://github.com/xmake-io/xmake/blob/6aa2fa8a103ab33412cef65ce2afdff99e71f06b/xmake/modules/package/manager/find_package.lua#L67
> 
> 这也不合适吧，pkgconfig还是有用的，检测到.a就排除也可以避免头文件混用，而且现在本来就要提取libfiles，其中顺便做个检测不好吗

没懂，怎么个检测 .a 排除法

**Comment by xq114** [comment]
> 
> 没懂，怎么个检测 .a 排除法

https://github.com/xmake-io/xmake/blob/dev/xmake/modules/package/manager/pkgconfig/find_package.lua#L88-L89 这里加个判断？

**Comment by waruqi** [comment]
> > 没懂，怎么个检测 .a 排除法
> 
> https://github.com/xmake-io/xmake/blob/dev/xmake/modules/package/manager/pkgconfig/find_package.lua#L88-L89 这里加个判断？

windows plat 检测到 .a 就返回 nil? 那 headeronly 怎么处理呢

**Comment by waruqi** [comment]
我暂时不清楚 #4479 里面的运行环境，但是根据目前的信息看，他是在加载了 msys2/mingw 的环境下，强行走 `xmake f -p windows` 去切的 msvc 。。导致的  msvc 和 msys2/mingw 之间的冲突。

本身 windows 下用 pkg-config 并没啥问题，它支持 windows ，那就应该能用。

如果是上述我猜想的环境，那么 应该还存在 PKG_CONFIG_PATH 变量，设置到了 msys2 的路径，类似这种

```console
$ echo $PKG_CONFIG_PATH
/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig
```

这会导致 pkg-config 默认从 msys2 中找库。

如何这个运行环境猜测的没问题，那么应该可以通过下面的方式来解决：

1. pkgconfig/find_package 针对 windows plat 下，直接屏蔽系统 os.getenv("PKG_CONFIG_PATH") 的配置，去找库，不再从系统库中去找，仅仅从包的 PKG_CONFIG_PATH 配置中找库。
2. 针对 mingw 开放系统 PKG_CONFIG_PATH 下的路径查找。

**Comment by xq114** [comment]
> 1. pkgconfig/find_package 针对 windows plat 下，直接屏蔽系统 os.getenv("PKG_CONFIG_PATH") 的配置，去找库，不再从系统库中去找，仅仅从包的 PKG_CONFIG_PATH 配置中找库。
> 2. 针对 mingw 开放系统 PKG_CONFIG_PATH 下的路径查找。

包的 PKG_CONFIG_PATH 是指xmake安装的包吗？那就无意义了，不如直接禁用pkgconfig。

 https://github.com/xmake-io/xmake/blob/6aa2fa8a103ab33412cef65ce2afdff99e71f06b/xmake/modules/package/manager/find_package.lua#L67 在这里改的话我理解还是可以显式写 pkgconfig::xxx 来查找pkgconfig的包，这样处理就可以，windows不加pkgconfig::前缀就不找pkgconfig

**Comment by waruqi** [comment]
> > 1. pkgconfig/find_package 针对 windows plat 下，直接屏蔽系统 os.getenv("PKG_CONFIG_PATH") 的配置，去找库，不再从系统库中去找，仅仅从包的 PKG_CONFIG_PATH 配置中找库。
> > 2. 针对 mingw 开放系统 PKG_CONFIG_PATH 下的路径查找。
> 
> 包的 PKG_CONFIG_PATH 是指xmake安装的包吗？那就无意义了，不如直接禁用pkgconfig。
> 
> https://github.com/xmake-io/xmake/blob/6aa2fa8a103ab33412cef65ce2afdff99e71f06b/xmake/modules/package/manager/find_package.lua#L67
> 
> 在这里改的话我理解还是可以显式写 pkgconfig::xxx 来查找pkgconfig的包，这样处理就可以，windows不加pkgconfig::前缀就不找pkgconfig

在这里改，就是 windows 下，完全去掉 pkgconfig 的查找

**Comment by waruqi** [comment]
暂时对 windows 禁用了 pkgconfig 查找，但是 mingw/msys2 下依然可用。
