### ISSUE TITLE
stackoverflow when run xmake project 

### ISSUE THREAD

**Issue by raininfall** [xmake-io/xmake#560]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
stackoverflow when run **xmake project -k vs2017**

### Expected behavior
without error

### Error output
[@programdir\core\sandbox\modules\io.lua:101]: in function '_write'
    [@programdir\core\sandbox\modules\io.lua:101]: in function '_write'
    [@programdir\core\sandbox\modules\io.lua:101]: in function '_write'
    [@programdir\core\sandbox\modules\io.lua:101]: in function '_write'
    [@programdir\core\sandbox\modules\io.lua:101]: in function '_write'
    [@programdir\core\sandbox\modules\io.lua:101]: in function '_write'
    [@programdir\core\sandbox\modules\io.lua:101]: in function '_write'
    [@programdir\core\sandbox\modules\io.lua:101]: in function '_write'
    [@programdir\core\sandbox\modules\io.lua:101]: in function '_write'
    [@programdir\core\sandbox\modules\io.lua:101]: in function '_write'
    [@programdir\core\sandbox\modules\io.lua:101]: in function '_write'
    [@programdir\core\sandbox\modules\io.lua:101]: in function '_write'
    [@programdir\core\sandbox\modules\io.lua:101]: in function '_write'
    [@programdir\core\sandbox\modules\io.lua:101]: in function 'write'
    [@programdir\core\sandbox\modules\io.lua:109]: in function '_print'
    [@programdir\plugins\project\vstudio\impl\vsfile.lua:33]: in function 'print'
    [...gramdir\plugins\project\vstudio\impl\vs201x_solution.lua:27]: in function '_make_header'
    [...gramdir\plugins\project\vstudio\impl\vs201x_solution.lua:109]: in function 'make'
    [@programdir\plugins\project\vstudio\impl\vs201x.lua:286]: in function 'make'
    [@programdir\plugins\project\vstudio\vs.lua:48]:
    [@programdir\plugins\project\main.lua:65]: in function '_make'
    [@programdir\plugins\project\main.lua:78]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:508]: in function 'run'
    [@programdir\core\main.lua:236]:

### Related Environment
xmake version: v2.2.8
os: windows 10

**Comment by waruqi** [comment]
I'll look at it later, you can try `xmake project -k vsxmake`

**Comment by waruqi** [comment]
I fix this problem, you can run `xmake update dev` or download and install https://ci.appveyor.com/api/buildjobs/x70d22up326bygah/artifacts/xmake-installer.exe to try it again.

But I still recommend that you use `xmake project -k vsxmake` instead of `vs201x`

You can see https://xmake.io/#/plugin/builtin_plugins?id=compile-with-xmake-integration

**Comment by raininfall** [comment]
Update and sloved.
