### ISSUE TITLE
Pass file's path when trying to export all symbols

### ISSUE THREAD

**Issue by 01Pollux** [xmake-io/xmake#5601]
### Is your feature request related to a problem? Please describe.

Currently, there is no way to know the file path from which a symbol was exported.

### Describe the solution you'd like

It would be useful to have a way to export all symbols from files inside the 'Public/' directory, for example.
The pseudocode could look like this:
``` LUA
target("bar")
    set_kind("shared")
    add_files("src/bar.cpp")
    add_rules("utils.symbols.export_all", {export_filter = function (symbol, path)
        if path:find("Public/", 1, true) then
            return true
        end
    end})
```

**Comment by waruqi** [comment]
If we pass sourcefile as path, the implementation is very complicated and it is not very accurate. This is because some rules automatically generate objectfiles and do not save the corresponding sourcefiles.

So I think it might be better and more accurate to pass objectfile as the path.

**Comment by waruqi** [comment]
try this patch. https://github.com/xmake-io/xmake/pull/5608

```lua
target("bar")
    set_kind("shared")
    add_files("src/bar.cpp")
    add_rules("utils.symbols.export_all", {export_filter = function (symbol, opt)
        local filepath = opt.sourcefile or opt.objectfile
        if filepath and filepath:find("bar.cpp", 1, true) and symbol:find("add", 1, true) then
            print("export: %s at %s", symbol, filepath)
            return true
        end
    end})
```
