### ISSUE TITLE
on_run is not invoked if Visual Studio is unable to start debugger for unknown toolchains

### ISSUE THREAD

**Issue by ArgoreOfficial** [xmake-io/xmake#5602]
### Xmake Version

2.9.4

### Operating System Version and Architecture

Windows 10

### Describe Bug

When working with a custom toolchain, pressing Start in Visual Studio 2022 throws an error for a missing debugger.
There doesn't seem to be a way to run custom debuggers at the moment, so I hoped I could invoke the platform debugger with on_run as a workaround, but it is not called if the application fails to start. 

### Expected Behavior

If Visual Studio does not have a debugger, on_run should still be invoked.
Or preferably, allow a custom debugger to be added to the toolchain. Related #5554 

### Project Configuration

cannot provide

### Additional Information and Error Logs

Visual Studio:
Unable to start debugging. Check your debugger settings by opening project properties and navigating to 'Configuration Properties-->Debugging'

**Comment by waruqi** [comment]
vs/vsxmake generator does not support the custom debugger.
