### ISSUE TITLE
set_values(a, b, c) will set_default(a) by default

### ISSUE THREAD

**Issue by Freed-Wu** [xmake-io/xmake#5605]
### 你在什么场景下需要该功能？

Like meson, `set_values(a, b, c)` will `set_default` 1st value as default.

### 描述可能的解决方案

/

**Comment by waruqi** [comment]
you can call `set_default` to set `a`

**Comment by Freed-Wu** [comment]
I found by default it will `set_default(nil)`, not sure the behaviour is better...
