### ISSUE TITLE
vscode下终端下运行xmake显示问题

### ISSUE THREAD

**Issue by bstaint** [xmake-io/xmake#561]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题

在vscode终端下运行xmake显示有问题：
![screenshot](https://user-images.githubusercontent.com/5853792/64060068-57fd6e80-cbfa-11e9-974c-d5a8fcee7aee.png)

### 相关环境
Windows 7
VSCode 1.37.1
xmake v2.2.8+201908261502,

**Comment by waruqi** [comment]
恩 目前xmake在win上默认放开 color code输出了，win10以上的cmd应该都是支持的 回头我尝试改进下 看看能否更精准的检测下环境来判断是否启用 。。

目前你可以通过xmake g --theme=plain全局切到plain主题禁用color code输出 

或者通过设置COLOR_TERM=nocolor环境变量来禁用

也可以将vscode的终端shell切到powershell试试 看看color是否能正常显示

**Comment by bstaint** [comment]
我尝试了xmake g --theme=plain和COLOR_TERM=nocolor都无效，%appdata%\.xmake\xmake.conf中有配置信息，但是只有在vscode中会出现这种情况，单独打开cmd和powershell都是正常无颜色的，我还测试msys2的bash也是一样的情况。

**Comment by waruqi** [comment]
好的 我回头看下

**Comment by waruqi** [comment]
COLORTERM=nocolor 环境变量你再试试，之前我说错了。。

**Comment by bstaint** [comment]
`COLORTERM=nocolor`可以

**Comment by waruqi** [comment]
那就先这样吧 回头我看看能否更好的检测下环境
