### ISSUE TITLE
add_requires()期望支持config={shared=true}

### ISSUE THREAD

**Issue by jason-fan** [xmake-io/xmake#562]
1、由于lua动态加载C模块(require())需要编译为shared方式，所以，我们期望add_requires() 支持config={shared=true}，但实际还是生成static lib

2、我们又需要在多个lua版本中切换，期望xmake build & xmake install时能把requires的lua dll/so一起拷贝出来，目前是不支持的，ruki很好，给我解答了这个问题，可以在after_install的事件中通过 target:pkg("lua"):get("linkdirs")获取到包的输出目录，只是，还是卡在了问题1.

期望ruki有空时能支持 package的编译配置。感谢！

**Comment by waruqi** [comment]
等回头有时间我完善下

**Comment by OpportunityLiu** [comment]
1那个不是应该在需要导出的函数前面加上 `__declspec(dllexport)` 就完了？

**Comment by jason-fan** [comment]
宿主需要采用动态连接库的形式编译的，不然require会失败

**Comment by waruqi** [comment]
我加上了，你可以试试，更新到dev版本：xmake update -s dev

不过xmake-repo上我目前只更新了dev分支，你需要在xmake.lua手动切换到dev版本repo来更新lua包：

```lua
add_requires("luajit", {system = false, configs = {shared = true}})
add_repositories("xmake-repo-dev https://github.com/xmake-io/xmake-repo.git dev")

target("test")
    set_kind("binary")
    add_files("src/*.c") 
    add_packages("lua")
```

设置system=false禁止检测系统第三方lua包，仅从xmake-repo包中获取，方便测试
add_repositories里面切到dev的xmake-repo

如果之前已装了lua，先卸载下，然后xmake f -c清下cache

```console
xmake require --uninstall lua
xmake f -c -v -D 
xmake
```

**Comment by waruqi** [comment]
> 1那个不是应该在需要导出的函数前面加上 `__declspec(dllexport)` 就完了？

他是需要so/dll库，xmake install时候，自动把安装的动态库一起导出打包安装，现有版本add_requires仅支持编译static库

**Comment by waruqi** [comment]
@jason-fan 不过xmake install，等1跑通后，你先暂时 after_install 里面自己去 os.cp下吧。。这块需求偏定制化，暂时不太好内置支持。在 after_install自己copy也没几行代码。

**Comment by jason-fan** [comment]
很好，感谢这么快就解决了问题
