### ISSUE TITLE
Default Update from Github

### ISSUE THREAD

**Issue by TabNahida** [xmake-io/xmake#5620]
### Is your feature request related to a problem? Please describe.

gitee经常ping很快，但是带宽很低，然后被选择到gitee上，半天更新不完

### Describe the solution you'd like

提供一个用户选项，可以选择自己的默认更新的网站

### Describe alternatives you've considered

如果自己维护了一个xmake的版本，也可以支持一下默认更新的网站选自己的网站

**Comment by waruqi** [comment]
github 经常被墙不稳，也好不到哪去， 自己改下就行了 https://xmake.io/#/guide/configuration?id=xmake_main_repo

**Comment by TabNahida** [comment]
> github 经常被墙不稳，也好不到哪去， 自己改下就行了 https://xmake.io/#/guide/configuration?id=xmake_main_repo

我的意思就是不是靠ping来决定，而是用户可以自己选择，然后就一直用这个

**Comment by TabNahida** [comment]
> github 经常被墙不稳，也好不到哪去， 自己改下就行了 https://xmake.io/#/guide/configuration?id=xmake_main_repo

这个解决不了xmake update

**Comment by waruqi** [comment]
> > github 经常被墙不稳，也好不到哪去， 自己改下就行了 https://xmake.io/#/guide/configuration?id=xmake_main_repo
> 
> 这个解决不了xmake update

xmake update github:xmake-io/xmake

**Comment by TabNahida** [comment]
> > > github 经常被墙不稳，也好不到哪去， 自己改下就行了 https://xmake.io/#/guide/configuration?id=xmake_main_repo
> > 
> > 
> > 这个解决不了xmake update
> 
> xmake update github:xmake-io/xmake

感谢，这些可以加到文档里吗

**Comment by waruqi** [comment]
原本文档里就有，搜一下 xmake update 就出来了，而且 --help 里也有说明

https://xmake.io/#/guide/installation?id=update-upgrade
