### ISSUE TITLE
release mode 中 NDEBUG 也应该为cuflags添加

### ISSUE THREAD

**Issue by cherichy** [xmake-io/xmake#5632]
### 你在什么场景下需要该功能？

目前在rules/mode/xmake.lua中NDEBUG加在cxflags中，对cuda程序而言这个flag就没有作用

### 描述可能的解决方案

在target:add("cxflags", "-DNDEBUG")之后添加target:add("cuflags", "-DNDEBUG")

**Comment by waruqi** [comment]
来个 pr 过来
