### ISSUE TITLE
生成的vsxmake工程包含了排除的文件

### ISSUE THREAD

**Issue by Domain** [xmake-io/xmake#564]
add_files("./src/**.cpp|unit_test.cpp")
这里面unit_test.cpp不应该包含在工程里面吧

**Comment by waruqi** [comment]
贴下你的源文件结构，这个排除的是 src/unit_test.cpp

**Comment by Domain** [comment]
对啊，就是要排除这个，但是生成的工程包含了

**Comment by waruqi** [comment]
生成的什么工程？vs工程？还是vsxmake？

**Comment by waruqi** [comment]
我试了下，不管是vs工程，还是vsxmake工程，还是直接命令行编译。。都ok的么。。src/unit_test.cpp都被正常过滤掉了。。并没有复现你这的问题

你可以确认下，其他`add_files()`里面是否也会吧`./src/unit_test.cpp`给加进去。。

还是不行的，可以提供一个可以复现的demo工程给我，我看下。

```lua
target("test8")
    set_kind("binary")
    add_files("./src/**.cpp|unit_test.cpp") 
```
![Snip20190901_5](https://user-images.githubusercontent.com/151335/64076382-c1fb3e00-ccf6-11e9-90e1-cb5518494e5c.png)

**Comment by waruqi** [comment]
还是不行么？不行的话 提供个demo看下呗？

**Comment by Domain** [comment]
不好意思，暂时没有环境，等有环境弄一个出来

**Comment by Domain** [comment]
好像是我弄错了
