### ISSUE TITLE
便携版xmake生成的vsxmake项目找不到xmake

### ISSUE THREAD

**Issue by Domain** [xmake-io/xmake#5642]
### Xmake 版本

v2.9.5+HEAD.d30de52e9

### 操作系统版本和架构

windows 10

### 描述问题

使用`xmake project -k vsxmake`生成的工程，编译时提示找不到xmake.exe，提示的路径里面确实没有xmake.exe

### 期待的结果

正常编译

### 工程配置

无

### 附加信息和错误日志

C:\Users\admin\AppData\Local\Temp\.xmake0\2.9.5+HEAD.d30de52e9\scripts\vsxmake\vsproj\Xmake.targets(85,5): error : xmake.exe not found at 'C:\Users\admin\AppData\Local\Temp\.xmake0\2.9.5+HEAD.d30de52e9\', please set XMAKE_PROGRAM_DIR in environments or XmakeProgramDir in vcxproj file

**Comment by waruqi** [comment]
试下这个 patch https://github.com/xmake-io/xmake/pull/5650

我这暂时没 vs 环境，如果不行，就自己基于这个 patch 调下，改改。。

**Comment by waruqi** [comment]
bundle 包在这个 patch 的 ci 里面，会有对应 artifacts 提供下载。如果要自己编译 bundle 包，可以执行：

```console
cd core
xmake f --embed=y -c
xmake
```

**Comment by waruqi** [comment]
再试试 

https://github.com/xmake-io/xmake/actions/runs/10990561050/artifacts/1965288123

**Comment by star-hengxing** [comment]
以前设置 programfile 环境变量好像也遇到过这个问题，试了下没问题了
