### ISSUE TITLE
xmake watch命令无法递归检测子目录中文件变动

### ISSUE THREAD

**Issue by Sunrisepeak** [xmake-io/xmake#5645]
### Xmake 版本

2.9.5

### 操作系统版本和架构

Ubuntu24.01

### 描述问题

无法递归检测所有子目录中文件变动

```bash
speak@speak-pc:~/test$ vim watch_test/dir1/dir2/t.text
speak@speak-pc:~/test$ mv watch_test/dir1/dir2/t.text  watch_test/dir1/dir2/t.txt
speak@speak-pc:~/test$ code watch_test/dir1/dir2/t.txt 
speak@speak-pc:~/test$ xmake watch -d  "watch_test"
watching watch_test/** ..
^C
speak@speak-pc:~/test$ tree watch_test/
watch_test/
└── dir1
    └── dir2
        └── t.txt

3 directories, 1 file
```

### 期待的结果

递归监听所有子目录中文件变动

### 工程配置

复现示例

```bash
speak@speak-pc:~/test$ tree watch_test/
watch_test/
└── dir1
    └── dir2
        └── t.txt

3 directories, 1 file
```

### 附加信息和错误日志

speak@speak-pc:~/test$ xmake watch -d  "watch_test"
watching watch_test/** ..
watch_test/dir1/t.text modified
watch_test/dir1/t.text modified
watch_test/dir1/t.text modified
watch_test/dir1/t.text modified

**Comment by Sunrisepeak** [comment]
看了一下可能和依赖库tbox中的`tb_fwatcher_add`接口实现有关

- 在xmake中 recursion 是 bool 类型标识
- tbox中
  - tb_fwatcher_add 的recursion 是 bool 类型标识
  - tb_directory_walk 中是用recursion 用long来标识深度

**可能的解决方法**

- 1. 简单的设置一个 默认的最大递归深度 5 or x
- 2. 修改tb_fwatcher_add接口recursion 和 tb_directory_walk 对齐, 但属于破坏式更新

不知道有没有支持递归多层子目录的想法, 如果比较忙这个工作我可以做

xmake-fwatcher

https://github.com/xmake-io/xmake/blob/a44ccf767d56f8e74006d52616a0234b63ff13f8/xmake/core/sandbox/modules/import/core/base/fwatcher.lua#L34

https://github.com/xmake-io/xmake/blob/a44ccf767d56f8e74006d52616a0234b63ff13f8/xmake/core/base/fwatcher.lua#L59

https://github.com/xmake-io/xmake/blob/a44ccf767d56f8e74006d52616a0234b63ff13f8/core/src/xmake/fwatcher/wait.c#L56

tbox-fwatcher

![image](https://github.com/user-attachments/assets/d9477528-b08f-4974-8504-48d7bb250c97)

```c
tb_void_t tb_directory_walk(tb_char_t const* path, tb_long_t recursion, tb_bool_t prefix, tb_directory_walk_func_t func, tb_cpointer_t priv)
```

**Comment by Sunrisepeak** [comment]
设置默认值的方式

https://github.com/tboox/tbox/pull/266

**Comment by waruqi** [comment]
更新了，再试试
