### ISSUE TITLE
`xmake check clang.tidy` doesn't check headers files

### ISSUE THREAD

**Issue by yh-sb** [xmake-io/xmake#5647]
### Xmake Version

2.9.5

### Operating System Version and Architecture

Windows 11 23H2 22631.4037

### Describe Bug

I've noticed that the `xmake check clang.tidy` command doesn't check header files.
As I understand, it only checks files present in **compile_commands.json**, which does not include header files.

Do you have any ideas on how to fix this?

### Expected Behavior

`xmake check clang.tidy` passes all source files of the project to clang-tidy.

### Project Configuration

```lua
add_rules("mode.debug", "mode.release")

target("app")
    add_files("main.cpp")
```

### Additional Information and Error Logs

No additional information

**Comment by waruqi** [comment]
it should has `-Ixxx` flags in compile_commands.json. Won't clang-tidy look for headers from these flags? Do I need to manually tell it what headers it has?

**Comment by yh-sb** [comment]
clang-tidy doesn't get header files from compile_commands.json. It take for analysis only files which are explicitly passed in source list.

**Comment by waruqi** [comment]
try this patch https://github.com/xmake-io/xmake/pull/5651

**Comment by yh-sb** [comment]
Unfortunately it doesn't help: `headerfiles` is always empty.

**Comment by waruqi** [comment]
Did you set `add_headerfiles`?

**Comment by waruqi** [comment]
> No, I didn't specified `add_headerfiles`. If I list headers using `add_headerfiles`, then clang.tidy check works fine, analyzing listed headers.
> 
> But in most common (non header-only) C++ projects, it's not mandatory to list headers in `add_headerfiles`, right?

Analyzing the header file list is not the work of xmake, it's the work of the compiler. Xmake only tells the compiler `-Ixx` flags. If clang-tidy does not support `-Ixxx` and the user does not specify header files, then xmake cannot do more. You can open a feature request to clang-tidy to support `-Ixxx`.

**Comment by yh-sb** [comment]
Ok, I found another way how to collect and pass c++ files to clang-tidy: `git ls-files '*.c' '*.cc' '*.cpp' '*.cxx' '*.c++' '*.h' '*.hpp' '*.hh'`

**Comment by waruqi** [comment]
you can pass `--files="src/**.cc"` to set them
