### ISSUE TITLE
Cross compile bug

### ISSUE THREAD

**Issue by MaxwellGengYF** [xmake-io/xmake#5658]
### Xmake 版本

v2.9.5+dev.21e4c2a3a

### 操作系统版本和架构

Windows

### 描述问题

同项目使用 cross compile 导致 can not find program ar

### 期待的结果

正常编译。

### 工程配置

``` lua
target("llvm_target")
set_languages("cxx20")
set_toolchains("llvm")
on_load(function(target)
    target:set("kind", "static")
end)
add_files("dummy.cpp")
target_end()

target("clang_cl_target")
set_languages("cxx20")
on_load(function(target)
    target:set("kind", "static")
end)
add_files("dummy.cpp")
target_end()
```

> xmake f -m debug --toolchain=clang_cl -c
> xmake
> xmake f -m release --toolchain=clang_cl -c
> xmake
> xmake f -m debug --toolchain=clang_cl -c
> xmake
...

### 附加信息和错误日志

error: cannot get program for ar

**Comment by waruqi** [comment]
试下，应该可以了，这个跟 cache 没啥关系，是 clang-cl toolchain 的问题。。

因为 msvc/clang-cl 都是用的 link.exe ，但是探测 find_link 需要调用 cl/clang-cl 去尝试编译+ link

切到 clang-cl toolchain 后，envs 被加载为 clang-cl的环境，cl.exe 不在 PATH 里，所以之前 find_link 固定用 cl.exe 去探测，就会出这个问题，导致 link.exe 没找到。

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/pull/5661
