### ISSUE TITLE
添加includes从环境变量包含路径的功能

### ISSUE THREAD

**Issue by Zmmfly** [xmake-io/xmake#5664]
### 你在什么场景下需要该功能？

使用 xmake 制作 SDK，需要将SDK与工程分离，并且需要避免使用`git submodule`的场景

### 描述可能的解决方案

目录结构：
```
C:.
├─app
│      main.c
│      xmake.lua
│
└─foo
        foo.c
        foo.h
        xmake.lua
```

`app/xmake.lua` 内容:
```lua
includes("@env:SDK_PATH")

target("app")
    set_kind("binary")
    add_files("main.c")
    add_deps("foo")
```

### 描述你认为的候选方案

`includes("@env:SDK_PATH")`

**fork中已实现**
https://github.com/Zmmfly/xmake/blob/f04be61e0ce31a83a3646f8a510e9dd0c2e2f60d/xmake/core/base/interpreter.lua#L1713-L1730

**Comment by star-hengxing** [comment]
有些工具链需要些一堆 xmake.lua ，而作为远程包又无法去 includes 这些。感觉这个接口还有扩展空间。
比如工程初始化前可以先执行 setup.lua 调用 `xrepo install` 安装工具链，然后 includes `package:installdir`

**Comment by waruqi** [comment]
原本就支持，用 os.getenv
```lua
includes(os.getenv("SDK_PATH"))
```

**Comment by Zmmfly** [comment]
> 原本就支持，用 os.getenv
> 
> ```lua
> includes(os.getenv("SDK_PATH"))
> ```

没想到这一点，看了内置变量后思维停留在 `$(env SDK_PATH)` 这种方法上，然后学着`@builtin`就变成了`@env:SDK_PATH`
