### ISSUE TITLE
.xmake/linux/x86_64/cache/config failed, cannot serialize: not enough memory!

### ISSUE THREAD

**Issue by hkunbin** [xmake-io/xmake#567]
kirito@HK:~/root_home/document/svn/ZhuHai/svn_root/Trunks/BLELock/ARM/BLELock_source_easy/xmake$ xmake

error: save /home/kirito/root_home/document/svn/ZhuHai/svn_root/Trunks/BLELock/ARM/BLELock_source_easy/xmake/.xmake/linux/x86_64/cache/config failed, cannot serialize: not enough memory!
kirito@HK:~/root_home/document/svn/ZhuHai/svn_root/Trunks/BLELock/ARM/BLELock_source_easy/xmake$ 
kirito@HK:~/root_home/document/svn/ZhuHai/svn_root/Trunks/BLELock/ARM/BLELock_source_easy/xmake$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.8G  4.0K  7.8G   1% /dev
tmpfs           1.6G  1.2M  1.6G   1% /run
/dev/sda8       275G  256G  5.2G  99% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            7.8G   39M  7.8G   1% /run/shm
none            100M  4.0K  100M   1% /run/user
/dev/sda7       304G  199G   90G  69% /home
kirito@HK:~/root_home/document/svn/ZhuHai/svn_root/Trunks/BLELock/ARM/BLELock_source_easy/xmake$ free -h
             total       used       free     shared    buffers     cached
Mem:           15G        11G       4.2G       214M       606M       1.3G
-/+ buffers/cache:       9.4G       6.2G
Swap:         1.9G         0B       1.9G
kirito@HK:~/root_home/document/svn/ZhuHai/svn_root/Trunks/BLELock/ARM/BLELock_source_easy/xmake$

**Comment by waruqi** [comment]
I tried to fix it, you can update it and try it again. `xmake update -s dev`

**Comment by hkunbin** [comment]
xmake can work now, thanks a lot.
