### ISSUE TITLE
install命令没有复制依赖的package里的动态链接库

### ISSUE THREAD

**Issue by vkensou** [xmake-io/xmake#5673]
### Xmake 版本

v2.9.5+HEAD.d30de52e9

### 操作系统版本和架构

Windows 10

### 描述问题

xmake install命令无法将target通过add_packages引入的动态链接库复制到安装目录。目前测试了几个只有libsdl可以在windows平台复制到安装目录。

### 期待的结果

主target的packages依赖的动态库和主target deps的target的packages依赖的动态库都复制到安装目录

### 工程配置

xmake.lua
```
if is_plat("android") then
    set_runtimes("c++_shared")
else 
    set_runtimes("MD")
end

add_requires("libsdl", {configs = {sdlmain = true, shared = true}})
add_requires("udt", {configs = {shared = true}})
if is_plat("android") then
    add_requires("clipper2", {configs = {shared = true}})
else 
    add_requires("xlsxio", {configs = {shared = true}})
end 

target("testdep")
    set_kind("shared")
    add_files("dep.c")
    add_packages("udt")
    add_rules("utils.symbols.export_all")

target("main")
    add_packages("libsdl", "clipper2")
    if is_plat("android") then
        add_packages("clipper2")
    else 
        add_packages("xlsxio")
    end

    add_deps("testdep")
    add_files("main.cpp")

    if is_plat("android") then 
        set_kind("shared")
        add_syslinks("log", "android")
    else
        set_kind("binary")
        add_ldflags("/subsystem:console")
    end
```
main.cpp
```
#ifdef __cplusplus
extern "C"
#endif
int SDL_main(int argc, char* argv[])
{
    return 0;
}
```
dep.c
```
extern int add(int a, int b)
{
    return a + b;
}
```

### 附加信息和错误日志

首先输入以下命令：
```
xmake f -y -p windows -a x64 -m release
xmake build -r
xmake install -a -o build
```
发现build/bin目录下有以下文件
```
bin
|--main.exe
|--SDL2.dll
|--testdep.dll
```
预期还应该有xlsxio.dll和udt.dll

然后再输入以下命令：
```
xmake f -y -p android -a arm64-v8a -m release
xmake build -r
xmake install -a -o build
```
发现build/lib目录下有以下文件
```
bin
|--main.so
|--testdep.so
```
预期还应该有libSDL2.so、libclipper2.dll和libudt.dll，以及libc++_shared.so

**Comment by waruqi** [comment]
>     add_deps(testdep)   --为什么这里不能加引号？

就是因为你没加引号，等于是 `add_deps(nil)` ，空操作，根本没设置 testdep 依赖，当然不会去安装它的 packages

**Comment by vkensou** [comment]
> > ```
> > add_deps(testdep)   --为什么这里不能加引号？
> > ```
> 
> 就是因为你没加引号，等于是 `add_deps(nil)` ，空操作，根本没设置 testdep 依赖，当然不会去安装它的 packages

我加上引号以后，在windows下报错：fatal error LNK1181: 无法打开输入文件“testdep.lib”

```xmake.lua
target("testdep")
    set_kind("shared")
    add_files("dep.cpp")

target("main")
    add_deps("testdep")
    add_files("main.cpp")

    if is_plat("android") then 
        set_kind("shared")
        add_syslinks("log", "android")
    else
        set_kind("binary")
        add_ldflags("/subsystem:console")
    end
```

**Comment by waruqi** [comment]
> 我加上引号以后，在windows下报错：fatal error LNK1181: 无法打开输入文件“testdep.lib”

没导出符号。。win 动态库需要自己配置导入符号，自己 google 下

**Comment by vkensou** [comment]
> > 我加上引号以后，在windows下报错：fatal error LNK1181: 无法打开输入文件“testdep.lib”
> 
> 没导出符号。。win 动态库需要自己配置导入符号，自己 google 下

好吧，我忘了。。。  我把1楼的代码改好了，但我说的问题还是存在，几个packages的dll还是没复制过来。

**Comment by waruqi** [comment]
那你给下改好的工程，完整的发来

**Comment by waruqi** [comment]
目前的策略是，你的 target 确实用到了 package 里面的 dll，存在了依赖关系，xmake 会自动调用 dumpbin/objdump 去解析你 target 里面的 dll 依赖，然后 install 时候保留他们，其他没用到的 package dll 不会去安装，安装了也没用到。。

你这里 sdl.dll 安装了，说明确实用到了，其他库 dll 没安装，就是你代码中实际上没用到，没必要去装。因为 package 里面有时候会有大量无用 dll，全去装没必要。

如果你的代码里面确实用到了，但还是没安装，那就自己调下这里：

https://github.com/xmake-io/xmake/blob/654f149719975310ee8998e3d6c1f120ddcb8641/xmake/modules/target/action/install/main.lua#L80-L86

https://github.com/xmake-io/xmake/blob/dev/xmake/modules/utils/binary/deplibs.lua

你也可以强制开启安装所有 dll，启用下这个 policy 就行了。。"install.strip_packagelibs"

**Comment by vkensou** [comment]
感谢，这个policy是我需要的。看来安卓上没复制libsdl2.dll是因为在windows上没法查看.so导致的。

**Comment by vkensou** [comment]
现在就还有一个问题：libc++_shared.so没复制。
在xmake-gradle里是处理了，不过如果能把这一点移到xmake本体里更好。这样就可以完全实现纯c++/xmake开发安卓应用了。

**Comment by waruqi** [comment]
> 现在就还有一个问题：libc++_shared.so没复制。 在xmake-gradle里是处理了，不过如果能把这一点移到xmake本体里更好。这样就可以完全实现纯c++/xmake开发安卓应用了。

不考虑，这不是 xmake 该干的事情
