### ISSUE TITLE
linux跨平台libcurl包 编译错误

### ISSUE THREAD

**Issue by ranwei1025** [xmake-io/xmake#568]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
包依赖编译 
xmake 包含add_requires("libcurl"）
xmake f -p linux -a mips --sdk=/home/toolchains_sdkdir --cross=mips-linux-

### Error output
error: assertion failed!
  => install openssl 1.1.1 .. failed                                                                                                                                                                 
error: install failed!

> If it is a xmake related compilation problem, please add the `-v -D` parameter and give the detailed compilation output information.

### Related Environment
xmake 当前最新版本 ubentu系统

**Comment by waruqi** [comment]
暂时还不支持用户指定的第三方toolchains的交叉编译，目前只有部分包已经完成mingw/ios/android等特定toolchains的交叉编译

具体每个包的支持平台见：https://github.com/xmake-io/xmake-repo/blob/master/PKGLIST.md
