### ISSUE TITLE
加载配置文件的set_toolchains不能全局生效

### ISSUE THREAD

**Issue by liangzc1** [xmake-io/xmake#5682]
### Xmake 版本

2.95

### 操作系统版本和架构

ubuntu 20.04

### 描述问题

根目录set_toolchains能全局生效，根目录直接includes("platform/config/config.lua")，在config.lua里面set_toolchains不能全局生效，也就是另外一个xmake.lua文件下工具链没有生效

### 期待的结果

全局的set_toolchains配置能通过配置文件实现，而不是在根目录写

### 工程配置

config.lua
-- 引入工具链和规则配置
includes("toolchain.lua")

set_plat("cross")
set_arch("mips32r2")
-- 设置全局工具链为 T41
set_toolchains("T41")

根xmake.lua
-- set_toolchains("T41")

includes("platform/config/config.lua")
includes("app/xmake.lua")
includes("samples/xmake.lua")

目标在samples/xmake.lua下定义

### 附加信息和错误日志

envs
C Compiler (cc) not found
gcc
C Compiler (cc): /usr/bin/gcc
yasm
C Compiler (cc) not found
nasm
C Compiler (cc) not found
fasm
C Compiler (cc) not found
cuda
C Compiler (cc) not found
go
C Compiler (cc) not found
rust
C Compiler (cc) not found
swift
C Compiler (cc) not found
gfortran
C Compiler (cc) not found
fpc
C Compiler (cc) not found

**Comment by waruqi** [comment]
includes 的作用是引入所有配置，以及 targets 等各种定义，set_toolchains set_xxx 的所有 target 接口，都是根据 target 作用域设置的。并不会根据 includes 直接生效。。你想要子 xmake.lua 的配置影响 根 xmake.lua

就要在子 xmake.lua 里面用 function 去 wrap 这些 set_toolchains 设置，然后在根目录调用才行。

**Comment by waruqi** [comment]
建议仔细看下作用域相关的文档：https://xmake.io/#/zh-cn/guide/syntax_description?id=%e5%a4%9a%e7%ba%a7%e9%85%8d%e7%bd%ae

**Comment by liangzc1** [comment]
用函数包起来可以生效，感谢解答
