### ISSUE TITLE
val('buildir ') alwasy be empty

### ISSUE THREAD

**Issue by Freed-Wu** [xmake-io/xmake#5684]
### Xmake Version

2.9.4

### Operating System Version and Architecture

ArchLinux

### Describe Bug

```lua
xmake> val('buildir')
< ""
```

### Expected Behavior

Not empty.

### Project Configuration

xmake create -lc

### Additional Information and Error Logs

/

**Comment by waruqi** [comment]
you need to load config cache first.

**Comment by Freed-Wu** [comment]
How to load config cache?

**Comment by waruqi** [comment]
config.load and you need to run `xmake f` first.
Besides, I do not recommend using val. I may deprecate it in the future.

**Comment by Freed-Wu** [comment]
I try:

```sh
xmake f
xmake l
> val('buildir')
```

However still empty :cry:

**Comment by waruqi** [comment]
```console
ruki-2:test ruki$ xmake l
xmake> config = import("core.project.config")
xmake> config.load()
< true
xmake> val("buildir")
< "build"
xmake> config.buildir()
< "build"
```

**Comment by Freed-Wu** [comment]
Thanks!
