### ISSUE TITLE
install命令没有复制静态依赖的package里的动态链接库

### ISSUE THREAD

**Issue by vkensou** [xmake-io/xmake#5692]
### Xmake Version

2.9.5

### Operating System Version and Architecture

Windows 10

### Describe Bug

跟（https://github.com/xmake-io/xmake/issues/5673 ）类似，只不过这次的deps是静态的
静态deps依赖的package里的动态库没有复制到install目录

windows打windows包，SDL2.dll没有复制
windows打android包，libSDL2.so也没有复制

### Expected Behavior

使用到的都复制过去，或者至少xmake.lua里引用的复制过去

### Project Configuration

xmake.lua
```
set_policy("install.strip_packagelibs", false)

add_requires("libsdl", {configs = {sdlmain = true, shared = true}})

target("deps")
    set_kind("static")    <--- 就是这里，shared可以，但static不行
    add_packages("libsdl")
    add_files("frame.cpp")

target("main")
    if is_plat("windows") then
        set_kind("binary")
        add_ldflags("/subsystem:console")
    else 
        set_kind("shared")
    end
    set_rundir("$(projectdir)")
    add_deps("deps")
    add_files("main.cpp")
```
main.cpp
```
#include "frame.h"

#ifdef __cplusplus
extern "C"
#endif
int SDL_main(int argc, char* argv[])
{
    return add(1, 2);
}
```
frame.cpp
```
int add(int a, int b)
{
    return a + b;
}
```
frame.h
```
#ifdef __cplusplus
// extern "C"
#endif
int add(int a, int b);
```

### Additional Information and Error Logs

无

**Comment by star-hengxing** [comment]
看了下源码，发现要 `add_packages("libsdl", {interface = true})` 或者 `public = true` 才会打包

**Comment by vkensou** [comment]
> 看了下源码，发现要 `add_packages("libsdl", {interface = true})` 或者 `public = true` 才会打包

感谢帮忙。我试了可以。这个感觉有点隐晦，也没有文档说明。不知这么做是为了满足什么需求。

**Comment by waruqi** [comment]
试试这个 patch https://github.com/xmake-io/xmake/pull/5706

**Comment by star-hengxing** [comment]
> 试试这个 patch #5706

我这里测试没问题。

有一个疑问，安装 static target 不需要拷贝 package 的 dll/lib 吗

**Comment by waruqi** [comment]
> > 试试这个 patch #5706
> 
> 我这里测试没问题。
> 
> 有一个疑问，安装 static target 不需要拷贝 package 的 dll/lib 吗

shared/binary 依赖的 可以根据 rpath 什么的自动 strip 。。静态库也要装的话，那可能会安装一坨的 so/dll，大多数时候还不一定会用到，暂时不搞了。等后面有问题再说。
