### ISSUE TITLE
ldflags `/INCLUDE:?warp_size@cuda@at@@YAHXZ` can not be added directly

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#5694]
### Xmake 版本

2.9.5

### 操作系统版本和架构

Windows 11

### 描述问题

windows上加上述ldflags的时候会被xmake忽略，必须使用{force = true}才能加上；然而-v里显示xmake并未去检测这个flag，直接就忽略了，这个行为不对

### 期待的结果

不使用{force = true}也能正常为msvc添加ldflags

### 工程配置

```lua
set_project("toytrain")
set_languages("cxxlatest")

add_rules("mode.debug", "mode.release")
set_runtimes("MD")

add_requires("cmake::Torch", {system = true, configs = {envs = {CMAKE_PREFIX_PATH = "C:\\Users\\xq114\\Downloads\\libtorch"},
                                                        presets = {CMAKE_BUILD_TYPE = "Release"}}})

target("toytrain")
    set_kind("binary")
    add_packages("cmake::Torch")
	add_files("src/main.cpp")
    add_ldflags("/INCLUDE:?warp_size@cuda@at@@YAHXZ", {force = true})


```

### 附加信息和错误日志

https://github.com/xmake-io/xmake/discussions/5674

**Comment by waruqi** [comment]
```console
$ xmake -v
checking for flags (/INCLUDE:?warp_size@cuda@at@@YAHXZ) ... no

warning: add_ldflags("/INCLUDE:?warp_size@cuda@at@@YAHXZ") is ignored, please pass `{force = true}` or call `set_policy("check.auto_ignore_flags", false)` if you want to set it.
```

这不是检测了的么，不检测，不会去忽略。。

除非是上次已经检测过，有缓存了。`xmake f -c` 加 -c 重新触发下就行了。。没啥问题

**Comment by xq114** [comment]
![image](https://github.com/user-attachments/assets/b1cacea6-3a0f-423f-84d5-5366bb8c13a9)

我这不行，没看到检测，而且即使有检测，检测会不通过也很奇怪

**Comment by xq114** [comment]
![image](https://github.com/user-attachments/assets/0df8b14d-5e06-4c8c-85c1-9203abf5f531)

detect cache也没有

**Comment by waruqi** [comment]
> 我这不行，没看到检测，而且即使有检测，检测会不通过也很奇怪

你加的是 ldflags，只有在实际 link 时候，用到了，才会延迟检测。。你这 编译 main.cpp 就报错中断了，都还没走到  link 。。当然不会检测了。。
