### ISSUE TITLE
请问如何实现自己开发解析Kconfiglib输出的.config文件，文件解析部分已经编写测试，但是没有找到在xmake中不依赖target就可以注入解析好的map到内置环境中

### ISSUE THREAD

**Issue by juiceRv** [xmake-io/xmake#5704]
### Xmake 版本

2.5.9

### 操作系统版本和架构

window

### 描述问题

请问如何实现自己开发解析Kconfiglib输出的.config文件，文件解析部分已经编写测试，但是没有找到在xmake中不依赖target就可以注入解析好的map到内置环境中，因为我的工程是多层目录的，需要include多个xmake.lua，我只希望在顶层xmake.lua中进行.config解析后，下层的无论哪一个target都可以获取到这个解析后的map变量。

### 期待的结果

谢谢作者的贡献

### 工程配置

谢谢作者的贡献

### 附加信息和错误日志

谢谢作者的贡献

**Comment by waruqi** [comment]
跟 includes 无关，写个 rule，在 on_load/on_config 里面解析加载，然后全局顶层 add_rules 对所有 target 生效。。每个 target 都能获取到。。。

**Comment by juiceRv** [comment]
好的，感谢大佬

**Comment by juiceRv** [comment]
我希望注入一个变量可以让所有xmake.lua都可以直接使用，请问我应该使用哪一个方式才符合官方的设计？

**Comment by waruqi** [comment]
set_values + target:values()

**Comment by juiceRv** [comment]
在rule中无法set_values，我用memcache.set("xxx", "xxx", xxx)解决了，谢谢您的帮助。
