### ISSUE TITLE
xmake cache 未生效

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#5712]
### Xmake 版本

v2.9.2

### 操作系统版本和架构

Linux 720ce3a659a2 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

无论是通过 xmake f --ccachedir=$HOME/.xmake/ccache 还是用 xmake remote cache：
```bash
xmake service --ccache --start
xmake service --connect --ccache
```
从日志和缓存目录里都看不到任何缓存，在什么情况下是会关闭 cache 行为的？

### 期待的结果

怀疑是一些环境变量检测没通过导致 cache 行为失败。

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
xmake f/g --ccache=n 和 set_policy("build.ccache", false) 会禁用，win 下 msvc 会默认禁用。。其他情况都开启的。

**Comment by waruqi** [comment]
obj file 读写走的 hash，只要代码不同，不冲突，就安全，但如果完全相同的代码 完全相同的编译 flags，正好同一时间编译缓存，有可能不安全，但概率极低。。

**Comment by waruqi** [comment]
```console
ruki-2:test ruki$ xmake f --ccachedir=/tmp/ccache
checking for platform ... macosx
checking for architecture ... x86_64
checking for Xcode directory ... /Applications/Xcode.app
checking for Codesign Identity of Xcode ... Apple Development: waruqi@gmail.com (T3NA4MRVPU)
checking for SDK version of Xcode for macosx (x86_64) ... 14.0
checking for Minimal target version of Xcode for macosx (x86_64) ... 14.0
ruki-2:test ruki$ xmake -r
[ 50%]: cache compiling.release src/main.cpp
[ 75%]: linking.release test
[100%]: build ok, spent 1.876s
ruki-2:test ruki$ tree /tmp/ccache/
/tmp/ccache/
└── 00
    └── 00a7fe634a91df3f6b4515abb466badc

1 directory, 1 file
ruki-2:test ruki$ ls -l /tmp/ccache/00/
total 8
-rw-r--r--  1 ruki  wheel  3608 10 14 22:50 00a7fe634a91df3f6b4515abb466badc
```

这边测试可以的么，没啥问题

**Comment by TOMO-CAT** [comment]
能看到 remote cache 设置成功了，但是从日志上看不出来 remote cache 是否启用了：
![image](https://github.com/user-attachments/assets/02d70b9f-6d20-416e-b1c1-9f37fcffaf2a)

![image](https://github.com/user-attachments/assets/2a683ac1-10b1-4081-a04b-0f6a9bbb3bd6)
本地是可以看到有很多 remote_cache 的日志，而且会显示 cache 命令：
![image](https://github.com/user-attachments/assets/43b1cf28-634c-4560-aa7e-85b83be3ca71)

**Comment by TOMO-CAT** [comment]
> 这边测试可以的么，没啥问题

这个我本地也是可以设置 ccachedir 的，一样的镜像，不清楚线上机器为什么一直没生效。我先把线上的 jenkins 流水线简化一下看看。

**Comment by waruqi** [comment]
> 本地是可以看到有很多 remote_cache 的日志，而且会显示 cache 命令：

那不就是生效了么。

**Comment by TOMO-CAT** [comment]
> 那不就是生效了么。

本地都能用，但是无论是 xmake f --ccachedir 还是 xmake service --ccache 在线上机器都没任何作用。

我用 xmake g -c 清理了全局配置还是没生效：
![image](https://github.com/user-attachments/assets/e6480b62-67d3-4a58-991a-2dac121ca01b)

什么情况下会没有 cache compiling 的输出呢？
![image](https://github.com/user-attachments/assets/dcf2b9de-6843-46db-9d75-b42e723ede69)

**Comment by TOMO-CAT** [comment]
我找运维登上 ci 的机器后 手动编译也是能正常走到 cache 的：
![6eef04f5c9295690eb3c61c90e0910b7](https://github.com/user-attachments/assets/4efe4f4e-9299-4358-9553-dcc566dd2f01)

我现在怀疑是因为编译时 cache 没生效导致的，但是 xmake g -c 后还是没 cache：
![image](https://github.com/user-attachments/assets/7c7ac8a5-074c-440c-b33c-e299600b6116)

或者能指一下这个 `cache compiling` 在源码哪个位置呢，按照字符串搜索返回结果太多了，我可以自己看下对应的源码。

**Comment by TOMO-CAT** [comment]
![image](https://github.com/user-attachments/assets/a53bf87e-7c7c-4268-9c0a-fb366b0d4d99)
ci 流水线打印出来 xmake f -v 的数据了，没发现和本地有什么异常，环境变量也清空了。

**Comment by TOMO-CAT** [comment]
排查的时候发现另一个问题，proto.cc 是不是没有缓存，build 文件夹下面的 cache 很少。
![image](https://github.com/user-attachments/assets/e6833e97-032a-47f0-bcbc-07b8120e0fdd)

**Comment by TOMO-CAT** [comment]
![image](https://github.com/user-attachments/assets/33c0ad42-c715-4315-8609-3d39163007f9)
好像是 xmake 主动关的

**Comment by waruqi** [comment]
> > 这边测试可以的么，没啥问题
> 
> 这个我本地也是可以设置 ccachedir 的，一样的镜像，不清楚线上机器为什么一直没生效。我先把线上的 jenkins 流水线简化一下看看。

只要是 client 端 logs 里看到拉取 remote cache ，那就是生效了。。

remote cache 在 server 端，不使用 ccachedir ，那个是给本地项目缓存配置的。。

server 端，目前全部存在 `~/.xmake/service/server/remote_cache/sessions/<id>` 里面

然后参考这个固定下 session id

https://github.com/xmake-io/xmake/discussions/4524#discussioncomment-7924722

**Comment by waruqi** [comment]
> ![image](https://private-user-images.githubusercontent.com/47598093/376864915-a53bf87e-7c7c-4268-9c0a-fb366b0d4d99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDg5NzUsIm5iZiI6MTcyOTA0ODY3NSwicGF0aCI6Ii80NzU5ODA5My8zNzY4NjQ5MTUtYTUzYmY4N2UtN2M3Yy00MjY4LTljMGEtZmIzNjZiMGQ0ZDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDAzMTc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiYWI4YzYxYTljYzkzODlhNjMwMzk3OGUwZjMzMWQ5NmRhNzZhZjcwZWE0NWZiMWViOTkyZTVmYzI3YTNlYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W0q-wbGh4aTTZ4j27fbG3-jFUT2CbPPY8P96oWdrstQ) ci 流水线打印出来 xmake f -v 的数据了，没发现和本地有什么异常，环境变量也清空了。

不要看 进度信息，rules 里面的 log 不会显示 ccache 状态，只有内置的 target c/c++ files 编译 log 才会显示 ccache 状态

**Comment by TOMO-CAT** [comment]
> 不要看 进度信息，rules 里面的 log 不会显示 ccache 状态，只有内置的 target c/c++ files 编译 log 才会显示 ccache 状态

设置 ccachedir 的时候我看的是 ~/.xmake/ccache 目录里一直是空的，例外使用 xmake service remote cache 的时候我查看的是服务端 ~/.xmake/service/server/logs.txt 也是空的。

最后发现是 xmake 源码里检测到 ci 环境就把  ccache 关了，我把环境变量改回来就能解决这个问题。另外跨机 remote cache 很容易超时，所以我现在用的是设置全局的 ccachedir 方便多个项目共享 cache。

现在只剩下一个问题就是 proto 生成的 cc 文件好像是不 cache 的？

![image](https://github.com/user-attachments/assets/b23e83d5-f17c-4cad-86ab-e4984d36fae9)

**Comment by waruqi** [comment]
上面说了，只是自定义 rule 的 log 里面没显示 ccache 字样而已。

你自己调下 https://github.com/xmake-io/xmake/blob/cd6663abb6da35cb798004f19b1d106f3cc73f50/xmake/modules/core/tools/gcc.lua#L805

**Comment by waruqi** [comment]
有没有启用 cache ，你调下上面的 地方就知道了。。反正 log 里，只有原生 c/c++ target code 会打
