### ISSUE TITLE
`xmake build <target>` support link only

### ISSUE THREAD

**Issue by star-hengxing** [xmake-io/xmake#5716]
### Is your feature request related to a problem? Please describe.

```lua
xmake build <target> --files=xxx.cpp
xmake build <target> --linkonly
```

It skip other files mtime check. This is useful in debugging large projects.

### Describe the solution you'd like

N/A

**Comment by waruqi** [comment]
直接 rm targetfile 也就一两行的事情

```console
ruki-2:test ruki$ rm build/macosx/x86_64/release/test ; xmake
[ 75%]: linking.release test
[100%]: build ok, spent 0.533s
```

**Comment by star-hengxing** [comment]
不过我认为直接内置到构建系统里比较好，比如 msbuild 就支持

**Comment by waruqi** [comment]
试试 https://github.com/xmake-io/xmake/pull/5725
