### ISSUE TITLE
os.dirs能像add_includedirs那样支持$(xxx)变量

### ISSUE THREAD

**Issue by ZZH-Finalize** [xmake-io/xmake#5726]
### 你在什么场景下需要该功能？

根据option的配置不同递归添加include路径时

### 描述可能的解决方案

add_includedirs可以使用$开头的变量来控制添加的路径, 但os.dirs并不能这样做, 只能手动调用get_config之后再进行字符串拼接, 例如

```lua
add_includedirs('src/main/$(arch)')
add_includedirs(os.dirs(string.format('src/main/%s/**', get_config('arch'))))
```

如果能够让add_includedirs支持通配符或os.dirs支持变量的话, 那么就可以简化为
`add_includedirs('src/main/$(arch)/**')` 或 `add_includedirs(os.dirs('src/main/$(arch)/**'))`

**Comment by waruqi** [comment]
不考虑，原本 add_includedirs + os.dirs 就是不推荐用法，很容易引入脏目录，干扰 search
