### ISSUE TITLE
Simplifying boolean value configs

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#5727]
### 你在什么场景下需要该功能？

对于有很多组件/设置的包，一个个指定比较繁琐
```
add_requires("boost >=1.78.0", {configs = {iostreams = true, system = true, thread = true}})
```

### 描述可能的解决方案

https://github.com/xmake-io/xmake/issues/5527

希望3.0中可以简化设置，支持
```lua
add_requires("boost[iostreams,system,thread] >=1.78.0")
```
等价于在原有configs后追加`iostreams = true, system = true, thread = true`

### 描述你认为的候选方案

```lua
add_requires("boost >=1.78.0", {configs = ["iostreams", "system", "thread"])
```
若传入list则认为是config名称；这种做法灵活性比上一种差，但对现有语法变动小

**Comment by star-hengxing** [comment]
https://github.com/xmake-io/xmake-repo/blob/a3db9799031f80657356df314cd261838f341ad3/packages/t/thorvg/xmake.lua#L19-L23

```lua
add_requires("thorvg", {configs = {
    loaders = {"svg", "png"},
    tools = {"svg2png"}
}})
```

**Comment by xq114** [comment]
> [xmake-io/xmake-repo@`a3db979`/packages/t/thorvg/xmake.lua#L19-L23](https://github.com/xmake-io/xmake-repo/blob/a3db9799031f80657356df314cd261838f341ad3/packages/t/thorvg/xmake.lua#L19-L23)
> 
> ```lua
> add_requires("thorvg", {configs = {
>     loaders = {"svg", "png"},
>     tools = {"svg2png"}
> }})
> ```

这么写就更复杂了，尤其是90%的情况只需要一个配置xxx=true

**Comment by xq114** [comment]
> [xmake-io/xmake-repo@`a3db979`/packages/t/thorvg/xmake.lua#L19-L23](https://github.com/xmake-io/xmake-repo/blob/a3db9799031f80657356df314cd261838f341ad3/packages/t/thorvg/xmake.lua#L19-L23)
> 
> ```lua
> add_requires("thorvg", {configs = {
>     loaders = {"svg", "png"},
>     tools = {"svg2png"}
> }})
> ```

这么写就更复杂了，尤其是90%的情况只需要一个配置xxx=true

**Comment by waruqi** [comment]
可以考虑 ，还可以带上string值。复杂的，array values 这种，就用 configs = {} 配。

```lua
add_requires("boost[iostreams,system,thread,key=value] >=1.78.0")
```

```console
xrepo install boost[iostreams,system,thread,key=value]
```

**Comment by waruqi** [comment]
这个实现比较简单，并且没啥副作用，可以提前进去，试试这个 patch https://github.com/xmake-io/xmake/pull/5736

**Comment by waruqi** [comment]
改进了下，还能支持 array values

```console
 xrepo install ffmpeg[shared,debug,codecs=[foo,bar,zoo]]
```

**Comment by xflcx1991** [comment]
反对一个功能有多种写法，这会给以后交流学习，教程编写带来分歧，会进一步误导新手。

add_requires("boost >=1.78.0", {configs = {iostreams = true, system = true, thread = true}})

复制不就行了，难道真手敲？

**Comment by waruqi** [comment]
目前限制仅对 xmake 包生效，三方包不启用，因为 vcpkg::boost[core] 等三方包有自己的包名格式，会冲突

**Comment by heheda123123** [comment]
> 反对一个功能有多种写法，这会给以后交流学习，教程编写带来分歧，会进一步误导新手。
> 
> add_requires("boost >=1.78.0", {configs = {iostreams = true, system = true, thread = true}})
> 
> 复制不就行了，难道真手敲？

都写c++了，一种功能多种写法应该习惯了，自己选择吧
