### ISSUE TITLE
xmake 编译 cpu 利用率低

### ISSUE THREAD

**Issue by TOMO-CAT** [xmake-io/xmake#5729]
### Xmake 版本

v2.9.2

### 操作系统版本和架构

Linux 720ce3a659a2 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

项目中有数百个 cc 文件，从实际的编译体验上看如果有很多 cc 文件编译时间较长（1 分钟以上），很容易出现 cpu 轮空的情况导致实际 cpu 利用率低。

举个可能不恰当的例子，n 核假设一个批次是 n 个 cc 文件的编译，经常看到只剩下一两个核在跑，标准输出也停住。相同的项目反复测试后 bazel 编译时长 4 分钟，xmake 需要跑到 7 分钟以上。

### 期待的结果

提高 cpu 利用率缩短编译时间。

### 工程配置

无

### 附加信息和错误日志

无

**Comment by TOMO-CAT** [comment]
> 给个可以复现的 project 或 case ，否则没法调

这去哪里找一个这么大的项目。。你们手头上没有合适的项目测试下吗

**Comment by TOMO-CAT** [comment]
bazel 能做到如果核数是 8，时刻有 8 个任务把核吃满，即使有个任务需要时间比较久
![image](https://github.com/user-attachments/assets/c1775d02-8357-4b86-ba71-ed9a01b7a90d)

**Comment by TOMO-CAT** [comment]
测试了一下发现应该是 set_policy("build.across_targets_in_parallel", true) 没有真正实现跨 target 并发导致 target 很多的时候 cpu 没跑满，我看能不能写一个 demo 吧。

**Comment by waruqi** [comment]
这边目前没遇到问题，不同项目不同的 case ，用的 rules 不同，都会有不同的行为表现。有些特殊 rule 可能会干扰并行，这个就要具体问题具体分析了，没法复现我不好调

**Comment by TOMO-CAT** [comment]
> 这边目前没遇到问题，不同项目不同的 case ，用的 rules 不同，都会有不同的行为表现。有些特殊 rule 可能会干扰并行，这个就要具体问题具体分析了，没法复现我不好调

写了一个 demo，用的最新版本的 xmake，从我测试结果来看就是简单的跨 target 并行失效了。https://github.com/TOMO-CAT/xmake-template/tree/main/cpu_usage

**Comment by TOMO-CAT** [comment]
测试了一下应该是 object target 才有的问题，如果把 target 换成 static 类型就没这个问题，这个能修吗？
![image](https://github.com/user-attachments/assets/8e501d97-29b4-4868-95fc-cc81128a4a5e)

**Comment by waruqi** [comment]
object kind 暂时还不支持，等后面有空再看看吧。。

**Comment by TOMO-CAT** [comment]
> object kind 暂时还不支持，等后面有空再看看吧。。

有预期时间吗，这个影响还挺大的，开了 target 并行 3 分钟，不开编译要 7 分钟

**Comment by waruqi** [comment]
没有

**Comment by waruqi** [comment]
再试下，应该可以了。。https://github.com/xmake-io/xmake/pull/5759

```console
xmake update -s github:xmake-io/xmake#object
```
