### ISSUE TITLE
xmake f -m debug -a x86 出现错误

### ISSUE THREAD

**Issue by ranwei1025** [xmake-io/xmake#573]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题
 xmake f -m debug -a x86 -D -v
error: @programdir\core\project\cache.lua:118: save D:\test\.xmake\windows\x64\cache/config failed, cannot serialize: not enough memory!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:762]: in function 'raise'
    [@programdir\core\project\cache.lua:118]: in function 'flush'
    [@programdir\actions\config\main.lua:301]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:508]: in function 'run'
    [@programdir\core\main.lua:236]:

请尽量清晰精准地描述你碰到的问题。

之前都是好的 后面升级了xmake出现了这个问题

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 错误信息

如果可能，请尽量附加程序运行过程中的错误输出信息。

> 如果是xmake相关编译问题，请加上`-v -D`参数运行，并给出详细编译输出信息。

### 相关环境
windows 平台
xmake v2.2.8+201908261502, A cross-platform build utility based on Lua

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by waruqi** [comment]
见：https://github.com/xmake-io/xmake/issues/567  更新到master/dev就行了
