### ISSUE TITLE
Xmake是否支持在plat=windows的情况下，自定义msvc的编译链

### ISSUE THREAD

**Issue by Zcaic** [xmake-io/xmake#5732]
### Xmake Version

2.9.5

### Operating System Version and Architecture

Windows10

### Describe Bug

我电脑由于不能联网，所以安装的是便携版的msvc，并设置好相应的`PATH`、`INLCUDE`、`LIB``环境变量，用cmake是能够正确识别和编译的，但是用xmake的时候，发现会提示找不到vs。

### Expected Behavior

无

### Project Configuration

无

### Additional Information and Error Logs

无

**Comment by waruqi** [comment]
这边支持 vcvarsall.bat 的探测和加载，以及支持 vs prompt cmd 环境。。其他的环境不支持

**Comment by waruqi** [comment]
跟 msbuild 有啥关系，xmake 直接调用的编译器。

环境加载依赖 vcallvars.bat 你可以自己看下源码

https://github.com/xmake-io/xmake/blob/dev/xmake/modules/detect/sdks/find_vstudio.lua

**Comment by waruqi** [comment]
我没用过便携版的msvc，可以提供下 安装包，或者直接提 pr 到 xmake-repo 收录进来。后面倒是可以考虑整合进来

**Comment by Zcaic** [comment]
好的嘞，大佬，这是便携版MSVC的下载开源工具，https://github.com/Data-Oriented-House/PortableBuildTools

**Comment by waruqi** [comment]
现在支持了 可以试下： https://github.com/xmake-io/xmake/issues/5848

**Comment by Zcaic** [comment]
强啊大佬，我晚上回去就去试试
