### ISSUE TITLE
xmake and mingw strange behaviour 

### ISSUE THREAD

**Issue by zelid** [xmake-io/xmake#574]
I started adding mingw support to packages repository.

My first package is `xz` which uses `autotools`,
xmake.lua:
```
package("xz")

    set_homepage("https://tukaani.org/xz/")
    set_description("General-purpose data compression with high compression ratio.")

    set_urls("https://downloads.sourceforge.net/project/lzmautils/xz-$(version).tar.gz",
             "https://tukaani.org/xz/xz-$(version).tar.gz")
    add_versions("5.2.4", "b512f3b726d3b37b6dc4c8570e137b9311e7552e8ccbab4d39d47ce5f4177145")

    on_install("mingw@linux,macosx", function (package)
        local configs = {"--disable-shared", "--enable-static",  "--with-gnu-ld=yes"}
        -- table.insert(configs, "--host=i686-w64-mingw32")
        import("package.tools.autoconf").configure(package, configs)
        os.vrun("make  -j36")
    end)

    on_test(function (package)
        os.vrun("xz --version")
        assert(package:has_cfuncs("lzma_code", {includes = "lzma.h"}))
    end)
```

To test my local package installation I use simple project with xmake.lua:
```
add_repositories("my-repo repo")
add_requires("xz", {system = false})
target("hello")
    add_packages("xz")
    set_kind("binary")
    add_files("src/*.cpp") 
```

To verify `xz` package I run:
`xmake f -p mingw -a i386 -v -y`
inside my `hello` demo project.

The build of `xz` with mingw as `xmake` package always fails :(
Seems to be an issue with `xmake` hidden environment variables and `autoconf`.
The error happens on linker stage. Somehow when configured with `xmake` autoconf thinks we link library as MSVC and not with MinGW.

When I extract `xz` and configure it manually for MinGW cross-compilation:
`export arch=i686-w64-mingw32 `
`./configure --host=${arch} --prefix=/tmp/${arch} --disable-shared --enable-static`
 then builds and links fine.

Here are 2 `config.log` results of `xmake` and `'direct'` configurations to see the difference:
[`./configure --host=${arch} --prefix=/tmp/${arch} --disable-shared --enable-static`](https://gist.github.com/zelid/3bd456c7f54ff96c2af4304694e9d8b6)
and 
[`xmake f -p mingw -a i386 -v -y`](https://gist.github.com/zelid/e6515d3fe90fb95b66765b6bf95382ba)

Why build with `xmake` failed and `'direct'` build with the same configure parameters succeed?

**Comment by zelid** [comment]
Basically for `xz` package:

This works fine (configure and make):
export arch=i686-w64-mingw32
./configure --host=${arch} --prefix=/tmp/${arch} --disable-shared --enable-static

And this does not work because configure result is different from above: 
on_install("mingw@linux,macosx", function (package)
        local configs = {"--disable-shared", "--enable-static"}
        os.vrun("make  -j4")
    end)

You can see the difference between this two configure results: https://gist.github.com/zelid/3bd456c7f54ff96c2af4304694e9d8b6
and 
https://gist.github.com/zelid/e6515d3fe90fb95b66765b6bf95382ba

**Comment by waruqi** [comment]
This seems to be a problem with ./configure, we can't pass i686-w64-mingw32-g++ as a linker for mingw to ./configure

xmake will pass all toolchains configuration to configure instead of setting `--host=arch`. for example:

```console
{ 
  CC = "/usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-gcc",
  AR = "/usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-ar",
  LDFLAGS = "-m64",
  arch = "x86_64-w64-mingw32",
  PKG_CONFIG_PATH = "",
  ARFLAGS = "",
  CPP = "/usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-gcc -E",
  CFLAGS = "-m64",
  SHFLAGS = "-m64",
  ACLOCAL_PATH = "",
  LD = "/usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-g++",
  CXXFLAGS = "-m64",
  ASFLAGS = "-m64",
  AS = "/usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-gcc",
  RANLIB = "/usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-ranlib",
  LDSHARED = "/usr/local/opt/mingw-w64/bin/x86_64-w64-mingw32-g++" 
}

./configure --disable-dependency-tracking --disable-silent-rules --enable-shared=no --prefix=/Users/ruki/.xmake/packages/x/xz/5.2.4/06887ad44515c1a2eae5ce16affc7df1 --host=x86_64-w64-mingw32
```

See https://github.com/xmake-io/xmake/blob/56021b09ccfadde89756298c7d9afd688c896d21/xmake/modules/package/tools/autoconf.lua#L81-L95

And I have fixed this problem with this patch. (We pass i686-w64-mingw32-ld as mingw linker instead of i686-w64-mingw32-g++ when runing ./configure)

https://github.com/xmake-io/xmake/blob/56021b09ccfadde89756298c7d9afd688c896d21/xmake/modules/package/tools/autoconf.lua#L96-L109

You can update the dev branch scripts and try it again. `xmake update -s dev`

BTW, I have improved xmake-repo/xz/xmake.lua in dev branch. You can pull this package from dev branch.

```lua
add_repositories("xmake-repo-dev https://github.com/xmake-io/xmake-repo.git dev")
```

If the test passed, I will update to the master branch later.

**Comment by zelid** [comment]
Great, I'll try in few hours. I really like xmake because it's simple, fast and has good IDE integrations.
I'm going to port around 30-40 packages to mingw for start.

How do you usually debug .lua scripts like
`xmake/xmake/modules/package/tools/autoconf.lua` and  `xz/xmake.lua`?

**Comment by waruqi** [comment]
You can see https://xmake.io/#/package/remote_package?id=local-test to test xmake-repo packages fastly.

And you can clone xmake source codes to compile and debug it.

```console
# compile and load local xmake source environment
cd xmake-source
make build
source scripts/srcenv.profile
xmake --version

# now you can edit and debug xmake-source/xxx.lua scripts

# debug packages
cd xmake-repo
xmake l scripts/test -v -D --shallow xz
```

Or we can also build and install source scripts

```console
# compile and install local xmake source environment
cd xmake-source
make build
./scripts/get.sh __local__ __install_ony__

# edit and debug lua scripts
# and reinstall it
./scripts/get.sh __local__ __install_ony__``
