### ISSUE TITLE
依赖解析速度是不是有点慢啊  

### ISSUE THREAD

**Issue by Super1Windcloud** [xmake-io/xmake#5751]
### Is your feature request related to a problem? Please describe.

简单添加个 yyjson `  xmake require -y yyjson ` 就等了一分多钟,   拉取源代码文件也就几秒钟 ,  

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

**Comment by star-hengxing** [comment]
添加 -v 参数看一下 log，大概率卡在下载了
