### ISSUE TITLE
添加依赖配置确实比 CMake  和meson要好多了  ,  

### ISSUE THREAD

**Issue by Super1Windcloud** [xmake-io/xmake#5753]
### Is your feature request related to a problem? Please describe.

 # CMake 添加依赖
```  
FetchContent_Declare(
        fmt
        GIT_REPOSITORY https://github.com/fmtlib/fmt
        GIT_TAG        master
)

FetchContent_MakeAvailable(fmt) 
``` 

### Describe the solution you'd like

#  meson 添加依赖 
```  
mkdir  subprojects  
meson  wrap    install fmt  
接在meson.build  添加
fmt_lib = dependency('fmt' ) 
executable('meson_demo',
           'main.cpp' ,
           dependencies : [fmt_lib],
          )
```  

### Describe alternatives you've considered

#  对比xmake只需要

```  
add_requires("fmt")
target("xmake_demo")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("fmt") 
xmake  &&  xmake run 即可  
``` 

### Additional context

# 但是这里希望 ,xmake能够实现自动同步依赖配置的功能  
 ##  *比如 , 添加功能当` xmake require    --add    fmt`  时能够自动 更新xmake.lua文件而无需手动处理xmake.lua*

**Comment by waruqi** [comment]
不考虑，直接编辑 xmake.lua 也就两行代码的事情。
