### ISSUE TITLE
生成makefile不正确

### ISSUE THREAD

**Issue by sxpc722** [xmake-io/xmake#577]
### 描述问题

生成的makefile不完整，并且target 中设置add_tools("cc", "clang")不起作用。

#### xmake.lua:
set_project("testM")
set_version("1.5.1", {build = "%Y%m%d%H%M"})

add_rules("mode.debug", "mode.release")

target("testM")
    set_kind("binary")
    add_files("src/*.c")
    add_vectorexts("avx2")
    add_tools("ld","clang")
    add_tools("cc","clang")

#### 生成的makefile （xmake project -k makefile -v）
CCACHE=ccache
MXX=/usr/bin/clang
CU=/usr/bin/clang++
CC=/usr/bin/gcc
CXX=/usr/bin/gcc
AS=/usr/bin/gcc
MM=/usr/bin/clang

SH=/usr/bin/g++
LD=/usr/bin/g++
AR=/usr/bin/ar

testM_CC=-fvisibility=hidden -O3 -mavx2 -Qunused-arguments -m64 -I/usr/local/include -I/usr/include
testM_LD=-s -fvisibility=hidden -m64 -L/usr/local/lib -L/usr/lib

default:  testM

all:  testM

.PHONY: default all  testM

testM: build/linux/x86_64/release/testM
build/linux/x86_64/release/testM: build/.objs/testM/linux/x86_64/release/src/main.c.o
        @echo linking.release testM
        @mkdir -p build/linux/x86_64/release
        @$(LD) -o build/linux/x86_64/release/testM build/.objs/testM/linux/x86_64/release/src/main.c.o $(testM_LD) > build/.build.log 2>&1

build/.objs/testM/linux/x86_64/release/src/main.c.o: src/main.c
        @echo compiling.release src/main.c
        @mkdir -p build/.objs/testM/linux/x86_64/release/src
        @$(CC) -c $(testM_CC) -o build/.objs/testM/linux/x86_64/release/src/main.c.o src/main.c > build/.build.log 2>&1

clean:  clean_testM

clean_testM: 

### 期待的结果

1. clean_testM 目标
2. clang

### 错误信息

configure
{
    arch = x86_64
    ccache = true
    mode = release
    ndk_stdcxx = true
    plat = linux
    kind = static
    buildir = build
    clean = true
    host = linux
}
checking for the clang ... /usr/bin/clang
checking for the objc++ compiler (mxx) ... clang
checking for the rustc ... no
checking for the rust compiler (rc: rustc) ... no
checking for the nvcc ... no
checking for the Cuda SDK directory ... no
checking for the cuda compiler (cu: nvcc) ... no
checking for the clang++ ... /usr/bin/clang++
checking for the cuda compiler (cu) ... clang++
checking for the gcc ... /usr/bin/gcc
checking for the c compiler (cc) ... gcc
checking for the c++ compiler (cxx) ... gcc
checking for the dmd ... no
checking for the dlang compiler (dc: dmd) ... no
checking for the ldc2 ... no
checking for the dlang compiler (dc: ldc2) ... no
checking for the gdc ... no
checking for the dlang compiler (dc: gdc) ... no
checking for the go ... no
checking for the golang compiler (gc: go) ... no
checking for the gccgo ... no
checking for the golang compiler (gc: gccgo) ... no
checking for the assember (as) ... gcc
checking for the objc compiler (mm) ... clang
checking for the Cuda SDK directory ... no
checking for the cuda linker (cu-ld: nvcc) ... no
checking for the g++ ... /usr/bin/g++
checking for the shared library linker (sh) ... g++
checking for the rust shared library linker (rc-sh: rustc) ... no
checking for the dlang shared library linker (dc-sh: dmd) ... no
checking for the dlang shared library linker (dc-sh: ldc2) ... no
checking for the dlang shared library linker (dc-sh: gdc) ... no
checking for the linker (ld) ... g++
checking for the rust linker (rc-ld: rustc) ... no
checking for the dlang linker (dc-ld: dmd) ... no
checking for the dlang linker (dc-ld: ldc2) ... no
checking for the dlang linker (dc-ld: gdc) ... no
checking for the golang linker (gc-ld: go) ... no
checking for the golang linker (gc-ld: gccgo) ... no
checking for the ccache ... no
checking for the ar ... /usr/bin/ar
checking for the static library archiver (ar) ... ar
checking for the rust static library archiver (rc-ar: rustc) ... no
checking for the dlang static library archiver (dc-ar: dmd) ... no
checking for the dlang static library archiver (dc-ar: ldc2) ... no
checking for the dlang static library archiver (dc-ar: gdc) ... no
checking for the golang static library archiver (gc-ar: go) ... no
checking for the golang static library archiver (gc-ar: gccgo) ... no
checking for the flags (-O3) ... ok
checking for the flags (-mavx2) ... ok
create ok!

### 相关环境
xmake v2.2.8+201908261455
OS: ubuntu 19.04

**Comment by waruqi** [comment]
目前makefile的生成不是很完善的，建议还是直接调用xmake命令来编译，毕竟xmake重点还是在直接构建上。

而关于你说的makefile上的一些问题，我回头有时间看下，会做一些改进支持。

**Comment by waruqi** [comment]
add_tools 的问题我修复了。你可以更新到 dev 再试试 xmake update -s dev

clean 我看了下，正常没看出啥问题，能够正常clean target files

**Comment by waruqi** [comment]
我新增了 `xmake project -k xmakefile` 去生成带有xmake的makefile ，你也可以试试
