### ISSUE TITLE
vscode xmake插件 add_ldflags("-mcpu=cortex-m3 -mthumb") 出现警告

### ISSUE THREAD

**Issue by cc-cao** [xmake-io/xmake#5770]
### Xmake 版本

v2.9.5+20240914

### 操作系统版本和架构

windows 11, macOS 15.1

### 描述问题

![image](https://github.com/user-attachments/assets/423dbfe7-64b2-4f07-8201-27215cf79298)

### 期待的结果

不要出现警告，尽管我可以用 force=true 忽略

### 工程配置

set_xmakever('2.9.5')
set_project('A2Plus')

add_rules("mode.debug", "mode.release")

-- 设置默认的平台架构
set_defaultplat('cross')
set_defaultarchs('cortex-m3')
set_defaultmode('debug')

-- 定义工具链
if is_host("windows") then
    local TOOLCHAIN = "C:/Users/blade/work/compiler/gcc-arm-none-eabi-10.3-2021.10"
elseif is_host("macosx") then
    local TOOLCHAIN = "/Applications/ArmGNUToolchain/13.3.rel1/arm-none-eabi"
end

toolchain("gcc-arm-none-eabi")
    set_kind("standalone")
    set_sdkdir(TOOLCHAIN)
toolchain_end()

target("A2Plus.elf")
    -- 设置工具链
    set_toolchains("gcc-arm-none-eabi")
    set_targetdir("build")

    set_languages("c11", "c++17")

    if is_mode("debug") then
        add_defines("DEBUG")
        set_optimize("none")
    elseif is_mode("release") then
        set_optimize("fastest")
    end

    add_defines("USE_HAL_DRIVER", "STM32F103xE")

    add_cxflags(
        "-mcpu=cortex-m3 -mthumb",
        "-fdata-sections -ffunction-sections",
        "-Wall"
    )

    add_asflags(
        "-mcpu=cortex-m3 -mthumb",
        "-fdata-sections -ffunction-sections",
        "-x assembler-with-cpp"
    )

    add_ldflags(
        "-mcpu=cortex-m3 -mthumb",
        "-specs=nano.specs",
        "-T./src/system/STM32F103VETx_FLASH.ld",
        "-lc -lm -lnosys",
        "-Wl,--gc-sections"
        -- {force = true}
    )

    add_includedirs(
        "drivers/CMSIS/Include",
        "drivers/CMSIS/Device/ST/STM32F1xx/Include",
        "drivers/STM32F1xx_HAL_Driver/Inc/Legacy",
        "drivers/STM32F1xx_HAL_Driver/Inc",
        "middlewares/FreeRTOS/Source/include",
        "middlewares/FreeRTOS/Source/portable/GCC/ARM_CM3",
        "middlewares/FreeRTOS/Source/CMSIS_RTOS_V2",
        "src/include"
    )

    add_files(
        "src/system/startup_stm32f103xe.s",
        "drivers/**.c",
        "middlewares/**.c",
        "src/**.c",
        "src/**.cpp"
    )

    after_build(function(target)
        local elf = target:targetfile()
        local hex = string.gsub(elf, "elf", "hex")
        local bin = string.gsub(elf, "elf", "bin")
        local toolchain_bin = TOOLCHAIN.."/bin/"
        os.exec(toolchain_bin.."arm-none-eabi-size -Ax "..elf)
        os.exec(toolchain_bin.."arm-none-eabi-size -Bd "..elf)
        os.exec(toolchain_bin.."arm-none-eabi-objcopy -O ihex "..elf.." "..hex)
        os.exec(toolchain_bin.."arm-none-eabi-objcopy -O binary "..elf.." "..bin)
    end)
target_end()

task("download")
    set_menu {
        usage = "xmake download",
        description = "download to device",
        options = {}
    }

    on_run(function ()
        os.exec("openocd -f interface/cmsis-dap.cfg -f target/stm32f1x.cfg -c 'adapter speed 10000; init; reset halt; wait_halt; program ./build/A2Plus.hex verify; shutdown'")
    end)
task_end()

### 附加信息和错误日志

![image](https://github.com/user-attachments/assets/4bb234f8-d405-4736-be3d-b0f5dc7c9017)

**Comment by waruqi** [comment]
这边暂时没法复现，给个可以复现的最小完整工程 zip

**Comment by cc-cao** [comment]
> 这边暂时没法复现，给个可以复现的最小完整工程 zip

[demo.zip](https://github.com/user-attachments/files/17571841/demo.zip)

编译器链接: https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-darwin-arm64-arm-none-eabi.tar.xz

**Comment by waruqi** [comment]
> > 这边暂时没法复现，给个可以复现的最小完整工程 zip
> 
> [demo.zip](https://github.com/user-attachments/files/17571841/demo.zip)
> 
> 编译器链接: https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-darwin-arm64-arm-none-eabi.tar.xz

我没 mac M1 ，用不了

**Comment by waruqi** [comment]
> warning: add_ldflags(""-mcpu=cortex-m3 -mthumb"") is ignored, please pass `{force = true}` or call `set_policy("check.auto_ignore_flags", false)` if you want to set it.

你没加 force ，上面提示不是很明显么，加上就没事了
