### ISSUE TITLE
构建工具需要专注依赖和构建方式的配置描述，提高用户体验

### ISSUE THREAD

**Issue by sxpc722** [xmake-io/xmake#578]
### 你在什么场景下需要该功能？

多数用户总是希望工具能契合实际需求而几乎没有学习成本。类似git这样的工具能迅速风靡，快速取代同类工具就是遵循这条规律。

**构建工具的设计思路应该着眼于对依赖关系的梳理编排以及对构建方法的描述**。而这些仅靠一个结构化的配置文件就足够了。我们应该考虑在遵循构建工作基本思路的前提下，最大程度地提供便利。这是一个工具的价值。

所以，对于构建工作来说提高依赖关系编排以及构建方式描述的效率才是重点。

举个例子：
对于一个包含多语言的复杂项目，有若干子系统，每个子系统可能由不同的语言实现（包括未知语言），也可能被分别部署到不同的平台。子系统内部又有诸多模块，互有依赖。构建工程师需要完成全系统构建，方便后续人员完成部署、调试等工作。期望构建工具能在获得最少必要信息的情况下完成构建。

### 描述可能的解决方案
我们不可能知道用户的工程有多复杂，不能指望预配置方案能给用户带来价值。人与工具的信息交互格式要符合构建工作的思维，便于构建者阅读理解，减少非必要的内容，言简意赅。
例如，是否可以用json格式描述构建信息，而不需要额外命令。

**Comment by waruqi** [comment]
? 所以具体需要表达什么呢？xmake.lua改成json描述？现在你这遇到的问题点是什么？

**Comment by OpportunityLiu** [comment]
这么一大段话，好像说了什么，又好像啥都没说。。。

**Comment by sxpc722** [comment]
需要构建工具的项目，一定不会是简单项目。从依赖描述，构建方法描述等方面来看，我觉得它作为构建工具，目前还不能解决项目构建的痛点。
对于稍微复杂点的项目而言，不仅需要准确描述模块，子系统之间的依赖关系，还要调度诸多编译工具，工作量是非常大的。我们希望只是提供构建所需的必要信息，而不用写任何命令。以此作为输入提供给构建工具。这可以极大提高构建工作的效率。

**Comment by waruqi** [comment]
> 从依赖描述，构建方法描述等方面来看，我觉得它作为构建工具，目前还不能解决项目构建的痛点。

是指哪方面痛点不满足呢？能举个实际例子来说明下 目前xmake提供的设置描述无法对其描述的地方么？目前通过`target.add_deps`也无法描述你这项目的子项目依赖关系？

> 对于稍微复杂点的项目而言，不仅需要准确描述模块，子系统之间的依赖关系，还要调度诸多编译工具，工作量是非常大的。我们希望只是提供构建所需的必要信息，而不用写任何命令。以此作为输入提供给构建工具。这可以极大提高构建工作的效率。

目前调用各种编译工具，也没让用户写命令么，你是指写了哪些命令？

**Comment by sxpc722** [comment]
例如需要描述一千个不同的依赖关系，是不是要写一千个target.add_deps ？ 这些输入对于构建者而言是不必要的。所以我的意思是，用工具去读，去分析构建者输入的构建信息，而不是要求他们用工具的API去输入信息。比如像makefile那样描述依赖关系，就基本找不出“废话”（对用户而言）。

编译工具的调用属于构建方式，留给用户去发挥，工具能帮他少写重复命令就挺好了。这个还是借鉴makefile。

但makefile的痛点是结构化不足，不便于阅读和维护。 
希望你能理解构建工程师的苦^.^

**Comment by sxpc722** [comment]
再举个例子，比如有个基础模块要修改接口，我需要知道有多少依赖它的模块受到影响，以便在构建前确认相关模块是否完成相应的修改。那能不能比较方便地从配置中找到答案。

**Comment by waruqi** [comment]
> 比如像makefile那样描述依赖关系，就基本找不出“废话”（对用户而言）。

makefile 这种不需要写一千个？我看也没省多少么？

```
a1: b1, b2, b3 b1000
a2: ...
...
a1000:
```

 > 用工具去读，去分析构建者输入的构建信息

那构建者输入的信息是什么？ add_deps不也是构建者输入的信息么？用其他方式输入 跟 add_deps输入有什么本质区别呢？

**Comment by sxpc722** [comment]
makefile里面的依赖信息已经没有可以省略的内容了，这就是做到了最少输入，这是用户想要的。用户很懒的，对于996的码农来讲多写一个点都不愿意。所以这就是站在谁的角度去看问题差别了。不全力替用户着想，用户肯定不买账的。^.^

**Comment by waruqi** [comment]
> 编译工具的调用属于构建方式，留给用户去发挥，工具能帮他少写重复命令就挺好了。这个还是借鉴makefile。
> 我们希望只是提供构建所需的必要信息，而不用写任何命令。以此作为输入提供给构建工具

又要让用户自己调用编译工具，又不能让用户写任何命令，是不是有点矛盾，而且这两方式 xmake 原本都支持。。xmake里面用户可以不写任何构建命令，也可以自己写任何构建命令

**Comment by waruqi** [comment]
> makefile里面的依赖信息已经没有可以省略的内容了，这就是做到了最少输入，这是用户想要的。用户很懒的，对于996的码农来讲多写一个点都不愿意。所以这就是站在谁的角度去看问题差别了。不全力替用户着想，用户肯定不买账的。^.^

我也是用户，而且是第一个用户，就是因为自己懒 不想敲makefile，所以整了xmake。原本写1千行makefile干的事情，xmake.lua 十几行就能搞定。。我个人觉得已经很省事，至少帮我省了大吧的时间。

**Comment by sxpc722** [comment]
我说的命令是指 xmake的api，大多数人是不想学新的api。要花成本的。

eclipse CDT 可以自动生成makefile，那是真的一个字都不用写。。。 看站在哪个角度看问题吧，如果自己用的话确实也不需要太关注其他人的看法。

**Comment by waruqi** [comment]
> 再举个例子，比如有个基础模块要修改接口，我需要知道有多少依赖它的模块受到影响，以便在构建前确认相关模块是否完成相应的修改。那能不能比较方便地从配置中找到答案。

通过`target.add_deps`维护的所有deps，每个target的依赖模块，也能很方便知道，项目不大的话，一眼就能看出来，项目大的话，`print(target:deps())` 就可以dump出来，我不相信用makefile维护依赖1000多个多层嵌套的target，能够比`print(target:deps())` 这十几个字符更少更快的方式立即获取到，而且在xmake.lua用户可以自己组织结构话查看deps。。

**Comment by waruqi** [comment]
> 我说的命令是指 xmake的api，大多数人是不想学新的api。要花成本的。
> 
> eclipse CDT 可以自动生成makefile，那是真的一个字都不用写。。。 看站在哪个角度看问题吧，如果自己用的话确实也不需要太关注其他人的看法。

xmake也能生成makefile，如果生成的结果不满意，我之前也说了，后面会改进生成结果。。

**Comment by sxpc722** [comment]
对，这个就是makefile做不到的地方，要借助工具。所以这一点就是xmake之于makefile的优势，解决的痛点之一，会是用户选用xmake的理由之一

**Comment by waruqi** [comment]
> 我说的命令是指 xmake的api，大多数人是不想学新的api。要花成本的。

你可以吧xmake.lua 上层描述的 所有设置。。不当成api，就是各种你说的json配置项就行了，只是多加了add_/set_三个字符的前缀。。

```lua
target
{
    name = "test",
    defines = "DEBUG",
    files = {"src/*.c", "test/*.cpp"}
}
```
这种方式之前也是同时支持的，跟add_xxx本质没啥区别，只不过后来实在是没人用这种方式写，我就去掉了。。

**Comment by waruqi** [comment]
> 我说的命令是指 xmake的api，大多数人是不想学新的api。要花成本的。
> 
> eclipse CDT 可以自动生成makefile，那是真的一个字都不用写。。。 看站在哪个角度看问题吧，如果自己用的话确实也不需要太关注其他人的看法。

我觉得你可以看下这个：
https://tboox.org/cn/2017/01/07/build-without-makefile/

目前你提的这些，xmake都有支持，建议你还是先熟悉下xmake各种功能

**Comment by waruqi** [comment]
> 中文版和英文版还有点差异，英文版全一些吧

完全一样的，英文只是从中文google翻译的。

> json方式是可以再考虑考虑的，几乎没有学习成本。

我刚说了，是否json对于目前xmake.lua的描述，两者没有本质区别，只是多了个set_/add_前缀而已，如果觉得加了这两就算学习成本了，那我也没办法

`add_files("src/*.c")`  等价于  `add_files "src/*.c"`  这跟  `"files": "src/*.c"` （json）这是写法上的不同而已，而且我觉得 前者更可读，有动词更易于理解。

> 但有开发难度，主要是信息的结构化。如果能实现的话，就能搞个zmake出来^.^，只要能转makefile就行，因为json和make工具链很完善。
> 只是多数人可能比我还要懒一点，看到长篇手册就绕道了

如果没有完全了解xmake的特性，建议还是先仔细研读熟悉下，再决定xmake是否满足你的需求，因为你的说的很多东西，xmake都有，只是你还不知道。

如果实在是懒 不想了解，那可以改用其他更省事，文档更少的工具好了，也可以自己整个zmake也行。。我当初也是不习惯cmake/autoconf才自己整了一个。

目前在xmake.lua描述语法上大体基本定型了，目前不打算做大的改动，而且这也是个人觉得比cmake/makefile之类更加有优势的地方，我觉得可读性，可维护性已经很好了。。关于目前xmake.lua的语法设计和理念，你可以看下：https://xmake.io/#/zh-cn/guide/syntax_description 里面介绍。

也非常感谢你对xmake的建议。

**Comment by sxpc722** [comment]
谢谢，最后还是希望能良好地接轨主流工具。毕竟操作系统标配的是make、nmake等。如果因为用户不认识xmake而无法编译发布的源码，这不利于使用xmake构建的开源项目
