### ISSUE TITLE
method 'set_enable' is not callable (a nil value)

### ISSUE THREAD

**Issue by MaxwellGengYF** [xmake-io/xmake#5783]
### Xmake 版本

v2.9.6+dev.668e8f302

### 操作系统版本和架构

Any OS

### 描述问题

使用target:set_enabled(false)报错。

### 期待的结果

set_enabled可以被调用

### 工程配置

on_load(function(target)
        target:set_enabled(true)
end)

### 附加信息和错误日志

error: error: method 'set_enabled' is not callable (a nil value)

**Comment by waruqi** [comment]
所有描述域的  set_xxx 和 add_xxx 接口，在脚本域，都是对应 `target:set("xxx", ...)` 和 `target:add("xxx", ...)`
