### ISSUE TITLE
error: @programdir/core/project/project.lua:994: @projectdir(ucsr7bc)/xmake.lua:2: attempt to call global 'set_license' (a nil value) stack traceback:

### ISSUE THREAD

**Issue by zombiezero** [xmake-io/xmake#5784]
### Xmake Version

2.3.7

### Operating System Version and Architecture

deepin 20.7.1

### Describe Bug

安装失败
error: @programdir/core/base/interpreter.lua:625: @programdir/core/sandbox/modules/interpreter/ifelse.lua: bad binary format (not a binary chunk)
stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:1004: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir/core/base/interpreter.lua:625: in function 'base/interpreter.builtin_modules'
        @programdir/core/base/interpreter.lua:692: in function 'base/interpreter.new'
        @programdir/core/theme/theme.lua:60: in function 'theme/theme._interpreter'
        @programdir/core/theme/theme.lua:133: in function 'theme/theme.load'
        @programdir/core/main.lua:277: in function 'main.entry'
        (...tail calls...)
error: @programdir/core/base/interpreter.lua:625: @programdir/core/sandbox/modules/interpreter/ifelse.lua: bad binary format (not a binary chunk)
stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:1004: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir/core/base/interpreter.lua:625: in function 'base/interpreter.builtin_modules'
        @programdir/core/base/interpreter.lua:692: in function 'base/interpreter.new'
        @programdir/core/theme/theme.lua:60: in function 'theme/theme._interpreter'
        @programdir/core/theme/theme.lua:133: in function 'theme/theme.load'
        @programdir/core/main.lua:277: in function 'main.entry'
        (...tail calls...)

### Expected Behavior

下载了源码使用./scripts/get.sh __local__  安装

### Project Configuration

export PATH=/home/wujiangfeng/.local/bin:$PATH

# parameter completions for *nix shell

if   [[ "$SHELL" = */zsh ]]; then
  # zsh parameter completion for xmake
  _xmake_zsh_complete() 
  {
    local completions=("$(XMAKE_SKIP_HISTORY=1 XMAKE_ROOT=y xmake lua private.utils.complete 0 nospace "$words")")
    reply=( "${(ps:\n:)completions}" )
  }
  compctl -f -S "" -K _xmake_zsh_complete xmake
elif [[ "$SHELL" = */bash ]]; then
  # bash parameter completion for xmake
  _xmake_bash_complete()
  {
    local word=${COMP_WORDS[COMP_CWORD]}
    local completions
    completions="$(XMAKE_SKIP_HISTORY=1 XMAKE_ROOT=y xmake lua private.utils.complete "${COMP_POINT}" "nospace-nokey" "${COMP_LINE}")"
    if [ $? -ne 0 ]; then
      completions=""
    fi
    COMPREPLY=( $(compgen -W "$completions") )
  }
  complete -o default -o nospace -F _xmake_bash_complete xmake
fi

### Additional Information and Error Logs

no

**Comment by xq114** [comment]
2.3.7？为啥要用这么老的版本

**Comment by waruqi** [comment]
too old version, please update to 2.9.6

**Comment by zombiezero** [comment]
是2.9.6出现这种问题，2.3.7可以安装，我也不想用老的呀

**Comment by zombiezero** [comment]
error: @programdir/core/base/interpreter.lua:625: @programdir/core/sandbox/modules/interpreter/ifelse.lua: bad binary format (not a binary chunk)
stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:1004: in function 'os.raiselevel'
        (...tail calls...)
        @programdir/core/base/interpreter.lua:625: in function 'base/interpreter.builtin_modules'
        @programdir/core/base/interpreter.lua:692: in function 'base/interpreter.new'
        @programdir/core/theme/theme.lua:60: in function 'theme/theme._interpreter'
        @programdir/core/theme/theme.lua:133: in function 'theme/theme.load'
        @programdir/core/main.lua:277: in function 'main.entry'
        (...tail calls...)
error: @programdir/core/base/interpreter.lua:625: @programdir/core/sandbox/modules/interpreter/ifelse.lua: bad binary format (not a binary chunk)
stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:1004: in function 'os.raiselevel'
        (...tail calls...)
        @programdir/core/base/interpreter.lua:625: in function 'base/interpreter.builtin_modules'
        @programdir/core/base/interpreter.lua:692: in function 'base/interpreter.new'
        @programdir/core/theme/theme.lua:60: in function 'theme/theme._interpreter'
        @programdir/core/theme/theme.lua:133: in function 'theme/theme.load'
        @programdir/core/main.lua:277: in function 'main.entry'
        (...tail calls...)

**Comment by zombiezero** [comment]
sudo chmod 777 ./xmake-x.x.x.gz.run
./xmake-x.x.x.gz.run
使用的上面的安装方式出现下面的错误怎么解决
error: @programdir/core/base/interpreter.lua:625: @programdir/core/sandbox/modules/interpreter/ifelse.lua: bad binary format (not a binary chunk)
stack traceback:

**Comment by waruqi** [comment]
用官网提供的一键安装脚本安装，根据提示操作。。

> error: @programdir/core/base/interpreter.lua:625: @programdir/core/sandbox/modules/interpreter/ifelse.lua: bad binary

新版本不存在这个文件，不要用低版本
