### ISSUE TITLE
让zig工具链可以编译汇编

### ISSUE THREAD

**Issue by wenxuanjun** [xmake-io/xmake#5786]
### 你在什么场景下需要该功能？

当需要使用zigcc来当作全套交叉编译工具链时，在编译汇编代码时仍然会fallback使用gcc而不是zigcc。
虽然可以`set_toolset("as", "zig cc")`手动设置使用，但无法使用拉取的zig工具链：`set_toolchains("@zig")`。

### 描述可能的解决方案

在`xmake/toolchains/zig/xmake.lua`中添加两行：
```lua
toolchain:set("toolset", "as", zig .. " cc")
toolchain:add("zig_cc.asflags", "-target", target)
```

### 描述你认为的候选方案

使用`set_toolset`来调用从xrepo拉取的zig工具链：`set_toolchains("@zig")`。

**Comment by waruqi** [comment]
可以直接提个 pr 过来
