### ISSUE TITLE
 xmake run -d 弹出框crash on Windows 10

### ISSUE THREAD

**Issue by ForrestSu** [xmake-io/xmake#579]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题
xmake run -d
error: execv(C:\WINDOWS\system32\vsjitdebugger.exe E:\workspace\xmake\hello\build\windows\x64\release\hello.exe) failed(2147500036)!

the debugger carsh ....

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 错误信息

如果可能，请尽量附加程序运行过程中的错误输出信息。

> 如果是xmake相关编译问题，请加上`-v -D`参数运行，并给出详细编译输出信息。

### 相关环境

请提供编译和运行环境信息，例如：xmake版本、操作系统等
xmake：  v2.2.8
OS：Windows10 专业版 1903 
已安装 visual studio  2017 社区版

### 其他信息
弹出的提示信息框
Visual Studio Just-In-Time Debugger
An error occurred while launching 'E:\workspace\xmake\hello\build\windows\x64\release\hello.exe ':

The Visual Studio Just-In-Time Debugger was not notified that the application correctly started.

Check the documentation index for 'Just-in-time debugging, errors' for more information.

**Comment by waruqi** [comment]
既然是调试程序，请先切到debug模式编译，确保pdb被生成

另外 xmake run -d 就是用来加载vs调试器来调试程序的，原本就会弹出crash框的。。点开始调试就行了。。

这个属于正常行为，如果觉得行为不正常，请截个图给我看下

**Comment by OpportunityLiu** [comment]
这个行为不正常。。我一个月前就在telegram上提过的。。。

**Comment by waruqi** [comment]
> 这个行为不正常。。我一个月前就在telegram上提过的。。。

你之前提的是 vsjitdebugger这个工具没找到吧。。他这个vsjitdebugger已经起来了。

**Comment by OpportunityLiu** [comment]
就是起来以后报这个错啊，一样一样的

**Comment by waruqi** [comment]
> 就是起来以后报这个错啊，一样一样的

哦 我以为你之前是调用没找到 vsjitdebugger 。能给个截图么？我这之前试了下 都没复现这个问题

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/65232386-a28c4f80-db03-11e9-8db0-9ba7e67ccb4c.png)

**Comment by OpportunityLiu** [comment]
好像必须从管理员启动

**Comment by waruqi** [comment]
> 好像必须从管理员启动

就是说这个 权限问题？管理员启动就正常了？ @ForrestSu 你这也试试呢 管理员模式

不过我这没用管理员 也能正常运行。

**Comment by ForrestSu** [comment]
> > 好像必须从管理员启动
> 
> 就是说这个 权限问题？管理员启动就正常了？ @ForrestSu 你这也试试呢 管理员模式
> 
> 不过我这没用管理员 也能正常运行。

用了管理员启动，正常运行了，但是怎么提前设置断点呢？

**Comment by waruqi** [comment]
> > > 好像必须从管理员启动
> > 
> > 
> > 就是说这个 权限问题？管理员启动就正常了？ @ForrestSu 你这也试试呢 管理员模式
> > 不过我这没用管理员 也能正常运行。
> 
> 用了管理员启动，正常运行了，但是怎么提前设置断点呢？

自己代码里面加个 int3 或者 abort 中断下就行了，比如在main开头加一下

```c
int main ()
{
    *((volatile int*)0) = 0;
    ....
}
```

**Comment by OpportunityLiu** [comment]
https://docs.microsoft.com/en-us/visualstudio/debugger/debugbreak-and-debugbreak?view=vs-2019

**Comment by OpportunityLiu** [comment]
> 用了管理员启动，正常运行了，但是怎么提前设置断点呢？

还是直接用 `xmake project -k vsxmake` 吧，也不需要管理员，也可以提前设断点

**Comment by OpportunityLiu** [comment]
> 不过我这没用管理员 也能正常运行。

感觉不应该是管理员的问题，启用管理员只是掩盖了某些问题让他能用了。

建议2010以后的调试器还是尽快改成 devenv.exe 吧

https://docs.microsoft.com/en-us/visualstudio/ide/reference/debugexe-devenv-exe?view=vs-2019

之前想提个PR加进去的，不知道为啥死活找不到devenv……

**Comment by waruqi** [comment]
回头我试试devenv，不过我为啥不用管理员也ok，有点怪。

**Comment by waruqi** [comment]
看了下，devenv就是ide主程序么，在IDE目录下，通过命令行带起调试，这样功能和兼容性确实比直接调vsjitdebugger要更好些。

```console
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\devenv.exe" /DebugExe build\windows\x64\debug\test.exe
```

带起来后，如果把main源文件拖进ide，也可以直接设置断点了，不用手动加int3去break了。。

或者可以想办法在`xmake run -d`带起程序后，让devenv自动加载所有源码会更方便些，不过这样似乎要依赖xmake project -k vsxmake去提前生成.sln才行，然后devenv才会加载整个sln包括源码.

**Comment by ForrestSu** [comment]
I use ` xmake project -k vsxmake ` is works fine.  but I use `xmake project -k vs2017` is crash !!
![image](https://user-images.githubusercontent.com/5516080/65318993-45f76600-dbd1-11e9-85af-b92c6f7f0e01.png)

**Comment by OpportunityLiu** [comment]
想指定 VS 版本用 `xmake project -k vsxmake2017`， `xmake project -k [vs|vs2017]` 那是另一码事了

**Comment by waruqi** [comment]
@OpportunityLiu @ForrestSu 我dev上更新了，xmake update -s dev

`xmake run -d` 默认采用devenv来加载和调试程序，加载打开vs后，可以吧main所在的源文件拖入vs，通过vs设置好断点，点击vs里面的运行按钮，即可开启调试，也不用手动加int3了
