### ISSUE TITLE
Can't  use ninja to build package

### ISSUE THREAD

**Issue by star-hengxing** [xmake-io/xmake#5792]
### Xmake Version

2.9.6

### Operating System Version and Architecture

all

### Describe Bug

https://github.com/xmake-io/xmake-repo/issues/5679
Caused by https://github.com/xmake-io/xmake/commit/5da59ed0a5da2b1f992c8548ca0325714c1ea4b3

### Expected Behavior

Work.

### Project Configuration

N/A

### Additional Information and Error Logs

N/A

**Comment by waruqi** [comment]
再试试 dev

**Comment by star-hengxing** [comment]
Work fine.
