### ISSUE TITLE
build.ccache.global_storage policy is not working as expected

### ISSUE THREAD

**Issue by for2years** [xmake-io/xmake#5793]
### Xmake Version

v2.9.6

### Operating System Version and Architecture

ubuntu 2204

### Describe Bug

I cloned two identical projects on the same machine and set `set_policy("build.ccache.global_storage", true)` for both.

 However, after compilation the another repo, the cache hit rate is 0.

### Expected Behavior

These two identical  projects should share the same ccache in `~/.xmake/.build_cache`.

### Project Configuration

none

### Additional Information and Error Logs

```bash
build cache stats:
cache directory: /root/.xmake/.build_cache
cache hit rate: 0%
cache hit: 0
cache hit total time: 0.000s
cache miss: 453
cache miss total time: 0.209s
new cached files: 453
remote cache hit: 0
remote new cached files: 0
preprocess failed: 0
compile fallback count: 3
compile total time: 5406.370s
```

**Comment by waruqi** [comment]
it works for me. you can debug here.
https://github.com/xmake-io/xmake/blob/a71785c9a6d7c7a3ca953986e155e50015c06214/xmake/modules/private/cache/build_cache.lua#L131-L133

```console
ruki-2:test ruki$ xmake -r
[ 50%]: cache compiling.release src/main.cpp
ccachedir
ccachedir2 /Users/ruki/.xmake/.build_cache
[ 75%]: linking.release test
[100%]: build ok, spent 0.772s
ruki-2:test ruki$ tree ~/.xmake/.build_cache/
/Users/ruki/.xmake/.build_cache/
└── 42
    └── 42f0b0efe4f63b66f9833ec1252d169d
```

```lua
add_rules("mode.debug", "mode.release")
set_policy("build.ccache.global_storage", true)

target("test")
    set_kind("binary")
    add_files("src/*.cpp")
```

**Comment by for2years** [comment]
> if not cachedir and project.policy("build.ccache.global_storage") then 
>      cachedir = path.join(global.directory(), ".build_cache") 
>  end

`set_policy("build.ccache.global_storage", true)` do indeed redirect the ccache directory to `~/.xmake/.build_cache`.

However, my question is that for two **same** projects, the cache hit rate should no be 0 after compiling them sequentially.

**Comment by for2years** [comment]
I want to use this policy because I cloned the same project in different directories on the same machine, like `~/A/my_project` and `~/B/my_project`, so I expect them to share the same cache.

**Comment by waruqi** [comment]
it still works for me.

```console
ruki-2:tmp ruki$ cp -r test test2
ruki-2:test2 ruki$ xmake -r
[ 50%]: cache compiling.release src/main.cpp
ccachedir
ccachedir2 /Users/ruki/.xmake/.build_cache
[ 75%]: linking.release test
[100%]: build ok, spent 1.775s
ruki-2:test2 ruki$ tree ~/.xmake/.build_cache/
/Users/ruki/.xmake/.build_cache/
└── 42
    └── 42f0b0efe4f63b66f9833ec1252d169d
```

```console
build cache stats:
cache directory: /Users/ruki/.xmake/.build_cache
cache hit rate: 100%
cache hit: 1
cache hit total time: 0.002s
cache miss: 0
cache miss total time: 0.000s
new cached files: 0
remote cache hit: 0
remote new cached files: 0
preprocess failed: 0
compile fallback count: 0
compile total time: 0.000s
```

**Comment by for2years** [comment]
ok thanks, I try to debug it.

**Comment by for2years** [comment]
The reason is that I used `add_includedirs(os.projectdir())` which caused the compile parameters to be inconsistent.

Another issue is that if my target is a proto-target to generate *.h and *.cc according to *.proto files like:

```lua
target("my_proto_target")
    set_kind("object")
    add_rules("protobuf.cpp")
    add_files("proto/*.proto", {proto_public = true})
    add_packages("protobuf-cpp", {public = true})
```

It **does not generate any cache files**, rusulting in a cache hit rate of 0, what should I do to reuse the cache for proto files?

**Comment by waruqi** [comment]
same cache policy. you can debug proto files compilation flags. 

And this issue should have been resolved. build.ccache.global_storage policy has no any problem.

**Comment by for2years** [comment]
ok thanks anyway~

**Comment by for2years** [comment]
> you can debug proto files compilation flags.

Do you have any suggestions to help me debug the no-cache-problem for proto files. I don't know where to start actually.

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/blob/86936573d8659a0a3a0d4507c1e89f65459e202f/xmake/modules/core/tools/gcc.lua#L812

https://github.com/xmake-io/xmake/blob/86936573d8659a0a3a0d4507c1e89f65459e202f/xmake/modules/private/cache/build_cache.lua#L277

check the cache key and cppinfo

**Comment by for2years** [comment]
ok I will try it, thanks
