### ISSUE TITLE
有考虑增加一种kind，伪目标类型吗？

### ISSUE THREAD

**Issue by pimatrix** [xmake-io/xmake#5798]
### 你在什么场景下需要该功能？

比如，xmake 一些特殊的任务，xmake 下载；xmake 生成代码；xmake 文档，等

### 描述可能的解决方案

类似makefile的伪目标

### 描述你认为的候选方案

才接触xmake，搜索了一下没有发现这个功能

**Comment by star-hengxing** [comment]
https://xmake.io/#/manual/project_target?id=phony

**Comment by waruqi** [comment]
走 rule
