### ISSUE TITLE
panic when debug with Emmylua

### ISSUE THREAD

**Issue by for2years** [xmake-io/xmake#5799]
### Xmake Version

latest maser

### Operating System Version and Architecture

ubuntu 2204

### Describe Bug

Compiling directly with xmake works correctly:
```bash
xmake -bvrD
```

But **everytime** when I try to debug with Emmylua, it will panic at xpcall:
![b98da37d73c7d0c784fbc365e31c8355](https://github.com/user-attachments/assets/d58cf03f-7838-49d4-b85f-a3f338755f10)

### Expected Behavior

Can use Emmylua to debug xmake successfully.

### Project Configuration

my break poing:

https://github.com/xmake-io/xmake/blob/86936573d8659a0a3a0d4507c1e89f65459e202f/xmake/modules/private/cache/build_cache.lua#L275

https://github.com/xmake-io/xmake/blob/86936573d8659a0a3a0d4507c1e89f65459e202f/xmake/modules/core/tools/gcc.lua#L770

https://github.com/xmake-io/xmake/blob/86936573d8659a0a3a0d4507c1e89f65459e202f/xmake/modules/core/tools/gcc.lua#L901

### Additional Information and Error Logs

my debug command:
```bash
xrepo env -b emmylua_debugger -- xmake -bvrD
```

logs:
```bash
error: /usr/local/share/xmake/core/main.lua:329: /usr/local/share/xmake/actions/build/main.lua:148: /usr/local/share/xmake/modules/async/runjobs.lua:325: ...ocal/share/xmake/modules/private/action/build/object.lua:91: /usr/local/share/xmake/modules/core/tools/gcc.lua:938: /usr/local/share/xmake/modules/core/tools/gcc.lua:901: invalid key to 'next'
stack traceback:
    [/usr/local/share/xmake/modules/core/tools/gcc.lua:901]:
stack traceback:
        [C]: in function 'error'
        /usr/local/share/xmake/core/base/os.lua:1004: in function 'base/os.raiselevel'
        (...tail calls...)
        /usr/local/share/xmake/core/main.lua:329: in upvalue 'cotask'
        /usr/local/share/xmake/core/base/scheduler.lua:406: in function </usr/local/share/xmake/core/base/scheduler.lua:399>
error: execv(xmake -bvrD) failed(255)
```

**Comment by waruqi** [comment]
I don't know, please use print to debug it.

**Comment by for2years** [comment]
> I don't know, please use print to debug it.

ok thanks, `print` is enough for me.
