### ISSUE TITLE
无法识别数据盘上的Qt环境

### ISSUE THREAD

**Issue by Elite-stay** [xmake-io/xmake#5801]
### Xmake 版本

2.9.5

### 操作系统版本和架构

银河麒麟

### 描述问题

执行xmake f --qt=/data/Qt5.14.2时，提示`Qt SDK directory ... %s`，数据盘不是nas的

![U5J~IZINO0IQM3UV_}WH9YH](https://github.com/user-attachments/assets/9cc3498f-d14b-4c93-8a19-6d538311ece8)

### 期待的结果

可以正常使用

### 工程配置

`xmake f --qt=/data/Qt5.14.2 -vD`

### 附加信息和错误日志

```console
checking for platform ... linux
checking for architecture ... arm64
checking for gcc ... /usr/bin/gcc
checkinfo: runv(zig version) failed(127)
checking for zig ... no
checkinfo: runv(zig version) failed(127)
checking for zig ... no
checkinfo: runv(nim --version) failed(127)
checking for nim ... no
checkinfo: runv(nim --version) failed(127)
checking for nim ... no
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /bin/gzip
checking for tar ... /bin/tar
checking for Qt SDK directory ... %s
checking for Qt SDK version ... no
error: @programdir/core/main.lua:329: @programdir/rules/qt/ui/xmake.lua:35: uic not found!
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:1004]: in function 'raiselevel'
    [@programdir/core/sandbox/modules/utils.lua:143]: in function 'assert'
    [@programdir/rules/qt/ui/xmake.lua:35]: in function 'on_config'
    [...dir/core/sandbox/modules/import/core/project/project.lua:133]: in function '_config_target'
    [...dir/core/sandbox/modules/import/core/project/project.lua:157]: in function '_config_targets'
    [...dir/core/sandbox/modules/import/core/project/project.lua:204]: in function 'load_targets'
    [@programdir/actions/config/main.lua:407]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:241]:
    [@programdir/core/base/task.lua:491]: in function 'run'
    [@programdir/core/main.lua:327]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:406]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:1004: in function 'os.raiselevel'
        (...tail calls...)
        @programdir/core/main.lua:329: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:406: in function <@programdir/core/base/scheduler.lua:399>
```

**Comment by waruqi** [comment]
改成 `/data/Qt/5.14.2` 目录结构试下，然后看下 里面  bin 目录下有没有 qmake

或者自己 加 print 调试下 https://github.com/xmake-io/xmake/blob/dev/xmake/modules/detect/sdks/find_qt.lua

**Comment by Elite-stay** [comment]
> 改成 `/data/Qt/5.14.2` 目录结构试下，然后看下 里面 bin 目录下有没有 qmake
> 
> 或者自己 加 print 调试下 https://github.com/xmake-io/xmake/blob/dev/xmake/modules/detect/sdks/find_qt.lua

下载源码编译完了之后，`source scripts/srcenv.profile`提示权限不够，但是我`ls -la`看了xmake权限是775呀

**Comment by waruqi** [comment]
> > 改成 `/data/Qt/5.14.2` 目录结构试下，然后看下 里面 bin 目录下有没有 qmake
> > 或者自己 加 print 调试下 https://github.com/xmake-io/xmake/blob/dev/xmake/modules/detect/sdks/find_qt.lua
> 
> 下载源码编译完了之后，`source scripts/srcenv.profile`提示权限不够，但是我`ls -la`看了xmake权限是775呀 ![企业微信截图_17310348203543](https://private-user-images.githubusercontent.com/9249009/384252560-f39cc9ed-625e-4f02-ac58-fcb32db8cada.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNDk3ODgsIm5iZiI6MTczMTA0OTQ4OCwicGF0aCI6Ii85MjQ5MDA5LzM4NDI1MjU2MC1mMzljYzllZC02MjVlLTRmMDItYWM1OC1mY2IzMmRiOGNhZGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMDcwNDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzQzZWFhMDQ2MDBkYjc0MGEzODAxNGQ5ZmY0OTg0ZWNjODA1ZGI1MDMxODkxNDc4ZTdlMjg5NTIyYzVjNjkwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.eSXe4zK9311NdI0mHewN4zuNor0tsxCeANv-csrWIN8)

这种权限问题，你自己研究下么，跟 xmake 又没啥关系。chmod 自己搞下

**Comment by Elite-stay** [comment]
应该是权限问题，数据盘是mount出来然后noexec的，应该修一下`find_qt.lua`的`_get_qtenvs`里`results`的判断`nil`就行，这种平时不提示，但是在`-v`的情况下提示一下比较好？

**Comment by waruqi** [comment]
> https://github.com/xmake-io/xmake/blob/dev/xmake/modules/detect/sdks/find_qt.lua

提示啥，这种出现概率不到 1% ，有问题调下 find_qt.lua 就行了，加了 logs，也没几个人能修，还是得调这个
