### ISSUE TITLE
xrepo 搜索的时候是否可以把最新版本号带上

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#5802]
### 你在什么场景下需要该功能？

否则还得xrepo info 去看

### 描述可能的解决方案

xrepo search xxx的时候，把最新版本号也带上

**Comment by waruqi** [comment]
原本就带上的，是之前重构搜索改出来的 bug，现在可以了。。`xmake update -s dev`

**Comment by heheda123123** [comment]
我就说，好像以前看到过版本，后来咋没了，还以为记错了
