### ISSUE TITLE
xmake lua version 

### ISSUE THREAD

**Issue by CppCXY** [xmake-io/xmake#5810]
### Xmake 版本

2.9.6

### 操作系统版本和架构

linux

### 描述问题

我收到bug报告: 使用emmylua调试时xmake在断点时崩溃, 通过排查分析, 我发现是xmake内建的lua版本是lua5.4.3, 而emmylua调试器自带的lua版本是5.4.6. 我通过降级emmylua调试器带的lua源码到5.4.3后, 崩溃现象不再出现, 我建议考虑在xrepo仓库的emmylua调试器降级lua源码版本, 或者升级xmake的lua源码版本

### 期待的结果

不再崩溃

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
xrepo. 仓库里有各种 lua 版本，自己选择指定版本安装就行了。

**Comment by for2years** [comment]
#5799 

xmake and emmylua both embed Lua 5.4, but with different versions, which causes unexpected errors during debugging.

**Comment by waruqi** [comment]
其实之前已经更新到 lua 5.4.6 了，只是更新过程中，xmake/core/lua 里面切错版本了，切到了 5.4.3 而已。。我现在更新到了 5.4.7 了，可以再试试

**Comment by for2years** [comment]
now it fixed
