### ISSUE TITLE
gitee is *very* slow

### ISSUE THREAD

**Issue by davidchisnall** [xmake-io/xmake#5812]
### Xmake Version

N/A

### Operating System Version and Architecture

N/A

### Describe Bug

Running the install script fetches the dependencies as submodules from gitee (including ones where upstream is hosted elsewhere, so I guess these are mirrors?).  Unfortunately, this is *painfully* slow (outside China?) and often results in timeouts and disconnections.  I'm trying to set up CI to test the xmake builds each day to prevent regressions, but the [most recent run](https://github.com/CHERIoT-Platform/cheriot-rtos/actions/runs/11777659529/job/32802502156) has spent ten minutes trying to download the source.  Compiling it then takes <30s.

It would be great if the install script could provide an option to fetch from some mirror, rather than doing a clone from such a slow server.

### Expected Behavior

Running the install script doesn't take over 10 minutes to fetch the code before it even starts building.

### Project Configuration

N/A

### Additional Information and Error Logs

N/A

**Comment by waruqi** [comment]
why do not use xmake github action? it will be faster. and it support install binary cache.

https://github.com/xmake-io/github-action-setup-xmake

**Comment by waruqi** [comment]
now it will use github url on action ci. https://github.com/xmake-io/xmake/commit/52548a1ba3a1949d3cf36d5c019a1849e3e45d17
