### ISSUE TITLE
动态库依赖 abseil 时，链接报错提示 abseil 非 -fPIC 编译，即使加上选项

### ISSUE THREAD

**Issue by vrecluse** [xmake-io/xmake#5816]
### Xmake 版本

2.9.6

### 操作系统版本和架构

Ubuntu 23.04

### 描述问题

如题，手动加上 cxflags -fPIC 和 requires 里 configs 设置都不行

### 期待的结果

成功链接

### 工程配置

add_rules("mode.debug", "mode.release")

add_cxflags("-fPIC")
add_requires("abseil", {configs = {pic = true}})
add_requires("spdlog")

target("mylib")
    set_kind("shared")
    set_languages("c++20")
    add_packages("abseil", "spdlog")
    add_files("./src/*.cpp")
    set_toolchains("clang")

### 附加信息和错误日志

```
error: mold: error: /home/xavier/.xmake/packages/a/abseil/20240722.0/e068e8bd8b7e42199d4d8762b92b8f9a/lib/libabsl_hash.a(hash.cc.o):(.text): R_X86_64_PC32 relocation at offset 0x110 against symbol `absl::lts_20240722::hash_internal::MixingHashState::kSeed' can not be used; recompile with -fPIC
```

**Comment by star-hengxing** [comment]
pic 默认开启的，会传给 cmake `-DCMAKE_POSITION_INDEPENDENT_CODE=ON`。如果是交叉编译，那应该和这个一样 https://github.com/xmake-io/xmake/issues/5814 。

---

项目 xmake.lua 各种操作都不会影响 package 的构建，额外操作都在 `add_requires` 控制。
```lua
add_requires("abseil", {configs = {cxflags = "-fPIC"}})
```

**Comment by waruqi** [comment]
目前 交叉编译对 cmake 包，默认没处理 pic ，就只对处理 linux/bsd 处理了。主要是之前我不确定所有交叉编译工具链是否都支持 pic

我先暂时放开了，让 cmake 自己去处理好了。

https://github.com/xmake-io/xmake/pull/5817
