### ISSUE TITLE
Allow target:on_config to be used for general configuration

### ISSUE THREAD

**Issue by Raildex** [xmake-io/xmake#5831]
### Is your feature request related to a problem? Please describe.

We can use `on_config("windows")` and `on_config("linux")` to specify platform (and arch) specific configuration.

however, `on_config()` without a platform/arch is not called when one of the `on_config` matches

### Describe the solution you'd like

I would like to have `on_config` without parameters to be used for general configuration:

```lua

target(foo)
	on_config(function(target) 
	-- general config here, gets executed for any plat/arch
	end)

	on_config("windows|x86",function(target) 

	-- win x86 here
	end)

	on_config("windows|x64",function(target) 

	-- win x64 here
	end)

	on_config("linux|x64",function(target) 
	-- linux x64 here
	end)

	on_config("linux|x86",function(target) 
	-- linux x86 here
	end)

target_end()

```

### Describe alternatives you've considered

```lua
target(foo)

on_config(function(target) 

if(is_plat("windows")) then 
	if(is_arch("x64")) then
-- win x64 here
	elseif(is_arch("x86")) then
-- win x86 here
	end
elseif (is_plat("linux")) then
	if(is_arch("x64")) then
-- linux x64 here
	elseif(is_arch("x86")) then
-- linux x86 here
	end
end

-- general config here

end)
```

**Comment by waruqi** [comment]
> however, on_config() without a platform/arch is not called when one of the on_config matches

no, on_config is only for fallback, if no specific platform is matched, on_config without platform will be called.

for windows:

```
on_config("linux", ...)
on_config(...) -> called
```


for linux:

```
on_config("linux", ...) --> called
on_config(...) 
```

**Comment by Raildex** [comment]
thats what i figured. would it be possible to add my desired behaviour or make an alternative ("before_config()") ?

I would like to avoid if-else chains

**Comment by waruqi** [comment]
this? https://github.com/xmake-io/xmake/pull/5813

**Comment by Raildex** [comment]
Can these functions be added for a target?

**Comment by waruqi** [comment]
no, only for rule
