### ISSUE TITLE
无法通过 is_config() 对 plat/arch/toolchain 进行配置后，应用于 add_requires() 和 各 target()  的编译

### ISSUE THREAD

**Issue by yflin1** [xmake-io/xmake#5832]
### Xmake 版本

xmake v2.9.6+HEAD.abd15c2

### 操作系统版本和架构

Ubuntu 22.04

### 描述问题

想要通过 xmake 命令行参数(device)，如 xmake f --device=pc，统一对不同的设备的 arch/plat/toolchain 等等进行配置，但达不到效果。

### 期待的结果

如果执行 xmake f --device=pc，那么对 add_require() 引入的第三方库 和 各个 target 的编译时都自动使用 arch=x86_64, plat=linux, toolchain=mygcc9; 
如果 xmake f --device=dev1，那么对 第三方库 和 各个 target 的编译都自动使用 arch=arm64, plat=linux, toolchain=my-dev1-gcc; ...

### 工程配置

options.lua:
option("device")
    set_default("pc")
    set_showmenu(true)
    set_values("pc", "dev1", "dev2)
    set_description("Set target device")

xmake.lua:
if is_config("device", "dev1") then
    set_toolchains("my-dev1-gcc")
    set_plat("linux")
    set_arch("aarch64")
elseif is_config("device", "dev2") then
    set_toolchains("my-dev2-gcc")
    set_plat("linux")
    set_arch("aarch64")
elseif is_config("device", "pc") then
    set_toolchains("gcc9")
    set_plat("linux")
    set_arch("x86_64")
end

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
到底怎么个没达效果，倒是说说哈，is_config 没生效？。。。？

logs 也没有，我咋知道

**Comment by yflin1** [comment]
> 到底怎么个没达效果，倒是说说哈，is_config 没生效？。。。？
> 
> logs 也没有，我咋知道

就是，如果我执行 xmake f --device=dev1，理论上，应该用 arch=aarch64,plat=linux,toolchain=my-dev1-gcc 这组参数编译 我的第三方库，但实际上看起来用的还是默认的 arch=x86_64, plat=linux, toolchain=gcc

options.lua文件:
...
option("device")
set_default("pc")
set_showmenu(true)
set_values("pc", "dev1", "dev2)
set_description("Set target device")
...

xmake.lua文件:
...
if is_config("device", "dev1") then
    set_toolchains("my-dev1-gcc")
    set_plat("linux")
    set_arch("aarch64")
elseif is_config("device", "dev2") then
...

我不知道我这样写是否有问题

**Comment by yflin1** [comment]
set_toolchains("my-dev1-gcc")
set_plat("linux")
set_arch("aarch64")

是否可以应用于 add_requires() 里的第三方库的编译？

**Comment by waruqi** [comment]
> set_toolchains("my-dev1-gcc") set_plat("linux") set_arch("aarch64")
> 
> 是否可以应用于 add_requires() 里的第三方库的编译？

可以，你可以看下这个 example ，就是完全用了，并且每天 ci tests 都在跑，一直没问题。。

https://github.com/xmake-io/xmake/blob/4778eb29d31ce7745e75f0b74c71cc9c93b469af/tests/projects/package/toolchain_muslcc/xmake.lua#L5

https://github.com/xmake-io/xmake/blob/4778eb29d31ce7745e75f0b74c71cc9c93b469af/tests/projects/package/toolchain_muslcc/xmake.lua#L36

**Comment by yflin1** [comment]
> > set_toolchains("my-dev1-gcc") set_plat("linux") set_arch("aarch64")
> > 是否可以应用于 add_requires() 里的第三方库的编译？
> 
> 可以，你可以看下这个 example ，就是完全用了，并且每天 ci tests 都在跑，一直没问题。。
> 
> https://github.com/xmake-io/xmake/blob/4778eb29d31ce7745e75f0b74c71cc9c93b469af/tests/projects/package/toolchain_muslcc/xmake.lua#L5
> 
> https://github.com/xmake-io/xmake/blob/4778eb29d31ce7745e75f0b74c71cc9c93b469af/tests/projects/package/toolchain_muslcc/xmake.lua#L36

好的，感谢！我这边测试可以了。
看起来是 set_toolchains 这些代码写的位置的问题，我把 options 和 requires 分别写在不同的 .lua 文件里，再在主 xmake.lua 里 include 进来。原本 set_toolchains 写在 requires.lua 里，这样就会有上面的问题，现在改写在主 xmake.lua 里，就正常了。

**Comment by star-hengxing** [comment]
如果不是用 set_config("arch", xx) 设置的，当然不一样。但你已经在 xmake.lua 用了 `set_arch` ，target 就不会去用 config 里的 arch 了。

**Comment by waruqi** [comment]
> 这样只是说，在 xmake f -vv --device=dev1 时，参数 -v 最后打印出来的 configure 日志里 arch 是错的： configure { arch = x86_64 ndk_stdcxx = true plat = linux device = dev1 buildir = /home/nn/test/build mode = release kind = static target_os = linux host = linux ccache = true }
> 
> 其中 aarch 理论上应该是 aarch64 才对

没啥问题，你理解的不对。

set_arch/set_plat 是 target 粒度的，你每个 target 可以设置不同的 plat/arch/toolchain ，跨 arch/toolchain 编译，如果你放在根域，那就是全局所有 target 生效

但是 `xmake f --arch=` 是全局平台粒度的，如果你没设置 set_arch，则所有 target 默认用这个 arch ，但是如果你配置了 set_arch ，优先走 target 粒度的 arch 配置。。这两是两个东西。 不要搞混了。。

你 `xmake f -v`  看到的 arch 信息，仅仅只是 全局平台的 arch 。。不可能每个 target 的 arch 全部显示出来。

总之，只要你用 set_arch/set_plat/set_toolchain 对target 做了设置，就不用管 平台那个默认的 plat/arch/toolchain 了。。要 `xmake -rv` 看 target 编译实际生效了哪个 arch 就行了。。
