### ISSUE TITLE
Blocking in find_openssl

### ISSUE THREAD

**Issue by fxxhuang** [xmake-io/xmake#5838]
### Xmake Version

2.9.6

### Operating System Version and Architecture

ubuntu 20.04 amd64

### Describe Bug

The xmake build is blocking at find_openssl and has a proxy set up with no network issues. When “which emerge” found my project unrelated to the toolkit /xxxx/INNOVUS/bin/emerge. This emerge should not be what xmake needs to find. When using the ” /xxxx/INNOVUS/bin/emerge --version“ command, it gets stuck here.

### Expected Behavior

xmake can be built smoothly.

### Project Configuration

add_rules("mode.debug", "mode.release")
add_requires("openssl")

target("xxx")
    set_kind("binary")
    add_files("src/*.cpp")

### Additional Information and Error Logs

<subprocess: cat>: cat /proc/cpuinfo
<subprocess: which>: which gcc
<subprocess: gcc>: /usr/bin/gcc --version
checking for gcc ... /usr/bin/gcc
<subprocess: which>: which zig
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
<subprocess: which>: which zig
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
<subprocess: which>: which nim
checkinfo: cannot runv(nim --version), No such file or directory
checking for nim ... no
<subprocess: which>: which nim
checkinfo: cannot runv(nim --version), No such file or directory
checking for nim ... no
<subprocess: which>: which git
<subprocess: git>: /usr/bin/git --version
checking for git ... /usr/bin/git
<subprocess: which>: which gzip
<subprocess: gzip>: /usr/bin/gzip --version
checking for gzip ... /usr/bin/gzip
<subprocess: which>: which tar
<subprocess: tar>: /usr/bin/tar --version
checking for tar ... /usr/bin/tar
/usr/bin/git rev-parse HEAD
<subprocess: git>: /usr/bin/git rev-parse HEAD
finding openssl from xmake ..
checking for xmake::openssl ... no
finding openssl from find_openssl ..
<subprocess: which>: which pacman
checkinfo: cannot runv(pacman --version), No such file or directory
checking for pacman ... no
<subprocess: which>: which emerge
<subprocess: emerge>: /home/user49/EDAtool/software/cadence/INNOVUS201/bin/emerge --version
^C[xmake]: [engine]: 1000
stack traceback:
        [C]: in function 'base/io.poller_wait'
        @programdir/core/base/poller.lua:115: in function 'base/poller.wait'
        @programdir/core/base/scheduler.lua:1063: in function 'base/scheduler.runloop'
        @programdir/core/main.lua:333: in function 'main.entry'
        (...tail calls...)
Trace/breakpoint trap (core dumped)
(base) huangfuxing@AS-4124GS-TNR:~/project/floorplanning$ XMAKE_PROFILE=stuck xmake -vD
<subprocess: cat>: cat /proc/cpuinfo
<subprocess: which>: which gcc
<subprocess: gcc>: /usr/bin/gcc --version
checking for gcc ... /usr/bin/gcc
<subprocess: which>: which zig
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
<subprocess: which>: which zig
checkinfo: cannot runv(zig version), No such file or directory
checking for zig ... no
<subprocess: which>: which nim
checkinfo: cannot runv(nim --version), No such file or directory
checking for nim ... no
<subprocess: which>: which nim
checkinfo: cannot runv(nim --version), No such file or directory
checking for nim ... no
<subprocess: which>: which git
<subprocess: git>: /usr/bin/git --version
checking for git ... /usr/bin/git
<subprocess: which>: which gzip
<subprocess: gzip>: /usr/bin/gzip --version
checking for gzip ... /usr/bin/gzip
<subprocess: which>: which tar
<subprocess: tar>: /usr/bin/tar --version
checking for tar ... /usr/bin/tar
/usr/bin/git rev-parse HEAD
<subprocess: git>: /usr/bin/git rev-parse HEAD
finding openssl from xmake ..
checking for xmake::openssl ... no
finding openssl from find_openssl ..
<subprocess: which>: which pacman
checkinfo: cannot runv(pacman --version), No such file or directory
checking for pacman ... no
<subprocess: which>: which emerge
<subprocess: emerge>: /xxxx/INNOVUS/bin/emerge --version

**Comment by waruqi** [comment]
这种没办法，你环境提供的 emerge 卡住了，这边是规避不了的，只能你自己解决 emerge 的问题，这边统一走的 which 去找的

理论上机制找的 bin 不对，尝试执行 --version，对应程序也不应该卡住。。这是你这 emerge 的问题

**Comment by fxxhuang** [comment]
是的，我这边先屏蔽emerge
