### ISSUE TITLE
为什么  xmake环境变量是错误的? 

### ISSUE THREAD

**Issue by Super1Windcloud** [xmake-io/xmake#5844]
### Xmake Version

latest 

### Operating System Version and Architecture

win11  

### Describe Bug

# 构建输出 
![图片](https://github.com/user-attachments/assets/d1349f81-f077-4b69-be0e-38d49793e02a)

#  环境变量路径是 Mingw-12 , 但是终端输出的版本的Mingw-5   

![图片](https://github.com/user-attachments/assets/01612f8e-8470-4f61-b5cb-990740a71fbc)

 #  并且后续的编译工具链输出是 MSVC 而不是 GCC  , 很奇怪 

### Expected Behavior

.

### Project Configuration

.

### Additional Information and Error Logs

.

**Comment by Super1Windcloud** [comment]
![图片](https://github.com/user-attachments/assets/3546c431-2ea6-42da-9cd6-925a21c29a42)


![图片](https://github.com/user-attachments/assets/07adf6c0-c74e-440b-abca-d696e8ad9601)

**Comment by star-hengxing** [comment]
`xmake f -c --mingw=path/to/sdk`

**Comment by waruqi** [comment]
xmake 默认只会检测 MSYSTEM 变量来判断当前是否在 msys2/mingw环境，如果不是，你只能自己切到 mingw 平台，`xmake f -c -p mingw --mingw=path/to/sdk`
