### ISSUE TITLE
C/C++ Code Analysis Extended support [Valgrind, PVS-Studio-cli]

### ISSUE THREAD

**Issue by kassane** [xmake-io/xmake#585]
It would be interesting to attach as an extra extension in xmake debugging code using valgrind and pvs-studio cli.

[pvs-studio-cmake-example](https://github.com/viva64/pvs-studio-cmake-examples/blob/master/PVS-Studio.cmake)

**Comment by waruqi** [comment]
You can write a custom on_run script to implement in xmake.lua

```lua
target("test")
    on_run(function (target)
        os.exec("")
    end)
```
