### ISSUE TITLE
大工程里vsxmake单独编译一个cpp卡住的问题

### ISSUE THREAD

**Issue by wagcheg** [xmake-io/xmake#5860]
### Xmake 版本

v2.9.2

### 操作系统版本和架构

Windows 11 

### 描述问题

工程里300+工程3000+文件
单编一个cpp卡住无输出

看代码虽然指定了target但是还是遍历了所有target

### 期待的结果

正常使用单编一个cpp的功能

### 工程配置

无

### 附加信息和错误日志

xmake build -y  -P .  --files=“/path/path/path/path/100.cpp" "foo100"

**Comment by star-hengxing** [comment]
参考 https://github.com/xmake-io/xmake/issues/2033 看一下堆栈

**Comment by wagcheg** [comment]
[many_targets_with_longpath_files.zip](https://github.com/user-attachments/files/17872376/many_targets_with_longpath_files.zip)
复现xmake b --files="1.cpp" "t1"

**Comment by wagcheg** [comment]
[wc@wc many_targets_with_longpath_files]$ XMAKE_PROFILE=stuck xmake b --files="1.cpp" "t1"
<subprocess: cat>: cat /proc/cpuinfo
checking for platform ... linux
checking for architecture ... x86_64
<subprocess: which>: which gcc
<subprocess: gcc>: /usr/bin/gcc --version
<subprocess: which>: which zig
<subprocess: which>: which zig
<subprocess: which>: which nim
<subprocess: which>: which nim
^C
^C[xmake]: [engine]: stack traceback:
        @programdir/modules/async/runjobs.lua:180: in function <@programdir/modules/async/runjobs.lua:56>
        (...tail calls...)
        @programdir/actions/build/build_files.lua:205: in function <@programdir/actions/build/build_files.lua:196>
        (...tail calls...)
        @programdir/actions/build/main.lua:107: in global '_do_build'
        @programdir/actions/build/main.lua:126: in function <@programdir/actions/build/main.lua:120>
        [C]: in function 'xpcall'
        @programdir/core/base/utils.lua:244: in function 'base/utils.trycall'
        @programdir/core/sandbox/modules/try.lua:117: in global 'try'
        @programdir/actions/build/main.lua:118: in global 'build_targets'
        @programdir/actions/build/main.lua:201: in function <@programdir/actions/build/main.lua:165>
        (...tail calls...)
        [C]: in function 'xpcall'
        @programdir/core/base/utils.lua:244: in function 'base/utils.trycall'
        (...tail calls...)
        @programdir/core/base/task.lua:491: in function 'base/task.run'
        @programdir/core/main.lua:327: in upvalue 'cotask'
        @programdir/core/base/scheduler.lua:406: in function <@programdir/core/base/scheduler.lua:399>
^C追踪或断点陷阱（核心已转储）

**Comment by wagcheg** [comment]
![2024-11-22_23-20](https://github.com/user-attachments/assets/df294584-971a-46ca-a011-202753390157)
我的修改

**Comment by wagcheg** [comment]
压缩包里有火焰图
    替换profiler.lua
    XMAKE_PROFILE=flamegraph xmake b --files="1.cpp" "t1" > perf.folded
    flamegraph.pl perf.folded > perf.svg
这个问题和文件路径长度有关系 实际环境里的长度比这个还要长些
应该是对全部文件匹配一次耗时太高
我的修改降低了要遍历的文件数量

**Comment by waruqi** [comment]
跟长文件没关系，整个匹配也就 6s，是 target job 链死循环了。再试试 `xmake update -s dev`
