### ISSUE TITLE
增量编译问题

### ISSUE THREAD

**Issue by wagcheg** [xmake-io/xmake#5861]
### Xmake 版本

v2.9.2

### 操作系统版本和架构

Windows 11

### 描述问题

1.obj文件的依赖没有pch文件 为了实现sharedpch以及问题3
2.动态库只删除dll或者lib后不能生成dll 
2.1由于中断链接生成的2M大小的dll 运行不起来 手动删除该dll 重新编译不会链接新的
2.2排查链接问题 删除lib不触发链接
3.rules生成的cpp没有depfile和pch依赖支持 删除间接引用的dllexport的头文件的函数导致使用moc的target链接不过 目前通过修改rules在load阶段将moc.cpp添加到files解决

### 期待的结果

能够增量构建

### 工程配置

项目为300+target大工程 rebuild耗时太长
目前正在实现sharedpch加速编译

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
看不懂你在说啥，多个问题不要混一起，一个问题一个 issues，并详细说明。
