### ISSUE TITLE
find_packages 在VS code下有bug

### ISSUE THREAD

**Issue by wangzhankun** [xmake-io/xmake#587]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题
平台：
Ubuntu 16.04
VS code 1.36.1

find_packages在VS code的终端下无法使用。具体表现如下，外部终端与VS code内置终端对比：
![image](https://user-images.githubusercontent.com/35724924/66313499-11133f00-e945-11e9-8a96-b4b2c580a15c.png)

同时可能由于find_packages的bug问题，可能会造成链接问题。可见我前天的问题，里面出现了链接的问题，怀疑有可能与此有关。https://github.com/xmake-io/xmake/issues/583#issuecomment-538649475

**Comment by waruqi** [comment]
看下你的vscode里面错误提示，很明显xmake.lua第一行没找到  add_syslink 。。你xmake.lua 里面没写对，是 add_syslinks 不是 add_syslink，只要是支持多值设置的Api，都会有s的后缀

**Comment by wangzhankun** [comment]
不是啊，我是執行的xmake l find_packages pthread, 在VScode終端下執行的就是這個指令，與外部終端執行的指令是一致的。

**Comment by waruqi** [comment]
正常的，目前只要是在xmake.lua所在的工程目录执行所有xmake xxx 命令，都会加载xmake.lua 包括xmake lua命令，因为xmake.lua里面也会去定义task，只有加载了xmake.lua 才能决定调用哪个task

如果要保证xmake l find_packages每次都会重新检测，不受cache和xmake.lua影响，就切到非工程目录执行就行了
