### ISSUE TITLE
希望支持ninja

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#588]
ninja编译速度快，希望支持

**Comment by waruqi** [comment]
近期可能没什么时间 先备着吧 有空了会考虑支持

**Comment by waruqi** [comment]
恩，目前的重点还是在自身构建效率改进上，回头可以看看ninja到底做了哪些优化措施，借鉴过来就好。

目前xmake已有的一些提速措施: 

1. 多任务编译，默认 4 job 
2. 增量编译
3. 对ccache的支持
4. linux下临时文件放置到/dev/shm

后期的一些规划

1. 内置跨平台的分布式编译，最近正在着手准备中
2. 内置实现类似ccache的功能，实现内置跨平台cache
3. xmake/lua自身损耗上的一些优化
4. 多任务这块还可以在改进下，目前多个不相关的target的link阶段还没做成多任务
5. 其他，可参考下ninja

**Comment by waruqi** [comment]
关于构建速度优化这块，我单独开了个issues，https://github.com/xmake-io/xmake/issues/589 后期可在这里跟进

**Comment by waruqi** [comment]
dev上，我对default jobs做了些改进，可以试试效果，详情见: https://github.com/xmake-io/xmake/issues/589#issuecomment-539771195

后面有时间会继续做一些其他的优化

**Comment by fasiondog** [comment]
确实，ninja不是目的，目的是提升编译速度

**Comment by Retia-Adolf** [comment]
Google 有个工具可以把 Makefile 转成 Ninja 格式：https://github.com/google/kati
所以如果能支持导入 Ninja 文件就好了，嗯……

**Comment by waruqi** [comment]
> Google 有个工具可以把 Makefile 转成 Ninja 格式：https://github.com/google/kati
> 所以如果能支持导入 Ninja 文件就好了，嗯……

xmake目前没太多时间精力去处理 第三方构建文件的 导入导出上，重点还是在把自身构建做完善，`xmake project`插件里面已经有makefile, vcproj, compile_commands,cmakelists的导出支持

ninja和xcode的导出，以及从其他文件的导入，如果大家有兴趣欢迎提pr在插件里面扩展支持。谢谢

**Comment by waruqi** [comment]
ninja的生成支持我dev加上了，目前测试对比下来，确实比xmake自身构建快了一倍，回头如果有时间我分析下，尝试进一步优化下构建效率，后续的优化进展在：https://github.com/xmake-io/xmake/issues/589 上跟进

```console
xmake update dev
xmake project -k ninja
```

**Comment by waruqi** [comment]
xmake的自身构建效率，我最近也提升了不少，基本上快逼近ninja了，回头我看看能否继续优化下。https://github.com/xmake-io/xmake/issues/589#issuecomment-593405044

**Comment by waruqi** [comment]
多进程并行调度策略这块我也改进过了，提升还是很明显的，现在已经很逼近ninja的速度了

唯一还需改进的地方是ninja的link全部挪到最后并行处理的，而xmake每个target间还是串行的 所以link时候会有停滞阻塞其他job构建

这块如果在重构改进下基本上效率可以跟ninja完全一致了。不过即使现在这样，也已经非常快了

可以先更新到dev试试
