### ISSUE TITLE
Imrpove missing package message

### ISSUE THREAD

**Issue by star-hengxing** [xmake-io/xmake#5882]
### Is your feature request related to a problem? Please describe.

              We should probably improve xmake tooltips when it doesn't find something (based on levenshtein distance for example) instead of adding fake packages

_Originally posted by @SirLynix in https://github.com/xmake-io/xmake-repo/issues/5691#issuecomment-2462449972_
            

### Describe the solution you'd like

https://github.com/xmake-io/xmake/blob/a9e8492bcc68823067d805a7ee666e99c08ad02f/xmake/modules/private/action/require/install.lua#L48-L54

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/pull/5889

```console
note: the following packages were not found in any repository (check if they are spelled correc
tly):
  -> cpu_features, maybe cpu-features v0.9.0 in local-repo
  -> tbo, maybe tbb 2021.12.0 in local-repo
```

**Comment by star-hengxing** [comment]
I want to remove some alias package from xrepo and has a problem:
```console
note: the following packages were not found in any repository (check if they are spelled correctly):
  -> onetbb, maybe onetbb nil in xmake-repo
```

**Comment by waruqi** [comment]
it works for me after removing onetbb.

```console
note: the following packages were not found in any repository (check if they
are spelled correctly):
  -> onetbb, maybe tbb 2022.0.0 in local-repo
error: package(onetbb) not found!
```
