### ISSUE TITLE
Package version range auto-resolve

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake#5890]
### 你在什么场景下需要该功能？

在dartsim中若设置add_deps("python 3.11.x")，其依赖的pybind11设置为`add_deps("python 3.x")`，则会报错

```
package(python/3.x:{"runtimes=MT"}): conflict dependencies with package(python/3.11.x:{"runtimes=MT"}) in dartsim!
```
但实际上这里3.11.x被3.x包含，并非冲突关系

### 描述可能的解决方案

利用symver的求交，在出现多个version范围时求其中交集作为实际version范围，如果没有交集再报错 conflict version

**Comment by waruqi** [comment]
重复了，等这个 https://github.com/xmake-io/xmake/issues/5745

**Comment by star-hengxing** [comment]
自动合并包还要做版本解析才能分析吧 https://github.com/xmake-io/xmake/issues/4486

**Comment by waruqi** [comment]
可以了，再试试 https://github.com/xmake-io/xmake/pull/5901  

version 能自动解析了
