### ISSUE TITLE
增加关闭检测 toolchain 的全局接口

### ISSUE THREAD

**Issue by gycherish** [xmake-io/xmake#5891]
### Is your feature request related to a problem? Please describe.

我准备用 xmake 管理一些依赖，项目中的 target 都是伪目标，且都自定义了编译步骤，没有真正需要编译的 target，本地也没有安装相关 toolchain，但是 xmake 运行时会首先检测 toolchain，检测不到就报错了：
![image](https://github.com/user-attachments/assets/ef5dcbab-e009-40b8-a9a2-db39767db29b)

### Describe the solution you'd like

增加一个全局接口，关闭 toochain：
set_toolchains("none")

**Comment by waruqi** [comment]
关不了，自己 `xmake f --toolchain=` 切下
