### ISSUE TITLE
Support `merge_staticlib` for static kind package

### ISSUE THREAD

**Issue by star-hengxing** [xmake-io/xmake#5894]
### Is your feature request related to a problem? Please describe.

A new policy, `package.merge_staticlib`, can be used for libraries like abseil that have many sub-libraries(86+), let xmake merge into a single static library.

### Describe the solution you'd like

N/A

**Comment by waruqi** [comment]
大概实现了，https://github.com/xmake-io/xmake/pull/5927

不过 .pc/.cmake 的导入文件没法处理，库名换了，可能会影响其他库去 find package，像 abeils 这种，一堆的 .pc ，不太适用
