### ISSUE TITLE
QML Plugin 目标构建失败

### ISSUE THREAD

**Issue by Doekin** [xmake-io/xmake#5900]
### Xmake 版本

xmake v2.9.6+HEAD.abd15c255

### 操作系统版本和架构

Arch Linux 

### 描述问题

构建示例项目 [quickplugin example](https://github.com/xmake-io/xmake/tree/master/tests/projects/qt/quickplugin) 时 coredump
![71c960d2f6ab6d935e6c377c7fcb430](https://github.com/user-attachments/assets/89a2b9ef-0555-4317-a882-98805c3acc88)

### 期待的结果

正常构建 QML Plugin

### 工程配置

与示例项目一致，Qt 版本为 6.8.0
```
add_rules("mode.debug", "mode.release")

target("demo")
    add_rules("qt.qmlplugin")
    add_headerfiles("src/*.h")
    add_files("src/*.cpp")

    set_values("qt.qmlplugin.import_name", "My.Plugin")
```

### 附加信息和错误日志

问题很可能产生于
https://github.com/xmake-io/xmake/blob/7a545f48f4c3bc9c21f46d22df8562756d9894cc/xmake/rules/qt/qmltyperegistrar/xmake.lua#L121C1-L124C12
当`qt.qmlplugin.qmldirfile` 未设定时，`qmldir`= `target:scriptdir()` ，继而 if 判断为真，尝试将 `target:scriptdir()` 复制到 `target:targetdir()` ，循环复制产生 coredump

**Comment by waruqi** [comment]
可以直接来个 pr 过来

**Comment by Doekin** [comment]
把 if 的判断条件由  `qmldir`  改为 `target:values("qt.qmlplugin.qmldirfile")` 可以解决这一问题
不过在Windows 上构建还有点问题，需要进一步确认
