### ISSUE TITLE
the xmake command will disappear on restarting terminal(macisx)

### ISSUE THREAD

**Issue by RPG3D** [xmake-io/xmake#591]
step:
1.open terminal on the project direcotry;
2.run bash <(curl -fsSL https://raw.githubusercontent.com/xmake-io/xmake/master/scripts/get.sh);
3.run xmake build binary;
4.close terminal, open termianl again, run xmake, get errors, xmake is not a valid command

**Comment by waruqi** [comment]
what is your shell name and os? It will append profile to `~/.bashrc`, `~/.zshrc` or ~/.profile after  installing.

https://github.com/xmake-io/xmake/blob/d7a10b512c94a58b0047d937fd25e44911d6a991/scripts/get.sh#L198-L204

You can also run `source ~/.xmake/profile` to set xmake environment.
