### ISSUE TITLE
能否支持nuget的包

### ISSUE THREAD

**Issue by heheda123123** [xmake-io/xmake#5911]
### 你在什么场景下需要该功能？

有挺多项目使用nuget的形式下发，有些包单独有写包描述加到xrepo仓库里，
但是还有些比较复杂，官方提供的手动方式也需要把props文件加到项目，如果支持nuget就可以直接引入
https://github.com/MiroKaku/ucxxrt/blob/main/README.zh-CN.md
https://github.com/MiroKaku/Musa.Runtime/blob/main/README.zh-CN.md
https://github.com/Chuyu-Team/VC-LTL5/blob/master/Readme.osc.md

### 描述可能的解决方案

把nuget作为类似于brew/vcpkg同样的包管理器

**Comment by waruqi** [comment]
直接 `add_requires("nuget::xxx")` 么。直接走描述 port 过去，工作量大也没必要。

可以提 pr 到这里，https://github.com/xmake-io/xmake/tree/dev/xmake/modules/package/manager

**Comment by waruqi** [comment]
加上了 https://github.com/xmake-io/xmake/pull/5981

```lua
add_requires("nuget::zlib_static", {alias = "zlib"})

target("test")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("zlib")
```
