### ISSUE TITLE
依赖包的 package::check_cxxsnippets 不支持使用 clang/libcxx 测试

### ISSUE THREAD

**Issue by Redbeanw44602** [xmake-io/xmake#5916]
### Xmake 版本

v2.9.6+20241030

### 操作系统版本和架构

Manjaro Linux

### 描述问题

如果将依赖包的 stdlib 切换为 libc++
```lua
local opt = {
    configs = {
        toolchains = 'clang',
        cxflags = {
            '-stdlib=libc++'
        }
    }
}

add_requireconfs('**|cmake|pkg-config', opt)
```

当依赖包在执行 on_test 时，依然使用 libstdc++ 进行测试，往往会因 abi 不兼容导致测试失败。

### 期待的结果

测试成功

考虑自动选择 on_test 使用的工具链/标准库实现？

### 工程配置

N/A

### 附加信息和错误日志

![图片](https://github.com/user-attachments/assets/16508f9f-c21d-421e-bb4b-8c0a43f6c6fb)

**Comment by star-hengxing** [comment]
用 `set_runtimes("c++shared")` 才会透传到包构建和测试，加上后再给 -vD log 看看。

**Comment by waruqi** [comment]
你要自己走 runtimes 切下。 `xmake f --runtimes=c++_shared` 或者全局 set_runtimes("c++_shared")
