### ISSUE TITLE
add_linkgroups whole失效

### ISSUE THREAD

**Issue by Dozingfiretruck** [xmake-io/xmake#5922]
### Xmake 版本

2.9.6

### 操作系统版本和架构

win10

### 描述问题

add_linkgroups whole失效
![image](https://github.com/user-attachments/assets/ac863e14-af0d-43e2-9053-4d1a88f0640e)
![image](https://github.com/user-attachments/assets/a7703bbd-abe3-4734-b8e1-03ecf210be6e)
只有group没有whole

### 期待的结果

whole正常

### 工程配置

![image](https://github.com/user-attachments/assets/ac863e14-af0d-43e2-9053-4d1a88f0640e)

### 附加信息和错误日志

![image](https://github.com/user-attachments/assets/ac863e14-af0d-43e2-9053-4d1a88f0640e)
![image](https://github.com/user-attachments/assets/a7703bbd-abe3-4734-b8e1-03ecf210be6e)

**Comment by waruqi** [comment]
写法不对，`{whole = true, group = true}` ，为啥你会整两个 `{}` block 呢，这样只有最后一个才是扩展配置。

**Comment by Dozingfiretruck** [comment]
> 写法不对，`{whole = true, group = true}` ，为啥你会整两个 `{}` block 呢，这样只有最后一个才是扩展配置。

脑子瓦特了。。。
