### ISSUE TITLE
脚本域复制命令问题

### ISSUE THREAD

**Issue by 1143910315** [xmake-io/xmake#5930]
### Xmake 版本

2.9.6+HEAD.abd15c255

### 操作系统版本和架构

Windows 10 专业版 22H2 19045.5011

### 描述问题

我在脚本域使用os.cp出现复制歧义。
我的目的是复制npm构建后的dist复制到构建目录build\windows\x64\debug下。
但是这个os.cp存在一个问题。
在build\windows\x64\debug目录下没有dist目录的时候，会复制成build\windows\x64\debug\dist\构建文件
在经过一次on_build后，这时候build\windows\x64\debug\dist会存在，这时候os.cp的行为变成了build\windows\x64\debug\dist\dist\构建文件。

### 期待的结果

我期待的结果是，执行
```lua
os.cp("$(scriptdir)/dist", target:targetdir().."/dist")
```
时，行为应该是判断$(scriptdir)/dist是目录，target:targetdir().."/dist"没有以/结尾，应该是源目录的dist重命名为目标目录的dist，而不是在dist存在的时候，将源目录的dist复制到目标目录的dist下

### 工程配置

target("ui")
    on_build(function (target)
        local oldir = os.cd(os.scriptdir())
        os.run("npm.cmd run build")
        os.cp("$(scriptdir)/dist", target:targetdir().."/dist")
        os.cd(oldir)
    end)

### 附加信息和错误日志

没有日志

**Comment by star-hengxing** [comment]
脚本域用 `os.scriptdir()`

**Comment by waruqi** [comment]
> 在build\windows\x64\debug目录下没有dist目录的时候，会复制成build\windows\x64\debug\dist\构建文件
在经过一次on_build后，这时候build\windows\x64\debug\dist会存在，这时候os.cp的行为变成了

这不是很正常么，一开始目录 dist 不存在，当然直接复制成 dist 了。

后来 dist 存在了，如果还要按你说的行为，那得把 目的已有的 dist 整个删了，重新复制替换。。但这回误删很多文件。

如果你要增量复制。那应该是 `os.cp("dist/*", "debug/dist/")` 走通配符才对，而不只是 `os.cp("dist")`，你现在整个目录 copy ，按你说的 肯定会干翻目的目录。只能复制到 debug/dist/ 下，变成 `debug/dist/dist`

**Comment by waruqi** [comment]
即使系统 cp 目前也是 os.cp 的行为

```console
ruki-2:tmp ruki$ mkdir foo
ruki-2:tmp ruki$ touch foo/a
ruki-2:tmp ruki$ touch foo/b
ruki-2:tmp ruki$ cp -r foo dist
ruki-2:tmp ruki$ tree dist
dist
├── a
└── b

0 directories, 2 files
ruki-2:tmp ruki$ cp -r foo dist
ruki-2:tmp ruki$ tree dist
dist
├── a
├── b
└── foo
    ├── a
    └── b

1 directory, 4 files
```
