### ISSUE TITLE
Add packages through Option

### ISSUE THREAD

**Issue by TabNahida** [xmake-io/xmake#5932]
### Is your feature request related to a problem? Please describe.

Add a package through ``option``. You can use the to choose which package to implement some functions.

### Describe the solution you'd like

```lua
option("test")
    ...
    add_requires("boost")
option_end()

target("TEST")
    ...
    set_options("test")
target_end()
```

**Comment by waruqi** [comment]
不知道你要改啥，走 has_config 原本就能 option 条件添加，

```
option("xxx")
  -- ...

if has_config("xxx") then
    add_requires("xxx")
end
```

**Comment by TabNahida** [comment]
> 不知道你要改啥，走 has_config 原本就能 option 条件添加，
> 
> ```
> option("xxx")
>   -- ...
> 
> if has_config("xxx") then
>     add_requires("xxx")
> end
> ```

我知道啊，不能封装一下？我感觉用脚本的方式很丑

**Comment by waruqi** [comment]
自己封装，外面自己 function wrap 下也没几行代码，不要想着什么都内置封装，用户各种需求，哪有都要 xmake 内置的。
