### ISSUE TITLE
xmake update 后，原项目编译报错

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#594]
![图片](https://user-images.githubusercontent.com/1145161/66804761-ec772280-ef55-11e9-8bda-29abd362b56e.png)
xmake update 升完级原有工程就报错（master、dev都一样），退回2.2.8就行。（公司项目没法提供更多信息了）
其他项目（hikyuu）又没有问题，可以正常编译

**Comment by waruqi** [comment]
dev重构过一些代码，可能会有些不稳定，等晚上我看下。。

**Comment by waruqi** [comment]
这个问题比较怪，能否帮忙更新到dev后，在出错的target里面加个on_load，帮忙打印一些调试信息，给我看下，不会涉及到项目本身信息。

```lua

on_load(function (target)

    print("----------- language rules --------------")
    import("core.language.language")
    local lang = language.load_ex(path.extension("xxx.cpp"))
    if lang then
        print(lang:rules())
    end

    print("----------- target rules --------------")
    for _, r in pairs(target:rules()) do
        print(r:name(), r:get("extensions"))
    end
end)
```

**Comment by fasiondog** [comment]
![图片](https://user-images.githubusercontent.com/1145161/66880983-d883fd00-eff7-11e9-9556-2fe9820234cc.png)

里面"target xxx: loading yihua.rules ...." 是我这边在自定义的rules里after_load加的

**Comment by waruqi** [comment]
怪了，感觉target内置的c++.build rule没了，被覆盖了

你是用add_rules添加的规则，还是set_rules?

**Comment by fasiondog** [comment]
add_rules

**Comment by fasiondog** [comment]
![图片](https://user-images.githubusercontent.com/1145161/66882405-d40e1300-effc-11e9-80a4-af48d2bfa0fc.png)
我再 rules 里的 before_load 中，target:add("options"，....） 了下，会不会有影响

**Comment by waruqi** [comment]
```lua
on_load(function (target)

    print("----------- language rules --------------")
        local rulenames = {}
        table.join2(rulenames, t:get("rules"))
        for _, sourcefile in ipairs(table.wrap(t:get("files"))) do
            local lang = language.load_ex(path.extension(sourcefile))
            print("ex: %s, lang: %s", path.extension(sourcefile), lang:name())
            if lang and lang:rules() then
                print("add lang rule")
                table.join2(rulenames, lang:rules())
            end
        end
       print("-------- rulenames ----------- ")
       print(rulenames)
       print("-------- get ----------- ")
        for _, rulename in ipairs(rulenames) do
            local r = project.rule(rulename) or rule.rule(rulename)
            if r then
                  print("r: %s", r:name())
            end
        end
   ```

能否帮忙再dump下。。

**Comment by fasiondog** [comment]
![图片](https://user-images.githubusercontent.com/1145161/66882969-e1c49800-effe-11e9-8f0c-7e02b37ed30e.png)

**Comment by waruqi** [comment]
哦，我大概知道原因了，dev我重构过一次build rules， 把所有c/c++等原生构建规则全部抽离到独立的c++ rules中区，方便后续扩展维护。。

在探测target的builti rules时候，对files的过滤文件模式忘记处理了。。。所以对于 `add_files("src/*.cpp|ios/**") ` 这种就找不到c++ rules了。。

等我回头处理好，你再试试。

**Comment by fasiondog** [comment]
牛！ 好的，3Q

**Comment by waruqi** [comment]
你执行这个命令，从github dev更新下脚本后再试试，应该可以了。。xmake update -s github:xmake-io/xmake#dev

等晚上我再更新其他repo mirror

**Comment by fasiondog** [comment]
![图片](https://user-images.githubusercontent.com/1145161/66889584-8fdb3c80-f015-11e9-8f0c-4454dfb95887.png)

**Comment by waruqi** [comment]
xmake update github:xmake-io/xmake#dev 去掉 -s ，编译更新下   c core dev上也改了，有新的native api调用

**Comment by waruqi** [comment]
我同步上去了，你可以执行 xmake update dev 拉取整个安装包重装下，就不会有这个错误了。。你试试

**Comment by fasiondog** [comment]
OK, 正常
