### ISSUE TITLE
增加运行时类型识别的开关 (RTTI)

### ISSUE THREAD

**Issue by AhMisty** [xmake-io/xmake#5951]
### 你在什么场景下需要该功能？

使用MSVC编译器时，设置add_cxflags("-fno-rtti")不能正确地转换为"/GR-"，能否添加一个内置方法关闭运行时类型识别

### 描述可能的解决方案

添加内置方法如set_rtti("none")以关闭运行时类型识别

**Comment by waruqi** [comment]
为啥不直接 `add_cxflags("/GR-")`

**Comment by AhMisty** [comment]
这样不是还需要判断编译器来判断输入的flag吗

**Comment by waruqi** [comment]
> 这样不是还需要判断编译器来判断输入的flag吗

根据平台判断

```lua
if is_plat("windows") then
end
```

或者约束编译器

```lua
add_cxflags("cl::/GR-")
```

或者直接裸写，写全，反正会自动检测，不支持的 Flags 自动会忽略

```lua
add_cxflags("/GR-")
```

不要想着遇到个 flags，就希望 xmake 内置抽象，这么多 flags 了，不可能每个都这么来一遍，提供 add_cxflags 就提供用于自己配置 flags 灵活性。

**Comment by AhMisty** [comment]
好的
