### ISSUE TITLE
xmake require -f -v -D xxxx 无法强制 clone 只有 git 地址的依赖包

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#596]
如题

**Comment by waruqi** [comment]
哦 回头我看下

**Comment by waruqi** [comment]
我看了下，不管是git还是zip包。。--force 只是强制重装，但是clone下来的repo 以及下载下来的zip包，如果已经存在， 则还是会复用，因为没必要重新再去下载一遍。。zip包下载过一次后，sha256验证通过，重新force去重下载没必要

而clone下来的库也是，如果clone中途失败，repo库会回退，git自己能够保证完整性，也没必要重下。

而之前老版本不支持clone submodule, dev已经支持，也没必要再去重新clone了。。

如果确实像重新clone/download已经缓存的包，可以执行xmake require --clean 清除下 cache 后，在执行安装

```console
xmake require --clean
xmake require -f -v xxx
```

就会强制重下

**Comment by fasiondog** [comment]
另外，问下，clone 有没有办法像下载那样通过版本指定分支？

**Comment by waruqi** [comment]
> 另外，问下，clone 有没有办法像下载那样通过版本指定分支？

```lua
-- 从分支拉
add_requires("tbox dev")
add_requires("tbox master")

-- 如果版本是分支，也可以直接clone后，checkout到对应版本分支
add_requires("tbox v1.6.4")
```

**Comment by fasiondog** [comment]
好的，3Q

**Comment by OpportunityLiu** [comment]
git历史。。。不是任人打扮的小姑娘吗？别说分支和Tag了，提交都可以随便改。。。

**Comment by waruqi** [comment]
> git历史。。。不是任人打扮的小姑娘吗？别说分支和Tag了，提交都可以随便改。。。

xmake-repo 里面可以指定 commit 号 来对应某个版本的。。来校验修改。

如果指定从master/dev这种分支拉取，xmake-repo里面 指定的都是 包对应的官方仓库，只能假设这些官方git源自己保证安全性和编译可靠性了。。当然如果master上他们大改了，比如构建工具换了，这里安装脚本没更新，确实有可能导致安装失败，这种既然用户选择 从 master 拉取包，而不是指定版本，就应该自己有这个心理准备。

不过一般官方xmake-repo仓库，我都会加上 tar/gz包源，如果存在都是优先从这个上拉取的。。有sha256校验，git源只是作为用户想要手动选择从dev/master分支拉取时候 准备的
