### ISSUE TITLE
使用c++ module编译内部库生成vs项目，static正常使用，shared编译过不去

### ISSUE THREAD

**Issue by sunsmart96** [xmake-io/xmake#5969]
### Xmake 版本

2.8.1

### 操作系统版本和架构

windows11

### 描述问题

在window 下使用xmake c++ module的时候，如果内部库是static生成的vs项目可以正常编译使用，但是如果把内部库设置成shared就没法编译

### 期待的结果

可以正常编译运行

### 工程配置

整个项目配置

add_rules("mode.debug", "mode.release")

set_languages("c11", "c++23")

target("library")
    set_kind("shared")
    add_files("src/*.ixx")

target("test1")
    set_kind("binary")
    set_policy("build.c++.modules", true)
    add_deps("library")
    add_files("src/*.cpp")

去生成vs2022项目，如果libray是static的可以正常使用，但是如果配置成shared就编译不过去

mian.cpp

import std;
import sort;

int main(int argc, char **argv) {
  add(1, 2);

  return 0;
}

sort.ixx

export module sort;

import std;

export int add(int a, int b)
{
    return a + b;
}

### 附加信息和错误日志

<img width="1026" alt="屏幕截图 2024-12-15 165129" src="https://github.com/user-attachments/assets/7e46fa9f-e9c9-47a7-8e35-a5cf9fde89c9" />

**Comment by sunsmart96** [comment]
所有编译子模块为动态库的形式都编译不过去，说打不开lib文件

**Comment by waruqi** [comment]
> 所有编译子模块为动态库的形式都编译不过去，说打不开lib文件

你没导出符号，这个跟 modules 也没啥关系吧。msvc 下只有你导出了符号，才会自动生成 dll 对应的 lib 导入库

**Comment by sunsmart96** [comment]
> > 好的，了解
