### ISSUE TITLE
macosx/iOS需要支持从XCode的里SDK/usr/lib中去find_packages

### ISSUE THREAD

**Issue by L1MeN9Yu** [xmake-io/xmake#598]
## 现状

在Apple的平台下，find_packages目前只支持从`/usr/lib/`,`/usr/local/`等目录中查找。

## 存在的问题

从Xcode10开始，Command Line Tools将安装在Xcode的目录中，[xcode_10_release_notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes)。
所以当 platforn=macosx 时，只能通过安装 system wide Command Line Tools 或者 brew 安装的方式去 link 需要的 lib ，当 platforn=iOS 时，貌似无法 link 到需要的lib了（因为iOS系统版本的不一致，系统中的 lib 版本也存在着差异，所以一般尽量选择使用系统内的 lib）。

## Feature request

1. 支持从 Xcode 的 SDK 目录中 find_packages.
2. 支持tbd格式的 lib.

**Comment by L1MeN9Yu** [comment]
理论上 `LDFlags` 应该是直接支持 `tbd` 格式的吧？

**Comment by waruqi** [comment]
默认link ，只要加了 add_links("zlib") 都会自动从系统link的，你得说清楚，是find_packages默认不支持xcode找tbd的库。。

**Comment by waruqi** [comment]
dev上我已经对 macos/iphoneos xcode sdk下 *.tbd的查找做了支持，你可以更新下试试，xmake update dev

xmake l find_packages zlib的查找顺序：

1. homebrew
2. pkg-config
3. /usr and /usr/local
4. macos xcode sdk / *.tbd

并且如果是iphoneos/watchos下编译， 也可以找到对应arch的库

**Comment by L1MeN9Yu** [comment]
![image](https://user-images.githubusercontent.com/6925196/67350772-55762000-f57e-11e9-92c9-277d4a549660.png)

![image](https://user-images.githubusercontent.com/6925196/67350895-b7368a00-f57e-11e9-803c-1994a5189de6.png)

看起来还是没找到。。。

**Comment by waruqi** [comment]
你执行下 xmake l find_packages system::zlib 或者 xmake l find_packages system::z 看看呢

由于zlib无法直接通过libzlib.a 来获取库名，目前是先通过 pkg-config 获取到 z ，然后去找 libz.a的。。

可能你这pkg-config无法通过zlib获取到 z link ，你可以先手动试试 xmake l find_packages system::z

**Comment by L1MeN9Yu** [comment]
``` bash
xmake l find_packages system::z

{
  {
    links = {
      "z"
    },
    linkdirs = {
      "/usr/lib"
    }
  }
}
```

**Comment by waruqi** [comment]
那就是你这 pkg-config zlib 找不到 导致没获取到 z ，这个要特殊处理下 find_zlib.lua ，回头我改进下，但是不影响其他 lib 在 tbd中的查找。

**Comment by L1MeN9Yu** [comment]
OK
那可以指定find_packages的本地路径吗？

**Comment by waruqi** [comment]
find_packages("xxx", {includedirs = {"xxx", "xxx"}, linkdirs = {"xxx", "xxx"}})

**Comment by L1MeN9Yu** [comment]
``` bash
xmake l find_packages zlib

{
  {
    links = {
      "z"
    },
    linkdirs = {
      "/usr/lib"
    }
  }
}
```

赞~
