### ISSUE TITLE
luajit.h: No such file or directory

### ISSUE THREAD

**Issue by stsp** [xmake-io/xmake#599]
### Describe the bug
builds fails not finding luajit.h.

### Expected behavior
builds

### Error output
```
lcurses.c:68:10: fatal error: luajit.h: No such file or directory
   68 | #include "luajit.h"
      |          ^~~~~~~~~~
compilation terminated.
```

### Related Environment

xmake sources from git
Ubuntu 19.10

### Additional context
```
$ ls -l /usr/include/luajit-2.1/luajit.h
-rw-r--r-- 1 root root 2873 окт 25  2017 /usr/include/luajit-2.1/luajit.h
```

luajit.h is present, but it must be properly prefixed.

**Comment by waruqi** [comment]
Please let me see your xmake.lua

**Comment by OpportunityLiu** [comment]
git submodule update --init

**Comment by waruqi** [comment]
If you are compiling the xmake source, you need to pull git submodules first.

**Comment by stsp** [comment]
Thanks!
I wonder if some hint can be printed,
or maybe even some make target could
do it automatically...
