### ISSUE TITLE
support zig cc -target 

### ISSUE THREAD

**Issue by jimying** [xmake-io/xmake#5990]
### Is your feature request related to a problem? Please describe.

- support  `zig cc -target x86_64-linux-gnu`
- support `zig cc -target x86_64-linux-gnu.2.18`   specify glibc version 2.18

### Describe the solution you'd like

error build c++ hello project
```
export tgt=x86_64-linux-gnu.2.18
xmake f --cc="zig cc -target $tgt"  --cxx="zig c++ -target $tgt" --ld="zig c++ -target $tgt" -c
xmake
```
error:
```
error: cannot find known tool script for zig c++ -target x86_64-linux-gnu.2.18
```

**Comment by waruqi** [comment]
```console
xmake f --toolchain=zig
xmake
```

**Comment by waruqi** [comment]
switch to cross platform. https://github.com/xmake-io/xmake/blob/ca53159567407c93e948c265fa9c36fbcb1752bc/xmake/toolchains/zig/xmake.lua#L129

```console
xmake f -p cross --toolchain=zig --cross=mips64el-linux-gnuabi64
```

**Comment by waruqi** [comment]
Afterwards, zigcc will need a separate zigcc toolchain; zig and zigcc will be split into two independent toolchains. (https://github.com/xmake-io/xmake/pull/7383)
