### ISSUE TITLE
为何 添加 LLVM时 , xmake 构建无法自动下载依赖

### ISSUE THREAD

**Issue by Super1Windcloud** [xmake-io/xmake#6004]
### Xmake Version

2.9.7

### Operating System Version and Architecture

win11  

##  我添加其他库都能正常下载依赖,  但是 LLVM不行 

![image](https://github.com/user-attachments/assets/26736eba-b2cb-4e65-8431-7599b1dd7401)

### Expected Behavior

![image](https://github.com/user-attachments/assets/330c147f-e1f2-4acf-9349-60f6e24867c0)

### Project Configuration

.

### Additional Information and Error Logs

.

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-repo/issues/1802#issuecomment-1426058217
