### ISSUE TITLE
Add `xmake format` plugin task to format xmake.lua 

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#601]
format xmake.lua by lua syntax in project.

Roadmap

- [ ] format custem lua script  
- [ ] format scope()/scope_end() block

Lua format tools

 - https://github.com/Koihik/LuaFormatter
 - clang-format?

**Comment by OpportunityLiu** [comment]
这真能搞得出来？

**Comment by waruqi** [comment]
不知道 还只是想法，不知道clang-format支持lua不，先尝试对lua进行常规format下，clang-format不支持，就换其他format tools试试。

**Comment by OpportunityLiu** [comment]
问题的关键难道不是xmake.lua根本不是lua吗？
lua的format没法理解一个函数调用后面所有语句开始缩进是咋回事…………

**Comment by waruqi** [comment]
> 问题的关键难道不是xmake.lua根本不是lua吗？
> lua的format没法理解一个函数调用后面所有语句开始缩进是咋回事…………

这个我也想过了，提xmake format我也是主要为了format域设置这块的缩进，不过这块可以先不用管，可以先集成LuaFormatter后做些基础lua语法的format，对自定义脚本里面的lua代码format下

而后面的target等域设置的缩进，可以后面加上支持，比如尝试改改 LuaFormatter 里面的实现，做个定制化的版本。

**Comment by OpportunityLiu** [comment]
应该把 `add_files` 和 `add_headers` 包含的文件也格式化掉吧，这个才是clang-format应该干的事情。

之后再考虑xmake.lua

**Comment by OpportunityLiu** [comment]
直接搞LSP吧，搞出来就啥都有了

**Comment by waruqi** [comment]
恩，回头有时间也可以考虑整下

**Comment by waruqi** [comment]
想想，搞个单独的 `xmake format` 也没啥意义，大部分用户都还是借助 编辑器/ide 自带的格式化，很少会用命令行的工具。。除非搞 lsp ，有点折腾。

我看有人这么配置，也能多少解决部分缩进问题

```lua
target("test") do
    set_kind("binary")
    add_files("src/*.c")
end
```

不过这样，还是没有真正结束作用域，有些场景还是要用 target_end 显式结束


```lua
target("test") do
    set_kind("binary")
    add_files("src/*.c")
end target_end()
```

虽然有点别扭，还自己个人对缩进和格式化的需求吧，像我通常都是手打缩进，也不需要格式化。

**Comment by fcying** [comment]
要是有个api 文件, 能当个library接入现在的lua lsp也挺好的.

**Comment by waruqi** [comment]
实现这个，还不如直接改进配置语法。。新搞了个可选的配置语法：https://xmake.io/#/zh-cn/guide/syntax_description?id=%e5%8f%af%e9%80%89%e7%9a%84%e5%9f%9f%e9%85%8d%e7%bd%ae%e8%af%ad%e6%b3%95

```lua
add_defines("ROOT")

target("foo", function ()
    set_kind("binary")
    add_files("src/*.cpp")
    add_defines("FOO")
end)

target("bar", function ()
    set_kind("binary")
    add_files("src/*.cpp")
    add_defines("BAR")
end)
```

不仅对 LSP 友好，支持自动格式化缩进，并且还自动设置了 `target_end()` 实现域隔离，两个 target 定义之间，可以随意配置其他的全局配置，不再干扰。

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/pull/3049

**Comment by AzarAI-TOP** [comment]
> 实现这个，还不如直接改进配置语法。。dev 上新搞了个可选的配置语法：https://xmake.io/#/zh-cn/guide/syntax_description?id=%e5%8f%af%e9%80%89%e7%9a%84%e5%9f%9f%e9%85%8d%e7%bd%ae%e8%af%ad%e6%b3%95
> 
> add_defines("ROOT")
> 
> target("foo", function ()
>     set_kind("binary")
>     add_files("src/*.cpp")
>     add_defines("FOO")
> end)
> 
> target("bar", function ()
>     set_kind("binary")
>     add_files("src/*.cpp")
>     add_defines("BAR")
> end)
> 不仅对 LSP 友好，支持自动格式化缩进，并且还自动设置了 `target_end()` 实现域隔离，两个 target 定义之间，可以随意配置其他的全局配置，不再干扰。

这个确实实际性地解决了我目前的问题， 多谢指教
