### ISSUE TITLE
在Wsl的情况下找不到vcpkg命令

### ISSUE THREAD

**Issue by Ultraman95** [xmake-io/xmake#602]
直接使用vcpkg没有问题
如果使用xmake build，则找不到vcpkg

![image](https://user-images.githubusercontent.com/1725360/67381200-21baea80-f5be-11e9-98d9-7c0975fbbc9f.png)

**Comment by waruqi** [comment]
先确认下，有没有根据文档集成vcpkg，https://xmake.io/#/zh-cn/package/system_package?id=%e6%9f%a5%e6%89%bevcpkg%e5%8c%85

需要先执行vcpkg integrate install集成，或者设置xmake f --vcpkg才能找到
