### ISSUE TITLE
通过vcpkg安装的静态库如何被使用

### ISSUE THREAD

**Issue by Ultraman95** [xmake-io/xmake#603]
如果xxx是静态库
add_requires("vcpkg::xxx")
add_packages("vcpkg::xxx")
只是这样好像不起作用

**Comment by waruqi** [comment]
请根据创建issues时候的模板提示，提供完整的xmake.lua内容，以及详细的执行输出和其他辅助信息。。

否则不清楚你这到底是啥情况，语法进一步分析问题

**Comment by Ultraman95** [comment]
main.cpp

#include <iostream>
#include <string>
#include <vector>
#include "absl/strings/str_cat.h"

using namespace std;

int main(int argc, char** argv)
{
	cout << "hello world!" << endl; 
	std::string s1;
	int i = 255;
	s1 = absl::StrCat("hello 0x", absl::Hex(i)); 
	std::cout << s1 << std::endl;

	s1 = absl::StrCat("hello 0x", absl::Hex(i, absl::kZeroPad4)); 
	std::cout << s1 << std::endl;

	s1 = absl::StrCat("hello 0x", absl::Hex(i, absl::kSpacePad4)); 
	std::cout << s1 << std::endl;
	return 0;
}


xmake.lua

add_rules("mode.debug", "mode.release")

add_requires("vcpkg::abseil")

-- add target
target("test")

    -- set kind
    set_kind("binary")

    -- add files
    add_files("src/*.cpp") 
	
    add_packages("vcpkg::abseil")

**Comment by Ultraman95** [comment]
错误信息：
![image](https://user-images.githubusercontent.com/1725360/67446434-2d9cc000-f643-11e9-9a25-24413eee1669.png)

**Comment by Ultraman95** [comment]
改成这样add_requires("vcpkg::abseil", {configs = {vs_runtime = "MT"}})，也不行

**Comment by waruqi** [comment]
目前vs_runtime还不支持传递到vcpkg，只支持对xmake-repo官方repo下包的处理，我回头试试传递到vcpkg下看看，目前vcpkg默认安装都是md的，你可以先在自己工程里面 改成md试试。。

等我后两天把vcpkg/MT的支持加上后，你再试下

**Comment by Ultraman95** [comment]
好的

**Comment by Ultraman95** [comment]
vcpkg在windows下基本上是默认安装动态库，abseil这个库特殊，如果用vcpkg install安装，会是静态库。vcpkg在linux下基本上是默认安装静态库的

**Comment by waruqi** [comment]
xmake 也是内部直接调用的vcpkg install 安装 没特别处理，理论上应该是一样的

**Comment by waruqi** [comment]
> 改成这样add_requires("vcpkg::abseil", {configs = {vs_runtime = "MT"}})，也不行

vs_runtime 的设置我支持了，如果不设置，vs_runtime 默认也是MT ，所以只有需要使用MD的时候，才需要设置MT

add_requires("vcpkg::abseil")     
-> 默认MT，执行的 vcpkg install abseil:x64-windows-static

add_requires("vcpkg::abseil", {configs = {vs_runtime = "MD"}})
-> 手动切到MD，执行的 vcpkg install abseil:x64-windows

可以看下 msdn里面的描述：https://blogs.msdn.microsoft.com/c/2016/12/14/vcpkg%e6%9b%b4%e6%96%b0%ef%bc%9a%e9%9d%99%e6%80%81%e9%93%be%e6%8e%a5/

> 请注意:所有的在*-windows-static triplets 参数里面的libraries 都是根据静态CRT(/MT 或者/MTd)进行链接的，所以你将需要改变你的CMAKE_CXX_FLAGS (请查看http://stackoverflow.com/questions/14172856/cmake-compile-with-mt-instead-of-md)

如果要使用vcpkg 的MT版本库，需要install 带 -static后缀的库版本，而这块，xmake的dev版本里面，我刚已经内置做了自动处理，只需要设置vs_runtime，就可以随意切换vcpkg的安装库MT/MD

你可以更新下xmake到dev试试，xmake update dev  （ci上还在build，请过上10几分钟后在执行更新命令。）

**Comment by waruqi** [comment]
可以了么？
