### ISSUE TITLE
正常的静态库，也无法使用

### ISSUE THREAD

**Issue by Ultraman95** [xmake-io/xmake#604]
xmake.lua

-- add modes: debug and release 
add_rules("mode.debug", "mode.release")

add_defines("_WIN32_WINNT=0x600")

    -- add target
    target("test")

    -- set kind
    set_kind("binary")

    -- add files
	add_includedirs("src/")
	add_includedirs("generated/")
	add_includedirs("C:/Tools/vcpkg/installed/x64-windows/include/")
        add_files("src/*.cpp")
	add_files("generated/*.cc")
	
	
	add_linkdirs("C:/Tools/vcpkg/installed/x64-windows/lib/")
	add_links("grpc++_unsecure")
	add_links("libprotobuf")
	add_links("ws2_32")

grpc++_unsecure.lib这个库是个静态库

-----错误信息-----------
error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(hello_server_impl.cpp.obj
中)

**Comment by waruqi** [comment]
mt md不匹配哈，test是mt的 库是md的 当然有这问题了 跟xmake没啥关系。。你自己add_ldflags 设置下runtime flags -MT -MD，保证两边一致就行了

**Comment by Ultraman95** [comment]
add_ldflags("-MT")

**Comment by Ultraman95** [comment]
这样也不行啊

**Comment by Ultraman95** [comment]
add_ldflags这个怎么用啊

**Comment by Ultraman95** [comment]
好像是库是mt的， test是md的

**Comment by waruqi** [comment]
> 这样也不行啊

看你的错误提示哈

> “MT_StaticRelease”(hello_server_impl.cpp.obj中)

这不明显你的test是MT么，你还去通过add_ldflags设置 MT ，当然没效果了。

**Comment by waruqi** [comment]
> add_linkdirs("C:/Tools/vcpkg/installed/x64-windows/lib/")

看你加的库搜索目录，x64-windows，这个里面的vcpkg lib都是 MD 版本的，只有 x64-windows-static目录下的才是 MT版本的。。

而你的test明显是MT的（根据错误提示），所以肯定会冲突。。

一种方式，全部走MD，也就是test下xmake.lua里面设置到MD， add_ldflags("-MD")
另外一种方式，全部走MT，也就是add_linkdirs 指定到 x64-windows-static的 vcpkg lib目录，选择MT版本的vcpkg库。。

其实这块跟xmake没啥关系，建议你先查看下vcpkg下关于MT/MD的切换支持文档和相关资料：
https://blogs.msdn.microsoft.com/c/2016/12/14/vcpkg%e6%9b%b4%e6%96%b0%ef%bc%9a%e9%9d%99%e6%80%81%e9%93%be%e6%8e%a5/
https://github.com/Microsoft/vcpkg/issues/36

而关于xmake里面add_ldflags的使用，见xmake的文档：https://xmake.io/#/manual/project_target?id=targetadd_ldflags
