### ISSUE TITLE
自举还是个问题呀。应该提供个CMakeLists.txt

### ISSUE THREAD

**Issue by euloanty** [xmake-io/xmake#607]
用cmake自举一次来安装xmake, 这样xmake就能到处用了.我这个根本用不了.

如果能再提供个xmake自举xmake最好了.

**Comment by waruqi** [comment]
> 用cmake自举一次来安装xmake, 这样xmake就能到处用了.我这个根本用不了.

xmake每个平台都有提供对应安装方式，也有通用的一键安装脚本命令，基本上linux mac win android下都可直接安装，具体可以看下安装文档 https://xmake.io/#/zh-cn/?id=%e5%ae%89%e8%a3%85
暂时不考虑使用cmake来维护，因为已有makefile/xmake.lua两种方式来维护xmake/core源码了，不想再加一种了，而且用cmake维护，还得先装cmake，额外多了一层依赖

如果你这还是不能安装，请提供你这具体系统环境和平台，以及安装过程的错误信息


> 如果能再提供个xmake自举xmake最好了.

xmake原本就已经支持自举，只要系统上已经装有xmake，就可以通过xmake编译xmake源码，我win上编译xmake，就是通过xmake来编译的，而linux上问题是现有发行版并不自带xmake，所以只能通过make来编译，但是如果已有xmake，那么通过xmake来编译也是可以的

**Comment by euloanty** [comment]
我不需要你这些脚本。基本全是炸妈的。到最后这些所谓的一键安装命令就和make一样的翔，得继续用cmake炸妈。

可惜的是光编译lua就非常困难了。

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by waruqi** [comment]
我刚已经说了，xmake支持自举编译

> 如果你这还是不能安装，请提供你这具体系统环境和平台，以及安装过程的错误信息

只要用户配合提供信息，总归能解决安装问题的，目前到现在还没遇到过现有方式装不上的情况

issues上模板也有提示说明，有问题请提供详细错误信息和使用环境，我们会排查问题来帮用户解决，而不是只管自己在那吐槽，这解决不了问题

并且除了脚本安装，文档里也有详细说明，如何通过make去编译源码安装，不走脚本

如果你还是觉得不满足你的需求，建议直接使用cmake来维护项目会更好些

谢谢

**Comment by euloanty** [comment]
> 我刚已经说了，xmake支持自举编译
> 
> > 如果你这还是不能安装，请提供你这具体系统环境和平台，以及安装过程的错误信息
> 
> 只要用户配合提供信息，总归能解决安装问题的，目前到现在还没遇到过现有方式装不上的情况
> 
> issues上模板也有提示说明，有问题请提供详细错误信息和使用环境，我们会排查问题来帮用户解决，而不是只管自己在那吐槽，这解决不了问题
> 
> 并且除了脚本安装，文档里也有详细说明，如何通过make去编译源码安装，不走脚本
> 
> 如果你还是觉得不满足你的需求，建议直接使用cmake来维护项目会更好些
> 
> 谢谢

make依赖shell. win下根本没有shell,不借助一些奇奇怪怪的东西根本运行不了. 这就是为何有人希望能支持ninja之类的原因.
make本身就是炸妈的.不然就没有cmake了

**Comment by waruqi** [comment]
releases下有提供各个版本 win exe安装包，你可以仔细看下安装文档说明

里面并没有强制要求必须使用ps脚本来安装，提供ps脚本安装方式，只是多一种可用的安装方式而已，如果你觉得不适合，可以直接下载exe安装，直接安装

我平常win下都是直接通过安装包装的，所以需要用户在反馈问题的时候，先提供自己的使用环境信息

只是一味吐糟脚本不好用，作者是不知道用户是否在win下，也没法给与针对性的解决方式

**Comment by euloanty** [comment]
> releases下有提供各个版本 win exe安装包，你可以仔细看下安装文档说明
> 
> 里面并没有强制要求必须使用ps脚本来安装，提供ps脚本安装方式，只是多一种可用的安装方式而已，如果你觉得不适合，可以直接下载exe安装，直接安装
> 
> 我平常win下都是直接通过安装包装的，所以需要用户在反馈问题的时候，先提供自己的使用环境信息
> 
> 只是一味吐糟脚本不好用，作者是不知道用户是否在win下，也没法给与针对性的解决方式

我用powershell一类的同样折腾不出来,直接就炸了.

**Comment by waruqi** [comment]
所以我刚说了，如果ps安装不满足需求，可以使用安装包的安装方式

**Comment by euloanty** [comment]
> 所以我刚说了，如果ps安装不满足需求，可以使用安装包的安装方式

我说了.我用安装包同样是炸的.uname之类的炸,msys2炸.

**Comment by waruqi** [comment]
我已经说了好几遍了，如果安装失败，请提供详细的错误信息，我们都会尽力帮忙排查问题，帮用户解决，安装包出错，就提供错误提示或者截图，脚本出错，就提供脚本错误信息

只管自己吐槽，到现在什么错误信息都不提供，我们也没办法给你解决问题，实在不好意思

**Comment by waruqi** [comment]
> 我说了我不需要你帮我解决问题.我需要cmake.不要替我选择.

既然你都这么说了，你大可以直接使用cmake，没必要在这里折腾xmake

我们也没必要你替我们选择加cmakelists.txt 我们不需要 谢谢

**Comment by euloanty** [comment]
> > 我说了我不需要你帮我解决问题.我需要cmake.不要替我选择.
> 
> 既然你都这么说了，你大可以直接使用cmake，没必要在这里折腾xmake
> 
> 我们也没必要你替我们选择加cmakelists.txt 我们不需要 谢谢

同样呀,按你的逻辑.绝大多数人也不需要你这依赖lua的破玩意.对吧.你开心就好.程序员都是小白是吧.

一边扯说cmake怎样怎样的不好.一边自己折腾的东西走回和make一样的老路.有什么意义呢?
