### ISSUE TITLE
Win下编译anroid armv7-a默认未链接unwind，导致程序无法捕获C++异常

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#608]
Win下编译 android armv7-a 使用c++_static时（linux没试验），由于默认未链接 libunwind.a，将导致C++程序中的try catch 无法捕获异常直接退出。

android C++异常无法捕获导致程序退出的问题之前挺多，这个可参考：
[https://github.com/android/ndk/issues/289](https://github.com/android/ndk/issues/289)

android ndk 应该是更改了编译脚本，默认在c++_static + armv7-a时，自动链接 libunwind.a 和 libatomic.a 两个库。可以参考 NDK 目录下（ndk-bundle\sources\cxx-stl\llvm-libc++\libs\armeabi-v7a）的相关 libc++.a.xx 文件，如 libc++.a.29内容如下：
INPUT(-lc++_static -lc++abi -lunwind -latomic)

**Comment by waruqi** [comment]
好的，我回头看下

**Comment by waruqi** [comment]
我github上更新了，可以试试： xmake update -s github:xmake-io#dev 其他镜像还没更新。

**Comment by fasiondog** [comment]
好，明天试下

**Comment by fasiondog** [comment]
![图片](https://user-images.githubusercontent.com/1145161/67741887-62e74a80-fa55-11e9-9637-571e3c960d14.png)

**Comment by waruqi** [comment]
你网络的问题的，github访问不到？ 不过我所有mirror都更新了，你直接 xmake update -s dev就好了。会自动拉取gitee的。。

**Comment by OpportunityLiu** [comment]
命令输错了吧。。。`github:xmake-io/xmake#dev`

**Comment by waruqi** [comment]
哦 我敲错了 = =

**Comment by fasiondog** [comment]
不清楚是不是网络，但git我可以访问。明天再试下。

**Comment by fasiondog** [comment]
OK，可以

**Comment by fasiondog** [comment]
这个只有在32位的arm里加，64位的不能加，现在64位的编译失败了，找不unwind库

**Comment by waruqi** [comment]
你再更新下dev脚本试试

**Comment by fasiondog** [comment]
可以了
