### ISSUE TITLE
错误的主题配置导致xmake无法启动

### ISSUE THREAD

**Issue by OpportunityLiu** [xmake-io/xmake#610]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题

![图片](https://user-images.githubusercontent.com/13471233/67660824-a2049580-f99a-11e9-829a-573af963d550.png)

### 期待的结果

回退到default

### 错误信息

如果可能，请尽量附加程序运行过程中的错误输出信息。

> 如果是xmake相关编译问题，请加上`-v -D`参数运行，并给出详细编译输出信息。
加 -v -D 不会增加任何调试输出。

### 相关环境

xmake v2.2.8+201909050349, A cross-platform build utility based on Lua
win 10

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by waruqi** [comment]
试试 xmake global -c 重置下cache

**Comment by OpportunityLiu** [comment]
一样的错误。。。

**Comment by waruqi** [comment]
额，好吧。等晚上我看看。= =

**Comment by OpportunityLiu** [comment]
只能手动请xmake.conf

**Comment by waruqi** [comment]
我github上更新了，可以试试： xmake update -s github:xmake-io#dev   其他镜像还没更新。
