### ISSUE TITLE
更新dev分支之后，脚本报错

### ISSUE THREAD

**Issue by owllyi** [xmake-io/xmake#611]
win10系统，win64版本，用的最新的xmake 2.2.8版本，执行如下命令：
xmake update -s dev

更新完成之后，再次运行xmake，出现脚本报错：

$ xmake --version
error: .\core\base\task.lua:400: .\actions\build\xmake.lua:46: attempt to call field 'cpuinfo' (a nil value)
stack traceback:
    [.\actions\build\xmake.lua:46]: in main chunk

麻烦看下，是哪里遇到了问题，改如何解决？

此外，一但lua脚本报错，好似就没有办法再更新回去了。
能否保留一种机制，能回退到上一个版本。或者把更新机制放在c++中，确保出错了能自救呢。

**Comment by OpportunityLiu** [comment]
因为binary更改了。。。

**Comment by owllyi** [comment]
嗯，猜测也是。需要：xmake update dev 来更新对吧

**Comment by owllyi** [comment]
能否增加一种机制，确保exe和lua的API版本能对应上呢？

**Comment by OpportunityLiu** [comment]
-s本来就是偏向调试用的，主要是之前win上全量更新不方便做的，现在有了ci以后其实没啥必要了

**Comment by owllyi** [comment]
请问ci具体是指什么呢？

**Comment by OpportunityLiu** [comment]
https://ci.appveyor.com/project/waruqi/xmake/branch/master
win上的更新现在是从这里编译和分发的

**Comment by OpportunityLiu** [comment]
https://ci.appveyor.com/project/waruqi/xmake/branch/master/job/imgf986elw9ppnmg/artifacts
直接下载安装包后台安装

**Comment by owllyi** [comment]
明白了，多谢。
请问master和dev分支有什么区别呢，更新的时候使用哪个分支版本？

**Comment by OpportunityLiu** [comment]
其实这两个都不是生产版本，master差不多是beta，dev差不多是alpha，生产版本什么都不写直接xmake update就好

**Comment by waruqi** [comment]
-s还是有必要的 ci上有时候下载慢 。直接拉scripts会走gitee镜像 至少会快不少

dev是开发版 有可能不稳定，平常建议从master拉，不过如果一些特定问题的修复验证，master还没更新，可以从dev拉取后测试
