### ISSUE TITLE
VS解决方案应该增加一个更新自身的工程

### ISSUE THREAD

**Issue by Domain** [xmake-io/xmake#612]
现在如果加了文件，需要用命令来更新工程，太麻烦了，应该增加一个新的空工程，专门用来更新，不需要另外使用命令

**Comment by waruqi** [comment]
> 应该增加一个新的空工程，专门用来更新，不需要另外使用命令

这块没理解，能具体细说下吗？怎么个更新方式

**Comment by OpportunityLiu** [comment]
是这个道理，等我研究研究

**Comment by OpportunityLiu** [comment]
工具-外部工具，然后加上这个
![图片](https://user-images.githubusercontent.com/13471233/68013594-53236c80-fcc8-11e9-9aa2-ee5a89f9e026.png)
就有了
![图片](https://user-images.githubusercontent.com/13471233/68013619-5e769800-fcc8-11e9-91a7-1d0893c7f079.png)
![图片](https://user-images.githubusercontent.com/13471233/68013660-76e6b280-fcc8-11e9-843b-91e5e97bd711.png)

**Comment by Domain** [comment]
> 工具-外部工具，然后加上这个
> ![图片](https://user-images.githubusercontent.com/13471233/68013594-53236c80-fcc8-11e9-9aa2-ee5a89f9e026.png)
> 就有了
> ![图片](https://user-images.githubusercontent.com/13471233/68013619-5e769800-fcc8-11e9-91a7-1d0893c7f079.png)
> ![图片](https://user-images.githubusercontent.com/13471233/68013660-76e6b280-fcc8-11e9-843b-91e5e97bd711.png)

这确实是个好方法，不过这需要每个人都知道怎么加，还是不够友好。我之前用fastbuild的时候，就会有一个工程专门用来更新，编译它就会更新整个解决方案，还是更加方便点。

**Comment by waruqi** [comment]
@Domain 创建vs proj时候 里面自动附带一个 auto_update 自更新 target 子工程，然后里面自定义build脚本 ，里面每次同时编译自动检测xmake.lua如果有更新就自动执行下 xmake project -k vsxmake 实现自更新么？

**Comment by waruqi** [comment]
如果是这样的话 我觉得你可以直接在 xmake.lua自己加个target就可以了吧，比如

```lua
target("autoupdate")
    set_kind("phony")
    after_build(function(target)
        os.run("xmake project -k vsxmake")
    end)

**Comment by Domain** [comment]
> 如果是这样的话 我觉得你可以直接在 xmake.lua自己加个target就可以了吧，比如
> 
> ```lua
> target("autoupdate")
>     set_kind("phony")
>     after_build(function(target)
>         os.run("xmake project -k vsxmake")
>     end)
> ```

这个怎么用？我直接复制到根目录的xmake.lua里面，运行xmake就没反应了

**Comment by OpportunityLiu** [comment]
自从project lock实装，在xmake里调xmake就再不能用了

**Comment by waruqi** [comment]
因为都用到了xmake config，操作都在相同project下，不加lock又会有之前的build冲突问题，除了build，其他action没加lock，所以跟build不相关的script里面内部调用不会卡

不过即使能调用，vcproj文件在打开状态，build后重新生成似乎也不能覆写吧。

**Comment by OpportunityLiu** [comment]
> vcproj文件在打开状态

VS又不会锁定文件的。。

**Comment by waruqi** [comment]
那可以试试不阻塞调用xmake，就不会被lock卡了

```lua
target("autoupdate")
    set_kind("binary")
    on_build(function(target)
        local proc = process.open("xmake project -k vsxmake")
        if proc then
              proc:close()
        end
    end)
```

**Comment by waruqi** [comment]
@Domain 你试试我刚贴的方式，我试过了，vcproj可以自动被更新掉，也不会卡，唯一的问题是  如果文件列表变动，vs的界面上源码列表不会自动刷新，需要重新打开vs重新加载下才行

**Comment by Domain** [comment]
@waruqi 确实可以了, 感谢! 
不过还有几个问题要请教一下:
1. 怎么把生成的项目放到不同的解决方案文件夹里面? 现在全部都是放在一起, 管理起来不方便
2. 现在好像无论是否有改变都会重新生成工程文件, 导致每次都要重新加载, 是否可以做到没变化就不要重新生成?
3. 每次编译其实都很慢, 下面这句话
$xmake config -P . -p windows -m debug -a x64 -o "build" autoupdate
需要等待好几秒, 另外,每个工程都会重新检查VS版本, 浪费了很多时间. 如果直接在命令行执行xmake就没有这些问题

**Comment by OpportunityLiu** [comment]
1. 没弄懂啥意思，具体是什么样的效果呢？
2. 可以做
3. 还是 @waruqi 优化下 config 的速度吧，从 vs 插件这里改。。工程量太大了，还需要额外维护状态

**Comment by Domain** [comment]
现在是这样的
![image](https://user-images.githubusercontent.com/903197/68844461-ca172700-0704-11ea-91a2-eea9deb65ea1.png)
我想设置每个的文件夹:
![image](https://user-images.githubusercontent.com/903197/68844586-021e6a00-0705-11ea-9f8e-fba51bfe1ca2.png)

**Comment by waruqi** [comment]
回头我看下 按理有config cache ，vs只检测一遍才对

**Comment by waruqi** [comment]
> 每次编译其实都很慢, 下面这句话
> $xmake config -P . -p windows -m debug -a x64 -o "build" autoupdate
> 需要等待好几秒, 另外,每个工程都会重新检查VS版本, 浪费了很多时间. 如果直接在命令行执行xmake就没有这些问题

@Domain 这个我看了下，主要是由于`xmake config xxx`后面带了targetname，导致vs里面多个`xmake config`进程同时起来，每个进程只写到对应自己target的config里面，然后把对方target的config cache给覆写重置了。。因为同时加载的时候对方target的config cache还不存在。

@OpportunityLiu 我觉得vs里面没必要对每个target 来一遍 `xmake config`，因为 arch / mode / plat这些配置都是全局影响的，只需要全局执行一次  `xmake config -P . -p windows -m debug -a x64 -o "build"` 就行了。。即使每个target都执行，也不必带上targetname

`xmake config targetname`指定target的配置方式，手动执行的时候都很少会用到，更何况vs里面这些配置都是全局的

**Comment by OpportunityLiu** [comment]
我周末搞一下吧

**Comment by waruqi** [comment]
> 每次编译其实都很慢, 下面这句话
> $xmake config -P . -p windows -m debug -a x64 -o "build" autoupdate
> 需要等待好几秒, 另外,每个工程都会重新检查VS版本, 浪费了很多时间. 如果直接在命令行执行xmake就没有这些问题

@Domain 这个问题最新的patch已经改进过了，你可以更新到master试试  xmake update master

**Comment by Domain** [comment]
@waruqi @OpportunityLiu 
2、确认好了，工程没变化不会重新生成
3、确实比以前快了很多，不过比fastbuild还有差距，我的fastbuild里面十几个工程，如果没有任何变化，点击编译全部，不到一秒就会提示全部最新。xmake需要每个工程单独确认，每个大概1秒

**Comment by waruqi** [comment]
> @waruqi @OpportunityLiu
> 2、确认好了，工程没变化不会重新生成
> 3、确实比以前快了很多，不过比fastbuild还有差距，我的fastbuild里面十几个工程，如果没有任何变化，点击编译全部，不到一秒就会提示全部最新。xmake需要每个工程单独确认，每个大概1秒

这是因为目前vs里面build，是每个target单独调用xmake命令去build，如果直接调用xmake build去一次构建所有 就不会有这问题。

这个有办法对全部编译只执行一次xmake么？  @OpportunityLiu

**Comment by Domain** [comment]
更正一下，现在工程没变化，还是会重新生成，只是不会覆盖，所以不会重新加载。如果可以不用重新生成就更好了，虽然生成时间也不长。如果不好做，最好就是全部编译的时候，可以指定这个工程不执行，需要时，自己手动编译这个就行了。这些目前fastbuild都可以做到，可以研究一下。

**Comment by OpportunityLiu** [comment]
@waruqi 我觉得不太行。。

**Comment by Domain** [comment]
@OpportunityLiu 我看了一下，我自己生成的fastbuild工程是这样，首先每个项目是单独的工程，然后还有两个特殊的空白工程，一个是更新工程本身的update工程，一个是编译全部工程的all工程，点编译解决方案时，编译的是all工程，其他工程都不编译，它就是简单在根目录执行fbuild。这样想更新工程本身就自己编译update，需要编译全部就点生成解决方案，或者编译all，想编译独立的就编译对应的，非常灵活

**Comment by OpportunityLiu** [comment]
如果你们能接受牺牲正确性换方便的话就自己去改吧。。

**Comment by Domain** [comment]
> 如果你们能接受牺牲正确性换方便的话就自己去改吧。。

自己增加update和all工程很容易，但是现在不能控制点击生成解决方案时哪些工程需要编译，如果生成的工程有这个选项，我就可以自己实现这些了

**Comment by waruqi** [comment]
@Domain 可以参考之前xmake.lua那个autoupdate，自己加个buildall的target就好了

不想自动build，就对target设置下set_default(false);

**Comment by OpportunityLiu** [comment]
> 我就可以自己实现这些了

你现在就可以自己实现
开源项目，自己动手，丰衣足食

**Comment by Domain** [comment]
> > 我就可以自己实现这些了
> 
> 你现在就可以自己实现
> 开源项目，自己动手，丰衣足食

我倒是想自己改，不过我对这个不熟悉，研究起来还是挺费时间的。我看了一下，应该是文件
ProjConfig(target,mode,arch)
里面第二行：
```{#target_id#}.#mode#|#arch#.Build.0 = #mode#|#vsarch#```
决定是否编译。
我的想法是，默认都是编译的，和现在不变，如果用
```target:set_values("vsxmake.build", "false")```
就不生成这一行。这样默认行为就不会改变

**Comment by OpportunityLiu** [comment]
还没明白我的意思吗。。。

我反对这样做，所以我是不会去改的，你们谁支持谁去动手。没人给我发钱的情况下我为啥要自己去吃屎呢？

**Comment by Domain** [comment]
好吧，我明白了
