### ISSUE TITLE
after_build或者after_link能否设为真的有该行为的时候才执行？

### ISSUE THREAD

**Issue by eddylin83** [xmake-io/xmake#617]
因为想编译之后进行upx压缩。放在after_build或者after_link都可以，就是没改动的时候再次进行一次编译。实际上编译操作都会跳过（因为已经是最新的），也就是没有link一类的操作了，但是上述两个行为也会触发。虽然没啥影响，upx最多就报错已经压缩过。就是强迫症觉得有点受不了。而且没有link行为但是出发before/after_link这些好像逻辑有点不好。

**Comment by waruqi** [comment]
on/before/after_link只是暴露每个阶段 给用户一个可以执行自定义脚本的机会，每个脚本阶段对于内置on_link是否会实际执行ld是不关心的，即使内部没执行ld，也许有用户就是有需要每次这个阶段做一些自己的逻辑处理，不管是否执行了ld

如果觉得没必要，可以自行在after_link里面忽略处理，比如生成到target.upx一个独立文件，通过os.mtime()判断是否需要再做一次处理

```lua
os.cp(targetfile, targetfile.upx)
if os.mtime(targetfile) > os.mtime(targetfile.upx) then
    os.exec("upx ... targetfile.upx")
end
```
