### ISSUE TITLE
.xmakerc (.bashrc likeruncomfile)

### ISSUE THREAD

**Issue by inter1965** [xmake-io/xmake#620]
It would be ideal that we have a custom rc file for xmake to store some global functions or configs, and we could customize it according to different platform so we have a uniform file.

**Comment by waruqi** [comment]
Is this? `~/.xmake/profile`

**Comment by inter1965** [comment]
However, according to your document ("https://xmake.io/#/guide/installation?id=installation"), `~/.xmake/profile` is a bash source file. 
Actually what i mean is a global file that would be read every time before the project's "xmake.lua", it's a lua file and those common code blocks in every projects's `xmake.lua` could be centralized and reused.

**Comment by waruqi** [comment]
I see what you mean, but this feature can only be used for private individual projects and cannot be distributed.

**Comment by waruqi** [comment]
But for some personal private project, this feature does provide some convenience. So I'll consider it.

**Comment by waruqi** [comment]
I have supported it, you can run `xmake update dev` to update and try it.

The default file path:
```console
~/.xmakerc.lua
```

Or you can set `XMAKE_RCFILE` environment variable to modify the default path.

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/69019139-3e461900-09ea-11ea-8e39-367776c5dd37.png)
可以参考一下其他软件的设计

**Comment by waruqi** [comment]
@OpportunityLiu Ok, I will improve it.

**Comment by waruqi** [comment]
I improved it again. xmake will read xmakerc file from `/etc/xmakerc.lua` -> `~/.xmakerc.lua` -> `~/.xmake/xmakerc.lua` -> `$XMAKE_GLOBALDIR/xmakerc.lua`

**Comment by fasiondog** [comment]
能在项目目录底下加个 xmakerc 不？ 只对该项目及其依赖的源码包生效。否则，现在这个机制只适合私人使用，团队协作的时候很不方便，总能每次都让大家去手动修改自己的xmakerc吧

**Comment by waruqi** [comment]
> 能在项目目录底下加个 xmakerc 不？ 只对该项目及其依赖的源码包生效。否则，现在这个机制只适合私人使用，团队协作的时候很不方便，总能每次都让大家去手动修改自己的xmakerc吧

项目底下，你直接自己 includes 下 不就完事了么。。

**Comment by fasiondog** [comment]
这个问题和昨天那个toolchain相关，我在 .xmakerc 里增加 toolchain，怎么共享给其他人？项目里有依赖了其他的源码包，不可能一一去修改

**Comment by waruqi** [comment]
> 这个问题和昨天那个toolchain相关，我在 .xmakerc 里增加 toolchain，怎么共享给其他人？项目里有依赖了其他的源码包，不可能一一去修改

这个问题 跟这里的 rc 问题没啥关系，可以到单独 issues 讨论，目前的实现机制，项目中 toolchain 的定义是没法透传的，一种办法只能像 cmake/autoconf拆解成 cc/ld 那样单独透传，但也有局限
