### ISSUE TITLE
請問 vsmake 可以能否設置 windows sdk 版本?

### ISSUE THREAD

**Issue by orzuk-lmj** [xmake-io/xmake#621]
先前的版本貌似有做一部分的 WindowsTargetPlatformVersion 設置，但也綁死了VS版本號，Xmake.props 最新的貌似也已經刪除了sdkver 設定。

如果從 `local configcache = cache("local.config")` 取得windows sdk版號，會發生問題嗎??
@waruqi @OpportunityLiu 

因為一些代碼分析軟體會取用這個windows sdk版本號，方便後續使用，所以想問看看有沒有辦法。

**Comment by OpportunityLiu** [comment]
其实也可以。。之前那个根据vs版本设sdk版本问题很大，就删掉了
