### ISSUE TITLE
add_cflags("--coverage") 链接报错

### ISSUE THREAD

**Issue by mzfhhhh** [xmake-io/xmake#623]
### 描述问题

xmake2.2.8 + windows 10 64位 + mingw64

编译demo工程,编译成功

加上 `add_cflags("--coverage")` 编译选项后,再次编译,链接报错

```
add_cflags("--coverage") 

-- define target
target("test_sub")
    -- set kind
    set_kind("binary")
    -- add files
    add_files("test_sub.c")
```

### 错误信息

[100%]: linking.release test_sub.exe
error: build\.objs\test_sub\mingw\x86_64\release\.\test_sub.c.obj:test_sub.c:(.text+0x5a3): undefined reference to `__gcov_init'
build\.objs\test_sub\mingw\x86_64\release\.\test_sub.c.obj:test_sub.c:(.text+0x5b7): undefined reference to `__gcov_exit'
build\.objs\test_sub\mingw\x86_64\release\.\test_sub.c.obj:test_sub.c:(.data+0x60): undefined reference to `__gcov_merge_add'
collect2.exe: error: ld returned 1 exit status

**Comment by waruqi** [comment]
`--coverage` 这个 ldflags里面也得加，否则链接不过的，或者直接用 `add_rules("mode.coverage")`

然后切到coverage模式编译，`xmake f -m coverage; xmake`就行了，内置的mode.coverage规则已经给你配置好这些了。。

https://github.com/xmake-io/xmake/blob/5fa5b0a217aff8fa8c6e8cc1bbe3031e3b1f1bec/xmake/rules/mode/xmake.lua#L119-L140

**Comment by mzfhhhh** [comment]
```
add_cflags("--coverage") 
add_ldflags("--coverage")

-- define target
target("test_sub")

    -- set kind
    set_kind("binary")

    -- add files
    add_files("*.c")
```
编译后,源码路径生成一个文件 "gcc_has_flags.gcno"
运行release目录下exe,没有任何文件生成
怎么用gcov命令行进一步生成覆盖文件信息?

**Comment by waruqi** [comment]
这属于gcov自身的使用的问题，你自行google下

**Comment by mzfhhhh** [comment]
```
编译：gcc -fprofile-arcs -ftest-coverage -o myapp main.c tmp.c
运行：./myapp
然后 输入命令： gcov main.c,gcov tmp.c
```
使用上面的步骤,
1. 每个.c文件都有一个同名的.gcno文件
2. 运行exe,也能得到每个.c文件同名的.gcda文件
3. 输入gcov *.c,能得到获取到覆盖率信息

但使用上面的xmake命令编译后,就生成一个gcc_has_flags.gcno,我看了里面内容,对应的源码文件应该是
int main(int argc, char** argv)
{return 0;}
与源文件没任何关系,是我上面的xmake脚本有问题吗?

----
另外,我一输入这个命令,就把编译环境改为vs了
PS F:\code\test\\src> xmake f -m coverage
checking for the architecture ... x64
checking for the Microsoft Visual Studio (x64) version ... 2017

**Comment by waruqi** [comment]
> 但使用上面的xmake命令编译后,就生成一个gcc_has_flags.gcno,我看了里面内容,对应的源码文件应

xmake也就只是追加这个flags而已，你敲xmake -v 看下完整命令，如果确认flags加上了，那就跟xmake没啥关系了，你也可以手动复制出来 里面的 完整命令，直接运行测试

gcno应该是默认生成到obj对应路径，而不是.c对应路径，只不过你这测试正好obj/c在一起而已。。你到obj下面找下，或者整个目录全局Find下


> 另外,我一输入这个命令,就把编译环境改为vs了
> PS F:\code\test\src> xmake f -m coverage
> checking for the architecture ... x64
> checking for the Microsoft Visual Studio (x64) version ... 2017

每次配置，都是完整配置，不是增量配置，你要敲全所有配置，包括mingw的切换

**Comment by mzfhhhh** [comment]
完整配置: xmake f -p mingw --sdk=C:\mingw64 -m coverage
再次 xmake ,然后 xmake run demo后,得到如下文件
```
src\demo.c
src\xmake.lua
src\build\.objs\test_sub\mingw\x86_64\coverage\demo.c.obj
src\build\.objs\test_sub\mingw\x86_64\coverage\demo.c.gcda
src\build\.objs\test_sub\mingw\x86_64\coverage\demo.c.gcno
```

直接 gcov demo.c 得到错误信息
demo.gcno:cannot open notes file

需要做如下修改,才能得到demo.gcov文件, 有点繁琐,**请问最佳实践是什么?**

1. 复制:demo.c -> coverage文件夹
2. 修改:demo.c.gcda -> demo.gcda
3. 修改:demo.c.gcda -> demo.gcno
4. gcov demo.c 生成 demo.gcov文件

**Comment by waruqi** [comment]
> 需要做如下修改,才能得到demo.gcov文件, 有点繁琐,请问最佳实践是什么?

自己写个脚本放在一起处理下

**Comment by waruqi** [comment]
之前编译时候--coverage没生效，我dev改进过这块了，详情见：https://github.com/xmake-io/xmake/issues/634#issuecomment-562909601
