### ISSUE TITLE
xmake project -k vsxmake 生成 vs 工程打开报错

### ISSUE THREAD

**Issue by 316064780** [xmake-io/xmake#624]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
在vsxode 中使用 xmake project -k vsxmake  命令创建 Vs工程后，在Vs2010 环境中打开时报错

### Expected behavior
生成的 VS10  工程正常打开并能调试运行

### Error output
 The imported project "D:\Microsoft.Cpp.Default.props" was not found.  
 Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.   
 C:\Program Files\xmake\plugins\project\vsxmake\vsproj\Xmake.props
### Related Environment
configure
{
    arch = x86
    ccache = true
    plat = windows
    ld = link.exe
    mode = debug
    ndk_stdcxx = true
    host = windows
    buildir = build
    kind = static
    theme = plain
    vs = 2010
    cxx = cl.exe
}

**Comment by waruqi** [comment]
这个不是xmake-vscode的问题，我迁移过来了，你可以打包提供下你这生成的 vs工程作为issues附件，发来看看

**Comment by OpportunityLiu** [comment]
求你们装个新版吧。。实在不想维护这么旧的版本了

**Comment by 316064780** [comment]
[test-c.txt](https://github.com/xmake-io/xmake/files/3878366/test-c.txt)
这是一个 .7z 的压缩包，由于上传限制，手动改成 .txt 了。

另外 旧的版本是指的是 Vs2010 么，那你们通常用的那个版本，我换一下；

**Comment by OpportunityLiu** [comment]
我这里只装了2019

**Comment by 316064780** [comment]
2019 32 位系统能装不？

**Comment by OpportunityLiu** [comment]
vs从来没出过64位版本
