### ISSUE TITLE
`tb_uuid_generate` 改成正确的 UUID V4 实现

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#629]
@waruqi 请尽快把 `tb_uuid_generate` 改成正确的 UUID V4 实现，这里可能有潜在的 bug，貌似 VS 不认错误的 SolutionGuid

_Originally posted by @OpportunityLiu in https://github.com/xmake-io/xmake/pull/628#issuecomment-557875424_

**Comment by OpportunityLiu** [comment]
还有 `tb_uuid_make_cstr`

**Comment by waruqi** [comment]
可以，我回头都改进下

**Comment by waruqi** [comment]
@OpportunityLiu   我改进过了 你再试试  dev版本
