### ISSUE TITLE
Linux 下 xmake update 命令未生效

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#632]
### 描述问题

Linux 下（优麒麟 18.04），使用 xmake 的 deb 包安装后，运行 xmake update 或 sudo xmake update 都没有实际更新。

![图片](https://user-images.githubusercontent.com/1145161/70025766-f1ad3100-15d8-11ea-9f3d-47c8e6bd554c.png)

**Comment by OpportunityLiu** [comment]
这不已经是最新版了吗？

要升级到现在的开发中版本请用 `xmake update master` 和 `xmake update dev`

**Comment by waruqi** [comment]
@fasiondog   xmake update 仅用于更新到 2.2.8 最新的正式版，你这边已经是2.2.8版本了，所以不会重复更新，如果要更新到dev/master版本，需要在xmake update xx中指明分支名

**Comment by fasiondog** [comment]
晕，我犯错了
