### ISSUE TITLE
以 coverage 模式编译并运行程序，未生成 .gcno 文件

### ISSUE THREAD

**Issue by lc-soft** [xmake-io/xmake#634]
### 描述问题

第一次运行时会生成 gcc_has_cflags.gcno 文件，删掉重新跑后就没了。

```bash
xmake create test-coverage
cd test-coverage
# 编辑 xmake.lua，插入 mode.coverage 规则
gedit xmake.lua
xmake config --mode=coverage
xmake
xmake run
```
![2019-12-03 18-57-34 的屏幕截图](https://user-images.githubusercontent.com/1730073/70045295-d2c19580-15fe-11ea-9e12-df1b09aad299.png)

### 期待的结果

- 生成的 .gcno 文件名应该与源文件/目标同名
- 每次运行程序应该重新生成 .gcno 文件

### 错误信息

无

### 相关环境

- Xmake: v2.2.8+201908291003
- Ubuntu 18.04.3 LTS

### 其他信息

无

**Comment by waruqi** [comment]
见：https://github.com/xmake-io/xmake/issues/623

**Comment by lc-soft** [comment]
> 需要到build/.obj目录 对应obj路径下找

.objs 目录内容如下：

![image](https://user-images.githubusercontent.com/1730073/70106114-bf094400-167d-11ea-9752-e3ebb56883c2.png)

**Comment by lc-soft** [comment]
`--coverage` 检测未通过，加上 `add_cflags("-ftest-coverage", "-fprofile-arcs", {force = true})` 就可以了。

![image](https://user-images.githubusercontent.com/1730073/70300289-16e8ac00-1832-11ea-93a1-8947b1766a08.png)

![image](https://user-images.githubusercontent.com/1730073/70300307-27008b80-1832-11ea-9251-0f80fb2cca90.png)

**Comment by waruqi** [comment]
👍 回头我改进下

**Comment by waruqi** [comment]
这个问题我改进过了，你可以更新到 xmake update dev 再试试，不用在外面额外追加 "-ftest-coverage", "-fprofile-arcs"了

其实--coverage等价于这两flags，只不过之前xmake在检测这个flag的时候，内部采用--coverage -o /dev/null来尝试编译检测，会失败，因为写文件/dev/null.gcno失败了。

现在我改进了flags检测，改用 --coverage -o os.tmpfile()  来检测，就能检测通过，对于整体其他flags的检测成功率也会提升不少
