### ISSUE TITLE
Compile failed for QT5.13 project

### ISSUE THREAD

**Issue by rel1ve** [xmake-io/xmake#635]
The project has compiled successfully with QtCreater, bug failed with xmake.

`error: build/.objs/scp-tool/linux/x86_64/release/src/mainwindow.cpp.o：在函数‘MainWindow::MainWindow(QWidget*)’中：
mainwindow.cpp:(.text+0x5eb)：对‘LoginUser::staticMetaObject’未定义的引用
mainwindow.cpp:(.text+0x657)：对‘LoginUser::staticMetaObject’未定义的引用
build/.objs/scp-tool/linux/x86_64/release/src/loginuser.cpp.o：在函数‘LoginUser::LoginUser(QObject*)’中：
loginuser.cpp:(.text+0x11)：对‘vtable for LoginUser’未定义的引用
build/.objs/scp-tool/linux/x86_64/release/src/loginuser.cpp.o：在函数‘LoginUser::~LoginUser()’中：
loginuser.cpp:(.text+0x93)：对‘vtable for LoginUser’未定义的引用
build/.objs/scp-tool/linux/x86_64/release/src/loginuser.cpp.o：在函数‘LoginUser::~LoginUser()’中：
loginuser.cpp:(.text+0x123)：对‘vtable for LoginUser’未定义的引用
build/.objs/scp-tool/linux/x86_64/release/gens/rules/qt/moc/moc_mainwindow.cpp.o：在函数‘MainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)’中：
moc_mainwindow.cpp:(.text+0x11b)：对‘LoginUser::staticMetaObject’未定义的引用
build/.objs/scp-tool/linux/x86_64/release/gens/rules/qt/moc/moc_mainwindow.cpp.o：在函数‘QMetaTypeIdQObject<LoginUser*, 8>::qt_metatype_id()’中：
moc_mainwindow.cpp:(.text._ZN18QMetaTypeIdQObjectIP9LoginUserLi8EE14qt_metatype_idEv[_ZN18QMetaTypeIdQObjectIP9LoginUserLi8EE14qt_metatype_idEv]+0x43)：对‘LoginUser::staticMetaObject’未定义的引用
build/.objs/scp-tool/linux/x86_64/release/gens/rules/qt/moc/moc_logindialog.cpp.o：在函数‘LoginDialog::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)’中：
moc_logindialog.cpp:(.text+0x18b)：对‘LoginUser::staticMetaObject’未定义的引用
collect2: error: ld returned 1 exit status`

**Comment by waruqi** [comment]
LoginUser相关定义没找到，确定通过add_files添加编译进去了？

**Comment by rel1ve** [comment]
sorry for my reply late. I forgot to add_files with Q_OBJECT meta. It's not a bug.

**Comment by waruqi** [comment]
ok
