### ISSUE TITLE
xmake 在 windows 与 linux 平台行为不一致

### ISSUE THREAD

**Issue by idealvin** [xmake-io/xmake#638]
### 描述问题

win10 执行 xmake str，报错: `invalid task: str`  
ubuntu 执行 xmake str，正常  

win10 执行 xmake clean，正常  
ubuntu 执行 xmake clean，报错: `error: unknown target: clean`

### 期待的结果

win10 与 ubuntu 执行上述 xmake 命令，行为应该保持一致。

### 错误信息

ubuntu 执行 xmake c/clean 报错如下:  
```sh
root@Vin test# xmake c
checking for the architecture ... x86_64
error: unknown target: c
root@Vin test# xmake clean
checking for the architecture ... x86_64
error: unknown target: clean
```

win10 执行 xmake target 报错如下:  
```sh
error: invalid task: str
```

### 相关环境

- xmake v2.2.8
- win10
- ubuntu 16.04  (root用户，使用了 xmake --root)

### 其他信息

[xmake.lua](https://github.com/idealvin/co/tree/master/test)
```lua
set_kind("binary")
add_cxxflags("-std=c++11")
set_optimize("faster")
set_targetdir("../build")
add_includedirs("..")
add_linkdirs("../lib")
add_links("base")

if is_plat("macosx", "linux") then
    add_cxflags("-g3", "-Wall")
    add_ldflags("-lpthread -ldl")
end
if is_plat("macosx") then
    add_cxflags("-fno-pie")
end
if is_plat("windows") then
    add_cxflags("-Ox", "-fp:fast", "-EHsc")
end

target("co")
    add_files("co_test.cc")

target("fast")
    add_files("fast_test.cc")

target("flag")
    add_files("flag_test.cc")

target("hash")
    add_files("hash_test.cc")

target("json")
    add_files("json_test.cc")

target("rapidjson")
    add_files("rapidjson_test.cc")

target("log")
    add_files("log_test.cc")

target("rpc")
    add_files("rpc_test.cc")

target("str")
    add_files("str_test.cc")

target("time")
    add_files("time_test.cc")

target("tw")
    add_files("tw_test.cc")

target("xx")
    add_files("xx_test.cc")
```

**Comment by waruqi** [comment]
> win10 执行 xmake target 报错如下:
> 
> error: invalid task: str

win的这个行为是正常行为，没啥问题，如果要指定target构建，请敲：xmake build str 

> ubuntu 执行 xmake c/clean 报错如下:
> 
> root@Vin test# xmake c
> checking for the architecture ... x86_64
> error: unknown target: c
> root@Vin test# xmake clean
> checking for the architecture ... x86_64
> error: unknown target: clean

我这里mac/ubuntu测了下，都是ok的没这个问题，你这报错估计是因为root下，你设置了alias xmake = xmake --root 导致

因为--root目前的使用需要放置在指定的action后面才行，例如：xmake clean --root 放前面，解析时候会被作为action干扰，通常--root只用于临时的开启某次root执行

你可以改用export XMAKE_ROOT=y设置环境变量来代替。。

另外，除非必要，尽量建议不要再root下使用，因为xmake.lua毕竟里面都是脚本，虽然外层描述域很安全，但是自定义的脚本域里面可以随意写各种脚本，如果开发者写的脚本有误，用户编译的时候会导致一些错误的读写系统文件的风险存在。所以默认xmake才会提示并作了root限制。

**Comment by idealvin** [comment]
对的，设置了 alias xmake='xmake --root'

**Comment by waruqi** [comment]
> 对的，设置了 alias xmake='xmake --root'

那你改成export XMAKE_ROOT=y 就行了

**Comment by idealvin** [comment]
好的，原来如此，谢谢

**Comment by yunshouhu** [comment]
开发环境ubuntu死活安装不上。坑。

**Comment by idealvin** [comment]
@yunshouhu 请将详细的报错信息，提交给作者吧

**Comment by waruqi** [comment]
> 开发环境ubuntu root用户死活安装不上。坑。

@yunshouhu   原本就不建议root装了用了，即使装上了，默认也是禁用root运行的。。如果非要用root，请开issues 反馈详细信息  光吐糟不能解决问题

**Comment by yunshouhu** [comment]
改成export XMAKE_ROOT=y 就行了。
