### ISSUE TITLE
xmake.lua 中包含两个同名但不同类的 target 时，编译报错

### ISSUE THREAD

**Issue by idealvin** [xmake-io/xmake#640]
### 描述问题

xmake.lua 中包含两个同名但不同类的 target 时，编译报错

### 期待的结果

理论上可以支持同名但不同类型的 target。

### 错误信息

error: /usr/bin/ld: cannot find -ldb

### 相关环境

xmake v2.2.8
ubuntu 16.04

xmake.lua 如下:
预期结果是:  第一个 target 生成 libdb.a,  第二个生成可执行文件 db

```lua
target("db")
    set_kind("static")
    add_cxxflags("-std=c++11")
    set_optimize("faster")  -- -O2
    set_warnings("all")     -- -Wall
    set_targetdir("../lib")
    add_includedirs("..")
    add_files("db.cc", "sqlite3.c")

    if is_plat("macosx", "linux") then
        add_cxflags("-g3")
        if is_plat("macosx") then
            add_cxflags("-fno-pie")
        end
        after_build(function ()
            os.run("rm -rf build")
        end)
    end

    if is_plat("windows") then
        add_cxflags("-Ox", "-fp:fast", "-EHsc")
        after_build(function ()
            os.run("cmd /k rd /s /q build; exit")
        end)
    end

target("db")
    set_kind("binary")
    add_cxxflags("-std=c++11")
    set_optimize("faster")  -- -O2
    set_warnings("all")     -- -Wall
    set_targetdir("../build")
    add_includedirs("..")
    add_linkdirs("../lib")
    add_links("base", "db")
    add_files("test.cc")

    if is_plat("macosx", "linux") then
        add_cxflags("-g3")
        if is_plat("macosx") then
            add_cxflags("-fno-pie")
        end
        add_links("pthread", "dl")
        after_build(function ()
            os.run("rm -rf build")
        end)
    end

    if is_plat("windows") then
        add_cxflags("-Ox", "-fp:fast", "-EHsc")
        after_build(function ()
            os.run("cmd /k rd /s /q build; exit")
        end)
    end
```

**Comment by OpportunityLiu** [comment]
你这个用法太高级了，我觉得不太行。。。

**Comment by waruqi** [comment]
@idealvin 一个target name唯一标示一个目标文件，不管kind是啥，都属于同一个target，同名`target("xx")`在xmake中有额外的意义，就是target重入和追加覆写之前的定义。

也就是说，其他地方定义了target("db")，如果其他子xmake.lua想要追加或者覆写一些设置，可以重新进入`target("db")`作用域来改写设置。

你如果要分kind，可以设置不同的target name，但是最后生成的目标文件名和路径，可以通过set_basename和set_targetdir来改写区分，例如：

```lua
target("db_static")
    set_kind("static")
    set_basename("db")

target("db_shared")
    set_kind("shared")
    set_basename("db")
```

这样就可以生成两个不同kind的目标文件，但是目标名是libdb.a和libdb.so，可以达到你要的效果。

需要注意的是，同名静态库和动态库放置在同一个目录，链接的时候（-ldb）会有干扰，建议通过`set_targetdir`分开存储，或者干脆不设置set_basename，就生成为libdb_static.a和libdb_shared.so更稳妥。

**Comment by waruqi** [comment]
另外，你那一坨重复设置，可以放置在子xmake.lua的根域复用，减少冗余设置

```lua
    add_cxxflags("-std=c++11")
    set_optimize("faster")  -- -O2
    set_warnings("all")     -- -Wall

    if is_plat("macosx", "linux") then
        add_cxflags("-g3")
        if is_plat("macosx") then
            add_cxflags("-fno-pie")
        end
        add_links("pthread", "dl")
    end

    if is_plat("windows") then
        add_cxflags("-Ox", "-fp:fast", "-EHsc")
    end

target("db_static")
    set_kind("static")
    -- ...

target("db_shared")
    set_kind("shared")
    -- ...
```

**Comment by waruqi** [comment]
```lua
        after_build(function ()
            os.run("rm -rf build")
        end)

        after_build(function ()
            os.run("cmd /k rd /s /q build; exit")
        end)
```

这个也没必要，如果要清掉整个build目录，只需要执行 xmake clean --all 或者 xmake c -a

默认的clean只会请一些临时obj文件，这样rebuild会快不少，要整个全清 包括target file 需要加 --all

或者定制自己的 after_clean 脚本。而不是放在after_build里面调用系统删除命令，xmake 也有内置的 os.rm 可以删文件和目录，更加通用

**Comment by idealvin** [comment]
@waruqi 好的，非常感谢，我正想请教快捷的删 build 目录的方法..

**Comment by waruqi** [comment]
```lua
    add_includedirs("..")
    add_linkdirs("../lib")
    add_links("base", "db")
```

这块也没必要，通过target的add_deps添加静态库依赖target，可以自动继承links, linkdirs, includedirs相关设置。这块可以看下add_deps文档描述 ，直接加`add_deps("base", "db")`就好

**Comment by waruqi** [comment]
add_cxxflags("-std=c++11")

这个建议用set_languages("c++11")更加通用，适配不同编译器

**Comment by idealvin** [comment]
@waruqi 再请教两个问题:
1. add_defines 如何定义带值的宏？文档里好像没找到
2. is_arch("x64")   文档里说用 "x86_64"，但我在 windows 上测试发现必须用 "x64"

**Comment by waruqi** [comment]
add_links("pthread", "dl")

系统库的链接建议用add_syslinks， 会自动放置在所有add_links最后，确保链接顺序ok

**Comment by waruqi** [comment]
> add_defines 如何定义带值的宏？文档里好像没找到
add_defines("A=1")

> is_arch("x64") 文档里说用 "x86_64"，但我在 windows 上测试发现必须

不同平台，arch是不一样的，请根据xmake f --help里面提示的对应plat的arch列表为准

**Comment by idealvin** [comment]
@waruqi 好的好的，非常感谢您的指导，现在去改进一下我的编译脚本..
