### ISSUE TITLE
c++编译缓慢, 希望支持预编译功能

### ISSUE THREAD

**Issue by fabri-guo** [xmake-io/xmake#641]
### 你在什么场景下需要该功能？

请尽量清晰精准地描述你碰到的问题。

### 描述可能的解决方案

请尽量清晰精准地描述你期待我们要做的，描述你想到的实现方案。

### 描述你认为的候选方案

请尽量清晰精准地描述你能接受的候选解决方案。

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by waruqi** [comment]
原本就支持 请看文档 https://xmake.io/#/zh-cn/manual/project_target?id=targetset_pcxxheader

**Comment by fabri-guo** [comment]
&nbsp; 感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ruki"<notifications@github.com&gt;; 
发送时间: 2019年12月12日(星期四) 下午4:38
收件人: "xmake-io/xmake"<xmake@noreply.github.com&gt;; 
抄送: "郭胜锋"<254033410@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xmake-io/xmake] c++编译缓慢, 希望支持预编译功能 (#641)




Closed #641.

**Comment by fabri-guo** [comment]
xmake&nbsp; 如何设置平台工具集, 只能看到windows&nbsp; [x86|x64], 但是至于 Visual Studio 2015 - Windows XP (v140_xp)的这种情况 如何设置?






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ruki"<notifications@github.com&gt;; 
发送时间: 2019年12月12日(星期四) 下午4:38
收件人: "xmake-io/xmake"<xmake@noreply.github.com&gt;; 
抄送: "郭胜锋"<254033410@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xmake-io/xmake] c++编译缓慢, 希望支持预编译功能 (#641)




原本就支持 请看文档 https://xmake.io/#/zh-cn/manual/project_target?id=targetset_pcxxheader

**Comment by waruqi** [comment]
见：https://github.com/xmake-io/xmake/issues/229
