### ISSUE TITLE
windows 10 上使用 xmake f -p mingw 结果 cross配置项错误

### ISSUE THREAD

**Issue by structure-charger** [xmake-io/xmake#643]
系统里有装vs2017 ，llvm全套（独立于msys安装），msys mingw-gcc 9.2.0全套
执行xmake f -p mingw之后
再执行xmake -v
结果：
configure
{
    arch = x86_64
    debugger = D:\application\compiler\LLVM\bin
    bin = D:\msys2\mingw64\bin
    ccache = true
    buildir = build
    mode = release
    ndk_stdcxx = true
    host = windows
    cross = wasm-
    mingw = D:\msys2\mingw64
    kind = static
    theme = default
    vs = 2017
    vcpkg = D:\C-project\vcpkg
    plat = mingw
}
checking for the c compiler (cc: gcc) ... no
checking for the c compiler (cc: gcc) ... no
error: cannot get program for cc

使用xmake f --cross=x86_64-w64-mingw32- 尝试手动恢复之后还是没找到gcc
 xmake -v
configure
{
    arch = x64
    ccache = true
    host = windows
    ndk_stdcxx = true
    buildir = build
    mode = release
    plat = windows
    cross = x86_64-w64-mingw32-
    mingw = D:\msys2\mingw64
    kind = static
    theme = default
    vs = 2017
    vcpkg = D:\C-project\vcpkg
    debugger = D:\application\compiler\LLVM\bin
}
checking for the c compiler (cc) ... cl.exe
checking for the ccache ... no
checking for the flags (-Ox -fp:fast) ... ok
[  0%]: compiling.release entr_spec.c
cl.exe -c -Ox -fp:fast -nologo -Fobuild\\.objs\\entr\\windows\\x64\\release\\.\\entr_spec.c.obj entr_spec.c
error: entr_spec.c
d:\c-project\entr\entr.c(17): fatal error C1083: ▒޷▒▒򿪰▒▒▒▒ļ▒: ▒▒sys/param.h▒▒: No such file or directory
看上面报错还是用的默认的vs cl编译器，是不是需要全部手动设置一遍才能正常生效？

**Comment by structure-charger** [comment]
或者系统path是不是需要去掉一些其他编译器的配置才能保证gcc单独生效？

**Comment by waruqi** [comment]
请根据自身环境情况，自己追加--bin= 等相关路径，可以看下相关文章介绍：https://tboox.org/cn/2019/12/05/quickstart-9-cross-compile/

也可以看下交叉编译文档：https://xmake.io/#/zh-cn/guide/configuration?id=%e4%ba%a4%e5%8f%89%e7%bc%96%e8%af%91

> 使用xmake f --cross=x86_64-w64-mingw32- 尝试手动恢复之后还是没找到gcc

只有xmake f -p cross/linux/mingw 这三平台才支持走交叉编译，默认不指定平台，会采用windows平台，也就是用的msvc，具体细节看下文档
