### ISSUE TITLE
编译时怎么移除默认的cxxflags

### ISSUE THREAD

**Issue by fuyunbo** [xmake-io/xmake#644]
请问编译的时候怎么移除自动生成的编译选项，比如我要移除下面的编译文件中-gcc-toolchain，应该怎么做呢
/home/fyb/Android/ndk/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -c -g -O0 -std=c++11 -Ithirdparty -I/home/fyb/Android/ndk/android-ndk-r20/sources/android/cpufeatures -fPIC -pthread -pipe -frtti -fexceptions -DANDROID -DNDEBUG --sysroot=/home/fyb/Android/ndk/android-ndk-r20/sysroot -isystem /home/fyb/Android/ndk/android-ndk-r20/sysroot/usr/include/x86_64-linux-android -I/home/fyb/Android/ndk/android-ndk-r20/sources/cxx-stl/llvm-libc++/include -I/home/fyb/Android/ndk/android-ndk-r20/sources/cxx-stl/llvm-libc++/libs/x86_64/include -I/home/fyb/Android/ndk/android-ndk-r20/sources/cxx-stl/llvm-libc++abi/include -Qunused-arguments -target x86_64-none-linux-android -gcc-toolchain /home/fyb/Android/ndk/android-ndk-r20/toolchains/x86_64-4.9/prebuilt/linux-x86_64 -D__ANDROID_API__=29 -o build/.objs/cryptopp/android/x86_64/debug/thirdparty/cryptopp/gf2_32.cpp.o thirdparty/cryptopp/gf2_32.cpp

**Comment by waruqi** [comment]
-gcc-toolchain 这个ndk编译是必须的 为啥要移呢

**Comment by fuyunbo** [comment]
因为我在编译一个开源库的android版本时如果加上这一句就会报错，
如果加上就会报错，但是这个又是一个开源库，不希望去修改源码，而且也只有这个x86_64的架构才有这个问题，所以想去掉，最下面是错误信息，谢谢：
/home/fyb/Android/ndk/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -c -g -O0 -std=c++11 -Ithirdparty -I/home/fyb/Android/ndk/android-ndk-r20/sources/android/cpufeatures -fPIC -pthread -pipe -frtti -fexceptions -DANDROID -DNDEBUG --sysroot=/home/fyb/Android/ndk/android-ndk-r20/sysroot -isystem /home/fyb/Android/ndk/android-ndk-r20/sysroot/usr/include/x86_64-linux-android -I/home/fyb/Android/ndk/android-ndk-r20/sources/cxx-stl/llvm-libc++/include -I/home/fyb/Android/ndk/android-ndk-r20/sources/cxx-stl/llvm-libc++/libs/x86_64/include -I/home/fyb/Android/ndk/android-ndk-r20/sources/cxx-stl/llvm-libc++abi/include -Qunused-arguments -target x86_64-none-linux-android -gcc-toolchain /home/fyb/Android/ndk/android-ndk-r20/toolchains/x86_64-4.9/prebuilt/linux-x86_64 -D__ANDROID_API__=29 -o build/.objs/cryptopp/android/x86_64/debug/thirdparty/cryptopp/sosemanuk.o thirdparty/cryptopp/sosemanuk.cpp
**thirdparty/cryptopp/sosemanuk.cpp:372:3: error: unknown token in expression
                INTEL_NOPREFIX
                ^
thirdparty/cryptopp/cpu.h:46:25: note: expanded from macro 'INTEL_NOPREFIX'
        #define INTEL_NOPREFIX ".intel_syntax;"**

**Comment by waruqi** [comment]
这错误跟-gcc-toolchain 有啥关系，是库自身的代码编译问题

**Comment by fuyunbo** [comment]
下面这个是它工程编译命令行，这个里面是没有-gcc-toolchain的
/home/fyb/Android/ndk/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF /home/fyb/Workspace/algorithm/xy/algorithm/packages/cryptopp-android/.cryptopp/cryptopp-8.2/obj/local/x86_64/objs/cryptopp_static/sosemanuk.o.d -target x86_64-none-linux-android23 -fdata-sections -ffunction-sections -fstack-protector-strong -funwind-tables -no-canonical-prefixes  --sysroot /home/fyb/Android/ndk/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/sysroot -g -Wno-invalid-command-line-argument -Wno-unused-command-line-argument  -fno-addrsig -fno-exceptions -fno-rtti -fPIC -O2 -DNDEBUG  -I/home/fyb/Android/ndk/android-ndk-r20/sources/android/cpufeatures -I/home/fyb/Android/ndk/android-ndk-r20/sources/cxx-stl/llvm-libc++/include -I/home/fyb/Android/ndk/android-ndk-r20/sources/cxx-stl/llvm-libc++/../llvm-libc++abi/include -I/home/fyb/Workspace/algorithm/xy/algorithm/packages/cryptopp-android/.cryptopp/cryptopp-8.2 -std=c++11    -DANDROID  -nostdinc++ -Wa,--noexecstack -Wformat -Werror=format-security -Wall -frtti -fexceptions  -c  /home/fyb/Workspace/algorithm/xy/algorithm/packages/cryptopp-android/.cryptopp/cryptopp-8.2/sosemanuk.cpp -o /home/fyb/Workspace/algorithm/xy/algorithm/packages/cryptopp-android/.cryptopp/cryptopp-8.2/obj/local/x86_64/objs/cryptopp_static/sosemanuk.o

**Comment by fuyunbo** [comment]
找到一个其它解决方法，谢谢了
