### ISSUE TITLE
xmake run 设置工作目录

### ISSUE THREAD

**Issue by codehz** [xmake-io/xmake#645]
### 你在什么场景下需要该功能？

xmake run 默认的工作目录在 `build/<os>/<arch>/<mode>` 这种位置，并不是特别好用。。
我觉得应该要添加一个选项设置工作目录

### 描述可能的解决方案

添加选项 -C <path>
如 xmake run -C . XXX ARG
表示在当前目录执行

### 描述你认为的候选方案

备选方案当然就是直接在当前目录执行而不是在那么深的目录跑了

**Comment by waruqi** [comment]
有的哦：`xmake run -w/--workdir=`

或者xmake.lua里面加 set_rundir 详情见文档：https://xmake.io/#/zh-cn/manual/project_target?id=targetset_rundir

更多细节见：https://github.com/xmake-io/xmake/issues/440

**Comment by codehz** [comment]
哎！居然没发现有这个功能，抱歉打扰了
