### ISSUE TITLE
关于ccache的问题

### ISSUE THREAD

**Issue by j7252008** [xmake-io/xmake#649]
> 注：如果是`问题报障`或者`特性请求`，请选择对应issues模板，否则一律不回复。

### 描述问题详情
请在这描述你的问题详情。

在编译是发现使用ccache compile很快，是缓存了中间文件吗，这个需要清理吗？如何清理

**Comment by waruqi** [comment]
不需要清理，这个你自己google下ccache的使用就好了。

**Comment by j7252008** [comment]
明白了，谢谢
