### ISSUE TITLE
xmake create 创建了错误的目录

### ISSUE THREAD

**Issue by codehz** [xmake-io/xmake#652]
### 描述问题

```bash
cd /tmp
mkdir test
cd test
xmake create
```
然后创建出了/tmp/test/test ...

### 期待的结果

在当前目录创建项目文件而不是子目录

### 错误信息

（无）

### 相关环境

xmake v2.2.9+201912211044
arch linux

### 其他信息

如果使用 xmake create . 倒是能创建在当前目录了，但是创建出的target也是.
我希望xmake create .和xmake create保持等价，都是在当前目录创建项目，并且target也为当前目录的名字

**Comment by waruqi** [comment]
是的，默认不会在当前目录下展开，你需要指定工程目录，试试：

```console
xmake create -P .
xmake create -P . test
```
