### ISSUE TITLE
add_requires | system = true 时可选检查

### ISSUE THREAD

**Issue by codehz** [xmake-io/xmake#653]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题

add_requires参数 system = true 时，应该允许在系统未安装时跳过强制检查

### 期待的结果

```lua
add_requires("uring", {system = true})

target("demo_uring")
    set_default(has_config("demo"))
    set_kind("binary")
    add_deps("ctxco")
    add_packages("uring", {system = true})
    on_load(function (target)
        if not has_package("uring") then
            target:set("enabled", false)
        end
    end)
    add_defines("_GNU_SOURCE")
    add_files("src/demo/uring.c")
target_end()
```
然后当系统中不存在uring安装时跳过，而不中断构建（静默忽略目标，因为实际上这个目标已经被disabled了，不应该再考虑他的依赖库）

### 错误信息

error: The package(uring) not found!

### 相关环境

xmake: 2.2.9

### 其他信息
（我觉得针对这种情况应该设计一个新的指令，例如add_optional，然后自动根据依赖关系禁用目标（build --all的时候还可以顺便输出一些警告，如由于XXX依赖关系未满足，跳过YYY目标的生成（用英语）

**Comment by waruqi** [comment]
之前只对 system = false 禁用从系统优先检测的逻辑处理，system = true 只启用从系统检测 还没处理，回头我改进下。

**Comment by waruqi** [comment]
哦，我忘记了，其实这里没有问题，你加个 optional = true 就行了。。默认是必选的 依赖包。。即使是找system包。如果摘不到 还是会默认提示用户 。。让用户去配置系统库

但是可以设置为可选包 。。找不到就不会提示了

这块有文档描述：https://xmake.io/#/zh-cn/package/remote_package?id=%e5%8f%af%e9%80%89%e5%8c%85%e8%ae%be%e7%bd%ae

**Comment by waruqi** [comment]
```lua

add_requires("uring", {system = true, optional = true})

target("test")

    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("uring")
    on_load(function (target)
        if has_package("uring") then
            print("found")
        end
    end)
```
