### ISSUE TITLE
不同的工程目标支持设置编译架构

### ISSUE THREAD

**Issue by dulingzhi** [xmake-io/xmake#654]
### 你在什么场景下需要该功能？

单个解决方案中某些工程需要x86平台，某些需要x64平台编译

### 描述可能的解决方案

使用target设置的arch

### 描述你认为的候选方案

类似premake的 https://github.com/premake/premake-core/wiki/architecture

### 其他信息

虽然用多个独立工程可用解决，但生成的IDE不在一起，开发体验不理想。

**Comment by waruqi** [comment]
xmake的机制不一样，主要用于命令下的直接构建，而不是像premake那样主要用于生成ide文件，因此同时只处理同一个arch的构建

对于生成vsproj等ide程序虽然也支持，但只是作为插件提供，并不属于主要功能，暂时先这么凑合着用吧，而且vsproj的生成默认就是多个arch都生成好的，直接在vs里面选择arch切换编译就好了
