### ISSUE TITLE
关于os.exec的两点建议

### ISSUE THREAD

**Issue by wax1223** [xmake-io/xmake#656]
## 环境
所使用的版本是xmake v2.2.9+201912201704
操作系统是win10 x64 Pro1809

## 背景
尝试使用xmake来构建android的app
由于xmake（在我的认知里）只能生成so文件，无法将so文件打包成.apk文件。
只能手动编写打包程序，其中在打包的步骤中有一个叫dx的程序，它是本质上是一个.bat的批处理文件。还有一个aapt的程序

### 问题一
```
os.exec("dx --version")
```
会得到
![image](https://user-images.githubusercontent.com/7008358/71640922-bb95c680-2cd6-11ea-804c-4dfbb2b4e976.png)

而在命令行执行dx --version确能得到正确的输出。 从xmake提供的错误信息中也完全无法推测出问题所在。
### 解决办法
经过了一段时间的摸索，发现只要将命令从os.exec("dx --version")改为os.exec("dx.bat --version")就可以获得想要的结果。
### 建议
希望os.exec能输出更多更详细的错误信息而不是只有一行error。

### 问题二
```
import("core.project.config")
os.cd(android_build_dir)
os.exec("aapt add -v hello.unaligned.apk lib/arm64-v8a/libhello.so") 
```
![image](https://user-images.githubusercontent.com/7008358/71641089-85a61180-2cd9-11ea-9d21-eba410ba8c35.png)

lib/arm64-v8a/libhello.so会被转换为lib\arm64-v8a\libhello.so导致打包失败。
```
iimport("core.project.config")
--os.cd(android_build_dir)
os.exec("aapt add -v hello.unaligned.apk lib/arm64-v8a/libhello.so") 
```
不执行 os.cd(android_build_dir)的话，不会发生转换，但是由于目录不对，无法打包
![image](https://user-images.githubusercontent.com/7008358/71641085-60190800-2cd9-11ea-8724-b094bc54b0ab.png)
### 解决办法
直接直接调用process模块来避免发生转换
```
local proc = process.open("aapt add -v hello.unaligned.apk lib/arm64-v8a/libhello.so", outfile, errfile)
if proc then
    local waitok, status = process._subprocess.wait(proc, -1)
    process._subprocess.close(proc)
end
```

官方文档上process的使用示例中是process.wait，然而在我的环境中会出现错误。
````
error: attempt to call field 'wait' (a nil value)
````
将process.wait改为process._subprocess.wait(proc, -1)程序就能正常运行。

### 建议
希望os.exec()可以提供一个选项，不解析命令本身的内容，而是直接执行后返回结果。

对我来说，xmake是一个不错的工具，使用起来虽然小问题不断，但是总体体验不错。希望xmake能越来越好。

谢谢你们创造了xmake. :)

**Comment by waruqi** [comment]
> 希望os.exec能输出更多更详细的错误信息而不是只有一行error。

返回failed(-1)，通常都是 dx程序没找到，导致调用失败。这块的提示 我回头改进下

> os.exec("aapt add -v hello.unaligned.apk lib/arm64-v8a/libhello.so") 

因为是完整字符串传入，这里是会处理各种转换，如果不想转，保留原始参数，可以使用os.execv接口

```lua
 os.execv("aapt", {"add", "-v", "hello.unaligned.apk", "lib/arm64-v8a/libhello.so") 
```

> 官方文档上process的使用示例中是process.wait，然而在我的环境中会出现错误。

这块是因为2.2.9我对process模块做了些改动，因为目前很少有人直接用process接口，所以我暂时忘记更新文档了。。

改成这样就可以了，现在我都实例化了。。

```lua
if proc then
    local waitok, status = proc:wait(-1)
    proc:close()
end
```

**Comment by waruqi** [comment]
关于process的文档，我稍微更新了下，还有os.runv/os.execv的文档 我也稍微完善了下。。

**Comment by idealvin** [comment]
@waruqi 
os.exec() 在检测到程序返回 -1 时，会报一行 error。
在 c/c++ 代码里调用 exit(-1)，会导致 xmake run 执行完后报一行错误。
因为这个问题，我直接将 exit(-1) 改成了 exit(0)，代码在[这里](https://github.com/idealvin/co/commit/0a13abc3bac7e2cb90397bbc290407ca67a644f3)

**Comment by waruqi** [comment]
> @waruqi
> os.exec() 在检测到程序返回 -1 时，会报一行 error。
> 在 c/c++ 代码里调用 exit(-1)，会导致 xmake run 执行完后报一行错误。
> 因为这个问题，我直接将 exit(-1) 改成了 exit(0)，代码在[这里](https://github.com/idealvin/co/commit/0a13abc3bac7e2cb90397bbc290407ca67a644f3)

这是正常行为，exit(-1) 说明子命令执行失败了，里面有错误发生，os.exec默认检测到会直接中断，这也是期待的行为，如果子命令正常完成执行才是exit(0)

如果exit(-1)了，还是假设这个子命令是正常退出，原本就是不对的。

如果你这非要使用exit(-1)作为正常退出，不想抛出异常去中断xmake，可以自己加个try-catch捕获后忽略掉

```lua
target("test")
    on_run(functon (target)
        try 
        { 
             function ()
                  os.exec(target:targetfile())
             end
         }
    end)
```

而前面的 dx命令找不到，目前我也是默认作为-1直接处理的，只不过暂时没提示更详细的错误信息，来区分是找不到失败，还是执行exit(-1)的子命令内部失败

后面我会对于找不到的执行失败，会提供更详细的错误提示，比如 command not found! 这种

**Comment by idealvin** [comment]
找不到命令，可以提示错误信息，程序返回 -1，似乎可以忽略不管，xmake 调用 os.exec() 将程序拉起来就可以了，至于程序报错是程序自己的事，与 xmake 应该没有关系。
而且运行出错的程序，一般自己会有错误信息

**Comment by idealvin** [comment]
很多程序会打印错误信息，然后调用 exit(-1) 退出，我这边建议 xmake 只负责拉起程序，没拉起来应该报个错误信息，一旦拉起来了，就可以放手不管了

**Comment by waruqi** [comment]
> 找不到命令，可以提示错误信息，程序返回 -1，似乎可以忽略不管，xmake 调用 os.exec() 将程序拉起来就可以了，至于程序报错是程序自己的事，与 xmake 应该没有关系。
> 而且运行出错的程序，一般自己会有错误信息

所以 xmake run后，程序它自己的错误信息 自己会回显，然后xmake中断后，用户查看错误信息

os.exec默认就是回显的不会隐藏程序自身的错误输出

但也有程序其实就是内部出错了，但是没内部print输出自己的错误信息，如果xmake默认不检测后中断，用户以为程序正常执行完了，反而会误导

**Comment by OpportunityLiu** [comment]
ERROR code 是程序的重要环节，怎么能默认忽略的啊。。。

**Comment by waruqi** [comment]
> 很多程序会打印错误信息，然后调用 exit(-1) 退出，我这边建议 xmake 只负责拉起程序，没拉起来应该报个错误信息，一旦拉起来了，就可以放手不管了

所以这个只是特定部分用户的特殊需求而已，这种特殊需求，xmake内部默认的逻辑不会去针对每个用户 都去适配一边，xmake提供了各种灵活的配置，让用户自己去定制，就比如我刚上面说的配置方式

```
target("test")
    on_run(functon (target)
        try 
        { 
             function ()
                  os.exec(target:targetfile())
             end
         }
    end)
```

你完全可以自己忽略掉，但是xmake不会

**Comment by idealvin** [comment]
在 co 项目中，xmake build flag 后，执行
```cpp
xmake run flag i32=8t
```
xmake 会报一行 error （程序中调用exit(-1)引起)，看着很奇怪。程序中调用 exit(-1) 可能并不是什么错误行为。
不管怎样，我已经将 exit(-1) 改成了 exit(0)，暂时这这样吧，先不管了

**Comment by OpportunityLiu** [comment]
http://www.cplusplus.com/reference/cstdlib/exit/ 
exit(-1)为啥不是错误行为，那说明程序有问题啊

**Comment by waruqi** [comment]
> xmake 会报一行 error （程序中调用exit(-1)引起)，看着很奇怪。程序中调用 exit(-1) 可能并不是什么错误行为。

xmake默认假定子命令是严格按照exit的规范走的，除了0和EXIT_SUCCESS，其他都是非正常退出。

```c
If status is zero or EXIT_SUCCESS, a successful termination status is returned to the host environment.
If status is EXIT_FAILURE, an unsuccessful termination status is returned to the host environment.
Otherwise, the status returned depends on the system and library implementation.
```

否则每个子命令都按自己的标椎走，返回各种非0 code作为正常退出，那就乱套了，目前这边执行这么多toolchains，从来没遇到过-1作为正常退出的。。

如果用户非要-1作为正常退出，可以按照我刚说的方式，自定义on_run去忽略异常，xmake也就不会报error了

**Comment by idealvin** [comment]
@waruqi @OpportunityLiu 
嗯，我现在已经改成 exit(0) 了，麻烦你们了

**Comment by waruqi** [comment]
@idealvin 

```console
$ xmake run flag i32=8t
out of range for int32: 8t
error: execv(Y:\co\build\windows\x64\release\flag.exe i32=8t) failed(-1)!
```

我看你的代码，本质上已经输出内部错误了，代码里面exit(-1)是正常行为，也回显了out of range错误信息，这本身没问题，没必要改成exit(0)

你的需求只是想隐藏最后一行error line而已，觉得看着别扭而已，所以我个人建议还是定制下xmake.lua，如果真的不想看到这行error line `error: execv(Y:\co\build\windows\x64\release\flag.exe i32=8t) failed(-1)!`，只想看out of range的话

```
target("test")
    on_run(functon (target)
        try { function ()
                  os.exec(target:targetfile())
             end}
    end)
```

xmake默认就忽略了，仅回显你程序自己error info的输出

**Comment by idealvin** [comment]
@waruqi 
非常感谢！对的，我只是希望  `xmake run flag i32=8t` 与手动执行 `./flag i32=8t`，得到相同的输出结果。我还是调用 exit(0) 吧，本来我就不太关心 exit() 的状态码，错误信息输出就足够了
