### ISSUE TITLE
2.2.9之後的 yasm 運作異常

### ISSUE THREAD

**Issue by orzuk-lmj** [xmake-io/xmake#657]
在2.2.8版本的時候，使用底下這種語法設置 yasm，正常使用且編譯成功。
`set_tools({as = path.absolute("../../../../Tools/yasm/msw/yasm.exe")})`
然後在on_load中添加.asm檔案
`target:add("files", "lib/vpx_dsp/x86_64/avg_ssse3_x86_64.asm")`

更新2.2.9之後，出現錯誤訊息
`error: unknown source file: lib\vpx_dsp\x86_64\avg_ssse3_x86_64.asm`
然後看到修訂紀錄，所以跟著改為
`set_toolchain("as", path.absolute("../../../../Tools/yasm/msw/yasm.exe"))`這種使用方法，但還是錯誤。

**Comment by waruqi** [comment]
恩 回头我看下 跟这个api没啥关系，两个都能用，是这边的构建规则做了重构，把不同语言剥离到独立的构建规则了，而你这边唯一的asm文件放在on_load里面去添加了，因此xmake暂时没检测到asm构建规则是否需要

目前临时的解决办法，就是把asm放到add_files外面去添加，如果必须放在on_load里，可以外面添加一个空asm文件，暂时告诉xmake需要asm构建规则

而对于on_load里面添加asm的情况，我回头看看稳定处理下

**Comment by waruqi** [comment]
因为对于files的rules识别目前是在on_load之前完成的，所以在on_load之后，暂时还没动态的更新rules。

如果非要在on_load里面动态添加files，并且外层没add_files添加过任何asm，建议手动加上asm的rules就行了。。

```lua
target("test")

    set_kind("binary")
    add_files("src/*.cpp")

    add_rules("asm") <-------------- 强制对当前target启用asm构建规则
    on_load(function (target)
        target:add("files", "src/*.S")
    end)
```

**Comment by orzuk-lmj** [comment]
感謝!  在最外層設置規則之後就正常了。
``` lua
add_rules("asm")
set_toolchain("as", path.absolute("../../../../Tools/yasm/msw/yasm.exe"))
```

但是另外嘗試了底下這種卻會錯誤，找不到yasm，貌似直接使用了ml64
``` lua
set_config("as", path.absolute("../../../../Tools/yasm/msw/yasm.exe"))
```
顯示的錯誤訊息為
``` lua
[  1%]: compiling.debug lib\vpx_dsp\x86\add_noise_sse2.asm
ml64.exe -c -W3 -WX -I..\\\\_build\\\\vs2017-x64-debug/generated -Ilib -D__platform_windows__ -D__config_x64__ -D__config_debug__ -DUNICODE -D_UNICODE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -DDEBUG -D_DEBUG -nologo -Fo..\\_build\\vs2017-x64-debug\\.objs\\vpx\\windows\\x64\\debug\\lib\\vpx_dsp\\x86\\add_noise_sse2.asm.obj lib\\vpx_dsp\\x86\\add_noise_sse2.asm
error: 䄠獳浥汢湩㩧氠扩癜硰摟灳硜㘸㙟尴癡彧獳敳弳㡸弶㐶愮浳਍楬屢灶彸獤屰㡸弶㐶慜杶獟獳㍥硟㘸㙟⸴獡⡭ㄱ ›慦慴⁬牥潲⁲ㅁ〰㨰慣湮瑯漠数⁮楦敬㨠∠桴物彤慰瑲⽹㡸椶据砯㘸湩⹣獡≭਍
stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:766: in function 'raiselevel'
        @programdir\core\sandbox\modules\utils.lua:206: in function 'assert'
        @programdir\modules\private\action\build\object.lua:78: in function '_do_build_file'
        @programdir\modules\private\action\build\object.lua:117: in function '_build_object'
        @programdir\modules\private\action\build\object.lua:141: in function <@programdir\modules\private\action\build\object.lua:135>
```

**Comment by waruqi** [comment]
toolchain的设置尽量用set_toolchain，更加灵活，可独立target设置，set_config有些Case的设置场景不一定能覆盖到，这块我回头看看能否再改进。。

**Comment by waruqi** [comment]
> 想問他們的相對路徑應該都是基於 project dir 對嗎?

恩，这两api的参数值设置并不要求path类型，所以内部不处理路径转换，所以跟add_files这种基于xmake.lua所在路径有点差异，默认都是基于projectdir的，你也可以加上"$(projectdir)/xxxx"来设置根目录

**Comment by orzuk-lmj** [comment]
謝謝。修正後都可以正常使用了，順帶說一下就是，會選擇在on_load中設置files是因為需要複雜條件判斷的時候，放置在那裏貌似比放在外層方便，也更容易掌握條件檢查的執行順序。

**Comment by waruqi** [comment]
恩，里面确实处理复杂逻辑会更灵活点，那这个就先这样吧。
