### ISSUE TITLE
有關生成pdb檔案的困惑

### ISSUE THREAD

**Issue by orzuk-lmj** [xmake-io/xmake#658]
### 描述问题
早先的版本，不論是否為靜態庫的專案，編譯後將會自動生成 `TargetName.pdb` 放在 `TargetName.lib`同一層的資料夾中。

現在這個版本中
- 如果為靜態庫專案，編譯後則生成`compile.TargetName.pdb`
- 如果是動態庫專案，編譯後則同時生成兩個pdb檔案`compile.TargetName.pdb` 和 `TargetName.pdb` 

    ``` lua
    if is_plat("windows") then
        if is_mode("debug") or is_mode("profile") then
            local symbolfile = path.absolute(target:symbolfile())
            if targetkind == "binary" then
                -- copy symbolfile to install bin_dir
            else
                -- copy symbolfile to install lib_dir
            end
        end
    end
    ```

### 期待的结果

想請問這麼設計的目的是什麼?  因為庫的debug模式我也都會打包pdb給其他人使用，現在有兩個檔案造成了些困惑。

最期望的結果就是，生成的pdb檔案名稱維持`TargetName.pdb`

**Comment by waruqi** [comment]
见：https://github.com/xmake-io/xmake/pull/495

目前link/compile的pdb是分离的，具体详情见上面的link，静态库的就直接用compile.TargetName.pdb吧，动态库和可执行文件就直接用targetname.pdb吧。

**Comment by OpportunityLiu** [comment]
反正直接把所有pdb往一个文件里塞在增量编译的时候会有问题，具体怎么回事我也没摸清楚

**Comment by waruqi** [comment]
目前先这样吧，回头我研究下，可以先确认下vs里面设置同一pdb在增量编译下是否ok，如果ok可以通过msbuild看下详细的编译命令，是怎么处理的 如果也不行就只能先这样了

**Comment by waruqi** [comment]
这个如果之后有遇到啥问题 再开好了
