### ISSUE TITLE
xmake support cp

### ISSUE THREAD

**Issue by idealvin** [xmake-io/xmake#660]
### Is your feature request related to a problem? Please describe.
After `xmake build`, the target may be in a deep path like:
```cpp
build/linux/x86_64/release/
```
It's not convenient to copy the target out as the path is rather long.

### Describe the solution you'd like
`xmake` may support a new command `cp`, and the target may be copied somewhere as below:
```sh
xmake cp target_name .   # copy to the current dir
```

**Comment by OpportunityLiu** [comment]
you mean `xmake l cp`?

**Comment by waruqi** [comment]
You can use `xmake install` or `xmake package` commands.

```console
xmake install -o /xxx/installdir
```

or

```console
xmake package -o /xxx/packagedir
```

You can also set the target output directory in xmake.lua

```lua
target("test")
    set_targetdir("$(buildir)")
```

It will generate target file to the build/test.exe after building.

**Comment by idealvin** [comment]
@waruqi 
我试了下 xmake install，在多项目情况下，可能不大好控制. 
改天我自己研究下 xmake install/package.

**Comment by waruqi** [comment]
> @waruqi
> 我试了下 xmake install，在多项目情况下，可能不大好控制.
> 改天我自己研究下 xmake install/package.

你是指哪方面不好控制呢，xmake.lua里面也可以通过 `add_installfiles` 来细粒度控制安装文件的路径

也可以通过自定义 on_install或者 after_install脚本 来更灵活控制 安装逻辑，去调用os.cp 在里面复制安装文件

**Comment by idealvin** [comment]
> > @waruqi
> > 我试了下 xmake install，在多项目情况下，可能不大好控制.
> > 改天我自己研究下 xmake install/package.
> 
> 你是指哪方面不好控制呢，xmake.lua里面也可以通过 `add_installfiles` 来细粒度控制安装文件的路径
> 
> 也可以通过自定义 on_install或者 after_install脚本 来更灵活控制 安装逻辑，去调用os.cp 在里面复制安装文件

有空我研究下 xmake 内部实现，看看能不能自己实现一下，免得老给你们添麻烦 😸

**Comment by waruqi** [comment]
> > > @waruqi
> > > 我试了下 xmake install，在多项目情况下，可能不大好控制.
> > > 改天我自己研究下 xmake install/package.
> > 
> > 
> > 你是指哪方面不好控制呢，xmake.lua里面也可以通过 `add_installfiles` 来细粒度控制安装文件的路径
> > 也可以通过自定义 on_install或者 after_install脚本 来更灵活控制 安装逻辑，去调用os.cp 在里面复制安装文件
> 
> 有空我研究下 xmake 内部实现，看看能不能自己实现一下，免得老给你们添麻烦

这块文档里也有说明的，你可以查下 add_installfiles on_install这些的使用 也可以直接在issues问 没关系的

**Comment by idealvin** [comment]
我先用 xmake install 吧，也能满足需求
