### ISSUE TITLE
window10 vs2008导入protobuf-cpp编译报错

### ISSUE THREAD

**Issue by jococi** [xmake-io/xmake#661]
### 描述问题
install protobuf-cpp 3.8.0 失败

### 错误信息

\> Executing task: xmake -w <

checking for the Microsoft Visual Studio (x86) version ... 2008
note: try installing these packages (pass -y to skip confirm)?
in xmake-repo:
  -> protobuf-cpp 3.8.0
please input: y (y/n)
y
  => install protobuf-cpp 3.8.0 .. failed
if you want to get verbose errors, please see:
  -> C:\Users\dayuan\AppData\Roaming\.xmake\cache\packages\2001\p\protobuf-cpp\3.8.0\installdir.failed\logs\install.txt
error: install failed!
终端进程已终止，退出代码: 1

终端将被任务重用，按任意键关闭。

### 相关环境

> window10 
> vs2008
> vscode

### 其他信息
C:\Users\dayuan\AppData\Roaming\.xmake\cache\packages\2001\p\protobuf-cpp\3.8.0\source\protobuf-3.8.0\src\google/protobuf/io/coded_stream.h(113): fatal error C1083: 无法打开包括文件:“atomic”: No such file or directory
C:\Users\dayuan\AppData\Roaming\.xmake\cache\packages\2001\p\protobuf-cpp\3.8.0\source\protobuf-3.8.0\src\google/protobuf/io/coded_stream.h(113): fatal error C1083: 无法打开包括文件:“atomic”: No such file or directory
C:\Users\dayuan\AppData\Roaming\.xmake\cache\packages\2001\p\protobuf-cpp\3.8.0\source\protobuf-3.8.0\src\google/protobuf/stubs/common.h(186): error C2958: 左 圆括号“(”(在“c:\users\dayuan\appdata\roaming\.xmake\cache\packages\2001\p\protobuf-cpp\3.8.0\source\protobuf-3.8.0\src\google\protobuf\stubs\common.h(186)”中找到)未能正确匹配
C:\Users\dayuan\AppData\Roaming\.xmake\cache\packages\2001\p\protobuf-cpp\3.8.0\source\protobuf-3.8.0\src\google/protobuf/stubs/common.h(186): error C2059: 语法错误 : “)”
C:\Users\dayuan\AppData\Roaming\.xmake\cache\packages\2001\p\protobuf-cpp\3.8.0\source\protobuf-3.8.0\src\google/protobuf/stubs/common.h(187): error C2059: 语法错误 : “return”
C:\Users\dayuan\AppData\Roaming\.xmake\cache\packages\2001\p\protobuf-cpp\3.8.0\source\protobuf-3.8.0\src\google/protobuf/stubs/common.h(217): error C2059: 语法错误 : “}”
C:\Users\dayuan\AppData\Roaming\.xmake\cache\packages\2001\p\protobuf-cpp\3.8.0\source\protobuf-3.8.0\src\google/protobuf/stubs/common.h(217): error C2143: 语法错误 : 缺少“;”(在“}”的前面)
C:\Users\dayuan\AppData\Roaming\.xmake\cache\packages\2001\p\protobuf-cpp\3.8.0\source\protobuf-3.8.0\src\google/protobuf/stubs/common.h(217): error C2059: 语法错误 : “}”
D:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\ymath.h(8): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
D:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\ymath.h(8): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
D:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\limits(976): error C2039: “_FDenorm”: 不是“`global namespace'”的成员
D:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\limits(976): error C2065: “_FDenorm”: 未声明的标识符
D:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\limits(976): error C2228: “._Float”的左边必须有类/结构/联合

**Comment by waruqi** [comment]
你的编译器太老，protobuf-cpp的代码 编译不过，这个是代码自身的问题，你可以尝试换高版本编译器去编译protobuf-cpp

**Comment by jococi** [comment]
好的感谢回复
