### ISSUE TITLE
collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by wangzhankun** [xmake-io/xmake#662]
## 环境
* Ubuntu 18.04
* x86_64
* opencv4
![image](https://user-images.githubusercontent.com/35724924/72035275-60656480-32d2-11ea-95dc-13a7a16ff114.png)
![image](https://user-images.githubusercontent.com/35724924/72035320-812dba00-32d2-11ea-8447-4960fac728eb.png)

## 问题
![image](https://user-images.githubusercontent.com/35724924/72035246-488de080-32d2-11ea-8e03-166ca855ff74.png)

## xmake脚本
```
add_syslinks("pthread","gxiapi","cjson")
add_requires( "opencv4")

includes("Main")
includes("Interface")
includes("Share")
includes("Detector")
includes("Infantry")
includes("Sentry")
includes("Hero")
includes("Buff")


target("CV")
    set_kind("binary")
    set_rules("mode.debug", "mode.release")
    set_optimize("fastest")
    add_packages( "opencv4")

set_languages("c99", "cxx11")
```

## 补充说明
相同的脚本配置在opencv3的情况下是可以使用的，但是换到opencv4之后就无法使用了。网上说是lib库链接的原因，但是我又不想手动添加太多的静态库进来。请问如何像在opencv3一样直接链接入所有的静态文件呢？

**Comment by waruqi** [comment]
目前xmake-repo里面没有收录opencv的库，所以你通过add_requires添加，其实走的还是find_packages 从系统库和pkg-config里面找的

看你的错误dl库通过add_syslinks加上就行了，看着也没几个系统依赖库，手动加上也不麻烦

如果要想完全自动追加各种links和依赖的系统库，需要在 https://github.com/xmake-io/xmake-repo 里面收录opencv的库描述，里面设置上对应依赖的系统库才行，这块我后面有时间可以考虑加进去，但是时间不定，如果继续你可以帮忙提个pr自己加一下

**Comment by wangzhankun** [comment]
```
add_requires("opencv")
```
这句话在一个xmake.lua中必须得添加，不添加会报错。我的工程目录如下：

![image_36](https://user-images.githubusercontent.com/35724924/72053347-cf0de680-3301-11ea-8d8a-13a738db5c88.png)
![image_37](https://user-images.githubusercontent.com/35724924/72053357-d33a0400-3301-11ea-98a9-242837fed0bf.png)

在opencv3环境下，所有的xmake.lua都添加```add_requires```则可以正常编译通过，当全部删除之后，则显示报错如下：
![image_38](https://user-images.githubusercontent.com/35724924/72053496-24e28e80-3302-11ea-90af-9f2a7262de70.png)

测试发现，无论在哪个xmake.lua添加这句话都可以，但至少要保留一个。
另外，比较疑惑为啥在opencv3环境下这样编写xmake.lua是可以正常编译链接运行的，为啥opencv4下不可以呢？

**Comment by waruqi** [comment]
就是我刚说的：

> 目前xmake-repo里面没有收录opencv的库，所以你通过add_requires添加，其实走的还是find_packages 从系统库和pkg-config里面找的

可能你opencv3可能直接能通过 pkg-config找完整所有依赖库

你可以直接执行 xmake l find_packages opencv3 opencv4 对比下查找结果

**Comment by wangzhankun** [comment]
在opencv4中的输出如下：
```
includedirs = { 
      "/usr/local/include/opencv4" 
    } 

```
在opencv3的输出中多了一个```/usr/local/include```，请问有什么方式可以进行修改吗

**Comment by wangzhankun** [comment]
![image](https://user-images.githubusercontent.com/35724924/72254535-495ea380-363f-11ea-9ea8-5be3112231b6.png)
我看这里的输出是说/usr/local/lib下的问题，但是find_packages里面是有这个目录的
![image](https://user-images.githubusercontent.com/35724924/72254575-70b57080-363f-11ea-904e-76b011c00441.png)

**Comment by wangzhankun** [comment]
> 目前xmake-repo里面没有收录opencv的库，所以你通过add_requires添加，其实走的还是find_packages 从系统库和pkg-config里面找的
> 
> 看你的错误dl库通过add_syslinks加上就行了，看着也没几个系统依赖库，手动加上也不麻烦
> 
> 如果要想完全自动追加各种links和依赖的系统库，需要在 https://github.com/xmake-io/xmake-repo 里面收录opencv的库描述，里面设置上对应依赖的系统库才行，这块我后面有时间可以考虑加进去，但是时间不定，如果继续你可以帮忙提个pr自己加一下

而且添加```add_syslinks("pthread","gxiapi","cjson","opencv_videoio")```链接仍然是有问题

**Comment by wangzhankun** [comment]
把opencv的编译更改为动态库之后链接成功。打扰你了。
另，请问方便发一下使用xmake进行静态库链接的方法吗？

**Comment by waruqi** [comment]
> 在opencv4中的输出如下：
> 
> ```
> includedirs = { 
>       "/usr/local/include/opencv4" 
>     } 
> ```
> 
> 在opencv3的输出中多了一个`/usr/local/include`，请问有什么方式可以进行修改吗

如果里面没有找到links，说明add_requires不管设置opencv3还是opencv4，其实都没生效，没找到对应的库，我不知道为啥你这为啥opencv3就可以。

你可以追加-v来编译：xmake -v，提供下详细的链接命令给我看下

> 而且添加add_syslinks("pthread","gxiapi","cjson","opencv_videoio")链接仍然是有问题

什么问题？看你刚提供的错误，是缺了dl库符号，还得add_syslinks("dl")才行

> 另，请问方便发一下使用xmake进行静态库链接的方法吗？

设置上-static ldflags就行了

**Comment by waruqi** [comment]
或者你找到对应的opencv库和路径，直接通过add_links/add_linkdirs来加上对应的链接，目前xmake的add_requires是通过pkg-config找的，似乎你这并没有找到对应的库

```
pkg-config --cflags --libs opencv4
```

你可以看看能否找到，所以为啥你这opencv3没找到links，还能link上就有点怪了，可以通过xmake -v看下link阶段命令里面实际的links有哪些

**Comment by waruqi** [comment]
如果要add_requires完整支持opencv3/opencv4，我需要在https://github.com/xmake-io/xmake-repo 里面收录添加对用的opencv库编译描述才行，这样的话，即使系统里面没有opencv也会自动下载编译和安装集成。。

如果你系统上已经有装opencv，可以先研究下pkg-config为啥没找到opencv，因为xmake也是通过这个找的。

后面等我有时间了，可以在https://github.com/xmake-io/xmake-repo里面加上对opencv的支持，如果你这有兴趣，也可以帮忙提个pr到xmake-repo进去加上它

**Comment by waruqi** [comment]
我在xmake-repo里面加上opencv的库描述了，可以试试

先执行 xmake repo -u 更新下仓库

默认使用4.x版本，或者人为指定4.x版本

```lua
add_requires("opencv")
add_requires("opencv 4.x")
```

或者指定使用3.x版本

```lua
add_requires("opencv 3.x")
```

就可以远程下载opencv编译安装和集成了，它依赖的pthread/dl等库都会自动加上links，目前win上我还没支持上，回头有时间可以也加上

如果不想远程拉取编译，只想使用自己本地安装到系统的opencv，也就是你之前的模式，需要指定下system参数。

```lua
add_requires("opencv", {system = true})
```

可以执行 `xmake f -c` 带上-c清下配置cache强制重新检测下。

由于opencv编译比较慢，如果要看详细进度可以追加-v参数来编译。

**Comment by wangzhankun** [comment]
感谢
