### ISSUE TITLE
set_installdir 设置安装目录后，执行 xmake install -o 无法安装到其他目录

### ISSUE THREAD

**Issue by idealvin** [xmake-io/xmake#663]
### set_installdir 设置安装目录后，执行 xmake install -o 无法安装到其他目录

首先调用 set_installdir 设置安装目录:
```lua
set_installdir("pkg")
```
执行 xmake install 确实会安装到 pkg 目录，ok.
执行 xmake install -o xxx，仍然会安装到默认的 pkg 目录，指定的 -o xxx 无效。

### 期待的结果

set_installdir 设置默认安装目录，xmake install -o 指定的目录，优先级应该高于默认安装目录。

**Comment by waruqi** [comment]
嗯 回头我调整下顺序

**Comment by waruqi** [comment]
你更新到dev版本试试 我改了

**Comment by idealvin** [comment]
> 你更新到dev版本试试 我改了 xmake update dev

Yes, It works. I'll update my xmake.lua when the next version of xmake was released.

**Comment by waruqi** [comment]
ok
