### ISSUE TITLE
支持 *nix style 的参数输入

### ISSUE THREAD

**Issue by OpportunityLiu** [xmake-io/xmake#665]
最好是直接支持 *nix style 的参数输入

_Originally posted by @OpportunityLiu in https://github.com/xmake-io/xmake/issues/639#issuecomment-563025781_

要是你觉得可以的话，刚好趁着放假搞一下 @waruqi

**Comment by waruqi** [comment]
只要兼容现有的输入style，可以搞下，不过option.lua这块属于xmake最早期做的module，历史包裹比较重，改起来很多细节需要考虑，还有一些需要重构的，所以我之前一直没去大改。

需要注意的一些地方，比如：

1. option.init 和 option.parse 实现了两遍解析，大部分是冗余的，但有少量差异，理论上应该要合并复用的，不然解析逻辑的改动，得改两遍

如果改动量不大，可以继续保留两份，如果改动量大，可能需要重构复用下了。

2. option._ifelse属于历史遗留代码，后期会考虑去掉，改用 `expr and a or b` 代替，不过这块暂时不动也没事，新加的代码建议不要去用这个了。

3. option.find的实现是不完善的，如果要改动输入style，也许得需要做下兼容或者更完善的实现，考虑复用option.parse

4. boolean的输入还是要兼容处理现有的取值：y/n/yes/no/true/false 包括大小写

还有一些细节我自己都快记不清了，反正你可以根据以上注意事项评估下 是否需要搞下，只要能够很好地兼容现有style的前提下，增加对*nix style的支持，这边很欢迎接受pr
