### ISSUE TITLE
是否内置支持单元测试？

### ISSUE THREAD

**Issue by xflcx1991** [xmake-io/xmake#668]
> 注：如果是`问题报障`或者`特性请求`，请选择对应issues模板，否则一律不回复。

### 描述问题详情
请问有单元测试的内置支持吗？我看了文档，但是没有找到。似乎能用before_* 来做自定义的测试脚本，或者新建一个target或task来解决。但是不能做到测试失败停止继续编译的功能？

**Comment by waruqi** [comment]
测试这块 每个用户需求不同，不太好通用化，另外现有的target/task的定制化 也已经满足需求

比如可以看下这个库里面对 unit_test的处理，也没几行设置：https://github.com/idealvin/co/blob/master/test/xmake.lua

具体要看你这边的需求要做成怎样的，如果觉得不太好写，可以这里描述下，我给你看看

**Comment by waruqi** [comment]
> 但是不能做到测试失败停止继续编译的功能？

就比如上面的例子，默认不编译unittests，可以单个编译执行测试：

```console
xmake build test1
xmake run test1
```

也可以编译运行所有tests

```console
xmake --all
xmake run --all
```

默认是先build所有后运行，如果你要编译一个运行一个，加个task就可以了，然后运行：`xmake tests`

```lua
task("tests")
    on_run(function ()
        for _, testname in ipairs({"test1", "test2", "test3"}) do
            os.exec("xmake build %s", testname)
            os.exec("xmake run %s", testname)
        end
    end)

    set_menu {usage = "xmake tests [options]",   description = "run tests!",   options = {}}
```

**Comment by OpportunityLiu** [comment]
> ```lua
> task("tests")
>     on_run(function ()
>         -- test list你可以通过os.files取下，参考上面的例子
>         for _, testname in ipairs({"test1", "test2", "test3"}) do
>             os.exec("xmake build %s", testname)
>             os.exec("xmake run %s", testname)
>         end
>     end)
> ```


project.lock 现在改进过了吗？我记得以前这种必死锁的

**Comment by waruqi** [comment]
> project.lock 现在改进过了吗？我记得以前这种必死锁的

这个是在task里面执行的，不会有这问题，只有build/install/clean/package这种跟project相关的内部action task才有lock

而独立的task 不一定是为了project服务的，默认都不会去加载project config，更不会去加lock

**Comment by xflcx1991** [comment]
@waruqi 谢谢示例。我改了一下，放弃测试失败停止继续编译。

首先正常写一个主体程序的 target，比如名字是“gogogo”，然后单独为测试写一个target，比如名字是“test1”，这个 target 设置set_kind("binary")，然后使用 gtest 或 catch2 内含任意多个测试，均可以run成功。

这样一来，发布之前首先手动生成测试程序 xmake -b test1 ，再运行测试 xmake run test1。如果测试通过再 xmake -b gogogo，运行 xmake run gogogo

目前这个效果可以接受了，利用测试框架内含多个测试，也不用写那个示例里面的 `for _, test in ipairs(all_tests()) do` 了

**Comment by waruqi** [comment]
ok

**Comment by waruqi** [comment]
支持了 https://github.com/xmake-io/xmake/issues/3381#issuecomment-1751623805
