### ISSUE TITLE
输出显示问题

### ISSUE THREAD

**Issue by OpportunityLiu** [xmake-io/xmake#670]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题

请尽量清晰精准地描述你碰到的问题。
![图片](https://user-images.githubusercontent.com/13471233/72673552-03726700-3aa7-11ea-9b24-e2f82ff4a39d.png)

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 错误信息

```
xmake l os.getwinsize
{
  height = 30,
  width = 65
}
xmake f -h
```

如果可能，请尽量附加程序运行过程中的错误输出信息。

> 如果是xmake相关编译问题，请加上`-v -D`参数运行，并给出详细编译输出信息。

### 相关环境

xmake -dev, win 10

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by OpportunityLiu** [comment]
感觉是stdout的buffer的问题

**Comment by idealvin** [comment]
应该是 vscode 的 terminal，不支持 ansi 的 color 序列

**Comment by idealvin** [comment]
老版本的 powershell, cmd，不支持 ^[38;5;2m 这种东西，[win10](https://stackoverflow.com/questions/2048509/how-to-echo-with-different-colors-in-the-windows-command-line/38617204#38617204) 才开始支持的

**Comment by OpportunityLiu** [comment]
都是一样的序列，哪有上一行识别不了下一行就能识别了的。。
而且改变teminal的宽度，出现这种情况的位置也会变

感觉是一个转义序列存在buffer里分两次写导致的问题

**Comment by idealvin** [comment]
可能是 vscode terminal 的 bug，我这边也遇到过颜色混乱的问题

**Comment by OpportunityLiu** [comment]
好像吧，同样的宽度conhost没啥问题

**Comment by idealvin** [comment]
@OpportunityLiu 
可否帮忙看看 [这里](https://github.com/xmake-io/xmake/pull/667#issuecomment-575961692) ?

**Comment by waruqi** [comment]
这。。。xmake里面怎么解？ 控制每行输出 color code 不被截断？这有点蛋疼哈~

**Comment by OpportunityLiu** [comment]
> 这。。。xmake里面怎么解？ 控制每行输出 color code 不被截断？这有点蛋疼哈~

不是截断问题，就是vscode的console问题，ansi escape code不能分两次写，我们在c里面实现的缓冲和他的缓冲冲突了

**Comment by OpportunityLiu** [comment]
https://github.com/tboox/tbox/blob/f2f7fb594e2642ea3c9be2cc564cb2550330f7fb/src/tbox/platform/windows/stdfile.c#L452

这里加上
```
 tb_stream_sync(stdfile->ofstream, tb_false);
```
就好了，每遇到一个换行就应该强制flush一次

**Comment by waruqi** [comment]
> https://github.com/tboox/tbox/blob/f2f7fb594e2642ea3c9be2cc564cb2550330f7fb/src/tbox/platform/windows/stdfile.c#L452

哦哦  我回头加一下试试，最近tbox正改到一半  暂时先不更新到xmake了，等后面我改完 一并merge过去好了。。

**Comment by waruqi** [comment]
> https://github.com/tboox/tbox/blob/f2f7fb594e2642ea3c9be2cc564cb2550330f7fb/src/tbox/platform/windows/stdfile.c#L452
> 
> 这里加上
> 
> ```
>  tb_stream_sync(stdfile->ofstream, tb_false);
> ```
> 
> 就好了，每遇到一个换行就应该强制flush一次

我tbox更新了，这个地方改过了，可以再试试 dev上。

**Comment by OpportunityLiu** [comment]
我这里转头就复现不了了。。。

**Comment by waruqi** [comment]
额 好吧

**Comment by waruqi** [comment]
等回头复现了再看看吧 这里我先close了 core里面flush我之前也改进过了
