### ISSUE TITLE
Compile ".c" file as C++

### ISSUE THREAD

**Issue by kraigher** [xmake-io/xmake#675]
I am investigating using xmake in an existing project. The projects has files named `".c"` which should be compiled using `"--std=c++11"`. 

I have tried:
```lua
-- No effect
set_languages("c++11", "c++11")

-- No effect
add_files("file.c", {languages = "c++11"})
```

Is there any way to achieve this with xmake? Do I need to set cflags manually?
I tried to `grep` in the `xmake` code base to find clues myself but I could not figure out where the `add_files` function was defined/implemented.

**Comment by waruqi** [comment]
`.c` is c language file. Why did you add `--std=c++11`? It only for c++ files, so xmake will ignore it.

You can set_languages("c11") for c language file. 

If you want to compile as c ++ code, you can rename the file to `.cpp`, then set_languages("c++11")

You can call `add_cflags("--std=c++11", {force = true})` to force to add it to c language file, but it is invalid.

**Comment by OpportunityLiu** [comment]
`{rule='c++.build'}`?

**Comment by kraigher** [comment]
Thank you. I will try your suggestions tomorrow and report back. It is an existing project so avoiding renaming the file is beneficial to ease the migration.

**Comment by waruqi** [comment]
> `add_files("*.c", {rule='c++.build'})`?

Overwriting rules is not supported yet, it will append rules -> c.build, c++.build

At present, it is not supported to compile .c as .cpp, because the source file kind needs to be modified to cxx.

I will support it in the future. Currently I recommend renaming the source files to *.cpp directly

**Comment by kraigher** [comment]
I think having a mechanism to override the file extension based source kind would help migration from projects where the file endings where not so strictly set.

**Comment by kraigher** [comment]
Could you guys explain what code gets executed when running `add_files`? I tried git-grepping but could not quite find what code is actually run. It would help me solve future issues if I can navigate the project and see what is happening under the hood.

**Comment by waruqi** [comment]
> Could you guys explain what code gets executed when running `add_files`? I tried git-grepping but could not quite find what code is actually run. It would help me solve future issues if I can navigate the project and see what is happening under the hood.

I have supported it on dev branch. You can run `xmake update dev` to try it again.

```lua
add_files("*.c", {sourcekind = "cxx"})    -- force to compile as c++
add_files("*.cpp", {sourcekind = "cc"})  -- force to compile as c
```

patch: d989ec1a9903dde07d08bf58386a45dd53651f6c

**Comment by kraigher** [comment]
The ability to set sourcekind to override the file extension solves my issue. Thank you.

**Comment by waruqi** [comment]
ok
