### ISSUE TITLE
询问 xmake update master 问题

### ISSUE THREAD

**Issue by xflcx1991** [xmake-io/xmake#676]
有个奇怪的问题。xmake update master 这条命令接连执行三遍，每次都会更新，版本号也会增长
`xmake v2.2.9+202002011120`
`xmake v2.2.9+202002011123`
`xmake v2.2.9+202002011125`
这是怎么回事？不可能我刚巧执行的时候作者都在更新吧。

**Comment by waruqi** [comment]
最后的是 build version，每次更新安装 lua vm/core 部分代码是 c 写的的，都需要本机编译，所以这个是这块的编译版本，也就是当前的构建时间，精确到分钟

如果确定当前 master 上 core 没啥大改动 可以执行 xmake update -s master 仅仅更新 lua 脚本，这样 build version 不会变

**Comment by xflcx1991** [comment]
明白了，原来如此。













在 2020-02-02 14:23:12，"ruki" <notifications@github.com> 写道：

最后的是 build version，每次更新安装 lua vm/core 部分代码是 c 写的的，都需要本机编译，所以这个是这块的编译版本，也就是当前的构建时间，精确到分钟

如果确定当前 master 上 core 没啥大改动 可以执行 xmake update -s master 仅仅更新 lua 脚本，这样 build version 不会变
