### ISSUE TITLE
Incorrent version matching for programs

### ISSUE THREAD

**Issue by rivy** [xmake-io/xmake#677]
Versions are being matched and reported incorrectly.

``` shell
$ # wsl/ubuntu/linux
$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ xmake --version
xmake v2.2.9+202002012341, A cross-platform build utility based on Lua
Copyright (C) 2015-2020 Ruki Wang, tboox.org, xmake.io
Copyright (C) 2005-2015 Mike Pall, luajit.org
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, tboox.org

    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor

$ xmake lua lib.detect.find_programver gcc
"7.4.0-1ubuntu1~18.04.1)"
```

``` shell
C:\> @REM :: windows
C:\> gcc --version
gcc (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

C:\> xmake v2.2.9+201912201654, A cross-platform build utility based on Lua
Copyright (C) 2015-2020 Ruki Wang, tboox.org, xmake.io
Copyright (C) 2005-2015 Mike Pall, luajit.org
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, tboox.org

    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor

C:\> xmake lua lib.detect.find_programver gcc
"686-posix-dwarf-rev0,"
```

Within the code, it looks like the regular expression `(%d+%.?%d*%.?%d*.-)%s` is used by default. This only requires a single leading digit followed by anything that's not a space. An equivalent regex would be `%d%S*`. I don't think that's a selective enough default requirement. I would think that requiring at least two digit sequences separated by a "." would be a better minimum default criteria.

I'm using the regex `%d+[.]%d+[-_.~%w]*` which translates to... at least two digit sequences separated by a ".", followed by any combination of alphanumeric and "-", "_", ".", "~" characters.

Using that the above versions translate as:

- "gcc (Ubuntu 7.4.0-1ubuntu1\~18.04.1) 7.4.0" => "7.4.0-1ubuntu1\~18.04.1"
- "gcc (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 8.1.0" => "8.1.0"

I think that's a better match.

**Comment by waruqi** [comment]
> "gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0" => "7.4.0-1ubuntu1~18.04.1"

We can only match `7.4.0-1ubuntu1` as a valid semantic version for `core.base.semver` module.

I have improve it, you can see https://github.com/xmake-io/xmake/commit/c1262215a240eefc46a97b88ec3086e0c55947e3

Although the current default matching rules are not perfect, they have basically met the requirements.

You can also continue to improve the following code.

https://github.com/xmake-io/xmake/blob/c1262215a240eefc46a97b88ec3086e0c55947e3/xmake/core/base/semver.lua#L164-L177

https://github.com/xmake-io/xmake/blob/c1262215a240eefc46a97b88ec3086e0c55947e3/tests/modules/semver/test.lua#L85-L91

**Comment by rivy** [comment]
Thanks for the quick response!
I'm quite happy with your modifications.
I hadn't reviewed the semver requirements, but, after reviewing them now, I think you've captured them correctly.

With your changes, I consider the problem solved.

Thanks again.
👍
