### ISSUE TITLE
很久以前的那條 android ndk r20c 修正，導致更早版本r18b r15c 出錯。

### ISSUE THREAD

**Issue by orzuk-lmj** [xmake-io/xmake#684]
### 描述问题

使用dev最新版的時候，最主要體現出來的錯誤狀況是：**原本從option來link的庫都無法被正確啟用**
``` lua
-- 一般來說我大致上是這樣link倚賴庫，原本是正確的
option("dependencies")
    set_showmenu(true)
    before_check(function (option)
        import("lib.detect.find_package")
        option:add(find_package("libwebm"))
        option:add(find_package("libyuv"))
    end)
option_end()
```

- 發生錯誤的時候，甚至連`.dep資料夾`中的`TargetName資料夾`都沒有建立出來。
- 畫面上報出來的錯誤訊息大致上都是 `undefined reference to` 或 `xxx/yyy.h file not found`這之類的。

我交叉測試了好多個版本，最終發現到去年的 b18c9aa8873edef1d6fc4c56a236a713282e1a6b 這條修正中，改變了clang++ /clang / g++ / gcc的順序。這部分我在現在dev最新版上跟著改回早期的順序後，就可以正常編譯了。

### 期待的结果

- 想了解一下改動順序的目的， r20版的link錯誤真要靠這順序嗎?
- 有沒有相容於老版本解法?

### 相关环境
- android-ndk-r15c
- android-ndk-r18b
- xmake dev 最新

**Comment by waruqi** [comment]
> 想了解一下改動順序的目的， r20版的link錯誤真要靠這順序嗎?

具体什么错误我忘记了，反正之前是r20以上版本link errors后，我才调整的，现在也不知道怎么复现了

你这里的错误，应该是check option (dependencies) 阶段失败了，导致这个option没生效

我这里还有点疑问，需要先了解下：

1. android 版本 系统上 find_package应该没这些库才对，你这边有自定义的find_package去找android版本libwebm？ 默认不太可能找到

2. 你这是什么平台？window ndk? 还是linux ?

你可以失败前，和成功后两个阶段，都执行下下面命令，给我看下详细完整的诊断输出：

```console
xmake f -p android --ndk=xxx -c -v -D
xmake -v 
```

我看下check option阶段是哪里出错了。

理论上gcc/clang的顺序应该跟check option没啥必然关系才对，唯一相关的是 check option会去尝试link 对应的links，用的gcc/clang linker有区别。

**Comment by orzuk-lmj** [comment]
1. 那些庫都是我自己編譯後，封裝好模組讓xmake自主去查詢的
2. 使用windows ndk環境
詳細診斷輸出，請稍等，我整理準備一下給你。
很怪的就是，所有CODE都沒變化，只改動gcc/clang順序，就讓編譯結果變化了。而且我確認測試，分別都是乾淨的環境重新下指令跑完全程。

**Comment by orzuk-lmj** [comment]
首先 libwebm和libyuv 也是用 xmake 幫助下編譯的。
然後 find_libwebm.lua 大致內容是底下這樣：
``` lua
-- imports
import("core.base.option")
import("core.project.config")
import("core.project.project")
import("lib.detect.find_path")
import("lib.detect.find_library")

function main(opt)
    -- 
    -- 前面放一些尋找到檔案的過程，然後我都轉為絕對路徑
    -- 

    local result =
    {
        links = {
            pkg_basename
        },
        linkdirs = {
            pkg_linkdirs
        },
        includedirs = {
            pkg_source_include
        },
        version = pkg_version,
        defines = pkg_defines,
        install_files = install_files
    }
    return result
end
```

**Comment by orzuk-lmj** [comment]
接下來我放上成功和錯誤的兩個完整LOG，請看：

[VPX_OK.txt](https://github.com/xmake-io/xmake/files/4185925/VPX_OK.txt)
[VPX_ERR.txt](https://github.com/xmake-io/xmake/files/4185926/VPX_ERR.txt)

**Comment by waruqi** [comment]
find这块应该没啥问题，应该还是后面check option的问题，这个我得看了-v -D logs后才能知道具体啥问题

```lua
        import("lib.detect.find_package")
        option:add(find_package("libwebm"))
        option:add(find_package("libyuv"))
 ```

另外这块可以改进为：

```lua
option:add(find_packages("libwebm", "libyuv"))
```

find_packages/find_package我都导出作为builtin了，不用import

还有，后期也可以考虑吧libwebp/libyuv的构建描述提交到xmake-repo，例如：https://github.com/xmake-io/xmake-repo/blob/master/packages/z/zlib/xmake.lua

直接使用xmake内置的包依赖下载和编译，原生支持android ndk，只需要

```lua
add_requires("libwebp", "libyuv")
target("xxx")
    add_packages("libwebp", "libyuv")
```

即使没有提交到xmake-repo，add_requires也会内部自动走find_packages，跟上面的option/find_packages效果一样，也是后期推荐包依赖引用方式。

**Comment by waruqi** [comment]
```
> checking for the c links(webm, yuv)
checkinfo: ...gramdir\core\sandbox\modules\import\core\tool\linker.lua:91: @programdir\core\sandbox\modules\os.lua:311: D:\\Workspace\\vpx_project\\Externals\\SDKs\\android-21-arm64\\libyuv\\debug\\bin/libyuv.so: undefined reference to `log10'
clang.exe: error: linker command failed with exit code 1 (use -v to see invocation)

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:751]: in function 'raise'
    [@programdir\core\sandbox\modules\os.lua:311]: in function 'runv'
    [@programdir\modules\core\tools\gcc.lua:355]:
    [C]: in function 'link'
    [...gramdir\core\sandbox\modules\import\core\tool\linker.lua:89]: in function 'link'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:196]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:192]:
    [C]: in function 'load'
    [@programdir\core\project\option.lua:103]: in function '_on_check'
    [@programdir\core\project\option.lua:167]: in function '_check'
    [@programdir\core\project\option.lua:217]: in function 'check'
    [...dir\core\sandbox\modules\import\core\project\project.lua:89]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:132]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:130]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:330]:

checking for the dependencies ... no
```
就是这个导致 check option失败了，option里面的所有links都会调用g++/clang++去尝试link，确保可用

**Comment by orzuk-lmj** [comment]
>
> 还有，后期也可以考虑吧libwebp/libyuv的构建描述提交到xmake-repo，例如：https://github.com/xmake-io/xmake-repo/blob/master/packages/z/zlib/xmake.lua
> 

好的，很樂意為xmake社群貢獻一份心力!
我想辦法試試，但因為我這裡維護的時候有穩定版號的需要，或是得打patch上去，所以都是另外存一份原代碼導致和官方直接抓得不一樣，這時候要怎麼提交建構描述到xmake-repo成了另外問題。

**Comment by waruqi** [comment]
> \bin/libyuv.so: undefined reference to `log10'

看着像是，clang.exe作为linker默认能找到log10 ，而clang++.exe 可以，所以检测links失败了

**Comment by waruqi** [comment]
> 我想辦法試試，但因為我這裡維護的時候有穩定版號的需要，或是得打patch上去，所以都是另外存一份原代碼導致和官方直接抓得不一樣，這時候要怎麼提交建構描述到xmake-repo成了另外問題。

打patch，可以通过add_patches()，比如：

```lua
    if is_plat("macosx") then
        add_patches("1.15", "https://raw.githubusercontent.com/Homebrew/patches/9be2793af/libiconv/patch-utf8mac.diff",
                            "e8128732f22f63b5c656659786d2cf76f1450008f36bcf541285268c66cabeab")
    end
```

如果确实差异大，也不必非得提交到xmake-repo，你可以在公司内部自建个私有的xmake-repo，引用和构建你定制版的libwebp/libyuv，然后通过 `xmake repo --add`或者`add_repositories()` 添加你的私有仓库。

add_requires是可以支持多个仓库，去中心化的，公司的packages可以独立到自己的私有仓库中，回去优先查找，只有找不到，才会退化到官方的xmake-repo中去找包描述

**Comment by waruqi** [comment]
> > \bin/libyuv.so: undefined reference to `log10'
> 
> 看着像是，clang.exe作为linker默认找不到log10 ，而clang++.exe 可以，所以检测links失败了

关于这个问题，我得想想怎么搞，我先尝试复现下之前调整linker顺序前遇到的link errors，再想想怎么兼容下

**Comment by orzuk-lmj** [comment]
> 
> 
> > > \bin/libyuv.so: undefined reference to `log10'
> > 
> > 
> > 看着像是，clang.exe作为linker默认找不到log10 ，而clang++.exe 可以，所以检测links失败了
> 

有個疑惑就是，我使用 option("dependencies") 的那個 target 是使用 clang++編譯啊，怎麼會跑去用clang檢查呢?

**Comment by waruqi** [comment]
> > > > \bin/libyuv.so: undefined reference to `log10'
> > > 
> > > 
> > > 看着像是，clang.exe作为linker默认找不到log10 ，而clang++.exe 可以，所以检测links失败了
> 
> 有個疑惑就是，我使用 option("dependencies") 的那個 target 是使用 clang++編譯啊，怎麼會跑去用clang檢查呢?

这块我cxx设置了 clang++ （按理应该设置clang就行了，具体为啥设置了这个 我也忘了），check links 走的是linker，目前优先的clang 这块确实也有些问题，我先调下吧，回头改进完，你再试试

**Comment by waruqi** [comment]
> 想了解一下改動順序的目的， r20版的link錯誤真要靠這順序嗎?

这块我复现了出来了，当初是切到clang++出现这个linker error，我才调整到clang作为linker来修复的。r20上

```console
ld: error: cannot find -lc++
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

而我设置的links只有-lc++_static -lc++abi -lunwind -latomic，但clang++还会自动去找-lc++，导致找不到就报错

**Comment by orzuk-lmj** [comment]
這有一串r20相關的討論，他們添加 `-nostdlib` 來解決
https://forum.qt.io/topic/103713/error-cannot-find-lc-qt-5-12-android/8

**Comment by waruqi** [comment]
> 這有一串r20相關的討論，他們添加 `-nostdlib` 來解決
> https://forum.qt.io/topic/103713/error-cannot-find-lc-qt-5-12-android/8

试了下，应该是`-nostdlib++`，用这个可以，我一会改下

**Comment by waruqi** [comment]
我修复了，你再试试：https://github.com/xmake-io/xmake/commit/7b08be3acbeeb49f691302ee9262a053171c70d5

**Comment by orzuk-lmj** [comment]
OK，目前編譯一切正常了。

- 但我比較在意的潛在問題是，option("dependencies")也許會給一個或多個target使用，這兩種狀況下會不會出現 dep(使用clang檢查) 但卻給 target(需要clang++編譯) 的這類交叉狀況。這有辦法解決嗎?
- 關於xmake-repo相關的，我另外開issues詢問。

**Comment by waruqi** [comment]
> 但我比較在意的潛在問題是：也許option("dependencies")會給一個或多個target使用，這兩種狀況下會不會出現 dep(使用clang檢查) 但卻給 target(需要clang++編譯) 的這類交叉狀況。這有辦法解決嗎?

两端是一致的，target是用clang++编译c++代码, clang编译的c代码，链接用的clang++

你这里之前的log看，c代码编译也是用的clang。。

而check阶段你看到用的clang，是因为之前为了修复-lc++ linker error，给调整过了。现在改回来了，那么 option check 用的还是clang++ 

因为你的option 只有links，所以只调用了linker /clang++来检测，并没有调用clang去检测c代码（func/include这种）

option的检测过程，由于你的option只设置了links，没设置includes/funcs/types这种需要compile步骤的检测，因此你只看到了linker/clang++而已。实际调用的compiler/linker跟target的编译链接是同步的。。这个不用担心。
```lua
            compiler.compile(sourcefile, objectfile, opt)
            if #links > 0 then
                linker.link("binary", {"cc", "cxx"}, objectfile, binaryfile, opt)
            end
```

**Comment by orzuk-lmj** [comment]
問題已解決!  這裡先關掉，我研究整理一下後另開issues詢問xmake-repo相關。
