### ISSUE TITLE
中文文档中可能有一处错字

### ISSUE THREAD

**Issue by SmartPolarBear** [xmake-io/xmake#685]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题

在文档 https://xmake.io/#/zh-cn/manual/project_target?id=targetadd_files中

>此接口使用方式跟add_installfiles接口几乎完全一样，都可以用来**天剑**安装文件，不过此接口仅用于安装头文件。 因此，使用上比add_installfiles简化了不少，默认不设置prefixdir，也会自动将头文件安装到对应的include子目录中。

### 期待的结果

可能应当为

>此接口使用方式跟add_installfiles接口几乎完全一样，都可以用来**添加**安装文件，不过此接口仅用于安装头文件。 因此，使用上比add_installfiles简化了不少，默认不设置prefixdir，也会自动将头文件安装到对应的include子目录中。

**Comment by waruqi** [comment]
这种你直接点右上角编辑帮忙改下呗 不用特地提issues

**Comment by waruqi** [comment]
我改掉了
