### ISSUE TITLE
How to disable some targets output during the installation?

### ISSUE THREAD

**Issue by tigerlee** [xmake-io/xmake#690]
> Note: If it is a 'bug report' or 'feature request', please select the corresponding issue template, otherwise this issue will be not replied. 

### Describe the problem details
I have a c++ project with multiple binary and static targets. binary targets depends on static targets. When I use `xmake install`, it's always output static targets under the install dir. I find nothing after read the whole documents. Can you help me to fix this issue? Thanks a lot.

**Comment by waruqi** [comment]
please run `xmake install --help` to see it's usages.

you can ony install the given target.

```
xmake install targetname
```

**Comment by tigerlee** [comment]
`on_install()` works. Thanks again.
