### ISSUE TITLE
请问如何编译依赖的第三方库？

### ISSUE THREAD

**Issue by isshe** [xmake-io/xmake#691]
> 注：如果是`问题报障`或者`特性请求`，请选择对应issues模板，否则一律不回复。

### 描述问题详情
目录结构：
* /
   * xmake.lua
    * src/
    * lib/
        * xmake.lua
        * libevent/
        * openssl/

项目根目录xmake.lua
```
set_project("test")

-- add modes: debug and release
add_rules("mode.debug", "mode.release")

includes("lib")
-- add target
target("test")

    -- set kind
    set_kind("binary")

    add_deps("libisshe", "libevent")
```

lib/xmake.lua:
```lua
target("libevent/openssl")
    -- 请问这里如何写？
    -- 这里进行的操作应该是：cd libevent; ./configure; make
```

**Comment by waruqi** [comment]
方式1：
    自行通过add_files, add_cxflags等写每个库的xmake.lua构建逻辑，移植编译，在通过add_deps添加引用

方式2：
    走远程库依赖，集成xmake-repo仓库中现有的包， 看文档：https://xmake.io/#/zh-cn/package/remote_package

方式3：
     如果有些库，xmake-repo官方仓库还没有的库，自行添加包构建描述，可以提交到xmake-repo仓库，也可以自建私有仓库，或者直接写在当前项目的xmake.lua中，见文档：
https://xmake.io/#/zh-cn/package/remote_package?id=%e6%b7%bb%e5%8a%a0%e5%8c%85%e5%88%b0%e4%bb%93%e5%ba%93
    项目example:
    https://github.com/tboox/benchbox

方式4：
    如果有些库xmake-repo仓库没有，也不想自己手动编辑加包描述，那么走conan/vcpkg等第三方包仓库，见文档：https://xmake.io/#/zh-cn/package/remote_package?id=%e7%ac%ac%e4%b8%89%e6%96%b9%e4%be%9d%e8%b5%96%e5%8c%85%e5%ae%89%e8%a3%85

方式5：
    直接将库安装到系统，通过add_requires("xxx", {system=true})或者find_packages直接从系统中检测和引用集成，见文档：https://xmake.io/#/zh-cn/package/system_package

**Comment by isshe** [comment]
好，感谢。
