### ISSUE TITLE
XMake: MSYS/MinGW

### ISSUE THREAD

**Issue by kassane** [xmake-io/xmake#692]
I used the standard mode but also the error.
**Note:** This only occurs on the msys2 terminal.

`error: ccache: error: Failed to create temporary file for /home/kassane/.ccache/tmp/src\main.stdout: No such file or directory`

**Comment by waruqi** [comment]
you can run `xmake f --ccache=n` to disable ccache first. I will look at it later.

**Comment by kassane** [comment]
> you can run `xmake f --ccache=n` to disable ccache first. I will look at it later.

Worked!

**Comment by waruqi** [comment]
I currently do not plan to support ccache on msys, you can disable cache first.
