### ISSUE TITLE
使用"|"作为多参数分隔符，导致通过Python调用时，命令被截断。

### ISSUE THREAD

**Issue by Zliu404** [xmake-io/xmake#693]
### 描述问题

在Python中执行xmake编译命令，若设置多个目标架构（arch1|arch2），会导致命令行解析出错，原因是由于命令行在“|”处被截断。

### 期待的结果

是否有其他设置方法绕过，或者 target 是否有API可以设置arch？

### 错误信息
case1：在Python中执行xmake编译命令：
```python
os.system("xmake config --plat=macosx --arch=i386|x86_64 -c")
```
运行结果：
> sh: x86_64: command not found

case2：加上转义
```python
os.system("xmake config --plat=macosx --arch=i386\|x86_64 -c")
```
运行结果：
> checking for the Xcode directory ... /Applications/Xcode.app
checking for the SDK version of Xcode ... 10.15
[ 49%]: compiling.release ../Dev/ModuleA/Source/xxxx.cpp
[  0%]: compiling.release ../Dev/ModuleB/Source/xxxxxx.cpp
error: clang: error: invalid arch name '-arch i386|x86_64'

### 相关环境
运行环境 mac，Python2.7

**Comment by waruqi** [comment]
> os.system("xmake config --plat=macosx --arch=i386|x86_64 -c")

我可没说过一次配置能支持多arch，文档里面这么写，意思是 or ，我只是做个简单的列举，能让用户一眼看到某个平台能支持哪些arch而已。。

不要照搬着写哈。。

一次配置切换只能支持一个arch，因为一次build只能构建一个arch。。

**Comment by Zliu404** [comment]
> > os.system("xmake config --plat=macosx --arch=i386|x86_64 -c")
> 
> 我可没说过一次配置能支持多arch，文档里面这么写，意思是 or ，我只是做个简单的列举，能让用户一眼看到某个平台能支持哪些arch而已。。
> 
> 不要照搬着写哈。。
> 
> 一次配置切换只能支持一个arch，因为一次build只能构建一个arch。。

好的，误解了。
那再请教下，通过并行执行编译命令，不同的平台（Android、iOS）是否可以同时编译？

**Comment by waruqi** [comment]
我加了project lock 应该不可以
