### ISSUE TITLE
package()定义的第三方包  make run 或者make build 将本地库lib 加到环境变量 可以直接make run ？

### ISSUE THREAD

**Issue by linuxsky** [xmake-io/xmake#696]
> 注：如果是`问题报障`或者`特性请求`，请选择对应issues模板，否则一律不回复。

### 描述问题详情
package()定义的第三方包 在编辑链接完成后 ，在xmake run 时候提示找不到库，请问这个设置运行库 应该在哪里比较合适？
比如

-- add modes: debug and release
add_rules("mode.debug", "mode.release")
add_repositories("local third_packages")
add_requires("zmq")
add_requires("protobuf")
add_requires("opencv 3.4.5")
-- add target
set_targetdir("build")
target("sample")
    add_packages("zmq")
    add_packages("protobuf")
    add_packages("opencv")
    add_includedirs("include","proto")
    add_syslinks("pthread")
    -- set kind

    before_run(function (target)
	os.run("xmake require --export --exportdir=$(buildir)/libs opencv")
	os.run("xmake require --export --exportdir=$(buildir)/libs zmq")
	os.run("xmake require --export --exportdir=$(buildir)/libs protobuf")
    end)

    on_run(function (target)
	local env_path=vformat(".")
        for _, dir in ipairs(os.dirs("$(buildir)/libs/*")) do
	   local path_dir = path.join("$(projectdir)",dir,"lib")
	   env_path = vformat("%s:%s",env_path,path_dir)
        end
        os.setenv("LD_LIBRARY_PATH", env_path)
        os.exec("$(buildir)/sample $(1)")
    end)
    set_kind("binary")
    -- add files
    add_files("src/*.cpp")
    add_files("proto/*.cc")

**Comment by linuxsky** [comment]
同时 想问下  make  run  如何传递 参数 到应用程序

**Comment by waruqi** [comment]
你整个好复杂，其实你add_packages的时候，就已经绑定这个pkg的所有环境了 只不过你的package定义设置里面，没设置上LD_LIBRARY_PATH而已，可以在里面package:addenv设置上对应目录就行了，可以参考下 https://github.com/xmake-io/xmake-repo/blob/13a4fc06771b8cb23a768061d43fedd805f5a503/packages/l/lua/xmake.lua#L19

```
before_run(function (target)
os.run("xmake require --export --exportdir=$(buildir)/libs opencv")
os.run("xmake require --export --exportdir=$(buildir)/libs zmq")
os.run("xmake require --export --exportdir=$(buildir)/libs protobuf")
end)

on_run(function (target)
local env_path=vformat(".")
    for _, dir in ipairs(os.dirs("$(buildir)/libs/*")) do
   local path_dir = path.join("$(projectdir)",dir,"lib")
   env_path = vformat("%s:%s",env_path,path_dir)
    end
    os.setenv("LD_LIBRARY_PATH", env_path)
```
这里一大块完全可以去掉，另外即使想在这里取pkg的路径信息，可以直接通过target:pkg("xxx"):get("linkdirs")来获取

> 同时 想问下 make run 如何传递 参数 到应用程序

通过 import core.base.option

然后option.get("arguments")就能取到所有

**Comment by linuxsky** [comment]
> 你整的好复杂，其实你add_packages的时候，就已经绑定这个pkg的所有环境了 只不过你的package定义设置里面，没设置上LD_LIBRARY_PATH而已，可以在里面package:addenv设置上对应目录就行了，可以参考下 https://github.com/xmake-io/xmake-repo/blob/13a4fc06771b8cb23a768061d43fedd805f5a503/packages/l/lua/xmake.lua#L19
> 
> ```
> before_run(function (target)
> os.run("xmake require --export --exportdir=$(buildir)/libs opencv")
> os.run("xmake require --export --exportdir=$(buildir)/libs zmq")
> os.run("xmake require --export --exportdir=$(buildir)/libs protobuf")
> end)
> 
> on_run(function (target)
> local env_path=vformat(".")
>     for _, dir in ipairs(os.dirs("$(buildir)/libs/*")) do
>    local path_dir = path.join("$(projectdir)",dir,"lib")
>    env_path = vformat("%s:%s",env_path,path_dir)
>     end
>     os.setenv("LD_LIBRARY_PATH", env_path)
> ```
> 
> 这里一大块完全可以去掉，另外即使想在这里取pkg的路径信息，可以直接通过target:pkg("xxx"):get("linkdirs")来获取
> 
> > 同时 想问下 make run 如何传递 参数 到应用程序
> 
> 通过 import core.base.option
> 
> 然后option.get("arguments")就能取到所有
我看了下 option 没太理解就是我要自己实现on_run ? 比如编译出来的 test.bin  运行需要执行 ./test.bin aaaa bbbb 两个参数,这个有参考的例子么？

**Comment by waruqi** [comment]
> 我看了下 option 没太理解就是我要自己实现on_run ? 比如编译出来的 test.bin 运行需要执行 ./test.bin aaaa bbbb 两个参数,这个有参考的例子么？

不需要啊，直接执行 `xmake run target aaaa bbbb` 不就好了

**Comment by linuxsky** [comment]
感谢，搞定了

**Comment by waruqi** [comment]
I added pkg:get("libpathes") to get all library files path. You can simply traverse this list to install the library files you need

see
#961 (comment)
