### ISSUE TITLE
如果制定自定义package 优先于 pkg-config 呢？

### ISSUE THREAD

**Issue by linuxsky** [xmake-io/xmake#697]
ok
libprotoc 3.3.0
checking for the autoconf ... no
checking for the automake ... no
checking for the libtool ... no
checking for the pkg-config ... no
checking for the xmake::zmq ... no
checking for the xmake::protobuf ... no
checking for the cmake ... no
checking for the xmake::opencv ... no
checking for the brew ... no
checking for the vcpkg directory ... no
checking for the brew ... no
checking for the autoconf ... /usr/bin/autoconf
checking for the libtool ... /home/shiyang/anaconda3/bin/libtool
checking for the pkg-config ... /usr/bin/pkg-config
checking for the automake ... /usr/bin/automake
checking for the cmake ... /usr/bin/cmake
checking for the pkg-config ... /usr/bin/pkg-config
checking for the pkg-config ... /usr/bin/pkg-config
checking for the pkg-config ... /usr/bin/pkg-config
checking for the opencv ... no
**_### **checking for the protobuf ... 2.6.1**_**
checking for the zmq ... no
note: try installing these packages (pass -y to skip confirm)?
in local:
  -> zmq master 
  -> opencv 3.4.5 
please input: y (y/n)

比如这个，我自定义本地库  zmq  opencv 和 protobuf ，但是protobuf 优先匹配了本地包，我想问下能否优先 自定义库 再xmake 库  再 自己电脑环境呢？

**Comment by waruqi** [comment]
add_requires("xxx", {system = false})

禁用从系统探测，强制走包仓库下载

**Comment by linuxsky** [comment]
我参考这个例子
```
add_requires("protobuf-cpp")

target("console_c++")
     set_kind("binary")
     set_languages("c++11")

     add_packages("protobuf-cpp")

     add_files("src/*.cpp")
     add_files("src/*.proto", {rules = "protobuf-cpp"})
```

实现了我写的：
```
-- add modes: debug and release
add_rules("mode.debug", "mode.release")
add_repositories("local third_packages")
add_requires("zmq",{system = false})
--add_requires("protobuf-2.6 2.6.1", {system = false})
add_requires("protobuf-cpp")
add_requires("opencv 3.4.5", {system = false})
-- add target
set_targetdir("build")
target("sample")
    set_languages("c++11")
    add_packages("zmq")
    add_packages("protobuf-cpp")
    add_packages("opencv")
    add_includedirs("include","proto")
    add_syslinks("pthread")
    -- set kind
    set_kind("binary")
    -- add files
    add_files("src/*.cpp")
    add_files("src/proto/*.proto", {rules = "protobuf-cpp"})
```
然后输出还是不认识
$ xmake -v     
checking for the architecture ... x86_64
checking for the unzip ... /usr/bin/unzip
checking for the git ... /usr/bin/git
checking for the gzip ... /bin/gzip
checking for the tar ... /bin/tar
checking for the ping ... /bin/ping
pinging for the host(gitee.com) ... 27 ms
checking for the nmap ... no
pinging for the host(github.com) ... 65535 ms
pinging for the host(gitlab.com) ... 65535 ms
checking for the autoconf ... no
checking for the automake ... no
checking for the libtool ... no
checking for the pkg-config ... no
checking for the xmake::zmq ... master
checking for the xmake::protobuf-cpp ... 3.8.0
checking for the cmake ... no
checking for the xmake::opencv ... 3.4.5
checking for the pkg-config ... /usr/bin/pkg-config
checking for the autoconf ... /usr/bin/autoconf
checking for the libtool ... /home/shiyang/anaconda3/bin/libtool
checking for the cmake ... /usr/bin/cmake
checking for the automake ... /usr/bin/automake
configure
{
    host = linux
    arch = x86_64
    ccache = true
    kind = static
    buildir = build
    plat = linux
    mode = release
    ndk_stdcxx = true
}
error: unknown source file: src/proto/meta.proto

我想问下像这种需要先将某些文件处理成为C或者cpp 需要 怎么实现，如果before build 这种 不能用add files。

**Comment by waruqi** [comment]
> error: unknown source file: src/proto/meta.proto

英文文档里面的这处rule名，我写的不对，你改成：protobuf.cpp

```lua
    add_files("src/proto/*.proto", {rules = "protobuf.cpp"})
```

**Comment by linuxsky** [comment]
> protobuf.cpp

赞已经搞定
