### ISSUE TITLE
add_requires(doctest) 无法安装

### ISSUE THREAD

**Issue by wfh1300** [xmake-io/xmake#698]
=> download https://github.com/onqtam/doctest/archive/2.3.6.tar.gz .. failed
  => downloading doctest .. (1/git) 
总是停留在这个界面

我已经自己手动把2.3.6.tar.gz 放置在cashdir文件夹里面。通过这样的做法，fmt包可以安装成功，但是doctest还是会失败
系统 windows10

**Comment by waruqi** [comment]
失败请提供失败信息，不然我也不知道啥问题。 加-v -D 看下失败信息

**Comment by wfh1300** [comment]
checking for the Microsoft Visual Studio (x64) version ... 2019
checking for the unzip ... ok
checking for the git ... ok
checking for the gzip ... ok
checking for the tar ... ok
checking for the ping ... ok
pinging for the host(gitee.com) ... 63 ms
pinging for the host(gitlab.com) ... 335 ms
checking for the nmap ... no
pinging for the host(github.com) ... 65535 ms
finding doctest from xmake ..
checking for the xmake::doctest ... no
finding doctest from vcpkg ..
checking for the vcpkg directory ... no
finding doctest from conan ..
finding doctest from pkg_config ..
checking for the pkg-config ... no
finding doctest from system ..
checking for the doctest ... no

**Comment by waruqi** [comment]
你给完整哈，给一半 我哪知道是啥 = =

```console
xmake f -c -vD
xmake -vD
```

怎么可以只有这些信息
