### ISSUE TITLE
linkdir

### ISSUE THREAD

**Issue by Clinkz24** [xmake-io/xmake#699]
### 描述问题
使用远程包仓库安装boost后，linkdir并没有自动加上，需要手动在项目lua文件中添加add_linkdirs。

### 期待的结果
自动添加linkdir。

### 错误信息
F:\workspace\hello>xmake -v -D --rebuild
checking for the Microsoft Visual Studio (x64) version ... 2015
checking for the unzip ... ok
checking for the git ... ok
checking for the gzip ... no
checking for the 7z ... ok
checking for the ping ... ok
pinging for the host(gitee.com) ... 24 ms
pinging for the host(gitlab.com) ... 242 ms
checking for the nmap ... no
pinging for the host(github.com) ... 65535 ms
finding nlohmann_json from xmake ..
checking for the xmake::nlohmann_json ... v3.7.0
finding boost from xmake ..
checking for the xmake::boost ... 1.70.0
configure
{
    arch = x64
    ld = link.exe
    ccache = true
    mode = release
    ndk_stdcxx = true
    host = windows
    plat = windows
    kind = static
    buildir = build
    vs = 2015
    cxx = cl.exe
}
checking for the cl.exe ... ok
checking for the flags (-Ox -fp:fast) ... ok
> cl.exe "-Ox" "-fp:fast"
checking for the ccache ... no
[  0%]: compiling.release src\main.cpp
cl.exe -c -Ox -fp:fast -IC:\\\\Users\\\\Administrator\\\\AppData\\\\Roaming\\\\.
xmake\\\\packages\\\\n\\\\nlohmann_json\\\\v3.7.0\\\\aa7fbd80abda4d1a97f445168f6
f3c1d\\\\include -IC:\\\\Users\\\\Administrator\\\\AppData\\\\Roaming\\\\.xmake\
\\\packages\\\\b\\\\boost\\\\1.70.0\\\\2545cb1dcbc249309dc8d740a7ac9cee\\\\inclu
de /EHsc -nologo -Fobuild\\.objs\\.\\hello\\windows\\x64\\release\\src\\main.cpp
.obj src\\main.cpp
[100%]: linking.release hello.exe
link.exe -nologo -dynamicbase -nxcompat -machine:x64 -out:build\\windows\\x64\\r
elease\\.\\hello.exe build\\.objs\\.\\hello\\windows\\x64\\release\\src\\main.cp
p.obj
error: @programdir\core\main.lua:261: [@encode(error)]: {stdout="LINK : fatal er
ror LNK1104: cannot open file 'libboost_thread-vc140-mt-s-x64-1_70.lib'\
",errors="LINK : fatal error LNK1104: cannot open file 'libboost_thread-vc140-mt
-s-x64-1_70.lib'\
",stderr=""}
stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:818: in function 'raise'
        @programdir\core\main.lua:261: in function 'cotask'
        @programdir\core\base\scheduler.lua:306: in function <@programdir\core\b
ase\scheduler.lua:304>

github上传不了图片 只能复制黏贴啦，不好意思

### 相关环境
win7 X64 VS2015 xmake 2.3.1

### 其他信息
在项目lua文件中手动add_linkdirs后编译通过。

查看依赖库好像有问题？boost没有表面linkdir在哪个目录
F:\workspace\hello>xmake require --list
The package dependencies of project:
    require(nlohmann_json): v3.7.0
      -> version: v3.7.0
      -> includedirs: C:\Users\Administrator\AppData\Roaming\.xmake\packages\n\n
lohmann_json\v3.7.0\aa7fbd80abda4d1a97f445168f6f3c1d\include
    require(boost): 1.70.0
      -> version: 1.70.0
      -> includedirs: C:\Users\Administrator\AppData\Roaming\.xmake\packages\b\b
oost\1.70.0\2545cb1dcbc249309dc8d740a7ac9cee\include

**Comment by waruqi** [comment]
我回头看下

**Comment by waruqi** [comment]
我本地暂时没环境，我看ci上 vs2015 x64上有linkdir的么，https://ci.appveyor.com/project/waruqi/xmake-repo/build/job/euborl09e7gg14o9

你可以执行下下面的命令，看下装完boost有没有linkdirs

```console
git clone https://github.com/xmake-io/xmake-repo.git
cd xmake-repo
xmake l scripts/test.lua -v -D --shallow boost
```

另外你这的xmake.lu配置也给我看下

**Comment by Clinkz24** [comment]
xmake官方仓库的boost安装会有问题 我自己搭建了一个仓库 放在我本地 修改了boost的lua文件。不知道是哪个操作取消了设置linkdirs。我github速度超慢、所以您先看下是不是我哪里用错了。十分感谢。另外我可以在包的安装脚本里指定linkdirs吗 package的文档xmake.io上好像没有。。

这是我的项目的xmake.lua
-- add modes: debug and release
add_rules("mode.debug", "mode.release")
--add_packagedirs("../nlohmann/json")
add_repositories("Iudge-XMake-Repo-Local F:\\workspace\\source\\xmake-repo")
add_requires("nlohmann_json", "boost")
-- add target
target("./hello")
    -- set kind
    set_kind("binary")
    -- add files
    add_files("src/*.cpp")

    add_packages("nlohmann_json", "boost")

    add_cxxflags("/EHsc", {force = true})


这是我修改后boost的安装lua

package("boost")
    set_homepage("https://www.boost.org/")
    set_description("Collection of portable C++ source libraries.")
    add_urls("http://192.168.10.15:8081/repository/cpp/boost/boost_$(version).tar.bz2", {version = function (version)
            return (version:gsub("%.", "_"))
        end})
    add_versions("1.70.0", "430ae8354789de4fd19ee52f3b1f739e1fba576f0aded0897c3c2bc00fb38778")
    add_versions("1.68.0", "7f6130bc3cf65f56a618888ce9d5ea704fa10b462be126ad053e80e553d6d8b7")

    if is_plat("linux") then
        add_deps("bzip2", "zlib")
    end



    local libnames = {"filesystem", 
                      "fiber", 
                      "coroutine", 
                      "context", 
                      "thread", 
                      "regex",
                      "system",
                      "container",
                      "exception",
                      "timer",
                      "atomic",
                      "graph",
                      "serialization",
                      "random",
                      "wave",
                      "date_time",
                      "locale",
                      "iostreams"}

    add_configs("multi",        { description = "Enable multi-thread support.",  default = true, type = "boolean"})
    for _, libname in ipairs(libnames) do
        add_configs(libname,    { description = "Enable " .. libname .. " library.", default = true, type = "boolean"})
    end

    on_load("windows", function (package)
        local vsversion = package:build_getenv("cxx")
        local PACKAGE_VER = package:version_str()
        local v1 = PACKAGE_VER:split('%.')
        local arch = package:arch()
        local vs_runtime = package:config("vs_runtime")
        for _, libname in ipairs(libnames) do
            local linkname = "libboost_" .. libname .. "-vc140"
            if package:config("multi") then
                linkname = linkname .. "-mt"
            end
            if vs_runtime == "MT" then
                linkname = linkname .. "-s"
            elseif vs_runtime == "MTd" then
                linkname = linkname .. "-sgd"
            elseif vs_runtime == "MDd" then
                linkname = linkname .. "-gd"
            end

            if arch == "x64" or arch == "x86_64" then
                linkname = linkname .. "-x64-"
            else
                linkname = linkname .. "-x32-"
            end
            linkname = linkname .. v1[1] .. "_" ..v1[2]
            package:add("links", linkname)
        end
    end)

    on_install("macosx", "linux", "windows", function (package)
        -- force boost to compile with the desired compiler
        local PACKAGE_VER = package:version_str()
        local file = io.open("user-config.jam", "a")
        if file then
            if is_plat("macosx") then
                file:print("using darwin : : %s ;", package:build_getenv("cxx"))
            elseif is_plat("windows") then
                file:print("using msvc : : %s ;", package:build_getenv("cxx"))
            else
                file:print("using gcc : : %s ;", package:build_getenv("cxx"))
            end
            file:close()
        end

        local bootstrap_argv = 
        {
            "--prefix=" .. package:installdir(), 
            "--libdir=" .. package:installdir("lib"),
            "--without-icu"
        }
        if is_host("windows") then
            os.vrunv("bootstrap.bat", bootstrap_argv)
        else
            os.vrunv("./bootstrap.sh", bootstrap_argv)
        end
        os.vrun("./b2 headers")

        local argv =
        {
            "--prefix=" .. package:installdir(), 
            "--libdir=" .. package:installdir("lib"), 
            "--toolset=msvc-14.0",
            "-d2",
            "-j4",
            "--hash",
            "--user-config=user-config.jam",
            "--no-cmake-config",
            "-sNO_LZMA=1",
            "-sNO_ZSTD=1",
            "install",
            "threading=" .. (package:config("multi") and "multi" or "single"),
            "debug-symbols=" .. (package:debug() and "on" or "off"),
            "link=static"
        }
        local arch = package:arch()
        if arch == "x64" or arch == "x86_64" then
            table.insert(argv, "address-model=64")
        else
            table.insert(argv, "address-model=32")
        end
        if package:plat() == "windows" then
            local vs_runtime = package:config("vs_runtime")
            if vs_runtime and vs_runtime:startswith("MT") then
                table.insert(argv, "runtime-link=static")
            else
                table.insert(argv, "runtime-link=shared")
            end
            table.insert(argv, "cxxflags=-std:c++14")
        else
            table.insert(argv, "cxxflags=-std=c++14")
        end
        for _, libname in ipairs(libnames) do
            if package:config(libname) then
                table.insert(argv, "--with-" .. libname)
            end
        end

        local INSTALL_LOG = io.open(package:installdir() .. "/install_log.txt", "w")
        INSTALL_LOG:write('\r\nB2 参数\r\n')
        INSTALL_LOG:write(PACKAGE_VER.." ver is a "..type(PACKAGE_VER).." v1 is a "..type(v1)..'\r\n')
        INSTALL_LOG:save(argv)
        INSTALL_LOG:close()

        os.vrunv("./b2", argv)

        if not os.isdir(package:installdir().. "include/boost") then
            local v1 = PACKAGE_VER:split('%.')
            local check_folder = "boost-" .. v1[1] .. "_" .. v1[2]
            if os.isdir(package:installdir().. "/include/" .. check_folder) then
                os.mv(package:installdir().. "/include/" .. check_folder .. "/boost", package:installdir().. "/include/boost")
                os.rm(package:installdir().. "/include/" .. check_folder)
            end
        end
    end)

    on_test(function (package)
        assert(package:check_cxxsnippets({test = [[
            #include <string>
            #include <vector>
            #include <assert.h>
            using namespace std;
            static void test() {
                assert(true);
            }
        ]]}, {configs = {languages = "c++14"}}))
    end)

**Comment by waruqi** [comment]
直接add_linkdirs("lib")到package就会加上，不过默认库在lib下的话，是不需要的 会自动find到对应库然后加上，通常不需要额外添加的，除非库不在lib下，才需要额外配置其他linkdirs

另外路径拼接请用path.join
所以你这没有也比较怪，可以看下对应lib下有没有库

**Comment by Clinkz24** [comment]
在包的安装目录下的lib目录中，boost的几个静态库是有成功生成，我在hello这个项目的xmake.lua文件中调用add_linkdirs就可以成功链接了。
奇怪的是xmake官方仓库上boost的安装脚本在我机器上会有明显的错误，boost头文件因为xmake.lua生成的目录会在include下的boost-1_70下(pkginstalldir\include\boost-1_70\boost)，为什么你生成的就会没有问题？
希望在xmake.io上补一下内置模块package的文档，像我这种lua菜鸟还不太会调试xmake的源码，很依赖这种接口文档来使用xmake。

**Comment by waruqi** [comment]
这就不知道了 可能boost得那个安装在win上不同环境装的include路径也不同的，不过ci上我也就vs2017通过了 vs2015原本就没通过，后来我一直没时间细看 


include路径不同，可以通过add_includedirs("include/1_70")对package的win平台改下，或者也可以看看 b2配置安装的时候 除了指定libdir看看incdir能否也额外指定

**Comment by Clinkz24** [comment]
嗯 这个比较好解决 我是直接移动目录就好了。
我还有一个问题就不提issue了，就直接这里问您。
vcpkg这个包管理器可以将项目依赖的动态库(.dll)直接输出到生成目录，这个xmake支持吗？应该使用哪个API或有文档示例吗

**Comment by waruqi** [comment]
可以执行xmake require --export pkgname导出到build或者指定目录 我记得这些文档里都写了的 你可以找找 侧边栏 远程包管理 里面

**Comment by Clinkz24** [comment]
好的，多谢，我自己再研究下。
