### ISSUE TITLE
申请添加 zmq ，低版本protobuf ，和opencv 的支持

### ISSUE THREAD

**Issue by linuxsky** [xmake-io/xmake#700]
目前在很多项目上用到了zmq  和protobuf2（低版本） 还有做图像计算的opencv ，希望能在xmake 的库中添加对应的支持，相关版本 如下：
protobuf2（目前都是protobuf3 ，下载地址规则变了）：
add_urls("https://github.com/protocolbuffers/protobuf/releases/download/v$(version)/protobuf-$(version).zip", {alias = "github"})
 add_versions("github:2.6.1","146362958db8c07a3459e81edf3c3b73ec81b26e54293ec7340e510bbb930504")

opencv：
    add_urls("https://github.com/opencv/opencv/archive/$(version).tar.gz")
    add_versions("3.4.5","0c57d9dd6d30cbffe68a09b03f4bebe773ee44dc8ff5cd6eaeb7f4d5ef3b428e")

zmq：
add_urls("https://github.com/zeromq/libzmq.git")

**Comment by waruqi** [comment]
我回头有时间会给你加上，或者你可以自己提pr到xmake-repo上，更新下对应版本和url

**Comment by linuxsky** [comment]
> 我回头有时间会给你加上，或者你可以自己提pr到xmake-repo上，更新下对应版本和url

好的，那我抽空提交到 repo 上也行，目前上面放的opencv 3.4.9版本 默认编译会失败，需要改里面默认源码文件。

**Comment by waruqi** [comment]
zeromq我加上了。
