### ISSUE TITLE
package:addenv("LD_LIBRARY_PATH", "lib")  覆盖问题？

### ISSUE THREAD

**Issue by linuxsky** [xmake-io/xmake#701]
xmake.lua 内容：
-- add modes: debug and release
add_rules("mode.debug", "mode.release")
add_repositories("local third_packages")
--add_requires("zmq",{system = false})
add_requires("zmq")
add_requires("protobuf-cpp 2.6.1",{system = false})
--add_requires("opencv 3.4.5", {system = false})
add_requires("opencv 3.4.9")
-- add target
set_targetdir("build")
target("matrix-sample")
    set_languages("c++11")
    add_packages("zmq","opencv","protobuf-cpp")
    add_includedirs("include")
    add_syslinks("pthread")
    -- set kind
    set_kind("binary")
    -- add files
    add_files("src/*.cpp")
    add_files("src/proto/*.proto", {rules = "protobuf.cpp"})

其中 zmq  和opencv  都加了环境变量 如下：
    on_load(function (package)
        package:addenv("LD_LIBRARY_PATH", "lib")
    end)

但是好像会覆盖 如何 不覆盖而是累加 呢？add_packages("zmq","opencv","protobuf-cpp") 后面的会覆盖前面的。

**Comment by waruqi** [comment]
这个覆盖问题我测试没发现啥问题，并且dev我已经内置LD_LIBRARY_PATH了。
