### ISSUE TITLE
find_package 无法找到xmake 库 或者 自定义repo 下的包么？？

### ISSUE THREAD

**Issue by linuxsky** [xmake-io/xmake#702]
xmake run -v:

```
configure
{
    ld = /usr/bin/g++
    ccache = true
    mode = release
    ndk_stdcxx = true
    host = linux
    plat = linux
    cc = /usr/bin/gcc
    kind = static
    buildir = build
    arch = x86_64
    cxx = /usr/bin/gcc
}
checking for the brew ... no
checking for the vcpkg directory ... no
checking for the pkg-config ... /usr/bin/pkg-config
checking for the protobuf-cpp ... no
```

xmake.lua :
```
-- add modes: debug and release
add_rules("mode.debug", "mode.release")
add_repositories("local third_packages")
add_requires("zeromq",{system = false})
add_requires("opencv 3.4.9",{system = false})
add_requires("protobuf-cpp 2.6.1",{system = false})
-- add target
set_targetdir("build")
target("matrix-sample")
    set_languages("c++11")
    add_packages("protobuf-cpp")
    add_packages("zeromq")
    add_packages("opencv")
    add_includedirs("include")
    add_syslinks("pthread")

    before_run(function (target)
        import("lib.detect.find_package")
        local package = find_package("protobuf-cpp")
	print(package)
    end)
    -- set kind
    set_kind("binary")
    -- add files
    add_files("src/*.cpp")
    add_files("src/proto/*.proto", {rules = "protobuf.cpp"})
```
工程已经可以编译通过，再run 的时候找不到库，尝试通过在运行前 手动find 然后添加lib path
但是返回来的 都是空，但是如果将库改为 系统默认的比如jpeg 时
`configure
{
    ld = /usr/bin/g++
    ccache = true
    mode = release
    ndk_stdcxx = true
    host = linux
    plat = linux
    cxx = /usr/bin/gcc
    kind = static
    buildir = build
    arch = x86_64
    cc = /usr/bin/gcc
}
checking for the brew ... no
checking for the vcpkg directory ... no
checking for the pkg-config ... /usr/bin/pkg-config
checking for the jpeg ... ok
{
  links = {
    "jpeg"
  },
  linkdirs = {
    "/usr/lib/x86_64-linux-gnu"
  }
}

`

**Comment by waruqi** [comment]
找不到哪个库？xmake-repo一般默认都是编译生成的static，如果有些是动态的，请改下包描述，走static版本，run时候就不会有这问题了，另外为了支持其他平台和交叉编译，static版本支持力度更加好点

当然动态库也是要支持的，不过一般是要通过 add_requires("xx", {configs = {shared=true}})`引入，默认走static的， 虽然有些库里面我还没加上对这个的判断。。

尽量不要再before_run加，这种毕竟不是很nice的方式，虽然可以，我回头处理下env覆盖问题，直接在package里面加上ld_library_path就行了，或者我看看内置run里面处理下

另外find_package现在是内置了的，不用import也可以用

你也可以通过xmake l find_package xxx 直接测试检测

**Comment by linuxsky** [comment]
> 找不到哪个库？xmake-repo一般默认都是编译生成的static，如果有些是动态的，请改下包描述，走static版本，run时候就不会有这问题了，另外为了支持其他平台和交叉编译，static版本支持力度更加好点
> 
> 当然动态库也是要支持的，不过一般是要通过 add_requires("xx", {configs = {shared=true}})`引入，默认走static的， 虽然有些库里面我还没加上对这个的判断。。
> 
> 尽量不要再before_run加，这种毕竟不是很nice的方式，虽然可以，我回头处理下env覆盖问题，直接在package里面加上ld_library_path就行了，或者我看看内置run里面处理下
> 
> 另外find_package现在是内置了的，不用import也可以用
> 
> 你也可以通过xmake l find_package xxx 直接测试检测
```

auto1@auto1-ThinkCentre-M920x-N000:~/workspace/gitlab/matrix-sample-code$ xmake l find_package opencv
nil
auto1@auto1-ThinkCentre-M920x-N000:~/workspace/gitlab/matrix-sample-code$ xmake l find_package opencv
nil
auto1@auto1-ThinkCentre-M920x-N000:~/workspace/gitlab/matrix-sample-code$ xmake l find_package zmq
nil
auto1@auto1-ThinkCentre-M920x-N000:~/workspace/gitlab/matrix-sample-code$ xmake l find_package protobuf-cpp
nil
auto1@auto1-ThinkCentre-M920x-N000:~/workspace/gitlab/matrix-sample-code$ xmake l find_package jpeg
{
  links = {
    "jpeg"
  },
  linkdirs = {
    "/usr/lib/x86_64-linux-gnu"
  }
}
auto1@auto1-ThinkCentre-M920x-N000:~/workspace/gitlab/matrix-sample-code$ xmake l find_package libtool
nil
auto1@auto1-ThinkCentre-M920x-N000:~/workspace/gitlab/matrix-sample-code$ xmake l find_package cmake
nil
auto1@auto1-ThinkCentre-M920x-N000:~/workspace/gitlab/matrix-sample-code$
```

**Comment by linuxsky** [comment]
目前看是找不到呢，是因为我用了 system= false，但是应该也会从 xmake中查找，恩都是默认传入的。
行啊，其实我也是觉得 加入 到ld path 会比较干净  就是通过xmake  run 的都走的 xmake 包或者 系统包

**Comment by waruqi** [comment]
直接命令找 只能找系统的，ld那个我会看的，不过你要先跟我说下哪个库加载失败？

还有 默认我还是建议走static ， 如果哪个库目前走的so link和加载，建议尝试先改进pkg描述 切到static编译，xmake-repo里面大部分库都是走的static

**Comment by linuxsky** [comment]
> 默认我还是建议走static ， 如果哪个库目前走的so link和加载，建议尝试先改进pkg描述 切到static编译，xmake-repo里面大部分库都是走的

好的，我试试用默认的 static 编译下试试。
建议：如果选用了share so库 建议增加一个 LD路径。

**Comment by waruqi** [comment]
那你还是没跟我说 是哪个库加载so失败哈，我都问两回了。。

**Comment by linuxsky** [comment]
> 那你还是没跟我说 是哪个库加载so失败哈，我都问两回了。。

抱歉抱歉， 是 zeromq 和 opencv 3.4.9（默认编译会出错）

**Comment by waruqi** [comment]
zeromq 我默认改成 static了，可以通过 `add_requires("xx", {configs = {shared=true}})``启用动态库版本，protobuf 2低版本太老了，我就不支持了。。

**Comment by waruqi** [comment]
我写了个demo测了下，两个package同时加 LD_LIBRARY_PATH env，并且同时加add_packages，并不会覆盖之前的。

```
        print(os.getenv("LD_LIBRARY_PATH"))
```

before_run里面显示是两个同时存在的，并没有什么问题：

```console
$ xmake
$ xmake run
/Users/ruki/.xmake/packages/z/zeromq/4.3.2/a09afa96792545769f95949af25c5da0/lib:/Users/ruki/.xmake/packages/z/zlib/1.2.11/a09afa96792545769f95949af25c5da0/lib
```

```lua

-- add modes: debug and release
add_rules("mode.debug", "mode.release")

package("zeromq")

    set_homepage("https://zeromq.org/")
    set_description("High-performance, asynchronous messaging library")

    set_urls("https://github.com/zeromq/libzmq/releases/download/v$(version)/zeromq-$(version).tar.gz",
             "https://github.com/zeromq/libzmq.git")

    add_versions("4.3.2", "ebd7b5c830d6428956b67a0454a7f8cbed1de74b3b01e5c33c5378e22740f763")

    on_load(function (package)
        package:addenv("LD_LIBRARY_PATH", path.join(package:installdir("lib")))
    end)

    if is_host("windows") then
        add_deps("cmake")
    end

    on_install("windows", function (package)
        local configs = {}
        table.insert(configs, "-DBUILD_SHARED_LIBS=" .. (package:config("shared") and "ON" or "OFF"))
        import("package.tools.cmake").install(package, configs)
    end)

    on_install("linux", "macosx", function (package)
        local configs = {}
        import("package.tools.autoconf").install(package, configs)
    end)
 
    on_test(function (package)
        assert(package:has_cfuncs("zmq_msg_init_size", {includes = "zmq.h"}))
    end)
package_end()

package("zlib")

    set_homepage("http://www.zlib.net")
    set_description("A Massively Spiffy Yet Delicately Unobtrusive Compression Library")

    set_urls("http://zlib.net/zlib-$(version).tar.gz",
             "https://downloads.sourceforge.net/project/libpng/zlib/$(version)/zlib-$(version).tar.gz")

    add_versions("1.2.10", "8d7e9f698ce48787b6e1c67e6bff79e487303e66077e25cb9784ac8835978017")
    add_versions("1.2.11", "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1")

    on_load(function (package)
        package:addenv("LD_LIBRARY_PATH", path.join(package:installdir("lib")))
    end)

    on_install("windows", function (package)
        io.gsub("win32/Makefile.msc", "%-MD", "-" .. package:config("vs_runtime"))
        os.vrun("nmake -f win32\\Makefile.msc zlib.lib")
        os.cp("zlib.lib", package:installdir("lib"))
        os.cp("*.h", package:installdir("include"))
    end)

    on_install("linux", "macosx", function (package)
        import("package.tools.autoconf").install(package, {"--static"})
    end)
 
    on_install("iphoneos", "android@linux,macosx", "mingw@linux,macosx", function (package)
        import("package.tools.autoconf").configure(package, {host = "", "--static"})
        io.gsub("Makefile", "\nAR=.-\n",      "\nAR=" .. (package:build_getenv("ar") or "") .. "\n")
        io.gsub("Makefile", "\nARFLAGS=.-\n", "\nARFLAGS=cr\n")
        io.gsub("Makefile", "\nRANLIB=.-\n",  "\nRANLIB=\n")
        os.vrun("make install -j4")
    end)

    on_test(function (package)
        assert(package:has_cfuncs("inflate", {includes = "zlib.h"}))
    end)
package_end()

add_requires("zeromq", "zlib", {system = false})

-- add target
target("testr")

    -- set kind
    set_kind("binary")

    -- add files
    add_files("src/*.cpp")

    add_packages("zeromq", "zlib")

    before_run(function (target)
        print(os.getenv("LD_LIBRARY_PATH"))
    end)
```

**Comment by waruqi** [comment]
我刚dev分支，LD_LIBRARY_PATH自动追加了，对每个package。。不用在package里面额外设置了。。你可以更新下试试 xmake update dev

**Comment by linuxsky** [comment]
> zeromq 我默认改成 static了，可以通过 `add_requires("xx", {configs = {shared=true}})``启用动态库版本，protobuf 2低版本太老了，我就不支持了。。
> 
> opencv 3.4.9编译报什么错？ 我这网不行 下载太慢，暂时复现不了

这个错误，应该是个通病，好像是下载下不到。
```
[ 84%] Building CXX object modules/tracking/CMakeFiles/opencv_tracking.dir/src/trackerMILModel.cpp.o
[ 84%] Building CXX object modules/tracking/CMakeFiles/opencv_tracking.dir/src/trackerMedianFlow.cpp.o
[ 84%] Building CXX object modules/tracking/CMakeFiles/opencv_tracking.dir/src/trackerModel.cpp.o
[ 84%] Building CXX object modules/tracking/CMakeFiles/opencv_tracking.dir/src/trackerSampler.cpp.o
[ 85%] Building CXX object modules/tracking/CMakeFiles/opencv_tracking.dir/src/trackerSamplerAlgorithm.cpp.o
[ 85%] Building CXX object modules/tracking/CMakeFiles/opencv_tracking.dir/src/trackerStateEstimator.cpp.o
[ 85%] Building CXX object modules/tracking/CMakeFiles/opencv_tracking.dir/src/tracking_utils.cpp.o
[ 85%] Building CXX object modules/tracking/CMakeFiles/opencv_tracking.dir/src/unscented_kalman.cpp.o
[ 85%] Building CXX object modules/tracking/CMakeFiles/opencv_tracking.dir/opencl_kernels_tracking.cpp.o
[ 85%] Linking CXX static library ../../lib/libopencv_tracking.a
[ 85%] Built target opencv_tracking
[ 86%] Built target opencv_videostab
[ 86%] Building CXX object modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/src/boostdesc.cpp.o
/home/auto1/.xmake/cache/packages/2003/o/opencv/3.4.9/resources/opencv_contrib/3.4.9.tar.gz.dir/opencv_contrib-3.4.9/modules/xfeatures2d/src/boostdesc.cpp:654:20: fatal error: boostdesc_bgm.i: No such file or directory
           #include "boostdesc_bgm.i"
                    ^~~~~~~~~~~~~~~~~
compilation terminated.
modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/build.make:80: recipe for target 'modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/src/boostdesc.cpp.o' failed
make[2]: *** [modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/src/boostdesc.cpp.o] Error 1
CMakeFiles/Makefile2:4012: recipe for target 'modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/all' failed
make[1]: *** [modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
error: cannot copy file install/lib, error: not found this file
  => install opencv 3.4.9 .. failed
error: install failed!
```

**Comment by linuxsky** [comment]
> ev分支，LD_LIBRARY_PATH自动追加了，对每个package。。不用在package里面额外设置了。。你可以更新下试试 xmake update dev

dev 分之测试了是好的，LD_LIBRARY_PATH。这个能合到主线么？ 或者加个什么开关开启？

**Comment by linuxsky** [comment]
> > zeromq 我默认改成 static了，可以通过 `add_requires("xx", {configs = {shared=true}})``启用动态库版本，protobuf 2低版本太老了，我就不支持了。。
> > opencv 3.4.9编译报什么错？ 我这网不行 下载太慢，暂时复现不了
> 
> 这个错误，应该是个通病，好像是下载下不到。
> 
> ```
> [ 84%] Building CXX object modules/tracking/CMakeFiles/opencv_tracking.dir/src/trackerMILModel.cpp.o
> [ 84%] Building CXX object modules/tracking/CMakeFiles/opencv_tracking.dir/src/trackerMedianFlow.cpp.o
> [ 84%] Building CXX object modules/tracking/CMakeFiles/opencv_tracking.dir/src/trackerModel.cpp.o
> [ 84%] Building CXX object modules/tracking/CMakeFiles/opencv_tracking.dir/src/trackerSampler.cpp.o
> [ 85%] Building CXX object modules/tracking/CMakeFiles/opencv_tracking.dir/src/trackerSamplerAlgorithm.cpp.o
> [ 85%] Building CXX object modules/tracking/CMakeFiles/opencv_tracking.dir/src/trackerStateEstimator.cpp.o
> [ 85%] Building CXX object modules/tracking/CMakeFiles/opencv_tracking.dir/src/tracking_utils.cpp.o
> [ 85%] Building CXX object modules/tracking/CMakeFiles/opencv_tracking.dir/src/unscented_kalman.cpp.o
> [ 85%] Building CXX object modules/tracking/CMakeFiles/opencv_tracking.dir/opencl_kernels_tracking.cpp.o
> [ 85%] Linking CXX static library ../../lib/libopencv_tracking.a
> [ 85%] Built target opencv_tracking
> [ 86%] Built target opencv_videostab
> [ 86%] Building CXX object modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/src/boostdesc.cpp.o
> /home/auto1/.xmake/cache/packages/2003/o/opencv/3.4.9/resources/opencv_contrib/3.4.9.tar.gz.dir/opencv_contrib-3.4.9/modules/xfeatures2d/src/boostdesc.cpp:654:20: fatal error: boostdesc_bgm.i: No such file or directory
>            #include "boostdesc_bgm.i"
>                     ^~~~~~~~~~~~~~~~~
> compilation terminated.
> modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/build.make:80: recipe for target 'modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/src/boostdesc.cpp.o' failed
> make[2]: *** [modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/src/boostdesc.cpp.o] Error 1
> CMakeFiles/Makefile2:4012: recipe for target 'modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/all' failed
> make[1]: *** [modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/all] Error 2
> Makefile:162: recipe for target 'all' failed
> make: *** [all] Error 2
> error: cannot copy file install/lib, error: not found this file
>   => install opencv 3.4.9 .. failed
> error: install failed!
> ```

这个问题是opencv 的问题，但是opencv 如果编译成为静态库 是有问题的，因为opencv 本身会编译很多第三方库，然后在静态库链接的时候 提示找不到很多函数，我把opencv 该生shared 方式 就可以了。

**Comment by waruqi** [comment]
哦 等回头有时间我看看 ld_library_path那个我支持了 你可以更新下dev版本时候 不行opencv你先shared好了

**Comment by waruqi** [comment]
你这里什么系统？linux? 我这里mac上试了下 opencv 3.4.9安装没啥问题么。。也没这错误

**Comment by linuxsky** [comment]
> 你这里什么系统？linux? 我这里mac上试了下 opencv 3.4.9安装没啥问题么。。也没这错误

我这里是ubuntu，不过目前改了下也没啥问题了。 暂时先用自己写的package了。
