### ISSUE TITLE
set_languages 在生成项目时没有生成对应规则

### ISSUE THREAD

**Issue by wicast** [xmake-io/xmake#705]
### 描述问题

xmake.lua 文件中写了 set_languages("cxx17") 
生成的 cmakelists.txt 中没有同样效果的set(CMAKE_CXX_STANDARD 17) set(CMAKE_CXX_EXTENSIONS OFF)，生成的 visual studio 项目打开后也会提示不支持的语法

### 期待的结果

生成项目时正确处理 set_languages

**Comment by waruqi** [comment]
我看生效了的么 

```
set_property(TARGET test PROPERTY CXX_STANDARD 17)
```

并且编译我看带了 -std=gnu++1z的么 没问题啊 

效果跟你的 set(CMAKE_CXX_STANDARD 17)
应该是一样的，但你这个只能全局设置，不能针对特定target单独设置

所以xmake里面不能这么用，另外我这边测试正常 没看出哪里有问题

**Comment by wicast** [comment]
我知道了，我是写在了target里……
