### ISSUE TITLE
更好的vcpkg互操作性

### ISSUE THREAD

**Issue by codehz** [xmake-io/xmake#706]
### 你在什么场景下需要该功能？

部分包在vcpkg下打包更为完善（如boost，可以按照具体部件打包而无需一次性引入全部，以及可以设置依赖参数），但是vcpkg对一些包没有提供自动配置头文件的功能，这导致在xmake中无法正确找到头文件（以及库文件，而且这不可能自动化的查找）

### 描述可能的解决方案

一个最简单且通用的方案是允许用户直接取得对应triplet的installed路径，然后自行配置相关头文件和库
当然这就可能要加入新的api了
我觉得还可以进一步提升，比如允许用户手动指定vcpkg的triplet

### 描述你认为的候选方案

另一种方法就是提供给vcpkg的包做附加元数据的方便函数，比如增加选项要求主动引入某些路径作为include，和lib

**Comment by waruqi** [comment]
目前远程包本身的架构设计上，原本就支持用户透传特定配置给包管理器处理的，不过现在就对xmake repo以及conan包我做了很好的透传支持，vcpkg因为目前用的人不多，没多少人跟我反馈，所以我之前懒得搞。。

conan里面透传方式：

```lua
add_requires("CONAN::OpenSSL/1.0.2n@conan/stable", {alias = "openssl", 
    configs = {options = "OpenSSL:shared=True"}})
```

具体可以看下：
https://github.com/xmake-io/xmake/issues/339

目前支持的conan包仓库特定参数扩展以及如何整合的，可以看下：

https://github.com/xmake-io/xmake/blob/acca2c3115570e7f3b1ef059413c4dce49c520d1/xmake/modules/package/manager/conan/install_package.lua#L112-L121

而xmake-repo等内置包，对这块的透传做的更好，可以按需定制编译特定版本的包，现在都是支持的。。


而vcpkg对这块扩展支持，也是很方便的，如果用户需求量大， 也是可以考虑后期加上定制化配置的，等有时间我会考虑弄下。。主要也就是改下： vcpkg/find_package/install_package.lua 

添加上内置vcpkg特有的配置参数，然后透传给vcpkg命令就行了。。

**Comment by codehz** [comment]
主要是现在的情况是部分vcpkg引入的包找不到头文件和库文件，而且它本身也没提供配置功能（cmake也找不到的那种，不存在元数据，只能手动找

**Comment by waruqi** [comment]
是怎么个找不到法，能给个具体lib么 我看下，一种是可以改进xmake内置的find_package让它找到，一种是在用户项目里提供自定义find_package.lua来进一步改进find让它找到，或者也可以通过透传includedir和linkdir到add_requires让其找到，这种得改下才能支持

**Comment by codehz** [comment]
示例： vcpkg::boost-beast 
需求： 能跑通官方coro-server示例（windows/linux），其中需要链接一些库才能跑通

**Comment by waruqi** [comment]
哦 等我忙完其他的 回头看看这个。。

**Comment by waruqi** [comment]
我搞了个demo在linux下测了下，没啥问题么，能正常编译通过，运行也ok，仅仅只是加个pthread库，

```lua
add_requires("vcpkg::boost-beast", {alias = "boost-beast"})
set_languages("c++11")

target("test")
    set_kind("binary")
    add_files("src/*.cpp") 
    add_packages("boost-beast")
    add_syslinks("pthread")
```

```console
[  0%]: ccache compiling.release src/main.cpp
/usr/bin/ccache /usr/bin/gcc -c -fvisibility=hidden -O3 -std=c++11 -I/mnt/vcpkg-2020.01/installed/x64-linux/include -m64 -I/usr/local/include -I/usr/include -o build/.objs/test/linux/x86_64/release/src/main.cpp.o src/main.cpp
checking for the flags (-MMD -MF) ... ok
[100%]: linking.release test
/usr/bin/g++ -o build/linux/x86_64/release/test build/.objs/test/linux/x86_64/release/src/main.cpp.o -s -fvisibility=hidden -lpthread -m64 -L/usr/local/lib -L/usr/lib
```

**Comment by waruqi** [comment]
我试了下这个例子：https://github.com/boostorg/beast/blob/develop/example/websocket/server/coro/websocket_server_coro.cpp

除了boost自身有点bug，需要手动patch下，https://github.com/boostorg/coroutine/pull/45

其他还好么，加上对应需要的依赖库模块，可以正常编译运行。。也没啥问题，也不需要额外传入什么参数么。。

```lua
add_requires("vcpkg::boost-beast", {alias = "boost-beast"})
add_requires("vcpkg::boost-coroutine", {alias = "boost-coroutine"})
add_requires("vcpkg::boost-context", {alias = "boost-context"})
add_requires("vcpkg::boost-thread", {alias = "boost-thread"})

set_languages("c++11")

target("test")
    set_kind("binary")
    add_files("src/*.cpp") 
    add_packages("boost-beast", "boost-coroutine", "boost-context", "boost-thread")
    add_syslinks("pthread")
```

**Comment by waruqi** [comment]
目前看似乎没必要透传add_requires参数给vcpkg了，这里先close了。。有问题再开新的吧
