### ISSUE TITLE
error: cannot get program for ar

### ISSUE THREAD

**Issue by llatecomers** [xmake-io/xmake#707]
MAC OS上面编译android版本，
xmake f -c -p android

checking for the architecture ... armv7-a
checking for the NDK directory ... /Users/hubinxiong/Library/Android/android-ndk-r20b
checking for the SDK version of NDK ... 21
checking for the toolchains version of NDK ... 4.9
checking for the Android SDK directory ... /Users/hubinxiong/Library/Android/sdk
checking for the Build Tools Version of Android SDK ... 29.0.3

xmake:遇到如下错误
[ 48%]: compiling.release src/tbox/platform/socket.c
error: cannot get program for ar

已参考issue#592中所提示的步骤:
xmake update dev
升级之后还是提示 error: cannot get program for ar。

**Comment by waruqi** [comment]
xmake f -c -p android -v -D
xmake -r -v -D 

执行下这两个，给我看下完整错误信息

**Comment by llatecomers** [comment]
hubinxiongdeMacBook-Pro:tbox hubinxiong$ xmake -r -v -D
configure
{
    sh = /usr/bin/clang++
    deprecated = false
    gcc_toolchain = /Users/hubinxiong/Library/Android/android-ndk-r20b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64
    clean = true
    polarssl = false
    pcre = false
    ndk_toolchains_ver = 4.9
    object = false
    arch = armv7-a
    sqlite3 = false
    ndk_sdkver = 21
    info = false
    cc = /usr/bin/clang
    cross = arm-linux-androideabi-
    sdk = /Users/hubinxiong/Library/Android/sdk
    force-utf8 = false
    wchar = false
    build_toolver = 29.0.3
    float = true
    ndk_stdcxx = true
    host = macosx
    charset = false
    xml = false
    bin = /Users/hubinxiong/Library/Android/android-ndk-r20b/toolchains/llvm/prebuilt/darwin-x86_64/bin
    exception = false
    database = false
    demo = true
    ndkver = 20
    openssl = false
    pcre2 = false
    zlib = false
    android_sdk = /Users/hubinxiong/Library/Android/sdk
    regex = false
    micro = false
    coroutine = false
    plat = android
    ccache = true
    hash = false
    buildir = build
    zip = false
    ld = /usr/bin/clang++
    mbedtls = false
    ndk = /Users/hubinxiong/Library/Android/android-ndk-r20b
    small = true
    mode = release
    mysql = false
    kind = static
}
checkinfo: @programdir/core/sandbox/modules/os.lua:258: cannot runv(/Users/hubinxiong/Library/Android/android-ndk-r20b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ar -cr /var/folders/xt/4pcqp08n3951zrr1s0b4xx880000gn/T/.xmake501/200314/_6D3244C2E41A42308EB421368B574460.a /var/folders/xt/4pcqp08n3951zrr1s0b4xx880000gn/T/.xmake501/200314/_29DB737279D245308C069F85BA675460.o), error: Permission denied
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:781]: in function 'raise'
    [@programdir/core/sandbox/modules/os.lua:258]: in function 'runv'
    [@programdir/modules/detect/tools/find_ar.lua:38]:
    [C]: in function 'load'
    [.../core/sandbox/modules/import/lib/detect/find_program.lua:67]: in function '_check'
    [.../core/sandbox/modules/import/lib/detect/find_program.lua:115]: in function '_find_from_pathes'
    [.../core/sandbox/modules/import/lib/detect/find_program.lua:156]: in function '_find'
    [.../core/sandbox/modules/import/lib/detect/find_program.lua:267]: in function 'find_tool'
    [@programdir/modules/lib/detect/find_tool.lua:32]: in function '_find_from_modules'
    [@programdir/modules/lib/detect/find_tool.lua:71]: in function 'find_tool'
    [@programdir/modules/private/platform/check_toolchain.lua:41]: in function '_check_tool'
    [@programdir/modules/private/platform/check_toolchain.lua:77]: in function 'check_toolchain'
    [@programdir/platforms/android/config.lua:132]: in function 'on_check'
    [@programdir/core/platform/platform.lua:327]: in function 'tool'
    [@programdir/core/tool/tool.lua:158]: in function 'load'
    [@programdir/core/tool/linker.lua:93]: in function '_load_tool'
    [@programdir/core/tool/linker.lua:129]: in function 'load'
    [@programdir/core/project/target.lua:446]: in function 'linker'
    [@programdir/core/project/target.lua:795]: in function 'targetfile'
    [@programdir/actions/build/build.lua:31]: in function '_clean_target'
    [@programdir/actions/build/build.lua:130]: in function '_build_target'
    [@programdir/actions/build/build.lua:164]: in function '_build_target_and_deps'
    [@programdir/actions/build/build.lua:236]: in function 'build'
    [@programdir/actions/build/main.lua:115]:
    [C]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [@programdir/actions/build/main.lua:109]:
    [C]: in function 'load'
    [@programdir/core/base/task.lua:520]: in function 'run'
    [@programdir/core/main.lua:259]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:315]:

checkinfo: @programdir/core/sandbox/modules/os.lua:258: cannot runv(arm-linux-androideabi-ar -cr /var/folders/xt/4pcqp08n3951zrr1s0b4xx880000gn/T/.xmake501/200314/_4BE9AA89176544008AA36B762A05CF10.a /var/folders/xt/4pcqp08n3951zrr1s0b4xx880000gn/T/.xmake501/200314/_9323E58C04884D308DD72034DEB61770.o), error: No such file or directory
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:781]: in function 'raise'
    [@programdir/core/sandbox/modules/os.lua:258]: in function 'runv'
    [@programdir/modules/detect/tools/find_ar.lua:38]:
    [C]: in function 'load'
    [.../core/sandbox/modules/import/lib/detect/find_program.lua:67]: in function '_check'
    [.../core/sandbox/modules/import/lib/detect/find_program.lua:213]: in function '_find'
    [.../core/sandbox/modules/import/lib/detect/find_program.lua:267]: in function 'find_tool'
    [@programdir/modules/lib/detect/find_tool.lua:32]: in function '_find_from_modules'
    [@programdir/modules/lib/detect/find_tool.lua:71]: in function 'find_tool'
    [@programdir/modules/private/platform/check_toolchain.lua:41]: in function '_check_tool'
    [@programdir/modules/private/platform/check_toolchain.lua:77]: in function 'check_toolchain'
    [@programdir/platforms/android/config.lua:132]: in function 'on_check'
    [@programdir/core/platform/platform.lua:327]: in function 'tool'
    [@programdir/core/tool/tool.lua:158]: in function 'load'
    [@programdir/core/tool/linker.lua:93]: in function '_load_tool'
    [@programdir/core/tool/linker.lua:129]: in function 'load'
    [@programdir/core/project/target.lua:446]: in function 'linker'
    [@programdir/core/project/target.lua:795]: in function 'targetfile'
    [@programdir/actions/build/build.lua:31]: in function '_clean_target'
    [@programdir/actions/build/build.lua:130]: in function '_build_target'
    [@programdir/actions/build/build.lua:164]: in function '_build_target_and_deps'
    [@programdir/actions/build/build.lua:236]: in function 'build'
    [@programdir/actions/build/main.lua:115]:
    [C]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [@programdir/actions/build/main.lua:109]:
    [C]: in function 'load'
    [@programdir/core/base/task.lua:520]: in function 'run'
    [@programdir/core/main.lua:259]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:315]:

checking for the arm-linux-androideabi-ar ... no
checking for the static library archiver (ar: ar) ... no
checkinfo: cannot runv(/Users/hubinxiong/Library/Android/android-ndk-r20b/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar -version), error: Permission denied
checkinfo: cannot runv(llvm-ar -version), error: No such file or directory
checking for the llvm-ar ... no
checking for the static library archiver (ar: llvm-ar) ... no
error: @programdir/core/main.lua:261: @programdir/actions/build/main.lua:123: @programdir/core/project/target.lua:448: cannot get program for ar
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:781]: in function 'raise'
    [@programdir/core/project/target.lua:448]: in function 'linker'
    [@programdir/core/project/target.lua:795]: in function 'targetfile'
    [@programdir/actions/build/build.lua:31]: in function '_clean_target'
    [@programdir/actions/build/build.lua:130]: in function '_build_target'
    [@programdir/actions/build/build.lua:164]: in function '_build_target_and_deps'
    [@programdir/actions/build/build.lua:236]: in function 'build'
    [@programdir/actions/build/main.lua:115]:
    [C]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [@programdir/actions/build/main.lua:109]:
    [C]: in function 'load'
    [@programdir/core/base/task.lua:520]: in function 'run'
    [@programdir/core/main.lua:259]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:315]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:781: in function 'raise'
	@programdir/core/main.lua:261: in function 'cotask'
	@programdir/core/base/scheduler.lua:315: in function <@programdir/core/base/scheduler.lua:313>

**Comment by waruqi** [comment]
> runv(/Users/hubinxiong/Library/Android/android-ndk-r20b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ar -cr /var/folders/xt/4pcqp08n3951zrr1s0b4xx880000gn/T/.xmake501/200314/_6D3244C2E41A42308EB421368B574460.a /var/folders/xt/4pcqp08n3951zrr1s0b4xx880000gn/T/.xmake501/200314/_29DB737279D245308C069F85BA675460.o), error: Permission denied

你看下错误：Permission denied

请确认下对应的临时目录有可读写权限

**Comment by llatecomers** [comment]
改完/var的权限后：
hubinxiongdeMacBook-Pro:tbox hubinxiong$ xmake -r -v -D
configure
{
    sh = /usr/bin/clang++
    deprecated = false
    gcc_toolchain = /Users/hubinxiong/Desktop/android-ndk-r20b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64
    clean = true
    polarssl = false
    pcre = false
    ndk_toolchains_ver = 4.9
    object = false
    arch = armv7-a
    sqlite3 = false
    ndk_sdkver = 21
    info = false
    cc = /usr/bin/clang
    cross = arm-linux-androideabi-
    sdk = /Users/hubinxiong/Library/Android/sdk
    force-utf8 = false
    wchar = false
    build_toolver = 29.0.3
    float = true
    ndk_stdcxx = true
    host = macosx
    charset = false
    xml = false
    bin = /Users/hubinxiong/Desktop/android-ndk-r20b/toolchains/llvm/prebuilt/darwin-x86_64/bin
    exception = false
    database = false
    demo = true
    ndkver = 20
    openssl = false
    pcre2 = false
    zlib = false
    android_sdk = /Users/hubinxiong/Library/Android/sdk
    regex = false
    micro = false
    coroutine = false
    plat = android
    ccache = true
    hash = false
    buildir = build
    zip = false
    ld = /usr/bin/clang++
    mbedtls = false
    ndk = /Users/hubinxiong/Desktop/android-ndk-r20b
    small = true
    mode = release
    mysql = false
    kind = static
}
checkinfo: @programdir/core/sandbox/modules/os.lua:258: cannot runv(/Users/hubinxiong/Desktop/android-ndk-r20b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ar -cr /var/folders/xt/4pcqp08n3951zrr1s0b4xx880000gn/T/.xmake501/200316/_63C61E57A6294D10803E6507A4A3FC30.a /var/folders/xt/4pcqp08n3951zrr1s0b4xx880000gn/T/.xmake501/200316/_631D4A53EDE547308420CA156EAF9E60.o), error: Permission denied
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:781]: in function 'raise'
    [@programdir/core/sandbox/modules/os.lua:258]: in function 'runv'
    [@programdir/modules/detect/tools/find_ar.lua:38]:
    [C]: in function 'load'
    [.../core/sandbox/modules/import/lib/detect/find_program.lua:67]: in function '_check'
    [.../core/sandbox/modules/import/lib/detect/find_program.lua:115]: in function '_find_from_pathes'
    [.../core/sandbox/modules/import/lib/detect/find_program.lua:156]: in function '_find'
    [.../core/sandbox/modules/import/lib/detect/find_program.lua:267]: in function 'find_tool'
    [@programdir/modules/lib/detect/find_tool.lua:32]: in function '_find_from_modules'
    [@programdir/modules/lib/detect/find_tool.lua:71]: in function 'find_tool'
    [@programdir/modules/private/platform/check_toolchain.lua:41]: in function '_check_tool'
    [@programdir/modules/private/platform/check_toolchain.lua:77]: in function 'check_toolchain'
    [@programdir/platforms/android/config.lua:132]: in function 'on_check'
    [@programdir/core/platform/platform.lua:327]: in function 'tool'
    [@programdir/core/tool/tool.lua:158]: in function 'load'
    [@programdir/core/tool/linker.lua:93]: in function '_load_tool'
    [@programdir/core/tool/linker.lua:129]: in function 'load'
    [@programdir/core/project/target.lua:446]: in function 'linker'
    [@programdir/core/project/target.lua:795]: in function 'targetfile'
    [@programdir/actions/build/build.lua:31]: in function '_clean_target'
    [@programdir/actions/build/build.lua:130]: in function '_build_target'
    [@programdir/actions/build/build.lua:164]: in function '_build_target_and_deps'
    [@programdir/actions/build/build.lua:236]: in function 'build'
    [@programdir/actions/build/main.lua:115]:
    [C]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [@programdir/actions/build/main.lua:109]:
    [C]: in function 'load'
    [@programdir/core/base/task.lua:520]: in function 'run'
    [@programdir/core/main.lua:259]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:315]:

checkinfo: @programdir/core/sandbox/modules/os.lua:258: cannot runv(arm-linux-androideabi-ar -cr /var/folders/xt/4pcqp08n3951zrr1s0b4xx880000gn/T/.xmake501/200316/_7F9AE74B8FF649208C8FE82B7B537540.a /var/folders/xt/4pcqp08n3951zrr1s0b4xx880000gn/T/.xmake501/200316/_ADD7446BBB574B2087E7467E4D81E430.o), error: No such file or directory
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:781]: in function 'raise'
    [@programdir/core/sandbox/modules/os.lua:258]: in function 'runv'
    [@programdir/modules/detect/tools/find_ar.lua:38]:
    [C]: in function 'load'
    [.../core/sandbox/modules/import/lib/detect/find_program.lua:67]: in function '_check'
    [.../core/sandbox/modules/import/lib/detect/find_program.lua:213]: in function '_find'
    [.../core/sandbox/modules/import/lib/detect/find_program.lua:267]: in function 'find_tool'
    [@programdir/modules/lib/detect/find_tool.lua:32]: in function '_find_from_modules'
    [@programdir/modules/lib/detect/find_tool.lua:71]: in function 'find_tool'
    [@programdir/modules/private/platform/check_toolchain.lua:41]: in function '_check_tool'
    [@programdir/modules/private/platform/check_toolchain.lua:77]: in function 'check_toolchain'
    [@programdir/platforms/android/config.lua:132]: in function 'on_check'
    [@programdir/core/platform/platform.lua:327]: in function 'tool'
    [@programdir/core/tool/tool.lua:158]: in function 'load'
    [@programdir/core/tool/linker.lua:93]: in function '_load_tool'
    [@programdir/core/tool/linker.lua:129]: in function 'load'
    [@programdir/core/project/target.lua:446]: in function 'linker'
    [@programdir/core/project/target.lua:795]: in function 'targetfile'
    [@programdir/actions/build/build.lua:31]: in function '_clean_target'
    [@programdir/actions/build/build.lua:130]: in function '_build_target'
    [@programdir/actions/build/build.lua:164]: in function '_build_target_and_deps'
    [@programdir/actions/build/build.lua:236]: in function 'build'
    [@programdir/actions/build/main.lua:115]:
    [C]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [@programdir/actions/build/main.lua:109]:
    [C]: in function 'load'
    [@programdir/core/base/task.lua:520]: in function 'run'
    [@programdir/core/main.lua:259]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:315]:

checking for the arm-linux-androideabi-ar ... no
checking for the static library archiver (ar: ar) ... no
checkinfo: cannot runv(/Users/hubinxiong/Desktop/android-ndk-r20b/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar -version), error: Permission denied
checkinfo: cannot runv(llvm-ar -version), error: No such file or directory
checking for the llvm-ar ... no
checking for the static library archiver (ar: llvm-ar) ... no
error: @programdir/core/main.lua:261: @programdir/actions/build/main.lua:123: @programdir/core/project/target.lua:448: cannot get program for ar
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:781]: in function 'raise'
    [@programdir/core/project/target.lua:448]: in function 'linker'
    [@programdir/core/project/target.lua:795]: in function 'targetfile'
    [@programdir/actions/build/build.lua:31]: in function '_clean_target'
    [@programdir/actions/build/build.lua:130]: in function '_build_target'
    [@programdir/actions/build/build.lua:164]: in function '_build_target_and_deps'
    [@programdir/actions/build/build.lua:236]: in function 'build'
    [@programdir/actions/build/main.lua:115]:
    [C]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [@programdir/actions/build/main.lua:109]:
    [C]: in function 'load'
    [@programdir/core/base/task.lua:520]: in function 'run'
    [@programdir/core/main.lua:259]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:315]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:781: in function 'raise'
	@programdir/core/main.lua:261: in function 'cotask'
	@programdir/core/base/scheduler.lua:315: in function <@programdir/core/base/scheduler.lua:313>

**Comment by waruqi** [comment]
你看下改完后 加 -vD执行 还有  error: Permission denied 字样的权限错误

或者，手动执行下 /Users/hubinxiong/Library/Android/android-ndk-r20b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ar  --help 看看，能否正常执行。。

这边也是mac，也是一直用的r20b ，从没有过问题。。看你这错误就是权限问题导致尝试运行ar检测执行失败了。。

**Comment by waruqi** [comment]
不行你就吧 /Users/hubinxiong/Library/Android/android-ndk-r20b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin 整个改成可执行权限试试

chmod -R 777 /Users/hubinxiong/Library/Android/android-ndk-r20b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin

**Comment by llatecomers** [comment]
NDK官网上下载的包不知道为啥解压了不能用，在android studio中下载的ndk可以直接使用。
