### ISSUE TITLE
Win10 Qt mingw 动态库生成失败

### ISSUE THREAD

**Issue by conlay-cn** [xmake-io/xmake#709]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题

在Win10下，Qt5.7.0，Qt自带mingw环境，使用模板生成
xmake create -t qt.console co
和
xmake create -t qt.static st
都能通过。
但是生成动态库却是失败，命令和过程如下：
生成模板
PS C:\workspace> xmake create -t qt.shared sh          
create sh ...
  [+]: src\demo.cpp
  [+]: src\demo.h
  [+]: src\demo_global.h
  [+]: xmake.lua
  [+]: .gitignore
create ok!
环境配置
PS C:\workspace\sh> xmake f -v -D -c -p mingw -a i386 --qt=C:\Qt\5.7.0 --sdk=C:\Qt\Qt5.7.0\Tools\mingw530_32
checking for the mingw directory ... C:\Qt\Qt5.7.0\Tools\mingw530_32
checking for the Qt SDK directory ... C:\Qt\Qt5.7.0\5.7\mingw53_32
checking for the Qt SDK version ... 5.7.0
configure
{
    arch = i386
    ccache = true
    bin = C:\Qt\Qt5.7.0\Tools\mingw530_32\bin
    mode = release
    host = windows
    clean = true
    ndk_stdcxx = true
    plat = mingw
    sdk = C:\Qt\Qt5.7.0\Tools\mingw530_32
    mingw = C:\Qt\Qt5.7.0\Tools\mingw530_32
    kind = static
    buildir = build
    cross =
    qt_sdkver = 5.7.0
    qt = C:\Qt\Qt5.7.0\5.7\mingw53_32
}
编译
PS C:\workspace\sh> xmake -v -D > log.txt
log.txt文件内容如下：
configure
{
    ccache = true
    ndk_stdcxx = true
    plat = mingw
    sdk = C:\Qt\Qt5.7.0\Tools\mingw530_32
    mingw = C:\Qt\Qt5.7.0\Tools\mingw530_32
    buildir = build
    arch = i386
    clean = true
    qt_sdkver = 5.7.0
    cxx = C:\Qt\Qt5.7.0\Tools\mingw530_32\bin\gcc
    cross = 
    sh = C:\Qt\Qt5.7.0\Tools\mingw530_32\bin\g++
    kind = static
    bin = C:\Qt\Qt5.7.0\Tools\mingw530_32\bin
    host = windows
    mode = release
    qt = C:\Qt\5.7.0
}
[100%]: linking.release sh.dll
C:\\Qt\\Qt5.7.0\\Tools\\mingw530_32\\bin\\g++ -o build\\mingw\\i386\\release\\sh.dll build\\.objs\\sh\\mingw\\i386\\release\\src\\demo.cpp.obj -LC:\\\\Qt\\\\Qt5.7.0\\\\5.7\\\\mingw53_32\\\\lib -s -lQt5Gui -lQt5Core -lQt53DCore -lQt53DExtras -lQt53DInput -lQt53DLogic -lQt53DQuick -lQt53DQuickExtras -lQt53DQuickInput -lQt53DQuickRender -lQt53DRender -lQt5AxBase -lQt5AxContainer -lQt5AxServer -lQt5Bluetooth -lQt5Bootstrap -lQt5CLucene -lQt5Concurrent -lQt5DBus -lQt5Designer -lQt5DesignerComponents -lQt5Help -lQt5Location -lQt5Multimedia -lQt5MultimediaQuick_p -lQt5MultimediaWidgets -lQt5Network -lQt5Nfc -lQt5OpenGL -lQt5OpenGLExtensions -lQt5PacketProtocol -lQt5PlatformSupport -lQt5Positioning -lQt5PrintSupport -lQt5Purchasing -lQt5Qml -lQt5QmlDebug -lQt5QmlDevTools -lQt5Quick -lQt5QuickControls2 -lQt5QuickParticles -lQt5QuickTemplates2 -lQt5QuickTest -lQt5QuickWidgets -lQt5Script -lQt5ScriptTools -lQt5Scxml -lQt5Sensors -lQt5SerialBus -lQt5SerialPort -lQt5Sql -lQt5Svg -lQt5Test -lQt5UiTools -lQt5WebChannel -lQt5WebSockets -lQt5Widgets -lQt5WinExtras -lQt5Xml -lQt5XmlPatterns -lqtfreetype -lqtmain -lmingw32 -shared -m32 -Wl,--out-implib,build\\\\mingw\\\\i386\\\\release\\\\sh.lib
error: @programdir\core\main.lua:261: @programdir\actions\build\main.lua:123: @programdir\actions\build\kinds\shared.lua:104: @programdir\core\sandbox\modules\os.lua:321: C:\\Qt\\Qt5.7.0\\5.7\\mingw53_32\\lib/libQt5AxServer.a(qaxserverdll.o):qaxserverdll.cpp:(.text+0xf7): undefined reference to `_imp___ZNK7QObject10objectNameEv'
C:\\Qt\\Qt5.7.0\\5.7\\mingw53_32\\lib/libQt5AxServer.a(qaxserverdll.o):qaxserverdll.cpp:(.text+0x146): undefined reference to `_imp___ZNK7QStringeqE13QLatin1String'
C:\\Qt\\Qt5.7.0\\5.7\\mingw53_32\\lib/libQt5AxServer.a(qaxserverdll.o):qaxserverdll.cpp:(.text+0x189): undefined reference to `_imp___ZN10QArrayData10deallocateEPS_jj'
.................
C:\\Qt\\Qt5.7.0\\5.7\\mingw53_32\\lib/libQt5AxServer.a(qaxtypes.o):qaxtypes.cpp:(.text$_ZN5QListI8QVariantE18detach_helper_growEii[__ZN5QListI8QVariantE18detach_helper_growEii]+0xd3): undefined reference to `_imp___ZN8QVariantC1ERKS_'
C:\\Qt\\Qt5.7.0\\5.7\\mingw53_32\\lib/libQt5AxServer.a(qaxtypes.o):qaxtypes.cpp:(.text$_ZN5QListI8QVariantE6appendERKS0_[__ZN5QListI8QVariantE6appendERKS0_]+0x40): undefined reference to `_imp___ZN8QVariantC1ERKS_'
C:\\Qt\\Qt5.7.0\\5.7\\mingw53_32\\lib/libQt5AxServer.a(qaxtypes.o):qaxtypes.cpp:(.text$_ZN5QListI8QVariantE6appendERKS0_[__ZN5QListI8QVariantE6appendERKS0_]+0x53): undefined reference to `_imp___ZN9QListData6appendEv'
C:\\Qt\\Qt5.7.0\\5.7\\mingw53_32\\lib/libQt5Bootstrap.a(qbytearray.o):qbytearray.cpp:(.text$_Z11qUncompressPKhi+0x8c): undefined reference to `uncompress'
C:\\Qt\\Qt5.7.0\\5.7\\mingw53_32\\lib/libQt5Bootstrap.a(qbytearray.o):qbytearray.cpp:(.text$_Z9qCompressPKhii+0xb6): undefined reference to `compress2'
collect2.exe: error: ld returned 1 exit status

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:814]: in function 'raise'
    [@programdir\core\sandbox\modules\os.lua:321]: in function 'runv'
    [@programdir\modules\core\tools\gcc.lua:356]:
    [C]: in function 'link'
    [@programdir\actions\build\kinds\shared.lua:104]: in function '_do_link_target'
    [@programdir\actions\build\kinds\shared.lua:127]:
    [@programdir\actions\build\kinds\shared.lua:155]: in function '_link_target'
    [@programdir\actions\build\kinds\shared.lua:187]: in function 'build'
    [@programdir\actions\build\build.lua:40]: in function '_do_build_target'
    [@programdir\actions\build\build.lua:59]: in function 'on_build'
    [@programdir\actions\build\build.lua:107]: in function 'script'
    [@programdir\actions\build\build.lua:137]: in function '_build_target'
    [@programdir\actions\build\build.lua:164]: in function '_build_target_and_deps'
    [@programdir\actions\build\build.lua:236]: in function 'build'
    [@programdir\actions\build\main.lua:115]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\actions\build\main.lua:109]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:520]: in function 'run'
    [@programdir\core\main.lua:259]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:306]:

stack traceback:
	[C]: in function 'error'
	@programdir\core\base\os.lua:814: in function 'raise'
	@programdir\core\main.lua:261: in function 'cotask'
	@programdir\core\base\scheduler.lua:306: in function <@programdir\core\base\scheduler.lua:304>
中间太长了，没有粘上来，从第1865行开始接的
麻烦给看一下。

以下是Qt控制台程序，没问题
PS C:\workspace> xmake create -t qt.console co
create co ...
  [+]: src\main.cpp
  [+]: xmake.lua
  [+]: .gitignore
create ok!
PS C:\workspace> cd co
PS C:\workspace\co> xmake f -v -D -c -p mingw -a i386 --qt=C:\Qt\5.7.0 --sdk=C:\Qt\Qt5.7.0\Tools\mingw530_32
checking for the mingw directory ... C:\Qt\Qt5.7.0\Tools\mingw530_32
checking for the Qt SDK directory ... C:\Qt\Qt5.7.0\5.7\mingw53_32
checking for the Qt SDK version ... 5.7.0
configure
{
    arch = i386
    ccache = true
    bin = C:\Qt\Qt5.7.0\Tools\mingw530_32\bin
    mode = release
    host = windows
    clean = true
    ndk_stdcxx = true
    plat = mingw
    sdk = C:\Qt\Qt5.7.0\Tools\mingw530_32
    mingw = C:\Qt\Qt5.7.0\Tools\mingw530_32
    kind = static
    buildir = build
    cross =
    qt_sdkver = 5.7.0
    qt = C:\Qt\Qt5.7.0\5.7\mingw53_32
}
PS C:\workspace\co> xmake -v -D                                                               configure
{
    arch = i386
    ccache = true
    clean = true
    cross =
    host = windows
    mode = release
    ndk_stdcxx = true
    plat = mingw
    sdk = C:\Qt\Qt5.7.0\Tools\mingw530_32
    mingw = C:\Qt\Qt5.7.0\Tools\mingw530_32
    kind = static
    buildir = build
    bin = C:\Qt\Qt5.7.0\Tools\mingw530_32\bin
    qt_sdkver = 5.7.0
    qt = C:\Qt\5.7.0
}
checking for the gcc ... C:\Qt\Qt5.7.0\Tools\mingw530_32\bin\gcc
checking for the c++ compiler (cxx) ... gcc
checking for the C:\Qt\Qt5.7.0\Tools\mingw530_32\bin\gcc ... ok
checking for the flags (-O3) ... ok
> gcc "-O3"
checking for the flags (-fPIC) ... ok
> gcc "-fPIC"
checking for the ccache ... no
[  0%]: compiling.release src\main.cpp
C:\\Qt\\Qt5.7.0\\Tools\\mingw530_32\\bin\\gcc -c -fvisibility=hidden -O3 -std=c++11 -IC:\\\\Qt\\\\Qt5.7.0\\\\5.7\\\\mingw53_32\\\\include\\\\QtCore -IC:\\\\Qt\\\\Qt5.7.0\\\\5.7\\\\mingw53_32\\\\include -IC:\\\\Qt\\\\Qt5.7.0\\\\5.7\\\\mingw53_32\\\\mkspecs\\\\win32-g++ -DQT_NO_DEBUG -DQT_DEPRECATED_WARNINGS -DQT_CORE_LIB -fPIC -m32 -o build\\.objs\\co\\mingw\\i386\\release\\src\\main.cpp.obj src\\main.cpp
checking for the flags (-MMD -MF) ... ok
> gcc "-MMD" "-MF" "C:\Users\conlay\AppData\Local\Temp\.xmake\200314\_BBAED641BB1A4C40847B0DD55059EE70"
checking for the flags (-fcolor-diagnostics) ... no
> gcc "-fcolor-diagnostics"
checkinfo: @programdir\core\sandbox\modules\os.lua:321: gcc: error: unrecognized command line option '-fcolor-diagnostics'

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:814]: in function 'raise'
    [@programdir\core\sandbox\modules\os.lua:321]: in function 'runv'
    [@programdir\modules\detect\tools\gcc\has_flags.lua:44]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\detect\tools\gcc\has_flags.lua:44]: in function 'hasflags'
    [@programdir\modules\lib\detect\has_flags.lua:114]: in function 'has_flags'
    [@programdir\modules\core\tools\gcc.lua:367]: in function '_has_color_diagnostics'
    [@programdir\modules\core\tools\gcc.lua:443]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\core\tools\gcc.lua:428]: in function '_compile1'
    [@programdir\modules\core\tools\gcc.lua:526]:
    [C]: in function 'compile'
    [@programdir\modules\private\action\build\object.lua:79]: in function '_do_build_file'
    [@programdir\modules\private\action\build\object.lua:118]: in function '_build_object'
    [@programdir\modules\private\action\build\object.lua:142]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:132]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:130]: in function 'cotask'
checking for the flags (-fdiagnostics-color=always) ... ok
> gcc "-fdiagnostics-color=always"
src\main.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 #include <QCoreApplication>
 ^
checking for the g++ ... C:\Qt\Qt5.7.0\Tools\mingw530_32\bin\g++
checking for the linker (ld) ... g++
[100%]: linking.release co.exe
C:\\Qt\\Qt5.7.0\\Tools\\mingw530_32\\bin\\g++ -o build\\mingw\\i386\\release\\co.exe build\\.objs\\co\\mingw\\i386\\release\\src\\main.cpp.obj -LC:\\\\Qt\\\\Qt5.7.0\\\\5.7\\\\mingw53_32\\\\lib -s -fvisibility=hidden -lQt5Core -lQt53DCore -lQt53DExtras -lQt53DInput -lQt53DLogic -lQt53DQuick -lQt53DQuickExtras -lQt53DQuickInput -lQt53DQuickRender -lQt53DRender -lQt5AxBase -lQt5AxContainer -lQt5AxServer -lQt5Bluetooth -lQt5Bootstrap -lQt5CLucene -lQt5Concurrent -lQt5DBus -lQt5Designer -lQt5DesignerComponents -lQt5Gui -lQt5Help -lQt5Location -lQt5Multimedia -lQt5MultimediaQuick_p -lQt5MultimediaWidgets -lQt5Network -lQt5Nfc -lQt5OpenGL -lQt5OpenGLExtensions -lQt5PacketProtocol -lQt5PlatformSupport -lQt5Positioning -lQt5PrintSupport -lQt5Purchasing -lQt5Qml -lQt5QmlDebug -lQt5QmlDevTools -lQt5Quick -lQt5QuickControls2 -lQt5QuickParticles -lQt5QuickTemplates2 -lQt5QuickTest -lQt5QuickWidgets -lQt5Script -lQt5ScriptTools -lQt5Scxml -lQt5Sensors -lQt5SerialBus -lQt5SerialPort -lQt5Sql -lQt5Svg -lQt5Test -lQt5UiTools -lQt5WebChannel -lQt5WebSockets -lQt5Widgets -lQt5WinExtras -lQt5Xml -lQt5XmlPatterns -lqtfreetype -lqtmain -lmingw32 -m32
PS C:\workspace\co> xmake run
hello xmake
PS C:\workspace\co>

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 错误信息

如果可能，请尽量附加程序运行过程中的错误输出信息。

> 如果是xmake相关编译问题，请加上`-v -D`参数运行，并给出详细编译输出信息。

### 相关环境

请提供编译和运行环境信息，例如：xmake版本、操作系统等

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by conlay-cn** [comment]
试着去掉三个库-lQt5AxBase -lQt5AxContainer -lQt5AxServer，再去掉-Wl,--out-implib,build\\mingw\\i386\\release\\sh.lib条件
用提取的命令行编译，通过
PS C:\workspace\sh> C:\Qt\Qt5.7.0\Tools\mingw530_32\bin\g++ -o build\mingw\i386\release\sh.dll build\.objs\sh\mi> C:\Qt\Qt5.7.0\Tools\mingw530_32\bin\g++ -o build\mingw\i386\release\sh.dll build\.objs\sh\mingw\i386\release\src\demo.cpp.obj -LC:\\Qt\\Qt5.7.0\\5.7\\mingw53_32\\lib -s -lQt5Core -lQt53DCore -lQt53DExtras -lQt53DInput -lQt53DLogic -lQt53DQuick -lQt53DQuickExtras -lQt53DQuickInput -lQt53DQuickRender -lQt53DRender -lQt5Bluetooth -lQt5Bootstrap -lQt5CLucene -lQt5Concurrent -lQt5DBus -lQt5Designer -lQt5DesignerComponents -lQt5Gui -lQt5Help -lQt5Location -lQt5Multimedia -lQt5MultimediaQuick_p -lQt5MultimediaWidgets -lQt5Network -lQt5Nfc -lQt5OpenGL -lQt5OpenGLExtensions -lQt5PacketProtocol -lQt5PlatformSupport -lQt5Positioning -lQt5PrintSupport -lQt5Purchasing -lQt5Qml -lQt5QmlDebug -lQt5QmlDevTools -lQt5Quick -lQt5QuickControls2 -lQt5QuickParticles -lQt5QuickTemplates2 -lQt5QuickTest -lQt5QuickWidgets -lQt5Script -lQt5ScriptTools -lQt5Scxml -lQt5Sensors -lQt5SerialBus -lQt5SerialPort -lQt5Sql -lQt5Svg -lQt5Test -lQt5UiTools -lQt5WebChannel -lQt5WebSockets -lQt5Widgets -lQt5WinExtras -lQt5Xml -lQt5XmlPatterns -lqtfreetype -lqtmain -lmingw32 -shared -m32                                            PS C:\workspace\sh> ls .\build\mingw\i386\release\


    目录: C:\workspace\sh\build\mingw\i386\release


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        2020/3/14     14:45          15872 sh.dll
-a----        2020/3/14     14:32           2034 sh.lib


PS C:\workspace\sh>

**Comment by waruqi** [comment]
我暂时没qt环境，磁盘空间不够，等回头有时间了给你看下。

**Comment by conlay-cn** [comment]
好的
我创建一个百度网盘链接，可以下载Qt5.7 mingw。有需要可以下载。
链接：https://pan.baidu.com/s/163DiQz3pR2I8oVctw6cbvg 
提取码：i4lr
感谢

**Comment by conlay-cn** [comment]
又做了一个测试，在xmake/rules/qt/load.lua中
注释
--    target:add("syslinks", _find_static_links(qt.linkdirs, is_plat("windows") and "qt*.lib" or "libqt*.a"))
编译通过。
这个target:add说明是如果找的到，就将一些静态第三方库链接进来，但涉及的库太多了，也许根本不需要。
    -- add some static third-party links if exists

注释target:add，链接的库少多了，也能编译通过了，输出如下：
PS C:\workspace\sh> xmake f -c -p mingw -a i386 --qt=C:\Qt\Qt5.7.0 --sdk=C:\Qt\Qt5.7.0\Tools\mingw530_32
checking for the mingw directory ... C:\Qt\Qt5.7.0\Tools\mingw530_32
checking for the Qt SDK directory ... C:\Qt\Qt5.7.0\5.7\mingw53_32
checking for the Qt SDK version ... 5.7.0
PS C:\workspace\sh> xmake -v -D
configure
{
    arch = i386
    ccache = true
    clean = true
    cross =
    host = windows
    mode = release
    ndk_stdcxx = true
    plat = mingw
    sdk = C:\Qt\Qt5.7.0\Tools\mingw530_32
    mingw = C:\Qt\Qt5.7.0\Tools\mingw530_32
    kind = static
    buildir = build
    bin = C:\Qt\Qt5.7.0\Tools\mingw530_32\bin
    qt_sdkver = 5.7.0
    qt = C:\Qt\Qt5.7.0
}
checking for the gcc ... C:\Qt\Qt5.7.0\Tools\mingw530_32\bin\gcc
checking for the c++ compiler (cxx) ... gcc
checking for the C:\Qt\Qt5.7.0\Tools\mingw530_32\bin\gcc ... ok
checking for the flags (-O3) ... ok
> gcc "-O3"
checking for the flags (-fPIC) ... ok
> gcc "-fPIC"
checking for the g++ ... C:\Qt\Qt5.7.0\Tools\mingw530_32\bin\g++
checking for the shared library linker (sh) ... g++
[100%]: linking.release sh.dll
C:\\Qt\\Qt5.7.0\\Tools\\mingw530_32\\bin\\g++ -o build\\mingw\\i386\\release\\sh.dll build\\.objs\\sh\\mingw\\i386\\release\\src\\demo.cpp.obj -LC:\\\\Qt\\\\Qt5.7.0\\\\5.7\\\\mingw53_32\\\\lib -s -lQt5Gui -lQt5Core -lmingw32 -shared -m32 -Wl,--out-implib,build\\\\mingw\\\\i386\\\\release\\\\sh.lib

这个还是请斟酌下怎么处理？

**Comment by waruqi** [comment]
我回头看下

**Comment by waruqi** [comment]
> -- target:add("syslinks", _find_static_links(qt.linkdirs, is_plat("windows") and "qt*.lib" or "libqt*.a"))


这块我处理过了，应该可以了，你更新下 dev版本试试，xmake update dev

这个地方主要是自动追加一些 libqtfreetype.a libqtpng.a等qt frameworks依赖的第三方库的，但是由于win上文件路径大小写不敏感，导致现有 libqt*.a的匹配模式，会把 libQt5xxx.a 这种qt frameworks库，也给自动追加了。。

我现在做了些处理，排除这些，仅添加 libqtxxx.a这种第三方库，应该就可以了。

另外，我稍微改进了下qt下mingw sdk的路径探测，即使不追加 --sdk=/--mingw=，只要设置了qt路径，就能自动探测到mingw sdk路径。。

简化配置：`xmake f -vD -c -p mingw -a i386 --qt=C:\Qt\5.7.0`

**Comment by conlay-cn** [comment]
更新了，没有问题了，而且比原来更好用。
谢谢。
