### ISSUE TITLE
如何使用sdcc作为cc编译器？

### ISSUE THREAD

**Issue by deeyi2000** [xmake-io/xmake#712]
我希望xmake使用sdcc([http://sdcc.sourceforge.net/](sdcc))作为cc编译器，但是无论如何配置都无法正确构建项目。

我使用以下命令配置xmake
`xmake f -p sdcc -a stm8 --sdk="C:\Program Files\SDCC" --cc="gcc@sdcc" --cflags="-mstm8 -c" --ld="gcc@sdld" --ldflags="-f stm8"`
xmake不能良好的识别sdcc编译器，并且即使手动指定调用方法(--cc="gcc@sdcc" --ld="gcc@sdld"),也不能传递正确的参数。

在cmake中只需设置参数 -DCMAKE_SYSTEM_NAME=Generic -DCMAKE_C_COMPILER=sdcc，即可正常调用(如：[https://blog.csdn.net/xy1157/article/details/93317868](sdcc))，但是xmake中我没有找到近似的方法实现。

**Comment by waruqi** [comment]
那得看sdcc的参数flags是否跟gcc兼容了，如果完全兼容，是可以通过 gcc@sdcc 这么搞，如果差异大，就要xmake里面单独做适配了。。

回头有时间我先看下吧，加上支持也是可以的。

**Comment by deeyi2000** [comment]
如何适配?我自己可以完成吗？

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/tree/master/xmake/modules/detect/tools 下面加上 find_sdcc.lua 等对应工具的查找匹配，以及has_flags的自动检测

https://github.com/xmake-io/xmake/tree/master/xmake/modules/core/tools 这里面加上sdcc的各种flags处理和编译link

如果你有兴趣 可以研究下

**Comment by waruqi** [comment]
我dev分支新增了sdcc编译平台，以及编译器支持，你更新到dev试试: `xmake update dev`

我也简化了下配置，不用配置这么多：

```console
xmake f -p sdcc -c --sdk=~/Downloads/sdcc-4.0.0
```

指定sdk就可以了，如果是windows上，还会自动读取注册表探测，所以--sdk也可以省略

如果要切port可以通过，`-a mcs51`或者`--arch stm8`来切，会自动追加-mstm8 flags，默认不设置就是stm8的。。

```console
ruki-2:testaa ruki$ xmake f -p sdcc -c --sdk=~/Downloads/sdcc-4.0.0
ruki-2:testaa ruki$ xmake -r -v
configure
{
    arch = stm8
    ccache = true
    xcode = /Applications/Xcode.app
    mode = release
    ndk_stdcxx = true
    host = macosx
    sdk = ~/Downloads/sdcc-4.0.0
    plat = sdcc
    kind = static
    buildir = build
    clean = true
    bin = /Users/ruki/Downloads/sdcc-4.0.0/bin
    theme = default
}
checking for the sdar ... /Users/ruki/Downloads/sdcc-4.0.0/bin/sdar
checking for the static library archiver (ar) ... sdar
checking for the sdcc ... /Users/ruki/Downloads/sdcc-4.0.0/bin/sdcc
checking for the c compiler (cc) ... sdcc
checking for the c compiler (cc) ... sdcc
checking for the /Users/ruki/Downloads/sdcc-4.0.0/bin/sdcc ... ok
checking for the flags (--opt-code-speed) ... ok
checking for the ccache ... /usr/local/bin/ccache
[ 25%]: ccache compiling.release src/interface.c
/Users/ruki/Downloads/sdcc-4.0.0/bin/sdcc -c --opt-code-speed -mstm8 -o build/.objs/testaa/sdcc/stm8/release/src/interface.c.rel src/interface.c
[ 37%]: ccache compiling.release src/test.c
/Users/ruki/Downloads/sdcc-4.0.0/bin/sdcc -c --opt-code-speed -mstm8 -o build/.objs/testaa_demo/sdcc/stm8/release/src/test.c.rel src/test.c
src/test.c:12: warning 85: in function main unreferenced function argument : 'argc'
src/test.c:12: warning 85: in function main unreferenced function argument : 'argv'
[ 50%]: archiving.release testaa.lib
/Users/ruki/Downloads/sdcc-4.0.0/bin/sdar -cr build/sdcc/stm8/release/testaa.lib build/.objs/testaa/sdcc/stm8/release/src/interface.c.rel
checking for the linker (ld) ... sdcc
[ 87%]: linking.release testaa_demo.bin
/Users/ruki/Downloads/sdcc-4.0.0/bin/sdcc -o build/sdcc/stm8/release/testaa_demo.bin build/.objs/testaa_demo/sdcc/stm8/release/src/test.c.rel -Lbuild/sdcc/stm8/release -ltestaa -mstm8
[100%]: build ok!
```

对于sdcc这块我还不是特别了解，目前虽然跑通编译，但是否能用，你先试试吧，我也还不清楚.ihx 这个格式干啥的，什么时候回去用，所以暂时没启用--out-fmt-ihx 

如果要进一步改进，请简单描述下 .hex/.ihx/.bin什么关系已经大体的构建流程，我才能进一步尝试改进构建过程。。

或者你也可以自己提个pr帮我改进下platforms/sdcc相关代码。

**Comment by deeyi2000** [comment]
好的，我测试一下，非常感谢！

**Comment by waruqi** [comment]
可以了么

**Comment by waruqi** [comment]
没问题 我这里先close了，会有有问题 再开好了

**Comment by waruqi** [comment]
我重构了toolchain的支持，可以通过以下方式选择sdcc工具链来编译：

```console
xmake f -p cross -a stm8 --toolchain=sdcc --sdk=/xxxx
xmake
```

请先更新到dev版本，xmake update dev
