### ISSUE TITLE
關於#589合併後編譯出錯

### ISSUE THREAD

**Issue by orzuk-lmj** [xmake-io/xmake#713]
### 描述问题
這篇主要是相關於 #589 合併後的問題回報，因為issues已經關閉了所以新開一條。
抓了最新的 8dfb6e866604516ecff093404cec9182a1c3d6b1 之後，我現有的一個正常專案，更新後出錯了。

我懷疑是併行link有問題

### 错误信息
主要錯誤訊息是類似找不到lib檔案 : 
發生的平台是 windows msvc/ mingw / android  都有同類的link錯誤
```
[ 97%]: linking.debug icuin57.dll
C:\\mingw-builds\\i686-7.3.0-release-posix-dwarf-rt_v5-rev0\\mingw32\\bin\\g++ -o ..\\_build
(參數很長，先略過，

error: C:/mingw-builds/i686-7.3.0-release-posix-dwarf-rt_v5-rev0/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -licuuc57
collect2.exe: error: ld returned 1 exit status
```

### 相关环境
專案根目錄中有一個 xmake.lua 內容大致上是
``` lua
-- project and version
set_xmakever("2.2.9")
set_project("icu")
set_version("57.1")
-- setup utility path
......
-- 子目錄中還有 xmake 內容是單一的 target
includes("src/stubdata")
includes("src/common")
includes("src/i18n")
includes("src/io")
includes("src/layout")
includes("src/layoutex")
```

各別的target 大致上會按照上面的目錄順序設置倚賴
``` lua
target("stubdata")
    -- add rules  (這裡的規則主要是放一些我整理好方便使用的工具，理論上應該不影響)
    add_rules("gk.common")
    add_rules("gk.mode")
    add_rules("gk.install")

    -- set kind
    set_kind("shared")
    
    -- add files
    add_files("*.c")
    set_basename("icudt57")
    
    -- add include search directories
    add_includedirs("../../inc", {public = true})
```

``` lua
target("common")
    -- add deps
    add_deps("stubdata")

    -- add rules (同上，略過... )
    -- set kind and name
    set_kind("shared")
    set_basename("icuuc57")

    -- add files
    add_files("*.c", "*.cpp")
    add_headerfiles("*.h")
    add_headerfiles("../../inc/**.h")

    -- add include search directories
    add_includedirs(".", {public = true})

    -- default definitions
    add_defines("U_ATTRIBUTE_DEPRECATED=")
    add_defines("U_COMMON_IMPLEMENTATION")

    on_load(function (target)
        -- check for shared library definitions
        local targetkind = target:targetkind()
        if targetkind == "shared" then
            if is_plat("windows") or is_plat("mingw") then
                target:add("links", "Advapi32")
            elseif is_plat("linux") then
                target:add("links", "dl")
            end
        end

        -- disable warning
        if is_plat("windows") then
            -- '=': conversion from '__int64' to 'int32_t', possible loss of data
            target:add("cxflags", "/wd4244")
            -- 'initializing': conversion from 'size_t' to 'int32_t', possible loss of data
            target:add("cxflags", "/wd4267")
            -- 'operator new': non-member operator new or delete functions may not be declared inline
            target:add("cxflags", "/wd4595")
            -- 'GetVersionExW': was declared deprecated
            target:add("cxflags", "/wd4996")
        elseif is_plat("linux") then
            target:add("cxflags", "-Wno-stringop-truncation")
            target:add("cxflags", "-Wno-stringop-overflow")
        end
    end)
```

``` lua
target("i18n")
    -- add deps
    add_deps("common")

    -- add rules (同上，略過... )
    -- set kind and name
    set_kind("shared")
    set_basename("icuin57")

    -- 底下略，幾乎都差不多
```

我反覆測試後，發現如果只留下前三個  (不要同時處理 link common 的話)  就可以正確
順帶一提，我的target名字和建立後的lib/dll名字設置不同。

**Comment by waruqi** [comment]
你试试 xmake -j1 有问题么。。icuuc57.lib/icuuc57.dll这个target的依赖关系是怎样的，哪些target会用到，实际报错的是在哪个target里面？

**Comment by orzuk-lmj** [comment]
簡單來說，注意一下倚賴順序大致上是
``` lua
includes("src/stubdata") -- 內容會建立 target stubdata (base改名為icudt57)，沒有倚賴
includes("src/common")  -- 內容會建立 target common (base改名為icuuc57)，倚賴stubdata 
includes("src/i18n")  -- 內容會建立 target i18n (base改名為icuin57)，倚賴common
includes("src/io")  -- 內容會建立 target io (base改名為icuio57)，倚賴common 和 i18n
includes("src/layout")  -- 內容會建立 target  layout (base改名為 icule57)，倚賴common
includes("src/layoutex")  -- 內容會建立 target layoutex (base改名為 iculx57)，倚賴common 和 layout
```

**Comment by waruqi** [comment]
就是说 link icuin57的时候，找不到依赖的 common target的 icuuc57.lib?

icuin57 和 common 之间确定加了 add_deps了对吧。。能给下 完整的 xmake -r 构建输出列表么，我要看下实际的执行顺序。。

另外xmake -j1 是ok的么？

**Comment by orzuk-lmj** [comment]
>就是说 link icuin57的时候，找不到依赖的 common target的 icuuc57.lib?

找不到

>icuin57 和 common 之间确定加了 add_deps了对吧。。

確定加了add_deps ，其他的倚賴也用 add_deps 加的

> 能给下 完整的 xmake -r 构建输出列表么，我要看下实际的执行顺序。。

參見附檔
[RLOG.txt](https://github.com/xmake-io/xmake/files/4336800/RLOG.txt)

> 另外xmake -j1 是ok的么？

指令 xmake build -j1  加上限制後，還是一樣的錯誤訊息

**Comment by waruqi** [comment]
> [ 97%]: linking.debug icule57.dll
> [ 97%]: linking.debug icuin57.dll
> [ 97%]: linking.debug icudt57.dll
> error: [@encode(error)]: {stdout="LINK : fatal error LNK1104: cannot open file 'icuuc57.lib'\
> 

有点怪，icuuc57这个都还没执行link么。。按理加了 add_deps，那么icuuc57 应该会优先执行link，如果是并行问题，应该xmake -j1 强制串行后，就不会有问题。。

感觉还是依赖分析上有问题。你加上xmake -r --dry-run空跑下，再给个输出，我看下 icuuc57到底什么时候才会去link

**Comment by orzuk-lmj** [comment]
> 感觉还是依赖分析上有问题。你加上xmake -r --dry-run空跑下，再给个输出，我看下 icuuc57到底什么时候才会去link

[RLOG2.txt](https://github.com/xmake-io/xmake/files/4336949/RLOG2.txt)

**Comment by waruqi** [comment]
我更新了下dev，增加两个dump诊断，你这帮忙执行下，给我看下输出：

```console
xmake update -s dev
xmake l private.diagnosis.dump_targets
xmake l private.diagnosis.dump_batchjobs
```

**Comment by orzuk-lmj** [comment]
> ```
> xmake l private.diagnosis.dump_targets
> xmake l private.diagnosis.dump_batchjobs
> ```

[dump_targets.txt](https://github.com/xmake-io/xmake/files/4337229/dump_targets.txt)

[dump_batchjobs.txt](https://github.com/xmake-io/xmake/files/4337230/dump_batchjobs.txt)

**Comment by waruqi** [comment]
xmake l private.diagnosis.dump_batchjobs 我刚写错了，应该是 

```console
xmake l private.diagnosis.dump_buildjobs
```

能再给个么

**Comment by orzuk-lmj** [comment]
> ```
> dump_buildjobs
> ```

[dump_buildjobs.txt](https://github.com/xmake-io/xmake/files/4337541/dump_buildjobs.txt)

**Comment by waruqi** [comment]
收到 等晚上有时间我分析下

**Comment by waruqi** [comment]
初步看了下，目前的deps展开到batchjobs是有点问题，这块我需要花点时间完善下，可能要多搞点test case做下覆盖测试才行，大体原因知道了。。你先回退到之前的版本吧。。等我搞完你在试试

目前只影响 a, b, c, d 依赖同一个common的场景

**Comment by waruqi** [comment]
我处理过了，这边测试case目前过了各种deps结构，你再更新下dev版本试试

**Comment by waruqi** [comment]
@orzuk-lmj 可以了么？

**Comment by orzuk-lmj** [comment]
> @orzuk-lmj 可以了么？

再等等下，我把自動編譯全跑完一次。 。。

**Comment by orzuk-lmj** [comment]
我這裡能測試的平台，都OK了，感謝修正!

**Comment by waruqi** [comment]
好的，回头有时间可以帮忙对比下跟2.3.1正式版的编译速度，看看有没有提升
