### ISSUE TITLE
windows下install动态库能否将*.lib同时安装

### ISSUE THREAD

**Issue by conlay-cn** [xmake-io/xmake#714]
windows下shared动态库install时，安装了include头文件和.dll动态库，但配套.lib没有同时安装。
通过add_installfiles安装的话因为无法获得编译目录无法进行。
可以通过after_install安装.lib，但每个动态库工程都要添加，略显麻烦。
其实在windows下生成动态库，虽然有.dll就可以运行了，但基于动态库的开发要链接.lib，既然include都install了，还请将install规则稍微改进一下，将.lib一并加入到install中好了。

**Comment by waruqi** [comment]
恩 这个我之后加下

**Comment by waruqi** [comment]
这个我dev加了，但是没测试过，你先试试吧，xmake update -s dev

**Comment by conlay-cn** [comment]
OK，很好。
用的越来越顺手。
辛苦了，深夜更新。
