### ISSUE TITLE
执行 xmake update dev 后第一次总会出现乱码，在执行一次就好了

### ISSUE THREAD

**Issue by linuxsky** [xmake-io/xmake#715]
⇒  xmake update dev
update version dev from official source ..
  => download https://gitee.com/tboox/xmake.git .. ok
  => install to ~/.local/bin .. ok
xmake v2.3.1+202003171447, A cross-platform build utility based on Lua
Copyright (C) 2015-2020 Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, tboox.org

    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor

H��L��L��1��ha�H�L�dM�������H��H�������`H�5�ntax error near unexpected token `��\��H,�H��H1��H,�f.�HC�����H�lH��L����L��H��L��L����Hc�H���`�H�H�H;�$�����H�������k`H�5�
�H����_�H��H�H;�$�u��H�Ĉ[A\A]A^A_]�����_H�5�
�H���^�[�H�51H��A�1��X)H��t�H��H���a�[ÐAWAVSH����L�?I��tI��tI��u�����SH��tFH����JH��t7H��tyH��uPH�5�H�m�A�1���)H��us�)1�[�H�5yH�B�A�1��)H��uHH����]H�5!
                                                                     ������I���E1����H��� H��tfH��L�0H�@H�I�G�H��w#H��J�D��H�8��
                                                                                                                                ����
                                                                                                                                    ��tI��L�{ H�C(	H�{0�s:H��H��h�g:�1�HH�p�{;H�;H�5DH����H���?CH�H���UH����H�;H�5�t$Ð��AWAVSH�� H�
�������rH�;H���H��
L���^\H�;H�    L�5
������MrH�;H��ts1�1����
�������q�MQH���9I��W�)�$)�$�)�$�)�$�)�$�)�$�)�$�)�$�)�$�)D$p)D$`'
H��L��L��1��ha�H�L�dM�������H��H�������`H�5�H��L��L����Hc�H���`�H�H�H;�$�����H�������k`H�5�5�
�H����_�H��H�H;�$�u��H�Ĉ[A\A]A^A_]�����_H�5�
�H���^�[�H�51H��A�1��X)H��t�H��H���a�[ÐAWAVSH����L�?I��tI��tI��u�����SH��tFH����JH��t7H��tyH��uPH�5�H�m�A�1���)H��us�)1�[�H�5yH�B�A�1��)H��uHH����]H�5!
                                                                     ������I���E1����H��� H��tfH��L�0H�@H�I�G�H��w#H��J�D��H�8��
                                                                                                                                ����
                                                                                                                                    ��tI��L�{ H�C(	H�{0�s:H��H��h�g:�1�HH�p�{;H�;H�5DH����H���?CH�H���UH����H�;H�5�t$Ð��AWAVSH�� H�

**Comment by waruqi** [comment]
你这什么系统？什么arch?

**Comment by linuxsky** [comment]
> ⇒ xmake update dev
> update version dev from official source ..
> => download https://gitee.com/tboox/xmake.git .. ok
> => install to ~/.local/bin .. ok
> xmake v2.3.1+202003171447, A cross-platform build utility based on Lua
> Copyright (C) 2015-2020 Ruki Wang, tboox.org, xmake.io
> _
> __ ___ __ __ __ _| | ______ \ / / | / |/ _ | |/ / __ > < | __/ | /_| | < ___/ /_/__|_| |_|__ |_|_____|
> by ruki, tboox.org
> 
> ```
> 👉  Manual: https://xmake.io/#/getting_started
> 🙏  Donate: https://xmake.io/#/sponsor
> ```
> 
> H��L��L��1��ha�H�L�dM�������H��H�������`H�5�ntax error near unexpected token `��\��H,�H��H1��H,�f.�HC�����H�lH��L����L��H��L��L����Hc�H���`�H�H�H;�$�����H�������k`H�5�
> �H����_�H��H�H;�$�u��H�Ĉ[A\A]A^A_]�����_H�5�
> �H����^�[�H�51H��A�1��X)H��t�H��H���a�[ÐAWAVSH����L�?I��tI��tI��u�����SH��tFH����JH��t7H��tyH��uPH�5�H�m�A�1���)H��us�)1�[�H�5yH�B�A�1��)H��uHH����]H�5!
> ������I���E1����H��� H��tfH��L�0H�@h�I�G�H��w#H��J�D��H�8��
> ����
> ��tI��L�{ H�C( H�{0�s:H��H��h�g:�1�HH�p�{;H�;H�5DH����H���?CH�H���UH����H�;H�5�t$Ð��AWAVSH�� H�
> �������rH�;H���H��
> L���^\H�;H� L�5
> ������MrH�;H��ts1�1����
> �������q�MQH���9I��W�)�$)�$�)�$�)�$�)�$�)�$�)�$�)�$�)�$�)D$p)D$`' H��L��L��1��ha�H�L�dM�������H��H�������`H�5�H��L��L����Hc�H���`�H�H�H;�$�����H�������k`H�5�5�
> �H����_�H��H�H;�$�u��H�Ĉ[A\A]A^A_]�����_H�5�
> �H����^�[�H�51H��A�1��X)H��t�H��H���a�[ÐAWAVSH����L�?I��tI��tI��u�����SH��tFH����JH��t7H��tyH��uPH�5�H�m�A�1���)H��us�)1�[�H�5yH�B�A�1��)H��uHH����]H�5!
> ������I���E1����H��� H��tfH��L�0H�@h�I�G�H��w#H��J�D��H�8��
> ����
> ��tI��L�{ H�C( H�{0�s:H��H��h�g:�1�HH�p�{;H�;H�5DH����H���?CH�H���UH����H�;H�5�t$Ð��AWAVSH�� H�



> 你这什么系统？什么arch?
昨天使用的是 Ubuntu 16.04 出了一次，全新安装xmake 后执行 xmake update dev。
今天使用的macos 最新版本系统， 也是同样的操作，第二次执行后 正常
⇒  xmake update dev
update version dev from official source ..
  => download https://gitee.com/tboox/xmake.git .. ok
  => install to ~/.local/bin .. ok

**Comment by waruqi** [comment]
2.3.1那个线上版本是有这问题的，我之前修复了，所以你更新到dev后 第二次就没事了。。只要dev上没事就行，回头等下个版本一发就覆盖过去了

**Comment by linuxsky** [comment]
> 2.3.1那个线上版本是有这问题的，我之前修复了，所以你更新到dev后 第二次就没事了。。只要dev上没事就行，回头等下个版本一发就覆盖过去了

收到
