### ISSUE TITLE
includes lua  时，会意外影响到内部设定package的add_includedirs

### ISSUE THREAD

**Issue by codehz** [xmake-io/xmake#717]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题

具体来说，我想把定义包描述的内容放在某个子目录的lua中
然后在主lua中include

大体上是这样
includes ("packages/*.lua")
然后里面写
package ("funchook")
  set_homepage ("https://github.com/kubo/funchook")
  set_description ("Funchook - an API Hook Library")

  set_urls ("https://github.com/kubo/funchook.git")

  add_deps ("cmake")
  add_includedirs ("include")

  add_links ("funckhook_dll")

  on_install (function (package)
    import("package.tools.cmake").install (package)
  end)
package_end ()
接着在使用的时候，就会发现 include 的路径被意外改变，就像下面这个一样C:\Users\*\AppData\Roaming\.xmake\packages\f\funchook\master\aa7fbd80abda4d1a97f445168f6f3c1d\packages\include

### 期待的结果

正常解析子目录下的package里的add_includedirs

### 错误信息

cl.exe -c -std:c++latest -IC:\\\\Users\\\\CodeHz\\\\AppData\\\\Roaming\\\\.xmake\\\\packages\\\\f\\\\funchook\\\\master\\\\c6d35553172d4eef836d09b206be23c8\\\\packages\\\\include -nologo -Fobuild\\.objs\\ModLoader\\windows\\x64\\release\\ModLoader\\HealthCheck.cpp.obj ModLoader\\HealthCheck.cpp

### 相关环境

xmake v2.3.1+202003181541
windows 10 x64

**Comment by waruqi** [comment]
https://gist.github.com/codehz/6968a90623a5c3bb85bd1e51efbd16fa 复现代码

**Comment by waruqi** [comment]
mac/linux有这问题么？ 我win上require --info funchook_test看了下，路径正常的么。。你这个demo

**Comment by waruqi** [comment]
哦 我复现出来了 回头查下

**Comment by waruqi** [comment]
这个也不算是bug，add_includedirs 等所有api都是根据 当前xmake.lua所在目前来加的路径，通过includes引入所以会有影响。。因为你includes的时候加了个 xxxx子目录，所以会自动计算出相对于projectdir根目录的路径来。

如果要在当前工程定义package和引入，建议走 add_repositories("benchbox-repo repo")，这样projectdir/repo目录下是独立的 仓库目录 不受includes干扰的。。

具体例子参考：https://github.com/tboox/benchbox/blob/master/xmake.lua

**Comment by waruqi** [comment]
https://xmake.io/#/zh-cn/package/remote_package?id=%e6%b7%bb%e5%8a%a0%e5%8c%85%e5%88%b0%e4%bb%93%e5%ba%93 

相关文档说明

**Comment by codehz** [comment]
（恩，这是好一个方法，不过我觉得package的这个设计还是bug，因为正常角度思考，这个addincludedirs应该是相对于package的安装目录

**Comment by waruqi** [comment]
add_includedirs 目前统一的语义 都是基于 当前xmake.lua 的相对路径，以及 projectdir 。。package里面我只是复用了而已。。建议先走 add_repositories 吧

**Comment by waruqi** [comment]
这块我独立开了 之前的方式应该也没问题了 你更新下试试 xmake update -s github:xmake-io/xmake#dev

其他镜像我还没时间同步，先直接从github更新吧

要验证请先 xmake require --uninstall xxx 卸载下之前的包 

然后执行 xmake f -c 清下cache重装下就行了

**Comment by codehz** [comment]
看起来dev已经解决了，不过我已经打算用repo的方案了

**Comment by waruqi** [comment]
恩 repo那个也是推荐方案，通常只有临时引入个pkg用用，才会直接在工程xmake.lua里面直接定义package
