### ISSUE TITLE
当package具有多个不同的url时，下载缓存有一定概率失效

### ISSUE THREAD

**Issue by codehz** [xmake-io/xmake#718]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题

例子是boost，提供了两个url作为备选，这就导致有一定概率出现重复下载的问题

### 期待的结果

允许强制指定一个下载文件名，以规避这个问题

### 错误信息

（无）

### 相关环境

xmake v2.3.1+202003181541

**Comment by waruqi** [comment]
我修复了，内部统一处理了，应该不会有这个问题了，你再试试，dev版本

**Comment by waruqi** [comment]
这个应该可以了，我先close了
