### ISSUE TITLE
package 安装时中断，将导致无法重新安装

### ISSUE THREAD

**Issue by codehz** [xmake-io/xmake#719]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题

具体来说，就是安装一半ctrl+C结束程序会导致必须人工介入删除cache才能重新运行安装命令

### 期待的结果

正确处理这个情况，重新安装时不会报错

### 错误信息

```
7z x -y boost_1_72_0.tar.bz2 -oC:\\Users\\CodeHz\\AppData\\Local\\Temp\\.xmake\\200320\\_483786805AE04530899EA4E596A0BFA0.tar

7-Zip 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30

Scanning the drive for archives:
1 file, 106907358 bytes (102 MiB)

Extracting archive: boost_1_72_0.tar.bz2
--
Path = boost_1_72_0.tar.bz2
Type = bzip2

Everything is Ok

Size:       688230400
Compressed: 106907358
7z x -y C:\\Users\\CodeHz\\AppData\\Local\\Temp\\.xmake\\200320\\_483786805AE04530899EA4E596A0BFA0.tar\\boost_1_72_0.tar -osource.tmp

7-Zip 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30

Scanning the drive for archives:
1 file, 688230400 bytes (657 MiB)

Extracting archive: C:\Users\CodeHz\AppData\Local\Temp\.xmake\200320\_483786805AE04530899EA4E596A0BFA0.tar\boost_1_72_0.tar
--
Path = C:\Users\CodeHz\AppData\Local\Temp\.xmake\200320\_483786805AE04530899EA4E596A0BFA0.tar\boost_1_72_0.tar
Type = tar
Physical Size = 688230400
Headers Size = 37637120
Code Page = UTF-8

Everything is Ok

Folders: 6043
Files: 64810
Size:       633756333
Compressed: 688230400
error: cannot remove directory source Unknown
  => download *** .. failed
error: download failed!
```

### 相关环境

xmake v2.3.1+202003181541

### 其他信息

除了 source 之外，source.tmp也会移除失败

**Comment by waruqi** [comment]
初步看了下，包安装本身是有回滚机制的，你这边移除失败，主要还是由于crtl-c后，内部安装进程没有立即完全退出，继续占用source等目录

导致下次安装触发回滚，尝试删除之前的source等目录，由于还在占用所以移除失败了。。

**Comment by waruqi** [comment]
测试了下应该是boost里面编译用到了 .bat ，通过 bat开启的进程，通过 ctrl+c 没法直接立马退出，还是会在后台继续执行。顶多会提示：Terminate batch job (Y/N)

**Comment by waruqi** [comment]
http://kingsamchen.github.io/2017/07/24/terminate-child-processes-on-close-using-job-object/

**Comment by waruqi** [comment]
我重构了下进程执行这块，目前windows不管如何退出都会自动退掉所有子进程，除非`process.openv(.., {detach = true})`开启的进程，才会在退出后保留

linux/mac下ctrl+c处理也能正常退干净，对于正常程序退出，部分process没有close，导致的残留子进程，目前是通过直接挨个kill去解决（不过还不能完全kill掉子进程的子进程，暂时没找到比较完美的方案，先就这样吧，回头有时间再看看）

**Comment by waruqi** [comment]
这里没问题 我先close了
