### ISSUE TITLE
package add_deps 处理问题

### ISSUE THREAD

**Issue by codehz** [xmake-io/xmake#722]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题

在一个package里添加一个不存在的deps，即可导致cli停止运行（不报错 -v -D 也没有输出
add_deps("testNOTEXISTS")
并且如果此时用ctrl+c结束程序，再重新运行的时候，xmake会假装这个包已经安装完成，然后直接跳过安装步骤（

### 期待的结果

在添加了不存在的deps后能有机制报错，以及在强制结束后能正确清理，而不是假装装好了

### 错误信息

（直接卡住没了）

### 相关环境

xmake v2.3.1+202003181541
os: windows 10 x64 vs2019

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by waruqi** [comment]
我这我修复了，是因为无效的deps，默认作为system包还是被加载了导致，我稍微处理了下，应该可以了。xmake update -s dev

**Comment by codehz** [comment]
关于强制结束后缓存认为安装完成的问题我觉得也需要解决一下（

**Comment by waruqi** [comment]
> 关于强制结束后缓存认为安装完成的问题我觉得也需要解决一下（

这是另外一个问题了，如果觉得是bug，那就新开个issues吧
