### ISSUE TITLE
xmake run中添加执行多个target

### ISSUE THREAD

**Issue by conlay-cn** [xmake-io/xmake#723]
### 你在什么场景下需要该功能？

在build后，用xmake run只能在运行全部target或指定某一个taget中做出选择。
在一个项目中可能有多个target，可能有一个主程序target，还有很多是单元测试。
可能主程序target是一个守护进程，不方便一起run：xmake run --all。
希望在xmake run中可以指定多个target依次运行，
最好能有通配项，如xmake run test*，一次运行匹配target。
这样可以一次运行所有测试。

### 描述可能的解决方案

在xmake run中设置多个target，
最好可以通配，如xmake run test*

### 描述你认为的候选方案

也可以在xmake.lua中设置test target，
这个是否已实现？请指点。

### 其他信息

无

**Comment by waruqi** [comment]
这种自己加个task就好了，也没几行代码

```lua

task("tests")
    set_menu {usage = "xmake tests [options]" , description = "Hello xmake!", options = {}}
    on_run(function ()
        import("core.project.project")
        for _, target in pairs(project.targets()) do
            local targetname = target:name()
            if targetname:find("test.*") then
                os.exec("xmake run %s", targetname)
            end
        end
    end)
```

然后运行 

```console
xmake tests
```

就可以执行所有tests了，如果test也想自动根据xxx_test.cc适配扩展Target，可以参考：https://github.com/idealvin/co/blob/master/test/xmake.lua

关于task使用见文档：https://xmake.io/#/plugin/plugin_development

**Comment by waruqi** [comment]
如果觉得task麻烦，你可以定义个phony kind 的target("tests")，然后里面的 on_run 自定义下，参考上面的脚本，就可以通过`xmake run tests` 来实现了，参数的获取 可以导入 `core.base.option`后，通过option.get("arguments")来获取，实现各种参数化tests过滤

```lua
target("tests")
    set_kind("phony")
    on_run(function ()
        import("core.base.option")
        local args = option.get("arguments")
        for _, target in pairs(project.targets()) do
            local targetname = target:name()
            if targetname:find("test.*") then -- 通过args定制化过滤
                os.exec("xmake run %s", targetname)
            end
        end
    end)
```

```console
xmake run tests xxxx
```

**Comment by waruqi** [comment]
这种需求 特定用户相关性太强，如果直接改写内部xmake run逻辑，影响面太广，其他用户也许并不需要，所以自己在自己的工程里面扩展下就好，又没几行代码，想怎么定制就怎么定制。

**Comment by conlay-cn** [comment]
我用了一下定义一个target，如下：
```
target("co")
    set_kind("binary")
    add_files("src/main.cpp", "src/b.cpp")

target("test.unit1")
    set_kind("binary")
    add_files("src/main.cpp", "src/c.cpp")

target("test.unit2")
    set_kind("binary")
    add_files("src/main.cpp")

target("sh")
    set_kind("shared")
    add_files("src/a.cpp")

target("unittest")
    set_kind("phony")
    on_run(function ()
        import("core.base.option")
        local args = option.get("arguments")
        for _, target in pairs(project.targets()) do
            local targetname = target:name()
            print("target name:" .. targetname)
            if targetname:find("test.*") then -- 通过args定制化过滤
                os.exec("xmake run %s", targetname)
            end
        end
    end)
```
编译和单独运行test.unit1、test.unit2都没有问题，但是运行`xmake run unittest`报错：
```
PS C:\workspace\sub> xmake run unittest
error: attempt to index global 'project' (a nil value)
```
好像是project用的不对。

**Comment by conlay-cn** [comment]
用plugin加入一个task，能实现想要的结果。但有一个问题，
按照手册，task可以放入三个地方：xmake/plugins、~/.xmake或者/path/to/some/where，然后add_plugindirs()。
我在win10系统下，只有第一种方式，放入xmake/plugins可以运行`xmake tests`，其他两种方式提示：
```
error: invalid task: tests
```
这样的话用户自定义插件混在内置插件中了，会产生维护上的不便。

**Comment by conlay-cn** [comment]
我觉得运行多目标和定制目标虽说需求并不是很强烈，也能通过其他方法曲线实现。但是要更改xmake run的话，也许可能只需要变更xmake run的内部逻辑，原有用户和外部接口可以保持现状，可以通过增加run选项来实现。即使不是全部用户都需要，但运行多目标毕竟是在单一目标和所有目标之外向用户又提供了一种选择嘛，如果方便实现，何乐而不为呢？

**Comment by waruqi** [comment]
> 我用了一下定义一个target，如下：
> 
> ```
> target("co")
>     set_kind("binary")
>     add_files("src/main.cpp", "src/b.cpp")
> 
> target("test.unit1")
>     set_kind("binary")
>     add_files("src/main.cpp", "src/c.cpp")
> 
> target("test.unit2")
>     set_kind("binary")
>     add_files("src/main.cpp")
> 
> target("sh")
>     set_kind("shared")
>     add_files("src/a.cpp")
> 
> target("unittest")
>     set_kind("phony")
>     on_run(function ()
>         import("core.base.option")
>         local args = option.get("arguments")
>         for _, target in pairs(project.targets()) do
>             local targetname = target:name()
>             print("target name:" .. targetname)
>             if targetname:find("test.*") then -- 通过args定制化过滤
>                 os.exec("xmake run %s", targetname)
>             end
>         end
>     end)
> ```
> 
> 编译和单独运行test.unit1、test.unit2都没有问题，但是运行`xmake run unittest`报错：
> 
> ```
> PS C:\workspace\sub> xmake run unittest
> error: attempt to index global 'project' (a nil value)
> ```
> 
> 好像是project用的不对。

我只是随手敲的project找不到，就自己导入下么。。import("core.project.project")

**Comment by waruqi** [comment]
> 用plugin加入一个task，能实现想要的结果。但有一个问题，
> 按照手册，task可以放入三个地方：xmake/plugins、~/.xmake或者/path/to/some/where，然后add_plugindirs()。
> 我在win10系统下，只有第一种方式，放入xmake/plugins可以运行`xmake tests`，其他两种方式提示：
> 
> ```
> error: invalid task: tests
> ```
> 
> 这样的话用户自定义插件混在内置插件中了，会产生维护上的不便。

我之前没说要加入plugins哈，task可以直接在你的工程 xmake.lua写不就好了，task可以用来写插件，也可以用来写其他扩展task任务。。

**Comment by waruqi** [comment]
> 我觉得运行多目标和定制目标虽说需求并不是很强烈，也能通过其他方法曲线实现。但是要更改xmake run的话，也许可能只需要变更xmake run的内部逻辑，原有用户和外部接口可以保持现状，可以通过增加run选项来实现。即使不是全部用户都需要，但运行多目标毕竟是在单一目标和所有目标之外向用户又提供了一种选择嘛，如果方便实现，何乐而不为呢？

如果每个用户都一种不同的运行方式需求，都要加个参数扩展来支持，那不是会越来越乱，这种外面用户自己只需要不到10行就能解决的问题，为啥非要塞进内置xmake run里面去呢。。外面你想怎么搞就怎么搞，xmake的脚本原本就是完全可扩展的。

> 看到加上了`feature request`，希望那一天早点到来。

我没说要实现这个特性，之前说了，这个用户相关性太强，暂时不考虑实现，只不过你提的类型属于新特性请求，我只是标注下而已。

**Comment by waruqi** [comment]
不过关于tests这块 目前我这遇到的用户需求都比较杂 后期我会汇总下 尝试对tests这块做内置更完善的支持 这也是会考虑的，但不是现在 ，目前你还是先自己处理下吧

**Comment by conlay-cn** [comment]
好的， @waruqi ，对xmake的手册还没有完全看完，更别提贯通了。
但目前用起来很好，赞一个。
从这里讨论还是学到了不少用法和思路。
谢谢你，也谢谢你真诚的态度。

**Comment by waruqi** [comment]
那这里我先close了 你先试试吧 不行再提issues好了
