### ISSUE TITLE
用xmake构建tbox x86时，开启全部功能，无法生成对应x86的库

### ISSUE THREAD

**Issue by xinlengyuer** [xmake-io/xmake#724]
构建参数： xmake f -m release --arch=x86
                    xmake

执行后：
note: try installing these packages (pass -y to skip confirm)?
in xmake-repo:
  -> zlib 1.2.11 (optional)
  -> sqlite3 3.24.0 (optional)
  -> mbedtls 2.13.0 (optional)
  -> pcre2 10.31 (optional)
     or pcre 8.41 (optional)
please input: y (y/n)
y
  => download https://downloads.sourceforge.net/project/libpng/zlib/1.2.11/zlib-1.2.11.tar.gz .. ok
  => install zlib 1.2.11 .. ok
  => download https://github.com/ARMmbed/mbedtls/archive/mbedtls-2.13.0.zip .. ok
  => install mbedtls 2.13.0 .. failed
  => download https://ftp.pcre.org/pub/pcre/pcre2-10.31.zip .. ok
  => install pcre2 10.31 .. failed
  => download https://sqlite.org/2018/sqlite-autoconf-3240000.tar.gz .. failed

查看xmake缓存发现，mbedtls和pcre2 编译时没有生成对应x86的配置，只有x64，导致编译失败，sqlite为下载失败。

还有就是自己手动修改 mbedtls和pcre2 后，再次xmake，没有重新去判断mbedtls和pcre2库是否编译，就直接构建了tbox库。

**Comment by waruqi** [comment]
> 查看xmake缓存发现，mbedtls和pcre2 编译时没有生成对应x86的配置，只有x64，导致编译失败，sqlite为下载失败。

目前仓库里面的大部分还不能同步xmake的arch的，只能构建当前pc arch版本，只有少部分库支持了 arch切换 以及 交叉编译支持，比如zlib等。。暂时不支持切Arch的依赖，先禁用好了，等回头有时间我会看看能否支持上。。

你可以改下 `add_requires("xxx", {configs = {cflags = "-m32", ldflags ="-m32"}})` 强制切到32版本编译他们。。如果还不行，就先禁用对应依赖好了。

> 还有就是自己手动修改 mbedtls和pcre2 后，再次xmake，没有重新去判断mbedtls和pcre2库是否编译，就直接构建了tbox库。

正常的，目前tbox的所有依赖我都配置了optional可选依赖，也就是说安装失败后，就会默认禁用他们，下次编译就直接跳过了，确保整体编译通过。

你可以追加-c清下配置，重新强制安装就行了，`xmake f -c --small=n`

**Comment by waruqi** [comment]
我看了下其它几个库x86应该也是支持的，你可以追加-vD给我看下完整错误输出

xmake -vD

**Comment by waruqi** [comment]
这几个库我支持上i386了。。你再更新到dev试试

```console
xmake update dev
xmake repo -u       <- 同时更新下repo
cd tbox
xmake f -c
xmake
```

**Comment by waruqi** [comment]
可以了么
