### ISSUE TITLE
xmake require --uninstall无法卸载project定义的包

### ISSUE THREAD

**Issue by codehz** [xmake-io/xmake#725]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题

如题，
直接返回找不到本地包

### 期待的结果

能正确卸载本地包

### 错误信息

```
local packages not found!
```

### 相关环境

xmake v2.3.1+202003181541
win10 x64

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by waruqi** [comment]
我用你这 funchook_test那个case测试了下，能够正常uninstall么，并没有复现

```lua
add_requires("funchook_test", {system = false})
```

而且我看了下代码，这块应该能够正常处理project的包的。可否提供个能够复现的demo case给我，我看看。

**Comment by codehz** [comment]
啊，我发现了，原来是我写了 `{ configs = {vs_runtime="MD"}}`
然后cmd使用 `xmake q --extra='{configs={vs_runtime="MD"}}' --uninstall` 是不行的
得 `--extra="{configs={vs_runtime=\"MD\"}}"`
