### ISSUE TITLE
如果把包含在项目中的cmake项目作为依赖加入

### ISSUE THREAD

**Issue by wicast** [xmake-io/xmake#729]
### 描述问题详情
在这样的一个项目结构下，
.
├── main.cpp
├── thrid-party
│   └── cpp-taskflow
│       ├── 3rd-party
│       ├── CMakeLists.txt
│       ├── Cpp-TaskflowConfig.cmake.in
│       ├── LICENSE
│       ├── README.md
│       ├── benchmarks
│       ├── docs
│       ├── doxygen
│       ├── examples
│       ├── image
│       ├── legacy
│       ├── sandbox
│       ├── taskflow
│       └── unittests
└── xmake.lua

这种把第三方源码直接加入还是比较常见的，个人也比较倾向用git submodules管理，但 package()的方式似乎不能用set_urls指定本地目录，如果重新用xmake在写一遍是比较麻烦的，不知是否有解决方法。

**Comment by waruqi** [comment]
一种方式：

```lua
target("thrid-party")
    set_kind("phony")
    on_build(function (target)
        os.cd(os.scriptdir())
        os.exec("cmake .")  --- 自己写点脚本执行cmake构建
    end)

target("xxxx")
    add_deps("thrid-party")
    add_links("")
    add_linkdirs("")
    add_includedirs("") 
```

要么还是用package，set_urls设置为你自身带有third-party源码的tar url，下载进入子目录编译安装

另外，干嘛非得放自身目录呢，add_requires管理依赖，直接走远程url拉取第三方包不是更干净。。

**Comment by wicast** [comment]
depth 1 可以少下很多东西

**Comment by waruqi** [comment]
> depth 1 可以少下很多东西

你git submodules维护，不是还是要深度clone ，submodule拉取我记得不支持depth 1的 ，而且走独立package，拉tar包就好了，比depth 1更省。。我xmake-repo的包大部分走的tar.gz 

而且如果有镜像源，下载更快。

**Comment by waruqi** [comment]
反正要么走package，要么加个xmake.lua维护，要么就通过on_build自己os.exec("cmake") 执行下内部构建三种方式，其他的方案暂不支持。。
