### ISSUE TITLE
windows下无法编译项目

### ISSUE THREAD

**Issue by jococi** [xmake-io/xmake#730]
### 期待的结果

编译生成dll文件。

### 错误信息
checking for the architecture ... x64
checking for the Microsoft Visual Studio (x64) version ... no
please run:
    - xmake config --vs=xxx [--vs_toolset=xxx]
or  - xmake global --vs=xxx
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
------------------------------------------------------------

### 相关环境

- 系统：windows10
- Visual Studio：2015
- 项目：sharde lib

### 其他信息
设置全局vs版本：
PS F:\workspace\xmakeObj\DFYQuoteApi> xmake global --vs=2015
configure
{
    theme = default
    vs = 2015
}
同样不行
请提供其他附加信息帮助我们诊断问题。

**Comment by waruqi** [comment]
执行下 xmake l detect.sdks.find_vstudio 给我看下输出

**Comment by jococi** [comment]
> 执行下xmake l detect.sdks.find_vstudio给我看下输出

{
  "2015" = {
    vcvarsall_bat = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat",
    version = "14.0",
    vcvarsall = {
      x86 = {
        libpath = "C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB;C:\Program Files (x86)\Windows Kits\8.1\References\CommonConfiguration\Neutral;\Microsoft.VCLibs\14.0\References\CommonConfiguration\neutral;",
        UniversalCRTSdkDir = "C:\Program Files (x86)\Windows Kits\10\",
        UCRTVersion = "10.0.10240.0",
        VSInstallDir = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\",
        DevEnvdir = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\",
        path = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\MSBuild\14.0\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\;C:\Users\dayuan\xmake;F:\soui\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Users\dayuan\AppData\Local\Microsoft\WindowsApps;D:\Program Files (x86)\Microsoft VS Code\bin",
        WindowsLibPath = "C:\Program Files (x86)\Windows Kits\8.1\References\CommonConfiguration\Neutral",
        WindowsSDKVersion = "\",
        WindowsSdkDir = "C:\Program Files (x86)\Windows Kits\8.1\",
        lib = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x86;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x86;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86;",
        include = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\\shared;C:\Program Files (x86)\Windows Kits\8.1\include\\um;C:\Program Files (x86)\Windows Kits\8.1\include\\winrt;",
        VCInstallDir = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\"
      },
      x64 = {
        libpath = "C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\8.1\References\CommonConfiguration\Neutral;\Microsoft.VCLibs\14.0\References\CommonConfiguration\neutral;",
        UniversalCRTSdkDir = "C:\Program Files (x86)\Windows Kits\10\",
        UCRTVersion = "10.0.10240.0",
        VSInstallDir = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\",
        path = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\MSBuild\14.0\bin\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\8.1\bin\x64;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\Users\dayuan\xmake;F:\soui\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Users\dayuan\AppData\Local\Microsoft\WindowsApps;D:\Program Files (x86)\Microsoft VS Code\bin",
        WindowsLibPath = "C:\Program Files (x86)\Windows Kits\8.1\References\CommonConfiguration\Neutral",
        WindowsSDKVersion = "\",
        WindowsSdkDir = "C:\Program Files (x86)\Windows Kits\8.1\",
        lib = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64;",
        include = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\\shared;C:\Program Files (x86)\Windows Kits\8.1\include\\um;C:\Program Files (x86)\Windows Kits\8.1\include\\winrt;",
        VCInstallDir = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\"
      }
    }
  }
}

**Comment by jococi** [comment]
`{
  "2015" = {
    vcvarsall_bat = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat",
    version = "14.0",
    vcvarsall = {
      x86 = {
        path = "C:\Users\dayuan\xmake;F:\soui\bin;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Users\dayuan\AppData\Local\Microsoft\WindowsApps;D:\Program Files (x86)\Microsoft VS Code\bin"
      },
      x64 = {
        path = "C:\Users\dayuan\xmake;F:\soui\bin;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Users\dayuan\AppData\Local\Microsoft\WindowsApps;D:\Program Files (x86)\Microsoft VS Code\bin"
      }
    }
  }
}`

**Comment by waruqi** [comment]
那就是有的么。。

先清掉全局配置，再清掉本地配置，强制全局重新检测下看看

```console
xmake g -c
xmake f -c
```

**Comment by jococi** [comment]
恩，可以
