### ISSUE TITLE
CharNextExA找不到实现

### ISSUE THREAD

**Issue by jococi** [xmake-io/xmake#731]
项目中一键设置：
**add_requires("tbox master",{system = false ,configs = {cxflags = "-fPIC",coroutine=true,charset=true,wchar=true}})**
### 描述问题详情
正在创建库 build\windows\x64\release\DFYTradeApi.lib 和对象 build\windows\x64\release\DFYTradeApi.exp
tbox.lib(charset.c.obj) : error LNK2019: 无法解析的外部符号 __imp_CharNextExA，该符号在函数 "unsigned __int64 __cdecl tb_charset_conv_impl_char_cp_bytes(unsigned char const *,unsigned __int64,unsigned int)" (?tb_charset_conv_impl_char_cp_bytes@@YA_KPEBE_KI@Z) 中被引用
build\windows\x64\release\DFYTradeApi.dll : fatal error LNK1120: 1 个无法解析的外部命令

**Comment by waruqi** [comment]
先自己link下 user32库

**Comment by waruqi** [comment]
我repo上更新过了，内部加了user32了，重新更新repo重装下tbox就可以了

```console
xmake repo -u
xmake f -c
xmake
```

**Comment by waruqi** [comment]
你先试试吧，应该可以了的

**Comment by jococi** [comment]
好的
