### ISSUE TITLE
xmake.conf problem in demo shared library

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake#735]
On Windows, `xmake create -l c -t shared test`, in `.xmake\windows\x64\xmake.conf`: `kind = "static"`.
Should it be `kind = "shared"`?

Thanks

**Comment by waruqi** [comment]
It only for `xmake f --kind=[static|shared]` to set target kind dynamically. If you do not specify a value, it is static by default.

```lua
target("test")
    set_kind("$(kind)")  <--- set target kind dynamically
```

But `xmake create -l c -t shared test` only create target with the shared kind.

```lua
target("test")
    set_kind("shared")
```

**Comment by conlay-cn** [comment]
参见#711

config里面看到都是xmake config 的配置参数，xmake config --kind=static/shared

用于动态切换某个target的kind类型，例如：

target("test")
    set_kind("$(kind)")
而如果你项目都写死set_kind("shared")了，那么不管xmake f --kind=static怎么改，都是影响不到的，而默认kind的命令参数值是static，所以你如果没去传递参数改它，那就一直是这个值

**Comment by playgithub** [comment]
@waruqi @conlay-cn 

如果`xmake create -l c -t shared test`指定了shared，`xmake.conf`里面`kind = "shared"`，是不是更好？

**Comment by waruqi** [comment]
> @waruqi @conlay-cn
> 
> 如果`xmake create -l c -t shared test`指定了shared，`xmake.conf`里面`kind = "shared"`，是不是更好？

之前说了，xmake.conf里面，是给`xmake f -k xxx`搭配`$(kind)`变量和`get_config("kind")`动态切kind用的，模板工程都写死指定shared kind 的target，就没必要用xmake config去动态切了，干嘛还要去关心config里面的值。。
