### ISSUE TITLE
includes和set_pcxxheader冲突

### ISSUE THREAD

**Issue by bstaint** [xmake-io/xmake#736]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题

2.3.2 includes和set_pcxxheader冲突，2.3.1无问题
目录结构：
E:.
│  .gitignore
│  test2.lua
│  xmake.lua
│
├─src
│      main.cpp
│      pch.h
│
├─src2
│     test.cpp

`xmake.lua`
```
includes('test2.lua')

-- add modes: debug and release
add_rules("mode.debug", "mode.release")

-- add target
target("test1")

    -- set kind
    set_kind("binary")

    -- add files
    add_deps("test2")
    add_files("src/main.cpp")

    set_pcxxheader("src/pch.h")
```

`test2.lua`
```
target("test2")

    set_kind("static")
    add_files("src2/test.cpp")
```

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 错误信息

如果可能，请尽量附加程序运行过程中的错误输出信息。

> E:\Downloads\test2>d:\Develop\xmake\xmake.exe build
[ 25%]: compiling.debug src\main.cpp
[ 37%]: compiling.debug src2\test.cpp
error: main.cpp
src\main.cpp: fatal error C1083: 无法打开预编译头文件: “build\.objs\test1\windows\x86\debug\src\pch.h.pch”: No such file or directory。

### 相关环境

请提供编译和运行环境信息，例如：xmake版本、操作系统等

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by waruqi** [comment]
等我晚上看下

**Comment by waruqi** [comment]
我改了下，你在试试 xmake update -s dev

**Comment by waruqi** [comment]
这个主要是这个版本重构整个并行构建优化编译速度引出来的一些bug。

**Comment by bstaint** [comment]
可以了 谢谢。
