### ISSUE TITLE
xmkae支持直接从Github拉取依赖的项目的源码么？

### ISSUE THREAD

**Issue by jackywu** [xmake-io/xmake#738]
> 注：如果是`问题报障`或者`特性请求`，请选择对应issues模板，否则一律不回复。

### 描述问题详情

xmkae支持直接从Github拉取依赖的项目的源码么？
例如，X项目在github的地址是： github.com/man/X, 我在项目里使用到了这个package，能够在xmake的配置文件里设置里这个 github.com/man/X 地址后，xmake自己去下载源码然后执行编译过程么？

**Comment by waruqi** [comment]
可以啊 add_urls 加上你的git url就行了 
xmake-repi里面随便找个package描述参考下就行 都有git url

或者看下 https://github.com/tboox/benchbox/blob/master/repo/packages/c/coroutine/xmake.lua

**Comment by jackywu** [comment]
理解了，多谢。
