### ISSUE TITLE
在安装了vs2010和vs2015下使用xmake遇到了问题

### ISSUE THREAD

**Issue by zchGithub123** [xmake-io/xmake#739]
> 注：如果是`问题报障`或者`特性请求`，请选择对应issues模板，否则一律不回复。

### 描述问题详情
请在这描述你的问题详情。

我的电脑同时安装了vs2010和vs2015，使用了xmake构建我的项目，但是xmake好像是找不到对应的文件，一直断言失败，一下是xmake的报错堆栈：
error: @programdir\core\main.lua:261: @programdir\core\sandbox\modules\import\co
re\base\task.lua:65: @programdir\core\sandbox\modules\os.lua:505: assertion fail
ed!
stack traceback:
    [C]: in function 'assert'
    [@programdir\core\sandbox\modules\os.lua:505]: in function 'isfile'
    [@programdir\modules\detect\sdks\find_vstudio.lua:206]: in function 'find_vs
tudio'
    [@programdir\modules\private\platform\check_vstudio.lua:37]: in function '_c
heck_vsenv'
    [@programdir\modules\private\platform\check_vstudio.lua:83]: in function 'ch
eck_vstudio'
    [@programdir\platforms\windows\config.lua:135]: in function 'on_check'
    [...mdir\core\sandbox\modules\import\core\project\config.lua:123]: in functi
on 'check'
    [@programdir\actions\config\main.lua:253]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:520]: in function 'run'
    [@programdir\core\sandbox\modules\import\core\base\task.lua:63]: in function
 'run'
    [@programdir\actions\build\main.lua:99]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:520]: in function 'run'
    [@programdir\core\main.lua:259]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:306]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:814: in function 'raise'
        @programdir\core\main.lua:261: in function 'cotask'
        @programdir\core\base\scheduler.lua:306: in function <@programdir\core\b
ase\scheduler.lua:304>

**Comment by waruqi** [comment]
你是在vsprompt的命令终端下执行的？这个里面检测有点小问题，如果当前cmd存在VCInstallDir环境变量，会优先从这个里面检测vcvarsall.bat，没检测到就报错了。

你要么切到正常cmd下试试，或者执行xmake update dev更新的dev版本试试，我刚稍微处理了下

**Comment by zchGithub123** [comment]
thanks a million
