### ISSUE TITLE
xmake update导致~/.bashrc被破坏

### ISSUE THREAD

**Issue by KB5201314** [xmake-io/xmake#740]
### 描述问题

从xmake 2,.3.1 执行xmake update，导致`~/.bashrc`最后一行被破坏

原因是下面语句中echo内容前缺少换行符
https://github.com/xmake-io/xmake/blob/8447f895b453a9b624b50b6f457083b3096f74bc/scripts/get.sh#L212

### 错误信息

![图片](https://user-images.githubusercontent.com/14936301/78232100-597f7400-7506-11ea-9f7f-05e5363a0e70.png)

### 相关环境

xmake 2.3.1

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by waruqi** [comment]
哦 那你帮忙提个pr改下吧。。或者等我忙完其他的后 再改下这里。。

**Comment by KB5201314** [comment]
提交了pr #741

**Comment by waruqi** [comment]
merge了
