### ISSUE TITLE
如何选择vs版本进行编译？

### ISSUE THREAD

**Issue by garraGH** [xmake-io/xmake#742]
> 注：如果是`问题报障`或者`特性请求`，请选择对应issues模板，否则一律不回复。

### 描述问题详情
电脑上有多个vs版本，xmake默认会找到最新的vs2019版本进行编译，如何设置使用别的vs版本？谢谢！

**Comment by waruqi** [comment]
xmake f --vs=2017 -c

具体看xmake f --help
