### ISSUE TITLE
QT 添加 gui-private库支持

### ISSUE THREAD

**Issue by KellyGodLv** [xmake-io/xmake#749]
QT有个库似乎不能解析，QtGui库有个私有库，头文件是在E:\Qt\Qt5.12.7\5.12.7\msvc2017_64\include\QtGui\5.12.7  ，通过QtGui-private似乎无法自动添加该头文件进去。这是我的写法
add_frameworks("QtCore","QtGui","QtWidgets","QtPrintSupport","QtGui-private")
把QtGui-private解析成其他目录了-IE:\Qt\Qt5.12.7\5.12.7\msvc2017_64\include\QtGui-private

**Comment by waruqi** [comment]
把对应的 include 目录和lib名字发我下

**Comment by KellyGodLv** [comment]
比如QT 5.12.7 加入gui-private可以访问E:\Qt\Qt5.12.7\5.12.7\msvc2017_64\include\QtGui\5.12.7\QtGui
E:\Qt\Qt5.12.7\5.12.7\msvc2017_64\include\QtGui\5.12.7
下的文件，命令行中没有单独的库出来，应该是Qt5Gui.dll 
除了gui-private 还有 core-private，主要是为了访问  头文件

**Comment by waruqi** [comment]
哦，我回头看下

**Comment by waruqi** [comment]
@KellyGodLv 关于这个问题，@shaoxie1986 帮忙提了个pr支持上了，你可以关注下，看看是否也能解决你这的问题 https://github.com/xmake-io/xmake/pull/752

**Comment by waruqi** [comment]
这个我merge了，你可以试试：`add_frameworks("QtGui", "QtGuiPrivate")`

**Comment by waruqi** [comment]
可以了么

**Comment by KellyGodLv** [comment]
OK
