### ISSUE TITLE
xmake repo --list 报错

### ISSUE THREAD

**Issue by vkensou** [xmake-io/xmake#751]
系统是windows8.1。
在添加删除了一个本地仓库后，xmake repo --list 报如下错误：

>xmake repo --list
local repositories:

global repositories:
error: bad argument #1 to 'isdir' (string expected, got nil)

**Comment by waruqi** [comment]
请追加 -vD 参数，给我看下详细栈信息

**Comment by vkensou** [comment]
抱歉，我解决不了问题直接重装xmake了。现在可以正常使用了。

**Comment by waruqi** [comment]
那等之后复现了 再给我看下栈好了
