### ISSUE TITLE
希望可以将本地git仓库作为包源

### ISSUE THREAD

**Issue by vkensou** [xmake-io/xmake#753]
为了更方便的部署本地的私有仓库。希望可以将电脑本地的git仓库作为包源。

**Comment by waruqi** [comment]
我看了下，本地git源原本就支持的，不过你需要指定到 `/.git` git仓库，因为remote有git://协议可以识别到是git仓库，本地的话只能通过.git后缀来识别

```lua
    add_urls("/Users/ruki/projects/personal/tbox/.git")
```

也支持切指定tag/commit/branch

```lua
    add_urls("/Users/ruki/projects/personal/tbox/.git")
    add_versions("v1.6.2", "v1.6.2")
    add_versions("v1.6.2", "xxxxxxxx") -- commit
    add_versions("v1.6.2", "branch_name")  -- branch
```

然后

```lua
add_requires("tbox 1.6.2")
```

就能切到1.6.2对应的分支/tag

**Comment by vkensou** [comment]
抱歉。经过测试确实可以将本地git仓库作为源来使用。
唯一不太方便的是，git 纯版本库也必须放到.git文件夹下。

**Comment by waruqi** [comment]
> 抱歉。经过测试确实可以将本地git仓库作为源来使用。
> 唯一不太方便的是，git 纯版本库也必须放到.git文件夹下。

什么是git 纯版本库？git库，不是本身当前目录下就会有 .git 目录存在的么。。

**Comment by vkensou** [comment]
> > 抱歉。经过测试确实可以将本地git仓库作为源来使用。
> > 唯一不太方便的是，git 纯版本库也必须放到.git文件夹下。
> 
> 什么是git 纯版本库？git库，不是本身当前目录下就会有 .git 目录存在的么。。

就是 git init --bare   tortoisegit 管它叫纯版本库。我不知道别的地方怎么叫。。。

**Comment by waruqi** [comment]
> git init --bare tortoisegit

不就是裸库么，通常不也是要 `git init --bare tortoise.git` 来约定下.git命名么，虽然不是强制的

没有约定，我这边检测不到是否为git仓库，虽然可以通过里面的各种内部文件来探测是否为git，但这也太蛋疼了，先就这样吧。。目前仅支持 git://xxx https:/xxxx.git 以及 local/file/.git等url规范的git仓库

**Comment by vkensou** [comment]
补充一下。我之前以为裸库也要放到 .git 文件夹下，这样感觉有点不方便。经测试后发现，文件夹名以.git结尾就可以了，这样就方便了。

**Comment by waruqi** [comment]
只需要后缀名带.git就行了，不一定是 独立 .git 目录
