### ISSUE TITLE
travis上使用xmake编译项目突然失败

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#755]
travis编译地址：
[https://travis-ci.org/github/fasiondog/hikyuu/jobs/671646013](https://travis-ci.org/github/fasiondog/hikyuu/jobs/671646013)

见下图：
![图片](https://user-images.githubusercontent.com/1145161/78564942-c0c35e00-784f-11ea-8a76-193dc6498207.png)

travis中获取xmake的部分：
![图片](https://user-images.githubusercontent.com/1145161/78565137-0a13ad80-7850-11ea-8492-5a128c36afe0.png)

**Comment by waruqi** [comment]
这个我后两天看下，我还有些其他的issues需要先处理下。

**Comment by waruqi** [comment]
这个也是前两天为了支持frameworks，重构links继承时候，忘记对phony做了处理导致，应该可以了，你再试试

**Comment by waruqi** [comment]
另外，我看你这边已经用了 add_requires，为啥boost/python 还是单独引入，也可以考虑切到add_requires一起维护

**Comment by waruqi** [comment]
这个可以了么？

**Comment by fasiondog** [comment]
可以了。boost/python一直没改是因为懒，后面找个时间切过来
