### ISSUE TITLE
xmake project -k vsxmake -m "debug;release" 报错

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#756]
xmake project -k vsxmake -m "debug;release" 报错：error: key 'debug' not found

![图片](https://user-images.githubusercontent.com/1145161/78568966-79d86700-7855-11ea-960b-5e5886f6a340.png)

**Comment by waruqi** [comment]
我这里没这问题么。你追加 -vD 给我看下详细栈

**Comment by fasiondog** [comment]
PS D:\workspace\hikyuu> xmake project -k vsxmake -m "release;debug" -a x64 -v -D
configure
{
    sh = link.exe -dll
    test = small
    ndk_stdcxx = true
    host = windows
    ar = link.exe -lib
    buildir = build
    with-demo = false
    arch = x64
    plat = windows
    hdf5 = false
    ccache = true
    mode = debug
    mysql = true
    cc = cl.exe
    boost-python-suffix = 3X
    cxx = cl.exe
    kind = static
    hdf5_D = true
    vs = 2017
    ld = link.exe
}
using project kind vs2017
checking for the release.x64 ...
> checking for the c links(hku_hdf5_D, hku_hdf5_hl_D, hku_hdf5_cpp_D, hku_hdf5_hl_cpp_D)
checkinfo: ...gramdir\core\sandbox\modules\import\core\tool\linker.lua:91: @programdir\modules\core\tools\link.lua:135: LINK : fatal error LNK1181: 无法打开输入文件“hku_hdf5_D.lib”

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:787]: in function 'raise'
    [@programdir\modules\core\tools\link.lua:135]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
    [@programdir\modules\core\tools\link.lua:117]:
    [C]: in function 'link'
    [...gramdir\core\sandbox\modules\import\core\tool\linker.lua:89]: in function 'link'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:196]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:192]:
    [C]: in function 'load'
    [@programdir\core\project\option.lua:103]: in function '_on_check'
    [@programdir\core\project\option.lua:167]: in function '_check'
    [@programdir\core\project\option.lua:217]: in function 'check'
    [...dir\core\sandbox\modules\import\core\project\project.lua:89]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:190]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:187]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

checking for the hdf5_D ... no
> checking for the c links(hku_hdf5, hku_hdf5_hl, hku_hdf5_cpp, hku_hdf5_hl_cpp)
> checking for the c links(libmysql)
> checking for the c++ links(hku_hdf5, hku_hdf5_hl, hku_hdf5_cpp, hku_hdf5_hl_cpp)
checking for the hdf5 ... ok
> checking for the c++ links(libmysql)
checking for the mysql ... ok
generating D:\workspace\hikyuu\config.h.in to hikyuu_cpp\hikyuu\config.h ..
  > replace VERSION -> 1.1.5
  > replace VERSION_MAJOR -> 1
  > replace VERSION_MINOR -> 1
  > replace VERSION_ALTER -> 5
  > replace SUPPORT_SERIALIZATION -> 1
  > replace SUPPORT_TEXT_ARCHIVE -> 0
  > replace SUPPORT_XML_ARCHIVE -> 1
  > replace SUPPORT_BINARY_ARCHIVE -> 1
  > replace CHECK_ACCESS_BOUND -> 1
  > replace USE_ASYNC_LOGGER -> 0
  > replace SPDLOG_ACTIVE_LEVEL -> 2
  > replace HKU_DISABLE_ASSERT -> 0
generating D:\workspace\hikyuu\config.h.in ... cache
checking for the debug.x64 ...
> checking for the c links(hku_hdf5, hku_hdf5_hl, hku_hdf5_cpp, hku_hdf5_hl_cpp)
checkinfo: ...gramdir\core\sandbox\modules\import\core\tool\linker.lua:91: @programdir\modules\core\tools\link.lua:135: LINK : fatal error LNK1181: 无法打开输入文件“hku_hdf5.lib”

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:787]: in function 'raise'
    [@programdir\modules\core\tools\link.lua:135]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
    [@programdir\modules\core\tools\link.lua:117]:
    [C]: in function 'link'
    [...gramdir\core\sandbox\modules\import\core\tool\linker.lua:89]: in function 'link'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:196]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:192]:
    [C]: in function 'load'
    [@programdir\core\project\option.lua:103]: in function '_on_check'
    [@programdir\core\project\option.lua:167]: in function '_check'
    [@programdir\core\project\option.lua:217]: in function 'check'
    [...dir\core\sandbox\modules\import\core\project\project.lua:89]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:190]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:187]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

checking for the hdf5 ... no
> checking for the c links(hku_hdf5_D, hku_hdf5_hl_D, hku_hdf5_cpp_D, hku_hdf5_hl_cpp_D)
> checking for the c links(libmysql)
> checking for the c++ links(hku_hdf5_D, hku_hdf5_hl_D, hku_hdf5_cpp_D, hku_hdf5_hl_cpp_D)
checking for the hdf5_D ... ok
> checking for the c++ links(libmysql)
checking for the mysql ... ok
generating D:\workspace\hikyuu\config.h.in to hikyuu_cpp\hikyuu\config.h ..
  > replace VERSION -> 1.1.5
  > replace VERSION_MAJOR -> 1
  > replace VERSION_MINOR -> 1
  > replace VERSION_ALTER -> 5
  > replace SUPPORT_SERIALIZATION -> 0
  > replace SUPPORT_TEXT_ARCHIVE -> 0
  > replace SUPPORT_XML_ARCHIVE -> 1
  > replace SUPPORT_BINARY_ARCHIVE -> 1
  > replace CHECK_ACCESS_BOUND -> 1
  > replace USE_ASYNC_LOGGER -> 0
  > replace SPDLOG_ACTIVE_LEVEL -> 2
  > replace HKU_DISABLE_ASSERT -> 0
generating D:\workspace\hikyuu\config.h.in ... ok
error: @programdir\core\main.lua:261: @programdir\plugins\project\vsxmake\vsxmake.lua:62: key 'debug' not found
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:787]: in function 'raise'
    [@programdir\plugins\project\vsxmake\vsxmake.lua:62]: in function 'paramsprovider'
    [@programdir\plugins\project\vsxmake\render.lua:31]:
    [C]: in function 'gsub'
    [@programdir\plugins\project\vsxmake\render.lua:66]:
    [C]: in function 'gsub'
    [@programdir\plugins\project\vsxmake\render.lua:66]: in function 'render'
    [@programdir\plugins\project\vsxmake\vsxmake.lua:168]:
    [@programdir\plugins\project\main.lua:76]: in function '_make'
    [@programdir\plugins\project\main.lua:89]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:520]: in function 'run'
    [@programdir\core\main.lua:259]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:787: in function 'raise'
        @programdir\core\main.lua:261: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>

**Comment by fasiondog** [comment]
单独 "debug" 或者 "release" 都没问题，但是 "debug;release" 或者 "release;debug"就不行

**Comment by waruqi** [comment]
我稍微看了下，应该是这个地方导致：

```lua
target("_hikyuu")
    set_kind(ifelse(is_mode("release"), "shared", "phony"))
```

在设置了 "debug;release" 组合后，会根据 shared ，分别对release/debug 生成对应的配置

但是你这里动态切了，所以切到debug生成时候，发现没了 shared -> debug的配置，因为你改成phony了。所以就失败了。。

如果要生成vs工程，建议不要这么设置，导致动态切kind ，因为生成后的 vsproj 定死了，要么debug/release全有这个shared，要么全没有。。

几种解决方案：

1. 不要生成组合debug/release了。
2. 改成固定kind，至少不要根据mode来切kind。

如果非要根据mode来禁用某个target，不要通过设置成phony来禁用，可以通过 set_enabled/set_default 来

`set_default(false)`会默认禁用这个target的编译，除非显示指定xmake build _hikyuu才会去编译，但是target还存在，里面的files会保留到vcproj

```lua
target("_hikyuu")
    set_kind("shared")
    if not is_mode("release") then
        set_default(false)
    end
```

`set_enable(false)`会彻底禁用这个target，连target的meta也不会被加载，vcproj不会保留它

```lua
target("_hikyuu")
    set_kind("shared")
    if not is_mode("release") then
        set_enabled(false)
    end
```

你可以先试试set_default的方案。phony仅仅用于一些不设置add_files，。仅仅做一些关联scripts的操作，你的这些target设置成phony，还保留了add_files，所以之前那个 linker error，也是这个问题导致，虽然我内部处理掉了。。

**Comment by waruqi** [comment]
另外ifelse尽量不要去用了，这个是历史遗留接口了，我正在逐步弃用，你可以用 `a and a or b` 来达到跟 `ifelse(a, a, b)` 一个效果，ifelse会同时预执行false块的脚本，并不是特别好。

**Comment by fasiondog** [comment]
谢谢，又学了一招。现在可以了。
