### ISSUE TITLE
add_frameworks, add_frameworkdirs没有生效

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#762]
编译ios程序时，在工程中使用 add_frameworks, add_frameworkdirs 引用第三方的framework，但没有生效，始终报确实被引用库的头文件，-v -D 打印的编译信息中，也没有显示出这两个命令加入的目录或对象
<img width="952" alt="图片" src="https://user-images.githubusercontent.com/1145161/79114134-1d28ff00-7db5-11ea-90b7-18d66236fc62.png">

**Comment by waruqi** [comment]
请贴下xmake.lua 以及文本错误信息

**Comment by fasiondog** [comment]
命令：xmake f -y -p iphoneos -a arm64 --target_minver=9.0 --tiny=y --mode=release --purpose=release

xmake.lua部分内容: 
    if is_plat("iphoneos") then 
        add_frameworks("MNN")
        add_frameworkdirs("./cpp/yihua/3rdlib/ios")
    else
        add_packages("mnn")
    end

shell输出：
[ 66%]: compiling.release cpp/yihua/face_module/livedetect/LivenessDetectSession68.cpp
"/usr/bin/xcrun -sdk iphoneos clang" -c -fvisibility=hidden -Wall -Werror -mfpu=neon -std=c++17 -I/Users/ljh/src/boost_1_72_0 -I/Users/ljh/git-view/yhfacedetect/cpp -I. -DBOOST_ALL_DYN_LINK -DDLIB_NO_GUI_SUPPORT -DDLIB_PNG_SUPPORT -DDLIB_JPEG_SUPPORT -DDLIB_JPEG_STATIC -D_ENABLE_NEON -framework Foundation -framework CoreFoundation -I/Users/ljh/.xmake/packages/d/dlib/master/6addb4d1afac48cd98c9f4acbd02ada1/include -DDLIB_DISABLE_ASSERTS -fvisibility-inlines-hidden -frtti -fexceptions -Wno-unused-variable -ffast-math -Wno-error=unused-variable -Wno-missing-braces -Os -Qunused-arguments -arch arm64 -miphoneos-version-min=9.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk -o build/release/iphoneos/arm64/.objs/yhsdk/iphoneos/arm64/release/cpp/yihua/face_module/livedetect/LivenessDetectSession68.cpp.o cpp/yihua/face_module/livedetect/LivenessDetectSession68.cpp
error: @programdir/modules/private/async/runjobs.lua:213: @programdir/modules/private/action/build/object.lua:79: @programdir/modules/core/tools/gcc.lua:466: In file included from cpp/yihua/face_module/FaceModule.cpp:10:
In file included from cpp/yihua/face_module/FaceModule.h:14:
cpp/yihua/face_module/FaceModule_inl.h:18:10: fatal error: 'MNN/Interpreter.hpp' file not found
#include <MNN/Interpreter.hpp>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:787]: in function 'raise'
    [@programdir/modules/core/tools/gcc.lua:466]: in function 'catch'
    [@programdir/core/sandbox/modules/try.lua:127]: in function 'try'
    [@programdir/modules/core/tools/gcc.lua:416]:
    [C]: in function 'compile'
    [@programdir/modules/private/action/build/object.lua:79]: in function 'script'
    [@programdir/modules/private/action/build/object.lua:92]: in function '_build_object'
    [@programdir/modules/private/action/build/object.lua:117]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:190]:
    [C]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [@programdir/modules/private/async/runjobs.lua:187]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:317]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:787: in function 'raise'
	@programdir/modules/private/async/runjobs.lua:213: in function 'catch'
	@programdir/core/sandbox/modules/try.lua:127: in function 'try'
	@programdir/modules/private/async/runjobs.lua:187: in function 'cotask'
	@programdir/core/base/scheduler.lua:317: in function <@programdir/core/base/scheduler.lua:315>
--> 合并 libyhsdk.a
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: no input files specified
usage: lipo <input_file> <command> [<options> ...]
  command is one of:
    -archs
    -create
    -detailed_info
    -extract <arch_type> [-extract <arch_type> ...]
    -extract_family <arch_type> [-extract_family <arch_type> ...]
    -info
    -remove <arch_type> [-remove <arch_type> ...]
    -replace <arch_type> <file_name> [-replace <arch_type> <file_name> ...]
    -thin <arch_type>
    -verify_arch <arch_type> ...
  options are one or more of:
    -arch <arch_type> <input_file>
    -hideARM64
    -output <output_file>
    -segalign <arch_type> <alignment>
cp: ./build/ios_pkg/libdlib.a: No such file or directory

**Comment by fasiondog** [comment]
mac下编译

**Comment by waruqi** [comment]
我这里测试正常，你是用的最新的dev/commit版本么。。我记得之前一次commit add_deps 后会导致 add links等失效，后来我修复了来着。。你更新到最新版本dev试试呢

**Comment by fasiondog** [comment]
xmake v2.3.2+202004140932 （提示是从gitee上download的）
还是不行

**Comment by waruqi** [comment]
那就怪了，我这也是mac没法复现你这问题，要么你给个能复现的精简demo，我看下。

**Comment by waruqi** [comment]
这里也可以尝试回溯下之前的commit看看

可以尝试拉取源码编译，方便回溯：

```console
git clone ...
git checkout ..
git submodule update 
make build
source ./scripts/srcenv.profile
```

```console
cd yourproj
xmake

cd xmakeproj
git checkout ...
git submodule update 
make build --> 如果core没改动，可以不用每次build

cd yourproj
xmake
```

**Comment by fasiondog** [comment]
试了下，只要用 kind "static“ 就会报无法找到 framework 里的头文件，(binary和shared不会）

add_rules("mode.debug", "mode.release")

-- add target
target("hello")

    -- set kind
    set_kind("static")


    add_frameworkdirs("ios")
    add_frameworks("MNN")

    -- add files
    add_files("src/*.c")

**Comment by fasiondog** [comment]
(base) ljh@mac hello % xmake f -y -p iphoneos -a arm64 --target_minver=9.0 --mode=release
(base) ljh@mac hello % xmake -b -v -D hello                                              
configure
{
    ccache = true
    xcode_mobile_provision = iOS Team Provisioning Profile: com.chinalishi.app
    ndk_stdcxx = true
    plat = iphoneos
    ar = /usr/bin/xcrun -sdk iphoneos ar
    buildir = build
    arch = arm64
    xcode = /Applications/Xcode.app
    mode = release
    host = macosx
    cxx = /usr/bin/xcrun -sdk iphoneos clang
    cc = /usr/bin/xcrun -sdk iphoneos clang
    xcode_codesign_identity = Apple Development: fasiondog@sina.com (AB2S26JNDZ)
    kind = static
    xcode_sdkver = 13.4
    target_minver = 9.0
    ld = /usr/bin/xcrun -sdk iphoneos clang++
}
checking for the /usr/bin/xcrun -sdk iphoneos clang ... ok
checking for the flags (-Oz) ... ok
> xcrun -sdk iphoneos clang "-Oz"
checking for the ccache ... no
[ 50%]: compiling.release src/main.c
"/usr/bin/xcrun -sdk iphoneos clang" -c -fvisibility=hidden -Oz -Qunused-arguments -arch arm64 -miphoneos-version-min=9.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk -o build/.objs/hello/iphoneos/arm64/release/src/main.c.o src/main.c
checking for the flags (-MMD -MF) ... ok
> xcrun -sdk iphoneos clang "-MMD" "-MF" "/dev/null" "-Qunused-arguments" "-arch" "arm64" "-miphoneos-version-min=9.0" "-isysroot" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk"
checking for the flags (-fcolor-diagnostics) ... ok
> xcrun -sdk iphoneos clang "-fcolor-diagnostics" "-Qunused-arguments" "-arch" "arm64" "-miphoneos-version-min=9.0" "-isysroot" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk"
error: @programdir/modules/private/async/runjobs.lua:213: @programdir/modules/private/action/build/object.lua:79: @programdir/modules/core/tools/gcc.lua:466: src/main.c:3:10: fatal error: 'MNN/Interpreter.hpp' file not found
#include <MNN/Interpreter.hpp>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:787]: in function 'raise'
    [@programdir/modules/core/tools/gcc.lua:466]: in function 'catch'
    [@programdir/core/sandbox/modules/try.lua:127]: in function 'try'
    [@programdir/modules/core/tools/gcc.lua:416]:
    [C]: in function 'compile'
    [@programdir/modules/private/action/build/object.lua:79]: in function 'script'
    [@programdir/modules/private/action/build/object.lua:92]: in function '_build_object'
    [@programdir/modules/private/action/build/object.lua:117]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:190]:
    [C]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [@programdir/modules/private/async/runjobs.lua:187]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:317]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:787: in function 'raise'
	@programdir/modules/private/async/runjobs.lua:213: in function 'catch'
	@programdir/core/sandbox/modules/try.lua:127: in function 'try'
	@programdir/modules/private/async/runjobs.lua:187: in function 'cotask'
	@programdir/core/base/scheduler.lua:317: in function <@programdir/core/base/scheduler.lua:315>

**Comment by waruqi** [comment]
恩 这个我复现了，我先看看

**Comment by waruqi** [comment]
还是那个inherit_links重构引出的问题，有些case没处理完整，我修复了，你再试试。。dev版本

**Comment by fasiondog** [comment]
可以了

**Comment by fasiondog** [comment]
3Q
