### ISSUE TITLE
MacOSX下编译android后，再次编译总提示找不到上次的.o

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#763]
xmake v2.3.2+202004131824

第一次执行命令（正常编译）：
xmake f -v -D -y -p android --ndk="/Users/ljh/Library/Android/sdk/ndk-bundle" --ndk_sdkver=22 --android_sdk=/Users/ljh/Library/Android -a arm64-v8a --tiny=y --purpose=release 

修改某个文件后，重新执行上述命令，输出（注下面涉及的.o文件的列表有手工删减，仅示意）：
xmake f -v -D -y -p android --ndk="/Users/ljh/Library/Android/sdk/ndk-bundle" --ndk_sdkver=22 --android_sdk=/Users/ljh/Library/Android -a arm64-v8a --tiny=y --purpose=release 
target unit-test: loading yihua.rules ...
target yhsdk: loading yihua.rules ...
configure
{
    ex = /Users/ljh/Library/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-ar
    ccache = true
    ndk = /Users/ljh/Library/Android/sdk/ndk-bundle
    ndk_stdcxx = true
    host = macosx
    buildir = build
    header_only = false
    runtime_link = static
    gcc_toolchain = /Users/ljh/Library/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64
    cxx = /Users/ljh/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
    cross = aarch64-linux-android-
    tiny = true
    exception = true
    ndkver = 21
    purpose = release
    plat = android
    sdk = /Users/ljh/Library/Android
    ndk_toolchains_ver = 4.9
    arch = arm64-v8a
    rtti = true
    mode = release
    lto = false
    ndk_sdkver = 22
    boost-python-suffix = 3X
    cc = /Users/ljh/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
    kind = static
    ld = /Users/ljh/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
    android_sdk = /Users/ljh/Library/Android
    bin = /Users/ljh/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin
    sh = /Users/ljh/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
}
target unit-test: loading yihua.rules ...
target yhsdk: loading yihua.rules ...
configure
{
    ex = /Users/ljh/Library/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-ar
    ccache = true
    ndk = /Users/ljh/Library/Android/sdk/ndk-bundle
    ndk_stdcxx = true
    host = macosx
    buildir = build
    header_only = false
    runtime_link = static
    gcc_toolchain = /Users/ljh/Library/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64
    cc = /Users/ljh/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
    bin = /Users/ljh/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin
    tiny = true
    exception = true
    ndkver = 21
    purpose = release
    plat = android
    sdk = /Users/ljh/Library/Android
    ndk_toolchains_ver = 4.9
    arch = arm64-v8a
    rtti = true
    mode = release
    lto = false
    sh = /Users/ljh/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
    boost-python-suffix = 3X
    ndk_sdkver = 22
    kind = static
    ld = /Users/ljh/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
    android_sdk = /Users/ljh/Library/Android
    cross = aarch64-linux-android-
    cxx = /Users/ljh/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
}
[ 94%]: inserting.release cpp/yihua/3rdlib/android/aarch64/libomp.a
extracting cpp/yihua/3rdlib/android/aarch64/libomp.a to build/release/android/arm64-v8a/.objs/yhsdk/android/arm64-v8a/release/cpp/yihua/3rdlib/android/aarch64/libomp.a.o.dir
[ 97%]: linking.release libyhsdk.so
/Users/ljh/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -o build/release/android/arm64-v8a/lib/libyhsdk.so build/release/android/arm64-v8a/.objs/yhsdk/android/arm64-v8a/release/cpp/yihua/3rdlib/android/aarch64/libomp.a.o.dir/kmp_alloc.cpp.o build/release/android/arm64-v8a/.objs/yhsdk/android/arm64-v8a/release/cpp/yihua/3rdlib/android/aarch64/libomp.a.o.dir/kmp_taskdeps.cpp.o -L/Users/ljh/src/boost_1_72_0/stage/lib -L/Users/ljh/.xmake/packages/d/dlib/master/035f6e90cb0f4570b267d09e7c1b16dd/lib -L/Users/ljh/.xmake/packages/s/sqlite3/master/094bac91962f4b15b9b322ca9ac799a4/lib -L/Users/ljh/.xmake/packages/m/mnn/master/bd8f0a94ada341059a0a3225422d1af5/lib -s -ldlib -lsqlite3 -lMNN -lm -lz -ljnigraphics -landroid -Wl,-hash-style=sysv -Wl,--gc-sections -shared -fPIC -llog -target aarch64-none-linux-android -gcc-toolchain /Users/ljh/Library/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/ljh/Library/Android/sdk/ndk-bundle/platforms/android-22/arch-arm64 -L/Users/ljh/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/arm64-v8a -lc++_static -lc++abi -nostdlib++
error: @programdir/modules/private/async/runjobs.lua:213: @programdir/actions/build/kinds/shared.lua:102: @programdir/core/sandbox/modules/os.lua:258: clang++: error: no such file or directory: 'build/release/android/arm64-v8a/.objs/yhsdk/android/arm64-v8a/release/cpp/yihua/image_process/ImageUtil.cpp.o'
clang++: error: no such file or directory: 'build/release/android/arm64-v8a/.objs/yhsdk/android/arm64-v8a/release/cpp/yihua/GlobalConfig.cpp.o'
clang++: error: no such file or directory: 'build/release/android/arm64-v8a/.objs/yhsdk/android/arm64-v8a/release/cpp/yihua/utils/format.cpp.o'

stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:787]: in function 'raise'
    [@programdir/core/sandbox/modules/os.lua:258]: in function 'runv'
    [@programdir/modules/core/tools/gcc.lua:343]:
    [C]: in function 'link'
    [@programdir/actions/build/kinds/shared.lua:102]: in function '_do_link_target'
    [@programdir/actions/build/kinds/shared.lua:126]:
    [@programdir/actions/build/kinds/shared.lua:147]: in function '_link_target'
    [@programdir/actions/build/kinds/shared.lua:169]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:190]:
    [C]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [@programdir/modules/private/async/runjobs.lua:187]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:317]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:787: in function 'raise'
	@programdir/modules/private/async/runjobs.lua:213: in function 'catch'
	@programdir/core/sandbox/modules/try.lua:127: in function 'try'
	@programdir/modules/private/async/runjobs.lua:187: in function 'cotask'
	@programdir/core/base/scheduler.lua:317: in function <@programdir/core/base/scheduler.lua:315>

**Comment by waruqi** [comment]
之前就不行，还是最近才出现的？如果是更新后才出现的问题，可以回溯下 是哪个commit 导致。。

目前看log信息量太少，也不清楚你这的工程结构和编译设置，不太好定位问题。

**Comment by fasiondog** [comment]
之前应该是可以的

**Comment by waruqi** [comment]
那就帮忙回溯下commit吧。。方便定位问题

**Comment by fasiondog** [comment]
这个不是 xmake 的问题，是我这上面封了一层脚本导致的
