### ISSUE TITLE
构建docker 镜像时使用的安装脚本

### ISSUE THREAD

**Issue by TheBegining** [xmake-io/xmake#766]
### 你在什么场景下需要该功能？

构建我的docker 开发环境

### 描述可能的解决方案

在构建镜像时安装 xmake

### 描述你认为的候选方案

在 Dockerfile 运行安装脚本

### 其他信息

目前的安装脚本并不能直接用在 docker 镜像的构建中

```
FROM debian:buster

WORKDIR /workspace

ADD https://xmake.io/shget.text /workspace

RUN bash -e shget.text
```
推测是 bash 后台执行 docker 认为其已经结束，所以没有执行完，安装失败。

**Comment by waruqi** [comment]
可以参考下 https://github.com/waruqi/dockerfiles/blob/master/ubuntu/Dockerfile
