### ISSUE TITLE
显示找不到 Microsoft Visual Studio (x64) version

### ISSUE THREAD

**Issue by VkBlau** [xmake-io/xmake#770]
λ xmake
checking for the architecture ... x64
checking for the Microsoft Visual Studio (x64) version ... no
please run:
    - xmake config --vs=xxx [--vs_toolset=xxx]
or  - xmake global --vs=xxx

x

如上，怎么解决

**Comment by waruqi** [comment]
执行下 xmake l detect.sdks.find_vstudio 贴下输出，如果找不到，就自己到 安装目录加print调下这个脚本：https://github.com/xmake-io/xmake/blob/master/xmake/modules/detect/sdks/find_vstudio.lua

**Comment by yahao333** [comment]
没有 VCInstallDir 环境变量

Virtual Studio 16.9.0
win10 64位

**Comment by waruqi** [comment]
描述清楚上下，问题详情，如何复现。期待的结果，操作场景。

**Comment by xq114** [comment]
https://github.com/xmake-io/xmake/issues/2927 检查一下cmd是不是好的

**Comment by waruqi** [comment]
执行下 `xmake g -c` 清下全局缓存，强制重新检测下试试

**Comment by 666hsy** [comment]
请问解决了吗，我也遇到这个问题

**Comment by waruqi** [comment]
> 请问解决了吗，我也遇到这个问题

你可以单独开 issues 并提供完整 -vD logs 

也可以自己调下 find_vstudio.lua 那个脚本

**Comment by 666hsy** [comment]
新的issue：https://github.com/orgs/xmake-io/discussions/3785
