### ISSUE TITLE
add_requires，vcpkg的支持

### ISSUE THREAD

**Issue by Ultraman95** [xmake-io/xmake#776]
add_requires("vcpkg::gtest","vcpkg::cli11)	
此时这个地方只会安装gtest的windows-static库，怎么写才能安装dll动态库

**Comment by waruqi** [comment]
由于vcpkg 静态链接库默认 /MT(d)；动态链接库默认 /MD(d)

目前xmake里面是通过vs_runtime的设置来切的

```lua
add_requires("vcpkg::gtest","vcpkg::cli11", {configs = {vs_runtime = "MD"}})
```

只要设置成MD，就自动切到动态库。。

不过我想了想，还是得用 `{configs = {shared = true}}` 来切更一致些，我回头改进下，你先这么试试吧

**Comment by waruqi** [comment]
我刚dev上改进过了，统一走 shared = true 吧。。从ci上下载最新的dev包安装试下https://ci.appveyor.com/api/buildjobs/0qq0o1oly29g0ism/artifacts/xmake-installer.exe

或者等ci跑完后，执行xmake update dev更新到dev版本

然后使用这个（不过我没测过，win上没空间折腾安装vcpkg了，你先这边试试吧，不行再过来反馈，理论上改动不大，应该没啥大问题）
```lua
add_requires("vcpkg::gtest","vcpkg::cli11", {configs = {shared = true}})
```

**Comment by waruqi** [comment]
可以了么
