### ISSUE TITLE
使用windows交叉编译arm64-v8a项目的问题

### ISSUE THREAD

**Issue by dsp2000** [xmake-io/xmake#777]
> 注：如果是`问题报障`或者`特性请求`，请选择对应issues模板，否则一律不回复。

### 描述问题详情
请在这描述你的问题详情。

使用xmake create -t shared -l c test生成一个新的项目，如何将这个项目修改为交叉编译arm64-v8a的?

**Comment by dsp2000** [comment]
在xmake.lua里面加入吗?
-target aarch64-none-linux-android

**Comment by waruqi** [comment]
你都没说清楚交叉编译到哪个平台？android? 其他linux cross toolchain?

android的你看下文档 https://xmake.io/#/zh-cn/guide/configuration?id=android

其他交叉编译工具链见：https://xmake.io/#/zh-cn/guide/configuration?id=交叉编译

**Comment by dsp2000** [comment]
我需要用clang交叉编译到arm64平台，不是安卓的，但用安卓ndk自带的clang编译器

**Comment by waruqi** [comment]
> 我需要用clang交叉编译到arm64平台，不是安卓的，但用安卓ndk自带的clang编译器

你都用了android ndk去编译arm64-v8a了，不就等于是编译android的库么，只不过你不是给android用而已

一样的用法，直接用 https://xmake.io/#/zh-cn/guide/configuration?id=android 里面说的方式就行了

**Comment by dsp2000** [comment]
我用xmake f -p android --ndk=D:\msys32\android-ndk-r20b/  -a x86 可以检测到编译器，但用

xmake f -p windows --ndk=D:\msys32\android-ndk-r20b/  -a x86 就不行，
我想用这个x86编译电脑可以运行的bin

如果不行，在不安装 Visual studio的情况下，有什么轻量级的编译器可以支持?clnag有吗?

**Comment by dsp2000** [comment]
我就是希望用xmake + clang编译所有平台的的库

**Comment by waruqi** [comment]
> 
> xmake f -p windows --ndk=D:\msys32\android-ndk-r20b/ -a x86 就不行，
> 我想用这个x86编译电脑可以运行的bin

你既然用了ndk，就只能设置-p android平台，pc上x86你直接走vs不就好了，-p windows默认用的是vs的环境


> 
> 如果不行，在不安装 Visual studio的情况下，有什么轻量级的编译器可以支持?clnag有吗?

可以用mingw，或者llvm clang都可以

**Comment by waruqi** [comment]
> 我就是希望用xmake + clang编译所有平台的的库

那你就单独装llvm的工具链么

**Comment by waruqi** [comment]
> > 我就是希望用xmake + clang编译所有平台的的库
> 
> 那你就单独装llvm的工具链么

不同平台还是要用不同的工具链的，就像ndk虽然提供各种arch，但是依赖runtime是针对android的，不同平台都是不同的

你用非ndk的工具链编译的so，即使arch对，android下也不一定跑的起来

**Comment by dsp2000** [comment]
![UEMS3I 8PCBW3YSY8Q{VZ4V](https://user-images.githubusercontent.com/54521555/81490369-1ad29b80-92b4-11ea-94fe-d100a573217e.png)
target("arm64")

    -- set kind
    set_kind("static")

    -- add files
    add_files("src/interface.c")

-- add target
target("arm64_demo")

    -- set kind
    set_kind("binary")

    -- add deps
    add_deps("arm64")

    -- add files
    add_files("src/test.c")


上面生成libarm64.a 及 libarm64.so 两个文件，libarm64.a是不是只有interface.c的内容而没有test.c的内容的?

**Comment by dsp2000** [comment]
安装vs太费劲了，我只是需要生成dos可以运行的exe就可以了，主要是用来验证结果方便点而已。打算xmake + clang + vs code来实现，现在下载llvm之中

**Comment by waruqi** [comment]
> ![UEMS3I 8PCBW3YSY8Q{VZ4V](https://user-images.githubusercontent.com/54521555/81490369-1ad29b80-92b4-11ea-94fe-d100a573217e.png)
> target("arm64")
> 
> ```
> -- set kind
> set_kind("static")
> 
> -- add files
> add_files("src/interface.c")
> ```
> 
> -- add target
> target("arm64_demo")
> 
> ```
> -- set kind
> set_kind("binary")
> 
> -- add deps
> add_deps("arm64")
> 
> -- add files
> add_files("src/test.c")
> ```
> 
> 上面生成libarm64.a 及 libarm64.so 两个文件，libarm64.a是不是只有interface.c的内容而没有test.c的内容的?

是的

**Comment by waruqi** [comment]
> 安装vs太费劲了，我只是需要生成dos可以运行的exe就可以了，主要是用来验证结果方便点而已。打算xmake + clang + vs code来实现，现在下载llvm之中

或者用tcc 轻量点

**Comment by dsp2000** [comment]
msvc编译很多现在的库比较多写法不支持的，例如64位的LL tcc应该也是很老的编译器，估计也不行

**Comment by waruqi** [comment]
那就llvm clang好了

**Comment by dsp2000** [comment]
![26WS0CYNO31ZFLSDXXTVH 9](https://user-images.githubusercontent.com/54521555/81494043-0dc7a380-92d8-11ea-9275-dd2d1ca987b2.png)

xmake f -p windows --ndk=D:\Program Files\LLVM/

**Comment by dsp2000** [comment]
![1PM1(Y}Z_`FV7ED6C)BGU66](https://user-images.githubusercontent.com/54521555/81494059-46677d00-92d8-11ea-9e6e-95652ad1701d.png)

**Comment by dsp2000** [comment]
xmake f -p windows --ndk=D:\Program Files\LLVM/ 不可以选择llvm吗？

**Comment by waruqi** [comment]
ndk是给android平台用的，windows平台编译你传ndk干啥，xmake f -p windows --cc=xxx --cxx=xxx --ld=xxx 

或者走cross平台 xmake f -p cross --sdk=xxx --cc=xx

你自己看下交叉编译文档吧 ，都有详细说明

https://xmake.io/#/zh-cn/guide/configuration?id=%E4%BA%A4%E5%8F%89%E7%BC%96%E8%AF%91

**Comment by waruqi** [comment]
https://tboox.org/cn/2019/12/05/quickstart-9-cross-compile/

**Comment by dsp2000** [comment]
像llvm这些常用的也需要自己指cc这些找出来啊？

**Comment by dsp2000** [comment]
觉得也应该给你一个路径就可以了。我试试

**Comment by waruqi** [comment]
> 像llvm这些常用的也需要自己指cc这些找出来啊？

我只是随手敲的，举个例子，看这里面的说明 根据自己的实际情况操作 我现在又没有llvm环境 
 https://tboox.org/cn/2019/12/05/quickstart-9-cross-compile/

**Comment by dsp2000** [comment]
我本来是认为llvm太常用了，xmake本来就支持的，像ndk这样就很好

**Comment by waruqi** [comment]
> 我本来是认为llvm太常用了，xmake本来就支持的，像ndk这样就很好

所以我不是说根据 https://tboox.org/cn/2019/12/05/quickstart-9-cross-compile/ 这里面的说明一步步操作么，里面说了 默认只要设置--sdk=就能自动探测使用，不行再根据自己的实际情况一步步设置--cc=参数

自己看下文章 稍微配置下就能用了

你先自己仔细看下文章和文档，llvm这种其他人稍微看下文档就能搞定，不用每次都要我给你打全配置命令的，我现在又没llvm环境

**Comment by dsp2000** [comment]
![9RDIF)} EY83861E}KWY}MX](https://user-images.githubusercontent.com/54521555/81495170-df01fb00-92e0-11ea-8cab-3d962212c125.png)
上面的我明白了，如何在vscode里面调用xmake?

**Comment by waruqi** [comment]
装下xmake-vscode插件，你到插件中心搜下

**Comment by dsp2000** [comment]
![YHQO 58`3QUHY``F}5TH~KU](https://user-images.githubusercontent.com/54521555/81495645-5ab17700-92e4-11ea-987d-555141b54593.png)
找了下，没有使用的例子，只有你的博客说明怎样制作vscode插件的
不知怎样用

**Comment by dsp2000** [comment]
支持多相对路径这样吗？
 add_includedirs("../, ../Inc, ../Src, ../

**Comment by waruqi** [comment]
> ![YHQO 58`3QUHY``F}5TH~KU](https://user-images.githubusercontent.com/54521555/81495645-5ab17700-92e4-11ea-987d-555141b54593.png)
> 找了下，没有使用的例子，只有你的博客说明怎样制作vscode插件的
> 不知怎样用

这还需要使用说明哈，就下面一排button摸索两下就会了，所以我没写

你到https://github.com/xmake-io/xmake-vscode/blob/master/README.md的readme里面看下几张gif图演示就行，基本上就是全部使用方式了

**Comment by waruqi** [comment]
> 支持多相对路径这样吗？
> add_includedirs("../, ../Inc, ../Src, ../

你看下文档 https://xmake.io/#/zh-cn/manual/project_target?id=targetadd_includedirs

add_includedirs("dir1", "dir2", "dir3")

路径相对于当前xmake.lua所在目录

**Comment by waruqi** [comment]
可以看下这篇 https://tboox.org/cn/2017/10/17/xmake-vscode-update-v1.0.1/

**Comment by dsp2000** [comment]
我是想知道支持当前的上一层../../ 这样的吗？或者必须绝对路径C;/Library/这样？

**Comment by waruqi** [comment]
> 我是想知道支持当前的上一层../../ 这样的吗？或者必须绝对路径C;/Library/这样？

我刚不是说了是相对的，那当然支持啊，难道相对路径不支持.. ？

> 路径相对于当前xmake.lua所在目录

**Comment by dsp2000** [comment]
还有在vxcode之中。在路径 .vscode/c_cpp_properties.json 之中 如果已经设置includePath，可以自动到当中找出来*.h文件？这里重复设置了

**Comment by dsp2000** [comment]
add_includedirs("D:/multimedia/app/jni/DecM8c/libavutil"); 这样的路径并不认，用../../这样的路径也不行

**Comment by dsp2000** [comment]
是不是需要修改成与/d/multimedia类似linux这样的才行？现在的情况是怎样也找不到指定目录下的*.h文件，但vscode配置好后就找到了， 
 "includePath": [
                "${workspaceFolder}/**",
                "../",
                "../Inc",
                "../Src/include",

**Comment by waruqi** [comment]
> 还有在vxcode之中。在路径 .vscode/c_cpp_properties.json 之中 如果已经设置includePath，可以自动到当中找出来*.h文件？这里重复设置了

跟这个没有关系，这个只是编辑器提示和文件跳转用的 跟编译没关系

**Comment by waruqi** [comment]
> add_includedirs("D:/multimedia/app/jni/DecM8c/libavutil"); 这样的路径并不认，用../../这样的路径也不行

你说的不认是指什么，add_includedirs仅用于编译，只要能编译过就行，目前不支持跟vscode配合做文件跳转和提示

**Comment by waruqi** [comment]
> 是不是需要修改成与/d/multimedia类似linux这样的才行？现在的情况是怎样也找不到指定目录下的*.h文件，但vscode配置好后就找到了，
> "includePath": [
> "${workspaceFolder}/**",
> "../",
> "../Inc",
> "../Src/include",

vscode的这个设置仅影响vscode的提示跳转，这个你自己折腾下吧 目前xmake的插件还不支持同步includes提示

只要add_includedirs设置后，调用xmake编译能通过就行了 如果编译器提示找不到头文件，那就贴下编译错误

**Comment by dsp2000** [comment]
编译提示没有找到.h文件，我怎样加路径都不行。

**Comment by dsp2000** [comment]
编辑器提示和文件跳转正常，表示他可以找到.h文件了
ncludePath": [
"${workspaceFolder}/**",
"../",
"../Inc",
"../Src/include",

**Comment by dsp2000** [comment]
类似的用add_includedirs 
xmake编译提示没有找到.h文件

**Comment by waruqi** [comment]
> 编译提示没有找到.h文件，我怎样加路径都不行。

那就贴下错误信息，当前add_includedirs的设置，你代码里面怎么include的也贴下

自己对应库头文件的目录结构也贴下 不然我不知道你这的情况

**Comment by dsp2000** [comment]
![(0U}`98)BDG8PGK{0~W4NEM](https://user-images.githubusercontent.com/54521555/81497330-53906600-92f0-11ea-9311-da69fd8c10d1.png)
![0B7N{8}F37(OL{{8AIU~YOL](https://user-images.githubusercontent.com/54521555/81497459-327c4500-92f1-11ea-9e58-3d7fc8ba69f2.png)
![)C3A_D$HIG7%7YHWPTN~5SE](https://user-images.githubusercontent.com/54521555/81497466-3a3be980-92f1-11ea-9f54-3ed0305c65f4.png)

**Comment by dsp2000** [comment]
![POYIGO2QRDHR38}C3SG0~~Y](https://user-images.githubusercontent.com/54521555/81497478-52ac0400-92f1-11ea-9998-d573c93a0cfb.png)

**Comment by dsp2000** [comment]
主要的路径都是在windows上层出现的，也有的绝对路径，担心支持windows路径不太友好因为
// 
 /
\\
\
这几种

**Comment by waruqi** [comment]
> 主要的路径都是在windows上层出现的，也有的绝对路径，担心支持windows路径不太友好因为
> //
> /
> \
> 
> 这几种

这种是最基础的支持，如果这都支持不了，老早其他用户来反馈了

你xmake.lua的内容也不贴，include的代码也不贴，intmath.h的路径在哪也没贴，我怎么知道咋回事

按理这种includedirs的问题，跟xmake没啥关系，你自己折腾下就行了

出现include文件找不到，首先自己确认下找不到intmath.h的路径在哪里，include怎么包含的，然后对下xmake.lua里面add_includedirs里面的目录是否匹配intmath.h所在目录

你可以执行xmake -v或者插件设置里面xmake.loglevel设置成verbose看下详细编译命令，里面有-Idir的完整include路径，自己对下就行了

**Comment by dsp2000** [comment]
intmath.h位于已经指示的路径
"../libavutil", （ D:\pAndroid\multimedia\app\jni\DecM8c\libavutil）
 add_includedirs("../, "../Inc", "../Src", "../Src/include", "../libavcodec", "../libavutil", "../libavutil/arm"
![M`(G8NH})3D@2C{J8@1078H](https://user-images.githubusercontent.com/54521555/81515034-c804ec80-9364-11ea-93e3-db07685bfa86.png)

**Comment by dsp2000** [comment]
![KHJ)DCZL0VQWN )R%%%N%{E](https://user-images.githubusercontent.com/54521555/81515152-35b11880-9365-11ea-963e-ef743eb5e610.png)

**Comment by dsp2000** [comment]
![KHJ)DCZL0VQWN )R%%%N%{E](https://user-images.githubusercontent.com/54521555/81515152-35b11880-9365-11ea-963e-ef743eb5e610.png)

**Comment by waruqi** [comment]
看你的xmake.lua内容，add_includedirs你是加在了 target("DecM8c")这个静态库里面，仅仅编译interface.c时候才会生效。。

而你编译报错的是main.c，是另外一个target，当然不行了，你想哪个target带上includedirs，就对哪个target加上add_includedirs，或者要么就在根域上设置。。

你main.c所在的target又没设置add_includedirs，怎么可能找的到。。，自己看下输出了，`-I/xxx`都没在里面。

![image](https://user-images.githubusercontent.com/151335/81515684-d7d20000-9367-11ea-8620-fbdb8a6bb6d3.png)

**Comment by dsp2000** [comment]
明白了，现在用dos窗口编译不提示这个了，但vs没有调用 xmake
![%H `D5{BZ_SBPSX6%8DG75Y](https://user-images.githubusercontent.com/54521555/81515819-5f1f7380-9368-11ea-8062-0a46f2cf1129.png)

**Comment by dsp2000** [comment]
xmake f -p cross --sdk=D:\Program Files\LLVM --cross=clang-

D:\Program Files\LLVM\bin
![$3XSODP121S ~H29L%1ZJ K](https://user-images.githubusercontent.com/54521555/81517070-487b1b80-936c-11ea-9951-0aa2a70f6dee.png)

**Comment by dsp2000** [comment]
![P_DL$155H$OVBOID L@UI 4](https://user-images.githubusercontent.com/54521555/81517324-2635cd80-936d-11ea-8a98-ebb358390753.png)
这个是使用llvm时出错，现在我是在两台电脑上分别试，这台没有安装vs所以需要clang

**Comment by waruqi** [comment]
> xmake f -p cross --sdk=D:\Program Files\LLVM --cross=clang-

这里 就是 clang.exe 。。没cross前置，你不用指定，又不是 xxxx-clang.exe这种。。

另外你这里报错，是因为 你终端敲 D:\Program Files\LLVM  这种路径，你好歹用个 双引号 wrap下吧，不然终端传给xmake的实际参数，被它split过的。

**Comment by waruqi** [comment]
> 明白了，现在用dos窗口编译不提示这个了，但vs没有调用 xmake
> ![%H `D5{BZ_SBPSX6%8DG75Y](https://user-images.githubusercontent.com/54521555/81515819-5f1f7380-9368-11ea-8062-0a46f2cf1129.png)

没明白你要说什么

**Comment by dsp2000** [comment]
![H$UUT)JE80CHNX}}LPNAM$X](https://user-images.githubusercontent.com/54521555/81517750-7e210400-936e-11ea-9568-e5bb3d700e4c.png)
f -p 没有出错，但没有用

**Comment by waruqi** [comment]
给我贴错误的时候，请追加 -vD 参数，获取完整诊断信息，另外xmake f 时候追加 -c 参数，强制忽略之前的错误配置cache

```console
xmake f -p cross --sdk=xxx -c
xmake -vD
```

**Comment by dsp2000** [comment]
![JDW99P%E 7Q~@SQT~UM06I](https://user-images.githubusercontent.com/54521555/81518624-3cde2380-9371-11ea-9941-a2462c8932a6.png)
![LTR{6RK_5P(2T) J~GP~6)4](https://user-images.githubusercontent.com/54521555/81518648-4d8e9980-9371-11ea-9a8a-585a52081358.png)
有没有输出log文件的？

**Comment by dsp2000** [comment]
[a.log](https://github.com/xmake-io/xmake/files/4607268/a.log)

**Comment by waruqi** [comment]
> [a.log](https://github.com/xmake-io/xmake/files/4607268/a.log)

被wasm-ld.exe干扰了 --cross=的探测，导致检测到--cross为wasm-了，所以尝试运行 wasm-clang失败了，我回头改进下，你先手动配置置空--cross=好了，应该就可以了，

```
xmake f -p cross --sdk=xxx --cross= -c
xmake
```

等回头我改进完，你再更新下

**Comment by dsp2000** [comment]
另外一台电脑
![2(V3SW)4{I_1%75EXVW4 U2](https://user-images.githubusercontent.com/54521555/81547812-f3142e00-93ae-11ea-8a2e-a1f46c1c3a91.png)
[b.log](https://github.com/xmake-io/xmake/files/4608817/b.log)

**Comment by dsp2000** [comment]
> > 明白了，现在用dos窗口编译不提示这个了，但vs没有调用 xmake
> > ![%H `D5{BZ_SBPSX6%8DG75Y](https://user-images.githubusercontent.com/54521555/81515819-5f1f7380-9368-11ea-8062-0a46f2cf1129.png)
> vscode的 start Debugging 没有调用xmake, 现在xmake是在命令行操作的
> 没明白你要说什么

**Comment by dsp2000** [comment]
![A V_BOOC3QI`HQ`K~(VG}@C](https://user-images.githubusercontent.com/54521555/81554009-9d448380-93b8-11ea-9d1f-3cf7df4cbc8e.png)
如何实现像这样的定义？
![ITQ@GA9IU6GKIURTE}Y``{I](https://user-images.githubusercontent.com/54521555/81554122-cfee7c00-93b8-11ea-82c1-89bbd84903c1.png)

**Comment by waruqi** [comment]
add_defines

**Comment by waruqi** [comment]
> > [a.log](https://github.com/xmake-io/xmake/files/4607268/a.log)
> 
> 被wasm-ld.exe干扰了 --cross=的探测，导致检测到--cross为wasm-了，所以尝试运行 wasm-clang失败了，我回头改进下，你先手动配置置空--cross=好了，应该就可以了，
> 
> ```
> xmake f -p cross --sdk=xxx --cross= -c
> xmake
> ```
> 
> 等回头我改进完，你再更新下

这个我改进过了，更新到dev版本就行了(xmake update dev)，可以不用置空--cross了，直接：

```console
xmake f -p cross --sdk=/xxx/llvm -c
```

**Comment by dsp2000** [comment]
更新到dev版本 在windows是怎样操作的？我现在是下载release解压的

**Comment by waruqi** [comment]
cmake update dev

**Comment by dsp2000** [comment]
![J2XY(%Z9YJK@Q0EIIVZ4{JW](https://user-images.githubusercontent.com/54521555/81627672-4a5ae280-9431-11ea-8af8-4eb86d0f8ab9.png)

**Comment by dsp2000** [comment]
另外一部电脑
![NX ~`}XEK}B 0MF1`HLGF7I](https://user-images.githubusercontent.com/54521555/81628065-424f7280-9432-11ea-81c0-51fad02e0332.png)

**Comment by dsp2000** [comment]
[c.log](https://github.com/xmake-io/xmake/files/4612877/c.log)
这部电脑没有安装vs的

**Comment by waruqi** [comment]
waiting for xmake to exit ..

之后应该会弹出可视化安装界面，提示用户 点下一步安装的，如果没显示，那就是没更新上。。

或者直接从 ci 上拉取安装包直接装吧

下载这个包 
https://ci.appveyor.com/api/buildjobs/dj2xblh05r05cgkg/artifacts/xmake-installer.exe

**Comment by waruqi** [comment]
我刚看了下，update 不生效确实是之前有个改动导致了一些问题，我已经修复，不过也要重启拉取最新的dev安装包安装后，下次xmake update dev才会正常。 

所以你先从ci上拉取dev安装包装下好了。https://ci.appveyor.com/api/buildjobs/pw5rg4dafhtwqmg6/artifacts/xmake-installer.exe

**Comment by dsp2000** [comment]
![PD47UWEQNPRYQ`CO4}}{0O3](https://user-images.githubusercontent.com/54521555/81636947-b0eafb00-9447-11ea-8bb4-9fe90989296f.png)
[d.log](https://github.com/xmake-io/xmake/files/4613298/d.log)
![PUSC@Q2PIBTQP7Q 3~K8N75](https://user-images.githubusercontent.com/54521555/81637030-e09a0300-9447-11ea-9237-4d3f7b99cc86.png)

**Comment by dsp2000** [comment]
升级后两台电脑结果还是一样

**Comment by waruqi** [comment]
那不可能，我之前用我给你的ci上的安装包测试，完全ok

看你给的log，还是检测到wasm-的Cross，这个只有老代码才会

请先确认下确实已经更新到新版本

xmake --version给我看下

**Comment by dsp2000** [comment]
![%X%SNW $@(98GW{@RW)0WB5](https://user-images.githubusercontent.com/54521555/81647270-51004e80-945f-11ea-8d0b-2085b65be7b8.png)
![DXIX}8HZQI1}TT857I61VZE](https://user-images.githubusercontent.com/54521555/81647526-bce2b700-945f-11ea-94a7-5a6ece3680c4.png)

**Comment by waruqi** [comment]
你手动删下 当前工程下的 .xmake 目录 再重新执行下 配置和编译 试试呢

**Comment by dsp2000** [comment]
删除了
[e.log](https://github.com/xmake-io/xmake/files/4614187/e.log)
.xmake
![PGCIODBVAQUHKP( FGJZZ9S](https://user-images.githubusercontent.com/54521555/81658755-a4789980-946b-11ea-840e-057e88ad46b0.png)

**Comment by waruqi** [comment]
哦 ，你这里测试的是 static library程序，我这边测试的是 binary程序，static似乎是有点问题，我调下

**Comment by waruqi** [comment]
你再更新下试试，仅仅只需要更新下脚本：xmake update -s dev

我稍微做了一些改进和修复：

```console
xmake f -p cross --sdk=/xxx/llvm --sdkname=llvm -c
xmake
```

我新增了一个--sdkname参数，来辅助提示是llvm sdk工具链，应该可以了

后面几天，我会改进下交叉编译这块，对常用的toolchains做更智能的检测，你先这么凑活着用用吧，现在

**Comment by waruqi** [comment]
关于其他常见工具链的支持和改进，之后可以在这个上跟进，后期我会路径完善 https://github.com/xmake-io/xmake/issues/780

现有llvm，你先按我现在的方式 用最新dev试试吧，应该也是可以的

**Comment by waruqi** [comment]
你更新下dev然后用 --toolchain=llvm这个参数 也只是llvm工具链 （因为这版本我会对交叉编译作比较大的重构，来更好的支持各种常用工具链，先定义好参数规范，以免后期再有改动。#780 ）

```console
xmake update -s dev
xmake f -p cross --sdk=/xxx/llvm --toolchain=llvm -c
xmake
```

**Comment by dsp2000** [comment]
![8~MNBM$E}2YTF6X_F~HG~NX](https://user-images.githubusercontent.com/54521555/81779581-925c3100-9527-11ea-8923-787dc6de400f.png)
还是不行，我等你搞好再用吧

**Comment by dsp2000** [comment]
![{)5T04SA)Z~92J9XU96%83F](https://user-images.githubusercontent.com/54521555/82003827-f1d74f80-9693-11ea-80dc-80f0f477c43c.png)
[f.log](https://github.com/xmake-io/xmake/files/4631892/f.log)

**Comment by waruqi** [comment]
我这边没遇到这个问题，不行就根据自己的情况，追加 --cc=/xxx/clang的全路径就行了。。

**Comment by dsp2000** [comment]
你没有用windows试过吧？

**Comment by waruqi** [comment]
> 你没有用windows试过吧？

我就是win10下下的最新llvm测试的。

**Comment by waruqi** [comment]
![Snip20200515_2](https://user-images.githubusercontent.com/151335/82008702-fefa3b80-969f-11ea-8579-88909377cec7.png)

**Comment by dsp2000** [comment]
我这里有两台电脑，一台安装了vs的win7可以用的。另外一台刚好需要用clang的用不了

**Comment by dsp2000** [comment]
configure
{
    plat = cross
    ccache = true
    arch = none
    bin = D:\Program Files\LLVM\bin
    cc = D:\Program Files\LLVM\bin\clang
    mode = release
    ndk_stdcxx = true
    host = windows
    sdk = D:\Program Files\LLVM
    clean = true
    kind = static
    buildir = build
    ar = D:\Program Files\LLVM\bin\llvm-ar
    toolchain = llvm
}
[  5%]: compiling.release main.c
"D:\\Program Files\\LLVM\\bin\\clang" -c -fvisibility=hidden -O3 -Ibuild -I.. -I..\Inc -I..\Src -I..\Src\include -I..\libavcodec -I..\libavutil -I..\libavutil\arm -ID:\Library\kc3x "-ID:\\Program Files\\LLVM\\include" -Qunused-arguments -o build\.objs\WinDecM8c\cross\none\release\.\main.c.o main.c

**Comment by dsp2000** [comment]
现在是xmake 是每次都重新编译的吗？不是已经编译过的只链接？

**Comment by dsp2000** [comment]
如果*.c出错没有做完，就会每次全部编译，否则只是链接。可能需要修正下。
另外target("WinM8c")这样在xmake+vs 是生成WinM8c.exe 在xmake+llvm生成WinM8c， 是问题吗？

**Comment by waruqi** [comment]
> 如果*.c出错没有做完，就会每次全部编译，否则只是链接。可能需要修正下。

gcc vs clang目前xmake都支持头文件依赖处理，不会每次重编，我刚测了下 确认不会重编

> 另外target("WinM8c")这样在xmake+vs 是生成WinM8c.exe 在xmake+llvm生成WinM8c， 是问题吗？

不是问题，不过可以改成.exe

**Comment by dsp2000** [comment]
编译完成删除了中间文件吗？我需要找*.map文件，但没有

**Comment by waruqi** [comment]
> 编译完成删除了中间文件吗？我需要找*.map文件，但没有

build/.deps里面，自己的格式，我会去去提取解析

**Comment by dsp2000** [comment]
没有存在
![D%A6)8TKKXCD{BM21QN{% E](https://user-images.githubusercontent.com/54521555/82117631-d78c9700-97a3-11ea-9f5c-8b1c7c67d42a.png)
![_2CTO(8K1KRRS293%)5J9@M](https://user-images.githubusercontent.com/54521555/82117634-de1b0e80-97a3-11ea-887c-ab36dd6f0f05.png)
![TG_@Z(P4LXJOLK44XOHKGDS](https://user-images.githubusercontent.com/54521555/82117635-e410ef80-97a3-11ea-940b-a57ea77ddfc8.png)
![F@K9K9{NZYVK}FQ`UQFV}Y1](https://user-images.githubusercontent.com/54521555/82117640-ea9f6700-97a3-11ea-8344-02e01e910af3.png)


![N0OJS576Y2K{THMEIB7S9AU](https://user-images.githubusercontent.com/54521555/82117645-f723bf80-97a3-11ea-8732-56b3e40b83c9.png)

**Comment by waruqi** [comment]
这两个.d的不就是么，就是用来分析头文件依赖来实现增量编译的，.map默认不会生成

应该是xmake不会自动设置各种flags，除非用户自己在xmake.lua设置 

如果是msvc 就自己通过add_ldflags设置/map 的flags，如果是 llvm/clang 你自己google下对应flags 通过add_ldflags加上就行了，或者用clang-cl

**Comment by dsp2000** [comment]
configure
{
    arch = none
    ccache = true
    mode = release
    host = windows
    clean = true
    ndk_stdcxx = true
    plat = cross
    sdk = D:\Program Files\LLVM
    bin = D:\Program Files\LLVM\bin
    kind = static
    buildir = build
    ar = D:\Program Files\LLVM\bin\llvm-ar
    toolchain = llvm
}
checking for the clang ... no
checking for the c compiler (cc: clang) ... no
checking for the c compiler (cc: clang) ... no

为什么在这台电脑出错?

**Comment by waruqi** [comment]
不行 就先自己设置下 --cc=xxx/clang --cxx=xxx/clang 编译器全路径

**Comment by dsp2000** [comment]
![WS LNDYLUI7`SQ`QUS{CRF](https://user-images.githubusercontent.com/54521555/82134666-88d70f80-982c-11ea-8f1b-41cc5a0bb3af.png)

**Comment by waruqi** [comment]
自己看下错误么 clang崩了，请先确保clang能在你这台pc上正常运行

**Comment by dsp2000** [comment]
clang好像不能自己在windows安装使用的，需要vs或mingw？

**Comment by dsp2000** [comment]
如果是这样，有什么编译器推荐下？

**Comment by waruqi** [comment]
不知道 没试过 我这都是装了vs的 你可以提个issues给llvm问下

**Comment by dsp2000** [comment]
安装vs算了

**Comment by waruqi** [comment]
可以看下 https://www.zhihu.com/question/268562772 似乎还真没法完全不依赖vs，要么你装mingw好了

**Comment by waruqi** [comment]
或者装intel的编译器 icc，这个应该可以完全独立，不过我还是好久之前用的了 xmake里面还没怎么支持 需要自己挨个设置--cc --cxx --ld 另外这个需要收费的 不过也有x版本 可以找找

**Comment by waruqi** [comment]
除了这些 还有些比较冷门的，但也是完全独立的你可以看看，比如
bcc(borland c++ builder) 
dmc  https://digitalmars.com/ctg/sc.html
watcom什么的

**Comment by waruqi** [comment]
或者可以看看这个 https://github.com/mstorsjo/llvm-mingw

**Comment by waruqi** [comment]
> > 如果*.c出错没有做完，就会每次全部编译，否则只是链接。可能需要修正下。
> 
> gcc vs clang目前xmake都支持头文件依赖处理和增量编译，不会每次重编，我刚测了下 确认不会重编
> 
> > 另外target("WinM8c")这样在xmake+vs 是生成WinM8c.exe 在xmake+llvm生成WinM8c， 是问题吗？
> 
> 不是问题，不过可以改成.exe

我重构好了 详情可以看下 https://github.com/xmake-io/xmake/issues/780

现在工具链和平台做了分离，你可以直接在win平台使用llvm工具链，这样生成的文件后缀就会保持.exe .lib

xmake f --toochain=llvm -c
xmake 

不用特地切到cross平台，除非是交叉编译

可以通过xmake update dev更新到dev试试
