### ISSUE TITLE
arm-linux交叉编译问题

### ISSUE THREAD

**Issue by kof98765** [xmake-io/xmake#783]
按教程操作，--cc不能用，--cross不能用...自动检测又编译不了...

error: invalid argument: --cc=armm-linux-gcc
root@491f4c97a42c:~/lua/ltui# xmake f --root --sdk=/usr/local/arm-2014.05/ [--toolchains=/usr/local/arm-2014.05/bin] --cross=arm-linux-
error: invalid argument: --cross=arm-linux-
root@491f4c97a42c:~/lua/ltui# xmake f --root --sdk=/usr/local/arm-2014.05/ [--toolchains=/usr/local/arm-2014.05/bin] 
checking for the architecture ... x86_64
note: try installing these packages (pass -y to skip confirm)?
in xmake-repo:
  -> lua 5.3.5 
please input: y (y/n)
  => install lua 5.3.5 .. failed                                               
if you want to get verbose errors, please see:
  -> /root/.xmake/cache/packages/2005/l/lua/5.3.5/installdir.failed/logs/install.txt
error: install failed!                                                         
root@491f4c97a42c:~/lua/ltui# /lib/ld-linux.so.3: No such file or directory

root@491f4c97a42c:~/lua/ltui#

**Comment by waruqi** [comment]
ltui这个项目 不支持交叉编译，不是xmake不支持，而是这个ltui这个项目本身 我之前压根没打算支持交叉编译，所以它依赖的 lua/ncurses 库 编译不过的。。

**Comment by waruqi** [comment]
> xmake f --root --sdk=/usr/local/arm-2014.05/ [--toolchains=/usr/local/arm-2014.05/bin]

另外，你也不要完全照搬文档的哈。。好歹自己分析理解下，， [--xxx=xx] 这种一看就不能直接在终端敲得，你还真照贴啊。。

加[-xxx=xx]的意思就是，这是可选的配置参数，根据自己需要追加，xmake f --xxx=xxx 可以加，也可以不加 --xxx=xx

**Comment by kof98765** [comment]
我也试过把[]去掉，反正就是不行。。。看来我得自己交叉编译lua和ncurses了..

**Comment by waruqi** [comment]
> 我也试过把[]去掉，反正就是不行。。。看来我得自己交叉编译lua和ncurses了..

恩，主要是里面lua/ncruses的依赖我之前我就没打算做交叉编译支持，你可以改下xmake.lua，去掉add_requires/add_packages，然后直接改用 add_links/add_incluedirs，然后自己交叉编译lua/ncurses。。理论上是可以的。。

> 而是这个ltui这个项目本身 我之前压根没打算支持交叉编译，所以它依赖的 lua/ncurses 库 编译不过的。。

**Comment by waruqi** [comment]
这个属于ltui的问题，你应该提到ltui/issues，而不是这里。
