### ISSUE TITLE
xmake on Windows 10 re-configures itself when I give it a bad command

### ISSUE THREAD

**Issue by RussellHaley** [xmake-io/xmake#785]
> Note: If it is a 'bug report' or 'feature request', please select the corresponding issue template, otherwise this issue will be not replied. 

### Describe the problem details
Hello, 
Thank you for the help with FreeBSD. 

I am having great sucess with xmake on Windows as well. I am using an LLVM-Mingw compiler toolchain, but I also have Visual Studio 2017.

I have figured out how to configure a build to use my toolchain:
`xmake config -a i686 -p mingw --cc=clang --mingw="C:\program files (x86)\WinLua\WLC"`

However, if I enter a bad command with xmake, it re-configures to use Visual Studio
```
PS C:\Users\russh\git\lmdb\libraries\liblmdb> xmake run mtest2.exe
checking for the architecture ... x64
checking for the Microsoft Visual Studio (x64) version ... 2017
error: unknown target: mtest2.exe
```
Is there any way to stop this from happening?

**Comment by waruqi** [comment]
Ok, I will attempt to fix it.

**Comment by waruqi** [comment]
I have fixed it, you can download dev version and try it again from https://ci.appveyor.com/api/buildjobs/h0cbm5slo55vbykj/artifacts/xmake-installer.exe

**Comment by RussellHaley** [comment]
Brilliant! Thanks so much.
