### ISSUE TITLE
package在windows下的打包文件缺少*.lib

### ISSUE THREAD

**Issue by x1244** [xmake-io/xmake#787]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题
在windows平台下使用`xmake package`，对于项目`foo`，生成安装包`foo.pkg`，在`lib/$(mode)`目录下只拷贝了`foo.dll`，并没有拷贝`foo.lib`。这样在使用这个安装包时，会因为链接库找不到而报错
```
PS C:\workspace\bar> xmake f -c
checking for the architecture ... x64
checking for the Microsoft Visual Studio (x64) version ... 2019
checking for the foo ... no
```
但是有一点我不理解，如果是编译`-p mingw`，那么只有`foo.dll`也是可以链接成功的，请问这是怎么做到的？

手动拷贝`foo.lib`到`bar/pkg/foo.pkg/windows/x64/lib/release`下，再配置和编译则通过。

### 期待的结果

在windows平台上`xmake package`时，连同`foo.lib`一同打包。
windows+vs2019时，还有一个`foo.exp`文件，是否也应该同时打包。

### 错误信息

```
PS C:\workspace\bar> xmake
[ 50%]: compiling.release src\main.cpp
error: main.cpp
src\main.cpp(2): fatal error C1083: 无法打开包括文件: “interface.h”: No such file or directory
```

### 相关环境
win10 VS2019
win10 qt migw32

### 相关配置
`foo/xmake.lua`
```
add_rules("mode.debug", "mode.release")
target("foo")
    set_kind("shared")
    add_files("src/interface.cpp")
    add_headerfiles("src/interface.h")
target("foo_demo")
    set_kind("binary")
    add_deps("foo")
    add_files("src/test.cpp")
```
`bar/xmake.lua`
```
add_rules("mode.debug", "mode.release")
add_packagedirs("pkg")
target("bar")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("foo")
```

**Comment by x1244** [comment]
可能和这个问题类似
https://github.com/xmake-io/xmake/issues/714

**Comment by waruqi** [comment]
> 在windows平台上xmake package时，连同foo.lib一同打包。
windows+vs2019时，还有一个foo.exp文件，是否也应该同时打包。

lib可以package里面加上，exp没必要

> PS C:\workspace\bar> xmake
[ 50%]: compiling.release src\main.cpp
error: main.cpp
src\main.cpp(2): fatal error C1083:

看下pkg里面对应头文件有没有打包进去，执行xmake -v看下完整编译命令，确认下有没有相关-Ixxx指向这个头文件所在目录，可以贴下出来

> 但是有一点我不理解，如果是编译-p mingw，那么只有foo.dll也是可以链接成功的，请问这是怎么做到的？

mingw 我也会生成对应.lib

https://github.com/xmake-io/xmake/blob/ba17a96c48652053a14d37501dff1bc0a334ce45/xmake/modules/core/tools/gcc.lua#L317

**Comment by x1244** [comment]
pkg里有对应头文件，但是因为打包时没有加入`foo.lib`，导致在`xmake f`时`checking for the foo ... no`没有检测到foo包，所以再`xmake build`时会提示`“interface.h”: No such file or directory`。

这时如果手动拷贝`foo.lib`到`foo.pkg/windows/x64/lib/release`下，再配置和编译则通过。所以不是头文件不存在的事，还是因为打包时`foo.lib`没有加进去。

我看到了`mingw`下也生成`.lib`文件，`xmake install`时也完成了安装。我只是奇怪为什么pkg中没有`foo.lib`，在`mingw`下却可以完成编译链接？
如果不用`package`方案，`mingw`编译链接缺少`.lib`是不能通过的。但经过测试，如果没有`foo.lib`，而有`foo.dll`，在`xmake.lua`中如果配置有
```
    add_links("foo")
```
也能通过编译链接，看来是`mingw`和`linux`下一样，`.lib`不是必须的。

**Comment by waruqi** [comment]
我回头会在pkg里面加上的

**Comment by waruqi** [comment]
我加上了，不过没测 你先试试  https://ci.appveyor.com/api/buildjobs/pxl7qqkcaj2yt97a/artifacts/xmake-installer.exe  装这个ci上的dev包

**Comment by x1244** [comment]
OK!搞定，打包成功，可以编译链接。
