### ISSUE TITLE
编译有些c文件使用#include "xx.c"的方式存在不更新的问题

### ISSUE THREAD

**Issue by dsp2000** [xmake-io/xmake#789]
在编译一个库时， aaa.c文件使用#include "bbb.c"的方式加入时，当只更新bbb.c（没有更新aaa.c）
没有检测到bbb.c的更新而导致编译bbb.c。
现在只有在更新aaa.c文件才可以使用新的bbb.c

**Comment by waruqi** [comment]
描述问题的时候，请根据issues的模板提示，详细提供下当前xmake版本，所在系统版本，使用的什么工具链

**Comment by waruqi** [comment]
由于不知道你的具体环境信息，我现在只能假设你用的是vs，我这边测试 vs下 完全正常，可以在bbc.c更新后触发对aaa.c的重编。。linux/mac下也测试正常，没法复现你的问题

如果确实是vs环境，请提供能复现的精简demo给我测试。。如果不是 请提供你的工具链信息

**Comment by dsp2000** [comment]
llvm
[a.log](https://github.com/xmake-io/xmake/files/4642840/a.log)

另外llvm将下面的结构用到0x18字节。就是以64位处理，如何修改为32位的？

typedef struct HuffTable {
    int xsize;
    const uint8_t *bits;
    const uint16_t *codes;
} HuffTable;

**Comment by waruqi** [comment]
> llvm
a.log

我这里测试llvm，编辑bbb.c也能正常触发aaa.c的重编，并没发现什么问题，没法复现。

> 另外llvm将下面的结构用到0x18字节。就是以64位处理，如何修改为32位的？

自己google下吧。把llvm对应x86编译模式的flags传入xmake f --cxflags="" --ldflags="" --arflags=""

比如-m32什么的。。

目前自定义的交叉工具链走的是通用模式，不会去处理arch，因为不同工具链的arch模式都不同，未知编译器没法走分别处理，你只能自己传flags进去

如果要内置llvm工具链支持分arch，只能等：https://github.com/xmake-io/xmake/issues/780 这个我重构完才行了，至少还需要一两周的时间。

**Comment by waruqi** [comment]
dev上我支持对llvm/arch处理了

```console
xmake f -p cross -a i386 --toolchain=llvm --sdk=/xxxxxx
```

指定-a i386就会切到 -m32 编译
