### ISSUE TITLE
xcode.application 类型的 target 运行提示找不到依赖的dylib

### ISSUE THREAD

**Issue by TopXX** [xmake-io/xmake#790]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题

xcode.application 类型的 target 编译后无法运行，提示找不到依赖的dylib。

### 期待的结果

xcode.application 类型的 target 编译后，需要将依赖的dylib复制到app/Contents/MacOS/目录下。

### 错误信息

Termination Reason:    DYLD, [0x1] Library missing

> 如果是xmake相关编译问题，请加上`-v -D`参数运行，并给出详细编译输出信息。

### 相关环境

xmake 2.3.3、macOS Catalina

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by waruqi** [comment]
嗯，这个版本会排期支持上

**Comment by waruqi** [comment]
我支持上了，并且改进了xmake run对macapp的支持

**Comment by waruqi** [comment]
测试example: https://github.com/xmake-io/xmake/tree/dev/tests/projects/objc/macapp_with_shared

**Comment by TopXX** [comment]
我这边有个小失误或误导，dylib应该放在 frameworks 目录下，而不是 MacOS 目录，sorry！

**Comment by waruqi** [comment]
现在放macos不能用？

**Comment by TopXX** [comment]
可以正常使用，但是我看了好多app，好像都是放frameworks目录下的。

**Comment by waruqi** [comment]
那是依赖的 framework类型的target才会，不过framework的依赖copy我还没整
