### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake#791]
README.md开始处的一句话：
The project focuses on making development and building easier and provides many features

README_zh.md中为：
xmake的目标是开发者更加关注于项目本身开发

以英文为准还是以中文为准？

**Comment by waruqi** [comment]
en文水平不行，我随便写的 这就不要纠结了

**Comment by playgithub** [comment]
那我看中文了

**Comment by waruqi** [comment]
恩 文档也是中文写的，用google翻译的en文，建议能看中文的直接看中文
