### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by RussellHaley** [xmake-io/xmake#793]
### Describe the problem details
Hello, 

I have some questions for which I could not find solutions from the documentation. I've sent you a small token of appreciation. If any of these questions are reasonable answered in the documentation, then feel free to just point me to the information.

- Can I set a global install dir on windows (e.g. `C:\Program Files (x86)\` )?

- how do I access the arch/platform and other build specific information from within the xmake script?
	Similarly, I saw in the examples a magic $(buildDir). Are those built in substitutions? (I tried it in a script and it failed).

- I'd like to execute an external command: llvm-dlltool. Is os.exec the best method? Should I create a task? I am using the tool to create a *.lib file. How do I add the output from the command to the build directory for linking with my target?

- Is there a way to glob files from all subdirs? e.g. `c:\mydir\*\*.c`

- I noted that some functions only accept strings (I don't remember which ones I tried). No tables?

- There is no require()? I'm not sure if that's a luajit thing? How do I get access to the filesystem? external lua Modules?

- What if I would like to change default extensions? For instance, I prefer using *.a for static libraries. 
I posit that I will need to build from source.

- I have been creating variables and lua procedural code in the xmake.lua file. I noted once when I added a print statement that the file gets executed several times. Is creating variables and procedures a bad idea?
``` lua
local paths = {}
paths.PGF32 = "C:/Program Files (x86)/"
paths.PGF64 = "C:/Program Files/"
paths.LUABIN = paths.PGF32.."WinLua/Lua/5.3/bin"
paths.LUAINC = paths.PGF32.."WinLua/Lua/5.3/include"
paths.LUALIB = paths.PGF32.."WinLua/Lua/5.3/lib/lua/5.3/"

...

local function add_lua()
	add_includedirs(paths.LUAINC)
    add_linkdirs(paths.LUABIN)
    add_links("lua53")
end
...

--Build the AssertsTest library
target("libAssertTests")
	set_kind("shared")
	set_installdir(install_dir)
	add_lua()  --< Does this cause problems or get added many times?
	add_syslinks("winpthread")
```

- Finally, if I passed on an xmake file via email, would you be willing to review it and give me feedback? For another small token of appreciation of course. I quite like having the freedom to ask some questions and offer remuneration, it relieves me of guilt!

**Comment by waruqi** [comment]
> ### Describe the problem details
> Hello,
> 
> I have some questions for which I could not find solutions from the documentation. I've sent you a small token of appreciation. If any of these questions are reasonable answered in the documentation, then feel free to just point me to the information.
> 
> * Can I set a global install dir on windows (e.g. `C:\Program Files (x86)\` )?

You can use set_installdir or custom on_install script.

```lua
target("test")
    set_installdir("xxx")
```

Or 

```lua
target("test")
    on_install("windows", function (target)
        os.cp(target:targetfile(), "xxx/")
    end)
```

Or run command: `xmake install -o /xxx/installdir`

> * how do I access the arch/platform and other build specific information from within the xmake script?

In description scope:

We can uses get_config, is_arch, is_plat, is_host, or `$(arch)`, `$(host)` and `$(plat)` builtin vars.

```lua
target("test")
    if is_plat("windows") then
        add_defines("xxx")
    end
    if is_arch("x64", "arm") then
        add_defines("$(arch)")
    end
    -- Or
    if get_config("plat") == "linux" then
    end
```

In script scope:

We can also use get_config, is_arch, is_plat, is_host, or `$(arch)`, `$(host)` and `$(plat)` builtin vars.

and we can uses more module and interfaces. e.g. os.host(), config.arch(), config.get("arch") 

```lua
target("test")
    after_install(function (target)
        import("core.project.config")
        print(os.host())
        print(get_config("plat"))
        print(config.get("plat"))
        print(config.get("buildir"))
        print("$(arch)")
    end)
```

>   Similarly, I saw in the examples a magic $(buildDir). Are those built in substitutions? (I tried it in a script and it failed).

```lua
target("test")
    add_includedir("$(buildir)/xxx")
    after_install(function (target)
        print(get_config("buildir"))

        --import("core.project.config")
        --print(config.get("buildir"))

        -- get target directory
        print(target:targetdir())
    end)
```

> * I'd like to execute an external command: llvm-dlltool. Is os.exec the best method? Should I create a task? I am using the tool to create a *.lib file. How do I add the output from the command to the build directory for linking with my target?

like this?

```lua
target("xxx")
    set_kind("static")
    after_link("windows", function (target)
          os.exec("llvm-dlltool %s", target:targetfile()) -- for .lib target?
          -- os.execv("llvm-dlltool", {target:targetfile()}, {envs = {PATH = "xxx"}})

          --If we want to get output, we can use os.iorun or os.iorunv:
          local stdout, stderr = os.iorun("llvm-dlltool ...")
    end)
```

> * Is there a way to glob files from all subdirs? e.g. `c:\mydir\*\*.c`

```lua
target("test")
    add_files("src/**.c") -- recursive subdirs
    on_load(function (target)
         -- recursive: **
         -- not recursive: *, e.g. src/*/*.c
         for _, filepath in ipairs(os.files("c:/mydir/**.c")) do
              print(filepath)
         end

         -- only dirs
         -- os.dirs("src/**")

         -- file and dirs
         --os.filedirs("src/**")
    end)
```

> * I noted that some functions only accept strings (I don't remember which ones I tried). No tables?

Most configuration interfaces are string lists.

```lua
add_files("src/*.c", "test/*.c")
add_defines("xx", "dd", "yy")
```

> * There is no require()? I'm not sure if that's a luajit thing? How do I get access to the filesystem? external lua Modules?

We can use the built-in file system interface of xmake to handle most things. you can see https://xmake.io/#/manual/builtin_modules?id=ioopen

```lua
os.filedirs
os.files
f = io.open("a.txt", 'r')
if f then
    f:write("xxx")
    f:print("%s", "hello")
    f:close()
end
a = io.readfile("a.txt")
io.writefile("a.txt", "data")
```

And we can uses `import` api to import external modules and xmake's extension modules. you can see 
https://xmake.io/#/manual/builtin_modules?id=import
https://xmake.io/#/manual/global_interfaces?id=add_moduledirs

projectdir/modules/mymodule.lua
projectdir/modules/mymodule3.lua
projectdir/modules/subdir/mymodule2.lua

```lua
add_moduledirs("$(projectdir)/modules")
target("test")
     after_run(function (target)
          import("mymodule")
          import("subdir.mymodule2")
          mymodule() -- call main()
          mymodule2.hello() -- call hello() interfaces
     end)
```

mymodule.lua

```lua
import("mymodule3")
function main()
end
```

mymodule2.lua

```lua
function hello()
end
```

> * What if I would like to change default extensions? For instance, I prefer using *.a for static libraries.

```lua
target("test")
    set_filename("libtest.a")
```

>   I posit that I will need to build from source.

?

> * I have been creating variables and lua procedural code in the xmake.lua file. I noted once when I added a print statement that the file gets executed several times. Is creating variables and procedures a bad idea?

Please write complex code logic in the script scope(e.g. on_xxx, after_xxx, before_xxx), the description scope is only used for simple configuration.

script scope:

```lua
target("test")
    before_build(function (target)
        print("xxx") -- only print once
    end)
```

you can see https://xmake.io/#/guide/syntax_description?id=configuration-separation

> 
> ```lua
> local paths = {}
> paths.PGF32 = "C:/Program Files (x86)/"
> paths.PGF64 = "C:/Program Files/"
> paths.LUABIN = paths.PGF32.."WinLua/Lua/5.3/bin"
> paths.LUAINC = paths.PGF32.."WinLua/Lua/5.3/include"
> paths.LUALIB = paths.PGF32.."WinLua/Lua/5.3/lib/lua/5.3/"
> 
> ...
> 
> local function add_lua()
> 	add_includedirs(paths.LUAINC)
>     add_linkdirs(paths.LUABIN)
>     add_links("lua53")
> end
> ...
> 
> --Build the AssertsTest library
> target("libAssertTests")
> 	set_kind("shared")
> 	set_installdir(install_dir)
> 	add_lua()  --< Does this cause problems or get added many times?

yes, It will be parsed and executed multiple times in the description field, usually only used to set the read-only configuration.

Or you can try

```lua
target("libAssertTests")
    on_load(function (target)
         -- only run once and you can do more complex configuration logic
         target:add("includedirs", "xxx")
         target:add("links", "lua53")
         target:add("linkdirs", "xxxx")
    end)
```

> 	add_syslinks("winpthread")
> ```
> 
> * Finally, if I passed on an xmake file via email, would you be willing to review it and give me feedback? For another small token of appreciation of course. I quite like having the freedom to ask some questions and offer remuneration, it relieves me of guilt!

If I have time, I will do some review and improvement for your xmake.lua, but maybe I will not reply immediately because my spare time is not much.

**Comment by RussellHaley** [comment]
You are a gentleman and a scholar. Thank you for your feedback, I will continue to review.

> If I have time, I will do some review and improvement for your xmake.lua, but maybe I will not reply immediately because my spare time is not much.

"If you want something done, ask a busy person." ~ Benjamin Franklin.

**Comment by waruqi** [comment]
Ok, I closed this issue first, if there are other problem, please open a new issue.

Thanks!
