### ISSUE TITLE
xmake f配置保存在那里？

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake#794]

**Comment by waruqi** [comment]
这个你要知道来干嘛，切记千万别直接从这个里面去取私有配置数据作为正式场景使用，如果只是研究性质，可以执行下面的命令查看

 xmake l core.project.config.filepath

**Comment by playgithub** [comment]
目前觉得xmake不错，打算深入学习，如果有好的想法肯定PR

**Comment by waruqi** [comment]
ok
