### ISSUE TITLE
xmake run -d 能不能制定调试程序

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake#795]
clang++编译，有时候lldb调试不了，gdb可以，默认选择了lldb

**Comment by waruqi** [comment]
这个你切下默认的调试器到gdb不就好了。。

xmake f --debugger=gdb
xmake run -d

也可以配置到全局设置，避免每次切换配置

xmake g --debugger=gdb

**Comment by playgithub** [comment]
`xmake f -h` 里有，粗心了，找了一下没找到。
谢谢
