### ISSUE TITLE
vsxmake project.

### ISSUE THREAD

**Issue by ankitkk** [xmake-io/xmake#799]
### Is your feature request related to a problem? Please describe.
yes - usability of generated C++ visual studio project

### Describe the solution you'd like
Generated project has no concept of header files - it lists files added via add_files which makes sense, but I can't add .H files. I am not sure what the solution is - maybe a default .H rule which does nothing? so it shows up in the project but not compiled directly ? and everything works

**Comment by waruqi** [comment]
you can use add_headerfiles(), see https://xmake.io/#/manual/project_target?id=targetadd_headerfiles

add_files only for compiling source files.

**Comment by ankitkk** [comment]
Oh thank you.
