### ISSUE TITLE
头文件和链接库搜索路径设定方式问题

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake#801]
头文件和链接库搜索路径只能通过`xmake f`指定吗？
是不是放到`xmake.lua`里面更好：
- 方便编辑
- 根据条件设定不同值

BTW，如果不要`xmake f`，都放到`xmake.lua`，会不会更好？

**Comment by waruqi** [comment]
> 头文件和链接库搜索路径只能通过`xmake f`指定吗？
> 是不是放到`xmake.lua`里面更好：
> 
> * 方便编辑
> * 根据条件设定不同值
> 
> BTW，如果不要`xmake f`，都放到`xmake.lua`，会不会更好？

仔细看文档哈，https://xmake.io/#/zh-cn/manual/project_target?id=targetadd_includedirs

原本就是add_includedirs, add_links, add_linkdirs在xmake.lua里面配置的，`xmake f --includedirs=`只是提供给用户临时追加一些配置的灵活性和便利性而已。

这种是基础配置哈，xmake.lua里面不支持那还搞啥~

**Comment by playgithub** [comment]
我还找了很久文档，居然没找到
谢谢

**Comment by waruqi** [comment]
文档站左上角有全文搜索的
