### ISSUE TITLE
xmake install默认空操作？

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake#806]
xmake.lua没有on_install
```
# xmake install
installing lua_shared_lib ..
installing lua ..
installing lua_static_lib ..
installing luac ..
install ok!
```
空操作？

**Comment by waruqi** [comment]
windows默认系统安装还没实现(C盘安装得需要权限，安装到其他目录，还得设置系统path env，懒得搞)，你可以 xmake install -o xxx安装到指定目录

目前只有非win上，可以直接装到/usr/local/bin

**Comment by waruqi** [comment]
或者你自己实现on_install也可以

**Comment by playgithub** [comment]
> windows默认系统安装还没实现(C盘安装得需要权限，安装到其他目录，还得设置系统path env，懒得搞)，你可以 xmake install -o xxx安装到指定目录

没有没问题，就是提示有点迷惑

> 目前只有非win上，可以直接装到/usr/local/bin

这个默认可以的
