### ISSUE TITLE
fatal error LNK1170: 命令文件中的行包含 131071 个或更多字符

### ISSUE THREAD

**Issue by yanghuan** [xmake-io/xmake#812]
错误输出信息如下，操作系统win10, xmake 版本xmake v2.3.3+202004261017

error: Microsoft (R) Incremental Linker Version 14.26.28805.0
Copyright (C) Microsoft Corporation.  All rights reserved.

C:\Users\YangHuan\AppData\Local\Temp\.xmake\200526\_A2506E069DF84D89938E1E5EE61BBAC6.args.txt : fatal error LNK1170: 命令文件中的行包含 131071 个或更多字符

The terminal process terminated with exit code: 1

我搜索了下原因，好像文件需要分割一下
https://developercommunity.visualstudio.com/content/problem/441978/fatal-error-lnk1170-line-in-command-file-contains.html

**Comment by waruqi** [comment]
我回头处理下

**Comment by waruqi** [comment]
我dev上改进过了，等半小时ci上跑完后，你执行xmake update dev更新下到dev版本再试试。

**Comment by yanghuan** [comment]
好的，感谢！

**Comment by yanghuan** [comment]
更新至 xmake v2.3.3+202005261535，有如下输出

[ 99%]: linking.debug outcpp.exe
error: ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:47: 
stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:788: in function 'raise'
        ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:47: in function 'co_start_named'
        @programdir\modules\private\async\runjobs.lua:185: in function <@programdir\modules\private\async\runjobs.lua:144>
        [C]: in function 'trycall'
        @programdir\core\base\scheduler.lua:423: in function 'co_group_begin'
        ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:85: in function 'co_group_begin'
        @programdir\modules\private\async\runjobs.lua:144: in function 'runjobs'
        @programdir\actions\build\build.lua:221: in function 'build'
        @programdir\actions\build\main.lua:116: in function <@programdir\actions\build\main.lua:111>
        [C]: in function 'trycall'
        @programdir\core\sandbox\modules\try.lua:121: in function 'try'
        @programdir\actions\build\main.lua:110: in function <@programdir\actions\build\main.lua:83>
        [C]: in function 'load'
        @programdir\core\base\task.lua:520: in function 'run'
        @programdir\core\main.lua:281: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>
The terminal process terminated with exit code: 1

**Comment by yanghuan** [comment]
重新rebuild已经成功，感谢修正
