### ISSUE TITLE
特定情况，文档点击目录项，目录内容定位错误

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake#813]
重现：

1. 通过目录，定位到“快速入门/工程例子”，https://xmake.io/#/zh-cn/guide/project_examples
2. 滚动目录到“快速入门/配置说明”，如图
![image](https://user-images.githubusercontent.com/3665590/82902763-8a25dc00-9f92-11ea-9ccb-75bc444c0487.png)
3. 点击“配置说明”，目录定位错误，如图：
![image](https://user-images.githubusercontent.com/3665590/82903036-f1439080-9f92-11ea-9c56-e055d3eb371e.png)

**Comment by waruqi** [comment]
我这里测试正常，清下cache试试吧 或者换个浏览器， 不行我也没办法，文档站也是用的别人的现成的docsify框架，真有问题 我也改不了

**Comment by playgithub** [comment]
试了edge也不行，同样的问题。估计是点“快速入门/配置说明”后“快速入门/工程例子”自动折叠，导致定位不对

**Comment by waruqi** [comment]
这个我也没办法 要么你提到docsify的issues上去

**Comment by playgithub** [comment]
OK

**Comment by OpportunityLiu** [comment]
我这里也有这个问题啊

**Comment by playgithub** [comment]
提交到docsify了，https://github.com/docsifyjs/docsify/issues/1202

**Comment by waruqi** [comment]
这个这里先close了 到docsify上跟进就好了
