### ISSUE TITLE
protobuf例子问题

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake#814]
```lua
add_requires("protobuf-cpp")

target("console_c++")
    set_kind("binary")
    set_languages("c++11")

    add_packages("protobuf-cpp")

    add_files("src/*.cpp")
    add_files("src/*.proto", {rules = "protobuf.cpp"})
```
两个疑问：

- `add_files("src/*.proto", {rules = "protobuf.cpp"})`这句生成的.cpp会通过上一句`add_files("src/*.cpp")`加入到编译里面吗？
- protobuf源文件改动以后能保证每次编译都是对应最新的protobuf源文件吗？

**Comment by waruqi** [comment]
> add_files("src/*.proto", {rules = "protobuf.cpp"})这句生成的.cpp会通过上一句add_files("src/*.cpp")加入到编译里面吗？

你编译试下不就知道了，会参与编译，但不是加入上面那句配置

> protobuf源文件改动以后能保证每次编译都是对应最新的protobuf源文件吗？

还是那句话，这种你直接试试不就立马出结果了么

**Comment by playgithub** [comment]
如果一看就知道就更好了
