### ISSUE TITLE
qt console项目崩溃问题

### ISSUE THREAD

**Issue by vkensou** [xmake-io/xmake#817]
创建了一个简单的qt console 项目，在debug下运行会崩溃。
qt 版本是 5.11.1  msvc2017_64
文件如下：
xmake.lua：
```
add_rules("mode.debug", "mode.release")
target("test")
    add_rules("qt.console")
    add_files("src/*.cpp")
```
src/test.cpp
```
#include <QTextStream>
int main(int argc, char *argv[])
{
	QTextStream cout(stdout, QIODevice::WriteOnly);
	cout << "a";
	return 0;
}
```

只要用 cout 输出任何内容都会崩溃，不输出不会崩溃。
我用vs2017 手动创建一个一样的工程也是会崩溃。
但是用vs 的qt插件创建的就没有问题。感觉可能是少了什么配置。

**Comment by waruqi** [comment]
这个你先自己调下吧，我暂时没qt/win环境，磁盘没空间了。  可以看看依赖的qt dll是否被正常加载，如果缺少相关path，可以先自己在xmake.lua里面通过 add_runenvs 设置一些需要的path

https://xmake.io/#/zh-cn/manual/project_target?id=targetadd_runenvs

**Comment by vkensou** [comment]
经过研究发现，手动创建的vs工程崩溃是因为错链接了release版qtdll。。。

但是xmake生成的工程还是有问题，具体表现是这样的：
第一次运行会报错：未加载ntdll.pdb
设置了pdb服务器之后，下载了ntdll.pdb
又报错：无可用源    怀疑是因为没有qt 的debug版 pdb导致的

我疑惑的是为啥xmake生成的工程非得加载pdb
我手动创建的vs工程并不需要加载pdb就可以正常运行

**Comment by waruqi** [comment]
你可以执行xmake -v 看下完整编译命令行，然后跟vs->设置->高级里面，编译和链接的 完整命令行参数做下对比。。

理论上pdb缺失应该不影响运行才对，顶多是断点和调试时候符号找不到。。只要dll什么正常加载就行。。

**Comment by vkensou** [comment]
我找到原因了
原来是vs_runtime的问题，设置为MD就好了。
但是我在文档中没有找到target域下如何设置 vs_runtime，请问如何在target里设置这个值呢？

**Comment by waruqi** [comment]
> 但是我在文档中没有找到target域下如何设置 vs_runtime，请问如何在target里设置这个值呢？

vs/gcc各种编译器flags这么多，xmake不可能每个都给个api设置，直接用 add_cxflags设置下不就好了，具体看下文档说明

add_cxflags("/MD")

**Comment by vkensou** [comment]
谢谢你，问题解决了

**Comment by waruqi** [comment]
ok
