### ISSUE TITLE
通过add_files添加静态库libfmt.a不起作用

### ISSUE THREAD

**Issue by Frandy** [xmake-io/xmake#818]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题
写了一个简单的程序使用boost和fmt库，在xmake.lua里面通过add_files添加了libboost_filesystem.a和libfmt.a， 链接时提示libfmt里面的函数未定义，然而直接使用g++  加上这两个lib, 是可以编译过的. 
通过xmake -v, 可以看到link时只添加了libboost_filesystem.a相关的内容，没有libfmt.a相关的内容.

xmake.lua的内容

```--arts_third_part 是定义过的一个变量
set_languages("cxx14")
add_includedirs(arts_third_part.."source/boost_1_73_0")
add_files(arts_third_part.."source/boost_1_73_0/stage/lib/libboost_filesystem.a")

add_includedirs(arts_third_part.."fmt/include")
add_files(arts_third_part.."fmt/lib/libfmt.a")

-- add modes: debug and release
add_rules("mode.debug", "mode.release")

-- add target
target("test")
    -- set kind
    set_kind("binary")
    -- add files
    add_files("*.cpp")
    add_files("../ProgramInfo.cpp")
        add_includedirs("..")
```

### 期待的结果

能够添加上fmt库，编译通过

### 错误信息

configure
{
    arch = x86_64
    ccache = true
    mode = release
    ndk_stdcxx = true
    plat = linux
    kind = static
    buildir = build
    cxx = g++
    ld = /usr/bin/g++
    host = linux
}
[ 83%]: linking.release test
/usr/bin/g++ -o build/linux/x86_64/release/test build/.objs/test/linux/x86_64/release/./testProgramInfo.cpp.o build/.objs/test/linux/x86_64/release/__/ProgramInfo.cpp.o build/.objs/test/linux/x86_64/release/__/__/__/__/__/arts_third_part/source/boost_1_73_0/stage/lib/libboost_filesystem.a.o.dir/codecvt_error_category.o build/.objs/test/linux/x86_64/release/__/__/__/__/__/arts_third_part/source/boost_1_73_0/stage/lib/libboost_filesystem.a.o.dir/directory.o build/.objs/test/linux/x86_64/release/__/__/__/__/__/arts_third_part/source/boost_1_73_0/stage/lib/libboost_filesystem.a.o.dir/exception.o build/.objs/test/linux/x86_64/release/__/__/__/__/__/arts_third_part/source/boost_1_73_0/stage/lib/libboost_filesystem.a.o.dir/operations.o build/.objs/test/linux/x86_64/release/__/__/__/__/__/arts_third_part/source/boost_1_73_0/stage/lib/libboost_filesystem.a.o.dir/path.o build/.objs/test/linux/x86_64/release/__/__/__/__/__/arts_third_part/source/boost_1_73_0/stage/lib/libboost_filesystem.a.o.dir/path_traits.o build/.objs/test/linux/x86_64/release/__/__/__/__/__/arts_third_part/source/boost_1_73_0/stage/lib/libboost_filesystem.a.o.dir/portability.o build/.objs/test/linux/x86_64/release/__/__/__/__/__/arts_third_part/source/boost_1_73_0/stage/lib/libboost_filesystem.a.o.dir/unique_path.o build/.objs/test/linux/x86_64/release/__/__/__/__/__/arts_third_part/source/boost_1_73_0/stage/lib/libboost_filesystem.a.o.dir/utf8_codecvt_facet.o build/.objs/test/linux/x86_64/release/__/__/__/__/__/arts_third_part/source/boost_1_73_0/stage/lib/libboost_filesystem.a.o.dir/windows_file_codecvt.o -s -m64 -L/usr/local/lib -L/usr/lib
error: @programdir/modules/private/async/runjobs.lua:213: @programdir/actions/build/kinds/binary.lua:89: @programdir/core/sandbox/modules/os.lua:258: /usr/bin/ld: build/.objs/test/linux/x86_64/release/./testProgramInfo.cpp.o: in function `fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char>::on_error(char const*) [clone .isra.0]':
testProgramInfo.cpp:(.text+0x1f): undefined reference to `fmt::v6::internal::error_handler::on_error(char const*)'

### 相关环境

xmake 2.3.3
WSL Ubuntu 
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

### 其他信息
g++ testProgramInfo.cpp ../ProgramInfo.cpp ../ProgramInfo.h -std=c++14 ../../../../../arts_third_part/fmt/lib/libfmt.a -I../../../../../arts_third_part/fmt/include/ -I../../../../../arts_thi
rd_part/source/boost_1_73_0/ ../../../../../arts_third_part/source/boost_1_73_0/stage/lib/libboost_filesystem.a -o test
这样直接编译，是可以通过的.

**Comment by waruqi** [comment]
仔细看文档，add_files仅用于添加参与编译的源文件，.a这种请通过add_links/add_linkdirs添加

add_files("*.a")仅用于静态库的merge，也就是抽取.a到.o，然后重新打包合并

**Comment by Frandy** [comment]
哦，我看到有一个地方是用add_files添加静态库，就这样用了，谢谢指正啊。
我用过add_links, 只是遇到一个问题，目录下面同时有静态库和动态库，add_links会使用动态库，但是我想link静态库。这个怎么指定呢？

**Comment by waruqi** [comment]
不同目录存放，或者通过add_ldflags("libxxx.a", {force = true}) 写全ldflags试试

**Comment by Frandy** [comment]
试了一下add_ldflags("libxxx.a", {force = true}) , 不起作用或许还是得把目录分开

**Comment by Frandy** [comment]
用add_ldflags(full_lib_path)这样也可以，先这样用了，谢谢
