### ISSUE TITLE
升级到2.3.3以后qt程序编译找不到ui_xxx.h文件

### ISSUE THREAD

**Issue by buaayhq** [xmake-io/xmake#821]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题

我从xmake2.2.8升级到2.3.3之后发现之前能正常编译的qt程序报找不到ui_xxxx.h的文件

### 期待的结果

能够正常编译

### 错误信息

如果可能，请尽量附加程序运行过程中的错误输出信息。

> 如果是xmake相关编译问题，请加上`-v -D`参数运行，并给出详细编译输出信息。

### 相关环境

xmake 版本：2.3.3
编译环境：windows 10 vs2017 qt5.9.6

### 其他信息

错误信息：
\windows\x64\release\rules\qt\moc\../../../.\moc\moc_mprtest.cpp.obj build\.gens\xx\windows\x64\release\rules\qt\moc\moc_mprtest.cpp./../../../../../xxx/xxx/mprtest.h(4): fatal error C1083: 无法打开包括文件: “ui_mprtest.h”: No such file or directory

**Comment by waruqi** [comment]
你更新到 dev 版本试试呢，看看是否还有同样的问题。xmake update dev

**Comment by buaayhq** [comment]
dev版本可以正常编译，谢谢
