### ISSUE TITLE
add_packages("protobuf-cpp") 下载失败

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake#824]
文档里的列子
```lua
add_requires("protobuf-cpp")

target("test")
    set_kind("binary")
    set_languages("c++11")

    add_packages("protobuf-cpp")

    add_files("*.cpp")
    add_files("proto/*.proto", {rules = "protobuf.cpp"})
```

```
> xmake
checking for the architecture ... x64
checking for the Microsoft Visual Studio (x64) version ... 2019
note: try installing these packages (pass -y to skip confirm)?
in xmake-repo:
  -> protobuf-cpp 3.8.0
please input: y (y/n)

  => download https://github.com/protocolbuffers/protobuf/releases/download/v3.8.0/protobuf-cpp-3.8.0.zip .. failed
error: download failed!
```

add_packages和add_requires一样也会远程下载？有什么区别？
这个例子也依赖7z，7z下载成功了，工程目录下找不到，下载到哪里了？
7z是开了代理秒下的，开代理通过浏览器下载[https://github.com/protocolbuffers/protobuf/releases/download/v3.8.0/protobuf-cpp-3.8.0.zip]()也是秒下，开代理xmake一直提示
```
=> downloading protobuf-cpp .. (1/curl)
```

**Comment by waruqi** [comment]
xmake也是调用的curl下载，下载失败通常是网络问题，你可以xmake -v执行看下实际的包下载存储路径，然后自己下载后放置进去

> add_packages和add_requires一样也会远程下载？有什么区别？

add_requires全局设置需要的packages依赖，以及设置版本和配置信息，然后下载

add_packagr对指定的target生效，包括links linkdirs，并不是下载了 所有target都会自动集成

具体详情看文档 https://xmake.io/#/zh-cn/manual/global_interfaces?id=add_requires

https://xmake.io/#/zh-cn/manual/project_target?id=targetadd_packages


这个例子也依赖7z，7z下载成功了，工程目录下找不到，下载到哪里了？

xmake require --info 7z

**Comment by playgithub** [comment]
刚才开了代理忽然能下载了。
有个小问题，既然add_package能自动下载需要的依赖，为什么还要add_requires?

**Comment by waruqi** [comment]
> 刚才开了代理忽然能下载了。
> 有个小问题，既然add_package能自动下载需要的依赖，为什么还要add_requires?

仔细看我刚说的，我哪说add_packages能下载了？

> add_requires全局设置需要的packages依赖，以及设置版本和配置信息，然后下载

**Comment by playgithub** [comment]
对的，这样就清楚了，谢谢。

**Comment by playgithub** [comment]
xmake成功，可以运行了。
然后`xmake p`，安装过的protobuf-cpp没了，通过`xmake require --info protobuf-cpp`找到cachedir和installdir，都为空，这是什么情况？

**Comment by waruqi** [comment]
xmake p 不会去干扰packages 两个完全没关系。

**Comment by playgithub** [comment]
是啊，忽然就被清空了，7z还在

**Comment by playgithub** [comment]
手动下载`protobuf-cpp-3.8.0.zip`，copy到`AppData\Local\.xmake\cache\packages\2006\p\protobuf-cpp\3.8.0`
然后xmake成功，但是`AppData\Local\.xmake\packages\p\protobuf-cpp\3.8.0\aa7fbd80abda4d1a97f445168f6f3c1d`是空的

**Comment by waruqi** [comment]
如果xmake编译成功，说明还是在的 不然也不可能编译link通过 估计在其他目录 自己找找吧 或者 xmake -v看下

**Comment by playgithub** [comment]
没有protobuf源文件，只有一个HelloWorld cpp文件，现在如果cache没有zip，`xmake`就会下载，如果手动拷一个zip过去，`xmake`不会解压，可能是因为build用不到吧，明天价格proto文件试试。

**Comment by playgithub** [comment]
`add_files`加了protobuf源文件，`xmake`就安装protobuf-cpp了，否则就算`add_requires("protobuf-cpp")`，也只是下载zip不安装，有点智能。（PS：由于下载不了，手动下载拷贝到cache目录里）
