### ISSUE TITLE
protobuf-cpp 支持目录结构吗？

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake#827]
```
proto-files
    a.proto
    common-files
        b.proto
```
其中`a.proto` `import "common-files/b.proto"`

xmake.lua
```lua
add_files("proto-files/**.proto", {rules = "protobuf.cpp"})
```

`xmake`时报错
> a.pb.cc can not open include file: `common-files/b.pb.h`

`.gens`目录下a.pb.*和b.pb.*在同一级，xmake处理protobuf是可以保持目录结构吗？

**Comment by waruqi** [comment]
目前还不支持
