### ISSUE TITLE
add_packages支持debug / release吗？

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake#830]
`add_packages`会自动为编译器添加include lib等依赖，我习惯build release时链接release库，build debug时链接debug库，`add_package`支持吗？

**Comment by waruqi** [comment]
https://xmake.io/#/zh-cn/package/remote_package?id=%e4%bd%bf%e7%94%a8%e8%b0%83%e8%af%95%e7%89%88%e6%9c%ac%e7%9a%84%e5%8c%85

**Comment by playgithub** [comment]
看不明白才问的，我再研究一下

**Comment by playgithub** [comment]
```
add_requires("tbox", {debug = true})
add_packages("tbox")
```
这样会使用debug版？

---

```
add_requires("tbox", {debug = false})
add_packages("tbox")
```
这样会使用release版？

---

如果这样，`add_requires`没问题，`add_packages`参数相同怎么知道链接debug还是release?

**Comment by waruqi** [comment]
add_packages就是引用的add_requires里面的设置

**Comment by playgithub** [comment]
可以的，这样简洁
