### ISSUE TITLE
add_requires实现在哪里？

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake#831]
找了一下，没找到

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/blob/master/xmake/actions/require/install.lua

**Comment by playgithub** [comment]
基本看不懂，应该是[https://github.com/xmake-io/xmake/blob/master/xmake/actions/require/search.lua]()里面更新xmake-io/xmake-repo，然后关联吧

**Comment by waruqi** [comment]
不是 这个一两句话说不清楚  反正都在那个目录下 你自己研究下吧

**Comment by playgithub** [comment]
OK
