### ISSUE TITLE
set_urls / add_urls 使用git地址时add_versions怎么写？

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake#833]
* 怎么根据version checkout匹配的版本？
* add_versions第二个参数（即sha256）是什么？

**Comment by waruqi** [comment]
add_versions的第二个参数可以是 zip/sha256，也可以是git commit/tag/branch

可以看下这个包的add_versions，就是git commit
https://github.com/xmake-io/xmake-repo/blob/master/packages/x/x264/xmake.lua

**Comment by playgithub** [comment]
> add_versions的第二个参数可以是 zip/sha256，也可以是git commit/tag/branch
> 
> 可以看下这个包的add_versions，就是git commit
> https://github.com/xmake-io/xmake-repo/blob/master/packages/x/x264/xmake.lua

`add_versions("v2018.09.25", "545de2ffec6ae9a80738de1b2c8cf820249a2530")`
第一个参数是git checkout 后面的参数？
第二个参数是git object hash?

**Comment by waruqi** [comment]
仔细看我刚说的啊，第一个自己随便填版本

> add_versions的第二个参数可以是 zip/sha256，也可以是git commit/tag/branch

**Comment by playgithub** [comment]
这样方便，使用git地址不需要修改`xmake-repo`

**Comment by waruqi** [comment]
> 这样方便，使用git地址不需要修改`xmake-repo`

如果add_urls仅仅设置了git url，并且仅仅走分支 是不需要，但这样不安全可靠，因为上游repo一有变动，就会影响你的项目，通常不建议，除非用户了解其中利弊。

而 add_versions("v2018.09.25", "commit/tag/branch") 的方式，还是需要修改repo，通过add_versions增加对应版本号 -> commiit/tag/branch的关系，add_requires才能选择里面的版本。

**Comment by playgithub** [comment]
> 如果add_urls仅仅设置了git url，并且仅仅走分支（add_requires("pkgname branchname")） 是不需要，但这样不安全可靠，因为上游repo的特定分支一有变动，就会影响你的项目，通常不建议，除非用户了解其中利弊。

自己开发指定分支才方便，发布可以指定某个commit，好在有选择

> 而 add_versions("v2018.09.25", "commit/tag/branch") 的方式，还是需要修改repo，通过add_versions增加对应版本号 -> commiit/tag/branch的关系，add_requires才能选择里面的版本。（就是为了保证安全可靠，每次下载的依赖版本完全固定）

第一个参数相当于ID，ID灵活
