### ISSUE TITLE
忘了当前配置是deubg还是release，怎么查看？

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake#836]
忘了上次是用`xmake f --mode=debug`还是`xmake f --mode=debug`配置的

PS：如果多加一些查询就方便了

**Comment by waruqi** [comment]
xmake f -v

**Comment by playgithub** [comment]
> xmake f -v 就可以看

`xmake f -v`可以的

> 另外每次编译的时候 不是进度信息就带mode显示了么 还看不到哈。。。

编译前看啊

PS：如果加点这样的选项就好了：
* `xmake f mode` or `xmake f --mode`
* `xmake f plat` or `xmake f --plat`
* `xmake f arch` or `xmake f --arch`
* `xmake f target_path` or `xmake f --target_path`
我得先看看代码，看能不能加吧

**Comment by waruqi** [comment]
> 编译前看啊

不是有 `xmake f -v` 了么，新版本也可以通过 `xmake show`  看。

>  xmake f --mode
> xmake f plat or xmake f --plat
> xmake f arch or xmake f --arch

你就不要瞎设计了，干扰正常的配置

**Comment by playgithub** [comment]
> 不是有 `xmake f -v` 了么，新版本也可以通过 `xmake show` 看。

`xmake show`好，速度比`xmake f -v`快多了

> > xmake f --mode
> > xmake f plat or xmake f --plat
> > xmake f arch or xmake f --arch
> 
> 你就不要瞎设计了，干扰正常的配置

哈哈哈，我的接口应该不够好，但是功能真有这个需求，`xmake f target_path or xmake f --target_path`可以解决我的主要问题，有了这个vscode就能使用普通的`lanuch.json`了，如果targetPath写死，可以使用快捷键，而且不会卡住。知道你忙，我有空学习一下代码先。

**Comment by waruqi** [comment]
> > 不是有 `xmake f -v` 了么，新版本也可以通过 `xmake show` 看。
> 
> `xmake show`好，速度比`xmake f -v`快多了
> 
> > > xmake f --mode
> > > xmake f plat or xmake f --plat
> > > xmake f arch or xmake f --arch
> > 
> > 
> > 你就不要瞎设计了，干扰正常的配置
> 
> 哈哈哈，我的接口应该不够好，但是功能真有这个需求，`xmake f target_path or xmake f --target_path`可以解决我的主要问题，有了这个vscode就能使用普通的`lanuch.json`了，如果targetPath写死，可以使用快捷键，而且不会卡住。知道你忙，我有空学习一下代码先。

之前就说了，xmake-vscode内部就是透传的lanuch.json，跟你外面设置lanuch.json没有本质区别，即使不改插件，也有对应的配置选项，可以完全改写内置lanuch.json里面的所有设置

而且 https://github.com/xmake-io/xmake-vscode/issues/36  都有其他用户说了，卡住可能跟externalConsole的设置有关，你自己配置改写下内部的 externalConsole 设置么。。

```
"xmake. customDebugConfig": {
    externalConsole: false
}
```

https://github.com/xmake-io/xmake-vscode/issues/33
https://github.com/xmake-io/xmake-vscode/issues/39

这两个里面，我都说了好几遍了，尝试下改externalConsole，你有这点时间折腾，稍微研究下xmake-vscode的配置 说不定老早搞定了。

哪怕是直接研究xmake-vscode的源码也比这个快。。

而且获取指定target路径的方式，xmake-vscode源码里面也有，直接参考下么，也就一行命令的事

https://github.com/xmake-io/xmake-vscode/blob/289d7b81ab8409e011255425cf5f3fb727be5016/src/xmake.ts#L704-L710

```console
xmake l assets/targetpath.lua targetname
```

https://github.com/xmake-io/xmake-vscode/blob/master/assets/targetpath.lua

**Comment by playgithub** [comment]
好的，谢谢，研究一下
