### ISSUE TITLE
调用可执行程序的路径问题

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake#837]
刚拷了一个xmake工程到新机器。
* 这个工程`add_requires("protobuf-cpp")`，间接依赖`cmake`
* 新机器有`protoc.exe`（独立安装的），新装的`xmake`

问题：
* 运行`xmake`没有尝试获取`protobuf-cpp`和`cmake`，直接就使用原有的`protoc.exe`编译了。然后随便修改一下`xmake.lua`在`xmake`，就会获取`protobuf-cpp`和`cmake`了。这是为什么？
* `xmake`获取`protobuf-cpp`后，使用的是`xmake`获取的`protobuf-cpp`还是原来的独立安装的`protobuf-cpp`？

PS：如果使用绝对路径使用`xmake`获取的`protobuf-cpp`更好？因为`add_requires`有版本要求

**Comment by waruqi** [comment]
默认会检测优先用系统已有的，也可以强制完全走xmake-repo提供的版本，不走系统：`add_requires("protobuf-cpp", {system = false})`


> PS：如果使用绝对路径使用xmake获取的protobuf-cpp更好？因为add_requires有版本要求

没明白什么绝对路径，add_requires 你有版本要求，那就追加版本，没版本要求，那就默认

**Comment by playgithub** [comment]
我可能误会了，我以为既然`add_requires`支持版本，那么`xmake`就不会用系统的。问题是`xmake`还能检测系统的比如`protoc.exe`的版本？
是不是`add_requires`不加版本时才考虑系统的？

**Comment by waruqi** [comment]
我觉得我刚说的很明白了，默认走，也可以指定不走，跟版本有什么关系，指定版本 如果探测到系统也有对应版本（但不一定每个包都能正常探测到系统安装的版本），当然也走系统，如果没匹配版本，就走xmake-repo

> 默认会检测优先用系统已有的，也可以强制完全走xmake-repo提供的版本，不走系统：add_requires("protobuf-cpp", {system = false})
