### ISSUE TITLE
Qt版本获取问题

### ISSUE THREAD

**Issue by bstaint** [xmake-io/xmake#840]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

Windows下把Qt装在E:/3rdParty/qt5目录下，运行xmake f --qt=E:\3rdParty\qt5，结果
```
checking for the architecture ... x64
checking for the Microsoft Visual Studio (x64) version ... 2019
checking for the Qt SDK directory ... E:\3rdParty\qt\5.15.0\msvc2019_64
checking for the Qt SDK version ... 3
```
xmake好像是匹配目录名获取的版本，只有把目录中其他数字去掉才正常`--qt=E:\ZrdParty\qt`

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 错误信息

如果可能，请尽量附加程序运行过程中的错误输出信息。

> 如果是xmake相关编译问题，请加上`-vD`参数运行，并给出详细编译输出信息。

### 相关环境

请提供编译和运行环境信息，例如：xmake版本、操作系统等

### 其他信息

请提供其他附加信息帮助我们诊断问题(比如截图，xmake.lua或者可复现的demo)。

**Comment by waruqi** [comment]
目前没有更好的检测Qtsdk版本的方式，只能根据路径检测，如果检测的不对，就自己指定下吧。。`xmake f --qt_sdkver=5.15 --qt=/xxx`

**Comment by bstaint** [comment]
我看了下，可以用qmake来获取：
```
qmake.exe -query QT_VERSION
```

**Comment by waruqi** [comment]
哦 那等回头有时间我看看 你先手动设吧

**Comment by waruqi** [comment]
我处理过了，你更新下试试 

```console
xmake update -s dev
xmake f -c --qt=xxxx
```

**Comment by bstaint** [comment]
可以了，感谢。
