### ISSUE TITLE
无法通过add_packages/requires安装vcpkg包

### ISSUE THREAD

**Issue by sandunder** [xmake-io/xmake#841]
xmake.lua:
`add_rules("mode.debug", "mode.release")
add_requires("vcpkg::boost","vcpkg::opencl")
target("temp")
    set_languages("c11","c++17")
    set_kind("binary")
    set_optimize("fastest")
    add_files("src/*.cpp")
    add_packages("vcpkg::boost","vcpkg::opencl")
`
输出：
`checking for the Microsoft Visual Studio (x64) version ... 2019
note: try installing these packages (pass -y to skip confirm)?
in vcpkg:
  -> vcpkg::boost    
please input: y (y/n)
y
  => install vcpkg::boost  .. failed
if you want to get verbose errors, please see:
  -> C:\Users\省略\AppData\Local\.xmake\cache\packages\2006\v\vcpkg_boost\installdir.failed\logs\install.txt
error: install failed!
`

**Comment by waruqi** [comment]
带-vD执行下看看 详细错误信息

xmake f --vD
xmake -vD

**Comment by sandunder** [comment]
PS D:\sand_under\source\VScode project\temp> xmake -vD
checking for the Microsoft Visual Studio (x64) version ... 2019
checking for the unzip ... ok
checking for the git ... ok
checking for the gzip ... no
checking for the 7z ... ok
checking for the ping ... ok
pinging for the host(gitee.com) ... 31 ms
pinging for the host(gitlab.com) ... 214 ms
checking for the nmap ... no
pinging for the host(github.com) ... 65535 ms
finding boost from vcpkg ..
checking for the vcpkg directory ... D:\vcpkg
checking for the vcpkg::boost ... no
finding opencl from vcpkg ..
checking for the vcpkg::opencl ... 2.2-2
note: try installing these packages (pass -y to skip confirm)?
in vcpkg:
  -> vcpkg::boost
please input: y (y/n)
y
installing boost from vcpkg ..
D:\vcpkg\vcpkg install boost:x64-windows-static
Computing installation plan...
The following packages are already installed:
    boost[core]:x64-windows-static
Package boost:x64-windows-static is already installed

Total elapsed time: 2.19 ms

finding boost from vcpkg ..
checking for the vcpkg::boost ... no

error: @programdir\actions\require\impl\action\install.lua:191: fetch vcpkg::boost failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:788]: in function 'raiselevel'
    [@programdir\core\sandbox\modules\utils.lua:181]: in function 'assert'
    [@programdir\actions\require\impl\action\install.lua:191]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\actions\require\impl\action\install.lua:127]: in function 'install'
    [@programdir\actions\require\impl\package.lua:618]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:185]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:182]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

  => install vcpkg::boost  .. failed
error: @programdir\modules\private\async\runjobs.lua:207: @programdir\actions\require\impl\action\install.lua:250: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:788]: in function 'raise'
    [@programdir\actions\require\impl\action\install.lua:250]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
    [@programdir\actions\require\impl\action\install.lua:127]: in function 'install'
    [@programdir\actions\require\impl\package.lua:618]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:185]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:182]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:788: in function 'raise'
        @programdir\modules\private\async\runjobs.lua:207: in function 'catch'
        @programdir\core\sandbox\modules\try.lua:127: in function 'try'
        @programdir\modules\private\async\runjobs.lua:182: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>

**Comment by waruqi** [comment]
应该是你这之前就装好了vcpkg::boost，但是xmake的 find_package 没找到导致，我现在暂时没磁盘空间装vcpkg和boost，你先自己到 https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/manager/vcpkg/find_package.lua 里面加print看看好了

等后面有时间腾出空间了，我再看看

> checking for the vcpkg::boost ... no
> Package boost:x64-windows-static is already installed

**Comment by waruqi** [comment]
看了下，这个是由于 vcpkg提供的boost库，是拆成独立子模块装的，不是单纯引用了个boost就集成了所有，你得指定集成哪个boost子库，比如：`add_requires("vcpkg::boost-beast")` 

即使你要使用默认boost提供基础子库，也得指定boost-core，而不是boost

`add_requires("vcpkg::boost-core")` 

所以，xmake本身没啥问题，拟选用vcpkg库的时候，名字自己改下就好。。不要单用boost，得用boost-[sublibname]

或者使用xmake-repo内置的boost包也可以（不走vcpkg）：

```lua
add_requires("boost")
add_requires("boost", {configs = {beast = true}})
```

**Comment by sandunder** [comment]
哦，知道了，谢谢
麻烦您了
