### ISSUE TITLE
rc文件依赖不会检测更新

### ISSUE THREAD

**Issue by shuax** [xmake-io/xmake#847]
### 描述问题

rc文件通过引用一个h文件写入版本号

### 期待的结果

在修改h文件以后，重新编译，文件版本号能更新

### 错误信息

版本号未更新

### 相关环境

vs2019

### 其他信息

也许rc文件编译结果不缓存更好？

**Comment by waruqi** [comment]
> 也许rc文件编译结果不缓存更好？

不是，是因为你是目前第一个需要rc依赖更新的人，rc用的人少，没人提需求，我就懒得整了

**Comment by waruqi** [comment]
我支持了，你更新到dev试试  xmake update dev

**Comment by shuax** [comment]
测试成功
