### ISSUE TITLE
add_requires怎么才能立即使用最新版本的库

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake#848]
提交PR，等待合并，时间有点长，怎么才能立即使用最新版本的库？

**Comment by waruqi** [comment]
只要merge到master，就可以使用，不过本地repo你也得手动更新下，然后追加-c清下之前的检测结果，强制触发重新检测

```console
xmake repo -u
xmake f -c
```

**Comment by waruqi** [comment]
> 提交PR，等待合并，时间有点长，怎么才能立即使用最新版本的库？

总归要过完ci以及一些review的，如果想在没merge之前就用上，可以先放到自己的私有仓库，先从你自己的repo中找boost使用，或者直接在xmake.lua里面定义自己的package。。

https://xmake.io/#/zh-cn/package/remote_package?id=%e4%bd%bf%e7%94%a8%e8%87%aa%e5%bb%ba%e7%a7%81%e6%9c%89%e5%8c%85%e4%bb%93%e5%ba%93
