### ISSUE TITLE
xmake-repo有boost 1.73.0，构建时怎么下载1.72.0？

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake#849]
1. [https://github.com/xmake-io/xmake-repo/blob/master/packages/b/boost/xmake.lua](https://github.com/xmake-io/xmake-repo/blob/master/packages/b/boost/xmake.lua)有`boost 1.73.0`
2. `xmake update -s dev`
3. `xmake.lua`没指定`boost`版本
3. `xmake`还是下载`boost 1.72.0`

**Comment by waruqi** [comment]
更新下repo

```console
xmake repo -u
```
