### ISSUE TITLE
add_requires动态链接库，二进制路径问题

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake#850]
比如Windows上使用动态链接库，`add_requires(test_lib)`，.h和.lib添加文档有，.dll怎么找到的？

**Comment by waruqi** [comment]
默认走的lib，可以通过 `add_requires("xxx", {configs = {shared = true}})` 切到动态库，但并不是设置了，一定就用了动态库，还得看xmake-repo里面目前收录的package是否处理了shared配置，目前有些库支持了，有些没支持

你自己到xmake-repo里面去看是否有相关shared的处理逻辑，如果特定pkg还不支持shared生成，自己提个pr进去改进下。或者提个issues备着，看我排期

另外，xmake require --info xxx 可以看到特定包的 所有配置有哪些，比如shared，这个文档有说明

**Comment by playgithub** [comment]
运行程序知道那dll路径吗？还是要另外手动指定？

**Comment by waruqi** [comment]
package安装通常都是安装到 bin/lib下，这些 xmake run时候 都会自动附加到path上去。
