### ISSUE TITLE
编译android 的armeabi平台动态库失败

### ISSUE THREAD

**Issue by jococi** [xmake-io/xmake#859]
###> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题
配置：
`> Executing task: xmake f -p android -a armeabi -m release --ndk="/media/mic/Soft/SDK/ndk/21.3.6528147" --trybuild=ndkbuild <`

编译：
`> Executing task: xmake -r -w <`

编译android 的armeabi平台失败，其他部分平台编译成功。

### 期待的结果
正常编译

### 错误信息

[ 37%]: ccache compiling.release src/interface.cpp
[ 50%]: ccache compiling.release src/test.cpp
[ 62%]: linking.release libDFYTradeApi.so
error: /media/mic/Soft/SDK/ndk/21.3.6528147/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lc++_static
/media/mic/Soft/SDK/ndk/21.3.6528147/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lc++abi
/media/mic/Soft/SDK/ndk/21.3.6528147/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lunwind
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

> 如果是xmake相关编译问题，请加上`-vD`参数运行，并给出详细编译输出信息。

### 相关环境

xmake版本:2.3.4
操作系统:deepin
ADK:21.3.6528147

### 其他信息

请提供其他附加信息帮助我们诊断问题(比如截图，xmake.lua或者可复现的demo)。

**Comment by waruqi** [comment]
ndk r16b 以后版本 google已经不提供 armeabi 支持了，当然编译不过。。要用armeabi ，就换r16b老版本ndk，或者用 armv7-a

**Comment by jococi** [comment]
感谢告知
