### ISSUE TITLE
本地包管理机制

### ISSUE THREAD

**Issue by car520120** [xmake-io/xmake#861]
```
pkgmgr_rootdir
            |-------plat
                        |----x86
                        |----x64
                        |----arm
                                  |-----zlib1.2.8
                                                |-----bin
                                                |-----include
                                                |-----lib
                                  |-----zlib1.2.8-$(sha256)   特殊版本
                                                |-----bin
                                                |-----include
                                                |-----lib
            |-------src
                        |----sqlite3
                                  |-----sqlite-autoconf-3320300.tar.gz
                                  |-----sqlite-autoconf-3310300.tar.gz
                                  |-----check. sha256
                        |----tbox
                                  |-----tbox1.6.5.zip
                                  |-----check. sha256
            |-------git
                        |----7-Zip
                        |----xmake
            |-------repo
                         |-----zlib
                                  |-----xmake.lua
                         |-----sqlite3
                                  |-----xmake.lua

```
--如果使用了这个设置
set_pkgmgr($(pkgmgr_rootdir))

--工程会优先到  pkgmgr_rootdir 目录中查找对应的包
--如果没有找到则到 xmake-repo 中下载存放到 pkgmgr_rootdir 目录中

--引用包 
add_requires("tbox", {debug = is_mode("debug")})

**Comment by waruqi** [comment]
xmake.lua需要给用户分发，这种属于个人用户需求，加在xmake.lua里面对其他用户没什么用，即使其他用户需要，也应该走xmake config/global配置

暂时不考虑新开接口到xmake.lua

具体xmake config/global里面怎么加 我会评估，但不会搞这么复杂

* tar包的下载文件本地搜索根目录(不分级)
* 包实际安装的根目录，这个只能通过xmake global全局唯一切换到其他配置，且内部结构固定不能改动

**Comment by waruqi** [comment]
我改进过了，xmake global加了两个目录配置参数：

```console
$ xmake g --help
        --pkg_searchdirs=PKG_SEARCHDIRS                      The search directories of the remote package.
                                                                 e.g.
                                                                 - xmake g --pkg_searchdirs=/dir1:/dir2
        --pkg_installdir=PKG_INSTALLDIR                      The install root directory of the remote package.
```

xmake config也支持搜索目录配置

```console
$ xmake f --help
        --pkg_searchdirs=PKG_SEARCHDIRS                      The search directories of the remote package.
                                                                 e.g.
                                                                 - xmake g --pkg_searchdirs=/dir1:/dir2
```

具体包的搜索名字可以通过下面的命令获取到：

```console
$ xmake require --info opencv
    require(opencv): 
      -> searchdirs: /tmp:~/Downloads/search
      -> searchnames: opencv.git, opencv-4.2.0.tar.gz
```

下载失败，也会有提示给用户如何操作：

```console
  => download https://cmake.org/files/v3.15/cmake-3.15.4-Darwin-x86_64.tar.gz .. failed
  => download https://github.com/Kitware/CMake/releases/download/v3.15.4/cmake-3.15.4-Darwin-x86_64.tar.gz .. failed
  => download https://gitlab.com/xmake-mirror/cmake-releases/raw/master/cmake-3.15.4-Darwin-x86_64.tar.gz .. failed

we can also download these packages manually:
  - https://cmake.org/files/v3.15/cmake-3.15.4-Darwin-x86_64.tar.gz
  - https://github.com/Kitware/CMake/releases/download/v3.15.4/cmake-3.15.4-Darwin-x86_64.tar.gz
  - https://gitlab.com/xmake-mirror/cmake-releases/raw/master/cmake-3.15.4-Darwin-x86_64.tar.gz
to the local search directories: /tmp:~/Downloads/search
  - cmake-3.15.4.tar.gz
and we can run `xmake g --pkg_searchdirs=/xxx` to set the search directories.
error: download failed!
```

**Comment by waruqi** [comment]
请安装toolchain分支包测试。。xmake update github:xmake-io/xmake#toolchain

或者从https://github.com/xmake-io/xmake/actions/runs/143784830 下载win安装包装

**Comment by playgithub** [comment]
测试结果

1. `xmake.lua`
```
add_requires("boost", {configs={shared=true, date_time=true}})

target("test")
    set_kind("binary")

    add_packages("boost")
	
	add_files("main.cpp")
```
PS: main.cpp = HelloWorld

2.
```
...
...failed updating 4 targets...
...skipped 4 targets...
...updated 15365 targets...
error: @programdir\core\sandbox\modules\os.lua:387: execv(./b2 --prefix=C:\Users\aaa\AppData\Local\.xmake\packages\b\boost\1.73.0\9b46ca5f04fd469f9bbfb1c29a271f20 --libdir=C:\Users\aaa\AppData\Local\.xmake\packages\b\boost\1.73.0\9b46ca5f04fd469f9bbfb1c29a271f20\lib -d2 -j4 --hash --layout=tagged-1.66 --user-config=user-config.jam --no-cmake-config -sNO_LZMA=1 -sNO_ZSTD=1 install threading=multi debug-symbols=off link=static address-model=64 runtime-link=static cxxflags=-std:c++14 --with-filesystem --with-date_time) failed(1)
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:792]: in function 'raise'
    [@programdir\core\sandbox\modules\os.lua:387]: in function 'runv'
    [@programdir\core\sandbox\modules\os.lua:284]: in function 'vrunv'
    [...xmake\repositories\xmake-repo\packages\b\boost\xmake.lua:130]: in function 'script'
    [@programdir\actions\require\impl\utils\filter.lua:120]: in function 'call'
    [@programdir\actions\require\impl\action\install.lua:168]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\actions\require\impl\action\install.lua:127]: in function 'install'
    [@programdir\actions\require\impl\package.lua:619]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:185]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:182]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

  => install boost 1.73.0 .. failed
error: @programdir\modules\private\async\runjobs.lua:207: @programdir\actions\require\impl\action\install.lua:250: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:792]: in function 'raise'
    [@programdir\actions\require\impl\action\install.lua:250]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
    [@programdir\actions\require\impl\action\install.lua:127]: in function 'install'
    [@programdir\actions\require\impl\package.lua:619]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:185]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:182]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:792: in function 'raise'
        @programdir\modules\private\async\runjobs.lua:207: in function 'catch'
        @programdir\core\sandbox\modules\try.lua:127: in function 'try'
        @programdir\modules\private\async\runjobs.lua:182: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>
```

**Comment by waruqi** [comment]
> 测试结果
> 
> 1. `xmake.lua`
> 
> ```lua
> add_requires("boost", {configs={shared=true, date_time=true}})
> 
> target("test")
>     set_kind("binary")
> 
>     add_packages("boost")
> 	
>     add_files("main.cpp")
> ```
> 
> PS: main.cpp = HelloWorld
> 
> 
> ```
> λ xmake f -cvD
> ...
> ...failed updating 4 targets...
> ...skipped 4 targets...
> ...updated 15365 targets...
> error: @programdir\core\sandbox\modules\os.lua:387: execv(./b2 --prefix=C:\Users\aaa\AppData\Local\.xmake\packages\b\boost\1.73.0\9b46ca5f04fd469f9bbfb1c29a271f20 --libdir=C:\Users\aaa\AppData\Local\.xmake\packages\b\boost\1.73.0\9b46ca5f04fd469f9bbfb1c29a271f20\lib -d2 -j4 --hash --layout=tagged-1.66 --user-config=user-config.jam --no-cmake-config -sNO_LZMA=1 -sNO_ZSTD=1 install threading=multi debug-symbols=off link=static address-model=64 runtime-link=static cxxflags=-std:c++14 --with-filesystem --with-date_time) failed(1)
> stack traceback:
>     [C]: in function 'error'
>     [@programdir\core\base\os.lua:792]: in function 'raise'
>     [@programdir\core\sandbox\modules\os.lua:387]: in function 'runv'
>     [@programdir\core\sandbox\modules\os.lua:284]: in function 'vrunv'
>     [...xmake\repositories\xmake-repo\packages\b\boost\xmake.lua:130]: in function 'script'
>     [@programdir\actions\require\impl\utils\filter.lua:120]: in function 'call'
>     [@programdir\actions\require\impl\action\install.lua:168]:
>     [C]: in function 'trycall'
>     [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
>     [@programdir\actions\require\impl\action\install.lua:127]: in function 'install'
>     [@programdir\actions\require\impl\package.lua:619]: in function 'jobfunc'
>     [@programdir\modules\private\async\runjobs.lua:185]:
>     [C]: in function 'trycall'
>     [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
>     [@programdir\modules\private\async\runjobs.lua:182]: in function 'cotask'
>     [@programdir\core\base\scheduler.lua:317]:
> 
>   => install boost 1.73.0 .. failed
> error: @programdir\modules\private\async\runjobs.lua:207: @programdir\actions\require\impl\action\install.lua:250: install failed!
> stack traceback:
>     [C]: in function 'error'
>     [@programdir\core\base\os.lua:792]: in function 'raise'
>     [@programdir\actions\require\impl\action\install.lua:250]: in function 'catch'
>     [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
>     [@programdir\actions\require\impl\action\install.lua:127]: in function 'install'
>     [@programdir\actions\require\impl\package.lua:619]: in function 'jobfunc'
>     [@programdir\modules\private\async\runjobs.lua:185]:
>     [C]: in function 'trycall'
>     [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
>     [@programdir\modules\private\async\runjobs.lua:182]: in function 'cotask'
>     [@programdir\core\base\scheduler.lua:317]:
> 
> stack traceback:
>         [C]: in function 'error'
>         @programdir\core\base\os.lua:792: in function 'raise'
>         @programdir\modules\private\async\runjobs.lua:207: in function 'catch'
>         @programdir\core\sandbox\modules\try.lua:127: in function 'try'
>         @programdir\modules\private\async\runjobs.lua:182: in function 'cotask'
>         @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>
> ```

这个错误跟此issues无关，boost自身b2编译问题，你自己排查下 或者另开issues，这里只验证 pkg search 是否生效。

**Comment by playgithub** [comment]
好的，我是看这个版本才发这里的

**Comment by waruqi** [comment]
这个目前看来应该生效了，没啥问题，先close了，回头有问题再开新issues好了
