### ISSUE TITLE
add_requires重复解压优化

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake#863]
`add_requires("boost")`
boost解压特别慢，改了一下配置，`xmake f -c`会重新解压，其实没必要。
PS: 解压到source.tmp，完成后更名未source，那可以假设source是完整的吗？`xmake f -c`看到source目录就不重复解压了，一般没问题。考虑意外可以强制解压，`xmake f -cf`。不过接口变复杂了不是很好，如果实现可以复杂一点，接口简单一点就更好吧。

**Comment by waruqi** [comment]
不能假设完整，可以考虑优化 但是考虑和处理的细节 会不少。。等回头有时间吧。

**Comment by playgithub** [comment]
哈哈，是很细节，虽然可以节省时间和磁盘写操作。

**Comment by waruqi** [comment]
刚想了下，当初考虑重复解压，主要还是了保证构建之前 source 目录是完全干净的，确保每次build的环境都会干净一致的

因为很多第三方构建系统都会生成各种临时和缓存文件，导致二次编译行为不一致。虽然可以通过 make clean, 什么的清干净，但不是所有构建系统一个 make clean就完事的，cmake/meson什么clean方式都不相同，还有些nmake和makefile连clean都不一定有

另外，通过clean来，还得在每个package的xmake.lua里面定制on_clean才行，维护工作量更大

如果通过git来保证干净，也不是用户都装了git，多了依赖，虽然repo本身也是需要git，但还是感觉有点蛋疼~

**Comment by playgithub** [comment]
那解压前吧source改为source.tmp，再比对zip和source.tmp，按单个文件或目录，source.tmp有就移动到source，没有就解压单个文件货创建单个目录。有点过分。

**Comment by waruqi** [comment]
我不折腾，吃力不讨好 我宁愿两次解压

**Comment by playgithub** [comment]
如果解压库有遍历和解压单个文件的API，那也不折腾，省很多CPU和磁盘写操作。

**Comment by waruqi** [comment]
大哥，这么多解压格式了，zip gzip 7z bz2 tar xz 你让我一个个移植成搞成库link进来？岂不是更蛋我不干

**Comment by playgithub** [comment]
如果zip gzip 7z bz2 tar xz库都支持遍历和解压单个文件，那写个统一的接口也不是难事。但只要有一个库不支持，就麻烦了。

**Comment by waruqi** [comment]
即使都支持我也不搞 没事link这么多依赖干嘛 编译依赖多 生成的xmake也大 也不方便移植

**Comment by playgithub** [comment]
好像7z都支持的吧

**Comment by waruqi** [comment]
整一个7z进来 也够大了，我连minizip都一直没我弄进来

**Comment by playgithub** [comment]
好的，要求高好，那先这样。

**Comment by playgithub** [comment]
> 不能假设完整

刚`xmake f -c`，因为boost已经存在没有在编译，那就是假设`%localappdata%\.xmake\packages\b\boost\1.73.0\ce8fae33ec0248febcf9f638382abbda`是完整的

source.tmp成功后才会更名为source，那为什么不能假设source是完整的？

**Comment by waruqi** [comment]
现在的问题不是完整性，是要保证每次clean。确保每次build效果一致 不被其他cache干扰。。我不想在纠结这个问题了，暂时先这样吧

**Comment by playgithub** [comment]
对的，一时想到，忘记clean的问题了
