### ISSUE TITLE
Support new cl.exe dependency report files

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#868]
https://github.com/ninja-build/ninja/issues/1806
https://github.com/ninja-build/ninja/issues/1766
https://github.com/ninja-build/ninja/pull/1812/files/48275bf8b04f4b2352d9c1e2ea7213b2ff9fde1d..00fe279c0c23396cf77a5d06073a1a23085506a6

**Comment by OpportunityLiu** [comment]
所以还是赶紧弄个正经的JSON库进来吧

**Comment by waruqi** [comment]
是会弄个的 不过得等等 最近没啥时间

**Comment by waruqi** [comment]
json的调研和集成后期到这里跟进：https://github.com/xmake-io/xmake/issues/893

**Comment by waruqi** [comment]
> 所以还是赶紧弄个正经的JSON库进来吧

我加上了

**Comment by waruqi** [comment]
我初步支持上了，/sourceDependences 解析，初步看了下，似乎默认所有系统头文件也会带进来，没看到像gcc/clang那样可指定只生成项目的includes，这样可以减少不少输出量，提高处理和编译效率。

先这样吧，回头有问题再改进
