### ISSUE TITLE
手动设置目标目录后，报目录已存在的错误

### ISSUE THREAD

**Issue by huye** [xmake-io/xmake#871]
在 xmake.lua 中全局设置了 set_objectdir("$(projectdir)/.objs")，然后编译xmake -b xxx目标会出现 error: cannot create directory: xxx/.objs/xxx/linux/x86_64/debug/., File exists的错误，这时再执行下下xmake -b xxx又能正常编译了。我使用的是2.3.5版本

**Comment by waruqi** [comment]
我这边测试正常，没法复现，请给个能复现的demo

**Comment by huye** [comment]
我知道了，都没有关系，是当源文件没有在子目录上的时候，源文件在项目根目录中就会出现这个问题。因为我是在一个已有项目中使用，这个项目的文件都在一级目录下，没有 src 子目录。

**Comment by huye** [comment]
所以提示出错的路径最后有一个.，应该是你直接把源文件路径求目录，而源文件又没有目录，所以求出来的是个.，你直接连上去创建目录就报错了。

**Comment by waruqi** [comment]
哦 我回头兼容下，你先自己处理下好了。

**Comment by waruqi** [comment]
你更新到 xmake update -s dev 再试试

**Comment by huye** [comment]
执行更新报错：error: unzip not found! we need install it first，这是什么意思，系统的unzip是安装了的

**Comment by waruqi** [comment]
切到 非项目目录下执行 update

**Comment by huye** [comment]
我已经手动根据你的更新修改了

**Comment by waruqi** [comment]
?? 非项目目录，没有xmake.lua 不会有项目缓存，肯定能检测奥unzip的，除非没装
