### ISSUE TITLE
set_filename和add_deps不协调

### ISSUE THREAD

**Issue by huye** [xmake-io/xmake#872]
在目标中使用set_basename重命名文件后使用add_deps是正常的会正常链接重命名的动态库，而如果使用set_filename生命名后的链接参数却是原始的 -ltarget名称，无法正常链接。

**Comment by huye** [comment]
target("abc")

    set_kind("shared")
    -- set_filename("new123.so")
    set_basename("abc_$(mode)")

target("test")
    set_kind("binary")
    add_deps("abc")


这样在编译test时会正常链接 -labc_debug 到 libabc_debug.so文件
使用set_filename("new123.so")后不是 -l:new123.so，而是用的 -labc，显然不能正确链接。

**Comment by waruqi** [comment]
你filename改了，那当然不行了，如果改成了  xxx.xx 连so都不是，根本没法处理，通常特定平台后缀名so原本就是固定不变的，没必要改，那用set_filename来干嘛呢，直接改basename不就好了

**Comment by huye** [comment]
我后面举例的那个-l:new123.so是gcc支持的语法啊，提供了set_filename当然还是处理好点更好了，刚好原来我这就有这个需求。使用set_basename是因为会自动补全lib，而我这里就是不要lib前缀，set_filename手册里的用法正好符合。

**Comment by waruqi** [comment]
> 我后面举例的那个-l:new123.so是gcc支持的语法啊，提供了set_filename当然还是处理好点更好了，刚好原来我这就有这个需求。使用set_basename是因为会自动补全lib，而我这里就是不要lib前缀，set_filename手册里的用法正好符合。

都是些奇怪的需求，自己去掉add_deps，直接add_ldflags add_linkdirs好了

**Comment by huye** [comment]
好的，原来去掉继承是这个意思啊，没理解到。
