### ISSUE TITLE
升级xmake 2.3.5后，ios依赖包没发编译

### ISSUE THREAD

**Issue by fasiondog** [xmake-io/xmake#873]
版本：2.3.5

原工程编译 ios 版本时报错，依赖包没发编译

xmake f -v -D -y -p iphoneos -a x86_64 --target_minver=9.0 --tiny=y --mode=release
checking for the Xcode directory ... /Applications/Xcode.app
checking for the SDK version of Xcode ... 13.5
checking for the Codesign Identity of Xcode ...
checking for the Mobile Provision of Xcode ... 
checking for the unzip ... /usr/bin/unzip
checking for the git ... /usr/bin/git
checking for the gzip ... /usr/bin/gzip
checking for the tar ... /usr/bin/tar
checking for the ping ... /sbin/ping
pinging for the host(gitee.com) ... 30 ms
pinging for the host(gitlab.com) ... 194 ms
checking for the nmap ... no
pinging for the host(github.com) ... 65535 ms
finding catch2 from xmake ..
error: @programdir/core/main.lua:284: ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:87: ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:47: @programdir/modules/private/async/runjobs.lua:207: @programdir/core/tool/toolchain.lua:212: @programdir/toolchains/xcode/load_iphoneos.lua:39: attempt to concatenate local 'target_minver' (a nil value)
stack traceback:
    [@programdir/toolchains/xcode/load_iphoneos.lua:39]:
    [@programdir/toolchains/xcode/xmake.lua:79]:
    [C]: in function 'load'
    [@programdir/core/tool/toolchain.lua:209]: in function '_load'
    [@programdir/core/tool/toolchain.lua:120]: in function 'get'
    [@programdir/core/platform/platform.lua:312]: in function 'formats'
    [@programdir/core/platform/platform.lua:626]: in function 'format'
    [@programdir/core/project/target.lua:1918]: in function 'filename'
    [.../core/sandbox/modules/import/lib/detect/find_library.lua:66]: in function 'find_library'
    [@programdir/modules/package/manager/xmake/find_package.lua:118]: in function '_find_package_from_repo'
    [@programdir/modules/package/manager/xmake/find_package.lua:256]:
    [@programdir/modules/package/manager/find_package.lua:89]: in function '_find_package'
    [@programdir/modules/package/manager/find_package.lua:169]: in function 'find_package'
    [@programdir/modules/lib/detect/find_package.lua:77]: in function '_find_package'
    [@programdir/core/package/package.lua:856]: in function 'fetch'
    [@programdir/actions/require/impl/package.lua:754]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:185]:
    [C]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [@programdir/modules/private/async/runjobs.lua:182]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:317]:

**Comment by waruqi** [comment]
xmake config的时候，追加下 -c ，清下 之前老的 配置 cache，强制重新检测环境，再编译试试
