### ISSUE TITLE
os.run, os.exec等无法执行if, [ 等语句块

### ISSUE THREAD

**Issue by huye** [xmake-io/xmake#876]
如这样的： os.run("if echo abc; then echo 123; fi")

**Comment by waruqi** [comment]
os.run/os.exec 仅支持进程执行，不是shell，如果要用shell，请运行 sh/bash/zsh ...

os.exec("bash -c 'if echo abc; then echo 123; fi'")

**Comment by huye** [comment]
哦好的，我已经改用lua来写了

**Comment by huye** [comment]
建议像makefile一样，直接在描述域中提供一个执行shell代码块的接口，如run_shell什么的，这样写出来的shell块如果生成makefile就可以直接生成过去。现在用lua代码加os.run执行的shell代码就没办法生成到makefile中了

**Comment by waruqi** [comment]
见：https://xmake.io/#/zh-cn/manual/builtin_variables?id=varshell
