### ISSUE TITLE
用了phony后不能生成makefile

### ISSUE THREAD

**Issue by huye** [xmake-io/xmake#878]
用了phony后不能生成makefile，但能生成cmake。这个可以优化下，忽略phony后生成。cmake能正常生成应该也是这样处理的吧。

**Comment by huye** [comment]
建议像makefile一样，直接在描述域中提供一个执行shell代码块的接口，如run_shell什么的，这样写出来的shell块如果生成makefile就可以直接生成过去。现在用lua代码加os.run执行的shell代码就没办法生成到makefile中了

**Comment by waruqi** [comment]
> 建议像makefile一样，直接在描述域中提供一个执行shell代码块的接口，如run_shell什么的，这样写出来的shell块如果生成makefile就可以直接生成过去。现在用lua代码加os.run执行的shell代码就没办法生成到makefile中了

https://xmake.io/#/zh-cn/manual/builtin_variables?id=varshell

**Comment by huye** [comment]
我说的不是这个意思，我说的是就像你的xmake编译安装的makefile里，创建目录，和复制文件那样的直接在makefile中写shell命令的情况。有时候有这种需要，在依赖的目标完成后，需要一些shell操作，如果能这样实现，那生成的makefile里也可以运行这些shell代码

**Comment by waruqi** [comment]
xmake目的就是尽量走lua，要么之前说的直接os.exec 跑 bash 就可以了

**Comment by waruqi** [comment]
phony我修复了，xmake update -s dev更新到dev试试

**Comment by huye** [comment]
我只是说提供一个这样的接口，只是不建议使用这个接口，为特殊需求嘛。比如不要求跨平台时，在没有安装xmake的机器上可能要用原生makefile的，能直接自动生成进去就不用再手动处理了。当然我说的只是特殊需求，可以不用理会

**Comment by waruqi** [comment]
> 我只是说提供一个这样的接口，只是不建议使用这个接口，为特殊需求嘛。比如不要求跨平台时，在没有安装xmake的机器上可能要用原生makefile的，能直接自动生成进去就不用再手动处理了。当然我说的只是特殊需求，可以不用理会

xmake的脚本域是不支持生成到makefile，不管什么接口都没用，想要生成到makefile里面，除了on_load以外的所有脚本域都不支持，目前。
