### ISSUE TITLE
ide support

### ISSUE THREAD

**Issue by uael** [xmake-io/xmake#88]
I'm continue using cmake because it fill well with my ide, did you plan to support some ide ? autocompletion, refactoring, ..

**Comment by waruqi** [comment]
I also want to support some IDEs, but I do not have much time to do this now.

**Comment by uael** [comment]
Yes it's an hard work, I'm going to look for CLion there is already an lua plugin, maybe it can be extended or a good base to start ?

**Comment by TitanSnow** [comment]
Some one have written a plugin for vim [luzhlon/xmake.vim](https://github.com/luzhlon/xmake.vim)

And I have written a GUI-frontend [TitanSnow/ts-xmake-gui](https://github.com/TitanSnow/ts-xmake-gui) :smiley:

**Comment by uael** [comment]
[facebook/buck](https://github.com/facebook/buck) is a JetBrains build system plugin, can provide some inspiration :smiley:

**Comment by TitanSnow** [comment]
I have a see facebook/buck before. Great speed with high concurrency

**Comment by waruqi** [comment]
vscode plugin example: [vscode-cmake-tools](https://github.com/vector-of-bool/vscode-cmake-tools)

**Comment by waruqi** [comment]
A XMake integration in Visual Studio Code: [xmake-vscode](https://github.com/tboox/xmake-vscode).

Some of the details need to be improved. 😄

**Comment by waruqi** [comment]
A XMake integration in Sublime Text: [xmake-sublime](https://github.com/tboox/xmake-sublime)

**Comment by waruqi** [comment]
[#146](https://github.com/tboox/xmake/issues/146)

**Comment by waruqi** [comment]
A XMake integration in IntelliJ IDEA: [xmake-idea](https://github.com/tboox/xmake-idea)

**Comment by waruqi** [comment]
Please install the newest xmake version in master branch to test it. :simle:

**Comment by waruqi** [comment]
I add some new features for [xmake-idea] plugin in these days:

Parse compiling errors/warnings and goto file: 

![problem](https://raw.githubusercontent.com/tboox/xmake-idea/master/res/problem.gif)

And I will add some c/c++ project templates with `xmake.lua` and support xmake api completion lists in this plugin in the future.

**Comment by waruqi** [comment]
the [xmake-idea](https://github.com/tboox/xmake-idea) plugin has been uploaded to [jetbrains plugins](https://plugins.jetbrains.com/plugin/10156-xmake).
