### ISSUE TITLE
Fortran: MOD files not found

### ISSUE THREAD

**Issue by interkosmos** [xmake-io/xmake#884]
### Describe the bug
If projects written in Fortran depend on Fortran modules, the required `*.mod` files are not found at build stage. Given are a Fortran program `sample.f90` and a Fortran module `mymod.f90`, with the program importing the module. Compiling `mymod.f90` manually will output object `module.o` and the module file `mymod.mod` for linking.

But `mymod.mod` will not be found with the following target:

```
target("sample")
    set_languages("fortran")
    set_kind("binary")
    add_files("src/sample.f90")
    add_files("lib/mymod.f90")
    add_includedirs("$(projectdir)")
    set_objectdir("build/")
    set_targetdir("build/")
```

### Expected behavior
`*.mod` files will be found for linking.

### Error output
```
$ xmake
error: src/sample.f90:8:10:
    8 |     use :: mymod
      |          1
Fatal Error: Cannot open module file 'mymod.mod' for reading at (1): No such file or directory
compilation terminated.
```

### Related Environment
```
$ xmake --version
xmake v2.3.5+202007061244
```

**Comment by waruqi** [comment]
Please give me a example/demo project, I will test it.

**Comment by interkosmos** [comment]
`sample.f90`:
```
program sample
    use :: mymod
    call hi()
end program sample
```

`mymod.f90`:
```
module mymod
contains
    subroutine hi()
        print *, 'Hi, there!'
    end subroutine hi
end module mymod
```

Compilation:
```
$ gfortran -c mymod.f90 
$ gfortran -o sample sample.f90 mymod.o
```

**Comment by waruqi** [comment]
Ok, I will improve modules in these days.

**Comment by waruqi** [comment]
I need to confirm whether there will be dependencies between fortran modules? 

for example: mod1.f90 -> mod2.f90 -> mod3.f90？

Or Is there only a dependency between program and module?

**Comment by interkosmos** [comment]
Yes, dependencies between Fortran modules are possible.

**Comment by waruqi** [comment]
Got it, I have updated some codes. You need to strictly ensure that the order of adding source files is consistent with module dependencies

```lua
target("sample")
    set_kind("binary")
    add_files("mymod.f90")   
    add_files("sample.f90")
```

And ensure that single-task running compilation, parallel compilation is disabled.

```console
xmake -j1
```

> Yes, dependencies between Fortran modules are possible.

Since the source file was also dependent before, it will affect the parallel compilation optimization of xmake. You can only compile single task for now.

I will think carefully about how to better handle module compilation in these days.

**Comment by interkosmos** [comment]
Works for the given example, but still fails for dependencies:

```
target("lib")
    set_kind("static")
    add_files("src/mymod2.f90")
    add_files("src/mymod.f90")

target("sample")
    set_kind("binary")
    add_deps("lib")
    add_files("src/sample.f90")
```

```
$ xmake
[ 22%]: compiling.release src/mymod2.f90
[ 33%]: compiling.release src/mymod.f90
[ 44%]: archiving.release liblib.a
[ 77%]: compiling.release src/sample.f90
error: src/sample.f90:2:10:
    2 |     use :: mymod
      |          1
Fatal Error: Cannot open module file 'mymod.mod' for reading at (1): No such file or directory
compilation terminated.
```

**Comment by waruqi** [comment]
please given me the demo project.

**Comment by interkosmos** [comment]
`src/mymod.f90`:
```
module mymod
    use :: mymod2
contains
    subroutine hi()
        call hello()
    end subroutine hi
end module mymod
```
`src/mymod2.f90`:
```
module mymod2
contains
    subroutine hello()
        print *, 'Hello!'
    end subroutine hello
end module mymod2
```
`src/sample.f90`:
```
program sample
    use :: mymod
    call hi()
end program sample
```

**Comment by waruqi** [comment]
please update to the dev branch version and try it again.

**Comment by interkosmos** [comment]
Works for static libraries now, but fails for dynamically ones:

```
target("shared")
    set_kind("shared")
    add_files("lib/mymod2.f90")
    add_files("src/mymod.f90")
```
```
$ xmake
[ 40%]: compiling.release lib/mymod2.f90
[ 60%]: compiling.release src/mymod.f90
error: src/mymod.f90:2:10:
    2 |     use :: mymod2
      |          1
Fatal Error: Cannot open module file 'mymod2.mod' for reading at (1): No such file or directory
compilation terminated.
```

**Comment by waruqi** [comment]
Please run `xmake -j1` to disable parallel compilation. At present, it does not support parallel compilation of fortran modules, because there are dependencies between fortran module files。

I will find a way to better support fortran modules, but currently you can only use single task compilation.

**Comment by interkosmos** [comment]
Can confirm, works with `xmake -j1`.

**Comment by interkosmos** [comment]
Unfortunately, the `*.mod` files are deleted by xmake automatically. But they are required for linking of object files and static libraries. Is it possible to change this default behaviour?

**Comment by waruqi** [comment]
> Unfortunately, the `*.mod` files are deleted by xmake automatically. But they are required for linking of object files and static libraries. Is it possible to change this default behaviour?

They will be removed only when running `xmake -r/--rebuild` or `xmake clean`.

However, the next time they are compiled and linked, they will still be regenerated without affecting normal linking.

If you encounter problems here, please describe your steps and error output

**Comment by interkosmos** [comment]
This xmake file will compile `libsample.a`:

```
target("sample")
    set_kind("static")
    add_files("src/mymod2.f90")
    add_files("src/mymod.f90")           
```

But no `*.mod` files are generated, therefore, `libsample.a` is not linkable.

**Comment by waruqi** [comment]
It works for me.

```
ruki@869df55b0d22:/mnt/testf2$ xmake -j1
[ 40%]: ccache compiling.release src/mymod2.f90
[ 60%]: ccache compiling.release src/mymod.f90
[ 80%]: archiving.release libsample.a
[100%]: build ok!
ruki@869df55b0d22:/mnt/testf2$ tree ./build/
./build/
`-- linux
    `-- x86_64
        `-- release
            `-- libsample.a

3 directories, 1 file
ruki@869df55b0d22:/mnt/testf2$ tree build/.objs/
build/.objs/
`-- sample
    `-- linux
        `-- x86_64
            `-- release
                `-- src
                    |-- mymod.f90.o
                    `-- mymod2.f90.o

5 directories, 2 files
ruki@869df55b0d22:/mnt/testf2$ tree build/.objs/sample/linux/x86_64/release/.modules/
build/.objs/sample/linux/x86_64/release/.modules/
|-- mymod.mod
`-- mymod2.mod
```

**Comment by interkosmos** [comment]
I had to delete the `.xmake` directory, for whatever reason. Now, it works.

**Comment by waruqi** [comment]
you can try add `-c` args to `xmake f -c`. it will ignore all local config cache. You need not remove .xmake manually.

**Comment by waruqi** [comment]
I have improved the fortan build rule.  You need not add `-j1` argument. You can only run `xmake` to build.

**Comment by interkosmos** [comment]
Thank you, works.
