### ISSUE TITLE
关于set_version

### ISSUE THREAD

**Issue by x1244** [xmake-io/xmake#889]
### 你在什么场景下需要该功能？

在target中应用set_version("1.0.0")后，可以通过target:get("version")获得设置的版本。但是编译生成的可执行文件在windows下，没有版本信息。

### 描述可能的解决方案

希望编译后的可执行文件可以查看版本信息。

### 其他信息

Qt 5.7 mingw32 win10

xmake v2.3.5+202007071609

**Comment by waruqi** [comment]
这个应该是用户自己通过rc文件设置的，xmake不会去干这个事情。

**Comment by x1244** [comment]
qt mingw 怎么编译rc文件

**Comment by waruqi** [comment]
嗯
