### ISSUE TITLE
vsxmake2017 x86在vs下Ctrl+F5运行报错

### ISSUE THREAD

**Issue by xstrings** [xmake-io/xmake#890]
https://github.com/xmake-io/xmake/blob/749f61dd839ad30db6bc820374752d7c7f655172/xmake/plugins/project/vsxmake/vsproj/templates/vcxproj/ProjectConfiguration(mode%2Carch)#L1

project vsxmake2017 -a x86生成的工程在vs下Ctrl+F5运行报错 debug | x86 could not be found in the collection，尝试如下修改后可正常运行
> \<ProjectConfiguration Include="#mode#|`#vsarch#`"\>

**Comment by waruqi** [comment]
既然找到原因了 就直接帮忙提个pr过来好了

**Comment by waruqi** [comment]
我dev改了，不过我这测试 include 里面不管是啥 似乎都没遇到问题。 @OpportunityLiu 可以帮忙一起看下

**Comment by OpportunityLiu** [comment]
确实有问题

**Comment by xstrings** [comment]
感谢，第一次用，还不熟悉结构，不确定如何正确修改所以先抛个issue。
祝越来越完善！
