### ISSUE TITLE
现在Linux端是不是还不支持vcpkg呀

### ISSUE THREAD

**Issue by a5066987** [xmake-io/xmake#891]
### Describe the problem details

在Linux下尝试添加vcpkg的远程包，但是会出错
![image](https://user-images.githubusercontent.com/13390857/87404695-52d7b280-c573-11ea-9560-ec0d972b539b.png)
我试了下环境变量里应该有vcpkg的目录
然后我尝试手动指定vcpkg的目录，得到了这样的提示：
![image](https://user-images.githubusercontent.com/13390857/87404843-84e91480-c573-11ea-8617-0bfda6ca9a55.png)

**Comment by waruqi** [comment]
mac/linux 都支持，只不过--vcpkg的配置项 目前只加了win的 回头我加下就好

如果有环境变量 可以提供下 我改进下检测

**Comment by waruqi** [comment]
我加上了 你再试试 更新到dev分支 xmake update dev

**Comment by a5066987** [comment]
好的，我找时间试一下

**Comment by a5066987** [comment]
![image](https://user-images.githubusercontent.com/13390857/87488192-8d356400-c5f4-11ea-82f5-fe748b7b4418.png)
试了一下，好像还是不行，xmake g --help里面也没有找到vcpkg的信息

xmake --version
![image](https://user-images.githubusercontent.com/13390857/87488304-dab1d100-c5f4-11ea-8e11-f1e4c8d3d3c5.png)

**Comment by a5066987** [comment]
发现问题了，我安装的时候是安装到/usr/local/bin里的，但是update之后装到了~/.local/bin. 

能不能正常用vcpkg还没试，但是添加配置可以了，等试完vcpkg我再来update

**Comment by a5066987** [comment]
试了一下，没什么问题了，可以正常添加vcpkg的远程包
