### ISSUE TITLE
[WSL2 container] sandbox filelock failing

### ISSUE THREAD

**Issue by n8v8R** [xmake-io/xmake#900]
### Describe the bug
filelock fails

### Expected behavior
filelock to work

### Error output
```
error: @programdir/core/main.lua:284: @programdir/core/sandbox/modules/import/core/base/task.lua:65: ...dir/core/sandbox/modules/import/core/project/project.lua:149: cannot create the project lock!
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:792]: in function 'raise'
    [...dir/core/sandbox/modules/import/core/project/project.lua:149]: in function 'filelock'
    [...dir/core/sandbox/modules/import/core/project/project.lua:169]: in function 'trylock'
    [...dir/core/sandbox/modules/import/core/project/project.lua:156]: in function 'lock'
    [@programdir/actions/config/main.lua:165]:
    [C]: in function 'load'
    [@programdir/core/base/task.lua:520]: in function 'run'
    [@programdir/core/sandbox/modules/import/core/base/task.lua:63]: in function 'run'
    [@programdir/actions/build/main.lua:74]: in function '_try_build'
    [@programdir/actions/build/main.lua:85]:
    [C]: in function 'load'
    [@programdir/core/base/task.lua:520]: in function 'run'
    [@programdir/core/main.lua:282]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:792: in function 'raise'
        @programdir/core/main.lua:284: in function 'cotask'
        @programdir/core/base/scheduler.lua:317: in function <@programdir/core/base/scheduler.lua:315>
```

### Related Environment

Please provide compiling and running environment information:

- xmake version: v2.3.5+202007222026
- os: WSL2 container kali-linux (`Linux 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 GNU/Linux`)
- target platform: x86_64-pc-linux-gnu

### Additional context
* successfully compiled xmake from source and installed
* git cloned github.com/torvalds/linux.git
* generated a git worktree from the above clone
* changed directory to the git worktree
* ran `xmake -vD` that produced:

>note: Makefile found, try building it or you can run `xmake f --trybuild=` to set buildsystem (pass -y or --confirm=y/n/d to skip confirm)?
please input: y (y/n)

* confirmed with `y` and then the above error incurred 
* checked with `lslocks` but that comes up empty
* `ulimit -a` produces

```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 102370
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 102370
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

```

**Comment by waruqi** [comment]
I have not wsl2 environment now, but I added some debug code to the test branch. You can fetch this branch code and compile xmake to test it again, then please let me see the output info.

```console
$ git fetch origin test:test
$ git checkout test
$ make build
$ source scripts/srcenv.profile # switch to the current source environment
$ # test it and give me output
```

**Comment by n8v8R** [comment]
Thank you for the effort, the output however appears to be the same as previously reported:

```
note: Makefile found, try building it or you can run `xmake f --trybuild=` to set buildsystem (pass -y or --confirm=y/n/d to skip confirm)?
please input: y (y/n)
y
error: @programdir/core/main.lua:284: @programdir/core/sandbox/modules/import/core/base/task.lua:65: ...dir/core/sandbox/modules/import/core/project/project.lua:149: cannot create the project lock!
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:792]: in function 'raise'
    [...dir/core/sandbox/modules/import/core/project/project.lua:149]: in function 'filelock'
    [...dir/core/sandbox/modules/import/core/project/project.lua:169]: in function 'trylock'
    [...dir/core/sandbox/modules/import/core/project/project.lua:156]: in function 'lock'
    [@programdir/actions/config/main.lua:165]:
    [C]: in function 'load'
    [@programdir/core/base/task.lua:520]: in function 'run'
    [@programdir/core/sandbox/modules/import/core/base/task.lua:63]: in function 'run'
    [@programdir/actions/build/main.lua:74]: in function '_try_build'
    [@programdir/actions/build/main.lua:85]:
    [C]: in function 'load'
    [@programdir/core/base/task.lua:520]: in function 'run'
    [@programdir/core/main.lua:282]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:792: in function 'raise'
        @programdir/core/main.lua:284: in function 'cotask'
        @programdir/core/base/scheduler.lua:317: in function <@programdir/core/base/scheduler.lua:315>
```
___
Just to be sure checked that the compiled debug binary is executed, upon `source scripts/srcenv.profile` it printed

```
xmake v2.3.5+202007230959, A cross-platform build utility based on Lua
Copyright (C) 2015-2020 Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, tboox.org

    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor

"/srv/git/xmake/xmake"
"/srv/git/xmake/core/src/demo/demo.b"
```

Also `command -v xmake` produces

>alias xmake='/srv/git/xmake/core/src/demo/demo.b'

**Comment by n8v8R** [comment]
Just run this https://gist.github.com/mschmitt/3722296 (not sure whether reliable though) 

as root

```
perl /srv/test_lockfile.pl
Locked file: /home/.test.lock
Press Enter to finish.
```

as sudo

```
sudo perl /srv/test_lockfile.pl
[sudo] password for km:
Locked file: /home/.test.lock
Press Enter to finish.
```

**Comment by waruqi** [comment]
You can look at the code to confirm whether the patch takes effect. https://github.com/xmake-io/xmake/commit/598ddc1d367af10e786dcf65ca6bb525ec784501

If you are running xmake under root, please set environment variables. `export XMAKE_ROOT=y`

**Comment by n8v8R** [comment]
as root

```
note: Makefile found, try building it or you can run `xmake f --trybuild=` to set buildsystem (pass -y or --confirm=y/n/d to skip confirm)?
please input: y (y/n)
y
project.filelock
openlock        /srv/src/linux/5.7/.xmake/linux/x86_64/project.lock
[xmake]: [filelock_open]: tb_filelock_init_from_path: 0x5d6b40, tryn: 1, errno: 2 No such file or directory
result  <filelock: ..6_64/project.lock>
checking for the architecture ... x86_64
checking for the gcc ... /usr/bin/gcc
configure
{
    arch = x86_64
    ccache = true
    mode = release
    ndk_stdcxx = true
    plat = linux
    kind = static
    buildir = build
    trybuild = make
    host = linux
}
project.filelock
make VERBOSE=1 -j12
***
*** Configuration file ".config" not found!
***
*** Please run some configurator (e.g. "make oldconfig" or
*** "make menuconfig" or "make xconfig").
***
make: *** [Makefile:689: .config] Error 1
error: @programdir/core/main.lua:284: @programdir/core/sandbox/modules/os.lua:387: execv(make VERBOSE=1 -j12) failed(2)
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:792]: in function 'raise'
    [@programdir/core/sandbox/modules/os.lua:387]: in function 'vexecv'
    [@programdir/modules/private/action/trybuild/make.lua:54]: in function 'build'
    [@programdir/actions/build/main.lua:76]: in function '_try_build'
    [@programdir/actions/build/main.lua:85]:
    [C]: in function 'load'
    [@programdir/core/base/task.lua:520]: in function 'run'
    [@programdir/core/main.lua:282]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:792: in function 'raise'
        @programdir/core/main.lua:284: in function 'cotask'
        @programdir/core/base/scheduler.lua:317: in function <@programdir/core/base/scheduler.lua:315>
```

**Comment by waruqi** [comment]
> project/project.lua:149: cannot create the project lock!

oh, I see that this problem has been solved. Maybe you set XMAKE_ROOT to make it work.

**Comment by waruqi** [comment]
> as root
> 
> ```
> note: Makefile found, try building it or you can run `xmake f --trybuild=` to set buildsystem (pass -y or --confirm=y/n/d to skip confirm)?
> please input: y (y/n)
> y
> project.filelock
> openlock        /srv/src/linux/5.7/.xmake/linux/x86_64/project.lock
> [xmake]: [filelock_open]: tb_filelock_init_from_path: 0x5d6b40, tryn: 1, errno: 2 No such file or directory
> result  <filelock: ..6_64/project.lock>
> checking for the architecture ... x86_64
> checking for the gcc ... /usr/bin/gcc
> configure
> {
>     arch = x86_64
>     ccache = true
>     mode = release
>     ndk_stdcxx = true
>     plat = linux
>     kind = static
>     buildir = build
>     trybuild = make
>     host = linux
> }
> project.filelock
> make VERBOSE=1 -j12
> ***
> *** Configuration file ".config" not found!
> ***
> *** Please run some configurator (e.g. "make oldconfig" or
> *** "make menuconfig" or "make xconfig").
> ***
> make: *** [Makefile:689: .config] Error 1
> error: @programdir/core/main.lua:284: @programdir/core/sandbox/modules/os.lua:387: execv(make VERBOSE=1 -j12) failed(2)
> stack traceback:
>     [C]: in function 'error'
>     [@programdir/core/base/os.lua:792]: in function 'raise'
>     [@programdir/core/sandbox/modules/os.lua:387]: in function 'vexecv'
>     [@programdir/modules/private/action/trybuild/make.lua:54]: in function 'build'
>     [@programdir/actions/build/main.lua:76]: in function '_try_build'
>     [@programdir/actions/build/main.lua:85]:
>     [C]: in function 'load'
>     [@programdir/core/base/task.lua:520]: in function 'run'
>     [@programdir/core/main.lua:282]: in function 'cotask'
>     [@programdir/core/base/scheduler.lua:317]:
> 
> stack traceback:
>         [C]: in function 'error'
>         @programdir/core/base/os.lua:792: in function 'raise'
>         @programdir/core/main.lua:284: in function 'cotask'
>         @programdir/core/base/scheduler.lua:317: in function <@programdir/core/base/scheduler.lua:315>
> ```

This is just a problem with the makefile of the third-party library. If you need to use xmake to compile, you need to write the xmake.lua file

**Comment by n8v8R** [comment]
It came down to file permission on the git worktree when running as user other than root, sorted now with ACL. Pardon the waste of your time :bowing_woman: 

And thank you for this nice bit of code!
