### ISSUE TITLE
希望添加构建好的二进制包

### ISSUE THREAD

**Issue by skyfireitdiy** [xmake-io/xmake#904]
### 你在什么场景下需要该功能？

公司由于信息安全原因无法通过 git 等版本控制工具从 gitee 或者 github 下载源码，那么就无法使用`bash <(curl -fsSL https://xmake.io/shget.text)`去安装 xmake 。

### 描述可能的解决方案

希望可以提供二进制包或者一份手工编译指导手册。

### 描述你认为的候选方案

尽量可以提供二进制包，rpm 和 deb 或者单纯的xmake可执行文件

**Comment by skyfireitdiy** [comment]
好像有提供，我没有看到，抱歉

**Comment by waruqi** [comment]
releases下有 deb 或者 gz.run 的自安装包都可以，.run的所有linux/macos都通用 可以直接运行安装
