### ISSUE TITLE
xmake f --menu报错

### ISSUE THREAD

**Issue by username-ui** [xmake-io/xmake#905]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
运行xmake f --menu 报错 error: attempt to call field 'isdone' (a nil value)

### Error output
error: attempt to call field 'isdone' (a nil value)

### Related Environment

Please provide compiling and running environment information:

- xmake version:v2.3.6
- os:winows10  2004 19041.388
- target platform:x64

**Comment by waruqi** [comment]
I have fixed it, you can update to dev branch and try it again.

```console
$ xmake update dev
$ xmake f --menu
```

Or you can download the dev version from https://github.com/xmake-io/xmake/actions/runs/187948204
