### ISSUE TITLE
Merging static libraries

### ISSUE THREAD

**Issue by interkosmos** [xmake-io/xmake#909]
### Describe the problem details
Given are source files in an arbitrary language (C, Fortran, …) that compile to several static libraries:

```
target("mylib1")
    set_kind("static")
    add_files("src/mylib1/*.c")

target("mylib2")
    set_kind("static")
    add_files("src/mylib2/*.c")
```

Is there an easy way in xmake to create a shared library out of the the two targets? This obviously doesn’t work:

```
target("merged")
    set_kind("static")
    add_deps("mylib1")
    add_deps("mylib2")  
```

**Comment by waruqi** [comment]
You can see https://github.com/xmake-io/xmake/blob/master/tests/projects/other/merge_archive/xmake.lua

**Comment by interkosmos** [comment]
Thank you.
