### ISSUE TITLE
Grouping targets

### ISSUE THREAD

**Issue by interkosmos** [xmake-io/xmake#911]
### Describe the problem details
Is there any way in xmake to group multiple targets? Say, targets `test1` and `test2` are defined, as well as a group `examples` that includes both targets. When xmake is run, like, `xmake examples`, both targets will be build.

**Comment by waruqi** [comment]
You  can add_deps("test2") to target test1 and ony run `xmake build test1`

or you can define a task("examples") and call task.run("build", {"test1", "test2"}) to build these targets.  see https://xmake.io/#/manual/plugin_task?id=task

**Comment by interkosmos** [comment]
But using tasks requires to define a menu, correct?

**Comment by waruqi** [comment]
> But using tasks requires to define a menu, correct?

Yes, if you want to perform this task on the command line, you need to define a menu to describe the command options. Of course you can define the simplest empty menu.

**Comment by waruqi** [comment]
for example:

```lua
task("examples")
    set_menu {usage = "xmake examples [options]",  description="xxx", options = {}}
    on_run(function ()
        import("core.base.task")
        task.run("build", {}, "test1")    -----> xmake build test1
        task.run("build", {rebuild = true}, "test2")  -----> xmake build -r test2

        -- or you can call the following command, but it will create subprocess/xmake to run them. 
        -- os.exec("xmake build test1")
        -- os.exec("xmake build test2")
    end)
```

```console
$ xmake examples
```

**Comment by interkosmos** [comment]
Thank you for the verbose examples. Works fine.
