### ISSUE TITLE
xmake project -k make 生成的makefile无法正常执行

### ISSUE THREAD

**Issue by username-ui** [xmake-io/xmake#913]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
xmake project -k make 生成的makefile无法正常执行

### Error output
makefile:20: *** commands commence before first target.  Stop.

### Related Environment

Please provide compiling and running environment information:

- xmake version:xmake v2.3.6+202007300945
- os:windows

###生成的Makefile

CXX=D:\Program Files\LLVM\bin\clang++.exe

LD=D:\Program Files\LLVM\bin\clang++.exe

Test_CXXFLAGS=-fvisibility=hidden -Qunused-arguments
Test_LDFLAGS=-s

default:  Test

all:  Test

.PHONY: default all  Test

Test: build\cxx=cl.exe\none\release\Test
build\cxx=cl.exe\none\release\Test: build\.objs\Test\cxx=cl.exe\none\release\src\main.cpp.o
	@echo linking.release Test
	@mkdir -p build\cxx=cl.exe\none\release
	@"D:\\Program Files\\LLVM\\bin\\clang++.exe" -o build\cxx=cl.exe\none\release\Test build\.objs\Test\cxx=cl.exe\none\release\src\main.cpp.o $(Test_LDFLAGS) > build/.build.log 2>&1

build\.objs\Test\cxx=cl.exe\none\release\src\main.cpp.o: src\main.cpp
	@echo compiling.release src\main.cpp
	@mkdir -p build\.objs\Test\cxx=cl.exe\none\release\src
	@"D:\\Program Files\\LLVM\\bin\\clang++.exe" -c $(Test_CXXFLAGS) -o build\.objs\Test\cxx=cl.exe\none\release\src\main.cpp.o src\main.cpp > build/.build.log 2>&1

clean:  clean_Test

clean_Test: 
	@rm -f build\cxx=cl.exe\none\release\Test
	@rm -f build\.objs\Test\cxx=cl.exe\none\release\src\main.cpp.o

**Comment by username-ui** [comment]
![image](https://user-images.githubusercontent.com/56100274/89096801-eaf6e800-d40b-11ea-9f32-30ac98f08482.png)

**Comment by waruqi** [comment]
你这是windows上，但是看生成的makefile是 gnu makefile 。。你不是cmd下执行呢？

目前的策略是这样的

1. 如果是cmd下执行的，生成的是nmake的makefile，完全支持cmd里面的各种命令和语法（比如 del），直接使用 `nmake -f makefile`就可以编译

2. 如果是msys/cygwin下，默认生成的应该是 gnu makefile，里面用的是linux的命令，比如rm什么的，应该使用gnu make去编译。

不过你这里比较怪的并不是nmake还是gnumake，是生成的里面是这样的：

> @mkdir -p build\cxx=cl.exe\none\release


plat平台为啥是`cxx=cl.exe`，arch是none 好奇怪，你的`xmake f`配置命令能贴我看下么？

或者你在生成前，先强行清下配置缓存，重置下plat/arch再试试呢？

```console
$ xmake f -c
$ xmake project -k make
```

你可以对比下我这里的生成结果：

```
-@mkdir build\windows\x64\minsizerel > NUL 2>&1
```

plat/arch都是正常的windows/x64

```
# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

MRC=C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\rc.exe
CC=C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29109\bin\HostX64\x64\cl.exe
CXX=C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29109\bin\HostX64\x64\cl.exe
AS=C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29109\bin\HostX64\x64\ml64.exe

SH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29109\bin\HostX64\x64\link.exe
LD=C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29109\bin\HostX64\x64\link.exe
AR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.27.29109\bin\HostX64\x64\link.exe

test_CXXFLAGS=-O1 -GL -nologo
test_LDFLAGS=/opt:ref /opt:icf /ltcg -nologo -dynamicbase -nxcompat -machine:x64

default:  test

all:  test

.PHONY: default all  test

test: build\windows\x64\minsizerel\test.exe
build\windows\x64\minsizerel\test.exe: build\.objs\test\windows\x64\minsizerel\src\main.cpp.obj
	@echo linking.minsizerel test.exe
	-@mkdir build\windows\x64\minsizerel > NUL 2>&1
	@"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Preview\\VC\\Tools\\MSVC\\14.27.29109\\bin\\HostX64\\x64\\link.exe" $(test_LDFLAGS) -out:build\windows\x64\minsizerel\test.exe build\.objs\test\windows\x64\minsizerel\src\main.cpp.obj > build/.build.log 2>&1

build\.objs\test\windows\x64\minsizerel\src\main.cpp.obj: src\main.cpp
	@echo compiling.minsizerel src\main.cpp
	-@mkdir build\.objs\test\windows\x64\minsizerel\src > NUL 2>&1
	@"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Preview\\VC\\Tools\\MSVC\\14.27.29109\\bin\\HostX64\\x64\\cl.exe" -c $(test_CXXFLAGS) -Fobuild\.objs\test\windows\x64\minsizerel\src\main.cpp.obj src\main.cpp > build/.build.log 2>&1

clean:  clean_test

clean_test: 
	@del /F /Q build\windows\x64\minsizerel\test.exe > NUL 2>&1
	@del /F /Q build\.objs\test\windows\x64\minsizerel\src\main.cpp.obj > NUL 2>&1
```

**Comment by username-ui** [comment]
每当我想要试着设置platform和arch时,xmake都会报错,所以我就一直没有设置xmake的platform和arch,但最近这个问题好像得到了解决.
具体报错如下
error:系统未能找到指定路径
系统未能找到指定路径
系统未能找到指定路径
系统未能找到指定路径
系统未能找到指定路径

**Comment by waruqi** [comment]
> 每当我想要试着设置platform和arch时,xmake都会报错,所以我就一直没有设置xmake的platform和arch

你就贴下你是怎么设置的，报的错误信息，不然我不知道是哪里的问题

> 但最近这个问题好像得到了解决.
> 具体报错如下
> error:系统未能找到指定路径
> 系统未能找到指定路径
> 系统未能找到指定路径
> 系统未能找到指定路径
> 系统未能找到指定路径

请贴下你的xmake f配置命令，否则我不知道问题原因，另外请尝试运行我上文说的`xmake f -c`

**Comment by username-ui** [comment]
未能找到路径的错误已经解决了,但我并不知道是怎么被解决的.
我的xmake配置命令
xmake f --cxx="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\Llvm\x64\bin\clang.exe"
xmake f -p windows -a x64 -m release

**Comment by waruqi** [comment]
为啥要分开执行两遍 xmake f，只能一次完整配置，否则只会使用最后一次配置

**Comment by waruqi** [comment]
那就是暂时没问题咯？那我先 close 了，回头有问题 再开新 issues 好了。
