### ISSUE TITLE
bad light userdata pointer

### ISSUE THREAD

**Issue by wangzhankun** [xmake-io/xmake#914]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

当执行```bash <(curl -fsSL https://xmake.io/shget.text)```进行xmake编译时遇到下面的问题：
![image](https://user-images.githubusercontent.com/35724924/89101324-7afb5880-d431-11ea-8ab3-f207535a79ae.png)

我在其他地方见到了类似的错误https://github.com/torch/torch7/issues/1035 和 https://github.com/neovim/neovim/issues/7879

从这两个帖子可以看出来应该是lua的问题，但是我不确定该怎么处理，不确定xmake是否可以避免该问题。如果不可以的是否有什么方法可以将xmake的工程转成cmake之类的工程的命令吗？

### 期待的结果
可以在ubuntu18.04 server aarch64上正常安装xmake。

### 相关环境

- 树莓派4b
- ubuntu server18.04 
- Linux ubuntu 5.3.0-1017-raspi2 18.04.1-Ubuntu SMP Fri Jan 17 11:14:07 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

**Comment by waruqi** [comment]
哦 你是 arm64的linux，这个之前可以 只不过好久没测了，可能后来bytecode的改动导致了问题，你可以先其他机器上 xmake project -k cmake 生成cmakelists来编译试试

我现在没环境，等部署好环境我才能测试下。

**Comment by waruqi** [comment]
你可以先自己拉取代码编译装，跳过bytecode gen应该是可以过掉这个问题的 你先试试

```console
git clone https://github.com/xmake-io/xmake.git
cd ./xmake
git submodule update --init
make build
make install
```

**Comment by wangzhankun** [comment]
> 你可以先自己拉取代码编译装，跳过bytecode gen应该是可以过掉这个问题的 你先试试
> 
> ```
> git clone https://github.com/xmake-io/xmake.git
> cd ./xmake
> git submodule update --init
> make build
> make install
> ```

可以正常安装，但是无法运行。
![image](https://user-images.githubusercontent.com/35724924/89117182-80f34700-d4ce-11ea-9389-ab64b26a1530.png)

**Comment by waruqi** [comment]
那等周一我再看下，现在我没arm64的环境

**Comment by waruqi** [comment]
看着跟arm64下 linux kernel 的虚拟地址超过48bits 存储到lightdata之后会出问题，一些相关workaround方案：

https://github.com/LuaJIT/LuaJIT/pull/230
https://github.com/LuaJIT/LuaJIT/pull/245/files
https://github.com/debayang/lua-nginx-module/commit/543a722ec585d0cacb5223122c6f7e252ca75edd
https://github.com/zhaozg/luv/commit/43f120ccc07fd084a7faf35ad7aa643990ad7de7


不过我搞了个ubuntu arm64的环境，似乎一切正常，可以正常安装运行，还是没法复现问题。。我得先尝试复现下 才能想办法看看怎么修复。

**Comment by wangzhankun** [comment]
好的，我明天看一下解决方案。我这个平台感觉还不完全是arm64的架构，因为我在jetson nano上是正常的。jetson nano是完全正常的arm64架构。树莓派的话，我在raspberry pi官方32位系统上是完全正常的。但是rasbian系统对多线程支持度不好，所以重新刷入了Ubuntu server18.04 64位的系统,然后就出问题了。你要不尝试在qemu下仿真一下树莓派4用Ubuntu server引导一下。

**Comment by wangzhankun** [comment]
> 看着跟arm64下 linux kernel 的虚拟地址超过48bits 存储到lightdata之后会出问题，一些相关workaround方案：
> 
> [LuaJIT/LuaJIT#230](https://github.com/LuaJIT/LuaJIT/pull/230)
> https://github.com/LuaJIT/LuaJIT/pull/245/files
> [debayang/lua-nginx-module@543a722](https://github.com/debayang/lua-nginx-module/commit/543a722ec585d0cacb5223122c6f7e252ca75edd)
> [zhaozg/luv@43f120c](https://github.com/zhaozg/luv/commit/43f120ccc07fd084a7faf35ad7aa643990ad7de7)
> 
> 不过我搞了个ubuntu arm64的环境，似乎一切正常，可以正常安装运行，还是没法复现问题。。我得先尝试复现下 才能想办法看看怎么修复。

要不你试下ubuntu server 18.04吧，[下载页面](https://ubuntu.com/download/raspberry-pi)，
![image](https://user-images.githubusercontent.com/35724924/89138378-fcf09c00-d56d-11ea-9ec3-cfbba6b87b0e.png)

**Comment by waruqi** [comment]
感觉好折腾，暂时没这么多时间捣鼓环境，如果有直接可用的docker image就好了，等回头有时间我再看看吧。

**Comment by waruqi** [comment]
我在raspi64分支加了点log，先确认下到底是哪几处lua_pushlightuserdata处理的pointer超过了 47bits，我回头直接改好了。折腾环境太浪费时间了

```console
git fetch origin raspi64
git checkout raspi64
make build
source ./script/srcenv.profile    <-- 这里面也会执行 xmake --version 应该就会报错
xmake --version 
```

然后把所有log发我看下。

**Comment by wangzhankun** [comment]
这个是执行```source scripts/srcenv.profile```的报错：
```bash
[xmake]: [file_open]: xm_io_file_open: lua_pushlightuserdata: 0xaaaad75802b0
error: bad light userdata pointer
[xmake]: [file_open]: xm_io_file_open: lua_pushlightuserdata: 0xaaaae553e2b0
error: bad light userdata pointer
[xmake]: [file_open]: xm_io_file_open: lua_pushlightuserdata: 0xaaaae01852b0
error: bad light userdata pointer

```

**Comment by wangzhankun** [comment]
我这里找到了一个qemu的脚本测试通过了。在系统里面尝试安装xmake碰到了相同的问题。
```bash
#!/usr/bin/env bash

set -eux

# Tested on Ubuntu 18.10.
# - https://superuser.com/questions/942657/how-to-test-arm-ubuntu-under-qemu-the-easiest-way
# - https://askubuntu.com/questions/797599/how-to-run-ubuntu-16-04-arm-in-qemu

# Parameters.
# This filename may need updating, check http://cdimage.ubuntu.com/releases/18.04/release/
id=ubuntu-18.04.3-server-arm64   
#id=debian-9.6.0-arm64-xfce-CD-1
img="${id}.img.qcow2"
img_snapshot="${id}.img.snapshot.qcow2"
iso="${id}.iso"
flash0="${id}-flash0.img"
flash1="${id}-flash1.img"

# Images.
if [ ! -f "$iso" ]; then
  wget "http://cdimage.ubuntu.com/releases/18.04/release/${iso}"
fi
if [ ! -f "$img" ]; then
  qemu-img create -f qcow2 "$img" 1T
fi
if [ ! -f "$img_snapshot" ]; then
  qemu-img \
    create \
    -b "$img" \
    -f qcow2 \
    "$img_snapshot" \
  ;
fi
if [ ! -f "$flash0" ]; then
  dd if=/dev/zero of="$flash0" bs=1M count=64
  dd if=/usr/share/qemu-efi/QEMU_EFI.fd of="$flash0" conv=notrunc
fi
if [ ! -f "$flash1" ]; then
  dd if=/dev/zero of="$flash1" bs=1M count=64
fi

# Run.
#
# cdrom must be scsi or else the installation fails midway with:
#
# > Detect and mount CD-ROM
# >
# > Your installation CD-ROM couldn't be mounted. This probably means
# > that the CD-ROM was not in the drive. If so you can insert it and try
# > again.
# >
# > Retry mounting the CD-ROM?
# > Your installation CD-ROM couldn't be mounted.
#
# This is because the drivers for the default virtio are not installed in the ISO,
# because in the past it was not reliable on qemu-system-aarch64.
#
# See also:
# https://bazaar.launchpad.net/~ubuntu-testcase/ubuntu-manual-tests/trunk/view/head:/testcases/image/1688_ARM64_Headless_KVM_Guest
qemu-system-aarch64 \
  -cpu cortex-a57 \
  -device rtl8139,netdev=net0 \
  -device virtio-scsi-device \
  -device scsi-cd,drive=cdrom \
  -device virtio-blk-device,drive=hd0 \
  -drive "file=${iso},id=cdrom,if=none,media=cdrom" \
  -drive "if=none,file=${img_snapshot},id=hd0" \
  -m 2G \
  -machine virt \
  -netdev user,id=net0 \
  -nographic \
  -pflash "$flash0" \
  -pflash "$flash1" \
  -smp 2 \
;
```
直接执行运行即可。我在ubuntu18.04下执行通过了。登录的账号是```ubuntu```，密码是```asdfqwer```

**Comment by waruqi** [comment]
我这里是mac环境，这个脚本跑不起来，cloud-localds没这命令，user-data.img也没有, QEMU_EFI.fd我倒是下了一个。不过mac的dd也跟linux的不同，反正改动还挺多，就不折腾了。。

大概我也知道了，反正是pointer值过大的问题，xmake里面就那么几处用了lightuserdata，回头我改下就好

**Comment by waruqi** [comment]
这块牵扯的东西还比较多，可能要花点时间改下 等改完你再试试

**Comment by waruqi** [comment]
我改了下，应该可以了的，你拉下dev分支源码安装下试试，我对lua_pushlightuserdata做了层workaround wrap，但仅对于47bits高地址pointer生效，所以平常的arm64/x86_64设备基本上还是走原来的逻辑。

只有部分存在高地址的aarch64设备才会切到workaround模式。

https://github.com/xmake-io/xmake/blob/96b0eae26058482a83f5bbf57bab15a834339464/core/src/xmake/prefix.h#L36-L83

**Comment by wangzhankun** [comment]
非常感谢，现在测试成功了。有一个其他的问题，就是为啥我进行编译的时候总是提醒我要安装openssl呢，而我没有用到相关的内容。

**Comment by waruqi** [comment]
> 非常感谢，现在测试成功了。有一个其他的问题，就是为啥我进行编译的时候总是提醒我要安装openssl呢，而我没有用到相关的内容。

那是因为你执行的是 get.sh 那个一键安装脚本，这个会自动安装一些build需要的基础依赖，比如git, gcc啥的，可能内部依赖带上了openssl吧。。

https://github.com/xmake-io/xmake/blob/db31246f1fa9d00cdc3d4bc5ed82213e46fa0d7d/scripts/get.sh#L152

**Comment by wangzhankun** [comment]
是这样的，就是我在输入```xmake```编译我的项目的过程中出现的，而且导出```cmakelists```之后也是会有openssl的链接，但是我并没有用到过，我把```cmakelists```里面的```openssl```删除掉之后也是可以正常编译的，因为我的项目确实没有用到这个库，在```xmake.lua```里面也没有添加```openssl```。原来在其他平台上我都是输入```n```不安装，但是今天我在树莓派上编译的时候不安装的话不能正常编译。感觉这个又跟平台没啥关系。因为我在x86_64平台下遇到相同的问题，而且会提醒我安装```opencv4```，因为我用到了这个动态库，但是我在本地已经自行编译安装过了。

**Comment by waruqi** [comment]
那就要看你add_requires加了哪些依赖库了 有些依赖库内部会依赖openssl

**Comment by waruqi** [comment]
那就要看你add_requires加了哪些依赖库了 有些依赖库内部会依赖openssl

**Comment by waruqi** [comment]
这是另外一个问题 如果觉得有问题 那就提个issues

**Comment by wangzhankun** [comment]
好的，谢谢

**Comment by waruqi** [comment]
这两天，luajit作者终于修掉这个问题了 https://github.com/LuaJIT/LuaJIT/commit/e9af1abec54

不必再用workaround方案了，不过要升级下luajit才行，前阵子刚升级了一遍，蛋疼~ 

等回头空了，我再升级一波好了

**Comment by waruqi** [comment]
我升级了luajit 并且去除了之前的workaround patch，你可以再更新到dev试试，应该还是可以正常运行的

**Comment by wangzhankun** [comment]
好的，感谢。等过两天回学校试一下

**Comment by wangzhankun** [comment]
> 我升级了luajit 并且去除了之前的workaround patch，你可以再更新到dev试试，应该还是可以正常运行的

好的，感谢。Dev分支我重新编译了一下是可以正常编译安装的

**Comment by waruqi** [comment]
arm64上运行也正常吗？

**Comment by wangzhankun** [comment]
是的，在树莓派4b上跑的，OS是ubuntu server18.04
