### ISSUE TITLE
[feature suggestion] support ipk packaging

### ISSUE THREAD

**Issue by n8v8R** [xmake-io/xmake#915]
It would handy if *opkg-utils* integrated support could be considered, bridging the gap from compiled code to portable package.

* info https://git.yoctoproject.org/cgit/cgit.cgi/opkg-utils
* repo http://git.yoctoproject.org/cgit/cgit.cgi/opkg/

**Comment by waruqi** [comment]
Can it only be used on openwrt system, can it be used on ubuntu x86_64?

**Comment by n8v8R** [comment]
Debian is not packing it (neither Ubuntu). It can be compiled/installed/used however on any Debian x86_64 derivate node, if that what you are asking?

**Comment by waruqi** [comment]
ok, I will consider supporting it, but I am not sure that it will be supported in this version, please be patient for a while.

Or you can try to support it yourself, just refer to the implementation of other package management modules, for example: https://github.com/xmake-io/xmake/tree/master/xmake/modules/package/manager

**Comment by n8v8R** [comment]
Likely I have been misleading with the initial post... Did not mean that _xamke_ to support _opkg_ (package installation/removal) but rather the creation of portable _ipk_ packages (when cross compiling) for the compiled code.

For that the _opkg-utils_ scripts (https://git.yoctoproject.org/cgit/cgit.cgi/opkg-utils) might be reusable in _xmake_.

https://raymii.org/s/tutorials/Building_IPK_packages_by_hand.html#toc_2
>ipk is an archive (either tar or ar or gzip)

**Comment by waruqi** [comment]
Oh, we do not consider support for this at present, usually only the user needs to implement the on_package script by themselves.

for example:

```lua
target("test")
    add_files("src/*.c")
    on_package(function (target)
        os.exec("opkg ...")
    end)
```

Or you can write a custom rule to support it.

```lua
rule("opkg")
    on_package(function (target)
        os.exec("opkg ...")
    end)

target("test")
    add_files("src/*.c")
    add_rules("opkg")
```
