### ISSUE TITLE
failed to run: xmake f --test=hello

### ISSUE THREAD

**Issue by guyansrg** [xmake-io/xmake#917]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
failed to run xmake f --test=hello.

### Expected behavior
Run xmake f --test=hello successful.

### Error output
<pre>
$ xmake f --test=hello
checking for the architecture ... x86_64
--> test=hello
error: ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:47: bad argument #1 to 'getfenv' (number expected, got table)
stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:792: in function 'raise'
        ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:47: in function 'co_start_named'
        @programdir/modules/private/async/runjobs.lua:180: in function <@programdir/modules/private/async/runjobs.lua:139>
        [C]: in function 'trycall'
        @programdir/core/base/scheduler.lua:423: in function 'co_group_begin'
        ...mdir/core/sandbox/modules/import/core/base/scheduler.lua:85: in function 'co_group_begin'
        @programdir/modules/private/async/runjobs.lua:139: in function <@programdir/modules/private/async/runjobs.lua:54>
        ...dir/core/sandbox/modules/import/core/project/project.lua:112: in function 'check'
        @programdir/actions/config/main.lua:253: in function <@programdir/actions/config/main.lua:138>
        [C]: in function 'load'
        @programdir/core/base/task.lua:520: in function 'run'
        @programdir/core/main.lua:282: in function 'cotask'
        @programdir/core/base/scheduler.lua:317: in function <@programdir/core/base/scheduler.lua:315>
</pre>

> If it is a xmake related compilation problem, please add the `-v -D` parameter and give the detailed compilation output information.

### Related Environment

Please provide compiling and running environment information:

- xmake version: v2.3.6+202007280927
- os: Ubuntu Server 20.04
- target platform: linux x86_64

### Additional context
xmake.lua
<pre>
-- 自定义一个配置选项到命令行菜单
option("test")
    set_showmenu("true")
    set_description("The test config option")
option_end()

-- 如果自定义的test配置值是hello1或者hello2
if is_config("test", "hello", "hello1", "hello2") then
    add_defines("HELLO")
    print("--> test=hello")
end

-- add modes: debug and release
add_rules("mode.debug", "mode.release")

-- add target
target("hello")

    -- set kind
    set_kind("binary")

    -- add files
    add_files("src/*.cpp")
</pre>

**Comment by waruqi** [comment]
> set_showmenu("true")

这里改成，`set_showmenu(true)`

然后更新下 `xmake update dev` 到dev分支，我修复了。。另外，建议加上 `set_default("")` 设置上默认值，就不会触发额外不必要的check操作。

**Comment by guyansrg** [comment]
It's **OK** now.
Thank you very much!
