### ISSUE TITLE
set_targetdir not setting the path to given output directory

### ISSUE THREAD

**Issue by n8v8R** [xmake-io/xmake#919]
### Describe the bug
`set_targetdir` does not set the path to given output directory

### Expected behavior
`set_targetdir` to set the path to given output directory

### Error output
no errors are printed, setting the path just does not happen

### Related Environment

Please provide compiling and running environment information:

- xmake version: v2.3.6+202008110211
- os: linux

### Additional context

`xmake f -o /test` works as expected however _xmake.lua_ file with

```
target("name")
    set_targetdir("/test")
```
does not.

**Comment by waruqi** [comment]
Please let me the verbose output. `xmake -v`

```
target("name")
    set_targetdir("/test")
```

There is not any source files and no target kind.

```
target("name")
    set_kind("binary")
    set_targetdir("/test")
    add_files("src/*.c")
```

**Comment by n8v8R** [comment]
Well, it works but strangely `xmake show` does not exhibit the path with under `buildir` whilst it show correctly when setting the path with `xmake f -o /test`

**Comment by waruqi** [comment]
set_targetdir only for the given target, but `-o buildir` for all targets, it is global.
