### ISSUE TITLE
Better incooperation of other xmake projects

### ISSUE THREAD

**Issue by PucklaMotzer09** [xmake-io/xmake#924]
### Is your feature request related to a problem? Please describe.
I have been working on a library that I published as a seperate project. Then I wanted to implement this library into another project. Both projects are using xmake to build the source code. I thought that I could somehow just import said library into my new project, but this feature seems to be missing.

### Describe the solution you'd like
I imagined that you could somehow import the porject, either a git repository (the library I wrote is a git repository) or a local folder. I would implement this like this:
1. Include the project
 a. git repository: ```add_project("my_other_project", "https://github.com/username/my_other_project.git", {git_repo = true})```
 b. folder: ```add_project("my_other_project", "C:\\Projects\\my_other_project")```
2. Then declare dependencies similiar as you would with targets of the current project
```add_deps("my_other_project@target_name")```

I don't know how hard this is to implement or if there's a paticular reason for why this feature doesn't exist, but it would certainly improve the usability of xmake.

### Describe alternatives you've considered
The workaround in my case was to package to library using ```xmake package``` and then loading all files into a **packages** directory of my new project, but I don't want to load built libraries into my repository or force other people to manually download, built and package my dependencies.

### Additional context
I am pretty new to xmake, so there might even be such a feature. Otherwhise I would really appreciate the implementation of said feature.

**Comment by waruqi** [comment]
You can use `package()` to define your package and use add_requires()/add_packages() to add your package to the given target.

You can see https://xmake.io/#/package/remote_package?id=using-self-built-private-package-repository

An example project 

https://github.com/tboox/benchbox

**Comment by PucklaMotzer09** [comment]
I actually looked at https://xmake.io/#/package/remote_package?id=using-self-built-private-package-repository. But couldn't find anything that satifies me. But now I looked at https://github.com/tboox/benchbox and I found the following code inside the **xmake.lua** of the **coroutine** package.

```lua
package("coroutine")

    set_homepage("https://github.com/cloudwu/coroutine")
    set_description("A asymmetric coroutine library for C.")

    set_urls("https://github.com/cloudwu/coroutine.git")

    on_install("linux", function (package)
        import("package.tools.xmake").install(package)
        os.cp("coroutine.h", package:installdir("include", "coroutine"))
    end)
```

This code suggests that you can just automatically install a xmake package using
```lua
import("package.tools.xmake").install(package)
```
when used in ```on_install```. Is this right? I looked at https://github.com/cloudwu/coroutine and it is not a xmake project. It just has a Makefile. Is it possible to use the same code for a project using xmake? Would this automatically create a .pkg folder with all the libraries? If so, this would satisfy my request.

**Comment by PucklaMotzer09** [comment]
Now I found this code:
```lua
package("libaco")

    set_homepage("https://github.com/hnes/libaco")
    set_description("A blazing fast and lightweight C asymmetric coroutine library.")

    set_urls("https://github.com/hnes/libaco.git")

    on_install("macosx", "linux", function (package)
        io.writefile("xmake.lua", [[
            add_rules("mode.debug", "mode.release")
            target("aco")
                set_kind("static")
                add_files("aco.c")
                add_files("acosw.S")
                add_headers("*.h")
        ]])
        import("package.tools.xmake").install(package)
    end)
```

This suggests exactly what I said. So it is possible to use it for xmake projects. Thank you for guiding me to right direction.

**Comment by waruqi** [comment]
If your other independent libraries are also maintained by xmake, then you can also use git submodule, and directly use the includes() interface to import them, then you can directly run the xmake command to compile all, and use add_deps to key your Dependent library

Of course, you can also use the method in benchbox to import the packages you define through add_requires. In on_install, you can also call other build systems to compile and install them.

**Comment by PucklaMotzer09** [comment]
I tried this in an example project, but I ran into some issues. The package could not be found.
**xmake.lua**
```lua
set_project("test")

add_repositories("test-repo repo")

add_requires("moviemaker-cpp")

target("test")
    set_kind("binary")

    add_packages("moviemaker-cpp")
    
    if is_os("windows") then
        add_links("ole32", "Ws2_32", "Secur32", "user32", "Bcrypt")
    end

    add_files("test.cpp")

```

**test.cpp**
```cpp
#include <iostream>

int main(int argc, char *argv[]) {
  std::cout << "Hello World" << std::endl;

  return 0;
}
```

**Output** of ```xmake f -c -vD```
```
checking for the architecture ... x64
checking for the vswhere.exe ... C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
checking for the cl.exe ... C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\cl.exe
checking for the Microsoft Visual Studio (x64) version ... 2019
checking for the dmd ... no
checking for the ldc2 ... no
checking for the gdc ... no
checking for the unzip ... ok
checking for the git ... ok
checking for the gzip ... no
checking for the 7z ... ok
checking for the ping ... ok
pinging for the host(gitlab.com) ... 4 ms
pinging for the host(github.com) ... 17 ms
pinging for the host(gitee.com) ... 216 ms
error: @programdir\core\main.lua:284: @programdir\actions\require\impl\package.lua:247: package(moviemaker-cpp latest): not found!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:792]: in function 'raise'
    [@programdir\actions\require\impl\package.lua:247]: in function '_select_package_version'
    [@programdir\actions\require\impl\package.lua:331]: in function '_load_package'
    [@programdir\actions\require\impl\package.lua:375]: in function '_load_packages'
    [@programdir\actions\require\impl\package.lua:729]: in function 'load_packages'
    [@programdir\actions\require\impl\package.lua:747]: in function 'install_packages'
    [@programdir\actions\require\install.lua:162]: in function 'install_requires'
    [@programdir\actions\config\main.lua:272]:
    [C]: in function 'load'
    [@programdir\core\base\task.lua:520]: in function 'run'
    [@programdir\core\main.lua:282]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:792: in function 'raise'
        @programdir\core\main.lua:284: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>

```
Contents of **repo** directory:
```
packages
    - m
        - moviemaker-cpp
            xmake.lua
```
**packages/m/moviemaker-cpp/xmake.lua**
```lua
package("moviemaker-cpp")
    set_homepage("https://github.com/PucklaMotzer09/moviemaker-cpp")

    set_urls("https://github.com/PucklaMotzer09/moviemaker-cpp")
    set_description("Encode video frame by frame in C++ using FFmpeg")

    on_install(function(package)
        import("package.tools.xmake").install(package)
        os.cp("include/movie.h", package:installdir("include", "movie.h"))
    end)

```

**Comment by PucklaMotzer09** [comment]
How would the git submodules approach look like? Is there an example project?

**Comment by waruqi** [comment]
> https://github.com/cloudwu/coroutine and it is not a xmake project. It just has a Makefile. Is it possible to use the same code for a project using xmake?

xmake will scan source files and generate a xmake.lua automaticall. then try build it.

**Comment by PucklaMotzer09** [comment]
> xmake will scan source files and generate a xmake.lua automatically. then try build it.

That's a really good build system. It seems that ```import("package.tools.xmake").install(package)``` isn't documented anywhere.

**Comment by waruqi** [comment]
This is not there yet, you can look at the code directly. https://github.com/xmake-io/xmake/blob/master/xmake/modules/package/tools/xmake.lua

**Comment by waruqi** [comment]
> How would the git submodules approach look like? Is there an example project?

you can see https://github.com/xmake-io/xmake/tree/master/core

**Comment by waruqi** [comment]
> I tried this in an example project, but I ran into some issues. The package could not be found.
xmake.lua

where is the path of this repo?

you can run `xmake repo -l` and `xmake reuqire --info moviemaker-cpp` to look at it.

**Comment by Sahnvour** [comment]
How would you set up a super-project that is composed of multiple sub-projects in different repositories ?

Contrived example: you have libraries `foo`, `bar` and the project `baz`.
Each one of these is defined in xmake, `bar` depends on `foo`, and `baz` depends both on `foo` and `bar`.
Each one of these projects are actively being worked on, ie. it's very convenient to be able to modify `foo` from inside your `baz` repository, and eventually submit changes.

meson does that by its concept of "subprojects", it clones them in a predefined way and you're able to include them. It also merges subprojects that are declared multiple times (as is `foo` in my example).
It's very handy, but I'm not sure it's doable at the moment in xmake ?

The xrepo is a different use case, and git submodules would not be shared down the hierarchy of subprojects (?).

**Comment by waruqi** [comment]
> How would you set up a super-project that is composed of multiple sub-projects in different repositories ?
> 
> Contrived example: you have libraries `foo`, `bar` and the project `baz`.
> Each one of these is defined in xmake, `bar` depends on `foo`, and `baz` depends both on `foo` and `bar`.
> Each one of these projects are actively being worked on, ie. it's very convenient to be able to modify `foo` from inside your `baz` repository, and eventually submit changes.
> 
> meson does that by its concept of "subprojects", it clones them in a predefined way and you're able to include them. It also merges subprojects that are declared multiple times (as is `foo` in my example).
> It's very handy, but I'm not sure it's doable at the moment in xmake ?
> 
> The xrepo is a different use case, and git submodules would not be shared down the hierarchy of subprojects (?).

includes("subprojectdir") and add_deps("bar")

**Comment by Sahnvour** [comment]
I'd need the following directory structure, correct ?
```
baz/
├── bar/
│   └── foo/
└── foo/
```

Then, I can't share `foo` between `baz` and `bar`, especially if I want to modify it inplace.

**Comment by waruqi** [comment]
Why not share foo? you can only define `target("foo")` in any xmake.lua or sub xmake.lua and use add_deps("foo") to add it.

### only some xmake.lua

```lua
target("baz")
    add_deps("foo")
    -- ...

target("bar")
    add_deps("foo")
    -- ...

target("foo")
    -- ...
```

### Includes multiple subproject/xmake.lua

```
xmake.lua
    - bar/xmake.lua
    - foo/xmake.lua
```

root xmake.lua

```lua
target("baz")
    add_deps("foo")
    -- ...

includes("bar", "foo")
```

bar/xmake.lua

```lua
target("bar")
    add_deps("foo")
    -- ...
```

foo/xmake.lua

```lua
target("foo")
    -- ...
```

**Comment by Sahnvour** [comment]
> Why not share foo? you can only define target("foo") in any xmake.lua or sub xmake.lua and use add_deps("foo") to add it.

Each one of my projects/libs is usable on its own, so it would have its own subprojects in the tree.
In my example, both `baz` and `bar` would have `foo/`, and using xmake's `includes()` would work but the dependency would not be the same for `baz` and `bar` (if I understand correctly).

**Comment by waruqi** [comment]
No, includes does not change any dependencies, it just imports all target/option definitions in xmake.lua in the subproject directory.

You can use includes to contain target definitions in sub xmake.lua, or you can directly define all targets in the root xmake.lua.

Only the add_deps() interface can set the dependency of the target.
