### ISSUE TITLE
find_packages 是如何支持 pkg-config 的？

### ISSUE THREAD

**Issue by q962** [xmake-io/xmake#926]
xmake.lua 中使用 find_packages 返回 `{}`

```lua
target( "test_libusb_1" )
	set_kind("binary")
	add_files("src/*.c")
	on_load(function ( target )
		-- target:add( find_packages( "libusb-1.0" ) )
		local packages = find_packages("libusb-1.0")
		print( packages )
	end)
```

`xmake l find_packages` 命令能获得 include

**Comment by waruqi** [comment]
首先你得先确定 `pkg-config --libs --cflags libusd-1.0` 也能正常获取到。

如果能获取到，请贴下返回值。如果获取不到，那用 find_packages 也一样。

**Comment by q962** [comment]
当然，如果没有 那么 `xmake l find_packages libusb-1.0` 会工作吗

```
{
    version = "1.0.23",
    includedirs = {
      "D:/msys64/mingw64/include/libusb-1.0"
    }
  }
}

----------------

PS test_libusb_1> pkg-config --libs --cflags libusb-1.0
-ID:/msys64/mingw64/include/libusb-1.0 -LD:/msys64/mingw64/lib -lusb-1.0
```

**Comment by waruqi** [comment]
既然 xmake l find_packages 可以取到，那就执行下 xmake f -c 先清下之前的配置缓存，再看下试试

**Comment by q962** [comment]
带有 `find_packages` 函数，生成会导致错误
`error: cannot import module: package.manager.pkg.find_package, not found!`

那个片段就是全部代码了，是否还缺少关键代码？

**Comment by q962** [comment]
带有 `find_packages` 函数，生成会导致错误
`error: cannot import module: package.manager.pkg.find_package, not found!`

那个片段就是全部代码了，是否还缺少关键代码？

**Comment by waruqi** [comment]
?? 你能否描述清楚下 现在到底啥问题，如果是on_load 里面 find_packages 返回 {} 那就先按我刚说的试下 

如果还有其他错误 详细说明下 复现步骤和上下文背景

> 既然 xmake l find_packages 可以取到，那就执行下 xmake f -c 先清下之前的配置缓存，再看下试试

**Comment by q962** [comment]
🤔

find_package 返回`{}`，  `xmake f -c | del .xmake` 没用，报上述错误

**Comment by waruqi** [comment]
那就 xmake f -c -vD 给我看下详细错误信息

**Comment by q962** [comment]
v2.3.6 
error: invalid option: -vD

**Comment by waruqi** [comment]
不可能不支持这个选项 你截图下执行过程呢 

或者 xmake f -c -v - D

**Comment by q962** [comment]
这样可以，不支持 -vD 的写法

**Comment by q962** [comment]
```
checking for the architecture ... x86_64
checking for the mingw directory ... D:\msys64\mingw64
finding libusb-1.0 from xmake ..
finding libusb-1.0 from vcpkg ..
checking for the vcpkg directory ... no
finding libusb-1.0 from conan ..
checking for the libusb-1.0 ... no
{ }

configure
{
    arch = x86_64
    ccache = true
    theme = default
    host = windows
    mode = release
    ndk_stdcxx = true
    plat = mingw
    sdk = D:\msys64\mingw64       
    mingw = D:\msys64\mingw64     
    kind = static
    buildir = build
    cross = 
    clean = true
    bin = D:\msys64\mingw64\bin   
}
```
好吧，看样子没有使用 pkg-config

**Comment by waruqi** [comment]
> 这样可以，不支持 -vD 的写法

这就怪了，这个肯定应该支持的才对 回头我看下

> 好吧，看样子没有使用 pkg-config

在msys? 这个子系统环境 说不准还真没用 具体我得看下

另外我没看到你刚说的 cannot import module 错误么，再执行下 xmake -v -D 看看能 有没有错误信息

**Comment by q962** [comment]
xmake -v -D
```
{ }

configure
{
    clean = true
    ccache = true
    host = windows
    cc = D:\msys64\mingw64\bin\gcc
    cross = 
    mode = release
    ndk_stdcxx = true
    plat = mingw
    bin = D:\msys64\mingw64\bin   
    mingw = D:\msys64\mingw64     
    kind = static
    theme = default
    arch = x86_64
    buildir = build
    sdk = D:\msys64\mingw64
}
[  0%]: ccache compiling.release src\main.c
ccache D:\\msys64\\mingw64\\bin\\gcc -c -m64 -o build\\.objs\\test_libusb_1\\mingw\\x86_64\\release\\src\\main.c.obj src\\main.c
error: @programdir\actions\build\main.lua:75: @programdir\core\sandbox\modules\process.lua:148: @programdir\modules\private\action\build\object.lua:78: @programdir\modules\core\tools\gcc.lua:431: src\main.c:2:10: fatal error: libusb.h: No such file or directory
    2 | #include <libusb.h>
      |          ^~~~~~~~~~
compilation terminated.
stack traceback:
    [C]: in function 'error'
    [@programdir\modules\core\tools\gcc.lua:431]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
    [@programdir\modules\core\tools\gcc.lua:387]: in function '_compile1'
    [@programdir\modules\core\tools\gcc.lua:479]:
    [C]: in function 'compile'
    [@programdir\modules\private\action\build\object.lua:78]: in function '_do_build_file'
    [@programdir\modules\private\action\build\object.lua:117]: in function '_build_object'
    [@programdir\modules\private\action\build\object.lua:141]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\sandbox\modules\utils.lua:206: in function 'assert'
        @programdir\modules\private\action\build\object.lua:78: in function '_do_build_file'
        @programdir\modules\private\action\build\object.lua:117: in function '_build_object'
        @programdir\modules\private\action\build\object.lua:141: in function <@programdir\modules\private\action\build\object.lua:135>
```

无法复现 `cannot import module ` 刚才试了几次都报错，现在没了，奇了怪了

我想，使用 pkg-config 应该设计的和子系统无关吧？
使用 path 中的 pkg-config，或者指定，单纯使用它的结果不可以吗？

**Comment by waruqi** [comment]
目前是判断当前平台和宿主平台完全匹配才会走 pkgconfig 和从系统路径查找，避免交叉编译情况下去使用本机的pkgconfig

而你这宿主是windows ，平台是 mingw ，那么就是属于交叉编译了 所以当前没去使用 pkgconfig

看配置信息，我不确定你是否在用msys，下回提issue 记得根据issues的模板提示 提供详细的环境信息

https://github.com/xmake-io/xmake/blob/00b0c1607426b0d9c1fc654aad3e33e416d80010/xmake/modules/package/manager/find_package.lua#L56

**Comment by q962** [comment]
config.get("arch"):  x86_64
config.get("plat"):  mingw
os.host():  windows
os.arch():  x64

使用的 msys2，但没有使用 msys，而是其提供的 mingw64

**Comment by waruqi** [comment]
默认msys上 应该会自动切到 msys平台才对，你是手动指定了 xmake f -p mingw 切到的mingw?

可以执行 xmake l os.subhost 看下

**Comment by q962** [comment]
我明白了，我应该在 msys shell 中执行xmake，现在是在 vsc powershell 中执行的
对的，是手动指定

**Comment by waruqi** [comment]
> 我明白了，我应该在 msys shell 中执行xmake，现在是在 vsc powershell 中执行的
> 对的，是手动指定

你在cmd/ps下执行，手动切的 mingw 平台，那就属于交叉编译，xmake 只知道当前是在 windows下，不知道 msys2的存在，所以不会去用pkgconfig

你可以在 msys 下运行 xmake，也不用手动切到 mingw 平台，默认检测到 msys 平台后，就能够使用 pkgconfig 

不过还是要先更新下 xmake 到 dev版本，我稍微做了些修改。支持find_package 对子系统的匹配。

xmake update -s dev

**Comment by waruqi** [comment]
我dev上已经改成 对 os.subhost / os.subarch 的匹配探测了。 os.subhost 是获取的win 子系统环境 msys，而 os.host 永远是 windows

https://github.com/xmake-io/xmake/blob/256c36adcb212ab0325a8206bff557a6c896409c/xmake/modules/package/manager/find_package.lua#L56-L62

**Comment by q962** [comment]
```
PS test_libusb_1> xmake update -s dev
update version dev from official source ..
  => download https://gitee.com/tboox/xmake.git .. ok    
  => install script to C:\Program Files (x86)\xmake .. ok
PS test_libusb_1> xmake
error: @programdir\core\base\string.lua:39: attempt to call field '_lastof' (a nil value)
stack traceback:
        @programdir\core\base\string.lua:39: in function 'lastof'
        @programdir\core\base\path.lua:34: in function 'directory'
        @programdir\core\main.lua:102: in function '_find_root'
        @programdir\core\main.lua:171: in function '_init'
        @programdir\core\main.lua:222: in function <@programdir\core\main.lua:219>
```

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake/suites/1114894767/artifacts/15721369

你直接到 github action上下载完整最新dev安装包安装试试呢

**Comment by waruqi** [comment]
还是不行么

**Comment by q962** [comment]
重新安装可以使用 xmake 了

```
config.get("arch"):  x86_64
config.get("plat"):  mingw
os.host():  windows
os.arch():  x64
os.subhost():  msys
os.subarch():  x86_64
```
msys2 中有三种环境
- msys
- mingw64
- mingw32

我想应该对 msys 做特殊判断

**Comment by q962** [comment]
我想知道是如何判断 subhost 的

根据 `os.subhost()` 的代码，我进行搜索
```
$ grep -rn 'xmake._SUBHOST'
xmake/core/base/os.lua:848:    return xmake._SUBHOST
xmake/core/_xmake_main.lua:27:xmake._SUBHOST          = _SUBHOST

---

$ grep -rn '_SUBHOST'
core/src/xmake/engine.c:692:    lua_setglobal(engine->lua, "_SUBHOST");
xmake/core/base/os.lua:848:    return xmake._SUBHOST
xmake/core/_xmake_main.lua:27:xmake._SUBHOST          = _SUBHOST
```

还有 `config.get()`
```
$ grep -rnP 'config._CONFIGS'
xmake/core/project/config.lua:63:    if config._CONFIGS then
xmake/core/project/config.lua:64:        value = config._CONFIGS[name]
xmake/core/project/config.lua:97:    config._CONFIGS = config._CONFIGS or {}
xmake/core/project/config.lua:98:    config._CONFIGS[name] = value
xmake/core/project/config.lua:111:    assert(config._CONFIGS)
xmake/core/project/config.lua:115:    for name, value in pairs(config._CONFIGS) do
xmake/core/project/config.lua:245:    config._CONFIGS = nil
```

没有找到想要的

**Comment by waruqi** [comment]
> 重新安装可以使用 xmake 了
> 
> ```
> config.get("arch"):  x86_64
> config.get("plat"):  mingw
> os.host():  windows
> os.arch():  x64
> os.subhost():  msys
> os.subarch():  x86_64
> ```
> 
> msys2 中有三种环境
> 
> * msys
> * mingw64
> * mingw32
> 
> 我想应该对 msys2 做特殊判断

xmake不会做更细粒度的子系统判断，这样不好维护，只要是加载了msys2的shell环境，subhost就是统一的msys，mingw64这种 只是内部的默认工具链不同，对于xmake 不算子系统

**Comment by waruqi** [comment]
> 我想知道是如何判断 subhost 的
> 
> 根据 `os.subhost()` 的代码，我进行搜索
> 
> ```
> $ grep -rn 'xmake._SUBHOST'
> xmake/core/base/os.lua:848:    return xmake._SUBHOST
> xmake/core/_xmake_main.lua:27:xmake._SUBHOST          = _SUBHOST
> 
> ---
> 
> $ grep -rn '_SUBHOST'
> core/src/xmake/engine.c:692:    lua_setglobal(engine->lua, "_SUBHOST");
> xmake/core/base/os.lua:848:    return xmake._SUBHOST
> xmake/core/_xmake_main.lua:27:xmake._SUBHOST          = _SUBHOST
> ```
> 
> 还有 `config.get()`
> 
> ```
> $ grep -rnP 'config._CONFIGS'
> xmake/core/project/config.lua:63:    if config._CONFIGS then
> xmake/core/project/config.lua:64:        value = config._CONFIGS[name]
> xmake/core/project/config.lua:97:    config._CONFIGS = config._CONFIGS or {}
> xmake/core/project/config.lua:98:    config._CONFIGS[name] = value
> xmake/core/project/config.lua:111:    assert(config._CONFIGS)
> xmake/core/project/config.lua:115:    for name, value in pairs(config._CONFIGS) do
> xmake/core/project/config.lua:245:    config._CONFIGS = nil
> ```
> 
> 没有找到想要的

https://github.com/xmake-io/xmake/blob/00b0c1607426b0d9c1fc654aad3e33e416d80010/core/src/xmake/engine.c#L676

https://github.com/tboox/tbox/blob/330aa7bf9014b7557865d71b4a8f8da6d04104f2/src/tbox/prefix/compiler.h#L136

**Comment by q962** [comment]
好的，谢谢。

那现在该如何使用 pkg-config？

**Comment by waruqi** [comment]
你直接在 msys/mingw64 shell环境运行xmake 走默认配置，不要切mingw平台，应该就行 ，`xmake f -c` 清下配置，强制检测下

或者也可以通过 add_requires("pkg_config::libusb-1.0") 的方式显式走pkgconfig查找，不过这样就只能从pkgconfig栈了，其他包管理方式就不会去找了

**Comment by q962** [comment]
好的，可以用了
