### ISSUE TITLE
openssl 重复下载安装

### ISSUE THREAD

**Issue by wangzhankun** [xmake-io/xmake#928]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

当安装完xmake之后第一次编译程序时提醒下载OpenSSL，但是我已经安装过OpenSSL了。

### 期待的结果

希望xmake可以自动识别出已经安装的OpenSSL。

### 错误信息

如果可能，请尽量附加程序运行过程中的错误输出信息。

> 如果是xmake相关编译问题，请加上`-vD`参数运行，并给出详细编译输出信息。

### 相关环境

- xmake版本：自编译，最新版dev分支
- xmake运行平台：ubuntu server arm64
- xmake目标平台：ubuntu server arm64

#### 无法识别OpenSSL
![image](https://user-images.githubusercontent.com/35724924/91626250-f7a53680-e9df-11ea-9005-0f7a493143c8.png)
#### 提醒安装OpenSSL
![image](https://user-images.githubusercontent.com/35724924/91626254-fb38bd80-e9df-11ea-9ca6-aee6d547ee23.png)

**Comment by waruqi** [comment]
给我看下xmake.lua

**Comment by wangzhankun** [comment]
```lua
add_syslinks("pthread","gxiapi","cjson", "yaml-cpp")
add_requires("opencv")

includes("Main")
includes("Share")
includes("Armor")
includes("Buff")

target("CV")
    set_kind("binary")
    set_rules("mode.debug", "mode.release")
    --  set_optimize("fastest")
    add_packages("opencv")

set_languages("cxx11")

```

**Comment by waruqi** [comment]
find_packages 没检测到，你可以手动执行下 pkg-config --libs --cflags openssl 看看能获取到么。。

**Comment by wangzhankun** [comment]
也是找不到

**Comment by wangzhankun** [comment]
找到了，网上说是libssl-dev没有安装。安装一下就可以了。
