### ISSUE TITLE
共用描述域

### ISSUE THREAD

**Issue by compilelife** [xmake-io/xmake#929]
### 你在什么场景下需要该功能？

有若干个独立的工程，都有类似的lua配置如下：

```lua
add_repositories("evrepo /home/compilelife/work/pop/xmake-repo")

add_requires("gtest")

set_warnings("all")
if is_mode("debug") then
    set_symbols("debug")
    set_optimize("none")
elseif is_mode("release") then
    set_strip("all")
    set_optimize("faster")
end
```

这些工程每个都是独立的git工程，且在不同项目组维护

我的问题是：

1. 能否将这些配置抽离到独立的一个文件，然后在xmake.lua里”包含“？
2. 如果有现成方法可以，那么是否有办法”远程包含“，即我将公共配置放在http上，所有工程使用同一份、最新的公共配置。

### 描述可能的解决方案

因为文档里看到的都是模块的用法，也就是运行在脚本域，但是以上配置又无法在脚本域执行，所以走模块方案走不通；

又尝试了用lua的require引入文件，但是貌似在描述域无法使用这个特性

期待有解决方法😜

**Comment by compilelife** [comment]
关于”描述域的api无法在脚本域使用“，延伸一种场景：

像`add_requires`这样的配置会导致在`xmake f`时，就下载好了依赖库。但是，诸如gtest这样的依赖，实际只在test这个target里用到，而其他同事下载这个工程时，可能都不想跑test，但却要被强制下载和编译gtest

**Comment by compilelife** [comment]
另一个类似的问题，我在私有仓库里很多xmake.lua有类似的配置：

```lua
on_load(function(package)
			local cxxstl = import("core.project.config").get("ndk_cxxstl")
			if cxxstl:startswith("gnustl") then
				package:add("deps", "gnustl")
				local url = string.gsub(package:get("urls"), package:name(), "gnustl/"..package:name())
				print("url: "..url)
				package:set("urls", url)
			end
		end)
```

用于建立自定义的规则

希望这样的代码能抽象到一个独立的文件，每个xmake.lua文件来包含。如果用模块的做法，受repo的目录规则限制，无法放到repo里；如果放到/usr/local/share/xmake/modules/也许可以，但是这样会要求所有人都修改本地的xmake环境，难以保证；

所以，又回到一开始提的”远程模块“的思路……😂

**Comment by waruqi** [comment]
> 能否将这些配置抽离到独立的一个文件，然后在xmake.lua里”包含“？

自己用includes包含下指定路径 xmake.lua就行了，也有全局 ~/.xmakerc.lua可用

> 如果有现成方法可以，那么是否有办法”远程包含“，即我将公共配置放在http上，所有工程使用同一份、最新的公共配置。

这个不支持，你自己整个脚本搞下

> 像add_requires这样的配置会导致在xmake f时，就下载好了依赖库。但是，诸如gtest这样的依赖，实际只在test这个target里用到，而其他同事下载这个工程时，可能都不想跑test，但却要被强制下载和编译gtest

可自定义一个option配置选项 比如 xmake f --gtest=y，默认禁用状态，通过if has_config("gtest") then 判断是否要add_requires，默认禁用不开开启   只有自己需要的时候手动配置--gtest=y开启

> 希望这样的代码能抽象到一个独立的文件，每个xmake.lua文件来包含。如果用模块的做法，受repo的目录规则限制，无法放到repo里；如果放到/usr/local/share/xmake/modules/也许可以，但是这样会要求所有人都修改本地的xmake环境，难以保证；

脚本域可以用 import 导入指定路径的模块，绝对路径 相对路径的都可以

模块根路径可以通过 add_moduledirs配置，也可以直接 import("", {rootdir = xxx}) 来配置

**Comment by compilelife** [comment]
好的，感谢！我先按你的思路调调看

**Comment by compilelife** [comment]
> 能否将这些配置抽离到独立的一个文件，然后在xmake.lua里”包含“？

这个我试了下includes来包含，但是没生效，可能是我没用对？

目录结构：

```
.
├── main.cpp
├── xmake.lua
└── xscript
    └── xmake.lua
```

xmake.lua 

```lua
includes("xscript")

target("main")
    set_kind("binary")
    add_files("main.cpp")
```

xscript/xmake.lua

```lua
set_warnings("all")
if is_mode("debug") then
    set_symbols("debug")
    set_optimize("none")
elseif is_mode("release") then
    set_strip("all")
    set_optimize("faster")
end
```

我试图达到的效果是，根目录下的xmake.lua能把xscript/xmake.lua的内容”整合进来“，但是实际看，并没有生效：

```
# xmake f -m debug -c
checking for the architecture ... x86_64

# xmake -v
configure
{
    arch = x86_64
    ccache = true
    proxy_pac = pac.lua
    clean = true
    ndk_stdcxx = true
    plat = linux
    mode = debug
    kind = static
    theme = default
    buildir = build
    host = linux
}
checking for the c++ compiler (cxx) ... gcc
checking for the ccache ... /usr/bin/ccache
[ 50%]: ccache compiling.debug main.cpp
/usr/bin/ccache /usr/bin/gcc -c -I/usr/local/include -I/usr/include -m64 -o build/.objs/main/linux/x86_64/debug/./main.cpp.o main.cpp
checking for the /usr/bin/gcc ... ok
checking for the flags (-MMD -MF) ... ok
checking for the flags (-fcolor-diagnostics) ... no
checking for the flags (-fdiagnostics-color=always) ... ok
checking for the g++ ... /usr/bin/g++
checking for the linker (ld) ... g++
[ 75%]: linking.debug main
/usr/bin/g++ -o build/linux/x86_64/debug/main build/.objs/main/linux/x86_64/debug/./main.cpp.o -L/usr/local/lib -L/usr/lib -m64
[100%]: build ok!
```

看这行：`/usr/bin/ccache /usr/bin/gcc -c -I/usr/local/include -I/usr/include -m64 -o build/.objs/main/linux/x86_64/debug/./main.cpp.o main.cpp`

并没有`-g -O0`，所以没生效。

**Comment by waruqi** [comment]
所有全局设置都是按includes tree状结构继承，scripts下的属于子模块配置，里面的全局设置只对scripts当前以及下一级includes里面的targets生效，其他同级和父级里面的target是不会生效的

你可以在 scripts/xmake.lua 里面定义rule("common") 规则，里面设置上你的所有通用设置，然后在根xmake.lua中通过 add_rules("common")对你的所有targets生效

xmake内置的mode.releases等规则都是这么做的

请参考 https://github.com/xmake-io/xmake/blob/master/xmake/rules/mode/xmake.lua

或者也可以通过在 scripts/xmake.lua里面 用一个function wrap下，

```
function set_common()
    set_warnings("all")
if is_mode("debug") then
    set_symbols("debug")
    set_optimize("none")
elseif is_mode("release") then
    set_strip("all")
    set_optimize("faster")
end
end
```

然后你根xmake.lua里面includes后，后面调用下 set_common() 也是可以的

**Comment by compilelife** [comment]
@waruqi 按照你通过的思路，验证问题都可以解决。多谢
