### ISSUE TITLE
子工程对于其它构建系统的配置

### ISSUE THREAD

**Issue by wangling12** [xmake-io/xmake#932]
### 你在什么场景下需要该功能？

项目引用了一些第三方库,这些库可能用了autotools,make之类的构建系统.当前似乎对于第三方构建工具只有终端命令支持,在xmake.lua中没有api(也可能是我没找到)

### 描述可能的解决方案

可能需要一些配置项来配置子工程的构建系统,以及记录子工程的输出文件,以便与使用第三方构建系统的子工程偶合度更高.

**Comment by waruqi** [comment]
通过add_requires + 内置私有包的方式 集成其他第三方构建系统维护的库。相关文档：https://xmake.io/#/zh-cn/package/remote_package?id=%e4%bd%bf%e7%94%a8%e8%87%aa%e5%bb%ba%e7%a7%81%e6%9c%89%e5%8c%85%e4%bb%93%e5%ba%93

包定义的配置 example : https://github.com/xmake-io/xmake-repo/blob/master/packages/p/pcre2/xmake.lua

xmake.lua 中内置私有仓库+第三方包定义的 example https://github.com/tboox/benchbox

**Comment by wangling12** [comment]
看起来很强大,但是很多时候类似于"屎山"子项目工程可能不值得这么耗费精力.set_trybuild和add_tryconfigs再加上一个类似set_outputfiles估计就能覆盖90%以上的需求.

**Comment by waruqi** [comment]
你可以看下 https://github.com/tboox/benchbox 里面的配置，集成方式也就几行，set_trybuild和add_tryconfigs 这种反而更折腾，而且不可靠，如果连 package() + add_requires 就这么几行的配置精力都没有，那也没必要用其他的方式了。。

**Comment by waruqi** [comment]
或者自己定义on_build整个覆盖重写build，里面自己调用 os.exec 执行第三方构建系统命令去编译就行了，输出到哪里自己拼对应的命令参数 也就几行代码的事

**Comment by wangling12** [comment]
嗯嗯,多谢回复,我再仔细看看你给的例子
