### ISSUE TITLE
在更新xmake 2.3.3时遇到错误

### ISSUE THREAD

**Issue by rel1ve** [xmake-io/xmake#935]
最近在更新xmake 2.3.3时遇到如下错误（从2.3.3 - 2.3.6版本更新的错误相同）：

update version v2.3.3 from official source ..
  => install to ~/.local/bin .. ok                                                                                                                   xmake v2.3.3+202009011544, A cross-platform build utility based on Lua
Copyright (C) 2015-2020 Ruki Wang, tboox.org, xmake.io
                         _        
    __  ___ __  __  __ _| | ______ 
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____| 
                         by ruki, tboox.org
    
    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor
    
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of xmake is available!                                       ║
  ║                                                                            ║
  ║ To update to the latest version v2.3.6, run "xmake update".                ║
  ╚════════════════════════════════════════════════════════════════════════════╝

/home/lanxum/.local/bin/xmake: 行 4: 未预期的符号 `(' 附近有语法错误
/home/lanxum/.local/bin/xmake: 行 4: `pp@p@@@\.\. �=�=r�=r��H �=�=r�=r@��@�@DD�=�=r�=r P�td(�(�O(�OLTLTQ�tdR�td�=�=r�=r``/lib64/ld-linux-x86-64.so.2GNU GNU<H�QV�ܒI�r��@j��)���0�@ A H!  4�HX
sp�                         J<>?@ACDEGHILOQRSXZ]_�V�!��
   ϣҿ-2@��ݣk����°�
/├r@�|�qX��|��    9�ĉ�)����1��
              I���V�|��fUa'�|BE����
                                   4BtuYO���.�|W�|�~�|���H��
                                                            ��
                                                              �+��┴�7+J  '

**Comment by waruqi** [comment]
这个是低版本的 xmake update 里面有点bug，高版本已经修了，不用管它，你可以执行下 xmake --version 应该是更新好了的，如果不行，就完整重装下就好。
