### ISSUE TITLE
Fortran module files path

### ISSUE THREAD

**Issue by interkosmos** [xmake-io/xmake#942]
### Describe the problem details
In Fortran build targets, module files (`*.mod`) are stored in `build/.objs/<name>/<platform>/<architecture>/<release|debug>/.modules/` by default. Is there any way to change the directory with something like `target:set_objectdir` for Fortran mod files? As they are required for linking, setting the path to something like `build/mod/` on occasion may be preferable.

**Comment by waruqi** [comment]
Why do you need to directly link the module? Why not use static libraries to link them?

**Comment by interkosmos** [comment]
in Fortran, those module files are required to link static libraries.

**Comment by waruqi** [comment]
So when xmake generates static libraries, it will compile .f90 files to generate module files and link them. If you want to use module files of other libraries, you can also link them into a static library, and then we will link this static library

**Comment by waruqi** [comment]
So when xmake generates static libraries, it will compile .f90 files to generate module files and link them. If you want to use module files of other libraries, you can also link them into a static library, and then we will link this static library

**Comment by interkosmos** [comment]
Module files in Fortran are similiar to C headers. In order to link an arbitrary Fortran-based static library in Fortran, all `*.mod` files of the library have to be present as well. As the module files are always required along the library it would therefore make sense to be able to change the output directory.

**Comment by waruqi** [comment]
I added `set_values("fortran.moduledir", "/xx")` to set it. you can update dev and try it again.

```lua
target("test")
    set_kind("binary")
    add_files("src/*.c")
    set_values("fortran.moduledir", "$(buildir)/mod")
```

**Comment by interkosmos** [comment]
I tried the current master branch, but module files are still stored in the default path:
```
target("example")
    set_kind("static")
    add_files("src/*.f90")
    set_targetdir("build")
    set_values("fortran.moduledir", "$(buildir)")
```
