### ISSUE TITLE
--debugger设置批处理

### ISSUE THREAD

**Issue by bstaint** [xmake-io/xmake#949]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

从2.3.2开始，`xmake f -a x86 -m debug --debugger="D:\Portable\lnk\windbg.bat"`，debugger就不能设置批处理了，xmake run -d不会启动，2.3.1是可以的。

又仔细试了下是因为批处理中的`start`的问题，去掉就可以了，2.3.1是可以直接用。
```
@echo off

set DBG_EXE=D:\Develop\WinDbg\x86\windbg.exe

start %DBG_EXE%
```

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 错误信息

如果可能，请尽量附加程序运行过程中的错误输出信息。

> 如果是xmake相关编译问题，请加上`-vD`参数运行，并给出详细编译输出信息。

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：
- xmake运行平台：
- xmake目标平台：

### 其他信息

请提供其他附加信息帮助我们诊断问题(比如截图，xmake.lua或者可复现的demo)，以及你遇到的问题的一些背景信息。

**Comment by waruqi** [comment]
？这块应该没动过，就是调用os.exec执行的

**Comment by bstaint** [comment]
我知道，但是我试了几个版本，从2.3.2往后调用批处理里start就没任何效果了。

**Comment by waruqi** [comment]
之前是改动过一次 os.exec 确保所有进程在 xmake 退出后自动退出，通常为了编译完成后，不会存在残留进程。

调试运行这块我刚改了下，detach 了进程，你更新到 dev试试

**Comment by bstaint** [comment]
dev分支没看到有相关commit.

**Comment by waruqi** [comment]
刚提交失败了 忘记同步了 一会我再提交下

**Comment by waruqi** [comment]
好了

**Comment by bstaint** [comment]
应该跟os.exec实现有关，我测试：

1.lua
```
os.exec('1.bat')
```

1.bat:
```
start notepad
```

`xmake lua 1.lua`

2.3.1可以正常打开记事本。

**Comment by waruqi** [comment]
刚的提交也不行？

**Comment by bstaint** [comment]
不行。

**Comment by waruqi** [comment]
> ```
> os.exec('1.bat')
> ```

你说的是--debugger，那就是 `xmake run -d ` 加载调试时候行不行？我仅仅只是改了这个，你单独测试这个当然没效果。。

os.exec("1.bat") 原本就是执行完后，xmake 只要已退出 就会自动退出所有子进程的，这是正常行为。。

如果不想退出，需要 `os.execv("1.bat", {}, {detach = true})` 去解除对子进程的关联，notepad才会正常起来，而这个 我刚的patch 里面 已经对 `xmake run -d` 加载调试器的 已经设置上了，还是不行？

**Comment by waruqi** [comment]
我之前忘记透传detach 给 os.execv， 更新了下，你再试试 `xmake run -d`

**Comment by bstaint** [comment]
现在可以了，感谢。
