### ISSUE TITLE
是否支持动态库静态库混合链接

### ISSUE THREAD

**Issue by Biobots** [xmake-io/xmake#957]
### 描述问题

mingw下编译可执行程序后运行报找不到动态库

### 期待的结果

可指定链接库的类型

### 错误信息

```
[ 75%]: linking.release gl.exe
C:\mingw64\bin\x86_64-w64-mingw32-g++ -o build\mingw\x86_64\release\gl.exe build\.objs\gl\mingw\x86_64\release\test.cpp.obj -s -LC:\Users\xxx\AppData\Local\.xmake\packages\g\glew\2.1.0\89c21cf8a58c45879bbb108d97a0bab7\lib -LC:\Users\xxx\AppData\Local\.xmake\packages\g\glfw\3.3.2\89c21cf8a58c45879bbb108d97a0bab7\lib -lglew32 -lglfw3 -lglfw3dll -lopengl32 -lgdi32 -luser32 -lshell32 -m64
[100%]: build ok!
```

之后运行时找不到glew动态库

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：dev分支
- xmake运行平台：mingw
- xmake目标平台：windows

### 其他信息

将上述命令修改为直接指定静态库：

```
C:\mingw64\bin\x86_64-w64-mingw32-g++ -o build\mingw\x86_64\release\gl.exe build\.objs\gl\mingw\x86_64\release\test.cpp.obj -s \Users\xxx\AppData\Local\.xmake\packages\g\glew\2.1.0\89c21cf8a58c45879bbb108d97a0bab7\lib\libglew32.a \Users\xxx\AppData\Local\.xmake\packages\g\glfw\3.3.2\89c21cf8a58c45879bbb108d97a0bab7\lib\libglfw3.a -lopengl32 -lgdi32 -luser32 -lshell32 -m64
```

或使用`-static`参数：

```
-o build\mingw\x86_64\release\gl.exe build\.objs\gl\mingw\x86_64\release\test.cpp.obj -s -LC:\Users\xxx\AppData\Local\.xmake\packages\g\glew\2.1.0\89c21cf8a58c45879bbb108d97a0bab7\lib -LC:\Users\xxx\AppData\Local\.xmake\packages\g\glfw\3.3.2\89c21cf8a58c45879bbb108d97a0bab7\lib -static -lglew32 -lglfw3 -lglfw3dll -lopengl32 -lgdi32 -luser32 -lshell32 -m64
```

均可正常运行

**Comment by Biobots** [comment]
xmake.lua:

```lua
add_requires("glew", "glfw")
add_rules("mode.debug", "mode.release")


target("gl")
    set_kind("binary")
    add_packages("glew", "glfw")
    add_files("*.cpp")
    if is_plat("windows") then
        add_cxflags("-MDd")
        add_ldflags("-nodefaultlib:msvcrt.lib")
    end
```

**Comment by waruqi** [comment]
这需要改包定义，加上 .dll 所在 lib 目录到 path 才行。xmake run 才会自动加上对应的搜索路径，然后重装下包，你可以自己先试试

https://github.com/xmake-io/xmake-repo/blob/master/packages/g/glew/xmake.lua


```lua
    on_load("mingw", "windows", function (package)
        if package:config("shared") then
            package:addenv("PATH", "lib")
        end
    end)
```

**Comment by Biobots** [comment]
> 这需要改包定义，加上 .dll 所在 lib 目录到 path 才行。xmake run 才会自动加上对应的搜索路径，然后重装下包，你可以自己先试试
> 

我发现glew中的dll是被放到bin里面了……

还有个问题是，如果我想把这里面的glew和glfw作为静态库链接，应该怎么配置？

**Comment by waruqi** [comment]
> 我发现glew中的dll是被放到bin里面了……

那就针对mingw 添加bin到path

> 还有个问题是，如果我想把这里面的glew和glfw作为静态库链接，应该怎么配置？

按理，默认安装的包，就是要静态库的，只有配置了下面的，才会安装动态库。

add_requires("xxx", {configs = {shared = true}})

包定义里面，通过 `if package:config("shared") then` 控制下安装静态库、动态库

**Comment by Biobots** [comment]
> 按理，默认安装的包，就是要静态库的，只有配置了下面的，才会安装动态库。

那为什么运行后会提示找不到`glew32.dll`呢？按我的理解，上面那个g++的命令中，在没有指定`-static`的情形下，`-l`应该是优先链接动态库的，但是`lib`目录下根本没有动态库，那这是应该去找静态库链接，但是这里却出现了链接动态库才会发生的错误。

以及这个默认使用静态库是如何实现的呢？

**Comment by waruqi** [comment]
> 那为什么运行后会提示找不到glew32.dll呢？

msvc/mingw 又不支持rpath，dll的加载是windows的搜索路径规则决定的，默认从当前目录下找，没有就从 PATH 变量中找，或者从系统 windows 目录找。。

所以 xmake run 的时候，只有附带上对应 dll 所在的目录到 PATH 变量，才能运行时候加载成功，这个编译链接没有任何关系，只有 elf/macho 才可以在链接时候，通过rpath设置加载路径

所以，我刚跟你说，这个得改 package 定义，on_load的时候配置上PATH才行。。

```lua
    on_load("mingw", "windows", function (package)
        if package:config("shared") then
            package:addenv("PATH", package:is_plat("mingw") and "bin" or "lib")
        end
    end)
```

**Comment by waruqi** [comment]
> 按我的理解，上面那个g++的命令中，在没有指定-static的情形下，-l应该是优先链接动态库的，但是lib目录下根本没有动态库，那这是应该去找静态库链接，但是这里却出现了链接动态库才会发生的错误。

这个就要问mingw/gcc了。。

> 以及这个默认使用静态库是如何实现的呢？

xmake-repo仓库的package() 定义，默认都是只装static，只有通过 `add_requires("xxx", {configs = {shared = true}})` 才回去装dll，这个我刚说过了。。不要同时安装 static/shared 

什么都不配置的时候，`package:config("shared")` 默认就是false ，也就是默认安装静态库。安装阶段你要透传cmake参数给它。

```lua
    on_install("macosx", "linux", function (package)
        local configs = {}
        table.insert(configs, "-DBUILD_SHARED_LIBS=" .. (package:config("shared") and "ON" or "OFF"))
        table.insert(configs, "-DCMAKE_BUILD_TYPE=" .. (package:debug() and "Debug" or "Release"))
        import("package.tools.cmake").install(package, configs)
    end)
```

**Comment by Biobots** [comment]
知道原因了，目录下没有.dll但是有.dll.a，链接到了这个库，运行时又没找到dll，所以报错了

还是得设置`BUILD_SHARED_LIBS`才行
