### ISSUE TITLE
English documentation 

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#96]
Translating ..., help me please! [Edit this page](http://xmake.io/#/manual?id=target_end)

- [x] Specification
- [ ] Documentation
  - [x] Conditions
  - [x] Global Interfaces
  - [ ] Project Target (in progress ...)
  - [ ] Configuration Option
  - [ ] Plugin and Task
  - [ ] Extension Platforms
  - [ ] Extension Languages
  - [ ] Project Templates
  - [ ] Builtin Variables
  - [ ] Builtin Modules
  - [ ] Extension Modules

**Comment by uael** [comment]
:+1:
