### ISSUE TITLE
win32: copy package DLLs to install dir?

### ISSUE THREAD

**Issue by paul-reilly** [xmake-io/xmake#961]
At the moment on Windows, when we run `xmake install -o install/myapp` for a build file with a binary and a shared target, the default output is something like:
```
install
│
├─── myapp
│
├─────── bin
│            myapp.exe
│
├─────── include
│            myshlib.h
│
├─────── lib
│            myshlib.dll
│            myshlib.lib
└
```
DLLs from packages are not copied and on Windows they won't have been installed to system/usr dirs for usage. In that structure `myapp.exe` won't be able to locate `myshlib.dll` either.

What's the best current way to copy DLLs from packages to our install location?

Ideally I think it would be good to be able to do something more like this as some kind of (overridable) default install for win32:

**Layout 1: Flat structure**
```
install
│
├─── myapp
│        myapp.exe
│        myshlib.dll
│        package1shlib.dll
│        package2shlib.dll
└
```
**Layout 2: DLL subdirectory with manifest**
```
install
│
├─── myplugin
│        myplugin.dll
│        myplugin.dll.manifest
│
├─────── morelibs
│            myshlib.dll
│            package1shlib.dll
│            package2shlib.dll
└
```

**Comment by waruqi** [comment]
I can improve it and we only need to copy the dll to the bin directory for installing executable program. 

```
install
│
├─── myapp
│
├─────── bin
│            myapp.exe
│            myshlib.dll. <--
│
├─────── include
│            myshlib.h
│
├─────── lib
│            myshlib.dll
│            myshlib.lib
└
```

If you want to further customize the installation, you can define on_install to rewrite the internal installation process.

```lua
target("test")
    set_kind("binary")
    add_files("src/*.c")
    on_install(function (target)
        os.cp(target:targetfile(), path.join(target:installdir(), "xxx"))
    end)
```

**Comment by waruqi** [comment]
I have improved it in dev branch. `xmake update -s dev`

```
install
│
├─── myapp
│
├─────── bin
│            myapp.exe
│            myshlib.dll. <--
```

**Comment by paul-reilly** [comment]
Thanks, that's a good initial improvement!

**Comment by paul-reilly** [comment]
This works, I don't know if direct access of the private `_`, `__` fields is allowed or whether this is the ideal way:
```
-- get any dlls from required packages
function _install_package_dlls(target, destdir)
    for pkg, pkg_details in pairs(target:pkgs()) do
        local info = pkg_details._INFO
        if info.__enabled and info.links then

            -- info.links is a string for one and a table for multiple
            local links = type(info.links) == "string" and { info.links } or {}
            for _, link in pairs(links) do
                local filename = link .. ".dll"

                for _, dir in pairs(info.linkdirs) do
                    local filepath = path.join(dir, filename)
                    if os.isfile(filepath) then

                        -- trace
                        print("copying package dep %s to install dir", filename)
                        if os.isfile(path.join(destdir, filename)) then
                            cprint("${red}Warning: DLL with the name '%s' already exists in install dir.", filename)
                            cprint("${red}         Aborting copy of DLL from package: '%s'.", info.name or "NO NAME")
                        else
                            os.vcp(filepath, destdir)
                        end
                    end
                end
            end
        end
    end
end
```

**Comment by waruqi** [comment]
Please do not directly access the private fields, they may be changed at any time.

>         local info = pkg_details._INFO
        if info.__enabled and info.links then

Please use `pkg:get("links")`

**Comment by paul-reilly** [comment]
Okay, thanks... will do!

**Comment by paul-reilly** [comment]
Just leaving this here for now. For DLLs that do not have the same name as the `.lib` file I had to do some probing of the `.lib` for the DLL name, which is a lot faster than using `dumpbin`. I'm using the simple and consistent goto pattern to make up for the lack of `continue` in Lua.... it's fine people, really it's fine! :)
```

function _get_dll_filename_from_lib(libpath)
    local file = io.open(libpath, "rb")
    local dump = file:read("*a") -- TODO: see why buffer read (eg 4096) doesn't work
    local _, _, dll_name = dump:find("__IMPORT_DESCRIPTOR_([%a%d_%-%.]+)\0", 1, false)
    file:close()
    if dll_name then
        dll_name = dll_name .. ".dll"
    end
    return dll_name
end

-- get any dlls from required packages
function _copy_package_dlls(target, destdir)
    for pkg_name, pkg in pairs(target:pkgs()) do

        -- TODO: a package with a static config could potentially have shared deps
        local static = not pkg:extrainfo() or (pkg:extrainfo() and pkg:extrainfo().configs and not pkg:extrainfo().configs.shared)
        if static then
            goto continue_pkgs_loop
        end
        local links = pkg:get("links")

        if not links then goto continue_pkgs_loop end

        -- links is a string for one and a table for multiple
        local links = type(links) == "string" and { links } or links
        for _, link in pairs(links) do

            -- first search for dlls with same name as lib
            local dllname = (link or "").. ".dll"

            -- trace
            print("finding link: %s from package %s", link, pkg_name)
            local dllpath = find_file(dllname, pkg:get("linkdirs"))
            if dllpath then
                if os.isfile(path.join(destdir, dllname)) then
                    cprint("${yellow}warning: DLL with the name '%s' already exists in install dir.", dllname)
                    cprint("${yellow}         overwriting with DLL from package: '%s'.", pkg_name or "NO NAME")
                end
                os.vcp(dllpath, destdir)
                
                goto continue_links_loop
            end

            -- dll not the same name as lib, find name from lib and search again
            local libname = (link or "") .. ".lib"
            local libpath = find_file(libname, pkg:get("linkdirs"))
            if libpath then
                local dllname = _get_dll_filename_from_lib(libpath)
                if dllname then
                    local dllpath = find_file(dllname, pkg:get("linkdirs"))
                    if dllpath then
                        if os.isfile(path.join(destdir, dllname)) then
                            cprint("${yellow}warning: DLL with the name '%s' already exists in install dir.", dllname)
                            cprint("${yellow}         overwriting with DLL from package: '%s'.", pkg_name or "NO NAME")
                        end
                        os.vcp(dllpath, destdir)
                        
                        goto continue_links_loop
                    end
                end
            end

            cprint("${red}Could not find DLL for %s.lib in package: %s", link, pkg_name)

            ::continue_links_loop::
        end

        ::continue_pkgs_loop::
    end
end
```

**Comment by paul-reilly** [comment]
`copy_package_dll_paths` would probably be a good user function to have, for custom install functions.

Name clashes are something to think about. I'm thinking of LuaSocket with the:

```
├── socket
│        core.dll
├── mime
│        core.dll
```
Install requirement for Lua finding them via the standard `require("socket.core")`. At the moment there is a clash unless they are individually named for later renaming.

It's probably better if the user is not required to know the details of package artifacts for relocating/renaming after install. So having some kind of `relativeinstalldir` so that in this case we could `target.set_relativeinstalldir("socket")` in the package could maybe solve this issue.

Also a `target.set_installlayout({ bin = "", include = nil, lib = "shared" })` function would probably complete this FR.

**Comment by waruqi** [comment]
> Also a target.set_installdirstructure({ bin = "", include = nil, lib = "shared" }) function would probably complete this FR. We would not need to copy DLLs into the bin dir 96fe212 either since the required layout would be automatic.

These are user-defined installation requirements, and other users may have more complicated installation structures.

This interface does not meet the needs of all users, xmake only needs to provide a basic default installation structure.

If you need a more customized installation, users can implement on_install() to customize them, or they can define a rule("myinstall") to encapsulate their own installation rules.

**Comment by paul-reilly** [comment]
In the docs you wrote: "according to the 28th law, 80% of the cases, we only need to write".

cmake + vcpkg copies DLLs on build so this functionality is expected. Do you not want this functionality - not specifically what I wrote - in xmake?

**Comment by waruqi** [comment]
I will improve the built-in installation rule to support copy package dlls.

**Comment by waruqi** [comment]
I have improved the builtin action `xmake install` to support for installing dlls from packages.

https://github.com/xmake-io/xmake/blob/dev/xmake/actions/install/install/windows.lua

**Comment by paul-reilly** [comment]
Okay, that's saved Windows users who use shared libs a great deal of hassle already! 

Although not having a public function to get the DLL paths means that Windows users using a custom `on_install` function don't have access to the logic that this file uses to get them, both for package DLLs and [dep DLLs](https://github.com/xmake-io/xmake/blob/dev/xmake/actions/install/install/windows.lua#L111-L119).

I would be good for install scripts to have access to this information.

**Comment by waruqi** [comment]
I will provide a more general interface to get all library file paths of each package more conveniently.

**Comment by waruqi** [comment]
I added `pkg:get("libpathes")` to get all library files path. You can simply traverse this list to install the dll library files you need

https://github.com/xmake-io/xmake/blob/e3659747443021e53a71992710b28c12fb76adc4/xmake/actions/install/install/windows.lua#L42-L51

**Comment by paul-reilly** [comment]
That's good, that's the information available, thanks!

Btw, I notice that the misspelt word "pathes" is used here and elsewhere in the codebase, maybe this needs aliased for future correctness and to preserve backwards compatibility?

**Comment by waruqi** [comment]
is paths? Sorry, my English is not good, if pathes is wrong, I will rename libpathes to libpaths

and I will try to make some changes in other places and preserve backwards compatibility.

**Comment by paul-reilly** [comment]
Yes, it is "paths". Your English is good btw, infinitely better than my 普通話。!

**Comment by waruqi** [comment]
This is all thanks to Google Translate. 😄 

I have renamed libpathes to libfiles, you can try it again.

About pathes, because there are more related codes, when I have time later, I will try to modify it.

**Comment by paul-reilly** [comment]
不怕慢，就怕站 :) (I can only count to 10 in Mandarin so I definitely used the internet for that <--- !!!)

Thanks, I will test more later!

**Comment by waruqi** [comment]
I have rename all `pathes` to paths and ensure backward compatibility. 

```
find_tool(, {paths = {}})
find_program(, {paths = {}})
```

**Comment by paul-reilly** [comment]
Good stuff.

So how do we get this in `on_install`?
```
on_install(function(target)
    cprint("pkg = %s", tostring(target:pkg())) -- == nil
end)
```

I think it would be useful to be able to use the work the standard install does first. 
```
on_install(function(target)
    target:standard_install()
    -- change a few things
end)

after_install(function(target)
    -- do more things
end)
```

**Comment by waruqi** [comment]
> So how do we get this in on_install?

```
print("%s", target:pkg("luajit"):name())
```

Or use `target:pkgs()` or `target:orderpkgs()`

https://github.com/xmake-io/xmake/blob/b1c358e57b442610f481cf8c834ae46c90b99645/xmake/actions/install/install/windows.lua#L56-L62

> I think it would be useful to be able to use the work the standard install does first.

Later, I will consider encapsulating them in the built-in extension modules and provide them to users through the import interface.

But it will take some time, I have other things to deal with first.

You can refer to the above method first, and then traverse all packages in on_install, which is not very troublesome.

**Comment by paul-reilly** [comment]
Thanks, look forward to it!

**Comment by waruqi** [comment]
I have exported action/install and uninstall modules on dev, You can try it.

Common mode:

```lua
on_install(function (target)
    import("target.action.install")
    install(target, {bindir = "bin", libdir = "lib"})
end)
```

Only for windows

```lua
on_install(function (target)
    import("target.action.install.windows")
    windows.install_shared(target, {bindir = "bin", libdir = "lib"}) -- installdir/bin/*.dll  lib/*.lib
    windows.install_shared(target, {bindir = "", libdir = ""}) -- installdir/*.dll, *.lib
end)
```

```lua
on_install(function (target)
    import("target.action.install.windows")
    windows.install_static(target, {libdir = "lib"})
end)
```


```lua
on_install(function (target)
    import("target.action.install.windows")
    windows.install_binary(target, {bindir = "bin"})
end)
```

**Comment by paul-reilly** [comment]
Thanks, I'll give those a good test.

**Comment by paul-reilly** [comment]
I notice that the `libuv` package installs the dll in the `lib` directory and the new logic does not check this directory:

https://github.com/xmake-io/xmake/blob/84201fe219187b44b1b32eee369a08b7ccdbf38b/xmake/modules/package/manager/xmake/find_package.lua#L107-L109

... so `uv.dll` is never copied.

**Comment by waruqi** [comment]
you need reinstall libuv.

**Comment by waruqi** [comment]
I have improved it, you can update dev and try it again.
