### ISSUE TITLE
No way to express file dependencies?

### ISSUE THREAD

**Issue by tim-lebedkov** [xmake-io/xmake#963]
### Is your feature request related to a problem? Please describe.
I want to replace some texts in "app.rc.in" and generate "app.rc" and then compile it with "winres" and link. How can I do this?

### Describe the solution you'd like
Dependencies between files as in "make".

### Describe alternatives you've considered
I do not see any alternatives

### Additional context
-

**Comment by waruqi** [comment]
```lua
target("testrc")
    set_kind("binary")
    add_files("src/*.cpp")
    add_files("$(buildir)/app.rc")
    add_configfiles("src/app.rc.in")
```

You can see https://xmake.io/#/manual/project_target?id=targetadd_configfiles

**Comment by tim-lebedkov** [comment]
This works. Thank you.
