### ISSUE TITLE
io.readfile throws

### ISSUE THREAD

**Issue by tim-lebedkov** [xmake-io/xmake#964]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
Cannot read the contents of a text file. Here is the first line of my "xmake.lua":

`local appveyor 	= io.readfile("../appveyor.yml")
`

### Expected behavior
Text from appveyor.yml

### Error output
```
C:\Users\IEUser\Documents\npackd-cpp\npackdg>xmake
error: @programdir\core\project\project.lua:994: .\xmake.lua:1: attempt to index global 'io' (a nil value)
stack traceback:
    [.\xmake.lua:1]: in main chunk

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:792: in function 'raise'
        @programdir\core\project\project.lua:994: in function 'tasks'
        @programdir\core\project\project.lua:983: in function 'task'
        @programdir\core\main.lua:275: in function <@programdir\core\main.lua:219>

```
> If it is a xmake related compilation problem, please add the `-v -D` parameter and give the detailed compilation output information.

### Related Environment

Please provide compiling and running environment information:

- xmake version:2.3.7+202009141205
- os:Windows 10
- target platform:MinGW-64 64 bit

**Comment by waruqi** [comment]
Please use io module in script scope.

You can only use some basic configuration interfaces in the description scope. If you want to use more module interfaces to write complex scripts, you need to write them in the script scope.

https://xmake.io/#/guide/syntax_description?id=script-scope

**Comment by tim-lebedkov** [comment]
This helps, but now set_version cannot be used from on_load. I want to read the version number from appveyor.yml:

target("npackdg")
	on_load(function (target)
                local appveyor = io.readfile("../appveyor.yml") 
		local version = string.trim(appveyor:split("\n")[1]:split(":")[2]:split(".{")[1])
		set_version(version)
        end)

**Comment by waruqi** [comment]
target:set("version", "1.1")

**Comment by tim-lebedkov** [comment]
This works. Now I want to use the version number as a define, but this doesn't

```Lua
	add_defines("UNICODE", "_UNICODE", "NPACKD_VERSION=\"" + target:get("version") + "\"")`
```

**Comment by waruqi** [comment]
target:add("defines", "UNICODE", "_UNICODE", "NPACKD_VERSION=\"" + target:get("version") + "\"")`

**Comment by tim-lebedkov** [comment]
Your line generates an error:

error: attempt to perform arithmetic on a string value

**Comment by waruqi** [comment]
please let me see your xmake.lua

**Comment by waruqi** [comment]
You need to use `..` instead of `+` to concatenate strings, this is the string concatenation syntax of lua script.

```lua
target:add("defines", "UNICODE", "_UNICODE", "NPACKD_VERSION=" .. target:get("version"))
```

**Comment by tim-lebedkov** [comment]
Thank you. That was it. 

I have one more question though: what should I use instead of "set_configvar" inside of "on_load"? BTW, what is the reason to disallow all this at the top level?

**Comment by waruqi** [comment]
target:set("configvar", "xxx", "vvv")

> BTW, what is the reason to disallow all this at the top level?

see https://xmake.io/#/guide/syntax_description?id=configuration-separation

**Comment by tim-lebedkov** [comment]
I don't like the 2 domains (configuration and code). It is confusing and more complicated than having just one. I doubt this helps in simple cases as they would look exactly the same if everything would be code. It hurts in more complex cases. BTW, I don't even consider my requirements as complex, but I had problems implementing them. 

target:set("configvar",...) seems also to not be a part of the public API.

**Comment by waruqi** [comment]
`target:set()` is the public api and it can set all target config items, e.g.    `target:set("xx", "yy")` -> set_xx("yy")
