### ISSUE TITLE
Handle CMAKE_GENERATOR being set to unsupported generator

### ISSUE THREAD

**Issue by paul-reilly** [xmake-io/xmake#965]
I had an error installing the `libuv` package, Windows 10/MSVC:
```
CMake Error at CMakeLists.txt:3 (project):
  Generator
    Ninja
  does not support platform specification, but platform
    x64
  was specified.
```
This is because I have the `CMAKE_GENERATOR` env variable set to `Ninja` but xmake currently only supports using msbuild when using cmake to build packages, this particular error just came earlier than it would have if Ninja supported setting platforms.

I fixed it in [cmake.lua](https://github.com/xmake-io/xmake/blob/ef86cee77a2cb6cdb3449b48ce33cb8123933a8c/xmake/modules/package/tools/cmake.lua#L35) with:
```lua
-- get configs for windows
function _get_configs_for_windows(package, configs)
    local vsvers = {
        ["2019"] = "16",
        ["2017"] = "15",
        ["2015"] = "14",
        ["2013"] = "12",
        ["2012"] = "11",
        ["2010"] = "10",
        ["2008"] = "9"
    }

    -- if a default cmake generator is set and is not a supported generator, set generator to Visual Studio
    local cmake_gen = os.getenv("CMAKE_GENERATOR")
    if cmake_gen and cmake_gen:find("Visual Studio") == nil then
        local vs = config.get("vs")
        assert(vsvers[vs], "Unknown Visual Studio version: '" .. tostring(vs) .. "' set in project.")
        table.insert(configs, "-G")
        table.insert(configs, "Visual Studio " .. vsvers[vs] .. " " .. vs)
    end
 ```
Which could be expanded to include `Ninja Multi-Config` at some point too. But this doesn't fix this potential error on other hosts/platforms.

It might be better to unset/reset `CMAKE_GENERATOR` around the calls to cmake for now...
https://github.com/xmake-io/xmake/blob/ef86cee77a2cb6cdb3449b48ce33cb8123933a8c/xmake/modules/package/tools/cmake.lua#L263-L264

https://github.com/xmake-io/xmake/blob/ef86cee77a2cb6cdb3449b48ce33cb8123933a8c/xmake/modules/package/tools/cmake.lua#L300

To enforce the expected default on all platforms, or there's something else I haven't thought about that would work better.

**Comment by waruqi** [comment]
I have improved it and merged your patch. https://github.com/xmake-io/xmake/commit/3d8633b429950b6605e20563f5e324ea13a037bb

we can choose which generator or cmake/build.

```lua
-- use default generator and call msvc/make to build/install package
import("package.tools.cmake").install(package, configs)

-- use Ninja generator and call ninja to build/install package
import("package.tools.cmake").install(package, configs, {cmake_generator = "Ninja"})

-- use Ninja generator and call cmake/--build/--install to build/install package
import("package.tools.cmake").install(package, configs, {cmake_generator = "Ninja", cmake_build = true})
```

**Comment by paul-reilly** [comment]
Nice!

I'll give it a good test run later!

**Comment by paul-reilly** [comment]
The logic for checking the env variable `CMAKE_GENERATOR` has been removed so the initial issue is still present.

Running CMake without specifying a generator means that it uses the default. This is VS/msbuild on Windows. Users can set the environment variable eg `CMAKE_GENERATOR=Ninja`, permanently if they like, to tell CMake to always use another generator _if one has not been specified_.

Also, with Ninja, unless we use `Ninja Multi-Config` we need to run CMake once for each build type with [CMAKE_BUILD_TYPE](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html).

**Comment by waruqi** [comment]
> The logic for checking the env variable CMAKE_GENERATOR has been removed so the initial issue is still present.
> Running CMake without specifying a generator means that it uses the default.

Why? `cmake.install(.. {cmake_generator = "Ninja"})` will pass `cmake -G Ninja` to use ninja generator. 

Why does cmake still use the default generator? It works fine for me.

```lua
import("package.tools.cmake").install(package, configs, {cmake_generator = "Ninja"})
```

**Comment by paul-reilly** [comment]
The issue is that xmake assumes VS/msbuild with:
```
import("package.tools.cmake").install(package)
```
But when the env var [`CMAKE_GENERATOR`](https://cmake.org/cmake/help/latest/envvar/CMAKE_GENERATOR.html) is set to "Ninja" then Cmake will always use Ninja, unless a different one is specified with `-G`.

So building xmake-repo packages that use CMake on Windows, such as libuv, fails with this env var set to Ninja.

In the code I posted I:

- check if CMAKE_GENERATOR is set
     - if it is set, check it is a supported build system: ie VS (or now Ninja)
        - if not, set -G"Visual Studio [PROJECT VS VERSION]" to force using VS

Or we could unset CMAKE_GENERATOR around the build to remove its influence.

**Comment by waruqi** [comment]
> The issue is that xmake assumes VS/msbuild with:
> 
> ```
> import("package.tools.cmake").install(package)
> ```
> 
> But when the env var [`CMAKE_GENERATOR`](https://cmake.org/cmake/help/latest/envvar/CMAKE_GENERATOR.html) is set to "Ninja" then Cmake will always use Ninja, unless a different one is specified with `-G`.
> 
> So building xmake-repo packages that use CMake on Windows, such as libuv, fails with this env var set to Ninja.
> 
> In the code I posted I:
> 
> * check if CMAKE_GENERATOR is set
>   
>   * if it is set, check it is a supported build system: ie VS (or now Ninja)
>     
>     * if not, set -G"Visual Studio [PROJECT VS VERSION]" to force using VS
> 
> Or we could unset CMAKE_GENERATOR around the build to remove its influence.

So please use `import("package.tools.cmake").install(package, configs, {cmake_generator = "Ninja"})` for libuv/windows.

```lua
package("libuv")
    on_install("windows", function (package)
        import("package.tools.cmake").install(package, configs, {cmake_generator = "Ninja"})
    end)
```

**Comment by waruqi** [comment]
> This is because I have the CMAKE_GENERATOR env variable set to Ninja but xmake currently only supports using msbuild when using cmake to build packages, this particular error just came earlier than it would have if Ninja supported setting platforms.

Oh, I may have misunderstood what you mean, the external CMAKE_GENERATOR variable should not affect tools/cmake.lua. I need to unset CMAKE_GENERATOR

**Comment by paul-reilly** [comment]
Yes, that's the issue.

**Comment by waruqi** [comment]
I have improved it, you can try it again. (dev)

**Comment by paul-reilly** [comment]
The `-A` flag is incompatible with the Ninja generator:

https://github.com/xmake-io/xmake/blob/4b906d273d9bfb0b51f5f0d16f3dfa0f4f5676a7/xmake/modules/package/tools/cmake.lua#L36-L40

Ninja follows the arch for the environment that it's run in, eg with vcvars / VsDevCmd.bat.

Speaking of the environment, I notice a very good feature of xmake is that it finds the paths of Visual Studio etc so it does not have to be run in a Developer Command Prompt, or have vcvars run. Ninja is not on that list at the moment:

>CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.

Which does _not_ happen when run in a Developer Command Prompt, but is something to think about.

One last potential error is if CMAKE_GENERATOR is set to an unsupported type eg:

```powershell
$env:CMAKE_GENERATOR="CodeBlocks - Ninja"
```
... which would result in an error. This also shows that checking for Ninja means that any `:find("Ninja"....` needs to check that the result starts at 1 (and is not "Ninja Multi-Config").

Here are all the generators with the word "Ninja" in them:

```
Ninja
Ninja Multi-Config
CodeBlocks - Ninja
CodeLite - Ninja
Sublime Text 2 - Ninja
Kate - Ninja
Eclipse CDT4  - Ninja
```

**Comment by waruqi** [comment]
> The -A flag is incompatible with the Ninja generator:
> One last potential error is if CMAKE_GENERATOR is set to an unsupported type eg:

I have fixed these issues.

**Comment by waruqi** [comment]
> CMake Error: CMake was unable to find a build program corresponding to "Ninja". CMAKE_MAKE_PROGRAM is not set.

> Which does not happen when run in a Developer Command Prompt, but is something to think about because this is a really good feature.

I will look at it later.

**Comment by paul-reilly** [comment]
I have encountered a problem with using Ninja as a user default with packages from xmake-repo.

**Problem:**
- there is no guarantee that a CMake script creates an `install` target
- CMake `install` targets do not have to use `CMAKE_INSTALL_LIBDIR`

See this for an example of two install options that are both unsuitable for each of these reasons:
https://github.com/cnjinhao/nana/blob/master/build/cmake/install_nana.cmake

So a package would:
- need to be able to declare "no Ninja install" or similar
- have to have post-build steps just for Ninja

**Solution:**
- Ignore `CMAKE_GENERATOR`, always use msbuild unless Ninja is explicitly requested?

**Comment by waruqi** [comment]
Now I always set the cmake generator explicitly to avoid being affected by $CMAKE_GENERATOR

**Comment by paul-reilly** [comment]
Excellent, it is now using msbuild when `CMAKE_GENERATOR=Ninja`. Good stuff.

That's this issue resolved!
