### ISSUE TITLE
win32: copy package LIB file to install dir?

### ISSUE THREAD

**Issue by RussellHaley** [xmake-io/xmake#966]
Hi, this is a follow up to your answer in https://github.com/xmake-io/xmake/issues/961

How do I copy the link lib file for the dll?

```
target "lua54-lib"
    set_basename ("lua54")
    set_kind ("shared")
    set_installdir(root_install_dir.."Lua/5.4/")
    add_installfiles(lua54_src.."*.h", {prefixdir = "include"})
    add_defines("LUA_BUILD_AS_DLL")
    add_includedirs(lua54_src)
    add_files (lua54_src.."*.c")
    del_files (lua54_src.."lua.c", lua54_src.."luac.c")
    on_install(function (target)
        os.cp(target:targetfile(), path.join(target:installdir(), "bin"))
        os.cp(target:basename()..".lib", path.join(target:installdir(), "bin"))
    end);
```
```
error: install failed, cannot copy file lua54.lib, not found this file
```

(By the way, the error message should be 'file not found' instead of 'not found this file'.)

**Comment by waruqi** [comment]
>         os.cp(target:basename()..".lib", path.join(target:installdir(), "bin"))

```
os.cp(path.join(target:targetdir(), target:basename()..".lib"), path.join(target:installdir(), "bin"))
```

**Comment by waruqi** [comment]
> (By the way, the error message should be 'file not found' instead of 'not found this file'.)

I have modified it.

**Comment by RussellHaley** [comment]
Thanks! I've been using cmake for the past few months and it's like a breath of fresh air using xmake again.
