### ISSUE TITLE
更新dev版本后windows平台cmake生成的makefile与platform不匹配

### ISSUE THREAD

**Issue by Biobots** [xmake-io/xmake#967]
### 描述问题

更新dev版本后windows平台cmake生成的makefile与platform不匹配，应该是mingw，生成了vs工程。

https://github.com/xmake-io/xmake/blob/151998405503c71004ef7e6642c6d2dbd94fd39b/xmake/modules/package/tools/cmake.lua#L197

不知这里是否是拼写错误？

**Comment by waruqi** [comment]
白天的改动导致的笔误 我一会改下 ，或者你可以提个pr帮忙改下
