### ISSUE TITLE
make uninstall doesn't uninstall everything

### ISSUE THREAD

**Issue by stsp** [xmake-io/xmake#970]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
make uninstall only removes /usr/local/share/xmake
but /usr/local/bin/xmake is still there.

### Expected behavior
Should remove everything that "make install" installed.

### Error output
If applicable, please add verbose the errors output to help us analyze your problem.

> If it is a xmake related compilation problem, please add the `-v -D` parameter and give the detailed compilation output information.

### Related Environment

Please provide compiling and running environment information:

- xmake version: git
- os: linux
- target platform: x86_64

**Comment by waruqi** [comment]
I have fixed it on dev branch.

**Comment by stsp** [comment]
Thanks, its working now.
Btw, your commits have trailing
white-space errors.

**Comment by waruqi** [comment]
trailing white-spaces?  I do not found any errors. `make uninstall` works fine for me.

https://github.com/xmake-io/xmake/commit/eb0434f929fd00e69bb5710bd1ab0f950b59e1b8

**Comment by stsp** [comment]
I looked also at 0a16fbb6, it really
has white-space errors in many places.
But its not a problem, can all be fixed
with a sed script. :)

**Comment by waruqi** [comment]
I have fixed it. https://github.com/xmake-io/xmake/commit/90af4956738036172984f068502624bbc515cae7

**Comment by stsp** [comment]
Thanks!
Quite a big patch. :)

**Comment by waruqi** [comment]
BTW, what problems can the trailing blank cause you? Because I have never encountered any problems here, I didn't deal with them before.

**Comment by stsp** [comment]
They are highlighted by git log and
by text editors. In fact, IIRC even
`git am` will prodice loud warnings
when encountering them.

**Comment by waruqi** [comment]
ok, got it.
