### ISSUE TITLE
xmake v2.3.7 --- vcpkg无法支持，老版本可以的

### ISSUE THREAD

**Issue by Ultraman95** [xmake-io/xmake#971]
xmake.lua
add_requires("vcpkg::yaml-cpp", {configs = {vs_runtime = "MD"}})

error:
checking for the Microsoft Visual Studio (x86) version ... 2019
error: ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:47: only support static libraries with /MT[d] for vcpkg!
stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:792: in function 'raise'
        ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:47: in function 'co_start_named'
        @programdir\modules\private\async\runjobs.lua:180: in function <@programdir\modules\private\async\runjobs.lua:139>
        [C]: in function 'trycall'
        @programdir\core\base\scheduler.lua:423: in function 'co_group_begin'
        ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:85: in function 'co_group_begin'
        @programdir\modules\private\async\runjobs.lua:139: in function 'runjobs'
        @programdir\actions\require\impl\package.lua:755: in function 'install_packages'
        @programdir\actions\require\install.lua:162: in function 'install_requires'
        @programdir\actions\config\main.lua:272: in function <@programdir\actions\config\main.lua:138>
        [C]: in function 'load'
        @programdir\core\base\task.lua:520: in function 'run'
        @programdir\core\main.lua:282: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>

**Comment by waruqi** [comment]
只是加了个严格的配置检测，默认安装的是 静态库版本，你 vs_runtime 切到 MD，只是改了依赖的运行时库到动态版本，但是安装的还是静态库，两者是冲突的。。

你要用 MD ，那个 vcpkg 的包 也得安装动态库，得切到动态库配置上去`shared = true`。。

```
add_requires("vcpkg::yaml-cpp", {configs = {shared = true, vs_runtime = "MD"}})
```

**Comment by Ultraman95** [comment]
改了之后，xmake build，成功了
但是xmake project -k vsxmake -m "debug,release" -a x86 生成vs2019工程，编译报错：
1>checking for the Microsoft Visual Studio (x86) version ... 2019
1>note: try installing these packages (pass -y to skip confirm)?
1>in builtin-repo:
1>  -> 7z 18.05
1>please input: y (y/n)
1>EXEC : error : packages(7z): must be installed!
1>C:\Program Files\xmake\plugins\project\vsxmake\vsproj\Xmake.targets(97,5): error MSB3073: 命令“
1>C:\Program Files\xmake\plugins\project\vsxmake\vsproj\Xmake.targets(97,5): error MSB3073:       chcp 65001 > NUL
1>C:\Program Files\xmake\plugins\project\vsxmake\vsproj\Xmake.targets(97,5): error MSB3073:       pushd D:\Works\Market\nxMarket\xmake\qmarketTest\
1>C:\Program Files\xmake\plugins\project\vsxmake\vsproj\Xmake.targets(97,5): error MSB3073:       set XMAKE_CONFIGDIR=D:\Works\Market\nxMarket\xmake\qmarketTest
1>C:\Program Files\xmake\plugins\project\vsxmake\vsproj\Xmake.targets(97,5): error MSB3073:       set XMAKE_PROGRAM_DIR=C:\Program Files\xmake
1>C:\Program Files\xmake\plugins\project\vsxmake\vsproj\Xmake.targets(97,5): error MSB3073:       set XMAKE_SKIP_HISTORY=1
1>C:\Program Files\xmake\plugins\project\vsxmake\vsproj\Xmake.targets(97,5): error MSB3073:     
1>C:\Program Files\xmake\plugins\project\vsxmake\vsproj\Xmake.targets(97,5): error MSB3073:       "C:\Program Files\xmake\xmake.exe" config -P . -p windows -m debug -a x86 -o "build"”已退出，代码为 -1。
1>已完成生成项目“qmarketTest.vcxproj”的操作 - 失败。

**Comment by waruqi** [comment]
> 1>in builtin-repo:
1> -> 7z 18.05
1>please input: y (y/n)
1>EXEC : error : packages(7z): must be installed!

检测到7z没装所以失败了。。

手动切到 `xmake f -c -a x86 -m debug` 看看会触发 7z安装么。。

**Comment by Ultraman95** [comment]
不行，而且没办法输入y，一下子就过去了，没时间输入y

**Comment by Ultraman95** [comment]
如何手动安装呢，安装到哪儿呢？怎么更新了一下xmake版本就感觉各种报错了

**Comment by waruqi** [comment]
你更新的正式版？还是dev版本？

**Comment by Ultraman95** [comment]
正式版本

**Comment by waruqi** [comment]
正式版本应该没啥太大改动，就是之前的版本做一些补丁修复，我这里按你的步骤测试了下  一切正常，并没有你的问题。。

7z这个，是在 %localappdata%\Local\.xmake\packages\7\7z 里面，可以确认下装了没有。。


默认是不会去装这个的，只有 add_requires 存在，首次编译才需要，因为要下载依赖包去解压。。。而你这里已经build通过了，按理不会再出现这个问题的。。

你可以 `xmake f -c` 清下cache，或者手动 删下 .xmake 试试

**Comment by waruqi** [comment]
还是不行么？执行下面的命令给我看下完整输出呢？

```console
xmake f -c -vD
xmake project -k vsxmake -m "debug,release" -a x86 -vD
```

**Comment by Ultraman95** [comment]
![1601001509(1)](https://user-images.githubusercontent.com/1725360/94220324-4977a880-ff1b-11ea-9955-3836ae36222a.png)
![1601001557(1)](https://user-images.githubusercontent.com/1725360/94220381-61e7c300-ff1b-11ea-8cde-32b0c755875f.png)

**Comment by Ultraman95** [comment]
![1601001649(1)](https://user-images.githubusercontent.com/1725360/94220471-9c516000-ff1b-11ea-8981-9fff713969c5.png)

**Comment by waruqi** [comment]
哦，编译错误哈，我以为你创建出错。。

```console
xmake clean -P . -a qmarketTest
xmake config -P . -p windows -m debug -a x86 -o build 
```

你手动执行下里面显示的这两命令呢，看看

如果复现后，在执行下 下面的，给我看下详细输出

```console
xmake clean -P . -a qmarketTest -vD
xmake config -P . -p windows -m debug -a x86 -o build -c -vD
```

**Comment by Ultraman95** [comment]
没有用，vs工程报同样的错误，xmake build没有问题

**Comment by waruqi** [comment]
所以我要看错误信息

**Comment by Ultraman95** [comment]
第一个命令无法执行xmake clean -P . -a qmarketTest -vD

**Comment by Ultraman95** [comment]
![image](https://user-images.githubusercontent.com/1725360/94228868-9023cd80-ff30-11ea-9091-ef40259c011c.png)

**Comment by Ultraman95** [comment]
![image](https://user-images.githubusercontent.com/1725360/94228924-b0538c80-ff30-11ea-8990-6bfd23964b52.png)

**Comment by waruqi** [comment]
> 第一个命令无法执行xmake clean -P . -a qmarketTest -vD

你给的图只截了上半截 我看不到最下面的错误信息

不加 -c -vD的结果呢 我也看下

> xmake clean -P . -a qmarketTest
> xmake config -P . -p windows -m debug -a x86 -o build 
> 你手动执行下里面显示的这两命令呢，看看

> 如果复现后，在执行下 下面的，给我看下详细输出

**Comment by waruqi** [comment]
如果方便的话 也可以搞个能复现的demo工程，直接打包发但github issues附件 我看看能否复现

**Comment by waruqi** [comment]
另外你之前的版本号多少，c:/programdirs 和 programdirs (x86)安装目录下 确认下，是否只安装了一个xmake包

**Comment by Ultraman95** [comment]
只装了一个

**Comment by Ultraman95** [comment]
[qmarketTest.zip](https://github.com/xmake-io/xmake/files/5281584/qmarketTest.zip)
这个就是

**Comment by Ultraman95** [comment]
我这个demo是只支持x86的

**Comment by waruqi** [comment]
好的，等晚上我看下

**Comment by waruqi** [comment]
我大概知道问题，跟2.3.7版本没啥关系，是你这环境变动过了。。

背景：
目前add_requires的使用在windows上必须要下载 7z 来支持依赖包的  tar.gz 解压，所以如果7z不存在就会首次提示装下。。

但是如何用户的环境中，xmake 检测到 tar/gzip这两个工具已经存在，也可以用来解压 tar.gz 那就没必要额外安装7z了。。

你这里的问题是：

你的终端环境检测到 tar/gzip存在了，如下图，所以 xmake config 和创建vs工程过程中，没有提示下载7z

但是你在vs里面执行xmake编译，这个时候脱离了你的终端环境，所以检测不到 gzip/tar，触发了 xmake 提示下载 7z 的逻辑

解决方案有几种：

1.  你开个不带gzip/tar到path的 cmd 终端，里面执行下 xmake f -c ，强制触发7z提示安装，你手动装下，装好就没事了
2. 打开vs里面工程属性页，有个xmake专门的配置属性也，可以里面追加 `-y` 的自定义配置，强制在vs编译中触发 7z 的自动下载安装（不推荐）

![Snip20200925_1](https://user-images.githubusercontent.com/151335/94252311-5665bd80-ff56-11ea-8b89-bdce062d0697.png)

**Comment by waruqi** [comment]
我改进过了，对于win下的xmake安装包，我把内置的unzip.exe切换到了 7z.exe，也就不会提示安装它了。。

最新安装包请到这里下载尝试：

https://github.com/xmake-io/xmake/actions/runs/280772581
