### ISSUE TITLE
print projectdir

### ISSUE THREAD

**Issue by pchaos** [xmake-io/xmake#973]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题
文件 xmake.lua:

target("test")
    if is_mode("debug") then 
        set_kind("static")
    else
        set_kind("shared")
    end
    local s = format("工程目录: $(projectdir), $(curdir)")
    print(s)
 
执行 xmake结果：
工程目录: $(projectdir), $(curdir)
工程目录: $(projectdir), $(curdir)
工程目录: $(projectdir), $(curdir)
工程目录: $(projectdir), $(curdir)
工程目录: $(projectdir), $(curdir)
工程目录: $(projectdir), $(curdir)

$(projectdir), $(curdir) 没有打印出真实的值

### 期待的结果

打印出变量$(projectdir), $(curdir) ，正确的路径

### 错误信息

如果可能，请尽量附加程序运行过程中的错误输出信息。

> 如果是xmake相关编译问题，请加上`-vD`参数运行，并给出详细编译输出信息。

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.3.7+202009222359
- xmake运行平台：fedora 30
- xmake目标平台：linux

### 其他信息

The information of xmake:
    version: 2.3.7+202009222359
    host: linux/x86_64

The information of project: 
    plat: linux
    arch: x86_64
    mode: release
    buildir: build
    configdir: /tmp/.xmake/linux/x86_64
    projectdir: /tmp
    projectfile: /tmp/xmake.lua

**Comment by waruqi** [comment]
看下描述域文档最底下说明 https://xmake.io/#/zh-cn/guide/syntax_description?id=%e6%8f%8f%e8%bf%b0%e5%9f%9f

不要在描述域做print调试，请在on_load等脚本域操作

我后续会考虑描述域直接禁用print接口了，避免乱用

**Comment by pchaos** [comment]
类似$(projectdir), $(curdir)这样的变量能在描述域使用吗？

**Comment by waruqi** [comment]
> 类似$(projectdir), $(curdir)这样的变量能在描述域使用吗？

原本就是给描述域用的，只是不要用print在描述域调试，要调请到脚本域调。
