### ISSUE TITLE
import 导入失败

### ISSUE THREAD

**Issue by KellyGodLv** [xmake-io/xmake#975]
我想在xmake.lua中使用 local msbuild = find_tool("msbuild", {envs = runenvs})
发现似乎不能使用  import 会出现
error: @programdir\core\project\project.lua:994: .\xmake.lua:1: attempt to call global 'import' (a nil value)
stack traceback:
    [.\xmake.lua:1]: in main chunk

**Comment by waruqi** [comment]
请先阅读下xmake文档描述域和脚本域相关部分介绍：https://xmake.io/#/zh-cn/guide/syntax_description

然后再脚本域中使用 import

**Comment by KellyGodLv** [comment]
测试了下可以了 太方便了，项目分不同场景自动打包
