### ISSUE TITLE
无法在控制台下使用xmake run -d开始调试

### ISSUE THREAD

**Issue by littlewater** [xmake-io/xmake#983]
按照教程上的说明xmake run -d是可以进入调试的，但是我自己实际操作了一下发现没有成功，提示如下：
~/src/testxmk0$ xmake run -d
GNU gdb (Ubuntu 9.1-0ubuntu1) 9.1
<-----省略----->
Reading symbols from /home/xxxxx/src/testxmk0/build/linux/x86_64/debug/testxmk0...
error: execv(/usr/bin/gdb --args /home/xxxxx/src/testxmk0/build/linux/x86_64/debug/testxmk0) failed(-1)

另外，我在vscode里面直接调用运行调试都没有问题，我认为我安装xmake应该没有问题，还有xmake run是正常的，还有直接调用/usr/bin/gdb --args /home/xxxxx/src/testxmk0/build/linux/x86_64/debug/testxmk0，也是不会这样报错的，如下：
GNU gdb (Ubuntu 9.1-0ubuntu1) 9.1
<------ 省略 ------>
For help, type "help".
Reading symbols from /home/xxxxx/src/testxmk0/build/linux/x86_64/debug/testxmk0...
(gdb) 

各种信息：
- xmake version: 2.37
- os: Ubuntu 20.04 LTS
- target platform: Ubuntu 20.04 LTS

**Comment by waruqi** [comment]
dev分支上我修复了，你更新后再试试

**Comment by littlewater** [comment]
好的，不过我当时安装是从deb上直接安装好的，还没有看过和试过编译，可能确认时间要久一点。

**Comment by waruqi** [comment]
只需要

```console
xmake update dev
source ~/.xmake/profile
```

或者到action ci下载对应平台的安装包：https://github.com/xmake-io/xmake/actions/runs/289050862

**Comment by littlewater** [comment]
对的，我今天再看其他教学的时候才想起来内置了update的功能。去试试。

**Comment by littlewater** [comment]
xmake v2.3.7+202010060805, A cross-platform build utility based on Lua
更新到这个版本了，测试已经没有问题了，感谢。

顺便一问，我现在想要回到master去，实验了一下update master，结果还是这个10060805的版本，命令如下：
`
xmake update master
update version master from official source ..
  => download https://gitee.com/tboox/xmake.git .. ok
  => install to ~/.local/bin .. ok
`
原来我是觉得应该都是下载到本地编译出新的程序，但是master的分支好像没效果还是怎么？
是不是我得手动删除~/.local/bin/xmake的这个程序了？看了一下入门到精通1的说明好像没提到。

**Comment by waruqi** [comment]
最近的master和dev差别不大 我刚同步过  顶多差几个commit，10060805是时间戳，编译c core时候决定的，所以两个时间相同也是可能的 你应该已经更新过去了
