### ISSUE TITLE
Add Support for `c11` and `c17` for MSVC Version 16.8 and Above

### ISSUE THREAD

**Issue by RoyiAvital** [xmake-io/xmake#986]
Microsoft will soon add `c11` and `c17` support for it `MSVC`. For reference see [C11 and C17 Standard Support Arriving in MSVC](https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc/).

In case of `xmake` recognizes `MSVC 16.8` and above it should map the `c_std` parameter to the `MSVC` equivalent.  
For lower versions it should say the feature is invalid.

**Comment by waruqi** [comment]
I have supported for them.

```lua
set_languages("c11")
set_languages("c17")
```

**Comment by RoyiAvital** [comment]
Do you mean for `MSVC` version 16.8?

**Comment by waruqi** [comment]
Yeah, I have tested it. It works fine for msvc 16.8 preview.

If the lower version of msvc is not supported, it will automatically ignore them. `/std:c17` ..
