### ISSUE TITLE
Windows 10 下头文件更新不触发重编译

### ISSUE THREAD

**Issue by wicast** [xmake-io/xmake#987]
### 描述问题
建了一个测试用的项目： https://github.com/wicast/headerTest
main.cpp 依赖 S.h，修改 S.h 的输出内容，xmake 不触发重编译，cmake 会触发编译。

Windows 10手头有两台一台是scoop.sh安装、一台是官网installer安装，两台都出现问题，试过dev版问题依旧。cmd、powershell、gitbash均无法触发重编译。
而Linux测试没有这个问题，手头没mac没法测试

### 期待的结果
触发重编译

### 错误信息
直接build 100% 未触发重编译

### 相关环境

- xmake版本：v2.3.7+202009141205
- xmake运行平台：win10
- xmake目标平台：win10

**Comment by waruqi** [comment]
这是后来支持上msvc新版本的 头文件依赖 report json 文件解析导致的问题，cl.exe 的 /sourceDependencies 生成的头文件依赖路径都给自动转成了小写。

而你这的路径目录，以及 S.h 都是有大写的，所以xmake在解析时候就出现了问题。现在dev上我修复了。。你再试试

https://github.com/xmake-io/xmake/issues/868

**Comment by wicast** [comment]
最新的dev可以了，感谢修复
