### ISSUE TITLE
包含同名.o的静态库，链接到可执行程序出错

### ISSUE THREAD

**Issue by LeopardDing** [xmake-io/xmake#991]
**xmake.lua如下：**
add_rules("mode.debug", "mode.release")

-- target("hello")
--     set_kind("static")
--     add_files("src/**.c")
--     del_files("src/main.c")

target("main")
    set_kind("binary")
    add_files("src/main.c")
    add_files("build/linux/x86_64/release/libhello.a")

**错误信息如下：**
jack@jack:~/xmakeTest/sample$ xmake -vD
[ 40%]: inserting.release build/linux/x86_64/release/libhello.a
❗ error: @programdir/modules/private/async/runjobs.lua:210: ...mdir/core/sandbox/modules/import/core/tool/extractor.lua:41: @programdir/modules/core/tools/ar.lua:96: object name(iic.c.o) conflicts in library: /home/jack/xmakeTest/sample/build/linux/x86_64/release/libhello.a
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:792]: in function 'raise'
    [@programdir/modules/core/tools/ar.lua:96]:
    [C]: in function 'extract'
    [...mdir/core/sandbox/modules/import/core/tool/extractor.lua:39]: in function 'extract'
    [@programdir/rules/utils/merge_archive/xmake.lua:63]: in function 'script'
    [@programdir/actions/build/kinds/object.lua:43]: in function 'jobfunc'
    [@programdir/modules/private/async/runjobs.lua:188]:
    [C]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:121]: in function 'try'
    [@programdir/modules/private/async/runjobs.lua:182]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:317]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:792: in function 'raise'
	@programdir/modules/private/async/runjobs.lua:210: in function 'catch'
	@programdir/core/sandbox/modules/try.lua:127: in function 'try'
	@programdir/modules/private/async/runjobs.lua:182: in function 'cotask'
	@programdir/core/base/scheduler.lua:317: in function <@programdir/core/base/scheduler.lua:315>

**尝试解决方法：**
add_linkdirs("build/linux/x86_64/release")
add_links("hello")
如果静态库不是libxxx.a的格式，怎么链接？求教！！！

**Comment by waruqi** [comment]
自身target依赖请用add_deps("hello") ，外部库用add_links/add_linkdirs

add_files里面加.a 是用来重新拆包做merge的 不是link

**Comment by LeopardDing** [comment]
嗯，谢了。特殊名称的库可以用add_links(":xxxx.a")来链接。库文件名前加冒号

**Comment by waruqi** [comment]
你这个demo只需要add_deps("hello") 会自动link，并且确保依赖的构建顺序，用不到add_links
