### ISSUE TITLE
`xmake install` as the very first invocation for a phony project that only installs will result in root owned `cache/history`

### ISSUE THREAD

**Issue by jschwartzenberg** [xmake-io/xmake#993]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
When `xmake install` is ran for the very first time with a phony project that has no build phase, just an install phase, it will create `.xmake/linux/x86_64/cache/history` as root and this file will be owned by root when telling xmake to proceed when administrator privileges are requested.

### Expected behavior
This file should be owned by the user starting xmake.

### Error output
Not applicable. Next invocations will show problems.

> If it is a xmake related compilation problem, please add the `-v -D` parameter and give the detailed compilation output Please provide compiling and running environment information:

- xmake version: v2.3.7+202010041035
- os: Parabola
- target platform: Parabola AMD64

**Comment by waruqi** [comment]
I cannot reproduce your problem here, can you give me a reproducible xmake.lua and a complete xmake execution command?

this is my xmake.lua.

```
target("test")
    set_kind("phony")
    on_install(function (target)
        io.writefile(path.join(target:installdir(), "lib", "libtest.a"), "")
    end)
```

Then we run `$ xmake install --admin`, but it works fine for me.

```console
$ rm -rf .xmake
$ xmake install --admin
$ ls -l .xmake/linux/x86_64/cache/history 
-rw-r--r-- 1 ruki ruki 181 Oct 15 01:31 .xmake/linux/x86_64/cache/history
```

**Comment by waruqi** [comment]
I rolled back to the online version 2.3.7, and it did reproduce your problem. This problem does not exist on the master/dev branch. 

In addition, in the next version, we have improved `xmake install` and disabled the interactive installation process. By passing the `--admin` parameter, we request administrator privileges to install the program.

online v2.3.7

```console
$ xmake install        
checking for the architecture ... x86_64
install
note: try continue to install with administrator permission again (pass -y or --confirm=y/n/d to skip confirm)?
please input: y (y/n)
```

next version (dev/master):

If the installation directory requires administrator rights, we need to manually pass the `--admin` parameter to perform the installation

```console
$ xmake install --admin
install ok
```

If the `--admin` parameter is not passed, the installation does not have permission, and there will be a prompt message.

```console
$ xmake install 
error: install failed, cannot open file: /usr/local/lib/libtest.a, Permission denied
warning: please pass the --admin parameter to `xmake install` to request administrator permissions!
```

**Comment by waruqi** [comment]
Therefore, you don’t need to care about this issue, this issue will not exist in the next version, and we will release a new version in the last two weeks.

You can also manually update to the master/dev version to test and verify this problem.

```console
xmake update dev
source ~/.xmake/profile
```

**Comment by jschwartzenberg** [comment]
That's great news!! Thank you very much for checking it out!! Glad to know it will be fixed soon!
