### ISSUE TITLE
How to install conan package when to compile with '-p mingw' on Windows?

### ISSUE THREAD

**Issue by rel1ve** [xmake-io/xmake#994]
xmake v2.3.7

log as below: 
>xmake f -p mingw -v -D -y
checking for the architecture ... x86_64
checking for the mingw directory ... C:\mingw64
checking for the unzip ... ok
checking for the git ... ok
checking for the gzip ... no
checking for the 7z ... ok
checking for the ping ... ok
pinging for the host(gitee.com) ... 26 ms
checking for the nmap ... no
pinging for the host(gitlab.com) ... 65535 ms
pinging for the host(github.com) ... 65535 ms
finding cryptopp/1.0.0@lanxum/testing from conan ..
checking for the CONAN::cryptopp/1.0.0@lanxum/testing ... no
installing cryptopp/1.0.0@lanxum/testing from conan ..
checking for the conan ... ok
generate E:\src\SP1800_V1-trunk\SafePrinterClient\ConfigManage\build\.conan\cryptopp\1.0.0@lanxum\testing\conanfile.txt ..
error: ...ramdir\modules\package\manager\conan\install_package.lua:176: cannot install package(cryptopp/1.0.0@lanxum/testing) on platform(mingw)!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:788]: in function 'raise'
    [...ramdir\modules\package\manager\conan\install_package.lua:176]: in function '_install_package'
    [@programdir\modules\package\manager\install_package.lua:109]:
    [@programdir\core\package\package.lua:1185]: in function 'script'
    [@programdir\actions\require\impl\utils\filter.lua:120]: in function 'call'
    [@programdir\actions\require\impl\action\install.lua:142]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\actions\require\impl\action\install.lua:126]: in function 'install'
    [@programdir\actions\require\impl\package.lua:617]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:190]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:187]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

  => install CONAN::cryptopp/1.0.0@lanxum/testing  .. failed
error: @programdir\modules\private\async\runjobs.lua:213: @programdir\actions\require\impl\action\install.lua:249: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:788]: in function 'raise'
    [@programdir\actions\require\impl\action\install.lua:249]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
    [@programdir\actions\require\impl\action\install.lua:126]: in function 'install'
    [@programdir\actions\require\impl\package.lua:617]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:190]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:187]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
	[C]: in function 'error'
	@programdir\core\base\os.lua:788: in function 'raise'
	@programdir\modules\private\async\runjobs.lua:213: in function 'catch'
	@programdir\core\sandbox\modules\try.lua:127: in function 'try'
	@programdir\modules\private\async\runjobs.lua:187: in function 'cotask'
	@programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>

**Comment by waruqi** [comment]
I have not tested the installation of the conan package on mingw, maybe some changes are needed to support it.

https://github.com/xmake-io/xmake/blob/d482b1f6dc82ed80161600f2697ca33183dd02a2/xmake/modules/package/manager/conan/install_package.lua#L170-L177

https://github.com/xmake-io/xmake/blob/d482b1f6dc82ed80161600f2697ca33183dd02a2/xmake/modules/package/manager/conan/find_package.lua#L31-L34

**Comment by waruqi** [comment]
I will support mingw in the next version.

**Comment by waruqi** [comment]
I have supported it for mingw on windows. `xmake update dev`
