### ISSUE TITLE
编译C/C++代码如何指定链接脚本

### ISSUE THREAD

**Issue by zwxf** [xmake-io/xmake#995]
请问下，编译C/C++语言如何指定特定的链接脚本，嵌入式开发很经常会链接自己定义的链接脚本，而不是编译器默认的链接脚本，我好像没看到这方面的设置信息，麻烦确认下是否有，如果没有能否添加这个功能？感谢。

**Comment by waruqi** [comment]
自己通过add_ldflags/add_shflags设置 跟 makefile的LDFLAGS类似

**Comment by zwxf** [comment]
> 
> 
> 自己通过add_ldflags/add_shflags设置 跟 makefile的LDFLAGS类似

那不同编译器需要不同的链接脚本，编译过程就需要根据当前的编译器类型，选择不同的链接脚本，编译过程可以获取到编译器类型的信息吗？

**Comment by waruqi** [comment]
默认`add_ldflags`的所有设置，xmake都会自动检测，当前编译器不支持的就会自动忽略，所以即使不判断全部设置上也没啥。

另外，尽量使用抽象的跨编译器接口，不用操心编译器差异，例如：`set_optimize("fast")`, `set_languages("c++17")`, `set_strip("all")`，add_links,add_linkdirs 等等

只有，特殊情况才用 add_ldflags/add_cflags来原始配置。

如果要判断，简单的，就直接通过平台判断，除了常用的iphoneos/linux/windows/macos等平台，用户可以设置任意自己的嵌入式平台，来配置交叉编译，例如：

```console
xmake f -p sunos --sdk=/xxx
```

```lua
target("test")
    set_kind("binary")
    add_files("src/*.c")
    if is_plat("myplat") then
        add_ldflags("xxx")
    end
```

也可以通过 `is_arch()` 来判断，如果非要根据编译器来判断，可以再 on_load 里面通过 `import("core.tool.compiler")` 模块获取所有编译器信息，来各种判断。。

```lua
target("test")
    set_kind("binary")
    add_files("src/*.c")
    on_load(function (target)
        import("core.tool.compiler")
        local name = compiler.load("cc"):name()
        if name == "gcc" then
            target:add("ldflags", "xxx")
        end
    end)
```

master/dev 版本提供了新的直接获取编译器名的接口，更加方便点


```lua
target("test")
    set_kind("binary")
    add_files("src/*.c")
    on_load(function (target)
        local name = import("core.tool.compiler").name()
        if name == "gcc" then
            target:add("ldflags", "xxx")
        end
    end)
```

这块可以参考：

https://github.com/xmake-io/xmake/blob/d482b1f6dc82ed80161600f2697ca33183dd02a2/xmake/rules/c%2B%2B/openmp/load.lua#L22-L41


关于compiler/linker模块的接口，可以看下文档：https://xmake.io/#/zh-cn/manual/extension_modules?id=coretoolcompiler

不过不全，也可以直接到代码中看完整接口：https://github.com/xmake-io/xmake/blob/master/xmake/core/sandbox/modules/import/core/tool/compiler.lua

**Comment by waruqi** [comment]
如果不想导入额外的compiler模块，`target:tool("cc")` 也可以快速获取编译器名

```
target("test")
    set_kind("binary")
    add_files("src/*.c")
    on_load(function (target)
        local _, name = target:tool("cc")
        if name == "gcc" then
            target:add("ldflags", "xxx")
        end
    end)
```

> armcc我按照：https://xmake.io/#/zh-cn/manual/custom_toolchain这里面来做发现并不能用

custom toolchain 肯定是能用的，只是你还不会，xmake里面的所有的内部 toolchains 也是这么定义的。

> 想参考sdcc实现下，发现还得重新编译源码，

不需要，将里面`toolchain("sdcc")`定义配置，放到工程 xmake.lua 里面就行了，只不过xmake内置了一些toolchains而已，用户完全可以自己配置定义自己的toolchain

> MDK的armcc是否有添加的计划

可以单独提feature requres 到issues，但支持时间不确定，看我个人时间安排。

**Comment by zwxf** [comment]
感谢，那我这几天再看看！
