### ISSUE TITLE
Implement vcpkg for Linux

### ISSUE THREAD

**Issue by paul-reilly** [xmake-io/xmake#996]
I notice that vcpkg can't be found when attempting to use a vcpkg package on Linux and I see that there's a TODO in `find_vcpkgdir.lua` for finding vcpkg on non-Windows systems.

Is adding Linux support for vcpkg part of the short term plans?

**Comment by waruqi** [comment]
I can consider improving it.

**Comment by paul-reilly** [comment]
Excellent news, thanks!

**Comment by waruqi** [comment]
I have improved to find it from $PATH, if the vcpkg directory is added to $PATH

**Comment by paul-reilly** [comment]
Nice one, that's it working and automatically installing missing vcpkg packages just like in Windows. Cheers!
