### ISSUE TITLE
CMake: set_languages("c++17"), language not set in CMakeLists.txt

### ISSUE THREAD

**Issue by paul-reilly** [xmake-io/xmake#997]
Create an xmake project with:
```
set_languages("c++17")
```

Create a CMakeLists.txt project file with xmake:
```
xmake project -k cmake
```

The resulting CMakeLists.txt does not have the language standard set for the target, eg:

```
target_compile_features(my_target PRIVATE cxx_std_17)
```

**Comment by waruqi** [comment]
I have supported it on dev branch. You can try it again.

**Comment by paul-reilly** [comment]
That's it fixed, thanks!
