### ISSUE TITLE
Dealing with wasm html shell output

### ISSUE THREAD

**Issue by elitepleb** [xmake-io/xmake#999]
### Describe the problem details
My wasm build abused naming `target("output.html")` and using `add_ldflags("--shell-file ./shell/shell_minimal.html")`.
This would produce a proper html output file that dealt with the {{{ SCRIPT }}} tag.

The recent update added `set_formats("binary", "$(name).js")` for platform WASM giving the linker `output.html.js` instead.
Because the linker checks if the output file ends with .html for --shell-file, it no longer makes the shell file.
https://emscripten.org/docs/compiling/Deploying-Pages.html#build-files-and-custom-shell

Should there also be a `set_formats("shell", "$(name).html")` ?
I am not sure what's the proper solution to this.

**Comment by waruqi** [comment]
I have renamed `$(name).js` to `$(name).html` on dev branch, because I found that `.js/.wasm` files will also be generated at the same time as long as .html files are generated.

You can also use `set_filename` to modified file extension in xmake.lua manually for 2.3.8 version.

```lua
target("test")
    set_filename("test.html")
    add_ldflags("--shell-file shell.html")
```

**Comment by elitepleb** [comment]
Thanks for that, it works great!

Since a default shell is provided if the `add_ldflags("--shell-file shell.html")` is omitted
there should be no problems just having the linker make a .html file by default for binary targets.
